### ISSUE TITLE
There is no `SDL_ReadS8`

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10008]
There exists `SDL_ReadU8`, but no `SDL_ReadS8`.

https://github.com/libsdl-org/SDL/blob/96bb06d9c703061db8e7b156515dfa37af6720d7/include/SDL3/SDL_iostream.h#L626

Would a `SDL_ReadS8` make sense?

Or is one expected to use [`SDL_ReadIO`](https://github.com/libsdl-org/SDL/blob/96bb06d9c703061db8e7b156515dfa37af6720d7/include/SDL3/SDL_iostream.h#L501) to read a single character/signed 8-byte integer?

**Comment by slouken** [comment]
Sure, it makes sense to add that for completeness.
