### ISSUE TITLE
[Regression (again)] Metal YUV rendering broken on Intel MacOS

### ISSUE THREAD

**Issue by olekolek1000** [libsdl-org/SDL#10006]
I was going to report a very similar YUV format issue related to internal webcam capture on MacOS (green tint and double vision), but on the way I encountered this:

![Untitled](https://github.com/libsdl-org/SDL/assets/29149078/70e4cfbc-4a0f-4be1-92b7-b64d9e2cf01a)

It's probably highly related to the resolved issue I reported before: [issue](https://github.com/libsdl-org/SDL/issues/9367)

Steps to reproduce: Run `testcamera` on Intel Macbook (2015 in this case). MacOS 12.7.2 (the newest one available for this hardware)

**Comment by olekolek1000** [comment]
Bisecting (again)...

**Comment by olekolek1000** [comment]
It's quite hard to bisect `testcamera` due to various bugs in the previous commits (SIGABRT), trying again with `drawchessboard` which is also completely black

**Comment by slouken** [comment]
I ran testcamera on an Intel MacBook 2019, running macOS 14.5, and it worked with no issues.

Does everything except testcamera work? If so, what are the inputs and outputs to the `CoreMediaFormatToSDL()` function?

**Comment by olekolek1000** [comment]
Yes, tested `testdrawchessboard` and `testgeometry`, both run without any issues.
I've hooked up a printf() just under `CoreMediaFormatToSDL()` in `GatherCameraSpecs` function, it prints out these formats:
SDL_PIXELFORMAT_YUY2
SDL_PIXELFORMAT_UYVY
SDL_PIXELFORMAT_NV12
SDL_PIXELFORMAT_YUY2
SDL_PIXELFORMAT_UYVY
SDL_PIXELFORMAT_NV12
SDL_PIXELFORMAT_YUY2
SDL_PIXELFORMAT_UYVY
SDL_PIXELFORMAT_NV12

**Comment by olekolek1000** [comment]
> Just to be clear, this is happening if you explicitly use the _software renderer_ and not OpenGL or Metal?

Let me check, one moment

**Comment by olekolek1000** [comment]
> Just to be clear, this is happening if you explicitly use the _software renderer_ and not OpenGL or Metal?

Yup, that's it!
`SDL_RENDER_DRIVER` software and opengl works as intended, Metal is broken.

Texture renders correctly now (when it comes to the display itself, the color space of the camera is a different issue that I was originally going to report):
![Untitled](https://github.com/libsdl-org/SDL/assets/29149078/45f6a598-f425-457e-95d4-a0d9168ce451)

**Comment by olekolek1000** [comment]
`testdrawchessboard` and `testgeometry` both work OK on this laptop, in all three video backends (metal, gl, software).

**Comment by slouken** [comment]
> Yes, tested `testdrawchessboard` and `testgeometry`, both run without any issues. I've hooked up a printf() just under `CoreMediaFormatToSDL()` in `GatherCameraSpecs` function, it prints out these formats: SDL_PIXELFORMAT_YUY2 SDL_PIXELFORMAT_UYVY SDL_PIXELFORMAT_NV12 SDL_PIXELFORMAT_YUY2 SDL_PIXELFORMAT_UYVY SDL_PIXELFORMAT_NV12 SDL_PIXELFORMAT_YUY2 SDL_PIXELFORMAT_UYVY SDL_PIXELFORMAT_NV12

Do you know which of these formats is actually used when you're getting frames from the camera?

**Comment by olekolek1000** [comment]
> Do you know which of these formats is actually used when you're getting frames from the camera?

`SDL_PIXELFORMAT_UYVY`, grabbed from `next_frame` just below `SDL_AcquireCameraFrame()`

**Comment by icculus** [comment]
> SDL_PIXELFORMAT_UYVY

The Metal renderer doesn't support this format, so it's something in the fallback code (GetClosestSupportedFormat or something down the line from that in SDL_CreateTextureWithProperties) that's probably blowing up.

**Comment by slouken** [comment]
Yeah, I tested with testyuv --uyvy and it worked with the metal renderer, so this needs more investigation.

**Comment by slouken** [comment]
I was able to reproduce this.  There were two problems. The first is that we were trying to use a YUV shader with an RGB texture, which caused the graphical corruption and occasional crash. The second is that we were using default frame output settings, which converted the YUVY frame to NV12.

**Comment by icculus** [comment]
> which converted the YUVY frame to NV12.

Oh, I think Sylvain mentioned something about how Apple was giving NV12 data when you ask for YUVY data in the original pull request...! Mystery solved!

**Comment by 1bsyl** [comment]
yes, indeed something gets fixed. Previous SDL3 version didn't work on macosx for me with an external camera, and now that's ok.
