### ISSUE TITLE
 SDL3 static link fail when making a shared object without SDL_STATIC_PIC

### ISSUE THREAD

**Issue by loicmagne** [libsdl-org/SDL#10004]
Ubuntu 24.04, I'm trying to statically link SDL3 to build a shared module. When I follow the [official guide](https://wiki.libsdl.org/SDL3/README/cmake#including-sdl-in-your-project), I get the following error:

```
/usr/bin/ld: deps/SDL/libSDL3.a(SDL_x11dyn.c.o): warning: relocation against X11_XDisplayKeycodes' in read-only section .text'
/usr/bin/ld: deps/SDL/libSDL3.a(SDL_video.c.o): relocation R_X86_64_PC32 against symbol `Wayland_bootstrap' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

This is resolved by turning SDL_STATIC_PIC on, I don't know if it's a problem specific to my setup but maybe this should be specified in the guide FAQ ?

**Comment by madebr** [comment]
I think it's better to remove the `SDL_STATIC_PIC` option and let people use `CMAKE_POSITION_INDEPENDENT_CODE` instead.
There's no need for adding our own abstractions.
(And document this in `README-cmake.md`.)

**Comment by loicmagne** [comment]
> I think it's better to remove the `SDL_STATIC_PIC` option and let people use `CMAKE_POSITION_INDEPENDENT_CODE` instead. There's no need for adding our own abstractions. (And document this in `README-cmake.md`.)

`SDL_STATIC_PIC` already defaults to `CMAKE_POSITION_INDEPENDENT_CODE` but yeah maybe it could be simply removed https://github.com/libsdl-org/SDL/blob/4fc68a48f20574326eb18022eed0b7c0fa52a10e/CMakeLists.txt#L370

**Comment by madebr** [comment]
It's removed in dd0bb25f6625d240fea2844731685355e424bbea
`CMAKE_POSITION_INDEPENDENT_CODE` is documented [here](https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md#linking-against-a-static-sdl-library-fails-due-to-relocation-errors)

**Comment by loicmagne** [comment]
> It's removed in [dd0bb25](https://github.com/libsdl-org/SDL/commit/dd0bb25f6625d240fea2844731685355e424bbea) `CMAKE_POSITION_INDEPENDENT_CODE` is documented [here](https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md#linking-against-a-static-sdl-library-fails-due-to-relocation-errors)

Very cool thanks!
