### ISSUE TITLE
SDL2 SDL_Keycode returns characters in current keyboard layout

### ISSUE THREAD

**Issue by eszdman** [libsdl-org/SDL#10002]
System:
```
OS: Arch Linux x86_64
Kernel: 6.9.3-arch1-1 
DE: Plasma 6.0.5 
Graphics Platform: Wayland
```
Same issue using X11.

When I get SDL_Keycode from key press event I get symbols in keyboard layout at startup, this means that this doesn't correspond to a SDL_Keycode value in the enumeration.

Examples for qwertyuiop keys range:

Startup with en-US selected layout works as intended
```
keycode: 113
keycode: 113
keycode: 119
keycode: 119
keycode: 101
keycode: 101
keycode: 114
keycode: 114
keycode: 116
keycode: 116
keycode: 121
keycode: 121
keycode: 117
keycode: 117
keycode: 105
keycode: 105
keycode: 111
keycode: 111
keycode: 112
keycode: 112
```

Startup with ru-RU selected layout causes incorrect recognition of pressed buttons

```
keycode: 1081
keycode: 1081
keycode: 1094
keycode: 1094
keycode: 1091
keycode: 1091
keycode: 1082
keycode: 1082
keycode: 1077
keycode: 1077
keycode: 1085
keycode: 1085
keycode: 1075
keycode: 1075
keycode: 1096
keycode: 1096
keycode: 1097
keycode: 1097
keycode: 1079
keycode: 1079

```

Is it supposed to work like this or is it a bug since I can't recognize which buttons were pressed using SDL_Keycode enum?

**Comment by slouken** [comment]
If you want to know what the key would be on an en-US keyboard, you can use the function `SDL_GetDefaultKeyFromScancode()` which was introduced in SDL3 for exactly this purpose.

FYI, SDL3 also removes the SDL_Keycode enum and turns the type into Uint32, so it's more clear that it's not a predefined set of values, the keycode can be any printable key on the keyboard.

**Comment by ocornut** [comment]
> If you want to know what the key would be on an en-US keyboard, you can use the function SDL_GetDefaultKeyFromScancode() which was introduced in SDL3 for exactly this purpose.

FYI `SDL_GetDefaultKeyFromScancode()` was removed 3 months later by c298a3749b68122d985fe504127a9bcb72b40111, which is fine as the new key map functions can provide equivalent features. Just pointing this out in case someone else stumbles on this.
