### ISSUE TITLE
SDL_ReadU32LE vs SDL_SwapLE32: location of LE suffix is inconsistent

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10007]
SDL defines `SDL_ReadU32LE` for reading a little-endian 32-bit integer:
https://github.com/libsdl-org/SDL/blob/96bb06d9c703061db8e7b156515dfa37af6720d7/include/SDL3/SDL_iostream.h#L706

but defines `SDL_SwapLE32`
https://github.com/libsdl-org/SDL/blob/96bb06d9c703061db8e7b156515dfa37af6720d7/include/SDL3/SDL_endian.h#L502
https://github.com/libsdl-org/SDL/blob/96bb06d9c703061db8e7b156515dfa37af6720d7/include/SDL3/SDL_endian.h#L511

Would it make sense to name the latter `SDL_Swap32LE` instead?

**Comment by slouken** [comment]
Possibly? @icculus, thoughts?

**Comment by icculus** [comment]
They were both `LE32` in SDL2; we changed the `Read` functions for SDL3, so we should definitely make these match again.
