### ISSUE TITLE
Hint for using RawInput for mouse?

### ISSUE THREAD

**Issue by sam20908** [libsdl-org/SDL#10016]
TL;DR: A way to capture mouse motion outside of the window without needing relative mode.

The rationale is that there's a corresponding hint for the keyboard, but the mouse requires much more work...

I closed my attempt due to https://github.com/libsdl-org/SDL/pull/10013#issuecomment-2165910148

**Comment by slouken** [comment]
Have you looked at SDL_CaptureMouse()? That’s exactly what it’s for.

**Comment by sam20908** [comment]
> This function may also deny mouse input to other windows--both those in your application and others on the system--so you should use this function sparingly, and in small bursts

That isn't what I want.

**Comment by slouken** [comment]
It sounds like you just want to track the global mouse position. Have you checked out SDL_GetGlobalMouseState()?

**Comment by sam20908** [comment]
I want the motion. I currently have my own raw input and send the events to the sdl hand, but I just thought since sdl has the raw input infrastructure maybe this is a nice addition

**Comment by slouken** [comment]
Ah, as you can see it doesn't work the way you'd want, for various reasons. @expikr has a number of bugs and pull requests related to this that we'll review for SDL3 release.

**Comment by sam20908** [comment]
Okay, I found out this wouldn't do what I want either, so I'm going to close this and roll my own RawInput. If someone else wants it they can create an issue :D

**Comment by sam20908** [comment]
I needed to get the input events regardless of whether the window has focus or not, and I realized that is probably out of scope for SDL.

**Comment by slouken** [comment]
In this particular case, it seems like directly using raw input is the right solution.
