### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by sechshelme** [libsdl-org/SDL#10027]
I have another extension suggestion for SDL3. A function that can generate random numbers, I think this is something that is needed in almost every game.

This would allow us to move away from `<stdlib.h>` even further.

**Comment by slouken** [comment]
We discussed this and concluded that an application that wants good random numbers will pick an implementation that meets their needs: https://github.com/libsdl-org/SDL/issues/4968

**Comment by slouken** [comment]
This is implemented in https://github.com/libsdl-org/SDL/commit/d1d484ddbef2ad3a5bb243388ef9e47fac021f50.

**Comment by sechshelme** [comment]
Thanks
