### ISSUE TITLE
[Question][SDL3/testffmpeg] How can do 'SDL_RenderFillRect' on video frame?

### ISSUE THREAD

**Issue by jskimn** [libsdl-org/SDL#10022]
I am trying to draw rectangle on video frame like below code, but I can not get any result.
Render device type is D3D11 and I can display video frame.
Is it impossible to draw rectangle on YUV texture?

**//Test code fragments in testffmpeg.c**
void drawRect(SDL_Renderer* renderer)
{
    //SDL_RenderClear(renderer);
    SDL_FRect viewport;
    SDL_GetRenderViewport(renderer, &viewport);

    SDL_Rect rect;
    rect.x = 0;
    rect.y = 0;
    rect.w = 500;
    rect.h = 500;
    //SDL_SetRenderViewport(renderer, &viewport);
    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
    //SDL_RenderRect(renderer, &rect);
    int status = SDL_RenderFillRect(renderer, &rect);

    //SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    //SDL_RenderPresent(renderer); 
}

static void HandleVideoFrame(AVFrame *frame, double pts)
{
     ~~
    /* Render any bouncing balls */
    MoveSprite();
   
    //
    drawRect(renderer);

    SDL_RenderPresent(renderer);
     ~~~
}

**Comment by slouken** [comment]
That seems like it should work. Does running with `--sprites 10` show bouncing smiley faces in MoveSprite()?

**Comment by jskimn** [comment]
Hi, Slouken,
I checked with "--sprites 10" option and I got following screen shot.
![screenshot](https://github.com/libsdl-org/SDL/assets/58724183/f61ea562-df5e-4abb-815e-4855803a6fbd)

I will refer codes that is related with "--sprites 10" option.
thanks.

**Comment by jskimn** [comment]
> Your code looks like it shouldn't compile. SDL_RenderFillRect() takes an SDL_FRect pointer, not SDL_Rect.

Oops...I got it.
I will close this issue.
