### ISSUE TITLE
Turn SDL_GLContext into an opaque type

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10025]
Currently, SDL_GLContext is defined as a void pointer typedef:

https://github.com/libsdl-org/SDL/blob/51902d4ac53ca7ef46baff38e75deec98321667d/include/SDL3/SDL_video.h#L203

Would it make sense to define it as an opaque struct typedef instead?
```c
typedef struct struct_SDL_GLContext *SDL_GLContext;
```

[In this recent issue](https://github.com/libsdl-org/SDL/issues/10023), a user is using the wrong type as an argument of `SDL_GL_MakeCurrent`, for which the compiler does not warn (even with `-Wall -Wextra`).

**Comment by slouken** [comment]
I don't think SDL will compile if you make that change, but you're welcome to try it.

**Comment by madebr** [comment]
I grep'ed around in the SDL headers and could find these void pointer typedefs:
https://github.com/libsdl-org/SDL/blob/51902d4ac53ca7ef46baff38e75deec98321667d/include/SDL3/SDL_video.h#L210-L212
https://github.com/libsdl-org/SDL/blob/51902d4ac53ca7ef46baff38e75deec98321667d/include/SDL3/SDL_metal.h#L44

All of these could benefit from the added type safety, but users will need explicitly add a cast when using native GL/Metal/macos types.

**Comment by slouken** [comment]
The EGL types are actually `void *`. The metal one is `void *` so it can be easily assigned to a Metal view in Objective C code.
