### ISSUE TITLE
Set gain value in audio streams

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#10028]
Hello, I think it would be useful to set a gain value per audio stream that can be modified dynamically like frequency ratio.
Not sure if this is not implemented for a reason but I would like to ask.

`int SDL_SetAudioStreamGainRatio(SDL_AudioStream* stream, float ratio);`

`float SDL_GetAudioStreamGainRatio(SDL_AudioStream* stream);`

Thanks

**Comment by icculus** [comment]
I think we were just trying to find a point to stop adding features, but this _would_ be useful and (probably) not difficult.
