### ISSUE TITLE
macOS: SDL_LEAN_AND_MEAN is incompatible with SDL_render_metal

### ISSUE THREAD

**Issue by mekhontsev** [libsdl-org/SDL#10038]
SDL_render_metal.m is not compatible with undefined SDL_HAVE_YUV (and defined SDL_LEAN_AND_MEAN)
because [interface METAL_TextureData](https://github.com/libsdl-org/SDL/blob/4e5ed569c3c80f6d10e958ba6a32a254da7d2535/src/render/metal/SDL_render_metal.m#L154) does not have "yuv" and "nv12" properties which are used unconditionally [later in the file](https://github.com/libsdl-org/SDL/blob/4e5ed569c3c80f6d10e958ba6a32a254da7d2535/src/render/metal/SDL_render_metal.m#L758).

**Comment by slouken** [comment]
Fixed, thanks!
