### ISSUE TITLE
Is it right use the same value for the left right rumble in SDL/src/joystick/hidapi/SDL_hidapi_switch.c

### ISSUE THREAD

**Issue by qingwa2009** [libsdl-org/SDL#10034]
I found the switch pro controller use the same value for the left and right rumble, is it right or mistake? 

   if (low_frequency_rumble || high_frequency_rumble) {
        EncodeRumble(&ctx->m_RumblePacket.rumbleData[0], k_usHighFreq, k_ucHighFreqAmp, k_ucLowFreq, k_usLowFreqAmp);
        EncodeRumble(&ctx->m_RumblePacket.rumbleData[1], k_usHighFreq, k_ucHighFreqAmp, k_ucLowFreq, k_usLowFreqAmp);
    } else {
        SetNeutralRumble(&ctx->m_RumblePacket.rumbleData[0]);
        SetNeutralRumble(&ctx->m_RumblePacket.rumbleData[1]);
    }

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/blob/63138c79af23ae1a5903f9949a87d8a91b04dbd1/src/joystick/hidapi/SDL_hidapi_switch.c#L1514-L1520

**Comment by slouken** [comment]
I believe this is correct, but I'm not an expert on Switch rumble values. Maybe @TellowKrinkle has some insight here?

**Comment by TellowKrinkle** [comment]
The two rumble motors are identical, so they don't really correspond to high/low frequency.  Just a question of whether you want the rumble felt more on the left side of the controller or the right, which isn't part of SDL's gamepad rumble API.
