### ISSUE TITLE
CMake: SDL3 headers not found on macOS

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10035]
It seems that after some lines have been removed from sdl3-config.cmake the header files are no longer found on my project. Simply re-adding them fixed the issue. I suggest the appended patch:
[headers.txt](https://github.com/user-attachments/files/15856429/headers.txt)

**Comment by madebr** [comment]
The removal was intentional.
You need to include SDL3 headers as `#include <SDL3/SDL.h>`, not `#include "SDL.h"`

**Comment by andreasgrabher** [comment]
What is the reason for this change? Are there any benefits? It is a bit annoying, especially when keeping optional SDL2 support for a while. Am 16.06.2024 um 14:12 schrieb Anonymous Maarten ***@***.***>:﻿
The removal was intentional.
You need to include SDL3 headers as #include <SDL3/SDL.h>, not #include "SDL.h"

**Comment by slouken** [comment]
This is so code can be compiled on all platforms without changes. Apple frameworks require this.

**Comment by sezero** [comment]
> What is the reason for this change? Are there any benefits?

It unifies the way of including SDL3 headers on all platforms.

Previously, some people included SDL2 (and SDL1) headers like `"SDL.h"`
while others used `"SDL2/SDL.h"` or `<SDL2/SDL.h>` or `<SDL.h>`, sometimes
out of necessity (e.g. on with Apple frameworks) or sometimes for lack of
knowledge.

**Comment by andreasgrabher** [comment]
Is this really tve case? My application uses <SDL.h> and works on macOS, Windows, NetBSD and several Linux distros.

**Comment by madebr** [comment]
When not using cmake or pc, people need to explicitly add the SDL3 include path.
For certain packages, such as Xcode projects using the frameworks or Android studio using android archives, this is not easily done.
- in the xcode project, you'd need to add an explicit `-I /Frameworks/SDL3.xcframework/macos-arm64-x86_64/SDL3.framework/Headers`
- for the android archive, using prefab, there's no way to get the path of the extracted files so you'd need to add the headers twice (to support both include methods)

But isn't your SDL2 and SDL3 code path currently sufficiently diverged that an extra `#ifdef` for the headers won't matter much? Perhaps a `sdl2_sdl3.h` "abstraction header" is needed?

**Comment by andreasgrabher** [comment]
Up till now I could simply use #if SDL_MAJOR_VERSION == n (n being 2 or 3) to simply distinguish between SDL2 and SDL3. That is no longer possible. There are other ways for sure, but it just makes things more complicated now. If at least it was SDL/SDL.h it would make things more straightforward.

**Comment by slime73** [comment]
> If at least it was SDL/SDL.h it would make things more straightforward.

Wouldn't that cause all sorts of issues when people try to compile code written for SDL1 or SDL2 or SDL3 with any of the other two libraries also installed?

**Comment by andreasgrabher** [comment]
I think it was best the way it was until recently. I have SDL2 and SDL3 installed and there are no conflicts.

**Comment by slime73** [comment]
How SDL2 did things worked for some workflows and toolchains, but required changes for others (as was pointed out) which ended up causing issues.

If your code is compatible with both SDL2 and SDL3 and you don't already have a project-wide define you use to determine whether to use SDL2 versus SDL3, another option is to use the has_include preprocessor operator to help pick which header to include.
