### ISSUE TITLE
SDL_SetRelativeMouseMode specific to a window

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#10041]
It would be useful to be allowed to specify a window when calling SDL_SetRelativeMouseMode.

For example someone might have a game window where the relative mouse mode should be on, and another debug-editing window where the relative mouse mode should be off.

I guess you could work around this enabling/disabling the relative mouse mode depending on the current focused window but in my opinion the change I suggested would make the API more clear and effective.

**Comment by slouken** [comment]
Done! Thanks for the suggestion.
