### ISSUE TITLE
Why is SDL3's version 2.30.x

### ISSUE THREAD

**Issue by bit7** [libsdl-org/SDL#10043]
Who is running the show around here?  When I download source code for SDL3 the version should be 3.x.  Am I wrong?

**Comment by slime73** [comment]
Where are you downloading SDL3 from? It's not released yet so there aren't official binaries in the same spot as the 2.x releases.

**Comment by bit7** [comment]
I was looking for the source code.

https://wiki.libsdl.org/SDL3/SourceCode
At the web page above when you click the link to the source code it brings you to 2.30.3
I thought for sure I read somewhere that 3.0 was out.  Now I can't find that page.

I think I have the madness.  Sorry everybody!

**Comment by slouken** [comment]
Thank you for the heads up! I clarified on the wiki that there aren't any public releases yet.
