### ISSUE TITLE
SDL2 2.30.2 fullscreen shows only blank screen on Debian Linux testing (trixie) 

### ISSUE THREAD

**Issue by cslr** [libsdl-org/SDL#10050]
On Linux, SDL 2.30.3 shows only blank screen when fullscreen. I'm using multithreaded code and using mutex to synchronize SDL access (mostly from one thread). In windowed mode screen is updated without problems.

uname -a:
Linux whiteice 6.7.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.12-1 (2024-04-24) x86_64 GNU/Linux

dpkg -l libsdl2-2.0-0:
ii  libsdl2-2.0-0:amd64 2.30.3+dfsg-1 amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:i386  2.30.3+dfsg-1 i386         Simple DirectMedia Layer

dpkg -l libsdl2-dev:
ii  libsdl2-dev:amd64 2.30.3+dfsg-1 amd64        Simple DirectMedia Layer development files

**Comment by haydentech** [comment]
Are you checking the return value on your update calls?  I had a very similar problem, and it was due to calling SDL functions from different threads.  In my case, the SDL update calls were failing with a "Unable to make GL context current" error.

**Comment by slouken** [comment]
You must call update from the main thread.
