### ISSUE TITLE
SDL3 Camera Frame Rate Limited to 20 FPS on Apple M1

### ISSUE THREAD

**Issue by qqiu** [libsdl-org/SDL#10051]
I'm experiencing an issue where the camera frame rate is limited to 20 FPS on the Apple M1 chip, despite setting the camera to operate at 30 FPS. The camera is capable of supporting up to 60 FPS.

In contrast, the same camera and settings achieve 30 FPS on the Apple M2 chip.

**Comment by icculus** [comment]
We just pushed some camera framerate fixes a few minutes ago; can you retest with the latest in revision control?

**Comment by qqiu** [comment]
I retested with the most recent version and encountered an error stating "camera spec format error not available" when trying to open the camera. Upon reviewing the latest updates, it appears that the function ChooseBestCameraSpec() is not selecting an appropriate colorspace.

**Comment by olekolek1000** [comment]
Can confirm.

testcamera:
```
./build/test/testcamera
2024-06-25 14:19:53.089 testcamera[2694:932729] INFO: Saw 2 camera devices.
2024-06-25 14:19:53.089 testcamera[2694:932729] INFO:   - Camera #0:  FaceTime HD Camera
2024-06-25 14:19:53.089 testcamera[2694:932729] INFO:   - Camera #1:  OBS Virtual Camera
2024-06-25 14:19:54.123 testcamera[2694:932729] DEBUG: Cannot create AVCaptureDeviceInput
2024-06-25 14:19:54.123 testcamera[2694:932729] INFO: Failed to open camera device: Cannot create AVCaptureDeviceInput
2024-06-25 14:19:54.123 testcamera[2694:932729] DEBUG: Parameter 'camera' is invalid
2024-06-25 14:19:54.123 testcamera[2694:932729] DEBUG: Parameter 'texture' is invalid
```

SDL_GetError(): `camera spec format not available`

**Comment by slouken** [comment]
What is the device format and colorspace? Why are they different now from when they were enumerated?

**Comment by olekolek1000** [comment]
Looks like colorspace and format is swapped in the code:

```printf("SPEC: colorspace %u, format %u, device_colorspace %u, device_format %u\n", spec->colorspace, spec->format, device_format, device_colorspace);```

```SPEC: colorspace 554697761, format 842094158, device_colorspace 842094158, device_format 554697761```

colorspace 554697761 = BT709
colorspace 842094158 = it's a format (NV12)

format 842094158 = NV12
format 554697761 = it's a colorspace (BT709)

**Comment by olekolek1000** [comment]
Looks like it doesn't pass if spec->colorspace is set to 0 in COREMEDIA_OpenDevice, but i'm properly setting it to a non-zero value in SDL_OpenCameraDevice. Investigating further...

**Comment by olekolek1000** [comment]
> I retested with the most recent version and encountered an error stating "camera spec format not available" when trying to open the camera. Upon reviewing the latest updates, it appears that the function ChooseBestCameraSpec() is not selecting an appropriate colorspace.

Yup, that's it, closest->colorspace is never set in ChooseBestCameraSpec function if we request a specific camera spec in SDL_OpenCameraDevice.

**Comment by olekolek1000** [comment]
Fixed it, merge request will be soon
