### ISSUE TITLE
Issue with Rate Selection in COREMEDIA_OpenDevice Due to Float Comparison

### ISSUE THREAD

**Issue by qqiu** [libsdl-org/SDL#10053]
In the COREMEDIA_OpenDevice function, there's a problem when selecting a supported rate because the comparison between the rate and the rate range is inaccurate. For example, if the rate is 30 and both the minimum and maximum rates are 30.002, the function fails to select a suitable rate. It might be better to use integers instead of floats for comparing rates.

**Comment by slouken** [comment]
Fixed, thanks!
