### ISSUE TITLE
SDL1.x - which version supports NT3.1 or Win3.1?

### ISSUE THREAD

**Issue by Torinde** [libsdl-org/SDL#10065]
SDL 2004 website [FAQ What Platforms are Supported](https://web.archive.org/web/20041211005740/http://www.libsdl.org/cgi/docwiki.cgi/FAQ_20What_20Platforms_20are_20Supported) is not archived and I can't find information which version (if any) of SDL supports those:
- Windows NT3.1
- Windows 3.1x with Win32s

Closest I found is [here](https://www.vogons.org/viewtopic.php?p=710400#p710400):
> Lowest SDL 1.2.13 supports is 95 (original) (unknown about betas) and NT 3.50 (Have to disable fullscreen support and use 3.51 joystick dll.)

**Comment by icculus** [comment]
I'm not sure that NT3.1 or Win32s was _ever_ supported; that vogons.org post was saying that the author had personally patched it to work on NT3.1 (and that HX DOS Extender could run his Win95 build with its Win32s support). It's not impossible that the windib video backend would work on those platforms without changes, but even the winmm audio code needs to spin a thread internally, so it might work on ancient WinNT, but it's likely a non-starter on win32s in any case.

But there are fallbacks for platforms without DirectX at all, so with work one could probably get it running, maybe disabling audio.

SDL 1.2 (even the latest in revision control, afaik) should still work on Windows 95 and WinNT 4.0, but no one here is testing these platforms any more (or SDL 1.2 at all, really, at this point).
