### ISSUE TITLE
SDL_RELEASED and SDL_PRESSED

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10069]
Do we want to make these into an enum, or just replace them with an SDL_bool?

```c
/* General keyboard/mouse state definitions */
#define SDL_RELEASED    0
#define SDL_PRESSED     1
```

**Comment by slouken** [comment]
I think where they're used in the event, the type is Uint8, which isn't compatible with either an enum or an SDL_bool. I'm not opposed to changing this, but the names make code clearer when reading it, so if we change it to an SDL_bool I'd probably still want the symbols around, defined to SDL_TRUE and SDL_FALSE. Application code passes these values around in various types so I wouldn't want to make it an enum.
