### ISSUE TITLE
Documentation: clarify how hidpi affects mouse scaling

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#10074]
README-hidpi.md does not mention anything about how display scaling will influence SDL's mouse input scaling. 

There should be a comprehensive clarification about how each hint and dpi configuration interacts with the events which are posted, with concrete cases for various game types (FPS, hardware-cursor RTS, software-cursor rhythm games etc) and how users can set their OS settings or envvars to override developer oversights.

**Comment by slouken** [comment]
It does not affect mouse input. Those units don't change.

A comprehensive guide sounds good, but probably not something we'll have time to write as we work towards SDL 3.0 release. Please feel free to create a PR with one you've written.
