### ISSUE TITLE
SDL_timer.h: canceling a timer vs removing a timer 

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10079]
The documentation of the timer callback and functions that create timers say the timer is cancelled when it returns 0.
https://github.com/libsdl-org/SDL/blob/53eff7f9038b28e8eba9052a1804c7b3d659dd28/include/SDL3/SDL_timer.h#L140
https://github.com/libsdl-org/SDL/blob/53eff7f9038b28e8eba9052a1804c7b3d659dd28/include/SDL3/SDL_timer.h#L166-L167
https://github.com/libsdl-org/SDL/blob/53eff7f9038b28e8eba9052a1804c7b3d659dd28/include/SDL3/SDL_timer.h#L203
https://github.com/libsdl-org/SDL/blob/53eff7f9038b28e8eba9052a1804c7b3d659dd28/include/SDL3/SDL_timer.h#L229-L230

But `SDL_RemoveTimer` talks about removing a timer.
https://github.com/libsdl-org/SDL/blob/53eff7f9038b28e8eba9052a1804c7b3d659dd28/include/SDL3/SDL_timer.h#L261

I suppose canceling and removing a timer means the same thing, but I think the documentation should clarify this.

Also, the documentation mixes USA's `canceled` and UK's `cancelled`.

The reason I'm opening this issue is because an error occurs when a timer is removed that was cancelled:
https://github.com/libsdl-org/SDL/blob/cf267e49855c435743b25d649ea2dcbefe0d30db/test/testautomation_timer.c#L163-L165

**Comment by slouken** [comment]
Fixed, thanks!
