### ISSUE TITLE
 KEYBOARD_IGNOREMODIFIERS 0x08 vs. 0x0

### ISSUE THREAD

**Issue by sechshelme** [libsdl-org/SDL#10089]
Is this a typo or is it intentional that it was changed from 0x08 to 0x0?

[src/events/SDL_keyboard.c](https://github.com/libsdl-org/SDL/commit/90034b16dcacc7c0642a9bc94d393b2a12bc108d#diff-5b3b28c770d13cfbb9626d73d0721a6d82d30f8c8dcdf7cb326a72d98c8da4ff)
Copied!
Original file line number	Diff line number	Diff line change
@@ -30,16 +30,18 @@

/* Global keyboard information */

typedef enum
{
    KEYBOARD_HARDWARE = 0x01,
    KEYBOARD_VIRTUAL = 0x02,
    KEYBOARD_AUTORELEASE = 0x04,
    KEYBOARD_IGNOREMODIFIERS = 0x08
} SDL_KeyboardFlags;
#define KEYBOARD_HARDWARE   0x01
#define KEYBOARD_VIRTUAL    0x02
#define KEYBOARD_AUTORELEASE    0x04
#define KEYBOARD_IGNOREMODIFIERS    0x0

**Comment by slouken** [comment]
That was a typo. I’m AFK at the moment, but if you put up a PR, I can accept it.

Thanks!

**Comment by Kontrabant** [comment]
I caught and fixed this while working on the *nix keymapping code.

**Comment by slouken** [comment]
Thanks!
