### ISSUE TITLE
UNIX version of SDL_GetBasePath in SDL_sysfilesystem.c not correct for Solaris, probably other UNIXes

### ISSUE THREAD

**Issue by joncox123** [libsdl-org/SDL#10097]
The UNIX version of `SDL_GetBasePath` in `./src/filesystem/unix/SDL_sysfilesystem.c` is not correct for Solaris, and probably not correct either for most true UNIX versions. The issue is that `const char *path = getexecname()` is not guaranteed (usually does not on Solaris, in my experience) return the absolute path name. This is stated in Oracle's [documentation](https://docs.oracle.com/cd/E88353_01/html/E37843/getexecname-3c.html).

Furthermore, the documentation says the proper way to use `getexecname()` to get an absolute path is to combine it with `getcwd()` in the event that `getexecname()` does not return an absolute path. Again, I find it usually does not return an absolute path on Solaris. 

Therefore, I suggest making the following change to the SOLARIS block of `SDL_GetBasePath()` in  `./src/filesystem/unix/SDL_sysfilesystem.c`, which spans roughly Lines 235-246 in SDL2-2.30. I wrote this code to fix the issue:

```c
#if defined(__SOLARIS__)
    const char *path = getexecname();
    if (path != NULL) {
    	char *buf;
    	if (path[0] != '/') { /* must be absolute path... */
    		/* Per Oracle Solaris documentation, getexecname() may not return the
    		 * the absolute path. The docs say to call getcwd() if this is the
    		 * case, and append the results.
    		 */
    		long cwdSz = pathconf(".", _PC_PATH_MAX);
    		char *cwdBuf;
    		cwdBuf = (char *)malloc((size_t)cwdSz);
    		if (cwdBuf != NULL) {
    			char *cwdPtr = getcwd(cwdBuf, (size_t)cwdSz);
				buf = (char *) malloc((strlen(path) + strlen(cwdPtr) + 1)*sizeof(char));
				if (!buf) {
					SDL_OutOfMemory();
					return NULL;
				}
				strcat(buf, cwdPtr);
				strcat(buf, "/");
				strcat(buf, path);
				free(cwdBuf);
				retval = buf;
    		}
    		else {
    			SDL_OutOfMemory();
    			return NULL;
    		}
    	}
    	else {
    		retval = SDL_strdup(path);
			if (!retval) {
				SDL_OutOfMemory();
				return NULL;
			}
    	}
    }
#endif
```

**Comment by icculus** [comment]
So a fundamental problem with this is that it will fail if the process's cwd has changed since startup.

BUT: Solaris 10 has a Linux-like /proc directory, and `/proc/$PID/path/a.out` appears to be a symlink to the absolute path to the running binary.

**Comment by icculus** [comment]
Oh, we already have the Solaris-specifc /proc support code in place.

I'm inclined to not change this; getexecname() is merely the fallback if /proc is missing for some reason, and it's not safe to assume the current working directory is still correct by the time this code runs, so it's correct to fail if not provided an absolute path by getexecname.
