### ISSUE TITLE
Solaris 10 does not include compatible UTF8 support by default, SDL2 cannot compile

### ISSUE THREAD

**Issue by joncox123** [libsdl-org/SDL#10094]
Solaris 10 (SPARC) does not include the UTF8 libraries by default. People report mixed success actually installing them regardless. Since UTF8 is not a requirement for SDL2, SDL2 should still build on Solaris 10, even if there is no UTF8 support.

My solution was to hard code the `#define SDL_X11_HAVE_UTF8 0` in `./src/video/x11/SDL_x11messagebox.c`, but it seems to me that CMake should be defining this automatically.

**Comment by madebr** [comment]
Can you provide us with a (link to) a cross build toolchain, or a docker container with one?\
Addressing your issues will go way faster that way.

**Comment by icculus** [comment]
I have Solaris 10 (x86) running under VMware Workstation, now.  :)
