### ISSUE TITLE
SDL incorrectly detects X11_XRANDR with CMake, does not compile on Solaris 10

### ISSUE THREAD

**Issue by joncox123** [libsdl-org/SDL#10099]
By default, SDL2 tries to enable support for XRANDR with the SDL_X11_XRANDR option in CMake, for example. The problem is that Solaris 10 does not actually support XRANDR in practice, even though CMake and configure are detecting it. As a result, compilation will fail during the build process.

Therefore, if the Solaris or SunOS platform is detected in [sdlplatform.cmake](https://github.com/libsdl-org/SDL/blob/f08f458896d99f63b829c994623f8b9701d7eaf9/cmake/sdlplatform.cmake#L23), I suggest a warning message is written and SDL_X11_XRANDR  is set to "OFF" by default. I am not a build system engineer, so if you have a more elegant way of handling this, I am all ears.

**Comment by slouken** [comment]
We are scoping work for the SDL 3.2.0 release, so please let us know if this is a showstopper for you.

**Comment by sezero** [comment]
The commit seems to conditionalize SDL_X11_XFIXES, not SDL_X11_XRANDR

**Comment by madebr** [comment]
> The commit seems to conditionalize SDL_X11_XFIXES, not SDL_X11_XRANDR

That's a dump mistake by me...
I fixed it in fc608ffb5f61caae0e1034da181ac90760285410
