### ISSUE TITLE
VC : Add /MT /MTd and /MD /MDd in artifacts github

### ISSUE THREAD

**Issue by corentin35000** [libsdl-org/SDL#10103]
Hello, it would be interesting to add to the github assets the fact of having 4 folders (MT MTd MD MDd) for each system architecture which adds this! I wanted to start on /MT /MTd, but the SDL libraries are built for /MD, I will have to rebuild the libraries for all the SDL libraries.. it's super long

**Comment by madebr** [comment]
Testing/building for 4 mslibc runtime adds 0% to the test coverage.
Perhaps building and testing a `-DSDL_LIBC=OFF` Windows library would be useful.
But I would not build it for every architectures.

We advise projects supporting Windows to use the shared `SDLx.dll` libraries.
The SDL API is painstakingly designed to be libc-independent.

**Comment by slouken** [comment]
Also, the intention is not to provide release builds from GitHub CI, those will come from official releases, and will cover all supported platforms.
