### ISSUE TITLE
doctest + SDL2main : error LNK2019 (despite using DOCTEST_CONFIG_IMPLEMENT)

### ISSUE THREAD

**Issue by corentin35000** [libsdl-org/SDL#10109]
I have the impression that despite using DOCTEST_CONFIG_IMPLEMENT, I have the impression that it redefines the main! I have this on Windows, while on Android I don't need the SDL2main link and I have no problems! I have the impression that doctest and SDL2main are in conflict! <br />

Error : SDL2main.lib(SDL_windows_main.obj) : error LNK2019: symbole externe non résolu _SDL_main référencé dans la fonction _main_getcmdline <br />

main.cpp : 

```#include "game.h"
#include "unit-tests/unit-tests.h"
#include <rc2d/RC2D.h>

int main(int argc, char* argv[])
{
#ifdef NDEBUG // If we are in Release mode
    // Garder uniquement les logs critiques + Redirige la sortie dans un fichier
    rc2d_log_set_priority(RC2D_LOG_ERROR);
#else // If we are in Debug mode
    // Afficher tous les niveaux de logs
    rc2d_log_set_priority(RC2D_LOG_DEBUG);
#endif

#ifndef DOCTEST_CONFIG_DISABLE
    // Run all unit tests if Doctest is enabled
    // If tests fail, exit with error code
    if (rc2d_tests_runAllTests(argc, argv) != 0) return -1;
#endif

    RC2D_Callbacks myGameCallbacks = {};
    myGameCallbacks.rc2d_unload = rc2d_unload;
    myGameCallbacks.rc2d_load = rc2d_load;
    myGameCallbacks.rc2d_update = rc2d_update;
    myGameCallbacks.rc2d_draw = rc2d_draw;
    myGameCallbacks.rc2d_keypressed = rc2d_keypressed;
    myGameCallbacks.rc2d_keyreleased = rc2d_keyreleased;
    myGameCallbacks.rc2d_mousemoved = rc2d_mousemoved;
    myGameCallbacks.rc2d_mousepressed = rc2d_mousepressed;
    myGameCallbacks.rc2d_mousereleased = rc2d_mousereleased;
    myGameCallbacks.rc2d_wheelmoved = rc2d_wheelmoved;
    myGameCallbacks.rc2d_gamepadpressed = rc2d_gamepadpressed;
    myGameCallbacks.rc2d_gamepadreleased = rc2d_gamepadreleased;
    myGameCallbacks.rc2d_joystickpressed = rc2d_joystickpressed;
    myGameCallbacks.rc2d_joystickreleased = rc2d_joystickreleased;
    myGameCallbacks.rc2d_joystickadded = rc2d_joystickadded;
    myGameCallbacks.rc2d_joystickremoved = rc2d_joystickremoved;
    myGameCallbacks.rc2d_dropfile = rc2d_dropfile;
    myGameCallbacks.rc2d_droptext = rc2d_droptext;
    myGameCallbacks.rc2d_dropbegin = rc2d_dropbegin;
    myGameCallbacks.rc2d_dropcomplete = rc2d_dropcomplete;

    return rc2d_run(&myGameCallbacks, 1280, 720, 1280, 720, RC2D_RENDER_LOGICAL_SIZE_MODE_LETTERBOX, NULL);
}```

and unit-tests.cpp : 
```#include "unit-tests/unit-tests.h"
#define DOCTEST_CONFIG_IMPLEMENT // Il faut l'inclure que dans un seul fichier source et avant l'inclusion de doctest.h
#include <doctest/doctest.h>

// Run all tests with Doctest and return the result
int rc2d_tests_runAllTests(int argc, char* argv[])
{
    doctest::Context context;             // Initialisez le contexte
    context.applyCommandLine(argc, argv); // Appliquez les arguments de la ligne de commande
    int test_result = context.run();      // Executez les tests

    if(context.shouldExit() || test_result != 0) 
    {
        return test_result; // Termine l'exécution si Doctest demande de quitter ou si les tests échouent
    }

    return 0;
}

TEST_CASE("Example test case") {
    int x = 1;
    CHECK(x == 1); // Test success
    //CHECK(x == 2); // Test error
}
```

**Comment by madebr** [comment]
Linking with SDL2main has the implicit expectation you included `SDL.h` in the translation unit in which the main function is declared and implemented.

So there are 2 ways to fix this:
- Don't link with SDL2main and make sure to run `SDL_SetMainReady` in the test suite fixture
- Include `SDL.h` in your test suite *before the headers of doctest*, such that SDL can rename main to SDL_main,

**Comment by corentin35000** [comment]
I have already tried to use: SDL_SetMainReady(); obviously removing SDL2main! But I have this: MSVCRT.lib(exe_winmain.obj): error LNK2019: unresolved WinMain external symbol referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) (so it expects me to defined SDL2main). I also tested SDL.h before including doctest.h, it's the same... I had already tested these are two solutions

**Comment by corentin35000** [comment]
> Linking with SDL2main has the implicit expectation you included `SDL.h` in the translation unit in which the main function is declared and implemented.
> 
> So there are 2 ways to fix this:
> 
> * Don't link with SDL2main and make sure to run `SDL_SetMainReady` in the test suite fixture
> * Include `SDL.h` in your test suite _before the headers of doctest_, such that SDL can rename main to SDL_main,


I have already tried to use: SDL_SetMainReady(); obviously removing SDL2main! But I have this: MSVCRT.lib(exe_winmain.obj): error LNK2019: unresolved WinMain external symbol referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@yahxz) (so it expects me to defined SDL2main). I also tested SDL.h before including doctest.h, it's the same... I had already tested these are two solutions

**Comment by madebr** [comment]
The linker is missing `WinMain`, which means you're linking the executable as a GUI executable (Windows subsystem).
However, you probably want to use the CONSOLE subsystem.
This can be done by passing `/subsystem:CONSOLE` to the linker, or drop the `WIN32` from `add_executable(mytest WIN32 src1.c)`.

**Comment by corentin35000** [comment]
> L'éditeur de liens est manquant `WinMain`, ce qui signifie que vous liez l'exécutable en tant qu'exécutable GUI (sous-système Windows). Cependant, vous souhaiterez probablement utiliser le sous-système CONSOLE. Cela peut être fait en passant `/subsystem:CONSOLE`à l'éditeur de liens ou en supprimant le `WIN32`from `add_executable(mytest WIN32 src1.c)`dans cmake.

I simply use this for Windows in Release mode, to avoid having the terminal open in Release mode: set_target_properties(${PROJECT_NAME} PROPERTIES WIN32_EXECUTABLE $<CONFIG:Release>)

I commented out and added this: 
set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "/subsystem:console")

But now I have another error: error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main( void)" (?invoke_main@@YAHXZ.

Especially with what you're telling me, I'm going to have the terminal open, so I wanted to keep it in GUI mode.

**Comment by madebr** [comment]
When you don't link to SDL2main, add `SDL_SetMainReady` to an appropriate location and add `target_compile_definitions(${PROJECT_NAME} PRIVATE SDL_MAIN_HANDLED)`.

**Comment by corentin35000** [comment]
> When you don't link to SDL2main, add `SDL_SetMainReady` to an appropriate location and add `target_compile_definitions(${PROJECT_NAME} PRIVATE SDL_MAIN_HANDLED)`.

I added this:
set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS_DEBUG "/SUBSYSTEM:CONSOLE")
target_compile_definitions(${PROJECT_NAME} PRIVATE SDL_MAIN_HANDLED)

main.cpp : 
```#include <rc2d/RC2D.h>
#include "game.h"
#include "unit-tests/unit-tests.h"

int main(int argc, char* argv[])
{
    SDL_SetMainReady();

#ifdef NDEBUG // If we are in Release mode
    // Keep only error and critical logs
    rc2d_log_set_priority(RC2D_LOG_ERROR);
#else // If we are in Debug mode
    // Show all log levels
    rc2d_log_set_priority(RC2D_LOG_DEBUG);
#endif

#ifndef DOCTEST_CONFIG_DISABLE
    // Run all unit tests if Doctest is enabled
    // If tests fail, exit with error code
    if (rc2d_tests_runAllTests(argc, argv) != 0) return -1;
#endif

    return 0;
}```

**Comment by corentin35000** [comment]
> > When you don't link to SDL2main, add `SDL_SetMainReady` to an appropriate location and add `target_compile_definitions(${PROJECT_NAME} PRIVATE SDL_MAIN_HANDLED)`.
> 
> I added this: set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS_DEBUG "/SUBSYSTEM:CONSOLE") target_compile_definitions(${PROJECT_NAME} PRIVATE SDL_MAIN_HANDLED)
> 
> main.cpp :
> 
> ```
> #include "game.h"
> #include "unit-tests/unit-tests.h"
> 
> int main(int argc, char* argv[])
> {
>     SDL_SetMainReady();
> 
> #ifdef NDEBUG // If we are in Release mode
>     // Keep only error and critical logs
>     rc2d_log_set_priority(RC2D_LOG_ERROR);
> #else // If we are in Debug mode
>     // Show all log levels
>     rc2d_log_set_priority(RC2D_LOG_DEBUG);
> #endif
> 
> #ifndef DOCTEST_CONFIG_DISABLE
>     // Run all unit tests if Doctest is enabled
>     // If tests fail, exit with error code
>     if (rc2d_tests_runAllTests(argc, argv) != 0) return -1;
> #endif
> 
>     return 0;
> }
> ```

I still have the error: Error: error LNK2019: unresolved external symbol main referenced in function "int __cdecl __scrt_common_main_seh(void)"

**Comment by corentin35000** [comment]
SDL_SetMainReady, does this system still work? :(

**Comment by corentin35000** [comment]
, knowing that this is not appropriate I would like to keep: set_target_properties(${PROJECT_NAME} PROPERTIES WIN32_EXECUTABLE $<CONFIG:Release>). To have an application in Release mode without a terminal! And if I put this I end up with the WinMain error..

**Comment by madebr** [comment]
It's probably something silly. Please share a minimum reproducible project and I'll see whether I can reproduce your issue and how to fix it.

**Comment by corentin35000** [comment]
> It's probably something silly. Please share a minimum reproducible project and I'll see whether I can reproduce your issue and how to fix it.

This is going to be complicated, my RC2D wrapper uses submodules..etc :/ I plan to upgrade the version for SDL3 from my wrapper, but I wanted to wait for v3.2.0 to avoid too many breaking changes.. since I see that it still changes a lot of things currently... would I have less problems with SDL3 given that SDLmain was deleted it seems to me?

**Comment by corentin35000** [comment]
I use SDL, SDLttf, SDLmixer and SDLimage I saw that none of the repositories were versioned yet, should I base it on master / main for SDL3_* for all the libraries?

**Comment by madebr** [comment]
> > It's probably something silly. Please share a minimum reproducible project and I'll see whether I can reproduce your issue and how to fix it.
> 
> This is going to be complicated, my RC2D wrapper uses submodules..etc :/ I plan to upgrade the version for SDL3 from my wrapper, but I wanted to wait for v3.2.0 to avoid too many breaking changes.. since I see that it still changes a lot of things currently... would I have less problems with SDL3 given that SDLmain was deleted it seems to me?

You'll have to additionally [deal with a full-blown migration](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md).
The main entry function _should_ not appear though.
