### ISSUE TITLE
Multiple Windows  and SDL_EVENT_QUIT failure

### ISSUE THREAD

**Issue by sechshelme** [libsdl-org/SDL#10115]
If I create just one window, everything works fine. As soon as I have two or more windows, `SDL_EVENT_QUIT` is not executed.

As far as I remember, this used to work.
For testing, I just pulled the latest SDL3 with git pull.
Tested with Linux 64bit and wine.

```c
/*
  Linux:
  gcc main.c -o main -lSDL3

  Windows:
  x86_64-w64-mingw32-gcc main.c -o main.exe -lSDL3 -I/usr/local/include -L.
*/

#include <SDL3/SDL.h>

int main(int argc, char *argv[])
{
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window * win1 = SDL_CreateWindow("win 1", 320, 200, 0);
    SDL_Window * win2 = SDL_CreateWindow("win 2", 320, 200, 0);

    SDL_bool quit = SDL_FALSE;
    while (!quit)
    {
        SDL_Event event;
        while (SDL_PollEvent(&event))
        {
            switch (event.type)
            {
                case SDL_EVENT_QUIT:
                    SDL_Log("Finish") ;
                    quit = SDL_TRUE;
                    break;
            }
        }
    }
    SDL_Quit();
    return 0;
}
```

**Comment by slouken** [comment]
When would you expect this event? Are you handling `SDL_EVENT_WINDOW_CLOSE_REQUESTED`?

**Comment by slouken** [comment]
No, the quit event is just sent when the last window has been requested to close. If you don't close the windows when requested then clearly you don't want to quit the app. :)
