### ISSUE TITLE
Encoding of paths in file dialogs

### ISSUE THREAD

**Issue by lachrymaLF** [libsdl-org/SDL#10119]
I was trying out SDL_ShowOpenFileDialog on some paths with CJK characters. It seems that:
- On Linux I am getting percent-encoded strings in the callback. (`.../スクリーンショット.png` turns into `.../%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88.png`)
- But on Windows they were raw (non-encoded) strings.

(In particular, I'm not able to open a file directly using the string received on Linux, but it is OK on Windows.)

Is the expected behavior documented anywhere?

**Comment by slouken** [comment]
The expected behavior is for the paths to be UTF-8 encoded characters, not percent escapes. @Semphriss, can you take a look?

**Comment by Semphriss** [comment]
Tried and reproduced, it seems to happen specifically with XDG Portals.

Zenity works fine, so if this is urgent, `SDL_SetHint(SDL_HINT_FILE_DIALOG_DRIVER, "zenity");` can act as a workaround until this is fixed (requires Zenity on the target device(s), must be set only on Unix).

It sounds like the kind of thing that should be a setting somewhere, but I'm not familiar enough to know where to look. @Kontrabant You're more familiar than me with that; do you know what's the XDG-recommended way of obtaining an UTF-8 string? If not, I'll try to dig in the documentation and bug trackers, surely others have had similar issues.

**Comment by Kontrabant** [comment]
There no option in the portal to do so, but it's trivial to convert percent encoding to UTF-8, as it can be done in-place since percent encoded characters take 3 characters to represent one. SDL already has some (duplicated) code in places to do this, so this would be a good excuse to factor out that functionality.
