### ISSUE TITLE
segfault in testaudio

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10130]
There's a segfault because `SDL_GetAudioDeviceName(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK)` returns `NULL`,
which is used as an argument to `SDL_strdup`.

https://github.com/libsdl-org/SDL/blob/a4f962fd46b5b0b4ed9d5eb1e40a203cc0e5f422/test/testaudio.c#L1016

https://github.com/libsdl-org/SDL/blob/a4f962fd46b5b0b4ed9d5eb1e40a203cc0e5f422/test/testaudio.c#L971

https://github.com/libsdl-org/SDL/blob/a4f962fd46b5b0b4ed9d5eb1e40a203cc0e5f422/test/testaudio.c#L988

stacktrace:
```
__strlen_avx2 0x00007ffff7b7f8dd
SDL_strlen_REAL SDL_string.c:561
SDL_strdup_REAL SDL_string.c:855
SDL_strdup SDL_dynapi_procs.h:1020
CreatePhysicalDeviceThing testaudio.c:988
CreateDefaultPhysicalDevice testaudio.c:1016
SDL_AppInit testaudio.c:1100
SDL_InitMainCallbacks SDL_main_callbacks.c:99
SDL_EnterAppMainCallbacks_REAL SDL_sysmain_callbacks.c:42
SDL_EnterAppMainCallbacks SDL_dynapi_procs.h:171
SDL_main SDL_main_impl.h:59
SDL_RunApp_REAL SDL_runapp.c:40
SDL_RunApp_DEFAULT SDL_dynapi_procs.h:709
SDL_RunApp SDL_dynapi_procs.h:709
main SDL_main_impl.h:208
```

**Comment by icculus** [comment]
Gosh, how long has this been broken?!

**Comment by icculus** [comment]
Oh, only since e23257307e220c7dd3d827e195f52adaabaaeeeb, where this used to handle NULL just fine and then I wrapped it in an SDL_strdup.
