### ISSUE TITLE
Cannot create renderer even after `SDL_DestroyWindowSurface` has been called on a window

### ISSUE THREAD

**Issue by ankith26** [libsdl-org/SDL#10133]
Over at pygame-ce, we have gotten an issue report, which essentially boils down to this SDL issue:

`SDL_GetWindowSurface` can create and associate a texture/renderer with the window in some cases, but calling `SDL_DestroyWindowSurface` does not seem to clean up this up.

This leads to the `"Renderer already associated with window"` error being thrown if `SDL_CreateRenderer` is called after the old surface associated with the window has already been cleaned up with `SDL_DestroyWindowSurface`.

My guess is that `SDL_DestroyWindowTexture` must be called in `SDL_DestroyWindowSurface` to deal with such a scenario.

PS: I am making this issue based on SDL2, but it could potentially be relevant to SDL3 as well.

**Comment by slouken** [comment]
This is fixed for the next 2.30 release.

**Comment by ankith26** [comment]
thanks!

**Comment by slouken** [comment]
The release is live!
https://github.com/libsdl-org/SDL/releases/tag/release-2.30.5
