### ISSUE TITLE
Commit `22c1444` breaks compiling for WINAPI_PARTITION_GAMES (Xbox)

### ISSUE THREAD

**Issue by sykhro** [libsdl-org/SDL#10159]
The commit https://github.com/libsdl-org/SDL/commit/22c14442e22b432c69348211fc97c81248269d30 unconditionally introduces a call to GetMessageTime(), which comes from `user32`. This is not available when targetting WINAPI_PARTITION_GAMES strictly.

**Comment by slouken** [comment]
Does the build break with one of the existing projects? If not, feel free to submit a PR or patch with a fix you can test there.

**Comment by sykhro** [comment]
Yes, I have a fix - will send soon; opened the issue to avoid forgetting :)

**Comment by slouken** [comment]
Thanks!

**Comment by slouken** [comment]
Did you create a PR for this?

**Comment by sykhro** [comment]
I'm terribly sorry! I thought I sent this ages ago, I have rebased it on top of the `SDL2` branch; see #10909
