### ISSUE TITLE
Export SDL_UCS4ToUTF8()?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#10157]
This function keeps coming up in relation to keyboard and text handling, and I think we should make it available in the API.

Does anyone feel like we shouldn't do this?

**Comment by icculus** [comment]
Pros:

- much less heavyweight than SDL_iconv
- people rolling their own will either get it wrong, or get it _really_ wrong by casting to char.


Cons:

...?

**Comment by icculus** [comment]
Dumb questions:

- What should this do with too-large values? A value > 0x10FFFF not only isn't a valid Unicode codepoint, it also won't fit in a UTF-8 4-byte sequence. The current code just generates a 4-byte sequence with apparently-random bits.
- Should it fail if they try to encode a UTF-16 surrogate codepoint? I'd say yes, but right now it does not.

I'm thinking in both cases this should either encode an `SDL_INVALID_UNICODE_CODEPOINT` instead (which is the Unicode REPLACEMENT CHARACTER: that weird question mark diamond shape thing we've all seen at some point), or report an error in some way, or both.

**Comment by slouken** [comment]
> Dumb questions:
> 
> * What should this do with too-large values? A value > 0x10FFFF not only isn't a valid Unicode codepoint, it also won't fit in a UTF-8 4-byte sequence. The current code just generates a 4-byte sequence with apparently-random bits.
> * Should it fail if they try to encode a UTF-16 surrogate codepoint? I'd say yes, but right now it does not.
> 
> I'm thinking in both cases this should either encode an `SDL_INVALID_UNICODE_CODEPOINT` instead (which is the Unicode REPLACEMENT CHARACTER: that weird question mark diamond shape thing we've all seen at some point), or report an error in some way, or both.

Agreed.

**Comment by icculus** [comment]
> I'm thinking in both cases this should either encode an SDL_INVALID_UNICODE_CODEPOINT instead (which is the Unicode REPLACEMENT CHARACTER: that weird question mark diamond shape thing we've all seen at some point), or report an error in some way, or both.

Went with the first one; the pattern `char *end = SDL_UCS4ToUTF8(ch, an_array_not_a_pointer); *end = 0;` was the primary way we were using this, so reporting an error would be awkward and probably unnecessary.
