### ISSUE TITLE
SDL_Keycode does no longer represent a key

### ISSUE THREAD

**Issue by Kaktus514** [libsdl-org/SDL#10150]
Earlier I think both `SDL_Scancode` and `SDL_Keycode` represented keys on the keyboard but with recent changes I feel this is no longer true for `SDL_Keycode`.

Now it seems like `SDL_Keycode` instead represents _how you might want to interpret a key press if you consider the state of other keys_. I think this complicates things considerably. Many games don't care if Shift or Alt Gr is pressed down, or if Caps Lock is on, they still want to move the player, fire the bullet, and so on, regardless.

I know it's possible to enable the old behavior using
```
SDL_SetHint(SDL_HINT_KEYCODE_OPTIONS, "unmodified");
```
or work around it using `SDL_GetKeyFromScancode` but people still have to deal with the confusion of having two versions of every letter key (e.g. `SDLK_a` and `SDLK_A`). Constants are often all-uppercase and the letter keys that people see on their keyboard are uppercase so it's natural to try writing `SDLK_A` in the code when in fact it should be `SDLK_a`. I have done this many times but I could always rely on the compiler to catch this error but now it would silently compile.

There was also someone recently who suggested that `SDL_GetKeyName(SDLK_a)` should return "a" (since `SDL_GetKeyName(SDLK_A)` return "A" now) but it's still the "A" key (uppercase) on the keyboard and what I would consider the appropriate name to show to the users.

My concern is that all this will make SDL harder to teach and that it will lead to bugs that are not noticed until much later when someone reports that a key doesn't work in combination with other keys. If it's just a minority that needs this functionality then maybe they are the ones who should carry the extra burden. Don't forget what the S in SDL stands for.

I don't know what the best way forward is but maybe keep `SDL_Keycode` working the way it has been in SDL2 and introduce another type (and another field in `SDL_KeyboardEvent`), with its own set of constants, to represent this new thing.

**Comment by slouken** [comment]
All this is good feedback, and why we didn't do this in SDL2. However, the new model more closely matches how X11 works, and is the only way the web platform works. (Emscripten events have a scancode and composed letter and that's it)

@icculus, thoughts?

**Comment by slouken** [comment]
The old behavior has been restored, the details are in https://github.com/libsdl-org/SDL/pull/10156. Thanks for the feedback!
