### ISSUE TITLE
SDL_PixelFormat [R/G/B/A]loss is broken and confusing

### ISSUE THREAD

**Issue by 0x1F9F1** [libsdl-org/SDL#10168]
The loss members of SDL_PixelFormat are equal to `8 - number_of_bits_in_channel`, which is already confusing, but now with 10-bit channel support, they don't make any sense (they are currently clamped to 0 instead of being -2 for a 10-bit channel).

Would it be better to just replace them with `[R/G/B/A]bits` instead?

Also this line is broken (I assume it meant to check for number of bits):
https://github.com/libsdl-org/SDL/blob/b948d1446ac3a106f580df151f7c9db0e577b0ac/src/video/SDL_blit.c#L235

**Comment by slouken** [comment]
> The loss members of SDL_PixelFormat are equal to `8 - number_of_bits_in_channel`, which is already confusing, but now with 10-bit channel support, they don't make any sense (they are currently clamped to 0 instead of being -2 for a 10-bit channel).
> 
> Would it be better to just replace them with `[R/G/B/A]bits` instead?

Yes, probably. There was some code where this made it easier to do pixel conversion, but it's easy enough to do the calculation locally based on the number of bits in the channel instead.

**Comment by slouken** [comment]
I looked at this a little bit, and it would greatly reduce performance to change core blitting code from this:
```c
*r = SDL_expand_byte[format->Rloss][v];
```
to this:
```c
*r = SDL_expand_byte[SDL_max((8 - format->Rbits), 0)][v];
```
Maybe there's a better solution?

**Comment by 0x1F9F1** [comment]
> I looked at this a little bit, and it would greatly reduce performance to change core blitting code from this:
> 
> ```c
> *r = SDL_expand_byte[format->Rloss][v];
> ```
> 
> to this:
> 
> ```c
> *r = SDL_expand_byte[SDL_max((8 - format->Rbits), 0)][v];
> ```
> 
> Maybe there's a better solution?

Reverse the order of the array and expand it to handle the 9 and 10 bit cases if necessary (though I think those are handled elsewhere anyway).

**Comment by slouken** [comment]
I like it!

**Comment by 0x1F9F1** [comment]
It's also worth noting that `(r >> format->Rloss)` isn't mathematically correct, i.e going from 8-bit to 6-bit you would want to do `(r * 63) / 255`, which isn't quite equal to `r >> 2` or `r / 4`.

One way to do it properly would be to use fixed-point multiplication instead (which might even be slightly faster than full lookup tables on modern hardware).

```c
// Q16 fixed-point factors for converting from N-bit to 8-bit
// r = (to_8_bit[fmt->Rbits] * ((pixel & fmt->Rmask) >> fmt->Rshift)) >> 16
const Uint32   to_8_bit[11] = { 0x000000, 0xFF0000, 0x550000, 0x246DB7, 0x110000, 0x0839CF, 0x040C31, 0x020205, 0x010000, 0x007FC0, 0x003FD0 };

// Q16 fixed-point factors for converting from 8-bit to N-bit
// pixel = ((from_8_bit[fmt->Rbits] * r) >> 16) << fmt->Rshift
const Uint32 from_8_bit[11] = { 0x000000, 0x000102, 0x000304, 0x000708, 0x000F10, 0x001F20, 0x003F40, 0x007F80, 0x010000, 0x020102, 0x040304 };
```

**Comment by slouken** [comment]
Good point. Should we incorporate this into the blit improvement PR? I believe in general that tries to have more accurate blends for all blitters. Or maybe we should merge that first and open a new one with this change?

**Comment by 0x1F9F1** [comment]
> Good point. Should we incorporate this into the blit improvement PR? I believe in general that tries to have more accurate blends for all blitters. Or maybe we should merge that first and open a new one with this change?

Best to keep it separate, the existing PR is already fairly large.
