### ISSUE TITLE
Flydigi Apex 4 support

### ISSUE THREAD

**Issue by zany130** [libsdl-org/SDL#10161]
as recommended here https://github.com/hhd-dev/hhd/issues/73#issuecomment-2204345871
it sounds like this would be the best place to get this supported?  If not could you please point me in the right direction, I have no experience with these kinds of things :sweat_smile: 

I found that the [Flydigi Apex 4 controller](https://www.amazon.com/PC-Controller-Feedback-Force-Adjustable-Full-Color-Vibration/dp/B0CRR1WR9W) has four interfaces

1. normal gamepad
2.  gyro mouse device  toggled with a button on the controller (circle button next to home)
3. gamepad with gyro
4. unknown, maybe firmware updates or the Windows software.

Right now, Steam and other SDL applications are reading the first interface, meaning they do not see the gyro.

In the above issue, it was recommended that this could maybe be fixed in SDL?

**Comment by slouken** [comment]
I picked up the Apex 4 controller, and it looks like the third interface only has gyro data when mouse mode is enabled. I verified this on both Windows and Linux. I haven't installed the Space Station software or anything, so this is the default firmware out of the box.

The reason why SDL only sees the first interface is because the third interface is using a custom vendor-specific usage page and usage, and that's being ignored right now.

**Comment by slouken** [comment]
If you can figure out what needs to be sent to the controller to enable gyro data with the mouse mode off, then we could create an SDL hidraw driver that supports the back buttons and the gyro simultaneously.

**Comment by zany130** [comment]
> I picked up the Apex 4 controller, and it looks like the third interface only has gyro data when mouse mode is enabled. I verified this on both Windows and Linux. 

Hmmm that's strange on Linux I saw what I assumed was gyro data (but might be wrong) on the 3rd interface with mouse mode off .

I treated with the hid-recoeder 

And moving the controller around changed the values

**Comment by slouken** [comment]
I believe you, but maybe something put the controller into a mode where it reports that data? Maybe a firmware update, or the Windows app turning on DS mode?

**Comment by zany130** [comment]
Yes I will investigate I don't think it's ds mode as I currently have that off and I don't think that affects Linux anyway

It could be firmware update.

**Comment by zany130** [comment]
would this be enough to get gyro support added in a SDL driver? 

not sure if this is "true" gyro or just the same thing as the mouse mode when you press the circle button

**Comment by slouken** [comment]
Given that you need to set a gyro mapping in software, and it looks like we can't tell if that's set, I'm going to say this isn't enough to add gyro support in an SDL driver. If we can find out whether gyro is enabled, then that might change, but I'm going to go ahead and close this for now.

**Comment by zany130** [comment]
sorry for bumping this but just wanted to add a few observations I made.

This might of already been obvious but

there 2 ways  the controller sends gyro data to the OS (this is both on linux and windows WITHOUT the driver software running (more on that in a bit)

1. Natively in switch mode
2. Emulating some other input device (a mouse or one controller analog stick  either left or right) and mapping that device to the controller's gyro 

The second way of sending gyro can further be separated into two catagory's

- built in to the controller (works in linux and windows) 

This is what pressing the "circle button" (extra button next to home) does in dinput mode and is what flydigi refers to as" flymouse". All the OS sees is the normal controller and a virtual mouse which is mapped to gyro by the controllers firmware.

- Done in the driver software

This is the Gyro mapping I mentioned you can set up in software. You can  map  gyro to either analog sticks, or to the "fly mouse" (controller virtual mouse)

Interestingly, mouse Gryo doesn't need the driver software running (it does require the software to set it up), but analog stick gyro does (this is true on BOTH windows and Linux)
