### ISSUE TITLE
Audio noise caused by the buffer issue, re-open issues 9700 and 9708

### ISSUE THREAD

**Issue by joey-cyt** [libsdl-org/SDL#10166]
The issue #9700 and #9708 were merged/closed on May 17. However, the commit was reverted by   https://github.com/libsdl-org/SDL/commit/90beffdeb1425b7c8fd9630c47da052e703838e0
to solve Dota/CS2 audio noise issue.
The reversion brought back the original issues of #9700 and #9708. Didn't find the option to re-open the closed issue, thus create this new one to track the issue.

**Comment by icculus** [comment]
Reopened the original issue.
