### ISSUE TITLE
[Regression] SDL3 doesn't receive input events when registering RawInput devices

### ISSUE THREAD

**Issue by sam20908** [libsdl-org/SDL#10178]
I used to be able to register my own RawInput devices and pass in the SDL window's HWND. However, it does not work anymore, and either I get all my inputs through RawInput, or I don't use it at all.

OS: Windows 11

**Comment by slouken** [comment]
Have you checked the latest SDL code? We used to always register a raw keyboard handler, and that's now disabled by default. Maybe check to see if WIN_RawInputThread() is getting called?

**Comment by sam20908** [comment]
Ah yeah it's getting called

I'm using prerelease 3.1.1
