### ISSUE TITLE
Move SDL_RunApp related code to src/main

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10170]
This is super nitpicky and not urgent for a 3.2.0 release, but src/core/SDL_runapp.c and the various platform-specific SDL_RunApp implementations in src/core/* subdirs should probably live under src/main instead.

(Putting this under the 3.2.0 milestone for now, just in case it's quick and desirable to change this, though.)

**Comment by slouken** [comment]
Yeah, let's do this.
