### ISSUE TITLE
New API suggestion: SDL_LoadWAVRegion and SDL_LoadWAVRegion_IO

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#10176]
Recently I was trying to implement dynamic audio streaming from a file for a music player but i noticed that there is no way to partially load the wav file or to get information about the wave file to manually stream it in.
To fix this i would propose these two APIs:

```
int SDL_LoadWAVRegion(
       const char *path, 
       SDL_AudioSpec *spec, 
       Uint8 **audio_buf, 
       Uint32 *audio_len,
       Uint32  sample_offset,
       Uint32 sample_count
);

int SDL_LoadWAVRegion_IO(
       SDL_IOStream *src, 
       SDL_bool closeio, 
       SDL_AudioSpec *spec,
       Uint8 **audio_buf, 
       Uint32 *audio_len
       Uint32  sample_offset,
       Uint32 sample_count
);
```

**Comment by slouken** [comment]
That's beyond the scope of the core SDL library. You can implement that for your own use, or use SDL_mixer, which does dynamic loading and streaming of music.
