### ISSUE TITLE
floating point Refresh Rate not reported correctly

### ISSUE THREAD

**Issue by TylerGlaiel** [libsdl-org/SDL#10185]
Windows says my monitor is 143.963hz
SDL reports this as 144.0hz

**Comment by slouken** [comment]
Can you debug it and find out why?

**Comment by TylerGlaiel** [comment]
![image](https://github.com/libsdl-org/SDL/assets/1686664/77ec4b2e-3b16-4852-a8a1-d165d17c74d4)
something to do with windows maybe

**Comment by TylerGlaiel** [comment]
I can confirm that using DXGI instead reports the correct framerate

**Comment by slouken** [comment]
Fixed!

**Comment by TylerGlaiel** [comment]
![image](https://github.com/user-attachments/assets/86e46ee4-4a2a-4617-b984-b07c9df5f188)
theres still a little bit of weird rounding here (float refresh rate is 143.960, but actual refresh rate (numerator / denominator) is 143.963

**Comment by slouken** [comment]
The floating point value has 2 digits of precision for display purposes. If you want the full precision, you should use the numerator and denominator to calculate it.
