### ISSUE TITLE
Entire device display freezes when resizing [Windows 11]

### ISSUE THREAD

**Issue by HotNoggin** [libsdl-org/SDL#10195]
When the window is resized, the display (the ENTIRE display, not just the SDL window) freezes for a moment before returning to normal. This issue only occurs when resizing (not with dragging). The issue mysteriously vanishes when certain applications are open at the same time, including Windows Snipping Tool (both while recording and while open but not recording) and Godot applications, but not applications like Chrome, Discord, GitHub Desktop, or Visual Studio.

This issue occurs when using `SDL_RenderPresent()` each frame, even without any other renderer operations. This is why I believe it's a bug with SDL and not an issue in the C++ project's code (but feel free to check the repo).

Device specifications:
Processor: AMD Ryzen 9 6900HS with Radeon Graphics           3.30 GHz
64-bit operating system, x64-based processor
Windows 11 Home (version 23H2)

(Duplicate of [this issue](https://github.com/HotNoggin/Arcade-Maker/issues/1) from the actual application repository).

**Comment by Squall-Leonhart** [comment]
I believe this is a bug in your display driver that AMD is already aware of.
