### ISSUE TITLE
[SDL3 suggestion]: rename SDL_GL_DeleteContext to SDL_GL_DestroyContext

### ISSUE THREAD

**Issue by Qwinci** [libsdl-org/SDL#10197]
Its inconsistent with the other create/destroy functions, so I don't see why it should be delete instead of destroy.

**Comment by icculus** [comment]
In this case, it's because "Delete" is _OpenGL_'s naming convention (wglDeleteContext, glXDeleteContext), so we're going to leave this one as-is.

**Comment by icculus** [comment]
Wait, wait, it's glXDestroyContext, and wglDeleteContext...ugh.

Okay, we'll change it.

**Comment by icculus** [comment]
Okay, this is done in SDL3 now! Thanks for pointing this out!
