### ISSUE TITLE
configure for iOS doesn't work

### ISSUE THREAD

**Issue by ronaaron** [libsdl-org/SDL#10205]
Because I'm doing headless builds for support libraries, I build SDL2 on a 'build machine'.

The 'configure' script is passed "--host=aarch64-ios-darwin" however, it doesn't add in SDL_VIDEO_UIKIT ... so none of the video stuff gets compiled in.

**Comment by ronaaron** [comment]
Forgot to mention, this is with the current SDL2-2.30.5

**Comment by slouken** [comment]
You'll need to do additional work to make sure the development libraries for iOS are found. Xcode is the supported iOS build environment, but you're welcome to submit patches to get your use case working.
