### ISSUE TITLE
threads are needed by many SDL subsystems and may not be disabled

### ISSUE THREAD

**Issue by hadjTahar** [libsdl-org/SDL#10214]
I have a cmake project with SDL3 source code, but cmake fails with a message "threads are needed by many SDL subsystems and may not be disabled"

I have to set "HAVE_PTHREADS" to ON manually for it to work.

Also there is an error at "SDL_iconv.c", that says "error: unknown type name ptrdiff_t", I have to include  "<stddef.h>".

The same project compiles on Windows 10, but fails on Linux.

- cmake 3.22.1
- linux mint: x86_64-linux-gnu
- gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by madebr** [comment]
On Linux, the threads error message shows when cmake fails to detect a compatible pthread implementation.
This is done in `CheckPTHREAD`](https://github.com/libsdl-org/SDL/blob/fdc04708f1950ad76eff16fd47ffe67dcdc5ba04/cmake/sdlchecks.cmake#L761-L899).
Can you please share the `CMakeFiles/CMakeConfigureLog.yaml` file from a fresh, unmodified SDL build?

`stddef.h` should be included through `SDL_internal.h`, but is only included when `HAVE_STDDEF_H` is on.
Sharing the yaml might also shed a light on why CMake could not detect `stddef.h`.

**Comment by hadjTahar** [comment]
There is no `CMakeFiles/CMakeConfigureLog.yaml` file, and the log files are huge more that 4k lines, should I post them here?

**Comment by madebr** [comment]
Thanks.

Why does CMake want to add `-Wl,-Bstatic,--whole-archive -lpthread -Wl,--no-whole-archive` to the compile command?
A lot of tests fail to link because of this:
```
/usr/bin/ld: cannot find -lgcc_s: No such file or directory
```
This explains all your errors.

**Comment by hadjTahar** [comment]
Thanks a lot. 
I had missing DLLs on windows (Mingw) so the quick fix was to add these to cmake, but I forgot about them and now they were causing the issue.
```
set(CMAKE_CXX_STANDARD_LIBRARIES "-static-libgcc -static-libstdc++")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-Bstatic,--whole-archive -lpthread -Wl,--no-whole-archive")
```
