### ISSUE TITLE
Add Splitfish FragFX FragChuck support

### ISSUE THREAD

**Issue by ceski-1** [libsdl-org/SDL#10220]
This is a unique controller, sort of like half of an Xbox controller and used in combination with a mouse:
https://world.splitfish.com/fragfx-game-controllers/fragfx-fragchuck-pc-mac.html
https://www.amazon.co.uk/dp/B00SLKVJ2Y

The USB adapter has a switch for two modes: keyboard or gamepad. The latter is the one of interest.

Splitfish FragFX FragChuck (in gamepad mode, as "SplitFish Game Controller"):

030000004c0500006802000000000000,SplitFish Game Controller,platform:Windows,crc:5628,a:b0,b:b16,leftstick:b1,leftshoulder:b17,rightshoulder:b10,dpup:b4,dpdown:b6,dpleft:b7,dpright:b5,leftx:a0,lefty:a1,lefttrigger:b8,

**Comment by Chonkblonk** [comment]
This seems to now have broken.
