### ISSUE TITLE
SDL3 Camera Frame Rate Limited to 10 FPS on Ubuntu 22.04

### ISSUE THREAD

**Issue by qqiu-cyt** [libsdl-org/SDL#10234]
I'm experiencing an issue where the camera frame rate is limited to 10 FPS on Ubuntu 22.04, despite setting the camera to operate at 30 FPS. The camera is capable of supporting up to 60 FPS.

Spec used to open the camera:
            .format = SDL_PIXELFORMAT_YUY2,
            .colorspace = SDL_COLORSPACE_YUV_DEFAULT,
            .width = 1920,
            .height = 1080,
            .framerate_numerator = 30,
            .framerate_denominator = 1

I conducted some tests and discovered that the function SDL_AcquireCameraFrame() is consistently returning frames at exactly 10 FPS.

**Comment by icculus** [comment]
@slouken, we were talking about some change to fix camera access for fps vs interval...or something, I can't remember the specifics...did that ever make it to revision control?

**Comment by slouken** [comment]
Yep, it did.

**Comment by slouken** [comment]
@qqiu-cyt, can you try now?

**Comment by qqiu-cyt** [comment]
@slouken I can confirm the issue is fixed now. Thanks!

**Comment by slouken** [comment]
Great, you're welcome!
