### ISSUE TITLE
SDL_SetAudioDeviceFrequencyRatio and SDL_GetAudioDeviceFrequencyRatio

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#10242]
Since `SDL_SetAudioDeviceGain()` and `SDL_GetAudioDeviceGain()` was added, 
it would be useful to also have a setter and getter for the frequency ratio to match the audio stream API.

**Comment by slouken** [comment]
Maybe we should remove SDL_SetAudioDeviceGain() and SDL_GetAudioDeviceGain()?

**Comment by luppichristian** [comment]
I think it would be useful to keep them since you can use audio devices to "group" audio streams.
For example you could manage the "master" volume and frequency ratio only operating on the audio device, instead of each individual audio stream.

**Comment by icculus** [comment]
We're 100% not adding per-device frequency. I'm not sure what one would use it for, and making that work would probably be disproportionately complex.

But there _is_ something useful to a master gain value to adjust all playing things at once, so I would rather leave that.
