### ISSUE TITLE
[Suggestion] Rename concepts in the Properties API

### ISSUE THREAD

**Issue by Ribiveer** [libsdl-org/SDL#10241]
In the current naming scheme, using the word "properties' might mean

- More than one property
- A property set
- More than one property set

This ambiguity leads to difficulties talking about the properties system. For this reason, I suggest the following naming changes:

- `SDL_CopyProperties` -> `SDL_CopyPropertySet`
- `SDL_CreateProperties` -> `SDL_CreatePropertySet`
- `SDL_DestroyProperties` -> `SDL_DestroyPropertySet`
- `SDL_EnumerateProperties` -> `SDL_EnumeratePropertySet`
- `SDL_GetGlobalProperties` -> `SDL_GetGlobalPropertySet`
- `SDL_LockProperties` -> `SDL_LockPropertySet`
- `SDL_UnlockProperties` -> `SDL_UnlockPropertySet`
- `SDL_EnumeratePropertiesCallback` -> `SDL_EnumeratePropertySetCallback`
- `SDL_PropertiesID` -> `SDL_PropertySetID`

There are also two functions that I think would benefit from a more precise name:
- `SDL_SetProperty` sets a pointer property. Since functions setting properties of other type specify their types, I feel `SDL_SetPointerProperty` would be a better name.
- `SDL_SetNumberProperty` takes a 64-bit signed integer. Personally I think `SDL_SetIntegerProperty` would make more sense, since it's more precise wording (floats are also numbers!).

**Comment by slouken** [comment]
In SDL documentation "properties" almost always means a group of properties associated with an SDL_PropertiesID. The only case this isn't true is when talking conversationally about setting properties on an object... which is always implemented as a group of properties associated with an SDL_PropertiesID.

I understand your confusion, but maybe instead of renaming the functions we can do a better job of describing things in the introduction?

**Comment by Ribiveer** [comment]
I'm not quite sure who wrote the descriptions of the functions, but they all refer to an `SDL_PropertiesID` as "a set of properties". This is understandable, since they are referring to a set and not the properties themselves. While writing the introduction just now, I stumbled upon this as well, and have written it in such a way that it's clear that `SDL_PropertiesID` and the like really mean a set, and not some amount of properties.

Now of course, if confusing names cannot be changed, it's the responsibility of the documentation to pick up the slack and explain their meanings, and that's what I tried to do with my last commit to the wiki. I appreciate that due to API compatibility reasons names can't always be changed. However, if it is possible, I think tackling an issue at its source is the best option!

**Comment by slouken** [comment]
Maybe instead of calling them a set of properties, we can call them a group of properties? Would that be more clear?

**Comment by slouken** [comment]
> * `SDL_SetProperty` sets a pointer property. Since functions setting properties of other type specify their types, I feel `SDL_SetPointerProperty` would be a better name.

This is implemented in https://github.com/libsdl-org/SDL/pull/10243, thanks!

> * `SDL_SetNumberProperty` takes a 64-bit signed integer. Personally I think `SDL_SetIntegerProperty` would make more sense, since it's more precise wording (floats are also numbers!).

This wording is baked into the names of the properties as well, so I don't think we'll be changing that at this point.

**Comment by Ribiveer** [comment]
> Maybe instead of calling them a set of properties, we can call them a group of properties? Would that be more clear?

That would be just as clear, not more not less I'd say. My issue isn't with the documentation, but just that the names of the type and the functions themselves don't make sense. They're names that say one thing but _really_ mean another thing. Not impossible to get used to, but still.

**Comment by slouken** [comment]
Okay, my brain is already adjusted to think of "group of properties" and `SDL_PropertiesID` as synonymous. I'll leave this open for other opinions though.

**Comment by Ribiveer** [comment]
Y'know, that makes sense! I can totally see this as the kind of thing you don't think twice about once you've gotten used to it.

**Comment by slouken** [comment]
@icculus, thoughts?

**Comment by icculus** [comment]
I'm totally fine with "group" instead of "set".

As far as the API goes, I think the hope was "PropertiesID" (plural) was enough to imply it's a group without using a lot of characters. Documentation and programming needs clash sometimes, and this is a good example. I'd probably leave that as-is.

Totally agree about the SetProperty/SetPropertyPointer issue, that's definitely a change for the better (as it was, implied this was the most correct thing to use, but it's also the most complex).

**Comment by slouken** [comment]
Does this make more sense?
https://github.com/libsdl-org/SDL/pull/10244/commits/bcce0b3285a329f2926c132340ff419ab8ba7635

**Comment by Ribiveer** [comment]
As I said previously, I think it's just as clear, not more not less. Personally I prefer calling it a set, since that usually refers to a collection with no duplicates, which this is about.

I guess I hadn't really explained my issue well, because what I was attempting to address in this issue is that I think `SDL_PropertiesID`, and the function names that stem from that, is not the best name for it. For instance, the function `SDL_CreateProperties()` doesn't create any properties! Because it doesn't refer to creating properties, it refers to creating a set/group/collection/whatever.

**Comment by slouken** [comment]
Okay. I don't think that's something we're going to change. Thanks for the feedback!

**Comment by Ribiveer** [comment]
Okay. I guess that's that.

**Comment by slouken** [comment]
The feedback really is appreciated, and even though we decided not to change that, it ended up clarifying the documentation and renaming the Get/SetProperty() API.

Thanks!
