### ISSUE TITLE
Drawing regression in latest SDL3

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10248]
There seems to be a regression in the latest development version of SDL3. I don't know which change introduced this, but my build from July 11th worked fine while the one from July 12th fails.

This is how it should look:
<img width="1232" alt="good" src="https://github.com/user-attachments/assets/cfb7027a-c5e1-4881-92f7-937b037b0cc6">

And this is how it looks now:
<img width="1232" alt="bad" src="https://github.com/user-attachments/assets/809ce47d-e733-4de2-a7dc-1354fe73d1d2">

I am running this on an M1 Mac mini with the latest version of macOS.

**Comment by icculus** [comment]
Are these 8-bit surfaces?

**Comment by andreasgrabher** [comment]
Format of the surface is SDL_PIXELFORMAT_ARGB8888.

**Comment by AntTheAlchemist** [comment]
Same thing happened to me, and I thought it was because I've been using the wrong format all this time. I changed it to `SDL_PIXELFORMAT_RGBA32` and it works now.

**Comment by andreasgrabher** [comment]
Format is obtained from 

```
SDL_Texture* uiTexture = SDL_CreateTexture(sdlRenderer, SDL_PIXELFORMAT_UNKNOWN, SDL_TEXTUREACCESS_STREAMING, width, height);
format = SDL_GetNumberProperty(SDL_GetTextureProperties(uiTexture), SDL_PROP_TEXTURE_FORMAT_NUMBER, NULL);
SDL_Surface* sdlscrn = SDL_CreateSurface(width, height, format);
```

Forcing format to SDL_PIXELFORMAT_RGBA32 does not fix the problem and causes wrong colours.

**Comment by slouken** [comment]
@0x1F9F1, is this related to the blitter changes?

**Comment by andreasgrabher** [comment]
After some testing it seems this commit caused the regression: [https://github.com/libsdl-org/SDL/commit/875c4f0a4ce2003ee64db6218526664fb718d618](https://github.com/libsdl-org/SDL/commit/875c4f0a4ce2003ee64db6218526664fb718d618)

**Comment by slouken** [comment]
Can you see where indexed format surfaces are being used in your code?

**Comment by andreasgrabher** [comment]
It might be this:

```
/*-----------------------------------------------------------------------*/
/**
 * Load an 1 plane XBM into a 8 planes SDL_Surface.
 */
static SDL_Surface *SDLGui_LoadXBM(int w, int h, const Uint8 *pXbmBits)
{
	SDL_Surface *bitmap;
	Uint8 *dstbits;
	const Uint8 *srcbits;
	int x, y, srcpitch;
	int mask;

	srcbits = pXbmBits;

	/* Allocate the bitmap */
	bitmap = SDL_CreateSurface(w, h, SDL_GetPixelFormatForMasks(8, 0, 0, 0, 0));
	if (bitmap == NULL)
	{
		Log_Printf(LOG_ERROR, "SDLGui: failed to allocate bitmap: %s", SDL_GetError());
		return NULL;
	}

	srcpitch = ((w + 7) / 8);
	dstbits = (Uint8 *)bitmap->pixels;
	mask = 1;

	/* Copy the pixels */
	for (y = 0 ; y < h ; y++)
	{
		for (x = 0 ; x < w ; x++)
		{
			dstbits[x] = (srcbits[x / 8] & mask) ? 1 : 0;
			mask <<= 1;
			mask |= (mask >> 8);
			mask &= 0xFF;
		}
		dstbits += bitmap->pitch;
		srcbits += srcpitch;
	}

	return bitmap;
}
```

**Comment by slouken** [comment]
That's very likely. Are you assuming a palette on there?

The other possibility, since I noticed the issue is with text, is that you're using SDL_ttf and haven't updated to the latest code.

**Comment by icculus** [comment]
Okay, so a change we just made is that 8-bit surfaces do _not_ get a palette by default now; the idea is that trying to blit from an indexed surface without a palette will just memcpy() the indices instead of try to map the colors, which can be very useful when you instead to have a destination surface where you're adjusting the palette and just want to fill in the new data from another surface without mapping colors during the blit.

(This is apparently how DirectDraw does it, too.)

The quickest fix: apply a palette to the new thing!

```c
SDL_Palette *palette = SDL_CreatePalette(2);
if (palette) {
    /* Create a black and white bitmap palette */
    palette->colors[0].r = 0xFF;
    palette->colors[0].g = 0xFF;
    palette->colors[0].b = 0xFF;
    palette->colors[1].r = 0x00;
    palette->colors[1].g = 0x00;
    palette->colors[1].b = 0x00;
    SDL_SetSurfacePalette(surface, palette);
    SDL_DestroyPalette(palette);
}
```

@slouken will have to say if I screwed up that code completely, it's untested.

(Also, @slouken, README-migration really needs a code example for this.)

But my suspicion is that SDL_ttf just needs to be updated and it'll solve this problem.

**Comment by slouken** [comment]
This is the biggest change likely to bite people unexpectedly in SDL3. I'm really tempted to roll it back.

**Comment by icculus** [comment]
I'm okay with a rollback, but the one-time fix for things bit by this is dirt-simple and extremely localized.

Maybe a separate function that explicitly creates a surface without a palette would be better though, so you don't get a surprising result from the usual path, and only use it when you definitely want it? I think the new behavior is good, but it could be that the default isn't.

**Comment by slouken** [comment]
That's true, maybe documentation is enough. I'll add a note to README-migration.md and see how that goes.

**Comment by slouken** [comment]
FWIW, having the new behavior is as simple as `SDL_SetSurfacePalette(surface, NULL);` after you create it.

**Comment by slouken** [comment]
But, having a palette on a surface isn't very useful until you set the colors, so you might as well set the palette explicitly. If people are doing that, they're much more likely to either not need to set one, or set a palette already shared with other surfaces, so creating one initially is just wasteful.

**Comment by slouken** [comment]
Maybe it would be helpful to add `SDL_CreatePaletteForSurface(surface)`, which automatically creates it with the right number of entries for the bit depth?

**Comment by andreasgrabher** [comment]
@icculus: Thank you for the code. This fixes my issue. But I think it would be great if there was a simpler solution.

```
	/* Create a black and white bitmap palette */
	palette = SDL_CreatePalette(2);
	if (palette == NULL)
	{
		Log_Printf(LOG_ERROR, "SDLGui: failed to allocate palette: %s", SDL_GetError());
		return NULL;
	}
	palette->colors[0].r = palette->colors[0].g = palette->colors[0].b = 255;
	palette->colors[1].r = palette->colors[1].g = palette->colors[1].b = 0;
	SDL_SetSurfacePalette(bitmap, palette);
	SDL_DestroyPalette(palette);
```
In case it still matters: SDL_ttf is not used.

**Comment by andreasgrabher** [comment]
Update: Seems this one works too:

```
	/* Create an all white bitmap palette */
	palette = SDL_CreatePalette(1<<8);
	if (palette == NULL)
	{
		Log_Printf(LOG_ERROR, "SDLGui: failed to allocate palette: %s", SDL_GetError());
		return NULL;
	}
	SDL_SetSurfacePalette(bitmap, palette);
	SDL_DestroyPalette(palette);
```

**Comment by slouken** [comment]
I've made it even simpler, adding SDL_CreateSurfacePalette():
```c
	/* Create an all white bitmap palette */
	if (!SDL_CreateSurfacePalette(bitmap))
	{
		Log_Printf(LOG_ERROR, "SDLGui: failed to allocate palette: %s", SDL_GetError());
		SDL_DestroySurface(bitmap);
		return NULL;
	}
```

**Comment by slouken** [comment]
In any case, with the new utility function and documentation in README-migration.md, I think we're in a good place now.

Thanks!

**Comment by andreasgrabher** [comment]
Thank you very much for the support! Just a little suggestion: Maybe it would be even simpler to have something like SDL_CreateSurfaceWithPalette instead.

**Comment by slouken** [comment]
You'd have to have two calls anyway, one to create a surface with a palette, and one to get the palette. This way the order of operations is simple and obvious. You create the surface, you create the palette, you take that palette and set colors, and you move on.
