### ISSUE TITLE
[SDL_video] SDL_GetWindowPixelFormat still returns Uint32 instead of an SDL_PixelFormat value

### ISSUE THREAD

**Issue by lumPalette** [libsdl-org/SDL#10257]

**Comment by Navya-Rawat999** [comment]
Hey there. Could you please tell me how to install SDL3 ? I used cmake and added the libraries to my include path. But I can't find the implementations of those header files.

**Comment by lumPalette** [comment]
hi! have you tried this? https://github.com/libsdl-org/SDL/blob/main/INSTALL.md

**Comment by Navya-Rawat999** [comment]
Yeah , I read this and used it's macos install instructions for command line. I built the project using cmake and got all header files but there are no implementations of the functions that are inside header files.

**Comment by slouken** [comment]
Fixed, thanks!
