### ISSUE TITLE
CMAKE_ASM_MASM_COMPILE_OBJECT not set when adding SDL as a subdirectory to CMake

### ISSUE THREAD

**Issue by nevemlaci** [libsdl-org/SDL#10250]
```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_ASM_MASM_COMPILE_OBJECT
```

This is the minimal CMakeList.txt that produces the error on my end.

```cmake
cmake_minimum_required(VERSION 3.25)
project(CMakeTest)

set(CMAKE_CXX_STANDARD 23)
set(SDL_STATIC ON)
set(SDL_SHARED OFF)
set(BUILD_SHARED_LIBS OFF)

add_subdirectory(extern/sdl)
add_subdirectory(extern/sdl_image)
add_subdirectory(extern/sdl_ttf)
add_subdirectory(extern/sdl_mixer)

add_executable(CMakeTest main.cpp)

target_link_libraries(CMakeTest PRIVATE SDL3::SDL3-static)
```
 The only thing I've found that could cause this is <https://github.com/libsdl-org/SDL/blob/2dcb9440f141bef61fce341ed4b7c099d5bf9c50/CMakeLists.txt#L488> 

Building any of the libraries manually from the command line worked, using the same toolchain(Visual Studio).

MinGW works fine.

**Comment by madebr** [comment]
I think you're seeing a CMake issue for which I have no good solution, only a workaround.
When a language is enabled in a subdirectory, that is not enabled in the topdirectory, the top project does not know how to handle object files from the extra enabled language.

My current workaround is to enable the language in the top project.
So do:
```cmake
if(MSVC)
  enable_language(ASM_MASM)
endif()
```
Or link to `SDL3::SDL3-shared` instead.


[In SDL_image, we have a similar issue with `CXX`.](https://github.com/libsdl-org/SDL_image/blob/004aedba893ec6a8b0ce500af5671fab98034074/CMakeLists.txt#L628)

**Comment by madebr** [comment]
Or wait, perhaps `SDL_mslibc_x64.masm` is only needed when building with `-DSDL_LIBC=OFF`.

**Comment by nevemlaci** [comment]
I tried 
```cmake
if(MSVC)
  enable_language(ASM_MASM)
endif()
```

but now the CMAKE_ASM_NASM_COMPILE_OBJECT variable is missing. 
Same when linking SDL3::SDL3-shared

**Comment by madebr** [comment]
nasm is used by some dependencies from SDL_image (dav1d, I think).
So you'd need to do `enable_language(ASM_NASM)` as well.

[SDL_image does the same](https://github.com/libsdl-org/SDL_image/blob/004aedba893ec6a8b0ce500af5671fab98034074/CMakeLists.txt#L435-L437)

Does the `CMAKE_ASM_NASM_COMPILE_OBJECT` error also appear with the minimal example?

**Comment by nevemlaci** [comment]
```cmake
cmake_minimum_required(VERSION 3.25)
project(CMakeTest)

set(CMAKE_CXX_STANDARD 23)

if(MSVC)
    enable_language(ASM_MASM)
    enable_language(ASM_NASM)
    enable_language(ASM)
endif (MSVC)

add_subdirectory(extern/sdl)

add_subdirectory(extern/sdl_image)

add_subdirectory(extern/sdl_ttf)

add_subdirectory(extern/sdl_mixer)

add_executable(CMakeTest main.cpp)

target_link_libraries(CMakeTest PRIVATE SDL3::SDL3-static PRIVATE SDL3_image::SDL3_image PRIVATE SDL3_ttf::SDL3_ttf PRIVATE SDL3_mixer::SDL3_mixer)
```
now I get something different that I guess won't necesseraly be related to SDL
```
CMake Error in extern/sdl_image/external/dav1d/CMakeLists.txt:
  MSVC_RUNTIME_LIBRARY value 'MultiThreadedDebugDLL' not known for this ASM
  compiler.
```

**Comment by madebr** [comment]
We recently removed `CMAKE_MSVC_RUNTIME_LIBRARY` from SDL3's cmake script.
Are you using latest SDL3, or are you setting it yourself?

**Comment by madebr** [comment]
Not sure if it'll fix it, but does adding the following in the `if(MSVC)` conditional change anything? (Try adding before and/or after the `enable_language`'s)
```
set(CMAKE_ASM_COMPILE_OPTIONS_MSVC_RUNTIME_LIBRARY_MultiThreaded         "")
set(CMAKE_ASM_COMPILE_OPTIONS_MSVC_RUNTIME_LIBRARY_MultiThreadedDLL      "")
set(CMAKE_ASM_COMPILE_OPTIONS_MSVC_RUNTIME_LIBRARY_MultiThreadedDebug    "")
set(CMAKE_ASM_COMPILE_OPTIONS_MSVC_RUNTIME_LIBRARY_MultiThreadedDebugDLL "")
```

**Comment by nevemlaci** [comment]
Yeah, that gave me another thing that was supposedly fixed in CMake
```
CMake Error in extern/sdl_image/external/dav1d/CMakeLists.txt:
  MSVC_DEBUG_INFORMATION_FORMAT value 'ProgramDatabase' not known for this
  ASM compiler.
```

**Comment by madebr** [comment]
```cmake
set(CMAKE_ASM_COMPILE_OPTIONS_MSVC_DEBUG_INFORMATION_FORMAT_Embedded "")
set(CMAKE_ASM_COMPILE_OPTIONS_MSVC_DEBUG_INFORMATION_FORMAT_ProgramDatabase "")
set(CMAKE_ASM_COMPILE_OPTIONS_MSVC_DEBUG_INFORMATION_FORMAT_EditAndContinue "")
```

**Comment by nevemlaci** [comment]
Thank you sir, it is working :)
