### ISSUE TITLE
Patching with SDL_migration.cocci does not work

### ISSUE THREAD

**Issue by J0ySF** [libsdl-org/SDL#10260]
I am trying to patch some SDL2 code (the Nuklear SDL demos https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo) and it seems that the commit 2ba76db introduced the following code in SDL_migration.cocci at line 3486:

```
typedef SDL_PixelFormat, SDL_PackedPixelDetails;
@@
- SDL_PixelFormat
+ SDL_PixelFormatDetails
@@
```

which causes the error `incompatible minus and plus code starting on lines 3489 and 3490` when patching (tested on commit 509f3a4). I do not know how coccinelle works but patching works when removing the previously mentioned lines.

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by madebr** [comment]
Not tested, but does the following work? The typedefs were not matching.
```
@@
typedef SDL_PixelFormat, SDL_PixelFormatDetails;
@@
- SDL_PixelFormat
+ SDL_PixelFormatDetails
```
