### ISSUE TITLE
Rename some Get/Set functions to match the new naming style

### ISSUE THREAD

**Issue by captain0xff** [libsdl-org/SDL#10277]
I think these functions (at least some of them) should be renamed to SDL_Get*/SDL_Set* to match the style with other functions
```
SDL_AndroidGetActivity
SDL_AndroidGetCachePath
SDL_AndroidGetExternalStoragePath
SDL_AndroidGetExternalStorageState
SDL_AndroidGetInternalStoragePath
SDL_AndroidGetJNIEnv
SDL_AtomicGet
SDL_AtomicGetPtr
SDL_Direct3D9GetAdapterIndex
SDL_GDKGetDefaultUser
SDL_GDKGetTaskQueue
SDL_WinRTGetDeviceFamily
SDL_WinRTGetFSPath
SDL_AtomicSet
SDL_AtomicSetPtr
SDL_LinuxSetThreadPriority
SDL_LinuxSetThreadPriorityAndPolicy
SDL_iOSSetAnimationCallback
SDL_iOSSetEventPump
```

**Comment by captain0xff** [comment]
Also, maybe rename `SDL_RenderViewportSet` to `SDL_IsRenderViewportSet` as you already have some functions that look like SDL_Is*.

**Comment by slouken** [comment]
> SDL_AndroidGetActivity
> SDL_AndroidGetCachePath
> SDL_AndroidGetExternalStoragePath
> SDL_AndroidGetExternalStorageState
> SDL_AndroidGetInternalStoragePath
> SDL_AndroidGetJNIEnv
> SDL_Direct3D9GetAdapterIndex
> SDL_GDKGetDefaultUser
> SDL_GDKGetTaskQueue
> SDL_WinRTGetDeviceFamily
> SDL_WinRTGetFSPath
> SDL_LinuxSetThreadPriority
> SDL_LinuxSetThreadPriorityAndPolicy
> SDL_iOSSetAnimationCallback
> SDL_iOSSetEventPump

@icculus, should we move Get first, like we do with other functions, or is the platform important namespacing for these?

> SDL_AtomicGet
> SDL_AtomicGetPtr
> SDL_AtomicSet
> SDL_AtomicSetPtr

Atomic is an adjective in this case.

> Also, maybe rename `SDL_RenderViewportSet` to `SDL_IsRenderViewportSet` as you already have some functions that look like SDL_Is*.

The other SDL_Is* functions are "is this a named thing" and the state questions have had "Is" removed, so they read more naturally.

**Comment by icculus** [comment]
> @icculus, should we move Get first, like we do with other functions, or is the platform important namespacing for these?

Normally I would say "SDL_SetLinuxThreadPriority" is more correct, but I kinda want to keep a giant red flag on what these things do: non-portable, special case, but also maybe very important, things.

Agree on atomic stuff. You're doing an "atomic set" of a variable, not setting an atomic variable, although I recognize the difference between those two is quite murky. It's less murky when not using SDL_AtomicInt and instead the APIs that take a void pointer, though.

Is there a better word for the viewport one? SDL_RenderViewportInitialized or something? Don't feel strongly about this one, but I can definitely see the name being confusing (but also, any attempt to use it would clarify that confusion immediately, I assume, when it doesn't take any arguments and returns a bool).

**Comment by slouken** [comment]
Okay, I'm inclined to have the platform functions match the rest of the naming and leave the giant red flag in the documentation rather than being a quirk of the API naming convention that just confuses people.

**Comment by slouken** [comment]
Fixed, thanks!
