### ISSUE TITLE
Clarification of thread safety of SDL_GetStringRule

### ISSUE THREAD

**Issue by 0x1F9F1** [libsdl-org/SDL#10283]
Functions which use SDL_GetStringRule are marked as safe to call from any thread, but it seems like there is the possibility of race conditions when a background thread is processing a returned string whilst the main thread is running the event pump.

Should functions which use SDL_GetStringRule be switched to only being safe to be called from the main thread? Or perhaps use a more delayed method of freeing strings generated on background threads?

**Comment by slouken** [comment]
This was the original reason we weren't going to go with this approach for SDL strings. I know we had some different ideas that all had drawbacks. @icculus, what was the final solution we landed on?

**Comment by icculus** [comment]
Hmm, the current documentation says the pointer is safe until the event queue runs _from any thread_, but yeah, that would be a surprising result for most people.

SDL_FreeLater() holds the event lock, so you can't lose a pointer to a race condition if the main thread is in the middle of running the event queue when it happens. Anything after that just makes the race _after_ different, if the main thread is just calling the event queue in a tight loop: do we require the memory to live at least X milliseconds, or event pumps, before it's eligible? If the background thread gets hung up for a bit, still trouble,

Let me think on this a bit.

**Comment by icculus** [comment]
We could definitely make the pending-deletion list a thread-local thing, which will free everything if _that thread_ pumps the event queue, or the thread terminates, but we chose the event queue because a) we already had something in place for dynamic event memory and b) every app (should) reliably call this function at a regular interval so the app wouldn't have to do anything new. But there's no reason we can't offer a way for a long-running thread that doesn't pump the event queue to clean the list out from time to time.

**Comment by slouken** [comment]
> We could definitely make the pending-deletion list a thread-local thing, which will free everything if _that thread_ pumps the event queue, or the thread terminates, but we chose the event queue because a) we already had something in place for dynamic event memory and b) every app (should) reliably call this function at a regular interval so the app wouldn't have to do anything new. But there's no reason we can't offer a way for a long-running thread that doesn't pump the event queue to clean the list out from time to time.

That's actually not a bad idea. That guarantees that the memory is thread-safe, and we can expose `SDL_FlushEventMemory(0)` as `SDL_TrimThreadMemory()` or `SDL_GiveMyMemoryBackYouPeskyStringRule()` or something. :)
