### ISSUE TITLE
Locale change causes Android app to restart, despite configChanges settings

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#10293]
The `android:configChanges` manifest settings are working for all other things. If I change the device language, the app will shut down and restart. Logcat output doesn't say anything about a forced restart due to configChanges. It just shows a `onDestroy()` and it goes Pete-Tong from there.

Shall I try to debug and step through code to see what's happening?

**Comment by slouken** [comment]
Sure, that would be great.

**Comment by AntTheAlchemist** [comment]
I've looked hard at this issue. I'm not sure how to fix it or what exactly is going wrong, but here is what I do know.

`onConfigurationChanged()` is not being triggered for locale changes, but it's triggered for everything else it deals with. 
Logcat gives nothing away - which doesn't seem right. If an app is restarted due to a config change it doesn't handle internally, logcat would surely explain that?
Logcat does say this though:
```
22:17:09.054  V  SDL main() finished
22:17:09.054  V  activity finished
22:17:09.056  I  System.exit called, status: 0
```
A System.exit suggests a serious app closure, not a config change closure. 

I did wonder if it's because a locale change also requires a BroadcastReceiver on a Intent.ACTION_LOCALE_CHANGED ? But this is where my knowledge is lacking and I'd rather pass it on to someone more experienced. I failed setting up a BroadcastReceiver to test this theory.

I think this is as far as I can get with this for now.

**Comment by AntTheAlchemist** [comment]
Thanks @1bsyl , but that doesn't work, the app still gets force-closed. I'm not seeing a SDL_EVENT_QUIT, either, so there's no chance for the app to save anything. Something else is going on here, because `android:configChanges="...|locale|..."` should be enough to stop the app restarting on a language change.

**Comment by AntTheAlchemist** [comment]
Okay, I found the problem. If I add `layoutDirection` to `android:configChanges`, it works and `onConfigurationChanged()` gets called and the `SDL_EVENT_LOCALE_CHANGED` event comes through okay. We probably also need to add `grammaticalGender`. 

This was infuriating. I'm going to also add `fontScale` & `fontWeightAdjustment` for good measure, unless someone has a good reason not to. 

I'll create a PR to fix this.

**Comment by AntTheAlchemist** [comment]
layoutDirection is already there, but was somehow missing from my project [*facepalm*]. I'll still add the others, as some locale changes will surely trigger `grammaticalGender`.

**Comment by 1bsyl** [comment]
if you get an onDestroy(), at some point, in SDLActivity.java, it calls: SDLActivity.nativeSendQuit(); (can you trace that).
and then it waits for the C thread (500 or 1000 ms), so there really should an SDL_QUIT event for the user, (provided that the app is still polling, but it may be as well in background, since you need to go to the menu to change languages.).


from you log:
```
22:17:09.054  V  SDL main() finished
22:17:09.054  V  activity finished
22:17:09.056  I  System.exit called, status: 0
```
it comes from on Create() : we catch that and prevent the app to re-create the activity (without fully reloading the native c code).
you got the message `"SDL main() finished"` so `mSDLMainFinished` is set. and this means you should have also `"Finished main function"`. It sounds to me the C main finished cleanly.

**Comment by AntTheAlchemist** [comment]
Tested again and the quit event worked like you said this time. Thanks again, and sorry for the fumbling around with this bug - I need to not code tired at 3am.

To conclude, all that was missing was `grammaticalGender`, so we can close this once that PR is merged.

**Comment by 1bsyl** [comment]
@AntTheAlchemist no problem, you're welcome!
