### ISSUE TITLE
`SDL_PrintString` ignores `SDL_FormatInfo.left_justify`

### ISSUE THREAD

**Issue by howprice** [libsdl-org/SDL#10310]
This means that left-aligned fixed width strings are not supported, for example:

```
sprintf(buffer, sizeof(buffer), "    %-14s%s,%s", mnemonic, srcOperand, dstOperand);
```

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by howprice** [comment]
> Fixed, thanks!

Thank you very much. I'm sorry I could find the time to tackle this myself.

Could you please tell me if there is a process to "backport" this change into SDL2?

**Comment by slouken** [comment]
You're welcome! The fix is already backported to SDL2 and cherry-picked for the next release.

**Comment by howprice** [comment]
Wonderful. Thanks again.

**Comment by slouken** [comment]
You're welcome!
