### ISSUE TITLE
Could you provide SDL_URIToLocal to SDL 3 in Windows too, please

### ISSUE THREAD

**Issue by Dragon-Baroque** [libsdl-org/SDL#10319]
Could you make `SDL_URIToLocal` available to SDL 3 in Windows, like you did for all Unixes in commit 71200e94a ?

**Rationale**

In the replacement of `WM_DROPFILES` by a full `IDropTarget` in the Windows Drag and Drop for SDL 3 that I would like to Pull Request in a near future, I have added `text/uri-list` to `CF_HDROP` as supported target types.
For `text/uri-list`, I have the same string splitter and normalizer as in Wayland and in X11, respectively `SDL_strtok_r` and `Windows_URIToLocal`. `Windows_URIToLocal` is a clone of `X11_URIToLocal` before it was excised to `SDL_URIToLocal`.
I would like to remove that clone and use the common `SDL_URIToLocal` instead.

**Advisory**

The various `URIToLocal` make a reference to `gethostname`, which is, in Windows, defined in `winsock.h` and provided by `ws2_32`, neither of which are in the requirements.
I know the proper needed change in `CMakeLists.txt` ( add `ws2_32` to the list `kernel32 .. shell32` ), but that works for the CMake / MingW builds, not for the VisualC builds which I am unable to perform.

**Comment by Kontrabant** [comment]
Sure, it can be elevated out of the *nix code if needed.

**Comment by Kontrabant** [comment]
Can Windows actually return local paths with a hostname in them? It would be much simpler to just #ifdef that bit out vs wiring up and starting the whole socket system on Windows just for this.

**Comment by Dragon-Baroque** [comment]
If I understand, `SDL_URIToLocal` takes an URI and checks whether it names a local file, returns the path to that file if yes.

The URI can be `file:/localPath` or `localPath`, `file:///localPath` or `//localPath` where `localPath` does not start with `/`.
In all these cases, the `is local` condition is satisfied and `SDL_URIToLocal` returns the `localPath` amended of its `%hh`.

When the URI is `file://remoteHost/remotePath` or `/remoteHost/remotePath`, then `SDL_URIToLocal` obtains the local hostname and compares it with `remoteHost`, if equal then uses `remotePath` as `localPath` earlier, otherwise rejects the file as non local.

I find the string comparison of the local hostname and the `remoteHost` rather strange because there are many aliases for the local hostname : `localhost`, `localhost.localdomain` and their IPV4 and IPV6 variants, explicit IP `127.0.0.1` or `::1`, for which the comparison would fail even though `remoteHost` is actually the local host.

Could we place at least a comparison to `localhost`, possibly to `127.0.0.1`, and in Windows, stop there, and in Unix leave the comparison to the `gethostname` ? SDL 3 on Windows would no longer depend on the Windows Socket stack.

Actually, to answer your question, I should point out that I added `text/uri-list` to allow application to application file Drag and Drop, for those applications that did not want to or could not build a `CF_HDROP` clipboard in the Windows case.
This was the case in Exult, were the Game engine ran using SDL 2 and the Drag and Drop file sender ran using GTK+.
