### ISSUE TITLE
[audio][multichannel] SDL_AudioSpecsEqual failed assertion in SDL_PlaybackAudioThreadIterate due to missing stream channel map

### ISSUE THREAD

**Issue by sylware** [libsdl-org/SDL#10317]
I was trying to play a multichannel streams on a multichannel device, and I got this assertion (see title) because the stream does not have a channel map but the device has one.

Anyone can reproduce?

**Comment by icculus** [comment]
Is there an easy way to reproduce this? Or is it just "make a stream and bind it to a device"?

**Comment by icculus** [comment]
Ah, I can reproduce it with loopwave if I force a device channel map. I'll fix this.

**Comment by icculus** [comment]
Should be fixed by 068c7854919cdb67633e7e0ebaff4496226b9659; let me know if you're still having problems after you update to the latest!
