### ISSUE TITLE
Sub-pixel motions are lost or amplified on X11 if application uses absolute motion and pointer warp

### ISSUE THREAD

**Issue by mahkoh** [libsdl-org/SDL#10325]
Tested with SDL2 under Xwayland but might also apply to X in general.

- X sends XI_Motion (500.5, 500.5)
- The driver forwards (500, 500) to SDL_mouse
- The application warps the pointer to (500, 500)
- Repeat

From the perspective of SDL_mouse, there appears to be no motion but the user is moving their mouse by (0.5, 0.5) at a time.

If the user moves their mouse in the opposite direction, the movement is instead amplified due to the rounding down.

The wayland driver seems to be unaffected with the same application.

**Comment by Kontrabant** [comment]
This is unlikely to ever be fixed in SDL2, as mouse coordinates are treated everywhere in the library as integers. SDL3 uses floats for pointer coordinates to avoid losing subpixel precision, including for warp destination coordinates.

SDL2 also doesn't implement setting the pointer position hint via the confinement protocol in the Wayland driver, so it won't appear to be affected because any warp functionality is a no-op.

**Comment by slouken** [comment]
Does this happen with SDL3, using the latest code in main?

**Comment by mahkoh** [comment]
Can I use SDL3 as a drop in in a proprietary game that currently uses SDL2? Otherwise, can you recommend some demo application that I can test SDL3 with?

**Comment by slouken** [comment]
Conceptually, I would think a warp would clear out any fractional mouse motion when it resets the position. I'm curious why this works on Wayland?

**Comment by mahkoh** [comment]
It appears that the wayland driver automatically switches into relative motion mode if the application tries to warp the cursor and the cursor is invisible.

**Comment by slouken** [comment]
That makes sense. I wonder if we should do that for other drivers?

**Comment by Kontrabant** [comment]
Additionally, it looks like XWayland converts absolute pointer coordinates to integers internally: https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/hw/xwayland/xwayland-input.c#L660

With SDL3 under a real X session, subpixel pointer coordinates are passed through. On XWayland, I'm only seeing integers.

>That makes sense. I wonder if we should do that for other drivers?

It wouldn't be hard to move the activation logic to the mouse layer, and the Wayland `SDL_HINT_VIDEO_WAYLAND_EMULATE_MOUSE_WARP` hint could be repurposed for the general case. The one 'gotcha' case to watch out for is when SDL tries to warp the pointer during fullscreen transitions, as this has inadvertently activated the relative mode emulation when it shouldn't if the client has the system cursor hidden in favor of drawing their own software cursor.
