### ISSUE TITLE
SDL_windowswindow.c doesn't compile, the conditional statement isn't written correctly

### ISSUE THREAD

**Issue by Please-just-dont** [libsdl-org/SDL#10330]
See at line 778:

#ifdef SDL_VIDEO_OPENGL_ES2
        if ((_this->gl_config.profile_mask == SDL_GL_CONTEXT_PROFILE_ES ||
             SDL_GetHintBoolean(SDL_HINT_VIDEO_FORCE_EGL, SDL_FALSE)) && /* && SHOULD BE BENEATH the next #ifdef I believe*/
#ifdef SDL_VIDEO_OPENGL_WGL
             (!_this->gl_data || WIN_GL_UseEGL(_this))
#endif /* SDL_VIDEO_OPENGL_WGL */
        ) {
#ifdef SDL_VIDEO_OPENGL_EGL

**Comment by slouken** [comment]
Fixed, thanks!
