### ISSUE TITLE
`SDL_GetFullscreenModeMatch` is not memory-safe

### ISSUE THREAD

**Issue by hwsmm** [libsdl-org/SDL#10353]
https://github.com/libsdl-org/SDL/blob/4d8b938969309e99147b1ec2d632bbe11793e0bf/src/video/SDL_video.c#L1128-L1140

`SDL_GetFullscreenModeMatch` uses `SDL_GetFullscreenDisplayModes` which returns an array, with the actual data at the end, that gets freed _later_, so `SDL_GetFullscreenModeMatch` indirectly returns a pointer that cannot be referenced later.

<br />

https://github.com/libsdl-org/SDL/blob/9758e102bcd530d3110ad3fcd9225fc6f5d71b9c/src/video/SDL_video.c#L1749

The problem is that, `SDL_UpdateFullscreenMode` uses the pointer directly from `SDL_GetWindowFullscreenMode` (which uses  `SDL_GetFullscreenModeMatch` internally) without copying.

<br />

https://github.com/libsdl-org/SDL/blob/9758e102bcd530d3110ad3fcd9225fc6f5d71b9c/src/video/SDL_video.c#L1368

It goes on, and `SDL_SetDisplayModeForDisplay` -> `SDL_SetCurrentDisplayMode` doesn't copy the content of it, so it ends up storing a 'will-be-freed' pointer.

**Comment by slouken** [comment]
Good catch, thank you.

**Comment by hwsmm** [comment]
I found this issue while trying to use `SDL_GetWindowSizeInPixels`, as it kept putting weird data into the passed pointers.

I tried patching it myself, but I couldn't come up with a simple solution, so I just posted this issue :sweat_smile:

**Comment by slouken** [comment]
Yep, it'll take some thought. Thanks for posting!

**Comment by slouken** [comment]
I think this will work, please let me know if you find any problems with it!

**Comment by hwsmm** [comment]
Thanks a lot, it fixes the issue!

**Comment by slouken** [comment]
Great! :)
