### ISSUE TITLE
prerelease-3.x tags

### ISSUE THREAD

**Issue by M2-TE** [libsdl-org/SDL#10367]
Occasionally, there seemed to have been prerelease tags for versions 3.x and above, which sometimes seemed to disappear. These are really useful when trying to include SDL3 using e.g. CMake's FetchContent API and wanting to freeze the version to play nice with ImGui. In the FetchContent example, specific commit hashes can be used, but those fail with the GIT_SHALLOW option.

Is there a specific reason not to have these prerelease tags? I see that prerelease-3.0.0 exists, but that one is rather old at this point.

**Comment by slouken** [comment]
Because the API is changing daily and we don't want people to freeze on a specific version. We have an ABI stable release coming soon, and we'll tag that for people to play with.
