### ISSUE TITLE
Android `SDL_GetPreferredLocales` memory corruption

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#10362]
Easily reproducible by simply calling `SDL_GetPreferredLocales` anywhere: This started happening when this function was converted into returning temp memory. 

Memory corruption will cause random effects. Repeated calls will guarantee a crash.

I first noticed a crash after a `PumpEvents()`, during freeing temp memory.

**Comment by slouken** [comment]
Fixed, thanks!
