### ISSUE TITLE
SDL_RenderTexture9Grid enhancement / freature request

### ISSUE THREAD

**Issue by zaun** [libsdl-org/SDL#10389]
SDL_RenderTexture9Grid is a very nice addition but just falls short on being 100% useful. As is the function works perfectly if the corners are all the same and all square, but if the 3x3 grid needs to be flexible this function won't work and we'll need to make 9 individual calls.

What would be ideal is having a SDL_RenderTexture9Grid call that works with 4 values, the width of the top 2 widths and the 2 heights. This lets the Left/Right corners have different widths and the Top/Bottom conners have different heights. This would allow an image like the attached to be split properly without having the top center stretched badly as either the top left or right corner could contain the color divide.

![metalPanel_blueCorner](https://github.com/user-attachments/assets/86dd359b-71dd-4ded-8316-e67733b23313)

**Comment by slouken** [comment]
Sure, feel free to submit a PR that does what you want.

I'd be curious why you can't use a square texture for the above image? What is the output intended to look like?

**Comment by zaun** [comment]
So with the current `SDL_RenderTexture9Grid` the above image turns out to look like this:
<img width="868" alt="Screenshot 2024-07-26 at 5 09 15 PM" src="https://github.com/user-attachments/assets/53bb9703-ccfc-4ab9-8c87-5ae28529cc08">

With the updated function it lets you do either of these:
<img width="912" alt="Screenshot 2024-07-31 at 12 58 37 PM" src="https://github.com/user-attachments/assets/fb26cf50-cc04-4e95-93a7-bc0669ce3e88">
<img width="912" alt="Screenshot 2024-07-31 at 1 01 52 PM" src="https://github.com/user-attachments/assets/a3be2cb4-9bf0-4796-b002-0a28972a92da">

**Comment by slouken** [comment]
I'm wondering if this should be the default function instead of the simpler one?

**Comment by zaun** [comment]
I would be okay with either way. I didn't modify the existing functions mostly because I don't have any idea about dynapi besides just running the script and when I tried without making a new function I got errors compiling.

In general I think having the one function would be fine, it's not hard to type the same number 4 times if you want things to be uniform.

**Comment by slouken** [comment]
Added, thanks!
