### ISSUE TITLE
New temporary memory management can't work with threads

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10387]
I am afraid the new temporary memory management has critical design flaws. In its current state it won't work with threads. SDL_FreeTemporaryMemory() can't be called safely. This example should explain why:

Let's say our application has three threads:
- Thread 1 checks for mice using SDL_GetMice(). It only needs the number of mice and returned memory can be discarded immediately.
- Thread 2 checks for keyboards using SDL_GetKeyboards(). The returned information is required for further processing.
- Thread 3 checks for joysticks using SDL_GetJoysticks(). The returned information is required for further processing.

Now there are three possibilities:
- Call SDL_FreeTemporaryMemory() in thread 1 after SDL_GetMice(). This might free temporary memory of threads 2 and 3 even if SDL_ClaimTemporaryMemory() is called immediately after SDL_GetKeyboards() and SDL_GetJoysticks(). This is a race condition and will fail sooner or later.
- Call SDL_FreeTemporaryMemory() after SDL_ClaimTemporaryMemory() in thread 2. This will free temporary memory of thread 1 and preserve temporary memory of thread 2 but may free temporary memory of thread 3 before it can be claimed. This is a race condition and will fail sooner or later.
- Call SDL_FreeTemporaryMemory() right before quitting the application. This will work but renders the new temporary memory system useless.

All in all using this new temporary memory management is too complicated and will cause lots of issues in threaded applications. I think it should be removed in favour of the classic method using SDL_free() individually. It just should be clarified at a central point which functions return data that needs to be freed at some point.

**Comment by icculus** [comment]
We're removing this system, so it doesn't matter, but FreeTemporaryMemory only frees memory allocated on the current thread.
