### ISSUE TITLE
define of SDL_GetKeyboardState cannot avoid discarded-qualifiers warning

### ISSUE THREAD

**Issue by Jar387** [libsdl-org/SDL#10380]
The define of SDL_GetKeyboardState is const Uint8 *SDL_GetKeyboardState(int *numkeys) in the newest version of SDL2
It returns a const pointer. So I can't pass it to a non-const global pointer var without triggering discarded-qualifiers warning.
I think if we just detect keyboard status without event trigger. We should use a global Uint8 pointer and update it every render loop.
So the solution is to remove "const" from function declaration. Need I fork it and send a tiny PR?

**Comment by slime73** [comment]
The solution would be for you to declare a `const UInt8 *` global variable instead, which can still be reassigned later whenever you call SDL_GetKeyboardState.

**Comment by Jar387** [comment]
but reassign any const var will cause compile-time error. I'm using c99 and gcc 11.4.0-1ubuntu1~22.04

**Comment by slime73** [comment]
`const UInt8 *` disallows modification of the memory (the array), but allows reassigning the variable to a different pointer, so  there'll be no compile time error unless you're trying to modify the array.

**Comment by Jar387** [comment]
It works :)
thanks very much
