### ISSUE TITLE
[SDL3] opengl issue

### ISSUE THREAD

**Issue by r-tmp** [libsdl-org/SDL#10397]
using opengl used to work until recently, now it doesn't build with the following errors:

```
unresolved external symbol __imp_glClear referenced in function main
unresolved external symbol __imp_glClearColor referenced in function main	
unresolved external symbol __imp_glClearStencil referenced in function main
unresolved external symbol __imp_glViewport referenced in function main	
```

I've used the cmake file example here:
https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md

The cmake file compiles as it is, it fails to build as soon as I make the following changes:

![Screenshot 2024-07-27 223058](https://github.com/user-attachments/assets/78b54da0-216a-4c88-be3a-5aed6e3dc7bc)

What am I doing wrong here?

* PS: in my actual project I use `SDL_CreateWindow` instead of `SDL_CreateWindowAndRenderer`

**Comment by icculus** [comment]
You need to add the OpenGL libraries to your build.

**Comment by icculus** [comment]
Closing this as not an SDL bug.

I would either ask on [our forums](https://discourse.libsdl.org/) or [our Discord server](https://discord.gg/BwpFGBWsv8) if you want some help getting OpenGL up and running...both have places are full of super-friendly and helpful people!
