### ISSUE TITLE
Issue with FPS Capping at Monitor Refresh Rate Even When VSync is Disabled

### ISSUE THREAD

**Issue by edwardgushchin** [libsdl-org/SDL#10393]
Hello everyone! I apologize for posting this here, but I couldn't find documentation that addresses my question about VSync behavior.

I've written a simple FPS counter and encountered a strange behavior: all the rendering drivers available on my system, except for the `software` driver, show 144 FPS when VSync is disabled (`SDL_SetRenderVSync(renderer, 0)`). This matches the refresh rate of my monitor.

I recall from using SDL2 previously that FPS would be much higher than the monitor's refresh rate unless VSync was explicitly enabled.

So, my question is: Is this behavior normal, and how (if possible) can I achieve FPS higher than the monitor's refresh rate?

## System Information:

**Operating System**: Windows 10

**Available Rendering Drivers**:
1. direct3d11
2. direct3d12
3. direct3d
4. opengl
5. opengles2
6. vulkan
7. software

Any guidance or clarification on this matter would be greatly appreciated!

**Comment by AntTheAlchemist** [comment]
Nvidia driver settings on Windows allow you to override vsync behaviour, including forcing it to be on for applications. Is something like that the case? 

![image](https://github.com/user-attachments/assets/f6524628-669e-4d10-9cbb-4678870fff4a)

**Comment by edwardgushchin** [comment]
@AntTheAlchemist I should have known that this might be the reason. Thank you!

**Comment by AntTheAlchemist** [comment]
No problem! It's caught me out a few times over the years as well
