### ISSUE TITLE
[SDL3] testffmpeg render issue

### ISSUE THREAD

**Issue by WoHal** [libsdl-org/SDL#10402]
I am experiencing rendering issues when attempting to play the [example.mkv](https://drive.google.com/file/d/1nb2wOhpgNXz_AH5hB8spkzb3LMNAfJmB/view?usp=drive_link) video file using `testffmpeg` on macOS Sonoma 14.1 .
The `example.mkv` file is a segment extracted from the original video using `ffmpeg`.
```
ffmpeg -ss 00:00:00 -to 00:02:00 -i origin.mkv -c copy example.mkv
```

```
> ffprobe -v error -select_streams v:0 -show_entries stream=pix_fmt,color_range,color_space,color_transfer,color_primaries,chroma_location -of default=noprint_wrappers=1 example.mkv
pix_fmt=yuv420p10le
color_range=tv
color_space=bt709
color_transfer=bt709
color_primaries=bt709
chroma_location=left
```

It appears that `input_type` should not be set to `INPUTTYPE_HDR10` directly.

https://github.com/libsdl-org/SDL/blob/35e42d0a254f230bb736cf993a9c3855ea1680a1/src/render/metal/SDL_render_metal.m#L1361-L1364

<img width="1081" alt="Screenshot 2024-07-28 at 15 02 55" src="https://github.com/user-attachments/assets/29185d50-a0e8-4cbd-ab41-616cb4f95cb2">

**Comment by slouken** [comment]
Fixed, thanks!
