### ISSUE TITLE
SDL3 - iOS needs SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE=0 if mouse pointer is hidden

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/SDL#10413]
For Exult we hide the mouse pointer and with the change 66eb2ea44 we need to set SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE to 0 to make touch work correctly. Otherwise it seems the pointer is stuck in the upper left area.
I have not yet tested on Android, whether we need it there as well.

Tagging @Kontrabant as I'm not sure whether this is considered a bug or not.

**Comment by slouken** [comment]
@Kontrabant, this is on iOS. Maybe we need some special consideration there for touch input?

**Comment by Kontrabant** [comment]
I'm wondering if we even need it enabled by default on the non-desktop platforms, given that this is mainly to help legacy titles on platforms where constantly warping the pointer doesn't behave as expected?

**Comment by DominusExult** [comment]
JFYI it also affects Android builds (needing `SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE=0` to work) after this change.

**Comment by slouken** [comment]
> I'm wondering if we even need it enabled by default on the non-desktop platforms, given that this is mainly to help legacy titles on platforms where constantly warping the pointer doesn't behave as expected?

Probably not, but it sounds like a bug that if it's enabled for some reason (maybe someone sets it in their application?) it affects touch input.

**Comment by slouken** [comment]
I'll take a look and see what's going on.

**Comment by Kontrabant** [comment]
@DominusExult, can you try the main branch now and see if your issue is fixed?

**Comment by slouken** [comment]
I'm having trouble getting a repro case here.

Are these the correct steps?
1. Hide the cursor
2. Warp the mouse to 0,0
3. Mouse events no longer report change in position

Is that right?

At least with those steps, I'm seeing mouse relative mode being enabled and then touch moves the mouse.

Are there any other hints in play or something I'm missing?

**Comment by DominusExult** [comment]
Maybe it‘s
1. start with the mouse pointer hidden
2. Unhide it
3. Hide it again (maybe by touch)
4. ..

**Comment by slouken** [comment]
Can you debug the SDL mouse code and see what's happening there? I can't repro with a simple test case.

**Comment by DominusExult** [comment]
I need some help with what you need to be logged where in SDL source and in which form, that's not my strength. (Or I can send a package with Exult source etc. and data to make it run on your end).

**Comment by slouken** [comment]
Yeah, a package with repro steps would be helpful, thanks!

**Comment by DominusExult** [comment]
I've sent you an email

**Comment by slouken** [comment]
I got it, thanks. However, I'm seeing different behavior.

Regardless of the value of the hint, the green cursor is stuck in the upper right area of the game, but clicking on the map shows a message "Clicked at tile (x, y)" and the values seem to match up with where I'm clicking. If I drag briefly the character will walk to the area I clicked. If I click on an object I get a dropdown menu of actions.

If I try to click on the map, the green cursor is outside the map and it just closes, I don't teleport at all.

As I said, this doesn't change based on the value of the hint. I haven't played this before, so I'm not sure whether this is correct behavior or not?

**Comment by DominusExult** [comment]
You have to double tap/click the map to get the cheat map (without the compass in the upper right) that teleports you to where you click on it.
The teleport part is important as this only triggers the odd behaviour.

**Comment by slouken** [comment]
So this is the issue. The mouse gets hidden, and then this code runs, which triggers the automatic relative mouse mode.
```
	//	teleported = 1;
	// generate mousemotion event
	float x;
	float y;
	SDL_GetMouseState(&x, &y);
	SDL_WarpMouseInWindow(win->get_screen_window(), x, y);
```

@Kontrabant, do we need a better heuristic for entering relative mouse mode? Maybe repeated warps to the center?

**Comment by DominusExult** [comment]
Hmm, I wonder if we actually need this in Exult anymore. Commenting that whole part seems to make no difference and that code is essentially 23 years old.
We use SDL_WarpMouseInWindow() in our main mouse code as well https://github.com/exult/exult/blob/master/mouse.cc#L162

**Comment by DominusExult** [comment]
The problem is fixed on our side by removing the one `SDL_WarpMouseInWindow()` in our code that Sam pointed at. The other one is not affecting our mobile platforms.
Up to you to decide whether you need to follow up with a general fix for when  `SDL_WarpMouseInWindow()` is used on iOS/Android.

**Comment by Kontrabant** [comment]
> @Kontrabant, do we need a better heuristic for entering relative mouse mode? Maybe repeated warps to the center?

I think that would be a good idea. Maybe more than one warp to center within a certain timeframe (a 30ms window or so)?
