### ISSUE TITLE
Android Rumble Crash joystick->hwdata == null if rumble attempted and GamePad disconnects

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#10422]
SDL_sysjoystick.c, `ANDROID_JoystickRumble()`, line #592 crashed due to "item" being null. This happened on an 8BitDo Pro 2, connected via Bluetooth. Rumble (& triggers) were attempted, but failed, as not supported (as per usual with Bluetooth & Android). Something in SDL's background keep's retrying the rumble ? and sets an error "That operation is not supported". If I slide the switch of this GamePad to a different mode, to force it to disconnect, this crash happens after a `SDL_PumpEvents()`, which triggers an `SDL_UpdateJoysticks()`, which calls `ANDROID_JoystickRumble()` on an invalid joystick, which has a nulled "hwdata". 

Convoluted bug report, sorry, but is it enough to show what's happening? I'll keep trying to see if it's easy to trigger other ways.

**Comment by slouken** [comment]
That makes total sense. Can you try the patch in the PR and see if that fixes it for you?

**Comment by AntTheAlchemist** [comment]
Yep! That appears to have fixed it.

**Comment by slouken** [comment]
Thanks!
