### ISSUE TITLE
Wishlist: Console API

### ISSUE THREAD

**Issue by KirillAldashkin** [libsdl-org/SDL#10430]
It would be nice to have an API to interact with console:
* write text with configured foreground/background color
* show/hide console cursor, query/change it's position
* access standard input/output/error as `SDL_IOStream`
* query/change a console title

as it can be useful for creating interactive CLI programs.

![image](https://github.com/user-attachments/assets/09139ea8-b03f-49ab-b34b-8d347946f14a)

**Comment by slouken** [comment]
There are currently no plans for this, but there are lots of libraries out there for this, it doesn't need to be a part of this SDL library.
