### ISSUE TITLE
no longer possible to initialize and create hidden window on headless linux (regression in SDL 2.30.1)

### ISSUE THREAD

**Issue by manylegged** [libsdl-org/SDL#10436]
My game has a headless mode where it runs on a server, downloading player generated content and taking screenshots of it.

```SDL_Init(SDL_INIT_VIDEO);
SDL_Window *window = SDL_CreateWindow("OpenGL test", -32, -32, 32, 32, SDL_WINDOW_OPENGL|SDL_WINDOW_HIDDEN);
SDL_GLContext context = SDL_GL_CreateContext(window);
... draw stuff with opengl, take screenshot, exit
```

Since version 2.30.1, SDL_Init() fails with "x11 not available".
I can toggle the sdl version back and forth with my package manager, and 2.28.5 works fine, whereas all version from 2.30.1 to 2.30.5 fail.

Could possibly be related to the wayland fixes in 2.30.1?

If it matters, my server is running Manjaro Linux, an Arch derivative.
I'm not sure how popular use case is, but I found at least one forum reference: https://discourse.libsdl.org/t/possible-to-run-sdl2-headless/25665

**Comment by slouken** [comment]
We were having people building without X11 support and wondering why creating a window succeeded but didn't show a window, so we made offscreen support opt-in. Try explicitly setting the offscreen driver with `SDL_SetHint(SDL_HINT_VIDEODRIVER, "offscreen");`

**Comment by slouken** [comment]
Actually, I don't think that change made it to SDL2 yet.

That message, "x11 not available" will only happen if the X11 driver is being forced by a hint or environment variable, or if you linked to an X11-only framework like glew or NVIDIA Cg.

Does setting the hint work for you?

**Comment by manylegged** [comment]
The hint totally works! Thank you so much for the quick response! I will post the solution on the forum post I posted earlier, in case anyone else has the same problem.

**Comment by slouken** [comment]
You're welcome!
