### ISSUE TITLE
Fullscreen-desktop window squashed on Macbook with camera notch

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#10453]
When going into a fullscreen space on macOS, the window is placed below the notch on recent Macbooks with camera notches. Ideally we want the window to extend to the entire screen and the safe area to be updated to reflect the notch.

**Comment by slime73** [comment]
Recent mac laptops that have the notch have a non-standard aspect ratio when it's included - 16:10 without it, and ~15.4:10 with it. I wonder if that combined with the notch still preventing visibility for part of that area would cause surprises for certain apps? Maybe it makes sense to have notch-aware fullscreen opt-in via a hint on macOS?

**Comment by slouken** [comment]
Good point. I'll go ahead and close this for now, and we can add a hint later if we want.
