### ISSUE TITLE
SDL3: SDL_Free will cause crashes upon usage

### ISSUE THREAD

**Issue by atsb** [libsdl-org/SDL#10458]
I've migrated one of my projects to SDL3 a while ago and there were no issues, however, using the latest master, SDL_Free causes crashes unless all instances of it are removed.  This was never an issue before in other SDL3 commit hashes.

The commit I am using is: f01d427

![sdl_free_crash](https://github.com/user-attachments/assets/0a24511e-e89a-4b04-9246-a8be768d33c5)

**Comment by slouken** [comment]
This means that there is memory corruption in your program. Are you seeing it with the SDL test programs? Are you freeing event memory which no longer needs to be freed?

**Comment by icculus** [comment]
Or you're freeing something that is no longer malloc'd in SDL3...what data are you freeing in this case?

**Comment by atsb** [comment]
In this case, I am free'ing a char filepath (Goes to SDL_GetBasePath).  Since it worked in previous commits, this is why I was curious if it was a regression or not.

`char *path, *dir;
path = malloc(512);

if ((dir = I_GetUserDir())) {
        snprintf(path, 511, "%s%s", dir, file);
Free(dir);`

**Comment by slouken** [comment]
SDL_GetBasePath() returns a `const char *` now. You should have gotten a compiler error when you tried to assign it to a non-const `char *`

**Comment by icculus** [comment]
Or the SDL headers you built against need to be updated...this changed relatively recently.

We're almost done making changes like this, I promise.
