### ISSUE TITLE
Why SDL_RenderReadPixels get no data when in main thread?

### ISSUE THREAD

**Issue by gangster-puppy** [libsdl-org/SDL#10481]
1. On the Linux platform, the sub-thread is a rendering thread that has been calling SDL_RenderPresent to render video data.

2. At this time, when I call SDL_RenderReadPixels on the main thread to obtain the pixel data of the current frame, the result is empty. Why? 

3. The renderer uses GLES2. I tried it on Windows and it worked fine. The renderer used on Windows is D3D11.

Can anyone tell me a workaround? Thx...

**Comment by slouken** [comment]
You should call SDL_RenderReadPixels() before SDL_RenderPresent(), and on the same thread as you're doing rendering. You can then pass the returned pixels off to the main thread yourself.

**Comment by gangster-puppy** [comment]
Yes，you are right! And I try to  use SDL_HideWindow before SDL_RenderReadPixels so that SDL_RenderPresent does not work, Haha...
