### ISSUE TITLE
[SDL2] Changing refresh_rate to float instead of int.

### ISSUE THREAD

**Issue by vanfanel** [libsdl-org/SDL#10495]
Hello,

Some emulators (like current WinUAE's codebase port to GNU/Linux, called Amiberry) try to detect the in-use video mode, and/or try to adjust internal emulation framerate to the current physical display refresh rate.
That produces always-smooth, perfect screen refresh, as expected when emulating those platforms which were equiped with specialized scrolling hardware.
But that only works if the internal frame rate matches the external (host) display refresh rate exactly to the decimal (ie: emulate an Amiga 58.84xxxx Hz video mode on a 60.000000Hz display and you get micro-stuttering every few seconds).

SDL2 can report in-use refresh rate by means of **SDL_GetDesktopVideoMode()** which returns an **SDL_VideoMode** pointer.
The problem is that the refresh_rate in an SDL_VideoMode struct is an integer, truncated from the native video systems exact refresh rate. For example, in the SDL2 Wayland backend, I see:

https://github.com/libsdl-org/SDL/blob/81252eb06d525de060a53a05581e7aeb01da03f6/src/video/wayland/SDL_waylandvideo.c#L594
and
https://github.com/libsdl-org/SDL/blob/81252eb06d525de060a53a05581e7aeb01da03f6/src/video/wayland/SDL_waylandvideo.c#L615

...which painfully eliminate precission from the MHz cipher and cripple it into a two-digit integer, unusable for precise video mode synchronization on emulators.

So, would it be possible (I am willing to do a PR) to transform the integer member in **SDL_VideoMode** struct into a float, or at least make SDL2 report the refresh rate using that same integer, but in MHz instead of Hz? I can modify the Wayland and KMSDRM backends to do so. Other backends are out of my scope.

Thanks

**Comment by slime73** [comment]
SDL3 provides fractional values for refresh rates: https://wiki.libsdl.org/SDL3/SDL_DisplayMode

**Comment by vanfanel** [comment]
@slime73 You are right on that, yes:
https://github.com/libsdl-org/SDL/blob/7b97fd3b4458bc7c43f14738eda98d77503851b2/src/video/wayland/SDL_waylandvideo.c#L744
https://github.com/libsdl-org/SDL/blob/7b97fd3b4458bc7c43f14738eda98d77503851b2/src/video/wayland/SDL_waylandvideo.c#L745
That's very good.

I take backporting that to SDL2 is too much of an API break, but what about returning MHz in SDL2 or making that dreaded **refresh_rate** integer in SDL_VideoMode into a float?

**Comment by slime73** [comment]
Both of those would break existing code written for SDL2, so I doubt that's on the table. Features like accurate refresh rate are a good reason to look into updating a project to support SDL3. :)

**Comment by vanfanel** [comment]
What about adding the **mode.refresh_rate_numerator** and **mode.refresh_rate_numerator** to the SDL_VideoMode struct definition in SDL2?
That wouldn't cause any API breaking at all...
@slouken , what do you think? Would that be acceptable?

**Comment by slouken** [comment]
> What about adding the **mode.refresh_rate_numerator** and **mode.refresh_rate_numerator** to the SDL_VideoMode struct definition in SDL2? That wouldn't cause any API breaking at all (unless I don't know what an API break is, that is). @slouken , what do you think? Would that be acceptable?

That would change the size of the structure and would be an ABI break. SDL3 ABI freeze is right around the corner, so now's a good time to check it out.

**Comment by vanfanel** [comment]
> > What about adding the **mode.refresh_rate_numerator** and **mode.refresh_rate_numerator** to the SDL_VideoMode struct definition in SDL2? That wouldn't cause any API breaking at all (unless I don't know what an API break is, that is). @slouken , what do you think? Would that be acceptable?
> 
> That would change the size of the structure and would be an ABI break. SDL3 ABI freeze is right around the corner, so now's a good time to check it out.

Understood, sir!
