### ISSUE TITLE
Memory leak in get_driindex() of SDL_kmsdrmvideo.c when DRM Master can't be obtained

### ISSUE THREAD

**Issue by davidk408** [libsdl-org/SDL#10499]
Noticed a coding error while I was visually inspecting the `get_driindex()` function in SDL_kmsdrmvideo.c.

When skipping a device (connector) because DRM Master cannot be obtained, the `continue` statement on line 144 is taken and the code fails to call `KMSDRM_drmModeFreeConnector(conn)`, resulting in a memory leak.

https://github.com/libsdl-org/SDL/blame/2428d906f15dc465a6cdb479836b70fd6e3b1e55/src/video/kmsdrm/SDL_kmsdrmvideo.c#L144

**Comment by slouken** [comment]
Can you take a look at https://github.com/libsdl-org/SDL/pull/10504 and see if that fixes it?

**Comment by slouken** [comment]
> Can you take a look at #10504 and see if that fixes it?

Is the thumbs up "that fixed it" or "I'll take a look"?

**Comment by davidk408** [comment]
Sorry for the ambiguity of the thumbs-up -- your fix looks good!

**Comment by slouken** [comment]
Great, thanks!
