### ISSUE TITLE
SDL_SetWindowsMessageHook() issues

### ISSUE THREAD

**Issue by dtromb** [libsdl-org/SDL#10497]
Over the course of the past few days trying to implement a simple custom-drawn border resizable window, I've noticed a couple of rough spots relating to the `SDL_SetWindowsMessageHook()` feature, which allows users to intercept or override SDL event loop processing for specific Windows events.

First, any messages that occur during a modal resize are not passed to the hook at all!   This is because the hook is currently only being called before message translation, from the SDL event loop, and not from the WndProc that actually handles the messages.  Since modal resize events are added directly to the message queue by the operating system, and not dispatched by the user, they are not seen by the SDL event loop and therefore cannot be sent to the hook.

Second, many windows events expect a return value from the handler function that affects the behavior of the system - there is two-way communication between the event source and the event handler.  However, although the `SDL_WindowsMessageHook `callback facility allows us to override the default SDL processing, it does provides any way of setting the return value from the user's handler.  This results in a zero value always being returned, and makes implementation of some behaviors totally impossible (for example, to implement my use case, I need to return `WVR_VALIDRECTS` from the `WM_NCCALCSIZE` handler, which is currently not possible without modifying SDL source.

After some helpful conversations with Discord user @playmer, he felt this should be addressed and we discussed ways to do it, changing the callback type slightly and moving the processing to the WndProc.   I've since gone ahead and made the changes in a fork and would be happy to present for CR / PR on this issue.

**Comment by slouken** [comment]
Great, please feel free to make a PR to address this.

Thanks!

**Comment by slouken** [comment]
Closed per discussion on https://github.com/libsdl-org/SDL/pull/10500
