### ISSUE TITLE
SDL_SetSurfaceColorKey() sets wrong color

### ISSUE THREAD

**Issue by Tsukulimer** [libsdl-org/SDL#10509]
I have a palette with 2 colors:
```
{
    {92, 75, 29, 255}, // orange
    {255, 255, 255, 255} // white
}
```

Also I have a surface with **SDL_PIXELFORMAT_INDEX8** format fully filled with 0
If I just create a texture from this surface, then everything is ok and I can see plain orange rectangle,
but if I uncomment `SDL_SetSurfaceColorKey(details, texture_palette, 255, 0, 255)`, then the texture becomes transparent.
I don't have this color in the palette at all.

Some strange examples:
if palette[1] == 255, 0, 0, 255, then palette[0] is transparent
if palette[1] == 200, 0, 100, 255, then palette[0] is opaque

So somehow palette[0] depends on palette[1]

Im using the latest build of SDL from main branch

Here's my code: (Without error checking, but the order is the same)

```
SDL_Color palette[] =
{
    {192,75,29,255},
    {255,0,100,255},
};

SDL_Palette *texture_palette = SDL_CreatePalette( SDL_arraysize(palette));

surface = SDL_CreateSurface(w, h, SDL_PIXELFORMAT_INDEX8);

SDL_SetPaletteColors(texture_palette, palette, 0, SDL_arraysize(palette));
SDL_SetSurfacePalette(surface, texture_palette);

const SDL_PixelFormatDetails *details = SDL_GetPixelFormatDetails(surface->format);
Uint32 color_key = SDL_MapRGB(details, texture_palette, 255, 0, 255);
SDL_SetSurfaceColorKey(surface, SDL_TRUE, color_key)

texture = SDL_CreateTextureFromSurface(renderer, surface);
```

same effect with opengl and vulkan renderers

OS: Linux
Videocard: Intel HD 500

**Comment by Tsukulimer** [comment]
working example:

```
#include <SDL3/SDL.h>

int main()
{
    SDL_Window *window = SDL_CreateWindow("test", 640, 360, SDL_WINDOW_RESIZABLE);
    SDL_Surface *surface;
    SDL_Texture *texture;
    SDL_Renderer *renderer = SDL_CreateRenderer(window, NULL);


    SDL_Color palette[] =
    {
        {192,75,29,255},
        {255,0,0,255}, // transparent
//        {255,0,100,255}, // opaque
    };

    SDL_Palette *texture_palette = SDL_CreatePalette( SDL_arraysize(palette));

    surface = SDL_CreateSurface(100, 100, SDL_PIXELFORMAT_INDEX8);

    SDL_SetPaletteColors(texture_palette, palette, 0, SDL_arraysize(palette));
    SDL_SetSurfacePalette(surface, texture_palette);

    const SDL_PixelFormatDetails *details = SDL_GetPixelFormatDetails(surface->format);
    Uint32 color_key = SDL_MapRGB(details, texture_palette, 255, 0, 255);
    SDL_SetSurfaceColorKey(surface, SDL_TRUE, color_key);

    texture = SDL_CreateTextureFromSurface(renderer, surface);
    SDL_RenderClear(renderer);
    SDL_RenderTexture(renderer, texture, NULL, NULL);
    SDL_RenderPresent(renderer);
    SDL_Delay(2000);
}
```

**Comment by slouken** [comment]
I don't think this is a bug. You're using SDL_MapRGB() to get the colorkey, which will find the closest color in the palette. If you want to get an exact match you'll need your own function to go through and return an error if the color isn't in the palette.

**Comment by Tsukulimer** [comment]
Ah, I see. Well, sorry for wasted time.
I suspected this behaviour, but it was strange for me, that sometimes this function just can't find any color.
So this is not recommended to use this function on pack of images with and without key color to make pink color transparent only if it exists

**Comment by slouken** [comment]
> So this is not recommended to use this function on pack of images with and without key color to make pink color transparent only if it exists (when each image has its own palette)

That's correct.
