### ISSUE TITLE
SDL_CreateDirectories / SDL_CreatePath

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#10502]
On Win32 `SDL_CreateDirectory` only works if the last specified folder name in path has to be created.
It would be useful to implement a function called for example `SDL_CreateDirectories` or `SDL_CreatePath` that actually creates all the missing folders.
Maybe this behaviour could be implemented in `SDL_CreateDirectory` directly.

**Comment by icculus** [comment]
There was some reason we _didn't_ do this, but I can't remember why; I'm going to poke around the issue tracker and try to figure that out later today. If I can't find a good reason, we'll add this.
