### ISSUE TITLE
SDL3: Mouse cursor gets locked when calling SDL_HideCursor()

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10505]
I have a new issue with SDL3. In some cases SDL_HideCursor() locks the cursor to my window or permanently hides it and it won't get visible if I move beyond the window bounds. When calling SDL_ShowCursor() and SDL_HideCursor() again it mostly does not happen anymore. This did not happen with SDL3 versions from a few days ago. It also does not happen with the latest release version of SDL2 (2.30.6).

**Comment by slouken** [comment]
@Kontrabant, related to your relative mode changes?

**Comment by Kontrabant** [comment]
If an attempt to warp the mouse was made after hiding it, then it may have hit the warp emulation path.

@andreasgrabher, does this still happen with SDL3 main now that #10492 is merged?

**Comment by andreasgrabher** [comment]
The problem seems to be gone. Thank you!

**Comment by andreasgrabher** [comment]
The problem seems to be gone. Thank you!
