### ISSUE TITLE
Feature request SDL_EVENT_FINGER_CANCELLED

### ISSUE THREAD

**Issue by vrolife** [libsdl-org/SDL#10528]
The SDL_EVENT_FINGER_CANCELLED is useful for handling the cancellation of fullscreen gestures on Android. When a fullscreen gesture is triggered, the Android system sends a touch down event to the app. If the app does not handle this gesture, the Android system cancels it. The cancelled touch event behaves similarly to a click event in SDL2.

**Comment by slouken** [comment]
@vrolife, I've added the event, but I haven't been able to trigger it. Do you have steps that work with the SDL test programs?

**Comment by slouken** [comment]
Actually, never mind. I can reproduce it on Android 15 by sliding my finger up from the bottom and having the app management UI come up.

**Comment by slouken** [comment]
Added!
