### ISSUE TITLE
Decide and Document how planar data is stored in / accessed from Surfaces

### ISSUE THREAD

**Issue by Green-Sky** [libsdl-org/SDL#10530]
I saw some discussions around planar pixel formats, especially accompanying the great Camera api.
But no where in the documentation it is stated how to access the pixels/planes. Most of the outside video world uses planes packed or separate.
Looking at https://github.com/libsdl-org/SDL/issues/8703 , it seems like the ABI is decided for SDL3, but it does not really look conclusive? There is also no documentation at SDL_Surface indicating how _continuous_ planes are stored, looking at the code it seems continuous after another (well obv).
So the documentation should contain something similar to:
```
Planar SDL_PixelFormats are stored continuously in `pixels` in the order specified by the format.
```
in the remarks.

Also a helper function like
https://github.com/libsdl-org/SDL/blob/871d0074d2f1e5716667a370ff0a96359b0665d4/src/video/SDL_yuv.c#L200-L201
for surfaces would be cool, so I don't have to calculate that manually.

**Comment by Green-Sky** [comment]
note: my wording does not account for strides.

**Comment by slouken** [comment]
Documented!

I didn't add the helper function, since you can just grab the function directly if you need it. If we extend surfaces to have separate planes in the future, we'll add it then.
