### ISSUE TITLE
All standard SDL properties should be namespaced

### ISSUE THREAD

**Issue by Akaricchi** [libsdl-org/SDL#10543]
I'm currently working on an `SDL_Render` backend on top of the upcoming SDL GPU API (#9312)

One thing that came up is that it makes perfect sense to pass-through properties from the `CreateRenderer` callback to `SDL_GpuCreateDevice`, so that the user can pick a backend and configure any other aspects the underlying API may export via properties in the future. However, this doesn't work, because both `SDL_PROP_RENDERER_CREATE_NAME_STRING` and `SDL_PROP_GPU_CREATEDEVICE_NAME_STRING` are defined to `"name"`, and thus conflict.

I propose that all predefined properties should be namespaced, e.g. something like `sdl.render.driver` and `sdl.gpu.driver` in this case. The macros themselves are already namespaced, so why not the values?

**Comment by slouken** [comment]
That seems reasonable. We don't want the `*CREATE*` properties to have the same name as the final properties, but there's no reason they can't be namespaced for the relevant API.

**Comment by slouken** [comment]
Done!
