### ISSUE TITLE
How does SDL2 implement testffmpeg.c

### ISSUE THREAD

**Issue by Mangomm** [libsdl-org/SDL#10548]
hello, SDL2.25 and above, For example SDL2.26.1 how to realize the functions of https://github.com/libsdl-org/SDL/blob/4368f70ff9447f5960e1afa7a2bb878414c50bc1/test/testffmpeg.c, Since test/testffmpeg.c is an interface using SDL3, could you please tell me how to implement it

**Comment by slouken** [comment]
I suggest using SDL3. It's stable enough to start using at this point.
