### ISSUE TITLE
testcamera prints irrelevant debug message on exit (Windows)

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10541]
When closing testcamera on Windows, the following debug message is printed:
```
. In Accept Drag and Drop, window 2, disabled Full OLE IDropTarget
```
This is the origin:
https://github.com/libsdl-org/SDL/blob/f95027e3d7a692b9324cfa53f371f8cfdb2575e3/src/video/windows/SDL_windowswindow.c#L2152-L2154

Is this message expected?
`testdropfile` does not print any drop releated debug messages.

**Comment by slouken** [comment]
I wonder why the debug log is being printed? Debug logs are disabled by default...

**Comment by Dragon-Baroque** [comment]
Is it because `testcamera` has a `SDL_SetLogPriorities(SDL_LOG_PRIORITY_VERBOSE);` that `testdropfile` does not ?

**Comment by slouken** [comment]
> Is it because `testcamera` has a `SDL_SetLogPriorities(SDL_LOG_PRIORITY_VERBOSE);` that `testdropfile` does not ?

Yup!
