### ISSUE TITLE
SDL_EnumerateDirectory fails if it hits a file currently in use

### ISSUE THREAD

**Issue by JBetz** [libsdl-org/SDL#10546]
On the Windows 32-bit preview release of SDL3, using `SDL_EnumerateDirectory` on a directory with a file currently in use causes an invalid memory access error. The corresponding Windows error message is: "The process cannot access the file because it is currently being used by another process."

I would expect it to still return the file name, and only error if you actually try to read the file.

The callback I'm sending to SDL is just printing the directory and file name, and succeeds on the first two files but then SDL errors when it hits the third. I know the third is in use since it's an active Brave session file, and I get the aforementioned error from the Win32 API if I try to open it directly.

Here's some Smalltalk code to help reproduce / see what I'm doing:

```smalltalk
| sdl userFolder callback sessionsPath |
sdl := SDL3Library default.
userFolder := sdl getUserFolder_folder: SDL_FOLDER_HOME.
sessionsPath := userFolder , 'AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Sessions'.
callback := ExternalCallback 
    block: [:userdata :dirname :fname | Transcript display: dirname -> fname; cr. 1]
    descriptor: (ExternalDescriptor returnType: 'sdword' argumentTypes: 'void* char* char*').
sdl
  enumerateDirectory_path: sessionsPath
  callback: callback asParameter
  userdata: nil
```

**Comment by JBetz** [comment]
Okay, I tried on a completely different directory with files that weren't in use and it still errored. So now I think this is actually not an issue with the file being opened and more likely either the callback or one of the strings getting garbage collected by Smalltalk before SDL is done with it.

**Comment by JBetz** [comment]
I get the same error if I pass an empty string as the path argument to `SDL_EnumerateDirectory`. which is making me even more convinced it's not a bug in SDL.

**Comment by slouken** [comment]
Okay, I'll go ahead and close this for now. Feel free to reopen it or enter a new bug if you narrow down what's happening and SDL needs a fix.

**Comment by JBetz** [comment]
I've been testing with `SDL_EnumeratreProperties` now since it also uses a callback and fails in the same way, which proves it's a more general problem with the Dolphin Smalltalk -> SDL interface. 

Still haven't debugged the issue, but I did notice that the memory errors are always either writing to the address passed in to `userdata`. More precisely, the most-significant 16 bits of it. So `0xFFFF` will result in an invalid write to `0xFFFF` and `0xFFFF1111` will too. And if I just pass in `null` then it tries writing to `0x0`.

My best guess is some sort of calling convention issue, but I've tried using both `cdecl:` and `stdcall:` and it failed in the same way for both.

**Comment by JBetz** [comment]
~Interesting, the problem vanished when I killed the CEF process that was running alongside SDL's message loop.~

**Comment by JBetz** [comment]
Investigating this further, there is indeed an issue with the calling convention used by SDL vs Dolphin Smalltalk. Reproducing it with a Debug build of SDL, I get this error:

> Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

I am specifying `cdecl:` as the calling convention for both the FFI for the method `SDL_EnumerateDirectory` and for the `SDL_EnumerateDirectoryCallback` callback itself. So this is either a bug in Dolphin's FFI itself or I'm wrong about SDL using `cdecl:` here. But then if I try with `stdcall:` it doesn't work either.

**Comment by JBetz** [comment]
Fixed by: https://github.com/dolphinsmalltalk/Dolphin/pull/1347
