### ISSUE TITLE
Mouse cursor remains visible SDL2-2.30.x ( xwayland ) 

### ISSUE THREAD

**Issue by j4reporting** [libsdl-org/SDL#10550]
this has been reported [here](https://github.com/Novum/vkQuake/issues/721)   and might have been introduced with commit  https://github.com/libsdl-org/SDL/commit/c39f86c28a54c3f108c31a58ff610fe9508d03c4 

The AppIimage binary was created  on Ubuntu 20.04 (SDL2-2.30.4 ).   
My local binaries (Fedora 40 )  work fine though. 

Mouse cursor is not visible on screen shots, HW cursor?

**Comment by Kontrabant** [comment]
Cherry-picked an SDL3 commit that should fix this.
