### ISSUE TITLE
SDL_Event.key and kdevice does not return expected IDs?

### ISSUE THREAD

**Issue by lumpalette** [libsdl-org/SDL#10558]
In a regular event loop, I'm trying to get the SDL_KeyboardIDs whenever the user connects a new keyboard or they pressed a key, using `event.key.which` and `event.kdevice.which`.

However, after connecting a new keyboard, the event seems to be getting triggered twice, and the IDs are just random numbers, but the SDL_KeyboardID wiki says that IDs should start at 1 and for every new ID it just increments from there. When I pressed a key, `key.which` returns 0 every time, even with multiple keyboards.

Strangely, every other field from both events seems okay.

This is the code for the whole program:
```
#include <iostream>
#include <SDL3/SDL.h>

int main()
{
	SDL_Init(SDL_INIT_EVENTS);
	SDL_Init(SDL_INIT_VIDEO);

	SDL_Window* w;
	SDL_Renderer* r;
	SDL_CreateWindowAndRenderer("keyboard test", 640, 360, 0, &w, &r);

	bool running = true;
	while (running) {
		SDL_Event e;
		while (SDL_PollEvent(&e)) {
			switch (e.type) {
			case SDL_EVENT_QUIT:
				running = false;
				break;
			case SDL_EVENT_KEYBOARD_ADDED:
				std::cout << (unsigned int)e.kdevice.which << '\n';
				break;
			case SDL_EVENT_KEY_DOWN:
				std::cout << (unsigned int)e.key.which << '\n';
				break;
			}
		}
		SDL_DelayNS(SDL_SECONDS_TO_NS(1 / 60));
	}
	SDL_Quit();
}
```
I'm using an SDL3 Windows build from 3 days ago.

Am I doing something wrong? Or this is expected behaviour?

**Comment by slouken** [comment]
What is the output if you set the environment variable `SDL_EVENT_LOGGING=1`?

**Comment by lumpalette** [comment]
![regular](https://github.com/user-attachments/assets/956a91f8-f4c2-4c0d-a1a0-f9260c093a93)
Still random values for which.

I don't know why, but SDL_EVENT_MOUSE_REMOVED is also being sent??? This only happens with one keyboard, though, the other one works "fine"
![mouse](https://github.com/user-attachments/assets/1a448b14-8fde-4363-83c5-e85d3a186fae)

**Comment by lumpalette** [comment]
I disconnected and connected it four times just to check, and the IDs match in both SDL_EVENT_KEYBOARD_ADDED/REMOVED:
![regular](https://github.com/user-attachments/assets/cd4070b4-a8d8-480b-852e-462ec4eaa3ed)

With the other keyboard, somehow SDL_EVENT_MOUSE_REMOVED/ADDED is also being sent???
![mouse](https://github.com/user-attachments/assets/48e53f0e-284d-4abc-b0d4-527ba499c458)

**Comment by lumpalette** [comment]
Pressing random keys outputs this:
![keys](https://github.com/user-attachments/assets/132a044c-b25a-487f-afb5-098284cb6a19)

**Comment by lumpalette** [comment]
The timestamps in the first screenshot are weird, and in the last screenshot, the windowid starts at 2, but it should start at 1

**Comment by lumpalette** [comment]
creating another window increments the ID counter correctly to 3

**Comment by slouken** [comment]
You can't assume anything about object IDs, other than they'll be non-zero.

**Comment by slouken** [comment]
I clarified the documentation to reduce confusion, thanks for pointing this out!

**Comment by slouken** [comment]
FYI, the keyboard ID for key events will only be set when raw input is enabled on Windows.

**Comment by lumpalette** [comment]
so key.which is only set on Windows? what about other platforms?

**Comment by lumpalette** [comment]
I think SDL_WindowID and SDL_DisplayID should have documentation too, just for consistency.

**Comment by slouken** [comment]
> so key.which is only set on Windows? what about other platforms?

It depends on the platform. It's not currently defined when it's available, you should experiment and see what works for you.

**Comment by slouken** [comment]
> I think SDL_WindowID and SDL_DisplayID should have documentation too, just for consistency.

Done!

**Comment by lumpalette** [comment]
> > so key.which is only set on Windows? what about other platforms?
> 
> It depends on the platform. It's not currently defined when it's available, you should experiment and see what works for you.

That's a shame, I saw somewhere that multiple keyboard support was added, but it didn't mentioned it was platform dependant xd. Maybe it should be specified in SDL_KeyboardEvent?
