### ISSUE TITLE
Should RWseek(0, RW_SEEK_CUR) be optimized?

### ISSUE THREAD

**Issue by ds-sloth** [libsdl-org/SDL#10556]
@Wohlstand and I found a case where MixerX (possibly also Mixer?) MP3 file format detection code that called RWtell in a hot loop (roughly 20k times) led to a minute-long hang on 3DS.

This happens because the fseek implementation on 3DS (and probably elsewhere) invokes a syscall to refill the file pointer's buffer, and RWseek does not optimize out the fseek(0, SEEK_CUR) call even though it is a noop per the POSIX standard.

If the SDL team thinks it is safe to optimize out this case, I'm happy to submit a PR to both branches doing so.

**Comment by slouken** [comment]
Sure, go for it.

**Comment by ds-sloth** [comment]
PRs submitted, thank you!

**Comment by icculus** [comment]
Okay, PRs are merged! Thanks for jumping on this so quickly, @ds-sloth!
