### ISSUE TITLE
Retrobit Sega Saturn Wireless Contoller has invalid parameters

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#10557]
I'm talking about this controller:

![image](https://github.com/user-attachments/assets/135db19c-7e51-4367-a610-df303c6886fc)
[RETRO-BIT X SEGA COLLABORATION](https://retro-bit.com/sega-collaboration)

If I use latest SDL library (version 2.30.6.0) then this controller is detected as follows (using DirectInput method, which is the default method used automatically after pairing with PC):

```
INFO:           name: SWITCH CO.,LTD. Retro-bit Controller
INFO:           type: Game Controller
INFO:            LED: no
INFO:         rumble: no
INFO: trigger rumble: no
INFO:           axes: 16
INFO:          balls: 0
INFO:           hats: 0
INFO:        buttons: 15
INFO:    instance id: 0
INFO:           guid: 03001a64632500007505000000016800
INFO:        VID/PID: 0x2563/0x0575
```
Complete garbage. Below are listed invalid properties:

```
INFO:         rumble: no    (should be "yes")
INFO:           axes: 16    (should be "4")
INFO:           hats: 0     (should be "1")
INFO:        buttons: 15    (should be "13")
```
This is how it look in the system controller configurator tool:

![image](https://github.com/user-attachments/assets/f41fcf3e-17d7-422f-a90a-76bf5a62968e)

When I switch the mode to X-Input (by pressing `Start+B` button combination), table is as follows:

```
INFO:           name: Xbox 360 Controller
INFO:           type: Game Controller
INFO:            LED: no
INFO:         rumble: yes
INFO: trigger rumble: no
INFO:           axes: 6
INFO:          balls: 0
INFO:           hats: 1
INFO:        buttons: 11
INFO:    instance id: 0
INFO:           guid: 030000175e0400008e02000000007200
INFO:        VID/PID: 0x045e/0x028e
```
![image](https://github.com/user-attachments/assets/9e8db503-4da9-4302-a7ee-2ac5a304a36d)

Everything is correct, so the problem seems to be in the DirectInput mode only. If you need more information please ask, I will be happy to provide it.

**Comment by furious-programming** [comment]
There is a one more problem — SDL sends power level event with the `SDL_JOYSTICK_POWER_WIRED` value when the battery is fully charged. This controller supports only wireless connection (USB cable is for charging only), so I wonder if SDL should actually provide this value. Honestly, I was expecting the value `SDL_JOYSTICK_POWER_FULL` or `SDL_JOYSTICK_POWER_MAX`, but maybe I don't understand something.

**Comment by slouken** [comment]
This is not a bug. This controller switches between XInput and PS3 mode. In PS3 mode rumble is not supported and there are extra axes to represent pressure on the buttons.

This is clearer with the SDL3 testcontroller test application, and the buttons shown match the PS3 button mapping in the manual.

**Comment by slouken** [comment]
Actually, I noticed that the triggers aren't detected properly and the controller doesn't actually support pressure sensitive buttons. I'll go ahead and fix these up and change the power level to unknown, since it doesn't report that information as far as I can tell.

**Comment by slouken** [comment]
Fixed!
