### ISSUE TITLE
SDL_DestroyTexture leak memory wayland X11.

### ISSUE THREAD

**Issue by TKNgu** [libsdl-org/SDL#10566]
I build simple program SDL2 on ubuntu 24.04 wayland card nvidia driver 550.90.07 with SDL2 lib build from source: 
`
ExternalProject_Add(libsdl2
  GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
  GIT_TAG release-2.30.6
  PREFIX ${CMAKE_SOURCE_DIR}/lib/sdl2
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_SOURCE_DIR}/lib/local)
`

#include <SDL2/SDL.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_timer.h>
#include <SDL2/SDL_video.h>
#include <stdint.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
  printf("Check SDL2\n");
  if (SDL_Init(SDL_INIT_VIDEO) < 0) {
    printf("Error init sdl2\n");
    return 1;
  }

  SDL_Window *window =
      SDL_CreateWindow("Check SDL2", 100, 100, 800, 600, SDL_WINDOW_SHOWN);
  if (!window) {
    printf("Error create window\n");
    goto QUIT_SDL2;
  }

  SDL_Renderer *renderer =
      SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
  if (!renderer) {
    printf("Error create renderer\n");
    goto DESTROY_WINDOW;
  }

  int is_running = 750;
  while (is_running--) {
    uint32_t start_time = SDL_GetTicks();
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
      if (event.type == SDL_QUIT) {
        is_running = 0;
      }
    }

    SDL_Texture *texture =
        SDL_CreateTexture(renderer, SDL_PIXELFORMAT_NV12,
                          SDL_TEXTUREACCESS_STREAMING, 1920, 1080);
    SDL_DestroyTexture(texture);

    SDL_RenderPresent(renderer);
    uint32_t end_time = SDL_GetTicks();
    if (end_time < start_time + 40) {
      SDL_Delay(start_time + 40 - end_time);
    }
  }

  SDL_DestroyRenderer(renderer);
DESTROY_WINDOW:
  SDL_DestroyWindow(window);
QUIT_SDL2:
  SDL_Quit();
  return 0;
}

Check log valgrind:
==6296== Memcheck, a memory error detector
==6296== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==6296== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==6296== Command: ./a.out
==6296== 
Check SDL2
==6296== realloc() with size 0
==6296==    at 0x4E0C8EB: realloc (vg_replace_malloc.c:1690)
==6296==    by 0x142EEC0F: ??? (in /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.550.90.07)
==6296==    by 0x13786986: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x137E06A1: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x13786012: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x4005823: call_init (dl-init.c:120)
==6296==    by 0x4005823: _dl_init (dl-init.c:121)
==6296==    by 0x40015B1: _dl_catch_exception (dl-catch.c:211)
==6296==    by 0x400CD7B: dl_open_worker (dl-open.c:829)
==6296==    by 0x400CD7B: dl_open_worker (dl-open.c:792)
==6296==    by 0x400151B: _dl_catch_exception (dl-catch.c:237)
==6296==    by 0x400D163: _dl_open (dl-open.c:905)
==6296==    by 0x50B1193: dlopen_doit (dlopen.c:56)
==6296==    by 0x400151B: _dl_catch_exception (dl-catch.c:237)
==6296==  Address 0x12ba2260 is 0 bytes after a block of size 0 alloc'd
==6296==    at 0x4E050C5: malloc (vg_replace_malloc.c:442)
==6296==    by 0x142EEBFF: ??? (in /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.550.90.07)
==6296==    by 0x13786986: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x137E06A1: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x13786012: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x4005823: call_init (dl-init.c:120)
==6296==    by 0x4005823: _dl_init (dl-init.c:121)
==6296==    by 0x40015B1: _dl_catch_exception (dl-catch.c:211)
==6296==    by 0x400CD7B: dl_open_worker (dl-open.c:829)
==6296==    by 0x400CD7B: dl_open_worker (dl-open.c:792)
==6296==    by 0x400151B: _dl_catch_exception (dl-catch.c:237)
==6296==    by 0x400D163: _dl_open (dl-open.c:905)
==6296==    by 0x50B1193: dlopen_doit (dlopen.c:56)
==6296==    by 0x400151B: _dl_catch_exception (dl-catch.c:237)
==6296== 
==6296== posix_memalign() invalid size value: 0
==6296==    at 0x4E0D04C: posix_memalign (vg_replace_malloc.c:2099)
==6296==    by 0x142EEC45: ??? (in /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.550.90.07)
==6296==    by 0x13786986: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x137E06A1: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x13786012: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.550.90.07)
==6296==    by 0x4005823: call_init (dl-init.c:120)
==6296==    by 0x4005823: _dl_init (dl-init.c:121)
==6296==    by 0x40015B1: _dl_catch_exception (dl-catch.c:211)
==6296==    by 0x400CD7B: dl_open_worker (dl-open.c:829)
==6296==    by 0x400CD7B: dl_open_worker (dl-open.c:792)
==6296==    by 0x400151B: _dl_catch_exception (dl-catch.c:237)
==6296==    by 0x400D163: _dl_open (dl-open.c:905)
==6296==    by 0x50B1193: dlopen_doit (dlopen.c:56)
==6296==    by 0x400151B: _dl_catch_exception (dl-catch.c:237)
==6296== 
==6296== 
==6296== HEAP SUMMARY:
==6296==     in use at exit: 383,353 bytes in 3,624 blocks
==6296==   total heap usage: 161,806 allocs, 158,182 frees, 8,584,755,462 bytes allocated
==6296== 
==6296== 1,977 (184 direct, 1,793 indirect) bytes in 1 blocks are definitely lost in loss record 2,401 of 2,421
==6296==    at 0x4E0C6E5: calloc (vg_replace_malloc.c:1595)
==6296==    by 0x56E4DDF: ??? (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56E6D6D: _dbus_message_loader_queue_messages (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56EF8DB: ??? (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56EFAAF: ??? (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56F0BE0: ??? (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56F11CF: ??? (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56D6391: ??? (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56EB04C: dbus_pending_call_block (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56D819D: dbus_connection_send_with_reply_and_block (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56D843B: dbus_bus_register (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296==    by 0x56D8707: ??? (in /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.32.4)
==6296== 
==6296== 22,888 (1,768 direct, 21,120 indirect) bytes in 1 blocks are definitely lost in loss record 2,417 of 2,421
==6296==    at 0x4E050C5: malloc (vg_replace_malloc.c:442)
==6296==    by 0x6DDB496: ???
==6296==    by 0x6DDC378: ???
==6296==    by 0x6DD7A86: ???
==6296==    by 0x6DDC8B4: ???
==6296==    by 0x6C57939: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
==6296==    by 0x6C5CA70: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
==6296==    by 0x6C5DB18: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
==6296==    by 0x6C59548: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
==6296==    by 0x4D12C2B: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.3000.0)
==6296==    by 0x4D13FB6: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.3000.0)
==6296==    by 0x4CE8222: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.3000.0)
==6296== 
==6296== 33,280 bytes in 52 blocks are definitely lost in loss record 2,419 of 2,421
==6296==    at 0x4E0C8EB: realloc (vg_replace_malloc.c:1690)
==6296==    by 0x54C4700: XGetVisualInfo (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==6296==    by 0x137B2879: ???
==6296==    by 0x137D2262: ???
==6296==    by 0x137D3331: ???
==6296==    by 0x12EA926F: ???
==6296==    by 0x12EB4A4D: ???
==6296==    by 0x12EBAB0F: ???
==6296==    by 0x7836D59: ???
==6296==    by 0x782774B: ???
==6296==    by 0x7829E5D: ???
==6296==    by 0x745C7EC: ???
==6296== 
==6296== LEAK SUMMARY:
==6296==    definitely lost: 35,232 bytes in 54 blocks
==6296==    indirectly lost: 22,913 bytes in 222 blocks
==6296==      possibly lost: 0 bytes in 0 blocks
==6296==    still reachable: 325,208 bytes in 3,348 blocks
==6296==         suppressed: 0 bytes in 0 blocks
==6296== Reachable blocks (those to which a pointer was found) are not shown.
==6296== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==6296== 
==6296== For lists of detected and suppressed errors, rerun with: -s
==6296== ERROR SUMMARY: 5 errors from 5 contexts (suppressed: 0 from 0)

**Comment by TKNgu** [comment]
Update:
export SDL_VIDEODRIVER=wayland run OK.

**Comment by slouken** [comment]
Mesa and NVIDIA drivers have known memory leaks. I don't believe this is an SDL issue, but please reopen this if you find out differently.
