### ISSUE TITLE
dummy audio driver does not work on emscripten

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10573]
Running testautomation with the dummy audio driver fails with the following message:
```
2: Couldn't open audio: Couldn't create audio thread
2: INFO:__main__:Exit code = 1
```

Reproducer:
```sh
emcmake cmake -S /path/to/SDL -B /tmp/sdl-emscripten-build -DSDL_TESTS=ON -DSDLTEST_AUDIO_DRIVER=dummy
cmake --build /tmp/sdl-emscripten-build
cmake --build --target serve-sdl-tests &
ctest -V -test-dir /tmp/sdl-emscripten/build -R testautomation
```

**Comment by icculus** [comment]
So I haven't looked at this, but I can already say that every audio backend uses a thread by default unless it takes measures to provide its own...the emscripten backend uses a function that runs between iterations of the mainloop to get around this.

We could add an emscripten-specific similar thing for the dummy driver is this is useful, but it's probably better to just disable the test.

**Comment by icculus** [comment]
(Even the dummy backend needs to consume audio at a regular interval and provide silence on recording devices, so it still needs a thread.)

**Comment by icculus** [comment]
> We could add an emscripten-specific similar thing for the dummy driver is this is useful, but it's probably better to just disable the test.

This is fixed now, as of d118af53a121f25207e126d4bbe2744624adb010. Beyond the test, there are probably some small special cases where it's useful for people to be able to build Emscripten builds with only dummy audio, or for a user to override a page with `?SDL_AUDIO_DRIVER=dummy` on the URL, so I plugged this in.

**Comment by madebr** [comment]
Thanks!

To be honest, I wasn't sure about the need for this one.

**Comment by ericoporto** [comment]
Wasn't the dummy audio used to consume the audio output until someone interacted with the canvas which would then allow sound to actually be emitted? I remember something like this being mentioned at some point.

**Comment by icculus** [comment]
It's the emscripten backend; it uses setInterval in the same way, throwing away the data until the user interacts with the page so things stay in sync.
