### ISSUE TITLE
[Android] mouse - avoid popping out system bars

### ISSUE THREAD

**Issue by Laserlicht** [libsdl-org/SDL#10585]
Hi!

Is there a way to avoid popping out the system bars when moving the mouse to the borders in full screen?

Mouse dragging from borders would be okay, but hovering borders is not good for a game that needs the screen borders...

![grafik](https://github.com/user-attachments/assets/e0c4dc76-1e89-4a08-9b09-645c5f0e1a35)

**Comment by NTques** [comment]
Hello,

The issue can be resolved within Android. Please check the link below.

https://developer.android.com/training/system-ui/navigation
