### ISSUE TITLE
make src/libm a static library internal to SDL ?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#10584]
Many, if not all, of src/libm is actually unused in libc/libm-enabled builds and serves only to bloat the library size. Can we not make it into a static library internal only to SDL? (FWIW, the watcom os2 and win32 builds of sdl2 does just that.)

**Comment by slouken** [comment]
I'm fine with that. @madebr, what's involved here?

**Comment by sezero** [comment]
cmake side _should_ be pretty easy: build libm as static and link to shared sdl3, but add libm sources to static sdl3 as usual. job for @madebr

_Possibly_ tricky part is standalone project files, e.g. msvc and xcode project files.

**Comment by slouken** [comment]
The standalone projects have fixed configurations, so they include the math files or not, as needed for the platform.

**Comment by madebr** [comment]
Conditionally including libm is not that hard, and results in a small file size reduction.
A Linux SDL3 release library goes from 3461kiB to 3443kiB: around -18 kiB.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 55dec2e13..f1b2d3ebb 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -482,7 +482,6 @@ sdl_glob_sources(
   "${SDL3_SOURCE_DIR}/src/joystick/*.c"
   "${SDL3_SOURCE_DIR}/src/haptic/*.c"
   "${SDL3_SOURCE_DIR}/src/hidapi/*.c"
-  "${SDL3_SOURCE_DIR}/src/libm/*.c"
   "${SDL3_SOURCE_DIR}/src/locale/*.c"
   "${SDL3_SOURCE_DIR}/src/main/*.c"
   "${SDL3_SOURCE_DIR}/src/misc/*.c"
@@ -498,6 +497,11 @@ sdl_glob_sources(
   "${SDL3_SOURCE_DIR}/src/video/*.c"
   "${SDL3_SOURCE_DIR}/src/video/yuv2rgb/*.c"
 )
+if(NOT SDL_LIBC)
+  sdl_glob_sources(
+    "${SDL3_SOURCE_DIR}/src/libm/*.c"
+  )
+endif()
 if(MSVC AND TARGET SDL3-shared)
   if(SDL_CPU_X64)
     enable_language(ASM_MASM)
```

I see an issue on mingw, and potentially other platforms, in src/stdlibc/SDL_stdlib.c.
uclibc functions are used when its libc equivalents are broken.
e.g. here for SDL_isinf:
https://github.com/libsdl-org/SDL/blob/3e60fb42239f2617968dd0e4a167359ec199427a/src/stdlib/SDL_stdlib.c#L275-L282

**Comment by sezero** [comment]
> I see an issue on mingw, and potentially other platforms, in src/stdlibc/SDL_stdlib.c. uclibc functions are used when its libc equivalents are broken. e.g. here for SDL_isinf:

That's why we should build src/libm as a static lib and link to dynamic sdl3. Unless I'm missing something?

**Comment by madebr** [comment]
> > I see an issue on mingw, and potentially other platforms, in src/stdlibc/SDL_stdlib.c. uclibc functions are used when its libc equivalents are broken. e.g. here for SDL_isinf:
> 
> That's why we should build src/libm as a static lib and link to dynamic sdl3. Unless I'm missing something?

That'd work perhaps for the shared libraries, but won't for the static lbirary because we don't want to ship an extra library.
It turned out only isinf(f) and isnan(f) where giving issues, which is done in https://github.com/libsdl-org/SDL/pull/10587.

**Comment by sezero** [comment]
I mean something like: (pseudo)
```
 if(shared)
   add_target(static_libm libm_srcs)
   target_link_libs(sdl3-shared static libm)
 endif()
 if(static)
  append_target_srcs(sdl3-static libm_srcs)
 endif()
```

Why should it not work?

**Comment by madebr** [comment]
> Why should it not work?

Your approach works indeed.

But doesn't #10586 address this too?

**Comment by sezero** [comment]
> > Why should it not work?
> 
> Your approach works indeed.
> 
> But doesn't #10586 address this too?

`s/#10586/#10587/`

#10587 relies on !SDL_LIBC and adds some target-specific workarounds which may not satisfy all existing libc versions. Mine is more general and 100% reliable I believe.

**Comment by slouken** [comment]
If I'm understanding correctly, that means we build and link with a library named "libm", right? I'd rather the sources be built into SDL so we don't have separate static library dependencies.

**Comment by sezero** [comment]
> If I'm understanding correctly, that means we build and link with a library named "libm", right?

SDL_libm, better I guess

> I'd rather the sources be built into SDL so we don't have separate static library dependencies.

The way I suggest above, there will be no dependencies: SDL_libm will be a internaluse build-time static lib for shared sdl, and static SDL will be build the way it used to before.

**Comment by madebr** [comment]
This is what sezero suggests
https://github.com/madebr/SDL/commit/50d908bd4b1c4e45f16140fc1028f50065a71d4f

SDL_uclibc is a SDL cmake implementation detail.

**Comment by sezero** [comment]
> This is what sezero suggests [madebr@50d908b](https://github.com/madebr/SDL/commit/50d908bd4b1c4e45f16140fc1028f50065a71d4f)
> 
> SDL_uclibc is a SDL cmake implementation detail.

Yes. There are 3 CI failures which I haven't looked the reasons for, but this can be applied after fixing those.

**Comment by madebr** [comment]
In https://github.com/libsdl-org/SDL/commit/4b3a80bb73fd953126e4daaf4b63acc8ebd76de3, I added a conditional compile option to the msbuild files. But I don't think we want MSbuild in control of libc instead of the headers.

If this is okay, then we can add a property.

**Comment by icculus** [comment]
This is a dumb question that's maybe already been covered, but if we're not using this code in a particular build, wouldn't the linker just not include it? What's the value of a static library for this?

**Comment by sezero** [comment]
>  if we're not using this code in a particular build, wouldn't the linker just not include it? 

Not necessarily: See that @madebr's initial patch resulted in ~18k decrease in library size (see above.)

Maybe only with lto in place though, those unused code may be discarded.

**Comment by slouken** [comment]
> > The standalone projects have fixed configurations, so they include the math files or not, as needed for the platform.
> 
> Both Xcode and MSVC projects include the math source files. However, dnly the MSVC project actually needs them when really building w/o libc dependency.

I'll take a look at this later. @madebr, don't bother adding a property to the Visual Studio projects for this.
