### ISSUE TITLE
SDL3 Request: Process Spawning

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#10599]
A wrapper around `fork`/`exec`, `CreateProcess`, etc. to allow launching child processes with arguments. This will make running an application with a server-client architecture ([similar to the original Quake](https://archive.gamedev.net/archive/reference/articles/article987.html)) easier.

It's not too much code to do this by oneself, but it'll be good to have a battle-tested version available in SDL (especially given the subtle differences across various platforms).

---------

Examples:

+ https://github.com/DaanDeMeyer/reproc
+ https://github.com/eidheim/tiny-process-library
+ https://github.com/sheredom/subprocess.h

**Comment by hardening** [comment]
If we come to abstract this, if that could also include a facility to create communication channels between parent and child (socket pair under unixes and named pipes for windows) as it's a so common model...
