### ISSUE TITLE
Windows VC Linker error audio_async and sdl audio functions

### ISSUE THREAD

**Issue by BrianTheBrain11** [libsdl-org/SDL#10591]
Using latest VC release. Verified I've linked properly by being able to use other SDL functions, just whenever I try to call other sdl_audio stuff, like audio_async, I get linker errors.

**Comment by madebr** [comment]
We need more details here.
What is the link command, and can you copy/past the complete output?

**Comment by icculus** [comment]
`audio_async` isn't an SDL symbol.

[Based on this bug report](https://github.com/ggerganov/whisper.cpp/issues/2371), I'm assuming the problem is you need to compile examples/common-sdl.cpp along with whatever other code you're using, but this isn't an SDL issue.

**Comment by BrianTheBrain11** [comment]
Thank you, appreciate it, it a class in the project using sdl. Thank you!!!
