### ISSUE TITLE
Game controller support matrix

### ISSUE THREAD

**Issue by LIJI32** [libsdl-org/SDL#10593]
A frequent pain point I have with SDL game controllers is not being able to easily tell how "well" SDL supports each of the many controllers my users use, and I end up having to dig in the source to tell if SDL supports certain features (e.g. rumble) with certain controllers. It would be very helpful to have some sort of support matrix with the list of compatible controllers and the features SDL supports for each controller (e.g. rumble, motion controls, player LEDs, etc). Thanks!

**Comment by slouken** [comment]
This is a good idea, but depends on what driver is being used, which varies based on the support available on the customer's system. The best way to handle things is to check the supported capabilities in SDL3 or just assume all functionality is available if you don't need to surface UI about it to users.

**Comment by LIJI32** [comment]
This is what I do, the issue is that users end up opening bug reports about certain controllers not getting rumble or motion controls, and I have no easy way to tell if it's a bug or simply lack of support in SDL =/

**Comment by slouken** [comment]
Sure, I'll see if I can write something up for SDL3. If you already have this work in progress, feel free to create a PR.

**Comment by slouken** [comment]
A full matrix isn't really feasible and would probably be more confusing than helpful, so I better documented how to check for gamepad capabilities, so you can immediately see what SDL thinks is available and better communicate expectations to users.
