### ISSUE TITLE
audio_resampleLoss failure in testautomation-no-simd

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#10613]
See https://github.com/sezero/SDL/actions/runs/10607125643/job/29399092469

```
2024-08-29T01:41:09.8686968Z 21:  08/29/24 01:41:09: ----- Test Case 1.17: 'audio_resampleLoss' started
2024-08-29T01:41:09.8687423Z 21:  08/29/24 01:41:09: Test Description: 'Check signal-to-noise ratio and maximum error of audio resampling.'
2024-08-29T01:41:09.8687623Z 21:  08/29/24 01:41:09: Test Iteration 1: execKey 9482042555129633145
2024-08-29T01:41:09.8687988Z 21:  08/29/24 01:41:09: Assert 'Call to SDL_InitSubSystem(SDL_INIT_AUDIO)': Passed
2024-08-29T01:41:09.8688466Z 21:  08/29/24 01:41:09: Assert 'Check result from SDL_InitSubSystem(SDL_INIT_AUDIO)': Passed
2024-08-29T01:41:09.8689090Z 21:  08/29/24 01:41:09: Assert 'Test resampling of 50 s 440 Hz 0.000000 phase sine wave from sampling rate of 44100 Hz to 48000 Hz': Passed
2024-08-29T01:41:09.8689619Z 21:  08/29/24 01:41:09: Assert 'Call to SDL_CreateAudioStream(SDL_AUDIO_F32, 1, 44100, SDL_AUDIO_F32, 1, 48000)': Passed
2024-08-29T01:41:09.8689987Z 21:  08/29/24 01:41:09: Assert 'Expected SDL_CreateAudioStream to succeed.': Passed
2024-08-29T01:41:09.8690332Z 21:  08/29/24 01:41:09: Assert 'Expected input buffer to be created.': Passed
2024-08-29T01:41:09.8690677Z 21:  08/29/24 01:41:09: Assert 'Expected output buffer to be created.': Passed
2024-08-29T01:41:09.8691166Z 21:  08/29/24 01:41:09: Assert 'Call to convert_audio_chunks(stream, buf_in, 8820000, buf_out, 9600000)': Passed
2024-08-29T01:41:09.8691652Z 21: ERROR: 08/29/24 01:41:09: Assert 'Expected output length to be 9600000, got -1.': Failed
2024-08-29T01:41:09.8691976Z 21:  08/29/24 01:41:09: Assert 'Cleanup of test files completed': Passed
2024-08-29T01:41:09.8692101Z 21:  08/29/24 01:41:09: Fuzzer invocations: 4
2024-08-29T01:41:09.8692487Z 21: ERROR: 08/29/24 01:41:09: >>> Test 'audio_resampleLoss': Failed (Aborted)
2024-08-29T01:41:09.8692629Z 21:  08/29/24 01:41:09: Total Test runtime: 0.0 sec
2024-08-29T01:41:09.8693062Z 21: ERROR: 08/29/24 01:41:09: >>> Test 'audio_resampleLoss': Failed
```

**Comment by sezero** [comment]
This seems to be an oddball? Doesn't seem to happen all the time, but it just did. @icculus may have an idea.

**Comment by madebr** [comment]
I think the audio testautomation has some bugs left from the SDL_bool change.

**Comment by slouken** [comment]
> I think the audio testautomation has some bugs left from the SDL_bool change.

It's likely, but I did a quick scan through it and didn't see any issues. @sezero, can you add some additional logging to find out which SDL call is returning an unexpected result?

**Comment by sezero** [comment]
> @sezero, can you add some additional logging to find out which SDL call is returning an unexpected result?

I would, but I don't know whether I can make it to fail: it seems to have happened very rarely -- only once.

**Comment by slouken** [comment]
> > @sezero, can you add some additional logging to find out which SDL call is returning an unexpected result?
> 
> I would, but I don't know whether I can make it to fail: it seems to have happened very rarely -- only once.

sdl2-compat consistently fails this test, so maybe this is a preexisting condition? I'll take a look at that.

**Comment by slouken** [comment]
> sdl2-compat consistently fails this test, so maybe this is a preexisting condition? I'll take a look at that.

No, that's different, it's an off-by-one error that @icculus should really look at. Hmm, I'll step through the code again and see if I can see anywhere that could fail.

**Comment by sezero** [comment]
>  it's an off-by-one error that @icculus should really look at.

Most possibly: a `<=` or `>=` which should actually be `<` or `>` (or vice versa)

**Comment by slouken** [comment]
I don't see anywhere this can fail when using the same seed as the CI failure, other than legitimate allocation failures. This runs clean even with address sanitizer enabled. I'm bumping this to @icculus, maybe he has more ideas here?

**Comment by sezero** [comment]
As of https://github.com/sezero/SDL/commit/8ddb099d3e98bc4820af05f26aee9fd17c934c50, a lot of failures in CI..

**Comment by slouken** [comment]
> As of commit [8ddb099](https://github.com/libsdl-org/SDL/commit/8ddb099d3e98bc4820af05f26aee9fd17c934c50), a lot of failures in CI..

Yup, it's the sdl2-compat failure, ported to SDL3. @icculus is going to take a look when he gets a chance. You can ignore that failure for purposes of merging PRs.

**Comment by icculus** [comment]
I'm going to poke this real fast just to unblock things. Hopefully it's easy.

**Comment by icculus** [comment]
I assume this is SDL_GetResamplerOutputFrames coming out one frame larger in some cases, which it happily fills in when you give it a larger buffer, but I don't really know how to fix it. @0x1F9F1, any idea?

It's not a floating point rounding issue, as it doesn't use floats for this.

**Comment by icculus** [comment]
Might be this:

```c
    // output_frames = div_ceil(input_offset, resample_rate)
    Sint64 output_frames = (input_offset > 0) ? (((input_offset - 1) / resample_rate) + 1) : 0;
```

Taking out the +1 fixes it, but then we are one sample short on a later test.

Maybe "div_ceil" should round to nearest instead? I assume that's what the +1 is for, but I could be totally wrong.

**Comment by slouken** [comment]
How about [this](https://github.com/libsdl-org/SDL/pull/10635)?

**Comment by icculus** [comment]
Definitely fixes it for me.

**Comment by sezero** [comment]
Should 8ddb099d3e98bc4820af05f26aee9fd17c934c50 be reverted after that?

**Comment by slouken** [comment]
> Should [8ddb099](https://github.com/libsdl-org/SDL/commit/8ddb099d3e98bc4820af05f26aee9fd17c934c50) be reverted after that?

No, we want to keep that test case.

**Comment by slouken** [comment]
Okay, I fixed the extra sample issue, but we still don't know why this failed once with -1 for @sezero.

**Comment by slouken** [comment]
I got another failure in CI in this same test:
https://github.com/slouken/SDL/actions/runs/10645992611/job/29512397443#step:25:46378

Of course I can't reproduce this locally, even using the same seed.

There's something fishy here, @icculus.

**Comment by 0x1F9F1** [comment]
> Might be this:
> 
> ```c
>     // output_frames = div_ceil(input_offset, resample_rate)
>     Sint64 output_frames = (input_offset > 0) ? (((input_offset - 1) / resample_rate) + 1) : 0;
> ```
> 
> Taking out the +1 fixes it, but then we are one sample short on a later test.
> 
> Maybe "div_ceil" should round to nearest instead? I assume that's what the +1 is for, but I could be totally wrong.

Yeah, I think rounding to nearest is instead of rounding up is the right move in terms of matching what the user would expect, since there will always be small precision errors from using fixed point arithmetic.

```py
>>> resample_rate = (44100 << 32) // 48000
>>> (8820000 << 32) / resample_rate
9600000.000486568
```

I see you tried `resample_rate / 2`, but then switched to `resample_rate * 3 / 4` intead. I guess that's also fine, though did using half not fix the issue?

Currently no idea about the random failures though. testautomation could do with being run with `--log error`, and calling `SDL_GetError` after a failure.

**Comment by sezero** [comment]
What is this really about ?

```
22/22 Test #21: testautomation-no-simd ...........***Failed  Error regular expression found in output. Regex=[Total: [0-9]+\.[0-9]+ Kb in [1-9][0-9]* allocations] 10.79 sec

95% tests passed, 1 tests failed out of 22

Total Test time (real) =  35.31 sec

The following tests FAILED:
	 21 - testautomation-no-simd (Failed)
Errors while running CTest
Output from these tests are in: D:/a/SDL/SDL/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
Error: Process completed with exit code 8.
```

(Origin: https://github.com/sezero/SDL/actions/runs/10654652204/job/29531282628)

**Comment by madebr** [comment]
> What is this really about ?

The `audio_resampleLoss` test failed and didn't clean up its buffers.
And now CTest fails because there are leaks.
Since the return code is still !=0, it would fail anyhow.

**Comment by icculus** [comment]
> Of course I can't reproduce this locally, even using the same seed.

Does the CI not use SIMD or something? Trying to decide what would cause the difference.

**Comment by sezero** [comment]
> > What is this really about ?
> 
> The `audio_resampleLoss` test failed and didn't clean up its buffers. And now CTest fails because there are leaks. Since the return code is still !=0, it would fail anyhow.

What is the regex complaint about?

**Comment by madebr** [comment]
> What is the regex complaint about?

The key part is `in [1-9][0-9]* allocations`, which means >= 1.

**Comment by slouken** [comment]
> Does the CI not use SIMD or something? Trying to decide what would cause the difference.

It doesn't, in the cases where it's failing. But it doesn't fail all the time, most of the time the test passes in CI. I tested here with the exact same environment and command line and wasn't able to reproduce it either.

**Comment by icculus** [comment]
Gonna run this in a loop for awhile to see if it ever blows up on repeat.

```bash
while `./test/testautomation --seed WT96XZFERX63KY38 --filter audio_resampleLoss` ; do echo ok ; done
```

(I _think_ that's right...?)

**Comment by madebr** [comment]
On Linux, I cannot get it to fail.
But on Wine, it fails when I run it in a loop.
Running with `--log error` does not print extra information.

command:
```
SDL_AUDIO_DRIVER=dummy SDL_VIDEO_DRIVER=dummy SDL_CPU_FEATURE_MASK=-all  wine test/testautomation.exe --filter audio_resampleLoss  --log error --seed WT96XZFERX63KY38
```
<details>

<summary>with this patch:</summary>

```patch
diff --git a/include/SDL3/SDL_test_harness.h b/include/SDL3/SDL_test_harness.h
index 302388904..54dc2dc82 100644
--- a/include/SDL3/SDL_test_harness.h
+++ b/include/SDL3/SDL_test_harness.h
@@ -63,7 +63,7 @@ extern "C" {
 #define TEST_RESULT_SETUP_FAILURE       4
 
 /* !< Function pointer to a test case setup function (run before every test) */
-typedef void (*SDLTest_TestCaseSetUpFp)(void *arg);
+typedef void (*SDLTest_TestCaseSetUpFp)(void **arg);
 
 /* !< Function pointer to a test case function */
 typedef int (*SDLTest_TestCaseFp)(void *arg);
diff --git a/src/test/SDL_test_harness.c b/src/test/SDL_test_harness.c
index 1347bbf54..f1fc68f92 100644
--- a/src/test/SDL_test_harness.c
+++ b/src/test/SDL_test_harness.c
@@ -237,6 +237,7 @@ static int SDLTest_RunTest(SDLTest_TestSuiteReference *testSuite, const SDLTest_
     int testCaseResult = 0;
     int testResult = 0;
     int fuzzerCount;
+    void *data = NULL;
 
     if (!testSuite || !testCase || !testSuite->name || !testCase->name) {
         SDLTest_LogError("Setup failure: testSuite or testCase references NULL");
@@ -259,7 +260,7 @@ static int SDLTest_RunTest(SDLTest_TestSuiteReference *testSuite, const SDLTest_
 
     /* Maybe run suite initializer function */
     if (testSuite->testSetUp) {
-        testSuite->testSetUp(0x0);
+        testSuite->testSetUp(&data);
         if (SDLTest_AssertSummaryToTestResult() == TEST_RESULT_FAILED) {
             SDLTest_LogError(SDLTEST_FINAL_RESULT_FORMAT, "Suite Setup", testSuite->name, COLOR_RED "Failed" COLOR_END);
             return TEST_RESULT_SETUP_FAILURE;
@@ -267,7 +268,7 @@ static int SDLTest_RunTest(SDLTest_TestSuiteReference *testSuite, const SDLTest_
     }
 
     /* Run test case function */
-    testCaseResult = testCase->testCase(0x0);
+    testCaseResult = testCase->testCase(data);
 
     /* Convert test execution result into harness result */
     if (testCaseResult == TEST_SKIPPED) {
@@ -286,7 +287,7 @@ static int SDLTest_RunTest(SDLTest_TestSuiteReference *testSuite, const SDLTest_
 
     /* Maybe run suite cleanup function (ignore failed asserts) */
     if (testSuite->testTearDown) {
-        testSuite->testTearDown(0x0);
+        testSuite->testTearDown(data);
     }
 
     /* Cancel timeout timer */
diff --git a/test/testautomation.c b/test/testautomation.c
index 6480feb70..764a34518 100644
--- a/test/testautomation.c
+++ b/test/testautomation.c
@@ -165,8 +165,15 @@ int main(int argc, char *argv[])
         SDL_RenderClear(renderer);
     }
 
-    /* Call Harness */
-    result = SDLTest_RunSuites(testSuites, userRunSeed, userExecKey, filter, testIterations, randomOrder);
+    for (;;) {
+        /* Call Harness */
+        result = SDLTest_RunSuites(testSuites, userRunSeed, userExecKey, filter, testIterations, randomOrder);
+        if (result != 0) {
+            SDL_Log("FAIL!");
+            break;
+        }
+        SDL_Quit();
+    }
 
     /* Empty event queue */
     done = 0;
diff --git a/test/testautomation_audio.c b/test/testautomation_audio.c
index 9a9e726f5..967c313a5 100644
--- a/test/testautomation_audio.c
+++ b/test/testautomation_audio.c
@@ -15,12 +15,17 @@
 #include <SDL3/SDL_test.h>
 #include "testautomation_suites.h"
 
+typedef struct {
+    SDL_bool init_audio;
+} TestautomationAudioData;
+
 /* ================= Test Case Implementation ================== */
 
 /* Fixture */
 
-static void audioSetUp(void *arg)
+static void audioSetUp(void **arg)
 {
+    TestautomationAudioData *userdata;
     /* Start SDL audio subsystem */
     SDL_bool ret = SDL_InitSubSystem(SDL_INIT_AUDIO);
     SDLTest_AssertPass("Call to SDL_InitSubSystem(SDL_INIT_AUDIO)");
@@ -28,13 +33,24 @@ static void audioSetUp(void *arg)
     if (!ret) {
         SDLTest_LogError("%s", SDL_GetError());
     }
+    userdata = SDL_calloc(1, sizeof(TestautomationAudioData));
+    if (userdata) {
+        userdata->init_audio = ret;
+    }
+    *arg = userdata;
 }
 
 static void audioTearDown(void *arg)
 {
+    TestautomationAudioData* userdata = arg;
     /* Remove a possibly created file from SDL disk writer audio driver; ignore errors */
     (void)remove("sdlaudio.raw");
 
+    if (userdata && userdata->init_audio) {
+        SDL_QuitSubSystem(SDL_INIT_AUDIO);
+        SDLTest_AssertPass("Call to SDL_QuitSubSystem()");
+        SDL_free(userdata);
+    }
     SDLTest_AssertPass("Cleanup of test files completed");
 }
 
diff --git a/test/testautomation_blit.c b/test/testautomation_blit.c
index f13d9abf9..8ea58604f 100644
--- a/test/testautomation_blit.c
+++ b/test/testautomation_blit.c
@@ -40,7 +40,7 @@ Uint32 getRandomUint32() {
 /*
  * Resets PRNG state to initialize tests using PRNG
  */
-void blitSetUp(void *arg) {
+void blitSetUp(void **arg) {
     rngState[0] = 1;
     rngState[1] = 2;
 }
diff --git a/test/testautomation_iostream.c b/test/testautomation_iostream.c
index 23ac85061..3cff4aae5 100644
--- a/test/testautomation_iostream.c
+++ b/test/testautomation_iostream.c
@@ -32,7 +32,7 @@ static const char IOStreamAlphabetString[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
 
 /* Fixture */
 
-static void IOStreamSetUp(void *arg)
+static void IOStreamSetUp(void **arg)
 {
     size_t fileLen;
     FILE *handle;
diff --git a/test/testautomation_render.c b/test/testautomation_render.c
index 809a7ae91..230b5d3c7 100644
--- a/test/testautomation_render.c
+++ b/test/testautomation_render.c
@@ -44,7 +44,7 @@ static SDL_bool hasDrawColor(void);
 /**
  * Create software renderer for tests
  */
-static void InitCreateRenderer(void *arg)
+static void InitCreateRenderer(void **arg)
 {
     int width = 320, height = 240;
     const char *renderer_name = NULL;
diff --git a/test/testautomation_subsystems.c b/test/testautomation_subsystems.c
index 626c202e0..ab92bcaa8 100644
--- a/test/testautomation_subsystems.c
+++ b/test/testautomation_subsystems.c
@@ -9,7 +9,7 @@
 
 /* Fixture */
 
-static void subsystemsSetUp(void *arg)
+static void subsystemsSetUp(void **arg)
 {
     /* Reset each one of the SDL subsystems */
     /* CHECKME: can we use SDL_Quit here, or this will break the flow of tests? */
diff --git a/test/testautomation_surface.c b/test/testautomation_surface.c
index de1ce38a1..c10dc259e 100644
--- a/test/testautomation_surface.c
+++ b/test/testautomation_surface.c
@@ -41,7 +41,7 @@ static SDL_Surface *testSurface = NULL;
 /* Fixture */
 
 /* Create a 32-bit writable surface for blitting tests */
-static void surfaceSetUp(void *arg)
+static void surfaceSetUp(void **arg)
 {
     int result;
     SDL_BlendMode blendMode = SDL_BLENDMODE_NONE;
diff --git a/test/testautomation_timer.c b/test/testautomation_timer.c
index d04979efa..f8dc7138e 100644
--- a/test/testautomation_timer.c
+++ b/test/testautomation_timer.c
@@ -20,7 +20,7 @@ static int g_timerCallbackCalled = 0;
 
 /* Fixture */
 
-static void timerSetUp(void *arg)
+static void timerSetUp(void **arg)
 {
     /* Start SDL timer subsystem */
     SDL_bool ret = SDL_InitSubSystem(SDL_INIT_TIMER);

```

</details>

**Comment by icculus** [comment]
Guessing the common denominator here is Visual Studio, then.

**Comment by madebr** [comment]
> Guessing the common denominator here is Visual Studio, then.

This was built with mingw64. So I'd say Windows.

I just got this error:
```
 09/01/24 18:39:55: Assert 'Call to convert_audio_chunks(stream, buf_in, 19200000, buf_out, 4410000)': Passed
ERROR: 09/01/24 18:39:55: Assert 'Expected output length to be 4410000, got 1494488.': Failed
```

**Comment by slouken** [comment]
I ran it 1000 times and it failed 3 times. I'm setting a breakpoint to catch the error.

**Comment by slouken** [comment]
And of course a second thousand runs it didn't fail at all...

**Comment by sezero** [comment]
> And of course a second thousand runs it didn't fail at all...

it's mocking us :))

**Comment by slouken** [comment]
Okay, I think I see what's going on here. When we write a very small number of bytes into the stream (12) we don't get any bytes out, because it's within the number of padding bytes we keep in the stream and we're not flushing it yet. The test assumes this means end of stream, and returns a short count, which is a test failure.

I'm still looking at the best fix, but the good news is that this appears to be a test issue, not an SDL issue.

**Comment by slouken** [comment]
Fixed, AND I figured out why re-running with the same seed wouldn't let us reproduce the issue. :)
