### ISSUE TITLE
Problem with fullscreen modes when rotating a Windows 8 tablet by 90 degrees

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1061]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.0
**Reported for operating system, platform:** Windows 8, x86_64

# Comments on the original bug report:

On 2013-09-01 14:11:55 +0000, Elmar wrote:

> Hi,
> 
> if my app is running in fullscreen mode on a Windows 8 tablet, and the user rotates the tablet by 90 degrees, troubles start...
> 
> The good news is that a resize event arrives. If the normal fullscreen resolution is 1366x768, then the resize event usually reports 768x1366 (which is perfect), but not always, sometimes I get something broken like 768x1351 or so.
> 
> The bad news is that the function below doesn't get the new display modes after a 90 degree rotation, since it uses '!display->num_display_modes'.
> 
> ```c
> SDL_GetNumDisplayModesForDisplay(SDL_VideoDisplay * display)
> {
>     if (!display->num_display_modes && _this->GetDisplayModes) {
>         _this->GetDisplayModes(_this, display);
>         SDL_qsort(display->display_modes, display->num_display_modes,
>                   sizeof(SDL_DisplayMode), cmpmodes);
>     }
>     return display->num_display_modes;
> ```
>
> I fear the SDL code can currently not handle resolutions that change at app runtime..
> 
> Best regards,
> Elmar

**Comment by icculus** [comment]
My suspicion is we have fixed this since 2013; going to close for now.

**Comment by icculus** [comment]
Actually, wait, we _can_ handle orientation changes, but I'm pretty sure we can't handle dynamic display resolution changes. Putting this in 2.0.18 for consideration (but possibly it gets kicked to a later milestone).

**Comment by slouken** [comment]
I added the dynamic orientation change event on Windows and set up the infrastructure for a resolution change event, if we want to add one.
