### ISSUE TITLE
Suggestion: Remove SDL_SCALEMODE_BEST

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL#10619]
Correct me if I'm wrong but as far as I can tell, it's not even possible to render obliquely in SDL_render, nor is it possible to set mipmaps, so anisotropic filtering is just a waste of performance. I think calling it BEST is misleading at best. If anything it could at least be renamed to ANISOTROPIC just to make it clear what the actual mode is.

**Comment by slouken** [comment]
Agreed.
