### ISSUE TITLE
GPU: vsync is always enabled

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#10623]
D3D12_ClaimWindow() has the line:
```c
D3D12_INTERNAL_CreateSwapchain(renderer, windowData, SDL_GPU_SWAPCHAINCOMPOSITION_SDR, SDL_GPU_PRESENTMODE_VSYNC);
```
This means that the SDL renderer has vsync enabled regardless of the actual setting when creating a renderer.

**Comment by Akaricchi** [comment]
Is this D3D12 specific? Clients are expected to call `SDL_SetGPUSwapchainParameters` to change the presentation mode after claiming the window. The render driver does that, and it works for me on Vulkan. Can't test D3D12 right now because I'm on Linux.

**Comment by slouken** [comment]
Yes, this seems to be D3D12 specific.

**Comment by thatcosmonaut** [comment]
I think the actual issue here is that SDL_render_gpu.c is waiting for the present fence on every submission, which will effectively limit the framerate to the presentation timing.

**Comment by Akaricchi** [comment]
Why does Vulkan behave differently? Also you still got about 500 fps from testrendertarget, didn't you? Abysmal compared to Vulkan, but a far cry from 60… You're definitely right that presentation needs an improvement though. I'll try copying the FNA method tomorrow.

**Comment by flibitijibibo** [comment]
Fixed by https://github.com/libsdl-org/SDL/commit/5c8bed378040007d0e2e9267ff4bc76c016cee8f

**Comment by slouken** [comment]
Nice fix! :)
