### ISSUE TITLE
testyuv has incorrect colors when converting to RGB for texture upload

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#10624]
The hardware YUV output differs from the software output (and that of the non-GPU renderers)

**Comment by Akaricchi** [comment]
YUV support is not yet implemented in the render driver, so the fact that it runs at all must be because SDL converts it into RGBA before sending it to the driver.

**Comment by slouken** [comment]
Okay, once the text shows up I'll debug that conversion and see why it doesn't match the expected output.

**Comment by slouken** [comment]
Fixed!
