### ISSUE TITLE
Compiler warnings with system locale set to JP.

### ISSUE THREAD

**Issue by duerdak** [libsdl-org/SDL#10636]
I get the following warnings when trying to compile SDL3 on win 10 with system locale set to JP. There aren't all the warnings but here's a few:
![image](https://github.com/user-attachments/assets/3c3af02a-1dd1-46a2-82be-d2a300f68ce5)

**Comment by sezero** [comment]
I guess it this line 2142 in current SDL_hints.h ?
` *   keyboard would yield 'a' instead of 'ф'.`

**Comment by duerdak** [comment]
There's also one in SDL_joystick.c
![image](https://github.com/user-attachments/assets/d6a72e88-188e-4b1a-a2e8-75b45901f7f6)

**Comment by sezero** [comment]
> There's also one in SDL_joystick.c

That would be:
`    MAKE_VIDPID(0x0f0d, 0x011e), // Hori Fighting Stick α in PC Mode`
... at line 140 of SDL_joystick.c

**Comment by sezero** [comment]
> > There's also one in SDL_joystick.c
> 
> That would be: ` MAKE_VIDPID(0x0f0d, 0x011e), // Hori Fighting Stick α in PC Mode` ... at line 140 of SDL_joystick.c

Well, make that lines 139 to 141 where there is that `α` character...

**Comment by Susko3** [comment]
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=msvc-170

> C4819 occurs when you compile an ANSI source file on a system using a codepage that can't represent all characters in the file.

> Save the file in Unicode format to prevent data loss.

Perhaps the header files you have on disk are malformed in some way. Try redownloading SDL3 source again from https://github.com/libsdl-org/SDL/archive/refs/heads/main.zip.

If that doesn't help, try saving the offending files in 'UTF-8 (with signature/BOM)' encoding as suggested by the error description.

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by sezero** [comment]
BTW, SDL2 has a similar issue in SDL_audio.h at line 1175:
` * \param volume ranges from -128 - ∞ (at -128, the volume is at 0%, at 0 -`

.. but not release-2.30.x -- the diff between them being:
```diff
- * \param volume ranges from 0 - 128, and should be set to SDL_MIX_MAXVOLUME
- *               for full audio volume
+ * \param volume ranges from -128 - ∞ (at -128, the volume is at 0%, at 0 -
+ *               100% and the higher the number, the bigger the %), and should
+ *               be set to SDL_MIX_MAXVOLUME for full audio volume.
```

**Comment by sezero** [comment]
> BTW, SDL2 has a similar issue in SDL_audio.h at line 1175: ` * \param volume ranges from -128 - ∞ (at -128, the volume is at 0%, at 0 -`
> 
> .. but not release-2.30.x -- the diff between them being:
> 
> ```diff
> - * \param volume ranges from 0 - 128, and should be set to SDL_MIX_MAXVOLUME
> - *               for full audio volume
> + * \param volume ranges from -128 - ∞ (at -128, the volume is at 0%, at 0 -
> + *               100% and the higher the number, the bigger the %), and should
> + *               be set to SDL_MIX_MAXVOLUME for full audio volume.
> ```

Should we replace that `∞` with, like, INT_MAX if we want to fix that??

**Comment by slouken** [comment]
We shouldn't have changed the volume parameter in SDL2. I'll take a look.

**Comment by slouken** [comment]
We didn't, that was an incorrect edit pulled in from the wiki.

**Comment by sezero** [comment]
> We shouldn't have changed the volume parameter in SDL2. I'll take a look.

> We didn't, that was an incorrect edit pulled in from the wiki.

Revert then? (How was the wiki patch approved?)

**Comment by slouken** [comment]
> > We shouldn't have changed the volume parameter in SDL2. I'll take a look.
> 
> > We didn't, that was an incorrect edit pulled in from the wiki.
> 
> Revert then? (How was the wiki patch approved?)

Already done. (I've no idea)

**Comment by sezero** [comment]
> > Revert then? (How was the wiki patch approved?)
> 
> Already done. (I've no idea)

Looks like it was https://github.com/libsdl-org/sdlwiki/pull/485

**Comment by slouken** [comment]
> > > Revert then? (How was the wiki patch approved?)
> > 
> > 
> > Already done. (I've no idea)
> 
> Looks like it was [libsdl-org/sdlwiki#485](https://github.com/libsdl-org/sdlwiki/pull/485)

Yeah, that's not correct. Mixing at zero volume doesn't mix the source buffer at all, so there's no way that can result in mixing at full volume.
