### ISSUE TITLE
SDL3: Build fails on macOS

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10646]
Latest source code fails to build on macOS (latest version of macOS and Xcode; Mac mini M1). Report is appended.
[Build SDL3_2024-08-31T07-46-39.txt](https://github.com/user-attachments/files/16823579/Build.SDL3_2024-08-31T07-46-39.txt)

**Comment by madebr** [comment]
The xcode project needs an update for SDL_gpu
