### ISSUE TITLE
Nintendo NSO N64 Controller Mapping in Linux

### ISSUE THREAD

**Issue by theksepyro** [libsdl-org/SDL#10658]
When using the NSO N64 controller via wired connection in linux (Pop!_OS 22.04), the Z and Down-C buttons are treated as Axes rather than Buttons (lefttrigger+ and righttrigger+ respectively). In emulators that use SDL for their controller plugin this can cause these buttons to behave as though they are being held down even when they are not. 

There exist other buttons on the NSO N64 controller that basically don't get used that are mapped to other "buttons" rather than axes that in my opinion would be better fits for Z and Down C. The "Screenshot" button on the top left of the controller is mapped to "misc1" and the ZR button is mapped to leftstick.

**Comment by slouken** [comment]
So I double checked, and this mapping is what the controller actually provides for those controls. This controller uses the Switch Pro wire protocol and generates left trigger input for Z and right trigger input for C down, and the other buttons as you've mentioned.

I understand this isn't ideal for emulators, but is what Nintendo has designed for this controller. I'll go ahead and leave this as-is, and users and applications are always welcome to change the mapping to better suit their needs.
