### ISSUE TITLE
Names of gpu backends don't match those of the 2d renderer backend

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10650]
The SDL_Render backend has "direct3d", "direct3d11" and "direct3d12".
The SDL_Gpu backend has "d3d11" and "d3d12".

I propose to rename the gpu backend names.

**Comment by slouken** [comment]
I agree they should match, and it makes sense to use the names that people are already familiar with in the 2D renderer. @thatcosmonaut, are you fine with that?

**Comment by thatcosmonaut** [comment]
Fine by me.

**Comment by slouken** [comment]
Done!
