### ISSUE TITLE
GPU: API does not follow the SDL3 naming conventions

### ISSUE THREAD

**Issue by sbhutch** [libsdl-org/SDL#10661]
I noticed that SDL_gpu.h was recently added to main, congratulations! I wanted to point out that the structures are using camel case field names, which is inconsistent with most other public structures in SDL3, which use snake_case.

**Comment by slouken** [comment]
@flibitijibibo, this is part of the SDL3 naming convention. Can you review and fix? build-scripts/rename_symbols.py should be able to assist if you need it.

**Comment by flibitijibibo** [comment]
It might be up to a week before I can take a look, but the rest of the FNA team is now aware so it may get done sooner.
