### ISSUE TITLE
SDL_HINT_X11_XCB_LIBRARY should default to libX11-xcb.so.1 on most platforms

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#10677]
`SDL_HINT_X11_XCB_LIBRARY`, the library that is loaded to provide `XGetXCBConnection()`, currently defaults to `libX11-xcb.so`.

This is a problem for two reasons:

1. On OSs like the Debian and Fedora families that separate development files (typically a `-dev` or `-devel` package) from runtime libraries, `libX11-xcb.so` only exists if you have the development files installed, which end users typically will not.
2. If there is an ABI break in libX11-xcb at some point in the future (unlikely, but possible), `libX11-xcb.so` will normally point to the newest available ABI, which might not be compatible with the ABI that SDL and libvulkan were compiled with.

It should default to `libX11-xcb.so.1` on Linux, and probably every Unix platform except OpenBSD (which does not have a stable ABI and does not normally use ABI suffixes, so `libX11-xcb.so` is probably still correct there).

**Comment by slouken** [comment]
Agreed, can you whip up a quick PR for this?
