### ISSUE TITLE
`SDL_gpu.h` flags enums don't follow convention

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#10673]
SDL_gpu:

https://github.com/libsdl-org/SDL/blob/df501040fd646a1f4eab92aa5b698b35a36013ed/include/SDL3/SDL_gpu.h#L201-L211

Convention:

https://github.com/libsdl-org/SDL/blob/df501040fd646a1f4eab92aa5b698b35a36013ed/include/SDL3/SDL_pen.h#L68-L75

**Comment by slouken** [comment]
@flibitijibibo, this should be fixed when you go through and do a documentation pass. We don't use any kind of bit operation macros, so these should be plain defines.
