### ISSUE TITLE
Binary representation of `SDL_bool` is not clear

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#10672]
I'm writing cross-platform C# language bindings for SDL3. It's important to know the binary representation of `SDL_bool` so that it can be correctly used in C# code.

With f08ac438ed95dcdac2086f9bf84211d8ed6203a2 `SDL_bool` is now defined as a C `stdbool` or C++ `bool`. `stdbool` defines `true` as 1, and `false` as 0 so the binary representation is obvious. In C++, the representation of `bool` is a compiler implementation detail. (Also [C23 has proper bools now](https://en.cppreference.com/w/c/language/bool_constant)).

It would be helpful if you (the SDL team) looks at how the different compilers represent `SDL_bool` and provide documentation or compile time asserts on the binary representation of `SDL_TRUE` and `SDL_FALSE`. (Similar to how you check the size of `SDL_bool`).

https://github.com/libsdl-org/SDL/blob/df501040fd646a1f4eab92aa5b698b35a36013ed/include/SDL3/SDL_stdinc.h#L488

**Comment by maia-s** [comment]
I looked into this myself recently, and the conclusion of some Rust internals experts I asked is that C99 `_Bool` and C23 `bool` is binary compatible with Rust's `bool`, which is to say:
- Its size and alignment is one byte
- True is represented as `0x01`
- False is represented as `0x00`
- Any other value triggers undefined behaviour

**Comment by slouken** [comment]
> I looked into this myself recently, and the conclusion of some Rust internals experts I asked is that C99 `_Bool` and C23 `bool` are binary compatible with Rust's `bool`, which is to say:
> 
> * Its size and alignment is one byte
> * True is represented as `0x01`
> * False is represented as `0x00`
> * Any other value triggers undefined behaviour

This is SDL's expectation as well.
