### ISSUE TITLE
GPU: {Begin,End}GPURenderPass is a bit stinky

### ISSUE THREAD

**Issue by misyltoad** [libsdl-org/SDL#10671]
I don't really like the current {Begin,End}GPURenderPass API.

It really doesn't make sense for the users of the API to be responsible for tracking their renderpass and ending it.

Vulkan has deprecated renderpasses in Vulkan 1.3/with KHR_dynamic_rendering, and it really sucks that this awful smell of lingers in the SDL GPU api. No other graphics APIs have the requirement of renderpasses.

It would be really nice if this was just removed and replaced with `BindColorAttachments` or `BindDepthAttachments`, or `BeginRendering/EndRendering`. (I would prefer not even having the concept of renderpasses/begin/end rendering tbh)
The SDL GPU API could map that API to it's own renderpass tracking where `KHR_dynamic_rendering` is not supported, like DXVK pre-2.0 used to do.

Alternatively, I would be happy enough for the GPU API to just track the current "renderpass" on the command buffer, and make EndGPURenderPass take no args. 

I think it is a **huge** mistake to require the caller to track this for EndGPURenderPass, and I see no advantage for it. It's just clunky and bad API design that is seemingly inherited from the mistakes of renderpasses in Vulkan.

Something should be done about this before SDL3's release, as then it has to support it FOREVER and that would suck.

**Comment by Joshua-Ashton** [comment]
Actually, renderpasses in Vulkan don't even take the renderpass for end, and the backend just takes the command buffer...

```
static void VULKAN_EndRenderPass(
    SDL_GPUCommandBuffer *commandBuffer)
```

and the common code that DOES take the `renderpass` also barely uses it. So...

**Comment by thatcosmonaut** [comment]
Yes, it is annoying in Vulkan to have to create VkRenderPass objects and framebuffers. Fortunately our GPURenderPass is not conceptually equivalent to that. Our render pass is just a transient handle that is only there to hint towards correct usage of the API. You might note that VK_KHR_dynamic_rendering's VkRenderingInfo struct is basically equivalent to the parameters passed in to BeginGPURenderPass. It's literally the exact approach this API takes.

We also have compute passes and copy passes. Passes in this API exist so that we can do proper resource synchronization. It's illegal in Vulkan to do operations like memory barriers after calling vkCmdBeginRendering. or vkCmdBeginRenderPass. There's good reason for this.

**Comment by Joshua-Ashton** [comment]
I understand that they are not directly equivalent, and I agree that the design right now is much nicer -- but I think that my main gripe is simply that handle, and that EndGPURenderPass takes a render pass, rather than the command buffer.

It makes state tracking more annoying for the client.

**Comment by thatcosmonaut** [comment]
This is one of those things where I can't please everyone - there was no handle before and people complained about it. The client has to track state anyway because if they call a compute or copy function while inside a render pass it's a spec violation.

**Comment by Joshua-Ashton** [comment]
> I wasn't aware that render passes were outright deprecated... is this documented somewhere?

`VK_KHR_dynamic_rendering` was promoted to core in 1.3, which means all Vulkan 1.3 and above drivers **must** expose support for it.

With `VK_KHR_dynamic_rendering_local_read` it also fully encompasses all of what renderpasses could do, with subpasses.

You can get the jist of how renderpasses are percieved here https://www.khronos.org/blog/streamlining-render-passes and here https://www.khronos.org/news/press/khronos-drives-industry-support-for-expanded-3d-features-with-vulkan-roadmap-2024 -> `allowing developers to fully move over to dynamic rendering on all GPUs`

As for the term "deprecated", the Khronos group/Vulkan WG has never _officially_ used that term, but they essentially are at this point.

**Comment by flibitijibibo** [comment]
They might need to do that at some point, while we didn't fall into that pit I could see others falling into it maybe, particularly for compatibility reasons.

Good to know, but this should still be prototyped if we _need_ to strip these handles out - FNA3D is probably the best stress test we have for synchronizing render and copy passes at least, compute would need to be checked as well but the examples can cover that.

**Comment by Akaricchi** [comment]
I don't like the idea of removing the render pass handles. They make the API self-documenting through use of the type system to guide the correct call order. That's just good API design, IMO. It doesn't matter whether they use Vulkan render passes or dynamic rendering under the hood.

I also don't understand the complaint about having to track the handle. I've ported 2 things to this API now, and I probably would've needed some form of render pass tracking in both of them. Having an explicit handle just makes it easier.
