### ISSUE TITLE
GPU: Reference stencil should be dynamic

### ISSUE THREAD

**Issue by TheSpydog** [libsdl-org/SDL#10683]
Currently `reference` is a member of the `SDL_GPUDepthStencilState` struct used for pipeline creation, but there's no technical reason to bake it into the pipeline. D3D and Metal _only_ support stencil reference as dynamic state, and Vulkan 1.0 allows it via VkDynamicState. So let's add an `SDL_GPUSetStencilReference` function that can be called during render passes, similar to the SetViewport/Scissor calls we have now.

**Comment by conversy** [comment]
Hi,

is there any reason why this could not be applied to all members of `SDL_GPUDepthStencilState`? My use of stencil is I think pretty straightforward, setting `INCR` or `KEEP` or `DECR` or write_mask according to the rendering state.

I tried to circumvent the problem by creating multiple pipelines (which seems to be wrong IMO, as the number of pipelines might grow exponentially to take care of multiple combinations of features), but I do not know how to create pipelines that reuse the texture of the previous pipelines anyway...

Best regards.
