### ISSUE TITLE
GPU: Remove stride parameter from DrawPrimitivesIndirect

### ISSUE THREAD

**Issue by TheSpydog** [libsdl-org/SDL#10696]
Currently we require the client to provide a `stride` parameter in `DrawPrimitivesIndirect`/`DrawIndexedPrimitivesIndirect` to indicate the byte distance between consecutive indirect arguments encoded in an indirect buffer.

If we require that indirect buffers are tightly packed (which is [required by WebGPU](https://developer.mozilla.org/en-US/docs/Web/API/GPURenderPassEncoder/drawIndirect)) we could remove the stride parameter and all backend complication that comes along with it. This would be particularly helpful for D3D12, which requires a unique signature object to be created for every possible stride length.

**Comment by slouken** [comment]
Also, if we keep this parameter, we should rename it `pitch` to be consistent with the rest of the SDL API.
