### ISSUE TITLE
Linux:  Gamesir-T1s and Logitech G29 Wheel are not detected

### ISSUE THREAD

**Issue by lestcape** [libsdl-org/SDL#10697]
I'm running Debian 12 stable, and the default package libsdl2-2.0-0 version 2.26.5+dfsg-1 installed in x64 and i386.

I have a Gamesir-T1s, and a Logitech G29 Driving Force Racing Wheel, both are detected by the Linux Kernel, but some games and emulators only use libsdl to detect controllers on Linux (like Cemu) and unfortunately these don't detect any of the only two devices I have, which results in very bad statistics.

I know I'm using a version of libsdl that can be considered old here, but that's the price of using a stable distro. So, how can I find out what is causing this failure and find a solution? Is there any tool that can scan and give me a report of what is happening and regardless of what I can see or not in the emulator that uses libsdl?

What can I do if my device is not detected? Besides reporting it of course. Maybe there are some way to compile a new version of libsdl locally and force the emulator to use the local copy when running?  That at less will help to know if the problem was fixed in a new release.

**Comment by lestcape** [comment]
This is probably related with: https://github.com/libsdl-org/SDL/issues/10281 I use the class he provide to test what going own. And that is the result with both devices connected:

```
./test
Initializing SDL...
SDL initialized.
1 joysticks were found.

The names of the joysticks are:
Logitech G29 Driving Force Racing Wheel

IsGameController: 0
Failed to open GameController 0
Quitting SDL...
```

So yes, is not Cemu, there are problems to detect the Gamesir-T1s and the Logitech G29 Wheel is not detected as a Game controller. Maybe all this was solved in a new version of the library, but I still don't know how to test the new version without ending up messing up my system.

**Comment by slouken** [comment]
That's correct, wheels are not game controllers. The applications should be opening them as joysticks.

**Comment by slouken** [comment]
At least that's true for the wheel. I'm not sure why the T1s isn't showing up.

**Comment by lestcape** [comment]
> That's correct, wheels are not game controllers. The applications should be opening them as joysticks.

Cemu not detect it as anything. Are there a way to configured the library to see the wheels as a game controllers? I see that: https://github.com/libsdl-org/SDL/commit/189f71efb36da8a1c4b4c581023908a4162fa56e, but the problem with this argument is that not all in Linux is steam. What about other applications that are not steam and have a poor support for games controllers and who could benefit from something like that?

> At least that's true for the wheel. I'm not sure why the T1s isn't showing up.

Yes, well T1s is not in the libsdl official database, but it should be detected and let you to configured it. It's detected by SDL2 Gamepad Tool of General Arcade as 05004477ac0500002d0200001b010000 and they have a map available for it, but if libsdl can not see it, Cemu also can not.

![Captura desde 2024-09-04 13-26-32](https://github.com/user-attachments/assets/351ccedb-6909-4a0d-a5c7-7fecd2d9b5fb)

**Comment by lestcape** [comment]
I was also going to propose to use a pointer to a file in SDL_GAMECONTROLLERCONFIG instead of directly the settings, because seems that if you exceed a certain amount of device settings, the results are problematic: https://www.reddit.com/r/linux_gaming/comments/9cf6ip/comment/jjc2tbg/, but apparently this is included in sdl3 as can read in: https://github.com/libsdl-org/SDL/blob/f317581c91961ee628446886dd4df87e9c16ac79/include/SDL3/SDL_hints.h#L792

**Comment by lestcape** [comment]
I will close this, because i suspect the problem with the Gamesir-T1s will be resolved using a new version of the library and the reality is that i don't care about if this device work or not.  I care much more about the G29 and i know there are efforts to add better support for this type of devices.
