### ISSUE TITLE
GPU: CreateGPUGraphicsPipeline fails with non-empty color attachment descriptions

### ISSUE THREAD

**Issue by JBetz** [libsdl-org/SDL#10699]
I've been working my way through the SDL_gpu examples to test my [Dolphin Smalltalk bindings](https://github.com/JBetz/Dolphin-SDL), and so far have got `ClearScreen`, `Clear3DSlice`, `ComputeUniforms`, and `GenerateMipmaps` working, but I'm getting an invalid memory access when trying to run `BasicTriangle`.

The example fails during initialization in the call to `CreateGPUGraphicsPipeline`. Notably, it _doesn't_ fail if the array passed to `attachment_info.color_attachment_descriptions` is empty. So my best guess is that it's an issue with how the FFI is handling arrays. I've also tried simplifying the interface to just passing a pointer to a `GPUColorAttachmentDescription`, but that didn't help. I also don't think I've ever had an issue with this type of interface before.

Any ideas?

**Comment by JBetz** [comment]
![image](https://github.com/user-attachments/assets/9c9630dd-784f-4035-ae70-d8993a75c2d9)

**Comment by Capati** [comment]
I can relate to this issue using Odin Language, in my case the `attachmentInfo` becames invalid in the SDL side, acctually everything after `backStencilState` turn invalid.

Using an AddressSanitizer I got this information:

```
==13132==ERROR: AddressSanitizer: access-violation on unknown address 0x000000000000 (pc 0x7ffb35e7459d bp 0x0036f86ff020 sp 0x0036f86fede0 T0)
==13132==The signal is caused by a READ memory access.
==13132==Hint: address points to the zero page.
    #0 0x7ffb35e7459c in SDL_CreateGPUGraphicsPipeline_REAL \cpp\SDL\src\gpu\SDL_gpu.c:650
    #1 0x7ffb35e376ae in SDL_CreateGPUGraphicsPipeline \cpp\SDL\src\dynapi\SDL_dynapi_procs.h:135
    #2 0x7ff70260a691 in sdl3.create_gpu_graphics_pipeline \odin\sdl3-odin\sdl3\sdl_gpu.odin:1118:14
    #3 0x7ff70259c6b1 in gpu_basic_triangle.init \basic_triangle.odin:59:22
    #4 0x7ff70259ce69 in gpu_basic_triangle.main \basic_triangle.odin:80:2
    #5 0x7ff7025f3c4e in main \base\runtime\entry_windows.odin:46:4
    #6 0x7ff70265b03b in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #7 0x7ff70265b03b in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #8 0x7ffb85ac257c  (C:\Windows\System32\KERNEL32.DLL+0x18001257c)
    #9 0x7ffb8708af27  (C:\Windows\SYSTEM32\ntdll.dll+0x18005af27)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: access-violation \cpp\SDL\src\gpu\SDL_gpu.c:650 in SDL_CreateGPUGraphicsPipeline_REAL
==13132==ABORTING
```

Line to the breakpoint:

![image](https://github.com/user-attachments/assets/bac2bb12-3fbf-4977-b789-3e708b25c80f)

After more debugging on my side using raddbg, I see a padding before `attachmentInfo`, not sure if its a compiler optimization or ui bug:

![image](https://github.com/user-attachments/assets/66aea76f-0223-4494-8e0d-5af34ad4bd14)

**Comment by thatcosmonaut** [comment]
I think the issue here is non-intuitive struct padding caused by the change of SDL_bool to a 1-byte type. I'll look into this.

**Comment by JBetz** [comment]
Indeed, it works when I specify the bool fields as 1-byte:
![image](https://github.com/user-attachments/assets/1d64e17d-e1bb-4b9e-b270-ab0057a13913)

**Comment by thatcosmonaut** [comment]
PR: #10701
