### ISSUE TITLE
GPU: Prioritize Vulkan backend on Windows

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL#10719]
The D3D12 backend is strictly inferior to our Vulkan backend at this point, mostly due to much more efficient memory management on the part of the Vulkan backend, so I recommend that we prefer it over D3D12 when both are available. We can always re-evaluate the order preference when the D3D12 implementation improves.

**Comment by flibitijibibo** [comment]
Can be obsoleted by #10632
