### ISSUE TITLE
change SDL_GPU_VULKAN to match the other preprocessor definitions

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#10718]
from https://github.com/libsdl-org/SDL/pull/10709:

> We should probably change this to match the other preprocessor definitions, which are mostly `#define 1` or `#undef`

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/387774ab8a32151d12f3e76653d5b5bc070a28ce
