### ISSUE TITLE
`GL.currentContext.tempVertexBufferCounters1 is undefined` when trying to use OpenGL ES in Emscripten with SDL3

### ISSUE THREAD

**Issue by WerWolv** [libsdl-org/SDL#10720]
Hey

I'm working on a project that uses ImGui and is supposed to run on Windows, macOS and Linux as well as on the web using emscripten. On the native targets everything works correctly, however in Emscripten, the following error is thrown as soon as execution hits `emscripten_set_main_loop_arg`.

```
Uncaught TypeError: GL.currentContext.tempVertexBufferCounters1 is undefined
    newRenderingFrameStarted http://127.0.0.1:9090/test.js line 6023 > srcScript:6058
    Browser_mainLoop_runner http://127.0.0.1:9090/test.js line 6023 > srcScript:5359
    webgl_enable_ANGLE_instanced_arrays http://127.0.0.1:9090/test.js:6023
    initExtensions http://127.0.0.1:9090/test.js:6292
    registerContext http://127.0.0.1:9090/test.js:6249
    createContext http://127.0.0.1:9090/test.js:6229
    _emscripten_webgl_do_create_context http://127.0.0.1:9090/test.js:9740
    _main http://127.0.0.1:9090/test.js:10773
    callMain http://127.0.0.1:9090/test.js:11124
    ...
```

I tried debugging myself a bit and found that the `tempVertexBufferCounters1` variable is only being initialized when `Emscripten_UpdateWindowFramebuffer` is being called which doesn't happen when using the OpenGL context alone.

I've also tried building the [ImGui + SDL3 + OpenGL3 example](https://github.com/ocornut/imgui/blob/master/examples/example_sdl3_opengl3/main.cpp) for emscripten and got the same results.

**Comment by icculus** [comment]
The linked example is definitely working here:

![image](https://github.com/user-attachments/assets/2dca6c03-af38-4465-949a-ac6b2a3c0b12)

I'll note that tempVertexBufferCounters1 is not mentioned in SDL's code (it's an internal Emscripten thing as far as I can tell), so it's possible a different version of Emscripten fixes this, or something in a newer SDL3 or Dear Imgui fixed it.

I'll also note that I had to tweak Dear Imgui's Makefile.emscripten in that example to make it build, since it still references SDL2, and one can't just change it from `USE_SDL=2` to `USE_SDL=3` yet, so I pointed it at an SDL3 build I compiled myself:

```diff
diff --git a/examples/example_sdl3_opengl3/Makefile.emscripten b/examples/example_sdl3_opengl3/Makefile.emscripten
index 57247ff2..2325534f 100644
--- a/examples/example_sdl3_opengl3/Makefile.emscripten
+++ b/examples/example_sdl3_opengl3/Makefile.emscripten
@@ -36,9 +36,10 @@ EMS =
 ##---------------------------------------------------------------------
 
 # ("EMS" options gets added to both CPPFLAGS and LDFLAGS, whereas some options are for linker only)
-EMS += -s USE_SDL=2
+#EMS += -s USE_SDL=2
+EMS += -I/home/icculus/projects/SDL-icculus/include
 EMS += -s DISABLE_EXCEPTION_CATCHING=1
-LDFLAGS += -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=0 -s ASSERTIONS=1
+LDFLAGS += -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=0 -s ASSERTIONS=1 /home/icculus/projects/SDL-icculus/buildbot-emsdk/libSDL3.a
 
 # Build as single file (binary text encoded in .html file)
 #LDFLAGS += -sSINGLE_FILE
@@ -53,7 +54,7 @@ LDFLAGS += -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=0 -s ASSERTIONS
 # (Default value is 0. Set to 1 to enable file-system and include the misc/fonts/ folder as part of the build.)
 USE_FILE_SYSTEM ?= 0
 ifeq ($(USE_FILE_SYSTEM), 0)
-LDFLAGS += -s NO_FILESYSTEM=1
+#LDFLAGS += -s NO_FILESYSTEM=1
 CPPFLAGS += -DIMGUI_DISABLE_FILE_FUNCTIONS
 endif
 ifeq ($(USE_FILE_SYSTEM), 1)
```
