### ISSUE TITLE
GPU: Compute Samplers?

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#10733]
There currently doesn't seem to be any support for texture sampling in compute shaders, unless I'm missing something. This would be useful for (at least) compute-based post-processing. It's of course possible to emulate this with read-only storage textures but that's a pretty crappy solution that shouldn't be forced on users.

**Comment by thatcosmonaut** [comment]
For some reason I had gotten it in my head that compute samplers weren't supported on one of our backends, but I glanced over documentation and that isn't true. I'll add this.
