### ISSUE TITLE
SDL_PRESSED and SDL_RELEASED as bool? (take 2)

### ISSUE THREAD

**Issue by maia-s** [libsdl-org/SDL#10736]
I wanted to ask if it'd make sense to make SDL_PRESSED and SDL_RELEASED into SDL_bools, and found issue #10069, in which it was decided not to do this because SDL_bool at the time was incompatible with Uint8 as used in event structs. But as of the change to make SDL_bool use stdbool, it should now have the same size and alignment as Uint8, so I wanted to ask if this makes sense to do now.

**Comment by slouken** [comment]
Yep, I think it does. I reopened the original issue, for more context. Thanks for the ping!
