### ISSUE TITLE
WinRT readme was restored by the wiki bridge

### ISSUE THREAD

**Issue by zturtleman** [libsdl-org/SDL#10737]
fyi the wiki bridge readded docs/README-winrt.md in https://github.com/libsdl-org/SDL/commit/6da97c63da926098db3bd212637f15d7915eeba4 after it was removed in https://github.com/libsdl-org/SDL/commit/154452a72636ee7fd718c464e9d95860289db624.

**Comment by icculus** [comment]
Ah, the bridge won't delete files and doesn't know when one was intentionally deleted. The solution is to push deletes to both repos at once before the script runs for either commit.

Not a problem we're likely to have often again in SDL3.
