### ISSUE TITLE
GPU: Vulkan drawIndirectFirstInstance / WebGPU indirect-first-instance

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#10735]
This feature is required for setting firstInstance to non-zero in indirect draws, but isn't currently being checked or set.
Universally supported on desktop, but some older android HW doesn't support this.

EDIT: This is also not supported by default in WebGPU and requires the indirect-first-instance feature.
See: https://github.com/gpuweb/gpuweb/pull/2022 https://github.com/gpuweb/gpuweb/issues/1878

**Comment by thatcosmonaut** [comment]
It's an easy fix, we'll get it in ASAP.
