### ISSUE TITLE
Custom log categories ABI

### ISSUE THREAD

**Issue by zturtleman** [libsdl-org/SDL#10739]
Due to adding GPU log category, [SDL3 SDL_LOG_CATEGORY_RESERVED10](https://github.com/libsdl-org/SDL/blob/845855d6573c47f9f4c4074d575e431c90c2348c/include/SDL3/SDL_log.h#L104) (value 19) cannot currently be used by SDL3 in the future as sdl2-compat passes [SDL2 SDL_LOG_CATEGORY_CUSTOM](https://github.com/libsdl-org/SDL/blob/f5ed158d1f59d0d3bfe65f6c3603c5082c560797/include/SDL_log.h#L96) as the same value (19).

Could remove SDL3 RESERVED10 or have sdl2-compat add an offset to custom categories.

This is an observation related to fixing log category order in SDL 3 to match SDL 2 in https://github.com/libsdl-org/SDL/commit/360bc667a828425574a61a9bb8f9a98e88bfb44e.

**Comment by slouken** [comment]
Fixed, thanks!
