### ISSUE TITLE
SDL3: Crash when calling SDL_RenderPresent()

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10744]
My application suffers from a crashing bug with the latest revision of SDL3. I get this message inside Xcode when calling SDL_RenderPresent():

```
-[MTLDebugBlitCommandEncoder internalValidateCopyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:388: failed assertion `Copy From Texture Validation
destinationTexture must not be a framebufferOnly texture.
'
```

My system: Mac mini M1, macOS 14.6.1

**Comment by andreasgrabher** [comment]
The crash also happens when running testsprite
<img width="1512" alt="crash" src="https://github.com/user-attachments/assets/cab59b7a-688a-488d-a895-3fcd6f4d7837">

**Comment by thatcosmonaut** [comment]
Looks like the render backend is copying to the swapchain texture instead of blitting.

**Comment by andreasgrabher** [comment]
Great! Maybe you can also have look at this one: https://github.com/libsdl-org/SDL/issues/9698

Might this be a similar issue?

**Comment by thatcosmonaut** [comment]
That issue was filed before GPU was merged so I don't really know anything about how the other render backends work.
