### ISSUE TITLE
Clarify expected behavior of `SDL_strtol` and friends

### ISSUE THREAD

**Issue by castholm** [libsdl-org/SDL#10750]
Extracted from discussion in https://github.com/libsdl-org/SDL/pull/10741#discussion_r1748088833.

SDL's implements and exposes a subset of the C standard library. Most often, when the corresponding libc function is available, SDL simply forwards the call to the libc function; however, when the libc function is unavailable, SDL provides its own custom implementation.

The problem is that SDL's homemade implementations do not always match the behavior of the corresponding libc function, and its unclear whether these differences are bugs or intended.

For example, the homemade implementation of `SDL_strtol` does not handle uppercase `0X` prefixed numbers, octal numbers or base 36 numbers in the same way as libc `strtol`:

1\. Comment out `#cmakedefine HAVE_STRTOL 1` in `SDL_build_config.h.cmake` to make the build process act as if `strtol` is missing from the libc, forcing SDL to use its homemade implementation.

2\. Build SDL using CMake.

3\. Compile and run the following program:
```c
#include <stdlib.h>
#include <stdio.h>
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

int main(int argc, char **argv) {
    long parsed;

    parsed = SDL_strtol("0X123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = strtol("0X123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = SDL_strtol("0123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = strtol("0123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = SDL_strtol("xyz", NULL, 36);
    printf("%ld\n", parsed);

    parsed = strtol("xyz", NULL, 36);
    printf("%ld\n", parsed);

    return 0;
}
```
4. It outputs
```
0
291
123
83
0
44027
```
demonstrating the difference in behavior between SDL and libc.

Now, the vast majority of all built SDL libraries floating around in the wild are likely to have been compiled against a libc that provide the functions, so this is probably not an huge in practice since the homemade SDL implementations are almost never used.

But the discrepancy does make it more difficult to document some of the APIs listed in `SDL_stdinc.h`, since it's not clear which differences in behavior are intentional and which are bugs, making it difficult for users to make assumptions about the expected behavior. Most importantly, if a difference is intentional, the documentation should clearly state what behavior the user should expect, and if it's a bug, it should probably be fixed.

**Comment by slouken** [comment]
Octal numbers and other bases are not supported, and can be documented, though we can add those as needed. Not supporting upper case 0X is a bug, and will be fixed.

**Comment by slouken** [comment]
Although, realistically if those are easy to add, feel free to submit a PR with testautomation coverage and improved implementation.

**Comment by castholm** [comment]
Another example of an API that is unclear is `SDL_strtod`. Is only decimal notation supposed to be supported (i.e. no scientific or hexadecimal notation)? Should it support `"NAN"` or `"INF"`? `SDL_ScanFloat` divides the intermediate result by 10 in a loop, so is the precision of the rounding of the result intentionally unspecified?

**Comment by slouken** [comment]
> Another example of an API that is unclear is `SDL_strtod`. Is only decimal notation supposed to be supported (i.e. no scientific or hexadecimal notation)? Should it support `"NAN"` or `"INF"`? `SDL_ScanFloat` divides the intermediate result by 10 in a loop, so is the precision of the rounding of the result intentionally unspecified?

Only decimal notation is supported, NAN and INF or not, rounding is unspecified. Again, if any of these are an issue, they can be fixed, they just haven't come up in practice.
