### ISSUE TITLE
SDL3: Since recently it seems that a newly created texture is not initialised anymore

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10755]
Since recently I am getting a pink screen with my application. The texture that is rendered in the background is not filled with anything during startup. In the past that texture just stayed black until I filled it with data. Now it seems to start pink.
<img width="1232" alt="pink" src="https://github.com/user-attachments/assets/b58fb87c-bac9-41f0-8fe0-b87a8d70eca8">

**Comment by madebr** [comment]
What pixelformat are you using?
Does it happen with all renderers? vulkan, opengl, metal, gpu, ...

**Comment by andreasgrabher** [comment]
I am using SDL_PIXELFORMAT_BGRA32 (on little endian host). The renderer is whatever it is set by default and I don't know how to change it. It is with SDL3. I am on a Mac mini M1 with latest OS.

**Comment by andreasgrabher** [comment]
Found out how to change it. Renderer that causes the pink screen is gpu. Metal and opengl are still fine (black background on start).

**Comment by madebr** [comment]
With the `SDL_HINT_GPU_DRIVER` hint (`SDL_GPU_DRIVER` environment variable), you can choose the gpu backend.
On macos, I think the variable can be `metal`, `vulkan`, or `opengl`.

cc @thatcosmonaut

**Comment by slouken** [comment]
The contents of new textures aren't defined. I clarified this in the documentation. Once you create a texture, you should initialize it with the pixels you want in the texture.

**Comment by madebr** [comment]
So surfaces are initialized, but textures aren't?

**Comment by slouken** [comment]
> So surfaces are initialized, but textures aren't?

Yes, that's correct.
