### ISSUE TITLE
GPU: D3D12 backend log spam when clearing depth buffer to nonzero value

### ISSUE THREAD

**Issue by vfig** [libsdl-org/SDL#10758]
i am using SDL3 GPU. in my render pass's `SDL_GPUDepthStencilTargetInfo`, i set `.clear_value.depth = 1.0f`. this results in the following warning spamming the output log every frame:

```
D3D12 WARNING: ID3D12CommandList::ClearDepthStencilView: The clear values do not match those passed to resource creation. The clear operation is typically slower as a result; but will still clear to the desired value. [ EXECUTION WARNING #821: CLEARDEPTHSTENCILVIEW_MISMATCHINGCLEARVALUE]
```

this happens because in [SDL_gpu_d3d](https://github.com/libsdl-org/SDL/blob/7df1caba7cf5d7659f901614c8bd059d1fe84990/src/gpu/d3d12/SDL_gpu_d3d12.c#L2735) the depth value on creation defaults to zero.

i can work around this by creating a property group for the depth texture and setting `SDL_PROP_GPU_CREATETEXTURE_D3D12_CLEAR_DEPTH_FLOAT` in it to 1.0f, so that the on-creation depth and the clear depth match, preventing the warning.

it is annoying to have to add platform-specific code for such a small thing; but the presence of the log spam is worse because it makes messages about more significant problems harder to see.

is there a way to prevent it without using the property group workaround above? should i be doing something different?

(using SDL3 main @ d972436d23d1cc7de9f6e06dc5cf94a0cfd71926)

**Comment by thatcosmonaut** [comment]
This is Microsoft's boneheaded design and the warning comes straight from their validator layer. I'm not sure what we can do beyond suppressing this specific message. I agree that this is very stupid and annoying.

**Comment by slouken** [comment]
Should we default the value to 1.0f if it's not specified?

**Comment by thatcosmonaut** [comment]
It's not a bad idea but this warning applies to color clears too. I'm not sure why Microsoft decided to design clears this way or emit a warning on every single clear usage but here we are.

**Comment by vfig** [comment]
i am not getting any warning for the color clear (i am clearing to magenta). havent yet checked for stencil clears.

doesnt matter much whether the default on creation is 0.0f or 1.0f — using reversed z is common too, so cant win either way.

in any case, the props workaround is adequate. probably just deserves a footnote in the docs somewhere. i will submit a patch for that.

**Comment by vfig** [comment]
ok, ive added a brief discussion of this to the wiki under [SDL_BeginGPURenderPass](https://wiki.libsdl.org/SDL3/SDL_BeginGPURenderPass), as i guess that is where the warnings will be seen to be "coming from", even though the properties do actually belong with [SDL_GPUTextureCreateInfo](https://wiki.libsdl.org/SDL3/SDL_GPUTextureCreateInfo).

https://github.com/libsdl-org/sdlwiki/pull/591
