### ISSUE TITLE
SDL2 Window not appearing on RockyLinux9

### ISSUE THREAD

**Issue by swilkesaustin** [libsdl-org/SDL#10760]
Hi! I'm' new to GitHub and not sure what information is needed, so please kindly excuse my noob-ness. 
I'm trying to write a simple game with C++ in vs code on RockyLinux 9.
Following the book Game Programming in C++ by Sanjay Madhav, I have fought my way thru compiler and linker options to get SDL2 to compile, link, and to successfully execute SDL_Init() and SDL_CreateWindow with no warnings & no errors, but nothing new appears on my screen. 

I'm not using CMAKE to compile the code, just using linker options in tasks.json in vs code. It has been a battle just to get the linker ld to find the SDL2 object files. 

I see references to Wayland in the various forums that are making me think this may be a problem with Wayland -- I really didn't anticipate SDL2 might have a problem with the windowing architecture as surely Wayland supports SDL2, but maybe I'm wrong? Do I just need to add a some linker/compile options to my settings? 

At same time, wondering if I'm trying to use way too bleeding-edge corner-case distro for this effort. Maybe Ubuntu 22.04 would be better suited for a newbie just learning SDL2. Or should I upgrade to SDL3? 

Please advise. 

```
typedef double dbl;
typedef std::string str;

const str myGameName = "SpaceShipSim", myGameVersion = "0.0.3";
int PlayGame(void);

// main function with SDL code
int main(void) {
    std::cout << "Hi! My name is "<<  myGameName << " v" << myGameVersion << "!!!\n\n";

    int sdlResult = SDL_Init(SDL_INIT_VIDEO);
    if (sdlResult != 0) { 
        std::cout << "Unable to initialize SDL\n";
        SDL_Log("Unable to initialize SDL: %s", SDL_GetError());
        exit(-9);
    } else {
        std::cout << "Successfully initialized SDL\n";
    }

    myGameWindow = SDL_CreateWindow(
        myGameName.c_str(), // window title
        SDL_WINDOWPOS_UNDEFINED,    // top left x-coor of window
        SDL_WINDOWPOS_UNDEFINED,     // top left Y-coor of window
        1024,   // width of window
        768,    // height of window
        SDL_WINDOW_OPENGL | SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_ALWAYS_ON_TOP
    );
    if (!myGameWindow) {
        std::cout << "Unable to create myGameWindow\n";
        SDL_Log("Unable to create myGameWindow: %s", SDL_GetError());
        exit(-8);
    } else {
        std::cout << "Successfully created myGameWindow\n";
    }

    char c;
    while (myGameStatus == gamestatusRUN) {
        std::cout << "Enter q to quit, g for game: " ;
        std::cin >> c;
        if (c == 'q') myGameStatus = gamestatusSTOP; 
        if (c == 'g') PlayGame();  // just executes a 'tostr' function for a couple of objects that sends data to std::cout, 
                                                 // no interaction with game window yet
    }

    SDL_DestroyWindow(myGameWindow);
    SDL_Quit();

    std::cout << "Bye!!\n\n";

    return 0;
}

```

**Comment by madebr** [comment]
For beginners, it's easier to use the SDL2 prebuilt packages provided by your Linux distribution.
In RockyLinux's case: `libSDL2-devel`

If you insist building SDL2 from source, make sure to install SDL2's dependencies.
https://github.com/libsdl-org/SDL/blob/SDL2/docs/README-linux.md#build-dependencies
(You need to install the rockylinux equivalents of these)

**Comment by Kontrabant** [comment]
Debugging-wise, you can call `SDL_GetVideoDriver()` after initializing the video system to see what backend it is using.  If the returned string is "dummy" or "offscreen", it means you didn't have the required prerequisites for building the X11 and/or Wayland backends, which are needed to actually show a window on *nix platforms.

**Comment by slouken** [comment]
If you're using Wayland, you also need to poll for events. Discourse is a great place to ask for help:
https://discourse.libsdl.org/c/sdl-development/6

**Comment by swilkesaustin** [comment]
> For beginners, it's easier to use the SDL2 prebuilt packages provided by your Linux distribution. In RockyLinux's case: `libSDL2-devel`
> 
> If you insist building SDL2 from source, make sure to install SDL2's dependencies. https://github.com/libsdl-org/SDL/blob/SDL2/docs/README-linux.md#build-dependencies (I think rockylinux is very similar to Fedora)

not building from source, i ran 'sudo dnf install libSDL2-devel'... took me forever to figure where it put everything....

**Comment by swilkesaustin** [comment]
> Debugging-wise, you can call `SDL_GetVideoDriver()` after initializing the video system to see what backend it is using. If the returned string is "dummy" or "offscreen", it means you didn't have the required prerequisites for building the X11 and/or Wayland backends, which are needed to actually show a window on *nix platforms.

do you mean 'SDL_GetCurrentVideoDriver'???

**Comment by swilkesaustin** [comment]
```
    str mySDL2VideoDriver = SDL_GetCurrentVideoDriver();
    std::cout << "current video driver: " << mySDL2VideoDriver << "\n";

```
yields: 
current video driver: wayland

**Comment by swilkesaustin** [comment]
Ahhhhhh success! this link helped: https://jan.newmarch.name/Wayland/SDL/. it turns out that i needed to have a flag "SDL_WINDOW_SHOWN" in my SDL_CreateWindow convocation. Thanks so much for your help, y'all!
