### ISSUE TITLE
Omitting multisample_state in SDL_GPUGraphicsPipelineCreateInfo will mask with 0x00

### ISSUE THREAD

**Issue by hsjunnesson** [libsdl-org/SDL#10766]
Using sdl gpu, on Vulkan, I setup a simple graphics pipeline for some shadertoy style  signed distance field rendering.

```
SDL_GPUGraphicsPipelineCreateInfo pipeline_desc = {
	.target_info = {
		.num_color_targets = 1,
		.color_target_descriptions = &color_target_desc,
	},
	.primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST,
	.vertex_shader = vertex_shader,
	.fragment_shader = fragment_shader,
};
```

If I ommitt the `multisample_state` I get a black screen, because its `sample_count` and `sample_mask` are zeroed. I have to add this:

```
.multisample_state = {
	.sample_count = 0,
	.sample_mask = 0xf,
},
```

I'm not entirely sure this is a bug, so feel free to close. I think it's more of a question of where to draw the line. There's a gradient here of how much SDL is meant to help you out with reasonable defaults and vulkan's API being brutally explicit and verbose.

**Comment by thatcosmonaut** [comment]
Because of things like this our plan is to provide initializer functions that return reasonable defaults for these creation structs.

**Comment by thatcosmonaut** [comment]
#10703

**Comment by hsjunnesson** [comment]
Good stuff, I'm closing this.
