### ISSUE TITLE
GPU: Functions that may return errors should call SDL_SetError()

### ISSUE THREAD

**Issue by Akaricchi** [libsdl-org/SDL#10779]
Currently most (all?) of the error reporting is done through the SDL log, and APIs that may fail (e.g. `SDL_CreateGPUDevice`) do not call `SDL_SetError()`. This makes it impossible to, for example, display a message box with the failure reason.

**Comment by slouken** [comment]
The log calls should generally be switched to SDL_SetError()

**Comment by thatcosmonaut** [comment]
Error setting is reasonable on things like creation functions, where we return NULL if the creation failed, and we should do that. Error setting on hot-path commands will just be futile - those functions shouldn't return anything but void and nobody can check them for errors without turning their client code into an absolute mess.

**Comment by slouken** [comment]
We should probably have a similar policy with the SDL render API, and possibly add a debug layer there. @icculus, thoughts?

**Comment by icculus** [comment]
I think the render layer is okay as-is: it uses SDL_SetError where reasonable and doesn't need a debug layer because there isn't really much you can do with it that's a surprising silent failure, unlike using OpenGL directly.

**Comment by thatcosmonaut** [comment]
We decided that anything where the underlying APIs return error codes is something we should bubble up into GPU, anything else is probably unrecoverable or we can catch obvious failures with debug mode validations.

**Comment by thatcosmonaut** [comment]
Resolved by 557c6dfb1813e05f259f479cc9b4ced9a7ed471b

**Comment by slouken** [comment]
Not yet resolved, see comments.

**Comment by thatcosmonaut** [comment]
Maybe actually resolved by https://github.com/libsdl-org/SDL/commit/925e47a077fb7103831cce147b3751ba689d4170 ?

**Comment by thatcosmonaut** [comment]
@slouken If it's OK to call LogError and SetError I'll go ahead and just do that, but isn't it a bit redundant with SDL_LOG_PRIORITY_DEBUG?

**Comment by slouken** [comment]
I'm thinking something like this:
```c
SDL_SetError(...);
if (debug) {
    SDL_LogError(SDL_LOG_CATEGORY_GPU, ...);
}
```
Setting an error doesn't automatically log, and having an error in the GPU log category means that the application can filter it appropriately.

As an aside, we should have a hint that forces debug on so users can enable debug validation and error printing from the environment.

**Comment by thatcosmonaut** [comment]
That seems alright to me, but I do worry that not logging errors at all if debug mode is off might cause difficulties for clients if errors come up in deployment.

**Comment by slouken** [comment]
> That seems alright to me, but I do worry that not logging errors at all if debug mode is off might cause difficulties for clients if errors come up in deployment.

That's what the hint is for. "Just set this environment variable (or enable the "Debug GPU option") and send me the debug output"

**Comment by thatcosmonaut** [comment]
Alright, I'm going to revise the functions further tomorrow, we need to restructure some of them to cleanly return errors.
