### ISSUE TITLE
SDL3 SDL_malloc.c #define FORCEINLINE problem

### ISSUE THREAD

**Issue by Windings-Lab** [libsdl-org/SDL#10772]
Environment:
MSVC v143 x64/x86 latest based on Visual Studio 17.11.2
Windows 11 SDK (10.0.26100.0)
!!!! Using CLang Compiler will not reproduce this error !!!!

Using
commit id - 8371114009f103f629664664eee8f5dbdcb10f3d
commit message - Fixed error: multiple storage classes in declaration specifiers

Fix of the problem:
src/stdlib/SDL_malloc.c - comment #define FORCEINLINE
![image](https://github.com/user-attachments/assets/5ebdc4db-3b3a-4b3e-8532-80b38bbddc18)

CMakeLists.txt
CMAKE_BUILD_TYPE=Debug
```
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_SCAN_FOR_MODULES ON)

add_executable(WD_SDL main.cpp)

set(compiler_is_msvc "$<CXX_COMPILER_ID:MSVC>")
target_compile_options(WD_SDL PRIVATE
	$<${compiler_is_msvc}:
		  /std:c++latest
		  /Zc:preprocessor
		  /utf-8
		  /EHsc
		  /nologo
		  /UNICODE
		  /FAs
		  $<$<CONFIG:Release>:
			/Ox
			/MD
		  >
		  $<$<CONFIG:Debug>:
			/MDd
		  >
	 >
)

target_compile_features(WD_SDL PRIVATE cxx_std_23)

add_subdirectory(vendor)
```
vendor/CMakeLists.txt
```
target_compile_definitions(WD_SDL PUBLIC
    SDL_MAIN_USE_CALLBACKS
)

add_subdirectory(SDL EXCLUDE_FROM_ALL)
add_subdirectory(SDL_image EXCLUDE_FROM_ALL)

target_link_libraries(WD_SDL PUBLIC SDL3-static)
```

Error by a linker
```
MSVCRTD.lib(guard_support.obj) : error LNK2005: ReadNoFence64 already defined in SDL3-static.lib(SDL_malloc.c.obj)
MSVCRTD.lib(guard_support.obj) : error LNK2005: ReadPointerNoFence already defined in SDL3-static.lib(SDL_malloc.c.obj)
SDL3-static.lib(SDL_malloc.c.obj) : error LNK2019: unresolved external symbol RtlSetVolatileMemory referenced in function RtlFillVolatileMemory
SDL3-static.lib(SDL_malloc.c.obj) : error LNK2019: unresolved external symbol __imp_MapViewOfFileNuma2 referenced in function MapViewOfFile2
```

**Comment by madebr** [comment]
How come `HAVE_MALLOC` is false on your system?
https://github.com/libsdl-org/SDL/blob/47283250442a15de423d3bf4368f914105c6364f/CMakeLists.txt#L920-L921
What does the log say in `CMakeFiles/CMakeConfigureLog.yaml`?

**Comment by Windings-Lab** [comment]
Forgot to mention. I have those variables
```
        "SDL_STATIC": "ON",
        "SDL_SHARED": "OFF",
        "SDL_HIDAPI_LIBUSB": "OFF",
        "SDL_DUMMYVIDEO": "OFF",
        "SDL_HIDAPI_LIBUSB_SHARED": "OFF",
        "SDL_DIRECTX": "OFF",
        "SDL_VULKAN": "OFF",
        "SDL_HIDAPI": "OFF",
        "SDL_AVX": "OFF",
        "SDL_ASSEMBLY": "OFF",
        "SDL_POWER": "OFF",
        "SDL_LIBUDEV": "OFF",
        "SDL_VIRTUAL_JOYSTICK": "OFF",
        "SDL_OFFSCREEN": "OFF",
        "SDL_XINPUT": "OFF",
        "SDL_VIDEO": "ON",
        "SDL_GCC_ATOMICS": "OFF",
        "SDL_CAMERA": "OFF",
        "SDL_HAPTIC": "OFF",
        "SDL_JOYSTICK": "OFF",
        "SDL_TEST_LIBRARY": "OFF",
        "SDL_HIDAPI_JOYSTICK": "OFF",
        "SDL_SENSOR": "OFF",
        "SDL_DISABLE_INSTALL": "ON",
        "SDL_AVX2": "OFF",
        "SDL_AUDIO": "OFF",
        "SDL_AVX512F": "OFF",
        "SDL_LIBC": "OFF",
        "SDL_RENDER_METAL": "OFF",
        "SDL_RENDER": "OFF",
        "SDL_DIALOG": "OFF"
```
Here's a CmakeConfigureLog
[CMakeConfigureLog.txt](https://github.com/user-attachments/files/16932823/CMakeConfigureLog.txt)

**Comment by Windings-Lab** [comment]
> How come [`HAVE_MALLOC` is not defined](https://github.com/libsdl-org/SDL/blob/47283250442a15de423d3bf4368f914105c6364f/src/stdlib/SDL_malloc.c#L25) on your system?

I don't know. I recently fully reinstalled Windows 11. Installed Visual Studio Build Tools and used SDL3 for 1-2 month already until I've got this error. CLang is from MSYS2 MINGW64. With this toolchain is working fine

**Comment by Windings-Lab** [comment]
Okay. Found what's happening then. It can find malloc.h. But it using another variable to check if it's enabled? Or I don't understand
![image](https://github.com/user-attachments/assets/e046983c-bb98-4ef3-af05-54f4a47e7fc9)

**Comment by Windings-Lab** [comment]
Don't you need to use `target_compile_definitions` to define `HAVE_MALLOC`?

**Comment by madebr** [comment]
> Don't you need to use `target_compile_definitions` to define `HAVE_MALLOC`?

At the end of the configuration, a header is generated.
Something like `include-config-debug/build_config/SDL_build_config.h`.
If we would use compile definitions, the command would become very long and unreadable.

**Comment by Windings-Lab** [comment]
![image](https://github.com/user-attachments/assets/26663098-0a93-42f9-9e79-582f709c9a92)
SDL_build_config.h.intermediate has #define HAVE_MALLOC 1

Looking into other issue

**Comment by Windings-Lab** [comment]
Found it. Yeah. Thanks for the hints @madebr 
I disabled `"SDL_LIBC": "OFF"` in a preset causing this:
![image](https://github.com/user-attachments/assets/4a6e8bd1-c6c1-4b8c-8a9d-66ffe30f09dd)
