### ISSUE TITLE
Change SDL_GPU_TEXTUREFORMAT_INVALID to SDL_GPU_TEXTUREFORMAT_UNKNOWN = 0?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#10784]
This is more consistent with SDL pixel format and makes it easier to use zero-initialized structures.

**Comment by thatcosmonaut** [comment]
Upon reflection I'm in favor of this. Related to this: https://github.com/libsdl-org/SDL/issues/10785

**Comment by thatcosmonaut** [comment]
Resolved by https://github.com/libsdl-org/SDL/pull/10786
