### ISSUE TITLE
SDL_WINDOWEVENT_EXPOSED not triggered on sway

### ISSUE THREAD

**Issue by rom1v** [libsdl-org/SDL#10782]
On all others "platforms", when a window is opened and made visible, SDL sends both `SDL_WINDOWEVENT_SHOWN` and `SDL_WINDOWEVENT_EXPOSED`.

But on sway, `SDL_WINDOWEVENT_EXPOSED` is never sent.

Is it expected or is it a bug in SDL?

Refs https://github.com/Genymobile/scrcpy/pull/5280

**Comment by Kontrabant** [comment]
Indeed, the SDL2 Wayland backend wasn't sending exposure events in every case where the client should redraw (this was already fixed in SDL3). Should be fixed now.

**Comment by Kontrabant** [comment]
Backporting to stable as well.

**Comment by rom1v** [comment]
Thank you very much :rocket:
