### ISSUE TITLE
Undefined symbols in project after trying to link SDL2 statically

### ISSUE THREAD

**Issue by Lester702** [libsdl-org/SDL#10799]
Hello, I am trying to move my own library to a dll and in the process I have been trying to use SDL2 statically. I downloaded the source for 2.30.7 and built it with cmake and compiled the static library with VS 2022. When I try and link against the newly created static library I get 42 unresolved external symbols coming from the static sdl library file. I made sure to update the SDL header files in my project as well. Any idea what I could have missed or done wrong?

`1>SDL2-static.lib(SDL_systimer.obj) : error LNK2019: unresolved external symbol __imp_timeBeginPeriod referenced in function SDL_TimerResolutionChanged`
`1>SDL2-static.lib(SDL_systimer.obj) : error LNK2019: unresolved external symbol __imp_timeEndPeriod referenced in function SDL_TicksQuit`
`1>SDL2-static.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp_SetupDiEnumDeviceInfo referenced in function PLATFORM_hid_enumerate`
`1>SDL2-static.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp_SetupDiDestroyDeviceInfoList referenced in function PLATFORM_hid_enumerate`
`1>SDL2-static.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp_SetupDiEnumDeviceInterfaces referenced in function PLATFORM_hid_enumerate`
`1>SDL2-static.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp_SetupDiGetDeviceInterfaceDetailA referenced in function PLATFORM_hid_enumerate`
`1>SDL2-static.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp_SetupDiGetClassDevsA referenced in function PLATFORM_hid_enumerate`
`1>SDL2-static.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp_SetupDiGetDeviceRegistryPropertyA referenced in function PLATFORM_hid_enumerate`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoSizeA referenced in function IME_GetId`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoA referenced in function IME_GetId`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol VerQueryValueA referenced in function IME_GetId`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmGetIMEFileNameA referenced in function IME_GetId`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmGetContext referenced in function IME_ClearComposition`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmReleaseContext referenced in function IME_ClearComposition`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmAssociateContext referenced in function IME_Disable`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmGetCompositionStringW referenced in function IME_GetCompositionString`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmSetCompositionStringW referenced in function IME_ClearComposition`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmGetCandidateListW referenced in function IME_GetCandidateList`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmNotifyIME referenced in function IME_ClearComposition`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmSetCompositionWindow referenced in function WIN_SetTextInputRect`
`1>SDL2-static.lib(SDL_windowskeyboard.obj) : error LNK2019: unresolved external symbol ImmSetCandidateWindow referenced in function WIN_SetTextInputRect`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutGetNumDevs referenced in function WINMM_DetectDevices`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutGetDevCapsW referenced in function WINMM_DetectDevices`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutGetErrorTextW referenced in function SetMMerror`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutOpen referenced in function WINMM_OpenDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutClose referenced in function WINMM_CloseDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutPrepareHeader referenced in function WINMM_OpenDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutUnprepareHeader referenced in function WINMM_CloseDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutWrite referenced in function WINMM_PlayDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutReset referenced in function WINMM_CloseDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInGetNumDevs referenced in function WINMM_DetectDevices`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInGetDevCapsW referenced in function WINMM_DetectDevices`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInOpen referenced in function WINMM_OpenDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInClose referenced in function WINMM_CloseDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInPrepareHeader referenced in function WINMM_OpenDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInUnprepareHeader referenced in function WINMM_CloseDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInAddBuffer referenced in function WINMM_CaptureFromDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInStart referenced in function WINMM_OpenDevice`
`1>SDL2-static.lib(SDL_winmm.obj) : error LNK2019: unresolved external symbol __imp_waveInReset referenced in function WINMM_CloseDevice`
`1>SDL2-static.lib(SDL_windows_gaming_input.obj) : error LNK2019: unresolved external symbol __imp_CM_Get_Device_IDA referenced in function SDL_IsXInputDevice`
`1>SDL2-static.lib(SDL_windows_gaming_input.obj) : error LNK2019: unresolved external symbol __imp_CM_Get_Parent referenced in function SDL_IsXInputDevice`
`1>SDL2-static.lib(SDL_windows_gaming_input.obj) : error LNK2019: unresolved external symbol __imp_CM_Locate_DevNodeA referenced in function SDL_IsXInputDevice`

**Comment by madebr** [comment]
SDL makes use of the win32 api, so it needs to link against libraries of the Windows SDK (usually installed by Visual Studio).

When using SDL2 in your (cmake) project with a pre-built SDL2, we suggest using [the template found in our docs](https://github.com/libsdl-org/SDL/blob/SDL2/docs/README-cmake.md#including-sdl-in-your-project).

In your case, it should look like:
```cmake
find_package(SDL2 REQUIRED CONFIG COMPONENTS SDL2-static)
target_link_libraries(yourgame PRIVATE SDL2::SDL2main SDL2::SDL2-static)
```
Configure the project with `-DCMAKE_PREFIX_PATH=/path/to/installed/SDL2`.

**Comment by Lester702** [comment]
My game is using Visual Studio not cmake, sorry for the confusion. I just used cmake to setup the project so I can build SDL. I managed to get a lot of the LNK2019 errors figured out after some continued digging. This is where I am currently stuck.

![image](https://github.com/user-attachments/assets/803f11cc-c19f-43fe-8fb1-52d0f2679fd2)

**Comment by madebr** [comment]
There's not an easy way to do this automatically with Visual Studio (MSBuild).
When configuring SDL2's cmake project, the configuration process should print something as following:
```
--  EXTRA_LIBS:    kernel32;user32;gdi32;winmm;imm32;ole32;oleaut32;version;uuid;advapi32;setupapi;shell32;dinput8
```
By adding a `.lib` suffix to all, you can add these after `SDL2-static.lib` in your VS project.
```
SDL2-static.lib;kernel32.lib;user32.lib;gdi32.lib;winmm.lib;imm32.lib;ole32.lib;oleaut32.lib;version.lib;uuid.lib;advapi32.lib;setupapi.lib;shell32.lib;dinput8.lib
```

**Comment by slouken** [comment]
I highly recommend dynamic linking with SDL so customers can drop in updated DLLs with improvements and bug fixes in the future.
