### ISSUE TITLE
GPU shader format bit flags skip value 1

### ISSUE THREAD

**Issue by zturtleman** [libsdl-org/SDL#10797]
The bit shifts for the GPU shader format bit flags could all be decreased by 1 to start at value 1 (`1<<0`) instead of 2 (`1<<1`). I wouldn't expect it makes a functional difference either way but I haven't tested this change.

https://github.com/libsdl-org/SDL/blob/77c569496df90526641cdede56feeb263be0b7b6/include/SDL3/SDL_gpu.h#L589-L595

**Comment by thatcosmonaut** [comment]
I messed this up when I added the INVALID entry. Will fix.
