### ISSUE TITLE
Vcpkg Port Question

### ISSUE THREAD

**Issue by Honeybunch** [libsdl-org/SDL#10792]
Hi! Are SDL maintainers cool with vcpkg publishing an SDL3 pre-release port? 

See https://github.com/microsoft/vcpkg/pull/40867

**Comment by icculus** [comment]
At this point, I'd say please wait until the ABI lockdown, which is coming soon.

After that, we might add stuff but we will not change or remove existing stuff, so people will be able to update a package without their code breaking.

**Comment by BillyONeal** [comment]
vcpkg distributes sources, not binaries, and we assume most of the things we distribute are not ABI stable, so it should be safe to add a port with us without having ABI stability locked down. However, we will not merge a package until you / upstream are happy with us doing that.

Thanks @Honeybunch for the port and filing this issue and @icculus for your time :)

**Comment by slouken** [comment]
We have an API preview release coming soon, and that's a good time to add a vcpkg port.

**Comment by icculus** [comment]
I believe we're going to ABI lock tomorrow, so while we aren't yet at an official release, it will be safe to package SDL3 knowing that what's there won't be removed or changed (although we _will_  add more things).

We'll comment here again when it happens, but we're probably hours away now, not days.

**Comment by m6502** [comment]
These are good news. I know of about 40 students who will start using it next week then :-) Thanks for your work!

**Comment by icculus** [comment]
We are live! 

https://github.com/libsdl-org/SDL/releases/tag/preview-3.1.3

Feel free to package it!
