### ISSUE TITLE
blit_testExampleApplicationRender failing on big-endian

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#10794]
In SDL3 snapshot b1b4a9c (2024-09-03), which happens to be the newest version that I uploaded to Debian experimental, the tests pass on little-endian architectures (x86, ARM, etc.) but fail on big-endian (powerpc, s390x, etc.):

```
 09/04/24 10:39:59: [0;93m----- Test Case 25.1: 'blit_testExampleApplicationRender' started[0m
 09/04/24 10:39:59: Test Description: 'Test example application render.'
 09/04/24 10:39:59: Test Iteration 1: execKey 2055346379974795709
ERROR: 09/04/24 10:39:59: Assert 'Should render identically, expected hash 0xe345d7a7, got 0x4611709e': [0;31mFailed[0m
ERROR: 09/04/24 10:39:59: Assert Summary: Total=1 [0;32mPassed=0[0m [0;31mFailed=1[0m
```

I don't know whether this is an incorrect endianness in the test itself, or in the code under test.

I'm not intending to make this a high priority and I don't think it's a 3.2.0 blocker, because everything that would be reasonable to play games on is little-endian anyway, with the possible exception of some niche modern PowerPC machines, older-generation games consoles and older Apple machines; but if a big-endian-architecture enthusiast can fix it then so much the better.

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/e159bcf5ded370b78078e6ef66832fbb55e674f4
