### ISSUE TITLE
Guard against thread creation failure in PULSEAUDIO_DetectDevices

### ISSUE THREAD

**Issue by jessey-git** [libsdl-org/SDL#10806]
Blender encountered a hang in certain build configurations with SDL and it was graciously root caused by a volunteer on our side to an issue inside `PULSEAUDIO_DetectDevices`. I've linked their original analysis below [1], but here is a summary:

- During app startup SDL attempts to create its `pulseaudio_hotplug_thread` inside `PULSEAUDIO_DetectDevices`, but this fails
- Nothing checks this creation failure and SDL keeps waiting on its `ready_sem` which will never be set, leading to an app hang (This Bug)
- Thread creation fails because the stack size used for the thread is too small (256kb). There's a large dependency in Blender that has various large structures kept on the stack and as TLS (to the tune of ~280kb). SDL may need to at least consider using a larger stack for the threads it creates. The dependency is OpenUSD but an issue on their side has not been filed yet for them to at least consider reducing their stack usage in some way.

[1] https://projects.blender.org/blender/blender/issues/126661#issuecomment-1291337

**Comment by slouken** [comment]
@smcv, this is related to your other audio hardening work

**Comment by smcv** [comment]
> @smcv, this is related to your other audio hardening work

Only vaguely, I think - I was looking at scenarios where an audio library can be unloaded while a background thread is still trying to run it. This is sort of the opposite: we were hoping a background thread would run audio library code, but actually it never started.

**Comment by icculus** [comment]
I think we removed the obscenely low stack size in SDL3; I'll take this one.

**Comment by icculus** [comment]
> I think we removed the obscenely low stack size in SDL3; I'll take this one.

Nope, I lied, it's still there. I'll just let it choose the default.

**Comment by icculus** [comment]
Fixed in b7dc30ca24650a22de61c0c4ab28f7cb5905dee9 for SDL3 and 58f2586b4463b5b7e637b9b54798b4d6f0375c51 for SDL2.

**Comment by icculus** [comment]
(Also I just want to say that I'm not sure why Thread Local Storage would cause this, as Linux TLS is not stored on the stack, afaik, but I don't know the technical details of any of this.)
