### ISSUE TITLE
I would love a SDL_GPU_DISABLED if possible, please.

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#10813]
I would love a SDL_GPU_DISABLED if possible, please. It's the only way that I know that works for me to disable subsystems per-project.

_Originally posted by @AntTheAlchemist in https://github.com/libsdl-org/SDL/issues/10715#issuecomment-2347417689_

**Comment by slouken** [comment]
This should enable stub versions of the API that return SDL_Unsupported()

**Comment by AntTheAlchemist** [comment]
Thanks for this, but I get the following errors when using it:

```
SDL_gpu.c(552,12): error C2065: 'backends': undeclared identifier
SDL_gpu.c(552,12): error C2109: subscript requires array or pointer type
SDL_gpu.c(552,5): warning C4033: 'SDL_GetNumGPUDrivers_REAL' must return a value
SDL_gpu.c(561,12): error C2065: 'backends': undeclared identifier
SDL_gpu.c(561,20): error C2109: subscript requires array or pointer type
SDL_gpu.c(561,5): warning C4033: 'SDL_GetGPUDriver_REAL' must return a value
```

**Comment by AntTheAlchemist** [comment]
Also, `SDL_GPU_DISABLED` should be applied to all the platform-dependant build_config files? Otherwise the GPU defines are still enabled and built.

**Comment by AntTheAlchemist** [comment]
... the binaries have jumped massively in size since adding the GPU sub-system, even if it's not used.

**Comment by sezero** [comment]
Easy fix below. @AntTheAlchemist: Can you confirm? @slouken: OK to apply?

```diff
diff --git a/src/gpu/SDL_gpu.c b/src/gpu/SDL_gpu.c
index 0b07ff8..67e2079 100644
--- a/src/gpu/SDL_gpu.c
+++ b/src/gpu/SDL_gpu.c
@@ -150,7 +150,6 @@
 
 // Drivers
 
-#ifndef SDL_GPU_DISABLED
 static const SDL_GPUBootstrap *backends[] = {
 #ifdef SDL_GPU_METAL
     &MetalDriver,
@@ -166,7 +165,6 @@ static const SDL_GPUBootstrap *backends[] = {
 #endif
     NULL
 };
-#endif // SDL_GPU_DISABLED
 
 // Internal Utility Functions
 
```

**Comment by sezero** [comment]
> Easy fix below. @AntTheAlchemist: Can you confirm? @slouken: OK to apply?

More complete patch:

```diff
diff --git a/src/gpu/SDL_gpu.c b/src/gpu/SDL_gpu.c
index 0b07ff8..b458894 100644
--- a/src/gpu/SDL_gpu.c
+++ b/src/gpu/SDL_gpu.c
@@ -150,7 +150,6 @@
 
 // Drivers
 
-#ifndef SDL_GPU_DISABLED
 static const SDL_GPUBootstrap *backends[] = {
 #ifdef SDL_GPU_METAL
     &MetalDriver,
@@ -166,7 +165,6 @@ static const SDL_GPUBootstrap *backends[] = {
 #endif
     NULL
 };
-#endif // SDL_GPU_DISABLED
 
 // Internal Utility Functions
 
@@ -438,7 +436,6 @@ static const SDL_GPUBootstrap * SDL_GPUSelectBackend(SDL_PropertiesID props)
     SDL_LogError(SDL_LOG_CATEGORY_GPU, "No supported SDL_GPU backend found!");
     return NULL;
 }
-#endif // SDL_GPU_DISABLED
 
 static void SDL_GPU_FillProperties(
     SDL_PropertiesID props,
@@ -467,6 +464,7 @@ static void SDL_GPU_FillProperties(
     SDL_SetBooleanProperty(props, SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOL, debug_mode);
     SDL_SetStringProperty(props, SDL_PROP_GPU_DEVICE_CREATE_NAME_STRING, name);
 }
+#endif // SDL_GPU_DISABLED
 
 SDL_bool SDL_GPUSupportsShaderFormats(
     SDL_GPUShaderFormat format_flags,
```

**Comment by AntTheAlchemist** [comment]
@sezero shifting the `SDL_GPU_DISABLED` inside the backends array is fine. 

But I just noticed the `#undef`s in SDL_internal.h (I'm still learning how disabling sub-systems works), which already covers it, so there's no need for a `#ifndef SDL_GPU_DISABLED` in SDL_gpu.c I think?

**Comment by sezero** [comment]
OK, following @slouken's thumbs-up, applied the patch as a833ee2e63ee5da06fdc7ca72b4ec3375db5b8b8

> But I just noticed the `#undef`s in SDL_internal.h (I'm still learning how disabling sub-systems works), which already covers it, so there's no need for a `#ifndef SDL_GPU_DISABLED` in SDL_gpu.c I think?

The `#undef`s in SDL_internal.h disable the gpu backends, not SDL's gpu subsystem. Therefore the ifdefs in SDL_gpu.c are needed.
