### ISSUE TITLE
GPU: Depth Clamping?

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#10815]
Depth clamping is useful for more robust shadow map rendering and IMO is just generally better than depth clipping.
Always supported by D3D11+ & Metal (actually optional, but cube arrays need a higher version anyways).
Requires depthClamp on Vulkan, which is not supported by older Android devices.
Optional feature in WebGPU.
Relevant WebGPU discussion: https://github.com/gpuweb/gpuweb/issues/137 https://github.com/gpuweb/gpuweb/issues/2100 https://github.com/gpuweb/gpuweb/issues/480

**Comment by TheSpydog** [comment]
This seems reasonable, we'd just need to figure out a way to reconcile the backends' difference of opinion on depth clamping vs. clipping mutual exclusivity. If I'm reading this correctly, D3D always performs depth clamping, and clipping is an additional, optional step. But in Metal and Vulkan, it's one or the other -- you either clip or you clamp, but not both.

Will need to have a think on how to structure this in a way that makes sense across backends. It looks like 76% of Android devices support the feature so I'd be fine with requiring the feature in our Vulkan backend -- if it cuts off exclusively older devices, that's probably for the best anyway.

**Comment by rabbit-ecl** [comment]
Adding here that depthClamp is also part of Vulkan Roadmap 2022 so it's guaranteed to be supported in new devices even on Android.

**Comment by rabbit-ecl** [comment]
gpuinfo says that this is Mali being terrible again (of course), only Valhall µarch and newer hardware seems to have this (launched in 2019).

**Comment by thatcosmonaut** [comment]
Related to: https://github.com/libsdl-org/SDL/issues/10814
