### ISSUE TITLE
GPU: Change struct extension structure

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL#10829]
Should use `version` like other SDL structs instead of a properties table.

**Comment by flibitijibibo** [comment]
Putting this here for myself later... https://github.com/libsdl-org/SDL/pull/10726/files

**Comment by flibitijibibo** [comment]
In practice this ended up not making much sense; in addition to backend-specific properties already being in deployment the versioning would just end up getting mixed with the property extensions, so best to stick to one path rather than both.
