### ISSUE TITLE
Process: Argument finishing with a backslash fails test on Windows

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#10831]
Adding this test case in `process_testArguments` fails the test case:

    evil argument\

This could technically allow someone who controls the end of an argument the potential ability to insert extra arguments, but given that the process support was merged around an hour ago, I don't think anybody had had the time to develop any critical software with it :)

**Comment by slouken** [comment]
Feel free to PR your solution. :)

**Comment by Semphriss** [comment]
According to my research, there are two ways to fix this:

1. Backslash-escape every double quote, and every backslash that appears before a double quote (escaping other backslashes is not only not needed, it will in fact double the backslash), like: `arg\um"ent\` -> `arg\um\"ent\\`;
2. Replace the backslash with a double of the character, like: `arg\um"ent\` -> `arg\\um""ent\\`

Is there one that would be preferable? IMO the second one is much easier to implement, but it involves changing how it currently works.

**Comment by Semphriss** [comment]
Ended up doing the former; the latter didn't work, apparently.
