### ISSUE TITLE
SDL_WriteFile fails when writing lots of data, which the child process cannot buffer/process

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10834]
On my Linux system, writing a buffer bigger then 64kiB fails when using `SDL_WriteFile`.
This is expected as the default pipe capacity is 16 pages (=64kiB).
https://man7.org/linux/man-pages/man7/pipe.7.html

I think this is a recoverable "error state", so ideally `SDL_WriteFile` should also return the actual number of bytes written.

**Comment by slouken** [comment]
What is SDL_WriteFile()? SDL_WriteIO() does return the amount of data written, and there is an IO status of not ready. I use that in SDL_WriteProcess() to wait for data to be read by the child process.

**Comment by madebr** [comment]
Oops, I meant `SDL_WriteProcess`.
Python hangs indefinitely in the same situation.

https://github.com/libsdl-org/SDL/blob/27862907c65453e53828e9d892df81c8ce536ea7/include/SDL3/SDL_process.h#L307

**Comment by slouken** [comment]
You're right this is a footgun that we don't need in the API.
