### ISSUE TITLE
GPU: writeonly & atomics

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#10848]
Being pedantic here to point out that atomic ops are technically read-write and thus disallowed for writeonly storage bindings. What's SDL_gpu's stance on this? Atomics are the backbone of _a lot_ of compute algorithms and people are definitely going to be asking about this eventually.

**Comment by TheSpydog** [comment]
Yeah, so the reason for the `writeonly` terminology is that read-write compute resources are a huge mess. There are a grand total of 3 texture/buffer formats that are universally supported for RW access, and everything else is hardware dependent. If you're reading and writing from the same resource in a compute shader, it's extremely easy to accidentally write a compute setup that only works on a limited subset of machines.

That said, you can write whatever you want in your shaders. There's no way in D3D to require a UAV to be readonly, so "write only" is more of a suggestion than a requirement.

From a scan through the [D3D Feature Level 11.1 format support page](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/format-support-for-direct3d-11-1-feature-level-hardware), it looks like only 2 formats (R32_UINT / R32_SINT) support atomic operations. Unlike UAV typed load, they're not even optional for other formats.

I suppose we could change `writeonly` to `readwrite` with some heavy stipulations in the documentation that you can't rely on RW working outside of a small handful of formats (and we could add some related format queries), but I'm not sure how I feel about that. Do you have any suggestions for how we should handle this?

**Comment by thatcosmonaut** [comment]
Worth noting here that we have absolutely no way to perform validations on shader operations, so in general our only option is to document portability issues and leave it up to the client to make sensible choices.

**Comment by rabbit-ecl** [comment]
I'm not too well-versed in D3D semantics, but that R32_UINT / R32_SINT restriction looks similar to Vulkan/GL SSBO restrictions on atomics only being allowed for uint / int variables in core (with extensions adding support for other types). Metal seems to also only support atomics on 32-bit integers. "Atomics, but only for 32-bit ints" is a pretty universal restriction that people are used to and I think could be specified in the docs.

Also relevant from WebGPU: https://github.com/gpuweb/gpuweb/issues/2377 https://github.com/gpuweb/gpuweb/issues/1360

**Comment by thatcosmonaut** [comment]
I don't see how atomics really make sense for anything but integers so that seems right to me.

**Comment by rabbit-ecl** [comment]
Avert your eyes! (Not sure what this is useful for, but it exists ;) )
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_shader_atomic_float.html

**Comment by TheSpydog** [comment]
This was resolved by https://github.com/libsdl-org/SDL/pull/10965
