### ISSUE TITLE
GPU: More explicit multi-sampling?

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#10847]
From what I can gather, the current API with multi-sampled textures is something like this:
    - Creating a multi-sampled texture also implicitly creates a single-sampled texture
    - The implicit single-sampled texture is always resolved to on EndGPURenderPass
    - The implicit single-sampled texture is also used for other operations aside from rendering: copies & shader binding
    - load_op & store_op in BeginGPURenderPass only refer to the multi-sampled texture.

Some feedback:
    - Documentation is sparse
    - There's no control over whether resolves happen
    - There's no control over whether the single-sampled texture is created
    - It's impossible to copy between multi-sampled textures
    - It's impossible to read from multi-sampled textures in shaders (for custom resolves)
    - It's unclear if depth-stencil resolves are supported
    - This is completely different from the native APIs and adds some complexity on SDL_gpu side

I'm assuming(?) the idea here is to do some API-side automagic so users don't have to deal with the single-sampled/multi-sampled API use discrepancy.

But that seems futile given that sample_count is baked into GraphicsPipelineCreateInfo, thus users are always forced to deal with the discrepancy somewhere anyways.

I suggest just going a more native-like path and removing this implicit dual-texture thing.

FWIW sokol_gfx also moved away from this model: https://github.com/floooh/sokol/issues/816

**Comment by TheSpydog** [comment]
Completely agree. We were having this exact conversation internally earlier today and decided to rearchitect it to separate the multisample and resolve textures.
