### ISSUE TITLE
SDL2: Wayland + Zink gives Black Screen

### ISSUE THREAD

**Issue by fuenechaos** [libsdl-org/SDL#10853]
When using Wayland as video driver along with Zink the window is blank, but the process is running, like the audio plays and there is GPU usage which means the rendering is happening but the output is not being drawn to the window
I Tested it with both my igpu and dgpu which is giving the same result
X11 works fine, but i have had issues when using X11 driver with Zink for some games, causing crashes and freezing so Wayland is preferred

Here is my usual Launch command: 
`__GLX_VENDOR_LIBRARY_NAME=mesa __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink MESA_VK_DEVICE_SELECT=1002:1638 SDL_VIDEODRIVER=wayland  ./ioquake3.x86_64`

OS: Arch Linux
GPU: Nvidia GTX 1650 (dgpu), Radeon Vega 7 (igpu)

**Comment by Kontrabant** [comment]
This seems to be a Zink or driver bug, as I get a transparent or black window no matter what I run via Zink on Wayland (ioquake3, quakespasm, the SDL tests, es2gears). The last one is a Mesa demo, which doesn't use SDL.
