### ISSUE TITLE
`SDL_GpuGraphicsPipelineTargetInfo` prefix casing inconsistency

### ISSUE THREAD

**Issue by tritao** [libsdl-org/SDL#10855]
`SDL_GpuGraphicsPipelineTargetInfo` seems to be the only type using `Gpu`, when all others use `GPU`.

Is it an oversight and should this be fixed?

**Comment by flibitijibibo** [comment]
Yeah, probably got added right around the time we switched from Gpu to GPU. Can merge a fix for this super quickly if someone's able to do it soon!
