### ISSUE TITLE
SDL_GetRectAndLineIntersectionFloat hangs indefinitely

### ISSUE THREAD

**Issue by colinbs** [libsdl-org/SDL#10866]
I found that with certain input parameters, the function `SDL_GetRectAndLineIntersectionFloat` does not return.

I looked a bit deeper and found that in `SDL_INTERSECTRECTANDLINE` the Cohen-Sutherland algorithm spins forever. `outcode1` and `outcode2` are `8` and `5`, I can tell that much. Why, though, is beyond me. Searching through the git log I found out that e0fd59de646a43ec3fda84e92a673944b8d6d791 introduced the issue. Versions prior to this commit are working fine. In fact, if I change `ENCLOSEPOINTS_EPSILON` to `1.0f` in `video/SDL_rect.c` on the latest version, the issue disappears.

Anyways, an example program to reproduce the issue is here:

```c
#include <SDL3/SDL_main.h>
#include <SDL3/SDL_rect.h>

int main() {
    float x1 = 456.0f;
    float y1 = 592.0f;
    float x2 = 160.0f;
    float y2 = 670.0f;
    SDL_FRect rect;
    rect.x = 300.0f;
    rect.y = 592.0f;
    rect.w = 64.0f;
    rect.h = 64.0f;
    SDL_GetRectAndLineIntersectionFloat(&rect, &x1, &y1, &x2, &y2);
    return 0;
}
```

**Comment by slouken** [comment]
Fixed, thanks!
