### ISSUE TITLE
(SDL2.30.7 win32) Binaries distributed in release page depend on ucrtbase.dll

### ISSUE THREAD

**Issue by zongiin** [libsdl-org/SDL#10865]
This is a source built dll's dependency shown in Dependencies(modern rewrite of depends.exe). It does not have ucrtbase.dll as a dependency.

![image](https://github.com/user-attachments/assets/215830f1-4a56-49ba-a139-f3a08c1b1221)

This is the dependency of the dll distributed in the release page. It has a ucrtbase.dll dependency.

![image](https://github.com/user-attachments/assets/52c9fcfc-3a19-47ac-b323-ad168ebecee2)

I would like to check whether this is intended, since I prefer using the prebuilt binaries, but would not like c runtime in my dependencies.

**Comment by sezero** [comment]
Indeed. Running `x86_64-w64-mingw32-objdump -p SDL2.dll | grep 'DLL Name:'` outputs this:
```
	DLL Name: ADVAPI32.dll
	DLL Name: GDI32.dll
	DLL Name: IMM32.dll
	DLL Name: KERNEL32.dll
	DLL Name: api-ms-win-crt-environment-l1-1-0.dll
	DLL Name: api-ms-win-crt-heap-l1-1-0.dll
	DLL Name: api-ms-win-crt-private-l1-1-0.dll
	DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
	DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
	DLL Name: api-ms-win-crt-string-l1-1-0.dll
	DLL Name: api-ms-win-crt-time-l1-1-0.dll
	DLL Name: ole32.dll
	DLL Name: OLEAUT32.dll
	DLL Name: SETUPAPI.dll
	DLL Name: SHELL32.dll
	DLL Name: USER32.dll
	DLL Name: VERSION.dll
	DLL Name: WINMM.dll
```

**Comment by madebr** [comment]
For SDL2, this is intended. For SDL3, the default changed.

When building SDL using CMake, you can choose whether SDL uses libc with the CMake option `SDL_LIBC`.

Note that this option does only add a dependency to the SDL shared library. Your user application will remain untouched.
The SDL API is designed in such a way, that it does not expose anything from the c library (such as `FILE *`).

**Comment by sezero** [comment]
> For SDL2, this is intended.

No, it is not: @slouken builds using a mingw toolchain, and the resulting dll is based on how that gcc is configured.

**Comment by slouken** [comment]
@madebr, would it be possible to set up an SDL2 release workflow like you did for SDL3? It would be nice not to have to use a bespoke toolchain for releases. This would apply to the SDL satellite libraries as well.

**Comment by slouken** [comment]
I use `xcodebuild -configuration Release -scheme "Create DMG"`
Using scheme instead of target is important here.

**Comment by madebr** [comment]
Thanks, I [tried that](https://github.com/madebr/SDL_image/actions/runs/10931270581/job/30345907123#step:6:34),
but still see [issues with a few files](https://github.com/madebr/SDL_image/actions/runs/10931270581/job/30345907123#step:6:486).
Is it possible those files needs additional includes/dependencies?

**Comment by slouken** [comment]
The header search path in the Xcode project includes:
"$(SRCROOT)/$(PLATFORM)/SDL2.framework/Headers"
Is PLATFORM not being set, or do you not have the SDL3 framework available there?

**Comment by madebr** [comment]
Does the xcode framework need an installed SDL2 framework?
It's [part of the SDL2_image repo](https://github.com/libsdl-org/SDL_image/tree/SDL2/Xcode/macOS/SDL2.framework).

The log I shared is a build where the xcode project was built without anything done in advance.

**Comment by slouken** [comment]
No, $(SRCROOT) evaluates to the Xcode directory and macOS/SDL2.framework/Headers exists there, for example.

**Comment by madebr** [comment]
The issue was my scripts ignoring the symbolic links in the embedded framework.

Do the frameworks, built by the xcode project of SDL_image only support a single architecture?
https://github.com/madebr/SDL_image/actions/runs/10948332193/job/30399170473#step:10:59

**Comment by slouken** [comment]
I think you have to specify the architecture when building. I don't, which I think means they just support the current machine architecture? I'm not sure, and I'm not at a Mac at the moment, but if you ping me tomorrow I should be able to look if you haven't figured it out.

**Comment by madebr** [comment]
I have made no process on this.
A macos user tried the xcode project recently, and said "The Xcode project is properly configured, and environment variables seem like they have no effect".

[This is the log of a just-finished run.](https://github.com/madebr/SDL_image/actions/runs/11069226723)
I started the workflow by executing:
```sh
gh -R madebr/SDL_image workflow run release.yml --ref SDL2-release-scripts -f commit=$(git rev-parse HEAD)
```

**Comment by slouken** [comment]
It works for me locally...
`cd Xcode && xcodebuild -configuration Release -scheme "Create DMG"`
...
`created: /Users/valve/projects/SDL_image/Xcode/build/SDL2_image.dmg`

**Comment by slouken** [comment]
Oh, if I look at what's actually built though, it's arm64 only.  Let me see if it's possible to specify multiple architectures.

**Comment by madebr** [comment]
The workflow also creates a dng, but it's not fat.
Shouldn't it contain x86_64 and aarch64?

**Comment by slouken** [comment]
I think this needs the xcframework support that was added in SDL3. I think I'm fine with just including arm64 in published binaries.

**Comment by slouken** [comment]
Ah, got it!
`xcodebuild ONLY_ACTIVE_ARCH=NO -configuration Release -scheme "Create DMG"`

**Comment by madebr** [comment]
> Ah, got it! `xcodebuild ONLY_ACTIVE_ARCH=NO -configuration Release -scheme "Create DMG"`

That magic argument did the job!
https://github.com/madebr/SDL_image/actions/runs/11077956385
Many thanks :)

I'll look at porting this to SDL_mixer, SDL_net and SDL_ttf now.

**Comment by slouken** [comment]
You're welcome! Thank you! :)

**Comment by madebr** [comment]
I pushed something to SDL2 and release-2.30.x
I added `build-scripts/create-release.py` (instead of `create-release.sh`) as a thin wrapper around `git rev-parse HEAD` and `gh workflow run`.

|command|what|
|-|-|
|`build-scripts/create-release.py --ref release-2.30.x --commit 025fc35c87f05a0e0d8e2e9e3d497f2d3cc17aef`| Create release binaries using release.yml from 2.30.x branch, targeting commit 025fc35c |
|`build-scripts/create-release.py --ref release-2.30.x`| Create release using `release.yml` from `release-2.30.x` branch, which will execute the `build-release.py` script from the current checked out commit  |

This results in this run:
https://github.com/libsdl-org/SDL/actions/runs/11132270668

**Comment by sezero** [comment]
The mingw versions of the dlls have these dependencies, as output
by `x86_64-w64-mingw32-objdump -p $* | grep 'DLL Name:'`

```
	DLL Name: ADVAPI32.dll
	DLL Name: GDI32.dll
	DLL Name: IMM32.dll
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
	DLL Name: ole32.dll
	DLL Name: OLEAUT32.dll
	DLL Name: SETUPAPI.dll
	DLL Name: SHELL32.dll
	DLL Name: USER32.dll
	DLL Name: VERSION.dll
	DLL Name: WINMM.dll
```

**Comment by madebr** [comment]
I checked those too manually for the mingw and the msvc binaries, and looked correct to me. The new releases will have different SDL2.dll binaries for mingw vs msvc.
Your command might be useful to add to verify step for both msvc and mingw.

**Comment by slouken** [comment]
Yes, these are correct, thank you!

**Comment by slouken** [comment]
Okay, I'm checking the mingw development archive differences:
* The docs directory is missing
* SDL_config.h is the generated one instead of SDL_config_windows.h
* The lib directory is missing the .la files, and just has static archives, which means `make install-package` will fail, because it tries to modify those.

In the VC development archive:
* All the config headers are included instead of just SDL_config_windows.h renamed SDL_config.h
* The SDL2.dll included are from the MSVC build and not the mingw build.

I think aside from the missing .la files, these changes are okay. Can you fix that?

**Comment by madebr** [comment]
> Okay, I'm checking the mingw development archive differences:
> 
>     * The docs directory is missing

It now contains all `docs/*.md` in a `docs` folder.

> 
>     * SDL_config.h is the generated one instead of SDL_config_windows.h
> 
>     * The lib directory is missing the .la files, and just has static archives, which means `make install-package` will fail, because it tries to modify those.

SDL2 uses CMake to build the mingw binaries so there are no libtool files anymore.
(The SDL2 satellite libraries still use autoconf because it builds both shared and static libraries)
So I removed the relevant sed commands from the `Makefile`.


> In the VC development archive:
> 
>     * All the config headers are included instead of just SDL_config_windows.h renamed SDL_config.h
> 
>     * The SDL2.dll included are from the MSVC build and not the mingw build.
> 
> 
> I think aside from the missing docs and *.la files, these changes are okay. Can you fix that?

My intention for the `build-release.py` script is to make it identical over SDL2/SDL3 and all satellite libraries.
So I'd like to keep the modifications to a minimum.


New build at https://github.com/libsdl-org/SDL/actions/runs/11133449985,
triggered by `build-scripts/create-release.py --ref release-2.30.x`

**Comment by slouken** [comment]
Looks good. Instead of the .xz archives, can we add .zip archives for source and mingw packages? I can repack them here, so we don't need a respin of this, but some people download them on Windows and prefer having zip files available (or may not have tar extraction available at all)

**Comment by madebr** [comment]
The sources are already available as a zip. I'll add support for zipped mingw binaries.

**Comment by slouken** [comment]
Looks great, thanks everyone!
https://github.com/libsdl-org/SDL/releases/tag/release-2.30.8

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL_mixer/issues/638 is a blocker for SDL_image and SDL_mixer releases (I haven't looked into SDL_ttf yet)
