### ISSUE TITLE
warning: "SDL_VIDEO_RENDER_D3D12" is not defined

### ISSUE THREAD

**Issue by 1vanK** [libsdl-org/SDL#10861]
In mingw:
```
In file included from D:\a\dviglo2d\dviglo2d\repo\libs\third_party\sdl\repo\src\cpuinfo\SDL_cpuinfo.c:27:
D:/a/dviglo2d/dviglo2d/repo/libs/third_party/sdl/repo/src/core/windows/SDL_windows.h:39:5: warning: "SDL_VIDEO_RENDER_D3D12" is not defined, evaluates to 0 [-Wundef]
 39 | #if SDL_VIDEO_RENDER_D3D12 || defined(HAVE_DXGI1_6_H)
      |     ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by 1vanK** [comment]
In clang:

```
/home/runner/work/dviglo2d/dviglo2d/engine_repo/libs/third_party/sdl/repo/src/render/SDL_render.c:107:32: warning: variable 'render_drivers' is not needed and will not be emitted [-Wunneeded-internal-declaration]
static const SDL_RenderDriver *render_drivers[] = {
```

**Comment by slouken** [comment]
> In mingw:
> 
> ```
> In file included from D:\a\dviglo2d\dviglo2d\repo\libs\third_party\sdl\repo\src\cpuinfo\SDL_cpuinfo.c:27:
> D:/a/dviglo2d/dviglo2d/repo/libs/third_party/sdl/repo/src/core/windows/SDL_windows.h:39:5: warning: "SDL_VIDEO_RENDER_D3D12" is not defined, evaluates to 0 [-Wundef]
>  39 | #if SDL_VIDEO_RENDER_D3D12 || defined(HAVE_DXGI1_6_H)
>       |     ^~~~~~~~~~~~~~~~~~~~~~
> ```

This is fixed in 0f85fdefc.


> In clang:
> 
> ```
> /home/runner/work/dviglo2d/dviglo2d/engine_repo/libs/third_party/sdl/repo/src/render/SDL_render.c:107:32: warning: variable 'render_drivers' is not needed and will not be emitted [-Wunneeded-internal-declaration]
> static const SDL_RenderDriver *render_drivers[] = {
> ```

I wonder why this is happening? Even if the renderer is disabled, you'd still need the array size in SDL_GetNumRenderDrivers().

Do you have the latest code in main?

**Comment by 1vanK** [comment]
This version is used: https://github.com/dviglo2d/sdl

**Comment by 1vanK** [comment]
(sdl_render is disabled <https://github.com/dviglo2d/dviglo2d/blob/main/libs/third_party/sdl/CMakeLists.txt>)

**Comment by sezero** [comment]
> > In clang:
> > ```
> > /home/runner/work/dviglo2d/dviglo2d/engine_repo/libs/third_party/sdl/repo/src/render/SDL_render.c:107:32: warning: variable 'render_drivers' is not needed and will not be emitted [-Wunneeded-internal-declaration]
> > static const SDL_RenderDriver *render_drivers[] = {
> > ```
> 
> I wonder why this is happening? Even if the renderer is disabled, you'd still need the array size in SDL_GetNumRenderDrivers().

Looks like it is because the array size is computed at compile time and the array itself really isn't used at all at run time.

**Comment by Akaricchi** [comment]
`__attribute__ ((unused))` should fix that warning.

**Comment by sezero** [comment]
> `__attribute__ ((unused))` should fix that warning.

Yes, can be marked with `SDL_UNUSED`

**Comment by slouken** [comment]
I went ahead and just removed it.

**Comment by sezero** [comment]
> I went ahead and just removed it.

SDL_gpu.c should be changed similarly for `backends[]` then

**Comment by slouken** [comment]
> > I went ahead and just removed it.
> 
> SDL_gpu.c should be changed similarly for `backends[]` then

Done!

**Comment by sezero** [comment]
> > > I went ahead and just removed it.
> > 
> > 
> > SDL_gpu.c should be changed similarly for `backends[]` then
> 
> Done!

I can't see it -- forgot to push?

**Comment by slouken** [comment]
Oh, no, I pushed to my fork instead of SDL. Fixed!
