### ISSUE TITLE
Coordinate space of SDL_PenMotionEvent is unclear

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#10863]
The docs mention that `x` and `y` members of [`SDL_PenMotionEvent`](https://wiki.libsdl.org/SDL3/SDL_PenMotionEvent) correspond to the position of the pen on the tablet. But there is no way for an application to query the size of this 'tablet' -- no way to map them correctly to the game window.

I think it would make sense that these coordinates are in `SDL_Window` space.

Also, [`SDL_PEN_AXIS_XTILT` and `SDL_PEN_AXIS_YTILT`](https://wiki.libsdl.org/SDL3/SDL_PenAxis) mention a non-existent `SDL_PenCapabilityInfo` function.

**Comment by icculus** [comment]
Oh, yeah, I think I intended to normalize these coordinates, like touch events, and it turned out it wasn't possible. I'll double-check this.

**Comment by Susko3** [comment]
You should probably also update `SDL_ConvertEventToRenderCoordinates` to handle pen events when you figure the coordinate space out.
