### ISSUE TITLE
SDL_Process: file redirection on linux fails

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10868]
When redirecting stdin, stdout and stderr from SDL_IOStream's,
SDL_CreateProcessWithProperties fails with the error message:
```
posix_spawn() failed: Bad file descriptor
```

Test is available in https://github.com/libsdl-org/SDL/pull/10836

**Comment by smcv** [comment]
My guess would be that this is happening because `AddFileDescriptorCloseActions()` is sequenced before file redirection, but it should be after?

**Comment by slouken** [comment]
Yep, that's correct. I'll fix that, thanks!
