### ISSUE TITLE
Make overwrite behaviour uniform among `SDL_RenamePath` & `SDL_CopyFile`, etc. & document better

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#10886]
Digging into Windows code for `SDL_CopyFile`, it appears to fail if the destination exists, whereas `SDL_RenamePath` will overwrite the destination. Neither behaviour is documented. Should we uniform the behaviour of these operations? Or add a boolean overwrite option? Or at the very least document the behaviour?

**Comment by icculus** [comment]
Both should overwrite the destination, I'll fix that.
