### ISSUE TITLE
SDL3 seems to have audiodevice recording field backwards?

### ISSUE THREAD

**Issue by superfury** [libsdl-org/SDL#10885]
When I enable/disable the (record) audio device on Windows 10, I see that my app receives a SDL_EVENT_AUDIO_DEVICE_ADDED/SDL_EVENT_AUDIO_DEVICE_REMOVED with the recording field set backwards?

When I enable/disable the audio playback device, the events give adevice.recording==SDL_TRUE, when I enable/disable the audio recording device (a microphone), the events give adevice.recording==SDL_FALSE.

This is completely backwards from documentation?

**Comment by slouken** [comment]
Yep, this was backwards. Thanks!
