### ISSUE TITLE
renderer: dump most of the line drawing approaches

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10896]
We have _four_ different ways to draw lines in the 2D renderer:

- As actual lines, using QueueCmdDrawLines for native lines in the backend.
- As individual points, Bresenham-style, using QueueCmdDrawPoints for native points in the backend.
- As a collection of rectangles, Bresenham-style. Same idea, but used for scaling.
- With geometric primitives, ~1 pixel thick.

Partially this was to deal with the painful end-point laws on native lines, and partially this was to make several different camps happy (see #5061, where we beat this topic--and nearly ourselves--to death). One of the problems is that existing games could break with the geometry version, because they might be expecting specific (incorrect?) line end points, and they are very slightly thicker than native lines, but otherwise they seem to be pretty good.

Since we don't have to worry about existing games, I propose that we change this to do the following:

- If the backend supports native lines _and we are not scaling at all_, do that.
- Otherwise, use the geometry version.
- We remove native line support from everything but the software renderer.

The new intention of a backend supporting native lines isn't so much to pass stuff through to draw with `GL_LINES` on the GPU but to signal intention; this will let the software renderer draw a line faster than it could with the generic geometry; everything else backed by a GPU won't care either way so they don't implement it. We delete a bunch of code. Future backends have less to implement.

sdl2-compat will probably need to eat the Bresenham code from SDL_render.c to support existing games with specific pixel-perfect demands, but it would still be able to replicate everything but native lines with the public SDL3 API.

**Comment by slouken** [comment]
This seems like a good idea to me, as long as sdl2-compat works.

**Comment by icculus** [comment]
Okay, I just reread all of #5061, which gave me both PTSD and cold feet about making this change.

**Comment by icculus** [comment]
Let's not do this. It's only going to bring pain and misery.
