### ISSUE TITLE
SDL_GL_DeleteContext freezes in a threaded renderer

### ISSUE THREAD

**Issue by PunkPun** [libsdl-org/SDL#10900]
In OpenRA I tried to update to the latest SDL2 version and it seems that freezing on moving a window persists.

On Windows windowed mode OpenRA has avoided using threaded rendering for over 6 years due to other freezing issues, however when updating from `2.0.22` issues came to macOS as well.

Any Idea what could be causing a forever loop in `SDL_GL_SwapWindow` in a treaded context on macOS?

https://github.com/OpenRA/OpenRA/issues/20642 was the tracking issue that got fixed with us downgrading SDL2  2.26.1 -> 2.0.22. We had also downgraded because of #7507, but it was fixed in recent versions of SDL

**Comment by icculus** [comment]
This is always going to be dicey on macOS, but try adding this:

```c
SDL_SetHint(SDL_HINT_MAC_OPENGL_ASYNC_DISPATCH, "1");
```

**Comment by PunkPun** [comment]
Thanks, that fixed it.

But I'm also getting a different freeze in `SDL_GL_DeleteContext`

It happens when we try relaunching the game with a different resolution or window mode

**Comment by icculus** [comment]
What thread are you destroying the context from?

**Comment by PunkPun** [comment]
The thread the renderer is running in. And the thread it freezes the main thread one as well as we join them

**Comment by icculus** [comment]
We probably need the same async magic during destruction. I'll take a look.

**Comment by icculus** [comment]
@PunkPun, if you can try the latest in revision control for SDL3, it should fix your SDL_GL_DeleteContext problem. It uses the same SDL_HINT_MAC_OPENGL_ASYNC_DISPATCH hint now.

**Comment by PunkPun** [comment]
Updating to SDL3 is in our plans but may take a bit. How would I go to test this?

By coincidence today I was checking out how I would compile binaries from SDL3 and it seems many of the workflows were cleaned up (removed)

**Comment by icculus** [comment]
Oh, I forgot you were on SDL2. I can cherry-pick the change over there, I think.

**Comment by icculus** [comment]
Okay, try the latest in the SDL2 branch now, see if it solves the problem!

**Comment by PunkPun** [comment]
that seems to have fixed the issue

**Comment by anvilvapre** [comment]
Possibly relates #6981.
