### ISSUE TITLE
SDL_GPU should fail when explicitly requesting an unknown GPU backend

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#10919]
Currently, when running a test with an invalid gpu driver name, it will print an error message and fall back to a valid backend.
```
$ SDL_GPU_DRIVER=awesome_gpu_driver test/testsprite
ERROR: SDL_HINT_GPU_DRIVER unknown_gpu_driver unsupported!
4535.40 frames per second
4452.40 frames per second
... 
```

Instead, I think it should fail like it currently does for an unknown `SDL_AUDIO_DRIVER` or `SDL_VIDEO_DRIVER`:
```
$ SDL_VIDEO_DRIVER=mir test/testsprite
Couldn't initialize video driver: mir not available
```

**Comment by slouken** [comment]
Agreed.

**Comment by maia-s** [comment]
Why? Isn't it better that an incorrectly set environment variable doesn't stop every SDL app from working?

**Comment by maia-s** [comment]
esp since SDL 2 and 3 share environment variables and may have different drivers enabled

**Comment by flibitijibibo** [comment]
This may be my fault, I think it fell through when we unified the property string and environment variable. Should just need to add a return to the first part of SelectBackend and the rest will know what to do.

**Comment by flibitijibibo** [comment]
Actually it looks like we did that... I'm not sure how this is happening exactly. The fail line:

https://github.com/libsdl-org/SDL/blob/main/src/gpu/SDL_gpu.c#L425

**Comment by ritalat** [comment]
I think this is coming from the Renderer subsystem. Since commit [8585899](https://github.com/libsdl-org/SDL/commit/858589919aedb51911e8761f2bbaa2ca28de5bbf) SDL_GPU is the default backend but Renderer will simply fall back to something else if SDL_GPU fails to initialize.

**Comment by flibitijibibo** [comment]
Got it - so GPU fails but Render is able to keep going. I guess Render driver selection could treat GPU as a special case and fail early if the hint is set, but I wouldn't know what that would look like...

**Comment by Akaricchi** [comment]
> Got it - so GPU fails but Render is able to keep going. I guess Render driver selection could treat GPU as a special case and fail early if the hint is set, but I wouldn't know what that would look like...

I don't think this needs to be fixed. You can get this behavior by explicitly setting `SDL_RENDER_DRIVER=gpu`.

**Comment by slouken** [comment]
Yeah, this is fine. You're setting a GPU driver, but not specifying that the renderer needs to use the GPU renderer.
