### ISSUE TITLE
android-project using API 19 when new gradle needs 21

### ISSUE THREAD

**Issue by thenewkgb** [libsdl-org/SDL#10941]
I have Android Studio Koala 2024.1.2 Patch 1.
I'm using Linux Mint 22 Cinnamon.

If I open SDL-release-2.30.7/android-project it defaults to use gradle plugin 8.1.1 and the project builds and I have had it running on my phone. By upgrading gradle to 8.6.1 using AGP Upgrade Assistant I'm seeing an error I can't understand.

```
in unistd.h
line 239 : return __call_bypassing_fortify(readlinkat)(dirfd, path, buf, size);
```

```
error: cannot take address of function 'readlinkat' because parameter 3 has pass_object_size attribute
build failed
```

**Comment by thenewkgb** [comment]
Just as additional info

In file included from /home/***/Downloads/SDL-release-2.30.7/android-project/app/jni/SDL/src/SDL.c:28:
In file included from /home/***/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/unistd.h:428:

**Comment by madebr** [comment]
How did you fix, or work around this issue?

**Comment by thenewkgb** [comment]
Not fixed, but I thought I'd read up about it and not force someone else to tell me "tick this box" which is more likely.

**Comment by thenewkgb** [comment]
The SDL tar still used `arguments "APP_PLATFORM=android-19"` at line 22 in app/build.gradle
I changed the API for minSdkVersion but not the above.
API 21 works okay like it tells you to.

**Comment by thenewkgb** [comment]
A fix was found. I wouldn't want to push a change as some people may rely on an earlier gradle plugin. Change the API to 21 and it builds and runs.
