### ISSUE TITLE
POSIX SDL_SYS_CopyFile tmpfile choice

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10957]
src/filesystem/posix/SDL_sysfsops.c's SDL_SYS_CopyFile does this to choose a temp filename for the copy...

```c
    if (SDL_asprintf(&tmppath, "%s.tmp", newpath) < 0) {
        goto done;
    }
```

...without checking if that filename is currently in use, destroying its contents if so.

**Comment by icculus** [comment]
Actually, I'm going to remove the tempfile stuff, since we don't promise atomicity here.

**Comment by slouken** [comment]
Maybe we should?

**Comment by icculus** [comment]
Reopening this for a second for a bit more discussion, since I misunderstood Sam's reply up there.

So the docs now tell you how to guarantee atomicity for copies that replace an existing file, and steps have been taken to make sure the copy's data lands on disk so the rename afterwards will be safe.

We could build these steps into SDL_CopyFile() directly instead. The problems that I was avoiding by just leaving this as documentation:

- It's several steps that can go wrong.
- You need to have enough disk space to have two copies of the file in addition to the space used by the thing we're atomically replacing, which might not be a big deal but it _is_ an extra requirement.
- If the power goes out while writing to the temp file, SDL will _not_ be able to remove the temp file and won't know it's a temp file at all, whereas a game could definitely know to delete files named MYGAME-TEMPFILE-XXXXXX.tmp on startup.

**Comment by icculus** [comment]
Oh, and:

- The reason for this issue in the first place: you have to decide what temp filename to use, and make sure it's unique.

**Comment by slouken** [comment]
Good points.
