### ISSUE TITLE
 software renderer: examples/renderer/10-geometry missing a triangle

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10954]
The software renderer fails to draw a triangle in the top left of examples/renderer/10-geometry:

[Screencast from 2024-09-26 15-45-19.webm](https://github.com/user-attachments/assets/a60bacad-c5b6-4333-891b-f9e854ba284e)

It should have half of test/sample.bmp there, like in the OpenGL renderer:

[Screencast from 2024-09-26 15-47-08.webm](https://github.com/user-attachments/assets/eb360980-654a-4595-8a47-ff1eaed0b31f)

(it intentionally doesn't draw the whole .bmp, that's not a bug in this case.)

**Comment by 1bsyl** [comment]
it took me a while to find to find out how returning indice==2 was changed to indice=1
this is a typo  int changed to bool
