### ISSUE TITLE
Proposal: SDL_GetEntropy

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#10963]
Basically this would just be a thin shim for the secure OS RNG: getrandom/getentropy on linux, RtlGenRandom on Win32, etc.
Eventually SDL3_Net is going to need this, if we want to support TLS or similar.

`void SDL_GetEntropy(void *buf, size_t len)` (or bool? These really shouldn't ever fail in practice but the APIs insist...)

**Comment by nfries88** [comment]
IMO this is probably better left to SDL3_Net.

The main issue I have with putting this in core SDL3 is that a generic fallback implementation wouldn't be both cryptographically useful and simple.

I would also be pretty wary of SDL3_Net having its own TLS implementation, and existing TLS implementations like OpenSSL already provide their own functions for getting entropy so if simply wrapping one of those it shouldn't be necessary for SDL3_Net to have its own implementation.

**Comment by slouken** [comment]
Agreed, on all counts.
