### ISSUE TITLE
Segfault on Android after bumping SDL3

### ISSUE THREAD

**Issue by mechakotik** [libsdl-org/SDL#10970]
Just bumped SDL3 to latest commit (last time I bumped it before was 5 days ago), and my app is no longer launching. It gets segfault and prints lots of messages like this in logcat:

```
2024-09-27 22:31:59.959 12187-12242 vulkan org.libsdl.app E invalid vkGetDeviceProcAddr(VK_NULL_HANDLE, ...) call
```
Still works fine on my Linux desktop.

**Comment by slouken** [comment]
Any chance you can bisect the issue? I'm guessing this is a GPU regression (@thatcosmonaut?)

**Comment by flibitijibibo** [comment]
It's most likely the finalized physical device requirements but I'm pretty sure it knows to bail when those requirements aren't met. It'll help to know which device this is too.

**Comment by flibitijibibo** [comment]
Most likely failing here:

https://github.com/libsdl-org/SDL/blob/main/src/gpu/vulkan/SDL_gpu_vulkan.c#L11100

**Comment by thatcosmonaut** [comment]
It shouldn't even remotely reach that line unless the proc is found... We haven't touched the loader logic in a long time so it's somewhat surprising if this is a recent regression.

**Comment by flibitijibibo** [comment]
@mechakotik, can you give #10974 a try to see if that fixes it?

**Comment by mechakotik** [comment]
Yes, it works now. Thank you for being so fast in reviewing issues and PRs, this is honestly the most well maintained open source project I've ever dealt with.
