### ISSUE TITLE
SDL3, macOS: Main thread warnings with latest revision of SDL3

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10977]
Since recently I am getting these warnings when calling `SDL_RenderPresent()` on macOS Sonoma:

[NSView bounds] must be used from main thread only
[NSView convertRectToBacking:] must be used from main thread only

This did not happen before.

**Comment by Akaricchi** [comment]
Pretty sure it's because of #10958, since `SDL_RenderPresent()` calls `SDL_GetWindowSizeInPixels()` now, which calls those functions.

cc @thatcosmonaut

**Comment by flibitijibibo** [comment]
Marking as ABI since this may be an ABI regression in terms of having no way to get swapchain size safely.

**Comment by flibitijibibo** [comment]
@andreasgrabher, can you see if #10984 fixes this problem?
