### ISSUE TITLE
testnative doesn't quit

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#10988]
testnative doesn't quit for me when I hit the X button: window closes, but I have to `kill -9` to make the process actually quit. This is on i686 linux with X11 (no Wayland, just X11 on a gnome2 desktop.)

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by madebr** [comment]
Is this a duplicate of https://github.com/libsdl-org/SDL/issues/8111?

**Comment by sezero** [comment]
Ah yes, seems so. Closing.

P.S.: Would it make sense making testnative respond to ESC key?
