### ISSUE TITLE
Possible SDL_TICKS_PASSED macro optimization

### ISSUE THREAD

**Issue by dmzotov1986** [libsdl-org/SDL#10989]
I propose replacing the macro to potentially make it easier to perform operations on numbers with two's complement notation.

`<=` checks both zero and the high bit.

`>=` checks only the top bit. THEORETICALLY, on some machines it may be faster.

So instead of
```
#define SDL_TICKS_PASSED(A, B)  ((Sint32)((B) - (A)) <= 0)
```
, better like this:
```
#define SDL_TICKS_PASSED(A, B)  ((Sint32)((A) - (B)) >= 0)
```
.

This is in the <[SDL_timer.h](https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_timer.h#L106)> file, line number 106.

**Comment by slouken** [comment]
We'll pass on this, thanks!
