### ISSUE TITLE
Rename `SDL_IsAndroidTV()` to `SDL_IsTV()` and make it cross-platform ?

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#10999]
... like we already have a `SDL_IsTablet()`.

**Comment by flibitijibibo** [comment]
I'd be up for something like this - on PC we can check for SteamTenfoot and our console builds can simply return true. That said it's Android-related and I assume there's some very specific reason that check exists beyond tenfoot accessibility.

**Comment by slouken** [comment]
Sure, somebody feel free to create a PR for this.

**Comment by flibitijibibo** [comment]
@AntTheAlchemist, if you can do the rename before freeze I can take care of the PC implementation afterward for 3.2.0.

**Comment by AntTheAlchemist** [comment]
I'll knock something up now. Not entirely sure what I'm doing, so I'll just mirror how SDL_IsTablet is set up.

**Comment by AntTheAlchemist** [comment]
I've had a bash at this, but honestly don't really have a clue if I've done it right. Please somebody verify #11004

I noticed the core unsupported area is inconsistent. SDL_IsTablet doesn't appear there, but SDL_IsChromebook does, so I literally copied how SDL_IsTablet was set up. It seems to work, but I did all this by manually using the web-based edit option. I don't have any GitHub software installed.

**Comment by Sackzement** [comment]
Maybe related.

In `SDL_joystick.h` there is the macro constant `SDL_IPHONE_MAX_GFORCE`:
https://github.com/libsdl-org/SDL/blob/0b64520997ec89506895b091da4fbe84434923b0/include/SDL3/SDL_joystick.h#L164-L167
The mentioned  file `src/joystick/uikit/SDL_sysjoystick.m` doesn't exist.

`SDL_IPHONE_MAX_GFORCE` is only referenced in `docs/README-ios.md`: 
> Notes -- Accelerometer as Joystick
> ==============================================================================
> 
> SDL for iPhone supports polling the built in accelerometer as a joystick device.  For an example on how to do this, see the accelerometer.c in the demos directory.
> 
> The main thing to note when using the accelerometer with SDL is that while the iPhone natively reports accelerometer as floating point values in units of g-force, SDL_GetJoystickAxis() reports joystick values as signed integers.  Hence, in order to convert between the two, some clamping and scaling is necessary on the part of the iPhone SDL joystick driver.  To convert SDL_GetJoystickAxis() reported values BACK to units of g-force, simply multiply the values by SDL_IPHONE_MAX_GFORCE / 0x7FFF.

If this floating point is only used by Iphone, this is probably ok, and maybe the usage instructions could be mentioned above `SDL_IPHONE_MAX_GFORCE` as a comment.

If this applies to other devices too, the constant could be renamed to something generic.

**Comment by slouken** [comment]
Done!

**Comment by sezero** [comment]
> `SDL_IsAndroidTV()` is still in the public API? 

It is not.

**Comment by AntTheAlchemist** [comment]
Yep, ignore that. I (and the GitHub index) have just caught up.  All good.
