### ISSUE TITLE
SDL3, macOS: SDL_RenderPresent() hitting program assert

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10990]
With the latest revision of SDL3 my application hits a program assert when calling `SDL_RenderPresent()`. This error message is printed:

```
-[MTLTextureDescriptorInternal validateWithDevice:], line 1357: error 'Texture Descriptor Validation
MTLTextureDescriptor has width of zero.
MTLTextureDescriptor has height of zero.
'
```

This is most likely related to this commit: https://github.com/libsdl-org/SDL/pull/10984

It does not happen if I explicitly request a Metal renderer. The default renderer seems to be "gpu".

**Comment by flibitijibibo** [comment]
Looks like Metal is also prone to the zero width/height thing maybe?
