### ISSUE TITLE
Feature request: Make `SDL_AppQuit` aware of `SDL_AppResult`

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#10994]
Is it a good idea to pass `SDL_AppResult` to `SDL_AppQuit`, so it knows under what condition the app was terminated. For example, a decision can be made about saving settings depending on if the app shut down due to a failure.

**Comment by slouken** [comment]
Interesting idea. @icculus?

**Comment by icculus** [comment]
I just put up a PR for this; if you like it, click merge!
