### ISSUE TITLE
Wired Xbox 360 controller broken on macOS Sequoia

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#11002]
MacOS Sequoia added native support for wired Xbox 360 controllers using the Game Controller framework. This seems to have broken some assumptions that we had about Xbox 360 controller support on macOS in the HIDAPI driver. We assume that [we will always be talking through the 360Controller driver](https://github.com/libsdl-org/SDL/blob/1787d6ca5c249c7ebabf885e63c96b1a5f3f61cc/src/joystick/hidapi/SDL_hidapi_xbox360.c#L83C8-L97
) if we see a Xbox 360 wired controller on macOS. 360Controller speaks a slightly different protocol than the real Xbox 360 hardware, so these assumptions cause problems when we're receiving real unmodified reports from actual hardware.

The biggest problem is that the Y axis of both analog sticks is inverted. The reason is code here, presumably for a 360Controller quirk: https://github.com/libsdl-org/SDL/blob/1787d6ca5c249c7ebabf885e63c96b1a5f3f61cc/src/joystick/hidapi/SDL_hidapi_xbox360.c#L270-L274

The second issue is that rumble doesn't work through the HIDAPI device. One reason is the [special 360Controller rumble packet](https://github.com/libsdl-org/SDL/blob/1787d6ca5c249c7ebabf885e63c96b1a5f3f61cc/src/joystick/hidapi/SDL_hidapi_xbox360.c#L200-L223), but even getting rid of that hack doesn't result in working rumble. It's not clear if this is a limitation of macOS or something we're doing wrong.

Finally, the controller itself shows up twice in SDL. HIDAPI picks it up as an IOHID device and the MFI backend picks it up as a GCController. The latter seems to be what we really want to be using, since it has both a proper mapping and working rumble support.

This is all fairly easy to reproduce with `testcontroller`. By default you get both MFI and HIDAPI devices, but you can set `SDL_JOYSTICK_MFI=0` and `SDL_JOYSTICK_HIDAPI=0` to switch between the 2 duplicate devices.

It seems like we have basically two main options:
- Figure out how to tell 360Controller apart from real hardware in the HIDAPI driver and figure out how to get rumble working through HIDAPI (if it's even possible at all)
  - This seems like it will be a mess, since it will probably require adding a whole bunch of OS-specific stuff into the otherwise generic `SDL_hidapi_xbox360.c` file.
  - Sending raw output reports might not even be possible due macOS's driver having control of the device
- Figure out a way to prefer GCController over HIDAPI for these Xbox 360 controllers
  - We could prioritize GCController over HIDAPI for _all_ controllers, but I'm not sure if some controllers have more functionality through HIDAPI than GCController
  - We could prioritize GCController over HIDAPI for just certain controllers, but I don't know if there's an exhaustive list of all Xbox 360 devices that macOS Sequoia supports now. It could also change in a future OS update.

**Comment by slouken** [comment]
We can drop 360Controller support, that's fine. Currently we prefer HIDAPI over GCController for supported controllers because we typically have better support there. Does it work if we remove the 360Controller hacks?

**Comment by cgutman** [comment]
Not really, the axis inversion is fixed by removing 360Contoller support but broken rumble and duplicate controllers persist.

Deduplication between GCController and HIDAPI is also tough because we don't get a real VID/PID through GCController.

**Comment by slouken** [comment]
Thanks for the investigation! This is now fixed.

**Comment by slouken** [comment]
> Side question - it looks like the release that contains this fix will take some time to make it into Steam/MacOS/other software. In the interim, would wireless xbox controllers be technically susceptible to the same thing? Or would it only affect wired? I'm thinking as a temporary solution, people might be able to upgrade to a wireless controllers, potentially.

Wireless controllers work fine.

**Comment by acuteaura** [comment]
> Wireless controllers work fine.

Weirdly enough, I have an inverted Elite 2 on bluetooth in Lime3DS since Sequoia.

**Comment by slouken** [comment]
Does testcontroller from the SDL3 repo work?

**Comment by acuteaura** [comment]
> Does testcontroller from the SDL3 repo work?

Sorry, took me a while to figure out how to build everything. Does not reproduce on 3766a394096793e721e890dd2a046c9359524843. Neither Citra fork is unlikely to cut a release for a while, but once they do I'll check with them if this persists. Thanks.

**Comment by slouken** [comment]
Great, thanks for the update.

**Comment by v-pun215** [comment]
This is still an issue in macOS 15.5. Google Chrome, Crossover are some apps affected. Apps/Games that do not utilise SDL like Safari, native games like No Man's Sky, etc. are completely fine and do not have inverted y axis in Xbox 360 wired/2.4Ghz controllers.

**Comment by DivyumKinger** [comment]
> This is still an issue in macOS 15.5. Google Chrome, Crossover are some apps affected. Apps/Games that do not utilise SDL like Safari, native games like No Man's Sky, etc. are completely fine and do not have inverted y axis in Xbox 360 wired/2.4Ghz controllers.

So, is a fix not possible?

**Comment by v-pun215** [comment]
I believe it may be possible, but it all depends on chrome and crossover using the build of SDL that fixes this bug. I think it may be possible to patch a later SDL version into Crossover or/and Wine, but I don't really know.

**Comment by apoorv-agnihotri** [comment]
I have created a chrome extension to fix this issue let me know if it works.

https://github.com/apoorv-agnihotri/Gamepad-Mapper.

<img width="733" height="639" alt="Image" src="https://github.com/user-attachments/assets/c0eec0be-819c-4cd0-87fd-a75afe3249a6" />

**Comment by qwertychouskie** [comment]
The macOS-specific axis inversion was added back in https://github.com/libsdl-org/SDL/commit/d7b1ba1bfca7c9bf4f57075258ccfa0e0c6b2051, only about a week after this issue was closed as fixed.  While I don't have an OEM wired Xbox 360 controller to test, the Logitech F310 in Xinput mode, forced to use the libusb hidraw backend, has inverted Y axes.  If the Steam Virtual Gamepad and the old "360Controller" driver need axis inversion, shouldn't that be done specifically for these controllers, rather than breaking all other 360-class controllers?

**Comment by qwertychouskie** [comment]
I believe this issue should finally be fixed properly with https://github.com/libsdl-org/SDL/pull/15792.  If anyone has an OEM wired Xbox 360 controller they can use to confirm the fix is correct for macOS's native controller support, that would be greatly appreciated.
