### ISSUE TITLE
Thrustmaster T.16000 Joystick - Z-axis is not detected

### ISSUE THREAD

**Issue by D4n2021** [libsdl-org/SDL#11008]
See this issue please https://github.com/AntiMicroX/antimicrox/issues/1039

**Comment by trimikix20** [comment]
So de Z axies does not work and some of the buttons on the side of the flight controller

**Comment by trimikix20** [comment]
Is there a avancement to the process of fixing the issue?

**Comment by slouken** [comment]
Yes, I just tested with a T.16000M with testcontroller from SDL3 on Windows 10 and it works great! All the axes and buttons show up as expected.

**Comment by trimikix20** [comment]
There will be no problem with the windows 11?

**Comment by trimikix20** [comment]
Thank you for your work

**Comment by slouken** [comment]
I just tested SDL3 on Windows 11 and it works there as well.

**Comment by trimikix20** [comment]
for me i just reinstall the program and the z axie and the button i mention still doesnt show correctly or for the z axies doesnt do a thing

**Comment by AntTheAlchemist** [comment]
> for me i just reinstall the program and the z axie and the button i mention still doesnt show correctly or for the z axies doesnt do a thing

Do you have any other apps open? The Steam Client can mess with things.

**Comment by trimikix20** [comment]
no just the game and the app antimicrox 

but i have install the portable version, is it possible that could be from this version ?
