### ISSUE TITLE
SDL_IPHONE_MAX_GFORCE: adding usage comment in code

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#11005]
In `SDL_joystick.h` there is the macro constant `SDL_IPHONE_MAX_GFORCE`:

https://github.com/libsdl-org/SDL/blob/0b64520997ec89506895b091da4fbe84434923b0/include/SDL3/SDL_joystick.h#L164-L167

The mentioned file `src/joystick/uikit/SDL_sysjoystick.m` doesn't exist.

`SDL_IPHONE_MAX_GFORCE` is only referenced in `docs/README-ios.md`:

> # Notes -- Accelerometer as Joystick
> SDL for iPhone supports polling the built in accelerometer as a joystick device.  For an example on how to do this, see the accelerometer.c in the demos directory.
> The main thing to note when using the accelerometer with SDL is that while the iPhone natively reports accelerometer as floating point values in units of g-force, SDL_GetJoystickAxis() reports joystick values as signed integers.  Hence, in order to convert between the two, some clamping and scaling is necessary on the part of the iPhone SDL joystick driver.  To convert SDL_GetJoystickAxis() reported values BACK to units of g-force, simply multiply the values by SDL_IPHONE_MAX_GFORCE / 0x7FFF.

The mentioned demo file `accelerometer.c` isn't in SD3 anymore.
In SDL2 it can be foud under `SDL-2.30.7/Xcode-iOS/Demos/src/accelerometer.c`

**Comment by Sackzement** [comment]
Another idea:
Would it be be possible to convert the accelerometer values for iPhones inside the `SDL_GetJoystickAxis()` functions before returning it? Then clients wouldn't have to do it manually just for iPhones and all code using accelerometers would look the same.

**Comment by slouken** [comment]
Removed, thanks!
