### ISSUE TITLE
Expose texture size and add refcount?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11001]
The surface internal/public split seems to be working well for surfaces, do we want to do the same for textures to make the width and height public so people don't have to make a call to query it all the time, and add a public refcount like we do for surfaces?

On that note, do we want to do something similar for windows? @icculus, thoughts?

**Comment by icculus** [comment]
Don't know if we need the refcount for textures (but I'm not really awake yet to think this through), but not having to query for width/height is _super_ desirable.

**Comment by slouken** [comment]
So I tried out two different approaches:
https://github.com/libsdl-org/SDL/pull/11017
https://github.com/libsdl-org/SDL/pull/11018

I think the second one is better, what do you think?
I tried the same approach with windows, and it turns out pretty much the only safe thing to expose is the window ID, which is kind of silly.

**Comment by slouken** [comment]
Done!
