### ISSUE TITLE
GameCube Adapter support seems broken

### ISSUE THREAD

**Issue by bemug** [libsdl-org/SDL#11012]
Hi,

I'm on Linux running latest Arch.
I recall having my official Nintendo GameCube adapter working out of the box on SDL2 games. Now it doesn't seem to work anymore
I also recall testing [this Godot PR](https://github.com/godotengine/godot/pull/87925#issuecomment-2090170686) adding SDL support for gamepad and it worked correctly. Now rebuilding with the same commit fails.
I built [jstest-sdl](https://github.com/meleu/jstest-sdl.git) to test and indeed it couldn't detect my gamepad either.

I'm new to SDL development and would like someone to double check if it working on its side.

**Comment by flibitijibibo** [comment]
Did you have to add a udev rule for the adapter back then? Not sure if Arch packages that somehow but that's usually the main reason it's not detected at first; this is the same rule that's documented for dolphin-emu.

**Comment by bemug** [comment]
I remember having the udev rules back then, since my dolphin install is pretty old and it comes in its packages :
https://gitlab.archlinux.org/archlinux/packaging/packages/dolphin-emu/-/blob/main/PKGBUILD?ref_type=heads#L136

On my machine :
```
$ cat /usr/lib/udev/rules.d/51-usb-device.rules 
#GameCube Controller Adapter
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", TAG+="uaccess"

#Wiimotes or DolphinBar
SUBSYSTEM=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0306", TAG+="uaccess"
SUBSYSTEM=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0330", TAG+="uaccess"
```

I also have another file :
```
$ cat /etc/udev/rules.d/51-gcadapter.rules
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666"
```
That I should have created a while back when it was not packaged yet, as specified here :
https://fr.dolphin-emu.org/docs/guides/how-use-official-gc-controller-adapter-wii-u/

I tried removing both of them and unfortunately I still have the same issue. But AFAIK these rules are needed for SDL anyway.

**Comment by flibitijibibo** [comment]
Did a quick check and can confirm it works locally - if you happen to have FEZ on Steam you can opt into the `sdl3` beta branch and see if the controller is detected there.

udev rule on my system at `/etc/udev/rules.d/51-gcadapter.rules`:
```
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666"
```

**Comment by bemug** [comment]
Thank you for testing.

Interesting, I tried it on FEZ with the sdl3 and it works flawlessly. It does not on the main branch but I'm not sure it is supposed to.
May I ask you to try on an sdl2 game ? Or maybe a tool such as jstest-sdl for simplicity ?

**Comment by flibitijibibo** [comment]
It's been a while but I think the `beta` branch of FEZ is on 2.30.x, which I built with autoconf - if that build doesn't work I should be able to figure things out locally.

**Comment by bemug** [comment]
The `beta` branch is working. Strange.

**Comment by flibitijibibo** [comment]
The only thing I can think of is that 2.0 still requires passing `--enable-hidapi-libusb` to configure, not sure what CMake needs since 3.0 defaults to it being enabled...

**Comment by bemug** [comment]
Since it seems to be on my side I'll close the issue.
Thanks a lot for helping me debug this.

I'll reopen if I find anything new.

**Comment by bemug** [comment]
I figured it out.

If `--enable-hidapi-libusb` is required, then [this update to the Arch package](https://gitlab.archlinux.org/archlinux/packaging/packages/sdl2/-/commit/f382b345c13e9f5478717601048d6c1be2c0b6cc#9b9baac1eb9b72790eef5540a1685306fc43fd6c_26_26) is causing the issue : it removes the `SDL_HIDAPI_LIBUSB` flag.
It was 2 months ago, so it matches my timeline.

The [linked issue](https://gitlab.archlinux.org/archlinux/packaging/packages/sdl2/-/issues/2) states the same issue as me. Case solved.

**Comment by slouken** [comment]
`--enable-hidapi-libusb` is required, the whitelisting changes just make it possible to enable by default.
