### ISSUE TITLE
Change gendynapi.pl to gendynapi.py in comments

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#11032]
https://github.com/libsdl-org/SDL/blob/47450425fd4221f1979eee95afda4801e389f3fc/src/dynapi/SDL_dynapi_overrides.h#L23
https://github.com/libsdl-org/SDL/blob/47450425fd4221f1979eee95afda4801e389f3fc/src/dynapi/SDL_dynapi_procs.h#L24

------------------------
------------------------

Another question about `gendynapi.py`:
I found a function with two const parameters, which could be changed to a non-const ones:
`SDL_RenderTextureRotated()`'s `angle` and `flip`:
https://github.com/libsdl-org/SDL/blob/47450425fd4221f1979eee95afda4801e389f3fc/include/SDL3/SDL_render.h#L2063-L2066
https://github.com/libsdl-org/SDL/blob/47450425fd4221f1979eee95afda4801e389f3fc/src/render/SDL_render.c#L3912-L3915

Would it have been ok to change the parameters to non-const in the function declaration and definition and then to manually change it in `src/dynapi/SDL_dynapi_procs.h` too?:
https://github.com/libsdl-org/SDL/blob/47450425fd4221f1979eee95afda4801e389f3fc/src/dynapi/SDL_dynapi_procs.h#L786

Or is this, like the comment says, a big no-no?

What exactly are the steps when changing function parameter qualifiers?

**Comment by Sackzement** [comment]
> `gendynapi.py` only supports adding API functions, not modifications: those you need to apply manually.

Alright, thanks for the info!

**Comment by icculus** [comment]
> What exactly are the steps when changing function parameter qualifiers?

Hand-editing, and only until ABI lock happens. After that, we live with it unchanged until SDL4.

**Comment by icculus** [comment]
(So if you find any more consts like this, mention them asap, since we're about to go into ABI lock.)

**Comment by Sackzement** [comment]
> (So if you find any more consts like this, mention them asap, since we're about to go into ABI lock.)

Haven't found others in the public headers.

Only a few in src files like:
https://github.com/libsdl-org/SDL/blob/d287feaddfe4ce10128b2db93c144aecd4300212/src/SDL_hashtable.h#L32-L37
which aren't that important.

**Comment by slouken** [comment]
Let's clean up the ones in SDL_hashtable.h, since we might make that a public API at some point.

**Comment by Sackzement** [comment]
there's only one other const-qualified warning clang-tidy is spotting:
```c
src/libm/math_private.h:232:70: warning: parameter 5 is const-qualified
```
It's not that important, but it's the only one left

**Comment by slouken** [comment]
> there's only one other const-qualified warning clang-tidy is spotting:
> 
> ```c
> src/libm/math_private.h:232:70: warning: parameter 5 is const-qualified
> ```
> 
> https://github.com/libsdl-org/SDL/blob/d287feaddfe4ce10128b2db93c144aecd4300212/src/libm/math_private.h#L232
> 
> It's not that important, but it's the only one left

That's in third party code, so we won't be changing that.
