### ISSUE TITLE
SDL2 2.30.8: M_PI undeclared error

### ISSUE THREAD

**Issue by Mathieu015** [libsdl-org/SDL#11036]
Using SDL2 2.30.8 (mingw32 x86_64) causes the error of not being able to find M_PI constant from math.h. Using 2.30.7 doesn't give me that error.

**Comment by AntTheAlchemist** [comment]
Is SDL_PI_F / SDL_PI_D defined?

**Comment by Mathieu015** [comment]
No.

**Comment by sezero** [comment]
Unlike 2.30.7 and older, the 2.30.8 devel binaries package seems to contain cmake-generated SDL_config.h. 

I think your solution should be either (i) Take SDL_config_windows.h from the 2.30.8 source package, rename it to SDL_config.h and overwrite the SDL_config.h in the devel package you are using, or (ii) define `_USE_MATH_DEFINES` in your application before including SDL.h

**Comment by madebr** [comment]
Sure, but shouldn't SDL_config.h generated by autotools/cmake have similar behavior as the "fixed" ones?
What conditional define is missing from the generated `SDL_config.h`?

**Comment by slouken** [comment]
No, they're totally different. The automake generated one is based on the build environment, where the one we normally ship is stripped down and custom to the minimal set of requirements for an SDL development environment.

**Comment by slouken** [comment]
This is easier in SDL3 where we don't have build environment variables in public headers. :)

**Comment by slouken** [comment]
This has been fixed, thanks!
https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-mingw.zip

**Comment by sezero** [comment]
> This has been fixed, thanks! https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-mingw.zip

I downloaded the tarball https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-mingw.tar.gz instead: it contains _a lot_ of mac metadata: extracting on linux gives outputs many `tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'` messages and I have `._*` companions for every `*` file after extracting.

**Comment by madebr** [comment]
Same here. I think there went something wrong with the repack.

**Comment by slouken** [comment]
Mmmm, try this?
[SDL2-devel-2.30.8-mingw.tar.gz](https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-mingw.tar.gz)

**Comment by sezero** [comment]
> Mmmm, try this? [SDL2-devel-2.30.8-mingw.tar.gz](https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-mingw.tar.gz)

Good now

**Comment by slouken** [comment]
Great, thanks.

**Comment by sezero** [comment]
Also remember that SDL2-devel-2.30.8-VC.zip, SDL2-2.30.8-win32-x64.zip, and SDL2-2.30.8-win32-x86.zip contains msvc-built dlls, different than the ones in the mingw -devel package: this is different from older releases.

**Comment by slouken** [comment]
Yep.
