### ISSUE TITLE
SDL_migration.cocci still refers to SDL_CreateWindowWithPosition

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#11035]
SDL_migration.cocci has a wrong entry that almost every user is going to hit:

```
- SDL_CreateWindow(e1, e2, e3, e4, e5, e6)
+ SDL_CreateWindowWithPosition(e1, e2, e3, e4, e5, e6)
```

There's no CreateWindowWithPosition anymore; this needs to create an SDL_PropertiesID, put values for SDL_PROP_WINDOW_CREATE_X_NUMBER and SDL_PROP_WINDOW_CREATE_Y_NUMBER in it, call SDL_CreateWindowWithProperties, and then SDL_DestroyProperties.

I don't know how to correctly express that in this file, if someone else can take a run at it.

**Comment by icculus** [comment]
(Or is it better to create the window hidden, call SDL_SetWindowPosition, then show it? I can't remember.)

**Comment by slouken** [comment]
If the position is SDL_WINDOWPOS_UNDEFINED or SDL_WINDOWPOS_CENTERED, we can just use the new function and drop the position parameters. Otherwise, I think we don't touch it and let them look a the migration guide.

**Comment by icculus** [comment]
Okay, I'll take care of this tonight.

**Comment by icculus** [comment]
Turns out we already had the UNDEFINED one, so I just removed the obsolete one.

(CENTERED we probably can't guarantee, so I left that alone, too.)
