### ISSUE TITLE
Rendering to texture fails on Android with specific images

### ISSUE THREAD

**Issue by mechakotik** [libsdl-org/SDL#11033]
I have encountered a really strange issue. On Android only, some images fail to render to texture, while others work fine. Everything works fine on PC. My project uses SDL3 currently, however this issue also appeared on SDL2, but here it magically disappeared when I removed setting texture blend mode to `SDL_BLENDMODE_BLEND`. On SDL3, this workaround no longer works. Here is a minimal code + image example to easily reproduce the issue:

```cpp
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3_image/SDL_image.h>

int main(int argc, char* args[])
{
    SDL_Init(SDL_INIT_VIDEO);
    IMG_Init(IMG_INIT_PNG);

    SDL_Window *window;
    SDL_Renderer *renderer;
    SDL_CreateWindowAndRenderer("test", 3120, 1440, SDL_WINDOW_FULLSCREEN, &window, &renderer);

    SDL_Surface *surface = IMG_Load("sprite1.png");
    SDL_Texture *texture = SDL_CreateTextureFromSurface(renderer, surface);
    SDL_DestroySurface(surface);
    SDL_SetTextureScaleMode(texture, SDL_SCALEMODE_NEAREST);

    SDL_Texture* targetTexture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_TARGET, 3120, 1440);
    SDL_SetTextureScaleMode(targetTexture, SDL_SCALEMODE_NEAREST);

    while(true) {
        SDL_Event event;
        bool quit = false;
        while(SDL_PollEvent(&event)) {
            if(event.type == SDL_EVENT_QUIT) {
                quit = true;
                break;
            }
        }
        if(quit) {
            break;
        }

        SDL_SetRenderTarget(renderer, targetTexture);
        SDL_RenderClear(renderer);
        SDL_FRect srcRect{0, 0, 160, 144}, dstRect{0, 0, 1920, 1440};
        SDL_RenderTexture(renderer, texture, &srcRect, &dstRect);

        SDL_SetRenderTarget(renderer, nullptr);
        SDL_RenderClear(renderer);
        srcRect = dstRect = {0, 0, 3120, 1440};
        SDL_RenderTexture(renderer, targetTexture, &srcRect, &dstRect);
        SDL_RenderPresent(renderer);
    }

    SDL_DestroyTexture(texture);
    SDL_DestroyTexture(targetTexture);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);

    return 0;
}
```

![sprite1](https://github.com/user-attachments/assets/186e8d28-15e1-4b07-85bb-bfd8aedb1f5a)
![sprite2](https://github.com/user-attachments/assets/2f9abeab-47d9-4b87-8dd2-26bf43cd897a)

It doesn't work with the first image, but works with the second one. My device is Pixel 7 Pro, the issue also appeared on my old Redmi Note 5 Pro (tested with SDL2 only).

**Comment by mechakotik** [comment]
I was able to workaround this by opening the second image in sprite editor and copying the first image content in it. Maybe this is related to RGB/RGBA format difference?

**Comment by slouken** [comment]
Yes, SDL now defaults to enable blending for RGBA images, so if your image is saved with 0 in the alpha channel, it won't show up visually.
