### ISSUE TITLE
SDL_EGL_SetAttributeCallbacks is poorly thought out

### ISSUE THREAD

**Issue by Akaricchi** [libsdl-org/SDL#11039]
I previously opened #11013 to complain about the lack of a context parameter for the callback. That's been fixed, but now that I've actually tried using the new API, I realize that it's inadequate.

It seems to me that there are only two correct ways to use this API:

* Return a static data pointer from the callbacks; or
* Allocate the attribute arrays externally, pass them in `userdata`, and return pointers to them from the callback.

The client doesn't really know when or how many times the callback is going to be called. It's also not clear when it's safe to free the allocated memory, unless the user explicitly calls `SDL_GL_ResetAttributes()` and frees it afterwards.

It's questionable why this is implemented as a callback at all. I'd like to propose a simpler API:

```c
/**
 * Installs custom EGLAttrib arrays for EGL initialization.
 *
 * Each parameter should be a pointer to an EGL attribute array terminated
 * with EGL_NONE. These arrays will be appended to the existing attribute
 * arrays defined by SDL. Each parameter may be NULL, in which case the
 * corresponding array will not be modified.
 *
 * SDL will make an internal a copy of the arrays, so they don't have to be
 * valid after this function returns.
 *
 * Calling this function again will replace any previously installed
 * attribute arrays.
 *
 * NOTE: Custom EGL attributes will be reset after SDL_GL_ResetAttributes.
 *
 * \param platformAttribs   attributes to pass to eglGetPlatformDisplay.
 * \param surfaceAttribs    attributes to pass to eglCreateSurface.
 * \param contextAttribs    attributes to pass to eglCreateContext.
 *
 * \since This function is available since SDL 3.0.0.
 */
extern SDL_DECLSPEC void SDLCALL SDL_EGL_SetCustomEGLAttributes(const SDL_EGLAttrib *platformAttribs,
                                                                const SDL_EGLint *surfaceAttribs,
                                                                const SDL_EGLint *contextAttribs);
```

This API lacks the "return NULL to fail SDL_CreateWindow" feature, but I'm not sure how that can be effectively utilized under the current API, either.

**Comment by slouken** [comment]
This seems reasonable to me, @icculus?

**Comment by icculus** [comment]
Yeah, this shouldn't be a callback, imho, let's change this.

**Comment by slouken** [comment]
We should probably review the discussion on the bug that led to this change. I remember there being good rationale for it being a callback.

**Comment by Akaricchi** [comment]
If it absolutely must be a callback, then there has to be be a "free userdata" callback as well. I can't think of a good reason for it to be a callback though, really curious about that rationale.

**Comment by icculus** [comment]
I'll do some research real fast.

**Comment by Akaricchi** [comment]
The rationale for callbacks is in the commit that added them: https://github.com/libsdl-org/SDL/commit/085a276d6c53392dcf1467723e881d78e94e8a5e

> the EGL extension list before creating an EGLDisplay differs from the extension list after (i.e. display vs client extensions)

This makes sense… sort of. The problem with this is that the callbacks don't have enough information to actually query the extensions, e.g. you need an `EGLDisplay` pointer to query display extensions. It's possible to get it [through a terrible hack](https://github.com/taisei-project/taisei/blob/b61185ff06fa520242f7d1f171d8ef58628ff41e/src/renderer/glescommon/angle_egl.c#L125) in SDL2 (at least sometimes…), I'm not sure if SDL3 offers anything better in that regard.

**Comment by Akaricchi** [comment]
The new EGL functions in SDL3 make it easier

> [SDL_EGL_GetCurrentConfig](https://wiki.libsdl.org/SDL3/SDL_EGL_GetCurrentConfig)
> [SDL_EGL_GetCurrentDisplay](https://wiki.libsdl.org/SDL3/SDL_EGL_GetCurrentDisplay)
> [SDL_EGL_GetProcAddress](https://wiki.libsdl.org/SDL3/SDL_EGL_GetProcAddress)

I don't know how I feel about having to call `SDL_EGL_GetCurrentDisplay()` instead of getting it as a function parameter, but I suppose it works…

We can keep these as callbacks, then, but a cleanup callback needs to be added.

**Comment by icculus** [comment]
> We can keep these as callbacks, then, but a cleanup callback needs to be added.

Easiest is going to be to say that the callback must allocate the pointer, and SDL will call SDL_free() on it when it's done with it.

(and we can pass the display pointer in with the callbacks, discounting the platformattribute callback, where it doesn't exist yet.)

**Comment by Akaricchi** [comment]
> Easiest is going to be to say that the callback must allocate the pointer, and SDL will call SDL_free() on it when it's done with it.

I assume you're talking about the attribute list pointers returned from the callbacks. That kinda works but only solves part of the problem. The problem is that the userdata context struct will probably have to be allocated as well. Consider client code like this:

```c
void SetupEGLAttribs() {
    MyCallbackContext ctx = { };
    ctx.foo = "bar";
    SDL_EGL_SetAttributeCallbacks(my_callback1, my_callback2, my_callback3, &ctx);
}

void main() {
    SetupEGLAttribs();
    /* many calls later */
    CreateEGLContext();   // invokes callbacks -- MyCallbackContext pointer is invalid!
}
```

My understanding is that the callbacks installed by `SDL_EGL_SetAttributeCallbacks` stay there until they are reset or the video subsystem goes down, and may be potentially called more than once. For this to work, the context struct must be allocated or static.

It should be enough to let the client know when the context struct is no longer needed. It can then take care of freeing it and any attribute arrays it previously allocated (all of that could be parts of the same allocation, too).

**Comment by slouken** [comment]
Well, definitely don't set any SDL callbacks with a pointer on the stack unless you reset them before leaving the function. That's just user error. :)

Setting the callbacks to NULL is a good way to signal that you're done.

**Comment by icculus** [comment]
Also, after the call to SDL_CreateWindow, that's the definite end of the callbacks. They don't fire arbitrarily in the future, so the app knows the final point where they can be used.

**Comment by icculus** [comment]
Okay, I stuck a pull request up that should settle this...? Feedback welcome!

**Comment by Akaricchi** [comment]
> Well, definitely don't set any SDL callbacks with a pointer on the stack unless you reset them before leaving the function. That's just user error. :)

Yeah, that's my point. You can't do that, so you have to allocate the struct, and know when SDL is done with it.

> Also, after the call to SDL_CreateWindow, that's the definite end of the callbacks. They don't fire arbitrarily in the future, so the app knows the final point where they can be used.

What happens if the window is re-created or another one is opened?

**Comment by slouken** [comment]
@Akaricchi, does that commit work for you?
