### ISSUE TITLE
Incorrect Behaviour with SDL_WINDOW_FULLSCREEN_DESKTOP on Windows

### ISSUE THREAD

**Issue by ShikenNuggets** [libsdl-org/SDL#11041]
On Windows (11 in my case), creating a new window or calling `SDL_SetWindowFullscreen` with the `SDL_WINDOW_FULLSCREEN_DESKTOP` flag does not seem to produce the desired behaviour. It does create a window with no border that takes up the full display, but when the window gains focus some kind of display mode change is forced that blacks out my monitor for a few seconds, and alt-tabbing away or bringing up the taskbar triggers another display mode change. The behaviour is a bit different than `SDL_WINDOW_FULLSCREEN` as I can still see the window after tabbing or bringing up the taskbar. I _think_ this is something Windows is deciding to do on its own, not something that SDL is explicitly asking it to do, but regardless, other applications are able to produce the desired behaviour, so there should be a way for SDL to do so as well.

I have a [consistent repro for this here](https://github.com/ShikenNuggets/GadgetEngine/blob/main/WorkbenchCPP/Core/EditorWindow.cpp) if you want to confirm that I'm not doing anything obviously wrong (this is from a real repository; I can create a minimal repro case later if that would be helpful, though it should be easy enough to recreate). This repro is on 2.30.5, but I've confirmed that the issue is still present on 2.30.8. The window in my repro cases also has an OpenGL context, in case that's somehow relevant.

I did some digging and was able to narrow down a possible cause to the `GetWindowStyle` function in `SDL_windowswindow.c`. I tried removing `WS_POPUP` from the style defines used by that function, and that appears to give me the desired behaviour. I'm not confident enough in my Win32 knowledge or SDL's internal workings to recommend it as the official solution, and I'm not even entirely clear on what `WS_POPUP` is supposed to do exactly (the Microsoft documentation doesn't clear anything up, and I've gotten conflicting information from other sources). However, it did fully resolve this issue for me, so it may be worth exploring further.

**Comment by martinstarkov** [comment]
I don't necessarily know the exact cause of your issue but I noticed 2 potential reasons:

1. You seem to be using an internal fullscreen boolean flag to toggle between fullscreen and windowed. I suspect this is not recommended since there are certain window events that may switch the application between fullscreen and windowed. You should probably instead use

'''c++
int flags = SDL_GetWindowFlags();
if ((flags & SDL_WINDOW_FULLSCREEN_DESKTOP) == SDL_WINDOW_FULLSCREEN_DESKTOP) {
    // switch to windowed
} else if ((flags & (SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_FULLSCREEN)) == 0) {
    // switch to desktop fullscreen
}
'''

2. I noticed you are using the F11 key to toggle fullscreen. This key may be used by other applications to activate fullscreen. It's possible that this triggers a different application to go fullscreen somehow and in combination with the first issue it toggles your fullscreen status and it becomes out of sync.

**Comment by ShikenNuggets** [comment]
Both of those things are irrelevant, as I mentioned the issue also occurs on simply creating the window with the `SDL_WINDOW_FULLSCREEN_DESKTOP` flag.

For 1, that may be a technically better approach, though I'm not aware of anything that can cause an application to switch to/from fullscreen without it being explicitly requested. 2 just sounds impossible, but even if that was somehow a problem, it would not explain the behaviour that I described. For the sake of being thorough, I did test what you suggested with a few different hotkeys and the issue persists.

**Comment by slouken** [comment]
This is something that OpenGL drivers do automatically, and is not in control of the application. You can try a similar test using D3D or Vulkan using the SDL test programs to verify that it's not SDL. A workaround some developers do is to create a borderless window that is 1 pixel shorter than the display.

**Comment by ShikenNuggets** [comment]
> not in control of the application

And yet, changing the window style flags did seem to control it 🤷

Maybe it would make sense to only get rid of the `WS_POPUP` flag if the window also has the OpenGL flag then? I just can't figure out what `WS_POPUP` is actually meant to do to know if that's a good idea or not. But I would strongly prefer to avoid a hacky workaround if a real fix for this is possible.

**Comment by ShikenNuggets** [comment]
Wow, ok then. If what I suggested was completely stupid then fair enough, but you could at least explain why. Pretty disappointing for half of what I said to be ignored and then the issue closed with no further explanation when a possible solution was proposed.

**Comment by slouken** [comment]
The OpenGL drivers have done this intentionally, to bypass the DWM compositor and get the best graphics performance. If you want to tweak window flags to break this, that's fine, and you can submit a PR to add a hint for this if you want.

**Comment by nmlgc** [comment]
[This chance seems to have fixed the issue in SDL 3.](https://github.com/libsdl-org/SDL/commit/5da9e99da076dae56a4fbee31c774932d9928296)

**Comment by ShikenNuggets** [comment]
I still see the issue present in SDL3, with and without that change. However, curiously on both SDL2 and SDL3 the issue seems _far_ less pronounced than it was when I first encountered it 6 months ago. Before it caused a full display reset that took several seconds (and for unrelated reasons would result in my monitor not turning back on sometimes), now it just blacks out for a few frames. Maybe Windows and/or a GPU driver updated adjusted something? In any case, this has gone from being a _problem_ to a very minor inconvenience (and will go away entirely when I inevitably transition away from OpenGL), so I'm not gonna lose any more sleep over it.
