### ISSUE TITLE
Rename `SDL_BUTTON()` to `SDL_BUTTON_MASK()`

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#11056]
This macro transforms an index into a mask.
Maybe the name `SDL_BUTTON_MASK()` would fit better.
https://github.com/libsdl-org/SDL/blob/69196ab30d0b98d9b787fd583ddef7cddfbbee6c/include/SDL3/SDL_mouse.h#L121-L132

**Comment by slouken** [comment]
Fixed, thanks!
