### ISSUE TITLE
Add prefix `m` to `SDL_Event`'s mouse members

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#11059]
This is a proposal to make the fields in `SDL_Event` more consistent by adding the prefix `m` for the mouse fields, which don't have one.

Three mouse fields would get an `m` prefix.

This is what it would look like along other similarly named fileds:
```c
union SDL_Event
{
    mdevice
    motion  ==> mmotion
    button  ==> mbutton
    wheel   ==> mwheel
    
    jdevice                    
    jaxis                    
    jball                   
    jhat                      
    jbutton                      
    jbattery                       
    
    gdevice        
    gaxis          
    gbutton          
    gtouchpad            
    gsensor          
    
    pproximity
    ptouch
    pmotion
    pbutton
    paxis
};
```

**Comment by icculus** [comment]
Down to the wire on ABI changes; @slouken, you want this one?

**Comment by slouken** [comment]
I'm leaning towards no, but let me think about it for a few minutes.

**Comment by slouken** [comment]
Actually, I think not. We aren't prefixing the keyboard events with k, e.g. `kkey`, and the goal here is to make it easy to read and understand.

**Comment by andreasgrabher** [comment]
Not sure this is a good idea. Mouse like keyboard is a default input device. There are inconsistencies anyway. We would need to do get ddisplay, wwindow, kkey, tedit, ttext and so on to make this really consistent.
