### ISSUE TITLE
Rename `SDL_SetThreadPriority()` to `SDL_SetCurrentThreadPriority()`

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#11055]
`SDL_SetThreadPriority()` is the only (non-TLS) thread function, that operates on a current thread, but doesn't have the word "Current" in its name:

Here is a list of the thread functions:
```c
const char * SDL_GetThreadName      (SDL_Thread *thread);
SDL_ThreadID SDL_GetThreadID        (SDL_Thread *thread);

SDL_ThreadID SDL_GetCurrentThreadID (void);
bool         SDL_SetThreadPriority  (SDL_ThreadPriority priority);

void         SDL_WaitThread         (SDL_Thread *thread, int *status);
void         SDL_DetachThread       (SDL_Thread *thread);

void * SDL_GetTLS     (SDL_TLSID *id);
bool   SDL_SetTLS     (SDL_TLSID *id, const void *value, SDL_TLSDestructorCallback destructor);
void   SDL_CleanupTLS (void);
```
All other functions take a `SDL_Thread *` parameter and operate on that thread.
Renaming the function, would make it easy to identify, like `SDL_GetCurrentThreadID()`.

Edit:
This would also free the name for a possible future function to set the priority from outside the thread:
```c
SDL_SetThreadPriority(SDL_Thread *thread, SDL_ThreadPriority priority)
```

**Comment by icculus** [comment]
This is a good point.

**Comment by slouken** [comment]
Fixed, thanks!
