### ISSUE TITLE
Remove macro `SDL_SCANCODE_TO_KEYCODE()`

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#11057]
In `SDL_keycode.h` the macro `SDL_SCANCODE_TO_KEYCODE()` is no longer used to set the keycodes.
It is only mentioned in comments for keycodes `SDLK_CAPSLOCK` - `SDLK_ENDCALL`.
This change happened in c9cfa4688ebbce108604793f7673f9b81d0cb61a.

Here is the macro defined:
https://github.com/libsdl-org/SDL/blob/69196ab30d0b98d9b787fd583ddef7cddfbbee6c/include/SDL3/SDL_keycode.h#L49-L51
From here it is mentioned in comments:
https://github.com/libsdl-org/SDL/blob/69196ab30d0b98d9b787fd583ddef7cddfbbee6c/include/SDL3/SDL_keycode.h#L126-L131

There is only one instance, where it is actually used:
https://github.com/libsdl-org/SDL/blob/69196ab30d0b98d9b787fd583ddef7cddfbbee6c/src/video/wayland/SDL_waylandevents.c#L1186

Can this macro be removed?

---
Not so sure about `SDLK_SCANCODE_MASK`. It is used in a few places in the src files.
But for clients, I don't know how useful it can be.

**Comment by slouken** [comment]
No, we won't remove this macro. Among other things, it's useful for people to understand how the SDLK constants are constructed, and if we add new keycodes, we'll need to use it to generate the constants.
