### ISSUE TITLE
Skip CI builds for wiki bridge commits?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11066]
Is it possible to skip CI for commits with this message? "Sync SDL3 wiki -> header"

**Comment by madebr** [comment]
icculus should add `[ci skip]` to his commit message :)

**Comment by icculus** [comment]
This is done now!

**Comment by slouken** [comment]
Thanks!

**Comment by icculus** [comment]
I think for now we'll leave it at a full `skip` and see if we regret it later.  :)
