### ISSUE TITLE
3.1.3 Announcement

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11060]
I'd like to throw this up here as a draft of our announcement today for discussion:

## Announcing the SDL 3.1.3 Stable ABI Preview!

We have lots of bugs to fix before the 3.2.0 stable release, but SDL 3.0 has been battle tested by millions of people in DOTA, CS2 and Steam, and is ready for your eyes!
https://github.com/libsdl-org/SDL/releases/tag/preview-3.1.3

We have many many people to thank on the road to get here, but I'd like to call out special thanks to:
* @slouken and @icculus, lead developers
* @flibitijibibo, @thatcosmonaut, and @TheSpydog, the GPU API team
* @1bsyl, @0x1F9F1, @Kontrabant, and @Semphriss, for general development and major contributions
* @madebr, our CMake wizard and build guru
* @smcv, for words of wisdom and sanity checks
* @sezero and @Sackzement, for dotting all our i's and crossing all our t's
... and literally hundreds of other people who have contributed feedback, pull requests, and bug reports, helping make SDL what it is today.

If you're migrating from SDL2, we've put a comprehensive list of changes and migration tips here:
https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md

### Here are some of the highlights of what's new in SDL 3.0:

- [Extremely good documentation](https://wiki.libsdl.org/SDL3/APIByCategory): We've spent a ton of effort writing and revising the API reference.
- [Example programs](https://github.com/libsdl-org/SDL/tree/main/examples) to get you started, [running in your web browser](https://examples.libsdl.org/)!
- More consistent API naming conventions. Everything is named consistently across the API now, instead of different subsystems taking different approaches. Also, we've tended toward more descriptive names for things in SDL3.
- [GPU API](https://wiki.libsdl.org/SDL3/CategoryGPU): access to modern 3D rendering and GPU compute in a cross-platform way.
- [Dialog API](https://wiki.libsdl.org/SDL3/CategoryDialog): access to system file dialogs (file and folder selection UI for opening/saving).
- [Filesystem API](https://wiki.libsdl.org/SDL3/CategoryFilesystem): simple directory management and globbing, access to topic-specific user folders.
- [Storage API](https://wiki.libsdl.org/SDL3/CategoryStorage): Abstract interface to platform-specific storage.
- [Camera API](https://wiki.libsdl.org/SDL3/CategoryCamera): access to webcams.
- [Main Callbacks](https://wiki.libsdl.org/SDL3/README/main-functions#main-callbacks-in-sdl3): optionally run your program from callbacks instead of main().
- [Pen API](https://wiki.libsdl.org/SDL3/CategoryPen): access to pens (like Wacom tablets and Apple Pencil, etc).
- [Logical audio devices](https://wiki.libsdl.org/SDL3/SDL_OpenAudioDevice): different parts of an app can get their own unique audio device to use.
- [Audio streams](https://wiki.libsdl.org/SDL3/SDL_CreateAudioStream): handle buffering, converting, resampling, mixing, channel mapping, pitch, and gain. Bind to an audio device and go!
- [Default audio devices](https://wiki.libsdl.org/SDL3/SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK): SDL3 will automatically manage migrating to new physical hardware as devices are plugged in, ripped out, or changed.
- [Properties API](https://wiki.libsdl.org/SDL3/CategoryProperties): fast, flexible dictionaries of name/value pairs.
- [Process API](https://wiki.libsdl.org/SDL3/CategoryProcess): Spawn child processes and communicate with them in various ways.
- [Colorspace support](https://wiki.libsdl.org/SDL3/SDL_Colorspace): Surfaces and the renderer, etc, can manage multiple colorspaces.
- The Clipboard API [can support any data type](https://wiki.libsdl.org/SDL3/SDL_SetClipboardData) (SDL2 only handled text), and apps can provide data in multiple formats upon request in [a provided callback](https://wiki.libsdl.org/SDL3/SDL_ClipboardDataCallback).
- [Better keyboard input](https://wiki.libsdl.org/SDL3/BestKeyboardPractices), for all your keypress needs.
- [Customizable virtual keyboards](https://wiki.libsdl.org/SDL3/SDL_StartTextInputWithProperties) on iOS and Android.
- High DPI support is dramatically improved over SDL2.
- [App metadata API](https://wiki.libsdl.org/SDL3/SDL_SetAppMetadata) for letting SDL report things about your app correctly (like in the About dialog on macOS, etc).
- [Read/write thread locks](https://wiki.libsdl.org/SDL3/SDL_CreateRWLock), to let multiple threads access rarely-changing data in parallel.
- [Init State](https://wiki.libsdl.org/SDL3/SDL_InitState) to help with multiple threads that might need to initialize something on-demand without racing.

**Comment by icculus** [comment]
We'll never get everyone in the acknowledgments that deserves it, but can you throw 1bsyl in here, too? He did major subsystem work, including the camera API. 0x1F9F1 was _essential_ to the audio subsystem. Also smcv, who was absolutely a source of wisdom across all endeavors.

Otherwise, no notes, this looks good to me!

**Comment by sezero** [comment]
Is this finally the API + ABI freeze? Can we do this in sdl2-compat upon announcement?
```diff
diff --git a/src/sdl2_compat.c b/src/sdl2_compat.c
--- a/src/sdl2_compat.c
+++ b/src/sdl2_compat.c
@@ -320,3 +320,3 @@ static char loaderror[256];
 #ifndef SDL3_REQUIRED_VER
-#define SDL3_REQUIRED_VER SDL_VERSIONNUM(3,0,0)
+#define SDL3_REQUIRED_VER SDL_VERSIONNUM(3,1,3)
 #endif
```

**Comment by icculus** [comment]
Proposed text for the SDL3 frontpage on the wiki:

```
## Try it right now!

SDL3 is officially in ABI lock! We will add things to the API but not change or
remove anything, so it's safe to start porting your projects from SDL2!

Need some motivation? Here's a list of [NewFeatures](NewFeatures) that you can
enjoy today in SDL3!
```

(Yes, I know it's a lot of exclamation points.  "SDL3: WE'LL SELL YOU THE WHOLE SEAT...BUT YOU'LL ONLY NEED THE EDGE!" lol)

**Comment by sezero** [comment]
>  but can you throw 1bsyl in here, too? He did major subsystem work, including the camera API. 0x1F9F1 was _essential_ to the audio subsystem. Also smcv, who was absolutely a source of wisdom across all endeavors.

Indeed

**Comment by slouken** [comment]
> We'll never get everyone in the acknowledgments that deserves it, but can you throw 1bsyl in here, too? He did major subsystem work, including the camera API. 0x1F9F1 was _essential_ to the audio subsystem. Also smcv, who was absolutely a source of wisdom across all endeavors.

I would love to include them, and @Kontrabant too. Can you take a crack at verbiage?

**Comment by slouken** [comment]
> Is this finally the API + ABI freeze? Can we do this in sdl2-compat upon announcement?

Yes!

**Comment by slouken** [comment]
> Proposed text for the SDL3 frontpage on the wiki:
> 
> ```
> ## Try it right now!
> 
> SDL3 is officially in ABI lock! We will add things to the API but not change or
> remove anything, so it's safe to start porting your projects from SDL2!
> 
> Need some motivation? Here's a list of [NewFeatures](NewFeatures) that you can
> enjoy today in SDL3!
> ```
> 
> (Yes, I know it's a lot of exclamation points. "SDL3: WE'LL SELL YOU THE WHOLE SEAT...BUT YOU'LL ONLY NEED THE EDGE!" lol)

Proposed text changes:
```
## Try it right now!

SDL3 has officially stabilized the API and ABI, and a preview release is available at XXX. We will still be adding things to the API but not changing or removing anything, so it's safe to start porting your projects from SDL2.

Need some motivation? Here's a list of [NewFeatures](NewFeatures) that you can enjoy today in SDL3!
```

**Comment by icculus** [comment]
Needs more exclamation points.  :P

This is good, we'll go with that.

**Comment by slouken** [comment]
> > We'll never get everyone in the acknowledgments that deserves it, but can you throw 1bsyl in here, too? He did major subsystem work, including the camera API. 0x1F9F1 was _essential_ to the audio subsystem. Also smcv, who was absolutely a source of wisdom across all endeavors.
> 
> I would love to include them, and @Kontrabant too. Can you take a crack at verbiage?

Okay, I took a first pass at verbiage for those. We have more room, are there other major contributors to the SDL 3.0 code that we should add?

**Comment by icculus** [comment]
We have many many people to thank on the road to get here, but I'd like to call out special thanks to:

    @slouken and @icculus, lead developers
    @flibitijibibo, @thatcosmonaut, and @TheSpydog, the GPU API team
    @madebr, our CMake wizard and build guru
    @sezero and @Sackzement, for dotting all our i's and crossing all our t's
    @1bsyl, who jumped in to build out several subsystems
    @0x1F9F1, essential to refactoring and optimizing the audio code in ways we couldn't ourselves
    @Kontrabant, who did so much to make our Wayland support world-class
    And last but not least, @smcv, our API historian and most-trusted advisor.
    ... and literally hundreds of other people who have contributed feedback, pull requests, and bug reports, helping make SDL what it is today.


It took all my powers to not say "@Kontrabant, our Wayland wizard and windowing wunderkind" here.

**Comment by icculus** [comment]
Oh, we both did this; take whatever pieces of mine you want, if any.

**Comment by Kontrabant** [comment]
> It took all my powers to not say "@Kontrabant, our Wayland wizard and windowing wunderkind" here.

Not necessary to embellish to that extent, but thanks for the thought :)

**Comment by icculus** [comment]
Right now, if you go to wiki.libsdl.org/PAGENAME, it'll kick you over to SDL2/PAGENAME.

Is it time to flip it to SDL3/PAGENAME?

**Comment by icculus** [comment]
Also, this:

```diff
diff --git a/.wikiheaders-options b/.wikiheaders-options
index a6c85fb98..720a9de24 100644
--- a/.wikiheaders-options
+++ b/.wikiheaders-options
@@ -14,7 +14,7 @@ projecturl = https://libsdl.org/
 wikiurl = https://wiki.libsdl.org
 bugreporturl = https://github.com/libsdl-org/sdlwiki/issues/new
 warn_about_missing = 0
-wikipreamble = (This is the documentation for SDL3, which is under heavy development and the API is changing! [SDL2](https://wiki.libsdl.org/SDL2/) is the current stable version!)
+wikipreamble = (This is the documentation for SDL3, which is the current stable version. [SDL2](https://wiki.libsdl.org/SDL2/) was the previous version!)
 wikiheaderfiletext = Defined in [<SDL3/%fname%>](https://github.com/libsdl-org/SDL/blob/main/include/SDL3/%fname%)
 manpageheaderfiletext = Defined in SDL3/%fname%
 ```

Should this wait for 3.2.0, or are we going full-steam ahead?

**Comment by slouken** [comment]
> Right now, if you go to wiki.libsdl.org/PAGENAME, it'll kick you over to SDL2/PAGENAME.
> 
> Is it time to flip it to SDL3/PAGENAME?

Let's do it. :)

**Comment by slouken** [comment]
> Also, this:
> 
> ```diff
> diff --git a/.wikiheaders-options b/.wikiheaders-options
> index a6c85fb98..720a9de24 100644
> --- a/.wikiheaders-options
> +++ b/.wikiheaders-options
> @@ -14,7 +14,7 @@ projecturl = https://libsdl.org/
>  wikiurl = https://wiki.libsdl.org
>  bugreporturl = https://github.com/libsdl-org/sdlwiki/issues/new
>  warn_about_missing = 0
> -wikipreamble = (This is the documentation for SDL3, which is under heavy development and the API is changing! [SDL2](https://wiki.libsdl.org/SDL2/) is the current stable version!)
> +wikipreamble = (This is the documentation for SDL3, which is the current stable version. [SDL2](https://wiki.libsdl.org/SDL2/) was the previous version!)
>  wikiheaderfiletext = Defined in [<SDL3/%fname%>](https://github.com/libsdl-org/SDL/blob/main/include/SDL3/%fname%)
>  manpageheaderfiletext = Defined in SDL3/%fname%
> ```
> 
> Should this wait for 3.2.0, or are we going full-steam ahead?

Let's do this too, the more feedback the better!

**Comment by icculus** [comment]
Wiki is flipped to SDL3 as default!

Waiting to click Submit on the "Try it right now" section for SDL3/FrontPage until we have the download URL.

What else do we need to do at this point?

**Comment by slouken** [comment]
That's it, just waiting for final GPU documentation tweaks! :)

**Comment by icculus** [comment]
We are live! https://github.com/libsdl-org/SDL/releases/tag/preview-3.1.3

**Comment by icculus** [comment]
Btw, for those keeping track, the reference manual is now over 2000 pages. Barnes and Noble is going to be hella upset.

[SDL-reference-manual-3.1.3.pdf](https://github.com/user-attachments/files/17264868/SDL-reference-manual-3.1.3.pdf)
