### ISSUE TITLE
SDL_system.h: Hide `_XEvent`/`XEvent` `SDL_X11EventHook` and `SDL_SetX11EventHook` behind macro guards

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#11063]
These probably shouldn't be exposed on all platforms:
https://github.com/libsdl-org/SDL/blob/bd4cd34a747969f29391d031c03485fc491d017e/include/SDL3/SDL_system.h#L128-L146

**Comment by slouken** [comment]
This is explicitly defined so the API surface is available everywhere, even if it's a platform specific function.
