### ISSUE TITLE
`main` should *not* be `extern "C"`

### ISSUE THREAD

**Issue by Sirraide** [libsdl-org/SDL#11068]
I noticed this in a comment in `SDL3_main.h`:
https://github.com/libsdl-org/SDL/blob/8c3f88b49552a5273748be55b906d671a692ddff/include/SDL3/SDL_main.h#L135-L145

Rather unintuitively, this is incorrect. `main` is special: its linkage in C++ is actually implementation-defined according to [[basic.start.main]p3](https://eel.is/c++draft/basic.start.main#3):
> The linkage ([[basic.link]](https://eel.is/c++draft/basic.link)) of `main` is implementation-defined. [...] The main function shall not be declared with a [linkage-specification](https://eel.is/c++draft/dcl.link#nt:linkage-specification) ([[dcl.link]](https://eel.is/c++draft/dcl.link))[.](https://eel.is/c++draft/basic.start.main#3.sentence-5) A program that declares [...]
> - [(3.4)](https://eel.is/c++draft/basic.start.main#3.4) an entity named `main` with C language linkage (in any namespace) is ill-formed[.](https://eel.is/c++draft/basic.start.main#3.sentence-6)

Recently, Clang also started warning on this: https://godbolt.org/z/Wf9rWsTfv.

Admittedly, it *is* very likely that `main` actually has C linkage, so the code above *should* work on most platforms and with most compilers, but it would probably be better to not use `extern "C"` for `main` and just let the compiler do the right thing—that said, if there is a reason why that note is there, e.g. if you have run into a platform or compiler before that *does* require the `extern "C"`, then I would appreciate it if you would let me know so we can adjust the warning in Clang if need be ;Þ

(I also have not checked if there are other places in the codebase that declare or talk about declaring `main` as `extern "C"`.)

**Comment by Sirraide** [comment]
(Also, if `main` is actually a macro here, which I’ve seen some libraries do, and the actual `main` is *not* `extern "C"`, then feel free to disregard this of course ;Þ)

**Comment by icculus** [comment]
I _think_ this always goes through SDL_RunApp in SDL3, and never the _actual_ C entry point, but I'll double-check before closing.

**Comment by DanielGibson** [comment]
I think the `main` function that comment refers to is the one that will be renamed to `SDL_main` by [that #define in SDL_main.h](https://github.com/libsdl-org/SDL/blob/8c3f88b49552a5273748be55b906d671a692ddff/include/SDL3/SDL_main.h#L174)

In case the *actual* main() function ends up in another source file that's compiled as plain C (and will pass that function as a function pointer to `SDL_RunApp()`), C linkage is required. 
And even if the actual main is in the same source file (or also compiled as C++), I'm not 100% sure whether C linkage only affects the name mangling (that wouldn't matter) or also the calling convention (that does matter for function pointers).

---
However, probably the user doesn't have to specify that, because SDL_main.h already specifies the exact signature of `SDL_main()`: https://github.com/libsdl-org/SDL/blob/8c3f88b49552a5273748be55b906d671a692ddff/include/SDL3/SDL_main.h#L432
(it's implicitly `extern "C"` because basically the whole header is)

**Comment by Sirraide** [comment]
> I _think_ this always goes through SDL_RunApp in SDL3, and never the _actual_ C entry point, but I'll double-check before closing.

Alright, thanks, that’s fine then!

> In case the actual main() function ends up in another source file that's compiled as plain C (and will pass that function as a function pointer to SDL_RunApp()), C linkage is required.

Yeah, this is just about the fact that the actual `main()` function should not be defined in a C++ TU with `extern "C"` linkage (side note: just declaring it w/o defining it would technically be pointless in C++ as you’re actually not allowed to call `main()` either in C++, though I *think* it’s fine in C). 

If `main()` is defined in a C TU then that should be fine ofc., and likewise it makes perfect sense that `SDL_main()` needs to have C linkage if it’s called from C.

I feel like maybe the comment could mention that `main` is actually defined to be `SDL_main`, but also, I might just be the only one who was a bit confused about this ;Þ. I only brought this up is because we *did* in fact have a bunch of places that had to be fixed where we were doing `extern "C" int main()` (in libc++, I believe) when we started warning on this in Clang, so it didn’t seem to unreasonable to me that someone else might have done that too because most compilers don’t warn about this afaik.

> I'm not 100% sure whether C linkage only affects the name mangling (that wouldn't matter) or also the calling convention (that does matter for function pointers).

I don’t know what the standard says about this off the top of my head; my guess is that it’s probably just implementation-defined.

**Comment by DanielGibson** [comment]
So anyway, I think that comment linked in the first post should go:
https://github.com/libsdl-org/SDL/blob/8c3f88b49552a5273748be55b906d671a692ddff/include/SDL3/SDL_main.h#L135-L145

* When neither SDL_MAIN_NEEDED nor SDL_MAIN_AVAILABLE nor SDL_MAIN_USE_CALLBACKS is defined, `main()` will not be turned into SDL_main and thus should **not** be `extern "C"` for the reasons @Sirraide mentioned (apparently invalid in C++)
* For the case that `main()` *is* renamed to `SDL_main()`, https://github.com/libsdl-org/SDL/blob/8c3f88b49552a5273748be55b906d671a692ddff/include/SDL3/SDL_main.h#L432
  (together with the `extern "C" { .. }` that's around most of SDL_main.h) should ensure that the users (SDL_)main function will have C linkage

So IMHO that doc comment should probably look like:
```c
/**
 *  \file SDL_main.h
 *
 *  The application's main() should look like this:
 *
 *  ```c
 *  int main(int argc, char *argv[])
 *  {
 *  }
 *  ```
 */
```

@slouken according to the SDL-1.2 repo, you originally committed that comment in 2001 ([in the first commit](https://github.com/libsdl-org/SDL-1.2/blame/359adb4186fc9ad6b2351f6880d8a5ebcf3cb5ea/include/SDL_main.h#L42-L50)), do you remember why the `extern "C"` bit was in there? Just to make sure I'm not missing something here ;)
(Not that I'd expect anyone to remember anything from >20y ago, and it being the first commit in the repo doesn't mean you wrote it originally, of course - no idea where SDL's code lived before it got into CVS the repo that eventually turned into the hg and then git repo..)

**Comment by slouken** [comment]
I think in the original commit we didn't declare SDL_main separately and ran into problems when it was declared in a C++ program and called from the C SDL library. In any case that's ancient history and I've updated the documentation.

Thanks!

**Comment by DanielGibson** [comment]
Great, thanks!

I created a pull request for the simplification of including SDL_main_impl.h I talked about: https://github.com/libsdl-org/SDL/pull/11126
