### ISSUE TITLE
Enhancement request: `sdl3.pc` missing include flag `-I${includedir}/SDL3`

### ISSUE THREAD

**Issue by ankith26** [libsdl-org/SDL#11074]
`sdl2.pc` has `Cflags: -I${includedir}/SDL2`. For consistency in `sdl3.pc` I would like to have `Cflags: -I${includedir}/SDL3` so that `#include <SDL.h>` works and I don't have to change it to `#include <SDL3/SDL.h>`

**Comment by slouken** [comment]
`#include <SDL3/SDL.h>` is the recommended way of including SDL and the only way that works with macOS frameworks.
