### ISSUE TITLE
SDL 3.1.3 SDLActivity.getContentView() returns null on Android

### ISSUE THREAD

**Issue by kadirlua** [libsdl-org/SDL#11073]
Hi, thanks for SDL 3.1.3 preview release. I have been using SDL3 for a long time for my project and It's really great.  When I have upgraded to latest version of SDL3 (3.1.3), my app cannot be started properly and crashed. When I check and debug the app, I see SDLActivity.getContentView() returns null. Here's a screenshot of the issue:

![Screenshot_20241005_123020_C Media Player](https://github.com/user-attachments/assets/34b7c531-53dc-467d-9581-8eca036380a2)

I need that value because I create a new activity for my app. It was working before SDL 3.1.3.

**Comment by slouken** [comment]
Do you have local modifications to the Java files?

**Comment by kadirlua** [comment]
> Do you have local modifications to the Java files?

Opps sorry, It was my mistake. I have forgotten to upgrade my sdl java files with the latest ones. It's working now. Thanks.

**Comment by madebr** [comment]
The SDL 3.1.3 prerelease ships with a prebuilt Android aar-chive that you can use in your Android (Gradle?) project.
Using that, you don't need to add SDL sources to your repo.
