### ISSUE TITLE
SDL_AddGamepadMapping return value broken since boolean change

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#11095]
SDL_AddGamepadMapping returns an int and is documented to return 1 if the mapping was newly added, 0 if it's updating a previously set mapping, and -1 if there was an error. However commit 9ff3446f036094bc005ef119e0cf07fc9b503b8e changed the implementation code to return false instead of -1 and true instead of 0 in some codepaths, which still get converted to an int so now it never returns a failure status if the mapping string is invalid.

**Comment by slouken** [comment]
Fixed, thanks!
