### ISSUE TITLE
sdl3 vcpkg package

### ISSUE THREAD

**Issue by howprice** [libsdl-org/SDL#11096]
Congratulations on the [3.1.3 Announcement](https://github.com/libsdl-org/SDL/issues/11060)

Now that the ABI is stable, I'd love to start upgrading some of my my SDL2 projects to SDL3 . Would you be able to push for a [vcpkg](https://vcpkg.io/) package so I can easily integrate this into my projects? It has been requested a couple of times [here](https://github.com/microsoft/vcpkg/issues/37162) and [here](https://github.com/microsoft/vcpkg/issues/37162), but closed as stale.

**Comment by madebr** [comment]
I think https://github.com/microsoft/vcpkg/pull/40867 will make it :)

**Comment by howprice** [comment]
I missed that. This is excellent news thanks.
