### ISSUE TITLE
SDL3: SDL_CreateGPUDevice with SDL_GPU_SHADERFORMAT_SPIRV on Ubuntu 18 virtual machine fails

### ISSUE THREAD

**Issue by Asnkngt** [libsdl-org/SDL#11101]
I attempted to run the examples from https://github.com/TheSpydog/SDL_gpu_examples on my Ubuntu 18 virtual machine to confirm as well. Project builds, but `SDL_CreateGPUDevice(SDL_ShaderCross_GetSPIRVShaderFormats(), true, NULL)` fails.

I checked that vulkan driver is present with the following:
```
int numDrivers = SDL_GetNumGPUDrivers();
std::cout << "Num Drivers:" << numDrivers << std::endl;
for (int i = 0; i < numDrivers; ++i) {
    std::cout << SDL_GetGPUDriver(i) <<std::endl;
}
```

Output:
```
Num Drivers:1
vulkan
```

After a few debug statements, I found this error `Installed Vulkan doesn't implement the VK_KHR_surface extension`. Appears to be from `result = _this->Vulkan_LoadLibrary(_this, path);` in SDL_video.c

Installed vulkan packages:
```
sudo apt-get install vulkan-utils libvulkan1 libvulkan-dev
```

Running vulkaninfo shows the following
```
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

Cannot create Vulkan instance.
/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:768: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

Any ideas or suggestions for what I'm missing?

**Comment by Asnkngt** [comment]
Also, installing `mesa-vulkan-drivers` causes the application to segfault when attempting to load library

**Comment by thatcosmonaut** [comment]
This is almost certainly not our bug, the issue is with the virtual machine. You need to check the VM's support for this.

**Comment by Asnkngt** [comment]
Makes sense. Looks like there's some issues with the vm detecting the graphics card a therefore unable to get the drivers. Closing the issue
