### ISSUE TITLE
SDL_HINT_GAMECONTROLLER_SENSOR_FUSION most probably broken

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/SDL#11118]
Specifically the part where it's not set to 0 or 1 but "a comma separated list of USB VID/PID pairs in hexadecimal form, e.g. 0xAAAA/0xBBBB,0xCCCC/0xDDDD".

By reading some code I accidentally stumbled upon bugs, I think?
I can't really test the affected code (esp. whether that sensor fusion stuff works), but I'll describe why I think it's wrong.

### First, general problem: SDL_GetStringInteger() is broken

https://github.com/slouken/SDL/blob/596ef1ba2e8254d84c3b9b57059d366977b20bf3/src/SDL_hints.c#L235-L250
```c
int SDL_GetStringInteger(const char *value, int default_value)
{
    if (!value || !*value) {
        return default_value;
    }
    if (*value == '0' || SDL_strcasecmp(value, "false") == 0) {
        return 0;
    }
    if (*value == '1' || SDL_strcasecmp(value, "true") == 0) {
        return 1;
    }
    if (*value == '-' || SDL_isdigit(*value)) {
        return SDL_atoi(value);
    }
    return default_value;
}
```

If the string starts with '0', it'll return 0, even if it's really "0123", because `if (*value == '0' || SDL_strcasecmp(value, "false") == 0)` doesn't check whether `value[1] == '\0'`.
Same for '1': For the string "100", SDL_GetStringInteger() returns 1.

While this might be "truthy", this function looks like it's generally supposed to parse an integer (otherwise why handle '-' and call atoi() later).

### Second problem, specific to SDL_HINT_GAMECONTROLLER_SENSOR_FUSION

This is the relevant joystick code that uses that hint: https://github.com/slouken/SDL/blob/596ef1ba2e8254d84c3b9b57059d366977b20bf3/src/joystick/SDL_joystick.c#L908-L917
```c
    hint = SDL_GetHint(SDL_HINT_GAMECONTROLLER_SENSOR_FUSION);
    hint_value = SDL_GetStringInteger(hint, -1);
    if (hint_value > 0) {
        return true;
    }
    if (hint_value == 0) {
        return false;
    }

    if (hint) {
         // etc, parse the USB VID/PID string
```

If the string is "0xAAAA/0xBBBB,0xCCCC/0xDDDD", SDL_GetStringInteger() will return 0, for **two** reasons:
1. The one mentioned above, the string starts with 0
2. Even if 1. is fixed, `SDL_atoi(value);` will be returned, because `SDL_isdigit(*value)` will be true when the first char of the string is '0'.
  I think SDL_atoi() will return 0, either because '0' is the only digits it encounters before encountering a non-digit, or maybe it decides that it's an invalid string, and in case of errors at least regular `atoi()` also returns 0.

So you'll run into the `if (hint_value == 0) { return false; }` case and never reach the USB VID/PID parsing code.

**Comment by slouken** [comment]
Fixed, thanks!
