### ISSUE TITLE
Issue compiling after updating to latest source code

### ISSUE THREAD

**Issue by bjadamson** [libsdl-org/SDL#11117]
Hello all! 
I keep SDL3 in my source tree and build it as a static library it as part of my build process.  I include SDL3 using cmake. Today I updated my copy of SDL3 in-place with the latest code from this repo, and now build SDL3-static is failing in my windows test environment. The error comes from each .c file when trying to compile SDL3, this worked previously.

The error is from this include:
https://github.com/libsdl-org/SDL/blob/main/src/SDL_internal.h#L63

![image](https://github.com/user-attachments/assets/c3e6e604-925c-428b-b9ba-60dfe7b6aca4)

Looks like my build setup was relying on the source files to include build_config/ prefixes, but this commit changes this:
https://github.com/libsdl-org/SDL/commit/c298d2024a473a44e97f542064305246acaad66c

Indeed the path for build_config/ is not found by visual studio. In this screenshot `include-config-debug` is part of the set of directories visual studio will search, the final `build_config` directory (containg SDL_build_config.h) is omitted.
![image](https://github.com/user-attachments/assets/8dc8752d-29bb-451c-ae55-78670e20f3a2)

Could this be an error with the SDL3 CMakeLists.txt file, or something I am not doing correctly?

**Comment by madebr** [comment]
`C:\users\adams\projects\rrogue\build-system\Debug\source\external\SDL3\include-config-debug\build_config` should be added to SDL3-static here:
https://github.com/libsdl-org/SDL/blob/5db64300b8353029d5ad6fafd950b4f4734967e4/CMakeLists.txt#L3373

**Comment by bjadamson** [comment]
> make sure you use latest SDL3

Yeah like I said I just downloaded the latest commit today. Is this an instruction I should be following, or something your stating should be true but for whatever reason isn't applying for me? TBH I'm a little confused with your reply.

**Comment by madebr** [comment]
> Is this an instruction I should be following, or something your stating should be true but for whatever reason isn't applying for me? TBH I'm a little confused with your reply.

I meant to say it's added to the include search path at the location I posted.
You need to check why it's not present in your project.

**Comment by bjadamson** [comment]
Thanks a bunch.

To anyone in the future, it looks like I forgot to update the CMakeLists.txt file when I upgraded.
