### ISSUE TITLE
Feature request: Implement PS2 / PS3 pressure-sensitive face buttons

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#11125]
I've just had a user request this feature in a review of my Android app.

Is this possible?
Is it worthwhile?

**Comment by slouken** [comment]
Yes, it's possible. SDL exposes them as unmapped axes that you can read using the joystick API. Whether it's worthwhile is totally up to you. :)

**Comment by AntTheAlchemist** [comment]
Ah great, thanks! 

I don't suppose you'd consider adding it to the mapping?

Just a quick related question. Is there an easy way to catch unmapped input? If something comes in as a joystick axis / button, is there an easy way to identify that it's not going to also come in as a gamepad event (without diving into the mapping string and deciphering it) ? So it can be *caught* and processed. It's something I've been struggling with solving.

**Comment by slouken** [comment]
> I don't suppose you'd consider adding it to the mapping?

No, pressure sensitive buttons are basically provided by only one controller and hardly any games take advantage of them.
 
> Just a quick related question. Is there an easy way to catch unmapped input? If something comes in as a joystick axis / button, is there an easy way to identify that it's not going to also come in as a gamepad event (without diving into the mapping string and deciphering it) ? So it can be _caught_ and processed. It's something I've been struggling with solving.

You can call SDL_GetGamepadBindings() to get the pre-parsed bindings, and look for any buttons or axes that aren't listed there.

**Comment by danomatika** [comment]
I c

> You can call SDL_GetGamepadBindings() to get the pre-parsed bindings, and look for any buttons or axes that aren't listed there.

Thanks, I can confirm it works just fine to grab PS3 controller button pressure events via SDL_JOYAXISMOTION. I check if the axis is handled by the binding via `SDL_GameControllerHasAxis()` then process it when not: 

https://github.com/danomatika/joyosc/blob/main/src/joyosc/GameController.cpp#L285

**Comment by AntTheAlchemist** [comment]
> ```c++
> (SDL_GameControllerAxis)event->jaxis.axis
> ```

This is a nice solution if it'll work in all bases, but is that a good idea? Because jaxis.axis isn't a `SDL_GameControllerAxis`.
