### ISSUE TITLE
Should the MinGW binary packages contain static libraries?

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#11132]
Until now, all MinGW binary packages contain a dynamic dll and a static library.
Since the SDL project recommends using shared libraries, would it make sense to stop adding static libraries?
MinGW is the only platform for which we provide static libraries.

**Comment by slouken** [comment]
Yes.

**Comment by madebr** [comment]
Is the yes an answer to the title, or the question in my post?

**Comment by slouken** [comment]
> Since the SDL project recommends using shared libraries, would it make sense to stop adding static libraries?

Yes. :)

**Comment by madebr** [comment]
This change has been applied to all SDL3 build scripts.
