### ISSUE TITLE
iOS on macOS SDL_EVENT_FINGER_UP

### ISSUE THREAD

**Issue by kyle-sylvestre** [libsdl-org/SDL#11131]
computer: macbook air m3
macOS version: 14.6.1
iOS emulated version: 17.6
SDL commit: preview-3.1.3 e292d1f5a

I am running into a bug when I run my iOS app on a macOS. In SDL_uikitview.c, touchesBegan successfully sends a SDL_EVENT_FINGER_DOWN but the corresponding touchesEnded fails to send the SDL_EVENT_FINGER_UP. After debugging I found that the "if (event.buttonMask & SDL_BUTTON_MASK(i)) {" check is failing due to event.buttonMask being zero. This issue occurs on both tap and click using the touchpad.

https://github.com/libsdl-org/SDL/blob/8e6ead2f7ba56edafd30debdac5bc01fd463aa23/src/video/uikit/SDL_uikitview.m#L297

**Comment by slouken** [comment]
This should be fixed, can you confirm?

**Comment by slouken** [comment]
Great!
