### ISSUE TITLE
Should SDL window size queries be allowed to be called from a thread on MacOS?

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL#11138]
On MacOS, calling a window size query function from a non-main thread will produce the following warnings:
```
[NSView bounds] must be used from main thread only
[NSView convertRectToBacking] must be used from main thread only
```

 Is it possible to allow this to be worked around, like with a caching scheme? This is incredibly burdensome to work around in the GPU and Render GPU backend context. This also seems like a big footgun for clients - this restriction isn't documented anywhere and doesn't seem to be an issue on any other platform.

**Comment by thatcosmonaut** [comment]
Related: #9698

**Comment by slouken** [comment]
In general all windowing functions can only be called on the main thread. We haven't finished the threadsafety documentation for SDL_video.h, but that will be the note for almost every function in that file.

**Comment by slouken** [comment]
We don't cache the value because there are times when the underlying layer may change size and we haven't run the event loop to pick up the change.

**Comment by thatcosmonaut** [comment]
Alright.
