### ISSUE TITLE
After obtaining an SDL_Texture using SDL3's API, how can a shader effect with an outer contour be applied to this SDL_Texture?

### ISSUE THREAD

**Issue by jcy1001** [libsdl-org/SDL#11149]
After obtaining an SDL_Texture using SDL3's API, how can a shader effect with an outer contour be applied to this SDL_Texture?

**Comment by duerdak** [comment]
With the built-in renderer? Maybe render the texture in the same spot several times but scale it on x and y and set the draw color to black (or whichever color you prefer). Otherwise if you want to use a proper shader you'll need to use the GPU API.

**Comment by icculus** [comment]
Yes, the 2D API does not support shaders directly, but the GPU API does.
