### ISSUE TITLE
SDL_Delay/SDL_DelayNS provide less sleep functionality than SDL_SYS_DelayNS

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#11141]
On Windows, if I use `SDL_Delay(1)` every frame with a minimal app I get about 600 fps on my computer, with very low CPU usage. If I use `SDL_DelayNS(SDL_MS_TO_NS(1))` then I get about 850 fps with very high CPU usage (it maxes out one of my cores).

If I hack `SDL_DelayNS` to pass through to `SDL_SYS_DelayNS` without the spin loop, and then call `SDL_DelayNS(SDL_NS_PER_MS * 0.5)`, I get 980 fps with very low CPU usage.

The latter is how I'd like my app to behave - I'm not interested in calling a delay function that maxes out a core (it defeats the whole purpose of its usage in every situation where I use a delay function) and I also don't want to sleep for more time than needed when it can be avoided. It'd be nice if SDL's external API allowed for that, especially since I think it was the original purpose of `SDL_DelayNS` before it got changed.

**Comment by nfries88** [comment]
I also would prefer if SDL_DelayNS didn't do the busy-spin, but do not see it as a major problem.

In the context of the problem it seeks to solve, I would actually prefer a function which makes a reasonable effort to return *before* but as close as possible to the specified delay to one that busy-spins, as starting a frame eg 500us early is usually preferable to starting 50ns late. Implementing the busy-spinning from there, if desired, is not exactly rocket science and fairly portable logic expressable in terms of functionality SDL already exposes.

**Comment by Short3D** [comment]
This also affects SDL_WaitEvent, having a core maxed out when the event system is blocked seems sub optimal.

**Comment by slime73** [comment]
Personally I think something that has looping logic implemented on top of the internal platform sleep functions should be a separate function from SDL_Delay/SDL_DelayNS (rather than a hint or something), especially since people are wanting different types of looping logic which have their own pros and cons. But that's just my 2c.

**Comment by slouken** [comment]
> Personally I think something that has looping logic implemented on top of the internal platform sleep functions should be a separate function from SDL_Delay/SDL_DelayNS (rather than a hint or something), especially since people are wanting different types of looping logic which have their own pros and cons and use cases where a global user-set switch might do very unexpected things. But that's just my 2c.

Good point, I'm separating the functionality into two functions.

**Comment by slime73** [comment]
Thanks!

**Comment by slouken** [comment]
> Thanks!

Thanks for the feedback! :)
