### ISSUE TITLE
Mesh Shader support?

### ISSUE THREAD

**Issue by RoyAwesome** [libsdl-org/SDL#11143]
Heyoo

Are there plans to support a mesh shader api for the platforms that support them?

**Comment by thatcosmonaut** [comment]
No.

https://wiki.libsdl.org/SDL3/CategoryGPU

> The GPU API targets a feature set with a wide range of hardware support and ease of portability. It is designed so that the app won't have to branch itself by querying feature support. If you need cutting-edge features with limited hardware support, this API is probably not for you.
