### ISSUE TITLE
howto use sdl3 shader api

### ISSUE THREAD

**Issue by jcy1001** [libsdl-org/SDL#11160]
when i use sdl2 an sdl_gpu lib (SDL_gpu)[https://github.com/grimfang4/sdl-gpu]  i can use shader process my image like this 
GPU_Image* image = GPU_LoadImage("data/test3.png"); 
    Uint32 color_shader;
    GPU_ShaderBlock color_block = load_shader_program(&color_shader, "data/shaders/common.vert", "data/shaders/color.frag");
    int color_loc = GPU_GetUniformLocation(color_shader, "myColor");
        GPU_ActivateShaderProgram(color_shader, &color_block);
        update_color_shader((1+sin(t))/2, (1+sin(t+1))/2, (1+sin(t+2))/2, 1.0f, color_loc);
        GPU_Blit(image, NULL, screen, screen->w/4, screen->h/4);
        
        ,now How do I apply shaders to images in SDL3, and is there any demo code available?

**Comment by icculus** [comment]
(If it wasn't clear, grimfang4's "SDL_gpu" library is completely unrelated to SDL3's API.)

Here is some demo code for SDL3's GPU API, including using shaders:

https://github.com/TheSpydog/SDL_gpu_examples

We've been too busy to do so yet, but eventually we hope those examples will move to SDL's repo.
