### ISSUE TITLE
SDL_GetWindowProperties for `const SDL_Window*`

### ISSUE THREAD

**Issue by maia-s** [libsdl-org/SDL#11172]
I need to access a window's properties in a function that only gets a const reference to the window. I see that `SDL_GetWindowProperties` modifies the `props` field of the window if it's 0, so the window pointer can't be made const (and it's also passed to SDL_ObjectValid via CHECK_WINDOW_MAGIC which takes a writable pointer but doesn't seem to need to write to it)

Is it possible to always create properties for a window when it's created so that this function can be made const, or alternatively, could a const version of `SDL_GetWindowProperties` be added? It's ok if that returns an error if the window doesn't have any properties set.

**Comment by slouken** [comment]
None of the SDL API functions take a const SDL_Window pointer, out of curiosity why are you doing that? If you just need a unique window identifier, you can use the window ID.

**Comment by maia-s** [comment]
I want to integrate the Rust SDL 3 bindings with the `raw-window-handle` crate, which provides a generic way for other crates to work with window handles. The most natural way to do this is to implement its traits for the `SDL_Window` type. The functions of the `raw-window-handle` traits are called on `&self`, which is equivalent to a non-null pointer to const. I can't simply cast it to a mutable pointer as writing to a pointer derived from a const reference is undefined behaviour

**Comment by maia-s** [comment]
If it's an issue, I can implement the traits for a wrapper type around the properties of the window instead. Actually maybe I should do that anyway, so I can lock the properties? In general though, it'd be nice if SDL didn't require everything to be mutable.

**Comment by slouken** [comment]
What else can you do with raw-window-handle besides get properties? None of the other API functions will let you use a const window pointer.

**Comment by slouken** [comment]
The properties ID is a unique non-mutable type, and you can associate a window with its own properties if that's helpful. Maybe that's a better way to go here?

**Comment by slouken** [comment]
We don't accept a const window pointer in the API functions because frequently even the query functions may have to do some internal bookkeeping, or might have to in the future, and we don't want to bake assumptions about implementation into the API.

**Comment by maia-s** [comment]
I only need to get the properties, in order to get the native window handles that raw-window-handle wants.

Ok, I can implement it for a wrapper around the properties id instead.

**Comment by Akaricchi** [comment]
A `const` pointer wouldn't be correct for `SDL_GetWindowProperties()`, because the properties are lazily allocated on the first call to that function.
