### ISSUE TITLE
GPU: clarification on shader resource binding

### ISSUE THREAD

**Issue by radgeRayden** [libsdl-org/SDL#11187]
Coming from WebGPU (and other modern APIs like vulkan) I was expecting the gpu api to have a concept of descriptor sets / bind groups, which are pre-made, grouped shader resource bindings that you swap all at once (presumably at low cost). This may include uniform / storage buffers, samplers, texture views. It appears that this is not how this API works, and it's not well explained how it does in fact work, despite it being non-obvious due to the current status quo. What I could gather is that there are sets dedicated to each resource type (what about visibility?), and you bind your resources and refer to the order in the array for the binding index. If this is the case, I don't see clear documentation on what set index is used for each resource type, ie. how would one go about referring to these resources in eg. GLSL -> SPIR-V, which requires set/binding decorations?

(apologies if this is documented somewhere, I tried my best to read the relevant comments. And I do know there are examples but this is something that is very important to have clear documentation on).

**Comment by thatcosmonaut** [comment]
https://wiki.libsdl.org/SDL3/SDL_CreateGPUShader

**Comment by radgeRayden** [comment]
Understood, I still suggest that something be added more prominently to the header intro. I'm not sure if I should close this, but my question is answered.

**Comment by thatcosmonaut** [comment]
I can add a link to the function docs in the header intro, but there's a lot of information in this API and there's only so much we can do to help people discover it. I think the tutorial series we have planned should help with this.

**Comment by radgeRayden** [comment]
On a related note, are all these binding slots equivalent between the shader languages? I'm wondering if it will work seamlessly when using shader cross compilation.

**Comment by thatcosmonaut** [comment]
Yeah we've never had an issue. Please refer to https://github.com/libsdl-org/SDL_gpu_shadercross for how we configured the cross-compilation.

**Comment by radgeRayden** [comment]
Thank you.
