### ISSUE TITLE
SDL_GPU VULKAN_AcquireSwapchainTexture() waits on most recent frame, not least recent

### ISSUE THREAD

**Issue by MrBrixican** [libsdl-org/SDL#11186]
After having some issues not consistently acquiring a swapchain in high load scenarios using `SDL_GPU_PRESENTMODE_MAILBOX` despite waiting on the least recent (based on 3 frames in flight) command buffer's fence, I did some searching and it seems that `VULKAN_AcquireSwapchainTexture()` is waiting on the most recent frame's fence. I believe this is due to the ordering of the frameCounter increment in `VULKAN_Submit()`.

I logged the pointers for the fence in `VULKAN_Submit()` and `VULKAN_AcquireSwapchainTexture()` to confirm this behavior.

I don't know if this behavior is intentional or not, but the comments in `VULKAN_AcquireSwapchainTexture()` suggest to me that it should be waiting on the least recent frame:

```
if (windowData->presentMode == SDL_GPU_PRESENTMODE_VSYNC) {
    // In VSYNC mode, block until the least recent presented frame is done
    if (!VULKAN_WaitForFences(
        (SDL_GPURenderer *)renderer,
        true,
        &windowData->inFlightFences[windowData->frameCounter],
        1)) {
        return false;
    }
} else {
    if (!VULKAN_QueryFence(
            (SDL_GPURenderer *)renderer,
            windowData->inFlightFences[windowData->frameCounter])) {
        /*
         * In MAILBOX or IMMEDIATE mode, if the least recent fence is not signaled,
         * return true to indicate that there is no error but rendering should be skipped
         */
        return true;
    }
}
```

I've not checked the implementation in the other backends, so this same behavior may be occurring there as well.

**Comment by thatcosmonaut** [comment]
It should be waiting on the least recent frame so if it isn't doing that it's definitely a bug.

**Comment by thatcosmonaut** [comment]
I opened a PR for a patch that I think resolves this, if you wouldn't mind testing it.

**Comment by MrBrixican** [comment]
#11189 Resolves the issue. Thanks!

**Comment by thatcosmonaut** [comment]
Thanks for catching the bug!
