### ISSUE TITLE
Error handling in SDL_LoadBMP() and SDL_SaveBMP()

### ISSUE THREAD

**Issue by zturtleman** [libsdl-org/SDL#11188]
Trying to open a non-existent file using SDL_LoadBMP() reports SDL_GetError() as "Parameter 'src' is invalid".

SDL_LoadBMP_IO() sets `SDL_InvalidParamError("src");` which overrides whatever error SDL_IOFromFile() sets when it returns NULL.

https://github.com/libsdl-org/SDL/blob/b641c2a0db26127f3e379f8b92bc15feb500e242/src/video/SDL_bmp.c#L590-L593

SDL_SaveBMP_IO() has special handling for SDL_SaveBMP() to not overwrite the error if SDL_IOStream is NULL but as a result directly calling SDL_SaveBMP_IO() with NULL SDL_IOStream does not set an error.

It seems like SDL_Load/SaveBMP() should return early if SDL_IOFromFile() returns NULL and remove the special handling to skip setting an error in SDL_SaveBMP_IO().

I don't know if there is a specific desire to support  `SDL_SaveBMP_IO(SDL_IOFromFile())` format in which case `SDL_InvalidParamError("src");` could be removed from SDL_LoadBMP_IO() to report the earlier error from SDL_IOFromFile().

**Comment by slouken** [comment]
Good catch. Fixed, thanks!

**Comment by AntTheAlchemist** [comment]
SDL_LoadFile suffers from the same problem.
