### ISSUE TITLE
Inconsistent behavior of `SDL_SetWindowShape` between Windows and Mac in SDL3

### ISSUE THREAD

**Issue by benjitrosch** [libsdl-org/SDL#11199]
I've noticed that `SDL_SetWindowShape()` behaves differently between Mac and Windows. On Mac, the areas outside of the window render, but on Windows they do not.

I'm inclined to believe the Windows behavior is "correct" because of how it's described in the function:

```c
 * This sets the alpha channel of a transparent window and any fully
 * transparent areas are also transparent to mouse clicks.
```

But it's not the clearest grammar so I'm unsure.

The comment follows that "using something besides the SDL render API" means the alpha channel has to be set manually. In my case, I'm using OpenGL and filling a SDL_Surface with transparent pixels, regardless of whether the area rendered by OpenGL is *fully* transparent, which might explain the discrepancy.

**Comment by slouken** [comment]
The window shape transparency needs to be set in the shape you provide. In addition, you must also render those areas with the same transparency if you're doing your own drawing. Maybe you can suggest clearer documentation?

**Comment by benjitrosch** [comment]
@slouken thanks for the quick response. Maybe something along the lines of:

> This uses the alpha channel from the shape to set the transparency of the window, where fully transparent areas will not respond to mouse clicks.

Here are some images of the inconsistent visual behavior. In both examples, clicking in the areas not covered by the surface's opaque pixels will click through to the background as expected, but in the Windows example it also occludes those pixels. I've made a small repro for this: https://github.com/benjitrosch/SDL3-SetWindowShape-Test/blob/main/main.c

## On my Mac M1
> <img width="928" alt="Screenshot 2024-10-13 at 8 45 03 PM" src="https://github.com/user-attachments/assets/aad5a70f-2ecc-4f6d-ab52-1c848ec6998b">

## On my Windows 10
> ![image](https://github.com/user-attachments/assets/ba176533-e517-4077-a6ee-cfc6c39db146)

**Comment by slouken** [comment]
You need to do both to get consistent cross-platform results. You need to make the pixels transparent in the shape, and you also need to render them transparent yourself if you're not using the SDL 2D render API.

**Comment by benjitrosch** [comment]
@slouken Thanks for clarifying, the original comment makes a lot more sense to me now. It might help if the comment is amended a little to included what you just said:

> If you are using something besides the SDL render API, then you are responsible for setting the alpha channel of the window yourself **to get consistent cross-platform results**. There is no guarantee that transparent sections from the shape will be rendered or not.

**Comment by slouken** [comment]
Thanks for the feedback, I've clarified the documentation.
