### ISSUE TITLE
Move SDLTest_DrawString into the public API?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#11201]
This might be overkill, but there's been like 30,000 times I've written quick-and-dirty little apps that just need a little debug text, or to show an error message, etc, and it would be nice if SDL could dump that information into a rendering context.

Nothing fancy: no wordwrapping, fonts, Unicode, etc.

We already have this, in libSDLtest. It's got a tiny hardcoded font that only does ASCII that you can say "draw this C string at (x,y) on this SDL_Renderer".

It could be super-useful for this to be a real SDL API function that apps can use.

**Comment by icculus** [comment]
(Note that there is fancier functionality in that SDLtest source, for text windows and stuff, I'm just advocating for the core draw-a-basic-ugly-debug-string function here.)

**Comment by slouken** [comment]
Sure. SDL_RenderDebugText()?

**Comment by icculus** [comment]
I'm on it.

**Comment by icculus** [comment]
Is nice.

![image](https://github.com/user-attachments/assets/241f808b-89d7-4cd5-a54e-b6e83512cc4c)

**Comment by slouken** [comment]
Yeah, nearest scaling text doesn’t work so well at 150% scale.

**Comment by icculus** [comment]
I added a parameter to specify preferred scaling.

**Comment by AntTheAlchemist** [comment]
Super useful, thanks for adding it 🙏🏼 . 2 quick questions.

In `SDL_DestroyRendererWithoutFreeing()`, should `debug_char_texture_atlas` be destroyed with `SDL_DestroyTextureInternal()` instead? To keep in-line with how the rest of the method.

And is it worthwhile, with a tiny code modification, to _character_-wrap to a new line when the right of the window is reached? I know it's supposed to be raw and debuggy, but it'll add to usefulness maybe.

**Comment by KevinVitale** [comment]
Heya! 👋

I've been working on [KevinVItale/SwiftSDL](https://github.com/KevinVitale/SwiftSDL). As part of the project, I'm reimplementing several of the test benches.

Thank you for moving `SDLTest_DrawString` in to the public API.

However, it doesn't seem to be working on macOS Sequoia / 15.1. It's working as expected on Ubuntu 24.

<img width="820" alt="linux" src="https://github.com/user-attachments/assets/d471f164-892a-43f3-bee6-04aeb52f0f3e">
<img width="1028" alt="macos" src="https://github.com/user-attachments/assets/47b64736-ab8c-4bdc-9cbb-ed16634ff8a3">

---

The function is being called the same on both platforms (adopted from `testcontiroller`):

```swift
@MainActor
private func _drawGamepadWaiting(_ graphics: any Renderer) throws(SDL_Error) {
  let text = "Waiting for gamepad, press A to add a virtual controller";
  var x: Int, y: Int;
  
  x = Int((SceneLayout.sceneWidth / 2) - Double(Int(SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE) * text.count) / 2)
  y = Int((SceneLayout.sceneWidth / 2) - Double(Int(SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE)) / 2)
  
  try graphics.set(color: .black)
  try graphics(SDL_RenderDebugText, Float(x), Float(y), text)
}
```

**Comment by AntTheAlchemist** [comment]
@KevinVitale can you do a quick test and hardcode both the x & y to "0", and tell me if it works then?

**Comment by KevinVitale** [comment]
> @KevinVitale can you do a quick test and hardcode both the x & y to "0", and tell me if it works then?

Thanks for the quick follow up. Unfortunately, it still isn't working with hardcoded  zeroes, either.

<img width="1026" alt="xcode" src="https://github.com/user-attachments/assets/68199307-4568-4ca6-9943-1965482e135b">

**Comment by madebr** [comment]
Can you try building and running `examples/renderer/18-debug-text/debug-text.c`?
Does Swift correctly pass an utf-8 encoded string to SDL3? Perhaps you can add a bit of printf-style debugging inside `SDL_RenderDebugText`?

**Comment by icculus** [comment]
Could be GPU+Metal backends. GPU+Vulkan and OpenGL both worked for me on Linux.

Can you add this to the very start of the program and see what happens?

```c
SDL_SetHint(SDL_HINT_RENDER_DRIVER, "OpenGL");
```

**Comment by KevinVitale** [comment]
> Can you add this to the very start of the program and see what happens?
> 
> ```c
> SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl");
> ```

This seemingly had no affect.

---

> Can you try building and running `examples/renderer/18-debug-text/debug-text.c`? Does Swift correctly pass an utf-8 encoded string to SDL3? Perhaps you can add a bit of printf-style debugging inside `SDL_RenderDebugText`?

This was helpful, and the example rendered correctly. So I coped the debug code into my own, which also rendered as expected.

The issue may be with Swift itself, which (ironically) is behaving as intended on Linux, but not on macOS. So, while I'm no longer blocked (**thanks!**), I'm definitely left with more questions than answers.
