### ISSUE TITLE
Steam Deck HIDAPI controller detected even when running with Steam Input

### ISSUE THREAD

**Issue by Akaricchi** [libsdl-org/SDL#11215]
See taisei-project/taisei#388

I don't own a Steam Deck (sad face) so I can't reproduce the issue myself.

**Comment by mausimus** [comment]
I can reproduce this on 3.1.3 with my own project on a Steam Deck:

Launching the game through Steam shows one gamepad and works fine:
1. Steam Deck Controller

Launching standalone outside of Steam, SDL enumerates two gamepads and I get double inputs:
1. Steam Deck
2. Steam Virtual Gamepad

Note slightly different names of 1. between scenarios

**Comment by slouken** [comment]
This is fixed and is queued up for the next SDL2 update. Feel free to try out the latest main/SDL2 code and verify it there.
