### ISSUE TITLE
Building with MSYS: Cannot file EGL/egl.h

### ISSUE THREAD

**Issue by eliemichel** [libsdl-org/SDL#11216]
When I try to build SDL3 using MSYS on Windows, I get the following error:

```
[ 32%] Building C object _deps/sdl2-build/CMakeFiles/SDL3-shared.dir/src/render/direct3d/SDL_render_d3d.c.obj
In file included from D:/a/sdl3webgpu/sdl3webgpu/build/_deps/sdl2-src/src/video/SDL_egl_c.h:28,
                 from D:/a/sdl3webgpu/sdl3webgpu/build/_deps/sdl2-src/src/video/windows/SDL_windowsopengles.h:29,
                 from D:/a/sdl3webgpu/sdl3webgpu/build/_deps/sdl2-src/src/video/windows/SDL_windowsvideo.h:58,
                 from D:/a/sdl3webgpu/sdl3webgpu/build/_deps/sdl2-src/src/render/direct3d/SDL_render_d3d.c:29:
D:/a/sdl3webgpu/sdl3webgpu/build/_deps/sdl2-src/include/SDL3/SDL_egl.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

I tried to install the package `egl-headers`, but it did not change the result.

Example of erroneous run with full log: https://github.com/eliemichel/sdl3webgpu/actions/runs/11341309283/job/31539336851

**Comment by slouken** [comment]
@madebr, shouldn't we be detecting egl.h?

**Comment by madebr** [comment]
@eliemichel 
Can you try https://github.com/libsdl-org/SDL/pull/11244?

**Comment by eliemichel** [comment]
After further investigation, it seems I had messed up with my CI config, it was trying to run a MSYS build from a non-MSYS bash! Fixing that fixed my issue.

@madebr Your PR does not fix the case where I misuse the API ([example run](https://github.com/eliemichel/sdl3webgpu/actions/runs/11394143148/job/31703851340)), but it's not a relevant case anyways! Sorry for the trouble and thank you for taking the time of opening this PR for testing.
