### ISSUE TITLE
SDL3 Proposal: Add `SDL_AppTickLogic()` and rename `SDL_AppIterate()` to `SDL_AppPresentFrame()`

### ISSUE THREAD

**Issue by nightmareci** [libsdl-org/SDL#11210]
Right now, with the current `SDL_App*` callbacks, it's pretty awkward to run explicitly paced game logic "the right way", that is, not within `SDL_AppIterate()`; the snake game example shows "the right way" to do it in the current structure. My proposal is to add a new callback, `SDL_AppTickLogic()`, and rename `SDL_AppIterate()` to `SDL_AppPresentFrame()`, so it's clear what duties each callback must serve.

The documentation could note that audio playback should only be initiated in `SDL_AppTickLogic()`, never `SDL_AppPresentFrame()`.

Here's my initial idea for the logic tick callback, for the snake game example. It's more or less like the timer callback, in terms of how SDL paces out calls of it:
```c
#define STEP_RATE_IN_NANOSECONDS (STEP_RATE_IN_MILLISECONDS * SDL_NS_PER_MS)
SDL_AppResult SDL_AppTickLogic(void *appstate, Uint64 *interval)
{
    SnakeContext *ctx = &((AppState *)appstate)->snake_ctx;
    snake_step(ctx);

    static bool first = true;
    static Uint64 last;
    static Uint64 start;
    static Sint64 accumulated;

    if (first) {
        first = false;
        start = SDL_GetTicksNS();
        accumulated = 0;
    } else {
	last = start;
	start = SDL_GetTicksNS();
	const Sint64 next_accumulated = accumulated + (start - last) - STEP_RATE_IN_NANOSECONDS;
        if (next_accumulated >= STEP_RATE_IN_NANOSECONDS || (next_accumulated < 0 && -next_accumulated >= STEP_RATE_IN_NANOSECONDS)) {
            accumulated = 0;
        } else {
            accumulated = next_accumulated;
        }
    }

    *interval = STEP_RATE_IN_NANOSECONDS - accumulated;
    return SDL_APP_CONTINUE;
}
```
Though maybe SDL should implement that fixed timestepping logic, not the user code. Like the timer callback, the user would be required to return an interval value every call.

To me, this seems a lot cleaner and easier to use than the snake game example's "hack" of generating user events in a timer thread. It would also mean the snake game example, using this new structure, could run on platforms without threading support.

**Comment by slouken** [comment]
We are already ABI locked, so we can't remove the existing callback, but adding @icculus for his opinions.

**Comment by icculus** [comment]
The correct thing to do is run your game logic and render a frame in SDL_AppIterate. The snake game is currently overcomplicating this with a timer callback, imho.

**Comment by slouken** [comment]
> The snake game is currently overcomplicating this with a timer callback, imho.

We should fix that so people don't trip over it.

**Comment by nightmareci** [comment]
The issue with putting logic in `SDL_AppIterate()` is you don't get *realtime* desired pacing, at best you can update once the time has passed a deadline, since the iteration function can be called at any rate, not the pace your logic wants.

**Comment by icculus** [comment]
Example game is updated to not use a timer. I don't think we'll be changing the way the main callbacks work, so I'm calling this done for now.

**Comment by slouken** [comment]
@nightmareci, you can set SDL_HINT_MAIN_CALLBACK_RATE to "0" to run as fast as possible, and do any kind of frame pacing you want in the appiterate callback.

**Comment by nightmareci** [comment]
@slouken, if that behavior is *guaranteed* for all platforms, shouldn't that be documented as a proper usage?
