### ISSUE TITLE
SDL gpu querying buffer allocation size

### ISSUE THREAD

**Issue by jsoulier** [libsdl-org/SDL#11222]
Not an issue more a question.

Is there a way to query GPU buffer allocation sizes? For dynamic resources I often have to check if new data exceeds the size of the old buffer before swapping. I have in my code:

```c
typedef struct
{
    SDL_GPUBuffer* handle;
    uint32_t size;
}
my_buf_t;
```

It would be nice to just pass around `SDL_GPUBuffer` handles directly though. It seems like all the GPU backends support querying the buffer size (either through the allocator or just stored in the xxxBuffer object itself).

Would this ever get added? If yes, happy to submit prototype PR

Thanks!

**Comment by thatcosmonaut** [comment]
You as the client define the size when creating the buffer and it never changes, so adding a query for this is just pointless round-tripping.

**Comment by jsoulier** [comment]
> You as the client define the size when creating the buffer and it never changes, so adding a query for this is just pointless round-tripping.

I understand all buffers are static, but I imagine people are often going to delete/create a buffer when they find out the out one isn't big enough anymore. I'm only suggesting another function to expose the buffer size stored internally so that users don't have to store it themselves.

**Comment by thatcosmonaut** [comment]
If you need the size then just store it. There's no point in adding a query function for a value that is static and passed in at creation time.
