### ISSUE TITLE
Remove SDL_build_config_emscripten.h?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11236]
Are we still building emscripten outside of CMake?

**Comment by icculus** [comment]
I'm not, and I can't think of a reason why someone would want to.

Do we need it if someone just dumps all the source code into a different project and clicks "compile"? (Does that even work?!)

**Comment by sezero** [comment]
Removing should be safe.

**Comment by sezero** [comment]
The only remaining oddball is SDL_build_config_ngage.h I guess.

**Comment by madebr** [comment]
I was looking up how emscripten builds the SDL libraries, and it turns out they are using `SDL_build_config_emscripten.h`.
https://github.com/emscripten-core/emscripten/blob/main/tools/ports/sdl2.py

**Comment by slouken** [comment]
> I was looking up how emscripten builds the SDL libraries, and it turns out they are using `SDL_build_config_emscripten.h`. https://github.com/emscripten-core/emscripten/blob/main/tools/ports/sdl2.py

Is that going to continue with SDL3?

**Comment by madebr** [comment]
I dunno.
@sbc10 Do you know?

**Comment by sbc100** [comment]
We (emscripten) don't use cmake to build any of our ports (since we don't want make cmake a hard dependency), so we basically roll our own builds.

I certainly think it would be nicer to keep this config file upstream like this but ultimately we instead store it downstream ourselves if we must.  Something like this: https://github.com/emscripten-core/emscripten/blob/b53978ee3f540dc74761eba127aa7f1b8761a125/tools/ports/libjpeg.py#L44-L62

**Comment by slouken** [comment]
@madebr, can we save the emscripten CI generated header in the build_config directory for the emscripten port? My only concern would be whether our CI environment matches upstream emscripten build environment.

@sbc100, do you have a preference here? It's probably safest if you keep things in sync on your end, but we can do a best effort here too.

**Comment by sbc100** [comment]
I don't have a strong preference.

**Comment by madebr** [comment]
> @madebr, can we save the emscripten CI generated header in the build_config directory for the emscripten port? My only concern would be whether our CI environment matches upstream emscripten build environment.

https://github.com/libsdl-org/SDL/pull/11326 adds those.
For reference, [this](SDL_build_config.zip](https://github.com/user-attachments/files/17513481/SDL_build_config.zip) is the current `SDL_build_config.h` generated by emscripten on ci.

**Comment by sbc100** [comment]
Thanks!  That will be very useful when we update to SDL3.

**Comment by madebr** [comment]
Multithreaded emscripten is currently not part of the test matrix.
Should it be added?

**Comment by icculus** [comment]
> Multithreaded emscripten is currently not part of the test matrix.

Putting that in a separate issue for later.

**Comment by slouken** [comment]
@sbc100, we'll go ahead and keep the CMake build configuration and you're welcome to have a static build config header for your build processes.
