### ISSUE TITLE
Remove N-Gage support?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11243]
It's been 2 years with no N-Gage activity, should we remove it for the 3.2.0 release? We can always re-add it later, if someone is interested in maintaining it.

@mupfdev, thoughts?

**Comment by icculus** [comment]
The problem before was they needed to get a newer GCC build that could handle variable declarations in the middle of a scope, since we changed policy for SDL3. There was some effort on this--there was overlap between a GCC release that supported this and _also_ hadn't yet removed the n-gage object format, but I don't know if they ever got it working.

**Comment by mupfdev** [comment]
The problem remains unresolved. Unfortunately. @FtZPetruska has put a lot of work into this. If no one else has an idea on how to make this work, I'm fine with removing support for the time being.

Details:

https://github.com/ngagesdk/ngage-toolchain/issues/9#issuecomment-1620867826

**Comment by slouken** [comment]
Okay, let's pull it for now.

**Comment by I-asked** [comment]
Hi there! Me and my friend @technicaljicama are currently working on a new Symbian toolchain, targeting S^3 and later devices, here: https://github.com/SymbianRevive/ERA
We support Linux natively and we also have working GCC 12 along with custom SBSv2 configs suitable for the compiler. We are most definitely interested in bringing SDL3 to Symbian^3 (call it SDL^3 :joy:).
While this does not cover ngages (which unfortunately sport very old versions of Symbian, with no GPU acceleration, less sophisticated system API's, less memory, etc.), Symbian phones such as the Nokia E7 are much more powerful (perhaps on par with consoles such as PS Vita[?]), support more API's (up to C++11 STL with some C++14 features) and much more.
Best of all, parts of SymC++ code can be shared between the SymbianRevive toolchain (ERA) and the ngage toolchain.
If you still consider Symbian support, we could put ngage on proverbial life support along with our modernized effort.

**Comment by icculus** [comment]
If there's a toolchain to unblock the port, we can keep it (and add newer Symbian, too, if someone wants to take a run at it!).

**Comment by icculus** [comment]
I'm going to pull the ngage support for now, but we can revert that once a toolchain is up and running. We'll also accept a general Symbian port in SDL3 when it's ready to go.

ngage support will continue to live in SDL2, unconditionally, as that source tree still works with the existing compilers.

**Comment by mupfdev** [comment]
I will be happy to take another look at the topic and make a PR in due course.  The problem is basically not the compiler, just the abandoned support for ARM PE executables.

Thank you for your continued interest in our work - even though it is such a niche. It's appreciated!

**Comment by icculus** [comment]
Definitely keep us posted, we will happily revert the removal when you are ready to move forward again!
