### ISSUE TITLE
#11228 still exists after update to latest git main branch.

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#11242]
> @sandsc: please confirm that current git main branch behaves in your environment
after delete cache and reconfigure cmake, issue still exists.
![image](https://github.com/user-attachments/assets/bf7ae5e0-9df8-440d-b023-9c2f4d02899b)
>[cmake] -- SDL3 was configured with the following options:
[cmake] -- 
[cmake] -- Platform: Windows-10.0.19045
[cmake] -- 64-bit:   TRUE
[cmake] -- Compiler:  MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
[cmake] -- Revision: SDL3-preview-3.1.3-180-gdd955332a
[cmake] -- Vendor:   
[cmake] -- 
[cmake] -- Subsystems:
[cmake] --   Audio:    OFF
[cmake] --   Video:    ON
[cmake] --   GPU:      ON
[cmake] --   Render:   ON
[cmake] --   Camera:   ON
[cmake] --   Joystick: OFF
[cmake] --   Haptic:   OFF
[cmake] --   Hidapi:   OFF
[cmake] --   Power:    OFF
[cmake] --   Sensor:   OFF
[cmake] --   Dialog:   ON
[cmake] -- 
[cmake] -- Options:
[cmake] --   SDL_ALSA                    (Wanted: OFF): OFF
[cmake] --   SDL_ALSA_SHARED             (Wanted: OFF): OFF
[cmake] --   SDL_ALTIVEC                 (Wanted: OFF): OFF
[cmake] --   SDL_ARMNEON                 (Wanted: OFF): OFF
[cmake] --   SDL_ARMSIMD                 (Wanted: OFF): OFF
[cmake] --   SDL_ASAN                    (Wanted: OFF): OFF
[cmake] --   SDL_ASSEMBLY                (Wanted: ON): ON
[cmake] --   SDL_ASSERTIONS              (Wanted: auto): auto
[cmake] --   SDL_AVX                     (Wanted: ON): ON
[cmake] --   SDL_AVX2                    (Wanted: ON): ON
[cmake] --   SDL_AVX512F                 (Wanted: ON): ON
[cmake] --   SDL_BACKGROUNDING_SIGNAL    (Wanted: OFF): OFF
[cmake] --   SDL_CCACHE                  (Wanted: OFF): OFF
[cmake] --   SDL_CLANG_TIDY              (Wanted: OFF): OFF
[cmake] --   SDL_CLOCK_GETTIME           (Wanted: OFF): OFF
[cmake] --   SDL_COCOA                   (Wanted: OFF): OFF
[cmake] --   SDL_DBUS                    (Wanted: OFF): OFF
[cmake] --   SDL_DIRECTX                 (Wanted: OFF): OFF
[cmake] --   SDL_DISABLE_INSTALL         (Wanted: ON): OFF
[cmake] --   SDL_DISABLE_UNINSTALL       (Wanted: ON): OFF
[cmake] --   SDL_DISKAUDIO               (Wanted: OFF): OFF
[cmake] --   SDL_DUMMYAUDIO              (Wanted: OFF): OFF
[cmake] --   SDL_DUMMYCAMERA             (Wanted: ON): ON
[cmake] --   SDL_DUMMYVIDEO              (Wanted: ON): ON
[cmake] --   SDL_EXAMPLES                (Wanted: OFF): OFF
[cmake] --   SDL_EXAMPLES_LINK_SHARED    (Wanted: OFF): OFF
[cmake] --   SDL_FOREGROUNDING_SIGNAL    (Wanted: OFF): OFF
[cmake] --   SDL_GCC_ATOMICS             (Wanted: OFF): OFF
[cmake] --   SDL_GPU_DXVK                (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI                  (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI_JOYSTICK         (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI_LIBUSB           (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI_LIBUSB_SHARED    (Wanted: OFF): OFF
[cmake] --   SDL_IBUS                    (Wanted: OFF): OFF
[cmake] --   SDL_INSTALL_TESTS           (Wanted: OFF): OFF
[cmake] --   SDL_JACK                    (Wanted: OFF): OFF
[cmake] --   SDL_JACK_SHARED             (Wanted: OFF): OFF
[cmake] --   SDL_KMSDRM                  (Wanted: OFF): OFF
[cmake] --   SDL_KMSDRM_SHARED           (Wanted: OFF): OFF
[cmake] --   SDL_LASX                    (Wanted: OFF): OFF
[cmake] --   SDL_LIBC                    (Wanted: ON): ON
[cmake] --   SDL_LIBICONV                (Wanted: OFF): OFF
[cmake] --   SDL_LIBUDEV                 (Wanted: ON): OFF
[cmake] --   SDL_LSX                     (Wanted: OFF): OFF
[cmake] --   SDL_METAL                   (Wanted: OFF): OFF
[cmake] --   SDL_MMX                     (Wanted: ON): OFF
[cmake] --   SDL_OFFSCREEN               (Wanted: ON): ON
[cmake] --   SDL_OPENGL                  (Wanted: ON): ON
[cmake] --   SDL_OPENGLES                (Wanted: ON): ON
[cmake] --   SDL_OSS                     (Wanted: OFF): OFF
[cmake] --   SDL_PIPEWIRE                (Wanted: OFF): OFF
[cmake] --   SDL_PIPEWIRE_SHARED         (Wanted: OFF): OFF
[cmake] --   SDL_PTHREADS                (Wanted: OFF): OFF
[cmake] --   SDL_PTHREADS_SEM            (Wanted: OFF): OFF
[cmake] --   SDL_PULSEAUDIO              (Wanted: OFF): OFF
[cmake] --   SDL_PULSEAUDIO_SHARED       (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_D3D              (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_D3D11            (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_D3D12            (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_GPU              (Wanted: ON): ON
[cmake] --   SDL_RENDER_METAL            (Wanted: ON): OFF
[cmake] --   SDL_RENDER_VULKAN           (Wanted: OFF): OFF
[cmake] --   SDL_ROCKCHIP                (Wanted: OFF): OFF
[cmake] --   SDL_RPATH                   (Wanted: OFF): OFF
[cmake] --   SDL_RPI                     (Wanted: OFF): OFF
[cmake] --   SDL_SNDIO                   (Wanted: OFF): OFF
[cmake] --   SDL_SNDIO_SHARED            (Wanted: OFF): OFF
[cmake] --   SDL_SSE                     (Wanted: ON): ON
[cmake] --   SDL_SSE2                    (Wanted: ON): ON
[cmake] --   SDL_SSE3                    (Wanted: ON): ON
[cmake] --   SDL_SSE4_1                  (Wanted: ON): ON
[cmake] --   SDL_SSE4_2                  (Wanted: ON): ON
[cmake] --   SDL_SYSTEM_ICONV            (Wanted: OFF): OFF
[cmake] --   SDL_TESTS                   (Wanted: OFF): OFF
[cmake] --   SDL_TESTS_LINK_SHARED       (Wanted: OFF): OFF
[cmake] --   SDL_VIRTUAL_JOYSTICK        (Wanted: OFF): OFF
[cmake] --   SDL_VIVANTE                 (Wanted: OFF): OFF
[cmake] --   SDL_VULKAN                  (Wanted: OFF): OFF
[cmake] --   SDL_WASAPI                  (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND                 (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND_LIBDECOR        (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND_LIBDECOR_SHARED (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND_SHARED          (Wanted: OFF): OFF
[cmake] --   SDL_X11                     (Wanted: OFF): OFF
[cmake] --   SDL_X11_SHARED              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XCURSOR             (Wanted: OFF): OFF
[cmake] --   SDL_X11_XDBE                (Wanted: OFF): OFF
[cmake] --   SDL_X11_XFIXES              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XINPUT              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XRANDR              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XSCRNSAVER          (Wanted: OFF): OFF
[cmake] --   SDL_X11_XSHAPE              (Wanted: OFF): OFF
[cmake] --   SDL_XINPUT                  (Wanted: ON): OFF

_Originally posted by @sandsc in https://github.com/libsdl-org/SDL/issues/11228#issuecomment-2418325104_

**Comment by sandsc** [comment]
Why is this issue closed and is there a solution？

**Comment by sezero** [comment]
> Why is this issue closed and is there a solution？

Because you already posted this message as a follow-up in #11228, and #11228 is reopened and discussion is continued there. Please answer the questions raised in #11228.

**Comment by sandsc** [comment]
> > Why is this issue closed and is there a solution？
> 
> Because you already posted this message as a follow-up in #11228, and #11228 is reopened and discussion is continued there. Please answer the questions raised in #11228.

oh, sorry, I thought that issue had been closed.
