### ISSUE TITLE
Cannot infer default ASAN libraries on Windows

### ISSUE THREAD

**Issue by kamenkitanov** [libsdl-org/SDL#11262]
When building SDL2 as a shared library on Windows with MSVC (17.11.5) and ASAN turned on for all targets via:
`add_compile_options(/fsanitize=address)`

I get the following linking error when building SDL:
`LINK : fatal error LNK1394: cannot infer default ASAN libraries; please specify them on the link command line`

This seems to be caused by the /NODEFAULTLIB switch that SDL uses by default when building as a shared library. To workaround the problem, I can set "SDL_LIBC" option to ON, which causes SDL to link to MSVC's standard library.

Should SDL check for /fsanitize=address with MSVC and if detected link to the standard library?

**Comment by slouken** [comment]
Interesting question. @madebr, what do you think?

**Comment by madebr** [comment]
It's not common to use [properties](https://cmake.org/cmake/help/latest/prop_dir/COMPILE_OPTIONS.html) when doing compile checks.
Because `COMPILE_OPTIONS` can use generator expressions, they cannot be (reliably) expanded during configure time.

I'd say this is a configuration error, and you must enable `-DSDL_LIBC` when you want to use libc==asan.

Our CMake script has a `SDL_ASAN` option, that checks before adding the `-fsanitize=` options.
The downside of our `SDL_ASAN` is that it enables extra sanitizers (boo,bounds,enum,undefined,leak,...)

**Comment by slouken** [comment]
Sounds good. Where can we document this?

**Comment by kamenkitanov** [comment]
@madebr Thanks for the explanation.
SDL_ASAN doesn't seem to do anything on Windows/MSVC, at least for SDL2. The compiler checks are returning false.
Also, should SDL_ASAN imply that SDL should link to the standard library with MSVC?

**Comment by madebr** [comment]
@kamenkitanov
Perhaps you can still use the address sanitizer with `-DSDL_LIBC=OFF`, you only need to explicitly add their libraries to the linker.
About the failing `SDL_ASAN` tests, can you look in the configure logs why these are failing? 

> Also, should SDL_ASAN imply that SDL should link to the standard library with MSVC?

I think so.  The address sanitizer must hook known functions. If you're using fully custom allocation functions, the sanitizer cannot add it checks.

See https://github.com/libsdl-org/SDL/pull/11265

**Comment by kamenkitanov** [comment]
> Perhaps you can still use the address sanitizer with -DSDL_LIBC=OFF, you only need to explicitly add their libraries to the linker.

You are correct - as the error itself implies you can link in the ASAN libs manually without SDL linking to libc. But it's a cumbersome solution, since you need to specify their full VS-version dependant path and handle CRT differences and architecture:
https://devblogs.microsoft.com/cppblog/asan-for-windows-x64-and-debug-build-support/

> About the failing SDL_ASAN tests, can you look in the configure logs why these are failing?

This is a relevant exempt of the configure log:

```
variable: "HAS_CXX_FLAG_address"
.....
LINK Pass 1: command "C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_a6bd1.dir\\src.cxx.obj /out:cmTC_a6bd1.exe /implib:cmTC_a6bd1.lib /pdb:cmTC_a6bd1.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console -fsanitize=address asan.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_a6bd1.dir/intermediate.manifest CMakeFiles\\cmTC_a6bd1.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : warning LNK4044: unrecognized option '/fsanitize=address'; ignored\x0d
LINK : fatal error LNK1104: cannot open file 'asan.lib'\x0d
ninja: build stopped: subcommand failed.
```
