### ISSUE TITLE
Identifying the correct shared object file via cmake for a Linux app bundle

### ISSUE THREAD

**Issue by DctrNoob** [libsdl-org/SDL#11260]
I have included SDL3 as a git submodule and build it as a shared lib. After the build I want to copy the lib to my game folder which, according to the cmake readme, should be done using the cmake generator expression `$<TARGET_FILE:SDL3::SDL3-shared>`. 

On Linux, however, this identifies the version specific .so file `libSDL3.so.0.1.3` which, for some reason, is not the library referenced by the executable. This would be `libSDL3.so.0` which exists as a symlink in the SDL build folder.

I was able to solve the problem by using the cmake generator expression `$<TARGET_SONAME_FILE:SDL3::SDL3-shared>` instead which, unfortunately, doesn't work on all platforms (e.g. Windows).

Tbh. I am not sure what the correct/best solution to this problem would be. Is it really the updated generator expression? Or is there a deeper root cause like some rpath-related stuff wrt. the executable?

Either way, the current proposal by the cmake readme didn't work for me on Linux and I'd be happy to raise a PR wrt. the cmake readme if you would like.

**Comment by madebr** [comment]
In general, you don't need to copy .so files around because there are runpaths (rpath) on (most) unix systems.
Even if you copy the `libSDL3.so.0.*` to your build folder, you application will still load the original one (unless you enable [`SKIP_BUILD_RPATH`](https://cmake.org/cmake/help/latest/prop_tgt/SKIP_BUILD_RPATH.html)).

When you want to create a distributable that includes your application and dependencies, I think using `install(TARGETS)`, eventually combined with `RUNTIME_DEPENDENCIES` or `RUNTIME_DEPENDENCY_SET`, is more appropriate.

About the documentation, I would mention `$<TARGET_SONAME_FILE>` (and explain why it exists) but not provide an example as it is generally not needed.
Your pr would be welcomed :)

**Comment by DctrNoob** [comment]
Thanks for the feedback. You're right and I should have been more specific!

For my day-to-day dev build I indeed don't need to copy the dynamic libs around - everything works out of the box. My problem description was about an app bundle for distribution (a Linux build for Steam). And in that case just using `$<TARGET_FILE:SDL3::SDL3-shared>` didn't work.

Since you're mentioning the rpath settings, this is how I have configured the rpath for the Linux app bundle in cmake:
```
set(CMAKE_BUILD_RPATH "$ORIGIN")
set(CMAKE_INSTALL_RPATH "$ORIGIN")
set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
```

Afaik this is the correct config if I want my dynamic libs to live next to the executable. But my experience in that regard is very limited and I'd be happy to learn about a cleaner way to achieve the same thing. And one that is maybe compatible to the readme suggestion of using `$<TARGET_FILE:SDL3::SDL3-shared>`.

Best regards,
Thomas

**Comment by madebr** [comment]
Copying the dll using `$<TARGET_FILE>` on Windows is only meant for development purposes, not for creating distributables.
Our suggestion might also not be the correct one. When on Windows, I configure my projects with [`-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=%cd%/bin`](https://cmake.org/cmake/help/latest/variable/CMAKE_RUNTIME_OUTPUT_DIRECTORY.html), which makes the problem go away  completely.

There is [`CMAKE_LIBRARY_OUTPUT_DIRECTORY`](https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_OUTPUT_DIRECTORY.html) for unix.

**Comment by madebr** [comment]
Can you have a look at https://github.com/libsdl-org/SDL/pull/11265?

**Comment by DctrNoob** [comment]
Thanks for the PR and also thanks for the suggestion regarding the RUNTIME and LIBRARY output directories. Gonna check these out.
