### ISSUE TITLE
Blit2101010toN and BlitNto2101010 appear to be unused

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#11271]
These functions are selected in `SDL_CalculateBlitN`, however the check preceding the call to it in `SDL_CalculateBlit` suggests that `SDL_Blit_Slow` will always be used instead.

```
        } else if (SDL_ISPIXELFORMAT_10BIT(surface->format) ||
                   SDL_ISPIXELFORMAT_10BIT(dst->format)) {
            blit = SDL_Blit_Slow;
        }
```

**Comment by slouken** [comment]
You're right. Removed, thanks!
