### ISSUE TITLE
`SDL_EVENT_DID_ENTER_FOREGROUND`, and similar events are no longer being seen in `main()` with `SDL_PumpEvents()`

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#11287]
This used to work and has worked for years, so a recent change within the last month or few months has caused this.
I understand "This event must be handled in a callback set with SDL_AddEventWatch().", but, these events used to come through without the need for a callback, so this behaviour change would potentially break any SDL app that relied on these events coming through with all the other events.
These events are affected:
```
SDL_EVENT_WILL_ENTER_BACKGROUND
SDL_EVENT_DID_ENTER_BACKGROUND
SDL_EVENT_WILL_ENTER_FOREGROUND
SDL_EVENT_DID_ENTER_FOREGROUND
SDL_EVENT_LOW_MEMORY
```

**Comment by slouken** [comment]
Yes, this is a behavior change in SDL3 to make handling more consistent across mobile platforms.
