### ISSUE TITLE
GPU reset handling?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11288]
How is device reset handled in the GPU driver? The renderer sends a SDL_EVENT_RENDER_DEVICE_RESET event, and I'm about to add an SDL_EVENT_RENDER_DEVICE_LOST event. It looks like recovering from device lost is not possible on NVIDIA with Vulkan drivers, but works on D3D11 and D3D12.

**Comment by thatcosmonaut** [comment]
Device loss is a catastrophic error that will never occur unless invalid commands are submitted. We don't handle it at all except to report errors before the inevitable crash. Device reset also isn't really a concept in modern APIs as far as I know.

**Comment by slouken** [comment]
It happens during driver updates and GPU hot-swaps.

**Comment by slouken** [comment]
> We don't handle it at all except to report errors before the inevitable crash.

This is probably sufficient for now, thanks for clarifying.
