### ISSUE TITLE
Undefined Reference to specific functions (SDL3).

### ISSUE THREAD

**Issue by CatAClock** [libsdl-org/SDL#11283]
I don't know if I am missing something or not.

# computer specs

- Debian GNU/Linux 12
- KDE Plasma
- X11
- Kernal version 6.1.0
- Nvidia graphics card, Intel CPU

# Steps to get issue

1. download 3.1.3 from releases
2. use command `sudo cmake -S . -B build && sudo cmake --build build && sudo cmake --install build`
3. have it installed successfully into /usr/local/include (as far as i'm aware).
4. Make a project with `#include <SDL3/SDL.h>`. [This is my project](https://codeberg.org/Crowded-Games/SDL-Library).
5. compile the project using `g++ [source file] -o [output file]`
6. errors preventing compilation.

# What is supposed to happen.
Project compiles successfully. The output file can be run afterwards.

# Things I have tried

- installing all the files it failed to find during `cmake -S . -B build`.
- Looking online for any similar problems
- Reinstalling SDL3 with the main repo (same issues)
- Went to my laptop (running Lubuntu) to see if it has the same issues.

# image
![Example](https://github.com/user-attachments/assets/0593cfc8-901a-4303-af3f-6fc4f594ec48)

# image 2 (using renderer example 01-clear)
![Example2](https://github.com/user-attachments/assets/e656a23f-8b70-4ea4-aee3-455bffcdcdb3)

**Comment by cmitu** [comment]
> I don't know if I am missing something or not.

Yes, you're missing the step of linking the SDL library into your final executable, see [here](https://wiki.libsdl.org/SDL3/Installation) on how to do that on Linux:

> ...
> Once you have the library installed, you can use the pkg-config program to help you compile your own code:
> ```
>     gcc -o myprogram myprogram.c `pkg-config sdl3 --cflags --libs`
> ```

This is not really an issue, for general support or programming questions is better to use the forums.
