### ISSUE TITLE
How to use SDL2 with .NET MAUI/Xamarin

### ISSUE THREAD

**Issue by hossam14102010** [libsdl-org/SDL#11290]
I am trying to use SDL2 with .NET MAUI. 

I have tried to build the native libraries using the androidbuildlibs.sh at the buildscriprs directory. it generated libSDL.so for different architectures. and then I added them to libs/<architecture> directory in the project and set there build action to AndroidNativeLibrary. when I try to Initialize SDL using:

```
[DllImport("libSDL2.so", CallingConvention = CallingConvention.Cdecl)]
public static extern int SDL_Init(uint flags);
```

the SDL_Init method returns -1.

I thought I should Initialize it somewhere in the MainActivity. so, I built the java library that contains SDLActivity to .jar file and I made a binding project to it. then I tried to make the MainActivity inherit from SDLActivity instead of MauiAppCompatActivity. and I overrided the LoadLibraries method like so:

```
[Activity(Theme = "@style/Maui.SplashTheme", MainLauncher = true, LaunchMode = LaunchMode.SingleTop, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize | ConfigChanges.Density)]
public class MainActivity : SDLActivity
{
    public override void LoadLibraries()
    {
        base.LoadLibraries();
        SDL2Helper.InitSDL();
    }
}
```

Now I get an error indicating that the libmain.so not found.
I really do not know what to do. I am really new to sdl.

**Comment by madebr** [comment]
`main` comes from the default [`getLibraries`](https://github.com/libsdl-org/SDL/blob/bcf1397e330f38f6fe4cf1fec980acea4d37d8d1/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L262-L279) method.
You should override it in your subclass and return only those shared libraries that are needed for your app.
If your project has for example a  `libMyGame.so` library containing `SDL_main`,
then `getLibraries` should return (at least) `{ "SDL2", "MyGame" }`.

**Comment by hossam14102010** [comment]
can I somehow write my entry point (SDL_main) in C#?

**Comment by hossam14102010** [comment]
@madebr This may seem very stupid but how do I create or get the library that contains SDL_main I have built the SDL source code and there is only libSDL2.so

**Comment by madebr** [comment]
`SDL_main` is the entry point of your application. So you have to create it yourself, it's your app. In C-land, SDL2 automatically renames `main` to `SDL_main` by including `"SDL.h"`. (In SDL3, you have to additionally include `<SDL3/SDL_main.h>`)

**Comment by hossam14102010** [comment]
@madebr can I write it in managed code?

**Comment by hossam14102010** [comment]
@madebr Where should I use the SDL_Init?

**Comment by madebr** [comment]
> @madebr can I write it in managed code?

I think so.
You just need to make sure `SDL_main` is compatible.



> @madebr Also where should I use the SDL_Init?

Inside `SDL_main`.

**Comment by hossam14102010** [comment]
How can I write it in managed code? is this [issue](https://discourse.libsdl.org/t/sdl-add-createsdlmainrunnable-to-sdlactivity-thanks-cole/47104) related

**Comment by Susko3** [comment]
This is the MVP that just calls another C# "main" function.

https://github.com/ppy/SDL3-CS/blob/master/SDL3-CS.Tests.Android/MainActivity.cs

**Comment by hossam14102010** [comment]
@Susko3, @madebr Thanks for your help.

**Comment by alextnull** [comment]
@Susko3 
Have you ever tried to run SDL without SDLActivity on MAUI/Xamarin?

Here's what I got, not sure if it's completely correct:
```csharp
 public class MainActivity : MauiAppCompatActivity
 {
     protected override void OnCreate(Bundle? savedInstanceState)
     {
         base.OnCreate(savedInstanceState);
         InitSdl();
     }

     protected override void OnDestroy()
     {
         base.OnDestroy();
         CloseSdl();
     }

     private void InitSdl()
     {
         SDL.LoadLibrary("SDL2", this);
         SDL.SetupJNI();
         SDL.Initialize();
         SDL.Context = this;
         SdlBinding.SDL_SetMainReady(); 
         SdlBinding.SDL_Init(SdlBinding.SDL_INIT_AUDIO);
     }

     private void CloseSdl()
     {
         SdlBinding.SDL_Quit();
         if (SDL.Context == this)
         {
             SDL.Context = null;
         }
     }
 }
 ```

**Comment by Susko3** [comment]
Why not make a new SDL activity that just handles the SDL stuff? What's the reason you need to use the maui activity in the first place?

I hope you know that you can have more than one activity in the same application.

**Comment by alextnull** [comment]
I'm only interested in audio, the SDLActivity class is too overloaded for such a simple case.

**Comment by hossam14102010** [comment]
@alextnull Thanks, you helped me very much. I was also trying to use it with audio.
