### ISSUE TITLE
SDL_GLprofile and SDL_GLcontextFlag shouldn't be enums

### ISSUE THREAD

**Issue by maia-s** [libsdl-org/SDL#11308]
This may be too late to change now that SDL 3 is ABI stable, but `SDL_GLprofile` and `SDL_GLcontextFlag` are defined as enums, but they're used as masks/flags

**Comment by slouken** [comment]
We guarantee that the enum is the size of an int, and all currently supported platforms use 32-bit ints, so we could probably safely switch these to Uint32.

@icculus, what do you think?

**Comment by slouken** [comment]
Actually, these values are never used directly in the ABI, we can definitely change these.

**Comment by icculus** [comment]
I tossed up a PR for this, if we want to merge it.
