### ISSUE TITLE
Difficulties with SDL_Gpu Cycling

### ISSUE THREAD

**Issue by RandyGaul** [libsdl-org/SDL#11305]
I've been using SDL_Gpu for some time now, and have been reading [Evan's nice post on cycling](https://moonside.games/posts/sdl-gpu-concepts-cycling/). Though, I wanted to try and ask @thatcosmonaut directly some questions, as I'm totally stuck. Hopefully this is an appropriate place. I have this issue where if the application runs too quickly the cycling feature is allocating many extra gigabytes of memory. The cycling in question is on a transfer buffer map/unmap for per-frame sprite batching on a buffer of about 5mb.

My understanding is this can happen when GPU bound and can cause a huge cycle chain to get constructed. Pretty much a severe memory leak. Is this true? If so, what's the recommended strategy to sync when GPU bound? Would the simplest solution be to simply call `SDL_WaitForGPUIdle` each frame? Is there a recommended way to use fences for this situation?

In other older APIs I would double, or triple buffer for streaming vertices (sprite batching), and sync on a fence before writing data. But it looks like the cycle design is supposed to alleviate that necessity. How should I go about understanding when a particular resource cycle chain is growing too long, and start waiting on the GPU? It seems like I want to specify a cycle chain capacity limit and have the API wait for an available resource if full. But yeah I’m not sure how I should be thinking about this stuff. Looking for some additional guidance other than simply calling `SDL_WaitForGPUIdle`.

**Comment by slouken** [comment]
Please ask questions on the forums so other people can see and help, or benefit from the answer there:
https://discourse.libsdl.org/c/sdl-development/6

**Comment by thatcosmonaut** [comment]
Acquiring the swapchain should block on vsync mode or return NULL in non-vsync. If I had to guess it sounds like your render loop is submitting commands regardless of the swapchain status which would cause the CPU to get way ahead of the GPU and consume tons of memory. But we can discuss on the forum.
