### ISSUE TITLE
GPU: IMMEDIATE/MAILBOX & Empty Command Buffer Spam

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#11313]
This probably isn't a big deal, but I thought I'd bring it up.

The obvious rendering function looks something like this:
```
void render()
{
    SDL_GPUCommandBuffer *cmd_buf = SDL_AcquireGPUCommandBuffer(device);

    SDL_GPUTexture *texture;
    uint32_t width, height;
    SDL_AcquireGPUSwapchainTexture(cmd_buf, window, &texture, &width, &height);

    if (texture) {
        // Do some rendering here.
    }

    SDL_SubmitGPUCommandBuffer(cmd_buf);
}
```
Can this end up constantly spamming the API with empty do-nothing command buffers in IMMEDIATE or MAILBOX modes?

**Comment by thatcosmonaut** [comment]
This is the intended usage. It's not an issue because command buffers with nothing to do are finished and recycled quickly on the next Submit call.
