### ISSUE TITLE
Access violation error when pushing user events

### ISSUE THREAD

**Issue by JBetz** [libsdl-org/SDL#11339]
Every so often I get an access violation error when trying to push a `SDL_UserEvent` to the event queue. I haven't found a reliable way to reproduce it, but wanted to report in case anyone recognizes the error, or has any advice around potential issues when using this feature in a language with garbage collection. My understanding is that the `SDL_Event` is safe to dispose of after `SDL_PushEvent` returns, so I'm not sure what could be going wrong.

Here's the topmost SDL call which shows values in the event struct:

![image](https://github.com/user-attachments/assets/ac42bf8d-b416-41a7-b5c0-e28030ba037f)

Here's the bottommost SDL call:

![image](https://github.com/user-attachments/assets/690f2e1e-9ccc-4b20-a942-60942b4420bb)

And here's the assembly in `memcpy` that throws the exception:

![image](https://github.com/user-attachments/assets/4b524f81-2f8a-4496-9929-08a3ea9e5af0)

**Comment by JBetz** [comment]
I just noticed that the event's `timestamp` field is `174255680834700` / `16r9E7C0FF4CC8C`  when it should be `0`. The values for `windowID` and `code`, however, are correct. So likely this is an issue with how `Uint64` is represented in the language I'm calling SDL from (Dolphin Smalltalk, which is 32-bit).

**Comment by JBetz** [comment]
Usually the timestamp has the correct value, though, and I never set it to anything other than `0`. So the weird thing is that it's only sometimes somehow gets a junk value.

**Comment by madebr** [comment]
It looks like it fails to read `event+0x40` (64 bytes).
Events must be exactly 128 bytes:
https://github.com/libsdl-org/SDL/blob/8468c372b21b937d7adb340c4725d77c7d87c4d9/include/SDL3/SDL_events.h#L996

**Comment by JBetz** [comment]
Indeed, my struct definition was only 32 bytes. Thank you!
