### ISSUE TITLE
CI: Use a specific Linux container?

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#11357]
Oh no, it's one of _those_ threads... and it's all my fault! What have I become???

This came up since, as part of keeping FNA's Apple support limping along, we started to upload binary builds of our native libraries to GitHub, so that I don't have to manually build stuff I don't support myself. We have everything built now, except for SDL on Linux specifically - the MSVC and macOS artifacts from libsdl-org are fine as-is, but Linux isn't quite there:

- We don't control the glibc minimum with ubuntu-latest, and ubuntu-20.04 may get deprecated next year...?
- Ubuntu LTS releases with a low enough glibc don't support all backends (PipeWire is the big one, libdecor is also part of this I think)

Thankfully GitHub Actions makes using a container _really_ easy, so that's what we went with. FNA went with Rocky Linux because that's what flibitBuild has always used, but for SDL I think it would make more sense to target the [Sniper runtime](https://gitlab.steamos.cloud/steamrt/steamrt/-/blob/steamrt/sniper/README.md). This is [what dxvk does](https://github.com/doitsujin/dxvk/blob/master/.github/workflows/artifacts.yml#L39) and it has the added benefit of being a runtime we _really_ care about, and it'd allow us to make sure compatibility with SLR remains consistently good without Simon having to discover regressions after it's too late.

The only two arguments _against_ this I can think of:
- It does add a few seconds to the Ubuntu build time - that said, our Rocky builds are still stupidly fast even though it runs `dnf update/install` multiple times
- This may _technically_ be redundant since Sniper already comes as a prebuilt runtime, but it's nice to have this from SDL's end without having to download a whole entire sysroot

Thoughts?

**Comment by icculus** [comment]
What's the policy for grabbing these binaries? Is there a stable URL to say "give me the latest SDL3 build compiled against Sniper"?

I haven't looked into this at all, but it would be nice to be able to download them on-demand.

**Comment by flibitijibibo** [comment]
We were thinking the same thing, but unfortunately it requires a third party tool like https://nightly.link/ to make the URL stable for latest commit... it could work for tagged releases maybe?

**Comment by madebr** [comment]
You can do it with the `gh` util.
```sh
workflow_id=$(gh -R libsdl-org/SDL run list -c $(git rev-parse HEAD) --json databaseId --jq '.[0].databaseId')
gh -R libsdl-org/SDL run download $(workflow_id) -p '*sniper*'
```

**Comment by slouken** [comment]
FYI, I believe the plan is to include SDL3 in the sniper runtime, so you won't need to grab it at all. :)
