### ISSUE TITLE
SDL2: Android 15 sound issue

### ISSUE THREAD

**Issue by onesixromcom** [libsdl-org/SDL#11376]
Recently my phone was updated to Android 15 and audio sounds like a white noise. Phone is Google Pixel 7 pro.
I've made some debug and find out that removing setting performance mode fixed the issue. Set mode to AAUDIO_PERFORMANCE_MODE_NONE also helps, but according to the documentation it's the default value.
https://android.googlesource.com/platform/frameworks/av/+/master/media/libaaudio/include/aaudio/AAudio.h

Commit where it was implemented:
https://github.com/libsdl-org/SDL/commit/1e016fd5eaa3b78248fc9e14a5958c0a884b76b8
issue: https://github.com/libsdl-org/SDL/issues/8888

Temp solution to remove lines with
ctx.AAudioStreamBuilder_setPerformanceMode(ctx.builder, AAUDIO_PERFORMANCE_MODE_LOW_LATENCY);

extended solution could be when latency disabled by default.
if (SDL_GetHintBoolean("SDL_ANDROID_LOW_LATENCY_AUDIO", SDL_FALSE)) {
        ctx.AAudioStreamBuilder_setPerformanceMode(ctx.builder, AAUDIO_PERFORMANCE_MODE_LOW_LATENCY);
    }

**Comment by vovan4ik123-engine** [comment]
That is not answer to issue but on most Google Pixels devices i can not run SDL (with its android-project) at all. It craches at launch. I blocked all Google Pixels devices for my app in google play because these devices generate too much crashes.

**Comment by slouken** [comment]
> That is not answer to issue but on most Google Pixels devices i can not run SDL (with its android-project) at all. It craches at launch. I blocked all Google Pixels devices for my app in google play because these devices generates too much crashes.

Interesting, Steam Link ships with SDL3 on all kinds of devices and I'm not seeing crashes on Google Pixel devices. Do you have a version of SDL and call stack for this crash?

**Comment by slouken** [comment]
> Recently my phone was updated to Android 15 and audio sounds like a white noise. Phone is Google Pixel 7 pro. I've made some debug and find out that removing setting performance mode fixed the issue. Set mode to AAUDIO_PERFORMANCE_MODE_NONE also helps, but according to the documentation it's the default value. https://android.googlesource.com/platform/frameworks/av/+/master/media/libaaudio/include/aaudio/AAudio.h
> 
> Commit where it was implemented: [1e016fd](https://github.com/libsdl-org/SDL/commit/1e016fd5eaa3b78248fc9e14a5958c0a884b76b8) issue: #8888
> 
> Temp solution to remove lines with ctx.AAudioStreamBuilder_setPerformanceMode(ctx.builder, AAUDIO_PERFORMANCE_MODE_LOW_LATENCY);
> 
> extended solution could be when latency disabled by default. if (SDL_GetHintBoolean("SDL_ANDROID_LOW_LATENCY_AUDIO", SDL_FALSE)) { ctx.AAudioStreamBuilder_setPerformanceMode(ctx.builder, AAUDIO_PERFORMANCE_MODE_LOW_LATENCY); }

Interesting. I just updated my Pixel 6a to Android 15 and am not getting any issues with SDL3. We've implemented the low latency callback there though, so it might be just that we can't enable low latency audio on SDL2. Can you run a test with SDL3 and see if that's still an issue?

**Comment by slouken** [comment]
This is fixed for the next release, thanks!

**Comment by onesixromcom** [comment]
Thanks @slouken !
