### ISSUE TITLE
SDL3: Unable to build for Android with CMake

### ISSUE THREAD

**Issue by mechakotik** [libsdl-org/SDL#11382]
I am trying to migrate from ndk-build to CMake, as my project uses CMake for all other platforms. When I build apk, building is suspiciously fast (5 seconds against 1 minute with ndk-build), SDL library doesn't get included into apk for arm64-v8a platform, SDL_image and SDL_mixer libraries doesn't get into apk at all.

<img src="https://github.com/user-attachments/assets/1c4f449a-7cbf-4997-b1dc-3e40286946a6" width="512">

Here is my `CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.22)
project(tails-adventure)

set(CMAKE_CXX_STANDARD 20)

add_subdirectory(external/SDL)
add_subdirectory(external/SDL_image)
add_subdirectory(external/SDL_mixer)

file(STRINGS "src/sources.list" TA_SOURCES)

add_library(tails-adventure SHARED
    ${TA_SOURCES}
    external/tinyxml2/tinyxml2.cpp
)

find_library(NDK_LOG_LIB log)
target_link_libraries(tails-adventure PRIVATE
    SDL3::SDL3
    SDL3_image::SDL3_image
    SDL3_mixer::SDL3_mixer
    ${NDK_LOG_LIB}
)

target_include_directories(tails-adventure PRIVATE
    include
    include/objects
    external/SDL/include
    external/SDL_image/include
    external/SDL_mixer/include
    external/tinyxml2
)
```

What am I doing wrong?

**Comment by madebr** [comment]
You're building static `SDL3_image` and  `SDL3_mixer` libraries.
Do `set(BUILD_SHARED_LIBS ON)` before `add_subdirectory(external/SDL_image) ...`

**Comment by mechakotik** [comment]
I thought `BUILD_SHARED_LIBS` was enabled by default. Setting it to `ON` solved the issue, thanks!
