### ISSUE TITLE
GPU doesn't report `SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER`

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#11393]
GPU doesn't expose the texture limit which is available other renderers, it always returns "-1". How can we know the texture limit when GPU is chosen as the default renderer?

Edit: I meant it always returns "default" ("-1", in my case).

**Comment by slouken** [comment]
Excellent question, @thatcosmonaut?

**Comment by thatcosmonaut** [comment]
8192x8192 is the universally supported minimum max size, so we should just hardcode it to that.

**Comment by AntTheAlchemist** [comment]
Can't you pass through the SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER reported by the sub-system renderer chosen by the GPU?

**Comment by thatcosmonaut** [comment]
We could, but it wouldn't be a good idea, because as soon as an application tries to load a texture on a machine with a smaller max size than the development machine it will break. In the GPU API we set device limits based on universally supported minimums for maximum portability, and these limits tend to be quite high. An 8192x8192 32-bit color texture is 2 gigabytes.

**Comment by TheSpydog** [comment]
> 8192x8192 is the universally supported minimum max size

The [size we validate against](https://github.com/libsdl-org/SDL/blob/0508f100e21b7ab004beb1e93e7dfeb656075265/src/gpu/SDL_gpu.c#L914) is actually 16384x16384, since that's supported on all our target APIs and hardware.

**Comment by thatcosmonaut** [comment]
I stand corrected ... so that's an 8GB texture you have to work with.

**Comment by slime73** [comment]
> An 8192x8192 32-bit color texture is 2 gigabytes.

It's 256 MB. Overall as a user I wouldn't expect the GPU render backend to be less capable than the other ones.

**Comment by thatcosmonaut** [comment]
This is what I get for doing napkin math on a Friday...

**Comment by slouken** [comment]
Fixed, thanks!
