### ISSUE TITLE
SDL3, macOS: Copy framework using CMake does no longer work

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#11394]
With the latest pre-release 3.1.6 my CMake script no longer works for copying SDL3.framework to my application bundle. I am using this command:

`COMMAND cp -R $<TARGET_FILE:SDL3::SDL3-shared> ${BUNDLE_CONTENTS}/Frameworks/`

**Comment by andreasgrabher** [comment]
Yes, I did use the DMG. After some more investigation it seems that disabled line 104 in `share/cmake/SDL3/SDL3Config.cmake` is the problem:

`if(0)  # if(CMAKE_VERSION GREATER_EQUAL "3.28")`

If I re-enable that line, it works again.

**Comment by madebr** [comment]
What is the error you're seeing?
As a non-Apple user it seems like it copies the SDL3 xcframework directory. A xcframework is for development only. At runtime, you only need a framework.

If you're running this command to create a package, can you give [`install(IMPORTED_RUNTIME_DEPENDENCIES)`](https://cmake.org/cmake/help/latest/command/install.html#imported-runtime-artifacts) a shot?

**Comment by andreasgrabher** [comment]
While that line is commented, it copies

`SDL3.xcframework/macos-arm64_x86_64/SDL3.framework/SDL3`

instead of 

`SDL3.xcframework/macos-arm64_x86_64/SDL3.framework`


I don't know how to use those CMake features and I want to keep CMake 3.12 as minimum version.

**Comment by madebr** [comment]
Isn't [`TARGET_BUNDLE_DIR`](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_BUNDLE_DIR) what you're after?

**Comment by andreasgrabher** [comment]
I get this error with TARGET_BUNDLE_DIR:

```
CMake Error at src/CMakeLists.txt:85 (add_custom_target):
  Error evaluating generator expression:

    $<TARGET_BUNDLE_DIR:SDL3::SDL3-shared>

  TARGET_BUNDLE_DIR not allowed for IMPORTED targets.

```

**Comment by andreasgrabher** [comment]
To make the issue more clear: While the line is commented, the contents of the framework folder in my bundle look like this:
<img width="1032" alt="Bildschirmfoto 2024-11-02 um 14 22 52" src="https://github.com/user-attachments/assets/1a9758ea-6853-4d65-8310-76039d0bd5fe">
and with the line re-enabled it looks like this:
<img width="1032" alt="Bildschirmfoto 2024-11-02 um 14 26 28" src="https://github.com/user-attachments/assets/15f4cb3e-7854-4c60-9e10-f84d57e73f5a">

Same result can be achieved if changing line 115 to
`IMPORTED_LOCATION "${_sdl3_framework_path}"`

**Comment by madebr** [comment]
You're right, not adding `/SDL3` fixes it.
c56a3f60f does that.

Thanks for suggesting this fix!

**Comment by madebr** [comment]
I'm going to revert ad3c7b92f8726816580033fdaeb52933419102b8 and c56a3f60fe88e9c8b13d7bfd92363e5d2c9a152f .
With those patches, linking to `SDL3::SDL3-shared` does not set the rpath on the linked executable.

Because of not adding `/SDL3`, we also lost compatibility with CMake older then 3.28.

logs: https://github.com/madebr/issues/actions/runs/12955258656

**Comment by andreasgrabher** [comment]
That would break my build process.

At the moment I use this command to copy the framework bundle into my application bundle:

`COMMAND cp -R $<TARGET_FILE:SDL3::SDL3-shared> ${BUNDLE_CONTENTS}/Frameworks/`

What is the proper way to do this? I can‘t use a fixed path, because the framework might be installed in many different places.

**Comment by madebr** [comment]
Are you doing the copy for package purposes?

If so, I'd look into `RUNTIME_DEPENDENCY_SET` of CMake. [documentation](https://cmake.org/cmake/help/latest/command/install.html)
I haven't used it, but it looks to be used as following:
```
# The usual
find_package(SDL3 REQUIRED CONFIG)
add_executable(yourapp main.c)
target_link_libraries(yourapp PRIVATE SDL3::SDL3-shared)

install(TARGETS yourapp RUNTIME_DEPENDENCY_SET yourapp-runtime-dependencies)
install(RUNTIME_DEPENDENCY_SET yourapp-runtime-dependencies)
```
I haven't used this feature myself, so I can't guarantee its correctness.
It is possible it does not work currently, because `IMPORTED_LOCATION` of `SDL3::SDL3-shared` is missing the `/SDL3` suffix, so you'd have to append it yourself.

**Comment by andreasgrabher** [comment]
These are the relevant lines in my build scripts (simplified):

```
find_package(SDL3 REQUIRED COMPONENTS SDL3)
add_executable(${APP_NAME} ${SOURCES})
set_target_properties(${APP_NAME} PROPERTIES INSTALL_RPATH "@executable_path/../Frameworks")
set_target_properties(${APP_NAME} PROPERTIES BUILD_WITH_INSTALL_RPATH TRUE)
target_link_libraries(${APP_NAME} ${SDL3_LIBRARIES})
```

You can find the full scripts [here](https://sourceforge.net/p/previous/code/HEAD/tree/branches/branch_filesharing/CMakeLists.txt) and [here](https://sourceforge.net/p/previous/code/HEAD/tree/branches/branch_filesharing/src/CMakeLists.txt)

I have no experience with `RUNTIME_DEPENDENCY_SET`. I wanted to release the new version of my application with SDL3 by the weekend. I'll stay with SDL2 for now as that works without any issues and hope for someone else to solve this problem.

Btw. for copying SDL2.framework and png.framework I use these commands:
`cp -R ${SDL2_LIBDIR} ${BUNDLE_CONTENTS}/Frameworks/`
`cp -R ${PNG_LIBRARY} ${BUNDLE_CONTENTS}/Frameworks/`

**Comment by madebr** [comment]
I can't help you (not an Apple user myself).
Only thing I can suggest to you is posting something at [discourse.cmake.org](https://discourse.cmake.org/) or on the #cmake channel at cpplang.slack.com

(Let us know how you handle it)

**Comment by andreasgrabher** [comment]
I still think the fixes that were un-done were correct. I have been building SDL3 pre-releases without issues and I had no issues linking the built frameworks with my application. 

I'll let some time go past and hope someone with a similar issue comes up with a solution.
