### ISSUE TITLE
Warning "event->paxis.axis >= 0" always true

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#11410]
Maybe a minor warning to ignore, or "axis" variable could be as well turned into a signed type

```
src/events/SDL_events.c:733:48: warning: result of comparison of unsigned enum expression >= 0 is always true [-Wtautological-unsigned-enum-zero-compare]
  733 |                            ((event->paxis.axis >= 0) && (event->paxis.axis < SDL_arraysize(pen_axisnames))) ? pen_axisnames[event->paxis.axis] : "[UNKNOWN]", event->paxis.value);
      |                              ~~~~~~~~~~~~~~~~~ ^  ~
```

**Comment by sezero** [comment]
I hate that about clang. Is it impossible to receive an arbitrary integer instead of the defined enumerated values in C?

**Comment by icculus** [comment]
>  Is it impossible to receive an arbitrary integer instead of the defined enumerated values in C?

No, but all the values in that enum are >= 0, so the warning is correct to alert us to a potential coding error, imho.
