### ISSUE TITLE
emulated windows accel curve is completely inaccurate

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#11412]
Env: 
- Windows 10, 100% scaling

Repro:
- disable SDL_HINT_MOUSE_RELATIVE_MODE_CENTER
- enable SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE
- enable SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE
- enable Enhance Pointer Precision
- every frame, draw vertical and horizontal lines at position reported by SDL_GetMouseState
- observe cursor not following the cross point

Recommendation:
- use the above test case to reverse engineer the acceleration implementation until it matches
- key points to note:
  - windows acceleration is done per-input without knowledge of delta time
  - the acceleration behavior is slightly different between Windows 7 and Windows 8+

Related Issue:
- Windows do not provide any way to distinguish between inputs sent by Precision TouchPads and other injected inputs, but Precision TouchPads maintains its own set of pointer speed/accel options separate from the system option retrieved by SDL. So if the user has acceleration disabled for mice but not for TouchPads, there will be always deviation from behaviour emulated by SDL when the user uses the Precision TouchPad; this use case unsolvable, so care should be taken to advertise this deviation.

**Comment by slouken** [comment]
PR welcome!
