### ISSUE TITLE
Move SDL_Render to separate repo

### ISSUE THREAD

**Issue by 1vanK** [libsdl-org/SDL#11418]
Most people use SDL as a thin layer between a game and OS, and few use SDL Render. Why not put SDL Render in a separate repository, like SDL Mixer?

**Comment by slouken** [comment]
The API and ABI is frozen.

**Comment by 1vanK** [comment]
> The API and ABI is frozen.

When? We have a lot of commits that break the API

https://github.com/dviglo2d/sdl/commit/7108291d0b7792fd7e1039cfc7897189e5d58adc

**Comment by madebr** [comment]
> > The API and ABI is frozen.
> 
> When? We have a lot of commits that break the API
> 
> [dviglo2d@7108291](https://github.com/dviglo2d/sdl/commit/7108291d0b7792fd7e1039cfc7897189e5d58adc)

API != ABI
Renaming a type does not change change its binary representation, or the contract of a function.

**Comment by 1vanK** [comment]
> API != ABI

I didn't say anything about ABI

**Comment by madebr** [comment]
Mmm indeed, you're eight.
 That commit slightly changes the api.

But there's a difference between this renaming, and removing a complete subsystem.
