### ISSUE TITLE
SDL2: Window resizing with software renderer appears broken on Wayland

### ISSUE THREAD

**Issue by dhthwy** [libsdl-org/SDL#11423]
Things work wonderfully when the renderer is hardware, but when resizing the window in software mode, renderering breaks.

I have:
One thread pumping events.
One thread which creates the SDL_Window, SDL_Renderer, and handles all rendering. Events are pushed to a thread safe queue where it is handled in the rendering thread's loop.

Here is how I am constructing the renderer.

 ```
flags = SDL_WINDOW_RESIZABLE
SDL_Window* handle = SDL_CreateWindow(title, x, y, w, h, flags);
if (!handle) {
            ...
}

SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "best");
// force software for testing
SDL_RendererFlags rflags = (SDL_RendererFlags)SDL_RENDERER_SOFTWARE;
SDL_Renderer* renderer = SDL_CreateRenderer(handle, -1, rflags);
```

When SDL dispatches a resize event, SDL_Window data from gdb shows:

```
$2 = {magic = 0x726c00000a28, id = 1, title = 0x720400008190 "SDL", icon = 0x0, x = 0, y = 0, w = 654, h = 480, min_w = 64, min_h = 48, max_w = 0, max_h = 0, 
  flags = 550, last_fullscreen_flags = 40, display_index = 0, windowed = {x = 0, y = 0, w = 654, h = 480}, fullscreen_mode = {format = 0, w = 0, h = 0, refresh_rate = 0, 
    driverdata = 0x0}, opacity = 1, brightness = 1, gamma = 0x0, saved_gamma = 0x0, surface = 0x7218001ae0e0, surface_valid = SDL_FALSE, is_hiding = SDL_FALSE, 
  is_destroying = SDL_FALSE, is_dropping = SDL_FALSE, mouse_rect = {x = 0, y = 0, w = 0, h = 0}, shaper = 0x0, hit_test = 0x0, hit_test_data = 0x0, data = 0x720800006e20, 
  driverdata = 0x72440000ff00, prev = 0x0, next = 0x0}
```

So it seems the surface is being invalidated (nevermind, looks like it's supposed to be when resizing). I've snooped around the issues and it seems this sort of thing has come up before. Is there a workaround?  Or will disabling resizing solve the rendering breakage (asking, in case there's other things that can break it)?

SDL2 version: 2.30.3

My platform and hardware information:

```
Operating System: Fedora Linux 40
KDE Plasma Version: 6.2.2
KDE Frameworks Version: 6.7.0
Qt Version: 6.7.2
Kernel Version: 6.11.5-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 27.3 GiB of RAM
Graphics Processor: AMD Radeon Graphics
```

**Comment by Kontrabant** [comment]
The renderers are generally not considered to be thread safe. Certain renderer backends may work when run threaded on certain platforms under certain circumstances, but there are no guarantees (see #11159)

In the case you describe, your event and rendering threads are racing, even though you are trying to handle events in a thread safe manner. The software renderer uses an event watcher callback to watch for resize events and invalidate the window and surface if the size changes. This watcher will be called from the event thread at the time that events are initially pumped and placed in the SDL event queue, which means that a resize event might be processed and invalidate the window and surface in the middle of rendering operations.

**Comment by dhthwy** [comment]
Thank you for your detailed explanation.

There must be something else going on as I changed it to poll events and render all from the main thread. Same behavior. Stuff works until I attempt to resize with software renderer. 

So I either 
1) botched something with the recent change
2) it was already botched
3) there is a problem with SDL2/Wayland/etc on my system.

Feel free to close this issue if you'd like, and I can reopen it if I believe it's not something I did.

The test driver looks something like this. 

```
void run()
{
    if (SDL_Init(SDL_INIT_VIDEO) != 0) {
        fprintf(stderr, "SDL Failed to init: %s\n", SDL_GetError());
        goto quit;
    }

// Create window, renderer
    if (app.init()) {
        goto quit;
    }

    while (1) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            switch (e.type) {
            case SDL_QUIT:
                app.shutdown();
                goto quit;
            }
        }
        // render frame
        app.update();
    }
    
quit:
    SDL_QuitSubSystem(SDL_INIT_VIDEO);
    SDL_Quit();
}
```

**Comment by Kontrabant** [comment]
Do the other test suite programs work, such as testsprite2 (`testsprite2 --resizable --renderer software`)?

The other test apps don't destroy and recreate the renderer when resizing, and it shouldn't be necessary in general. Do you have a small reproduction case that you can share, which reliably reproduces your problem?

**Comment by dhthwy** [comment]
testsprite2 --resizable --renderer software

is working.

No simple test case atm, the app is simple I think, but clearly one is needed. I'll whip up something.

I am creating two textures with this software renderer:

```
SDL_CreateTexture(renderer, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_STATIC, 1, 1);
```

and then another one for a font atlas. 

I'm not sure if that matters -- I assumed SDL would use the 'software version' for these textures.

**Comment by dhthwy** [comment]
Oh boy. It's my damned event filter. Sorry. Figured it was probably me.

This is an extension for another application and needs to detect whether the event is for its own stuff so the rest of the application doesn't handle it.

Bare bones, it's like this:

```
static int handle_event(void* data, SDL_Event* e)
    {
          ...
          const Uint32 flags = SDL_GetWindowFlags(main_window->context.window_handle);

        if ((e.type == SDL_WINDOWEVENT && e.window.windowID == main_window->context.window_id) // is our window
                || (flags & SDL_WINDOW_INPUT_FOCUS)) { // We have input focus

            SDL_Event ec;
            std::memcpy(&ec, &e, sizeof(SDL_Event));
            event_pipe.sdl_event.push(ec);
            return 0;
        }
        return 1;
    }
```

**Comment by Kontrabant** [comment]
Yes, if you are returning 0 for any events targeted at your main window, the events are being discarded before any event watchers are called. Since the software renderer uses a watcher to watch for resize events, this will break things.

**Comment by dhthwy** [comment]
Thank you. I spose then this is

NOTABUG or REPORTERISBUG.

**Comment by dhthwy** [comment]
Just to add:

According to the documentation https://wiki.libsdl.org/SDL2/SDL_SetEventFilter:

"If the filter function returns 1 when called, then the event will be added to the internal queue. If it returns 0, then the event will be dropped from the queue, but the **internal state will still be updated**. This allows selective filtering of dynamically arriving events."

I read this as 'internal handling of the resize event (update state) will still happen.' It may be worthwhile to add an exception note to the docs if this only applies to certain events.
