### ISSUE TITLE
SDL GPU clear texture of integers on render pass begin

### ISSUE THREAD

**Issue by jsoulier** [libsdl-org/SDL#11451]
Pretty much the title. If I bind a texture of integers as a render target (`R32_INT`), how can I clear the render target? The `SDL_GPUColorTargetInfo` only takes floats and in the vulkan GPU implementation, only `clearColor.float32` is set.

My use case is edge detection where I only need a boolean. Thanks

**Comment by flibitijibibo** [comment]
Does #11347 do what you need?

**Comment by jsoulier** [comment]
Yeah it does thanks. Closing
