### ISSUE TITLE
Android: SDL 2.30.9 introduced a lot of audio latency

### ISSUE THREAD

**Issue by leonstyhre** [libsdl-org/SDL#11457]
Hi!

I just updated my application (ES-DE Frontend) to use SDL 2.30.9 and this unfortunately introduced a lot of audio latency. I was previously using 2.30.7 and there the amount of latency was fine.

I saw the following in the 2.30.9 changelog and I wonder whether this could be the cause of the problem?
"Fixed audio issues on Android 15"

Not sure what was changed specifically though?

I've tested across multiple devices and Android versions and the issue exists everywhere I tested, although it seems to be worse on some devices than others. But all devices got additional latency for sure with 2.30.9

Thanks in advance!

**Comment by leonstyhre** [comment]
I have an update on this issue, I have experimented with using the OpenSL ES driver instead and this is working fine with low latency overall. I did not realize that you could set the SDL_AUDIODRIVER environment variable also on Android to change the driver. So the following works:

`setenv("SDL_AUDIODRIVER", "openslES", 1);`

I've as such changed my application to use OpenSL ES by default and although mass testing is required to confirm it's working reliably, so far it looks very promising as I've tested a range of different devices from Android 10 to Android 15 including Android TV and they all offer good low latency audio with OpenSL ES.

Even before SDL 2.30.9 some devices like the Samsung Galaxy S23 had an absurd amount of audio latency with the AAudio driver, I estimate 200 to 400 milliseconds on that specific device and I've received similar reports from other Samsung users.

According to Google the AAudio driver is supposed to be a low latency implementation so something must be wrong somehow, also before 2.30.9 but especially as of this release. For me the problem is likely solved by switching audio drivers, unless there are some unforeseen drawbacks of using OpenSL ES. But I have an automatic failover in place to AAudio in case SDL_InitSubSystem(SDL_INIT_AUDIO) fails for OpenSL ES, and I also added a menu entry where the user can manually select which audio driver to use.

Maybe it's even worth considering making OpenSL ES the default driver instead of AAudio?

**Comment by icculus** [comment]
`AAUDIO_PERFORMANCE_MODE_LOW_LATENCY` strikes again.

Likely this is the commit that caused your problem: d2b9ecd2814424f76e6b6deac5fbb3a0825d9ab1 ...but this has been ping-ponging back and forth as we find different sets of devices it causes problems on.

The _easiest_ solution, if it's working for you, is to just leave it forced to use OpenSL ES for SDL2, and remove that explicit backend request if/when you move to SDL3.

We have to backport a bunch of improvements to our AAudio code into SDL2 to make this work well, and I don't know if we're going to have time to do that in the near future. But if OpenSL ES turns out to be a disaster for other reasons, I'll find some time to help on this.

**Comment by slouken** [comment]
OpenSL ES is actually very well supported and a great path for SDL2. Maybe we should just remove the aaudio driver there?

**Comment by icculus** [comment]
We can just bump the driver priority. Someone is definitely going to be mad if we remove it and OpenSL ES doesn't work for them.

**Comment by leonstyhre** [comment]
Thanks for the info, yes it sure sounds like AAUDIO_PERFORMANCE_MODE_LOW_LATENCY is the problem, but like mentioned some Samsung devices don't seem to support that anyway as they have an incredible amount of latency when using the AAudio driver even in 2.30.7 and earlier releases. I'm curious how they behave with SDL3 and AAudio though.

I will most definitely move to SDL3 in the somehow near future and for now it's perfectly fine to keep using OpenSL ES as it seems to work well (and also solves the Samsung problem). Actually, what are the benefits of AAudio over OpenSL ES in the first place?

Regarding removal of AAudio form SDL2, I'm not sure what the benefit would be? Maybe there are some pros and cons between the two drivers so it could be good that the user could select either or, like in my case with ES-DE? It probably does make sense to set OpenSL ES as the default driver though, AAudio behaves pretty bad in 2.30.9 on most devices. It is not the case everywhere however, the Google Pixel Tablet has relatively low audio latency even with 2.30.9 when using the AAudio driver.

And yes, backporting the improvements from SDL3 are likely not worth it I guess since this is only a temporary situation anyway.

**Comment by leonstyhre** [comment]
@icculus You posted just before I pressed "Comment" :)

Yes that sounds like a good approach! And as I described above I fallback to AAudio automatically if a device does not suport OpenSL ES, which is probably a good idea as I have no idea what device support is like for OpenSL ES.

**Comment by icculus** [comment]
Okay, OpenSL ES is preferred for SDL2 now. We'll reopen if this turned out to be a terrible idea, in which case the next step would be to backport AAudio stuff from SDL3.

**Comment by leonstyhre** [comment]
Good, thanks for looking into this so quickly! And I'll for sure get mass testing of OpenGL ES when I release the next version of ES-DE!
