### ISSUE TITLE
SDL3 GPU API: A Question regarding missing Features

### ISSUE THREAD

**Issue by Xeais** [libsdl-org/SDL#11478]
Is there a plan to add missing features (like ray tracing, mesh shaders etc.) in the not so distant future?

**Comment by thatcosmonaut** [comment]
No.

**Comment by icculus** [comment]
To clarify: maybe, someday, when these features prove worthwhile, and reasonable to implement across several platforms and underlying APIs...so while these things are not in the "never" category, they are definitely not "near future" items either.

**Comment by Xeais** [comment]
> To clarify: maybe, someday, when these features prove worthwhile, and reasonable to implement across several platforms and underlying APIs...so while these things are not in the "never" category, they are definitely not "near future" items either.

Okay and thank you for the clarification!

**Comment by slouken** [comment]
Can we get this in a FAQ or README somewhere so @thatcosmonaut can just point at that instead of a short rebuff to being asked this over and over?

**Comment by icculus** [comment]
Reopening for FAQ addition.

**Comment by Xeais** [comment]
> Can we get this in a FAQ or README somewhere so @thatcosmonaut can just point at that instead of a short rebuff to being asked this over and over?

May I ask where this question was already answered, because I couldn't find an answer.
