### ISSUE TITLE
Expose SDL_MAX_QUEUED_EVENTS to users

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#11485]
Would it be possible to export the [`SDL_MAX_QUEUED_EVENTS`](https://github.com/libsdl-org/SDL/blob/0f9e551d7127e9d244b25bf8ceef63422f77cfc2/src/events/SDL_events.c#L44) macro in [`SDL_events.h`](https://github.com/libsdl-org/SDL/blob/0f9e551d7127e9d244b25bf8ceef63422f77cfc2/include/SDL3/SDL_events.h)? I understand that it will become part of the ABI contract, but it'll be useful for programs to be able to record events in a pre-allocated static buffer (especially games that use the callback-based `main`) without having to put a potentially heavyweight `malloc` in the event loop which will add latency to the event processing.

**Comment by slouken** [comment]
No, you'll almost never reach the limit of events. If you do, that means you're getting events at a high rate and not emptying the queue regularly.

If you want more efficient event processing, it's better to do something like this:
```c
{
    SDL_Event events[128];
    int count;

    SDL_PumpEvents();
    while ((count = SDL_PeepEvents(events, SDL_arraysize(events), SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST)) > 0) {
        for (int i = 0; i < count; ++i) {
            // Handle events[i]
        }
    }
}
```

**Comment by slouken** [comment]
> > No, you'll almost never reach the limit of events.
> 
> @slouken Is this true for all platforms and situations? For example, if a user types a long string on an IME keyboard, can we be sure that that string will not be delivered as a long series of events -- one for each codepoint in the string?

Yes, you can verify this by looking at the code or testing it yourself.

> How do `SDL_PumpEvents`/`SDL_PeepEvents` interact with the `SDL_AppEvent`? I can't find documentation for it.

Oh, this approach won't work for SDL_AppEvent(), if you're using the callbacks you don't need to worry about it. Your function will get called once for each event.

**Comment by slouken** [comment]
I'm not sure I understand. Why would you have to call malloc() inside the AppIterate function?

In any case, we're not going to expose this value. You can assume it, if you like, since it's not likely to change.
