### ISSUE TITLE
CI: Windows ARM builds have been failing

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#11484]
See, e.g.: https://github.com/libsdl-org/SDL/actions/runs/11873470201/job/33088578294

**Comment by madebr** [comment]
This job from yesterday succeeded: https://github.com/libsdl-org/SDL/actions/runs/11865207517/job/33070022770
This job from 17 minutes ago failed: https://github.com/libsdl-org/SDL/actions/runs/11873470201/job/33088578294

A relevant change is a bump from MSVC [19.41.34123.0](https://github.com/libsdl-org/SDL/actions/runs/11865207517/job/33070022770#step:22:72) to [19.42.34433.0](https://github.com/libsdl-org/SDL/actions/runs/11873470201/job/33088578294#step:22:72)

**Comment by sezero** [comment]
> I've created a ticket [here](https://github.com/actions/runner-images/issues/10981).

s/system32.lib/kernel32.lib/

**Comment by madebr** [comment]
> s/system32.lib/kernel32.lib/

Thanks. I've downloaded the latest (=10.0.26100.0) Windows ARM SDK using [this script](https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977/) and the `um` and `ucrt` directories are empty indeed.

Has anybody seen an announcement about Windows on ARM being deprecated?

**Comment by sezero** [comment]
Other SDL libs need similar treatment, including active branches, and including sdl2-compat which suffers from the issue.
