### ISSUE TITLE
`SDL_SaveBMP` doesn't save alpha of `SDL_PIXELFORMAT_RGBA128_FLOAT` surface.

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#11483]
`SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGBA128_FLOAT)` comes back false, so the BMP is saved as 24 bit, instead of 32 bit

**Comment by slouken** [comment]
Fixed, thanks!
