### ISSUE TITLE
MacOS: UI is blocked while resizing

### ISSUE THREAD

**Issue by eyalamirmusic** [libsdl-org/SDL#11508]
This seems like exactly the same issue that happens here:
https://discourse.libsdl.org/t/update-window-during-resize-in-mac-os/47912/3

To test, build on MacOS any of the examples (for example, renderer-geometry) with the SDL_WINDOW_RESIZABLE flag.

Once you click and hold the mouse in the bottom right corner, animation stops until the mouse is released.
On Windows I don't get that this issue, so it seems to be MacOS only.

Any suggestions?

**Comment by ThrudTheBarbarian** [comment]
Yep, I noticed this as well - asked [a question](https://discourse.libsdl.org/t/live-resize-of-an-sdl-window/56045) in the forum about it, which has some videos of the effect.

**Comment by slouken** [comment]
I just ran testgeometry on macOS 15.1 with the --resizable command line option and it smoothly rendered during the resize... ?

**Comment by slouken** [comment]
I'm testing on the latest SDL3 code, are you seeing the same thing?

**Comment by ThrudTheBarbarian** [comment]
I'm using the released version as of a few weeks ago, but I can download/compile the main branch and see if that works. Be awesome if it did :)

**Comment by ThrudTheBarbarian** [comment]
https://github.com/user-attachments/assets/3cae78e5-7914-4a7f-be6b-f57913daf909

The above is what I see with --resizable on freshly-downloaded/compiled SDL3. It's most obvious when you change the aspect ratio of the window (so just expand horizontally or vertically, not both). This is on an M4 Max MBP running Sequoia 15.1 (24B2082), if it makes any difference.

**Comment by slouken** [comment]
Oh, I see what you mean. Thanks for clarifying!

**Comment by slouken** [comment]
Fixed! :)

**Comment by slouken** [comment]
This fix has been cherry-picked for the next SDL2 release as well.

**Comment by ThrudTheBarbarian** [comment]
Confirmed, working on my Mac :) Thank you Sam!

**Comment by slouken** [comment]
You're welcome! :)

**Comment by eyalamirmusic** [comment]
Thank so much for this fix!
However it's not 100% solved. 

Indeed, during the resize itself redraw happens as expected.
But - if you just hold your mouse button on the bottom right corner and not move it, redrawing is frozen.

Attaching a gif showing the issue:
![geometryfrozen](https://github.com/user-attachments/assets/b5664651-1cf9-4633-98d0-119b78d0c9ea)

**Comment by slouken** [comment]
> Indeed, during the resize itself redraw happens as expected. But - if you just hold your mouse button on the bottom right corner and not move it, redrawing is frozen.

That's correct, because the macOS event loop is blocked waiting for a live resize to start. Feel free to open another issue to track this, but I'm not sure what can be done about it.

**Comment by eyalamirmusic** [comment]
@slouken I wrote a trivial gui app with JUCE that animates a rectangle with a resizable window and the issue doesn't happen there (GIF attached) so to my knowledge it's very possible.

![resizeJUCE](https://github.com/user-attachments/assets/7958639e-084c-4281-864e-4cb8f5c1d22f)

**Comment by OneSadCookie** [comment]
Has this regressed? I don't see any events sent during live resize on macOS Tahoe 26.3.1 (a) with SDL 3.4.4.
