### ISSUE TITLE
Could not make GL context current on Ubuntu 22.04

### ISSUE THREAD

**Issue by runninglinuxkernel** [libsdl-org/SDL#11510]
I wrote a code for display video, using SDL 2.30.9 and QT 5.12, the code like below:

sdl_window = SDL_CreateWindowFrom(window_id);
sdl_render = SDL_CreateRenderer(sdl_window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
 ret = SDL_UpdateYUVTexture();

SDL_LockMutex(sdl_mutex);
SDL_RenderClear(sdl_render);
SDL_RenderCopy(sdl_render, sdl_texture, NULL, &rect);
SDL_RenderPresent(sdl_render);
SDL_UnlockMutex(sdl_mutex);

this code works fine on Ubuntu 20.04, but show green screen on Ubuntu 22.04.

i open the debug on SDL:
running with SDL version 2.30.9
Renderer 0: opengl
Renderer 1: software
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
render name opengl

DEBUG: Could not make GL context current: BadAccess (attempt to access private resource denied)
DEBUG: Could not make GL context current: BadAccess (attempt to access private resource denied)
DEBUG: Could not make GL context current: BadAccess (attempt to access private resource denied)
DEBUG: Could not make GL context current: BadAccess (attempt to access private resource denied)

what is problem? how to fix it?

**Comment by icculus** [comment]
According to [the glxMakeCurrent manpage](https://linux.die.net/man/3/glxmakecurrent) ...

> BadAccess is generated if ctx was current to another thread at the time glXMakeCurrent was called.

This seems unlikely within SDL itself, as SDL_CreateRenderer would create the context and make it current within the same _function_, let alone the same thread.

But also: "Could not make GL context current" is not a string that appears in SDL's source code...is Qt  _also_ trying to make a GL context on this window, and this is causing a conflict with SDL, causing it to write out those `DEBUG` lines?

**Comment by runninglinuxkernel** [comment]
It looks that they are not in the same thread.
