### ISSUE TITLE
CI: Apple targets have been failing randomly as of late

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#11517]
As title says: See recent commits and/or pull requests.
Re-running the failed ones usually end up in success.

CC: @madebr

**Comment by maia-s** [comment]
The ones I've seen fail when installing pkgconf
```
==> Pouring pkgconf--2.3.0_1.arm64_sonoma.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
  brew unlink pkg-config@0.29.2

To force the link and overwrite all conflicting files:
  brew link --overwrite pkgconf

To list all files that would be deleted:
  brew link --overwrite pkgconf --dry-run

Possible conflicting files are:
/opt/homebrew/bin/pkg-config -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/bin/pkg-config
/opt/homebrew/share/aclocal/pkg.m4 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/aclocal/pkg.m4
/opt/homebrew/share/man/man1/pkg-config.1 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/man/man1/pkg-config.1
```

**Comment by madebr** [comment]
https://github.com/Homebrew/brew/issues/18788 might be related

**Comment by madebr** [comment]
pkg-config is [installed by default on the macos runners](https://github.com/actions/runner-images/tree/main/images/macos).
Starting from 000745122, we will no longer install pkg-config (or its newer pkgconf nephew)

**Comment by slouken** [comment]
Thank you!

**Comment by madebr** [comment]
There's a part II ;) 848fd1eab

**Comment by sezero** [comment]
SDL2 and release-2.30.x branches need similar massage: see failures
for today's commits in those branches

The satellite libs also seem to install pkg-config for Apple targets
and most possibly need similar treatment:
SDL_image, SDL_net: SDL2 branch only
SDL_rtf: main branch only
SDL_mixer, SDL_ttf: main and SDL2 branches

**Comment by sezero** [comment]
> These branches need patches similarly to this one: [dface78](https://github.com/libsdl-org/SDL/commit/dface78331d692ee98ae4939abafc0c204a2ee45)

Should I touch the satellite libs like that?

P.S.: release-2.30.x is missing the Windows 32 bit ARM workaround and keep failing at that.

**Comment by madebr** [comment]
> Should I touch the satellite libs like that?

Please do, or keep a mental note and do it when you need to do actual work on the repo?

> P.S.: release-2.30.x is missing the Windows 32 bit ARM workaround and keep failing at that.

I tried 01dee787c1, but am unsure this is a correct fix.

**Comment by madebr** [comment]
> Incorrect I guess: still failing.

I'm going to backport SDL3's ci build system to SDL2. Looks like I don't know how to set the Windows SDK version for Visual Studio CMake projects.
