### ISSUE TITLE
Add APIs to identify the audio device type.

### ISSUE THREAD

**Issue by yunline** [libsdl-org/SDL#11529]
Currently there is no "official" way to identify if an audio device is physical or logical, playback or recording.

Looking at the source code
https://github.com/libsdl-org/SDL/blob/bbe843fd80e351b82ff3c9d7d510d91b345e9385/src/audio/SDL_audio.c#L1357-L1358

So I recommend to add these macros to `SDL_audio.h`, as an "official" way to identify the types of a audio device 
```c
#define SDL_AUDIO_DEVICE_MASK_PLAYBACK   0x00000001u
#define SDL_AUDIO_DEVICE_MASK_PHYSICAL   0x00000002u
#define SDL_AUDIO_DEVICE_ISPLAYBACK(x)   ((x)&SDL_AUDIO_DEVICE_MASK_PLAYBACK)
#define SDL_AUDIO_DEVICE_ISRECORDING(x)  (!SDL_AUDIO_DEVICE_ISPLAYBACK(x))
#define SDL_AUDIO_DEVICE_ISPHYSICAL(x)   ((x)&SDL_AUDIO_DEVICE_MASK_PHYSICAL)
#define SDL_AUDIO_DEVICE_ISLOGICAL(x)    (!SDL_AUDIO_DEVICE_ISPHYSICAL(x))
```

**Comment by icculus** [comment]
Is there a need for this? The numbering of devices is an implementation detail, for internal efficiency, that isn't part of the public API.

**Comment by icculus** [comment]
If we were to do this, it wouldn't be a macro, in case we ever change the numbering scheme internally.
