### ISSUE TITLE
hint for choosing which system cursor to use as default

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#11533]
Currently, the default system cursor unconditionally uses SDL_SYSTEM_CURSOR_DEFAULT for all applicable platforms.

There may be use cases where the developer wants to use a different choice among SDL_SystemCursor, for example an image viewer application where the default state should be the system-set move cursor.

Allowing this to be set as a hint greatly reduces the complexity for using SDL to make quick apps that always stick to one system cursor but not necessarily the default arrow, without overriding the user preference in their system cursor set.

**Comment by slouken** [comment]
This seems reasonable. Feel free to submit a PR for this.
