### ISSUE TITLE
KWin X11 memory leak after exiting an SDL program

### ISSUE THREAD

**Issue by eigenvoid** [libsdl-org/SDL#11538]
OS: Arch Linux with X11 and KDE Plasma 6.2.3
GPU: Intel Iris Xe integrated graphics

Every time I close my program written in C++ with SDL3, KWin (the KDE window manager) leaks memory, anywhere from 1 to 10 MB at a time. After about 1 GB has leaked, KWin starts to get unstable, and it crashes soon thereafter.

I occasionally see the following error in the console:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x7e171fc
  Serial number of failed request:  560
  Current serial number in output stream:  560
```

This issue happens with both SDL2 and SDL3.

This is a minimal SDL3 program that reproduces the issue:

```
#include <SDL3/SDL.h>
#include <cstdlib>

int main(void) {
	SDL_Init(SDL_INIT_VIDEO);
	SDL_Window *window = SDL_CreateWindow(nullptr, 1024, 768, 0);

	for (bool running = true; running;) {
		for (SDL_Event event; SDL_PollEvent(&event);) {
			switch (event.type) {
			case SDL_EVENT_QUIT:
				running = false;
				break;
			}
		}
	}

	SDL_DestroyWindow(window);
	SDL_Quit();
	return EXIT_SUCCESS;
}
```

**Comment by Kontrabant** [comment]
I ran the SDL X11 backend through Valgrind and can't find any obvious leaks, outside of a few bytes from within DBus and libX11, which is a known issue, and that memory belongs to the SDL process and is cleaned up on exit. Nothing that would potentially account for tens of megabytes persisting after the process terminates. If KWin is leaking memory even after the SDL process is terminated, that's not an SDL bug.

This may be related: https://bugs.kde.org/show_bug.cgi?id=496405
