### ISSUE TITLE
Request: Current Working Directory

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#11531]
While `chdir` was [considered problematic](https://github.com/libsdl-org/SDL/issues/9110) due to its global nature, I don't think `getcwd` should be an issue. Getting the current working directory is important to be able to implement a "Recently Opened Files" list if the files were passed as a relative path.

**Comment by icculus** [comment]
I agree on this. Platforms without a concept of a cwd can return a root (or home, whatever) directory.

**Comment by slouken** [comment]
Yep, agreed.
