### ISSUE TITLE
[SDL3] ``SDL_FillSurfaceRect`` and ``SDL_FillSurfaceRects`` uses SDL_Rect instead of SDL_FRect

### ISSUE THREAD

**Issue by OceanOC** [libsdl-org/SDL#11555]
I noticed that SDL_FillSurfaceRect (and SDL_FillSurfaceRects) uses SDL_Rect instead of SDL_FRect. I intend to post a PR to fix SDL_FillSurfaceRect (and SDL_FillSurfaceRects) to use SDL_FRect instead, but I was wondering if this was intentional, If so would it be better to create a new function?

**Comment by icculus** [comment]
Surfaces generally deal with pixels, not subpixel precision, so we left this as SDL_Rect.
