### ISSUE TITLE
SDL_SetWindowSize during SDL_WINDOWEVENT_SIZE_CHANGED, different behaviour between sdl2 and sdl3

### ISSUE THREAD

**Issue by edo9300** [libsdl-org/SDL#11561]
When porting my code from sdl2 to sdl3, on windows, i noticed that maximizing the window and then restoring it, left it in a weird state, where it went out of the maximized state, but the window size didn't restore properly and remained the maximized one.
Turns out that the issue was a weird call I was doing to `SDL_SetWindowSize`, as i was calling it during a `SDL_WINDOWEVENT_SIZE_CHANGED` event, passing to it the dimensions that were just changed (can't even remember why i did that, but i guess i never noticed because it worked as expected)
This is a sample SDL2 program exhibiting this behaviour
```c
#include "SDL.h"

int main(int argc, char *argv[])
{
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window* window = SDL_CreateWindow("Test", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, SDL_WINDOW_RESIZABLE);

    SDL_Event e;
    while(SDL_WaitEvent(&e)) {
        if((e.type == SDL_WINDOWEVENT) && (e.window.event == SDL_WINDOWEVENT_SIZE_CHANGED)) {
            SDL_SetWindowSize(window, e.window.data1, e.window.data2);
        }
        if(e.type == SDL_QUIT) {
            SDL_Quit();
            return 0;
        }
    }
}
```
I'm not really sure if this issue would belong here, as this really is the product of dubious code, so could be considered a bug of the application, or would belong to sdl2-compat, as a quirk to be handled there (i did test with the latest sdl2 compat, and indeed i get the same "issue" when running the aplication through it). Also i don't know what the output of this would be on other platforms, as i only tested on windows

**Comment by Kontrabant** [comment]
Setting the window size while the window was in a fixed-size state in SDL2 was essentially undefined behavior. Some backends guarded against it in certain circumstances, while others didn't, and while most of the time the request would just be silently dropped, there were no guarantees. SDL3 makes every effort not to drop requested window state, particularly as requests are now considered be be asynchronous, and is sizing the window to exactly what you asked for. The documentation for `SDL_SetWindowSize()` reflects this as well:

>If, at the time of this request, the window in a fixed-size state, such as maximized or fullscreen, the request will be deferred until the window exits this state and becomes resizable again.

If SDL2 clients generally expect the undefined behavior here to be defined as a no-op, we should address that quirk in sdl2-compat.

**Comment by edo9300** [comment]
> The documentation for `SDL_SetWindowSize()` reflects this as well:
> 
> > If, at the time of this request, the window in a fixed-size state, such as maximized or fullscreen, the request will be deferred until the window exits this state and becomes resizable again.

Well, I guess I missed that piece of documentation (it being at the top rather than at the bottom made me skip it)

> If SDL2 clients generally expect the undefined behavior here to be defined as a no-op, we should address that quirk in sdl2-compat.

I don't really know how widespread that would be, as at worst it would be a blunder like in my case, rather than intentional code, but I guess if the major systems (x11/windows/cocoa, didn't test there tho) had it working by acting as noop, it could be made a sdl2 compat quirk.

**Comment by edo9300** [comment]
> (can't even remember why i did that, but i guess i never noticed because it worked as expected)

Well, I think I found what the source of this was, it was caused by the porting from sdl1 to sdl2, as in sdl1, you have to do an equivalent handling
> When SDL_RESIZABLE is passed as a flag to [SDL_SetVideoMode](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlsetvideomode.html) the user is allowed to resize the applications window. When the window is resized an SDL_VIDEORESIZE is report, with the new window width and height values stored in w and h, respectively. When an SDL_VIDEORESIZE is recieved the window should be resized to the new dimensions using [SDL_SetVideoMode](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlsetvideomode.html).

and I ported it over to my sdl2 code

**Comment by Kontrabant** [comment]
The more I look and test, the more I seem to find behavior like this, particularly in SDL2 titles. I'm working on more narrowly defining when the size and position can be set, as that seems to be what client apps/games expect. The changes are actually simplifying some backends that needed a lot of edge case handling for the previous behavior.

**Comment by icculus** [comment]
> it was caused by the porting from sdl1 to sdl2

Oh, wow, a third migration...that's honestly impressive.  :)

**Comment by Kontrabant** [comment]
This should no longer be a problem, as size/position changes that can't actually be applied to the current window state are now dropped to mimic the old behavior.  This should help avoid future porting issues and annoying window behavior when running via compatibility layers.
