### ISSUE TITLE
SDL_ShouldIgnoreJoystick disables steam deck input

### ISSUE THREAD

**Issue by dortamiguel** [libsdl-org/SDL#11579]
After updating my sdl build I noticed controller input stopped working on Steam Deck.

I'm running a windows build under proton.

If I comment this line here it starts working again https://github.com/libsdl-org/SDL/blob/main/src/joystick/windows/SDL_rawinputjoystick.c#L884

This line was introduced a few months ago in this commit  https://github.com/libsdl-org/SDL/commit/c41b2bb855d541cdb67d00bd99735b3cbad15951#diff-a45523b1115bb4dc77c94ed98405a20695ebd0ac608e90a53bbe815bea053144

On windows 11 and macos, controllers are working fine.

**Comment by slouken** [comment]
What is the vendor and product ID in that call?

**Comment by slouken** [comment]
Also, what game is this?

**Comment by dortamiguel** [comment]
I'm getting the following:

```
Vendor ID: 1118
Product ID: 654
Version Number: 1
```

I also connected an external PS5 controller and it gives me the same ids

My game is still not available on steam but I can send you a build if you want

**Comment by slouken** [comment]
Does this work?
```diff
+#ifdef SDL_PLATFORM_WIN32
+    if (SDL_GetHintBoolean("SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD", false) &&
+        SDL_GetHintBoolean("STEAM_COMPAT_PROTON", false)) {
+        // We are launched by Steam and running under Proton
+        // We can't tell whether this controller is a Steam Virtual Gamepad,
+        // so assume that Proton is doing the appropriate filtering of controllers
+        // and anything we see here is fine to use.
+        return false;
+    }
+#endif // SDL_PLATFORM_WIN32
+
```

**Comment by slouken** [comment]
This might also be a Proton bug. What version of Proton are you using? Do you get different results if you switch to Proton Experimental?

**Comment by dortamiguel** [comment]
You are right, in proton experimental the problem is gone.

But I also tried your fix and that makes the controller to work again in proton 9 and below.

**Comment by slouken** [comment]
What is the VID/PID of the Steam Deck controller and DualSense controller in Proton experimental?

**Comment by dortamiguel** [comment]
I'm getting the same for both controllers
```
Vendor ID: 10462
Product ID: 4607
Version Number: 0
```

**Comment by slouken** [comment]
Are you getting it at the application level too?

**Comment by dortamiguel** [comment]
I'm printing this values inside the sdl `RAWINPUT_AddDevice` function.

At the application level how I can get this values?

**Comment by slouken** [comment]
SDL_GetGamepadVendor() and SDL_GetGamepadProduct()

**Comment by dortamiguel** [comment]
you want me to use those too?

**Comment by slouken** [comment]
Yes please, I’d like to know whether the original device VID/PID is getting through to the application.

**Comment by dortamiguel** [comment]
Using SDL_GetGamepadVendor() and SDL_GetGamepadProduct() on steam deck I get

```
# Proton experimental
Steam Deck controller
vendor: 10462
product: 4613

PS5 controller
vendor: 1356
product: 3302

# Proton 9
Same for all controllers
vendor: 1118
product: 654
```

**Comment by slouken** [comment]
Perfect, thanks!
