### ISSUE TITLE
[SDL3] difference in blending mode in metal renderer (bug?)

### ISSUE THREAD

**Issue by superzazu** [libsdl-org/SDL#11576]
Hello!

I just noticed a case where two renderers would not have the same behaviour.

I have a simple PNG that uses indexed colours and is in RGB colour space:

```
General
Complete name                            : myfile.png
Format                                   : PNG
Format/Info                              : Portable Network Graphic
File size                                : 1.32 KiB

Image
Format                                   : PNG
Format/Info                              : Portable Network Graphic
Compression                              : Deflate
Format settings                          : Indexed-8
Width                                    : 64 pixels
Height                                   : 64 pixels
Display aspect ratio                     : 1.000
Color space                              : RGB
Bit depth                                : 8 bits
Compression mode                         : Lossless
Stream size                              : 1.32 KiB (100%)
```

If I load this file using SDL_Image, then do `SDL_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND)` and try to draw this texture to the screen:

- metal: image is not displayed (all back)
- gpu: image is displayed
- EDIT: opengl: image is displayed
- EDIT: software: image is displayed

I realise I might not want to set blend mode to `SDL_BLENDMODE_BLEND` on textures that have no alpha channel, however I think I'd better report this behaviour difference.

Here is a simple code to reproduce:

```c
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3_image/SDL_image.h>

int main(void) {
  SDL_Init(SDL_INIT_VIDEO);

  // SDL_SetHint(SDL_HINT_RENDER_DRIVER, "gpu");

  SDL_Window* window = NULL;
  SDL_Renderer* renderer = NULL;
  SDL_CreateWindowAndRenderer("test bug", 800, 600, 0, &window, &renderer);

  const char* renderer_name = SDL_GetRendererName(renderer);
  SDL_Log("using %s\n", renderer_name);

  SDL_Texture* tex = IMG_LoadTexture(renderer, "buggy.png");

  // line that triggers the problem:
  // note: no problem with SDL_BLENDMODE_BLEND_PREMULTIPLIED
  SDL_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND);

  int should_quit = 0;
  while (!should_quit) {
    SDL_Event e;
    while (SDL_PollEvent(&e) != 0) {
      if (e.type == SDL_EVENT_QUIT) {
        should_quit = 1;
      }
    }

    SDL_RenderClear(renderer);
    SDL_RenderTexture(renderer, tex, NULL, NULL);
    SDL_RenderPresent(renderer);
  }

  SDL_Quit();
  return 0;
}
```

Have a good day!

EDIT: I also tested with OpenGL & software renderers, which seem to have the same behaviour as "gpu" ; so it looks like a bug with the metal renderer?

**Comment by superzazu** [comment]
I also tried with `opengl` + `software` renderers and I have the same results as `gpu`, so it may be a metal renderer bug?

Here's a test image that reproduces the bug on my computer

![buggy2](https://github.com/user-attachments/assets/2ec1bddb-c4c0-4a7b-a447-30fee3a1ed3d)

**Comment by slouken** [comment]
Fixed, thanks for the great repro case!
