### ISSUE TITLE
Vulkan surface resize issue 

### ISSUE THREAD

**Issue by bl4ckb0ne** [libsdl-org/SDL#11597]
I'm currently playing with Vulkan and SDL3 (3.1.6 preview and master) and I noticed that upon resizing (adding `SDL_WINDOW_RESIZABLE` to the `SDL_CreateWindow` creation flag) on Wayland, `vkAcquireNextImageKHR` never returns `VK_SUBOPTIMAL_KHR` or `VK_ERROR_OUT_OF_DATE_KHR`.

I am using the latest Sway release (1.10) and the window gets resized soon after creation (from 640x480 to whatever's tiled). Using `SDL_VIDEODRIVER=x11`  I do get `VK_SUBOPTIMAL_KHR`  but not with `SDL_VIDEODRIVER=wayland`.

Here's a log with `WAYLAND_DEBUG=1` [log.txt](https://github.com/user-attachments/files/18040082/log.txt) I have added a log message with the actual window size from `SDL_GetWindowSize` showing the resize happening. 

My client gets the `xdg_surface.configure` event but only the `wl_viewport` and `wl_region` gets updated.

**Comment by flibitijibibo** [comment]
I remember fussing with this on Wayland locally, particularly when we were deciding whether or not to expose size info to the swapchain texture API... @thatcosmonaut can correct me but I believe Wayland _never_ emits suboptimal/out-of-date because Wayland _always_ considers surfaces to be valid even if the underlying wl_surface size changes. At one point we were deciding if the resize should be handled inside the GPU backend or the application, I _thought_ we went with the former but maybe I'm wrong on that.

**Comment by thatcosmonaut** [comment]
> I remember fussing with this on Wayland locally, particularly when we were deciding whether or not to expose size info to the swapchain texture API... @thatcosmonaut can correct me but I believe Wayland _never_ emits suboptimal/out-of-date because Wayland _always_ considers surfaces to be valid even if the underlying wl_surface size changes. At one point we were deciding if the resize should be handled inside the GPU backend or the application, I _thought_ we went with the former but maybe I'm wrong on that.

Yeah our solution was to force-resize the swapchain by hooking into the window resize event in the GPU backend.

**Comment by bl4ckb0ne** [comment]
So that would be a driver issue rather than a SDL issue? I haven't try another compositor beside sway. Hooking the window resize event was next on my list. Thanks for clarifying it.

**Comment by thatcosmonaut** [comment]
It's only an issue insofar as different presentation systems decide to have different behavior, and the Vulkan spec allows this. It's a little annoying that Wayland chose to act differently from everyone else, but c'est la vie.

**Comment by bl4ckb0ne** [comment]
I came across your issue on [mesa](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10254), the Wayland WSI is already able to return [VK_SUBOPTIMAL_KHR](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_wayland.c#L1696) but not for size, which is a bit annoying.

I'll see what I can do for this.

**Comment by bl4ckb0ne** [comment]
I managed to talk to the relevant people about this issue. I'll write it out here for the next one wondering why `vkAcquireNextImageKHR` can't return `VK_SUBOPTIMAL_KHR` or `VK_ERROR_OUT_OF_DATE_KHR`.

Simply put, the Mesa wayland WSI [1] is not aware of the surface being drawn on, it simply handles buffers and provides a place to draw on. The WSI has no way at the moment to get the window size from the compositor and issue a `VK_SUBOPTIMAL_KHR` result to the client. Even if it would make sense logically to inform the client that the swapchain does not match the window size, Wayland still consider the buffer valid and will display it no matter what.

Listening to the `SDL_EVENT_WINDOW_RESIZED` event is the right way to go to resize the swapchain and continue to render with an accurate buffer.

[1]: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_wayland.c#L100

**Comment by Kontrabant** [comment]
>Even if it would make sense logically to inform the client that the swapchain does not match the window size, Wayland still consider the buffer valid and will display it no matter what.

And if the viewport protocol is involved, which it almost always is, it removes whatever remaining concept of buffer size = window size there may have been, as any portion of the buffer can be mapped and scaled to the output window.
