### ISSUE TITLE
Before and after all events

### ISSUE THREAD

**Issue by 1vanK** [libsdl-org/SDL#11592]
Nuklear requires to call functions before and after all events

https://github.com/Immediate-Mode-UI/Nuklear/blob/master/demo/sdl_opengl3/main.c#L158-L164
```
        SDL_Event evt;
        nk_input_begin(ctx);
        while (SDL_PollEvent(&evt)) {
            if (evt.type == SDL_QUIT) goto cleanup;
            nk_sdl_handle_event(&evt);
        }
        nk_sdl_handle_grab(); /* optional grabbing behavior */
        nk_input_end(ctx);

       update();
       draw();
```
How to do this when using SDL_MAIN_USE_CALLBACKS?

How can we determine that a new frame has started when using callbacks?
It may be necessary to have another callback that signals that a new frame has started.

Of course, we can come up with some kind of hack that will turn on some flag when the first event in the frame arrives and turn it off in SDL_AppIterate(), but it's not very nice.

**Comment by 1vanK** [comment]
```
static bool nk_input_beginned = false;

void App::handle_sdl_event(const SDL_Event& event)
{
    // First event in frame
    if (!nk_input_beginned)
    {
        DV_LOG->write_info("BEGIN");
        nk_input_beginned = true;
        nk_input_begin(ctx);
    }

    nk_sdl_handle_event(&event);

    ...
}

void App::update(u64 ns)
{
    if (nk_input_beginned)
    {
        nk_input_beginned = false;
        nk_sdl_handle_grab();
        nk_input_end(ctx);
        DV_LOG->write_info("END");
    }

   if (nk_begin(ctx, "Demo", nk_rect(50, 50, 230, 250),
    NK_WINDOW_BORDER | NK_WINDOW_MOVABLE | NK_WINDOW_SCALABLE |
    NK_WINDOW_MINIMIZABLE | NK_WINDOW_TITLE))
   {
       nk_end(ctx);
   }
```

not works, because there may be frames without events, and nuklear doesn't know that a new frame has started and call nk_begin(...) several times with same data

**Comment by 1vanK** [comment]
Or maybe add a new event "SDL_EVENT_NEW_FRAME" that will raise every frame before all other events

**Comment by slouken** [comment]
Each app iterate is a frame, so can you just call nk_input_begin() at the end of app init and then at the end of app iterate?

**Comment by 1vanK** [comment]
> Each app iterate is a frame, so can you just call nk_input_begin() at the end of app init and then at the end of app iterate?

This will not solve the problem globally. Let's say I increment a frame counter by one every frame. I can only do this in Update(). But the event handler can also contain game logic that uses the frame counter.

**Comment by 1vanK** [comment]
This may solve the problem in a specific case, but it won't solve it globally. Plus the nk_input_end() function won't be called in the last frame and will also have to be moved to the next event. Looks like a hack.

**Comment by slouken** [comment]
Don't use the main callbacks? :)
A hypothetical frame event would work the same way, it would be sent before the first iterate and then after each iterate. It's the same flow, just a different mechanism.

**Comment by 1vanK** [comment]
> Don't use the main callbacks? :)

https://github.com/libsdl-org/SDL/issues/9102

**Comment by slouken** [comment]
> > Don't use the main callbacks? :)
> 
> #9102

Using main callbacks isn't necessary for that fix, you can also watch for expose events and redraw in the event handling.

**Comment by 1vanK** [comment]
> Using main callbacks isn't necessary for that fix, you can also watch for expose events and redraw in the event handling.

It's clear that I can implement it myself, but it makes sense when something is already ready without unnecessary code and is available to everyone. In the end, I can add the events I need in my fork.

**Comment by slouken** [comment]
Okay, feel free to create a PR once you've done that, so we can see whether it makes sense generally for SDL.

Thanks!

**Comment by 1vanK** [comment]
> A hypothetical frame event would work the same way, it would be sent before the first iterate and then after each iterate. It's the same flow, just a different mechanism.

Yes, you are right.

**Comment by slouken** [comment]
If you still want to use events and don't want to modify SDL, you can use a user event to do the same thing.

**Comment by 1vanK** [comment]
> Each app iterate is a frame, so can you just call nk_input_begin() at the end of app init and then at the end of app iterate?

```
new_frame()
SDL_DelayPrecise() from SDL_EnterAppMainCallbacks()
update()
draw()
```

instead

```
new_frame()
update()
draw()
SDL_DelayPrecise() from SDL_EnterAppMainCallbacks()
```

(different time in functions)
