### ISSUE TITLE
[SDL3] Make an extern function for SDL_INIT_INTERFACE

### ISSUE THREAD

**Issue by edwardgushchin** [libsdl-org/SDL#11607]
Hi! Problem: When it comes to SDL shells for other languages, you can't call macros directly via PInvoke, you can only rewrite them for ease of use in your language, but SDL_INIT_INTERFACE is not a simple macro, and you can't rewrite it (because its implementation contains a whole bunch of other macros and internal SDL methods).
And without it it is impossible to initialize and use such things as IOStreamInterface, StorageInterface and VirtualJoystickDesc.

Consequently, the ability to create, for example, virtual joysticks in shells is lost.

Is it possible to make a function that will be available through PInvoke, with which it will be possible to initialize the necessary interfaces?

Thanks!

**Comment by slouken** [comment]
We can't make that an internal function, but you can pretty easily implement it yourself:
```c
SDL_memset(p, 0, sizeof(*p));
p->version = sizeof(*p);
```
