### ISSUE TITLE
Wayland video driver not being used on Wayland devices

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#11603]
As of recently (I can try to bisect the exact commit if necessary), SDL will no longer use the Wayland driver on any of my Wayland devices, including Ubuntu 24.04. I verified in the system settings that I'm using Wayland and not Xorg.

Here's a basic test program that I used with latest commit on main (f64e9a5):

```c
#include <SDL3/SDL.h>

int main(void)
{
  if (SDL_Init(SDL_INIT_VIDEO) < 0) {
    SDL_Log("Could not init SDL: %s", SDL_GetError());
    return 1;
  }

  SDL_Log("Video driver: %s\n", SDL_GetCurrentVideoDriver());

  SDL_Quit();

  return 0;
}
```

This prints: `Video driver: x11`.

---

Some extra info:
- When configuring SDL, I verified that Wayland support is enabled:
      --   SDL_WAYLAND                 (Wanted: ON): ON
      --   SDL_WAYLAND_LIBDECOR        (Wanted: ON): ON
      --   SDL_WAYLAND_LIBDECOR_SHARED (Wanted: ON): ON
      --   SDL_WAYLAND_SHARED          (Wanted: ON): ON
- I enabled verbose logging for all categories, and SDL seems to attempt to load some Wayland and libdecor functions: `Failed loading wl_egl_window_create: /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: _wl_egl_window_create`; `Failed loading libdecor_unref: /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: _libdecor_unref`

**Comment by slouken** [comment]
We default to X11 unless certain Wayland extensions are available, for performance reasons. What happens if you set the environment variable `SDL_VIDEO_DRIVER=wayland`?

**Comment by Semphriss** [comment]
With `SDL_VIDEO_DRIVER=wayland`, it reports using Wayland as expected.

Is the change recent? I was quite surprised to see my apps switch to X11, given that my system has "regular" Wayland support.

It's mostly an issue for Ubuntu Touch phones, for which I'm currently working on an SDL port, and whose support for X11 is abysmal. I can manually set `SDL_HINT_VIDEO_DRIVER` to `wayland`, though I should instruct app porters to do the same.

**Comment by slouken** [comment]
Yes, it was made recently, due to performance issues with current Wayland support. See https://github.com/libsdl-org/SDL/pull/9383 for details.
