### ISSUE TITLE
Simplify testgpu_spinning_cube.c

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11614]
We should simplify the spinning cube example, remove the SDL test dependency, switch to callbacks to remove emscripten ifdefs, etc.

**Comment by icculus** [comment]
We can do that, but that's also likely exactly what we're going to do for the examples directory.

(There is a little blurring between "test" and "examples" now, and this one is a good example of that.)

**Comment by slouken** [comment]
Yeah, and I realized that the clear example also has a test library dependency, which is totally appropriate for the programs in the test directory.

So… any ETA for the WebGPU implementation? 😉
I know @thatcosmonaut has said he isn’t working on it, but is there any hints he can give that would help speed that along, or any functionality in the API that can’t be done in WebGPU?

**Comment by flibitijibibo** [comment]
#10768 shows some promise for WebGPU but it's probably still a ways off; it's not one of our targets so it'll almost certainly require additional investing to get up to speed.

This could also be rolled into our issue filed at https://github.com/TheSpydog/SDL_gpu_examples/issues/12 which is tracking the process of moving the repo to the examples/ folder. Again though, we've had to put this to the side while we focus on other stuff (mainly Xbox and PS5 at the moment).
