### ISSUE TITLE
VULKAN_ClaimWindow() can return false without setting error

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11613]
@thatcosmonaut, can you do an audit and make sure the GPU API functions always return an error if they return false, and not just rely on logging? In this particular case, in the video https://youtu.be/PuE98lipGU8?t=4509, VULKAN_INTERNAL_CreateSwapchain() returned false and the streamer had no idea why it failed.

**Comment by thatcosmonaut** [comment]
We already audited this but I'm sure some stuff slipped through the cracks. I went through the swapchain initialization code and found a couple of things but unrelated to this error.

More importantly, I cannot reproduce this issue at all on Windows 10 or Fedora Linux. I tried to set up some code similar to the code that caused the failure in the video:

```c
	SDL_Renderer *renderer;
	SDL_CreateWindowAndRenderer("window", 640, 480, windowFlags, &context->Window, &renderer);

	context->Device = SDL_CreateGPUDevice(
		SDL_GPU_SHADERFORMAT_SPIRV | SDL_GPU_SHADERFORMAT_DXIL | SDL_GPU_SHADERFORMAT_MSL,
		true,
		NULL);

	if (context->Device == NULL)
	{
		SDL_Log("GPUCreateDevice failed: %s", SDL_GetError());
		return -1;
	}

	if (!SDL_ClaimWindowForGPUDevice(context->Device, context->Window))
	{
		SDL_Log("GPUClaimWindow failed: %s", SDL_GetError());
		return -1;
	}
```

On Windows SDL_GetError() gives me VK_ERROR_NATIVE_WINDOW_IN_USE_KHR. On Fedora it runs without error. I'm curious what the dev environment is in the video.

**Comment by slouken** [comment]
Fixed by https://github.com/libsdl-org/SDL/pull/11615
