### ISSUE TITLE
Large SDL DLL size

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11620]
The 2.30.10 mingw release includes debug symbols, so the DLL is huge (12865 KB vs 2231 KB in 2.30.9). Can we strip it before archiving for release?

**Comment by madebr** [comment]
I forgot to add `-O2 -g0` when I switched SDL2's mingw build from CMake to autotools.

**Comment by slouken** [comment]
I can drop in the win32 DLLs and re-upload the archives. Can you fix it for the next release?

**Comment by madebr** [comment]
SDL2 (SDL and satellite libraries) mingw binaries, built by autotools, are now built with `CFLAGS=-O2` and `LDFLAGS=-Wl,-s`.

SDL3 does not have this issue, since we use `RelWithDebInfo` already.
I'm not 100% sure why stripping the output binary is not needed there to reduce the file size.
