### ISSUE TITLE
SDL_EVENT_WINDOW_CLOSE_REQUESTED triggered unexpectedly on window focus loss

### ISSUE THREAD

**Issue by FromNorthProjekt** [libsdl-org/SDL#11649]
I am experiencing an issue where SDL_EVENT_WINDOW_CLOSE_REQUESTED is triggered unexpectedly in SDL3 when switching focus to another program’s window (e.g., a browser). This behavior is not expected, as this event should only be fired when the user explicitly requests to close a window (e.g., by clicking the close button or pressing Alt+F4).

`			VG_ASSERT_MSG(e.window.windowID != 0, "Window ID is 0");

			//close the window when user clicks the X button or alt-f4s
			if (e.type == SDL_EVENT_QUIT) // no need to check for window id
			{
				Application::GetApp()->m_ShouldTerminate = true;
				break; // no need to continue processing events
			}

			auto window = DisplayWindow::Library::GetWindow(e.window.windowID);

                       //for multiple windows (only if more than one window is currently opened)
			if (e.type == SDL_EVENT_WINDOW_CLOSE_REQUESTED) // -->BUG :: this get triggered  when focus loss
			{
				if (window->IsMainWindow())
				{
					VG_CORE_WARN("Closing The Main Window");
					Application::GetApp()->m_ShouldTerminate = true;
					DisplayWindow::Library::CloseWindow(window->GetWindowID());
					break;
				}
				else
				{
					VG_CORE_WARN("Closing Window ID: {0}", window->GetWindowID());
					DisplayWindow::Library::CloseWindow(window->GetWindowID());
					continue;
				}
			}`

**Comment by icculus** [comment]
Did this resolve itself in some form, or did this get closed by accident?
