### ISSUE TITLE
[SDL3] Can not disable HIDAPI on macOS

### ISSUE THREAD

**Issue by ivan-ushakov** [libsdl-org/SDL#11647]
I tried to disable HIDAPI on macOS with this configuration in CMake:

```
SET(SDL_HIDAPI OFF CACHE BOOL "")
add_subdirectory(ThirdParty/SDL)
```

but I get compile error `call to undeclared function 'hid_darwin_set_open_exclusive'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]` because of this code:

```c++
#ifdef SDL_PLATFORM_MACOS
    hid_darwin_set_open_exclusive(0);
#endif
```

Is it possible to disable HIDAPI on macOS?

**Comment by sezero** [comment]
Maybe something like the following? (Not tested.)

```diff
--- a/src/hidapi/SDL_hidapi.c
+++ b/src/hidapi/SDL_hidapi.c
@@ -1244,3 +1244,3 @@ int SDL_hid_init(void)
 
-#ifdef SDL_PLATFORM_MACOS
+#if defined(HAVE_PLATFORM_BACKEND) && !defined(SDL_HIDAPI_DISABLED)
     hid_darwin_set_open_exclusive(0);
```

**Comment by sezero** [comment]
( CC @slouken )

**Comment by slouken** [comment]
The patch looks good to me, I'm just waiting for feedback from @ivan-ushakov

**Comment by ivan-ushakov** [comment]
> The patch looks good to me, I'm just waiting for feedback from @ivan-ushakov

It works, thank you!

**Comment by sezero** [comment]
OK, patch is in. Thanks for the issue report.
