### ISSUE TITLE
SDL_Process created with pipe_stdio set to true hangs on large output.

### ISSUE THREAD

**Issue by failedev17** [libsdl-org/SDL#11645]
```
int main(){
    const char* args[] {"clang++", "--help", nullptr};
    SDL_Process* p = SDL_CreateProcess(args, true);
    SDL_WaitProcess(p, true, nullptr);
    SDL_DestroyProcess(p);
}

```
Side note, Using SDL_ReadIO and SDL_LoadFile_IO on p.stream before and after flushing/closing doesn't give the output that was written to the file. I don't know if this is intended or not.
```
	Process p;
	p.stream = SDL_IOFromFile("temp.txt", "w+b");
	SDL_PropertiesID props = SDL_CreateProperties();
	SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, (void *)args.data());
	SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_PROCESS_STDIO_REDIRECT);
	SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_STDOUT_POINTER, p.stream);
	p.process = SDL_CreateProcessWithProperties(props);
	if(!p.process){
		printf("%s\n", SDL_GetError());
	}
	SDL_DestroyProperties(props);

```

OS : Windows 10.

**Comment by madebr** [comment]
Your code also blocks on Linux.
clang's help is very long and will fill the pipe buffer (64kiB on Linux).
What's happening is that the kernel suspends the process (because `write(2)` is a blocking write) until the pipe buffer is drained.

Use `SDL_ReadProcess` to read all stdout in one go:
```c
#include <SDL3/SDL.h>
int main(){
    const char* args[]= {"clang++", "--help", NULL};
    SDL_Process *p = SDL_CreateProcess(args, true);
    int ec;
    size_t s;
    void *d = SDL_ReadProcess(p, &s, &ec);
    SDL_Log("Got %p s=%u", d, (unsigned int)s);
    SDL_Log("%s", (const char *)d);
    SDL_WaitProcess(p, true, NULL);
    SDL_DestroyProcess(p);
    return 0;
}
```

Alternatively, you read chunks of data when it becomes available as long as the process is alive:
```c
#include <SDL3/SDL.h>
int main(){
    const char* args[]= {"clang++", "--help", NULL};
    SDL_Process *p = SDL_CreateProcess(args, true);
    SDL_IOStream *clang_output = SDL_GetProcessOutput(p);
    
    while (!SDL_WaitProcess(p, false, NULL)) {
      char buffer[4096];
      size_t nb = SDL_ReadIO(clang_output, buffer, sizeof(buffer)-1);
      buffer[nb] = '\0';
      if (nb) {
        SDL_Log("nb=%u", (unsigned)nb);
        SDL_Log("Got %s", buffer);
      }
    }
    int rc;
    SDL_WaitProcess(p, true, &rc);
    SDL_Log("rc=%d", rc);
    SDL_DestroyProcess(p);
    return 0;
}
```

**Comment by failedev17** [comment]
Thanks for the info. I guess it should be mentioned in the SDL_WaitProcess docs somewhere. I thought what I had to do was, SDL_WaitProcess() then do a SDL_ReadProcess() and not the other way around.

**Comment by madebr** [comment]
The process subsystem is relatively very prone to a deadlock. My code above would lock when clang would read from stdin (close stdin of the subprocess after startup to avoid this. I have to check myself now what would happen if a subprocess opens `/dev/tty` after having closed stdin)
You need to code very careful to avoid this.

You're right about the docs.

**Comment by slouken** [comment]
The documentation has been updated, thanks!
