### ISSUE TITLE
Random garbage filters appearing in the drop-down in file dialogs

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#11653]
![image](https://github.com/user-attachments/assets/46e7f0be-a908-4239-ac65-5f5607289821)

This is quite easy to reproduce. Latest SDL3, Windows 10.
```
#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL_main.h>
#include <SDL3/SDL.h>

SDL_AppResult SDL_AppInit(void ** win, int, char**) {
	SDL_Init(SDL_INIT_VIDEO);
	*win = (void*) SDL_CreateWindow(nullptr, 1000, 500, 0);
	return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppIterate(void*) {
	SDL_Delay(1);
	return SDL_APP_CONTINUE;
}

static void SDLCALL Callback(void* userdata, const char* const* files, int filter) {
}
const SDL_DialogFileFilter filters[3] = {
	{ "PNG images", "png" },
	{ "BMP images", "bmp" },
	{ "All files", "*" }
};

SDL_AppResult SDL_AppEvent(void * win, SDL_Event* event) {
	switch (event->type) {
	case SDL_EVENT_KEY_UP:
		SDL_ShowOpenFileDialog(Callback, nullptr, (SDL_Window*)win, filters, sizeof(filters) / sizeof(*filters), nullptr, false);
		break;
	case SDL_EVENT_QUIT:
		return SDL_APP_SUCCESS;
	}
	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void*, SDL_AppResult result) {
}
```

**Comment by slouken** [comment]
@Semphriss, can you take a look?

**Comment by Semphriss** [comment]
Yes, I'll check that whenever I have a moment.

**Comment by RT2Code** [comment]
I have the same issue. It also happens with the titles. With the following code:
```c
	SDL_PropertiesID properties = SDL_CreateProperties();

	const char* title = "Open";
	SDL_SetStringProperty(properties, SDL_PROP_FILE_DIALOG_TITLE_STRING, title);

	SDL_DialogFileFilter filters[]{
		{"JPG", ".jpg"},
		{"PNG", ".png"}
	};
	SDL_SetPointerProperty(properties, SDL_PROP_FILE_DIALOG_FILTERS_POINTER, &filters);
	SDL_SetNumberProperty(properties, SDL_PROP_FILE_DIALOG_NFILTERS_NUMBER, 2);

	SDL_ShowFileDialogWithProperties(SDL_FILEDIALOG_OPENFILE, &callback, nullptr, properties);
```

Here's what I get:
![Screenshot (7)](https://github.com/user-attachments/assets/c5fb18b9-7b7c-4f68-987c-c17013f6bfdc)

Could it be related to string encoding? I'm using the latest commit (https://github.com/libsdl-org/SDL/commit/b84f150d0669592f4d4eedac2ea893c61194ba72) on Windows 11.

Also, if I specify a parent window, the dialog won't open.

**Comment by adamkewley** [comment]
Experiencing the same thing after integrating `SDL_ShowOpenFileDialog` into [opensim-creator](https://github.com/ComputationalBiomechanicsLab/opensim-creator):

![image](https://github.com/user-attachments/assets/c267f410-d826-4f8b-a20b-6364dfbb7af0)

I'm not using static strings as above, but `std::string`s that are allocated and held in the SDL callback's closure, as specified in the docs (paraphrasing what I understand: "the filter list must be valid at least until the callback is invoked").

I tried reading through the windows implementation code but there's quite a bit of string juggling going on in there (not SDL's fault, thank Windows' `wchar` API 😄 ), but it looks very... out-of-bounds-ey

**Comment by adamkewley** [comment]
Thanks @Semphriss . Completely understand the challenges around that part of the codebase! Lots of string wrangling to do ⚙️
