### ISSUE TITLE
[SDL2] Possible crash in SDL_CreateJoystickGUID on Windows when SDL_hid_device_info is zeroed, or missing vendor/product info

### ISSUE THREAD

**Issue by SupergiantDexter** [libsdl-org/SDL#11658]
I received a crash report in `SDL_Init()` while a PS4 controller was plugged in over USB (model no. CUH-ZCT1). I have the offending device on-hand but have been unable to repro on my machine. I followed the minidump and concluded that passing a null `product_name` into `SDL_strlcpy` is the site of the read violation, and I can contrive that crash by zeroing out the `SDL_hid_device_info` struct higher up the stack. My suspicion is that the end user's machine is unable to fully identify the device name, vendor id and product id (possibly more), which eventually trips up `SDL_CreateJoystickGUID`.

I have the repro and a suspect fix in the patch, though I'm unsure if this change is appropriate / necessary. Given this doesn't repro in a "real" scenario, it would also be reasonable to me to close this if the root cause is outside SDL (e.g. user needs to reinstall a driver).
 
OS: Windows 11
Branch: SDL2 (ad93f50ee6408c90eec0d96867b41046392bb426)

```diff --git a/src/joystick/SDL_joystick.c b/src/joystick/SDL_joystick.c
index 4fe0b6a25..f585c5945 100644
--- a/src/joystick/SDL_joystick.c
+++ b/src/joystick/SDL_joystick.c
@@ -2511,7 +2511,9 @@ SDL_JoystickGUID SDL_CreateJoystickGUID(Uint16 bus, Uint16 vendor, Uint16 produc
             guid.data[14] = driver_signature;
             guid.data[15] = driver_data;
         }
-        SDL_strlcpy((char *)guid16, product_name, available_space);
+        if (product_name) {
+            SDL_strlcpy((char *)guid16, product_name, available_space);
+        }
     }
     return guid;
 }
diff --git a/src/joystick/hidapi/SDL_hidapijoystick.c b/src/joystick/hidapi/SDL_hidapijoystick.c
index 28209fa5e..3b31e7ca7 100644
--- a/src/joystick/hidapi/SDL_hidapijoystick.c
+++ b/src/joystick/hidapi/SDL_hidapijoystick.c
@@ -889,6 +889,7 @@ static SDL_HIDAPI_Device *HIDAPI_AddDevice(const struct SDL_hid_device_info *inf
         SDL_free(device);
         return NULL;
     }
+    //SDL_memset(info, 0, sizeof(*info)); // NOCOMMIT(Dexter): force null entire device struct, including product strings
     device->seen = SDL_TRUE;
     device->vendor_id = info->vendor_id;
     device->product_id = info->product_id;

**Comment by slouken** [comment]
Thanks for the report! This was fixed in SDL3 but hadn't been backported to SDL2.

I've cherry-picked it for the next release in https://github.com/libsdl-org/SDL/commit/ca8e33375bfa1d2ffff1dc81b401c0c27e1ac5a9.
