### ISSUE TITLE
Random characters appearing in the title in file dialogs

### ISSUE THREAD

**Issue by RT2Code** [libsdl-org/SDL#11661]
It's kind of the same issue as in https://github.com/libsdl-org/SDL/issues/11653, except it happens in the title. If the default title value is used, it's fine. But if a custom title is specified, random garbage characters start to appear at the end of the string.

Example:
![396769440-0766c9fb-1ab7-46f2-95f1-870432886f32](https://github.com/user-attachments/assets/813ecbde-237f-405a-8cf7-8de979625db9)

**Comment by RT2Code** [comment]
I forgot to tag you @Semphriss. And thanks for your hard work on this feature, it's a great addition to the SDL3.

**Comment by Semphriss** [comment]
Leaving a message so that this shows up on my front page.

**Comment by AntTheAlchemist** [comment]
I'm also getting garbage appearing by default in the filename field.

![image](https://github.com/user-attachments/assets/0935cb79-cf67-4810-8023-e3e6dedaadde)

**Comment by Semphriss** [comment]
@AntTheAlchemist Can you open a new issue with the filename bug so that I don't forget about it?
