### ISSUE TITLE
SDL_GPU shading problems

### ISSUE THREAD

**Issue by jkinz3** [libsdl-org/SDL#11670]
The SDL_GPU library is giving me a super weird problem that looks like this.
![image](https://github.com/user-attachments/assets/598fa4c7-b22f-48a9-b95c-9d04dd4441e7)

Basically i'm intending to draw the world normals of the mesh but as you can see, halfway down the model, the values get all sorts of effed up. I did some digging and found that it might be due to an interpolation issue between the vertex and fragment shader but I'm not sure how to fix it.

I'm including the source code for the a super simple program that demonstrates this. 
[SDLBug.zip](https://github.com/user-attachments/files/18200978/SDLBug.zip)

For a quick overview, however, here is the vertex shader. It's HLSL that I used SDL_GPU_shadercross to compile into SPIRV
```
struct Vertex
{
	float4 pos : TEXCOORD0;
	float3 norm : TEXCOORD1;
};

struct PSInput
{
	float4 PositionPS : SV_POSITION;
	float3 Normal : NORMAL;
};

cbuffer TransformConstants : register(b0, space1)
{
	float4x4 WVP;
	float4x4 World;
}


PSInput main( Vertex vert)
{
	PSInput vout;
	vout.PositionPS = mul(vert.pos, WVP);
	vout.Normal = mul(vert.norm, (float3x3)World);

	return vout;
}
```

And here's the fragment shader:

```
struct PSInput
{
	float4 PositionPS : SV_POSITION;
	float3 Normal : NORMAL;
};


float4 main(PSInput pin) : SV_TARGET
{
	float3 N = normalize(pin.Normal);
	return float4(N, 1.0f);
}
```

If the issue is on my end, please let me know what it is because i've been racking my brain about this for a few days now. The only thing I can think of is that the issue is related to the semantics TEXCOORD, however using any other semantic (such as NORMAL) results in an error because SDL_GPU assumes that the semantics are all TEXCOORD and there isn't any documentation about semantics at all that would explain the proper way to handle them.

**Comment by slime73** [comment]
For visualizing normals (or any other [-1, 1] range normalized value) you'd want to convert them to [0, 1], something like this:
```hlsl
float4 main(PSInput pin) : SV_TARGET
{
	float3 N = normalize(pin.Normal);
	return float4(N * 0.5 + 0.5, 1.0f);
}
```

**Comment by prcastro** [comment]
https://github.com/libsdl-org/SDL/issues/11672

I had the same problem with HLSL semantics btw

**Comment by jkinz3** [comment]
> For visualizing normals (or any other [-1, 1] range normalized value) you'd want to convert them to [0, 1], something like this:
> 
> ```hlsl
> float4 main(PSInput pin) : SV_TARGET
> {
> 	float3 N = normalize(pin.Normal);
> 	return float4(N * 0.5 + 0.5, 1.0f);
> }
> ```

I appreciate the reply but that's not really the issue.

**Comment by thatcosmonaut** [comment]
What exactly is the issue then? Normal vectors can have negative components, and negative color values get clamped to 0, which is why you see the black colors on the bottom right. If you want to visualize the normals in terms of color then the value have to be in a 0-1 range. 

I recommend that you familiarize yourself with a graphics debugging tool like [RenderDoc](https://renderdoc.org)/. The odds that this is an SDL issue are extremely low.

**Comment by thatcosmonaut** [comment]
I'm closing this, if it turns out to be a problem on our end feel free to reopen it.
