### ISSUE TITLE
[FEATURE REQUEST] Lower level memory allocation

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#11671]
Right now SDL only provides standard memory allocation functions(malloc,calloc,free) but i think It would be useful to offer an API that allows to operate on memory on a lower level. The API may look something like this:
- SDL_ReserveMemory(size_t size)
- SDL_ReleaseMemory(void* addr)
- SDL_CommitMemory(void* addr, size_t size)
 - SDL_DecommitMemory(void* addr, size_t size)
- SDL_ProtectMemory(void* addr, size_t size)

On windows this functionality can be implemented with VirtualAlloc, VirtualFree, etc...

**Comment by slouken** [comment]
We don't have any plans to add this.
