### ISSUE TITLE
GPU: Topology error drawing line or points in Direct3D12 debug mode

### ISSUE THREAD

**Issue by spriest487** [libsdl-org/SDL#11680]
I'm seeing the following error message when attempting to draw using a pipeline with the primitive type set to `SDL_GPU_PRIMITIVETYPE_LINELIST`, `SDL_GPU_PRIMITIVETYPE_LINESTRIP`, or `SDL_GPU_PRIMITIVETYPE_POINTLIST`:

```
D3D12 ERROR: ID3D12CommandList::DrawIndexedInstanced: The primitive topology does not belong to the appropriate group specified by the current pipeline state. [ EXECUTION ERROR #611: PRIMITIVE_TOPOLOGY_MISMATCH_PIPELINE_STATE]
```

This appears to be coming from the Direct3D debug layer, and it renders as expected when debug mode is off, although the error is always visible in RenderDoc. 

None of the changes I've tried making to any of the other pipeline info parameters, the vertex data, or the shaders seem to have any effect on this. I can repro this on any of the programs in [this samples repo](https://github.com/TheSpydog/SDL_gpu_examples) by changing only the primitive type (and adding the `"direct3d12"` name parameter to the `SDL_CreateGPUDevice` call).

I'm not too familiar with D3D12 itself but I'm trying to port an existing program that uses Vulkan to use SDL3 GPU instead. Using Vulkan, either directly as in the original program or as a backend through SDL, changing the primitive type works exactly as expected with no other changes necessary.

Looking into the SDL source a bit I see this line in `D3D12_CreateGraphicsPipeline`:

```
psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
```

In `D3D12_BindGraphicsPipeline`, the topology is set correctly in the command list:

```
ID3D12GraphicsCommandList_IASetPrimitiveTopology(d3d12CommandBuffer->graphicsCommandList, SDLToD3D12_PrimitiveType[pipeline->primitiveType]);
```

This matches what I can see in RenderDoc so this looks like the source of the mismatch?

**Comment by flibitijibibo** [comment]
Yeah, probably just that missing conversion where it's hardcoded to triangles instead, specifically when it creates the pipeline object - currently away from my Xbox setup but can still review a change from somebody else pretty quickly.

**Comment by flibitijibibo** [comment]
Line in question:

https://github.com/libsdl-org/SDL/blob/main/src/gpu/d3d12/SDL_gpu_d3d12.c#L2867

Should be as simple as replacing the value with the array used elsewhere, the input value is in the createInfo structure.

**Comment by flibitijibibo** [comment]
@spriest487, does #11683 fix this for you? I don't have a D3D12 setup at the moment so I'm patching this blindly.

**Comment by spriest487** [comment]
I tried fixing it myself locally and ended up with something very similar to @TheSpydog 's change. I don't have access to an Xbox for testing right now, but I assume it's exactly the same as Windows 11 where it seems to work great.
