### ISSUE TITLE
using on-screen keyboard on iOS crashes in event poll

### ISSUE THREAD

**Issue by ronaaron** [libsdl-org/SDL#11708]
I've _almost_ [got my app](https://8th-dev.com/zemanim2.html) running on iOS now, but there's one problem.

In text entry fields, I call SDL_StartTextInput() and the on-screen keyboard pops up as expected. But when I press any 'key', the app crashes.

According to XCode this is happening in SDL_PollEvent() (I changed to using SDL_WaitEventTimeout() with the same result).

```
Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)
A bad access to memory terminated the process.
```
TBF, I'm compiling SDL2 manually, but I use the configure script except I also add the UIKIT defines so it'll work on iOS. Anyway, I'm unsure how to proceed...

**Comment by slouken** [comment]
We'll need a call stack to see what's going on here.

**Comment by ronaaron** [comment]
![image](https://github.com/user-attachments/assets/94559784-e225-4071-9549-7f9a2d357bec)

**Comment by ronaaron** [comment]
![image](https://github.com/user-attachments/assets/6a18f619-9e96-455b-b12b-7f3b4818e9e4)

**Comment by ronaaron** [comment]
Somewhere it looks like the 'committedText' gets messed up. I don't see where, though.

**Comment by slouken** [comment]
Can you try the latest code? We just made a change to reset the committed text when text input is stopped.

**Comment by ronaaron** [comment]
I can't really drop-in SDL3 right now, but I'll take a look at the diff from 2.30.8 and see if the fix fixes it for me.

**Comment by ronaaron** [comment]
The changes from 2.30.8 to most recent trunk in uikitcontroller for committedText don't make any difference I can see. I copied the few changes over, no difference.

**Comment by slouken** [comment]
Okay, can you reproduce this with any of the SDL test programs? checkkeys is a good one to try out.

**Comment by slime73** [comment]
>  I'm compiling SDL2 manually, but I use the configure script except I also add the UIKIT defines so it'll work on iOS.

Are you still able to reproduce it if you use the `xcodebuild` command-line tool with the xcode project (or build via Xcode's UI) instead of manually adding iOS support to the other build system?

**Comment by ronaaron** [comment]
Well hell. When I use XCode to build it, the library works. So I guess this should be closed...
