### ISSUE TITLE
No function to check a threads status

### ISSUE THREAD

**Issue by Mori-TM** [libsdl-org/SDL#11702]
It would be really helpful if there was a function to check if a thread is still running or has already finished.
Something like this could be implemented:

```
typedef enum SDL_ThreadState
{
    SDL_THREAD_STATE_ALIVE,
    SDL_THREAD_STATE_DETACHED,
    SDL_THREAD_STATE_ZOMBIE,
    SDL_THREAD_STATE_CLEANED,
} SDL_ThreadState;


SDL_ThreadState SDL_GetThreadStatus(SDL_Thread *thread)
{
    return (SDL_ThreadState)SDL_GetAtomicInt(&thread->state);
}
```

**Comment by slouken** [comment]
I agree, I was looking for something like that the other day. I'll put this on the 3.x milestone, but feel free to contribute a PR if you'd like it for the 3.2 release.
