### ISSUE TITLE
Hint `"SDL_BORDERLESS_RESIZABLE_STYLE"` breaks maximized window

### ISSUE THREAD

**Issue by GoaLitiuM** [libsdl-org/SDL#11716]
Maximizing a window when ``"SDL_BORDERLESS_RESIZABLE_STYLE"`` hint is set to 1 doesn't resize the window properly to whole screen area, the window seems to be resized almost fully to the active screen but taskbar is still blocking the window. I don't believe this hint should affect maximizing the window at all.

**Comment by slouken** [comment]
This hint is unsupported and has varying behavior on different Windows versions.
