### ISSUE TITLE
SDL_GetWindowFullscreenMode(window) always returns NULL

### ISSUE THREAD

**Issue by Photosounder** [libsdl-org/SDL#11718]
On SDL3 (commit from yesterday) `SDL_GetWindowFullscreenMode(window)` always returns `NULL` (even when called late in the program, even when fullscreen has been manually toggled on or off) whereas something like `SDL_GetCurrentDisplayMode(1)` returns something correct.

I'm on Windows 10, I'm not sure what other information would be needed, my window is initialised with [this code](https://github.com/Photosounder/rouziclib/blob/master/rouziclib/libraries/sdl.c#L665) using the flags `SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE`.

**Comment by slouken** [comment]
Did you call SDL_SetFullscreenMode()? If you don’t, SDL will use desktop full screen instead.

**Comment by Photosounder** [comment]
No I defaulted to the borderless mode. So what function should I use to obtain the mode of the screen my window is attached to when not in exclusive fullscreen mode?

**Comment by slouken** [comment]
SDL_GetDisplayForWindow() will get you the display the window is on, and you can use any of the display functions, like SDL_GetDesktopDisplayMode() to get the desktop resolution.
