### ISSUE TITLE
Keep app open when closing the last window if the app has a system tray icon?

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#11722]
By default, SDL will emit `SDL_EVENT_QUIT` when closing the last open window.

The most common purpose for a system tray icon is to allow an app to stay active and interactive without having a window open (Steam, various messaging apps, mail clients, etc).

SDL Applications that create a system tray would unexpectedly close and remove their system tray icon whenever the last window is closed; developers would have to add code to manually ignore an `SDL_EVENT_QUIT` that is associated with the closing of a window.

Would it be relevant to change the behavior of SDL to emit `SDL_EVENT_QUIT` when closing the last window only if there is no currently active system tray icon? (Possibly re-emitting the quit event if the last tray icon is destroyed and there are no active windows)

Most SDL applications won't use the system tray and would therefore remain unaffected. Only the apps that use the system tray and keep their system tray active after having all windows closed would observe the change in behavior, which I think would be preferable.

**Comment by slouken** [comment]
Yes, that’s a good idea!
