### ISSUE TITLE
SplitFish Game Controller overrides mapping for PS3 Controller

### ISSUE THREAD

**Issue by StephenCWills** [libsdl-org/SDL#11723]
I was testing DevilutionX earlier today, and I noticed my DualShock 3 controller is no longer working. By my recollection it had been working before so I did a bit of investigating and found that it's due to the SplitFish Game Controller mapping added by #10236. This SplitFish mapping has the same GUID as the PS3 Controller mapping on line 228 of the game controller database.

https://github.com/libsdl-org/SDL/blob/b8036bdd41dfc48c614a1a023804306687fcc4c8/src/joystick/SDL_gamepad_db.h#L228

https://github.com/libsdl-org/SDL/blob/b8036bdd41dfc48c614a1a023804306687fcc4c8/src/joystick/SDL_gamepad_db.h#L306

Because of the GUID conflict, the SplitFish mapping ends up overwriting the data in the `ControllerMapping_t` struct that was allocated for the PS3 Controller mapping in the `s_pSupportedControllers` list. The SplitFish mapping's CRC makes it fail to match my joystick, which is just as well since the two mappings are in fact different, but it explains why the controller stopped working entirely.

DevilutionX is currently using SDL 2.30.9.

**Comment by slouken** [comment]
What driver are you using to get your PS3 controller working on Windows?

**Comment by slouken** [comment]
Also, the intent is for the CRC to be included in the GUID, to resolve situations like this:
```c
        // Make sure the GUID has the CRC, for matching purposes
        char *crc_string = SDL_strstr(pchMapping, SDL_GAMEPAD_CRC_FIELD);
        if (crc_string) {
            crc = (Uint16)SDL_strtol(crc_string + SDL_GAMEPAD_CRC_FIELD_SIZE, NULL, 16);
            if (crc) {
                SDL_SetJoystickGUIDCRC(&jGUID, crc);
            }
        }
```
Can you debug and see why that's not working?

**Comment by StephenCWills** [comment]
Sure, I debugged it earlier. I can share some more details.

The issue happens earlier, in the following loop which copies data from the game controller db into the `s_pSupportedControllers` linked list.

https://github.com/libsdl-org/SDL/blob/c98c4fbff6d8f3016a3ce6685bf8f43433c3efcc/src/joystick/SDL_gamecontroller.c#L1897-L1903

The `SDL_PrivateGameControllerAddMapping()` function invokes `SDL_PrivateAddMappingForGUID()` with `SDL_CONTROLLER_MAPPING_PRIORITY_DEFAULT`, so all the game controller db mappings have the same priority.

https://github.com/libsdl-org/SDL/blob/c98c4fbff6d8f3016a3ce6685bf8f43433c3efcc/src/joystick/SDL_gamecontroller.c#L1373-L1375

Since the two mappings have the same priority, the SplitFish mapping just completely overwrites the PS3 Controller mapping.

https://github.com/libsdl-org/SDL/blob/c98c4fbff6d8f3016a3ce6685bf8f43433c3efcc/src/joystick/SDL_gamecontroller.c#L1305-L1308

SDL will only check the CRC when attempting to match an actual joystick GUID against the `s_pSupportedControllers` linked list. But by then, the PS3 Controller mapping no longer exists in that list.

**Comment by slouken** [comment]
Ah, I see the problem. Because it's added after the PS3 entry, and because the PS3 entry doesn't have a CRC, it's considered a match. Hmmmmm...

**Comment by slouken** [comment]
Can you try this patch on SDL3?
```diff
diff --git a/src/joystick/SDL_gamepad.c b/src/joystick/SDL_gamepad.c
index 7d75a5a92..8c7e58cda 100644
--- a/src/joystick/SDL_gamepad.c
+++ b/src/joystick/SDL_gamepad.c
@@ -928,6 +928,16 @@ static GamepadMapping_t *SDL_PrivateGetGamepadMappingForGUID(SDL_GUID guid, bool
 
     mapping = SDL_PrivateMatchGamepadMappingForGUID(guid, true);
     if (mapping) {
+        if (adding_mapping) {
+            Uint16 crc = 0;
+            SDL_GetJoystickGUIDInfo(guid, NULL, NULL, NULL, &crc);
+
+            // Don't overwrite an existing mapping that may not have a CRC
+            const char *crc_string = SDL_strstr(mapping->mapping, SDL_GAMEPAD_CRC_FIELD);
+            if (crc && !crc_string) {
+                return NULL;
+            }
+        }
         return mapping;
     }
 
```

**Comment by slouken** [comment]
Here's the equivalent patch for SDL2:
```diff
diff --git a/src/joystick/SDL_gamecontroller.c b/src/joystick/SDL_gamecontroller.c
index d3a4668a6..ed1327dd6 100644
--- a/src/joystick/SDL_gamecontroller.c
+++ b/src/joystick/SDL_gamecontroller.c
@@ -748,6 +748,18 @@ static ControllerMapping_t *SDL_PrivateGetControllerMappingForGUID(SDL_JoystickG
 
     mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_TRUE);
     if (mapping) {
+        if (adding_mapping) {
+            Uint16 crc = 0;
+            SDL_GetJoystickGUIDInfo(guid, NULL, NULL, NULL, &crc);
+
+            /* Don't overwrite an existing mapping that may not have a CRC */
+            if (crc) {
+                const char *crc_string = SDL_strstr(mapping->mapping, SDL_CONTROLLER_CRC_FIELD);
+                if (!crc_string) {
+                    return NULL;
+                }
+            }
+        }
         return mapping;
     }
 ```

**Comment by slouken** [comment]
Here's an alternate approach that might be better:
```diff
diff --git a/src/joystick/SDL_gamecontroller.c b/src/joystick/SDL_gamecontroller.c
index d3a4668a6..72529862a 100644
--- a/src/joystick/SDL_gamecontroller.c
+++ b/src/joystick/SDL_gamecontroller.c
@@ -688,7 +688,7 @@ static ControllerMapping_t *SDL_CreateMappingForWGIController(SDL_JoystickGUID g
 /*
  * Helper function to scan the mappings database for a controller with the specified GUID
  */
-static ControllerMapping_t *SDL_PrivateMatchControllerMappingForGUID(SDL_JoystickGUID guid, SDL_bool match_version)
+static ControllerMapping_t *SDL_PrivateMatchControllerMappingForGUID(SDL_JoystickGUID guid, SDL_bool match_version, SDL_bool exact_match_crc)
 {
     ControllerMapping_t *mapping, *best_match = NULL;
     Uint16 crc = 0;
@@ -728,9 +728,10 @@ static ControllerMapping_t *SDL_PrivateMatchControllerMappingForGUID(SDL_Joystic
 
                 /* An exact match, including CRC */
                 return mapping;
+            } else if (crc && exact_match_crc) {
+                return NULL;
             }
 
-
             if (!best_match) {
                 best_match = mapping;
             }
@@ -746,7 +747,7 @@ static ControllerMapping_t *SDL_PrivateGetControllerMappingForGUID(SDL_JoystickG
 {
     ControllerMapping_t *mapping;
 
-    mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_TRUE);
+    mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_TRUE, adding_mapping);
     if (mapping) {
         return mapping;
     }
@@ -760,7 +761,7 @@ static ControllerMapping_t *SDL_PrivateGetControllerMappingForGUID(SDL_JoystickG
 
     if (SDL_JoystickGUIDUsesVersion(guid)) {
         /* Try again, ignoring the version */
-        mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_FALSE);
+        mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_FALSE, SDL_FALSE);
         if (mapping) {
             return mapping;
         }
```

**Comment by StephenCWills** [comment]
Both of these patches worked for me just now, applied to SDL2. Currently, I don't have a good way of testing SDL3 using DevilutionX.

**Comment by slouken** [comment]
Great, thanks for the feedback!

**Comment by slouken** [comment]
The second approach has been applied to SDL3, SDL2, and cherry-picked for the next release.

Thanks!
