### ISSUE TITLE
Popup window initial position is ignored

### ISSUE THREAD

**Issue by GoaLitiuM** [libsdl-org/SDL#11735]
Seems to be a recent regression (from eda0261c4e2fc845fadff397da1b04a2c5d2cd7f ?), but setting the initial position for popup-style windows seems to be ignored and the window is placed at the top-left corner of the parent window instead (at least on Windows, not sure about other platforms).

**Comment by Kontrabant** [comment]
It was indeed a regression and is fixed now. Sorry about that.
