### ISSUE TITLE
`clang-cl` reports minor warnings for SDL_gameinputjoystick.c

### ISSUE THREAD

**Issue by t-mat** [libsdl-org/SDL#11733]
As of SDL3-3.1.6 for Windows, when we specify `clang-cl` as a C compiler, it reports the following warnnings:

```
SDL3\src\joystick\gdk\SDL_gameinputjoystick.c(264,81): warning : format specifies type 'unsigned int' but the argument has type 'HRESULT' (aka 'long') [-Wformat] [SDL3\build-win32-x64-msvc2022\SDL3-shared.vcxproj]
SDL3\src\joystick\gdk\SDL_gameinputjoystick.c(277,96): warning : format specifies type 'unsigned int' but the argument has type 'HRESULT' (aka 'long') [-Wformat] [SDL3\build-win32-x64-msvc2022\SDL3-shared.vcxproj]
```

NOTE: `cl.exe` doesn't report them, though.

These lines are:

```C
return SDL_SetError("GameInputCreate failure with HRESULT of %08X", hR);
```

Since SDL3 doesn't have a global symbol for `HRESULT_FMT`, we may need to add `HRESULT_FMT` at the beginning of the `SDL_gameinputjoystick.c`

```C
// SDL_gameinputjoystick.c
...
#ifdef _WIN32
#define HRESULT_FMT "(0x%08lX)"
#else
#define HRESULT_FMT "(0x%08X)"
#endif
...
```

And change these explicit `%08X` to `HRESULT_FMT` to resolve the warnings.

```C
- return SDL_SetError("GameInputCreate failure with HRESULT of %08X", hR);
+ return SDL_SetError("GameInputCreate failure with HRESULT of" HRESULT_FMT, hR);
```

If above is a ideal solution for you, I'll write a trivial PR for them.
But I also think you may have a better plan to resolve these `HRESULT_FMT` issues.

**Comment by sezero** [comment]
Unless I'm missing something, this was already fixed by commit https://github.com/libsdl-org/SDL/commit/0f9e551d7127e9d244b25bf8ceef63422f77cfc2

Thanks for the report. Closing.

**Comment by t-mat** [comment]
oops.  I must check the HEAD of the repo.  Thanks!
