### ISSUE TITLE
Parented window initial position is ignored

### ISSUE THREAD

**Issue by GoaLitiuM** [libsdl-org/SDL#11738]
Looks like similar issue as with #11735, this time for normal windows which have a parent. The window is positioned on top-left corner of the current screen instead of at the specified position. Observed the issue on Windows.

**Comment by Kontrabant** [comment]
Fixed!

**Comment by slouken** [comment]
Are any of these fixes relevant for other platforms?

**Comment by Kontrabant** [comment]
No, I double checked, and they were windows specific bugs.
