### ISSUE TITLE
SDL_WaitAndAcquireGPUSwapchainTexture is terribly slow

### ISSUE THREAD

**Issue by Aandreba** [libsdl-org/SDL#11731]
I've been playing arround with the new SDL3 GPU API, but the terrible performance of `SDL_WaitAndAcquireGPUSwapchainTexture` is not allowing me to do anything. On my M1 Mac, the program is waiting shy of half a second every time I call `SDL_WaitAndAcquireGPUSwapchainTexture`.

Debug mode is disabled, so I don't know what could possibly be causing these slowdowns. I tested it on Linux and the same problem shows up there, though not as severe.

**Comment by thatcosmonaut** [comment]
Could we see some code?

**Comment by Aandreba** [comment]
If you want to see any other part of the code just tell me, I honestly don't know where the issue would be.

```c
SDL_GPUColorTargetInfo color_target_info;
SDL_zero(color_target_info);

if (!SDL_WaitAndAcquireGPUSwapchainTexture(cmdbuf, ctx.renderer.window, &color_target_info.texture, &w, &h)) {
    SDL_CancelGPUCommandBuffer(cmdbuf);
    return;
}
```

**Comment by thatcosmonaut** [comment]
As the name indicates, this function blocks until a swapchain texture is available. The two possibilities here are that the GPU is completely maxed out and falling behind the CPU or that you're doing something nonstandard with frame timing.

**Comment by Aandreba** [comment]
How would I do standard frame timing? Also having to wait half a second per frame looks more like a bug of some sorts than an issue of the GPU not being able to catch up to the COU, given that I don't think I'm doing much heavy GOU work

**Comment by thatcosmonaut** [comment]
I am not psychic so I do not know how you are using the API unless you share code. I would recommend looking at the examples and comparing your usage to those: https://github.com/TheSpydog/SDL_gpu_examples

**Comment by Aandreba** [comment]
On the GPU, I'm only runing very simple vertex and fragment shaders:
```hlsl
cbuffer UniformBlock : register(b0, space1) {
    float4x4 transform : packoffset(c0);
};

struct Input {
  float3 position : TEXCOORD0;
  float3 normal : TEXCOORD1;
  float2 texcoord : TEXCOORD2;
};

struct Output {
  float2 texcoord : TEXCOORD0;
  float4 position : SV_Position;
};

Output main(Input input) {
  Output output;
  output.texcoord = input.texcoord;
  output.position = mul(transform, float4(input.position, 1.));
  return output;
}
```

```hlsl
Texture2D<float4> Texture : register(t0, space2);
SamplerState Sampler : register(s0, space2); 

struct Input {
  float2 texcoord : TEXCOORD0;
};

struct Output {
  float4 color : SV_Target;
};

Output main(Input input) {
  Output output;
  output.color = Texture.Sample(Sampler, input.texcoord);
  return output;
}
```

And on my CPP code boils down to this render loop.

```cpp
...
while (true) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        switch (event.type) {
            case SDL_EVENT_QUIT:
                return 0;
        }
    }

    uint32_t w, h;
    SDL_GPUColorTargetInfo color_target_info;
    SDL_zero(color_target_info);

    SDL_GPUCommandBuffer* cmdbuf = SDL_AcquireGPUCommandBuffer(ctx.renderer.device);
   // Most of the time is spent here 
    if (!SDL_WaitAndAcquireGPUSwapchainTexture(cmdbuf, ctx.renderer.window, &color_target_info.texture, &w, &h)) {
        SDL_CancelGPUCommandBuffer(cmdbuf);
        return;
    }

    color_target_info.clear_color = (SDL_FColor){0.f, 0.f, 0.f, 1.f};
    color_target_info.load_op = SDL_GPU_LOADOP_CLEAR;
    color_target_info.store_op = SDL_GPU_STOREOP_STORE;

    SDL_GPUDepthStencilTargetInfo depth_stencil;
    SDL_zero(depth_stencil);
    depth_stencil.texture = ctx.renderer.GetDepthBuffer(w, h);
    if (!depth_stencil.texture) return;
    depth_stencil.clear_depth = 1.f;
    depth_stencil.load_op = SDL_GPU_LOADOP_CLEAR;
    depth_stencil.store_op = SDL_GPU_STOREOP_DONT_CARE;
    depth_stencil.stencil_load_op = SDL_GPU_LOADOP_DONT_CARE;
    depth_stencil.stencil_store_op = SDL_GPU_STOREOP_DONT_CARE;
    depth_stencil.cycle = true;

    SDL_GPURenderPass* pass = SDL_BeginGPURenderPass(cmdbuf, &color_target_info, 1, &depth_stencil);
    for (unsigned int i = 0; i < 10; ++i) {
        for (unsigned int j = 0; j < 10; ++j) {
            const Biome& biome = map.tiles[i * map.w + j].biome;
            Transform3D transf({(float)j, 0.f, (float)i});
            SDL_BindGPUGraphicsPipeline(pass, pipeline);

            float16 transf_mat = frame.projection * static_cast<float4x4>(transf);
            SDL_PushGPUVertexUniformData(cmdbuf, 0, transf_mat.Data(), sizeof(transf_mat));

            SDL_GPUTextureSamplerBinding texture_binding = {biome.texture, this->sampler};
            for (const Mesh& mesh : frame.ctx->assets.Get(biome.object)) {
                mesh.Bind(frame);
                SDL_BindGPUFragmentSamplers(pass, 0, &texture_binding, 1);
                SDL_DrawGPUIndexedPrimitives(pass, mesh.index_count, mesh.vertex_count, 0, 0, 0);
            }
        }
    }

    SDL_EndGPURenderPass(pass);
    SDL_SubmitGPUCommandBuffer(cmdbuf);
}
```

In this 10x10 case example, each frame update logic takes arround 1.5 ms, whilst each SDL_WaitAndAcquireGPUSwapchainTexture takes 60 ms. The rendered meshes also don't have many vertices or triangles, so what is the problem here, or what am I doing wrong?

**Comment by MirkoCovizzi** [comment]
What present mode are you using?

**Comment by Aandreba** [comment]
SDL_GPU_PRESENTMODE_IMMEDIATE

**Comment by MirkoCovizzi** [comment]
`if (!depth_stencil.texture) return;`

Not sure if it's related, but I think that if you return here, the command buffer you acquired is never submitted.

**Comment by Aandreba** [comment]
> `if (!depth_stencil.texture) return;`
> 
> Not sure if it's related, but I think that if you return here, the command buffer you acquired is never submitted.

Yeah, I still don't know how to handle the errors in that case

**Comment by Aandreba** [comment]
If it helps, the tiles come from [this asset pack](https://kenney.nl/assets/hexagon-kit)

**Comment by MirkoCovizzi** [comment]
How many indexed draws are you doing per frame? You can check in Xcode

**Comment by thatcosmonaut** [comment]
> In this 10x10 case example, each frame update logic takes arround 1.5 ms, whilst each SDL_WaitAndAcquireGPUSwapchainTexture takes 60 ms

60ms is not even remotely close to half a second. I'm curious how you are profiling this.

Skimming your code, binding a new pipeline before every single draw call is very inefficient for the GPU. In general you should consider state changes to be expensive and try to minimize that as much as possible in your renderer design.

At any rate, this is not really an appropriate venue for discussing client-side performance issues so I will be closing this issue. Feel free to reach out on the forums or the Discord for help with this and reopen the issue f you find evidence that there is actually a problem on SDL's side.

**Comment by Aandreba** [comment]
> 60ms is not even remotely close to half a second. I'm curious how you are profiling this.

It was half a second when the map was 25x25

**Comment by Aandreba** [comment]
> At any rate, this is not really an appropriate venue for discussing client-side performance issues so I will be closing this issue. Feel free to reach out on the forums or the Discord for help with this and reopen the issue f you find evidence that there is actually a problem on SDL's side.

Okey, thanks for your help!!
