### ISSUE TITLE
tray tooltip and label encoding, windows implementation

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#11749]
As I noted in #10873, windows tray implementation unconditionally uses
mbstowcs_s and wcslen from MS libc: we should not do that. For wcslen()
we do have SDL_wcslen, but we don't have a mbstowcs_s replacement, and
I think it comes to tooltip and label encodings: The documentation does
not specify anything about tooltip and label parameters' encodings, but
we usually - always? - expect UTF-8 encoded strings do we not? Then, if
we document those as such in SDL_tray.h, we can use WIN_UTF8ToStringW()
instead of mbstowcs_s(), can we not?

CC: @slouken, @icculus, @Semphriss

**Comment by Semphriss** [comment]
I've also used `MultiByteToWideChar` extensively in the tray PR, not sure if this is part of the functions to avoid?

**Comment by sezero** [comment]
> I've also used `MultiByteToWideChar` extensively in the tray PR, not sure if this is part of the functions to avoid?

Possibly, although I don't know for 100%

**Comment by slouken** [comment]
You should use WIN_UTF8ToString()

**Comment by Semphriss** [comment]
@slouken Does SDL have a function to convert a string and write it directly into an output buffer, or should I use `WIN_UTF8ToString` + `wcscpy` or an equivalent?

**Comment by slouken** [comment]
> @slouken Does SDL have a function to convert a string and write it directly into an output buffer, or should I use `WIN_UTF8ToString` + `wcscpy` or an equivalent?

No, it doesn't, but this code:
```c
    int len_w = MultiByteToWideChar(CP_UTF8, 0, escaped, len + 1, NULL, 0);
    wchar_t *out = (wchar_t *)SDL_malloc(len_w * sizeof(wchar_t));

    if (!out) {
        SDL_free(escaped);
        return NULL;
    }

    MultiByteToWideChar(CP_UTF8, 0, escaped, -1, out, len_w);

    SDL_free(escaped);

    return out;
```
can be simplified to:
```c
wchar_t *out = (wchar_t *)WIN_UTF8ToString(escaped);
SDL_free(escaped);
return out;
```

**Comment by madebr** [comment]
When building SDL on MSVC with `-DSDL_LIBC=OFF`, I see these tray-related link errors:
```
SDL_tray.c.obj : error LNK2019: unresolved external symbol __imp_wcslen referenced in function SDL_SetTrayEntryLabel_REAL
SDL_tray.c.obj : error LNK2019: unresolved external symbol __imp_mbstowcs_s referenced in function SDL_CreateTray_REAL
```

**Comment by sezero** [comment]
> When building SDL on MSVC with `-DSDL_LIBC=OFF`, I see these tray-related link errors:

Yes. This ticket is about all that.

**Comment by Semphriss** [comment]
> > @slouken Does SDL have a function to convert a string and write it directly into an output buffer, or should I use `WIN_UTF8ToString` + `wcscpy` or an equivalent?
> 
> No, it doesn't, but this code:
> 
> ```c
>     int len_w = MultiByteToWideChar(CP_UTF8, 0, escaped, len + 1, NULL, 0);
>     wchar_t *out = (wchar_t *)SDL_malloc(len_w * sizeof(wchar_t));
> 
>     if (!out) {
>         SDL_free(escaped);
>         return NULL;
>     }
> 
>     MultiByteToWideChar(CP_UTF8, 0, escaped, -1, out, len_w);
> 
>     SDL_free(escaped);
> 
>     return out;
> ```
> 
> can be simplified to:
> 
> ```c
> wchar_t *out = (wchar_t *)WIN_UTF8ToString(escaped);
> SDL_free(escaped);
> return out;
> ```

I was about `mbstowcs_s`; the two places where it is used are for the tooltip, which needs to be written directly into the `nid.szTip` buffer.

**Comment by madebr** [comment]
[msdn](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mbstowcs-s-mbstowcs-s-l?view=msvc-170) says: 
> mbstowcs_s uses the current locale for any locale-dependent behavior; _mbstowcs_s_l is identical except that it uses the locale passed in instead. For more information, see [Locale](https://learn.microsoft.com/en-us/cpp/c-runtime-library/locale?view=msvc-170).

The current locale is not always UTF-8.
And `mbstowcs_s` is not available when building SDL without libc (`-DSDL_LIBC=OFF`).

If you really want to do the transformation without buffer allocation, you can use [`SDL_iconv`](https://wiki.libsdl.org/SDL3/SDL_iconv), but then you can run into length issues.

**Comment by Semphriss** [comment]
Sorry, I mean to say that I was wondering about _how to replace_ instances of `mbstowcs_s` in the current code with SDL equivalents.

**Comment by sezero** [comment]
> Sorry, I mean to say that I was wondering about _how to replace_ instances of `mbstowcs_s` in the current code with SDL equivalents.

Try something like the following: (not tested, and not guaranteed to be correct :))

```diff
diff --git a/src/tray/windows/SDL_tray.c b/src/tray/windows/SDL_tray.c
index ba1a560..2ee9b9f 100644
--- a/src/tray/windows/SDL_tray.c
+++ b/src/tray/windows/SDL_tray.c
@@ -26,7 +26,6 @@
 
 #include <windowsx.h>
 #include <shellapi.h>
-#include <stdlib.h> /* FIXME: for mbstowcs_s, wcslen */
 
 #include "../../video/windows/SDL_surface_utils.h"
 
@@ -210,7 +209,9 @@ SDL_Tray *SDL_CreateTray(SDL_Surface *icon, const char *tooltip)
     tray->nid.uFlags = NIF_ICON | NIF_MESSAGE | NIF_TIP | NIF_SHOWTIP;
     tray->nid.uCallbackMessage = WM_TRAYICON;
     tray->nid.uVersion = NOTIFYICON_VERSION_4;
-    mbstowcs_s(NULL, tray->nid.szTip, sizeof(tray->nid.szTip) / sizeof(*tray->nid.szTip), tooltip, _TRUNCATE);
+    wchar_t *tooltipw = WIN_UTF8ToStringW(tooltip);
+    SDL_wcslcpy(tray->nid.szTip, tooltipw, sizeof(tray->nid.szTip) / sizeof(*tray->nid.szTip));
+    SDL_free(tooltipw);
 
     if (icon) {
         tray->nid.hIcon = CreateIconFromSurface(icon);
@@ -260,7 +261,9 @@ void SDL_SetTrayIcon(SDL_Tray *tray, SDL_Surface *icon)
 void SDL_SetTrayTooltip(SDL_Tray *tray, const char *tooltip)
 {
     if (tooltip) {
-        mbstowcs_s(NULL, tray->nid.szTip, sizeof(tray->nid.szTip) / sizeof(*tray->nid.szTip), tooltip, _TRUNCATE);
+        wchar_t *tooltipw = WIN_UTF8ToStringW(tooltip);
+        SDL_wcslcpy(tray->nid.szTip, tooltipw, sizeof(tray->nid.szTip) / sizeof(*tray->nid.szTip));
+        SDL_free(tooltipw);
     } else {
         tray->nid.szTip[0] = '\0';
     }
@@ -464,7 +467,7 @@ void SDL_SetTrayEntryLabel(SDL_TrayEntry *entry, const char *label)
     mii.fMask = MIIM_STRING;
 
     mii.dwTypeData = label_w;
-    mii.cch = (UINT) wcslen(label_w);
+    mii.cch = (UINT) SDL_wcslen(label_w);
 
     if (!SetMenuItemInfoW(entry->parent->hMenu, (UINT) entry->id, TRUE, &mii)) {
         SDL_SetError("Couldn't update tray entry label");
```

**Comment by sezero** [comment]
> Try something like the following: (not tested, and not guaranteed to be correct :))

P.S.: I didn't bother understanding your `convert_label()`, therefore I didn't mess with it.
