### ISSUE TITLE
X11 Window tooltip and popup window initial position is ignored

### ISSUE THREAD

**Issue by GoaLitiuM** [libsdl-org/SDL#11750]
Continuation from #11738 but this time on X11/XWayland. The window position briefly appears at the correct location but is immediately reset back to 0,0 position of the parent window. The application receives `SDL_EVENT_WINDOW_MOVED` event at 0,0 position shortly after the window has been created.

**Comment by Kontrabant** [comment]
Hmm, I'm not seeing this with testpopup. Are you calling SDL_SetWindowPosition() after creation, or just using the coordinates the window was created with?

**Comment by GoaLitiuM** [comment]
I was calling `SDL_SetWindowSize` in response to `SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED` event but didn't check if the window size actually changed. So just calling `SDL_SetWindowSize` with the initial window size seems to cause the position to reset.

**Comment by Kontrabant** [comment]
Thanks, I can reproduce it now. Should be a simple fix.

**Comment by Kontrabant** [comment]
Should be fixed now.
