### ISSUE TITLE
x11 regression: SDL_SetWindowSize fails to properly resize if SDL_SetWindowMinimumSize is called afterward

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#11754]
If I create a window and set up some window state, and then later do something like this:

```c
SDL_SetWindowSize(window, 256, 256);
SDL_SetWindowMinimumSize(window, 1, 1);
```

It reverts back to the original window size on x11. It seems to be working fine on macOS and Windows. I'm not sure about Wayland. If I comment out the `SDL_SetWindowMinimumSize` call then it resizes properly on x11.

I believe this regression was introduced with https://github.com/libsdl-org/SDL/pull/11639 (fyi @Kontrabant)

I first noticed this in love's automated tests (https://github.com/love2d/love/actions/runs/12496817150/job/34871183100) - and then I set up WSL2 and did some testing and reduced it down from the other stuff love does inside its love.window.setMode call to just this LuaJIT code run inside love. I don't have a plain C repro but I hope that's enough to go from:
```Lua
ffi = require("ffi")

ffi.cdef[[
typedef struct SDL_Window SDL_Window;

bool SDL_SetWindowSize(SDL_Window *window, int w, int h);
bool SDL_SetWindowMinimumSize(SDL_Window *window, int min_w, int min_h);
]]

local window = ffi.cast("SDL_Window *", love.window.getPointer())

ffi.C.SDL_SetWindowSize(window, 256, 256)
ffi.C.SDL_SetWindowMinimumSize(window, 1, 1)
```

**Comment by Kontrabant** [comment]
Fixed. This was a problem with setting the max size with the same pattern as well.

**Comment by slime73** [comment]
Thanks for the quick fix!
