### ISSUE TITLE
Wayland popup window `SDL_EVENT_WINDOW_RESIZED` reports wrong size

### ISSUE THREAD

**Issue by GoaLitiuM** [libsdl-org/SDL#11764]
The resized event followed by resizing a popup window on Wayland with `SDL_SetWindowSize` reports the old window size instead of the new size.

**Comment by Kontrabant** [comment]
Can you give some more info on your exact sequence of operations? I'm having trouble replicating this, as the resized events I'm seeing are reporting the correct size.
