### ISSUE TITLE
Windows popup window doesn't receive resized events

### ISSUE THREAD

**Issue by GoaLitiuM** [libsdl-org/SDL#11786]
Calling `SDL_SetWindowSize` for popup windows on Windows doesn't seem to emit ``SDL_EVENT_WINDOW_RESIZED`` event anymore.

**Comment by Kontrabant** [comment]
Huh, for some reason, GetClientRect returns the old size for popup windows when called in WM_WINDOWPOSCHANGED, but returns the correct size for regular windows.

**Comment by GoaLitiuM** [comment]
The event seems to be called now, but when I try to resize the backbuffer to render to the extended area of the popup window, the image is stretched to the old size and extended area remains black.

**Comment by Kontrabant** [comment]
Can you try [this branch](https://github.com/Kontrabant/SDL/tree/win32_popup_size_event)? Adding the WS_THICKFRAME style seems to make it properly resizable with no side effects.

**Comment by GoaLitiuM** [comment]
That seems to fix it, though there is some extra padding on the window now initially, but it goes away after resizing it.

**Comment by Kontrabant** [comment]
The padding should be fixed now, if you could test again.

**Comment by GoaLitiuM** [comment]
Thanks, this version works perfectly.

I did double check our current Windows implementation, and it looks like we are catching all window size changes (including popup windows) from `WM_SIZE` messages, and SDL seems to only look for `WM_SIZING` messages.
