### ISSUE TITLE
Move tray API to 3.3?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11790]
The tray API is coming in hot and we're very close to the 3.2.0 release. Maybe we should pull it temporarily and re-add it once 3.2 is live? That would give @Semphriss time to get feedback and polish before release.

@icculus, @Semphriss, thoughts?

**Comment by Semphriss** [comment]
I'm fine with pulling the tray stuff for now and working on my branch if it avoids locking the ABI into something undesirable.

**Comment by slouken** [comment]
I don't think it's undesirable, but we're getting good feedback and I think it makes sense to get more before we lock it in.

**Comment by slouken** [comment]
On the other hand, if it's close, it would be nice not to have to bounce it out and back, that's work I'd rather not spend time doing at this point. :)

**Comment by icculus** [comment]
We only need the API to be solid for 3.2.0, since that can't change once it's locked in, and surely we're close on that...?

Surely we can know what has to change pretty quickly at this point, too.

**Comment by icculus** [comment]
Which is to say we can pull it if necessary, but I'd rather not if we can avoid it.

**Comment by slouken** [comment]
Okay, agreed. @Semphriss, go ahead and work on the tray feedback for 3.2.0. Thanks!
