### ISSUE TITLE
Non-existent CMake path prefix '/tmp/tardir/' in SDL2-devel-2.30.10-mingw.tar.gz from release page

### ISSUE THREAD

**Issue by DavidWilliams81** [libsdl-org/SDL#11795]
Hi,

The file 'SDL2-2.30.10/x86_64-w64-mingw32/lib/cmake/SDL2/sdl2-config.cmake' from 'SDL2-devel-2.30.10-mingw.tar.gz' contains the following entries (lines 21-23):

```
set(bindir "/tmp/tardir/SDL2-2.30.10/build-mingw/install-x86_64-w64-mingw32/bin")
set(libdir "/tmp/tardir/SDL2-2.30.10/build-mingw/install-x86_64-w64-mingw32/lib")
set(includedir "/tmp/tardir/SDL2-2.30.10/build-mingw/install-x86_64-w64-mingw32/include")
```
Note the '/tmp/tardir/' prefix. I assume this refers to the machine on which the package was built, and should not have made it into the release? Obviously these paths do not exist on my machine.

For context I am using this package under Ubuntu 24.04 to cross compile from Linux to Windows. I am using the following toolchain file (from [here](https://gist.github.com/peterspackman/8cf73f7f12ba270aa8192d6911972fe8#file-mingw-w64-x86_64-cmake)):

```
# Sample toolchain file for building for Windows from an Ubuntu Linux system.
#
# Typical usage:
#    *) install cross compiler: `sudo apt-get install mingw-w64`
#    *) cd build
#    *) cmake -DCMAKE_TOOLCHAIN_FILE=~/mingw-w64-x86_64.cmake ..
# This is free and unencumbered software released into the public domain.

set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

# cross compilers to use for C, C++ and Fortran
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_Fortran_COMPILER ${TOOLCHAIN_PREFIX}-gfortran)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

# target environment on the build host system
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

# modify default behavior of FIND_XXX() commands
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
Which I save as '/home/davidw/Downloads/mingw-w64-x86_64.cmake', and I have also extracted 'SDL2-devel-2.30.10-mingw.tar.gz' to '/home/davidw/Downloads'. From my project folder I then run:

`cmake -DCMAKE_TOOLCHAIN_FILE=/home/davidw/Downloads/mingw-w64-x86_64.cmake -DSDL2_DIR=/home/davidw/Downloads/SDL2-2.30.10/cmake/ ..`

Which gives:

> CMake Error at /home/davidw/Downloads/SDL2-2.30.10/x86_64-w64-mingw32/lib/cmake/SDL2/sdl2-config.cmake:13 (message):
>   File or directory
>   /tmp/tardir/SDL2-2.30.10/build-mingw/install-x86_64-w64-mingw32/bin
>   referenced by variable SDL2_BINDIR does not exist !
> Call Stack (most recent call first):
>   /home/davidw/Downloads/SDL2-2.30.10/x86_64-w64-mingw32/lib/cmake/SDL2/sdl2-config.cmake:27 (set_and_check)
>   /home/davidw/Downloads/SDL2-2.30.10/cmake/sdl2-config.cmake:19 (include)
>   CMakeLists.txt:128 (find_package)

This failure is due to the incorrect path mentioned previously. If I manually modify lines 21-23 of the provided sdl2-config.cmake as follows:

```
set(bindir "/home/davidw/Downloads/SDL2-2.30.10/x86_64-w64-mingw32/bin")
set(libdir "/home/davidw/Downloads/SDL2-2.30.10/x86_64-w64-mingw32/lib")
set(includedir "/home/davidw/Downloads/SDL2-2.30.10/x86_64-w64-mingw32/include")
```
(a change from '/tmp/tardir/' to '/home/davidw/Downloads/') then CMake and the subsequent build of my project complete successfully.

**Comment by madebr** [comment]
Yes, I/we consider the mingw support of 2.30.10 broken.
This has been fixed in the [release-2.30.x branch](https://github.com/libsdl-org/SDL/commit/fc2fd42197e3635e6d1218ba8ae131e920c05a9a) for a possible next 2.30.x release, and is also fixed in the [SDL2 branch](https://github.com/libsdl-org/SDL/commit/d890d2594aa8db224a9f7a476760af75912ef06e) for a future 2.32.x release.

**Comment by madebr** [comment]
Here are the release archives for the current SDL2 main branch, if SDL2 would be released today:
https://github.com/madebr/SDL/actions/runs/12558312279

We'd really appreciate it if you'd test them so we have more confidence it is fixed :)

**Comment by DavidWilliams81** [comment]
> Here are the release archives for the current SDL2 main branch, if SDL2 would be released today (see artifacts at the bottom): https://github.com/madebr/SDL/actions/runs/12558312279

Thanks for your help, I can confirm the issue is fixed for me in the release archives you provided :-)

**Comment by ericoporto** [comment]
Is this fixed in the 2.30.11 ? The commit that closed this isn't related here, and this issue isn't tracked to any milestone, so its hard to figure it out

**Comment by madebr** [comment]
Yes, 2.30.11 is working again.
https://github.com/libsdl-org/SDL/commit/fc2fd42197e3635e6d1218ba8ae131e920c05a9a fixed it.

**Comment by ericoporto** [comment]
Thank you @madebr !!! :)
