### ISSUE TITLE
SDL_TEXTEDITING is sent unnecessarily when window focus changes

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1186]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2013-11-02 20:37:25 +0000, Vladimir wrote:

> I try to use http://hg.libsdl.org/SDL/file/cc2289c332eb/test/testime.c
> SDL_TEXTINPUT work fine,
> SDL_TEXTEDITING only works when the focus window changing
> 
> LOG
> INFO: Using font: consola.ttf
> INFO: text editing "", selected range (0, 0)
> INFO: Keyboard: text input "1"
> INFO: text inputed: 1
> INFO: Keyboard: text input "2"
> INFO: text inputed: 12
> INFO: Keyboard: text input "3"
> INFO: text inputed: 123
> INFO: text editing "", selected range (0, 0)
> INFO: text editing "", selected range (0, 0)
> 
> Bug? or What am I doing wrong.

On 2014-02-20 12:06:16 +0000, Andreas Ertelt wrote:

> SDL_TEXTEDITING is only generated for languages using composed characters (e.g. Japanese). With it you receive the new sequence the previous one (if any) has to be replaced with.
> 
> The reason why you receive it (with an empty string) when switching focus is to cancel a possibly ongoing composition.

On 2014-05-09 00:14:34 +0000, Adam M. wrote:

> I consider this a bug. SDL_TEXTEDITING should not be sent when the user changes window focus just because there's a possibility that there was an ongoing composition. SDL should keep track of whether there actually was an ongoing composition, and only send the event in that case.

On 2014-06-25 09:13:46 +0000, Sam Lantinga wrote:

> That's certainly probably the better behavior. I don't have a good IME test setup here. Feel free to submit a tested patch.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
