### ISSUE TITLE
Allow modifying SDLAppDelegate behaviour

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1216]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [The Proposed new cocoa header file (SDL_cocoaappdelegate.h, text/plain, 2013-11-14 10:03:31 +0000, 1318 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1442)
* [Diff of SDL_cocoaevents.m (SDL_cocoaevents.m.diff, text/plain, 2013-11-14 10:04:24 +0000, 1013 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1443)

**Reported in version:** don't know
**Reported for operating system, platform:** Mac OS X (All), All

# Comments on the original bug report:

On 2013-11-14 10:03:31 +0000, Pallav Nawani wrote:

> Created attachment 1442
> The Proposed new cocoa header file
> 
> Currently, SDLAppDelegate for the Mac is defined/declared in SDL_cocoaevents.m. Because of this, it is not possible to, for example, add a category to the AppDelegate.
> 
> For example, to verify Mac App Store receipts, Apple Recommends that the application check the receipt in applicationWillFinishLaunching delegate, and exit with a code of 173 if the receipt is not found.
> 
> The attached patch moves the declaration to a header file. The header file can now be included and the delegate added via a category.

On 2013-11-14 10:04:24 +0000, Pallav Nawani wrote:

> Created attachment 1443
> Diff of SDL_cocoaevents.m

On 2020-04-26 22:30:47 +0000,  wrote:

> I recommend adding this patch; with the closing of bug 4877 (where a menu NIB can now be specified), it seems that menu items in a NIB can now interact with an SDL app by adding a category to the SDLAppDelegate (in order to define functions that can send userevents), which this patch will allow to be done.

**Comment by slouken** [comment]
@slime73, we've modified the SDL app delegate code a bunch since this was requested. Is it still relevant?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
