### ISSUE TITLE
extend 2D render api with transform stack

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1229]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[add transform stack to the renderer api v1 (tranform_v1.diff, text/plain, 2013-11-19 22:13:51 +0000, 18524 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1461)~~
* [add transform stack to the renderer api v2 (tranform_v2.diff, text/plain, 2013-11-24 20:16:01 +0000, 21120 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1474)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2013-11-19 22:13:51 +0000, Guillaume Laforie wrote:

> Created attachment 1461
> add transform stack to the renderer api v1
> 
> here is my patch for extend the renderer api with transform stack
> current transform (scale, rotate, translate)
> current renderer direct3d, opengl

On 2013-11-23 11:55:25 +0000, Philipp Wiesemann wrote:

> I have not tried the patch but here some comment for possible (although minor and maybe really important) improvements:
>  * SDL_render.h: There is no documentation what the four new functions actually do. I can guess it but maybe a small description and ranges for arguments would be useful for some users.
>  * SDL_render.h: There is a typo at the comment for SDL_RENDERER_TRANSFORM.
>  * SDL_render.c: It would be possible to use "return SDL_Error()" instead of calling SDL_Error() and then "return -1".
>  * SDL_render.*: Parameter names have inconsistent case: "offsetx"/"offsetx" (lower case) and "scaleX"/"scaleY" (camelCase).
>  * SDL_render_d3d.c: Two error messages tell "SetTransformp()" failed but (in the source) "SetTransform()" was called.

On 2013-11-24 20:16:01 +0000, Guillaume Laforie wrote:

> Created attachment 1474
> add transform stack to the renderer api v2
> 
> take account from remarks. This patch is needed to simplify a private project and i only need windows plateform, i added opengl because it's simple. I can add opengl_es in case of interrest in the fonctionnality. For software it is more difficult... i will have a look at opencv for this one...

**Comment by icculus** [comment]
Passing on this one.
