### ISSUE TITLE
New windows should not steal focus in focus-follows-mouse mode

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1230]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2013-11-20 13:04:18 +0000, Andrew Church wrote:

> In SDL 2.0.1 on Linux/X11 using focus-follows-mouse, new windows created with SDL_CreateWindow() steal input focus even if the SDL_WINDOW_INPUT_FOCUS flag is not specified, contrary to the expected behavior of not taking focus if the mouse pointer is not inside the new window.
> 
> This is a regression from SDL 1.2.15.

On 2015-02-19 05:22:18 +0000, Ryan C. Gordon wrote:

> 
> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry if you got a lot of email from this. This is to help me sort through some bugs in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4, though!

**Comment by icculus** [comment]
The first question is "is there a way to determine if this is a focus-follows-mouse window manager?"

If not, the question is "are the popular WMs generally going to give new windows focus if we don't explicitly raise them?"

If the first one is yes, then we don't raise the window on those systems. If the second one is yes, we just stop explicitly raising new windows at all.

If neither is yes, we add a hint and people use FFM WMs can set it.

**Comment by icculus** [comment]
Actually, there doesn't appear to be a place where SDL explicitly raises new windows, like I thought it did, and there's several paths in the X11 code where it _needs_ to raise it (mouse grab, etc), so I don't think we should risk changing this.

**Comment by joaotavora** [comment]
What a bummer :-(  

> and there's several paths in the X11 code where it needs to raise it (mouse grab, etc), so I don't think we should risk changing this.

of course, grabbing the mouse needs focus, and that requires raising, so I don't understand the problem with not raising everywhere else.

My use case is a continuously running-then-killing a toy SDL app for interactive development. Everytime I save in my text editor, the program re-runs, the window re-appears... and I lose focus in my text editor.

**Comment by slouken** [comment]
I'm actually not seeing anywhere we explicitly raise the window or set focus in the normal create window flow. If I set GNOME to sloppy focus (focus follows mouse except over desktop), then an SDL window gains focus when it's shown, and so does xev, but xeyes and terminal don't. What's different about the window manager handling between those two cases?

**Comment by slouken** [comment]
Ah, yes, the `<focusNew>yes</focusNew>` configuration definitely seems like it would cause the behavior you're seeing.
