### ISSUE TITLE
Improve Website

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1252]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Safari's default rendering without change encoding manually (Screen Shot 2013-11-29 at 10.57.23 AM.png, image/png, 2013-11-29 03:08:57 +0000, 11943 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1477)

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2013-11-29 03:08:57 +0000, Ma Xiaojun wrote:

> Created attachment 1477
> Safari's default rendering without change encoding manually
> 
> SDL_image website has following issues:
> 
> 1. It is encoded in Latin-1 but neither server header or HTML meta information is present to user agent, so that it at least confuses Safari (Safari defaults to UTF-8 and doesn't seem to do automatic encoding detection) and results in something like the attached image.
> 
> 2. It contains line like "". I guess it tries to do server-side include but that fails.
> 
> 3. The HTML tags used are very outdated, for example <font> is already deprecated in HTML 4. Given the fact that http://www.libsdl.org is valid HTML5 according to http://validator.w3.org , I guess it should receive some update.
> 
> 4. The Documentation links to 1.2 docs. 
> 
> 5. It looks retro, this may be a feature.
> 
> BTW1, other SDL_* websites have similar issues.
> 
> BTW2, I cannot select 2.0.0 Version in bug report, I guess it's time to add 2.0.x versions.

On 2018-08-07 21:31:08 +0000, Ryan C. Gordon wrote:

> 
> This was fixed on the main site awhile ago, but these are worth cleaning up for SDL_mixer, etc.
> 
> --ryan.

**Comment by a-hurst** [comment]
@icculus Regarding the out-of-date docs for image/mixer/ttf: with all the recent effort put into syncing the SDL2 Wiki with the docs in the SDL2 headers, would it make sense to add the documentation for those addon modules to the wiki as well? That would help ensure the docs stay in sync with the headers going forward and reduce the maintenance burden.

The current online docs for the addon modules were last updated in 2009, so there are a fair number of functions across them that are only documented in the headers themselves.

**Comment by icculus** [comment]
@a-hurst this is actually underway now! You can see that over in #3004.

**Comment by icculus** [comment]
Okay, docs are bridged between the wiki and headers for all the libraries now, and the the SDL_image, etc, pages just redirect to GitHub now, so we should have everything resolved here...? I'm closing this one now.
