### ISSUE TITLE
Get the internal SDL_Texture type

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1299]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Mac OS X 10.6, x86

# Comments on the original bug report:

On 2014-01-06 10:44:17 +0000,  wrote:

> Problem discussed here : https://forums.libsdl.org/viewtopic.php?t=9865&sid=0c905cfc712a811965568be86aa4b8a9
> and here : https://forums.libsdl.org/viewtopic.php?t=9776&postdays=0&postorder=asc&start=0
> 
> Adding a parameter to the SDL_QueryTexture() function which return an enum corresponding to the internal texture type can be useful to be sure that a specific texture code will never be broken if you change/optimize the encapsulated stuff.
> 
> In my case it will be useful because I use shaders on a render texture to apply a post-processing filter.

**Comment by slouken** [comment]
It looks like this was worked around in https://github.com/solarus-games/solarus/commit/51932e064ef9828c0a2f20383063b6719786fa28 where they assume what SDL is using internally.

@icculus, should we make any guarantees about what we're using internally? Should we expose what we use so that other people can do the same?

**Comment by icculus** [comment]
I want to say no to this. On newer OpenGLs they can query this from the texture handle directly, and in any case shaders only care about rgba data, regardless of the internal format.

**Comment by icculus** [comment]
Oh wait, they want to know if it's a GL_TEXTURE_2D vs GL_TEXTURE_RECTANGLE? Even harder pass, now that non-power-of-two textures are basically universal.

**Comment by slouken** [comment]
Except we use both in SDL and they need to know which we picked... Maybe SDL needs to be updated to only use npot textures?

**Comment by icculus** [comment]
> Maybe SDL needs to be updated to only use npot textures?

It does for the opengl backend, and if those aren't supported, it'll try to use texture_rectangle (and fallback to power-of-two textures if neither is). But there are two bugs in this code currently, at a quick glance:

- It favors NPOT textures in GL_CreateTexture, but favors texture_rectangle when setting `renderer->info.max_texture_*`
- It doesn't check if we're on OpenGL 2.0 or later (which supports NPOT textures implicitly without an extension).

I'll open bugs for those.

Once those are fixed, they don't need a new API, they can query the system to figure out which path we chose (or just always use NPOT textures on their end and assume any modern GPU and driver will support it, so SDL will always choose it in reasonable circumstances).

**Comment by icculus** [comment]
Putting this in 2.0.20 so we remember to close it.   :)

**Comment by icculus** [comment]
Okay, these changes (and the hint to force one or the other) is satisfactory, so I'm closing this.

**Comment by slouken** [comment]
For posterity, the hint is "GL_ARB_texture_non_power_of_two"
