### ISSUE TITLE
CMake build system should support using the static C runtime for non-shared builds of SDL

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1311]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Windows (All), x86_64

# Comments on the original bug report:

On 2014-01-17 08:06:27 +0000, Brad Davis wrote:

> On windows environments, in order to avoid having to deal with providing the Microsoft C runtime re-distributable, it's often desirable to be able to configure your code to use the static C runtime (use /MT and /MTd instead of /MD and /MDd).  This allows the developer to create a single executable that has no DLL dependencies.  
> 
> 
> CMake doesn't appear to support this as a simple toggle, but there is some information out there on how to trigger this by manipulating the compiler flags (see http://stackoverflow.com/questions/10113017/setting-the-msvc-runtime-in-cmake ) and a number of other projects support this, notably OpenCV, which has it's own CMAKE setting flag for this (BUILD_WITH_STATIC_CRT) and encapsulates the logic required to accomplish it in this file:  https://github.com/Itseez/opencv/blob/master/cmake/OpenCVCRTLinkage.cmake

**Comment by slouken** [comment]
If someone wants to create a PR for this, we'll be happy to evaluate it for inclusion, but closing this for now.
