### ISSUE TITLE
Round or truncate issue when resizing the window.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1341]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Mac OS X 10.6, x86_64

# Comments on the original bug report:

On 2014-02-04 15:06:31 +0000,  wrote:

> Hi. 
> 
> The "SDL-generic" viewport resizing have a round or truncate issue. It isn't critical, but I post it here because every game maker will have the problem. 
> 
> If you resize the window and let SDL adjust the viewport, there will be some round problem visible here ==> http://www.youtube.com/watch?v=QUUTCma9HNI 
> The original game size is 320x240, and the default window size is 640x480 : there is no problem. If I resize to a non-multiple size (maximize window in my case), some tiles are wrong placed/have a wrong size because of the round/truncate issue.

On 2017-08-14 14:07:01 +0000, Sam Lantinga wrote:

> Marking for API review in SDL 2.1, thanks!

**Comment by 1bsyl** [comment]
I think we can close since we moved to float viewport/cliprect with  https://github.com/libsdl-org/SDL/commit/15a30521c69845ba129f177c047cf73f09c41a6d
