### ISSUE TITLE
Build failed if include SDL CMakeLists.txt from another project

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1349]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Mac OS X 10.8, x86

# Comments on the original bug report:

On 2014-02-11 19:45:04 +0000, Ivan Vashchaev wrote:

> If setted -std=c++11 compiler flag (I think and any other C++ related flags) .m files can't compile
> 
> Fix:
> diff -r e749005cfd72 CMakeLists.txt
> --- a/CMakeLists.txt	Mon Feb 10 13:40:02 2014 -0800
> +++ b/CMakeLists.txt	Tue Feb 11 23:28:14 2014 +0400
> @@ -991,6 +991,7 @@
>    if(SDL_FILESYSTEM)
>      set(SDL_FILESYSTEM_COCOA 1)
>      file(GLOB FILESYSTEM_SOURCES ${SDL2_SOURCE_DIR}/src/filesystem/cocoa/*.m)
> +	set_source_files_properties(${FILESYSTEM_SOURCES} PROPERTIES LANGUAGE C)
>      set(SOURCE_FILES ${SOURCE_FILES} ${FILESYSTEM_SOURCES})
>      set(HAVE_SDL_FILESYSTEM TRUE)
>    endif()

On 2015-02-19 05:22:21 +0000, Ryan C. Gordon wrote:

> 
> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry if you got a lot of email from this. This is to help me sort through some bugs in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4, though!

**Comment by okuoku** [comment]
It's already done here(and other subsystems), no?

https://github.com/libsdl-org/SDL/blob/ac32c522ada13ba39b166f84cad13e0b74738388/CMakeLists.txt#L1752-L1753

**Comment by ericoporto** [comment]
I had to add some things to use the proper SDL_config when including in another project with add_subdirectory
https://github.com/adventuregamestudio/ags/blob/f103caa629581a612e4dbee1dc2fae917c791f81/CMake/FetchSDL2.cmake#L32

**Comment by icculus** [comment]
I _think_ this is fixed, but please report back if it's still a problem!
