### ISSUE TITLE
Window steals focus when switching to a different desktop

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1366]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Quick patch (tmp.patch, text/plain, 2014-02-23 06:39:32 +0000, 2389 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1575)

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2014-02-21 07:16:35 +0000, Katie Stafford wrote:

> When I run an SDL2 application in a window, if I switch to another desktop, the SDL application will request focus immediately, cause the window manager to switch back to the desktop containing the SDL application and bring it to the front.
> 
> The only way that I can actually switch to a different desktop is if: 1. The SDL application is currently the foreground window, 2: I use keyboard shortcuts (clicking on the pager does not work), and 3: there is no full-screen window on the desktop I switch to (e.g. Firefox in full-screen mode).
> 
> Here is a video which demonstrates this behavior, and also shows which events the application receives when the bug happens: https://www.youtube.com/watch?v=BfxtD-PCNz4
> 
> I am using XFCE as a window manager.

On 2014-02-23 01:22:34 +0000, Sam Lantinga wrote:

> I've never seen this behavior or heard of it before. Can you track down the sequence of X11 events and calls that are causing this?
> 
> Thanks!

On 2014-02-23 06:39:32 +0000, Katie Stafford wrote:

> Created attachment 1575
> Quick patch
> 
> I've traced the problem to SDL_x11events.c:768, in the handling for PropertyNotify:
> 
>             if (xevent.xproperty.atom == data->videodata->_NET_WM_STATE) {
>                 /* Get the new state from the window manager.
>                    Compositing window managers can alter visibility of windows
>                    without ever mapping / unmapping them, so we handle that here,
>                    because they use the NETWM protocol to notify us of changes.
>                  */
>                 Uint32 flags = X11_GetNetWMState(_this, xevent.xproperty.window);
>                 if ((flags^data->window->flags) & SDL_WINDOW_HIDDEN) {
>                     if (flags & SDL_WINDOW_HIDDEN) {
>                         X11_DispatchUnmapNotify(data);
>                     } else {
>                         X11_DispatchMapNotify(data);
>                     }
>                 }
>             }
> 
> The problem is that XFCE only sets _NET_WM_STATE_HIDDEN on windows that are minimized, not on windows that are not visible due to being on another desktop.
> 
> The comment above indicates that this code works around other window managers not sending unmap events, so it shouldn't be run if an unmap event has been received, i.e. SDL_WINDOW_HIDDEN should be the logical OR of <unmapped> or <_NET_WM_STATE_HIDDEN>.
> 
> I have attached a quick-and-dirty patch which fixes the problem for me, but I haven't tested with any other window managers.

On 2014-02-23 06:51:06 +0000, Katie Stafford wrote:

> There is another related issue that happens now that I have applied the patch: SDL_OnWindowRestored calls SDL_RaiseWindow, so any time the window is unhidden, it steals focus. If I have an SDL application in the background, and I switch to another desktop, then switch back, the SDL application will now be in the foreground.
> 
> Is there a reason SDL_RaiseWindow needs to be called from SDL_OnWindowRestored? It seems that the intention was that OnWindowRestored means that the window was minimized, and the user has just switched to it, in which case it should already be in the foreground and focused.

On 2014-03-08 16:50:01 +0000, Katie Stafford wrote:

> Forgot to mark as responded

On 2014-06-14 12:21:42 +0000, Drew Ferguson wrote:

> Should this issue be closed now?
> 
> I seem to be experiencing similar behaviour with SDL 2.0.3

**Comment by icculus** [comment]
Let's verify this is fixed for 2.0.18

**Comment by icculus** [comment]
Tried this with xfce on Ubuntu 21.10, and it works as expected (run testsprite2, click the virtual desktop control in the titlebar to chose a different desktop). Works whether we're in the foreground or background, doesn't request focus immediately.
