### ISSUE TITLE
SDL_GetRelativeMouseState() acts strange immediately after SDL_SetRelativeMouseMode() on OS X

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1392]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Simple test app demonstraing behavior (bug2437-test.c, text/plain, 2014-03-08 14:14:12 +0000, 958 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1584)
* [Simple app demonstrating workaround (bug2437-workaround.c, text/x-csrc, 2014-03-08 14:24:44 +0000, 1402 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1585)

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Mac OS X 10.8, x86_64

# Comments on the original bug report:

On 2014-03-08 00:23:00 +0000,  wrote:

> On OS X (Not Windows or Linux), the first time I call SDL_GetRelativeMouseState() after a call to SDL_SetRelativeMouseMode(SDL_TRUE) acts as if the cursor moved to the center of the window. Also, if I then call SDL_SetRelativeMouseMode(SDL_FALSE) and then SDL_SetRelativeMouseMode(SDL_TRUE) again without any intervening mouse motion events, the first mouse motion event afterwards acts as if the cursor moved from the center of the window back to where it was last visible.
> 
> Manually calculating deltas using the non-relative SDL_GetMouseState() yields the same problems.
> 
> I managed to get around it in my own application by calling SDL_GetRelativeMouseState(NULL, NULL) immediately after all calls to SDL_SetRelativeMouseMode() and again on the first mouse motion event after.

On 2014-03-08 04:51:54 +0000, Sam Lantinga wrote:

> We just recently fixed something similar to this. Can you try in the latest SDL snapshot?
> http://www.libsdl.org/tmp/SDL-2.0.zip

On 2014-03-08 13:18:22 +0000,  wrote:

> (In reply to Sam Lantinga from comment # 1)
> > We just recently fixed something similar to this. Can you try in the latest
> > SDL snapshot?
> > http://www.libsdl.org/tmp/SDL-2.0.zip
> 
> The snapshot seems to fix the second case, but not the first. Also, with the snapshot build, when the cursor is restored after SDL_SetRelativeMouseMode(SDL_FALSE), it's placed at the center of the window instead of where it was last before SDL_SetRelativeMouseMode(SDL_TRUE). If at all possible, I'd like to keep the old behavior where the cursor coordinates are retained between calls.
> 
> Let me see if I can come up with a small example program demonstrating the issue.

On 2014-03-08 14:14:12 +0000,  wrote:

> Created attachment 1584
> Simple test app demonstraing behavior
> 
> Here's a small test app. It outputs to stdout every time SDL_GetRelativeMouseState() returns a dimension whose absolute value is greater than 50. Left mouse down callsSetRelativeMouseMode(SDL_TRUE), and vice-versa for mouse up.
> 
> To demonstrate the bug:
> 
> 1. Press the mouse button somewhere far from the center of the window. Don't move the mouse or release the button. On OS X, it outputs the delta from the cursor to the center of the window. On Linux and Windows, no mouse motion is registered.
> 
> 2. Release the mouse button. On OS X, it outputs the delta from the center of the window back to where the cursor is restored (in the snapshot build, the cursor is restored to the center of the window, so nothing happens). On Linux and Windows, no mouse motion is registered.
> 
> 3. Now double-click and hold the mouse button, careful not to move the mouse. Sometimes (I'm not sure of the exact case) the next time you move the mouse while still holding the button, a larger than expected relative mouse motion is reported on OS X.
> 
> Bottom line, SDL_GetRelativeMouseState() acts inconsistently after calls to SDL_SetRelativeMouseMode() on OS X.

On 2014-03-08 14:24:44 +0000,  wrote:

> Created attachment 1585
> Simple app demonstrating workaround
> 
> And here's the same app with the workaround I developed. It calls SDL_GetRelativeMouseState(NULL, NULL) just before the cases that were producing the unexpected results. Including it makes my program operate more-consistently between platforms (OS X, Windows, and Linux)

**Comment by icculus** [comment]
We fixed this at some point; the test app is behaving correctly on macOS now (although the mouse cursor doesn't go back to where we first set relative mode, so you'll probably find it against the edge of the window when you leave relative mode, but I guess that's okay?). Relative coordinates are correct when I change it to print any motion instead of motion > 50.
