### ISSUE TITLE
testautomation failure of video_getSetWindowSize on cygwin

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1404]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2014-03-12 15:37:34 +0000, Andreas Schiffler wrote:

> SDL_SetWindowSize cannot set the maximum window size of 1920x1080, but the window is silently clipped to 1918x1078.
> 
> Repro:
> ./testautomation.exe --info all --seed 0XO6BKAAPA4AU8OA --filter video_getSetWindowSize
> 
> Built-in video drivers: windows, dummy
> Video driver: windows
> Number of displays: 1
> Display 0: ViewSonic VX2450 Series
> Bounds: 1920x1080 at 0,0
>   Current mode: 1920x1080@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
>       Red Mask   = 0x00ff0000
>       Green Mask = 0x0000ff00
>       Blue Mask  = 0x000000ff
> ...snip...
> INFO:  03/12/14 08:28:22: ----- Test Case 17.20: 'video_getSetWindowSize' started
> INFO:  03/12/14 08:28:22: Test Description: 'Checks SDL_GetWindowSize and SDL_SetWindowSize positive and negative cases'
> INFO:  03/12/14 08:28:22: Test Iteration 1: execKey 11664770304046843992
> INFO:  03/12/14 08:28:22: Assert 'SDL_GetDisplayBounds()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify return value; expected: 0, got: 0': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_CreateWindow('Title',87,22,993,757,52)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Validate that returned window struct is not NULL': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1,1)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1,91)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 91, got: 91': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 91, got: 91': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1,1079)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1,1080)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1080': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1080': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,38,1)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 38, got: 38': Passed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 38, got: 38': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,10,93)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 10, got: 10': Passed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 93, got: 93': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 10, got: 10': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 93, got: 93': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,90,1079)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 90, got: 90': Passed
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 90, got: 90': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,64,1080)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 64, got: 64': Passed
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 64, got: 64': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1919,1)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1919,12)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 12, got: 12': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 12, got: 12': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1919,1079)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1918': Failed
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1919,1080)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1919': Passed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1080': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1919, got: 1919': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1080': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1920,1)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1, got: 1': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1920,87)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 87, got: 87': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 87, got: 87': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1920,1079)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1918': Failed
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1918': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> ERROR: 03/12/14 08:28:22: Assert 'Verify returned height; expected: 1079, got: 1078': Failed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_SetWindowSize(...,1920,1080)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize()': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1920': Passed
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1080': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&h=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned width; expected: 1920, got: 1920': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL)': Pass
> INFO:  03/12/14 08:28:22: Assert 'Verify returned height; expected: 1080, got: 1080': Passed
> INFO:  03/12/14 08:28:22: Assert 'Call to SDL_GetWindowSize(&w=NULL,&h=NULL)': Pass
> ...snip...
> INFO:  03/12/14 08:28:22: Fuzzer invocations: 16
> ERROR: 03/12/14 08:28:22: Assert Summary: Total=227 Passed=205 Failed=22
> INFO:  03/12/14 08:28:22: Total Test runtime: 0.0 sec
> ERROR: 03/12/14 08:28:22: >>> Test 'video_getSetWindowSize': Failed
> ...snip...
> INFO: Unknown event 770
> INFO: SDL EVENT: Window 1 shown
> INFO: SDL EVENT: Window 1 lost keyboard focus
> INFO: Unknown event 770
> INFO: SDL EVENT: Window 2 gained keyboard focus
> INFO: SDL EVENT: Window 2 shown
> INFO: SDL EVENT: Window 2 hidden
> INFO: SDL EVENT: Window 2 changed size to 1918x1078
> INFO: SDL EVENT: Window 2 resized to 1918x1078
> INFO: SDL EVENT: Window 2 lost keyboard focus
> INFO: Unknown event 770

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
