### ISSUE TITLE
SDL_GL_CreateContext memory leak (x11)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1480]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[patch for x11opengl memory leak (x11opengl_memleak.patch, text/plain, 2014-05-11 23:24:44 +0000, 4276 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1645)~~
* [corrected patch (x11opengl_memleak.patch, text/plain, 2014-05-12 09:40:38 +0000, 4323 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1647)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2014-05-11 23:24:44 +0000, Tito Latini wrote:

> Created attachment 1645
> patch for x11opengl memory leak
> 
> No problem if
> 
>         _this->gl_config.major_version < 3 &&
>         _this->gl_config.profile_mask == 0 &&
>         _this->gl_config.flags == 0
> 
> otherwise it is necessary to explicitly free the pointer returned by
> glXChooseFBConfig [1].
> 
> Unluckily, there isn't a way to retrieve the fbconfig-pointer from a
> GLXContext. I've attached a patch with a possible solution.
> 
> [1] https://www.opengl.org/sdk/docs/man2/xhtml/glXChooseFBConfig.xml

On 2014-05-12 09:40:38 +0000, Tito Latini wrote:

> Created attachment 1647
> corrected patch

On 2014-05-12 09:42:07 +0000, Tito Latini wrote:

> sorry, the original patch contains an error (corrected).

On 2017-09-22 14:08:37 +0000,  wrote:

> This sounds similar to a memory bug in ResidualVM.
> 
> See https://github.com/residualvm/residualvm/issues/1365.

**Comment by icculus** [comment]
I suspect we fixed this at some point, but verify for 2.0.18

**Comment by 1bsyl** [comment]
Yes, this was fixed here: https://github.com/libsdl-org/SDL/commit/a1f427651d0111463bd44d08d58ae9ecc4a9321e
