### ISSUE TITLE
VS2012 solution puts SDL2.lib in a different dir than the libraries (Image, ttf, mixer) expect

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1530]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch for the SDL 2012 project (8884.patch, text/plain, 2014-06-21 11:08:44 +0000, 1510 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1697)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2014-06-21 11:08:44 +0000, Ken Paulson wrote:

> Created attachment 1697
> Patch for the SDL 2012 project
> 
> SDL was creating SDL2.lib in:
> SDL\VisualC\Win32\Debug
> but the other SDL libraries (_image, _ttf, _mixer)expect it in:
> SDL\VisualC\SDL\Win32\Debug

**Comment by madebr** [comment]
There is no `VisualC/SDL/SDL_VS2012.vcxproj` anymore.
So I think this one is okay to close.

**Comment by madebr** [comment]
And the visualc projects of the satellite libraries co-operate with the SDL one.
