### ISSUE TITLE
Xcode 5 does not include llvm-gcc-4.2, which iosbuild.sh requires

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1532]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Other, iPhone/iPod touch

# Comments on the original bug report:

On 2014-06-25 15:33:21 +0000, Trygve Vea wrote:

> This may be a duplicate of 1445, which is marked as fixed.  Creating a new bug;
> 
> Trying to run iosbuild.sh from build-scripts gives the following output:
> 
> build-scripts tv$ ./iosbuild.sh
> Building with iOS SDK v7.1 for iOS >= 3.0
> checking build system type... i386-apple-darwin13.2.0
> checking host system type... armv6-apple-darwin
> checking how to print strings... printf
> checking for armv6-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/llvm-gcc-4.2
> checking whether the C compiler works... no
> configure: error: in `/Users/tv/hg/SDL-foo/build/armv6':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
> 
> 
> After performing some research on why this is, I've learnt that llvm-gcc-4.2 is not included in Xcode 5.  iosbuild.sh currently require llvm-gcc-4.2 to be available, and thus will not work with Xcode 5.

On 2015-02-19 06:32:14 +0000, Ryan C. Gordon wrote:

> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry
> if you got a lot of email from this. This is to help me sort through some bugs
> in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4,
> though!

On 2015-04-07 04:57:57 +0000, Ryan C. Gordon wrote:

> 
> (sorry if you get a lot of copies of this email, I'm marking several bugs at once)
> 
> Marking bugs for the (mostly) final 2.0.4 TODO list. This means we're hoping to resolve this bug before 2.0.4 ships if possible. In a perfect world, the open bug count with the target-2.0.4 keyword is zero when we ship.
> 
> (Note that closing a bug report as WONTFIX, INVALID or WORKSFORME might still happen.)
> 
> --ryan.

On 2015-05-27 01:13:12 +0000, Alex Szpakowski wrote:

> iosbuild.sh does a lot of extremely outdated things. Would it make sense to scrap its contents and replace it with a small script that invokes xcodebuild, instead?

On 2015-05-28 15:35:34 +0000, Sam Lantinga wrote:

> Yup, that sounds like a good idea. I've reassigned this to you for implementation, thanks!

On 2015-05-28 19:12:24 +0000, Ryan C. Gordon wrote:

> (In reply to Sam Lantinga from comment # 4)
> > Yup, that sounds like a good idea. I've reassigned this to you for
> > implementation, thanks!
> 
> Ah, the accidental volunteer, I love it.  :)
> 
> --ryan.

**Comment by slouken** [comment]
Now that we have good Xcode project support for iOS, let's just remove this script.
