### ISSUE TITLE
[patch] Multitouch support for evdev input via mtdev

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1627]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Adds multitouch support for evdev input via mtdev (SDL2-evdev-mtdev.patch, text/plain, 2014-09-02 11:45:21 +0000, 18674 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1858)
* [add evdev touch support (multitouch.patch, text/plain, 2015-05-09 01:34:21 +0000, 7922 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2152)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2014-09-02 11:45:21 +0000, Tobias Himmer wrote:

> Created attachment 1858
> Adds multitouch support for evdev input via mtdev
> 
> The proposed patch will implement multitouch support for the evdev input module, currently used by the Raspberry PI.
> mtdev is added as an optional dependency. It will only be used for devices reported to be touchscreens. Without it, no multitouch device is supported.
> 
> A few other things that would be changed in the existing behavior:
>  * The udev module will additionally report touchscreen devices.
>  * There won't be separate events for x and y movements. They get cached and reported on the next SYN_REPORT.
>  * Non-event devices (like /dev/input/mouse0) will be ignored. Previously they have been read and erroneously interpreted as event devices.
> 
> Multitouch coordinates are currently reported in window/screen coordinates - not normalized between 0.0 and 1.0 - to match the X11 behavior. (Bug 2307)
> 
> This is tested by sending multitouch events to the kernel via uinput as I do not have an actual multitouch device.

On 2014-09-02 12:27:29 +0000, Gabriel Jacobo wrote:

> Thanks, this is great! I'll be reviewing this patch after 2.0.4 is out.

On 2014-09-02 13:42:41 +0000, Alex Szpakowski wrote:

> (In reply to Tobias Himmer from comment # 0)
> > Multitouch coordinates are currently reported in window/screen coordinates -
> > not normalized between 0.0 and 1.0 - to match the X11 behavior. (Bug 2307)
> 
> That doesn't match the Android/iOS/Mac/Windows behaviour or the SDL documentation or public header file comments, though.

On 2015-05-09 01:34:21 +0000, Michael Weber wrote:

> Created attachment 2152
> add evdev touch support
> 
> I didn't realize somebody already worked on this, but here is my version of the patch that adds support for multitouch for evdev.
> 
> This version matches the 0.0 -> 1.0 span for x and y coordinates by looking up the min/max values of the input device via ioctl.

On 2017-08-14 05:11:37 +0000, Sam Lantinga wrote:

> Is there a reason to use the mtdev support over the raw evdev support? Should we use mtdev and fall back to evdev if it's not available?

**Comment by icculus** [comment]
I'll Google mtdev during 2.0.18 and see if we should close/merge/punt.

**Comment by slouken** [comment]
This looks interesting, but we should put it in at the beginning of a patch cycle rather than the end.

**Comment by icculus** [comment]
Testing this today. The original patch looks significantly more robust than the second, so I'm going with that one.

**Comment by icculus** [comment]
Starting updating this patch to the latest in revision control, and saw we already have multitouch evdev support, since https://github.com/libsdl-org/SDL/commit/1a31bbe2c8c984b2665b1264037faf1038ca9a78 or so. Not inclined to add the dependency on mtdev at this point unless there's a compelling reason to do so.
