### ISSUE TITLE
SDL_MOUSEMOTION outside of window - inconsistency

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1643]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [patch to fix issue (sdl_mouse_movement.patch, text/plain, 2015-08-30 21:20:06 +0000, 1086 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2257)

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows (XP), x86

# Comments on the original bug report:

On 2014-09-15 07:37:02 +0000, Mervin wrote:

> Press the left mouse button with the pointer inside the window and keep the button pressed. Move the pointer outside of the window and release the button. Now the next mouse movement outside of the window triggers a single SDL_MOUSEMOTION event, which reports absolute x,y coordinates clamped to the window dimensions but not xrel,yrel.
> This event doesn't seem to be triggered directly above the window, only left right and below the window.
> 
> This SDL_MOUSEMOTION event beyond the window shouldn't appear.

On 2015-08-03 10:37:34 +0000, Amit Jain wrote:

> Hi
> Any update or fix for this defect ?

On 2015-08-11 09:32:11 +0000, Pankaj wrote:

> Hi Mervin,
> 
> Is this defect reproduced 100% in your case?
> In my case, this is being reproduced only when mouse pointer dragged fast outside the window and release the button.

On 2015-08-30 21:20:06 +0000, Emily Dobervich wrote:

> Created attachment 2257
> patch to fix issue
> 
> Attached a patch for this issue.
> 
> The call to SDL_UpdateMouseFocus on SDL_RELEASED originally struck me as
> unnecessary, but after further digging I suspect it has something to do with
> something with SUPPORT_DRAG_OUTSIDE_WINDOW. If anyone knows for sure, I'd be
> interested in hearing about it.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
