### ISSUE TITLE
GetKeyboardState not returning hardware keyboard state when using exotic keyboard layout

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1663]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2014-10-17 16:36:09 +0000, John Barbero Unenge wrote:

> Platform: Debian SID 64bit
> SDL Version: 2.1, (but I suspect it's prevalent in previous versions too)
> Keyboard layout: Svdvorak (swedish flavor of dvorak)
> 
> I'm working on a desktop application which uses SDL and I've noticed an issue with SDL_GetKeyboardState, namely that it returns the software keystate rather than the hardware keystate. The SDL_KeyboardEvent also return text that has been typed with the current keyboard layout, which is expected.
> 
> Perhaps this isn't a bug per se, but it is really annoying. I could of course fix this in my particular application, but the issue remains in other software (not written by me).
> 
> Most noticable when playing steam games that use SDL. The well established WASD wont work without rebinding ALL THE KEYS!
> 
> Current workaround: 
> * Switch to se or us layout
> * Launch game/application
> * While running, switch back to svdvorak
> 
> This gives my wanted behavior of se/us layout for hardware keys and svdvorak for text input.
> 
> As a developer I'd love to help solve this, that is if anyone else consider this a bug/in need of a fix. Any pointers regarding where to start digging are welcome!
> 
> (I haven't checked this behavior in Windows or OS X, but could do so if needed).

On 2017-08-14 04:58:46 +0000, Sam Lantinga wrote:

> SDL_GetKeyboardState() actually returns an array indexed by scancodes which are not supposed to move around with layout changes.
> 
> Ryan, can you confirm that the X11 code is doing the right thing here?

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
