### ISSUE TITLE
Code is attempting to include non-existent extutil.h

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1666]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[Build log, second failure (SDL2-2.0.3-build.log, text/plain, 2014-10-18 18:12:13 +0000, 61293 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1904)~~
* [Build log, second failure (SDL2-2.0.3-error.log, text/plain, 2014-10-18 18:15:17 +0000, 3937 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1905)
* [Build log, third failure (SDL2-2.0.3-error2.log, text/plain, 2014-10-18 18:15:53 +0000, 3810 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1906)

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Solaris, x86

# Comments on the original bug report:

On 2014-10-18 18:12:13 +0000, UX-admin wrote:

> Created attachment 1904
> Build log, second failure
> 
> Code is attempting to include "X11/extensions/extutil.h", but there is no such thing on Solaris 10. The system has the SUNWCxall, "Full + OEM" package metacluster installed, since it is a build system.
> 
> If the header reference in question is removed, compilation still results in an error.
> 
> Build log(s) with the error are attached; re-running ./configure as the build engine suggests does not resolve the problem.
> 
> This bug should be linked or related to bug 2755 in some way.

On 2014-10-18 18:15:17 +0000, UX-admin wrote:

> Created attachment 1905
> Build log, second failure
> 
> (First failure occurs in bug 2755.)

On 2014-10-18 18:15:53 +0000, UX-admin wrote:

> Created attachment 1906
> Build log, third failure

**Comment by icculus** [comment]
This probably just needs a check in the configure script. I'll look at this for 2.0.18, but whether it actually works on Solaris is beyond my resources.

**Comment by icculus** [comment]
Turns out the only reason we need extutil.h is for SDL_x11sym.h, and that only needed it because we used to have a copy of extutil.h in the source tree which had inline code that called some functions.

That header isn't part of SDL anymore, so I removed the references to it and the otherwise-unused functions in SDL_x11sym.h.
