### ISSUE TITLE
Improve WinRT Documentation + Setup

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1683]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 8, All

# Comments on the original bug report:

On 2014-11-01 15:39:19 +0000, David Ludwig wrote:

> Here are a few, miscellaneous TODOs regarding SDL/WinRT documentation and/or overall-setup:
> 
> - Document details of SDL satellite library support
> - Make NuGet (https://www.nuget.org) packages for SDL/WinRT
> - Create templates for both MSVC 2012 and MSVC 2013, and have the corresponding
>   VSIX packages either include pre-built copies of SDL, or reference binaries
>   available via MSVC's NuGet servers
>     - Write setup instructions that use MSVC 201x templates
> - Write a list of caveats found in SDL/WinRT, such as APIs that don't work due
>   to platform restrictions, or things that need further work
> 
> NOTE: some of these TODOs may be better served through separate Bugzilla cases.  Individual items may be split off, as needed.

**Comment by icculus** [comment]
This got written at some point; README-winrt.md is pretty detailed.
