### ISSUE TITLE
SDL1 does detect joystick (hdaps), SDL2 does not

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1727]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2014-12-21 20:22:57 +0000, Conrad Kostecki wrote:

> Hi!
> I've installed the hdaps module on my Thinkpad X200, so I can use it as a joystick. SDL 1.x application are working correct and do recognize the hdaps joystick. So games like neverball 1.5.x oder tuxracer are working fine.
> 
> But never games, which depend on SDL 2.x, like neverball 1.6.x are unable to use that. SDL 2.x only reports, that it didn't find any joystick. I've also tried the current git-version, which has the same problem for me. SDL 2.x compiled without udev also has this problem.
> 
> I've compiled the testjoystick and testgamecontroller utility. SDL1 finds my joystick. SDL2 does not find any joystick.
>
> LIBSDL 1.1.15
> ```
> There are 2 joysticks attached
> Joystick 0: ThinkPad HDAPS joystick emulation
>        axes: 2
>       balls: 0
>        hats: 0
>     buttons: 0
> Joystick 1: ThinkPad HDAPS accelerometer data
>        axes: 2
>       balls: 0
>        hats: 0
>     buttons: 0
> ```
>
> LIBSDL2 2.0.3
> ```
> INFO: There are 0 joysticks attached
> INFO: There are 0 game controller(s) attached (0 joystick(s))
> ```
> 
> Could you have a look?
> 
> Conrad

On 2014-12-21 20:26:06 +0000, Conrad Kostecki wrote:

> ```
> # udevadm info --query=all /dev/input/event10
> P: /devices/virtual/input/input11/event10
> N: input/event10
> E: DEVNAME=/dev/input/event10
> E: DEVPATH=/devices/virtual/input/input11/event10
> E: ID_INPUT=1
> E: MAJOR=13
> E: MINOR=74
> E: SUBSYSTEM=input
> E: USEC_INITIALIZED=36577
> ```
>
> Distro is Gentoo Linux.
> Kernel 3.18.1
> 
> ```
> [ebuild   R    ] media-libs/libsdl-1.2.15-r8  USE="X alsa joystick opengl oss sound video xinerama xv -aalib -custom-cflags -dga -fbcon -libcaca -nas -pulseaudio -static-libs -tslib" ABI_X86="32 (64) (-x32)" 3.829 KiB
> [ebuild   R    ] media-libs/libsdl2-2.0.3-r200  USE="X alsa dbus joystick mmx opengl oss sound sse sse2 threads udev video xinerama xscreensaver -3dnow (-altivec) (-custom-cflags) -fusionsound -gles -haptic -nas -pulseaudio -static-libs -tslib -wayland" ABI_X86="32 (64) (-x32)" 3.781 KiB
> ```

On 2015-02-19 06:32:16 +0000, Ryan C. Gordon wrote:

> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry
> if you got a lot of email from this. This is to help me sort through some bugs
> in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4,
> though!

On 2018-08-06 21:20:19 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting dozens of copies of this message by email.
> 
> We are closing out bugs that appear to be abandoned in some form. This can happen for lots of reasons: we couldn't reproduce it, conversation faded out, the bug was noted as fixed in a comment but we forgot to mark it resolved, the report is good but the fix is impractical, we fixed it a long time ago without realizing there was an associated report, etc.
> 
> Individually, any of these bugs might have a better resolution (such as WONTFIX or WORKSFORME or INVALID) but we've added a new resolution of ABANDONED to make this easily searchable and make it clear that it's not necessarily unreasonable to revive a given bug report.
> 
> So if this bug is still a going concern and you feel it should still be open: please feel free to reopen it! But unless you respond, we'd like to consider these bugs closed, as many of them are several years old and overwhelming our ability to prioritize recent issues.
> 
> (please note that hundred of bug reports were sorted through here, so we apologize for any human error. Just reopen the bug in that case!)
> 
> Thanks,
> --ryan.

On 2018-08-07 09:07:17 +0000, Conrad Kostecki wrote:

> This is still not implemented :(

**Comment by icculus** [comment]
Might not be worth spending time on, but let's either fix or close as WONTFIX in 2.0.18.

**Comment by slouken** [comment]
You can set the hint SDL_HINT_LINUX_JOYSTICK_CLASSIC to enable the classic /dev/input/js* joysticks as of https://github.com/libsdl-org/SDL/commit/1c78b0800759174abe1bac01ce5b9cd788a6a372
