### ISSUE TITLE
Windows: No way to tell whether SDL_KEY* events was trapped by the IMs

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1737]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows (All), x86

# Comments on the original bug report:

On 2015-01-07 14:53:54 +0000, Kengo Ide wrote:

> In the Windows backend of SDL 2.0.3, SDL is posting keyboard events which comes with VK_PROCESSKEY code to the SDL application as well as other virtual key codes. By the time applications receive them, those events was already processed by IME, typically to allow users to manipulate it, such as choosing candidates by arrow keys and submitting text by the enter key. An application that enables text input API would also have interest to these keys to implement their text editing function, so it will be a kind of weird behaviour, since key inputs that users meant to control IME will somehow also affects the underlying application.
> 
> As it seems that the SDL doesn't have any API to differentiate these key events, there is no way to implement East Asian text input correctly.
> 
> This issue also reported in the forum by a developer named ancientcc.
> According to him, SDL1 didn't send trapped key events to the application.
> https://forums.libsdl.org/viewtopic.php?p=44956&sid=04e7eb76a28229818b3c0de5f926434b

**Comment by slouken** [comment]
I believe this is fixed in https://github.com/libsdl-org/SDL/pull/5398, please reopen this if that's not the case.
