### ISSUE TITLE
Keyboard layout not detected because of custom 'xmodmap' mappings.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1755]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.2
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-02-02 14:03:57 +0000,  wrote:

> I have a slightly customized keyboard layout to make the tab key and some other weird placed keys on my laptop dead:
> 
> ````
> xmodmap -e "keycode 112 = Left"
> xmodmap -e "keycode 117 = Right"
> ````
> 
> SDL2.0.2 completely fails to detect the keyboard layout and emits the following message: "Keyboard layout unknown, please send the following to the SDL mailing list"
> 
> The keyboard is fully unusable, not a single key is properly recognized.
> 
> My current workaround is to make a private build of SDL to force the generic X11 layout in X11_InitKeyboard()

On 2016-10-07 23:40:16 +0000, Sam Lantinga wrote:

> Can you provide a patch that does that? That seems like reasonable default behavior if we can't detect the keyboard layout.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
