### ISSUE TITLE
virtual key Home reported as numpad 7

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1766]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.2
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-02-11 21:46:07 +0000, Andrew Kelley wrote:

> When I press the Home key on my keyboard, which looks like this: http://superjoe.s3.amazonaws.com/blog-files/laptop-review-bonobo-extreme/bonox-keyboard.jpg
> 
> SDL virtual key code is reported as numpad 7. It should be reported as virtual key home. Here is the xev event:
> 
> KeyPress event, serial 37, synthetic NO, window 0x4800001,
>     root 0x28b, subw 0x0, time 74498988, (109,61), root:(816,165),
>     state 0x0, keycode 79 (keysym 0xff95, KP_Home), same_screen YES,
>     XLookupString gives 0 bytes: 
>     XmbLookupString gives 0 bytes: 
>     XFilterEvent returns: False

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
