### ISSUE TITLE
after changing keyboard layouts SDL reports the wrong virtual key code when ctrl is pressed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1767]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.2
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-02-11 22:40:01 +0000, Andrew Kelley wrote:

> To reproduce:
> 
> 1. Start an SDL application in Dvorak keyboard layout.
> 2. Press ctrl+x (in dvorak) and observe that you get a key down event with virtual key SDLK_x
> 3. Switch the keyboard layout to QWERTY
> 4. Press ctrl+x (in qwerty) and observe that you get a key down event with virtual key SDLK_q when you expected to get virtual key SDLK_x

On 2015-10-14 20:36:37 +0000, Philipp Wiesemann wrote:

> Maybe this is related to bug 3050.

**Comment by earl-ducaine** [comment]
I think the the problem mentioned above is more general than described -- it's not just switching keyboard layouts _while_ SDL is running, but that the `x` part of `ctrl+x` is only available via scancode or key symbol which don't go through translation for the current OS keyboard layout. 

As an example, an emacs-like editor on simulated hardware. I'm using a DVORAK mapping in Ubuntu. 
Type some text:
1. physical keys `k`  
2. physical keys `j` 
3. physical keys `d` 
4. I see the characters `t` `h` `e` (via text input)

Using the `alt` key as a modifier
1. Press physical key `alt` and hold
2. Press the physical key `n` 
3. Grab the printable part of the chord from text input, `n` mapped to `b`
4. Read the modifier to determine the `alt` is depressed
5. I can figure out that the command `alt+b` was intended! (hack, but it works)

However: using the `ctlr` key as a modifier
1. press physical key `ctrl` and hold
2. press the physical key `n` 
3. No text input event generated, so I have to use key up and key down events and grab the sym/scancode, which isn't mapped.
4. I still know `ctrl` is the modifier, but I have no way to know that the user is using the DVORAK keyboard and `n` is mapped to `b`

This is related to issue: #3586, which is closed. But I think it wasn't realized how problematic this is for certain applications.

Also, maybe I'm missing something? or there's a work-around! In any case thanks for all the great work!

**Comment by slouken** [comment]
@earl-ducaine, I think this works the way you're hoping in SDL3.

Here is the output of pressing the physical N key in the checkkeys test program, using the DVORAK keyboard layout on Ubuntu:
```
Key pressed :  raw 0x39, scancode 17 = N, keycode 0x00000062 = B  modifiers: (none)
Key pressed :  raw 0x39, scancode 17 = N, keycode 0x00000062 = B  modifiers: LALT
Key pressed :  raw 0x39, scancode 17 = N, keycode 0x00000062 = B  modifiers: LCTRL
```
We've also written up a guide for keyboard input which might be helpful:
https://wiki.libsdl.org/SDL3/BestKeyboardPractices
