### ISSUE TITLE
SOFT RENDERER: Textured Triangles prerequisites

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1778]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[Macro file. (common_macros.h, text/plain, 2015-02-23 22:34:44 +0000, 1604 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2045)~~
* ~~[Floating-point header. (common_float.h, text/plain, 2015-02-23 22:35:17 +0000, 2913 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2046)~~
* ~~[Floating-point implementation. (common_float.xmacro, text/plain, 2015-02-23 22:35:46 +0000, 3541 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2047)~~
* ~~[Implementation instantiation file. (common_float.c, text/plain, 2015-02-23 22:36:33 +0000, 1790 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2048)~~
* ~~[Floating-point header cleanup file. (end_common_float.h, text/plain, 2015-02-23 22:40:18 +0000, 432 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2049)~~
* ~~[File archive. (RendPrereq.tar, application/x-tar, 2015-02-28 03:08:59 +0000, 14848 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2055)~~
* ~~[Tar'ed file set (RendPrereq.tar, application/x-tar, 2015-03-14 14:13:12 +0000, 14848 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2061)~~
* ~~[Common macros & float funcs (RendPrereq_4.tar, application/x-tar, 2015-03-17 02:13:16 +0000, 13824 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2066)~~
* ~~[Common macros & float funcs (RendPrereq_5.tar, application/x-tar, 2015-03-20 03:52:32 +0000, 13824 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2072)~~
* ~~[Common macros & floating point functions (RendPrereq_6.tar, application/x-tar, 2015-03-22 08:00:23 +0000, 15360 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2077)~~
* ~~[Common macros and floating-point functions (rendprereq_7.tar, application/x-tar, 2015-03-23 04:45:31 +0000, 15872 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2080)~~
* ~~[Common macros and floating-point functions (rendprereq_8.tar, application/x-tar, 2015-03-25 05:18:13 +0000, 15872 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2084)~~
* ~~[Common macros and floating-point functions (rendprereq_9.tar, application/x-tar, 2015-03-27 03:10:04 +0000, 15872 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2093)~~
* ~~[Common macros and floating-point functions (rendprereq_9.tar, application/x-tar, 2015-03-28 20:05:04 +0000, 15872 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2097)~~
* ~~[Common macros and floating-point functions (rendprereq_10.tar, application/x-tar, 2015-04-01 03:50:11 +0000, 15872 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2102)~~
* ~~[Common macros and floating-point functions (rendprereq_11.tar, application/x-tar, 2015-04-24 23:38:33 +0000, 22528 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2133)~~
* [Snapshot, in case something has changed. (rendprereq_12.tar, application/x-tar, 2015-05-27 01:47:32 +0000, 22528 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2161)

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2015-02-23 22:33:47 +0000, Jared wrote:

> A set of C preprocessor macros and floating-point mathematics routines.
> 
> The floating-point routines are styled after SGLIB: set a few preprocessor macros, include the relevant file (either .h or .xmacro), and use the files as appropriate. They need to be adapted to the SDL build system.
> 
> The routines and macros are used in a un-committed "pixel perfect" subdivision-area-based textured-triangle renderer. The renderer is intended to support [1734], and these files are in turn intended to support the renderer.

On 2015-02-23 22:34:44 +0000, Jared wrote:

> Created attachment 2045
> Macro file.

On 2015-02-23 22:35:17 +0000, Jared wrote:

> Created attachment 2046
> Floating-point header.

On 2015-02-23 22:35:46 +0000, Jared wrote:

> Created attachment 2047
> Floating-point implementation.

On 2015-02-23 22:36:33 +0000, Jared wrote:

> Created attachment 2048
> Implementation instantiation file.

On 2015-02-23 22:40:18 +0000, Jared wrote:

> Created attachment 2049
> Floating-point header cleanup file.
> 
> Used to get rid of preprocessor warnings if you invoke the header several times. Used by common_float.c

On 2015-02-28 03:08:59 +0000, Jared wrote:

> Created attachment 2055
> File archive.
> 
> Archive for more convenience.

On 2015-03-14 14:13:12 +0000, Jared wrote:

> Created attachment 2061
> Tar'ed file set
> 
> A new file archive, just in case I changed something and forgot.

On 2015-03-17 02:13:16 +0000, Jared wrote:

> Created attachment 2066
> Common macros & float funcs
> 
> Fixed a bug that resulted in functions getting the wrong name.

On 2015-03-20 03:52:32 +0000, Jared wrote:

> Created attachment 2072
> Common macros & float funcs
> 
> Fixes INT_CONSTR()

On 2015-03-22 08:00:23 +0000, Jared wrote:

> Created attachment 2077
> Common macros & floating point functions
> 
> Fixes several bugs in the implementations.

On 2015-03-22 08:04:27 +0000, Jared wrote:

> Comment on attachment 2077
> Common macros & floating point functions
> 
> Partially tested.

On 2015-03-23 04:45:31 +0000, Jared wrote:

> Created attachment 2080
> Common macros and floating-point functions
> 
> Newest source. Separate pretest program runs to completion.

On 2015-03-25 05:18:13 +0000, Jared wrote:

> Created attachment 2084
> Common macros and floating-point functions
> 
> Latest code. Pretest runs to completion.

On 2015-03-27 03:10:04 +0000, Jared wrote:

> Created attachment 2093
> Common macros and floating-point functions

On 2015-03-28 20:05:04 +0000, Jared wrote:

> Created attachment 2097
> Common macros and floating-point functions
> 
> Just-in-case upload.

On 2015-04-01 03:50:11 +0000, Jared wrote:

> Created attachment 2102
> Common macros and floating-point functions

On 2015-04-24 23:38:33 +0000, Jared wrote:

> Created attachment 2133
> Common macros and floating-point functions
> 
> I got tired of the debug messages, so now there's a simple report formatting system to provide nesting-dependent prefix-whitespace.

On 2015-05-27 01:47:32 +0000, Jared wrote:

> Created attachment 2161
> Snapshot, in case something has changed.

**Comment by icculus** [comment]
I think we're good, with Sylvain's triangle rendering work.
