### ISSUE TITLE
fullscreen broken in legacy mode

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1782]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-02-27 13:43:27 +0000, Stas Sergeev wrote:

> Hi.
> 
> fullscreen legacy mode is used under vnc, so it may
> be very good to keep it working. Currently SDL-based
> apps cannot be used under vnc.
> 
> To reproduce the problem:
>
> ```bash
> cd test
> SDL_VIDEO_X11_LEGACY_FULLSCREEN=1 ./testdraw2 --fullscreen
> ```
>
> The drawing is wrongly positioned.
> 
> ```bash
> SDL_VIDEO_X11_LEGACY_FULLSCREEN=1 ./testdraw2 --fullscreen-desktop
> ```
>
> Window is invisible.

On 2018-08-06 21:20:25 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting dozens of copies of this message by email.
> 
> We are closing out bugs that appear to be abandoned in some form. This can happen for lots of reasons: we couldn't reproduce it, conversation faded out, the bug was noted as fixed in a comment but we forgot to mark it resolved, the report is good but the fix is impractical, we fixed it a long time ago without realizing there was an associated report, etc.
> 
> Individually, any of these bugs might have a better resolution (such as WONTFIX or WORKSFORME or INVALID) but we've added a new resolution of ABANDONED to make this easily searchable and make it clear that it's not necessarily unreasonable to revive a given bug report.
> 
> So if this bug is still a going concern and you feel it should still be open: please feel free to reopen it! But unless you respond, we'd like to consider these bugs closed, as many of them are several years old and overwhelming our ability to prioritize recent issues.
> 
> (please note that hundred of bug reports were sorted through here, so we apologize for any human error. Just reopen the bug in that case!)
> 
> Thanks,
> --ryan.

On 2018-08-07 11:11:22 +0000, Stas Sergeev wrote:

> I re-checked and the bug is still there.
> Since it is easily reproducible with the
> existing SDL test program, I think it should
> better stay open.

On 2018-08-07 14:11:33 +0000, Ryan C. Gordon wrote:

> (In reply to Stas Sergeev from comment # 2)
> > I re-checked and the bug is still there.
> > Since it is easily reproducible with the
> > existing SDL test program, I think it should
> > better stay open.
> 
> The intention is to remove the legacy code from SDL. VNC should update their code to use XRandR.
> 
> --ryan.

On 2018-08-07 15:38:09 +0000, Stas Sergeev wrote:

> In this case please feel free to close this.
> Still as the code is not yet removed, and neither
> the vnc have updated, I wonder if that would be
> the right thing to do.

On 2018-08-07 18:27:00 +0000, Stas Sergeev wrote:

> (In reply to Ryan C. Gordon from comment # 3)
> > The intention is to remove the legacy code from SDL. VNC should update their
> > code to use XRandR.
> 
> Last time I looked, this had nothing to
> do with xrandr. IIRC the problem was a missing
> EWMH support under VNC.

**Comment by icculus** [comment]
Gonna recommend we print a giant warning to stderr if we are about to use XVidMode for 2.0.18, and then kick this bug to 2.0.20 for complete removal of the XVidMode code.

(Unless we have time to explore VNC or we decide we don't _care_ what VNC does, in which case let's rip it out in 2.0.18.)

**Comment by stsp** [comment]
> Gonna recommend we print a giant warning to stderr if we are about to use XVidMode

But this has nothing to do
with XVidMode.
Unfortunately the test-case I
used to demonstrate, no longer
works.
Can someone please check
if testdraw2 still works as
expected? For me it draws
nothing at all now.

**Comment by stsp** [comment]
OK, the bug is here:
```
dnl Check for SDL
SDL_VERSION=2.0.0
AM_PATH_SDL2($SDL_VERSION,
            :,
       AC_MSG_ERROR([*** SDL version $SDL_VERSION not found!])
)
```

test/configure.ac requires
version 2.0.0 but commit
commit 4b42c05ba1eaaaa9a4ef803acea8f13402271039
Author:     Ethan Lee <flibitijibibo@gmail.com>
AuthorDate: Mon Nov 8 13:52:48 2021 -0500
Commit:     Sam Lantinga <slouken@libsdl.org>
CommitDate: Mon Nov 8 14:16:54 2021 -0800

    video: Add SDL_SetWindowMouseRect.

has this:
```
diff --git a/include/SDL_test_common.h b/include/SDL_test_common.h
index 21b412cd9..65a38c894 100644
--- a/include/SDL_test_common.h
+++ b/include/SDL_test_common.h
@@ -73,6 +73,7 @@ typedef struct
     int window_minH;
     int window_maxW;
     int window_maxH;
+    SDL_Rect confine;
     int logical_w;
     int logical_h;
     float scale;
```

... which is an ABI break.
Please bump SDL_VERSION to 2.0.18 for tests.

**Comment by stsp** [comment]
OK, so testdraw2 finally works
after I stopped it from using the
host headers from earlier sdl.

So the bug is still reproducible
with:
```
SDL_VIDEO_X11_LEGACY_FULLSCREEN=1 ./testdraw2 --fullscreen-desktop
```

Obviously --fullscreen-desktop has
nothing to do with XVidMode.

**Comment by icculus** [comment]
XVidMode (and Xinerama) support are now removed. If XRandR is missing, we can still report a single display with much of the useful information available, but not all of it, and it won't be able to change resolutions.

Which is to say: there is no more "legacy" mode at all now.
