### ISSUE TITLE
SDL2 include fails with Clang (llvm) 3.6

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1790]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows (XP), x86

# Comments on the original bug report:

On 2015-03-11 08:24:40 +0000,  wrote:

> Set up clang with codelite according to instructions here:
> http://codelite.org/LiteEditor/ClangCompiler
> (copy clang.exe and clang.exe to mingw bin folder).
> 
> Compilation works fine without SDL2 header included, with it included get 19 errors and 180 warnings, all based around SDL_cpuinfo.h.
> 
> Warnings are of the form:
> 
> e:/programming/mingw/lib/gcc/mingw32/4.8.1/include\mmintrin.h:45:72: warning: unknown attribute '__artificial__' ignored [-Wunknown-attributes]
> extern __inline void __attribute__((__gnu_inline__, __always_inline__, __artificial__))
> 
> 
> Errors are of the form:
> 
> e:/programming/mingw/lib/gcc/mingw32/4.8.1/include\xmmintrin.h:113:19: error: use of undeclared identifier '__builtin_ia32_mulss'
> return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);

On 2015-03-12 03:51:36 +0000,  wrote:

> Have now tested with a local build of latest mercurial, no change.

On 2017-02-20 10:53:20 +0000, dmikos wrote:

> HI
> 
> i am use clang in visual studio 2015 and trying to compile SDL.
> 
> Some errors:
> "
> 1>C:\Dev\waytrel2\src\3rdparty\sdl\src\video\SDL_fillrect.c(103,5): error : member reference base type '__m128' (vector of 4 'float' values) is not a structure or union
> 1>      SSE_BEGIN;
> 1>      ^~~~~~~~~
> 1>  C:\Dev\waytrel2\src\3rdparty\sdl\src\video\SDL_fillrect.c(33,9):  note: expanded from macro 'SSE_BEGIN'
> "
> 
> this can be fixed by 
> "#if defined(_MSC_VER) && !defined(__clang__)" in "src\video\SDL_fillrect.c".
> 
> 
> Some warnings:
> warning : '__SSE__' macro redefined [-Wmacro-redefined]
> and warnings related to _ReadWriteBarrier.

**Comment by icculus** [comment]
I assume this is fixed in either Clang or SDL since this report was made.
