### ISSUE TITLE
--disable-assembly (#undef SDL_ASSEMBLY_ROUTINES) does not work

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1798]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2015-03-18 19:22:22 +0000,  wrote:

> Instances of asm, __asm__, and __asm appear all over the code unguarded by a preprocessor check for defined(SDL_ASSEMBLY_ROUTINES). The --disable-assembly flag is supposed to eliminate them by #undef-ing SDL_ASSEMBLY_ROUTINES.
> 
> This fails to compile in some cases. e.g., src/cpuinfo/SDL_cpuinfo.c will not compile under clang on Linux x86_64 when --disable-assembly is specified. The fix is trivial.
> 
> To fix: Insert a preprocessor check for "defined(SDL_ASSEMBLY_ROUTINES)" wherever asm, __asm__, or __asm appears. That will fix most of them. There are a few other places that will slip through, e.g., USE_ASM_STRETCH in src/video/SDL_stretch.c

**Comment by icculus** [comment]
Let's take a run at this for 2.0.18.

**Comment by icculus** [comment]
So this compiles on GCC and Clang with --disable-assembly, although I assume it still hits some asm blocks. I'm not sure how to check for this further beyond grepping around...if I were to build with -fno-asm or even just -Dasm=sdkfjskdfj on the command line, it'll fail in system headers.

I'm closing this until there's further complaint.
