### ISSUE TITLE
Sort bugs with "*don't know*" component

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1813]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2015-04-05 23:21:50 +0000, Ryan C. Gordon wrote:

> We've got a bunch of bugs marked "*don't know*"  ...at some point we should see what these all are and maybe make a few new components.
> 
> --ryan.

**Comment by icculus** [comment]
Not relevant since migrating to GitHub.
