### ISSUE TITLE
EGL ChooseConfig selects software renderer on Android

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1842]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Android (All), All

# Comments on the original bug report:

On 2015-04-25 15:14:43 +0000,  wrote:

> I set these attributes on Android:
> SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
> SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
> SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
> SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
> SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
> After that SDL selects Android Pixelflinger intead of hardware GLES renderer on some devices.
> It caused by finding config by comparing attributes, that seems to drop all hardware configs. Affected on some PowerVR GPUs.
> All other EGL config selection examples uses first config from list, but i don't know how to do that with SDL without modifications in libSDL2.
> It's better to add some flag to skip config search or add flag to avoid software rendering (or use ACCELERATED_VISUAL flag to disallow software rendering).

On 2015-04-26 13:45:10 +0000,  wrote:

> http://hg.libsdl.org/SDL/diff/ba26f042e36d/src/video/SDL_egl.c

On 2016-10-08 00:32:47 +0000, Sam Lantinga wrote:

> Can you provide a patch that gives the behavior you would expect?
> 
> Thanks!

On 2016-10-14 17:15:51 +0000,  wrote:

> This commit enables egl context select by macro, which is always disabled:
> https://github.com/mittorn/SDL-mirror/commit/9c0e1dd819cd8470dd80c9ff5085def223306a16
> The only reason when enable it. I think, if it does not work on many android devices, it may be broken on other EGL implementations. Android drivers does return invalid contexts in list, but first context is valid on all devices.
> maybe enable macro on all non-android devices?

On 2016-10-17 08:01:08 +0000, Sylvain wrote:

> Hi,
> 
> Some time ago, there was an analog situation: a bad EGL config was chosen, discarding the correct ones.
> 
> See https://bugzilla.libsdl.org/show_bug.cgi?id=2291
> 
> I ended up checking all the EGL config, and clearly some were producing a blinking red overlay.
> 
> 1) I wonder now if adding "SDL_RENDERER_PRESENTVSYNC" would have fixed the issue ? And also if it would fix your issue.
> 
> 
> 2) I suggest that instead of a pre-processor ifdef, maybe we could add a software SDL Hint to disable the bit-diff.

**Comment by 1bsyl** [comment]
@mittorn : not sure, if you're the report author ?
I how this prevent to select software egl implementation on Android.

**Comment by mittorn** [comment]
It not preventing to select software implementation, but uses default implementation which used by most opengl applications. On GLES1 there are software configs from Android Pixelflinger, which sometimes was preferred.
As i remember, bitdiff selected broken context on some Adreno devices in 2015, causing black screen

**Comment by 1bsyl** [comment]
@mittorn 
Ok, this was your previous patch. To just select the first config found.
SDL was update to promote 332 or 565 to 888, if something is found. (see FAVOR_TRUECOLOR flag).

My commit https://github.com/libsdl-org/SDL/commit/7b284dbb34a8c34f5d6f79c58c860c9f7894fd56
just:
- search first something among non slow (eg software), non non-conformant.
- if nothing is found, it searchs among all.  (still using the requests config flags)

For instance, consider a device with only:
(565, hardware) and (888, software)
- if you request a 565, it now selects (565, hardware). (and wouldn't promote to 888).
(before it would choose the 888 software).
- if  you request a 888, it selects the (888, software)

It don't think it hurts to do that!
