### ISSUE TITLE
Mouse Warp not working due to in_title_click variable

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1847]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2015-05-01 15:04:34 +0000, Anders Davallius wrote:

> We used an older version of SDL until recently when we decided to compile our own, but then we started to run in to a new bug, where some of our players of our game (Cloudbuilt) had problem with the mouse.
> 
> We have managed to track it down quite far, but are not sure how to really solve it.
> 
> We are pretty sure it's because of these changes: http://hg.libsdl.org/SDL/rev/75ad8ebb3768
> 
> When running windows normally, there is no issue, but when we change windows performance options to "Adjust for best performance" we never get the WM_NCMOUSELEAVE event, thus the "in_title_click" variable stays true all the time if it's ever set to true (by clicking on the title bar or resizing the window or similar). Which is stopping mouse warping form working, rendering relative mouse pretty much useless for those players(and this is quite severe, because these widows settings can significantly boost performance if turned down).
> 
> We are not sure why this is happening, and the errors seem to be partially due to windows not sending the event, but it also seems like SDL could do something a little differently to work around it. Maybe there is a better event to listen to instead, or something like that?
> 
> If the person that made these changes is around, maybe he might have some ideas?
> 
> Please let me know if you have any problem recreating or understanding the issue!
> 
> Thanks!

On 2015-05-01 15:09:37 +0000, Anders Davallius wrote:

> There seem to be some discussions bout this event here:
> http://forums.codeguru.com/showthread.php?393227-No-WM_NCMOUSELEAVE-under-quot-Windows-Classic-Style-quot-!
> 
> Might be useful.

On 2015-05-01 15:23:37 +0000, Anders Davallius wrote:

> I tried a little "hack", to always run the following code when I get a SDL_WINDOWEVENT_ENTER event:
> 
> 	TRACKMOUSEEVENT* tme = new TRACKMOUSEEVENT();
> 	tme->hwndTrack = handle;
> 	tme->cbSize = sizeof(TRACKMOUSEEVENT);
> 	
> 	tme->dwFlags = TME_LEAVE | TME_NONCLIENT ;
> 
> 	tme->dwHoverTime = 1000 * 3;
> 	TrackMouseEvent(tme);
> 
> And that seem to solve it, because the mouse tracking is not automatic when you are running some windows settings. Though, it might be redundant to run this code if the mouse is already being tracked, or maybe this affect something else negatively? I would love if someone more knowledgeable about SDL could look in to this a little bit more and see what would be the best things to do.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
