### ISSUE TITLE
SDL_RWeof() needed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1856]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2015-05-11 22:52:13 +0000, Nicholas wrote:

> An end-of-file for the RW file functions would be handy.  At the moment, the only way to check for end-of-file for read-only/read-write files is to see if the file pointer is greater than the file size.  However, I can see this being a problem if the file size makes the return value go negative (due to being  a signed value) or the file size being 2^64 bytes

On 2017-08-12 23:55:57 +0000, Sam Lantinga wrote:

> Agreed. Marking as assigned for SDL 2.1

**Comment by icculus** [comment]
Going to argue we _don't_ need this, since reading will tell you if you're at EOF, and since we're built on top of stdio FILE*, you need to have executed a failed read before feof() returns true anyhow.
