### ISSUE TITLE
SDL_SendEditingText and SDL_SendKeyboardText cut off IME input more than 32 bytes.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1879]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[patch to implement SendEditEX for 3006, 3421, 4782, and 4783 for windows and fcitx (not yet for ibus) (SDL_3006_3421_4782_4783_for_windows_and_fcitx.diff, text/plain, 2019-09-08 03:41:06 +0000, 28930 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3958)~~
* [patch to implement SendEditEX for bugs 3006, 3421, 4782, and 4783 on windows and fcitx (not yet for ibus) (SDL_3006_3421_4782_4783_for_windows_and_fcitx.diff, text/plain, 2019-09-10 01:06:26 +0000, 34007 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3962)

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2015-06-10 03:03:46 +0000, Hak Matsuda wrote:

> In SDL_SendEditingText and SDL_SendKeyboardText, it cut off an input string from IME more than 32 bytes via SDL_utf8strlcpy().
> The size is hard limit for Asian IMEs since it can easily generates strings more than 32 bytes.
> 
> Rather than just cutting off a remaining bytes, having an API to retrieve a rest of 
> string is an ideal.

On 2015-06-15 02:36:09 +0000, Sam Lantinga wrote:

> How big are the strings likely to be?
> One solution to this is to have the application free those strings. Another solution would be to keep some number of them cached and valid, but that could cause an application to crash or see the wrong text if the events are not handled for a long time.

On 2015-06-15 03:35:24 +0000, Hak Matsuda wrote:

> In case of Japanese, it's likely in a range of 64 bytes ~ 256 bytes in most of use cases (I would imagine it's similar in other languages that has a context based character transform mechanism).
> 
> I would prefer former option rather than to have a chance to lose them.

On 2015-06-16 04:48:20 +0000, Ryan C. Gordon wrote:

> (In reply to Sam Lantinga from comment # 1)
> > How big are the strings likely to be?
> > One solution to this is to have the application free those strings. Another
> > solution would be to keep some number of them cached and valid, but that
> > could cause an application to crash or see the wrong text if the events are
> > not handled for a long time.
> 
> I haven't looked, but could we just split them up into multiple TEXTINPUT events? That would keep the existing API/ABI intact.
> 
> --ryan.

On 2015-06-16 06:32:30 +0000, Sam Lantinga wrote:

> SendKeyboardText could, but the editing text is an in-place temporary string and each event replaces the previous text.

On 2015-06-16 18:13:36 +0000, Hak Matsuda wrote:

> If it's easier to fix, adding new definition of SDL_TEXTEDITING_EXTRA to send extra bytes (multiple times depending on the length) in addition to existing message and let the receiver to concatenate them, would work?

On 2015-09-29 18:29:51 +0000, Alex Baines wrote:

> In the iBus code, I worked around this by sending multiple input / editing events in a row if the text is more than 32 bytes.
> 
> You'd have to concatenate all the editing events that were received in a single PumpEvents / PollEvent loop to get the full replacement editing string.
> 
> Not sure that is the best approach though.

On 2016-10-08 00:53:01 +0000, Sam Lantinga wrote:

> *** Bug 2857 has been marked as a duplicate of this bug. ***

On 2016-10-08 03:41:01 +0000,  wrote:

> I think one could just add an SDL_TEXTEDITING_EX event which appends text to those sent by SDL_TEXTEDITING and updates the cursor accordingly. That way, existing applications could just ignore that and work with the old clamped text.

On 2016-10-08 08:36:02 +0000, Sam Lantinga wrote:

> We could also do the same thing that we do for drag-and-drop events, where we create a new event that's disabled by default, and the text is dynamically allocated and needs to be freed by the code processing the event.

On 2019-02-08 02:10:26 +0000,  wrote:

> Is there a consensus regarding the solution?
> 
> This latter proposal is probably the best option. If we have to add new events anyway (due to binary compatibility) and have to adjust the app code to handle them then we shouldn't make our lives more difficult by creating new events that have to cooperate with the old ones.
> 
> How to allow the opt-in? A function call (like SDL_EnableTextInput2()) that turns all SDL_TEXTEDITING and SDL_TEXTINPUT events into their v2 form (SDL_TEXTEDITING_2 and SDL_TEXTINPUT_2?) or an alternative like an SDL_StartTextInput2() function so different parts of the codebase can choose from v1 or v2 events by calling either SDL_StartTextInput() or SDL_StartTextInput2(). That way older parts of the app could still use the old SDL_StartTextInput() and work with the older events.
> 
> Having both versions of the events in the same application might add more trouble than benefit due to the centralised nature of event handling in a lot of SDL apps so having a global switch is probably a safer choice.

On 2019-09-01 19:35:57 +0000, tamo wrote:

> *** Bug 4774 has been marked as a duplicate of this bug. ***

On 2019-09-01 19:39:01 +0000, tamo wrote:

> (In reply to tamo from comment # 11)
> > *** Bug 4774 has been marked as a duplicate of this bug. ***
> 
> But 4774 has a buildable patch to malloc the text (and thus needs freeing).

On 2019-09-02 14:43:49 +0000, tamo wrote:

> If you should add another event to push extra information on editing event, please consider separating readingstring from composition (editing) text.
> 
> Currently SDL puts readingstring into composition text at cursor's position.
> http://hg.libsdl.org/SDL/file/08db6a6f6c23/src/video/windows/SDL_windowskeyboard.c#l771
> But they are different things. I don't think they should be mixed.
> 
> For example, target range, which I suggested you add to the event in bug 4783, refers to raw composition text, not the mixed text. If readingstring were a separate field, the patch for bug 4783 would have been a little simpler.
> 
> Composition is composition, reading is reading. I hope they will be provided in their whole length, as individual variables.

On 2019-09-08 03:41:06 +0000, tamo wrote:

> Created attachment 3958
> patch to implement SendEditEX for 3006, 3421, 4782, and 4783 for windows and fcitx (not yet for ibus)
> 
> (In reply to Alex Baines from comment # 6)
> > In the iBus code, I worked around this by sending multiple input / editing
> > events in a row if the text is more than 32 bytes.
> 
> As mentioned in comment # 4, the current SendEditingText implementations for ibus and fcitx are broken. They try to iterate a long editing text, but it doesn't work.
> 
> I wrote an editx for fcitx.
> 
> Although this patch includes some lines for ibus, they must be broken, bogus, because I haven't successfully set up ibus on my WSL ubuntu and I haven't tested them at all.

On 2019-09-10 01:06:26 +0000, tamo wrote:

> Created attachment 3962
> patch to implement SendEditEX for bugs 3006, 3421, 4782, and 4783 on windows and fcitx (not yet for ibus)
> 
> (In reply to tamo from comment # 14)
> > I wrote an editx for fcitx.
> 
> I made it a little more readable.
> I tested it with testime. (This patch modifies it so that it underlines the target text. Also, space key is disabled because fcitx uses Ctrl+space to trigger IME. Press backspace to exit.)
> 
> The following statement is still true.
> 
> > Although this patch includes some lines for ibus, they must be broken,
> > bogus, because I haven't successfully set up ibus on my WSL ubuntu and I
> > haven't tested them at all.

**Comment by slouken** [comment]
SDL_SendKeyboardText() will now break long input into chunks for delivery. SDL_SendEditingText() will send an extended event with dynamic allocation in SDL2 if the application handles that, and in SDL3 it will always allocate memory for long text, as of https://github.com/libsdl-org/SDL/commit/7e445da56990ce741e356ff7ed354abea129f288.

**Comment by Susko3** [comment]
Is the new proper usage of the events documented on the wiki? I see the new event has both `text` and `short_text`, I assume consumers should ignore `short_text` and just treat `text` as a null-terminated string (I hope there's no edge case with 32 character strings (32+null)).

**Comment by slouken** [comment]
Yeah, I'll clarify it more in the documentation.

**Comment by icculus** [comment]
> SDL_SendKeyboardText() will now break long input into chunks for delivery.

Wait, I have some questions, which might be okay and I'm just ignorant of some of the finer points of Unicode here.

First, in SDL_SendKeyboardText, this is at the top of the function:

```c
    /* Don't post text events for unprintable characters */
    if ((unsigned char)*text < ' ' || *text == 127) {
        return 0;
    }
```

- Are these values actually invalid?
- Should we lose the entire string if the first character is one of these?

Later, we split this up into multiple events:

```c
        while (pos < length) {
            advance = SDL_utf8strlcpy(event.text.text, text + pos, SDL_arraysize(event.text.text));
            if (!advance) {
                break;
            }
            pos += advance;
            posted |= (SDL_PushEvent(&event) > 0);
        }
```

- What happens if this splits on a Unicode [combining or modifier character](https://stackoverflow.com/questions/54450823/what-is-the-difference-between-combining-characters-and-modifier-letters)? What if, say, someone wants to do a [hand wave emoji with a specific color](https://unicode.org/emoji/charts/full-emoji-modifiers.html), but it splits into two events between these two values? Should the app buffer these things between events?

**Comment by Susko3** [comment]
If the app wants correctness (one user action = one text event/text commit), it should definitely buffer the events. To reduce latency, I think it makes sense to buffer when calling `SDL_PeepEvents()`. You can probably expect all text events generated from a single user action to arrive in the same peep (untested).

The pseudocode below illustrates my approach:

```c++
string buffer = "";

do {
    SDL_PeepEvents(events, ...);
    for (event : events) {
        if (event.type == SDL_TEXTINPUT)
            buffer += event.text.text;
    }
} while (there are events to peep);

if (text != "")
    HandleText(buffer);
```

**Comment by slouken** [comment]
> > SDL_SendKeyboardText() will now break long input into chunks for delivery.
> 
> Wait, I have some questions, which might be okay and I'm just ignorant of some of the finer points of Unicode here.
> 
> First, in SDL_SendKeyboardText, this is at the top of the function:
> 
> ```c
>     /* Don't post text events for unprintable characters */
>     if ((unsigned char)*text < ' ' || *text == 127) {
>         return 0;
>     }
> ```
> 
> * Are these values actually invalid?

Yes, they're non-printable characters.

> * Should we lose the entire string if the first character is one of these?

Probably, it just means a backend sent us a control character accidentally.

> Later, we split this up into multiple events:
> 
> ```c
>         while (pos < length) {
>             advance = SDL_utf8strlcpy(event.text.text, text + pos, SDL_arraysize(event.text.text));
>             if (!advance) {
>                 break;
>             }
>             pos += advance;
>             posted |= (SDL_PushEvent(&event) > 0);
>         }
> ```
> 
> * What happens if this splits on a Unicode [combining or modifier character](https://stackoverflow.com/questions/54450823/what-is-the-difference-between-combining-characters-and-modifier-letters)? What if, say, someone wants to do a [hand wave emoji with a specific color](https://unicode.org/emoji/charts/full-emoji-modifiers.html), but it splits into two events between these two values? Should the app buffer these things between events?

That's a good point. I'll change the text input event to work the same as the editing event.
