### ISSUE TITLE
grab mouse inconsistent state

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1887]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-06-15 06:45:04 +0000, Martin Gerhardy wrote:

> Not sure - but I think there might be a logic flaw in SDL_SetWindowGrab.
> 
> The problem here is that this modifies the window flags and e.g. sets 
> SDL_WINDOW_INPUT_GRABBED - but the _this->grabbed_window pointer is not 
> yet set.
> 
> Then in SDL_UpdateWindowGrab the _this->grabbed_window pointer is only 
> set if the function pointer _this->SetWindowGrab is not NULL. But if 
> this is NULL, the _this->grabbed_window pointer is never set, but every 
> future call to any of the grab functions include an assert for:  
> SDL_assert(!_this->grabbed_window || ((_this->grabbed_window->flags & 
> SDL_WINDOW_INPUT_GRABBED) != 0));
> 
> That means the first call works, the second always fails and triggers 
> the assert.

On 2015-06-16 06:44:54 +0000, Sam Lantinga wrote:

> Okay, I think this is fixed:
> https://hg.libsdl.org/SDL/rev/885b6b5c8426
> 
> I don't have an environment where I can easily test this, can you verify the fix?
> 
> Thanks!

On 2015-06-16 07:43:29 +0000, Martin Gerhardy wrote:

> Still triggered.
> 
> Assertion failure at SDL_GetGrabbedWindow_REAL (/home/mgerhardy/dev/caveexpress/src/libs/SDL/src/video/SDL_video.c:2180), triggered 1 time:
>   '!_this->grabbed_window || ((_this->grabbed_window->flags & SDL_WINDOW_INPUT_GRABBED) != 0)'

On 2015-06-16 07:44:02 +0000, Martin Gerhardy wrote:

> reopen - see my previous comment

On 2015-06-16 07:48:20 +0000, Martin Gerhardy wrote:

> looks like SDL_SetWindowGrab and SDL_UpdateWindowGrab compute different "SDL_bool grabbed" states

On 2015-06-16 14:42:30 +0000, Ryan C. Gordon wrote:

> 
> This one is my bug, taking it.
> 
> --ryan.

On 2015-07-21 04:40:35 +0000, Yash wrote:

> Hi Ryan
> 
> Any fix so far ?

On 2015-12-31 08:54:32 +0000, Ryan C. Gordon wrote:

> 
> Actually, I'm trying to find a way to trigger that assertion and can't.
> 
> Martin, is this still happening to you?
> 
> --ryan.

On 2015-12-31 10:22:28 +0000, Martin Gerhardy wrote:

> hm. I can't reproduce the assert anymore - but for my code the grabbing and ungrabbing doesn't work at all anymore. I always have the mouse grabbed (software renderer - as there might be grabbing issues... e.g. I only receive mouse move event in software render mode after I at least once alt+tabbed away)
> 
> will try a different renderer to double check.

On 2015-12-31 10:59:47 +0000, Martin Gerhardy wrote:

> Assertion failure at SDL_GetGrabbedWindow_REAL (/home/mgerhardy/dev/caveexpress/src/libs/sdl2/src/video/SDL_video.c:2283), triggered 1 time:
>   '!_this->grabbed_window || ((_this->grabbed_window->flags & SDL_WINDOW_INPUT_GRABBED) != 0)'
> 
> still happens on latest hg rev.
> 
> void SDLFrontend::toggleGrabMouse () {
> #if SDL_VERSION_ATLEAST(2, 0, 4)
> 	const bool grabMouse = SDL_GetGrabbedWindow() == _window;
> #else
> 	const bool grabMouse = Config.isGrabMouse();
> #endif
> 	if (grabMouse) {
> 		SDL_SetWindowGrab(_window, SDL_FALSE);
> 		Log::info(LOG_GFX, "Mouse grab is now deactivated");
> 		Config.setGrabMouse(false);
> 	} else {
> 		SDL_SetWindowGrab(_window, SDL_TRUE);
> 		Log::info(LOG_GFX, "Mouse grab is now activated");
> 		Config.setGrabMouse(true);
> 	}
> }
> 
> this is the code that I use to trigger it.

**Comment by icculus** [comment]
I'm assuming we fixed this in the past seven years, and if not, someone can open a new bug report.
