### ISSUE TITLE
Refactor Cmake scripts

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1889]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch enabling switching of debug Symbols (GCC only) (9758.patch, text/plain, 2015-06-19 05:48:58 +0000, 1211 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2187)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows Vista, x86

# Comments on the original bug report:

On 2015-06-15 13:38:19 +0000, DarioOO wrote:

> I asked previously improvements in the CMake script files, but I just saw the cmake build script is broken (again!) and there are already many open tickets for Cmake. 
> 
> Most big c++ projects are switching to Cmake as primary build system, It's just disappointing you not have Cmake as priority and often I see it is actually broken for SDL2 making other framworks more appealing. (I know Cmake it's not a panacea, but if used properly has great benefits)
> 
> The build system needs heavy refactoring in my opinion, I marked that as enanchment because I already filed a bug for the broken build in 2.0.4 RC1, But in general if you do not improve the CMake scripts you would end up having broken build everytime you apply small changes.
> 
> Not everyone will just spent time even reporting bugs (I also tried to fix that script but it is just too complex for the occasional user)
> 
> I hope you see that as a priority. (I can even give some help if there's someone that want to explain me certain weird stuff done at low level like: checking if "printf" is available O_O)

On 2015-06-16 06:40:11 +0000, Sam Lantinga wrote:

> Sure, can you coordinate with Ryan to see how the CMake scripts can be improved? I don't use CMake myself for various reasons, so I leave it in y'all's capable hands. :)

On 2015-06-18 23:34:04 +0000, DarioOO wrote:

> Ok I partially QUICK fixed the problem. I submitted the patch with HG (it don't asked credentials, so I hope I was already granted write access and that is not a security breach XD).
> 
> - Now debug symbols can be disabled for GCC reducing binary size from 5 MB to 1.3 MB (default is now without debug symbols)
> 
> - There's much more margin for improvement
> 
> I think that's enough for RC1, but I'm willing to do more work for improving Cmake scripts :).
> 
> Can someone confirm the patch is in the "trunk" (sorry I used mostly SVN and GIT so I don't know if I did the commit correctly with HG)

On 2015-06-19 01:28:45 +0000, Ryan C. Gordon wrote:

> (In reply to DarioOO from comment # 2)
> > Ok I partially QUICK fixed the problem. I submitted the patch with HG (it
> > don't asked credentials, so I hope I was already granted write access and
> > that is not a security breach XD).
> 
> If you "committed" the change, that means it's committed to your local copy of the repository; it doesn't work like Subversion in this case.
> 
> You would have to "push" the change to our repository, but you don't have access to do that. You can do "hg export tip" and attach the output of that to this bug report, though, and we'll review and push it!
> 
> Thanks,
> --ryan.

On 2015-06-19 05:48:58 +0000, DarioOO wrote:

> Created attachment 2187
> Patch enabling switching of debug Symbols (GCC only)
> 
> Here the patch. It does not any major change. It just add the chance to change compile settings

On 2015-06-22 15:54:50 +0000, Ryan C. Gordon wrote:

> 
> We're going to wait on this until 2.0.5; the thing we _should_ be doing is not forcing debug symbols at all (that's what the built in CMAKE_BUILD_TYPE=Debug is for). There's a couple things like that we need to fix.
> 
> --ryan.

On 2016-06-12 23:54:52 +0000, Cyberunner23 wrote:

> I would like to volunteer for the refactoring if you don't mind. Perhaps I could actually work on it right now and show it to you, test it, change it if you want and so on once I'm done.

**Comment by icculus** [comment]
I would like to see some movement (or at least a plan) by 2.0.20, even if the plan is "we applied a bunch of patches and piece by piece this got it into a good place.

**Comment by icculus** [comment]
Going to say a full rewrite of the CMake scripts might be extremely worthwhile for SDL3, but for 2.x, let's just keep patching specific issues.

**Comment by icculus** [comment]
Moving this out of 2.0.22 milestone (specific issues can be patched separately). This general "rework the whole thing" issue is moving to SDL3.
