### ISSUE TITLE
SDL_HapticRumbleInit() FAILS

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1891]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2015-06-16 03:57:11 +0000, Joe Thompson wrote:

> With Direct Input device (MOMO Steering Wheel w/FF)
> SDL_HapticRumbleInit() FAILS with error:
> Haptic error Unable to create effect

On 2015-06-16 03:58:48 +0000, Joe Thompson wrote:

> This effects 2.0.4 rc1

On 2015-06-16 05:03:51 +0000, Ryan C. Gordon wrote:

> 
> Assigning Edgar's bugs to me.
> 
> --ryan.

On 2016-05-28 15:41:54 +0000, Joe Thompson wrote:

> The MOMO Steering wheel only seems to support SDL_HAPTIC_CARTESIAN coordinates for downloaded effects. The SDL built-in Rumble effect does not set the efx->periodic.direction.type. So SDL_HAPTIC_POLAR is used.
> 
> In SDL_haptic.c (at line 767) adding 
> 
> efx->periodic.direction.type = SDL_HAPTIC_CARTESIAN;
> efx->periodic.direction.dir[0] = 0;
> 
> allows SDL_HapticRumbleInit() to succeed. 
> 
> I have no other dinput devices, so I do not know if this would break existing Rumble devices.
> 
> Joe

**Comment by icculus** [comment]
This is probably a loss at this point, for age and lack of hardware. Sorry!
