### ISSUE TITLE
SDL_GetWindowMinimumSize doesn't account for system-imposed minimums

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1895]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2015-06-19 00:43:07 +0000, Adam M. wrote:

> There appear to be minimums imposed by some part of the system (either the OS or SDL) on the size of a window. For instance, it's not possible to use SDL to create a normal window with a 100x100 drawing area on my machine. The actual drawing area becomes 116x100, and this is minimum is not reflected by SDL_GetWindowMinimumSize.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
