### ISSUE TITLE
[2.0.4 RC2] Problem when using SDL_SetRenderTarget + SDL_RenderReadPixels (Windows only)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1908]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2015-06-29 06:24:29 +0000,  wrote:

> I'm still experiencing this bug on Windows in 2.0.4 RC2.
> 
> https://bugzilla.libsdl.org/show_bug.cgi?id=2705
> 
> Using the code:
> 
> ```c
>   SDL_SetRenderTarget(m_renderer, m_targetTex);
>   int readResult = SDL_RenderReadPixels(m_renderer, NULL, SDL_PIXELFORMAT_ARGB8888, pixelData, pitch);
>   SDL_SetRenderTarget(m_renderer, NULL);
> ```
> 
> The actual pixel data is grabbed from the backbuffer, and not the render target.

**Comment by icculus** [comment]
This is probably fixed, will verify.

**Comment by icculus** [comment]
Tested this and it works in modern times.
