### ISSUE TITLE
SDL_GetModState consumes SHIFT(L/R), when SHIFT + Numpad key(0-9) is pressed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1917]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2015-07-10 09:26:32 +0000, Vikas wrote:

> 1. Enable the NUM lock key
> 2. Press the Shift(Left or right) key continuously
> 3. Simultaneously press 0-9 key from numpad 
> 4. SDL_GetModState returns 0(no modifier key pressed)
> 
> Note :
> 1. Press SHIFT + ALT + CTRL +  (0-9) numpad, SDL_GetModState returns 'ALT|CTRL' but not SHIFT
> 2. Disable the NUM lock, and it starts returning SHIFT modifier(for 0-9 num pad key)
> 
> For all other keys, SDL_GetModState returns SHIFT(if pressed)

On 2015-07-24 11:58:47 +0000, Vikas wrote:

> I tested the same scenario in Linux and it works fine.
> 
> It seems its windows bugs. 
> Consider the following scenario:
> 1. Enable NUM lock
> 2. Press SHIFT + 1(Num pad(0-9) key)
> 
> Here I get 3 events
> 1. SHIFT released(I didn't released the shift)
> 2. NUM 1
> 3. SHIFT pressed
> 
> instead of NUM 1 + modifier(SHIFT)
> 
> It looks like windows is sending one extra SHIFT released and pressed event.
> 
> Any workaround for this?

**Comment by slouken** [comment]
Windows is actually sending a key up message for the shift key. I don't think there's anything we can do about that.
