### ISSUE TITLE
numFingers is 16 bit and then 32 bit depending on event structure

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1921]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-07-12 13:32:32 +0000, Luke A. Guest wrote:

> Hi,
> 
> Whilst binding the events, I found an inconsistency with the above field in SDL_MultiGestureEvent and SDL_DollarGestureEvent, in the former it is Uint16 and the latter it is Uint32. Surely they should both be 16 bit with a padding field?
> 
> Thanks,
> Luke.

**Comment by icculus** [comment]
Evaluate this in SDL3 (including whether we should just remove gesture support. It might be something to spin out to a satellite library that you feed touch events to? Or just remove outright?)

**Comment by slouken** [comment]
Agreed, I don't know of anyone who uses the API. Possibly we can default the support off in SDL3 prereleases and see if anyone cares.

**Comment by icculus** [comment]
Gesture is gone, but tossing this into 3.2 just in case we want to consider any changes to the touch event structs. Close this as completed if not.
