### ISSUE TITLE
SDL_MOUSEBUTTONUP event triggers out of the SDL window

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1944]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2015-08-11 05:37:23 +0000, Amit Jain wrote:

> Step to reproduce:
> 1. Press the left mouse button with inside SDL window and keep the button pressed.
> 2. Move the mouse cursor outside of SDL window and release it.
> 3. SDL Window triggers a single SDL_MOUSEBUTTONUP event.
> 
> Expected result:
>  >> This SDL_MOUSEBUTTONUP event beyond the window shouldn't appear.

On 2015-08-12 14:16:47 +0000, Ryan C. Gordon wrote:

> 
> My understanding is that this has to happen, or apps may think the mouse button was held down forever.
> 
> --ryan.

On 2015-08-13 06:48:49 +0000, Pankaj wrote:

> (In reply to Ryan C. Gordon from comment # 1)
> > My understanding is that this has to happen, or apps may think the mouse
> > button was held down forever.
> > 
> > --ryan.
> 
> Hi Ryan,
> 
> As per my analysis current behavior of SDL_MOUSEBUTTONUP event in Linux & Windows :
> Linux: 
> 1. Press the left mouse button with inside SDL window and keep the button pressed.
> 2. Move the mouse cursor outside of SDL window and release it.
> 3. SDL_MOUSEBUTTONUP event comes to application at the moment we release button.
> 
> Windows:
> 1. Press the left mouse button with inside SDL window and keep the button pressed.
> 2. Move the mouse cursor outside of SDL window and release it.
> 3. SDL_MOUSEBUTTONUP event doesn't come(It comes when cursor moves inside the SDL window)
> 
> In linux case, application is knowing button released event at the same time when it is released.
> In windows case, application is not knowing when button is released. It knows only mouse moves inside the window.
> 
> Behaviour of Release events should be consistent in both the platforms.

On 2015-08-15 05:20:12 +0000, Ryan C. Gordon wrote:

> (In reply to Pankaj from comment # 2)
> > In linux case, application is knowing button released event at the same time
> > when it is released.
> > In windows case, application is not knowing when button is released. It
> > knows only mouse moves inside the window.
> > 
> > Behaviour of Release events should be consistent in both the platforms.
> 
> 
> Tossing this bug to Sam to look at.
> 
> Sam, which platform is correct here, or should either behavior be considered acceptable?
> 
> --ryan.

On 2015-08-24 07:24:12 +0000, Amit Jain wrote:

> Hi Mr. Sam,
> 
> Which is correct behavior?
> 
> 
> Regards,
> Pankaj

On 2016-10-08 01:14:33 +0000, Sam Lantinga wrote:

> We probably want to release the button when it actually goes up. I think currently we also release the button when the window loses focus.

**Comment by gschwind** [comment]
Hello,

This bug is in conflict with #2819

Following the documentation the correct behavior is that the SDL window should recieve the mouse up event [[1]](https://wiki.libsdl.org/SDL_CaptureMouse)

Best regards

[[1] https://wiki.libsdl.org/SDL_CaptureMouse](https://wiki.libsdl.org/SDL_CaptureMouse)
