### ISSUE TITLE
SDL_WINDOWEVENT_LEAVE / SDL_WINDOWEVENT_ENTER receive issue

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1953]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows 8, x86_64

# Comments on the original bug report:

On 2015-08-24 10:58:43 +0000,  wrote:

> There is a issue with receiving window leave / enter events. When you press mouse button and hold it down and then you move "fast" out of SDL window, app does not receive SDL_WINDOWEVENT_LEAVE event. Same problem appears when you enter window (SDL_WINDOWEVENT_ENTER event). Its really annoying.

**Comment by icculus** [comment]
I don't know what platform this was on, but this is almost certainly behaving differently due to the new autocapture code (now you don't get the LEAVE event until you let go of the mouse button in this scenario).

Assuming fixed until someone reports it again in a new bug.
