### ISSUE TITLE
SDL can not recognize the key is pressed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1965]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-09-06 15:01:57 +0000,  wrote:

> When running SDL, I meet this problem: "The key you just pressed is not recognized by SDL. To help get this fixed , please report... X11 Keycode 37 (29) , X11 KeySym 0x0 ((null))"

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
