### ISSUE TITLE
SDL2 color cursors are offset on OS X

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1966]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Test case (sdl2-color-cursor-test.c, text/x-csrc, 2015-09-06 19:59:07 +0000, 3221 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2258)
* [Screenshot of game 0 A.D. showing effect of bug (osx-cursor-offset-bug-effect.png, image/png, 2015-09-06 20:01:58 +0000, 47769 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2259)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2015-09-06 19:59:07 +0000, historic_bruno wrote:

> Created attachment 2258
> Test case
> 
> As reported here: https://forums.libsdl.org/viewtopic.php?t=11308
> 
> On every version of OS X I've tested, SDL2 color cursors (created by SDL_CreateColorCursor and SDL_CreateRGBSurfaceFrom) appear offset by about 3 pixels in both x and y directions. I'll attach some sample code, which works perfectly with no offsets on Linux and Windows. I'll also attach a screenshot from the game 0 A.D. with overlays to show the effect on our GUI interaction.
> 
> I tried to work around the offset by decreasing the x and y hotspot values passed to SDL_CreateColorCursor, but this caused an ugly black rectangle to follow the cursor on Yosemite (perhaps another bug?)

On 2015-09-06 20:01:58 +0000, historic_bruno wrote:

> Created attachment 2259
> Screenshot of game 0 A.D. showing effect of bug
> 
> Here is a screenshot showing a button in the game 0 A.D.'s UI, with a green overlay of where the cursor should activate the button, as it does on Linux and Windows. The red overlay shows where the cursor appears to activate the button on OS X.

**Comment by icculus** [comment]
Updated test program, draws a green box that is centered on the cursor's hotspot.

```c
// Test for color cursor behavior on OS X

#include "SDL.h"
#include <stdio.h>

// 8x8 red sprite for test cursor
unsigned int pixels[] = {
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000,
    0xFFFF0000, 0xFFFF0000, 0xFFFF0000, 0xFFFF0000
};

int main(int argc, char* argv[]) {

    SDL_Window *window;

    SDL_Init(SDL_INIT_VIDEO);

    window = SDL_CreateWindow(
                              "SDL2 Color Cursor Test",
                              SDL_WINDOWPOS_UNDEFINED,
                              SDL_WINDOWPOS_UNDEFINED,
                              150,
                              100,
                              SDL_WINDOW_OPENGL
                              );

    if (window == NULL) {
        printf("Could not create window: %s\n", SDL_GetError());
        return 1;
    }

    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
    if (renderer == NULL) {
        printf("Could not create renderer: %s\n", SDL_GetError());
        return 1;
    }

    SDL_Surface* surface = SDL_CreateRGBSurfaceFrom(pixels, 8, 8, 32, 32, 0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000);
    if (surface == NULL) {
        printf("Could not create surface: %s\n", SDL_GetError());
        return 1;
    }
    // Hotspot of (3,3) here "fixes" the bug on OS X
    SDL_Cursor* cursor = SDL_CreateColorCursor(surface, 0, 0);
    if (cursor == NULL) {
        printf("Could not create cursor: %s\n", SDL_GetError());
        return 1;
    }
    SDL_SetCursor(cursor);

    while (1) {
        SDL_Event event;
        SDL_Rect r;

        if (SDL_PollEvent(&event)) {
            if (event.type == SDL_QUIT)
                break;
            else if (event.type == SDL_WINDOWEVENT) {
                switch (event.window.event) {
                    case SDL_WINDOWEVENT_ENTER:
                        printf("Mouse entered window %d\n",
                               event.window.windowID);
                        break;
                    case SDL_WINDOWEVENT_LEAVE:
                        printf("Mouse left window %d\n", event.window.windowID);
                        break;
                    default:
                        break;
                }
            }
        }

        SDL_GetMouseState(&r.x, &r.y);
        r.w = r.h = 6;
        r.x -= r.w / 2;
        r.y -= r.h / 2;

        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 0, 255, 0, 255);
        SDL_RenderFillRect(renderer, &r);
        SDL_RenderPresent(renderer);
    }

    SDL_FreeCursor(cursor);
    SDL_FreeSurface(surface);

    SDL_DestroyWindow(window);
    SDL_DestroyRenderer(renderer);

    SDL_Quit();
    return 0;
}
```

**Comment by icculus** [comment]
This appears to work now...the this we're drawing is centered on the cursor's hotspot (picture taken on phone both to zoom in and capture the cursor).

![image](https://user-images.githubusercontent.com/673562/147683169-1e352c8f-a06d-44c8-9e75-788a70e616a2.jpeg)

**Comment by icculus** [comment]
Tested with non-zero hotspot coords and it works, too. This clearly got fixed at some point.
