### ISSUE TITLE
It would be nice, if SDL would support including SDL project as a subdirectory into another CMake project

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2010]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [CMakeLists.txt patch (file_3166.txt, text/plain, 2018-09-23 10:51:13 +0000, 1597 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3307)

**Reported in version:** don't know
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2015-11-07 21:06:15 +0000, Denis Kerzhemanov wrote:

> One of the variants of using external CMake project inside your project, is including it as a directory using add_subdirectory directive. It is very useful if you want to build SDL yourself. Then you just write something like that:
>   add_subdirectory(../SDL2 SDL2)
>   target_link_libraries(yourtarget 
> 	SDL2
> 	SDL2main
>   )
> It works almost fine, but there is one small problem. CMake can automatically import include directories from libraries, but in case of SDL this feature does not work. To make it work, you need to do two things:
>   1. Remove this string from CMakeLists.txt:
>     include_directories(${SDL2_BINARY_DIR}/include ${SDL2_SOURCE_DIR}/include)"
>   2. Add these strings somewhere after definition of correspondent libraries: 
>     target_include_directories(SDL2 PUBLIC ${SDL2_BINARY_DIR}/include PUBLIC ${SDL2_SOURCE_DIR}/include)
>     target_include_directories(SDL2main PUBLIC ${SDL2_BINARY_DIR}/include PUBLIC ${SDL2_SOURCE_DIR}/include)
>     target_include_directories(SDL2-static PUBLIC ${SDL2_BINARY_DIR}/include PUBLIC ${SDL2_SOURCE_DIR}/include)
> target_include_directories directive is better way of adding include directories because it makes obvious for what libraries they are added. Also it allows you to specify whether those directories will be needed by dependent projects.
> 
> Thank you!

On 2016-02-24 21:06:48 +0000, Magnus Bjerke Vik wrote:

> I would also like this to be added. It makes using the library as a subproject easier, though it is still possible without it.
> 
> I thought I'd mention that you need to bump the cmake_minimum_required version to 2.8.11, as the function was introduced in this version: https://cmake.org/files/v2.8/CMakeChangeLog-2.8.11

On 2018-09-23 10:51:13 +0000, Wayde Reitsma wrote:

> Created attachment 3307
> CMakeLists.txt patch
> 
> After attempting to use SDL2 in the way described in this bug, I found the main issue was the includes not being added to the compiler command.
> 
> I found the issue was that the target_include_directories commands for the SDL2, SDL2-static and SDL2main targets only sets the public includes for installations using the INSTALL_INTERFACE generator expression.
> 
> I have written a patch to CMakeLists.txt that fixes this issue by adding another item to the target_include_directories commands, utilizing the BUILD_INTERFACE generator expression to correctly add the include directory during builds.

On 2018-09-24 15:42:33 +0000, Sam Lantinga wrote:

> I've added your patch, is that all that is needed to close this bug?
> https://hg.libsdl.org/SDL/rev/4972784f494e

On 2018-09-25 05:48:04 +0000, Wayde Reitsma wrote:

> Unfortunately I've run into a bit of a problem. The patch I submitted doesn't take into account the generated SDL_config.h, and while trying to add it to the includes, I was unable to get CMake to add the generated include directory before the main include directory. CMake seems to disregard the order that the include directories were specified in the CMakeLists.txt file.
> 
> This results in programs that use the CMake add_subdirectory method to include the manually written SDL_config_{platform}.h header instead of the CMake generated one. This won't necessarily cause an error, but it is not ideal.
> 
> I'm not sure what to do about this, as I can't find a way to force CMake to add the include directories in a particular order.

**Comment by saxbophone** [comment]
I have done some work implementing something similar to this in a fork, which allows CMake's [`FetchContent()`](https://cmake.org/cmake/help/latest/module/FetchContent.html) API to be used to fetch and build SDL as a sub-project.

I've tested it using CPM (https://github.com/cpm-cmake/CPM.cmake), a third-party wrapper around `FetchContent()`, but it should also work with bare `FetchContent()` and possibly when SDL is used as a Git submodule too.

I think I shall make some small test projects to verify that these all work with my patch, and if this is something others might find useful, submit a PR.

**Comment by icculus** [comment]
I think we have since fixed this in SDL itself...?  Will verify for 2.0.20 and decide what to do, if anything.

**Comment by saxbophone** [comment]
@icculus I think that is correct. I remember testing SDL as a subproject for my linked patch (test code: https://github.com/saxbophone/SDL-cmake-subproject-test/tree/master/test-git-submodule).

**Comment by glebm** [comment]
Here is an example in the wild (from Devilutionx) of how to use SDL2 via FetchContent: https://github.com/diasurgical/devilutionX/tree/master/3rdParty/SDL2

**Comment by ericoporto** [comment]
@saxbophone how do you solve the SDL_config.h that is generated in a different directory? Also the sdl2-config.cmake that is also made in some random place? I had to roll all sorts of magic to be able to fetch and add subdirectory below (this works with SDL2 at least 2.0.12 to 2.0.20)

https://github.com/ericoporto/ags/blob/master/CMake/FetchSDL2.cmake

**Comment by icculus** [comment]
> how do you solve the SDL_config.h that is generated in a different directory?

For what it's worth, unconfigured SDL headers can be used to build SDL apps; in modern times, we've moved most of the target-specific stuff out of the public headers (macros are now functions that do the right thing inside SDL but look the same to the calling app, or platform-specific things are handled with unchanging preprocessor checks in the default headers, etc).

SDL itself needs the configured header to build properly, but your app that uses SDL does not.

I'm not sure if this answers your question...?

**Comment by ericoporto** [comment]
I was answering in the subject of the original issue above 2018 message

> Unfortunately I've run into a bit of a problem. The patch I submitted doesn't take into account the generated SDL_config.h, and while trying to add it to the includes, I was unable to get CMake to add the generated include directory before the main include directory. CMake seems to disregard the order that the include directories were specified in the CMakeLists.txt file.
> 
> This results in programs that use the CMake add_subdirectory method to include the manually written SDL_config_{platform}.h header instead of the CMake generated one. This won't necessarily cause an error, but it is not ideal.



https://github.com/libsdl-org/SDL/blob/6d1c3cd6918aa84fe2a0ba7d895169a4f69233bc/CMakeLists.txt#L308

I have not checked it recently but it's basically the headers are in a binary dir and aren't passed publicly from the targets so you endup with a config that causes weird errors - like in Android.

**Comment by madebr** [comment]
@glebm

> First, SDL2's `CMakeLists.txt` does not define the `SDL2::SDL2` target for the static-only build. We work around it like this:
> 
> ```cmake
> if(TARGET SDL2::SDL2-static)
>   add_library(SDL2::SDL2 ALIAS SDL2-static)
> endif()
> ```

https://github.com/libsdl-org/SDL/pull/5800 will fix this.

> Second, we have to add an empty [`FindSDL2.cmake`](https://github.com/diasurgical/devilutionX/blob/master/3rdParty/SDL2/CMake/FindSDL2.cmake), so that other projects that use SDL2 use the same version. This is probably (?) unavoidable unless there is some magic CMake variable that can be set to tell `find_package(SDL2)` to do nothing.

Current master (=will be in the next release) installs cmake config files, hoping that every project carrying a `FindSDL2.cmake` scripts will be a thing of the past.
I don't understand the "empty" in your statement though.

**Comment by glebm** [comment]
> Current master (=will be in the next release) installs cmake config files, hoping that every project carrying a FindSDL2.cmake scripts will be a thing of the past.
I don't understand the "empty" in your statement though.

We use SDL2 as a subproject but other subprojects that we include do `find_package(SDL2 REQUIRED)`.

To allow that call to succeed, we add a stub `FindSDL2.cmake` that does nothing (at the time of me writing that comment -- https://github.com/diasurgical/devilutionX/blob/b038b3ce3d304cde0cc0e305756b2ad858741b36/3rdParty/SDL2/CMake/FindSDL2.cmake). This is probably the only way to achieve this in CMake in general.

**Comment by glebm** [comment]
> https://github.com/libsdl-org/SDL/pull/5800 will fix this.

Thanks for fixing this!

**Comment by ericoporto** [comment]
The pr that actually theoretically fixed the include being in the wrong place I mentioned is #5829

**Comment by Rickodesea** [comment]
OK, thanks for this thread.  

I am also including SDL as a subproject:
```cmake
add_subdirectory(${Src}/SDL ${Bin}/SDL)
```
in which `${Src}/SDL` is SDL2 project's root directory.

I was trying to figure out why I am getting this error:
```bash
Build/Debug/SDL/include/SDL2/SDL_stdinc.h:31:10: fatal error: SDL_config.h: No such file or directory
   31 | #include "SDL_config.h"
```
But then I realized, that the SDL_config.h is generating but not in the SDL include folder that's in my bin
directory. So it's missing since I am using that include folder as the include folder for SDL.
```cmake
target_include_directories(${project-core} PUBLIC
${Bin}/SDL/include
)
```

### My Solution

I found a solution by just adding a copy function in the CmakeLists.txt file that calls add_subdirectory(SDL).

Here is my example:
```cmake
if($<CONFIG:Release>) 
    set(SDL_CONFIG_FOLDER include-config-release/SDL2) 
else() 
    set(SDL_CONFIG_FOLDER include-config-debug/SDL2) 
endif()

CxCopy(FILE 
INPUT ${Bin}/SDL/${SDL_CONFIG_FOLDER}
OUTPUT ${Bin}/SDL/include/SDL2 
VAR sdl-config-headers
)
add_custom_target(copy-sdl-config-headers DEPENDS ${sdl-config-headers})
add_dependencies(${project-core} copy-sdl-config-headers)
```

`${Bin}` is the bin root directory SDL is being built in.  I am building the SDL2 project in a folder called SDL hence my
my full path is ${Bin}/SDL.
`${project-core}` is my project's target that depends on SDL2.  This is where the source codes that include SDL2 exists (that is, `#include "SDL2/SDL.h"`).
`CxCopy` is a custom made Cmake Copy function.  You can get it here: https://github.com/Rickodesea/Cmake-Extensions

**Comment by madebr** [comment]
@Rickodesea 
How are you using SDL2?
SDL2's cmake script is already copying the headers to appropriate locations, to ensure a generated `SDL_config.cmake` is used.

When linking to a vendored `SDL2` target (or `SDL2::SDL2` in general), the SDL2 include paths in the SDL2 build directory are added automatically to your target [This is done here.](https://github.com/libsdl-org/SDL/blob/f569cc56a97567635d5a75712a82e9b6e5860d3a/CMakeLists.txt#L3466-L3472) The `PUBLIC` is important.

So the following should be sufficient for `#include "SDL_config.h"` to work:
```cmake
target_link_libraries(yourgame PRIVATE SDL2::SDL2)
```

When you don't link to SDL2, but explicitly only want access to its headers, you can do the following:
```cmake
target_include_directories(yourgame PRIVATE $<TARGET_PROPERTY:SDL2::SDL2,INTERFACE_INCLUDE_DIRECTORIES>)
```

With SDL3, there is a dedicated headers-only target, usable as
```cmake
target_link_libraries(yourgame PRIVATE SDL3::Headers)
```

**Comment by Rickodesea** [comment]
@madebr I wrote in my answer how I am using it - using add_subdirectory.   
SDL_Config.h doesn't get copied into the include directory if you add SDL as a cmake subdirectory.
I'm using SDL2 2.28.5 not SDL3.
https://github.com/libsdl-org/SDL/releases/tag/release-2.28.5

I no longer have an issue, thank you.
I shared my solution to be useful to someone else who may run into the problem.

**Comment by saxbophone** [comment]
You can see a sample CMake project I made for testing SDL with a change I
made to their CMake config (since merged!) here:
https://github.com/saxbophone/SDL-cmake-subproject-test
