### ISSUE TITLE
SDL_RenderDrawRect direct3d

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2018]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2015-11-11 23:07:54 +0000, Marcel Bakker wrote:

> Windows 7
> direct3d
> 
> In SDL_RenderDrawRect(),
> the top-left and bottom-left corners are drawn 2 times.

On 2017-08-12 22:50:56 +0000, Sam Lantinga wrote:

> More drawing endpoint bugs for you, Ryan.

**Comment by icculus** [comment]
This is confirmed fixed.
