### ISSUE TITLE
libsdl2: windows set to fullscreen with SDL_WINDOW_FULLSCREEN_DESKTOP are not visible in xmonad

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2023]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [c++ program demonstrating issue (file_3180.txt, text/plain, 2015-11-14 06:59:04 +0000, 901 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2302)

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-11-14 06:59:04 +0000, Lucian Poston wrote:

> Created attachment 2302
> c++ program demonstrating issue
> 
> Fullscreen windows created via SDL_CreateWindow() using the SDL_WINDOW_FULLSCREEN_DESKTOP flag are not visible when run in xmonad window manager. This also occurs to a window is set to fullscreen via SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP).
> 
> Attached simple program demonstrating issue.

On 2015-11-14 09:49:42 +0000, Lucian Poston wrote:

> For anyone else encountering this issue, a workaround in xmonad is to enable ewmh. See http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-EwmhDesktops.html#v:ewmh
> 
> Enabling ewmh causes libsdl2 to use _NET_WM_STATE_FULLSCREEN code path instead of the legacy mode in SDL_x11window.c.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
