### ISSUE TITLE
SDL_SetWindowSize oddness

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2040]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Test program demonstrating the problem, written in C99 (sdlbug.c, text/x-csrc, 2015-12-03 22:32:46 +0000, 3905 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2326)

**Reported in version:** 2.0.2
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-12-03 22:32:46 +0000, Solra Bizna wrote:

> Created attachment 2326
> Test program demonstrating the problem, written in C99
> 
> When I change a window's size with SDL_SetWindowSize, and subsequently make SDL_Render* calls without processing events, the renderer gives incorrect output. It continues to give incorrect output until the SDL_WINDOWEVENT_EXPOSED event generated by the call is _received_. I have attached a program that demonstrates the problem.
> 
> I'm running on Linux, under X11, using Sawfish (a non-compositing window manager). The test program reports that the OpenGL renderer is being used.
> 
> The test program doesn't reflect this, but I tried combinations of SDL_RenderSetLogicalSize / SDL_RenderSetViewport and every similar function I could find with no effect.
> 
> If you change the "#if 0" on line 27 to "#if 1", it repeats Clear+Copy+Present every time a SDL_WINDOWEVENT_EXPOSED event is received, and the glitches effectively disappear. It also, however, hits a much less serious bug, in that an excessive number of SDL_WINDOWEVENT_EXPOSED events are generated. (A "good" event loop will defer actually rendering until SDL_PollEvent returns 0, which makes that bug unimportant to me.)
> 
> It is possible that this is not a bug, in which case the actual bug is in the documentation for SDL_SetWindowSize. It can be worked around completely by not rendering between calling SDL_SetWindowSize and receiving the corresponding SDL_WINDOWEVENT_EXPOSED event.

On 2016-01-03 14:36:05 +0000, Solra Bizna wrote:

> Upon testing with different renderers, I have found that SDL_WINDOWEVENT_EXPOSED is not always generated on calling SDL_SetWindowSize. My more universal workaround now also involves explicitly pushing an SDL_WINDOWEVENT_EXPOSED event after calling SDL_SetWindowSize. Blech...

**Comment by icculus** [comment]
I'm assuming this is either a window manager/driver/whatever issue, or we fixed it.
