### ISSUE TITLE
SDL_SetWindowSize and unwanted window movement

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2041]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.2
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2015-12-05 21:50:23 +0000, Solra Bizna wrote:

> I implemented the workaround for bug # 3198 into my "real app", but now every time SDL_SetWindowSize is called, the window moves down and to the right by the size of my left and top window decorations. I suspect this is another manifestation of the underlying problem bug # 1300 dealt with. I tried working around it with SDL_GetWindowPosition before the call, SDL_SetWindowPosition after, and another SDL_GetWindowPosition to be sure it stuck... but the window seems to move some time after the expose event is generated for that window.
> 
> The test program I gave for # 3198 also displays this bug. As with # 3198, I'm running on Linux, under X11, using Sawfish.

On 2015-12-29 05:32:37 +0000, Ryan C. Gordon wrote:

> 
> Out of curiousity, are you on SDL 2.0.3? I believe we fixed this a few months ago in revision control, but I could be wrong.
> 
> --ryan.

On 2015-12-30 06:32:50 +0000, Ryan C. Gordon wrote:

> (In reply to Ryan C. Gordon from comment # 1)
> > Out of curiousity, are you on SDL 2.0.3? I believe we fixed this a few
> > months ago in revision control, but I could be wrong.
> 
> No, wait, I'm thinking of Bug # 3085, which isn't fixed, but I'm about to look into...so you should get some results soon, I hope.
> 
> --ryan.

**Comment by icculus** [comment]
Assuming this is fixed.
