### ISSUE TITLE
introduce a typedef for a type that marks functions that return an error-code

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2059]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2016-01-01 16:53:41 +0000,  wrote:

> i'm working on a Common Lisp FFI for libsdl, and the whole thing is mostly automatically generated (https://github.com/attila-lendvai/hu.dwim.sdl).
> 
> on the lisp side i have introduced a type that upon ffi->lisp conversion automatically signals an error if the return value is negative, but right now i would need to list every function by hand where it applies. unfortunately not all int return values are error codes.
> 
> if there was something along the lines:
> 
> typedef SDL_ErrorCode int;
> 
> and it was used to mark the functions that return an error code, then the lisp FFI could automatically translate that type. please consider adding this!

On 2017-08-12 21:49:16 +0000, Sam Lantinga wrote:

> That seems like a good change for SDL 2.1

**Comment by attila-lendvai** [comment]
if i may, today i'd propose the name `SDL_ReturnCode` instead... :)

**Comment by icculus** [comment]
Honestly, I think it's wordy and I don't think we should jump through hoops for random language bindings, but I'll put this in the SDL3 milestone for now, where we will maybe close this as WONTFIX.

**Comment by attila-lendvai** [comment]
the exact name is not relevant, it may be as short as `eint`.

also note that at this point most languages that want to use SDL through an FFI have an automatic binding generator, and a condition system to handle exceptions. IOW, this applies to almost all of the languages that want to interface with SDL through an FFI.

**Comment by slouken** [comment]
I think we won't do this in the SDL headers, instead it would be in markup for language bindings generated by gendynapi.py. I'm going to add this to https://github.com/libsdl-org/SDL/issues/6337.

**Comment by attila-lendvai** [comment]
> I don't think we should jump through hoops for random language bindings

i'm wonder what's the ratio of the users of SDL who 1) use it from C, and those who 2) use it from another language through some FFI binding... i wouldn't be surprised if 2) was larger than 1).

**Comment by slouken** [comment]
FWIW, I reviewed the SDL API return values and it's all over the place. Often the functions return -1 or 0, but there are functions that return SDL_bool, pointers, integers that have non-error code meanings, etc.
