### ISSUE TITLE
Clang Module maps

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2091]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Mac OS X framework module map (SDL2.modulemap, text/plain, 2016-02-02 01:33:04 +0000, 1761 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2370)
* ~~[Linux/OS X library module (SDL2-linux.modulemap, text/plain, 2016-02-02 01:41:06 +0000, 2156 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2371)~~
* [Linux/OS X library module, v2 (SDL2-linux.modulemap, text/plain, 2016-02-02 02:02:46 +0000, 2172 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2373)
* [module map diff (properModuleMap.diff, text/plain, 2016-02-06 20:33:50 +0000, 5479 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2377)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Mac OS X 10.8, x86_64

# Comments on the original bug report:

On 2016-02-02 01:33:04 +0000, C.W. Betts wrote:

> Created attachment 2370
> Mac OS X framework module map
> 
> The following are module maps that can be used by Swift to help with importing.
> 
> The commented out sections are due to Mac OS X not having OpenGL ES headers.

On 2016-02-02 01:41:06 +0000, C.W. Betts wrote:

> Created attachment 2371
> Linux/OS X library module
> 
> This is a library module that can be used by Linux and Mac OS X built as a library.
> 
> It could be set so that the include path is set by the configure/CMake script instead of being hard-coded.

On 2016-02-02 02:02:46 +0000, C.W. Betts wrote:

> Created attachment 2373
> Linux/OS X library module, v2
> 
> This is a library module that can be used by Linux and Mac OS X built as a library.
> 
> It could be set so that the include path is set by the configure/CMake script instead of being hard-coded.

On 2016-02-06 20:33:50 +0000, C.W. Betts wrote:

> Created attachment 2377
> module map diff
> 
> Actual patch that adds the module map file to the build phase.

**Comment by icculus** [comment]
This sort of feels like it will bitrot over time and no one will maintain it. Also it's five years old at this point. I'm closing this one, but if someone stumbles upon it and wants to educate me, I can be convinced to change my mind.
