### ISSUE TITLE
Controller event SDL_CONTROLLERDEVICEREMOVED not clear.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2092]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-02-02 09:39:09 +0000, Alain Dupuis wrote:

> From the name of the event 'SDL_CONTROLLERDEVICEREMOVED' one would believe the event to be triggered whenever a controller is removed. Only after looking at the source code (as of changeset 10061) file:SDL_events.h line:121 that one can tell that this event is triggered only when an "opened" controller has been removed.
> 
> This leaves no event for when any unopened controller is removed. This causes a problem if a list of available controllers is built and presented to the user and a controller is removed before the user makes a choice. Since no events are triggered there is no way of telling that a particular controller is no longer available, unless the program keeps checking all the controllers over and over.
> 
> Wouldn't it be better to send that event whenever any controller is removed, and leave it to the programmer to check if it's an opened one and take action if it's the case?
> 
> Thanks.

On 2017-08-12 04:50:34 +0000, Sam Lantinga wrote:

> Yes, that makes sense. I'm marking this for review for SDL 2.1.
> 
> Thanks!

**Comment by icculus** [comment]
We just solved this in 2.24.0 for unopened audio devices by reporting an id of zero (which is not a valid audio device ID, but safe to attempt to close). We could do the same here in SDL2, too.

**Comment by slouken** [comment]
We can do a little better than that. We actually have the device ID, we just didn't know whether it was a game controller.
