### ISSUE TITLE
CMake 3.5 could not build SDL source

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2108]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2016-02-23 22:09:45 +0000,  wrote:

> in CMakeLists.txt, we have :
> 
> if(${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_BINARY_DIR})
>   message(FATAL_ERROR "Prevented in-tree built. Please create a build directory outside of the SDL source code and call cmake from there")
> endif()
> 
> in CMake version 3.5-RCx, CMAKE_BINARY_DIR is internally setting ( looks like  ) to be the same as CMAKE_SOURCE_DIR. So the above comparison will end up with always TRUE, hence could not build.  This happens with all version of CMAKE 3.5 RC.  CMake guys recommended not to manually mess up CMAKE_BINAR_DIR, so they have no plan to make it behaves the same as earlier cmake versions.
> 
> With some experiments, looks this could be fixed with
> 
> if(${CMAKE_CURRENT_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_BINARY_DIR})
>   message(FATAL_ERROR "Prevented in-tree built. Please create a build directory outside of the SDL source code and call cmake from there")
> endif()
> 
> CMAKE_CURRENT_SOURCE_DIR & CMAKE_CURRENT_BINARY_DIR approach works for both cmake 3.5 RC versions and also 3.4, 3.3

**Comment by slouken** [comment]
@icculus, can you check to see if this is still an issue?

**Comment by Wohlstand** [comment]
I checked this just now, with my fixes (where the CMake < 3.7 builds is broken), this works perfectly, I tried with CMake 3.5.0, works just fine, @slouken, you may close this, because fixes I made, aren't related to this problem which is no longer exists since there "CMAKE_CURRENT..." was already used here as mentioned at the post.

**Comment by slouken** [comment]
Okay, thanks!
