### ISSUE TITLE
SDL 2.0.4 does not allow activating system menu via keyboard

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2114]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch allows users to activate the system menu via keyboard. (sdl2-allow-sysmenu.patch, text/plain, 2016-02-29 03:31:56 +0000, 443 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2386)

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows (All), All

# Comments on the original bug report:

On 2016-02-29 03:31:56 +0000,  wrote:

> Created attachment 2386
> Patch allows users to activate the system menu via keyboard.
> 
> When using programs linked against SDL 2.0.4, the system menu is not properly activated when pressing Alt-Space. I tracked this down to hg commit 9624. In this commit, the developer was working around Windows's extra noisy behavior, fixing bug # 2669. He did this by gobbling up every WM_SYSCOMMAND message, including legitimate ones.
> 
> I've provided a patch that allows WM_SYSCOMMAND when the Alt-Space is pressed, so that the system menu can still be activated. There may be other Alt-* combinations that should be whitelisted too.

On 2017-08-12 04:40:08 +0000, Sam Lantinga wrote:

> We may need to add a hint for this. Games which use ALT as control (e.g. show HUD state, etc.) may want to be able to use space for jumping at the same time. More desktop style applications may be able to want to get to the system menu.
> 
> What is your use case here?

On 2017-08-14 08:43:44 +0000,  wrote:

> The use case is just ordinary window management. Moving the window, resizing, maximizing, etc. I discovered this bug when I was using a Windows computer with a low resolution screen, and the SDL2 program I was looking at had a window that was too big. The title bar was beyond the top of the screen, so I couldn't reach it with the mouse. Then I found out Alt-Space did not work as expected, and I could not move or resize the window at all.
> 
> Adding a hint might be a good idea. Would the same hint also disable Alt-Tab? Maybe the game wants to use Tab for firing and F4 to change the HUD.
> 
> Right now Alt-Space works fine in Linux, and I assume Mac, since hg commit 9624 was Windows specific and not intended to disable anything other than Windows's excessive beeping. Introducing this bug to Windows was an accident.
> 
> If you do add a hint, please make the default be to allow window manipulation via Alt-*, because those controls work fine in nearly every program, including SDL programs before 2.0.4, and users expect it to work. Also, the similar hint that's been available since SDL 2.0.4, SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4, allows Alt-F4 to work by default.

**Comment by icculus** [comment]
If someone can use Alt to get at the title bar, they can also right-click the window in the taskbar and choose "move" to deal with the "titlebar is off the screen" scenario. @slouken, should we just close this one?

**Comment by slouken** [comment]
I just surveyed a bunch of Windows games and none of them responded to Alt-Space, even when windowed. I'm fine with adding a hint that defaults off, but given this isn't a request we get much, let's go ahead and close it for now.
