### ISSUE TITLE
Upgrade from SDL 2.0.3 to 2.0.4: The key you just pressed is not recognized by SDL.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2116]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2016-02-29 09:02:40 +0000,  wrote:

> My System:
> Raspberry Pi 2 with Rasbian, Kernel 4.1.17
> Gamepad: Wii U Pro Controller connected via xwiimote (https://github.com/dvdhrm/xwiimote) and Bluetooth
> Keyboard: Small Bluetooth keyboard
> 
> I have RetroPie working on this system which is a compilation of several emulators for the Raspberry Pi. These emulators and their frontend make much use of SDL.
> 
> As long I had installed SDL 2.0.3 I had no problems.
> After the installation of SDL 2.0.4 some days ago I get several of these error messages when I start any of the emulators:
> 
> INFO: The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL mailing list sdl@libsdl.org EVDEV KeyCode 545
> INFO: The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL mailing list sdl@libsdl.org EVDEV KeyCode 305
> 
> My gamepad does not work anymore if I use sdl2 in RetroArch (http://www.libretro.com/). My key bindings got messed up. Using udev instead my gamepad works again. But those errormessages still remain.
> 
> What can I do to solve this? Is there is anything I can do to take a deeper look into this please let me know.

On 2016-04-11 19:08:47 +0000, Jools Wills wrote:

> I have bisected this to https://hg.libsdl.org/SDL/rev/6c86d3216f6a
> 
> from this ticket
> https://bugzilla.libsdl.org/show_bug.cgi?id=2719
> 
> I can confirm it breaks ps3 and the wii U pro and possibly other controllers. Had to roll back to 2.0.3 on RetroPie due to problems, but will revert this and do a custom 2.0.4 for our project.
> 
> I hope this can be looked into - without the patch we had no major problems before, and PS3 controllers worked.

**Comment by icculus** [comment]
Assuming this has been fixed since 2016.

**Comment by slouken** [comment]
Actually, probably not...

**Comment by slouken** [comment]
This has been fixed for this milestone.
