### ISSUE TITLE
SDL_SetTextInputRect fails when Ubuntu "Scale for menu and title bars" is higher than 1

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2117]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-03-01 06:59:26 +0000,  wrote:

> SDL_SetTextInputRect puts the IME candidate window at a different location than specified when the "Scale for menu and title bars" value in Ubuntu Display Settings is higher than 1. It seems to have multiplied the scale value to the specified coordinates.
> 
> Tested on a 3840x2160 screen in Ubuntu 16.04. The IME in question is ibus-pinyin, which is installed using apt-get.

On 2016-03-01 07:01:31 +0000,  wrote:

> The SDL used is a manually-built copy of the official 2.0.4 release with ibus support enabled. It's not the one installed from apt-get. I didn't make any custom change.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
