### ISSUE TITLE
Can't get system "SIZE" cursors, but instead always getting the "HAND" cursor

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2123]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-03-05 16:43:54 +0000, cra0zy@gmail.com wrote:

> The following cursors:
> SDL_SYSTEM_CURSOR_SIZENWSE
> SDL_SYSTEM_CURSOR_SIZENESW
> SDL_SYSTEM_CURSOR_SIZEWE
> SDL_SYSTEM_CURSOR_SIZENS
> SDL_SYSTEM_CURSOR_SIZEALL
> 
> are all getting replaced by:
> SDL_SYSTEM_CURSOR_HAND
> 
> That is trying to use them always results into getting a hand cursor.

On 2016-03-05 16:58:49 +0000, cra0zy@gmail.com wrote:

> Correction, they aren't getting replaced by SDL_SYSTEM_CURSOR_HAND
>  but by "fully closed hand", That hand is gotten when the window is moving.

On 2016-03-05 17:10:19 +0000, cra0zy@gmail.com wrote:

> And I may have jumped the gun, found the reason, it turns out that:
> SDL_SYSTEM_CURSOR_SIZEWE
> SDL_SYSTEM_CURSOR_SIZENS
> 
> work correctly, but these 2:
> SDL_SYSTEM_CURSOR_SIZENWSE
> SDL_SYSTEM_CURSOR_SIZENESW
> are getting replaced by the hand.
> 
> Some Linux DEs have 4 cursors, one for each corner instead of Windows like where there are 2 cursors.

On 2016-03-05 22:57:14 +0000, Philipp Wiesemann wrote:

> In "src/video/x11/SDL_x11mouse.c" the same cursor is set for SDL_SYSTEM_CURSOR_SIZENWSE, SDL_SYSTEM_CURSOR_SIZENESW and SDL_SYSTEM_CURSOR_SIZEALL.
> 
> This could be a bug. Or maybe the active cursor theme uses "closed hand" for both "sizing" and "moving" (which could be confusing :).

On 2016-03-06 21:07:27 +0000, cra0zy@gmail.com wrote:

> > Or maybe the active cursor theme uses "closed hand" for both "sizing" and "moving" (which could be confusing :).
> 
> Linux Cursor themes I've seen ended up having 4 different cursors for it(1 for each window corner). The API should probably be updated to support each corner cursor separately.
> 
> Example with awdita theme(default with GNOME):
> https://github.com/GNOME/adwaita-icon-theme/blob/master/src/cursors/pngs/96x96/top_left_corner.png
> https://github.com/GNOME/adwaita-icon-theme/blob/master/src/cursors/pngs/96x96/top_right_corner.png
> https://github.com/GNOME/adwaita-icon-theme/blob/master/src/cursors/pngs/96x96/bottom_left_corner.png
> https://github.com/GNOME/adwaita-icon-theme/blob/master/src/cursors/pngs/96x96/bottom_right_corner.png

On 2016-03-08 04:36:00 +0000, Ryan C. Gordon wrote:

> 
> This is because SDL_SYSTEM_CURSOR_SIZENWSE and SDL_SYSTEM_CURSOR_SIZENESW both map to X11's XC_fleur cursor. Windows has a cursor that has two diagonal arrows that matches well here, but X11 doesn't.
> 
> These are the choices:
> 
>  https://tronche.com/gui/x/xlib/appendix/b/
> 
> There are clearly better choices if we had separate SDL cursors for NE, NW, SE and SW (and Windows could have reused cursors as appropriate), but that's not how it worked out.
> 
> (Having a hand cursor is technically a bug in the font used for this, but it's probably because XC_fleur is generally used when dragging things.)
> 
> Going to mark this bug as ASSIGNED, so we can change this API later.
> 
> --ryan.

On 2018-08-06 21:20:25 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting dozens of copies of this message by email.
> 
> We are closing out bugs that appear to be abandoned in some form. This can happen for lots of reasons: we couldn't reproduce it, conversation faded out, the bug was noted as fixed in a comment but we forgot to mark it resolved, the report is good but the fix is impractical, we fixed it a long time ago without realizing there was an associated report, etc.
> 
> Individually, any of these bugs might have a better resolution (such as WONTFIX or WORKSFORME or INVALID) but we've added a new resolution of ABANDONED to make this easily searchable and make it clear that it's not necessarily unreasonable to revive a given bug report.
> 
> So if this bug is still a going concern and you feel it should still be open: please feel free to reopen it! But unless you respond, we'd like to consider these bugs closed, as many of them are several years old and overwhelming our ability to prioritize recent issues.
> 
> (please note that hundred of bug reports were sorted through here, so we apologize for any human error. Just reopen the bug in that case!)
> 
> Thanks,
> --ryan.

On 2018-08-07 06:13:15 +0000, cra0zy@gmail.com wrote:

> Gonna reopen this as this is still an issue.

**Comment by icculus** [comment]
Let's see if this is reasonable to extend the API 2.0.20.

**Comment by icculus** [comment]
Ok, wait, easy fix on X11: `XC_top_left_corner` points NWSE and `XC_top_right_corner` points NESW...at least on Gnome in Ubuntu 21.10. Like all things X11, we're at the mercy of the whims of the desktop environment, but I think that even if it ends up only pointing one way instead of two, it's better than the current `XC_fleur`.

...and no API changes necessary!  :)

Pushing that change and leaving open so I can double-check the Mac cursor situation.

**Comment by icculus** [comment]
macOS is sort of infuriating. Not only are the cursors in question hooked up to "hand," but the "wait" cursors are hooked up to generic "arrow."

Everything we need is there, [as undocumented APIs](https://stackoverflow.com/a/46635398), too. Which is to say we can query for them and use them, but this will result in a Mac App Store rejection.  😭

**Comment by slouken** [comment]
Maybe check with Nat on the status of the undocumented APIs?

**Comment by icculus** [comment]
I was already typing up an email.  :)

**Comment by icculus** [comment]
I wrote this email, but then realized you can load these cursors from image files in standard locations that are sandbox-accessible, so I'm going to try that first and save my political capital from when I need Metal shader bytecode format documentation.  :)

**Comment by icculus** [comment]
Okay, the new Mac code is in (and looks _great_!), so between the better X11 and better Cocoa support, this issue can be closed now.
