### ISSUE TITLE
Shaped windows creation and destruction

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2128]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2016-03-15 18:22:10 +0000, Juha Niemimäki wrote:

> There might be a couple of issues with shaped windows:
> 
> 1) SDL doesn't check the function pointers (like CreateShaper) before using ( https://hg.libsdl.org/SDL/file/9cec5fe32bca/src/video/SDL_shape.c#l38 )
> 
> 2) Cleanup: shouldn't shaper and data be cleaned during window destruction? Perhaps SDL_DestroyWindow could check for shaper existance, and when found, call a shaper destructor function?

**Comment by icculus** [comment]
NULL check was added in 00394996eb7e48e2f23a7aff15418813951044f0.

This bug is correct, we _don't_ seem to free shaper stuff. We should fix that in SDL2, and decide if we even _want_ the shaped window API in SDL3.
