### ISSUE TITLE
Any Blitting from a 16-Color Palette Always Fails

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2140]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2016-04-11 08:07:32 +0000, LRFLEW wrote:

> I ran into a problem trying to use an image stored using a 16-Color (4-bit) palette as a texture. No matter what I did, the resulting texture was empty. This issue continued even if I first used SDL_ConvertSurface or even SDL_BlitSurface. I ended up stepping through the code to find the problem. In SDL_CalculateBlit, it will first try to use SDL_CalculateBlit0 to get a blit function for the surface, but since the first thing that function does is return NULL if it isn't a 2-Color (1-bit) palette. The rest of SDL_CalculateBlit will attempt to find a relevant function, but can only search RGB-based format conversions. The blit fails with the error "Blit combination not supported".
> 
> Since the format is a core format in the library, it would make sense to me to implement it. If, however, there are no plans to implement it, then this issue should at least cover the fact that both SDL_ConvertSurface and SDL_CreateTextureFromSurface don't provide any indication when the blit fails. They both return non-null empty images when the blit fails, instead of the error-indicating NULL value.

**Comment by 1bsyl** [comment]
Fixed, + add some test-case
[main_bug_2140_palette_16color.c.txt](https://github.com/libsdl-org/SDL/files/8041032/main_bug_2140_palette_16color.c.txt)

**Comment by 1bsyl** [comment]
I don't know ..
(real SDL 1.2 or the SDL_Compat 1.2 / 2 layer ? )

**Comment by sezero** [comment]
The real one. Anyways, forget it, possibly not worth the trouble.
