### ISSUE TITLE
SDL Render functions crash when using window menus

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2148]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Complete test case source file, including build instructions. (test.cpp, text/x-csrc, 2016-05-02 22:49:56 +0000, 2339 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2437)

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2016-05-02 22:49:56 +0000, Angus Holder wrote:

> Created attachment 2437
> Complete test case source file, including build instructions.
> 
> I have been using the Windows API to add a window menu to the top bar, but when I try using the SDL Render API instead of raw OpenGL, I get a null pointer dereference crash at the first render function that's reached (both SDL_RenderClear and SDL_SetRenderDrawColor will crash). The only Windows specific event I capture is WM_CREATE, where I append a menu to the Window. I'm compiling with the compiler of Visual Studio 2015. Attached is a minimal repro of my issue. The crash doesn't happen if I don't attach a menu to my window, or, strangely, if I don't create a texture.

On 2016-05-03 15:20:03 +0000, Angus Holder wrote:

> I have found that the issue is specific to the Direct3D renderer, so am currently working around it with
> SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl");
> I'm using an Intel HD4400 GPU, with driver version 10.18.10.3345, forgot to add that in the original post.

**Comment by icculus** [comment]
This was the test case from Bugzilla. I haven't tested this yet.

```c
/* Compile with:

    @echo off
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
    cl -Od -nologo -Zi test.cpp -Ipath_to_sdl_headers

*/

#include <SDL2/SDL.h>
#include <SDL2/SDL_syswm.h>

#pragma comment(lib, "User32.lib")
#pragma comment(lib, "../lib/SDL2.lib")
#pragma comment(lib, "../lib/SDL2main.lib")

enum {
    IDC_Debug_Debugger = 9001,
};

int main(int argc, char *argv[]) {
    if (SDL_Init(SDL_INIT_VIDEO) < 0)
        SDL_assert(!"Failed init.");

    SDL_EventState(SDL_SYSWMEVENT, SDL_ENABLE);
    SDL_Window *window = SDL_CreateWindow(
        "Test",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        512, 480,
        0);
    if (!window)
        SDL_assert(!"Failed to create window.");

    SDL_Renderer *renderer = SDL_CreateRenderer(
        window, -1, 0);//SDL_RENDERER_PRESENTVSYNC);
    if (!renderer)
        SDL_assert(!"Failed to create renderer.");

    SDL_Texture *tex = SDL_CreateTexture(
        renderer, SDL_PIXELFORMAT_ABGR8888, SDL_TEXTUREACCESS_STREAMING,
        256, 240);
    if (!tex)
        SDL_assert(!"Failed to create texture.");

    bool running = true;

    while (running) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            switch (e.type) {
                case SDL_QUIT: {
                    running = false;
                } break;

                case SDL_SYSWMEVENT: {
                    HWND Window   = e.syswm.msg->msg.win.hwnd;
                    UINT Msg      = e.syswm.msg->msg.win.msg;

                    if (Msg == WM_CREATE) {
                        HMENU Menu = CreateMenu();

                        HMENU SubMenu = CreatePopupMenu();
                        AppendMenu(SubMenu, MF_STRING, IDC_Debug_Debugger, "&Debugger");
                        AppendMenu(Menu, MF_STRING | MF_POPUP, (UINT_PTR)SubMenu, "&Debug");

                        SetMenu(Window, Menu);
                    }
                } break;
            }
        }

        if (SDL_SetRenderDrawColor(renderer, 255, 0, 255, 255) < 0)
            SDL_assert(!"Failed to set color.");

        if (SDL_RenderClear(renderer) < 0)
            SDL_assert(!"Failed to clear screen.");

        SDL_RenderPresent(renderer);
    }

    return 0;
}
```

**Comment by slouken** [comment]
This appears to have been a driver bug that has since been fixed. This test is working fine for me on Windows 11 with an NVIDIA card.
