### ISSUE TITLE
Switching from fullscreen to desktop fullscreen broken

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2189]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Render output after switching from initial fullscreen to deskto fullscreen mode (render-issue-after-switch-to-fullscreen-desktop.png, image/png, 2016-06-09 18:40:11 +0000, 20299 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2486)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-06-09 18:40:11 +0000, Kai Sterker wrote:

> Created attachment 2486
> Render output after switching from initial fullscreen to deskto fullscreen mode
> 
> I am using SDL2 from hg (changeset 10179 7cbfd97f1430) and experience issues when switching from fullscreen mode to fullscreen desktop mode. To reproduce the problem, run
> 
> ./testdraw2 --fullscreen
> press Shift+Enter to switch to desktop fullscreen mode.
> 
> Expected behavior: correct rendering at desktop resolution
> Actual behavior: rendering at correct resolution, but only the (possibly 640x480 sized) top left part of the screen shows something, the remainder is black (see attached screenshot).
> 
> 
> This happens on both Ubuntu 14.04 and 16.04, using standard Unity desktop and the nvidia binary driver.
> 
> 14.04
> nvidia 352.63
> Linux Britannia 3.19.0-59-generic # 66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> X.Org X Server 1.15.1
> 
> 16.04
> nvidia 361.42
> Linux Trinsic 4.4.0-22-generic # 40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> X.Org X Server 1.18.3
> 
> 
> For what it's worth, it is possible to get it to render correctly, by executing the following sequence:
> ./testdraw2 --fullscreen
> Shift+Enter (now it's fullscreen desktop, but broken)
> Alt+Enter (now it's in window mode, correctly)
> Shift+Enter (now it's fullscreen desktop, correctly)
> And from now on, repeated Shift+Enter correctly toggles fullscreen and fullscreen desktop
> 
> 
> Since the behavior can easily reproduced with SDLs own test program, there's probably no need to point to my own application that suffers the issue, but for completeness sake:
> http://cvs.savannah.gnu.org/viewvc/adonthell-0.3/?root=adonthell
> http://cvs.savannah.gnu.org/viewvc/wastesedge/?root=adonthell
> First module contains the engine, second the data.

On 2017-08-12 02:16:40 +0000, Sam Lantinga wrote:

> Ryan, can you look at this for 2.0.6?

**Comment by icculus** [comment]
This got fixed at some point, it works here.
