### ISSUE TITLE
Mouse focus is 0 if exiting fullscreen overlaps mouse button event while in relative mouse mode.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2215]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Demo for mouse focus loss. (SDLRelativeMouseFocusTest.cpp, text/x-c++src, 2016-07-07 14:08:09 +0000, 1269 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2527)

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-07-07 14:08:09 +0000, Jason Wyatt wrote:

> Created attachment 2527
> Demo for mouse focus loss.
> 
> While in SDL_WINDOW_FULLSCREEN_DESKTOP mode, with relative mouse mode enabled. If a mouse button down event triggers switching to windowed mode, the following sequence of events causes the current mouse focus to be NULL.
> 
>  - Mouse button down event, at a point outside where the window will be.
> 
>  - Leave fullscreen, causing resize.
> 
>  - (LeaveNotify and EnterNotify cause mouse focus to be lost and gained again, however relative mouse mode prevents this being used to update coordinates).
> 
>  - Mouse button up event. Coordinates have not been updated, so this calls SDL_UpdateMouseFocus with coordinates outside the window, resulting in the mouse focus being set to NULL.
> 
> Mouse focus won't be reset until the next EnterNotify event or similar (e.g. alt-tabbing out then in again).
> 
> (Again, relative mouse mode prevents the focus being updated in SDL_SendMouseMotion)
> 
> Seen in Fedora 23, under Gnome.
> 
> Demo attached - move the cursor to some large coordinates and click (being careful not to move the mouse during the click, as this may cause the mouse position to be updated.)
> The mouse motion events will report a window id of 0, despite the window still having the mouse grab. Also alt-tabbing to other programs may be broken, because SDL won't properly release the mouse.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
