### ISSUE TITLE
Cannot find EGL header when using MinGW

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2220]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2016-07-13 19:31:20 +0000,  wrote:

> Using GCC 6.1 on Windows (MinGW), I get the following error building SDL:
> 
> [  5%] Building C object vendor/SDL/CMakeFiles/SDL2.dir/src/render/direct3d/SDL_render_d3d.c.obj
> In file included from <...>\vendor\sdl\src\video\sdl_egl_c.h:28:0,
>                  from <...>\vendor\sdl\src\video\windows\SDL_windowsopengles.h:29,
>                  from <...>\vendor\sdl\src\video\windows\sdl_windowsvideo.h:47,
>                  from <...>\vendor\SDL\src\render\direct3d\SDL_render_d3d.c:35:
> <...>/vendor/SDL/include/SDL_egl.h:29:21: fatal error: EGL/egl.h: No such file or directory
>  #include <EGL/egl.h>
>                      ^
> compilation terminated.
> 
> It looks like Windows doesn't have EGL headers. I also tried using the one written for visual studio in SDL_egl.h, but it fails with a large number of errors.

On 2016-07-13 20:21:01 +0000,  wrote:

> I believe I got it to build by turning the following off:
> DIRECTX
> RENDER_D3D
> VIDEO_OPENGLES
> 
> Not optimal, but at least it builds

On 2016-07-17 20:24:11 +0000, Philipp Wiesemann wrote:

> There was a maybe related post on the forum some time ago (but no fix): http://forums.libsdl.org/viewtopic.php?t=11642

**Comment by icculus** [comment]
This obviously got fixed at some point.
