### ISSUE TITLE
SDL_GetDisplayDPI returns a wrong value on Linux and FreeBSD (X11)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2226]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [X11: a sample code that works and returns the correct DPI (x11-get-dpi.cpp, text/x-c++src, 2016-08-01 10:24:20 +0000, 950 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2535)

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-08-01 09:05:02 +0000, Lena wrote:

> On my system with Linux 4.6.4 and X11 1.18.4 the function SDL_GetDisplayDPI returns a wrong value. The same happens on FreeBSD 10.2 too.
> 
> My physical DPI is 96, while the functions always gives me 129.280685 average. Can I even trust this function on X11 to calculate a proper content scale factor?

On 2016-08-01 10:24:20 +0000, Lena wrote:

> Created attachment 2535
> X11: a sample code that works and returns the correct DPI

On 2016-08-01 20:28:25 +0000, Philipp Wiesemann wrote:

> Does the program from "test/testdisplayinfo.c" also report a wrong value?
> 
> And is XRandR support activated on the two systems and also compiled into SDL?
> 
> There are two implementations to get the DPI in SDL (both in "src/video/x11/SDL_x11modes.c"). The older looks similar to the attached sample. It is used if no XRandR support is available.

On 2016-08-02 06:43:15 +0000, Lena wrote:

> The test program has the same values as my code had.
> 
> INFO:     DPI: ddpi=128.876648; hdpi=128.336838; vdpi=130.628571
> 
> This are the X11 libraries my SDL2 build is using: xcursor xdbe xinerama xinput2 xinput2_multitouch xrandr xscrnsaver xshape xvidmode
> 
> 
> Maybe a compute issue in the XRandR code?

**Comment by icculus** [comment]
This got fixed to use XRandR's actually reported values per-display in https://github.com/libsdl-org/SDL/commit/ec0204d2438829b18d5942b93713dfd00682121c
