### ISSUE TITLE
VS vcxproj does not contain MT or static library variants

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2231]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 10, All

# Comments on the original bug report:

On 2016-08-14 20:28:16 +0000, Ted wrote:

> The Visual Studio project (SDL.vcxproj) should be updated to contain MultiThreaded (/MT) and Static Library configurations. This applies for both x86 / Win32 and x64.
> 
> Currently we have to patch the vcxproj file to build a MultiThreaded Static Library of SDL2.

On 2016-08-14 20:29:25 +0000, Ted wrote:

> I should also add that the /MT configurations should define HAVE_LIBC.

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/pull/7257 should address this

**Comment by madebr** [comment]
@slouken 
Is the current lack of building a static SDL library the reason the SDL-VC-devel archives don't contain a static SDL library?

**Comment by slouken** [comment]
No, this is intentional, to allow customers to upgrade SDL in products that are no longer in development.
