### ISSUE TITLE
SDL enters infinite loop in X11_SetWindowGrab

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2233]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Demo for hang. (SDLGrabHangTest.cpp, text/x-c++src, 2016-08-17 10:52:12 +0000, 783 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2549)

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-08-17 10:52:12 +0000, Jason Wyatt wrote:

> Created attachment 2549
> Demo for hang.
> 
> If relative mouse mode is on, and SDL_ShowWindow is followed by SDL_HideWindow without a call to SDL_PumpEvents in between, the SDL enters an infinite loop.
> This is because SDL will call X11_SetWindowGrab in response to the focus in event that resulted from SDL_ShowWindow. X11_SetWindowGrab will call XGrabPointer until it returns GrabSuccess. However the window is now hidden, so XGrabPointer will always return GrabNotViewable.

On 2016-08-17 11:26:55 +0000, Jason Wyatt wrote:

> Actually, calling SDL_PumpEvents after SDL_HideWindow() always seems to cause this hang, because SDL_HideWindow() causes the following series of events:
> 
> UnmapNotify event, serial 27, synthetic NO, window 0x2400005,
>     event 0x2400005, window 0x2400005, from_configure NO
> 
> FocusOut event, serial 27, synthetic NO, window 0x2400005,
>     mode NotifyNormal, detail NotifyNonlinear
> 
> FocusIn event, serial 27, synthetic NO, window 0x2400005,
>     mode NotifyNormal, detail NotifyPointer

On 2016-08-17 15:06:04 +0000, Jason Wyatt wrote:

> With relative mouse mode disabled:
> 
> SDL_HideWindow(window)
> SDL_PumpEvents()
> SDL_SetRelativeMouseMode(SDL_TRUE)
> 
> will also cause the hang, because the focus is still set to the hidden window.

On 2017-07-21 09:58:56 +0000, Jason Wyatt wrote:

> https://hg.libsdl.org/SDL/rev/79be3e82dcf1 prevents the infinite loops. However it makes it impossible to grab the cursor again if the grab fails.
> 
> https://hg.libsdl.org/SDL/rev/7cfe088fafba somewhat reduces the chances of coming across this issue, since the hidden state of a window is now properly reflected. However it still seems to be possible to cause the grab to fail (I haven't narrowed this down beyond rapid window interaction while SDL tries to set the mouse grab).

On 2017-08-25 15:07:15 +0000, Ryan C. Gordon wrote:

> 
> I think we should punt on this for 2.0.6.

**Comment by icculus** [comment]
This appears to be working correctly in modern times.
