### ISSUE TITLE
Wrong SDL_Keycode for X11 Workman layout

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2240]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-08-28 06:37:52 +0000, Braden Obrzut wrote:

> Tested with Hg changeset 9a277db2806d on Kubuntu 16.04 x86_64 (also affects version of SDL2 shipped with the distro).
> 
> I have my keyboard layout set to US-Workman in KDE and SDL handles this mostly fine except for the number keys.  Those get translated as follows:
> 
> 1 = Return
> 2 = Escape
> 3 = Backspace
> 4 = Tab
> 5 = Space
> 6 = -
> 7 = =
> 8 = [
> 9 = ]
> 
> The beginning sequence there looks a lot like the scancodes in the switch statement on line 335 of SDL_x11keyboard.c, so I commented that switch block out.  With the modified SDL library the keyboard input works as expected with the keycode matching my layout and scancode matching qwerty.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
