### ISSUE TITLE
Duplicate SDL_KEYDOWN events for Left Alt and combinations

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2252]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-09-20 10:31:37 +0000, Alex Smith wrote:

> If the Left Alt key is pressed, or a combination of that and another key is pressed, this will send two SDL_KEYDOWN events.
> 
> From what I can tell this is because for some reason X is sending two FocusOut events and a FocusIn event prior to the KeyPress event whenever Left Alt or a combination with it are pressed. On the FocusIn event X11_ReconcileKeyboardState is called, which will call SDL_SendKeyboardKey(SDL_PRESSED, ...) because it will see that the key is pressed. Then SDL_SendKeyboardKey will be called again on the KeyPress, which is treated as a repeat so another SDL_KEYDOWN is sent.
> 
> This is happening on Ubuntu 16.04 under Unity, with both SDL 2.0.4 and current HG.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
