### ISSUE TITLE
Multi-controller USB adapters reports controllers wrongly on Mac OS X

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2269]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Mac OS X (All), x86

# Comments on the original bug report:

On 2016-10-11 18:38:45 +0000, Rodrigo Cardoso wrote:

> I tested 3 different devices:
> 
>  * EMS Trio Linker Plus II - 1 GameCube port + 1 Dreamcast port + 1 PlayStation port
>  * Dual SNES Adapter - 2x Super NES ports
>  * Mayflash GameCube Controller Adapter (PC mode) - 4x GameCube ports
> 
> (I think all of them are made by Mayflash)
> 
> ------------
> The problem:
> 
> Any of the listed devices show a multiple controllers correctly on Windows but a single monolithic Controller on Mac.
> 
> On Windows it shows everything correctly and separated.
> On Mac everything works but as if there is a single device with 40+ buttons, 10+ axes, 4+ hats.
> 
> with the exception of EMS Trio Linker Plus II, it reports more than one device on Windows no matter the number of connected controllers (including no one).
> 
> Similar issue, maybe: https://bugs.dolphin-emu.org/issues/8187
> 
> -------------
> Pictures:
> 
> With a simple SDL program that lists all connected controllers you can find the problem.
> For this bug report I will post pictures that illustrate the problem.
> 
> The mac pics are from my app Joystick Show, which uses SDL2.
> The windows pics are from the control panel, which doesnt use SDL, of course, but shows the controllers the same way.
> 
> GameCube 4 port Adapter:
> > Mac:
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/mac/GC%20Adapter%20-%20any%20number%20of%20controllers.png
> > Windows:
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/windows/gc%20adapter.png
> 
> SNES 2 port Adapter:
> > Mac:
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/mac/Snes%20Adapter%20-%20any%20number%20of%20controllers.png
> > Windows:
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/windows/snes%20adapter.png
> 
> EMS Trio Linker Plus II:
> > Mac:
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/mac/Trio%20Linker%20II%20-%20One%20controller.png
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/mac/Trio%20Linker%20II%20-%20Two%20controllers.png
> > Windows:
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/windows/trio%20linker%20no%20controller.png
> https://dl.dropboxusercontent.com/u/14890209/dev/sdl%20mayflash/windows/trio%20linker%202%20controllers.png

On 2017-08-30 04:35:11 +0000, Rodrigo Cardoso wrote:

> Updating the image links since Dropbox will remove the public links this week:
> 
> GameCube 4 port Adapter:
> > Mac:
> https://www.dropbox.com/s/l4vjm14wirr2aqk/GC%20Adapter%20-%20any%20number%20of%20controllers.png?dl=0
> > Windows:
> https://www.dropbox.com/s/zugvftuo6y0j4b6/gc%20adapter.png?dl=0
> 
> SNES 2 port Adapter:
> > Mac:
> https://www.dropbox.com/s/4wnzokmdtfm16ht/Snes%20Adapter%20-%20any%20number%20of%20controllers.png?dl=0
> > Windows:
> https://www.dropbox.com/s/1ma4al9qm7uil8q/snes%20adapter.png?dl=0
> 
> EMS Trio Linker Plus II:
> > Mac:
> 1- https://www.dropbox.com/s/eqk4mdjj958xt03/Trio%20Linker%20II%20-%20One%20controller.png?dl=0
> 2- https://www.dropbox.com/s/ajym2f804ogt7bp/Trio%20Linker%20II%20-%20Two%20controllers.png?dl=0
> > Windows:
> 1- https://www.dropbox.com/s/h7acm3b5ffez7xd/trio%20linker%202%20controllers.png?dl=0
> 2- https://www.dropbox.com/s/0snm9h0ogwc9uo8/trio%20linker%20no%20controller.png?dl=0

**Comment by slouken** [comment]
This requires custom driver work to enable on Linux and macOS. This has been done for the MayFlash GameCube adapter in [SDL_hidapi_gamecube.c](https://github.com/libsdl-org/SDL/blob/main/src/joystick/hidapi/SDL_hidapi_gamecube.c), but the others would probably need to be implemented.

I'm going to go ahead and close this for now, and feel free to reopen it if you have a PR you'd like reviewed.
