### ISSUE TITLE
Setting window opacity while window is partially offscreen doesn't work

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2282]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2016-10-20 22:51:20 +0000,  wrote:

> When the opacity of a window is decreased from 1 to anything lower than 1 while the window is partially offscreen, the window turns invisible rather than changing to the correct opacity.
> 
> I'm using version 2.0.5 of SDL.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
