### ISSUE TITLE
iOS. OpenGLES2. Something weird with window size after power button off -> on

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2284]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Other, iPhone/iPod touch

# Comments on the original bug report:

On 2016-10-22 13:26:06 +0000, dmuratshin wrote:

> After updating to iOS 10 "SDL_GL_GetDrawableSize" returns wrong size when you switch display Off and then On
> for example on my iPhone 5 in Landscape mode it returns (144, 1632) and (640, 1136)
> instead off (1136, 640).
> 
> iOS 7/8/9 works fine as expected and always returns (1136, 640)

On 2016-10-22 13:46:56 +0000, dmuratshin wrote:

> more info
> flags:
>             int flags = SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN;
>             flags |= SDL_WINDOW_BORDERLESS;
>             flags |= SDL_WINDOW_ALLOW_HIGHDPI;
>             flags |= SDL_WINDOW_FULLSCREEN;
> 
> main loop via:
>     SDL_iPhoneSetAnimationCallback

On 2016-10-22 14:05:52 +0000, dmuratshin wrote:

> ok, after some investigation I've found key
> bug reproducible only if you use SDL_iPhoneSetAnimationCallback instead of common main loop

On 2016-10-22 14:34:36 +0000, Alex Szpakowski wrote:

> Can you provide a minimal test case that reproduces the issue?

On 2016-10-22 22:11:23 +0000, dmuratshin wrote:

> https://github.com/oxygine/SDL2/commit/e22853e5ce3ebe35ed13b23b1cd2d06814933fdf
> minimum changes.
> I've found that it happens only in pair with SDL_WINDOW_FULLSCREEN flag

On 2016-10-26 21:23:24 +0000, dmuratshin wrote:

> Do you need any assist? Or maybe you expect directly attached files?

On 2017-04-26 15:46:46 +0000, dmuratshin wrote:

> how to reproduce video:
> https://goo.gl/photos/iCCdsQJa7FWXuZyP7

On 2017-08-11 20:13:36 +0000, Sam Lantinga wrote:

> Alex, can you look at this for the 2.0.6 release?

On 2017-08-12 13:02:02 +0000, dmuratshin wrote:

> update:
> it is not ios 10 only. Could be reproduced with 8/9 too.
> happens with SDL_iPhoneSetAnimationCallback.
> 
> how to repro (see video above):
> 
> 0. launch landscape app
> 1. open/close any native UI in game (keyboard, facebook login etc)
> 2. rotate display to portrait mode
> 3. turn display off
> 4. turn on
> 5. try to open any native UI
> result -> broken background size

On 2017-08-19 02:25:42 +0000, Alex Szpakowski wrote:

> I believe I've fixed it / worked around the problem with https://hg.libsdl.org/SDL/rev/770196e01af1 , can you confirm?

On 2017-08-29 14:28:03 +0000, dmuratshin wrote:

> Still not fixed
> proof:
> https://goo.gl/photos/RffZqHBG3LKCVNXS7
> 
> please note
> 1. SDL_iPhoneSetAnimationCallback should be used
> 2. FULLSCREEN BORDERLESS mode
> 3. UIKit_ComputeViewFrame called only on start
> 4. native UI should be opened before bug occures

On 2017-08-29 14:31:16 +0000, dmuratshin wrote:

> 5. iphone (not ipad)

On 2017-08-29 15:14:02 +0000, Alex Szpakowski wrote:

> Is it still reproducible when using SDL's native virtual keyboard rather than a third party / other native UI? If not, the problem may not be fixable on SDL's end as it's likely a bug in iOS or the third party UI.

On 2017-09-20 15:03:23 +0000, Alex Szpakowski wrote:

> iOS 11 may have fixed the underlying issue, as well.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
