### ISSUE TITLE
SDL_RenderCopyEx rotation center not well-defined (please support float)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2308]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [A simple test to determine how the rotation center is interpreted (sdl-rotate-center-test.cpp, text/x-c++src, 2016-11-15 21:26:29 +0000, 2654 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2631)
* [Rendering of the test on my system (sdl-rotate-center-test.png, image/png, 2016-11-15 21:27:38 +0000, 8802 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2632)

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2016-11-15 21:26:29 +0000,  wrote:

> Created attachment 2631
> A simple test to determine how the rotation center is interpreted
> 
> I find the rotation center very ambiguous, because it only accepts integer coordinates. But what do they mean? top left corner of a pixel cell, or the center of a pixel cell?
> 
> The latter makes more sense when talking about integer coordinates, but the top left corners makes more sense in a float context.
> 
> Therefore it seems to me, that the backend used by SDL actually allows float coordinates, but SDL artificially restricts this to integer.
> 
> This leads to unexpected behavior. E.g. rotating a 1x1 texture around itself (rotation center = NULL, i.e. same as texture coordinates) and rendering that 1px texture with 0,90,180,270 degrees rotation will lead to 4 pixels being drawn, because the pixel is not rotated around it's center, but it's top left corner.
> 
> See attachment for a simple test.
> 
> The tests only behave as expected for textures with even width and height.

On 2016-11-15 21:27:38 +0000,  wrote:

> Created attachment 2632
> Rendering of the test on my system

**Comment by 1bsyl** [comment]
I re-tested and this has been fixed between 2.0.9 and 2.0.10 with floating coordinates.
( https://github.com/libsdl-org/SDL/blob/main/src/render/SDL_render.c#L3647 )
now all 4 pixels are draw at the same position.

And for the software renderer, this is fixed with removing integer casting: [e366ad1](https://github.com/libsdl-org/SDL/commit/e366ad128831fbc14646d3a606709ab52e142c46)
