### ISSUE TITLE
Window size bug + window title disappears + sometimes the whole window disappears

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2314]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [C++ code reproducing the issue (main.cpp, text/x-csrc, 2016-11-26 23:31:47 +0000, 971 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2640)

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Mac OS X 10.11, x86_64

# Comments on the original bug report:

On 2016-11-26 23:31:47 +0000, emlai wrote:

> Created attachment 2640
> C++ code reproducing the issue
> 
> When I create a non-fullscreen 800x600 window, SDL_GetWindowSize return 800x600. So far so good.
> 
> When I create a fullscreen (SDL_WINDOW_FULLSCREEN_DESKTOP) 800x600 window and SDL_SetWindowFullscreen it back to windowed mode, SDL_GetWindowSize return 800x578. (The missing 22 pixels is the height of the window title bar.) Additionally, sometimes the window disappears completely at this point, with no way of bringing it back.
> 
> This messes up our app because its not able to draw 600 pixels vertically. (The disappearing window is not so nice either.)
> 
> I'm using macOS 10.12 (which is by the way missing in the bug report OS dropdown menu), but I remember seeing this behavior in earlier macOS versions too.

On 2016-11-27 14:20:07 +0000, emlai wrote:

> Also, the window title disappears when starting the window in fullscreen and then making it windowed.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
