### ISSUE TITLE
Multiple Joysticks Change order every time application (or the joystick subsystem) starts.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2317]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Mac OS X 10.11, x86

# Comments on the original bug report:

On 2016-12-01 20:48:15 +0000, Rodrigo Cardoso wrote:

> The Problem:
> - Connect 2 or more gamepads/joysticks;
> - In a SDL app, open all joysticks;
> - without connecting or disconnecting anything, restart the app;
> - most of the time the order of the devices changed.
> 
> Why this happens?
> Is that a by-product of the way the backend works?
> Is it possible to make sure the order is always the same? (assuming you didnt touch any device, or change ports)

On 2016-12-01 20:57:30 +0000, Rodrigo Cardoso wrote:

> Forgot to mention that, this reordering is very bad because games with custom mappings will switch controllers and make the mappings useless in most cases.

**Comment by icculus** [comment]
We don't guarantee device order between runs. Closing.
