### ISSUE TITLE
SDL_GL_SwapWindow does not return error status

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2326]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2016-12-09 06:21:33 +0000, Intellectual Kitty wrote:

> SDL_GL_SwapWindow may have errors but does not return error status.  Based on a survey of the code, it is possible to work around this by (1) checking the window's flags to see if it supports OpenGL and (2) checking that the window is current; this is actually what SDL_GL_SwapWindow does internally.  However, this isn't consistent with the SDL standard of returning 0 on success and -1 on failure, and it makes error checking a little more difficult.

On 2016-12-09 09:48:09 +0000, Sam Lantinga wrote:

> Fixed, thanks!
> https://hg.libsdl.org/SDL/rev/23a825f341e6

On 2016-12-11 20:09:52 +0000, Sam Lantinga wrote:

> Actually, this changes the ABI, so I'm backing out this change for now.

On 2016-12-11 20:11:39 +0000, Sam Lantinga wrote:

> *** Bug 2936 has been marked as a duplicate of this bug. ***

**Comment by 1bsyl** [comment]
closing since the PR was merged
