### ISSUE TITLE
GL with SDL_SetWindowFullscreen wierd behavior

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2338]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [described in the comment (sdlbug.rar, application/x-rar, 2016-12-17 23:31:35 +0000, 130273 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2650)

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2016-12-17 23:31:35 +0000, Marco wrote:

> Created attachment 2650
> described in the comment
> 
> First I create a window with only (SDL_WINDOW_SHOWN | SDL_WINDOW_OPENGL) and create the GL context. After that i issue a few OpenGL commands (glViewport, glClearColor, ...) and enter the render loop. Inside the loop I first check for the F key press which toggles the fullscreen mode then continues to render the triangle and swap the buffers.
> 
> Then i hit F once to enter fullscreen mode and heres the problem now: when i hit F again to leave fullscreen mode the OpenGL viewport will be displaced to the top left corner as if there was no title bar nor border. I will attach the same exact code I'm running with a Screenshot showing the window at startup and the window after the fullscreen toggling. I'm using Visual Studio 2015 Community.

On 2019-06-21 19:45:44 +0000, Jon Daniel wrote:

> Try the workaround at https://bugzilla.libsdl.org/show_bug.cgi?id=3524#c1 it seems to be a similar problem.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
