### ISSUE TITLE
Information about the cause of SDL_QUIT event requested

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2348]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2016-12-30 04:30:17 +0000, Intellectual Kitty wrote:

> An SDL_QUIT event can be generated for a number of reasons.  However, this information is not passed along with the event, which makes it difficult for the application to decide whether or not the quit event should be acted on.  For instance, a text editing application should continue to run even when the last window is closed, but it's currently not possible to determine this kind of quit event from one generated for another reason (e.g., Command-Q on macOS, an interrupt signal, etc.).

On 2017-08-11 20:06:36 +0000, Sam Lantinga wrote:

> This is a good idea for SDL 2.1, thanks!

**Comment by Ben2917** [comment]
Is there a way to start making contributions to SDL 3.0? I've added this functionality to my fork of SDL2 and I was hoping to contribute this enhancement if possible.

Thanks!

**Comment by slouken** [comment]
Not yet, we plan to start the 3.0 branch next month.

**Comment by Ben2917** [comment]
> Not yet, we plan to start the 3.0 branch next month.

Thanks for letting me know. I'll keep an eye out for that

**Comment by icculus** [comment]
If you have a working patch, though, don't be afraid to submit a pull request for it now; we will be able to merge it to the SDL 3 branch when we start.

**Comment by slouken** [comment]
This also seems like something that could go into SDL2, without an ABI change.

**Comment by slouken** [comment]
I think a better way to resolve this issue is to set the hint SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4 to "1" and then handle the QUIT event by quitting and handle the window close event however makes sense for your application.
