### ISSUE TITLE
Hint to disable SDL_QUIT on last window closed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2349]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2016-12-30 04:32:38 +0000, Intellectual Kitty wrote:

> For most applications, generating an SDL_QUIT event on the last window closing is correct.  However, for something like a text editing application, this behavior is not desirable.  So, a hint disabling this behavior would be helpful.

On 2017-08-11 20:05:47 +0000, Sam Lantinga wrote:

> Good idea, thanks!

**Comment by icculus** [comment]
Note for SDL3 (#3519): let's add a field to SDL_QuitEvent that says _why_ the event was generated (last window closed, SIGINT, Command-Q on macOS, etc).

For SDL2, the hint is totally reasonable.
