### ISSUE TITLE
Window title disappears after setting fullscreen then fullscreen desktop

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2352]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** macOS 10.12, x86

# Comments on the original bug report:

On 2016-12-30 23:13:10 +0000, Intellectual Kitty wrote:

> When a window, beginning in standard windowed mode, is first set to fullscreen [by calling SDL_SetWindowFullscreen(m_pkWindow,SDL_WINDOW_FULLSCREEN)] and then to fullscreen desktop [by calling SDL_SetWindowFullscreen(m_pkWindow,SDL_WINDOW_FULLSCREEN_DESKTOP)], the title disappears when it changes back to windowed mode [by calling SDL_SetWindowFullscreen(m_pkWindow,0)].  If I then use another sequence, such as changing to either fullscreen or fullscreen desktop and then back to windowed mode, the title reappears.
> 
> I've tried every possible combination, and the title only disappears when the window is (1) first set to fullscreen, (2) then fullscreen desktop, and (3) then back to standard windowed mode.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
