### ISSUE TITLE
The key you just pressed is not recognized by SDL

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2370]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-01-13 06:12:31 +0000, Alain Dupuis wrote:

> I was play testing my game and got the following message twice within a couple minutes.
> 
> "The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL mailing list <sdl@libsdl.org> X11 KeyCode 130 (122), X11 KeySym 0xFF31 (Hangul)."
> 
> The messages appeared as I was using the arrow keys. Any combination of the arrow keys may have been pressed at the same time. Keyboard is alogitech bluetooth.
> 
> This bug is similar to bug 3277 which is same bug but with a different keycode.
> 
> 
> This is as changeset: 10807:3d7cae208a0c

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
