### ISSUE TITLE
Fullscreen display cropped to desktop resolution

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2388]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-01-31 22:12:17 +0000, Yann Dirson wrote:

> Eg. to reproduce:
> 
> * setup a SDL2 game like nexuiz to use your best fullscreen resolution, and close it
> * use xrandr to switch to a smaller resolution
> * launch nexuiz again: you get your requested resolution, but the display is cropped at the smaller resolution, making the whole just unusable
> 
> (SDL1.2 apps like Battle for Wesnoth, OTOH, crash with an XF86VidModeSwitchToMode exception)
> 
> What happens is that SDL does not touch the Xrandr Screen Size.  While this is probably useful to avoid the desktop manager to shuffle icons, it has a bit downside for users willing eg. to use 4K only for gaming and not on the desktop.

On 2017-08-11 19:52:33 +0000, Sam Lantinga wrote:

> True fullscreen (not fullscreen desktop) games should be setting the mode as the come into focus. Ryan, are we capping this to the desktop resolution on Linux?

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
