### ISSUE TITLE
SDL_main seems not working and not-using on MinGW (non-w64).

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2391]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows (All), x86

# Comments on the original bug report:

On 2017-02-02 09:06:18 +0000, Vitaly Novichkov wrote:

> Because SDL_main doesn't works on MinGW (MinGW itself uses generic main or ANSI-based WinMain).
> 
> Myself I implemented the thing which will 100% give UTF8 into the main() function:
> https://github.com/WohlSoft/PGE-Project/tree/master/_common/Utf8Main
> 
> I just ignoring all arguments of WinMain, and taking command line by GetCommandLineW(), then splitting it into separated arguments by CommandLineToArgvW call and then converting each argument into UTF-8 to store into separated array which will be sent into regular main function.
> 
> Also, my reply is: if you have no UNICODE macro, just don't use WinMain's arguments and get them by GetCommandLineW() call, split and convert into UTF8.

**Comment by Wohlstand** [comment]
It's my issue I reported a while ago. The true solution to why it doesn't work is the missing the necessary to properly link the -lmingw32 library.

So, the next link order to get it properly work:
```
-lmingw32 -lSDL2main -lSDL2
```
@slouken, @sezero This issue can be closed, it's no longer actual.

**Comment by sezero** [comment]
OK, closing.
