### ISSUE TITLE
Restored minimized maximized window missing SDL_WINDOW_MAXIMIZED flag

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2403]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-02-27 14:36:25 +0000, Rainer Deyke wrote:

> Simple problem, easy to reproduce:
>   - Take a resizable SDL window.
>   - Maximize it by pressing the maximize button on the window border.
>   - Minimize it by pressing the minimize button on the window border.
>   - Restore it to maximized clicking on it on the task bar.
>   - The window is now maximized, but is missing the SDL_WINDOW_MAXIMIZED flag.
> 
> I'm actually receiving three relevant events when the window is restored:
>   - SDL_WINDOWEVENT_RESTORED
>   - SDL_WINDOWEVENT_MAXIMIZED
>   - SDL_WINDOWEVENT_RESTORED again
> 
> Tested under x86_64 Lubuntu 16.04 LTS, LXDE desktop environment, Openbox window manager.  Problem persists in the the latest HG.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
