### ISSUE TITLE
SDL 2.04 fails to render when Nvidia's "fast" vsync setting is enabled

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2425]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2017-03-26 23:29:38 +0000,  wrote:

> mingwx64 6.3 or 5.1
> win7 x64
> 8gb ram
> core2duo e8500
> nvidia gtx 750
> latest mainstream drivers as of 23/3/2017
> 
> Using "fast" vsync setting in nvidia graphics driver settings means SDL2 displays nothing onscreen. Other aspects (sound etc) continue.
> 
> Since I can't get 2.05 to run on my system (see timer bug) I cannot evaluate whether this bug is still present in it.

On 2017-03-27 05:41:24 +0000, Ryan C. Gordon wrote:

> 
> It's possible we fixed this, so we'll sort out the timer bug first and revisit this, but: are you rendering with OpenGL, Direct3D? The SDL render API or direct OpenGL calls, etc?
> 
> --ryan.

On 2017-03-27 07:03:16 +0000,  wrote:

> Yeah, straight SDL API, opengl-capable window. Will try a minimal test case for the other one and get back to you.

On 2017-08-13 22:36:02 +0000,  wrote:

> Confirming that this still occurs with the most recent build release (tested via the auto-build for VCC) with 'Fast' vsync as of today.

On 2018-08-06 21:20:22 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting dozens of copies of this message by email.
> 
> We are closing out bugs that appear to be abandoned in some form. This can happen for lots of reasons: we couldn't reproduce it, conversation faded out, the bug was noted as fixed in a comment but we forgot to mark it resolved, the report is good but the fix is impractical, we fixed it a long time ago without realizing there was an associated report, etc.
> 
> Individually, any of these bugs might have a better resolution (such as WONTFIX or WORKSFORME or INVALID) but we've added a new resolution of ABANDONED to make this easily searchable and make it clear that it's not necessarily unreasonable to revive a given bug report.
> 
> So if this bug is still a going concern and you feel it should still be open: please feel free to reopen it! But unless you respond, we'd like to consider these bugs closed, as many of them are several years old and overwhelming our ability to prioritize recent issues.
> 
> (please note that hundred of bug reports were sorted through here, so we apologize for any human error. Just reopen the bug in that case!)
> 
> Thanks,
> --ryan.

On 2018-08-06 23:56:47 +0000,  wrote:

> Bug still present in 2.08 and with latest nvidia drivers in Win7 x64

On 2018-08-07 01:12:40 +0000, Ryan C. Gordon wrote:

> 
> Okay, I'll try to reproduce this here.
> 
> --ryan.

**Comment by icculus** [comment]
I'm assuming this is long-since fixed or a driver bug or not widespread.
