### ISSUE TITLE
wayland: add support for fullscreen shell compositors.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2436]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Proposed patch (0001-add-support-for-wayland-fullscreen-shell.patch, text/plain, 2017-04-15 01:40:13 +0000, 11657 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2721)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2017-04-15 01:40:13 +0000, Nathaniel Lewis wrote:

> Created attachment 2721
> Proposed patch
> 
> Add support for wayland compositors that implement fullscreen-shell.  An example of which is weston with the fullscreen-shell plugins (instead of the default desktop-shell one).  The idea of the fullscreen compositor is that only one, fullscreen surface is visible at any time without any sort of window management.  The primary purpose is to run other compositors to provide fast switching, but there may be other interesting usages of them.
> 
> I've attached a proposed patch.  fullscreen compositors do not have the wl_shell interface, so all functions using wl_shell or wl_shell_surface had to be guarded.  The window show and window show fullscreen functions had to be modified to call zwp_fullscreen_shell_present in the event that the SDL application is running in a fullscreen compositor (checked by whether or not zwp_fullscreen_shell is available).
> 
> Testing:
> - Apply patch to master SDL and build
> - Launch weston via "weston --no-config --width=1024 --height=768 --shell=fullscreen-shell.so --backend=<drm-backend.so, wayland-backend.so or x11-backend.so>"
> - Run an SDL client via ssh (if drm) or locally (if wayland or x11) with WAYLAND_DISPLAY set to the correct display.
> 
> Notes:
> 1) I noticed that without these changes if a window is CREATED with flags specifying fullscreen, the surface will be created with the display's dimensions regardless of the specified size.  It's curious to me as wayland supports fullscreening arbitrarily sized surfaces via scaling.  If it is not created as fullscreen and then later made fullscreen via SDL_SetWindowFullscreen, it is drawn with the regular wayland fullscreen method (draw centered on a black background).
> 
> 2) Since there is no concept of "fullscreen" and "windowed" in fullscreen compositors (only one surface draws to the output at a time), I made "windowed" mode drawing the surface at its specified resolution centered on the display (fullscreen presentation mode "default") and "fullscreen" mode drawing zoomed on the display (no cropping).
> 
> 3) Fullscreen compositors support mode switching by trying to match the surface size to an output mode.  Since the existing wayland video implementation doesn't support mode switching, I didn't add it quite yet.  Still working on a graceful method to support it, but the patch as is is functional.  Need to understand (1) a bit more first.

On 2017-08-11 17:45:43 +0000, Sam Lantinga wrote:

> Gabriel, are you maintaining the Wayland code these days?

**Comment by flibitijibibo** [comment]
I actually looked into whether this protocol was still in use... I think Weston still has support but there are also newer fullscreen shells that just use xdg_shell: https://www.phoronix.com/scan.php?page=news_item&px=Wayland-Weston-Kiosk-Shell

Other fullscreen shells do the same thing from what I can tell. And as you'd expect, this patch doesn't come _close_ to applying cleanly 5 years later. Unless someone really wants to make a path for a very specific compositor I don't think this is going to happen.
