### ISSUE TITLE
Compiles with warnings at SDL_test_common.c(64-bit) and SDL_render_gles2.c(32-bit) on Android NDK

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2442]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows 10, Other

# Comments on the original bug report:

On 2017-04-22 11:18:26 +0000,  wrote:

> When trying to compile SDL2 2.0.5 on Android-ndk, I get the following warnings on SDL_test_common.c 64-bit compilations:
> 
> --- Begin of error copy
> jni/SDL2/src/test/SDL_test_common.c: In function 'SDLTest_PrintEvent':
> jni/SDL2/src/test/SDL_test_common.c:1213:9: warning: format '%lld' expects argument of type 'long long int', but argument 2 has type 'SDL_GestureID' [-Wformat=]
>          SDL_Log("SDL_EVENT: Dollar gesture detect: %"SDL_PRIs64, (Sint64) event->dgesture.gestureId);
>          ^
> jni/SDL2/src/test/SDL_test_common.c:1216:9: warning: format '%lld' expects argument of type 'long long int', but argument 2 has type 'SDL_GestureID' [-Wformat=]
>          SDL_Log("SDL_EVENT: Dollar gesture record: %"SDL_PRIs64, (Sint64) event->dgesture.gestureId);
> --- End of error copy
> (The Begin and End of the copied text from the Windows 10 command prompt are marked on their own lines)
> 
> Also, some other warning occurs on 32-bit compilations:
> --- Begin of error copy
> jni/SDL2/src/render/opengles2/SDL_gles2funcs.h: In function 'GLES2_LoadFunctions':
> jni/SDL2/src/render/opengles2/SDL_render_gles2.c:294:45: warning: assignment from incompatible pointer type
>  #define SDL_PROC(ret,func,params) data->func=func;
>                                              ^
> jni/SDL2/src/render/opengles2/SDL_gles2funcs.h:56:1: note: in expansion of macro 'SDL_PROC'
>  SDL_PROC(void, glShaderSource, (GLuint, GLsizei, const GLchar* const*, const GLint *))
> --- End of error copy
> 
> The SDL2/src directory is a directly unmodified copy of the SDL2-2.0.5\src folder in the zip file provided on the libsdl.org website.

On 2017-08-11 18:39:55 +0000, Sam Lantinga wrote:

> Hey Ryan, more joy with the format specifiers...

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
