### ISSUE TITLE
X11: SDL_SetWindowSize always resets the window position to zero

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2444]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-04-26 17:29:06 +0000, Daniel wrote:

> The problem is that when XResizeWindow emits ConfigureNotify, x and y of the XConfigureEvent struct set to zero, because the function doesn't change the coordinates.
> 
> This means that XResizeWindow always resets the window position to zero in SDL_x11_events.c by sending SDL_WINDOWEVENT_MOVED.
> 
> I do not know whether it's possible to distinguish resizing from moving in X11, but one possible solution is to add X11_XMoveWindow() after X11_XResizeWindow() in X11_SetWindowSize(). It's not perfect since SDL_WINDOWEVENT_MOVED
> event will still be generated on resizing, but at least it (and SDL_GetWindowSize()) will have the right position instead of zero.

On 2017-08-11 18:38:52 +0000, Sam Lantinga wrote:

> Ryan, can you look at this? Is there a mask of changes that we're not paying attention to?

**Comment by icculus** [comment]
We fixed this at some point, test case follows (just press 1 or 2 to change window sizes)...

```c
#include <stdio.h>
#include "SDL.h"

int main(int argc, char **argv)
{
    SDL_Init(SDL_INIT_EVENTS | SDL_INIT_VIDEO);
    SDL_Window *win = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, 0);
    SDL_Renderer *renderer = SDL_CreateRenderer(win, -1, 0);
    SDL_bool done = SDL_FALSE;

    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);

    while (!done) {
        SDL_Event ev;
        while (SDL_PollEvent(&ev)) {
            if (ev.type == SDL_KEYDOWN) {
                switch (ev.key.keysym.sym) {
                    case SDLK_1: SDL_SetWindowSize(win, 640, 480); break;
                    case SDLK_2: SDL_SetWindowSize(win, 800, 600); break;
                    default: break;
                }
            } else if (ev.type == SDL_QUIT) {
                done = SDL_TRUE;
            }
        }

        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
    }

    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(win);
    SDL_Quit();

    return 0;
}
```
