### ISSUE TITLE
SDL_LogSetOutputFunction(...) should revert to default output function

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2469]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-06-09 07:17:44 +0000,  wrote:

> Call to function SDL_LogSetOutputFunction(SDL_LogOutputFunction callback, void *userdata) with parameter callback set to NULL should revert to default output function (e.g. if (callback == NULL)SDL_log_function = SDL_LogOutput;).
> Otherwise upon changing the log output function to a custom one, one cannot revert to the default (function SDL_LogOutput is declared static in SDL_log.c).

On 2017-06-09 09:06:31 +0000,  wrote:

> In case of forgetting to do first a Get before setting the custom function.

On 2017-06-09 14:28:27 +0000, Ryan C. Gordon wrote:

> 
> Right now, callback==NULL doesn't crash when logging, it effectively turns logging off, which could also be desirable. I don't think we specifically documented that effect, though, so we _could_ change this.
> 
> Another alternative is to add a SDL_LogGetDefaultOutputFunction() API.
> 
> Sam, do you have a preference on this?
> 
> --ryan.

On 2017-06-09 16:42:19 +0000,  wrote:

> Would be nice to have a consistent approach for all callback function (e.g. SDL_HitTest, and others I don't know of).
> 
> Many thanks!

**Comment by icculus** [comment]
Let's make a decision on what this should do in 2.0.20.

**Comment by slouken** [comment]
You can get the original logging function with SDL_LogGetOutputFunction(), so we don't need to change behavior here.

**Comment by Raffaello** [comment]
@slouken  it would be nice though to have an `SDL_LogResetOutputFunction` to restore to default setting. very "user friendly" IMO.
