### ISSUE TITLE
SDL_FreeSurface is NOT thread safe

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2475]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Source of test app (SDL_FreeSurface_double_free.c, text/x-csrc, 2017-06-16 13:57:12 +0000, 2706 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2763)

**Reported in version:** 2.0.5
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-06-16 13:57:12 +0000, Dan_ru wrote:

> Created attachment 2763
> Source of test app
> 
> Function SDL_FreeSurface() is NOT thread safe in all 2.0.X version of SDL.
> Versions 1.X.X is free from bug.
> 
> Calling SDL_FreeSurface() on different surfaces can cause crashing ("double free").
> 
> As I see problem is in fuctions SDL_AllocFormat() and SDL_FreeFormat() - currently work with global list "static SDL_PixelFormat *formats;" is not under mutex.
> 
> 
> Also I can suggest to move calling SDL_FreeFormat() from SDL_FreeSurface() to SDL_QuitSubSystem(SDL_INIT_VIDEO) and/or SDL_Quit().
> 
> Source of test app is attched.

On 2020-08-24 18:40:05 +0000,  wrote:

> I ran into this issue yesterday after refactoring my surface loading logic and, after several hours of frustration, I decided that the problem probably lies in SDL itself. My surface is stored in a wrapper that calls SDL_FreeSurface, and that wrapper is stored in a smart pointer - as such, it is impossible for my program to have freed the same surface twice. Furthermore, this issue doesn't occur when I comment out SDL_FreeSurface, so I'm certain that the problem has to do with it.
> 
> Has anything been done for this issue? I'm thinking I might have to just single-thread my surface loading for now.
> 
> Additional info: while this issue occurred for me on Linux, I could not reproduce it on Windows.

**Comment by slouken** [comment]
This was fixed by https://github.com/libsdl-org/SDL/commit/6867f6189fa31bd22d623d87367975f830f14a46

**Comment by icculus** [comment]
Nothing quite like fixing something four years ago and then totally forgetting about it.  :)
