### ISSUE TITLE
SDL2 cannot be compiled with CLANG, LLVM-vs2014, vs2017, v141

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2479]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [result of building via LLVM-vs2014 chain (CLANGOUT.txt, text/plain, 2017-06-22 05:46:13 +0000, 32331 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2766)
* [remaining warnings after removing files (CLANG remaining warnings.txt, text/plain, 2017-06-22 09:40:28 +0000, 56852 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2767)

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2017-06-22 05:46:13 +0000, Paul wrote:

> Created attachment 2766
> result of building via LLVM-vs2014 chain
> 
> Flooded with bad defines and cant find identifiers correctly, bad includes.

On 2017-06-22 09:40:28 +0000, Paul wrote:

> Created attachment 2767
> remaining warnings after removing files
> 
> Ok, after removing SDL_string.c and SDL_fillrect.c, it compiled with a long list of warnings that need fixing, which might be fine for now as I don't need either of those components...

On 2017-06-22 09:42:34 +0000, Paul wrote:

> I will also note, some log and build directories need fixing in cmake as it currently places them outside the build tree, you'll see which ones when you do a full build.

On 2017-08-19 10:13:43 +0000, Sam Lantinga wrote:

> This is partially fixed with this commit, allowing SDL applications to build with clang on Visual Studio:
> https://hg.libsdl.org/SDL/rev/6ae35c5f7f7b
> 
> We don't currently support building SDL with LLVM on Windows, so I'm lifting this bug from blocking the 2.0.6 release.
> 
> Please feel free to submit a patch if you implement this yourself.

**Comment by sezero** [comment]
This should be fixed after #4269 was merged. Closing.
