### ISSUE TITLE
osx cursor can move out of window while grabbed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2480]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** macOS 10.12, x86_64

# Comments on the original bug report:

On 2017-06-22 21:57:55 +0000,  wrote:

> Video with test program: https://streamable.com/yeete
> Code https://gist.github.com/VPeruS/8b4baaf59940443c615a2ab32e7a0259
> 
> Real cursor is out of window. 
> If you make big mouse move in edge direction while cursor is near it and then try move it back cursor will stay in same position.

On 2017-07-14 02:50:10 +0000, Alex Szpakowski wrote:

> Have you tried compiling SDL with SDL_MAC_NO_SANDBOX defined? It enables a better method of mouse grabbing which should fix the issues you're seeing.
> 
> The reason why it's not used by default is, as the name implies, it's disallowed by the Mac App Store sandboxing rules.

On 2017-07-22 15:43:05 +0000,  wrote:

> Also I run it on my VM. Use brew for downloading SDL. Will try to comiple manually with SDL_MAC_NO_SANDBOX.

On 2017-07-31 20:47:24 +0000,  wrote:

> ./confine CFLAGS="-DSDL_MAC_NO_SANDBOX" didnt help.

On 2017-08-02 17:32:20 +0000, Sam Lantinga wrote:

> Have you tried it running natively with defining SDL_MAC_NO_SANDBOX? You can always get the mouse cursor out of a VM.
> 
> Also, did you confirm that the flag was making it into the compile?

On 2017-08-02 19:43:13 +0000,  wrote:

> (In reply to Sam Lantinga from comment # 4)
> > Have you tried it running natively with defining SDL_MAC_NO_SANDBOX? You can
> > always get the mouse cursor out of a VM.
> > 
> > Also, did you confirm that the flag was making it into the compile?
> 
> No I didn't, only on VM. CFLAGS variable in Makefile has -DSDL_MAC_NO_SANDBOX

On 2017-08-03 16:40:54 +0000, Sam Lantinga wrote:

> Please try running natively instead of in a VM and see if you still see the problem.

**Comment by icculus** [comment]
To be verified in 2.0.20.

**Comment by slouken** [comment]
This was actually fixed in 2.0.18, in commit https://github.com/libsdl-org/SDL/commit/35d90f17e1c7d3740c75641ef94b5e5c938c20c6
