### ISSUE TITLE
Caps lock key changes caps lock state while text input is disabled

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2484]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-06-26 00:29:43 +0000, stef wrote:

> While text input is disabled, pressing caps lock still toggles the caps lock state. (using 2.0.5 on linux/X11 - I did not check other platforms)
> 
> IMO this is a bug, since caps lock is a text input modifier. Also, this prohibits the use of caps lock as a regular key while text input is off.

On 2017-08-11 18:08:00 +0000, Sam Lantinga wrote:

> I don't know that we can actually fix this, as it's handled by the X server. Ryan, do you know?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
