### ISSUE TITLE
patch proposal to support compose keys in wayland driver

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2488]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [proposed patch (wayland_compose_keys.diff, text/plain, 2017-06-30 08:06:25 +0000, 8412 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2783)

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2017-06-30 08:06:25 +0000,  wrote:

> Created attachment 2783
> proposed patch
> 
> The current (2017-06-30) SDL2 wayland driver does not support compose (dead) keys
> for input of e.g. accented characters. The attached patch provides a solution.

**Comment by flibitijibibo** [comment]
I think this is still unsupported in the current revision... this patch needs to be rebased.

**Comment by flibitijibibo** [comment]
Resolved by https://github.com/libsdl-org/SDL/commit/5c78df9c2337746bb929337239d000f8a2e6560f
