### ISSUE TITLE
Resizing a window with hidden cursor causes window to resize to 0x0 px

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2507]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2017-07-21 21:18:40 +0000, Temtaime wrote:

> After upgrading to 2.0.5 i've noticed that resizing a window with hidden cursor makes something weird : the window becomes of the size 0x0 and doesn't resize after it at all.
> With 2.0.4 it worked.

On 2017-07-21 21:20:04 +0000, Temtaime wrote:

> I think there's was a change that moves a cursor to the center of the window, but does that even when an user clicked on the window frame, so user starts to resize, and sdl sees that window is active again and moves the cursor to the center, until the window becomes 0x0.

On 2017-07-21 21:28:38 +0000, Temtaime wrote:

> Forgot to say, the bug appears when SDL_SetRelativeMouseMode(true) was called

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
