### ISSUE TITLE
[patch] Display hotplugging

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2515]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[Cocoa display hotplugging patch (cocoa-display-hotplug.patch, text/plain, 2017-07-27 20:15:40 +0000, 3332 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2808)~~
* [Cocoa + win32 display hotplugging patch (display-hotplug-cocoa-win.diff, text/plain, 2017-08-01 23:12:16 +0000, 7868 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2814)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-07-27 05:55:46 +0000, Eric Wasylishen wrote:

> Would be nice to have. e.g. you currently can't plug in a display, drag an SDL window to it, and go fullscreen on the new display.
> 
> Seems pretty easy to do. e.g. add a SDL_ClearVideoDisplays function to SDL_video.c that does:
>     _this->displays = NULL;
>     _this->num_displays = 0;
> Then add OS-specific handlers that detect a configuration change, and clear + re-add all of the displays.
> 
> - Windows: handle WM_DISPLAYCHANGE, probably in the helper window created in SDL_HelperWindowCreate?
> - macOS: CGDisplayRegisterReconfigurationCallback

On 2017-07-27 20:15:40 +0000, Eric Wasylishen wrote:

> Created attachment 2808
> Cocoa display hotplugging patch
> 
> Here is a first attempt at a Cocoa implementation.
> 
> To test it out I used this patch: https://bugzilla.libsdl.org/show_bug.cgi?id=3646
> which adds Option+Left and Option+Right keybindings to the test apps to move the window between displays.

On 2017-07-31 00:58:30 +0000, Eric Wasylishen wrote:

> And for X11, I think it's RRScreenChangeNotify we'll need to listen for?
> https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt#n1715

On 2017-08-01 13:19:50 +0000, Alex Szpakowski wrote:

> It'd be nice if SDL events were posted when this happens as well.
> 
> I can pretty easily implement the iOS backend code for this, if the functionality goes into SDL.

On 2017-08-01 23:12:16 +0000, Eric Wasylishen wrote:

> Created attachment 2814
> Cocoa + win32 display hotplugging patch
> 
> Yeah, an SDL event for when this happens would be good to add.
> 
> Another thing not currently handled by my patch is if the display dimensions change when a SDL window is currently fullscreen-desktop on it (e.g. if the display is rotated or the resolution is changed.)
> 
> Added a win32 implementation.

On 2017-08-11 22:38:49 +0000, Eric Wasylishen wrote:

> The Windows patch needs some more work; it's causing a crash when doing fullscreen mode changes.
> 
> It seems that WM_DISPLAYCHANGE gets delivered to the helper window during the ChangeDisplaySettingsEx call in WIN_SetDisplayMode. This results in all of the SDL_VideoDisplay objects being freed and the displays re-enumerated, but WIN_SetDisplayMode still has a stale pointer to one of the freed displays which it tries to dereference.
> 
> so, I'll need to do something more involved than just freeing displays and re-creating them.. maybe setting a flag on the SDL_VideoDisplay to mark it as "removed".

**Comment by icculus** [comment]
I assume this is resolved by 76980e30f29e92529f62bc910a991e3baf233e2b.
