### ISSUE TITLE
Fullscreen exits fullscreen when minimized or hidden

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2516]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Program illustrating issue (file_3717.txt, text/plain, 2017-07-28 14:51:38 +0000, 1155 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2809)
* [Patch removing the fullscreen changes (patch, text/plain, 2017-07-28 14:57:03 +0000, 1123 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2810)

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-07-28 14:51:38 +0000, James Legg wrote:

> Created attachment 2809
> Program illustrating issue
> 
> When a fullscreen window is minimized (which happens by default when it looses focus) or hidden, the fullscreen state is removed, and the window resized to its previous size (either the size it was before entering fullscreen mode or size specified on creation if created fullscreen). On GNOME, the window contents can still be updated in this state as the window is visible in the Activities view, however it is not screen size and should be.
> 
> Steps to reproduce:
> 1. Compile attached program with c++ $(sdl2-config --cflags --libs)
> 2. Run the program on GNOME
> 3. Press Super + H to hide the window
> 4. Press Super to show the Activities view
> 
> Expected result:
> The program's window appears:
>  - undecorated
>  - all red, with a darker patch in the middle,
>  - with the same proportions as its display, and
>  - at the same size as any non-SDL fullscreen windows if any are present on the workspace.
> (Basically, as it was before it was hidden, scaled to fit)
> 
> Actual result:
> The window appears:
>  - decorated,
>  - with no dark red patch,
>  - square, and
>  - at most 64×64 pixels in size.

On 2017-07-28 14:57:03 +0000, James Legg wrote:

> Created attachment 2810
> Patch removing the fullscreen changes
> 
> This patch removes the change to non-fullscreen windows, which fixes the behaviour for the test program. However, I think this needs more thought when entering and leaving fullscreen would involve a video mode change (a subset of the SDL_WINDOW_FULLSCREEN but not SDL_WINDOW_FULLSCREEN_DESKTOP case), and I haven't tested this on other platforms.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
