### ISSUE TITLE
Configure script fails to set up dynamic loading for some libs.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2531]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-08-07 14:56:07 +0000, Ryan C. Gordon wrote:

> The "find_lib" function in the configure script (and probably the equivalent in CMake) will find libraries for dynamic loading if a "libname.so.1" exists on the system, but it will fail if the system only has "libname.so.1.1" ...apparently the Debian/Ubuntu package for libsndio-dev only installs a "libsndio.so.6.1" file.
> 
> To reproduce:
> - Install Ubuntu.
> - sudo apt-get install libsndio-dev
> - Run SDL's configure, see that it found sndio support, but doesn't list it as a dynamic dependency, thus linking directly to it.
> 
> In this case, SDL should find "libsndio.so.6.1" for the library name as a fallback.
> 
> --ryan.

On 2017-08-09 05:25:36 +0000, Ryan C. Gordon wrote:

> (Sorry if you get a lot of copies of this email, we're touching dozens of bug reports right now.)
> 
> Tagging a bunch of bugs as target-2.0.6.
> 
> This means we're in the final stretch for an official SDL 2.0.6 release! These are the bugs we really want to fix before shipping if humanly possible.
> 
> That being said, we don't promise to fix them because of this tag, we just want to make sure we don't forget to deal with them before we bless a final 2.0.6 release, and generally be organized about what we're aiming to ship. After some debate, we might just remove this tag again and deal with it for a later release.
> 
> Hopefully you'll hear more about this bug soon. If you have more information (including "this got fixed at some point, nevermind"), we would love to have you come add more information to the bug report when you have a moment.
> 
> Thanks!
> --ryan.

On 2020-07-03 11:22:11 +0000, Rainer Deyke wrote:

> Just came here to report this (for cmake), only to find that it's three-year-old known bug.  As a workaround, I am manually passing "-DSNDIO_SHARED=ON" to cmake for now.

**Comment by madebr** [comment]
I can reproduce this with current main in a docker container.
The following libsndio libraries are installed:
```
/usr/lib/x86_64-linux-gnu/libsndio.so -> libsndio.so.7.2
/usr/lib/x86_64-linux-gnu/libsndio.so.7 -> libsndio.so.7.2
/usr/lib/x86_64-linux-gnu/libsndio.so.7.0 -> libsndio.so.7.2
/usr/lib/x86_64-linux-gnu/libsndio.so.7.2
```
The current behavior of the cmake script is:
1. find `libsndio.so`
2. follow the symlink to `libsndio.so.7.2`
3. chop off all final dots and digits to end up with with `libsndio.7`

There is no check whether `libsndio.so.7` actually exists.
When I manually `sudo rm libsndio.so.7`, the cmake script keeps using `libsndio.so.7`.

**Comment by madebr** [comment]
#7923 fixes this for SDL3

When removing `libsndio.so.7` in the above example, it will resolve to `libsndio.so.7.2` instead of the previous `libsndio.so.7`.

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/pull/7931 addresses this for SDL2's cmake.
