### ISSUE TITLE
SDL_iconv_string doesn't properly signal an error with invalid input sizes

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2559]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [A little test case for wrong usage of SDL_iconv_string. (iconv_test.c, text/x-csrc, 2017-08-21 15:36:36 +0000, 1856 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2869)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-08-21 15:36:36 +0000, Simon Hug wrote:

> Created attachment 2869
> A little test case for wrong usage of SDL_iconv_string.
> 
> SDL_iconv_string can return without encoding all characters and then doesn't signal that an error happened, like returning NULL. This only seems to be possible if the user makes a mistake and calculates the size of the string wrong. The SDL implementation of iconv may throw SDL_ICONV_EINVAL in that case and SDL_iconv_string essentially just exits with the unfinished string.
> 
> SDL is not responsible for user error, but I think it should signal that something went wrong. If the last character is expected to be a terminating zero and it is missing, well... we all known to what kind of bugs that leads.
> 
> Since SDL_iconv_string allocates plenty of memory, I also propose that it always adds a terminating zero at the end.
> 
> The attached program converts a string four times and dumps the memory.
> 
> I did not test any iconv implementations outside of SDL yet. I'm guessing it's also a problem there.

On 2017-08-30 07:06:43 +0000, Sam Lantinga wrote:

> I agree this should be fixed, but I'd like to research what different platforms do in this case, and it doesn't need to hold up 2.0.6.

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
