### ISSUE TITLE
Fullscreen windows incorrect in vmware

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2570]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Screenshot of testsprite2 --fullscreen working badly. (Screen Shot 2017-08-25 at 10.47.38 AM.png, image/png, 2017-08-25 15:04:08 +0000, 118425 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2894)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2017-08-25 15:04:08 +0000, Ryan C. Gordon wrote:

> Created attachment 2894
> Screenshot of testsprite2 --fullscreen working badly.
> 
> On vmware, creating a 640x480 (or whatever) fullscreen window fails to work, even though the X server reports it supports a 640x480 resolution (see attached screenshot).
> 
> When running "./testsprite2 --fullscreen", it "changed resolution" (in vmware's case: resized the window on the host machine), but failed to put the SDL window in the right place. If I then hit ctrl-g to grab the mouse, or ctrl-r to toggle on relative mouse mode, it fixes itself.
> 
> Note that the window is rendering incorrectly (the sprites are _way_ too big; is this a matter of SDL_RenderSetLogicalSize() getting the wrong dimensions?). When grabbing the mouse fixes the window, this all starts rendering at the correct size.
> 
> --fullscreen-desktop works correctly in any case.
> 
> Default Ubuntu 17.04 install in the virtual machine.
> 
> This appears to be working correctly on real hardware with a real 640x480 resolution available, and _maybe_ this is a vmware bug, but since SDL can right itself here when grabbing the mouse, I'm wondering if there's some magic incantation we can do at the end of X11_CreateWindow() that will sync all this up, or some wait we have to do while the X server changes resolutions that we aren't doing, etc.
> 
> A quick test shows this has been broken all the way back to SDL-2.0.0, and since no one is complaining loudly, this probably isn't super-urgent.
> 
> --ryan.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
