### ISSUE TITLE
Debian package builder

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2601]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [0001-debian-Use-latest-libudev-dependency-if-possible.patch (0001-debian-Use-latest-libudev-dependency-if-possible.patch, text/plain, 2020-06-21 10:33:01 +0000, 1177 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4394)

**Reported in version:** don't know
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2017-09-09 18:25:51 +0000, Sam Lantinga wrote:

> At some point it would be nice to have a debian package builder to verify that the debian package builds correctly and has the right version number.

On 2020-06-20 09:52:16 +0000, RzR wrote:

> Hi,
> may this relate,
> I am manually building snapshot builds (with some WIP changes) using OBS.
> To avoid overlap I used lower version that latest release.

On 2020-06-21 10:33:01 +0000, RzR wrote:

> Created attachment 4394
> 0001-debian-Use-latest-libudev-dependency-if-possible.patch
> 
> Hi again,
> 
> I can also help to provide helper files to build snapshotpackage,
> here is the first patch of upcoming serie.
> 
> Attached file is same as:
> 
> https://github.com/CrossStream/SDL/commit/3a6f68487819b247aec69ef8e6c2d2ebb8926ea0.patch
> 
> from:
> 
> https://github.com/CrossStream/SDL/commits/sandbox/rzr/review/master
> 
> Review welcome

**Comment by slouken** [comment]
We have removed the Debian packaging from SDL, as they maintain that entirely upstream.
