### ISSUE TITLE
Fallthrough warnings gcc-7

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2603]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [gcc 7 fallthrough warnings (warning.txt, text/plain, 2017-09-10 17:47:33 +0000, 68271 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2922)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-09-10 17:47:33 +0000, Martin Gerhardy wrote:

> Created attachment 2922
> gcc 7 fallthrough warnings
> 
> There are more warnings as in # 3780

On 2017-09-10 19:54:59 +0000, Sam Lantinga wrote:

> Fixed, thanks!
> https://hg.libsdl.org/SDL/rev/93013728e8a3

On 2017-09-10 20:05:52 +0000, Martin Gerhardy wrote:

> Looks like this https://hg.libsdl.org/SDL/rev/93013728e8a3 doesn't fix it (for whatever reason)
> 
> same is true for DUFFS_LOOP4 fix - maybe due to the fact that it is a macro? I have no idea yet. Will investigate a little bit more. Ideas are welcome.
> 
> Btw. thanks for taking care that fast.

On 2017-09-10 20:30:45 +0000, Sam Lantinga wrote:

> It works here with gcc 7.2. What version of gcc are you using?

On 2017-09-11 05:51:36 +0000, Martin Gerhardy wrote:

> GCC 7.2.0-1 (Debian)

On 2017-09-11 17:55:03 +0000, Sam Lantinga wrote:

> Okay, well feel free to submit a patch that works for you.

**Comment by icculus** [comment]
We did some work on fallthrough warnings in 2.0.18, so I'm assuming this is fixed until someone reports it again.
