### ISSUE TITLE
install-strip is not supported

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2609]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, x86

# Comments on the original bug report:

On 2017-09-11 11:03:53 +0000, Christer Solskogen wrote:

> 'install-strip' is not a valid target for SDL, but it is for (at least SDL_image, and SDL_ttf) for the other SDL projects.

**Comment by madebr** [comment]
CMake (at least when using the `Ninja` or `Unix Makefiles` generator) automatically provides a `install/strip` target doing what you ask.
