### ISSUE TITLE
request to implement input.h switch codes

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2610]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-09-11 17:50:41 +0000, Clayton Craft wrote:

> There are a few switch scancodes defined in linux/input.h that would be very useful for interacting with from within SDL2, and I was wondering if some of them could be implemented (list taken from kernel 4.12 input.h) :
> 
> #define SW_LID			0x00  /* set = lid shut */
> #define SW_TABLET_MODE		0x01  /* set = tablet mode */
> #define SW_HEADPHONE_INSERT	0x02  /* set = inserted */
> #define SW_RFKILL_ALL		0x03  /* rfkill master switch, type "any"
> 					 set = radio enabled */
> #define SW_RADIO		SW_RFKILL_ALL	/* deprecated */
> #define SW_MICROPHONE_INSERT	0x04  /* set = inserted */
> #define SW_DOCK			0x05  /* set = plugged into dock */
> #define SW_LINEOUT_INSERT	0x06  /* set = inserted */
> #define SW_JACK_PHYSICAL_INSERT 0x07  /* set = mechanical switch set */
> #define SW_VIDEOOUT_INSERT	0x08  /* set = inserted */
> #define SW_CAMERA_LENS_COVER	0x09  /* set = lens covered */
> #define SW_KEYPAD_SLIDE		0x0a  /* set = keypad slide out */
> #define SW_FRONT_PROXIMITY	0x0b  /* set = front proximity sensor active */
> #define SW_ROTATE_LOCK		0x0c  /* set = rotate locked/disabled */
> #define SW_LINEIN_INSERT	0x0d  /* set = inserted */
> #define SW_MUTE_DEVICE		0x0e  /* set = device disabled */
> #define SW_MAX			0x0f
> #define SW_CNT			(SW_MAX+1)

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
