### ISSUE TITLE
SDL_SetWindowPosition does not send a SDL_WINDOWEVENT_MOVED

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2613]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2017-09-12 01:08:39 +0000, Ioannis Makris wrote:

> I think that SDL_SetWindowPosition, on Windows, would never send a SDL_WINDOWEVENT_MOVED
> 
> in SDL_video.c (https://hg.libsdl.org/SDL/file/d167d43d74f2/src/video/SDL_video.c) we have the following:
> 
>   1813         if (!SDL_WINDOWPOS_ISUNDEFINED(x)) {
>   1814             window->x = x;
>   1815         }
>   1816         if (!SDL_WINDOWPOS_ISUNDEFINED(y)) {
>   1817             window->y = y;
>   1818         }
>   1819 
>   1820         if (_this->SetWindowPosition) {
>   1821             _this->SetWindowPosition(_this, window);
>   1822         }
>   1823         SDL_SendWindowEvent(window, SDL_WINDOWEVENT_MOVED, x, y);
> 
> then in SDL_windowevents.c (https://hg.libsdl.org/SDL/file/d167d43d74f2/src/events/SDL_windowevents.c):
>   
> https://hg.libsdl.org/SDL/file/d167d43d74f2/src/events/SDL_windowevents.c
> 
>    122         if (data1 == window->x && data2 == window->y) {
>    123             return 0;
>    124         }
>    
> but data1 and data2 is x and y. It will always return 0 and skip sending the message further.

**Comment by slouken** [comment]
That's correct. Programmatic changes don't result in move events, as it's assumed the application already knows about the move.
