### ISSUE TITLE
provide access to SDL_Surface of already-created software renderer(s)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2615]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [possible implementation, #1 (SDL_GetSoftwareRendererSurface_1.diff, text/plain, 2017-09-13 17:22:36 +0000, 3643 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2932)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-09-13 17:22:36 +0000, David Ludwig wrote:

> Created attachment 2932
> possible implementation, # 1
> 
> If and when a software SDL_Renderer is created, there does not appear to be any means to get its inner SDL_Surface, once the renderer has been created.  An SDL_Surface can be passed into SDL_CreateSoftwareRenderer, and that SDL_Surface may be used later on, however, if one is created through other means, such as a user setting the SDL_RENDER_DRIVER environment variable, there is no public API to retrieve this surface.
> 
> Proposal: add an API to retrieve the SDL_Surface of an existing software SDL_Renderer.
> 
> Attached is a potential implementation of such a function.  The function itself is:
> 
> SDL_Surface * SDL_GetSoftwareRendererSurface(SDL_Renderer * renderer);
> 
> This function will return NULL for non-software renderers, or on error.  If the renderer is a software renderer, it'll return its SDL_Surface.

On 2017-09-13 17:48:06 +0000, David Ludwig wrote:

> To note, the use case I am looking into here, involves:
> 
> 1. an SDL_Renderer being created, with users, potentially, adjusting what type of renderer is used
> 2. if and when a software renderer is being used, have an app use custom routines to scale images, to the destination surface

**Comment by icculus** [comment]
SDL_GetWindowSurface exists (perhaps it didn't in 2017?). I think this can be closed.

**Comment by slouken** [comment]
Actually, this is a request to get the surface used by a software renderer, not the window surface. This seems like a reasonable request, I'll throw it on for SDL 3.x

**Comment by icculus** [comment]
Isn't the window surface what the software renderer uses?

https://github.com/libsdl-org/SDL/blob/a6bb00f3995aa0e3b3d26d24084809e7e1fb4037/src/render/software/SDL_render_sw.c#L1166

**Comment by slouken** [comment]
It is for that call, but you can also create a renderer for an arbitrary surface (see `SW_CreateRendererForSurface()`)

**Comment by slouken** [comment]
You can grab the surface from a renderer using the SDL_PROP_RENDERER_SURFACE_POINTER property.
