### ISSUE TITLE
The audio callback should have a void* pointer

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2625]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-09-21 17:33:29 +0000, Sam Lantinga wrote:

> The audio callback should have a void* pointer to the data so it's clear that it has a variable type.

**Comment by slouken** [comment]
@1bsyl went ahead and made this change and it turned out not to be an improvement for application code, so we're not going to implement this.
