### ISSUE TITLE
SDL_GetWindowPosition() regression in 2.0.6

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2631]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-09-24 10:29:02 +0000, Daniel wrote:

> Previously (at least in 2.0.4), SDL_GetWindowPosition() returned position of the window decoration, which was consistent with SDL_SetWindowPosition(). I updated to 2.0.6, and it now returns position of the viewport.
> 
> It looks like there was something similar in bug 1300.
> 
> I don't sure: maybe it's by design, and the bug is actually in SDL_SetWindowPosition(), which should ignore the decoration?

On 2017-09-24 19:17:12 +0000, Sam Lantinga wrote:

> Yes, the bug is in SDL_SetWindowPosition()
> 
> What window manager are you using?
> 
> Ryan, can you take a look when you get a chance?

On 2017-09-25 14:37:04 +0000, Daniel wrote:

> My window manager is xfwm4 (Xfce).

On 2017-09-25 16:17:42 +0000, Daniel wrote:

> I currently found that this only happens after all events are polled. That's why testautomation_video.c doesn't detect the bug.
> Here is a snippet:
> 
>     SDL_SetWindowPosition(window, 1, 1);
> 
>     int x, y;
>     SDL_GetWindowPosition(window, &x, &y);
>     printf("Pos %i %i\n", x, y);
> 
>     SDL_Event event;
>     while (SDL_PollEvent(&event)) {
>     }
> 
>     SDL_GetWindowPosition(window, &x, &y);
>     printf("New pos %i %i\n", x, y);
> 
> On my machine, it prints:
>   Pos 1 1
>   New pos 2 27

On 2020-03-15 17:40:45 +0000, Eric Shepherd (:sheppy) wrote:

> I thought this was similar to a problem I'm having but after starting to comment, I decided it might only be tangentially related at most. For whatever it's worth, I filed my problem as bug 5032.

**Comment by rversteegen** [comment]
In my testing, `SDL_GetWindowPosition`  followed by `SDL_SetWindowPosition` immediately after calling `SDL_SetWindowFullscreen(window, 0)` to exit fullscreen (to force the window to go back to position before fullscreening, to work around another SDL bug) moves the window by the window border size under Linux/X11/xfce4/SDL2.0.16 but not under Windows{XP,10}/SDL2.0.14.

Related to #2041.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
