### ISSUE TITLE
Fix detection of EGL support when using DRM

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2641]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to modify configure.in (0001-Modify-configure.in-test-for-DRMKMS-EGL-detection.patch, text/plain, 2017-10-02 10:39:52 +0000, 3566 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2963)

**Reported in version:** 2.0.6
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2017-10-02 10:39:52 +0000, Olivier wrote:

> Created attachment 2963
> Patch to modify configure.in
> 
> In the compile test to check for EGL, gbm.h must be included to
> satisfy the EGL/eglplatform.h check #elif defined(__GBM__) when libdrm and gbm is used with MESA OpenGLES.
> 
> This will then define SDL_VIDEO_OPENGL_EGL which is checked in the drmkms driver.  It will also correctly typedef EGLNativeDisplayType,
> EGLNativePixmapType and EGLNativeWindowType.
> 
> Tested with testgles and testgles2 on RaspberryPi3 with
> libdrm, VC4 gallium driver and Mesa 17.2.1
> 
> The same change should be made for CMakeLists.txt and sdlchecks.make.
> 
> The attached patch only serves to illustrate the problem with a crude fix.  The bottom line is that in the compile tests for EGL, gbm.h needs to be included when using DRMKMS, else OpenGles will not work.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
