### ISSUE TITLE
please allow for paletted surfaces with 32 bit depth

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2671]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2017-10-16 11:09:56 +0000, Fabian Greffrath wrote:

> Hi there,
> 
> as the API documentation for SDL_CreateRGBSurface() states "If depth is 4 or 8 bits, an empty palette is allocated for the surface. If depth is greater than 8 bits, the pixel format is set using the [RGBA]mask parameters."
> 
> However, I would like to create a surface with a 32-bit palette. Why? Because I am creating a source port for Doom, which usually uses a 256-color palette stored in a single byte per color. I want to extend the game to optional true-color rendering and will thus have to change the framebuffer to a 32-bit surface. In order to prevent the need to completely reimplement each rendering routine, I would like to increase the default framebuffer to 32-bit per pixel and interpret each pixel value as a palette index in "paletted" mode and as a RGBA tupel in "true-color" mode. However, with the current limitations on SDL_CreateRGBSurface() this seems impossible to achieve.
> 
> Please consider allowing for 32-bit paletted surfaces, thanks!
> 
>  - Fabian

On 2017-10-16 18:19:14 +0000, Sam Lantinga wrote:

> I'm fine with that, but it would be a feature of SDL_Surface, not the rendering system.
> 
> Would you like to attach a tested patch?

On 2017-10-17 10:29:33 +0000, Fabian Greffrath wrote:

> (In reply to Sam Lantinga from comment # 1)
> > Would you like to attach a tested patch?
> 
> I am not yet that far, just sharing the idea.

On 2017-10-17 15:45:45 +0000, Sam Lantinga wrote:

> Okay, that would be fine with me. :)

On 2017-10-17 15:47:13 +0000, Sam Lantinga wrote:

> Once you implement a patch you might want to check the performance. Shuffling around 32-bit data might be more expensive than working with 8-bit data and doing a final 32-bit expansion right before rendering.

On 2018-08-15 21:55:17 +0000, Fabian Greffrath wrote:

> This seems to be a lot more involved than I initially expected/hoped. There are assumptions about palette values being Uint8 all over the code.
> 
> However, I was pleasantly surprised that simply changing code from this
> 
> screenbuffer = SDL_CreateRGBSurface(0, SCREENWIDTH, SCREENHEIGHT, 8, 0, 0, 0, 0);
> 
> to this
> 
> screenbuffer = SDL_CreateRGBSurface(0, SCREENWIDTH, SCREENHEIGHT, 32, 0, 0, 0, 0);
> SDL_Palette *palette = SDL_AllocPalette(256);
> SDL_SetSurfacePalette(screenbuffer, palette);
> SDL_FreePalette(palette);
> 
> does at least not crash, but then each paletted image will be displayed as shades of blue.

**Comment by icculus** [comment]
I don't think we should add this to SDL.
