### ISSUE TITLE
SDL_SetTextureBlendMode(texture, SDL_BLENDMODE_MOD ) doesnt work with SDL_SetTextureAlphaMod

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2673]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.6
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2017-10-17 07:10:50 +0000, Philipp M. wrote:

> Using SDL_SetTextureBlendMode with the SDL_BLENDMODE_MOD flag the alpha value
> of the texure does not change after calling SDL_SetTextureAlphaMod.

**Comment by slouken** [comment]
The alpha value of the texture doesn't actually change with SDL_BLENDMODE_MOD.
