### ISSUE TITLE
SDL_CreateWindow didn't set SDL_WINDOW_INPUT_FOCUS flag

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2680]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [A simple reproducer. (SDL2BugDemo.tar.gz, application/gzip, 2017-10-23 08:14:00 +0000, 5183758 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3027)

**Reported in version:** 2.0.6
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-10-23 08:14:00 +0000, Tony Liu wrote:

> Created attachment 3027
> A simple reproducer.
> 
> Hi, 
> 
> I've found that the SDL_CreateWindow didn't set the SDL_WINDOW_INPUT_FOCUS flag, which could be reproduced on both Ubuntu 14.04 and 16.04. It causes problem for selecting focused window among multiple windows created. I've prepared a simple reproducer for this problem. 
> 
> This problem might also be duplicate to the one here: https://bugzilla.libsdl.org/show_bug.cgi?id=2745
> 
> BR,
> Tony

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
