### ISSUE TITLE
proposal for bug-fix-only stable branches

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2683]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-10-24 09:44:40 +0000,  wrote:

> I think it would be useful to release bug-fix-only stable branches for one or more versions of SDL and/or related libraries because, currently, each new release adds (sometimes extensive) new features and inadvertantly adds more bugs.
> This would also provide a mechanism to easily release critical security bug fixes without having to wait for the development branch to become stable enough to release.
> I think this could be implemented by somehow providing a simple mechanism for bug-fix commits to be proposed for addition to the stable branches while allowing for possible changes required for back-porting the fix.
> 
> for versioning, I think we could use something like 2.0.6.1 or 2.0.6-1 as the version number for the first bug-fix release based on 2.0.6.
> 
> Alternatively we could the versioning system described in SDL_version.h and start incrementing the minor version for backwards compatible changes, instead of how the patch number has been incrementing even though there have been some non-trivial additions (new audio resampling system, vulkan support, etc.). Then, when a non-backwards-compatible change is made, we'd switch the version to 3.0 instead of 2.1. To facilitate this, what would have been named 2.0.8 will be called 2.1.0 or 2.1.1 instead. I think it would be better to leave the already released versions with their original version numbers to reduce confusion.

**Comment by icculus** [comment]
> each new release adds (sometimes extensive) new features and inadvertantly adds more bugs

This isn't wrong, but I also don't think we're going to change the way we're currently doing this, at least for now.
