### ISSUE TITLE
testautomation surface_testCompleteSurfaceConversion failure

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2691]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.6
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-10-28 10:08:00 +0000, Juha Niemimäki wrote:

> surface_testCompleteSurfaceConversion test seems to fail on both Linux Mint (x86_64) and AmigaOS 4 (PowerPC). Tested here the latest version repository:
> 
> INFO: Linked version: 2.0.7.11658 (hg-11658:fbfdee28682d)
> 
> ./testautomation --filter surface_testCompleteSurfaceConversion
> 
> INFO:  10/28/17 13:03:14: ----- Test Case 14.6: 'surface_testCompleteSurfaceConversion' started
> INFO:  10/28/17 13:03:14: Test Description: 'Tests surface conversion across all pixel formats'
> INFO:  10/28/17 13:03:14: Test Iteration 1: execKey 4328591082807434845
> INFO:  10/28/17 13:03:14: Assert 'Check that testSurface is not NULL': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDL_SetSurfaceBlendMode, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDL_GetSurfaceBlendMode, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate blendMode, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Verify face surface is not NULL': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0005_TestOutput.bmp' and 'CompareSurfaces0005_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0010_TestOutput.bmp' and 'CompareSurfaces0010_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0015_TestOutput.bmp' and 'CompareSurfaces0015_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> INFO:  10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 0': Passed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0020_TestOutput.bmp' and 'CompareSurfaces0020_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0021_TestOutput.bmp' and 'CompareSurfaces0021_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0022_TestOutput.bmp' and 'CompareSurfaces0022_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0023_TestOutput.bmp' and 'CompareSurfaces0023_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0024_TestOutput.bmp' and 'CompareSurfaces0024_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> ERROR: 10/28/17 13:03:14: Comparison of pixels with allowable error of 0 failed 906 times.
> ERROR: 10/28/17 13:03:14: First detected occurrence at position 0,0 with a squared RGB-difference of 195075.
> ERROR: 10/28/17 13:03:14: Surfaces from failed comparison saved as 'CompareSurfaces0025_TestOutput.bmp' and 'CompareSurfaces0025_Reference.bmp'
> ERROR: 10/28/17 13:03:14: Assert 'Validate result from SDLTest_CompareSurfaces, expected: 0, got: 906': Failed
> ERROR: 10/28/17 13:03:14: Assert Summary: Total=30 Passed=21 Failed=9
> INFO:  10/28/17 13:03:14: Total Test runtime: 0.0 sec
> ERROR: 10/28/17 13:03:14: >>> Test 'surface_testCompleteSurfaceConversion': Failed

On 2017-10-28 19:04:57 +0000, Sylvain wrote:

> It seems to be because of format ARGB2101010
> 
> 
> see bug 3367 - RGBA_FROM_PIXEL macro can't handle SDL_PIXELFORMAT_ARGB2101010
> https://hg.libsdl.org/SDL/rev/7f429e943ed3

**Comment by 1bsyl** [comment]
now this test passes
