### ISSUE TITLE
[patch] Wayland: SDL applications start in XWayland by default

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2710]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [prefer-wayland-over-x11.patch (prefer-wayland-over-x11.patch, text/plain, 2019-10-23 14:14:00 +0000, 814 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4017)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-11-07 21:42:34 +0000, Andrey Alexeyev wrote:

> This is because SDL prefers the X11 driver. If XWayland is running on the default display, SDL will happily settle for it, even if the Wayland driver could be used instead.
> 
> This is far from ideal. I've experienced subpar performance and visual artifacts, both specific to XWayland, in my OpenGL game.
> 
> Applications can work around this by attempting to initialize video with the Wayland driver explicitly first.
> 
> This issue probably applies to every other video system where an X11 compatibility layer could be present, e.g. Mir, though I haven't tested that.
> 
> Simply moving X11 lower on the priority list should fix this.

On 2019-10-23 14:07:49 +0000, David Heidelberg (okias) wrote:

> I believe this patch [1] solves this issue. It's took from new linux Librem 5 phone gitlab [2].
> 
> Since two years passed and Wayland became preferred solution in Linux world, would make sense to prefer it over X11 backend?
> 
> [1] https://source.puri.sm/Librem5/libsdl2/raw/997f974c1d0a3acb869cee956c06ba33480f5e58/debian/patches/prefer-wayland-over-x11.patch
> [2] https://source.puri.sm/Librem5/libsdl2/commit/997f974c1d0a3acb869cee956c06ba33480f5e58

On 2019-10-23 14:14:00 +0000, David Heidelberg (okias) wrote:

> Created attachment 4017
> prefer-wayland-over-x11.patch

On 2019-10-23 16:49:05 +0000, Ryan C. Gordon wrote:

> (In reply to David Heidelberg (okias) from comment # 1)
> > Since two years passed and Wayland became preferred solution in Linux world,
> > would make sense to prefer it over X11 backend?
> 
> SDL's wayland target needs client-side decorations in some form, at a minimum, before it can be favored over X11.
> 
> This is definitely not going to happen for 2.0.12.
> 
> --ryan.

**Comment by flibitijibibo** [comment]
I've been hammering at this for quite a while and I'm now pretty comfortable in saying that this is _extremely_ close to being usable by default. The TODO, as far as I can tell:

- Client-side decorations (#3439, #3739, PR #4068)
- Keyboard mapping updates (#3471, #4142, #4187)
- Dead key support (Patch at #2488)
- Clipboard fixes (#3724, #3725, PR #4295)

Once that's done, these three blocks have to be switched around:

https://github.com/libsdl-org/SDL/blob/27b74d3334174d0c57cd314ee9545614902603f7/src/video/SDL_video.c#L64-L69
https://github.com/libsdl-org/SDL/blob/27b74d3334174d0c57cd314ee9545614902603f7/src/video/SDL_video.c#L4042-L4047
https://github.com/libsdl-org/SDL/blob/27b74d3334174d0c57cd314ee9545614902603f7/src/video/SDL_video.c#L4150-L4163

Christian is working on libdecor, I just wrapped up clipboard fixes, the keyboard stuff might be out of my range so both of those are up for grabs.

**Comment by flibitijibibo** [comment]
The last of the list was just merged into main - now CSD is the only blocker for _real_ this time, I hope. I had this written down internally, but I don't think this is necessary to ship:

```
xdg-shell/libdecor stuff:
    - SetWindowIcon
    - GetWindowBordersSize

Maybe in the spec, I think:
    - GetDisplayBounds
    - GetDisplayUsableBounds
    - GetDisplayDPI
    - SetWindowModalFor
    - SetWindowInputFocus
    - HideWindow
    - RaiseWindow
    - XTranslateCoordinates equivalent for IME rectangle
```

**Comment by StarStarJ** [comment]
Will this get a fallback to xwayland for non GLES apps/contexts, or will you wait for mesa drivers to catch up with desktop OpenGL drivers without GLX dependency?
Just wondering, if it won't break alot of stuff.
Testing the linked PR with mesa 21.2 on amdgpu wouldn't work yet.

And another question
Will SDL somehow provide a way to check if the default context profile would be ES, e.g. by setting ES context as default value for SDL_GL_CONTEXT_PROFILE_MASK, so that you can programmatically setup GLES stuff for you application?

**Comment by flibitijibibo** [comment]
To the best of my knowledge Wayland does not default to ES, it just happens to use EGL for WSI - the opengles.c filename is kind of misleading in Wayland's case.

On my AMD test environment it uses desktop GL unless I explicitly set the ES flag. An environment that defaults to ES is going to have problems regardless of display server, forcing desktop GL would probably be a very common workaround for end users on that system.

**Comment by StarStarJ** [comment]
Ah thats good to know. I'm not too much into all these driver things, just read on some stackoverflow that the GLX dependecies in the mesa drivers don't allow native wayland to use desktop OpenGL, which appearntly is wrong then.

Thanks for the quick response.
