### ISSUE TITLE
STREAMING Texture, UpdateTexture not compatible with LockTexture()

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2714]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [testcase (main_bug_update_streaming_texture.c, text/x-csrc, 2017-11-10 20:05:06 +0000, 4442 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3080)
* ~~[patch (main_bug_update_streaming_texture.c, text/x-csrc, 2017-11-10 20:07:34 +0000, 4442 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3081)~~
* ~~[patch (patch_bug_3954_streaming_texture.diff, text/plain, 2017-11-10 20:08:33 +0000, 1737 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3082)~~
* [patch v2 (patch_bug_3954_streaming_texture-v2.diff, text/plain, 2019-06-22 06:52:34 +0000, 2199 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3837)

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-11-10 20:05:06 +0000, Sylvain wrote:

> Created attachment 3080
> testcase
> 
> When using textures created with SDL_TEXTUREACCESS_STREAMING flags, 
> SDL_UpdateTexture() and SDL_LockTexture() aren't updating the same internal memory.
> 
> If you initialize first  your texture with SDL_UpdateTexture(), you won't get the pixels back by using SDL_LockTexture().
> 
> 
> It would work with software renderer, but not with opengl, nor opengles2.
> here's a testcase

On 2017-11-10 20:07:34 +0000, Sylvain wrote:

> Created attachment 3081
> patch
> 
> Small patch could be redirect SDL_UpdateTexture() to a combination of  LockTexture() / SDL_memcpy() / SDL_UnlockTexture().

On 2017-11-10 20:08:33 +0000, Sylvain wrote:

> Created attachment 3082
> patch
> 
> patch

On 2019-05-18 18:48:53 +0000, Ryan C. Gordon wrote:

> 
> Tagging a bunch of bugs with "target-2.0.10" so we have a clear list of things to address before a 2.0.10 release.
> 
> Please note that "addressing" one of these bugs might mean deciding to defer on it until after 2.0.10, or resolving it as WONTFIX, etc. This is just here to tell us we should look at it carefully, and soon.
> 
> If you have new information or feedback on this issue, this is a good time to add it to the conversation, as we're likely to be paying attention to this specific report in the next few days/weeks.
> 
> Thanks!
> 
> --ryan.

On 2019-05-19 17:46:58 +0000, Sam Lantinga wrote:

> This is already fixed, thanks!

On 2019-05-20 18:50:48 +0000, Sylvain wrote:

> Hi,
> It seems to me it's not fixed.
> 
> tested with current head, on linux, with the current test case:
> 
> with the software renderer, the image is drawn in background.
> with other renderer, there is a black background.

On 2019-06-09 14:59:46 +0000, Sylvain wrote:

> The patch seem to works, but I think it's not correct, and maybe there are more optimized things to do.
> 
> the streaming texture can be: 
> - normal: (it has one of the renderer format or not)
> - need a conversion. (then has a "native" texture field).
> 
> Most renderers implement streaming access by adding Lock/Unlock texture functions which are an intermediate storing buffer before access. 
> Just wondering if those implementation could be simply removed and replaced by a dummy use of the "native" texture field (with the same format as the user texture).

On 2019-06-21 17:27:48 +0000, Sam Lantinga wrote:

> Let's revisit this after 2.0.10. This is somewhat by design, for efficiency. Let's see if there is a solution that doesn't reduce performance by introducing additional copy operations.

On 2019-06-22 06:52:34 +0000, Sylvain wrote:

> Created attachment 3837
> patch v2
> 
> I agree. 
> 
> So either UpdateTexture updates the streaming buffer and then, it's consistent with Lock/UnlockTexture, or not, and then, it's faster.
> 
> Here's a modified patch if needed (it seems to affect normal texture, and native, but not yuv).
> 
> But, it's probably better to keep the actual UpdateTexture so it's faster.
> 
> If user needs to update the entire streaming buffer, it can still be done by Locking the buffer.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
