### ISSUE TITLE
Auto-detection to build KMSDRM on Raspberry Pi Rasbpian Stretch does not work

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2742]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [patch of pi kmsdrm build fix (sdl_pi_kmsdrm.patch, text/plain, 2017-12-03 23:16:58 +0000, 853 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3107)

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Other, ARM

# Comments on the original bug report:

On 2017-11-30 21:55:11 +0000, Eric wing wrote:

> The KMSDRM backend will not be compiled in on a typical Raspberry Pi Raspbian Stretch system trying to use the Broadcom drivers.
> 
> The problem is that the script is trying to use pkg-config to get the flags for the EGL library, but two assumptions are broken on the Pi.
> 
> 1. The Broadcom libraries are now prefixed with 'brcm'. That means we have libbrcmegl instead of libegl.
> 
> 2a. The pkg-config script is also named differently. It is brcmegl instead of egl.
> 
> 2b. Raspbian puts these scripts in /opt/vc/lib/pkgconfig. But this is not in the default pkg-config path, so you must explicitly add it. It is recommended you add this to the build system directly.
> 
> I have a patch for the CMake side which I will post a link to after this (so I can commit this bug number to the commit log).
> 
> I've only looked at the CMake script, not the Autotools script.
> 
> 
> My testing presumes the user has actually activated the GL KMS driver in raspi-config.
> My suspicion is that any other testing that has not caught this problem on Raspbian Stretch is due to developers installing Mesa or other alternative EGL libraries. I do not know if those interact with the brcm drivers and if you get the hardware acceleration. But an advantage of using the brcm ones (and this fix) is I beleive  all these things should already be installed by default on a Raspbian Stretch system and do not require the user to install more things.

On 2017-11-30 21:59:44 +0000, Eric wing wrote:

> I published a repo with the fix at https://bitbucket.org/ewing/sdlpikmsbuildfix

On 2017-12-01 02:56:47 +0000, Sam Lantinga wrote:

> Can you attach a patch to this bug?
> 
> Thanks!

On 2017-12-03 23:16:58 +0000, Eric wing wrote:

> Created attachment 3107
> patch of pi kmsdrm build fix
> 
> Here's the patch

On 2017-12-04 00:18:48 +0000, Sam Lantinga wrote:

> Thanks, can you attach a tested patch for configure.in as well?

On 2017-12-04 00:38:02 +0000, Eric wing wrote:

> (In reply to Sam Lantinga from comment # 4)
> > Thanks, can you attach a tested patch for configure.in as well?
> 
> Sorry, I really don't know my way around configure scripts. Is there anybody we can grab who is more knowledgable?

On 2017-12-04 04:19:45 +0000, Sam Lantinga wrote:

> I'm familiar with autoconf, but I don't have a raspberry pi setup.
> 
> Ryan, you want to look at this one?

On 2018-01-30 01:53:08 +0000, Conn O'Griofa wrote:

> Eric,
> 
> Are you testing against 2.0.7 or the latest master? If the former, you should ensure that you're testing with these patches that were merged post-2.0.7: https://bugzilla.libsdl.org/show_bug.cgi?id=3938
> 
> With the above patches, it's possible to compile a build with --enable-video-rpi and --enable-video-kmsdrm together, and everything works as expected depending on the active kernel overlay.
> 
> It wasn't necessary to modify the cmake file as you propose here, and I didn't encounter any dependency or build errors. Are you certain this is not going to break either the rpi or kmsdrm driver when targeting a build that includes both drivers?

On 2018-02-07 19:05:40 +0000, Eric wing wrote:

> (In reply to Conn O'Griofa from comment # 7)
> > Eric,
> > 
> > Are you testing against 2.0.7 or the latest master? If the former, you
> > should ensure that you're testing with these patches that were merged
> > post-2.0.7: https://bugzilla.libsdl.org/show_bug.cgi?id=3938
> > 
> > With the above patches, it's possible to compile a build with
> > --enable-video-rpi and --enable-video-kmsdrm together, and everything works
> > as expected depending on the active kernel overlay.
> > 
> > It wasn't necessary to modify the cmake file as you propose here, and I
> > didn't encounter any dependency or build errors. Are you certain this is not
> > going to break either the rpi or kmsdrm driver when targeting a build that
> > includes both drivers?
> 
> This was tested against the latest master at the time I submitted the patch. 
> The switches you describe don't apply to CMake as far as I understand as CMake doesn't use switches like that. I did not submit any changes to the Autotools system, though I suspect it needs similar changes. 
> 
> I believe the effect of this patch is to indeed get the KMSDRM backend compiled with the Pi drivers. The problem is that the Broadcom Pi drivers were relocated and renamed which is what this patch fixed.

**Comment by slouken** [comment]
@madebr, do you know if we need this patch?

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen if you're still seeing this issue.

**Comment by madebr** [comment]
I haven't tested rpi, but I can build SDL3 with kmsdrm support.
When running `testsprite`, I see a mouse pointer but cannot move it. Pressing <kbd>ESC</kbd> does not exit the application, but <kbd>CTRL</kbd>+<kbd>C</kbd> does.
If I'm not mistaken, there is an issue for this.
