### ISSUE TITLE
GetRawInputDeviceList may return less entries than requested

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2759]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [proposed fix (SDL2-GetRawInputDeviceList.patch, text/plain, 2017-12-21 21:23:26 +0000, 1430 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3117)

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2017-12-21 21:23:26 +0000, Mathieu Laurendeau wrote:

> Created attachment 3117
> proposed fix
> 
> Hello,
> 
> I think I found an issue in SDL_dinputjoystick.c and SDL_xinputjoystick.c.
> 
> There is no guarantee the GetRawInputDeviceList returns the requested number of entries. Moreover the provided buffer is malloc'd, which means something unexpected/random may happen.
> 
> https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms645598(v=vs.85).aspx
> 
> > If the function is successful, the return value is the number of devices stored in the buffer pointed to by pRawInputDeviceList.
> 
> See attached patch.

On 2020-04-25 13:08:54 +0000, Mathieu Laurendeau wrote:

> Please consider adding the suggested patch.

**Comment by slouken** [comment]
Fixed, thanks!
