### ISSUE TITLE
SDL_init after SDL_quit triggers weird message

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2760]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** macOS 10.12, x86

# Comments on the original bug report:

On 2017-12-21 22:12:58 +0000, skaller wrote:

> I have a function which does some basic line drawing, which calls SDL_init to start and SDL_quit to finish. It creates a window to draw in. After the drawing is done, it waits for either a timeout of 15 seconds, or the user to quit by clicking the WM's close button. An event loop reads messages and terminates on seeing SDL_QUIT
> 
> This all works fine for a single call to the function. However if I call it twice I get these messages:
> 
> 2017-12-22 08:42:01.772 flx_arun[7419:700714] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_attributesForCharacterIndex:reply:) block performed very slowly (6.65 secs).
> 
> 2017-12-22 08:42:01.772 flx_arun[7419:700714] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_windowLevelWithReply:) block performed very slowly (4.64 secs).
> 
> The times mentioned here roughly agree with the 15 second delays. The delays are implemented by a spin loop implemented in C++ using a timed lock combined with a separate thread that monitors events using kqueue, that is, all done outside SDL.
> 
> Note, the SDL code actually works correctly. The program actually running is called "flx_arun". This program loads a dylib containing the application code, which loads a library providing SDL services as a dylib, which in turn loads SDL2 as a dylib.
> 
> Note: SDL_main() is never called. Nor is SDL_SetMainReady().
> 
> This is definitely a Mac OSX 10.12 issue. See also:
> 
> https://discussions.apple.com/thread/7367367
> https://stackoverflow.com/questions/40997541/r-warnings-imkclient-stall-detected
> 
> So this is not a bug as such, rather the documentation is a bit weak explaining how SDL_init/SDL_quit/SDL_SetMainReady, etc interact. Any help on this appreciated.

On 2019-05-18 18:48:55 +0000, Ryan C. Gordon wrote:

> 
> Tagging a bunch of bugs with "target-2.0.10" so we have a clear list of things to address before a 2.0.10 release.
> 
> Please note that "addressing" one of these bugs might mean deciding to defer on it until after 2.0.10, or resolving it as WONTFIX, etc. This is just here to tell us we should look at it carefully, and soon.
> 
> If you have new information or feedback on this issue, this is a good time to add it to the conversation, as we're likely to be paying attention to this specific report in the next few days/weeks.
> 
> Thanks!
> 
> --ryan.

**Comment by icculus** [comment]
Look at this (but not necessarily do anything) for 2.0.20.

**Comment by slouken** [comment]
It sounds like there isn't anything that we need to do here. Closing for now, please reopen if that's not correct.
