### ISSUE TITLE
[PATCH] Wayland: fix update fullscreen in multimonitor mode with multiple windows

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2765]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [proposed patch (SDL2-wayland-fix-update-fullscreen.patch, text/plain, 2017-12-27 14:05:03 +0000, 1556 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3121)

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-12-27 14:05:03 +0000, Vladimir wrote:

> Created attachment 3121
> proposed patch
> 
> Change video mode only if needed
> 
> Tested on Centos7 + Weston

On 2018-01-03 18:43:45 +0000, Sam Lantinga wrote:

> This patch needs additional review because it affects other systems and the fullscreen mode switching is very delicate in some cases.

**Comment by flibitijibibo** [comment]
Pretty sure this has been obsoleted by https://github.com/libsdl-org/SDL/commit/4d76c9cb46491064b1817bd69f78d59783546ee5, unless this person was making this change for Xwayland?

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
