### ISSUE TITLE
SDL 2.0.7 wrong screen size detection on android

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2767]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2017-12-29 23:41:27 +0000, tibiz wrote:

> I dont know if it's a pure SDL bug or not,but it's pretty weird.In my app I have a java method to determine the screen resolution of the device.The method is called in the onCreate() method of SDLActivity.I use a Samsung Galaxy A5(2017)(SM-A520F)(1920x1080) for testing,and when i have sdl 2.0.7 it tells 1440x810,and when building project with SDL 2.0.4 it tells 1920x1080.Maybe this but is due to the recent changes in the android subsystem.

On 2017-12-29 23:42:18 +0000, tibiz wrote:

> Forgot to tell,but this bug doesn't appear on emulators

On 2018-01-02 14:47:42 +0000, Sylvain wrote:

> what is your java method ?
> maybe this is a change is you targetSdkVersion API ?

On 2018-01-03 10:53:05 +0000, tibiz wrote:

> This is the function to determine the screen size:
> 
> private String[] getScreenDimension(){
>         DisplayMetrics dm = new DisplayMetrics();
>         getWindowManager().getDefaultDisplay().getRealMetrics(dm);
> 
>         int width = dm.widthPixels;
>         int height = dm.heightPixels;
>         int dens = dm.densityDpi;
>         double wi = (double)width / (double)dens;
>         double hi = (double)height / (double)dens;
>         double x = Math.pow(wi, 2);
>         double y = Math.pow(hi, 2);
>         double screenInches = Math.sqrt(x+y);
> 
>         String[] screenInformation = new String[3];
>         screenInformation[0] = String.valueOf(width) + " px";
>         screenInformation[1] = String.valueOf(height) + " px" ;
>         screenInformation[2] = String.format("%.2f", screenInches) + " inches" ;
> 
>         return screenInformation;
>     }
> 
> getScrenDimension()[0] and getScrenDimension()[1] give me the wrong width and height.
> 
> This is my API version:
>  minSdkVersion 19
>  targetSdkVersion 26

On 2018-01-03 15:54:43 +0000, Sylvain wrote:

> If you build with SDL 2.0.4 and use the same API version as in your 2.0.7, eg
>  minSdkVersion 19
>  targetSdkVersion 26
> 
> what happens ?

On 2018-01-03 20:04:20 +0000, tibiz wrote:

> If I use this:
>  minSdkVersion 19
>  targetSdkVersion 26
> in SDL 2.0.4 it gives me a correct width and height.Also I have noticed, when logcating with SDL 2.0.7 I get this message "D/SurfaceView: Relayout returned: oldFrame=[0,72][1440,810] newFrame=[0,72][1440,810] result=0x1 surface={Surface(name=null)/@0x87f7d7d isValid=true 542053654016}"
> 
> and when using SDL 2.0.4 I get "D/SurfaceView: Relayout returned: oldFrame=[0,72][1920,1080] newFrame=[0,72][1920,1080] result=0x1 surface={Surface(name=null)/@0x87f7d7d isValid=true 542053654016}"

On 2018-01-03 20:19:42 +0000, Sylvain wrote:

> And, why if you use 
> DisplayMetrics dm = getContext().getResources().getDisplayMetrics(); 
> ?

On 2018-01-03 20:32:53 +0000, tibiz wrote:

> If i use this ,I get an error:
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference at org.libsdl.app.SDLActivity.getScreenDimension(SDLActivity.java:170)

On 2018-01-03 20:37:35 +0000, Sylvain wrote:

> strange ... you need to call at a good place, not to early maybe.
> 
> 
> - Also, you can try something in AndroidManifest.xml: android:configChanges="..."
> see if "screenLayout|fontScale|uiMode|screenSize" matters.
> 
> - or to comment out the setSystemUiVisibility() in SDLActivity.java
> 
> 
> - in your logcat, you should also have a line : 
>   SDL : Window size: 1080x1920
> 
> 
> Otherwise, I don't have much idea ...

On 2018-01-03 20:47:05 +0000, tibiz wrote:

> This is what I get in logcat: SDL : Window size: 1440x810.
> Anyway,thanks

**Comment by 1bsyl** [comment]
closing

**Comment by sezero** [comment]
> closing

you did not..
