### ISSUE TITLE
SDL_FINGERDOWN/UP/MOTIOIN and SDL_GetTouchFinger inconsistency

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2778]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2018-01-07 19:25:00 +0000, Peter Kosyh wrote:

> After this patch (Normalize touch events to the render viewport (thanks Sylvain!)) in 2.0.7:
> 
> https://github.com/spurious/SDL-mirror/commit/f686a7de990696afb3b6e371723b22843f73a899#diff-5afd80fd540d64019a6f4665e0b1ff1a
> 
> We have inconsistency between SDL_FINGERDOWN event and SDL_GetTouchFinger result.
> It is so, becouse SDL_AddFinger() does not normalize x and y, so... We have totaly broken situation.
> 
> Possible solutions:
> 
> 1) Revert the patch
> 2) Patch the SDL_AddFinger() instead event watcher ???

On 2018-01-08 12:02:16 +0000, Sylvain wrote:

> Indeed, some inconsistency ... that was bug # 2307

On 2019-10-17 11:45:42 +0000, Sylvain wrote:

> It's reasonable to say that querying the state returns raw values,!
> We can revisit this for SDL 2.1
> (see also bug 2442)

**Comment by slouken** [comment]
This is fixed in SDL3, events come in with the same coordinates as are returned by APIs that query event state. There is a new function SDL_ConvertEventToRenderCoordinates() that you can call if you want to convert event coordinates into the renderer coordinate system, and you should do similar conversion for the results of other API queries.

**Comment by 1bsyl** [comment]
@slouken not sure to understant, APIs that query event state.

SDL_GetTouchFinger() gives a SDL_Finger with x/y being in 0..1
whereas the events gives screen/renderer coordinates:

this produces different outputs:

```
95                 case SDL_EVENT_FINGER_DOWN:
 96                     {
 97                        SDL_Finger *f =  SDL_GetTouchFinger(evt.tfinger.touchId, 0);
 98                        int num = SDL_GetNumTouchFingers(evt.tfinger.touchId);
 99                        if (f) {
100                            SDL_Log("Down %d:: %f %f --- %f %f", num, evt.tfinger.x, evt.tfinger.y, f->x, f->y);
```

**Comment by slouken** [comment]
Ah, okay, that should be fixed.

**Comment by 1bsyl** [comment]
here's the PR https://github.com/libsdl-org/SDL/pull/8514

**Comment by 1bsyl** [comment]
it does the conversion, fill the SDL_Finger data struct, which is used both for the SDL_EVENTs and for the API SDL_GetTouchFinger

**Comment by slouken** [comment]
But the coordinates should be relative to the window, not the renderer. I'll take a look at this again when I have more time.

**Comment by 1bsyl** [comment]
you were right. the bug was fixed. 
SDL_GetTouchFinger gives the same as the events !  in 0..1

**Comment by 1bsyl** [comment]
my mistake

**Comment by slouken** [comment]
Glad to hear it.
