### ISSUE TITLE
Mac: SDL_PumpEvents hangs after SDL_HideWindow on SDL_WINDOW_FULLSCREEN_DESKTOP window

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2781]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [repro (repro.c, text/x-csrc, 2018-01-08 14:29:53 +0000, 1506 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3126)

**Reported in version:** 2.0.7
**Reported for operating system, platform:** macOS 10.13, x86_64

# Comments on the original bug report:

On 2018-01-08 14:29:53 +0000, Aleksi Juvani wrote:

> Created attachment 3126
> repro
> 
> Calling SDL_HideWindow on a SDL_WINDOW_FULLSCREEN_DESKTOP window will hang the application in SDL_PumpEvents for approximately 60 seconds, and will fail to hide the window properly, causing it to reappear some time later.
> 
> It looks like SDL hangs in Cocoa_SetWindowFullscreenSpace while waiting for the fullscreen transition to complete.
> 
> I've attached a minimal repro.

**Comment by icculus** [comment]
The repro, just so it's here and not just in the bugzilla archives:

```c
#include <assert.h>
#include <stdio.h>
#include <SDL.h>

int main()
{
    assert(SDL_Init(SDL_INIT_VIDEO) == 0);

    // if SDL_WINDOW_FULLSCREEN_DESKTOP is replaced with SDL_WINDOW_FULLSCREEN,
    // the application doesn't hang
    SDL_Window* window = SDL_CreateWindow("macOS fullscreen hide bug",
                                          SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
                                          1280, 800,
                                          SDL_WINDOW_OPENGL | SDL_WINDOW_ALLOW_HIGHDPI
                                          | SDL_WINDOW_FULLSCREEN_DESKTOP);
    assert(window);

    unsigned int starttime = SDL_GetTicks();
    unsigned int previoustick = starttime;

    // also reproducible with "while (1)"
    while (SDL_GetWindowFlags(window) & SDL_WINDOW_SHOWN) {
        int tick = SDL_GetTicks();

        if (tick != previoustick && tick % 100 == 0) {
            if (tick > starttime + 2000) {
                printf("%d: hiding window now!\n", tick);

                // if this call is replaced by SDL_DestroyWindow (and window is
                // set to NULL), application doesn't hang
                SDL_HideWindow(window);
            } else {
                printf("%d: not hung\n", tick);
            }

            previoustick = tick;
        }

        // hangs here after SDL_HideWindow
        SDL_PumpEvents();
    }

    printf("window is hidden, quitting!\n");

    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}
```

**Comment by icculus** [comment]
This is my output from that repro on the latest SDL2 in revision control:

```
1200: not hung
1300: not hung
1400: not hung
1500: not hung
1600: not hung
1700: not hung
1800: not hung
1900: not hung
2000: not hung
2100: not hung
2200: not hung
2300: not hung
2400: not hung
2500: not hung
2600: not hung
2700: not hung
2800: not hung
2900: not hung
3000: not hung
3100: not hung
3200: hiding window now!
3788: window is hidden, quitting!
```

So the hide takes a little less than 600 milliseconds, which is all window transition animation time. It's probably not great that SDL_HideWindow blocks while the animation is iterating--a further argument for async window operations--but this didn't hang for 60 seconds.

Either we fixed this, or macOS fixed this, in the last 5 years, but we're good to go either way.
