### ISSUE TITLE
Inconsistent names for static libraries when built for windows with cmake.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2794]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[windows cmake enhancements (better-windows-cmake.patch, text/plain, 2018-01-13 10:23:11 +0000, 4876 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3133)~~
* [0001-appveyor.yml-add-basic-ci-for-msvc.patch (0001-appveyor.yml-add-basic-ci-for-msvc.patch, text/plain, 2018-01-14 14:10:31 +0000, 667 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3135)
* [0002-CMakeLists.txt-sane-name-for-msvc-static-library.patch (0002-CMakeLists.txt-sane-name-for-msvc-static-library.patch, text/plain, 2018-01-14 14:12:13 +0000, 1092 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3136)
* [0003-appveyor.yml-add-mingw-w64-build.patch (0003-appveyor.yml-add-mingw-w64-build.patch, text/plain, 2018-01-14 14:12:49 +0000, 1821 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3137)
* [0004-CMakeLists.txt-generate-pkg-config-files-on-mingw.patch (0004-CMakeLists.txt-generate-pkg-config-files-on-mingw.patch, text/plain, 2018-01-14 14:13:28 +0000, 1849 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3138)
* [0005-CMakeLists.txt-better-leverage-GNUInstallDirs.patch (0005-CMakeLists.txt-better-leverage-GNUInstallDirs.patch, text/plain, 2018-01-14 14:14:31 +0000, 2594 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3140)

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Windows (All), x86_64

# Comments on the original bug report:

On 2018-01-13 06:50:10 +0000,  wrote:

> When building for windows (msvc or mingw-w64) the name of the sdl2 static
> library is inconsistent as compared to linux (unsure about osx).
> 
> I have prepared a patchset which addresses this issue, but I cannot yet
> post emails to discourse. I can attach here, if desired, but in general I
> try to avoid having so many logins/accounts.

On 2018-01-13 10:23:11 +0000,  wrote:

> Created attachment 3133
> windows cmake enhancements
> 
> changes a few things:
> 
> Better leverages GNUInstallDirs to avoid hardcoded directories.
> 
> Changes mingw-w64 libraries to libSDL2.dll, libSDL2.dll.a and libSDL2.a
> and msvc libraries to SDL2.dll, SDL2.lib, and libSDL2.lib for runtime,
> import, and static libraries.
> 
> Adds an appveyor.yml for ci integration (may want to look into that),
> uses cmake to build
> log here: https://ci.appveyor.com/project/hanetzer/sdl/build/2.0.7.28

On 2018-01-13 10:25:54 +0000,  wrote:

> Oh, and it also enables sdl2.pc generation on mingw-w64 targets.

On 2018-01-14 14:10:31 +0000,  wrote:

> Created attachment 3135
> 0001-appveyor.yml-add-basic-ci-for-msvc.patch
> 
> Optional. Adds msvc appveyor support

On 2018-01-14 14:12:13 +0000,  wrote:

> Created attachment 3136
> 0002-CMakeLists.txt-sane-name-for-msvc-static-library.patch
> 
> sets library file names to libSDL2.dll, libSDL2.dll.a, and libSDL2.a for
> mingw-w64 and SDL2.dll, SDL2.lib, and libSDL2.lib for runtime, import
> and static libraries respectively

On 2018-01-14 14:12:49 +0000,  wrote:

> Created attachment 3137
> 0003-appveyor.yml-add-mingw-w64-build.patch
> 
> Adds appveyor support for mingw-w64 x86_64 builds, optional

On 2018-01-14 14:13:28 +0000,  wrote:

> Created attachment 3138
> 0004-CMakeLists.txt-generate-pkg-config-files-on-mingw.patch
> 
> Generates pkg-config files for mingw-w64 builds

On 2018-01-14 14:14:31 +0000,  wrote:

> Created attachment 3140
> 0005-CMakeLists.txt-better-leverage-GNUInstallDirs.patch
> 
> hardcodes less install destinations using GNUInstallDirs

**Comment by madebr** [comment]
The only thing not fixed in current master is the inconsistent naming of static libraries.
Using MSVC, when configuring using CMake with:
```
cmake -DSDL_SHARED=ON -DSDL_STATIC=ON
```
The dll import library is named: `SDL2.lib` and the static library `SDL2-static.lib`.

When configuring using:
```
cmake -DSDL_SHARED=OFF -DSDL_STATIC=ON
```
Suddenly, the static library is named `SDL2.lib`.
This can confuse people.

The patch in this issue proposes to rename the static library (only on MSVC) to `libSDL.a`, independent of the used cmake configuration options.

Because, personally, I feel like using `SDL2.lib` for an import library and using `libSDL2.lib` for a static library feels a bit arbitrary.
I would, on MSVC only, always name the import library `SDL2.lib` and the static library `SDL2-static.lib`.
This should make the distinction clear.

There is of course the risk that this will break people's projects if they don't use the CMake generate configuration files.

**Comment by slouken** [comment]
I'm fine with adding -static for the static library. I think that's been done ad-hoc by SDL users in the past and it makes sense to me.
