### ISSUE TITLE
No way to disable linking to libiconv

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2800]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to fix the problem - untested, please verify before applying! (x.txt, text/plain, 2018-01-17 09:44:22 +0000, 989 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3144)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-01-17 09:44:22 +0000, Rainer Deyke wrote:

> Created attachment 3144
> Patch to fix the problem - untested, please verify before applying!
> 
> Even though SDL works fine without libiconv, SDL insists on linking to libiconv if the configure script detects the libiconv development libraries installed.  Among other reasons, this is problematic because libiconv uses the LGPL license, which requires special care when linking to a project that cannot be open sourced.  There should be a configuration option to not use libiconv.

**Comment by madebr** [comment]
With CMake, use of the system libiconv library can be configured through the `SDL_SYSTEM_ICONV` cache variable.

https://github.com/libsdl-org/SDL/blob/27e8eb4ca8c98425311ddd7c057e309c730825f6/CMakeLists.txt#L394
