### ISSUE TITLE
cmake script doesn't honor CMAKE_INSTALL_{BIN,LIB,DATA{,ROOT},DOC,INCLUDE,...}DIR variables

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2805]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2018-01-20 15:55:25 +0000, Tiago O. wrote:

> It even includes GNUInstallDirs module, but doesn't make use of the extra variables it defines.
> 
> https://cmake.org/cmake/help/v3.10/module/GNUInstallDirs.html

On 2018-02-13 16:12:21 +0000, Sam Lantinga wrote:

> Do you have a tested patch that fixes this?
> 
> Thanks!

**Comment by icculus** [comment]
I _think_ we have since fixed this? Adding to 2.0.20 to check.
