### ISSUE TITLE
Make iOS build friendlier for consumption by Xamarin projects

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2806]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [A patch including the changes described in this ticket. (xamarin.diff, text/plain, 2018-01-20 20:04:46 +0000, 7695 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3148)

**Reported in version:** don't know
**Reported for operating system, platform:** iOS 11, iPhone/iPod touch

# Comments on the original bug report:

On 2018-01-20 20:04:46 +0000, Cole Campbell wrote:

> Created attachment 3148
> A patch including the changes described in this ticket.
> 
> The included patch makes the following changes, which are designed to make it easier to use SDL from a Xamarin iOS project:
> 
> 1. When the XAMARIN flag is defined as part of the build arguments, the main() function defined in SDL_uikitappdelegate.m is removed. The Xamarin runtime already defines a main() function, so this being present causes linker errors.
> 
> 2. When the SDL_DYNAMIC_MAIN flag is defined, the following new API functions are exposed:
> 
>  * SDL_SetDynamicMain()
>  * SDL_GetDynamicMain()
> 
> A C# application can use P/Invoke to pass a pointer to managed code into the SDL_SetDynamicMain() function; a simple replacement for the SDL_main function is included which will invoke this function at the necessary time.
> 
> The SDL_DYNAMIC_MAIN flag is automatically set when the XAMARIN flag is set and the target platform is iOS.

**Comment by icculus** [comment]
Let's see if this is still necessary and relatively trivial to resolve.

**Comment by TheSpydog** [comment]
This was effectively resolved last year with the addition of the SDL_MAIN_HANDLED preprocessor check in SDL_uikit_main: https://github.com/libsdl-org/SDL/commit/3a4b217d6c26df04f4afe05d5f0eec5edd14afef

Applications using different runtimes (like Xamarin) can build SDL with that flag enabled and use SDL_UIKitRunApp to initialize the app. This issue can be closed.
