### ISSUE TITLE
No mouse up event

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2819]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-02-07 19:34:01 +0000,  wrote:

> Initial conditions: window not focused.
> 
> Scenario:
>  move mouse in window
>  press left mouse button
>  drag mouse out of window 
>  release mouse button
> 
> Expected: get mouse button up event

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
