### ISSUE TITLE
CMake build process produces output that seems to confuse Xcode

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2841]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.6
**Reported for operating system, platform:** macOS 10.13, x86_64

# Comments on the original bug report:

On 2018-03-01 00:46:19 +0000, Tom Seddon wrote:

> The CMake build process produces the following output:
> 
>     message(STATUS "${LT_VERSION} :: ${LT_AGE} :: ${LT_REVISION} :: ${LT_CURRENT} :: ${LT_RELEASE}")
> 
> For some reason, don't ask me what, Xcode seems to interpret this as an error. This is a bit annoying when rebuilding the project after changing a CMakeLists.txt file. (And it doesn't have to be a change to the SDL one - any change to any CMakeLists.txt in any of the consuming projects seems to trigger this.)
> 
> I've changed my copy to produce the following output, which Xcode appears to treat as ordinary output:
> 
>     message(STATUS "LT_VERSION = ${LT_VERSION}; LT_AGE = ${LT_AGE}; LT_REVISION = ${LT_REVISION}; LT_CURRENT = ${LT_CURRENT}; LT_RELEASE = ${LT_RELEASE}")
> 
> This still isn't quite perfect. After changing my project's CMakeLists.txt, I do still usually have to build multiple times. (I don't think cmake's Xcode support is actually all that great, and of course Xcode is terrible to start with.) But at least this way I don't get a build error from SDL... just an "build cancelled" message, which is obviously bogus, since I didn't cancel the build.
> 
> --Tom

**Comment by slouken** [comment]
This status message has been removed.
