### ISSUE TITLE
DirectFB renderer cannot be enabled

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2859]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2018-04-02 06:56:15 +0000, Michael Hamann wrote:

> Due to change https://hg.libsdl.org/SDL/rev/d1ce8396c356#l1.22, the DirectFB renderer cannot be enabled anymore. As the change is otherwise totally unrelated, I assume this was not intentional. Fixing this should be trivial by reverting the affected line. This is a regression of 2.0.8 compared to 2.0.7. This breaks osk-sdl (https://github.com/postmarketOS/osk-sdl) and thus booting of postmarketOS (https://postmarketos.org) with full disk encryption.

On 2018-06-12 14:32:11 +0000, Guido wrote:

> Could it be that the removal of AC_DEFINE(SDL_VIDEO_RENDER_DIRECTFB, 1, [ ]) in configure.in is to blame for this?

On 2018-06-12 15:15:01 +0000, Michael Hamann wrote:

> Yes, I am sorry if this was not clear, this is exactly the line I have linked to. By "reverting the affected line" I mean re-adding that statement. I can confirm that re-adding that statement fixes this problem. I have also submitted a corresponding patch to Alpine Linux (https://github.com/alpinelinux/aports/pull/3889) with this fix that has been merged and successfully tested by other people from postmarketOS. As I have no Mac, I cannot test if this has any effect on the use of the Metal renderer (which has been introduced in the change where this line has been deleted).

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
