### ISSUE TITLE
CMake: Invalid symlink when building shared library with debug profile with 'd' suffix

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2861]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-04-03 18:41:51 +0000, Vitaly Novichkov wrote:

> When I building SDL2 in debug profile (CMAKE_BUILD_TYPE=Debug) and when I having 'd' suffix (results libSDL2-2.0d.so.0.8.0 file), the 'libSDL2.so' symbolic link still refer 'libSDL2-2.0.so' while actual target is 'libSDL2-2.0d.so'.

**Comment by Wohlstand** [comment]
This issue has been solved a while ago. Can anybody close this issue? @icculus, @sezero, @slouken

**Comment by sezero** [comment]
OK, closing.
