### ISSUE TITLE
Wrong touch input coords values

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2862]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2018-04-06 09:57:46 +0000,  wrote:

> event (from PollEvent) SDL_FINGERDOWN/SDL_FINGERMOTION doesn't return right values..
> Values are not normalized (the official guide shows values between 0 and 1) but negative values are also returned.
> 
> However, when the screen is in one place, the value returned is randomly wrong.
> 
> This bug occurs if the game / app texture is created with SDL_CreateTexture() and SDL_TEXTUREACCESS_STREAMING and if the texture is not fullscreen.
> So in this case for example ev.tfinger.x*nativeWidth are randomly wrong.
> 
> reference project: https://github.com/DCurrent/openbor
> files:
> https://github.com/DCurrent/openbor/blob/master/engine/android/jni/openbor/video.c
> https://github.com/DCurrent/openbor/blob/master/engine/sdl/control.c

On 2018-04-21 04:31:30 +0000,  wrote:

> I confirm the bug when use SDL_RenderSetLogicalSize()

On 2019-08-06 05:06:47 +0000, Kostyarezkiy wrote:

> This isn't a bug. You just need to multiply it by the screenwidth.
> 
> int Xclick = e.tfinger.x * SCREENWIDTH;//technically this is a float value, but we can make it int fine.
> int Yclick = e.tfinger.y * SCREENWIDTH;
> SDL_Log(" X %d  Y %d \n",Xclick , Yclick );

**Comment by 1bsyl** [comment]
just need to scale with SCREENWIDTH/ SCREENHEIGHT 
closing
