### ISSUE TITLE
EGL/OpenGL ES support is broken on Linux with X11 backend

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2863]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2018-04-07 10:40:55 +0000, Andrey Alexeyev wrote:

> First of all, the SDL_GL_CONTEXT_PROFILE_MASK attribute needs to be set before attempting to load the GL library in this configuration, since it determines whether to load libGLES or libGL. This is not obvious and not documented anywhere.
> 
> However, consider this ugly hack here: https://hg.libsdl.org/SDL/file/f1084c419f33/src/video/SDL_video.c#l213
> 
> This forces the library to load at the video driver initialization time, giving the application no chance to request a GLES context. It can be worked around by setting one of the hints that forces ShouldUseTextureFramebuffer to return early.

**Comment by icculus** [comment]
I think this works in modern times, but I'll check.
