### ISSUE TITLE
Moving the mouse when in relative mouse mode(SDL_SetRelativeMouseMode(SDL_TRUE)) moves back?

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2867]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-04-12 13:59:49 +0000,  wrote:

> When I enable the relative mouse mode using SDL_SetRelativeMouseMode(SDL_TRUE), when I look at reported mouse movement of e.g. moving the mouse down and right, I first see the correct mouse movement(1,1 xrel,yrel and increasing location in .x and .y event), but it's then oddly followed up by a second event reversing the previous one(the same xrel and yrel, but negative). The same kind of behaviour happens in both x and y redirections(negative followed by positive, or positive followed by negative)?
> 
> Is that supposed to happen? When setting SDL_SetRelativeMouseMode(SDL_FALSE), it behaves as normal(and works just fine), but moves the mouse around, which I don't want in my case(PC emulator using mouse input and keyboard input, capturing them for emulated input while hiding the mouse)?

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
