### ISSUE TITLE
Pulseaudio is not found during the configure when building 32 bit version of library

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2871]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-04-15 16:49:33 +0000, Roman wrote:

> I'm using a separate environment inside docker container to build 32-bit version of libsdl2.
> 
> Here's my Dockerfile:
> 
> FROM ubuntu:trusty
> RUN dpkg --add-architecture i386
> RUN apt-get update
> RUN apt-get install -y --no-install-recommends gcc-multilib make curl libasound2-dev:i386 libx11-dev:i386 libxext-dev:i386 libgl1-mesa-dev libxrandr-dev:i386 libpulse-dev:i386
> RUN curl -s http://libsdl.org/release/SDL2-2.0.7.tar.gz | tar xzf -
> WORKDIR /SDL2-2.0.7
> ENV CC="gcc -msse2 -march=i686 -m32 -ggdb -O2"
> RUN ./configure \
> 	--disable-dependency-tracking \
> 	--enable-audio \
> 	--enable-video \
> 	--enable-events \
> 	--disable-render \
> 	--enable-joystick \
> 	--disable-haptic \
> 	--disable-power \
> 	--enable-threads \
> 	--enable-timers \
> 	--enable-loadso \
> 	--enable-video-opengl \
> 	--enable-x11-shared \
> 	--enable-video-x11 \
> 	--enable-video-x11-xrandr \
> 	--enable-video-x11-scrnsaver \
> 	--enable-video-x11-xinput \
> 	--disable-video-x11-xshape \
> 	--disable-video-x11-xdbe \
> 	--disable-libudev \
> 	--disable-dbus \
> 	--disable-ibus \
> 	--enable-sdl-dlopen \
> 	--disable-video-opengles \
> 	--disable-cpuinfo \
> 	--disable-assembly \
> 	--disable-atomic \
> 	--enable-alsa-shared \
> 	--enable-pulseaudio-shared
> 
> However during the configure phase it says
> 
> checking for PulseAudio 0.9 support... no
> 
> And it ends up not including pulseaudio in the build:
> 
> Audio drivers   : disk dummy oss alsa(dynamic)
> 
> libpulse-simple is present and ldconfig can find it:
> 
> ldconfig -p | grep pulse
>         libpulse.so.0 (libc6) => /usr/lib/i386-linux-gnu/libpulse.so.0
>         libpulse.so (libc6) => /usr/lib/i386-linux-gnu/libpulse.so
>         libpulse-simple.so.0 (libc6) => /usr/lib/i386-linux-gnu/libpulse-simple.so.0
>         libpulse-simple.so (libc6) => /usr/lib/i386-linux-gnu/libpulse-simple.so
>         libpulse-mainloop-glib.so.0 (libc6) => /usr/lib/i386-linux-gnu/libpulse-mainloop-glib.so.0
>         libpulse-mainloop-glib.so (libc6) => /usr/lib/i386-linux-gnu/libpulse-mainloop-glib.so

**Comment by icculus** [comment]
Surely this was fixed at some point since 2018, or this was a misconfigured end-user's system, since the Steam Runtime has a 32-bit SDL with Pulse support.
