### ISSUE TITLE
Can't build SDL2 for iOS using

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2872]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Build Error (Screenshot 2018-04-15 16.14.48.png, image/png, 2018-04-15 23:33:34 +0000, 58028 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3222)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Mac OS X 10.11, x86_64

# Comments on the original bug report:

On 2018-04-15 23:33:34 +0000, Steve Robinson wrote:

> Created attachment 3222
> Build Error
> 
> Reproduction steps:
> 
> 1. Untar SDL2-2.0.8.tar.gz source archive
> 2. In Mac OS X Finder program, open the source folder and go to Xcode-iOS/SDL
> 3. Double-click on SDL.xcodeproj to open it in Xcode
> 4. In Xcode, go to Product > Build
> 
> Build fails.  The errors are in the attached screen shot.
>
> ![image](https://github.com/libsdl-org/SDL/assets/673562/e21b28e7-a096-401e-96ca-73c40494737c)
>
> When I perform these steps with the SDL2-2.0.7.tar.gz source archive, it builds fine.
> 
> I'm using Xcode 8.2.1 (8C1002) with Mac OS X 10.11.6 (El Capitan) on a MacBook Pro 13" Mid 2009.  I'm on the newest Xcode/OS X that's supported for this laptop.
> 
> I looked in docs/README-ios.md and it didn't indicate that I'm using unsupported software.

**Comment by icculus** [comment]
We clearly fixed this at some point.
