### ISSUE TITLE
fullscreen_width and fullscreen_height variables are ignored

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2873]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [fullscreen_width and fullscreen_height should limit the game picture size like this but they don't. (16-10 spherical powerup_with_bb.png, image/png, 2018-04-18 10:43:37 +0000, 510347 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3225)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2018-04-18 10:43:37 +0000,  wrote:

> Created attachment 3225
> fullscreen_width and fullscreen_height should limit the game picture size like this but they don't.
> 
> I set the fullscreen_width to 1728 and fullscreen_height to 1080 in Chocolate Doom config file and expected the game to be rendered fullscreen with black bars on the sides as my monitor is 1920x1080 (like in the provided screenshot), but the picture was stretched full screen instead.

On 2018-05-09 16:48:56 +0000, Fabian Greffrath wrote:

> I should probably provide some more context to this (Chocolate Doom dev).
> 
> Usually, if a user chooses to play the game in fullscreen, we set the SDL_WINDOW_FULLSCREEN_DESKTOP flag, because we assume the player wants to keep his desktop resolution and simply have the game cover the whole screen.
> 
> However, there are two variables, fullscreen_width and fullscreen_height, which the user may set in the config file to express that he wants to play the game in fullscreen *in a specific screen resolution*. In that case, we set the SDL_WINDOW_FULLSCREEN flag, instead. Later on, we pass the width and height variables along with the flags to SDL_CreateWindow().
> 
> What we expect from this function in the latter case is to switch the screen to the given resolution - or the next highest one and and render the game in a centered area of the given dimensions surrounded by a black border.
> 
> The code which is supposed to do what I just described can be found here:
> 
> https://github.com/chocolate-doom/chocolate-doom/blob/master/src/i_video.c#L1145
> 
> 
> However, we had reports from a Windows user that this doesn't work as intended. The downstream bug report is here:
> 
> https://github.com/chocolate-doom/chocolate-doom/issues/1010
> 
> I can confirm it doesn't work as described on Linux with Wayland as well, whereas another user reported the feature to work on a Mac.
> 
> Hope you can get after it!
> 
> Best regards,
> 
>  - Fabian

**Comment by flibitijibibo** [comment]
Not sure about Windows, but I can confirm that Wayland is technically working as intended since SDL_WINDOW_FULLSCREEN is totally unsupported there and is intentionally not part of the protocol. I believe it returns -1 if you try, but this should be re-tested.

**Comment by slouken** [comment]
@fabiangreffrath, is this still active?

**Comment by fabiangreffrath** [comment]
Yes, this still seems to be valid. If (1) a window is created with the `SDL_WINDOW_FULLSCREEN` flag, and (2) the `w` and `h` variables passed to `SDL_CreateWindow()` do not match a valid screen mode, and (3) if `SDL_RenderSetLogicalSize()` is *not* called for the window's renderer, then the next highest video mode is selected and the screen content is stretched to screen instead of being rendered into a centered area on screen using the `w` and `h` dimensions.

**Comment by slouken** [comment]
This is expected, you can request a fullscreen mode, but you must either check to see what is actually available or use SDL_RenderSetLogicalSize() to set a logical size for your content.
