### ISSUE TITLE
GDK SCALE leads to wrong resolution in wayland

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2879]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-04-21 19:54:59 +0000, Fabian wrote:

> Setting up GNOME in HiDPI mode (GDK_SCALE=2) and now launching a sdl2 using game with it's wayland backends leads to a 2x greater resoltion.
> 
> So Windows that are rendered for a 1920*1080 resolution will be streched to 3849*2160. While this sounds logical, it isnt. The content is just streched, rendered in 1920*1080.

On 2018-10-27 21:03:42 +0000, Sebastian Krzyszkowiak wrote:

> Basically there is no HIGHDPI support in the Wayland backend at all - it's implemented only in macOS, iOS and Emscripten ones so far.

**Comment by flibitijibibo** [comment]
This should be retested - we do support high-DPI for Wayland now and it works on my setups, but I don't know if GDK_SCALE=2 behaves differently from GNOME's 200% option in their graphical Settings app. If it's the same, this should be fixed now.

**Comment by flibitijibibo** [comment]
Researched this some more and I think this is now technically NOTABUG - Wayland high DPI does respect the desktop settings and/or GDK_SCALE, but doing both messes with programs all over, so it's not unique to SDL here. With high DPI implemented in Wayland now, we shouldn't require any further intervention than is necessary to use any other program.
