### ISSUE TITLE
android joystick compatibility. no controller work!!

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2890]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Android (All), x86

# Comments on the original bug report:

On 2018-05-06 01:31:00 +0000,  wrote:

> android joystick compatibility. no controller work!!
> for some joystick no working d-pad/axis..
> for others no working buttons..
> 
> tested on all android API and HW x86

On 2018-05-10 22:17:35 +0000,  wrote:

> Also for some joysticks no response from axis and/or buttons..

On 2018-11-14 19:41:12 +0000, Sam Lantinga wrote:

> This should be fixed in SDL 2.0.9, can you confirm?
> http://www.libsdl.org/download-2.0.php

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
