### ISSUE TITLE
Retrieve Android Joystick Hats

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2893]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Android (All), x86

# Comments on the original bug report:

On 2018-05-10 14:30:44 +0000,  wrote:

> For many joystick there is a bug for:
> SDL_JoystickNumHats() that return 0 hats
> and that SDL_JoystickGetHat() that it doesn’t work…
> On windows it seems working well...

On 2018-05-10 22:17:48 +0000,  wrote:

> Also for some joysticks no response from axis and/or buttons..

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
