### ISSUE TITLE
Text Input is active by default

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2897]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-05-11 20:22:25 +0000, Bram Stolk wrote:

> Text Input is active by default.
> This is not mentioned in the Wiki documentation.
> 
> Text Input causes 2ms spikes for each key-press.
> 
> Write up here:
> http://thelittleengineerthatcould.blogspot.ca/2018/05/the-curious-case-of-fps-jitter.html
> 
> At the very least, documentation should be fixed to mention this.
> 
> Or better, Text Input mode should not be active by default.
> 
> Ubuntu 18.04
> SDL 2.0.8

On 2018-10-17 19:55:34 +0000, Linus Probert wrote:

> Nice post. I was not aware of this but I've been wondering over the "jitter" you mentioned which I'm quite sure I've been affected by.
> 
> Not my place to say, but the offending line is in SDL_video.c:568 (current code).
> 
> The comment above suggests that this is intended so perhaps the documentation should be updated:
> 
> ---
>     /* If we don't use a screen keyboard, turn on text input by default,
>        otherwise programs that expect to get text events without enabling
>        UNICODE input won't get any events.
> 
>        Actually, come to think of it, you needed to call SDL_EnableUNICODE(1)
>        in SDL 1.2 before you got text input events.  Hmm...
>      */
>     if (!SDL_HasScreenKeyboardSupport()) {
>         SDL_StartTextInput();
>     }
> ---

**Comment by slouken** [comment]
We should revisit whether text input is automatically enabled for SDL 3.0

**Comment by icculus** [comment]
I think this got revisited, can this bug be closed?

**Comment by slouken** [comment]
Yep!
