### ISSUE TITLE
Sharing resources via wglShareLists (i.e. SDL_GL_ShareLists)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2899]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows (All), All

# Comments on the original bug report:

On 2018-05-13 17:23:14 +0000, Charles Van Noland wrote:

> With the existing functionality added that separated out the window handling from the GL rendering contexts it would be nice to be able to apply that to multithreaded resource generation (i.e. generating mesh vertex buffers, textures, etc) but this requires that a 2ndary rendering context interacted with by worker threads be able to generate resources and upload them to the GPU for the rendering context on the main thread to use for rendering. By default OpenGL does not share resources across rendering contexts within a program, this must be accomplished via wglShareLists (on Windoze systems) and there's nothing in SDL currently wrapping it, so users are forced to include OS-specific code in their SDL program in order to share GL resources between contexts.

On 2018-11-11 01:27:23 +0000, Alex Szpakowski wrote:

> Does SDL_GL_SetAttribute(SDL_GL_SHARE_WITH_CURRENT_CONTEXT, 1) work for you when creating the second context?

**Comment by slime73** [comment]
I think this issue can be closed - `SDL_windowsopengl.c` calls `wglShareLists` if `SDL_GL_SHARE_WITH_CURRENT_CONTEXT` is set.
