### ISSUE TITLE
Screen width and height reported by SDL_GetCurrentDisplayMode changes after SDL_CreateWindow is called on iPad

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2927]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** iOS 8, iPhone/iPod touch

# Comments on the original bug report:

On 2018-06-09 23:37:03 +0000, Steve Robinson wrote:

> On my iPad simulator (Xcode 9.4) and iPad hardware, I noticed that SDL_GetCurrentDisplayMode(0, &current) reported these screen width and height values before SDL_CreateWindow is called:
> 
> current.w=320
> current.h=480
> 
> And these after:
> 
> current.w=768
> current.h=1024
> 
> These numbers did not change on iPhone simulator or hardware, nor did they change on Windows, Linux, Mac or Android.
> 
> I tracked the change down to UIKit_GetDisplayModes.  Here's the call stack:
> 
> SDL_CreateWindow(const char *title, int x, int y, int w, int h, Uint32 flags)
>   SDL_FinishWindowCreation(window, flags);
>     SDL_SetWindowFullscreen(window, flags); - w and h get zeroed out here
>     SDL_ShowWindow(window);
>       SDL_SendWindowEvent(window, SDL_WINDOWEVENT_SHOWN, 0, 0);
>         SDL_OnWindowShown(window);
>           SDL_OnWindowRestored(window);
>             SDL_UpdateFullscreenMode(window, SDL_TRUE);
>               SDL_GetWindowDisplayMode(other, &fullscreen_mode)
>                 SDL_GetClosestDisplayModeForDisplay(SDL_GetDisplayForWindow(window),
>                                              &fullscreen_mode,
>                                              &fullscreen_mode)
>                   SDL_GetNumDisplayModesForDisplay(display)
>                      _this->GetDisplayModes(_this, display)
>                        UIKit_GetDisplayModes(_THIS, SDL_VideoDisplay * display)
> 
> In my program, I simply made sure I only called SDL_GetCurrentDisplayMode once to get consistent behavior across all platforms.  Still, it was really confusing and I spent a lot of time messing with it so I figured I should log a bug.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
