### ISSUE TITLE
testautomation_hints "verbose" values seem wrong

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2938]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch proposal (testautomation_hints.patch, text/plain, 2018-07-05 09:47:16 +0000, 2076 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3269)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-07-05 09:47:16 +0000, Juha Niemimäki wrote:

> Created attachment 3269
> Patch proposal
> 
> It seems to me that there is extra "HINT_" in each "verbose" string, please see include/SDL_hints.h for comparison.

**Comment by capehill** [comment]
It seems this has been fixed and can be closed.

https://github.com/libsdl-org/SDL/commit/94a42af57088efb1f336059dc79fe6ad2da37888
