### ISSUE TITLE
[PATCH] Fix for SDL_CreateWindowFrom that doesn't initialize OpenGL properly on Windows

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2942]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch for SDL 2.0.8 that fix OpenGL with SDL_CreateWindowFrom (windowfrom_opengl.patch, text/plain, 2018-07-18 20:11:01 +0000, 1794 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3272)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows (All), All

# Comments on the original bug report:

On 2018-07-18 20:11:01 +0000, Michael Larouche wrote:

> Created attachment 3272
> Patch for SDL 2.0.8 that fix OpenGL with SDL_CreateWindowFrom
> 
> We use SDL_CreateWindowFrom in our in-house game editor to embed our C++ game engine using a child HWD created by our C# WPF editor. We use OpenGL for rendering and when I developed the embedding, I noticed that OpenGL wasn't initialized properly when using SDL_CreateWindowFrom, the OpenGL extensions weren't there and the effective OpenGL version was 1.1, not 4.x that my video card can support.
> 
> This patch included in this bug report fix the issue. Since there's no way to specify the SDL_Window flags when using SDL_CreateWindowFrom, I had to hardcode SDL_WINDOW_OPENGL.
> 
> Let me know if you want the patch to be based on the upstream Mercurial repository.

**Comment by icculus** [comment]
Obviously we can't just hardcode `SDL_WINDOW_OPENGL` into all windows generated by SDL_CreateWindowFrom, but we could add a hint if nothing else.

**Comment by flibitijibibo** [comment]
I ended up accidentally doing the same thing, but for Vulkan: #5338
