### ISSUE TITLE
Append EGL CFLAGS before AC_TRY_COMPILE in "Find OpenGL ES"

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2965]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Append EGL CFLAGS before AC_TRY_COMPILE in "Find OpenGL ES" (0001-sdl-2.0.8-add-egl-cflags-to-test.patch, text/plain, 2018-08-31 20:49:12 +0000, 1687 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3291)
* [alternative EGL_FLAGS patch (1a.patch, text/plain, 2018-09-06 15:33:10 +0000, 4643 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3298)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-08-31 20:49:12 +0000, Sergey Zhuravlevich wrote:

> Created attachment 3291
> Append EGL CFLAGS before AC_TRY_COMPILE in "Find OpenGL ES"
> 
> Append EGL CFLAGS before AC_TRY_COMPILE in "Find OpenGL ES" section of configure.in. On some configurations the compiler check might fail without include paths from these CFLAGS.

On 2018-09-06 15:33:10 +0000, Ozkan Sezer wrote:

> Created attachment 3298
> alternative EGL_FLAGS patch
> 
> PKG_CONFIG stuff is still handled without use of pkg.m4 in SDL configury
> so I cooked the attached alternative quick patch: does it work correctly
> for you?

**Comment by slouken** [comment]
@madebr, we don't need this patch, right?

**Comment by madebr** [comment]
Seen the lack of build issues using autotools on Linux, no.
