### ISSUE TITLE
Render API shouldn't check if window is hidden

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2979]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2018-09-17 05:26:19 +0000, Ryan C. Gordon wrote:

> I assume this change was made for iOS, seven years ago...
> 
> https://hg.libsdl.org/SDL/rev/59d398ac031e
> 
> ...in recent revisions, these check if the window is "hidden" instead of minimized, but I'm wondering if these should be removed.
> 
> Apps on iOS should catch the event telling them the process went to the background and should stop drawing on their own in that case, like they would have to do if they used OpenGL directly instead of SDL's renderer, and having these checks here means that a minimized window on any platform that's rendering to a render target will end up with a blank texture that might be meant to persist for long past a single frame.
> 
> As I'm reworking the render API to batch up draw commands, there are further questions about when and if we should abort drawing like this.
> 
> The downside of removing this check is that an iOS app in the background that tries to call SDL_Render*() will crash, but I'd argue that was a bug in their app. They shouldn't be doing serious work in the background, including running their rendering loop, whether we prevent the actual rendering calls or not.
> 
> Can I remove these "/* Don't draw while we're minimized */" checks? We can definitely keep the glFinish() call on backgrounding, if that's helpful to iOS, though.
> 
> --ryan.

On 2018-09-17 05:57:18 +0000, Sam Lantinga wrote:

> The problem is that iOS enforces the "no rendering" policy immediately, but the app may not receive the notification that they should stop rendering until later. I'm fine with making that an iOS and Android only check though, if that's helpful.

**Comment by icculus** [comment]
Gonna revive this, and #ifdef these checks to be iOS/Android only. Reference conversation:

https://discourse.libsdl.org/t/can-you-renderpresent-when-another-fullscreen-application-is-running/28915/2
