### ISSUE TITLE
Implement missing features of SDL_vsnprintf, namely string width & precision

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2982]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [patch for string.c (string.patch, text/plain, 2018-09-25 20:53:32 +0000, 2245 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3312)
* [patch implementing precision for the integral value printers (string_2.patch, text/plain, 2018-09-26 17:09:36 +0000, 1822 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3316)
* [tests (tests.zip, application/zip, 2018-09-28 22:43:49 +0000, 2750 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3330)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2018-09-20 01:57:08 +0000, Anthony @ POW Games wrote:

> The precision and width of strings is ignored. There's todo in the source code that mentions this is missing. Can it be implemented pretty please? 
> 
> I'm trying to use "%.*s" where I specify a width using a parameter, but it's ignored. Even  "%.8s" doesn't work.

On 2018-09-24 23:34:26 +0000, Sam Lantinga wrote:

> Hey Ozkan, do you want to take a look at this?

On 2018-09-25 06:18:21 +0000, Ozkan Sezer wrote:

> Will try looking (no promises or an ETA.)

On 2018-09-25 20:53:32 +0000, Ozkan Sezer wrote:

> Created attachment 3312
> patch for string.c
> 
> Here is an initial patch for string.c which does the following:
> 
> - make %.* correctly parse precision.
> - make %* correctly parse width.
> - make string printer honor the precision.
> 
> Minimally tested, so please review carefully and test carefully.

On 2018-09-25 20:58:45 +0000, Ozkan Sezer wrote:

> For the record, I tested the patch using the following minimal C code
> on Linux:
> 
> #include <stdio.h>
> #include "SDL.h"
> 
> char foo[] = "abcdefghi";
> char bar[64];
> int main (void) {
>   printf("%.*s\n",6,foo);
>   printf("%.6s\n",foo);
> 
>   printf("%10.*s\n",6,foo);
>   printf("%*.6s\n",10,foo);
> 
>   SDL_snprintf(bar,sizeof(bar),"%.*s",6,foo);
>   printf("%s\n",bar);
>   SDL_snprintf(bar,sizeof(bar),"%.6s",foo);
>   printf("%s\n",bar);
> 
>   SDL_snprintf(bar,sizeof(bar),"%10.*s",6,foo);
>   printf("%s\n",bar);
>   SDL_snprintf(bar,sizeof(bar),"%*.6s",10,foo);
>   printf("%s\n",bar);
> 
>   return 0;
> }

On 2018-09-26 03:16:10 +0000, Sam Lantinga wrote:

> Offhand it looks good. Could you also implement them for the numeric print formatters?
> 
> Thanks!

On 2018-09-26 07:46:05 +0000, Ozkan Sezer wrote:

> > Offhand it looks good.
> 
> I pushed the existing patch in two parts with slight modification:
> https://hg.libsdl.org/SDL/rev/4cbf7e663cb2
> https://hg.libsdl.org/SDL/rev/3c5adcfe014e
> 
> > Could you also implement them for the numeric print formatters?
> 
> OK, not closing this yet and will look.

On 2018-09-26 17:09:36 +0000, Ozkan Sezer wrote:

> Created attachment 3316
> patch implementing precision for the integral value printers
> 
> (In reply to Sam Lantinga from comment # 5)
> >  Could you also implement them for the numeric print
> > formatters?
> 
> Attached patch implements precision for integral value printers.
> It might not be the most efficient, but it seems to do the job.
> 
> It also _fixes_ it because, without this, SDL_PrintString() makes
> a mess now that it honors precision for strings, and the integral
> value printers do call SDL_PrintString().
> 
> Please review.
> 
> Will look at float value printing later.

On 2018-09-26 21:02:24 +0000, Sam Lantinga wrote:

> This is missing check for maxlen, but otherwise looks good. Thanks!

On 2018-09-26 21:35:35 +0000, Ozkan Sezer wrote:

> Applied with maxlen checking added:
> https://hg.libsdl.org/SDL/rev/d3b8ea488be8
> 
> Please review / test this final state: if all good, then
> let's close this.
> 
> As for float prints, there already is precision handling
> in there AFAICS (looked only briefly), so I won't touch
> it unless something is actually wrong with it.

On 2018-09-27 06:45:41 +0000, Ozkan Sezer wrote:

> Anthony:  Had you a chance to test the latest code in hg?

On 2018-09-27 18:21:31 +0000, Anthony @ POW Games wrote:

> I don't know how to compile from source for Windows, but I managed to test the latest hg on Android and yes, all appears ok, in so far as "*" width for strings. 
> 
> I haven't done an extensive test of all the features though. Would you like me to try to break it to make sure it's solid before closing this?
> 
> Thanks for pulling together to get this working - impressive. I should try to contribute code in the future, but I don't feel worthy :-|

On 2018-09-27 18:27:12 +0000, Ozkan Sezer wrote:

> (In reply to Anthony @ POW Games from comment # 11)
> > I don't know how to compile from source for Windows,
> 
> Sam: can we point to a buildbot windows build for him?
> 
> 
> >  but I managed to test
> > the latest hg on Android and yes, all appears ok, in so far as "*" width
> > for strings. 
> 
> Assuming Android is configured without HAVE_LIBC, then this is good.
> 
> > I haven't done an extensive test of all the features though. Would you
> > like me to try to break it to make sure it's solid before closing this?
> 
> No need, I guess, but would be interesting to see such a report.
> (Not every single feature of vsnprintf() is really implemented in
> there, so it shouldn't be hard to break.)
> 
> > Thanks for pulling together to get this working
> 
> You're welcome.

On 2018-09-27 21:53:57 +0000, Sam Lantinga wrote:

> We don't have the buildbot builds accessible right now, but I'm going to put up an RC build this weekend and he can check it out there.

On 2018-09-28 11:12:43 +0000, Ozkan Sezer wrote:

> Anthony:  there are 2.0.9 prerelease builds here, which include
> the SDL_vsnprintf() updates:
> http://www.libsdl.org/tmp/download-2.0.php
> 
> You can use them to test on windows.

On 2018-09-28 12:56:35 +0000, Anthony @ POW Games wrote:

> That's awesome, thank you. I'll try them out now. I have some issues with the latest Android build not running on Android 4.2.2 (anything pre-Kitkat I suspect). And issues with the joysticks on Android being opened as keyboards and some keyboards being opened as joysticks (the HUD stuff seems to have made things worse). I'll open bugs repots when I know more. 
> 
> Do I need to close this if it's ok, or can anyone?

On 2018-09-28 14:06:21 +0000, Ozkan Sezer wrote:

> (In reply to Anthony @ POW Games from comment # 15)
> > Do I need to close this if it's ok, or can anyone?
> 
> You can close it if things are OK.

On 2018-09-28 18:08:06 +0000, Anthony @ POW Games wrote:

> Just noticed the "+" flag isn't implemented for integers (this forces a + or - to be written, regardless). That's the only thing I've noticed so far for SDL_vsnprintf whiles testing 2.0.9 with my game.

On 2018-09-28 18:36:25 +0000, Ozkan Sezer wrote:

> (In reply to Anthony @ POW Games from comment # 17)
> > Just noticed the "+" flag isn't implemented for integers (this forces a + or
> > - to be written, regardless). That's the only thing I've noticed so far for
> > SDL_vsnprintf whiles testing 2.0.9 with my game.
> 
> Sam:  Do we want the '+' flag for 2.0.9, or leave it for later times?

On 2018-09-28 18:49:34 +0000, Anthony @ POW Games wrote:

> Include it in 2.0.9, please. Else I will need to use stdio's version - I can ditch stdio entirely if this works.
> 
> I'm having a few issues with 2.0.9 on Android. Let me raise them before roll-out.

On 2018-09-28 21:51:36 +0000, Ozkan Sezer wrote:

> Pushed a fix after the width / precision updates that had gone in:
> https://hg.libsdl.org/SDL/rev/2dbf011db466

On 2018-09-28 22:25:54 +0000, Ozkan Sezer wrote:

> Well, I went ahead and implemented '+' for signed integers printing:
> https://hg.libsdl.org/SDL/rev/f1ac9de30ee1
> 
> Can we close this now?

On 2018-09-28 22:43:49 +0000, Ozkan Sezer wrote:

> Created attachment 3330
> tests
> 
> FWIW, here are the tests I used myself when working with this.

On 2018-09-29 01:43:14 +0000, Anthony @ POW Games wrote:

> I wonder if it's necessary to "info.force_sign = SDL_FALSE;" for unsigned? But otherwise looks good. Many thanks.

**Comment by howprice** [comment]
Hi. `SDL_PrintString` ignores `SDL_FormatInfo.left_justify` it did this in SDL2 and I was hoping it would be fixed in SDL3, but it looks like it is the same code. I'm trying to apply formatting with fixed width strings, for example:

```
sprintf(buffer, sizeof(buffer), "    %-14s%s,%s", mnemonic, srcOperand, dstOperand);
```

Are there any plans to fix this? Should I open a new issue?

**Comment by slouken** [comment]
> Hi. `SDL_PrintString` ignores `SDL_FormatInfo.left_justify` it did this in SDL2 and I was hoping it would be fixed in SDL3, but it looks like it is the same code. I'm trying to apply formatting with fixed width strings, for example:
> 
> ```
> sprintf(buffer, sizeof(buffer), "    %-14s%s,%s", mnemonic, srcOperand, dstOperand);
> ```
> 
> Are there any plans to fix this? Should I open a new issue?

Go ahead and open a new issue, and feel free to take a crack at a fix that works for you!
