### ISSUE TITLE
Japanese IME on Windows 10 makes invisible window over fullscreen game, StopTextInput no effect

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2997]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-09-29 15:55:08 +0000, Bart van der Werf wrote:

> When in fullscreen on windows 10 (no reproduction on windows 7 in testing) when triggering Hiragana input mode using japanese IME windows shortcuts (alt-tilde) or Japanese 109 layout metakeys causes an invisible window to be placed over the center of the game, causing a mouse click in that area to minimize the game and other input weirdness.
> 
> I could not find documentation on how to suppress ime input to allow WASD input without composing to happen.
> 
> StopTextInput had no effect.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
