### ISSUE TITLE
Request for Nintendo Switch Joy Con support

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3003]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2018-10-02 16:26:12 +0000,  wrote:

> The analog sticks on the joy cons for Nintendo Switch only registers the direction, and not the analog values. Everything else, as far as I know, works fine. If it's possible, please add support for this. Thanks.
> 
> I'm sorry if this report is too vague. This is the first time I've reported something like this.

On 2019-05-18 18:48:55 +0000, Ryan C. Gordon wrote:

> 
> Tagging a bunch of bugs with "target-2.0.10" so we have a clear list of things to address before a 2.0.10 release.
> 
> Please note that "addressing" one of these bugs might mean deciding to defer on it until after 2.0.10, or resolving it as WONTFIX, etc. This is just here to tell us we should look at it carefully, and soon.
> 
> If you have new information or feedback on this issue, this is a good time to add it to the conversation, as we're likely to be paying attention to this specific report in the next few days/weeks.
> 
> Thanks!
> 
> --ryan.

On 2019-05-19 18:34:48 +0000, Sam Lantinga wrote:

> Can you try the latest SDL snapshot?
> http://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by icculus** [comment]
@slouken just did a ton of work on Joy-Cons for 2.22.0, so I believe this to be resolved now.
