### ISSUE TITLE
Please make SDL_image|mixer|ttf|net first class citizen

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3004]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2018-10-03 12:25:27 +0000, David Demelier wrote:

> Hello,
> 
> When looking at the website nobody can reach SDL_image|mixer|ttf|net page even in download section. People that do not know SDL could not see there is some addons. We can think that official SDL addons are not first class values.
> 
> 1. We should add official links to Download section,
> 2. We should add documentation on the wiki.

**Comment by icculus** [comment]
(I think this was @markand's bugzilla report before, if you want to follow along.)

# Wiki stuff...

So I'm going to adjust ghwikipp to handle subdirectories, so SDL_mixer pages are all grouped together...

```
https://wiki.libsdl.org/SDL_mixer/Mix_OpenAudio
```

...this will leave the git repo of pages nice and organized, and help with our various utility scripts that want to iterate over a single directory for all pages associated with a single project.

If that's annoying, we can have the PHP code look for pages across all subdirs and either jump to the correct one or show a disambiguation page if the same file is in multiple places, but this seems like unnecessary complexity.

This will make it possible to _publish_ pages for these projects, and also generate offline documentation, etc.

Then we'll get the headers of these projects up to spec so we can bridge them to the wiki like we already do for SDL, generate manpages, etc.


# Webpage stuff...

I think we should probably just redirect the existing project pages to their GitHub project page, where we make sure there's a robust README.md for each, and not maintain these as pages on [libsdl-org/sdlweb](https://github.com/libsdl-org/sdlweb) anymore.

I have sort of a love/hate relationship with the satellite libraries, so I'm not big on presenting them as first-class citizens. I like to think of them as possibly-useful, but easy to disavow when better options come along (looking at you, SDL_net...plus the rest of the planet has already forgotten SDL_rtf, etc). If we're going to link them somewhere prominent, I'd really like it to include some sentiment like "we wrote these but they are **optional** and **external** libraries that are **separate** from SDL." But that's just me.

**Comment by icculus** [comment]
ghwikipp fixes are in and live on the site now. So you can go to:

https://wiki.libsdl.org/SDL_mixer/SomePageNameOrWhatever

And create it, edit, etc. Subdirectories can't be added without admin intervention, so for now SDL_mixer is the only one while I experiment. I'll add the rest when it makes sense to do so.

SDL's build-scripts/wikiheaders.pl _mostly_ works already, but needs some improvements to generalize it for external projects. I might try to knock that out tomorrow if it won't take long.

Most of these libraries' headers are nowhere close to our needs at the moment; SDL_mixer is pretty well-commented but needs heavy reformatting to get the benefits of the wikiheaders.pl bridge, SDL_image is severely under-documented, etc. This is going to take a lot of effort to do well, but we can likely get it to the limping-along stage pretty quickly and just make tweaks over time...this _is_ what a wiki is good at, after all!

SDL/build-scripts/fnsince.pl is probably a total loss outside of SDL itself, but these external libraries haven't had many significant API additions in a long time, so it's probably safe to manage these manually.

**Comment by slouken** [comment]
If you let me know what changes need to be done to the headers, I can go through and update the formatting pretty quickly.

**Comment by icculus** [comment]
> If you let me know what changes need to be done to the headers, I can go through and update the formatting pretty quickly.

I updated one function in SDL_mixer as an example:

https://github.com/libsdl-org/SDL_mixer/commit/6fe6a3733b5db15cfa58f8f755dd90c9aa206558

Basically:
- It has to start with a Doxygen comment ( `/**` ) or it is ignored completely.
- The first line is a brief summary sentence, which is treated specially by both Doxygen and wikiheaders.pl. Keep it separate from other paragraphs.
- The formatting in the headers is Markdown, so things like these parentheses...
  ```
  (variablename)
  ```
  ...became backticks...
  ```
  `variablename`
  ```
- Added `\param` and `\returns` as essential information. Moved some stuff out of the "returns" section to general notes.
- (optionally) add `\sa` ("see also") fields
- Added a `\since` field; these probably go way back before 2.0.0, but I don't know the specifics.

The first time wikiheaders runs over this, it'll adjust the wordwrapping to be 80-column friendly and align things correctly in paragraph blocks, so don't worry too much about that.

There are probably other subtle details we'll fix as we go, but this is 95% of the cleanup work.

For more examples, look at almost any function in SDL's headers.

**Comment by icculus** [comment]
SDL/build-scripts/wikiheaders.pl is updated to deal with external projects. You can see I added this (somewhat mysterious) file to SDL_mixer, so the script will do the right project-specific things when pointed at the SDL_mixer source tree:

https://github.com/libsdl-org/SDL_mixer/commit/ab8301a2c7e201d833808ca9ac132aac8150f870

The SDL_mixer one turns on the option to complain about missing documentation for functions it sees, which is useful for a small project like this where the goal is to iterate through and fix up/document every function. For SDL itself, we don't currently turn that on so we don't have to deal with all the things like SDL_stdinc.h

To use: clone SDL, SDL_mixer, sdlwiki, and run:

```bash
./SDL/build-scripts/wikiheaders.pl SDL_mixer sdlwiki --copy-to-wiki
```

And then look at the output and what files it created/overwrote in sdlwiki/SDL_mixer/

And then just start iterating on it by editing the headers and checking the output.

**Comment by icculus** [comment]
Okay, a first-pass over all of SDL_net is done, and the bidirectional wiki bridge is up and running! Edit the headers or wiki and it'll show up in the other place!

Which means this can be enabled for other libraries now, once we're ready.

Lots of fixes to make this work.  :)

**Comment by slouken** [comment]
Awesome, thanks!

**Comment by icculus** [comment]
So all the satellite libraries are updated; we just need to either have the project pages point to the wiki for documentation, or have the project pages just redirect to the GitHub repo main pages. Either is fine with me. @slouken, which do you prefer?

**Comment by slouken** [comment]
The project pages are now pointing at GitHub.
