### ISSUE TITLE
Android : wrong size reported when not in fullscreen.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3011]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Android (All), All

# Comments on the original bug report:

On 2018-10-07 13:34:36 +0000, Sylvain wrote:

> Android seems to be hardcoded in fullscreen.
> 
> Changeset https://hg.libsdl.org/SDL/rev/6de756c9975a
> Get and sends the fullscreen size, whereas the screen is even not currently in fullscreen but with status bar.
> 
> Moreover, there is a ugly screen glitch when app starts / goes to background/foreground. Event when it ends ...
> 
> 
> 
> 
> A few points:
> - In the onCreate() method. It always starts in non-fullscreen.
> https://hg.libsdl.org/SDL/file/c4d5e502c1f4/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#l267
> 
> - SDL_WINDOW_RESIZABLE:
> Like Mac OS X "SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES" (SDL_hints.h), it dictates fullscreen policy.
> SDL_WINDOW_RESIZABLE (or not) offers (or not) the fullscreen.
> 
> I think we should keep the resize flag, and remove this line: 
> https://hg.libsdl.org/SDL/file/d8683d6ff2f8/src/video/android/SDL_androidwindow.c#l57
> 
> - SDL_video.c : 
> Maybe also this define is wrong:
> https://hg.libsdl.org/SDL/file/c4d5e502c1f4/src/video/SDL_video.c#l1311

On 2018-10-19 13:38:34 +0000, Sylvain wrote:

> The glitch when exiting is gone thanks to https://hg.libsdl.org/SDL/rev/85c6aa0836d8
> 
> Maybe something similar when going to foreground/background could be done ? do you have that glitch too ?

On 2019-06-12 15:26:08 +0000, Sam Lantinga wrote:

> Is this taken care of now, with the other changes you've made?

On 2019-06-13 08:14:06 +0000, Sylvain wrote:

> I am not sure ...
> 
> With SDL_WINDOW_FULLSCREEN:
> 
> I see first:
> 06-13 09:43:38.548  2781  2781 V SDL     : Window size: 1080x2147
> 06-13 09:43:38.548  2781  2781 V SDL     : Device size: 1080x2340
> Then
> 06-13 09:43:39.112  2781  2781 V SDL     : Window size: 1080x2265
> 06-13 09:43:39.112  2781  2781 V SDL     : Device size: 1080x2340
> 
> Without SDL_WINDOW_FULLSCREEN:
> only one:
> 06-13 09:56:15.543  4570  4570 V SDL     : Window size: 1080x2147
> 06-13 09:56:15.543  4570  4570 V SDL     : Device size: 1080x2340
> 
> 
> 
> Device Size is the one exposed in DisplayMode.
> I usually use it to create the SDL_Window, so I am wrong.
> 
> I should in fact use afterwards SDL_GetWindowSize() to get the size of the created window. 
> And this is working in non FULLSCREEN.
> 
> 
> But in FULLSCREEN (so immersive), I should also always check for RESIZE_EVENT which is problematic to get ,
> app are not necessarily designed to respond to a resize of width/heigth (eg be resizeable).
> Also the first SDL_GetWindowSize() will return the size of non immersive because it's called early.

On 2019-06-14 09:11:18 +0000, Sylvain wrote:

> I think this is now a duplicate of bug 4256

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
