### ISSUE TITLE
CMake MSVC ARM/ARM64 builds fail

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3014]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [build log (log (2).txt, text/plain, 2018-10-10 22:31:55 +0000, 13631 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3361)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows (All), ARM

# Comments on the original bug report:

On 2018-10-10 22:31:55 +0000, Joel Winarske wrote:

> Created attachment 3361
> build log
> 
> When building for MSVC ARM or MSVC ARM64 build fails with error:
> C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\corecrt.h(226): fatal error C1189: #error:  Compiling Desktop applications for the ARM platform is not supported.
> 
> 
> 
> This is the solution I've come up with for the pthreads4w and PDCurses open source projects.  The other flags are used by version.rc to define the proper machine string.
> 
> 
> include (target_arch)
> 
> get_target_arch(TARGET_ARCH)
> 
> if(${TARGET_ARCH} STREQUAL "ARM")
>     add_definitions(-D__PDCURSES_ARCHARM)
>     if(MSVC)
>         add_definitions(-D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1)
>     endif()
> elseif(${TARGET_ARCH} STREQUAL "ARM64")
>     add_definitions(-D__PDCURSES_ARCHARM64)
>     if(MSVC)
>         add_definitions(-D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1)
>     endif()
> elseif(${TARGET_ARCH} STREQUAL "x86_64")
>     add_definitions(-D__PDCURSES_ARCHAMD64)
> elseif(${TARGET_ARCH} STREQUAL "x86")
>     add_definitions(-D__PDCURSES_ARCHX86)
> elseif(${TARGET_ARCH} STREQUAL "x64")
>     add_definitions(-D__PDCURSES_ARCHX64)
> else()
>     MESSAGE(ERROR "\"${TARGET_ARCH}\" not supported in version.rc")
> endif()
> message(STATUS "Target ................. ${TARGET_ARCH}")

**Comment by icculus** [comment]
This bug is obsolete in modern times; every commit is checked on MSVC/arm64 generated with CMake, now.
