### ISSUE TITLE
opengl renderer renders black window on nvidia AGX jetson xavier

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3020]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [sample program (opengl-fails.zip, application/zip, 2018-10-14 00:20:20 +0000, 11984 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3372)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2018-10-14 00:20:20 +0000, Jon wrote:

> Created attachment 3372
> sample program
> 
> The NVIDIA Jetson family is the one that powers the Nintendo Switch, although the AGX Xavier is of a more modern vintage (turing, 512 cores.)
> 
> When using the sample program from https://watte.net/opengl-fails.zip together with libsdl2 2.0.8 built from source on the Xavier, software works great. However, the opengl renderer just renders a black window.
> 
> The sample program captures a side-by-side stereo video image from a Zed camera; you can change the frame size to match some other webcam you might have; you can also change the yuyv->rgba conversion function to force a particular color, but it will still just render black.

On 2018-11-03 00:10:13 +0000, Sam Lantinga wrote:

> I don't have that platform to test on, did you figure this out?

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
