### ISSUE TITLE
Don't copy all right and down pixels in SoftwareRenderer with rotate and odd sizes

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3021]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [patch (patch_bug_4313_software_RenderCopyEx.diff, text/plain, 2018-10-15 20:50:33 +0000, 2779 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3374)
* [test case (main_bug_4313_software_copyex.c, text/x-csrc, 2018-10-17 20:14:37 +0000, 2598 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3382)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-10-14 00:30:54 +0000, Nik wrote:

> ```c
> #include <iostream>
> 
> #include <SDL2/SDL.h>
> 
> 
> int main(int, char **) {
> 	//odd values:
> 	const size_t W = 3;
> 	const size_t H = 5;
> 
> 	//any color
> 	const Uint32 DEFAULT_COLOR = (128 << 24) + (128 << 16) + (128 << 8) + 255;
> 
> 
> 	SDL_Surface *orig = SDL_CreateRGBSurfaceWithFormat(0, W, H, 32, SDL_PIXELFORMAT_RGBA32);
> 	Uint32 *pixels = (Uint32*)orig->pixels;
> 	for (size_t i = 0; i < W * H; ++i) {
> 		pixels[i] = DEFAULT_COLOR;
> 	}
> 
> 	SDL_Surface *res = SDL_CreateRGBSurfaceWithFormat(0, W, H, 32, SDL_PIXELFORMAT_RGBA32);
> 	SDL_Renderer *renderer = SDL_CreateSoftwareRenderer(res);
> 
> 	SDL_Texture *origTexture = SDL_CreateTextureFromSurface(renderer, orig);
> 	SDL_RenderCopyEx(renderer, origTexture, 0, 0, 180, 0, SDL_FLIP_NONE);
> 
> 	pixels = (Uint32*)res->pixels;
> 
> 	//all right pixels
> 	for (size_t y = 0; y < H; ++y) {
> 		Uint32 color = pixels[y * res->pitch + (W - 1) * 4];
> 		if (color != DEFAULT_COLOR) {
> 			std::cout << "Error on pixel <" << (W - 1) << ", " << y << ">\n";
> 		}
> 	}
> 
> 	//and all down pixels
> 	for (size_t x = 0; x < W; ++x) {
> 		Uint32 color = pixels[(H - 1) * res->pitch + x * 4];
> 		if (color != DEFAULT_COLOR) {
> 			std::cout << "Error on pixel <" << x << ", " << (H - 1) << ">\n";
> 		}
> 	}
> 
> 	return 0;
> }
> ```

On 2018-10-15 11:29:16 +0000, Sylvain wrote:

> your test case is incorrect because your look at the wrong position:
> not 
>
> ```c
> Uint32 color = pixels[y * res->pitch + (W - 1) * 4];
> ```
>
> but		
>
> ```c
>   Uint32 color = pixels[y * (res->pitch / 4) + (W - 1)];
> ```
> 
> and not
>
> ```c
>   Uint32 color = pixels[(H - 1) * res->pitch + x * 4];
> ```
>
> but
>
> ```c
>   Uint32 color = pixels[(H - 1) * (res->pitch / 4) + x];
> ```  
> 
> And you also need to retrieve the rotated surface by calling: 
>
> ```c
>   SDL_RenderReadPixels(renderer, NULL, SDL_PIXELFORMAT_RGBA32, pixels, res->pitch);
> ```
> 
> 
> There is one pixel shift, but as you said, this is because of odd width/height. 
> According to SDL_render.h doc, if you don't provide the center, "rotation will be done around dstrect.w/2, dstrect.h/2).".
> So I am not sure this is a bug.
> 
> if you want a perfect 180 rotation, you can use flip flags.

On 2018-10-15 16:31:52 +0000, Nik wrote:

> >your test case is incorrect because
>
> Oops, I made some stupid mistakes in first, sorry
> 
> >SDL_RenderReadPixels
>
> SoftwareRenderer draw directly on surface, is not?
> In any way, it string is not affects
> 
> 
> Here is new version of test-code:
> 
> ```c
> #include <iostream>
> 
> #include <SDL2/SDL.h>
> 
> 
> int main(int, char **) {
> 	//odd values:
> 	const size_t W = 3;
> 	const size_t H = 5;
> 
> 
> 	SDL_Surface *orig = SDL_CreateRGBSurfaceWithFormat(0, W, H, 32, SDL_PIXELFORMAT_RGBA32);
> 
> 	//any color
> 	const Uint32 DEFAULT_COLOR = SDL_MapRGBA(orig->format, 128, 128, 128, 255);
> 
> 
> 	Uint32 *pixels = (Uint32*)orig->pixels;
> 	for (size_t i = 0; i < W * H; ++i) {
> 		pixels[i] = DEFAULT_COLOR;
> 	}
> 
> 	SDL_Surface *res = SDL_CreateRGBSurfaceWithFormat(0, W, H, 32, SDL_PIXELFORMAT_RGBA32);
> 	SDL_Renderer *renderer = SDL_CreateSoftwareRenderer(res);
> 
> 	SDL_Texture *origTexture = SDL_CreateTextureFromSurface(renderer, orig);
> 	SDL_RenderCopyEx(renderer, origTexture, 0, 0, 180, 0, SDL_FLIP_NONE);
> 
> 	pixels = (Uint32*)res->pixels;
> 	for (size_t y = 0; y < H; ++y) {
> 		for (size_t x = 0; x < W; ++x) {
> 			Uint32 color = pixels[y * W + x];
> 			std::cout << (color == DEFAULT_COLOR) << ' ';
> 		}
> 		std::cout << '\n';
> 	}
> 
> 	return 0;
> }
> ```

On 2018-10-15 16:39:38 +0000, Nik wrote:

> >So I am not sure this is a bug.
>
> But it's 100% bug, try rotate surface 1x1 - get pixel with value 0
> 
> >if you want a perfect 180 rotation, you can use flip flags.
>
> It's workaround, I need rotate to 180 correctly
> And 90 & 270 rotation incorrectly on odd size too

On 2018-10-15 20:50:33 +0000, Sylvain wrote:

> Created attachment 3374
> patch
> 
> You're right, no need of SDL_RenderReadPixels.
> 
> I can propose this patch that seems working but I haven't tested much outside of the test-case. Please give a try with various rotations to see if it holds.

On 2018-10-15 20:52:00 +0000, Sylvain wrote:

> It fixes useless colorkey error message in SDL_rotate.c.

On 2018-10-17 20:02:53 +0000, Nik wrote:

> It seems to be working

On 2018-10-17 20:14:37 +0000, Sylvain wrote:

> Created attachment 3382
> test case
> 
> careful on if you use head SDL sources, there is an issue with bug # 4188 which break rotations 90 using RenderCopyEx.
> 
> 
> Here's my test case. you can modify angle and also renderer (software,opengl,gles2) with the Hint.
> And see the output. The output must be the same for all renderers.
> 
> 
> The patch seems to fix 180 rotation offset, for all renderers (software, opengl, gles2).
> For 90 rotation, there is still an offset, but it's the same for all 3 renderers.
> 
> 
> Previously, there were also an offset for 180, the same for all 3 renderers.

On 2018-10-17 21:52:52 +0000, Nik wrote:

> > The output must be the same for all renderers.
>
> Yes, but it's very strange
> 
> If we set dstrect's x = y = 0, why appearance offset?
> SDL rotate about center area with width = max(srcrect.w, dstrect.w) and height = max(srcrect.h, dstrect.h)?
> Or what?
> I don't understand for what need this strange behavior

On 2018-10-18 18:30:59 +0000, Sylvain wrote:

> I agree the offset is strange, but consistent among renderers.
> You could check on window to see how it behaves.
> 
> RenderCopyEx rotate and also can stretch.

**Comment by icculus** [comment]
@1bsyl Should we incorporate this patch into 2.0.20, or is this obsolete at this point?

**Comment by 1bsyl** [comment]
I'll double check !

**Comment by 1bsyl** [comment]
this is ok, I checked the issue, and the patch is actually in, you fixed it :)  with "render: Add floating point versions of various draw APIs. "

```
-    SDL_Point real_center;
+    SDL_FPoint real_center;
```
https://github.com/libsdl-org/SDL/commit/8340b0f0e2b84957e2eee444ae83b6b506d9b15d#diff-265e4391f34d3bb7f8f42bbd547fc6311ef9e37f3bc7f3b397c8f83f59c143cdR2921
