### ISSUE TITLE
Getting Display Handle

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3022]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Small testcase (not written by me) for the CL/GL sharing (cworks.zip, application/zip, 2018-10-14 09:16:37 +0000, 396415 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3373)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-10-14 09:13:15 +0000, Martin Gerhardy wrote:

> I'm having trouble setting up the OpenCL OpenGL sharing context. When doing the init of the OpenCL context, you have to specify the display and the context handle. The context should not be a problem - we could just use SDL_GL_GetCurrentContext (which hopefully directly maps to glXGetCurrentContext or eglGetCurrentContext) - but OpenCL also needs to get the display handle and here it gets ... tricky. For windows this is wglGetCurrentDC and for linux it is glXGetCurrentDisplay - or eglGetCurrentDisplay if you are using EGL. To be honest, I don't know a way to check at runtime whether my context is egl or glx/wgl - I could only check this at compile time afair.
> 
> Therefore it would be nice if we could also get something similar as SDL_GL_GetCurrentContext for the display. E.g. SDL_GL_GetCurrentDisplay(SDLWindow* window)

On 2018-10-14 09:16:37 +0000, Martin Gerhardy wrote:

> Created attachment 3373
> Small testcase (not written by me) for the CL/GL sharing
> 
> Attached a small glx example where the CL sharing works with glfw and glx
> 
> And this is the OpenCL extension I'm talking about:
> https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/cl_khr_gl_sharing.html

On 2018-10-14 09:46:39 +0000, Martin Gerhardy wrote:

> And the last thing - We also need to know which type of handle it is. Is it glx, egl, wgl, ...? this is due to the fact that OpenCL must know this, too. 
> 
> 
> https://github.com/mgerhardy/engine/blob/master/src/modules/computevideo/cl/CLComputeVideo.cpp
> 
> CL_WGL_HDC_KHR
> CL_GLX_DISPLAY_KHR
> CL_EGL_DISPLAY_KHR
> 
> CL_CGL_SHAREGROUP_KHR for CGL is quite easy I suppose.
> CL_GL_CONTEXT_KHR is for the gl context.

On 2018-11-03 00:13:02 +0000, Sam Lantinga wrote:

> Would you like to propose an API change for this?

On 2018-11-08 07:54:33 +0000, Martin Gerhardy wrote:

> What do you think about this?
> 
> /**
>  *  \brief Get the display of the given window
>  *
>  *  \param window   Window from which the display should be queried
>  */
> extern DECLSPEC SDL_GLDisplay SDLCALL SDL_GL_GetDisplay(SDL_Window * window);
> 
> If nobody votes against this, I would implement it.

On 2018-11-13 00:39:47 +0000, Sam Lantinga wrote:

> That sounds reasonable. Let's call it SDL_GL_GetCurrentDisplay() to match the naming from the platform extensions.
> 
> Thanks!

**Comment by icculus** [comment]
Putting this in 2.0.20, but we might bump it out (or merely close it without adding this API).

**Comment by icculus** [comment]
I'm thinking we shouldn't add this; OpenCL is being replaced with Compute functionality directly contained in Vulkan, Direct3D 12, and Metal. For X11 and Windows without us making changes, they can use SDL_SysWM to get the Display pointer or HDC. 

For EGL, there's an eglGetCurrentDisplay() API.
