### ISSUE TITLE
SDL going into fullscreen during a Windows 10 RDP session crashes the SDL library

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3041]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-10-27 10:53:58 +0000,  wrote:

> I notice that the entire desktop becomes unresponsive(verified using both Windows 10 RDP and TeamViewer). Visual Studio Community 2018 breaks into it's debugger(being unresponsive itself).
> 
> (replace APP_NAME.exe with the SDL app's filename.
> It says: "Exception thrown at 0x0000000000000000 in APP_NAME.exe: 0xC0000005: Access violation executing location 0x0000000000000000.
> 
> The debugger itself looks like it's pointing to SDL_render_GL.c line 1093.
> 
> The entire desktop is unreponsive. The only thing that can be done is CTRL+ALT+END to log off. Any other actions(like task manager) show the task manager which is also unresponsive, probably due to SDL still being in fullscreen somehow.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
