### ISSUE TITLE
Add and update include guards

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3042]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[0001-Add-and-update-include-guards.patch (0001-Add-and-update-include-guards.patch, text/plain, 2018-10-28 18:53:00 +0000, 24496 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3406)~~
* [0001-Add-and-update-include-guards.patch (0001-Add-and-update-include-guards.patch, text/plain, 2018-10-28 20:44:37 +0000, 22937 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3407)
* [0002-Rename-files-meant-to-be-included-multiple-times.patch (0002-Rename-files-meant-to-be-included-multiple-times.patch, text/plain, 2018-10-28 20:46:16 +0000, 87137 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3408)

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-10-28 18:53:00 +0000, janisozaur wrote:

> Created attachment 3406
> 0001-Add-and-update-include-guards.patch
> 
> Include guards in most changed files were missing, I added them keeping
> the same style as other SDL files. In some cases I moved the include
> guards around to be the first thing the header has to take advantage of
> any possible improvements compiler may have for inclusion guards.

On 2018-10-28 20:44:37 +0000, janisozaur wrote:

> Created attachment 3407
> 0001-Add-and-update-include-guards.patch
> 
> V1 was too eager and guarded too many files. This patch fixes that.

On 2018-10-28 20:46:16 +0000, janisozaur wrote:

> Created attachment 3408
> 0002-Rename-files-meant-to-be-included-multiple-times.patch
> 
> As a way of addressing the need for header files to contain an include guard, but some files need to be explicitly included multiple times, rename such special files to reflect that need.

On 2018-10-28 21:25:23 +0000, Sam Lantinga wrote:

> The include guards patch is in:
> https://hg.libsdl.org/SDL/rev/c46e72bd9950
> 
> The other patch we can evaluate after 2.0.9 ships.

On 2018-10-28 21:37:21 +0000, janisozaur wrote:

> Thanks!

**Comment by icculus** [comment]
I'm saying no to renaming files that are included multiple times, so this is done.
