### ISSUE TITLE
Add a default gamepad mapping for the 8Bitdo SN30 using the "8Bitdo Receiver"

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3048]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2018-11-02 23:20:39 +0000, Manuel Alfayate Corchete wrote:

> Hi there,
> 
> I'd like to have this default mapping for the 8Bitdo SN30 gamepad added in src/joystick/SDL_gamecontrollerdb.h, so the gamepad is detected as a gamepad by SDL2 and games threat it as such a device.
> 
> This is the mapping it fits better: it's the same as a 8Bitdo SFC30, only the GUID changes:
> 
> "03000000c82d00000031000011010000,8Bitdo Receiver,a:b1,b:b0,back:b10,leftshoulder:b6,leftx:a0,lefty:a1,rightshoulder:b7,start:b11,x:b4,y:b3,",
> 
> Please add it to the "#if defined(__LINUX__):" section at least, as I am testing this on GNU/Linux systems on ARM/AARCH64 and X86_64.
> 
> Thanks!

**Comment by sezero** [comment]
There are several 8Bitdo SN30 entries there, but not this one..
