### ISSUE TITLE
Window forgets w & h when created maximized and attaching an openGL renderer

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3054]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, All

# Comments on the original bug report:

On 2018-11-06 08:55:17 +0000, Anthony @ POW Games wrote:

> So, when SDL_CreateWindow is used with the SDL_WINDOW_MAXIMIZED & SDL_WINDOW_RESIZABLE flags, the window should restore to the w & h specified in SDL_CreateWindow. This appears to stop working (as in the window stays full screen w & h instead) when creating a renderer that uses openGL, but works with software and Direct3D renderers. 
> 
> I thought this might be a post-2.0.9 bug, but it exists in 2.0.9 official.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
