### ISSUE TITLE
SDL_WINDOW_ALLOW_HIGHDPI flag is not unset on failure

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3062]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2018-11-09 02:58:31 +0000, Caleb Cornett wrote:

> On macOS, if SDL cannot create a high-DPI window (e.g. because of an insufficient screen resolution), the SDL_WINDOW_ALLOW_HIGHDPI window flag is never turned off. This makes it difficult to determine at runtime if high-dpi window creation has been successful.
> 
> The snippet responsible for this behavior (or lack thereof) appears to be this:
> https://hg.libsdl.org/SDL/file/a4d730631698/src/video/cocoa/SDL_cocoawindow.m#l1360
> 
> What's the best way to fix this? I suspect there's a simple solution, but I'm not familiar with Cocoa so I have no idea what it would be.

On 2018-11-09 12:11:21 +0000, Alex Szpakowski wrote:

> As the flag's name implies, it just makes SDL windows capable of being high-dpi, it isn't really meant to fail to create the window if it isn't high dpi - you can use SDL_GL_GetDrawableSize (if you're using OpenGL directly), or SDL_GetRendererOutputSize (if you're using SDL_Render) and compare that to SDL_GetWindowSize, to determine if the window is currently high dpi.

**Comment by slime73** [comment]
I think this issue can be closed (not a bug).

**Comment by slouken** [comment]
In addition, in SDL 3.0 you can get the actual pixel density using `SDL_GetWindowPixelDensity()`
