### ISSUE TITLE
SDL_RenderCopyEx rotation and global scaling around the wrong way

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3070]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2018-11-19 01:14:21 +0000, Anthony @ POW Games wrote:

> This should be an easy fix. Simply apply global scale factor after rotating verts?
> 
> The problem is when using SDL_RenderSetScale with non-equal width and height. This scale factor is applied before rotation. I can't think of any situation where this is the desired result. It means the rotated shape is distorted. Say you have a square texture, and scale factor of 1, .5, the square will be squashed and rotated, rather than rotated, then squashed in unison with all the other non-rotated shapes.

On 2018-11-19 13:16:05 +0000, Anthony @ POW Games wrote:

> After briefly looking at the source code, I can see there is no simple fix for this. Scaling is done before the angle is passed down deeper into the renderer's QueueCopyEx(). 
> 
> Scaling would need to be passed down deeper into the renderer queue and applied there.
> 
> This is still a bug though. It's caused me many problems that I've had to find a messy work-around for in most of my designs.

**Comment by 1bsyl** [comment]
Fixed also for PSP https://github.com/libsdl-org/SDL/commit/61abc4e5b64c390d7c7c1ff25fa0e2b755fc34eb

**Comment by 1bsyl** [comment]
@AntTheAlchemist this was fixed for accelerated renderer that use rendergeometry but now this should be fixed also for software renderer !

**Comment by 1bsyl** [comment]
here a testcase : [main_bug_3070__scale_rotate.c.txt](https://github.com/libsdl-org/SDL/files/8068335/main_bug_3070__scale_rotate.c.txt)
arrows: to scale in/out in x/y
b: blendmode
