### ISSUE TITLE
HINT to show cursor in RELATIVE mouse mode

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3078]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [suggested patch (relative-cursor.patch, text/plain, 2018-11-22 13:37:06 +0000, 3253 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3501)

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-11-22 13:37:06 +0000, Mouhamad Kebe wrote:

> Created attachment 3501
> suggested patch
> 
> By default, SDL hides the cursor in relative mouse mode. Some applications may want to be able to display it.
> 
> If SDL_HINT_MOUSE_RELATIVE_SHOW_CURSOR is set to "1", the cursor will be visible

On 2018-11-22 16:17:26 +0000, Sam Lantinga wrote:

> Some platforms implement relative mode by warping the cursor to the center of the screen every frame. On other platforms, the cursor will go to the edge of the screen and just stick there. Are you sure you want to see that?

On 2018-11-22 16:18:32 +0000, Sam Lantinga wrote:

> For applications that have a logical cursor in relative mode, it's probably better for them to just draw the cursor where they intend for it to be. That's what most games do.

**Comment by icculus** [comment]
This one is a no from me.
