### ISSUE TITLE
OpenGL rendering issues when toggling window border

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3098]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2018-12-10 06:29:11 +0000,  wrote:

> When SDL is used with OpenGL for rendering, turning off the window border with SDL_SetWindowBordered() causes the render output to be shifted down within the window area. 
> 
> The window itself seems to stay in the initial position, with only the window border disappearing as expected, but the contents within the window are offset by an amount that appears to be equal to the height of the now-hidden title bar. Occasionally when selecting the application window in the task bar, the title bar text will appear again, but drawn *within* the window itself (with the text changing color when gaining/losing focus as usual).
> 
> Run the testgl2 example and press Ctrl+B to reproduce. This issue is not seen when running a non-OpenGL example (testdraw2, testsprite2 etc).
> 
> Switching to a basic Windows theme (ie. non-Aero) avoids the problem.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
