### ISSUE TITLE
ime_threadmgrex turns invalid if window loses focus while using COINIT_MULTITHREADED

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3105]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-12-16 10:01:34 +0000,  wrote:

> Before initializing SDL2 I call CoInitializeEx(0, COINIT_MULTITHREADED).
> Then using the events subsystem, it works fine until my window loses fokus.
> Then it does lose fokus in SDL_windowskeyboard.c in UILess_DisableUIUpdates will be a read access violation since ime_threadmgrex->lpVtbl turns invalid (the pointer lpVtbl itself didn't change).
> This does not happen without CoInitializeEx(0, COINIT_MULTITHREADED), but SDl2 is supposed to be compatible with COINIT_MULTITHREADED?

On 2019-02-07 22:09:21 +0000,  wrote:

> The crashing code belongs to the uiless windows IME that seems to be incomplete and doesn't work. You can try to disable it by recompiling the library with either SDL_DISABLE_WINDOWS_IME defined or the following line commented out:
> 
> videodata->ime_uiless = UILess_SetupSinks(videodata);

**Comment by slouken** [comment]
UILess_SetupSinks() has been removed.
