### ISSUE TITLE
SDL_LoadBMP does not support path name that contains space bar on Windows

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3110]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-12-27 11:17:33 +0000,  wrote:

> SDL_LoadBMP does not support path name that contains space bar on Windows. For example, 
> 
> SDL_Surface* pTempSurface = SDL_LoadBMP("..\\assets in this book\\rider.bmp"); 
> 
> will return NULL. Please fix it.

**Comment by slouken** [comment]
Paths with spaces work. The problem here is that \ is an escape character and needs to be doubled up to be interpreted as a path separator.
Try this:
```c
SDL_Surface* pTempSurface = SDL_LoadBMP("..\\assets in this book\\rider.bmp");
```
