### ISSUE TITLE
The key you just pressed is not recognized by SDL.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3113]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2018-12-31 01:55:56 +0000, ploni wrote:

> I was playing a game (SuperTux) which uses SDL, and when I run it from the command line I see the following message appears when I press the 'Fn' key (the key that toggles the legacy 'F#' keys with the new multimedia keys):
> 
> "The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 151 (143), X11 KeySym 0x1008FF2B (XF86WakeUp)."

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
