### ISSUE TITLE
SDL_GameControllerName and SDL_JoystickName don't return the expected name for XBox controllers

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3131]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-01-19 12:43:13 +0000, Rémy Tassoux wrote:

> I have both a XBox 360 and XBox One controller, and if I try to get their name using either SDL_GameControllerName or SDL_JoystickName, the ouput is always "XInput Controller" instead of their real name.

On 2019-02-15 17:46:44 +0000, Bob Ombo wrote:

> What is the GUID of your controller?
> 
> I have a "compatible" controller, i get:
> 
> INFO: Joystick (0)[Microsoft X-Box 360 pad] ADDED!
> INFO: Controller (0)[XInput Controller] ADDED!
> 
> when using events
> 
> SDL_CONTROLLERDEVICEADDED:
> SDL_GameControllerNameForIndex(event.cdevice.which)
> 
> SDL_JOYDEVICEADDED:
> SDL_JoystickNameForIndex(event.jdevice.which)
> 
> so i get both, not sure if that's a bug?

On 2019-04-04 11:24:35 +0000, Rémy Tassoux wrote:

> Here are the GUIDs and the associated names I get for each controller :
> 
> [ XBox 360 Wired Controller ]
> GUID: 030000005e0400008e02000000007801
> Joystick Name: XInput Controller # 1
> Controller Name: XInput Controller
> 
> [ XBox One S Controller ]
> GUID: 030000005e040000ea02000000007801
> Joystick Name: XInput Controller # 2
> Controller Name: XInput Controller
> 
> Both are official Microsoft controllers. Their GUIDs are missing from SDL_gamecontrollerdb.h, I guess that's why I get generic names.

**Comment by icculus** [comment]
It's possible hidapi handles this and we just have to close this bug, but tossing to Sam to verify.

**Comment by slouken** [comment]
This is the name that any controller gets when it's handled by XInput. Since this was reported we added RAW game controller support which gives us the real names.
