### ISSUE TITLE
Changing to/from fullscreen moves the cursor without user input

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3132]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, All

# Comments on the original bug report:

On 2019-01-20 12:17:21 +0000,  wrote:

> Changing to/from fullscreen moves the mouse cursor. This is extremely noticeable with "fake" windowed fullscreen mode that doesn't change the actual video mode/resolution. A cursor that moves without user input is annoying and can disorient the user. At the same time the resized window might contain interface elements in a different location so even if the application wanted to keep the cursor over a specific user interface element the cursor adjustment could be done only by the application.
> 
> Changing to/from fullscreen mode seems to keep a constant offset of the cursor from the topleft corner of the window client area. The issue with this solution isn't only the annoyance and bad user experience but it gives totally wrong results when switching from a "large" fake fullscreen window into a "small" non-fullscreen window when the cursor is close the bottom-right area of the fullscreen window.
> 
> I had a quick look at the SDL sources and the likely source of the issue is this change: https://hg.libsdl.org/SDL/diff/5c4635640bf9/src/video/SDL_video.c
> 
> That change should've solved the issue by updating the cached cursor positions to the actual cursor positions instead of forcing the cursor on the screen to an older cached position. In certain cases (like on windows platform) caching might have more issues than benefits compared to querying the cursor position directly (assuming that the query doesn't happen too often).

**Comment by rversteegen** [comment]
I'm seeing a variant of this on X11/xfce4/SDL2-git, but not on WindowsXP/SDL2.0.14. It is certainly very annoying. The mouse cursor sometimes or frequently jumps randomly when exiting or leaving desktop fullscreen.

It happens regardless on which display the window is on, whether it's centered, whether I move the mouse, whether the mouse is over the window, or whether I add an SDL_Delay() to the loop. There are two different effects. Rarely, the mouse jumps across the screen or to a different display. More frequently, it gets into a pattern of moving the mouse down-right (by the window border size?) every time I leave fullscreen, or up-left every time I enter it, until I move the mouse. Once I saw it alternative between two mouse positions every time I entered/exited fullscreen, until I moved the mouse.

When I run the following testcase sometimes the mouse warps only about 10% of the time, on other runs it about 90%. It's much more frequent when exiting fullscreen. 
```
#include <SDL2/SDL.h>

int main(int argc, char **argv) {
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window* window = SDL_CreateWindow(NULL, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 600, 0);
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, 0);

    SDL_Event e;
    while (1) {
        while (SDL_PollEvent(&e) != 0) {
            if (e.type == SDL_QUIT) {
                return 0;
            }
            if (e.type == SDL_KEYDOWN && e.key.keysym.sym == SDLK_F1) {
                SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);
            }
            if (e.type == SDL_KEYDOWN && e.key.keysym.sym == SDLK_F2) {
                SDL_SetWindowFullscreen(window, 0);
            }
        }
        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
    }
}
```
Spam F1/F2 keys repeatedly.

**Comment by slouken** [comment]
I just tested this here on GNOME and it worked as expected - the mouse moved to the relative offset in the window during the transition between windowed and fullscreen. I'm going to close this for now, please feel free to reopen it if it's an issue with xfce4.
