### ISSUE TITLE
Vulkan Wayland fullscreen not working

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3135]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-01-23 10:09:44 +0000,  wrote:

> With OpenGL switching to fullscreen mode works flawlessly on Wayland. But when using Vulkan and Wayland SDL_WINDOW_FULLSCREEN and SDL_WINDOW_FULLSCREEN_DESKTOP do nothing. I also tested around a bit for myself and created a wl_shell_surface for my wl_surface in Vulkan and called wl_shell_surface_set_fullscreen on it with no luck. Is this some kind of limitation of Vulkan and Wayland or is it just SDL not having implemented it as of now?
> I am using plasma-wayalnd-session and kwin and have intel integrated graphics.

**Comment by flibitijibibo** [comment]
The latest SDL tip should resolve this - a lot of changes were made to the window handling and fixing fullscreen support was a major part of those changes.
