### ISSUE TITLE
Screenshot button on Switch Pro Controller not detected

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3146]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2019-01-30 12:53:50 +0000,  wrote:

> I am trying to get Switch Pro Controller to work on my mac. After I called SDL_JoystickNumButtons(), it returned 15, which in fact should be 16. I've figured out that the missing button is the Screenshot button on the left side of the joystick (the one at the left of the home button and below the minus button). I've tried buttons from 0~14 and none of them represented the screenshot button.
> 
> I'm using the SDL2# binding by flibitijibibo but it shouldn't change anything since it's calling the same functions. And my OS X version is 10.14 Mojave.
> 
> I came here because the mighty internets does not seem to know about this problem.

**Comment by icculus** [comment]
I have a Switch Pro controller here, I'll at least verify for 2.0.20 (but maybe not fix, if the OS itself isn't reporting the button).

**Comment by icculus** [comment]
This works on Mojave with the latest SDL:

<img width="513" alt="Screen Shot 2021-12-29 at 10 52 52 AM" src="https://user-images.githubusercontent.com/673562/147680238-109ad919-6ed5-4bd1-b451-42b87ba9c3e1.png">


...however, X and Y, and A and B, are reversed from what they should be. How does this work with hidapi? Do we just tweak this in the gamecontrollerdb.h file or is it somewhere else (and is tweaking it going to break it for non-hidapi builds, if such builds are still a thing?). Filing a separate issue for that.
