### ISSUE TITLE
SDL_PrivateJoystickAdded generates incorrect device_index

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3154]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-02-04 16:33:12 +0000, Rutger Janssen wrote:

> When performing the following reproduction steps, I noticed that the device index is incorrect reported with a PS4 and Xbox controller
> 
> 1. Connect PS4 and XBox controller
> 2. Start application
> SDL_PrivateJoystickAdded already creates device_index of 0 twice, but this is not a problem as no events are generated and devices are added later by looping over all devices.
> 3. Remove PS4 controller
> 4. Attach PS4 controller
> Notice that instance_id is 2 and device index is 0.
> 5. Call SDL_GameControllerOpen with the device index (0)
> Notice that the instance_id is 1 (The xbox controller)
> 
> I would expect that the device index that's reported in the event to be the same index I can use to open the controller.
> 
> Based on my short investigation, this has to do that the device index is based on the joystick driver order, windows_joystick first, HIDAPI_joystick later. However the device enumeration first detects the PS4 controller but as WINDOWS_JoystickDetect cleared the SYS_Joystick list, it doesn't know of the windows controllers and is given index 0. The XInput controller is then added and given index 0, as it's first in the driver list, thus changing the index of the PS4 controller.

**Comment by slouken** [comment]
We now go through and update the index of events when controllers are added. I believe this is resolved, but feel free to reopen if you're still seeing this.
