### ISSUE TITLE
SDL_GameControllerAddMapping update problem

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3164]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Example code for SDL_GameControllerAddMapping() (joy.c, text/x-csrc, 2019-02-15 18:35:39 +0000, 4604 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3625)

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-02-15 18:35:39 +0000, Bob Ombo wrote:

> Created attachment 3625
> Example code for SDL_GameControllerAddMapping()
> 
> The map doesn't seem to survive a second SDL_GameControllerAddMapping()
> 
> SDL_GameControllerAddMapping
> const char *mappingString="..."
> 
> // first add my map
> amr=SDL_GameControllerAddMapping(mappingString);
> // (added) everything works as expected!
> 
> // just do it a second time
> amr=SDL_GameControllerAddMapping(mappingString);
> // (updated) now some axis and buttons are wrong
> 
> (Complete example attached.)

On 2019-02-15 18:55:48 +0000, Bob Ombo wrote:

> Actually the same happens if i just call 
> SDL_GameControllerAddMapping()
> ONCE, then just close and reopen the controller:
> 
> SDL_GameControllerClose(controller);
> controller=SDL_GameControllerOpen(0);
> 
> The map is saved:
> SDL_GameControllerMapping(controller)
> does show the correct map.
> 
> Just some axis and buttons are wrong now.

On 2019-02-26 17:34:58 +0000, Bob Ombo wrote:

> OK i finally found out what the problem was:
> 
> 1. The mapping was wrong
> 2. The controller did work because it didn't use the wrong map, but default mapping instead
> 
> If you do
> 
> controller=SDL_GameControllerOpen(0);
> SDL_GameControllerAddMapping(mappingString);
> 
> the mapping will not be active!
> 
> So always do it the other way round:
> 
> SDL_GameControllerAddMapping(mappingString);
> controller=SDL_GameControllerOpen(0);
> 
> So unless this is a bug, and SDL_GameControllerAddMapping should work even
> when the controller is opened already, this bug can be closed.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
