### ISSUE TITLE
[Feature Request] include jsmpeg video driver?

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3169]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.6
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2019-02-18 05:52:09 +0000,  wrote:

> in my private branch of SDL2 (based on 2.0.6) I've managed to add a
> video driver based on jsmpeg (see https://github.com/phoboslab/jsmpeg).
> Please find the code in https://www.androwish.org in the jni/SDL2 folder.
> Should it be usable, I'll be glad if you include it into the official SDL2.
> 
> Best,
> Christian

On 2019-03-17 02:24:46 +0000, Sam Lantinga wrote:

> What's the use case for this?

On 2019-03-17 04:56:26 +0000,  wrote:

> The idea is to have headless operation e.g. on a Raspberry
> resembling Xvnc but without the overhead of an X11 installation.

On 2019-06-12 03:35:30 +0000, Sam Lantinga wrote:

> This is cool, can you put together some documentation and a standalone demonstration?
> 
> Thanks!

On 2019-06-12 08:47:44 +0000,  wrote:

> End of June 2019 I'll have a talk @ EuroTcl2019, see
> 
>   https://ssl.webpack.de/www.eurotcl.eu
> 
> where I will present it in combination with undroidwish.
> Usually the talks appear soon later in the Tcl/Tk youtube
> channel, see
> 
>   https://www.youtube.com/channel/UCaHkl87soQMlWHbLdFdNf0w
> 
> Slides of the conferences will be online after the conference, too.
> 
> Meanwhile, there's my 2018 talk in
> 
>   https://www.youtube.com/watch?v=D6B5PN_xfQU
> 
> which shows SDL2 with Tcl/Tk on Wayland, Haiku, KSMDRM, etc.
> 
> All the best,
> Christian

On 2019-06-12 14:51:09 +0000, Sam Lantinga wrote:

> I'm actually asking for a way to run the programs in the SDL test directory in a way that I can see and verify the functionality?

On 2019-06-13 05:23:21 +0000,  wrote:

> (In reply to Sam Lantinga from comment # 5)
> 
> > I'm actually asking for a way to run the programs in the SDL test directory
> > in a way that I can see and verify the functionality?
> 
> Ah, I see. Having not checked it myself, forcible set the video driver to
> be used per environment variable SDL_VIDEODRIVER=jsmpeg prior to starting
> your test binary. When the test binary runs, point your HTML5/WebGL
> capable browser to http://localhost:8080
> 
> If you'd like to use another TCP port, use the environmnt variable
> SDL_VIDEO_JSMPEG_PORT=8181 for TCP port 8181 and so on.
> 
> HTH,
> Christian

**Comment by icculus** [comment]
This is cool but I'm passing on this.

**Comment by slouken** [comment]
I'm not adding this to any milestone, but I kinda want to play with it a bit.
