### ISSUE TITLE
SDL_audiocvt crashes on enumerating hardware during HID?

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3173]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-02-20 12:32:56 +0000,  wrote:

> When I run my app using SDL 2.0.9 while switching between Windows 10 using RDP and without RDP(which happens a lot during me developing my app), either after some time or because I'm mounting the mouse/keyboard by hiding the mouse the normal way(changed with SDL 2.0+. Haven't figured out the exact cause yet), I see the hid_enumerate function crashing in it's enumeration loop, trying to dereference an invalid pointer?
> 
> These are the lines of code that remain in Visual Studio after the debugger had stopped the application:
> 
> src/hidapi/windows/hid.c:419
> src/events/SDL_events.c:664
> src/audio/SDL_audiocvt.c:558
> src/joystick/SDL_joystick.c:1075
> src/joystick/hidapi/SDL_hidapijoystick.c:872
> 
> I think the first error came from the VC++ debugger on the hic.c line, but it might also have been the SDL_audiocvt.c line.
> 
> Either way, for some unknown reason, SDL crashed dereferencing a NULL pointer at either device enumeration(hid.c) or audio convertion(SDL_audiocvt.c)?

On 2019-02-20 12:51:15 +0000,  wrote:

> If I remember correctly, the debugger was breaking at the SDL_audiocvt.c line, so perhaps the HID API had nothing directly to do with it.

**Comment by icculus** [comment]
I think this is likely to close as WONTFIX, but I'll toss it into the 2.26 milestone to try and reproduce it.
