### ISSUE TITLE
Correct mappings for PSX joystick via USB adapter

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3175]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2019-02-21 04:46:36 +0000, Manuel Alfayate wrote:

> Hi there,
> 
> PSX joystick via USB adapter with ID 03000000ff1100004133000010010000 needs to be adjusted so L2 and R2 buttons work, otherwise these two buttons are just ignored and don't generate a SDL_CONTROLLERBUTTONDOWN event.
> 
> Currently we have in SDL_gamecontrollerdb.h:
> 
> "03000000ff1100004133000010010000,PS2 Controller,a:b2,b:b1,back:b8,leftshoulder:b6,lefttrigger:b4,leftx:a0,lefty:a1,rightshoulder:b7,righttrigger:b5,start:b9,x:b3,y:b0,",
> 
> But the right line would be this:
> 
> "03000000ff1100004133000010010000,PS2 Controller,a:b2,b:b1,back:b8,leftshoulder:b6,leftstick:b4,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b5,start:b9,x:b3,y:b0,",
> 
> Please set this line in SDL_gamecontrollerdb.h.  
> 
> Thanks
> 
> Manuel Alfayate

On 2019-03-17 01:54:03 +0000, Sam Lantinga wrote:

> The change you made removes the bindings for the trigger. Is that what you meant to do? I'm pretty sure the original device that this was tested with used those buttons for triggers, not stick buttons.

**Comment by icculus** [comment]
@slouken Is there some way to look this up in Steam's crowdsourced mappings database, to see if there's a definitive string we should use here?

**Comment by slouken** [comment]
I'm pretty sure these are mappings for different controllers that share USB VID/PID. Let's get a new mapping for the device using controllermap from SDL 2.25.

**Comment by icculus** [comment]
It's a USB adapter for a PlayStation 1 controller (I assume that's what "PSX" means here) so we'd need @vanfanel to do this, if he still has the hardware available.

**Comment by vanfanel** [comment]
@icculus Sorry to say this, but I don't have the adapter here anymore.
I may be able to get it back in some months when I go visit my parent's...

**Comment by icculus** [comment]
@vanfanel No problem; I'm going to close this issue for now, but if you happen to get the adapter back at some point, please do let us know and we'll open it again!

**Comment by vanfanel** [comment]
@icculus Aye aye, sir!
