### ISSUE TITLE
SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS doesn't work (tvOS)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3185]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Other, x86_64

# Comments on the original bug report:

On 2019-03-02 03:53:35 +0000, Trent Gamblin wrote:

> On tvOS, SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS is supposed to allow passing the menu button to the OS so your app can be "backed out" to the OS. I set this to "1" on my title screen. It works fine in older versions of SDL (I believe I was using 2.0.5 or 2.0.6) but doesn't work anymore in 2.0.9. Pressing menu just does the usual keypresses even if that flag is set to 1.
> 
> Apple guidelines recommend Menu goes back to the previous menu then drops to the OS at the top-level menu (https://developer.apple.com/design/human-interface-guidelines/tvos/remote-and-controllers/remote/).

On 2019-03-03 13:13:07 +0000, Trent Gamblin wrote:

> I've done some more testing:
> 
> 2.0.9: Menu button doesn't drop to OS, and swiping the Siri remote causes multiple events, eg swipe once will cause 1-3 direction events
> 
> 2.0.8: Menu button doesn't drop to OS, but swipe events are OK
> 
> 2.0.7: Library doesn't link for tvOS (multiple undefined symbols)
> 
> 2.0.6: Everything works here

**Comment by slouken** [comment]
I believe this is fixed, and tested extensively in the Steam Link app.
