### ISSUE TITLE
SDL_GetKeyState() Reports key as pressed when window gets hidden

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3186]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Example to reproduce the issue (main.c, text/plain, 2019-03-02 12:33:36 +0000, 1758 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3686)

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2019-03-02 12:33:36 +0000,  wrote:

> Created attachment 3686
> Example to reproduce the issue
> 
> When a key is pressed while the window gets hidden, SDL_GetKeyState() will keep the state as activated/pressed. Even when the window is shown again, the key still returns as pressed, as long as until it’s really pressed again.
> Also, the window itself seems to stay focused on the keyboard (when hidden), at least SDL_GetKeyboardFocus() says so. According to the Win32 API, if a window gets hidden, another window should be activated (https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-showwindow SW_HIDE parameter), and I think this should apply to SDL aswell?
> 
> Expected behaviour:
> - If the window gets hidden, SDL_GetKeyState() should not return any activated keys.
> - The window should loose focus and therefore, SDL_GetKeyboardFocus() should not return the same window.
> 
> Workarounds:
> 
> I found a workaround, if SDL_MinimizeWindow() followed by SDL_RestoreWindow() are called before hidding the window via SDL_HideWindow(), the keystate is working correctly. However, the window still stays active.
> 
> How to reproduce:
> 
> For me, it reproduces every time, I wrote a sample to isolate/test it (See attachment), Keys WASD are defined for testing, W will hide the window (It will be shown again automatically after 3 seconds).

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
