### ISSUE TITLE
Build warning: 'GetDoubleClickTime' undefined; assuming extern returning int

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3206]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows (All), x86_64

# Comments on the original bug report:

On 2019-03-22 15:46:45 +0000, Coriiander wrote:

> FILE: SDL2-2.0.9\src\events\SDL_mouse.c
> FUNCTION: SDL_MouseDoubleClickTimeChanged
> 
> For Win32-platforms this function makes a call to GetDoubleClickTime, as below:
> 
> #ifdef __WIN32__
> mouse->double_click_time = GetDoubleClickTime();
> #else
> 
> While building a warning is issued about the GetDoubleClickTime symbol not being defined - which may lead to undefined behaviour, including crashes.
> 
> To use GetDoubleClickTime include <windows.h> and link to user32.lib.
> You can do so at the top of the file:
> 
> #ifdef __WIN32__
> #include <windows.h> /* Needed for GetDoubleClickTime. Cheers Coriiander! */
> #endif

**Comment by sezero** [comment]
This has been fixed for quite some time
