### ISSUE TITLE
resizing a window on a mac via SDL_SetWindowSize isn't guaranteed to give you the requested dimensions, and SDL data gets out of sync (+patch)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3217]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [patch for mac resize bug (sdl_mac_fix.diff, text/plain, 2019-03-30 22:48:04 +0000, 1040 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3718)

**Reported in version:** 2.0.7
**Reported for operating system, platform:** macOS 10.12, x86

# Comments on the original bug report:

On 2019-03-30 22:48:04 +0000, Kyle Rawlins wrote:

> Created attachment 3718
> patch for mac resize bug
> 
> When I resize a (non-fullscreen) window via `SDL_SetWindowSize`, OS X sometimes chooses a different size than the one I give to SDL. The main way that I know to trigger this is to have a dock on the lower part of the scren, and pick a window height that would exceed the usable space; the actual window height that OS X gives then is the maximum user height that the client area + window decorations will fit into. If this happens, then the dimensions on the SDL_Window object reflect what was passed to `SDL_SetWindowSize`, not the actual resulting size, and so calls to `SDL_GetWindowSize` return the wrong value. (Compounding things, calls to `SDL_GL_GetDrawableSize` seem to still be correct, though the value is in device pixels.) The only way I've found on the SDL user side is to manually resize the window, at which point things become in sync.
> 
> The attached patch fixes this problem for us (us = DCSS). I'm afraid that I don't know much about SDL internal best practices so you may well prefer to solve this a different way, e.g. by sending a resize message to the client when this happens. However, the SDL_SetWindowSize already does send a size changed message (and it is currently sending the wrong values too), so that would require some refactoring.
> 
> (I marked 2.0.7 because that is what we are using at the moment, and that is what this patch is against, but it doesn't appear that the relevant code has been touched more recently.)
> 
> Possibly related to https://bugzilla.libsdl.org/show_bug.cgi?id=2452?

On 2019-06-12 03:12:07 +0000, Sam Lantinga wrote:

> Alex, can you check this?
> 
> Why would we get a size changed message with the wrong size and never get this corrected by the OS resize notifications?

On 2019-06-13 00:32:21 +0000, Alex Szpakowski wrote:

> I just tried to reproduce this using the latest code from hg, but I wasn't able to.
> 
> If I call SDL_SetWindowSize on a window that wasn't created with the SDL_WINDOW_RESIZABLE flag, it seems to use my chosen size no matter what. If I call SetWindowSize on a window without that flag, the OS resizes my window to fit in the status bar, SDL_GetWindowSize immediately gives back the updated size, and I also get a resize event which gives the updated size as well.
> 
> Can you try the most recent possible SDL code or version and see if it still happens for you? If it does still happen, a small bit of code that can reproduce the issue would help as well.

On 2019-06-13 23:03:52 +0000, Kyle Rawlins wrote:

> I can look at this again and try to create a MWE, but it will take me a few days to get back to it.

**Comment by blumens** [comment]
I have the same problem with SDL 2.0.14 under Linux if I use a tiling window manager like i3.

**Comment by slouken** [comment]
I believe this is fixed with the recent work @icculus did for SDL 2.0. If you're still seeing this, go ahead reopen it.
