### ISSUE TITLE
Improve WASAPI audio backend latency

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3234]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Improve WASAPI audio backend latency (WASAPI_PERIOD.patch, text/plain, 2019-04-12 04:48:50 +0000, 2311 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3743)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-04-12 04:48:50 +0000, Anthony Pesch wrote:

> Created attachment 3743
> Improve WASAPI audio backend latency
> 
> Currently, the WASAPI backend creates a stream in shared mode and set's the device's callback size to be half of the shared stream's total buffer size.
> 
> This works, but doesn't coordinate will with the actual hardware. The hardware will raise an interrupt after every period which in turn will signal the object being waited on inside of WaitDevice. From my empirical testing, the callback size was often larger than the period size and not a multiple of it, which resulted in poor latency when trying to time an application based on the audio callback. The reason for this looked something like:
> 
> * The device's callback would be called and and the audio buffer was filled.
> * WaitDevice would be called.
> * The hardware would raise an interrupt after one period.
> * WaitDevice would resume, see that a a full callback had not been played and then wait again.
> * The hardware would raise an interrupt after another period.
> * WaitDevice would resume, see that a full callback + some extra amount had been played and then it would again call our callback and this process would repeat.
>  The effect of this is that the pacing between subsequent callbacks is poor - sometimes it's called very quickly, sometimes it's called very late.
> 
> By matching the callback's size to the stream's period size, the pacing of calls to the user callback is improved substantially. I didn't write an actual test for this, but my use case for this was my Dreamcast emulator (https://redream.io) which uses the audio callback to help drive the emulation speed. Without this change and with the default shared stream buffer (which has a period of ~10ms) I would get frame times that were between ~3-30 milliseconds; after this change I get frame times of ~11-22 milliseconds.
> 
> Note, this patch also has a change that removes passing a duration to the Initialize call. It seems that the default duration used (when 0 is passed) does typically match up with the duration returned by GetDevicePeriod, however the Initialize docs say:
> 
> >To set the buffer to the minimum size required by the engine thread, the client should call Initialize with the hnsBufferDuration parameter set to 0. Following the Initialize call, the client can get the size of the resulting buffer by calling IAudioClient::GetBufferSize.
> 
> This change isn't strictly required, but I made it to hopefully rule out another source of unexpected latency.

On 2019-04-12 04:53:42 +0000, Anthony Pesch wrote:

> One thing I didn't test with this change was audio capture - I don't have any applications which use this. This should be tested before committing.

On 2019-06-12 03:05:26 +0000, Sam Lantinga wrote:

> This seems like a good change. Ryan, can you review it after we ship 2.0.10?

On 2020-01-08 19:40:28 +0000, Anthony Pesch wrote:

> Hey Ryan,
> 
> Just wanted to bump this so it doesn't slip through the cracks.

On 2020-03-24 20:21:30 +0000, Ryan C. Gordon wrote:

> 
> Marking this for target-2.0.14 (the next official release, 2.0.13 is the current development version), so it _doesn't_ slip through the cracks again.
> 
> --ryan.

On 2020-04-07 18:39:06 +0000, Ryan C. Gordon wrote:

> 
> This patch looks good. It's now https://hg.libsdl.org/SDL/rev/41280cc79f3d, thanks!
> 
> --ryan.

**Comment by pcorbineau** [comment]
Hi!

We are facing issue on microphone since this commit has been merged. We decided to update from SDL 2.0.10 to 2.0.14 to get Controllers improvements. Many customers notify us that microphone randomly failed to works since this update. We decided to send a SDL 2.0.14 patched with reverted commit `4c2be472071bf676390214cb942e4569f57a158f`. It works for our customer but I can't find the issue in this commit.

Any Idea ?

**Comment by icculus** [comment]
I'll test this over here before 2.0.16 is finalized; likely we can keep the existing changes and just not use them for audio capture.

**Comment by icculus** [comment]
It's not clear to me either why this change breaks capture, but it's easy enough to special-case the changes to still act the old way on capture devices. @pcorbineau, if you get a chance, please try the latest in revision control and see if it resolves your issue!

**Comment by icculus** [comment]
Actually, more careful reading shows that #4353 probably explains this.  0d0fee7569803ddc41985bfc249418b02dd8cd97 probably fixes this indirectly, but I'll evaluate @Splamy's patch next to see if it's a better fix.

**Comment by icculus** [comment]
Yeah, I think @Splamy has the actual problem here, so I've backed out my patch and applied his.

@pcorbineau, if you're still having problems after this patch, let me know and we'll take the nuclear option by reapplying my workaround.
