### ISSUE TITLE
SDL_CreateWindow fails on systems without X11, if libEGL.so is not linked manually or preloaded

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3267]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-05-26 21:18:11 +0000, Danilo Spinella wrote:

> In a configuration with OpenGL ES v1/v2 and EGL enabled, a program linked with -lSDL2 fails to create a window.
> 
> I've also tested the bug against this simple application:
> https://wiki.libsdl.org/SDL_GetWindowSurface
> 
> 
> SDL_Error() report: "failed to create a window surface".
> 
> If I link the application with EGL ("-lEGL") it works flawlessy, the same if I use LD_PRELOAD=/usr/lib/libEGL.so.
> 
> Running a strace of the application, it loads /usr/lib/wayland-egl.so when it is isn't compiled with "-lEGL".

On 2019-05-26 21:27:44 +0000, Danilo Spinella wrote:

> As an additional note, I am running a musl based system. It doens't seem to be related though.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
