### ISSUE TITLE
SDL_OpenAudio return WASAPI can't initialize audio client

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3270]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [It is a photo of the bug report (Bug_Audio_open.png, image/png, 2019-05-30 07:26:48 +0000, 1223947 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3802)

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2019-05-30 07:26:48 +0000, Sun DaQing wrote:

> Created attachment 3802
> It is a photo of the bug report
> 
> ![image](https://github.com/libsdl-org/SDL/assets/673562/a2b2082b-044e-4d60-b146-d7b7a6449d9a)
>
>
> OS: win7
> My simple player works well with SDL 2.0.3 , but once I change SDL2.DLL to 2.0.9 , it does not work and I debug into the source and find that the spec.format does not match the wanted.format. You can see the source codes in ffplay.c.
> 
> After that I run ffplay(4.1) and got the err infor as the title.
> In the end I run ffplay(4.1) in Win 8 and it works well.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
