### ISSUE TITLE
GameCube controller joystick axis doesn't use full axis range

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3293]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2019-06-19 09:38:41 +0000, Zack Middleton (zturtleman) wrote:

> The GameCube controller (via the Nintendo USB GameCube Adapter) joystick/trigger axis don't use the full axis range.
> 
> The joystick/trigger axis is a Uint8 in the approximate range of 32 to 224. This varies by axis and between controllers but for different controllers it's a similar distance from the axis initial position. SDL does ((axis * 257) - 32768) in HIDAPI_DriverGameCube_UpdateDriver() so it uses values approximately +/-24k but +/-32k is expected by applications.
> 
> Due to non-centered axis, simply increasing the 257 multiplier seems like a bad idea. Maybe have a default distance (per-axis) from initial position to use for scaling and increase min/max if axis goes past it. (I probably should test this / try to figure out what GameCube games do.)
> 
> axis_initial = first_value
> axis_max = axis_initial + default_distance[axisnum]
> axis_min = axis_initial - default_distance[axisnum]
> ...
> if (axis > axis_max) axis_max = axis;
> if (axis < axis_min) axis_min = axis;
> SDL_PrivateJoystickAxis( js, axisnum, ((axis - axis_min) * 65536 / (axis_max - axis_min)) - 32768 );
> 
> I'm not entirely sure if this should be handled by SDL or if applications are expected to handle 'non-normalized axis'. Though I think ideally the default range of axis would be GameCube specific.

On 2019-06-19 13:48:15 +0000, Sam Lantinga wrote:

> Okay, I'll leave this bug open for you to investigate and propose a patch.
> 
> Thanks!

On 2019-07-30 17:49:38 +0000, Ryan C. Gordon wrote:

> 
> (Sorry if you get several emails like this, we're marking a bunch of bugs.)
> 
> We're hoping to ship SDL 2.0.11 on a much shorter timeframe than we have historically done releases, so I'm starting to tag bugs we hope to have closed in this release cycle.
> 
> Note that this tag means we just intend to scrutinize this bug for the 2.0.11 release: we may fix it, reject it, or even push it back to a later release for now, but this helps give us both a goal and a wishlist for the next release.
> 
> If this bug has been quiet for a few months and you have new information (such as, "this is definitely still broken" or "this got fixed at some point"), please feel free to retest and/or add more notes to the bug.
> 
> --ryan.

On 2019-09-20 20:47:36 +0000, Ryan C. Gordon wrote:

> 
> We're changing how we do SDL release versions; now releases will be even numbers (2.0.10, 2.0.12, etc), and as soon as we tag a release, we'll move the internal version number to an odd number (2.0.12 ships, we tag the latest in revision control as 2.0.13 immediately, which will become 2.0.14 on release, etc).
> 
> As such, I'm moving the bugs tagged with target-2.0.11 to target 2.0.12. Sorry if you get a lot of email from this change!
> 
> Thanks,
> --ryan.

On 2019-09-20 20:48:44 +0000, Ryan C. Gordon wrote:

> 
> We're changing how we do SDL release versions; now releases will be even numbers (2.0.10, 2.0.12, etc), and as soon as we tag a release, we'll move the internal version number to an odd number (2.0.12 ships, we tag the latest in revision control as 2.0.13 immediately, which will become 2.0.14 on release, etc).
> 
> As such, I'm moving the bugs tagged with target-2.0.11 to target 2.0.12. Sorry if you get a lot of email from this change!
> 
> Thanks,
> --ryan.

On 2019-12-12 00:59:46 +0000, Sam Lantinga wrote:

> To be clear, the idea is that calibrated values span the whole range of the axis.
> 
> Some autocalibration systems will use a clamped range and expand it out as they see larger values. That won't help with center offset though... ?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
