### ISSUE TITLE
Optionally disable the Windows key when capturing keyboard and enabled?

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3340]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2019-07-25 08:26:40 +0000,  wrote:

> Is it possible to capture the Windows key in SDL when capturing the keyboard using a hint?
> 
> I'm handling the LGUI and RGUI keys in my application using a matrix of keys, but they won't show up because Windows handles them internally and they don't reach the app(as well as taking focus from the app because it's handling it through explorer.exe).
> 
> Perhaps making it optional to enable and disable the windows key capturing?
> 
> I've found this: https://programmersheaven.com/discussion/362851/using-keyboard-hooks-how-do-i-disable-the-windows-key
> 
> As well as: http://www.cplusplus.com/forum/general/217945/
> 
> Both seem to implement the same method, handling the windows events through a keyboard hook?

On 2019-07-30 17:35:13 +0000, Sam Lantinga wrote:

> Yes, you're welcome to submit a patch that does this.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
