### ISSUE TITLE
SDL_GetError causing memory leaks

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3354]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-08-02 12:54:35 +0000,  wrote:

> When using SDL_GetError() my memory leak checker returned this  
> New fresh storage (type char *) passed as implicitly temp (not
>                     released): SDL_GetError()
>   A memory leak has been detected. Storage allocated locally is not released
>   before the last reference to it is lost. (Use -mustfreefresh to inhibit
>   warning)
> 
> Im assuming this memory leak caused my programs to randomly segfault when using SDL_GetError() as the program had no issues running once it was was deleted.
> 
> this happened with SDL_Log and printf.
> 
> my operating system is: anarchy linux x86_64 Linux 5.2.5-arch1-1-ARCH using X11 and XFCE4 DE

**Comment by 0ric1** [comment]
SDL_ClearError only sets error to 0, but does not free the allocated memory in function SDL_GetErrBuf:
```
        errbuf = (SDL_error *)SDL_malloc(sizeof(*errbuf));
```
and there is no function SDL_FreeErrorBuf that can be called to free the allocated buffer.

**Comment by icculus** [comment]
@slouken Have we decided that making SDL_TLSCleanup a public function in fb283a732a11a4ccd6ebcfbe3cd671844b5b92e6 solves this? Or do we still want to try to clean up the error buffer during SDL_Quit()?

**Comment by icculus** [comment]
Bumping this to 2.0.18, so we can consider it more carefully. SDL_Quit probably isn't where to handle this.

**Comment by slouken** [comment]
To fix this we need to add a new API, since the error buffer is actually allocated by SDL_malloc()
Keep in mind that the memory allocators might actually change at runtime - see SDL_SetMemoryFunctions()

**Comment by slouken** [comment]
Actually, this is already taken care of, just call SDL_TLSCleanup(), it will free the error buffer.
