### ISSUE TITLE
SDL_WaitEvent() randomly stalls with events pending (2.0.10 regression)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3355]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-08-02 19:44:46 +0000, Andrew Church wrote:

> In SDL 2.0.10, SDL_WaitEvent() can stall for a short but noticeable period of time (200-300ms?) even while events are pending.  I observed this as seeing joystick input seem to drop out once every few seconds using a udev-based controller (specifically a Sony DualShock 3).
> 
> This does not occur in SDL 2.0.9.
> 
> Sample code (spin an analog stick and watch for the event counter to pause):
> -----------------------------------------------------
> #include <assert.h>
> #include <stdio.h>
> #include <SDL2/SDL.h>
> int main(void)
> {
>     int counter = 0;
>     SDL_Init(SDL_INIT_EVERYTHING);
>     assert(SDL_NumJoysticks() >= 1);
>     SDL_Joystick *js = SDL_JoystickOpen(0);
>     assert(js);
>     for (;;) {
>         SDL_Event event;
>         SDL_WaitEvent(&event);
>         printf("event %d\n", counter++);
>     }
> }
> -----------------------------------------------------

On 2019-08-06 06:49:45 +0000, Sam Lantinga wrote:

> Ryan, can you look at this ASAP?

**Comment by slouken** [comment]
I believe this is fixed in 2.0.18. Please reopen this bug if you are still seeing this.
