### ISSUE TITLE
Resize regression with 52dddda6fba7 when exiting fullscreen

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3363]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2019-08-12 05:06:52 +0000,  wrote:

> 52dddda6fba7 introduced a bug where the the video is not resized when the window size is changed from full screen to windowed.
> 
> This bug was originally reported to FFmpeg here: https://trac.ffmpeg.org/ticket/8072

On 2019-08-12 07:38:14 +0000, Ozkan Sezer wrote:

> Adding Ethan Lee (commit author) to CC list.

On 2019-08-13 01:59:08 +0000, Ethan Lee wrote:

> This revision was made to resolve Bug 4227.
> 
> Without looking at their source it may be expecting a RESIZED when fullscreen is toggled, but I don’t know if they use FULLSCREEN_DESKTOP, or if their window size is reapplied on fullscreen toggle, or if the window is resizable, or what have you... do we have a small repro case for this?

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
