### ISSUE TITLE
Direct3D 11 renderer emits error message when created

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3370]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Sample initialization (test.cpp, text/plain, 2019-08-19 13:59:17 +0000, 464 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3927)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-08-19 13:59:17 +0000, Alex wrote:

> Created attachment 3927
> Sample initialization
> 
> When creating a Direct3D 11 renderer you get some error messages. They are visible if debug logs are enabled.
> 
> Here is an output from Visual Studio:
> 
> ```
> D3D11 ERROR: ID3D11Device::CreateBuffer: The Dimensions are invalid. ByteWidth cannot be 0. [ STATE_CREATION ERROR # 66: CREATEBUFFER_INVALIDDIMENSIONS]
> D3D11 ERROR: ID3D11Device::CreateBuffer: CreateBuffer returning E_INVALIDARG, meaning invalid parameters were passed. [ STATE_CREATION ERROR # 69: CREATEBUFFER_INVALIDARG_RETURN]
> DEBUG: __FUNCTION__, ID3D11Device1::CreateBuffer [vertex buffer]: The parameter is incorrect.
> INFO: Created renderer: direct3d11
> ```

On 2019-08-19 16:43:49 +0000, Alex wrote:

> It seems like ignoring commands without vertex data. Because code like this:
> 
> ```c
> SDL_RenderClear(renderer);
> SDL_RenderFlush(renderer);
> ```
>
> just doesn't work.
> 
> So I looked at the sources and found this code:
> 
> ```c
> if (D3D11_UpdateVertexBuffer(renderer, vertices, vertsize) < 0) {
>     return -1;
> }
> ```
>
> Then changed into:
> 
> ```c
> if (vertsize > 0 && D3D11_UpdateVertexBuffer(renderer, vertices, vertsize) < 0) {
>     return -1;
> }
> ```
>
> Now works as expected but I'm not sure!

**Comment by slouken** [comment]
This was fixed with https://github.com/libsdl-org/SDL/commit/1ce1364b29e90af81133c0ddcb4a92d9e81f6b49.
