### ISSUE TITLE
In i3, game is rendered in a corner instead of the center.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3374]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-08-26 11:31:00 +0000, crocket wrote:

> Initially, game is rendered at the center of an i3 window.
> 
> After changing i3 layout, game is rendered in corners.
> 
> Refer to https://github.com/chocolate-doom/chocolate-doom/issues/1191 for screenshots.

On 2019-08-27 06:48:03 +0000, crocket wrote:

> Putting "export SDL_VIDEO_CENTERED=1" in ~/.profile and logging in again works around the issue.
> 
> 
> SDL_VIDEO_CENTERED centers a floating i3 window on the screen and centers the game in a tiled i3 window.

On 2019-08-27 07:04:56 +0000, crocket wrote:

> Correction // SDL_VIDEO_CENTERED doesn't center a game in a window.
> It only centers a window on a screen.

**Comment by icculus** [comment]
Pretty confident this is not an SDL bug.
