### ISSUE TITLE
Android: Alert dialog (Couldn't load hidapi: hidapi.so) is displayed when SDL is compiled with disabled hidapi

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3378]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2019-08-29 19:58:35 +0000, ZZ wrote:

> In connection to this: https://bugzilla.libsdl.org/show_bug.cgi?id=3918#c23
> 
> If SDL on Android is compiled with hidapi disabled an alert dialgo is displayed informing about missing hidapi.so
> 
> ```java
> private HIDDeviceManager(final Context context) {
>         mContext = context;
> 
>         // Make sure we have the HIDAPI library loaded with the native functions
>         try {
>             SDL.loadLibrary("hidapi");
>         } catch (Throwable e) {
>             Log.w(TAG, "Couldn't load hidapi: " + e.toString());
> 
>             AlertDialog.Builder builder = new AlertDialog.Builder(context);
>             builder.setCancelable(false);
>             builder.setTitle("SDL HIDAPI Error");
>             builder.setMessage("Please report the following error to the SDL maintainers: " + e.getMessage());
>             builder.setNegativeButton("Quit", new DialogInterface.OnClickListener() {
>                 @Override
>                 public void onClick(DialogInterface dialog, int which) {
> ```
> 
> I suggest that there is some option for the user to easily disable the use of hidapi in SDLActivity.java I created a custom variable that I can set in a class that inherits from SDLActivity so that I don't have to modify SDLs own source code:
> 
> ```java
>         if (isHIDAPIEnabled)
>         {
>             mHIDDeviceManager = HIDDeviceManager.acquire(this);
>         }
> ```
>
> Or maybe some other method could be employed like the Java code could query SDL for hidapi support and disable the above code automatically.

**Comment by icculus** [comment]
Not sure if hidapi is _always_ available now. If we can still build Android without it, this check makes sense. Otherwise, let's just close this bug as-is.

**Comment by slouken** [comment]
Yep, this code doesn't exist anymore.
