### ISSUE TITLE
[PATCH] Remove dependency on libudev.h

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3379]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to remove libudev header. (udev.patch, text/plain, 2019-08-30 11:56:48 +0000, 431 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3936)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-08-30 11:56:48 +0000,  wrote:

> Created attachment 3936
> Patch to remove libudev header.
> 
> Proposed patch to remove need to #include <libudev.h>, which was only needed for 3 struct forward declarations.
> 
> This mostly removes the need to have libudev installed to enable support, though there's still some configuration required to determine the SDL_UDEV_DYNAMIC define.

**Comment by slouken** [comment]
This is possible to do in the current SDL source, but not worth the effort. If someone wants udev support, they should install the udev development libraries. This is generally true for other SDL dependencies.
