### ISSUE TITLE
Direct3D 11 render target warnings

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3380]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Sample program (sample.c, text/plain, 2019-08-30 13:50:02 +0000, 1081 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3937)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-08-30 13:50:02 +0000, Alex wrote:

> Created attachment 3937
> Sample program
> 
> (In addition to bug # 4767)
> 
> When you render to a texture AFTER rendering it to screen you get these warnings:
> 
> D3D11 WARNING: ID3D11DeviceContext::OMSetRenderTargets: Resource being set to OM RenderTarget slot 0 is still bound on input! [ STATE_SETTING WARNING # 9: DEVICE_OMSETRENDERTARGETS_HAZARD]
> D3D11 WARNING: ID3D11DeviceContext::OMSetRenderTargets[AndUnorderedAccessViews]: Forcing PS shader resource slot 0 to NULL. [ STATE_SETTING WARNING # 7: DEVICE_PSSETSHADERRESOURCES_HAZARD]
> 
> I have searched the Internet for a solution. This for example: https://gamedev.stackexchange.com/a/95629
> 
> You may see the D3D11 code in comments inside the sample program. This code should fix it, I think.

**Comment by icculus** [comment]
We might have fixed this already, but I'll toss it into 2.24.0 in case I have time to look at it.

**Comment by slouken** [comment]
This is one of those cases where depending on where we move the setrendertargets call, we get different errors. I'm bumping this out of the 2.24.0 milestone for more investigation.

Luckily in production code this doesn't cause any issues that I'm aware of.
