### ISSUE TITLE
Feature request: please allow disabling virtual keyboard on Android even when using SDL_StartTextInput()

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3383]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Android (All), x86_64

# Comments on the original bug report:

On 2019-09-01 14:06:14 +0000, Ellie wrote:

> Here it was described that SDL_StartTextInput() is now tied together with showing the virtual keyboard: https://discourse.libsdl.org/t/on-screen-keyboard-change/19216
> 
> However, I now have the following problem:
> 
> - I have a custom cross-platform simplified virtual keyboard written in SDl2/in-app to have one for use with xbox controller (for entering high score abbreviations etc with just the controller)
> 
> - Since I want things to work with e.g. xbox controllers on Android too I HAVE to use this custom keyboard on Android I think. But even otherwise I would also still want to, for keeping it uniform and since nobody will enter like emails or novels where full international input would be super important anyway
> 
> - However, I also want to support enabling the hardware keyboard at the same time for user convenience, and I want things like ':' to work. And this can differ depending on layout and may or may not involve checking the shift modifier etc., so not sure how practical this is to do manually. I'd rather use the text input event, but that would bring up the second native android virtual keyboard...
> 
> Combined this means my best solution appears to be to use SDL_StartTextInput() but WITHOUT showing the native/android virtual keyboard, so exactly what apparently was removed from SDL2 in 2012.
> 
> Is there any chance this separation can be reintroduced in some form? Maybe a hint would work to just disable ever bringing up the virtual keyboard altogether?

**Comment by ericoporto** [comment]
Solved by https://github.com/libsdl-org/SDL/commit/a6a222095e85e179209b9badb611c3dbdb16ccc6
