### ISSUE TITLE
cannot get IME target range

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3385]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [implement target range in edit event (target.diff, text/plain, 2019-09-02 14:17:35 +0000, 6536 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3945)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, All

# Comments on the original bug report:

On 2019-09-02 14:17:35 +0000, tamo wrote:

> Created attachment 3945
> implement target range in edit event
> 
> Looking at bug 4782, I found that SDL didn't provide a way to get IME target range.
> (I had thought I could get it as event.edit.start and event.edit.length, but they are just a readingstring range, which Japanese IMEs rarely use.)
> 
> You can see what the "target" means by seeing the picture attached to bug 4782.
> To liken IME to an translator, she may translate "I love you" to "Je vous aime." But you may tell her to use "te" instead of "vous." In this case, your target is "vous."

**Comment by slouken** [comment]
@Susko3, is this something that you're able to take a look at?

**Comment by Susko3** [comment]
I can take a look. The proposal looks similar to what I've worked on in osu!framework (Windows-specific handling)

But IME can be a hard topic to work on, as it's specific to different languages, and different platforms/operating systems might have different requirements .

I think it's best to investigate how things currently stand. And not jump into fixes and changes too soon.

For making changes, I think it's useful to look at how web browsers are handling it, as their wide audience and global reach mean that their IME code is well tested and has most of the common issues and pitfalls ironed out.

**Comment by slouken** [comment]
That's a good point. There is a large number of IME bugs that have accumulated and I've put them in the 3.2.0 milestone for us to look at. Maybe it's worth looking at them all together to understand what issues there are?

**Comment by slouken** [comment]
This is implemented in the latest code. The target selection is sent when the cursor is at the beginning of the selection. This works with all the IME test cases I know of, but feel free to reopen this if there's a case this doesn't properly handle.

**Comment by slouken** [comment]
@Susko3, can you let me know if this works for you? I'd be interested to know if osu!framework's Windows specific code can be removed now?
