### ISSUE TITLE
Linux accelerometers no longer available as joysticks

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3387]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Support SDL_HINT_ACCELEROMETER_AS_JOYSTICK on Linux (accelerometer.patch, text/plain, 2019-09-05 05:32:00 +0000, 1067 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3952)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-09-05 05:32:00 +0000, Daniel Drake wrote:

> Created attachment 3952
> Support SDL_HINT_ACCELEROMETER_AS_JOYSTICK on Linux
> 
> A long time ago, it was possible to play neverball on Linux using the accelerometer found in HP laptops.
> 
> The kernel exposes the accelerometer as a joystick (/dev/input/jsX) as well as an evdev device (/dev/input/eventX). I guess it worked fine when SDL was using the js interface, but then stopped working here: http://hg.libsdl.org/SDL/rev/fdaeea9e7567
> 
> Looking at current code which uses udev to discover joysticks, it looks for the udev tag ID_INPUT_JOYSTICK.
> 
> However udev's internal input_id logic specifically tags accelerometers as ID_INPUT_ACCELEROMETER and nothing else.
> 
> This looks like a good fit for SDL_HINT_ACCELEROMETER_AS_JOYSTICK.

On 2019-09-06 15:43:15 +0000, Sam Lantinga wrote:

> Looks good to me, thanks!
> https://hg.libsdl.org/SDL/rev/211e1b06ec47

**Comment by AnterCreeper** [comment]
why not use iio-sensor-proxy to read data from sensor?
