### ISSUE TITLE
Sounds do not play properly

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3396]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2019-09-10 22:45:38 +0000,  wrote:

> For whatever reason this version of SDL is not functioning properly in the application it is being used in.
> 
> I originally reported this issue here:
> https://github.com/fabiangreffrath/crispy-doom/issues/454
> 
> Please direct me as to what other useful information i can provide to solve this problem.
> 
> Please also re-categorize this bug report as necessary.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
