### ISSUE TITLE
Getting both mouse events and finger events

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3400]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Example that does not reproduce the error. (test_touch_event.cpp, text/x-c++src, 2019-09-15 12:38:20 +0000, 998 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3970)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2019-09-15 12:38:20 +0000, Moritz Bruder wrote:

> Created attachment 3970
> Example that does not reproduce the error.
> 
> I'm using a Raspberry Pi with an ADS7846 touchscreen running an SDL application on top of an xserver:
> 
> [alarm@pi src]$ export DISPLAY=:0.0 
> [alarm@pi src]$ xinput
> ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
> ⎜   ↳ ADS7846 Touchscreen                     	id=6	[slave  pointer  (2)]
> ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
>     ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
> 
> However, since 2.0.10 (sdl2-2.0.10-1 archlinuxarm) I get duplicated events. That is, I receive both mouse events and finger events. I did some simple print output debugging in my program (this is after i touched it once):
> 
> event.type = 1024 SDL_MOUSEMOTION
> event.type = 1025 SDL_MOUSEBUTTONDOWN
> event.type = 1792 SDL_FINGERDOWN
> event.type = 1024 SDL_MOUSEMOTION
> event.type = 1794 SDL_FINGERMOTION
> event.type = 1024 SDL_MOUSEMOTION
> event.type = 1794 SDL_FINGERMOTION
> event.type = 1024 SDL_MOUSEMOTION
> event.type = 1794 SDL_FINGERMOTION
> event.type = 1026 SDL_MOUSEBUTTON_UP
> event.type = 1793 SDL_FINGERUP
> event.type = 32768 SDL_USEREVENT
> event.type = 32768 SDL_USEREVENT
> 
> I tried this with a simple application but unfortunately I can't reproduce the behavior (there I only get touch events). Maybe you can give me some pointers on how to debug this further.
> 
> In my application where it occurs I use user events (but I only ever push them).
> * This is where I setup SDL: https://github.com/muesli4/mpd-touch-screen-gui/blob/36ebdb473e2a145bcf425156f7de3b062e7a2acc/src/main.cpp#L55
> * This is where I handle the specific events: https://github.com/muesli4/libwtk-sdl2/blob/09b736a9ae9ffe13fd3bc2f9a66258d9f8153685/src/widget_context.cpp#L44

On 2019-09-16 10:10:50 +0000, Sylvain wrote:

> Hi,
> how are set the hints 
> 
> SDL_HINT_TOUCH_MOUSE_EVENTS
> SDL_HINT_MOUSE_TOUCH_EVENTS
> 
> https://hg.libsdl.org/SDL/file/2ede888544ac/include/SDL_hints.h#l313
> 
> please log also the 
> id: TouchId and MouseId
> 
> https://hg.libsdl.org/SDL/file/2ede888544ac/include/SDL_events.h#l438
> https://hg.libsdl.org/SDL/file/2ede888544ac/include/SDL_events.h#l258
> 
> also, try the latest SDL, and do you know which sdl code is used with xserver ?
> 
> see bug 1612 
> because it triggers SendMouseMotion in EnterNotify and LeaveNotify
> https://hg.libsdl.org/SDL/annotate/84bbd421d62f/src/video/x11/SDL_x11events.c#l315
> which might be incorrect or inconsistent with other backends

On 2019-09-16 10:12:18 +0000, Sylvain wrote:

> Besides, using atexit + SDL_Quit has proved to cause some trouble
> 
> https://github.com/muesli4/mpd-touch-screen-gui/blob/36ebdb473e2a145bcf425156f7de3b062e7a2acc/src/main.cpp#L62

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
