### ISSUE TITLE
SDL_main

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3403]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Android (All), All

# Comments on the original bug report:

On 2019-09-23 12:37:33 +0000,  wrote:

> I'm trying to run a test-SDL2-project with my Android Studio 3.5
> (Build #AI-191.8026.42.35.5791312, built on August 9, 2019, JRE: 1.8.0_202-release-1483-b49-5587405 amd64, JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.15.0-64-generic (Ubuntu 18.04)) as instructed in the android-readme with SDL 2.0.10.
> 
> The project builds without any errors. However, when I try to run my super simple test-app (SDL_Init, SDL_Delay for 10 sec., SDL_Quit), I get this error in Logcat:
> 
> E/SDL: nativeRunMain(): Couldn't find function SDL_main in library /data/app/org.libsdl.app--Lrz...k0CA==/lib/x86/libmain.so

On 2019-09-24 10:25:03 +0000, Sylvain wrote:

> Try "objdump -t your_path/libmain.so | grep main"
> You should have a "SDL_main" inside.
> 
> 
> In you c file where "main()" is defined, add an include of SDL.h so that it transforms main() into SDL_main().

**Comment by 1bsyl** [comment]
closing
