### ISSUE TITLE
Static Library with CMake Broken

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3413]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-10-07 06:30:21 +0000, Ryan Edward wrote:

> Hi there,
> I’m on windows 10, using clang + mingw.
> I recently attempted to update to sdl2.0.10. I invoke the following command:
> 
> cmake.exe -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles"^
>         -DCMAKE_C_FLAGS="-target x86_64-windows-gnu"^
>         -DCMAKE_C_COMPILER_ID="Clang" -DCMAKE_C_COMPILER="clang.exe"^
>         -DCMAKE_CXX_FLAGS="-target x86_64-windows-gnu"^
>         -DCMAKE_CXX_COMPILER_ID="Clang++" -DCMAKE_CXX_COMPILER="clang++.exe"^
>         -DDIRECTX=OFF -DSDL_TEST=OFF -DSDL_SHARED=OFF -DSDL_STATIC=ON ..
> 
> cmake.exe --build . -- -j %NUMBER_OF_PROCESSORS%
> 
> This produces un-usable ‘.lib’ files, specifically SDL2maind.lib and SDL2d.lib. Performing the same invocation on sdl2.0.9 gives usable ‘.a’ files, specifically libSDL2maind.a and libSDL2d.a. If this is a problem, could someone give me a link to an archived sdl2.0.9 source?
> 
> Thanks.

**Comment by madebr** [comment]
@ryanedwards (if you aren't the OP, sorry for the nuisance)

MinGW (using gcc) is currently tested using GitHub CI so it should work.
Pre-built MinGW development libraries are available in [GitHub releases](https://github.com/libsdl-org/SDL/releases) and on the [libsdl.org website](https://libsdl.org/download-2.0.php).
(you need the SDL2-devel-2.0.xx-mingw.zip archive)
