### ISSUE TITLE
XInput relative motion incorrect with Wacom tablet

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3442]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-10-30 04:05:29 +0000, Jay Cornwall wrote:

> Relative motion in the XInput backend is implemented through XI_RawMotion events. The backend currently assumes these events report relative motion at screen scale. A Wacom tablet instead reports absolute RawMotion events at much higher DPI:
> 
> Device 11
> Class 2
>         Range: 0.000000 - 44704.000000
>         Resolution: 200000 units/m
>         Mode: absolute
>         Current value: 13423.000000
> 
> To fix this we could record the mode/range and emulate screen-scale relative motion from absolute XI_RawMotion events, if the screen scale is known.
> 
> Alternatively we could emulate relative motion through the the post-scaled absolute XI_Motion event when only absolute XI_RawMotion events are available. I think this makes more sense.
> 
> I could have a go at this but wanted to check if there are good reasons to use XI_RawMotion?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
