### ISSUE TITLE
SDL appears to use enums instead of enum classes

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3454]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2019-11-19 19:07:51 +0000, Alex wrote:

> When I compile my code in Visual Studio, I get the following warnings:
> Warning	C26812	The enum type 'SDL_Scancode' is unscoped. Prefer 'enum class' over 'enum'
> and	
> Warning	C26812	The enum type 'SDL_Bool' is unscoped. Prefer 'enum class' over 'enum'
> 
> The discussion at the bottom of the  MSDN page for this warning suggests that developers should report this as a bug in APIs, so here I am.

On 2019-12-04 06:35:30 +0000, Sam Lantinga wrote:

> Maybe we need an SDL_ENUM definition that resolves to enum in C and enum class for C++ at the appropriate revision?
> 
> Alex, what version of Visual Studio are you running?

On 2019-12-04 16:53:58 +0000, Alex wrote:

> I'm running what I believe to be the latest version: Visual Studio Community 2019 Version 16.3.9

On 2019-12-04 19:23:02 +0000, Ryan C. Gordon wrote:

> (In reply to Alex from comment # 0)
> > The discussion at the bottom of the  MSDN page for this warning suggests
> > that developers should report this as a bug in APIs, so here I am.
> 
> With respect to Microsoft, but this is _not_ a bug in external APIs, it's a C++-specific, overaggressive compiler warning about a common API pattern. We should probably just disable this warning within the scope of the SDL headers.
> 
> Also, if we make these into "enum class" types, it'll break unsuspecting C++11 programs that include SDL.h and then try to do...
> 
>    SDL_bool x;
>    x = SDL_TRUE;
> 
> ...as this would become a compiler error. It would need to be "x = SDL_bool::SDL_TRUE;"
> 
> --ryan.

**Comment by icculus** [comment]
Closing this report, this change is a bad idea.

**Comment by tommai78101** [comment]
@icculus Hello, may I ask for clarification on what change is considered a bad idea?

1. Using SDL_ENUM definition that resolves to enum in C and enum class for C++ at the appropriate revision.
2. Disable overaggressive C++ compiler warnings about common API patterns within the scope of the SDL headers.
3. Both items above.

Which is it, it may be? 1, 2, or 3? Thanks, and appreciated.

**Comment by icculus** [comment]
Item 1 is the bad idea. The technical explanation is in the comments above.

(Further rant: it's also completely unacceptable for compilers to make changes like this and in the documentation encourage users to file bugs against other projects to work around these changes.)

**Comment by tommai78101** [comment]
Thank you for your clarification.
