### ISSUE TITLE
disconnecting and reconnecting game controller from/to system does not generate button/axis events

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3468]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-12-06 07:36:03 +0000, Rafael Kitover wrote:

> Disconnecting a game controller from the system generates an SDL_CONTROLLERDEVICEREMOVED event, and subsequently reattaching the controller generates an SDL_CONTROLLERDEVICEADDED event correctly.
> 
> However, even if the device is closed and reopened, there are no further events generated for e.g. button presses or axis motion for this controller in this scenario.
> 
> This is as opposed to connecting a controller with the application running, in that case the SDL_CONTROLLERDEVICEADDED event fires and subsequently button/axis events are also received.
> 
> The problem is present on both linux and windows with SDL 2.0.10.
> 
> I tested with an xbox 360 controller (wired and wireless.)
> 
> My apologies if I'm doing something wrong.

On 2019-12-24 15:16:21 +0000, Rafael Kitover wrote:

> I solved this problem in our app by falling back to polling the controllers on an interval after calling SDL_PollEvent().
> 
> The ADDED/REMOVED events allow for having a valid device handle.

On 2020-03-24 20:15:38 +0000, Ryan C. Gordon wrote:

> 
> Just to be clear, did you work around a problem in SDL or was this fixing the app to use the API correctly?  It's a common mistake to confuse device indexes and instance IDs for controllers. Plugging the same controller again will give it a different instance_id (and definitely can't use the existing SDL_GameController pointer without reopening the device).
> 
> I'm trying to decide if we have a bug to fix in SDL or if this bug can just be closed as resolved.
> 
> --ryan.

On 2020-03-25 00:00:09 +0000, Rafael Kitover wrote:

> This is my joystick handler:
> 
> https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/wx/widgets/wx/sdljoy.h
> 
> https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/wx/widgets/sdljoy.cpp
> 
> As far as I know I am following the API correctly.
> 
> I am closing the device and obtaining a new device pointer on a device added event. I've tried various variations of this, and it makes no difference.

**Comment by AfzalivE** [comment]
I've been able to track this bug down (I think) to [this commit](https://github.com/libsdl-org/SDL/commit/5b3616c325c4461fe7e038706502ff6c300f539d) in SDL, where `SDL_rawinputjoystick.c` was refactored (among other things).

It's reproducible in the [testgamecontroller.c](https://github.com/libsdl-org/SDL/blob/release-2.26.5/test/testgamecontroller.c?rgh-link-date=2023-05-27T00%3A19%3A25Z) test program.

In `SDL_rawinputjoystick.c`, when calling `RAWINPUT_UpdateOtherAPIs()` after `RAWINPUT_JoystickOpen()`, `RAWINPUT_UpdateXInput()` gets called, which tries to get the capabilities using `XINPUTGETCAPABILITIES()`.

That function is what causes the controller to shut off.

A workaround is to call `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");` and switch to XInput. In fact, that's what Yuzu does too but Ryujinx doesn't, and it also faces this bug.

**Comment by slouken** [comment]
That's very strange that calling `XINPUTGETCAPABILITIES()` on an Xbox 360 controller would stop input, but XInput would continue working. Does this specific controller have a driver mode that's either raw input or XInput?

**Comment by AfzalivE** [comment]
It's an Xbox One Controller, so it should have one of them, right? How do I check the driver mode?

**Comment by kanedauy** [comment]
> It's a Microsoft Xbox One Controller, so it should have one of them, right? How do I check the driver mode?

It happens with the Xbox Series Controller also

**Comment by slouken** [comment]
I haven't seen this behavior here. What version of Windows are you guys running?

**Comment by AfzalivE** [comment]
Windows 11.

**Comment by slouken** [comment]
> Windows 11. If you can, try doing this in the `testgamecontroller.c` program.
> 
> 1. Start the program.
> 2. Turn on the Xbox Series X controller (title bar will update to show the new controller).
> 3. Hold the guide button to turn off the controller.
> 4. Turn the controller again.
> 
> It will turn off after turning on.

Okay, I'm running Windows 11 22H2, with a Microsoft Series X controller with firmware version 5.15.3168, connected via Bluetooth, and tried exactly those steps, touching nothing else on the controller, and it worked fine. It connected the first time, connected the second time, didn't turn off, and all inputs on the controller worked as expected. I then updated to the latest firmware using the Xbox Accessories App, to version 5.17.3202 and got the same result.

What am I missing?

**Comment by AfzalivE** [comment]
I guess the only thing different, then, is that I'm connecting using the Xbox One Wireless Adapter instead of bluetooth.

**Comment by slouken** [comment]
Interesting. I can reproduce this with the Xbox One Wireless Adapter. Investigating...

**Comment by slouken** [comment]
It looks like the issue really is trying to use XInput and raw input at the same time. WGI works, but the XInput calls turn the controller off, and only when the Xbox One Wireless Adapter is being used.

If you edit SDL_rawinputjoystick.c and comment out `#define SDL_JOYSTICK_RAWINPUT_XINPUT` at the top, does that fix all issues for you, @AfzalivE and @kanedauy?

**Comment by AfzalivE** [comment]
Can confirm that the fix works! Thank you, and also thank you for porting it to SDL2 as well!

**Comment by kanedauy** [comment]
Thanks a lot @slouken!, seems to work

**Comment by slouken** [comment]
Great, thanks!

**Comment by AfzalivE** [comment]
@slouken , do you know when the next SDL 2 version will be released please?

**Comment by slouken** [comment]
We are working on the last few bugs before release. :)
