### ISSUE TITLE
Android backspace key not working on Pixel 3 native keyboard

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3474]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2019-12-09 16:10:34 +0000, MatD wrote:

> We’re not getting any events from the backspace key on the Android soft keyboard, for quite a few newer Android devices (eg. Google Pixel 3).

On 2019-12-10 09:24:01 +0000, Sylvain wrote:

> I'd say, put some trace in the SDLActivity.java file, in onBackPressed()

On 2019-12-10 11:32:19 +0000, MatD wrote:

> Hi Sylvain, thanks for the quick reply.
> 
> I can confirm (from using breakpoints in SDLActivity.java) that...
> 
> On A Nexus 7 running Android 6.0.1, the soft-keyboard delete key triggers:
> 
> sendKeyEvent (line 1592) followed by
> dispatchKeyEvent (line 375) followed by 
> onKey (line 1537)
> 
> But on a Google Pixel 3a with Android 10, the delete key triggers sendKeyEvent then dispatchKeyEvent but *not* onKey.
> 
> Does this help?
> Kind regards
> -Mat

On 2019-12-10 12:12:30 +0000, MatD wrote:

> (In reply to MatD from comment # 2)
> > Hi Sylvain, thanks for the quick reply.
> > 
> > I can confirm (from using breakpoints in SDLActivity.java) that...
> > 
> > On A Nexus 7 running Android 6.0.1, the soft-keyboard delete key triggers:
> > 
> > sendKeyEvent (line 1592) followed by
> > dispatchKeyEvent (line 375) followed by 
> > onKey (line 1537)
> > 
> > But on a Google Pixel 3a with Android 10, the delete key triggers
> > sendKeyEvent then dispatchKeyEvent but *not* onKey.
> > 
> > Does this help?
> > Kind regards
> > -Mat
> 
> 
> As a workaround, we have added the following to dispatchKeyEvent:
> 
>         if(keyCode == KeyEvent.KEYCODE_DEL)
>         {
>             if(event.getAction() == KeyEvent.ACTION_DOWN)
>                 SDLActivity.onNativeKeyDown(keyCode);
>             else
>                 SDLActivity.onNativeKeyUp(keyCode);
>         }

On 2019-12-10 12:50:33 +0000, Sylvain wrote:

> Hi Mat, 
> 
> Not sure about the lines numbers. Which version is this ?
> Anyway, I would advice to try the head SDL version!
> 
> There are two onKey() methods: the normal one, another one in DummyEdit, which is triggered if you make the soft keyboard appears with  SDL_StartTextInput();
> 
> On the pixel 3a, how the backspace behave compared to another key ?

On 2019-12-10 12:51:54 +0000, Sylvain wrote:

> ( I tried on a recent phone with android 10 and the soft-keyboard backspace appears in the onKey on DummyEdit )

On 2019-12-10 13:15:30 +0000, MatD wrote:

> Thanks for trying that.
> 
> We are currently on 2.0.8, we will look at moving to the latest version.
> Regards
> -Mat

On 2019-12-19 13:07:15 +0000, Sylvain wrote:

> maybe an issue with focus when hiddin the keyboard
> see bug 4906

On 2020-10-07 07:10:22 +0000, Sylvain wrote:

> Do you have more information ?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
