### ISSUE TITLE
Keyboard event doesn't return sym value when "nonusbackslash" key is pressed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3476]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2019-12-10 19:01:55 +0000, rosenrost wrote:

> I am running Hatari, an Atari ST emulator, on my Raspberry Pi 3B. Hatari uses SDL2 in order to display graphics without X11. I am using a German keyboard which has a key next to the left shift key that is missing on US keyboard layouts. This key is not recognized by Hatari.
> 
> After adding some debug messages to Hataris keyboard handling functions, I discoverd that the keyboard event returns 0 in the sym field of the SDL_keysym structure, while the correct scan code (100) is returned in the scancode field of that structure.
> 
> In my case (German keyboard layout, but it's the same on any western European keyboard except UK), the the characters "<" and ">" are mapped to this key, so I really need it. So, SDL_keysym.sym should be 60 and not 0.

On 2019-12-11 15:23:53 +0000, rosenrost wrote:

> Oh, I forgot to mention that the RPI driver is used.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
