### ISSUE TITLE
SDL doesn't center window correctly when taskbar is placed vertically on side

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3480]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2019-12-17 11:28:00 +0000,  wrote:

> My laptop has a 1366x768 resolution (yeah, I know...) to get most vertical space out of it I've been used to put the Windows taskbar on side for years.
> 
> The remaining space is big enough to fit a window of 1280x720 (client area size), however when I try to create a 1280x720 window with SDL:
> 
> SDL.SDL_CreateWindow("SDL2 Window", SDL.SDL_WINDOWPOS_CENTERED, SDL.SDL_WINDOWPOS_CENTERED, 1280, 720, SDL.SDL_WindowFlags.SDL_WINDOW_SHOWN);
> 
> (I'm using SDL-CS binding for C#)
> 
> The window is placed as if the taskbar is at the bottom of the screen, which in my case (vertical taskbar on right side) the window is neither centered vertically (a bit too high, as if SDL assumes there's a taskbar at the bottom) nor centered horizontally (it is centered to the entire display width, not the area excluding taskbar)

**Comment by slouken** [comment]
We're going to go ahead and change centering to center on the usable area rather than the center of the monitor.
