### ISSUE TITLE
SDL2 used in scrcpy v1.10 and up not recognizing all mouse activities using SmartNav (a head controlled mouse)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3485]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-12-21 11:33:35 +0000, Alvin Lin wrote:

> all inputs from mouse using SmartNav on scrcpy version 1.10 to 1.12.1 (a phone mirroring app) doesn't work and it doesn't even recognize mouse cursor is moved if i have someone (since i can't physically use a normal mouse) clicking to emulate touch and me moving the mouse cursor using SmartNav/the head controlled mouse. overwriting SDL2.dll file from version 1.9 to the newest version fixed it.
> 
> below is SmartNav site link and scrcpy for reference if needed
> 
> SmartNav: https://www.naturalpoint.com/smartnav/
> scrcpy: https://github.com/Genymobile/scrcpy

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
