### ISSUE TITLE
SDL_SendKeyboardText skips '\r' and '\n' to be reported as text input.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3503]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-01-04 16:10:08 +0000, ongamex wrote:

> SDL_SendKeyboardText skips '\r' and '\n' to be reported as text input.
> 
> This happens because:
> int SDL_SendKeyboardText(const char *text) {
>  // ....
> /* Don't post text events for unprintable characters */
> if ((unsigned char)*text < ' ' || *text == 127) { // <---- HERE
>     return 0;
> }
> 
> The comment however doesn't describe why we need to do that.
> Is is because of some specific platform now reporting it?
> WINAPI reports these with WM_CHAR.
> 
> I need those events as I'm writing a text editor and I need these in text in some form.
> 
> Is there a workaround? Can this if be removed or better documented?

On 2020-01-04 17:51:43 +0000, Alex Szpakowski wrote:

> Can your code use SDL_KEYDOWN events for those? That approach has worked well for me in the past.

**Comment by slouken** [comment]
Whether the Return key performs navigation or enters text is application and context dependent, so we let the application handle the key rather than always provide it as text input.
