### ISSUE TITLE
NSOpenGLContext setView and update methods must be called from main thread

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3507]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [dispatch GL context updates to main thread (cocoa.patch, text/plain, 2020-01-08 20:31:59 +0000, 3036 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4155)

**Reported in version:** 2.0.15
**Reported for operating system, platform:** macOS 10.15, All

# Comments on the original bug report:

On 2020-01-08 00:27:46 +0000, Tim McDaniel wrote:

> Similar to bug 4714, but new as of macOS 10.15 when building with Mac SDK 10.15.
> 
> Calling NSOpenGLContext 'setView' or 'update' methods on a non-main thread will cause a hard crash (illegal instruction exception), so these methods must be called from the main thread.  The simple way to accomplish this is:
> 
> if ([NSThread isMainThread]) {
>     [super update]; // assuming super is an NSOpenGLContext
> } else {
>     dispatch_sync(dispatch_get_main_queue(), ^{ [super update]; });
> }
> 
> Note that the isMainThread check is necessary, since dispatch_sync to the main queue cannot be called on the main thread, because the main queue is already on the main thread, and this would cause deadlock.
> 
> This fix should be applied to all setView and update calls in SDL_cocoaopengl.m.
> 
> Similar fixes can be found in several projects online, such as:
> https://github.com/google/filament/pull/1959/commits/5d0bc0d5416e0da91ca06575fb1838ac01a97143
> 
> In bug 4714, some concern was expressed about the performance implications of dispatch_sync, particularly if SDL_GL_MakeCurrent might be called every frame.  This was perhaps a valid concern, but considering the alternative is now a crash, well...

On 2020-01-08 00:50:39 +0000, Tim McDaniel wrote:

> I should add: In our internal SDL fork, in Cocoa_GL_MakeCurrent, as an optimization we skip
> 
> [nscontext setWindow:window];
> [nscontext updateIfNeeded];
> 
> if the passed in window is the same as the nscontext's current window, since those calls are unnecessary in that case.

On 2020-01-08 15:18:36 +0000, Sam Lantinga wrote:

> Thanks, can you provide a tested patch?

On 2020-01-08 20:31:59 +0000, Tim McDaniel wrote:

> Created attachment 4155
> dispatch GL context updates to main thread
> 
> I can't vouch for the viability of this patch, as I have not tested it as-is.  I have removed some of our mods that would only muddy the waters, and are specific to our SDL fork.  Specifically, with our mods, we take explicit control of GL context updates by passing in a NULL window pointer to SDL_GL_MakeCurrent, which disables SDL's automatic context update mechanism (e.g. context update when window is resized) and causes an explicit forced update.

On 2020-04-07 18:29:38 +0000, Ryan C. Gordon wrote:

> 
> This patch looks reasonable to me.
> 
> With minor changes to make it apply, it's now https://hg.libsdl.org/SDL/rev/19c4516de68d, thanks!
> 
> --ryan.

On 2021-02-08 18:04:16 +0000, Thomas Altenburger wrote:

> Hello there,
> 
> Maintainer of MonoGame here. MonoGame uses SDL on macOS and we believe that this issue might not have been addressed properly.
> 
> We have a macOS build bot on the MonoGame repository which runs tests in threads with NUnit and since SDL 2.0.14 the tests are getting frozen upon calling SDL_GL_CreateContext (which never returns).
> 
> We assumed a threading issue and narrowed this down to these changes https://hg.libsdl.org/SDL/rev/19c4516de68d
> 
> Reverting them worked.
> 
> Cheers,
> Thomas

**Comment by mrhelmut** [comment]
@icculus I've been looking a bit more into this and I wonder if the blocking call may be ```Cocoa_GL_MakeCurrent``` within ```Cocoa_GL_CreateContext```.
https://github.com/libsdl-org/SDL/blob/main/src/video/cocoa/SDL_cocoaopengl.m#L303

**Comment by timmcd69** [comment]
The blocking call is certainly `Cocoa_GL_MakeCurrent`, which ultimately leads to '[NSOpenGLContext setView]' and/or '[NSOpenGLContext update]' being dispatched to the main thread (if you're running on a non-main thread), since both 'setView' and 'update' are required to be called only on the main thread, i.e. the UI thread.  AFAIK, this has always been a soft requirement, but with macOS 10.15 it became a hard requirement. The change rev you identified as your culprit is the one where this dispatch to the main thread was implemented. It sounds like your main thread is somehow blocking the handling of these dispatched calls.

**Comment by icculus** [comment]
...which is to say: it probably blocks until the main thread calls SDL_PollEvent() or SDL_PumpEvents().

**Comment by mrhelmut** [comment]
This all makes sense! In our case, the event pump doesn't run on the main thread but on another thread along with the context creation and presentation, which explains it.

We'll work out a way to pump events on the main thread.

Please consider this issue closed (I can't close it myself with the migration). Thanks!
