### ISSUE TITLE
SDL_WarpMouseInWindow does not work as expected

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3508]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-01-09 07:33:44 +0000,  wrote:

> int gx,gy;
> int wx,wy;
> int ww,wh;
> SDL_GetGlobalMouseState(&gx,&gy);
> printf("Global mouse state x: %d, y: %d\n",gx,gy);
> 
> SDL_GetWindowPosition(Window,&wx,&wy);
> printf("Window position x: %d, y: %d\n",wx,wy);
> 
> SDL_GetGlobalMouseState(&gx,&gy);
> printf("Global mouse state x: %d, y: %d\n",gx,gy);
> 
> SDL_GetWindowSize(Window,&ww,&wh);
> printf("Window size x: %d, y: %d\n",ww,wh);
> 
> SDL_GetGlobalMouseState(&gx,&gy);
> printf("Global mouse state x: %d, y: %d\n",gx,gy);
> 
> if (gx>=wx && gx<=(wx+ww) && gy>=wy && gy<=(wy+wh)) {
>     SDL_WarpMouseInWindow(Window,gx-wx,gy-wy);
> }
> 
> SDL_GetGlobalMouseState(&gx,&gy);
> printf("Global mouse state x: %d, y: %d\n",gx,gy);
> 
> 
> console output:
> Global mouse state x: 696, y: 431
> Window position x: 560, y: 300
> Global mouse state x: 696, y: 431
> Window size x: 800, y: 600
> Global mouse state x: 696, y: 431
> Global mouse state x: 696, y: 468
> 
> If mouse cursor is on top of the Window the cursor drops down 37 pixels which is the height of the window title bar.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
