### ISSUE TITLE
Number of screens don't get updated

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3509]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Possible fix, kinda hacky. (hackyfix.patch, application/mbox, 2020-01-10 21:02:06 +0000, 1682 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4156)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows (All), x86_64

# Comments on the original bug report:

On 2020-01-10 21:02:06 +0000,  wrote:

> Created attachment 4156
> Possible fix, kinda hacky.
> 
> Overview:
> When adding or removing a display SDL_GetNumVideoDisplays() doesn't change the number of displays, also resolutions don't change.
> 
> Steps to Reproduce:
> 1) Initialize the SDL System
> 2) SDL_GetNumVideoDisplays(); will return the active number of displays
> 3) Add or remove a display
> 4) Call SDL_GetNumVideoDisplays();
> 
> Actual Results:
> It will still have the same number of displays in step 2 as in step 4
> 
> Expected Results:
> It will have the new number of displays
> 
> Build Date & Hardware:
> SDL2-2.0.10-win32-x64.zip and windows 10.
> 
> Additional Builds and Platforms:
> Same happens for 32 bit, and all other windows versions
> 
> Additional Information:
> Windows has an WindowProc message called WM_DISPLAYCHANGE to handle this.
> Added is a patch that will fix it, but it's not clean, but we can't just remove all displays and then re-add them since SDL will close all windows.

On 2020-03-31 19:58:17 +0000,  wrote:

> Do you need any additional details for this?

On 2020-03-31 20:04:57 +0000, Ryan C. Gordon wrote:

> 
> My concern is that we probably can't change this until we break ABI in 2.1, since GetNumVideoDisplays can't change if an app is in the middle of using it.
> 
> But I have to think through this more (including if we should _actually_ be concerned in 2.0 about a race condition on the extraordinary event of display setup changing).
> 
> We definitely shouldn't just pretend there's a 720p display there if one suddenly vanishes.
> 
> --ryan.

On 2020-03-31 22:15:49 +0000, Sam Lantinga wrote:

> I think it's okay for us to change the number of displays and not worry about the race condition for now, as long as we cleanly return an error if we're passed a newly invalid index (which I think we do right now)

On 2020-06-27 20:38:25 +0000, Ryan C. Gordon wrote:

> 
> I'm going to bump this to 2.0.16. It's worth doing, but it's more involved than I want to mess with for this release.

**Comment by icculus** [comment]
We added events and API promises to manage display hotplug in recent times, so this can be closed.
