### ISSUE TITLE
Keys can get stuck in pressed state

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3512]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows (All), All

# Comments on the original bug report:

On 2020-01-13 14:00:12 +0000, Rokas Kupstys wrote:

> Steps:
> 1. Open SDL application and have it's window focused.
> 2. Press LGUI+v
> 
> Result:
> Builtin windows clipboard utility pops up and SDLK_LGUI is not reported as released even though GetKeyState(VK_LWIN) does report key as released.
> 
> Expected result:
> SDL should report SDLK_LGUI as released.
> 
> Cause:
> Win32 does not send WM_KEYUP message.
> 
> Originally reported at: https://github.com/ocornut/imgui/issues/2976

On 2020-01-13 14:47:47 +0000, Rokas Kupstys wrote:

> Actually this is true for every key. If key is released while window does not have focus VM_KEYUP will not be sent to that window.

On 2020-01-17 11:00:27 +0000, Rokas Kupstys wrote:

> For reference, this is how GLFW fixed it: https://github.com/glfw/glfw/commit/562c17d131bd99d92f1166e2a8a42d7af023d122

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
