### ISSUE TITLE
[WIN32] Key presses with unset scancode get ignored

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3513]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows (All), All

# Comments on the original bug report:

On 2020-01-13 16:08:42 +0000, Rokas Kupstys wrote:

> Windows clipboard (Win+v) sends windows messages for CTRL+v with no scancode set. These key presses are lost because scancode is used to translate key press to SDL key.

On 2020-01-17 11:00:03 +0000, Rokas Kupstys wrote:

> For reference this is how GLFW fixed it: https://github.com/glfw/glfw/commit/789a2bcb3985a882944f3ae8dc6aa8aa22a23494

**Comment by slouken** [comment]
This is fixed in 98582dca02f99886e81081205afd7f6337e86ca4
