### ISSUE TITLE
Getting mouse ID == 0 from touch events

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3522]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-01-24 15:10:04 +0000, Marius Elvert wrote:

> This is on a microsoft surface 2017 on Windows 10.
> 
> When using the touch input, most of the mouse events I'm getting are marked with SDL_TOUCH_MOUSEID, but I also get a few with mouse ID equal to 0 regularly. This is for motion, button-down and button-up events.
> 
> It worked fine a while ago when I last tested it with SDL 2.0.9. I cannot say whether a windows update or the SDL update caused this.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
