### ISSUE TITLE
Audio recording sounds wrong on raspbian

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3538]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2020-02-13 05:33:53 +0000, Rene Dudfield wrote:

> I had a problem with audio recording on raspbian playing back all scratchy-robot-like. Tried two different USB sound cards.
> 
> I haven't confirmed yet with the latest hg... only with their included libsdl version. Will add more details here as I investigate more.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
