### ISSUE TITLE
Steam fails to start with 10 bit color precision per subpixel

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3539]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [How steam looks with 30 bit color per pixel (74376712-8b177100-4dda-11ea-8fac-4f890d650ad8.png, image/png, 2020-02-13 12:19:34 +0000, 13758 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4209)

**Reported in version:** don't know
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-02-13 12:19:34 +0000, m wrote:

> Created attachment 4209
> How steam looks with 30 bit color per pixel
> 
> Currently if trying to run steam with 30 bit color per pixel using the nvidia proprietary drivers the app will not run.
> I have tried running steam with "SDL_VIDEO_X11_VISUALID=xyz steam" as sugested on the github bug report and the only effect that it has is that it shows a window with the colors showned in the attachment.

**Comment by slouken** [comment]
This is not an SDL bug.
