### ISSUE TITLE
IBus: Text editing events don't work correctly, start is not set to cursor position

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3577]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2020-03-09 16:59:59 +0000,  wrote:

> Instead it's used in a wrong way, which would allow infinite text lengths
> 
> See file `SDL_ibus.c`, second half of function `IBus_MessageHandler`

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
