### ISSUE TITLE
Closing window in full screen mode leaves empty desktop

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3582]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Screen grab of mission control with a blank desktop, showing the minimize button. (Black.png, image/png, 2020-03-11 18:03:33 +0000, 58390 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4248)

**Reported in version:** don't know
**Reported for operating system, platform:** macOS 10.15, x86

# Comments on the original bug report:

On 2020-03-11 18:03:33 +0000,  wrote:

> Created attachment 4248
> Screen grab of mission control with a blank desktop, showing the minimize button.
> 
> In the game Factorio, the following triggers the bug I'm describing:
> - Start application
> - Put application in full screen mode
> - Perform updates. This will close the window and open a new one.
> 
> Result: The window that was closed leaves a blank (= black) desktop behind in macOS mission control. macOS behaves a bit strange when you try to activate this desktop. This was reported on their forum (https://forums.factorio.com/viewtopic.php?f=48&t=70191), but they replied that it's an SDL bug/problem.
> 
> Expected behaviour: the desktop should be removed the moment the window is closed.
> 
> Work around: When the application is closed, the empty desktop(s) disappear as well. Also it is possible to minimize the blank desktops from mission control, which will also cause them to cease to exist.
> 
> Note: Since I'm not the developer I don't know the version of SDL, but of course I expect it's the most recent stable release.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
