### ISSUE TITLE
Compile for Android using NDK r21 fails

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3592]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2020-03-15 18:52:31 +0000, Ron Aaron wrote:

> Compiling on macOS using the 'androidbuildlibs.sh' and NDK r21, the compiler gives:
> 
> armeabi-v7a] Compile thumb  : SDL2 <= SDL_hints.c
> [armeabi-v7a] Compile thumb  : SDL2 <= SDL.c
> In file included from ./src/SDL.c:37:
> In file included from ./include/SDL.h:38:
> In file included from ./include/SDL_cpuinfo.h:86:
> In file included from /Users/ron/src/android-ndk-r21/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/immintrin.h:14:
> /Users/ron/src/android-ndk-r21/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/mmintrin.h:50:12: error: invalid conversion between vector type
>       '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
>     return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
>            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/ron/src/android-ndk-r21/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/mmintrin.h:129:12: error: invalid conversion between vector
>       type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
>     return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
> 
> etc...

On 2020-03-15 18:56:12 +0000, Ron Aaron wrote:

> It does compile with NDK r21 on Linux.

On 2020-03-16 19:33:20 +0000, Sam Lantinga wrote:

> I'm not seeing that either...?
> stream-mac:SDL valve$ export PATH=$HOME/android/android-ndk-r21:$PATH
> stream-mac:SDL valve$ ./build-scripts/androidbuildlibs.sh 
> [armeabi-v7a] Compile thumb  : SDL2 <= SDL_hints.c
> [armeabi-v7a] Compile thumb  : SDL2 <= SDL.c
> [armeabi-v7a] Compile thumb  : SDL2 <= SDL_dataqueue.c
> [armeabi-v7a] Compile thumb  : SDL2 <= SDL_assert.c
> [armeabi-v7a] Compile thumb  : SDL2 <= SDL_log.c

On 2020-03-17 04:47:33 +0000, Ron Aaron wrote:

> Strange. Perhaps it's to do with the XCode or OS version? Unlikely I would think, since the NDK is its own thing.
> 
> For reference, I'm on macOS 10.14.6 (Mojave), and XCode 11.3.1

On 2020-03-20 20:38:33 +0000, Ryan C. Gordon wrote:

> 
> Any chance you've run the configure or CMake scripts in this source tree on macOS, so it overwrote SDL_config.h with something macOS-specific?
> 
> (or it picked up SDL_config.h from an installed copy in /usr/local or something?)
> 
> This is trying to include the header for MMX support (mmintrin.h) which shouldn't happen on ARM Android, and SDL_cpuinfo.h decides to include that header based on something we'll set in SDL_config.h.
> 
> --ryan.

**Comment by icculus** [comment]
This was a misconfiguration on the end-user's part.
