### ISSUE TITLE
Opt Controller into Steam Input OSX causes dropped input issue, but is fine on Windows

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3599]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [The options mentioned in the ticket (screenshot.png, image/png, 2020-03-20 06:49:17 +0000, 225113 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4270)

**Reported in version:** don't know
**Reported for operating system, platform:** macOS 10.15, x86_64

# Comments on the original bug report:

On 2020-03-20 06:49:17 +0000, Jimmy Spencer wrote:

> Created attachment 4270
> The options mentioned in the ticket
> 
> When I opt controllers in using Steam Input via Steamworks, the OSX build of our game starts dropping inputs, while the Windows build runs just fine. Seems to be some internal fighting between Steam and SDL.
> 
> Picture attached of the option I'm talking about.

On 2020-03-20 06:50:26 +0000, Jimmy Spencer wrote:

> Both versions use the same version of gamecontrollerdb. Turning off Steam Input allows the OSX build to run as expected.

On 2020-03-20 19:11:30 +0000, Sam Lantinga wrote:

> Austin, can you look at this or pass it on to Mike?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
