### ISSUE TITLE
RPI compile with "enable-x11-shared=yes" fails miserably at runtime

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3614]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2020-03-26 14:34:09 +0000, Ron Aaron wrote:

> Configured with --enable-x11-shared-yes and --enable-video-rpi=no, among other things.
> 
> Compiled *on* the RPI to ensure I had whatever runtime libs it expects (normally I cross-compile).
> 
> At runtime, SDL_Init() crashes because it's failing to look up symbols. Actually, dlerror() is crashing because I didn't set locales properly, but that is only why it crashes as opposed to complaining.
> 
> The first symbol it crashes on is _XMissingExtension, which it's looking for in the libX11.so.  But it's in libXext.so.  
> 
> There are a number of similar issues, making dynamic X11 on RPI untenable.

**Comment by icculus** [comment]
I am pretty sure this works here, but we'll double-check before 2.0.16.

**Comment by icculus** [comment]
So yes, it _does_ look in the wrong libraries sometimes, as it looks through the entire list of opened X11 libraries for a symbol until it finds it. But as far as I'm concerned, this is correctly handled on our end, and his unrelated crash in dlerror() is the actual issue, as SDL would have eventually found the symbol and carried on correctly.
