### ISSUE TITLE
Documentation missing for SDL_WINDOW_VULKAN.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3631]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2020-04-10 04:02:49 +0000, Jonathan Levi wrote:

> https://wiki.libsdl.org/SDL_WindowFlags does not list SDL_WINDOW_VULKAN.
> 
> Maybe this should be in a separate issue but
> https://wiki.libsdl.org/CategoryVulkan does not list the need to create window with SDL_WINDOW_VULKAN flag.
> 
> (I figured out how to do it, but it took me longer than I would have liked.)

**Comment by icculus** [comment]
https://wiki.libsdl.org/SDL_WindowFlags was already updated, and I added a note about creating the window in https://github.com/libsdl-org/sdlwiki/commit/cfdf0d5445e50def3c1d31a0ac2500d3abea8a54
