### ISSUE TITLE
CMake builds on Windows broken by sensor support

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3636]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [sensor support in SDL_config.h.cmake + hack in SDL_windowssensor.c (sensor.diff, text/plain, 2020-04-12 19:04:50 +0000, 1732 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4303)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-04-12 19:04:50 +0000, DominikD wrote:

> Created attachment 4303
> sensor support in SDL_config.h.cmake + hack in SDL_windowssensor.c
> 
> CMakes on HG tip are currently broken (at least on Windows). There are three problems I've noticed:
> 
> 1. Sensor support missing in `SDL_config.h.cmake`.
> 2. `SENSOR_DATA_TYPE_ANGULAR_VELOCITY_*_DEGREES_PER_SECOND` symbols duplication.
> 3. If SDL_SENSOR is disabled, dynapi build fails on sensor-related APIs.
> 
> The first one is easily fixable in the patch attached.
> The second one would require `DEFINE_PROPERTYKEY` lines to be removed (I get them from `#include <Sensors.h>`) but I assume these were added for a reason. Ugly hack in the patch attached.
> The last one may be something wrong I'm doing.
> 
> Given that sensor support seems to be very much WIP it's likely that tip will change before maintainers attend to this report. But I hope it's at least a little bit useful (don't know if any of you guys uses Windows as the default platform).

On 2020-04-13 15:09:22 +0000, Sam Lantinga wrote:

> Thanks, your patch to SDL_config.h.cmake is in:
> https://hg.libsdl.org/SDL/rev/0aea93477d09
> 
> I'll look more closely at why my Sensors.h doesn't define the angular velocity properties.

**Comment by madebr** [comment]
> > 1. Sensor support missing in `SDL_config.h.cmake`.

already fixed

> > 2. `SENSOR_DATA_TYPE_ANGULAR_VELOCITY_*_DEGREES_PER_SECOND` symbols duplication.

https://github.com/libsdl-org/SDL/blob/32df5aeb3d0dca1a28533d413bdd54ea072fe0d3/src/sensor/windows/SDL_windowssensor.c#L45-L47

Current master has added a `SDL_` prefix, thus avoiding a symbol clash.

> > 3. If SDL_SENSOR is disabled, dynapi build fails on sensor-related APIs.

I am able to build using MinGW with `-DSDL_SENSOR=OFF`,
so I think this problem has been fixed in the mean time.
