### ISSUE TITLE
WIN_Vulkan_CreateSurface hardcodes NULL for VkAllocationCallbacks parameter

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3638]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-04-13 16:14:17 +0000, bjc wrote:

> There is no way to provide SDL with a VkAllocationCallbacks struct that it can then pass to vkCreateWin32SurfaceKHR internally. This parameter is just hardcoded to NULL currently, in SDL_windowsvulkan.c. This is a problem when an application uses Vulkan custom memory allocation routines, because it violates Vulkan specification which states:
> 
> If no VkAllocationCallbacks were provided when surface was created, pAllocator must be NULL (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroySurfaceKHR-surface-01268)
> 
> Specifically, an application using custom memory allocation routines would provide the callbacks to vkDestroySurfaceKHR, but because they weren't *also* provided to the SDL call to vkCreateWin32SurfaceKHR, a spec violation occurs, which results in undefined behavior (and is also flagged by the Vulkan validation layers).

**Comment by slouken** [comment]
@icculus, is this already fixed?

**Comment by icculus** [comment]
This is **not** fixed; we would need to change the API to accept allocator callbacks (which I'm not sure why we didn't offer in the first place).

I can easily change this for SDL3; for SDL2, we'd have to add an SDL_Vulkan_CreateSurfaceWithAllocator function that takes an extra parameter.

**Comment by slouken** [comment]
Let's change this for SDL3 and leave it alone for SDL2.

**Comment by icculus** [comment]
Fixed in 2f92807087f49c830481cc5689ae53cb7cdb42e2, and sdl2-compat is updated to respect the API change in https://github.com/libsdl-org/sdl2-compat/commit/f110cbb375d2793b1f7117b360c098ff23622dde

**Comment by madebr** [comment]
Untested, but `build-tools/SDL_migration.cocci` should get the following rule:
```
@@
expression w, i, s;
@@
- SDL_Vulkan_CreateSurface(w, i, s)
+ SDL_Vulkan_CreateSurface(w, i, NULL, s)
```

**Comment by icculus** [comment]
> `build-tools/SDL_migration.cocci` should get the following rule:

Looks correct to me; I put it in with 869257a5c1c68882eb875d92f2223191aee8f8a9
