### ISSUE TITLE
SDL_CondWaitTimeout causes deadlock when used in multi-threads.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3639]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [this bug's comment (SDL_CondWaitTimeout causes deadlock.txt, text/plain, 2020-04-14 02:34:51 +0000, 2245 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4305)
* [Modified the text format of first attachment file. (SDL_CondWaitTimeout causes deadlock.txt, text/plain, 2020-04-14 03:01:25 +0000, 1963 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4306)

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-04-14 02:34:51 +0000, elite_jwp wrote:

> Created attachment 4305
> this bug's comment
> 
> (This description also can be found in attachment file, which should be more easy to read due to the text format.)
>

**Comment by slouken** [comment]
@icculus, this looks legit. Any ideas how to fix?
