### ISSUE TITLE
PulseAudio backend should default to native source/sink parameters

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3644]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-04-14 22:40:52 +0000, Daniel Glöckner wrote:

> When an application passes 0 in one of the SDL_AudioSpec fields, prepare_audiospec chooses default values that the PulseAudio backend passes to the server. The server will happily obey and convert the audio data when the hardware can't deal with these settings. Usually our game is played by people with sound hardware that captures its audio input with a stereo ADC. But some people want to use more professional equipment that captures f.ex. six microphones in one audio stream. If our application asks for two channels, the additional channels of the professional equipment are inaccessible. If we ask for 6 channels, the data from the consumer hardware gets remixed into a 5.1 stream.
> 
> What I as a user of the API would expect is that a 0 in one of the SDL_AudioSpec fields leads to a settings that avoids audio conversion in software. The same can be said about the allowed_changes parameter of SDL_OpenAudioDevice. To me these flags are an invitation to use the settings with the least overhead.
> 
> In the PulseAudio backend the format with the least overhead is probably the one mentioned in the sample_spec field of the pa_sink_info/pa_source_info structures. The backend already asks for these structures to determine the name of the device.

**Comment by flibitijibibo** [comment]
With SDL_GetAudioDeviceSpec and SDL_GetDefaultAudioInfo this is now possible... but I bet applications rely on the hardcoded fallbacks, so I wonder if this is 3.0 material?

**Comment by icculus** [comment]
This is changing in SDL3

**Comment by icculus** [comment]
> Going to reopen this and put in the 3.2.0 milestone, just to remind myself to double-check this is okay in SDL3. 

Okay, in SDL3, this defaults the hardware to whatever the platform told us is the desired default (and we use `DEFAULT_AUDIO_PLAYBACK_CHANNELS` and friends if the platform _can't_ tell us a default). This happens in SDL_AddAudioDevice() internally.

PulseAudio does this in AddPulseAudioDevice(), and has access to that info during device add, so we're solid here.


The places that _can't_ do this:

- sndio
- alsa (we could if we opened the device to query it, but that is unnecessary risk).
- directsound if you're on Windows XP
- disk (obviously)
- dummy (obviously)
-
