### ISSUE TITLE
macOS has over-saturated colors when system colorspace isn't sRGB

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3645]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Mac OS X (All), All

# Comments on the original bug report:

On 2020-04-15 20:35:04 +0000,  wrote:

> On macOS, the display rendered is over-saturated.
> 
> You can see this by e.g. opening a PNG in Preview.app, and then displaying the same image in SDL (using a loader like libpng, libspng, lodepng, stb_image, etc that bypasses the system color management).
> 
> There was a previous commit to fix this https://hg.libsdl.org/SDL/rev/e5b39f4935c8 that set the window colorspace to sRGB, but apparently caused performance issues https://hg.libsdl.org/SDL/rev/3a847ed9f8b1https://hg.libsdl.org/SDL/rev/3a847ed9f8b1 .  I couldn't find any other references to this issue, though note that OpenTTD was able to _improve_ performance by setting the colorspace https://github.com/OpenTTD/OpenTTD/issues/7644
> 
> If setting the colorspace causes performance issues, then we should figure out another way to do it such that colors are rendered correctly.

**Comment by ellipticaldoor** [comment]
Could be possible to fix this? Now on mac using OpenGL textures don't match the color profile of the monitor

**Comment by slime73** [comment]
If we can't make this work purely inside SDL without performance regressions then IMO something should be exposed via an API to either let users choose what to do or to give them the tools to do color conversions on their own. I can't say I've looked at this much lately so I don't know what's the best solution though.

**Comment by ellipticaldoor** [comment]
So I think the only thing I need is to convert an image texture to the color profile of the system, Doing that just once will be performant. But I have no clue where to start...

**Comment by ellipticaldoor** [comment]
that will be nice, while that get updated, there is any way of telling macos to color correct the window?

**Comment by slime73** [comment]
I think this is fixed with https://github.com/libsdl-org/SDL/commit/d2300516c3998277c993fd4ac336fbb4ba71641a

**Comment by icculus** [comment]
Sasha is correct; I believe this was the fix, and I can see it on my own monitor.
