### ISSUE TITLE
Emscripten: connecting and disconnecting real-joysticks can close virtual joysticks

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3647]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Fix #1: use SDL_GetNextJoystickInstanceID() for alloc'ing joystick-ids in Emscripten joystick backend (SDL_Bug_5097-Fix_1.patch, text/plain, 2020-04-18 16:13:38 +0000, 2614 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4310)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Other, Other

# Comments on the original bug report:

On 2020-04-18 15:52:40 +0000, David Ludwig wrote:

> SDL2's Emscripten joystick backend appears to be allocating SDL_JoystickIDs using its own, private, integer counter, rather than through SDL_GetNextJoystickInstanceID().  This can have harmful effects if and when a virtual joystick is attached (using functionality new to SDL 2.0.13+).  For example, when connecting and disconnecting real game-controller hardware, Emscripten's joystick backend can assign an SDL_Joystick a SDL_JoystickID that is being used by an active virtual-joystick (which uses a different, joystick-subsystem backend).

On 2020-04-18 16:13:38 +0000, David Ludwig wrote:

> Created attachment 4310
> Fix # 1: use SDL_GetNextJoystickInstanceID() for alloc'ing joystick-ids in Emscripten joystick backend
> 
> Here is an attempt at a fix.  It seems to work fine for me, however it could, perhaps, use more testing, and maybe review by someone more familiar with SDL2's Emscripten joystick backend.

**Comment by Daft-Freak** [comment]
I think the only reason that code wasn't using `SDL_GetNextJoystickInstanceID` is that it didn't exist at the time... and the backend wasn't updated when it was added.
