### ISSUE TITLE
Timer resolution should not be set to 1ms on default.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3654]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-04-22 22:16:03 +0000, Joel Linn wrote:

> SDL_Init() initializes Ticks which sets the windows timer resolution to 1ms at default. timeBeginPeriod() is used for this. We call NtSetTimerResolution() before to set the resolution to a lower value and SDL overwrites this at default, which costs us decreased frame-rates. This behaviour can be turned off setting a Hint before calling SDL_Init() of course.
> 
> However, in SDL_hints.h it is elaborated that setting the timer resolution is a bad idea in many cases as well as:
> > This hint is only used on Windows 7 and earlier.
> From that I deduce timeBeginPreiod() should never be called on Windows 8 upwards, hence a bug report.

**Comment by icculus** [comment]
> timeBeginPreiod() should never be called on Windows 8 upwards

This isn't true, and the comment is misleading, based on something Bruce Dawson said in a blog post about Windows 8 moving to a tickless kernel. Having a tickless kernel mitigates some of the power and performance concerns of using timeBeginPeriod, but it doesn't render the API obsolete.

There is probably room for improvement: we don't need to force the higher resolution to use QueryPerformanceCounter, which hopefully we _always_ use in reasonable setups, and we can force the timer resolution higher just during SDL_Delay() calls, but I haven't tested this to see if it causes problems (and anyhow, the problem reported is in us changing the resolution at all).

I don't know if this comment in SDL/src/timer/windows/SDL_systimer.c is correct:

```c
    /* if we didn't set a precision, set it high. This affects lots of things
       on Windows besides the SDL timers, like audio callbacks, etc. */
```

If that's true, we're probably stuck with things as they are. If not, we could definitely experiment with this after 2.0.16.

As to the _specific_ problem in this bug report: the reporter should use the hint, even on Windows 8+, and/or don't call NtSetTimerResolution before SDL_Init(), and/or don't call an undocumented function like NtSetTimerResolution _at all_.

For now, if we change this line in SDL_hints.h about `SDL_HINT_TIMER_RESOLUTION` ...

    This hint is only used on Windows 7 and earlier.

...to...

    This hint is only used on Windows.

...then we can close this issue.

**Comment by Lokathor** [comment]
This appears to have some updated info for Windows 10: https://randomascii.wordpress.com/2020/10/04/windows-timer-resolution-the-great-rule-change/

**Comment by icculus** [comment]
My guess is that Windows still has to swallow the cost of a more-frequent timer interrupt with the Win10 change, but saves power by not scheduling sleeping processes that haven't requested a higher timer resolution, which usually just find out they have nothing to do yet and go right back to sleep...this would be a 15x energy savings.
