### ISSUE TITLE
Return value of SDL_GameControllerAddMappingsFromFile doesn't count mappings for certain GUIDs

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3660]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-04-24 22:04:41 +0000, PkR wrote:

> I'm calling SDL_GameControllerAddMappingsFromFile to load controller mappings from a text file. I found out that mappings for controllers with certain GUIDs are ignored despite existing in the .txt file. It seems to have something to do with a specific part of the GUID that is in the range between the 17th and 20th bytes. If this part doesn't contain letters, the mapping fails to load. One of my controllers has a GUID like this (as reported by SDL), so it always fails to load mappings from a file: 03000000790000000600000000000000. However, if I rewrite the GUID to make the byte range 17-20 contain letters, it loads (as indicated by the function's return value). For example this GUID doesn't fail: 030000007900000006AAAA0000000000.
> 
> Here's an example mapping string from the file that fails to load:
> 03000000790000000600000000000000,Default Controller,a:b0,b:b1,x:b2,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,-rightx:-a2,+rightx:+a3,righty:a4,lefttrigger:b6,righttrigger:b7,platform:Windows,
> 
> If you try to load gamecontrollerdb.txt from here https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt a good chunk of controller mappings fails to load, with only 78 succeeding.

On 2020-04-24 22:16:36 +0000, PkR wrote:

> I tested the project with different versions of SDL and it seems to work with versions 2.0.8 and below. 2.0.9 and above are affected by this issue.

On 2020-04-24 23:18:05 +0000, PkR wrote:

> To add to the previous comment, it looks like the issue only affects the function's return value, the mappings themselves are actually loaded. It only doesn't count the mapping strings with such GUIDs. If there are such strings in the text file, the return value is lower than the number of loaded controller mappings. It returns 0 if all GUIDs in the text file are "wrong".
> SDL 2.0.8 and below aren't affected by this.

**Comment by slouken** [comment]
SDL will overwrite previous mappings if the GUID VID and PID match, and these entries are not counted in the return value from the function.
