### ISSUE TITLE
CMake won't compile in VS2019 (patch included)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3662]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch (13782.patch, text/plain, 2020-04-27 02:09:04 +0000, 839 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4323)
* [Patch v2 (13782_bis.patch, text/plain, 2020-04-27 03:00:45 +0000, 752 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4324)

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-04-27 02:09:04 +0000,  wrote:

> Created attachment 4323
> Patch
> 
> Trying to build SDL with VS2019 using CMake will encounter a linking error
> 
> More specifically:
> 
>     1>SDL_string.obj : error LNK2019: unresolved external symbol memset referenced in function SDL_vsnprintf_REAL
> 
> 
> It seems memcpy call needs vcruntime library.
> 
> The attached patch fixes the error. This patch was tested against VS2019.
> 
> More details here:
> 
> https://stackoverflow.com/questions/58288692/cant-build-solution-in-release-mode-for-sdl-library-on-vs-2019

On 2020-04-27 02:25:25 +0000,  wrote:

> DO NOT USE THIS PATCH
> 
> After looking into:
> 
> https://developercommunity.visualstudio.com/content/problem/711317/unexpected-implicit-memset-in-release-optimized-bu.html
> 
> It would seem SDL does as much as possible to avoid the CRT; and it already uses  #pragma function() in src/stdlib/SDL_stdlib.c but it does not do that with memset.

On 2020-04-27 03:00:45 +0000,  wrote:

> Created attachment 4324
> Patch v2
> 
> New fix to the problem, without linking to libc

On 2020-05-01 21:38:30 +0000, Alex Szpakowski wrote:

> I worked around this problem in a different manner: https://github.com/love2d/megasource/commit/7ed6273a1a8e913157236cd18a0de46fd029a447
> 
> I'm not sure which way is better.

On 2020-05-02 21:43:55 +0000, Sam Lantinga wrote:

> Fixed, thanks!
> https://hg.libsdl.org/SDL/rev/d5fe4ad4d29c

On 2020-05-06 18:04:20 +0000, Martin Gerhardy wrote:

> Now the reverse is happening. Without that revision everything links fine
> ----------------------------------------------------------------
> 2020-05-06T15:14:11.7285275Z libvcruntimed.lib(memcpy.obj) : error LNK2005: memcpy already defined in sdl2.lib(SDL_stdlib.obj) [D:\a\engine\engine\build\src\modules\voxelutil\tests-voxelutil.vcxproj]
> 
> 
> Github Actions output for the version:
> ----------------------------------------------------------------
> 2020-05-06T14:53:25.8733456Z Microsoft Windows Server 2019
> 2020-05-06T14:53:25.8733674Z 10.0.17763
> 2020-05-06T14:53:25.8734418Z Environment: windows-2019
> 2020-05-06T14:53:25.8734599Z Version: 20200426.1
> 2020-05-06T14:53:25.8734923Z Included Software: https://github.com/actions/virtual-environments/blob/win19/20200426.1/images/win/Windows2019-Readme.md

On 2020-11-08 19:53:15 +0000, Ozkan Sezer wrote:

> *** Bug 5334 has been marked as a duplicate of this bug. ***

On 2020-11-09 07:27:15 +0000, Sam Lantinga wrote:

> Okay, we need to not define memset() and memcpy() in SDL. I want to fix this for 2.0.14.

On 2020-12-09 03:08:02 +0000, Sam Lantinga wrote:

> It turns out that we do need to define memset and memcpy in SDL to handle compiler intrinsic optimization.
> 
> Can you check the latest SDL snapshot and make sure it works for your scenarios?
> http://www.libsdl.org/tmp/SDL-2.0.zip
> 
> Thanks!

**Comment by matteckert** [comment]
Same issue as Martin Gerhardy, the patch that was merged before the 2.0.14 release _causes_ a multiply defined linker error for me. Could it be because I'm trying to link SDL statically and the `_MT` guard was removed?

**Comment by madebr** [comment]
I am ale to build it on a local VS2019 + it is built on Github CI with VS2022 so this should have been fixed.
