### ISSUE TITLE
SDL_CreateWindowFrom allow opengl context creation

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3668]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-04-30 20:29:22 +0000,  wrote:

> It currently seems impossible to create an opengl window using SDL_CreateWindowFrom().
> 
> There are proposed patches here (https://bugzilla.libsdl.org/show_bug.cgi?id=4219), but it would be great to have an official implementation. 
> 
> Preferably, something along the lines of 
> 
> SDL_CreateWindowFrom(void* data, flags)
> 
> would seem best fit (for vulkan, etc.), while also aligning with SDL_CreateWindow.
> 
> This would allow ex. creating sdl windows from child windows to hook into editors, etc.

On 2020-04-30 20:34:23 +0000,  wrote:

> Further references for people searching for this functionality:
> 
> https://discourse.libsdl.org/t/how-to-integrate-sdl-as-a-child-window/14962/3
> 
> https://gamedev.stackexchange.com/questions/110205/context-is-null-with-sdl-createwindowfrom-win32

**Comment by slouken** [comment]
This is fixed in https://github.com/libsdl-org/SDL/commit/1c4723ac66363c1b0dd08f2095869b810bfd16ec, where you can set properties indicating that the external window is used for OpenGL
