### ISSUE TITLE
Unexpected resize event sent by SDL_DestroyWindow, patch included

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3669]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows (All), x86_64

# Comments on the original bug report:

On 2020-05-01 07:04:55 +0000, Elmar wrote:

> Dear SDL team,
> 
> when my app left the SDL_WINDOW_FULLSCREEN mode in Windows 10 and switched back to a normal smaller window, it received a resize event to blow the normal window back up to the fullscreen resolution.
> 
> I traced it back and found that..
> 
> 1) My app calls SDL_DestroyWindow when leaving fullscreen.
> 2) SDL_DestroyWindow calls SDL_HideWindow
> 3) SDL_HideWindow calls SDL_UpdateFullscreenMode(window, SDL_FALSE);
> 4) SDL_UpdateFullscreenMode calls SDL_OnWindowResized(window);
> 5) SDL_OnWindowResized sends the unexpected SDL_WINDOWEVENT_SIZE_CHANGED
> 
> I figured it is not really expected to send a SDL_WINDOWEVENT_SIZE_CHANGED event with the old window size when you want to hide a window (but maybe there is a good reason ;-), anyway I patched it away like this
> 
> 
> >replace
> ```
> SDL_OnWindowResized(SDL_Window * window)
> {
>     window->surface_valid = SDL_FALSE;
>     SDL_SendWindowEvent(window, SDL_WINDOWEVENT_SIZE_CHANGED, window->w, window->h);
> }
> ```
> >with
> ```
> SDL_OnWindowResized(SDL_Window * window)
> {
>     window->surface_valid = SDL_FALSE;
>     /* Do not generate a size change event if we are hiding the window, e.g. during SDL_DestroyWindow,
>        otherwise the App will receive a resize event for the next window opened with the old size */
>     if (!window->is_hiding) SDL_SendWindowEvent(window, SDL_WINDOWEVENT_SIZE_CHANGED, window->w, window->h);
> }
> 
> ```
> This may be related to bug 4760:
> https://bugzilla.libsdl.org/show_bug.cgi?id=4760
> 
> It also persists in the latest SDL 2.0.12.
> 
> Best regards,
> Elmar

**Comment by sezero** [comment]
Is this still an issue?

**Comment by slouken** [comment]
I'm not sure about the hiding case, but it definitely shouldn't send a resize event while being destroyed. This is fixed in https://github.com/libsdl-org/SDL/commit/69518b9ecc1b987ce2962216289318fdd44ece46

Thanks!
