### ISSUE TITLE
Window that is minimized and then shown is missing minimized flag but still minimized.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3670]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-05-02 22:18:14 +0000, Erik Soma wrote:

> Steps to reproduce:
>  - create a window with default flags
>  - minimize the window (SDL_WINDOW_MINIMIZED is correctly set)
>  - hide the window (SDL_WINDOW_MINIMIZED is still set)
>  - show the window
>  - check SDL_WINDOW_MINIMIZED, it is not set, but the OS window is still minimized
> 
> SDL_ShowWindow causes SDL_SendWindowEvent(..., SDL_WINDOWEVENT_SHOWN, ...) which removes the SDL_WINDOW_MINIMIZED flag. This behavior was added in changeset 12730. The commit message is "Windows are not in a minimized state when they are shown", but this is not the case at least in Windows (I don't have another platform with GUI to test the behavior there). However, given the order of SDL_FinishWindowCreation it doesn't seem likely this is the case on other platforms either (otherwise passing SDL_WINDOW_MINIMIZED to SDL_CreateWindow would appear to do nothing?). From an API perspective it seems surprising that the intent would be for SDL_ShowWindow to also restore the minimized window (though I suppose not from a natural language perspective, but it would mean there is no way to un-hide a window without also restoring it).
> 
> I was unable to find another bug report that prompted this change. So perhaps I'm missing some context, but reverting 12730 fixed the issue for me.

**Comment by slouken** [comment]
@Kontrabant, is this fixed with your work?

**Comment by Kontrabant** [comment]
Mine or someone else's, but it seems to have been fixed at some point as it behaves correctly now.
