### ISSUE TITLE
Window size is returning a wrong value in max resolution

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3674]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-05-06 01:00:41 +0000, Lísias de Castro wrote:

> When I used my function to get a resolution I saved it into file. Before to get into the event loop the resolution was correct, but when the loop came into SDL_WINDOWEVENT_RESIZED and I updated my screen width and height through event.window.data. The problem is the data2 came with the wrong value.
> 
> here is my event code piece:
> 
> ...
> case SDL_WINDOWEVENT_RESIZED:
>                 {
>                     machine->width = SDL_C(machine->plugin)->event.window.data1;
>                     machine->height = SDL_C(machine->plugin)->event.window.data2;
>                     SDL_IMAGE_SET * image = (SDL_IMAGE_SET*) map->of->image;
>                     if (image && image->memory) {
>                         B32 width, height;
>                         SDL_QueryTexture(image->memory, NULL, NULL, &width, &height);
>                         map->width = (BP32) width;
>                         map->height = (BP32) height;
>                     }
>                 }
>                     break;
> ...

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
