### ISSUE TITLE
Add ability to get the device path of a joystick

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3675]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Proposed patch (0001-Expose-Linux-device-path-for-Joysticks.patch, text/plain, 2020-05-06 08:52:26 +0000, 4902 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4333)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-05-06 08:52:26 +0000, Sjoerd Simons wrote:

> Created attachment 4333
> Proposed patch
> 
> Sometimes it can be useful to understand which device a Joystick actually refers to; E.g. to get information for it that SDL doesn't support (which usb port is it connected to, what's the bt mac as exposed of usb) or functionality not supported by SDL (firmware updates, LED controls etc). 
> 
> The attached patch adds the ability on linux to get the underlying device path, which can then futher be used with other APIs  with the device (e.g. libudev, fwupd etc).
> 
> The patch adds a Linux specific function; Unsure if that's OK for SDL or whether it should be done in a more cross-platform name (Though i have no idea what a good system device indentifier would be on other systems).

On 2021-01-25 11:54:58 +0000, Dimitriy Ryazantcev wrote:

> I proposing to extend this approach with ability to return device interface path on Windows too. 
> I talking about string like `\\?\HID#VID_203A&PID_FFFC&MI_01# 7&2de99099&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}` that could be used for example to acquire audio interface on that PS4/5 controller via CM_* or SetupDi* API.

**Comment by icculus** [comment]
This is a no for SDL2; I'm not _against_ it for SDL3, but I question the value of it.

**Comment by slouken** [comment]
Oh, hah, this already exists.

SDL2: `SDL_JoystickPathForIndex()` and `SDL_JoystickPath()`
SDL3: `SDL_GetJoystickInstancePath()` and `SDL_GetJoystickPath()`
