### ISSUE TITLE
Activity lock guards in Android code seem to cause freezes in some more complex scenarios

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3679]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-05-09 06:04:04 +0000, Ellie wrote:

> The python-for-android project appears to have downgraded from SDL 2.0.10 to 2.0.9 due to added lock guards causing freezes:
> 
> https://github.com/kivy/python-for-android/issues/2169
> 
> The lock guards in particular are the ones in src/core/android/SDL_android.c in functions like onNativeResize.
> 
> There is a write-up why this could possibly happen: https://github.com/kivy/python-for-android/issues/2169#issuecomment-625367151
> 
> ... although rereading and rethinking that, SDL_LockMutex() is recursive, so this could only happen if somehow execution jumps into a different thread into the call chain. So possibly something else is at play to cause a freeze:
> 
> My new guess is, it appears onNativeResize/onNativeOrientationChanged/...s guarded calls of Android_SendResize/Android_SetScreenResolution/... (which can cause cascarded follow-ups like recursive screen resolution changes) can in Android's Java API call another thread recursively that is waited for which re-enters these guarded callbacks in onNativeResize/..., causing a freeze.
> 
> In any case, one thing that I think might solve it is to somehow schedule these calls with some mutex to only protect that scheduling mechanism, and then check & do these scheduled calls back in the regular main thread in something like SDL_PollEvent() and any SDL_Create*() and ideally any other commonly called function as called by the user code (before the function then does afterwards what it usually does, like poll the regular events, create the resource, ...). This would just inherently remove the possibility of multiple threads running into these complex functions and deadlocking.
> 
> I might be wrong with all of this of course, since nobody has so far gotten a backtrace of a freeze to confirm my suspicions. (The pseudo mocked up backtrace in the comment I linked assumes it happens on the same thread, which obviously would be fine since SDL_LockMutex() acts recursively, so that one can't be how it actually goes down.)

On 2020-05-09 15:41:06 +0000, Sylvain wrote:

> With this issue, it's mandatory to try with latest SDL2 dev sources.
> 
> If you see or believe it goes into deadlock,
> You can easily simulate it by adding some SDL_delay() in SDL2 (core/android/SDL_android.c) and in java side (using Thread.sleep()).
> 
> - add traces also to see which function are called.
> - provide a logcat of traces
> - provide a test-case, and which SDL_delay() / functions to reproduce the issue
> 
> most of record is in bug # 4142

On 2020-05-09 15:53:07 +0000, Ellie wrote:

> I personally can't currently provide what you ask for since I haven't seen these freezes first hand, but if I may note, I'm also not sure trying to trace down all the freezes manually and hoping to catch most is the best approach here:
> 
> As suggested above, I would suggest to at least CONSIDER greatly stripping down the code that runs in another thread with these guards and off-loading it into the main thread by hooking into commonly called functions. Maybe I'm misunderstanding the design, but to me it seems like doing such complex activities in these guards is just asking for corner cases that do calls back into the Android JNI APIs and indirectly end up on some parallel thread. That seems like it'll be an endless source of trouble in the future.
> 
> My own projects based on SDL2 sadly aren't currently ready for testing, otherwise I'd do some more digging myself into these hangs just out of curiosity.

On 2020-05-09 16:54:43 +0000, Sylvain wrote:

> So forward to whoever has the issue. Eg. test with latest source, it shouldn't be a big deal since SDL2 API are backward compatible.
> 
> If this still happen, check what the code is doing when it happens. try to reduce to something simpler. look at traces. add trace if it help. add delay to help also if necessary. give me the log when it happens, and the step to reproduce if possible.
> 
> Mutex you saw are there to protect access to some share data, between the java 
> activity thread, and main C thread.
> 
> If you want information on some specific mutex line added, you can look at the specific commit (see mercurial logs, annotate, https://hg.libsdl.org/SDL/ etc.) and see the commit message, usually I explained the testcase to prove how it failed before.

On 2020-05-09 17:28:59 +0000, Ellie wrote:

> FWIW in python-for-android, SDL2 upgrades are usually an ordeal of a couple of months and there is not really a "simple" test case, because it always puts thj entirety of CPython, and usually the kivy graphics framework in between. I can forward your request, but I'm not sure it'll lead to quick or any responses.
> 
> But you seem to kind of avoid my more general remarks about the way these guards are laid out and that I find the current design of that unfortunate, I would be interested in actually hearing your opinion on those.

On 2020-05-09 17:31:38 +0000, Ellie wrote:

> Just to be super clear, I am talking about Android_ActivityMutex as used in onNativeOrientationChanged, onNativeResize, or onNativeSurfaceChanged, with the guard wrapping complex calls that can trigger an entire chain of follow-up things (including JNI calls that do more resizes) like Android_SendResize or Android_SetScreenResolution. That just seems fundamentally like a brittle approach to me.

On 2020-05-09 19:16:09 +0000, Sylvain wrote:

> As long as there are both lock and unlock calls, the function is fine for dealing with shared data I guess.
> 
> There is no case, that I know, where a thread  (sdl or java) would take mutex, and trigger + wait for the other thread to perform an action which would also take the same mutex. That would be a deadlock.
> 
> (there are some function that lock/unlock and retry a couple of time though)
> 
> I understand onNativeOrientationChanged, onNativeResize, or onNativeSurfaceChanged is a quite complex logic, and I agree. but there are mostly setting an internal state, and also checking that the internal state isn't getting updated while updating it. this is quite complex because, based on several condition, you have to deal with pausing/resuming and the gl context. there is also a mode with multi-window allowed.
> 
> The java call cannot be just recorded / scheduled / delayed. for instance, when the surface view is changed, you must create the EGL context immediately, you cannot send an event to defer it. Otherwise, at that time, it could be possible that the surface is in fact destroyed (because there are sometime pause/resume/pause sequence of the activity).
> 
> I you have multiple resize, or whatever call, each is processed somehow atomically and that shouldn't be an issue.
> 
> There are various corner cases already fixed, and there are very subtle because of timing issue. But always reproduceable with SDL_delay().
> You can remove all the Lock calls, and believe that it still work, but in fact, If you look thoroughly and across a large amount of devices, you'll get some black screen at start or at resume, glitch, crashes in the middle of the app or at exit, wrong screen w/h, etc.
> 
> you can look in details of each function if you want:
> onNativeOrientationChanged:
> - make sure Android_Window doesn't change (SDL_window could be destroyed in the meantimes !) 
> - send the event
> 
> onNativeResize
> - make sure Android_Window doesn't change
> - update display->*_modes
> - send the event
> 
> onNativeSurfaceChanged
> - make sure Android_Window doesn't change
> - create SDL_EGL_CreateSurface
> 
> I don't think the code is perfect, and if you still see a deadlock cascade, you can try to prove it with SDL_delay() etc. There is very likely room for improvement.
> 
> And also, if you see some function that can be simplified, this is also welcome.

On 2020-05-11 18:13:41 +0000, Ellie wrote:

> > The java call cannot be just recorded / scheduled / delayed. for instance, when the surface view is changed, you must create the EGL context immediately, you cannot send an event to defer it.
> 
> Ok, that makes a lot of sense, thanks for explaining! I will see if I can poke for python-for-android folks, and hopefully my own SDL2 stuff for Android should also run soon so I can test around. I would really like to catch these freezes in action if I can...

On 2020-10-07 07:10:16 +0000, Sylvain wrote:

> Do you have more information ?

On 2020-10-07 08:17:59 +0000, Ellie wrote:

> I have actually both moved away from Python and Android, I purely use SDL2 on a Linux phone now. I suppose it might make sense to resolve this as abandoned for now...? Unless somebody else who still uses python-for-android steps up with some info, or you'd prefer to keep it open anyway

On 2020-10-07 08:30:08 +0000, Sylvain wrote:

> ok. marked as abandoned, please re-open if needed.

**Comment by misl6** [comment]
Hi @1bsyl !

1/8 Kivy Core Developer here, updating our SDL2 dependencies on `python-for-android` here: https://github.com/kivy/python-for-android/pull/2673

The `mutex.patch` patch just adds some logging for testing purposes + currently avoids the usage of `SDL_LockMutex` and `SDL_UnlockMutex` on `Android_GLES_SwapWindow`.

That is what happens when `SDL_LockMutex ` and `SDL_UnlockMutex` are left uncommented on `Android_GLES_SwapWindow` ( Looks like we are having a deadlock here ):
```
09-25 16:17:56.588 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.588 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.605 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.605 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.622 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.622 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.638 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.638 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.654 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.654 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.672 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.672 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.688 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.688 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.705 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.705 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.721 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.721 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.738 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.738 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.755 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.755 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.771 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.771 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.788 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.788 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.805 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.806 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.816 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.816 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:56.816 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:56.817 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:57.219 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:57.219 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:57.243 12952 13234 V SDL     : Android_GLES_SwapWindow()-Lock
09-25 16:17:57.247 12952 13234 V SDL     : Android_GLES_SwapWindow()-Unlock
09-25 16:17:57.273 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:57.273 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:57.289 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:57.289 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:57.299 12952 13234 V SDL     : Android_GLES_SwapWindow()-Lock
09-25 16:17:57.301 12952 13234 V SDL     : Android_GLES_SwapWindow()-Unlock
09-25 16:17:57.306 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:57.306 12952 12952 V SDL     : onNativeTouch()-Unlock
09-25 16:17:57.321 12952 13234 V SDL     : Android_GLES_SwapWindow()-Lock
09-25 16:17:57.323 12952 13234 V SDL     : Android_GLES_SwapWindow()-Unlock
09-25 16:17:57.323 12952 12952 V SDL     : onNativeTouch()-Lock
09-25 16:17:57.324 12952 13234 V SDL     : Android_GLES_SwapWindow()-Lock
```

Can we re-open the issue?

If you (or the SDL2 team) need some additional tests / a test app / further information, feel free to ask.

**Comment by 1bsyl** [comment]
Hi @misl6 
not sure what you mean :
but:
you "onNativeTouch()-Lock" means, on next instruction we are going to try to call SDL_LockMutex lock the mutex.
you can add "onNativeTouch()-LockED" just after the lock, so that we see if it is actually locked.
(you can also add on, before the unlock)

On you branch, in Android_GLES_SwapWindow(), there is "Android_GLES_SwapWindow()-Lock" but you removed the call to SDL_Lock/UnlockMutex(), didn't you ?

Btw, what do you observe or are you testing ?

**Comment by misl6** [comment]
> you "onNativeTouch()-Lock" means, on next instruction we are going to try to call SDL_LockMutex lock the mutex.
you can add "onNativeTouch()-LockED" just after the lock, so that we see if it is actually locked.
(you can also add another one before the unlock)

Sure!


Current patch:
```patch
diff -Naur SDL.orig/src/core/android/SDL_android.c SDL/src/core/android/SDL_android.c
--- SDL.orig/src/core/android/SDL_android.c	2022-09-26 20:48:31.000000000 +0200
+++ SDL/src/core/android/SDL_android.c	2022-09-26 20:51:30.000000000 +0200
@@ -1112,11 +1112,15 @@
                                     jint touch_device_id_in, jint pointer_finger_id_in,
                                     jint action, jfloat x, jfloat y, jfloat p)
 {
+    __android_log_print(2, "SDL", "onNativeTouch()-Lock");
     SDL_LockMutex(Android_ActivityMutex);
+    __android_log_print(2, "SDL", "onNativeTouch()-LockED");
 
     Android_OnTouch(Android_Window, touch_device_id_in, pointer_finger_id_in, action, x, y, p);
 
+    __android_log_print(2, "SDL", "onNativeTouch()-Unlock");
     SDL_UnlockMutex(Android_ActivityMutex);
+    __android_log_print(2, "SDL", "onNativeTouch()-UnlockED");
 }
 
 /* Mouse */
diff -Naur SDL.orig/src/video/android/SDL_androidgl.c SDL/src/video/android/SDL_androidgl.c
--- SDL.orig/src/video/android/SDL_androidgl.c	2022-09-26 20:48:31.000000000 +0200
+++ SDL/src/video/android/SDL_androidgl.c	2022-09-26 20:52:16.000000000 +0200
@@ -65,7 +65,9 @@
 {
     int retval;
 
+    __android_log_print(2, "SDL", "Android_GLES_SwapWindow()-Lock");
     SDL_LockMutex(Android_ActivityMutex);
+    __android_log_print(2, "SDL", "Android_GLES_SwapWindow()-LockED");
 
     /* The following two calls existed in the original Java code
      * If you happen to have a device that's affected by their removal,
@@ -76,7 +78,9 @@
     _this->egl_data->eglWaitGL();*/
     retval = SDL_EGL_SwapBuffers(_this, ((SDL_WindowData *) window->driverdata)->egl_surface);
 
+    __android_log_print(2, "SDL", "Android_GLES_SwapWindow()-Unlock");
     SDL_UnlockMutex(Android_ActivityMutex);
+    __android_log_print(2, "SDL", "Android_GLES_SwapWindow()-UnlockED");
 
     return retval;
 }
```

Log + video:
```
09-26 21:07:43.517  7805  7805 V SDL     : onNativeTouch()-Unlock
09-26 21:07:43.518  7805  7805 V SDL     : onNativeTouch()-UnlockED
09-26 21:07:43.524  7805  7835 V SDL     : Android_GLES_SwapWindow()-Lock
09-26 21:07:43.525  7805  7835 V SDL     : Android_GLES_SwapWindow()-LockED
09-26 21:07:43.527  7805  7835 V SDL     : Android_GLES_SwapWindow()-Unlock
09-26 21:07:43.527  7805  7835 V SDL     : Android_GLES_SwapWindow()-UnlockED
09-26 21:07:43.535  7805  7805 V SDL     : onNativeTouch()-Lock
09-26 21:07:43.535  7805  7805 V SDL     : onNativeTouch()-LockED
09-26 21:07:43.535  7805  7805 V SDL     : onNativeTouch()-Unlock
09-26 21:07:43.535  7805  7805 V SDL     : onNativeTouch()-UnlockED
09-26 21:07:43.538  7805  7835 V SDL     : Android_GLES_SwapWindow()-Lock
09-26 21:07:43.538  7805  7835 V SDL     : Android_GLES_SwapWindow()-LockED
09-26 21:07:43.541  7805  7835 V SDL     : Android_GLES_SwapWindow()-Unlock
09-26 21:07:43.541  7805  7835 V SDL     : Android_GLES_SwapWindow()-UnlockED
09-26 21:07:43.551  7805  7805 V SDL     : onNativeTouch()-Lock
09-26 21:07:43.551  7805  7805 V SDL     : onNativeTouch()-LockED
09-26 21:07:43.552  7805  7835 V SDL     : Android_GLES_SwapWindow()-Lock
```

https://user-images.githubusercontent.com/8177736/192360806-ce194a09-d323-47b3-9a11-70b20c3268a5.mov

(Everything looks good until `Android_GLES_SwapWindow()` is called)

This is just a quick demo app meant for testing touch events and UI refresh.

> On your branch, in Android_GLES_SwapWindow(), there is "Android_GLES_SwapWindow()-Lock" but you removed the call to SDL_Lock/UnlockMutex(), didn't you ?

Yeah, that has been done to have a testable APK (which is not crashing) from the CI. On my local environment, the patch does not comment out `SDL_LockMutex(Android_ActivityMutex);` or `SDL_UnlockMutex(Android_ActivityMutex);`.

**Comment by 1bsyl** [comment]
Sounds strange,
Could  you add also a "Android_GLES_SwapWindow()-LockED"  to see if it locked.
+ add to both lockED functions the value return by "SDL_ThreadID()" to see if it come from the same thread or not.

.. but that shouldn't be a problem anyway.

BTW, are you polling the SDL_Events ?
do you have a "log cat" trace ?

**Comment by misl6** [comment]
> Could you add also a "Android_GLES_SwapWindow()-LockED" to see if it locked.

Uh, it's already present. (See patch above)

> add to both lockED functions the value return by "SDL_ThreadID()" to see if it come from the same thread or not.

Sure, I can do that, but I guess is the one the logcat is already printing?

> BTW, are you polling the SDL_Events ?

Yes, we're calling `SDL_PollEvent` here: https://github.com/kivy/kivy/blob/d9e0b4c72e4dd56be130ec3b87ad248646561652/kivy/core/window/_window_sdl2.pyx#L615 (`poll()` is called here: https://github.com/kivy/kivy/blob/1d6be8579d8abfd43220c5fd4b030626b23b7d03/kivy/core/window/window_sdl2.py#L561)

> do you have a "log cat" trace ?

The one posted above is actually a logcat from the android device. (is just filtered to only show logs from `SDL`), but if you would like to inspect an unfiltered one, just ask 😄

**Comment by 1bsyl** [comment]
Ok. Sorry. So two different threads. The video thread is waiting for the mutex.

Not sure about the python log. But is the event queue depleted each time?

Please show the full log!
Thanks

**Comment by misl6** [comment]
> Please show the full log!

Sure!, full log here: 
[log-kivy-x-sdl-202209272025.txt](https://github.com/libsdl-org/SDL/files/9658704/log-kivy-x-sdl-202209272025.txt)

(The errors you're seeing from the python3 side are completely unrelated)

> But is the event queue depleted each time?

We continuously poll for events, and we empty the event queue before starting our idle.

**Comment by 1bsyl** [comment]
this doesn't tell much...

just to make sure: you usually must poll all the events between 2 frames. not 1 events, between two frames).

what is strange is that the "touch" isn't getting to the unlock. I would look there. adding traces, to see where it gets stucked.
( Android_OnTouch, 
SDL_androidtouch.c:  SDL_SendTouch, SDL_SentTouchMotion, and so on).

maybe, just print directly inside the:
 SDL_PushEvent(): at the beginning and before each return.

**Comment by misl6** [comment]
> just to make sure: you usually must poll all the events between 2 frames. not 1 events, between two frames).

Yes, all the events are polled between 2 frames

> what is strange is that the "touch" isn't getting to the unlock. I would look there. adding traces, to see where it gets stucked.
( Android_OnTouch,
SDL_androidtouch.c: SDL_SendTouch, SDL_SentTouchMotion, and so on).
maybe, just print directly inside the:
SDL_PushEvent(): at the beginning and before each return.

👍 Will report back as soon I have some news.

**Comment by misl6** [comment]
Ouch, looks like I found the real root cause, and it's not SDL fault.

**Preface:**

We use `SDL_SetEventFilter` so we can catch some events before they are added to the queue. (And that may need some rework)
The callback passed to `SDL_SetEventFilter` requires the GIL.

**Analysis:**

The `onNativeTouch` callback is called, but `Android_ActivityMutex` is already locked by `Android_GLES_SwapWindow` (from a different thread), so it waits until `Android_ActivityMutex` gets unlocked.
```
10-01 13:51:11.327  5356  5356 V SDL     : onNativeTouch()-Lock
10-01 13:51:11.328  5356  5386 V SDL     : Android_GLES_SwapWindow()-Unlock
10-01 13:51:11.328  5356  5386 V SDL     : Android_GLES_SwapWindow()-UnlockED
```
The `Android_GLES_SwapWindow` finishes and unlocks `Android_ActivityMutex` so `onNativeTouch` can now lock `Android_ActivityMutex`. The touch event then gets pushed via `SDL_PushEvent`, where 
```
10-01 13:51:11.328  5356  5356 V SDL     : onNativeTouch()-LockED
10-01 13:51:11.328  5356  5356 V SDL     : in SDL_PushEvent -> Type: 1024
10-01 13:51:11.328  5356  5356 V SDL     : in SDL_LockMutex(SDL_event_watchers_lock) -> Type: 1024
10-01 13:51:11.328  5356  5356 V SDL     : in SDL_LockMutex(SDL_event_watchers_lock) [LOCKED] -> Type: 1024
```

The `SDL_EventOK.callback` (which as said before requires the GIL on the Python side), gets called but looks stuck.
```c
if (!SDL_event_watchers_lock || SDL_LockMutex(SDL_event_watchers_lock) == 0) {
        if (SDL_EventOK.callback && !SDL_EventOK.callback(SDL_EventOK.userdata, event)) {  \\ <--- We are now here
            if (SDL_event_watchers_lock) {
                SDL_UnlockMutex(SDL_event_watchers_lock);
            }
            return 0;
        }
```
Why? Well, meanwhile on thread `5386` our `flip` method, which is calling `SDL_GL_SwapWindow` have the GIL locked, and can't release it as `Android_GLES_SwapWindow` is stuck on `SDL_LockMutex(Android_ActivityMutex);`, waiting for `onNativeTouch` to unlock the `Android_ActivityMutex`.
```
10-01 13:51:11.332  5356  5386 V SDL     : Android_GLES_SwapWindow()-Lock
```

Ouch. deadlocked.

**Comment by 1bsyl** [comment]
ok, I see
maybe you can try to link and use these functions (maybe you need to add and set them "extern" in include/SDL_system.h":
```
 void Android_ActivityMutex_Lock(void);
 void Android_ActivityMutex_Unlock(void);
```

in your `flip` method, 

```
Android_ActivityMutex_Lock()
get the GIL locked()
... code that does SDL_GL_SwapWindow()
release the GIL locked()
Android_ActivityMutex_Unlock()

```

**Comment by misl6** [comment]
> ok, I see maybe you can try to link and use these functions (maybe you need to add and set them "extern" in include/SDL_system.h":
> 
> ```
>  void Android_ActivityMutex_Lock(void);
>  void Android_ActivityMutex_Unlock(void);
> ```
> 
> in your `flip` method,
> 
> ```
> Android_ActivityMutex_Lock()
> get the GIL locked()
> ... code that does SDL_GL_SwapWindow()
> release the GIL locked()
> Android_ActivityMutex_Unlock()
> ```

Yep, that's an option! (But it will add some platform-specific complexity that may be avoided)
ATM, from some tests ( we had a performance drop previously ), looks like we can safely release the GIL.

Thank you for your support @1bsyl ! (and sorry for the noise generated by this issue) 😄

**Comment by 1bsyl** [comment]
adding some platform-specific complexity may make sense:  Android  ( other like IOS also ?) has it specificity that
the activity has it's own thread and is able to push SDL_event. hence your issue.

thanks for the feedback anyway
