### ISSUE TITLE
Synchronous dispatch causes deadlock

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3680]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch (asyncdispatch.patch, text/plain, 2020-05-10 16:04:05 +0000, 745 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4336)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** macOS 10.15, x86_64

# Comments on the original bug report:

On 2020-05-10 16:04:05 +0000, Emir Marincic wrote:

> Created attachment 4336
> Patch
> 
> http://hg.libsdl.org/SDL/rev/19c4516de68d
> 
> This revision changes the `performSelectorOnMain` with a `dispatch_sync` which ignores the `waitUntilDone:NO`.
> 
> This causes a deadlock if the main thread is waiting on the auxilliary thread that caused this dispatch.
> 
> I've been running a copy with a `dispatch_async` instead and it seems stable, one thing I'm not sure about is the `setView` dispatch. Preliminary investigation would suggest that'd also be fine as an async dispatch but as I don't really know which bug that fixes I haven't tested it, thus I haven't included it in this patch.

On 2020-05-13 00:49:29 +0000, Sam Lantinga wrote:

> Alex, can you review this?
> 
> Thanks!

On 2020-10-18 16:56:19 +0000, Emir Marincic wrote:

> Ping? This is a bug that's rather annoying to workaround as you need to compile with an older version of the SDK and that brings problems with it. If you don't think this is the correct way to fix this maybe we can discuss and figure out a better way?
> 
> https://github.com/teeworlds/teeworlds/issues/2624
> https://github.com/ddnet/ddnet/issues/2173

**Comment by sezero** [comment]
This deserves fixing in 2.0.16
