### ISSUE TITLE
Feature request: SDL_isalpha

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3681]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2020-05-12 17:10:18 +0000, Anthony @ POW Games wrote:

> Please :-)
> 
> We already have SDL_isdigit, so makes sense to have alpha as well.
> 
> Can we also add in SDL_isalnum ?
> 
> No hurry. Thanks!

**Comment by sezero** [comment]
Both of SDL_isalnum and SDL_isalpha have been added recently.

Closing.
