### ISSUE TITLE
Fullscreen window not working

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3684]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-05-13 13:44:17 +0000, ImAnonym wrote:

> I have recently updated SDL to the version 2.0.12, but then fullscreen windows aren't working anymore.
> 
> This simple example fails:
> 
> ```c
> #include <SDL2/SDL.h>
> 
> int main(int main, char* argv[])
> {
>     int quit = 0;
>     SDL_Event event;
>     SDL_Window* window;
>     SDL_Init(SDL_INIT_EVERYTHING);
> 
>     window = SDL_CreateWindow("fullscreen",0,0,640,480,SDL_WINDOW_SHOWN | SDL_WINDOW_FULLSCREEN);
>     while(!quit)
>     {
>         while(SDL_PollEvent(&event))
>         {
>             if(event.type == SDL_QUIT){
>                 quit = 1;
>             }
>         }
> 
>         SDL_UpdateWindowSurface(window);
>     }
>     return 0;
> }
> ```
>
> To be sure that it's a version problem i've tested the same code with an older version and it worked, all tests were done in Windows.
> 
> Can someone tell me if i'm doing something wrong? Or is it really a bug?

On 2020-05-13 15:44:18 +0000, Sam Lantinga wrote:

> I'll take a look, thanks!

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
