### ISSUE TITLE
Identical joysticks are not handled properly

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3686]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch (sdl_duplicate.patch, text/plain, 2020-05-15 00:25:33 +0000, 2203 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4340)

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-05-15 00:25:33 +0000, Jasem Mutlaq wrote:

> Created attachment 4340
> Patch
> 
> This issue came up as I was trying to play X4 Foundations on Linux. I have Dual ThrustMaster 16000M Joysticks. Only one of them appear in X4 Foundations. This patch renames any subsequent discovered joystick with an index. i.e. If the name is "Joystick", then the second discovered joystick name is "Joystick 2", then "Joystick 3" and so forth.
> 
> Furthermore, it changes the guid to make them all unique. Both these changes were necessary to make the 2nd joystick appear in X4. They now both operate perfectly within the game.

**Comment by sezero** [comment]
If this is still an issue, worth fixing in 2.0.16

**Comment by slouken** [comment]
The guid is supposed to be the same for all joysticks of a certain type. If X4 relies on them being different, that's a bug in X4.

**Comment by slouken** [comment]
I'd like to find a way to generalize the name de-duplication at a higher level so it works for all drivers.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by slouken** [comment]
It looks like this is a bug in X4, it should not be looking at the GUID as a unique joystick identifier, instead it's an identifier for the type of joystick.
