### ISSUE TITLE
SDL_CreateWindow() width defaults to 120 when creating smaller windows on Windows platform.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3691]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-05-17 16:11:46 +0000, Dan Lawrence wrote:

> Reported on the pygame issue tracker originally where husano896 kindly provided a C code reproduction:
> 
>     window = SDL_CreateWindow("Test", 0, 0, 20, 20, 0);
>     int check_w, check_h;
>     SDL_GetWindowSize(window, &check_w, &check_h);
> 
>     //Shows 120,20
>     std::cout << check_w << "," << check_h;
> 
> Apparently windows can be made smaller than this since a second call to set_mode in pygame will correctly set the size of the window.
> 
> See the original issue here:
> 
> https://github.com/pygame/pygame/issues/993
> 
> Cheers,
> 
> Dan

**Comment by ankith26** [comment]
Can't reproduce this on windows 11, SDL 2.24.0

**Comment by slouken** [comment]
I think this has since been fixed, thanks!
