### ISSUE TITLE
SDL_DROPFILE events are delivered before SDL_MOUSEMOTION event when SDL is built in Release mode

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3695]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-05-20 14:20:25 +0000, Raffaele Bratta wrote:

> As the summary says, if I drop a file over a SDL window, the order in which drop file and mouse motion events are delivered is not consistent among Debug and Release configuration. When SDL is built in Debug mode, the mouse motion event is delivered before the drop file events, while the contrary happens when SDL is build in Release mode.
> Which is the expected behavior? Can I rely on the fact that the events delivery order remains constant among Debug and Release configuration?
> 
> SDL: 2.0.12 (built in Debug|x64 and Release|x64 using SDL.sln)
> Windows SDK Version: 10.0.18362.0
> Platform Toolset: Visual Studio 2019 (v142)
> 
> OS: Windows 10 Pro 18363.836

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
