### ISSUE TITLE
SDL_MOUSEMOTIONEVENT: non-zero xrel/yrel with immobile mouse

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3701]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-05-23 08:31:07 +0000,  wrote:

> With immobile mouse, the SDL_MOUSEMOTION event's xrel/yrel values are sometimes nonzero, even though the mouse is immobile. This can be verified by checking the event's x/y values, which do not change while the xrel/yrel values are nonzero.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
