### ISSUE TITLE
mingw32 library has bug, can't run vulkan, and freeze window then closed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3703]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-05-23 20:11:47 +0000,  wrote:

> please check it

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
