### ISSUE TITLE
CMake Windows builds dll even though only static set

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3704]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-05-25 16:31:25 +0000,  wrote:

> Hi, I'm noticing on Windows that sdl builds both the dll + static version of sdl even though I set:
> 
> set(SDL_SHARED OFF FORCE)
> set(SDL_STATIC ON FORCE)
> 
> What would be ideal is that in this case, the static library is built with the name 'SDL2.lib' instead of the usual 'SDL2-static.lib'
> 
> This shouldn't be hard a fix, and would make it easier to pick up static builds of sdl

**Comment by okuoku** [comment]
> on Windows that sdl builds both the dll + static version of sdl even though I set

This is because these are `option`s. Since options are `CACHE`d variables, say:

```cmake
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
```

(or, specify `-DSDL_SHARED=OFF` on the command-line) to enforce it.

**Comment by madebr** [comment]
As @okuoku said, `option` creates cache variables thus you need these using "cache operations".
