### ISSUE TITLE
Implement AAudio for modern Android devices

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3710]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Android (All), All

# Comments on the original bug report:

On 2020-05-29 05:14:13 +0000, Ryan C. Gordon wrote:

> Modern Android releases have an audio API called AAudio...
> 
> https://developer.android.com/ndk/guides/audio/aaudio/aaudio
> 
> ...which is meant to be preferred over OpenSL ES. Implement this (leaving our OpenSL ES target as a fallback for older devices, of course).
> 
> --ryan.

**Comment by icculus** [comment]
Assigning myself for now, but this is probably post-2.0.16 work. Feel free to steal if you want to work on this!

**Comment by 1bsyl** [comment]
I've added the AAudio back-end, nothing special except: 
- it dynamically loads the libaaudio.so, which may not be present if the API < 26
- uses GetDeviceBuf / PlayDevice, with SDL_RunAudio thread
- tested with playback and capture


Android: OpenSLES, explicitly initialise the global variable 'bqPlayer' https://github.com/libsdl-org/SDL/commit/4118fe62fe278429a514c43d02286f8e0c7741df
Android: add AAudio back-end, with playback and capture: https://github.com/libsdl-org/SDL/commit/04b2f5f6ecdb18ded9d30b816ca96d444535df31
AAudio: add bootstrap in SDL_audio.c https://github.com/libsdl-org/SDL/commit/f1fab24e35c6974b358d283091cc01bb5af92a82
AAudio: add compilation to Android.mk, but not activated in SDL_config_android.h https://github.com/libsdl-org/SDL/commit/146656cfe6620e7fa81704f5d149ac8172fc4b7f
Android: add openslES and AAudio compilation to CMakeLists https://github.com/libsdl-org/SDL/commit/02b1ebc9e0b2a8a517cfea705e733a29ba43e2e9
AAudio: add aaudio pause/resume function to android events loop https://github.com/libsdl-org/SDL/commit/b4f89c56c67950d261d579dd865046bc3e4c37c3

**Comment by icculus** [comment]
Ooh, nice work!

Let's leave it inactive in the config until 2.0.16 ships, and then make it the default right after, so it has time for testing.

**Comment by 1bsyl** [comment]
ok!

**Comment by icculus** [comment]
Marking with 2.0.18 milestone so we don't forget to flip this in the config.  :)
