### ISSUE TITLE
Initializing joystick subsystem causes USB mouse to no longer work

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3712]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** NetBSD, x86_64

# Comments on the original bug report:

On 2020-05-29 18:15:09 +0000,  wrote:

> If either SDL_Init or SDL_InitSubsystem is called with the argument to initialize the joystick subsystem, the USB mouse will no longer work.

**Comment by icculus** [comment]
I'm sort of powerless to fix this, but I'm assigning myself so I remember to check the original bugzilla database to see who this was and if they have a GitHub account, to pull them back into this discussion.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
