### ISSUE TITLE
[Windows] SDL2 kills the actuators of the Top Gun Afterburner FF joystick

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3718]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-06-01 19:38:34 +0000, ioanch wrote:

> Thrustmaster Top Gun Afterburner Force Feedback (https://support.thrustmaster.com/en/product/topgunafterburnerffb-en/) is a joystick which relies on actuators to stay straight (and also for force feedback).
> 
> I have it running with the native Windows drivers, no Thrustmaster software install involved. None of the drivers from the linked page work for me, presumably because they're too old.
> 
> I tested this on macOS and Windows. Only on Windows I have this problem. It has appeared since SDL v2.0.4 and continues occurring on the current development builds. It wasn't happening on SDL v2.0.3 or SDL v1.2.
> 
> The problem: calling SDL_JoystickOpen for this joystick is enough to *shut down* its actuators (causing the joystick to stay limp when manipulated, instead of returning to the center). The joystick will only recover when re-plugged.

**Comment by sezero** [comment]
Is this still an issue?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
