### ISSUE TITLE
sdlgenblit.pl / SDL_blit_auto.c does not use DUFFS_LOOP

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3728]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2020-06-10 10:48:24 +0000, bugmenot_0 wrote:

> To my surprise, sdlgenblit.pl does not appear to use `DUFFS_LOOP`. Most other blitters do this though.
> 
> Why is this?
> 
> It should be tested if this affects performance.

On 2020-06-10 15:52:45 +0000, Sam Lantinga wrote:

> Patches are welcome!
> 
> Please include optimized benchmark timing results and code size difference for your changes.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
