### ISSUE TITLE
sdlgenblit.pl / SDL_blit_auto.c does expensive tasks in the inner pixel-processing loop

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3730]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2020-06-10 11:04:22 +0000, bugmenot_0 wrote:

> The code generator in sdlgenblit.pl moves a lot of the conditional operations into the inner loop which processes pixels.
> 
> This goes against intuition. While it creates readable code, it is potentially slow code.
> I feel like the main purpose of the generator is to produce fast code, as the resulting code doesn't have to be concise and redundancy is to be expected.
> The only code quality that matters is that of the generator script itself.
> 
> As such, it would probably be better to avoid constructs like this:
> 
> ```c
> for(y = 0; y < height; y++)
>     for(x = 0; x < width; x++)
>         switch (flags) {
>         case SDL_COPY_BLEND: process_pixel_blend(); break
>         case SDL_COPY_ADD: process_pixel_add(); break;
>         case SDL_COPY_MOD: process_pixel_mod(); break;
>         case SDL_COPY_MUL: process_pixel_mul(); break;
>         }
>     }
> }
> ```
> 
> Instead, the code generator should probably generate this:
> 
> ```c
> switch (flags) {
> case SDL_COPY_BLEND:
>     for(y = 0; y < height; y++)
>         for(x = 0; x < width; x++)
>             process_pixel_blend();
>         }
>     }
>     break;
> case SDL_COPY_ADD:
>     for(y = 0; y < height; y++)
>         for(x = 0; x < width; x++)
>             process_pixel_add();
>         }
>     }
>     break;
> case SDL_COPY_MOD:
>     for(y = 0; y < height; y++)
>         for(x = 0; x < width; x++)
>             process_pixel_mod();
>         }
>     }
>     break;
> case SDL_COPY_MUL:
>     for(y = 0; y < height; y++)
>         for(x = 0; x < width; x++)
>             process_pixel_mul();
>         }
>     }
> }
> ```
> 
> This would avoid reliance on the optimizing compiler, and makes the intention more obvious, which might also affect optimizers.

On 2020-06-10 15:49:06 +0000, Sam Lantinga wrote:

> Patches are welcome!
> 
> Please include optimized benchmark timing results for your changes.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
