### ISSUE TITLE
High CPU usage with VSync

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3734]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Other, Other

# Comments on the original bug report:

On 2020-06-14 19:28:17 +0000, Andreas wrote:

> High CPU usage on call to SDL_GL_SwapWindow when SDL_GL_SetSwapInterval(1) is set:
> 
> https://stackoverflow.com/questions/62373762/high-cpu-usage-with-vsync-turned-on-in-opengl-and-sdl2-application

On 2020-06-14 20:29:55 +0000, Cameron Gutman wrote:

> We're going to need more than that to debug:
> 
> - OS
> - GPU hardware
> - GPU driver version
> 
> If I had to guess, I'd say you're on Linux using the NVIDIA proprietary drivers, and that your problem is that you should try setting __GL_YIELD to USLEEP.

On 2020-06-15 05:01:50 +0000, Ashfaaq wrote:

> @Andreas thanks for posting this here, im not sure if this is a bug or not yet. So on to the problem, @Cameron i posted the problem in stackoverflow. The specs of my system are,
> OS: windows 7
> GPU hardware: gtx 750
> GPU driver: 446.14

**Comment by icculus** [comment]
I assume this is not our bug, if it even exists anymore. Closing.
