### ISSUE TITLE
Wayland fullscreen does not forward NULL output

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3736]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-06-14 21:32:41 +0000, Christian Rauch wrote:

> 'SetFullscreen' uses output to determine if fullscreen should be set (output!=NULL) or unset (output==NULL).
> 
> However, the request xdg_toplevel.set_fullscreen also accepts NULL as output. From the protocol documentation:
> > The output passed by the request indicates the client's preference as
> > to which display it should be set fullscreen on. If this value is NULL,
> > it's up to the compositor to choose which display will be used to map
> > this surface.

**Comment by flibitijibibo** [comment]
I believe this counts as NOTABUG - the way we set fullscreen is by using the output of the SDL_VideoDisplay that the window is on, meaning we toggle fullscreen at the same location as the window. While the spec does allow for null outputs, in this case I don't think it's a _bug_, just an unused feature.
