### ISSUE TITLE
Second SDL_KEYDOWN generated with a delay

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3746]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2020-06-19 10:49:31 +0000,  wrote:

> When Pressing Ctrl+Shift or Shift+Ctrl, the SDL_KEYDOWN for the second key is generated with the same delay as for repeat keypresses.

On 2020-06-19 11:04:27 +0000,  wrote:

> I have tried to get over it using SDL_GetModState() but it also reports key press changes with a delay.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
