### ISSUE TITLE
Creating window from SDL_CreateWindowFrom does not fire internal view events (e.g. resetCursorRects) on OS X

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3748]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** macOS 10.15, x86_64

# Comments on the original bug report:

On 2020-06-19 12:10:22 +0000, Konrad wrote:

> I believe this is a bug from SDL2 in which creating a custom window (NSWindow and NSView) and using SDL_CreateWindowFrom on it does lead to a situation where events from normally inheritable SDLView of NSView (SDL_cocoawindow.m) such has e.g. resetCursorRects or acceptsFirstMouse are not working since custom view does not inherit those event handlers. This is after all crucial for the application behavior.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
