### ISSUE TITLE
filesystem disable SDL_GetBasePath implementation

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3752]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Disable SDL_GetBasePath implementation (patch-src_filesystem_unix_SDL_sysfilesystem_c, text/plain, 2020-06-20 23:20:23 +0000, 954 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4393)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-06-20 23:20:23 +0000, Brad Smith wrote:

> Created attachment 4393
> Disable SDL_GetBasePath implementation
> 
> Disable the SDL_GetBasePath implementation on OpenBSD. It is not functional.

On 2020-09-05 02:23:35 +0000, Brad Smith wrote:

> ping.

On 2020-12-09 15:19:43 +0000, Sam Lantinga wrote:

> I imagine it worked at some point? Do you have replacement code?

**Comment by icculus** [comment]
I'll try this out the OpenBSD buildbot and see what happens.

**Comment by icculus** [comment]
So this works _sometimes_.

It works if there's an absolute path to the binary on the command line, and it works if there's a relative path and the current directory hasn't changed.

It 100% doesn't work if the program is run from the $PATH, or maybe if it's mangled it's argv[], if that affects the syscall.

We need a mechanism that doesn't rely on the command line for this.

**Comment by icculus** [comment]
I don't see anything in OpenBSD we can rely on for this. And apparently when asked for this functionality, Theo de Raadt replied "Quite expensive, for such a small need."  :/

https://marc.info/?l=openbsd-misc&m=144987773230417

So I guess the best fix is to search the $PATH if realpath() fails, and return NULL if that doesn't work out, and if something messes with the cwd or the command line, they're just out of luck on this platform.
