### ISSUE TITLE
Window is not resizable on wayland

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3753]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-06-20 23:29:47 +0000, Deve wrote:

> May be related to https://bugzilla.libsdl.org/show_bug.cgi?id=4859 because as I see you already started working on a patch.
> 
> In SDL_Video.c file there is
> 
> ```c
> if ((want != have) && (_this->SetWindowResizable)) {
>     if (want) {
>         window->flags |= SDL_WINDOW_RESIZABLE;
>     } else {
>         window->flags &= ~SDL_WINDOW_RESIZABLE;
>     }
>     _this->SetWindowResizable(_this, window, (SDL_bool) want);
> }
> ```
>
> so that SDL_WINDOW_RESIZABLE flag is set only if there is _this->SetWindowResizable. 
> 
> Currently Wayland backend doesn't have this function defined. I made a simple fix:
> ```c
> if ((want != have)) {
>     if (want) {
>         window->flags |= SDL_WINDOW_RESIZABLE;
>      } else {
>         window->flags &= ~SDL_WINDOW_RESIZABLE;
>      }
>      if (_this->SetWindowResizable)
>         _this->SetWindowResizable(_this, window, (SDL_bool) want);
> }
> ```
>
> and resizing works fine for me on KDE and also on Gnome after I set the hittest function. I'm not sure if/how it affects other backends though.
> 
> Or in worst case maybe just create empty SetWindowResizable function for wayland backend to make sure it doesn't break anything else?

**Comment by flibitijibibo** [comment]
This was resolved by https://github.com/libsdl-org/SDL/commit/e787282ba8021388d955a7481027beee46ea4f65#diff-d7981dffd4e10c93a60470c43124a2dcd1c56e6483f58937b347c0febbe8af12

**Comment by icculus** [comment]
Closing because Ethan already fixed it.  :)
