### ISSUE TITLE
Inputs sometimes stop registering after alt-tabbing back to game

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3758]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-06-28 09:06:18 +0000, Dennis Felsing wrote:

> Hi,
> 
> Using SDL 2.0.12 we have a bug report by multiple players in DDNet: https://github.com/ddnet/ddnet/issues/2369
> 
> The issue is that in the map editor (ctrl-shift-e) alt-tabbing to another window and then at some point back to the game sometimes messes up the inputs permanently. Mouse coordinates become something like -67108864 and keyboard inputs also don't register anymore. This seems to happen very sporadically, but after downgrading to SDL 2.0.8 it seems to have disappeared again.
> 
> Since I can't reproduce it myself, I can't debug deeper.
> 
> Best regards
> Dennis

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
