### ISSUE TITLE
Xbox One Controller Menu button not registering as Start on Android

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3763]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch which allows Android to read Xbox One Menu Button as Start (XboxOneStartButtonOnAndroid.diff, text/plain, 2020-07-06 15:27:03 +0000, 505 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4404)

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Android (All), All

# Comments on the original bug report:

On 2020-07-06 15:27:03 +0000,  wrote:

> Created attachment 4404
> Patch which allows Android to read Xbox One Menu Button as Start
> 
> Just spotted this during testing. 
> 
> Xbox One Wireless Controller (Model 1708) connected via Bluetooth to Amazon Fire TV (AFTT).
> 
> The Menu Button (as per diagram here: https://support.xbox.com/help/hardware-network/controller/xbox-one-wireless-controller) reports on most platforms as SDL_CONTROLLER_BUTTON_START but on Android is completely ignored.
> 
> It's an easy fix of adding a case for AKEYCODE_MENU to the switch in keycode_to_SDL() in SDL_sysjoystick.c to map the button to SDL_CONTROLLER_BUTTON_START:
> 
>         case AKEYCODE_BUTTON_START:
>         case AKEYCODE_MENU:    // <-- New bit
>             button = SDL_CONTROLLER_BUTTON_START;
>             break;
> 
> Patch attached.

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
