### ISSUE TITLE
Cannot open file 'SDL2.main.lib'

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3765]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Windows 10, All

# Comments on the original bug report:

On 2020-07-08 19:12:35 +0000,  wrote:

> I tried renaming 'SDL2main.lib' to the file it's looking for, but that led to a duplicate token. I'm really not sure what the problem is.
> Full error log:
> 1>------ Build started: Project: Project1, Configuration: Debug x64 ------
> 1>LINK : fatal error LNK1104: cannot open file 'SDL2.main.lib'
> 1>Done building project "Project1.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by madebr** [comment]
This looks like a user error to me.
