### ISSUE TITLE
Keyboard events are not received in cocoa app when not starting from SDL_main

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3777]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** macOS 10.15, x86_64

# Comments on the original bug report:

On 2020-07-17 21:28:50 +0000, Amir Amitai wrote:

> My setup is like this:
> From a WDL/SWELL main application (only a wrapper) I'm creating an SDL window on macOS - therefore an instance of SDLApplication is not being set.
> 
> After polling event with SDL_PollEvent,
> SDL_KEYDOWN, and SDL_KEYUP are not being called.
> You can force it to call if you smash the keyboard and it gets some keystrokes here and there.
> 
> SDL_GetModState() returns always zero and SDL_GetKeyboardState(NULL) never changes.
> 
> Debugging this, leads me to the problematic line:
> SDL_cocoaevents.m:
> NSEvent *event = [NSApp nextEventMatchingMask:NSEventMaskAny untilDate:[NSDate distantPast] inMode:NSDefaultRunLoopMode dequeue:YES ];
> 
> if we change it to 
> NSEvent *nextDown = [NSApp nextEventMatchingMask:NSEventMaskAny untilDate:[NSDate dateWithTimeIntervalSinceNow:0.01] inMode:NSDefaultRunLoopMode dequeue:YES];
> 
> After this, it started work, but it's too much time waiting there polling the event. I was looking everywhere what could be dequeuing this event. 
> 
> Eventually I have found the SDLWindow class, in SDL_cocoawindow.m.
> It has the same callback as SDLApplication - sendEvent. It receives all the keystrokes in time like a charm. from there I'm pushing it back to SDL's pipe by calling Cocoa_DispatchEvent(event).
> 
> It looks that the key handling events is on the NSApplication (SDLApplication) and not on the NSWindon (SDLWindow)
> 
> 
> here's my working patch (needs a bit of tidying):
> https://github.com/amiramitai/SDL-mirror/commit/5b5b818795e39b751c65b8e6c9bd908a4a0df853

**Comment by icculus** [comment]
So the weird thing about this is that there _is no_ SDL_main for macOS. It just uses the standard Unix main without any platform-dependent code before it. This wasn't true for SDL 1.2 on Mac OS X, fwiw.

I'm wondering if he's not running in an application bundle and it's causing issues, but afaik launching a Unix-style binary also works fine.

@amiramitai, are you still around and having this problem? Is there some way we can see the code of the app where this isn't working correctly?

**Comment by icculus** [comment]
I don't know, the patch doesn't look _unreasonable_ but there's more information we need here, about why this happens to him at all. I'm going to kick this to the 2.0.18 milestone for now.

**Comment by InfoTeddy** [comment]
The link to the patch in the OP now 404s.

**Comment by icculus** [comment]
ok, I'm giving up on this for now, because I don't have a copy of the 404'd patch and it seems to be generally working for everyone else without a patch.

@amiramitai, if you're still having this issue, please feel free to let me know and we'll reopen this bug and figure out what to do.
