### ISSUE TITLE
[PATCH] add Linux mapping for Ipega PG-9087S

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3783]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [[PATCH] add Linux mapping for Ipega PG-9087S (ipega_mappings.patch, text/plain, 2020-07-25 08:42:43 +0000, 1926 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4426)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-07-25 08:42:43 +0000, soredake wrote:

> Created attachment 4426
> [PATCH] add Linux mapping for Ipega PG-9087S
> 
> http://ipega.hk/gamehandle/53-194.html

**Comment by soredake** [comment]
I reported this.

**Comment by soredake** [comment]
[ipega_mappings.zip](https://github.com/libsdl-org/SDL/files/5963608/ipega_mappings.zip)
