### ISSUE TITLE
SDL timers don't like linux system time change

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3785]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2020-07-31 13:51:15 +0000, Guido wrote:

> SDL 2.0.10 on self build Linux (kernel 4.9) for an embedded target.
> 
> When changing the system time to a time/date in the past (using "date" on the terminal of the target) the SDL timers in my application don't trigger anymore. I guess this kind of makes sense, but it is a bit of a pain having to manual restart the timers after a date/time change.
> 
> FYI:
> -Target is not connected to the internet in normal operation, that's why the system time/date has to be changed manually.

**Comment by icculus** [comment]
We should be using the monotonic clock...his system might just not have support in the headers...?

I'll recheck for 2.0.16.

**Comment by icculus** [comment]
This works here, I think it was just an SDL built without monotonic clock support (which we can't do anything about).
