### ISSUE TITLE
Build warning on MSVC: M_PI redefined

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3790]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, All

# Comments on the original bug report:

On 2020-08-09 18:26:27 +0000, Albert Vaca Cintora wrote:

> On MSVC, including SDL.h and later including math.h, produces:
> 
> warning C4005: 'M_PI': macro redefinition
> 
> This is because SDL defines its own M_PI constant and math.h tries to define it again.
> 
> Instead of defining our own M_PI in SDL_stdinc.h, we should include math.h instead.
> 
> Note that, on top of that, MSVC needs _USE_MATH_DEFINES to be defined before including math.h, otherwise it won't define M_PI.

On 2020-08-10 23:22:19 +0000, Albert Vaca Cintora wrote:

> I found this problem is quite more easy to reproduce than I thought. If _USE_MATH_DEFINES is set, just by including SDL.h we trigger the compiler warning in MSVC about M_PI being redefined.
> 
> This is due to the following include chain:
> 
> SDL.h -> SDL_main.h -> SDL_stdinc.h -> #define M_PI
> SDL.h -> SDL_thread.h -> process.h -> corecrt_startup.h -> math.h -> #define M_PI again (if _USE_MATH_DEFINES is set)
> 
> I think SDL should not define M_PI itself and instead include math.h

On 2020-08-23 16:35:52 +0000, Albert Vaca Cintora wrote:

> It seems this fork of SDL has a similar fix to what I'm proposing here, so at least one more person found this annoying: https://github.com/Jimbly/SDL/commit/2e42806dbca55a22b5b15a4a5becc779f2118735

**Comment by slouken** [comment]
Sure, that sounds good.
