### ISSUE TITLE
Windows disappear when moving a window to second display in Windows 10

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3797]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [This is codeblocks in debug mode for multiple windows project. (2020-08-16.png, image/png, 2020-08-16 16:02:30 +0000, 1201038 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4439)

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-08-16 16:02:30 +0000, Allan Kiipli wrote:

> Created attachment 4439
> This is codeblocks in debug mode for multiple windows project.
> 
> My system has laptop and second monitor connected with hdmi cable.
> I use lazy foo examples with Codeblocks.
> 
> mingw32-g++.exe -LC:\SDL2-2.0.12\i686-w64-mingw32\lib -LC:\SDL-1.2.15\lib -o bin\Debug\37_multiple_displays.exe obj\Debug\37_multiple_displays.o  -lmingw32 -lSDL2main -lSDL2 -lopengl32 -lglu32 -lgdi32 -mwindows -lglew32mx -lglew32 -lfreetype -lDevIL -lILU -lILUT -lmingw32 -lSDLmain -lSDL -lSDL_image -lsdlgfx -lSDL_mixer -lSDL_ttf -lpthread  
> Output file is bin\Debug\37_multiple_displays.exe with size 1.00 MB
> 
> Both examples fail same way when i move window to the second display.
> 
> https://lazyfoo.net/tutorials/SDL/36_multiple_windows/index.php
> https://lazyfoo.net/tutorials/SDL/37_multiple_displays/index.php

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
