### ISSUE TITLE
SDL is blocking window compositor.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3802]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-08-22 10:52:59 +0000,  wrote:

> SDL is blocking window manager compositor. This can be fixed by turning off "Allow applications to block compositor" in systemsettings, howewer it's annoying, and it will not block also apps, where it is needed. There should be some function, such as SDL_Allow_Compositor(bool Allowed), or flag in SDL_Init() to leave enabled, or disable compositor.

On 2020-08-22 21:10:17 +0000, Ryan C. Gordon wrote:

> 
> Is this with X11? Set this environment variable:
> 
>     export SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0
> 
> 
> Or if you want to force it in your app, do this before calling SDL_CreateWindow:
> 
>     SDL_SetHint(SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR, "0");
> 
> --ryan.

**Comment by icculus** [comment]
This can be closed, since the hint handles the need.
