### ISSUE TITLE
Deadzone incorrectly applied to trigger on Linux

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3805]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-08-25 12:13:18 +0000, Mathieu Eyraud wrote:

> On Linux, deadzone for joystick axis are applied around 0. For triggers, this make their value snap on 0 in the middle of their travel.
> 
> I think deadzone should be applied around the rest value of the axis.

On 2020-12-09 14:44:23 +0000, Sam Lantinga wrote:

> Do you have a tested patch to fix this? I'm not sure whether Linux joysticks have specific axes that are designated as triggers.

On 2020-12-10 09:48:02 +0000, Mathieu Eyraud wrote:

> Taking a look at SDL_gamecontrollerdb.h, there is no axis designated for triggers.
> 
> Personnaly, I agree with pj5085 (bug5241) that deadzone should be removed. That would fix this bug.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
