### ISSUE TITLE
Controller mappings for Saitek P880

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3824]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Map string (sdlmapping, text/plain, 2020-09-15 19:28:17 +0000, 252 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4464)

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-09-15 19:28:17 +0000,  wrote:

> Created attachment 4464
> Map string
> 
> I apologize if this is the wrong place to submit this.
> 
> I found my old USB joypad and noticed many buttons were wrong despite an entry for this GUID. I can confirm this mapping is correct for linux (Linux kor 5.6.15-1-MANJARO # 1 SMP PREEMPT Wed May 27 20:38:56 UTC 2020 x86_64 GNU/Linux). I don't have another OS so I can't test on anything else.
> 
> The string is below and I attached a file just in case
> 
> 03000000a30600000901000000010000,Saitek P880,a:b2,b:b3,x:b0,y:b1,back:b4,guide:b10,start:b5,leftstick:b8,rightstick:b9,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a2,platform:Linux,

**Comment by slouken** [comment]
This is in, thanks!
