### ISSUE TITLE
SDL_RenderCopy ARGB888 texture to IYUV texture, RGB color be lost

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3829]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2020-09-22 06:45:54 +0000,  wrote:

> SDL_Texture *YUVtexture = SDL_CreateTexture(render, SDL_PIXELFORMAT_IYUV, /* YV12/NV12... */, SDL_TEXTUREACCESS_TARGET, width, height);
> if (texture)
> {
> SDL_UpdateYUVTexture(YUVtexture, NULL, yPlane, yPicth, uPlane, uPicth, vPlane, vPicth);
> 
> SDL_Texture *RGBtexture = SDL_CreateTexture(render, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STATIC, width, height);
> SDL_UpdateTexture(RGBtexture, NULL, rgbData, rgbPitch);
> 
> SDL_SetRenderTarget(m_render, YUVtexture);
> SDL_RenderCopy(m_render, RGBtexture, NULL, NULL); /* Copy RGB texture to YUV texture */
> SDL_SetRenderTarget(m_render, NULL);
> 
> SDL_RenderCopy(m_render, YUVtexture, NULL, NULL); /* RGB texture without color */
> }

On 2020-09-22 06:46:50 +0000,  wrote:

> render is OPENGL

**Comment by 1bsyl** [comment]
FOURCC isn't supported by renderer back-ends for target access
So use a correct format and fallback to with native/yuv path

Fixed in https://github.com/libsdl-org/SDL/commit/e87c7940f59db12670089a4ed79c91dfbca92b33
