### ISSUE TITLE
if SDL_ShowCursor fails to disable the cursor, a subsequent SDL_QUERY shows cursor enabled

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3830]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2020-09-24 17:29:06 +0000, Anthony @ POW Games wrote:

> I have an old Android 4.2.2 device that has a nice graphical mouse cursor which cannot be disabled by SDL2. SDL_ShowCursor(SDL_DISABLE) will return 1 (SDL_ENABLE / shown) and fail to show the cursor and set error "That operation is not supported". All great so far.
> 
> But subsequent calls to SDL_ShowCursor(SDL_QUERY) will wrongly return 0 (SDL_DISABLE / hidden).
> 
> This bug has probably always existed and may exist cross platform. I'm guessing it's an easy fix.

On 2020-12-09 14:38:18 +0000, Sam Lantinga wrote:

> SDL_ShowCursor() returns the previous state, not the new state, so I think the only issue is that it's not updating the cursor_shown state if setting a blank cursor fails.

**Comment by slouken** [comment]
This API has changed and now always returns 0.
