### ISSUE TITLE
AVAudioSessionCategoryAmbient is no longer the default

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3831]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Other, iPhone/iPod touch

# Comments on the original bug report:

On 2020-09-24 17:54:07 +0000, Diego wrote:

> This revision (http://hg.libsdl.org/SDL/rev/9c0592cc3e92) changed the default AVAudioSessionCategory from AVAudioSessionCategoryAmbient to AVAudioSessionCategoryPlayback which doesn't match the SDL_HINT_AUDIO_CATEGORY specified default value.

On 2020-10-02 01:04:35 +0000, Diego wrote:

> Also, SDL_hints.h says SDL_HINT_AUDIO_CATEGORY should be set to the string "ambient" to use AVAudioSessionCategoryAmbient, when SDL_HINT_AUDIO_CATEGORY actually needs to be set to the string "AVAudioSessionCategoryAmbient" to use AVAudioSessionCategoryAmbient.
> 
> Also, just to give some context, I believe the default AVAudioSessionCategory should be AVAudioSessionCategoryAmbient instead of AVAudioSessionCategoryPlayback because AVAudioSessionCategoryPlayback decreases all sounds other than the apps. For example, if you have music playing and open the app that uses AVAudioSessionCategoryPlayback, the music will decrease in volume. This is not the default behavior in iOS apps.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
