### ISSUE TITLE
SDL_GetWindowBordersSize() includes drop shadow on Windows

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3835]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-09-27 22:14:56 +0000, Michel Rouzic wrote:

> WIN_GetWindowBordersSize() relies on GetWindowRect() to get the rectangle of the outer window. The problem with this as MSDN explains is that this rectangle "includes the area occupied by the drop shadow", which is why I get 31 8 8 8 when clearly there isn't 8 px of visual border. So instead of:
> GetWindowRect(hwnd, &rcWindow);
> we should use:
> DwmGetWindowAttribute(hwnd, DWMWA_EXTENDED_FRAME_BOUNDS, &rcWindow, sizeof(rcWindow));
> 
> When my window is maximised this gives me 23 0 0 0 and when it's not I get 31 1 1 1, which seems to be exactly what it should be. Note that you might need to add something to the effect of the following to make it work:
> #include <dwmapi.h>
> #pragma comment (lib, "Dwmapi.lib")
> 
> Btw the SDL wiki hasn't been updated to reflect that SDL_GetWindowBordersSize() works on Windows.

**Comment by Swyter** [comment]
Take a look at 7c60bec4, I talk about why the grip border margin are included by design in my patch.

The equivalent ticket transplanted here from the original issue is #2768.
