### ISSUE TITLE
Bogus position data in mouse event when right clicking over an unfocused window

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3838]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** macOS 10.14, x86_64

# Comments on the original bug report:

On 2020-10-05 19:10:47 +0000, Miles wrote:

> In MacOS, right-clicking into a window doesn't focus it. However, the window can still recieve those mouse events. This is fine, except that the position given in the events is not right. If you get a MOUSEBUTTONDOWN or MOUSEBUTTONUP event, instead of reporting the current position of the mouse, the event contains the position of the where the mouse was most recently dragged.
> 
> So for example, if you repeatedly click around without dragging, it will keep reporting the same stale location for both MOUSEBUTTONDOWN and MOUSEBUTTONUP events, regardless of where you click. But if you repeatedly click and drag, you will get a MOUSEBUTTONDOWN event with the same position as the previous MOUSEBUTTONUP event, but the MOUSEBUTTONUP event will have the correct (current) mouse position. Basically, it seems to only be updating the reported mouse position when the mouse is dragged.
> 
> The positions reported by SDL_GetMouseState() are similarly stale, but those reported by SDL_GetGlobalMouseState() are not.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
