### ISSUE TITLE
SDL_MOUSEMOTION massive random xrel & yrel values when Present(): DEVICELOST

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3843]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-10-08 15:47:02 +0000, Anthony @ POW Games wrote:

> You can force a Present(): DEVICELOST in Windows by Ctrl+Alt+Del and cancelling. When the window is restored there is no harm is done, but...
> 
> If the mouse is within the window, a SDL_MOUSEMOTION event is generated with massive random xrel & yrel values. Then another SDL_MOUSEMOTION event is generated with zero xrel & yrel values. The mouse hasn't moved during this time.
> 
> Also, alt-tab away from the window and back into the window generates a SDL_MOUSEMOTION event, even though the mouse hasn't moved. But calling SDL_SetWindowFullscreen, which changes the window size and so the position of the mouse, doesn't generate a SDL_MOUSEMOTION event.
> 
> This all seems like strange behaviour. Might be related to bug 5154.
> 
> I'm not using any relative mouse mode functions. It happens in both full screen and windowed.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
