### ISSUE TITLE
[rfe] implement console switching

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3844]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-10-09 16:15:28 +0000, Stas Sergeev wrote:

> SDL2 seems to support drm rendering without X.
> But in this mode console switching doesn't work.
> Neither Alt-fN not Ctrl-Alt-fN (where N is a
> console number) produce any switch.

On 2020-10-15 15:32:47 +0000, Manuel Alfayate Corchete wrote:

> Isn't this happening because SDL2 is getting the input instead of TTY?
> In other words, I guess that non-working TTY switching while a program is running is the intended behaviour, if I am not mistaken.
> I don't even start to guess how to do this, if possible at all.

On 2020-10-15 16:25:30 +0000, Stas Sergeev wrote:

> > Isn't this happening because SDL2 is getting the input instead of TTY?
> 
> Yes, this is the reason why native switching is disabled.
> But it won't work anyway. It just doesn't look like DRM
> console can switch the rendered content on its own. I
> tried to enable the native switching, but it never restores
> the graphical content when I switch back.
> 
> > I don't even start to guess how to do this, if possible at all.
> 
> Classic gfx console switching works as follows.
> 
> ioctl(0, VT_GETSTATE, &vts);
> our_vt_num = vts.v_active; // get our console num
> ioctl(0, VT_SETMODE, VT_PROCESS); // enter manual console switching
> ioctl(0, KDSKBMODE, KD_GRAPHICS); // switch console to gfx mode
> /* do some gfx rendering here */
> /* detect Ctrl-Alt-fN presses */
> ioctl(0, VT_ACTIVATE, N); // activate console N
> usleep(10000);      /* some kernel bug, hangs without this */
> ioctl(0, VT_RELDISP, 1); // confirm console release
> ioctl(0, VT_WAITACTIVE, N); // wait activation of console N
> ioctl(0, VT_WAITACTIVE, our_vt_num); // wait until our console is switched on again when user hits Ctrl-Alt-f<our_vt_num>
> /* restore the gfx image here, as it gets destroyed */
> /* return back to client code */
> 
> I hope DRM console have some better techniques
> than all that crap. In particular, it would be
> cool if it could at least save/restore image itself.
> But my experiment shows its not the case, so perhaps
> you'll have to execute the entire sequence above. :(

On 2020-10-16 10:01:02 +0000, Stas Sergeev wrote:

> Even after googling for the whole day, I can't
> find any docs on drm VT switching, other than
> that you need to "drop master" via drmDropMaster().
> But you do not seem to be doing drmSetMaster()
> anyway.
> Maybe you just need to do drmDropMaster()
> before ioctl(0, VT_RELDISP, 1), and do the
> classical switching? Or should it be something
> entirely different?
> Is this drm stuff that much undocumented...

**Comment by hramrach** [comment]
AFAIK there is no drm console, only FB console. Hence no drm console switching. #4812 mentions seatd for switching between applications but not familiar with that.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by stsp** [comment]
Why is this "not planned"?
I think switching consoles is an
absolute must to have, if you are
serious about kmsdrm support.

**Comment by stsp** [comment]
https://github.com/mpv-player/mpv/pull/9270
This is an example of implementing
the console switching under kmsdrm.
It requires linux-5.10, which is quite
old today, so perfectly suitable.

Please re-open and consider porting
that code to sdl.

**Comment by stsp** [comment]
https://github.com/torvalds/linux/commit/45bc3d26c95a8fc63a7d8668ca9e57ef0883351c
This is the commit that added the
needed functionality.
It even pre-dates this ticket.

**Comment by slouken** [comment]
Thanks for the info! I'm reopening this issue.
