### ISSUE TITLE
Bordersize can't be polled immediately after window creation

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3853]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-10-13 13:17:12 +0000,  wrote:

> Hello all,
> 
> I am currently trying to setup clamping windows to the edges of the screen when they're being created. This is mostly used for popups/context-menus.
> 
> My calculations are all fine, however when I pass the variables to `SDL_CreateWindow` the created window sticks out to the right by 2 * the border of the window.
> So I tried polling `SDL_GetWindowBordersSize`. This however always sets all variables to 0 (and returns 0 as well so it's successful) if polled immediately after the window creation. 
> After some digging I figured out that this has to do with the fact that SDL doesn't post a `_NET_REQUEST_FRAME_EXTENTS` to the window manager during window creation.
> 
> I believe this to be a bug since it appears that SDL internally also takes this into account. If I just call `SDL_CreateWindow(args)` the window sticks out to the right. If I add a `std::this_thread::sleep_for(50ms)` after the window creation it is properly aligned at the right screen edge without any overhang. This seemingly indicates that SDL wants to take the border-size into account but can't because the values aren't there yet since they haven't been requested from the WM.
> 
> sincerely,
> Folling

On 2020-10-14 09:57:24 +0000,  wrote:

> I just noticed this only happens if I call `SDL_ShowWindow` shortly after the window's creation. Not doing that resolves the issue. I presume this might be because it forces SDL to show the window before the frame extents information is polled.

**Comment by icculus** [comment]
An unmapped X11 window has no decorations and thus no border size, and we don't know this information until the window manager assigns decorations asynchronously. I'm not sure if this is something we can or should fix. Maybe just a documentation note about the platform-specific quirk?

**Comment by flibitijibibo** [comment]
FWIW, Wayland is exactly the same way and is explicit about this behavior. It's probably worth documenting as unavailable until the window has been presented at least once and has had a chance to be decorated by the display server.

**Comment by icculus** [comment]
Yeah, let's document this. I feel like this has bitten people several times now, and afaik there isn't some notification we can wait on to know when it's ready (or if it's coming at all).
