### ISSUE TITLE
Suggestion: default to Wayland for better compatibility, at least on mobile (or maybe everywhere?)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3862]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2020-10-27 23:09:13 +0000, Ellie wrote:

> On the PinePhone, it appears SDL2 defaults to XWayland still. This means issues with scaling and such, because the X11 compatibility of the new phone-centric mobile desktops is often quite basic and incomplete. I would anticipate this to possibly remain that way since GTK+ and Qt work nicely with Wayland, so there is no incentive for those new desktops to iron out the X11 support for all corner cases. As a result, SDL2 defaulting to X11/XWayland (without an env var set to change this) means it automatically runs in a buggier second class mode.
> 
> Would it therefore make sense to always have SDL2 try Wayland first? I can't really see the harm in an X11-only environment, where that would simply fail and then SDL2 would fall back to X11 anyway. Or am I missing something? Is there a reason this isn't how it currently operates other than nobody thought of it so far?

**Comment by icculus** [comment]
Favoring Wayland over X11 by default absolutely can't happen before libdecoration is widely available, as SDL's Wayland experience is going to be subpar without window decorations.

But in the meantime, mobile devices can set the environment variable SDL_VIDEODRIVER=wayland to force SDL to favor it over X11 at runtime.

Closing this bug, but my hope is at some point we _will_ favor Wayland over X11, even while X11 is the more common system...but we aren't there yet.
