### ISSUE TITLE
System Detection Is Not Correct

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3867]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-11-02 14:39:08 +0000,  wrote:

> Because of msys2 use cygwin core, The system is always regurded as unix OS, not windows or win32. It will cause a lot of error when trying to build SDL2.

**Comment by icculus** [comment]
I'm assuming this is resolved, or it's a configuration we don't support.
