### ISSUE TITLE
DirectX HARDWARE RENDERER: SDL_RenderSetClipRect doesn't work properly when used with SDL_RenderCopy

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3876]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Left == broken version, Right == correct version (Capture (1).png, image/png, 2020-11-11 01:40:01 +0000, 14523 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4512)

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-11-11 01:40:01 +0000,  wrote:

> Created attachment 4512
> Left == broken version, Right == correct version
> 
> When using SDL_RenderSetClipRect with SDL_RenderCopy while using DirectX, it appears that the back buffer isn't cleared. Attached an image to show side by side differences.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
