### ISSUE TITLE
Electric fence reports malloc(0) on SDL_Init(SDL_INIT_VIDEO)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3897]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Stack trace (stack trace.png, image/png, 2020-11-30 07:39:41 +0000, 97950 bytes)](https://bugzilla-attachments.libsdl.org/attachments/4547/stack%20trace.png)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2020-11-30 07:39:41 +0000, Guido wrote:

> Created attachment 4547
> Stack trace
> 
> Electric fence reports "ElectricFence Aborting: Allocating 0 bytes, probaly a bug" on SDL_Init(SDL_INIT_VIDEO). In my case SDL_Init is called in a function called from main.c. I tried calling it directly from the main() without any luck, still the same outcome.
> 
> SDL: 2.0.10 (linked & compiled)
> Language: C
> OS: Linux Mint 20 Cinnamon 4.6.7 on VMware Player on Win10Pro
> 
> Added stack trace (png)

**Comment by InfoTeddy** [comment]
The attachment leads to a 404.

**Comment by sezero** [comment]
Here is the attachment recovered from https://web.archive.org/web/20210211231141/https://bugzilla.libsdl.org/show_bug.cgi?id=5370

![stack trace](https://user-images.githubusercontent.com/4222725/146711864-378ccc9f-6f35-4ef3-8fdd-d039188ad19e.png)

**Comment by icculus** [comment]
The malloc(0)--actually a memalign(0)--appears to be happening in an OpenGL driver. Not our bug.
