### ISSUE TITLE
Corrupted background color in fullscreen Metal on Big Sur

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3903]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Expected output (OpenGL) (OpenGL.png, image/png, 2020-12-02 03:14:20 +0000, 217675 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4552)
* [Broken output (Metal) (Metal.png, image/png, 2020-12-02 03:14:54 +0000, 547416 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4553)

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2020-12-02 03:13:34 +0000, Cameron Gutman wrote:

> When running on Big Sur using Metal, I see areas in my app that should be solid black (cleared and never drawn) showing up as an odd striped red and black color. I haven't the slightest clue what is happening, but I was able to reproduce it with one of the SDL test apps.
> 
> It seems to be new to Big Sur and doesn't happen on Catalina. SDL 2.0.12 and SDL Hg (8d5e22789f3f) are both impacted.
> 
> The following invocations all reproduce the bug:
> ./testsprite2 --fullscreen-desktop
> ./testsprite2 --fullscreen
> 
> The following invocations do NOT reproduce the bug:
> ./testsprite2
> ./testsprite2 --fullscreen-desktop --renderer opengl
> ./testsprite2 --fullscreen --renderer opengl
> 
> In case it matters, I'm running:
> MacBook Pro (13-inch, 2020, 4 Thunderbolt Ports)
> 2.3 GHz Intel Core i7 (Ice Lake)
> Intel Iris Plus Graphics
> macOS Big Sur 11.0.1
> Xcode 12.2

On 2020-12-02 03:14:20 +0000, Cameron Gutman wrote:

> Created attachment 4552
> Expected output (OpenGL)

On 2020-12-02 03:14:54 +0000, Cameron Gutman wrote:

> Created attachment 4553
> Broken output (Metal)

On 2020-12-09 14:26:40 +0000, Sam Lantinga wrote:

> Ryan, can you look at this for the SDL release? Do you have hardware for testing?

**Comment by slime73** [comment]
Hi @cgutman , I just tried to reproduce this on my 2016 MBP with macOS 11.2 using the latest SDL code from git and I couldn't (it behaved as expected for me). I did have to change a couple things for it to choose the Metal renderer backend though.

Are you able to reproduce it with the latest code? If so, are there any OS updates available for you?

**Comment by cgutman** [comment]
yes, it still reproduces on 11.2. I believe it's a driver bug with Big Sur on the Ice Lake IGP. It doesn't impact my 2016 MacBook on Big Sur nor did it impact the 2020 MBP under Catalina. I also noticed that my Qt 6.0 app was also impacted with the same red stripes using Qt's Metal renderer.

I will see if the 11.3 Beta fixes it, otherwise I'll report it to Apple.
