### ISSUE TITLE
VK_MVK_ios_surface and VK_MVK_macos_surface deprecated by VK_EXT_metal_surface

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3906]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2020-12-04 20:03:59 +0000, Diego wrote:

> Not so much a bug as information.
> Similarly vkCreateMacOSSurfaceMVK and vkCreateIOSSurfaceMVK are deprecated by vkCreateMetalSurfaceEXT.

**Comment by ellipticaldoor** [comment]
Any follow up on this?

https://github.com/charles-lunarg/vk-bootstrap expects `VK_EXT_metal_surface` instead of `VK_MVK_macos_surface` and then it makes it crash
