### ISSUE TITLE
SDL_gamecontrollerdb mapping for PowerA XBox One Controller on Linux

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3910]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-12-08 20:10:17 +0000,  wrote:

> The PowerA Xbox One Wired controller does not appear to be in the gamecontrollerdb. 
> 
> The following is what I used to make it work, setting it in my user's profile:
> 
> export SDL_GAMECONTROLLERCONFIG=03000000c62400003a54000001010000,PowerA XBox One Controller SDL2,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.7,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux
> 
> This came from this ticket: https://github.com/ValveSoftware/steam-for-linux/issues/7200

**Comment by sezero** [comment]
I think this deserves fixing for 2.0.16
