### ISSUE TITLE
ARM support little update proposal

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3929]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch proposal (patch, text/plain, 2020-12-17 23:13:15 +0000, 6257 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4586)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Other, ARM

# Comments on the original bug report:

On 2020-12-17 23:13:15 +0000, David Carlier wrote:

> Created attachment 4586
> Patch proposal
> 
> No fix but mostly an update for ARM architecture.

On 2020-12-18 14:55:49 +0000, Ozkan Sezer wrote:

> It looks like this patch is applied as https://hg.libsdl.org/SDL/rev/35a9cd058340
> Closing.

**Comment by icculus** [comment]
(mentioned the wrong issue number in an unrelated bug, disregard.)
