### ISSUE TITLE
Playstation 5 Controller has no rumble support on Linux.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3937]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-12-22 05:07:07 +0000,  wrote:

> When using the Playstation 5 Controller on Linux (Pop OS 20.04), upon using "SDL_GameControllerRumble" there is no haptic feedback, both from Bluetooth as well as wired. The weird thing about this is that, the function returns "0" which implies that it's functioning with a rumble-enabled controller, even though it doesn't actually cause any rumble feedback when executing.

**Comment by Wohlstand** [comment]
Recently I and my friend reproduced the same on Linux and on Android

**Comment by Wohlstand** [comment]
P.S. Forgot to tell, SDL 2.0.18 was used here.

**Comment by slouken** [comment]
I don't think rumble is hooked up in the Linux PS5 kernel driver. Were you able to confirm that you were using the SDL HIDAPI driver? I would expect it to work there.

**Comment by Wohlstand** [comment]
From my side, I can confirm, PS5 controller works just fine on my end, all buttons, rumble, etc. Both wired and Bluetooth. Linux Mint 21.2.

**Comment by slouken** [comment]
Great, thanks.
