### ISSUE TITLE
Committed memory keeps rising when repeatedly resizing window with openGL context.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3947]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Native win32 test case for possibly related problem. (win32_crash_leak_investigation.cpp, text/plain, 2020-12-31 11:32:48 +0000, 4414 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4622)

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-12-29 22:58:18 +0000, Filippo Crocchini wrote:

> I managed to repro this problem with this example (not mine) https://gist.github.com/jordandee/94b187bcc51df9528a2f
> 
> If you spam "f" to toggle fullscreen the committed memory keeps rising and stays the same after you stop.
> It also seems to happen after resizing the window, but for some reason sometimes it decreases although increasing on average.
> 
> I checked with Resource Monitor(perfmon.exe)and with Visual Studio.

On 2020-12-31 11:31:23 +0000, Filippo Crocchini wrote:

> Upon further investigation it looks like it could be a driver issue, both the drivers for Intel UHD Graphics 630 version 27.20.100.8681 and for Nvidia RTX 2060 version 27.21.14.6089 have almost the same problem. I tried on a different machine with different drivers and everything works fine.
> 
> If the reason is the same as the one I found then it's not an SDL bug, I have attached the code that I used to test it (the problem is with SwapBuffers and wglSwapLayerBuffers). If you don't have the same problem then I may just be very unlucky.
> 
> You may have better chances to get those bugs fixed on the driver side so I'm leaving this here.

On 2020-12-31 11:32:48 +0000, Filippo Crocchini wrote:

> Created attachment 4622
> Native win32 test case for possibly related problem.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
