### ISSUE TITLE
X_setInputfocus BadMatch 42

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3949]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-12-30 23:20:08 +0000, ghen_arcanum wrote:

> Operating System: Void Linux
> 
> When starting the program, the new window blinks for a second then crashes with:
> 
> Pioneer:
> X Error of failed request:  BadMatch (invalid parameter attributes)
>   Major opcode of failed request:  42 (X_SetInputFocus)
>   Serial number of failed request:  220
>   Current serial number in output stream:  221
> 
> Grafx-sdl2 version:
> X Error of failed request:  BadMatch (invalid parameter attributes)
>   Major opcode of failed request:  42 (X_SetInputFocus)
>   Serial number of failed request:  214
>   Current serial number in output stream:  215
> 
> I came across this while compiling grafx2 for void linux. You can do three versions with it: normaly it uses sdl 1.2.x for compiling, which works fine. The X-version without sdl works fine too, just the sdl2 version doesn't work.
> 
> likewise every program using sdl2 crashes on my system.
> 
> I have quite a niche windowmanager, which is amiwm. But Gimp and Krita works totally fine with it. 
> 
> It seems that your competition had a similar problem:
> https://github.com/SFML/SFML/issues/991
> and there it was even linked to a bug here
> https://bugzilla.libsdl.org/show_bug.cgi?id=2997
> and it even says it is patched! Which is confusing.
> 
> What is going on? :) thx in advance

On 2021-01-12 17:21:11 +0000, Ryan C. Gordon wrote:

> 
> Going to guess it's this code in X11_ShowWindow...
> 
>     if (!data->videodata->net_wm) {
>         /* no WM means no FocusIn event, which confuses us. Force it. */
>         X11_XSetInputFocus(display, data->xwindow, RevertToNone, CurrentTime);
>         X11_XFlush(display);
>     }
> 
> I'll try to reproduce over here.
> 
> --ryan.

**Comment by icculus** [comment]
I threw an XSync in here, which made the problem go from 100% reproducable on amiwm to 0%, but it's possible this just moved the needle enough to beat a race condition and we need to be more aggressive in querying the window to see if it's officially marked as mapped before calling XSetInputFocus().

But for now, this is good enough.
