### ISSUE TITLE
opengles: Reduce drawcalls and improve the performance of SDL_RenderCopy and SDL_RenderCopyEx

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3956]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Reduce drawcalls of SDL_RenderCopy and SDL_RenderCopyEx. (SDL_opengles_merge_render_copies.patch, text/plain, 2021-01-02 12:25:02 +0000, 11788 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4627)

**Reported in version:** 2.0.15
**Reported for operating system, platform:** iOS (All), x86_64

# Comments on the original bug report:

On 2021-01-02 12:25:02 +0000,  wrote:

> Created attachment 4627
> Reduce drawcalls of SDL_RenderCopy and SDL_RenderCopyEx.
> 
> This patch roughly merges multiple glDrawArrays calls into a single glDrawArrays call to improve performance of SDL_RenderCopy and SDL_RenderCopyEx for rendering a large number of small sprites sharing the same texture.
> 
> 8192 "icon.bmps" were created with random color and angular velocity on iphone 6.
> The original SDL2 render these sprites at about 24 Frames Per Second while the patched SDL2 do the same thing at more than 39 Frames Per Second. The patch makes it possible to render more small particles fast with SDL2.

On 2021-01-02 18:17:21 +0000, Sam Lantinga wrote:

> Ryan, is this something that's generally useful for all the renderers?

On 2021-01-12 04:32:35 +0000, Ryan C. Gordon wrote:

> (In reply to Sam Lantinga from comment # 1)
> > Ryan, is this something that's generally useful for all the renderers?
> 
> Yes, many of them can benefit from this at a higher level. A good practical use case is particle systems that will draw maybe hundreds of the same sprite with different vertex colors and rotations.
> 
> Some of the renderers have the vertex color put in a uniform, which would need to be replaced to work with this approach, and could probably do the merging on the fly at a higher level, but yeah, something like sowfelicity's patch is worth aiming for.
> 
> --ryan.

**Comment by 1bsyl** [comment]
I think we can close it as batching has been added
