### ISSUE TITLE
SDL 2.0.14 and hg tip FTBFS on Ubuntu 14.04 if wayland deps are installed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3966]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [config.log from FTBFS with wayland deps installed on Ubuntu 14.04 (config.log, text/x-log, 2021-01-04 11:26:43 +0000, 313234 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4637)

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2021-01-04 11:26:43 +0000, Rémi Verschelde wrote:

> Created attachment 4637
> config.log from FTBFS with wayland deps installed on Ubuntu 14.04
> 
> When building SDL 2.0.14 or the current hg tip on Ubuntu 14.04 64-bit with wayland deps installed, `./configure` enables `wayland(dynamic)` support but then `make` fails:
> 
> ```
> # make
> Warning, configure is out of date, please re-run autogen.sh
> mkdir -p -- gen
>   GEN    gen/org-kde-kwin-server-decoration-manager-client-protocol.h
> usage: ./scanner [client-header|server-header|code]
> 
> Converts XML protocol descriptions supplied on stdin to client headers,
> server headers, or protocol marshalling code.
> make: *** [gen/org-kde-kwin-server-decoration-manager-client-protocol.h] Error 1
> ```
> 
> I did not check which deps are required exactly but installing `libsdl2-dev` seems to provide the necessary deps for wayland support being enabled automatically.
> 
> Steps to reproduce:
> 
> - Run Ubuntu 14.04, e.g. in Docker
> - `apt-get install libsdl2-dev`
> - `./configure && make`
> 
> I attach the `config.log` from a failed build of latest hg tip (fdcd36d21c77).
> Note that I'm running a Ubuntu 14.04 container with `podman` on Fedora 33, so some of the specs might be matching the host maching (like `uname -r`).

**Comment by icculus** [comment]
Just realized this said _14.04_ and I'm just going to go ahead and close it. This doesn't seem like something we'll fix.
