### ISSUE TITLE
iOS always defines main() even if built as a shared library

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3979]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.15
**Reported for operating system, platform:** iOS (All), x86

# Comments on the original bug report:

On 2021-01-10 23:29:18 +0000, Caleb Cornett wrote:

> Before the Xcode/Xcode-iOS merge, the iOS SDL_main definition could be disabled for shared libraries by defining IOS_DYLIB=1 (which is still defined in the iOS-Shared target in the new Xcode project file). However, the check for that define was removed so main() is now always defined: https://hg.libsdl.org/SDL/rev/6c2bbcfc3940 vs. https://hg.libsdl.org/SDL/file/17d911637a65/src/main/uikit/SDL_uikit_main.c
> 
> This is problematic for applications which do not statically link with SDL2, or which have their own main function. It seems the simplest solution is to just copy the #if defined(...) from the old uikitappdelegate code into SDL_uikit_main, but there might be a better option.

**Comment by slouken** [comment]
This is fixed in SDL3.
