### ISSUE TITLE
SDL_RWsize() returns wrong value if start pos != 0 ?

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4026]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2021-01-28 03:07:32 +0000, Ozkan Sezer wrote:

> Suppose that I do:
> ```c
>     FILE *f = fopen("test","rb"); /* 100 bytes file */
>     fseek(f, 20, SEEK_SET);
>     SDL_RWops *rw = SDL_RWFromFP(f);
> ```
> SDL_RWsize() would give me 100 instead of 80.  Only if I apply the
> following then it gives me 80.  Is this an unsupported scenario or
> is it an oversight?
> ```diff
> diff --git a/src/file/SDL_rwops.c b/src/file/SDL_rwops.c
> --- a/src/file/SDL_rwops.c
> +++ b/src/file/SDL_rwops.c
> @@ -357,7 +357,7 @@ stdio_size(SDL_RWops * context)
>      size = SDL_RWseek(context, 0, RW_SEEK_END);
>  
>      SDL_RWseek(context, pos, RW_SEEK_SET);
> -    return size;
> +    return size - pos;
>  }
>  
>  static Sint64 SDLCALL
>```

On 2021-01-28 03:30:02 +0000, Ozkan Sezer wrote:

> Another scenario is the test case from bug # 4410:
> ```c
>     SDL_RWops *file = SDL_RWFromFile("test.dat", "rb");
>     SDL_RWseek(file, 69531, RW_SEEK_SET); /* MP3 is 69531 bytes from start */
>     Mix_Music *music = Mix_LoadMUS_RW(file, 0);
>     Mix_PlayMusic(music, -1);
> ```
> And see current hg for this:
> https://hg.libsdl.org/SDL_mixer/file/a341f68abf34/src/codecs/mp3utils.c#l29
> 
> I can easily fix bug # 4410 by doing the following:
> ```diff
> diff --git a/src/codecs/music_mpg123.c b/src/codecs/music_mpg123.c
> --- a/src/codecs/music_mpg123.c
> +++ b/src/codecs/music_mpg123.c
> @@ -231,6 +231,7 @@ static void *MPG123_CreateFromRW(SDL_RWo
>      music->mp3file.src = src;
>      music->volume = MIX_MAX_VOLUME;
>  
> +    music->mp3file.start  = SDL_RWtell(src);
>      music->mp3file.length = SDL_RWsize(src);
>      if (mp3_skiptags(&music->mp3file, SDL_TRUE) < 0) {
>          SDL_free(music);
> ```
> ... _but only if_ I apply the patch stdio_size() patch to SDL2.
> 
> SDL_rwops.c::windows_file_size() has the same issue.

On 2021-01-28 14:07:51 +0000, Ozkan Sezer wrote:

> I fixed the bug # 4410 issue by not using SDL_RWsize() and fixing
> other mistakes in the code there.
> 
> However the SDL_RWsize() concerns I noted here still remain. Not
> sure if they are to be fixed, though.

On 2021-02-05 12:26:27 +0000, Ozkan Sezer wrote:

> Closing this as WONTFIX -- any changes to RWsize() would be too
> intrusive and result in other possible bugs.

**Comment by icculus** [comment]
Reopening this for consideration in SDL3.

**Comment by slouken** [comment]
Conceptually `SDL_RWsize()` returns "the size of the datastream", which to date has meant the entire size of the file, regardless of current seek position. I think if we change that to "the remaining size of the datastream" we would break lots of code. We could add `SDL_RWremaining()` if we wanted that had the behavior you expected, or people can just do `SDL_RWsize() - SDL_RWtell()`...

**Comment by sezero** [comment]
The intent might be feeding SDL a datastream from a non-zero offset.
However: The whole issue _may_ very well be non-existing now, now
that FromFP functionality is gone, so you may ignore the thing. (I just
wanted to be sure.)

**Comment by sezero** [comment]
Well, however I look at it, this is now a non-issue. Closing again.
