### ISSUE TITLE
Windows-specific: wrong window size after SDL_SetWindowResizable()

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4031]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Windows 8, x86

# Comments on the original bug report:

On 2021-01-29 10:04:27 +0000, Ivan wrote:

> Under Windows:
>  1. Create a window without SDL_WINDOW_RESIZABLE flag 
>  2. Call SDL_SetWindowResizable() to make it resizable.
>  3. Try to resize it and get a SDL_WINDOWEVENT_SIZE_CHANGED with WRONG window size (width and height is decreased by 10).
> 
> This happens if no SDL_SetWindowSize() is called between 2 and 3. 
> Because Windows needs to update window size via MoveWindow() when window's style (border type) is changed, otherwise it reports wrong client area.

On 2021-01-29 10:06:46 +0000, Ivan wrote:

> I'd suggest to add MoveWindow() call after SetWindowLong() in WIN_SetWindowResizable() in SDL_windowswindow.c

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
