### ISSUE TITLE
SDL >= 2.0.14 "real" fullscreen does not minimize on META key press

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4039]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2021-02-01 18:11:00 +0000,  wrote:

> On SDL 2.0.12 it works fine.
> master and the package from debian do not work.
> 
> debian unstable
> KDE
> X11

**Comment by j4reporting** [comment]
Windows is also affected. Switching from fullscreen to desktop via ALT + TAB  or windows key  does not minimize  SDL screen.
The resolution of the desktop  is not restored if  the SDL full screen resolution differ.

**Comment by icculus** [comment]
We changed this to not minimize when fullscreen loses focus in 2.0.14 because doing so causes a bunch of other bugs. (See #3656) but clearly this needs more work, or a revert.

**Comment by peppy** [comment]
Just a heads up that we also had many [users experience](https://github.com/ppy/osu-framework/issues/4322) this, and have since had to flip the hint across.

**Comment by Cacodemon345** [comment]
This "fix" causes much more problems than it fixes. I also couldn't reproduce #3656 on a Windows system so it is likely a X11 bug.

**Comment by slouken** [comment]
I think what we want to do here is have the default of the hint be "auto", which will be "1" for fullscreen windows and "0" for fullscreen desktop windows. We want to minimize fullscreen windows so they restore the video mode, but fullscreen desktop windows are usually managed by the window manager and usually just go to the background in games that use that mode.

Ryan, can you try this out and see if it fixes people's issues?

**Comment by j4reporting** [comment]
I think this will just create another problem for Windows, because "borderless" windows are not minimized  with  <WinKey> + <Down Arrow>.  The only way to minimize borderless windows is to use some utilities like GUIPropView by nirsoft or to use the 'Show Desktop' function,  For Windows, the old default setting of "1"  works best and is consistent with user experience over the years.

**Comment by slouken** [comment]
> I think what we want to do here is have the default of the hint be "auto", which will be "1" for fullscreen windows and "0" for fullscreen desktop windows. We want to minimize fullscreen windows so they restore the video mode, but fullscreen desktop windows are usually managed by the window manager and usually just go to the background in games that use that mode.

This is what we ended up doing for 2.0.16. The hint is still respected if people want specific behavior, but by default real fullscreen games will minimize when losing focus so the video mode is restored.
