### ISSUE TITLE
Maximised window with SDL_BORDERLESS_WINDOWED_STYLE hint has edges clipped and overlaps 2nd monitor

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4043]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Screenshot of clipped edge and overlap onto second monitor when maximised (SDL maximised bug.png, image/png, 2021-02-04 10:10:20 +0000, 34913 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4760)

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2021-02-04 10:10:20 +0000, Jon wrote:

> Created attachment 4760
> Screenshot of clipped edge and overlap onto second monitor when maximised
> 
> Maximising a window created with the SDL_BORDERLESS_WINDOWED_STYLE and SDL_BORDERLESS_RESIZABLE_STYLE hints results in the edges of the drawable region being clipped and some visible overlap on a second monitor.
> 
> 
> Steps to Reproduce
> 
> 1. Set SDL_BORDERLESS_WINDOWED_STYLE and SDL_BORDERLESS_RESIZABLE_STYLE hints
> 2. Create a window with flags SDL_WINDOW_OPENGL | SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE
> 3. Maximise window through any means (drag-snapping to the top of the screen, double-clicking custom titlebar area, win-up)
> 
> 
> Actual Results
> 
> The window becomes too large for the monitor it is displayed on with roughly 8px around all edges of the window being cut off.
> 
> Additionally, with a dual monitor setup, maximising the window on the rightmost monitor results in a black strip down the side of the other monitor. The overlap appears to be the same width as the strip that is cut off from the edge of the window, and has the same height as the height of the window prior to maximising.
> 
> 
> Expected Results
> 
> No overlap on the second monitor, and for the client area of the maximised window to be fully within the bounds of the monitor and taskbar with no part of the gl context clipped.
> 
> 
> Build Date & Hardware
> 
> Tested with SDL 2.0.14 (stable)
> Windows 10 Version 10.0.18363 Build 18363
> 
> 
> Additional Information
> 
> - The monitors are both 1080p, landscape with display scaling set to 100% 
> - The rendered content is using a glViewport of (0, 0, win_w, win_h) where win_w and win_h are the values returned by SDL_GetWindowSize
> - The width and height returned by SDL_GetWindowSize when maximised is 1936x1056, which is 16px wider than the resolution of the display (and presumably taller than the space between the top of the display and the taskbar)
> - I have only tested this on a dual-monitor setup so can't currently be sure if the clipping issue is present for single-monitor setups
> 
> I've also attached a screenshot showing the issue.

**Comment by slouken** [comment]
When you use the borderless windowed style, Windows still believes that your window has decorations, and will calculate the maximum size of your window appropriately, and position it with the client area onscreen and the decorations offscreen.

Raymond Chen has more explanation here:
https://devblogs.microsoft.com/oldnewthing/20150304-00/?p=44543

**Comment by slouken** [comment]
This is fixed by https://github.com/libsdl-org/SDL/commit/41e1a2360f2b26d9167b85f2f2259757d4f5ea28.
