### ISSUE TITLE
[Patch] Check for WAYLAND_CLIENT_H header guard

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4044]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Fix for WAYLAND_CLIENT_H (wlheader.diff, text/plain, 2021-02-05 00:08:43 +0000, 764 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4761)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2021-02-05 00:08:43 +0000, Ethan Lee wrote:

> Created attachment 4761
> Fix for WAYLAND_CLIENT_H
> 
> Attached is a patch to fix the wayland-client.h header check - newer versions appear to use WAYLAND_CLIENT_H instead of _WAYLAND_CLIENT_H. Not a big deal, just have to check for both.

**Comment by slouken** [comment]
Patch added, thanks!
https://github.com/libsdl-org/SDL/commit/cad67082f325ea29a742bc9bf6ee5eba83372c79
