### ISSUE TITLE
[PATCH] Support using CRITICAL_SECTION-based mutexes with condition variables on Windows

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4051]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[Patch (condvar_cs.patch, text/plain, 2021-02-09 01:10:03 +0000, 15342 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4783)~~
* [Patch v2 (condvar_cs_v2.patch, text/plain, 2021-02-10 00:25:36 +0000, 14852 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4788)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2021-02-09 01:09:19 +0000, Cameron Gutman wrote:

> In Vista, Microsoft added both the SleepConditionVariableSRW API that SDL currently uses with the SRW-based mutex implementation and also the SleepConditionVariableCS API which works with CRITICAL_SECTION-based mutexes. We currently only support the former, and this patch adds support for the latter. 
> 
> I've also renamed the SDL_syscond_srw.c file and SDL_cond_srw struct now that they no longer require SRW locks.
> 
> As a side effect of implementing this support, SDL_HINT_WINDOWS_FORCE_MUTEX_CRITICAL_SECTIONS=1 no longer disables the use of the CONDITION_VARIABLE-based implementation. I can't really see a reason why someone would want to turn off the faster condition variable implementation, but I can add a hint for it if you think that's important.

On 2021-02-09 01:10:03 +0000, Cameron Gutman wrote:

> Created attachment 4783
> Patch

On 2021-02-09 13:16:00 +0000, Ozkan Sezer wrote:

> This will hit -Werror=declaration-after-statement

On 2021-02-09 23:27:34 +0000, Joel Linn wrote:

> With this we have three implementations for condvars... I deliberately ignored the Vista case because of that. Adding another hint would further increase the possible combinations. Thoughts about this from a maintainer?
> 
> Will review the diff itself later

On 2021-02-10 00:25:36 +0000, Cameron Gutman wrote:

> Created attachment 4788
> Patch v2
> 
> @Ozkan: Thanks for catching that. Fixed it in v2.
> 
> @Joel: We still only have 2 implementations of CVs. The only function that needed to change was SDL_CondWaitTimeout() and it was just the addition of a few lines (since the CS implementation is actually a bit simpler than the SRW implementation due to the lack of any internal SDL lock state). We're just calling SleepConditionVariableCS() instead of SleepConditionVariableSRW() if we're using CS-based mutexes.
> 
> The majority of the diff is that SDL_syscond_srw -> SDL_syscond_cv name change.

**Comment by JoelLinn** [comment]
Vista marketshare is at about 0,1%, (although thats higher than I expected) it is even below XP by at least a factor of two.
We already do jump tables for srw vs. fallback impl and are now discussing to add another level by branching within the current gen srw implementation. I don’t have a Vista install for a decade and therefore can’t reliably test this code :/

I appreciate the contribution as such but I still think in this case I worry about feature creep and added complexity (in code where subtle bugs can cause major headache down the road) just too much.

**Comment by slouken** [comment]
Reviewing this, I think this is reasonable and safe to add.

**Comment by icculus** [comment]
> Reviewing this, I think this is reasonable and safe to add.

I think it's way too risky to change this for 2.0.16, but I won't object to it landing immediately after.

...but also, I just want to make sure I understand this: why are we favoring CRITICAL_SECTIONs over SRW locks? Aren't SRW locks supposed to be faster and more lightweight? It's there's a good reason, it's fine with me, though.

**Comment by cgutman** [comment]
It’s defaulting to SRW locks on Win7+ and CRITICAL_SECTIONs on Vista. That’s handled by the existing sysmutex code.

**Comment by icculus** [comment]
I'm going to bump this to 2.0.17 (so it goes into revision control right after 2.0.16 ships).

**Comment by slouken** [comment]
@cgutman, can you rebase this patch and apply it to current SDL?

**Comment by icculus** [comment]
Ok, I rebased this (it mostly applied cleanly already). Gonna merge the PR tomorrow if no one objects.

**Comment by icculus** [comment]
> Gonna merge the PR tomorrow if no one objects.

...or 24 tomorrows...

This is in revision control now.
