### ISSUE TITLE
SDL_string.c uses intptr_t, which may actually be undefined.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4053]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2021-02-09 13:57:14 +0000, vladius wrote:

> The module's code may use intptr_t, which may actually be undefined in case LIBC is not available.
> uintptr_t seems to be more assured. Maybe use that type instead?

**Comment by sezero** [comment]
Did you actually hit an issue, if you did, what toolchain? If not, let's close this, because commit e228d15261 may have already 'fixed' it.

**Comment by icculus** [comment]
Agree. If someone reports an actual failure to compile, we'll open a new bug.

**Comment by limepixl** [comment]
I'm trying to compile SDL2 as part of my project through CMake. 
Platform: Windows 10 x64
Compiler: Clang 11.0.0 compiling for x64, using the GNU CLI version of the compiler (not `clang-cl`)
`clang --version` output: 
```
clang version 11.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

Output from my CMake build log:
```
[build] ../thirdparty/SDL2/src/stdlib/SDL_string.c:284:13: error: use of undeclared identifier 'intptr_t'
[build]     while ((intptr_t)dstp1 & 0x3) {
[build]             ^
[build] ../thirdparty/SDL2/src/stdlib/SDL_string.c:332:11: error: use of undeclared identifier 'intptr_t'
[build]     if (((intptr_t)src & 0x3) || ((intptr_t)dst & 0x3)) {
[build]           ^
[build] ../thirdparty/SDL2/src/stdlib/SDL_string.c:332:36: error: use of undeclared identifier 'intptr_t'
[build]     if (((intptr_t)src & 0x3) || ((intptr_t)dst & 0x3)) {
```

This isn't an issue with MSVC.
