### ISSUE TITLE
Clang detection in CMake build is incorrect

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4054]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[Robust Clang and libc detection. (sdl-clang-libc-detection.patch, text/plain, 2021-02-10 09:00:30 +0000, 6089 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4789)~~
* [NEW Robust Clang and libc detection. (SDL_14878.patch, text/plain, 2021-02-10 13:14:13 +0000, 1116 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4791)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2021-02-09 14:41:49 +0000, vladius wrote:

> The detection mechanism uses CMAKE_COMPILER_IS_GNUCC first, but that actually hides the Clang detection that way, cause Clang is also GNU-compliant.
> 
> I would suggest swapping the two clauses like so:
> 
> # Compiler info
> >if(CMAKE_C_COMPILER_ID MATCHES "Clang")
> >  set(USE_CLANG TRUE)
> >  set(OPT_DEF_ASM TRUE)
> >elseif(CMAKE_COMPILER_IS_GNUCC)
> >  set(USE_GCC TRUE)
> >  set(OPT_DEF_ASM TRUE)
> 
> That would allow for a proper default LIBC value detection via:
> >if(UNIX OR MINGW OR MSYS OR USE_CLANG)
> >  set(OPT_DEF_LIBC ON)
> >endif()
> 
> This doesn't uses the OR USE_CLANG now currently, and misses that available Clang's libc that way. This second code snippet must also be moved down, right after USE_CLANG detection to be able to work correctly.
> 
> Thank you.

On 2021-02-09 23:05:35 +0000, Sam Lantinga wrote:

> Can you attach a tested patch that implements this change?
> 
> Thanks!

On 2021-02-10 09:00:30 +0000, vladius wrote:

> Created attachment 4789
> Robust Clang and libc detection.
> 
> I'm now successfully detecting the presence of the libc under Clang with the following changes:

On 2021-02-10 09:01:11 +0000, vladius wrote:

> Added a patch.

On 2021-02-10 12:03:50 +0000, Ozkan Sezer wrote:

> (In reply to vladius from comment # 2)
> > Created attachment 4789 [details]
> > Robust Clang and libc detection.
> > 
> > I'm now successfully detecting the presence of the libc under Clang with the
> > following changes:
> 
> This patch touches things it is not supposed to,  e.g.: all
> changes after about line 400.

On 2021-02-10 13:11:47 +0000, vladius wrote:

> (In reply to Ozkan Sezer from comment # 4)
> > (In reply to vladius from comment # 2)
> > > Created attachment 4789 [details]
> > > Robust Clang and libc detection.
> > > 
> > > I'm now successfully detecting the presence of the libc under Clang with the
> > > following changes:
> > 
> > This patch touches things it is not supposed to,  e.g.: all
> > changes after about line 400.
> 
> You're right. Seems like I've done something wrong. Not quite used to Mercurial as of now.
> Attaching the correct patch now.

On 2021-02-10 13:14:13 +0000, vladius wrote:

> Created attachment 4791
> NEW Robust Clang and libc detection.
> 
> Together with a patch from this issue https://bugzilla.libsdl.org/show_bug.cgi?id=5539
> Clang now should compile correctly on Windows via CMake.

**Comment by vladipus** [comment]
Ditch the patches. Fixed by: https://github.com/libsdl-org/SDL/pull/4062

**Comment by sezero** [comment]
Fixed as of commit 05cc9e37649a
