### ISSUE TITLE
Weird color tinting in Wayland

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4056]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [reproduction code (test.c, text/x-csrc, 2021-02-10 00:00:47 +0000, 1289 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4785)
* [expected result (x11) (x11_grays.png, image/png, 2021-02-10 00:01:29 +0000, 2763 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4786)
* [actual result (wayland) (wayland_grays.png, image/png, 2021-02-10 00:01:51 +0000, 2864 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4787)

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2021-02-10 00:00:47 +0000, gabriel.holodak@gmail.com wrote:

> Created attachment 4785
> reproduction code
> 
> When trying to render some grayscale values, I noticed this weird tinting/banding effect. The problem disappears when using XWayland/the "x11" video driver. Results are exactly the same with the software renderer.
> 
> Additional info:
> I'm using Arch Linux with the Sway WM. GPU is a Radeon RX 5700 XT.

On 2021-02-10 00:01:29 +0000, gabriel.holodak@gmail.com wrote:

> Created attachment 4786
> expected result (x11)

On 2021-02-10 00:01:51 +0000, gabriel.holodak@gmail.com wrote:

> Created attachment 4787
> actual result (wayland)

**Comment by icculus** [comment]
I wonder if one is using the GL render and the other the GLES renderer.

**Comment by icculus** [comment]
Yeah, this is the same bug as we're seeing in Life is Strange, in #4132. Fix incoming.
