### ISSUE TITLE
PATCH: OpenGL is not included in the proper tests when using CMake

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4057]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Provide OpenGL for CMake tests (opengl-for-cmake-tests.patch, text/plain, 2021-02-10 15:46:39 +0000, 2077 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4792)
* [Hexadecimal unifont variant to be used in tests. (sdl-unifont-for-tests.patch, text/plain, 2021-02-10 15:53:12 +0000, 3837810 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4793)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2021-02-10 15:46:39 +0000, vladius wrote:

> Created attachment 4792
> Provide OpenGL for CMake tests
> 
> I'm including a patch to provide a portable and conditional OpenGL inclusion intro proper tests. Tested.

On 2021-02-10 15:53:12 +0000, vladius wrote:

> Created attachment 4793
> Hexadecimal unifont variant to be used in tests.
> 
> Even with the unifont functionality built in the testtime.c, the file is still missing from the repository and is not loaded correctly.
> This patch is adding this file. The new CMakeLists.txt should already be updated with the previous patch in this issue, to copy the font to the destination build directory correctly.

**Comment by vladipus** [comment]
Ditch the patches. Fixed by: https://github.com/libsdl-org/SDL/pull/4062

**Comment by sezero** [comment]
Fixed as of commit a52d0db5328
