### ISSUE TITLE
PATCH: Fixed testwm2.c test

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4058]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Additional conditional to clear the render target (sdl-testwm2-closing-fixed.patch, text/plain, 2021-02-10 17:58:13 +0000, 872 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4795)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2021-02-10 17:58:13 +0000, vladius wrote:

> Created attachment 4795
> Additional conditional to clear the render target
> 
> A small fix with a patch attached. Additional conditional is needed to clear the render target must be implemented, cause the renderers are destroyed in default's test event handler. Assertion may be raised otherwise.

**Comment by slouken** [comment]
This patch has been added:
https://github.com/libsdl-org/SDL/commit/31e8a4627a2d798bbe8724dd29e45a8b5daa0fa4

Thanks!
