### ISSUE TITLE
SDL_GetRevisionNumber no longer makes sense

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4063]
Mercurial tracks commits as both SHA-1 hashes and a single incrementing integer, but Git only does hashes.

This means that SDL_GetRevisionNumber() is meaningless moving forward (and, since that number could change arbitrarily depending on one's local clone of Mercurial and what branches are being committed to, was always a dicey proposition).

Let's change this to always return 0 (the default, meaning "unknown", depending on how you built SDL) and change the docs to say "don't call this function anymore" ... and remove it outright in 2.1.

**Comment by sezero** [comment]
Sounds good to me.
