### ISSUE TITLE
Clean out references to wiki.libsdl.org...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4064]
There are some references to wiki.libsdl.org in the SDL source code, clean these out and point them to https://github.com/libsdl-org/SDL/wiki instead.

**Comment by erikyuzwa** [comment]
I haven't contributed anything yet - can I take this one off your hands @icculus ?

**Comment by icculus** [comment]
@erikyuzwa Please do!

**Comment by erikyuzwa** [comment]
addressed in PR - https://github.com/libsdl-org/SDL/pull/4069

**Comment by icculus** [comment]
Thank you!

**Comment by erikyuzwa** [comment]
no worries - it's tech - it happens. 🤷 - good luck and I'd be happy to help update anything if you need an extra hand here.
