### ISSUE TITLE
SDL_JoystickRumble not working on SDL 2.0.14

### ISSUE THREAD

**Issue by Boomslangnz** [libsdl-org/SDL#4072]
Hi

Im finding i cannot get SDL_JoystickRumble to work anymore at all on SDL 2.0.14, it returns 0 to me as if its successful still but no rumble occurs across multiple devices. Testing SDL 2.0.12 and SDL 2.0.9 has worked fine and rumbles fine

**Comment by slouken** [comment]
What devices and OS are you using?

**Comment by Boomslangnz** [comment]
Windows 10 latest update and using xbox one controller and logitech f710 for tests. Also tested with sdl_controllerrumble last night and same issue

Haptic itself still works fine on my wheel etc

**Comment by Boomslangnz** [comment]
Hi

Ive gone back through commits to work out when it stopped working for me and it's this

https://github.com/libsdl-org/SDL/commit/ce77966da85aeb68a1015c5eb5319ceea60350af

commit before this still gives SDL_JoystickRumble to my xbox one controller but I get 2 x Xbox One Controllers showing one called Controller (Xbox One For Windows) which still performs no rumble at all and another called Xbox One Game Controller which performs rumble effects fine. On latest SDL2 updates i only get 1 x device showing and it is the one called Controller (Xbox One For Windows) and no SDL_JoystickRumble effect occurs

**Comment by Boomslangnz** [comment]
Found my issue 

I had to set 

SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0"); 

before SDL_Init and now i get SDL_JoystickRumble across both controllers fine but names are just Xinput #1 and Xinput #2

**Comment by endrift** [comment]
I've been observing this too. Your approach sounds like a workaround, and there's an actual bug present. If I roll back to 2.0.12 it goes back to working fine, but some users are complaining about issues with Switch Pro Controllers afterwards (see https://github.com/mgba-emu/mgba/issues/2162)
