### ISSUE TITLE
SDL_min() and SDL_max() are macros with double-evaluation

### ISSUE THREAD

**Issue by InfoTeddy** [libsdl-org/SDL#4080]
Currently, `SDL_stdinc.h` defines `SDL_min()` and `SDL_max()` as macros that have an issue of double-evaluation.

These work on every single type, and are fine if your arguments are idempotent; if not, then you have to work around the issue by either (1) assigning them to a temporary variable at the callsite, (2) using another library (most likely libc) that provides these as proper functions instead of macros, or (3) rolling your own functions.

In the header, there is a comment above them, which says:

```c
/* !!! FIXME: these have side effects. You probably shouldn't use them. */
/* !!! FIXME: Maybe we do forceinline functions of SDL_mini, SDL_minf, etc? */
```

`SDL_mini` and `SDL_minf` don't seem to exist anywhere, so it seems like this comment laid down plans to create those functions, which haven't gone through.

My question is: what should we do about this situation? Should we implement `SDL_min()` and `SDL_max()` as proper functions (taking ints and returning int), or should we create new functions as the comment suggested?

**Comment by Xeverous** [comment]
I don't think you can actually write type-agnostic functions in C without extensions. C and C++ programmers are already aware that many macros may evaluate things multiple times, so `MACRO(++x)` is bad code, whether macro evaluates multiple times or not.

**Comment by InfoTeddy** [comment]
Yes, you cannot.<sup>[note 1]</sup> The next best thing, and imo which I think should be done, is to make `SDL_mini`/`SDL_minf` functions, as suggested in the comment.

<sup>[note 1]</sup>: C11 has `_Generic`, but nobody uses C11. Or at least SDL doesn't. It's also basically just a C++ template, but you're the one who generates the code for each type instead of the compiler.

**Comment by slouken** [comment]
The best implementation I've found is something like this, but it only works for GCC/clang:
```
#define SDL_min_unsafe(x, y) (((x) < (y)) ? (x) : (y))
#define SDL_max_unsafe(x, y) (((x) > (y)) ? (x) : (y))
#ifdef __cplusplus
template<typename T>
const T& SDL_min(const T &x, const T &y)
{
    return !(y < x) ? x : y;
}
template<typename T>
const T& SDL_max(const T &x, const T &y)
{
    return !(y > x) ? x : y;
}
#else
#define SDL_min(x, y)        \
({                           \
    __typeof__ (x) _x = (x); \
    __typeof__ (y) _y = (y); \
    _x < _y ? _x : _y;       \
})
#define SDL_max(x, y)        \
({                           \
    __typeof__ (x) _x = (x); \
    __typeof__ (y) _y = (y); \
    _x < _y ? _x : _y;       \
})
#endif
```

Given that, we'll go ahead and leave it as-is. I'll update the comments in the headers.

**Comment by slouken** [comment]
Closing with https://github.com/libsdl-org/SDL/commit/d5ad6f6e6abf7845e3a99bde5d7fb0a9a599e559

**Comment by InfoTeddy** [comment]
I was wondering if adding dedicated functions for types like `SDL_mini`, `SDL_maxi`, `SDL_minf`, `SDL_maxf`, etc. would be acceptable. That's kind of half the reason I opened this issue in the first place.

**Comment by slouken** [comment]
I considered it, but we use the macro with int, unsigned int, size_t, 64-bit types, etc. Adding the whole matrix of available types is really unwieldy. I'd rather just recommend that developers use good practices when calling these macros.
