### ISSUE TITLE
Do we need a VisualC.html ?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4081]
Does this file need to exist in the root directory, or can we move it to a (not HTML) file in docs?

**Comment by erikyuzwa** [comment]
not to be ultra-greedy here @icculus - I can take this one. I can move it either to a wiki entry or a file in docs..

**Comment by Dasein12** [comment]
i think it will issue an internal server error

**Comment by icculus** [comment]
> not to be ultra-greedy here

Be greedy, fix anything you like!  lol

**Comment by erikyuzwa** [comment]
Not sure if it's outside the scope of this repository, but after the hell I went through trying to get a working SDL2 project up and running in `CMake` within `CLion`, a wiki page might be in good order. I'll dig up my notes.

**LOTS** of outdated blog posts on this, which you won't even realize until it's too late.

**Comment by erikyuzwa** [comment]
(and maybe `vcpkg`)

**Comment by beezyb2** [comment]
Open

**Comment by slouken** [comment]
This was fixed by https://github.com/libsdl-org/SDL/commit/9c1871c14488fd324ff3285f6fb281e22beb8aa8
