### ISSUE TITLE
Instructions on how to use KMSDRM on *BSDs is not available

### ISSUE THREAD

**Issue by Cacodemon345** [libsdl-org/SDL#4086]
There isn't any readme file that explains how to use the KMSDRM video backend on the BSDs yet.

Such documentation should be added.

**Comment by Visith168** [comment]
Hi dear

**Comment by Cacodemon345** [comment]
Dealing with spams is going to be hard...

**Comment by icculus** [comment]
> Dealing with spams is going to be hard...

There's a button next to the comment that lets me block them from all SDL projects for spamming, which I have just pushed.  :)
