### ISSUE TITLE
CMake build on Haiku results a faulty build

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#4092]
Hello!

Just now I reminded of the old bug of SDL2' CMake build that produces an unstable result: it lacks sound and may glitch during the workflow. However, installing the SDL2 via Haiku Depot (No idea is that a slightly tuned fork or it was just built via Autotools way, I should verify this case on my end to confirm will the Autotools-built SDL2 work properly on Haiku or don't).

**Comment by icculus** [comment]
Having not explored this at all, I would assume this is a fault of our CMake script (the autotools way, to my knowledge, works on Haiku).

**Comment by kenmays** [comment]
Please use the patchser located here: https://raw.githubusercontent.com/haikuports/haikuports/master/media-libs/libsdl2/libsdl2-2.0.14.recipe

**Comment by icculus** [comment]
> Please use the patchset located here:

I believe all of this has been upstreamed into SDL's repository, fwiw.

**Comment by icculus** [comment]
I've applied the HaikuPorts CMake patches that @kenmays mentioned, which I believe resolves this issue. If it's still broken for you, please reopen this bug!

(everything else in that patchset has already been committed to SDL's revision control, except the Makefile.in patch, which has a long history of being rejected here for changing the C compiler command line to C++; if we can ever find a portable resolution to that, we can finally be done with external patches for Haiku.  :)  )

**Comment by icculus** [comment]
> (everything else in that patchset has already been committed to SDL's revision control, except the Makefile.in patch, which has a long history of being rejected here for changing the C compiler command line to C++; if we can ever find a portable resolution to that, we can finally be done with external patches for Haiku. :) )

Opened an issue about it here, fwiw: https://github.com/haikuports/haikuports/issues/6095

**Comment by jessicah** [comment]
this should suffice: https://gist.github.com/jessicah/5ee4aaefcc4c28adf7be3a6238be6497
