### ISSUE TITLE
'UpdateTextureYUV': is not a member of 'SDL_Renderer' when using SDL_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4093]
When using VC++2019 and the SDL_LEAN_AND_MEAN pre-def I get a compile error in SDL_render_d3d.c(1713,15).

p.s. I miss Bugzilla :-(

**Comment by sezero** [comment]
> When using VC++2019 and the SDL_LEAN_AND_MEAN pre-def I get a compile error in SDL_render_d3d.c(1713,15).

Should be fixed by https://github.com/libsdl-org/SDL/commit/f2a2d0c696bf7a752df3ef3c5f1d8a12d196c8a6

> p.s. I miss Bugzilla :-(

Me too, I _really_ do.
