### ISSUE TITLE
GitHub isn’t recognizing SDL’s license

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4096]
The main SDL page on GitHub lists the license as "other" even though it correctly identifies the file containing the license.

It _does_ correctly list SDL-1.2 as LGPL-2.1, but SDL2 is not listed as zlib.

GitHub uses a Ruby gem named Licensee to determine licenses. This library appears to recognize zlib.

I guess we should find another zlib-licensed project on GitHub and figure out what it does differently?

**Comment by erikyuzwa** [comment]
I can take this @icculus :)

**Comment by Lokathor** [comment]
Well i have almost all my projects under Zlib (as well as other license options)

<https://github.com/Lokathor/utf16_lit>

So I'm putting the license in `LICENSE-ZLIB.md`, and as you can see GitHub seems to pick that up and show the correct thing in the "about" sidebar.

**Comment by flibitijibibo** [comment]
We actually have the same issue for our libraries... is this something we can ping GitHub about? Both this repo's COPYING.txt and our [LICENSE](https://github.com/FNA-XNA/FAudio/blob/master/LICENSE) files don't seem _too_ crazy, right?

**Comment by Lokathor** [comment]
@flibitijibibo i don't know for sure but try taking off the comments markers from your LICENSE file. Heuristic checking stuff is usually pretty easy to confuse.

**Comment by erikyuzwa** [comment]
Okay reproduced "A Way" here in my forked repo @icculus  - https://github.com/erikyuzwa/SDL/tree/main

- removed the `COPYING.txt` file from the root
- added a `LICENSE` file of the Apache 2.0 license, retaining the original copyright years and Sam's email at the bottom of it
- (not assuming the project take this particular license of course, merely testing how to make it register properly in Github)
- 
![Capture](https://user-images.githubusercontent.com/962434/108098498-af86d880-7040-11eb-8096-8958350d2a50.PNG)

**Comment by icculus** [comment]
Renaming it from COPYING.txt to LICENSE.txt, and then from there to LICENSE broke it, too, over in my fork. This seems kinda delicate.

Gonna try again shortly and then try in the main repo if it works in a newly-created fork.

**Comment by erikyuzwa** [comment]
yeah I found that it wouldn't recognize properly until it was in `main` - a branch didn't seem to cut it.

**Comment by icculus** [comment]
Didn't work for me over at https://github.com/icculus/SDL  ... gonna wait a bit and see if there's some cronjob or whatever that only updates that thing once a day or whatever.

**Comment by erikyuzwa** [comment]
think I figured it out -- you need to have the copyright year and Sam's email as the first line in the file instead of the SDL line

**Comment by icculus** [comment]
It worked! Nice job.  :)

**Comment by erikyuzwa** [comment]
thanks!
