### ISSUE TITLE
Audio clipping with surround sound

### ISSUE THREAD

**Issue by crudelios** [libsdl-org/SDL#4104]
Hi,

Apparently SDL has a problem when converting mono/stereo audio to 5.1/7.1 (for example when the source audio is stereo but the output should be in surround). There seems to be a lot of gain which, in turn, can cause clipping.

This problem was first brought to my attention here: https://github.com/Keriew/augustus/issues/194

I am unsure but it may be related to these lines:

https://github.com/libsdl-org/SDL/blob/d79bc0015eaf8307bfe8ac0240944fa372625122/src/audio/SDL_audiocvt.c#L249

https://github.com/libsdl-org/SDL/blob/d79bc0015eaf8307bfe8ac0240944fa372625122/src/audio/SDL_audiocvt.c#L286

https://github.com/libsdl-org/SDL/blob/d79bc0015eaf8307bfe8ac0240944fa372625122/src/audio/SDL_audiocvt.c#L354

This has been tested with 2.0.14 in Windows.

Thanks!

**Comment by icculus** [comment]
@1bsyl Is this resolved with f8695185331460106f34286ebe466cb605f85bb6 and 21349901ea250483600cbe4771d865cc06f6b538, or did it need more tweaking? I saw there was a multiplication by 0.571f discussed on https://github.com/Keriew/augustus/issues/194, but wasn't sure if that was decided to be better or not.

**Comment by 1bsyl** [comment]
hey @icculus 
https://github.com/libsdl-org/SDL/commit/f8695185331460106f34286ebe466cb605f85bb6 removes the saturation
https://github.com/libsdl-org/SDL/commit/21349901ea250483600cbe4771d865cc06f6b538 fixes a typo

But it seems, from users, that there is still a too high gain
A fix is proposed here: https://github.com/Keriew/augustus/issues/194#issuecomment-847655049
(multiplication by "0.571f" but also using "0.5f * ce" to reduce the gain)
Still waiting for a feedback ...

Maybe important, there is a suspicion for some audio under-run with wasapi audio (but not with directsound)
https://github.com/Keriew/augustus/issues/436
https://github.com/Keriew/augustus/issues/436#issuecomment-868565571
https://github.com/Keriew/augustus/issues/194#issuecomment-847331005

**Comment by icculus** [comment]
I'm going to go with this for now, as it seems like an improvement, even if we end up tweaking it further later. And bump this to the 2.0.18 milestone, when we have had some feedback. If the feedback is good, we can close this issue without further action.

**Comment by 0x1F9F1** [comment]
I can't say if the current version is "correct", but if you expand/simplify the equations used (which should also be applied to the actual code) it becomes clearer what the issues are/were:
```cpp
// Too loud
// https://github.com/libsdl-org/SDL/commit/38854e03332d2298eefccd21c917de4220669bbf
// https://www.wolframalpha.com/input/?i=a+%2B+%28a+-+%28%28a+%2B+b%29+*+0.5%29%29
dst[0] = (lf * 1.5f) - (rf * 0.5f);

// Too quiet
// https://github.com/libsdl-org/SDL/commit/f8695185331460106f34286ebe466cb605f85bb6
// https://www.wolframalpha.com/input/?i=0.5+*+%28a+%2B+%28a+-+%28%28a+%2B+b%29+*+0.5%29%29%29
dst[0] = (lf * 0.75f) - (rf * 0.25f);

// Just right?
// https://github.com/libsdl-org/SDL/commit/659e1f0a3f6a29aea2a220203643f6b44eaf65e9
// https://www.wolframalpha.com/input/?i=%284%2F7%29+*+%28a+%2B+%28a+-+0.5+*+%28%28a+%2B+b%29+*+0.5%29%29%29 (assume 0.571 == 4/7)
dst[0] = lf - (rf * 0.14285f); // (1/7)
```

**Comment by icculus** [comment]
I think this is good to close on our end now. @1bsyl, please reopen if you think this needs more work!
