### ISSUE TITLE
License filename change broke things...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4108]
Sam pointed out that https://github.com/libsdl-org/SDL/commit/ffce58a30c2b3214b5ea5a249122226c589bfa58 breaks a bunch of stuff, so I'm grepping for the old filename to see what references it (makefiles, etc).

Assigning to myself, shouldn't take long.

**Comment by icculus** [comment]
Looks like the Makefile was smart enough to do this:

```sh
SRC_DIST = *.txt
```
...so COPYING.txt -> LICENSE.txt didn't blow up in the most crucial part. I suspect this would blow up a lot more in the 1.2 branch, but GitHub already correctly identifies the file as LGPL 2.1 there, so we don't have to change anything.

If/when we do this for the satellite libraries, we should be more careful, though.

Cleaned out the rest of the wrong filenames.

**Comment by sezero** [comment]
Off-topic:  25 out of 27 files touched by the fixing commit is visualtest:
is it actually used or maintained?  I know that it's not packaged in the
releases..

**Comment by icculus** [comment]
> is it actually used or maintained?

I actually don't know; it was originally a Google Summer of Code project, and I don't think anyone has looked at it, or tried it, in a long time. @slouken, do you know if this thing is still useful?
