### ISSUE TITLE
sdl2 bug in VGA sis in linux

### ISSUE THREAD

**Issue by ArionDeno** [libsdl-org/SDL#4124]
bug sdl2 and sdl1.2 in VGA sis  Linux. I would like to inform you that there is a bug in both version 2.14. and sdl1.2.15 in Linux environment use VGA sis, I tested it with Debian 11 and kernel 5.10., I tried sdl_surface and sdl_renderer.at start game, the monitor turns off, then after 2 seconds it returns to display the graphical mode and every 10 seconds it turns off the screen and returns to the graphical mode. before reporting, I tested it with Allegro 4, and it works normally, I believe it is a sdl bug

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
