### ISSUE TITLE
Not building on Windows since 2c3269152a9b363b0b67c035f79a745b2791b2dc

### ISSUE THREAD

**Issue by JibbSmart** [libsdl-org/SDL#4125]
I've been unable to build SDL2 for Windows (both Win32 and x64) in Visual Studio since commit 2c3269152a9b363b0b67c035f79a745b2791b2dc by @RyuzakiKK .

This is very much out of my wheelhouse, so I'm unable to offer a proposed solution. But here's the error I get in Visual Studio:

> LNK2019 unresolved external symbol close referennced in function HIDAPI_JoystickQuit - SDL_hiapijoystick.obj
> LNK1120 1 unresolved externals - SDL2.dll

Prior to that commit, I have no problems building in Visual Studio.

**Comment by slouken** [comment]
It looks like this is fixed in https://github.com/libsdl-org/SDL/commit/7a2b6f331b2744315865370c4e611bc631cceaca
