### ISSUE TITLE
windows opengl es2 issue

### ISSUE THREAD

**Issue by amurat** [libsdl-org/SDL#4129]
assertion failure when creating window with
opengl es2 context on windows platform. 
think i've narrowed down the bug to the following commit https://github.com/libsdl-org/SDL/commit/8babda2c206949ad9c4f42e64bf8ae3e35b2e709

**Comment by arkiruthis** [comment]
Thank you for reporting this, I've also encountered this issue whilst trying to use ANGLE with SDL2. 

I only got the assert error when I moved from my own SDL2 (2.0.12 from the site) to the SDL2 (2.0.14) that's packaged with vcpkg, so I think you're right about the associated commit.

**Comment by icculus** [comment]
Going to close this issue and further discussion can happen at #4177.
