### ISSUE TITLE
CMake script is broken on FreeBSD

### ISSUE THREAD

**Issue by Cacodemon345** [libsdl-org/SDL#4133]
The CMake script is currently unusable on FreeBSD; it currently shows an syntax error likely related to the `sdlchecks.cmake` POSIX thread flag tests.

**Comment by sezero** [comment]
What is the error message from current git?  Do you have a patch?

**Comment by Cacodemon345** [comment]
I don't have a patch yet.

**Comment by Cacodemon345** [comment]
@sezero This is the error message I always get:
```CMake Error: Parse error in command line argument: -D_THREAD_SAFE
Should be: VAR:type=value```The call trace is inconsistent when this error message appears.

**Comment by sezero** [comment]
I don't see how that's happening. I'm not running on FreeBSD,
but I copied line 876 from freebsd case to Linux case at line 865,
I see no errors at all with my cmake-3.9.6

**Comment by Cacodemon345** [comment]
You could try reproducing this bug on a FreeBSD VM.

**Comment by sezero** [comment]
> You could try reproducing this bug on a FreeBSD VM.

Sorry, I won't do that.

**Comment by Cacodemon345** [comment]
This looks like I am going to be completely on my own about getting this fixed since nobody else seems to be willing to fix it.

**Comment by Cacodemon345** [comment]
Passing `-DSDL_VIDEO=0` to CMake allows the script to work on FreeBSD.
