### ISSUE TITLE
dwm vs SDL_WINDOW_FULLSCREEN_DESKTOP

### ISSUE THREAD

**Issue by cmF3** [libsdl-org/SDL#4136]
When using SDL_WINDOW_FULLSCREEN_DESKTOP an app linked against **SDL2 2.0.14** fails to render. It looks like the Render Process/Thread hangs but the rest of the app continues to run. I can reproduce the issue with the minimal code snippet below.  Note that by replacing SDL_WINDOW_FULLSCREEN_DESKTOP with SDL_WINDOW_FULLSCREEN the app renders correctly.

Compiled with
`
cc -ansi -Wall -pedantic -Werror -Wshadow -Wstrict-aliasing -Wstrict-overflow -O2 -o main main.c -I/usr/include/SDL2 -D_REENTRANT -pthread -lSDL2
`

```c
#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
        SDL_Window * win;
        int fs;

        if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
                fprintf(stderr, "SDL_Init Error: %s\n", SDL_GetError());
                return EXIT_FAILURE;
        }

        win = SDL_CreateWindow("Hello World!", 0, 0, 640, 480, SDL_WINDOW_SHOWN);
        if (win == NULL) {
                fprintf(stderr, "SDL_CreateWindow Error: %s\n", SDL_GetError());
                return EXIT_FAILURE;
        }

        fs = SDL_SetWindowFullscreen(win, SDL_WINDOW_FULLSCREEN_DESKTOP);
        if(fs < 0) {
                fprintf(stderr, "SDL_SetWindowFullscreen Error: %s\n", SDL_GetError());
                return EXIT_FAILURE;
        }
        sleep(5);
        SDL_DestroyWindow(win);
        SDL_Quit();

        return EXIT_SUCCESS;
}
```

**Comment by cgutman** [comment]
I'm guessing this is probably Linux or some UNIX-based OS based on your compiler invocation (please confirm). Are you using X11, Wayland, or KMSDRM for rendering? More information about your distro and desktop environment would be helpful too.

I've shipped binaries that use SDL_WINDOW_FULLSCREEN_DESKTOP with SDL 2.0.14 on Linux and render fine, so there must be more to it than that.

Can you run your sample under `gdb` and break in when the hang occurs to capture a backtrace?

**Comment by cmF3** [comment]
Yes, I confirm I am running Linux 5.11.1 and Xorg 1.20.10 using amdgpu 19.1.0. 

I have investigated further and it looks like this may be a problem with dwm fullscreen mode.

**Comment by Introscopia** [comment]
Also experiencing something similar on windows, with 2.0.16.
if I run SDL_SetWindowFullscreen( window, SDL_WINDOW_FULLSCREEN_DESKTOP ); before the program starts rendering to the screen, it works fine. But when I try to switch to or from fullscreen during execution the contents of the program disappear, window is suddenly empty. I've also had it one time where only some elements disappeared, others remained.
I'm compiling with MinGW on the command line.. Don't know what more information I could supply that would be useful

**Comment by icculus** [comment]
So after some more poking, it looks like dwm over here is fullscreening a window correctly, but then sends window resize events to tell the app it's at an incorrect size, which is fine if you haven't created a renderer yet but sort of disastrous if you have.

Which, I'm pretty certain, is 100% unrelated to what the original bug report is about, which was _also_ a dwm bug, which is to say I am reaffirmed in my belief that niche window managers are a giant drain on developer resources across the board.
