### ISSUE TITLE
GitHub code search seems broken on this repo

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#4138]
The code search functionality on this repo seems to not be working. I'm not sure if it has something to do with the Mercurial migration, if GitHub just takes time to index, or something else.

Take a simple query like a search for SDL_CreateWindow (which is used all over the place).
- Running the [query against spurious/SDL-mirror](https://github.com/spurious/SDL-mirror/search?q=SDL_CreateWindow) yields 45 results
- Running the [same query against libsdl-org/SDL](https://github.com/libsdl-org/SDL/search?q=SDL_CreateWindow) yields no results.

Strangely, the search does seem to be able to search commits, issues, and wiki pages, just not the code itself. Quite strange...

**Comment by sezero** [comment]
Mercurial migration broke the history too - I'm using a local clone of https://github.com/Didstopia/SDL.git for that purpose.

**Comment by icculus** [comment]
I'll open a ticket with GitHub.

**Comment by icculus** [comment]
Ticket filed. If they reply, I'll let you know, otherwise, I guess we'll just recheck to see if search starts working?

Obviously the SDL repo history is thornier, but it looks like search is working on other repos; I just tried SDL_mixer and it is functioning.

**Comment by icculus** [comment]
GitHub wrote back to report they have resolved the bug on their end! And indeed, it appears to work now.

Closing this bug. Thanks for alerting me to the problem!
