### ISSUE TITLE
Namespace CMake options

### ISSUE THREAD

**Issue by jonesmz** [libsdl-org/SDL#4139]
E.g. VIDEO_KMSDRM should be SDL_VIDEO_KMSDRM, and KMSDRM_SHARED should be SDL_VIDEO_KMSDRM_SHARED

The way things are now, it's very difficult to determine which options are from SDL and which options are from other projects in the same cmake build.

**Comment by icculus** [comment]
I agree, but changing this is going to be non-trivial, so we might bump this to 2.0.18.
