### ISSUE TITLE
Could not find load file SDL2Targets.cmake

### ISSUE THREAD

**Issue by ElJaviLuki** [libsdl-org/SDL#4141]
Trying to install SDL in my project is being a frustrating pain:
Given the third-party bundled libraries folder:
```
externals
├───cpp-httplib
│   ···
├───rapidjson
│   ···
├───SDL
│   ···
└───CMakeLists.txt
```

This is `externals/CMakeLists.txt`:
``` cmake
## Definitions for all external libraries

# cpp-httplib
# NOTE: Replaceable with 'add_subdirectory'?
	add_library(cpp-httplib INTERFACE)
	target_include_directories(cpp-httplib INTERFACE cpp-httplib)

# rapidjson
# NOTE: Replaceable with 'add_subdirectory'?
	add_library(rapidjson INTERFACE)
	target_include_directories(rapidjson INTERFACE rapidjson/include)

# Painful SDL
	set(SDL2_DIR SDL)
	find_package(SDL2 REQUIRED)

#	add_library(SDL INTERFACE)
#	target_include_directories(SDL PUBLIC ${SDL2_INCLUDE_DIRS})
#	target_link_libraries(SDL PUBLIC ${SDL2_LIBRARIES})
```

But VS2019 throws a CMake Error:
```
CMake Error at externals/SDL/SDL2Config.cmake:1 (include):
  include could not find load file:

    C:/dev/Pasapalabra/externals/SDL/SDL2Targets.cmake
```

**Comment by DanielGibson** [comment]
What did you put into that SDL/ directory?
Just copying SDL2Config.cmake is not enough.
You need to compile SDL2 with cmake and install it into that directory (=> when configuring SDL with cmake select it as CMAKE_INSTALL_PREFIX) for SDL2Config.cmake to work (because then CMake will  create an appropriate SDL2Targets.cmake, and also the libs to link against etc)

**Comment by madebr** [comment]
Reading [`find_package`'s documentation](https://cmake.org/cmake/help/latest/command/find_package.html), `<PackageName>_DIR` should contain the path containing the cmake script.
Instead, you're setting it to the root of the installed SDL project.
So I think you should set rthe `<PackageName>_ROOT` variable instead.

Also, that variable should contain a non-relative path.

Please try the following (modify as needed)
```cmake
	set(SDL2_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/SDL")
	find_package(SDL2 REQUIRED)
```
