### ISSUE TITLE
CMake: Should project-wide links/definitions be changed to target-specific ones?

### ISSUE THREAD

**Issue by saxbophone** [libsdl-org/SDL#4150]
In SDL's `CMakeLists.txt` file, there are a few cases where the following CMake directives are used:

- `link_libraries()`
- `add_definitions()`
- `include_directories()`

Each of these has a target-specific version e.g. `target_link_libraries()`, etc, all of which set their properties on a specific target, as opposed to the ones listed above, which set their properties on all targets defined after they're invoked in the file.

It seems fairly clear that SDL's using these _global_ versions because there are some compiler definitions, include directories and link targets needed library-wide, however CMake recommends using the target-specific versions of these wherever possible, according to its docs: https://cmake.org/cmake/help/latest/command/link_libraries.html

There is a way to do both of these things, using CMake's interface libraries: https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#interface-libraries

What this approach basically does is create a pseudo-target, whose only purpose is to collate "global" properties like compiler definitions, include directories, etc, and propagates these properties to all targets that link against it, so linking against it specifies those properties are to be inherited.

This would, I believe, achieve the same outcome as the current system, but in a much neater way.

The one gotcha with this approach is that `PRIVATE` linkage must be made to the pseudo-target to avoid propagating the properties to dependents of SDL. Also, CMake isn't smart enough to work out when a usage requirements target like this doesn't need to be exported along with the library, so it has to be wrapped in a generator expression to avoid this:

```cmake
target_link_libraries(
    SDL2-static PRIVATE
    $<BUILD_INTERFACE:sdl-compiler-options>
)
```

I have successfully applied this approach to my own projects, and would be able to make these modifications myself, but I am interested to know what others think before I do any work on it.

**Comment by icculus** [comment]
Yeah, this is probably leftover from the initial CMake project work, around the dawn of time. I'll look at cleaning this up.

**Comment by saxbophone** [comment]
Glad to hear it's not just me being a pedant :)

**Comment by icculus** [comment]
I believe this is resolved now, using an interface library. Please reopen if I missed something or screwed this up real badly!

**Comment by saxbophone** [comment]
This looks great, thanks! Initial test working fine on my machine. I'll have a go trying out a build with SDL as a subproject later and report back if any issues.
