### ISSUE TITLE
Commit 2f5beac breaks keycode SDL_DELETE

### ISSUE THREAD

**Issue by jm-mikkelsen** [libsdl-org/SDL#4152]
I just happened to see this commit notification go past:

https://github.com/libsdl-org/SDL/commit/2f5beac190dec5bbfb266d9a2fa46661304bbbbe

It incorrectly translates an octal constant of '\177' to '\x1f'. The correct translation is '\x7f'.

**Comment by sezero** [comment]
Fixed by commit a7938107ae, thanks.
