### ISSUE TITLE
SDL_SetTextInputRect BUG

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#4154]
SDL_DISABLE_WINDOWS_IME is invalid in the case of definition SDL_SetTextInputRect

I think videodata->ime_hwnd_current is not initialized
version: 2.0.14
Platform: Windows

Sorry, I can't speak English. This is from machine translation
```c
void
WIN_SetTextInputRect(_THIS, SDL_Rect *rect)
{
    SDL_VideoData *videodata = (SDL_VideoData *)_this->driverdata;
    HIMC himc = 0;

    if (!rect) {
        SDL_InvalidParamError("rect");
        return;
    }

    videodata->ime_rect = *rect;

    himc = ImmGetContext(videodata->ime_hwnd_current);
    if (himc)
    {
        COMPOSITIONFORM cf;
        cf.ptCurrentPos.x = videodata->ime_rect.x;
        cf.ptCurrentPos.y = videodata->ime_rect.y;
        cf.dwStyle = CFS_FORCE_POSITION;
        ImmSetCompositionWindow(himc, &cf);
        ImmReleaseContext(videodata->ime_hwnd_current, himc);
    }
}
```

**Comment by slouken** [comment]
ime_hwnd_current is initialized in WIN_StartTextInput() -> IME_Init() -> IME_SetWindow()

**Comment by baidwwy** [comment]
@slouken 
My program is two windows,
The first window is the loading window,
The second window is the game window.

I solved the problem with the following code
```cpp
HWND hwnd = ((SDL_WindowData*)window->driverdata)->hwnd;
himc = ImmGetContext(hwnd);
```

**Comment by slouken** [comment]
Can you attach your copy of SDL_windowskeyboard.c so I can see your changes?

**Comment by baidwwy** [comment]
```cpp
	if (SDL_Init(SDL_INIT_VIDEO) == -1) {
		SDL_Log("SDL_Init failed: %s\n", SDL_GetError());
		return 1;
	}

	SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1");
	const int winw = 800;
	const int winh = 600;
	SDL_Window* window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, winw, winh, 0);
	if (!window) {
		SDL_Log("SDL_CreateWindow failed: %s\n", SDL_GetError());
		SDL_Quit();
		return 1;
	}
	SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
	if (!renderer) {
		SDL_Log("SDL_CreateRenderer failed: %s\n", SDL_GetError());
		SDL_Quit();
		return 1;
	}
	SDL_Rect rect = { 0,0,0,0 };
	SDL_StartTextInput();
	SDL_SetTextInputRect(&rect);
	SDL_StopTextInput();

	SDL_Window* window1 = SDL_CreateWindow("Hello SDL1", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, winw, winh, 0);
	SDL_Renderer* renderer1 = SDL_CreateRenderer(window1, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
	if (!renderer) {
		SDL_Log("SDL_CreateRenderer failed: %s\n", SDL_GetError());
		SDL_Quit();
		return 1;
	}

	SDL_StartTextInput();
	SDL_SetTextInputRect(&rect);
	SDL_StopTextInput();

	SDL_DestroyWindow(window1);
	
	SDL_StartTextInput();
	SDL_SetTextInputRect(&rect);
	SDL_StopTextInput();
```

```cpp
void
WIN_SetTextInputRect(_THIS, SDL_Rect *rect)
{
    SDL_Window* window;
    SDL_VideoData *videodata = (SDL_VideoData *)_this->driverdata;
    HIMC himc = 0;

    if (!rect) {
        SDL_InvalidParamError("rect");
        return;
    }

    videodata->ime_rect = *rect;
   
    window = SDL_GetKeyboardFocus();
    HWND hwnd = ((SDL_WindowData*)window->driverdata)->hwnd;
    SDL_Log("ime_hwnd_current %p", videodata->ime_hwnd_current);
    SDL_Log("hwnd %p", hwnd);
    himc = ImmGetContext(hwnd);
    if (himc)
    {
        COMPOSITIONFORM cof;
        CANDIDATEFORM caf;

        cof.dwStyle = CFS_RECT;
        cof.ptCurrentPos.x = videodata->ime_rect.x;
        cof.ptCurrentPos.y = videodata->ime_rect.y;
        cof.rcArea.left = videodata->ime_rect.x;
        cof.rcArea.right = videodata->ime_rect.x + videodata->ime_rect.w;
        cof.rcArea.top = videodata->ime_rect.y;
        cof.rcArea.bottom = videodata->ime_rect.y + videodata->ime_rect.h;
        ImmSetCompositionWindow(himc, &cof);

        caf.dwIndex = 0;
        caf.dwStyle = CFS_EXCLUDE;
        caf.ptCurrentPos.x = videodata->ime_rect.x;
        caf.ptCurrentPos.y = videodata->ime_rect.y;
        caf.rcArea.left = videodata->ime_rect.x;
        caf.rcArea.right = videodata->ime_rect.x + videodata->ime_rect.w;
        caf.rcArea.top = videodata->ime_rect.y;
        caf.rcArea.bottom = videodata->ime_rect.y + videodata->ime_rect.h;
        ImmSetCandidateWindow(himc, &caf);

        ImmReleaseContext(hwnd, himc);
    }
}
```

`
INFO: ime_hwnd_current 4a05ba
INFO: hwnd 4a05ba

INFO: ime_hwnd_current 4a05ba
INFO: hwnd 320968 //this is Focus

INFO: ime_hwnd_current 4a05ba
INFO: hwnd 4a05ba
`
@slouken 
Should I use focus if I have multiple windows?

sorry i don't speak english, this is from google translate

**Comment by baidwwy** [comment]
```cpp
void
WIN_SetTextInputRect(_THIS, SDL_Rect *rect)
{
    SDL_Window* window;
    SDL_VideoData *videodata = (SDL_VideoData *)_this->driverdata;
    HIMC himc = 0;
    HWND hwnd = 0;

    if (!rect) {
        SDL_InvalidParamError("rect");
        return;
    }

    window = SDL_GetKeyboardFocus();
    if (window) {
        hwnd = ((SDL_WindowData*)window->driverdata)->hwnd;
        himc = ImmGetContext(hwnd);
    }
   
    if (himc)
    {
        COMPOSITIONFORM cof;
        CANDIDATEFORM caf;

        videodata->ime_rect = *rect;

        cof.dwStyle = CFS_RECT;
        cof.ptCurrentPos.x = videodata->ime_rect.x;
        cof.ptCurrentPos.y = videodata->ime_rect.y;
        cof.rcArea.left = videodata->ime_rect.x;
        cof.rcArea.right = videodata->ime_rect.x + videodata->ime_rect.w;
        cof.rcArea.top = videodata->ime_rect.y;
        cof.rcArea.bottom = videodata->ime_rect.y + videodata->ime_rect.h;
        ImmSetCompositionWindow(himc, &cof);

        caf.dwIndex = 0;
        caf.dwStyle = CFS_EXCLUDE;
        caf.ptCurrentPos.x = videodata->ime_rect.x;
        caf.ptCurrentPos.y = videodata->ime_rect.y;
        caf.rcArea.left = videodata->ime_rect.x;
        caf.rcArea.right = videodata->ime_rect.x + videodata->ime_rect.w;
        caf.rcArea.top = videodata->ime_rect.y;
        caf.rcArea.bottom = videodata->ime_rect.y + videodata->ime_rect.h;
        ImmSetCandidateWindow(himc, &caf);

        ImmReleaseContext(hwnd, himc);
    }
}
```
This works fine
![动画](https://user-images.githubusercontent.com/6239458/148662749-b43e48ce-5e06-4ba5-8634-10eb7422b194.gif)

**Comment by slouken** [comment]
@zreedy, the issue here is that we currently have the concept of a global window context for the IME, but it's perfectly valid to have multiple windows. Thoughts?

**Comment by zreedy** [comment]
@slouken Our application has multiple windows and this works fine with the current implementation (without the SDL_DISABLE_WINDOWS_IME flag). I don't think the HWND handle matters too much here, but there might be some hidden bug that didn't show either in our workflow or in testing.

As for the issue reported by the Author, the SDL_DISABLE_WINDOWS_IME flag can just declare an empty body for `WIN_SetTextInputRect`, it's not like it's going to be used regardless. Unless I misunderstand this flag?

**Comment by baidwwy** [comment]
@zreedy 
SDL_DISABLE_WINDOWS_IME is not enabled,
SDL_SetTextInputRect  also have problems

**Comment by baidwwy** [comment]
In version 2.0.20, I use SDL_SetHint('SDL_IME_SHOW_UI', '1')

**Comment by zreedy** [comment]
@baidwwy You mentioned SDL_DISABLE_WINDOWS_IME in the first post, what was that about? Maybe I'm misunderstanding something here. I thought that this was crashing only if SDL_DISABLE_WINDOWS_IME was enabled.

Are you using SDL 2.0.22? That's our version and multiple windows seems to work fine with IME here.

**Comment by baidwwy** [comment]
> ```c++
> 	if (SDL_Init(SDL_INIT_VIDEO) == -1) {
> 		SDL_Log("SDL_Init failed: %s\n", SDL_GetError());
> 		return 1;
> 	}
> 
> 	SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1");
> 	const int winw = 800;
> 	const int winh = 600;
> 	SDL_Window* window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, winw, winh, 0);
> 	if (!window) {
> 		SDL_Log("SDL_CreateWindow failed: %s\n", SDL_GetError());
> 		SDL_Quit();
> 		return 1;
> 	}
> 	SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
> 	if (!renderer) {
> 		SDL_Log("SDL_CreateRenderer failed: %s\n", SDL_GetError());
> 		SDL_Quit();
> 		return 1;
> 	}
> 	SDL_Rect rect = { 0,0,0,0 };
> 	SDL_StartTextInput();
> 	SDL_SetTextInputRect(&rect);
> 	SDL_StopTextInput();
> 
> 	SDL_Window* window1 = SDL_CreateWindow("Hello SDL1", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, winw, winh, 0);
> 	SDL_Renderer* renderer1 = SDL_CreateRenderer(window1, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
> 	if (!renderer) {
> 		SDL_Log("SDL_CreateRenderer failed: %s\n", SDL_GetError());
> 		SDL_Quit();
> 		return 1;
> 	}
> 
> 	SDL_StartTextInput();
> 	SDL_SetTextInputRect(&rect);
> 	SDL_StopTextInput();
> 
> 	SDL_DestroyWindow(window1);
> 	
> 	SDL_StartTextInput();
> 	SDL_SetTextInputRect(&rect);
> 	SDL_StopTextInput();
> ```
> 
> ```c++
> void
> WIN_SetTextInputRect(_THIS, SDL_Rect *rect)
> {
>     SDL_Window* window;
>     SDL_VideoData *videodata = (SDL_VideoData *)_this->driverdata;
>     HIMC himc = 0;
> 
>     if (!rect) {
>         SDL_InvalidParamError("rect");
>         return;
>     }
> 
>     videodata->ime_rect = *rect;
>    
>     window = SDL_GetKeyboardFocus();
>     HWND hwnd = ((SDL_WindowData*)window->driverdata)->hwnd;
>     SDL_Log("ime_hwnd_current %p", videodata->ime_hwnd_current);
>     SDL_Log("hwnd %p", hwnd);
>     himc = ImmGetContext(hwnd);
>     if (himc)
>     {
>         COMPOSITIONFORM cof;
>         CANDIDATEFORM caf;
> 
>         cof.dwStyle = CFS_RECT;
>         cof.ptCurrentPos.x = videodata->ime_rect.x;
>         cof.ptCurrentPos.y = videodata->ime_rect.y;
>         cof.rcArea.left = videodata->ime_rect.x;
>         cof.rcArea.right = videodata->ime_rect.x + videodata->ime_rect.w;
>         cof.rcArea.top = videodata->ime_rect.y;
>         cof.rcArea.bottom = videodata->ime_rect.y + videodata->ime_rect.h;
>         ImmSetCompositionWindow(himc, &cof);
> 
>         caf.dwIndex = 0;
>         caf.dwStyle = CFS_EXCLUDE;
>         caf.ptCurrentPos.x = videodata->ime_rect.x;
>         caf.ptCurrentPos.y = videodata->ime_rect.y;
>         caf.rcArea.left = videodata->ime_rect.x;
>         caf.rcArea.right = videodata->ime_rect.x + videodata->ime_rect.w;
>         caf.rcArea.top = videodata->ime_rect.y;
>         caf.rcArea.bottom = videodata->ime_rect.y + videodata->ime_rect.h;
>         ImmSetCandidateWindow(himc, &caf);
> 
>         ImmReleaseContext(hwnd, himc);
>     }
> }
> ```
> 
> ` INFO: ime_hwnd_current 4a05ba INFO: hwnd 4a05ba
> 
> INFO: ime_hwnd_current 4a05ba INFO: hwnd 320968 //this is Focus
> 
> INFO: ime_hwnd_current 4a05ba INFO: hwnd 4a05ba ` @slouken Should I use focus if I have multiple windows?
> 
> sorry i don't speak english, this is from google translate

INFO: ime_hwnd_current 4a05ba
INFO: hwnd 320968 //this is Focus

in multiple windows 
always the hwnd of the 1st window

**Comment by slouken** [comment]
I may be misunderstanding, but it looks like @baidwwy is starting text input on each window immediately after it is created, assuming that it would put the last window created into text input mode. The correct model is to start text input in response to window focus change events.

e.g.
```c
if (event.window.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_FOCUS_GAINED) {
    SDL_StopTextInput();
    SDL_SetTextInputRect(&rect);
    SDL_StartTextInput();
}
```
Is that right, @zreedy?

**Comment by zreedy** [comment]
@slouken That would work to change the rect. Optionally you could
```
if (event.window.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_FOCUS_GAINED) {
    SDL_ClearComposition();
    SDL_SetTextInputRect(&rect);
}
```

Which might be more expedient since it does less flag shuffling and doesn't fully disable the IME at the kernel level.

@baidwwy I understand that the HWND is always the 1st window. What I don't understand is what's the buggy behavior here? Just that this variable isn't what you expect? What is the buggy User Experience?
In other words, unless the HWND not matching the newly created window explicitly results in some unexpected behavior that the user can observe this is not a bug. Given my current understanding of how the Windows API for IMEs work the HWND does not matter as all HWNDs in the process will share the same HIMC.

Is the issue that the Candidate Window appears at the wrong location?

**Comment by baidwwy** [comment]
@zreedy share the same HIMC？i didn't know that。。。
but why doesn't it work
Modifying the focus HWND is valid

**Comment by baidwwy** [comment]
@zreedy 
I tested again, no problem, ver 2.0.20
2.0.14 I'm sure there is a problem😢

**Comment by baidwwy** [comment]
I tested again, no problem, ver 2.0.20
2.0.14 I'm sure there is a problem😢
