### ISSUE TITLE
SDL_egl.c: Uses libGL.so.1 and fails when it should use libOpenGL.so.0

### ISSUE THREAD

**Issue by lanodan** [libsdl-org/SDL#4158]
Found while testing [taisei](https://taisei-project.org/) in a [libX11-less wayland setup](https://hacktivis.me/notes/pure-wayland.shtml) where I get `glcommon_load_library: SDL_GL_LoadLibrary() failed: Could not initialize OpenGL / GLES library` without changes.

I can load it with setting `SDL_VIDEO_GL_DRIVER=libOpenGL.so` but one fix for this is changing `#define DEFAULT_OGL "libGL.so.1"` to `#define DEFAULT_OGL "libOpenGL.so.0"` in `src/video/SDL_egl.c`.

Would have send a patch but it doesn't seems to be an easy fix… maybe with reusing `-DEGL_NO_X11` (used in `/usr/include/EGL/eglplatform.h`)?

**Comment by InfoTeddy** [comment]
> Would have send a patch but it doesn't seems to be an easy fix…

What's wrong with the change you suggested?

**Comment by lanodan** [comment]
> What's wrong with the change you suggested?

Doesn't works in systems that do not have libglvnd where libOpenGL.so.0 comes from. (I know it's the case in FreeBSD)

**Comment by Cacodemon345** [comment]
@lanodan Could you try testing #4183 and see if the issue is fixed?
