### ISSUE TITLE
SDL_ConvertPixels should reject indexed pixel formats

### ISSUE THREAD

**Issue by JRF-github** [libsdl-org/SDL#4160]
Currently SDL_ConvertPixels accepts the following nonsense:
```
auto I8 = SDL_PIXELFORMAT_INDEX8;
auto s1 = SDL_CreateRGBSurfaceWithFormat(0, 20, 20, 0, I8);
auto s2 = SDL_CreateRGBSurfaceWithFormat(0, 20, 20, 0, I8);
auto r = SDL_ConvertPixels(20, 20, I8, s1->pixels, s1->pitch, I8, s2->pixels, s2->pitch);
```
This "works" in the sense that SDL_ConvertPixels copies data from s1 to s2 and returns 0, but since the two surfaces may have completely different palettes that seems just wrong. Without arguments for palettes I don't see how the function can ever work correctly with indexed formats.

**Comment by 1bsyl** [comment]
index8 to index8 makes sense if you consider it only does a copy. Also, it's useful also to change the 'pitch'.

Otherwise, the conversion with index8 gets rejected there: 
https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_surface.c#L1338

So I think I can close the issue.
