### ISSUE TITLE
New issue in 2.0.14 causing controller detection not to work when controller is on after app is opened

### ISSUE THREAD

**Issue by MasonT8198** [libsdl-org/SDL#4173]
In 2.0.12 the issue is gone so it seems to be a regression.

**Comment by MasonT8198** [comment]
https://github.com/libsdl-org/SDL/commit/cbe13d232d40ff3cdd5313057a09e6ff4e1fad56#diff-f6d88a1dd41357072aa1ad38b2f479cbeb968236ed1138e43c907e459785d5c3 found the cause of the regression, this seems to make SDL not detect controllers when the app is open, instead you have to close the application then reopen it for the changes to take effect. It shouldn't be a hard regression to fix. It works in linux and macOS just fine.

**Comment by MasonT8198** [comment]
It seems the kill_timer function in the commit may be killing the timer too early so the controller doesn't get added onto the program in Windows 10, odd how it works in linux and macos however

**Comment by slouken** [comment]
I'm not seeing this issue and have been doing extensive testing on Windows.

Are you able to reproduce it with the testgamecontroller test program? If not, can you post a link to the project that's having this problem?

**Comment by glebm** [comment]
This appears to be a similar bug report: https://github.com/libsdl-org/SDL/issues/4147

**Comment by MasonT8198** [comment]
> I'm not seeing this issue and have been doing extensive testing on Windows.
> 
> 
> 
> Are you able to reproduce it with the testgamecontroller test program? If not, can you post a link to the project that's having this problem?

I'm on linux so I can't reproduce the problem, but the project that is using this is the emulator https://www.xemu.app/ , we noticed this when we updated to 2.0.14, our discord (primarily) windows users, said that they could no longer connect their controllers while the application was open

**Comment by slouken** [comment]
This is fixed in https://github.com/libsdl-org/SDL/commit/adb75d642cabcd8b42b817de711b4ab03e35b634
