### ISSUE TITLE
[ARM NEON] "Performing Test ARMNEON_FOUND - Failed" even though the SBCs support NEON

### ISSUE THREAD

**Issue by SupervisedThinking** [libsdl-org/SDL#4174]
I build a SDL2 package for my LibreELEC 10 fork but even though `-DARMNEON=ON` is set the assembly test fails with:

```
-- Performing Test ARMNEON_FOUND
-- Performing Test ARMNEON_FOUND - Failed
```

The target systems are e.g. RK3399, A311D SBCs and support NEON. The build host is a generic x86_64 system so I cross-compile SDL2.

sdl2 package:
https://github.com/SupervisedThinking/LibreELEC-RR/blob/libreelec-10.0-RR/packages/supervisedthinking/multimedia/SDL/sdl2/package.mk

CMake build log:
https://pastebin.com/PUnhQ65k

CMakeError.log
https://pastebin.com/SwhwVjzn

**Comment by Cacodemon345** [comment]
A glance at the error log hints at either CMake or the assembler generating garbage code.

**Comment by SupervisedThinking** [comment]
Obviously that's the reason why the check fails ^^ the "assembler" is probably GCC10.2, at least from my experience usually gcc is used for assembler code when used in libretro cores.

**Comment by icculus** [comment]
Moving files to GitHub in case we lose them on pastebin.

[SDL2 git 3a1317e ARMNEON RK3399.txt](https://github.com/libsdl-org/SDL/files/6240381/SDL2.git.3a1317e.ARMNEON.RK3399.txt)
[SDL2 git 3a1317e build log.txt](https://github.com/libsdl-org/SDL/files/6240382/SDL2.git.3a1317e.build.log.txt)

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
