### ISSUE TITLE
Hidpi support in X11

### ISSUE THREAD

**Issue by realh** [libsdl-org/SDL#4176]
The X11 backend doesn't seem to support hidpi yet, but Wayland does. It would be useful if SDL could support hidpi on X11, because there there are lots of obstacles to gamers adopting Wayland, including #3739.

**Comment by icculus** [comment]
I can't find clear guidance on what needs to be done for this. Was this all built at the Gnome and KDE level, and toolkits talking directly to X11 are out of luck?

I assume we need a way to broadcast "we can cooperate in a HiDPI environment" to the system and then report correct (scaled) values for window size, mouse coordinates, SDL_GL_GetDrawableSize, etc. but I need information on how this works in current times at the X11 level.

**Comment by realh** [comment]
I think it is done at the toolkit level with a user option, eg GNOME/GTK3 has a dconf setting, Qt and GTK2 have environment variables. In theory you should be able to query the X server to at least be able to calculate the DPI and decide on appropriate scaling, but the information can be highly unreliable. For example, ISTR my previous TV, a Sony, reported its dimensions as 16m x 9m!

I don't suppose you'd want to link SDL with dconf, so having its own environment variable would probably be the best way forwards.

**Comment by slouken** [comment]
This is now implemented for SDL 3.0.
