### ISSUE TITLE
CMake build on macOS produces `sdl2-config` with dubious `--static-libs` output

### ISSUE THREAD

**Issue by thomcc** [libsdl-org/SDL#4181]
On MacOS, when building with cmake, the resulting `sdl2-config --static-libs` result tells me to link frameworks with -l/absolute/path/to/Blah.framework. For example: 

```
-l/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/CoreVideo.framework
```

I gather this is because CMake does some automatic translation of these (According to <https://cmake.org/cmake/help/latest/command/find_library.html>):

> If the library found is a framework, then `<VAR>` will be set to the full path to the framework `<fullPath>/A.framework`. When a full path to a framework is used as a library, CMake will use a `-framework A`, and a `-F<fullPath>` to link the framework to the target.

This seems okay (actually, it seems pretty strange to pass `-F<fullpath>` in for system frameworks, but it... probably is harmless for most cases).

The problem occurs when they get handled the same as the libraries needing `-l` here: https://github.com/libsdl-org/SDL/blob/3d22731d94d6259255ef3fd5006c8c6c80e377b4/CMakeLists.txt#L2266

which I believe blindly adds `-l` to the front of each item in the list.

There are two problems with this:

1. These should be `-framework Blah` to link with a framework, and not `-l`.

2. Even if this worked (you could imagine splitting it into `-F/path/to/Frameworks` and `-framework CoreVideo` parts, mimicing the logic described in the CMake docs), it hard-codes the path to the current OS version's SDK, e.g. `MacOSX11.0.sdk`.

    I may have `sdl2-config` longer than I have that path, after which sdl2-config will no longer work, as those paths will no longer exist. That said, these paths shouldn't need to show up anywhere anyway.

    (Note: Obviously this only matters for the stuff that gets hardcoded into `sdl2-config`, and other stuff that contains build output that persists past this build, such as pkgconfig output — in particular, I don't expect it to matter at all for actually building the SDL library artifacts).

### Suggested solution:

My understanding is that SDL2 only links to system frameworks, so IMO the best and easiest solution would just be some logic (possibly hacky logic) to just output something like `-framework Baz` (or `-Wl,-framework,Baz`) if static linking with SDL2 requires I link to `Baz.framework`.

(For clarity: no need to output `-F` at all, since these should already be on the framework search path)

This would make the `cmake`'s `sdl2-config` produce output which more-or-less matches that of the autotools build system's `sdl2-config`, which seems desirable.

---

While I'm reporting this, there's one more bit of weirdness in the output of cmake's `sdl2-config --static-libs`:

It seems to contain several flags that are clearly intended for building the SDL2 dylib, such as the `-Wl,-current_version` and `-Wl,-compatibility_version` options.

I assume this is just a mistake. For clarity, these three are included, but probably shouldn't be: https://github.com/libsdl-org/SDL/blob/3d22731d94d6259255ef3fd5006c8c6c80e377b4/CMakeLists.txt#L539-L541

The first one doesn't matter — `-undefined error` is the default setting of the macos linker (although it might not work how you want), but the others are probably not intended for users of SDL2.

---

Anyway, these aren't a *huge* deal (although they do prevent me from directly using the CMake build, or at least make it trickier), and this sort of thing seems somewhat expected given that the `cmake` system is still listed as experimental — I figured I'd file an issue since I couldn't find anything on file already, and have some background with linking on macOS.

Thanks for everything, hope that helps! (Also, sorry if this is the wrong place to report an issue!)

**Comment by icculus** [comment]
I hate to keep kicking this down the line, but I'm bumping this to 2.0.20. The work to fix this isn't something we should do at the last minute (which is why it got bumped from 2.0.16, too! This is my fault both times.), and while it's not a complete rewrite or anything, it's not trivial either.

**Comment by slouken** [comment]
@madebr, is this something that makes sense to keep in this milestone? We're starting to wrap up for release.
