### ISSUE TITLE
Question: Is Joystick UUID specific to individual device sample or to the model number?

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#4202]
Hello!

I have the `SDL_JoystickGetGUID()` call that returns the UUID number of the gamepad. I have the question: does UUID is specific to the model or to the device sample? I mean, will be UUID different or the same when I will plug two and more equal gamepads (of the same model and manufacturer)? Right now I have two different gamepads, however, I got a think what will be if there are two equal gamepads will be.

**Comment by icculus** [comment]
If they are exactly the same model of device, they'll have the same GUID. Now you might get two PlayStation 4 controllers that look completely identical but Sony changed the product ID between them, and then they'll be different GUIDs.

We use the GUID to decide what controller it is when deciding how to make the joystick look like a standard game controller, by looking up the GUID in a list of known controllers we maintain, so they are largely reliable, but we don't use it to compare one device to another, as far as I know. On most platforms, the GUID is created from the USB HID vendor/model/product ID reported to the OS.

(and on some platforms: the same physical controller will produce a different GUID if you plug it in via USB or Bluetooth.)

So it's complicated.  :)

Does this answer your question?

**Comment by Wohlstand** [comment]
Yeah, thanks for the explanation! :fox_face:

I think about the strategy on how I'll assign the controller-individual settings (mapping) manually configured by every user through the setup (that allows the user to set up every button to every in-game action manually, like with the keyboard case). So, if I have two equal gamepads, I should also use the last joystick index in the array as a second key, and do find the last saved settings by UUID for only the case when controllers were been re-plugged into different ports and their array order got changed. Right now I do use the SDL_Joystick API with the full manual gamepad set up by the user, and soon I going to start using the SDL_GameController to simplify the controller usage.

**Comment by Wohlstand** [comment]
Mainly I want to allow users to toggle different plugged controllers and keep user's settings for each individual device, and don't require the user to re-setup gamepad controls after selecting the different gamepad of a different model. (The miss-up of the previous author of the game I develop now, I gonna resolve this completely).

**Comment by Lokathor** [comment]
If both devices support the Controller API, then you can have the user settings be in terms of that, and then their settings will easily be usable with anything else that uses the Controller API as well.
