### ISSUE TITLE
Support returning `sfSymbolsName` for gamepad controls on macOS / iOS / tvOS

### ISSUE THREAD

**Issue by pbhogan** [libsdl-org/SDL#4203]
Apple has a requirement that games published in Apple Arcade need to display controls properly when rebound and use the Apple's [SFSymbols](https://developer.apple.com/sf-symbols/) icon library to display control icons. 

From my experience with developers implementing this (I'm the developer of InControl, a commonly-used input plugin for Unity) it's enough for developers to have the string name of the symbol they need to use. This is exposed on `GCControllerElement` as an instance property `sfSymbolsName` ([reference](https://developer.apple.com/documentation/gamecontroller/gccontrollerelement/3563999-sfsymbolsname?language=objc)). With that, they can have a lookup table of icons and go from there.

Currently, there is no way to get at this in SDL. I basically need to implement access to this for a project and I was just going to hack in a patch to `SDL_mfijoystick.m` to let me query it, but it would be nice if there was an officially supported way to query this with the SDL API. 

Since I'm going to do the work anyway, I'd be happy to put together a pull request. However, I'm not sure how it would fit in with the joystick API, and I'm not sure what SDL's practice is for extremely platform specific API calls like this.

I was thinking to add exposed functions like `SDL_JoystickGetAppleSFSymbolsNameForButton( SDL_Joystick* joystick, int button );` and the same for axes and hats.

There's also another property `localizedName` that may be useful to expose in the same way.

Can someone give me a bit of guidance on what the API should look like—the SDL style-guide, so to speak? Is this something desirable for a pull request?

**Comment by icculus** [comment]
This feels like wedging in an iOS-specific API is probably correct here. I can't imagine a cross-platform equivalent of this that would be implemented anywhere else.

(Now an API that returns the icons themselves, so you can show PlayStation/Xbox/whatever icons for the controller in use? That would be cool, but also a giant and never-ending project, and way beyond what is needed here.)

**Comment by flibitijibibo** [comment]
This might be an instance where a SysJoystick would be helpful, i.e. an equivalent to SysWM. On Switch, for example, we have a handful of scenarios where we either have to drill into SDL's internals to get certain data or add one-off API calls, neither of which are all that great and leave you ultimately writing platform-specific paths anyway (and adds unnecessary maintenance burdens to SDL since we then have to preserve that hacky behavior). HIDAPI might complicate this, but for the rest it can't be too hard to scribble in, right...?

**Comment by icculus** [comment]
> it can't be too hard to scribble in, right...?

Har har.  :)

On the Switch, we have a "here's the actual platform handle if you need it" for all the weird Switch things you can do, and possibly this is the right thing to do in a generic sense, but I still think a throwaway iOS/Mac API is the most expedient thing here.

**Comment by pbhogan** [comment]
> On the Switch, we have a "here's the actual platform handle if you need it" for all the weird Switch things you can do, and possibly this is the right thing to do in a generic sense

Just having the `GCController` handle would be enough for my purposes, but there are several other cases where access to the actual backing control handles for each input would be useful.

> but I still think a throwaway iOS/Mac API is the most expedient thing here.

Agreed.

I actually have this _mostly_ working now, implemented as:
`const char * SDL_GameControllerGetAppleSFSymbolsNameForAxis(SDL_GameController *gamecontroller, SDL_GameControllerAxis axis)` 
and
`const char * SDL_GameControllerGetAppleSFSymbolsNameForButton(SDL_GameController *gamecontroller, SDL_GameControllerButton button)`
since it's only practically useful in the context of the game controller API rather than the joystick API. And it's far simpler to implement for a known set of controls. I had to put the code in `SDL_mfijoystick.m` to get access to the internals. 

I'm unsure how to check that a given `SDL_Joystick` is handled by the Apple Game Controller driver internally. Sorry, I'm still finding my way around the codebase. :) I can't check `guid.data[14] == 'm'` as it's [not always set in every case](https://github.com/libsdl-org/SDL/blob/4acd1dcad41d154093ca14eb0adf35f4f99bd06a/src/joystick/iphoneos/SDL_mfijoystick.m#L318-L324) for some reason. Do I just do `SDL_GameControllerGetJoystick(gamecontroller)->driver == &SDL_IOS_JoystickDriver`?

Still debugging some weird behavior I'm seeing. Apple's framework is returning blanks for some controllers, and also I think SDL is making a duplicate controller for the Xbox One S (white) controller connected with bluetooth on macOS 11.  So I get two controllers show up, with different product IDs, one of which has the symbols return things and the other does not. So maybe the second is coming from the HIDAPI driver and there's a duplicate because `IOS_SupportedHIDDevice()` is failing... but I could be doing something stupid. ¯\_(ツ)_/¯ I'll track it down.

**Comment by slouken** [comment]
The duplicate controller should be fixed in the latest SDL code. Can you submit a pull request for your changes? I'd like to get them in for 2.0.18 if possible.

**Comment by pbhogan** [comment]
Sure—I've got it [here](https://github.com/libsdl-org/SDL/pull/4806).

**Comment by slouken** [comment]
This has been added in https://github.com/libsdl-org/SDL/commit/149e5c656a063f64fa3e257d0bca5e8fcaada603
Note that I did a little cleanup and changed the function to return NULL if the symbol wasn't found in https://github.com/libsdl-org/SDL/commit/e14358265e627a4c0324eaa7317ed13f28d7a138. Please let me know if that's a problem!

**Comment by pbhogan** [comment]
> Note that I did a little cleanup and changed the function to return NULL if the symbol wasn't found in [e143582](https://github.com/libsdl-org/SDL/commit/e14358265e627a4c0324eaa7317ed13f28d7a138). Please let me know if that's a problem!

The reason I had it return an empty string is that my use case down the line is always to return a string. So, now I need to do a NULL check and string copy if not NULL. Not a big deal. I can see it both ways and I can work with this.

Probably a more elegant solution would be to take a char buffer pointer and max length as parameters which gets the buffer filled and return either a boolean, or non-zero length if anything was written.

¯\_(ツ)_/¯
