### ISSUE TITLE
relative mouse mode issues under windows remote desktop.

### ISSUE THREAD

**Issue by Robadob** [libsdl-org/SDL#4206]
*This is related to #2331, however from looking at the code it appears that was remedied despite the issue being open (there is a special case for remote desktop mouse movements as they are provided absolute rather than relative).*

## Context

Under remote desktop, windows reports mouse movement in absolute rather than relative terms. SDL already has a fix for this, which stores the previous mouse position to derive the relative movement between updates.

https://github.com/libsdl-org/SDL/blob/4acd1dcad41d154093ca14eb0adf35f4f99bd06a/src/video/windows/SDL_windowsevents.c#L707

It doesn't however appear that SDL is able to warp the mouse during remote desktop sessions.

## Issues

* As the mouse movement is absolute, once the mouse reaches the edge of the screen, it can nolonger move further in that direction. Therefore relative mouse events do not occur, if they would take the mouse outside of the screen.

* The `lastMousePoint` value which tracks the mouse's previous location is function static, therefore when leaving and re-entering relative mouse mode, a (large) false mouse movement event is generated if the mouse has moved whilst not in relative mouse mode.

* In a multi-monitor setup, where remote desktop is only on one monitor, it is possible for the mouse to leave the remote desktop window and stop being tracked.

## Resolution

Inside remote desktop, the cursor is treated as a touchscreen, so only absolute mouse movements are received, and hence WINAPI `setCursorPos()` does not work normally. This is for performance/security reasons. It can apparently be bypassed via [RemoteFX USB forwarding](https://superuser.com/a/853172), however in attempting to test that I've managed to prevent myself from being able to connect to the remote machine I was using.

As such 2 of the 3 issues can't be remedied by SDL itself, and remaining issue doesn't merit fixing given that relative mouse mode is too limited within remote desktop.

I would suggest better signposting the limitations of relative mouse mode over windows remote desktop, but I'm not sure of the best place to do so.

**Comment by slouken** [comment]
I've added documentation to the relevant functions in https://github.com/libsdl-org/SDL/commit/d89f4b3ae48a69873c31c31b7a66e463f5063a9b

Thanks!
