### ISSUE TITLE
SDL_GetPlatform() returns "Mac OS X" for macOS.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4208]
I have no idea what sort of damage it would do to change this, but Apple changed the name of the platform from "Mac OS X" to "macOS" awhile ago, so we should probably change SDL_GetPlatform.

Presumably this is mostly used for logging, and actual logic that changes based on platform would use a preprocessor test, right??

**Comment by slime73** [comment]
I can imagine some code written in languages that don't have platform preprocessing might use `SDL_GetPlatform` with actual logic.

Maybe there should be a new function just to get the platform's 'pretty name' for logging and display purposes? I don't know if that's worth it just to support the macOS name change though, or even if the language thing is a real problem with real code or just a hypothetical.

**Comment by icculus** [comment]
> I can imagine some code written in languages that don't have platform preprocessing might use SDL_GetPlatform with actual logic.

Yeah, that's a good point. We'll leave it alone for now.

**Comment by flibitijibibo** [comment]
It's already closed, but for future reference: Can confirm that this would be pretty catastrophic for C# games - there's supposed to be an OSVersion in the C# standard but it intentionally does not work, so we have to use something like SDL_GetPlatform instead:

https://github.com/FNA-XNA/FNA/wiki/4:-FNA-and-Windows-API#environmentspecialfolder
