### ISSUE TITLE
Viewport Render Clear Oddity

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4210]
As discussed [here](https://discourse.libsdl.org/t/viewport-render-clear-oddity/30948) ...

> It appears that if you do the following:
>    * Set a viewport of a portion of the window
>    * Render to the viewport
>    * Set a viewport to the entirety of the window
>    * Render Clear
>
> Only the last viewport to be drawn to will be cleared. However, if you render to the "fullwindow" viewport before clearing, the entire screen will be cleared as normal. If the "fullwindow" viewport is 1 pixel smaller than the window, the render clear will clear the entire screen as normal.
>
> This doesn't really seem like intended behavior? At the vary least I just wanted to document in case somebody runs into this issue in the future as I couldn't find anything related.

**Comment by JayFoxRox** [comment]
What backend is affected?

This sounds like a potential duplicate or similar problem to https://github.com/libsdl-org/SDL/issues/3357.
So I suggest to test with GL backend which has #3357 fixed; if that resolves it it's probably enough to fix #3357 for other backends.

If it's not a duplicate I suggest to fix the GL backend first (before doing #3357 for other backends, to avoid different solutions in different backends).

**Comment by icculus** [comment]
As JayFoxRox mentioned, this is likely a Direct3D 9 issue that was just fixed for #3357, but here's a test program that does what the bug described, and it's working fine on OpenGL. Will verify on Windows (and see if it was specifically 585c11c5aef170a181402184fa0dcbd31653fe02 that fixed it) in the morning. But I assume we're good to go here.

```c
#include "SDL.h"

int main(void)
{

    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *win = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, 0);
    SDL_Renderer *rend = SDL_CreateRenderer(win, -1, SDL_RENDERER_PRESENTVSYNC);

    while (1) {
        SDL_SetRenderDrawColor(rend, 0, 0, 0, 255);
        SDL_RenderClear(rend);

        const SDL_Rect r1 = { 100, 100, 100, 100 };
        SDL_RenderSetViewport(rend, &r1);

        SDL_SetRenderDrawColor(rend, 255, 0, 0, 255);
        SDL_RenderDrawLine(rend, 150, 150, 50, 50);

        // same results with an explicit SDL_Rect or NULL.
        //const SDL_Rect r2 = { 0, 0, 640, 480 };
        SDL_SetRenderDrawColor(rend, 255, 255, 255, 255);
        SDL_RenderSetViewport(rend, NULL); //&r2);
        SDL_RenderClear(rend);

        SDL_RenderPresent(rend);
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                SDL_Quit();
                return 0;
            }
        }
        SDL_Delay(15);
    }
    SDL_Quit();
    return 0;
}
```

**Comment by icculus** [comment]
Turns out this was still broken on Direct3D 9. The previous fix to the clip rect _was_ necessary, but Direct3D 9 also clears based on the viewport settings, and the test app above sets it to the size of the render target right before the SDL_RenderClear call...SDL was checking the requested viewport size but not whether that request had actually been committed to Direct3D yet.

Anyhow, fixed now.

**Comment by icculus** [comment]
(Just for sanity's sake, while I'm on a Windows machine: this works correctly on Direct3D 11, too.)

**Comment by icculus** [comment]
(This is fixed, unless there was reopened by accident.)

**Comment by slouken** [comment]
No, I reverted your change. It broke rendering in all the test programs.

**Comment by icculus** [comment]
> It broke rendering in all the test programs

Yikes, that's unexpected! I'll check that shortly.

**Comment by icculus** [comment]
Fixed this issue and confirmed that other test apps _also_ still render this time. Sorry about that!
