### ISSUE TITLE
GetWindowSize returns wrong dimensions

### ISSUE THREAD

**Issue by blumens** [libsdl-org/SDL#4216]
I have a problem with SDL 2.0.14 under Linux with X and a tiling window manager like i3. Directly after I open a window the dimensions returned by SDL_GetWindowSize are wrong since the window manager ignores the dimensions supplied by SDL. This is fixed once I call SDL_WaitEvent, presumably because SDL gets a SDL_WINDOWEVENT_RESIZED event and updates the values internally.

This issue seems related to  #3217 and #1407.

**Comment by briggs-w** [comment]
This sounds related: https://github.com/libsdl-org/SDL/issues/3337

**Comment by xTVaser** [comment]
We were seeing this issue as well on i3 - it was fixed in this recent PR https://github.com/libsdl-org/SDL/pull/7341 and then reverted more recently, causing a regression https://github.com/libsdl-org/SDL/pull/7502/files#diff-4d617e5c2011238b8ec8564c68b8a4bf491d9500c1cfc2d2660ceaa39d56c4f7R1098-R1108

**Comment by 1bsyl** [comment]
My understanding is that while it's in the middle of the resizing process, SDL_GetWindowSize gives the last good value.
the news size, should be given by the SIZE event.


the "revert" was to fix bug, pass test test (eg. ./testautomation --filter video) .
maybe,  https://github.com/libsdl-org/SDL/issues/7638 is a way to improve things ..

**Comment by icculus** [comment]
I'm thinking we can just add an extra query for window geometry in X11_ShowWindow, which is called before a window is mapped, even at creation time, so we can add an event to the SDL queue right after the window officially lands on the screen, in case the window manager adjusted it. In theory, this should make SDL_GetWindowSize report correctly directly after SDL_CreateWindow, and probably catch other corner cases, too.

**Comment by icculus** [comment]
Okay, this is tested on i3 over here, and it went from 100% reproducable to 0% with the pushed patch.

Test program:
```c
#include "SDL.h"

int main(int argc, char **argv)
{
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, 0);
    int x, y;
    SDL_GetWindowSize(window, &x, &y);
    printf("at start: %dx%d\n", x, y);
    SDL_Delay(1000);
    SDL_Event e;
    while (SDL_PollEvent(&e)) {}
    SDL_GetWindowSize(window, &x, &y);
    printf("at end: %dx%d\n", x, y);
    SDL_Quit();
    return 0;
}
```

The "at start" line would be 640x480 before this patch, and after the patch it's the actual window size the WM chose.

**Comment by slouken** [comment]
Are you cherry-picking that for SDL 2.28?

**Comment by 1bsyl** [comment]
I haven't really checked in details, but it seems 
`./test/testautomation --filter video` 
is now occasionally failing (for instance, with `--seed PAGZZ81JV8BADZI3`)
```
Assert 'Validate y (current: 734, expected: 808)': Failed
Assert 'Validate y (current: 734, expected: 808)': Failed
```

**Comment by slouken** [comment]
We should change the test so the position being different isn't a failure. That's something that we expect applications to be able to handle.
