### ISSUE TITLE
Audio: Assert in SDL_Audio::SDL_RunAudio when pairing bluetooth headphones

### ISSUE THREAD

**Issue by willco007** [libsdl-org/SDL#4221]
On Windows 10, when I pair my Sony WH-1000XM3 headphones, I hit an assert in SDL_Audio.c line 751, 

`SDL_assert((got < 0) || (got == device->spec.size));`

The got value is 0.

Steps:
1) Open audio connection like so:
`soundDevice = SDL_OpenAudioDevice(
		NULL, 
		0,
		&want, 
		&have, 
		0); // do not SDL_AUDIO_ALLOW_FORMAT_CHANGE
`
2) Pair bluetooth headphones while application is running.

RESULT:
Assert 

I'd be happy to provide any additional information requested.

**Comment by flibitijibibo** [comment]
Seems like this assert could stand to be <= 0 and not be a problem - just means a period is going to be silent while it moves things around. Does changing the assert accordingly sound okay on your end?

**Comment by willco007** [comment]
Yup, that seems fine. If I continue after the assert the audio does successfully move to my BT headphones. Thanks for the quick follow-up.

**Comment by flibitijibibo** [comment]
Sounds good - @icculus: I think either code path technically works for this, but do we want to use the SDL_Delay path when `got == 0` or is the current memset path okay for this situation?
