### ISSUE TITLE
[BUG] XBox One Series X controller, the "Share" button doesn't works, Linux Mint

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#4222]
Hello! I do have the recently bought gamepad of Xbox One Series X model 1914. I run it via USB (USB Type-C <-> PC). The device itself is wireless mainly, but it can be used via USB cable too.

Here are the next specs I got when I run the unit test:
```
INFO: Joystick device 0 added.
INFO: Joystick
INFO:        name: Xbox One Series X Controller
INFO:        type: Game Controller
INFO:        axes: 6
INFO:       balls: 0
INFO:        hats: 1
INFO:     buttons: 11
INFO: instance id: 0
INFO:        guid: 030000005e040000120b000001050000
INFO:     VID/PID: 0x045e/0x0b12
```

I had to use SDL 2.0.14, however, I found this commit: https://github.com/libsdl-org/SDL/commit/a5dba7d3ab2bcdefb2dc9e590767bf345a81dfa5

Then, I tried to build the top main state (c12f46b100d22a0e06a64c5b6d1baa3f446d34e6), however, the button is still won't work.

**Comment by Wohlstand** [comment]
Should I try to make the raw HIDAPI input dump and do you have any things on how to make that?

**Comment by Wohlstand** [comment]
Okay, I found that the HIDAPI flag was OFF at me, but when I rebuilt the library with:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DHIDAPI=ON ..
```
still the "Share" button won't work

**Comment by slouken** [comment]
Did you confirm that the HIDAPI driver actually worked? On many Linux systems you'll need to run as root to directly access the USB devices.

You'll be able to tell if it's actually coming through HIDAPI because the GUID has "68" near the end.

**Comment by Wohlstand** [comment]
Lemme try some... I probably need to add something into the rules.d to allow the non-root usage then...

**Comment by Wohlstand** [comment]
,


The GUID is "030000005e040000120b000001050000" and seems it doesn't appear on the HIDAPI list, something other makes it work in a different way (probably there is some driver I should uninstall?)

Also, I did the test with the latest SDL2 library from the top and demo built, ran under root:
![Снимок экрана от 2021-07-24 13-07-14](https://user-images.githubusercontent.com/6751442/126865208-a971c4f6-82c8-46ee-8cce-3c6d88aef1db.png)
result is the same

**Comment by slouken** [comment]
I'm happy to troubleshoot this live with you. Let me know if you're available and the best way to reach you.

**Comment by Wohlstand** [comment]
My time zone is UTC+3, I am usually available the rest of the daylight, and some time in the evening and night (I usually go sleep lately, at 1~2 AM, but I may go sleep earlier if I got very tired)

**Comment by cgutman** [comment]
That GUID doesn’t look like it’s using HIDAPI, so the problem is probably that your Linux kernel doesn’t expose the share button. It was just added recently in v5.14 which is not officially released yet.

https://github.com/torvalds/linux/commit/0b1d6c8c00157cbfcf343925c4de81af0187a7b7

**Comment by Wohlstand** [comment]
I see, at me, the kernel was 5.8, just now I installed the 5.11 (I do install low-latency kernels)

**Comment by Wohlstand** [comment]
Also, on my system there are 5 hidraw devices listed, and they are:
- CMedia (my USB headphones)
- keyboard uses two hidraw devices at once
- mouse uses two hidraw devices at once

**Comment by I-g-e** [comment]
Hi, it seems like this did not get resolved yet? This seems like a relevant issue, so I’m posting here rather than creating a new one.

I am also having trouble with the share button of this controller via [another program](https://github.com/AntiMicroX/antimicrox/issues/307), which is using SDL.

I ran the `testgamepad` command that is provided with the SDL source code. Pressing the share button on the controller gives the following output:
> The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 175 (167), X11 KeySym 0x1008FF1C (XF86AudioRecord).

I also ran the `controllermap` command, this is the mapping I ended up with:

```
050000005e040000130b000007050000,Xbox Series X Controller,platform:Linux,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,misc1:b15,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,
```

The same error message as above was printed when I pressed the share button while the button was highlighted in the shown layout.

My system information:
```
$ cat /etc/fedora-release
Fedora release 35 (Thirty Five)
$ uname -r
5.15.12-200.fc35.x86_64
```

Please tell me if I can provide any more useful information for solving this.

**Comment by I-g-e** [comment]
**EDIT:** Actually, sorry, seems like my controller is not exactly the same as OP’s:

```
INFO: Joystick
INFO:           name: Xbox Series X Controller
INFO:           type: Game Controller
INFO:            LED: no
INFO:         rumble: no
INFO: trigger rumble: no
INFO:           axes: 6
INFO:          balls: 0
INFO:           hats: 1
INFO:        buttons: 16
INFO:    instance id: 1
INFO:           guid: 050000005e040000130b000007050000
INFO:        VID/PID: 0x045e/0x0b13
```

@slouken Should I move this into a new issue?

**Comment by slouken** [comment]
> @slouken Should I move this into a new issue?

Yes please. X11 interpreting the share button as a record key is a different issue from the original one where the HIDAPI driver wasn't being used.

**Comment by slouken** [comment]
The version of kernel you're using doesn't support the Share button. I believe this works on the latest 6.x series kernel.

**Comment by Wohlstand** [comment]
I updated the stuff a while ago  and it works now. I forgot to reply here.

**Comment by Wohlstand** [comment]
Forgot to say, my current system is Linux Mint 21.2 (Ubuntu 22.04). Previous was 20.3 (Ubuntu 20.04).
