### ISSUE TITLE
Assertion in WaveFormatToSDLFormat

### ISSUE THREAD

**Issue by swx2k** [libsdl-org/SDL#4223]
WaveFormatToSDLFormat does seem to handle the case when waveformat->wFormatTag = WAVE_FORMAT_EXTENSIBLE and 
waveformat->wBitsPerSample = 24. The device is "Headphones (STRIX RAID DLX)". This happens when calling SDL_Init.

**Comment by flibitijibibo** [comment]
Function in question...

https://github.com/libsdl-org/SDL/blob/main/src/audio/wasapi/SDL_wasapi.c#L85

I don't think 24-bit audio is supported at all right now... we could create the constant value with these:

https://github.com/libsdl-org/SDL/blob/main/include/SDL_audio.h#L69

But actual mix support is a whole other issue. A workaround is to switch to 16-bit audio on the system (or float32 if possible).

**Comment by flibitijibibo** [comment]
Resolved by #4240
