### ISSUE TITLE
Proposing Text to Speech in SDL

### ISSUE THREAD

**Issue by blastbay** [libsdl-org/SDL#4225]
Would there be any interest in having a subsystem in SDL for platform specific text to speech?

Text to speech is being used more and more widely, particularly when it comes to adding accessibility for blind and visually impaired users. But there are a lot of other applications as well, and I think that supporting this in SDL would be a great asset.

If there is interest in this, I would like to spend some time working out a generic API and then get some feedback from others. if the feedback is positive, I'd be happy to provide implementations for a couple of backends - specifically Microsoft Sapi 5 and CMU Flite. I don't have access to other platforms at the moment so I would probably need help from others with additional backends, unless I can get my hands on more hardware.

I imagine something like the following for a minimal feature set:

* Enumerate available backends and initialize the one you want
* Enumerate voices, with or without language/gender/age filters
* Select a voice and get information such as bit depth and sample rate
* Configure voice attributes such as speaking rate, volume and pitch (this will be backend dependent but we can have some common ones)
* Submit UTF-8 text (either plain or SSML when supported)
* Retrieve the entire synthesized waveform into a buffer
* If streaming synthesis is supported, begin retrieving the waveform in small chunks (either via a callback or through a polling interface)
* If memory streams are not supported by the backend, submit text to be played directly to the default audio device as a fallback

Ideally we want to retrieve data via memory streams and then submit it to SDL's audio subsystem manually, because the resamplers supported by most tts backends are of widely differing quality and it would be nice to get some predictability by using SDL's resampler whenever possible. Most voices produce audio at 11025, 16000 or 22050 HZ.

Let me know if any of you find this interesting!

Kind regards,

Philip Bennefall

**Comment by TheQuinbox** [comment]
I know this is a few months old, but I for one would find this very interesting and useful
