### ISSUE TITLE
[BUG] Game Controller: X/Y and A/B got swapped on Android via USB-OTG

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#4226]
Hello!

I have two different gamepads: 
- **Xbox One Series X Controller model 1914** that can work via Bluetooth and via USB OTG 
  - GUID: `030000005e040000120b000000006800` on Android USB-OTG
  - GUID: `030000005e040000120b000001050000` on Linux Mint USB
  - VID/PID: `0x045e/0x0b12` on Linux USB
- **Aceline CG-1 one**
  - GUID: `0500000079000000110000005f7e0000` on Android USB-OTG
  - GUID: `03000000790000001100000010010000` on Linux USB
  - VID/PID: `0x0079/0x0011` on Linux USB

Both giving the same issue: the two pairs of keys: X-Y, and A-B buttons got swapped mapping when they work via USB-OTG (I.e. when I hit Y, I get X, and when I hit X, I get Y. The same when I git A, I get B, and when I git B, I get A). 

When the Xbox controller works through Bluetooth, it works correctly, all buttons were mapped properly. On Linux Mint they do give the correct mapping.

Where I should tweak at SDL2 to fix this issue on Android with USB-OTG?

**Comment by Wohlstand** [comment]
Hello!
My friend has tested my game and confirms that the same bug gets reproduce on the Retroid Pocked device, the controller has been recognized as a "Playstation 3".

![изображение](https://user-images.githubusercontent.com/6751442/112735602-532ba880-8f5e-11eb-88a0-0ccd8930f2a4.png)

**Comment by slouken** [comment]
I'm surprised that the Xbox controller has the wrong mapping. It's using HIDAPI, and the input report data is the same, and interpreted the same, across all supported platforms.

I ran a test where I connected the Xbox Series X controller to a Google Pixel 3a phone via USB cable, and used the Steam Link app to test the mapping. All buttons were reported correctly.

Are you able to reproduce this with the latest SDL snapshot?
http://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by Wohlstand** [comment]
Hi there!
Sorry for the late reply, I didn't test yet the build, but, today I got a PS4 controller from my friend to test some, and. I wonder, it works correctly in as-is form, all buttons mapped properly. XBox' and second controllers were buggies here (button mappings swapped), so, gonna try to build the thing with your snapshot and verify the work with Xbox thing again...

**Comment by Wohlstand** [comment]
On the first, gonna try the recent 2.0.16 release

**Comment by Wohlstand** [comment]
Just now I tested the thing, Xbox controller has been fixed on 2.0.16, it's mapped as intended, `Aceline CG-1 one` (UUID: `0500000079000000110000005f7e0000`) still have an incorrect mapping:
![20210831_144640](https://user-images.githubusercontent.com/6751442/131497507-3866d4d5-7f35-4c0c-8037-ea00a1664c0b.jpg)
where 3 should be A, however, B recognized; where 2 should be B, however, A recognized;
where 4 should be X, however, Y recognized; where 1 should be Y, however, X recognized.

**Comment by slouken** [comment]
Okay, glad to hear it. That controller just needs an updated mapping.

**Comment by Wohlstand** [comment]
btw, Where I may find the default mappings to let me make the quick patch for that?

**Comment by Wohlstand** [comment]
Lol, the Linux UUID of the Aceline CG-1 one controller is matched with this entry:
```
"03000000790000001100000010010000,Retrolink SNES Controller,a:b2,b:b1,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b9,x:b3,y:b0,",
```
Really this and mine are using the same chip? :thinking:

**Comment by Wohlstand** [comment]
Hm... :thinking:  Inside there are no exact chips, there is a black droplet, and the "GYH-705A" label on the board :thinking: 

![20210904_143722](https://user-images.githubusercontent.com/6751442/132093138-17703876-cc94-4899-bc69-bd2bbc5a537b.jpg)

![20210904_143729](https://user-images.githubusercontent.com/6751442/132093141-daeefb29-bcda-421b-b243-6ddde642d4e0.jpg)

**Comment by Wohlstand** [comment]
Okay, just for a test, I'll try to copy the mapping from Linux into Android block to try some...

**Comment by Wohlstand** [comment]
I made the little experiment with the copying of the mapping from the Linux into Android, and that resulted in the whole mapping is confused even worse than was :zany_face: 
So, I will need to compose the new mapping from the scratch... If the mapping will work, I will sent the pull-request with the fix

**Comment by Wohlstand** [comment]
@slouken, I guess, the main issue has been solved, and you may remove the "waiting" tag, the last thing related to the DragonRise chip can be discussed later at #4718, because it's a special case because this chip is widely used by a lot of various controllers giving the same UUID causing hard way to differentiate them.
