### ISSUE TITLE
SIGSEGV / SIGABRT on SDL_DestroyRenderer after return of main

### ISSUE THREAD

**Issue by Urfoex** [libsdl-org/SDL#4231]
I was tinkering with emscripten, and used RAII and global variables for automatic SDL resource cleanup, when I noticed SIGSEGV and SIGABRT popping up on shutting down the program.
Sample program [free_after_end.cpp.txt](https://github.com/libsdl-org/SDL/files/6195204/free_after_end.cpp.txt)
Compiling: $ g++ -Wall -Wextra -std=c++20 -ggdb free_after_end.cpp -D_REENTRANT -I/usr/include/SDL2 -lSDL2
Output [SIGSEGV.log](https://github.com/libsdl-org/SDL/files/6195206/SIGSEGV.log)
Output [SIGABRT.log](https://github.com/libsdl-org/SDL/files/6195208/SIGABRT.log)

Debian
libsdl2-2.0-0:amd64    2.0.14+dfsg2-3
g++ (Debian 11-20210319-1) 11.0.1 20210319
libgl1-mesa-dri:amd64    21.0.0-1

**Comment by icculus** [comment]
This test program works for me here. It's possible we fixed this recently, or it's a bug in your OpenGL drivers...?
