### ISSUE TITLE
D3D11 is missing

### ISSUE THREAD

**Issue by graducan** [libsdl-org/SDL#4237]
Why is D3D11 renderer missing from the prebuild binaries?

**Comment by icculus** [comment]
We (currently) only build it for WinRT/UWP by default, but it's probably reasonable to use it (and _default to it_) on other Windows platforms now, falling back to Direct3D 9 when unavailable.

I'm going to tentatively toss this issue into the 2.0.18 milestone, for now at least.

**Comment by icculus** [comment]
Actually, this appears to be wired up in configure, cmake, and the Visual Studio projects already.

SDL_config_windows.h will enable support if `SDL_WINDOWS7_SDK` is defined, and defines that earlier as...

```c
#if _WIN32_WINNT >= 0x0601  /* Windows 7 */
#define SDL_WINDOWS7_SDK
#endif
```

...so this _might_ just work out of the box on a modern Visual Studio (or Windows SDK)? I'll verify.

**Comment by slouken** [comment]
The prebuilt binaries are built with mingw64, which don't have that enabled by default.

The D3D9 renderer should still be the default, as it's still faster than D3D11 on older hardware, and not significantly slower on newer hardware.

**Comment by icculus** [comment]
Okay, for now we'll call this done. @graducan, you can force the d3d11 renderer with a hint or by specifically asking for it by index number in SDL_CreateRenderer.
