### ISSUE TITLE
[KMS/DRM] vkQuake3 No Longer Works on the Pi4 in >= 1080p Resolutions

### ISSUE THREAD

**Issue by bluestang2006** [libsdl-org/SDL#4243]
Hello,

I updated SDL2 from the source yesterday and vkQuake3 no longer seems to "work properly". By that, I mean that the binary runs but there is no display when using the Vulkan backend. This is happening in the KMS/DRM API only, if I switch to X11 I am able to run vkQuake3 without any issues. I am also able to run vkQuake3 in KMS/DRM with the OpenGL1 renderer so this is strictly happening with Vulkan.

Running GDB is pointless because vkQuake3 is running, but again there is no display. I am running RPiOS 64-bit (aarch64) with the Pi4's KMS video and audio driver set to 1920x1080 @ 120 Hz.

I am able to run vkQuake1 just fine, and other Vulkan games so it is not a MESA driver issue. I know there have been substantial changes to the KMS/DRM code in the recent week.

**Update:** This issue appears to be evident when running in a HD resolution or higher. 720p or lower works just fine...

**Comment by vanfanel** [comment]
I just tried to build latest vkQuake3 and latest SDL2/KMSDRM and things work fine around here (my monitor doesn't support 120Hz modes anyway, but for the modes it supports, the game runs fine).
If someone else can reproduce this and give us a clue I will gladly look at the problem. But I can see no problem here so far.

**Comment by bluestang2006** [comment]
Resolved...turns out this was a monitor issue causing this. For whatever reason, my Pi4 did not like a certain HDMI port on my monitor.
