### ISSUE TITLE
[Linux] Text input depends on X locale mechanism

### ISSUE THREAD

**Issue by Carmina16** [libsdl-org/SDL#4245]
It seems that unless the system locale is supported by an obsolete X librray locale mechanism, text input doesn't work for non-ASCII characters. In particular, `SDL_TextInputEvent::text` seems to be empty for keys that X library could not translate.

Modern toolkits do not use that hopelessly obsolete mechanism.

**Comment by flibitijibibo** [comment]
Huh, it seems like we're looking at roughly the same thing from different angles. I'm working on IME support for Wayland via #4246, but I have absolutely no idea what I'm doing - do you happen to have experience with this? I dunno how much attention X will get, but if we can get this right in Wayland the first time around this might eventually fix itself.

**Comment by icculus** [comment]
What is the recommended mechanism in modern times, @Carmina16?

**Comment by icculus** [comment]
I think this is likely to bump out of 2.0.22 as well.  :(

**Comment by icculus** [comment]
I'm kicking this to 2.0.24, but not even early-in-milestone. Right now my only goal for 2.0.24 is _research_ to figure out what the modern options are and if they are available to us.

**Comment by slouken** [comment]
We do have modern IME support that should handle the case you're talking about. Please reopen this if you have a test case and repro steps.

Thanks!
