### ISSUE TITLE
Github Actions not running on repo

### ISSUE THREAD

**Issue by Thog** [libsdl-org/SDL#4247]
Hello there,

I was looking around and saw that the ``Build`` and ``GitHub Pages`` break because of org level restrictions.

It would be nice to fix that by allowing Github Actions to use ``actions/checkout`` at the org level.

Example of failing run: https://github.com/libsdl-org/SDL/actions/runs/694708029

**Comment by icculus** [comment]
This is fixed now; future pull requests (and probably future pushes to current ones) will run CI now.
