### ISSUE TITLE
Joystick Handle leak

### ISSUE THREAD

**Issue by twisted89** [libsdl-org/SDL#4259]
With a Dualshock 4 connected and HID support disabled SDL2 leaks User Objects like there's no tomorrow. 
Tested on Windows 10 pro x64 build 19042.870

![image](https://user-images.githubusercontent.com/1544273/113157696-0af8d880-9233-11eb-9c2b-ea55a6c17641.png)

I've noticed the issue doesn't occur when SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1"); is set

Issue easily reproducible with latest official DLL '2.0.14' and the following test code (with a Dualshock 4 connected via USB)

```c++
#include <iostream>
#include <vector>
#include <SDL.h>
#include <Windows.h>

static int sdlinput_js_init() {
    
    // SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");
    SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS4, "0");
    
    if (SDL_Init(0) < 0) {
        printf("SDL_Init failed");
        return -1;
    }
    
    if (SDL_InitSubSystem((SDL_INIT_GAMECONTROLLER | SDL_INIT_HAPTIC)) < 0) {
        printf("SDL_InitSubSystem failed");
        return -1;
    }
    
    return 0;
}
    
static void sdl_peep_events() {
    
    static SDL_Event sdl_events[256];
    unsigned int minType = SDL_JOYAXISMOTION;
    unsigned int maxType = SDL_CONTROLLERDEVICEREMAPPED; 
    SDL_PeepEvents(sdl_events, 256, SDL_GETEVENT, minType, maxType);
}

#undef main
int main()
{
    sdlinput_js_init();
    while (true)
    {
        sdl_peep_events();
        Sleep(10);
    }
    
    return 0;
}
```

**Comment by slouken** [comment]
I wasn't able to reproduce this with the latest code snapshot, can you try that and see if this is fixed?
http://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by slouken** [comment]
You should definitely poll for events or use the event thread so Windows can clean up event handles.
