### ISSUE TITLE
Does Cocoa's -[NSOpenGLContext update] need dispatch to main thread, or just a mutex?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4260]
For future evaluation:

See this comment about whether we needed to use dispatch to the main thread or just a carefully-placed mutex, and research further. If the mutex is safe, it's a way more desirable approach.

https://github.com/libsdl-org/SDL/pull/4242#issuecomment-811125659

**Comment by nighthawk469** [comment]
Found this comment in AppKit while debugging  [NSOpengGLContext update] crash in OpenMW.
Macosx sdk 10.15
![Screen Shot 2021-04-25 at 4 02 39 PM](https://user-images.githubusercontent.com/2553980/116009275-9cffc100-a5e6-11eb-9240-851ba532ee8c.png)

https://gitlab.com/OpenMW/openmw/-/issues/5939

**Comment by icculus** [comment]
I guess that settles that.  :)

Thanks!
