### ISSUE TITLE
Raspberry Pi 4, software/hardware forced VSYNC?

### ISSUE THREAD

**Issue by padremayi** [libsdl-org/SDL#4265]
I wrote an emulator and I have a piece of code that syncs audio/video using elapsed time and remaining bytes to play on audio buffer and maintains nominal game FPS. This works very well.

If I remove that piece of code emulator runs as fast as it can on x86 Ubuntu laptop, i.e. over 200 FPS. On Raspberry Pi v4 I can't go over 60 FPS (for some games stucks at 30 FPS) like an hardware VERTICAL SYNC is enabled.

I don't use **SDL_RENDERER_PRESENTVSYNC** when create the renderer.

So, the problem is not a piece of code, and now the synchronization code is commented out, the problem is:

**"Why WITHOUT that code Raspberry Pi 4 stucks on 60 FPS?"**

SDL2 built from 2.0.14 source code with

    --disable-video-rpi --enable-video-kmsdrm

Test with Raspberry Pi v4 with Kernel 5.4 or Kernel 5.10 with `dtoverlay=vc4-fkms-v3d` or `dtoverlay=vc4-kms-v3d` in config.txt.

Monitor set to 1080p at 60 Hz, Raspberry Pi v3 works as expected and goes over 60 FPS without any problem.

If I use **SDL_RENDERER_PRESENTVSYNC** emulator works as expected also on Raspberry Pi v4. So, is it mandatory to use VSYNC on Raspberry Pi v4 or is it a bug?

**Comment by audetto** [comment]
I have a similar setup as yours except I use the SDL from the OS.
If I disable vsync, I can get full screen with full KMS, well above 100FPS on a Pi4.

**Comment by audetto** [comment]
And, have you tried https://wiki.libsdl.org/SDL_GL_SetSwapInterval?

**Comment by icculus** [comment]
We appear to have code in place to handle this:

https://github.com/libsdl-org/SDL/blob/fc508eabe2ed808c4b2258bdbbab5940b8c9a0f8/src/video/kmsdrm/SDL_kmsdrmopengles.c#L157-L168

I'll try this out and see if it's a regression.

**Comment by slouken** [comment]
It looks like this is fixed. We've done a bunch of work on the KMSDRM video support since 2.0.14, so I'm not surprised that it works correctly now.

I built the latest code from Git and ran testsprite2 with no options:
`INFO: 1773.40 frames per second`
then ran testsprite2 --vsync:
INFO: 60.00 frames per second

Please let us know if you're still seeing this with the latest code.
