### ISSUE TITLE
[Wayland] Fullscreen toggles get canceled out by a bogus resize

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#4281]
Pretty easy test: Open a 1280x720 window, then call SDL_SetWindowFullscreen with SDL_WINDOW_FULLSCREEN_DESKTOP. At first it does the usual resize event to your desktop resolution, but then it comes right back around and gets resized to the old windowed mode of 1280x720. This is presumably because of the `pending` value causing an outdated resize to get sent after the fullscreen set has been done. The result is bogus window information, which means your eventual glBlitFramebuffer will eventually be wrong! OpenGL and Vulkan behave differently because of HandlePendingResize timing differences, but they're both wrong in their own strange way.

Interestingly the current libdecor path in #4068 is unaffected by this, but it may also explain why the window size is completely wrong when going from windowed -> fullscreen -> windowed, so I'll CC @christianrauch here just in case.

Capsized is my test case for this since it has hardcoded screen size values (sorry), it is on the very latest FNA as of writing.

**Comment by christianrauch** [comment]
Regarding toggling fullscreen or maximised mode from a fixed-sized window, there are some issues with mutter, the Wayland compositor of GNOME Shell:
- https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1795
- https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1811

So this might not be SDL's sole fault.

**Comment by flibitijibibo** [comment]
Luckily this is pretty consistent on KWin as well - the part where we're at fault is letting pre-existing clamps cause resize events when making the move to/from fullscreen. Easy fix, just gotta wedge the calls in... #4285 should cover it!
