### ISSUE TITLE
sdl2.m4 is broken on cross-compilation environments

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#4283]
sdl2.m4 has this line:
`-],, no_sdl=yes,[echo $ac_n "cross compiling; assumed OK... $ac_c"])`
Which means a breakage on a cross-compilation
environments, notably on buildroot.

Please avoid the use of AC_TRY_RUN().
I think AC_CHECK_HEADERS()+AC_CHECK_LIBS()
should be enough.

**Comment by icculus** [comment]
So I don't see how this would be broken, here's what this does according to https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Runtime.html ...

`AC_RUN_IFELSE (input, [action-if-true], [action-if-false], [action-if-cross-compiling])`

So if this succeeds (not cross-compiling, the thing compiles and runs and the version check it is doing works), this runs `[action-if-true]` (which is a no-op here), if not cross-compiling and it fails it runs `[action-if-false]` (which sets up the script to complain properly), and if cross-compiling it *does nothing* and runs `[action-if-cross-compiling]`, where we say "it's fine, go on anyhow."

Anecdotally, I've cross-compiled SDL many times, and it hasn't caused this problem.

(this thing can't just check headers and libs, because it's trying to verify that sdl2-config reports the correct version.)

If this is still causing you problems, can you post the config.log where this is failing?

**Comment by stsp** [comment]
> Anecdotally, I've cross-compiled SDL many times, and it hasn't caused this problem.

Compiling SDL makes no problems.
But if you take sdl2.m4 into your
project and use AM_PATH_SDL2()
and friends, then obviously you get
no checks at all, so I do this:
```
diff --git a/src/plugin/sdl/m4/sdl2.m4 b/src/plugin/sdl/m4/sdl2.m4
index a03b2d270..8ff2c5d31 100644
--- a/src/plugin/sdl/m4/sdl2.m4
+++ b/src/plugin/sdl/m4/sdl2.m4
@@ -137,7 +137,7 @@ int main (int argc, char *argv[])
     }
 }
 
-],, no_sdl=yes,[echo $ac_n "cross compiling; assumed OK... $ac_c"])
+],, no_sdl=yes, no_sdl=yes)
         CFLAGS="$ac_save_CFLAGS"
         CXXFLAGS="$ac_save_CXXFLAGS"
         LIBS="$ac_save_LIBS"
```

**Comment by stsp** [comment]
sdl2.m4 should provide the same
amount of checks for host and
cross-compiling environments.
Otherwise it breaks the projects
that use sdl2.m4 when cross-compiling
is used.

**Comment by icculus** [comment]
> Otherwise it breaks the projects that use sdl2.m4 when cross-compiling is used.

So to be clear: you're saying the current code is _not_ printing "cross compiling; assumed OK..." and then continuing on without error?

**Comment by stsp** [comment]
Suppose you have some project
that you are trying to compile with
buildroot. buildroot sets all the
needed variables like PKG_CONFIG_PATH
to the cross-tools, so normal autoconf
packages can perform all their usual
checks on a cross environment.
But sdl is not being properly checked.
It just says "cross compiling; assumed OK"
even if nothing is OK (no sdl installed).

My point is: pkg-config CAN be used
when cross-compiling (because the
PKG_CONFIG_PATH shows to target
sysroot), so there is no need to skip
all checks. AC_TRY_RUN can't be used
but some alternate checks would be
good to have.

**Comment by stsp** [comment]
So all I ask for, is to replace
"echo cross compiling; assumed OK"
with the set of cross-safe checks,
like AC_CHECK_LIBS, AC_CKECK_HEADERS,
PKG_CHECK_MODULES etc.
They all work fine under cross-compilation,
and AC_TRY_RUN has an extra arg
for cross-compilation exactly for that,
not for a plain "echo assume OK".

**Comment by slouken** [comment]
Ah, that makes sense. Let's do this for the 2.0.20 release.

**Comment by stsp** [comment]
Please remove "waiting" label then.

**Comment by stsp** [comment]
> Ok, so the "assume OK" thing isn't a check for a library, it's some C code that parses the output of sdl2-config
> to decide if the version is new enough.

Hi @icculus would you be more
specific, please? :)
You have:
```
AC_RUN_IFELSE([AC_LANG_SOURCE([[
some C code here
]])], [], [no_sdl=yes], [echo $ac_n "cross compiling; assumed OK... $ac_c"])
```

What kind of "C code that parses the output of sdl2-config to decide"
do you have in mind?
Currently there is none.
If you want to add some,
then you can as well add
the AC_CHECK_LIBS and
alike, so I don't understand
your point.

> This seems dumb even outside of a cross-compiling environment,

I am confused also here, as
the last arg of AC_RUN_IFELSE()
is exactly and only for cross env.
Outside of a cross env, there are
the checks to see if the prog can
be compiled and run.

> It appears to already be a fallback for PKG_CHECK_MODULES

Thanks, so I'll simply get rid of
`AM_PATH_SDL2` then.
Wasn't aware its deprecated.

**Comment by icculus** [comment]
> What kind of "C code that parses the output of sdl2-config to decide" do you have in mind?

I was referring to this thing, specifically:

https://github.com/libsdl-org/SDL/blob/ec0204d2438829b18d5942b93713dfd00682121c/sdl2.m4#L114-L149

Which can probably be done without C code at all, honestly, but also, unless a good patch shows up to remove it, this code is Good Enough until we delete the configure script completely.

**Comment by stsp** [comment]
> we delete the configure script completely.

I switched my project to
PKG_CHECK_MODULE().
You could mention initially
that sdl2.m4 is deprecated. :)

Feel free to close this.

**Comment by icculus** [comment]
> You could mention initially that sdl2.m4 is deprecated.

I honestly didn't know; it's all dark magic to me. Sorry!
