### ISSUE TITLE
warning from SDL_kmsdrmvulkan.c

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#4284]
```
src/video/kmsdrm/SDL_kmsdrmvulkan.c: In function 'KMSDRM_Vulkan_CreateSurface':
src/video/kmsdrm/SDL_kmsdrmvulkan.c:201: warning: initialization makes integer from pointer without a cast
```
This is on an ILP32 build, where `VK_DEFINE_NON_DISPATCHABLE_HANDLE` defines
not a pointer but an uint64_t. Is the following patch acceptable? @vanfanel?
```diff
diff --git a/src/video/kmsdrm/SDL_kmsdrmvulkan.c b/src/video/kmsdrm/SDL_kmsdrmvulkan.c
index c101ead..a477529 100644
--- a/src/video/kmsdrm/SDL_kmsdrmvulkan.c
+++ b/src/video/kmsdrm/SDL_kmsdrmvulkan.c
@@ -198,7 +198,7 @@ SDL_bool KMSDRM_Vulkan_CreateSurface(_THIS,
     VkDisplaySurfaceCreateInfoKHR display_plane_surface_create_info;
 
     VkExtent2D image_size;
-    VkDisplayModeKHR display_mode = NULL;
+    VkDisplayModeKHR display_mode = (VkDisplayModeKHR)0;
     VkDisplayModePropertiesKHR display_mode_props = {0};
     VkDisplayModeParametersKHR new_mode_parameters = { {0, 0}, 0};
 
```

**Comment by vanfanel** [comment]
@sezero Well, I don't like it much because it makes code less clear, and I don't even know what an ILP32 system is.
But if it doesn't break anything and you think it's ok, go for it. I trust your criteria more than mine :)

**Comment by sezero** [comment]
>  what an ILP32 system is.

32 bit systems, e.g. i686

> But if it doesn't break anything 

That's why I'm actually asking you

**Comment by vanfanel** [comment]
@sezero Ah ok. Well, the only place where `display_mode` is used for comparing against a value, it's safe to assume it's 0, so should be perfectly ok.

**Comment by sezero** [comment]
Applied https://github.com/libsdl-org/SDL/commit/e97cfe4ad1f5ef5b52c76905312d85e861e92ca2
