### ISSUE TITLE
Build error on macOS 11.2.3+Xcode 12.4+cmake 3.19

### ISSUE THREAD

**Issue by tom-seddon** [libsdl-org/SDL#4286]
macOS 11.2.3
Xcode 12.4
cmake version 3.19.20201025-gd749d46

Repro steps: (commit 0f4aba7bcdc6aa8671c1f93700266b0e8907cc70 is HEAD at time of writing)

```
cd /tmp
git clone https://github.com/libsdl-org/SDL
cd SDL
git checkout 0f4aba7bcdc6aa8671c1f93700266b0e8907cc70
mkdir ../SDL.cmake
cd ../SDL.cmake
cmake ../SDL/
make
```

Expected result: SDL builds

Actual result: a bunch of errors that look like it's attempting to build Objective C code as C, e.g.:

```
[  0%] Building C object CMakeFiles/SDL2.dir/src/file/cocoa/SDL_rwopsbundlesupport.m.o
In file included from /tmp/SDL/src/file/cocoa/SDL_rwopsbundlesupport.m:24:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:492:1: error:
      expected identifier or '('
@class NSString, Protocol;
^
```

**Comment by tom-seddon** [comment]
I'd completely forgotten that I'd previously submitted https://github.com/libsdl-org/SDL/commit/4b35a18d8b4529944f537c4cf316395e10bc8f72 - vaguely similar symptoms, as I recall. And now I'm reminded of it, I remember it having to be reverted, so I'm not going to attempt a fix for this issue either. Just a report.

Looks like https://github.com/libsdl-org/SDL/pull/4274 might also be the same kind of thing.

**Comment by natbro** [comment]
is this possibly a problem with your cmake 3.19.20201025-gd749d46 ? I'm able to build without issues on macOS 11.2.3+ and Xcode 12.4. .m files are automatically built with -ObjC

**Comment by tom-seddon** [comment]
Thanks for the suggestion - I upgraded to cmake 3.20, and it now builds. Presumably something in Xcode changed.

**Comment by okuoku** [comment]
In regard of #4274 it was a bit more complex.

In [CMake 3.19.1, it dropped language enforcement with `LANGUAGE` property](https://cmake.org/cmake/help/v3.19/release/3.19.html#id1), and that was why your update to 3.20 fixed issue.

Unfortunately, `Xcode` generator still does not allow `LANGUAGE` to `C` override if one had `enable_language`'ed `OBJC` or `OBJCXX` and that was my case -- my project builds [ANGLE as OpenGL ES implementation](https://github.com/okuoku/angle-static-cmake) and other METAL based middlewares alongside SDL. These include [`enable_language(OBJCXX)`](https://github.com/okuoku/angle-static-cmake/blob/a76de3179c0607def1efcf0d58a740ca627fcc78/CMakeLists.txt#L9) thus  #4274 was created to support this project structure but it drops earlier CMake and now-unsupported OSX SDKs.

I feel requiring CMake 3.16 (was released in 2019Nov) is a bit too early and seeking workaround..
