### ISSUE TITLE
CI should run tests and visualtest to ensure consistent behaviour across all platforms

### ISSUE THREAD

**Issue by JayFoxRox** [libsdl-org/SDL#4297]
Currently the CI appears to only check if the build succeeds.
However, with so many different backends available, the CI should run way more tests to ensure consistent behaviour across all platforms / renderers / ...

Not all backends can be tested fully automatically (testing input or audio is difficult probably), but a lot can still be done.
Visual output could also be compared against a known reference output, or screenshots could be made available as an artifact, so it's easier to inspect bugs. visualtest might already offer some of this, but probably depends on #1557.

- I'm confident that having this (+ extended tests) would have caught #3357 and #4210.
- It will make it easier to test and review changes such as #4195 (see commit title: "Add D3D11 implementation (not yet tested)").
- It will also reveal backend inconsistency which will help to improve documentation (as things likely aren't as strictly specified as they should have been).
- It could also reveal outdated backends that should be fixed or removed.

**Comment by icculus** [comment]
My inclination is this is going to cause way more problems than it catches.

**Comment by JayFoxRox** [comment]
> My inclination is this is going to cause way more problems than it catches.

How so?

- Unit-testing and testing are essential parts of software development, and that they are invaluable feedback during development.. and deployment (which is why CI is a good spot for it + not everybody runs tests locally, so CI can do it for them).
- Aiding developers to test cases they can't locally reproduce (such as documenting new bugs on macOS by a backend change that was only meant to affect Windows) is a benefit for identifying remaining issues with a change.
- Similar tests in CI ared used by various projects of different sizes to great success. For standard unit tests this is clear, for visual tests see something like this:
    - Dolphin Gamecube / Wii emulator has fifoci for example, and it's used to great extent to visually compare different code revisions of the renderer in many different game situations. This helps to developer to test games and platforms that they don't own themselves.
        - Here's an example for visual CI result: https://fifo.ci/compare/5716299-5715442/
    - There's a whole industry around visual testing: https://duckduckgo.com/?q=visual+test+CI&t=h_&ia=web (often with marketing claims like "AI" - but let's ignore those)

I don't think a failed test on CI should necessarily prevent merges (which potentially slows down development), but it will still lead to exposure of backend issues or tests.
For changes which introduce new problems, those don't necessarily have to be fixed as part of the PR which introduce these inconsistencies, but just be kept track of (e.g. ~"we updated backend $A here, but it caused problems with backend $B and $C").
Such exposure makes it more likely that they'll be fixed by PR authors (they might simply have been unaware of their bugs), or outside contributors (who can now anticipate that the next SDL release would be broken for them).

---

Here's another angle to look at it.

For example, I tried running this on Linux:

```bash
git clone https://github.com/libsdl-org/SDL.git
cd SDL
cmake -B build -DSDL_TEST=ON
cmake --build build
./build/test/testautomation 
```

Even this trivial test fails with a segmentation fault:

```
[...]
INFO:  04/14/21 07:59:51: Assert 'Verify return value; expected: -1, got: -1': Passed
INFO:  04/14/21 07:59:51: Assert 'Call to SDL_CloseAudio(), call 1': Pass
INFO:  04/14/21 07:59:51: Assert 'Call to SDL_CloseAudio(), call 2': Pass
INFO:  04/14/21 07:59:51: Assert 'Call to SDL_AudioQuit(), call 1': Pass
INFO:  04/14/21 07:59:51: Assert 'Call to SDL_AudioQuit(), call 2': Pass
INFO:  04/14/21 07:59:51: Assert 'Call to SDL_GetAudioDriver(2)': Pass
INFO:  04/14/21 07:59:51: Assert 'Audio driver name is not NULL': Passed
INFO:  04/14/21 07:59:51: Assert 'Audio driver name is not empty; got: sndio': Passed
INFO:  04/14/21 07:59:51: Assert 'Call to SDL_AudioInit('sndio')': Pass
ERROR: 04/14/21 07:59:51: Assert 'Validate result value; expected: 0 got: -1': Failed
Segmentation fault (core dumped)
```

So SDL already has known bugs in the test harness, [which doesn't seem to have a bug report](https://github.com/libsdl-org/SDL/issues?q=is%3Aissue+is%3Aopen+testautomation) (or it's drained in other issues, making it hard to find it = not enough exposure).

The mere existing of a non-functional testharness also means that not enough developers use it (= bitrot occurs).
They don't consider testing essential enough to be worth fixing (unlikely), or they are unaware that these tests exist (likely).

Either this is caused by a broken testharness (should be fixed), or it's a bug in the SDL core (should be fixed) or a backend (should be fixed).
So eitherway, a change to SDL is inevitable.

If we had run these trivial steps (leading to segmentation fault) on CI, we'd create additional exposure for these kind of bugs, so more developers will hopefully try to fix it sooner.
Running tests on CI, also adds exposure for the existing test-harnesses themselves. It suggests that running tests as part of the development process is expected, leading to better code quality.

---

I think the first technical solution should be kept simple, but the (non-technical) goal should be to improve integration tests, to avoid bugs and regressions in the future (which would cause more work for maintainers, trouble for end-users and financial loss for developers using SDL).

**Comment by icculus** [comment]
> So SDL already has a problem which makes the test harness fail, which doesn't seem to have a bug report

Yes, that's my point: no one is maintaining these tests, and hasn't in years, which makes them a liability, not a benefit. It's likely it's not SDL that's buggy here, but the test itself.

This is before we get to "what happens when we try to test something that gets an incorrect result because of a buggy OpenGL driver and not SDL's use of OpenGL" and "what happens when we try to use OpenGL on GitHub's CI virtual machines".

Also: tests are useless when they work in our comfortably static CI environment but don't catch the real problems we actually hit: bleeding edge Linux distros, niche X11 window managers, someone showing up with a _littleendian_ PowerPC machine, win32 code that doesn't work the same in Wine--or Windows 10--mouse cursors acting strange over Microsoft Remote Desktop, etc, etc.  Things we can't easily test, and things we would never conceive of testing in the first place.
