### ISSUE TITLE
Joystick rumble continues even after `duration_ms`, if `SDL_JoystickUpdate` is not called (since SDL 2.0.12)

### ISSUE THREAD

**Issue by JayFoxRox** [libsdl-org/SDL#4300]
*(I'm not sure where the change from 6efebf176852a3bfedb57d81c409270cbeb4714f was originally discussed; links would be appreciated)*

This problem came up during PR review of a joystick driver backend implementation in a port of SDL 2.0.9.
During code review we spotted a potential problem in SDL 2.0.12 and higher.

We did not verify if this problem exists in practice (yet), but I'm confident that this is a bug that can actually be triggered, so here's a bug report.

**Discussion of new code + problem**

While [commit 6efebf176852a3bfedb57d81c409270cbeb4714f simplified the backend](https://github.com/libsdl-org/SDL/commit/6efebf176852a3bfedb57d81c409270cbeb4714f), it also potentially introduced a new kind of bug.

The new code moves the responsibility to stop the rumble (after ~`duration_ms`) to the application using SDL, particularily as part of `SDL_JoystickUpdate`:

https://github.com/libsdl-org/SDL/blob/6efebf176852a3bfedb57d81c409270cbeb4714f/src/joystick/SDL_joystick.c#L1243-L1251

This means that if the user is not calling the update function often enough, then the rumble might continue for much longer than expected.

This is made worse, because `SDL_JoystickRumble` is typically implemened as synchronous function which does not require `SDL_JoystickUpdate` to trigger the rumble effect.
So if the user simply omits `SDL_JoystickUpdate` from their mainloop, then joystick rumble can be started, but it will not stop automatically.

Similarly this can happen if a long blocking event prevents joystick updates. Imagine this:

- User is in main menu and presses "A"-button to select "Start game".
- Gamepad is meant to vibrate for a short time (100ms) to provide feedback to user, so rumble is started.
- Now the application starts loading the game which takes 5 seconds, which blocks the main thread in a `loading()` routine.
    (&rarr; SDL is no longer updated during the loadscreen = rumble doesn't stop until loading finished).

In that situation, the new code might rumble for 5 seconds instead of 100ms.
*(SDL aside, this problem is so common with games, that you probably already experienced some form of it in the past)*

**Discussion of old code + how some backends prevented it**

The old code could avoid this bug in some backends (which may or may not be part of the SDL upstream tree) because they use effect-APIs on the haptic device. Such APIs upload effects (basically waveforms/curves to control motors) to the input device once, and then they only triggers playback of the waveform on the device to start force-feedback.
For such effect-API, it also means that the duration is part of the effect which is stored in the device. So timekeeping is also typically done on the device, not on the host.
Therefore, with the old code, the SDL application was not responsible for polling to stop the rumble, and the rumble stopped, even if the application became unresponsive (temporarily or permanently).

**How to fix this**

There should probably be an asynchronous timer which stops the rumble, or the old interface should be exposed, so effect-APIs can be used more effectively.

**Comment by Sanchocore2103** [comment]
Hab's

**Comment by slouken** [comment]
This bug would have existed prior to that refactoring, because at least with the existing drivers, they were all updated by a call to `SDL_JoystickUpdate `.

I agree this is a potential issue and should be fixed.

Do you have a backend implementation that would use the duration parameter, or would that be better implemented at a higher level?

**Comment by JayFoxRox** [comment]
> Do you have a backend implementation that would use the duration parameter, or would that be better implemented at a higher level?

At the moment I only care about state-based APIs to control the hardware (specifically, our backend is for original Xbox).
However, for other projects I have used effect-based APIs which have a duration parameter.

I could imagine, that in science or the simulation domain, where you are dealing with powerful motors / actuators for force-feedback, most of the control should probably remain on the driver side (outside of SDL) to give very low latency and avoid any problems if the rest of the machine were to crash.
Hence, effect based APIs are probably more common in those fields.
That said, I think it's uncommon for them to be using the joystick interface - they'd likely just use the haptic code directly.

I'd just keep it simple and stupid for now.

**Comment by slouken** [comment]
I can't think of a simple solution that doesn't involve adding a thread to handle rumble, which has other risks regarding starvation and race conditions.

Any ideas?

**Comment by slouken** [comment]
We don't have a good general solution for this. I went ahead and added documentation for this limitation.

Feel free to reopen this if you have any suggestions.
