### ISSUE TITLE
CMake build of git code on Linux produces libSDL2-2.0.so.*1*

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/SDL#4310]
Instead of libSDL2-2.0.so.**0**

This makes testing git vs release versions hard. The autotools build doesn't seem to do this.

Apparently caused by 350f1b0d1697715a4bbcf407b2288f87099b6c1b, more specifically `set(SDL_INTERFACE_AGE 1)` (line 57).
Because that's used to set `LT_REVISION` in https://github.com/libsdl-org/SDL/blob/d4e96e1153906c458a53c38ccc11a3b64b0dc06a/CMakeLists.txt#L68
Which is then used for the `SOVERSION` in https://github.com/libsdl-org/SDL/blob/d4e96e1153906c458a53c38ccc11a3b64b0dc06a/CMakeLists.txt#L2485

@slouken @philippwiesemann  is this intentional?

**Comment by icculus** [comment]
I think this is unintentional; I'll look at what configure does here and match this up.
