### ISSUE TITLE
SDL_RenderSetScale seems incorrect for more 25 or greater

### ISSUE THREAD

**Issue by DeafMan1983** [libsdl-org/SDL#4311]
Hello everyone,

I found bug in SDL_RenderSetScale()
If X + Y are over then 50 int then it looks ugly when I use C# oe Java
![image](https://user-images.githubusercontent.com/57066679/115161271-12c2d480-a09d-11eb-8135-79aa45920f27.png)
Renderer Width and Height are 200 length.
But yellow rectangle is really incoorect for scale
Rectangle : X = 32, Y = 32, Width = 136, Height = 136 + Scale = 16 ==> Incorrect drawing.. Like 32 + 136 + 32 = 200 and scale is 16.
Rectangle : X = 50, Y = 50, Width = 100, Height = 100 + Scale = 25 ==> Correct drawing. Like 50 + 100 + 50 = 200 and scale is 25.

Under Ubuntu 20.04
I have downloaded from libsdl source.

I tell how do I draw correct like that:
```
            SDL2.Rectangle rectangle2 = new SDL2.Rectangle
            {
                X = 4,
                Y = 4,
                Width = 192,
                Height = 192
            };
            renderer.DrawRectangle(rectangle2, 0, 255, 0, 255, 2f);
```

I made SDL2 for C# with object oriented programing like GtkSharp 2 / 3 or SMFL.Net
I made simple DrawRectangle()
```
        public void DrawRectangle(Rectangle rectangle, byte red, byte green, byte blue, byte alpha, float scale)
        {
            SDL_RenderSetScale(Handle, scale, scale);
            SDL_Rect internal_rect = new SDL_Rect
            {
                x = (int)(rectangle.X / scale),
                y = (int)(rectangle.Y / scale),
                w = (int)(rectangle.Width / scale),
                h = (int)(rectangle.Height / scale)
            };
            SDL_SetRenderDrawColor(Handle, red, green, blue, alpha);
            SDL_RenderDrawRect(Handle, ref internal_rect);
        }
```

But It looks like weird drawing.

I have tried to use normal SDL2-CS = No success....

Thanks!

**Comment by DeafMan1983** [comment]
No replies????????

What does it happen with SDL2 for Ubuntu 20.04?

And SDL_GL_GetProcAddress can't find to libGL.so.1 If I use Ubuntu 20.04.2 

PLEASE REPLAY ME! I WAIT LONGER FOR RESULTS. Thanks for understanding!

**Comment by lacc97** [comment]
It seems to me your issue is with this part:
```
x = (int)(rectangle.X / scale),
                y = (int)(rectangle.Y / scale),
                w = (int)(rectangle.Width / scale),
                h = (int)(rectangle.Height / scale)
```

You are scaling down and truncating the result of the division. So when the renderer  scales them up again you don't actually get back your original dimensions.

**Comment by 1bsyl** [comment]
@DeafMan1983 is this solved ? 
or do you have a full test-case in C  ?
