### ISSUE TITLE
Remove wl_shell support

### ISSUE THREAD

**Issue by bl4ckb0ne** [libsdl-org/SDL#4322]
The `wl_shell` protocol is officially [deprecated][1], and its support should be dropped. 

One of the breaking change that comes in mind would be the `shell_surface` field in [SDL_syswm.h][2] that should be replaced with a `xdg_surface` since the `xdg_shell` protocol is [stable][3]. 

The `xdg-shell-unstable-v6` protocol support should also be dropped, or labeled deprecated.

[1]: https://cgit.freedesktop.org/wayland/wayland/tree/protocol/wayland.xml#n1040
[2]: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/include/SDL_syswm.h#L292
[3]: https://cgit.freedesktop.org/wayland/wayland-protocols/tree/stable/xdg-shell/xdg-shell.xml

**Comment by flibitijibibo** [comment]
I would be okay with removing both of these, but I never really checked to see who was using what. I _think_ Ubuntu 18.04 still uses the v6 protocol, but then again I think 18.04 also uses the old kwin decoration extension which we removed just recently. I have no idea who is using shell but we did have this in the source:

https://github.com/libsdl-org/SDL/blob/8e3ec34d34af6aa3348b0dd9bbd3d8dee246e819/src/video/wayland/SDL_waylandwindow.c#L139-L142

If it were up to me, I would cut anything that's not necessary as of Ubuntu 20.04, as I imagine anyone using anything older will be using X instead. If there are any users of these protocols, now would be a good time to bring up the use case...

**Comment by bl4ckb0ne** [comment]
Sway dropped the support of `xdg-shell-unstable-v6` and `wl-shell` a while ago. I think `xdg-shell` should be good on 18.04, the protocole has been stable for a while. 

I already have WIP to drop the `wl-shell` support, I'll push it publicly if the decision is made to go forward.

**Comment by flibitijibibo** [comment]
@icculus, I checked the logs and it seems like one way to deal with this would be to require Wayland 1.12, released in 2017 with the xdg-shell protocol included. Do we just want to set that as the minimum so older setups fall back to X? That seems like it'd be a good way to strip a lot of the historical cruft while almost keeping the experience the same for those older setups, which are presumably either running X or currently running with SDL's x11 driver anyway.

**Comment by icculus** [comment]
Let's definitely not remove anything before 2.0.16 ships.

**Comment by bl4ckb0ne** [comment]
What's the ETA for 2.0.16? I'll push the patch as draft later so we dont forget about it.

**Comment by icculus** [comment]
ETA for 2.0.16 is May 21st. I've already marked this issue for 2.0.18, so it definitely won't be forgotten. If you push a patch, reference this issue, please!

**Comment by flibitijibibo** [comment]
Resolved by #4323 (Dangit GitHub this one was tagged)
