### ISSUE TITLE
Wayland: OpenGL window resize event unnecessarily delayed until next buffer swap

### ISSUE THREAD

**Issue by mstoeckl** [libsdl-org/SDL#4326]
Reported in version: SDL 2.0.14, and latest git version as of 2021-04-22
Reported for operating system, platform: Linux, x86_64

The SDL wayland backend currently handles resize events windows slightly different than the X11 backend. Specifically, say an application creates a OpenGL window, which it redraws only in response to input events. (For example, a main menu without any animations.) If you resize the window, then the `SDL_WINDOWEVENT_RESIZED/SIZE_CHANGED` events are delayed until the next time that `SDL_GL_SwapWindow` is called, which only occurs after the application is given some reason to redraw itself., so the window remains "stuck" drawn at the wrong size for a while. Under X11, the  `SDL_WINDOWEVENT_RESIZED/SIZE_CHANGED` events would be provided immediately, and the window could be redrawn as it is resized.

I've attached a test program with which this bug can be seen. Each time the window is redrawn it uses a different color; keypresses and resize events both should cause a redraw. 
[delayed_resize_event.c.txt](https://github.com/libsdl-org/SDL/files/6362294/delayed_resize_event.c.txt)

This can be fixed by immediately applying resize events with OpenGL windows, as with the following patch.

```diff
diff --git a/src/video/wayland/SDL_waylandopengles.c b/src/video/wayland/SDL_waylandopengles.c
index 5da365c8..b5390cfc 100644
--- a/src/video/wayland/SDL_waylandopengles.c
+++ b/src/video/wayland/SDL_waylandopengles.c
@@ -68,9 +68,6 @@ Wayland_GLES_SwapWindow(_THIS, SDL_Window *window)
         return -1;
     }
 
-    // Wayland-EGL forbids drawing calls in-between SwapBuffers and wl_egl_window_resize
-    Wayland_HandlePendingResize(window);
-
     WAYLAND_wl_display_flush( data->waylandData->display );
 
     return 0;
diff --git a/src/video/wayland/SDL_waylandwindow.c b/src/video/wayland/SDL_waylandwindow.c
index c06616bd..1b5f90a0 100644
--- a/src/video/wayland/SDL_waylandwindow.c
+++ b/src/video/wayland/SDL_waylandwindow.c
@@ -182,9 +182,7 @@ handle_configure_wl_shell_surface(void *data, struct wl_shell_surface *shell_sur
     wind->resize.height = height;
     wind->resize.pending = SDL_TRUE;
 
-    if (!(window->flags & SDL_WINDOW_OPENGL)) {
-        Wayland_HandlePendingResize(window);  /* OpenGL windows handle this in SwapWindow */
-    }
+    Wayland_HandlePendingResize(window);
 }
 
 static void
@@ -232,9 +230,7 @@ handle_configure_zxdg_shell_surface(void *data, struct zxdg_surface_v6 *zxdg, ui
         wind->resize.pending = SDL_TRUE;
         wind->resize.configure = SDL_TRUE;
         wind->resize.serial = serial;
-        if (!(window->flags & SDL_WINDOW_OPENGL)) {
-            Wayland_HandlePendingResize(window);  /* OpenGL windows handle this in SwapWindow */
-        }
+        Wayland_HandlePendingResize(window);
     }
 }
 
@@ -348,9 +344,7 @@ handle_configure_xdg_shell_surface(void *data, struct xdg_surface *xdg, uint32_t
         wind->resize.pending = SDL_TRUE;
         wind->resize.configure = SDL_TRUE;
         wind->resize.serial = serial;
-        if (!(window->flags & SDL_WINDOW_OPENGL)) {
-            Wayland_HandlePendingResize(window);  /* OpenGL windows handle this in SwapWindow */
-        }
+        Wayland_HandlePendingResize(window);
     }
 }
 
@@ -495,9 +489,7 @@ update_scale_factor(SDL_WindowData *window) {
        window->resize.height = window->sdlwindow->h;
        window->resize.scale_factor = new_factor;
        window->resize.pending = SDL_TRUE;
-       if (!(window->sdlwindow->flags & SDL_WINDOW_OPENGL)) {
-           Wayland_HandlePendingResize(window->sdlwindow);  /* OpenGL windows handle this in SwapWindow */
-       }
+       Wayland_HandlePendingResize(window->sdlwindow);
    }
 }
```
</details>

It no longer appears to be the case that "Wayland-EGL forbids drawing calls in-between SwapBuffers and wl_egl_window_resize", as mentioned by the late 2018 patch that (among other changes) introduced this behavior (48917e0e709d0f8efb7a0c476bb96652e1dd4ba3, https://github.com/libsdl-org/SDL/issues/3056). Mesa seems to have fixed the underlying problem since then, with (presumably) the following change from early 2019: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/252 .

**Comment by flibitijibibo** [comment]
This makes sense to me, but I would be worried that this causes regressions for older LTS systems. Maybe this can be part of 2.0.18 when we start ripping out the old/deprecated stuff, will defer to @icculus on this one.

**Comment by icculus** [comment]
Let's wait for 2.0.18, but let's definitely rip this out at that point. I was never really thrilled about this workaround. Flagging this for the 2.0.18 milestone so we remember to do it.

**Comment by DeafMan1983** [comment]
@flibitijibibo but Ubuntu 18.04 is unstable now. Because libGL seems disabled and I have upgraded to Ubuntu 20.04 and I see like SDL2 Window Resizable if you resize edge of SDL Window and it jumps weird commonly.

Also X11 has bug too.

**Comment by mstoeckl** [comment]
> if you resize edge of SDL Window and it jumps weird commonly. [...] Also X11 has bug too.

Sorry, it's not clear what you mean here. If your program has the same behavior resizing on X11 as with Wayland, then this specific issue does not apply. You can check whether or not this issue affects you by trying the suggested patch. Typical programs using OpenGL will always redraw the window at e.g. 60fps, in which case the behavior described in this issue is very hard to notice.

**Comment by flibitijibibo** [comment]
After doing a lot of testing and research, I'd like to propose that this be bumped to 2.0.16. I previously suggested this could be an issue for systems with Mesa versions prior to 18.3.5, but in looking around I was unable to find _any_ supported distribution that fulfilled the following requirements:

- Wayland officially supported
- Mesa 18.3.5
- Not completely EOL

I mentioned CentOS/RHEL 7 as a possible concern, but this turned out to be bogus - the Wayland client version is _very_ old on 7 and is not actually recommended there, at most presented as a "Technology Preview" for RHEL (in contrast, 8 onward has Wayland as the default!). libdecor doesn't even compile there, and that would have been necessary to properly support it anyway. I don't even think a system SDL package would even be updated in this case (it's probably not even 2.0.14...).

With all that in mind, I don't see any reason to put this off to 2.0.18.

**Comment by DeafMan1983** [comment]
Wait X11 has nothing bug and I have made X11 in C#. It works fine but
multiple drawings like X11 's DrawRectangles()

**Comment by icculus** [comment]
> Wait X11 has nothing bug and I have made X11 in C#. It works fine but multiple drawings like X11 's DrawRectangles()

I don't understand what this means; this bug is about fixing Wayland resizing.

**Comment by flibitijibibo** [comment]
Great! @mstoeckl, do you have time to turn your original patch into a PR?

**Comment by dos1** [comment]
As the author of the commit that introduced this behavior, just wanted to say I'm glad to see that it can be got rid of :)

**Comment by icculus** [comment]
I took care of it.
