### ISSUE TITLE
Possible to keep creating mapping for android gamepad even without axis?

### ISSUE THREAD

**Issue by Benau** [libsdl-org/SDL#4327]
![IMG_0139](https://user-images.githubusercontent.com/3252341/115857499-5bdda480-a460-11eb-9d38-33cbb215a368.JPG)
For this type of gamepad for example, the "axis" on the LHS mapped into 4 dpad directions

Will SDL upstream accept that:
```
    if (!(button_mask & face_button_mask) || !axis_mask) {
        /* We don't know what buttons or axes are supported, don't make up a mapping */
        return NULL;
    }
```
change into:
```
    if (!(button_mask & face_button_mask)) {
        /* We don't know what buttons are supported, don't make up a mapping */
        return NULL;
    }
```
In the past it worked and regression found at https://github.com/libsdl-org/SDL/commit/1a17ab30e17f22c390caa1403f32dfac03532dff

**Comment by slouken** [comment]
Yep, that's fine. :)
