### ISSUE TITLE
On SwayVM window doesn't show up without calling SDL_GetWindowSurface

### ISSUE THREAD

**Issue by soratobukuroneko** [libsdl-org/SDL#4332]
I just started learning (Py)SDL2 and I encountered an issue with minimal code examples: the window doesn't show up. If I add a call to `SDL_GetWindowSurface`, then the code works as expected.

Is it required to call `SDL_GetWindowSurface` to get the `window.show` function working? Or is it a bug?

There are a similar issue reported there marcusva/py-sdl2#139

**Comment by soratobukuroneko** [comment]
Doesn't work:

```C
#include <SDL.h>

int main(int argc, char ** argv) {
    SDL_Init(SDL_INIT_VIDEO);
    SDL_CreateWindow(
            "Hello, World!",
            SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
            800, 600,
            SDL_WINDOW_SHOWN
    );
    SDL_Delay(2000);

    return 0;
}
```

**Comment by flibitijibibo** [comment]
From what I understand this is an intentional Wayland feature - you need to call some kind of presentation function at least once before the compositor will draw the window.
