### ISSUE TITLE
keypad arrow key key codes are sent incorrectly

### ISSUE THREAD

**Issue by dpadgett** [libsdl-org/SDL#4336]
i think it happened since this commit: https://github.com/libsdl-org/SDL/commit/f867cebbd4c63221759edf9c613935a574ec7f27
with num lock off, kp_2, kp_4, kp_6, and kp_8 key events are sent with scancodes of the regular arrow keys instead of the numpad scancodes
only observed / tested it on windows 10

**Comment by cgutman** [comment]
Did you test 2.0.14? I fixed this bug in 771732ed32a3077c85d92c5d4f3d61497e64588d

**Comment by dpadgett** [comment]
yeah i verified that it still occurs on the latest SDL2.dll

**Comment by dpadgett** [comment]
you are right!  i accidentally overwrote the 2.0.14 dll before testing with it.  oops :).
