### ISSUE TITLE
SDL_vulkan_utils.c:91:14: error: 'VK_ERROR_INCOMPATIBLE_VERSION_KHR' undeclared

### ISSUE THREAD

**Issue by shoober420** [libsdl-org/SDL#4337]
I'm trying to compile libsdl2 from git master (https://github.com/libsdl-org/SDL/commit/9727655b896b69e73b187815d0a4e1fc68701128) on gentoo. I'm encountering a build error. Log is attached.

SDL_vulkan_utils.c:91:14: error: 'VK_ERROR_INCOMPATIBLE_VERSION_KHR' undeclared (first use in this function); did you mean 'VK_ERROR_INCOMPATIBLE_DISPLAY_KHR'?

[libsdl2-9999.txt](https://github.com/libsdl-org/SDL/files/6379235/libsdl2-9999.txt)

**Comment by 1bsyl** [comment]
@shoober420 maybe, this should fix the compilation, can you double-check ?

**Comment by shoober420** [comment]
@1bsyl 

w00t!

This fixed the build.

sdl2-9999 is now a thing is anyone wants to try it on gentoo.

https://github.com/shoober420/shoober420-overlay/tree/main/media-libs/libsdl2
