### ISSUE TITLE
Distortions on resampled audio

### ISSUE THREAD

**Issue by vitor-k** [libsdl-org/SDL#4342]
I've bisected this commit b98b5adcaea159fc6a9753f808875acf7d3ee945 as the cause of audio problems on resampled audio when I was testing building SDL from source for Citra.
The audio gets distorted, with much higher pitch, and sometimes clipping. The sample rate of the original 3ds audio is 32728 Hz.

(will enter more information in a bit, accidentally published in the middle of writing)

**Comment by vitor-k** [comment]
Ok, so I had a look at the implementation used in the example on the wiki and compared to how it is in citra's code, and the flag SDL_AUDIO_ALLOW_FREQUENCY_CHANGE stood out to me. 
When the flag was removed, the audio went back to being resampled normally.

What I take from this is that when the flag is present, the audio shouldn't be resampled, but WASAPI was resampling it anyway, causing the behavior reported above.
If that's the case, this issue can be closed and I'll fix the code on citra's side.

**Comment by icculus** [comment]
`SDL_AUDIO_ALLOW_FREQUENCY_CHANGE` tells SDL "I want this frequency, but I can handle whatever you can give me," which is to say: it's telling SDL that _you_ have a resampler of your own.

I would assume when SDL_OpenAudioDevice returns with that flag set, the `obtained.freq` is set to something like 48000 and not 32728.

As you've discovered, leave that flag off and always feed the audio callback data sampled at 32728 and you should be okay.
