### ISSUE TITLE
Will SDL be part of some future GSOC event?

### ISSUE THREAD

**Issue by Axilot** [libsdl-org/SDL#4343]
As the title says, i am wondering if there would be a chance of seeing SDL as a project on the GSOC event.

**Comment by icculus** [comment]
We have participated over several years in the past, and while some of the work was amazing, it was a lot of effort to mentor and most of the results were not great.

I would be inclined to say we won't participate again. The organization application deadline for the year is already passed in any case, but to be honest: for the right proposal, maybe I'd change my mind next year.
