### ISSUE TITLE
windows do not restore to floating from maximised mode

### ISSUE THREAD

**Issue by christianrauch** [libsdl-org/SDL#4345]
Windows on Wayland do not restore to their floating mode after being unmaximised.

1. run an example with resizable window, e.g. `./testsprite2 --resizable`
2. press `Ctrl+M` to maximise
3. press `Ctrl+M` again to restore to floating

The key combination `Ctrl+M` should toggle between maximised and floating mode, but the test window stays in maximised mode.

This works as expected with the `libdecor` extension (https://github.com/libsdl-org/SDL/pull/4068) where the window correctly switches between maximised and floating mode.

**Comment by flibitijibibo** [comment]
The part that matters:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandwindow.c#L831
