### ISSUE TITLE
multiple window will close at once if one of them is closed

### ISSUE THREAD

**Issue by christianrauch** [libsdl-org/SDL#4348]
Under some condition, when closing one of many open windows, the process will crash and all windows will be closed.

1. `SDL_VIDEODRIVER=wayland ./testgl2 --windows 4`
2. switch to the activity overview in GNOME Shell (Meta / Win key)
3. close one of the 4 windows

This issue is not properly reproducible.

**Comment by flibitijibibo** [comment]
Closer's not too special: https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandwindow.c#L439

Maybe it fires twice or something, I don't know how many events there are for resources being closed by UI.

**Comment by christianrauch** [comment]
The issue appears in https://github.com/libsdl-org/SDL/blob/7b284dbb34a8c34f5d6f79c58c860c9f7894fd56/src/video/wayland/SDL_waylandwindow.c#L212 when the frame callback is added.

It looks like `wl_surface_frame(wind->surface)` returns NULL here. Maybe because the `surface` was destroyed earlier?

**Comment by flibitijibibo** [comment]
We may need to guard that with something indicating the window's already closed - I forget if there's a built-in flag for that.

**Comment by christianrauch** [comment]
@icculus PR https://github.com/libsdl-org/SDL/pull/4352 fixes the issue for me. I opened 20 windows 4 times and could close all of them without the process crashing.

**Comment by icculus** [comment]
I'm wondering if it fixed it, or just made the race condition smaller, though.

**Comment by flibitijibibo** [comment]
I don't think it'll race, since AFAIK these callbacks will only occur during a dispatch, so a destroy would have to happen while the callbacks are happening. I think we were just hitting a case where a destroy happens, then the next PumpEvents tries calling stuff that _should_ have been destroyed but weren't in the previous frame's events.

The destroy call might need a NULL check, but it makes sense to me aside from that.

**Comment by icculus** [comment]
oh, I thought this was for the PR that i merged this morning. My bad, this probably _does_ fix it.
