### ISSUE TITLE
Pressing Win+Space will break the keyup event for the Windows key

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#4369]
**The issue:**

Using the Windows language switcher (`Win+Space`) will make SDL think that the Win key is held down, even when it isn't. The "held down" state is released when the SDL window loses focus, or when you press and release the Win key again.

**Repro steps:**

1. Have at least 2 Windows input languages
2. Run the sample program
3. Press `Win+Space` (the language switcher should open) 
4. Observe that when you release the Win key, the language switcher will close, but the keyup event won't arrive

**Remarks:**

Other Win-hotkeys (such as `Win+A`) don't cause this bug.

The bug doesn't occur if the language popup is dismissed by clicking or by pressing `Esc`.

The popup doesn't take window focus from the SDL window (the window will appear to be in focus), but it takes keyboard focus (pressing keyboard keys doesn't produce SDL_KEYUP/DOWN events).

**Code to test:**

Sample program that will output to SDL log and show the last Windows key keyup/down event on screen as color.
https://gist.github.com/Susko3/b93e7e0a2c2998e79a312d6d1e40fa69

**Comment by Susko3** [comment]
Also happens with the Game Bar (<kbd>Win</kbd>+<kbd>G</kbd>). The Game Bar also takes keyboard focus, but will leave the active window in a focused state.

If the Game Bar takes some time to load, releasing <kbd>Win</kbd> before the Game Bar appears will normally send a keyup for <kbd>Win</kbd>.

**Comment by slouken** [comment]
This is fixed by https://github.com/libsdl-org/SDL/commit/3b85e3fdfce01c528a6ebf9ac537bdc106ba4963, thanks!
