### ISSUE TITLE
Proposal to add SDL_Texture userdata API

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#4370]
Just like SDL_Surface userdata

Sorry, this content comes from Google Translate!

**Comment by slouken** [comment]
Added in https://github.com/libsdl-org/SDL/commit/f5794f9eebaac3e70d4fc849641f30bc36913367, thanks!

**Comment by baidwwy** [comment]
Hi @slouken 
I have a question
Does SDL_CreateTexture need to add texture->userdata = NULL;
