### ISSUE TITLE
Documentation: SDL_LockAudioDevice/UnlockAudioDevice guidlines for drivers.

### ISSUE THREAD

**Issue by isage** [libsdl-org/SDL#4371]
So, most of the audio drivers are using SDL_AudioLockDevice_Default which uses mutexes, which are recursive. So, historically, calls to SDL_LockAudio are recursive too. But there seems to be no documentation on whether LockDevice/UnlockDevice driver funcs should actually be recursive or not.

That question raised because of n3ds sdl1.2 port, which uses non-recursive locks, so it's not clear if that should be considered a bug in that port or totally legal.

**Comment by icculus** [comment]
My thinking is that these probably need to require recursive locks since most platforms are already allowing them (albeit undocumented) but I am almost certain in the 1.2 era it was explicitly forbidden to double-lock a device. I'll do some research and report back.

**Comment by slouken** [comment]
Yes, to sum up, SDL now requires a recursive mutex implementation and the audio subsystem allows nested lock/unlock pairs.

**Comment by icculus** [comment]
I believe the sticking point was some platforms (classic Mac OS, etc) used hardware interrupts for the audio callback and locking got complicated then, but all that's gone in SDL2.
