### ISSUE TITLE
[feature request] Implement an equivalent to glfwRequestWindowAttention

### ISSUE THREAD

**Issue by Jupeyy** [libsdl-org/SDL#4372]
We'd like to remove x11 dependencies for native wayland support, but this function we strumbble on.
Someone who knows a bit about WM said, wayland doesn't really have a demand/urgency function yet, but atleast there is an issue about it on wayland's side (https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/31).

Would also be nice to have less #ifdef WINDOWS or other OS branches.
It also doesn't matter if the function would fail IMO, still better than not having it.

(if this was asked before i tried to quick-search "attention", "demand", "urgency" etc. didnt find anything)

**Comment by flibitijibibo** [comment]
You want SDL_RaiseWindow and xdg-activation. This is a very new spec though, so you will need a bleeding-edge build of a desktop that support it to write and test this.

**Comment by Jupeyy** [comment]
I've no idea, if that function changed lately, but from description it sounds different. I basically just want the taskbar icon blinking or however the wm implements it, not activate it automatically.
On windows and KDE it would just blink at least

**Comment by flibitijibibo** [comment]
RaiseWindow is usually a request, while SetWindowInputFocus is a demand. For Wayland, xdg-activation will raise if it thinks it's appropriate, otherwise it will either drop the request or simply point out that it wanted focus. In any case you probably want to be at wayland-protocols, this is in the TODO for #4306.

**Comment by Jupeyy** [comment]
Ok, maybe I don't directly understand your points, but it sounds like these function would try to set windows focus or raise the window.
But I want the users attention, not anything directly window managment related, more like a visual signal for the user.
I can't explain it really better, if you ever used a chat programm on windows or KDE you might understand.
It's basically like the manual says for glfwRequestWindowAttention:

```
This function requests user attention to the specified window. 
On platforms where this is not supported, attention is requested to the application as a whole.

Once the user has given attention, usually by focusing the window or application,
the system will end the request automatically.
```

We currently use SDL and have this function customly made for x11 and windows, but would be nice to have it inside of SDL, so we have no x11 dependencies.
Since glfw implements it, I guess it would fit SDL too, and we wouldn't require todo some shared library hacks on our side.

**Comment by flibitijibibo** [comment]
Looks like the implementations are one line each. Since you already have it written you can add a new function if you want, at minimum we will probably need Windows, Cocoa, and X11, with Wayland to come later with the RaiseWindow implementation (see xdg-activation's set_serial API).

**Comment by flibitijibibo** [comment]
SDL_RaiseWindow has been implemented for Wayland as of the latest revision. This is probably as good as it'll get without writing a new SDL_FlashWindow function.

**Comment by slouken** [comment]
An SDL_FlashWindow() function is probably worth adding. @Jupeyy, would you like to create one and submit a pull request?

**Comment by Jupeyy** [comment]
> An SDL_FlashWindow() function is probably worth adding. @Jupeyy, would you like to create one and submit a pull request?

I can try to implement a bare minimum(basically what we use on our project for X11 and Windows), but I don't feel confident enough to implement it good enough to make it actually cross platform and/or respect all edge cases/error handlig from these OS.

**Comment by flibitijibibo** [comment]
> > An SDL_FlashWindow() function is probably worth adding. @Jupeyy, would you like to create one and submit a pull request?
> 
> I can try to implement a bare minimum(basically what we use on our project for X11 and Windows), but I don't feel confident enough to implement it good enough to make it actually cross platform and/or respect all edge cases/error handlig from these OS.

Write what you know will work for your targets and I'll clean up for the rest, I can do Cocoa and Wayland and then the rest can be SDL_Unsupported() for now.

**Comment by flibitijibibo** [comment]
Working on Wayland support for this now, at which point this can be closed - Cocoa doesn't seem to have a window-specific API, it just flashes the entire app which is probably overkill.

**Comment by slouken** [comment]
> Working on Wayland support for this now, at which point this can be closed - Cocoa doesn't seem to have a window-specific API, it just flashes the entire app which is probably overkill.

Given that most games are single-window, flashing the entire app is probably appropriate on Cocoa.
