### ISSUE TITLE
Linux: enabling Video subsystem with vukan while disabling Dlopen gives compile-time errors

### ISSUE THREAD

**Issue by v1993** [libsdl-org/SDL#4373]
I've been trying to reduce build time of a project that builds SDL2 (via CMake) with it while using only very few of its subsystems. It turns out that configuration step runs correctly but `SDL_x11vulkan.c` fails to compile with rather confusing set of errors, like

```C
externals/SDL/src/video/x11/SDL_x11vulkan.c:47:5: error: unknown type name 'VkExtensionProperties'
   47 |     VkExtensionProperties *extensions = NULL;
      |     ^~~~~~~~~~~~~~~~~~~~~
```

IMO Vulkan should either be disabled in such situation or configuration step should error out.

**Comment by v1993** [comment]
@icculus Is CMake build also fixed? Linked commit doesn't appear to touch it.

**Comment by icculus** [comment]
Hmm, I'll check.
