### ISSUE TITLE
Does it support DualSense's adaptive triggers (and eventually haptic feedbacks)?

### ISSUE THREAD

**Issue by nougator** [libsdl-org/SDL#4379]
I saw that the support for the DualSense but does it support adaptive triggers? I can't find anything about it.

**Comment by icculus** [comment]
I believe we support the haptic triggers on the PS5 now (and offer an new API for it). This is only in revision control atm, I think, but does work as far as I know.

**Comment by icculus** [comment]
Oh, I thought this was asking about SDL_JoystickRumbleTriggers, sorry for the confusion!

**Comment by slouken** [comment]
We've added the officially supported API in https://github.com/libsdl-org/SDL/commit/d135c0762f11c29eb9cce377648f25e5a91b4522
