### ISSUE TITLE
[WinRT] Remove support for EOL targets

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#4382]
In going over the UWP target again recently, I realized that almost everything we have in VisualC-WinRT is long dead:

- WinRT 8.1 and WinPhone 8.1 are fully and totally unsupported; you can't even submit app updates anymore
- The NuGet metadata is unused, and a live package does not exist as far as I know
- The UWP project works, but is based on a long-dead VS version (unlike Win32 this actually matters)

Once 2.0.16 is released I'd like to do the following:

- Delete the nuspec/targets files, WinRT81_VS2013, and WinPhone81_VS2013
- Move the contents of UWP_VS2015 up one level
- Update the UWP project to Visual Studio 2019

Unlike Win32 where using older Visual Studio releases is possible (and probably a good idea, tbh), UWP is _far_ more aggressive about being on updated versions - you can't even connect to a device unless the VS debugger matches the Windows 10 version exactly, and on Xbox you _have_ to use the latest OS to be on the network at all! This means that you either always update the project files because you're forced to, or you try to use an old toolchain and now you can't run a debugger for reasons the IDE will never disclose unless you just happen to know about the versioning issue. The good news is that the VS version doesn't necessary align with SDK versions; as long as your sln and cpp targets are updated, you can still target 10240 if you want.

I can do all of this really easily, just throwing this out there in case someone has a super specific scenario where the above changes will cause any major issues. I'm thinking about cutting Windows 10 Phone as well but the EOL schedule for apps isn't entirely clear.

**Comment by icculus** [comment]
Pinging @DavidLudwig in case he has a concern, but otherwise this is 100% fine with me.

**Comment by slouken** [comment]
Go ahead and submit a pull request for this.

Thanks!
