### ISSUE TITLE
SDL_SetClipboardText doesn't register in certain applications, like Chrome in X11.

### ISSUE THREAD

**Issue by adamharrison** [libsdl-org/SDL#4384]
I think this is a MIME type issue; most applications seem to set multiple MIME types whenever a paste happens. Chrome doesn't seem to respond to UTF8_STRING, but it does respond to text/plain, so that's a possible fix.

**Comment by icculus** [comment]
I just want to note that I was able to copy/paste between Chrome and an SDL app on X11 before this change I just merged, and I don't know if that was something else changing or dumb luck on my part, but the change appears to be the right thing to do in any case.
