### ISSUE TITLE
Extend absolute devices support in SDL_evdev.c (other than touch screen)

### ISSUE THREAD

**Issue by lmerckx** [libsdl-org/SDL#4394]
Absolute coordinates (with min/max) are supported for touch screens but not for other devices (ex: mouse, trackball, ...).

Is it possible to extend the logic for these ?

Ex: The Mayflash Dolphinbar allows to use a wiimote as an absolute mouse but it has a very limited range !
X=0-512
Y=0-400
So, for the moment, this device doesn't allow to point a whole screen/window. 
As for touch screens, the min-max should be proportional to screen size.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
