### ISSUE TITLE
SDL_SetWindowIcon not setting a window icon on Linux with X11

### ISSUE THREAD

**Issue by isaboll1** [libsdl-org/SDL#4395]
It appears as though on my system (currently I am using Pop OS 20.10, with the "Dash to Dock" shell extension), any application, including the ones that I compile myself, do not set an icon when calling the "SDL_SetWindowIcon" function from SDL2

**Comment by icculus** [comment]
Installed Pop OS 21.10 in a virtual machine, "sudo apt-get install" all the Ubuntu dev packages from docs/README-linux.md, configure/make/make install, and added this to testsprite2.c:

```diff
diff --git a/test/testsprite2.c b/test/testsprite2.c
index 88419ffcf..949830ee7 100644
--- a/test/testsprite2.c
+++ b/test/testsprite2.c
@@ -96,6 +96,7 @@ LoadSprite(const char *file)
     /* Create textures from the image */
     for (i = 0; i < state->num_windows; ++i) {
         SDL_Renderer *renderer = state->renderers[i];
+        SDL_SetWindowIcon(state->windows[i], temp);
         sprites[i] = SDL_CreateTextureFromSurface(renderer, temp);
         if (!sprites[i]) {
             SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Couldn't create texture: %s\n", SDL_GetError());
```

...and the icon worked fine. Maybe Pop OS fixed something since 20.10?
