### ISSUE TITLE
Where is SDL.xcodeproj inside Xcode-IOS Folder ?

### ISSUE THREAD

**Issue by HelloKashif** [libsdl-org/SDL#4397]
The iOS build guide says that we need to open SDL.xcodeproj (located in Xcode-iOS/SDL) in Xcode.
But there is NO such file/folder

Ref: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/docs/README-ios.md

It was there until v2.0.10 and disappeared in the latest release

**Comment by 1bsyl** [comment]
now, the project is located in located in "Xcode/SDL"

**Comment by 1bsyl** [comment]
@HelloKashif : to easily build libs for iOS / tvOS, you may want to try this script: https://github.com/libsdl-org/SDL/issues/4410
