### ISSUE TITLE
Migration from 1.0.14 to 2.0.14, can not use SDL_OpenAudioDevice alone

### ISSUE THREAD

**Issue by buaabyl** [libsdl-org/SDL#4405]
My PC have two sound card. I found 2.x API have new api `SDL_OpenAudioDevice`

And I want to open second device alone, leaving first device closed.
But SDL do not playback audio (silence instead).

Code here

```c
    int dev_index = 1;
    const char* name = SDL_GetAudioDeviceName(dev_index, 0);

    SDL_zero(obtained);
    wavSpec.callback    = audioCallback2;
    wavSpec.userdata    = NULL;

    audioDevice = SDL_OpenAudioDevice(
            name,
            SDLX_PLAYBACK_DEVICE,
            &wavSpec, 
            &obtained,
            0);
    SDL_Delay(10);
    printf("open dev = %d\n", audioDevice);
```

But when I try to call `SDL_OpenAudio` before `SDL_OpenAudioDevice`, both two sound card play correctly.

```c
    wavSpec.callback    = audioCallback1;
    wavSpec.userdata    = NULL;
    SDL_OpenAudio(&wavSpec, NULL);
    audioDevice_default = 1;
    SDL_Delay(10);
    printf("open dev = %d\n", audioDevice_default);


    int dev_index = 1;
    const char* name = SDL_GetAudioDeviceName(dev_index, 0);

    SDL_zero(obtained);
    wavSpec.callback    = audioCallback2;
    wavSpec.userdata    = NULL;

    audioDevice = SDL_OpenAudioDevice(
            name,
            SDLX_PLAYBACK_DEVICE,
            &wavSpec, 
            &obtained,
            0);
    SDL_Delay(10);
    printf("open dev = %d\n", audioDevice);
```

Does this usage correct, or I have to open all devices?

**Comment by buaabyl** [comment]
<img width="782" alt="SDL_MixAudio_issue" src="https://user-images.githubusercontent.com/1212230/120186370-01e1b300-c246-11eb-9c16-c07c39f0c49f.png">

I fellow the API calling, and have found that the `SDL_MixAudio` API is misunderstanding......

**Comment by icculus** [comment]
SDL_MixAudio only works when a device is opened with SDL_OpenAudio (both are compatibility APIs from SDL 1.2), because it gets the audio format from the opened device.

Use SDL_MixAudioFormat() instead, which lets you specify the format of the audio data.

**Comment by buaabyl** [comment]
Thanks
