### ISSUE TITLE
Android: Should I create thread from Java or from SDL?

### ISSUE THREAD

**Issue by MikuAuahDark** [libsdl-org/SDL#4406]
This is more of a question rather than bug report.

As per title, should I create new thread using Java or using SDL functions?

According to SDL's `SDL_AndroidGetJNIEnv`, creating thread from Java thread will result in memory leak if this function is called. However, creating thread using SDL function causes the Java classpath not set properly which causes my program unable to resolve classes from JNI.

I'm open to any suggestions or solutions.

**Comment by icculus** [comment]
Paging @1bsyl: any advice here?

**Comment by 1bsyl** [comment]
@MikuAuahDark  
what about using SDL_SetEnv() to add more things to the  classpath ?

just wondering, if you call you JNI function from the main SDL, that should work, right ?

**Comment by MikuAuahDark** [comment]
> what about using SDL_SetEnv() to add more things to the classpath ?
Not sure how to do this one. Any pointers?

> just wondering, if you call you JNI function from the main SDL, that should work, right ?
Yes, calling the function that interacts with JNI (and my Android Java classes) in main thread is okay, but calling it from threads created by SDL is not.

**Comment by 1bsyl** [comment]
functions are:
```
 char *SDLCALL SDL_getenv(const char *name);
 int SDL_setenv(const char *name, const char *value, int overwrite);
```

display the "CLASSPATH" variable of the main thread, 
set the same thing, to your second thread !?

**Comment by MikuAuahDark** [comment]
Quick `getenv` call shows that `getenv("CLASSPATH")` returns NULL, so not sure how that approach works.

**Comment by 1bsyl** [comment]
@MikuAuahDark 
I think I have the same issue, but I don't know how to fix it.

As a workaround, it seems you can use "FindClass" and "GetStaticMethodId" (and others) from the main() function, and cache the variables.
And re-use them in your thread to call the JNI function.

**Comment by MikuAuahDark** [comment]
I guess that's the only way then.

I previously used that method but for some reason it causes JNI error despite my usage is _correct_. I'll try to look at that code more later, thanks.

<details>
<summary>For more information, feel free to ignore.</summary>
I probably hit some nasty bug and I probably dumb, but for some reason this simple code triggers JNI bug.

```cpp
// This function is called from SDL-created thread
HTTPSClient::Reply AndroidClient::request(const HTTPSClient::Request &req)
{
    JNIEnv *env = SDL_AndroidGetJNIEnv(); // SDL_AndroidGetJNIEnv is actually a variable (dlsym'ed)
    jclass httpsClass = findClass(env, "org.love2d.luahttps.LuaHTTPS");

    jmethodID constructor = env->GetMethodID(httpsClass, "<init>", "()V");
    jmethodID setURL = env->GetMethodID(httpsClass, "setUrl", "(Ljava/lang/String;)V");
    // ... some methodID getter code omitted

    jobject httpsObject = env->NewObject(httpsClass, constructor);

    // Set URL
    jstring url = env->NewStringUTF(req.url.c_str());
    env->CallVoidMethod(httpsObject, setURL, url);
    env->DeleteLocalRef(url); // ERROR: accessed stale Local followed by use of deleted local reference
    // ... rest of code omitted
}
```

As soon as I tried to release `url`, it complains about it being already deleted?

For more information, `findClass` is variable to function (loaded with `dlsym`) and that function is declared in another shared object as follows:

```cpp
extern "C" JNIEXPORT jclass findClass(JNIEnv *env, const char *name)
{
    jclass result = nullptr;

    if (classLoader) // classLoader is global ref, cached on main thread
    {
        jstring temp = env->NewStringUTF(name);
        result = (jclass) env->CallObjectMethod(classLoader, findClassLoader, temp); // findClassLoader is ClassLoader.getClass
        env->DeleteLocalRef(temp);
    }

    return result;
}
```

Any ideas what could probably wrong?

I can't use `env->FindClass` because the code that calls `AndroidClient::request` and the code that caches the global `classLoader` object is not in same thread.
</details>

**Comment by 1bsyl** [comment]
@MikuAuahDark : maybe you need to acquire global ref on the class objects ?
the method id also need to be found on the main thread ?

**Comment by 1bsyl** [comment]
@MikuAuahDark 
also, maybe there is a fix to this FindClass issue.
because FindClass of "java/lang/Class" is actually working.
So setting a CLASSPATH with SDL_setenv may solve that. Not sure which value it should points to...

**Comment by 1bsyl** [comment]
I re-open, so we think about investigating this.

**Comment by MikuAuahDark** [comment]
I don't think Android uses the `CLASSPATH` environment variables (and isn't environment variables is shared across process?), but from what I read:

* For Java-created threads, the classloader is set to the caller classloader (in this case, Android-specific classloader) which is able to resolve Android-specific classes.
* For C/C++-created threads (SDL counts), the classloader is set to "system" classloader. This classloader can't set resolve Android-specific classes.

**Comment by 1bsyl** [comment]
yes, this seems to be the reason ! 
just documented this, and closing the issue
