### ISSUE TITLE
Random high GPU usage on macos when using an OpenGL context

### ISSUE THREAD

**Issue by ellipticaldoor** [libsdl-org/SDL#4408]
So I'm getting a very strange random behaviour where sometimes my GPU usage its very high and sometimes just stays below 2%.

Right now I'm using an OpenGL context to make draw calls, you can see the code I'm using to reproduce this bug on this repo.

https://github.com/ellipticaldoor/sdl-opengl-high-gpu-usage-bug/blob/master/src/main.cpp

I isolated this down to just the SDL_GL_SwapWindow call, if you look at the screenshot you can see it's taking 26% of GPU usage just on its own. This is random, if I wait a couple of hours and come back de GPU usage will be around 2%.

I closed all other applications and processes to check this is not happening when other apps are open.

I'm using latest sdl2 version from brew 2.0.14_1 with macos catalina 10.15.7 and my GPU is Intel Iris Plus Graphics 1536 MB

![high gpu usage](https://user-images.githubusercontent.com/3449006/120303574-e074db80-c2c6-11eb-851c-13d9ad364381.jpg)

**Comment by icculus** [comment]
This is probably not an SDL bug.

**Comment by ellipticaldoor** [comment]
I just tried with glfw and I can see the same issue, so it's true it's not SDL2

I want to be sure, is this GPU usage normal or could be a macos or driver issue?

**Comment by slouken** [comment]
> I just tried with glfw and I can see the same issue, so it's true it's not SDL2
> 
> I want to be sure, is this GPU usage normal or could be a macos or driver issue?

It could be a macos or driver issue.

**Comment by ellipticaldoor** [comment]
I see, I believe that too.
