### ISSUE TITLE
Script to build SDL libs on iOS / tvOS 

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#4410]
Here is a basic script to automatically build the SDL library and the satellite libs for iOS / tvOS, configuration Debug/Release of Device/Simulator.

```
./ios_build_libs.sh -h
./ios_build_libs.sh: [--build | --clean | --state | --list] [--tvOS]
 build: re-compil with current sources
 clean: remove build directories
 state: see what's built
 list:  list xcode schemes & targets
```

It expects the directory SDL/SDL_image/ttf/mixer in the path named "PREFIX"
and install the libs in $PREFIX/SDL/{Debug,Release}-iphone{os,simulator}/

Attached script (.sh): [ios_build_libs.sh.txt](https://github.com/libsdl-org/SDL/files/9483389/ios_build_libs.sh.txt)

Old ticket: #1274

edit: update script

**Comment by sidshekar** [comment]
Where should I place this script to run it?

**Comment by 1bsyl** [comment]
this is hard-coded in PREFIX.

if you don't want to change anything.
create:
$HOME/release/Release_SDL_IOS/
put inside SDL sources, eg directories
SDL 
SDL_image
SDL_ttf
SDL_mixer
run the script from directory "$HOME/release/Release_SDL_IOS/"

let me know how it works for you, as may I have forgotten something
you also need the xcodebuild tools of xcode

**Comment by sidshekar** [comment]
I think I need to start with ...I am an absolute noob to SDL ...

So when you say put the directories in the release_SDL_ios, I think you mean the files in the build/ direftory that gets created once I run the iosBuild.sh file in the build-scripts directory. Because that was the only place I could find file called SDL_mixer... so I am guessing here.

Once I place the ios_build_libs.sh file (after removing the .txt from the file name) in the release_SDL_ios directory I run the script by ./ios_build_libs.sh file from it and I get permission denied. When I add sudo ./ios_build_libs.sh I get command not found. 

SO not sure what I am doing wrong.

**Comment by 1bsyl** [comment]
SDL, just a git clone of SDL tree/project. SDL_image for SDL_image tree.
etc. no need to use "iosBuild.sh".
you don't need to run it with sudo. but you need to add the right to execute, eg "chmod u+x" to the script

**Comment by sidshekar** [comment]
So I just cloned the SDL repo. I have SDL in the root directory along with the script and I get errors !!

  
![Screen Shot 2021-11-30 at 9 41 04 PM](https://user-images.githubusercontent.com/2862097/144013756-3b32903f-6452-43e6-9a72-6acc5f5f318b.png)

**Comment by 1bsyl** [comment]
once cloning, you should have the directory "Xcode/SDL/SDL.xcodeproj" in SDL/ 
the clone should be named "SDL"  in " $HOME/release/Release_SDL_IOS/"

**Comment by sidshekar** [comment]
Ok... I took the script and put it inside directory where xcode/sdl/sdl.xcodeproj is present and did --build. and I got build successfully. 

Now how would I go about using the new sdl project in creating an iOS and SDL project.

I just create a new iOS project. Add the new sdl project as a sub project. Delete all the main, appdelegate, sceneDelegate files. Create a new main.c with SDL code in and it will work??

Thanks millions!!!

**Comment by 1bsyl** [comment]
the script builds libraries of SDL. you can see what's build , and where, with "--list" option.
the you need to incorporate that with you project.... 

I personnally use CMake to have an xocde project for my application.
here some example, but you'll have to adapt it.

```
cmake_minimum_required(VERSION 2.8)

set(NAME "my_project_name")  
set(ID_NAME id_name)  
set(MACOSX_BUNDLE_BUNDLE_VERSION "1.01")
set(APP_ID 99999999)
project(${NAME})

set(CMAKE_INSTALL_NAME_TOOL /Applications/Xcode.app/Contents/Developer/usr/bin/install_name_tool)

add_definitions(-O2)
set(MY_IOS_ORIENTATION UIInterfaceOrientationPortrait)

# Take All headers and source files ! 
file(GLOB SOURCES *.c *.cpp *.mm common/*.c common/*.cpp common/*.mm)
file(GLOB HEADERS *.h *.hpp common/*.h common/*.hpp)
file(GLOB IMAGES *.png *.ttf *.wav APHONE.xcassets)

# Frameworks
set(IOS_FRAMEWORKS
   AudioToolbox
   ImageIO
   CoreGraphics
   QuartzCore
   UIKit
   OpenGLES
   MobileCoreServices
   AVFoundation
)

set(CMAKE_OSX_SYSROOT /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk)


set(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2")
set(CMAKE_OSX_ARCHITECTURES "armv7;arm64")

# ???
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -ObjC")

# to search some framework
#set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -F/Users/user/release/Release_SDL_IOS/SDL/Xcode/SDL")

foreach(FW ${IOS_FRAMEWORKS})
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -framework ${FW}")
endforeach()

# Weak link to GameController so that it runs on iPod 4
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-weak_framework,GameController")

include_directories(
   ${CMAKE_CURRENT_SOURCE_DIR}/
   ${CMAKE_CURRENT_SOURCE_DIR}/common/
   ${CMAKE_CURRENT_SOURCE_DIR}/../../../release/Release_SDL_IOS/SDL/include
   ${CMAKE_CURRENT_SOURCE_DIR}/../../../release/Release_SDL_IOS/SDL_image
   ${CMAKE_CURRENT_SOURCE_DIR}/../../../release/Release_SDL_IOS/SDL_mixer/include
   ${CMAKE_CURRENT_SOURCE_DIR}/../../../release/Release_SDL_IOS/SDL_ttf
   ${CMAKE_CURRENT_SOURCE_DIR}/../../../release/Release_SDL_IOS/SDL_ttf/external/harfbuzz-2.8.0/src
)

link_directories(
   ${CMAKE_CURRENT_SOURCE_DIR}/../../../release/Release_SDL_IOS/SDL
)

set(MACOSX_BUNDLE_PRODUCT_NAME ${NAME})

add_executable(
   ${NAME}
   MACOSX_BUNDLE
   ${HEADERS}
   ${SOURCES}
   ${IMAGES}
)

set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER "com.blabla.${ID_NAME}")

set_target_properties(${NAME} PROPERTIES RESOURCE "${IMAGES}")

set_target_properties(${NAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/../path_to..../IOS/Info.plist.in)

set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "iPhone Developer")

set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_DEVELOPMENT_TEAM "some_number")

set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_INSTALL_PATH "/Applications") 

set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET "9.0") 

set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_ASSETCATALOG_COMPILER_APPICON_NAME "AppIcon") 

target_link_libraries(${NAME} SDL2 SDL2_image SDL2_mixer SDL2_ttf)


```

**Comment by 1bsyl** [comment]
you generate an Xcode IOS project from the CMake file, with something like
```
cd your_app; // CMakeLists.txt is inside, with sources
mkdir build;
cd build;
cmake -GXcode ..
```

**Comment by 1bsyl** [comment]
At some point you'll need a template file named Info.plist.in
... but you need to get more familiar with apple stuffs ...

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleDevelopmentRegion</key>           <string>English</string>
<key>CFBundleExecutable</key>                  <string>${MACOSX_BUNDLE_EXECUTABLE_NAME}</string>
<key>CFBundleGetInfoString</key>               <string>${MACOSX_BUNDLE_INFO_STRING}</string>
<key>CFBundleIdentifier</key>                  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
<key>CFBundleInfoDictionaryVersion</key>       <string>6.0</string>
<key>CFBundleLongVersionString</key>           <string>${MACOSX_BUNDLE_BUNDLE_VERSION}</string>
<key>CFBundleName</key>                        <string>${MACOSX_BUNDLE_BUNDLE_NAME}</string>
<key>CFBundleDisplayName</key>                 <string>${NAME}</string>
<key>CFBundlePackageType</key>                 <string>APPL</string>
<key>CFBundleShortVersionString</key>          <string>${MACOSX_BUNDLE_BUNDLE_VERSION}</string>
<key>CFBundleSignature</key>                   <string>??????</string>
<key>CFBundleVersion</key>                     <string>${MACOSX_BUNDLE_BUNDLE_VERSION}</string>
<key>CSResourcesFileMapped</key>               <true/>
<key>NSHumanReadableCopyright</key>            <string>${MACOSX_BUNDLE_COPYRIGHT}</string>

<key>LSRequiresIPhoneOS</key>                         <true/>                            

<!--   With dont use encryption -->
<key>ITSAppUsesNonExemptEncryption</key>              <false/>

<!--   Allow Admob HTTP request -->
<key>NSAppTransportSecurity</key>
<dict>
   <key>NSAllowsArbitraryLoads</key> <true/>
   <key>NSAllowsArbitraryLoadsForMedia</key> <true/>
   <key>NSAllowsArbitraryLoadsInWebContent</key> <true/>
</dict>

<!--   custom stuff here -->
<key>UIStatusBarHidden</key>                          <true/>
<key>UIInterfaceOrientation</key>                     <string>${MY_ORIENTATION}</string>
<key>UISupportedInterfaceOrientation</key>            <string>${MY_ORIENTATION}</string>
<key>APP_ID</key>                                     <string>${APP_ID}</string>
<key>UIViewControllerBasedStatusBarAppearance</key>   <false/>
<key>UIRequiresFullScreen</key>                       <true/>

<key>UILaunchImages</key>
<array>
</array>


```

**Comment by sidshekar** [comment]
Thanks ... but I am finding this method really hard :D ..... I was trying otherways to get the iOS SDL base project working.... would you be able to guide with this error here https://github.com/libsdl-org/SDL/issues/4774 and drop some hint as what might be causing the error... :)

**Comment by 1bsyl** [comment]
Sorry, I don't know the other method. I use this one for publishing.

I've updated the script with some help inside (+ one directory of SDL_ttf was changed)

**Comment by sidshekar** [comment]
I just wanted to get my SDL MacOS Vulkan project running on the iOS device to see how it looked. Didnt thinnk it would take so much to get a basic iOS SDL project running. 

But Thanks so much for help!! Maybe ill get back on it when I get more time to get the base iOS SDL project running.

Cheers!!

**Comment by 1bsyl** [comment]
It shouldn't be that hard with those infos.
ios_build_libs should take 5 min to build.
then adapt the CMakeList.txt  file to your project and generate your xcode project.
open it and compile.
probably adapt the info.list
run it.

**Comment by sidshekar** [comment]
I was trying to run the demo project... even they are giving such a hard time to run. I get this error when I run it. I even entered 1.0 in the build number and still I get this error.

Seems like which ever method you try, its a dead end. Wish there was more updated documentation on creating iOS projects. As all of the methods as of now are broken or require expert level alternate skills to get the project running. 

![Screen Shot 2021-12-01 at 12 35 17 AM](https://user-images.githubusercontent.com/2862097/144040434-43636bc4-2c1d-4e4f-b05b-888dda3fc4a3.png)
.

**Comment by sidshekar** [comment]
If you could put up a youtube video showing how to run a basic example it would be very useful. I really just need a window so that I can get a surface to render the Vulkan scene into it. I really dont need SDL for anything else. THanks!

**Comment by 1bsyl** [comment]
Read the error the message and check the info.plist file
you can see on https://discourse.libsdl.org/ maybe this has been asked before.

**Comment by sidshekar** [comment]
Hi! Thanks for your input. I gave the script an another shot at building.

I made a folder structure as you mentioned.

![Screen Shot 2021-12-01 at 12 01 19 PM](https://user-images.githubusercontent.com/2862097/144141885-dbcb3ee5-289d-4f1e-a366-3cd709804388.png).

But it fails to build.

![Screen Shot 2021-12-01 at 12 02 00 PM](https://user-images.githubusercontent.com/2862097/144141965-58afd571-4fae-48de-9bc1-c20a1f732049.png)

![Screen Shot 2021-12-01 at 12 02 30 PM](https://user-images.githubusercontent.com/2862097/144142014-011b8012-8b8a-49e5-a792-e513e3b58d6d.png)

![Screen Shot 2021-12-01 at 12 03 18 PM](https://user-images.githubusercontent.com/2862097/144142101-554dc5ca-97a6-4cf0-a23b-1134c25916f3.png)

Any suggestions??

**Comment by 1bsyl** [comment]
I am still building with SDK 14.5 whereas you have SDK 15.
it says i386 is deprecated, maybe remove it from the script

**Comment by 1bsyl** [comment]
I've tried with an updated version. And this worked for me with latest macosx/xcode, with lasted SDL source.
Did you change the something in the sdl xcode project like the target, as the message said?

**Comment by 1bsyl** [comment]
I've just updated the script fixing the build with latest SDL libs
