### ISSUE TITLE
SDL cannot be displayed in QLabel, which is beyond the scope of QLabel

### ISSUE THREAD

**Issue by wj19950515** [libsdl-org/SDL#4411]
screen = SDL_CreateWindowFrom((void *)ui->label->winId());
sdlRender = SDL_CreateRenderer(screen,-1,0);
texture = SDL_CreateTexture(sdlRender,SDL_PIXELFORMAT_IYUV, SDL_TEXTUREACCESS_STREAMING,width,height);//width,height the width and height of the actual video
SDL_UpdateTexture(texture, nullptr, pixels, pitch);    
SDL_RenderClear(sdlRender);    
SDL_RenderCopy(sdlRender, texture, nullptr, nullptr); //Setting the third and fourth parameters is not invalid
SDL_RenderPresent(sdlRender);

**Comment by wj19950515** [comment]
How can I set it so that it can be displayed within the scope of QLabel

**Comment by wj19950515** [comment]
run in macos

**Comment by wj19950515** [comment]
MacOS Qt development environment

**Comment by icculus** [comment]
SDL isn't really intended to run in a widget like this; SDL_CreateWindowFrom is meant to use a top level window.
