### ISSUE TITLE
CMake: missing support for SDL_JOYSTICK_RAWINPUT

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#4412]
This was the reason the build error from https://github.com/libsdl-org/SDL/pull/4388#issuecomment-852713792 wasn't caught by CI.

**Comment by sezero** [comment]
sdlchecks.cmake and include/SDL_config.h.cmake needs updating for this,
which I'm not volunteering for.

**Comment by sezero** [comment]
PING?

**Comment by slouken** [comment]
RAWINPUT doesn't depend on HIDAPI, so I think you can move it out of that block. Otherwise that seems correct to me.

**Comment by sezero** [comment]
> RAWINPUT doesn't depend on HIDAPI, so I think you can move it out of that block.

autotools makes it depend on hipapi..

**Comment by slouken** [comment]
That used to be true, but isn't anymore. I'll fix that, along with the hint SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT, which has nothing to do with HIDAPI.

**Comment by slouken** [comment]
That's fixed in https://github.com/libsdl-org/SDL/commit/24059a19c5302fa2ed40cbdb3e4dcaae9e732690

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL/commit/a809d62605f0de051c665ae6c981d89d6923533d to fix this.
