### ISSUE TITLE
Linux Bluetooth Button Mapping on PS4 Controller broke in 2.0.14

### ISSUE THREAD

**Issue by wberrier** [libsdl-org/SDL#4414]
On Fedora 34 with official PS4 controllers paired via bluetooth, the button mapping is wrong.

I was able to track this regression by trying the Fedora 33 rpms for SDL2 (2.0.12) and the mappings are correct.

I suspect the commit:

43b377b0 Fixed wired PS4 controller support on Android

broke this.

Reason being, doing `sdl2-jstest --list` and diffing the output for the non-working and then working versions produced the following:

```patch
$ cat ps4-linux-bluetooth-broken-2.0.14-to-working-2.0.12.diff 
--- out2	2021-06-03 00:05:56.941542352 -0600
+++ out3	2021-06-03 00:10:40.009376951 -0600
@@ -1,13 +1,13 @@
 Found 1 joystick(s)
 
-Joystick Name:     'PS4 Controller'
-Joystick GUID:     030000004c050000cc09000000006800
+Joystick Name:     'Wireless Controller'
+Joystick GUID:     050000004c050000cc09000000810000
 Joystick Number:    0
 Number of Axes:     6
-Number of Buttons: 16
-Number of Hats:     0
+Number of Buttons: 13
+Number of Hats:     1
 Number of Balls:    0
 GameController:
   Name:    'PS4 Controller'
-  Mapping: '030000004c050000cc09000000006800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,touchpad:b15,'
+  Mapping: '050000004c050000cc09000000810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,'

```

Changing to an earlier kernel version didn't seem to change anything.

I'm not sure of what the fix for both Android wired and Linux bluetooth may be?

**Comment by wberrier** [comment]
Actually, it looks like 43b377b was in 2.0.12, so maybe the changed guid chose the wrong button mapping?

**Comment by slouken** [comment]
It looks like 2.0.14 is using the HIDAPI driver, but I'm surprised that the button mapping is wrong, since we're using raw HID reports, which shouldn't change across platform.

What specifically isn't working correctly?

**Comment by slouken** [comment]
If you use the SDL testgamecontroller program, does it not work correctly for you?

**Comment by slouken** [comment]
I think what may be happening is that you're assuming joystick buttons and axes remain constant across versions of SDL. The only mapping which is guaranteed is the game controller mapping. The joystick level axes and buttons can change between OS version, SDL driver, and controller firmware version.

Please let me know if that's what's happening here.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by wberrier** [comment]
> I think what may be happening is that you're assuming joystick buttons and axes remain constant across versions of SDL. The only mapping which is guaranteed is the game controller mapping. The joystick level axes and buttons can change between OS version, SDL driver, and controller firmware version.
> 
> Please let me know if that's what's happening here.

I'm really sorry I didn't get back to this long ago... I think that's definitely what had happened.
