### ISSUE TITLE
OS X Big Sur 11.4 update breaks SDL2

### ISSUE THREAD

**Issue by Bambofy** [libsdl-org/SDL#4421]
Error message:

```
====================[ Build | Harvestor | Debug ]===============================
"/Users/x/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7442.42/CLion.app/Contents/bin/cmake/mac/bin/cmake" --build /Users/x/Documents/GitHub/x/cmake-build-debug --target Harvestor -- -j 3
make[3]: *** No rule to make target `/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreVideo.framework', needed by `Harvestor'.  Stop.
make[3]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/Harvestor.dir/source/main.cpp.o
make[2]: *** [CMakeFiles/Harvestor.dir/all] Error 2
make[1]: *** [CMakeFiles/Harvestor.dir/rule] Error 2
make: *** [Harvestor] Error 2

```

Fix:

Create a symlink called MacOSX11.1.sdk in the Library/Developer/CommandLineTools/SDKs/ direction which links to Library/Developer/CommandLineTools/SDKs/ MacOSX11.sdk

**Comment by icculus** [comment]
This is working for me on 11.4, with both Xcode 12 and the Xcode 13 Beta.

What is _likely_ happening is that you ran CMake, which finds the SDK in your Xcode install, then upgraded Xcode, and ran `make` again. The now-missing SDK directory is hardcoded in the build files that CMake produced.

If this is the case, the fastest solution is to delete the build directory and recreate it with CMake, so it will find the correct SDK again.

Closing this in case I'm right, but feel free to reopen if this doesn't resolve the issue for you!
