### ISSUE TITLE
SDL_GameControllerRumbleTriggers not working for Xbox One controllers

### ISSUE THREAD

**Issue by Gpinchon** [libsdl-org/SDL#4425]
SDL version : 2.0.14 static library
OS : Windows 10 version 20H2
Issue : When attempting to use SDL_GameControllerRumbleTriggers with an Xbox One controller connected through Bluetooth it does not work and ends up in WINDOWS_JoystickRumbleTriggers which simply returns SDL_Unsupported, is this an expected behavior ? Is there a way to have the "impulse triggers" working with this device ?

**Comment by slouken** [comment]
I believe Xbox One controllers don't support trigger rumble over Bluetooth.

**Comment by xDShot** [comment]
I am implementing Rumble Triggers feature in my project. I have Xbox One Controller (Model 1708) connected via USB. SDL2 reports it doesn't have the feature.

Sample code:
```c
#include <stdio.h>
#include <SDL2/SDL.h>

int main()
{
	SDL_version v;
	SDL_version *sdl_version = &v;
	SDL_GetVersion(&v);

	printf("Found SDL version %i.%i.%i\n", sdl_version->major, sdl_version->minor, sdl_version->patch);

	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_XBOX, "1");

	if (SDL_Init(0) < 0)
	{
		printf("Couldn't init SDL: %s", SDL_GetError());
		return 1;
	}
	
	if (SDL_InitSubSystem(SDL_INIT_GAMECONTROLLER) == -1 )
	{
		printf("could not initialize SDL Game Controller\n");
		return 1;
	}

	printf("Number of Joysticks: %d\n", SDL_NumJoysticks ());

	SDL_GameController *joy_active_controller = SDL_GameControllerOpen (0);
	if (!joy_active_controller)
	{
		printf("couldn't open gamepad device %d\n", 0);
		return 1;
	}

	printf("VendorID=0x%x, ProductID=0x%x\n", SDL_GameControllerGetVendor(joy_active_controller), SDL_GameControllerGetProduct(joy_active_controller));
	
	int has_rumble_triggers = SDL_GameControllerHasRumbleTriggers(joy_active_controller);
	printf("Does it have Rumble Triggers? %d\n", has_rumble_triggers);

	int rumble_trigger_result = SDL_GameControllerRumbleTriggers(joy_active_controller, 0x1000, 0xF000, 250);
	printf("rumble_trigger_result = %d\n", rumble_trigger_result);

	SDL_Quit();
	return 0;
}
```

Output:
```
$ ./impulse_triggers_test 
Found SDL version 2.30.0
Number of Joysticks: 1
VendorID=0x45e, ProductID=0x2ea
Does it have Rumble Triggers? 0
rumble_trigger_result = -1
```

Why it reports False if it is supposed to have the feature?

**Comment by slouken** [comment]
Did you print SDL_GetError() to find out why?

**Comment by xDShot** [comment]
> Did you print SDL_GetError() to find out why?

```c
printf("Does it have Rumble Triggers? %d %s\n", has_rumble_triggers, SDL_GetError());
```

```
Does it have Rumble Triggers? 0 Unexpected controller element crc
```

**Comment by slouken** [comment]
No, I mean after rumble triggers result.

**Comment by xDShot** [comment]
> No, I mean after rumble triggers result.

Not near computer, but tried. Result is something like:

-1 This operation is not permitted

**Comment by xDShot** [comment]
```c
int rumble_trigger_result = SDL_GameControllerRumbleTriggers(joy_active_controller, 0x1000, 0xF000, 250);
printf("rumble_trigger_result = %d %s\n", rumble_trigger_result, SDL_GetError());
```

```
rumble_trigger_result = -1 That operation is not supported
```

**Comment by slouken** [comment]
What version of SDL are  you using? Does it work with testgamecontroller/testcontroller?

**Comment by xDShot** [comment]
> What version of SDL are you using? Does it work with testgamecontroller/testcontroller?

2.30 provided by Arch Linux.

I did tests on Windows machine in testgamecontroller and it worked.

**Comment by slouken** [comment]
Arch Linux doesn't provide trigger rumble in their kernel drivers.

**Comment by PeteHaughie** [comment]
I hate to be a thread necromancer but I'm seeing this same issue with PS4 controllers, SDL2 and Mac OS Sonoma.

A wired controller rumbles as expected but the same controller connected wirelessly returns a -1 and`That operation is not supported`

Is this an OS level thing that I won't be able to circumvent?

**Comment by slouken** [comment]
> I hate to be a thread necromancer but I'm seeing this same issue with PS4 controllers, SDL2 and Mac OS Sonoma.

PS4 controllers don't have trigger rumble. If you're experiencing a different issue, please enter a new bug for your problem.
