### ISSUE TITLE
SDL_SpinLock "corruption" if values are stored in an array

### ISSUE THREAD

**Issue by lgblgblgb** [libsdl-org/SDL#4431]
I'm not sure if it's not my fault. I'm using bunch of spinlocks. Something like this

```
static SDL_SpinLock locks[4];

[...]

for (int i = 0; i < 4; i++) {
    printf("About to lock #%d now: %d\n", i, locks[i]);
    SDL_AtomicLock(&locks[i]);
    // do something "protected" under the i-th lock ...
    SDL_AtomicUnlock(&locks[i]);
}
```

My experience, that after a while (even if this is the only code now, no other thread/etc uses these locks yet), some spinlock "stuck", the printf shows some esoteric random value (that was the only reason I inserted that printf), like 7789 (varies), while normally those are seems to be 0 and 1. Surely, at that pont the code execution stuck at `SDL_AtomicLock()`.

Interestingly, if I break these array of locks into separate variables, "far enough away" from each other, there is no problem (or, if I put into those SDL_SpinLock values into an array of structs with lots of other unrelated variables as well, like: `&mytodo[i].spinlock`). This is the really interesting part what I can't understand. I can even imagine that this behaviour is some gcc optimization bug. Or I've done something it shouldn't be.

OS: Linux (kernel: 5.4.0), Ubuntu 20.04.2 LTS, 64 bit using Xorg
SDL: 2.0.10 (Ubuntu package: libsdl2-2.0-0:amd64 2.0.10+dfsg1-3)

**Comment by icculus** [comment]
Marking this for 2.0.16 just so it gets my attention soon, but my suspicion is that this isn't an SDL bug...but I'll try to reproduce it, just in case!

**Comment by lacc97** [comment]
I'm pretty sure this isn't an SDL bug. You must be accidentally writing over the spinlocks somewhere else in your code because the only valid values a spinlock can have are 0 (unlocked) or 1 (locked). The issue could be you are forgetting to initialise them to zero; that's why it gets stuck in the code snippet you posted.

**Comment by icculus** [comment]
> The issue could be you are forgetting to initialise them to zero

`static` variables are implicitly initialized to zero.

**Comment by lgblgblgb** [comment]
I've tried again yesterday, now I can't reproduce this problem any more. Thus I guess I had some other bug maybe, like corruption of the locks, or anything, I really can't tell :( I guess in this case, it's not so much possible to handle this issue as an investigable one too much. I think, I'll close it, not to bother SDL developers with bugs may be not there anyway.

**Comment by icculus** [comment]
No worries, closing now.
