### ISSUE TITLE
'instant' KEYDOWN event on a background process when the foreground process is killed

### ISSUE THREAD

**Issue by wraitii** [libsdl-org/SDL#4432]
I've encountered a rather peculiar issue.
When an app gains focus, it seems to re-trigger Keydown events (without repeat) incorrectly. This is confirmed only on Linux with X11.

Here's a toy example reproducing the issue:
- start two instances (distinct processes)
- Alt-F4 the first
- It gets killed via SDL_Quit
- The second gets killed as well, by receiving the keydown events sent to the first window.
The latter behaviour is incorrect and appears to only happen on linux (we've not been able to reproduce on MacOS/Windows).
The keydown events that the 2nd process receives have repeat == 0 and no way to distinguish them from real keydown events, as far as I can tell.

```c
#include <SDL2/SDL.h>
 
#include <cstdio>
 
int main(int argc, char ** argv)
{
	// variables
 
	SDL_Init(SDL_INIT_VIDEO);
	SDL_Window * window = SDL_CreateWindow("Test",
		SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, 0);
 
	bool quit = false;
	SDL_Event event;
 
	bool alt = false;
	bool f4 = false;
	while (!quit)
	{
		SDL_WaitEvent(&event);
 		printf("event: %i\n", event.type);
		switch (event.type)
		{
		case SDL_QUIT:
			quit = true;
			break;
		case SDL_KEYDOWN:
		{
			printf("keydown: %i, repeat %i\n", event.key.keysym.scancode, event.key.repeat);
			if (event.key.keysym.scancode == SDL_SCANCODE_LALT)
				alt = true;
			else if (event.key.keysym.scancode == SDL_SCANCODE_F4)
				f4 = true;
			break;
		}
		case SDL_KEYUP:
		{	
			if (event.key.keysym.scancode == SDL_SCANCODE_LALT)
				alt = false;
			else if (event.key.keysym.scancode == SDL_SCANCODE_F4)
				f4 = false;
			break;
		}
		}
		if (alt && f4)
			break;
	}
 
	SDL_DestroyWindow(window);
	SDL_Quit();
 
	return 0;
}
```

**Comment by Imarok** [comment]
It looks similar to #4018

**Comment by jpcima** [comment]
I experience a somewhat similar problem, perhaps it can help with reproducing.
Occurring both in KDE and XFCE.

- open my SDL window and have it focused
- open desktop's application runner by Alt+F2 shortcut
- type a program in the app runner and validate by return key (eg. "xterm")
- immediately as the runner closes, the SDL window incorrectly receives the "return" keypress event

This is the program affected: https://github.com/jpcima/smf-dsp/
every SDL2 I tried (on 2.0.18 currently)

**Comment by jpcima** [comment]
Here's a log which results from this bug, under current SDL 419ae29, `DEBUG_KEYBOARD` and `DEBUG_XEVENTS` enabled.
[SDL-log.txt.gz](https://github.com/libsdl-org/SDL/files/7812557/SDL-log.txt.gz)

I followed the steps which are described in the previous post.
The undesired keypress with Return key seems generated by the FocusIn handler.

**Comment by jpcima** [comment]
In order to resolve this, can we disallow `X11_ReconcileKeyboardState` to synthesize key presses? (or maybe, at least in the case that results from a focus change)

https://github.com/libsdl-org/SDL/blob/16f5b9e3c33316b257c7dcc689d7df0efe6c0cae/src/video/x11/SDL_x11events.c#L410-L411

**Comment by slouken** [comment]
Yep, that seems like the right approach.
