### ISSUE TITLE
SDL_GetBasePath() returns truncated path on Windows if path of folder containing exetuable is more than 126 characters long (excluding trailing backslash)

### ISSUE THREAD

**Issue by notnullnotvoid** [libsdl-org/SDL#4439]
https://github.com/libsdl-org/SDL/blob/2f248a2a31c3323ecc37c00ad5e269e347ae392a/src/filesystem/windows/SDL_sysfilesystem.c#L36

^ I haven't debugged this myself, but from reading the code, my guess is that the loop is written assuming the return value of `GetModuleFileNameExW` counts the null terminator, but it doesn't, so when the path is too large for the buffer it's returning `buflen - 1` instead of the expect `buflen` and so the loop always exits at the first iteration.

https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulefilenameexw

Docs say: "If the function succeeds, the return value specifies the **length of the string** copied to the buffer." (emphasis added). I think that means it does *not* include the null terminator, although it isn't super clear.

**Comment by icculus** [comment]
Docs are more clear on a different page:

https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew

If the buffer is too small, this returns the `buflen` and SDL should then double the buffer size and try again based on that. Are you saying this isn't doing that?

If you can try debugging this, I'd like to know what value is actually being returned from that function (and what version of Windows this is happening on).

**Comment by notnullnotvoid** [comment]
Just did some testing and confirmed it's an off-by-one error. The page you linked is the documentation for a function called "GetModuleFileNameW", which **does** count the null terminator in its return value. The one you load in the source code is a different function called "GetModuleFileName**Ex**W", which **does not** count the null terminator in its return value. Thanks, Microsoft.

Test code:
```C
const static int pathsize = 10; //arbitrary small size
wchar_t pathbuf[pathsize];

HMODULE psapi = LoadLibraryA("psapi.dll");
typedef DWORD (WINAPI *GetModuleFileNameExW_t) (HANDLE, HMODULE, LPWSTR, DWORD);
GetModuleFileNameExW_t pGetModuleFileNameExW = (GetModuleFileNameExW_t) GetProcAddress(psapi, "GetModuleFileNameExW");
int pathlen = pGetModuleFileNameExW(GetCurrentProcess(), NULL, pathbuf, pathsize);
printf("ExW len: %d (%d)\n", pathlen, pathsize);

HMODULE kernel32 = LoadLibraryA("kernel32.dll");
typedef DWORD (WINAPI *GetModuleFileNameW_t) (HMODULE, LPWSTR, DWORD);
GetModuleFileNameW_t pGetModuleFileNameW = (GetModuleFileNameW_t) GetProcAddress(kernel32, "GetModuleFileNameW");
pathlen = pGetModuleFileNameW(NULL, pathbuf, pathsize);
printf("W len: %d (%d)\n", pathlen, pathsize);
```
Output:
```
ExW len: 9 (10)
W len: 10 (10)
```

**Comment by pmttavara** [comment]
There is a PR to fix this issue: https://github.com/libsdl-org/SDL/pull/4437
> If you can try debugging this, I'd like to know what value is actually being returned from that function (and what version of Windows this is happening on).
I debugged SDL source on Win10 v10586 and reproduced the issue on Win10 v19041 as well.
The value returned is always <= 127. Microsoft APIs never fail to amaze! 😄 
If older Windows versions return `buflen` rather than `buflen - 1`, then checking against `buflen - 1` ought to be benign - worst case scenario, SDL does one extra temporary reallocation that gets freed later.

**Comment by icculus** [comment]
Oh, good catch!
