### ISSUE TITLE
SDL_GetPrefPath on Unix doesn't return XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by zxzax** [libsdl-org/SDL#4447]
`SDL_GetPrefPath` is currently returning a path in `XDG_DATA_HOME`, which is more intended to be the equivalent of /usr/share -- for only storing static, read-only data files. By convention, user preferences typically go in `XDG_CONFIG_HOME`. Here are some relevant quotes from the [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html):

>$XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

>$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

I don't know if there is a good way to fix this without causing apps to lose their configurations though, since they won't be able to find the old folder... I guess the function could check for existence of the folder in `XDG_DATA_HOME` first,  return that if it exists, otherwise return the `XDG_CONFIG_HOME` path? The only caveat there is that if the install process also happens to put things in that folder (e.g. if a package is built and installed with `./configure --prefix=$HOME/local`), the old folder will always be returned, but likely that is not common?

**Comment by icculus** [comment]
I don't think we are going to change this.

**Comment by zxzax** [comment]
@icculus Could there be a documentation change saying that this is using the wrong path on Unix, and the function should not be used in new applications there? It seems unfortunate that nothing can be done about this.

**Comment by icculus** [comment]
It's not the wrong place; lots of files are stored there besides config files: save games, logs, mods and DLC. Generically, it's data.

**Comment by zxzax** [comment]
I guess I just wouldn't describe most of those as needing to go in the "pref path." Mods and DLC would probably go in ~/.local/share, but save games would probably want to be placed in ~/.local/state, config files in ~/.config, and logs would go in ~/.cache or /run/user.

This is of course for packages shipped by the distro -- for an "portable app" style build where everything is stored in a single folder, or for something downloaded off Steam or some other service, it seems those would either use `SDL_GetBasePath` to store everything in the one folder, or would skip both in favor of storing configuration and savegames in Steam Cloud, or similar.

**Comment by icculus** [comment]
> I guess I just wouldn't describe most of those as needing to go in the "pref path." Mods and DLC would probably go in ~/.local/share, but save games would probably want to be placed in ~/.local/state, config files in ~/.config, and logs would go in ~/.cache or /run/user.

I get that it bothers you that this doesn't exactly match the spec, but when the spec is bad--such as demanding an app barfs its content all over the filesystem--then the spec should be disregarded.

**Comment by zxzax** [comment]
It's not that I particularly care about the spec, but some apps are prone to dumping large files in ~/.local/share. When moving between machines, it can be a lot easier to sync configuration if all it means is copying ~/.config. That's my only concern. I agree that there are too many random paths in Linux, but the goal with the spec is actually to reduce the total number of ones that the user needs to check.

**Comment by zxzax** [comment]
@icculus Can you please post a link to a more improved spec that can be used? I would really like to get this issue corrected, if not here then downstream. It would be great to have something concrete to show them.

**Comment by icculus** [comment]
I'm willing to live with the regret of calling this "PrefPath" instead of "PathWhereMyAppCanSafelyWriteData," and I don't intend to change this interface in SDL.
