### ISSUE TITLE
Input focus is inaccurate on Win32 when process calling SDL_CreateWindow() is not foreground

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#4450]
When creating a window with `SDL_CreateWindow()`, the window may not be able to be foregrounded upon initial activation. The criteria for foregrounding are [listed here](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks). The most common case I've encountered is that the user has clicked another window just before I'm about to call `SDL_CreateWindow()`.

In the case that the newly activated window is not made the foreground window, SDL incorrectly believes that it has input focus due to receiving the `WM_ACTIVATE` message for the window. This logic seems wrong, since [activation is thread-local state](https://devblogs.microsoft.com/oldnewthing/20131016-00/?p=2913
). However, I haven't succeeded in finding a better alternative.

This bug doesn't just cause `SDL_WINDOW_INPUT_FOCUS` to be set incorrectly, but also causes significant issues when `SDL_SetRelativeMouseMode(SDL_TRUE)` or `SDL_SetWindowKeyboardGrab()` is used. In the former case, the mouse is confined to a tiny rectangle in the center of the screen. In the latter case, modifier key events will be intercepted from other applications that should receive them, causing unexpected behavior.

I tried using `GetForegroundWindow()` in `WM_ACTIVATE` to see if we're the actual foreground window before calling `SDL_SetKeyboardFocus()`, but no dice. We don't become the foreground window (if it will happen at all) until after `WM_ACTIVATE` is processed.

For now, I have hacked around the issue by getting the HWND via `SDL_GetWindowWMInfo()` and calling `SetForegroundWindow()` myself where I can inspect the return value to see if foregrounding succeeded. If it didn't, I don't enable grab or relative mouse mode.

**Comment by DomGries** [comment]
Yes, there is an attempt to fix it in #4293 but it does not seem failure proof yet

**Comment by slouken** [comment]
Can you check to see whether https://github.com/libsdl-org/SDL/commit/632aca29453cf09a44bd45497363607a106634f8 fixes this issue?

**Comment by slouken** [comment]
It looks like this is fixed. Please let me know if it doesn't work for you, or the fix has unintended side-effects.
