### ISSUE TITLE
buildbot configuration

### ISSUE THREAD

**Issue by Try2Code** [libsdl-org/SDL#4456]
hi developers!

First of all: sry for creating the request, but I could not find any mailing list or other more simple way of contacting you. I am looking for a real-world example for an up-to-date buildbot installation. My current installation is based on 0.8.x so there is not easy way of porting things and I want to start from scratch. 

So would you mind sharing the master.cfg of https://buildbot.libsdl.org?

thx on advance

**Comment by icculus** [comment]
I'll strip the passwords out of it and post it. I can't promise it's actually a _good_ example but it does work.

(And yes, when I moved from 0.8.0 to modern releases, I had to throw the whole config away and start from scratch, too, so I feel your pain here.)

**Comment by Try2Code** [comment]
hi @icculus !

thx a lot for your help :pray: 

Maybe you can help me with a more specific topic: We have a group of gatekeepers in my project, which used to start all builders (basically combinations of OS and compilers) with a single 'Force All Builders' button giving a repo and a branch. I know I probably can replace this by a proper webhook for pull-requests, but I want to keep the old options (at least for a while). 
Any info on that would be helpful for me ;-)

**Comment by icculus** [comment]
Here's the config with email addresses and passwords edited out...

I might delete the gist later, so please grab it now.

https://gist.github.com/icculus/b81b1688a4110f17d0caf84202ba6e22

Note that this config still triggers builds based on commits to our Mercurial repo; I intended to update it for GitHub, but haven't yet. There's explicit GitHub support in buildbot if you need this...I believe it just needs a basic GitHub webhook, not a fancy GitHub Action...the buildbot manual has the details.

If you have any questions, let me know.

**Comment by Try2Code** [comment]
u made my day!!! :raised_hands:
