### ISSUE TITLE
Audio Capture from source with 7 channels

### ISSUE THREAD

**Issue by hanseuljun** [libsdl-org/SDL#4458]
Unfortunately, Azure Kinect, a device from Microsoft has 7 channels for its microphone... While it is not supported in SDL.

Inside SDL_BuildAudioCVT() of audio/SDL_audiocvt.c, seems like conversions between 1, 2, 4, 8 channels are supported, but there is no support for 7, which seems like the reason why SDL is not supporting 7 channels.

Would there be a way I can still use SDL for this case with 7 channels? I don't need the conversion between audio channels as having 7 channels would be perfectly fine for me.

Or maybe I should try implementing the conversion to and from 7 channels? I'm no audio expert (very afraid of doing the math wrong here) but in case this really is what I should do, I can give it a try...

**Comment by icculus** [comment]
So 7 channels is kinda weird; the reason we handle 6 and 8 is because they are well-defined in space (left, right, front, back, etc), but if this is a special case just for this one microphone, then we need to figure out what each channel represents and how to map it to something meaningful.

(I don't think we've ever seriously tested with a _stereo_ microphone, let alone a surround-sound input, fwiw.)

**Comment by hanseuljun** [comment]
That sounds like this case is too specific for SDL. I guess I should add another library/dependency for audio to my project...

**Comment by slouken** [comment]
It's not too specific, we just don't have the hardware for testing. If you know what the 7 channel mapping is, we can expose it. Are there docs for it?

**Comment by slouken** [comment]
@icculus, is there a reason we don't just pass back 7 channels? Why would we need to do any conversion if the audio device open call allows returning the hardware audio format?

**Comment by icculus** [comment]
SDL doesn't currently have a concept of 7 channels, so it's possible this could go wrong in 20 different ways.

Is there some documentation on what each of these 7 channels represent? Is it the same as a 7.1 config without the subwoofer channel? If that's the case the conversion is simple.

**Comment by hanseuljun** [comment]
Thank would be more than wonderful! The 7 channel mapping of Azure Kinect can be found from the right side of the first figure from the below article:
https://docs.microsoft.com/en-us/azure/Kinect-dk/hardware-specification

Mic #0: Center (Towards the ceiling)
Mic #1: Front
Mic #2: Front-Right
Mic #3: Rear-Right
Mic #4: Rear
Mic #5: Rear-Left
Mic #6: Front-Left

The six microphones expect for Mic #0 form a circle, with 60 degrees apart from each other from the center of the circle, which is where Mic #0 is at.

And, of course if this is an odd case, exposure without conversion would work wonderful too and I really appreciate SDL that not adding this thing will not change my mind!

**Comment by 1bsyl** [comment]
@hanseuljun 
Not sure if this would help, but you can try this PR https://github.com/libsdl-org/SDL/pull/4974

**Comment by hanseuljun** [comment]
@1bsyl Wow, this is a really pleasant surprise. Of course I will!!

**Comment by slouken** [comment]
Fixed in #4974, thanks!
