### ISSUE TITLE
SDL_HINT_RENDER_DRIVER is checked too early

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#4459]
SDL_HINT_RENDER_DRIVER should,
intuitively, be set before SDL_CreateRenderer()
call.
Unfortunately this is not the case, because
it is checked in ShouldUseTextureFramebuffer(),
which is called from SDL_VideoInit().
It is _also_ checked in SDL_CreateRenderer()
though, leading to an inconsistencies.

**Comment by slouken** [comment]
Do you have a suggestion on how to fix that?

**Comment by stsp** [comment]
We need to ask @stefand who
analysed that problem and found
the solution.

I myself do think that because you
already have the SDL_HINT_FRAMEBUFFER_ACCELERATION
hint where you can specify the
particular driver, SDL_HINT_RENDER_DRIVER
should not be checked at VideoInit().
At the render creation time, you can
allow only a subset of values for
SDL_HINT_RENDER_DRIVER
that are possible for the current
setting of SDL_HINT_FRAMEBUFFER_ACCELERATION,
and in case of an incompatible values,
return an error, or maybe ignore
SDL_HINT_RENDER_DRIVER
and use whatever was set with
SDL_HINT_FRAMEBUFFER_ACCELERATION
in case of an incompatible settings.

**Comment by slouken** [comment]
Fixed by https://github.com/libsdl-org/SDL/commit/fcfd19db862b60159577720f46d31a35a03e7888
