### ISSUE TITLE
SDL_OpenAudioDevice cannot access sound card device with id = 1

### ISSUE THREAD

**Issue by adamdev41** [libsdl-org/SDL#4461]
Accrding to: https://wiki.libsdl.org/SDL_OpenAudioDevice
>Passing in a device name of NULL requests the most reasonable default (and is equivalent to what SDL_OpenAudio() does to choose a device). 

Expected behaviour:
```
    if ( SDL_OpenAudio(&desiredSpec, NULL) < 0 ) {
        fprintf(stderr, "Couldn't open audio: %s\n", SDL_GetError());
    }
```
should work the same as:
```
    const int audio_dev_id = SDL_OpenAudioDevice(nullptr, 0, &desiredSpec, &obtainedSpec, SDL_AUDIO_ALLOW_ANY_CHANGE);
    if (audio_dev_id == 0) {
        printf("Error opening audio device: %s\n", SDL_GetError());
    }
```

Current behaviour:
After call to SDL_OpenAudioDevice  right device is not opened. I would expect audio_dev_id to have value: 1 but is 2.

**Comment by icculus** [comment]
Device id #1 is reserved for backwards compatibility with SDL_OpenAudio. The APIs from SDL 1.2, where you could only open a single device, reserve the first handle value.
