### ISSUE TITLE
syswm passes bogus pointer to the app...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4463]
The X11 implementation of syswm events:

```c
    if (SDL_GetEventState(SDL_SYSWMEVENT) == SDL_ENABLE) {
        SDL_SysWMmsg wmmsg;

        SDL_VERSION(&wmmsg.version);
        wmmsg.subsystem = SDL_SYSWM_X11;
        wmmsg.msg.x11.event = *xevent;
        SDL_SendSysWMEvent(&wmmsg);
    }
```

Windows does the same:

```c
    /* Send a SDL_SYSWMEVENT if the application wants them */
    if (SDL_GetEventState(SDL_SYSWMEVENT) == SDL_ENABLE) {
        SDL_SysWMmsg wmmsg;

        SDL_VERSION(&wmmsg.version);
        wmmsg.subsystem = SDL_SYSWM_WINDOWS;
        wmmsg.msg.win.hwnd = hwnd;
        wmmsg.msg.win.msg = msg;
        wmmsg.msg.win.wParam = wParam;
        wmmsg.msg.win.lParam = lParam;
        SDL_SendSysWMEvent(&wmmsg);
    }
```

(OS/2 and directfb also implement this, in the same way).

SDL_SendSysWMEvent just builds the SDL event and pushes it on the event queue:

```c
int
SDL_SendSysWMEvent(SDL_SysWMmsg * message)
{
    int posted;

    posted = 0;
    if (SDL_GetEventState(SDL_SYSWMEVENT) == SDL_ENABLE) {
        SDL_Event event;
        SDL_memset(&event, 0, sizeof(event));
        event.type = SDL_SYSWMEVENT;
        event.syswm.msg = message;
        posted = (SDL_PushEvent(&event) > 0);
    }
    /* Update internal event state */
    return (posted);
}
```

...but right after the call to SDL_SendSysWMEvent, the `message` pointer becomes invalid, because it's a stack-allocated struct, but we copy the pointer for the event queue to pass to the app later.

I'm not sure how to reasonably fix this, since there isn't an API for freeing SDL events. Should we document that these pointers are only valid during event filters and watchers, and should not be dereferenced in a standard SDL_PollEvent loop?

**Comment by slouken** [comment]
No, we have special handling for this in SDL_AddEvent() where we copy the data for the event.
