### ISSUE TITLE
Multitouch events are split into separate events

### ISSUE THREAD

**Issue by omahena** [libsdl-org/SDL#4465]
It appears there is a limitation in the SDL2 event structure that is focused on single point event reporting for all input devices. 

It makes sense in most cases but it complicates the matters for multitouch touch screen interactions. It creates a situation where the application mostly has an incorrect touch state and where filtering needs to be implemented to determine where all points have been updated and the received state matches the actual state on the touchscreen.

Could the events for touchscreens be batched and provide an array of points instead of a single point?

**Comment by bradallred** [comment]
isn't this what `SDL_Finger` is for?

**Comment by omahena** [comment]
Thank you for pointing out those functions. But they don't entirely solve the problem. 

I opened this issue because it is difficult if not impossible to determine what state the touch screen is in. The issue is about providing the information as a list of points whenever possible to save CPU resources on both ends and provide a smoother experience to the user.

For example iOS is capable of returning a single event if two fingers are placed on the screen at the same time. The OS already does this, there is no further work required. On Windows the touch down events are split up, but the first point is still reported as a move when the first point is reported as a FINGERDOWN event. Same thing on Android. I am not sure how XWindows handle this but here is a log of SDL reports on XWindows:

```
11:39:39:460 SdlEventProc: Fingers: 1, Event: SDL_FINGERDOWN
11:39:39:460 SdlEventProc: Finger: 0, Id: 38, [ 400.0,  207.0]
11:39:39:480 SdlEventProc: Fingers: 2, Event: SDL_FINGERDOWN
11:39:39:480 SdlEventProc: Finger: 0, Id: 38, [ 400.0,  207.0]
11:39:39:480 SdlEventProc: Finger: 1, Id: 39, [ 327.0,  202.0]
11:39:40:127 SdlEventProc: Fingers: 2, Event: SDL_FINGERUP
11:39:40:127 SdlEventProc: Finger: 0, Id: 38, [ 400.0,  207.0]
11:39:40:127 SdlEventProc: Finger: 1, Id: 39, [ 327.0,  202.0]
11:39:40:147 SdlEventProc: Fingers: 1, Event: SDL_FINGERUP
11:39:40:148 SdlEventProc: Finger: 0, Id: 39, [ 327.0,  202.0]
```

Here two fingers were placed on the screen and then lifted. I don't see much wrong with the way this event was handled by SDL other than if the OS is capable of reporting a multiple FINGERDOWN event it would be cool to receive a single FINGERDOWN event IF the OS already provides an event in that form. 

But the FINGERDOWN and FINGERUP are minor issues compared to the FINGERMOTION event. Consider the following sequence:

```
11:42:31:275 SdlEventProc: Fingers: 1, Event: SDL_FINGERDOWN, Touch FingerID: 0
11:42:31:275 SdlEventProc: Finger: 0, Id: 40, [ 385.0,  225.0]
11:42:31:439 SdlEventProc: Fingers: 1, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:31:439 SdlEventProc: Finger: 0, Id: 40, [ 394.0,  225.0]
11:42:31:458 SdlEventProc: Fingers: 2, Event: SDL_FINGERDOWN, Touch FingerID: 0
11:42:31:458 SdlEventProc: Finger: 0, Id: 40, [ 394.0,  225.0]
11:42:31:458 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  224.0]
11:42:31:477 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:31:477 SdlEventProc: Finger: 0, Id: 40, [ 399.0,  225.0]
11:42:31:477 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  224.0]
11:42:31:582 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:31:582 SdlEventProc: Finger: 0, Id: 40, [ 400.0,  226.0]
11:42:31:582 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  224.0]
11:42:31:606 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:31:606 SdlEventProc: Finger: 0, Id: 40, [ 401.0,  226.0]
11:42:31:606 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  224.0]
11:42:31:638 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:31:638 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  226.0]
11:42:31:638 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  224.0]
11:42:31:736 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: 0
11:42:31:736 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  226.0]
11:42:31:736 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  225.0]
11:42:31:983 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:31:984 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  227.0]
11:42:31:984 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  225.0]
11:42:32:005 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: 0
11:42:32:005 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  227.0]
11:42:32:006 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  226.0]
11:42:32:025 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: 0
11:42:32:025 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  227.0]
11:42:32:025 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  227.0]
11:42:32:044 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:32:044 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  229.0]
11:42:32:044 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  227.0]
11:42:32:063 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: 0
11:42:32:064 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  229.0]
11:42:32:064 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  228.0]
11:42:32:116 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:32:116 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  231.0]
11:42:32:116 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  228.0]
11:42:32:206 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: 0
11:42:32:206 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  231.0]
11:42:32:206 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  231.0]
11:42:32:231 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:32:231 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  234.0]
11:42:32:231 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  231.0]
11:42:32:264 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: 0
11:42:32:264 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  234.0]
11:42:32:265 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  234.0]
11:42:32:346 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: -1320071424
11:42:32:346 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  236.0]
11:42:32:346 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  234.0]
11:42:32:385 SdlEventProc: Fingers: 2, Event: SDL_FINGERMOTION, Touch FingerID: 0
11:42:32:385 SdlEventProc: Finger: 0, Id: 40, [ 402.0,  236.0]
11:42:32:385 SdlEventProc: Finger: 1, Id: 41, [ 339.0,  236.0]
```

The user touched the screen with two fingers and pulled them down the screen to change the pitch of the camera. But if the user would keep the first finger stationary and move the second finger this could be a pinch-rotate event to rotate the view. So when the move events are broken down into two individual FINGERMOTION events the result is not smooth pitch motion of the camera's view but a jagged [rotate], [pitch & -rotate], [rotate], [pitch & -rotate]... sequence.

What I am trying to say is that if a group motion event provided by the OS is serialized into a sequence of single point motion events in SDL, the grouping information is lost as the SDL implementation stands today.

Is it impossible to use the touch screen feature? No, of course not. With a hash table and a bunch of filtering code that takes into account timestamps, locations and possibly some other factors it should be possible to reconstruct the groupings of motion events to a certain degree.

The functions mentioned by @bradallred don't help reconstruct the FINGERMOTION group events since the points returned by the `SDL_GetTouchFinger ` are identical as they will be received by the subsequent FINGERMOTION events hence there is no point in retrieving the points at each event. But if SDL would update the entire internal list of points with the information received by the OS provided multi-touch move, before doing a sequence of FINGERMOTION events, then the situation would be different. It would still mean that unnecessary events would be generated but at least the filtering would become trivial.

So what I am asking is if it wouldn't make more sense for SDL to simply pass the grouped touch screen related events as they are provided by the OS?

I see there might be a concern that if SDL doesn't work the same way on all platforms and allows that the SDL behavior is OS dependent... Then people might still have to write the same smart filters to account for HW or OSes with non-grouped touch events. So the only way to maintain consistency would be for SDL to implement those filters... While the current solution simply demands this of the developer.

**Comment by bradallred** [comment]
it's been my experience (so limited to iOS mostly) that rotating gestures come in as `SDL_MULTIGESTURE` events, not as a collection of disparate `SDL_FINGERMOTION` events. I've never had a problem implementing pinch to zoom, swipe, or rotate events that work smoothly. There is also `SDL_DOLLARGESTURE` that I've never used but looks capable of doing more complex gestures. You can read about both of them [here](https://github.com/libsdl-org/SDL/blob/main/docs/README-gesture.md).

I dont think the limitation is in the way SDL presents them, but perhaps the `XWindows` backend or even the layer below SDL.

**Comment by omahena** [comment]
Ah, I see. Unfortunately I cannot take the gesture path. Gestures are a really tempting feature but I cannot use them for two reasons... 

I can only rely on SDL for basic window creation and basic event handling on Linux and Windows while on other platforms I use a different approach. I want to depend as little as possible on external code and retain full control over handling user interaction. This means that SDL gestures would not be available on iOS and Android or any potential future platform (possibly not supported by SDL). So raw events seemed the most elegant way forward and should probably be within the scope of basic SDL functionality.

Unfortunately even on Windows and Linux SDL has not been performing to my expectations. Event pump is really sluggish in my experience and makes my app feel very slow. I will need to look at alternative solutions I fear. On Windows I intercepted window events and handle them directly and the touch screen response time went from one second or more per frame in pure SDL to very fluid on the same HW. Now I am wondering if the same thing is happening on XWin... The slowdown wasn't as pronounced but direct code driven animations seem faster than user interaction driven movement. I need to research and tweak this a bit.

Thanks for getting back to me @bradallred.

**Comment by bradallred** [comment]
there is an open bug for `SDL_PumpEvents` regarding RAW event slow down: #4376 

> retain full control over handling user interaction.
I dont see how using SDL events prevents this. on iOS you can subclass the SDL app delegate and whatever else. You can do the same on Android AFIK.

**Comment by dos1** [comment]
Having the touchpoints split into separate events is not a problem - the problem is that SDL does not provide any frame of reference that would allow the user to combine those events into single state (without resorting to hacky heuristics). Wayland's wl_touch, for instance, sends all touchpoints as separate events as well, but then [follows with `wl_touch.frame` event](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_touch) that ties them together. Something similar could be added to SDL as well for clients that need to rely on that information.

**Comment by omahena** [comment]
@dos1 Good point. A broken up sequence of events with a frame of reference would work equally well as a single event with an array of points, and operations up/down/move for each point (neglected to point that out in my first post). All solutions that provide a trivial way of determining which events belong together are fine.

**Comment by slouken** [comment]
The way to do that is to do something like the following:
```
// Begin frame event handling
SDL_PumpEvents();
while ( SDL_PeepEvents(...) > 0 ) {
    // Process events
}
```
If you do that each frame, you know that all the events you read that frame are associated together.

**Comment by omahena** [comment]
@slouken Thank you for your suggestion. I am trying to understand why and how this would work. So `SDL_PumpEvents()` puts events in the event queue.. And `SDL_PeepEvents(...)` would allow peeping at the queued events without removing them from the queue... And touch events would appear in blocks as they were multiplexed from a OS provided multitouch event into a series of `SDL_TouchFingerEvent`s. And based on their sequence in the queue the grouping is implicitly known. Do I understand this correctly?

If I understood you OK, I am not sure if the following concerns are somehow addressed in SDL already:

1. The sample rate of the touch panel and the refresh rate of the screen timing the rendering of frames are not coupled from what I understand. So when it is time to draw a frame, SDL might be half-done multiplexing a multitouch event into the event queue and this would result in a "torn" multitiouch event. Is my assumption correct? So for example for a three finger multitouch event I might get anything from 1 to 3 `SDL_TouchFingerEvent`s from the queue?

2. In the case where the sample rate of a touch panel is a lot higher than the refresh / redraw rate of the screen, there might be several sequences of `SDL_TouchFingerEvent`s in the event queue and there is no way of determining if they are just one multitouch event or several and perhaps a few `SDL_TouchFingerEvent`s from a multitouch event that is being processed (so a torn event like I describe in point 1).

Are these cases addressed in SDL? My guess is they are not, but you know a lot more about SDL internals than I do.

**Comment by slouken** [comment]
So the assumption is that you're calling SDL_PumpEvents() often enough that any events that come through since the last call can be considered simultaneous. You're right that this isn't synchronized with the update rate of the touch surface, but at human reaction times that's usually okay.

You should never get event "tearing" as you're describing. Pumping the event loop will pull all pending touch events, so the only way that would happen is if the touch device itself didn't report all simultaneous events, which is unlikely.

Does this help?

**Comment by slouken** [comment]
Also, you would call SDL_PeepEvents() with SDL_GETEVENT, so you'd actually be removing them from the queue at the time you're checking it.
