### ISSUE TITLE
kmsdrm: wrong resolution

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#4470]
I updated sdl from git and found
that the resolution is wrong on kms
console under qemu. It is larger than
the screen, so only the part of the image
of my program is visible.
I bisected that to commit 0219928d.
After reverting it, things goes back to
normal.
Haven't analysed the problem.
Let me know what info is needed.

**Comment by slouken** [comment]
Can you check the latest code? We've updated with some KMSDRM fixes.

**Comment by stsp** [comment]
LGTM, thanks!

**Comment by slouken** [comment]
Great, thanks!
