### ISSUE TITLE
SDL_GL_SetSwapInterval is partly broken on macOS

### ISSUE THREAD

**Issue by nadiaholmquist** [libsdl-org/SDL#4471]
Let's say I'm using a 120Hz monitor and want my game to run at 60Hz, I call `SDL_GL_SetSwapInterval(2)` to vsync every other frame, this seems to work correctly on Linux, however on macOS Big Sur, this seems to behave the same as if I had passed 1 to `SDL_GL_SetSwapInterval`.

Is this intended behavior or a bug? And in case it is a bug, is there a different way to accomplish this that is more cross platform?

Tested with an RX480 on a Hackintosh as well as my M1 MacBook Air.

**Comment by slime73** [comment]
Unfortunately I don't think macOS' NSOpenGL APIs support those swap intervals. It might be possible if SDL's macOS backend was restructured to use DIsplayLink APIs, but OpenGL windowing-related APIs in macOS are pretty fragile so I'm not sure that's a good idea.

**Comment by ellipticaldoor** [comment]
Not sure if this can help but using vulkan in macos solves this issue

**Comment by icculus** [comment]
> Not sure if this can help but using vulkan in macos solves this issue

Vulkan for macOS is built on top of Metal, which offers more control than OpenGL.

Apple's OpenGL only allows a swap interval of 1 (wait for vsync) or 0 (don't wait for vsync). We can't offer more.

(I'll also warn that building your game to rely on the swap interval is going to cause you an enormous amount of heartache; better to use timers like SDL_GetTicks() or SDL_GetPerformanceCounter() to decide when it's time to continue on, or even better still: make it run at any framerate.)

**Comment by nadiaholmquist** [comment]
> (I'll also warn that building your game to rely on the swap interval is going to cause you an enormous amount of heartache; better to use timers like SDL_GetTicks() or SDL_GetPerformanceCounter() to decide when it's time to continue on, or even better still: make it run at any framerate.)

For sure, this is an existing codebase where the game logic is highly coupled to the frame rate so there isn't much I can do, if I was making my own thing from scratch I'd not have done this.

Thanks for the info though, will have to see what else I can do then.

**Comment by ellipticaldoor** [comment]
Is this a proper thread to ask this? If you don't rely on the swap interval how do you know how much you should limit the fps to math the refresh rate of the monitor?

**Comment by nadiaholmquist** [comment]
> If you don't rely on the swap interval how do you know how much you should limit the fps to match the refresh rate of the monitor?

A combination of vsync plus waiting basdd om performance counters. It works, though it's not exactly great.
