### ISSUE TITLE
How to release SDL_SetRelativeMouseMode on unfocusing

### ISSUE THREAD

**Issue by StarStarJ** [libsdl-org/SDL#4474]
The problem is, I'd like to release the mouse when unfocusing window to prevent side effects of hovering over relative mouse mode windows.

i use the testrelative.c from the tests
the apparent solution would be
```
case SDL_WINDOWEVENT:
{
  switch(event.window.event)
  {
  case SDL_WINDOWEVENT_FOCUS_GAINED:
	  SDL_SetRelativeMouseMode(SDL_TRUE);
	  break;
  case SDL_WINDOWEVENT_FOCUS_LOST:
	  SDL_SetRelativeMouseMode(SDL_FALSE);
	  break;
  }
}
break;
```

This hoever breaks Windows in fullscreen completly(even reproducable with wine). It doesn't allow the Windows(if used by wine and KDE the same) taskbar to popup at all.
This is probably bcs the SDL event is much after Windows already unfocused the app and SDL_SetRelativeMouseMode refocuses it again.

So i added an event watch:
```

SDLCALL int SetMouse(void *userdata, SDL_Event * event) {
	switch(event->type) {
	case SDL_MOUSEMOTION:
	
		case SDL_WINDOWEVENT:
		{
			switch(event->window.event)
			{
			case SDL_WINDOWEVENT_FOCUS_GAINED:
				SDL_SetRelativeMouseMode(SDL_TRUE);
				break;
			case SDL_WINDOWEVENT_FOCUS_LOST:
				SDL_SetRelativeMouseMode(SDL_FALSE);
				break;
			}
		}
		break;
	}
    return 1;
}

int main()[...]
[...]

    SDL_AddEventWatch(SetMouse, NULL);
```

And it works as expected, but the documentation says:
`WARNING: Be very careful of what you do in the event filter function, as it may run in a different thread!`
And SDL_SetRelativeMouseMode doesn't look thread safe.

Easiest for a game dev would probably to check if the window has input focus and don't have to handle all these stuff(like should happen automatically), but I assume it's also used in different ways :D

If there is any solution I didn't find, it could atleast be added to the documentation :D

**Comment by slouken** [comment]
You shouldn't actually need to do this at all. SDL manages relative mode internally and should disable it when the application loses focus. I just tested this with the testsprite2 application (using Ctrl-R to toggle relative mode) on Windows, and it worked fine. Do you have a case where that's not happening?

**Comment by StarStarJ** [comment]
not having access to a windows pc anytime soon, but even on KDE relative mode isnt deactivated properly:

https://user-images.githubusercontent.com/77283933/127489650-8c1a00cc-3856-45a2-8574-db250413f325.mp4

And under windows this caused massive glitches, the cursor always teleported into the center as soon as i hit the window, and i could really use my mouse anymore
Especially with windowed fullscreen, when the app is still in the background this caused alot of problems

I'll test this again as soon as i get in touch with a win pc again, but can take a few weeks, maybe it was fixed in SDL and i used a too old version for windows

**Comment by StarStarJ** [comment]
Hey, sorry for the long delay
I found out that the "glitch" i descriped happens if you set `SDL_SetHint(SDL_HINT_MOUSE_RELATIVE_MODE_WARP, "1");`

https://user-images.githubusercontent.com/77283933/128673000-658f5f37-4cb0-4c27-a827-1d0586cc1055.mp4

Note that I see both, the above and this as problem. As I also don't want the cursor to disappear(as said especially if you have the game in background)

**Comment by icculus** [comment]
(I'm leaving this bug in the 2.0.18 milestone for now, but we're going to have to bump it to 2.0.20 soon, so let's try to get that pull request sorted out this week if at all possible.)

**Comment by slouken** [comment]
@StarStarJ, a bunch of work has gone into relative mode recently, do you still need the SDL_HINT_MOUSE_RELATIVE_MODE_WARP hint? If so, why?

**Comment by StarStarJ** [comment]
> @StarStarJ, a bunch of work has gone into relative mode recently, do you still need the SDL_HINT_MOUSE_RELATIVE_MODE_WARP hint? If so, why?

Never really needed it, i just randomly noticed the bug with it. However it was fixed long ago.

Tho keep in mind this wasn't the reason I opened this issue.
I'll test if the `real` issue is fixed

**Comment by StarStarJ** [comment]
On Windows:
The desktop fullscreen mouse release seems to work. The taskbar doesn't pop up, but i guess this is related to double buffering in OpenGL (and maybe a AMD driver related issue), dunno if it can be improved
On Linux & Windows:
The mouse is still invisible

**Comment by slouken** [comment]
I've never seen the mouse stay invisible after relative mode is disabled. If that's the real issue, can you please open a new bug with just this, and repro steps?

Thanks!

**Comment by StarStarJ** [comment]
> I've never seen the mouse stay invisible after relative mode is disabled. If that's the real issue, can you please open a new bug with just this, and repro steps?
> 
> Thanks!

In your own words:
https://github.com/libsdl-org/SDL/issues/4474#issuecomment-888632874

This isn't fixed
