### ISSUE TITLE
WinRT: Add support for Windows Gaming Input

### ISSUE THREAD

**Issue by RustyMoyher** [libsdl-org/SDL#4487]
Looking into 2.0.14 and the last tip, I think that WinRT doesn't use SDL_JOYSTICK_WGI. Instead WinRT is using the XInput driver. This limits the total connected controllers to 4 (among other things, I believe).

I've only just moved to 2.0.14, so I'm a bit unfamiliar with the new RAWINPUT driver. Is WinRT using this?

**Comment by flibitijibibo** [comment]
I can confirm it is not:

https://github.com/libsdl-org/SDL/blob/main/include/SDL_config_winrt.h#L198-L206

Probably worth checking out at the same time as the thing mentioned at the bottom of #4321

**Comment by slouken** [comment]
Do you have a tested patch to enable this? I've enabled hotplugging on WinRT, so that should be taken care of.

**Comment by RustyMoyher** [comment]
No, I don’t. I tried to hack something together, but didn’t get anywhere.

**Comment by RustyMoyher** [comment]
Reopening this because I think SDL_JOYSTICK_WGI would still be a smart addition to WinRT, particularly so it can use more than 4 controllers. Sorry I wasn't able to figure it out myself.

**Comment by flibitijibibo** [comment]
Makes sense to me - that said WinRT is extremely dead and Microsoft has indirectly said so via the .NET Foundation, so I'm not even 100% sure this would make a big difference vs. trying to make SDL compatible with GDK instead.

**Comment by RustyMoyher** [comment]
Added in [e04a022](https://github.com/libsdl-org/SDL/commit/110e4e133453cc4f9c466a6312f7f52d02eff516), which is now in the 2.0.18 release -- closing as fixed.
