### ISSUE TITLE
2.0.15 Exception Thrown in Windows.Gaming.Input.dll on SDL_Quit() running from VS2019

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4488]
Here are the exact conditions to trigger this exception:

1) SDL version 2.0.15 (I'm using 32-bit, same probably happens in 64).
2) Have at least 1 non-360 game controller plugged in before running.
3) Run from Visual Studio 2019. It happens in both release and debug mode.
4) SDL_INIT_GAMECONTROLLER with a window and very basic event loop.
5) Quit application after waiting about 30 seconds.
6) Run in Windows 10.

That's it. You don't need to actually open any controllers. It doesn't happen with a 360 controller. It doesn't trigger if you quit the application before about 30 seconds. 

The exact message I get is: 

Exception thrown at 0x532FFE27 (Windows.Gaming.Input.dll) in test.exe: 0xC0000005: Access violation reading location 0x60051B98.

I'm unable to debug this dll because there are no symbols, but when looking at the disassembly I see a symbol called "GameController::~GameController". Guessing this is Windows internal code relating to joystick destruction? Hope this makes sense to someone?

**Comment by slouken** [comment]
I was able to reproduce this a few months ago, but I'm not able to anymore. Are you still able to reproduce this?

**Comment by slouken** [comment]
I'm still able to reproduce this with a Nintendo Switch Pro controller connected.

**Comment by slouken** [comment]
... and now I can't reproduce it anymore

**Comment by AntTheAlchemist** [comment]
It's still there and it's 100% consistent to reproduce; not random. It only happens on my non-360 controllers and only after about 25 seconds. My non-360 controllers are all cheap Chinese generic ones, some mapped, some not.

Shall I test on the latest source? I'll need to download and build the DLL manually (it's the only way my dumb brain knows how to do it, lol)

**Comment by slouken** [comment]
Ah, having it running for 25 seconds was key. I'm able to reproduce it that way too, thanks!
