### ISSUE TITLE
Win 2.0.15 Mocute-032X no longer mapped as controller

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4489]
I have this tiny VR Bluetooth multifunction controller that used to map to a 360 type controller but now is a plain old joystick. This happened some time since 23rd of April when I compiled a DLL at that date which still works. Mocute make a large selection of controllers and it's possible they're all affected by this. I've dug as deep as I can but don't know what to look for or know how to step through SDL source.

On Android everything works great. It comes up as a mapped controller called "MOCUTE-032X_B63-88CE" and a GUID 050000003536343700000000dfff3.

On Windows 10 (32-bit DLL) using the latest source it comes up as a plain old joystick called "Gamepad".

If I go back to an old SDL2.dll built on 23rd of April, it comes up as a "GameStop Gamepad", which is wrong but at least it has xbox type mapping. GUID is different: "03000000ffff00000000000000000000".

Not much to go on, sorry, but something's not right since on the same SDL code Android is seeing the device correctly but not in Windows.

**Comment by slouken** [comment]
Is this what you have?
https://smile.amazon.com/MOCUTE-052-Wireless-Controller-Smartphone/dp/B07D3514M1/ref=sr_1_5?dchild=1&keywords=mocute&qid=1625584429&sr=8-5

**Comment by AntTheAlchemist** [comment]
Nope, this:
https://www.amazon.com/Zopsc-Controller-Wireless-Bluetooth-Joystick/dp/B07RMY6YS5/ref=sr_1_18?dchild=1&keywords=mocute&qid=1625584539&sr=8-18

**Comment by slouken** [comment]
Okay, I'll pick one up and see what's going on.

**Comment by AntTheAlchemist** [comment]
Thank you! I know you'll say no, but I'd be happy to wishlist/gift it to you

**Comment by slouken** [comment]
I already ordered it, but I appreciate the gesture!

**Comment by AntTheAlchemist** [comment]
It has a few different modes which I think are selected by holding down one of the 4 buttons whilst turning it on (during which, it might need to be in game or keyboard mode using the slider switch on the side). I had mine stuck in the wrong mode for a while and it was spitting out keyboard events rather than axis / buttons. Just to keep in mind. Very neat little device anyway - hope it helps.

**Comment by AntTheAlchemist** [comment]
Thanks for your time Sam. It makes sense, but why am I getting a mapped controller for this device in Android with the correct name which works really well. I'm getting the correct axis and ABXY buttons, holding the start button gives me the right-stick axis. I understand it's a fluke that it works, but why isn't this same mapping coming up on Windows? Why the platform inconsistency?

**Comment by slouken** [comment]
The Android OS has a built in mapping whereas Windows does not. I'm surprised the buttons are coming up correctly though, since from the mapping I found on Windows, the A button isn't the first button, which is usually the way it's mapped. Does the mapping I provided above work for you?

**Comment by AntTheAlchemist** [comment]
Apologies; I was mistaken about the Windows mapping in 2.0.14 being spot-on, I think I was assuming the Android mapping was the same. Hard to diagnose because I'm using 2.0.15's GrabKeyboard & GrabMouse (very useful additions, btw!).

Yes the mapping you provided above worked - but not as good as Android's mapping. Holding start will open up the right hand stick axes and more buttons - I can't find any documents to describe this but Android seems to map it all. It's not of high importance and I don't want to take up your valuable time.

The only closing thought / hypothetical questions I have now is how does Android's mapping work so well? Is it subject to the same GUID clashes?

I think you were right to close this originally; not much that can be done.

**Comment by slouken** [comment]
I'm not sure how Android is doing that. Windows seems to have its own internal Bluetooth controller interpretation so mappings from other OSes don't work the same on Windows. There won't be any GUID clashes because on Android the mapping is created dynamically:
https://github.com/libsdl-org/SDL/blob/main/src/joystick/SDL_gamecontroller.c#L471

**Comment by slouken** [comment]
I redid the mapping with the Start+Button combinations for you:
0500000047616d657061640000000000,Gamepad,a:b3,b:b2,x:b1,y:b0,back:b9,start:b8,leftshoulder:b11,rightshoulder:b10,leftx:a0,lefty:a1,rightx:a3,righty:a4,
