### ISSUE TITLE
Changing IME on Windows Leaves Modifier Key Set

### ISSUE THREAD

**Issue by renpytom** [libsdl-org/SDL#4500]
On Windows 10 and SDL 2.0.14, switching from a Japanese IME to an English one by pressing Windows+Space seems to leave the key modifiers set. More specifically, the KMOD_LGUI flag appears to be set in SDL_KEYDOWN events when this happens, and doesn't clear until the windows key is pressed a second time. 

As a workaround, I've been clearing the key modifier using SDL_SetModState(0) when a SDL_KEYMAPCHANGED event, which is a practical if imperfect solution. 

This started off as renpy/renpy#2849. Thank you for your attention.

**Comment by slouken** [comment]
This is fixed by https://github.com/libsdl-org/SDL/commit/3b85e3fdfce01c528a6ebf9ac537bdc106ba4963, thanks!
