### ISSUE TITLE
CMake config files are broken for static-only builds.

### ISSUE THREAD

**Issue by isage** [libsdl-org/SDL#4501]
SDL2Config.cmake expects `SDL2::SDL2` target to be available, however static-only builds do not have in in SDL2Targets.cmake

https://github.com/libsdl-org/SDL/pull/4320 this essentially broke sdl2+cmake on platforms with only static linking available (like PSVita)

Sure, that can be "fixed" by enabling shared lib on those platforms, but that'll produce cmake warnings
```
CMake Warning (dev) at CMakeLists.txt:2523 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Proposed solution: create ALIAS `SDL2::SDL2` target in SDL2Config.cmake if it's unavailable

**Comment by madebr** [comment]
This is fixed in current master.

If no shared SDL2 is available, but a static SDL2 is,
then `SDL2::SDL2` will be the same as `SDL2::SDL2-static`.
