### ISSUE TITLE
Windows Buildbot stop building ?

### ISSUE THREAD

**Issue by psykokwak-com** [libsdl-org/SDL#4504]
Hi all,
There is no new build for visualstudio for 5 months : https://buildbot.libsdl.org/#/builders/7
(and the "include" directory is empty).
How can we get the latest build ?

**Comment by icculus** [comment]
We never hooked this up after the GitHub migration.

I'll wire this up shortly.

**Comment by icculus** [comment]
The buildbot is up and running again, and talking to GitHub instead of Mercurial now; please let me know if you have problems!
