### ISSUE TITLE
SDL.h/SDL_cpuinfo.h incorrectly includes immintrin.h during ARM64 cross compile builds

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4507]
It appears that when cross-compiling to ARM64 on an x64 system, SDL2 headers will include `immintrin.h` (which google tells me is x64-specific) and produce an error:

```
aarch64-linux-gnu-gcc -Wall -Wextra -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-variable ...  -c -o prj/scriptcore.o prj/scriptcore.c
In file included from /tmp/repository/vendor/SDL-upstream/include/SDL2/SDL.h:38,
                 from prj/scriptcore.c:9:
/tmp/repository/vendor/SDL-upstream/include/SDL2/SDL_cpuinfo.h:99:10: fatal error: immintrin.h: No such file or directory
   99 | #include <immintrin.h>
```
So basically SDL2 itself compiles fine (I cross-compiled that right before) but then the application itself does not. It appears there is some `#ifdef` magic missing in the headers to prevent this situation. Maybe ARM64 should be detected in `SDL_cpuinfo.h` and then this header skipped? My apologies if this isn't a bug and just a user error, but I wouldn't know right now what I did wrong to cause this.

A working workaround is to add `-DSDL_DISABLE_IMMINTRIN_H` to the `CFLAGS` of my cross compile builds. That fixes the build. But it really feels like that shouldn't be needed.

**Comment by sezero** [comment]
With which SDL version (or git revision) is this?  Is the SDL version in
use configured and built using autotools or cmake? I had recently pushed
this commit to autotools to prevent this issue from happening:
https://github.com/libsdl-org/SDL/commit/2143534a1cf2c3c66af2b62672bf743cf4872f3c

**Comment by ell1e** [comment]
I used autotools. But I just checked https://github.com/libsdl-org/SDL/commit/9170c0c7f8d3deebb60fff4a88e074de1c37a2f5 and it works, my  bad. I must have been a couple of days behind your fix.
