### ISSUE TITLE
Proposal: SCHED_ISO scheduler policy on Linux

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL#4510]
Hello, I am currently investigating some input latency issues on FNA that seem to be related to oversleeping the thread. 

In my investigations I noticed that Feral's `gamemode` is utilizing the `SCHED_ISO` scheduler policy at a priority of 0. 
https://github.com/FeralInteractive/gamemode/blob/b11d2912e280acb87d9ad114d6c7cd8846c4ef02/daemon/gamemode-sched.c#L176

According to this kernel patch, SCHED_ISO is a "method of providing real time scheduling to unprivileged users which increasingly is desired for multimedia workloads." 
https://lwn.net/Articles/120030/

This seems like something that would be useful for games - wondering if it's worth accounting for in SDL2.

**Comment by thatcosmonaut** [comment]
Here's the discussion where this was merged into `gamemode`: https://github.com/FeralInteractive/gamemode/pull/56

**Comment by dos1** [comment]
As far as I can see, `SCHED_ISO` was never merged into Linux, so it's utility would be very limited.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
