### ISSUE TITLE
Libraries installed in /usr/local/lib are not detected for dynamic loading support

### ISSUE THREAD

**Issue by vanfanel** [libsdl-org/SDL#4520]
Hi there,

I have noticed that having libgbm and libdrm under /usr/local/lib prevents SDL2 from finding them.

This function called `find_lib` in configure.ac uses `gcc -print-search-dirs` to try to find the library files, but fails because gcc does not know about libs installed in `/usr/local/lib`, it only cares about libs in `/usr/lib`
https://github.com/libsdl-org/SDL/blob/48bbe31bc63de67ef118f3d9f40b710178cb78b9/configure.ac#L150

How could this be solved? (ie: configure should be able to find libgbm.so and libdrm.so in `/usr/local/lib` and not only in `/usr/lib`).

I could simply remove these two:
https://github.com/libsdl-org/SDL/blob/48bbe31bc63de67ef118f3d9f40b710178cb78b9/configure.ac#L2225-L2226
I think it's not the best option, but it works beacuse the linker will take care of things even if gcc doesn't know about the libs when you ask him via `gcc -print-search-dirs`.

But what really puzzles me is that find_lib() seems to care about /usr/local/lib:
https://github.com/libsdl-org/SDL/blob/48bbe31bc63de67ef118f3d9f40b710178cb78b9/configure.ac#L158

So, what am I missing here? How should this be handled?

Thanks

**Comment by sezero** [comment]
You have the relevant libraries under both `/usr/lib` _and_ `/usr/local/lib`?

If not:  As I recall libdrm and libgbm are discovered using pkg-config in configure.ac,
so setting `PKG_CONFIG_PATH` to e.g. `/usr/local/lib/pkgconfig` may help?

(I hope we are talking about the same thing..)

(And, may not be exactly relevant, but I had issues with `find_lib`, here: https://github.com/libsdl-org/SDL/issues/3375)

**Comment by vanfanel** [comment]
@sezero Thanks for taking the time to look into this with me!

I only have the relevant libs under /usr/local/lib:
```
pi@raspberrypi:~ $ ls /usr/local/lib/aarch64-linux-gnu/libgbm.so
libgbm.so        libgbm.so.1      libgbm.so.1.0.0
pi@raspberrypi:~ $ ls /usr/local/lib/aarch64-linux-gnu/libdrm.so
libdrm.so        libdrm.so.2      libdrm.so.2.4.0
```

And yes, as you said, libdrm and libgbm are discovered using pkg-config in configure.ac, here:
https://github.com/libsdl-org/SDL/blob/48bbe31bc63de67ef118f3d9f40b710178cb78b9/configure.ac#L2207-L2208
This first search works perfectly well, via PKGCONFIG.

BUT then, the physical libs on-disk are searched again here, while trying to activate dynamic loading support:
https://github.com/libsdl-org/SDL/blob/48bbe31bc63de67ef118f3d9f40b710178cb78b9/configure.ac#L2225-L2226

That second search is what is failing if the lib files live in `/usr/local/lib/...`
And that happens because `find_lib()` can't find the lib files there.

**Comment by sezero** [comment]
First: there was an obvious typo in callin `find_lib`,
And then: the discovery was not reported. Does the patch
below work for you? If it does, I will apply it.

For me, configure now reports:
```
checking for libdrm >= 1.4.82... yes
checking for gbm >= 11.1.0... yes
checking for kmsdrm dynamic loading support... yes
-- dynamic libdrm -> libdrm.so.2
-- dynamic libgmb -> libgbm.so.1
```
And in my generated SDL_config.h, I have:
```
#define SDL_VIDEO_DRIVER_KMSDRM 1
#define SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC "libdrm.so.2"
#define SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC_GBM "libgbm.so.1"
```

Here is the patch:
```
diff --git a/configure.ac b/configure.ac
index b937115..1dcb00f 100644
--- a/configure.ac
+++ b/configure.ac
@@ -2222,8 +2222,8 @@ CheckKMSDRM()
 
             AC_MSG_CHECKING(for kmsdrm dynamic loading support)
             kmsdrm_shared=no
-            drm_lib=[`find_lib "libdrm.so.*" "$DRM_LIBS"`]
-            gbm_lib=[`find_lib "libgbm.so.*" "$DRM_LIBS"`]
+            drm_lib=[`find_lib "libdrm.so.*" "$LIBDRM_LIBS"`]
+            gbm_lib=[`find_lib "libgbm.so.*" "$LIBGBM_LIBS"`]
             if test x$have_loadso != xyes && \
                test x$enable_kmsdrm_shared = xyes; then
                 AC_MSG_WARN([You must have SDL_LoadObject() support for dynamic kmsdrm loading])
@@ -2240,6 +2240,10 @@ CheckKMSDRM()
                 SUMMARY_video="${SUMMARY_video} kmsdrm"
             fi
             AC_MSG_RESULT($kmsdrm_shared)
+            if test x$kmsdrm_shared = xyes; then
+                echo "-- dynamic libdrm -> $drm_lib"
+                echo "-- dynamic libgmb -> $gbm_lib"
+            fi
             have_video=yes
         fi
     fi
diff --git a/configure b/configure
index be32733..fe4bd0f 100755
--- a/configure
+++ b/configure
@@ -22240,8 +22240,8 @@ $as_echo "#define SDL_VIDEO_DRIVER_KMSDRM 1" >>confdefs.h
             { $as_echo "$as_me:${as_lineno-$LINENO}: checking for kmsdrm dynamic loading support" >&5
 $as_echo_n "checking for kmsdrm dynamic loading support... " >&6; }
             kmsdrm_shared=no
-            drm_lib=`find_lib "libdrm.so.*" "$DRM_LIBS"`
-            gbm_lib=`find_lib "libgbm.so.*" "$DRM_LIBS"`
+            drm_lib=`find_lib "libdrm.so.*" "$LIBDRM_LIBS"`
+            gbm_lib=`find_lib "libgbm.so.*" "$LIBGBM_LIBS"`
             if test x$have_loadso != xyes && \
                test x$enable_kmsdrm_shared = xyes; then
                 { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: You must have SDL_LoadObject() support for dynamic kmsdrm loading" >&5
@@ -22272,6 +22272,10 @@ _ACEOF
             fi
             { $as_echo "$as_me:${as_lineno-$LINENO}: result: $kmsdrm_shared" >&5
 $as_echo "$kmsdrm_shared" >&6; }
+            if test x$kmsdrm_shared = xyes; then
+                echo "-- dynamic libdrm -> $drm_lib"
+                echo "-- dynamic libgmb -> $gbm_lib"
+            fi
             have_video=yes
         fi
     fi
```

**Comment by vanfanel** [comment]
@sezero That patch works perfect! Please, merge it :)
Thanks a lot!

**Comment by sezero** [comment]
Done: https://github.com/libsdl-org/SDL/commit/15ed665363b192c29f733d54d46e9669256760fd
