### ISSUE TITLE
Subtle delay in updating mouse position after left click on osx

### ISSUE THREAD

**Issue by triplejam** [libsdl-org/SDL#4522]
SDL_GetMouseState() seems to not return different x and y coordinates for a few frames after a click proceeded by a quick deliberate dragging motion on osx. It does not appear to be the same for right and middle clicks. I also have tried setting relative mouse mode and using SDL_GetRelativeMouseState() and same problem persists.

**Comment by slouken** [comment]
I'm able to reproduce this, but only when clicking on the window when another application has focus. In that case the first left click is used to give the window focus, and is not reported to the application.

This behavior can be changed by using the hint [SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH](https://wiki.libsdl.org/SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH)

If that's not what you're seeing, feel free to reopen this bug with more detailed repro steps.
