### ISSUE TITLE
Disable AVX code on old compilers

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4533]
> Yes, this needs to be disabled on older compilers if they will ICE on it. We can just make a blanket "if it's less than GCC 5.0.0" or whatever. Those compilers will just not get the AVX version of the converter.

__Originally posted by @icculus in https://github.com/libsdl-org/SDL/pull/4436#issuecomment-886119012__

**Comment by sezero** [comment]
FWIW, gcc4.9 doesn't fail for me - hope that helps.

**Comment by flibitijibibo** [comment]
Looks like 4.9 is the minimum - tried GCC 4.8.5 (CentOS 7 compiler) and it fails. Using devtoolset-10 fixes the issue.

**Comment by sezero** [comment]
> Looks like 4.9 is the minimum - tried GCC 4.8.5 (CentOS 7 compiler) and it fails. Using devtoolset-10 fixes the issue.

Quite reasonable to set gcc4.9 as minimum for avx

**Comment by sezero** [comment]
Tried clang-3.4.2 I've been keeping around, fails:
```
src/audio/SDL_audiocvt.c:110:15: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma clang attribute push (__attribute__((target("avx"))), apply_to=function)
              ^
src/audio/SDL_audiocvt.c:123:11: error: unknown type name '__m256'
    const __m256 two_fifths_v = _mm256_set1_ps(two_fifths_f);
          ^
src/audio/SDL_audiocvt.c:123:33: warning: implicit declaration of function '_mm256_set1_ps' is invalid in C99 [-Wimplicit-function-declaration]
    const __m256 two_fifths_v = _mm256_set1_ps(two_fifths_f);
                                ^
src/audio/SDL_audiocvt.c:124:11: error: unknown type name '__m256'
    const __m256 half = _mm256_set1_ps(0.5f);
          ^
src/audio/SDL_audiocvt.c:146:9: error: use of undeclared identifier '__m256'
        __m256 fc_distributed = _mm256_mul_ps(half, _mm256_insertf128_ps(_mm256_castps128_ps256(fc_distributed_lo), fc_distributed_hi, 1));
        ^
src/audio/SDL_audiocvt.c:153:9: error: use of undeclared identifier '__m256'
        __m256 permuted0 = _mm256_insertf128_ps(_mm256_castps128_ps256(permuted0_lo), permuted0_hi, 1);
        ^
src/audio/SDL_audiocvt.c:155:9: error: use of undeclared identifier '__m256'
        __m256 permuted1 = _mm256_insertf128_ps(_mm256_castps128_ps256(in1), in4, 1);
        ^
src/audio/SDL_audiocvt.c:160:9: error: use of undeclared identifier '__m256'
        __m256 out = _mm256_add_ps(permuted0, permuted1);
        ^
src/audio/SDL_audiocvt.c:161:9: error: use of undeclared identifier 'out'
        out = _mm256_add_ps(out, fc_distributed);
        ^
src/audio/SDL_audiocvt.c:161:15: warning: implicit declaration of function '_mm256_add_ps' is invalid in C99 [-Wimplicit-function-declaration]
        out = _mm256_add_ps(out, fc_distributed);
              ^
src/audio/SDL_audiocvt.c:161:29: error: use of undeclared identifier 'out'
        out = _mm256_add_ps(out, fc_distributed);
                            ^
src/audio/SDL_audiocvt.c:162:9: error: use of undeclared identifier 'out'
        out = _mm256_mul_ps(out, two_fifths_v);
        ^
src/audio/SDL_audiocvt.c:162:15: warning: implicit declaration of function '_mm256_mul_ps' is invalid in C99 [-Wimplicit-function-declaration]
        out = _mm256_mul_ps(out, two_fifths_v);
              ^
src/audio/SDL_audiocvt.c:162:29: error: use of undeclared identifier 'out'
        out = _mm256_mul_ps(out, two_fifths_v);
                            ^
src/audio/SDL_audiocvt.c:164:9: warning: implicit declaration of function '_mm256_storeu_ps' is invalid in C99 [-Wimplicit-function-declaration]
        _mm256_storeu_ps(dst, out);
        ^
src/audio/SDL_audiocvt.c:164:31: error: use of undeclared identifier 'out'
        _mm256_storeu_ps(dst, out);
                              ^
src/audio/SDL_audiocvt.c:184:15: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma clang attribute pop
              ^
6 warnings and 11 errors generated.
make: *** [build/SDL_audiocvt.lo] Error 1
```

**Comment by sezero** [comment]
Is the following OK?  Verified that only clang >= 5 and gcc >= 4.9 work
by testing at https://gcc.godbolt.org/
```diff
diff --git a/src/audio/SDL_audiocvt.c b/src/audio/SDL_audiocvt.c
index 23d1906..92205db 100644
--- a/src/audio/SDL_audiocvt.c
+++ b/src/audio/SDL_audiocvt.c
@@ -46,6 +46,11 @@
 #if defined(HAVE_IMMINTRIN_H) && !defined(SDL_DISABLE_IMMINTRIN_H)
 #define HAVE_AVX_INTRINSICS 1
 #endif
+#if defined(__clang__) && (__clang_major__ < 5)
+#undef HAVE_AVX_INTRINSICS
+#elif defined(__GNUC__) && ((__GNUC__ < 4) || (__GNUC__ == 4 && __GNUC_MINOR__ < 9))
+#undef HAVE_AVX_INTRINSICS
+#endif
 
 #if HAVE_SSE3_INTRINSICS
 /* Convert from stereo to mono. Average left and right. */
```

**Comment by sezero** [comment]
Better / corrected patch:
```diff
diff --git a/src/audio/SDL_audiocvt.c b/src/audio/SDL_audiocvt.c
index 23d1906..97f10df 100644
--- a/src/audio/SDL_audiocvt.c
+++ b/src/audio/SDL_audiocvt.c
@@ -46,6 +46,15 @@
 #if defined(HAVE_IMMINTRIN_H) && !defined(SDL_DISABLE_IMMINTRIN_H)
 #define HAVE_AVX_INTRINSICS 1
 #endif
+#if defined __clang__
+# if (__clang_major__ < 5)
+#   undef HAVE_AVX_INTRINSICS
+# endif
+#elif defined __GNUC__
+# if (__GNUC__ < 4) || (__GNUC__ == 4 && __GNUC_MINOR__ < 9)
+#   undef HAVE_AVX_INTRINSICS
+# endif
+#endif
 
 #if HAVE_SSE3_INTRINSICS
 /* Convert from stereo to mono. Average left and right. */
```

**Comment by icculus** [comment]
Go ahead and apply.

**Comment by sezero** [comment]
Applied as https://github.com/libsdl-org/SDL/commit/cf85710cf84707797bde8c7da1307014e0b335eb

**Comment by jbsolomon** [comment]
oddly enough I get this with Clang 12.0.1 / win x64

> Tried clang-3.4.2 I've been keeping around, fails:
> 
> ```
> src/audio/SDL_audiocvt.c:110:15: warning: unknown pragma ignored [-Wunknown-pragmas]
> #pragma clang attribute push (__attribute__((target("avx"))), apply_to=function)
>               ^
> src/audio/SDL_audiocvt.c:123:11: error: unknown type name '__m256'
>     const __m256 two_fifths_v = _mm256_set1_ps(two_fifths_f);
>           ^
> src/audio/SDL_audiocvt.c:123:33: warning: implicit declaration of function '_mm256_set1_ps' is invalid in C99 [-Wimplicit-function-declaration]
>     const __m256 two_fifths_v = _mm256_set1_ps(two_fifths_f);
>                                 ^
> src/audio/SDL_audiocvt.c:124:11: error: unknown type name '__m256'
>     const __m256 half = _mm256_set1_ps(0.5f);
>           ^
> src/audio/SDL_audiocvt.c:146:9: error: use of undeclared identifier '__m256'
>         __m256 fc_distributed = _mm256_mul_ps(half, _mm256_insertf128_ps(_mm256_castps128_ps256(fc_distributed_lo), fc_distributed_hi, 1));
>         ^
> src/audio/SDL_audiocvt.c:153:9: error: use of undeclared identifier '__m256'
>         __m256 permuted0 = _mm256_insertf128_ps(_mm256_castps128_ps256(permuted0_lo), permuted0_hi, 1);
>         ^
> src/audio/SDL_audiocvt.c:155:9: error: use of undeclared identifier '__m256'
>         __m256 permuted1 = _mm256_insertf128_ps(_mm256_castps128_ps256(in1), in4, 1);
>         ^
> src/audio/SDL_audiocvt.c:160:9: error: use of undeclared identifier '__m256'
>         __m256 out = _mm256_add_ps(permuted0, permuted1);
>         ^
> src/audio/SDL_audiocvt.c:161:9: error: use of undeclared identifier 'out'
>         out = _mm256_add_ps(out, fc_distributed);
>         ^
> src/audio/SDL_audiocvt.c:161:15: warning: implicit declaration of function '_mm256_add_ps' is invalid in C99 [-Wimplicit-function-declaration]
>         out = _mm256_add_ps(out, fc_distributed);
>               ^
> src/audio/SDL_audiocvt.c:161:29: error: use of undeclared identifier 'out'
>         out = _mm256_add_ps(out, fc_distributed);
>                             ^
> src/audio/SDL_audiocvt.c:162:9: error: use of undeclared identifier 'out'
>         out = _mm256_mul_ps(out, two_fifths_v);
>         ^
> src/audio/SDL_audiocvt.c:162:15: warning: implicit declaration of function '_mm256_mul_ps' is invalid in C99 [-Wimplicit-function-declaration]
>         out = _mm256_mul_ps(out, two_fifths_v);
>               ^
> src/audio/SDL_audiocvt.c:162:29: error: use of undeclared identifier 'out'
>         out = _mm256_mul_ps(out, two_fifths_v);
>                             ^
> src/audio/SDL_audiocvt.c:164:9: warning: implicit declaration of function '_mm256_storeu_ps' is invalid in C99 [-Wimplicit-function-declaration]
>         _mm256_storeu_ps(dst, out);
>         ^
> src/audio/SDL_audiocvt.c:164:31: error: use of undeclared identifier 'out'
>         _mm256_storeu_ps(dst, out);
>                               ^
> src/audio/SDL_audiocvt.c:184:15: warning: unknown pragma ignored [-Wunknown-pragmas]
> #pragma clang attribute pop
>               ^
> 6 warnings and 11 errors generated.
> make: *** [build/SDL_audiocvt.lo] Error 1
> ```

**Comment by sezero** [comment]
> oddly enough I get this with Clang 12.0.1 / win x64

Are you seeing those errors I get with clang-3.4 with clang-12 targeting windows?

**Comment by jbsolomon** [comment]
@sezero -- yes, or very similar ones (e.g. all the "use of undeclared identifier `__m256`", "undeclared identifier `out`", etc.)  I'm building from the latest `main` branch.

**Comment by sezero** [comment]
Is this `clang-cl` i.e. clang in use from MSVC, or some clang-based mingw?

Either way, I am not familiar with windows-targeting clang toolchains: @icculus,
@slouken, or someone else please take a look. Re-opening the issue.

**Comment by jbsolomon** [comment]
@sezero -- it's just the regular GNU-like Clang driven from the ordinary windows terminal (not touching MSVC) by Ninja generated by CMake 3.21.

**Comment by icculus** [comment]
...so we need to disable AVX support on Windows+Clang for now, then?

**Comment by slouken** [comment]
@jbsolomon, thanks for the details on your setup. I was able to reproduce this and fix it.

**Comment by sezero** [comment]
Huh. Looked at clang5, 11 and 12, their `immintrin.h` specifically doesn't include `avxintrin.h`
for `_MSC_VER` unless `__AVX__` is defined (or `__has_feature(modules)`, whatever
that is..)

**Comment by slouken** [comment]
Yup, by default clang won't include AVX intrinsics unless it's building with AVX instructions enabled. That's not safe to do by default, so I just disabled AVX unless that's turned on.

**Comment by sezero** [comment]
Well, I can build for x86_64 linux using clang >= 5 with avx - the new patch disables that.
And `clang -E -dD -xc /dev/null grep AVX` does print empty. This is a big hammer only to
fix windows+clang.

BTW, the relevant portion of clang's immintrin.h is this:
```c
#if !(defined(_MSC_VER) || defined(__SCE__)) || __has_feature(modules) ||      \
    defined(__AVX__)
#include <avxintrin.h>
#endif
```

Do note, that it does the same blacklisting for SSE, MMX, etc.

**Comment by sezero** [comment]
clang >= 5 also builds for MacOSX i686 and x86_64 without this patch, so it limited a lot:
I think you need a different solution for this.

**Comment by slouken** [comment]
Suggestions are welcome!

Have you looked at the relevant clang headers on Linux to see why they work? I would have expected something similar there - most compiler don't allow intrinsics unless the instruction set is valid for the compile.

**Comment by sezero** [comment]
> Suggestions are welcome!

I suggest something like this against current git: (@jbsolomon: please confirm)
```diff
diff --git a/src/audio/SDL_audiocvt.c b/src/audio/SDL_audiocvt.c
index aec6766..f422b2b 100644
--- a/src/audio/SDL_audiocvt.c
+++ b/src/audio/SDL_audiocvt.c
@@ -47,7 +47,7 @@
 #define HAVE_AVX_INTRINSICS 1
 #endif
 #if defined __clang__
-# if (__clang_major__ < 5) || !defined(__AVX__)
+# if (__clang_major__ < 5) || defined(_MSC_VER) || defined(__SCE__)
 #   undef HAVE_AVX_INTRINSICS
 # endif
 #elif defined __GNUC__
```

> Have you looked at the relevant clang headers on Linux to see why they work?

I think the key is `!(defined(_MSC_VER) || defined(__SCE__))` : since neither of
them are defined, clang includes avxintrin.h in immintrin.h

>  I would have expected something similar there - most compiler don't allow intrinsics unless the instruction set is valid for the compile.

The `target` pragma down below the file is supposed to handle that.

**Comment by slouken** [comment]
Okay, that makes sense and I confirmed it fixes the issue.

Thanks!
