### ISSUE TITLE
NEON implementation of Convert51ToStereo

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#4534]
Since we're on the topic of optimizing audiocvt, it'd be great to have 5.1->Stereo optimized for ARM as well - this is important for supporting cases like FAudio where [a stream may default to 5.1 output](https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio_platform_sdl2.c#L290-L333) expecting the platform layer to downmix to stereo when applicable.

**Comment by icculus** [comment]
I'm assigning myself, but if someone gets here before me, I don't mind. I won't get to this before 2.0.16 ships.

**Comment by icculus** [comment]
Here's a first shot at this...I've not even attempted to compile it yet! This is just the SSE version converted to use NEON intrinsics.

Beyond the likelihood that any SIMD code is wrong until rewritten three times, there are some other details to deal with:

- Make sure this only compiles when NEON is available to the compiler.
- Make sure this only runs when NEON is available to the CPU.
- Make sure this actually works with unaligned data. My understanding is that NEON allows unaligned accesses, but it's not clear if this is true in real life. If this will cause segfaults or whatever, we need to check if `src` is aligned to 16 bytes at start and fall back to scalar code for the entire buffer if not (as dst == src and both will move in 16 and 48 byte increments, so they're either always both aligned or both not). If unaligned access is merely slower but still better than scalar, we're golden.

I'm posting here in case someone wants to run with this, but I'll eventually come around and finish this off.

```c
#if HAVE_NEON_INTRINSICS
/* Convert from 5.1 to stereo. Average left and right, distribute center, discard LFE. */
static void SDLCALL
SDL_Convert51ToStereo_NEON(SDL_AudioCVT * cvt, SDL_AudioFormat format)
{
    float *dst = (float *) cvt->buf;
    const float *src = dst;
    int i = cvt->len_cvt / (sizeof (float) * 6);
    const float two_fifths_f = 1.0f / 2.5f;
    const float32x4_t two_fifths_v = vdupq_n_f32(two_fifths_f);
    const float32x4_thalf = vdupq_n_f32(0.5f);

    LOG_DEBUG_CONVERT("5.1", "stereo (using NEON)");
    SDL_assert(format == AUDIO_F32SYS);

    /* SDL's 5.1 layout: FL+FR+FC+LFE+BL+BR */

    /* Just use unaligned load/stores, it's the same NEON instructions and
       hopefully even unaligned NEON is faster than the scalar fallback. */
    while (i >= 2) {
        /* Two 5.1 samples (12 floats) fit nicely in three 128bit */
        /* registers. Using shuffles they can be rearranged so that */
        /* the conversion math can be vectorized. */
        const float32x4_t in0 = vld1q_f32(src);     /* 0FL 0FR 0FC 0LF */
        const float32x4_t in1 = vld1q_f32(src + 4); /* 0BL 0BR 1FL 1FR */
        const float32x4_t in2 = vld1q_f32(src + 8); /* 1FC 1LF 1BL 1BR */

        /* 0FC 0FC 1FC 1FC */
        const float32x4_t fc_distributed = vmulq_f32(half, vcombine_f32(vdup_lane_f32(vget_high_f32(in0), 0), vdup_lane_f32(vget_low_f32(in2)), 0));

        /* 0FL 0FR 1BL 1BR */
        const float32x4_t blended = vcombine_f32(vget_low_f32(in0), vget_high_f32(in2));

        /*   0FL 0FR 1BL 1BR */
        /* + 0BL 0BR 1FL 1FR */
        /* =  0L  0R  1L  1R */
        float32x4_t out = vaddq_f32(blended, in1);
        out = vaddq_f32(out, fc_distributed);
        out = vmulq_f32(out, two_fifths_v);

        vst1q_f32(dst, out);

        i -= 2; src += 12; dst += 4;
    }

    /* Finish off any leftovers with scalar operations. */
    while (i) {
        const float front_center_distributed = src[2] * 0.5f;
        dst[0] = (src[0] + front_center_distributed + src[4]) * two_fifths_f;  /* left */
        dst[1] = (src[1] + front_center_distributed + src[5]) * two_fifths_f;  /* right */
        i--; src += 6; dst+=2;
    }

    cvt->len_cvt /= 3;
    if (cvt->filters[++cvt->filter_index]) {
        cvt->filters[cvt->filter_index] (cvt, format);
    }
}
#endif
```

**Comment by 1bsyl** [comment]
Ok, I've double-check and didn't have to do much, only two compiles typos ("float32x4_thalf" and vdup_lane_f32 misplaced parenthesis)

- added the define to determine when neon is available to compile + at runtime
- double-checked the value with a small testcase

With NEON, IIRC, the alignment wont make the app crash. If the address isn't aligned it simply wont be optimized for access.

**Comment by icculus** [comment]
@flibitijibibo, do you have an ARM game that downmixes from 5.1 handy? If not, I'm comfortable considering this done just with the test case here.
