### ISSUE TITLE
doesn't show IME candidate list in windows 10(chinese Input support)

### ISSUE THREAD

**Issue by iBruCe07** [libsdl-org/SDL#4539]
![image](https://user-images.githubusercontent.com/6389033/127075563-b0ec0829-c6a6-4954-b9b8-7105f5286835.png)

#include <SDL.h>
//#include <SDL_ttf.h>
#include <stdio.h>
#include <string>

int main(int argc, char* argv[])
{
	SDL_Init(SDL_INIT_VIDEO);
	SDL_bool done = SDL_FALSE;

	//TTF_Init();

	//TTF_Font* font = TTF_OpenFont("./SimHei.ttf", 20);

	SDL_Window* window = SDL_CreateWindow("ime_test",
		SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
		500, 500,
		0);

	SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, 0);

	std::string text, composition;
	int cursor, selection_len;

	SDL_Rect rect;
	rect.x = 100;
	rect.y = 100;
	rect.w = 100;
	rect.h = 100;

	SDL_StartTextInput();
	SDL_SetTextInputRect(&rect);
	while (!done) {
		SDL_Event event;
		while (SDL_PollEvent(&event)) {
			switch (event.type) {
			case SDL_QUIT:
				/* quitting */
				done = SDL_TRUE;
				break;
			case SDL_TEXTINPUT:
				text += event.text.text;
				break;
			case SDL_TEXTEDITING:
				composition = event.edit.text;
				cursor = event.edit.start;
				selection_len = event.edit.length;
				break;
			case SDL_KEYDOWN:
				if (event.key.keysym.sym == SDLK_RETURN || event.key.keysym.sym == SDLK_SPACE) {
					composition = "";
				}
			}
		}

		//SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
		//SDL_RenderClear(renderer);

		//auto surface = TTF_RenderText_Blended(font, (text + composition).c_str(), { 255, 255, 255 });
		//if (surface) {
		//	auto texture = SDL_CreateTextureFromSurface(renderer, surface);
		//	SDL_Rect dst_rect = { rect.x, rect.y, surface->w, surface->h };
		//	SDL_FreeSurface(surface);

		//	SDL_RenderCopy(renderer, texture, nullptr, &dst_rect);
		//	SDL_DestroyTexture(texture);
		//}

		SDL_RenderPresent(renderer);
		SDL_Delay(30);
	}

	//TTF_CloseFont(font);
	SDL_DestroyRenderer(renderer);
	SDL_DestroyWindow(window);
	//TTF_Quit();
	SDL_Quit();

	return 0;
}

**Comment by slouken** [comment]
@zreedy, is this fixed with your changes?

**Comment by zreedy** [comment]
@slouken This should be fixed now. We see this functioning in our software with the following hint enabled:
```
SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1");
```

**Comment by slouken** [comment]
Okay, thanks!
