### ISSUE TITLE
HAVE_IMMINTRIN_H define in SDL_config_windows.h

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#4540]
https://github.com/libsdl-org/SDL/commit/20eea021c6558e391c1b95316845dd5bdfad73ff from @JoelLinn defined HAVE_IMMINTRIN_H in SDL_config_windows.h
without checking compiler and its version, which would very well break
building user programs with older/different compilers. We should change
the line to something like the following i.e. MSVC >=2010, assuming the
original commit intended this to be for MSVC:
```
#if (defined(_M_IX86) || defined(_M_X64) || defined(_M_AMD64)) && (defined(_MSC_VER) && _MSC_VER >= 1600)
#define HAVE_IMMINTRIN_H 1
#endif
```
Is this OK? (It would also need expanding to gcc and clang later..)

Also: Other SDL_config_XXX.h headers, most notably SDL_config_macosx.h,
would need similar defining of HAVE_IMMINTRIN_H, too.

**Comment by icculus** [comment]
Go for it.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL/commit/e16fb60323f96085982dc033b7d4544d99ba3bc6 touch in windows and macosx configs, hopefully correct.
The android config might need a similar touch.

Not closing this myself, in case issues show up or there are more things to do.

**Comment by sezero** [comment]
I think this can be closed now.
