### ISSUE TITLE
Joycons softlock SDL when connecting them the second time 

### ISSUE THREAD

**Issue by german77** [libsdl-org/SDL#4544]
`SDL_JoystickOpen()` doesn't return any value the second time you try to use a joycon. Softlocking the program until both joycons are disconnected and the program restarted.

How to reproduce:

- Enable ` SDL_SetHint("SDL_JOYSTICK_HIDAPI_JOY_CONS", "1");`
- Initialize the joycons with `SDL_JoystickOpen()` and `SDL_GameControllerOpen()`
- The joycons will now have a set led number.
- End the program.
- Restart the program without turning the joycon off and on
- Program will freeze at `SDL_JoystickOpen()`

**Comment by slouken** [comment]
I don't have any joycons, @JibbSmart, can you take a look for the 2.0.16 release?

**Comment by JibbSmart** [comment]
Can do, Sam. I should be able to have a look in the next couple of days.On 28 Jul 2021 8:06 am, Sam Lantinga ***@***.***> wrote:
I don't have any joycons, @JibbSmart, can you take a look for the 2.0.16 release?

**Comment by german77** [comment]
Just as extra info. The pro controller doesn't have this issue. Seems like this only happens with joycons especially when you have left and right connected

**Comment by sulix** [comment]
For what it's worth, I can't reproduce this with on a Linux system without ``hid-nintendo`` or ``joycond``: even with both joycons paired as regular bluetooth HID devices.

Running
```
SDL_JOYSTICK_HIDAPI_JOY_CONS=1 ./testgamecontroller
```
works fine with the latest SDL git, even if I re-run it multiple times without disconnecting/reconnecting the controllers. They also work fine as joysticks (not using the ``SDL_GameController`` API).

In my case, there's no 'set led number', though, probably due to not having any joycon-specific drivers installed: they just keep showing the 'pairing' bouncing LED.

**Comment by slouken** [comment]
@JibbSmart, we'd like to ship 2.0.16 next week. Is this something you'll have time to look at over the weekend?

**Comment by JibbSmart** [comment]
@slouken Oh, almost certainly not 😬. I'll try to make the time, but I don't have time this weekend. But I can probably take a look during the work week.

**Comment by JibbSmart** [comment]
I haven't been able to look at it -- I've been debilitatingly unwell. I'll still get on it as soon as I can.

**Comment by slouken** [comment]
> I haven't been able to look at it -- I've been debilitatingly unwell. I'll still get on it as soon as I can.

I hope you feel better soon!

I got a pair of joycons, so I'll see if I can reproduce it today.

**Comment by slouken** [comment]
I'm not able to reproduce this on Windows. I tried both testjoystick and testgamecontroller.

@german77, are you able to reproduce this with testjoystick in the SDL test directory? What OS are you running?

**Comment by german77** [comment]
I'm running on windows. I haven't tried with the testjoystick of SDL. I will give it a go this night. 

I mainly seen this problem on the yuzu emulator and other users there have reported as well even with the latest SDL commit. I will provide a test code in a few hours, hopefully you guys can reproduce. I'm having trouble troubleshooting this issue myself.

**Comment by slouken** [comment]
Yes, please provide code that reproduces this for you and we can take a look.

Thanks!

**Comment by german77** [comment]
I don't have this issue anymore on latest SDL 2.26.1
