### ISSUE TITLE
`SDL2::SDL2-static` target doesn't silently disable itself when libSDL2.a isn't present

### ISSUE THREAD

**Issue by Conan-Kudo** [libsdl-org/SDL#4553]
In Fedora, we recently switched from Autotools to CMake for the build, but we had an interesting surprise occur from that: the generated CMake SDL2 targets from a build that produced both dynamic and static libraries caused things to choke when the static library wasn't present on the system. We split out the static library into a subpackage so that we don't have it used by default, but the broken target files made it so we needed to have it always, even though we don't want it.

This also had a side-effect in making applications link with the static library when we wanted to use the dynamic library. Can we have this fixed so that callers don't "see" the static target unless the .a file is present?

Reference downstream bug: [RHBZ#1965359](https://bugzilla.redhat.com/show_bug.cgi?id=1965359)

**Comment by slouken** [comment]
Do you have a tested patch for this? Ryan and I are both more familiar with autotools than cmake, so I want to make sure any change is vetted downstream.

**Comment by Conan-Kudo** [comment]
I don't have a patch yet, though I have started looking into it.

**Comment by Conan-Kudo** [comment]
I've made a patch to try to fix this and submitted it as #5171.
