### ISSUE TITLE
wayland clients do not restore from maximised and fullscreen modes

### ISSUE THREAD

**Issue by christianrauch** [libsdl-org/SDL#4562]
When transitioning from floating -> maximised -> floating, the window will not restore to its previous floating mode but keep the maximised resolution.

Reproduce:
1. start `testgl2 --resizable`
2. maximise the window (Ctrl+M client-side or Win+Up server-side)
3. restore to floating (Ctrl+M client-side or Win+Down server-side)

The window will not have the maximised size, but should have the previous floating dimension. I believe this is supposed to be managed by `SDL_Rect windowed` from `SDL_Window`.

**Comment by flibitijibibo** [comment]
I wasn't able to reproduce this with the xdg backend using Plasma 5.22 or the libdecor backend using GNOME 40 (both tests run on Fedora 34). Tested with commit https://github.com/libsdl-org/SDL/commit/e5594e66778707c3bd9e1bce229140564e0c9844.

**Comment by christianrauch** [comment]
This is because later GNOME Shell versions send the floating state to the client (implemented by me). Older versions like 3.36 will send (0,0) and cause this behaviour.

**Comment by flibitijibibo** [comment]
I would definitely pin it in the configure callback then - possibly this bit here:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandwindow.c#L316

We fire SDL `RESIZED` events for all resizes that come from a configure callback - it's possible that either A: the maximize->floating change doesn't have the old window size passed here, or B: the maximize event writes over too much and the windowed rect gets overwritten, as you suggested.
