### ISSUE TITLE
SDL_OpenURL, LD_PRELOAD & Steam Overlays

### ISSUE THREAD

**Issue by darksylinc** [libsdl-org/SDL#4565]
**Note:** I'm creating this post out of experience implementing the exact same thing; I didn't test it on SDL_OpenURL personally but I can see the implementation has the same problem unless I missed somewhere where LD_PRELOAD is somehow not inherited to the child process.

On Linux, Steam Overlays integration uses `LD_PRELOAD` to inject its overlays.

This causes trouble when spawning Chrome because Chrome has anti-tamper mechanisms (and also injection gets confused with ANGLE libs) that prevents Chrome from launching correctly: Chrome may take a very long time to spawn (which makes waitpid stall for half a minute or more) or even causing weird crashes in the forked process (including very weird crashes like getting an apport for an mkdir process)

To make it work properly on Linux (when Steam Overlay integration is on) one must do:

```cpp
std::scoped_lock lock(mutex); // In case environment vars are accessed from other threads

const char *oldEnvValueCstr = getenv( "LD_PRELOAD" );
const std::string oldEnvValue = oldEnvValueCstr ? oldEnvValueCstr : ""; // hard copy
unsetenv( "LD_PRELOAD" );

SDL_OpenURL( "https://example.com" );

if( !oldEnvValue.empty() )
    setenv( "LD_PRELOAD", oldEnvValue.c_str(), 1 );
```

This leads to a few questions:

1. Should SDL2 alter `setenv`?  This would break if environment variables are accessed from another thread; since setenv/getenv/unsetenv are not inherently thread-safe.
2. Should `SDL_OpenURL2` be created that (optionally via 2nd boolean argument?) performs `setenv` automatically? (caller is responsible for ensuring thread safety of env calls)
3. Should SDL2 document this specific-but-very-relevant behavior in `SDL_OpenURL` comments? (probably yes)

Without knowledge of what's going on, it makes Linux builds that open internet links (or e.g. go to app's Steam store page) look extremely broken, buggy and generally a bad experience and devs have a hard time figuring out what's going wrong; until someone notices disabling Steam Overlays workarounds the problem but nobody knows why.

What's worse is that this is the case of "works on my machine" but "breaks when deployed from Steam"; so I believe this case should definitely be at least documented, and at best handled.

**Comment by dos1** [comment]
FWIW, `SDL_OpenURL` forks, so environment can be changed in the child process without having to worry about thread-safety.

**Comment by slouken** [comment]
Fixed, thanks for the heads up!
