### ISSUE TITLE
Mouse motion events not called while dragging a file over window in Linux

### ISSUE THREAD

**Issue by Wesxdz** [libsdl-org/SDL#4568]
SDL_GetMouseState does not return correct coordinates while dragging a file over a window (vs GLFW which does callback mouse coordinates on file drag)
Ubuntu 20.04.2 LTS x86_64

**Comment by Wesxdz** [comment]
Fortunately, it is possible as a workaround to get the mouse position with SDL_GetGlobalMouseState

**Comment by slouken** [comment]
In SDL3 there is a new event `SDL_EVENT_DROP_POSITION` to handle this.
