### ISSUE TITLE
Haiku: undefined reference to `operator new(unsigned long)'

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4590]
Buildbot coming back online, here's an error while building for Haiku:

All the details are here: https://buildbot.libsdl.org/#/builders/4/builds/755

Note this is a Haiku nightly from months and months ago, so it's possible this is an issue with the builder, but it would be _super_ helpful if someone from Haiku could grab the latest in revision control and check that it builds, unpatched (paging @pulkomandy, if you can tag someone appropriate here, I'd appreciate it), since as far as I know, 2.0.16 is shipping without any patches from HaikuPorts needed.

```
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: build/.libs/SDL_BeApp.o: in function `StartBeApp':
/boot/home/buildbot/worker/SDL/sdl-haiku-amd64/src/src/main/haiku/SDL_BeApp.cc:74: undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: build/.libs/SDL_bframebuffer.o: in function `HAIKU_CreateWindowFramebuffer':
/boot/home/buildbot/worker/SDL/sdl-haiku-amd64/src/src/video/haiku/SDL_bframebuffer.cc:78: undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: build/.libs/SDL_bmessagebox.o: in function `void std::vector<SDL_MessageBoxButtonData const*, std::allocator<SDL_MessageBoxButtonData const*> >::_M_realloc_insert<SDL_MessageBoxButtonData const*>(__gnu_cxx::__normal_iterator<SDL_MessageBoxButtonData const**, std::vector<SDL_MessageBoxButtonData const*, std::allocator<SDL_MessageBoxButtonData const*> > >, SDL_MessageBoxButtonData const*&&)':
/boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/8.3.0/include/c++/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: build/.libs/SDL_bopengl.o: in function `HAIKU_GL_CreateContext':
/boot/home/buildbot/worker/SDL/sdl-haiku-amd64/src/src/video/haiku/SDL_BWin.h:140: undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: build/.libs/SDL_bopengl.o: in function `HAIKU_GL_RebootContexts':
/boot/home/buildbot/worker/SDL/sdl-haiku-amd64/src/src/video/haiku/SDL_BWin.h:140: undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: build/.libs/SDL_bopengl.o:/boot/home/buildbot/worker/SDL/sdl-haiku-amd64/src/src/video/haiku/SDL_BWin.h:140: more undefined references to `operator new(unsigned long)' follow
```

**Comment by pulkomandy** [comment]
Hello,

This issue is similar to what was solved by https://gist.github.com/jessicah/5ee4aaefcc4c28adf7be3a6238be6497 in the autotools build.

Apparently in cmake, the equivalent fix would be something like this:

```
if (HAIKU)
    set(LINKER_LANGUAGE CXX)
endif()
```

https://cmake.org/cmake/help/latest/prop_tgt/LINKER_LANGUAGE.html

**Comment by sezero** [comment]
That would be nice having in cmake, I guess, but the buildbot failure in question seems to be from an autotools build to me.

**Comment by pulkomandy** [comment]
It seems I'm not fully awake this early in the morning.

Yes, it's an autotools build, so, is @jessicah 's patch somehow not working in this build? It's hard to tell because make does not show the exact command that it runs, and the configure script does not say what it sets LINKER to.

**Comment by icculus** [comment]
Okay, verbose builds are now enabled for all (well, most) platforms. Here's the same build for Haiku:

https://buildbot.libsdl.org/#/builders/4/builds/758

**Comment by pulkomandy** [comment]
It seems libtool is invoked with "g++" as it should be (line 523), but then the command it eventually runs is "ccache gcc" (line 527).

Does ccache need to be configured to use g++ as well?

**Comment by sezero** [comment]
Can ccache please die? At least on the buildbot? It can lead to obscure
failures, as apparent from this case.

**Comment by icculus** [comment]
> Can ccache please die? At least on the buildbot? It can lead to obscure failures, as apparent from this case.

It makes the buildbot run a job to completion in a fraction of the time, though. It's not the "ccache" though, it's the hardcoded "gcc" in our buildbot config in this case, I think. Checking now.

**Comment by icculus** [comment]
So some part of the system is using $CC for all builds (probably because SDL doesn't expect C++ files to be in the build), so it builds the Haiku-specific C++ code with $CC, too...which isn't a big deal, because GCC sees C++ file extensions and compiles it as C++ by default. But that's probably worth fixing in SDL to use $CXX to compile C++ code, at some point.

I forced the LD variable to `g++` and that fixed the build. I noticed it's doing this:

`/bin/sh ./libtool --tag=CC --mode=link ccache g++`

...and I thought we tweaked this to use `--tag=CXX` on Haiku...? That would be the likely specific problem.

But again, this might be a quirk of the buildbot or the worker's now-ancient Haiku nightly install, which I'll upgrade later. If a Haiku user says "this builds out of the box without drama on my totally normal Haiku install" then there's no problem at all here.

**Comment by icculus** [comment]
Yeah, I'll patch up CMakeLists.txt today in any case.

**Comment by icculus** [comment]
(Fwiw, right now the buildbot doesn't build both configure and CMake builds even if a target could support both...it would just add time and complexity to each run, but it would likely catch bugs.)

**Comment by icculus** [comment]
Figured it out, this is solid out of the box on Haiku now.
