### ISSUE TITLE
QNX build broken...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4591]
Buildbot coming back online, here's an error while building for QNX:

All the details are here: https://buildbot.libsdl.org/#/builders/14/builds/643

This might not be super-important; if this takes more than a minute to obviously fix, we should probably just drop QNX from the buildbot; the dev license I have for it is many years out of date at this point, and I have no idea what a modern QNX offers.

**Comment by sezero** [comment]
The key to failure is probably `checking for hidapi support... yes` at line 382 of configure output.
SDL_hidapijoystick.c is not configured for QNX.

**Comment by slouken** [comment]
It looks like QNX does have inotify_add_watch(), etc.
Can I jump onto the VM to verify?

**Comment by sezero** [comment]
What hidapi backend is qnx using after dd68307, libusb? The configury doesn't
seem to detect that, so the question is it builds somehow but does it run??

**Comment by icculus** [comment]
I don't know and don't have a reasonable way to test it, so "it builds and maybe doesn't actually work" is acceptable for 2.0.16, and after, until someone files a bug report saying otherwise.

Somewhere I had an extremely basic VMware image that booted an actual copy of qnx, but I don't know where at this point. This isn't something we can support more than making sure it continues to compile at the moment.

**Comment by sezero** [comment]
It would have been much easier to simply disable hidapi for qnx in configury.

**Comment by sezero** [comment]
Does qnx buildbot behave if you revert dd68307 and apply the following?
```diff
diff --git a/configure.ac b/configure.ac
index 2dbfd29..99ef331 100644
--- a/configure.ac
+++ b/configure.ac
@@ -3396,7 +3396,11 @@ CheckHIDAPI()
                   , enable_hidapi_libusb=maybe)
 
     if test x$enable_joystick = xyes -a x$enable_hidapi = xyes; then
+        hidapi_support=yes
         case "$host" in
+            *-*-nto*)
+                hidapi_support=no
+                ;;
             # libusb does not support iOS
             *-ios-* )
                 enable_hidapi_libusb=no
@@ -3408,7 +3412,6 @@ CheckHIDAPI()
                 ;;
         esac
 
-        hidapi_support=yes
         if test x$enable_hidapi_libusb = xyes; then
             PKG_CHECK_MODULES([LIBUSB], [libusb-1.0], have_libusb=yes, have_libusb=no)
             save_CPPFLAGS="$CPPFLAGS"
diff --git a/configure b/configure
index fd4d670..aebabbe 100755
--- a/configure
+++ b/configure
@@ -24619,7 +24619,11 @@ fi
 
 
     if test x$enable_joystick = xyes -a x$enable_hidapi = xyes; then
+        hidapi_support=yes
         case "$host" in
+            *-*-nto*)
+                hidapi_support=no
+                ;;
             # libusb does not support iOS
             *-ios-* )
                 enable_hidapi_libusb=no
@@ -24631,7 +24635,6 @@ fi
                 ;;
         esac
 
-        hidapi_support=yes
         if test x$enable_hidapi_libusb = xyes; then
 
 pkg_failed=no
```

**Comment by slouken** [comment]
We shouldn't revert https://github.com/libsdl-org/SDL/commit/dd683073bb3bb06c8014b8dbd036475f032e3484, as we should be checking feature, not platform.

We also probably shouldn't just disable hidapi_support for QNX, as it may actually be functional with the Linux hidraw support. It can stay the way it is until someone using QNX can comment.
