### ISSUE TITLE
Windows build without OpenGL also breaks DX9/DX11

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4593]
When building SDL2 with these options using MinGW-w64 for an x64 target:

```
./configure --disable-wasapi --enable-sse3 --enable-static --disable-shared --enable-ssemath --disable-video-opengles --disable-video-opengl --enable-video-vulkan --disable-libsamplerate
```
Then SDL_CreateRenderer() will fail to create *any* accelerated renderer in both wine on Linux, and in my Windows 10 test VM (which should have the Microsoft-provided DirectX software emulation, which to SDL should look like accelerated DirectX). Just SDL's software renderer works.

When removing the options to disable OpenGL and rebuilding, all of a sudden SDL_CreateRenderer() is also fine with returning a DirectX renderer both inside the VM and in wine. So there's definitely something fishy going on here. Tested this on revision: 32f909f7e36a270d3b761bf15d320906ecd31eb1

**Comment by slouken** [comment]
@ell1e I'm moving this out of the 2.0.18 milestone for now, since we haven't heard back.

**Comment by ell1e** [comment]
That sounds reasonable, and sorry that I forgot about this for a bit. Here are the build files:

[config.log](https://github.com/libsdl-org/SDL/files/7497414/RFS2-2021-11-08-1-Windows-x64-SDL2-config.log.txt)

[config.status](https://github.com/libsdl-org/SDL/files/7497416/RFS2-2021-11-08-1-Windows-x64-SDL2-config.status.txt)

[SDL_config.h](https://github.com/libsdl-org/SDL/files/7497417/RFS2-2021-11-08-1-Windows-x64-SDL2-SDL_config.h.txt) (copied from `SDL_repo_tree/include/SDL_config.h` after the build, I couldn't find any other one)

**Comment by slouken** [comment]
Okay, this seems reasonable... I'll try to build with this configuration and see what happens here.
```
#define SDL_VIDEO_DRIVER_WINDOWS 1
#define SDL_VIDEO_RENDER_D3D 1
#define SDL_VIDEO_RENDER_D3D11 1
```

**Comment by slouken** [comment]
Yeah, building with that configuration works for me here. I think you'll have to debug and find out what's happening for you.

**Comment by ell1e** [comment]
Okay, here are the updated files:

[SDL2-config.log](https://github.com/libsdl-org/SDL/files/7497845/RFS2-2021-11-08-1-Windows-x64-SDL2-config.log.txt)
[config.status](https://github.com/libsdl-org/SDL/files/7497848/RFS2-2021-11-08-1-Windows-x64-SDL2-config.status.txt)
[SDL_config.h](https://github.com/libsdl-org/SDL/files/7497849/RFS2-2021-11-08-1-Windows-x64-SDL2-SDL_config.h.txt)

The files above were outdated and kind of irrelevant, my bad. However, I'm not so sure what they would tell you anyway, it doesn't seem to be a configure problem necessarily.

> works for me here

My apologies if you did, but did you actually try running a program with `SDL_CreateRenderer` with the accelerated option? Otherwise you may not have looked at anything too relevant (also since I uploaded the wrong files, oops...), since the build output isn't what brought me here.

Rather the issue is that when I disable OpenGL (and **not** DirectX/D3D/Vulkan, `--disable-video-opengl --disable-video-opengles --enable-video-vulkan` - see also the correct `config.log` above) then `SDL_CreateRenderer` will always fail with the accelerated flag for no obvious reason, both with wine and my Windows VM. If I just change the `--disable-video-opengl` to `--enable-video-opengl` then I'll suddenly successfully get an accelerated renderer **named "direct3d"** (???) in both wine and my Windows VM. That just doesn't make any sense to me, why would the OpenGL option influence the ability to get a DirectX backend? There seems to be something wrong here.

In any case, if there's no time to look into this I understand since it's a bit of an obscure config. In that case it would probably make more sense to close the issue rather than assign it to me, though.

**Comment by slouken** [comment]
I build SDL with this SDL_config.h:
```

#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDARG_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMORY_H 1
#define HAVE_WCHAR_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MATH_H 1
#define HAVE_IMMINTRIN_H 1
#define SDL_VIDEO_DRIVER_DUMMY 1
#define SDL_AUDIO_DRIVER_DISK 1
#define SDL_AUDIO_DRIVER_DUMMY 1
#define SDL_VIDEO_VULKAN 1
#define HAVE_DDRAW_H 1
#define HAVE_DINPUT_H 1
#define HAVE_DSOUND_H 1
#define HAVE_DXGI_H 1
#define HAVE_XINPUT_H 1
#define HAVE_MMDEVICEAPI_H 1
#define HAVE_AUDIOCLIENT_H 1
#define SDL_JOYSTICK_HIDAPI 1
#define SDL_VIDEO_DRIVER_WINDOWS 1
#define SDL_VIDEO_RENDER_D3D 1
#define SDL_VIDEO_RENDER_D3D11 1
#define SDL_AUDIO_DRIVER_WINMM 1
#define SDL_AUDIO_DRIVER_DSOUND 1
#define SDL_JOYSTICK_RAWINPUT 1
#define SDL_JOYSTICK_XINPUT 1
#define SDL_JOYSTICK_DINPUT 1
#define SDL_HAPTIC_XINPUT 1
#define SDL_HAPTIC_DINPUT 1
#define HAVE_SENSORSAPI_H 1
#define SDL_SENSOR_WINDOWS 1
#define SDL_POWER_WINDOWS 1
#define SDL_FILESYSTEM_WINDOWS 1
#define SDL_THREAD_GENERIC_COND_SUFFIX 1
#define SDL_THREAD_WINDOWS 1
#define SDL_TIMER_WINDOWS 1
#define SDL_LOADSO_WINDOWS 1
#define SDL_JOYSTICK_VIRTUAL 1
```

and then ran this code:
```
    window = SDL_CreateWindow( "", 0, 0, WINDOW_WIDTH, WINDOW_HEIGHT, SDL_WINDOW_SHOWN );
    if ( !window )
	{
		quit( 2 );
	}

    renderer = SDL_CreateRenderer( window, -1, SDL_RENDERER_ACCELERATED );
    if ( !renderer )
    {
        quit( 2 );
    }
```

and I got an accelerated D3D renderer.

I think you'll need to run under the debugger and find out what's happening in SDL_CreateRenderer(). This should work, as far as I know. I'm going to close the bug, feel free to reopen if you find out more information.

Cheers,
