### ISSUE TITLE
Segfault in hidapi backend

### ISSUE THREAD

**Issue by Yamakaky** [libsdl-org/SDL#4596]
For access to controller sensors (gyro, accelerometer), SDL uses a modified bundled version of SDL2. For example, these fields are SDL specific https://github.com/libsdl-org/SDL/blob/main/src/hidapi/hidapi/hidapi.h#L87-L91. However, with my setup described below, the modified and upstream version seems to get mixed up, and I get a segfault. I'm not sure if it's a problem in SDL or my setup, but here it is.

Setup: I use SDL in rust using the [rust-sdl2](https://github.com/Rust-SDL2/rust-sdl2) library. Its static binary feature uses vcpkg, so that SDL can get static linked in the binary. I [modified the vcpkg port](https://github.com/Yamakaky/vcpkg/commit/f82e436a4ef627f5f4eec6b80103b242076d0135) to add `-DHIDAPI=ON`. I do that to be able to read controller sensors.

Example of affected binary:
- Get "gyromouse linux" at https://github.com/Yamakaky/joy/actions/runs/1100724491
- in `gdb gyromouse`:
  - `run list`
  - `break hid_enumerate` (call here: https://github.com/libsdl-org/SDL/blob/main/src/joystick/hidapi/SDL_hidapijoystick.c#L1054)
  - `finish`
  - `step`
  - `p *devs`
  - `p *$1`

Note that both have a type named `hid_device_info`, but only devs (SDL specific) has the additional SDL fields, while the return value (hidapi function) doesn't. That would imply either that the upstream version gets built or the system version is used. The segfault comes from the fact that the `next` pointer returned by the function gets read as the additional SDL fields, and the `next` pointer read is from random data after the struct (0x21 on my system, for example).

One difference I can find is that `hid.c` (modified hidapi) [uses `#include "hidapi.h"](https://github.com/libsdl-org/SDL/blob/main/src/hidapi/linux/hid.c#L53) while `SDL_hidapijoystick_c.h [uses `#include "../../hidapi.hidapi."](https://github.com/libsdl-org/SDL/blob/main/src/joystick/hidapi/SDL_hidapijoystick_c.h#L30). Maybe one uses the system hidapi.h while the other uses the SDL specific one? I tried to find such a difference in the cmake config, but couldn't find it.

Other thing I noticed:
- if I install hidapi in ubuntu before building SDL, I get this behaviour.
- If I install hidapi after (so SDL builds without system hidapi), I don't get motion events, so I assume hidapi isn't built/used? From what I understand, the system hidapi should not affect the build at all?

I'm not sure where to go from there, could someone with a better understanding of the SDL build system check if everything is OK with the hidapi subsystem? I can try to get a more simple setup if more information is needed.

**Comment by slouken** [comment]
I was able to reproduce this.

In order to reproduce this, I needed to statically link libhidapi as well as libSDL2 and have libhidapi before libSDL2 on the link line.

**Comment by slouken** [comment]
The right way to fix this is to prefix the hidapi symbols used by SDL so they don't collide with the system hidapi library. Unfortunately this involves changing the Android hidapi library and the Apple hidapi frameworks, so this won't make it for 2.0.16.

**Comment by Yamakaky** [comment]
OK, so after 2 days of debug I FINALLY managed to find that my build system was linking hidapi for an unrelated optional feature, even though I disabled it. I was starting to go mad. I added a check so that static sdl and this feature can't be used together, which is not a problem for my use case. I'm closing this one and opening another. Thanks for the help!
