### ISSUE TITLE
Artifacts when changing the projection matrix

### ISSUE THREAD

**Issue by NePutin94** [libsdl-org/SDL#4599]
I scale the view using a projection matrix:
```C++
            SDL_Rect v{0, 0, getSize().x, getSize().y};
            SDL_RenderSetViewport(Context::GetContext(), &v);
            glMatrixMode(GL_PROJECTION);
            glLoadIdentity();
            glLoadMatrixf(view->getMatrix());
            glMatrixMode(GL_MODELVIEW);
 ````
 And everything looks fine until I change the scale 2 or 3 times. Then `SDL_RenderDrawLineF` draws lines incorrectly. 
 Scaling by 2 times:
![изображение](https://user-images.githubusercontent.com/25349002/128549279-48983e91-ee88-4f49-87bb-5951e8d5a04c.png)
Scaling by 4 times:
![изображение](https://user-images.githubusercontent.com/25349002/128549019-7f1c4543-25ec-49ad-ad32-9531911b5519.png)
In fact, there should be a square perfectly along the edges of the sprite. 
For example, if you scaled the sprite itself:
![изображение](https://user-images.githubusercontent.com/25349002/128549224-f61f6045-a443-4ed3-a3d0-f480f7b62c22.png)

**Comment by slouken** [comment]
Ryan, is this something you can look at really quick today? If not, we can bump it to 2.0.18.

**Comment by icculus** [comment]
If this isn't just that the renderer isn't aware that the projection matrix changed (try SDL_RenderFlush between using SDL_Render calls and OpenGL), then we can't fix this for 2.0.16.

**Comment by NePutin94** [comment]
I don't quite understand what it means between opengl and SDL_Render calls.
I did it this way but nothing has changed:
```C++
            glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
            glClear(GL_COLOR_BUFFER_BIT);
            
            SDL_Rect vRect{0, 0, w.getSize().x, w.getSize().y};
            SDL_RenderSetViewport(Context::GetContext(), &vRect);
            glMatrixMode(GL_PROJECTION);
            glLoadIdentity();
            glLoadMatrixf(v.getMatrix());
            glMatrixMode(GL_MODELVIEW);
            SDL_RenderFlush(Context::GetContext());
            
            DebugDraw::DrawSpriteDebug(o.sprite, w);
            
            ImGui::Render();
            ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
            
            SDL_GL_SwapWindow(getWindow());
```
I also don't call `SDL_RenderPresent` because I use imgui and call `SDL_GL_SwapWindow`. `DrawSpriteDebug` draws a sprite and its rectangle using `SDL_RenderDrawLineF`. 
Even if I somehow change the texture rect for the sprite (I made it smaller in height and width) here's what happens, on the right and bottom there is a space between the red line and the sprite itself, although in fact it does not exist. The red line should run strictly along the border of the sprite. And the error in the display of lines turns out to be some small, it just appears at some point and does not change in any way. There may be an error in my matrix, but still the position of the lines relative to the sprite should be unchanged.
![изображение](https://user-images.githubusercontent.com/25349002/128558690-bcf2a733-0798-4efb-b7ec-274858574ecd.png)
I can use `SDL_RenderSetScale `and it works, but it's not exactly what I need.
![изображение](https://user-images.githubusercontent.com/25349002/128559606-becbabdb-05c9-487e-bc7d-e3a41a132063.png)

**Comment by NePutin94** [comment]
I used `glOrtho` to change the scale, but still this problem appears.
```C++
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        glOrtho(0.0, x, y, 0.0, 0.0, 1.0);
        glMatrixMode(GL_MODELVIEW);
        SDL_RenderFlush(renderer);

```
![изображение](https://user-images.githubusercontent.com/25349002/128607223-e74e12e6-8026-4ac8-ad2d-fad7a2cdc095.png)
If you change the view matrix, the problem also remains and everything looks exactly the same as in the screenshot above.
```C++
        glMatrixMode(GL_MODELVIEW);
        glPopMatrix();
        glLoadIdentity();
        glTranslatef( -x, -y, 0.f );
        glScalef(x2,y2,0.f);
        glPushMatrix();
        SDL_RenderFlush(renderer);
```

**Comment by 0x1F9F1** [comment]
The problem looks to be that any matrix-based scaling interferes with how [GL_QueueDrawLines](https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/render/opengl/SDL_render_gl.c#L891) achieves pixel-perfect results.
As noted in the function's comments, first the positions are offset by half a pixel, then the last segment is extended by 1 pixel.
If you introduce, for example, a 4x scaling factor, now all the lines are offset by 2 pixels, and the last line is 4 pixels longer.

I can't imagine there is anything which can realistically be done on SDL's side, since you are modifying GL state without the renderer knowing.

**Comment by slouken** [comment]
Yup, there's nothing you can do here. SDL_RenderSetScale() is the correct way to do this with the 2D renderer.
