### ISSUE TITLE
Pending static analysis issues...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4600]
Something to shake out for the next release: static analysis issues. At time of writing, there's 10 of them. Sometimes they're false positives or extremely unlikely to be hit in real life, but they're always worth grinding out.

Each build has the analysis results linked in it, like the "upload" link at the end of this build...

https://buildbot.libsdl.org/#/builders/17/builds/628

...but the latest is always at the top of this list, too:

https://buildbot.libsdl.org/sdl-static-analysis/sdl-macos-static-analysis/?C=M;O=D

(and eventially, we'll use this on things other than macOS builds...)

**Comment by meyraud705** [comment]
I sometime run clang-tidy on SDL. It gives the same warnings and I already checked some of them:

**Assigned value is garbage or undefined	audio/SDL_wave.c	MS_ADPCM_DecodeBlockData	624**
I did not check this one.

**Assigned value is garbage or undefined	video/SDL_surface.c	SDL_ConvertSurface	1205**
On step 18, assume `surface->format->palette->ncolors` is 0, so nothing is written to `surface->format->palette->colors`.
On step 25, assume `surface->format->palette->ncolors` is different from 0, so we read from `surface->format->palette->colors`.
Value of `ncolors` is not modified between these 2 step: **false positive**.
The analyzer does not know what is going on in `SDL_LowerBlit` and assumes `ncolors` may be modified.

**Called function pointer is null (null dereference)	video/SDL_egl.c	SDL_EGL_LoadLibrary	522**
On step 12, `SDL_EGL_LoadLibraryOnly` return -1 (from `SDL_SetError`) and value is stored in `library_load_retcode`.
On step 14, assume `library_load_retcode` is 0: **false positive**.
The analyzer does not know that `SDL_SetError` always return -1.

**Dead increment	joystick/SDL_joystick.c	SDL_CreateJoystickName	1771**
**Dead increment	joystick/SDL_joystick.c	SDL_CreateJoystickName	1775**
These are correct but harmless. You should check the code above thought: on line 1761 `name` is shortened but `len` is not modified.

**Dereference of null pointer	joystick/SDL_joystick.c	SDL_JoystickRumbleTriggers	916**
**Dereference of null pointer	joystick/SDL_joystick.c	SDL_JoystickRumble	882**
These assume that `SDL_JoystickUpdate` is called with `joystick->driver` being NULL. It should not be possible but comment on line 1549 say it happened:
 > /* This should always be true, but seeing a crash in the wild...? */

You should check before calling any function from `joystick->driver`.

**Result of operation is garbage or undefined	video/SDL_bmp.c	SDL_LoadBMP_RW	415**
**Result of operation is garbage or undefined	video/SDL_bmp.c	SDL_LoadBMP_RW	411**
On step 33, assume `(surface->format)->palette` is not NULL.
On step 41, assume biBitCount is 32.
I think that a 32 bit depth surface does not have a palette, so this is a **false positive**.

**Uninitialized argument value	video/SDL_video.c	SDL_SetWindowDisplayMode	1172**
On step 32, `SDL_GetWindowDisplayMode` return -1 (from `SDL_SetError`).
On step 33 , assume `SDL_GetWindowDisplayMode` returned 0: **false positive**.

**Comment by 1bsyl** [comment]
Since GLES2_QueueCopy would now draw triangles.
This could even be simplified, for all back-end that have RenderGeometry : 
-  by removing  QueueCopy and SDL_RENDERCMD_COPY from the backend
-  in SDL_render.c :  SDL_RenderCopy calls QueueCmdGeometry()

(...maybe also for FillRect, CopyEx ..., (maybe we could have a FillRectEx))

**Comment by icculus** [comment]
Okay, everything is handled except the Objective-C bits, which I believe are small fixes but I don't really feel qualified to mess with them right before the milestone wraps up. If @slime73 feels like taking a run at them, I won't mind, but otherwise the rest will bump to early-in-milestone 2.0.24.

The Objective-C issues are here: https://icculus.org/~icculus/code-checker-03242022/

**Comment by icculus** [comment]
Disregard the previous Objective-C issues; I need to rerun the static analysis to verify first. Now that we've moved to ARC, they're likely all resolved.

**Comment by icculus** [comment]
Rechecked this; ARC resolved all the issues!

I pushed one small thing in 6b4bd5a75924917e45c70d55596ac2d51267c19e, and the only other complaints are the test suite using rand() instead of arc4random because it gives better results, and I'm not inclined to change that (but an SDL_rand() would be nice to have, honestly).

**Comment by slouken** [comment]
SDL_rand() was discussed in https://github.com/libsdl-org/SDL/issues/4968.
