### ISSUE TITLE
Triage _all_ bugs...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4601]
There's 700+ open bugs, most of them things that were still open on Bugzilla when we migrated, and some of them _years_ old. It might be worth taking a few hours to read all of them and close a bunch, or tag them as "old but still valid" or whatever.

**Comment by icculus** [comment]
![image](https://user-images.githubusercontent.com/673562/128573303-a4487a78-8176-4b39-a576-8b109cf69bbe.jpeg)

:P

**Comment by icculus** [comment]
So a huge pile of these got added to the 2.0.18 milestone, a lot of them "we just should verify this real quick and close the bug," but we should just keep tossing _this_ issue to new milestones until we finally run out of old bugs.

(for now it stays in 2.0.18 in case we have room to slide more old bugs into this milestone.)

**Comment by slouken** [comment]
No more room! :)

**Comment by icculus** [comment]
In the interest of not drowning in the 2.0.26 milestone, let's not add more old bugs to it this time.

**Comment by slouken** [comment]
Holy crap... ALL the bugs are triaged!

We have almost 500 bugs split across 2.30.0 and SDL 3.0, down from almost 1000 bugs a week ago. :)
