### ISSUE TITLE
Rename hidapi symbols to prevent static linking issues

### ISSUE THREAD

**Issue by Yamakaky** [libsdl-org/SDL#4602]
SDL bundles a modified version of hidapi. Doing a static link of both upstream hidapi and SDL will override the modified functions, causing all sort of problems. To prevent this, every function in the bundled version should be prefixed to prevent conflicts, for example with `SDL_`. 

See https://github.com/libsdl-org/SDL/issues/4596 for a real world example.

**Comment by slouken** [comment]
We need to make sure we don't do this on Android, since the Java code interacts with just one C++ side implementation.

**Comment by slouken** [comment]
This is implemented in https://github.com/libsdl-org/SDL/commit/5b646cd19e36e02c658fcbf792721b5bdce8491f.
