### ISSUE TITLE
Add vsync support to the software renderer

### ISSUE THREAD

**Issue by cooljeanius** [libsdl-org/SDL#4612]
Previously I had requested that the Wesnoth project use vsync in this downstream bug: https://github.com/wesnoth/wesnoth/issues/5018 
However, upon investigation, devs discovered that the reason why that's not possible is because apparently it's actually an upstream issue with SDL 2 here, in that the software renderer doesn't support vsync, which is apparently due to this line:
https://github.com/libsdl-org/SDL/blob/391bb80bb9ac8dbdd08db87734beed0a0d3bb7e9/src/render/software/SDL_render_sw.c#L875
It would be nice if something in this area could be fixed here on SDL's end.

**Comment by cooljeanius** [comment]
oh wow, thanks for the quick fix!

**Comment by slouken** [comment]
You're welcome! :)
