### ISSUE TITLE
Missing ability to return what /dev/input a keyboard key event is coming from

### ISSUE THREAD

**Issue by mrfixit2001** [libsdl-org/SDL#4619]
I've been trying to find where a keyboard's event ID could be pulled from in SDL2 code, but I haven't been able to find it. I'm working on code that needs to support multiple keyboards and I need to distinguish inputs from each. If someone can tell me where inside the SDL2 keyboard code that the /dev/input/eventX detail can be referenced then I can try to patch SDL2 to add a new function that will return this detail. The joystick driver contains this information in it's hwdata and is populated at the time the joystick is added.

Any insights and advice welcome.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
