### ISSUE TITLE
2.0.16: incorrect libdir install path

### ISSUE THREAD

**Issue by kloczek** [libsdl-org/SDL#4621]
Looks like everything lbraries, pkgconfig file and cmake modules are installed in `${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX}`.
This is wrong path and it causes that all is installed in for exemple /urr/lib6464/
Here is the parch which removes breaking paths used in cmake `GNUInstallDirs` module https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
```patch
--- a/CMakeLists.txt~   2021-08-06 20:36:54.000000000 +0100
+++ b/CMakeLists.txt    2021-08-10 18:31:55.198332992 +0100
@@ -2662,15 +2662,15 @@

 ##### Installation targets #####
 install(TARGETS ${_INSTALL_LIBS} EXPORT SDL2Targets
-  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX}"
-  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX}"
+  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
+  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
   RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")

 ##### Export files #####
 if (WINDOWS)
   set(PKG_PREFIX "cmake")
 else ()
-  set(PKG_PREFIX "${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX}/cmake/SDL2")
+  set(PKG_PREFIX "${CMAKE_INSTALL_LIBDIR}/cmake/SDL2")
 endif ()

 include(CMakePackageConfigHelpers)
@@ -2717,7 +2717,7 @@
           execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink
             \"lib${SONAME}${SOPOSTFIX}${SOEXT}\" \"libSDL2${SOPOSTFIX}${SOEXT}\"
             WORKING_DIRECTORY \"${SDL2_BINARY_DIR}\")")
-        install(FILES ${SDL2_BINARY_DIR}/libSDL2${SOPOSTFIX}${SOEXT} DESTINATION "${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX}")
+        install(FILES ${SDL2_BINARY_DIR}/libSDL2${SOPOSTFIX}${SOEXT} DESTINATION "${CMAKE_INSTALL_LIBDIR}")
     endif()
   endif()
   if(FREEBSD)
@@ -2725,7 +2725,7 @@
     install(FILES ${SDL2_BINARY_DIR}/sdl2.pc DESTINATION "libdata/pkgconfig")
   else()
     install(FILES ${SDL2_BINARY_DIR}/sdl2.pc
-      DESTINATION "${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX}/pkgconfig")
+      DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig")
   endif()
   install(PROGRAMS ${SDL2_BINARY_DIR}/sdl2-config DESTINATION "${CMAKE_INSTALL_BINDIR}")
   # TODO: what about the .spec file? Is it only needed for RPM creation?
```
Please let me know if you want me to make PR.

**Comment by icculus** [comment]
Make a PR and I'll merge it, if you want credit in revision control, otherwise I can just apply this patch.

**Comment by slouken** [comment]
We should also track why LIB_SUFFIX was added in the first place.

**Comment by kloczek** [comment]
> Make a PR and I'll merge it, if you want credit in revision control, otherwise I can just apply this patch.

Done
https://github.com/libsdl-org/SDL/pull/4622

**Comment by icculus** [comment]
> We should also track why LIB_SUFFIX was added in the first place.

It's been there since the initial addition of CMakeLists.txt in Mercurial:

https://github.com/libsdl-org/SDL-historical-archive/blob/d36de559d2f4a6faa47d06b747e22fb1abd43b19/CMakeLists.txt#L1153-L1155

But at the time, it looked like `"lib${LIB_SUFFIX}"`, which suggests to me that this should have been removed when the formal `$CMAKE_INSTALL_DIR` variable arrived to replace it.

**Comment by kloczek** [comment]
> We should also track why LIB_SUFFIX was added in the first place.

Nope. Nothing like that shuld be done when `GNUInstallDirs` is used :)

**Comment by kloczek** [comment]
> It's been there since the initial addition of CMakeLists.txt in Mercurial:
> 
> https://github.com/libsdl-org/SDL-historical-archive/blob/d36de559d2f4a6faa47d06b747e22fb1abd43b19/CMakeLists.txt#L1153-L1155
> 
> But at the time, it looked like `"lib${LIB_SUFFIX}"`, which suggests to me that this should have been removed when the formal `$CMAKE_INSTALL_DIR` variable arrived to replace it.

Yep .. proper use `GNUInstallDirs` simplifirs many things and makes such hacks obsolete :)
BTW looking for `64` in CMakeLists.txt I found:
I found
```cmake
set(SIZEOF_VOIDP ${CMAKE_SIZEOF_VOID_P})
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(ARCH_64 TRUE)
  set(PROCESSOR_ARCH "x64")
else()
  set(ARCH_64 FALSE)
  set(PROCESSOR_ARCH "x86")
endif()
set(LIBNAME SDL2)
if(NOT LIBTYPE)
  set(LIBTYPE SHARED)
endif()
```
That looks like another kind of DYI hack :)

**Comment by icculus** [comment]
> That looks like another kind of DYI hack :)

CMake was the Wild West when we first added it to SDL. Anything that looks like this sort of unnecessary DIY stuff, we will happily accept pull requests to replace.

**Comment by kloczek** [comment]
I understand. You know how it is .. "in this world we are dealiong with only not-well-tested software" 😊
