### ISSUE TITLE
Emscripten port repo

### ISSUE THREAD

**Issue by Daft-Freak** [libsdl-org/SDL#4623]
Currently the copy of SDL used by Emscripten lives at https://github.com/emscripten-ports/SDL2, mostly because back when it was created SDL was using Mercurial and doing everything on GitHub was easier. I used to periodically push tested patches from there upstream and pull in upstream releases when necessary.

But now SDL is on GitHub too, so it's all a bit redundant. @kripken has mentioned in a couple of PRs that it would be ideal if we could just point Emscripten at upstream SDL. Also, since our repo is a fork of the old mirror, we can't just merge upstream releases now because of the different histories. (We're currently back at 2.0.10 with a few backports, mostly because I haven't had a need to update.)

Another issue is that I'm not really watching the upstream issues, and I'm aware that I'm sometimes a bit slow/behind with downstream issues/PRs.

There are only a few downstream patches at the moment (https://github.com/libsdl-org/SDL/compare/main...Daft-Freak:em (a rebase)). I'm not sure how acceptable the "replace the timer implementation" patch(es) are, and the config file will need updating.

I guess I'm just trying to start a discussion about where we should go from "mostly-upstreamed" that I don't forget about... and It's probably going to get more attention here than the downstream repo.

**Comment by icculus** [comment]
As far as I'm concerned you can have write access to work out of here directly (I think you might have had this for Mercurial...?).

If you want it, say the word and I'll send the invite.

**Comment by icculus** [comment]
In any case, putting this in the 2.0.18 milestone to have any pending Emscripten stuff merged before the next official release.

**Comment by Daft-Freak** [comment]
> (I think you might have had this for Mercurial...?)

Yeah, I did. Definitely wouldn't mind having write access again :smile:

**Comment by icculus** [comment]
Invite sent! Please merge whatever you feel is appropriate!

**Comment by icculus** [comment]
Okay, #4648 is resolved; is there anything else, @Daft-Freak, or can we close this issue?

**Comment by Daft-Freak** [comment]
I _think_ just [this config.h](https://github.com/emscripten-ports/SDL2/blob/master/include/SDL_config_emscripten.h) needs updated and merged and there was a recent patch to wheel events.

**Comment by icculus** [comment]
> I think just this config.h needs updated

Your wish is my command.  :)

If we're in sync, let's close this issue and point future stuff here, if you like.

**Comment by Daft-Freak** [comment]
Ah, sorry looks like I'd already merged the config file and updated it from 2.0.10.

Going to make sure nothing explodes if I point emscripten at upstream SDL now...

**Comment by Daft-Freak** [comment]
Looking good there https://github.com/emscripten-core/emscripten/pull/15452. Config "update" is effectively reverting 0a870756625d675923f4e57b93223f606a10f7a0 though. (At least partly my fault for replying late last night without checking...)

**Comment by icculus** [comment]
> At least partly my fault for replying late last night without checking

100% my fault for diffing the files backwards and thinking I was committing the newer version. Reverted now.

I'm closing this bug because we appear to be good on our end. Reopen or open a new one if we have other work on our end to get this finished, otherwise I'll assume this will wrap up in https://github.com/emscripten-core/emscripten/pull/15452
