### ISSUE TITLE
Is HasAcceleratedOpenGL() still necessary?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4624]
The answer might be "yes," in which case just close this issue, but can we consider if we need this anymore?

https://github.com/libsdl-org/SDL/blob/fcfd19db862b60159577720f46d31a35a03e7888/src/video/SDL_video.c#L175-L206

It requires us to create a throwaway OpenGL window for almost every SDL-using process, but also: are we living in a world where this is something we should work around anymore? Do most reasonable things have good GPUs and usable GL drivers in modern times?

(also, do AMD's drivers _still_ report themselves as "ATI Technologies"?)

**Comment by dos1** [comment]
Also - are vendor strings for Intel, Broadcom, Vivante, ARM, Qualcomm, ImTech and other devices with usable GL drivers (in many cases even fully free and part of Mesa) excluded intentionally? ;)

**Comment by slouken** [comment]
No, this just hasn't been revisited... ever. :)

**Comment by okuoku** [comment]
> (also, do AMD's drivers still report themselves as "ATI Technologies"?)

GPUinfo.org says [X.Org](https://opengl.gpuinfo.org/displayreport.php?id=5632) or [AMD](https://opengl.gpuinfo.org/displayreport.php?id=5477).

**Comment by ell1e** [comment]
I think this is actually still relevant, e.g. in my Windows VM there is no accelerated OpenGL, and no accelerated Direct3D either. `SDL_Renderer` actually messes this up because it gives me a suppoedly accelerated direct3d renderer when it should be giving me a software renderer IMHO. Also, a lot of Chinese Linux emulation handhelds are moving into the ARM64 and 2GB+ RAM space (which means usually recent kernel + SDL2 run) and some of these have no GPU acceleration either.

So my suggestion would be to keep this in, and instead expand it to cover Direct3D as well (to detect Microsoft's new fallback software mode which I heard they added in Windows 10 or so).

**Comment by icculus** [comment]
Okay, first step (don't create a throwaway GL context if not necessary) is in, which means we'll only do this for software rendered things now, instead of for everything.

Next step is improving the decision on whether we have a "good" OpenGL or not.

@ell1e is absolutely right that we should have a blacklist in the opengl renderer to refuse to continue if it lands on something called "Software Mesa" or "Microsoft Software Renderer" or whatever these are named...D3D9 might benefit from something similar, too...but we still need the current code to live in SDL_video.c because the software renderer uses it. It's likely I'll make this function shared internally so we can use it for both purposes, or have SDL_Renderers able to report if they are "slow" or whatever, I don't know yet.

**Comment by sezero** [comment]
Someone reported an issue with commit f37e4a9: https://github.com/libsdl-org/SDL/commit/f37e4a94d3acaa5c1872386d5a682292d48faf93#commitcomment-65875230

**Comment by grapeli** [comment]
@sezero 
It's me.
I'm not a developer. This change is definitely the cause of the dosbox-x crash. I am not able to judge if this is a bug in dosbox-x or sdl. I have attached the gdb log. Moreover, compiling dosbox-x yourself is easy (`./configure --enable-sdl2 --with-sdl2-prefix=...`). It's easy to reproduce. After running dosbox-x, start the mapper editor (`F12-M`), exit it, and then resize the dosbox-x window.

**Comment by icculus** [comment]
I'll reproduce over here.

**Comment by icculus** [comment]
Forgot to update this: this reproduces over here, too, trying to track down if this is a dosbox bug or an SDL bug.

**Comment by icculus** [comment]
I should be more clear here: this reproduces over here if I force the OpenGL renderer to report itself as unaccelerated.

So what's happening is DosBox-X forces SDL_HINT_FRAMEBUFFER_ACCELERATION to "opengl" (at least by default), because it wants to touch pixels in the framebuffer, but I assume also wants to apply OpenGL functionality on top of that, so when you have an unaccelerated OpenGL, the new code was refusing to use it. I've now changed this so if it's specifically requested we use it no matter what, since the app probably isn't requesting a specific backend for preference but rather because it _needs_ that API.

You should look into why you're ending up in an unaccelerated OpenGL (is it running in a virtual machine, etc?), though.

That change is in https://github.com/icculus/SDL/commit/23dbf4657904c35c884b2833e5421f22330c8149 and I think resolves the issue. Gonna put this in a pull request and merge shortly, but if you can retest, I'd appreciate it!

**Comment by icculus** [comment]
I can reproduce this crash.

I've been looking at this for too long now, but I'm currently of the opinion this is a DosBox-X bug that was hidden by SDL. Going to look a little further, but it seems like there's some sort of juggle where it's creating a whole bunch of GLX contexts and after the resize it eventually ends up using a bogus context for whatever reason.

**Comment by grapeli** [comment]
@icculus 
It is possible that a bug in dosbox-x code appeared with this sdl change.
https://github.com/joncampbell123/dosbox-x/commit/17918c686a72c57ba17bb048f2390af37f06de35
Quite recently there was a change in the dosbox-x [src/gui/sdl_mapper.cpp](https://github.com/joncampbell123/dosbox-x/commit/17918c686a72c57ba17bb048f2390af37f06de35#diff-04dbf3305aa720ff2f5ca0eb95af483fc8ced80da2dd34516cabc50387afa1f6) file. Before it, dosbox-x works fine when resizing windows (after exiting mapper) with the latest sdl.

**Comment by icculus** [comment]
@grapeli Yes, I've now tested this with this dosbox-x revision, the dosbox-x revision before this change, and SDL builds from before this issue's changes to the latest revision, and the crash is 100% reproducible in all cases only in builds that contain https://github.com/joncampbell123/dosbox-x/commit/17918c686a72c57ba17bb048f2390af37f06de35, with or without the SDL changes.

So as far as SDL goes, I believe this _is_ a dosbox-x issue and we can close the SDL bug report.
