### ISSUE TITLE
SDL_RenderSetLogicalSize issues

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4625]
I came here because I noticed something while working on 1oom SDL code (on gitlab):
- Calling both SDL_RenderSetLogicalSize and SDL_RenderSetIntegerScale sometimes results in a viewport 1 pixel too small. So the integer scale not respected as promised.
- If the aforementioned 2 things are both used and SDL_RenderSetLogicalSize is passed a size smaller than the actual window then viewport (as reported by SDL_RenderGetViewport) becomes -2147483648x-2147483648 so I suppose the integer scale became 0
This was on SDL 2.0.14. I'll have a look at the code.

_Originally posted by @sinf in https://github.com/libsdl-org/SDL/issues/1164#issuecomment-813349780_

**Comment by 1bsyl** [comment]
Fixed by casting as float (and not simply the result as float).
same way is done just after: 
https://github.com/libsdl-org/SDL/blob/main/src/render/SDL_render.c#L2281


partial test case:
```
    {   
        SDL_Rect r;
        SDL_RenderGetViewport(renderer, &r);
        SDL_Log("rect=%d %d, %dx%d", r.x, r.y, r.w, r.h);
    }   
    SDL_RenderSetLogicalSize(renderer, window_w + 10, window_h + 10);
    SDL_RenderSetIntegerScale(renderer, SDL_TRUE);        
    {   
        SDL_Rect r;
        SDL_RenderGetViewport(renderer, &r);
        SDL_Log("rect=%d %d, %dx%d", r.x, r.y, r.w, r.h);
    } 
```
outputs:
```
INFO: rect=0 0, 800x640
INFO: rect=-2147483648 -2147483648, -2147483648x-2147483648
```

**Comment by 1bsyl** [comment]
Maybe we can close the bug, since the first part is similar to #4657

**Comment by 1bsyl** [comment]
Actually reverted the commit because the scale is expected to be integer !
so not sure what we should do when logical size is larger than window size

**Comment by 1bsyl** [comment]
.. we could either the scale to 1:
    if (scale < 1.0f) {
       scale = 1.0f;
    }

or invalid the integer_scale, and fallback to normal scale...

@sinf what's your usecase ?

**Comment by 1bsyl** [comment]
The min valid integer scale is 1.0f, which fixes the invalid viewport size reported.
the other part is a duplicate bug.
so marking as fixed.
