### ISSUE TITLE
[Cross compile] broken includes if you cross compile

### ISSUE THREAD

**Issue by SupervisedThinking** [libsdl-org/SDL#4628]
There are two commits which broke cross compilation for me when building additional packages for [my LibreELEC fork](https://github.com/SupervisedThinking/LibreELEC-RR/tree/master-rr)

- https://github.com/libsdl-org/SDL/commit/c30845395257933685c4e348d34ec029121bd181 gives this result https://pastebin.com/6R4VZRQv

- https://github.com/libsdl-org/SDL/commit/6956f4aa1982b66b234026b46f7bb2dd44c67894 ends up with https://pastebin.com/kKKiFaxR

Last known good commit for me is https://github.com/libsdl-org/SDL/commit/403afdb558bd09741dac494207a9bbc78b1701fd - I've [reverted both commits](https://github.com/SupervisedThinking/SDL/commits/2.0.16) & amiberry builds fine again, need run testing too.

**Comment by madebr** [comment]
This has been fixed in https://github.com/libsdl-org/SDL/commit/799d39a3022415f698cb92f44b872c8513d83249
