### ISSUE TITLE
Differentiate physical from virtual gamepads

### ISSUE THREAD

**Issue by Yamakaky** [libsdl-org/SDL#4634]
For my software, I create virtual gamepads using uinput on linux. I also read from the connected gamepads. My issue is that the ControllerDeviceAdded event is also triggered for virtual gamepads. For compatibility with games and steam, I use the vendor, product and version ID from ps4 and xbox controller, so in SDL the name is PS4 Controller in both cases. Is there a way to differentiate between physical and virtual devices?

**Comment by slouken** [comment]
You can use `SDL_GameControllerPath()` to get the system path of the controller.
