### ISSUE TITLE
2.0.16 broke keyboard in Dungeon Crawl Stone Soup on sway

### ISSUE THREAD

**Issue by tmccombs** [libsdl-org/SDL#4642]
After upgrading my sdl2 package from 2.0.14 to 2.0.16, most key presses seem to be ignored and some seem to do the wrong thing when playing Dungeon Crawl Stone Soup in sway with native wayland.

If I run it without `SDL_VIDEODRIVER=wayland` (so it uses xwayland instead) it works fine. Let me know if there is any other information that would be useful for debugging this.

**Comment by flibitijibibo** [comment]
Wayland_keymap_iter is probably the function of interest:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L861
