### ISSUE TITLE
Building SDL 2.0.16 on Debian Jessie failing, worked on 2.0.12

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#4645]
Hi,

I am trying to build SDL2 2.0.16 on a Debian Jessie Docker. I used to build fine with 2.0.12.

```
ARG SDL2_VERSION=2.0.16
 ---> Running in 5a0108e48751
Removing intermediate container 5a0108e48751
 ---> 7b9c8ff88500
Step 15/21 : RUN curl -fLsS "https://www.libsdl.org/release/SDL2-$SDL2_VERSION.tar.gz" | tar -f - -xvzC /tmp && 
  cd /tmp/SDL2-$SDL2_VERSION &&
   ./configure --enable-shared --enable-loadso --enable-sdl-dlopen --enable-pulseaudio-shared --enable-sndio-shared --enable-x11-shared --enable-oss=no --enable-libsamplerate-shared --enable-wayland-shared --enable-directfb-shared &&
   make -j$(getconf _NPROCESSORS_ONLN) &&
 make install &&
   mkdir -p /usr/local/share/doc/libSDL2-2.0/ &&
 cp /tmp/SDL2-$SDL2_VERSION/debian/copyright 
```

But I am getting the following error now:

```
dir -p -- gen
mkdir -p -- gen
mkdir -p -- gen
  GEN    gen/idle-inhibit-unstable-v1-client-protocol.h
  GEN    gen/keyboard-shortcuts-inhibit-unstable-v1-client-protocol.h
  GEN    gen/pointer-constraints-unstable-v1-client-protocol.h
usage: ./scanner [client-header|server-header|code]
Converts XML protocol descriptions supplied on stdin to client headers,
server headers, or protocol marshalling code.
Makefile:864: recipe for target 'gen/idle-inhibit-unstable-v1-client-protocol.h' failed
make: *** [gen/idle-inhibit-unstable-v1-client-protocol.h] Error 1
make: *** Waiting for unfinished jobs....
usage: ./scanner [client-header|server-header|code]
Converts XML protocol descriptions supplied on stdin to client headers,
server headers, or protocol marshalling code.
  GEN    gen/relative-pointer-unstable-v1-client-protocol.h
Makefile:888: recipe for target 'gen/pointer-constraints-unstable-v1-client-protocol.h' failed
make: *** [gen/pointer-constraints-unstable-v1-client-protocol.h] Error 1
usage: ./scanner [client-header|server-header|code]
Converts XML protocol descriptions supplied on stdin to client headers,
server headers, or protocol marshalling code.
usage: ./scanner [client-header|server-header|code]
Converts XML protocol descriptions supplied on stdin to client headers,
server headers, or protocol marshalling code.
Makefile:876: recipe for target 'gen/keyboard-shortcuts-inhibit-unstable-v1-client-protocol.h' failed
make: *** [gen/keyboard-shortcuts-inhibit-unstable-v1-client-protocol.h] Error 1
Makefile:900: recipe for target 'gen/relative-pointer-unstable-v1-client-protocol.h' failed
make: *** [gen/relative-pointer-unstable-v1-client-protocol.h] Error 1
```

Any idea what changed between 2.0.12 to 2.0.16 to cause this error? Maybe a dependency? (There's no change [here](https://github.com/libsdl-org/SDL/blob/main/docs/README-linux.md))

My full log is here: https://cirrus-ci.com/task/6227332395433984

**Comment by flibitijibibo** [comment]
This might be a job for someone familiar with the autotools path - I'm seeing this in particular:

```
usage: ./scanner [client-header|server-header|code]
```

So whatever the generation process is it produces something that Jessie's tools don't like. (I didn't even know Jessie was still in service...)

**Comment by ericoporto** [comment]
Don't know if this helps, but here's a log for 2.0.12. My guess is the change is the inclusion of wayland protocols - I am not really sure though.

https://api.cirrus-ci.com/v1/task/5098874063814656/logs/build.log

>(I didn't even know Jessie was still in service...)

I am sorry... :( Erh, what's the old distro you recommend to use for low glibc compatibility? I was thinking about only moving on from Jessie in 2022, when it won't be oldoldstable anymore.

**Comment by flibitijibibo** [comment]
Looks like it was indeed skipping Wayland before, so disabling it in the current build should fix it.

I currently use CentOS 7, to get to a minimum requirement of 2.17. See the "flibitBuild" section of this page:

https://icculus.org/finger/flibitijibibo

**Comment by ericoporto** [comment]
ok, adding `--enable-video-wayland=no` fixed building on Debian Jessie. So it will need at least Debian Stretch theoretically to build with Wayland support - I am not sure I want to switch to CentOS 7 since it will leave me a bit lost regarding upgrade path in the future.

**Comment by flibitijibibo** [comment]
Just in case, here are the only two commits I could find within recent releases that may have affected this...

https://github.com/libsdl-org/SDL/commit/377f2d35d5b18cd6ac922dafc7180283cf7e804d

https://github.com/libsdl-org/SDL/commit/351abc585bef3508c87fc25ab03435dff72c9875

The original use of `scanner` dates back half a decade so I'm thinking it has to do with our inclusion of the protocols... if anyone wants to try and get it to turn off by default for the _really_ old systems they can try, but we have a workaround for now.

**Comment by ericoporto** [comment]
Ah, this errors too in CMake builds. It also needs to be turned off with `-DVIDEO_WAYLAND=0` apparently.

**Comment by dos1** [comment]
The problem comes from the fact that wayland-scanner 1.6 (as found in jessie) expects to get input on stdin and outputs to stdout, while SDL's scripts pass input and output filenames to it as parameters.

This helps:

```diff
diff --git a/cmake/sdlchecks.cmake b/cmake/sdlchecks.cmake
index ba549c3..c9bf192 100644
--- a/cmake/sdlchecks.cmake
+++ b/cmake/sdlchecks.cmake
@@ -596,14 +596,14 @@ macro(WaylandProtocolGen _SCANNER _CODE_MODE _XML _PROTL)
         OUTPUT "${_WAYLAND_PROT_H_CODE}"
         DEPENDS "${_XML}"
         COMMAND "${_SCANNER}"
-        ARGS client-header "${_XML}" "${_WAYLAND_PROT_H_CODE}"
+        ARGS client-header < "${_XML}" > "${_WAYLAND_PROT_H_CODE}"
     )
 
     add_custom_command(
         OUTPUT "${_WAYLAND_PROT_C_CODE}"
         DEPENDS "${_WAYLAND_PROT_H_CODE}"
         COMMAND "${_SCANNER}"
-        ARGS "${_CODE_MODE}" "${_XML}" "${_WAYLAND_PROT_C_CODE}"
+        ARGS "${_CODE_MODE}" < "${_XML}" > "${_WAYLAND_PROT_C_CODE}"
     )
 
     set(SOURCE_FILES ${SOURCE_FILES} "${_WAYLAND_PROT_C_CODE}")
```

but then it fails on:

```
../src/events/../video/wayland/SDL_waylanddyn.h:53:41: fatal error: xkbcommon/xkbcommon-compose.h: No such file or directory
 #include "xkbcommon/xkbcommon-compose.h"
```

So looks like SDL also depends on a newer xkbcommon than what's available in jessie - `xkbcommon-compose.h` has been added in 0.5.0, while jessie has 0.4.3.

**Comment by ericoporto** [comment]
in the case of CMake, I found the following code in the pkg checks
https://github.com/libsdl-org/SDL/blob/402b86f2a88b5ee3e112dbde2ec232ee5f36572f/cmake/sdlchecks.cmake#L621

I wonder if it would be alright to do a version check for wayland version - of course, if it isn't it's alright, but them it could disable wayland if lower than 0.5

**Comment by flibitijibibo** [comment]
I ended up just making xkbcommon 0.5.0 mandatory - it's about 7 years old at this point and nothing that old is building/running anything on Wayland. It's _probably_ possible to fix up the scanner issue, but this is a bit of a two-birds-one-stone situation for now.

**Comment by ericoporto** [comment]
Thank you! I think that works. It's what I had done. :)
