### ISSUE TITLE
SDL_CreateWindow() failed on macOS using XQuartz/X11 with SDL_VIDEODRIVER=x11

### ISSUE THREAD

**Issue by kjliew** [libsdl-org/SDL#4656]
This is not a typical configuration for HomeBrew/MacPort.

No problem with SDL2-2.0.14.
Commit 9b9d0d484d53c3f3258871cc92bfa1e04a001e6f introduced the bug.

Configure SDL2-2.0.16
```
./configure --prefix=/opt/homebrew --enable-hidapi --with-x
```
Simple code snippet to show the failure
```
int main (int ArgCount, char **Args)
{
  u32 WindowFlags = 0;
  SDL_Window *Window = SDL_CreateWindow("Test", 0, 0, 640, 480, WindowFlags);
  assert(Window);
  return 0;
}
```

**Comment by icculus** [comment]
I'm not really thrilled with the existing code, but this is the simplest fix here.
