### ISSUE TITLE
Upgrade from SDL2 2.0.14 to 2.0.16 casues broken gamepad to show as 4 dead devices

### ISSUE THREAD

**Issue by Lycanite** [libsdl-org/SDL#4667]
I use an Azeron gaming keypad and I've never had an issue with it before.
On upgrading to 2.0.16 the device shows up as 4 controllers where input from none of them works and hitting random keys randomly causes certain modifier keys such as ctrl to be stuck on to the point where I have to reboot my system.
Downgrading back to 2.0.14 resolves this issue.

If there's any other information you need me to send just let me know.

**Comment by slouken** [comment]
Is this still an issue?

**Comment by Lycanite** [comment]
It is but I've made a new issue that better describes the problem: https://github.com/libsdl-org/SDL/issues/4740
