### ISSUE TITLE
Joystick doesn't Work in Android 12 due to Missing Flags in PendingIntent

### ISSUE THREAD

**Issue by MikuAuahDark** [libsdl-org/SDL#4668]
Information: https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

> If your app targets Android 12, you must specify the mutability of each PendingIntent object that your app creates. This additional requirement improves your app's security.

Offending line: 
https://github.com/libsdl-org/SDL/blob/8270172e74a7da32c459c64a7c363b7bf05d1df2/android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java#L587

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/80d19282f735997bc1b748afa0a4d5f3d3dcba6c, thanks!
