### ISSUE TITLE
SDL_KeyboardEvent reports incorrect key when ctrl is held

### ISSUE THREAD

**Issue by tiger-chan** [libsdl-org/SDL#4672]
Holding `SDL_SCANCODE_LCTRL`, pressing `SDL_SCANCODE_PAUSE` reports that `SDL_SCANCODE_SCROLLLOCK` is the button pressed.
OS: Windows 10
SDL version: 2.0.14

**Comment by AntTheAlchemist** [comment]
I can confirm the same. It's very obscure behaviour for a keyboard, but when would this ever cause a problem? ScrLk and Pause are the same key for me - I have to hold down a Fn key to activate Pause, so I would assume left Ctrl overrides Fn. This is more a feature of Windows or the hardware than an SDL bug I think.
