### ISSUE TITLE
[Feature Request]: ‘keyboard layout unknown’ (from e2k PC - MCST Elbrus 2000 architecture)

### ISSUE THREAD

**Issue by r-a-sattarov** [libsdl-org/SDL#4678]
Hi. Please add this keyboard layout to SDL.

- [sdl_e2k.txt](https://github.com/libsdl-org/SDL/files/7026276/sdl_e2k.txt)

Request on site:
- https://discourse.libsdl.org/t/yet-another-keyboard-layout-unknown/23763

**Comment by slouken** [comment]
Can you retry with the latest version of SDL? We revamped the keyboard code a while back and this may be fixed.

**Comment by slouken** [comment]
Okay, thanks!
