### ISSUE TITLE
SDL_RenderReadPixels double free / invalid pointer

### ISSUE THREAD

**Issue by JoseGuilhermeCR** [libsdl-org/SDL#4684]
Hello there!

I'm trying to save a bitmap of part of a window by using the following code:

```
{
    void *pixels = malloc(canvas.pixels_length * 3);
    if (!pixels) {
        LOG_ERROR("Could not allocate temporary memory to save the canvas.\n");
        return;
    }

    const SDL_Rect *canvas_rect = (const SDL_Rect *)&canvas.placement;
    if (SDL_RenderReadPixels(window_get_renderer(),
        canvas_rect,
        SDL_PIXELFORMAT_RGB888,
        pixels,
        canvas.placement.w * 3) != 0) {
            LOG_ERROR("SDL_RenderReadPixels failed: %s\n", SDL_GetError());
            free(pixels);
            return;
    }

    SDL_Surface *bmp_surface = SDL_CreateRGBSurfaceWithFormatFrom(pixels,
                                                        canvas.placement.w,
                                                        canvas.placement.h,
                                                        8,
                                                        canvas.placement.w * 3,
                                                        SDL_PIXELFORMAT_RGB888);
    if (!bmp_surface) {
        LOG_ERROR("SDL_CreateRGBSurfaceWithFormatFrom failed: %s\n", SDL_GetError());
        free(pixels);
        return;
    }

    SDL_SaveBMP(bmp_surface, "test.bmp");

    SDL_FreeSurface(bmp_surface);
    free(pixels);
}
```

The first time this function runs, it creates test.bmp successfully, although the file has the resolution I expect, the contents torwards the right are duplicated.

Anyway, if I try to run this function once more, the program crashes inside SDL_RenderReadPixels and gives me:
<pre>double free or corruption (out)

Program received signal SIGABRT, Aborted.
<font color="#A2734C">__GI_raise</font> (<font color="#2AA1B3">sig=sig@entry</font>=6) at <font color="#26A269">../sysdeps/unix/sysv/linux/raise.c</font>:49
49	  <font color="#2A7BDE"><b>return</b></font> ret<font color="#C01C28">;</font>
</pre>

Result of bt:
<pre>(gdb) bt
#0  <font color="#A2734C">__GI_raise</font> (<font color="#2AA1B3">sig=sig@entry</font>=6) at <font color="#26A269">../sysdeps/unix/sysv/linux/raise.c</font>:49
#1  <font color="#12488B">0x00007ffff7b3a8a4</font> in <font color="#A2734C">__GI_abort</font> () at <font color="#26A269">abort.c</font>:79
#2  <font color="#12488B">0x00007ffff7b93a97</font> in <font color="#A2734C">__libc_message</font> (<font color="#2AA1B3">action=action@entry</font>=do_abort, <font color="#2AA1B3">fmt=fmt@entry</font>=0x7ffff7ca47fc &quot;%s\n&quot;) at <font color="#26A269">../sysdeps/posix/libc_fatal.c</font>:155
#3  <font color="#12488B">0x00007ffff7b9b70c</font> in <font color="#A2734C">malloc_printerr</font> (<font color="#2AA1B3">str=str@entry</font>=0x7ffff7ca6c90 &quot;double free or corruption (out)&quot;) at <font color="#26A269">malloc.c</font>:5628
#4  <font color="#12488B">0x00007ffff7b9cf90</font> in <font color="#A2734C">_int_free</font> (<font color="#2AA1B3">av</font>=0x7ffff7cd7a00 &lt;main_arena&gt;, <font color="#2AA1B3">p</font>=0x2347150, <font color="#2AA1B3">have_lock</font>=&lt;optimized out&gt;) at <font color="#26A269">malloc.c</font>:4547
#5  <font color="#12488B">0x00007ffff7ba07c8</font> in <font color="#A2734C">__GI___libc_free</font> (<font color="#2AA1B3">mem</font>=&lt;optimized out&gt;) at <font color="#26A269">malloc.c</font>:3309
#6  <font color="#12488B">0x00007ffff7e836d5</font> in <font color="#A2734C">SDL_free_REAL</font> (<font color="#2AA1B3">ptr</font>=0x2347160) at <font color="#26A269">/usr/src/debug/SDL2-2.0.16-1.fc34.x86_64/src/stdlib/SDL_malloc.c</font>:5432
#7  <font color="#A2734C">GL_RenderReadPixels</font> (<font color="#2AA1B3">renderer</font>=&lt;optimized out&gt;, <font color="#2AA1B3">rect</font>=&lt;optimized out&gt;, <font color="#2AA1B3">pixel_format</font>=&lt;optimized out&gt;, <font color="#2AA1B3">pixels</font>=&lt;optimized out&gt;, <font color="#2AA1B3">pitch</font>=&lt;optimized out&gt;)
    at <font color="#26A269">/usr/src/debug/SDL2-2.0.16-1.fc34.x86_64/src/render/opengl/SDL_render_gl.c</font>:1452
#8  <font color="#12488B">0x00007ffff7e7b802</font> in <font color="#A2734C">SDL_RenderReadPixels_REAL</font> (<font color="#2AA1B3">renderer</font>=0x918440, <font color="#2AA1B3">rect</font>=0x40e1cc &lt;canvas+12&gt;, <font color="#2AA1B3">format</font>=370546692, <font color="#2AA1B3">pixels</font>=0x1fc0bd0, <font color="#2AA1B3">pitch</font>=4200)
    at <font color="#26A269">/usr/src/debug/SDL2-2.0.16-1.fc34.x86_64/src/render/SDL_render.c</font>:3323
#9  <font color="#12488B">0x0000000000403825</font> in <font color="#A2734C">canvas_save_to_bmp</font> () at <font color="#26A269">src/canvas.c</font>:491
#10 <font color="#12488B">0x000000000040279b</font> in <font color="#A2734C">button_handle_mouse</font> (<font color="#2AA1B3">btn</font>=0x40e580 &lt;button_save_bmp&gt;, <font color="#2AA1B3">state</font>=1, <font color="#2AA1B3">x</font>=129, <font color="#2AA1B3">y</font>=659) at <font color="#26A269">src/button.c</font>:99
#11 <font color="#12488B">0x0000000000408131</font> in <font color="#A2734C">toolbox_handle_mouse</font> (<font color="#2AA1B3">state</font>=1, <font color="#2AA1B3">x</font>=129, <font color="#2AA1B3">y</font>=659) at <font color="#26A269">src/toolbox.c</font>:95
#12 <font color="#12488B">0x0000000000408e52</font> in <font color="#A2734C">window_run</font> () at <font color="#26A269">src/window.c</font>:147
#13 <font color="#12488B">0x0000000000405f64</font> in <font color="#A2734C">main</font> (<font color="#2AA1B3">argc</font>=1, <font color="#2AA1B3">argv</font>=0x7fffffffde78) at <font color="#26A269">src/main.c</font>:209
</pre>

I've tried debugging it, but it got way too deep for me, so I'm thinking it's just... broken?

By the way, if I give NULL as the rect of SDL_RenderReadPixels, it changes from `double free or corruption (out)` to `free(): invalid pointer`

I'm using Fedora 34 and the following:

<pre><font color="#F66151"><b>SDL</b></font>2.x86_64                                       2.0.16-1.fc34                          @updates                             
<font color="#F66151"><b>SDL</b></font>2-debuginfo.x86_64                             2.0.16-1.fc34                          @updates-debuginfo                   
<font color="#F66151"><b>SDL</b></font>2-debugsource.x86_64                           2.0.16-1.fc34                          @updates-debuginfo                   
<font color="#F66151"><b>SDL</b></font>2-devel.x86_64                                 2.0.16-1.fc34                          @updates                             
<font color="#F66151"><b>SDL</b></font>2-static.x86_64                                2.0.16-1.fc34                          @updates                             
<font color="#F66151"><b>SDL</b></font>2_ttf.x86_64                                   2.0.15-7.fc34                          @fedora                              
<font color="#F66151"><b>SDL</b></font>2_ttf-debuginfo.x86_64                         2.0.15-7.fc34                          @fedora-debuginfo                    
<font color="#F66151"><b>SDL</b></font>2_ttf-debugsource.x86_64                       2.0.15-7.fc34                          @fedora-debuginfo                    
<font color="#F66151"><b>SDL</b></font>2_ttf-devel.x86_64                             2.0.15-7.fc34                          @fedora   </pre>

<pre>gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)</pre>
<pre>Linux fedora 5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux</pre>

NVIDIA driver version: 470.63.01 from rpmfusion repositories.

Thank you for the attention!

**Comment by 0x1F9F1** [comment]
You are only allocating 3 bytes per pixel even though `SDL_PIXELFORMAT_RGB888` is a 32-bit format (even if only 24 of those bits are used). You can use `SDL_BYTESPERPIXEL` to check this.
I guess what you actually want is `SDL_PIXELFORMAT_BGR24`.

**Comment by JoseGuilhermeCR** [comment]
Oops... That's true! My mistake, let me try that out and I'll say here how it went. It would be nice if it worked, even though I ended up implementing my own simple BMP file saver.

**Comment by JoseGuilhermeCR** [comment]
Ok, I tried it out. It worked just fine... didn't crash or anything. It turns out I didn't pay attention to that. I just went with: "Oh, RGB888 so it must use 24 bits." LOL.

Thank you a lot for checking the code!! 

Sorry @icculus, seems it was my mistake after all! I'll be closing this issue and please remove it from the milestone.

Thank you @0x1F9F1!
