### ISSUE TITLE
Upgrade to 2.0.16 on macos causes “SDL2.framework” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by ellipticaldoor** [libsdl-org/SDL#4689]
After downloading the latest version of SDL and using the framework I get the following message before opening my app

![Screenshot 2021-08-23 at 19 06 02](https://user-images.githubusercontent.com/3449006/130495505-1f94b3dc-9472-4fa0-9db2-9a7df904a68b.jpg)

Is this normal? I'm just using the latest Framework from the website

**Comment by bradallred** [comment]
I believe you are expected to embed the framework in your app bundle and sign it yourself

**Comment by ellipticaldoor** [comment]
I thought the message was due to the update, but it's just a first time message that appears when loading SDL.

I will have to sign it myself on release.

**Comment by csalmeida** [comment]
In my case I fixed this error by running the executable, e.g. `./main` then opening the Privacy & Security settings and scroll to _Security_.

You will see a button to allow the `SDL2.framework`:

![CleanShot 2024-06-25 at 21 55 37](https://github.com/libsdl-org/SDL/assets/12223613/3dd03d48-2a11-4bce-8796-43316fb7bf74)

After allowing the framework, macOS will allow the code to run after confirmation:

![CleanShot 2024-06-25 at 21 55 51](https://github.com/libsdl-org/SDL/assets/12223613/ad0b1e17-9285-41d9-b655-d4907d4879b6)
