### ISSUE TITLE
Typedef "SDL_PixelFormatEnum" missing on armhf.

### ISSUE THREAD

**Issue by Sherknob** [libsdl-org/SDL#4694]
The typedef **SDL_PixelFormatEnum** is missing on armhf (tested on raspberrypi) in file /usr/include/SDL2/SDL_pixels.h in line 293.

**Comment by slouken** [comment]
It sounds like the version of SDL installed by default on Raspberry Pi is too old. You may be able to fix this by building and installing SDL from source.
