### ISSUE TITLE
Persistent message after app crash on macos

### ISSUE THREAD

**Issue by ellipticaldoor** [libsdl-org/SDL#4701]
After the app crashes macos gives this warning when trying to open the app again

![Screenshot 2021-08-27 at 15 03 37](https://user-images.githubusercontent.com/3449006/131139893-db17399e-4006-47cf-a64f-fd5a155920df.jpg)

I think this is a macos cocoa thing, and it doesn't seems like a feature that any SDL game will use. Could be possible to turn it off by default?

**Comment by ellipticaldoor** [comment]
I see! Thank you

**Comment by ellipticaldoor** [comment]
Uhm, seems like this doesn't works

**Comment by slouken** [comment]
Okay, if that doesn't work, I'm not sure how to avoid that. Maybe you can find the underlying cause of the application crashes?
