### ISSUE TITLE
API oversight: no obvious way to set app title & activity name for screensaver inhibition

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4703]
I scanned the SDL2 API list on the wiki, and it appears that there is no obvious way to set **app title & activity name for screensaver inhibition**. Furthermore, googling suggests even Valve's Steam has in the past had this set to "My SDL Application" (app name) and "Playing a game" (activity) which for the steam client itself is at best wildly misleading and uninformative to an end user.

I think SDL app writers should be encouraged to set this to something recognizable since the average end user has no idea what an "SDL Application" is, and a notable subset of SDL apps aren't actually a game.

My humble shot at possible function names for this:

1. For setting the app name (so it can be reused in other spots in the future where necessary): `void SDL_SetAppName(const char *appname)` - I suggest this value, if set, should also be used as a default titlebar text for windows opened from then on, and it would override the "My SDL Application" of the screensaver inhibition. Ideally, it'd be allowed to call this function as early as possible, e.g. even before `SDL_Init()`, so that app authors can put it in a spot where it's guaranteed to be before their app code attempts window creation.

2. For setting the type of activity to something more informative: `void SDL_SetSuspendInhibitionActivityName(const char *activityname)` - which would override the default of "Playing a game" of the screensaver inhibition.

I suggest that both of these functions should still work when `SDL_EnableScreenSaver` was temporarily used before, and that they should not have their values set back to the uninformative defaults if followed up with `SDL_DisableScreenSaver` again.

**Comment by sulix** [comment]
Hmm…

There's a very similar situation with PulseAudio app/stream names, which default to "SDL Application" and "Audio Stream" respectively. In that case, though, there are hints to override it:
- ``SDL_HINT_AUDIO_DEVICE_APP_NAME``
- ``SDL_HINT_AUDIO_DEVICE_STREAM_NAME``

(There's also a hint for changing the "role" from "Game" to something else.)

The simple solution for screensaver inhibition would be to also add hints, but I agree that having a general way of setting the application name which can be shared between all of the different places which need it is better. The activity name I'm less convinced is worth having a dedicated function for — a hint probably is sufficient here.

In any case, the app and activity names seem to be set every time the screensaver is inhibited:
https://github.com/libsdl-org/SDL/blob/d483970262e32ca7b3a376e538f454d8a1f1ec6d/src/core/linux/SDL_dbus.c#L368
So the obvious implementation would probably not reset them to the defaults, and allow them to be changed if the hint value changes.

**Comment by ell1e** [comment]
>  In that case, though, there are hints to override it:

Ah, neat. Yeah, maybe the best solution for the inhibition activity name then would be to add a hint and then mention it here: https://wiki.libsdl.org/SDL_DisableScreenSaver (important, otherwise nobody is going to find it!) But I agree setting the app name centrally and also using it for pulseaudio and other places would be nice.

**Comment by sulix** [comment]
I've prototyped a hint-based implementation here:
https://github.com/sulix/SDL/commit/84c6679b58f03dcf0a50e495cedd05232678ba2f

It works fine on most of my test machines, but one does seem to be showing both the specified names and "My SDL application"/"Playing a game". I suspect that's a result of either some odd state in the KDE power-management code or another SDL app running and doing something weird, and that a reboot will fix it, but be wary if you test it.

**Comment by icculus** [comment]
As I mentioned on the PR, the only way this is going to get wide use is if we require it to be specified as an argument to SDL_Init(), otherwise it's going to be an endless stream of individual programs getting bug reports about how their app shows up in various desktop environment's UI as "SDL Application," but unfortunately we can't change that before SDL 2.1.

So the hint patch we just merged is Good Enough for now, since it gives interested apps a path forward, but we really need to change the API at some point to handle this better.

(Another option, though: if the hint isn't set, we use the title of the latest window created, which isn't foolproof but might handle this automatically for a lot of apps.)

**Comment by slouken** [comment]
I like that option better. I'd like to avoid adding required parameters to the init call.

**Comment by ell1e** [comment]
> As I mentioned on the PR, the only way this is going to get wide use is if we require it to be specified as an argument to SDL_Init(), otherwise it's going to be an endless stream of individual programs getting bug reports about how their app shows up in various desktop environment's UI as "SDL Application,"

Why? Couldn't it default to the current behavior unless the name was explicitly set at least once via some `void SDL_SetAppName(const char *appname)` before `SDL_Init`? Or am I missing something.

I find a hint less optimal because it tends to be missed by so many devs. For something as important as an app name, I think a dedicated call would be better.

**Comment by icculus** [comment]
So as a way forward:

- for the audio stuff, use the old hint if set, if not, use the new generic hint (already in revision control).
- for everything else, use the new hint if set (already in revision control)
- if there isn't a hint, use the current title of the latest window to be created (this needs to be written and put in a common function so several pieces of code can access it).
- if no window: use the process name?

Going to reopen this for that last bit of work, and assign to the 2.0.18 milestone, with the intention to bump to 2.0.20 if we get overwhelmed with other things.

**Comment by ell1e** [comment]
@icculus  just in case it got lost, I still think a function call for the app name would be better, or an `SDL_Init` parameter as per above regarding the discovery of this for app devs

**Comment by slouken** [comment]
We're going to add an API in 2.0.20 that allows you to set the application name (and state?) so there's an official way to do this instead of a collection of hints.

**Comment by icculus** [comment]
Going to implement this shortly. So the info we want here, if we really want to encompass app metadata...

- app name
- developer name
- maybe some unique identifier like "org.icculus.RyansGame"
- version string
- some app type identifier ("media player" "game" "app" idk)
- probably other things...?

So we shove this into a struct and have an `SDL_SetAppInfo(&metadata_struct);` call that has to happen before SDL_Init() for apps that care. At init time, SDL will fill it in or override with existing hints that might be set. Once init is called, SDL_SetAppInfo returns -1 because we won't let it change once we set things up.

Anything else worth putting in that struct? @ell1e?

**Comment by icculus** [comment]
I don't think we're looking for a query, just a way that SDL can have that information available to forward to other things that want it (PulseAudio's list of applications making noise, the desktop environment telling you who is blocking the screensaver, etc). In that sense, we don't need things like copyrights and licenses listed here, I think.

**Comment by icculus** [comment]
We've talked about this and we'd rather do this right in SDL3, so we're going to bump this out of the SDL2 milestones instead of kicking it down the line. There are SDL hints that work for the urgent stuff (like PulseAudio, etc) in SDL2 for now.

**Comment by icculus** [comment]
Okay, I've been thinking about this, and I think we should put this in SDL_Init.

Those that don't want to bother just add an extra NULL to the call (or use SDL_InitSubsystem, finally giving it a good reason to exist at the same time as SDL_Init).

Having this in a separate function raises two concerns:

- Apps won't use it.
- It suggests this should be allowed to change after init time by calling it a second time.

Here's a proposed API. If this is absolutely unacceptable, we can do a separate SDL_SetAppMetadata() function.

The docs list a few reasons this is useful to an app (macOS About menu, system volume controls, etc), but the unspoken value of this in the future is that sdl3-compat will be able to use it to identify games for applying quirks.

```diff
diff --git a/include/SDL3/SDL_init.h b/include/SDL3/SDL_init.h
index 18d5d8956..981826ee7 100644
--- a/include/SDL3/SDL_init.h
+++ b/include/SDL3/SDL_init.h
@@ -66,6 +66,30 @@ typedef Uint32 SDL_InitFlags;
 #define SDL_INIT_SENSOR     0x00008000u /**< `SDL_INIT_SENSOR` implies `SDL_INIT_EVENTS` */
 #define SDL_INIT_CAMERA     0x00010000u /**< `SDL_INIT_CAMERA` implies `SDL_INIT_EVENTS` */
 
+
+typedef enum SDL_ApplicationType
+{
+    SDL_APPTYPE_OTHER,        /**< Doesn't fit other categories */
+    SDL_APPTYPE_GAME,         /**< A video game */
+    SDL_APPTYPE_MEDIAPLAYER,  /**< A media player */
+} SDL_ApplicationType;
+
+/**
+ * All of these fields (indeed, this entire struct) is optional!
+ * Leave strings as NULL to not report them.
+ */
+typedef struct SDL_AppMetadata
+{
+    const char *name;          /**< Name of the app ("My Game 2: Bad Guy's Revenge!") */
+    const char *identifier;    /**< Unique identifier in reverse domain format ("org.icculus.MyGame2") */
+    const char *version;       /**< Version of the app ("1.0.3beta5", a git hash, there aren't rules) */
+    const char *creator;       /**< Name of developer/maker ("MojoWorkshop, LLC") */
+    const char *copyright;     /**< Copyright string ("Copyright (c) 2024 MojoWorkshop, LLC") */
+    const char *url;           /**< URL for app ("https://icculus.org/MyGame2") */
+    SDL_ApplicationType type;  /**< What sort of app is this? */
+} SDL_AppMetadata;
+
+
 /**
  * Initialize the SDL library.
  *
@@ -105,7 +129,15 @@ typedef Uint32 SDL_InitFlags;
  * call SDL_Quit() to force shutdown). If a subsystem is already loaded then
  * this call will increase the ref-count and return.
  *
+ * You can optionally provide metadata about your app here. If this is NULL,
+ * SDL will function without the information, but there are several locations
+ * where it can make use of it (an "About" box in the macOS menu bar, the
+ * name of the app can be shown on some audio mixers, etc). Any field in
+ * SDL_AppMetadata can be left as NULL, if a copyright string, etc, doesn't
+ * make sense for the app.
+ *
  * \param flags subsystem initialization flags.
+ * \param metadata Metadata about this app. May be NULL.
  * \returns 0 on success or a negative error code on failure; call
  *          SDL_GetError() for more information.
  *
@@ -116,7 +148,7 @@ typedef Uint32 SDL_InitFlags;
  * \sa SDL_SetMainReady
  * \sa SDL_WasInit
  */
-extern SDL_DECLSPEC int SDLCALL SDL_Init(SDL_InitFlags flags);
+extern SDL_DECLSPEC int SDLCALL SDL_Init(SDL_InitFlags flags, const SDL_AppMetadata *metadata);
 
 /**
  * Compatibility function to initialize the SDL library.
```

**Comment by slouken** [comment]
I think... apps still won't use it, they'll just pass NULL. Also, everyone that does initialization of multiple subsystems are going to be annoyed that they either have to pass NULL or recreate the metadata for each call site, and won't necessarily know which call site will be called first.

**Comment by icculus** [comment]
Okay then:

```diff
diff --git a/include/SDL3/SDL_init.h b/include/SDL3/SDL_init.h
index 18d5d8956..efdf7e090 100644
--- a/include/SDL3/SDL_init.h
+++ b/include/SDL3/SDL_init.h
@@ -182,6 +182,56 @@ extern SDL_DECLSPEC SDL_InitFlags SDLCALL SDL_WasInit(SDL_InitFlags flags);
  */
 extern SDL_DECLSPEC void SDLCALL SDL_Quit(void);
 
+
+typedef enum SDL_ApplicationType
+{
+    SDL_APPTYPE_OTHER,        /**< Doesn't fit other categories */
+    SDL_APPTYPE_GAME,         /**< A video game */
+    SDL_APPTYPE_MEDIAPLAYER,  /**< A media player */
+} SDL_ApplicationType;
+
+/**
+ * All of these fields (indeed, this entire struct) is optional!
+ * Leave strings as NULL to not report them.
+ */
+typedef struct SDL_AppMetadata
+{
+    const char *name;          /**< Name of the app ("My Game 2: Bad Guy's Revenge!") */
+    const char *identifier;    /**< Unique identifier in reverse domain format ("org.icculus.MyGame2") */
+    const char *version;       /**< Version of the app ("1.0.3beta5", a git hash, there aren't rules) */
+    const char *creator;       /**< Name of developer/maker ("MojoWorkshop, LLC") */
+    const char *copyright;     /**< Copyright string ("Copyright (c) 2024 MojoWorkshop, LLC") */
+    const char *url;           /**< URL for app ("https://icculus.org/MyGame2") */
+    SDL_ApplicationType type;  /**< What sort of app is this? */
+} SDL_AppMetadata;
+
+/**
+ * Specify metadata about your app.
+ *
+ * You can optionally provide metadata about your app to SDL. This is not
+ * required, but strongly encouraged.
+ *
+ * There are several locations where SDL can make use of metadata (an "About"
+ * box in the macOS menu bar, the name of the app can be shown on some audio
+ * mixers, etc). Any field in SDL_AppMetadata can be left as NULL, if a
+ * copyright string, etc, doesn't make sense for the app.
+ *
+ * This function should be called as early as possible (before SDL_Init, even).
+ * Multiple calls to this function are allowed, but various state might not
+ * change once it has been set up with a previous call to this function.
+ *
+ * Passing a NULL removes any previous metadata.
+ *
+ * \param metadata Metadata about this app. May be NULL.
+ * \returns 0 on success or a negative error code on failure; call
+ *          SDL_GetError() for more information.
+ *
+ * \since This function is available since SDL 3.0.0.
+ *
+ * \threadsafety Do not call this function from two threads at once.
+ */
+extern SDL_DECLSPEC int SDLCALL SDL_SetAppMetadata(const SDL_AppMetadata *metadata);
+
 /* Ends C function definitions when using C++ */
 #ifdef __cplusplus
 }
```

**Comment by slouken** [comment]
Great!

Suggestion for consistency with other functions:
```diff
+ * \param metadata Metadata about this app, may be NULL.
```

**Comment by slouken** [comment]
Another option that is a little more unwieldy but gives us more flexibility in the future:
```c
SDL_SetAppMetadata(SDL_PropertiesID props);
```
Then we can define any properties we want, and you can pass 0 to clear them.

I'm going to be using a similar approach for textfield properties. There are so many different options and it seems like they've been growing over time, e.g. you can now specify that you're entering the day of the month of a birthday(!!) in an iOS textfield.

**Comment by icculus** [comment]
We should add something like:

```c
SDL_PropertiesID SDL_BuildProperties(...);
```

So you can do:

```c
SDL_SetAppMetadata(SDL_BuildProperties("name", "My Game", "version", "1.0", NULL));
```

**Comment by slouken** [comment]
Aside from the fact that you can't handle multiple property types from C, it would look like:
```c
SDL_SetAppMetadata(SDL_BuildProperties(SDL_PROP_METADATA_GAME_NAME_STRING, "My Game", SDL_PROP_METADATA_VERSION_STRING, "1.0", NULL));
```

**Comment by slouken** [comment]
How about we do it the usual way we use properties in the API?

We have a simple function, SDL_SetAppMetadata(const char *name, etc.) with the fields that we really want people to fill out, and then another function SDL_SetAppMetadataProperties(SDL_PropertiesID props), and the first one just fills out the common properties and passes it to the second?

We do this with with SDL_CreateWindow(), SDL_CreateRenderer(), etc.

**Comment by icculus** [comment]
> Aside from the fact that you can't handle multiple property types from C, it would look like:

Yeah, it would just be for string key/value pairs. Just trying to find ways to make it less unwieldy, but I think it isn't worth it.

> How about we do it the usual way we use properties in the API?

This I'm fine with, though. But I think we'd probably just have name and version in the normal function, and no one would ever use the Properties version until someone files a bug about the macOS About box.  :P

**Comment by icculus** [comment]
> Suggestion for consistency with other functions:

We should write these details down somewhere, so I can have a perl script or whatever enforce or fix these up across the headers before we ship.

**Comment by slouken** [comment]
> This I'm fine with, though. But I think we'd probably just have name and version in the normal function, and no one would ever use the Properties version until someone files a bug about the macOS About box. :P

What would the version be used for? Does this mean that you can pass NULL to SDL_GetPrefPath() for the metadata defaults?

**Comment by icculus** [comment]
I meant version as in "the SDL_PropertiesID version of the function" not "this app is version 1.0" ... but the app version is good for both a future sdl3-compat and a future version of SDL3 that needs to have a workaround for games with bugs.


As for PrefPath...that...is a good idea.

**Comment by icculus** [comment]
Decided against the PrefPath thing.

An initial shot at this is in #10391.
