### ISSUE TITLE
vulkan and/or custom renderers

### ISSUE THREAD

**Issue by adamschackart** [libsdl-org/SDL#4709]
It would be neat to have optional access to SDL_sysrender.h (in the same manner as SDL_syswm.h) in order to experiment with new rendering backends without having to build all of SDL and link against a custom shared library.

This could be used to easily experiment with Vulkan, DirectFB, software renderer SIMD/multithreading optimizations, ports to legacy game consoles, etc.

**Comment by slouken** [comment]
The interfaces are not guaranteed to stay stable, so we don't want to add them to the ABI. If you're really iterating on custom renderers, building your own SDL should be a fairly low bar. You could even write a renderer that loads an implementation dynamically if you want to do minimal code rebuilding.
