### ISSUE TITLE
Trying to call glActiveTextureARB without multitexturing support

### ISSUE THREAD

**Issue by Fatton1** [libsdl-org/SDL#4711]
Hello. I have a computer with ARM and Vivante without multitexture support. When I am trying to open Dosbox-0.77.0, it causes SIGSEGV in the function **SetCopyState()** (_src/render/opengl/SDL_renderer_gl.c:1127_), because **glActiveTextureARB** is not initialized:
```
if (texture != data->drawstate.texture) {
     const GLenum textype = data->textype;
     if (texturedata->yuv) {
          data->glActiveTextureARB(GL_TEXTURE2_ARB);
          data->glBindTexture(textype, texturedata->vtexture);

          data->glActiveTextureARB(GL_TEXTURE1_ARB);
          data->glBindTexture(textype, texturedata->utexture);
     }
     if (texturedata->nv12) {
          data->glActiveTextureARB(GL_TEXTURE1_ARB);
          data->glBindTexture(textype, texturedata->utexture);
     }
     data->glActiveTextureARB(GL_TEXTURE0_ARB);  //   <<------- Segfault on this call 
     data->glBindTexture(textype, texturedata->texture);

    data->drawstate.texture = texture;
}
```

 Initialization of **glActiveTextureARB** is in the function **GL_CreateRenderer** (_src/render/opengl/SDL_renderer_gl.c:1711_) and happens only with multitexture support:
```
/* Check for multitexture support */
if (SDL_GL_ExtensionSupported("GL_ARB_multitexture")) {
    data->glActiveTextureARB = (PFNGLACTIVETEXTUREARBPROC) SDL_GL_GetProcAddress("glActiveTextureARB");
    if (data->glActiveTextureARB) {
        data->GL_ARB_multitexture_supported = SDL_TRUE;
        data->glGetIntegerv(GL_MAX_TEXTURE_UNITS_ARB, &data->num_texture_units);
    }
}
```
Segmentation fault can be fixed with adding an error message:
```
if (SDL_GL_ExtensionSupported("GL_ARB_multitexture")) {
    data->glActiveTextureARB = (PFNGLACTIVETEXTUREARBPROC) SDL_GL_GetProcAddress("glActiveTextureARB");
    if (data->glActiveTextureARB) {
        data->GL_ARB_multitexture_supported = SDL_TRUE;
        data->glGetIntegerv(GL_MAX_TEXTURE_UNITS_ARB, &data->num_texture_units);
    }
}
else {
    printf("SDL: Sorry, but GL_ARB_multitexture is not supported on your system.\n");
    goto error;
}
```
But even with this error message we can't use the SDL library and Dosbox. Can we somehow get the functionality back?

Here's a stack for Dosbox:
```
SDL: Using driver "opengl" for texture renderer

Thread 1 "dosbox" received signal SIGSEGV, Segmentation fault
 
exc_instr_page_prot at 0x0

#0  0x0000000000000000 in ?? ()
#1  0x00004555556fd488 in SetCopyState (data=0x38df230, cmd=0x3a4b230) at ../SDL2-2.0.12/src/render/opengl/SDL_render_gl.c:1127
#2  0x00004555556fe540 in GL_RunCommandQueue (renderer=0x38ef6e0, cmd=0x3a4b230, vertices=0x3a4b270, vertsize=32)
    at ../SDL2-2.0.12/src/render/opengl/SDL_render_gl.c:1307
#3  0x00004555556d6f18 in FlushRenderCommands (renderer=0x38ef6e0) at ../SDL2-2.0.12/src/render/SDL_render.c:222
#4  0x00004555556f0350 in SDL_RenderPresent_REAL (renderer=0x38ef6e0) at ../SDL2-2.0.12/src/render/SDL_render.c:3151
#5  0x0000455555683c10 in SDL_RenderPresent (a=0x38ef6e0) at ../SDL2-2.0.12/src/dynapi/SDL_dynapi_procs.h:377
#6  0x00000000005314d0 in GFX_EndUpdate (changedLines=0xc2dffff1d28c) at ../src/gui/sdlmain.cpp:1620
#7  0x00000000005331d8 in _INTERNAL_11_sdlmain_cpp_57e1d4e0::DisplaySplash (time_ms=1000) at ../src/gui/sdlmain.cpp:1940
#8  0x00000000005379a0 in _INTERNAL_11_sdlmain_cpp_57e1d4e0::GUI_StartUp (sec=0x35a54a0) at ../src/gui/sdlmain.cpp:2474
#9  0x00000000007c7fd8 in Section::ExecuteInit (this=0x35a54a0, initall=true) at ../src/misc/setup.cpp:916
#10 0x00000000007d65a8 in Config::Init (this=0xc2dfffffe7a0) at ../src/misc/setup.cpp:887
#11 0x0000000000547c90 in sdl_main (argc=1, argv=0xc2dfffffe9c8) at ../src/gui/sdlmain.cpp:3582
#12 0x0000000000025100 in main (argc=1, argv=0xc2dfffffe9c8) at ../src/main.cpp:30
```

**Comment by 1bsyl** [comment]
@Fatton1 that's prevent the crash, but probably YUV texture cannot work correctly.
please give a try!

**Comment by Fatton1** [comment]
@1bsyl I tried it, but now Dosbox0.77.0 is showing a black screen without any textures. There are just messages of "_SDL: Using driver "opengl" for texture renderer_' in the console.

**Comment by 1bsyl** [comment]
@Fatton1 strange, not sure how Dosbox works.
I simply tried not to load this extension, then it crashes, if fixed it, and it was correctly displaying textures.
(note, in the code, if the extension isn't enabled, yuv aren't reported to be supported)


maye try the software renderer: 
setting the env: SDL_RENDER_DRIVER=software

**Comment by Fatton1** [comment]
@1bsyl I have built SDL with this setting and nothing changed. I will try to fix Dosbox later, maybe there are some troubles with YUV.

**Comment by Fatton1** [comment]
@1bsyl Software Renderer

**Comment by 1bsyl** [comment]
@Fatton1 software renderer is always built. It needs to be activated / forced. Check that, so that you can tell whether the issue is having multitexturing or not.

**Comment by Fatton1** [comment]
@1bsyl Yes, i have built the SDL with the forced parameter SDL_RENDER_DRIVER=software and the window of Dosbox is still black.

**Comment by Fatton1** [comment]
@1bsyl Ah, I got it. Ok, I will check i.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
