### ISSUE TITLE
Windows bug: window size continues to increase or shrink across monitors of different magnifications

### ISSUE THREAD

**Issue by hsdk123** [libsdl-org/SDL#4712]
Hi, I'm running into a bug where, if I have 2 monitors with different magnification scales, moving a window from one monitor to another, has the application window to continue shrinking or increasing each time I move. (this happens when the app window is sitting across both monitors)

**Comment by ericwa** [comment]
I think this is the same issue as https://github.com/libsdl-org/SDL/issues/3286

**Comment by slouken** [comment]
I think this is the correct behavior. If you have one monitor at 100% scale and another monitor at 200% scale, when you move from the 100% monitor to the 200% monitor, Windows will automatically double the size of your application window. If you want to avoid this behavior you have to tell Windows that your application is DPI aware (which is outside the scope of this issue)

Please reopen this bug if what I'm describing isn't what's happening here.

**Comment by hsdk123** [comment]
@slouken Hey, you've misinterpreted the issue - the bug is that the scaling 'continues' to occur - it doesn't stop and the window eventually becomes larger than the screen.

**Comment by hsdk123** [comment]
I'm not sure how I reopen this thread.

**Comment by slouken** [comment]
So let me see if I understand the steps:
There's a monitor at 100% scaling and one at 150%, the app launches on the monitor with 100% scaling, when it moves halfway onto to the 150% monitor, it increases in size by 50%, and when you move it back it doesn't shrink?

Do you have a video of this in action, or can we do a video call so I can see what's happening?

**Comment by hsdk123** [comment]
@slouken 
https://photos.app.goo.gl/mztj8VupzvPyZJYH9

The monitor on the left is at 100% scaling, the monitor on the right is at 150%.
As you can see from the video, **each time** I try pull it towards the left monitor, the window size keeps increasing.

**Comment by ericwa** [comment]
@hsdk123 is your application enabling DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2? I can reproduce this in SDL by enabling that DPI awareness level.

Assuming your app is doing that: what's going on is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 is promising Windows that we've made certain code changes in SDL which we actually haven't made yet, so we get this bad behaviour as a result. The specific call that is causing the infinite growth is the `AdjustWindowRectEx` call in `SDL_windowsevents.c`'s  WM_GETMINMAXINFO handler need to be replaced with `AdjustWindowRectExForDpi`. So, applications must not enable per-monitor-v2 until we update SDL to support it.

---

Further details on how to repro this:

Display setup:
- 3840x2160 pixels, (main display), 150% scaling
- 2560x1440 pixels, to the right, 100% scaling

Steps:
- apply [enable-v2-awareness.patch.txt](https://github.com/libsdl-org/SDL/files/7921450/enable-v2-awareness.patch.txt) to cause SDL to declare DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 awareness at startup
- launch SDL's testwm2 test program
- drag from the main display (150% scaled) to the monitor on the right - once it switches monitors, it should start growing for each pixel you drag the window
