### ISSUE TITLE
Android dlopen failed: library "libmain.so" not found

### ISSUE THREAD

**Issue by ambitslix** [libsdl-org/SDL#4715]
Android Studio 2020.3.1 patch 1
Build variant debug x86_64
Device pixel C api 31 abi x86_64
minSdk 21
build cmake
SDL latest main branch

Hello,

I've been able to build and run simple SDL2 app under latest Android Studio based on README-android, however I get the following error first in the app then in logcat:

```
W/System.err: dlopen failed: library "libmain.so" not found
```

Then the app exits via the exit button.

I saw in SDL/CMakeLists.txt about the dlopen issue and try to revert to:
```
find_library(ANDROID_DL_LIBRARY dl)
```

but still the same problem occurs.

My test app is the exact copy of android example from here:

https://lazyfoo.net/tutorials/SDL/52_hello_mobile/52_hello_mobile.zip

Any ideas?

Thank you!

**Comment by icculus** [comment]
Can you post the failing .apk file somewhere?

**Comment by ambitslix** [comment]
Have at it :)

https://www.dropbox.com/s/zwvwxxqtisp84k5/app-debug.apk?dl=0

Thanky

**Comment by ambitslix** [comment]
Update, I was able to get around the libmain.so dlopen issue by changing SDLActivity.java getlibraries with the correct library name for my app instead of main:

```
/**
     * This method is called by SDL before loading the native shared libraries.
     * It can be overridden to provide names of shared libraries to be loaded.
     * The default implementation returns the defaults. It never returns null.
     * An array returned by a new implementation must at least contain "SDL2".
     * Also keep in mind that the order the libraries are loaded may matter.
     * @return names of shared libraries to be loaded (e.g. "SDL2", "main").
     */
    protected String[] getLibraries() {
        return new String[] {
            "hidapi",
            "SDL2",
            "SDL2_image",
            // "SDL2_mixer",
            // "SDL2_net",
            // "SDL2_ttf",
            "sdlhello"  // instead of main
        };
``` 

The proper way would be to override this, but for now this is OK.

Now I'm faced with the following java exception:

**Need android.permission.BLUETOOTH_CONNECT permission**

**Comment by icculus** [comment]
Fwiw, this manifest works for me on Android (but I haven't actually _tried_ it with a bluetooth device, I just don't get an exception crashing the game, ymmv)...

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    android:versionCode="22"
    android:versionName="1.2"
    android:installLocation="auto"
    android:compileSdkVersion="29"
    android:compileSdkVersionCodename="10"
    package="org.your_company_here.your_game_name_here"
    platformBuildVersionCode="29"
    platformBuildVersionName="10">

    <!-- This will increase later as necessary. -->
    <uses-sdk android:minSdkVersion="26" android:targetSdkVersion="29" />

    <!-- OpenGL ES 2.0 -->
    <uses-feature android:glEsVersion="0x00020000" />

    <!-- Touchscreen support -->
    <uses-feature
        android:name="android.hardware.touchscreen"
        android:required="false" />

    <!-- Game controller support -->
    <uses-feature
        android:name="android.hardware.bluetooth"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.gamepad"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.usb.host"
        android:required="false" />

    <!-- External mouse input events -->
    <uses-feature
        android:name="android.hardware.type.pc"
        android:required="false" />

    <!-- Audio recording support -->
    <!-- if you want to capture audio, uncomment this. -->
    <!-- <uses-feature
        android:name="android.hardware.microphone"
        android:required="false" /> -->

    <!-- Allow writing to external storage -->
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <!-- Allow access to Bluetooth devices -->
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <!-- Allow access to the vibrator -->
    <uses-permission android:name="android.permission.VIBRATE" />
    <!-- Allow access to sockets -->
    <uses-permission android:name="android.permission.INTERNET" />

    <!-- if you want to capture audio, uncomment this. -->
    <!-- <uses-permission android:name="android.permission.RECORD_AUDIO" /> -->

    <!-- Create a Java class extending SDLActivity and place it in a
         directory under app/src/main/java matching the package, e.g. app/src/main/java/com/gamemaker/game/MyGame.java
 
         then replace "gtkActivity" with the name of your class (e.g. "MyGame")
         in the XML below.

         An example Java class can be found in README-android.md
    -->

    <application
        android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="true"
        android:hardwareAccelerated="true" >

        <!-- Example of setting SDL hints from AndroidManifest.xml:
        <meta-data android:name="SDL_ENV.SDL_ACCELEROMETER_AS_JOYSTICK" android:value="0"/>
         -->
     
        <activity
            android:label="@string/app_name"
            android:name="DragonRubyActivity"
            android:launchMode="singleInstance"
            android:configChanges="layoutDirection|locale|orientation|uiMode|screenLayout|screenSize|smallestScreenSize|keyboard|keyboardHidden|navigation"
            android:alwaysRetainTaskState="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <!-- Drop file event -->
            <!--
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="*/*" />
            </intent-filter>
            -->
        </activity>
    </application>
</manifest>
```

**Comment by ambitslix** [comment]
Yes, that won't work probably on a device with bluetooth in newer AS. If I turn off bluetooth in the device and uncomment android.permission.BLUETOOTH it works also.

**Comment by icculus** [comment]
Pinging @1bsyl...do we need to update our example AndroidManifest.xml ?

**Comment by ambitslix** [comment]
This may provide some clarity...

https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by 1bsyl** [comment]
Maybe just call the function to get the android permission ?

SDL_AndroidRequestPermission("android.permission.BLUETOOTH_CONNECT");

https://github.com/libsdl-org/SDL/blob/main/include/SDL_system.h#L319

**Comment by 1bsyl** [comment]
@ambitslix 
also, what is you android targetSdkVersion ?
when did this  permission / exception occurs ? is this the HID java code ?

**Comment by 1bsyl** [comment]
https://developer.android.com/about/versions/12/features/bluetooth-permissions
this seems a new thing to do when targeting Android-12
it says to add it in the AndroidManifest.xml (https://developer.android.com/about/versions/12/features/bluetooth-permissions#declare-new-permissions)
and also that it's a runtime permission, so the code need to request the permission 
( https://developer.android.com/about/versions/12/features/bluetooth-permissions#user-facing-dialog )

**Comment by ambitslix** [comment]
My targetSdk is 31, the exception occurs from Java...And as understand as you said that there needs to be a some java calls now to request permission.

**Comment by 1bsyl** [comment]
@ambitslix 
Set the targetSdk to 26, as in the SDL build.gradle 
(probably 26 to 30 should work)

**Comment by ambitslix** [comment]
Ok thanks I will try that.

**Comment by papasha1213** [comment]
![Screenshot_20240926-113105](https://github.com/user-attachments/assets/5ef8895c-bb53-43ee-9666-dcfa55eb91d3)
My phone is: Redmi C51, Android 13

**Comment by madebr** [comment]
@papasha1213 

Apply the change from https://github.com/libsdl-org/SDL/issues/4715#issuecomment-912998957, but replace `sdlhello` with the name of your shared library.
