### ISSUE TITLE
Applying a texture to a primitive.

### ISSUE THREAD

**Issue by NePutin94** [libsdl-org/SDL#4716]
I want to texture some primitive, as I understand SDL does not support this, so I use opengl. 
I used the code from [this](https://wiki.libsdl.org/SDL_GL_BindTexture) example: 
```C++
SDL_GL_BindTexture(testT.getTextureP(), NULL, NULL);
auto test = SDL_GetError();
glEnable(GL_BLEND);
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

glEnableClientState(GL_VERTEX_ARRAY);
glVertexPointer(3, GL_FLOAT, 0, Vertices);
glEnableClientState(GL_TEXTURE_COORD_ARRAY);
glTexCoordPointer(2, GL_FLOAT, 0, TexCoord);

glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_BYTE, indices);

glDisableClientState(GL_VERTEX_ARRAY);
glDisableClientState(GL_TEXTURE_COORD_ARRAY);
glDisable(GL_BLEND);
SDL_GL_UnbindTexture(testT.getTextureP());
SDL_SetRenderDrawBlendMode(w.getContext(), SDL_BLENDMODE_NONE);
SDL_RenderFlush(w.getContext());
```
But the texture is not superimposed on the rectangle. Am I wrong somewhere?
![изображение](https://user-images.githubusercontent.com/25349002/132092209-9198aece-5fe6-427a-a542-b05f3f977640.png)
In the example, they access opengl via render_data, I understand that this is SDL_Renderer, how can I do the same?

**Comment by bradallred** [comment]
isn't this what `SDL_RenderGeometry` and `SDL_RenderGeometryRaw` are for?

**Comment by NePutin94** [comment]
It's true. I tried to find something in Google, but no link led to this. Thanks
