### ISSUE TITLE
SDL2, SDL_Log behaves strange using %c with a 0 value.

### ISSUE THREAD

**Issue by theoldnewb** [libsdl-org/SDL#4717]
Hello everybody,

I don't know if this is a bug or not. But SDL_Log does not behave like printf in certain circumstances.
It seems that the moment a null character is printed via "%c" the output just stops.
[sdl_log_test.cpp.txt](https://github.com/libsdl-org/SDL/files/7111485/sdl_log_test.cpp.txt)

Sorry, for the formating, github 'eats' the bracket characters... 

```
// gcc sdl_log_test.cpp -o sdl_log_test -lSDL2
// ./sdl_log_test 
// Output:
// INFO: SDL: <
// PRINTF: <>,<b>
```

Kind regards,
theoldnewb

`
#include <stdio.h>
#include "SDL2/SDL.h"

int main()
{
    int a = 0 ;
    int b = 'b' ;

    SDL_Log("SDL: <%c>,<%c>", a, b) ;
    printf("PRINTF: <%c>,<%c>\n", a, b) ;

    return 0 ;
}

`

**Comment by sezero** [comment]
It is because `int a = 0 ;`

Try this instead:
```
snprintf(buf,sizeof(buf),"TEST: <%c>,<%c>\n", a, b);
printf("%s\n",buf);
```
.. which is practically what `SDL_Log` does behind the scene,
i.e. `%c` taking `0` terminates the temporary string buffer,
therefore nothing after that is printed.

**Comment by theoldnewb** [comment]
Thank you very much for the explanation.
