### ISSUE TITLE
Emscripten: Pass sampleRate param to the AudioContext constructor

### ISSUE THREAD

**Issue by macias0** [libsdl-org/SDL#4722]
https://github.com/libsdl-org/SDL/blob/ddfd21a6784f533bdd04b7e0dd61a0f400eee96e/src/audio/emscripten/SDL_emscriptenaudio.c#L217

It is possible to pass the `sampleRate` param to the `AudioContext` [constructor](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext)

If you can pass a parameter with the `desired` frequency to the `SDL_OpenAudioDevice`, it should be used in the implementation.
Currently it is ignored and the browser chooses the sampleRate (from OS current device frequency).

Also, if the `SDL_AUDIO_ALLOW_FREQUENCY_CHANGE` flag is not passed to the `SDL_OpenAudioDevice` function, the `obtained` parameter will not contain the correct frequency.

**Comment by icculus** [comment]
This issue was for SDL2, but in SDL3, it's an intentional decision to let the browser dictate the final sample rate. It's just going to be a question of where resampling happens anyhow.
