### ISSUE TITLE
Android SDL2-static linkage

### ISSUE THREAD

**Issue by ambitslix** [libsdl-org/SDL#4723]
Hi,

I've been toying with statically linking my SDL2 app with SDL, SDL_image etc. My partial builds are now much faster, no dlopen needed and no need to bundle dynamic libs.

Is there a downside to doing this for SDL and Android?

**Comment by slouken** [comment]
Nope, not on Android.

**Comment by ambitslix** [comment]
Great. What about other platforms since you said "on Android"? Also is there any interest in tiding up the cmake build system for SDL2? It seems it's a work in progress starting SDL_image/ttf/gfx. Are there any goals with it? Takes some tinkering to build statically and install locally. Is autotools still the official build system for SDL2?

**Comment by slouken** [comment]
On desktop platforms it's beneficial to link them dynamically so the end user can drop in replacements with improvements and support for new environments. A good example of this is Steam Linux games are getting an SDL upgrade that adds support for Wayland, extending the games to a new desktop environment.

**Comment by slouken** [comment]
Both autotools and CMake are used by different developers and are intended to continue to be supported. Feel free to submit pull requests for enhancements.

**Comment by ambitslix** [comment]
Will do, thanks.
