### ISSUE TITLE
autoconf build: running make a second time doesn't produce libSDL2.so`*`

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#4728]
after extracting 2.0.16 tarball, and running ./configure, make, make install, changing a random source file and running make again looks like this:

```
$ make
/bin/sh build-scripts/updaterev.sh
  CC     build/SDL_sysjoystick.lo
  LTLINK build/libSDL2.la
ar: `u' modifier ignored since `D' is the default (see `U')
```
i.e. libSDL2.so isn't created as it should, and make install doesn't create/install it either.
this makes it impossible to develop on SDL2 without recompiling everything over and over for every tiny change (before it is being suggested: no, i don't want to use CFake).

**Comment by sezero** [comment]
If the only problem is ARFLAGS, does applying this and regenerating configure help?
http://git.savannah.gnu.org/gitweb/?p=libtool.git;a=commitdiff;h=418129bc63afc312701e84cb8afa5ca413df1ab5

**Comment by rofl0r** [comment]
that does nothing more than muting that irrelevant warning.
the issue here is almost certainly that some dependencies aren't properly documented.

```
/src/build/sdl2/SDL2-2.0.16 # touch src/joystick/linux/SDL_sysjoystick.c
/src/build/sdl2/SDL2-2.0.16 # make
/bin/sh build-scripts/updaterev.sh
  CC     build/SDL_sysjoystick.lo
  LTLINK build/libSDL2.la
/src/build/sdl2/SDL2-2.0.16 # 
```

**Comment by rofl0r** [comment]
does the .so build depend on that .la archive ? if so it might help to delete the .a/.la always before trying to generate it - most handwritten makefiles have their rules for .a look like:

```
foo.a: $(DEPS)
    rm foo.a
    ar cru foo.a $(DEPS)
```

**Comment by sezero** [comment]
Sorry that I didn't mention this before: Run `make V=1` to see what
actually happens: Without `V=1` you'll only see `*.la` in the output,
with it you should see both `*.a` and the `*.so`. If you don't, then
there is a problem.

**Comment by rofl0r** [comment]
ouch. that does actually build a .so. guess the bogus output fooled me into thinking nothing happened

**Comment by sezero** [comment]
Ok, closing as invalid.

**Comment by rofl0r** [comment]
why does it not print that it's creating the .so though ?

**Comment by sezero** [comment]
IIRC, it's a libtool thing: in silent mode it only prints that it's generating the *.la file.
The *.la file can contain only *.a or only *.so or both, depending on how you configured.
