### ISSUE TITLE
[macOS] SDL2-2.0.14 sends two SDL_CONTROLLERDEVICEADDED events when my Xbox One X controller is attached

### ISSUE THREAD

**Issue by pcbeard** [libsdl-org/SDL#4732]
A simple SDL2 program that calls SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER), and waits for SDL_CONTROLLERDEVICEADDED events to arrive, receives two events when my Xbox One X controller is attached. They have distinct SDL_JoystickGUID and SDL_JoystickID values and their names are:

"Xbox One S Controller"
"Xbox Wireless Controller"

If I connect both of them, I see double SDL_JOYBUTTONDOWN / SDL_JOYBUTTONUP and SDL_JOYAXISMOTION events. For the controller that's called "Xbox Wireless Controller", the actual SDL_GameControllerButton values are incorrect. They are correct for the "Xbox One S Controller" controller.

Note, if I change the program to use SDL_Init(SDL_INIT_GAMECONTROLLER), this double connection doesn't happen and the correct controller is identified.

**Comment by slouken** [comment]
How is your Xbox One X controller connected to your Mac? What version of macOS are you running?

**Comment by pcbeard** [comment]
Here's a complete test case:

```
@interface SDLTests : XCTestCase
@end

@implementation SDLTests {
    NSMutableDictionary<NSNumber *, NSValue *> *controllers;
}

- (void)setUp {
    int rv = SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER);
    XCTAssertEqual(rv, 0);
    
    controllers = [NSMutableDictionary new];
}

- (void)tearDown {
    for (NSValue *value in controllers.allValues) {
        SDL_GameController *controller = value.pointerValue;
        if (controller != NULL) {
            SDL_GameControllerClose(controller);
        }
    }
    SDL_Quit();
}

- (void)addController:(SDL_ControllerDeviceEvent)deviceEvent {
    Sint32 deviceIndex = deviceEvent.which;
    if (SDL_IsGameController(deviceIndex) == SDL_TRUE) {
        SDL_GameController *controller = SDL_GameControllerOpen(deviceIndex);
        if (controller != NULL) {
            SDL_JoystickID deviceID = SDL_JoystickGetDeviceInstanceID(deviceIndex);
            controllers[@(deviceID)] = [NSValue valueWithPointer:controller];
            SDL_Log("attached controller:  %s", SDL_GameControllerName(controller));
        }
    }
}

- (void)waitForControllers {
    SDL_Event event;
    while (controllers.count == 0) {
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_CONTROLLERDEVICEADDED) {
                SDL_Log("SDL_CONTROLLERDEVICEADDED");
                [self addController:event.cdevice];
            }
        }
    }
}

- (void)testGameControllerDeviceAdded {
    [self waitForControllers];
    XCTAssertEqual(controllers.count, 1);
}

@end
```

This test fails because with libsdl v2.0.14, controllers.count == 2.

**Comment by pcbeard** [comment]
@slouken I'm running macOS Big Sur 11.5.2, and the Xbox controller is connected via Bluetooth.

**Comment by slouken** [comment]
Do you get the same problem with the latest SDL snapshot?
https://www.libsdl.org/tmp/SDL-2.0.zip

If so, do you also see the problem when running the testgamecontroller test program, included with the source snapshot?

**Comment by slouken** [comment]
This might also fix it:
https://github.com/libsdl-org/SDL/commit/ff85d4fbe5c013093a956f1126017e61d9ed37cd

**Comment by pcbeard** [comment]
Yes, that fixes the problem. As I stated in issue #4733, this problem is apparently fixed even in 2.0.16, but the controller is misidentified and the button values are wrong.

**Comment by pcbeard** [comment]
I guess we can close this one.

**Comment by slouken** [comment]
Great, thanks for the feedback!
