### ISSUE TITLE
[Linux] Xbox wireless controller detection

### ISSUE THREAD

**Issue by tome9111991** [libsdl-org/SDL#4734]
Hello
I use a Xbox one controller on Ubuntu mate 21.04 x64 via bluetooth.
Since sdl 2.0.9 i have issue with the controller name detection.
It will break my Retropie config.
Becsuse Emulatorstaion and Retroarch detect 2 different controller names.
First detect as "Xbox One S Controller"  second as "Xbox Wireless"

Here a output from sdl2-jstest with SDL2.0.16
```
 Joystick Name:     'Xbox One S Controller'
Joystick GUID:     050000005e040000fd02000003090000
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 17
Number of Hats:     1
Number of Balls:    0
GameControllerConfig:
  Name:    'Xbox One Wireless Controller'
  Mapping: '050000005e040000fd02000003090000,Xbox One Wireless Controller,a:b0,b:b1,back:b15,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b16,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b3,y:b4,platform:Linux,'
```
a dev by retropie thought it was related with HIDAPI drivers.
But i have compiled latest SDL with `--disable-api`
Still same problem.

You can find issue here.
https://github.com/RetroPie/RetroPie-Setup/issues/3398

Maybe anyone had an idea?

**Comment by pcbeard** [comment]
Sounds like the same thing as #5432.

**Comment by tome9111991** [comment]
> Sounds like the same thing as issue #4732.

True.
Is this fix only for macOS?

**Comment by FrodeSolheim** [comment]
This does not sound like an SDL bug about detecting two controllers, so not the same as [#4732](https://github.com/libsdl-org/SDL/issues/4732).

The problem described in https://github.com/RetroPie/RetroPie-Setup/issues/3398 seems to be rather about one part of the RetroPie system using udev device names (or similar), while other parts of the combined system uses SDL names - which in the latest SDL versions are cleanup by the SDL_CreateJoystickName function and therefore does no longer always match.

**Comment by FrodeSolheim** [comment]
That being said, it could be useful with an `SDL_HINT_JOYSTICK_USE_ORIGINAL_NAMES` or something like that...
