### ISSUE TITLE
SDL_SetWindowMinimumSize failing on Windows 11

### ISSUE THREAD

**Issue by allkern** [libsdl-org/SDL#4736]
This function is apparently failing on Windows 11 hosts. Setting any minimum size will have no effect, the window will be resizable past the specified minimum size, down to (120, 1).

I wrote some minimal code to test this particularly

![image](https://user-images.githubusercontent.com/15825466/132712537-93f78555-8f5d-4a55-9ab4-4f04b4379ef1.png)

Excuse me using an image, I couldn't use a code block, for some reason, the tildes are stacking on top of each other, not letting me correctly enclose the code 👎🏻

Changing the order of calls doesn't have any effect either.

OS: Windows 11 Pro (10.0.22000 Build 22000)

**Comment by baidwwy** [comment]
I tested 22000.176 and 22000.184 without reproducing the problem
SDL ver https://github.com/libsdl-org/SDL/commit/6f972052296fdfe63ecaa7edab3e5b4e663eea06

Sorry, I don’t know English, this is a translation from Google

**Comment by slouken** [comment]
I tested using testsprite2 --resizable --min-geometry 320x200 and wasn't able to reproduce it. I'll try your code as well.

**Comment by slouken** [comment]
I was also not able to reproduce it with your test code, running Windows 11 21H2. Are you able to debug it and find out what's happening?

Here's the code for future copy-paste reference:
```
#include "SDL.h"

#include <iostream>

#undef main

int WinMain()
{
	SDL_Init( SDL_INIT_VIDEO | SDL_INIT_EVENTS);

	SDL_Window *window = SDL_CreateWindow( "test", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 500, 500, SDL_WINDOW_RESIZABLE );
	SDL_Renderer *renderer = SDL_CreateRenderer( window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC );

	bool open = true;
	SDL_SetWindowMinimumSize( window, 250, 250 );
	while ( open )
	{
		SDL_Event event;
		while ( SDL_PollEvent( &event ) )
		{
			switch ( event.type )
			{
			case SDL_QUIT: { open = false; } break;
			case SDL_WINDOWEVENT: {
				int width = 0, height = 0;

				SDL_GetWindowSize( window, &width, &height );

				std::cout << width << " " << height << std::endl;
			}
			}
		}

		SDL_RenderClear( renderer );
		SDL_RenderPresent( renderer );
	}

	SDL_DestroyRenderer( renderer );
	SDL_DestroyWindow( window );
	SDL_Quit();
}
```

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
