### ISSUE TITLE
SDL fires `TEXTEDITING` event on startup despite not calling `StartTextInput`

### ISSUE THREAD

**Issue by jai-x** [libsdl-org/SDL#4739]
OS: Arch Linux kernel 5.13.13-arch-1-1 (mainline not custom built)
SDL Version: 2.0.16
iBus Version: 1.5.25

When the iBus daemon is running, upon SDL program start, SDL will fire many `SDL_TEXTEDITING` events.
These events occur before any call is made to `SDL_StartTextInput`.
These events will continue to fire until a call is made to `SDL_StopTextInput`, at which point they will stop.
These events seem to fire on window focus and unfocus.
In the event data, value `text` contains an empty string, value `start` is zero, value `length` is zero.

From the text input tutorial and supporting documentation, I assume that this behavior is unintentional and text based events should only occur after a call to `SDL_StartTextInput` is made: https://wiki.libsdl.org/Tutorials-TextInput

This should be easily reproducible, but I have also made a test program: https://github.com/jai-x/sdl-text-test/

**Comment by icculus** [comment]
Input is considered "started" by default on desktop environments. On things with virtual keyboards, like iOS and Android, it defaults to stopped.

This is a little confusing, but expected behavior.

(I can't speak to the editing events being correct or not though.)

**Comment by jai-x** [comment]
> Input is considered "started" by default on desktop environments. On things with virtual keyboards, like iOS and Android, it defaults to stopped.
> This is a little confusing, but expected behavior.

I see. In that case would it be fine to add a line about this in the documentation?
I'm assuming updating the comments in the header files will result in the wiki being updated?

**Comment by icculus** [comment]
Sure, go for it!

**Comment by icculus** [comment]
Editing it on the wiki updates the headers, too, if that's easier.  :)

**Comment by slouken** [comment]
Text input is no longer enabled at startup.
