### ISSUE TITLE
SDL2 2.0.16 Gamepad Showing Multiple Times vs 2.0.14

### ISSUE THREAD

**Issue by Lycanite** [libsdl-org/SDL#4740]
On upgrading to SDL2 2.0.16 my Azeron gamepad is coming up as 4 unusable devices! I've had to rollback to 2.0.14.
Here's the output of sdl2-jstest -l for each version:

**2.0.16 Broken**
`error: failed to read gamecontrollerdb.txt: Invalid RWops
Found 4 joystick(s)

Joystick Name:     'LTD Azeron Keypad'
Joystick GUID:     03000000d01600003f0f00000c006800
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 15
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'LTD Azeron Keypad'
  Mapping: '03000000d01600003f0f00000c006800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,'

Joystick Name:     'LTD Azeron Keypad'
Joystick GUID:     03000000d01600003f0f00000c006800
Joystick Number:    1
Number of Axes:     6
Number of Buttons: 15
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'LTD Azeron Keypad'
  Mapping: '03000000d01600003f0f00000c006800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,'

Joystick Name:     'LTD Azeron Keypad'
Joystick GUID:     03000000d01600003f0f00000c006800
Joystick Number:    2
Number of Axes:     6
Number of Buttons: 15
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'LTD Azeron Keypad'
  Mapping: '03000000d01600003f0f00000c006800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,'

Joystick Name:     'LTD Azeron Keypad'
Joystick GUID:     03000000d01600003f0f00000c006800
Joystick Number:    3
Number of Axes:     6
Number of Buttons: 15
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'LTD Azeron Keypad'
  Mapping: '03000000d01600003f0f00000c006800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,'`

**2.0.14 Working**
`error: failed to read gamecontrollerdb.txt: Invalid RWops
Found 1 joystick(s)

Joystick Name:     'LTD Azeron Keypad'
Joystick GUID:     03000000d01600003f0f000011010000
Joystick Number:    2
Number of Axes:     5
Number of Buttons: 32
Number of Hats:     1
Number of Balls:    0
GameControllerConfig:
  missing (see 'gamecontrollerdb.txt' or SDL_GAMECONTROLLERCONFIG)`

It looks like it's possibly related to mapping, maybe some new mappings are conflicting with this device (looks like the GUID is coming up different in the newer version, perhaps it's being read as the wrong device, it has a lot more than 15 buttons)? The device itself is a gaming keypad of sorts so I don't need to map it to a standard controller, but I do use AntimicroX heavily to configure this device and with this update the entire setup is bust. Let me know if you need more info.

**Comment by slouken** [comment]
Do you have some time to chat about this? What's the best way to reach you?

**Comment by slouken** [comment]
Please send me e-mail at slouken@libsdl.org with how to debug this interactively with you. I can do Zoom, Slack, Discord, etc.

**Comment by apmak3** [comment]
I tried that but have no success. But to crosscheck i updated my laptop also to fedora 36 and indeed same version of sdl and antimicrox and my keypad works even sdl2-jstest shows it correct. So it seems that problem is on my system. Sorry for waking this thread.
