### ISSUE TITLE
wayland libdecor: libdecor support not built with autotools

### ISSUE THREAD

**Issue by robertpfeiffer** [libsdl-org/SDL#4744]
I compiled and installed libdecor on my Ubuntu 21.04 machine. It works, and the demos work.

I tried the following with the latest release and master from git.

I compiled SDL2 with `./configure --enable-video-wayland --enable-wayland-shared --enable-libdecor --enable-libdecor-shared --enable-ssemath CFLAGS=-march=native && make -j 8`

I ran a SDL2 test program with enviroment variables `SDL_DYNAMIC_API=~/path/to/libSDL2-2.0.so.0.17.0 SDL_VIDEODRIVER=wayland` on weston and then gnome shell. It dod not have window decorations. (On sway, everything works already without libdecor and on SDL 2.0.14 because of server-side decorations. I did not test KDE.)

I investigated a bit, and I found that `SDL_WAYLAND_HAVE_WAYLAND_LIBDECOR` is not set, even though `HAVE_LIBDECOR_H` is set.

When building with cmake instead of autotools, everything works correctly.

**Comment by flibitijibibo** [comment]
I was unable to reproduce this locally - tested on Fedora 34 and CentOS 7.

**Comment by dos1** [comment]
Debian packaging uses autotools and I was able to build a deb with working libdecor support just fine as well (it doesn't use `shared` though)

**Comment by ernstp** [comment]
Works for me also, and I also built debian packages.
