### ISSUE TITLE
X11: SDL_ShowMessageBox provides a misleading error upon failure

### ISSUE THREAD

**Issue by Ciastex** [libsdl-org/SDL#4760]
**SDL version:** 2.0.16
**Build type:** from source; shared library
**Platform:** x86_64 Linux 5.13.10; X server 1.20.13; gcc 11.1.0

## Issue details
While trying to debug a possible issue with my software built atop SDL2 I've stumbled upon SDL_ShowMessageBox unconditionally saying there is "No message system available" while I could pretty much confirm there was one available and ready to use. After digging deeper into SDL2 it turns out that if any errors occur during [X11_ShowMessageBoxImpl initialization](https://github.com/libsdl-org/SDL/blob/release-2.0.16/src/video/x11/SDL_x11messagebox.c#L813), even despite [X11_MessageBoxInit setting meaningful errors](https://github.com/libsdl-org/SDL/blob/release-2.0.16/src/video/x11/SDL_x11messagebox.c#L201), those get [overwritten by SDL_ShowMessageBox](https://github.com/libsdl-org/SDL/blob/release-2.0.16/src/video/SDL_video.c#L4265) - links lead to direct line numbers contributing to the root cause of the issue.

I have succeeded in getting to the X11 error through printf-based debugging and - in my case - the error overwritten was X11 being unable to create the UTF-8 font set defined by SDL2 for a reason I'm yet to find out. I'd wager it's due to locale misconfiguration on my end as explained near the bottom of this [XCreateFontSet description section](https://www.x.org/releases/current/doc/man/man3/XCreateFontSet.3.xhtml#heading4) - I have already tried to run my software with different `LC_ALL` values - including `en_US`, `en_US.UTF-8` and `C` - it seems to make no difference, but I'm not sure if this subject is in scope of this issue.

## Proposed solution
Perhaps SDL could copy the underlying sub-system error before overwriting it in `SDL_ShowMessageBox` and append the copy afterwards. That would make the error a bit less vague for the end-user.

**Comment by flibitijibibo** [comment]
I wonder if this is the same story as #4495?

**Comment by audetto** [comment]
I have hit the same issue. The proposed solution seems to fix the error message, but not still not able to display the message.

Have you found a way to do it?
