### ISSUE TITLE
Compilation of hidapi.framework fails if MacOS deployment target is set >= 10.8

### ISSUE THREAD

**Issue by fergu** [libsdl-org/SDL#4763]
I've been trying to compile SDL2 as a framework for Apple Silicon. The Xcode project files that are in this repo have the MacOS target version for both the `Framework` and `hidapi` targets left blank, for which Xcode fills in 10.6 as the target version and then throws a warning that this configuration is unsupported. If one updates the target OS to even just the minimum of 10.9 the build will fail with the error that the symbol `_IOS_SupportedHIDDevice` being undefined for the `hidapi` target. This failure in turn prevents the `framework` target from compiling.

After some digging, this appears to be related to these lines in `./Library Source/hidapi/mac/hid.c`, currently at lines 494-501 as of the time of this writing:

```
#if defined(SDL_JOYSTICK_MFI)
		// We want to prefer Game Controller support where available,
		// as Apple will likely be requiring that for supported devices.
		extern SDL_bool IOS_SupportedHIDDevice(IOHIDDeviceRef device);
		if (IOS_SupportedHIDDevice(dev)) {
			continue;
		}
#endif
```

`SDL_JOYSTICK_MFI` is defined like so in `SDL_config_macosx.h`, lines 161-163 as of this writing:

```
#if MAC_OS_X_VERSION_MIN_REQUIRED >= 1080 && !defined(__i386__)
#define SDL_JOYSTICK_MFI 1
#endif
```

Playing around with the target OS build setting confirms that it is this directive that's causing the issue. This being set causes the build to fail. This, in turn, seems to be related to the definition of `IOS_SupportedHIDDevice`, defined in `./Library Source/joystick/iphoneos/SDL_mfijoystick.m`, starting at line 1490. A cursory glance seems to suggest that this file has the code that you'd expect, but perhaps it isn't included as part of the `hidapi` target which is why linking fails? I tried playing around to see if it was a simple matter of adding some files and frameworks but things got sticky in a hurry since I'm not familiar with the structure of the code.

Are the Xcode files generated automatically by a script and the relevant files aren't being included in that target? Alternately, is there a way to get the makefile to generate frameworks rather than static libraries?

**Comment by slouken** [comment]
This is not an easy fix, basically the hidapi project needs to be removed and the code built into the SDL library, with appropriate private namespace.

I'm adding this to my list for 2.0.18.

**Comment by MaddTheSane** [comment]
So hidapi will be merging into SDL2 proper, with the need for a duplicate symbol disappearing?

**Comment by slouken** [comment]
> So hidapi will be merging into SDL2 proper, with the need for a duplicate symbol disappearing?

Yep, and this is done.

Thanks!
