### ISSUE TITLE
cannot initialize SDL

### ISSUE THREAD

**Issue by Sundarcj** [libsdl-org/SDL#4774]
i'm trying SDL2 for ios. I followed [this](https://github.com/bminor/SDL/blob/master/docs/README-ios.md) instructions to build libsdl2.a and libsdlmain.a.

Have used the built in ios template xcode project.

But gives me error while Initialization.

SDL Error: Application didn’t initialize properly, did you include SDL_main.h in the file containing your main() function?

could anyone help me?

```
`#include "SDL.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 480

int
randomInt(int min, int max)
{
    return min + rand() % (max - min + 1);
}

void
render(SDL_Renderer *renderer)
{

    SDL_Rect rect;
    Uint8 r, g, b;

    /* Clear the screen */
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    SDL_RenderClear(renderer);

    /*  Come up with a random rectangle */
    rect.w = randomInt(64, 128);
    rect.h = randomInt(64, 128);
    rect.x = randomInt(0, SCREEN_WIDTH);
    rect.y = randomInt(0, SCREEN_HEIGHT);

    /* Come up with a random color */
    r = randomInt(50, 255);
    g = randomInt(50, 255);
    b = randomInt(50, 255);
    SDL_SetRenderDrawColor(renderer, r, g, b, 255);

    /*  Fill the rectangle in the color */
    SDL_RenderFillRect(renderer, &rect);

    /* update screen */
    SDL_RenderPresent(renderer);
}

int
main(int argc, char *argv[])
{

    SDL_Window *window;
    SDL_Renderer *renderer;
    int done;
    SDL_Event event;

    /* initialize SDL */
    if (SDL_Init(SDL_INIT_EVERYTHING) < 0) {
        printf("Could not initialize SDL\n");
        return 1;
    }

    /* seed random number generator */
    srand(time(NULL));

    /* create window and renderer */
    window =
        SDL_CreateWindow(NULL, 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT,
                         SDL_WINDOW_OPENGL);
    if (!window) {
        printf("Could not initialize Window\n");
        return 1;
    }

    renderer = SDL_CreateRenderer(window, -1, 0);
    if (!renderer) {
        printf("Could not create renderer\n");
        return 1;
    }

    /* Enter render loop, waiting for user to quit */
    done = 0;
    while (!done) {
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_QUIT) {
                done = 1;
            }
        }
        render(renderer);
        SDL_Delay(1);
    }

    /* shutdown SDL */
    SDL_Quit();

    return 0;
}
`
```

**Comment by sidshekar** [comment]
Same here I am also getting the error following the steps!! Were you able to resolve the issue?

**Comment by slouken** [comment]
Try [these](https://github.com/libsdl-org/SDL/blob/main/docs/README-ios.md) instructions, which were just updated.

**Comment by sidshekar** [comment]
@slouken Thanks!! I followed the steps, I am able to build Framework-iOS in the SDL project.

![Screen Shot 2021-12-01 at 11 06 46 AM](https://user-images.githubusercontent.com/2862097/144135786-53a9cad7-77a4-4432-a729-fd72b4779dcc.png)

 but I get the error as below when I try to run my project.

![Screen Shot 2021-12-01 at 11 07 58 AM](https://user-images.githubusercontent.com/2862097/144135930-ae5b12d1-e8fe-493f-83f9-f6bb38e24800.png)


The project is set up properly.

![Screen Shot 2021-12-01 at 11 09 33 AM](https://user-images.githubusercontent.com/2862097/144136124-e60e04ec-b62a-4068-9767-121c0f759d89.png)

![Screen Shot 2021-12-01 at 11 10 30 AM](https://user-images.githubusercontent.com/2862097/144136231-b9740e58-7aaf-491a-b02f-563c3663d9d2.png)

**Comment by sidshekar** [comment]
OK I found what the problem was. When I moved the SDL.xcodeproj the linking of the src and the include files were not proper. I updated the SDL project with the proper folder structure and it works fine on the Simulator.

![Screen Shot 2021-12-01 at 4 13 05 PM](https://user-images.githubusercontent.com/2862097/144165406-7600af5c-57ad-426f-96f5-7c2a86e208b9.png)

![Screen Shot 2021-12-01 at 4 13 26 PM](https://user-images.githubusercontent.com/2862097/144165435-2ae9b074-ec98-4464-bdd3-249e5dbf6a68.png)


However, it fails running on the device!!

![Screen Shot 2021-12-01 at 4 14 35 PM](https://user-images.githubusercontent.com/2862097/144165555-e6ec6a77-8d91-4e1f-bb64-9cecf23a5ce3.png)

**Comment by slouken** [comment]
Great, I'm glad you figured it out!

**Comment by sidshekar** [comment]
Ya well like I said, it work in the simulator, but doesnt work on the device. I still get the error below
![Screen Shot 2021-12-01 at 4 14 35 PM](https://user-images.githubusercontent.com/2862097/144166497-b4bd7cef-db75-491d-a875-340952c1096a.png)
.

**Comment by sidshekar** [comment]
Nevermind, I was able to figure it out in the other issue I created https://github.com/libsdl-org/SDL/issues/5051.

Thanks so much for you help!!

Cheers!

**Comment by slouken** [comment]
You're welcome!
