### ISSUE TITLE
Rendering to textures isn't working for multiple textures

### ISSUE THREAD

**Issue by gnevej** [libsdl-org/SDL#4779]
I have a single renderer with the `SDL_RENDERER_TARGETTEXTURE` flag, and I'm making multiple "layers" using textures.

It works by drawing all the game sprites to the correct layer, and then the handler renders all the layers in the correct order. The layers have the `SDL_PIXELFORMAT_RGBA8888` pixel format and the `SDL_TEXTUREACCESS_TARGET` access.

What happens is that only the _last layer_ is being rendered, and all the others aren't.

I am on Windows 11, and using SDL version `2.0.16`.

**Comment by icculus** [comment]
Can you post some example code that triggers this problem?

Is it possible the textures don't have a blend mode set, so only the only on top appears to have any image?

**Comment by gnevesdev** [comment]
> 
> 
> Can you post some example code that triggers this problem?
> 
> Is it possible the textures don't have a blend mode set, so only the only on top appears to have any image?

Yes, only the texture on top has an image. The code is really big, so take this smaller portion:
```cpp
SDL_SetRenderTarget(render_window->GetRenderer(), nullptr);
SDL_RenderCopy(render_window->GetRenderer(), this->space->GetSnapshot(), this->space->GetView()->GetRectangle(), nullptr);
SDL_RenderCopy(render_window->GetRenderer(), render_window->space->GetSnapshot(), nullptr, nullptr);
```

C++ code, this happens in the rendering part of each game scene, so `this` is the scene itself.
`GetSnapshot()` returns an `SDL_Texture*` containing the current state of the sprites in the scene.
`GetRectangle()` returns an `SDL_Rect*` representing the area to actually draw.
The game has only two layers, one for the GUI, inside the window class, and another one represents the space of the current scene, with all the visible objects drawn to it. That second layer is contained by the actual scene class.

**Comment by slouken** [comment]
The final picture is affected by the order that you draw things and the blending modes that you use.

Typically you draw things in order from the background and the foreground, and you set SDL_BLENDMODE_BLEND on the textures that you're copying, and then make sure the alpha channel is set opaque where you want the image to show and transparent where you want the background to show through.

It looks like you've done drawing with the background last, which draws it over everything else, which would make it look like the other things aren't being drawn. You can test that by commenting out the line where you draw the background and see if the other things show up.

If that takes care of the issue for you, go ahead and close this bug.

Cheers!
