### ISSUE TITLE
render_d3d: determining SDL_RENDERER_TARGETTEXTURE flag

### ISSUE THREAD

**Issue by rversteegen** [libsdl-org/SDL#4781]
A very minor bug. There seems to be a mistake in setting the direct3d render driver's flags.
In D3D_CreateRenderer:
```
    renderer->info.flags = (SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
```
later in the function:
```
    if (caps.NumSimultaneousRTs >= 2) {
        renderer->info.flags |= SDL_RENDERER_TARGETTEXTURE;
    }
```
However, according to [this](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/rendering-to-multiple-targets-simultaneously):
>A DirectX 9.0 version driver can render to multiple targets simultaneously if the driver indicates that its device supports multiple render targets. To indicate the number of render targets that the device supports, the driver sets this number in the NumSimultaneousRTs member of the D3DCAPS9 structure.

I'm not familiar with D3D, but that doesn't sound like the same thing as texture targets. I suspect that maybe that code was written due to a misreading of a remark on [SetRenderTarget](https://docs.microsoft.com/en-us/windows/win32/api/d3d9helper/nf-d3d9helper-idirect3ddevice9-setrendertarget):
> The device can support multiple render targets. The number of render targets supported by a device is contained in the NumSimultaneousRTs member of D3DCAPS9. See Multiple Render Targets (Direct3D 9).

The key word here being *can*. As far as I can tell, availability of render targets are actually tested using [CheckDeviceFormat](https://docs.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3d9-checkdeviceformat).

I checked opengl, opengles, opengles2, and d3d11's CreateRenderer functions and they don't have similar dead code for setting the flags.

**Comment by icculus** [comment]
This is correct; NumSimultaneousRTs appears to be intended to show whether the GPU can handle drawing to multiple color buffers at the same time:

https://docs.microsoft.com/en-us/windows/win32/direct3d9/multiple-render-targets

However:

> The key word here being can. As far as I can tell, availability of render targets are actually tested using CheckDeviceFormat.

I've never seen a direct3d 9 game that checks to make sure render targets _in general_ are available, and fwiw, `NumSimultaneousRTs` says this in its documentation:

https://docs.microsoft.com/en-us/windows/win32/api/d3d9caps/ns-d3d9caps-d3dcaps9

"Number of simultaneous render targets. This number must be at least one."

Which I take to mean that while you may or may not be able to render to multiple color buffers at once, _render targets_ in general are always supported on D3D9-level hardware.

So I think the correct approach is to remove the check and just always report render targets are available in the direct3d renderer.
