### ISSUE TITLE
EGL OpenGL context creation will fail if no-error context is requested but not supported

### ISSUE THREAD

**Issue by MausGames** [libsdl-org/SDL#4783]
In OpenGL, if a no-error context is requested with `SDL_GL_SetAttribute(SDL_GL_CONTEXT_NO_ERROR, 1);` and the backend is EGL, the context creation will fail if the display-extension string `EGL_KHR_create_context_no_error` cannot be found.

This behavior is not present in the WGL and GLX context creation code and could potentially surprise developers.

It makes it much harder to use this feature, as extensive checking for various strings or test-context creation would be necessary.

From the specification (as reference):
https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_create_context_no_error.txt
>   (6) Should creating a context fail if the context created context does not
  support a no error mode?
>
>  RESOLVED: No.  Expect context creation to succeed even if the implementation
  can't honor the request for a no error context. This reduces the number of
  reasons creating a context can fail and seems to be a more forward looking
  resolution considering context flags allow GL apps to query what context
  flags are set.

I think context creation should not be prevented by SDL in this case.

https://github.com/libsdl-org/SDL/blob/b592e78f93b1e698b981ecf5af90e48e52e6387e/src/video/SDL_egl.c#L1013
https://github.com/libsdl-org/SDL/blob/b592e78f93b1e698b981ecf5af90e48e52e6387e/src/video/x11/SDL_x11opengl.c#L772
https://github.com/libsdl-org/SDL/blob/b592e78f93b1e698b981ecf5af90e48e52e6387e/src/video/windows/SDL_windowsopengl.c#L767

**Comment by flibitijibibo** [comment]
Makes sense to me, would you be able to send this patch?

**Comment by MausGames** [comment]
Sure, I'm a bit rusty doing that with GitHub, but I will do my best.

**Comment by slouken** [comment]
It's fine if you just want to attach a patch file, we can apply it here.

Thanks!

**Comment by MausGames** [comment]
Aah, that's even easier, thank you.
```diff --git a/src/video/SDL_egl.c b/src/video/SDL_egl.c
index 0b8635db2..928a1df2f 100644
--- a/src/video/SDL_egl.c
+++ b/src/video/SDL_egl.c
@@ -1010,18 +1010,14 @@ SDL_EGL_CreateContext(_THIS, EGLSurface egl_surface)
         }
     }
 
-    if (_this->gl_config.no_error) {
 #ifdef EGL_KHR_create_context_no_error
+    if (_this->gl_config.no_error) {
         if (SDL_EGL_HasExtension(_this, SDL_EGL_DISPLAY_EXTENSION, "EGL_KHR_create_context_no_error")) {
             attribs[attr++] = EGL_CONTEXT_OPENGL_NO_ERROR_KHR;
             attribs[attr++] = _this->gl_config.no_error;
-        } else
-#endif
-        {
-            SDL_SetError("EGL implementation does not support no_error contexts");
-            return NULL;
         }
     }
+#endif
 
     attribs[attr++] = EGL_NONE;
 ```

**Comment by flibitijibibo** [comment]
Applied, thanks!

https://github.com/libsdl-org/SDL/commit/7c050aa60a14a4cc5f3520f6efc1156fcb4f7643
