### ISSUE TITLE
Borderless window with hit testing does not toggle system cursors in X11.

### ISSUE THREAD

**Issue by graphitemaster** [libsdl-org/SDL#4790]
The behavior for custom hit testing in X11 only works while the left mouse button is held down [1]. Because of this, X11 cannot actually toggle the cursor state for the window when the mouse is hovering over the edges of the custom hit testing rectangle. This makes it pretty hard to know if your cursor is actually in the area to begin resizing or dragging until the left mouse button is held down. One cannot set the cursor in the hit test function either because the function is only ever invoked while the left mouse button is held down.

[1] https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11events.c#L1235

**Comment by slouken** [comment]
@ileonte, is this something you can look at?

**Comment by ileonte** [comment]
> @ileonte, is this something you can look at?

Wow, this is quite the blast from the past, I haven't looked at SDL code since 2015-ish I think.
I can certainly look into it but it may take me a few weeks, depends how much of a rush you are in to have this fixed.

**Comment by slouken** [comment]
A few weeks is fine, thanks!

**Comment by ileonte** [comment]
I've looked into this and the situation is as follows:
* on Windows hit testing is a built-in system behavior (the application is sent [`WM_NCHITTEST`](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest) events and associated states such as setting the mouse cursor, triggering window resize/move, etc., are handled automatically based on what the message handler returns). 
* on pretty much all other platforms this is not something that the underlying system provides, it would need to be emulated in SDL by tracking mouse events and handling state changes from within the library. In particular, this would mean invoking the user-provided hit test function for each mouse (and pen?) movement event.

All of this to say that at the moment SDL simply exposes the underlying platform's behavior when it comes to hit testing.

@slouken do you want SDL to emulate the Windows behavior? If yes then I can probably implement it for X11 and Wayland but I cannot work on other platforms.

**Comment by slouken** [comment]
I think for SDL3 it makes sense to emulate the Windows behavior on other platforms where possible. We can make it more efficient by only running that logic when the hittest callback is set, but I think it's entirely expected that the application would be asked what the current state it whenever the mouse moves. An alternative would be for the application to set hit test regions, but that would be less flexible than the current situation.

Thoughts?

**Comment by ileonte** [comment]
I see no reason not to try emulating the Windows behavior. Note however that I have no experience with platforms other than Linux and (to a much lesser extent) Windows so I'm not sure how relevant my judgement is in this context. If I remember correctly @icculus was also involved in getting this merged in the first place, perhaps he has more insight about this matter.

**Comment by icculus** [comment]
So Windows calls the hit test callback _a lot_. When dragging, even after you've identified the current position in the window as draggable and the drag is literally in progress, it continually checks in, like "are you still sure?!?"

It probably does it for each mouse motion event, but I haven't checked.

Currently the X11 code doesn't do this, afaik, and no one has complained.

**Comment by ileonte** [comment]
I tagged you because I very vaguely remember writing a version of the hit-testing feature way back in the day when the Unreal Engine 4 source code was first released and the editor was very broken on Linux, though I am pretty sure you "adjusted" it quite a lot to get to what's in SDL right now.

> Currently the X11 code doesn't do this, afaik, and no one has complained.

This is what this issue is about - people have noticed that the behavior is different between Windows and the other platforms (in particular, on Windows, the mouse cursor automatically changes to show that dragging on a certain area of the window will perform an action such as resizing). I guess what we're trying to understand is if it makes sense to try and emulate the cursor behavior from Windows on the other platforms.

**Comment by slouken** [comment]
@ileonte, I'd say go for it!

**Comment by icculus** [comment]
>  guess what we're trying to understand is if it makes sense to try and emulate the cursor behavior from Windows on the other platforms.

Ah yes, I should have read more carefully; let's try to emulate that, if you are so inclined.

I need to do some work on hit testing in general on macOS, so I'll fight with that if you want to fight with X11 and/or Wayland!
