### ISSUE TITLE
SDL_snprintf prints zero incorrectly

### ISSUE THREAD

**Issue by Markvy** [libsdl-org/SDL#4795]
printf("%f", 0.0) should be "0.000000" but SDL gives simply "0".
This seems to be because 0 is using special case custom logic, but as far as I can tell, there's no need: the main logic actually handles zero correctly.  (I could have missed something; this is just from a cursory inspection.)

**Comment by Markvy** [comment]
Sorry the whitespace in the diff got messed up; it turns out I was mixing tabs and spaces.
I assume this is not the reason this tiny fix is being ignored?  (If it is, I will post a new diff with spacing fixed.)

**Comment by icculus** [comment]
>  I don't have commit rights

Pull requests are super-helpful because we the UI handles much of the merging work for us, but also because it makes sure the commit is credited to you.

If https://github.com/libsdl-org/SDL/pull/4919 looks okay to you, I'll merge it.

**Comment by slouken** [comment]
I added a test case to cover this and merged your patch.

Thanks!

**Comment by Markvy** [comment]
Thank you!  If you prefer pull requests I'll prepare one for my other sprintf things.
I'll have to get the tabs vs spaces thing fixed then.  Do you have a C style guide I should look at or just try to be reasonable?

**Comment by slouken** [comment]
Just match the style of the rest of the SDL code - no spaces after parentheses, brace on the same line, use spaces instead of tabs, etc.

**Comment by slouken** [comment]
Pull requests are great because GitHub will compile them and make sure that they can merge cleanly. If you can't, no worries, but it does make the integration easier if you create them.

**Comment by Markvy** [comment]
I can; just need to fix my messed up indentation
