### ISSUE TITLE
SDL2Config.cmake does not check for SDL2::SDL2 and does not handle SDL2-static

### ISSUE THREAD

**Issue by jcelerier** [libsdl-org/SDL#4797]
I build SDL with

    -DSDL_STATIC=1 
    -DBUILD_SHARED_LIBS=0

which means that there is no SDL2::SDL2 target exported in `SDL2Targets.cmake`. 

But the SDL2Config.cmake still tries to set stuff on SDL2::SDL2, which is incorrect (and rightfully fails).

This worked in 2.0.14.

**Comment by jcelerier** [comment]
@DanielGibson @slouken this seems to come from here: https://github.com/libsdl-org/SDL/commit/3ea11f9acbb876ab6b3261cff458fe69f4b96934

**Comment by DanielGibson** [comment]
damn, looks like I didn't test the static case, didn't know SDL2::SDL2 isn't available at all then.

does it help if, in SDL2Config.cmake, you add `if(SDL2::SDL2)` (**after** `include("${CMAKE_CURRENT_LIST_DIR}/SDL2Targets.cmake")`) and `endif()` (at the end of the file), so all that added cmake code is only run if `SDL2::SDL2` actually exists?

**Comment by jcelerier** [comment]
> Does it help if, in SDL2Config.cmake, you add if(SDL2::SDL2) (after

the proper CMake check would be 

    if(TARGET SDL2::SDL2)

I can propose a change if you want

**Comment by DomGries** [comment]
Should be fixed by https://github.com/libsdl-org/SDL/commit/407867cf7262a45952d095b9a22af14b22878df9

**Comment by madebr** [comment]
Imho, 407867cf7262a45952d095b9a22af14b22878df9 was a faulty commit.
The `SDL2::SDL2` target is reserved for a shared SDL2 library, and similarly `SDL2::SDL2-static` for a shared libraries.

`SDL2Config.cmake` from https://github.com/libsdl-org/SDL/pull/5727 does not need to do any shenanigans with targets to extract cmake variables for compatibility with the autotools `sdl2-config.cmake`.

**Comment by slouken** [comment]
Okay, feel free to back it out, or whatever is necessary to fix.

**Comment by madebr** [comment]
This issue should not be present anymore after #5727
