### ISSUE TITLE
Upload all builds to releases on GitHub

### ISSUE THREAD

**Issue by AJenbo** [libsdl-org/SDL#4810]
Lately libsdl.org has been down which causes various package managers to fail as they depend on the release files.

VCPKG is one such affected package manager, I'm not sure if they would be able to just use the straight source from GitHub instead.

`SDL2-devel-{VERSION}-mingw.tar.gz` is one of the packages only available from libsdl.org

![image](https://user-images.githubusercontent.com/204594/135864387-45f8b501-b324-4233-83f1-d2d7793e8e93.png)

**Comment by ItsSitanshu** [comment]
Agreed!

**Comment by Dobby233Liu** [comment]
> VCPKG is one such affected package manager, I'm not sure if they would be able to just use the straight source from GitHub instead.

They [literally does that](https://github.com/microsoft/vcpkg/blob/b6b6a8b63007df2ff37167a1974652a8e948f045/ports/sdl2/portfile.cmake#L2)

**Comment by AJenbo** [comment]
> > VCPKG is one such affected package manager, I'm not sure if they would be able to just use the straight source from GitHub instead.
> 
> They [literally does that](https://github.com/microsoft/vcpkg/blob/b6b6a8b63007df2ff37167a1974652a8e948f045/ports/sdl2/portfile.cmake#L2)

Looks like they updated there script about a month ago in conjunction with updating to SDL 2.0.16

But that still leaves out the other SDL packages.
https://github.com/microsoft/vcpkg/blob/master/ports/sdl2-image/portfile.cmake#L4

And the mingw package.

**Comment by kloczek** [comment]
Also as at the moment is almost 300 commits since last release IMO it would be good to make a new release.
As always it is better to make new release more frequently to better observe impact of recent changes.

**Comment by Dobby233Liu** [comment]
> Also as at the moment is almost 300 commits since last release IMO it would be good to make a new release. As always it is better to make new release more frequently to better observe impact of recent changes.

[Probably not yet](https://github.com/libsdl-org/SDL/milestone/2)

**Comment by slouken** [comment]
SDL 2.0.18 has the pre-compiled packages added to the GitHub release.
