### ISSUE TITLE
SDL_atoi() not conformant?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#4811]
`atoi(str)` is supposed to be equivalent to `strtol(str, NULL, 10)`, but
we are doing `strtol(str, NULL, 0)`: is this an oversight or on purpose?

**Comment by slouken** [comment]
No, that's an oversight.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL/commit/3ea35fe5bbbdc8adc9e1183f5fc6b325a48f33ed for it.

**Comment by slouken** [comment]
Thanks!
