### ISSUE TITLE
KMS/DRM backend leaves me stuck with no input, forced to hard-reset machine

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4812]
I compiled https://github.com/libsdl-org/SDL/commit/32f909f7e36a270d3b761bf15d320906ecd31eb1 hoping to be able to test out the KMS/DRM driver. 
[configure-output.txt](https://github.com/libsdl-org/SDL/files/7286321/configure-output.txt)
[config.log.txt](https://github.com/libsdl-org/SDL/files/7286326/config.log.txt)

Then I launched my test program with `SDL_VIDEODRIVER=kmsdrm` on a TTY. While it rendered fine, even with an accelerated SDL_Renderer if desired, none of keyboards and mouse/touchpad worked (it was a laptop with desktop peripherals attached, I tested both external and internal input devices). I was essentially stuck in the application with no way to interact with it or leave, while its animated opening scene rendered fine with no lag. Inside the regular GNOME 3 desktop, I can interact with it just fine.

**Comment by vanfanel** [comment]
@ell1e I get your point, but I don't think modifying the udev rules is a risk.
It's also required for RetroArch to operate directly on KMSDRM with udev input, so every distro you see around RetroArch (such as Lakka, EmuELEC, and a LOOONG etc) must have these permissions set so users can access the udev nodes.
Even LibreELEC (KODI distro) must have this setup for normal user to access the udev nodes.

**Comment by ell1e** [comment]
> I think it should be feasible to implement the safety that you mention. Perhaps if SDL fails to open any input device, we could fail the KMSDRM backend init (with an override like we did with SDL_HINT_KMSDRM_REQUIRE_DRM_MASTER).

I like the idea of a hint, `SDL_HINT_KMSDRM_REQUIRE_INPUT_ACCESS` maybe? Might maybe default to `"1"`, and any non-interactive thing (that is fine with trapping the user without input, like maybe some endless advertisement animation thing or something) could then set it to `"0"`.

**Comment by ell1e** [comment]
Fwiw, my system has both `input` and `video` groups, and my user is in neither. KMSDRM worked on the TTY anyway. Don't ask me why, I'm pretty new to this KMSDRM thing!

**Comment by robertpfeiffer** [comment]
As a casual SDL consumer (i.e. pygame committer), I'd say it's even a pitfall that sometimes with KMSDRM (or Rpi backend) and udev/evdev, there is no way to receive pygame.QUIT events (which are wrapping SDL_QuitEvent). Alt+F4 is just Alt+F4, and there is no window frame with an [x] to click on. This also leaves unsuspecting users forced to hard-reset their machine if they don't have SSH set up!

**Comment by FreeFull** [comment]
Properly solving this would probably require the use of something like seatd, to get access to the input devices in the same way that a Wayland compositor would, without requiring the user to be in the input group.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by ell1e** [comment]
Unless SDL3 implemented a mode where it stops launch when no input is detected with some sort of warning and an SDL2 hint to override that, maybe that would be still worth considering? For SDL3, of course.

**Comment by slouken** [comment]
Sure, I'll throw this in the 3.x milestone.

**Comment by slouken** [comment]
FYI, you can set the environment variable `SDL_INPUT_LINUX_KEEP_KBD=1` to keep console input. You won't get input into the application, but at least you'll be able to Ctrl-C out of it.

**Comment by slouken** [comment]
With the latest change, if we can't open the keyboard device we won't touch the console so you will still be able to hit Ctrl-C to stop your application.

VT switching is not implemented yet, but will be tracked in https://github.com/libsdl-org/SDL/issues/3844.

**Comment by ell1e** [comment]
I'm glad there's a way to get out of the app at all, at least! However, if there's ever time for that at all, I would also prefer a more visible error, e.g. a subsystem initialize failure. For apps that are meant to work without input but aren't written to ignore and suppress this error as needed, I think an SDL hint would be best (which defaults to off, and once enabled will silence this error like it behaves now).

**Comment by slouken** [comment]
We don't require a keyboard and mouse on any other platform, so it seems odd to fail KMSDRM for that. You might have a kiosk application or use a touchscreen or controllers, or have some other use case that may not require a keyboard.

Maybe the distinction here should be "We failed to open the mouse and keyboard"?

**Comment by stsp** [comment]
https://wiki.libsdl.org/SDL2/SDL_INIT_EVENTS
As can be seen, this is undocumented.
I assumed this flag implies mouse and
keyboard. If not - how about documenting
it, and perhaps to add another flags to
require mouse and keyboard?

**Comment by ell1e** [comment]
IMHO having *any working input method at all* seems like a sufficient condition to carry on. After all, you could probably exit most KMS SDL2 apps with just the mouse, and most likely without the input group neither mouse nor keyboard would work, right? So that seems to be covered by such a check.

**Comment by stsp** [comment]
> Maybe the distinction here should be "We failed to open the mouse and keyboard"?

mouse OR keyboard.
Yes, I think this would be a cheapest
short-term solution, so can you do that?
I.e. rather than checking the end results
(what is opened and what is not even
available), just propagate any error
during open.

By the way, I think this will rule out the
case you currently check for. You check
if no kbd is opened, then don't mute kbd.
If you propagate an error, then I suppose
"no kbd" case will mean "really no keyboard
here", so "don't mute" logic won't apply.

Also, can muting be done by a more "polite"
measures? `tcsetattr()` can be used to
disable console echo. This is more portable
and much easier to recover, than your
current ` ioctl(kbd->console_fd, KDSKBMODE, K_OFF);`.
