### ISSUE TITLE
Proper way of picking up multitouch events from a tablet?

### ISSUE THREAD

**Issue by franciscod** [libsdl-org/SDL#4819]
Hello, I've been trying to make SDL on Linux to pick up multitouch (finger) events from a Wacom tablet on a Linux machine.

After experimenting a bit, I came up with the following, which works! (see patch below)
* Init/Quit the evdev subsystem as part of the X11 Video Init/Quit
* Poll evdev events on the X11 event pump
* ~~A silly hardcoded path check for adding the `SDL_UDEV_DEVICE_TOUCHSCREEN` flag, which is used for filtering touch events down the line.~~ I'm now picking up the `FINGER` flag and setting a `TOUCHPAD` device class and then treating every touchpad as if it was a touchscreen.

A few questions:
1) Does the integration between the X11 and evdev stuff make sense?
2) ~~Should I be changing the udev class of my device from outside somehow?~~ (No, it has the `FINGER` flag)
3) Could any of this (probably after putting some more thought and work, for sure) be added into SDL? I'd love to help with it.

I guess that there's the unexpected situation where a touchpad in a laptop surprisingly acts as a multitouch source and that might be confusing... but would be cool to have support for this.

Thanks!

---

```diff
diff --git a/src/core/linux/SDL_evdev.c b/src/core/linux/SDL_evdev.c
index bd4fcf6cd..7558c85de 100644
--- a/src/core/linux/SDL_evdev.c
+++ b/src/core/linux/SDL_evdev.c
@@ -218,6 +218,10 @@ static void SDL_EVDEV_udev_callback(SDL_UDEV_deviceevent udev_event, int udev_cl
 
     switch(udev_event) {
     case SDL_UDEV_DEVICEADDED:
+        if (strstr(dev_path, "event19") != NULL) {
+            udev_class |= SDL_UDEV_DEVICE_TOUCHSCREEN;
+        }
+
         if (!(udev_class & (SDL_UDEV_DEVICE_MOUSE | SDL_UDEV_DEVICE_KEYBOARD |
             SDL_UDEV_DEVICE_TOUCHSCREEN)))
             return;
diff --git a/src/video/x11/SDL_x11events.c b/src/video/x11/SDL_x11events.c
index f91131305..4be5cab3a 100644
--- a/src/video/x11/SDL_x11events.c
+++ b/src/video/x11/SDL_x11events.c
@@ -22,6 +22,10 @@
 
 #if SDL_VIDEO_DRIVER_X11
 
+#ifdef SDL_INPUT_LINUXEV
+#include "../../core/linux/SDL_evdev.h"
+#endif
+
 #include <sys/types.h>
 #include <sys/time.h>
 #include <signal.h>
@@ -1640,6 +1644,10 @@ X11_PumpEvents(_THIS)
             X11_FlashWindow(_this, data->windowlist[i]->window, SDL_FLASH_CANCEL);
         }
     }
+
+#ifdef SDL_INPUT_LINUXEV
+    SDL_EVDEV_Poll();
+#endif
 }
 
 
diff --git a/src/video/x11/SDL_x11video.c b/src/video/x11/SDL_x11video.c
index f1d10410a..61c2c499b 100644
--- a/src/video/x11/SDL_x11video.c
+++ b/src/video/x11/SDL_x11video.c
@@ -22,6 +22,10 @@
 
 #if SDL_VIDEO_DRIVER_X11
 
+#ifdef SDL_INPUT_LINUXEV
+#include "../../core/linux/SDL_evdev.h"
+#endif
+
 #include <unistd.h> /* For getpid() and readlink() */
 
 #include "SDL_video.h"
@@ -453,6 +457,12 @@ X11_VideoInit(_THIS)
 
     X11_InitTouch(_this);
 
+#ifdef SDL_INPUT_LINUXEV    
+    if (SDL_EVDEV_Init() < 0) {
+        return -1;
+    }
+#endif    
+
     return 0;
 }
 
@@ -476,6 +486,10 @@ X11_VideoQuit(_THIS)
     X11_QuitKeyboard(_this);
     X11_QuitMouse(_this);
     X11_QuitTouch(_this);
+
+#ifdef SDL_INPUT_LINUXEV    
+    SDL_EVDEV_Quit();
+#endif    
 }
 
 SDL_bool

```

**Comment by slouken** [comment]
I'm not sure about the X11 portion, but the evdev changes look good to me, and I've added them in https://github.com/libsdl-org/SDL/commit/373216ae5be62b710ad68524777ae38ca712c53d

**Comment by franciscod** [comment]
Seems like the XInput path provides `SDL_FINGERMOTION`events (individual fingers?), but not `SDL_MULTIGESTURE` (compound gestures like pinch zoom / rotate).

**Comment by slouken** [comment]
`SDL_MULTIGESTURE` is always available when finger motion events are delivered. However I seem to remember that evdev and X11 don't return the same coordinate system (one is normalized and the other is not), can you confirm?

**Comment by slouken** [comment]
I just confirmed that X11 returns normalized events and testgesture handles them properly. I also confirmed that SDL_MULTIGESTURE events are generated in this case. You can see this by setting the environment variable SDL_EVENT_LOGGING=1 and watching the debug output.

I'll go ahead and close this, but please let me know if you're seeing something different.

**Comment by franciscod** [comment]
OK! I think I didn't receive events without the evdev init code that I added (but haven't checked again). That environment variable sure looks handy. Thanks!
