### ISSUE TITLE
macOS: Mouse button down/up events on unfocused windows have invalid position values

### ISSUE THREAD

**Issue by DiskPoppy** [libsdl-org/SDL#4828]
When right-clicking/middle-clicking a window that is unfocused causes the "mouse button down"/"mouse button up" structs to have x, y values that correspond to where the mouse was before (if it left a focused window, the x, y coordinates are relative to that window) while reporting windowID to be the unfocused window where the mouse is now, resulting in inconsistency.

I would expect the struct to have the current x, y coordinates. In case it can't be done: either old coordinates (as it is now) but also the id of the old window, to which they are relative; or the coordinates be flagged somehow as invalid.

Moving the mouse while a button is down generates mouse motion events with correct values though.

**Comment by icculus** [comment]
This reproduces for me with `./testsprite2 --windows 2 --info all`, looking further.
