### ISSUE TITLE
SDL1

### ISSUE THREAD

**Issue by Jalanjii** [libsdl-org/SDL#4835]
Hi, I have an old project with SDL1.2 and I want to migrate to SDL2. I read the migration guide and  I got so confused. I will post the code here with marker which lines should be updated as they show in red error in visual studio. They are a total of four errors when working with SDL2. They work with SDL1. All errors are of the form "X is undefined"

```
void AffGrid_open_window(AffGrille * AG) {
	int taille_pixel;
	Uint32 flags = SDL_HWSURFACE | SDL_HWACCEL | SDL_DOUBLEBUF; // this one doesn't work with SDL2

	if (SDL_Init(SDL_INIT_VIDEO) != 0) {
		fprintf(stderr, // this one doesn't work with SDL2
			"Erreur: ne peut pas initialiser le système graphique (\"%s\").\n",
			SDL_GetError());
		return;
	}
	atexit(SDL_Quit);
	const SDL_VideoInfo *info = SDL_GetVideoInfo();// this one doesn't work with SDL2
	taille_pixel = info->current_h / 2;

	if ((taille_pixel * 1.0) / AG->G->n > 1) {
		AG->cas_aff = 0;
		AG->taille_case = taille_pixel / AG->G->n;
	}
	else {
		AG->cas_aff = 1;
		AG->modulo = AG->G->n / taille_pixel;
	}

	SDL_SetVideoMode(AG->taille_case * AG->G->n, AG->taille_case * AG->G->m, 0,
		flags);

	SDL_EnableKeyRepeat(SDL_DEFAULT_REPEAT_INTERVAL / 4,// this one doesn't work with SDL2
		SDL_DEFAULT_REPEAT_DELAY / 12);

	SDL_WM_SetCaption("Sorting Robot", 0);
}
```

I would really appreciate your help.

**Comment by icculus** [comment]
I saw this was posted to our forums, too, so I replied over there. Feel free to reply there with other questions about migration to SDL2!

https://discourse.libsdl.org/t/sdl1-to-sdl2-migration-getting-errors/33034/2
