### ISSUE TITLE
SDL_AllocFormat(SDL_PIXELFORMAT_YUY2)    **Parameter 'format' is invalid**

### ISSUE THREAD

**Issue by AndreaRigoni** [libsdl-org/SDL#4837]
Hi SDL developers, I just tried with git version (master) and..

The call to allocate a new SDL_PixelFormat structure does not accept all formats in SDL_PixelFormatEnum.

` SDL_PixelFormat *fmt = SDL_AllocFormat(SDL_PIXELFORMAT_YUY2); `

returns NULL with error:  **Parameter 'format' is invalid**

**Comment by slouken** [comment]
That's correct, you can't create a software surface with a YUV format. They are only supported as textures in the SDL renderer.

What is your use case?
