### ISSUE TITLE
Request: Add Platform to Output of SDL_GameControllerMapping

### ISSUE THREAD

**Issue by stobb3s** [libsdl-org/SDL#4848]
I am developing a program which has an option to print the current controller mapping to the command line with ```SDL_GameControllerMapping()``` in case the user wants to modify it. So, the user would copy the mapping from the command line, paste into a config text file, modify it as they desire, and then the program would load the modified mapping with ```SDL_GameControllerAddMappingsFromFile()```.

The problem is that the ```SDL_GameControllerMapping()``` output doesn't include the platform at the end. I spent a long time trying and failing to load a modified output from ```SDL_GameControllerMapping()``` by using ```SDL_GameControllerAddMappingsFromFile()```, only to discover it was missing the platform information. So, I had to add "platform:Linux," to the end of the output of ```SDL_GameControllerMapping()```.

I think it would be more intuitive if ```SDL_GameControllerMapping()``` outputs a valid controller mapping that SDL can read, which requires the platform.

**Comment by slouken** [comment]
Makes sense, thanks!
