### ISSUE TITLE
How can I tell SDL to close down or share its DRM drawing context?

### ISSUE THREAD

**Issue by Fredrum** [libsdl-org/SDL#4851]
Hello!
I'm making some progress converting a program to use direct to screen drm rendering.
The program has two different visual 'front ends' a GUI drawn through SDL2 using gles2 with drm render, and a video stream using the ffmpeg version that handles this as well.

Both individual pieces are working on their own and display as expected when running the program from CLI.

But its failing me when I try to combine them. I start with the GUI and when the user hits the 'start' button I do the following to the SDL parts,
- Release the Video context from initial SDL_Init(SDL_INIT_VIDEO)
- Destroy the SDL Renderer.
- Destroy the SDL root Window.
(SDL is still running and doing things like capturing input)

I then have a sleep(3) just for now to make sure I give it time.

After that I start up the video stream.
But it doesn't work and just returns this error,
`drmModeSetPlane failed: Permission denied.`

I'm guessing SDL is still holding on to the drm pipeline somehow but I don't know how I can check this and more importantly, I dont know how to make SDL let go and allow avcodec to take over.

Does anyone have any ideas how I can get around this?

Cheers!

**Comment by Fredrum** [comment]
@slouken 
I haveen't got my RPi running right now and am 'at work' so I can't double check the actual SDL commands Im using to close down contexts and windows. But for SDL_INIT_VIDEO I read in the docs that there was a right way and a wrong way and I'm petty sure I tried the right way. I'll explore the other options too though. Thanks.

@cgutman
Ok that sounds interesting. So with the drm fd could I manually transfer it or free it up?  Or could I just hand it to the other part of my program to use? Drawing to the same drm context?

**Comment by cgutman** [comment]
You definitely don't want to close it since SDL still owns that fd. You can share it as long as you don't invoke any SDL APIs that might attempt change DRM state or render.

You may run into state issues when switching back and forth since the DRM clients may assume things haven't changed out from underneath them, so you will probably need to play with it a bit to get it to do what you want (selectively reinitialize things as required to get the state back to what was expected).

**Comment by Fredrum** [comment]
Right so I think it should be working now. I'm doing:
```
SDL_SysWMinfo WMinfo;
SDL_VERSION(&WMinfo.version);
SDL_GetWindowWMInfo(sdl_window, &WMinfo)
```

And when I run from CLI it reports being 
SDL2 version 2.0.17 and
'Unknown Subsystem'

even when my video driver and rendered is opengles2 and kmsdrm.
So hmm, could it be that I need to build somehow with SDL_PROTOTYPES_ONLY and/or SDL_VIDEO_DRIVER_KMSDRM as I see,
```
#if defined(SDL_VIDEO_DRIVER_KMSDRM)
        struct
        {
            int dev_index;               /**< Device index (ex: the X in /dev/dri/cardX) */
            int drm_fd;                  /**< DRM FD (unavailable on Vulkan windows) */
            struct gbm_device *gbm_dev;  /**< GBM device (unavailable on Vulkan windows) */
        } kmsdrm;
#endif
```

I am getting the kmsdrm rendering though already.
Can this be done without custom build as I'm hoping user will be able to use the default SDL2 that comes with their Distro?
