### ISSUE TITLE
Wayland: Can't enter character name in Jupiter Hell

### ISSUE THREAD

**Issue by ernstp** [libsdl-org/SDL#4857]
If you force SDL_VIDEODRIVER=wayland with the Linux native SDL based game Jupiter Hell (Steam), you can't enter a character name.
Other keyboard input seems to work fine.

Tested with SDL built from master ("Fixed grab handling when focus changes..."), mutter 40.5-1ubuntu2, mesa 21.3.0~rc1, 5.15-rc3.
AMDGPU, Radeon 6800 XT.

**Comment by flibitijibibo** [comment]
This may potentially be an API violation... if they depend on text input being started by default they need to update to support that scenario, since for Wayland we only enable text input on startup when the on-screen keyboard protocol is active. You can verify this by arbitrarily returning false here:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandkeyboard.c#L144

**Comment by flibitijibibo** [comment]
This is at risk of being pushed back to 2.0.20 - @ernstp, can you run the test above to see if this is just HasScreenKeyboard exposing an app assumption?

**Comment by icculus** [comment]
This can bump to 2.0.20, but maybe we need a hint to default to starting the keyboard, for users to force it when apps get this wrong.

**Comment by ernstp** [comment]
The "arbitrarily returning false here" worked, then you can enter character name under wayland.

**Comment by ernstp** [comment]
This game works on Windows and MacOS also so StartTextInput can't be needed on those desktop platforms currently either... ? So this would make wayland quite an odd one out among the desktop platforms.

**Comment by slouken** [comment]
Yes, text input should default on for platforms that don't have virtual keyboards. StartTextInput() is designed to bring up on-screen keyboards for platforms that need it.

**Comment by flibitijibibo** [comment]
Took a look and I have a better way to detect physical keyboards... better to use the wl_seat rather than the protocol support. Should take just a moment!

**Comment by flibitijibibo** [comment]
https://github.com/libsdl-org/SDL/commit/fc998b8ec963101466ee9827423ee29b270d93a2

There is some _slight_ ambiguity in that I wasn't able to get the compositor to give me a seat with no keyboard, but from what the protocol says WL_SEAT_CAPABILITY_KEYBOARD is only set when a _physical_ keyboard is set, and the text input protocol is meant to be a separate thing entirely (afaik).

From the limited testing I could do this now acts more like the other desktops, someone with Plasma Mobile or Phosh can verify this.
