### ISSUE TITLE
[macOS] No FindSDL2.cmake with the SDL2-2.0.16.dmg

### ISSUE THREAD

**Issue by nbriggs** [libsdl-org/SDL#4858]
Observed state: The CMake folks have been distributing a FindSDL.cmake, not sure where it originated, but there's no FindSDL2.cmake in the "normal" place for CMake on macOS (`/Applications/CMake.app/Contents/share/cmake-3.22/Modules/`).  The result is that having installed SDL2-2.0.16.dmg, CMake builds of SDL2 clients (which do `FIND_PACKAGE(SDL2 REQUIRED)`) on macOS fails out of the box.

It would be great if the right people could coordinate and release whatever is needed to whomever needs it so that this just works.

**Comment by icculus** [comment]
Bumping this to 2.0.20 because I'm not sure _who_ to talk to about this (the Kitware folks...?) and this likely will take more time than we have for 2.0.18.

**Comment by nbriggs** [comment]
I poked around a bit and I think they maintain on GitLab (gitlab.kitware.com) and you do the regular "submit a merge request" to have them merge the `FindSDL2.cmake` that you'd need to come up with, which is probably pretty similar to the `FindSDL.cmake` that they already distribute.  I'd do it myself, but I have no connection to either project and I'm overbooked on this sort of stuff.

**Comment by glebm** [comment]
`FindSDL2.cmake` shouldn't be needed for SDL2 because SDL2 already provides an `sdl2-config.cmake`, so `find_package(SDL2 REQUIRED)` should just work.

If it doesn't, that's an issue with the SDL2 installation, not CMake.

**Comment by nbriggs** [comment]
I've installed SDL2 v2.0.18 on my mac -- the framework does not contain an SDL2Config.cmake (or any other .cmake) file.  I've attached the file list.  Using find_package(SDL2 REQUIRED) results in

```
% cmake ..                      
CMake Error at CMakeLists.txt:79 (FIND_PACKAGE):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.
```

[files.txt](https://github.com/libsdl-org/SDL/files/7698293/files.txt)

**Comment by glebm** [comment]
@nbriggs Yeah I've just looked at the contents of the `.dmg` file and it's missing `SDL2Config.cmake`, that's a bug

**Comment by nbriggs** [comment]
@glebm -- is there a workaround for this?  The regular `SDL2Config.cmake` that's part of the source release doesn't appear to have the right stuff to just be dropped into `/Library/Frameworks/SDL2.framework/`.

**Comment by glebm** [comment]
A workaround would be to use the Homebrew version of SDL2 or build it from source in the project via FetchContent ([example](https://github.com/diasurgical/devilutionX/blob/master/3rdParty/SDL2/CMakeLists.txt)).

**Comment by icculus** [comment]
Bumping to 2.0.24, where I'll talk to Kitware about the right way to manage CMake issues.

**Comment by madebr** [comment]
If everything goes right, all development archives provided on libsdl.org will contain cmake scripts.

@slouken
Don't forget to update your release scripts.
If possible, also run the cmake test script (in the `cmake/test` folder) on the MSVC/MinGW/Xcode archives.
This can be automated.
