### ISSUE TITLE
Xbox One Trigger Impulse via the Widnows Runtime API

### ISSUE THREAD

**Issue by Ybalrid** [libsdl-org/SDL#4859]
Hello 👋

I have been playing a bit with the SDL_GameController* APIs and I was a bit surprised by the current support for Xbox One controllers.

Besides the fact that I am hitting the issue described in #4435 (SDL_GameControllerRumble does *nothing* on MSVC/Windows 64bit for me, unless I call `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");`), It seems that there would be a way to implement a missing feature of the Xbox One controllers in SDL2

These controllers have 4 rumblers inside of them: 2 main ones (a high freq and a low freq on the left/right holder parts) and two additional ones inside the triggers.

The main rumblers are available to windows applications via the XInput API, but not the trigger ones. They seem to only be part of the WinRT library here : https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepadvibration?view=winrt-22000

The functionality here should be able to map nicely to `SDL_GameControllerRumbleTriggers()`, but I'm not really familiar with that set of APIs from Microsoft, and I'm afraid that it wouldn't be available to Win32 applications, but that sounds absurd!

There are a few PC games that support these trigger rumbles, but they seem to all come from the Windows Store or Xbox Game Pass, so I have no working example of non-UWP applications having access to that feature...

**Comment by Ybalrid** [comment]
@AntTheAlchemist I was running the stable "official" build. I will try with a source build of the main branch of this repo 🤔

**Comment by Ybalrid** [comment]
Default (CMake) build options on the *main* branch, I have the same behavior with the Xbox One controller. 

(Windows 11, and it's a "launch" Xbox One controller, wireless via the special dongle, or wired. No Bluetooth)

Testing the SLN in the "VisualC" folder now...

**Comment by Ybalrid** [comment]
Okay, this is really interesting

Same sourcecode, the solution dll file built by the solution in the folder *has* working Trigger Rumble, if you use CMake instead, it doesn't.

Need to look into the options set in CMake by default, see if anything weird is going on

**Comment by Ybalrid** [comment]
A config variable is not set when building with CMake, opened a Pull Request!

**Comment by Ybalrid** [comment]
Actually, this seems to only work on wired mode, so it's not *everything* about what is going on here, but that's already something

**Comment by AntTheAlchemist** [comment]
I should add that I am using a 32-bit DLL built with Visual Studio 2019. I'm using an ordinary Bluetooth 5.0 dongle. Triggers still work on my Xbox One S on Windows 10. Keep in mind that you have to move and axis or press a button first. This seems to free something up and allow the rumble to function.
