### ISSUE TITLE
wayland-scanner when cross compiling

### ISSUE THREAD

**Issue by jwinarske** [libsdl-org/SDL#4860]
The currnet method of finding wayland-scanner uses package config.  That's fine when only building for host.  When cross compiling it attempts to find and use the targets version of wayland-scanner.  That's bad as the build attempts to run it on host.  In all cases you want to use host version of wayland-scanner.

**Comment by Mindavi** [comment]
I'm running into the same issue on SDL 2.20, but then for autotools. It goes wrong on this line: https://github.com/libsdl-org/SDL/blob/fa505970550346b613f31894095ffb8c2eedafa0/configure#L20602
