### ISSUE TITLE
optional SDL ALSA Hotplug Thread

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#4862]
i'd pretty much prefer if the hotplug thread was optional and could be disabled at compile time, for the following reasons:

- it's pretty much useless for 99.9% of users. who plugs in an additional audio device during execution of an SDL program (most of the time a game)?
- every additional thread makes debugging more complicated - an additional resource that has to be checked whenever an issue arises
- the actual code of alsa-lib that's called is pretty fragile, and does tons of memory allocations and config file parsing, over and over. for example it just crashed in calloc for me overwriting heap when there were no more available X windows (once you have like 200 X clients open, no new windows can be allocated). not only is it fragile, it's also resource-hungry.

**Comment by icculus** [comment]
Ok, this is in revision control; just toggle the SDL_ALSA_HOTPLUG_THREAD define to zero at the top of SDL/src/audio/alsa/SDL_alsa_audio.c. Let me know if this doesn't cover your needs!

**Comment by rofl0r** [comment]
thanks, that's really great news. this thread has been getting into my way over and over (e.g. set a breakpoint to find callers of SDL_Delay to identify where your audio or FPS is getting messed up, and you'll constantly end up in that thread's code, or have a double free somewhere and getting the crash in alsa code as it does like a gazillion of malloc calls while parsing a 20 line config file, etc etc...)

will test it asap and report back.

**Comment by rofl0r** [comment]
works like a charm <3
