### ISSUE TITLE
Add SDL_GetTicks64()

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4870]
It's silly that we have documentation and warnings about how SDL_GetTicks() overflows every 49 days, when most platforms offer a 64-bit timer that will overflow sometime after the sun burns out.

Most of our existing platform-specific code is already working from a 64-bit timer, too, which we clamp down to 32-bits:

- Unix uses `clock_gettime()` or `gettimeofday()`, both of which can produce 64-bit ticks, since it supplies seconds and nanoseconds/microseconds in separate fields that are >= 32 bits each.
- macOS and iOS can use the Unix codepath _or_ `mach_absolute_time()`, which is similar to gettimeofday
- PSP uses `gettimeofday()`
- Vita uses `sceKernelGetProcessTimeWide()`, a 64-bit process uptime counter.
- Haiku uses `system_time()`, which provides 64-bit system uptime in microseconds.
- OS/2 uses `DosTmrQueryFreq()`, which is a 64-bit uptime counter that increments at 1.19318Hz (the Intel 8254 timer, basically).
- Windows uses `QueryPerformanceCounter()`, which is 64-bit, unless it fails at startup, in which case it uses (32-bit!) `timeGetTime()`. WinRT only uses `QueryPerformanceCounter()`. [QPC can only fail at startup if you are on a pre-WinXP install](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter#return-value), which is to say it never fails on platforms SDL2 still supports. We should probably remove the timeGetTime() fallback in any case, honestly.

I propose we remove the 32-bit limit, which is mostly removing the Uint32 casts from existing code, expose it as SDL_GetTicks64(), and move SDL_GetTicks() to a platform-independent wrapper in SDL_timer.c that just returns `SDL_GetTicks64() & 0xFFFFFFFF`.

**Comment by slouken** [comment]
Can we do something smart with SDL_TICKS_PASSED() so it doesn't silently do the wrong thing if you pass the 64-bit ticks value?
