### ISSUE TITLE
[CMake] aclocal install set to absolute

### ISSUE THREAD

**Issue by jwinarske** [libsdl-org/SDL#4875]
Using CMAKE_STAGING_PREFIX is used to stage the installation location.

The current install path for aclocal is set for absolute:   https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L2804

For install path options using GNUInstallDirs there are two options:
```
CMAKE_INSTALL_<dir>      - destination for files of a given type
CMAKE_INSTALL_FULL_<dir> - corresponding absolute path
```

Changing it to use CMAKE_INSTALL_<dir> is preferred as this allows the use of CMAKE_STAGING_PREFIX.

https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
https://cmake.org/cmake/help/v3.0/variable/CMAKE_STAGING_PREFIX.html?highlight=cmake_staging_prefix

**Comment by icculus** [comment]
Closing because we already merged this PR.
