### ISSUE TITLE
mouse wheel events only registered from the second step on

### ISSUE THREAD

**Issue by fabiangreffrath** [libsdl-org/SDL#4888]
Hi there,

I am facing an issue that mouse wheel events are only registered once I moved the wheel at least two steps into the same direction. That is, a sequence of mwup/mwdn doesn't register an event - a sequence of mwup/mwdn/mwdn does register a single mwdn event and so on. 

This happens with SDL 2.0.16 on both Windows and Linux.

A minimal example is attached below. Put your pointer in the window and see what happens when you move the mouse wheel.

```C
#include <stdio.h>

#include <SDL.h>

int main (void)
{
	int quit = 0;
	SDL_Event event;

	if(SDL_Init(SDL_INIT_VIDEO) < 0)
		return 1;

	SDL_Window* window = SDL_CreateWindow("Mouse Events", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, 0);
	SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, 0);

	while (!quit)
	{
		while (SDL_PollEvent(&event))
		{
			fprintf(stderr, "type %d\n", event.type);

			if (event.type == SDL_KEYDOWN)
				quit = 1;
		}

		SDL_RenderClear(renderer);
		SDL_RenderPresent(renderer);
	}

	return 0;
}
```

**Comment by AntTheAlchemist** [comment]
It's working for me on Windows 10, SDL 2.0.17 (latest source build) on my physical mouse. But then today I noticed that a laptop touchpad was generating scroll wheel events with no x or y direction similar to what you're describing. I was testing the same application while using chrome desktop on a Cloud Ready laptop. Not sure if this helps.

**Comment by cgutman** [comment]
I believe this is just the current limitation of SDL scroll events being unable to convey fractional ticks.

**Comment by slouken** [comment]
Added fractional ticks to the mousewheel events for 2.0.18.

Thanks!
