### ISSUE TITLE
Restoring maximized window removes maximize flag on window

### ISSUE THREAD

**Issue by graphitemaster** [libsdl-org/SDL#4889]
If you minimize an already maximized window, then restore the window either with `SDL_RestoreWindow`, or via the operating system, SDL removes the `SDL_WINDOW_MAXIMIZED` flag from the window permanently [1] making `SDL_GetWindowFlags()` produce invalid state for the given window. We currently use `SDL_GetWindowFlags()` to check for maximize state because of bug <https://github.com/libsdl-org/SDL/issues/4816>. There doesn't appear to be a way to check if a window is actually maximized in SDL at all as both methods which expose that information are broken.

[1] <https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_windowevents.c#L146>

**Comment by icculus** [comment]
What platform is this happening on (and if it's with the X11 backend: what window manager?).

Does this test program reproduce it? (Launch it, press 'm' to minimize, restore from the task bar).

```c
#include "SDL.h"

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window *win = SDL_CreateWindow("Hello SDL",
                               SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                               640, 480, SDL_WINDOW_RESIZABLE | SDL_WINDOW_MAXIMIZED);
    SDL_Renderer *renderer = SDL_CreateRenderer(win, -1, 0);
    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);

    Uint32 flags = 0;

    SDL_bool quit = SDL_FALSE;
    while (!quit) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if ((e.type == SDL_KEYDOWN) && (e.key.keysym.sym == SDLK_ESCAPE)) {
                quit = SDL_TRUE;
            } else if ((e.type == SDL_KEYDOWN) && (e.key.keysym.sym == SDLK_m)) {
                SDL_MinimizeWindow(win);
            } else if (e.type == SDL_QUIT) {
                quit = SDL_TRUE;
            }
        }

        const Uint32 f = SDL_GetWindowFlags(win);
        if (f != flags) {
            printf("Flags changed! Now");
            #define FL(x) if (f & x) { printf(" %s", #x); }
            FL(SDL_WINDOW_FULLSCREEN);
            FL(SDL_WINDOW_OPENGL);
            FL(SDL_WINDOW_SHOWN);
            FL(SDL_WINDOW_HIDDEN);
            FL(SDL_WINDOW_BORDERLESS);
            FL(SDL_WINDOW_RESIZABLE);
            FL(SDL_WINDOW_MINIMIZED);
            FL(SDL_WINDOW_MAXIMIZED);
            FL(SDL_WINDOW_MOUSE_GRABBED);
            FL(SDL_WINDOW_INPUT_FOCUS);
            FL(SDL_WINDOW_MOUSE_FOCUS);
            FL(SDL_WINDOW_FULLSCREEN_DESKTOP);
            FL(SDL_WINDOW_FOREIGN);
            FL(SDL_WINDOW_ALLOW_HIGHDPI);
            FL(SDL_WINDOW_MOUSE_CAPTURE);
            FL(SDL_WINDOW_ALWAYS_ON_TOP);
            FL(SDL_WINDOW_SKIP_TASKBAR);
            FL(SDL_WINDOW_UTILITY);
            FL(SDL_WINDOW_TOOLTIP);
            FL(SDL_WINDOW_POPUP_MENU);
            FL(SDL_WINDOW_KEYBOARD_GRABBED);
            FL(SDL_WINDOW_VULKAN);
            FL(SDL_WINDOW_METAL);
            printf("\n");
            flags = f;
        }

        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
    }
    
    SDL_Quit();
    return 0;
}
```

**Comment by graphitemaster** [comment]
The output of that program while running it is. I don't have a task bar though. I'm restoring it with alt+tab. The window manager is OpenBox
```
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_SHOWN SDL_WINDOW_RESIZABLE SDL_WINDOW_MAXIMIZED SDL_WINDOW_INPUT_FOCUS
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_HIDDEN SDL_WINDOW_RESIZABLE SDL_WINDOW_MINIMIZED
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_SHOWN SDL_WINDOW_RESIZABLE SDL_WINDOW_INPUT_FOCUS
```

**Comment by icculus** [comment]
Hmm, I'm having the opposite problem on IceWM (which I don't recommend as desktop environment, except to illustrate this specific point)...once a window has the maximize flag, it never goes away.

I assume we're getting these flags from properties the window manager sets, and some window managers are not resetting them correctly, even if the window is otherwise functioning as expected.

I need to dig in deeper.

**Comment by icculus** [comment]
Testing this on Gnome, Ubuntu 21.10...

```
icculus@lucha:~$ ./testmaximize 
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_SHOWN SDL_WINDOW_RESIZABLE SDL_WINDOW_MAXIMIZED SDL_WINDOW_INPUT_FOCUS SDL_WINDOW_MOUSE_FOCUS
[ ... I press 'm' to minimize ...]
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_HIDDEN SDL_WINDOW_RESIZABLE SDL_WINDOW_MINIMIZED SDL_WINDOW_MOUSE_FOCUS
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_HIDDEN SDL_WINDOW_RESIZABLE SDL_WINDOW_MAXIMIZED
[ ... I click the app on the Dock to restore ... ]
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_SHOWN SDL_WINDOW_RESIZABLE SDL_WINDOW_INPUT_FOCUS
Flags changed! Now SDL_WINDOW_OPENGL SDL_WINDOW_SHOWN SDL_WINDOW_RESIZABLE SDL_WINDOW_MAXIMIZED SDL_WINDOW_INPUT_FOCUS

```

So it's going MINIMIZED for a brief moment on Gnome, but then going right back to being marked as MAXIMIZED, so this is either an SDL bug or a Gnome bug, at a minimum.

This is a mess, we should probably bump this to 2.0.24.

**Comment by icculus** [comment]
This continues to be a mess, so what we decided is we would try to see if we could get consistent behavior on Gnome and KDE and wash our hands of everything else, but we're out of time for this milestone so I'm bumping it for now.

(I'm still not confident we can get this to a usable state on x11 in any timeframe, but I'll explore this again for 2.26)

**Comment by icculus** [comment]
> So it's going MINIMIZED for a brief moment on Gnome, but then going right back to being marked as MAXIMIZED, so this is either an SDL bug or a Gnome bug, at a minimum.

That was Ubuntu 21.10, on 22.04 it doesn't ever lose the MAXIMIZED flag, and never gets the MINIMIZED flag.  :/

This is probably going to bump out of 2.26.0 at this point.

**Comment by icculus** [comment]
We're rethinking some desktop API details for SDL3, so I'm bumping this to that milestone.
