### ISSUE TITLE
SDL_GetModState doesn't work properly on windows 10

### ISSUE THREAD

**Issue by zebulgroz** [libsdl-org/SDL#4893]
hi,
SDL_GetModState give bad value when the numlock key on numeric pad is on.
It's ok when the num lock is off.
I attach a piece of code below to demonstrate that problem :

#include <SDL2/SDL.h>

#include <stdio.h>

int main(int argc, char **argv){
	
   SDL_Surface *surface = NULL;
   SDL_Renderer *renderer;
   SDL_Event event; 
   SDL_Window * window ;
   uint8_t quit=0;
   
  SDL_Rect rect;
  SDL_Init(SDL_INIT_VIDEO);
 
  window = SDL_CreateWindow("LSHIFT", 100, 100, 640, 480, SDL_WINDOW_SHOWN);
  renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED); 
  SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
  SDL_RenderClear(renderer);
  SDL_RenderPresent(renderer);
  while (!quit) {
       	SDL_PollEvent(&event); 
	switch(event.type) 
        {			
	    case SDL_QUIT:{
		    break;
	    }
	    case SDL_WINDOWEVENT:{
		    switch (event.window.event)  {
		    case SDL_WINDOWEVENT_CLOSE:  {
			    quit=1;
		    }
		    }//switch event.window.event
		    break;
	    }//switch SDL_WINDOWEVENT 
            case SDL_KEYDOWN: 
	    {
	         if (event.key.keysym.sym==SDLK_KP_PERIOD)
	         {
		    int k = SDL_GetModState();		
		    printf("key %i %i \n" , k & KMOD_LSHIFT , k & KMOD_NUM);
	         }			
	    }	
        }//switch event type
    }//!quit

    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    free(window);
    SDL_Quit();
 
    return 0;
}//main

the printf result will be : 
0 4096 when left shift is down and num lock on instead of 1 4096
1 0 when num lock is off as expected
Same problem occurs with RSHIFT key.
(Pressing 'del' key on numeric  pad seems to send a KEYUP message to SDL event loop.)  
Thank for your help

**Comment by slouken** [comment]
I'm not sure why, but Windows is actually generating a key-up message for the shift key in this situation:
```
INFO: SDL EVENT: SDL_KEYDOWN (timestamp=24106 windowid=1 state=pressed repeat=true scancode=225 keycode=1073742049 mod=4097)
Received windows message: 11409e WM_KEYDOWN -- 0x10, 0x402A0001
INFO: SDL EVENT: SDL_KEYDOWN (timestamp=24137 windowid=1 state=pressed repeat=true scancode=225 keycode=1073742049 mod=4097)
Received windows message: 11409e WM_KEYDOWN -- 0x10, 0x402A0001
INFO: SDL EVENT: SDL_KEYDOWN (timestamp=24168 windowid=1 state=pressed repeat=true scancode=225 keycode=1073742049 mod=4097)
Received windows message: 11409e WM_KEYUP -- 0x10, 0xC02A0001
INFO: SDL EVENT: SDL_KEYUP (timestamp=24200 windowid=1 state=released repeat=false scancode=225 keycode=1073742049 mod=4096)
Received windows message: 11409e WM_KEYDOWN -- 0x2E, 0x530001
INFO: SDL EVENT: SDL_KEYDOWN (timestamp=24200 windowid=1 state=pressed repeat=false scancode=99 keycode=1073741923 mod=4096)
INFO: key 0 4096 
```
We're accurately reflecting what Windows is doing here.
