### ISSUE TITLE
testgamecontroller won't run: ERROR: Couldn't create texture: Blit combination not supported

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4902]
First time I've tried to compile and run a SDL test. Not sure what could cause this. Seems 2 of the textures load ok, the other two generate this error. I've compiled it using VS2019 and copied the .bmp files from "test" and run it from a command prompt from "VisualC\Win32\Release" - didn't know how else to run it - I've never touched cmake.

**Comment by AntTheAlchemist** [comment]
It seems to have been caused by me adding SDL_LEAN_AND_MEAN. So the test apps require software renderer? Is that right?

**Comment by slouken** [comment]
Yes, the tests run with full SDL functionality. SDL_LEAN_AND_MEAN cuts out lots of things that they may need.
