### ISSUE TITLE
Feature request: disabling all hardware acceleration backends (--disable-video-opengl etc) on Windows results in no video output, a GDI backend would be nice

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4926]
With https://github.com/libsdl-org/SDL/commit/94c1276a5ff347eb9ce3ae7778f1192db2790027 I attempted to make a build that does just plain software video output, using configure with `--enable-video-opengl --disable-video-opengles --disable-video-vulkan --disable-render-d3d`. The idea was that I wanted to try to build for Windows XP without requiring special Direct3D 9 shader dlls, and without relying on Windows XP's on many installs kind of broken OpenGL backend. After all, SDL2's SDL_Renderer is supposed to have a software backend.

However, this is what these build options gave me as available video drivers as a result:
```
Video drivers   : dummy
```
What I really hoped for would be something like `--enable-video-gdi`/a resulting backend list similar to this:
```
Video drivers   : dummy wingdi
```
(or `winddraw` or something?)

It would be very cool if something like that were possible. Even on modern machines it might be interesting to have a build without 3d acceleration backends. (E.g. to be able to guarantee even stubborn apps using that SDL2 build will for sure render in software if it is in any way supported, which might be useful for testing purposes, or to avoid driver bugs.) Rright now there seemingly isn't any obvious way to do that with the existing configure options.

**Comment by ell1e** [comment]
A few files from the `./configure` run of that build:
[config.log](https://github.com/libsdl-org/SDL/files/7497123/RFS2-2021-11-08-1-Windows-x86-SDL2-config.log.txt)
[config.status](https://github.com/libsdl-org/SDL/files/7497128/RFS2-2021-11-08-1-Windows-x86-SDL2-config.status.txt)
[SDL_config.h](https://github.com/libsdl-org/SDL/files/7497125/RFS2-2021-11-08-1-Windows-x86-SDL2-SDL_config.h.txt)

**Comment by sulix** [comment]
I've used SDL2's software renderer on Windows XP recently, and it worked fine in a VM with no hardware accelerated graphics. There's no need to build SDL without the D3D or OpenGL backends available — the DLLs they use are only loaded when used.

Feel free to just grab the SDL builds from https://libsdl.org/ and set [SDL_RENDER_DRIVER](https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER)=``software`` as an environment variable, which will force the use of the software renderer. 

On Windows, the SDL2 software renderer (and the [SDL_GetWindowSurface()](https://wiki.libsdl.org/SDL_GetWindowSurface) function) will fallback to GDI if nothing better is available. You can force it to always use GDI with the [SDL_FRAMEBUFFER_ACCELERATION](https://wiki.libsdl.org/SDL_HINT_FRAMEBUFFER_ACCELERATION) hint. You can see the GDI-based implementation here:
https://github.com/libsdl-org/SDL/blob/main/src/video/windows/SDL_windowsframebuffer.c

**Comment by ell1e** [comment]
> the DLLs they use are only loaded when used.
Ah, that's actually really cool, I didn't know that.

The build options are still seemingly broken, though. If there is a GDI renderer, why would it be disabled with above options set? There does seem to be something fishy going on with the `configure` here.

**Comment by slime73** [comment]
I believe the SDL_Render software backend is platform-agnostic, it doesn't depend on the windowing/OS backend.

"video driver" in SDL is a bit misleading, it's just referring to windowing backends (win32 versus x11 etc).

**Comment by sulix** [comment]
I confess I haven't tried to build SDL myself for windows for a while, so there could still be build issues, but it's worth noting that the GDI code is not a separately-configurable renderer. It's just a part of the normal windows backend for SDL, so it won't show up as its own option in ``./configure`` (it's always enabled), nor is it listed as an ``SDL_Renderer`` — just use ``software``, which will use whatever the current platform has available.
