### ISSUE TITLE
Win10 direct3d & SDL_HINT_RENDER_BATCHING, "0" breaks the renderer

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4933]
A recent change to the current source has caused this bug. I don't seem to be getting any resize events when the window is resized by dragging the window to resize or with calls to SDL_SetWindowFullscreen() to restore from full screen. Only happens if batching is turned off. I'm using the default renderer (-1).

**Comment by slouken** [comment]
What platform are you running on, and what renderer are you getting?

**Comment by AntTheAlchemist** [comment]
Windows 10 and the default renderer is direct3d. This doesn't happen on the opengl renderers.

Looking deeper. I am getting windows events but it seems the renderer is breaking and giving a Present(): INVALIDCALL error. The window doesn't get updated once you've tried to resized, or other things like restoring from full screen.

**Comment by slouken** [comment]
Do you have repro steps with the SDL test programs, or a standalone test case?

**Comment by slouken** [comment]
I ran testsprite2 with --resizable --renderer direct3d, and confirmed that batching was off (which it is by default if you specify a renderer) and resized the window with no issues... ?

**Comment by slouken** [comment]
Are you using render targets? They need to be recreated in response to the SDL_RENDER_TARGETS_RESET event.

**Comment by AntTheAlchemist** [comment]
I'm not using render targets.

It's happening in my game controller diagnostics app which is fairly large. Let me set up a simple test case to see if I can reproduce it - stand by :-)

**Comment by slouken** [comment]
I'm also happy to try to repro with your app, if you want.

**Comment by AntTheAlchemist** [comment]
Just to note that the problem doesn't happen with the direct3d11 renderer either. Only the direct3d renderer seems affected.

My app's source isn't accessible online anywhere, so it's easier if I knock something up, which will help identify if it's something else that's sparking the problem. Nearly there, bare with...

**Comment by AntTheAlchemist** [comment]
@slouken I think I found found the trigger. SDL_SetHint(SDL_HINT_WINDOWS_USE_D3D9EX, "1"). You should be able to recreate the error with this example when resizing the window. You'll notice the title will display the error.

#include <SDL.h>
int main(int argc, char** argv) {
	SDL_SetHint(SDL_HINT_RENDER_BATCHING, "0");
	SDL_SetHint(SDL_HINT_WINDOWS_USE_D3D9EX, "1");
	SDL_Init(SDL_INIT_VIDEO);
	SDL_Window *w = SDL_CreateWindow("Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 500, 500, SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
	SDL_Renderer* r = SDL_CreateRenderer(w, -1, SDL_RENDERER_PRESENTVSYNC);
	bool running = true;
	SDL_FRect box = { 20, 20, 460, 460 };
	Uint8 colour = 0;
	while(running) {
		SDL_PumpEvents();
		SDL_Event event;
		while (SDL_PeepEvents(&event, 1, SDL_GETEVENT, 0, SDL_LASTEVENT) == 1) {
			switch (event.type) {
			case SDL_QUIT:
				running = SDL_FALSE;
				break;
			}
		}
		SDL_SetRenderDrawColor(r, 0x00, 0x00, 0x00, 0xFF);
		SDL_RenderClear(r);
		SDL_SetRenderDrawColor(r, colour++, 0xFF, 0xFF, 0xFF);
		SDL_RenderFillRectF(r, &box);
		SDL_RenderPresent(r);
		if (SDL_GetError()) {
			SDL_SetWindowTitle(w, SDL_GetError());
			SDL_ClearError();
		}
	}
	SDL_DestroyRenderer(r);
	SDL_DestroyWindow(w);
	SDL_Quit();
	return 0;
}

**Comment by slouken** [comment]
Hah, I found it. It's a one line fix.

Thanks for the good repro!
