### ISSUE TITLE
SDL requires libXi 1.7.4, hangs with older versions

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#4938]
In https://github.com/libsdl-org/SDL/issues/3978, @rofl0r said:
> fyi the commit fixing this issue [https://github.com/libsdl-org/SDL/commit/531d83bf6a140fcb5a858c9f23c76198016db869]  causes SDL2 to hang after update to 2.0.16 for everybody not using bleeding edge libxi. it took me about an hour to bisect the hang to this issue, and it seem i'm not alone - see references above. additionally the SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH define can't be toggled on or off via a ./configure flag.

Also see: https://github.com/ValveSoftware/steam-for-linux/issues/7874

@1bsyl said:
> @rofl0r thanks for the info!
> There is a function "query_xinput2_version()" in "src/video/x11/SDL_x11xinput2.c"
> Maybe we can add a variable "xinput2_grabtouch_supported" (similar to "xinput2_multitouch_supported")
> And activate the feature or not, based on the xinput2 version ?

We should figure out how to prevent the hang with older libXi, if possible.

**Comment by rofl0r** [comment]
ftr, this is fixed in libxi 1.7.10 released on 2019-06-19, so "bleeding-edge" might have been a bit exaggerated. otoh, it's not unusual in LTS distros (and especially RHEL/centos...) to use packages older than that.

**Comment by 1bsyl** [comment]
Just tried, and query_xinput2_version() is calling XIQueryVersion ( https://www.x.org/archive/X11R7.5/doc/man/man3/XIQueryVersion.3.html )
returns major:2 minor:2 on my system 
when, libXi is actually:
ii  libxi6:i386                                2:1.7.10-1build2                             i386         X11 Input extension library
So it may not be really helpful here.

There is also:
XGetExtensionVersion (https://www.unix.com/man-page/hpux/3/XGETEXTENSIONVERSION/ )
but it's said that it shouldn't be used.
Anyway, it returns 2.3 on my system (for extensions TOUCHPAD and TOUCHSCREEN)

it would be interesting what those version are on a broken system

**Comment by rofl0r** [comment]
@1bsyl can you paste your complete test programs pls. i dont know how to get the required `Display*`. 

or you can try yourself using the qemu image here http://ftp.barfooze.de/pub/sabotage/sabotage-1.1.24-x86_64-desktop-1f74666.img.xz user root, pass sabotage, then make a regular user and run startx.

**Comment by 1bsyl** [comment]
Here's a sample to get the versions:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/extensions/XInput.h>
#include <X11/extensions/XInput2.h>
 
int main(int argc, char **argv)
{
    Display *display;
    int major = 2; 
    int minor = 2;
    
    display = XOpenDisplay("");
    if (display == NULL) {
        printf("error display null\n");
        return 0;
    }

    XIQueryVersion(display, &major, &minor);
    printf("major:%d, minor:%d\n", major, minor);

    {
        XExtensionVersion *v = XGetExtensionVersion(display, "TOUCHPAD");
        printf("TOUCHPAD present:%d major:%d minor:%d\n", v->present, v->major_version, v->minor_version);

    }
    {
        XExtensionVersion *v = XGetExtensionVersion(display, "TOUCHSCREEN");
        printf("TOUCHSCREEN present:%d major:%d minor:%d\n", v->present, v->major_version, v->minor_version);
    }
    return 0;
}
```

Compile with:
```
gcc helloworld_x11.c -lX11 -lXi
```

Outputs:
```
major:2, minor:2
TOUCHPAD present:1 major:2 minor:3
TOUCHSCREEN present:1 major:2 minor:3
```

**Comment by icculus** [comment]
This is almost certainly the fix in libXi:

https://github.com/freedesktop/xorg-libXi/commit/60ef7bab67aca3dd7c83e8726feb3c46869a74c2

It's one of three code changes between 1.7.9 and 1.7.10.

**Comment by rofl0r** [comment]
> Here's a sample to get the versions:

thanks. the output i get in the above system image, which uses libXi 1.7.2, is identical to what you pasted.

> It's one of three code changes between 1.7.9 and 1.7.10.

sorry for not making that more clear: i was using 1.7.2 before 1.7.10. i now bisected xi releases between and in fact it's 1.7.4 that fixed the bug. since that one came out in 2014 i suppose this issue can be safely disregarded.

**Comment by 1bsyl** [comment]
If 1.7.4 fixed the bug, that's this (only) one.
https://github.com/freedesktop/xorg-libXi/commit/b731d1357d993663ee6b28d6627bdeba69b60dd2

btw, nothing seems in the revision history seems to indicate a version change that would appears through the software.
so query the version may be not possible.

**Comment by smcv** [comment]
> in fact it's 1.7.4 that fixed the bug. since that one came out in 2014 i suppose this issue can be safely disregarded

Steam games should be avoiding this by having a copy of libXi 1.7.4 in the Steam Runtime (<https://github.com/ValveSoftware/steam-for-linux/issues/7874>) - although if the runtime infrastructure can't tell whether the host or runtime libXi is newer, it prefers the host version, so very old host OSs like Debian 7 and Ubuntu 14.04 (which are both EOL) might still suffer from this.

> otoh, it's not unusual in LTS distros (and especially RHEL/centos...) to use packages older than that

According to https://repology.org/project/libxi/versions, CentOS 6+ have libXi 1.7.8 or better, so they shouldn't suffer from this.

**Comment by slouken** [comment]
Okay, it seems this isn't a concern. Thanks!
