### ISSUE TITLE
iOS: real mouse_motion locked on mouse_down

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/SDL#4941]
Continued from #4482

In Exult we use a custom mouse pointer. You move your Avatar by holding down the left mouse button and moving the mouse in various directions. The further away from the Avatar the faster you move (and the mouse pointer changes shape as well).
This worked with the previous release of SDL2. Now the mouse location gets "locked down" while you press a button (left or right) and you can't move the mouse until you release the button.
27ce914 is the culprit, tested with 19c129f and that still works.

I also tested the touch demo and there it works, so it is likely that something in Exult breaks (since Exult is a bit more elaborate than the touch demo :)).
To make it work again, I need to revert both file changes (SDL_uikitevents.m, SDL_uikitview.m).

**Comment by slouken** [comment]
Can you debug and find out what's going on? If not, can you provide me with the files I need to reproduce it here?

**Comment by DominusExult** [comment]
I have no idea where to begin on debugging that.
Exult is at https://github.com/exult/exult in it's /ios folder you need to add several sources to the subfolders:
- SDL2 to the SDL2 subfolder
- libogg https://github.com/xiph/ogg.git to the libogg subfolder
- libvorbis https://github.com/xiph/vorbis.git to the libvorbis subfolder
- munt git://github.com/munt/munt.git to the libmt32emu subfolder

Once these are placed you can just run the Exult project file from the ios subfolder and it *should* just compile.

The game files need to be moved onto the iOS device via iTunes file sharing (in Finder click on the iOS device, go to Files and then select Exult.
If you use the simulator, our debug outputs where the documents folder is situated, so you know where to put the game files on your hard drive (and then you need to restart Exult).
I'll email you the dropbox link to the game files.

Once the game starts, select Forge of Virtue and "journey onward". Exult usually hides the cursor but will show the cursor when you move a real mouse 
The event handler for all of this in the usual game screen is at https://github.com/exult/exult/blob/master/exult.cc#L1253
The changes for the real mouse were commits https://github.com/exult/exult/commit/fdd0e915c8834e500e3b8b939e6dfbab5dfd72fe and https://github.com/exult/exult/commit/bc982080edd75403c2ae2c8bfa8f5aebef754714

**Comment by slouken** [comment]
I'm able to reproduce this, and indeed, there are no SDL mouse motion events coming through. Investigating...

**Comment by slouken** [comment]
Fixed! Please open new bugs if there are any other issues. :)

**Comment by DominusExult** [comment]
Thank you!!! I'll test it over the weekend and will report if there is anything to report ;)
I hope getting Exult to run and the games on the device was painless enough!

**Comment by slouken** [comment]
Yup, they were great instructions, thanks!
