### ISSUE TITLE
Win10: Freshly opened Xbox 360 joysticks do not rumble until an axis or button event

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4949]
Rumble does nothing until an axis (but not trigger axis, strangely) is moved or a button pressed (but not the guide button) on the joystick. 
Tested on Xbox 360 & S. Latest DLL built with VC2019. Bug has been around for a while.
Also, `SDL_JoystickHasRumble()` doesn't ever return `SDL_TRUE`, even when rumble is working.
Also-also, `SDL_JoystickCurrentPowerLevel()` returns unknown (-1) until an axis is moved or button pressed <-- this might give a clue as to what's happening.
Repro with this test code. Plug controller in - keep it still so no events trigger. Press any key to rumble, you should get nothing. Then move axis or press a button on controller, then press a key and you'll get rumble. Dark green indicates controller added, bright green indicates `SDL_JoystickHasRumble()` returning `SDL_TRUE`.

```
#include <SDL.h>
int main(int argc, char** argv) {
	SDL_Init(SDL_INIT_VIDEO | SDL_INIT_JOYSTICK);
	SDL_Window* w; SDL_Renderer* r;
	SDL_CreateWindowAndRenderer(640, 480, 0, &w, &r);
	SDL_Joystick* j = nullptr;
	Uint8 g = 0;
	for (;;) {
		SDL_PumpEvents();
		SDL_Event event;
		while (SDL_PeepEvents(&event, 1, SDL_GETEVENT, 0, SDL_LASTEVENT) == 1) {
			switch (event.type) {
			case SDL_JOYDEVICEADDED:
				j = SDL_JoystickOpen(event.jdevice.which);
				if(j)
					g = 0x40;
				break;
			case SDL_KEYDOWN:
				SDL_JoystickRumble(j, 0xFFFF, 0xFFFF, 250);
				break;
			case SDL_QUIT:
				SDL_Quit();
				return 0;
			}
		}
		if (j && SDL_JoystickHasRumble(j) == SDL_TRUE)
			g = 0xFF;
		if (*SDL_GetError()) {
			SDL_SetWindowTitle(w, SDL_GetError());
			SDL_ClearError();
		}
		SDL_SetRenderDrawColor(r, 0, g, 0, 0xFF);
		SDL_RenderClear(r);
		SDL_RenderPresent(r);
	}
}
```

**Comment by slouken** [comment]
This is expected. The raw input controllers don't know what XInput slot or WGI device they're associated with until there's input to match them up.
