### ISSUE TITLE
Android 12 requires BLUETOOTH_CONNECT permission

### ISSUE THREAD

**Issue by StephenCWills** [libsdl-org/SDL#4952]
The following error and stack trace comes from DevilutionX as we were attempting to upgrade our target SDK version to 31: [android-err.log](https://github.com/libsdl-org/SDL/files/7532494/android-err.log). The game crashes at startup with this error on my Google Pixel 4 (Android 12). The error is referring to the call to `getBondedDevices()` in `HIDDeviceManager`.
https://github.com/libsdl-org/SDL/blob/674f361decbb607bf682535975b64d2ba5ad89fd/android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java#L375-L383

This was actually identified once before in a somewhat unrelated issue. https://github.com/libsdl-org/SDL/issues/4715#issuecomment-913211550 indicates that the permission needs to be added to `AndroidManifest.xml` and should also be requested at runtime. However, the suggested resolution toward the end of that thread was to downgrade to SDK 26, which doesn't seem like a good long-term solution. FYI, the messages in that issue also suggest that the `BLUETOOTH_SCAN` permission needs to be declared in `AndroidManifest.xml`, but I'm not sure if that's really the case as I haven't needed it in my testing.

Is this the only way to interface with Steam controllers? It seems reasonable to assume that the vast majority of users will not have a Steam controller, so I feel it's bit extreme to require a runtime permission request just to check for them.

**Comment by 1bsyl** [comment]
just to make clear, upgrading can mean two things:

1/ you can use the latest SDK, just to be up to date..
and then, you add/modify "compileSdkVersion 31" to your build.gradle
it's straight forward and should just work. if you update your sdk you can even have bugfix with that.

2/ but if  you want to *target* it, you need to add "targetSdkVersion 31" 
and this step means you've fully tested your code on android 12.
So you can encounter issue like this one. 
(SDL isn't ready for targetSdk 31)
but you can list stuff that need to be modified to targetSdkVersion 31. So that it will be easier to update.

Also.
- does steam controllers really need to target sdk 31 ?
- I think targetSdkVersion 29 is ok, and is required by googleplay as a minimum,

see:
https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd

**Comment by StephenCWills** [comment]
> but if you want to target it, you need to add "targetSdkVersion 31"
> and this step means you've fully tested your code on android 12.
> So you can encounter issue like this one.
(SDL isn't ready for targetSdk 31)

Yes, I imagine this issue is one of the things that would need to be resolved in order for SDL to be ready.

> does steam controllers really need to target sdk 31 ?

I'm not sure what this means, but if you meant to ask whether DevilutionX really needs to target SDK 31, I'd say that it's not strictly necessary at this moment. We should be able to use SDK 30 until Google raises the minimum requirement again. We're just following recommendations to make upgrading a priority.

> I think targetSdkVersion 29 is ok, and is required by googleplay as a minimum

As of August, API level 30 has been the requirement for new apps. As of this month, it is also required for app updates.
https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by AJenbo** [comment]
>     * does steam controllers really need to target sdk 31 ?

@1bsyl I think you miss understood. The issue here is that the current SDL code for the Steam controller breaks when setting targetSdkVersion to 31.

**Comment by 1bsyl** [comment]
@AJenbo 
I meant SDL source use targetSdkVersion 26. So do you really need to bump it to 31 ?

I personally use 29. but, as @StephenCWills  says, googleplay now requires 30.
maybe we should bump this to 30, @slouken ?

**Comment by AJenbo** [comment]
SDK 31 is needed fore some features such as:
  - Full App transferal, users won't have to download game data again when switching to a new phone
  - Game mode, user can choose to prioritize battery life, visuals or game performance

Google Play appears to increase the SDK version requirement for new apps each August, and for app updates each November.

Migrating internally to SDK 31 now means that we won't be in a mad dash by the time it is required. We can identify issues early in testing and development. Which gives us time to work with upstream to solve potential issues in time.

I'm not sure what your intended meaning is, but it reads like "why not wait with solving this identified issue until it's critical?". Which I think is a bad strategy.

We are happy to help out with patches and testing. But are a bit limited in that we do not have a Stream Controller to test with.

**Comment by slouken** [comment]
We should support SDK 31, if possible in the 2.0.18 release, so please continue to report issues and PRs.

@AJenbo, if you're in the US and serious about your offer, I can send you a Steam Controller. Just send me your mailing address to slouken@libsdl.org

**Comment by AJenbo** [comment]
> @AJenbo, if you're in the US and serious about your offer, I can send you a Steam Controller. Just send me your mailing address to [slouken@libsdl.org](mailto:slouken@libsdl.org)

Unfortunately I'm not, but @StephenCWills is so if you can send it to him instead we can still work on updating the support.

**Comment by slouken** [comment]
> > @AJenbo, if you're in the US and serious about your offer, I can send you a Steam Controller. Just send me your mailing address to [slouken@libsdl.org](mailto:slouken@libsdl.org)
> 
> Unfortunately I'm not, but @StephenCWills is so if you can send it to him instead we can still work on updating the support.

Sure, just send me your address!

**Comment by StephenCWills** [comment]
I sent it a few hours ago. Have you not received it?

**Comment by slouken** [comment]
No, I didn't get it... however... I fixed the bug! :)
