### ISSUE TITLE
macOS 10.6 aborts when scrolling using trackpad

### ISSUE THREAD

**Issue by zturtleman** [libsdl-org/SDL#4960]
Present in git HEAD (ebed961cb2f685a6db9467f2496d644110bea3c3)
Introduced in https://github.com/libsdl-org/SDL/commit/e841b066fd76aa1eb7cf2be9a46cc82798ab3c33 (SDL 2.0.10)
Based on [Apple docs](https://developer.apple.com/documentation/appkit/nseventtype/nseventtypebegingesture) and SDL's macOS compatibility this appears to affect macOS 10.6 to 10.10, and later versions if built against 10.7 to 10.10 SDK.

## Abort
Using the built in MacBook Pro trackpad on macOS 10.6; when scrolling or performing other gestures (magnify, rotate, swipe) there is an uncaught exception. SIGABRT is triggered causing the program to exit. Scrolling using a USB mouse does not have this issue.

The exception is thrown when getting the NSEvent subtype in [SDL_cocoawindow.m handleTouches](https://github.com/libsdl-org/SDL/blob/ebed961cb2f685a6db9467f2496d644110bea3c3/src/video/cocoa/SDL_cocoawindow.m#L1304) and also occurred in [touchesBeganWithEvent](https://github.com/libsdl-org/SDL/blob/ebed961cb2f685a6db9467f2496d644110bea3c3/src/video/cocoa/SDL_cocoawindow.m#L1253) with swipe gesture. Using the subtype to determine if it's from a trackpad was introduced in https://github.com/libsdl-org/SDL/commit/e841b066fd76aa1eb7cf2be9a46cc82798ab3c33.

Terminal log after scrolling using trackpad and program aborts:
```
2021-11-11 12:01:46.683 ioquake3[176:903] *** Assertion failure in -[NSEvent subtype], /SourceCache/AppKit/AppKit-1038.36/AppKit.subproj/NSEvent.m:1924
2021-11-11 12:01:46.684 ioquake3[176:903] An uncaught exception was raised
2021-11-11 12:01:46.684 ioquake3[176:903] Invalid message sent to event "NSEvent: type=BeginGesture loc=(370,324) time=250.4 flags=0x100 win=0x100629c50 winNum=25 ctxt=0x0"
2021-11-11 12:01:46.687 ioquake3[176:903] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid message sent to event "NSEvent: type=BeginGesture loc=(370,324) time=250.4 flags=0x100 win=0x100629c50 winNum=25 ctxt=0x0"'
*** Call stack at first throw:
(
	0   CoreFoundation                      0x00007fff8013c784 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x00007fff86937f03 objc_exception_throw + 45
	2   CoreFoundation                      0x00007fff8013c5a7 +[NSException raise:format:arguments:] + 103
	3   Foundation                          0x00007fff8278697a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AppKit                              0x00007fff89dad26e -[NSEvent subtype] + 212
	5   libSDL2-2.0.0.dylib                 0x00000001f1575622 -[Cocoa_WindowListener handleTouches:withEvent:] + 82
	6   AppKit                              0x00007fff89daa206 forwardMethod + 104
	7   AppKit terminate called after throwing an instance of 'NSException'
```

## Event types
This is incomplete as it doesn't cover 10.7 to 10.10 additions. macOS 10.8 and 10.10 add more touch event types. 10.7 may use [Gesture with subtype 16](https://bugzilla.mozilla.org/show_bug.cgi?id=863841#c13) for smart magnify (two finger double tap).

These event types don't have a subtype:
```
NSEventTypeBeginGesture
NSEventTypeEndGesture
NSEventTypeMagnify
NSEventTypeRotate
NSEventTypeSwipe
```
They occur on 10.6 along with NSEventTypeGesture. I tested 10.11 (final for my hardware) and only NSEventTypeGesture occurs there. Documentation for [NSEventTypeBegin/EndGesture](https://developer.apple.com/documentation/appkit/nseventtype/nseventtypebegingesture) says "Note that apps that link against macOS 10.11 and later no longer receive this event type."

NSEventTypeGesture subtype:
```
macOS 10.11 trackpad
0 - any touch

macOS 10.6 trackpad
6 -  two finger scroll
11 - any other single or multi touch
```
SDL checks if subtype is NSEventSubtypeMouseEvent (0) to see if touch event is from a trackpad. On macOS 10.6 NSEventTypeGesture has different subtypes and was never 0. I couldn't find any enum or defines they correspond with. On the same macbook running 10.11, subtype was always 0.

## Seeking a solution

I have a patch that _works for me_ for trackpad using 10.6 and 10.11 but it doesn't handle 10.7 to 10.10 additions. I don't know if macbook touch bar (and other touch devices?) will be misidentified as trackpad. So I don't think it makes sense to apply to SDL as-is.
```objc
    /* probably a MacBook trackpad; make this look like a synthesized event.
     * This is backwards from reality, but better matches user expectations.
     *
     * macOS 10.5 to 10.10 use begin/end gesture, magnify, rotate, and swipe
     * events; treat them as a trackpad. Gesture has subtype set to 6 for two
     * finger scroll and 11 otherwise. Other types throw an exception when
     * accessing subtype.
     */
    const BOOL istrackpad = ([theEvent type] == NSEventTypeGesture
                             && ([theEvent subtype] == NSEventSubtypeMouseEvent
                                 || [theEvent subtype] == 6
                                 || [theEvent subtype] == 11))
                         || [theEvent type] == NSEventTypeBeginGesture
                         || [theEvent type] == NSEventTypeEndGesture
                         || [theEvent type] == NSEventTypeMagnify
                         || [theEvent type] == NSEventTypeRotate
                         || [theEvent type] == NSEventTypeSwipe;
```

Trying to just prevent the abort (and leave 10.6 touch events not detected as trackpad):

respondsToSelector subtype evaluates to true even for NSEvent types without subtype (thus still triggering the abort). I'm not familiar with Objective-C so maybe I did something wrong.
```objc
    BOOL istrackpad = ([theEvent respondsToSelector:@selector(subtype)] && [theEvent subtype] == NSEventSubtypeMouseEvent);
```

Catching the exception still prints the assertion failure but without the stack trace to tell what's causing it. It's annoying and would probably be hard to track down from the terminal messages but it's a step up from aborting.
```objc
    BOOL istrackpad = NO;
    @try {
        istrackpad = ([theEvent subtype] == NSEventSubtypeMouseEvent);
    }
    @catch (NSException *e) {
        /* if NSEvent type doesn't have subtype, such as NSEventTypeBeginGesture on
         * macOS 10.5 to 10.10, then NSInternalInconsistencyException is thrown.
         * This still prints a message to terminal so catching it's not an ideal solution.
         *
         * *** Assertion failure in -[NSEvent subtype]
         */
    }
```
```
2021-11-11 12:01:46.683 ioquake3[176:903] *** Assertion failure in -[NSEvent subtype], /SourceCache/AppKit/AppKit-1038.36/AppKit.subproj/NSEvent.m:1924
```

**Comment by sezero** [comment]
Can this be closed after PR #4961?
