### ISSUE TITLE
`SDL_CreateRGBSurfaceFrom` and `SDL_CreateRGBSurfaceWithFormatFrom` don't check `pixels` is non-null

### ISSUE THREAD

**Issue by InfoTeddy** [libsdl-org/SDL#4963]
I just fixed a bug in VVVVVV that was partially caused by this (see TerryCavanagh/VVVVVV@6e832cae20102079a065b212fdc9b0b4f03795d3). A failed decode meant passing a null `pixels` to `SDL_CreateRGBSurfaceWithFormatFrom`, which succeeded and caused a crash further down the line (in `SDL_ConvertSurfaceFormat`).

While we should have been checking the return value of our decode function in the first place, it is quite curious that `SDL_CreateRGBSurfaceFrom` and `SDL_CreateRGBSurfaceWithFormatFrom` will accept a null `pixels` value without erroring. Is this intentional?

**Comment by slouken** [comment]
Yes, it's possible to create a placeholder surface with NULL pixels and then update the pointer later.
