### ISSUE TITLE
iconv-related warning when building main with musl libc

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#4966]
i'm just reporting this because i noticed in commit history that a great deal of work was invested lately to build SDL2 without warnings.

```
/home/user/tmp/SDL/src/stdlib/SDL_iconv.c: In function 'SDL_iconv_REAL':
/home/user/tmp/SDL/src/stdlib/SDL_iconv.c:76:49: warning: passing argument 2 of 'iconv' from incompatible pointer type [-Wincompatible-pointer-types]
     retCode = iconv((iconv_t) ((uintptr_t) cd), inbuf, inbytesleft, outbuf, outbytesleft);
                                                 ^~~~~
In file included from /home/usr/tmp/SDL/src/stdlib/SDL_iconv.c:38:0:
/usr/include/iconv.h:17:8: note: expected 'char ** restrict' but argument is of type 'const char **'
 size_t iconv(iconv_t, char **__restrict, size_t *__restrict, char **__restrict, size_t *__restrict);
```

musl libc uses the same signature as reported in the posix manpage "man 3p iconv"

```
SYNOPSIS

     #include <iconv.h>

     size_t iconv(iconv_t cd, char **restrict inbuf,
         size_t *restrict inbytesleft, char **restrict outbuf,
         size_t *restrict outbytesleft);
```

**Comment by slouken** [comment]
I've seen projects that check for the iconv prototype at configure time. Maybe we should do that too?

@rofl0r, just to be clear, iconv isn't actually modifying that parameter right? That could cause a crash converting read-only strings.

**Comment by rofl0r** [comment]
reading the code in musl it appears to modify the pointer, but not the pointed-to data, so it effectively uses the `char** restrict` as `char * const *`. this should be a non-issue though since the pointer is passed in a register.

**Comment by icculus** [comment]
So we already have some code to check for this specific thing...

https://github.com/libsdl-org/SDL/blob/main/src/stdlib/SDL_iconv.c#L40-L49

...if there's some reasonable way to decide we're building against musl, we can add it to that list.

**Comment by rofl0r** [comment]
> ...if there's some reasonable way to decide we're building against musl

wrong approach, the decision should be whether we're building against POSIX signature or not using a configure check.

see "why is there no `__MUSL__` macro" [here](https://wiki.musl-libc.org/faq.html) for an explanation.

**Comment by icculus** [comment]
There are macros for things like this _specifically because everything has quirks_, and one of those quirks is C runtimes that can't agree on what a function signature should be. Neither musl nor anyone else is going to change this function, regardless of who is correct.

Anyhow, I guess we'll add a configure check.

**Comment by slouken** [comment]
> Anyhow, I guess we'll add a configure check.

It looks like this version of iconv.m4 sets ICONV_CONST appropriately:
https://fossies.org/linux/libmicrohttpd/m4/iconv.m4

**Comment by sezero** [comment]
> It looks like this version of iconv.m4 sets ICONV_CONST appropriately: https://fossies.org/linux/libmicrohttpd/m4/iconv.m4

Mainstream of it is http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=m4/iconv.m4;hb=HEAD

**Comment by icculus** [comment]
So I don't know if this actually works with musl, but libxml just removed this test, and simply casts to `void *` now.

https://github.com/GerHobbelt/libxml2/commit/21ddad52840195b443ea57cf1cd0e123a8c10c24

Can we try that first and see if that makes everything happy, before we add this silly test to both configure and cmake?

**Comment by slouken** [comment]
Sure. :)

**Comment by icculus** [comment]
Okay, I put a patch in, but we'll revisit if the builders complain about whatever platforms in a few minutes.
