### ISSUE TITLE
Mono recording crashes with 2.0.16 release but not with latest build

### ISSUE THREAD

**Issue by shooshx** [libsdl-org/SDL#4967]
I'm using this simple bit of code for windows with VS2019:
https://fossies.org/linux/SDL2/test/testaudiocapture.c
I made a small change to it to record mono rather than stereo. In line 136 I changed the `SDL_AUDIO_ALLOW_ANY_CHANGE` to `0` so that the spec would remain with 1 channel.

When I run this with the 2.0.16 release DLL and it crashes with a access violation
I then compiled the latest code which says 2.0.18 in the WhatsNew.txt, used the resulting DLL and that worked perfectly.
Is that a bug that was fixed? something else?

**Comment by slouken** [comment]
Yup, the fix will be in the next public release.
