### ISSUE TITLE
API to update only certain joystick's state

### ISSUE THREAD

**Issue by sam20908** [libsdl-org/SDL#4976]
For my application, I only care about one of all joysticks SDL detects. It was terribly inefficient for my application to call `SDL_GameControllerUpdate` because it updates all the joystick's states even though I only want one joystick's state.

If there's an ability to do this, let me know!

**Comment by slouken** [comment]
It should only update joysticks that you've opened. If you haven't opened them, it will only poll devices when the system device list changes.

**Comment by sam20908** [comment]
Hmm, that almost works, but I wanted to open them all so the user can select joystick from names, but `SDL_GameControllerName` requires `SDL_GameControllerOpen`.

**Comment by slouken** [comment]
You can open them all while the user is selecting their joystick, and then close them once they're playing your game.

**Comment by AntTheAlchemist** [comment]
No need to open them to get the names. Can't you do this (copied from my code where I do something similar):

```
			for (int i = 0; i < joynum; i++) {
				const char* name;
				if (SDL_IsGameController(i))
					name = SDL_GameControllerNameForIndex(i);
				else
					name = SDL_JoystickNameForIndex(i);
```

**Comment by sam20908** [comment]
That looks like the solution, thanks!

Although I think it'd still be beneficial to have an API that does this only for one joystick, and `SDL_GameControllerUpdate` will use that for all joysticks instead.

**Comment by sam20908** [comment]
I'm closing the issue now since it's technically solved, but if you plan on making an API for this, you can reopen it.
