### ISSUE TITLE
"Passed a NULL mutex" when quitting SDL on Windows

### ISSUE THREAD

**Issue by meyraud705** [libsdl-org/SDL#4978]
I got "Passed a NULL mutex" 6 times when quitting SDL. It come from the joystick subsystem whether or not a joystick is plugged in. I tested with both 2.0.16 and latest git revision.

A similar issue was discussed in https://github.com/libsdl-org/SDL/issues/4435#issuecomment-965961929 .

I attached a backtrace from  where the mutex is destroyed (in RAWINPUT_JoystickQuit) and then locked (in RAWINPUT_WindowProc):

[null_mutex.txt](https://github.com/libsdl-org/SDL/files/7562156/null_mutex.txt)

**Comment by AntTheAlchemist** [comment]
I can confirm this error triggers by simply setting `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");` and `SDL_INIT_GAMECONTROLLER` without touching any of the game controller API or having a controller connected.  Once a controller is plugged in then this error triggers every frame, even in a minimal event polling loop.

**Comment by cgutman** [comment]
Please give #4980 a try. That should resolve your issues.

**Comment by meyraud705** [comment]
> Please give #4980 a try. That should resolve your issues.

That works, thanks.
