### ISSUE TITLE
Failed to open audio_device on Android 5.x with freq 96khz+

### ISSUE THREAD

**Issue by ITotalJustice** [libsdl-org/SDL#4982]
Firstly, thank you so much for sdl2, makes my life so much easier porting to different platforms. Android was especially simple

---

Hi. I'm using SDL2 from commit 7ad6435 on an emulated `nexus 5` running `android 5.0`. When trying to open an audio device, it fails.
I have of course called `SDL_init()` with flags `SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_HAPTIC | SDL_INIT_GAMECONTROLLER`.

this is my code to open an audio device
```c
// in header
enum
{
    CHANNELS = 2,
    SAMPLES = 1024,
    AUDIO_FREQ = 96000,
    AUDIO_FORMAT = AUDIO_S8,
    AUDIO_FLAGS = SDL_AUDIO_ALLOW_ANY_CHANGE,
};

// in src
SDL_AudioSpec wanted_spec =
{
    .freq = AUDIO_FREQ,
    .format = AUDIO_FORMAT,
    .channels = CHANNELS,
    .samples = SAMPLES,
    .callback = sdl2_audio_callback,
    .userdata = emu,
};

if (!streaming)
{
    wanted_spec.callback = NULL;
    wanted_spec.userdata = NULL;
}

audio_device = SDL_OpenAudioDevice(NULL, 0, &wanted_spec, &audio_spec, AUDIO_FLAGS);
if (audio_device == 0) // this is where it fails
{
    goto fail;
}
```

this was also tested on an actual nvidia shield running 5.1.

this works on all later versions of android, as well of pc, web etc...

Let me know if you need anymore info or want me to try something.

**Comment by ITotalJustice** [comment]
I forgot to mention, I am targeting sdk 31, min target is 21.

**Comment by ITotalJustice** [comment]
Update: using a lower requested frequency allows the audio device to be opened, for example 48k. This worked on the nvidia shield on 5.1!

However, on nexus 5 (emulated) running 5.0, in the case on callback based audio, the callback is called exactly a  few times (depends on sample size i think, usually between 3-6 calls), then never again. As for queue, it returns 0 (so success) but no audio is heard...

for non-callback audio, i have tried just returning straight away with in the callback, so not touching the data passed, it is still only called a few times.

Also, i'm curious as to why it would fail with 96k when i pass the flags to enable the frequency to be changed if needed.

**Comment by 1bsyl** [comment]
@ITotalJustice 
can you can display the error:
`SDL_Log("error: %s", SDL_GetError());`

**Comment by 1bsyl** [comment]
and also an "adb logcat"

**Comment by 1bsyl** [comment]
seems Android AudioTrack has a limitation for the frequency

https://android.googlesource.com/platform/frameworks/base/+/android-5.0.2_r1/media/java/android/media/AudioTrack.java#95

log
https://android.googlesource.com/platform/frameworks/base/+log/android-5.0.2_r1/media/java/android/media/AudioTrack.java

was fixed here:
https://android.googlesource.com/platform/frameworks/base/+/70b395e8c1d06ca9288afd418b9e889df4060eab%5E%21/media/java/android/media/AudioTrack.java

So it should be fixed, starting Android 5.0.2

**Comment by 1bsyl** [comment]
@ITotalJustice can you try with latest commit ?

**Comment by 1bsyl** [comment]
@ITotalJustice 
since the android issue was solved in 5.0.2
it makes sense to fail with the 5.0 device
but it should have been working with the 5.1 nvidia device !?

**Comment by ITotalJustice** [comment]
> @ITotalJustice since the android issue was solved in 5.0.2 it makes sense to fail with the 5.0 device but it should have been working with the 5.1 nvidia device !?

It didn't work with 5.0 or 5.1. If you have android studio, my exact setup to test was a `Nexus 5, API 22 (5.1)` and my mate tested it on his nvidia shield.

this is what i was using yesterday as a work around:
```c
 #ifdef ANDROID
     // SEE: https://github.com/libsdl-org/SDL/issues/4982
     if (SDL_GetAndroidSDKVersion() <= 22) // 5.1
     {
         wanted_spec.freq = 48000;
     }
 #endif
 ```
if i just check for 5.0 or lower, then it won't open on 5.1, so the latest commit just pushed also doesn't because it checks for 5.0. 

> @ITotalJustice can you can display the error: `SDL_Log("error: %s", SDL_GetError());`

sdl_geterror: `Open device failed!`

log info for android studio: 
```
E/libOpenSLES: Cannot create audio player: unsupported sample rate 96000000 milliHz
W/libOpenSLES: Leaving Engine::CreateAudioPlayer (SL_RESULT_CONTENT_UNSUPPORTED)
I/SDL/APP: [SDL-AUDIO] failed to open: Open device failed!
E/SDL/APP: failed: Open device failed!
```

**Comment by 1bsyl** [comment]
@ITotalJustice : ok, I'm mistaken, I fixed the java/audiotrack back-end, but also have the opensles backend which is in fact used by priority. .. so let me check this one

**Comment by 1bsyl** [comment]
After some investigation!
This sounds to be the same issue. Sample rate isn't supported and it fails to create the device.

OpenSLES have an interface to query the min/max sample rate for of the device ...
https://android.googlesource.com/platform/frameworks/wilhelm/+/master/include/SLES/OpenSLES.h#563
/ SL_IID_AUDIOIODEVICECAPABILITIES,

but it reports as not supported on a recent device ...
(similar issue https://groups.google.com/g/android-ndk/c/EM1YYXvkYAU?pli=1 )

so not sure what we should do ... maybe a similar fix like in the java backend ...

...
as a workaround (and to test the previous fix) you can test the oldest backend
SDL_SetEnv(SDL_AUDIODRIVER, "android");
(though but on recent android device, we use another backend: AAudio)

**Comment by ITotalJustice** [comment]
> After some investigation! This sounds to be the same issue. Sample rate isn't supported and it fails to create the device.
> 
> OpenSLES have an interface to query the min/max sample rate for of the device ... https://android.googlesource.com/platform/frameworks/wilhelm/+/master/include/SLES/OpenSLES.h#563 / SL_IID_AUDIOIODEVICECAPABILITIES,
> 
> but it reports as not supported on a recent device ... (similar issue https://groups.google.com/g/android-ndk/c/EM1YYXvkYAU?pli=1 )
> 
> so not sure what we should do ... maybe a similar fix like in the java backend ...
> 
> ... as a workaround (and to test the previous fix) you can test the oldest backend SDL_SetEnv(SDL_AUDIODRIVER, "android"); (though but on recent android device, we use another backend: AAudio)

Thank you for looking further into it. I’ll try the workaround shortly to make sure the previous commit worked

**Comment by 1bsyl** [comment]
@ITotalJustice 
so this fixes the OpenSLES back-end, with another attempt to open the device with a lower frequency

**Comment by ITotalJustice** [comment]
> @ITotalJustice so this fixes the OpenSLES back-end, with another attempt to open the device with a lower frequency

Thanks again! Yes that commit fixes it. I ended up doing something similar to your solution internally as well

```c
static const int frequencies[] =
{
    AUDIO_FREQ_192k, // 192000
    AUDIO_FREQ_96k,  // 96000
    AUDIO_FREQ_48k,  // 48000
    AUDIO_FREQ_44k,  // 44100
    AUDIO_FREQ_22k,  // 22050
    AUDIO_FREQ_11k,  // 11025
};

for (size_t i = 0; i < SDL_arraysize(frequencies); i++)
{
    wanted_spec.freq = frequencies[i];
    audio_device = SDL_OpenAudioDevice(NULL, 0, &wanted_spec, &audio_spec, AUDIO_FLAGS);

    // exit loop if we have opened audio!
    if (audio_device)
    {
        break;
    }

    log_info("[SDL-AUDIO] failed to open audio device with freq %d\n", frequencies[i]);
}

// we failed to open any audio device...
if (audio_device == 0)
{
    goto fail;
}
```
Anyway, thank you for digging into the problem and fixing it!
