### ISSUE TITLE
Failed create Direct3D11 renderer on Windows 7

### ISSUE THREAD

**Issue by DarkContact** [libsdl-org/SDL#4987]
Envoriment: Windows 7 (x64)
Compiler: MinGW 8.1.0

When creating Direct3D11 renderer on Windows 7, I get the following error message from SDL_GetError:
`__FUNCTION__, IDXGIFactory2::CreateSwapChainForHwnd: `

The message itself is not informative, perhaps this is a separate problem. However, if you change `swapChainDesc.Scaling = DXGI_SCALING_NONE;` -> `swapChainDesc.Scaling = DXGI_SCALING_STRETCH;` and don't call function `IDXGISwapChain1_SetRotation` in this case, the Direct3D11 renderer is created.

As for the replacement of the scaling modes, I found this in the Microsoft documentation: 
https://docs.microsoft.com/en-us/windows/win32/direct3darticles/platform-update-for-windows-7
>IDXGIFactory2::CreateSwapChainForHwnd takes a DXGI_SWAP_CHAIN_DESC1 structure, which has a field for Scaling. DXGI_SCALING_NONE is not supported on Windows 7 with the platform update and causes CreateSwapChainForHwnd to return DXGI_ERROR_INVALID_CALL when called.

There is a similar message for SetRotation:
https://docs.microsoft.com/ru-ru/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgiswapchain1-setrotation
>Platform Update for Windows 7:  On Windows 7 or Windows Server 2008 R2 with the Platform Update for Windows 7 installed, SetRotation fails with DXGI_ERROR_INVALID_CALL.

**Comment by slouken** [comment]
Good catch. Can you create a PR, attach a patch, or paste in the working code?

Thanks!

**Comment by DarkContact** [comment]
Yes, I created PR: https://github.com/libsdl-org/SDL/pull/4999

P.S. Sorry for reopened issue, accidentally pressed on the phone

**Comment by icculus** [comment]
Closing this, as the PR got merged.
