### ISSUE TITLE
Play audio on android when screen is turned off

### ISSUE THREAD

**Issue by db-tech** [libsdl-org/SDL#4991]
Hi,

I've created an android application with SDL2 where I can play different audio files.
Is there a way that the audio could continue playing when I turn the display off ?

What I did figure out is that I can remove `nativePause` and the audio will continue. 
But then, when I turn the display back on, the app will not reappear and I get a lot off errors like:
`E/libEGL: eglSwapBuffersWithDamageKHR:1152 error 300d (EGL_BAD_SURFACE)`

Any help is much appreciated

**Comment by ITotalJustice** [comment]
Hi,

I haven't tried this myself, but SDL_hint.h has some options related to this.
`SDL_HINT_ANDROID_BLOCK_ON_PAUSE`
and 
`SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO`

You could try enabling those and see if it works!

**Comment by ITotalJustice** [comment]
> Hi,
> 
> I haven't tried this myself, but SDL_hint.h has some options related to this. `SDL_HINT_ANDROID_BLOCK_ON_PAUSE` and `SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO`
> 
> You could try enabling those and see if it works!

i just tested this, it worked for me!
```c
SDL_SetHint(SDL_HINT_ANDROID_BLOCK_ON_PAUSE, "0");
SDL_SetHint(SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO, "0");
```

**Comment by db-tech** [comment]
Wow, thanks for the fast response. 
Unfortunately SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO is missing here. I am using 2.0.12 and it seems like this feature was added in 2.0.14... so I have to rebuild.
But yeah, awesome, I will try that as soon as possible.

**Comment by db-tech** [comment]
So, I did update to SDL version 2.0.16 and rebuild everything.
I did add those two lines right after the SDL_Init call.

Unfortunately, this does not seem to work. When I turn the display of, the audio is still pausing. 
Any Idea what could have gone wrong ?

**Comment by db-tech** [comment]
So after reading the Pause / Resume behavior section in the Android documentation, i got it to work. When setting SDL_HINT_ANDROID_BLOCK_ON_PAUSE to 0 and the Screen is pausing, I had to stop all calls to the Renderer in between of SDL_APP_WILLENTERBACKGROUND and  SDL_APP_DIDENTERFOREGROUND.

So consider this issue solved

**Comment by slouken** [comment]
I'm glad to hear it.
