### ISSUE TITLE
The format that SDL_PIXELFORMAT_RGB444 maps to should be named something else

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4994]
`SDL_PIXELFORMAT_RGB444` suggests it would be a packed 12bit format, which it is not. Also even more weirdly, the partially mirrored variation `SDL_PIXELFORMAT_XRGB4444` *is* better named. While I assume you won't want to remove the oddly (wrongly?) named one for backwards compatibility reasons, it would be nice if the proper name ~~`SDL_PIXELFORMAT_RGBX4444`~~ (see [here for correct name](https://github.com/libsdl-org/SDL/issues/4994#issuecomment-978131097) ) would be added as an alias at least so people can use the format name that actually reflects correctly what it is: a non-packed 16bit format, not a 12bit one.

**Comment by ccawley2011** [comment]
While `SDL_PIXELFORMAT_RGBX4444` (as well as `SDL_PIXELFORMAT_BGRX4444`, `SDL_PIXELFORMAT_RGBA5551` and `SDL_PIXELFORMAT_BGRA5551`) could be added as new format(s), it would be distinct from `SDL_PIXELFORMAT_XRGB4444` rather than an alias since the padding would be in the low 4 bits instead of the high 4 bits.

**Comment by ell1e** [comment]
Sorry I wasn't clear enough, it's supposed to be an alias of `SDL_PIXELFORMAT_RGB444`. Obviously `SDL_PIXELFORMAT_XRGB4444` is just a different format, which is exactly why a new proper alias for the one that *isn't* distinct but misleadingly named would be so important IMHO.

**Comment by ccawley2011** [comment]
Both `SDL_PIXELFORMAT_RGB444` and `SDL_PIXELFORMAT_XRGB4444` are defined using `SDL_PACKEDORDER_XRGB`, though, so it wouldn't make sense to define `SDL_PIXELFORMAT_RGBX4444` using the same packed order. In particular, `SDL_PIXELFORMAT_RGBX8888` already exists and is defined using `SDL_PACKEDORDER_RGBX` instead, so I would expect `SDL_PIXELFORMAT_RGBX4444` to be defined the same way.

I agree that the ambiguity with the `SDL_PIXELFORMAT_RGB444` alias isn't ideal, though.

**Comment by ell1e** [comment]
Oh so maybe I got you wrong then. Are you saying `SDL_PIXELFORMAT_RGB444` and `SDL_PIXELFORMAT_XRGB4444` are already equivalent?

I'm not sure that's true, from my tests `SDL_PIXELFORMAT_RGB444` on little endian is: **1. first byte:** lower order bits red, higher order bits green. **2. second byte:** lower order bits blue, higher order bits alpha. So `XR` are definitely not on the same byte, as that name would suggest. Hence, I think it should be `SDL_PIXELFORMAT_RGBX4444` as for the correct name.

**Comment by ell1e** [comment]
Thinking more about the little endian byte order, I think it should be:

`SDL_PIXELFORMAT_RGB444` is actually `SDL_PIXELFORMAT_XBGR4444` *(little endian, byte with lower address is the latter one in the name, and higher precedence 4-bit channel comes first consistent with a left-to-right read of a single byte)*

`SDL_PIXELFORMAT_XRGB4444` should map to a different format than it is right now, it doesn't map to one where `XR` are even paired, so I don't understand how that goes where it does at all.

`SDL_PACKEDORDER_XRGB` also seems to be wrong, since it also doesn't seem to map to a format right now where `XR` are on the same byte.

And `SDL_PIXELFORMAT_RGB444` should be a 12-bit format instead.

**Comment by ell1e** [comment]
My apologies again for the confusion. Just as a heads up I heavily edited all my previous comments and tried to add really in-depth reasoning so that hopefully it's correct now. In any case, it seems to me like no matter how it's looked at, the format names should be different.

**Comment by ell1e** [comment]
Maybe it would be useful to rename these with the release of SDL3? So that people use the correct names from then on.

**Comment by slouken** [comment]
The packed formats are always packed using bit operations on native integral types, and are sized to the nearest byte.

For example an `SDL_PIXELFORMAT_RGB555` pixel is composed of the 5 bit channel values assembled like so:
`R << 10 |  G << 5 | B`

The pixel format `SDL_PIXELFORMAT_RGB444` is composed of the 4 bit channel values assembled like so:
`R << 8 | G << 4 | B`

SDL_PIXELFORMAT_RGB444 is already an alias for the more correctly named `SDL_PIXELFORMAT_XRGB4444`, which fully indicates a 16-bit value with the upper 4 bits unused.

I looked at removing these shorter aliases, but it doesn't seem valuable to make the API more verbose in this case, when you can look at the header and easily see how they're encoded. If that's still confusing to you, please feel free to make a PR with better documentation, and this will be automatically bridged to the Wiki.

**Comment by ell1e** [comment]
Thanks for looking at this! For what it's worth, personally I think it might be better to remove the shorter aliases. They seem to mostly have the potential for confusion, while not usefully saving much letters to type. I doubt it's obvious to most user which ones are "weirdly" named short hands and which ones are the "true" names, and having to look at the actual header to figure that out seems like not a good use of everyone's time.

**Comment by ell1e** [comment]
If you're curious since my old comment also indicated a wrong order, I double checked and it seems to be fine. To document for others

Test for `XRGB4444`, expected behavior is a cyan square, which works:
```
#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdint.h>

int main(int argc, const char **argv) {
    SDL_Window *window = NULL;
    if (SDL_Init(SDL_INIT_VIDEO) < 0) return 1;
    window = SDL_CreateWindow("Test",
        SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
        200, 200, SDL_WINDOW_SHOWN);
    if (window == NULL) return 1;
    SDL_Renderer *renderer = SDL_CreateRenderer(
        window, -1, 0
    );
    if (renderer == NULL) return 1;

    SDL_Surface *srf = SDL_CreateRGBSurfaceWithFormat(
        0, 200, 200, 16, SDL_PIXELFORMAT_XRGB4444
    );
    if (srf == NULL) return 1;
    SDL_LockSurface(srf);
    uint8_t *writep = srf->pixels;
    uint32_t y = 0;
    while (y < 200) {
        uint32_t x = 0;
        while (x < 200) {
            // For little endian, most significant is higher byte:
            *(writep + 1) = (0 << 2) | 0;  // X: 0, R: 0
            // Then follow by least significant on lower byte:
            *(writep) = (15 << 4) | 15;  // G: 15, B: 15
            writep += 2;
            x++;
        }
        writep += srf->pitch - (200 * 2);
        y++;
    }
    SDL_Texture *tex = SDL_CreateTextureFromSurface(
        renderer, srf
    );
    if (tex == NULL) return 1;

    int keeprunning = 1;
    while (keeprunning) {
        SDL_Event e;
        while (SDL_PollEvent(&e) != 0) {
            if (e.type == SDL_QUIT) {
                keeprunning = 0;
                break;
            } else if (e.type == SDL_WINDOWEVENT) {
                if (e.window.event == SDL_WINDOWEVENT_CLOSE) {
                    keeprunning = 0;
                    break;
                }
            }
        }

        SDL_RenderCopy(renderer, tex, NULL, NULL);
        SDL_RenderPresent(renderer);
    }
    return 0;
}
```
Test for `XBGR4444` where yellow would be expected, which also works:
```
#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdint.h>

int main(int argc, const char **argv) {
    SDL_Window *window = NULL;
    if (SDL_Init(SDL_INIT_VIDEO) < 0) return 1;
    window = SDL_CreateWindow("Test",
        SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
        200, 200, SDL_WINDOW_SHOWN);
    if (window == NULL) return 1;
    SDL_Renderer *renderer = SDL_CreateRenderer(
        window, -1, 0
    );
    if (renderer == NULL) return 1;

    SDL_Surface *srf = SDL_CreateRGBSurfaceWithFormat(
        0, 200, 200, 16, SDL_PIXELFORMAT_XBGR4444
    );
    if (srf == NULL) return 1;
    SDL_LockSurface(srf);
    uint8_t *writep = srf->pixels;
    uint32_t y = 0;
    while (y < 200) {
        uint32_t x = 0;
        while (x < 200) {
            // For little endian, most significant is higher byte:
            *(writep + 1) = (0 << 2) | 0;  // X: 0, B: 0
            // Then follow by least significant on lower byte:
            *(writep) = (15 << 4) | 15;  // G: 15, R: 15
            writep += 2;
            x++;
        }
        writep += srf->pitch - (200 * 2);
        y++;
    }
    SDL_Texture *tex = SDL_CreateTextureFromSurface(
        renderer, srf
    );
    if (tex == NULL) return 1;

    int keeprunning = 1;
    while (keeprunning) {
        SDL_Event e;
        while (SDL_PollEvent(&e) != 0) {
            if (e.type == SDL_QUIT) {
                keeprunning = 0;
                break;
            } else if (e.type == SDL_WINDOWEVENT) {
                if (e.window.event == SDL_WINDOWEVENT_CLOSE) {
                    keeprunning = 0;
                    break;
                }
            }
        }

        SDL_RenderCopy(renderer, tex, NULL, NULL);
        SDL_RenderPresent(renderer);
    }
    return 0;
}
```
I tried some other colors too, and it seems to work fine.
