### ISSUE TITLE
SDL_GL_MakeCurrent & Event Polling 'deadlock' in X11

### ISSUE THREAD

**Issue by esoma** [libsdl-org/SDL#4996]
This appears to only happen with X11 video systems -- I've tested on both Windows and OSX and they do not exhibit this behavior.

I don't have a simple reproducer, mostly because I'm exhausted of this problem at the moment and finally appear to have removed it from my program :smile:. But roughly, if you have a program with two threads where:
- The main thread is polling for events (`SDL_WaitEvent`)
- The other thread tries to swap GL contexts (`SDL_GL_MakeCurrent`)

The program will 'deadlock'. I put deadlock in quotes, because as soon as a user input occurs (mouse move, key press, etc) the situation resolves itself. This has been an issue for me in automated testing (since user inputs aren't there to break the deadlock) and I could imagine it causing other weird issues for multithreaded programs with multiple windows that are rendered to.

My X11 knowledge is shallow, so I can only guess at the issue (`X11_XSync`?) and I've solved it in my application for now just by synchronizing around polling calls and GL context switches which are few enough.

**Comment by cgutman** [comment]
I think this is a duplicate of #4928 which is already fixed. Does this reproduce with the latest source?

**Comment by esoma** [comment]
Yes that fixes it, thanks!
