### ISSUE TITLE
SDL_VideoInit does not cleanup after itself on failure

### ISSUE THREAD

**Issue by esoma** [libsdl-org/SDL#5000]
Similar to #4826, `SDL_VideoInit` doesn't cleanup after itself if failure occurs prior to the video driver being created (for example the events subsystem will remain initialized if no video device is available, even after the changes from #4834).

**Comment by slouken** [comment]
Fixed with https://github.com/libsdl-org/SDL/commit/71e3998d6c0b0742bc0042894ea8327aadae811a, thanks!
