### ISSUE TITLE
CMAKE_COMPILER_IS_MINGW no longer supported in CMake

### ISSUE THREAD

**Issue by bscottm** [libsdl-org/SDL#5002]
I have a CMake superbuild that compiles SDL2 when needed, usually on Windows platforms. Somewhere between CMake 3.21 and 3.22, the CMAKE_COMPILER_IS_MINGW and CMAKE_COMPILER_IS_CYGWIN variables were dropped. The impact: Builds break because SDL2 will complain that it needs the DXDEV_DIR environment set to find DirectX, even though it's not applicable to MinGW builds.

Q: Propose a patch? (Note: I've got a question with Kitware open to get the "proper" workaround that's backwardly compatible.)

**Comment by bscottm** [comment]
`CMAKE_COMPILER_IS_MINGW` is an undocumented variable that was recently removed as the result of Kitware code cleanup. PTF.

**Comment by sezero** [comment]
@icculus, @slouken: we need the following - @bscottm: it's correct yes?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e8963a2..8a755c6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1519,7 +1519,7 @@ elseif(WINDOWS)
     if(DEFINED MSVC_VERSION AND NOT ${MSVC_VERSION} LESS 1700)
         set(USE_WINSDK_DIRECTX TRUE)
     endif()
-    if(NOT CMAKE_COMPILER_IS_MINGW AND NOT USE_WINSDK_DIRECTX)
+    if(NOT MINGW AND NOT USE_WINSDK_DIRECTX)
       if("$ENV{DXSDK_DIR}" STREQUAL "")
         message_error("DIRECTX requires the \$DXSDK_DIR environment variable to be set")
       endif()
@@ -1537,7 +1537,7 @@ elseif(WINDOWS)
     check_include_file(dxgi.h HAVE_DXGI_H)
     if(HAVE_D3D_H OR HAVE_D3D11_H OR HAVE_DDRAW_H OR HAVE_DSOUND_H OR HAVE_DINPUT_H)
       set(HAVE_DIRECTX TRUE)
-      if(NOT CMAKE_COMPILER_IS_MINGW AND NOT USE_WINSDK_DIRECTX)
+      if(NOT MINGW AND NOT USE_WINSDK_DIRECTX)
       # TODO: change $ENV{DXSDL_DIR} to get the path from the include checks
         target_link_directories(sdl-build-options INTERFACE "$$ENV{DXSDK_DIR}\\lib\\${PROCESSOR_ARCH}")
         target_include_directories(sdl-build-options INTERFACE "$ENV{DXSDK_DIR}\\Include")
```

**Comment by icculus** [comment]
`MINGW` is new in CMake 3.2, newer than we require. Should we check if the old variable is defined and set MINGW ourselves if so?

**Comment by sezero** [comment]
> `MINGW` is new in CMake 3.2, newer than we require.

Do you have a reference for it? My old cmake-2.8.12 does seem to define it.

**Comment by bscottm** [comment]
`MINGW` exists in 3.11, which is the minimum that SDL2 requires.

Re the diff: Yes, that looks correct. That's what I was going to propose.

**Comment by sezero** [comment]
OK -- Waiting for approval to push.

**Comment by sezero** [comment]
> Our CMake required version is 3.0.0. We dialed it back recently so older Linux distros were more likely to have a supported version.

That's OK, although `MINGW` is, as far as I know, older than cmake3
and even older than cmake2.8. See e.g.:
https://www.openguru.com/2009/04/cmake-detecting-platformoperating.html
https://cmake.org/pipermail/cmake/2005-November/007510.html
Those are from 2005 and 2009, way before cmake3.0 came to life.

One nit I can think of would be, should we consider checking `MSYS`
alongside `MINGW`, and if yes in which way in our cmake file?

**Comment by icculus** [comment]
Ah, their docs say it's new in 3.2:

https://cmake.org/cmake/help/latest/variable/MINGW.html

...but apparently that's a typo. Okay, safe to push.

(We can hold off on MSYS for now unless you feel strongly about adding it.)

**Comment by sezero** [comment]
>   Okay, safe to push.

Done -- https://github.com/libsdl-org/SDL/commit/d9f70878f9fb531c5a9fc7adfa1fda456b77010c

> (We can hold off on MSYS for now unless you feel strongly about adding it.)

I don't  :)
