### ISSUE TITLE
No rumble on Win10 with G-Shark GS-GP702 controllers.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5009]
> I also have the same problem (with current source code version) on Win10 with my G-Shark GS-GP702 controllers. Mine are branded Jite, model KD-890 Double Shock2. 
Product ID = 6
Vendor ID = 121
Guid = 03000000790000000600000000000000
>
> Here are the problems I'm having:
>
> 1. They're supposed to have rumble, but SDL is reporting no rumble.

__Originally posted by @AntTheAlchemist in https://github.com/libsdl-org/SDL/issues/5006#issuecomment-979669498__

**Comment by slouken** [comment]
@AntTheAlchemist, can I borrow your controllers to see what's going on here?

**Comment by AntTheAlchemist** [comment]
@slouken very sorry for the late reply - I've had a few personal problems. Mine are similar Ryan's "Jite CN-2021 Double Shock2". They're cheap and nasty and personally I don't think they're worth worrying about. I have 4 of them I don't and I'm happy to send you one to keep. If you're interested then inbox me your address and I'll get it over to you. I'll be mailing it from the UK.

**Comment by slouken** [comment]
Sure, send me e-mail at slouken@libsdl.org and I'll send you my address.

Thanks!

**Comment by slouken** [comment]
@AntTheAlchemist, did you ever send me one of those controllers? I'm not seeing any e-mail from you about it.

**Comment by AntTheAlchemist** [comment]
@slouken I did, right after getting your address in email last year. I remember cursing because the international shipping cost 10 x more than the controller 😢

These controllers are cheap & nasty; at least mine is. I cannot get the rumble to work anywhere, in any game or test app. So it's a Windows driver issue? I'm happy to close this bug.

**Comment by slouken** [comment]
Man, I'm sorry. I'm sure I have it around here somewhere. I'll go ahead and close this bug for now though.
