### ISSUE TITLE
Mac framework does not include SDL_hidapi.h - 2.0.18 Prerelease

### ISSUE THREAD

**Issue by RustyMoyher** [libsdl-org/SDL#5015]
Checking out the [Nov 26 Prerelease](https://discourse.libsdl.org/t/sdl-2-0-18-prerelease/33717) of 2.0.18, I'm not seeing the new SDL_hidapi.h file in the Mac SDL2.frameworks under headers. This is from the SDL2-2.0.18.dmg pre-compiled download.

**Comment by slouken** [comment]
Fixed, thanks!
