### ISSUE TITLE
WinRT not building from error in sdl_winrtvideocpp - 2.0.18 Prerelease

### ISSUE THREAD

**Issue by RustyMoyher** [libsdl-org/SDL#5016]
WinRT (UWP) is not building in the [Nov 26 Prerelease of 2.0.18](https://discourse.libsdl.org/t/sdl-2-0-18-prerelease/33717). The build fails on line 701 in sdl_winrtvideo.cpp. I think it's a simple cast issue? The eglCreateWindowSurface() call is expecting a NativeWindowType, but instead we're passing in a IInspectable. Here's the error:

```
Severity Code Description Project File Line Suppression State
Error C2664 'EGLSurface (EGLDisplay,EGLConfig,NativeWindowType,const EGLint *)': cannot convert argument 3 from 'IInspectable *' to 'NativeWindowType' SDL2-UWP c:\projects\sdl\src\video\winrt\sdl_winrtvideo.cpp 701 
```

**Comment by slouken** [comment]
Fixed by https://github.com/libsdl-org/SDL/commit/11a9cd6344f30055c5730f01bcab141e13151f45, thanks!
