### ISSUE TITLE
`TextInputEvent` chokes on £ symbol

### ISSUE THREAD

**Issue by chrisnorman7** [libsdl-org/SDL#5028]
Hi,
I am making bindings for SDL, and when I trigger a `TextInputEvent` by pressing the shift and 3 key combination on my UK keyboard, SDL sends the following characters: `[-62, -93]`

Is this a bug? Or am I supposed to be able to do something with them? Dart's [Utf8Codec](https://api.dart.dev/stable/2.14.4/dart-convert/Utf8Codec-class.html) doesn't like them:

```shell
Unhandled exception:
FormatException: Invalid UTF-8 byte (at offset 0)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
#3      Sdl.pollEvent (package:dart_sdl/src/sdl.dart:787:59)
#4      Sdl.getEvents (package:dart_sdl/src/sdl.dart:986:21)
<asynchronous suspension>
#5      main (file:///C:/Users/chris/src/dart_sdl/example/event_example.dart:6:3)
<asynchronous suspension>
```

I could allow malformed sequences, but the pound symbol is pretty standard here in the UK, and it can't be the only sequence that gets messed up.

Any help would be appreciated, and sorry if I'm doing something wrong.

Thanks in advance. I'm using SDL version `2.0.14`.

**Comment by chrisnorman7** [comment]
Just checked with version 2.0.16, and the behaviour is still the same. I'm using Windows 10 if that matters.

**Comment by cgutman** [comment]
Can you try with the 2.0.18 RC?

https://www.libsdl.org/tmp/download-2.0.php

**Comment by slouken** [comment]
That is the correct UTF-8 for the £ symbol, you can check it here:
https://convertcodes.com/unicode-converter-encode-decode-utf/

It results in the two byte sequence 0xc2,0xa3, which when you print it out as signed characters becomes -62,-93
UTF-8 is generally unsigned characters, so maybe you're converting the values to integer before passing them to Utf8Codec?

**Comment by chrisnorman7** [comment]
@cgutman I will do, unless it turns out my understanding of UTF8 is flawed.

@slouken Ah, thank you, that is interesting. I wonder why the Dart converter is choking on it?

As it is clearly not a bug in SDL (it's returning proper characters), I'll close this now, and dig more into Dart's UTF8 converters.

Thank you both for your input and help.

**Comment by slouken** [comment]
You're welcome!

**Comment by chrisnorman7** [comment]
For the sake of posterity, I fixed the problem by checking each number I
received from SDL and adding 256 where the number was negative. This works
now.

Take care,

Chris Norman
