### ISSUE TITLE
Latest main branch SDL crashes when rotating display when using wayland

### ISSUE THREAD

**Issue by mlehtima** [libsdl-org/SDL#5030]
Rotating display in Sailfish OS when using latest main branch SDL causes the app to crash after second rotation.

During the first rotation SDL_ResetDisplayModes is called in display_handle_geometry (https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c#L307) which calls SDL_free(display->display_modes[i].driverdata) (https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L872) but in wayland backend mode->driverdata is assigned a pointer to wl_output (https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c#L439 and https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.h#L94) and later calls to any of the callbacks in wl_output_listener will cause critical failure because the wl_output is no longer valid.

After removing the call to SDL_free(display->display_modes[i].driverdata) app won't crash anymore.

**Comment by flibitijibibo** [comment]
Should be fixed by https://github.com/libsdl-org/SDL/commit/72e53e4b87c8b0dc267cac596934e38d3068473d

**Comment by mlehtima** [comment]
I can confirm the fix in the commit above works correctly. Thanks.
