### ISSUE TITLE
Windows SDL2.0.16 Does Not Run On Linux WINE - Issue With SDL_INIT_SENSOR

### ISSUE THREAD

**Issue by FallenAngelSoftware** [libsdl-org/SDL#5031]
Hi,

The Windows version of our SDL2.0.16 game does not run on Linux WINE.
The issue is with SDL2’s sensor subsystem.

The current workaround is below:
if ( SDL_Init(SDL_INIT_TIMER|SDL_INIT_AUDIO|SDL_INIT_VIDEO|SDL_INIT_JOYSTICK|SDL_INIT_HAPTIC|SDL_INIT_GAMECONTROLLER|SDL_INIT_EVENTS) != 0 )

Little late, but was hoping this could be fixed in SDL 2.0.18 ?
Thanks!

Jesse "JeZxLee"

**Comment by slouken** [comment]
What's the issue with sensors?

**Comment by FallenAngelSoftware** [comment]
Hi Sam,

If we enable SDL2's sensor subsystem, the Windows version of our SDL2.0.16 game does not run on Linux WINE.
Game fails to "SDL_Init()" and Linux WINE closes almost immediately?

Disabling SDL_INIT_SENSOR in "SDL_Init()" allows Windows game to run on Linux WINE.


Jesse

**Comment by FallenAngelSoftware** [comment]
- Manjaro KDE 64Bit Linux OS on a custom desktop.
- Linux WINE version 6.22

**Comment by slouken** [comment]
What is the SDL error?

**Comment by slouken** [comment]
I tried running your game and got:
0035:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\home\\slouken\\projects\\TetriCrisis_4_110Percent_A.I._Turbo\\DoubleClickThisToRun.exe") not found

**Comment by FallenAngelSoftware** [comment]
Sorry about that, the game was built with MSVS19(which is new to me).
I built the Windows EXE again with Code::Blocks - should be ok now on GitHub...

**Comment by sezero** [comment]
That's the bad thing about `SDL_Init(SDL_INIT_EVERYTHING)`:
if one subsystem fails, all fail and you lose (and that is
not actually documented? maybe I'm wrong about that.)
Calling `SDL_Init()` for every wanted subsystem separately
in an as-needed way solves many things.

**Comment by FallenAngelSoftware** [comment]
How to get error if "SDL_Init()" fails?

**Comment by slouken** [comment]
SDL_Log("SDL_Init() failed: %s\n", SDL_GetError());

**Comment by FallenAngelSoftware** [comment]
Error is below:

![image](https://user-images.githubusercontent.com/35844132/143801900-cd0f745e-791f-435f-8e91-fc5437fad77f.png)

**Comment by slouken** [comment]
In general you should only initialize subsystems that you need for your application, but SDL_Init(SDL_INIT_EVERYTHING) shouldn't fail on Wine anymore.

Thanks!
