### ISSUE TITLE
Fullscreen behavior is still broken on Windows

### ISSUE THREAD

**Issue by StanleySweet** [libsdl-org/SDL#5033]
Hi the alt tabbing behavior is still broken in 2.0.16 which means 0 A.D. is stuck on 2.0.12 on Windows. See the following video for the bug

https://user-images.githubusercontent.com/6837402/143846036-f9ed21f5-cd83-49a4-bf33-9da9c64ca34d.mp4

Original thread

https://wildfiregames.com/forum/topic/49785-building-a-64-bit-pyrogenesis-and-deps-for-windows/?do=findComment&comment=452168

**Comment by cgutman** [comment]
It is related to this change in the 2.0.14 changelog:
> The default value for SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS is now false for better compatibility with modern window managers

That behavior was tweaked again with #4039 in SDL 2.0.16 but it only minimizes for `SDL_WINDOW_FULLSCREEN` mode and I see 0AD uses `SDL_WINDOW_FULLSCREEN_DESKTOP` instead.

We should probably figure out why that's not working as expected, but you can easily work around the issue by calling `SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "1")` in your game.

**Comment by AntTheAlchemist** [comment]
I'm not seeing the same thing happen with 2.0.18 using a basic test case.

**Comment by StanleySweet** [comment]
> I'm not seeing the same thing happen with 2.0.18 using a basic test case.

What OS are you using?



> It is related to this change in the 2.0.14 changelog:
> 
> > The default value for SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS is now false for better compatibility with modern window managers
> 
> That behavior was tweaked again with #4039 in SDL 2.0.16 but it only minimizes for `SDL_WINDOW_FULLSCREEN` mode and I see 0AD uses `SDL_WINDOW_FULLSCREEN_DESKTOP` instead.
> 
> We should probably figure out why that's not working as expected, but you can easily work around the issue by calling `SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "1")` in your game.

Good to know there is a workaround :) It would be nice for us to be able to update :)

**Comment by AntTheAlchemist** [comment]
> What OS are you using?

Windows 10 Pro 21H2

**Comment by StanleySweet** [comment]
Did you use SDL_WINDOW_FULLSCREEN_DESKTOP in your basic test case?

**Comment by AntTheAlchemist** [comment]
> Did you use SDL_WINDOW_FULLSCREEN_DESKTOP in your basic test case?

Yep yep:

```
	SDL_Window* w = SDL_CreateWindow(nullptr, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, SDL_WINDOW_FULLSCREEN_DESKTOP);
	SDL_Renderer* r = SDL_CreateRenderer(w, -1, SDL_RENDERER_PRESENTVSYNC);
```

Not rendering anything, just clearing and presenting. I *have* seen the behaviour before, which is shown in your video. 

Have you tried the latest 2.0.18? Can you reproduce it with a very basic game loop?

**Comment by StanleySweet** [comment]
Only 2.0.16 which was used for the video, I will try the game with 2.0.18.

**Comment by AntTheAlchemist** [comment]
> EDIT: It's not out yet?

It's out on pre-release [](https://www.libsdl.org/tmp/download-2.0.php)

^ mentioned on the SDL2 Forums: [](https://discourse.libsdl.org/t/sdl-2-0-18-prerelease/33717 )

**Comment by StanleySweet** [comment]
Just tested with 2.0.18 the behavior is slightly different in the sense that I can see my desktop, however if I click on it, it opens 0 A.D. 

The only thing that restores the behavior is SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "1")

**Comment by AntTheAlchemist** [comment]
Does 0 A.D. halt the rendering loop when it loses focus or something? It sounds like you're seeing your desktop because the game becomes transparent. The game should remain visible in the background, covering your desktop, so when you click on the background, you'll return to the game - which is happening. Just guessing wildly here.

**Comment by StanleySweet** [comment]
Well that's what happens with 2.0.16 and 2.0.14 but not 2.0.18 so maybe something changed? I believe it continues rendering in the background.

**Comment by cgutman** [comment]
Adding to the 2.0.20 milestone for investigation

**Comment by slouken** [comment]
Can you double check with the latest code? I may have fixed this in https://github.com/libsdl-org/SDL/commit/d40627851301aabf76a1d8acec7edb9ad675042d.

**Comment by StanleySweet** [comment]
Do you have a test build I could use?

**Comment by slouken** [comment]
Here you go:
https://www.libsdl.org/tmp/SDL.zip

**Comment by StanleySweet** [comment]
I need the lib files / headers as well to link with 0 A.D. Hope you don't mind...

**Comment by slouken** [comment]
You can use the 2.0.18 headers and libs:
https://www.libsdl.org/download-2.0.php

**Comment by StanleySweet** [comment]
Thanks, I tried it out today and it seemed to work!  No longer have it in the background when alt tabbing.
- Patched the headers and .lib
- Added the SDL2.dll you provided
- Removed `SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "1");` from our code.
- Compiled
- Started the game
- Windows + D
- Noticed the window was no longer in the background.

**Comment by slouken** [comment]
Great, thanks!
