### ISSUE TITLE
Missing input mapping for touchpad button (PS4)

### ISSUE THREAD

**Issue by DrRevert** [libsdl-org/SDL#5035]
It seems that currently for Windows platform there's no binding for SDL_CONTROLLER_BUTTON_TOUCHPAD on PS4 dualshock. This particular field seems to be missing from the gamecontrollerdb for some reason. And the example program controllermap.c which can be used to generate the binding string omits checking for SDL_CONTROLLER_BUTTON_TOUCHPAD.

TBH I'm not entirely sure if SDL doesn't perform some adhoc inclusion of the touchpad button as I have noticed the issue in other open source project (Godot) which only uses the mapping without integrating rest of the SDL (mapping in question https://github.com/gabomdq/SDL_GameControllerDB)

I tried to report the issue there https://github.com/gabomdq/SDL_GameControllerDB/issues/520#issuecomment-981225072 but basically got the answer that SDL_GameControllerDB doesn't want to diverge from SDL mapping and to fix it locally for the one project, even the issue seems to be global.

**Comment by offalynne** [comment]
> TBH I'm not entirely sure if SDL doesn't perform some adhoc inclusion of the touchpad button

if you read the reply to the issue you opened in the other repo you would have seen that it does.

> (Godot) which only uses the mapping without integrating rest of the SDL

your issue is with Gadot. file your complaint there.

**Comment by madmiraal** [comment]
@slouken b6bc3a6b0e435eae7340acc5d51ec05d7f21505e fixed this for PS4s with GUID 030000004c050000c405000000000000. Can the same be done for PS4s with GUID 030000004c050000cc09000000000000, which, as reported downstream: https://github.com/godotengine/godot/issues/55448, is the GUID for @DrRevert's PS4?
