### ISSUE TITLE
Y axis of right analog is not detected

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [libsdl-org/SDL#5037]
Hi!
I have Genesis Mangan 200 controller and i've tried to use it with RetroArch (linux) and xemu emulator (windows). On both they could not detect any movement of Y axis of my controller. When i turn off analog mode it detects Y axis as top/bottom  and X axis as left/right buttons. I am using Windows 11 as daily OS so i cannot change controller driver to linuxraw or other that worked with my gamepad.

**Comment by AntTheAlchemist** [comment]
This is fixed #5006 
I googled your controller and it looks identical to the G-Shark GS-GP702. Try 2.0.18. You'll also notice the SDL_Joystick events for the Y-axis still come through, it's just the mapping was broken for that axis.
