### ISSUE TITLE
autotools: upgrade to libtool-2.4.6 ?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5040]
If there is interest, I can do this for 2.0.20 (and also in the satellite projects.)

**Comment by icculus** [comment]
2.4.6 was released February 2015 and hasn't been updated since.

https://pkgs.org/search/?q=libtool  suggests that most things have been on it for a long time. I think I'm okay with this?

**Comment by sezero** [comment]
OK, will work on it after 2.0.18 ships.

**Comment by sezero** [comment]
See the 'autofoo' branch in my fork, here: https://github.com/libsdl-org/SDL/compare/main...sezero:autofoo
I can merge after 2.0.18 is released if you don't see any problems.

**Comment by sezero** [comment]
@slouken, @icculus: please review https://github.com/libsdl-org/SDL/compare/main...sezero:autofoo

**Comment by sezero** [comment]
I take that emoji reaction as OK, so applied the patchset. If there are any issues, drop a note here.

**Comment by slouken** [comment]
Thank you!

**Comment by sezero** [comment]
> Thank you!

Well, no cigar yet:

In my cross-build environment on linux, SDL_net and SDL_image test programs
(showinterfaces.exe of SDL_net, showanim.exe and showimage.exe of SDL_image)
fail linkage because of func_convert_path_nix_to_w32 (I guess), errors are:
```
$ pwd
/home/ozzie/11/SDL_image/b

$ PATH=/opt/cross_win64/bin:$PATH PKG_CONFIG_PATH=/home/ozzie/x86_64-w64-mingw32/lib/pkgconfig ../configure --prefix=/home/ozzie/z99 --host=x86_64-w64-mingw32 --disable-webp --disable-png
[....]
/bin/sh ./libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc  -g -O2 -Dmain=SDL_main -I/home/ozzie/x86_64-w64-mingw32/include/SDL2     -o showimage.exe showimage.o libSDL2_image.la -mwindows -L/home/ozzie/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2  
libtool: link: x86_64-w64-mingw32-gcc -g -O2 -Dmain=SDL_main -I/home/ozzie/x86_64-w64-mingw32/include/SDL2 -o .libs/showimage.exe showimage.o -mwindows  ./.libs/libSDL2_image.dll.a -L/home/ozzie/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -L/home/ozzie/z99/lib
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/home/ozzie/11/SDL_image/b/.libs'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/home/ozzie/x86_64-w64-mingw32/lib:/home/ozzie/x86_64-w64-mingw32/bin:/home/ozzie/11/SDL_image/b/.libs:/home/ozzie/z99/lib:/home/ozzie/z99/bin'
libtool:   error: Continuing, but uninstalled executables may not work.
/opt/cross_win64/lib/gcc/x86_64-w64-mingw32/4.5.4/../../../../x86_64-w64-mingw32/lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':
/home/ozzie/Downloads/W64_4.5_189152-src/build-crt/../mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2: ld returned 1 exit status
x86_64-w64-mingw32-strip: './showimage.exe': No such file
/bin/sh ./libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc  -g -O2 -Dmain=SDL_main -I/home/ozzie/x86_64-w64-mingw32/include/SDL2     -o showanim.exe showanim.o libSDL2_image.la -mwindows -L/home/ozzie/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2  
libtool: link: x86_64-w64-mingw32-gcc -g -O2 -Dmain=SDL_main -I/home/ozzie/x86_64-w64-mingw32/include/SDL2 -o .libs/showanim.exe showanim.o -mwindows  ./.libs/libSDL2_image.dll.a -L/home/ozzie/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -L/home/ozzie/z99/lib
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/home/ozzie/11/SDL_image/b/.libs'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/home/ozzie/x86_64-w64-mingw32/lib:/home/ozzie/x86_64-w64-mingw32/bin:/home/ozzie/11/SDL_image/b/.libs:/home/ozzie/z99/lib:/home/ozzie/z99/bin'
libtool:   error: Continuing, but uninstalled executables may not work.
/opt/cross_win64/lib/gcc/x86_64-w64-mingw32/4.5.4/../../../../x86_64-w64-mingw32/lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':
/home/ozzie/Downloads/W64_4.5_189152-src/build-crt/../mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2: ld returned 1 exit status
x86_64-w64-mingw32-strip: './showanim.exe': No such file
```

Manually running the gcc command links successfully, but because libtool is
getting in the way badly, it fails. I can _happily? go back to 2.4.2 or 2.2.6
in those ones if necessary.

Curiously, the test programs of SDL_mixer link successfully, but that's 
probably because, unlike others, SDL_mixer doesn't use automake.

@icculus, @slouken: Advise.

**Comment by sezero** [comment]
Seems like 2.4.2 (copied over from SDL2-2.0.18) behaves in the
same bad way.  Looking at SDL_image history, you noted that a
libtool update broke cross-compiling to Windows and reverted it:
https://github.com/libsdl-org/SDL_image/commit/39a3edae58e6c3d5e1a1ceeae818eeb6f6056209

So, going back to 2.2.6 seems to be the safest way, at least for
SDL_image, SDL_ttf, SDL_net and SDL_rtf which has test programs
_and_ use automake.

As for SDL_mixer, we can stay at 2.4.6 (it does compile its test
programs OK), or we can go back to 2.2.6 for sake of symmetry.

@icculus, @slouken: Waiting for advise.

**Comment by slouken** [comment]
Let's keep all of them on the same version of libtool.

**Comment by sezero** [comment]
> Let's keep all of them on the same version of libtool.

OK, then I will go back to 2.2.6 for all of the satellite projects:
Confirm?

What about the main SDL project? Keep the 2.4.6 upgrade? (It
does't seem to have issues. But if you want I can take it back to
2.4.2)

**Comment by sezero** [comment]
> Well, no cigar yet:
> 
> In my cross-build environment on linux, SDL_net and SDL_image test programs (showinterfaces.exe of SDL_net, showanim.exe and showimage.exe of SDL_image) fail linkage because of func_convert_path_nix_to_w32 (I guess), 

Issue possibly have started with this mainstream libtool commit:
http://git.savannah.gnu.org/gitweb/?p=libtool.git;a=commit;h=ac40b5f37ae68a7b4a254e43364e2d297f563310

> OK, then I will go back to 2.2.6 for all of the satellite projects: Confirm?
> 
> What about the main SDL project? Keep the 2.4.6 upgrade? (It does't seem to have issues. But if you want I can take it back to 2.4.2)

@slouken: Awaiting your response.

**Comment by slouken** [comment]
We can keep 2.4.6 for the main SDL library, that's fine.

**Comment by sezero** [comment]
Went back to libtool-2.2.6a for all satellite projects for the time being.
