### ISSUE TITLE
Segmentation fault on SDL_SetRenderDrawColor

### ISSUE THREAD

**Issue by undefinedmain** [libsdl-org/SDL#5047]
Segmentation fault on SDL_SetRenderDrawColor. 
Source code: https://github.com/undefinedmain/sdl2_issue
I am compiling this on Android using Termux

**Comment by slouken** [comment]
Do you have a call stack?

**Comment by undefinedmain** [comment]
This is output from gdb:


Starting program: /data/data/com.termux/files/home/projects/sdl2_issue/target/release/sdl2_issue
warning: .dynamic section for "/data/data/com.termux/files/home/projects/sdl2_issue/target/release/sdl2_issue" is not at the expected address (wrong library or version mismatch?)

Program received signal SIGSEGV, Segmentation fault.
0xb6872cd8 in ?? () from /data/data/com.termux/files/usr/lib/libSDL2-2.0.so.0.10.0
(gdb) bt
#0  0xb6872cd8 in ?? () from /data/data/com.termux/files/usr/lib/libSDL2-2.0.so.0.10.0
#1  0xb68611a6 in ?? () from /data/data/com.termux/files/usr/lib/libSDL2-2.0.so.0.10.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

> Do you have a call stack?

**Comment by slouken** [comment]
You might need to create a debug build of your application and SDL to get a good stack trace.

**Comment by 1bsyl** [comment]
@undefinedmain 
could this be the stack size ?
change 
`char grid[grid_width][grid_height];`
 to a SDL_malloc ?

and/or, which SDL version this on Termux ?

**Comment by undefinedmain** [comment]
> @undefinedmain could this be the stack size ? change `char grid[grid_width][grid_height];` to a SDL_malloc ?
> 
> and/or, which SDL version this on Termux ?

I don't think the problem is in the stack size, since the grid size is 64kb, while the stack size in my case should be 8mib. In addition, I know exactly SDL_SetRenderDrawColor is causing the Segmentation fault (thanks to printf's). But actually I don't quite understand exactly how the Segmentation fault works, so I could be wrong. SDL version is 2.0.10-25

**Comment by 1bsyl** [comment]
can you give a try anyway, because 
SDL_SetRenderDrawColor sound really safe:

```
int
SDL_SetRenderDrawColor(SDL_Renderer * renderer,
                       Uint8 r, Uint8 g, Uint8 b, Uint8 a)
{
    CHECK_RENDERER_MAGIC(renderer, -1);

    renderer->color.r = r;
    renderer->color.g = g;
    renderer->color.b = b;
    renderer->color.a = a;
    return 0;
}
```

**Comment by undefinedmain** [comment]
> @undefinedmain
> 
> can you give a try anyway, because SDL_SetRenderDrawColor sound really safe:
> 
> ```
> int
> SDL_SetRenderDrawColor(SDL_Renderer * renderer,
>                        Uint8 r, Uint8 g, Uint8 b, Uint8 a)
> {
>     CHECK_RENDERER_MAGIC(renderer, -1);
> 
>     renderer->color.r = r;
>     renderer->color.g = g;
>     renderer->color.b = b;
>     renderer->color.a = a;
>     return 0;
> }
> ```

I have no idea how (my stack size is really 8mb, no matter how much I check, and the grid size should be 64kb), but it worked. Thanks!

**Comment by 1bsyl** [comment]
it sounds strange...
maybe you can decrease also  grid_width and grid_height to see when that happens

**Comment by undefinedmain** [comment]
> it sounds strange... maybe you can decrease also grid_width and grid_height to see when that happens

It doesn't work even with grid_width = 8 and grid_height = 8. But with grid_width = 1 and grid_height = 1 it works

**Comment by undefinedmain** [comment]
> it sounds strange... maybe you can decrease also grid_width and grid_height to see when that happens

Oh, I just saw that it still does not work even with a size of 1 * 1. It's just that the Segmentation fault is displayed after a longer period of time than with a size of 256 * 256

**Comment by 1bsyl** [comment]
sounds like a compiler issue when using variable length array ... maybe report this to Termux
maybe change the compiler flags to -O0
