### ISSUE TITLE
Add a hint to implicitly capture the mouse when the mouse button is down.

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#5050]
People expect the mouse to be implicitly captured when the mouse button is down. Let's go ahead and add a hint for this behavior.

Related, currently if you hold down the mouse button and move the mouse quickly out of the window, on Windows you won't get a mouse leave event until you release the mouse button and move the mouse. It looks like the mouse tracking API is expecting to get mouse events while the mouse button is down.

**Comment by cgutman** [comment]
This landed in 2.0.22, right @slouken?

**Comment by slouken** [comment]
Yep, it was added as `SDL_HINT_MOUSE_AUTO_CAPTURE`
