### ISSUE TITLE
SDL iOS dyld[21053]: Library not loaded: @rpath/SDL2.framework/SDL2

### ISSUE THREAD

**Issue by sidshekar** [libsdl-org/SDL#5051]
While with the new tutorial showing how to build an iOS SDL project works on the Simulator, it breaks when running on the device. (Tutorial Link: https://github.com/libsdl-org/SDL/blob/main/docs/README-ios.md)

I built a new framework-ios for the device and linked it in build-phases. But I still get the error. 

![Screen Shot 2021-12-01 at 4 14 35 PM](https://user-images.githubusercontent.com/2862097/144168717-5ffe57b9-9176-4c63-bfd7-2af49e021c12.png)

**Comment by sidshekar** [comment]
Even on the simulator. It works on it when you run the application from Xcode on the simulator. Once you close the app and run it again on the simulator it crashes.

![Screen Shot 2021-12-01 at 5 28 12 PM](https://user-images.githubusercontent.com/2862097/144171874-d2cb64e8-5489-4cdf-a9ef-3a9e60897bf7.png)

**Comment by sidshekar** [comment]
After much toiling around found how to embed the sdl framework in the build.

Make sure in MainProject->Build Settings->Linking->Runpath search paths is set to @executable_path/Frameworks

![Screen Shot 2021-12-01 at 6 17 49 PM](https://user-images.githubusercontent.com/2862097/144176229-8c8d7ee0-bee8-4d44-b611-a2cb17be9dcb.png)

Next in MainProject->General->Frameworks, Libraries and Embedded Content, make sure the SDL2.framework is added and is set to Embed & Sign.

![Screen Shot 2021-12-01 at 6 19 29 PM](https://user-images.githubusercontent.com/2862097/144176377-5daba617-e1a6-4097-b35e-ea62095c0147.png)

Now the framework will be embedded in the project in both Simulator as well as Device when you build and run. 

![Screen Shot 2021-12-01 at 6 21 53 PM](https://user-images.githubusercontent.com/2862097/144176580-fb552d0b-b654-4425-bf1f-8d1f0d8a103a.png)

And the app will work even after closing and reopening it.

![Screen Shot 2021-12-01 at 6 20 47 PM](https://user-images.githubusercontent.com/2862097/144176482-9be7e2a0-24b9-447a-8349-9b3b20b84d1a.png)

**Comment by slouken** [comment]
There's a better way, that I added to the documentation:
Select the project in the main view, go to the "General" tab, scroll down to "Frameworks, Libraries, and Embedded Content", and select "Embed & Sign" for the SDL library.

**Comment by sidshekar** [comment]
Ya thanks! That's what I have mentioned as the solution. Regards.
