### ISSUE TITLE
SDL 2.0.18 don't build on Android with CMake

### ISSUE THREAD

**Issue by DarkContact** [libsdl-org/SDL#5053]
CMake version 3.10.2

After updating, I get the following build errors:

> In file included from ...\SDL\src\core\android\SDL_android.c:41:
> ...\SDL\src\video\android\SDL_androidwindow.h:40:5: error: unknown type name 'EGLSurface'; did you mean 'SDL_Surface'?
> In file included from ...\SDL\src\core\android\SDL_android.c:41:
> ...\SDL\src\video\android\SDL_androidwindow.h:41:5: error: unknown type name 'EGLContext'
> 
> ...\SDL\src\core\android\SDL_android.c:1010:34: error: use of undeclared identifier 'EGL_NO_SURFACE'

I found that this happens after the commit 7850d0cf6fa1b2e7d8999d0506bb907ae071f497

**Comment by 1bsyl** [comment]
@DarkContact 
I'm not using cmake for android, but what's the fastest way to get android compiling with cmake ?

otherwise you can try to spot why it's not defined.
adding some trace macro in that file
`#error  SomeTrace`
to see what gets compiled or not


src/video/android/SDL_androidwindow.h
includes 
src/video/SDL_egl_c.h
which includes
include/SDL_egl.h
which defines the type EGLSurface

**Comment by 1bsyl** [comment]
Also, can you give the output of CMake, what it finds ?
do you have local changing maybe ?

**Comment by 1bsyl** [comment]
@DarkContact  I gave another try, and it seems to compile and find the correct header for EGLSurface
(using this: https://stackoverflow.com/questions/67729247/build-cmake-library-without-android-studio-by-command-line-or-gui/67729248#67729248 )

**Comment by DarkContact** [comment]
@1bsyl I use Android Studio. My environment: Windows 7 (x64), ndk-r21e

I am trying to build SDL using `add_subdirectory` in my project. Here CMake output:
[cmake_build_output.txt](https://github.com/libsdl-org/SDL/files/7643197/cmake_build_output.txt)

**Comment by 1bsyl** [comment]
not sure, but you  have
  SDL_OPENGL                  (Wanted: OFF): OFF
  SDL_OPENGLES                (Wanted: OFF): OFF
and it should be, 
  SDL_OPENGL                  (Wanted: ON): OFF
  SDL_OPENGLES                (Wanted: ON): ON
at least, you should have the Wanted ON to require opengles

**Comment by 1bsyl** [comment]
If I set to cmake  SDL_OPENGLES=OFF and SDL_OPENGL=OFF
I get the same compilation error.
clear you cmake file/cache maybe, or is this expected ?

**Comment by DarkContact** [comment]
Yes, the rendering system is disabled, I use bgfx library for render. I enabled the SDL_OPENGLES option and the build was successful. Thanks. 
But it seems a little odd that the SDL_OPENGLES option is required because I don't create an OpenGL context. I also use the hint SDL_HINT_VIDEO_EXTERNAL_CONTEX

**Comment by 1bsyl** [comment]
The android backend save/restore the context when going to background, when the activity/SurfaceView has the focus.
so I'm not how it can work without knowing of egl_surface ...
not sure how it deals with bgfx

**Comment by DarkContact** [comment]
Ok. Now it is clear.
