### ISSUE TITLE
CMake option prefix change in SDL 2.0.18 isn't documented 

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#5057]
It looks like we never documented the change in https://github.com/libsdl-org/SDL/commit/7850d0cf6fa1b2e7d8999d0506bb907ae071f497 as part of the release notes for 2.0.18. Many distros that are using CMake for SDL builds have not updated their packaging scripts for this change. In fact, it looks like more _didn't_ fix them than did going by the [Repology page for SDL2](https://repology.org/project/sdl2/versions).

Affected distro packages so far (that were easy to find packaging scripts for):
[Arch Linux](https://github.com/archlinux/svntogit-packages/commit/085ce8f0d7ebe1a5261782345e3bd3440412b8de#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a)
[CRUX 3.6](https://crux.nu/ports/crux-3.6/opt/libsdl2/Pkgfile)
[OpenMandriva](https://github.com/OpenMandrivaAssociation/SDL2/blob/master/SDL2.spec)

Even Fedora [messed it up initially](https://src.fedoraproject.org/rpms/SDL2/c/0906fd7d1c6f3d154e06e6568f9ec1c95c1f193d?branch=rawhide) for the initial build of the 2.0.18 package before [fixing it](https://src.fedoraproject.org/rpms/SDL2/c/2f6f04f449958218ed7b421533dbf584de2eb67c?branch=rawhide) shortly after.

Can we amend the release notes to add something about this?

**Comment by slouken** [comment]
Sure, although I don't know the best way to communicate this change. Want to submit a PR?

**Comment by cgutman** [comment]
Opened #5060 with some proposed wording.

In terms of communication, I guess the best we can do is update the text in the places we can still edit, like the GitHub release and Discourse release post.

**Comment by slouken** [comment]
Done!
