### ISSUE TITLE
Question: draw texture cropped by non-rectangular shape

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#5067]
Hello! Is there is a way to draw some texture being cropped with non-rectangular shape using SDL Render API? Non-rectangular shape I mean: triangle, star, circle, polygon of random shape, etc. Basic features allows to crop it with rectangular shape.

Should I make a blank texture, render desired texture on it, then, fill the shape around by transparent pixels, and draw the final texture on screen? Or there is a simpler way?

**Comment by icculus** [comment]
You can use the new SDL_RenderGeometry to draw a non-rectangular shape that has a texture mapped to it, or you could set up a texture so its alpha channel dictates any arbitrary set of pixels being lit up.

**Comment by Wohlstand** [comment]
Oh, interesting, will try. Seems I will still need to make a workaround for older SDL2 versions that don't contain this feature.
