### ISSUE TITLE
How can I get GLES2 under Raspberry X11?

### ISSUE THREAD

**Issue by Fredrum** [libsdl-org/SDL#5068]
Hello! 

I'm needing to get a successful call to eglGetCurrentDisplay() in my program and I do when it's run from CLI, ie without X11.  I then also get a opengles2  SDL render driver, which is what I want.

But on the desktop/x11 I get a regular opengl render driver and the eglGetCurrentDisplay() does not work.
I need the return for a eglCreateImageKHR() call.

This is being done on a Raspberry Pi 4b, Buster 32 bit.
SDL2 2.0.17

This is how I'm creating the SDL2 window,

```
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);//2,3
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);//0,1
	SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 1);
	SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
	SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
	SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

	SDL_Init(SDL_INIT_VIDEO);
	SDL_Window *sdl_window;

	sdl_window = SDL_CreateWindow(
		"Chiaki",         			///    const char* title
		SDL_WINDOWPOS_UNDEFINED,  	///    int x: initial x position
		SDL_WINDOWPOS_UNDEFINED,  	///    int y: initial y position
		WinWidth,                   ///    int w: width, in pixels
		WinHeight,                  ///    int h: height, in pixels
		SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE
	);
```

I think the question is, how can I get a GLES2 context in the x11 environment?

Cheers!

**Comment by Fredrum** [comment]
I seem to have managed to force gles2 even in the x11 Desktop by adding the following,

```
	SDL_Log("Available renderers:\n");
	SDL_Log("\n");
	int renderer_index = 0;
	for(int it = 0; it < SDL_GetNumRenderDrivers(); it++) {
		SDL_RendererInfo info;
		SDL_GetRenderDriverInfo(it,&info);

		SDL_Log("%s\n", info.name);

		if(strcmp("opengles2", info.name) == 0) {
			printf("Got hold of GLES2, at %d\n", it);
			renderer_index = it;
		}
	}
```
end then
`	SDL_Renderer* sdl_renderer = SDL_CreateRenderer(sdl_window, renderer_index, SDL_RENDERER_ACCELERATED);`

SDL then confirms the render driver to be 'opengles2'.

BUT, unfortunately that has not solved my problem of not getting a good return from,
`eglGetCurrentDisplay()` 

Does anyone know why that is? And how I could get it working?

Cheers

**Comment by aquawicket** [comment]
I'll port this out to the RmlUi Samples soon. But if you can dig though the Irrelevant "roll-you-own" stuff, This is testing and working on my RaspBerry Pi 4 arm32 with opengles.   SDL is using x11, so I don't use it direct.  I can't remember off the top of my head but, I kind of remember at the moment, but there was a slight gotcha issue either in the library includes or version of x11 to use.  Please bare with my on these classes. Working code,..   not safe code.  lol

relevant code
 [DKSDLWindow](https://github.com/aquawicket/DigitalKnob/tree/master/DKPlugins/DKSDLWindow)
 [DKSDLRml](https://github.com/aquawicket/DigitalKnob/tree/master/DKPlugins/DKSDLRml)

**Comment by aquawicket** [comment]
Here's a huge clue actually.   My compile of SDL is calling for OpenGL for raspberry.   Not OpenGLES.  
```
if(RASPBERRY)
	DKDEPEND(opengl)
endif()
```

**Comment by Fredrum** [comment]
Ok interesting so you're managing to get a successful return from eglGetCurrentDisplay() ?
Yes please if you can, let me know how you set that up?

**Comment by Fredrum** [comment]
Actually I'm going to split the other part of the question into its own Issue.

**Comment by aquawicket** [comment]
I did a text search for "GetCurrentDisplay" though my code base and got no hits. Looks like I'm pretty much using the SDL Renderer for everything now. Here's the code that does work for me on RaPi in case you spot something. Pardon the mess. 
 Sorry couldn't be more help.   [DKSDLWindow](https://github.com/aquawicket/DigitalKnob/tree/master/DKPlugins/DKSDLWindow) [DKSDLRml](https://github.com/aquawicket/DigitalKnob/tree/master/DKPlugins/DKSDLRml) [DKSDLCef](https://github.com/aquawicket/DigitalKnob/tree/master/DKPlugins/DKSDLCef)   Hope you crack-the-code soon.
