### ISSUE TITLE
[ios] option to have SDL_GetPrefPath return NSDocumentDirectory instead of NSApplicationSupportDirectory

### ISSUE THREAD

**Issue by AJenbo** [libsdl-org/SDL#5070]
For iOS it may well be preferable to have `SDL_GetPrefPath` point to `NSDocumentDirectory` since it allows the app to make the app data accessible to the user via iTunes transfer. This way a user can transfer save games from another platform or backup there save games.

https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/filesystem/cocoa/SDL_sysfilesystem.m#L84

For reference:
https://www.raywenderlich.com/3110-itunes-tutorial-for-ios-how-to-integrate-itunes-file-sharing-with-your-ios-app

https://developer.apple.com/documentation/bundleresources/information_property_list/uifilesharingenabled

**Comment by icculus** [comment]
We've added https://wiki.libsdl.org/SDL3/SDL_GetUserFolder since this bug report, which should cover things.

**Comment by AJenbo** [comment]
@loftafi I'm not following your point, save games are not user preferences. Additionally in my case we need the user to provide game data. Hiding this or implementing our own none standard way to do so seems like a bad idea.

**Comment by loftafi** [comment]
You asked for `SDL_GetPrefPath` to point to `NSDocumentDirectory`.

I responded by suggesting that preferences files should not return the user data (NSDocumentDirectory) folder in order to express support for the solution provided.
 
`SDL_GetUserFolder` a good solution.

**Comment by AJenbo** [comment]
Please don't comment on all resolved issues, if you think the solution is good just give it a thumbs up, like I did at the time.

> I hope you were able to get your game working.

Yeah we implemented platform specific code to get the folder.
