### ISSUE TITLE
SDL_RenderGeometryRaw() passes colors as int* instead of SDL_Color*

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#5087]
The underlying drivers reinterpret the color parameter as SDL_Color, but the function signature uses int* instead of SDL_Color.

**Comment by DanielGibson** [comment]
How could this best be fixed?
Could you just change the function signature accordingly and quickly release 2.0.20 and deprecate 2.0.18, hoping only few people (who would need to adjust their code to pass SDL_Color) use this function so far?
I *think* the old and new versions of the function should still be binary compatible, as they take pointers to data that is supposed to be identical (and C/`extern "C"` doesn't mangle the types into the function names)?

Or would it be better to give the fixed version another name (and keep the original)?
You could still add something like `#define SDL_RenderGeometryRaw SDL_RenderGeometryRaw2` to the header so new code automatically uses the fixed version of the function, but existing binaries (and `dlsym()`) will still get the original function

**Comment by slouken** [comment]
I think it's probably best to change the function signature. It'll be ABI compatible, as you mentioned, but new code will be future-proofed. We just need to figure out what the right representation is.

I'm going to close this as a duplicate of #5093.

**Comment by 1bsyl** [comment]
I've changed the prototype, it still remains ABI compatible (just tried with an example).

**Comment by 1bsyl** [comment]
I have change the sysrender protype so that backend received a SDL_Color strided array, should I modify them ? @slouken @slime73 
If so, maybe we should merge https://github.com/libsdl-org/SDL/pull/5097 first

**Comment by slime73** [comment]
I made this change last night and rebased it after you pushed yours: #5100 

I think it won't have any conflicts with #5097 so they can be merged in any order.
