### ISSUE TITLE
Bogus not correct SDL_KEYUP events on macOS for pressed GUI key and wrong GUI key state from SDL_GetModState

### ISSUE THREAD

**Issue by slajerek** [libsdl-org/SDL#5090]
SDL version 2.0.18
macOS Catalina version 10.15.7 (19H1323)

I am receiving bogus (not true) SDL_KEYUP events when the key pressed is GUI (Command, ⌘) and combined with keyup event of F3 key (mostly, but this is intermittent and sometimes happens to other keys). Wrong state of GUI key is also confirmed by SDL_GetModState.

I checked the behaviour with a simple native macOS key event loop implemented in ObjC and I do not receive such key ups there, meaning that is not a problem of the OS or system configuration.

Please check example code to reproduce this bug:

```
if (event.type == SDL_KEYDOWN || event.type == SDL_KEYUP)
{
	LOGD("ProcessEvents: %s: keysym.sym=%d", (event.type == SDL_KEYDOWN ? "KeyDown" : "KeyUp"), event.key.keysym.sym);
	
	switch(event.key.keysym.scancode)
	{
		case SDL_SCANCODE_LGUI:
			LOGD("..SDL_SCANCODE_LGUI");
			break;
		case SDL_SCANCODE_RGUI:
			LOGD("..SDL_SCANCODE_RGUI");
			break;
	}
	
	
	LOGD("keyCode=%d SDL_GetModState()=%d KMOD_GUI=%d", event.key.keysym.sym, SDL_GetModState(), ((SDL_GetModState() & KMOD_GUI) != 0));
}
```

When I press and hold the LGUI key and then press the F1, F2, F3 - when I release the F3 key then the KeyUp event is fired for F3 key, **but also for the LGUI key** even though I keep the LGUI key pressed. Following release of the LGUI key does not send event. Note, the same behaviour is for both LGUI and RGUI keys.

Below the log produced by the above code:
```
[ press and hold LGUI key ]
ProcessEvents: KeyDown: keysym.sym=1073742051
..SDL_SCANCODE_LGUI
keyCode=1073742051 SDL_GetModState()=1024 KMOD_GUI=1

[ press and release only F1 key ]
ProcessEvents: KeyDown: keysym.sym=1073741882
keyCode=1073741882 SDL_GetModState()=1024 KMOD_GUI=1
ProcessEvents: KeyUp: keysym.sym=1073741882
keyCode=1073741882 SDL_GetModState()=1024 KMOD_GUI=1

[ press and release only F2 key ]
ProcessEvents: KeyDown: keysym.sym=1073741883
keyCode=1073741883 SDL_GetModState()=1024 KMOD_GUI=1
ProcessEvents: KeyUp: keysym.sym=1073741883
keyCode=1073741883 SDL_GetModState()=1024 KMOD_GUI=1

[ press and release only F3 key. BUG!! ]
ProcessEvents: KeyDown: keysym.sym=1073741884
keyCode=1073741884 SDL_GetModState()=1024 KMOD_GUI=1
ProcessEvents: KeyUp: keysym.sym=1073741884
keyCode=1073741884 SDL_GetModState()=0 KMOD_GUI=0
ProcessEvents: KeyUp: keysym.sym=1073742051
..SDL_SCANCODE_LGUI
keyCode=1073742051 SDL_GetModState()=0 KMOD_GUI=0

[ release LGUI key - no event ]
```

**Comment by slajerek** [comment]
This is interesting issue as I debugged this further, it seems this happens only on Catalina, and not Big Sur. And also only that SDL2. I am leaving this issue open for some time, but it seems that may not be related to SDL2 anyway.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
