### ISSUE TITLE
Secondary mouse button behaves incorrectly in OpenMW when mouse buttons are swapped

### ISSUE THREAD

**Issue by Javic36** [libsdl-org/SDL#5108]
Hello. I originally raised this issue in a [forum post](https://discourse.libsdl.org/t/seeking-help-with-openmw-sdl-mouse-button-issue/34127/2) which summarizes the key points. A respondent directed me here. I see the problem on 64-bit Windows 7 SP 1.

The problem occurs in [OpenMW](https://openmw.org/) which uses SDL. As the issue title says, with mouse buttons swapped via Windows control panel, the primary mouse button operates correctly but the secondary button does not. The secondary button must be clicked twice to take effect.

If you'd like to reproduce the problem exactly as I see it:

1. Swap primary and secondary mouse buttons in Windows control panel.
2. Install the latest release of OpenMW.
2. Replace "sdl2.dll" included with that release with the latest version from this site. (With the SDL library that ships with OpenMW, the problem is worse.)
3. Run OpenMW and configure mouse button bindings like this: “Use” --> "Mouse 1" (physical right button), “Inventory” --> "Mouse 3" (physical left button).

In the game, clicking Mouse 1 behaves correctly (for example, the character swings a weapon if one is equipped). But Mouse 3 must be clicked twice to open the Inventory screen. (That's two single clicks, not a double-click.) Correct behavior would open the Inventory with a single click.

As my earlier post says, I'm a developer but don't currently have the tools needed to build OpenMW or SDL. But after inspecting the mouse button handling code for both projects, I have one theory that could be worth investigating. The problem might be related to the concept of "pending click focus". I see in SDL (“SDL_windowsevents.c”) logic that stops forwarding a mouse button click if it thinks “click focus” is pending. The behavior I’ve observed could occur if the first click from Mouse 3 was interpreted as occurring while click focus is pending, followed by a second click which would be forwarded to the client application. Just a theory.

I’d be happy to look into this issue more deeply if you could supply me with a Windows debug build of the SDL library. I have a debugger (a fairly old version of Microsoft Visual C++) which should be sufficient. Regardless, let me know if I can supply any additional information.

**Comment by slouken** [comment]
Fixed, thanks!

You can get the DLL with the fix from:
https://www.libsdl.org/tmp/x64/SDL2.dll

**Comment by Javic36** [comment]
Works! Thanks. Awesome. I'll let the OpenMW folks know they'll want to include an updated SDL library in their package.

**Comment by slouken** [comment]
You're welcome!
