### ISSUE TITLE
Rect utility functions for FRect

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL#5110]
Hello!

I've noticed that the Rect utility functions (shown in the docs: https://wiki.libsdl.org/CategoryRect) don't seem to have variants for Float Rects.

I was wondering if there was any reason they don't have these functions. If the SDL developers think this would be a good addition, I could work on this.

I'm coming this from pygame, which occasionally gets requests for floating point versions of pygame.Rect. And because pygame uses the rect utility functions, we would have to implement them ourselves to get that working. And if we were already doing the work, it seems obvious to upstream it to SDL.

Also, could it be convenient to have easy conversion functions like `SDL_RectAsRectF` and `SDL_RectFAsRect`?

**Comment by icculus** [comment]
> Also, could it be convenient to have easy conversion functions like SDL_RectAsRectF and SDL_RectFAsRect?

Decided not to add these because they're straightforward to implement by the app, which can then decide if they want to truncate or round.

**Comment by Starbuck5** [comment]
Thanks for implementing this @icculus!

The include twice trick is very cool.
