### ISSUE TITLE
mouse cursor jumps to top-left corner on window focus/move on macOS 

### ISSUE THREAD

**Issue by shinyquagsire23** [libsdl-org/SDL#5111]
Tested on macOS Monterey 12.0.1, 12.1 on a 2021 Macbook Pro (ARM64) with the latest SDL2 available from `brew` (which seems to match the latest Github release, `2.0.18`).

Initially noticed it on my own project [here](https://github.com/shinyquagsire23/OpenJKDF2/) but I reproduced it on [this 53-line minimal SDL2 Metal example](https://gist.github.com/gcatlin/b89e0efed78dd91364609ca4095da346). As soon as I move my mouse across the window boundary, it jumps to the top-left corner of the screen.

If you move the mouse slow enough, it doesn't jump, however. Also, if the window spawns under the mouse, this warp only happens when clicking on the window border to move it (in my own project, this happens when I recreate the window as HiDPI and move it to the old window position).

Out of curiosity I also tried it with an extra monitor attached, and for some reason the mouse always warps to the top-left corner of the laptop display, even if the window is on the external display. I also tried with the external display mirrored to the laptop display (to remove the rounded corners and notch) and it still did the same mouse warp.

**Comment by bradallred** [comment]
yup, I just encountered this bug myself. very annoying.
