### ISSUE TITLE
SDL_GL_SetSwapInterval(-1) causes framebuffer to flip to the screen before rendering is finished

### ISSUE THREAD

**Issue by notnullnotvoid** [libsdl-org/SDL#5122]
I don't know whether this is a bug in SDL code or a bug in something SDL depends on, but I'm reporting it here for lack of a better place. Here is a video of the effect on a 60hz panel:

https://www.youtube.com/watch?v=EOWTnzGG8xY

The glitching doesn't show up in screenshots or screen capture, hence pointing a camera at the screen, but here is a screenshot of a framerate graph while it's happening:

![2021-12-20_11-59-34](https://user-images.githubusercontent.com/37276056/146814111-c35f2fba-1be4-4c2b-b4f6-a1c529c5720e.png)

The irregularities in the graph are the periods during which the glitch is happening. In this case it glitches occasionally, in other situations it glitches continuously or doesn't glitch at all, and this seems to correspond with how long the scene takes to render. It only seems to happen at a threshold of around 1-2ms on the 60hz panel, and around 2-3ms on the 144hz panel I also tested on. It's probably not clear from the video, but I can tell for sure that what's happening is an unfinished framebuffer is being presented on the screen before the GPU is done rendering to it.

Specs of my machine:
Windows 10 Version	10.0.19041 Build 19041
GPU: RX 580

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
