### ISSUE TITLE
Any plans on Dualsense adaptive trigger support?

### ISSUE THREAD

**Issue by selimrecep** [libsdl-org/SDL#5125]
Hi,
I ve checked library's dualsense part a bit. I think adaptive trigger isn't fully supported in library. It's been talked about a bit at https://github.com/libsdl-org/SDL/issues/4859#issuecomment-951532706 . Any plans on supporting it? I've also tweaked a bit with examples in the link as is:
```c
	DS5EffectsState_t state;

	Uint8 effects[][11] =
	{
		/* Clear trigger effect */
		{ 0x05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },



		{ 0x06, 15, 50, 100, 0, 0, 0, 0, 0, 0, 0 },
		{ 0x22, 0b10001000, 0, 0b111010, 0, 0,0 ,0, 0, 0, 0 }
		/*

		// Constant resistance across entire trigger pull
		{ 0x01, 0, 110, 0, 0, 0, 0, 0, 0, 0, 0 },
		// Resistance and vibration when trigger is pulled
		{ 0x06, 15, 63, 128, 0, 0, 0, 0, 0, 0, 0 },



		{ 0x21, 0b11100000, 0b11, 0, 0, 0b10010010, 0b100100, 0, 0, 0, 0 },*/
		//{ 0x25, 0b11, 0b1000001,  0b000000, 5,0,0,0,0,0,0}
	};

	trigger_effect = (trigger_effect + 1) % SDL_arraysize(effects);

	SDL_zero(state);
	state.ucEnableBits1 |= (0x04 | 0x08); /* Modify right and left trigger effect respectively */
	SDL_memcpy(state.rgucRightTriggerEffect, effects[trigger_effect], sizeof(effects[trigger_effect]));
	SDL_memcpy(state.rgucLeftTriggerEffect, effects[trigger_effect], sizeof(effects[trigger_effect]));
	SDL_GameControllerSendEffect(gGameController, &state, sizeof(state));
```

Using this link: https://gist.github.com/Nielk1/6d54cc2c00d2201ccb8c2720ad7538db#file-extendinput-datatools-dualsense-triggereffectgenerator-cs-L28
Gotta say that the adaptive trigger effect types in the link which are marked as "dont use, because not being used in libpad" aren't effects that I could produce with the functions which are "safe to use."
I also found a report of hid output report of dualsense, was originally posted in reddit but removed by owner for unkown reason, in there: https://gist.github.com/selimrecep/21be9aec0751219ebe4c12d8d81c9ed3 (forked from someone else)
I thought link could be useful. 

Edit: I realised it has raw support, just needs some structure to send effects.

**Comment by pktiuk** [comment]
> Edit: I realised it has raw support, just needs some structure to send effects.

I don't think raw support is a proper way of supporting it. I think it should be considered rather a hack than a proper support.  
This feature should be accesssible via haptics API. https://github.com/libsdl-org/SDL/blob/main/include/SDL_haptic.h

**Comment by slouken** [comment]
There are no plans for integrating the DualSense adaptive tiggers into the haptics API. The SDL haptics API doesn't map well to the capabilities of the adaptive triggers.

You are welcome to build your own library on top of SDL's DualSense raw effects support however.

**Comment by pktiuk** [comment]
Thank you for a clear statement. :)

**Comment by slouken** [comment]
You're welcome. :)

**Comment by equalent** [comment]
In case anyone needs the structures, they are now included in `isteamdualsense.h` as part of [Steamworks SDK](https://partner.steamgames.com/downloads/list). It's a header file straight up copied from the PS5 SDK
