### ISSUE TITLE
macOS: Instructions for building universal framework?

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL#5126]
Hi there!

I've been trying to figure out how the official SDL2 framework is built as a universal binary, with support back to 10.6 for Intel Macs as well as support for 11.0 and up on Apple Silicon machines. The current documentation gives instructions on how to build SDL2 as a universal dylib, but doesn't explain the same process for the frameworks.

I tried building it myself with the latest Xcode (13.2.1) and `xcodebuild -project SDL.xcodeproj -configuration Release MACOSX_DEPLOYMENT_TARGET=10.6`, but early on in the build I get the warning:

```
warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 12.2.
```

Can the details of the official build process please be added to the documentation?

Thanks in advance!

**Comment by slime73** [comment]
> early on in the build I get the warning

This warning comes from Xcode itself rather than something SDL can configure. Modern versions of the macOS SDK / Xcode build tools don't officially support targeting such old version of macOS anymore.

That being said, personally for my projects I set the deployment target to 10.7 anyway. I'm not sure if everything works or not though because basically no one runs such an old version of macOS these days.

**Comment by a-hurst** [comment]
> This warning comes from Xcode itself rather than something SDL can configure. Modern versions of the macOS SDK / Xcode build tools don't officially support targeting such old version of macOS anymore.

Right, but does that mean newer Xcode versions bump the minimum SDK to 10.9 (thus breaking compatibility with older releases), or does it still try to target the older SDK and just warn you it's unsupported behaviour?

I think 10.7 is definitely a safe lower bound nowadays, I just wanted to try and match SDL2's official version compatibility if it was easy to do.

**Comment by slime73** [comment]
> Right, but does that mean newer Xcode versions bump the minimum SDK to 10.9 (thus breaking compatibility with older releases), or does it still try to target the older SDK and just warn you it's unsupported behaviour?

As far as I know it's the latter (e.g. `otool -L` reports the specified version - 10.6 in this case - as the target rather than 10.9).

**Comment by a-hurst** [comment]
@slime73 Just tested out an SDL2 framework built with Xcode 13.2 on an old black MacBook running 10.6.8 and it works great despite the compiler warning. Thanks for helping out!
