### ISSUE TITLE
[SDL_Renderer] : high CPU usage of minimized applications with vertical sync

### ISSUE THREAD

**Issue by pionere** [libsdl-org/SDL#5134]
I'm using SDL2 in a game with optional VSYNC. This works fine and runs on my PC with about 10% cpu usage fullscreen/windowed mode.
This changes however when the application is minimized from fullscreen mode. The CPU usage jumps to 50%.
I checked the code and found a possible culprit. In D3D_RenderPresent SDL2 calls IDirect3DDevice9_TestCooperativeLevel before IDirect3DDevice9_Present, and if TestCooperativeLevel returns D3DERR_DEVICELOST, it simply returns. But according to the [documentation](https://docs.microsoft.com/en-us/windows/win32/api/d3d9helper/nf-d3d9helper-idirect3ddevice9-testcooperativelevel), TestCooperativeLevel returns D3DERR_DEVICELOST in case of a 'full screen device has lost focus'. This means IDirect3DDevice9_Present can not 'apply' VSYNC.

**Comment by pionere** [comment]
NOTE: Originally this issue was about Direct3D vs Vsync, but after checking the code the problem seems to be more common (-> changed the title).

As far as I understand when a standard application is rendering, the program/developer gets a feedback from the OS whether the rendering succeeds or not. This feedback is hidden by SDL at the moment, so it is impossible to tell if a rendering is failed/skipped due to an error (e.g. a minimized window). This means the program can not tell if vertical sync was 'applied' or not.

The failure of the vertical sync can lead to high CPU usage and the application has no way to react.

To resolve this issue, SDL should be more transparent when SDL_RenderPresent is called. The simplest would be a SDL_bool return value which tells whether the rendering succeeded, or not. Although a more elaborate return enum might be necessary later.

Here a summary of the renderers and how they are affected by the VSYNC problem:

**Renderer** | **Behavior**
-----------| --------
direct3d | IDirect3DDevice9_TestCooperativeLevel/IDirect3DDevice9_Present returns D3DERR_DEVICELOST
direct3d11 | IDXGISwapChain1_Present1 returns DXGI_STATUS_OCCLUDED
metal | METAL_ActivateRenderCommandEncoder returns SDL_FALSE
opengl(es) | GL_ActivateRenderer(SDL_GL_MakeCurrent) returns -1 ?
psp | seems to be not affected, although sceDisplayWaitVblankStart might return SCE_DISPLAY_ERROR_NO_PIXEL_DATA?
vita_gxm | seems to be not affected, although sceGxmDisplayQueueAddEntry might fail?
software | not affected since SDL_RENDERER_PRESENTVSYNC is not supported

At the moment only the `direct3d11` renderer sets an error (WIN_SetErrorFromHRESULT), the other renderers fail silently.

**Comment by slouken** [comment]
The application can detect the minimized state and avoid rendering, if you want an application level solution.

I'm thinking that we should detect this case in SDL, and potentially delay inside the library to simulate VSYNC in this situation. @icculus, @cgutman, thoughts?

**Comment by pionere** [comment]
> The application can detect the minimized state and avoid rendering, if you want an application level solution.

Sure? I tried to check WINDOWEVENTs, but for some reason it did not work out. Is there an 'official' solution?
And based on the description the rendering might fail even if the window is not minimized (in case the window is behind/hidden by other windows).

**Comment by andreasgrabher** [comment]
It seems there is a similar issue here on my Mac (M1, macOS 12.5.1, SDL v2.24.0). If I minimize my application's window (Previous: previous.sourceforge.net), both GPU and CPU usage go up to 100 % (100 % GPU total, 100 % of one performance CPU core).

**Comment by andreasgrabher** [comment]
I just compiled the latest code with the merged commits and unfortunately the problem still persists.

**Comment by slouken** [comment]
> I just compiled the latest code with the merged commits and unfortunately the problem still persists.

Fixed in https://github.com/libsdl-org/SDL/commit/82b40f097b0263837292763c36d4b6a6423e1548, thanks!

**Comment by andreasgrabher** [comment]
Thank you very much! Seems to work now. CPU and GPU usage stay about the same after minimizing the application window(s).

**Comment by slouken** [comment]
You're welcome! :)
