### ISSUE TITLE
undefined reference to `SDL_RenderGeometry'

### ISSUE THREAD

**Issue by karriszou** [libsdl-org/SDL#5137]
I build SDL(2.0.18 lastest) from source on Ubuntu 20.04, and type 'make install' to install. Then i link libSDL2.a and libSDL2main.a to my project, when i only call 'SDL_RenderGeometry()' function, linker complain "undefined reference to `SDL_RenderGeometry'", what's wrong?

**Comment by bradallred** [comment]
you are linking to the wrong library. Probably you are linking with the libsdl that comes from the Ubuntu repos instead of the one you built.

**Comment by meissner61** [comment]
> 

You probably figured this out by now but in case anyone searches this error in the future, after you compile SDL2 from source (You can check if you have the newer version by typing  "sdl2-config --version" into your terminal, you can now use that sdl2-config file in your gcc compiler options by adding 'sdl2-config --cflags --libs` exactly like that into your Makefile.
https://wiki.libsdl.org/Installation
