### ISSUE TITLE
iOS project getting started - main function not found

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [libsdl-org/SDL#5138]
I created a new SDL iOS project based on: https://github.com/libsdl-org/SDL/blob/main/docs/README-ios.md.
After following everything step by step under "Using the Simple DirectMedia Layer for iOS" section.

I get the following error:
> Undefined symbols for architecture arm64:   "_SDL_main", referenced from:       _main in SDL_uikit_main.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

When Rosetta is enabled:
> Undefined symbols for architecture x86_64:   "_SDL_main", referenced from:       _main in SDL_uikit_main.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation

Workstation: Macbook Pro 2021 M1 Pro (Apple Silicone), macOS v12.0.1 (21A559), Xcode 13.2

**Comment by aquawicket** [comment]
are you including libSDL2main.a (static) or libSDL2main.so (dynamic) library to your build. You can also just place SDL_uikit_main.c in with your apps source code.

**Comment by ZsoltMolnarrr** [comment]
Hello @aquawicket I am includoing libSDL2main.so (dynamic) library.

**Comment by aquawicket** [comment]
Compiler error says it can't find library that has SDL_uikit_main.o in it.  So you're missing that library linkage somewhere. It might have compiled statically.  Otherwise, just leave the SDL2main stuff out and include SDL_uikit_main.c into you app.

**Comment by slouken** [comment]
This is much easier to use in SDL3, the main function is entirely implemented in SDL_main.h
