### ISSUE TITLE
x11 "legacy" fullscreen behavior seems broken

### ISSUE THREAD

**Issue by vcaputo** [libsdl-org/SDL#5139]
After reworking fullscreen handling in my SDL2-utilizing GL2.1 game, which resulted in starting up as windowed instead of fullscreen, it seems I've uncovered a bug when run on non-NET_WM "legacy" x11 window managers (xorg-twm suffices for repro).

The specific SDL2 functions being used are, for creating the window+context:
```
win = SDL_CreateaWindow("foo", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 600, SDL_WINDOW_RESIZABLE | SDL_WINDOW_OPENGL | SDL_WINDOW_ALLOW_HIGHDPI);
glc = SDL_GL_CreateContext(win);
```

Then when switching to fullscreen via an in-game widget:
```
SDL_SetWindowFullscreen(win, SDL_WINDOW_FULLSCREEN_DESKTOP);
```

And the event loop handles resize events to keep the drawable size and glViewport in sync:
```
if (ev.type == SDL_WINDOWEVENT && ev.window.event == SDL_WINDOWEVENT_RESIZED) {
        int w, h;

        SDL_GL_GetDrawableSize(win, &w, &h);
        glViewport(0, 0, w, h);
}
```

Then when switching back to windowed mode, again via in-game widget, it's the same `SDL_SetWindowFullscreen()` just called with 0 instead of SDL_WINDOW_FULLSCREEN_DESKTOP, with the expectation of an SDL_WINDOWEVENT_RESIZED arriving again.

Now this all works swimmingly on "modern" x11 window managers, I verified that using WindowMaker.

But when run under xorg-twm or my own window manager, which don't support the NET_WM stuff, the behavior is very different and unusably broken.  Glancing at the source I see the "legacy" fullscreen path is very distinct, and there's this suspicious code in the reparenting step where the original window is being centered within the new parent:
https://github.com/libsdl-org/SDL/blob/a1e992b110b9adf3305a5ebb5514f0e970f7911e/src/video/x11/SDL_x11window.c#L1412-L1414

The breakage *appears* to be the original window dimensions (800x600) are used in computing this "centered" placement, but the actual rendering is fullsize at this now strange "centered" offset, presumably because a subsequent RESIZE event is handled and the glViewport() called to make GL rendering fullscreen-appropriate.

It's unclear to me if I should be trying to jump through some band-aid hoops to fix this on my end.  My knee-jerk reaction is that the semantics of the SDL2 API I'm calling shouldn't differ from one window manager to the other, and that this is an obvious bug, hence the issue.

If I have time and this issue sees no movement in the interim, I'll see about putting together a minimal repro test case.

Also, somewhat orthogonally, while testing this under WindowMaker where it works correctly, I observed the window repeatedly shrinking with every fullscreen->windowed cycle.  That's easily dealt with by the user, but seems like another bug... the window should just be going back to its previous windowed dimensions I presume.  Maybe that's in WindowMaker's court, just thought I'd mention it.

**Comment by vcaputo** [comment]
For the sake of having a convenient "real" repro of this I ported the same changes to a similarly structured tiny FOSS game I'd previously released.  Source is available at git://git.pengaru.com/sars (use recursive checkout, it has submodules), also  viewable on web @ https://git.pengaru.com/cgit/sars/.git/

Pre-built binaries (including the needed assets) available at https://dl.pengaru.com/hungrycat/sars/hungrycat-sars-rev3.zip
For linux there's both x86_64 and 32-bit arm builds appropriate for rpi in there, which is what's relevant to this issue.
There's also win32 and osx mach-o MINGW builds FWIW.

Press 'f' to cycle through the fullscreen/windowed modes.  Ideally this should produce the same results in both "modern" and "legacy" x11, but it'd be nice to just have usable unbroken results in "legacy" x11 (like on xorg-twm).  Bonus points would be the same results seen on osx and windows too, I haven't actually had a chance to test those non-linux builds yet.

**Comment by icculus** [comment]
This is a known issue, but we don't intend to fix the legacy path. Instead, we intend to remove it completely soon.

The discussion about that is in #1782, so I'm going to close this issue and encourage discussion to move over there.
