### ISSUE TITLE
SDL is broken [Windows 7/Audio] 

### ISSUE THREAD

**Issue by Knightsurfer** [libsdl-org/SDL#5141]
I dunno if it's due to a windows update or something I did, but SDL has stopped emitting sound on any application that uses it, just figured I'd get that out there.

How I noticed it is I was using Dosbox to play one of the old elder scrolls games, noticed I couldn't get sound to work no matter what I tried.

Then I went on mGBA to test out a homebrew project I had been working on the past few months and noticed it wouldn't emit sound unless I selected Qt Multimedia.

EDIT: the environment variable thing worked, although I haven't a clue how the bug initially started, I do know I tried this method earlier but the forum I got the info from said "dsound" instead of "directsound", either way thanks, 

also deleting the variable seems to have no effect, I guess once it's set right it stays as a permenant change? Either way it's working now. 

scratch that, it works on mGBA but it doesn't want to find an audio device in DOSBOX for whatever reason...

At closer inspection it seems DOSBOX uses an older version of SDL, I dunno what stopped that from working but I found a fix anyway, DOSBOX Pure for retroarch is a nice workaround.

**Comment by AJenbo** [comment]
Please edit your title to contain "Windows" and "audio". Also list the version you are using. The version of Windows and some of the games.

Did you change the version of SDL, or anything else, between when it did work and when it stopped working?

**Comment by icculus** [comment]
Other things:

- reboot the computer. I know, I know, but sometimes it works!

- force your app to use directsound, to rule out this being a bug in our WASAPI backend. `SDL_setenv("SDL_AUDIODRIVER", "directsound", 1);` before you call SDL_Init. Or set this environment variable before launching the program, but that tends to be complicated on Windows.

- see if there's something weird, like your default audio device became that SPDIF port no one actually uses, and SDL is correctly sending data to something that doesn't actually make noise.

**Comment by icculus** [comment]
Closing this; original post is edited to say it's working now.
