### ISSUE TITLE
undefined behavior in SDL_memset

### ISSUE THREAD

**Issue by andrewrk** [libsdl-org/SDL#5147]
shifting a char by 16 or 24 is UB in C:

https://github.com/libsdl-org/SDL/blob/6a7b63802c21882cbd1b7aab39b99f9f048f19b3/src/stdlib/SDL_string.c#L298

this can be observed by building SDL from source with clang's `-fsanitize=undefined` feature.

Here's a patch to fix:

```diff
--- a/src/stdlib/SDL_string.c
+++ b/src/stdlib/SDL_string.c
@@ -295,7 +295,7 @@ SDL_memset(SDL_OUT_BYTECAP(len) void *dst, int c, size_t len)
         }
     }
 
-    value4 = (c | (c << 8) | (c << 16) | (c << 24));
+    value4 = ((Uint32)c | ((Uint32)c << 8) | ((Uint32)c << 16) | ((Uint32)c << 24));
     dstp4 = (Uint32 *) dstp1;
     left = (len % 4);
     len /= 4;
```

no attribution required

**Comment by slouken** [comment]
Fixed, thanks!
