### ISSUE TITLE
Switch Pro Controller on macOS has X/Y and A/B buttons reversed

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5151]
> ...however, X and Y, and A and B, are reversed from what they should be. How does this work with hidapi? Do we just tweak this in the gamecontrollerdb.h file or is it somewhere else (and is tweaking it going to break it for non-hidapi builds, if such builds are still a thing?). Filing a separate issue for that.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3146#issuecomment-1002662169_

**Comment by icculus** [comment]
Assigning to Sam; this is likely a simple fix, but wanted to make sure the way this is fixed hasn't changed with hidapi.

`2021-12-29 10:59:25.754 testgamecontroller[38415:2986807] INFO: Nintendo Switch Pro Controller 0: Nintendo Switch Pro Controller (guid 030000007e0500000920000010026800, VID 0x057e, PID 0x2009, player index = 0)`

**Comment by icculus** [comment]
(Same result in USB and bluetooth mode, fwiw.)

**Comment by icculus** [comment]
Bluetooth guid, etc:

`2021-12-29 11:02:14.184 testgamecontroller[38569:2995816] INFO: Nintendo Switch Pro Controller 0: Nintendo Switch Pro Controller (guid 030000007e0500000920000001006800, VID 0x057e, PID 0x2009, player index = 0)`

**Comment by cgutman** [comment]
could this be related to `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS`?

**Comment by icculus** [comment]
Yeah, this was my misunderstanding. I didn't realize this was intentional behavior and users can flip it if they want. Not a bug!
