### ISSUE TITLE
2.0.18 SDL hints SDL_HINT_IME_SHOW_UI not work in windows 11

### ISSUE THREAD

**Issue by opxdo** [libsdl-org/SDL#5153]
[/src/video/windows/SDL_windowskeyboard.c
](https://github.com/libsdl-org/SDL/blob/2363ddc330efa939d2d43a6c809794970f401120/src/video/windows/SDL_windowskeyboard.c#L912)

change to

`
    case WM_IME_SETCONTEXT:
            if(videodata->ime_uiless){
                *lParam = 0;
            }
break;
`

will be ok.

**Comment by baidwwy** [comment]
Test passed 66666666

I mentioned this problem
https://github.com/libsdl-org/SDL/pull/4707#issuecomment-941857093

**Comment by slouken** [comment]
Fixed, thanks!
