### ISSUE TITLE
Windows: SDL locks modifier state after opening a dialog

### ISSUE THREAD

**Issue by six809** [libsdl-org/SDL#5157]
If I, say, make Control+L open a Windows load dialog, after it closes, SDL assumes Control is still pressed.

git bisect blames commit c542de92135a79f25648e75b1c2ab0fd581e29c0

http://www.6809.org.uk/tmp/xroar/focus-test.c (or .exe for a built test)

Edit: alt+tabbing away and back again prompts SDL to reread mod state.

**Comment by slouken** [comment]
Thanks for the excellent test case. This is fixed for the next release.
