### ISSUE TITLE
SDL Detects generic controller as NEXT SNES Controller

### ISSUE THREAD

**Issue by JohnMama12** [libsdl-org/SDL#5159]
Hi I was using the Cemu emulator and used SDL but my controller appears as a NEXT SNES Controller.
The keybind names are messed up such as the B button being left shoulder and some other buttons do not work they just don't detect their press at all, I can guarantee my controller works fine. tested in the controller options in the control panel...
![image](https://user-images.githubusercontent.com/80211498/147856787-075283fe-4a92-4591-9cd9-2ea3e4d1b1af.png)

**Comment by slouken** [comment]
What's the USB VID/PID of your controller?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.
