### ISSUE TITLE
SDL_VideoInit(): add an env variable to set the device index

### ISSUE THREAD

**Issue by substring** [libsdl-org/SDL#5160]
Hi,

any VideoBootStrap->create() takes an integer as parameter to select a device. in SDL_VideoInit, the index is set to 0 and never changes. It seems none of the video drivers handles a device index, but KMSDRM. Before submitting a PR, I'd like to discuss the opportunity to add a SDL_VIDEO_DEVICE_INDEX environment variable to set the video device index. That way, KMSDRM could use a different card, no need to make a KMSDRM specific env variable.

**Comment by slouken** [comment]
Yes, that's fine.
