### ISSUE TITLE
Man pages for offline documentation reading

### ISSUE THREAD

**Issue by cuppajoe123** [libsdl-org/SDL#5163]
Hello,
As a Linux user, man pages are generally a very helpful resource for reading documentation, but I noticed that SDL2 does not have any man pages available. The package I installed came with HTML pages from the wiki, but I would prefer to be able to read the docs from the command line. Has there been any discussion on creating man pages, or is there not enough interest?

**Comment by slouken** [comment]
We talked about it a long time ago, but there wasn't any feasible way to do this and keep the documentation up to date.

Now that the wiki is bridged to the SDL headers, this might be more feasible, but Ryan and I don't have time to do something like this. You're welcome to submit a pull request that adds this functionality if you want.

**Comment by icculus** [comment]
Okay, try this:

(EDIT 08/02/2025: updated this for the newer directory structure.  --ryan.)

```bash
git clone https://github.com/libsdl-org/SDL SDL
git clone https://github.com/libsdl-org/sdlwiki sdlwiki
./SDL/build-scripts/wikiheaders.pl SDL sdlwiki/SDL3 --copy-to-manpages
man SDL/man/SDL_OpenAudio.3
```

**Comment by swagtoy** [comment]
@icculus This script doesn't appear to work anymore. Maybe when I get a chance I can try to look into it, I still remember some Perl

**Comment by madebr** [comment]
@swagtoy 
SDL3's wikiheaders.pl produces high-quality man pages, and is used by the CMake script ([and also tested on ci](https://github.com/libsdl-org/SDL/actions/runs/16694419869/job/47256552567#step:34:118)).

So make sure to look at [`build-scripts/wikiheaders.pl`](https://github.com/libsdl-org/SDL/blob/main/build-scripts/wikiheaders.pl) from the main branch before diving in :)

**Comment by swagtoy** [comment]
@madebr Got it. Yes, I am on the main branch :-)

**Comment by swagtoy** [comment]
Interesting, it would appear that it worked when using the CMake...

**Comment by madebr** [comment]
> Interesting, it would appear that it worked when using the CMake...

The script has a quirk where it needs wiki pages to exist before it generates man pages.
Perhaps that's the problem you are seeing?

[Here's how the script is called from CMake](https://github.com/libsdl-org/SDL/blob/42463569d5e0b0949674b90247dae8d934765442/cmake/sdlmanpages.cmake#L46-L58)

Ideally, this middle step should be eliminated, and the script should get better dependency management.
(Perhaps the wikiheaders script can generate a `.d` dependency file, as `gcc -MD`)

**Comment by swagtoy** [comment]
> Perhaps that's the problem you are seeing?

The issue I indeed that. What I am doing as a workaround is iterating through all the files from the Wiki repository. However, then I end up with duplicates (i.e. SDL2 and SDL3 Cmake build page), so I am not sure how to handle this situation.

What would you suggest?

**Comment by madebr** [comment]
Do you mean SDL2 and SDL3 both generating e.g. a `SDL_Init.3` man page?
The SDL man pages are conflicting and cannot be installed at the same time.
You'd have to start renaming files to make them live together.

**Comment by icculus** [comment]
Also, our SDL2 documentation is quite bad in contrast to SDL3, I'm not sure it's worth keeping SDL2 manpages around.

**Comment by icculus** [comment]
I've updated my previous comments, too, as the command line would look for the wiki in the wrong directory (and thus manpages would not generate correctly). I think this was figured out later in the discussion, but just so that doesn't trip anyone up later.

**Comment by swagtoy** [comment]
> I've updated my previous comments, too, as the command line would look for the wiki in the wrong directory (and thus manpages would not generate correctly). I think this was figured out later in the discussion, but just so that doesn't trip anyone up later.

No.. i just realized this now :')

For some foolish reason I was trying to change the script to read through every directory like some sort of dunce. Maybe I should get some sleep...

Script is fine, though there is one thing id like to adjust maybe

Thank you for the help though all. Wouldve wasted a whole day otherwise
