### ISSUE TITLE
SDL version [question]

### ISSUE THREAD

**Issue by avafinger** [libsdl-org/SDL#5181]
Why is SDL version 2.0.19.0 linked to /usr/local/lib/libSDL2-2.0.so.0 -> libSDL2-2.0.so.0.18.1 ?
What is the versioning way SDL is utilizing?

./testver
INFO: Compiled with SDL 2.0 or newer
INFO: Compiled version: 2.0.19.0 (https://github.com/avafinger/SDL@d6a25587b65aa85dd69301878e6dc92d29c02684)
INFO: Linked version: 2.0.19.0 (https://github.com/avafinger/SDL@d6a25587b65aa85dd69301878e6dc92d29c02684)

**Comment by slouken** [comment]
It's using libtool versioning.
