### ISSUE TITLE
Feature request: Ability to create a window treated as a dock (X11)

### ISSUE THREAD

**Issue by gnevej** [libsdl-org/SDL#5185]
X11 has this thing for making the window manager treat the window like a dock `_NET_WM_WINDOW_TYPE_DOCK`.

I am making a dock for X11 with SDL and this is useful because some tiling window managers use this to avoid placing windows above the dock. By using other types of windows such as the `SDL_WINDOW_TOOLTIP` flag, it makes my window cover the tiled windows.

**Comment by icculus** [comment]
I don't think we should add a SDL_WINDOW_DOCK enum to the API, because we can't support this on almost any platform.

But maybe we can add an SDL hint that lets apps specify the _NET_WM_WINDOW_TYPE property, though!

**Comment by gnevej** [comment]
> I don't think we should add a SDL_WINDOW_DOCK enum to the API, because we can't support this on almost any platform.

There are many X11-only flags in that enum.

**Comment by icculus** [comment]
> There are many X11-only flags in that enum.

But I can support things like SKIP_TASKBAR and POPUP_MENU on other platforms, even if we currently don't.

**Comment by gnevej** [comment]
> > There are many X11-only flags in that enum.
> 
> But I can support things like SKIP_TASKBAR and POPUP_MENU on other platforms, even if we currently don't.

I understand.

Do it the way you think is best for SDL. If you don't want to add it, no problem. Keep up the good work and please keep me updated with the state of this feature if you decide to add it in a way or another!

**Comment by icculus** [comment]
Okay, try this...get and install the latest SDL from revision control and do this:

```c
SDL_SetHint(SDL_HINT_X11_WINDOW_TYPE, "_NET_WM_WINDOW_TYPE_DOCK");
SDL_Window *myDockWindow = SDL_CreateWindow("Dock Window", 100, 100, 100, 100, 0);
```

Or you can try this from the command line, with, say, SDL's testsprite2 test app:

```bash
SDL_X11_WINDOW_TYPE=_NET_WM_WINDOW_TYPE_DOCK ./testsprite2
```

(Just be prepared to kill that app from the command line, as it won't have a title bar.)

**Comment by gnevej** [comment]
> Okay, try this...

It works! Thanks for the feature!
