### ISSUE TITLE
[Intel C++] error : passing 'int' to parameter of incompatible type '__m128' (vector of 4 'float' values)

### ISSUE THREAD

**Issue by An0nyMooUS** [libsdl-org/SDL#5186]
Intel C++ 2022 Toolset, MSVC 2022.

![image](https://user-images.githubusercontent.com/73304497/148421126-767cd1f2-3c6c-4a40-8203-bee5bba7c53c.png)

**Comment by icculus** [comment]
So _mm_hadd_ps is an SSE3 intrinsic, newer than the rest on this line; for some reason we didn't `#include <pmmintrin.h>` but we did include xmmintrin.h or whatever.

**Comment by icculus** [comment]
...So this is building with VS2022, unless "Intel C++ 2022 Toolset" means some other piece of software that I didn't understand here.

Alternately: this might be a problem with the included .sln files that isn't a problem when CMake generates it's own from scratch...?

**Comment by icculus** [comment]
Oh, I think this means it's the Intel C++ Compiler, using MSVC as a development environment.

https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#dpcpp-cpp

**Comment by XXxR4GALXxx** [comment]
> Oh, I think this means it's the Intel C++ Compiler, using MSVC as a development environment.
> 
> https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#dpcpp-cpp

Yep! But this only happens when I have /W4 (Warning Level 4), and Intel C++ treats warnings as an error. Temporarily, I disabled the warnings as an error.

**Comment by slouken** [comment]
This is an important warning. It means the intrinsic expects input from a SIMD register, but it's coming from a non-SIMD register, and the operation will likely fail or crash the program.

**Comment by icculus** [comment]
I'm going to install Intel C++ today and see if I can reproduce it.

**Comment by icculus** [comment]
Okay, so it appears that Intel's compiler is just Clang now.

This works if you enable SSE3 support in the compiler. If you right-click SDL_audiocvt.c in Visual Studio's solution explorer, select "Properties", "C++", "Command Line" and add "-msse3" to "Additional Options," it'll work.

I don't think we can change the project files generically to handle this for Intel C++ users and also people that don't have Intel C++ installed, but I don't know anything about Visual Studio in this regard.

**Comment by icculus** [comment]
Hmm, we have this in SDL_cpuinfo.h...

```c
#if defined(HAVE_IMMINTRIN_H) && !defined(SDL_DISABLE_IMMINTRIN_H)
#include <immintrin.h>
#else
```

I'm wondering if that `#else` was meant to be an `#endif`

This gets us the needed pmmintrin.h include, but then Intel C++ throws an error because -msse3 needs to be specified. Although __SSE3__ is still defined without -msse3 here. Not sure why yet.

**Comment by slouken** [comment]
I think __SSE3__ was defined unconditionally as part of a separate commit. I'm guessing that's not what we want.

**Comment by icculus** [comment]
This is where __SSE3__ is getting defined in SDL_cpuinfo.h ...

```c
#ifndef _WIN64
#ifndef __MMX__
#define __MMX__
#endif
#ifndef __3dNOW__
#define __3dNOW__
#endif
#endif
#ifndef __SSE__
#define __SSE__
#endif
#ifndef __SSE2__
#define __SSE2__
#endif
#ifndef __SSE3__
#define __SSE3__
#endif
```

I'm thinking this was for older Visual Studios or something? It seems irresponsible to force these on, and it definitely breaks this case, because this is how we decide to use SSE3 intrinsics.

`__INTEL_COMPILER` and `__clang__` don't appear to be defined, so I don't know how to check for this, other than removing this code that forces it on.

**Comment by icculus** [comment]
(`__MSC_VER` _is_ defined, even though it's using Intel's compiler.)

**Comment by slouken** [comment]
Oops, I think that was me, in https://github.com/libsdl-org/SDL/commit/609cea1eb8149944c00018eb5209965995055d0b

**Comment by slouken** [comment]
We have a separate large discussion about the right way to handle intrinsics for 2.0.22. Should we back this out now and revisit then?

**Comment by slouken** [comment]
We don't want to disable SSE3 code in SDL, so let's leave this alone for now and revisit it in 2.0.22.

**Comment by An0nyMooUS** [comment]
https://stackoverflow.com/questions/13534032/how-to-detect-intels-compiler-icc-with-ifdef

Works fine to check Intel Compiler, in VS 2019/22.

```
#if !defined(SYCL_LANGUAGE_VERSION) && defined (__INTEL_LLVM_COMPILER)
   // code specific for Intel C++ Compiler below
   // ... ...

   // example only
	std::cout << "__INTEL_LLVM_COMPILER: " << __INTEL_LLVM_COMPILER << std::endl;
	std::cout << "__VERSION__: " << __VERSION__ << std::endl;
#endif
```

**Comment by iryont** [comment]
This is still an issue with recent SDL. In fact, the moment i switch toolset in MSVC to llvm I get this error. The fix is simple, just to add ``-msse3`` to ``SDL_audiocvt.c`` options.

**Comment by icculus** [comment]
For a later SDL release, we should rethink all of this, because we're obviously doing things wrong here, but for now the questions are:

- Can we add `-msse3` to the Visual Studio project files so it is _only_ used if building with Clang or Intel's LLVM, and not with Visual Studio's standard compiler? (I'm assuming no.)
- Can with use a `#pragma` to enable `-msse3` right before this code? (Maybe.)
- Can we add a check for the Intel compiler and complain loudly if `-msse3` isn't on the command line? (Yes?) We'll do this as a `#warning` so things still build without the faster code, though.
- Can we make sure CMake/configure are checking if `-msse3` works and adding it to the cflags? (Yes.)

**Comment by sezero** [comment]
Can we not separate sse[X] sources and use per-source compiler flags?

**Comment by sezero** [comment]
>    Can with use a `#pragma` to enable `-msse3` right before this code? (Maybe.)

This would be ideal for this particular issue, if such a pragma is available with icc.

**Comment by icculus** [comment]
> Can we not separate sse[X] sources and use per-source compiler flags?

Yes, but that would be a dramatic change I'd like to avoid for SDL2...but we'd still have the problem that we can't add the compiler flag for that source file _just for Intel C++_ into the Visual Studio project file...as far as I know.

**Comment by icculus** [comment]
I can't find a `#pragma` that will accomplish this, nor a way to say "only use this command line option with this compiler" in Visual Studio. Honestly it's a corner case, we should just make a note in the README that you have to add -msse3 to the command line flags.
