### ISSUE TITLE
Inverted event->wheel.x values under Wayland driver

### ISSUE THREAD

**Issue by UncombedCoconut** [libsdl-org/SDL#5202]
Hi, I have a Linux laptop whose mouse is a "SynPS/2 Synaptics TouchPad".
In case `SDL_VIDEODRVER=wayland` is set, I observe event->wheel.x values inverse to what they should be.
I don't know if this is a general issue or specific to my system. (The current behavior was decided/tested here: https://github.com/libsdl-org/SDL/commit/1fa4bcca6a2fb0f37907cf294c2913310490b346 https://github.com/libsdl-org/SDL/issues/2763)

Tested SDL version: commit 1f32dd8edcf2a7882378e5ff6d616d0382103c9c # Sun Jan 9 06:36:18 2022 -0800
Test procedure:
```bash
mkdir build-sdl
cd build-sdl
cmake -DSDL_TEST:ON ../SDL
make -j
SDL_VIDEODRIVER=x11 ./test/testgesture --info event
SDL_VIDEODRIVER=wayland ./test/testgesture --info event
```

Test results (marked with driver and scroll direction):
```
[x11     L] INFO: SDL EVENT: Mouse: wheel scrolled -1 in x and 0 in y (reversed: 0) in window 2
[x11     R] INFO: SDL EVENT: Mouse: wheel scrolled 1 in x and 0 in y (reversed: 0) in window 2
[x11     D] INFO: SDL EVENT: Mouse: wheel scrolled 0 in x and -1 in y (reversed: 0) in window 2
[x11     U] INFO: SDL EVENT: Mouse: wheel scrolled 0 in x and 1 in y (reversed: 0) in window 2
[wayland L] INFO: SDL EVENT: Mouse: wheel scrolled 1 in x and 0 in y (reversed: 0) in window 1
[wayland R] INFO: SDL EVENT: Mouse: wheel scrolled -1 in x and 0 in y (reversed: 0) in window 1
[wayland D] INFO: SDL EVENT: Mouse: wheel scrolled 0 in x and -1 in y (reversed: 0) in window 1
[wayland U] INFO: SDL EVENT: Mouse: wheel scrolled 0 in x and 1 in y (reversed: 0) in window 1
```

**Comment by flibitijibibo** [comment]
Wayland logic: https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L583-L590

X11 logic:
- https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11events.c#L175-L191
- https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11events.c#L1289

Does seem like it should be inverted but I don't have any horizontal wheel hardware to check. If a maintainer has such hardware and wants to sneak this into 2.0.20 this one's all yours, otherwise it can wait another cycle...

**Comment by icculus** [comment]
> If a maintainer has such hardware

This reproduces on a basic laptop touchpad for me. Two fingers to the left is negative in x11 and positive in Wayland here (and opposite to the right, of course).

**Comment by flibitijibibo** [comment]
https://github.com/libsdl-org/SDL/commit/3e1b3bc34489297bce35916a3d0242d0eadc95f0

@UncombedCoconut, let us know if this doesn't actually fix it!
