### ISSUE TITLE
Wrong filenames on wayland drag&drop events: trailing \r, URI instead of file name

### ISSUE THREAD

**Issue by haasn** [libsdl-org/SDL#5205]
I believe the code for handling file drag&drop events on Wayland is wrong:

```c
static void
data_device_handle_drop(void *data, struct wl_data_device *wl_data_device)
{
    SDL_WaylandDataDevice *data_device = data;
    void *buffer = NULL;
    size_t length = 0;

    const char *current_uri = NULL;
    const char *last_char = NULL;
    char *current_char = NULL;

    if (data_device->drag_offer != NULL) {
        /* TODO: SDL Support more mime types */
        buffer = Wayland_data_offer_receive(data_device->drag_offer,
                                            &length, FILE_MIME, SDL_FALSE);

        /* uri-list */
        current_uri = (const char *)buffer;
        last_char = (const char *)buffer + length;
        for (current_char = buffer; current_char < last_char; ++current_char) {
            if (*current_char == '\n' || *current_char == 0) {
                if (*current_uri != 0 && *current_uri != '#') {
                    *current_char = 0;
                    SDL_SendDropFile(NULL, current_uri);
                }
                current_uri = (const char *)current_char + 1;
            }
        }

        SDL_free(buffer);
    }
}
```

I can see multiple issues:

1. This splits on `\n`, when `file-list` URIs are actually separated by `\r\n`. This results in trailing `\r` entries in the sent drop file events.
2. This doesn't decode the `file://` URIs into actual file names, which is inconsistent with my interpretation of `SDL_DROPFILE` events:

```c
typedef struct SDL_DropEvent
{
    Uint32 type;        /**< ::SDL_DROPBEGIN or ::SDL_DROPFILE or ::SDL_DROPTEXT or ::SDL_DROPCOMPLETE */
    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
    char *file;         /**< The file name, which should be freed with SDL_free(), is NULL on begin/complete */
    Uint32 windowID;    /**< The window that was dropped on, if any */
} SDL_DropEvent;
```

There is no obvious indication to me that `file` should ever be allowed to be a `file://` URI, rather than a raw file name. I think that the correct resolution of this would be for SDL to decode the URIs and give API users actual file names, in addition to fixing the trailing `\r` issue.

**Comment by emersion** [comment]
For reference, the relevant code for X11: https://github.com/libsdl-org/SDL/blob/9e6249fa5460364fce0133866a1dc7529a7d906c/src/video/x11/SDL_x11events.c#L1490

**Comment by haasn** [comment]
For reference, GLFW has this function to parse URI lists:

https://github.com/glfw/glfw/blob/master/src/x11_window.c#L381

**Comment by flibitijibibo** [comment]
Self-assigning to mark as a Wayland item but this one's open for someone to get. As @emersion points out we should just copy what X11 does here.

**Comment by flibitijibibo** [comment]
Fixed by https://github.com/libsdl-org/SDL/commit/9a2bbd8acbebcde56dd2f89ebca3b196c2b38914.

A couple things to think about on top of this:
1. We don't have a window handle to send... NULL works for now but we should probably get an SDL_Window* from somewhere.
2. The URI decode is taken directly from the X11 folder, it'd be nice to put that in a common location but I don't know where that would be.
