### ISSUE TITLE
opengles2: Performance vs OpenGL...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5206]
I'm writing this up with the understanding that we might just throw up our hands and say "it can't be helped," but here's testdraw2 on this laptop...

| renderer    | line method | FPS  |
|----------------|-----------------|--------|
| opengl       | 1                  | 2093 |
| opengles   | 1                  | 2692 |
| opengles2 | 1                  | 312   |
| opengl       | 2                  | 5306 |
| opengles   | 2                  | 4278 |
| opengles2 | 2                  | 325   |
| opengl       | 3                  | 4968 |
| opengles   | 3                  | 3125 |
| opengles2 | 3                  | 340   |

...so there is obviously some bottleneck in the GLES2 backend.

OpenGL is (currently) using glBegin/glEnd, which suggests the GL itself is handling buffer management for us behind the scenes, perhaps with visibility into the driver and hardware we can't obtain and don't want to manage anyhow.

GLES1 is using glDrawArrays with client-side arrays; this machine has an Intel integrated GPU, so it's likely it can just access system RAM without penalty, and maybe that wouldn't be so forgiving with a discrete GPU (and maybe that's true for glBegin, etc as well).

GLES2 is using VBOs, so we have to manage them ourselves.

For testdraw2, the framerate doubles on this machine if I give it a pool of 512 VBOs to work from instead of the current 8. Presumably this helps because we're spending time waiting on a VBO that is still in flight from a previous frame when there are only 8. 128 VBOs didn't seem to help and I'm hesitant to boost this number so high without at least a fallback to manage this when the GL can't generate that many. Also, if we aren't running a benchmark and instead are using vsync, it's possible 8 is more than enough, as they would be definitely available again after a frame or two, instead of dozens of frames.

So what we're looking for here is:
- Is there a faster way to get data to the GL in GLES2 (even as an extension)?
- Is there a reasonable way to avoid waiting on in-flight resources?
- Is there some other bottleneck causing issues?

Or more directly:
- Is there a reason this same machine can't achieve comparable performance to opengl's glBegin with GLES2?

Let's see if we can figure something out for 2.0.22.

**Comment by 0x1F9F1** [comment]
When faced with a similar problem upgrading the [renderer for an old game](https://github.com/0x1F9F1/Open1560/blob/master/code/midtown/agigl/glstream.cpp), I came to the conclusion: persistent mapping > client-side > orphaning > multiple buffering > mapping.

Persistent mapping requires GLES 3.1 for sync objects and [EXT_buffer_storage](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_buffer_storage.txt), and client side is not available, so [buffer orphaning](https://www.khronos.org/opengl/wiki/Buffer_Object_Streaming#Buffer_re-specification) seems to be the best option available.

On a 1080ti with 400 objects I get:
| Renderer | FPS |
| - | - |
| opengles2 | 175 |
| [opengles2 orphaning](https://github.com/0x1F9F1/SDL/commit/c825fe7997baba5bff367de4bd02611d52b357fa) | 300 |
| opengl | 450 |

Unfortunately it's still considerably slower than client-side, but should be an improvement with most (hopefully all) drivers.

For reference a highly unsafe and unsynchronised version of persistent mapping (re-using the unmapped buffer pointer) gives 700 fps (which should match proper persistent mapping given a large enough buffer), so there is definitely still quite a bit of overhead.

**Comment by slime73** [comment]
All OpenGL ES versions support client-side vertex data I believe, it's just that SDL's GLES2 renderer code went with buffers to avoid a performance issue with client-side vertex data that's specific to ANGLE (and web), if I'm remembering right.

**Comment by slime73** [comment]
Ok it wasn't necessarily ANGLE specifically, more emscripten/webgl – this old commit has some hints about it: https://github.com/libsdl-org/SDL/commit/f5bbbe417d246a6eaddfededa86657ba313150bb

The original batching change for vertex data erased that split and made the gles2 renderer always use VBOs, I think.

**Comment by 1bsyl** [comment]
I have the same ration on my laptop, maybe worse.
Should we make a define to enable/disable the VBO then ?

**Comment by icculus** [comment]
Okay, I've set up a pull request to move everything but Emscripten to client-side arrays in GLES2. This makes testdraw2/testsprite2/etc performance comparable to the opengl backend:

| renderer    | line method | FPS  |
|----------------|-----------------|--------|
| opengl       | 1                  | 2093 |
| opengles   | 1                  | 2692 |
| opengles2 | 1                  | ***2330*** |
| opengl       | 2                  | 5306 |
| opengles   | 2                  | 4278 |
| opengles2 | 2                  | ***3934*** |
| opengl       | 3                  | 4968 |
| opengles   | 3                  | 3125 |
| opengles2 | 3                  | ***3089*** |

Please check the PR and complain loudly if I shouldn't merge it!

**Comment by 1bsyl** [comment]
small parenthesis 
@slime73  : may I ask you how you find the commit f5bbbe4 which is from 2014 ?  
Because when I try to look at the history (with github or someclient) it doesn't go before June 21, 2015 
( https://github.com/libsdl-org/SDL/commits/main?after=ae9e2149a55c75e99a2d1dade0f2c3a031b9139d+104&branch=main&path%5B%5D=src&path%5B%5D=render&path%5B%5D=opengles2&path%5B%5D=SDL_render_gles2.c )

**Comment by 1bsyl** [comment]
@icculus ... I've retried some bench of PR #5214, with opengles2 and in fact I see no difference between VBO and no VBO.
I was misleading because batching isn't automatically enabled.

with VBO or no VBO, with batching, line method 1,2 or 3, I see the same performance as opengl (+ or - 5% )

`SDL_RENDER_BATCHING=1 SDL_RENDER_LINE_METHOD=3 ./testdraw2 --info render --renderer opengles2`

**Comment by icculus** [comment]
Oh, huh, I probably disabled batching by accident too. I'll check when I get to the office.

**Comment by icculus** [comment]
As for the revision history: GitHub's importer screwed up and made everything a child of that one commit, which appears to contain the entire repository. The other commits are there, just everything ended up as a descendent of that one random commit. I don't know why. It's only a problem when looking up extremely old revision history, but I've hit this problem several times now.

What I've been doing is looking at an old copy of the mercurial repo for things that need really ancient history, and then looking up the hg.libsdl.org URL, which knows how to redirect to the proper GitHub commit.

I don't know how to fix this, short of manual editing of the git history and a force-push to main, which seems like an insane idea.

**Comment by sezero** [comment]
> What I've been doing is looking at an old copy of the mercurial repo for things that need really ancient history, and then looking up the hg.libsdl.org URL, which knows how to redirect to the proper GitHub commit.

I usually use https://github.com/SDL-mirror/SDL for that

**Comment by icculus** [comment]
> I don't know how to fix this, short of manual editing of the git history and a force-push to main, which seems like an insane idea.

That being said, I'm not _against_ the idea. I'm going to open a bug report as a "let's figure this out some day" thing, but if we were to ever do this, we'd want to do it _very_ carefully with a lot of experimentation in a temporary fork, first.

But at any rate, let's move discussion out of this bug.

**Comment by 1bsyl** [comment]
Thanks for the info SDL-mirror seems a good solution for me until this gets hopefully fixed :)

**Comment by icculus** [comment]
I went back and checked this, and the client-side arrays are _slightly_ faster on this laptop's integrated GPU:

OpenGLES 2, with SDL_RENDER_BATCHING, this time:

| approach | line method | FPS   |
|---------------|------------------|---------|
| VBOs        | 1                 | 2411 |
| CSAs        | 1                 | 2776 |
| VBOs        | 2                 | 5299 |
| CSAs        | 2                 | 5324 |
| VBOs        | 3                 | 5056 |
| CSAs        | 3                 | 5129 |

When not batching, it's likely the driver is just smart enough to copy the client-side data to a VBO and send it in one blast when necessary (which is to say, they just moved batching to the driver level).

Obviously the real win was _batching_, and on a discrete GPU there likely isn't _any_ win in batching mode, and the performance difference is negligible here anyhow.

But since it's easy to force a renderer and not batching (as we all made this mistake!), I think keeping the client-side arrays is a good idea.

**Comment by 1bsyl** [comment]
makes sense :)
just wondering if you should then merge this PR:
SDL_Renderer do Opengl batching: #5204

**Comment by slouken** [comment]
Yep, I'm wondering too. @icculus, you want to merge #5204 if that makes sense?

**Comment by arrowgent** [comment]
ive done similar comparison tests on a raspberry pi 4b using Mesa

using native opengl2, opengles/gles2 and gl4es conversion api

testing on a low powered device like this shows some issues with what would be expected to be GLES having better performance metrics, when its apparently not true.


my testing involved: glmark2, dosbox, yamagi-quake2, etc

https://github.com/glmark2/glmark2
glmark2 provides opengl2 and opengles2 binary executables

https://github.com/ptitSeb/gl4es
conversion layer for OGL to GLES


for mesa displaying graphics fps:
```
_mesa_fps.sh_
#!/bin/bash

GALLIUM_HUD="simple,fps+cpu" "$@"
```

mesa_fps.sh [application]
