### ISSUE TITLE
[autoconf] soversion is wrong for 2.0.20

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#5213]
Someone sent this to me and I see it on my system too... it looks like the filename was incremented incorrectly:

```
build/.libs/libSDL2-2.0.so.0.18.2
```

Everything else is still right so it shouldn't break anything unless someone went out of their way to link to the incorrect thing, but it's definitely worth checking out.

**Comment by slouken** [comment]
No, that's correct. It means 18 minor versions with function additions and 2 minor versions without any ABI changes.

**Comment by christianhaitian** [comment]
so uh, how is this 2.0.20?  It's a little confusing.  Shouldn't it just be SDL 2.0.18.2?

**Comment by flibitijibibo** [comment]
This was a misread on my end - see #5217 for a better discussion on this.
