### ISSUE TITLE
Emscripten : error: undefined symbol: SDL_strtokr

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#5216]
I am currently having the following error when using use SDL=2 flag with Emscripten

```
error: undefined symbol: SDL_strtokr (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _SDL_strtokr may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

This is a recent error using latest Emscripten. I remember there was a conversation to use SDL2 directly from here instead of Emscripten ports. Did this actually happen? Is the commit tied to somewhere in Emscripten/EMSDK now or am I always getting the main branch from here now?

If EMSDK is tracking main branch, it would be great if there was a `latest-release` branch and EMSDK tracked that instead and it only got merged from main branch on releases.

**Comment by sezero** [comment]
You are not including src/stdlib/SDL_strtokr.c in your emscripten builds

**Comment by ericoporto** [comment]
This means the error is probably this: https://github.com/emscripten-core/emscripten/pull/15985

**Comment by sezero** [comment]
Looks like it, yes. Closing as invalid.

**Comment by ericoporto** [comment]
@Daft-Freak is there any plans to move build to here instead of that python script? It seems it always get out of sync and blows up in my face.
