### ISSUE TITLE
Revision history is broken

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5220]
> As for the revision history: GitHub's importer screwed up and made everything a child of that one commit, which appears to contain the entire repository. The other commits are there, just everything ended up as a descendent of that one random commit. I don't know why. It's only a problem when looking up extremely old revision history, but I've hit this problem several times now.
>
> What I've been doing is looking at an old copy of the mercurial repo for things that need really ancient history, and then looking up the hg.libsdl.org URL, which knows how to redirect to the proper GitHub commit.
>
> I don't know how to fix this, short of manual editing of the git history and a force-push to main, which seems like an insane idea.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5206#issuecomment-1011140440_

**Comment by icculus** [comment]
This was the email I sent to GitHub before, for the sake of having the details in one place:

> GitHub imported our Mercurial repository incorrectly! This thing has lived through CVS, Subversion, and Mercurial before landing on GitHub, so it wouldn't surprise me if the data was straight up goofy in some way, but Mercurial could parse it correctly, so it seems like a bug in the GitHub importer. In practice, this doesn't affect us day to day, but if we have to get a "blame" of a file, or bisect for a very old bug, etc, eventually the git repo will believe the entire repository originated in this random commit that appears to incorrectly contain an entire copy of everything:
>
> https://github.com/libsdl-org/SDL/commit/0e45984fa036fff1912c62fee3ed4f5481f3c324
>
>The commit has no parents, and there is plenty of revision history in the repo that predates this arbitrary commit. I don't know what happened there. I just tried a fresh import of the Mercurial repo to a new private repo, and the import bug is still present.
>
> In these cases, I keep a local backup copy of the Mercurial repository to see into the distant past before this wonky commit, which is definitely not ideal.
>
> Discussion about this on our end:
>
> https://discourse.libsdl.org/t/migration-to-github-is-in-progress/28730/3
>
> Ticket filed with GitHub (which is listed as "not found" for me at this point)...
>
> https://support.github.com/ticket/personal/0/1019843
>
> I'm not sure this is _fixable_ now, short of force-pushing the entire gigantic repo, which sounds like a huge risk. But I would honestly love a GitHub engineer to take a thorough look at it someday and maybe talk me through what happened or what can be done, if anything.

**Comment by icculus** [comment]
> perhaps you have (intentionally?) removed pre-SDL 2.0.0 commits from Hg history?

We did, but the complete history was also imported:

https://github.com/libsdl-org/SDL-historical-archive/

The import went bad on that one too.

**Comment by icculus** [comment]
Also, it's worth noting that https://hg.libsdl.org/SDL/ redirects web browsers to the appropriate github URLs, but we check the User-Agent; actual Mercurial clients can still talk to that URL to clone.

**Comment by Ericson2314** [comment]
Yes it would be good to have this fixed. I am trying to backport pkg-config support to SDL 1's `sdl.m4` so I can cross compile old games. Having more history would help!

**Comment by sezero** [comment]
>  trying to backport pkg-config support to SDL 1's `sdl.m4`

sdl.m4 of SDL-1.2 has pkg-config support for quite some time already.

**Comment by Ericson2314** [comment]
Hmm. Is https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/libraries/SDL/default.nix due for an update?

**Comment by icculus** [comment]
I'm wondering if we could rewrite history not just so this fixes the problem but also all the existing commits can continue to live in the repo with the same hashes, just on an unnamed branch we never look at again...but so that web pages that reference those commits continue to work.

And if this _can_ work, does it make an already-large repo unmanageably larger?

Part of me wants to fix this in a separate SDL3 repo and archive the current one, but then we'd have to deal with the bugtracker, etc.

Then again, maybe walking away from all the 10-year-old open bugs is a good idea too.  :)

**Comment by okuoku** [comment]
> I'm wondering if we could rewrite history not just so this fixes the problem but also all the existing commits can continue to live in the repo with the same hashes, just on an unnamed branch we never look at again...

On GitHub, commit is shared among fork network so you can create a fork for archive and forget about it. For example, my unmerged commit https://github.com/okuoku/SDL2/commit/c92f3fe72439022a677b875356d9b25cf8517cb6 is also appear on SDL2 https://github.com/libsdl-org/SDL/commit/c92f3fe72439022a677b875356d9b25cf8517cb6 .

Unfortunately, I cannot find any source that prove it's a feature of GitHub; it can be just an easter-egg.

> And if this can work, does it make an already-large repo unmanageably larger?

No. Git clone won't fetch objects that isn't referenced with branch/tags of origin repository. e.g.) Above example `c92f3fe72439022a677b875356d9b25cf8517cb6` is not included if one cloned https://github.com/libsdl-org/SDL/ although it appear on GitHub web interface when directly referenced it with URL.

```
$ git show c92f3fe72439022a677b875356d9b25cf8517cb6
fatal: bad object c92f3fe72439022a677b875356d9b25cf8517cb6
```

**Comment by Ericson2314** [comment]
Yeah, you could even use a "non-branch" ref and then it will not be in forks or clones with the default refspec IIUC.

**Comment by slouken** [comment]
@icculus, I keep running into this trying to find the history of old commits. Is it possible to splice together SDL-mirror's history and our history and do a force-push? We'd do it once, and everyone would have to resync, but maybe it's worth it?

**Comment by icculus** [comment]
I hate this too, but untangling this is going to change the hash on _every_ commit in the repository (git hashes are not self-contained; the parent hashes are part of the child commit's hashes). I _think_ github will continue to honor web links to those old hashes indefinitely (but report them as "commits that are outside the repository"), but I don't know if that's always going to be true.

But mostly, it's just feels like an enormously risky thing to do. It'll almost certainly break every Pull Request that's still open, cherry-pick commit messages will mention a no-longer-existing hash [^1], and maybe lots of other things I'm not even considering.

I'm willing to entertain the idea of attempting to rebase the thing or figure out how to graft it onto SDL-mirror, but I think it's going to be difficult to clean up, even with the risks aside.

[^1]: To be fair, all our commits that say "Fixes Bugzilla #XXXX" link to the wrong GitHub bug report, and hg hashes that got mentioned are obviously bogus, and we survived both these things.

**Comment by slouken** [comment]
Okay, then I'll go ahead and close this. It's broken, we accept that.

**Comment by icculus** [comment]
(That being said, the first step is figuring out _how_ to clean this up, so if someone comes along and reads this at some point, and figures out how to get all our new commits on top of all our old commits, or the magic to rebase everything in the existing repository onto the correct parents, put it somewhere I can clone it and we'll talk about the ramifications of force-pushing...but I haven't figured out _how_ to clean this up in the first place, yet.)

**Comment by mirh** [comment]
I don't have anything figured out, though I was looking through old bug reports (in turn referencing old mercurial revisions), and for some reason my university firewall is blocking your domain. 
Is there any other way than your website to look up the new corresponding commits?
