### ISSUE TITLE
Feature request: Open Android_JNI_SendMessage() to the public, e.g. SDL_AndroidSendMessage()

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#5221]
This would negate the need for Android app developers making extra JNI functions if we can just use @Overide onUnhandledMessage() in our custom MainActivity. Obviously it would reject messages below COMMAND_USER (0x8000). It can be used to set achievements, load ads, etc, without the need to use SDL_AndroidGetJNIEnv(), SDL_AndroidGetActivity(), GetObjectClass(), GetStaticMethodID, etc.

Surely very useful and not much work to make happen?

**Comment by slouken** [comment]
Seems reasonable...

**Comment by 1bsyl** [comment]
@AntTheAlchemist fell free to propose a patch :)

Just to remark : 
- the C Jni would be called from the SDL app thread (eg. you main() ) then it calls java sendMessage (still the SDL App thread).
- but in the end, the java is executed in the Activity Java thread (SDLCommandHandler)

So maybe we would also need at some async acknowledgment ?

Also, maybe it would need more that 1 parameter, not sure ?

**Comment by AntTheAlchemist** [comment]
@1bsyl Wouldn't know where to begin with proposing a patch

No async needed, nothing extra is needed, not any code. Just move Android_JNI_SendMessage() to the front-end. Or at the very most add a new front-end method that just calls Android_JNI_SendMessage(). An int is already used by this existing SDL JNI as a parameter, and boolean returned, which makes it super-useful. These messages can be easily picked up java side in onUnhandledMessage.  I'm already using it, but I had to add my own method because I can't access SDL's private one which does exactly the same thing:

```
	JNIEnv* env = (JNIEnv*)SDL_AndroidGetJNIEnv();
	jobject activity = (jobject)SDL_AndroidGetActivity();
	cl = env->GetObjectClass(activity);
	jandroid = env->GetStaticMethodID(cl, "sendMessage", "(II)Z");
	env->DeleteLocalRef(activity);
	env->CallStaticBooleanMethod(cl, jandroid, command, param);
```

**Comment by 1bsyl** [comment]
@AntTheAlchemist added, please give a try ! thanks
