### ISSUE TITLE
Memory leak in SDL_GL_CreateContext on windows.

### ISSUE THREAD

**Issue by shangjiaxuan** [libsdl-org/SDL#5222]
Initializing and shut down multiple times within the same process shows consistent number of leaked allocations from given function on windows. Each restart adds a few MB of memory leaked. [memory snapshots](https://forum.nepfan.club/assets/files/2022-01-13/1642054525-733732-sdl-leak.png)

**Comment by shangjiaxuan** [comment]
[Location of leak](https://forum.nepfan.club/assets/files/2022-01-13/1642054666-243119-sdl-leak-location.png)

**Comment by shangjiaxuan** [comment]
Corresponding DeleteContext IS called.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
