### ISSUE TITLE
linux: joystick: axis values not zero at rest unlike jstest

### ISSUE THREAD

**Issue by jcelerier** [libsdl-org/SDL#5224]
Hello,
when I move my joystick (thrustmaster t.flight stick X) in jstest, it goes back to zero when I stop handling it.

But with SDL, the value I get  in "rest position" from SDL_JOYAXISMOTION seems to be 128.

jstest's range is  -32767..32767 while SDL is -32768..32767 so I don't think that accounts for the difference of 128.

cheers

**Comment by slouken** [comment]
jstest is applying a deadzone to the controller while SDL provides the raw axis values. Applications generally build their own dead zone handling, so SDL provides the raw values. This is by design.

**Comment by jcelerier** [comment]
hm ok thanks, I wouldn't have expected jstest to have a deadzone
