### ISSUE TITLE
The window won't show when I run SDL2 program by xcode

### ISSUE THREAD

**Issue by StarSugar** [libsdl-org/SDL#5226]
I am a new SDL2 user. When I use xcode to write SDL2 program, the window I create is not showing. Although there is a logo in the program dock, there is no window after clicking it.
```c
int main(int argc, const char * argv[]) {
    // insert code here...
    if(SDL_Init(SDL_INIT_VIDEO) < 0){
        printf("\nThere is a error:%s\n",SDL_GetError());
    }
    SDL_Window* window;
    window=SDL_CreateWindow("text", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 640, SDL_WINDOW_SHOWN);
    if(window == NULL){
        printf("\nerror is %s\n",SDL_GetError());
    }
    SDL_Surface *surface = SDL_GetWindowSurface(window);
    SDL_FillRect(surface, NULL, SDL_MapRGBA(surface->format, 0xFF, 0xFF, 0xFF, 1));
    SDL_UpdateWindowSurface(window);
    SDL_Delay(10000);
    SDL_DestroyWindow(window);
    SDL_Quit();
}
```
I look forward to your reply.

**Comment by icculus** [comment]
You probably need an event loop or macOS won't actually finish creating the window.

```c
int main(int argc, const char * argv[]) {
    // insert code here...
    if(SDL_Init(SDL_INIT_VIDEO) < 0){
        printf("\nThere is a error:%s\n",SDL_GetError());
    }
    SDL_Window* window;
    window=SDL_CreateWindow("text", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 640, SDL_WINDOW_SHOWN);
    if(window == NULL){
        printf("\nerror is %s\n",SDL_GetError());
    }
    SDL_Surface *surface = SDL_GetWindowSurface(window);
    SDL_FillRect(surface, NULL, SDL_MapRGBA(surface->format, 0xFF, 0xFF, 0xFF, 1));
    SDL_UpdateWindowSurface(window);

    // don't do this
    //SDL_Delay(10000);

    // try this instead...
    SDL_bool quit = SDL_FALSE;
    while (!quit) {
       SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                quit = SDL_TRUE;
            }
         }
    }


    SDL_DestroyWindow(window);
    SDL_Quit();
}
```

The new piece of code basically says "let the OS do what it needs to do forever, and let me know when the user requested to quit the application, so I can continue on to shut everything down."

(Also, when you get a little further, instead of using SDL_GetWindowSurface and SDL_UpdateWindowSurface, check out the render API, but let's get you up and running before we worry about that.)

**Comment by StarSugar** [comment]
Thank you very much! I was afraid of nobody will answer me as the problem is so elementary.

**Comment by icculus** [comment]
Okay, this is resolved I think. I would appreciate it if these sort of questions moved over to our forums at https://discourse.libsdl.org/ or our Discord chat room, though, as this is our bug tracker.  :)
