### ISSUE TITLE
HIDAPI deadzone behavior issues with Xbox One controllers

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#5227]
16f5b9e3c33316b257c7dcc689d7df0efe6c0cae introduces some deadzone-related issues with my Xbox One controllers using HIDAPI.

The most major issue is that the joystick axes snap to cardinal directions. This leads to difficulty making precise movements around cardinal directions. Here is a video demonstrating the issue when moving the left stick smoothly in a circular motion:

https://user-images.githubusercontent.com/2695644/149642102-52bac083-b331-4451-82fc-0114b14c24de.mov

Another issue is that the axes aren't scaled to behave linearly after the deadzone is applied. This means the axes jump abruptly from 0% to 20%, making small precise movements difficult. Here is a video demonstrating the issue when moving the left stick around the center position:

https://user-images.githubusercontent.com/2695644/149642171-c0ef3702-35d4-464d-9f8a-710b52e8e66e.mov

Finally, I'm not sure if using the hardcoded XInput deadzones is a good idea. Those were created during the Xbox 360 era (15 years ago) and controller manufacturing tolerances have gotten much better since then. My Xbox Series X controller can perform precise movements of the sticks and triggers at positions well within the XInput deadzones. Maybe it's best for the application to handle deadzones themselves (like they do for the other joysticks APIs)?

**Comment by slouken** [comment]
Hmmmmmmm. Okay, I'll disable them for now, thanks!
