### ISSUE TITLE
Request: Update CMake documentation to include game projects using cmake and SDL2

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#5237]
CMake documentation is not updated: https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md

It's written with the perspective that only SDL2 is being built with it. A common usecase is probably the one that mentions CMake in the Android case, where CMake is seen as the build system for the project the user is developing - a game, and engine or just some app that uses SDL2 features.

There is even an issue that mentions using SDL2 through fetch and add subdirectory (#2010), and a lot of issues dealing with building SDL2 statically. So my guess is a more useful CMake documentation would detail the usecase of CMake as the build system used on the user project when building for supported platforms.

**Comment by slouken** [comment]
I don't use CMake myself, so please feel free to make suggested edits in a pull request.

**Comment by slouken** [comment]
@madebr, should this file have some of the documentation you're updating on the Wiki?

**Comment by icculus** [comment]
Let's bump this and the PR to 2.26.

**Comment by slouken** [comment]
This is the first release with non-experimental CMake support, so I'd like the documentation updated for the release, if possible. @madebr has a change ready, it just doesn't merge cleanly at the moment. I'm hoping this is 5 minutes of cleanup for merge.

**Comment by slouken** [comment]
Changing the Android flow is definitely out of scope for this milestone, and needs discussion for how best to do and retain support for the old workflow.

**Comment by madebr** [comment]
I've been thinking. I would keep CMake support of the SDL main project experimental until I've made sure every cmake configuration option name has the same name layout and checked its behavior is "conform".
Unless we mean by removing the "experimental", we support it and will fix all issues, but do not commit on supporting every cmake configuration option.

Right now, the CMake configuration has `SDL2_xx` and `SDL_xx` options.
I'm not sure what naming convention is best.
For the SDL satellite projects, we've settled on using e.g. `SDL2IMAGE_xxx`.
For SDL, I suppose switching to `SDL2_xxx` would be a too big break so I will stick to `SDL_xxx`.

Also, I've restrained myself from changing too much in the cmake script.
I would like to do some refactoring in the next development cycle, and avoid having to support the current names. (Externally, there probably won't change much, only the SDL2_*` options will disappear)

**Comment by slouken** [comment]
That sounds good. Does that mean the documentation is fine as-is, or should we try to merge your PR?

FWIW, when we bump the satellite libraries to SDL3IMAGE, etc. we should remove the version number so future version bumps don't immediately break everyone's build scripts.

**Comment by icculus** [comment]
I'm assuming the thumbs-up reaction is for the removing the version number eventually...but should we try to merge your PR for 2.24.0, @madebr?  :)

**Comment by icculus** [comment]
Okay, the PR is merged and we have a separate issue for the future plans @madebr mentioned, that I've put in the 2.26 milestone for now. We're good here for 2.24, though, so I'm closing this issue. Thanks everyone!

**Comment by madebr** [comment]
Yes, I thumbed-up the remark about version numbering in the cmake option variables.
My apologies if this wasn't clear.

About documentation, that can always be improved/extended.
I would keep it KISS though.
Our CMake build scripts + generated cmake configuration files behave "normal" and should not need much extra explanation.
I would  just give code examples on how the library can be used and be done with it.

In this case, it's the Android build system that is the "ugly duckling".
