### ISSUE TITLE
Windows: user un-minimization breaks if non-resizable window was maximized via code

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#5240]
On Windows, if a SDL window is programmatically maximized (via `SDL_MaximizeWindow` or by creating the window with `SDL_WINDOW_MAXIMIZED`) while the window is *not* resizable, and then the user presses the window's minimize button, attempts to un-minimize the window via the task bar or alt-tab will fail (the window won't become properly visible).

macOS, on the other hand, seems to prevent any programmatic maximization of the window if it doesn't the have resizable flag set. This sort of makes sense to me because the resizable flag determines whether users can press the maximize button too (maximize is a resize operation). I'm not sure whether the best fix for Windows is to address the visibility/un-minimize issue or to prevent maximization if the window doesn't have the resizable flag.

Here's some code which reproduces it for me given the above steps:
```c
#include "SDL.h"

int main(int argc, char* argv[])
{
    int running = 1;
    SDL_Window* window;
    SDL_Renderer* renderer;
    int w = 640;
    int h = 480;

    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_EVENTS);

    window = SDL_CreateWindow("Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                        w, h, 0 /*| SDL_WINDOW_RESIZABLE*/ | SDL_WINDOW_MAXIMIZED);
    renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

    while (running)
    {
        SDL_Event ev;
        while (SDL_PollEvent(&ev))
        {
            switch (ev.type)
            {
            case SDL_QUIT:
                running = 0;
                break;
            case SDL_KEYDOWN:
                if (ev.key.keysym.sym == SDLK_m)
                    SDL_MaximizeWindow(window);
                break;
            }
        }

        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
    }

    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
}

```

This was originally reported in the LÖVE repository: https://github.com/love2d/love/issues/1716

**Comment by slime73** [comment]
If I change the above code to programmatically minimize the window after it's been maximized (eg change the keydown to call SDL_MinimizeWindow) I can also reproduce the problem. So it doesn't depend on the user pressing the minimize button, just the minimize operation happening at all while the window is in that state.

**Comment by madebr** [comment]
When doing the steps below, the application suddenly has 2 windows (the screenshot shows 1 terminal + 2 windows)
![part](https://user-images.githubusercontent.com/4138939/212497724-32228312-a3fa-4f16-a0dd-42886307b044.png)

1. Maximizing the window (using <kbd>m</kbd>)
2. Minimize the window
3. Right click on the icon in the task bar, and click on `<name_of_executable>.exe`
4. Minimize the window
5. Left click on the icon in the task bar
