### ISSUE TITLE
U8 audio conversion table is wrong?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5250]
> What was this change? https://github.com/pionere/SDL/commit/1882e6e93fbb6995262f85953c54349a0edc2c88 Better sound quality? These values have been there since the first revision of the CVS repository, 20+ years ago, so a little clarification would help me here before we change it. If it sounds better or fixes a bug, etc, let's definitely pull this in, though.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019428704_

**Comment by icculus** [comment]
This one is for Sam: this code was in the _first CVS commit_ so it showed up somewhere before we moved from Loki to devolution.

@pioneer points out, reasonably:

> I don't see a reason why the original change (from 0xFF to 0xFE) was necessary. If you apply the logic of 
https://github.com/pionere/SDL/commit/456a0431482c78519fa8d671e68901fa9fd99a40 to U8, then 0xFF should be used.

So do you have any idea why this was changed from ARDI's original values, 20+ years ago?  :)

**Comment by slouken** [comment]
I have NO idea :)

**Comment by icculus** [comment]
I'm inclined to merge that change, then. It seems more correct...?
