### ISSUE TITLE
Rename/move MFI joystick sources?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5251]
> Most of https://github.com/pionere/SDL/commit/2adda5b42f4733470d0db47981b753a185c44031 seems good, but despite being in an "iphoneos" directory, SDL_mfijoystick.m is used on macOS, too (MFI devices, "Made For iOS," obviously started there, but the API was added to macOS later).

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019428704_

The MFI joystick stuff probably should be moved to the "darwin" directory...? Or maybe just move everything in "darwin" and "iphoneos" to an "apple" directory?

(This is kind of a pedantic, minor cleanup.)

**Comment by pionere** [comment]
4a43321c81c085a11652188cd118a884a6c85814

**Comment by slouken** [comment]
This was done in cc1f9eb983a056bd4fd19dc4b8699c8b5d1cce77.
