### ISSUE TITLE
Split up and commit pionere's cleanup patch

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5252]
> This cleanup patch (https://github.com/pionere/SDL/commit/f8a63d295d1ed6c36d5a4180542dc4730ad3fd12) is mostly good, but it needs to be broken down into separate commits, I think. Just making a note here so I remember to come back and do that. I'll move this to a separate issue so it isn't forgotten.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019428704_

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
