### ISSUE TITLE
Add dummy thread implementation?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5253]
> I haven't added the dummy thread implementation (https://github.com/pionere/SDL/commit/4bf613e96b15d3087b43f10997b78d0932331e39) because there's already a weird tapdance with the "generic" stuff in SDL already, and I need to look at this more, but after looking over the whole patchset, Sam and I are of the opinion that "disabling" a subsystem _should not remove the API_, but just leave a stub there...so most of the bulk can evaporate out of a build, but the function is still available (even if that function just returns immediately with a failure)...which is to say we're probably going to want this patch once I research more.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019428704_

**Comment by slouken** [comment]
Enough subsystems in SDL rely on threads that we've come to the conclusion that we don't want a dummy thread implementation. Threads are generally supported on platforms these days, so we shouldn't need to worry about it going forward.
