### ISSUE TITLE
See if RWOPS can cleanly fail if disabled.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5254]
> We think (perhaps incorrectly!)  that these sort of patches are unnecessary, as (we hope) the RWops calls will correctly fail and not need a special `#ifdef` to get the right results: https://github.com/pionere/SDL/commit/6c3e1e8106bb048bfcc5e5d8d93d5bdb53e5e1a4  ...if that isn't the case, we would rather SDL be fixed to work that way instead of adding these `#ifdef` checks.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019428704_

I need to look over this, @pionere says it doesn't work how we think it does.

**Comment by slouken** [comment]
He's right, that define doesn't actually turn anything off. The question is, do we want to make it work, or do we want to remove that define? We should sit down and think about the goals of removing subsystems and how we want to handle that in general.

**Comment by icculus** [comment]
I want to punt serious redesigns into SDL3, but if the fix (make it fail correctly when disabled so we don't have ifdefs all over), is small, I'd like that for SDL2.

**Comment by slouken** [comment]
Sounds good.

**Comment by slouken** [comment]
We decided that IOStream is core functionality in SDL 3.0, so you don't need to disable it (and disabling it won't reduce the library size much)
