### ISSUE TITLE
 test\testgles2.c shows 'WebGL: INVALID_OPERATION' error when build with emscripten . 

### ISSUE THREAD

**Issue by bing2008** [libsdl-org/SDL#5258]
Hey! 
I am using SDL2 in Emscripten to build my app , this is the info :
 
OS: win10 64bit
Emscripten version :  3.1.0 (latest for now)
SDL Version :  2.0.10  (download by emsdk when add '-s USE_SDL=2' flag in build command line )
tests :  test\testgles2.c
build cmd : 
```
@REM build.bat
set "PATH=%PATH%;D:\App\emsdk\emsdk\upstream\emscripten;C:\Program Files\CMake\bin;c:\Program Files\Git\bin;D:\Anaconda3\envs\py36;C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin;"
set "PYTHONIOENCODING=utf8"
set "PYTHONUTF8=1"

@REM emsdk_SDL_24 :v 2.0.10
call D:\App\emsdk\emsdk\upstream\emscripten\emcc.bat E:\EMSDK_SDL2-version_24_V2_0_10\test\testgles2.c E:\EMSDK_SDL2-version_24_V2_0_10\src\test\SDL_test_common.c E:\EMSDK_SDL2-version_24_V2_0_10\src\test\SDL_test_memory.c E:\EMSDK_SDL2-version_24_V2_0_10\src\test\SDL_test_crc32.c -o emBin\testgles2.html -s USE_SDL=2 -O2 -I e:\EMSDK_SDL2-version_24_V2_0_10\include\

pause
```

The build was success , bug when run in web broswer , it don't show the 3D view and there errors in console : 

`VM1368:3 WebGL: INVALID_OPERATION: vertexAttribPointer: no ARRAY_BUFFER is bound and offset is non-zero`

After some search and google , i think that's the diffrent between [WebGL](https://developer.mozilla.org/zh-CN/docs/Web/API/WebGLRenderingContext/vertexAttribPointer) and [OpenGL](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml)( include [ES](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glVertexAttribPointer.xml)) about  'glVertexAttribPointer' function .  The last parameter is offset in webgl , but a point in OpenGL and ES . So i added some code to ' test\testgles2.c' like below :
```
#if __EMSCRIPTEN__

		GLuint vertexBufferObj;
		GL_CHECK(ctx.glGenBuffers(1, &vertexBufferObj));
		GL_CHECK(ctx.glBindBuffer(GL_ARRAY_BUFFER, vertexBufferObj));
		GL_CHECK(ctx.glBufferData(GL_ARRAY_BUFFER, sizeof(_vertices) * 4, _vertices, GL_STATIC_DRAW));
		GL_CHECK(ctx.glVertexAttribPointer(data->attr_position, 3, GL_FLOAT, GL_FALSE, 0, 0));
		GL_CHECK(ctx.glBindBuffer(GL_ARRAY_BUFFER, 0));

		GLuint colorBufferObj;
		GL_CHECK(ctx.glGenBuffers(1, &colorBufferObj));
		GL_CHECK(ctx.glBindBuffer(GL_ARRAY_BUFFER, colorBufferObj));
		GL_CHECK(ctx.glBufferData(GL_ARRAY_BUFFER, sizeof(_colors) * 4, _colors, GL_STATIC_DRAW));
		GL_CHECK(ctx.glVertexAttribPointer(data->attr_color, 3, GL_FLOAT, GL_FALSE, 0, 0));
		GL_CHECK(ctx.glBindBuffer(GL_ARRAY_BUFFER, 0));
#else
		/* Populate attributes for position, color and texture coordinates etc. */
		GL_CHECK(ctx.glVertexAttribPointer(data->attr_position, 3, GL_FLOAT, GL_FALSE, 0, _vertices));
		GL_CHECK(ctx.glVertexAttribPointer(data->attr_color, 3, GL_FLOAT, GL_FALSE, 0, _colors));
#endif
```
That will show the cube successed.

So am i doing right ? are there anyone reach this problem? or there are some better solution about this ? tell me pls!

**Comment by icculus** [comment]
2.0.10 is extremely old; are you sure this is the latest version Emscripten offers with USE_SDL=2 and not some old copy your computer had already?

**Comment by icculus** [comment]
Oh, but to answer the question: WebGL does in fact need vertex buffer objects, as you discovered. Emscripten can simulate client-side arrays on WebGL. It just manages the vertex buffer object for you. Build with -s FULL_ES2=1.

We should probably fix testgles2, though.

**Comment by icculus** [comment]
(and now I have fixed it. It won't need `-s FULL_ES2=1` now. Thank you!)

**Comment by bing2008** [comment]
Thank you @icculus too!

I checked the `-s FULL_ES2=1` flag , it's work. Glad to know that.
