### ISSUE TITLE
Incorrect input when focus is lost

### ISSUE THREAD

**Issue by ShaneYCG** [libsdl-org/SDL#5261]
WGI returns incorrect stick results when SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS is set and the window loses focus.

In WGI_JoystickUpdate the axis values are usually centered around 0.5, but when focus is lost GetCurrentReading returns all zeros. Without SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS these incorrect events are usually ignored, but with it enabled they propagate as incorrect inputs.

**Comment by ShaneYCG** [comment]
I am not very familiar with WGI but nothing jumped out at me as an obvious way to compensate for this other than ignoring 'all zero' axis values, as GetCurrentReading still returns S_OK.

**Comment by DJm00n** [comment]
Also related: WGI API will not work when app has no window or window is not in focus. See [Chuck Walbourn](https://stackoverflow.com/users/3780494/chuck-walbourn) answer at https://stackoverflow.com/q/57042069/1795050

**Comment by slouken** [comment]
Fixed, thanks!
