### ISSUE TITLE
 emscripten webassemly SDL could not get keyboard's caps/num locks in sync

### ISSUE THREAD

**Issue by qunying** [libsdl-org/SDL#5267]
I am not sure if this bug is caused in emscripten or in SDL code.

Please referring to bug report on [emscripten issues 16121](https://github.com/emscripten-core/emscripten/issues/16121)

**Comment by Daft-Freak** [comment]
There isn't a way to query the current caps/num lock state in JS, so we can't really know if we didn't see the `keydown/up` events.

(There is `.getModifierState()`, but that still needs to be used in a keyboard/mouse event handler... and there currently isn't any way of calling it)

**Comment by qunying** [comment]
Could we fire a keyboard event from JavaScript when focus is gain to get the right state?

**Comment by Daft-Freak** [comment]
Hmm, interesting idea... but apparently not

```js
document.addEventListener("keydown", e => console.log("caps?", e.getModifierState("CapsLock")))
document.dispatchEvent(new KeyboardEvent("keydown"))
"caps?" false
```
(in console, caps lock was on)

**Comment by qunying** [comment]
Another case that is possibly fixable, when the cap/num lock state is changed outside of browser, then when back to browser, after pressing a physical key, the cap/num lock state is not updated.
