### ISSUE TITLE
Inconsistent behaviour between KMS/DRM backend on RPI4 and default backend on linux desktop with ARGB8888 pixel format

### ISSUE THREAD

**Issue by alloncm** [libsdl-org/SDL#5273]
Hi Im using SDL in one of my [projects](https://github.com/alloncm/MagenBoy), and on windows or linux it runs just fine but when trying to port it to run on a Raspberrypi 4 running Raspbian with no desktop environment (without X) I stumbled upon some problems.

First I compiled SDL2 version 2.0.20   in order to enable the KMS/DRM backend like this:

```shell
# Install build deps
sudo apt install -y build-essential git libasound2-dev libsamplerate0-dev libibus-1.0-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libdrm-dev libgbm-dev
# Clone SDL
git clone https://github.com/libsdl-org/SDL
cd SDL
# Configure SDL
CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --prefix=/usr --disable-video-x11 --disable-video-wayland --disable-video-rpi --enable-video-kmsdrm --enable-arm-neon
# Compile and install 
make -j4
sudo make install
```

After I tried to ran my project but only saw a black screen with white flashes sometimes.

I wrote a simple C program to try and isolate the problem and came up with this program which uses the same features of SDL that my project uses.

```C
#include<stdio.h>
#define SDL_MAIN_HANDLED
#include<SDL.h>

#define WIDTH 160
#define HEIGHT 144
#define BUFFER_SIZE HEIGHT*WIDTH

int main(int argc, char* argv[]){
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window* window = SDL_CreateWindow("SDL_Test", SDL_WINDOWPOS_UNDEFINED_MASK, SDL_WINDOWPOS_UNDEFINED_MASK, WIDTH*sizeof(uint32_t), HEIGHT*sizeof(uint32_t), 0);
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);

// This is the suspicious line
    SDL_Texture* texture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, WIDTH, HEIGHT);

    uint32_t pixel_buffer[BUFFER_SIZE];

    memset(pixel_buffer, 0, sizeof(pixel_buffer));

    uint32_t color = 0x5050;

    // Make a square in the pixel buffer with color
    for (int i=0;i<50;i++){
        for (int j=0;j<50;j++){
            pixel_buffer[(i * WIDTH) + j] = color;
        }
    }

    SDL_Event event;
    while (1){
        if (SDL_PollEvent(&event) != 0){
            switch (event.type)
            {
            case SDL_QUIT:
                exit(0);
            case SDL_KEYDOWN:
                if (event.key.keysym.sym == SDLK_ESCAPE){
                    exit(0);
                }
            }
        }

        void* buffer;
        int pitch;
        SDL_LockTexture(texture, NULL, &buffer, &pitch);
        memcpy(buffer, pixel_buffer, BUFFER_SIZE * sizeof(uint32_t));
        SDL_UnlockTexture(texture);

        SDL_RenderCopy(renderer, texture, NULL, NULL);
        SDL_RenderPresent(renderer);
    }
    
    return 0;
}
```

This works on my windows (10) and linux (ubuntu) machines and also on the Raspberrypi 4 with X but on Raspberrypi 4 without X this produce a black screen with no square.

Changing the color to 0xFFFFFFFF (white) does produce an expected output, but any other color causes the square to disappear.

Furthermore, changing the texture pixel format from `SDL_PIXELFORMAT_ARGB8888` to `SDL_PIXELFORMAT_RGB888` solves the problem and the square appears on Raspberrypi 4 without X.
changing my project to use this pixel format also allowed it to work too.

By my understanding of SDL it is either me missing something obvious or this is a bug in the MKS/DRM backend.
Even tough I managed to find a workaround for this (using `SDL_PIXELFORMAT_RGB888` instead) this debugging session took me a whole weekend and a lot of self questioning whether I know what am I even doing :), so Ill be happy to hear what do you think about it (and of-course it is a bug or expected behavior and if yes what am I missing). 
 
Thanks in advance (and also for creating and maintaining this awesome project)

**Comment by Fredrum** [comment]
Just a wild guess as I don't really know...could it be an Alpha thing?
Since the alpha changes place in the order when you swap format.
I was reading about alpha issues here,
https://forums.raspberrypi.com/viewtopic.php?p=1964037&hilit=kms+alpha#p1964037

**Comment by alloncm** [comment]
Thanks for the quick replay!

I have looked into what you suggested, it seems like it is not pre-multiplied alpha issue.
Also I managed to display some colors with the `ARGB8888` pixel format and I think I know where the inconsistency comes from.

When I set the alpha channel values properly its rendering the square fine, the issue is about the inconsistency between the platforms (between windows and x11 linux and kms/drm linux).

After further inspections I noticed that the windows and X11 does not get effected by modifying the alpha component at all (while the KMS/DRM is).

I improved my testing script to this:
```C
#include<stdio.h>
#define SDL_MAIN_HANDLED
#include<SDL.h>

#define WIDTH 160
#define HEIGHT 144
#define BUFFER_SIZE HEIGHT*WIDTH

int main(int argc, char* argv[]){

    uint32_t endian_check = 1;
    if (*((uint8_t*)(&endian_check)) == 1){
        printf("little endian\n");
    }
    else{
        printf("big endian\n");
    }

    SDL_ClearError();
    if (SDL_Init(SDL_INIT_VIDEO) != 0){
        goto error;
    }

    SDL_ClearError();
    SDL_Window* window = SDL_CreateWindow("SDL_Test", SDL_WINDOWPOS_UNDEFINED_MASK, SDL_WINDOWPOS_UNDEFINED_MASK, WIDTH*sizeof(uint32_t), HEIGHT*sizeof(uint32_t), 0);
    if (!window){
        goto error;
    }
    SDL_ClearError();
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
    if (!renderer){
        goto error;
    }

    SDL_ClearError();
// This is the suspicious line
    SDL_Texture* texture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, WIDTH, HEIGHT);
    if (!texture){
        goto error;
    }

    const char* display_driver = SDL_GetCurrentVideoDriver();
    printf("SDL video driver %s\n", display_driver);

    SDL_RendererInfo renderer_info;
    SDL_ClearError();
    if (SDL_GetRendererInfo(renderer, &renderer_info)!= 0){
        goto error;
    }
    printf("SDL render driver %s\n", renderer_info.name);
    
    Uint8 alpha;
    SDL_GetTextureAlphaMod(texture, &alpha);
    printf("alpha: %d\n", alpha);

    for (int i=0;i<renderer_info.num_texture_formats;i++){
        printf("%s\n", SDL_GetPixelFormatName(renderer_info.texture_formats[i]));
    }

    SDL_ClearError();
    int vd = SDL_GetNumVideoDisplays();
    int dm = SDL_GetNumDisplayModes(vd-1);
    printf("num of video displays: %d\n", vd);
    printf("num of display modes: %d\n", dm);

    if (dm < 0){
        goto error;
    }

    SDL_DisplayMode display_mode;
    display_mode.format = 0;
    if (SDL_GetCurrentDisplayMode(0, &display_mode) != 0){
        goto error;
    }

    printf("Display mode format: %d | name:%s\n", display_mode.format, SDL_GetPixelFormatName(display_mode.format));

    uint32_t pixel_buffer[BUFFER_SIZE];

    memset(pixel_buffer, 0, sizeof(pixel_buffer));

    uint32_t color = 0x00505000;

    // Make a square in the pixel buffer with color
    for (int i=0;i<50;i++){
        for (int j=0;j<50;j++){
            pixel_buffer[(i * WIDTH) + j] = color;
        }
    }

    SDL_Event event;
    while (1){
        if (SDL_PollEvent(&event) != 0){
            switch (event.type)
            {
            case SDL_QUIT:
                exit(0);
            case SDL_KEYDOWN:
                if (event.key.keysym.sym == SDLK_ESCAPE){
                    exit(0);
                }
            }
        }

        void* buffer;
        int pitch;
        SDL_LockTexture(texture, NULL, &buffer, &pitch);
        memcpy(buffer, pixel_buffer, BUFFER_SIZE * sizeof(uint32_t));
        SDL_UnlockTexture(texture);

        SDL_RenderCopy(renderer, texture, NULL, NULL);
        SDL_RenderPresent(renderer);
    }

    return 0;

    error:
    printf("Error: %s\n", SDL_GetError());
    return 1;
}
```

The output on windows is:
```shell
little endian
SDL video driver windows
SDL render driver direct3d
alpha: 255
SDL_PIXELFORMAT_ARGB8888
SDL_PIXELFORMAT_YV12
SDL_PIXELFORMAT_IYUV
num of video displays: 1
num of display modes: 13
Display mode format: 370546692 | name:SDL_PIXELFORMAT_RGB888
```
And on my rpi4 with no X:
```shell
little endian
SDL video driver KMSDRM
SDL render driver opengl
alpha: 255
SDL_PIXELFORMAT_ARGB8888
SDL_PIXELFORMAT_ABGR8888
SDL_PIXELFORMAT_RGB888
SDL_PIXELFORMAT_BGR888
SDL_PIXELFORMAT_YV12
SDL_PIXELFORMAT_IYUV
SDL_PIXELFORMAT_NV12
SDL_PIXELFORMAT_NV21
num of video displays: 1
num of display modes: 1
Display mode format: 372645892 | name:SDL_PIXELFORMAT_ARGB8888
```
 I have noticed that on my windows machine and X11 Linux, even though Im configuring it to use ARGB8888, it actually uses RGB888 format and completely discards the alpha channel.

Im really not familiar enough with this project to tell if this is expected behavior, since this happens on both the opengl and directx renderers and windows and X11 video drivers it leads me to believe that this is expected behavior.

In case someone familiar with the internals would like to shed some light for me on this topic it would be great.
Any way it was really nice reading and investigating a project of this kind.

**Comment by slouken** [comment]
Yes, you have to do special work to enable the alpha channel on X11, so this is expected behavior. In general you want to use an RGB backbuffer for your application windows.
