### ISSUE TITLE
Can't immediately set window position after setting it to borderless

### ISSUE THREAD

**Issue by autoit4you** [libsdl-org/SDL#5274]
Hello,

while working on a project of mine I noticed I could not set the window position after setting it to be borderless because it crashes with the following error in the console:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x2802c77
  Serial number of failed request:  254
  Current serial number in output stream:  254
```

I'm using ArchLinux with:
Kernel: 5.16.3
Xorg: 21.1.3
SDL: 2.0.20

I found that with the following C-code I could reproduce it every single time I tried executing it:
```c
#include "SDL.h"

int main(int argc, char** argv)
{
    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS);
    SDL_Window* sdl_window = SDL_CreateWindow("test", 0, 0, 800, 600, SDL_WINDOW_OPENGL);

    SDL_Delay(1000);
    SDL_SetWindowBordered(sdl_window, SDL_FALSE);
    //SDL_Delay(1000); //nolonger crashes if you uncomment this
    SDL_SetWindowPosition(sdl_window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
    SDL_Delay(1000);

    SDL_DestroyWindow(sdl_window);
    SDL_Quit();
    return 0;
}
```

I could not find any existing discussion about this error, if there is/was please direct me there :)

Kind regards
Jonathan

**Comment by icculus** [comment]
This is likely a race condition between the X server still processing the window state change and SDL changing the next thing about it; I'm going to sprinkle around some XSync() calls to see if we can get SDL_SetWindowBordered to block until the X server says the change is in place.

**Comment by icculus** [comment]
Ok, it wasn't an XSync thing, it appears to be a "window manager is doing a lot of stuff behind the scenes and you might find your window is missing if you look at it at the wrong moment" thing, so now in the "wait a little for something to happen" loop in X11_SetWindowPosition, we now catch these errors and know to just continue to wait a little longer if an error fired.
