### ISSUE TITLE
CMake UWP builds are broken again

### ISSUE THREAD

**Issue by Cacodemon345** [libsdl-org/SDL#5282]
As the title says.

Right now the builds fail when compiling WGI due to its RAWINPUT usage which isn't available on UWP. Even if you somehow manage to get past this error with the joystick subsystem still building, other projects will fail to find the built library via CMake because the SDL2main target is actually non-existent.

**Comment by flibitijibibo** [comment]
Found a bunch of UWP patches while looking at a VVV update: https://github.com/microsoft/vcpkg/tree/master/ports/sdl2

**Comment by Cacodemon345** [comment]
Let's merge the UWP patches from it, shall we?

**Comment by sezero** [comment]
Applied two of the patches from there, i.e. https://github.com/libsdl-org/SDL/commit/c93e552068d14da2a5a8f77f11238ff288978fd2 and https://github.com/libsdl-org/SDL/commit/b5614d0c6e81fd1e127ad0444765a6e5a7a6ef3d

**Comment by flibitijibibo** [comment]
Build is working again according to Actions!

**Comment by sezero** [comment]
Yes, the CI failures were annoying.

If there are no other patches left to apply from there (I won't bother myself), then this can be closed.

**Comment by Cacodemon345** [comment]
CMake needs to be able to find the library without errors.

**Comment by sezero** [comment]
> CMake needs to be able to find the library without errors.

???

**Comment by flibitijibibo** [comment]
> Yes, the CI failures were annoying.
> 
> If there are no other patches left to apply from there (I won't bother myself), then this can be closed.

I don't think the rest are useful, at least not as-is. In order:

1. Add support for pkgconfig on Windows
2. Add option to disable ibus via CMake option
3. Add option to disable SDLmain via CMake option

There's one more patch for the annoying Windows CRT macros that I don't think would ever be applied...

**Comment by sezero** [comment]
Close then?
