### ISSUE TITLE
on linux thread name does not change if the given string is longer than 16 characters

### ISSUE THREAD

**Issue by ohsix** [libsdl-org/SDL#5283]
pthread_setname_np returns ERANGE and doesn't even try to set the name

the documentation for SDL_CreateThreadWithStackSize mentions the limit on linux, and says SDL will try and munge the string but it doesn't

  josh

**Comment by 1bsyl** [comment]
Fixed, and also changing call SDL_snprintf() to SDL_strlcpy()

**Comment by icculus** [comment]
I'm case this limit ever changes, would it be better to try to set the original string and then retry with 16 chars if we get ERANGE?

**Comment by 1bsyl** [comment]
I've also hesitated because I read this was a kernel limitation.
But maybe this is better to do so.

**Comment by 1bsyl** [comment]
... and fix compilation for RISCOS which didn't know ERANGE https://github.com/libsdl-org/SDL/commit/df0d696a620bf0bcf946c680ec43f31ee02136cb

**Comment by ohsix** [comment]
thank you for fixing this. it doesn't hurt to check ERANGE in case it gets bigger later.

there used to be lots of arguments about how the api for prctl / /proc/[tid]/comm could never change, but it seems attitudes have softened https://lkml.org/lkml/2021/10/13/377

they've fixed a lot of old bugs that made prctl the de-facto way to set the process name as well. now a future glibc can seek on that file to see the true length and write that length directly to it without the (completely different!) write truncation problems it used to have

josh
