### ISSUE TITLE
Couldn't find "libSDL2.so"

### ISSUE THREAD

**Issue by rumplestilzken** [libsdl-org/SDL#5285]
I am trying to build SDL2, using the android-project folder from your github, for android using android studio and when i get my app built and it is sent to the android device i get a message ending in "couldn't find "libSDL2.so"". How can i resolve this issue?

I read about a post from a few years ago that said you had to build the ndk portion on its own, is this still true? I haven't gotten it building running the ndk from the terminal.

When attempting to build using NDK i get "Your APP_BUILD_SCRIPT points to an unknown file: /home/nick/development/extenal_git/SDL/jni/Android.mk"

**Comment by aquawicket** [comment]
if you are on windows try this:

cd into the android-project directory and run this command
`gradlew clean build --info`

should give you more information

**Comment by SimonMaracine** [comment]
Hello! I have the same issue. I followed the instructions once, then started over again a second time and it gives me the same error when I run the application. I'm using CMake to build the project and I'm on Linux. I also tried running `./gradlew clean build --info`, but with no luck.

**Comment by SimonMaracine** [comment]
I somehow got it working by uncommenting `abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'` and commenting `abiFilters 'arm64-v8a'`.

**Comment by rumplestilzken** [comment]
> I somehow got it working by uncommenting `abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'` and commenting `abiFilters 'arm64-v8a'`.

If you are trying to build for a x64 ARM device, you will not have what you need, but if it got you to where you needed to be, that is good.
