### ISSUE TITLE
pipewire: Add support for session detection

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#5304]
This issue is a little unusual because the PipeWire feature doesn't actually exist yet! But, this seems to be the way that the detection problem will be solved, and the WirePlumber draft is here:

https://gitlab.freedesktop.org/pipewire/wireplumber/-/merge_requests/313

I would write this under the assumption that George's formatting for the key will be how it's implemented, rather than a boolean.

I'd like to have this written up early so that A: WirePlumber devs have more data to test against, and B: it ensures that the key actually does what we want on our end, and we can merge it into main the moment the feature is frozen for the next PW release.

Blocker for #5268

CC @Kontrabant

**Comment by Kontrabant** [comment]
Just to note that I've started to work on this locally, so I'll have the WIP branch available in the not too distant future.

**Comment by flibitijibibo** [comment]
Changing this one a tiny bit - some discussion for session detection in the OP's MR ended up leaning toward doing this in a more nuanced way, mainly the idea that session detection should include checking for a session that actually involves audio in some way (which it actually might not). So at the moment the graph looks a bit like this:

WirePlumber adds better async support for plugin initialization -> WirePlumber can implement a better async session startup -> SDL can detect sessions robustly

**Comment by flibitijibibo** [comment]
The PipeWire side is being investigated with the help of [Eden Industries](https://edenindustries.ca/blog/), the branches can be found here:

https://gitlab.freedesktop.org/antonio.ilersich/pipewire/-/tree/1835-session-detection
https://gitlab.freedesktop.org/antonio.ilersich/wireplumber/-/tree/1835-session-detection

Any eyeballs on this are welcome, as we'd like to have this ready to use by the end of this year!

**Comment by flibitijibibo** [comment]
WIP MRs are live:

https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1409

https://gitlab.freedesktop.org/pipewire/wireplumber/-/merge_requests/441

The goal is still to implement this entirely in PW, so if you're looking at this feature then the above MRs are where you want to be!

**Comment by Kontrabant** [comment]
Obsoleted by #9473
