### ISSUE TITLE
Implement Android on top of native glue

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#531]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2012-01-20 10:43:44 +0000, LCID Fire wrote:

> Google does provide a native glue (see android_native_app_glue.h) for Android so it seems it is not necessary to implement that much in Java to bootstrap SDL.
> Also since the *Sensor* support is not fixed, it would be easier if most of the code was implemented in C so it can be easier extended.
> Another reason can be that letting the VM do as less in Java as possible, could be better for its memory imprint.
> 
> I'll probably start to port the current state, because I also need Sensors access.

On 2012-01-20 20:07:05 +0000, Sam Lantinga wrote:

> The last time I looked there wasn't a significant advantage in using native code, since it was still new and less flexible than the Java code, but that may have changed in the last year.
> 
> Go for it!

On 2012-01-24 12:36:26 +0000, LCID Fire wrote:

> The first code landed.
> http://code.google.com/p/android-sdl-native/
> 
> The question to me is how to support some advanced features like
> - OpenSL ES
> - Sensors

On 2012-05-25 07:36:53 +0000, Gabriel Jacobo wrote:

> *** Bug 1466 has been marked as a duplicate of this bug. ***

On 2012-07-23 15:18:42 +0000, Matthew Huck wrote:

> I've got a working libSDL2 with native activities, no sensors yet, but that wouldn't be hard to add since it's demonstrated in the native activity code from google.  I've implemented it as a separate platform alongside the JNI android platform (it's called android_native).  It's built using cmake, and android ndk-r8 at the moment (just because we use cmake for all our other projects, and extern dependancies so cross compiling is easy).
> 
> How would you like to see what I've done?

On 2013-10-08 16:02:48 +0000, Denis Bernard wrote:

> @Matthew_Huck I would very much like to see your implementation. Thanks !

On 2015-02-19 05:22:20 +0000, Ryan C. Gordon wrote:

> 
> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry if you got a lot of email from this. This is to help me sort through some bugs in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4, though!

On 2015-02-19 05:24:18 +0000, Ryan C. Gordon wrote:

> 
> Whoops, that shouldn't be part of triage-2.0.4.
> 
> --ryan.

On 2015-09-07 01:33:53 +0000, terry_yu wrote:

> (In reply to Matthew Huck from comment # 4)
> > I've got a working libSDL2 with native activities, no sensors yet, but that
> > wouldn't be hard to add since it's demonstrated in the native activity code
> > from google.  I've implemented it as a separate platform alongside the JNI
> > android platform (it's called android_native).  It's built using cmake, and
> > android ndk-r8 at the moment (just because we use cmake for all our other
> > projects, and extern dependancies so cross compiling is easy).
> > 
> > How would you like to see what I've done?
> 
> Hi, @Matthew_Huck can you send me ur implementation about this(a working libSDL2 with native activities), my email is yzy0@yeah.net, thx!!

**Comment by slouken** [comment]
Google continues to add functionality that is only available from Java, so we won't try to implement this.
