### ISSUE TITLE
Undefined reference to AAssetManager_fromJava

### ISSUE THREAD

**Issue by rumplestilzken** [libsdl-org/SDL#5310]
I have had a lot of trouble getting libraries to link within the SDL android-project application. I have a project exporting a static library. I had all the proper flags in my projects Android.mk. as you can see, i had a lot of issues with includes too, so i hard coded them intending to refactor them later.

`LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := beast_hacker

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)

#LOCAL_C_INCLUDES := beast_hacker
LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/google/'
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/'
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/sqlite3'
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/lua/'
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/jni/'
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/SDL_image/'
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/SDL_ttf/'
LOCAL_C_INCLUDES += '/home/nick/development/external_git/SDL/android-project/app/jni/SDL_mixer/include/'

#LOCAL_C_INCLUDES := /home/nick/development/external_git/beast_hacker/src/main/cpp

$(info NDK $(NDK_PATH))
$(info PATH $(LOCAL_PATH))
$(info INCLUDES $(LOCAL_C_INCLUDES))

LOCAL_SRC_FILES := \
	$(subst $(LOCAL_PATH)/,, \
	$(wildcard $(LOCAL_PATH)/beasthacker/*.cpp) \
	$(wildcard $(LOCAL_PATH)/beasthacker/beast/*.cpp) \
	$(wildcard $(LOCAL_PATH)/beasthacker/beast/disk/*.cpp) \
	$(wildcard $(LOCAL_PATH)/beasthacker/processor/*.cpp) \
	$(wildcard $(LOCAL_PATH)/beasthacker/screens/*.cpp) \
	$(wildcard $(LOCAL_PATH)/beasthacker/scripts/*.cpp) \
	$(wildcard $(LOCAL_PATH)/beasthacker/token/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/configuration/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/event/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/exception/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/file/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/game/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/graphics/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/graphics/event/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/input/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/input/gamepad/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/input/keyboard/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/input/mouse/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/input/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/integrations/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/integrations/lua/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/integrations/microsoft/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/logging/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/mapping/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/memory/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/os/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/physics/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/resources/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/scripting/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/sound/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/time/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/utility/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/game/world/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/game/world/objects/*.cpp) \
	$(wildcard $(LOCAL_PATH)/engine/game/world/settings/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/android/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/android/logging/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/android/resources/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/android/scripting/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/java/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/java/processors/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/linux/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/proto/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2//event/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/graphics/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/input/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/input/gamepad/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/input/keyboard/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/logging/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/physics/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/resources/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/sound/*.cpp) \
	$(wildcard $(LOCAL_PATH)/integrations/sdl2/time/*.cpp) )

LOCAL_STATIC_LIBRARIES := lua sqlite3 android_native_app_glue

#LOCAL_SHARED_LIBRARIES := android

LOCAL_LDLIBS := -landroid -llog

LOCAL_CPP_FEATURES := rtti exceptions

include $(BUILD_STATIC_LIBRARY)`

`
cmake_minimum_required(VERSION 3.6)

project(beast_hacker)

find_library(log-lib log)
find_library(android-lib android)

target_link_libraries(main android-lib log-lib)
target_link_libraries(beast_hacker android-lib log-lib)
`

`LOCAL_LDLIBS := -lGLESv1_CM -lGLESv2 -llog -landroid` << src/Android.mk after modification

I spent the better part of four hours looking into the title exception. I tried every type of linking available between CMakeLists.txt and Android.mk LOCAL_LDLIBS LOCAL_STATIC_LIBRARIES LOCAL_SHARED_LIBRARIES with every variety i could think of, exhausting my google searches, i finally looked in the android-project/app/jni/src/Android.mk to find that android was not being linked at the top level. Once i added -landroid to the src/Android.mk LOCAL_LDLIBS my undefined reference went away. Since this is an android application, shouldn't you be linking to android in addition to log? I tried different ndk's, i tried relocating the code etc. I tried using the LOCAL_STATIC_LIBRARIES as well, the only fix was to like using LOCAL_LDLIBS.

**Comment by 1bsyl** [comment]
I think I also have this.
You should also need to add "-lOpenSLES" ?

```diff
--- a/android-project/app/jni/src/Android.mk
+++ b/android-project/app/jni/src/Android.mk
@@ -13,6 +13,6 @@ LOCAL_SRC_FILES := YourSourceHere.c
 
 LOCAL_SHARED_LIBRARIES := SDL2
 
-LOCAL_LDLIBS := -lGLESv1_CM -lGLESv2 -llog
+LOCAL_LDLIBS := -lGLESv1_CM -lGLESv2 -llog -landroid
```
