### ISSUE TITLE
SDL_GetDisplayBounds returns (0,0) on wayland

### ISSUE THREAD

**Issue by EmmanuelARB** [libsdl-org/SDL#5311]
Hi,

Platform : Arch Linux on kernel x86_64 5.16.5-arch1-1
WM : sway
SDL2 versions tested : latest Arch package (2.0.20-1) and latest git
Reproducibility : every time (at least on my computer)

I'm having an issue with SDL_GetDisplayBounds when video driver is wayland.
To illustrate this, I created a small code 

```
#include <SDL.h>
int main()
{
	SDL_Init(SDL_INIT_VIDEO);
	
	for (int i = 0; i < SDL_GetNumVideoDisplays(); i++) {
	    SDL_Rect displayBounds;		
	    if (SDL_GetDisplayBounds(i, &displayBounds) == 0) {
	    	SDL_LogInfo(SDL_LOG_CATEGORY_APPLICATION, "%d, %d, %d", i, displayBounds.x, displayBounds.y); 

	    }
	    else {
		SDL_LogWarn(SDL_LOG_CATEGORY_APPLICATION,
		            "SDL_GetDisplayBounds(%d) failed: %s",
		            i, SDL_GetError());
	    }
	}
	return 0;
}
```

When running with SDL_VIDEODRIVER=x11 (thus on xwayland), the output is fine : 

> INFO: 0, 2560, 210
INFO: 1, -1080, -70
INFO: 2, 0, 0

But when running with SDL_VIDEODRIVER=wayland (default since latest git), it only retrieves 0 :
> INFO: 0, 0, 0
INFO: 1, 0, 0
INFO: 2, 0, 0

This is making some apps behave strangely, such as moonlight-qt which will always spawn on screen 0 instead of the right one, where the QT window lies. This is how I realized the issue, which appeared around the end of last year.

I tried looking at the SDL_GetDisplayBounds code but did not see any obvious issue, especially a driver dependent one...

Thanks in advance !

PS : I know that my screen arrangement is weird, with it going right - left - center but I unfortunately have no control over this as far as I know. And I've also tried with two screens and no negative values for the left screen, with no luck each time...

**Comment by flibitijibibo** [comment]
This may be compositor-specific... we get the x/y data from the server:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c#L700-L709

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c#L324-L325

I don't know if there's a reason sway exposes this to Xwayland but not Wayland, but AFAICT this is the correct way to get this information.

**Comment by flibitijibibo** [comment]
Checked this on GNOME/Plasma again just to be sure and it does work. Sample output from GNOME:

```
[flibitijibibo@flibitTower test]$ SDL_DYNAMIC_API=../flibitBuild/build/.libs/libSDL2-2.0.so.0 ./testdisplayinfo 
INFO: Using video target 'wayland'.
INFO: See 2 displays.
INFO: 0: "LU28R55" (1920x1080, (1920, 0)), 2 modes.
INFO:     DPI: ddpi=154.227112; hdpi=154.819046; vdpi=152.399994
INFO: CURRENT: fmt=SDL_PIXELFORMAT_RGB888 w=1920 h=1080 refresh=60
INFO: DESKTOP: fmt=SDL_PIXELFORMAT_RGB888 w=1920 h=1080 refresh=60
INFO:     MODE 0: fmt=SDL_PIXELFORMAT_RGB888 w=3840 h=2160 refresh=60
INFO:     MODE 1: fmt=SDL_PIXELFORMAT_RGB888 w=1920 h=1080 refresh=60
INFO: 
INFO: 1: "DELL 2408WFP" (1920x1200, (0, 960)), 1 modes.
INFO:     DPI: ddpi=94.189400; hdpi=93.784615; vdpi=95.250000
INFO: CURRENT: fmt=SDL_PIXELFORMAT_RGB888 w=1920 h=1200 refresh=60
INFO: DESKTOP: fmt=SDL_PIXELFORMAT_RGB888 w=1920 h=1200 refresh=60
INFO:     MODE 0: fmt=SDL_PIXELFORMAT_RGB888 w=1920 h=1200 refresh=60
INFO:
```

**Comment by EmmanuelARB** [comment]
Thanks a lot ! I'll try to check this in sway but I'm afraid it's far beyond my knowledge to check why on earth it would handle differently Xwayland and Wayland...

**Comment by EmmanuelARB** [comment]
See Sway issue linked above : it is indeed compositor-specific and seems intended. I'll try to work it around on the only app I found misbehaving (Moonlight-QT)

**Comment by flibitijibibo** [comment]
Interesting, thanks for checking this out! Hopefully this won't have any impact on titles attempting multimonitor support, though I guess these days people get those 21:9 screens now...

**Comment by EmmanuelARB** [comment]
Thanks ! After investigating a bit there is still one strange behavior from SDL : since Sway completely ignores the positions given to SDL_CreateWindow and always spawns the SDL window on the current workspace, going fullscreen can lead to a different display than the one on which the window was rendered.
Once again, one could argue that it is an unconventional behavior from Sway but still, I guess that when going fullscreen, SDL could try to get the correct display it is rendering on, ignoring the initial x and y coordinates given to it...

I'll try to check a bit more what is happening and post another issue if relevant.
