### ISSUE TITLE
Windows - Regression in mouse left and right release events somewhere between 2.0.16 and 2.0.18

### ISSUE THREAD

**Issue by iryont** [libsdl-org/SDL#5314]
Hello

I have recently updated our project from **2.0.12** to **2.0.20** and I've noticed a regression in behavior when left and right buttons are clicked simultaneously and released at the same time.

The problem is that it does happen only to certain users and certain computers.

Sometimes following does happen:

1) Both mouse buttons are clicked at the same time.
2) **SDL_MOUSEBUTTONDOWN** is sent for both, in any order, doesn't matter.
3) Both buttons are quickly released.
4) **SDL_MOUSEBUTTONUP** is sent only for one of them, for example right one.
5) User moves his cursor and the app receives nomal **SDL_MOUSEMOTION** events.
6) User presses again right button and quickly releases it, now the release event **SDL_MOUSEBUTTONUP** for the left button is received first even though it should be sent in step 4.
7) App receives **SDL_MOUSEBUTTONDOWN** and **SDL_MOUSEBUTTONUP** for the right button in order as expected.

It clearly appears that the release event of **SDL_MOUSEBUTTONUP** for the left button is somewhere in there waiting to be dispatched (by another mouse poll call?). As obviously it isn't lost, it is just sent after the next mouse click.

The polling code is quite simple and I have always used the same code since 2.0.0 executed each frame:

```c++
    SDL_Event event;
    while(SDL_PollEvent(&event)) {
        ...
    }
```

Please note, this issue did not happen in **2.0.12** or prior releases.

**Comment by iryont** [comment]
We were able to narrow down the issue to be introduced somewhere between **2.0.16** and **2.0.18** (**2.0.16** being fine, **2.0.18** missing button up event).

**Comment by iryont** [comment]
Further more narrowing, the bug **does exist** in the following SDL2 revision:

https://github.com/libsdl-org/SDL/commit/fd79607eb077d364b5e46b1e48436cf29c86eee9

My initial assumption was that the bug was introduced along with ``[Track button state for each mouse input source separately](https://github.com/libsdl-org/SDL/commit/dfb834d3d4d06c9529d7577127d65b88a9ffc52d)`` but I was wrong.

There were a lot of commits, but I am now unsure which one could cause this. I do try to follow ``History for SDL/src/events/SDL_mouse.c`` which did sound logical.

If you have any idea feel free to let me know, we will gladly make some tests.

**Comment by 1bsyl** [comment]
@iryont 
you can use "git bisect" to find the broken commit !

git bisect start
git bisect bad _bad_revision_
git bisect good  _good_revision_

and it will update until it finds the issue !

**Comment by iryont** [comment]
@1bsyl 

What a nice thing! I didn't know about this. It did save me time by compiling only 8 times to find the wrong commit:

```
>git bisect start

>git bisect bad fd79607eb077d364b5e46b1e48436cf29c86eee9

>git bisect good 25f9ed87ff6947d9576fc9d79dee0784e638ac58
Bisecting: 251 revisions left to test after this (roughly 8 steps)
[114d1d46ac03cd1e3c509f769b99b542c74e904c] direct3d: Remove unnecessary render target support check.

>git bisect good
Bisecting: 125 revisions left to test after this (roughly 7 steps)
[b3f9d8f38d0b1494b9f48fc3fd01dc387db7f96b] remove unused local vars after the latest commits.

>git bisect bad
Bisecting: 62 revisions left to test after this (roughly 6 steps)
[a1fabca162091b50d6f7dd71879d028319e09d80] Removed mouse warping for local mice and improved warp handling for mouse over RDP

>git bisect bad
Bisecting: 31 revisions left to test after this (roughly 5 steps)
[ab7910facfcda8fa654220701a6ebf700106500c] cmake: Move the old, global add_definitions (etc) to an interface library.

>git bisect good
Bisecting: 15 revisions left to test after this (roughly 4 steps)
[723f5cea430d84da5a88e148c431f9e04e4e60c6] Fixed bug #4825 - NullPointerException on SDLActivity.getCurrentOrientation() (Thanks Benau!)

>git bisect good
Bisecting: 7 revisions left to test after this (roughly 3 steps)
[2423c514716f0202b098e20cb682f401b3c141fe] Work around hang in AAudioStream_write() during extended shared object loading while running in a debugger. Observed on a OnePlus 8T (KB2005) running Oxygen OS 11.0.10.10.KB05AA. The observed behavior is that any nonzero timeout value would hang until the device was paused and resumed. And a zero timeout value would always return 0 frames written even when audio fragments could be heard. Making a manual timeout system unworkable. None of the straightforward systems imply that there's a detectable problem before the call to AAudioStream_write(). And the callback set within AAudioStreamBuilder_setErrorCallback() does not get called as we enter the hang state. I've found that AAudioStream_getTimestamp() will report an error state from another thread. So this change codifies that behavior a bit until a better fix or more root cause can be found.

>git bisect good
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[0b6a821188e2456e196a30864f59f0e6d2f3dbf4] Messages posted on the same tick are not new

>git bisect good
Bisecting: 1 revision left to test after this (roughly 1 step)
[072e3fdfc437a87832d4ff569e8e1393abe251ae] Fixed bug #4534: NEON implementation of Convert51ToStereo (Thanks Ryan!)

>git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[5e89b3c89e90841f4f2a42c1e498f6aa3bb2604c] Don't need to use raw input to track the mouse during mouse capture (thanks Brick!)

>git bisect bad
5e89b3c89e90841f4f2a42c1e498f6aa3bb2604c is the first bad commit
commit 5e89b3c89e90841f4f2a42c1e498f6aa3bb2604c
Author: Sam Lantinga <slouken@libsdl.org>
Date:   Thu Oct 14 11:46:07 2021 -0700

    Don't need to use raw input to track the mouse during mouse capture (thanks Brick!)

 src/video/windows/SDL_windowsevents.c | 83 ++++++++++++++++++++---------------
 src/video/windows/SDL_windowsmouse.c  | 22 ++++++----
 src/video/windows/SDL_windowswindow.c | 12 -----
 src/video/windows/SDL_windowswindow.h |  1 +
 4 files changed, 62 insertions(+), 56 deletions(-)
 ```

**Comment by 1bsyl** [comment]
@iryont  great you found it ! (  https://github.com/libsdl-org/SDL/commit/5e89b3c89e90841f4f2a42c1e498f6aa3bb2604c )

**Comment by slouken** [comment]
Can you check to see whether this bug is still active in the latest code? I can't reproduce it anymore and may have fixed it in https://github.com/libsdl-org/SDL/commit/5ff42438e36e98c9d72ac70f5f5ce4599b96d3d2.

**Comment by iryont** [comment]
It seems like the issue was fixed :) Thank you, I do appreciate it very much.

**Comment by slouken** [comment]
You're welcome! Thanks for the report. :)
