### ISSUE TITLE
polling for SDL_ CONTROLLERAXISMOTION creates a lot of slowdown

### ISSUE THREAD

**Issue by spenttoolongthinkingofthisusername** [libsdl-org/SDL#5323]
I haven't posted github issues in a long while so please bear with me if I don't give good into.

I'm on mx linux using g++ to compile a SDL2 game compiled and linked against SDL version 2.0.20

I'm using SDL_pollEvent to manage controller input, but when I add
if(event.type == SDL_ CONTROLLERAXISMOTION){

}

and move my xbox series x left stick I get slowdown, and lag in a way that says to me that it's getting like 10,000 CONTROLLERAXISMOTION events from moving the stick from center to right.

personally I'd say sending motion events is a bad idea because just moving left to right would give you 65535 events added to the event queue.

Please let me know if y'all need any more info, or just input on this would be good. Thanks.

**Comment by 0x1F9F1** [comment]
If you are only getting a slowdown when you start handling the event, it would suggest the slowdown is in your handler code, not SDL. What are you doing inside the if statement?
It would also help if could provide a more precise count of the events being sent.
Either way, profiling the code would give a better understanding of any issues.

**Comment by icculus** [comment]
I agree, I think this is an app issue.

You can choose to not handle the event, and once per frame just query the controller's state with `SDL_GameControllerGetAxis`, and then only handle axis input once per frame, if that is easier for your app.
