### ISSUE TITLE
LT / RT axis of Xbox One Controller behave different in new update

### ISSUE THREAD

**Issue by cinatic** [libsdl-org/SDL#5325]
Hi,

most recently i had some strange behaviours while playing games in wine, LT / RT seem to "stuck" in the games once triggered. After some investigation i observed that 2.0.20 behaves different. Is this a bug or a misconfiguration?

|version|LT/RT Axis initial|max|min|
| ------------- | ------------- | ------------- | ------------- |
|2.0.20|16383|32767|4000, if i go lower than this (i guess deadzone) it snaps back to initial state 16383|
|2.0.18|0|32767|0 (no deadzone)|

kernel: 5.15.11-arch2-1

**Comment by slouken** [comment]
This is a bug, fixed in the latest code.
