### ISSUE TITLE
Mouse button click event doesn't works the first time after SDL_SetWindowFullscreen is called

### ISSUE THREAD

**Issue by ellipticaldoor** [libsdl-org/SDL#5327]
When I call SDL_SetWindowFullscreen in macos what happens is that the first click event SDL_MOUSEBUTTONDOWN is ignored, so you have to click twice.

The keyboard input works fine so I don't think is an issue with the focus of the window.

This also happens when SDL_WINDOWEVENT_MAXIMIZED is triggered. If I click the green maximize button in the macos window I get the same behaviour.

There is something I should call after an SDL_WINDOWEVENT_MAXIMIZED to gain back the SDL_Event for mouse buttons?

**Comment by icculus** [comment]
> There is something I should call after an SDL_WINDOWEVENT_MAXIMIZED to gain back the SDL_Event for mouse buttons?

No, this sounds like an SDL bug; I'll be trying to reproduce this here shortly.

**Comment by icculus** [comment]
I can reproduce this here with `SDL_EVENT_LOGGING=1 ./testsprite2 --resizable` ...run the program, click the green button, click on the window.

However, it's not the first click that's lost, it's all clicks _while the resize animation is running_. Once the smiley faces start moving again (which appears to be about 1 second after the animation appears to finish, then clicks will register with the app, looking like this in the event logging:

```
2022-03-23 17:28:09.792 testsprite2[63916:1866750] INFO: SDL EVENT: SDL_MOUSEBUTTONDOWN (timestamp=4629 windowid=1 which=0 button=1 state=pressed clicks=1 x=677 y=556)
2022-03-23 17:28:09.874 testsprite2[63916:1866750] INFO: SDL EVENT: SDL_MOUSEBUTTONUP (timestamp=4712 windowid=1 which=0 button=1 state=released clicks=1 x=677 y=556)
```

But pound on that mouse button before then? No events.

**Comment by icculus** [comment]
Followup: no events from macOS, as far as I can see. Our delegate doesn't receive any `mouseDown` messages until the animation finishes, and clicks before then are dropped completely. This is probably a good thing, as you really can't control _what_ you're clicking on while the animation is expanding the window, it's just unfortunate there's a brief moment it appears to be standing still but still won't accept clicks.

But this is at the OS level, not SDL, so we can't change this. I'm closing the bug, but if you're seeing something different (it literally drops the first click no matter what and how much time has passed), then please let me know and we'll revisit.

**Comment by ellipticaldoor** [comment]
I see! Thank you for looking into this

**Comment by ellipticaldoor** [comment]
Maybe this is a silly idea but, maybe sending a fake click event after going fullscreen will fix this?

**Comment by icculus** [comment]
We don't know if the user touched the mouse at all; the OS doesn't send the event to SDL, so we wouldn't know to send a fake event.
