### ISSUE TITLE
spinlock platform error on Windows arm64 with llvm-mingw

### ISSUE THREAD

**Issue by woollybah** [libsdl-org/SDL#5333]
When building on Windows 11 with llvm-mingw for arm64 target, we get a platform error when trying to compile SDL_spinlock.c, `SDL_AtomicTryLock()` :
```
Please implement for your platform.
```

We ended up adding the following, which resolved the issue for us,
```c
#elif (defined(__WIN32__) && defined(__GNUC__) && defined(__clang__)) && (defined(_M_ARM) || defined(_M_ARM64))
    SDL_COMPILE_TIME_ASSERT(locksize, sizeof(*lock) == sizeof(long));
    return (InterlockedExchange((long*)lock, 1) == 0);
```

Thanks! :)

**Comment by sezero** [comment]
This is a weird case. Assuming that you are _not_ using cmake or autotools,
does the following patch help at all? (If you are actually using cmake or autotools,
don't know where the issue is...)
```diff
diff --git a/src/atomic/SDL_spinlock.c b/src/atomic/SDL_spinlock.c
index bdd347e..4f10741 100644
--- a/src/atomic/SDL_spinlock.c
+++ b/src/atomic/SDL_spinlock.c
@@ -28,6 +28,12 @@
 #include "SDL_mutex.h"
 #include "SDL_timer.h"
 
+#if defined(__WIN32__) && defined(__clang__)
+# ifndef HAVE_GCC_ATOMICS
+# define HAVE_GCC_ATOMICS 1
+# endif
+#endif
+
 #if !defined(HAVE_GCC_ATOMICS) && defined(__SOLARIS__)
 #include <atomic.h>
 #endif
```

**Comment by woollybah** [comment]
Yes, defining `HAVE_GCC_ATOMICS` resolves the issue. 
No, we are not using cmake nor autotools for our builds.

Apologies for the noise.

Thanks again for the help!

**Comment by sezero** [comment]
OK, applied https://github.com/libsdl-org/SDL/commit/9b817248c52a1e5c79e318dde210c52760fc6b61

> Apologies for the noise.

It was no noise - thanks for the issue report!

**Comment by sezero** [comment]
> This should probably be done in SDL_config_windows.h, like the other build configurations, not in individual source files.

OK, can do -- do the same in SDL_config_winrt.h too?

**Comment by slouken** [comment]
Yep, I think that makes sense.

**Comment by sezero** [comment]
Done: https://github.com/libsdl-org/SDL/commit/67f12ede3ba88814dd1258d73d9879e945aa4a9b
