### ISSUE TITLE
WAYLAND: SDL2 fails to recognize new caps lock binding.

### ISSUE THREAD

**Issue by King-Mucus** [libsdl-org/SDL#5342]
Greetings. I'm using Sway with Xwayland disabled. I swapped caps lock with backspace using the following custom keyboard layout:

```
default partial alphanumeric_keys
xkb_symbols "basic" {
   include "br(nativo)"
   include "br-nativo-swap(swapcaps_bksp)"
};
partial modifier_keys
xkb_symbols "swapcaps_bksp" {
   replace key <BKSP> { [ Caps_Lock, NoSymbol, Caps_Lock ] };
   replace key <CAPS> { [ BackSpace ] };
};
```

Everything works superfine, but I'm unable to erase characters by pressing caps lock. It works on any other non-SDL software. 

This issue has been observed on SuperTuxKart, Wesnoth and freeciv-sdl2.

**Comment by King-Mucus** [comment]
Works fine on dosbox-staging after I remap both keys on the keymapper.

**Comment by flibitijibibo** [comment]
This is probably the callback you care about:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L1050

The keymap is mostly ripped off X11 but it may not be 100% the same.

**Comment by flibitijibibo** [comment]
Just realized that this might be text input and not necessarily keysyms - would be good to check this with testime.

**Comment by flibitijibibo** [comment]
An important discovery has been made: I am absolutely terrible at using Sway.

@King-Mucus, assuming someone is starting from a completely untouched default configuration, what would a step-by-step process look like for someone who has zero experience with tiling WMs and can barely even get a terminal opened in one?

**Comment by flibitijibibo** [comment]
Tried this one more time and discovered that this was an xkbcommon config... which I probably should have guessed from the start.

Was able to verify this combination locally:

- Backspace key: https://github.com/libsdl-org/SDL/commit/a75c6150e08a89ae9eb653c105a35cacf317be5d
- Caps issues: https://github.com/libsdl-org/SDL/commit/6d9ca926265fdadfc1676b9cfef8b098b0ac5d29

The latter patch probably isn't 100% air-tight for all locales, but the idea is at least in place for a vast majority of cases.

**Comment by flibitijibibo** [comment]
Looked up how others do this and found something infinitely better, we're good for sure now: https://github.com/libsdl-org/SDL/commit/2891f0821b27012242c30759308bd8eed83d3fe7
