### ISSUE TITLE
mac OS ：How should I use the event loop in the child thread?

### ISSUE THREAD

**Issue by muyiwq** [libsdl-org/SDL#5345]
Dear Mr,
        In mac OS multi-threaded mode, version 2.0.10 or 2.0.20 cannot support event loop crashes in child threads.
        The reason for the crash is that the video engine handle cannot be obtained, but I have tried to initialize the video and events in the main thread or sub-thread, and the problem remains the same.
        How should I use the event loop in the child thread?
        Looking forward to your reply. Thank you very much

**Comment by slouken** [comment]
On macOS you must do all event handling on the main thread. This is largely true on Windows as well.
