### ISSUE TITLE
Looking for details on how SDL fullscreen with OpenGL (gles2) differs from Windowed?

### ISSUE THREAD

**Issue by Fredrum** [libsdl-org/SDL#5347]
Hi!

In the program I'm working on I'm getting some microstutters on the video content rendered as GL texture when the SDL window/surface is large, nearing full HD size.
But to my surprise I noticed that almost all of the little stutters vanish once I trigger the app to go fullscreen.
I am usnig the various v-sync attributes, settings anf GL frame switch.

So I'm interested in looking at what the SDL fullscreen display mode really is and how it differs from windowed.
Is there a SDL source file that shows how fullscreen works?

This is on Linux X11. 
Raspberry Pi 4b.

Cheers
Fred

**Comment by Susko3** [comment]
For X11, start at

https://github.com/libsdl-org/SDL/blob/85977354fbce9ecb2add660a88e6bec3532c3e26/src/video/x11/SDL_x11window.c#L1560

**Comment by Fredrum** [comment]
Thank You!
I'm checking it out now!

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
