### ISSUE TITLE
Compiling for Android Soong Build System

### ISSUE THREAD

**Issue by shekhar-chauhan** [libsdl-org/SDL#5352]
How to compile the library for Android ? I am not talking about using the library for a Java app, instead, compiling the SDL library for android build system (Soong). 
The error I face when running the default Android.mk file is ".c.arm files are deprecated". Is there any workaround for that ?

**Comment by shekhar-chauhan** [comment]
![image](https://user-images.githubusercontent.com/48454925/154620951-3baa7b59-813c-4b80-a483-c583a9e48399.png)

and going over the link, it says, 

![image](https://user-images.githubusercontent.com/48454925/154621014-892c7b27-0751-4ad3-b473-08cc774beb74.png)


but how do we do that ?

**Comment by fayfive** [comment]
@shekhar-chauhan Can you solve it?
I want to use it as ffmpeg that can ndk cross compile to *.so not java

**Comment by shekhar-chauhan** [comment]
@fayfive still stuck man. no progress. do you have any idea about my issue ?
i do too want to use it as a .so and no a java one. 
even the default mk is not working, dont know how to proceed

**Comment by fayfive** [comment]
Here is the suggestion. But I can't build it
https://github.com/libsdl-org/SDL/issues/5356#issuecomment-1047879990

**Comment by shekhar-chauhan** [comment]
@fayfive the thing is, these guys are trying to use it inside of an app. What I want to do is build the lib, as you do in windows to create a .dll so that whatever app you built directly references it.

**Comment by fayfive** [comment]
@shekhar-chauhan 
I see.
That means just wrapping sdl2 acitvity into qt activity and use c++ to load the java?

**Comment by shekhar-chauhan** [comment]
@fayfive partially yes, and no. 

suppose you have a library, abc, containing .c and .h files. To be able to use it around easily, you'd want to create a static/shared library of it. You'll compile it as a dll on windows or .so/.a on Linux/Android.
That is what i want to achieve with SDL. 
The problem being, since it's very own Makefile, which, in normal conditions generate the .so or .a, is not working since compiling .c.arm files are no longer supported. Don't know how to proceed from there.

**Comment by shekhar-chauhan** [comment]
Although, i did make some progress, and sort of stuck at a different point.

![image](https://user-images.githubusercontent.com/48454925/155507916-99da51ed-5bef-4271-a10f-08dc309ddf36.png)

It'd be great if you or anyone else can help on this...
