### ISSUE TITLE
iOS: home bar and touch issues

### ISSUE THREAD

**Issue by hsdk123** [libsdl-org/SDL#5353]
There's an annoying home indicator on the bottom of ios apps that interferes with in app touches. I've found

https://developer.apple.com/documentation/uikit/uiviewcontroller/2887512-preferredscreenedgesdeferringsys

but it seems this would need to be a direct insertion into SDL and can't be done outside.
This is a request to implement this functionality into SDL to support iOS devices that have the home indicator.

https://twitter.com/solarsailer/status/1052538603451109376?lang=en

As shown here, this has also been implemented in Unity to support this.

**Comment by hsdk123** [comment]
Seems someone made a test implementation that was never merged, but seems reasonably simple / straightforward

https://github.com/libsdl-org/SDL/issues/2807

**Comment by korri1305-blip** [comment]
Nice code
