### ISSUE TITLE
joystick order on linux is random for some multijoysticks

### ISSUE THREAD

**Issue by MrMEEE** [libsdl-org/SDL#5366]
Hi

I have a 4 controller device (usb converted arcade cabinet).. where all the controllers are "behind" the same VID/PID:

[LOG] Searching gamepads...
[LOG] Found 4 gamepad(s):
[LOG] "HID 16c0:05df", 00000000c0160000df05000001010000 (mapping available)
[LOG] "HID 16c0:05df", 00000000c0160000df05000001010000 (mapping available)
[LOG] "HID 16c0:05df", 00000000c0160000df05000001010000 (mapping available)
[LOG] "HID 16c0:05df", 00000000c0160000df05000001010000 (mapping available)

(Output from gamepad-tool)

On Windows and using the old standard (/dev/input/js*) the joysticks are always presented in the same order.. but using SDL programs they are randomly changed around, between program restarts and machine reboots..

I have tried playing around with SDL_JOYSTICK_DEVICE, SDL_LINUX_JOYSTICK_CLASSIC and SDL_JOYSTICK_DISABLE_UDEV... but I can't seem to find a way to consistently get the same order...

Any ideas??

**Comment by clebercasali** [comment]
"env SDL_JOYSTICK_DISABLE_UDEV=1 mygame" should work.
SDL_JOYSTICK_DEVICE takes the event* nodes, not js*.
Check this [script](https://github.com/HugLifeTiZ/configs-scripts/blob/master/scripts/sdl-joystick-device).

**Comment by MrMEEE** [comment]
Will doublecheck.. but I'm pretty sure that I still get random results with SDL_JOYSTICK_DISABLE_UDEV=1...

How will I know the names of the event* ... they keep shifting?

**Comment by clebercasali** [comment]
> How will I know the names of the event* ... they keep shifting?

Look in "/sys/class/input/js*/device/". There must be a directory with the event number there.

**Comment by MrMEEE** [comment]
But the next time I turn the system on, they might/will be different?

So I should do a script that reads out the event-id?

**Comment by clebercasali** [comment]
Yes. The script I linked does just that.
[https://github.com/HugLifeTiZ/configs-scripts/blob/master/scripts/sdl-joystick-device](https://github.com/HugLifeTiZ/configs-scripts/blob/master/scripts/sdl-joystick-device)
