### ISSUE TITLE
Windows VC devel package contains not SDL2Config.cmake

### ISSUE THREAD

**Issue by feliwir** [libsdl-org/SDL#5373]
The windows devel package contains no CMake config, making it impossible to use `find_package(SDL2)` in config mode.
Having to manually add a custom `FindSDL2.cmake` on windows error-prone and not a great experience.

Was there a reason for the decision to disable this for VC development packages?

**Comment by icculus** [comment]
Bumping to 2.0.24, where I'll talk to Kitware about the right way to manage CMake issues.

**Comment by slouken** [comment]
@madebr, what's the right thing to do here?

**Comment by madebr** [comment]
I think, with some magic we can provide a `SDL2Config.cmake` script that provides `SDL2::` targets for x86 or x64.
We can e.g. use [`CMAKE_SIZEOF_VOID_P`](https://cmake.org/cmake/help/latest/variable/CMAKE_SIZEOF_VOID_P.html).

Where can I find the build scripts that you use to create the binary releases?

**Comment by slouken** [comment]
It's not anywhere public at the moment, but if you put a script in build-scripts, I can run it during the release package generation.

**Comment by madebr** [comment]
#5721 addresses this.

@feliwir It would be nice to have feedback from MSVC developers.

**Comment by madebr** [comment]
If everything goes right, the development package of the next release will have cmake configuration scripts included.
