### ISSUE TITLE
No `SDL_Delay` option for 64 bit integers

### ISSUE THREAD

**Issue by decrovert** [libsdl-org/SDL#5379]
I have recently started using `SDL_GetTicks64`, as it is the recommended way.

I have then realised that it creates a problem: the `SDL_Delay` function takes a `Uint32` as the argument. This generates a compiler warning saying that there is a possible loss of data everytime I pass a `Uint64` from `SDL_GetTicks64` into it.

**Comment by icculus** [comment]
I think it's probably reasonable to cast to Uint32 here, unless there's a serious need to put the process to sleep for more than 49 days...?
