### ISSUE TITLE
2.0.16+ : SDL_Init(SDL_INIT_JOYSTICK) requires also SDL_INIT_VIDEO for xbox one s controller to work on Windows

### ISSUE THREAD

**Issue by fabricecaruso** [libsdl-org/SDL#5380]
Since SDL2 2.0.16, with a XBox One S Controller, on Windows.

I have a thread running this code, that works fine with SDL 2.0.12 :
```
    SDL_Init(SDL_INIT_JOYSTICK);
    SDL_InitSubSystem(SDL_INIT_JOYSTICK);
    SDL_JoystickEventState(SDL_ENABLE);
    SDL_GameControllerEventState(SDL_ENABLE);
[...]
   if (SDL_PollEvent(&evt)) 
[...]
```
Joystick events (SDL_JOYAXISMOTION, SDL_JOYBUTTONDOWN, SDL_JOYBUTTONUP) are never received & return from SDL_JoystickGetButton is always 0.

In order to make it work, I also have to init VIDEO this way :
SDL_Init(SDL_INIT_JOYSTICK | SDL_INIT_VIDEO);

SDL_INIT_VIDEO should not be required to read joystick event/state.

**Comment by slouken** [comment]
The raw input backend requires a windows message pump active in order to receive input events.

If you're not using SDL video support, you can enable a standalone joystick message pump with:
```c
SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");
```

If you'd rather not use the raw input controller driver, you can disable it with:
```c
SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");
```
