### ISSUE TITLE
audio/haiku: Attempts to create a BApplication object is made even if one already exists

### ISSUE THREAD

**Issue by Cacodemon345** [libsdl-org/SDL#5385]
As the title says.

If a BApplication object already exists when initializing audio in Haiku, it will crash.

**Comment by Cacodemon345** [comment]
SDL_InitBeApp doesn't check for be_app beforehand and only checks if its own instance is already initialized.

**Comment by icculus** [comment]
Is this happening because the app has initialized be_app outside of SDL, or is this SDL accidentally initializing it outside of SDL_InitBeApp?

**Comment by waddlesplash** [comment]
I think SDL 1.2 already did the right thing here and just did "not worry about it" if a BApplication already exists. I've been meaning to experiment with modifications here but never got around to it.
