### ISSUE TITLE
X11 SDL_GetWindowFlags doesn't reflect fullscreen changes that happen outside of SDL

### ISSUE THREAD

**Issue by jo-valve** [libsdl-org/SDL#5390]
Not sure how widespread this is. I've only tested on Manjaro KDE Plasma.

Basically, if I toggle fullscreen using the window manager GUI instead of SDL code, SDL_GetWindowFlags doesn't reflect the changes. Here's a simple little program to test.

```c
#include <SDL2/SDL.h>
#include <stdio.h>

int main(void) {
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *window = SDL_CreateWindow(
        "Press F: Fullscreen (Red), Press W: Windowed (Green)",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        512, 512, SDL_WINDOW_RESIZABLE
    );

    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);

    for (;;) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            switch (event.type) {
                case SDL_KEYDOWN: {
                    if (event.key.keysym.sym == SDLK_f) {
                        SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);
                    } else if (event.key.keysym.sym == SDLK_w) {
                        SDL_SetWindowFullscreen(window, 0);
                    }
                    break;
                }
                case SDL_QUIT: {
                    return 0;
                }
            }
        }

        if ((SDL_GetWindowFlags(window) & SDL_WINDOW_FULLSCREEN) != 0) {
            SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
        } else {
            SDL_SetRenderDrawColor(renderer, 0, 255, 0, 255);
        }

        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
        SDL_Delay(1);
    }
}
```

**Comment by wooosh** [comment]
I can reproduce this in GNOME 41.3

**Comment by flibitijibibo** [comment]
This may need to be checked under Wayland as well, I think we actually enforce the SDL flags when using that backend.

**Comment by jo-valve** [comment]
Differentiating between `SDL_WINDOW_FULLSCREEN` and `SDL_WINDOW_FULLSCREEN_DESKTOP` complicates this somewhat. If a window manager enables fullscreen mode itself, it's likely more like `SDL_WINDOW_FULLSCREEN_DESKTOP`, but I guess there's no real way to know that for sure.

I think ideally, SDL could keep track of its `FULLSCREEN` / `FULLSCREEN_DESKTOP` preference separate from whether or not it's currently in fullscreen mode (maybe via the `0x00001000` window flag bit), intercept when the window manager wants to transition to fullscreen mode, then SDL itself could handle or fixup the transition itself with its preferences. But I'm not familiar enough with EWMH to know if that's really possible.

**Comment by icculus** [comment]
> I think ideally, SDL could keep track of its FULLSCREEN / FULLSCREEN_DESKTOP preference separate from whether or not it's currently in fullscreen mode

For now I settled for adding FIXME on this and when the window manager marks a window as _NET_WM_FULLSCREEN, we always mark the SDL window as SDL_WINDOW_FULLSCREEN.

(although I would argue that what Gnome and KDE are doing is making the window SDL_WINDOW_FULLSCREEN_DESKTOP, but I didn't want to risk any broken promises that might entail. I won't complain if someone else makes a decision)

**Comment by slouken** [comment]
I think this actually should be FULLSCREEN_DESKTOP, otherwise we'll try to change video modes and things...

**Comment by icculus** [comment]
Gonna make that change shortly, then.

**Comment by jo-valve** [comment]
@icculus `SDL_GetWindowFlags` is reflecting the external changes now, but `SDL_SetWindowFullscreen` doesn't work on the first change after an external change. Using the same test program above:

1. Start windowed.
2. Use the WM to switch to fullscreen.
3. Press `W` to invoke `SDL_SetWindowFullscreen(window, 0)`.
    The window stays fullscreen but turns green (i.e. `SDL_GetWindowFlags` says not fullscreen)
4. Press `F` to invoke `SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP)`
    The window stays fullscreen and turns red (i.e. `SDL_GetWindowFlags` is correct)
6. Press `W` again
    The window leaves fullscreen and turns green.

**Comment by jo-valve** [comment]
Looks good now. Thanks!

**Comment by icculus** [comment]
@jo-valve I had to back this out because it breaks other things; let's discuss this more for 2.0.24. I'm not confident we can rely on x11 window managers to behave well enough here to not cause an enormous amount of trouble, but I'll try to wrestle this down in the next milestone if possible.

**Comment by jo-valve** [comment]
No worries. Thanks!

**Comment by icculus** [comment]
Yeah, I think we have to give up on this with the current state of window managers; it's not reliable, and they treat "fullscreen" differently than we do (and differently from each other).

What we need here is changes to window managers (and possibly a new protocol for that to cooperate), and that's a steep hill, so I'm giving up on this for now.
