### ISSUE TITLE
cheap USB SNES pad

### ISSUE THREAD

**Issue by gwald** [libsdl-org/SDL#5395]
not sure if it's 100% right...

```
030000001f08000001e4000010010000,USB gamepad,platform:Linux,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:-a1,dpdown:+a1,dpleft:-a0,dpright:+a0,

**Comment by Wohlstand** [comment]
Is this another DragonRise based thing? :thinking:

**Comment by slouken** [comment]
In general we don't accept mappings for generic USB gamepads - there are too many different devices that share the same core components and we can't properly distinguish them.

Thanks though!
