### ISSUE TITLE
SDL_GL_LoadLibrary / SDL_GL_GetProcAddress fails with KMSDRM backend.

### ISSUE THREAD

**Issue by joolswills** [libsdl-org/SDL#5399]
Tested on SDL 2.0.21 (072db7b005ee19f8e53fd4d41491d6af8aa25790) on the RPI4 (Raspberry PI OS Buster) using KMSDRM video backend.

SDL Configured with: `./configure --enable-video-kmsdrm --disable-video-rpi --disable-video-vulkan`

The code example below will  print the pointer address returned by SDL_GL_GetProcAddress and works on SDL prior to commit - https://github.com/libsdl-org/SDL/commit/f60f8d5d84eeac4e115617070606a83f71abc61d

The commit above changes ordering so KMSDRM_GLES_LoadLibrary doesn't actually load the library now - this seems to break any code that does SDL_GL_LoadLibrary / SDL_GL_GetProcAddress calls (eg darkplaces quake) before any window is created etc.

From the commit:

```c
int
KMSDRM_GLES_LoadLibrary(_THIS, const char *path) {
    /* Just pretend you do this here, but don't do it until KMSDRM_CreateWindow(),
       where we do the same library load we would normally do here.
       because this gets called by SDL_CreateWindow() before KMSDR_CreateWindow(),
       so gbm dev isn't yet created when this is called, AND we can't alter the
       call order in SDL_CreateWindow(). */
#if 0
    NativeDisplayType display = (NativeDisplayType)((SDL_VideoData *)_this->driverdata)->gbm_dev;
    return SDL_EGL_LoadLibrary(_this, path, display, EGL_PLATFORM_GBM_MESA);
#endif
    return 0;
}
```

This example code below works before the commit referenced above - after the commit the SDL_GL_GetProcAddress call will segfault
```c
#include <SDL2/SDL.h>

int main(int argc, char* argv[]) {
    SDL_Init(SDL_INIT_VIDEO);
    if (SDL_GL_LoadLibrary(NULL) == 0) {
        printf("%p\n", SDL_GL_GetProcAddress("glGetString"));
    }
    SDL_Quit();
    return 0;
}
```

**Comment by joolswills** [comment]
Sorry - submitted prematurely - fixing up issue text now.

**Comment by joolswills** [comment]
I have updated the issue text - it was submitted prematurely.

**Comment by amparg** [comment]
This issue, is specific with Raspberry Pi platform ?

**Comment by icculus** [comment]
Basically the problem is that they are trying to load a GL library without creating a window, which like everything else OpenGL, is subject to the weird quirks of the platform.

I don't think we should segfault in this scenario, but I'm inclined to say that returning NULL is correct in this case, at least how the kmsdrm backend currently works.

We can investigate whether the backend's requirement that a window exist first is reasonable in the first place, but that's probably going to wait until we merge the atomic version in SDL3.
