### ISSUE TITLE
SDL_blit_N.c: duplicate 'const' declaration warning

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#5401]
Hello!

At the recent version of the code, I found the weird use of `const static const struct ....` which caused the compiler warning.

SDL_blit_N.c, line 131;
```c
const static const struct SDL_PixelFormat default_pixel_format = {
```

Do you want to write the `static const struct SDL_PixelFormat default_pixel_format` or ` const static struct SDL_PixelFormat default_pixel_format`?

P.S. https://stackoverflow.com/questions/12005959/static-const-vs-const-static :thinking:

**Comment by sezero** [comment]
Applied https://github.com/libsdl-org/SDL/commit/ee6bfcdd66c107187acbc928c379572b95479ff6 to fix it
