### ISSUE TITLE
Assertion fail in src/events/SDL_events.c on Windows

### ISSUE THREAD

**Issue by franko** [libsdl-org/SDL#5412]
I am having consistently an assertion fail using SDL 2.0.16 and 2.0.18 when the application is running for a long time in background. The problem is very difficult to reproduce, I have to leave the application running and it happens very seldomly.

The assertion that fails (2.0.16 release code) happen there:

```c
/* Remove an event from the queue -- called with the queue locked */
static void
SDL_CutEvent(SDL_EventEntry *entry)
{
    if (entry->prev) {
        entry->prev->next = entry->next;
    }
    if (entry->next) {
        entry->next->prev = entry->prev;
    }

    if (entry == SDL_EventQ.head) {
        SDL_assert(entry->prev == NULL);
        SDL_EventQ.head = entry->next;
    }
...
```

Below the stack trace I get on Windows with gdb (code based on 2.0.16):

```
...
#8  0x00007ff74e941c53 in SDL_PromptAssertion (
    data=0x7ff74eacca60 <sdl_assert_data>, userdata=0x0)
    at src/SDL_assert.c:224
#9  0x00007ff74e941ea4 in SDL_ReportAssertion_REAL (
    data=0x7ff74eacca60 <sdl_assert_data>,
    func=0x7ff74eadb660 <__func__.2> "SDL_CutEvent",
    file=0x7ff74eadb5b8 <_tls_used+4344> "src/events/SDL_events.c", line=575)
    at src/SDL_assert.c:355
#10 0x00007ff74e8036e5 in SDL_CutEvent (entry=0x2becde642f0)
    at src/events/SDL_events.c:575
#11 0x00007ff74e803b32 in SDL_PeepEvents_REAL (events=0xef46bfe610,
    numevents=1, action=SDL_GETEVENT, minType=0, maxType=65535)
    at src/events/SDL_events.c:673
#12 0x00007ff74e803fac in SDL_WaitEventTimeout_REAL (event=0xef46bfe610,
    timeout=0) at src/events/SDL_events.c:896
#13 0x00007ff74e803d3d in SDL_PollEvent_REAL (event=0xef46bfe610)
    at src/events/SDL_events.c:785
#14 0x00007ff74e7f7a9a in SDL_PollEvent (a=0xef46bfe610)
    at src/dynapi/SDL_dynapi_procs.h:153
#15 0x00007ff74e7b2d9f in f_poll_event (L=0x2becc303750)
    at ../src/api/system.c:119
...
```

I know the code was modified in relation to the sentinel but I don't know how this can be related with the problem I am observing.

I may test with 2.0.20 but please have a look at this problem before if you can. The nature of the problem is not clear to me.

**Comment by franko** [comment]
Just adding the screenshot of the popup window for the assert:

![image](https://user-images.githubusercontent.com/433545/158768660-d484619c-c8bb-4a05-a20e-de9c30eb9a0b.png)

**Comment by franko** [comment]
Thank you for looking at that. You maybe right, this could be a random memory corruption but I have some doubts.

Unfortunately I cannot reproduce the bug by now. For the moment you can probably ignore this issue. I may do more investigations on my side on the base of your suggestions.

**Comment by icculus** [comment]
Okay, let me know if it shows up again (and if there's some way we can run the program to reproduce it here if it does show up again).
