### ISSUE TITLE
no window with wayland on an old wayland client

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5416]
Setup: an old `Fedora 27 Linux, x86_64`, wayland-client 1.14
```
$ rpm -qa | grep wayl | sort
egl-wayland-1.0.3-2.20180201git6f5f7d0.fc27.x86_64
egl-wayland-devel-1.0.3-2.20180201git6f5f7d0.fc27.x86_64
gnome-session-wayland-session-3.26.1-1.fc27.x86_64
ibus-wayland-1.5.17-6.fc27.x86_64
libwayland-client-1.14.0-2.fc27.x86_64
libwayland-cursor-1.14.0-2.fc27.x86_64
libwayland-server-1.14.0-2.fc27.x86_64
mesa-libwayland-egl-17.3.9-1.fc27.x86_64
mesa-libwayland-egl-devel-17.3.9-1.fc27.x86_64
qt5-qtwayland-5.9.6-1.fc27.x86_64
wayland-devel-1.14.0-2.fc27.x86_64
wayland-protocols-devel-1.10-1.fc27.noarch
xorg-x11-server-Xwayland-1.19.6-7.fc27.x86_64
```

As of 2.0.16, where lots of wayland improvements went in, I get no
windows at all, e.g. with testsprite2 program: Hitting `Ctrl-C` quits
the test program. With 2.0.14 and older (tested down to v2.0.7), I
properly get a window (although w/o decorations, as expected.) This
is somewhat a problem, because with SDL2 builds from latest sources,
I have to set `SDL_VIDEODRIVER=x11` to run programs properly
because wayland now has priority over x11.

Any hints for solving this? (Assuming it is actually solvable..)
Are the wayland library requirements changed somehow but autotools
is unaware of it? (no issues building, though..)

**Comment by flibitijibibo** [comment]
First thing I would check is the path without libdecor (`SDL_VIDEO_WAYLAND_ALLOW_LIBDECOR=0`), just to make sure it's our standalone xdg path... after that `WAYLAND_DEBUG=1` should give us a pretty good window into what's going on. If anything I'd expect the opposite behavior because windows not being presented usually means we _never_ present, which qualifies as an application bug since Wayland doesn't show windows until they have initialized contents. We've chipped away at this for SDL's tests but I don't know if we've covered them all yet.

**Comment by sezero** [comment]
> `SDL_VIDEO_WAYLAND_ALLOW_LIBDECOR=0`

Does nothing, possibly because I don't have libdecor.

> `WAYLAND_DEBUG=1`

This gives a repetitive dbg output, don't know what it means at all :)
Attaching the first 128k of terminal output from a `testwm2` run:
[dbg.txt](https://github.com/libsdl-org/SDL/files/8304093/dbg.txt)

**Comment by sezero** [comment]
Any chance anyone looking into this?

**Comment by flibitijibibo** [comment]
Not yet, earliest I'll get to this is Monday.

**Comment by cgutman** [comment]
Any chance this is related to the removal of `wl_shell`?

**Comment by flibitijibibo** [comment]
For a Fedora version this old (and just as EOL), maybe... I would hope it will still show up without it though.

**Comment by flibitijibibo** [comment]
Found this old report that points to it using wl_shell: https://bugzilla.gnome.org/show_bug.cgi?id=792855

I'm not so sure about adding this back though... my understanding is that systems not using xdg-shell but still have support don't care about shell mappings at all, and thus should present. Not to mention, it's missing so many features that it would never be as reliable as xdg.

It's a bit weird but what if we detected compositors that had wl_shell but not xdg and fell back to X? It would fill in for the gap between desktops and embedded cases.

**Comment by icculus** [comment]
Yes, this is the right move; Wayland support should refuse to initialize if it doesn't have a minimum viable interface for our needs.

**Comment by flibitijibibo** [comment]
I've looked into this some more - we should bump the requirement to libwayland-client 1.20 or newer. Three points of reference:

- All distributions from 2018 onward have xdg-shell and libwayland 1.16, however...
- libdecor isn't supported below libwayland 1.18, which cuts out distributions before 2020, even so...
- Distributions basically decided not to backport libdecor, I could only find it in distributions like Fedora or upcoming ones like 22.04 which all have 1.20 anyway

Some upsides to the requirement spike:
- It fixes a bunch of bugs like #5376 and #4636 for free
- Roughly zero chance of running into weird, half-finished Wayland desktops
- The final transition can be more at the user's pace (i.e. someone on 18.04 LTS isn't going to discover a bunch of missing titlebars for new games)

Specialized systems using Wayland in some special case should have no problems updating the IPC libraries without affecting the rest of the system (which makes it odd that distributions don't do this, but it gave us this as a fix in return).

**Comment by flibitijibibo** [comment]
See #5429 for the patch. The patch is super basic, but since this is a raised system requirement will wait for a +1 (or -1 if anyone has a major objection to this).

**Comment by flibitijibibo** [comment]
Bumped the requirement to 1.18 in latest main.
