### ISSUE TITLE
Vita: Request for YUV texture format support

### ISSUE THREAD

**Issue by crudelios** [libsdl-org/SDL#5417]
This is more directed at @isage, since he's the main coder of the Vita port.

Is it possible to add YUV texture support for Vita? I believe Vita has a native YUV texture format, and even if that isn't feasible there's probably a way to do it using shaders. I would do it myself but I have no idea how to do it.

The reason I ask is because I'm using an MPEG1 software decoding library ([pl_mpeg](https://github.com/phoboslab/pl_mpeg), really nice single-header lib BTW), which is already slow, but having to convert the YUV to RGB in software just makes it unplayable. Using YUV textures directly would improve playback performance by up to 50%.

Thanks!

**Comment by isage** [comment]
Yeah, I'll take a look. Do you have any simple test code i can use?

**Comment by crudelios** [comment]
@isage Here you go:

[yuvtest.zip](https://github.com/libsdl-org/SDL/files/8304457/yuvtest.zip)

To use, download the zip file, then [download the demo mpg file](https://phoboslab.org/files/bjork-all-is-full-of-love.mpg) and place it on the empty `data` folder.

Then run: `mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make`.

It will create a `pl_mpeg.vpk` which will run the demo video when opened.

By default, the program is using a normal rgb texture and performing the conversion using software. I confirmed it works on my vita but the video runs at about 10fps.

If you want to test the YUV textures, go to line `334` of `pl_mpeg_player.c`, change `APP_TEXTURE_MODE_RGB` to `APP_TEXTURE_MODE_YCRCB` and recompile.

**Comment by isage** [comment]
Thanks! I'll take a look when i have time. Probably tomorrow

**Comment by isage** [comment]
@crudelios okay, so good news: i have crude yuv support. It still needs some cleanup, NV12/NV21 and SDL_SetYUVConversionMode support. But it works.
Bad news:
1) while performance is indeed way better, it still not fullspeed sometimes.
2) looks like pl_mpeg can use only float32 for audio. Vita has no support for that, so sdl needs to convert audio samples (there's a bug in sdl vita audio backend r/n preventing that conversion, i'll fix it together with adding yuv support)

**Comment by crudelios** [comment]
Thank you very much for your efforts! To be honest I wasn't expecting full speed. Still, I think a timely Vita overclock during video playback may just do the trick,  hopefully.

Nice catch with the audio bug, I didn't really test the audio side of things.

**Comment by crudelios** [comment]
Thanks for the hard work @isage!
