### ISSUE TITLE
Strange window decoration

### ISSUE THREAD

**Issue by guiguidu60** [libsdl-org/SDL#5420]
**Setup: SDL 2.0.20 - Fedora 36 pre-release - GNOME 42 (GTK 4) & Fedora 35 - GNOME 41 (GTK 4) **

When I create any window, it creates a strange window, which is obviously not generated by GTK.
It seems that SDL creates its own native window due to a problem with GTK.
Moreover, the button to maximize the window does not work and the window bar is always displayed when the program is in full screen.

![sdl_window](https://user-images.githubusercontent.com/1296525/159115191-e1c71d4d-0ad4-4985-a867-82d6fb35a21e.png)

**Comment by icculus** [comment]
Is this Wayland? I think that's libdecor's default UI...?

**Comment by guiguidu60** [comment]
Yes, GNOME use XWayland session.

**Comment by icculus** [comment]
@Conan-Kudo does this sound like anything you've seen (and maybe a dependency that needs to be added to SDL or Gnome in Fedora)?

**Comment by Conan-Kudo** [comment]
That is sadly what libdecor does currently. @jadahl has not implemented a GNOME backend for libdecor so that it would create proper window decorations that match GNOME itself.

**Comment by Conan-Kudo** [comment]
> 
> EDIT: after install GIMP and Inkscape, SDL create now a GTK window... So there was indeed a missing library. The problem is partially solved because I don't know what is this library.

Wait, hold on. It creates a GTK window after installing those applications? That sounds very odd. I'll look into it.

**Comment by guiguidu60** [comment]
After a fresh installation of Fedora 35 and without installing any program (except SDL2-devel), I don't have the problem...
I think I can close this issue.

**Comment by not-kaz** [comment]
This is not an isolated issue. Tried a few of the Fedora 36 beta RCs and they all have this problem.
Both on fresh installs and some installs that have Steam/Discord etc. installed, issue persists. On both Wayland/Xorg.

Might be a missing library but it's unsure which one. 

![Screenshot from 2022-03-28 22-29-30](https://user-images.githubusercontent.com/87723604/160481672-c7fd97ab-b47a-4895-97d4-f66f0fbc9850.png)

**Comment by jadahl** [comment]
What is odd about that screenshot? It appears to look like the default cairo based decorations of libdecor. Eventually we'll have a gtk based one (see https://gitlab.gnome.org/jadahl/libdecor/-/merge_requests/43) but it's not merged yet.

**Comment by icculus** [comment]
Has anyone figured out why some people are getting Gnome decorations, or was that maybe just using the X11 target by accident instead of Wayland?

**Comment by jadahl** [comment]
If you get GNOME decorations with SDL one is either running that branch, or it's using X11. Or magic.

**Comment by Conan-Kudo** [comment]
> Has anyone figured out why some people are getting Gnome decorations, or was that maybe just using the X11 target by accident instead of Wayland?

Yes. If you're on the Wayland target, you get the horrible Cario decorator, if you're on X11, Mutter draws the GTK decorator.
