### ISSUE TITLE
getenv instead of hint for OpenGL texture_rectangle?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5422]
We're checking an environment variable here...

https://github.com/libsdl-org/SDL/blob/main/src/render/opengl/SDL_render_gl.c#L1850

...instead of an SDL hint (which will _also_ check an environment variable, fwiw). @slouken, was this intentional, or can I change this to SDL_GetHintBoolean?

**Comment by slouken** [comment]
It's specifically using the environment variable to match what's happening in SDL_GL_ExtensionSupported()
I'm fine with changing it if we also change how that function works, but I wasn't sure we wanted to do that. I don't think setting an SDL hint should automatically change what extensions are used...

**Comment by icculus** [comment]
Okay, but let's reevaluate for SDL3.

#3519
