### ISSUE TITLE
Joysticks  cannot work  on Windows10 from version2.0.14 to version2.0.20

### ISSUE THREAD

**Issue by dzywater** [libsdl-org/SDL#5441]
I have a xbox one plugined into my computer.

I tested the version 2.0.10, 2.0.12, 2.0.14, 2.0.16, 2.0.18, 2.0.20 on Windows10 (19043.1526)

In version 2.0.10, 2.0.12, 2.0.14, 2.0.16, SDL_NumJoysticks returned 1.

In version 2.0.18, 2.0.20, SDL_NumJoysticks returned 0.

Let Functions = 
{
handleJoyAxis
handleJoyButtonDown
handleJoyButtonUp
handleJoyHatMotion
handleJoyDeviceAdded
}

In version 2.0.14, 2.0.16, 2.0.18, 2.0.20, Functions blocked.

In version 2.0.10, 2.0.12, Functions worked.

The relevant apps based on SDL on ubuntu20.04 work, but the SDL version is 2.0.10, not sure whether the versions from 2.0.14 to 2.0.20 can work normally.

**Comment by slouken** [comment]
Any chance we can set up a Zoom call to debug this interactively? I'm not seeing the issue here.

**Comment by slouken** [comment]
No response, so moving this out of the milestone. Please e-mail me at slouken@libsdl.org if you'd like to interactively debug this issue.

**Comment by dzywater** [comment]
> Any chance we can set up a Zoom call to debug this interactively? I'm not seeing the issue here.

Sorry for no response, I just saw you reply.
I tested v2.0.22, it still has same problem.

**Comment by slouken** [comment]
Calling `SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1")` might work for you.

This code works for me, but if I don't pump events and don't set the `SDL_HINT_JOYSTICK_THREAD` hint, I get the behavior you're describing.
```c
#include "SDL.h"

#define NO_PUMPEVENTS

int main(int argc, char *argv[])
{
    SDL_GameController *ctrl;

#ifdef NO_PUMPEVENTS
    SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");
#endif
    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER);

    ctrl = SDL_GameControllerOpen(0);
    if (ctrl) {
        for (;;) {
#ifdef NO_PUMPEVENTS
            SDL_GameControllerUpdate();
#else
            SDL_PumpEvents();
#endif
            SDL_Log("%d", SDL_GameControllerGetAxis(ctrl, SDL_CONTROLLER_AXIS_LEFTX));
            SDL_Delay(100);
        }
    }
    SDL_Quit();
    return 0;
}
```

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
