### ISSUE TITLE
Possibility to add the bitwise blend modes (such as AND, OR, XOR, etc.)

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#5455]
I had an attempt to suggest this at #2404, but it got been rejected because of "custom shaders needs". However, I had noted that bitwise blend modes were are a native feature of OpenGL and shouldn't require custom shaders. However, I want to get another shot and give some more explanations that they are possible without custom shaders.

Bitwise blend mode is required to implement some of the very specific graphical algorithms like [bitmask render](https://en.wikipedia.org/wiki/Mask_(computing)#Image_masks) at old game resources or use that to make several blend-based tricks, like, making invisible objects being visible because of color tricks.

### What about renderers support I had to dig:
- Software render shouldn't have any challenges, just use generic methods
- Windows GDI supports bitwise blend modes natively (using [BitBlt](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-bitblt) call and `SRCAND`, `SRCPAINT`, and `SRCINVERT` modes)
- OpenGL has logical operations as blend modes, and they were supported natively, no shaders are needed
- Vulkan supports natively: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap29.html#framebuffer-logicop, I also bet, there are no shaders needed. I hadn't used Vulkan directly yet, but I going to try somewhere later.

### What I don't know yet:
- DirectX: I never used DirectX at all, and I don't know its possibilities, but probably there are should be some of the blend modes available...
- Metal: Also don't know its possibilities...
- X11 renderer: I hadn't used software X11 rendering directly, as I always used OpenGL or Qt
- Wayland: also, I have no idea which APIs were used to render

**Comment by slouken** [comment]
If you provide a PR with support for the major renderers (software, opengl, opengles2, direct3d, direct3d11, metal) we'll consider applying it.

**Comment by slime73** [comment]
For reference, here are the graphics APIs that support fixed function pixel logic ops:
* Desktop OpenGL
* Direct3D 11.1 (Windows 8+)
* Vulkan (as an optional feature with only about 57% coverage according to the [gpuinfo database](https://vulkan.gpuinfo.org/listfeaturescore10.php)).

And here are the ones that don't support it:
* Metal
* Direct3D 11.0 (Windows 7)
* Direct3D 9
* 43% of Vulkan systems
* All OpenGL ES versions including OpenGL ES 1, 2, 3, and 3.2.

Some of the things you might use those logic ops for can also be accomplished by more broadly supported hardware features like stenciling (or more modern features like compute shaders).

**Comment by slime73** [comment]
For what it's worth I believe users of LÖVE have found general purpose stencil APIs pretty useful – but it seems a lot less appealing to add that sort of thing for a million backends compared to just one or two. Maybe if/when all those backends are replaced by the 3D API, additions like that will make more sense.

**Comment by TheSpydog** [comment]
It's still the same situation unfortunately. Metal doesn't support pixel logic ops at all and Vulkan hardware has even less(!?) widespread support than it did in 2022.

**Comment by Wohlstand** [comment]
Such stuff on new APIs can be done via shaders as I know. My co-developer @ds-sloth already did similar stuff with the modern OpenGL.

**Comment by ds-sloth** [comment]
Do you support the following workflow to emulate reading from the framebuffer in your GPU API?

* Render to texture A
* Copy portion of texture A to texture B
* Render to texture A while reading copied portion from texture B

If so, then logic op blending will be relatively easy for your clients to implement (though not terribly cheap).
