### ISSUE TITLE
testshader.c problem

### ISSUE THREAD

**Issue by padremayi** [libsdl-org/SDL#5456]
I added this shader

```
#version 120
varying vec4 Vertex_UV;
uniform mat4 gxl3d_ModelViewProjectionMatrix;
void main()
{
  gl_Position = gxl3d_ModelViewProjectionMatrix * gl_Vertex;
  Vertex_UV = gl_MultiTexCoord0;
}
```

```
#version 120
uniform sampler2D tex0;
varying vec4 Vertex_UV;
const float PI = 3.1415926535;
uniform float BarrelPower;

vec2 Distort(vec2 p)
{
    float theta  = atan(p.y, p.x);
    float radius = length(p);
    radius = pow(radius, BarrelPower);
    p.x = radius * cos(theta);
    p.y = radius * sin(theta);
    return 0.5 * (p + 1.0);
}

void main()
{
  vec2 xy = 2.0 * Vertex_UV.xy - 1.0;
  vec2 uv;
  float d = length(xy);
  if (d < 1.0)
  {
    uv = Distort(xy);
  }
  else
  {
    uv = Vertex_UV.xy;
  }
  vec4 c = texture2D(tex0, uv);
  gl_FragColor = c;
}
```

to [SDL](https://github.com/libsdl-org/SDL)/[test](https://github.com/libsdl-org/SDL/tree/main/test)/testshader.c but when I reach that shader I see only a (maybe???) black texture on black background.

Is there any problem with the example code?

**Comment by icculus** [comment]
Without looking closely, if all you did was change the shader source code, and haven't set values for `gxl3d_ModelViewProjectionMatrix` and `BarrelPower` with glUniform* calls in the C code, then this would definitely not work.

(testshader.c is not meant to be a robust framework for shader development, fwiw.)
