### ISSUE TITLE
Automatic mouse capture might interfere with manually initiated mouse capture

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#5457]
5ff42438e36e98c9d72ac70f5f5ce4599b96d3d2 added auto-capture for tracking mouse motion while buttons are pressed (enabled by default). It looks like this could interfere with applications that call `SDL_CaptureMouse()` themselves, most notably when the mouse button up event after clicking unexpectedly releases their mouse capture.

It seems like we might need some internal mouse capture function that knows the difference between auto-capture and manual capture to ensure that the external `SDL_CaptureMouse()` API still behaves as expected for existing applications. Auto-capture also causes observable changes to the window flags (setting `SDL_WINDOW_MOUSE_CAPTURE`), which we might want to also suppress for application compatibility reasons.

**Comment by sezero** [comment]
I'm experiencing an interference as I noted at https://github.com/libsdl-org/SDL/issues/5301#issuecomment-1084807920, but the games I try use SDL_SetRelativeMouseMode, not SDL_CaptureMouse.

**Comment by sezero** [comment]
Possibly related: https://github.com/libsdl-org/SDL/issues/5457

**Comment by slouken** [comment]
@icculus and I discussed this and the window flag should reflect the actual state, whether generated by an API call or the auto capture. We can revisit this if we find it's causing issues in real-world applications.
