### ISSUE TITLE
ERROR : Cannot receive mouse release event in some case

### ISSUE THREAD

**Issue by ChivenZhang** [libsdl-org/SDL#5461]
ERROR : I cannot receive mouse release event when i do what below: 
1. Press left mouse button
2. Press right mouse button
3. Release left mosue button
4. Release right mouse button （missing event）
, then I cannot get the last mouse release event in event loop.

**Comment by slouken** [comment]
What platform are you running on? If it's Windows, can you please try the latest snapshot?
https://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by ChivenZhang** [comment]
I have tried the snapshot you gave, it works well, thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 凌晨0:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [libsdl-org/SDL] ERROR : Cannot receive mouse release event in some case (Issue #5461)





 
What platform are you running on? If it's Windows, can you please try the latest snapshot?
 https://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by slouken** [comment]
Great, thanks!
