### ISSUE TITLE
Using SDL_SetRenderTarget(m_renderer, NULL) causes system to stop getting mouse inputs

### ISSUE THREAD

**Issue by db-tech** [libsdl-org/SDL#5471]
We experimenting with SDL2 and Dear-ImGui to create a simple editor for a GameEngine.
As some point we're switching the Renderer target from drawing to a texture back to drawing to a window by using NULL as the second parameter of SDL_SetRenderTarget.

Unfortunately if we do that, I cannot do anything anymore with my mouse. It seems nothing is getting mouse input anymore.
If is switch to another window (alt+tab) and back to the game window again, everything works perfectly again.

Does anyone have a clue what I might doing wrong here ?

I am using SDL2 2.0.20-2 on Manjaro Linux (gnome)

**Comment by icculus** [comment]
export the environment variable SDL_EVENT_LOGGING=2 before running your program. This will dump a flood of information to stderr as events flow through SDL's queue.

See if mouse events just sort of...stopped showing up? Then we can figure out what to do from there.

**Comment by db-tech** [comment]
Thanks for the hint @icculus , i just did that.
I seems that at the point when I switch the renderer to window (NULL) I will never get the event `SDL_WINDOWEVENT_LEAVE` and I get `SDL_MOUSEMOTION`events everywhere. 
So it behaves like as the window would be in fullscreen mode and span across all monitors (3 in my case), even so the window is in Window mode and pretty small.

Any Ideas what I could do wrong or do you need more infos ?

**Comment by icculus** [comment]
@slouken could this maybe the new automatic mouse capture code? I can't imagine why this would happen otherwise.

**Comment by slouken** [comment]
If you're still getting this, can you please post a minimal SDL test program that shows the issue, so we can debug it?

Thanks!

**Comment by db-tech** [comment]
Hi there, really sorry for not responding. Stressful time.
In the imgui example file imgui_impl_sdl.cpp there is this line

```c++
 SDL_CaptureMouse(bd->MouseButtonsDown != 0 ? SDL_TRUE : SDL_FALSE);
```
And this seemed to be the problem. I just added this:

```c++
#ifdef NDEBUG
    SDL_CaptureMouse(bd->MouseButtonsDown != 0 ? SDL_TRUE : SDL_FALSE);
#endif

```
as a workaround for the time beeing.
That also fixed an issue with problem (Mouse not working) while debugging.
Not sure why this is, will investigate further as soon as I have more time again.

**Comment by slouken** [comment]
Were you able to test with the latest snapshot? This might be fixed in https://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by slouken** [comment]
We're about to release a new SDL version, can you verify that it's been fixed in the latest code?

**Comment by icculus** [comment]
@db-tech Last call before 2.24 is finished, if you have time to verify we fixed this.

(if you're busy, that's okay, but we'd love to know if this is resolved for you or not.)

**Comment by db-tech** [comment]
Ok, i will test it this evening !

Am 9. Aug. 2022, 21:59, um 21:59, "Ryan C. Gordon" ***@***.***> schrieb:
***@***.*** Last call before 2.24 is finished, if you have time to verify

**Comment by db-tech** [comment]
Unfortunately I cannot test it at the moment. I did build this SDL2 version, but then I get a lot of undefined references with SDL_mixer SDL_image and SDL_ttf stuff... So i guess this takes more time that I can spend at the moment, I am sorry. I will test it at some point and give feetback. Sorry to be not of more help :-/

**Comment by slouken** [comment]
I'm going to go ahead and close this. Please reopen if you're still having this issue.

Thanks!
