### ISSUE TITLE
Joycon connected to BT dongle but not recognised within Yuzu after reconnecting

### ISSUE THREAD

**Issue by makapaka99** [libsdl-org/SDL#5488]
After disconnecting the Official Nintendo Joycons, they remain paired to my PC via a BT 5.0 dongle. When turning them on again, they connect to the PC however the lights continue to cycle and are not recognised by the yuzu emulator. Ive seen on other forums and posts that it might be an issue with SDL, as yuzu has implemented that into their emulator.

**Comment by german77** [comment]
Check that windows actually says connected. Windows has a bug where BT 5.0 joycons are always forgotten even when it says paired. You need to unpair and pair the controller again every time you turn on the joycon.

This is not a SDL or yuzu bug. It's a windows bug.

**Comment by slouken** [comment]
I have the same problem, and it appears to be a bug in the Windows 11 Bluetooth stack.
