### ISSUE TITLE
Access violation in SDL_WinRTApp::PumpEvents() on Xbox

### ISSUE THREAD

**Issue by mangledpixel** [libsdl-org/SDL#5489]
Running as a WinRT application on an Xbox Series S, `SDL_WinRTApp::PumpEvents()` (in SDL_winrtapp_direct3d.cpp) will sometimes crash at the line
`CoreWindow::GetForCurrentThread()->Dispatcher->ProcessEvents(CoreProcessEventsOption::ProcessAllIfPresent);` (Line 420)
with an access violation exception thrown from combase.dll, for example:
`Exception thrown at 0x00007FFFBEEFCD13 (combase.dll) in ####.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.`
This happens in about every 1 in 5 attempts. Other times it just runs perfectly fine.
I am unsure as to how to even debug this, as all the call stack shows is a path through Windows.UI.dll to combase.dll, neither of which I have symbols for.

**Comment by slouken** [comment]
Do you have a simple example that reproduces this? Offhand it seems like this could happen by pumping events off the main thread.

**Comment by mangledpixel** [comment]
I've created a simple [example](https://github.com/mangledpixel/SDLOnXboxTest) based on [the WinRT readme](https://github.com/libsdl-org/SDL/blob/main/docs/README-winrt.md) and ran it repeatedly hoping to reproduce the problem I was having in my main project, but so far I've not been able to do so.

When the crash does occur, it happens in the same thread (a thread named 'ApplicationView ASTA') that everything else (Init, CreateWindow etc) happened in. I'm not calling SDL_PollEvent from anywhere but the main game loop.

**Comment by slouken** [comment]
Is there an equivalent to `RoInitialize(RO_INIT_MULTITHREADED)` on Windows RT? I recently added a call to this on Win32 to fix mysterious crashes there, when using Windows.Gaming.Input. Maybe something similar is needed here?

**Comment by mangledpixel** [comment]
`RoInitialize` is apparently [available](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-api-ms-win-core-winrt-l1-1-0dll), though I gather the 'correct' thing to do is let winrt::init_apartment() do the work (which 'initializes the thread in the Windows Runtime; by default, in a multithreaded apartment' - though I'm not sure if that's the same thing). That isn't called anywhere in the current SDL code, though it may exist somewhere in the initialization of CoreApplication. If I try calling RoInitialize, where should I do so?

I'm afraid this is just a bit beyond my knowledge - I have never touched WinRT before starting this project.

**Comment by slouken** [comment]
I would try calling winrt::init_apartment() from the WinRT setup code and see if that fixes the issue.

**Comment by mangledpixel** [comment]
So, it turns out the apartment is already correctly initialized with the current call to `Windows::Foundation::Initialize` (which just wraps `RoInitialize`), and replacing that with `init_apartment` doesn't solve the issue.

Interestingly, while it's always crashing on CoreDispatcher::ProcessEvents, the exception is not always thrown from the same place. Often it's within combase.dll, but sometimes (as here) it's CoreMessaging.dll:

![image](https://user-images.githubusercontent.com/10273062/162923248-391b56af-4d6a-449c-80b5-b8bcb38e12f0.png)

I'm kinda stuck with even how to continue investigating why this happens.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
