### ISSUE TITLE
Steam Controller doesn't show up as a Joystick (Windows)

### ISSUE THREAD

**Issue by uramer** [libsdl-org/SDL#5490]
Has anybody had any success with getting Steam Controller recognized by SDL2? I've tried all the available connection methods (cable, dongle, Bluetooth) both with Steam on and off, and none worked.

I would like to support the touchpads natively, so simply using a Steam Input configuration isn't an option, and I don't want to use Steam Input API, rather than SDL.

I wonder if the same issue exists on Linux, and whether it affects Steam Deck as well. That could be more relevant, as Steam Controller is discontinued.

**Comment by slouken** [comment]
The Steam Controller is supported on mobile devices, but not on PC platforms where Steam is available. The Steam Input API really is a great way to support all kinds of controllers and is recommended where available. There are public implementations of Steam Controller support available (like the kernel patch for Linux) and you can talk directly to them using the SDL HIDAPI functions, so in theory you could add this support yourself, but that code hasn't been written to my knowledge.

On Steam Deck, Steam is always running so you shouldn't have an issue relying on Steam there.

**Comment by uramer** [comment]
Thanks for clarifying, I was confused about SDL's support for SC, and judging by some SDL forums posts, many other people were too.

The main problem with using Steam Input API is the license. E. g. it is not available to GPL projects. Although even without that, one of the core points of SDL is enabling cross-platform implementations, handling Steam API separately is really quite unfortunate.

Btw, technically it's not true that Steam is always running on Steam Deck. In desktop mode it is just a program, and you can run and stop it, same as it is on any Linux OS.
