### ISSUE TITLE
CMake 3.23.0 + SDL causes Qt AUTORCC to generate wrong UTF8 encoding

### ISSUE THREAD

**Issue by higaski** [libsdl-org/SDL#5494]
This is a weird one, I apologize upfront for the weird title and anything that follows. I've just made the switch from CMake 3.22.2 to 3.23.0 which causes a project I'm working on to suddenly not compile anymore. The project uses [Qt's resource system](https://doc.qt.io/qt-5/resources.html) to basically bake some .bmp files into the binary. CMake itself supports Qt's resource system by setting the variable [CMAKE_AUTORCC](https://cmake.org/cmake/help/latest/variable/CMAKE_AUTORCC.html).

Now some of the .bmp files contain German umlauts. For example on of the files is named `522.15 Panel ÖBB Hp0Hp1-R.Bmp`.

So far this filename has correctly been processed by CMake to `522.15 Panel \u00d6BB Hp0Hp1-R.Bmp` but with the latest version the capital Ö became `\u0582` which is wrong.

What does this have to do with SDL2 you ask? Well... the only way I can reproduce this behavior is by adding SDL2 to the projects dependencies. I've also posted this issue on the CMake repo [here](https://gitlab.kitware.com/cmake/cmake/-/issues/23399) as I still think that this is primarily their issue. However maybe someone here might have any idea on what's going on...

**Comment by madebr** [comment]
Does this problem still present itself?
If it is, can you provide a zip with a minimum reproducer?
I'm very suspicious SDL2 interfers with qt's resource system.

**Comment by madebr** [comment]
[The cmake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/23399) tells us it is a CMake regression, so closing this.
