### ISSUE TITLE
Recursive vs condition mutexes

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5497]
> Unfortunately, SDL has already painted itself into a corner by defining `SDL_mutex` to be a recursive (or reentrant) lock. For SDL 3, it might be a good idea to do what dbus did, and distinguish between "mutex that is compatible with condition variables but not necessarily recursive" and "mutex that is guaranteed to be recursive"?

_Originally posted by @smcv in https://github.com/libsdl-org/SDL/issues/5479#issuecomment-1090221325_

**Comment by slouken** [comment]
I don't think it's worth making this distinction. We should perhaps document this and leave it alone.
