### ISSUE TITLE
Using egl in sdl in android leads to crash

### ISSUE THREAD

**Issue by ZhenFTW** [libsdl-org/SDL#5498]
I want to create egl context using my sdl android app.  I know I can create the built in SDL_GL_createcontext but it doesn't work in my case. It only shows black screen on my attempt  to embed mpv on android using SDL. That's why I thought of using EGL. Down below is my code.  However the sdl asserts the following. Am I missing something here? The code below works fine in SDL windows application using angle jwith just simple difference. I am using the stable version of SDL. 
![image](https://user-images.githubusercontent.com/17694257/162252571-b378da0b-8a93-41b5-abea-c676b70c725a.png)

```
#include <stdlib.h>
#include <stdio.h>

#include "SDL.h"
#include "SDL_syswm.h"

#include <EGL/egl.h>
#include <GLES2/gl2.h>

using namespace std;


int main(int argc, char* argv[])
{
    SDL_Window* window = 0;
    
    if (0 != SDL_Init(SDL_INIT_VIDEO))
    {
        fprintf(stderr, "\nUnable to initialize SDL: %s\n", SDL_GetError());
        return 1;
    }
    window = SDL_CreateWindow("Glad Sample",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        800, 600, SDL_WINDOW_SHOWN |
        SDL_WINDOW_OPENGL);

  EGLint configAttribList[] =
    {
        EGL_RED_SIZE,       8,
        EGL_GREEN_SIZE,     8,
        EGL_BLUE_SIZE,      8,
        EGL_ALPHA_SIZE,     8 /*: EGL_DONT_CARE*/,
        EGL_DEPTH_SIZE,     EGL_DONT_CARE,
        EGL_STENCIL_SIZE,   EGL_DONT_CARE,
        EGL_SAMPLE_BUFFERS, 0,
        EGL_NONE
    };

    EGLint surfaceAttribList[] =
    {
        // EGL_CONTEXT_CLIENT_VERSION, 2,
         EGL_WIDTH, 800,
         EGL_HEIGHT, 600,
         EGL_NONE

    };
    EGLint attribListPbuffer[] = {
    EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
    EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
    EGL_BUFFER_SIZE, 32,
    EGL_DEPTH_SIZE, 24,
    EGL_STENCIL_SIZE, 8,
    EGL_NONE
    };

    EGLint numConfigs;
    EGLint majorVersion;
    EGLint minorVersion;
    EGLDisplay display;
    EGLContext context;
    EGLSurface surface;
    EGLConfig config;
    EGLint contextAttribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE, EGL_NONE };

    SDL_SysWMinfo info;
    SDL_VERSION(&info.version); // initialize info structure with SDL version info
    SDL_GetWindowWMInfo(window, &info);   
    SDL_bool get_win_info = SDL_GetWindowWMInfo(window, &info);
    SDL_assert_release(get_win_info);
    EGLNativeWindowType hWnd = info.info.android.window;

    // Get Display 
    display = eglGetDisplay(EGL_DEFAULT_DISPLAY); // EGL_DEFAULT_DISPLAY 
    if (display == EGL_NO_DISPLAY)
    {
        return EGL_FALSE;
    }

    // Initialize EGL 
    if (!eglInitialize(display, &majorVersion, &minorVersion))
    {
        return EGL_FALSE;
    }

    // Get configs 
    if (!eglGetConfigs(display, NULL, 0, &numConfigs))
    {
        return EGL_FALSE;
    }

    // Choose config 
    if (!eglChooseConfig(display, configAttribList, &config, 1, &numConfigs))
    {
        return EGL_FALSE;
    }

    // Create a 
    surface = eglCreateWindowSurface(display, config,hWnd, surfaceAttribList);
    if (surface == EGL_NO_SURFACE)
    {
        return EGL_FALSE;
    }
    context = eglCreateContext(display, config, EGL_NO_CONTEXT, contextAttribs);
    if (context == EGL_NO_CONTEXT)
    {
        return EGL_FALSE;
    }

    // Make the context current 
    if (!eglMakeCurrent(display, surface, surface, context))
    {
        return EGL_FALSE;
    }
    
    SDL_Event event;

    bool running = true;
    while (running)
    {
        SDL_PollEvent(&event);
        switch (event.type) {
        case SDL_QUIT:
            running = false;
            break;
        case SDL_WINDOWEVENT:
            if (event.window.event == SDL_WINDOWEVENT_EXPOSED)
              //  redraw = 1;
            break;
        }
       
        glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        eglSwapBuffers(display, surface);

    }
    SDL_DestroyWindow(window);
    SDL_Quit();

    exit(0);
}
```

**Comment by 1bsyl** [comment]
@ZhenFTW 
SDL_GetWindowWMInfo returns 1 / SDL_TRUE. which means ok. and triggers the assert(). 
"SDL_assert_release(get_win_info);"

**Comment by ZhenFTW** [comment]
> @ZhenFTW SDL_GetWindowWMInfo returns 1 / SDL_TRUE. which means ok. and strangely triggers the assert(). "SDL_assert_release(get_win_info);"
> 
> Can you try without using SDL_assert ?

I tried it and but the app still crashes.

**Comment by flibitijibibo** [comment]
Check SDL_GetError before the assert - the only error I can see is that the compiled and linked versions don't match.

**Comment by ZhenFTW** [comment]
> Check SDL_GetError before the assert - the only error I can see is that the compiled and linked versions don't match. I am using the stable build and made sure that the binary matches with the java sources matches with the same version. Anyone can reproduce this issue?

**Comment by ZhenFTW** [comment]
I am using the stable build and made sure that the binary matches with the java sources matches with the same version. Anyone can reproduce this issue?

**Comment by flibitijibibo** [comment]
It might be the headers then - we need the exact output of `SDL_GetError` to know exactly what went wrong (can be printf, log system, whatever's easiest to get the text).

For reference, this is what I think is the issue (if you're able to step in native code you should get here):

https://github.com/libsdl-org/SDL/blob/main/src/video/android/SDL_androidwindow.c#L209-L210

**Comment by 1bsyl** [comment]
I tried
```
04-08 07:58:47.735 24226 24270 I SDL/APP : SDL window: 0xb400007b5a3ee900 get_win_info:1 __ hWnd:0xb400007b5a35a010
04-08 07:58:47.736 24226 24270 E BufferQueueProducer: [SurfaceView[.MainActivity]#1(BLAST Consumer)1](id:5ea200000001,api:1,p:24226,c:24226) connect: already connected (cur=1 req=1)
04-08 07:58:47.736 24226 24270 E libEGL  : eglCreateWindowSurface: native_window_api_connect (win=0xb400007b5a35a010) failed (0xffffffea) (already connected to another API?)
04-08 07:58:47.736 24226 24270 E libEGL  : eglCreateWindowSurfaceTmpl:680 error 3003 (EGL_BAD_ALLOC)

```

**Comment by 1bsyl** [comment]
Android/SDL do that for you
or maybe you can compile without "SDL_VIDEO_OPENGL_EGL"

**Comment by 1bsyl** [comment]
https://github.com/libsdl-org/SDL/pull/5396

**Comment by 1bsyl** [comment]
I think the assert was trigger wrongly. it works but gets triggers :/ not sure why

**Comment by ZhenFTW** [comment]
This is the error 
![image](https://user-images.githubusercontent.com/17694257/162374489-7e23e814-740f-4a5c-8a72-fffb409b3800.png)
Which is weird.

**Comment by ZhenFTW** [comment]
I just logged it with  SDL_Log("SDL ERROR: %s\n", SDL_GetError());  without conditions.

**Comment by flibitijibibo** [comment]
Ah okay, so the issue is actually that the window didn't get made, so WMInfo is fine. The pixel format thing is where the Android stuff starts, so I'll slowly back out of the room now...

**Comment by ZhenFTW** [comment]
Any problem with how I initialized the window tho?
 `    window = SDL_CreateWindow( "An SDL2 window",  SDL_WINDOWPOS_UNDEFINED,  SDL_WINDOWPOS_UNDEFINED,     800,  600, SDL_WINDOW_OPENGL );` I changed it with this but still not working.

**Comment by 1bsyl** [comment]
@ZhenFTW i think you should compile like in #5396

**Comment by ZhenFTW** [comment]
> @ZhenFTW i think you should compile like in #5396

How to do that? Should shall I set DSDL_VIDEO_OPENGL_EGL=OFF?

**Comment by 1bsyl** [comment]
All the others flags.
You can hardcode in config.h

**Comment by ZhenFTW** [comment]
> All the others flags. You can hardcode in config.h

Tried it the the issue still the same.

**Comment by ZhenFTW** [comment]
![image](https://user-images.githubusercontent.com/17694257/162382803-41658e12-81ef-4786-9046-2428f80b75f7.png)

**Comment by 1bsyl** [comment]
@ZhenFTW if you remove "SDL_WINDOW_OPENGL" ?

**Comment by 1bsyl** [comment]
and set the hint, before creating the window: 
 "SDL_HINT_VIDEO_EXTERNAL_CONTEXT" hint.

**Comment by ZhenFTW** [comment]
![image](https://user-images.githubusercontent.com/17694257/162395901-65a954a7-f305-4b68-b458-193de6b4b16b.png)

**Comment by ZhenFTW** [comment]
> Sounds like SDL_CreateWindow() is called twice. ..
> 
> maybe AndroidManifest.xml hasn't the
> 
> ```
>  62                   android:alwaysRetainTaskState="true"
>  63                   android:launchMode="singleInstance"
> ```

Added it, still same issue.

**Comment by 1bsyl** [comment]
maybe add traces to SDL. 
inside: SDL_CreateWindow() call. 
inside:  Android_CreateWindow()

**Comment by ZhenFTW** [comment]
> maybe add traces to SDL. inside: SDL_CreateWindow() call. inside: Android_CreateWindow()

Sorry, but how? I'm still not that familiar with ndk and c++ debugging in general.

**Comment by 1bsyl** [comment]
edit the SDL sources you have, and write basic command to see some debug informaiotn
mostly: 

src/video/SDL_video.c:  
add:
SDL_Log("this is SDL_CreateWindow");

src/video/android/SDL_androidwindow.c:
add:
SDL_Log("this is Android_CreateWindow");

you shouldn't hit that previous error when it says you're creating twice the window.

btw, I ran you example, and it creates the window, 
then it failed because of CreateSurface attributes.
I didn't have to remove the compilation of opengl stuff. (like in 5396). ... (but well it may be better)
I just removed SDL_WINDOW_OPENGL of CreateWindow
and 
SDL_SetHint(SDL_HINT_VIDEO_EXTERNAL_CONTEXT, "1");

**Comment by ZhenFTW** [comment]
> edit the SDL sources you have, and write basic command to see some debug informaiotn mostly:
> 
> src/video/SDL_video.c: add: SDL_Log("this is SDL_CreateWindow");
> 
> src/video/android/SDL_androidwindow.c: add: SDL_Log("this is Android_CreateWindow");
> 
> you shouldn't hit that previous error when it says you're creating twice the window.
> 
> btw, I ran you example, and it creates the window, then it failed because of CreateSurface attributes. I didn't have to remove the compilation of opengl stuff. (like in 5396). ... (but well it may be better) I just removed SDL_WINDOW_OPENGL of CreateWindow and SDL_SetHint(SDL_HINT_VIDEO_EXTERNAL_CONTEXT, "1");

That is similar to what I just did. Revert back the compilation and remove opengl and just pass SDL_WINDOW_SHOWN instead of opengl but stillsame issue.

**Comment by 1bsyl** [comment]
@ZhenFTW I think you should use the SDL head git version. because the ReCreate Window code has changed and that may be the reason

**Comment by ZhenFTW** [comment]
> @ZhenFTW I think you should use the SDL head git version. because the ReCreate Window code has changed and that may be the reason

Does the window creation works fine on you now? Im using the latest version and still got the same error.

**Comment by ZhenFTW** [comment]
Here is my code,
```
#include <stdlib.h>
#include <stdio.h>

#include "SDL.h"
#include "SDL_syswm.h"

#include <EGL/egl.h>
#include <GLES2/gl2.h>

using namespace std;

int main(int argc, char* argv[])
{

    // SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    // SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION,2);

    if ( SDL_Init( SDL_INIT_EVERYTHING ) < 0 ) {
        
        SDL_Log("Could not create window: %s\n", SDL_GetError());
		return 1;
	} 

    SDL_SetHint(SDL_HINT_VIDEO_EXTERNAL_CONTEXT, "1");

    SDL_Window *window = NULL ; 
    
    window = SDL_CreateWindow(
        "An SDL2 window",                  // window title
        SDL_WINDOWPOS_UNDEFINED,           // initial x position
        SDL_WINDOWPOS_UNDEFINED,           // initial y position
        800,                               // width, in pixels
        600,                               // height, in pixels
        SDL_WINDOW_SHOWN          // flags - see below
    );

    // Check that the window was successfully created
    if (window == NULL) {
 
         SDL_Log("Could not create window: %s\n", SDL_GetError());
        //return 1;
    }
    //gl = SDL_GL_CreateContext(window);
    
    SDL_SysWMinfo info;
    SDL_VERSION(&info.version);
    SDL_bool get_win_info = SDL_GetWindowWMInfo(window, &info);
  
    SDL_Log("SDL ERROR: %s\n", SDL_GetError());
    
    SDL_assert_release(get_win_info);


SDL_version compiled;
SDL_version linked;

SDL_VERSION(&compiled);
SDL_GetVersion(&linked);
SDL_Log("We compiled against SDL version %u.%u.%u ...\n",
       compiled.major, compiled.minor, compiled.patch);
SDL_Log("But we are linking against SDL version %u.%u.%u.\n",
       linked.major, linked.minor, linked.patch);

EGLNativeWindowType hWnd = info.info.android.window;

  EGLint configAttribList[] =
    {
        EGL_RED_SIZE,       8,
        EGL_GREEN_SIZE,     8,
        EGL_BLUE_SIZE,      8,
        EGL_ALPHA_SIZE,     8 /*: EGL_DONT_CARE*/,
        EGL_DEPTH_SIZE,     EGL_DONT_CARE,
        EGL_STENCIL_SIZE,   EGL_DONT_CARE,
        EGL_SAMPLE_BUFFERS, 0,
        EGL_NONE
    };

    EGLint surfaceAttribList[] =
    {
        // EGL_CONTEXT_CLIENT_VERSION, 2,
         EGL_WIDTH, 800,
         EGL_HEIGHT, 600,
         EGL_NONE

    };
    EGLint attribListPbuffer[] = {
    EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
    EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
    EGL_BUFFER_SIZE, 32,
    EGL_DEPTH_SIZE, 24,
    EGL_STENCIL_SIZE, 8,
    EGL_NONE
    };

    EGLint numConfigs;
    EGLint majorVersion;
    EGLint minorVersion;
    EGLDisplay display;
    EGLContext context;
    EGLSurface surface;
    EGLConfig config;
    EGLint contextAttribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE, EGL_NONE };

  display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
    if (display == EGL_NO_DISPLAY)
    {
        return EGL_FALSE;
    }

    // Initialize EGL 
    if (!eglInitialize(display, &majorVersion, &minorVersion))
    {
        return EGL_FALSE;
    }

    // Get configs 
    if (!eglGetConfigs(display, NULL, 0, &numConfigs))
    {
        return EGL_FALSE;
    }

    if (!eglChooseConfig(display, configAttribList, &config, 1, &numConfigs))
    {
        return EGL_FALSE;
    }
    surface = eglCreateWindowSurface(display, config,hWnd, surfaceAttribList);
    if (surface == EGL_NO_SURFACE)
    {
        return EGL_FALSE;
    }
    context = eglCreateContext(display, config, EGL_NO_CONTEXT, contextAttribs);
    if (context == EGL_NO_CONTEXT)
    {
        return EGL_FALSE;
    }

    if (!eglMakeCurrent(display, surface, surface, context))
    {
        return EGL_FALSE;
    }

    SDL_Event event;
    bool running = true;
    while (running)
    {
        SDL_PollEvent(&event);
        switch (event.type) {
        case SDL_QUIT:
            running = false;
            break;
        case SDL_WINDOWEVENT:
            if (event.window.event == SDL_WINDOWEVENT_EXPOSED)
              //  redraw = 1;
            break;
        }
       
        glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
       // SDL_GL_SwapWindow(window);
        eglSwapBuffers(display, surface);



    }
    SDL_DestroyWindow(window);
    SDL_Quit();

    exit(0);
}
```
And this is the output. 
![image](https://user-images.githubusercontent.com/17694257/162554748-6fd6c381-1136-4c81-8c2e-0b6938a1a91b.png)
Using the latest SDL.

**Comment by ZhenFTW** [comment]
I think it's a bug with sdl_createwindow for android in general. I don't even not sure how window creation is possible with android using SDL. My programming knowledge is not enough to fix this issue hope someone guide me the right.

**Comment by 1bsyl** [comment]
It runs on my side ( I've just changed: init_video only. remove EGL_WIDTH/EGL_HEIGHT which give a bad attribute error. ).

It's not normal to have this error of double window creation when you only create one.
so maybe you have the apk/activity kept running. (so kill all app ? reboot the phone ?)
you should have in you android manifest.xml: 

activity
                    android:launchMode="singleInstance"


maybe you have other activities ?


```
#include <stdlib.h>
#include <stdio.h>

#include "SDL.h"
#include "SDL_syswm.h"

#include <EGL/egl.h>
#include <GLES2/gl2.h>

using namespace std;

int main(int argc, char* argv[])
{

    // SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    // SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION,2);

    if ( SDL_Init( SDL_INIT_VIDEO ) < 0 ) {
        SDL_Log("Could not init: %s\n", SDL_GetError());
	return 1;
    } 

    SDL_SetHint(SDL_HINT_VIDEO_EXTERNAL_CONTEXT, "1");

    SDL_Window *window = NULL ; 
    
    window = SDL_CreateWindow(
        "An SDL2 window",                  // window title
        SDL_WINDOWPOS_UNDEFINED,           // initial x position
        SDL_WINDOWPOS_UNDEFINED,           // initial y position
        800,                               // width, in pixels
        600,                               // height, in pixels
        SDL_WINDOW_SHOWN          // flags - see below
    );

    // Check that the window was successfully created
    if (window == NULL) {
 
         SDL_Log("Could not create window: %s\n", SDL_GetError());
        //return 1;
    }
    //gl = SDL_GL_CreateContext(window);
    
    SDL_SysWMinfo info;
    SDL_VERSION(&info.version);
    SDL_bool get_win_info = SDL_GetWindowWMInfo(window, &info);
  
    SDL_Log("SDL ERROR: %s\n", SDL_GetError());
    
    SDL_assert_release(get_win_info);


SDL_version compiled;
SDL_version linked;

SDL_VERSION(&compiled);
SDL_GetVersion(&linked);
SDL_Log("We compiled against SDL version %u.%u.%u ...\n",
       compiled.major, compiled.minor, compiled.patch);
SDL_Log("But we are linking against SDL version %u.%u.%u.\n",
       linked.major, linked.minor, linked.patch);

EGLNativeWindowType hWnd = info.info.android.window;

  EGLint configAttribList[] =
    {
        EGL_RED_SIZE,       8,
        EGL_GREEN_SIZE,     8,
        EGL_BLUE_SIZE,      8,
        EGL_ALPHA_SIZE,     8 /*: EGL_DONT_CARE*/,
        EGL_DEPTH_SIZE,     EGL_DONT_CARE,
        EGL_STENCIL_SIZE,   EGL_DONT_CARE,
        EGL_SAMPLE_BUFFERS, 0,
        EGL_NONE
    };

    EGLint surfaceAttribList[] =
    {
        // EGL_CONTEXT_CLIENT_VERSION, 2,
         EGL_NONE

    };
    EGLint attribListPbuffer[] = {
    EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
    EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
    EGL_BUFFER_SIZE, 32,
    EGL_DEPTH_SIZE, 24,
    EGL_STENCIL_SIZE, 8,
    EGL_NONE
    };

    EGLint numConfigs;
    EGLint majorVersion;
    EGLint minorVersion;
    EGLDisplay display;
    EGLContext context;
    EGLSurface surface;
    EGLConfig config;
    EGLint contextAttribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE, EGL_NONE };

  display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
    if (display == EGL_NO_DISPLAY)
    {
        return EGL_FALSE;
    }

    // Initialize EGL 
    if (!eglInitialize(display, &majorVersion, &minorVersion))
    {
        return EGL_FALSE;
    }

    // Get configs 
    if (!eglGetConfigs(display, NULL, 0, &numConfigs))
    {
        return EGL_FALSE;
    }

    if (!eglChooseConfig(display, configAttribList, &config, 1, &numConfigs))
    {
        return EGL_FALSE;
    }
    surface = eglCreateWindowSurface(display, config,hWnd, surfaceAttribList);
    if (surface == EGL_NO_SURFACE)
    {
        return EGL_FALSE;
    }
    context = eglCreateContext(display, config, EGL_NO_CONTEXT, contextAttribs);
    if (context == EGL_NO_CONTEXT)
    {
        return EGL_FALSE;
    }

    if (!eglMakeCurrent(display, surface, surface, context))
    {
        return EGL_FALSE;
    }

    SDL_Event event;
    bool running = true;
    while (running)
    {
        SDL_PollEvent(&event);
        switch (event.type) {
        case SDL_QUIT:
            running = false;
            break;
        case SDL_WINDOWEVENT:
            if (event.window.event == SDL_WINDOWEVENT_EXPOSED)
              //  redraw = 1;
            break;
        }
       
        glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
       // SDL_GL_SwapWindow(window);
        eglSwapBuffers(display, surface);



    }
    SDL_DestroyWindow(window);
    SDL_Quit();

    exit(0);
}


```

**Comment by ZhenFTW** [comment]
> 

Tysm, the code actually works now,. So the error was actually my fault. It triggers everytime I open the app the second time or more so it works the first time around but I just gotta deal with other errors.  The code works but it goes black screen when I go back to home screen or switch to another app. But gotta say I'm getting closer there. Thanks for your time.

**Comment by ZhenFTW** [comment]
New error is this.  Can you reproduce? try switching to another app and go back to the application.
![image](https://user-images.githubusercontent.com/17694257/162562776-4e9bb37d-d030-418e-8eed-b1fd7d1e010d.png)

**Comment by ZhenFTW** [comment]
> It runs on my side ( I've just changed: init_video only. remove EGL_WIDTH/EGL_HEIGHT which give a bad attribute error. ).
> 
> It's not normal to have this error of double window creation when you only create one. so maybe you have the apk/activity kept running. (so kill all app ? reboot the phone ?) you should have in you android manifest.xml:
> 
> activity android:launchMode="singleInstance"
> 
> maybe you have other activities ?
> 
> ```
> #include <stdlib.h>
> #include <stdio.h>
> 
> #include "SDL.h"
> #include "SDL_syswm.h"
> 
> #include <EGL/egl.h>
> #include <GLES2/gl2.h>
> 
> using namespace std;
> 
> int main(int argc, char* argv[])
> {
> 
>     // SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
>     // SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION,2);
> 
>     if ( SDL_Init( SDL_INIT_VIDEO ) < 0 ) {
>         SDL_Log("Could not init: %s\n", SDL_GetError());
> 	return 1;
>     } 
> 
>     SDL_SetHint(SDL_HINT_VIDEO_EXTERNAL_CONTEXT, "1");
> 
>     SDL_Window *window = NULL ; 
>     
>     window = SDL_CreateWindow(
>         "An SDL2 window",                  // window title
>         SDL_WINDOWPOS_UNDEFINED,           // initial x position
>         SDL_WINDOWPOS_UNDEFINED,           // initial y position
>         800,                               // width, in pixels
>         600,                               // height, in pixels
>         SDL_WINDOW_SHOWN          // flags - see below
>     );
> 
>     // Check that the window was successfully created
>     if (window == NULL) {
>  
>          SDL_Log("Could not create window: %s\n", SDL_GetError());
>         //return 1;
>     }
>     //gl = SDL_GL_CreateContext(window);
>     
>     SDL_SysWMinfo info;
>     SDL_VERSION(&info.version);
>     SDL_bool get_win_info = SDL_GetWindowWMInfo(window, &info);
>   
>     SDL_Log("SDL ERROR: %s\n", SDL_GetError());
>     
>     SDL_assert_release(get_win_info);
> 
> 
> SDL_version compiled;
> SDL_version linked;
> 
> SDL_VERSION(&compiled);
> SDL_GetVersion(&linked);
> SDL_Log("We compiled against SDL version %u.%u.%u ...\n",
>        compiled.major, compiled.minor, compiled.patch);
> SDL_Log("But we are linking against SDL version %u.%u.%u.\n",
>        linked.major, linked.minor, linked.patch);
> 
> EGLNativeWindowType hWnd = info.info.android.window;
> 
>   EGLint configAttribList[] =
>     {
>         EGL_RED_SIZE,       8,
>         EGL_GREEN_SIZE,     8,
>         EGL_BLUE_SIZE,      8,
>         EGL_ALPHA_SIZE,     8 /*: EGL_DONT_CARE*/,
>         EGL_DEPTH_SIZE,     EGL_DONT_CARE,
>         EGL_STENCIL_SIZE,   EGL_DONT_CARE,
>         EGL_SAMPLE_BUFFERS, 0,
>         EGL_NONE
>     };
> 
>     EGLint surfaceAttribList[] =
>     {
>         // EGL_CONTEXT_CLIENT_VERSION, 2,
>          EGL_NONE
> 
>     };
>     EGLint attribListPbuffer[] = {
>     EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
>     EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
>     EGL_BUFFER_SIZE, 32,
>     EGL_DEPTH_SIZE, 24,
>     EGL_STENCIL_SIZE, 8,
>     EGL_NONE
>     };
> 
>     EGLint numConfigs;
>     EGLint majorVersion;
>     EGLint minorVersion;
>     EGLDisplay display;
>     EGLContext context;
>     EGLSurface surface;
>     EGLConfig config;
>     EGLint contextAttribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE, EGL_NONE };
> 
>   display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
>     if (display == EGL_NO_DISPLAY)
>     {
>         return EGL_FALSE;
>     }
> 
>     // Initialize EGL 
>     if (!eglInitialize(display, &majorVersion, &minorVersion))
>     {
>         return EGL_FALSE;
>     }
> 
>     // Get configs 
>     if (!eglGetConfigs(display, NULL, 0, &numConfigs))
>     {
>         return EGL_FALSE;
>     }
> 
>     if (!eglChooseConfig(display, configAttribList, &config, 1, &numConfigs))
>     {
>         return EGL_FALSE;
>     }
>     surface = eglCreateWindowSurface(display, config,hWnd, surfaceAttribList);
>     if (surface == EGL_NO_SURFACE)
>     {
>         return EGL_FALSE;
>     }
>     context = eglCreateContext(display, config, EGL_NO_CONTEXT, contextAttribs);
>     if (context == EGL_NO_CONTEXT)
>     {
>         return EGL_FALSE;
>     }
> 
>     if (!eglMakeCurrent(display, surface, surface, context))
>     {
>         return EGL_FALSE;
>     }
> 
>     SDL_Event event;
>     bool running = true;
>     while (running)
>     {
>         SDL_PollEvent(&event);
>         switch (event.type) {
>         case SDL_QUIT:
>             running = false;
>             break;
>         case SDL_WINDOWEVENT:
>             if (event.window.event == SDL_WINDOWEVENT_EXPOSED)
>               //  redraw = 1;
>             break;
>         }
>        
>         glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
>         glClear(GL_COLOR_BUFFER_BIT);
>        // SDL_GL_SwapWindow(window);
>         eglSwapBuffers(display, surface);
> 
> 
> 
>     }
>     SDL_DestroyWindow(window);
>     SDL_Quit();
> 
>     exit(0);
> }
> ```

Oh so this might be the error. That you're talking about

**Comment by 1bsyl** [comment]
ok so I marked the issue as closed.

now you're going to hit each bug sdl fix for you when handling the context.
eg: black screen when using egl while in background. save and restore ctx. ..

**Comment by ZhenFTW** [comment]
> ok so I marked the issue as closed.
> 
> now you're going to hit each bug sdl fix for you when handling the context. eg: black screen when using egl while in background. save and restore ctx. ..

Thanks you helped me lots.

**Comment by ZhenFTW** [comment]
> ok so I marked the issue as closed.
> 
> now you're going to hit each bug sdl fix for you when handling the context. eg: black screen when using egl while in background. save and restore ctx. ..

Hello, sorry I know it is marked as closed but got last question to ask. Is it something to do with this code? Thanks for helping btw. Just need validation so I know I'm in the right path. Idk where to contact you so I'll just ask this here.

**Comment by ZhenFTW** [comment]
> > ok so I marked the issue as closed.
> > now you're going to hit each bug sdl fix for you when handling the context. eg: black screen when using egl while in background. save and restore ctx. ..
> 
> Hello, sorry I know it is marked as closed but got last question to ask. Is it something to do with this code? https://github.com/libsdl-org/SDL/blob/727eef7064e02aea89281493d0c5f16ad9e3c16f/src/video/android/SDL_androidevents.c#L71-L100 Thanks for helping btw. Just need validation so I know I'm in the right path. Idk where to contact you so I'll just ask this here.

**Comment by ZhenFTW** [comment]
> > > ok so I marked the issue as closed.
> > > now you're going to hit each bug sdl fix for you when handling the context. eg: black screen when using egl while in background. save and restore ctx. ..
 
@1bsyl. Hello, sorry I know it is marked as closed but got last question to ask. Is it something to do with this code? https://github.com/libsdl-org/SDL/blob/727eef7064e02aea89281493d0c5f16ad9e3c16f/src/video/android/SDL_androidevents.c#L71-L100
Thanks for helping btw. Just need validation so I know I'm in the right path. Idk where to contact you so I'll just ask this here.

**Comment by 1bsyl** [comment]
@ZhenFTW 
yes you need this code, something similar. 
you maybe need to poll SDL event / detect background events and save / restore things

in background, no use of renderer things
