### ISSUE TITLE
Support compiling with clang modules

### ISSUE THREAD

**Issue by izackp** [libsdl-org/SDL#5499]
Clang Modules solve these problems:
* Compile-time scalability: Redundant headers are only processed once
* Fragility: Unintended defines can break builds. Avoids macro collisions, and the developer worring about the order of includes.
* Less confusion: No worry about ordering, or if the header is meant to be apart of the api. 
* Compatiblity with Swift Package Manager

But the real question is, is it worth the effort and change to the existing code base and is it necessary? 

---
### Additional Info
Context:
I'm currently trying to get SDL2 to support clang's modules ([intro](https://clang.llvm.org/docs/Modules.html#introduction)). The idea being that modules is required to build c code with swift pm ([ref](https://bugs.swift.org/browse/SR-15080?focusedCommentId=63499&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-63499)). Using swiftpm I can make a SDL package from it and have the same workflow on all platforms that support the swift toolchain as well as simplify the cross compilation process. 

Why care about swift and swift pm?
Swift currently has toolchains with varying support for OSX, Windows, Android, WASI. Its currently a goal for swift to start expanding the number of platforms (Part of its #1 goal here: https://forums.swift.org/t/on-the-road-to-swift-6/32862).

Practical difficulty:
Personally, for clang modules, I have very limited personal experience with them besides this one project. So far its been quite difficult porting sdl2 to support being compiled with swift package manager + module maps as documentation and explanations on them are quite shallow. 

Notable:
There are already swift SDL packages with module maps, but they utilize a dynamic system library while I'm hoping to support a platform (iOS) with a static library. It all somehow works when things are already compiled and module maps are added after the fact and not used during compilation.

Nobody is complaining?
Some extensive google searching has shown there isn't anyone attempting to compile SDL2 with modules besides me. I guess that's why I'm making this ticket to see if people do care.

Either way, I just wanted to throw this out there for consideration to see if it would even add any value to the project. 

Thanks for your time.

**Comment by Zopolis4** [comment]
I would also like to be able to consume SDL in module form, as I am rewriting a project of mine to use modules but it is still hindered by the SDL2 include in terms of file size and compilation speed. I thought it would also be worth noting that modules are a part of the C++20 standard, and are supported by most compilers.

**Comment by slouken** [comment]
Feel free to create a PR that adds support for clang modules, but there hasn't been any activity on this for the past year, so I'm going to close it for now.
