### ISSUE TITLE
Rumble doesn't work with XBox 360 controller on Windows - (older issue #5351)

### ISSUE THREAD

**Issue by DarkerSquirrel** [libsdl-org/SDL#5502]
Hello  , 

Since #5351 has been closed and couldn't post there, I opened a new issue.

My XBOX 360 controller doesn't rumble with latest git (or latest stable).
(Controller is recognized by SDL2 as Xbox360 controller).

while(true)
if (SDL_GameControllerRumble(gamecontroller, 0xFFFF * 3 / 4, 0xFFFF * 3 / 4, 500) != 0)
		{
			printf("Warning: Unable to play game contoller rumble! %s\n", SDL_GetError());
		}

Err message: "controller isn't correlated yet , try hitting a button first!"

Even if a press a button , nothing happens, err keeps showing. 
Can you please fix this,it's a pitty that such a popular controller can't be rumbled with SDL2!
If there is anything I can do to debug this, please let me know!

Another question: Is it possible/advisable to move the rumbling code in SDL2 on a separate thread?
Rumbling can take a while , which blocks the thread in the meantime.

Win 8.1 , i7. Xbox360 controller.

Thanks

**Comment by slouken** [comment]
You need to update the game controller state in order to correlate controllers.
Try adding a call to SDL_JoystickUpdate() in your loop, if you're not going to call other SDL event functions.

You can also disable the raw input controller code if you don't need more advanced features, like support for more than 4 controllers:
```c
SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");
```

**Comment by DarkerSquirrel** [comment]
Thanks v much for suggestions , slouken.

Rumbling doesn't seem to work without SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");
It doesn't need SDL_JoystickUpdate() though.

But I have another issue now, rumbling doesn't stop once started. ( it should stop after 500 ms set in parameter).
Even if  I set parameter value 0 ms , rumbling still starts and doesn't stop anymore.
What am I missing here?

I use this small code to test:

Thanks

	SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");
	if (SDL_Init(SDL_INIT_EVERYTHING) < 0)
	{
		fprintf(stderr, "Couldn't initialize SDL: %s\n", SDL_GetError());
		exit(1);
	}

	printf("%i joysticks were found.\n\n", SDL_NumJoysticks());
	printf("The names of the joysticks are:\n");
	printf("name=%s\n", SDL_GameControllerNameForIndex(0));

	auto gamecontroller = SDL_GameControllerOpen(0);

	if (gamecontroller == nullptr)
		printf("ERROR\n");


	SDL_GameControllerUpdate();


	if (SDL_GameControllerRumble(gamecontroller, 0xFFFF * 3 / 4, 0xFFFF * 3 / 4, 500) != 0)
	{
		printf("Warning: Unable to play game contoller rumble! %s\n", SDL_GetError());
	}

	
	std::cin.get();

	SDL_Quit();
	return 0;

**Comment by 0x1F9F1** [comment]
> Thanks v much for suggestions , slouken.
> 
> Rumbling doesn't seem to work without SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0"); It doesn't need SDL_JoystickUpdate() though.
> 
> But I have another issue now, rumbling doesn't stop once started. ( it should stop after 500 ms set in parameter). Even if I set parameter value 0 ms , rumbling still starts and doesn't stop anymore. What am I missing here?

The rumble timeout is handled in SDL_JoystickUpdate, which is called by SDL_GameControllerUpdate or SDL_PumpEvents (or the related event functions), so you need to keep calling one of those instead of halting the app with `std::cin.get();`

**Comment by slouken** [comment]
You can use the testgamecontroller test program included with SDL to try out various game controller functions, including rumble.

Please let us know if you're seeing any issues with testgamecontroller, and I'll close this bug in the meantime.
