### ISSUE TITLE
gendynapi.pl generated bad output for a function pointer parameter

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5507]
If I add this to SDL_stdinc.h:
```
extern DECLSPEC void * SDLCALL SDL_bsearch(const void *key, const void *base, size_t nmemb, size_t size, int (*compare) (const void *, const void *));
```

... then gendynapi.pl outputs this to SDL_dynapi_procs.h:
```
SDL_DYNAPI_PROC(void*,SDL_bsearch,(const void *a, const void *b, size_t c, size_t d, int e, const void *f),(a,b,c,d,e,f),return)
```
The correct one should be this, i.e. like SDL_qsort:
```
SDL_DYNAPI_PROC(void*,SDL_bsearch,(const void *a, const void *b, size_t c, size_t d, int (*e)(const void *, const void *)),(a,b,c,d,e),return)
```

Unless I'm doing something incredibly wrong..

If it matters, my perl version is 5.10.1 (perl-5.10.1-144.el6.i686)

**Comment by icculus** [comment]
It's likely a bug in my perl code. The fastest fix would be to wrap the function pointer in a typedef, but I can look at the perl code if this is a dealbreaker.

**Comment by sezero** [comment]
Not a real deal breaker, at least not urgent, but was surprising: I guess the entry for SDL_qsort was hand-corrected back in the day because of this.

**Comment by icculus** [comment]
I just looked at this code, and it's just not worth extending it to make it parse these sort of constructs, now that I can see it'll work around it for future runs with hand-editing.

When we put the bsearch PR in, it'll have Ozkan's hand-edit, and that's good enough.
