### ISSUE TITLE
Windows: Fullscreen windows stuck on top after Alt+Tab focus loss

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#5509]
4e784fce431d588a949517fafece5903d1acae44  introduced a regression where Alt+Tab doesn't work properly if the window enters fullscreen mode while already having input focus. That particular code was modified a few times since, but the bug remains.

It looks like we hit this path where `HWND_TOPMOST` is set, but nothing ever sets `HWND_NOTOPMOST` later to undo that. As a result, the window stays on top even after losing focus via Alt+Tab.

https://github.com/libsdl-org/SDL/blob/727eef7064e02aea89281493d0c5f16ad9e3c16f/src/video/windows/SDL_windowswindow.c#L744-L748

Setting `HWND_NOTOPMOST` used to happen in `WIN_SetWindowPositionInternal()`  when `SDL_OnWindowFocusLost()` ungrabbed the mouse, so this broke when we stopped doing that in 4e784fce431d588a949517fafece5903d1acae44.

When launching with `--fullscreen-desktop` (which does not trigger the bug), we don't have input focus at the point we reach that code, so we don't set `HWND_TOPMOST` and don't get the bug. This makes me wonder whether we need `HWND_TOPMOST` for fullscreen windows at all. Windows seems to manage their Z order just fine on its own.

Repro steps:
1. Start testgl2.exe
2. Make sure the test window is focused and press Alt+Enter to enter fullscreen desktop mode
3. Press Alt+Tab and try to select another window

**Comment by slouken** [comment]
I’m out on vacation, do you have a patch you’d like to propose? We can look at removing topmost after 2.0.24 release, but we should definitely fix this regression.

**Comment by cgutman** [comment]
With the current code, applications will be assigned a `HWND_TOPMOST` fullscreen window if they happen to be focused when they enter fullscreen (for example: games that always start windowed then kick into fullscreen). If they are not focused at the time (maybe they pass `SDL_WINDOW_FULLSCREEN` during window creation), they will have a `HWND_NOTOPMOST` fullscreen window. 

I have a couple PoCs that work to address the issue, but they both change the behavior in ways that could be risky for some applications due to the non-deterministic behavior mentioned above.

Setting `HWND_TOPMOST` and `HWND_NOTOPMOST` when gaining/losing focus preserves behavior for the `HWND_TOPMOST` fullscreen scenario most accurately, but results in applications that were previously in the `HWND_NOTOPMOST` scenario using `HWND_TOPMOST` now. I'm also not sure if there are potential negative side effects from calling `SetWindowPos()` on focus change like this.
```
diff --git a/src/video/windows/SDL_windowsevents.c b/src/video/windows/SDL_windowsevents.c
index ebd0dd1f9..577347e83 100644
--- a/src/video/windows/SDL_windowsevents.c
+++ b/src/video/windows/SDL_windowsevents.c
@@ -430,11 +430,19 @@ WIN_UpdateFocus(SDL_Window *window, SDL_bool expect_focus)
         SDL_ToggleModState(KMOD_NUM, (GetKeyState(VK_NUMLOCK) & 0x0001) != 0);
         SDL_ToggleModState(KMOD_SCROLL, (GetKeyState(VK_SCROLL) & 0x0001) != 0);
 
+        if (window->flags & SDL_WINDOW_FULLSCREEN) {
+            SetWindowPos(hwnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
+        }
+
     } else {
         RECT rect;
 
         data->in_window_deactivation = SDL_TRUE;
 
+        if ((window->flags & SDL_WINDOW_FULLSCREEN) && !(window->flags & SDL_WINDOW_ALWAYS_ON_TOP)) {
+            SetWindowPos(hwnd, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
+        }
+
         SDL_SetKeyboardFocus(NULL);
         WIN_ResetDeadKeys();
 ```

Removing usage of `HWND_TOPMOST` for fullscreen windows preserves behavior for applications already hitting the `HWND_NOTOPMOST` fullscreen path but changes behavior for applications that hit `HWND_TOPMOST` before:
```
diff --git a/src/video/windows/SDL_windowswindow.c b/src/video/windows/SDL_windowswindow.c
index 90566d884..6dcea5bf2 100644
--- a/src/video/windows/SDL_windowswindow.c
+++ b/src/video/windows/SDL_windowswindow.c
@@ -158,7 +158,7 @@ WIN_SetWindowPositionInternal(_THIS, SDL_Window * window, UINT flags)
     int w, h;
 
     /* Figure out what the window area will be */
-    if (SDL_ShouldAllowTopmost() && ((window->flags & (SDL_WINDOW_FULLSCREEN|SDL_WINDOW_INPUT_FOCUS)) == (SDL_WINDOW_FULLSCREEN|SDL_WINDOW_INPUT_FOCUS) || (window->flags & SDL_WINDOW_ALWAYS_ON_TOP))) {
+    if (SDL_ShouldAllowTopmost() && (window->flags & SDL_WINDOW_ALWAYS_ON_TOP)) {
         top = HWND_TOPMOST;
     } else {
         top = HWND_NOTOPMOST;
@@ -741,7 +741,7 @@ WIN_SetWindowFullscreen(_THIS, SDL_Window * window, SDL_VideoDisplay * display,
         return;
     }
 
-    if (SDL_ShouldAllowTopmost() && ((window->flags & (SDL_WINDOW_FULLSCREEN|SDL_WINDOW_INPUT_FOCUS)) == (SDL_WINDOW_FULLSCREEN|SDL_WINDOW_INPUT_FOCUS) || window->flags & SDL_WINDOW_ALWAYS_ON_TOP)) {
+    if (SDL_ShouldAllowTopmost() && (window->flags & SDL_WINDOW_ALWAYS_ON_TOP)) {
         top = HWND_TOPMOST;
     } else {
         top = HWND_NOTOPMOST;
```

**Comment by slouken** [comment]
I went with the approach of removing HWND_TOPMOST for fullscreen windows, hopefully that's the safer change.
