### ISSUE TITLE
Add a way to force X11 programmatically?

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#5528]
Because Unix GUIs have traditionally been synonymous with X11, lots of Linux/Unix software will connect to a display server using protocol-agnostic APIs like SDL or GTK, then blindly assume that it is an X11 display and do X11-specific things with it. We saw this in GTK when GTK 3 gained native Wayland support, and we're seeing it again in SDL now that more distributions are compiling SDL 2 with native Wayland support, particularly now that 2.0.22rc1 behaves like GTK 3 by prioritizing native Wayland higher than X11.

A GTK example is that in Vim's GTK GUI, all the text is one big GTK widget, and instead of drawing text the GTK way (with Cairo), Vim draws its text by requesting the underlying X11 window and scribbling on it directly with X11 APIs. A SDL example is that as mentioned in https://github.com/libsdl-org/SDL/issues/5527#issuecomment-1097872619, games that use NVIDIA Cg use X11 directly, and so do games that call glXGetProcAddress() or similar.

The GTK developers added a way for developers who know they are going to use X11 directly to force the issue: you can call `gdk_set_allowed_backends ("x11")` to require that specific backend to be used, and [Vim now does that](https://github.com/vim/vim/commit/f80663f17b2f2499b45eb4467088704c8298c385).

I think it might be a good idea for SDL to have something similar, so that in games that are still maintained, if the maintainer knows they are using X11 directly, they can bypass the native Wayland video driver and force use of the X11 video driver (which will end up using Xwayland).

**Comment by sulix** [comment]
I think ``setenv("SDL_VIDEODRIVER", "x11", 1)`` before ``SDL_Init()`` is supported as a way of doing that…

This is, at least, [what sdl12-compat does](https://github.com/libsdl-org/sdl12-compat/blob/main/src/SDL12_compat.c#L2006).

**Comment by smcv** [comment]
Yes, developers could already do this with something like:

```
int main(int argc, char **argv)
{
#ifdef SDL_VIDEO_DRIVER_X11
    /* Always use X11 on platforms that support it, not native Wayland */
    setenv("SDL_VIDEODRIVER", "x11", 1);
#endif

    ... the rest of the code ...
}
```

But that will "leak" into subprocesses, because of how environment variables work.

**Comment by flibitijibibo** [comment]
Yeah, at the moment the environment variable is the only path to take. In the context of something like Steam, for example, it would need to set it to `x11` for native and `windows` when using Proton (probably not other tools though, including Luxtorpeda).

**Comment by slouken** [comment]
You can use `SDL_SetHint()` which sets it for the current application, but doesn’t leak into the environment.

**Comment by icculus** [comment]
> You can use SDL_SetHint() which sets it for the current application, but doesn’t leak into the environment.

SDL_VIDEODRIVER isn't wired up to the hint system though:

https://github.com/libsdl-org/SDL/blob/c36bd78474c962119db2f5161be6b0d4f07d535e/src/video/SDL_video.c#L427-L429

This is probably because this likely goes back to the 1.0 days. I'm not sure what the ramifications are of moving to SDL_GetHint() now, but if it's safe to do so, maybe we should.

**Comment by icculus** [comment]
One could always force the environment variable if unset, call SDL_Init, and then unset it again, though.

**Comment by slouken** [comment]
Yeah, let’s go ahead and switch it (and the corresponding audio variable) to use the hint system.

**Comment by icculus** [comment]
There's the pull request that does it, in #5544, in case we want it for 2.0.22. If not, we can click merge as soon as the release goes out the door.
