### ISSUE TITLE
[Wayland] Crash when many input events queued when application is not responsive temporarily.

### ISSUE THREAD

**Issue by p2004a** [libsdl-org/SDL#5536]
When there is a pause in the rendering loop when using SDL under wayland (e.g. assets are being loaded synchronously from disk in main thread) and when during that break there is a lot of events queued (e.g. move mouse a lot), the next call to `SDL_PollEvent` will make the wayland window crash.

Example small snippet that can be used to reproduce:

```c++
int counter = 1;
while (!done) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        if (event.type == SDL_QUIT)
            done = true;
        if (event.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_CLOSE && event.window.windowID == SDL_GetWindowID(window))
            done = true;
    }
    SDL_GL_SwapWindow(window);
    ++counter;
    if (counter % 1000 == 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(5000));
    }
}
```

If you just keep the mouse over the window and do nothing, all is fine, when I move the mouse a lot over the window it crashes without any error message. My compositor though produces "WL: error in client communication" in syslog.

Tested under Gnome 42, and nested weston and sway compositors. Tested 2.0.20 and master (55a4e1d336db0dd0af70bf22df8ec3ae0b38644a) versions. Doing the same type of stalling of main thread when using GLFW (tested just to see if it's a generic behavior for unresponsive windows) doesn't result in any crashes like this.

**Comment by flibitijibibo** [comment]
This crash occurs in libwayland rather than SDL, see #4769

**Comment by p2004a** [comment]
Ah, looks like exactly the same case and I just failed to find that closed issue. This can be probably closed as duplicate then.

(I wonder what GLFW does that I'm unable to trigger it in that library :thinking: but that's not a topic for SDL issue tracker)

**Comment by flibitijibibo** [comment]
If you find out what GLFW does I'd like to know - I didn't see anything out of the ordinary in their implementation (but they also haven't gotten to the wacky stuff like surface suspension yet, so who knows).

**Comment by p2004a** [comment]
@flibitijibibo I think I found the culprit...

Under weston I can make both GLFW and SDL windows to crash. The behavior there is the same. Under Gnome 42 though only SDL has issue, GLFW is fine.

Under Gnome, they merged https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2122 as a stop gap for this issue as part of merging https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1915. This is what is preventing the GLFW window to crash: after a bunch of pointer events with accompanying pings is send, but there aren't responses to ping requests, mutter stops sending pointer events to the GLFW window, preventing queue in compositor to overflow.

Why it doesn't help in SDL? SDL is using libdecor, and it looks to me like when this library is used there are 2 different wayland objects (surfaces?) created, each of them listening for pointer events. I think this causes the buffer on the server side to fill twice as fast and Gnome's protection doesn't help.

I've compiled SDL without libdecor support and then only one target of pointer events is created and Gnome protection prevents the crash.

Is there something in the integration with libdecor that can be changed to always have only one receiver of pointer events? Or is it the nature of how this library is implemented that it's not possible and 2 pointer targets are required?

---

Here is how the events (`WAYLAND_DEBUG=1`) look for GLFW/SDL without libdecor:

```
[2395664.787]  -> wl_pointer@21.motion(44815995, 1226.00000000, 48.00000000)
[2395664.801]  -> wl_pointer@21.frame()
[2395665.763]  -> wl_pointer@21.motion(44815996, 1226.00000000, 49.00000000)
[2395665.776]  -> wl_pointer@21.frame()
```

and here how it looks for with libdecor:

```
[3151389.084]  -> wl_pointer@28.motion(45571720, 405.00000000, 354.00000000)
[3151389.088]  -> wl_pointer@25.motion(45571720, 405.00000000, 354.00000000)
[3151389.091]  -> wl_pointer@25.frame()
[3151392.016]  -> wl_pointer@28.motion(45571723, 405.00000000, 353.00000000)
[3151392.023]  -> wl_pointer@25.motion(45571723, 405.00000000, 353.00000000)
[3151392.030]  -> wl_pointer@25.frame()
```

**Comment by flibitijibibo** [comment]
I believe this is just how libdecor decorates, or at least how the default cairo plugin works - might be a good question to ask upstream, now that I think about it

**Comment by p2004a** [comment]
I've opened question in `libdecor` https://gitlab.gnome.org/jadahl/libdecor/-/issues/35 and also opened the issue in `mutter` to highlight the issue there too https://gitlab.gnome.org/GNOME/mutter/-/issues/2234.

**Comment by flibitijibibo** [comment]
Will keep this open just in case then - but yeah, definitely not going to make it to 2.0.22 since third parties will need time to assess this.

**Comment by p2004a** [comment]
@flibitijibibo There is a workaround! We can run the programs that have this problem with environment variable `LIBDECOR_PLUGIN_DIR=null` set, this will cause libdecor to not load any plugin, fallback to no frame at all, no additional surface is created and it prevents apps from crashing.

Not a perfect workaround because you lose window decorations, but window is still usable without them with some keyboard shortcuts + a lot of games run in fullscreen where decorations are not visible anyway, so I will take it any day over just crashing application ;).

**Comment by flibitijibibo** [comment]
Just so nobody has to jump around issues to find it, here's the libwayland patch that will resolve this:

https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/188

**Comment by flibitijibibo** [comment]
#6213 may possibly help with this on our end, depends on whether or not reconnects will help us recover from broken pipe errors (seems unlikely, but who knows).

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
