### ISSUE TITLE
[2.0.22 Regression] Wayland: mouse can exit window in the fullscreen mode.

### ISSUE THREAD

**Issue by p2004a** [libsdl-org/SDL#5539]
The commit 4d76c9cb46491064b1817bd69f78d59783546ee5 (I did git bisect to identify it) introduced regression in version 2.0.22 when if the window is in the fullscreen mode, and user will move mouse to the bottom or right edge of the screen (left and top is fine), the mouse will leave the window.

Here is the recording of bug: https://vimeo.com/699833312
And example how it can impact game (can't move camera around with mouse): https://vimeo.com/699833326 (the top contains the last SDL event, and then cursor leaves window it's being rendered in center)

cc: @Kontrabant

**Comment by Kontrabant** [comment]
Made an adjustment to the rounding used when scaling pointer coordinates, maybe that will fix it.  If not, it could be a bug in GNOME's Mutter, as we've run into a few upstream bugs related to pointer confinement in the compositor where the confinement regions aren't calculated correctly.
