### ISSUE TITLE
What is this API?

### ISSUE THREAD

**Issue by Sawtaytoes** [libsdl-org/SDL#5545]
1. Just so I understand, is this the library used by Steam Input?
2. Is it an abstraction layer on top of X-Input, D-Input, and the like or does it work at an even lower level?
3. How does this library differentiate between an Xbox controller's Left and Right triggers as they share the same axis in DInput and RawInput?
4. I read somewhere that SDL2 doesn't work with rumble on Xbox controllers when disabling X-Input (which only supports up to 4 controllers). Is that the case anymore?
5. Does this library support trigger rumble on the Xbox One controllers?
6. If you want to support more than 4 controllers, is there anything special that needs to be done?

**Comment by slouken** [comment]
This is probably better asked on the SDL [forums ](https://discourse.libsdl.org/), but here you go:

> 1. Just so I understand, is this the library used by Steam Input?

Yes.

> 2. Is it an abstraction layer on top of X-Input, D-Input, and the like or does it work at an even lower level?

Yes, it's an abstraction over the normal platform controller APIs.

> 3. How does this library differentiate between an Xbox controller's Left and Right triggers as they share the same axis in DInput and RawInput?

It tries to correlate raw devices with XInput and WGI devices and uses XInput or WGI for trigger data when available.

> 4. I read somewhere that SDL2 doesn't work with rumble on Xbox controllers when disabling X-Input (which only supports up to 4 controllers). Is that the case anymore?

No, if SDL is able to correlate with WGI devices, it's able to rumble using that API.

> 5. Does this library support trigger rumble on the Xbox One controllers?

Yes, if SDL is able to correlate with WGI devices, it's able to rumble triggers using that API.

> 6. If you want to support more than 4 controllers, is there anything special that needs to be done?

No, the default build of SDL has support for more than 4 controllers.
