### ISSUE TITLE
SDL_SetWindowSize limits to desktop resolution, SDL_CreateWindow doesn't.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5548]
> Oh, interesting...SDL_CreateWindow() will let you make a window larger than the desktop, but SDL_SetWindowSize won't.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3871#issuecomment-1092427167_

This was on X11, don't know if that matters yet.

Decide which of these two API calls is correct.

**Comment by slouken** [comment]
I think originally both calls limited window size to desktop resolution, and we removed this limitation in CreateWindow but forgot SetWindowSize. I think there might be some tap dancing needed to make that work on all platforms.

**Comment by icculus** [comment]
This is an X11 window manager issue; they're actively preventing windows from being sized/moved off the desktop programmatically (even though a user can drag one as such). I'm not sure if this is intentional or not on their part, but it's not an SDL bug, or something we can control.
