### ISSUE TITLE
hidapi: Add support for Nintendo Switch Online controllers

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#5551]
Discovered after getting my hands on these recently: Neither SDL nor the kernel support these yet!

Custom kernel patches that cover NES/SNES, for reference:

https://github.com/nadiaholmquist/linux/commit/bdf4626b45eb631b61a55817dcf789f81f9bddb0
https://github.com/nadiaholmquist/linux/commit/21a824e0ac94b0e8453027ea22579e2d2f109ae3

Haven't gotten the N64 controller yet, nor have I seen any RE info for it.

**Comment by slouken** [comment]
Added support for Nintendo Switch Online controllers in https://github.com/libsdl-org/SDL/commit/68544be44bfa26d65726c74bd01c6fc79f4641f1.
