### ISSUE TITLE
Hint to prefer HIDAPI over MFI controllers

### ISSUE THREAD

**Issue by tellowkrinkle** [libsdl-org/SDL#5553]
Sometimes the HIDAPI driver works better than the MFI one, e.g. the Switch controller's MFI driver doesn't support rumble, while HIDAPI does.

In #4402 the possibility of other priorities seems to have been considered, but it doesn't look like any have been implemented yet.

**Comment by cgutman** [comment]
HIDAPI should be preferred over MFI as of https://github.com/libsdl-org/SDL/commit/c3ca3445bd43292f5f35058d86a64782ad03a286
