### ISSUE TITLE
Does not build with --disable-events and --disable-joystick

### ISSUE THREAD

**Issue by AMDmi3** [libsdl-org/SDL#5560]
FreeBSD port of SDL2 has options to disable each subsystem, I've developed an utility to test them all and have discovered some failures (sdl version is `2.0.20`).

--disable-events:
```
/work/usr/ports/devel/sdl20/work/SDL2-2.0.20/src/joystick/SDL_joystick.c:2768:13: error: use of undeclared identifier 'event_type'
        if (event_type != SDL_CONTROLLERTOUCHPADUP) {
            ^
1 error generated.
```
Full log: https://gist.github.com/04ec7c3efd275fb375a7a6c21224fe32

--disable-joystick:
```
ld: error: undefined symbol: test_bit
>>> referenced by SDL_syshaptic.c
>>>               build/.libs/SDL_syshaptic.o:(SDL_SYS_HapticMouse)
>>> referenced by SDL_syshaptic.c
>>>               build/.libs/SDL_syshaptic.o:(EV_IsHaptic)
>>> referenced by SDL_syshaptic.c
>>>               build/.libs/SDL_syshaptic.o:(EV_IsHaptic)
>>> referenced 12 more times
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
Full log: https://gist.github.com/1125f931440127e15a56b2fc2b5f7f18

**Comment by icculus** [comment]
These are likely small fixes, but for SDL3, I think we need to remove the subsystem-disabling build flags, because it's silly to have to fix bugs when _the event subsystem_ has been removed.

**Comment by slouken** [comment]
I'm going to go ahead and close this issue. Haptics and joysticks are closely tied, and if you disable joystick you should disable haptics as well. I don't think we need to prioritize additional work here.
