### ISSUE TITLE
Exception thrown at 0x00000000 with SDL_Init(SDL_INIT_GAMECONTROLLER) in Win32 VS2022

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#5563]
Latest 2.0.22 pre-release causes this error on init. No special test case needed, it just fails right out of the box.

**Comment by slouken** [comment]
Call stack?

**Comment by AntTheAlchemist** [comment]
When I compile the DLL with debug, it doesn't crash. Without debug it crashes, but there's no call stack. The code calls a null pointer, it seems.

**Comment by AntTheAlchemist** [comment]
It also crashes with the DLL from https://www.libsdl.org/tmp/download-2.0.php

**Comment by cgutman** [comment]
We had the wrong calling convention on a couple functions, so it trashed the stack upon return on x86 builds.
