### ISSUE TITLE
2.0.22 Win32 Rumble feature broken (due to a recent change)

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#5565]
Rumble was working fine in 2.0.20, so a recent change has broken something. Triggers now don't function at all on any controller and rumble only sometimes work, causing a "Controller isn't correlated yet, try hitting a button first" error, even after mashing buttons.

**Comment by AntTheAlchemist** [comment]
Ok, I can't reproduce the shoulder rumble thing - it must have been a fluke. However, no controllers are reporting trigger function when they did before.

**Comment by AntTheAlchemist** [comment]
Sort-of fixed. I was pressing the trigger axis to correlate, and they don't correlate, but the other axis do, so that was a little confusing when testing. Trigger axis are a special case? The trigger rumble doesn't generate the no-correlation error like the shoulder rumble does, if I'm being pedantic.

So it's looking like it's fixed apart from the picky bits above.

**Comment by slouken** [comment]
Yeah, we can't use the trigger axis to correlate, because that axis itself needs correlation.

Thanks!
