### ISSUE TITLE
SDL_RenderClear() memory leak

### ISSUE THREAD

**Issue by h-s-d** [libsdl-org/SDL#5567]
The following code causes a memory leak which quickly locks up and crashes my machine. Occurs with both SDL 2.0.14 and SDL 2.0.20.
```
#define SDL_MAIN_HANDLED 1

#include "SDL.h"

int main(int argc, char* argv[]) {
	int sdl_init = SDL_Init(SDL_INIT_TIMER | SDL_INIT_VIDEO | SDL_INIT_EVENTS);
	
	SDL_Window *sdl_window = SDL_CreateWindow("2022-04-22", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 600, SDL_WINDOW_ALLOW_HIGHDPI);
	
	SDL_Renderer *sdl_renderer = SDL_CreateRenderer(sdl_window, -1, SDL_RENDERER_ACCELERATED);
	
	int quit = 0;
	while (!quit) {
		SDL_RenderClear(sdl_renderer);
	}
	
	SDL_DestroyWindow(sdl_window);
	SDL_Quit();
	
	return 0;
}
```

**Comment by 0x1F9F1** [comment]
You need to call SDL_RenderPresent at the end of each frame (loop iteration), otherwise nothing is actually rendered.

The "leak" is happening because, by default, SDL batches up render commands and then executes them during SDL_RenderPresent (or SDL_RenderFlush).

**Comment by h-s-d** [comment]
Very helpful, thank you.
