### ISSUE TITLE
How to change the window background

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#5574]
I want to change window color before SDL_CreateRenderer
```c
wind = SDL_CreateWindow("TEST", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, SDL_WINDOW_SHOWN);
windSurface = SDL_GetWindowSurface(wind);  
SDL_FillRect(windSurface, NULL, SDL_MapRGB(windSurface->format, 240, 200, 112));
SDL_UpdateWindowSurface(wind);
SDL_CreateRenderer
```
It works, but how can I destroy the windSurface

It belongs to SDL_DONTFREE
https://github.com/libsdl-org/SDL/blob/e9ff4fdd49f4be77ebfa45e8a4f300cc2e8f5f23/src/video/SDL_video.c#L2577

**Comment by slouken** [comment]
This isn't a bug, please ask this on the discussion group:
https://discourse.libsdl.org/c/sdl-development/6
