### ISSUE TITLE
SDL_SetCursor not working (auto-capture issue?)

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5577]
Mentioned here:

https://discourse.libsdl.org/t/sdl-2-0-22-prerelease/35306/19

>There’s a regression of some sort in respect of SDL_SetCursor(). With 2.0.20 my app is changing the cursor shape as I move the mouse over different areas, as it should, but with 2.0.22 it’s not changing. I suspect this is related to a change in the mouse capture behavior (is it possible that when the mouse is captured the cursor shape is locked?).
>
> Edit: If I click the mouse in SDL’s window and then move it over the title bar the cursor shape is not changing back to the pointer as it should, it’s stuck in the shape I selected. This definitely looks to be related to the change in capture behavior.

Reproduction case from that thread:

> It’s the Windows edition that shows the problem here, here’s the [download link](https://www.bbcbasic.co.uk/bbcsdl/bbcsdl20.zip). Extract the contents of the zip to an empty directory, replace the supplied SDL2.dll (which is 2.0.20) with the 32-bit 2.0.22 and run bbcsdl.exe.
>
>You will initially be presented with a choice of IDE, you should select SDLIDE from the options given. Now try moving the mouse around: the cursor will change from an I-beam over the editing pane to an arrow over the toolbar.
>
>To repro the issue click in the editing pane (which I assume will cause the mouse to be captured in 2.0.22) and repeat the movement: now you should find that it doesn’t change shape even when over the title bar.

**Comment by icculus** [comment]
Video of issue:


https://user-images.githubusercontent.com/673562/165367536-a0eb2621-4c94-4fb3-9030-decee6615e1b.mp4

**Comment by slouken** [comment]
It sounds like for your application you don't want the auto capture behavior.

You can disable it with:
```c
SDL_SetHint(SDL_HINT_MOUSE_AUTO_CAPTURE, "0");
```

**Comment by icculus** [comment]
> It sounds like for your application you don't want the auto capture behavior.

Are you sure? This sounds like a legit bug, but I haven't looked further than pasting it in here.

**Comment by slouken** [comment]
> On the contrary, auto capture behavior would be great (I’m used to having it in native Windows apps) and is helpful in tracking mouse movements beyond the edge of the window. Currently (with 2.0.20) I have to tell my users that this doesn’t work.

> I just want to be able to change the cursor shape as the mouse moves, which should (surely?) be independent of the capture behavior.

**Comment by slouken** [comment]
FWIW, if you take Visual Studio or Microsoft Edge, click in the window and drag out, you'll get the same behavior. The close button doesn't highlight and the cursor doesn't change to the resize cursor because the mouse is captured by the app. I think this is correct application behavior on Windows.

**Comment by slouken** [comment]
> I just want to be able to change the cursor shape as the mouse moves, which should (surely?) be independent of the capture behavior.

I modified testcustomcursor.c to change cursors on a keystroke, and I'm able to hold the mouse button down and still change cursors, so it does seem to be independent of capture behavior. I'll take a look at your application.

**Comment by slouken** [comment]
Git bisect points at 86acb1a347fb232f0211864fe00af2d7590a3717 as the culprit here. I'm investigating...

**Comment by slouken** [comment]
Okay, I figured out the problem. The mouse is being captured on the main thread because of mouse input, but the application is calling `SDL_CaptureMouse(SDL_FALSE)` on a different thread. SDL proceeds to release the capture and updates state appropriately, but since Windows capture state is on a per-thread basis, the capture is still active on the main thread.

**Comment by rtrussell** [comment]
>  the application is calling SDL_CaptureMouse(SDL_FALSE) on a different thread.

My application never calls `SDL_CaptureMouse()`, but it does call `SDL_SetCursor()` from a non-main thread, is that what you are referring to?   That has not given problems previously.

**Comment by rtrussell** [comment]
Right, if I call `SDL_CaptureMouse()` from the main thread it does seem to fix the problem (although with the auto-capture behavior I don't need to call it at all, so I could alternatively omit the call entirely with SDL 2.0.22 or later).

**Comment by slouken** [comment]
> I could alternatively omit the call entirely with SDL 2.0.22 or later

I'm going to return an error if the call isn't made on the main thread so this doesn't bite other people, but for your use case that's probably the best solution.
