### ISSUE TITLE
X11: SDL_HideWindow and/or SDL_ShowWindow broken in 2.0.22

### ISSUE THREAD

**Issue by complexlogic** [libsdl-org/SDL#5595]
This is possibly related to #5572, but I'm going to make a separate issue just in case.

I'm on Arch Linux, and recently upgraded SDL to 2.0.22. My program [Flex Launcher](https://github.com/complexlogic/flex-launcher) uses SDL to render 2D graphics. Basically, it's a full screen application launcher that hides its window while the launched application is running, and then shows itself again after the application finishes. It uses the functions `SDL_HideWindow()` and `SDL_ShowWindow()` to accomplish this.

However, since I upgraded SDL, I noticed that after the application finishes and `SDL_ShowWindow()` is called, the resulting window is just completely blank (when it should have the rendered graphics). I verified this issue on two different Arch Linux PCs, one with a KDE Plasma desktop, one with Openbox (both X11). 

I downgraded SDL to 2.0.20 and it fixed the issue on both PCs. Therefore, I believe one of the recent commits is causing the issue.

**Comment by ubitux** [comment]
Can be reproduced with various tools such `ffplay` (video player test from FFmpeg project) is one of them (`f` for fullscreen).

**Comment by icculus** [comment]
@complexlogic Can you see if 9edd411a8315540b86fceec590dd5aa6be41f5f0 (the latest in main) fixes it for you?

**Comment by complexlogic** [comment]
I built `main` at the referenced commit, tested, and everything is working as it was before. Thanks.
