### ISSUE TITLE
X11: Short black screen on surface creation/destruction

### ISSUE THREAD

**Issue by alexdesaint** [libsdl-org/SDL#5613]
### Bug description

`SDL_GetWindowSurface` and then `SDL_DestroyWindow` trigger a short (less that a second) black screen on my desktop and is corrupting Firefox windows surface until I click on it. 

Only on X11 not on Wayland.

I am not sure if it is a X11, mesa, KDE or SDL2 problem but I am only experiencing this bug with SDL2 app compiled by me so I am posting here.
I believe I have other SDL app on my desktop that don't have this problem (Blender and Stream games...).

### SDL  tested version

- The system package SDL `2.0.22-1`
- The last main commit `a4594797695b4d16137d4958455a115bcda84288 (HEAD -> main, origin/main, origin/HEAD)`

### How to reproduce
```C++
#include <SDL2/SDL.h>
#include <iostream>

int main(int argc, char *args[]) {
    SDL_Init(SDL_INIT_VIDEO);
    std::cout << "error: " << SDL_GetError() << std::endl;

    SDL_Window *window = SDL_CreateWindow("sdl2 test",
                                          SDL_WINDOWPOS_UNDEFINED,
                                          SDL_WINDOWPOS_UNDEFINED,
                                          640,
                                          480,
                                          0);
    std::cout << window << " error: " << SDL_GetError() << std::endl;

    SDL_Delay(2000);

    std::cout << "Flickering 1" << std::endl;
    SDL_Surface *screenSurface = SDL_GetWindowSurface(window); // <----------------------
    std::cout << screenSurface << " error: " << SDL_GetError() << std::endl;

    SDL_Delay(2000);

    std::cout << "Flickering 2" << std::endl;
    SDL_DestroyWindow(window); // <----------------------
    std::cout << "error: " << SDL_GetError() << std::endl;

    SDL_Delay(2000);

    SDL_Quit();
    std::cout << "error: " << SDL_GetError() << std::endl;
    return 0;
}
```
Output:
```
error: 
0x55615b5ef190 error: 
Flickering 1
0x55615bf56160 error: 
Flickering 2
error: 
error: 
```

### My system
```
Operating System: Arch Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.17.5-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900 12-Core Processor
Memory: 15,6 GiB of RAM
Graphics Processor: AMD Radeon RX 480 Graphics
```

**Comment by icculus** [comment]
If it's corrupting a window from another process (Firefox in this case, which is likely using OpenGL to render to the screen), then this is a GPU driver bug (or at least an X server bug), not an SDL bug.

SDL_GetWindowSurface() will very likely decide to create an OpenGL context on X11, as the most efficient way to render pixels to the screen, which is where this probably upsets the GPU driver.

I just noticed we (rather, I) introduced a bug into 2.0.22 that makes it so you _can't_ disable using an OpenGL context in SDL_GetWindowSurface with a hint. I'll fix that in #5671.
