### ISSUE TITLE
[Request] Public API of SDL_LIST

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#5624]
https://github.com/libsdl-org/SDL/blob/main/src/SDL_list.h

**Comment by slouken** [comment]
That really isn't polished enough for external use. It's completely self-contained, so you're welcome to grab the source and use it in your project (keeping the license at the top of the files intact)

Tagging @icculus in case he has a different opinion.

**Comment by icculus** [comment]
Yeah, this doesn't need to be public, unless there was something really compelling about it vs other linked list implementations.
