### ISSUE TITLE
[SDL3] Simplify versioning

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#5626]
SDL 2 has some technical debt in its versioning scheme that was not possible to fix as part of #5217 without breaking backwards compatibility. When backwards compatibility is broken *anyway* for SDL 3, it would be good to clean this up:

CMake: if the next backwards-compatibility break after SDL 3 will be SDL 4, then stop overriding the `OUTPUT_NAME` to `SDL2-${LT_RELEASE}`, letting it default to `SDL3`, so that the library name is simplified from `libSDL2-2.0.so.0` to `libSDL3.so.0`. Then `LT_RELEASE` can be removed.

Autotools: if the Autotools build system is not deleted entirely, then remove `-release ${LT_RELEASE}`, so that the library name is simplified from `libSDL2-2.0.so.0` to `libSDL3.so.0`.

CMake: stop setting up the version via `SDL_BINARY_AGE`, `SDL_INTERFACE_AGE` and various `LT_` intermediate variables (their name comes from Libtool, which is not used in the CMake build). Instead do something like this (untested) which is probably clearer:

```
# Increment this if there is an incompatible change - but if that happens,
# we should rename the library from SDL3 to SDL4, at which point this would
# reset to 0 anyway.
set(ABI_MAJOR_VERSION 0)

if(SDL_MINOR_VERSION MATCHES "[02468]$")
    # Stable branch, 3.2.1 -> libSDL3.so.0.200.1
    math(EXPR ABI_MINOR_VERSION "${SDL_MINOR_VERSION} * 100")
    set(ABI_MICRO_VERSION "${SDL_MICRO_VERSION}")
else()
    # Development branch, 3.5.7 -> libSDL3.so.0.507.0
    math(EXPR ABI_MINOR_VERSION "${SDL_MINOR_VERSION} * 100 + ${SDL_MICRO_VERSION}")
    set(ABI_MICRO_VERSION "0")
endif()

...

set_target_properties(SDL3 PROPERTIES
    VERSION ${ABI_MAJOR_VERSION}.${ABI_MINOR_VERSION}.${ABI_MICRO_VERSION}
    SOVERSION ${ABI_MAJOR_VERSION})
```

Autotools: if the Autotools build system is not deleted entirely, then stop using `-version-info`; instead, calculate the ABI major/minor/micro version similar to the CMake code above, and pass it to the `-version-number` option, which acts like a combination of CMake's `SOVERSION` and `VERSION`.

**Comment by smcv** [comment]
Or the ABI version in SDL3 could even be simplified down to `0.${SDL_MINOR_VERSION}.${SDL_MICRO_VERSION}` if you don't care about obscure proprietary Unixes from the 1990s.

**Comment by madebr** [comment]
I like the simple version scheme.

```cmake
set(SDL_LIB_SOVERSION "0")
set(SDL_LIB_VERSION "${SDL_LIB_SOVERSION}.${SDL_VERSION_MINOR}.${SDL_VERSION_PATCH}")
```

Resulting in the following files (assuming version 3.0.0):
```
libSDL3.a
libSDL3.so -> libSDL3.so.0
libSDL3.so.0 -> libSDL3.so.0.0.0
libSDL3.so.0.0.0
```

**Comment by slouken** [comment]
> > Or the ABI version in SDL3 could even be simplified down to 0.${SDL_MINOR_VERSION}.${SDL_MICRO_VERSION} if you don't care about obscure proprietary Unixes from the 1990s
> 
> This only works if there are not going to be any alpha/beta versions of SDL 3 versioned 2.99.x (which is what GTK does for their major-version breaks). @slouken, did we decide that the alpha/beta versions were going to be 3.1.x, with 3.2.x as the first stable release, bypassing 3.0 completely?

Yes, we did.

**Comment by slouken** [comment]
I believe this is done. @smcv, is there anything remaining here?

**Comment by madebr** [comment]
On Macos, only SOVERSION is set, as did autotools.
Is the non-usage of VERSION intentional?

**Comment by sezero** [comment]
> On Macos, only SOVERSION is set, as did autotools. Is the non-usage of VERSION intentional?

BTW: In commit f6c9b06562009, we had added a note to remove SOVERSION when
targeting macOS. Reference issues / commits:
https://github.com/libsdl-org/sdl12-compat/issues/217
https://github.com/libsdl-org/sdl12-compat/commit/bf91f6aad1fce952a3c11dc6ace155a2d1f428b8

**Comment by smcv** [comment]
> On Macos, only SOVERSION is set, as did autotools.
> Is the non-usage of VERSION intentional?

Sorry, I haven't run macOS for about 20 years and I never developed for it, so I don't know what's desirable there. The important thing is that the library name is `(lib)SDL3`, the "major ABI version" is 0, and the "minor ABI version" goes up with each new SDL release.

If it can be the same CMake source code as Linux (with CMake doing the right thing behind the scenes, like presumably using `.dylib` instead of `.so`) then that would be great: the fewer code paths we need, the better.

Or, if people with macOS knowledge have a reason why it needs to be different, then I'm fine with it being different - but preferably with either a comment or an issue report reference to say *why* it needs to be different.

**Comment by smcv** [comment]
> I believe this is done. @smcv, is there anything remaining here?

Did we want to do https://github.com/libsdl-org/SDL/issues/5626#issuecomment-1119526069, so for example SDL version 3.23.5 would have a symlink `libSDL3.so.0 -> libSDL3.so.0.23.5` on Linux? If we want that, now is the time.

**Comment by smcv** [comment]
> what changes need to happen in CMake to change the symlink format?

Something like this

* Set the `VERSION` property to `${LT_MAJOR}.${SDL_MINOR_VERSION}.${SDL_MICRO_VERSION}`
* (optional) Rename `${LT_MAJOR}` to `${SOVERSION}` or `${ABI_MAJOR_VERSION}` or something, since the `LT` stands for libtool, which we no longer use since the Autotools build was deleted
* (optional) Simplify how we compute the macOS (dylib) ABI versioning
* (optional) Remove `SDL_BINARY_AGE`, `SDL_INTERFACE_AGE`, `LT_AGE`, `LT_CURRENT`, `LT_REVISION`, `LT_VERSION`, except where needed to support what's left of the dylib ABI versioning

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/blob/fc4fc5295fa7b3c4eb1a1c73711d9b30504d129d/CMakeLists.txt#L3260-L3262

The value of `VERSION` should become: `${LT_MAJOR}.${SDL_VERSION}`

**Comment by madebr** [comment]
@slouken 
Can we simplify the versioning for the dylibs as well?

https://github.com/libsdl-org/SDL/blob/7e7a8e76a58bb0a91a16e0e64a4e1aa84e9b1278/Xcode/SDL/SDL.xcodeproj/project.pbxproj#L9280-L9281

How will this increment for minor SDL3 releases/patch releases?

**Comment by slouken** [comment]
We shouldn't touch the Xcode projects. Those versions are embedded in the library and used as hints to determine whether an application is compatible with that library. The logic for changing them is in build-scripts/test-versioning.sh:
```sh
dylib_cur=$(sed -Ene 's/.*DYLIB_CURRENT_VERSION = (.*);$/\1/p' Xcode/SDL/SDL.xcodeproj/project.pbxproj)

case "$ref_minor" in
    (*[02468])
        major="$(( ref_minor * 100 + 1 ))"
        minor="$ref_micro"
        ;;
    (*)
        major="$(( ref_minor * 100 + ref_micro + 1 ))"
        minor="0"
        ;;
esac

ref="${major}.${minor}.0
${major}.${minor}.0
${major}.${minor}.0
${major}.${minor}.0"
```

**Comment by slouken** [comment]
@madebr I can test your changes on macOS to make sure the dylib filename looks good here.

**Comment by madebr** [comment]
See #6705

**Comment by slouken** [comment]
This ended up being wrong. libSDL3.so is a symlink to libSDL3.so.0.23.5 instead of libSDL3.so.0, and libSDL3.so.23.5 is a symlink to libSDL3.so.0 instead of vice versa.

**Comment by slouken** [comment]
Flipping VERSION and SOVERSION gave the correct result, but I don't know if you want to change variable names or anything.

**Comment by madebr** [comment]
I switched the use of the variables at `set_target_properties`.

**Comment by slouken** [comment]
Yup, looks great, thanks!
