### ISSUE TITLE
Create git submodules for third party dependencies

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#5631]
Right now we track external dependencies as code checked into the SDL_* libraries with .patch files with SDL specific changes to those packages. Those are cumbersome to maintain (some of the .patch files are out of date) and time consuming to update when upstream changes occur or we want to pull in CVE fixes and other improvements.

I propose that we fork the upstream projects into libsdl-org (or create repositories for those projects not already in git) and use git submodules to include those dependencies into SDL libraries. This would largely affect SDL_image and SDL_mixer, but could be used anywhere we depend on third party libraries.

The documentation for git submodules is here:
https://git-scm.com/book/en/v2/Git-Tools-Submodules

It looks like the work flow is greatly complicated by using git submodules, and it's easy to forget the various steps needed to use  them properly if the submodule options aren't already in the git config.

@smcv, do you have thoughts on the pros and cons of this approach?

@icculus, @1bsyl, @sezero, what are your thoughts?

**Comment by sezero** [comment]
gitsubmodules will likely cause a lot of pain. IMO, forking and customizing as we see fit should do.

**Comment by sezero** [comment]
Taking your newly created https://github.com/libsdl-org/jpeg repo as example: we should have a `vendor` branch where we will continuously pull in new versions (or in case of libraries with git repos we continuosly sync with their master), and then we can have `<version>-SDL` branches, like `9d-SDL`, `9e-SDL`, etc, where we apply customizations or fixes or whatever for our own use.

**Comment by slouken** [comment]
Yep, that sounds like a good plan.

**Comment by slouken** [comment]
I've set up libsdl-org/jpeg, which is an import of the official 9e release, added the v9e and v9e-SDL branches, and added our Android support to the v9e-SDL branch.
I've set up libsdl-org/libpng as a clone of the official github repo, branched v1.6.37 into v1.6.37-SDL, added our Android support, cherry picked an exif fix, and added an additional exif fix that we have in SDL_image.

How does this look?

**Comment by sezero** [comment]
Looks good to me, so far

**Comment by sezero** [comment]
Speaking of SDL-specific commits in those two, namely Android stuff:
Is it not possible to not pollute the top-level directory with Android-
specific config files, e.g. pnglibconf.h in libpng and jconfig.h in
libjpeg?

**Comment by slouken** [comment]
Yes, that would be awesome. For this initial state, I wanted to mirror what we currently have. We can do any improvements we want on the SDL branch.

**Comment by sezero** [comment]
I'm readying libtiff - shall I create it?

**Comment by slouken** [comment]
No, I've got it. I'm adding all the dependencies for SDL_image. Thanks!

**Comment by sezero** [comment]
libtiff in SDL_image is still in 4.2.0 (no reason for upgrading to 4.3.0), so I made a
v4.2.0-SDL branch and added our updates to it.

**Comment by slouken** [comment]
> libtiff in SDL_image is still in 4.2.0 (no reason for upgrading to 4.3.0), so I made a v4.2.0-SDL branch and added our updates to it.

Also no reason not to upgrade, right?

**Comment by sezero** [comment]
> Also no reason not to upgrade, right?

I guess not, but you should apply the CVE fixes from debian to it (v4.2.0-SDL already has them.)

**Comment by slouken** [comment]
> > Also no reason not to upgrade, right?
> 
> I guess not, but you should apply the CVE fixes from debian to it (v4.2.0-SDL already has them.)

We can switch back to v4.2.0, that's fine.

**Comment by sezero** [comment]
> We can switch back to v4.2.0, that's fine.

Done.

**Comment by slouken** [comment]
For platform specific config headers, like Android, etc., let's have the convention where we add config/<platform>/config.h and add that path to the include path for that platform, in the SDL branch for the library. That way we can have pregenerated config headers that don't conflict with autotools builds.

I'm going to make that change for harfbuzz when building with Xcode.

**Comment by sezero** [comment]
I had made a solution for harfbuzz, but it may be insufficient as it is.

**Comment by slouken** [comment]
> I had made a solution for harfbuzz, but it may be insufficient as it is.

I'll check in as-is then, and do you want to re-add your harfbuzz solution on the branch?

**Comment by sezero** [comment]
Well, my solution consisted of the following three files, feel free
to add them to branch (hopefully not too many changes will be needed
for going from 2.8.0 to 2.8.2):
https://github.com/libsdl-org/SDL_ttf/blob/0c6f2193430d5d47e08a063f77a350dd8b57df15/external/harfbuzz-2.8.0/config.h
https://github.com/libsdl-org/SDL_ttf/blob/0c6f2193430d5d47e08a063f77a350dd8b57df15/external/harfbuzz-2.8.0/config_sdl_win32.h
https://github.com/libsdl-org/SDL_ttf/blob/0c6f2193430d5d47e08a063f77a350dd8b57df15/external/harfbuzz-2.8.0/config_sdl_unix.h

**Comment by slouken** [comment]
> Well, my solution consisted of the following three files, feel free to add them to branch (hopefully not too many changes will be needed for going from 2.8.0 to 2.8.2): https://github.com/libsdl-org/SDL_ttf/blob/0c6f2193430d5d47e08a063f77a350dd8b57df15/external/harfbuzz-2.8.0/config.h https://github.com/libsdl-org/SDL_ttf/blob/0c6f2193430d5d47e08a063f77a350dd8b57df15/external/harfbuzz-2.8.0/config_sdl_win32.h https://github.com/libsdl-org/SDL_ttf/blob/0c6f2193430d5d47e08a063f77a350dd8b57df15/external/harfbuzz-2.8.0/config_sdl_unix.h

Go for it!

**Comment by sezero** [comment]
> Go for it!

Done.

You probably want to add Android.mk to harfbuzz too, if you haven't done so already
(I won't do that one.)

**Comment by sezero** [comment]
Added three additional patches to 1.3.5-SDL branch of ogg (mainstream PR/72, 73 and 75.)

**Comment by sezero** [comment]
libmodplug will be a problem: you'll probably want mainstream master branch, with additional PR patches and some additionals from my fork in the SDL branch.

**Comment by slouken** [comment]
Okay.

I noticed that libogg-1.3.2/0010-optflags.patch doesn't apply because the configure files aren't generated. Do you want to add autogenerated files to git, or apply that patch to configure.ac?

**Comment by sezero** [comment]
> I noticed that libogg-1.3.2/0010-optflags.patch doesn't apply

Not needed in the new version.

BTW, `make dist` will be a problem. Well need some dist-hook or something.
Even with that, the generated release tarballs will probably be larger because
the original projects most possibly exclude stuff from dist.

**Comment by sezero** [comment]
I fixed SDL_ttf build: `$(FREETYPE_PATH)/src/svg/svg.c` needed adding to freetype sources:
https://github.com/libsdl-org/SDL_ttf/commit/399973f09e742eacc37a9a905d29f5ca24b85ec2
Visual Studio and Xcode sides need your attention for it.

**Comment by slouken** [comment]
> libmodplug will be a problem: you'll probably want mainstream master branch, with additional PR patches and some additionals from my fork in the SDL branch.

I just forked your repo. Let me know if you'd rather I fork the upstream repo.

**Comment by sezero** [comment]
> > libmodplug will be a problem: you'll probably want mainstream master branch, with additional PR patches and some additionals from my fork in the SDL branch.
> 
> I just forked your repo. Let me know if you'd rather I fork the upstream repo.

Well, I'm flattered :)

Just remove a new api addition from the SDL branch (it's a PR yet and Konstanty
hasn't yet applied it), and it should be good to go: [patch.txt](https://github.com/libsdl-org/SDL/files/8646035/patch.txt)
(it refuses me committing to it, so I can't do it myself.)

**Comment by slouken** [comment]
You should have commit access now, go for it.

**Comment by slouken** [comment]
What do you recommend for mpg123? Should I fork your repo and use branch sezero-1.22.x?

**Comment by sezero** [comment]
> You should have commit access now, go for it.

Done.

**Comment by sezero** [comment]
> What do you recommend for mpg123? Should I fork your repo and use branch sezero-1.22.x?

mpg123 is a problem. It has svn2git mirrors but only for trunk and
even in the original svn the branches are a mess with git's point of
view, i.e. you can't pinpoint a commit to a release version. My fork
follows mainstream svn trunk, so not for public consumption.
The sezero-1.22.x fork there is a personal simplification of the old
1.22.4 version with only libmpg123 and it being _almost_ fully updated,
so using it will be going back a few versions somehow (SDL-1.2 branch
uses that one though for simplicity.)

The version in current SDL_mixer is [1.25.15](http://mpg123.org/download/mpg123-1.25.15.tar.bz2) with two or three
updates applied to it.

My recommendation is making a vendor branch and adding to it
whenever mainstream makes a release and then branching from a
selected one for our use.

**Comment by slouken** [comment]
Okay, I'll do the same thing I did for jpeg then.

Thanks!

**Comment by sezero** [comment]
> Okay, I'll do the same thing I did for jpeg then.

Okay -- if you are going to use 1.25.15, then these are the additional
commits I use: (ignore any changes to autofoo stuff in them)
https://github.com/libsdl-org/SDL_mixer/commit/887fdadb74bf0883b040446c892761cc1fe08a23
https://github.com/libsdl-org/SDL_mixer/commit/47dceba8f2f63b65a8c3ce6a3a5e772bbe65baa7
https://github.com/libsdl-org/SDL_mixer/commit/7aac1020eb2dfa7539b2ab1138b3f18290920d6e

**Comment by slouken** [comment]
> 1.25.15

I updated to 1.29.3

**Comment by slouken** [comment]
Okay, so SDL_ttf, SDL_image, and SDL_mixer have all been updated to use submodules, and in the process the latest versions of all dependencies.

Let the build fixing commence! :)

**Comment by slouken** [comment]
For future reference, each dependency is pinned to a specific commit in the SDL branch for that dependency.

If you want to make changes in those dependencies, check out the vX.Y.Z-SDL branch of that dependency, make the change, commit and push normally. Then in the SDL_* library, you need to do `git submodule update --remote` to update the SDL library to the latest dependency commit, and then commit and push that change.

**Comment by slouken** [comment]
For convenience, you should add the following to your `.git/config` file:
```
[submodule]
    recurse = true
```

**Comment by sezero** [comment]
> Let the build fixing commence! :)

SDL_ttf: `$(FREETYPE_PATH)/src/svg/svg.c` needed adding to freetype sources:
https://github.com/libsdl-org/SDL_ttf/commit/399973f09e742eacc37a9a905d29f5ca24b85ec2
I did that for autotools, but Visual Studio and Xcode sides need your attention.

**Comment by slouken** [comment]
> SDL_ttf: `$(FREETYPE_PATH)/src/svg/svg.c` needed adding to freetype sources: [libsdl-org/SDL_ttf@399973f](https://github.com/libsdl-org/SDL_ttf/commit/399973f09e742eacc37a9a905d29f5ca24b85ec2) I did that for autotools, but Visual Studio and Xcode sides need your attention.

Done!

**Comment by sezero** [comment]
And there is also the `make dist` issue I noted above. (It's rather late here though, tired.)

**Comment by slouken** [comment]
> And there is also the `make dist` issue I noted above.

Yep, we can tackle that when we get closer to release candidates for these libraries.

**Comment by sezero** [comment]
I added proper disthooks to eliminate unwanted stuff from external/ (at least most of it.)

**Comment by sezero** [comment]
Minor: https://github.com/libsdl-org/libtiff default branch should be `master`, not `branch-3.9`

**Comment by DJm00n** [comment]
`hidapi` should be fork of https://github.com/libusb/hidapi

**Comment by slouken** [comment]
> Minor: https://github.com/libsdl-org/libtiff default branch should be `master`, not `branch-3.9`

Fixed!

**Comment by slouken** [comment]
BTW, when you upgraded to harfbuzz 2.9.1, I needed to manually checkout the new branch in my repo:
```sh
cd external/harfbuzz
git checkout 2.9.1-SDL
```
I'm not sure why git didn't automatically check out the new branch when the .gitmodules was updated.

**Comment by sezero** [comment]
Really I don't know

**Comment by sezero** [comment]
> Really I don't know

That begs the question, though: are the others properly updated?

E.g.:  SDL_image: libtiff should be at v4.2.0-SDL : 
   2e28ca499d375be20509f82fb84dbd810ae330ba

SDL_ttf: freetype should be at: 1926d54b75cef24ba27671f38946e7cb92af3495

**Comment by slouken** [comment]
> That begs the question, though: are the others properly updated?
> 
> E.g.: SDL_image: libtiff should be at v4.2.0-SDL : 2e28ca499d375be20509f82fb84dbd810ae330ba
> 
> SDL_ttf: freetype should be at: 1926d54b75cef24ba27671f38946e7cb92af3495

FreeType was updated correctly. I needed to check out the 4.2.0 branch for libtiff and then it was updated properly.

@smcv, is there something we should be doing to have git automatically switch branches when .gitmodules is updated?

**Comment by sezero** [comment]
SDL_image: `libjxl` appears only in `.gitmodules` file but is not present,
perhaps not properly added by a `git submodule add` command? (Or, was
that intentional to not add it yet?)

**Comment by sezero** [comment]
> SDL_image: `libjxl` appears only in `.gitmodules` file but is not present, perhaps not properly added by a `git submodule add` command? (Or, was that intentional to not add it yet?)

In any case, it's somehow good that the submodule isn't truly added to the SDL_image repo:
The 0.6.1 gzipped source tarball alone is 16 MB and that's without its lots of dependencies.
If you add it, it may need some surgery to and also additional dist-hook rules to eliminate
unwanted cruft.

**Comment by sezero** [comment]
(No, this is not a git submodule, but for us to be in sync with autoconf versions we use)

I have an autoconf fork at https://github.com/sezero/autoconf with a few backports
to v2.69 in '2.69-backports' branch: we already have been using x11 detection patches,
this one includes a few more.

I can add it to repositories under libsdl-org, so everyone can be using the same autoconf
version in our SDL projects. OK?

**Comment by sezero** [comment]
> Any reason we don't all just update to the latest autoconf?

Haven't fully tried ac2.71 - if you did, though, then we can.

**Comment by slouken** [comment]
Yes, let's update to 2.71 instead of using a custom autoconf with backports, so it will be consistent when developers try to recreate configure themselves.

**Comment by slouken** [comment]
I went ahead and deleted our autoconf clone

**Comment by sezero** [comment]
zlib `develop` branch may have a few commits we might be interested in cherry-picking.

**Comment by slouken** [comment]
We should be tracking public releases, not the main branch for most projects. The only exception would be a CVE that is fixed but there won't be a release of that software before our next release.

**Comment by sezero** [comment]
I was talking about build and and some code generation fixes, but as you wish:

- Fix inflateBack to detect invalid input with distances too far.
  https://github.com/libsdl-org/zlib/commit/2333419cd76cb9ae5f15c9b240b16a2052b27691
- Fix odd error in Visual C compiler preventing automatic promotion.
  https://github.com/libsdl-org/zlib/commit/7ecf7c7458578d05a20fa481436dd5c58db112f7

And, _maybe_:
- Fix compile with Windows 10 SDK. (gvollant)
  https://github.com/libsdl-org/zlib/commit/ce12773790517034317274f5c65ba70cfeea29f7
- Fix configure issue that discarded provided CC definition.
  https://github.com/libsdl-org/zlib/commit/05796d3d8d5546cf1b4dfe2cd72ab746afae505d

**Comment by slouken** [comment]
> I was talking about build and and some code generation fixes, but as you wish:
> 
> * Fix inflateBack to detect invalid input with distances too far.
>   [libsdl-org/zlib@2333419](https://github.com/libsdl-org/zlib/commit/2333419cd76cb9ae5f15c9b240b16a2052b27691)
> * Fix odd error in Visual C compiler preventing automatic promotion.
>   [libsdl-org/zlib@7ecf7c7](https://github.com/libsdl-org/zlib/commit/7ecf7c7458578d05a20fa481436dd5c58db112f7)
> 
> And, _maybe_:
> 
> * Fix compile with Windows 10 SDK. (gvollant)
>   [libsdl-org/zlib@ce12773](https://github.com/libsdl-org/zlib/commit/ce12773790517034317274f5c65ba70cfeea29f7)
> * Fix configure issue that discarded provided CC definition.
>   [libsdl-org/zlib@05796d3](https://github.com/libsdl-org/zlib/commit/05796d3d8d5546cf1b4dfe2cd72ab746afae505d)

I leave it to your discretion. We just want to avoid any regressions and so the general policy is to stick to mainline releases.

**Comment by sezero** [comment]
@slouken: Can you please change our [opus fork](https://github.com/libsdl-org/opus)'s default branch to `main`? I don't seem to have permissions for it. (There are both main and master branches, master should stay as is, but mainstream change their default branch.)

**Comment by slouken** [comment]
> @slouken: Can you please change our [opus fork](https://github.com/libsdl-org/opus)'s default branch to `main`? I don't seem to have permissions for it. (There are both main and master branches, master should stay as is, but mainstream change their default branch.)

Done!
