### ISSUE TITLE
Creating PSP EBOOTs fails in parallel builds

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#5634]

**Comment by sharkwouter** [comment]
I've noticed this as well recently. I'm not quite sure how to fix it yet. I'll need to look into it.

**Comment by slouken** [comment]
We are scoping work for the SDL 3.2.0 release, so please let us know if this is a showstopper for you.

**Comment by sharkwouter** [comment]
I've updated the PSPDEV SDK and created the 2 merge requests which solve this issue for both SDL2 and SDL3.
