### ISSUE TITLE
Windows RT/UWP documentation is out of date

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#5639]
The Windows RT project files were previously restructured in PR #4731, however the [README-winrt.md](https://github.com/libsdl-org/SDL/blob/main/docs/README-winrt.md) document, the [relevant section](https://wiki.libsdl.org/Installation#winrtuwpwindows_8windows_10winphone) on the wiki, the [winrtbuild.ps1](https://github.com/libsdl-org/SDL/blob/main/build-scripts/winrtbuild.ps1) build script and the projects for SDL_mixer, SDL_image and SDL_ttf still refer to the old structure.

**Comment by slouken** [comment]
@ccawley2011, is this something you can look at for the 2.24.0 milestone?

**Comment by icculus** [comment]
I removed the wiki stuff in https://github.com/libsdl-org/sdlwiki/commit/d35b43d6828d68cecddda83ac25fdcda8923eaa4.

**Comment by icculus** [comment]
README-winrt.md is updated: https://github.com/libsdl-org/SDL/commit/8695d982d262324c063ae8fd744116870cff8bda

**Comment by icculus** [comment]
Ok, looking at it, I'm thinking winrtbuild.ps1 should be deleted, and then this issue can be closed. Stop me in the next few minutes, before I get to it, if you disagree!

**Comment by icculus** [comment]
You had 22 minutes to stop me!!  :)

Okay, we're good here now, afaik.
