### ISSUE TITLE
Document SDL integration with other UI libs

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#5651]
There were information about SDL compatibility with other UI lib (https://github.com/libsdl-org/SDL/pull/4195)
Not sure where this doc could be added.

Examples here:

Dear ImGUI:
https://github.com/ocornut/imgui/tree/master/examples/example_sdl_sdlrenderer

Nuklear:
https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/sdl_renderer

RmlUI (fork of libRocket):
https://github.com/mikke89/RmlUi/tree/master/Samples/basic/sdl2_sdlrenderer/src

Spine (http://esotericsoftware.com/):
https://github.com/royalstream/spine-sdl

Un-maintained project:

MicroUI:
https://github.com/rxi/microui/pull/48

libRocket:
https://github.com/libRocket/libRocket/pull/301

**Comment by 1bsyl** [comment]
what about there https://wiki.libsdl.org/Libraries ?
Since it's about "Additional libraries to extend SDL functionality. "

**Comment by slouken** [comment]
Sure, that sounds good.

**Comment by 1bsyl** [comment]
https://wiki.libsdl.org/Libraries
