### ISSUE TITLE
Motion events emulation & multitouch gestures for touch events broken as of 2.0.22 on certain devices (X11)

### ISSUE THREAD

**Issue by mil** [libsdl-org/SDL#5652]
As of upgrading to 2.0.22 on certain devices on X11, the emulation of motion events for touch devices is broken. Specifically I'm testing on the Pinephone on X11. What I've observed is that `SDL_MOUSEBUTTONUP` and `SDL_MOUSEBUTTONDOWN` are properly reported, however `SDL_MOUSEMOTION` events are not reported. Additionally gesture events (`SDL_MULTIGESTURE`) are not reported. Downgrading to 2.0.20 fixes these issues and `SDL_MULTIGESTURE` and `SDL_MOUSEMOTION` are then properly reported.

I've also noticed that setting the hint `SDL_TOUCH_MOUSE_EVENTS` to `0` restores the functionality of `SDL_MULTIGESTURE` events (but doesn't effect motion events..).

If I had to guess the root cause of this issue is: https://github.com/libsdl-org/SDL/commit/8f8b14cbb684603e71e5ee5ccf6e07f460efbb4c .. however I haven't tested beyond just downgrading to 2.0.20 and seeing things work.

I'm testing on X11/Alpine Linux edge (postmarketOS) on a Pinephone (aarch64). Two example applications packaged to test with are `mepo` and `rue` which both use touch events (and you can observe differences in application functionality between 2.0.22 and 2.0.20).

**Comment by mil** [comment]
https://github.com/koreader/koreader/issues/9091
^ found this issue in researching as well, may be related

**Comment by mil** [comment]
Hmm, so I tested reverting both: https://github.com/libsdl-org/SDL/commit/8f8b14cbb684603e71e5ee5ccf6e07f460efbb4c and https://github.com/libsdl-org/SDL/commit/96be9cddcc433f4ceeb7fa2c4df6b65196839b80 neither are the issue.

Not entirely sure on the root cause / where to investigate to determine cause of this issue. 2.0.20 is working as expected for me

**Comment by slouken** [comment]
Can you use git bisect to identify the breaking change?

**Comment by mil** [comment]
Offending commit is: 5ff42438e36e98c9d72ac70f5f5ce4599b96d3d2

Setting `export SDL_MOUSE_AUTO_CAPTURE=0` fixes things on 2.0.22 for me; maybe auto capture should be disabled by default

**Comment by slouken** [comment]
Why does auto capture affect touch events?

**Comment by sezero** [comment]
That commit caused _way too many_ issues

**Comment by dos1** [comment]
Touch handling on X11 with auto capture enabled is broken in general, it's not just gestures or mouse emulation. SDL sends an FINGERUP event right after FINGERDOWN (sometimes there's a single FINGERMOTION in between in you move your finger fast), so the touches end as soon as they start.

**Comment by slouken** [comment]
@icculus, can you look into this?

**Comment by ell1e** [comment]
For what it's worth, here is a reproduction case for the single touch mouse motion emulation (with `SDL_MOUSE_TOUCHID`) that has some visualization: https://github.com/libsdl-org/SDL/issues/5924#issue-1306801715 Doesn't cover multi touch however.

**Comment by slouken** [comment]
I can reproduce this here, I'm investigating.

**Comment by slouken** [comment]
Fixed, thanks!
