### ISSUE TITLE
Zandronum crashed

### ISSUE THREAD

**Issue by PenguinDOOM** [libsdl-org/SDL#5661]
I used sdl12-compat and it crashed.
And I found the problem part in SDL2.
https://github.com/libsdl-org/SDL/commit/635ebd967b7a8141e1022ed5c6b462df906f5c3a (It's also in `SDL_x11messagebox.c`)
`XInitThreads()` Do I have to comment out and rebuild SDL to disable this?

**Comment by icculus** [comment]
Wait, it's crashing in XInitThreads()? This seems like an extremely weird thing to cause problems. Is there something unique about your setup?

**Comment by PenguinDOOM** [comment]
No. Just using sdl12-compat will crash. And zandronum doesn't use multithreading.

**Comment by icculus** [comment]
But you're saying that the call to XInitThreads() in SDL2, added in 635ebd967b7a8141e1022ed5c6b462df906f5c3a, is what is causing the crash, right?

**Comment by PenguinDOOM** [comment]
Yes. The cause is SDL2.

**Comment by icculus** [comment]
Okay, but, again, XInitThreads() is an extremely unexpected place to crash. Can you tell me more about your setup? Is it some unusual piece of hardware, or an uncommon Linux distribution, etc?

**Comment by icculus** [comment]
I'm assuming this is a system issue. Feel free to reply with new information and we can revisit!
