### ISSUE TITLE
Virtual joystick stopped working on Android 

### ISSUE THREAD

**Issue by ceckak** [libsdl-org/SDL#5662]
Using SDL v2.0.14, I've been successfully setting up a virtual dpad in an android app using the following code:

```
	int joystickDeviceIndex = SDL_JoystickAttachVirtual(
			SDL_JOYSTICK_TYPE_GAMECONTROLLER, SDL_CONTROLLER_AXIS_MAX,
			SDL_CONTROLLER_BUTTON_MAX, 0);
	if (joystickDeviceIndex < 0) {
		return false;
	} else {
		m_gameController = SDL_GameControllerOpen(joystickDeviceIndex);
		if (!m_gameController) {
			return false;
		}
```

I am now trying to update to v2.0.22, and while the `SDL_JoystickAttachVirtual()` call succeeds, the `SDL_GameControllerOpen()` call fails.  After some digging, I've traced it back to [this code](https://github.com/libsdl-org/SDL/commit/1a17ab30e17f22c390caa1403f32dfac03532dff#diff-da9344d94c66b8c702a45e7649f412039f08bba83bd82de33f5c80ea9c8c39d5R488-R491), which is checking for some `SDL_GameControllerButton` flags to be set in the `SDL_JoystickGUID` data.  It doesn't appear that these get set automatically by `SDL_JoystickAttachVirtual()`, which thus prevents me from opening the virtual joystick with `SDL_GameControllerOpen()`.

Are there additional calls I can make to add these flags to the GUID, or is this a regression in support for virtual joysticks on Android?

Thanks!
Ken

**Comment by ceckak** [comment]
I realized after writing up this issue that I really don't need to be calling `SDL_GameControllerOpen()` at all since this is just a dpad with no game controller buttons on it.  After updating my code to call `SDL_JoystickOpen()`, I have the dpad up and working again on android with v2.0.22.

I'll leave this issue open for now until someone with more context can comment on whether it is expected/intended that `SDL_GameControllerOpen()` always fails with a virtual joystick.

**Comment by slouken** [comment]
Can you try the commit above and see if it fixes the problem you ran into?

Thanks!

**Comment by ceckak** [comment]
Thanks for the quick turnaround!  With https://github.com/libsdl-org/SDL/commit/7ad15c5b8f937bb759ae1f7d85f1a144a65194c6, I can open the controller now and the virtual joystick works for moving straight up and straight down, but I can no longer move diagonally or to either side.  This problem persists even if I change to using `SDL_JoystickOpen()` if https://github.com/libsdl-org/SDL/commit/7ad15c5b8f937bb759ae1f7d85f1a144a65194c6 is applied.

I'm out of time for tonight, but I'll do some digging this week to try and root cause the loss of side movement.

**Comment by slouken** [comment]
That's strange. I added code to testgamecontroller to verify virtual joysticks and the D-Pad works just fine there. The game controller code assumes it's implemented as buttons, but I shouldn't have changed the hat path when using the joystick interfaces.

**Comment by ceckak** [comment]
Agreed - it's not clear to me why this patch is triggering a problem.  I've confirmed that events are being pushed for both axes with nonzero values in `SDL_PrivateJoystickAxis()`.  Still tracing to see where they're getting lost at...

**Comment by ceckak** [comment]
The game uses calls to `SDL_GameControllerGetAxis()` to read `SDL_CONTROLLER_AXIS_LEFTX` and `SDL_CONTROLLER_AXIS_LEFTY` values.  I added some logging to `SDL_GameControllerGetAxis()` and found that there are `SDL_CONTROLLER_BINDTYPE_AXIS` bindings for ` SDL_CONTROLLER_AXIS_LEFTY`, `SDL_CONTROLLER_AXIS_RIGHTX`, `SDL_CONTROLLER_AXIS_TRIGGERLEFT` and `SDL_CONTROLLER_AXIS_TRIGGERRIGHT`, but no binding for `SDL_CONTROLLER_AXIS_LEFTX`.  That explains why I'm only getting vertical movement and no horizontal.

Now to find out why the `SDL_CONTROLLER_AXIS_LEFTX` binding is missing...

**Comment by slouken** [comment]
Interesting, I'm seeing the leftx binding here and able to get values from `SDL_GameControllerGetAxis()`

**Comment by ceckak** [comment]
Chased this down to root cause, although I'm still unclear why it is working for you and failing for me.  I should note that I am testing against the tip of `main`, which no longer has the `SDL_CreateMappingForVirtualController()` function you introduced in https://github.com/libsdl-org/SDL/commit/7ad15c5b8f937bb759ae1f7d85f1a144a65194c6.

Tracing through the issue, we have the following code which correctly writes the axis mask into the guid data for a virtual joystick:
https://github.com/libsdl-org/SDL/blob/f7b774a7e027b8fba0c98313812d8b0dea0eb239/src/joystick/virtual/SDL_virtualjoystick.c#L199-L207

Following the pointer arithmetic, that final line is writing `axis_mask` to bytes 14-15 of `guid.data`.  If I read the bytes back out at this point, I see the expected `axis_mask` value of `0x3f`.

However, the next couple of lines trample this value:
https://github.com/libsdl-org/SDL/blob/f7b774a7e027b8fba0c98313812d8b0dea0eb239/src/joystick/virtual/SDL_virtualjoystick.c#L210-L211

When I read out bytes 14-15 after that, I see a corrupted `axis_mask` value of `0x176`.

Later, when `SDL_CreateMappingForAndroidController()` tries to set up the mapping, it does so by reading these bytes out of the guid, and gets the erroneous `0x176` value:
https://github.com/libsdl-org/SDL/blob/f7b774a7e027b8fba0c98313812d8b0dea0eb239/src/joystick/SDL_gamecontroller.c#L483

With bit 0 unset in that value, it doesn't match the check for `SDL_CONTROLLER_AXIS_LEFTX` and I end up without a `leftx` in my mapping string, which ultimately leads to the missing binding:
https://github.com/libsdl-org/SDL/blob/f7b774a7e027b8fba0c98313812d8b0dea0eb239/src/joystick/SDL_gamecontroller.c#L547-L549

**Comment by slouken** [comment]
Ahh, nice sleuthing. It’s working for me because I’m on Windows. I’ll look into it shortly.

**Comment by slouken** [comment]
Here you go, this should work! :)

**Comment by ceckak** [comment]
Confirmed - works great now, both with `SDL_GameControllerOpen()` and `SDL_JoystickOpen()`.  Thanks!

**Comment by slouken** [comment]
Great, thanks!
