### ISSUE TITLE
IOS: Compilation of SDL and satellite libraries

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#5665]
I have this very simple script:
[ios_build_libs.sh.txt](https://github.com/libsdl-org/SDL/files/8698012/ios_build_libs.sh.txt)

That helps me to re-build all SDL, SDL_image, SDL_mixer and SDL_ttf libraries  in release, debug,device,simulator. for iOS or tvOS. In one command.
Now, it fails with mysterious messages. see below. (it may not be relevant).

I see that the "scheme" a now more homogeneous. For SDL the are "Static Library-iOS" or "-TV". But no differentiation for other libraries. Is this ok ? 
Same thing for "framework" scheme: there is  a "Framework-iOS" scheme for SDL. And only "Framework"for other libs.

I wonder which scheme should be used to build for ios. Thanks.

It seems this script should be legitimate to run correctly since it only triggers the Xcode build. with some parameter. Any help is appreciated :) 

```log
/Users/s/Library/Developer/Xcode/DerivedData/SDL-dgdwwfogariedibsiqbkveftrenw/Build/Intermediates.noindex/SDL.build/Debug-iphonesimulator/Framework-iOS.build/Objects-normal/i386/SDL_surface.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'Framework-iOS' from project 'SDL')

,,,

note: Building targets in dependency order
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'Framework' from project 'SDL_ttf')
/Users/s/release/Release_SDL_IOS/SDL_ttf/Xcode/SDL_ttf.xcodeproj: error: Building for iOS, but the linked framework 'SDL2.framework' was built for macOS. (in target 'Framework' from project 'SDL_ttf')
** BUILD FAILED **

```

**Comment by kambala-decapitator** [comment]
it's difficult to say what's causing the error without seeing full compile output.

haven't seen any issues when building static library target, you can check my script here: https://github.com/kambala-decapitator/vcmi-ios-depends/blob/main/build_depends.sh#L171

**Comment by slouken** [comment]
You might just need to clean before running this script?

**Comment by gbgames** [comment]
@kambala-decapitator Have you tried your script with SDL2_image v2.6.2? Your script references v2.0.5. I believe v2.0.5 still uses Xcode-iOS which does not exist anymore in the latest versions. 

My own similar xcodebuild command fails when building the simulator version with 

`error: ApplicationServices is not available when building for iOS Simulator. (in target 'Static Library' from project 'SDL_image')`

It's not the same error as @1bsyl, but it seems related in that SDL_image seems to want to build the iOS project as a Mac project, unless we are building it wrong?

My original xcodebuild command:

`xcodebuild -scheme "Static Library" -configuration Release -sdk iphoneos SKIP_INSTALL=NO BUILD_DIR=build/SDL2_image-iphoneos`

And I tried this change based partly on @kambala-decapitator's script:

`xcodebuild -target "Static Library" -configuration Release -sdk iphonesimulator ENABLE_BITCODE=NO IPHONEOS_DEPLOYMENT_TARGET=10.0 PLATFORM=iOS BUILD_DIR=build/SDL2_image-iphonesimulator`

**Comment by kambala-decapitator** [comment]
@gbgames if I recall correctly, Xcode project has been changed to multi-platform support, but unfortunately it requires Xcode 13 (you use 12.4 as I see)

you can also build with CMake and https://github.com/leetal/ios-cmake

**Comment by 1bsyl** [comment]
I have updated all libs to latest head version.
Indeed, adding a real "clean" target seems to solve the strange error as @slouken
But it still doesn't fully compile as I'd like. 
For some reasons: SDL_image seems unable to find the include of "SDL.h" whereas others do.
Which is strange because the script just trigger the xcodebuild

```
  2 CompileC /Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/Objects-normal/x86_64/IMG_xxx.o /User    s/s/release/Release_SDL_IOS/SDL_image/IMG_xxx.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Static Library' from project 'SDL_image')
  3     cd /Users/s/release/Release_SDL_IOS/SDL_image/Xcode
  4     export LANG\=en_US.US-ASCII
  5     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target x86_64-apple-ios9.0-simulator -fmessage-length\=235 -fdiagnostics-show-note-include-stack -fmacro-backtrace-    limit\=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-labe    l -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno    -bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DLOAD_PNG -DLOAD_XPM -isysroot /Applications    /Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comm    a -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -index-store-path /Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Index/DataStore -iquote     /Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/SDL2_image-generated-files.hmap -I/Users/s/Lib    rary/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/SDL2_image-own-target-headers.hmap -I/Users/s/Library/Deve    loper/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/SDL2_image-all-target-headers.hmap -iquote /Users/s/Library/Develop    er/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/SDL2_image-project-headers.hmap -I/Users/s/release/Release_SDL_IOS/SDL    /Debug-iphonesimulator/include -I/Users/s/release/Release_SDL_IOS/SDL_image/Xcode/SDL2.framework/Headers -I/Users/s/release/Release_SDL_IOS/SDL_image/external/jpeg -I/Users/s/Library/Developer/Xcode/DerivedData/SDL_ima    ge-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/DerivedSources-normal/x86_64 -I/Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonji    dffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/DerivedSources/x86_64 -I/Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build    /Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/DerivedSources -F/Users/s/release/Release_SDL_IOS/SDL/Debug-iphonesimulator -F/Users/s/release/Release_SDL_IOS/SDL_image/Xcode -fembed-    bitcode -MMD -MT dependencies -MF /Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/Objects-norm    al/x86_64/IMG_xxx.d --serialize-diagnostics /Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build/Debug-iphonesimulator/Static\ Library.build/Ob    jects-normal/x86_64/IMG_xxx.dia -c /Users/s/release/Release_SDL_IOS/SDL_image/IMG_xxx.c -o /Users/s/Library/Developer/Xcode/DerivedData/SDL_image-avfmwhcnonjidffrmpewletkllpe/Build/Intermediates.noindex/SDL_image.build    /Debug-iphonesimulator/Static\ Library.build/Objects-normal/x86_64/IMG_xxx.o -index-unit-output-path /SDL_image.build/Debug-iphonesimulator/Static\ Library.build/Objects-normal/x86_64/IMG_xxx.o
  6 In file included from /Users/s/release/Release_SDL_IOS/SDL_image/IMG_xxx.c:24:
  7 /Users/s/release/Release_SDL_IOS/SDL_image/SDL_image.h:32:10: fatal error: 'SDL.h' file not found
  8 #include "SDL.h"
```

Updated script: [ios_build_libs.sh.txt](https://github.com/libsdl-org/SDL/files/9481015/ios_build_libs.sh.txt)

Currently building the libraries static. Not tested to build as a framework.

**Comment by 1bsyl** [comment]
I fixed my script: 
[ios_build_libs.sh.txt](https://github.com/libsdl-org/SDL/files/9483381/ios_build_libs.sh.txt)

It seems I have to "force" the PLATFORM variable so that the HEADER_SEARCH_PATHS are correct.
eg: adding 'PLATFORM=iOS' to the xcodebuild command line.
