### ISSUE TITLE
SDL_HINT_FRAMEBUFFER_ACCELERATION is nerfed in 2.0.22

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5671]
In fixing up the framebuffer texture stuff, I accidentally nerfed SDL_HINT_FRAMEBUFFER_ACCELERATION:

https://github.com/libsdl-org/SDL/blob/adac3bd/src/video/SDL_video.c#L195-L221

This says "do we want a specific renderer? Find it. Otherwise, look for anything that isn't software rendering," but this doesn't take into account that the hint can be "0" to disable acceleration (force software).

**Comment by sezero** [comment]
We already have something in master, unless I'm missing something?
https://github.com/libsdl-org/SDL/pull/5611
https://github.com/libsdl-org/SDL/commit/adac3bd1e27c2c9535439ccce9fa64f120759613

**Comment by icculus** [comment]
Whoops, I didn't realize we fixed this in a higher-level function! Okay, sorry about that, closing...
