### ISSUE TITLE
Needed possibility to show the window without activating it

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#5676]
Being able to show a window without activating it would be very useful in applications that use more than one window. Currently there is a problem with this. I have the main window on the main screen and I want to show the second window on the secondary screen — it's currently impossible to do if I want to keep the main window focused.

For now, I have solved the problem by using WinAPI function [`ShowWindow`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow), specifying the `SW_SHOWNOACTIVATE` flag, but there must be an option added to SDL, so that you don't have to use platform-specific solutions.

There should be a flag like `SDL_WINDOW_NOACTIVATE` that could be attached to the flags in the `SDL_CreateWindow` function call, as well as an additional function like `SDL_ShowWindowInactive`, dedicated to displaying the window without activation. Such functionality should be available at least on desktop platforms.

**Comment by RT222** [comment]
Since 2.0.22, there's a hint named SDL_HINT_WINDOW_NO_ACTIVATION_WHEN_SHOWN who does exactly that, although it is implemented on Windows platform only.
