### ISSUE TITLE
Linux: Undefined reference when `HAVE_INOTIFY` not defined

### ISSUE THREAD

**Issue by player-03** [libsdl-org/SDL#5682]
The Linux version of SDL_sysjoystick.c [defines the `IsJoystickDeviceNode` function](https://github.com/libsdl-org/SDL/blob/db9e14e504af38b52a7cc8d0e03bc8c746816c12/src/joystick/linux/SDL_sysjoystick.c#L559-L567) inside an [`#ifdef HAVE_INOTIFY` block](https://github.com/libsdl-org/SDL/blob/db9e14e504af38b52a7cc8d0e03bc8c746816c12/src/joystick/linux/SDL_sysjoystick.c#L500-L611), but then [uses it outside the block](https://github.com/libsdl-org/SDL/blob/db9e14e504af38b52a7cc8d0e03bc8c746816c12/src/joystick/linux/SDL_sysjoystick.c#L640). This of course produces the error ```undefined reference to `IsJoystickDeviceNode'``` if the user lacks inotify.

**Comment by slouken** [comment]
Fixed, thanks!
