### ISSUE TITLE
[request] Surface flip API

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#5697]
https://github.com/libsdl-org/SDL/blob/83ae1b4987227e9580e32c8c87e92732e8d7edb3/src/render/software/SDL_render_sw.c#L443-L445

use software?

**Comment by Starbuck5** [comment]
Do you mean a function like pygame.transform.flip? https://www.pygame.org/docs/ref/transform.html#pygame.transform.flip

**Comment by baidwwy** [comment]
> 

right！right！right！

**Comment by baidwwy** [comment]
> Do you mean a function like pygame.transform.flip? https://www.pygame.org/docs/ref/transform.html#pygame.transform.flip

right！right！right！

**Comment by baidwwy** [comment]
https://github.com/pygame/pygame/blob/365f094d66e688b7582e41fb8aaf9d150b150774/src_c/transform.c#L781-L932
@slouken

**Comment by slouken** [comment]
This is a duplicate of https://github.com/libsdl-org/SDL/issues/8857
