### ISSUE TITLE
Cannot build SDL2 for Windows < 8

### ISSUE THREAD

**Issue by ronaaron** [libsdl-org/SDL#5715]
For some reason, as of 2.0.22 you are using the "RoInitializeFunc()" etc, which are only from Win8 and beyond.

Please allow them to be not used via an #ifdef, as I'm compiling for compatibility back to WinXP and Windows7.

**Comment by ccawley2011** [comment]
The `RoInitialize()` and `RoUninitialize()` functions are already dynamically loaded at runtime, so SDL should still work on Windows versions that don't have these functions.

Are you encountering any particular errors that are caused because of `RoInitialize()`?

**Comment by Wohlstand** [comment]
I successfully built the code of SDL2 2.0.22 in as-is form using the MinGW-w64 compiler, and it works perfect on Windows XP:

![image](https://user-images.githubusercontent.com/6751442/173716586-dda17b90-33ae-419e-b138-a99e213b45bc.png)

My major tip: **never use MSVC-family compilers** when targeting old Windows versions, it always intends to kill the backward compatibility, and blame MSVC's runtimes. MinGW-family compilers are very friendly in this case, so, you were able to compile the thing that will work even on Windows 9x in some conditions. MinGW-w64 gives you the modern C++ standards support, and allows you to build the application that will work on older Windows versions if you don't use too new WinAPI calls without the LoadLibrary()-based overlay.

**Comment by madebr** [comment]
I confirm.
I just tried running SDL3, built by 32-bit mingw, in a qemu windows xp vm and it works (mostly).
