### ISSUE TITLE
Build Android aar script broken

### ISSUE THREAD

**Issue by act262** [libsdl-org/SDL#5716]
After new AGP , rename outputs is fault.

`        libraryVariants.all { variant ->
            variant.outputs.each { output ->
                def outputFile = output.outputFile
                if (outputFile != null && outputFile.name.endsWith(".aar")) {
                    def fileName = "org.libsdl.app.aar";
                    output.outputFile = new File(outputFile.parent, fileName);
                }
            }
        }`

**Comment by slouken** [comment]
@madebr, is this still an issue?

**Comment by madebr** [comment]
I don't know how to reproduce this.
@act262 
Can you provide steps and/or a fix?
