### ISSUE TITLE
SDL_SetWindowBordered() changes window size

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#5718]
When you disable the window
controls with `SDL_SetWindowBordered(..., SDL_FALSE);`
your window gets effectively enlarged
for the space that was used by the
window controls. Likewise when you
enable controls, your drawing area
effectively shrinks.

SDL_SetWindowBordered() should
only enable/disable window decorations,
but it should not lead to the window
being effectively resized, from an app's
POV.

**Comment by slouken** [comment]
What platform are you seeing this on?

**Comment by icculus** [comment]
I recall this being an issue in the past, but fwiw, this is _not_ reproducing here, at least with this simple test program:

```c
#include "SDL.h"

int main(int argc, char **argv)
{
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, 0);
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);
    SDL_bool done = SDL_FALSE;
    SDL_bool bordered = SDL_TRUE;

    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);

    while (!done) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                done = SDL_TRUE;
            } else if ((e.type == SDL_KEYDOWN) && (e.key.keysym.sym == SDLK_b)) {
                bordered = bordered ? SDL_FALSE : SDL_TRUE;
                SDL_SetWindowBordered(window, bordered);
            }
        }

        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
        SDL_Delay(10);
    }
    return 0;
}
```

Pressing B makes the titlebar vanish (and in what might be a questionable design choice, moves the window up to the space where the titlebar used to be) but it does _not_ resize the window.

X11/gnome 42.1, Ubuntu 22.04

Can you try that test program on your system and see what happens? I'm using the latest in SDL's git repo, too.

**Comment by stsp** [comment]
Please try SDL_WINDOW_RESIZABLE
flag, thanks.

**Comment by icculus** [comment]
Definitely fixed the reproduction case here with b75cd2b36dd742b956a225087dad39d14884f581, but this sort of thing can be fragile, so we'll see if any new issues pop up now.

**Comment by stsp** [comment]
Perhaps it would make sense to report
a bug to wm instead (or in addition).

**Comment by stsp** [comment]
Or maybe that's a clue?
Perhaps if you don't want
window to resize, you
should first remove the
resizable flag? Because
w/o controls its not resizable
anyway. So wm could indeed
use that flag as a hint?

**Comment by icculus** [comment]
It really doesn't matter if this gets fixed in Gnome (if Gnome even would consider it a bug), because we need it to work with older Gnomes and other window managers.

**Comment by stsp** [comment]
Yeah but how about clearing
the resizable flag first? This may
even be the right thing to do, no?
And it will definitely fix the problem.
