### ISSUE TITLE
Cannot open the same controller multiple times on linux

### ISSUE THREAD

**Issue by hwjsnc** [libsdl-org/SDL#5722]
In SDL2 version 2.0.20 and before, it was possible to open the same controller multiple times from different processes such that all of them receive the controller input events simultaneously.

Since version 2.0.22 this is not possible anymore: Once the controller has been opened by one program, it cannot be opened by another until the first one closes it again. In the interim time, the corresponding /dev/input/event* /dev/input/js* files are gone.

**Comment by hwjsnc** [comment]
`git bisect` led me to commit 0cb39ed4685473928b01682f875f7bb086fbe465.

**Comment by slouken** [comment]
I'm pretty sure what happened here is that libusb didn't use to be available, and now it is. In order for libusb to function, it takes exclusive control over the USB devices, which doesn't play nice with other users on the system.

@madebr, the autotools version of this defaults libusb off, except on platforms like *BSD, where it's necessary. Is there a way to do something similar here with CMake?

**Comment by slouken** [comment]
Here's the relevant autotools snippet:
```sh
    AC_ARG_ENABLE(hidapi-libusb,
[AS_HELP_STRING([--enable-hidapi-libusb], [use libusb for low level joystick drivers [default=maybe]])],
                  , enable_hidapi_libusb=maybe)

    if test x$enable_hidapi = xyes; then
        case "$host" in
            # libusb does not support iOS
            *-ios-* )
                enable_hidapi_libusb=no
                ;;
            # On the other hand, *BSD specifically uses libusb only
            *-*-*bsd* )
                enable_hidapi_libusb=yes
                require_hidapi_libusb=yes
                ;;
           *-*-os2* )
                enable_hidapi_libusb=yes
                ;;
        esac

        hidapi_support=yes
        if test x$enable_hidapi_libusb = xyes; then
            PKG_CHECK_MODULES([LIBUSB], [libusb-1.0], have_libusb=yes, have_libusb=no)
            save_CPPFLAGS="$CPPFLAGS"
            CPPFLAGS="$save_CPPFLAGS $LIBUSB_CFLAGS"
            AC_CHECK_HEADER(libusb.h, have_libusb_h=yes, have_libusb_h=no)
            CPPFLAGS="$save_CPPFLAGS"
            if test x$have_libusb_h = xno && test x$require_hidapi_libusb = xyes; then
                hidapi_support=no
            fi
        fi
```

**Comment by slouken** [comment]
@madebr, can you please fix this for the 2.24.0 release?

**Comment by madebr** [comment]
@hwjsnc 
Can you test #5962?
On Linux, it disables libusb by default.

**Comment by hwjsnc** [comment]
Thanks for that fix. Unfortunately I can't test it at the moment because SDL doesn't compile for me for unrelated reasons (including versions which previously did). I'll try to figure out what's going on and test the patch, but it will likely take at least a few days.

**Comment by hwjsnc** [comment]
I can now confirm the patch works for me. Thanks again!
