### ISSUE TITLE
URL is miss leading

### ISSUE THREAD

**Issue by SkybuckFlying** [libsdl-org/SDL#5734]
https://github.com/libsdl-org/SDL

This makes it seem like this was the first version of SDL, while in reality it is 2.x

Recommend different URL which clearly states SDL2.

To prevent time wasted on using wrong version. I only noticed it after palette->version was missing.

60 minutes of time wasted, I consider myself lucky.

99.9% of the people on this planet suck at proper versioning, including file systems.

Fortunately SDL1 is not fully retarded:

https://github.com/libsdl-org/SDL-1.2

**Comment by slime73** [comment]
2 is part of the version number, not the project name. I think it's fairly intuitive.

**Comment by SkybuckFlying** [comment]
It's most likely part of the DLL name, so it's a big deal.

**Comment by SkybuckFlying** [comment]
> 2 is part of the version number, not the project name. I think it's fairly intuitive. The readme also says the major version number at the top.

For the love of god I have more things to do then read readme files. I need to download it first.

Which readme should I download ?!?!

Answer my question !

**Comment by slime73** [comment]
The readme is readable on this webpage, if you scroll down after loading https://github.com/libsdl-org/SDL

Right here: https://github.com/libsdl-org/SDL#simple-directmedia-layer-sdl-version-20

Also while I don't think slurs are necessary to communicate your frustrations.

**Comment by slouken** [comment]
In general, GitHub projects use the project name as the entire repo, including all versions of the project, and the main branch is the current version, and different versions are specified using branches or tags in the repo. You can see a good example of this at https://github.com/godotengine/godot.
