### ISSUE TITLE
uinput-fpc fingerprint sensor isn’t actually a joystick [ Linux Mobile edition]

### ISSUE THREAD

**Issue by nitanmarcel** [libsdl-org/SDL#5737]
Mobile phones that are running Linux distributions made for mobile device encounter an old issue that happened before with android phones and has been fixed at https://github.com/libsdl-org/SDL/commit/a2e856523089d5d95ba565a26a35ab367c960f12

The fix above is only for android builds of SDL but the bug can happen now on an device that runs a mobile packed linux distribution and a desktop version of sdl.

**Comment by slouken** [comment]
Can you confirm that removing the `#if defined(__ANDROID__)` part of that fixes the issue for you?

**Comment by nitanmarcel** [comment]
> Can you confirm that removing the `#if defined(__ANDROID__)` part of that fixes the issue for you?

Can you help me with compiling SDL2 for arm64 (aarch64) architecture?

I've done

```
./configure --host aarch64-linux --build amd64-linux --target aarch64-linux
make -j$(nproc)
sudo make install
```

But `libSDL2.so` is still ` x86-64`

**Comment by slouken** [comment]
Possibly fixed by https://github.com/libsdl-org/SDL/commit/7fa46ec40b8b6a58f174f0992ecead0a1ab23817

**Comment by slouken** [comment]
Can you confirm that this is fixed?

**Comment by nitanmarcel** [comment]
> Can you confirm that this is fixed?

Sorry for the delay.

I've compiled the following code found in the wiki and it still tells me that the fingerprint is a joystick:

```cpp
#include "SDL2/SDL.h"
#include <string>
#include <iostream>

int main(int argc, char *argv[]) {
  SDL_Init(SDL_INIT_EVERYTHING);

  int num_joy, i;
  num_joy = SDL_NumJoysticks();
  printf("%d joysticks found\n", num_joy);
  for (i = 0; i < num_joy; ++i) {
    printf("%s\n", SDL_JoystickNameForIndex(i));
  }
}
```

**Comment by slouken** [comment]
Any chance we can do a video call to interactively debug this? Please send me e-mail at slouken@libsdl.org to coordinate.

**Comment by nitanmarcel** [comment]
> Any chance we can do a video call to interactively debug this? Please send me e-mail at [slouken@libsdl.org](mailto:slouken@libsdl.org) to coordinate.

Okay. Sent you an email on gmail with a way we can communicate to debug this issue. :)

**Comment by slouken** [comment]
Hmm, I haven't received the e-mail... you can also send it to slouken@gmail.com

**Comment by nitanmarcel** [comment]
> Hmm, I haven't received the e-mail... you can also send it to [slouken@gmail.com](mailto:slouken@gmail.com)

Maybe also check the spam section? Anyway, I forwarded it to the email address

**Comment by nitanmarcel** [comment]
> Hmm, I haven't received the e-mail... you can also send it to [slouken@gmail.com](mailto:slouken@gmail.com)

In case you still haven't got it

> Hello.

> I'm nitanmarcel on github, you've told me to send you an email to help you debug the  linux mobile coming with an uinput-fpc fingerprint sensor that gets detected as a joystick.

> We can do a video call as you suggested when we both have time, and I can also create a tmate session and we can communicate to any service of online communication.

> If you don't know about tmate, it's a way to open an ssh session that others can access online.

> https://www.tecmint.com/tmate-share-ssh-terminal-session/

> If you have Telegram I can be contacted at t.me/nitanmarcel or if you have any suggestions for other way of communicating I'm happy to use it in helping you to debug this issue.

> Alex.

**Comment by slouken** [comment]
Yes, I got your e-mail and replied.

**Comment by nitanmarcel** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/7fa46ec40b8b6a58f174f0992ecead0a1ab23817 I just done something wrong in testing it and it used an old sdl installation. Everything works fine now ^^

**Comment by slouken** [comment]
Great, thanks!
