### ISSUE TITLE
CMake: SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC can end up empty, resulting in broken PA audio driver

### ISSUE THREAD

**Issue by kblaschke** [libsdl-org/SDL#5747]
If only PulseAudio headers & PkgConfig files are present, but `libpulse-simple.so` is not present (or not found in the default search dirs), PulseAudio support is enabled and  `SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC` in the generated `SDL_config.h` ends up as an empty string, effectively breaking the audio driver in the resulting binary.

I suggest also checking `PULSE_SIMPLE_LIB_SONAME` to contain an actual filename (and not being empty or containing `NOTFOUND`) [here](https://github.com/libsdl-org/SDL/blob/847539afebe1019c2e1320eccfbe2334d30a2bcc/cmake/sdlchecks.cmake#L174) before enabling Pulseaudio support.

It's a rare case and should certainly not happen in "good" setups, but when using a cross-compile toolchain with more than a single search path, it might break silently - resulting in a broken library while saying PA support is enabled.

**Comment by kblaschke** [comment]
Fully agree. Or at least set the use of the specific library/feature/driver to `OFF` and display it accordingly in the config summary, just similar to the behavior whenever the headers or the PkgConfig files aren't found.

In this case, it even leaves dynamic loading enabled, but tries to load an empty filename in `dlopen()` or `LoadLibrary()`, which naturally always fails. This results in the subsystem being used, but telling the user (at least in the audio driver case) at runtime that it's not been initialized.

**Comment by slouken** [comment]
> Fully agree. Or at least set the use of the specific library/feature/driver to `OFF` and display it accordingly in the config summary, just similar to the behavior whenever the headers or the PkgConfig files aren't found.

This is how autotools handles it, and is my preferred solution. SDL supports so many optional OS features that we shouldn't fail the build if they don't happen to be present on the system.
