### ISSUE TITLE
File handling Issue

### ISSUE THREAD

**Issue by SusheelThapa** [libsdl-org/SDL#5758]
1. I have created an object of an class and assign value to the object of that class
2. Then i have wrote that object in the file using SDL_RWops methods.
3. Then i have change the value of the object that i have written over the file
4. Then i have read the data that i have written to the file
5. Then I have create texture out the data that i have retrieve from the file.
6. But i didnot get the expected data

```C++
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_ttf.h>

#include "player.h"

#include <iostream>

class TestData
{
private:
    std::string data;

public:
    void setData(std::string d)
    {
        this->data = d;
    }
    std::string getData()
    {
        return data;
    }
};
bool init()
{ // Initialize SDL with video and audio
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO) < 0)
    {
        printf("SDL could not initialize! SDL Error: %s\n", SDL_GetError());
        return false;
    }

    // Set texture filtering to linear
    if (!SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "1"))
    {
        printf("Warning: Linear texture filtering not enabled!");
    }

    // Initialize PNG loading
    int imgFlags = IMG_INIT_PNG;
    if (!(IMG_Init(imgFlags) & imgFlags))
    {
        printf("SDL_image could not initialize! SDL_image Error: %s\n", IMG_GetError());
        return false;
    }

    // Initialize SDL_ttf
    if (TTF_Init() == -1)
    {
        printf("SDL_ttf could not initialize! SDL_ttf Error: %s\n", TTF_GetError());
        return false;
    }

    return true;
}

void close()
{

    // Quit SDL subsystems
    TTF_Quit();
    IMG_Quit();
    SDL_Quit();
}

int main(int argc, char const *argv[])
{
    init();

    // Create window
    SDL_Window *window = SDL_CreateWindow(
        "Learning SDL",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        900, 900,
        SDL_WINDOW_SHOWN);

    if (window == nullptr)
    {
        printf("Window could not be created! SDL Error: %s\n", SDL_GetError());
        return false;
    }

    // Create vsynced renderer for window
    SDL_Renderer *renderer = SDL_CreateRenderer(
        window, -1,
        SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

    if (renderer == nullptr)
    {
        printf("Renderer could not be created! SDL Error: %s\n", SDL_GetError());
        return false;
    }

    TTF_Font *font = TTF_OpenFont("res/fonts/verdana.ttf", 24);

    if (font == nullptr)
    {
        std::cout << "Unable to load the font\n"
                  << SDL_GetError() << "\n";
    }

    TestData test, test2;

    test.setData("SDL Learning");

    /*Writing over the file*/
    SDL_RWops *file_write = SDL_RWFromFile("data.bin", "w+b");

    SDL_RWwrite(file_write, &test, sizeof(TestData), 1);

    SDL_RWclose(file_write);

    test.setData("Herol is good");

    /*Reading over the file*/
    SDL_RWops *file_read = SDL_RWFromFile("data.bin", "r+b");

    // SDL_RWread(file_read, &test2, sizeof(TestData), 1);
    SDL_RWread(file_read, &test2, sizeof(TestData), 1);

    SDL_RWclose(file_read);

    std::cout << test2.getData() << "\n";

    /* Creating texture of the data we have read from the file*/
    SDL_Texture *texture;

    SDL_Surface *surface = TTF_RenderText_Solid(font, test2.getData().c_str(), {23, 45, 67});

    if (surface != nullptr)
    {
        texture = SDL_CreateTextureFromSurface(renderer, surface);

        if (texture == nullptr)
        {
            std::cout << "Texture loading error\n"
                      << SDL_GetError() << "\n";
        }
    }
    else
    {
        std::cout << "Unable to load the surface\n"
                  << SDL_GetError() << "\n";
    }

    SDL_Event e;
    while (true)
    {
        while (SDL_PollEvent(&e) != 0)
        {
            if (e.type == SDL_QUIT || e.key.keysym.sym == SDLK_ESCAPE)
            {
                exit(0);
            }
        }
        SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);

        SDL_RenderClear(renderer);

        SDL_RenderCopy(renderer, texture, nullptr, nullptr);

        SDL_RenderPresent(renderer);
    }

    TTF_CloseFont(font);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    window = nullptr;
    renderer = nullptr;

    return 0;
}
```

https://user-images.githubusercontent.com/83917129/172008011-a4069190-05c9-4504-af6a-68e9c56485c0.mp4

**Here i have write "SDL Learning" and after file is closed i have update the value of variable to "Herol is good.
While rendering it was expected to render "SDL Learning" as i have retrieve the data that is written from file but it show "Herol is good"**

**Comment by 0x1F9F1** [comment]
Both this and your other issue #5745 are happening because you cannot safely just copy the bytes of a `std::string` (or basically any other class which contains a pointer/owns memory), and expect it to work correctly. In C++ if a class can safely be copied in this way is it known as [trivially copyable](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable).

**Comment by SusheelThapa** [comment]
## Understanding
I understood that the implementation of C string and C++ string is different

## Another Issue

If i run the same code in window it display SDL learning but in linux it display Herol is good

https://user-images.githubusercontent.com/83917129/172047657-f39bac18-814b-4a70-a215-a6143d9ba042.mp4

**Comment by madebr** [comment]
Your issue is what @0x1F9F1 described.
```c++
SDL_RWwrite(file_write, &test, sizeof(TestData), 1);
```
will copy the binary layout of of the `TestData` object which contains a `std::string`.
Because `std::string` internally allocates a buffer and contains a buffer, it will write the pointer instead of the actual data.

So you need to add functionality to serialize/deserialize data.

It working on Linux and not working on Windows demonstrates you're using undocumented behavior.
It's working on Linux because of "c++ small string optimization".

Notice how, when you modify the first `test.setData` to pass it a longer/shorter string, the `data.bin` file does not change in file size.

Pass a very long string to the first `test.setData`, notice how the `data.bin` contains only binary data.

**Comment by madebr** [comment]
I'm going to close this issue as this is not an SDL issue.
