### ISSUE TITLE
Memory leaks on master with simple app not doing anything

### ISSUE THREAD

**Issue by WSSDude420** [libsdl-org/SDL#5759]
This simple sample with latest master from git is causing 5 allocations to keep hanging.
Am I missing some free I should have done? I think I did not left anything for simple sample 🤔 

I am on Windows 11, using Visual Studio 22 if it makes any difference.
Just this sample is causing mentioned issue, no other code is anywhere inbetween in the main itself.

```cpp
SDLMAIN_DECLSPEC int SDL_main(int argc, char* argv[])
{
  const auto init_allocations = SDL_GetNumAllocations(); // NOTE: always seems to be 0 at this point, but leaving it for good measure...

  // Setup SDL
  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_GAMECONTROLLER) != 0)
  {
    printf("Error: %s\n", SDL_GetError());
    return -1;
  }

  // Setup window
  SDL_WindowFlags window_flags = (SDL_WindowFlags)(SDL_WINDOW_VULKAN | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
  SDL_Window* window = SDL_CreateWindow("SDL2 Example", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 1280, 720, window_flags);

  // Main loop
  bool done = false;
  while (!done)
  {
    SDL_Event event;
    while (SDL_PollEvent(&event))
    {
      if (event.type == SDL_QUIT)
        done = true;
      if (event.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_CLOSE && event.window.windowID == SDL_GetWindowID(window))
        done = true;
    }
  }

  SDL_DestroyWindow(window);
  SDL_Quit();

  SDL_assert(init_allocations == SDL_GetNumAllocations()); // ERROR: assertion fails, as there seem to be 5 allocations performed inside some of these functions that do not get freed
  return 0;
}
```

**Comment by WSSDude420** [comment]
Ok, somehow I can't get the 5 allocations mentioned now after trying to replace memory functions to be able to monitor what allocations are not freed...
Am getting 3 after replacement.

With replacement, those 3 places seem to be:
- thread local storage allocation inside `src\thread\SDL_thread.c` in function `int SDL_TLSSet(SDL_TLSID id, const void *value, void (SDLCALL *destructor)(void *))` (culprit seems to be SDL_realloc)
- error buffer allocation in `src\thread\SDL_thread.c` inside function `SDL_error* SDL_GetErrBuf(void)` (there is only one SDL_malloc)
- ime composition allocation in `src\video\windows\SDL_windowskeyboard.c` inside function `void WIN_InitKeyboard(_THIS)` (assignment of `data->ime_composition`, SDL_malloc call)
-

**Comment by huth** [comment]
I'm seeing a similar problem - using this even more simple C program:
``
#include <SDL2/SDL.h>

int main()
{
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Quit();
  return 0;
}
``

Compiling it with ``gcc -fsanitize=address sdltest.c -o sdltest -lSDL2`` and running the test program, I can see a lot of leaks reported. For some reason, some of the leaks seem to go away if I also add SDL_INIT_AUDIO to the SDL_Init() call.

**Comment by icculus** [comment]
The error state and tls allocation (which is related to error state) is intentional, as far as I know (and I think we added a function you can call to clean this up manually).

The Windows IME thing is probably a legit leak to fix though. I'll take a look tomorrow.

**Comment by slouken** [comment]
The TLS cleanup function is `SDL_TLSCleanup()`

The memory leak is fixed in https://github.com/libsdl-org/SDL/commit/15bcf58d779fca8da37a7c3e8562af9d2503bbea

Thanks!
