### ISSUE TITLE
macOS: not receiving KEYDOWN events or correct keyboard state

### ISSUE THREAD

**Issue by bhallstein** [libsdl-org/SDL#5762]
Hi, I'm having an issue persuading a prototype SDL app to receive keyboard events.

## Steps to reproduce:

- Cloned SDL, built the framework for my mac using the Xcode project.
- Created a new Xcode project. Added the compiled SDL framework.
- Set up the AppDelegate to create a new SDL window and context.
- Create a timer to run the "game".
- Inside the timer call-back, process events using PollEvent.

This is somewhat different to a simple main-function-based while loop with an event loop inside of it. However it is a very familiar way to process events. As SDL creates and controls the window and its contents, and when those NSObjects provide events they can be added to the SDL global event queue as normal, there is no reason this should not work as far as I've been able to reason it.

I suspected a threading-related issue, especially as very occasionally a key event is entered onto the event queue (see below). I have however verified that `[NSThread isMainThread]` returns true in both the `applicationDidFinishLaunching` (where the window and context are created) and in the timer method (where events are dequeued).

## Reproduction repo:

I created a repo to reproduce the issue: https://github.com/bhallstein/SDLKeyEventRepro It should be compilable immediately after downloading.

The included SDL framework was compiled from release-2.0.22 on my M1 mac mini, target set to include both x64 and arm archs. macOS version was Monterey 12.4.

## An odd thing I noticed

_Very_ occasionally, a keypress event does make it through! This sounds vague but happens reproducibly. To reproduce,  try holding various keys depressed for a long time.

## What else I've tried

- I've tried using the GetKeyboardState command. Oddly this gives very similar results in that it does not report the key as down. And on one occasion while holding down a key for a long time, I found that that key state updated to 'pressed' in the returned array. However after that, it never re-updated to 'not pressed' in the array. Very strange.
- Everything I can find regarding telling the SDL window to accept input focus. In the current reproduction repo above, I just use RaiseWindow. Result: same.
- Verified that the window had focus using GetKeyboardFocus.
- A few different versions e.g. release-2.0.14 and a couple of commits that are more recent than 2.0.22.

**Comment by slime73** [comment]
Your own event loop is probably stealing OS input events from SDL.

**Comment by bhallstein** [comment]
@slime73 I'm doubtful but open minded. NB I have not created an event loop, just looping through using PollEvent based on a timer. That is, from what I can see there isn't anything that ought to interfere with event delivery to SDL.

I'd be very happy to be pointed to a recommended way to handle SDL events in a Cocoa app!

**Comment by slime73** [comment]
I believe an AppDelegate+timer approach will drain the same event queue that SDL uses to query for some input events (since you get an `applicationDidFinishLaunching` event, the OS is sending events to you). Typically you'd initialize SDL and poll for events using SDL functions in `main()` without using any Cocoa code.

**Comment by bhallstein** [comment]
I see, thank you. So SDL takes in events from a lower level platform event queue. This was unexpected to me as I've previously written code to bridge cocoa events to cpp-land, the approach I took was to handle methods called by Cocoa on NSView e.g. `-keyDown:`. (This also explains why e.g. in SDL_cocoawindow.m the event handling in keyDown/keyUp is commented out).

I'm not tied to doing things inside of NSApplicationDelegate so de-Cocoa it and move everything into a main function. This also I guess has the advantage of being a more similar app structure to other platforms. Thanks for your help.

**Comment by bhallstein** [comment]
It seems like you might be able to stop the built-in event loop by calling `[NSApp stop]`, which might allow SDL to read the event stream again.

https://developer.apple.com/documentation/appkit/nsapplication/1428473-stop?language=objc

I might give this a go if I have time.
