### ISSUE TITLE
SDL_TEXTUREACCESS_TARGET + direct3D11 + 2.0.23 = specified texture is not a render target

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#5774]
This works in 2.0.22, so a recent change caused this. It works on opengl and direct3d, so specific to direct3D11.

**Comment by slouken** [comment]
Can you provide more context? Sample code or repro with the SDL test programs would be ideal.

**Comment by chalonverse** [comment]
I actually noticed a potential cause of this while working on the D3D12 renderer -- if SDL_HAVE_YUV is 0, the D3D11 renderer never creates a render target view. PR submitted in #5775.

**Comment by AntTheAlchemist** [comment]
Basically target textures don't work in D3D11 since 2.0.23. Here's some code that'll trigger it:
```
#include <SDL.h>
int main(int argc, char** argv) {
	SDL_SetHint(SDL_HINT_RENDER_DRIVER, "direct3d11");
	SDL_Init(SDL_INIT_VIDEO);
	SDL_Window* w;
	SDL_Renderer* r;
	SDL_CreateWindowAndRenderer(800, 600, SDL_WINDOW_ALLOW_HIGHDPI, &w, &r);
	SDL_Texture* t = SDL_CreateTexture(r, SDL_GetWindowPixelFormat(w), SDL_TEXTUREACCESS_TARGET, 100, 100);
	if (SDL_SetRenderTarget(r, t) != 0) {
		SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "error", SDL_GetError(), w);
	}
	return 0;
}

```

**Comment by slouken** [comment]
I'm not seeing this issue with the latest code. Can you confirm it's fixed by https://github.com/libsdl-org/SDL/commit/6f69bbc541ed170e60b66a75977e627d4f7c5455?

**Comment by icculus** [comment]
(You don't want to make textures with the window pixel format in any case. Might not be the error here but it's not a good idea.)

**Comment by AntTheAlchemist** [comment]
It's fixed in the latest code now, thanks. 

Noted about the window pixel format - I thought it was a good idea to match the target texture to the window's format. Which would be a better way to choose a pixel format for a target texture?
