### ISSUE TITLE
cannot find -lSDL2main

### ISSUE THREAD

**Issue by nevemlaci** [libsdl-org/SDL#5777]
While trying to compile using:

g++ main.cpp -L -lSDL2  -lSDL2main -o main

(all the files from the lib folder are placed in the same folder as my source file)

getting

g++ main.cpp -L -lSDL2  -lSDL2main -o main

May be a really nooby error that can be fixed by no effort. Also seems like if i switch them around, always the second one is the one not found. Hope this is just me being bad with cmd and not an actual bug.

**Comment by slouken** [comment]
Does this work?
`g++ main.cpp $(sdl2-config --libs) -o main`

**Comment by icculus** [comment]
-L needs a path after it. Try `-L .` if everything is in the same directory.

**Comment by nevemlaci** [comment]
Totally my bad, I solved it and happily using SDL, but thanks for the answers!

**Comment by slouken** [comment]
You're welcome!
