### ISSUE TITLE
SDL "Couldn't open" with Xbox Elite Series 2 controller on macOS

### ISSUE THREAD

**Issue by yamyamyamyamyam** [libsdl-org/SDL#5781]
I have an Xbox Elite Series 2 controller that works just fine in Steam as well as lots of macOS games with controller support, but the SDL library is having trouble with it for some reason.

Using this code to test the controller: https://gist.githubusercontent.com/adituv/b72ce0d0ee31e6382ae7c2136a4f7bc8/raw/2eb6a6bec8df46e814432f1905b710a00d089357/main.cpp

I get the output: ``Warning: unable to open game controller 0!  SDL Error: Couldn't open Bluetooth Low Energy_045e_0b22_0x120604a60``

Let me know what other steps I can take to debug this. Thanks.

I should also mention, I've tried re-pairing the controller as well as updating the controller's firmware. It still works fine with the same things on macOS, except the SDL library.

**Comment by jcm93** [comment]
I'm still having the same issue with the latest release of SDL. Would appreciate any acknowledgment or attempt to reproduce.

**Comment by slouken** [comment]
That's interesting that it works in Steam, because Steam uses SDL. :)

I don't have an Xbox Elite Series 2 controller at the moment. You'll have to run a debugger and see what's happening.

**Comment by jcm93** [comment]
Well, here's something interesting.

https://github.com/mikyll/SDL2-Controller-Tester

Running this code with lldb, the controller works just fine.

Without lldb, I get the same error.

**Comment by jcm93** [comment]
https://user-images.githubusercontent.com/6864788/189205896-7025f53a-99cf-442b-b325-f9a977998a4f.mp4

**Comment by slouken** [comment]
This is the issue:
https://nachtimwald.com/2020/11/08/macos-iohidmanager-permission-issue/
