### ISSUE TITLE
tiny autoconf-2.71 bug

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5815]
autoconf-2.71, as we started using, sets `CC` to `gcc -std=gnu11`
if possible (as if I asked it to but whatever), but due to a bug
(a typo) in it, it fails to do the same for CXX: after fixing, it
sets `CXX` to `g++ -std=gnu++11`

This is the patch that fixes it:
http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=commitdiff;h=f460883035ef849a2248b1713f711292ec19f4f0

FYI..

**Comment by slouken** [comment]
Is there an AC_* directive to disable that behavior? I don't necessarily want it to try to use gnu11 or gnu++11.

**Comment by sezero** [comment]
> Is there an AC_* directive to disable that behavior? I don't necessarily want it to try to use gnu11 or gnu++11.

Not to my (limited) knowledge.

**Comment by sezero** [comment]
> > Is there an AC_* directive to disable that behavior? I don't necessarily want it to try to use gnu11 or gnu++11.
> 
> Not to my (limited) knowledge.

Just went through ac2.71 man pages, couldn't find anything to block it.

**Comment by slouken** [comment]
Okay, I think we can leave it as-is for now. We can revisit if this is causing issues on some platform.
