### ISSUE TITLE
Environment SDL_AUDIODRIVER may have invalid values

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#5818]
If someone has used an SDL1 software or driver, on Windows, they may have set an environment variable of `SDL_AUDIODRIVER` to `dsound`, but it now has been renamed as `directsound`. Since the environment variables don't have a version number `SDL2_...`, you may hit an audio driver system that doesn't initialize.

https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html

It would be useful if `SDL_InitSubSystem(SDL_INIT_AUDIO)` would not fail in an invalid environment variable, and instead attempt known good audio drivers before failing - like wasapi, directsound and winmm in Windows, but not dummy or disk.

**Comment by sulix** [comment]
We do handle the difference between "pulse" and "pulseaudio" as of #4693 — perhaps something similar could be done (though avoiding directsound may be worth doing on more modern systems…)

**Comment by ericoporto** [comment]
It would be good if SDL3 has these versioned to avoid clashing (e.g.: `SDL3_AUDIODRIVER` )

**Comment by sezero** [comment]
>  (though avoiding directsound may be worth doing on more modern systems…)

sdl12-compat probably needs that

**Comment by slouken** [comment]
> We do handle the difference between "pulse" and "pulseaudio" as of #4693 — perhaps something similar could be done (though avoiding directsound may be worth doing on more modern systems…)

Yep, I'll go ahead and implement this.
