### ISSUE TITLE
hidapi compiler issue on Android Studio

### ISSUE THREAD

**Issue by superfury** [libsdl-org/SDL#5825]
When I try to put any version newer than 2.0.16 into my own project ( https://bitbucket.org/superfury/unipcemu.git), using the steps mentioned in the manual for Android Studio compilation (It's running it in a directory structure that's compatible with the 2.0.0 releases of SDL2 and up), it starts sputing out the error that it can't compile the 'hidapi' module.

Anyone knows how to resolve this without breaking the Android Studio project (and keep it's compatibility with older versions of Android compilation)?

Btw, as a side note, is the 2.0.22 mouse change (with regard to clicking) compatible with the older SDL2 apps? It sounds like clicking anywhere on the screen causes some kind of mouse capturing by the app (like putting the mouse in relative mode, which is usually done by the app itself)? Or am I reading that incorrectly?

**Comment by slouken** [comment]
The hidapi module no longer exists, you can remove any references to it in your project.

**Comment by superfury** [comment]
OK. It seems that when simply replacing the files and java files in the Android studio project (src folder, include folder, Android.mk file and the org/libsdl/app java folder), Android Studio somehow remembers it was using the hidapi module in the project. So it keeps trying to compile it even though the text files don't mention them as shared objects anymore.

The solution was to (after updating) clean the project, invalidate the caches of Android Studio, re-sync and then compile the app again. That seems to have gotten rid of the Android Studio's idea that it should compile the now nonexistent module and perform the SDL2 compilation of versions past 2.0.16.
That might be helpful information for people trying to update their projects from SDL2 2.0.16 or below to the later versions.

So back to my other question:
I'm still wondering about the mouse changes of 2.0.22 though (which why I keep it at 2.0.20 atm). Does it affect behaviour of mouse clicking in 2.0.16-compatible apps or when updating the SDL dll to the latest version when built for said version?
