### ISSUE TITLE
Struct SDL_BlitMap exposed in API but not defined

### ISSUE THREAD

**Issue by shinedeveloper** [libsdl-org/SDL#5828]
Struct `SDL_Surface` contains this field:
~~~
    /** info for fast blit mapping to other surfaces */
    struct SDL_BlitMap *map;    /**< Private */
~~~

`SDL_BlitMap` is not defined in the API as a standalone element, only inline in the `SDL_Surface` typedef. The actual definition is in the implementation in `/src/video/SDL_blit.h`, but that is not part of the API. It is inconsistent with the rest of the API. I suggest either to replace it with `void *map` or define the `SDL_BlitMap` as an opaque pointer similar to other opaque pointers, such as SDL_Texture:
~~~
struct SDL_Texture;
typedef struct SDL_Texture SDL_Texture;
~~~

**Comment by icculus** [comment]
Is this all you're looking for here?

```diff
diff --git a/include/SDL_surface.h b/include/SDL_surface.h
index 441237617..838de654e 100644
--- a/include/SDL_surface.h
+++ b/include/SDL_surface.h
@@ -61,6 +61,8 @@ extern "C" {
  */
 #define SDL_MUSTLOCK(S) (((S)->flags & SDL_RLEACCEL) != 0)
 
+typedef struct SDL_BlitMap SDL_BlitMap;  /* this is an opaque type. */
+
 /**
  * \brief A collection of pixels used in software blitting.
  *
@@ -88,7 +90,7 @@ typedef struct SDL_Surface
     SDL_Rect clip_rect;         /**< Read-only */
 
     /** info for fast blit mapping to other surfaces */
-    struct SDL_BlitMap *map;    /**< Private */
+    SDL_BlitMap *map;           /**< Private */
 
     /** Reference count -- used when freeing surface */
     int refcount;               /**< Read-mostly */
```

**Comment by shinedeveloper** [comment]
Well, yes. Thank you.

There is also 1 more point, `SDL_Surface` struct has fields with both documentation comments on top of them `/**` as well as inline `/**<`. Would it be possible to merge it to one comment, please? This is the only place in the `/include` codebase where this happens. Or shall I make a pull request with the suggested change?

**Comment by icculus** [comment]
> There is also 1 more point, `SDL_Surface` struct has fields with both documentation comments on top of them `/**` as well as inline `/**<`.

It's legitimate Doxygen commenting; one is the general comments for the struct and the other documents specific fields. 

Doxygen format is used to bridge most of these headers to our wiki (you can make changes to the documentation in either place and it'll update the other automatically). As we might extend that bridge to include structs and not just functions, I'd rather these comments stay (and eventually, more be added).
