### ISSUE TITLE
using SDL_AudioInit doesn't increment ref count

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#5841]
Whenever `SDL_Init` or `SDL_InitSubSystem`, subsequent calls to initialize the same subsystem will be ref counted, and not return error, assuming the subsystem has been successfully initialized.

You can override an SDL specific config for audio drivers by using directly `SDL_AudioInit`. 

Unfortunately, SDL_AudioInit doesn't increment it's `SDL_SubsystemRefCount`, and so subsequent calls to `SDL_InitSubSystem(SDL_INIT_AUDIO)` will simply error. Ideally, SDL_AudioInit should increment the refcount or there should be an extra parameter to `SDL_InitSubSystem` to specify the audio driver to use.

This is following a line in the docs:

https://github.com/libsdl-org/SDL/blob/118a2189fb203dedc274848833b5431273cb1db5/include/SDL_audio.h#L314

If it's not supposed to be used this way, then the documentation needs to be updated.

**Comment by icculus** [comment]
@slouken I'm thinking this refcount issue should just be documented for SDL2 instead of changed (and maybe the direct init functions should be removed for SDL3, so there's only an SDL_Init() entry point). Agree?

**Comment by ericoporto** [comment]
But how can one set the audio driver in this case?

**Comment by slouken** [comment]
I think we should probably document that you're not supposed to mix `SDL_AudioInit()` and `SDL_InitSubSystem()`. The former gives you more fine grained control, but you need to manage initialization and shutdown in that case.

@ericoporto, does that solve your problem here?

**Comment by ericoporto** [comment]
Erh, I have no clue actually, I think I will open the issue in the library I am using and see how to go from there in this case
