### ISSUE TITLE
UWP build warnings

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5842]
From github CI logs:

```
D:\a\SDL\SDL\src\SDL.c(109,5): warning C4013: '_exit' undefined; assuming extern returning int [D:\a\SDL\SDL\build\SDL\SDL2.vcxproj]

D:\a\SDL\SDL\src\video\winrt\SDL_winrtvideo.cpp(527,1): warning C4973: 'Windows::UI::ViewManagement::IApplicationView::IsFullScreen::get': marked as deprecated [D:\a\SDL\SDL\build\SDL\SDL2.vcxproj]
D:\a\SDL\SDL\src\video\winrt\SDL_winrtvideo.cpp(527,1): message : Message: 'To check full screen mode, use IsFullScreenMode. To check if the view is adjacent to both edges, use AdjacentToLeftDisplayEdge and AdjacentToRightDisplayEdge. For more info, see MSDN.' [D:\a\SDL\SDL\build\SDL\SDL2.vcxproj]
```

**Comment by sezero** [comment]
Who's our UWP / WinRT maintainer?

**Comment by slouken** [comment]
@DavidLudwig, are you still working on UWP / WinRT support?

**Comment by sezero** [comment]
The `_exit undefined` warning is still not resolved.

**Comment by slouken** [comment]
I'm not getting it using the 2019 SDK, and it's specifically called out as a function you should not call in UWP applications in the MSDN documentation, so I think it's fine to leave it as-is.

**Comment by sezero** [comment]
> I'm not getting it using the 2019 SDK,

The CI runs using cmake + vs2022 still emit the warning:
https://github.com/libsdl-org/SDL/actions/runs/3490620314/jobs/5842279641#step:5:113

> and it's specifically called out as a function you should not call in UWP applications in the MSDN documentation,

Yes, that's correct: hence the warning, because we _are_ using it.

**Comment by slouken** [comment]
If it bugs you, you can add an extern function declaration for UWP builds. This is fine to put in for 2.26.

**Comment by sezero** [comment]
> If it bugs you, you can add an extern function declaration for UWP builds.

The _warning_ doesn't bug me. What bugs me is if/when they remove it completely
from uwp libs. Do we not have any equivalent(ish) apis to replace it?

**Comment by sezero** [comment]
OK then.
