### ISSUE TITLE
Faulty double-click logic with warped mouse

### ISSUE THREAD

**Issue by Photosounder** [libsdl-org/SDL#5843]
There's a problem with the logic of SDL's click count (`event.button.clicks`) detection when in warp mode (that means `SDL_SetRelativeMouseMode(1)` and `SDL_WarpMouseInWindow(NULL, ..., ...)`). It detects double clicks (`event.button.clicks` >= 2) in that mode despite the mouse travelling long distances between clicks.

The problem appears to lie in [`SDL_PrivateSendMouseButton()`](https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_mouse.c#L625), as what determines a double click is the time since the last click and the difference in absolute position (`mouse->x` and `y`) since the previous click. Since the mouse is warped the difference appears to be below the threshold and a double click is detected despite the considerable real distance between each click. Were I to fix this myself I would add a `int xd_acc, yd_acc;` to the `SDL_Mouse` struct, add every `xdelta` and `ydelta` to them at every mouse movement event and reset `xd_acc` and `yd_acc` to 0 after every time a click is detected, so that instead of using `SDL_abs(mouse->x - clickstate->last_x) > mouse->double_click_radius` as a condition we'd have `SDL_abs(mouse->xd_acc) > mouse->double_click_radius`.

**Comment by slouken** [comment]
SDL relative mode no longer uses warping, so this might be fixed for you? If not, can you describe the sequence of events that would result in a warp out and back where we shouldn't consider this a double click? We no longer generate delta motion for mouse warping in relative mode, so we can't use that to detect this case.

**Comment by Photosounder** [comment]
I don't think this has anything to do with the method used for the relative mode, it has to do with how SDL decides there's a double click in relative mode. Tested with the latest commit of the SDL2 branch:
[20241224_004613 Q36 -1p.webm](https://github.com/user-attachments/assets/0219ec63-eba1-4ada-b82b-a5047fdce734)

**Comment by slouken** [comment]
I'm not sure what's happening in the video. Are you warping the mouse? Can you provide steps using the SDL testwm test program? You can toggle relative mode with Ctrl-R, and passing the `--info event` command line parameter will show all the events (including click count).

**Comment by Photosounder** [comment]
My original post is pretty clear so I'm not sure what I can add to it. What happens in the video is that when only the cursor moves it's normal mode, and when the cursor is in the middle of the screen but everything else moves it's 
>SDL_SetRelativeMouseMode(1) and SDL_WarpMouseInWindow(NULL, ..., ...)

I only have the same problem with `testwm2.exe` in relative mode when `SDL_GetMouseState` reports that I'm in a corner, for instance:

```
INFO: SDL EVENT: Mouse: button 1 pressed at 639,479 with click count 1 in window 1
INFO: SDL EVENT: Mouse: button 1 released at 639,479 with click count 1 in window 1
INFO: SDL EVENT: Mouse: button 1 pressed at 639,479 with click count 2 in window 1
INFO: SDL EVENT: Mouse: button 1 released at 639,479 with click count 2 in window 1
```
even though my mouse moved between the two clicks (in the corner's direction so that `SDL_GetMouseState()` would report the same coordinates despite the movement). In the case of my program since I use `SDL_WarpMouseInWindow(NULL, ..., ...)` `SDL_GetMouseState()` always reports the center of the window (something like `960, 540`) so what happens only in corners in `testwm2.exe` happens all the time in my program, and if I remove `SDL_WarpMouseInWindow(NULL, ..., ...)` from my program then the problem of double clicks being detected only occurs if `SDL_GetMouseState()` reports that I'm in a corner and that I move further in the same direction so the reported coordinates of the second click are the same and therefore it's detected as a double click despite the movement between the two clicks which is not taken into consideration since only changes in the coordinates reported by `SDL_GetMouseState()` (which don't make much sense in relative mode) are considered.

Therefore, as suggested in my original post, it would be probably adequate, when relative mode is enabled, to stop using absolute coordinates to decide if a click is repeating but rather accumulate movement deltas since the last click. The problem is [this](https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_mouse.c#L890):

```
                if (now >= (clickstate->last_timestamp + mouse->double_click_time) ||
                    SDL_fabs((double)mouse->x - clickstate->last_x) > mouse->double_click_radius ||
                    SDL_fabs((double)mouse->y - clickstate->last_y) > mouse->double_click_radius) {
                    clickstate->click_count = 0;
                }
```
It shouldn't use `mouse->x` and `mouse->y` because this doesn't work as intended in (literal) corner cases or when warping the mouse constantly because then their values fail to change despite the mouse moving.

**Comment by slouken** [comment]
If your mouse is in the corner, then you're literally clicking the same point over and over again, which to me sounds like we should be incrementing the click count.

When you're warping the cursor, SDL_GetMouseState() should report the location that you're warping to. I'm guessing in this case, you're warping every frame, getting the delta and then warping to the center again?

**Comment by slouken** [comment]
Let me try your corner case. I think I understand what you're getting at here.

**Comment by Photosounder** [comment]
Please do, but the reason why this shouldn't count as a double click is that in relative mode, at least in my case, there are no edges, no corners, the mouse moves indefinitely, the coordinates reported by `SDL_GetMouseState()` mean nothing anymore, only movement deltas matter (that to me is kind of the whole point of this mode). That's how it is when you have something like a 3D game with a free camera, you can move the mouse endlessly, there are no more edges that stop the mouse. Therefore invisible edges shouldn't affect double click detection.

**Comment by slouken** [comment]
Yep, that makes sense. This is a little tricky when you think about multiple buttons and multiple mice, so I'm thinking some more about it.

**Comment by slouken** [comment]
So in the relative mode case, conceptually we want a point on an infinite plane, and we want to push that point around and check to see if the new point is outside the click radius from the old point. However, in relative mode we may be getting raw mouse deltas, which don't correspond to pixels, and even if they do, we might be rendering on a UI with scaling such that our double click radius doesn't make any sense. That's _probably_ okay, but just something to keep in mind.

In the warping case, you're physically moving the mouse cursor from one location to another, so that translation should be taken into account for double clicks. For example, if I click on a button in the lower right and then the application warps the mouse to the upper left, I shouldn't double click on the upper left.

**Comment by slouken** [comment]
Can you try out that PR and see if it helps your case?

**Comment by Photosounder** [comment]
The code looks correct thank you, hopefully this will be backported to SDL2 which I still use. However I cannot test this. I just tried to build the `main` branch (usually I'm on the `SDL2` branch) and it doesn't work at all. My steps:

- Clone the `main` branch in a new folder
- Open SDL3\VisualC\SDL.sln (it opens with VS 2022 17.11.5)
- Menu BUILD > Build Solution
- This happens:
![2024-12-24 11 12 57](https://github.com/user-attachments/assets/4f53b7cd-4379-4d77-820d-6226a4e2df86)

**Comment by slouken** [comment]
What Windows SDK do you have?

**Comment by Photosounder** [comment]
![2024-12-24 16 25 51](https://github.com/user-attachments/assets/406b8e4d-de35-477c-9364-0579ca7f5424)

**Comment by slouken** [comment]
What is the latest installed version? :)

**Comment by Photosounder** [comment]
Apparently it's `10.0.22000.0`. When I set it manually to `10.0.22000.0` I get this problem, but when I switch to `10.0.19041.0` it compiles fine 🤔

**Comment by slouken** [comment]
Interesting. I'll update my SDK and try to reproduce here.

**Comment by slouken** [comment]
Okay, try now?

**Comment by Photosounder** [comment]
It compiles 👍. It might be a while before I can test SDL3 though because I haven't used it since early 2023 and many things have changed so I have lots of code to fix.

**Comment by slouken** [comment]
Okay, I'll move this bug out of the milestone until you have a chance to test it.

**Comment by Photosounder** [comment]
Okay I fixed all my compilation errors and I can confirm that the problem is fixed.

**Comment by slouken** [comment]
Great, thanks!
