### ISSUE TITLE
Rendertarget is rendering incorrectly on psvita.

### ISSUE THREAD

**Issue by baiXfeng** [libsdl-org/SDL#5844]
@isage I compiled with the latest version of the sdl library and it does not render the rendertarget correctly on psvita, I have created a project to restore this problem.
https://github.com/baiXfeng/sdl2-test

**Comment by isage** [comment]
I'll take a look. It looks like texture format conversion problem, with `SDL_PIXELFORMAT_ABGR8888` for rendertarget everything works fine, because we use SCE_GXM_COLOR_FORMAT_A8B8G8R8 for sceGxmColorSurfaceInit (which is vita'a analogue of render target texture).
