### ISSUE TITLE
GDK build requires XCurl.dll

### ISSUE THREAD

**Issue by TheSpydog** [libsdl-org/SDL#5856]
When building for GDK as a DLL, it outputs two .dll files -- SDL2.dll and XCurl.dll. If SDL2.dll is copied to a game's output directory without XCurl.dll, it will crash with a cryptic exception message.

If this is intentional, XCurl should be added to [the list of required DLLs](https://github.com/libsdl-org/SDL/blob/main/docs/README-gdk.md#5-required-dlls) in the documentation. However I'm not sure that this is supposed to be output alongside SDL. Maybe this is some weird side effect of the Gaming.Desktop.x64 build system?

cc @chalonverse

**Comment by chalonverse** [comment]
Yes, it seems like XCurl.dll is required, because it is referenced by the Xbox services DLL. When compiling the test programs it doesn’t come up since it outputs to the same directory as the test program.

I think it makes sense to just add it to the list of required dlls in the docs

**Comment by flibitijibibo** [comment]
See #5857
