### ISSUE TITLE
 windows 7 windows key (eg: SDL_SCANCODE_LGUI) keyboard event error

### ISSUE THREAD

**Issue by zzhtom** [libsdl-org/SDL#5858]
**test machine environment：** windows7 
**SDL2 version：**  2.0.22

Question one:
for example, when LGUI key is pressed three times  in a row, SDL2 can receive two SDL_KEYDOWN events, missing one.

Question two：
When using the following function to set the keyboard hook function

```
SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_hook_cb, GetModuleHandle(NULL), 0);
```

KeyboardProc callback function：

```
 LRESULT CALLBACK keyboard_hook_cb(int code, WPARAM wparam, LPARAM lparam)
{
        KBDLLHOOKSTRUCT *hooked = (KBDLLHOOKSTRUCT *)lparam;
        DWORD dwmsg = (hooked->flags << 24) |  ((hooked->scanCode & 0xff) << 16) | 1;
       HWND win = NULL;
       SDL_SysWMinfo info;
       SDL_GetWindowWMInfo(sdl2_window->get_window(); // sdl2_window  by SDL_CreateWindow create
       win = info.info.win.window;

       switch (hooked->vkCode) {
       case VK_LMENU:
       case VK_RMENU:
               break;
       default:
               SendMessage(win, wparam, hooked->vkCode, dwmsg);
               return 1;
       }

    return CallNextHookEx(NULL, code, wparam, lparam);
}

```

Pressing the LGUI key don't release (SDL_KEYUP) it, when another key is pressed  LGUI key will be released(SDL_KEYUP).

other instructions：

when use SDL2-2.0.14 everything will be fine

**Comment by cgutman** [comment]
You should use `SDL_SetWindowKeyboardGrab()` instead of writing your own keyboard hook. SDL already has one.

**Comment by zzhtom** [comment]
> You should use `SDL_SetWindowKeyboardGrab()` instead of writing your own keyboard hook. SDL already has one.

Yes, I used `SDL_SetWindowKeyboardGrab`, but it is not able to capture all key events in windows environment, such as letters key.
so the keyboard hook is used.

**Comment by cgutman** [comment]
I'm not sure what you mean by "letters key", but please submit a PR if there are keys that SDL doesn't capture.

SDL's keyboard hook code is here: https://github.com/libsdl-org/SDL/blob/main/src/video/windows/SDL_windowsevents.c#L553-L613

**Comment by zzhtom** [comment]
> I'm not sure what you mean by "letters key", but please submit a PR if there are keys that SDL doesn't capture.
> 
> SDL's keyboard hook code is here: https://github.com/libsdl-org/SDL/blob/main/src/video/windows/SDL_windowsevents.c#L553-L613

Thanks for the reply.

After investigation, the reason was finally found.
It is caused by the installation of a third-party input method software (http://qq.pinyin.cn/). If the input method is removed, the SDL2 keyboard will work successfully.

If there are no other problems, I will close the issue tomorrow.

Thanks again
