### ISSUE TITLE
audio: Add support for 2.1, 4.1 configurations

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#5860]
I'm 99% sure this has been discussed before, but I couldn't find the report here...

Either way: SDL_GetAudioDeviceSpec has actually made this a bit more urgent, as OSes can now return these channel configurations, and when passed back to SDL unmodified it hits hardcoded errors when given 3 or 5 as a `channels` value. This has caused a mild spike in audio device open failures for applications that use the device spec, and working around it requires something obnoxious like [this](https://github.com/FNA-XNA/FAudio/commit/f4d7bcfcf5f7ab0d3d431b35aeb68d65a8098789).

**Comment by slouken** [comment]
Yep, that sounds like a good idea, do you want to submit a PR?

**Comment by flibitijibibo** [comment]
No objection here, I can still review and test at least!

**Comment by icculus** [comment]
So I'm working on this, and these are nasty but not impossible to add, but when SDL_GetAudioDeviceSpec reports that the system has one million unique speakers plugged into it, we're going to have to clamp it to something we actually support, right?

We shouldn't be adding every format possible, including ones no one uses and ones we can't test, just in case it shows up.

**Comment by icculus** [comment]
So then I guess my question is: are 2.1 and 4.1 crazy?

**Comment by flibitijibibo** [comment]
2.1 definitely isn't (I used to have this config!), 4.1 might be about as plausible as 5.0? When I was looking at this, I figured it might be enough to treat 2.1/3.0 and 4.1/5.0 as the same, since Center and LFE would be in the same spot and it's far more likely LFE would have a low-pass filter, unlike a center channel which would only be filtered if it was connected to an external system with filters enabled.

**Comment by icculus** [comment]
Okay, just thinking out loud here.

We have a bug pending that's been discussed internally at Valve, that our channel conversion isn't great as-is...it takes some heroic measures to try to duplicate and average channels into various surround sound configs, and that this is generally a wrong course of action, causing weird artifacts and unexpected output.

We've also got a problem that the way we do this is chain through various conversions (mono converts to stereo, then that buffer might convert that buffer in-place again to get to 5.1, and _again_ to get to 7.1, etc). Not only is this inefficient, the silly SDL_AudioCVT struct only has room for 10 filters, and reuses some of those slots to manage resampler state, and I _think_ stuffing 2.1 and 4.1 in here is either going to overflow that or hit the limit in pathological cases.

Not to mention...how do we go from stereo to 5.1? Do we pass through 2.1 on the way, or 4.1? Or do we just write a custom converter for each thing?

There are 8 possible channel layouts when we add 2.1 and 4.1 here, so doing by-hand conversion is 64 separate functions...times however many SIMD versions we want to do.

I haven't decided how I want to handle this yet, but the current conversion code seems like it needs a reworking. Gonna think on this a little today and decide what to do, and how to balance that against avoiding these sort of serious overhauls before SDL3.  :/

**Comment by flibitijibibo** [comment]
This is the table that Microsoft apparently uses in XAudio2, for basic conversion:

https://github.com/FNA-XNA/FAudio/blob/master/src/matrix_defaults.inl

For the most part it's really boring, for example when doing 2->6 it just uses left/right and completely ignores all the other channels, but the weird ones like 3 and 4 get kind of odd. Maybe there's something useful in there, no idea.

Where conversion _might_ get interesting is FAudio's mix functions, which are half mixer and half channel conversion functions when combined with the voice output matrix:

https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio_internal_simd.c#L1279

It works for arbitrary channel counts but it's a lot nicer when we have specialized paths (be it scalar or SIMD). Still, it needs that matrix... I'm really surprised this isn't specified in some ancient document somewhere.

**Comment by icculus** [comment]
Yeah, this is going to be a pain in the butt to retrofit well into SDL_BuildAudioCVT. I'm just going to fill in all the variations for 2.1 and 4.1, because it's not something we want to chain together with the existing converters, and call it a day for now.

**Comment by icculus** [comment]
I gave up and started rewriting this code late last week, almost there.

One notable thing, though, is the current channel layouts:

* 2 channels (stereo) layout: FL+FR
* 3 channels (2.1) layout: FL+FR+LFE
* 4 channels (quad) layout: FL+FR+BL+BR
* 5 channels (4.1) layout: FL+FR+LFE+BL+BR
* 6 channels (5.1) layout: FL+FR+FC+LFE+BL+BR
* 7 channels (6.1) layout: LFE+FC+FR+SR+BC+SL+FL
* 8 channels (7.1) layout: FL+FR+FC+LFE+BL+BR+SL+SR

That 6.1 layout is straight-up goofy. I _think_ we added this for that person with the weird Kinect audio array, but I'm honestly thinking we should change this to match everything else (and, if the Kinect pops up again, we should add code in WASAPI or whatever to detect the special case and swizzle to/from SDL's layout).

I assume literally nothing else uses 6.1 at the moment (if ever), but when something does, it's going to be surprised by this layout.

**Comment by slouken** [comment]
Yes, that was added for Kinect:
https://github.com/libsdl-org/SDL/issues/4458

Maybe @hanseuljun is available to do testing?

**Comment by hanseuljun** [comment]
First, thanks a lot for the 6.1 layout support that the SDL team has added. It really helped me a lot!

About the layout, I agree it is really weird and matching other layouts does make sense. Part of me thinks it is even okay to just make 6.1 FL+FR+FC+LFE+BC+SL+SR and tell app developers using Kinect to go figure given how nobody uses Kinect...

When casually tested (by using only one channel out of the seven at a time), the current implementation of SDL worked well. By worked well, I mean the first channel corresponded to the LFE mic, second to FC, and so on...

**Comment by icculus** [comment]
First shot at reworking this code is in a draft pull request. It's almost ready, I just wanted to demonstrate proof-of-life over here because it took so long.  :)
