### ISSUE TITLE
Inconsistent value of "batching" in SDL_CreateRenderer

### ISSUE THREAD

**Issue by chalonverse** [libsdl-org/SDL#5861]
I ran into an issue with the `batching` bool in `SDL_CreateRenderer`, which I'm not sure if it's intentional or not, but it seems weird to me. The variable is initialized to `SDL_TRUE` on the declaration at line 943.

If the renderer is selected through to the `SDL_HINT_RENDER_DRIVER` path or because `SDL_CreateRenderer` gets an `index` to the requested renderer, `batching` gets set to `SDL_FALSE`. _But_ if the renderer is selected as just the default renderer for the platform, `batching` stays as `SDL_TRUE`: https://github.com/chalonverse/SDL/blob/main/src/render/SDL_render.c#L993-L996

I noticed this because the DirectX 12 renderer (and probably the DirectX 11 renderer) will _not_ work if batching is enabled. For Xbox support, DirectX 12 is the only/default renderer, and so it goes into the path where it keeps `batching` as `SDL_TRUE`. You wouldn't notice this on Windows because the only way to enable the renderer goes through a path that sets batching to `SDL_FALSE`.

I suppose I could just set `SDL_HINT_RENDER_BATCHING` to "0" in the initialization of the DirectX 12 renderer to fix this, but I feel that the inconsistent logic should be looked at.

An easy fix would just be to initialize it to `SDL_FALSE` and force it to be universally opt-in, but I'm not sure if that's exactly what's wanted?

**Comment by slouken** [comment]
This is intentional. The idea is that if you're selecting a specific renderer, you may be doing other rendering in addition to SDL's rendering and so we disable batching for compatibility with previous behavior.

We should probably fix rendering if batching is enabled on D3D11/12. That's intended to be a working code path.

**Comment by chalonverse** [comment]
Oh, okay -- I confirmed that batching does work correctly for DirectX 11. It seems like the only reason it doesn't work for DirectX 12 is because of the vertex buffer size limit, so I will look at fixing that.
