### ISSUE TITLE
Android app does not run (exits immediately)

### ISSUE THREAD

**Issue by maxqxam** [libsdl-org/SDL#5864]
I am trying to start android development with C++ and SDL2 according to [this](https://github.com/libsdl-org/SDL/blob/main/docs/README-android.md) and [this](https://lazyfoo.net/tutorials/SDL/52_hello_mobile/index2.php) tutorial.

I run "./androidbuild.sh com.example.com ~/Downloads/lazyfootest/main.cpp" and after that a project inside the "build" folder gets created.
I enter that directory ("./build/com.example.com") and run "./gradlew assembleDebug".
The build process ends successfully and an "app_debug.apk" file gets created.

So I install that in my phone and when I try to run it, after showing a black screen for about half a second the program exits and thats it.

I repeated the same above process with "./test/testgles.cpp" which you mentioned in the tutorial, and it works and the program builds and runs successfully. 

What is the problem here? I couldn't find the answer anywhere and even asked it on stackoverflow but no help, so I asked it here although it is highly likely not a bug.

You can find the source code I'm trying to build in the second link. 

Thank you for spending your time and experience and reading this .

**Comment by slouken** [comment]
Try using adb logcat to catch the log when it fails?

**Comment by maxqxam** [comment]
Hi. I couldn't do it with ```adb logcat``` due to other applications log's spamming the console. so I used ```pidcat com.yourexample.com``` I hope that is okay?

The  Log file is attached. 

[pidcatLog.txt](https://github.com/libsdl-org/SDL/files/9031040/pidcatLog.txt)

**Comment by 1bsyl** [comment]
it looks like it cannot load your images
```
                SDL/APP  I  Unable to load image 52_hello_mobile/hello.bmp! SDL Error:
                         I  Failed to load splash texture!
                         I  Failed to load media!
                    SDL  V  Finished main function
```

**Comment by maxqxam** [comment]
@1bsyl 

I'm not sure if that is the case... 
because I created another project that only uses a ```SDL_Window``` and a ```SDL_renderer``` and I get the same result. In this minimal properties example I only tried to color the background using ```SDL_RenderClear```.



This is the log file when running it: [minimalTest.txt](https://github.com/libsdl-org/SDL/files/9031424/minimalTest.txt)

This second log file is much smaller than the first one and it contains this lines which seem important:
```
 E  nativeRunMain(): Couldn't find function SDL_main in library /data/app/~~onN4MTENvbHjiGNbI0cLzQ==
                            /com.yolo.test-4_k6bcH139ba-qRMrdey1g==/lib/arm64/libmain.so

 E  ioctl c0044901 failed with code -1: Invalid argument

```

**Comment by 1bsyl** [comment]
in your case, it searches for "SDL_main()", not main() !

**Comment by maxqxam** [comment]
@1bsyl  I don't get it. Are you saying if I change the ```main()``` function inside ```main.cpp``` to ```SDL_main()``` I should be good to go? because I tried changing it to ```SDL_main()``` but I get the same results!

```
E    nativeRunMain(): Couldn't find function SDL_main in library /data/app/~~gvhpQEv2YV_OO-OXpS6rfw==
                            /com.yolo.test-eprvH0V4Msp8Y81kE_NraQ==/lib/arm64/libmain.so
```

**Comment by 1bsyl** [comment]
@maxqxam 
Can be a compilation issue ? is it inside libmain.so ?
can you do "objdump -T libmain.so" to see if the symbol is there ?

**Comment by maxqxam** [comment]
@1bsyl  

In the project folder I did ```objdump -T libmain.so``` and I got ```objdump: 'libmain.so': No such File```.

But when doing this ```find .  | grep libmain.so``` I get:
```
./app/build/intermediates/cxx/Debug/4v2w3d4c/obj/local/arm64-v8a/libmain.so
./app/build/intermediates/cxx/Debug/4v2w3d4c/obj/local/armeabi-v7a/libmain.so
./app/build/intermediates/cxx/Debug/4v2w3d4c/obj/local/x86/libmain.so
./app/build/intermediates/cxx/Debug/4v2w3d4c/obj/local/x86_64/libmain.so
./app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libmain.so
./app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libmain.so
./app/build/intermediates/ndkBuild/debug/obj/local/x86/libmain.so
./app/build/intermediates/ndkBuild/debug/obj/local/x86_64/libmain.so
./app/build/intermediates/merged_native_libs/debug/out/lib/arm64-v8a/libmain.so
./app/build/intermediates/merged_native_libs/debug/out/lib/armeabi-v7a/libmain.so
./app/build/intermediates/merged_native_libs/debug/out/lib/x86/libmain.so
./app/build/intermediates/merged_native_libs/debug/out/lib/x86_64/libmain.so
./app/build/intermediates/stripped_native_libs/debug/out/lib/arm64-v8a/libmain.so
./app/build/intermediates/stripped_native_libs/debug/out/lib/armeabi-v7a/libmain.so
./app/build/intermediates/stripped_native_libs/debug/out/lib/x86/libmain.so
./app/build/intermediates/stripped_native_libs/debug/out/lib/x86_64/libmain.so
```

**Comment by slouken** [comment]
That output means SDL_main is a C++ function. 
Try declaring your main function like this:
```c++
#include "SDL_main.h"

extern "C"
int main(int argc, char *argv[])
{
...
}
```

**Comment by maxqxam** [comment]
@slouken 
@1bsyl
Yes! It finally worked thank you!! 
I was trying to fix this for weeks now... 
thanks for spending your time and experience!

**Comment by slouken** [comment]
You're welcome!
