### ISSUE TITLE
Build official binary distribution packages for Windows ARM

### ISSUE THREAD

**Issue by RockLakeGrass** [libsdl-org/SDL#5882]
I want the official Windows ARM binary distribution package built

**Comment by slouken** [comment]
@madebr, can we add ARM builds to CI and the release build action?

**Comment by madebr** [comment]
Sure we can.
How would you like to distribute them?
I propose to only add them to the `SDL3-devel-3.1.2-VC.zip` archive to avoid people accidentally downloading an arm32 library instead of x86.

**Comment by slouken** [comment]
I think we can have separate SDL-*-x86/x64/arm64.zip for the DLLs, and then include them in an arm64 subdirectory in the devel-*VC.zip like we do for the 32 and 64-bit x86 targets.

**Comment by madebr** [comment]
An arm64 VC binary is added in 86b2f441c

- An additional archive (`SDL3-3.1.2-win32-arm64.zip`), containing an arm64 `SDL3.dll` is built
- `SDL3-devel-3.1.2-VC.zip` adds a `arm64` folder contaning arm64 versions of `SDL3.dll`, `SDL3.lib`, `SDL3_test.lib` and `SDL3.pdb`. The CMake configuration files have also been modified accordingly.

ci: https://github.com/madebr/SDL/actions/runs/9199070391

**Comment by slouken** [comment]
Thanks!
