### ISSUE TITLE
Android: Rendering bugs on large textures using SDL_RenderCopyF

### ISSUE THREAD

**Issue by crudelios** [libsdl-org/SDL#5884]
Hello,

I'm having a strange issue on Android, which I don't know if it's really related to SDL or to Android's renderer, but I'm leaving here for better testing.

I'm contributing to a game which uses texture atlases to improve performance. This texture atlas is 4096x4096 in size.

When a texture needs to be drawn, the game uses the image's `x` and `y` position in the atlas texture, as well as its width and height, then calls `SDL_RenderCopyF` with those values as the source `SDL_Rect`. The destination `SDL_FRect` is exactly the same width and height as the source image, so there's no scaling.

However, what happens is, when the `x` and `y` values are large enough, the renderer doesn't fetch the correct coordinates, instead "missing" the required value by one or more pixels. In fact, the larger the `x` or `y` value, the larger the coordinate discrepancy.

This causes the game to draw parts of different images, which it fetches from the wrong coordinates in the atlas texture.

Here's how it looks (note that in the game, fonts are also regular images):

![Screenshot_20220703-210645_Opera](https://user-images.githubusercontent.com/6518876/177166080-961cb43b-ad6b-40f3-bb68-f5909c87e667.jpg)

This is how it should look:

![correct](https://user-images.githubusercontent.com/6518876/177166439-cce9aca0-80d4-44be-aae6-05aeb8d8a9af.jpg)

I can work around this problem by making the maximum atlas size 1024x1024 and using more, smaller, atlas images. However, that causes a performance reduction because of the more frequent rendering context changes. Besides, that isn't a proper fix.

For reference, this only happens on Android. I tested on a Samsung Galaxy S10 and a Samsung Galaxy Tab A (2016).

Thanks!

**Comment by 1bsyl** [comment]
ok!
btw, there is also an API to get the maximum texture size: 

https://github.com/libsdl-org/SDL/blob/main/include/SDL_render.h#L84
https://github.com/libsdl-org/SDL/blob/main/include/SDL_render.h#L171

**Comment by crudelios** [comment]
I just tested on android.

Using `SDL_RenderCopy` instead of `SDL_RenderCopyF` makes no difference. If anything it looks even worse.

However, using the software renderer works, albeit very slowly at 5fps (I guess that's expected).

**Comment by 1bsyl** [comment]
Indeed, it was expected that SDL_RenderCopy and SDL_RenderCopyF wouldn't fixed, and that the software renderer would work.

So, this could be a bug a some android device, but then, it would be nice to see this working correctly also on some other android device.

maybe this is something within shader precision: 
https://github.com/libsdl-org/SDL/blob/main/src/render/opengles2/SDL_shaders_gles2.c#L51
change 
`    precision mediump float; `
to 
`    precision highp float; `

for all shader of the gles2 back-end ?

**Comment by crudelios** [comment]
That change from `mediump` to `highp` fixes rendering for android on both my devices, so that seems to be exactly the cause.

**Comment by slime73** [comment]
Note that `highp` isn't always supported in fragment shaders on some very old GLES2 drivers/devices. You can query if `GL_FRAGMENT_PRECISION_HIGH` is defined, to check for support.

Also using `highp` for colors probably isn't too useful, it's just texture coordinates which are the issue here I think.

**Comment by crudelios** [comment]
I have no experience in shaders to tell which change(s) fixed the rendering, as I changed all instances of `precision mediump float`, but I can check it out via trial and error.

**Comment by 1bsyl** [comment]
So it's about removing the one from color (https://github.com/libsdl-org/SDL/blob/main/src/render/opengles2/SDL_shaders_gles2.c#L51 ? ).
the other shaders also use the color, can we mix highp and mediump ?

Shouldn't we be able to reproduce the issue on linux with opengles2 ?  Could a different destination/output window size make this not appearing ?

maybe we can make a patch with a "hint" so that each shader a prefixed either with "precision mediump float; " or "precision mediump float;" ?

**Comment by slime73** [comment]
Yep, I'll put something together soon.

**Comment by slime73** [comment]
I created a pull request with a potential fix: #5947
