### ISSUE TITLE
MacOS Error: NSWindow drag regions should only be invalidated on the Main Thread!

### ISSUE THREAD

**Issue by richstokes** [libsdl-org/SDL#5891]
When running something like
```
        if (main_window == NULL)
        {
                sdl_main_window = SDL_CreateWindow(
                    "test",
                    SDL_WINDOWPOS_CENTERED,
                    SDL_WINDOWPOS_CENTERED,
                    768,
                    576,
                    0);
        }
        else
        {
                SDL_CreateWindowFrom(main_window);
        }
```

Is there any way for SDL to detect that its running on MacOS, and structure its threads in a compatible way?

**Comment by frenzibyte** [comment]
Are you running on an M1? you might be hitting https://github.com/libsdl-org/SDL/issues/5203. I've PR'd a workaround for it on https://github.com/libsdl-org/SDL/pull/5708, you can test there with SDL hint `SDL_HINT_MAC_OPENGL_SYNC_DISPATCH=1` and see if it helps.

**Comment by richstokes** [comment]
Will take a look! Where would I set `SDL_HINT_MAC_OPENGL_SYNC_DISPATCH`? Just a regular static var?

**Comment by richstokes** [comment]
Just tried it real quick - doesn't seem to work. Same error. I'm on intel Mac, latest OS

**Comment by frenzibyte** [comment]
Ah, then I think you're encountering a different issue, as the one I linked is specific to Apple M1 GPUs.

**Comment by richstokes** [comment]
I think its probably a very similar issue though. It looks like SDL generally for mac, needs some kind of protected way to run all graphics calls on the same thread. It's something the latest MacOS enforces.

**Comment by richstokes** [comment]
Struggling to find good documentation on this, but [per this doc]:

> Some system frameworks contain APIs that you must only call from your app’s main thread. This requirement applies to most of the AppKit and UIKit user interface APIs, and also applies to some other system APIs. Calling these APIs from the main thread prevents race conditions by serializing the execution of the associated tasks. Failure to perform these operations on the main thread may result in visual defects, data corruption, or crashes.

**Comment by slouken** [comment]
This also matches SDL development recommendations. All windowing/graphics/video calls should be done on the main thread. Doing otherwise is a bug in the application and is not supported.

**Comment by frenzibyte** [comment]
In our case we perform OpenGL/graphics calls on a background thread, matching [Apple's recommendations](https://developer.apple.com/documentation/xcode/improving-app-responsiveness):

> ### Avoid hangs by keeping the main thread free from non-UI work
> Make sure your app uses the main thread only to interact with the user interface (UIKit, AppKit, or SwiftUI). Direct all other operations to a background thread, operation queue, or Grand Central Dispatch queue.

@richstokes On a second look at that PR, I think I mixed things up there... Can you try `SDL_HINT_MAC_OPENGL_SYNC_DISPATCH=0` instead?

**Comment by richstokes** [comment]
No luck with `SDL_HINT_MAC_OPENGL_SYNC_DISPATCH=0` either.

Any tips for tracking down what (non-ui stuff) may be running on the main thread?

I'm basically doing this:  
```
thread = SDL_CreateThread(app_main_thread, "Main Thread", (void *)NULL);
```
this calls a video init function, which seems to generate the error below if I do:
```
if (main_window == NULL)
        {
                rpclog("Trying to create window\n");
                sdl_main_window = SDL_CreateWindow(
                    "App",
                    SDL_WINDOWPOS_CENTERED,
                    SDL_WINDOWPOS_CENTERED,
                    768,
                    576,
                    0);
        }
```

and get:
```
[00000000]: Trying to create window
SDL_CreateWindowFrom could not be created! Error: NSWindow drag regions should only be invalidated on the Main Thread!
Video renderer init failed[00000000]: R 0=00000000 R 4=00000000 R 8=00000000 R12=00000000
R 1=00000000 R 5=00000000 R 9=00000000 R13=00000000
R 2=00000000 R 6=00000000 R10=00000000 R14=00000000
R 3=00000000 R 7=00000000 R11=00000000 R15=0C00000B
0 00000000 EAE00069
f 8=00000000 f 9=00000000 f10=00000000 f11=00000000
f12=00000000 f13=00000000 f14=00000000
[00000000]: F0=0.000000 F1=0.000000 F2=0.000000 F3=0.000000 [00000000]: F4=0.000000 F5=0.000000 F6=0.000000 F7=0.000000
```

**Comment by slouken** [comment]
Yes, you can't create windows in a separate thread. The main thread is the thread that starts executing your program, not a thread that you create and call "Main Thread" :)
