### ISSUE TITLE
SDL_GetCurrentVideoDriver()  on Raspberry OS stopped working.

### ISSUE THREAD

**Issue by Fredrum** [libsdl-org/SDL#5896]
Hello!

Using:  Raspberry Pi 4b, Raspberry OS 64bit Bullseye.
SDL 2.0.20

I just noticing that my code is breaking and that now the call SDL_GetCurrentVideoDriver() has started returning NULL whereas not long ago it correctly returned "x11" on the Raspberry OS desktop;

https://github.com/Fredrum/chiaki/blob/7c751dea9d0f2559f53dab0dba699b53931a0327/rpi/src/main.cpp#L67

To check that I wasn't going crazy I jumped back to an RPiOS Bullseye sd card I had that I hadn't updated for a while and yes it works correctly there.

So some update or change in how Raspberry OS works and presenting itself to other programs seems to have changed.
When? No idea. Maybe within the last week or two?

Has anyone else bumped into this or know what might have happened?

My program still runs perfectly fine on Raspberry Ubuntu 22.04 btw.

Cheers

**Comment by icculus** [comment]
Is this is a copy of SDL built from source code instead of the distro's package? Is it possible that SDL was built without X11 support (etc)?

**Comment by Fredrum** [comment]
SDL was built from source but the same un-touched build worked for a long time and then suddenly not.
Another user of my program did a fresh build and install using my sdl build script that also hadn't been changed for months.
He also got the same errors.

I then thought to re-build SDL, using the same un-altered install script, and it started working again.

I'm wondering if something SDL was linking to in the OS was changed and then when rebuilding this got somehow resolved.

A mystery to this day.
I guess I can close this issue.

**Comment by flufy3d** [comment]
I have the same issue ,arm64 stuck at SDL_GetCurrentVideoDriver

**Comment by icculus** [comment]
> I have the same issue ,arm64 stuck at SDL_GetCurrentVideoDriver

...and did you build your own SDL from source code?

**Comment by flufy3d** [comment]
> > I have the same issue ,arm64 stuck at SDL_GetCurrentVideoDriver
> 
> ...and did you build your own SDL from source code?

yes, I found the issue is no video driver available, my board is wayland gles2

**Comment by icculus** [comment]
Make sure the Wayland development packages are installed before building SDL, or it won't include support for Wayland. If there's a question of why it didn't include it, check config.log (or whatever the CMake log file is called).
