### ISSUE TITLE
support turning off player leds with SDL_GameControllerSetPlayerIndex on the dualsense

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [libsdl-org/SDL#5904]
Currently, if I set the player number on SDL_GameControllerSetPlayerIndex to 0, the player led(s) on my dualsense remains on, but if a send a custom effect to the controller I can actually turn the led(s) off. It would be nice if SDL2 just supported turning off the player leds out of the box without having to use a custom effect for it

**Comment by slouken** [comment]
Index 0 is a valid player index (they're zero-based). You probably want to set the hint SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED.

**Comment by Etaash-mathamsetty** [comment]
> Index 0 is a valid player index (they're zero-based). You probably want to set the hint SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED.

Yes 0 is a valid index but the player 1 light remains on with the index set to 0, but i will try this hint and see if it works

**Comment by slouken** [comment]
Zero based means that index 0 is player 1, index 1 is player 2, etc.

**Comment by Etaash-mathamsetty** [comment]
> Zero based means that index 0 is player 1, index 1 is player 2, etc.

yeah so if want to turn off all the player lights on the controller I literally can't since I can't set the index less than 0 right

**Comment by Etaash-mathamsetty** [comment]
I don't think you are still understanding
if I have `SDL_GameControllerSetPlayerIndex(handle, 0);`, the player one light turns on (even with the hint), but what I trying to accomplish is turning this light off, which is impossible with the current api without sending a custom effect to the controller

**Comment by slouken** [comment]
I do understand, and you're correct, that's not currently supported.

**Comment by slouken** [comment]
In the next release you'll be able to call `SDL_GameControllerSetPlayerIndex(handle, -1)` to clear the player index and turn the light off.
