### ISSUE TITLE
Pre-release 2.23.1 .tar.gz is missing SDL2Config.cmake.in

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL#5905]
Hi all,

Was just testing out the 2.23.1 pre-release's improved CMake build system out with the [pysdl2-dll](https://github.com/a-hurst/pysdl2-dll) Linux build scripts: with the .tar.gz hosted on the GitHub releases page the Autotools build system works perfectly, but attempting to use the CMake build system results in an error:

```
[...]
--  Build Shared Library: ON
--  Build Static Library: ON
--  Build Static Library with Position Independent Code: OFF
-- 
-- If something was not detected, although the libraries
-- were installed, then make sure you have set the
-- CFLAGS and LDFLAGS environment variables correctly.
-- 
CMake Error: File /tmp/cirrus-ci-build/temp/SDL2-2.23.1/SDL2Config.cmake.in does not exist.
CMake Error at /opt/_internal/pipx/venvs/cmake/lib/python3.9/site-packages/cmake/data/share/cmake-3.22/Modules/CMakePackageConfigHelpers.cmake:342 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:3114 (configure_package_config_file)
```

Looking at the `SDL2_2.23.1.tar.gz` contents manually, it is indeed missing the `SDL2Config.cmake.in` file in the root folder. The file is present in the 2.23.1 tagged commit though, so I'm guessing this is a bug or mishap with the code that bundles the tarball? Either way, I'm happy to keep with Autotools for now, but I figured you'd want a heads-up about this before the final 2.24.0 release!

**Comment by slouken** [comment]
Adding @madebr to sanity check :)

**Comment by madebr** [comment]
Looks good!

**Comment by slouken** [comment]
Thanks!
