### ISSUE TITLE
help i started SDL but something is wrong

### ISSUE THREAD

**Issue by idkanythinghelp** [libsdl-org/SDL#5916]
my compilier shows an output error as SDL_main must return a value

my code i am sorry for not adding coments and putting all code in main

#include <iostream>
#include "SDL.h"

using namespace std;

auto SDL_main(int argc, char* argv)
{

	SDL_Init(SDL_INIT_EVERYTHING);
	SDL_Window* wind;

	int h, w;
	char a, b;
	char name[512];
	cout << "do you want to create a window" << endl;
	cin >> a;

	if (a == 'y') {
		cout << "enter window height and weight" << endl;
		cin >> h >> w;

		cout << "name your window" << endl;
		cin >> name;

		wind = SDL_CreateWindow(name,
			SDL_WINDOWPOS_UNDEFINED,
			SDL_WINDOWPOS_UNDEFINED,
			w,
			h,
			SDL_WINDOW_RESIZABLE);

		cout << "do you wish to destroy window" << endl;
		cin >> b;

		if (b == 'y') {
			SDL_DestroyWindow(wind);
		}

	}

	SDLK_0;
	SDL_QUIT;

	return 0;

}

**Comment by icculus** [comment]
Use `int main(int argc, char **argv)` and not the `auto SDL_main` thing you have there now.
