### ISSUE TITLE
Listing audio devices on Windows recently broken

### ISSUE THREAD

**Issue by Photosounder** [libsdl-org/SDL#5919]
When listing audio devices (using the current latest main branch commit) both wasapi and directsound now return 0 devices, whereas winmm still works correcty. It's a recent change as swapping in the 2.0.22 DLL makes it list all the devices just fine. It's probably related to recent commits by @flibitijibibo.

**Comment by flibitijibibo** [comment]
DirectSound I could see a possible change, but WASAPI is surprising... the code is functionally identical, it just changed files.

The two commits in question, which work on my test lab:

https://github.com/libsdl-org/SDL/commit/ae105ae1c718c98d2c7c078b4f1d09e149fc8249
https://github.com/libsdl-org/SDL/commit/15d06180833da1270de809b90df8a80521b2c60d

I would definitely step through SDL_immdevice.c to see if anything unusual is happening.

**Comment by Photosounder** [comment]
I don't know but I just tested this commit https://github.com/libsdl-org/SDL/tree/2373da5d94fe8b977e89786519090cfd556862dd and confirm that things still worked correctly by that point.

**Comment by flibitijibibo** [comment]
The two places I would think could go awry are SDL_IMMDevice_Init and SDL_IMMDevice_EnumerateEndpoints, both in here:

https://github.com/libsdl-org/SDL/blob/main/src/core/windows/SDL_immdevice.c

I don't expect this bug to be subtle, it should light up pretty hard when stepped through in a debugger.

**Comment by Photosounder** [comment]
If you're counting on me to debug it I'm afraid that will have to wait, I'm busy releasing a new version of a program and literally just noticed the bug as I was filming the part of the announcement video where I show my dialog for selecting audio devices. I just need a DLL that works and that can't be the official 2.0.22 DLL as the mouse movement is broken in it and it can't be the latest commit either. It's pretty dire that I have to rely on an arbitrary intermediate commit.

**Comment by flibitijibibo** [comment]
I'll see if anything more subtle shows up (uninitialized memory...?). The local tests seem okay but maybe someone else's hardware will show it if mine doesn't.

(CC @icculus who probably has a lot more test environments than me)

**Comment by flibitijibibo** [comment]
Verified latest Git revision on a PC with a bunch of annoying devices with terrible drivers:

```
'testsurround.exe' (Win32): Loaded 'C:\Users\flibitijibibo\source\repos\dsoundugh\VisualC\Win32\Debug\testsurround.exe'. Symbols loaded.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Users\flibitijibibo\source\repos\dsoundugh\VisualC\Win32\Debug\SDL2.dll'. Symbols loaded.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\lpk.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\usp10.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devobj.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\version.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vcruntime140.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-crt-runtime-l1-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-core-timezone-l1-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-core-file-l2-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-core-localization-l1-2-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-core-synch-l1-2-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-core-processthreads-l1-1-1.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-core-file-l1-2-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-crt-heap-l1-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-crt-string-l1-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-crt-stdio-l1-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-crt-convert-l1-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-crt-math-l1-1-0.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\api-ms-win-crt-locale-l1-1-0.dll'. Cannot find or open the PDB file.
The thread 0x15f0 has exited with code 0 (0x0).
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\clbcatq.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MMDevAPI.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\propsys.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avrt.dll'. Cannot find or open the PDB file.
INFO: Available audio drivers:
INFO: 0: wasapi
INFO: 1: directsound
INFO: 2: winmm
INFO: 3: disk
INFO: 4: dummy
INFO: Using audio driver: wasapi
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\AudioSes.dll'. Cannot find or open the PDB file.
INFO: Testing audio device: Speakers (Creative SB X-Fi) (6 channels)
INFO: Playing 500 Hz test tone on channel: Front Left
INFO: Playing 500 Hz test tone on channel: Front Right
INFO: Playing 500 Hz test tone on channel: Front Center
INFO: Playing 50 Hz test tone on channel: Low Frequency Effects
INFO: Playing 500 Hz test tone on channel: Back Left
INFO: Playing 500 Hz test tone on channel: Back Right
The thread 0x167c has exited with code 0 (0x0).
INFO: Testing audio device: LU28R55 (NVIDIA High Definition Audio) (2 channels)
INFO: Playing 500 Hz test tone on channel: Front Left
INFO: Playing 500 Hz test tone on channel: Front Right
The thread 0x1610 has exited with code 0 (0x0).
INFO: Testing audio device: SPDIF Out (Creative SB X-Fi) (2 channels)
INFO: Playing 500 Hz test tone on channel: Front Left
INFO: Playing 500 Hz test tone on channel: Front Right
The thread 0x1794 has exited with code 0 (0x0).
The thread 0x1618 has exited with code 0 (0x0).
'testsurround.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\avrt.dll'
The thread 0x1524 has exited with code 0 (0x0).
The thread 0x13a0 has exited with code 0 (0x0).
The thread 0x161c has exited with code 0 (0x0).
The thread 0x1620 has exited with code 0 (0x0).
The thread 0x1614 has exited with code 0 (0x0).
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wintrust.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'. Cannot find or open the PDB file.
'testsurround.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msasn1.dll'. Cannot find or open the PDB file.
The program '[5552] testsurround.exe' has exited with code 0 (0x0).
```

(Separate from this: DirectSound on Windows 7 doesn't seem to like 6-channel audio... it doesn't really explain why though.)

**Comment by slouken** [comment]
@Photosounder, it works here on Windows 11 with wasapi and directsound. Do you have more information about what version of Windows you're using and what audio devices are connected?

**Comment by Photosounder** [comment]
I don't know if this helps but this is what I'm seeing when stepping into `SDL_GetNumAudioDevices(0);`
https://www.mediafire.com/file/yhsctahgxsjpvem/2022-07-15+01.01.04.mkv/file

My system is Windows 10 and these are the devices I see when using an older build: https://imgur.com/e2W7328

**Comment by icculus** [comment]
@Photosounder Are you initializing SDL more than once (perhaps deinitializing it with SDL_Quit() between init attempts)? It looks like we picked up the devices on a previous init and never cleared the list before a second init attempt.

@flibitijibibo WASAPI_Deinitialize() has code to free the device list, but it does not appear to have migrated with the rest of the new SDL_IMMDevice code. It also has a static variable for deviceid_list which might be superfluous now that this stuff is operating out of src/core/windows ...

**Comment by icculus** [comment]
(Also, I have never debugged something by watching a video of someone stepping through it in a debugger before, but this actually was super helpful in this case!)

**Comment by Photosounder** [comment]
Yes as you can partially see at the end of the second video I do:

```
	SDL_AudioQuit();					// quit the current audio driver
	SDL_AudioInit(SDL_GetAudioDriver(driver_index));	// initialise it
```
which is in the part of the code that reinitialises the audio based on the saved preferences. This comes after starting the program with `SDL_Init(SDL_INIT_TIMER | SDL_INIT_VIDEO | SDL_INIT_AUDIO)` which is the default for my system. So the audio system would have initialised once with SDL's default and a second time with my default which is DirectSound.

The code that reinitialises the audio is here https://github.com/Photosounder/rouziclib/blob/master/rouziclib/general/audio.c#L113 and the code that first initialises everything is here https://github.com/Photosounder/rouziclib/blob/master/rouziclib/libraries/sdl.c#L387

> (Also, I have never debugged something by watching a video of someone stepping through it in a debugger before, but this actually was super helpful in this case!)

I'm an endless source of exotic great ideas 😉. It was easy for me because I didn't need to take the time to figure out what's going on and yet you saw most of what you needed to see.

**Comment by flibitijibibo** [comment]
Should be resolved by https://github.com/libsdl-org/SDL/commit/fff34f630479f79cc58f0b3455969c3ddf32d5d0, feel free to reopen if not!

**Comment by Photosounder** [comment]
I confirm that it works, thank you!
