### ISSUE TITLE
DirectSound and multichannel audio support...

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#5920]
In doing some work to try and prioritize DirectSound support, I ran into something that apparently someone else filed 2 years ago:

https://discourse.libsdl.org/t/sdl-openaudiodevice-and-sdl-openaudio-fails-when-setting-more-that-2-channels-in-specs/27412

... and in fact, while trying to find _that_ report for this ticket, I found another report from _2012_:

http://quakeone.com/forum/quake-help/quake-clients/9269-5-1-channel-audio-unable-to-initialize-darkplaces-sdl-exe

We don't get good error messages from DirectSound (as far as I know) and the parameters for CreateSoundBuffer are completely valid - I even tweaked the AudioSpec to try and replicate the exact buffer size with stereo output and that didn't break like I'd hoped.

It seems like we're looking at one of three things:

- DirectSound wants a WAVEFORMATEXTENSIBLE for multichannel, to grab the dwChannelMask value
- Secondary buffers don't support more than stereo. Maybe primary buffers do?
- When Vista said DirectSound and 3D didn't work anymore, they weren't just talking about DirectSound3D!

I'm filing this mostly to have it on the GitHub tracker, and to run it by @slouken and @icculus to see if either of them know what could be the real issue here. For the new IMMDevice work this isn't nuclear or anything, if it turns out I'm actually right on the latter two possibilities all we have to do is clamp the channels value to 2 or less (the format and freq values will still be useful untouched).

**Comment by slouken** [comment]
I'm pretty sure the first thing is true. Is that easy to test?

**Comment by flibitijibibo** [comment]
PR is ready. Fun fact: This bug was introduced in SDL 1.2.8 - it would have celebrated its 18th birthday next month!

**Comment by mirh** [comment]
https://web.archive.org/web/20070304074300/http://msdn2.microsoft.com/en-us/library/bb206355.aspx
https://web.archive.org/web/20070814001754/http://msdn2.microsoft.com/en-us/library/bb147216.aspx
https://web.archive.org/web/20030819144319/http://msdn.microsoft.com/library/en-us/stream/hh/stream/aud-prop_8ugj.asp
Possible relevant references.
