### ISSUE TITLE
How can we send the files we created to the share on android?

### ISSUE THREAD

**Issue by mumin16** [libsdl-org/SDL#5923]
How can we send the files(pdf,xlsx,png,zip....) we created to the default application on android?

best regards!

**Comment by mumin16** [comment]
i did it , i did it... yuppi...

**Comment by slouken** [comment]
Can you post notes on how you did it for future reference and then close this bug?

**Comment by mumin16** [comment]
1- AndroidManifest.xml:

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="mypackage.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">

            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>

**Comment by mumin16** [comment]
2- res/xml/provider_paths.xml:
<?xml version="1.0" encoding="utf-8" ?>
<paths>
  <files-path name="files" path="." />
</paths>

**Comment by mumin16** [comment]
3- in java:
    public void shareFile(String shareFile,String file_type )//"application/pdf" , "application/xlsx"
    {
        File sharePath = new File(getFilesDir(), ".");
        File newFile = new File(sharePath, shareFile);
        Uri contentUri = FileProvider.getUriForFile(getContext(), "mypackage.fileprovider", newFile);


        Intent shareIntent = new Intent();
        shareIntent.setAction(Intent.ACTION_SEND);
        shareIntent.putExtra(Intent.EXTRA_STREAM, contentUri);
        shareIntent.setType(file_type);
        startActivity(Intent.createChooser(shareIntent, null));
    }

**Comment by mumin16** [comment]
4- in c++:

shareFile(rawFileName.c_str(),"application/pdf" );//"application/pdf" , "application/xlsx"

**Comment by mumin16** [comment]
![alt text](https://github.com/mumin16/builds/blob/main/Screenshot_20220716-185325.png?raw=true)

**Comment by slouken** [comment]
Great, thanks!
