### ISSUE TITLE
SDL_ShowSimpleMessageBox caused SIGSEGV on macOS Mojave and High Sierra

### ISSUE THREAD

**Issue by skynettx** [libsdl-org/SDL#5928]
Hi,

SDL_ShowSimpleMessageBox caused SIGSEGV on macOS Mojave and High Sierra when window is moved.
If you click on the button or press on enter everything works fine but when you moved the window will immediately SIGSEGV triggered.
Code example:
```
#include <stdio.h> 

#include "SDL.h"

int main(int argc, char *argv[])
{
  SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR,
            "Test", "Test Message", NULL);
}
```
I can't test whether the crash also occurs on newer or older macOS versions at the moment.
My SDL version is 2.0.22.

**Comment by icculus** [comment]
This is fixed on Mojave for me, now; I assume it affected most (all?) macOS versions, though, but we should be good now.
