### ISSUE TITLE
SDL_powerof2 loops infinitely for values bigger then 0x40000000

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#5930]
Introduced by https://github.com/libsdl-org/SDL/commit/b299cb3d3c2bed0a9d14db8f12ff6515a16ef5aa

The biggest power of 2 greater the `0x40000000` is `0x80000000`, which is -1 in 32-bit 2 complement. A negative number can never be greater then a positive number.

Changing the `int` to `unsigned` also doesn't fix the issue, because then it hangs for values greater then `0x80000000`. A 32-bit unsigned integer cannot represent a 33-bit integer.

**Comment by slouken** [comment]
Fixed, thanks!
