### ISSUE TITLE
Unknown battery level for DS4 on Linux

### ISSUE THREAD

**Issue by pktiuk** [libsdl-org/SDL#5933]
Hello,

I have problem with reading battery level from DualShock 4 using `SDL_JoystickCurrentPowerLevel`

I always get `SDL_JOYSTICK_POWER_UNKNOWN`. 
This is strange, because I can read battery level using `upower`

```bash
$ upower -i `upower -e | grep 'sony'`
  native-path:          sony_controller_battery_a4:ae:11:b2:6f:3d
  model:                Wireless Controller
  serial:               a4:ae:11:b2:6f:3d
  power supply:         no
  updated:              wto, 10 maj 2022, 16:19:57 (44 seconds ago)
  has history:          yes
  has statistics:       yes
  gaming-input
    rechargeable:        yes
    warning-level:       none
    percentage:          95%
    icon-name:          'battery-full-symbolic'
  History (charge):
    1652192397	0,000	unknown
  History (rate):
    1652192397	0,000	unknown
```
System: Linux pop-os 20.04
Kernel: 5.16.19

The same code compiled under Windows works properly.

**Comment by slouken** [comment]
It's set in this code in SDL_hidapi_ps4.c:
```c
    if (packet->ucBatteryLevel & 0x10) {
        SDL_PrivateJoystickBatteryLevel(joystick, SDL_JOYSTICK_POWER_WIRED);
    } else {
        /* Battery level ranges from 0 to 10 */
        int level = (packet->ucBatteryLevel & 0xF);
        if (level == 0) {
            SDL_PrivateJoystickBatteryLevel(joystick, SDL_JOYSTICK_POWER_EMPTY);
        } else if (level <= 2) {
            SDL_PrivateJoystickBatteryLevel(joystick, SDL_JOYSTICK_POWER_LOW);
        } else if (level <= 7) {
            SDL_PrivateJoystickBatteryLevel(joystick, SDL_JOYSTICK_POWER_MEDIUM);
        } else {
            SDL_PrivateJoystickBatteryLevel(joystick, SDL_JOYSTICK_POWER_FULL);
        }
    }
```
But, I suspect that the hidapi driver isn't being used for some reason in your build.

**Comment by cgutman** [comment]
> But, I suspect that the hidapi driver isn't being used for some reason in your build.

Yep. Generally `/dev/hidraw*` is going to be owned by `root` which will prevent SDL from being able to directly open the raw HID device for use with HIDAPI. You can probably configure `udev` to modify permissions on these devices to allow SDL to open them or just `chown` them for testing.

**Comment by pktiuk** [comment]
@cgutman   
I launched my app with `sudo` and it still showed unknown batttery.

**Comment by pktiuk** [comment]
> But, I suspect that the hidapi driver isn't being used for some reason in your build.

I use a regular build from Ubuntu repositories.  
I got it with:  
`sudo apt install libsdl2-dev`

Updating system to Pop OS 22.04 with SDL 2.0.20 fixed this issue.  
Maybe something was wrong with this package.
