### ISSUE TITLE
i want to access java variable from MULTITHREADING c++ code in sdl2.

### ISSUE THREAD

**Issue by mumin16** [libsdl-org/SDL#5936]
i can access java variable from single threadng c++ code in sdl2. but not in mutlthread code. i need create jvm and attach current thread but android not allow. do you have any solution?

**Comment by icculus** [comment]
You can use SDL_AndroidGetJNIEnv() from C++, to get the JNIEnv object for the current thread, and then you can use JNI directly to call back into Java from C++ (or query a Java variable from C++). This works with multithreaded apps.
