### ISSUE TITLE
Add Support for Switch JoyCon Gyro (exposed by HID Nintendo)

### ISSUE THREAD

**Issue by theofficialgman** [libsdl-org/SDL#5937]
in my experience, SDL2 does not support the hid-nintendo exposed accel/gyro (last tested on sdl2 2.0.20)

these can be found as event# devices separate from the controller itself. the controller is combined by the accompanying userspace program `joycond`
ex:
```
/dev/input/event7:	Nintendo Switch Right Joy-Con IMU
/dev/input/event9:	Nintendo Switch Left Joy-Con IMU
/dev/input/event10:	Nintendo Switch Combined Joy-Cons
```

**Comment by slouken** [comment]
Can you check to see if this commit added support?
https://github.com/libsdl-org/SDL/commit/9a4f200d44bfc20432f2581c8977561fd2af9151

**Comment by theofficialgman** [comment]
I already checked, that does not fix the problem. Aren't the accel/gyo implementations in SDL controller specific? nothing in the gamecontrollerdb.txt handles accel/gyro mapping

also let me say I find it very annoying that the `debian` folder was removed from SDL2. before I found it very easy to build local debs of SDL2 and test them, revert, etc. now I can't do that without creating all of that myself

**Comment by slouken** [comment]
I think `src/joystick/linux/SDL_sysjoystick.c` needs to be extended with support for separate led/power/gyro devices. I think there's been some discussion on various groups about this, but I don't know that anyone has figured out how to tie the devices together.

You're welcome to give it a shot and submit a PR if you find a good way to do that.

FYI, I usually build and install locally using:
```sh
mkdir build
cd build
../configure && make && make install
```
and then set LD_LIBRARY_PATH=/usr/local/lib so I know my tests are using the locally built version of SDL.

**Comment by theofficialgman** [comment]
yeah I get that you can install /usr/local
I just found it very nice that before that the `debian` folder was already prepopulated for builds with `dpkg-buildpackage -b`

**Comment by theofficialgman** [comment]
the issue in this case is not that joycons aren't supported in the driver, but that combined joycons are not supported. this is a `SwitchJoyConPair` (which btw seems to not have been fully added to SDL2 since there is no way to get that in `src/joystick/controller_type.c`)

**Comment by slouken** [comment]
The combined joycons is working with joycond and the new mappings, but joycond doesn't expose any gyro functionality, it just exposes the controller as a simple gamepad to applications.
