### ISSUE TITLE
Add iOS mappings for Switch controllers (iOS 16)

### ISSUE THREAD

**Issue by offalynne** [libsdl-org/SDL#5939]

**Comment by slouken** [comment]
Added in https://github.com/libsdl-org/SDL/commit/aad7ef6eafc01fd90677118340dc33f2f7ba9726, thanks!

**Comment by offalynne** [comment]
JoyCons are supported too -- individually, or paired by holding the meta buttons for several seconds

**Comment by slouken** [comment]
Thanks, added in https://github.com/libsdl-org/SDL/commit/f9beef760a778cc74d48d17971b6ce0451979c2e
