### ISSUE TITLE
SDL_SetWindowMouseRect — the set area is one pixel too small

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#5946]
On the Windows platform, the cursor boundary area is one pixel too small — pixel is missing on the right and bottom of the selected area. To avoid this error, currently I have to increase `Rect.W` and `Rect.H` by one pixel first, and then pass it to `SDL_SetWindowMouseRect`.

This problem does not occur when `null` is passed as a pointer to a rect. Apparently, the `SDL_SetWindowMouseRect` function miscalculates the coordinates of the right and bottom sides of the rectangle by subtracting one pixel unnecessarily.

**Comment by flibitijibibo** [comment]
I _think_ this is the relevant block:

https://github.com/libsdl-org/SDL/blob/main/src/video/windows/SDL_windowswindow.c#L1291-L1307

**Comment by furious-programming** [comment]
Thank you @flibitijibibo.

Note that the functions from the Win32 API take care of the correctness of `right` and `bottom` coordinates, not including these values in the handling of rects. So, wherever rect must be passed, `right` and `bottom` should be computed as `X + W` and `Y + H` respectively, without subtracting anything.

**Comment by flibitijibibo** [comment]
Makes sense to me! But, it looks like @slouken wrote this, so will defer to him since I don't know the Windows side very well:

https://github.com/libsdl-org/SDL/commit/7d21322df1fdf1ea9deaec4cdf3250fa3d736177

**Comment by slouken** [comment]
Fixed, thanks!
