### ISSUE TITLE
macOS build error against 10.9 sdk

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5954]
The following error I got when trying to build against 10.9 sdk.
I was targeting i686 but that is irrelevant here:
```
src/video/cocoa/SDL_cocoamouse.m:120:34: error: property 'valid' not found on object of type 'NSImage *'
    if ((image == nil) || (image.valid == NO)) {
                                 ^
1 error generated.
```

From the same failed run, I got lots of `-Wobjc-property-implementation`
warnings. They _might_ be because of me targeting i686, or they might be
something else -- don't know, so here they are (attaching instead of
inlining because of large volume of text): [warnings.txt](https://github.com/libsdl-org/SDL/files/9176784/warnings.txt)

**Comment by slime73** [comment]
SDL dropped x86 support on macOS as of ec8fa57 (https://github.com/libsdl-org/SDL/pull/5632 & https://github.com/libsdl-org/SDL/issues/5630#issuecomment-1120229800)

**Comment by sezero** [comment]
> SDL dropped x86 support on macOS as of [ec8fa57](https://github.com/libsdl-org/SDL/commit/ec8fa57750423978086cd7a96bd92e7e3ff46cc9) (#5632 & [#5630 (comment)](https://github.com/libsdl-org/SDL/issues/5630#issuecomment-1120229800))

OK, apart from the error, no warnings if I target x86_64 and build against 10.9 sdk: so ignore the warnings.

The error however is irrelevant of target: seems to be after @icculus' https://github.com/libsdl-org/SDL/commit/56665e1d9de9a5062b1933f4d51266b47f809f2a commit

**Comment by slime73** [comment]
Ah, I think it should probably be `image.isValid` instead of `image.valid`. Does that fix the error for you?

**Comment by sezero** [comment]
> Ah, I think it should probably be `image.isValid` instead of `image.valid`. Does that fix the error for you?

Yes.

**Comment by sezero** [comment]
> > Ah, I think it should probably be `image.isValid` instead of `image.valid`. Does that fix the error for you?
> 
> Yes.

Someone should push it and close this.

**Comment by sezero** [comment]
Addendum: Building against 10.7 sdk also fails like below. 10.8 sdk works with no warnings.
```
src/video/cocoa/SDL_cocoaevents.m:348:46: error: no visible @interface for 'NSBundle' declares the selector 'loadNibNamed:owner:topLevelObjects:'
            success = [[NSBundle mainBundle] loadNibNamed:mainNibFileName owner:[NSApplication sharedApplication] topLevelObjects:nil];
                       ~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:650: build/SDL_cocoaevents.lo] Error 1
src/video/cocoa/SDL_cocoamodes.m:157:10: warning: unused variable 'interlaced' [-Wunused-variable]
    bool interlaced = (ioflags & kDisplayModeInterlacedFlag) != 0;
         ^
src/video/cocoa/SDL_cocoamodes.m:151:10: warning: unused variable 'usableForGUI' [-Wunused-variable]
    bool usableForGUI = CGDisplayModeIsUsableForDesktopGUI(vidmode);
         ^
2 warnings generated.
make: Target 'all' not remade because of errors.
```

**Comment by slouken** [comment]
> > > Ah, I think it should probably be `image.isValid` instead of `image.valid`. Does that fix the error for you?
> > 
> > 
> > Yes.
> 
> Someone should push it and close this.

Done!

**Comment by slouken** [comment]
> Addendum: Building against 10.7 sdk also fails like below. 10.8 sdk works with no warnings.
> 
> ```
> src/video/cocoa/SDL_cocoaevents.m:348:46: error: no visible @interface for 'NSBundle' declares the selector 'loadNibNamed:owner:topLevelObjects:'
>             success = [[NSBundle mainBundle] loadNibNamed:mainNibFileName owner:[NSApplication sharedApplication] topLevelObjects:nil];
>                        ~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make: *** [Makefile:650: build/SDL_cocoaevents.lo] Error 1
> src/video/cocoa/SDL_cocoamodes.m:157:10: warning: unused variable 'interlaced' [-Wunused-variable]
>     bool interlaced = (ioflags & kDisplayModeInterlacedFlag) != 0;
>          ^
> src/video/cocoa/SDL_cocoamodes.m:151:10: warning: unused variable 'usableForGUI' [-Wunused-variable]
>     bool usableForGUI = CGDisplayModeIsUsableForDesktopGUI(vidmode);
>          ^
> 2 warnings generated.
> make: Target 'all' not remade because of errors.
> ```

Can you enter a new issue for this? It looks like we support building with the 10.7 SDK currently, so we should fix this (or bump our minimum SDK requirement)

**Comment by sezero** [comment]
> Can you enter a new issue for this? It looks like we support building with the 10.7 SDK currently, so we should fix this (or bump our minimum SDK requirement)

Opened new ticket https://github.com/libsdl-org/SDL/issues/5956 for it
