### ISSUE TITLE
SDL_guid.h not exported in SDL.h?

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL#5964]
While updating PySDL2 to wrap the new functions/constants/etc in SDL 2.23.1, I noticed that even though a new header `SDL_guid.h` was added #5757, it's not included in the main `SDL.h`.

Is this deliberate (i.e. those functions aren't meant to be included in the normal SDL namespace), or just something that got missed during the refactor?

**Comment by slouken** [comment]
It was missed, thanks!
Fixed in https://github.com/libsdl-org/SDL/commit/cbb3f4ca379097b98bc8a2bbe40cd539a3f93991
