### ISSUE TITLE
Is it worth adding a linker dependency for this OpenBSD sanity check?

### ISSUE THREAD

**Issue by time-killer-games** [libsdl-org/SDL#5970]
I wanted to add this code to SDL_GetBathPath() which verifies the executable path does in fact return the correct executable or one of its filesystem equivalents (i.e. a hard link to the correct file).

Here's the code I am using to do it for my own API:
https://github.com/time-killer-games/xproc/commit/03a643a7d33e679994f4896acfca7a9fa7d5467f

My question is, is it really worth adding a new linker dependency on `-lkvm` just for this 1 tiny sanity check? Or are you guys not worried about the chances of it returning the wrong executable path at all? This would allow you to produce an error code if the ino_t and dev_t do not match up or the file is no longer found.

That's pretty much it.
Samuel

**Comment by slouken** [comment]
Probably not worth it for the public release, but you're welcome to add that as a sanity check for your own code.
