### ISSUE TITLE
Joysticks have no haptics since 2.0.12

### ISSUE THREAD

**Issue by goob256** [libsdl-org/SDL#5971]
SDL_JoystickIsHaptic(joy) returns 0 on Xbox Series X and Logitech F510. I went back through some old DLLs and 2.0.12 was the last one that works for me. This was based on a game I'm making but I checked 2 of my old games which ship with 2.0.12 and newer DLLs do not find haptics on joysticks on those games either. I rebuilt one of the old games with 2.0.22 with no luck, no haptics.

**Comment by slouken** [comment]
The haptic system is deprecated, the new game controller rumble APIs are recommended for new development:
https://wiki.libsdl.org/SDL_GameControllerRumble

**Comment by goob256** [comment]
Thanks I'll give it a shot.

**Comment by goob256** [comment]
Works fine thanks.
