### ISSUE TITLE
Mouse relative mode still broken on MacOS 12.4

### ISSUE THREAD

**Issue by fhoenig** [libsdl-org/SDL#5976]
referring to: https://github.com/libsdl-org/SDL/issues/5340

When I enable relative mode, the mouse cursor is hidden correctly. However it stops at the edge of the screen.
I've tried all combinations of hints.

When I manually set the mouse cursor to the window center, it works while the cursor is visible. However not when it is hidden via set relative mode. 

Possibly a hardened runtime / macos "security feature" ?

**Comment by slouken** [comment]
Can you try `testsprite2 --info event_motion`, and then hit Ctrl-R to enter relative mode?
I'm seeing relative mode working correctly, not bounded by the edge of the screen.

Does it work in your application if you disable hardened runtime?

**Comment by icculus** [comment]
@fhoenig We're wrapping up the milestone here, if you get a chance to try this without hardened runtime soon, we can try to figure something out for 2.24.0.

**Comment by fhoenig** [comment]
Hey! I haven't got the time to try this yet. But I did notice one thing: relative still seems to work. I have reduced the issue to the fact that you cannot set the cursor position of a hidden mouse. since SDL docs state this behavior to undefined, I think you can close this issue.
