### ISSUE TITLE
When "SDL_SetRelativeMouseMode" is enabled, cursor moves much faster

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#5992]
Tested in Windows 10 (64-bit) with SDL 2.0.22.

For example, I move the mouse along the X axis in a window at a constant low speed, to make the cursor move every pixel. If `SDL_SetRelativeMouseMode` is disabled, `event.motion.xrel` returns `1`, as expected. But if I enable `SDL_SetRelativeMouseMode`, for the same low mouse speed, the `event.motion.xrel` field contains the values `2` or `3` (much more than it should be).

It looks as if the mouse speed is increased significantly when relative mode is on. This means that the game using this mode is not able to provide uniform cursor speed — the cursor will move with normal speed e.g. in the game menu (when relative mode is off), but much faster during the actual game (when relative mode is active).

What's wrong with this mode? Why is this happening?

**Comment by slouken** [comment]
I'm not sure why you're seeing this. Have you set the mouse speed slower in Windows mouse properties?

**Comment by furious-programming** [comment]
I have the mouse speed set to `2`:

![image](https://user-images.githubusercontent.com/8170730/182386463-f7ebe560-d9af-4aad-bef8-5695b01a97bc.png)

**Comment by slouken** [comment]
Oh, that's why. In mouse relative mode you get the raw mouse deltas. The default cursor speed is right in the middle between slow and fast.

**Comment by slouken** [comment]
Actually, I'm going to reopen this to investigate whether we want to add a hint to scale relative mode motion the same as the OS does for normal mouse motion.

**Comment by furious-programming** [comment]
In my opinion, SDL should respect user settings so that the game developer is able to provide a stable cursor speed regardless of whether the relative mode is active or not. I will be very grateful if scaling is added.

**Comment by peppy** [comment]
One thing to note is that if it is made to scale with the user's OS sensitivity setting, this should still hopefully be a toggle/hint.

We've run some real-life events where users would BYO keyboard / mouse, and applying their known settings in our game (mouse sensitivity or graphic tablet regions) without having to worry about external factors (ie. OS settings) is really useful in such a case.

**Comment by slouken** [comment]
> One thing to note is that if it is made to scale with the user's OS sensitivity setting, this should still hopefully be a toggle/hint.
> 
> We've run some real-life events where users would BYO keyboard / mouse, and applying their known settings in our game (mouse sensitivity or graphic tablet regions) without having to worry about external factors (ie. OS settings) is really useful in such a case.

Yes, for sure. It would be a hint that defaults off. I've prototyped this a bit in https://github.com/libsdl-org/SDL/pull/6000
