### ISSUE TITLE
direct3d 11 & 12 renderers are broken when using SDL_CreateWindowFrom

### ISSUE THREAD

**Issue by kadirlua** [libsdl-org/SDL#5997]
Hi, direct3d11 and 12 renderers are broken when using SDL_CreateWindowFrom in my project. It was working with SDL 2.0.22 but there is a problem with the last changes. By the way direct3d implementation works properly.

Here is a screenshot about the problem:
![direct3d-11-12](https://user-images.githubusercontent.com/20769946/182452076-9ffb1415-0681-4072-848d-70286f99e52c.png)

Thanks in advance.

**Comment by slouken** [comment]
Are you able to bisect to see what change broke this?

**Comment by kadirlua** [comment]
> Are you able to bisect to see what change broke this?

No, I tried somethings commit by commit but i did not find which change broke this yet.

**Comment by slouken** [comment]
Do you have a simple example we can use to reproduce this?

**Comment by kadirlua** [comment]
> Do you have a simple example we can use to reproduce this?

Sorry, I was busy with my job. No, I don't have but I found the issue. This problem causes from DXGI_SWAP_CHAIN_DESC1 structure's parameters. I think swap effect has some problems especially for child windows. (I had similar issues before.) What I have done is I changed the SwapEffect parameter to DXGI_SWAP_EFFECT_SEQUENTIAL with Scaling DXGI_SCALING_STRETCH in the file SDL_render_d3d11.c. It worked as I expected :)

```cpp
swapChainDesc.Scaling = DXGI_SCALING_STRETCH;
swapChainDesc.SwapEffect = DXGI_SWAP_EFFECT_SEQUENTIAL; /* All Windows Store apps must use this SwapEffect. */
```

Here is a screenshot:
![direct3d11](https://user-images.githubusercontent.com/20769946/183264117-df0ab1e9-83e6-4080-a33f-ed808f71fe36.png)


But I am not sure about other platforms (Windows Phone, Store) or situations effected by these changes? If the changes are ok with you, i can commit & push into the repo. 

Thanks.

**Comment by kadirlua** [comment]
When I checked the Microsoft docs about the swap effect on directx11 and 12, I reliazed that DXGI_SWAP_EFFECT_SEQUENTIAL is not compatible with directx12. Maybe we should find another solution. Here is the link:

https://docs.microsoft.com/en-us/windows/win32/api/dxgi/ne-dxgi-dxgi_swap_effect

**Comment by slouken** [comment]
Are you sure this works with 2.0.22? I don't see anything in the D3D11 changes since then that would affect the swap chain.

**Comment by kadirlua** [comment]
Yes, I am sure about it but I tested with Windows 10 long time ago. Now I have tested with SDL 2.0.22 at the moment and it has the same issue. I am using Windows 11 with the lastest Windows SDK (10.0.22621.0). Do you think Windows 11 has problems D3D11 or the lastest Windows SDK are broken for D3D11?

**Comment by kadirlua** [comment]
It might be a similar issue found on stackoverflow:

https://stackoverflow.com/questions/72958613/createswapchainforhwnd-with-multiple-child-windows-doesnt-render-to-the-right-a

**Comment by slouken** [comment]
What size is being passed to D3D11_CreateSwapChain()? It looks like you're creating a small buffer and presenting it on a larger window, and given that the flags don't say stretch, D3D is doing the right thing in that case.

**Comment by kadirlua** [comment]
The width and height values are correct being passed to D3D11_CreateSwapChain(). (w: 1544, h: 694)

![debug](https://user-images.githubusercontent.com/20769946/183281467-0c52618f-2bc3-4434-bc0f-7529dc4e48a1.png)

**Comment by slouken** [comment]
Do you have display scale set in your display settings? If so, if you change the scale to 100%, does that fix the issue?

**Comment by kadirlua** [comment]
> Do you have display scale set in your display settings? If so, if you change the scale to 100%, does that fix the issue?

Opps, you are right, i did not know that my display settings 125%. (It's automatically set it up by Windows) Because it's my new PC. After changed it to 100%, it worked properly. So the problem is scaling is not working for SDL?

**Comment by slouken** [comment]
The problem is D3D needs to scale the backbuffer to the window resolution, but we've told it not to scale.

@icculus, what do you think about enabling the scaling flag always, or checking to see if DPI scaling is enabled?

**Comment by kadirlua** [comment]
After taking some time with the issue I found a property named gdiScaling in the manifest file of my application. I have set it up as true which means the app will be scaled based on GDI. After removed it or set false, D3D11 worked properly. Microsoft also mentioned about it in a blog post: 
https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/

`
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
      <gdiScaling xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>
    </windowsSettings>
  </application>
`

**Comment by icculus** [comment]
> what do you think about enabling the scaling flag always, or checking to see if DPI scaling is enabled?

This is fine with me, but if the immediate problem is resolved, let's not make any changes for 2.24.

**Comment by slouken** [comment]
Sounds good.

**Comment by kadirlua** [comment]
I do not know why did you close this issue but the problem still does exists for direct3d11&12 in the lastest codebase of SDL.

**Comment by kadirlua** [comment]
It resolves the problem but I do not want to change that setting in the manifest file. As @slouken said , the scaling should be enabled when DPI scaling is enabled.
