### ISSUE TITLE
SDL_WarpMouseInWindow works incorrectly when relative mouse mode is active

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#6002]
Windows 10, 64-bit

If relative mouse mode is active, the `SDL_WarpMouseInWindow` function not only moves the cursor to the wrong place in the window (not compatible with the given new coordinates), it also does not generate the `SDL_MOUSEMOTION` event. I have the following code in my game project:

```pascal
procedure Game_WindowInstanceSetStickActive(AInstance: PGame_WindowInstance; AActive: TGame_Bool);
var
  CursorX: TGame_SInt32;
  CursorY: TGame_SInt32;
begin
  if AActive then
  begin
    SDL_SetRelativeMouseMode(SDL_TRUE);
    Game_StickSetActive(AInstance^.Stick, True);
  end
  else
  begin
    Game_StickSetActive(AInstance^.Stick, False);

    CursorX := AInstance^.BoundsClient.X + AInstance^.BoundsClient.W div 2;
    CursorY := AInstance^.BoundsClient.Y + AInstance^.BoundsClient.H div 2;

    SDL_WarpMouseInWindow(AInstance^.HandleWindow, CursorX, CursorY); // center the cursor in window
    SDL_SetRelativeMouseMode(SDL_FALSE);                              // disable mouse relative mode
  end;
end;
```
If the virtual stick (no matter what it is) is to be disabled, new coordinates for the cursor are computed (center of the window), the cursor is moved there, and finally the relative mouse mode is turned off. And the cursor is in the wrong place every time.

I displayed the data provided in the `SDL_MOUSEMOTION` events in the console. I turn on the game, unlock the virtual stick (enable relative mode), move the cursor to the upper left corner of the window (position `0,0`), turn off the stick (disable relative mode) and the system cursor appears in the lower right corner of the window, without generating the `SDL_MOUSEMOTION` event.

If I change the order of functions and turn off relative mode first and then change the cursor position:

```pascal
SDL_SetRelativeMouseMode(SDL_FALSE);
SDL_WarpMouseInWindow(AInstance^.HandleWindow, CursorX, CursorY);
```
everything works fine, but there is a nasty effect — the cursor first appears and then jumps to the center of the window, which is the effect expected with this order of the called functions. This is what I want to avoid, therefore I want to move the cursor first and then turn off relative mouse mode, but the `SDL_WarpMouseInWindow` function is not working properly.

**Comment by Susko3** [comment]
`SDL_WarpMouseInWindow` doesn't warp the OS/Windows cursor when relative mouse is enabled. I think this is by design. But it should warp the "internal" SDL mouse position so that turning off relative mode will warp the OS cursor to the new position.

Are you using [`SDL_HINT_MOUSE_RELATIVE_MODE_CENTER`](https://github.com/libsdl-org/SDL/blob/a2d3be904b219e4257fb11a8ecb51f5f9a9e60f7/include/SDL_hints.h#L986-L1000) and what value is it set to? The Windows cursor should already be in the center of the window. 

Try hiding the cursor during the warp so that it only shows when it's in the center:

```diff
+SDL_ShowCursor(SDL_DISABLE);
SDL_SetRelativeMouseMode(SDL_FALSE);
SDL_WarpMouseInWindow(AInstance^.HandleWindow, CursorX, CursorY);
+SDL_ShowCursor(SDL_ENABLE);
```

**Comment by furious-programming** [comment]
> `SDL_WarpMouseInWindow` doesn't warp the OS/Windows cursor when relative mouse is enabled. I think this is by design.

I don't know what SDL uses underneath, but the `SetWindowPos` function works in conjunction with the `ClipCursor` function from Win32 API. Meanwhile, the `SDL_WarpMouseInWindow` call changes the cursor position, but the new position is invalid. So this is why I suspect that this is a bug, not design.

> But it should warp the "internal" SDL mouse position so that turning off relative mode will warp the OS cursor to the new position.

This should work in such a way that the `SDL_WarpMouseInWindow` call should always position the cursor at the given position, regardless of the relative mouse mode state. If relative mode clips the cursor position to window bounds (which I am using), it should be possible to position the cursor anywhere inside the window client — which in version **2.0.22** does not work.

> Are you using [`SDL_HINT_MOUSE_RELATIVE_MODE_CENTER`](https://github.com/libsdl-org/SDL/blob/a2d3be904b219e4257fb11a8ecb51f5f9a9e60f7/include/SDL_hints.h#L986-L1000) and what value is it set to? The Windows cursor should already be in the center of the window.

No, but I just checked and it looks like this hint is not supported in **SDL 2.0.22** — in relative mode the cursor still wanders inside the window (I preview the position in the console, reading it directly from `SDL_MOUSEMOTION` events). There is the following line in the code above this hint declaration:

> By default SDL will constrain the mouse to the center of the window

which is not confirmed in reality — by default the cursor is clipped to the window client. Maybe this comment is for the next version of SDL, but not **2.0.22**.

> Try hiding the cursor during the warp so that it only shows when it's in the center:

This works fine, but in my project I will not use the system cursor (it will always be hidden), but my own, dynamically rendered with textures. Therefore, `SDL_WarpMouseInWindow` must start correctly positioning the cursor in the given place, while the relative mouse mode is active.

**Comment by furious-programming** [comment]
It looks like something was wrong on my site. I updated the headers (I'm using [SDL2-for-Pascal](https://github.com/PascalGameDevelopment/SDL2-for-Pascal) headers) and my code starts to work correctly. This is very strenge, because those headers contains mostly only imports, without any wrappers to the SDL functions.

So sorry for the confusion, the problem was on my side.

**Comment by Susko3** [comment]
I've taken a closer look at your code, and your warping logic is incorrect, `SDL_WarpMouseInWindow` already moves the cursor relative to the window top left corner. No idea why it works properly when relative is disabled.

```diff
procedure Game_WindowInstanceSetStickActive(AInstance: PGame_WindowInstance; AActive: TGame_Bool);
var
  CursorX: TGame_SInt32;
  CursorY: TGame_SInt32;
begin
  if AActive then
  begin
    SDL_SetRelativeMouseMode(SDL_TRUE);
    Game_StickSetActive(AInstance^.Stick, True);
  end
  else
  begin
    Game_StickSetActive(AInstance^.Stick, False);

-    CursorX := AInstance^.BoundsClient.X + AInstance^.BoundsClient.W div 2;
-    CursorY := AInstance^.BoundsClient.Y + AInstance^.BoundsClient.H div 2;
+    CursorX := AInstance^.BoundsClient.W div 2;
+    CursorY := AInstance^.BoundsClient.H div 2;

    SDL_WarpMouseInWindow(AInstance^.HandleWindow, CursorX, CursorY); // center the cursor in window
    SDL_SetRelativeMouseMode(SDL_FALSE);                              // disable mouse relative mode
  end;
end;
```

Calling `SDL_WarpMouseInWindow` ***will not*** generate a `SDL_MOUSEMOTION` and this is by design. But the internal SDL mouse position (queried by `SDL_GetMouseState`) will update (and so will the position of the Windows cursor).

I suggest you modify your cursor drawing function to use `SDL_GetMouseState` and that you manually force it to update the position when you manually warp the cursor.

**Comment by furious-programming** [comment]
> I've taken a closer look at your code, and your warping logic is incorrect, `SDL_WarpMouseInWindow` already moves the cursor relative to the window top left corner.

The logic for calculating the target position of the cursor is correct because `AInstance^.BoundsClient` contains an area inside the window and its upper left corner may have coordinates other than `0.0` (if the window aspect ratio is different than the internal back buffer aspect ratio). That is why the coordinates of the upper left corner are added to the half of the window size, and if I do not, the position will be calculated incorrectly.

> No idea why it works properly when relative is disabled.

I don't know either, that's why I'm reporting it as a bug.

> Calling `SDL_WarpMouseInWindow` _**will not**_ generate a `SDL_MOUSEMOTION` and this is by design. But the internal SDL mouse position (queried by `SDL_GetMouseState`) will update (and so will the position of the Windows cursor).

I don't understand why. If relative mode is disabled, the `SDL_WarpMouseInWindow` function generates an event, and if it is enabled, it doesn't. It seems inconsistent to me, especially since — as you say — the internal position of the cursor for SDL does not coincide with the real position of the cursor in the window.
 
> I suggest you modify your cursor drawing function to use `SDL_GetMouseState` and that you manually force it to update the position when you manually warp the cursor.

I don't have any custom cursor rendering code yet — I use the system cursor to confirm that my code and calculations are working correctly. And well, I found a bug related to cursor warping, not in my calculations.

I store data about the mouse (and other input devices) in my own structures and update it based on events generated by SDL. All because the state of all manipulators (buttons, axes, hats, wheels, etc.) from all devices is kept in such a way as to have access to their previous and current state. Thanks to this, I have a full range of possibilities, which is very valuable to me.

**Comment by Susko3** [comment]
One question: why are you toggling relative mode in the first place?

> it will not be possible to move the cursor outside the BoundsClient area

This is a perfect opportunity to have only relative mode on, and to make use of [`SDL_SetWindowMouseRect`](https://wiki.libsdl.org/SDL_SetWindowMouseRect). In relative mode, SDL will still keep an _absolute_ pointer position (and that position will update when you call `SDL_WarpMouseInWindow`). You can use that to position your mouse pointer, with the caveat that you won't get an event, see https://github.com/libsdl-org/SDL/issues/5609 and https://github.com/libsdl-org/SDL/commit/b44241ab2f626965912d419f6406b9336fe7969c.

If you use relative mouse mode the OS cursor position is invalid and not important, make your own cursor code (even a simple rectangle) before validating that this works.

**Comment by slouken** [comment]
Also, can you reproduce this with the testsprite2 program that comes with SDL?

I modified the SDL code with the following patch, and ran testsprite2 and used Ctrl-R to toggle relative mode, and each time relative mode was turned off, the mouse was centered in the window.
```diff
diff --git a/src/test/SDL_test_common.c b/src/test/SDL_test_common.c
index c86742cd4..196313ce6 100644
--- a/src/test/SDL_test_common.c
+++ b/src/test/SDL_test_common.c
@@ -2059,6 +2059,14 @@ SDLTest_CommonEvent(SDLTest_CommonState * state, SDL_Event * event, int *done)
         case SDLK_r:
             if (withControl) {
                 /* Ctrl-R toggle mouse relative mode */
+                if (SDL_GetRelativeMouseMode()) {
+                    SDL_Window *window = SDL_GetWindowFromID(event->key.windowID);
+                    if (window) {
+                        int w, h;
+                        SDL_GetWindowSize(window, &w, &h);
+                        SDL_WarpMouseInWindow(window, w / 2, h / 2);
+                    }
+                }
                 SDL_SetRelativeMouseMode(!SDL_GetRelativeMouseMode() ? SDL_TRUE : SDL_FALSE);
             }
             break;

```

**Comment by slouken** [comment]
BTW, you can test with the latest SDL snapshot:
https://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by furious-programming** [comment]
> One question: why are you toggling relative mode in the first place?

Because the relative mode is needed only when the player will use the mouse to control the hero (in the form of a virtual analog stick, for which I only need `xrel` and `yrel` to update), while if he will play on the keyboard or controller, the relative mode will not be used at all.

Second, the relative mode in its nature keep the cursor in the window area, what bothers me, because my game will have a built-in map/objects editor, which will ultimately be handled in two separate windows (on two screens). If I use the relative mode, I won't be able to move the cursor between the windows.

> This is a perfect opportunity to have only relative mode on, and to make use of [`SDL_SetWindowMouseRect`](https://wiki.libsdl.org/SDL_SetWindowMouseRect).

I am using this function currently. When controlling the hero with the mouse, the cursor will not be visible, and if the player presses the required button (`start` button), the container with items will open, which can be operated with the mouse — then the custom cursor will be rendered and the area of its movements clipped to the `AInstance^.BoundsClient`.

> In relative mode, SDL will still keep an _absolute_ pointer position (and that position will update when you call `SDL_WarpMouseInWindow`). You can use that to position your mouse pointer, with the caveat that you won't get an event, see #5609 and [b44241a](https://github.com/libsdl-org/SDL/commit/b44241ab2f626965912d419f6406b9336fe7969c).

If nothing changes, I will have to find a solution, so I will try to do something so that when I turn off relative mode, my cursor appears immediately at the intended place. Nevertheless, I would like to use SDL-generated mouse events to update mouse data so that I have one consistent mechanism for retrieving input devices data, without manually polling for their status.

**Comment by furious-programming** [comment]
My actual project already has thousands of lines, so to make sure it's not my code that's causing the problems, I wrote a simple test application:

```pascal
{$MODE OBJFPC}{$LONGSTRINGS ON}

uses
  SDL2;
var
  Window:   PSDL_Window;
  Event:    TSDL_Event;
  WindowW:  Integer;
  WindowH:  Integer;
  Relative: Boolean = False;
  Done:     Boolean = False;
begin
  SDL_Init(SDL_INIT_EVERYTHING);
  Window := SDL_CreateWindow('test', SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, 0);

  while not Done do
  begin
    SDL_PumpEvents();

    while SDL_PollEvent(@Event) = 1 do
    case Event.Type_ of
      SDL_WINDOWEVENT:
        Done := Event.Window.Event = SDL_WINDOWEVENT_CLOSE;

      SDL_MOUSEBUTTONDOWN:
        if Event.Button.Button = SDL_BUTTON_LEFT then
        begin
          Relative := not Relative;

          if not Relative then
          begin
            SDL_GetWindowSize(Window, @WindowW, @WindowH);
            SDL_WarpMouseInWindow(Window, WindowW div 2, WindowH div 2);
          end;

          SDL_SetRelativeMouseMode(TSDL_Bool(Relative));
        end;
    end;

    SDL_Delay(20);
  end;

  SDL_DestroyWindow(Window);
  SDL_Quit();
end.
```

Left mouse button to toggle relative mode. When disabling relative mode, the cursor moves to some random position instead of to the center of the window. If I remove the code that centers the cursor:

```pascal
      SDL_MOUSEBUTTONDOWN:
        if Event.Button.Button = SDL_BUTTON_LEFT then
        begin
          Relative := not Relative;

          //if not Relative then
          //begin
          //  SDL_GetWindowSize(Window, @WindowW, @WindowH);
          //  SDL_WarpMouseInWindow(Window, WindowW div 2, WindowH div 2);
          //end;

          SDL_SetRelativeMouseMode(TSDL_Bool(Relative));
        end;
    end;
```

SDL itself does not center it when turning off the relative mode.

I add the project sources (for FPC/Lazarus) and the executable file with SDL2 dll file version 2.0.22 to the attachments (inside the `bin` folder). If you want me to test a new version of the library, please provide the newly compiled `sdl2.dll` file and then I will test it on my own.

**Comment by slouken** [comment]
It looks like this is fixed for the next release. Here is a built DLL from current main SDL:
[SDL2.zip](https://github.com/libsdl-org/SDL/files/9271218/SDL2.zip)

**Comment by furious-programming** [comment]
Yes, I can confirm that in the SDL 2.23.1.0, the `SDL_WarpMouseInWindow` function works like a charm.

But still there is a problem with the `SDL_HINT_MOUSE_RELATIVE_MODE_CENTER` hint — no matter if it is set to `0` or `1`, relative mouse mode _**never**_ constrains the mouse to the center of the window. So still something is wrong.

**Comment by slouken** [comment]
That hint controls whether the physical mouse is constrained, not whether the SDL mouse coordinates are constrained. If you want the SDL mouse limited to a specific area, you can use `SDL_SetWindowMouseRect()`

**Comment by furious-programming** [comment]
Okay, I will investigate how it works in practice on my own. Meanwhile, thank you very much for your help and patience.
