### ISSUE TITLE
[hidapi] Whitelisting for libusb-only devices

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#6005]
We've had support for Nintendo's official GameCube adapter for a while...

https://github.com/libsdl-org/SDL/blob/main/src/joystick/hidapi/SDL_hidapi_gamecube.c

... but the big problem that's always kept it locked away is that it _requires_ libusb. This is because while it _looks_ like a HID, it doesn't _act_ like one: You have to manually initialize it with a magic number, then it suddenly starts acting like a real input device. This means the normal paths are out of the question (with the exception of writing support into the kernel, which is way out of my league and I don't know anyone else that wants to do it), and since libusb is [too aggressive to enable by default](https://github.com/libsdl-org/SDL/issues/5722#issuecomment-1139748983) most developers ship without it.

But from what I recall, it only takes exclusive control once you open the device, not during enumeration (unless you go out of your way to enable a flag that detaches drivers during enumeration). On top of that, the way we enumerate in SDL is by [getting the libusb devices first, then the platform implementation next](https://github.com/libsdl-org/SDL/blob/main/src/hidapi/SDL_hidapi.c#L1172). So I wonder if, for platforms with non-libusb backends, we could make a whitelist for devices that require libusb and then ignore the rest of what the backend finds, with the expectation that the platform API will pick those up the Proper Way(TM).

Odds are this would just be for WUP-028, but I wonder if there are other devices out there like this? In any case, this seems like the best way to achieve [the ultimate goal for SteamOS controller support](https://nintendo.fandom.com/wiki/DK_Bongo) provided the idea actually works.

CC: @slouken

**Comment by slouken** [comment]
Yeah, that sounds like a good idea to me.

**Comment by flibitijibibo** [comment]
Going to try and write this either tonight or tomorrow - FNA's been shipping with libusb for a while so we have _more_ than enough test data on our end to work with here.
