### ISSUE TITLE
Build fails on Android with latest NDK

### ISSUE THREAD

**Issue by akb825** [libsdl-org/SDL#6019]
When building SDL 2.0.22 on Android with the latest NDK, I'm seeing the following error:

```
/home/vsts/work/1/s/build/SDL2-2.0.22/src/core/android/SDL_android.c:515:13: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    JNIEnv *env = NULL;
            ^
/home/vsts/work/1/s/build/SDL2-2.0.22/src/core/android/SDL_android.c:2564:13: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    jstring jpermission = (*env)->NewStringUTF(env, permission);
```

It looks like this warning is explicitly enabled in the root CMakeLists.txt if the compiler supports it. I'm wondering if it wasn't supported until a recent release.

**Comment by slouken** [comment]
This should be fixed, can you try with the most recent snapshot?
https://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by akb825** [comment]
When I double checked before that it was present it turned out I wasn't looking at the latest master, it looks like it was fixed on 5/28. I can apply that as a patch on my end until it's available in the next release.

**Comment by akb825** [comment]
@slouken unfortunately I'm just getting another error later in the build. This also happens with the snapshot you linked. This is due to including the cpu-features.c file from the NDK directly into the project while applying the flags used for normal SDL code. The errors are:

```
/usr/local/lib/android/sdk/ndk/25.0.8775105/sources/android/cpufeatures/cpu-features.c:514:5: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    struct { uint32_t tag; uint32_t value; } entry;
    ^
/usr/local/lib/android/sdk/ndk/25.0.8775105/sources/android/cpufeatures/cpu-features.c:559:11: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    char* cpuFeatures = extract_cpuinfo_field(cpuinfo, cpuinfo_len, "Features");
          ^
/usr/local/lib/android/sdk/ndk/25.0.8775105/sources/android/cpufeatures/cpu-features.c:848:19: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
            char* value_end = value + strlen(value);
                  ^
/usr/local/lib/android/sdk/ndk/25.0.8775105/sources/android/cpufeatures/cpu-features.c:729:18: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
        uint32_t hwcaps = getauxval(AT_HWCAP);
                 ^
```

You can see the upstream file here: https://android.googlesource.com/platform/ndk/+/master/sources/android/cpufeatures/cpu-features.c

For now I'll probably patch out the block setting werror for declaration after code.

**Comment by slouken** [comment]
Can you submit a pull request for that change? I think we want to make that change for release here as well.

Thanks!

**Comment by akb825** [comment]
I assume you want the warning disabled for Android but still enabled for other platforms?

**Comment by slouken** [comment]
Yes please, with a comment as to why it's necessary to disable the warning.
