### ISSUE TITLE
SDL_GetDisplayName returns empty string for main display device

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#6031]
Windows 10, 64-bit.

The last stable version of the SDL library, marked as version `2.0.22.0`, can return the correct names of display devices. Simple code as below:

```pascal
var
  DeviceIndex: Integer;
  DeviceName:  PChar;
begin
  for DeviceIndex := 0 to SDL_GetNumVideoDisplays() - 1 do
  begin
    DeviceName := SDL_GetDisplayName(DeviceIndex);

    if DeviceName <> nil then
      WriteLn(DeviceIndex, ' - "', DeviceName, '"')
    else
      WriteLn(DeviceIndex, ' - "', SDL_GetError(), '"');
  end;
end;
```
displays valid device names:

```
0 - "LCD 1280x800"
1 - "Generic PnP Monitor"
```
The first is the laptop display, the second is an external monitor connected to the laptop.

On the occasion of the last issue, a fresh version binary marked `2.23.1.0` was released ([in this comment](https://github.com/libsdl-org/SDL/issues/6002#issuecomment-1206802715)) and in this version the `SDL_GetDisplayName` function no longer returns the correct device names. The same test code as above, returns an **empty string** for the main display, and a valid string for an additional one:

```
0 - ""
1 - "Generic PnP Monitor"
```
The documentation says that in case of an incorrect display index or failure, the function returns `null`. In my case, the function returns a valid pointer, but the string is empty (null-character only). A bug has crept in somewhere.

**Comment by icculus** [comment]
This was probably caused by 9a0367675f44821c69b60341eed539fdfd13e7e7 ... I'm looking into this.

**Comment by icculus** [comment]
Okay, it's not clear what's going wrong here, but if it returned something that isn't NULL it means it got all the way through the process without failing, so it's possible there _isn't_ a human-readable display name provided...?

The obvious workaround (and good defensive policy in general) would be for this to notice the string is empty, and treat that as a failure, so it uses the original code we now treat as a fallback path.

**Comment by furious-programming** [comment]
Wait a minute, because I don't understand something here. My hardware configuration provides access to human-readable names of both display devices. The main screen of the laptop got a name and it is `LCD 1280x800`. This name is available in the **Device Manager**:

![Device Manager](https://user-images.githubusercontent.com/8170730/183925001-9544a0de-d478-4e12-9445-afacda2f667c.png)

It is also available in any other computer information listing software such as **Speccy**:

![Speccy](https://user-images.githubusercontent.com/8170730/183924197-70ba24e9-72e7-4440-adc2-e422c4cf2fb5.png)

So the problem is not that SDL returns an empty string, but that it cannot read the display name correctly anymore. The last stable version of SDL — which is `2.0.22.0` — was able to do this, so there is a problem with the current SDL code.

**Comment by icculus** [comment]
> so there is a problem with the current SDL code.

And does the latest (as of an hour ago) give you the expected name, again?

If we get garbage from the OS with the new method, we fall back to trying the method we used in 2.0.22.

**Comment by furious-programming** [comment]
It's not the point. I haven't tested the sources ”from an hour ago” — I'm just answering what you wrote in the previous comment that there is no human-readable display name for the main screen.

I will check new sources and if there is any problem, I will let you know. Thank you for your intervention on this topic.

**Comment by icculus** [comment]
> I will check new sources and if there is any problem, I will let you know. Thank you for your intervention on this topic.

No worries, we'll make sure this isn't broken for you before we ship 2.24.0.  :)
