### ISSUE TITLE
Mouse jitter fix seems to cause perpetual panning in Minetest

### ISSUE THREAD

**Issue by ndren** [libsdl-org/SDL#6034]
Minetest is being ported to SDL, and I was hoping that would mean suitable Wayland support. The last thing that I can see needs fixing is mouse input. I am testing with SDL_VIDEODRIVER=wayland.
Before patching the game to set relative mouse mode, [Minetest's reliance on mouse warping](https://github.com/minetest/irrlicht/blob/master/source/Irrlicht/CIrrDeviceSDL.h#L145) meant that any time the mouse is moved away from the centre it would not be warped back and so the [screen would rotate permanently](https://bun.filedit.ch/QfKpyClBEuxgSSzxKIPH.mp4), proportional to the distance from the center of the screen. 

When switching to relative mouse mode, which seemed to fix the problem for the most part, the new code introduced [jitter on both X and Wayland](https://bun.filedit.ch/fCjvWtNdwGYkATSvSH.mp4).

I then built and used a later version of SDL, bdc7f958fda50305744dcefdccac29373da97d01, which removed the jitter but now [the screen again keeps panning permanently](https://bun.filedit.ch/cqbXHQqwOXaTNQCTmfGS.mp4), now seemingly proportional to the speed of the last mouse movement. I am not sure, but this may be related to the fix for #5609.

To reproduce (It is very similar to build upstream's version without relative mouse mode, but note that https://github.com/ndren/irrlicht/commit/542c8082962152307e3f29232fcf0d33ff80c0eb is required to make sure that Minetest builds and runs with SDL):

```
git clone https://github.com/ndren/minetest --depth=1
cd minetest/lib/
git clone https://github.com/ndren/irrlicht irrlichtmt --branch=defaulttosdl --depth=1
cd ..
cmake .
make -j$(nproc)
echo 'Test by running ./bin/minetest'
```

**Comment by slouken** [comment]
Thanks for the great reproduction steps. I can actually reproduce this under X11, so I don't think it's specific to Wayland.

**Comment by ndren** [comment]
Sorry for being a bit unclear, the reason why I mentioned Wayland is because the version from upstream works fine on X, and pans perpetually on Wayland, and changes in my fork (enabling relative mouse mode) cause jitter on both but makes them behave roughly the same (SDL 2.0.22-2, Arch). This ends up with more results on different SDL versions as well.

If you rebuild without https://github.com/minetest/minetest/commit/34cb3ae6ad7992e3e5961851fe78f95ca1db135f (or just cloning https://github.com/minetest/minetest) that should give you upstream's behaviour as described above, except for defaulting to the SDL driver, since the code I added to Irrlicht does not get called internally.

What I am trying to figure out is a way to get upstream's behavior on X on Wayland as well, and whether that would mean doing something other than setting relative mouse mode inside Minetest or if this is something SDL can handle better internally. I understand this is a complex problem given mouse warping on Wayland. Thanks!

**Comment by slouken** [comment]
I have a solution, I'll provide details shortly.

**Comment by slouken** [comment]
So the problem is that the engine is expecting a mouse motion event after the warp, which SDL doesn't do when relative mode is enabled.

Here's an engine patch to fix this:
```diff
diff --git a/source/Irrlicht/CIrrDeviceSDL.h b/source/Irrlicht/CIrrDeviceSDL.h
index d7ac203..2843b00 100644
--- a/source/Irrlicht/CIrrDeviceSDL.h
+++ b/source/Irrlicht/CIrrDeviceSDL.h
@@ -146,6 +146,12 @@ namespace irr
                        virtual void setPosition(s32 x, s32 y) _IRR_OVERRIDE_
                        {
                                SDL_WarpMouseInWindow(Device->Window, x, y);
+
+                               if (SDL_GetRelativeMouseMode()) {
+                                       // There won't be an event for this warp
+                                       Device->MouseX = x;
+                                       Device->MouseY = y;
+                               }
                        }
 
                        //! Returns the current position of the mouse cursor.
```
In the course of investigating this I found the cause of the mouse jitter in the video and fixed that.

I also added a hint, SDL_HINT_MOUSE_RELATIVE_WARP_MOTION, to enable the behavior the engine is expecting, so alternatively, you could do:
```
    SDL_SetHint(SDL_HINT_MOUSE_RELATIVE_WARP_MOTION, "1");
```
before the call to `SDL_Init()` in the engine.
