### ISSUE TITLE
Incorrect modifier flags in Wayland key events

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#6037]
When using the Wayland backend, key events contain incorrect modifiers in certain cases.

For example, when pressing Left Ctrl, Alt, Shift then releasing Left Shift, Alt, and Ctrl, the expected key events (as generated by the X11 backend) are:
```
SDL EVENT: SDL_KEYDOWN (timestamp=10334 windowid=2 state=pressed repeat=false scancode=224 keycode=1073742048 mod=64) - KMOD_LCTRL
SDL EVENT: SDL_KEYDOWN (timestamp=10851 windowid=2 state=pressed repeat=false scancode=226 keycode=1073742050 mod=320) - KMOD_LALT, KMOD_LCTRL
SDL EVENT: SDL_KEYDOWN (timestamp=11463 windowid=2 state=pressed repeat=false scancode=225 keycode=1073742049 mod=321) - KMOD_LSHIFT, KMOD_LALT, KMOD_LCTRL
SDL EVENT: SDL_KEYUP (timestamp=12501 windowid=2 state=released repeat=false scancode=225 keycode=1073742049 mod=320) - KMOD_LALT, KMOD_LCTRL
SDL EVENT: SDL_KEYUP (timestamp=13079 windowid=2 state=released repeat=false scancode=226 keycode=1073742050 mod=64) - KMOD_LCTRL
SDL EVENT: SDL_KEYUP (timestamp=13594 windowid=2 state=released repeat=false scancode=224 keycode=1073742048 mod=0) - None
```

However, Wayland seems to set both left and right modifiers of each type. Pressing and releasing keys in the same sequence yields:
```
SDL EVENT: SDL_KEYDOWN (timestamp=130851 windowid=2 state=pressed repeat=false scancode=224 keycode=1073742048 mod=64) - KMOD_LCTRL
SDL EVENT: SDL_KEYDOWN (timestamp=131613 windowid=2 state=pressed repeat=false scancode=226 keycode=1073742050 mod=448) - KMOD_LALT, KMOD_LCTRL, **KMOD_RCTRL**
SDL EVENT: SDL_KEYDOWN (timestamp=132227 windowid=2 state=pressed repeat=false scancode=225 keycode=1073742049 mod=961) - KMOD_LSHIFT, KMOD_LALT, **KMOD_RALT**, KMOD_LCTRL, KMOD_RCTRL
SDL EVENT: SDL_KEYUP (timestamp=134168 windowid=2 state=released repeat=false scancode=225 keycode=1073742049 mod=962) - **KMOD_RSHIFT**, KMOD_LALT, KMOD_RALT, KMOD_LCTRL, KMOD_RCTRL
SDL EVENT: SDL_KEYUP (timestamp=134936 windowid=2 state=released repeat=false scancode=226 keycode=1073742050 mod=704) - **KMOD_RALT**, KMOD_LCTRL, KMOD_RCTRL
SDL EVENT: SDL_KEYUP (timestamp=135509 windowid=2 state=released repeat=false scancode=224 keycode=1073742048 mod=128) - **KMOD_RCTRL**
````

Setting both left and right modifiers is probably fine in the case that we can't tell them apart (though Wayland generally _can_ tell them apart), but real problem is in the key up events. The `SDL_KEYUP` for each of the left-side modifiers has the modifier flags set as if the corresponding right-side modifier was currently down even though neither side is actually down.

I suspect this bug was introduced in 2891f0821b27012242c30759308bd8eed83d3fe7 (tweaked in 7a1c45bd1c62d7cf9e5cd67633e1f5db8a7752f7).

**Comment by slouken** [comment]
@flibitijibibo, is this something you can look at really quick?

**Comment by flibitijibibo** [comment]
Probably not until after the cutoff date, but I'm not aware of a way to check left/right mods, from what I remember about those commits xkb/Wayland just care about the state, not the key that caused the state to change.

**Comment by slouken** [comment]
@cgutman, if you have a PR to fix this, we can include that in 2.24.0.

**Comment by cgutman** [comment]
I have some possible ideas, but nothing I would feel comfortable shipping in 2.24.0 without knowing much more about what those commits were fixing.

**Comment by Kontrabant** [comment]
> Probably not until after the cutoff date, but I'm not aware of a way to check left/right mods, from what I remember about those commits xkb/Wayland just care about the state, not the key that caused the state to change.

Yeah, Wayland reports if a modifier is _active_ as opposed to any particular key being down, so it will basically tell you that, say, the shift modifier is active, but it doesn't report any specific keystate as shift being active doesn't necessarily correspond to the actual shift key being down.

Decoupling modifier states from the idea that they correspond to a particular physical key being pressed might be something to address in SDL3, as in a world of key remapping and virtual keyboards, modifier state is not necessarily correlated with keys being pressed.  For example, someone might set a key that toggles the shift state to be on without one of the shift keys actually being pressed, and in this state physically pressing the shift key may actually turn the shift modifier off in spite of the key being down.

**Comment by slouken** [comment]
This seems like a good idea to me. @flibitijibibo? @Kontrabant?

**Comment by flibitijibibo** [comment]
Gets a +1 from me!

**Comment by Kontrabant** [comment]
Sounds good to me.  +1

**Comment by diagonalisability** [comment]
Alright cool, I'll be working on this then.

**Comment by flibitijibibo** [comment]
Fixed by https://github.com/libsdl-org/SDL/commit/7c7cd2a605a0ad84184d323d6f10d79255aac3a9
