### ISSUE TITLE
Error: cputype does not match previous archive members cputype

### ISSUE THREAD

**Issue by paulocoutinhox** [libsdl-org/SDL#6041]
Hi,

Im getting this error:

```
cputype does not match previous archive members cputype
```

Anyone knows what can be wrong?

Full Log:
https://c3i.jfrog.io/c3i/misc/logs/pr/12186/3-configs/macos-m1-clang/sdl/2.0.22//1a51b3c2bef48f2ff0b3b07f7f42471608784267-build.txt

It is attached too:

[1a51b3c2bef48f2ff0b3b07f7f42471608784267-build.txt](https://github.com/libsdl-org/SDL/files/9329184/1a51b3c2bef48f2ff0b3b07f7f42471608784267-build.txt)

**Comment by slouken** [comment]
It sounds like you had a previous build for x86 architecture and are now building for arm64. I'm guessing you need to do a clean build?

**Comment by paulocoutinhox** [comment]
Hi,

It is a clean build from Github Action:
https://github.com/conan-io/conan-center-index/pull/12186

The log:
https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/12186/3-configs/macos-m1-clang/sdl/2.0.22//summary.json

**Comment by madebr** [comment]
With a bit of googling, I found out cputype 16777223 means “x86 64” and cputype 16777228 means "arm64".
So it looks like a lot of files are compiled as arm64 where they should have been compiled as x86_64.
I compared the logs with the logs of building 2.0.20 at https://github.com/conan-io/conan-center-index/pull/12018 and could not find a significant difference.

https://c3i.jfrog.io/c3i/misc/logs/pr/12018/1-configs/macos-m1-clang/sdl/2.0.20//fe30d62a63b5cde6e530feb6fb1b3dc2de680103-build.txt
[fe30d62a63b5cde6e530feb6fb1b3dc2de680103-build.txt](https://github.com/libsdl-org/SDL/files/9329659/fe30d62a63b5cde6e530feb6fb1b3dc2de680103-build.txt)

Can you check whether the previous sdl version(s) still build fine with the current build configuration?
If those still build fine, can you enable verbose building so we can see what compile flags are being used.

**Comment by paulocoutinhox** [comment]
Hi @madebr,

In my local machine it compile without problems.

Log is attached:
[sdl.txt](https://github.com/libsdl-org/SDL/files/9331761/sdl.txt)

**Comment by paulocoutinhox** [comment]
Hi @madebr,

How can i enable verbose in conan CI?

Thanks.
