### ISSUE TITLE
Pre-release 2.23.2 missing Windows binaries?

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL#6047]
The 2.23.1 pre-release had `SDL2-2.23.1-win32-x64.zip` and `SDL2-2.23.1-win32-x86.zip` archives containing binaries for testing on Windows, but the 2.23.2 pre-release doesn't have these. Can these please be added for the new pre-release as well?

Thanks in advance!

**Comment by slouken** [comment]
Added!
