### ISSUE TITLE
[iOS] shared library is missing some public symbols

### ISSUE THREAD

**Issue by kambala-decapitator** [libsdl-org/SDL#6059]
When I build shared library or framework for iOS (Xcode project or CMake, doesn't matter), then the resulting binary doesn't have `SDL_iPhoneSetEventPump` and `SDL_iPhoneSetAnimationCallback` symbols. Initially I noticed it when linking of my project failed, then checked with `nm -g`. With static library there's no such issue.

The only workaround I found is to enforce default visibility by passing `GCC_SYMBOLS_PRIVATE_EXTERN=NO` to `xcodebuild` invocation.

Checked in 2.0.22 release and the latest `main`.

**Comment by slouken** [comment]
I didn't see this issue here, but I did see the header declaring them wasn't included. Does this fix it for you? https://github.com/libsdl-org/SDL/commit/0cc8dfdb58b60e1ffc285025b7f1ed884a378601

**Comment by kambala-decapitator** [comment]
yes, thanks a lot!

I didn't think of checking if the header is included :)

**Comment by slouken** [comment]
Great, thanks!
