### ISSUE TITLE
[Question] Is possible to deformate textures using SDL Render API?

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#6064]
Recently while talking about future features for my project, I got a question, does SDL Render API supports the deformation of textures? I mean, where you can specify coordinates for each corner (vertex) of the texture rectangle and draw the quadrilateral with sides of any size, and have texture being stretched into it:
![изображение](https://user-images.githubusercontent.com/6751442/184759290-d8edad7d-388f-4f91-bdb1-8fe58e478125.png)

This is used to simulate various pseudo-3D stuff.
By plain OpenGL that's absolutely possible as I have to set the coordinate of every corner.

**Comment by icculus** [comment]
You can do this with the new triangle API, using two triangles per sprite and a little math.

**Comment by Wohlstand** [comment]
> two triangles per sprite

The same I do at plain OpenGL, will try some.

**Comment by genpfault** [comment]
Note that [`SDL_RenderGeometry()`](https://github.com/libsdl-org/SDL/blob/release-2.0.22/include/SDL_render.h#L1616-L1672) only does [affine texture mapping](https://en.wikipedia.org/wiki/Texture_mapping#Affine_texture_mapping), not perspective-correct.

**Comment by Wohlstand** [comment]
Thanks for the tip
