### ISSUE TITLE
[Deck] hidapi support for Steam Virtual Gamepad

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#6068]
I keep forgetting to write this down, so I'm just doing this now... obviously not a 2.24 requirement, but:

Right now the virtual gamepad is strictly a baseline XInput device - it even claims to be an Xbox 360 controller depending on who's asking. Problem is, this actually hides a lot about the device, specifically the gyro data. Other elements like the touchpads aren't _that_ big of a deal since the mouse simulation can be made to work with either absolute or relative motion, but gyro is definitely a blind spot. This can be an issue for applications like [Citra](https://citra-emu.org/), which have full support for SDL_sensor but can't see them on Deck!

Ignoring my distaste for the virtual gamepads (RIP Steam's old gamecontrollerdb exports), I wonder if SDL can read the virtual gamepad via hidapi _as its own device_, rather than as an XInput device, so that non-SDL games aren't affected but those that _do_ use SDL can see all the hardware available, without having to resort to Steam Input which may have licensing conflicts (Citra is one such case, being GPL-licensed).

This is probably 50% SDL and 50% Valve but it would definitely be nice for us to expose all the hardware to third-party applications, if possible.

**Comment by flibitijibibo** [comment]
Something else that's come to mind... by being able to read the device more directly, it would also allow us to dig up a lot of data about the hardware behind it. As an example: Initialization could encode the SDL_GameControllerType into the input stream, and would allow us to show the right glyphs without having to force Steam Input off (something that's bothered me pretty much since the beginning!).

**Comment by slouken** [comment]
As far as I know uinput doesn't allow passing metadata like the original game controller type through the interface, but Steam did recently add the slot index to the end of the name, and could potentially add some controller type metadata there.

It might be possible for uinput to create a gyro input device, I'm not sure how that works, but even if that happened, SDL doesn't currently support opening a controller via separate devices for different functionality. Adding support for the gyro on PlayStation controllers using the Linux input driver might be a good first step towards prototyping this.

**Comment by mubinulhaque** [comment]
Has anyone looked into the #streetpea/chiaki4deck#7 code? It seems they have managed to reverse-engineer gyro controls on Steam Deck, which could potentially fix this issue.

**Comment by slouken** [comment]
We haven't come up with a solution for passing metadata through uinput. I'm going to close this for now, feel free to reopen it if you have any ideas!
