### ISSUE TITLE
SDL2 (2.0.22 x86_64-w64-mingw32) do not compile on windows due to SDL_main

### ISSUE THREAD

**Issue by van3ll0pe** [libsdl-org/SDL#6069]
Hi,

I download the SDL2-devel-2.0.22-mingw folder, to execute a SDL program on windows 10.

On windows, I used mingw-w64 available on the website : https://winlibs.com/

I used the folders (bin/include/lib) present on the folder "x86_64-w64-mingw32" of the folder SDL2.
When I compiled I had an error with the prototype of the function SDL_main from the file SDL_main.h when I included the SDL.h file on my project.

Here to command that I used to compile:
![image](https://user-images.githubusercontent.com/96663251/184974377-3ba2d54d-16f1-4487-93af-bee1c712cb5f.png)

![image](https://user-images.githubusercontent.com/96663251/184973744-bf239532-cde0-47ad-a0b9-c1cf7d0db641.png)

To make my program work properly I put in comment the prototype of the function SDL_main in the file SDL_main.h at line 130

**Comment by van3ll0pe** [comment]
Same error if I use the folders "bin", "include" and "lib" from the folder "i686-w64-mingw32"

**Comment by madebr** [comment]
The warning/error is due to a conflict between the `SDL_main` prototype in the `SDL_main.h` header and your main method.

Change your `main` method from
```c
int main() {
    ...
}
```
to
```c
int main(int argc, char *argv[]) {
    ...
}
```
