### ISSUE TITLE
SDL_GL_BindTexture doesn't bind all textures with the opengles2 renderer

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#6070]
When using the opengl renderer, calling SDL_GL_BindTexture will bind all of the textures used by planar formats like SDL_PIXELFORMAT_YV12. When using the opengles2 renderer instead, it will only bind the texture containing the Y plane and not any of the others.

**Comment by slouken** [comment]
I think this is an oversight. Feel free to contribute a tested PR.

**Comment by icculus** [comment]
I'll fix this in 2.26 if @ccawley2011 doesn't beat me to it.
