### ISSUE TITLE
SetWindowGrab stopped working

### ISSUE THREAD

**Issue by matthiakl** [libsdl-org/SDL#6072]
After updating to 2.0.22, `SDL_SetWindowGrab(win, SDL_TRUE)` causes a strange behavior regarding the cursor:
1. The mouse can leave the window
2. Upon reentering it is grabbed correctly until a mouse button is pressed
3. After the button press the mouse can leave the window again.
4. back to 2.

System: Arch Linux, X11

**Comment by slouken** [comment]
Can you test on the latest prerelease?
https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.23.2

**Comment by matthiakl** [comment]
It is still present with a freshly build version from main branch.

**Comment by slouken** [comment]
Fixed, thanks!
