### ISSUE TITLE
Unknown memory leak

### ISSUE THREAD

**Issue by hellcutie** [libsdl-org/SDL#6076]
## Hello there. There is one small issue.

Working with SDL2 2.0.22-2 (from Arch Linux) I've noticed that there's an unknown memory leak.
So, with knowledge about my programming skills I've written a small code just to test that there's no problems:

```c++
int main(void) {
    
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window* win;
    SDL_Renderer* ren;

    SDL_CreateWindowAndRenderer(640, 480, SDL_WINDOW_SHOWN, &win, &ren);

    bool running = true;
    SDL_Event event;
    while (running) {
        while (SDL_PollEvent(&event) != 0) {
            if (event.type == SDL_QUIT) {
                running = false;
            }
        }

        SDL_RenderClear(ren);
        SDL_RenderPresent(ren);
    }
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    SDL_Quit();
}
```

I've compiled that code with following:
`g++ -fsanitize=address -std=c++20 main.cpp -o main 'pkg-conf --libs sdl2' 'pkg-conf --cflags sdl2'`

And yes. After startup process called `main` started to consume memory in geometrical progression (after 5 seconds it consumed 100+MiB of RAM)
![Screenshot from 2022-08-17 22-01-16](https://user-images.githubusercontent.com/110689538/185221539-03b27e11-d277-40e4-8557-6eff401f7244.png)

I'll send here my specs, sanitizer output, etc. here if it's needed, but I feel like there's a big leak on the side of SDL2.

If anywhere is my fault, please, explain and help to fix that. I'm using GNOME Wayland session.

Cheers, Alice.

**Comment by slouken** [comment]
@icculus, can you check to see if there's a regression here?

**Comment by hellcutie** [comment]
Regression? Do you mean like... "is consumption falls down after n time"?

**Comment by slouken** [comment]
No, I mean whether this is different from previous behavior.

I ran this test here and I saw memory stabilize at around 64 MB of resident memory usage, which is reasonable for a baseline graphical program.

In your case, if you let it run, does it eventually run out of memory? What is the memory usage after 30 seconds? 5 minutes?

**Comment by hellcutie** [comment]
Let me try, I'll send you results soon.

**Comment by icculus** [comment]
Running under valgrind, I see small one-time leaks inside LLVM (which Mesa uses for OpenGL shaders on this laptop)'s dlinit hook and pthread_once things, and a couple things deep under libX11...these are all either things they intend to live for the length of the process or failed to clean up, but they are not SDL bugs.

**Comment by hellcutie** [comment]
# Measurement results
- **30 seconds:** `220MiB`
- **5 minutes:** `481.6MiB`
- **Peak**: `481.6MiB`
    + Achieved after: `3.30 minutes`

**Comment by Guldoman** [comment]
> # Measurement results
> * **30 seconds:** `220MiB`
> * **5 minutes:** `481.6MiB`
> * **Peak**: `481.6MiB`
>   
>   * Achieved after: `3.30 minutes`

I can reproduce this kind of memory consumption only if compiled with the address sanitizer.
Compiled without the address sanitizer it tops out at around 19MB.

**Comment by slouken** [comment]
Ah, that makes sense. Yes, address sanitizer uses additional memory to track allocations, so this would be expected.
