### ISSUE TITLE
Mayflash Nintendo 64 adapter support

### ISSUE THREAD

**Issue by JunielKatarn** [libsdl-org/SDL#6079]
As of right now, the latest joystick DB does not include mappings for the Mayflower Nintendo 64 USB adapter.
https://www.mayflash.com/product/showproduct.php?id=19

It does seem to show up in https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt .

Is there any reason to exclude this specific mapping, or can it be added via pull request?

## See
- https://github.com/libsdl-org/SDL/blob/51be30f3cd29682cd94fcbfbe18eeac492095a05/src/joystick/SDL_gamecontrollerdb.h

**Comment by JunielKatarn** [comment]
I've found the mappings for this adapter with the original Nintendo 64 controller:
```
030000008f0e00001330000000000000,Mayflash N64 controller adapter PC043,a:b1,b:b2,start:b9,leftshoulder:b6,rightshoulder:b7,guide:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftx:a0,lefty:a1,rightx:a2,righty:a3,platform:Windows,
```

One issue to note is, it collides with [HuiJia SNES Controller](https://github.com/libsdl-org/SDL/blob/51be30f3cd29682cd94fcbfbe18eeac492095a05/src/joystick/SDL_gamecontrollerdb.h#L177).

**Comment by slouken** [comment]
I'm working on a change for SDL 2.26.0 that will allow us to create mappings for controllers with the same VID/PID to address exactly this issue. Once that's in, we can create new mappings and create PRs for them.

**Comment by slouken** [comment]
Feel free to create a PR using the latest SDL code in main, which should create mappings for the Mayflash N64 adapter that won't collide with the HuiJia SNES controller.

I'll close this for now, since we can't accept conflicting mappings upstream.

**Comment by slouken** [comment]
I backed out this mapping because of the collision with the HuiJia SNES Controller. We'll have to regenerate this mapping using the new controllermap program to get the correct CRC for the Mayflash PC043 adapter.

**Comment by JunielKatarn** [comment]
> 

Understood. I'm not familiar with this program.
Can you point me to building/downloading it to obtain the mapping data myself and share it?

**Comment by slouken** [comment]
It's a test program in the SDL source archive:
https://github.com/libsdl-org/SDL/blob/main/test/controllermap.c

The exact method to build it depends on your environment, but you can build it with Visual Studio in the VisualC directory or on the command line using configure and make in the test directory.
