### ISSUE TITLE
Enable ARM FillRect routines on ARMv4 and ARMv5 systems?

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#6088]
Unless I'm missing something obvious, the optimised FillRect functions included with the ARM SIMD blitters don't appear to use any ARMv6-specific instructions, so it might be worth separating them so that older ARM systems can make use of them.

**Comment by slouken** [comment]
Do you have a test case?

**Comment by slouken** [comment]
No response, closing for this milestone. Feel free to reopen it if you have hardware that you can use to verify functionality.
