### ISSUE TITLE
[Feature Request] PowerA Enhanced Wireless Controller (nintendo switch)

### ISSUE THREAD

**Issue by TheLadForTheJob** [libsdl-org/SDL#6092]

**Comment by slouken** [comment]
I can help you add support for this. What is the device VID/PID?

**Comment by TheLadForTheJob** [comment]
Well, the controller is bluetooth only, it doesn't work through USB so I
don't think it has a VID/PID.

**Comment by slouken** [comment]
I think we already support this controller. What platform are you running on?

**Comment by slouken** [comment]
I picked up one of these, and it looks like it works, although it's wireless-only. The wired connection is only for charging.
