### ISSUE TITLE
macOS: Blocking GL context update dispatch is inconsistent with SDL2-2.0.22

### ISSUE THREAD

**Issue by kjliew** [libsdl-org/SDL#6096]
The initial merge https://github.com/libsdl-org/SDL/pull/5708 is consistent with SDL2-2.0.22 which is non-blocking. The default changed to "blocking" in commit 3119d58ff536424c361892a0aa76f95731ea0fbc without any backing of resolved issues. If you traced the history of dispatch_async, it was included in 2.0.16 and fixed real deadlocks (https://github.com/libsdl-org/SDL/issues/3680) due to dispatch_sync https://github.com/libsdl-org/SDL/pull/4242.

QEMU featuring qemu-3dfx also reproduced deadlocks with the default "blocking" GL context update dispatch and fixed by SDL_SetHint() to "non-blocking" to match SDL2-2.0.22. That implies a potential recompile of SDL2 OpenGL applications with threaded GL context handling and those unmaintained will be forced to stay with SDL2-2.0.22.

Why was the "blocking" default preferred rather than maintaining consistency with existing SDL2 OpenGL application since 2.0.16 without forcing recompile? The given reason that "it is safer" has very vague implication compared to real deadlocks resolved by "non-blocking" dispatch_async.

**Comment by slime73** [comment]
See #5203 and #5708.

**Comment by kjliew** [comment]
@slime73 Thanks for the discussion in #5203. I was looking for such backing that resulted in the "blocking" default. #5708 actually suggested keeping the consistency with SDL2 with the "non-blocking" default.

I do agree that threaded GL handling is very difficult to debug but looking at ddnet/ddnet#4435 crashlog sounded more like issues with corrupted VBO/VAO associated with glDrawElements(). Perhaps something to do with coherency between rendering thread and another thread updating VBO/VAO. It is not uncommon that proper sync/mutex/fence object should be in-placed to ensure data coherency. A "blocking" GL context update hides such issues, so does x86 typical strong memory order.

IMHO modern OpenGL favors non-blocking, bulk dispatching and expects software to deal with coherency. The option for "blocking" behavior should only be used in aid of debugging.

**Comment by icculus** [comment]
You can set the hint and roll the dice if you think your app will be okay, but the default will remain synchronous.

**Comment by kjliew** [comment]
> You can set the hint and roll the dice if you think your app will be okay, but the default will remain synchronous.

I would argue that it wasn't as simple as that. SDL2 is a cross-platform library. If Windows/Linux OpenGL implementation is non-blocking, bulk dispatching in nature, then the same codes may deadlock on macOS. IMHO the decision making for SDL2 as cross-platform library should ideally prioritize cross-platform consistency, too.
