### ISSUE TITLE
How to create Texture and Renderer to write to the Texture without creating Surface or Window?

### ISSUE THREAD

**Issue by dustdfg** [libsdl-org/SDL#6098]
Hello!

I want to create Texture and Renderer for it but without creating Surface or Window.
I see that I need to do the following (Pseudo-code):

```
surface = SDL_CreateRGBSurface(...);
renderer = SDL_CreateSoftwareRenderer(surface);
texture = SDL_CreateTextureFromSurface(renderer, surface);
SDL_SetRenderTarget(renderer, texture);
SDL_FreeSurface(surface);
...
SDL_RenderDrawRect(renderer, ...)
```

How to avoid Surface creation? I don't need it

P.S I didn't try to start the above code so I don't know if I really need the `SDL_SetRenderTarget`

**Comment by slouken** [comment]
You don't need to create the texture or set the render target. Creating the software renderer with the surface as the output means that you can use both SDL blit/fill functions on the surface and the SDL render functions to draw to the surface. You do need the surface though, as you don't have anywhere for the rendering to go if you don't have it.

**Comment by dustdfg** [comment]
> You don't need to create the texture or set the render target. Creating the software renderer with the surface as the output means that you can use both SDL blit/fill functions on the surface and the SDL render functions to draw to the surface. You do need the surface though, as you don't have anywhere for the rendering to go if you don't have it.

I searched in internet and [found out](https://stackoverflow.com/questions/21392755/difference-between-surface-and-texture-sdl-general) that surface stores data in computermemory but texture stores data in gpu memory. So I wanted to know how to create sdl render that renders to texture without creating surface

**Comment by slouken** [comment]
There is nothing like that. You would create a normal renderer, create a texture with target access, set the render target to that texture, and then render normally. You can ask for further help on the discussion group:
https://discourse.libsdl.org/c/sdl-development/6

**Comment by dustdfg** [comment]
> There is nothing like that. You would create a normal renderer, create a texture with target access, set the render target to that texture, and then render normally. You can ask for further help on the discussion group: https://discourse.libsdl.org/c/sdl-development/6

I apologize for new message. I think that you meant renderer created with `SDL_CreateRenderer` when you wrote normal renderer. But I can't use  `SDL_CreateRenderer` without window and I don't have window...
