### ISSUE TITLE
[android] make SDLSurface public class

### ISSUE THREAD

**Issue by irov** [libsdl-org/SDL#6101]
Add the ability to inherit from the SDLSurface class. Allocate SDLSurface to a separate public class and add the createSDLSurface method to SDLActivity in order to be able to create the MySDLSurface class in your MySDLActivity

Thanks!

**Comment by slouken** [comment]
Do you want to submit a pull request for the functionality that you would like?

**Comment by irov** [comment]
Yes, i make pull request tomorrow

**Comment by irov** [comment]
https://github.com/libsdl-org/SDL/pull/6109

**Comment by slouken** [comment]
Done!
