### ISSUE TITLE
No accessible way to get Drawable Size with SDL_HINT_WINDOWS_DPI_SCALING and D3D11

### ISSUE THREAD

**Issue by NoelFB** [libsdl-org/SDL#6105]
With the new `SDL_HINT_WINDOWS_DPI_SCALING` hint in 2.24.0, SDL doesn't really have an accessible way to get the Drawable size when using D3D11 as far as I can tell.

For example, this used to work:
```c
void MyApp_GetDrawableSize(int* w, int* h)
{
    if (using_opengl)
        SDL_GL_GetDrawableSize(window, w, h);
    else if (using_vulkan)
        SDL_Vulkan_GetDrawableSize(window, w, h);
    else if (using_metal)
        SDL_Metal_GetDrawableSize(window, w, h);
    else if (using_d3d11 || using_none)
        SDL_GetWindowSize(window, w, h);
}
``` 

And this was fine because on Windows `SDL_GetWindowSize` would match the pixel size. However, with `SDL_HINT_WINDOWS_DPI_SCALING` this is not necessarily true, but SDL doesn't have a great way of getting this information anymore.

In D3D11 you can tell the SwapChain to resize the backbuffer automatically to the client size, and from there you can figure out the drawable size by querying the backbuffer texture. However, apparently [xbox has a regression](https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Driver_D3D11.c#L5407) where this doesn't work, which is why [FNA currently uses](https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Driver_D3D11.c#L5422) `SDL_GetWindowSize` to set the backbuffer size but in 2.24.0 that may not be correct.

**Comment by slouken** [comment]
We should add a function to get the window size in pixels, but in the meantime, you can get the window HWND and then call `GetClientRect()` to get the actual size in pixels.

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/00452e47fa022314b4c21af2d4e5b63a53f89b8f
