### ISSUE TITLE
Surfaces with pitch < bytes per pixel * pixels per row no longer allowed

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#6107]
I'm reporting this in case it becomes a practical problem, rather than advocating it being fixed preemptively. This issue can be closed as "won't fix" if SDL 2.24 is working as intended.

Historically, SDL didn't do much validation on the parameters used when creating a surface. However, since commit 535fdc3a (part of #5645, first released in prerelease 2.23.1), it checks that the pitch (aka rowstride) is at least the number of bytes required for a row.

While updating SDL in Debian, I discovered that the unit tests for [pysdl2](https://github.com/py-sdl/py-sdl2/) version 0.9.9 were (accidentally?) using a pitch of 16 bytes for 16x16 textures with 16 and 32 bits per pixel, which use 32 or 64 bytes (respectively) per row. This means the first few pixels of the second row address the same bytes in the memory buffer as the last few pixels of the first row, and so on, with the last bytes of the memory buffer being unused.

I *think* this was not intentionally done in pysdl2, because if it had been deliberate, then the memory buffer would have been smaller than `w * h * (bpp / 8)` bytes. It was fixed in passing by commit https://github.com/py-sdl/py-sdl2/commit/7c44df689cbe4c0f78b54af301a220f83a8ecfcf which changed the `pitch` from a fixed 16 to a dynamic `w * int(bpp.value / 8)`, which is correct for a packed memory buffer (no special padding between rows).

For now, I'm going to apply a hotfix patch to Debian's pysdl2 0.9.9 that bumps up the pitch to be equal to the amount of data needed per row, and then as a lower priority, look into upgrading it to the new upstream release 0.9.13. However, I'm opening this issue in case it reflects an (ab)use of the SDL API in real games: if it does, then SDL 2.24 might cause game regressions.

If there are real games that do this, then they will regress with SDL 2.23.x/2.24.0. We could "fix" them with:

```diff
-    minimalPitch = SDL_CalculatePitch(format, width, SDL_TRUE);
-
-    if (pitch < 0 || ((size_t) pitch) < minimalPitch) {
+    if (pitch < 0) {
```

(in two places)

---

More details:

Often an image will have no padding at all (bytes per row = bytes per pixel * pixels per row). pysdl 0.9.13's test suite looks like this. For example, a 32bpp image that is 3px wide might be stored with each 12-byte row directly following the previous row, which in SDL's terms means its pitch is 12 bytes:

```
00 01 02 03 04 05 06 07 08 09 10 11
 R  G  B  A  R  G  B  A  R  G  B  A    <- first row
12 13 14 15 16 17 18 19 20 21 22 23
 R  G  B  A  R  G  B  A  R  G  B  A    <- second row
...
```

Or, an image might have padding between the rows (bytes per row > bytes per pixel * pixels per row). The images we load and save in the SDL_image test suite were intentionally chosen to have "odd" sizes, so they look like this. For example, a 32bpp image that is 3px wide might be stored with each 12-byte row followed by 4 bytes of padding to get the beginning of the row nicely 16-byte aligned for SSE2, which in SDL's terms means its pitch is 16 bytes:

```
00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
 R  G  B  A  R  G  B  A  R  G  B  A xx xx xx xx    <- first row, xx = padding/"don't care"
16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
 R  G  B  A  R  G  B  A  R  G  B  A xx xx xx xx    <- second row
...
```

Since commit 535fdc3a, the pitch is not allowed to be strictly less than the amount of data required for a row. However, a game might conceivably have (ab)used SDL's API to have rows overlap:

```
pitch = 4 bytes
00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
 R  G  B  A  R  G  B  A  R  G  B  A                <- first row
             R  G  B  A  R  G  B  A  R  G  B  A    <- second row
...
```

or even to use the same memory for every row as a micro-optimization if the rows happen to all be identical, for example a plain black texture:

```
pitch = 0 bytes
00 01 02 03 04 05 06 07 08 09 10 11
 R  G  B  A  R  G  B  A  R  G  B  A                <- first row
 R  G  B  A  R  G  B  A  R  G  B  A                <- second row = first row
...
```

**Comment by smcv** [comment]
cc @slouken @a-hurst

@a-hurst: Was pysdl2 intentionally using overlapping rows, or was that a mistake that is fixed in recent versions?

**Comment by a-hurst** [comment]
@smcv No clue if it was originally intentional (I only took over maintenance in ~2020), but when rewriting that code I got the impression it was a genuine mistake. I caught and fixed it when I tested with the 2.23.1 pre-release binaries and got errors on those tests.

**Comment by slouken** [comment]
By the way, thank you for an excellent bug report.

I think for now let's leave it as-is. I'm betting that the 99% case will be that this catches bugs, and the 1% case will be something that is easily fixed. If we end up with an unmaintained binary that requires this behavior or someone has a good use case why they really want this behavior, let's revisit this.

Thanks!

**Comment by smcv** [comment]
See also #7970, https://github.com/libsdl-org/SDL/commit/77bcd269beccdd281789673313c4bb677e70bb12 "Allow creating an empty surface with pitch 0" which relaxed the check to allow pitch = 0 (every row occupies the same space), and https://github.com/libsdl-org/SDL/commit/d496d187c5a4a5b535fa35b38eb4fa1b439801d0 "Document that the pitch value may be zero for surfaces that will be filled in by the application later" which disallowed pitch = 0 again, except in the special case where pixels = NULL.
