### ISSUE TITLE
2.24.0: two TEST cmake variables

### ISSUE THREAD

**Issue by kloczek** [libsdl-org/SDL#6114]
Looks like cmake is using two TEST variables (from `cmake -L` output):
```console
SDL_TEST:BOOL=ON
SDL_TESTS:BOOL=ON

**Comment by kloczek** [comment]
```console
[tkloczko@devel-g2v SDL2-2.24.0]$ grep -r SDL_TEST -w
CMakeLists.txt:set(SDL_TEST   ${SDL_TEST_ENABLED_BY_DEFAULT} CACHE BOOL "Build the SDL2_test library")
CMakeLists.txt:dep_option(SDL_TESTS           "Build the test directory" OFF SDL_TEST OFF)
CMakeLists.txt:if(SDL_TEST)
CMakeLists.txt:  if(SDL_TEST)
CMakeLists.txt:  if(SDL_TEST)
CMakeLists.txt~:set(SDL_TEST   ${SDL_TEST_ENABLED_BY_DEFAULT} CACHE BOOL "Build the SDL2_test library")
CMakeLists.txt~:dep_option(SDL_TESTS           "Build the test directory" OFF SDL_TEST OFF)
CMakeLists.txt~:if(SDL_TEST)
CMakeLists.txt~:  if(SDL_TEST)
CMakeLists.txt~:  if(SDL_TEST)
```
```console
[tkloczko@devel-g2v SDL2-2.24.0]$ grep -r SDL_TESTS -w
CMakeLists.txt:dep_option(SDL_TESTS           "Build the test directory" OFF SDL_TEST OFF)
CMakeLists.txt:if(SDL_TESTS)
CMakeLists.txt~:dep_option(SDL_TESTS           "Build the test directory" OFF SDL_TEST OFF)
CMakeLists.txt~:if(SDL_TESTS)
```

**Comment by madebr** [comment]
Granted, it's not the best naming.

´SDL_TEST´ is for enabling the SDL2_test testing library:
https://github.com/libsdl-org/SDL/blob/277b033e78235d6ffad7525a1fb9acfef3a43433/CMakeLists.txt#L510

´SDL_TESTS´ is for enabling building the tests:
https://github.com/libsdl-org/SDL/blob/277b033e78235d6ffad7525a1fb9acfef3a43433/CMakeLists.txt#L513

**Comment by kloczek** [comment]
TBH `SDL_TEST` IMO is a bit misleading 🤔 
BTW .. `SDL_TEST=ON` is causing that this library is installed as well. Is that injtentional? 🤔

**Comment by madebr** [comment]
> TBH `SDL_TEST` IMO is a bit misleading :thinking:

Perhaps. The [CMake options for the other targets](https://github.com/libsdl-org/SDL/blob/50c5d23f7d1b5b15e5ecc3dce72fa6a35b68f960/CMakeLists.txt#L508-L510) are also dense so I kept them short.

> BTW .. `SDL_TEST=ON` is causing that this library is installed as well. Is that injtentional? thinking

Yes, this was intentional. Autotools also installs `SDL2_test`.
The `SDL2_test` library is used by other libraries, such as [SDL_image](https://github.com/libsdl-org/SDL_image/blob/18ca89d0f577476f2340c6ab18a312c314b1e696/test/CMakeLists.txt#L46)

**Comment by kloczek** [comment]
I'll close that thicekt.
Thank you for the explanations 😄 👍
