### ISSUE TITLE
Opinion: `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS` should default to 0

### ISSUE THREAD

**Issue by SuperSamus** [libsdl-org/SDL#6117]
As described [here](https://github.com/libsdl-org/SDL/blob/92b3c53c92971e685254fd89f89ce6bde8cea60e/include/SDL_hints.h#L532), `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS` makes the game controller face buttons report their values according to their labels instead of their positional layout.
Right now, this hint defaults to 1, but in my opinion it should default to 0.
Most players do not look at the controller while playing, and while players used to the Nintendo layout will have to rewire the brain to adjust the labels, it's definitely easier than rewiring the brain to push different buttons (with 1, if someone plays a game on Switch, then plays the same game on PC with a Switch Controller, they'd have to change the buttons to press).
It's important that the button positions are consistent between gamepads, and also games between different platforms (since the same game on Xbox and Switch map the buttons so that are in the same position (except for menus)).
Many games are also designed to have buttons in a specific layout (like the Binding of Isaac, or Inversus). Even if they aren't, many games show a gamepad layout when prompting a specific button.

**Comment by smcv** [comment]
Am I right in paraphrasing your opinion as being like this?

With `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS=1`, what primarily matters is how the button is labelled: the button at the bottom of the diamond is A on an Xbox controller or B on a Switch controller, the button at the top is Y on Xbox or X on Switch, and so on, and the game might expect you to press A to jump and Y to block, regardless of where that button is physically situated. This is good if the game displays prompts like "Press A to jump", but confusing if the game displays prompts like "Press (diagram of buttons with a highlight on the bottom one) to jump".

With `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS=0`, what primarily matters is where the button is: the game might expect you to press the button at the bottom of the diamond to jump, regardless of whether it's labelled A (Xbox), B (Switch) or cross (Playstation), and similarly press the button at the top of the diamond to block, regardless of whether it's labelled Y (Xbox), X (Switch) or triangle (Playstation). This is good if the game displays prompts like "Press (diagram of buttons with a highlight at the bottom) to jump", but confusing if the game displays prompts like "Press A to jump".

The `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS=0` model is also good for games that care about the physical layout of the ABXY buttons, like older Assassin's Creed titles which map the diamond of ABXY buttons to the player character's body (top button = head/first-person view, bottom button = legs/jump/run, left button = weapon hand/attack, right button = empty hand/grab).

Your reasoning is that the physical location of the buttons is the most important thing and their labels are secondary, similar to the way most games that are ported between Xbox and Playstation directly mirror the function of the Xbox ABXY buttons with the Playstation button that is in the corresponding position (Y = triangle and so on). Correct?

For what it's worth, the Linux kernel agrees with you: the [evdev gamepad interface](https://elixir.bootlin.com/linux/v5.19.3/source/Documentation/input/gamepad.rst) is written in terms of `BTN_NORTH`, `BTN_SOUTH`, `BTN_EAST` and `BTN_WEST` buttons, with `BTN_NORTH` aliased as `BTN_Y`, `BTN_EAST` as `BTN_B` and so on following the Xbox convention. The native Linux driver for Switch controllers, [hid-nintendo](https://elixir.bootlin.com/linux/v5.19.3/source/drivers/hid/hid-nintendo.c), maps the Switch controller's top button labelled X to Linux `BTN_NORTH`, and so on, disregarding the button labels and using the physical layout of the buttons as the thing that matters.

**Comment by SuperSamus** [comment]
You are perfectly right with your paraphrase.

**Comment by slouken** [comment]
I agree with your reasoning and I'll leave this open for further discussion, however making a change like this isn't something we should do lightly.

In the meantime, you can set the behavior you like by setting the environment variable:
`SDL_GAMECONTROLLER_USE_BUTTON_LABELS=0`
and then all games that use SDL will use positional layout instead of label layout.

**Comment by smcv** [comment]
For comparison, what does Steam Input remapping do with Nintendo controllers? Do they follow the positions or the button labels by default?

I don't currently have a Nintendo gamepad connected to any of my Steam devices, only Steam Controllers (which follow the convention that controllers designed for PC label and colour-code their buttons like an Xbox controller) and various generations of Playstation gamepads (which don't use the ABXY labels, but Steam treats them as equivalent to the Xbox button that has the corresponding position, disregarding labels and colour-coding).

**Comment by slouken** [comment]
Steam defaults to using the buttons as labeled, and has a setting to change that to positional mapping.

**Comment by smcv** [comment]
> Steam defaults to using the buttons as labeled, and has a setting to change that to positional mapping.

Consistent with current SDL (without the change proposed here), then, which makes sense.

**Comment by SuperSamus** [comment]
Steam however shows this is a GUI option, close to the one to enable the controller support in the first place. SDL's option is far less discoverable.

**Comment by Lokathor** [comment]
This seems to be approximately the same issue as https://github.com/libsdl-org/SDL/issues/6665, which I closed because a majority of the commenters seemed to be against the idea.

**Comment by SuperSamus** [comment]
Bump, is anything changing with SDL3?

**Comment by Squall-Leonhart** [comment]
> Bump, is anything changing with SDL3?

I hope not.

**Comment by SuperSamus** [comment]
So, a recap.

Problem with PC gaming: when playing with a Nintendo controller, the prompts don't match the buttons you press.
Is it severe? Not really, people don't look at the controller once they understood the controls.
Still, are there some solutions?

1. Change the prompts to match the buttons. This is what you get when playing on a Nintendo console (only exception is confirm/cancel). Some games on PC offer this.
2. Change the mapping to match the prompts. This creates more problems than it solves, because now you are playing a game with a mapping that the developer didn't intend. If the player is also used to playing with another controller (or the same game on console, including a Nintendo one), their muscle memory will be destroyed. This is what SDL (and Steam) are doing, enabled by default.

(Also, applying both solutions at the same time will make a game with both the wrong mapping and the wrong prompts. Meaning, if you play a game with the default SDL setting, you should not enable Nintendo prompts on a Nintendo controller.)

So, @Squall-Leonhart, are you going to write a motivation on why not? The motivation so far was because it was a big change, but now that they should be fair game due to SDL3, I'd want another one.

**Comment by Squall-Leonhart** [comment]
simply put, you're the only one that cares

thats not reason enough to invert behaviors from one sdl version to another.

**Comment by Lokathor** [comment]
If the prompt says "X" and I'm holding a switch pro controller I expect that the top button will do it. If the prompt says "Y", the left, and so on. I don't look at the controller, but I know by instinct which button is which on that controller. Programs should learn to respect Nintendo controller users, not the other way around. If i wanted an xbox controller I'd just get one and use that.

**Comment by SuperSamus** [comment]
> thats not reason enough to invert behaviors from one sdl version to another.

Could say the same about [SDL 2.0.12](https://github.com/libsdl-org/SDL/releases/tag/release-2.0.12), which introduced this to begin with.

> simply put, you're the only one that cares

Found someone else! https://www.reddit.com/r/linux_gaming/comments/fguome/comment/fk8o7lt/?context=3

> Programs should learn to respect Nintendo controller users, not the other way around.

Alright, but you should motive why this is better than destroying muscle memory and having a button layout different from the same game on the Nintendo console.

**Comment by CaptainCoward** [comment]
i stumbled over this trying to get the "correct" mapping for my WiiU-Pro Pad. The Launch parameter works fine. I just wonder, is there a more persistent way so that i wouldn't have to set that launch parameter for each game?

**Comment by SuperSamus** [comment]
If you want to set the environment variable for the entire user, add the following line to `~/.bashrc` (assuming you are using Bash):
```
export SDL_GAMECONTROLLER_USE_BUTTON_LABELS=0
```

**Comment by slouken** [comment]
Okay, this is implemented!
