### ISSUE TITLE
Strange headers *_c.h

### ISSUE THREAD

**Issue by dustdfg** [libsdl-org/SDL#6131]
What is the reason to use `file_name_c.h` for `file_name.c` at src dir when most other headers use the normal `file_name.h` for `file_name.c`? Example: [SDL_error_c.h](https://github.com/libsdl-org/SDL/blob/679582e702bef0ccd743f07dab860ebce8912856/src/SDL_error_c.h) It looks like someone renamed all other files and forgot some of them...

**Comment by sezero** [comment]
So that those private headers won't conflict with public ones.
