### ISSUE TITLE
Linux /dev/js* joysticks...?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6133]
This has come up from time to time, and it's my turn to get hit by it.

https://github.com/icculus/descent3-bugs/issues/9

SDL 1.2 talked to /dev/js0 (etc) ... these devices could be calibrated by an external utility and then the kernel would report input values with that calibration in mind.

SDL2 removed this, and instead talks to /dev/input/event* or hidapi, etc, but it basically always gets the raw values from the device. In modern times, this almost universally works, since hardware is better, etc, but for the random old flight stick and such, it would be nice if we could get the calibrated input values instead.

I assume this is probably not what most things should be using, so it would have to be a hint to use that interface instead of the standard one.

Failing that, perhaps we offer something like the controller mappings, that works at the joystick level, and we apply our own calibration based on that ("axis 1 goes from 128 to 32000, deadzone of 0 to 30"? I'm just thinking out loud here, that might be a terrible idea.

What's the best way forward here? (including "this isn't worth fixing for a small subset of use-cases")

**Comment by slouken** [comment]
You can set the hint SDL_HINT_LINUX_JOYSTICK_CLASSIC to enable the classic /dev/input/js* joysticks as of https://github.com/libsdl-org/SDL/commit/1c78b0800759174abe1bac01ce5b9cd788a6a372

**Comment by icculus** [comment]
Wow, I totally missed this! Nice!!

**Comment by slouken** [comment]
*grin* I knew we had solved this... :)
