### ISSUE TITLE
Unable to run files build with debugging information (-g option) with mingw on windows 11 after upgrading to version 2.24.0

### ISSUE THREAD

**Issue by rapte** [libsdl-org/SDL#6139]
I am running windows 11. I am using the TDM-GCC-64 compiler. After upgrading to the latest version 2.24.0, I am unable to run programs which are built with debugging information (-g option) while getting a "Access is denied" message. Binaries built without this option continue to run perfectly.

A very simple example

```c
#include <SDL2\SDL.h>

int main(int argc, char* argv[]) {
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Quit();
    return 0;
}
```

```
> gcc -g minimum-sdl2.c -lmingw32 -lsdl2main -lSDL2
> a.exe
Access is denied.
```

**Comment by slouken** [comment]
Are you able to use git bisect to find out where this broke?

**Comment by madebr** [comment]
I can reproduce this by downloading and installing [tdm64-gcc-10.3.0-2.exe](https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe) from [https://jmeubank.github.io/tdm-gcc/](https://jmeubank.github.io/tdm-gcc/).

Linking to the [MinGW SDL2 sdk](https://github.com/libsdl-org/SDL/releases/download/release-2.24.0/SDL2-devel-2.24.0-mingw.tar.gz) gives the following error on Windows 10:
![image](https://user-images.githubusercontent.com/4138939/187931556-08732f0a-758a-41fe-8b5a-a6ad4e244c56.png)

When I [link to the VC SDK](https://github.com/libsdl-org/SDL/releases/download/release-2.24.0/SDL2-devel-2.24.0-VC.zip), the executable runs just fine. You can link to `.lib` files by using full paths.

When I modify the code to the following, the executable builds and runs fine
```c
#define SDL_MAIN_HANDLED
#include <SDL2\SDL.h>
#include <stdio.h>
int main(int argc, char* argv[]) {
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Quit();
    printf("If you are reading this then nothing went wrong.\n");
    return 0;
}
```

So TDM is giving troubles when using SDLmain.

**Comment by slouken** [comment]
If I build with mingw using gcc 10.3.0, I get this issue. If I build with mingw using gcc 11.3.0, the executables work fine. The 2.0.22 binaries were built with gcc 11.1.0, and the 2.0.24 binaries were built with gcc 12.1.0, so it seems like it's an issue where gcc 12 binaries can't be linked using gcc 10.

Unfortunately I upgraded to gcc 12 because of a code generation issue in gcc 11 which caused a crash in SDL_ttf.

Let me think about this...

**Comment by slouken** [comment]
Actually, it's not quite that simple. The 2.24.0 libSDL2main.a works with mingw gcc version 10.2.0, so it's not strictly a gcc version issue.

**Comment by slouken** [comment]
This is the problem:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101377

The newer binutils uses -gdwarf-5 by default, which is broken in the earlier versions of binutils used by TDM and others. I can work around this by passing -gdwarf-4 in the command line options when building the release archive.
