### ISSUE TITLE
sdl2.m4 support for macOS frameworks probably broken

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#6141]
While writing #6140, I noticed that `AM_PATH_SDL2` in `sdl2.m4` has this:

```
    if test "$SDL2_CONFIG" = "no" -a "x$search_sdl_framework" = "xyes"; then      
      AC_MSG_CHECKING(for SDL2.framework)                                         
      if test "x$SDL2_FRAMEWORK" != x; then                                       
        sdl_framework=$SDL2_FRAMEWORK                                             
      else                                                                        
        for d in / ~/ /System/; do                                                
-->       if test -d "$dLibrary/Frameworks/SDL2.framework"; then                  
-->         sdl_framework="$dLibrary/Frameworks/SDL2.framework"                   
          fi                                                                      
        done                                                                      
      fi                                                                          
```

It's clear that the intention was to expand `$d` and append `Library/(etc.)` in order to search `/Library/Frameworks`, `~/Library/Frameworks` and `/System/Library/Frameworks`, but what this actually does is to expand `$dLibrary` (which almost certainly isn't set) and then look in what in practice is `/Frameworks`. It should be written as `${d}Library` if it's intended to work the way I think it is.

This bug has been there since 2016 and it seems nobody on macOS has noticed (5f2e83a9), which might indicate that nobody is actually using this code path? If that's the case then perhaps it can be deprecated or even removed?

**Comment by slouken** [comment]
Yes, frameworks aren't generally installed in /Library/Frameworks anymore, due to multi-platform / multi-target development. If you're developing using autotools on macOS, you get a shared library, not a framework, and if you're building frameworks you're using Xcode and not sdl2.m4.

I'll go ahead and fix this, but we should revisit it next time we're overhauling supported build environments.
