### ISSUE TITLE
[Maybe intended, but seems like bug] Pressing shift and "+" (US ANSI keyboard) gives me SDLK_EQUALS and not SDLK_PLUS

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#6147]
Pressing and holding shift, and then pressing "+" (US ANSI keyboard) will result in that second key down giving me SDLK_EQUALS and not SDLK_PLUS. I feel like conceptually that shouldn't happen and I should get SDLK_PLUS, and I might be wrong but did this maybe some years ago behave differently in SDL? Anyway, the doesn't-seem-right behavior happens with both `SDL_VIDEODRIVER=x11` and `SDL_VIDEODRIVER=wayland` on Fedora/Linux with SDL version 2.24.0-1.fc36, a physical keyboard, and a GNOME 3 Wayland session (so with XWayland for the X11 case), and I always unexpectedly get SDLK_EQUALS.

## Steps to reproduce:

**Step 1: copy this into `sdl2plusequalsbug.c`:**

```

#include <assert.h>
#include <SDL2/SDL.h>
#include <stdio.h>


int main(int argc, const char **argv) {
    int r = SDL_Init(SDL_INIT_EVERYTHING);
    assert(r == 0);

    SDL_Window *window = SDL_CreateWindow("sdl dpi bug", 0, 0, 200, 200,
        SDL_WINDOW_RESIZABLE|SDL_WINDOW_OPENGL);
    assert(window != NULL);
    SDL_Renderer *renderer = SDL_CreateRenderer(
        window, -1, SDL_RENDERER_PRESENTVSYNC|
        SDL_RENDERER_ACCELERATED);
    assert(renderer != NULL);

    int notquit = 1;
    while (notquit) {
        SDL_Event e = {0};
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                notquit = 0;
                break;
            } else if (e.type == SDL_WINDOWEVENT) {
                if (e.window.event == SDL_WINDOWEVENT_CLOSE) {
                    notquit = 0;
                    break;
                }
            } else if (e.type == SDL_KEYDOWN) {
                if (e.key.keysym.sym == SDLK_EQUALS)
                    printf("'=' pressed\n");
                if (e.key.keysym.sym == SDLK_PLUS)
                    printf("'+' pressed\n");
            }
        }
        SDL_RenderPresent(renderer);
    }
    return 0;
}
```

**Step 2: compile:**

```
$ gcc -g -o ./sdl2plusequalsbug sdl2plusequalsbug.c -lSDL2
```

**Step 3: run it and then press shift and hold it down, and while it is held down press `=` on an ANSI keyboard (which should give you `+`).**

Expected output of the test program: `'+' pressed`, actual output: `'=' pressed`.

## Use case

My bad if I'm merely just misunderstanding how the key syms are meant to be used. But for keyboards that combine multiple special characters on unusual keys, how else would a game map keyboard shortcuts to them and have them work for everyone? Using start text input might trigger international input methods and has no exact key down and up and all that, so I'm not sure that's a good replacement.

**Comment by flibitijibibo** [comment]
Yeah, SDL_keysym is one of those weird in-between things - it's not a scancode, but it's also not proper text input: It has the layout awareness that text input has, but ignores mods like a scancode would. So in this case, it only cares about what they symbol would be regardless of whether shift is held, so on US QWERTY the 0 key at the top row is always `SDLK_0`, rather than switching between `SDLK_0` and `SDLK_RPAREN` (or whatever it would be, if such a sym exists... keysyms give me a headache).
