### ISSUE TITLE
Target to build xcframework on iOS

### ISSUE THREAD

**Issue by tjpadula** [libsdl-org/SDL#6156]
I’ve been working on an iOS app using SDL. In so doing, I've run in to the common problem, with the release of Apple Silicon Macs, of having to constantly switch framework builds when switching between the simulator and a real device. Apple's solution for this is to use an xcframework, which was created for this purpose a few years back on Xcode 11.

The point of such a framework is to allow a single dynamically-linked lib for a client app that works on all combinations of device/simulator vs. Intel /Apple Silicon. (A conventional framework cannot do this, neither can statically linked libraries.)

I have this working to a first approximation on Xcode 11 and later. At this point, it builds SDL2.xcframework in a Products directory adjacent to SDL.xcodeproj. No other targets of the Xcode project have been changed. I have it on a branch and can of create a pull request if the build team would like to give it a go.

**Comment by slouken** [comment]
Sure, that would be interesting to look at. Thanks!

**Comment by tyrondis** [comment]
@tjpadula are you willing to share your branch? I am running into the same issues myself right now :)

**Comment by tyrondis** [comment]
Never mind, found it in your repo :) I checked it out and it works like a charm! Only thing I had to do was to manually set the header search paths to the `Headers` folder inside the framework.

Is that something we can fix on the xcframework level? It seems that the header files are currently found by adding the `SDL2/` folder to the include path, e.g. `SDL2/SDL.h`. However this doesn't work as `SDL.h` itself tries to include its dependencies directly, without the subfolder.

**Comment by tyrondis** [comment]
Never mind, found it and can confirm it works!

**Comment by slime73** [comment]
`xcodebuild -create-xcframework` can create an xcframework from a collection of static libraries for each platform, if anyone's interested in that sort of workaround for now. I've used it successfully in my projects (by building a static library for each platform and saving it, and using xcodebuild to combine them into an xcframework structure).

**Comment by tjpadula** [comment]
Ok, I have create a pull request after making sure there is relevant guidance in README-ios.md. This build has been tested on Xcode 11, 12, and 13, on both Intel and Apple Silicon (AS only for Xcode 13 of course).

**Comment by tyrondis** [comment]
@tjpadula can we do the same for SDL_image? Tried to google how to set it up in Xcode but wasn't very successful. Any pointers?

**Comment by tjpadula** [comment]
I haven't tried it. I could take a look in the next day or two. I don't see why it wouldn't work.

**Comment by slouken** [comment]
The SDL libraries are now set up to build xcframeworks.
