### ISSUE TITLE
Invalid linker flag for pkg-config using the static build using MSVC

### ISSUE THREAD

**Issue by quyykk** [libsdl-org/SDL#6158]
When building SDL as a static library using MSVC, the static library name is `SDL2-static.lib`. However, the generated `sdl2.pc` file from CMake uses `-lSDL2` instead of `-lSDL2-static`.  This is because the variable SDL_STATIC_LIBS is simply set to SDL_LIBS (CMakeLists.txt:2859) and SDL_LIBS is hardcoded to `-lSDL2` (CMakeLists.txt:324).

This makes any application using pkg-config to fail to build (using MSVC + static SDL) because `-lSDL2` can't be found.

The fix would probably involve clearing SDL_LIBS and setting the correct library to SDL_STATIC_LIBS (or maybe something else completely), but I'm very unsure about the potential implications of this so that's why I haven't made a PR.

For reference, here's the library line of the `sdl2.pc` file for a static build using MSVC:

```
Libs: -L"${libdir}"   -lSDL2   -lSDL2  -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -ladvapi32 -lsetupapi -lshell32 -ldinput8
```

**Comment by slouken** [comment]
In what context do you use sdl2.pc for a Visual Studio build?

**Comment by madebr** [comment]
Can `.pc` files express static and shared libraries having different names?
I hacked the CMake script to create a `libSDL2-static.a` static library and created the following `sdl2.pc`:
```
prefix=/home/maarten/programming/SDL/cmake-build-debug-mingw64/prefix
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: sdl2
Description: Simple DirectMedia Layer is a cross-platform multimedia library designed to provide low level access to audio, keyboard, mouse, joystick, 3D hardware via OpenGL, and 2D video framebuffer.
Version: 2.25.0
Requires:
Conflicts:
Libs: -L${libdir}   -lmingw32 -mwindows -lSDL2main -lSDL2 
Libs.private:  -lmingw32 -mwindows -lSDL2main -lSDL2-static  -lm -liconv -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -ladvapi32 -lsetupapi -lshell32 -ldinput8
Cflags: -I${includedir} -I${includedir}/SDL2  -Dmain=SDL_main
```

But:
```sh
$ PKG_CONFIG_PATH=$PWD/prefix/lib/pkgconfig pkg-config --libs --static sdl2 
-L/home/maarten/programming/SDL/cmake-build-debug-mingw64/prefix/lib -lmingw32 -mwindows -lSDL2main -lSDL2 -lmingw32 -mwindows -lSDL2main -lSDL2-static -lm -liconv -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -ladvapi32 -lsetupapi -lshell32 -ldinput8 
```

The link flags containg both `-lSDL2` and `-lSDL2-static`, which is not correct.

When building SDL2 with either `SDL_STATIC` or `SDL_SHARED` enabled, but not both, then the `sdl2.pc` is valid again.

**Comment by quyykk** [comment]
> In what context do you use sdl2.pc for a Visual Studio build?

With vcpkg. Some libraries use the pkg-config file with CMake to find SDL (yes even on Windows).

**Comment by madebr** [comment]
Currently, we don't generate/install `sdl2.pc` for MSVC.

https://github.com/libsdl-org/SDL/blob/cbb1cf0c930602c4e0001fc1768f070334141fd9/CMakeLists.txt#L2848

What projects require `sdl2.pc` to be present when building MSVC?

**Comment by quyykk** [comment]
ffmpeg and magnum.

> Currently, we don't generate/install sdl2.pc for MSVC.

That's probably something vcpkg changes then. In any case, if this is more of an issue with vcpkg (and not from upstream, i.e. here), then feel free to close this.

**Comment by madebr** [comment]
Looks like vcpkg [carries a patch enabling generation of `.pc`](https://github.com/microsoft/vcpkg/blob/779ce74ef67d3e12d904da1b15f9ed5626d5f677/ports/sdl2/0001-sdl2-Enable-creation-of-pkg-cfg-file-on-windows.patch) .
I don't understand why they added the `if(NOT WINDOWS_STORE)` though.
