### ISSUE TITLE
Raspberry Pi 4 - No Keyboard Inputs w/ Latest Pipewire + Wireplumber Releases

### ISSUE THREAD

**Issue by bluestang2006** [libsdl-org/SDL#6160]
I was referred here because of https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/341...

I'm not sure where the bug is present and what exactly is causing it but as the title reads...I'm getting no keyboard inputs during app execution.

What I do know is that this issue happens once wireplumber is installed and pipewire is made the default audio server. Uninstalling pipewire-pulse and wireplumber, and making pulseaudio the default again fixes this issue...

This is easily reproducible on the Fedora 37 nightly image for [aarch64](https://kojipkgs.fedoraproject.org/compose/branched/Fedora-37-20220830.n.0/compose/Workstation/aarch64/images/Fedora-Workstation-37-20220830.n.0.aarch64.raw.xz)

It's a bit more involved to get pipewire and wireplumber installed on the current Raspberry Pi OS...

**Comment by icculus** [comment]
That's extremely unexpected. I'll try to reproduce it here.

**Comment by bluestang2006** [comment]
> That's extremely unexpected. I'll try to reproduce it here.

I would recommend using Quake3e or RetroArch as the apps to reproduce.

As I said, the easiest way might be to use the Fedora 37 nightly image for aarch64 since it includes RPi4 support and all the latest libraries are present or easily installed from rpm. I encountered this issue not knowing what was the cause at first because I was just curious how Fedora 37 would fair on the RPi4 since once its officially released it will support it.

On Raspberry Pi OS, I had to compile libfixes+libfixes-dev 1.6 in order to compile the latest pipewire and then compile latest wireplumber.

**Comment by pinkflames** [comment]
I'll just note that libXfixes is an optional dependency of pipewire-module-x11-bell and you probably do not need or maybe even want either of them.

**Comment by bluestang2006** [comment]
Update - setting `SDL_AUDIODRIVER=dummy` fixes the issue with the keyboard input, however, the obvious issue is that there is no sound.

**Comment by bluestang2006** [comment]
Update - looks like the cause of the issue is my USB external Razer Sound Card. I have KVM monitor, the sound card is plugged into the RP keyboard to the monitor that has an internal KVM.

I'm closing this as this is not an SDL2 bug.
