### ISSUE TITLE
Android: SDLActivity (Java) key & edit events under API 33 (TIRAMISU)

### ISSUE THREAD

**Issue by 312937** [libsdl-org/SDL#6170]
I'd like to suggest at least one change to the class `DummyEdit`:

1. @lines 1863++

**CURRENT**

    public InputConnection onCreateInputConnection(EditorInfo outAttrs) {
        ic = new SDLInputConnection(this, true);
        
        outAttrs.inputType = InputType.TYPE_CLASS_TEXT;
        outAttrs.imeOptions = EditorInfo.IME_FLAG_NO_EXTRACT_UI
                | EditorInfo.IME_FLAG_NO_FULLSCREEN /* API 11 */;

        return ic;
    }

**MODIFIED**

    public InputConnection onCreateInputConnection(EditorInfo outAttrs) {
        ic = new SDLInputConnection(this, true);
        
        outAttrs.inputType = InputType.TYPE_CLASS_TEXT;
        outAttrs.imeOptions = EditorInfo.IME_FLAG_NO_EXTRACT_UI
                | EditorInfo.IME_FLAG_NO_FULLSCREEN /* API 11 */;
        
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            outAttrs.imeOptions |= EditorInfo.TYPE_TEXT_FLAG_MULTI_LINE;
        }

        return ic;
    }

2. I might suggest more modifications but they seem quite specific (personal/individual choice):

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            outAttrs.imeOptions |= EditorInfo.IME_FLAG_NO_PERSONALIZED_LEARNING;
        }

... and respectively (@line 1867):

        outAttrs.inputType = (InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS)
                & ~(InputType.TYPE_TEXT_FLAG_AUTO_CORRECT | InputType.TYPE_TEXT_FLAG_AUTO_COMPLETE);

3. Further, the declaration @line 209 might be improved:

-    protected static **DummyEdit** mTextEdit;

_DummyEdit_ instead of _View_.

All the proposed modifications have already been verified.

Ad 1)
The (TIRAMISU) trouble arises in `SDLInputConnection.commitText(...)` which provides (let's say) _'separated text chunks'_ (discarding the context on each EOL).

Many thanks for you great work!

**Comment by slouken** [comment]
I think this takes care of the big issues, yes?

**Comment by slouken** [comment]
So we are setting the inputType to InputType.TYPE_TEXT_FLAG_MULTI_LINE, and I don't see any documentation for EditorInfo.TYPE_TEXT_FLAG_MULTI_LINE. Can you check the current main code and see if that works, and if it doesn't, can you please provide more information on this option and why it's necessary?

**Comment by 312937** [comment]
The current main did not work (Tiramisu). I treat 2.24.0 as _current_ for Android. Up to my knowledge, there were no changes between 2.24.0 and 2.24.1 in the _android-project_ subfolder.
The trouble appeared while testing under Tiramisu (API 33 in Emulator).
I patched all my apps (in the store) with the described fix (after some debugging). Thus, I'm using the fix _in the field_ now.
I'll provide you the link to one app with a promotion code via another channel (where I reported _SDL2 2.0.16 bug while drawing rectangles_ about a year ago). I'd like to avoid _promoting_ my apps via this (your) platform.

**Comment by slouken** [comment]
You don't need to provide a link to your app, I was hoping for a link to the documentation for the option that you're setting.

So, just to be clear, you tested SDL 2.25.0 with change https://github.com/libsdl-org/SDL/commit/6acc7a5622a6962538907dc144ebfc4fedc1124d, and it did not work in the Tiramisu emulator, is that correct?
Here's a zip file you can download if you haven't already tested this commit:
https://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by 312937** [comment]
I'm sorry. I have (completely) misunderstood you (with _**current**_). I'll verify immediately and let you know.

**Comment by 312937** [comment]
It seems "_**to work for me**_" (if I didn't make any mistake during the build).

Roughly verified key input (main '2.25.0' SHA 4227a0b4f330027ab96e35b0832a396b56d45566) under emulator:

- API 33 
- API 28

PS.
1. I had a typo in my description `imeOptions` instead of `inputType`.
2. Sorry for the misunderstanding.

**Comment by slouken** [comment]
Great, thanks!
