### ISSUE TITLE
Automate version bumping...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6171]
> Yes please. And while you're at it, do you want to add it for SDL and SDL_* libraries? @smcv did a great job documenting all the places that need to be changed in release_checklist.md

_Originally posted by @slouken in https://github.com/libsdl-org/sdl12-compat/issues/205#issuecomment-1235974041_

**Comment by ericoporto** [comment]
Hey, does this script has to be perl based or can it be python based? We have [one here](https://github.com/adventuregamestudio/ags/blob/master/Script/push_version.py) that would possibly be very simple to adapt for SDL2 source, but it's written in python.

**Comment by icculus** [comment]
It doesn't have to be Perl, but the one I smashed together for sdl12-compat is pretty compact:

https://github.com/libsdl-org/sdl12-compat/blob/main/update_version.sh

**Comment by icculus** [comment]
Hey @smcv and @slouken, any objection to me moving test/versioning.sh to build-scripts/test-versioning.sh?  It's probably the more correct place for it.

**Comment by slouken** [comment]
No, please do. :)
