### ISSUE TITLE
Problems with linking headers in macOS framework

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#6175]
I have a Problem with headers when using the framework version of SDL2 v2.24.0 on macOS v12.5.1. The framework is stored in /Library/Frameworks. The problem did not exist in earlier versions of SDL2. It seems that the header path in SDL.h changed from 
`#include "SDL_x.h" `
to
`#include <SDL2/SDL_x.h>`

This leads to my build system not finding those SDL_x.h headers.

**Comment by madebr** [comment]
What build system are you using?

If it's CMake you're using, the framework provide CMake configuration scripts that makes available SDL2 targets to link to.

**Comment by andreasgrabher** [comment]
Yes, I am using CMake to generate an Xcode project. It seems this patch fixes my problems: https://sourceforge.net/p/previous/code/1161/

I did not test if it breaks building with older versions of SDL2 or if it also works on other platforms.

**Comment by madebr** [comment]
`SDL2::SDL2` is a target that is available everywhere, even on older versions of SDL2.

About the use of `SDL2_LIBRARY` in there, we never assigned something to that value.
However, `SDL2_LIBRARIES` is avilable everywhere.
But we encourage people to stop using the `SDL2_*` cmake variables and start using CMake targets.

**Comment by andreasgrabher** [comment]
Thank you for the feedback. I think this issue can be closed.
