### ISSUE TITLE
Using CMake give me error no such file or directory: 'CMakeFiles/SDL2.dir/src/main/windows/version.rc.res'

### ISSUE THREAD

**Issue by jjiangweilan** [libsdl-org/SDL#6176]
OS: Windows10
build system: CMake with Unix Makefiles
error message:
```
Building C object CMakeFiles/SDL2-static.dir/src/joystick/windows/SDL_rawinputjoystick.c.obj
[ 98%] Building C object CMakeFiles/SDL2-static.dir/src/joystick/windows/SDL_dinputjoystick.c.obj
[ 99%] Building C object CMakeFiles/SDL2-static.dir/src/joystick/windows/SDL_windows_gaming_input.c.obj
[ 99%] Building C object CMakeFiles/SDL2-static.dir/src/joystick/windows/SDL_windowsjoystick.c.obj
[ 99%] Building C object CMakeFiles/SDL2-static.dir/src/joystick/windows/SDL_xinputjoystick.c.obj
[ 99%] Building C object CMakeFiles/SDL2-static.dir/src/haptic/windows/SDL_windowshaptic.c.obj
[ 99%] Building C object CMakeFiles/SDL2-static.dir/src/haptic/windows/SDL_dinputhaptic.c.obj
[100%] Building C object CMakeFiles/SDL2-static.dir/src/haptic/windows/SDL_xinputhaptic.c.obj
[100%] Linking C shared library SDL2d.dll
clang: error: no such file or directory: 'CMakeFiles/SDL2.dir/src/main/windows/version.rc.res'
gmake[5]: *** [CMakeFiles/SDL2.dir/build.make:3200: SDL2d.dll] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:195: CMakeFiles/SDL2.dir/all] Error 2
gmake[4]: *** Waiting for unfinished jobs....
[100%] Linking C static library SDL2d.lib
[100%] Built target SDL2-static
gmake[3]: *** [Makefile:136: all] Error 2
gmake.exe[2]: *** [CMakeFiles/SDL2.dir/build.make:89: ThirdParty/SDL2/src/SDL2-stamp/SDL2-build] Error 2
gmake.exe[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/SDL2.dir/all] Error 2
gmake.exe: *** [Makefile:91: all] Error 2
```
I'm using a superbuild system with ExternalProject_Add. The minimum CMakeLists.txt is at below.
```
cmake_minimum_required(VERSION 3.18)

set(CMAKE_CXX_COMPILER "clang++")
set(CMAKE_C_COMPILER "clang")

project(SDL2SuperBuildTest)

  include(ExternalProject)

  ExternalProject_Add(SDL2
      PREFIX "ThirdParty/SDL2"
      GIT_REPOSITORY "https://github.com/libsdl-org/SDL.git"
      GIT_TAG "release-2.24.0"
      SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/ThirdParty/SDL2"
      INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}"
      CMAKE_ARGS
          "-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
          "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
          "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}"
  )
```
simplely put this cmake file in any folder and executing it can reproduce the issue
1. `mkdir build`
2. `cd build`
3. `cmake ..`
4. `cmake --build .`
I have used the same setup with ninja and it works.

**Comment by madebr** [comment]
Usually, the build log should contain a line doing:
```
[271/469] Building RC object CMakeFiles/SDL2.dir/src/main/windows/version.rc.res
```
With MinGW on Linux, doing a verbose builds shows the actual command being executed:
```
/usr/bin/x86_64-w64-mingw32-windres -O coff -DDLL_EXPORT -DUSING_GENERATED_CONFIG_H -I /home/maarten/programming/SDL/cmake-build-debug-mingw64/include -I /home/maarten/programming/SDL/cmake-build-debug-mingw64/include-config-  /
home/maarten/programming/SDL/src/main/windows/version.rc CMakeFiles/SDL2.dir/src/main/windows/version.rc.res
```

Can you please clean your build, do a verbose build and see what command is executed to generate `version.rc.res`?
```
cmake --build . --verbose
```

You can define the `RC` compiler through setting the [`CMAKE_RC_COMPILER` CMake variable](https://cmake.org/cmake/help/v3.10/envvar/RC.html).

**Comment by jjiangweilan** [comment]
> Usually, the build log should contain a line doing:
> 
> ```
> [271/469] Building RC object CMakeFiles/SDL2.dir/src/main/windows/version.rc.res
> ```
> 
> With MinGW on Linux, doing a verbose builds shows the actual command being executed:
> 
> ```
> /usr/bin/x86_64-w64-mingw32-windres -O coff -DDLL_EXPORT -DUSING_GENERATED_CONFIG_H -I /home/maarten/programming/SDL/cmake-build-debug-mingw64/include -I /home/maarten/programming/SDL/cmake-build-debug-mingw64/include-config-  /
> home/maarten/programming/SDL/src/main/windows/version.rc CMakeFiles/SDL2.dir/src/main/windows/version.rc.res
> ```
> 
> Can you please clean your build, do a verbose build and see what command is executed to generate `version.rc.res`?
> 
> ```
> cmake --build . --verbose
> ```
> 
> You can define the `RC` compiler through setting the [`CMAKE_RC_COMPILER` CMake variable](https://cmake.org/cmake/help/v3.10/envvar/RC.html).


so, today I changed my dev environment on Windows to clang with gnu (it was clang with msvc before). Then I went to reproduce this issue. Magically the issue was gone. We can close this if you think it's not necessary to track down the issue further.

**Comment by madebr** [comment]
I'm going to close it then.

I think you need to use `MinGW Makefiles` instead.
