### ISSUE TITLE
Add buildbot/github action for Android from Gradle+CMake

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#6178]
Currently only the Android from Android.mk is checked.

Possibly adding a binary variable in the project is enough to be able to switch between ndk and cmake in the CI.

**Comment by madebr** [comment]
We test building Android using `Android.mk` and `CMake`:
https://github.com/libsdl-org/SDL/blob/1b4e08b89ec7be7a63d47f8fef30aeab7e7d21ec/.github/workflows/android.yml#L13-L15

Can you describe what we're missing exactly? I don't fully understand your question.

**Comment by ericoporto** [comment]
So you do use CMake, but it's ran manually instead of using gradle. I just wonder if there's a difference, somehow, I absolutely could not build in Android Studio before https://github.com/libsdl-org/SDL/commit/a204ef50bbf20b77083c0a14124e673efc3a53c6, but I have no idea why. I am on Chipmunk 2021.2.1 patch 2.

**Comment by ericoporto** [comment]
I will close this since apparently CMake is used for building, but there is something different I can't figure out going on here.

**Comment by ericoporto** [comment]
I think before going into Maven is a good idea to really get the Gradle CI up and running for people who will keep building SDL from source in Android Studio.

**Comment by slouken** [comment]
@madebr, can you look at what's involved in building using a cmake + gradle workflow?

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/commit/e10666397e34efd421a75f1cfca05c09e59e4aff added a gradle job

I'll leave this open since creating an aar archive is broken
See https://github.com/libsdl-org/SDL/pull/5717
