### ISSUE TITLE
Unresolved symbols when building on MacOS for X11 only

### ISSUE THREAD

**Issue by cesss** [libsdl-org/SDL#6191]
I was trying to build for X11-only on Mac (configured as `--with-x --disable-render-metal --disable-video-metal --disable-video-cocoa`), and when linking the demos in the "test" subdirectory, I'm getting unresolved references to `Cocoa_IsWindowInFullscreenSpace()` and `Cocoa_SetWindowFullscreenSpace()`.

The reason is that **SDL_video.c** correctly avoids calling these functions when the driver being used is not Cocoa but, however, that test is done at runtime only: The compile-time requirement for linking to `Cocoa_IsWindowInFullscreenSpace()` and `Cocoa_SetWindowFullscreenSpace()` is just the definition of __MACOSX__ and it doesn't check if the Cocoa driver is being built or not.

**Comment by sezero** [comment]
Does the following patch fix it? (It doesn't account for the possibility
of both x11 and cocoa backends being compiled in, though...)

```diff
diff --git a/src/video/SDL_video.c b/src/video/SDL_video.c
index 881b06b..b4f3c1e 100644
--- a/src/video/SDL_video.c
+++ b/src/video/SDL_video.c
@@ -160,7 +160,7 @@ static VideoBootStrap *bootstrap[] = {
 
 #define FULLSCREEN_MASK (SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_FULLSCREEN)
 
-#ifdef __MACOSX__
+#if defined(__MACOSX__) && defined(SDL_VIDEO_DRIVER_COCOA)
 /* Support for Mac OS X fullscreen spaces */
 extern SDL_bool Cocoa_IsWindowInFullscreenSpace(SDL_Window * window);
 extern SDL_bool Cocoa_SetWindowFullscreenSpace(SDL_Window * window, SDL_bool state);
@@ -1335,7 +1335,7 @@ SDL_UpdateFullscreenMode(SDL_Window * window, SDL_bool fullscreen)
         return 0;
     }
 
-#ifdef __MACOSX__
+#if defined(__MACOSX__) && defined(SDL_VIDEO_DRIVER_COCOA)
     /* if the window is going away and no resolution change is necessary,
        do nothing, or else we may trigger an ugly double-transition
      */
@@ -3170,7 +3170,7 @@ ShouldMinimizeOnFocusLoss(SDL_Window * window)
         return SDL_FALSE;
     }
 
-#ifdef __MACOSX__
+#if defined(__MACOSX__) && defined(SDL_VIDEO_DRIVER_COCOA)
     if (SDL_strcmp(_this->name, "cocoa") == 0) {  /* don't do this for X11, etc */
         if (Cocoa_IsWindowInFullscreenSpace(window)) {
             return SDL_FALSE;
```

**Comment by cesss** [comment]
I'm testing, I'll tell in a few minutes. Anyway, I think that it does consider the possibility of both the x11 and cocoa drivers being built, because that's the situation for which I guess the `if (SDL_strcmp(_this->name, "cocoa") == 0) {  /* don't do this for X11, etc */` line was coded.

**Comment by cesss** [comment]
I confirm it works. I'm going to rebuild everything from scratch, and I'll try a Cocoa build as well. If I don't post any more problems, consider everything is perfect.

Thanks a lot, @sezero !!

**Comment by sezero** [comment]
>  I think that it does consider the possibility of both the x11 and cocoa drivers being built, because that's the situation for which I guess the `if (SDL_strcmp(_this->name, "cocoa") == 0) { /* don't do this for X11, etc */` line was coded.

Ah yes, you are right - it was staring right into my eyes and I missed them :(

Will push the patch shortly.
