### ISSUE TITLE
GL_EXT_direct_state_access missing definitions and prototypes in SDL_opengl_glext.h.

### ISSUE THREAD

**Issue by amskefx** [libsdl-org/SDL#6193]
Some functions from OpenGL 4.5 ARB_direct_state_access do not have definitions or prototypes in SDL_opengl_glext.h, such as glCreateBuffers, and glCreateFramebuffers.

**Comment by slime73** [comment]
`GL_EXT_direct_state_access` has a different set of APIs (and is much older) than `GL_ARB_direct_state_access`. It looks like the header file is just too old to have the ARB version's definitions?

**Comment by amskefx** [comment]
I think that is the case. The header file provided by SDL was last updated in May of 2014. `GL_ARB_direct_state_access` was in 4.5, in August of 2014.

**Comment by slouken** [comment]
Yes, we should update the OpenGL and Vulkan headers this milestone.
