### ISSUE TITLE
Broken clip behaviour on a render target (metal)

### ISSUE THREAD

**Issue by paladin-t** [libsdl-org/SDL#6199]
Platform: iOS

I use render target to pre-render map layers, then render it as a whole.

With and before SDL2-2.0.20, it was ok:

![1762724238](https://user-images.githubusercontent.com/2062224/188871443-f30e6505-f322-476a-9381-0425a27a88f1.jpg)

With and after SDL2-2.0.22 until the latest revision, it was broken:

![531670861](https://user-images.githubusercontent.com/2062224/188871479-f4f04bc9-590d-4a02-9402-e3e55aad78ec.jpg)

The intersection logic was incorrect when rendering onto a render target. And it was counted as the screen's size, rather than the render target's. If revert this function to its previous version, everything gets back normal.

I think this update (since SDL2-2.0.22) introduced a new bug while solved some old one.

https://github.com/libsdl-org/SDL/blob/d4e0d27c1c21e364d21be3af681f02b05f362345/src/render/metal/SDL_render_metal.m#L1232

```c++
static SDL_bool
SetDrawState(SDL_Renderer *renderer, const SDL_RenderCommand *cmd, const SDL_MetalFragmentFunction shader,
             const size_t constants_offset, id<MTLBuffer> mtlbufvertex, METAL_DrawStateCache *statecache)
{
    ...
    if (statecache->cliprect_dirty) {
        SDL_Rect output;
        SDL_Rect clip;
        if (statecache->cliprect_enabled) {
            clip = statecache->cliprect;
            clip.x += statecache->viewport.x;
            clip.y += statecache->viewport.y;
        } else {
            clip = statecache->viewport;
        }

        /* Set Scissor Rect Validation: w/h must be <= render pass */
        SDL_zero(output);
        METAL_GetOutputSize(renderer, &output.w, &output.h);

        if (SDL_IntersectRect(&output, &clip, &clip)) {
            MTLScissorRect mtlrect;
            mtlrect.x = clip.x;
            mtlrect.y = clip.y;
            mtlrect.width = clip.w;
            mtlrect.height = clip.h;
            [data.mtlcmdencoder setScissorRect:mtlrect];
        }

        statecache->cliprect_dirty = SDL_FALSE;
    }

    ...
}
```

**Comment by slime73** [comment]
Yeah, that logic doesn't look right - it should be using the active render target's width/height rather than the backbuffer's.

**Comment by slouken** [comment]
@1bsyl, what were you fixing in https://github.com/libsdl-org/SDL/commit/3bebdaccb7bff8c40438856081d404a7ce3def30?

**Comment by 1bsyl** [comment]
Some issue with rendering, see:
https://discourse.libsdl.org/t/rendergeometryraw-producing-different-results-in-metal-vs-opengl/34953/12

**Comment by 1bsyl** [comment]
is this commit the culprit ?
I have a doubt: IOS use metal or gles2 or both ?

**Comment by slime73** [comment]
iOS uses metal by default when it's supported, and falls back to GLES2 otherwise, I think.

Yeah that commit has the bug – it should be querying the dimensions of the active render pass' texture (whether that's a render target texture or the backbuffer) instead of just the backbuffer's dimensions. Maybe the right dimensions are already stored in a handy variable somewhere? (I haven't looked myself, just guessing).

**Comment by 1bsyl** [comment]
`METAL_GetOutputSize(renderer, &output.w, &output.h);`

should be something: 
```
if (renderer->target) {
       output.w = renderer->target.w;
       output.h = renderer->target.h;
}else{
        METAL_GetOutputSize(renderer, &output.w, &output.h);
}
```
?

**Comment by slime73** [comment]
I think that'd break a lot of existing user code – IMO it's just not the right API to call in that block of code.

**Comment by 1bsyl** [comment]
I mean in place of line 1270. (not changing the implementation of METAL_GetOutputSize.
can you try this patch @paladin-t ? 

Also, could you try switching from metal to gles2 to look how it goes ?
(add` SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles2");` before creating the renderer)

**Comment by paladin-t** [comment]
@1bsyl

> can you try this patch @paladin-t ?

Applying the patch solved the issue.

> Also, could you try switching from metal to gles2 to look how it goes ?

Switching to gles2 works ok.

**Comment by 1bsyl** [comment]
thanks @paladin-t this is fixed!
