### ISSUE TITLE
Option SDL_HIDAPI_LIBUSB always shown as OFF

### ISSUE THREAD

**Issue by JyKin** [libsdl-org/SDL#6207]
On SDL 2.24.0, when asking for this option, we get this output :
```
-- SDL_HIDAPI_LIBUSB (Wanted: ON): OFF
```
I'm sure the option was correctly used because I could use my gamecube controller properly (and couldn't without it).
From my understanding, the cmake files should set `HAVE_HIDAPI_LIBUSB` in case the option is really used for the reporting to work properly.

**Comment by sezero** [comment]
The following patch fixes it for me. @madebr?
```diff
diff --git a/cmake/sdlchecks.cmake b/cmake/sdlchecks.cmake
index 80f31c7..0fe1779 100644
--- a/cmake/sdlchecks.cmake
+++ b/cmake/sdlchecks.cmake
@@ -1198,10 +1198,12 @@ macro(CheckHIDAPI)
           endif()
         endif()
       endif()
       if(HIDAPI_ONLY_LIBUSB AND NOT HAVE_LIBUSB)
         set(HAVE_HIDAPI FALSE)
+      else()
+        set(HAVE_HIDAPI_LIBUSB TRUE)
       endif()
     endif()
 
     if(HAVE_HIDAPI)
       if(ANDROID)
```

**Comment by madebr** [comment]
I would do:
```patch
--- a/cmake/sdlchecks.cmake
+++ b/cmake/sdlchecks.cmake
@@ -1201,6 +1201,9 @@ macro(CheckHIDAPI)
       if(HIDAPI_ONLY_LIBUSB AND NOT HAVE_LIBUSB)
         set(HAVE_HIDAPI FALSE)
       endif()
+      if(NOT HAVE_LIBUSB)
+        set(HAVE_HIDAPI_LIBUSB FALSE)
+      endif()
     endif()
 
     if(HAVE_HIDAPI)
```
because `HIDAPI_ONLY_LIBUSB` is a variable only defined for certain platforms.

**Comment by sezero** [comment]
You are right (just push it.)

AFAICS, there is also a problem that if HAVE_HIDAPI is set to false
there, SDL_HIDAPI_DISABLED and SDL_HIDAPI aren't set to 0 or FALSE,
OFF or whatever in cmake-speak.

**Comment by madebr** [comment]
> You are right (just push it.)

WIll do.

> AFAICS, there is also a problem that if HAVE_HIDAPI is set to false there, SDL_HIDAPI_DISABLED and SDL_HIDAPI aren't set to 0 or FALSE, OFF or whatever in cmake-speak.

In general, the cmake scripts use the following convention: `SDL_*` options are the "input" and are configurable by the user.
The `HAVE_*` variables are variables converted into macro's.

So `SDL_HIDAPI` should be left alone: it is printed in the summary.
`SDL_HIDAPI_DISABLED` is an unfortunate collision and should indeed be set when not having hidapi.

**Comment by sezero** [comment]
I think this can be closed now: Fixed by 19b13aab98ef02c93ed356af639d1e4ed0254906 and its follow-up c3495ec6eaaaf9f0d3250a9d39356154b869251c.

**Comment by JyKin** [comment]
Sorry but the commits do not fix it. The commits never set HAVE_HIDAPI_LIBUSB to TRUE when wanted and available.

**Comment by madebr** [comment]
You're right. See 6dfd7a17e

**Comment by JyKin** [comment]
Seems to work properly know, thanks.
