### ISSUE TITLE
sdl error ioquake3 game

### ISSUE THREAD

**Issue by gregorypiro** [libsdl-org/SDL#6210]
Hi everyone. I have this problem. Could anybody help me, please?:

./baseq3/pak0.pk3 (3539 files)
    
----------------------
4115 files in pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
execing autoexec.cfg
Hunk_Clear: reset the hunk ok
----- Client Initialization -----
----- Initializing Renderer ----
Trying to load "renderer_opengl_x86_64.so" from "."...
Loading "renderer_opengl_x86_64.so" failed
failed:
"Failed loading ./renderer_opengl_x86_64.so: ./renderer_opengl_x86_64.so: cannot open shared object file: No such file or directory"
Trying to load "renderer_opengl2_x86_64.so" from "."...
-------------------------------
QKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
----- Client Shutdown (Client fatal crashed: GLimp_Init() - could not load OpenGL subsystem) -----
RE_Shutdown( 1 )
Hunk_Clear: reset the hunk ok
-----------------------
GLimp_Init() - could not load OpenGL subsystem
[gpiro@localhost release-linux-x86_64]$

**Comment by slouken** [comment]
Please contact the ioquake authors for help, I don't think this is an SDL issue.
