### ISSUE TITLE
Resize event missing with Wayland?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6219]
- Get a Wayland desktop (Ubuntu 22.04, Gnome/wayland here, ymmv)
- Run `SDL_VIDEODRIVER=wayland ./testsprite2 --fullscreen-desktop`
- Hit alt-enter to make it windowed.
- Watch it shrink to a windowed size correctly.
- Hit alt-enter again to make it fullscreen again.
- Watch the window grow to the desktop size, and clear to the correct background, but the green lines do not resize to fill the window.

Starting in windowed mode does not have this problem; you can alt-enter back and forth just fine. Are we dropping a resize event somewhere in this specific case?

This was without libdecor available, and in a vmware install, if that's meaningful at all.

![image](https://user-images.githubusercontent.com/673562/189770839-6ec6307b-3831-403e-b578-8c8309a9c925.png)

**Comment by Kontrabant** [comment]
Ah, I found the issue.  For some reason, when creating a fullscreen window, then leaving and re-entering fullscreen, GNOME sends a very strange sequence of configure events (it tries to resize the window to 1x1 before making it fullscreen).  Things end up caught in some dedup logic when the correct values eventually come through, and in this particular case, a resize isn't sent.  

Should be a simple fix, I'll have a patch for it tomorrow.
