### ISSUE TITLE
Allow NULL for "pixels" and "pitch" parameters of SDL_LockTexture

### ISSUE THREAD

**Issue by dustdfg** [libsdl-org/SDL#6221]
I created a cairo surface from sdl_texture as pointed [here](https://stackoverflow.com/a/24317443). I don't need to get "pixels" and "pitch" each time I draw something with cairo (I need to lock texture before painting) but I need to make unused variables because I need to pass something. I can't just pass NULL because it tries to write there.

**Comment by slouken** [comment]
You do need to get the new pixels and pitch value each time you lock the texture, as they may change. You're not guaranteed to get the same pointer back on all backends.

What you can do though is save the pixels and pitch you got last time and avoid recreating the cairo surface if they're the same.
