### ISSUE TITLE
[KMSDRM] Relative mouse motion doesn't seem to work

### ISSUE THREAD

**Issue by midwan** [libsdl-org/SDL#6223]
This issue was reported to me recently, and I managed to recreate it as well:

When using the current release of SDL2 (2.24.0), relative mouse motion events don't seem to work as expected (no mouse movement), on the KMSDRM back-end. They work normally when using X11.
Absolute mouse motion events, as well as mouse button events, work fine in all back-ends.

This was tested on a Raspberry Pi 4/Pi400, running the latest Manjaro Linux which comes with the latest SDL2 libraries, and the Amiberry emulator. The original issue reported is here: https://github.com/BlitterStudio/amiberry/issues/995

Reverting back to SDL2 v2.0.22 fixes the behavior, so we're using that as a workaround for now. But it would be nice to find out what caused this with the latest update.

**Comment by cgutman** [comment]
It looks like you're using the mouse ID as an index into an array without bounds checking and assuming the mouse ID will be a contiguous range of integers starting at 0.

https://github.com/BlitterStudio/amiberry/blob/0eae398aa464d98245d48d2a678f6529339016b8/src/osdep/amiberry.cpp#L1311-L1312

https://github.com/BlitterStudio/amiberry/blob/4db6f1cbdf46a24c032b628bf334aeea9046c4e1/src/inputdevice.cpp#L9183

SDL 2.0.22 and earlier always passed 0 as the mouse ID, but f9d1f34b6ca5b9efa4d0eed6f6caba6823c9e395 started providing unique mouse IDs by passing the fd like we do with touch events. I suspect that's what broke your application.

**Comment by midwan** [comment]
> It looks like you're using the mouse ID as an index into an array without bounds checking and assuming the mouse ID will be a contiguous range of integers starting at 0.
> 
> https://github.com/BlitterStudio/amiberry/blob/0eae398aa464d98245d48d2a678f6529339016b8/src/osdep/amiberry.cpp#L1311-L1312
> 
> https://github.com/BlitterStudio/amiberry/blob/4db6f1cbdf46a24c032b628bf334aeea9046c4e1/src/inputdevice.cpp#L9183
> 
> SDL 2.0.22 and earlier always passed 0 as the mouse ID, but [f9d1f34](https://github.com/libsdl-org/SDL/commit/f9d1f34b6ca5b9efa4d0eed6f6caba6823c9e395) started providing unique mouse IDs by passing the fd like we do with touch events. I suspect that's what broke your application.

Thanks, that seems like a good candidate to start looking into. However, it doesn't explain why the button events are handled correctly, and only the motion event in Relative mode isn't? Absolute movement mode also works. And it only breaks in KMSDRM, but perhaps that's something to do with the X11 mouse events treated differently?

Regardless, I'll do some debugging to see if that area is causing the problems and report back!

**Comment by midwan** [comment]
Confirmed workaround from my side: Since SDL2 does not yet support multiple system mice, I've switched to using a hardcoded ID (0) for my project for now, instead of `event.motion.which` - this fixes the immediate problem, and I can revisit the issue later for an improved implementation.

**Comment by cgutman** [comment]
It does support multiple mice on KMSDRM. That's what the commit that broke your app was adding.

Some of the SDL APIs don't take a mouse ID, so things like SDL_GetMouseState() can't distinguish them, but if you just stick to mouse events, it should work.

**Comment by midwan** [comment]
@cgutman 
Sorry for coming back to this, but I was wondering about a few things regarding the implementation. If there's a better channel I should ask about this, please let me know:
- Is there a way to enumarate the number of mice detected in the system? Something like `SDL_NumMice()` (in the same pattern as `SDL_NumJoysticks`) would be nice to have for this, but I couldn't find anything similar.
- Can we somehow query each mouse for the properties it has? Number of buttons, number of axes, possibly a name, all would be very useful - again, similar to the query we have for Joysticks and GameControllers.
- Without the above, how can one know which mouce device an event was triggered from? Assuming we have 2 mice connected, and we start getting mouse motion events (and we check `event.motion.which` IDs), how do you know which ID is which physical device?

Again, apologies if this is already documented somewhere, I just couldn't find it - I would be grateful if you could point me in the right direction?
