### ISSUE TITLE
Under relative mode, mouse cursor does not correctly lock to center of the window

### ISSUE THREAD

**Issue by xeonmc** [libsdl-org/SDL#6224]
Using [this app](https://github.com/EsportToys/RawInputViewer) the logical cursor position can be examined. 

Platform: Windows (tested using Love2D 11.4 on Windows 10 21H2 19044.1949)

## Expected Behaviour
* On even-valued resolution, cursor should be stable at bottom-right central pixel
* On odd-valued resolution, cursor should be stable at exact central pixel.

## Actual Behaviour
* on even-valued resolution, cursor moves between the bottom-right and top-left central pixels
* on odd-valued resolution, cursor moves between the central pixel and its top-left neighbor

## Cause
In [this section](https://github.com/libsdl-org/SDL/blob/00452e47fa022314b4c21af2d4e5b63a53f89b8f/src/video/windows/SDL_windowswindow.c#L1311), the clipping rectangle is a 2px by 2px box.

## Experiment
Testing the WinAPI [ClipCursor](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-clipcursor) function using AutoIt, the following behaviours are observed:

<details>
<summary>Show Test Code</summary>
<p>

```AutoIt
$even = WinGetPos(GUICreate("even",128,128,-1,-1,0x80000000))
GUISetBkColor(0x00ff00)
GUISetState()

$odd  = WinGetPos(GUICreate("odd" ,127,127,$even[0]-127,-1,0x80000000))
GUISetBkColor(0xff0000)
GUISetState()

MsgBox(0,"Instructions", "Press Esc to exit, 1 for 1x1 clip, 2 for 2x2 clip, tilde for 0x0 clip, 3 for odd red window, 4 for even green window")

$dim=$even
$clp=oneBox

HotKeySet("`",zeroBox)
HotKeySet("1",oneBox)
HotKeySet("2",twoBox)
HotKeySet("3",clipOdd)
HotKeySet("4",clipEven)

do
until GUIGetMsg()==-3

Func clipEven()
     $dim=$even
     $clp()
EndFunc

Func clipOdd()
     $dim=$odd
     $clp()
EndFunc

Func zeroBox()
     $clp=zeroBox
     ClipCursor (                 _
         int($dim[0]+$dim[2]/2) , _
         int($dim[1]+$dim[3]/2) , _
         int($dim[0]+$dim[2]/2) , _
         int($dim[1]+$dim[3]/2)   _
     )
EndFunc

Func oneBox()
     $clp=oneBox
     ClipCursor (                   _
         int($dim[0]+$dim[2]/2)   , _
         int($dim[1]+$dim[3]/2)   , _
         int($dim[0]+$dim[2]/2)+1 , _
         int($dim[1]+$dim[3]/2)+1   _
     )
EndFunc

Func twoBox()
     $clp=twoBox
     ClipCursor (                   _
         int($dim[0]+$dim[2]/2)-1 , _
         int($dim[1]+$dim[3]/2)-1 , _
         int($dim[0]+$dim[2]/2)+1 , _
         int($dim[1]+$dim[3]/2)+1   _
     )
EndFunc

Func ClipCursor($L=0,$T=0,$R=0,$B=0)
     Local $struct = DllStructCreate("struct;long Left;long Top;long Right;long Bottom;endstruct")
     $struct.Left   = $L
     $struct.Top    = $T
     $struct.Right  = $R
     $struct.Bottom = $B
     MsgBox(0,"Clip Size: " & $R-$L & "x" & $B-$T, "Left: " & $L & @CRLF & "Top: " & $T & @CRLF & "Right: " & $R & @CRLF & "Bottom: " & $B)
     DllCall( "user32.dll", "bool", "ClipCursor", "struct*", $struct )
EndFunc
```

</p> 
</details>

#### Clip rectangle set to `int(left+width/2) , int(top+height/2) , int(left+width/2)+1 , int(top+height/2)+1`
* a 1x1 box
* On even-valued resolution, cursor is stable at bottom-right central pixel
* On odd-valued resolution, cursor is stable at exact central pixel.
* this is the desired behaviour

#### Clip rectangle set to `int(left+width/2)-1 , int(top+height/2)-1 , int(left+width/2)+1 , int(top+height/2)+1`
* a 2x2 box
* on even-valued resolution, cursor clips between the bottom-right and top-left central pixels
* on odd-valued resolution, cursor clips between the central pixel and its top-left neighbor
* the clipping stably clips against the input direction.

#### Clip rectangle set to `int(left+width/2) , int(top+height/2) , int(left+width/2) , int(top+height/2)`
* a 0x0 box
* On even-valued resolution, cursor jitters between bottom-right and top-left central pixels
* On odd-valued resolution, cursor jitters between central pixel and its top-left neighbor
* the jitter simply happens such that it is the pixel that was _not_ the previous position, independent of the actual input direction

## Recommended Solution:
Set the clip rectangle set to a 1x1 box of `int(left+width/2) , int(top+height/2) , int(left+width/2)+1 , int(top+height/2)+1`

**Comment by slime73** [comment]
I don't think relative mode is actually meant to lock the UI cursor to a specific spot, is it?

**Comment by slouken** [comment]
When using relative mode, the actual position of the cursor is undefined and may vary depending on platform and user hints.

**Comment by slouken** [comment]
You're welcome to create a PR for this change. The behavior isn't defined, but it also shouldn't hurt.

**Comment by slouken** [comment]
Merged!
