### ISSUE TITLE
bogus -Wpragma-pack warning from clang?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#6240]
See latest clang-cl build logs in CI: Is this bogus or what am I not seeing?

```
In file included from D:/a/SDL/SDL/src/video/windows/SDL_windowsmessagebox.c:35:
D:/a/SDL/SDL/src/video/windows/SDL_windowstaskdialog.h:21:10: warning: the current #pragma pack alignment value is modified in the included file [-Wpragma-pack]
#include <pshpack1.h>
         ^
D:/a/_temp/msys64/clang32/include/pshpack1.h:7:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(push,1)
        ^
In file included from D:/a/SDL/SDL/src/video/windows/SDL_windowsmessagebox.c:35:
D:/a/SDL/SDL/src/video/windows/SDL_windowstaskdialog.h:156:10: warning: the current #pragma pack alignment value is modified in the included file [-Wpragma-pack]

#include <poppack.h>

         ^

note: previous '#pragma pack' directive that modifies alignment is here

2 warnings generated.
```

**Comment by slouken** [comment]
It seems legit, though I don't know why clang is warning about it. Those headers are there exactly to change the pack alignment.

**Comment by sezero** [comment]
> It seems legit,

Hm??

>  though I don't know why clang is warning about it. Those headers are there exactly to change the pack alignment.

That's what I meant: alignment is changed for the header _and_ then restored.

**Comment by sezero** [comment]
I wonder whether it would change anything if we move `#include <pshpack1.h>`
down to line 120, i.e. only to affect the struct (yes I guess I sound silly,
and I don't have a clang-cl environment to test.)

**Comment by sezero** [comment]
If we intend to silence this warning, the solution I came up with
is removing SDL_windowstaskdialog.h and moving its content properly
into its only user SDL_windowsmessagebox.c: [patch.txt](https://github.com/libsdl-org/SDL/files/9585819/patch.txt)
https://github.com/sezero/SDL/commit/4245777711467a8d54d6612fc1a666399a3ce6d8
https://github.com/sezero/SDL/actions/runs/3069310158/jobs/4957804961

If you are OK with it, I can push. Or, I will close this and can the patch.

**Comment by slouken** [comment]
Yep, that's fine.

**Comment by sezero** [comment]
OK, patch applied.
