### ISSUE TITLE
Blit4to4CopyAlpha is possibly redundant?

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#6241]
`Blit4to4CopyAlpha` copies each pixel unchanged using the `DUFFS_LOOP` macro when all masks match between the source and destination format, however this is also what `SDL_BlitCopy` does using SSE, MMX or `SDL_memcpy` when an identity blit occurs. Is there a specific case where `Blit4to4CopyAlpha` would be used instead of `SDL_BlitCopy`?

**Comment by slouken** [comment]
Yep, I think this is redundant. Fixed, thanks!
