### ISSUE TITLE
Changing window size sometimes shrinks window by one pixel or does not correctly scale to window content

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#6243]
Hello all,

I have the following two issues, which are probably related: 

1. My application always preserves aspect ratio of its window when resizing it. After resizing there are almost always black lines without content at the borders of the window (bottom, left or right border). It seems the window is slightly larger than needed after resize and does not exactly fit rendered content. This code is used:

`SDL_RenderGetScale(sdlRenderer, &scale, &scale);`
`SDL_SetWindowSize(sdlWindow, width*scale*dpiFactor, height*scale*dpiFactor);`

The variables `scale` and `dpiFactor` are floats. `dpiFactor` is 0.5 on my screen.

2. My application has a bar at the bottom of the window that can be shown or hidden. When changing visibility of the bar, the height of the window is changed appropriately. After hiding and then showing the bar again, the size of the window may have shrunken by a small amount. It sometimes also leads to issue 1 (black lines at borders). This code is used:

`SDL_RenderGetScale(sdlRenderer, &scale, &scale);`
`SDL_SetWindowSize(sdlWindow, width*scale*dpiFactor, height*scale*dpiFactor);`
`SDL_RenderSetLogicalSize(sdlRenderer, width, height);`
`SDL_RenderSetScale(sdlRenderer, scale, scale);`

The variable `width` has always the same value and `height` is changed when adjusting visibility of the bar. For `scale` and `dpiFactor` see issue 1.

The sources of my applications can be found here: [previous.sourceforge.net](previous.sourceforge.net). Tests have been performed on macOS v12.6 with SDL2 v2.24.0.

Screenshots:
Window after start-up with no black lines:
<img width="210" alt="normal" src="https://user-images.githubusercontent.com/112762147/190845214-62e421d5-889a-48ba-b3eb-cdce52b41b03.png">

Window after resize with black line at bottom:
<img width="210" alt="black line bottom" src="https://user-images.githubusercontent.com/112762147/190845220-d781cc3b-95fa-4927-81a1-060079552bd7.png">

Window after resize with black line on right border:
<img width="210" alt="black line right" src="https://user-images.githubusercontent.com/112762147/190845225-08fe4b6c-9049-4bea-b5ce-8cc323260709.png">

**Comment by slouken** [comment]
High DPI support and scaling have completely changed for SDL 3.0. Can you see if things behave better with the latest code on GitHub?

**Comment by andreasgrabher** [comment]
My application has not been ported to SDL 3.0 yet and I can't do that anytime soon. This is a cross-platform application and I need to wait until at least most of the supported platforms provide SDL3 before porting it. This might take time in the order of years. So this should be fixed in SDL2.

**Comment by slouken** [comment]
You should mark your application as DPI aware using the Windows manifest and then you can work in pixels. If you want to get the UI scale, you can call `SDL_GetWindowDisplayScale()` in SDL 3.0 or write platform specific code in SDL 2.0.

**Comment by andreasgrabher** [comment]
How do I do that? The problem occurs on HiDPI but also on „normal“ displays. Am 20.05.2023 um 02:04 schrieb Sam Lantinga ***@***.***>:﻿
You should mark your application as DPI aware using the Windows manifest and then you can work in pixels. If you want to get the UI scale, you can call SDL_GetWindowDisplayScale() in SDL 3.0 or write platform specific code in SDL 2.0.
