### ISSUE TITLE
SDL_SetWindowMouseGrab() in fullscreen windows

### ISSUE THREAD

**Issue by vanfanel** [libsdl-org/SDL#6249]
Hi,

I am trying to debug cursor position problems (https://github.com/libsdl-org/SDL/issues/4822) with some Wayland compositors like Weston and the basic WLRoots reference compositor, tinywl.

So I am doing test code for helping me find the problem, hence my question:

Is `SDL_SetWindowMouseRect` supposed to work with fullscreen windows? (SDL_WINDOW_FULLSCREEN or SDL_WINDOW_FULLSCREEN_DESKTOP) 

On Linux/X11, `SDL_SetWindowMouseRect` seems to work with non-fullscreen windows only, but not on fullscreen windows.
And I can't see anything about this particular behavior on the docs.

**Comment by Kontrabant** [comment]
First question: given that this issue is over a year old, is it still relevant?

`SDL_SetWindowMouseRect` should work on a fullscreen window, yes. Checking it now, it seems to work fine for me on both Wayland and X11 fullscreen windows.

**Comment by vanfanel** [comment]
Not for me.
