### ISSUE TITLE
Regression: Apps launched via Emulationstation-DE AUR version (SDL 2.24.0-2) can't see controller, but with the earlier libSDL2-2.0.so.0 from the AppImage version (2.0.20+dfsg-2build1), they can.

### ISSUE THREAD

**Issue by prmbittencourt** [libsdl-org/SDL#6258]
Hello. This is my first bug report on GitHub, so let's see if I can get it right:

SDL VERSION: 2.24.0-2

PLATFORM: x86_64 Intel PC

OS: EndeavourOS Linux

DE: Problem presents itself in both KDE Plasma and Openbox, was not tested in other DEs/WMs.

HARDWARE: A wired (USB) Xbox 360 controller (ID 045e:028e Microsoft Corp. Xbox360 Controller).

SOFTWARE: EmulationStation Desktop Edition (ES-DE), several emulators including RetroArch, mGBA, Flycast, bsnes and Dolphin.

STEPS TO REPRODUCE: 
    Prerequisites: The hardware listed above connected to a PC running an Arch-based distro with access to the AUR that recognizes the controller (which it should out of the box). At least one videogame emulator configured in ES-DE.
    1.  Launch a game emulator from the terminal, a .desktop file or other common method. Verify that it recognizes controller input. Exit the program.
    2.  Launch the AUR build of ES-DE. Verify that it also recognizes controller input. 
    3.  Finally, launch the same, known to work, emulator from Step 1 via ES-DE.

EXPECTED BEHAVIOR: The emulator will recognize the gamepad's input just as it did when launched directly.

ACTUAL BEHAVIOR: The emulator does not recognize any controller input whatsoever.

ADDITIONAL INFORMATION: 
*  Mouse and keyboard input are not affected and work normally.
*  Unplugging the controller after the emulator has been launched via ES-DE then plugging it back in makes it work for that session.
*  The "EmulationStation-DE-x64_Current.AppInfo" version of ES-DE is bundled with an earlier version of SDL (2.0.20+dfsg-2build1) from the Ubuntu 22.04 repos. 
*  This AppImage version works as expected and does not present this issue. 
*  Replacing the natively installed file /usr/lib/libSDL2-2.0.so.0 with the version bundled in the AppImage causes the AUR version to also work as it should.

CONCLUSION: One or more of the changes made to SDL between the two versions mentioned above has caused a regression which is probably the source of the error.

**Comment by leonstyhre** [comment]
Test this as well with the latest ES-DE 2.0.0-alpha AppImage which comes bundled with SDL 2.24.0. I have just tested it with my Xbox 360 wired controller in Kubuntu 22.04 and it works fine. You can download it here:

https://gitlab.com/es-de/emulationstation-de/-/packages/9556946

The GUID for my controller is 030000005e0400008e02000010010000 so it may not be the exact same model as yours though.

**Comment by prmbittencourt** [comment]
Hello, I just tested the 2.0.0-alpha AppImage from the link you provided. There seems to be a very slight delay before controller input begins registering, I'd say a little less than five seconds, but after that it does work as expected, tested with several different emulators. There has also been an update to the AUR package (though it still reports its version as 1.2.6) which now behaves in the same way as the 2.0 alpha.

Most intro screens last longer than that, but it is noticeable if I immediately load a save state when the emulator launches. I noticed the delay because I was specifically paying attention to this issue, I don't know that I would have otherwise.

My controller's GUID is also 030000005e0400008e02000014010000.

**Comment by slouken** [comment]
It sounds like this can be closed then?

**Comment by leonstyhre** [comment]
There is still a problem for sure, there should be no delay with registering the controller. But as I've tested the ES-DE 2.0.0-alpha AppImage (which includes SDL 2.24.0) in both Kubuntu 22.04, Fedora 36 and SteamOS I'd say it's likely related to something else in the EndeavourOS operating system rather than being an SDL issue. Rolling release distributions often have problems unfortunately as they use less-tested libraries and kernels. Btw, the 1.2.6-2 release in the AUR only included an update to the video player code to fix some issues introduced when going from FFmpeg 5.0 to 5.1 and had no changes to controller logic. But if you updated your OS at the same time as you applied the ES-DE update then I guess some other library or kernel update could have caused the improvement you're seeing.

**Comment by prmbittencourt** [comment]
> But if you updated your OS at the same time as you applied the ES-DE update then I guess some other library or kernel update could have caused the improvement you're seeing.

I only ever update the entire system at once, so that's very likely. Which is odd, since as I mentioned, swapping the /usr/lib/libSDL2-2.0.so.0 file and changing absolutely nothing else resolved the issue previously. But as far as I'm concerned, the issue can be closed. Thank you very much.

If I may ask a weird question, how would you rate this bug report? This is my first time submitting one and I wonder if it was too long, too short, not clear enough, etc. I know feedback is important and I don't want to waste anybody's time by giving it the wrong way in the future.Hopefully I didn't waste yours.

**Comment by leonstyhre** [comment]
I'm not an SDL developer so I don't know what their expectations are, but to me your report looks very good with all the details I would expect!

**Comment by slouken** [comment]
Yup, that was a great bug report, thank you!
