### ISSUE TITLE
CMake: support a SDL2_LIBRARY variable that doesn't include SDL2MAIN_LIBRARY

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#6259]
In here:

https://github.com/libsdl-org/SDL/blob/c83329481760b9f587e2cf3482e8590339852db9/sdl2-config.cmake.in#L31-L34

It would be nice if we could also have a variable like this
```CMake
set(SDL2_LIBRARY SDL2::SDL2) 
```

In this way, it's possible to use a variable to link only to `SDL2_LIBRARY`, without possibly linking also to `SDL2MAIN_LIBRARY`, which happens when using the `SDL2_LIBRARIES `.

**Comment by ericoporto** [comment]
Possibly not needed after #6260

**Comment by sezero** [comment]
OK, closing.
