### ISSUE TITLE
Milkytracker black screen on Nvidia gpu Linux with SDL 2.24.0 (milkytracker issue #295)

### ISSUE THREAD

**Issue by yves-le-berre** [libsdl-org/SDL#6271]
Output from milkytracker 1.03.00 with SDL2 2.24.0 and nvidia 515.65.01 on ArchLinux :

Available Renderers: opengl opengles2 software 
Vendor     : NVIDIA Corporation
Renderer   : NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Version    : OpenGL ES 3.2 NVIDIA 515.65.01
SDL: Minimum window size set to 640x480.
SDL: Using accelerated renderer.
SDL: Renderer supports rendering to texture.
SDL: Using audio driver: pulseaudio
SDL: Buffer size = 2048 samples (requested 2048)

Same thing with NVIDIA GTX 1660.

==> Does not work with SDL2 2.24.0, but it does work with SDL2 2.0.22.

Here is the thread created on the arch linux forums (in case that helps):
https://bbs.archlinux.org/viewtopic.php?pid=2056385#p2056385

**Comment by ericoporto** [comment]
There was a similar issue, although it mentions wayland and you are using X11, see https://github.com/libsdl-org/SDL/issues/6263. Can you try with what is the current [main](https://github.com/libsdl-org/SDL/tree/4a06cc0f75af431d1eb05e4d5cbbdd34bdc1e1fc)?

**Comment by yves-le-berre** [comment]
No more black window with milkytracker 1.03.00 and sdl2-git 2.24.0.r289.g8d2cb1555.
