### ISSUE TITLE
Limited SDL_iconv support on Windows

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#6279]
On Windows, SDL2 is built without libc support by default, which means that `SDL_iconv` only supports ASCII, ISO-8859-1 and Unicode encodings, and not the larger range of encodings provided by other implementations. The OS/2 port supports both dynamically loading external iconv implementations and using the native conversion APIs, so it might be worth providing something similar on Windows as well using [libiconv](https://www.gnu.org/software/libiconv/), [win-iconv](https://github.com/win-iconv/win-iconv) or something similar.

**Comment by slouken** [comment]
Feel free to create a PR for this. I'll go ahead and close this in the meantime.
