### ISSUE TITLE
cmake doesn't overwrite HAVE_DLOPEN variable

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#6283]
(Noticed this while messing with https://github.com/libsdl-org/sdl12-compat/issues/222)

We have this check for dlopen() in our cmake'ry:
https://github.com/libsdl-org/SDL/blob/main/cmake/sdlchecks.cmake#L32-L55
```
macro(CheckDLOPEN)
  check_symbol_exists(dlopen "dlfcn.h" HAVE_DLOPEN)
  if(NOT HAVE_DLOPEN)
    check_library_exists(dl dlopen "" DLOPEN_LIB)
    if(DLOPEN_LIB)
      list(APPEND EXTRA_LIBS dl)
      set(_DLLIB dl)
      set(HAVE_DLOPEN TRUE)
    endif()
  endif()
  if(HAVE_DLOPEN)
    if(_DLLIB)
      set(CMAKE_REQUIRED_LIBRARIES ${_DLLIB})
    endif()
    check_c_source_compiles("
       #include <dlfcn.h>
       int main(int argc, char **argv) {
         void *handle = dlopen(\"\", RTLD_NOW);
         const char *loaderror = (char *) dlerror();
         return 0;
       }" HAVE_DLOPEN)
    set(CMAKE_REQUIRED_LIBRARIES)
  endif()
endmacro()
```

The last check_c_source_compiles() check attempts to make sure that we
have dlfcn.h and can link, however it doesn't overwrite the HAVE_DLOPEN
variable: Verified this by changing `dlopen` to a bogus `dlopen1`. How
can we rectify this? Use another unique dummy variable?

There may be more similar cases like this in our cmake'ry. @madebr: All
yours.

**Comment by sezero** [comment]
I'd suggest simplifying the particular CheckDLOPEN case into this:
```
macro(CheckDLOPEN)
  check_include_file("dlfcn.h" HAVE_DLFCN_H)
  check_symbol_exists(dlopen "dlfcn.h" _HAVE_DLOPEN)
  if(NOT _HAVE_DLOPEN)
     check_library_exists(dl dlopen "" _DLLIB)
     if(_DLLIB)
        set(_HAVE_DLOPEN TRUE)
     endif()
  endif()
  if(HAVE_DLFCN_H AND _HAVE_DLOPEN)
     set(HAVE_DLOPEN TRUE)
  endif()
endmacro()
```

As I said though, there may (or may not) be similar cases elsewhere
in our cmake'ry.

**Comment by madebr** [comment]
Speaking of `dlopen`.
The [man page of `dopen`](https://man7.org/linux/man-pages/man3/dlopen.3.html) explicitly says:
> Link with -ldl.

But our cmake script checks whether `dlopen` is available in the c runtime.
Aren't we depending on implementation details if `dlopen` is available without adding `-ldl`?
Does an executable built on a Linux platform not requiring `-ldl` also work on a platform requiring `-ldl`?

**Comment by sezero** [comment]
> Link with -ldl.

For the record, that is a man page from glibc (which majority of linux setups
use. More below.)

> But our cmake script checks whether `dlopen` is available in the c runtime.

Many unices other than linux have it in libc, such as macosx. Yes, macosx
is a bad example in this particular case because the flow in the cmake'ry
doesn't check it because (i) it knows that osx has it since version 10.4,
and (ii) it has it in its libc i.e. libSystemB.dylib. The offending commit
in sdl12-compat came from a netbsd developer, where, obviously, has dlopen
and friends in libc.

> Does an executable built on a Linux platform not requiring -ldl

Linux glibc has it in libdl. However, I don't know about e.g. the musl
libc environment.

>  also work on a platform requiring -ldl?

If we are talking about two linux environments with two different libc
environments: No. The difference in libc implementation will be enough of
a run failure, regardless of libdl presence or not.
