### ISSUE TITLE
is it supposed to be a square?

### ISSUE THREAD

**Issue by QuantumApprentice** [libsdl-org/SDL#6287]
https://github.com/libsdl-org/SDL/blob/1e1be0b954d5d4cb62da38655f229fe2781ded41/src/video/SDL_fillrect.c#L332

Just noticed this as I was browsing the source code,

` const SDL_Rect *r = &rects[0];
  if (r->x == 0 && r->y == 0 && r->w == dst->w && r->w == dst->h) {
` 
is it supposed to check the source width  (r->w) against both the destination width (dst->w) and height (dst->h)?

**Comment by 1bsyl** [comment]
@QuantumApprentice 
I wrote this (https://github.com/libsdl-org/SDL/commit/a75041e8dd820b89e746c737f58d0163e100a3e6) so I'll double-check

**Comment by QuantumApprentice** [comment]
ah that was quick.
sorry to bother, just thought I might have caught something

**Comment by 1bsyl** [comment]
@QuantumApprentice 
this is fixed, thanks good catch !

**Comment by QuantumApprentice** [comment]
awesome! now if only I can figure out this pitch stuff :P

**Comment by 1bsyl** [comment]
@QuantumApprentice 
w is the number of pixel for a row of you image.
so it should take a of "w * byteperpixel" size in memory.
but sometime, this size is bigger, because of alignement or tricks or other raison. and some the line size is the "pitch".

- so the full image size is so:  h * pitch. (and not always w * byteperpixel * h).

**Comment by QuantumApprentice** [comment]
> 

Thanks for the explanation, but my problem is a little more specific :)

If you're interested, I have an 8-bit paletted SDL_Surface that I'm editing the pixels of, then trying to take those pixel positions and modify the exact same pixel positions on a 32 bit SDL_Surface for display.
I know, its weird.
The reason is I'm trying to duplicate the animated palette system that some of the old games from the 90s used to have (specifically Fallout/Fallout 2, but I've also seen in on Ultima 7).
My problem is the 8-bit paletted surfaces tend to have some buffer pixels which change the pixel positions and the image size, as you pointed out, so just tracking the pixel index doesn't work for odd sized images ().

And finally, if you're interested in taking the time to answer a question:
Is there an efficient (or easy) way to match the pixel position on an 8-bit palettized surface (with some buffer pixels) to a 32-bit surface (which is a duplicate of the 8-bit paletted surface, just un-palettized using SDL_ConvertSurface) ?

If you don't have the time, then don't worry :)
Thank you for explaining the basics behind pitch!
