### ISSUE TITLE
SDL_Renderer / Metal - broken on IOS 16 with landscape App.

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#6289]
Trying IOS 16.  my landscape app is scaled to 1/4 of the screen and shifted when the metal backend is selected.

Using opengles2 renderer, the result is correct.

- Portrait apps have no issue.
- Not sure if related, but In the log, I notice a SDL "RESIZED" event with metal configuration.

This can be reproduced with simulator and also with real device

**Comment by slouken** [comment]
I'm not seeing this with testsprite2, in the new SDLTest Xcode project. I'm testing with the command line arguments --renderer metal and the iPhone 14 Pro simulator. Are you seeing the same thing there?

**Comment by 1bsyl** [comment]
@slouken 
I haven't tested the SDLTest project, 
but here's a reduced test case that clears screen + fill rects: [main.cpp.txt](https://github.com/libsdl-org/SDL/files/9704131/main.cpp.txt)

It's seems that using SDL_WINDOW_OPENGL flags when creating the window is the issue.

nb: 
- it needs iOS 16
- SDL_SetHint(SDL_HINT_ORIENTATIONS, "LandscapeLeft LandscapeRight");


I think it's not a regression of a recent commit, because the SDL code was 2yo. But it's still reproduce-able with current head.

With iOS 15.5 simulator there is not issue. this really appears with iOS 16 and this may be a IOS 16 issue also.

**Comment by slouken** [comment]
Thanks for the test case. I think this is the right fix, can you try it out?

**Comment by 1bsyl** [comment]
@slouken 
it isn't fixed : the testcase app isn't fullscreen.
(tested with latest xcode and now ios 16.1 simulator)

**Comment by slouken** [comment]
Better fix! :)

**Comment by 1bsyl** [comment]
yes fixed ! thanks !

**Comment by slouken** [comment]
You're welcome! :)
