### ISSUE TITLE
The cross compiling architecture should override auto-detected system architecture settings.

### ISSUE THREAD

**Issue by gazsiazasz** [libsdl-org/SDL#6292]
If I setup my project with
```cmake
set(CMAKE_OSX_ARCHITECTURES "i386" CACHE INTERNAL "" FORCE)
set(ARCH "x86")
```
and add SDL2 with 
```cmake
FetchContent_Declare(SDL2
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG main)
FetchContent_MakeAvailable(SDL2)
```
then I should get it compiled for 32 bit, but the build system does not respect that and says:
```
-- Platform: Darwin-21.6.0
-- 64-bit:   TRUE
```

**Comment by madebr** [comment]
Can you provide the complete (simplified) cmake script?
[`CMAKE_OSX_ARCHITECTURES`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) must be defined **before** the first project.

Disclaimer: I don't own any Apple produce

**Comment by gazsiazasz** [comment]
I missed that the CMAKE_OSX_ARCHITECTURES should be before the first project entry.
Confguring that way it looks that it is configured correctly! Thanks!

```
-- Platform: Darwin-21.6.0
-- 64-bit:   FALSE
```
