### ISSUE TITLE
Steam is unable to pass rumble from Steam Input emulated controllers to an Xbox One controller.

### ISSUE THREAD

**Issue by Bitwolfies** [libsdl-org/SDL#6298]
While I understand that steam and sdl are not the same, Steam Input does use it, so I feel its worth asking here. In essence, if you force steam input on, creating a virtual Xbox 360 controller, it cannot pass its rumble to an xbox one controller, this has even started to effect steam input native games, such as spider-man. https://github.com/ValveSoftware/steam-for-linux/issues/8590

While I'm not truly versed in how this all works, as far as I can tell SDL creates rumble from HIDAPI, which finds the HIDRAW file of the Xbox one controller. Only issue is is that I cannot make my controller generate one of those files, (using xone driver), and despite that, rumble in dolphin-emu works fine over SDL, so I'm unsure if that's even part of the issue.

I have not been able to reproduce this issue on the Steam Deck, rumble is fine there.

Thank you for your time.

**Comment by slouken** [comment]
You can pretty easily tell if this is an SDL issue on your system. Go ahead and grab the SDL source code and build and run testgamecontroller. Pulling the triggers will rumble the controller if everything is working correctly. If that doesn't work, please provide more information about your system so we can diagnose the issue (kernel version, which Xbox controller driver you're using, etc.)

Steam does use SDL for Xbox controller input, so this should be a good way for us to identify the issue.

**Comment by Bitwolfies** [comment]
For sure, SDL rumble works fine on my Xbox One controller, Steam Input just flat out does not pass on rumble to it, and its not just me as my linked issue showed.

My Kernel is ARCH Linux 5.19.11, my primary driver is Xone, but this happens over standard Xpad as well, my controller is an Xbox One S controller, revision: "4.08

**Comment by Bitwolfies** [comment]
Can confirm, my deck generates an HIDRAW file, this might be the issue.

**Comment by Bitwolfies** [comment]
New beta update to steam converts the input ui one to that seen on the deck (even got the battery low icon in the overlay as a bug) but still, go figure, rumble still DOES NOT WORK.

**Comment by slouken** [comment]
Is this fixed in the latest beta?

**Comment by Bitwolfies** [comment]
It is, at least on my end, I tested three games. Crash N sane, Sackboy, and Mekazoo. All three rumbled. Thanks for taking the time to look at it though, should I re open it?

**Comment by slouken** [comment]
Nope, I just wanted to confirm. Thanks!

**Comment by DinoSour69** [comment]
> You can pretty easily tell if this is an SDL issue on your system. Go ahead and grab the SDL source code and build and run testgamecontroller. Pulling the triggers will rumble the controller if everything is working correctly. If that doesn't work, please provide more information about your system so we can diagnose the issue (kernel version, which Xbox controller driver you're using, etc.)
> 
> Steam does use SDL for Xbox controller input, so this should be a good way for us to identify the issue.

Can I get some help with compiling this? First it said 
`fatal error: SDL.h: No such file or directory`
for a couple files so I changed the headers from
`"SDL.h"` to `<SDL2/SDL.h>` 
but now when i try to build it gives more errors than before.
`error: ‘SDL_GameControllerGetSerial’ was not declared in this scope;`
and similar errors for other functions.

This is actually my first time trying to compile C on linux so I feel pretty stupid atm.
all I want is for rumble to work on my controller. I didn't think it would be this involved of a process when I purchased it.
