### ISSUE TITLE
unexpected pitch in SDL_Surface with SDL_PIXELFORMAT_RGB24 format and some width value

### ISSUE THREAD

**Issue by multiSnow** [libsdl-org/SDL#6302]
This is the demo code:
```C
#include <SDL2/SDL.h>

int main(int argc, char** argv){
  SDL_Surface* surface;
  int expected_pitch = 0;
  for (int width = 100; width < 120; width++) {
    surface = SDL_CreateRGBSurfaceWithFormat(0, width, 2000, 24, SDL_PIXELFORMAT_RGB24);
    if (surface == NULL) {
      SDL_Log("SDL_CreateRGBSurfaceWithFormat() failed: %s", SDL_GetError());
      exit(1);
    }
    expected_pitch = width * surface->format->BytesPerPixel;
    if (expected_pitch != surface->pitch)
      SDL_Log("width: %d, pitch: %d, expected: %d\n", width, surface->pitch, expected_pitch);
    SDL_FreeSurface(surface);
  }
  return 0;
}
```

compile with:
```shell
gcc -Wall test.c -o test -lSDL2
```

output of `./test`:
```
INFO: width: 101, pitch: 304, expected: 303
INFO: width: 102, pitch: 308, expected: 306
INFO: width: 103, pitch: 312, expected: 309
INFO: width: 105, pitch: 316, expected: 315
INFO: width: 106, pitch: 320, expected: 318
INFO: width: 107, pitch: 324, expected: 321
INFO: width: 109, pitch: 328, expected: 327
INFO: width: 110, pitch: 332, expected: 330
INFO: width: 111, pitch: 336, expected: 333
INFO: width: 113, pitch: 340, expected: 339
INFO: width: 114, pitch: 344, expected: 342
INFO: width: 115, pitch: 348, expected: 345
INFO: width: 117, pitch: 352, expected: 351
INFO: width: 118, pitch: 356, expected: 354
INFO: width: 119, pitch: 360, expected: 357
```

SDL2: release-2.24.0-339-ge17f0c283
gcc: (Debian 12.2.0-3) 12.2.0
system: Linux 5.19.0-1-amd64 Debian 5.19.6-1 (2022-09-01)

(It seems the pitch is always a multiple of 4, thus some width could not match to it if bpp is depth is 24. Is it on purpose?)

**Comment by slouken** [comment]
Yes, this is expected. Each scanline is aligned for SIMD access.

**Comment by multiSnow** [comment]
That's OK, but is such align mentioned in https://wiki.libsdl.org/ ?

And, I did some more work and found that not only SDL_Surface, but also SDL_Texture created with SDL_TEXTUREACCESS_STREAMING needs align in each row of pixel data if using SDL_LockTexture.

But, align is not needed for SDL_Texture created with SDL_TEXTUREACCESS_STATIC if using SDL_UpdateTexture. It makes quite different.

How to determine if SDL_Surface/SDL_Texture needs align? or I should remember them in each case? or just forget RGB24 and let the program use nearly 4/3 more RAM for each picture by converting to RGBA32?

**Comment by slouken** [comment]
They always need alignment. That's why you should use the pitch member of the surface and the texture locking API.
