### ISSUE TITLE
Get SDL for Android published on Maven Central

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#6315]
The repo now contains [a script](https://github.com/libsdl-org/SDL/blob/bac54b3d267d50bd5092ead26ea2064270a2fabc/build-scripts/android-prefab.sh) to build an android prefab archive.
The next problem is how to get these published to Maven Central, so SDL becomes available in all new Android gradle projects.

This requires a few checks and actions:
- [ ] *Create Central Repository account*: [Maven documentation](https://maven.apache.org/repository/guide-central-repository-upload.html#other-projects) says OSS projects should apply to [OSS Repository Hosting](https://central.sonatype.org/publish/publish-guide/).
    - @slouken should create an account and [register `org.libsdl` by creating a new project](https://central.sonatype.org/publish/publish-guide/#create-a-ticket-with-sonatype).
    - Register `org.libsdl` so we can create as many subgroups as required (we currently only need `org.libsdl.android`).
- [ ] *Versioning*: [Change/modification/deletion/updating a released packaged is impossible](https://central.sonatype.org/faq/can-i-change-a-component/).
  So only create a release when we're confident it's ok.

  - There is a possibility to [add `-SNAPSHOT`suffixes](https://central.sonatype.org/publish/publish-guide/#introduction) to review the release progress.
  - There is also [a staging repo](https://central.sonatype.org/publish/release/#locate-and-examine-your-staging-repository) which we should use.

- [ ] Project namespace. In the [SDL](#6291) and [SDL_image](https://github.com/libsdl-org/SDL_image/pull/307) pr, I made the executive decision to use `org.libsdl.android` as namespace for all SDL libraries. Is this fine for now (and eternity)?
    ```
    org.libsdl.android:SDL2:2.25.0-1
    org.libsdl.android:SDL2_image:2.7.0-1
    ```

- [ ] Comply with [requirements](https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources).
   The current prefab aar is monolithic, so I might need to pull it apart. But I'm unsure how to do that for a non-Java project.
   I think https://github.com/libsdl-org/SDL/pull/6314 makes it compliant, but I'm not 100% sure.

- [ ] The [android docker image](https://github.com/Simplatex/android-lightweight) I used to develop the prefab script uses the latest android ndk/sdk version, which we probably don't want to use as build base. Should I look into creating a docker image using older sdk/ndk?

**Comment by slouken** [comment]
Do most projects use .android in their namespace?

**Comment by madebr** [comment]
To be honest, I don't have much experience with packages from the OSS maven repo.
So far, I was only using dependencies from Google.
My logic to include the `.android` is to make it clear it is for Android and it is not a java binding for example.

**Comment by madebr** [comment]
@slouken 
Would it be fine if we went ahead with this for SDL2 2.26.x?

Please [register `org.libsdl` here](https://issues.sonatype.org/secure/CreateIssue.jspa?pid=10134&issuetype=21).
My username there is `madebr` (=useful to allow others make releases).

To prove ownership, [you'll have to create a TXT record at libsdl.org (which we'll know after we've registered)](https://central.sonatype.org/publish/requirements/coordinates/#choose-your-coordinates).

**Comment by samuelgrigolato** [comment]
Hey @madebr, just so you know I'm consuming a lot of your work with SDL2 on Android lately. It is a bit scattered around and I had to fill in some knowledge gaps here and there (NDK docs are very much lacking at times), but your prefab scripts helped me save a lot of hair, so kudos and thank you very much for making your scripts find their way to SDL's repos.

In the end I was able to run SDL2 + curl + SDL2_image on Android using local AAR prefab dependencies, but I agree that it would be easier if libsdl supported deploying official builds to a public maven repository. I would be willing to invest some time helping if you find two more hands would be great to have. I have experience with enterprise Java so it might come in handy.

**Comment by slouken** [comment]
This is on my list to look at once SDL3 changes slow down, thanks @madebr!

**Comment by madebr** [comment]
@ericoporto I think you commented in the wrong issue.

**Comment by ericoporto** [comment]
I am currently patching SDL android layer and because there is no CI or no one in SDL team using Gradle I am afraid I may have to rely on a binary distributed package for SDL3 for our stuff and just get our Android port broken for quite a while. And no one answered in the issue. The more magic SDL adds "for ease" the smaller is the pool of developers in SDL android.

**Comment by madebr** [comment]
@slouken 
Since https://github.com/libsdl-org/SDL/commit/45081db9d41eaaf92c61da8acde4e7f11a0bf302, the build-release.py script creates an android `SDL3-3.1.2.aar` Android archive.

Do you intend to add these to the "official" release binaries?

If so, I'll need to add documentation to `README-android.md`.

**Comment by slouken** [comment]
I need to chat with you about how all the different Android builds work together. Can you send e-mail to slouken@libsdl.org to coordinate?

**Comment by madebr** [comment]
I just shot you a mail, and a friend request on Discord.

Thinking more about this issue. Perhaps it's more fitting for the SDL project to simply provide a SDL3 aar Android archive.
The SDL project does currently also not provide "official" binaries for other package managers.
Interested packagers can always respin the aar-chive, and publish it themselves.

My idea is to simply publish e.g. SDL3-3.1.2.aar, alongside the source, windows and apple archives.
This archive can then be used in Android gradle projects by adding it to [their dependencies](https://github.com/madebr/sdlcross/blob/269251cb809852d334c89b2138a7880e124b395d/app/build.gradle#L44).
An example Android aarchive can be found [at the bottom of this page](https://github.com/madebr/SDL/actions/runs/9584723851).

**Comment by slouken** [comment]
This sounds like a good plan. This means that users don't have to build SDL themselves and can drop an official release into their builds. Let's go with that.

Should we change the existing android-project framework to reflect this model? Can/should we fix buildandroid.sh to set up a project using this?

**Comment by madebr** [comment]
> Should we change the existing android-project framework to reflect this model? Can/should we fix buildandroid.sh to set up a project using this?


I went the NIH way, and replaced `buildandroid.sh` with `create-android-project.py` in #10177
The python script has identical behavior of the sh script, with the extra capability to create a project making use of prefab aar archives (`--variant aar`)

**Comment by slouken** [comment]
Sounds good.

**Comment by madebr** [comment]
Things left to do:
- document how to use an SDL3 aar archive in `docs/README-android.md`
- add a (short) readme into the aar itself

**Comment by slouken** [comment]
@madebr, can you do the documentation portion of this for SDL 3.2?

**Comment by madebr** [comment]
> @madebr, can you do the documentation portion of this for SDL 3.2?

Can do :)

**Comment by madebr** [comment]
I think using the aar is documented in https://github.com/libsdl-org/SDL/blob/main/docs/README-android.md#using-the-sdl3-android-archive-aar

It's used in [libsdl-org/SDL_helloworld](https://github.com/libsdl-org/SDL_helloworld/) [here](https://github.com/libsdl-org/SDL_helloworld/blob/f085633b57012dc271c4dce16a36503f9eafa861/android-project/app/build.gradle#L40-L46)

**Comment by leasses** [comment]
Hello @madebr,
As it's said in title 'Get SDL on Maven Central', why I haven't searched such published library on it? I've tried 'org.sdl'.

**Comment by madebr** [comment]
The libsdl project (currently) does not push artifacts to any 3rd party package manager.
However, we will gladly help users who want to do this and need help.
(If it's an issue with SDL -> GitHub issues. Else, use discourse or discord)
