### ISSUE TITLE
Distinguish Bluetooth Gamepads via Windows.Gaming.Input backend

### ISSUE THREAD

**Issue by DJm00n** [libsdl-org/SDL#6322]
https://github.com/libsdl-org/SDL/blob/f8f562dace406d48ca754dae5a95e2880cba492b/src/joystick/windows/SDL_windows_gaming_input.c#L335

We can use [Windows.Gaming.Input.Gamepad.IsWireless](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad.iswireless). Need to confirm behavior on real hardware.

**Comment by slouken** [comment]
Yup, this works, thanks!
