### ISSUE TITLE
libdecor is not correctly working after setting HAVE_LIBDECOR_H = 1 

### ISSUE THREAD

**Issue by tylerfan** [libsdl-org/SDL#6323]
Have libdecor built from source and linked to sdl2 with HAVE_LIBDECOR_H = 1 , and then I found that SDL_WAYLAND_HAVE_WAYLAND_LIBDECOR = 0 and there is no where in the code that sets it, only found SDL_WAYLAND_MODULE(WAYLAND_LIBDECOR) gets called but SDL_WAYLAND_MODULE expands to nothing.  If I remove the check in 
should_use_libdecor(), the libdecor_new will cause segmentation fault. Could someone help to give some insights of what might be wrong here?

**Comment by slouken** [comment]
@flibitijibibo, can you provide some insight? This seems wrong somehow... :)

**Comment by flibitijibibo** [comment]
I'll need some information just to be sure...

1. The output from ./configure (or cmake if that's what's being used)
2. The contents of the generated SDL_config.h

That should be a good start I think, at this point the libdecor path is used more than any of the others (particularly on Fedora Workstation) so once the build is working I expect everything to be okay from that point onward.

**Comment by tylerfan** [comment]
> I'll need some information just to be sure...
> 
> 1. The output from ./configure (or cmake if that's what's being used)
> 2. The contents of the generated SDL_config.h
> 
> That should be a good start I think, at this point the libdecor path is used more than any of the others (particularly on Fedora Workstation) so once the build is working I expect everything to be okay from that point onward.

Found the issue. There is another MACRO I need to define. SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR libdecor-0.so.0...

**Comment by slouken** [comment]
Are you building SDL yourself without using the autotool or CMake build systems?

**Comment by tylerfan** [comment]
> Are you building SDL yourself without using the autotool or CMake build systems?

yes. Nothing special I did, I am merely copying what the cmake has... I searched a bit in the sdl2 cmake file but did not find anything related to SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR. I know the macros circles around to different things, maybe i overlooked..
