### ISSUE TITLE
bad function version info update from SDLWikiBot

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#6343]
SDLWikiBot pushed a bad commit bumping several function version infos from
2.26.0 to 2.26.1: Possibly an adverse effect of us having a 2.24.1 release?
https://github.com/libsdl-org/SDL/commit/4ca86dae2fca96e99d7bfa574e48904c30fc28e3
CC: @icculus, @slouken.

**Comment by icculus** [comment]
Ugh, I forgot about the wikibot. I'll look at this.

**Comment by icculus** [comment]
Ok, the cronjobs corrected the wiki and headers after this fix was pushed, so we're good to go again.
