### ISSUE TITLE
Maximize behavior on Windows with borderless window

### ISSUE THREAD

**Issue by Taiko2k** [libsdl-org/SDL#6346]
I find some behavior a little undesired when using a ***borderless*** window under Windows.

 1. When using `SDL_MaximizeWindow()` it effectively uses a *borderless fullscreen* that covers the taskbar etc. Preferred behavior would be to still have the taskbar shown **and** have Windows recognize it as a maximized window for use in conjunction with 2:
 2. When dragging a borderless window, (i.e. using `SDL_HITTEST_DRAGGABLE`), allow window to be maximized by bumping window to top desktop edge, and sides to work with Windows snap etc. (This works with bordered windows, but not with borderless)

These currently both effectively work as expected under Linux. I wonder if it easy/possible to have this behavior under Windows? 

This would help SDL based applications that draw their own window decorations to have more consistent behavior.

**Comment by rminderhoud** [comment]
I don't experience this behavior exactly described but slightly different:

Case 1:
- Window starts as normal, bordered window
- `SDL_MaximizeWindow()` works as expected and the window is a maximized bordered window and shows the taskbard

Case 2:
- Window is set to fullscreen borderless using ` SDL_SetWindowFullscreen(m_window, SDL_WINDOW_FULLSCREEN_DESKTOP)`
- Window is restored from fullscreen `SDL_SetWindowFullscreen(m_window, 0)`
- Window is maximized `SDL_MaximizeWindow(m_window)`
- The window is maximized but "borderless" as described above. It has a titlebar but overlays the task bar.

**Comment by Taiko2k** [comment]
To clarify, I'm only referring to behavior when using a window created with the `SDL_WINDOW_BORDERLESS` flag.

With which:

Case 1: `SDL_MaximizeWindow(m_window)` is behaving efficiently equivalent to `SDL_SetWindowFullscreen(m_window, SDL_WINDOW_FULLSCREEN_DESKTOP)` on Windows, but I'm suggesting that that behavior is undesired.

Case 2: Dragging a borderless window using `SDL_HITTEST_DRAGGABLE` dosen't respond to the usual Windows desktop edge bumps.

**Comment by rminderhoud** [comment]
@Taiko2k Regarding your case here:

> Case 1: SDL_MaximizeWindow(m_window) is behaving efficiently equivalent to SDL_SetWindowFullscreen(m_window, SDL_WINDOW_FULLSCREEN_DESKTOP) on Windows, but I'm suggesting that this behavior is undesired.

and the cases I mentioned, I believe this is more of an issue with the resizable flag rather than the borderless flag. Setting the `SDL_WINDOW_RESIZABLE` solves many problems I have been having with maximized:

The following creates a borderless (almost) maximized window that doesn't overlap the taskbar
```
 Uint32 flags = SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE | SDL_WINDOW_MAXIMIZED;
 m_window = SDL_CreateWindow("my window", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1920, 1080, flags);
 ```

**Comment by abdes** [comment]
> The following creates a borderless (almost) maximized window that doesn't overlap the taskbar

Not working in SDL3.

The original issue report is as described by @Taiko2k also for SDL3.

**Comment by icculus** [comment]
I'm popping this into the 2.28.0 milestone, but we're almost done there so it might slide back to 2.30.0.

**Comment by icculus** [comment]
Worth noting that the X11 backend refuses to maximize the window at all with SDL_MaximizeWindow if not resizable...you can see this by hitting ctrl-m on testsprite2. I'm not sure if this is Gnome refusing to do it or X11 or SDL itself.

That Windows resizes at all (let alone incorrectly) in this case might be the actual bug. I haven't tried other platforms yet.

Gonna need @slouken's opinion on which is correct here.

**Comment by slime73** [comment]
> That Windows resizes at all (let alone incorrectly) in this case might be the actual bug. I haven't tried other platforms yet.

Related: #5240 - a separate issue with maximizing non-resizable windows in Windows, where I've also tested it on macOS and discovered that SDL_MaximizeWindow does nothing in that situation and therefore avoids bugs like that, just like X11 apparently.

**Comment by icculus** [comment]
Do we just want to catch this at the higher level then, and refuse to play ball if the window isn't resizable?

```diff
diff --git a/src/video/SDL_video.c b/src/video/SDL_video.c
index 73a4d2c0d..7a33be9b4 100644
--- a/src/video/SDL_video.c
+++ b/src/video/SDL_video.c
@@ -2503,7 +2503,7 @@ void SDL_MaximizeWindow(SDL_Window *window)
 {
     CHECK_WINDOW_MAGIC(window, );
 
-    if (window->flags & SDL_WINDOW_MAXIMIZED) {
+    if ((window->flags & SDL_WINDOW_MAXIMIZED) || ((window->flags & SDL_WINDOW_RESIZABLE) == 0)) {
         return;
     }
```

(plus the same on other APIs, like SDL_MinimizeWindow and such)

**Comment by slime73** [comment]
> plus the same on other APIs, like SDL_MinimizeWindow and such

If that approach is taken (which I'm personally in favour of), `SDL_CreateWindow` with a `SDL_WINDOW_MAXIMIZED` flag and no `SDL_WINDOW_RESIZABLE` flag will need to be handled, too. :)

**Comment by slouken** [comment]
This seems reasonable (though minimize is actually iconification, and should be allowed while not resizable)

**Comment by icculus** [comment]
> SDL_CreateWindow with a SDL_WINDOW_MAXIMIZED flag and no SDL_WINDOW_RESIZABLE flag will need to be handled, too. :)

I guess it doesn't make sense to mark a window Maximized at startup that can't be changed afterwards (and this has never worked correctly afaik, so there's no chance someone is trying to get some sort of borderless-fullscreen-except-leave-the-taskbar-available thing this way, right?)

**Comment by icculus** [comment]
> This seems reasonable (though minimize is actually iconification, and should be allowed while not resizable)

So the list would be:

- SDL_CreateWindow should strip SDL_WINDOW_MAXIMIZE if SDL_WINDOW_RESIZABLE isn't set.
- SDL_MaximizeWindow shouldn't work if not resizable
- SDL_SetWindowSize shouldn't work if not resizable
- ...SDL_SetWindowMaximumSize should refuse if trying to make the window smaller...?
- SDL_RestoreWindow should restore minimized windows, but it shouldn't change a maximized window's size if not resizable
- SDL_SetWindowResizable should...not care if a window is currently maximized?
- SDL_SetWindowFullscreen should fail if not resizable...?
- Hit Test callbacks should ignore any of the SDL_HITTEST_RESIZE_* results (or maybe the OS handles this?)

I suspect handling this at the higher level is the correct approach, but it's not necessarily straightforward, so we have to be careful here.

**Comment by slouken** [comment]
I suspect that there are applications that rely on being able to set fullscreen mode, and handle their own sizing via hit testing even though the window is not marked as resizable. I think the intent of the window flag is that the user can't manually resize the window, but the application is welcome to change the size at any time.

**Comment by slouken** [comment]
Let's have it ignore the maximize request for now, and we can revisit this (and make all platforms consistent the other way) if that ends up being a problem.

**Comment by icculus** [comment]
Okay, this is in for SDL2 and SDL3.
