### ISSUE TITLE
This site can’t be reached (https://www.libsdl.org/)

### ISSUE THREAD

**Issue by chegrane** [libsdl-org/SDL#6358]
- This site can’t be reached www.libsdl.org took too long to respond.

- ERR_CONNECTION_TIMED_OUT

**Comment by sezero** [comment]
It just works fine. Possibly a temporary issue at that time.

**Comment by chegrane** [comment]
@sezero 
It's very weird, I tried to open it on several browsers and it doesn't work for me. But on my smartphone it works!!

**Comment by chegrane** [comment]
@sezero 
I changed the wifi network, and its work. I am at the university, and it seems that they have problem with [Eduroam](https://en.wikipedia.org/wiki/Eduroam) network. 
Sorry to bother you and thank you 😅
