### ISSUE TITLE
Using org.freedesktop.portal.FileTransfer for drag'n'drop

### ISSUE THREAD

**Issue by orowith2os** [libsdl-org/SDL#6368]
![image](https://user-images.githubusercontent.com/93224879/194921709-3337e48f-333e-4e3d-aa3e-14df1935a447.png)
Taking a look at the source code, SDL doesn't use the portal for drag n drop. This is needed for SDL to work properly in a sandbox (Flatpak).

Here is the appropriate portal documenation: https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileTransfer

**Comment by slouken** [comment]
Patches are welcome!

**Comment by orowith2os** [comment]
I'd love to give a PR that implements this, but I'm better suited to Rust and can't quite use the bare dbus interfaces properly.

**Comment by flibitijibibo** [comment]
A Rust implementation technically wouldn't work with SDL, but having it as a starting point to port to C might still be useful for someone else looking to get this fixed.

**Comment by orowith2os** [comment]
I'll get right on doing that, then.

**Comment by orowith2os** [comment]
Here's how `ashpd` does it, hopefully should be enough. https://github.com/bilelmoussaoui/ashpd/blob/master/src/documents/file_transfer.rs

**Comment by Etaash-mathamsetty** [comment]
I have used dbus with C before, maybe I could do this

**Comment by orowith2os** [comment]
boop

might I suggest taking a note of this for SDL 3, and backporting it to SDL 2 if possible/needed/easy?

**Comment by orowith2os** [comment]
Poking in again: would anybody be interested in working on this? I'll go grab the appropriate resources as well as a reference implementation of this portal in a bit. I'd like to sort this out for some projects I'm maintaining.

**Comment by Etaash-mathamsetty** [comment]
I looked at some more code and I still don't understand where you get the key value

**Comment by orowith2os** [comment]
GDK implements it here: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/filetransferportal.c

It might also help to ask on the Flatpak matrix channel or x-d-p issue tracker.

**Comment by orowith2os** [comment]
The key also seems to be returned when you call [Start transfer](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-FileTransfer.StartTransfer), both sender and receiver seem to call it.

**Comment by orowith2os** [comment]
Full layout:

1. Sender calls StartTransfer to get the `key`
2. Sender calls AddFiles with the key to add files to the appropriate Transfer
3. Receiver calls StartTransfer to get the `key`
4. Receiver calls RetrieveFiles with the key to receive files
5. If the portal has been asked not to close the transfer automatically, the Sender can call AddFiles to send more files if desired
6. Receiver or Sender call StopTransfer to end the transfer if the portal hasn't been asked to automatically close the transfer

**Comment by orowith2os** [comment]
Another update and small fix: only source calls StartTransfer, the target/receiver obtains the key from the native dnd/clipboard protocol.

**Comment by Kontrabant** [comment]
Closing as completed via #8257 and #8274
