### ISSUE TITLE
Xbox controller does not work when not used in loop mode on Windows 10

### ISSUE THREAD

**Issue by pjaholkowski** [libsdl-org/SDL#6374]
Way to reproduce:
1. Get SDL2 version 2.24.1
2. Connect compatible Xbox One controller.
3. In example "testgamecontroller.c" after output message:
SDL_Log("There are %d game controller(s) attached (%d joystick(s))\n", controller_count, SDL_NumJoysticks());
put:
while (1 == 1)
{
        SDL_GameControllerUpdate();
        Uint8 buttonA = SDL_GameControllerGetButton(gamecontrollers[0], SDL_CONTROLLER_BUTTON_A);
        Sint16 triggerLeft = SDL_GameControllerGetAxis(gamecontrollers[0], SDL_CONTROLLER_AXIS_TRIGGERLEFT);
        SDL_Log("buttonA = %u, triggerLeft=%u\n", buttonA, triggerLeft);
}

The button pressing is not signaled for Xbox controllers but it works with Dual-Shock 4 pad.
In the debug output I found message:
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!07B31146: (caller: 07B33A5C) ReturnHr(1) tid(5438) 80070005 Access is denied
When I launched test application with elevated rights (as administrator) it still does not read pressing of A button but pressing of left trigger is valid.
Bug is not related to button mappings because in loop mode button reading works.

**Comment by pjaholkowski** [comment]
Okay I found solution:
When Xbox controller is used without message loop then you need to set hint SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");
however it is not needed for Dual-Shock 4 pad.
I would rather consider this as a bug because I have seen that SDL_GameControllerUpdate(); calls XInput underneath which does not need message loop to work. I also tried setting SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_XBOX, "0"); but it didn't help in anything.

**Comment by slouken** [comment]
This is the correct solution. Do you have suggestions on where to document this that would be helpful?

**Comment by pjaholkowski** [comment]
Documentation of SDL_GameControllerGetButton function states that return value:
"Returns 1 for pressed state or 0 for not pressed state or error; call SDL_GetError for more information."
I think that SDL_GetError should return proper error message why SDL_GameControllerGetButton and SDL_GameControllerGetAxis could not return controller state in this case.

The best way to document proper usage of api is in "testgamecontroller.c" because most people instead of reading documentation first starts to seek for tutorials and examples.

**Comment by slouken** [comment]
The problem here is that SDL doesn't know that your application isn't providing a Windows event loop. It assumes that everything is merrily going along, and your controller isn't active.

**Comment by pjaholkowski** [comment]
That's not correct
It is not about message loop but about a window. If you call that loop from testgamecontroller.c without creating a window it won't work either. In windows you can call message loop without creating a window.
