### ISSUE TITLE
Linux SDL 2.24.x: Wayland_HasScreenKeyboardSupport can cause a Segmentation fault

### ISSUE THREAD

**Issue by mupfdev** [libsdl-org/SDL#6378]
I am currently experimenting with a proprietary embedded Linux system (kernel version 5.15.16). If certain services on the device have not been started at least once (in this case a QT-based runtime), I get a segmentation fault when starting SDL2 applications.

gdb refers to the following return call:

https://github.com/libsdl-org/SDL/blob/8c9beb0c873f6ca5efbd88f1ad2648bfc793b2ac/src/video/wayland/SDL_waylandkeyboard.c#L148-L149

Therefore, it is possible that a NULL pointer is dereferenced here. Shouldn't this be checked before access?

**Comment by flibitijibibo** [comment]
Huh, I would have thought it would be checked too... do we not do a check on `_THIS` in the high-level call before we get here? I would expect all this to get initialized at SDL_VideoInit time.

If at all possible a full stack would be great... private stuff can be obscured of course, we just care about the SDL stack for the most part.

**Comment by mupfdev** [comment]
However, this would still not exclude that `driverdata->input` equals `NULL`. Then `driverdata->input->keyboard` would be the respective illegal access.

**Comment by mupfdev** [comment]
I made a screenshot when it happened. Sorry for not providing plain text.

![segfault](https://user-images.githubusercontent.com/5272365/195129153-fe7e2656-7c01-4497-99d7-08ec7c669d81.png)

**Comment by flibitijibibo** [comment]
Dang, so it really is SDL_Init... okay, looking at this now, should be quick to fix.

**Comment by flibitijibibo** [comment]
Just pushed https://github.com/libsdl-org/SDL/commit/be2cb0006644cb17cafca449f2d69c989e18ed2f. @slouken, this is definitely a 2.24.x candidate if we're doing one more of those...

If this fixes everything we should be set, let me know if there are any others like this!

**Comment by slouken** [comment]
Yep, we're doing rolling patch releases, so I merged this over to the 2.24.x branch.
