### ISSUE TITLE
Wayland games crash after "wayland: Raise wl_seat maximum version to 8"

### ISSUE THREAD

**Issue by ernstp** [libsdl-org/SDL#6392]
Both Stellaris and Jupiter Hell crash if running with latest SDL and videodriver wayland.
I bisected it to 0b88e609bc5b0cdb4218d02c8a03403b067fffa8  #6375

Running on Ubuntu 22.10 with libwayland 1.21.0, libdecor 0.1.0+git2209191759.8b42120, wayland-protocols 1.27

**Comment by slouken** [comment]
@Kontrabant, can you look at this?

**Comment by Kontrabant** [comment]
Can you run something with WAYLAND_DEBUG=1 and post the output?

**Comment by Kontrabant** [comment]
Try this: https://github.com/Kontrabant/SDL/tree/wayland_xkb_map_private

With version 7 and higher, it is required that keyboard keymaps need to be mmap-ed with MAP_PRIVATE. I was getting a crash in Weston as well without this change.

**Comment by ernstp** [comment]
> Try this: https://github.com/Kontrabant/SDL/tree/wayland_xkb_map_private
> 
> With version 7 and higher, it is required that keyboard keymaps need to be mmap-ed with MAP_PRIVATE. I was getting a crash in Weston as well without this change.

That fixes it
