### ISSUE TITLE
provide prebuilt xcFramework in release artefacts for iOS

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#6398]
see https://github.com/libsdl-org/SDL/blob/main/docs/README-ios.md#notes----xcframework

In the `docs/README-ios.md` file, it's mentioned that SDL supports a new framework build that should be used when creating an iOS Xcode project, to keep compatibility with building in ARM based macOS computers. Currently this means you download the SDL source code, build this framework in Xcode, and then you can load your own project and use it. 

Making it available along the release artefacts would make it quicker to setup iOS projects.

Also, see comment: https://github.com/libsdl-org/SDL/pull/6188#issuecomment-1277181576
> Right now the xcframework is for iOS, which isn't pre-built as part of the release process. In the long run we probably want a single xcframework that covers all platforms and architectures and release that as a single download for Xcode. I'm not sure what needs to be done to make that happen though

- xcFramework was originally introduced in #6188
- issue that added the possibility #6156 

---

I also tried to follow this manual steps (which I was writing for myself)

1. Download **SDL** and extract it to a directory of your choice
2. Start **Xcode** and open the SDL project in `Xcode/SDL/SDL.xcodeproj`
3. In the Xcode title menu, go in **Product**, **Scheme**, **Choose Scheme** and  select **xcFramework-iOS**
4. Still in **Product**, go in **Destination** and select **Any iOS Device (arm64)**
5. Now in **Product**, **Archive** should be available, hit it to build the xcFramework
6. Wait for the build to finish, when it's done, in the window that appears, make sure the selected archive is the one you just build and click **Distribute Content**
7. Now click in **Built Products** and save it

But the resulting archive is a 33kB artifact so I don't think this is correct. I am on Xcode 14 and macOS 12.6.

**Comment by slouken** [comment]
SDL3 releases will be built as xcFrameworks, thanks!
