### ISSUE TITLE
SDL2d.dll not found when building with cmake 

### ISSUE THREAD

**Issue by sufiblues** [libsdl-org/SDL#6399]
I am trying to add SDL2 to my project by adding the source code directly to the repo and building it. My project folder looks like this 
root
-->src
-->include
-->libs
-->-->SDL2 (source)

My cmake file 
````
cmake_minimum_required (VERSION 3.8)

project ("shurukaro_win")

#  = include folder
include_directories(include)

#  = SDL
add_subdirectory(libs/SDL2)
include_directories(libs/SDL2/include)
link_libraries(SDL2main SDL2)

#  = flatbuffers
include_directories(libs/flatbuffers_header)

#  = imgui
include_directories(libs/imgui)
file(GLOB GUI libs/imgui/*.cpp)
add_library(imgui  ${GUI} )

# Add source to this project's executable.
file(GLOB SRC_FILES src/*.cpp)
add_executable (shurukaro_win  main.cpp ${SRC_FILES} )
target_link_libraries(shurukaro_win  imgui)


if (CMAKE_VERSION VERSION_GREATER 3.12)
  set_property(TARGET shurukaro_win PROPERTY CXX_STANDARD 20)
endif()

````

The error code that I get is "SDL2d.dll not found". The weird thing is that I think its a typo since it specfically says SDL2d.dll instead of SDL2.dll. Also when I link to the static library 'link_libraries(SDL2main SDL2-static)' it works perfectly fine.

**Comment by madebr** [comment]
When building in debug mode, by default, the CMake script adds a `d` suffix:
https://github.com/libsdl-org/SDL/blob/70dfd6dd1a89f753c47bf5db06fa843a60af5169/CMakeLists.txt#L90-L91
This suffix is overridable.

On Windows platforms, it is useful to add the following to your cmake script.
It automatically copies the correct `SDL` dll.
```cmake
if (WIN32)
    add_custom_command(
        TARGET yourgame POST_BUILD
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different $<TARGET_FILE:SDL2::SDL2> $<TARGET_FILE_DIR:yourgame>
        VERBATIM
    )
endif()
```

**Comment by sufiblues** [comment]
> When building in debug mode, by default, the CMake script adds a `d` suffix:
> 
> https://github.com/libsdl-org/SDL/blob/70dfd6dd1a89f753c47bf5db06fa843a60af5169/CMakeLists.txt#L90-L91
> 
> 
> This suffix is overridable.
> On Windows platforms, it is useful to add the following to your cmake script. It automatically copies the correct `SDL2.dll` to the correct build folder..
> 
> ```cmake
> if (WIN32)
>     add_custom_command(
>         TARGET yourgame POST_BUILD
>         COMMAND "${CMAKE_COMMAND}" -E copy_if_different "$<TARGET_FILE:SDL2::SDL2>" "$<TARGET_FILE_DIR:yourgame>"
>         VERBATIM
>     )
> endif()
> ```

 Thank you so much, adding this snippet fixed my issue. My build folder is looking more readable haha. Although I am still not sure what the snippet does. My understanding is that it takes the "sdl2.dll" file from the lib folder and place it in the same location as the executable. Is this a windows only thing? Will it have the same issue on linux/macos?

**Comment by madebr** [comment]
> Thank you so much, adding this snippet fixed my issue. My build folder is looking more readable haha. Although I am still not sure what the snippet does. My understanding is that it takes the "sdl2.dll" file from the lib folder and place it in the same location as the executable. 

Correct.
It copies the "target file of SLD2" to the "target file dir of yourgame".
So after building yourgame, it will copy `SLD2(d).dll` to the location where yourgame has been built.

> Is this a windows only thing? Will it have the same issue on linux/macos?

This is a Windows-only thing.
On other os'es, CMake sets the rpath in the build directories.
(This rpath is removed when installing.)

An alternative to copying dll's to the build location is setting [`CMAKE_RUNTIME_OUTPUT_DIRECTORY`](https://cmake.org/cmake/help/latest/variable/CMAKE_RUNTIME_OUTPUT_DIRECTORY.html).

I'm going to close this issue as your issue seems to be resolved.

**Comment by starball5** [comment]
Related to the solution posted by @sufiblues, see [How to copy DLL files into the same folder as the executable using CMake?](https://stackoverflow.com/q/10671916/11107541)
