### ISSUE TITLE
Joystick / controller support broken in Windows XP

### ISSUE THREAD

**Issue by Garirry** [libsdl-org/SDL#6400]
There are upwards of two separate albeit related issues relating to game controller input when running an app on Windows XP. The results are identical on two different XP systems, and are not present on any other system I've tried (W7, W8.1, Linux Wine and Linux native).

On versions 2.0.14 and 2.0.16, the earliest I've tested, the joystick is detected (using `SDL_NumJoysticks`) however it is not recognised as a valid game controller (`SDL_IsGameController`). Starting in 2.0.18 and up until the current version 2.24.1, it is further broken as `SDL_NumJoysticks` always returns 0, as if nothing is ever plugged in.

After experimenting, I found out that setting `SDL_HINT_JOYSTICK_RAWINPUT` to 0 completely solves this problem, and the controller works as if there are no problems. I have not found any adverse affects on any other platform. In fact, on Wine, it actually makes it more reliable, as otherwise I had inconsistent controller detection issues (though I haven't gone in-depth into this since it's not my priority). If this can't be fixed or set as the default for whatever reason, at the very least it should be documented so that other users know how to resolve it.

**Comment by slouken** [comment]
This should be fixed, thanks!
