### ISSUE TITLE
No proper way to access all Windows Messages (WM) in real time

### ISSUE THREAD

**Issue by GhostCore07** [libsdl-org/SDL#6413]
From my short inspection of the source code I only see two ways that SDL allows application code to access WM_ messages from an SDL window:

`SDL_SetWindowsMessageHook(SDL_WindowsMessageHook callback, void *userdata);`

and

`SDL_EventState(SDL_SYSWMEVENT, SDL_ENABLE);`

From my short testing both methods have issues with how they are implemented and thus lack the ability to robustly handle windows messages.

In the case of `SetWindowsMessageHook` it is being called before before `DispatchMessage`, which is flawed (my opinion) because on a `WM_NCLBUTTONDOWN`, `DispatchMessage` will not return until the window move is completed. Thus there is no way for this hook to actually catch any of the messages that are being sent directly to the windows procedure during the handling of the window move (`WM_MOVING`, `WM_WINDOWPOSCHANGING`, `WM_WINDOWPOSCHANGED`, etc.). They are just lost forever, that's not cool! I presume it’s the same for resizing as well but I have not tested it.

Perhaps this flaw was noted at some point because an attempted workaround was provided by enabling `SDL_SYSWMEVENT` which is checked in the Window Procedure: 

```
LRESULT CALLBACK
WIN_WindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    ...
    if (SDL_GetEventState(SDL_SYSWMEVENT) == SDL_ENABLE) {
        SDL_SysWMmsg wmmsg;
        ...
        SDL_SendSysWMEvent(&wmmsg);
    }
```

However, the flaw (my opinion) in this case is that the message handler in the windows procedure provided by SDL sends these messages to the SDL event queue via `SDL_SendSysWMEvent`. But as already explained, The SDL loop is blocked until `DispatchMessage` returns, which it won’t do until the move (or resize) is completed. The result then is that potentially thousands of events back up in the SDL queue that have no way of being processed until control is returned from `DispatchMessage`. Also not cool!

In my humble opinion a much more robust design would provide a way to handle messages directly from the window procedure either before or after `DefWindowProc` returns. Perhaps with a callback style hook similar to `SetWindowsMessageHook`, but inside the windows procedure somewhere, rather than before `DispatchMessage`. This way every single message sent to the window can be intercepted (in the before case) or inspected (in the after case) as they are being received.

If I am missing something here please let me know. This was tested in Windows 10. Thank you for reviewing this issue.

**Comment by genpfault** [comment]
Possibly related to #1059 & #4836.

**Comment by slouken** [comment]
You can use SDL_SetWindowsMessageHook() in SDL 3.0 to set a filter function that runs exactly when you're hoping. :)

**Comment by slouken** [comment]
We've also added a couple of ways of handling the Windows modal move/resize loop that don't require setting a message hook in  https://github.com/libsdl-org/SDL/commit/02f356439d1fedf0b4e5f96cd23c2d570e2f7be2

**Comment by GhostCore07** [comment]
Looking forward to the upgrade, appreciate the work!
