### ISSUE TITLE
Multigesture Events not being generated on Windows

### ISSUE THREAD

**Issue by SmithTom6304** [libsdl-org/SDL#6417]
SDL_MultiGestureEvents are not being generated on Windows when using a trackpad despite setting SDL_MOUSE_TOUCH_EVENTS hint to "1". This is occuring in C++ applications as well as C# using SDL-CS. This can be tested using the [LazyFoo MultiGesture tutorial](https://lazyfoo.net/tutorials/SDL/55_multitouch/index.php) - note that the SDL hint is not set in the program by default, but the issue persists after it's added. The issue is also occuring in our own application.

Some other symptoms I've found which might be related:

When attempting to pinch zoom on a windows trackpad a Control key down event is generated, followed by Mousewheel events. Is this intentional, as a way of handling pinch zoom via mouse events?

On windows, SDL_TouchFingerEvents aren't generated unless the touchpad is "clicked" down, rather than just touching it (like on mac). While it would be good to have finger down events fire when the touchpad is pressed rather than clicked, its possible that this isn't feasible due to how SDL creates its touch events synthetically from mouse events. However, I would expect FingerMotion to fire regardless of the mouse being up or down, as MouseMotion is still firing.

This behaviour all works correctly on Mac. This has been tested on Windows 10 version 21H1, across two different touchpad laptops. This occurs when building SDL from source c6e89619794ed6307f9efb0b242a2cdb605e1dc3, as well as on our forked version from back in August 293d29b78a7de4fdff26f59682852b0dca4786a9.

**Comment by zxhxw** [comment]
In fact, the operation of the touchpad is considered a touch event, not gesture event

**Comment by zxhxw** [comment]
> LazyFoo MultiGesture tutorial

In fact, the operation of the touchpad is considered a touch event, not gesture event
