### ISSUE TITLE
include version number in binaries as a human-readable string

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#6418]
When inspecting various versions of SDL, particularly in games that bundle some arbitrary version of their own, it would be nice if SDL included its own version number in a human-readable format that could be extracted with `strings(1)`, ideally with both the "marketing" version number (which tells us whether it's a release or a snapshot, and which branch) and the git revision (if available).

Prior art: Steam (which uses a bundled copy of SDL) logs something like `Loaded SDL version 2.25.0-7511446` during startup, but I think it's composing that with `printf()` at runtime. Looking at `strings(1)`, it seems like 2.25.0 is probably the `SDL_GetVersion()` (I don't see it anywhere in the `strings` output) and `7511446` is probably the `SDL_GetRevision()`.

In SDL official source release tarballs, as used in e.g. Debian and the Steam Runtime, the source tarball has a `SDL_revision.h` that contains a git commit like `https://github.com/libsdl-org/SDL.git@a1d194...`, but you need external information to find out that that commit a1d1946 was actually the `release-2.24.1` tag. It might be preferable to use `git describe --long --tags` if available, to get `release-2.24.1-0-ga1d1946dc` (0 commits after release-2.24.1) for real releases or something like `release-2.24.1-6-gabcdef` for unofficial snapshots?

In builds that are done from a git snapshot but with git unavailable at build time, `SDL_REVISION` gets defined to the empty string, which means we have no info. It seems like it would be nicer if the fallback mentioned the "marketing" version number, perhaps spelled as `2.24.1` or `2.24.1 (no VCS info available)`.

It would also be great if there was a way for downstream distributors to mark the binary with their own idea of version numbering, so we have a way to identify what patches (if any) have been applied - it's easy for a package vendor to insert their own vendor name and version number into the build system. Perhaps something like a build option `--with-vendor-info="Debian: 2.24.1+dfsg-1"`, which could lead to the `SDL_REVISION` in various different vendor builds looking like one of these?

```
release-2.24.1-0-ga1d1946dc (Debian: 2.24.1+dfsg-1)`
release-2.24.1-0-ga1d1946dc (SteamRT: 2.24.1+dfsg-1+steamrt1.1)`
2.25.0 (Steam revision 7511446)
2.24.1 (CS:GO build 123456)
```

Or this could be a new `SDL_DescribeVersion()` or something, instead of repurposing `SDL_GetRevision()`, if preferred.

The official binary builds done by @slouken for each release could even make use of that option too, to flag them as `--with-vendor-info="upstream win32-x64"` or similar and distinguish them from third-party binary builds.

**Comment by slouken** [comment]
This seems like a good idea, patches welcome!

**Comment by slouken** [comment]
Returning the string to the application should probably be done through a new API rather than repurposing SDL_GetRevision()

**Comment by AntTheAlchemist** [comment]
Could a char[] be added to the SDL_version struct?

**Comment by smcv** [comment]
> Could a char[] be added to the SDL_version struct?

That would be an ABI break, so no.

**Comment by madebr** [comment]
> Returning the string to the application should probably be done through a new API rather than repurposing SDL_GetRevision()


Reading [its documentation](https://wiki.libsdl.org/SDL_GetRevision), the format of the string is not fixed.
How about the following:
- If a `VERSION` file exists in the root of the project, assume that is the version (useful for source tarballs)
- Else, use git to determine the version/revision. For current HEAD, this is `release-2.24.0-540-g94ac8ae08`.

**Comment by smcv** [comment]
I'll try to implement a draft of this at some point. I'll do a separate API call since @slouken preferred that, but flattening that new API into `SDL_GetRevision()` instead would be straightforward.

**Comment by slouken** [comment]
Yeah, after reading the documentation again I agree using `SDL_GetRevision()` makes sense. Using a VERSION file at the root of the project is fine.

**Comment by smcv** [comment]
I'd prefer the vendor info to be a separate build option that gets appended to the upstream revision description, because in Debian etc., we would want to set the vendor info without having to overwrite the version supplied by the upstream source (which is still interesting from the point of view of "this is what we based our package on").

**Comment by smcv** [comment]
> I think this means we need to locally tag releases before building binaries, right?

Yes unless we have a mechanism for "ignore what git says, just use this string".

**Comment by slouken** [comment]
I think it's useful to have the full git information in the release binaries. Also I'd add the tag SDL to the info, so the upstream revision would be: `SDL-release-2.24.0-540-g94ac8ae08` and a prerelease build might be: `SDL-prerelease-2.23.2-0-gcb46e1b3f`

**Comment by smcv** [comment]
OK. That would be easy to grep out of `strings(1)`, which is nice, and the fallback if we don't have git info for whatever reason could look like `SDL-2.24.1` which also seems entirely reasonable.

**Comment by smcv** [comment]
Or `SDL-approximately-2.24.1` or something :-)

**Comment by smcv** [comment]
> There was an [interesting comment](https://github.com/libsdl-org/SDL/pull/6477#issuecomment-1299133284) about this [CMake module](https://github.com/rpavlik/cmake-modules/blob/main/GetGitRevisionDescription.cmake) recently, just mentioning so the information isn't lost.

I'm not intending to implement that myself, but if someone who likes (and understands!) CMake wants to open a pull request, I have no objection to the CMake part of #6420 being replaced.
