### ISSUE TITLE
SDL_JoystickSetVirtualAxis does not change axis

### ISSUE THREAD

**Issue by GentleHedgehog** [libsdl-org/SDL#6426]
Hello, I use a next version of the library - 2.0.18 (Windows x64). 

Try to open a new virtual joystick by:
```
SDL_Init( SDL_INIT_JOYSTICK );
int index1 = SDL_JoystickAttachVirtual(SDL_JoystickType::SDL_JOYSTICK_TYPE_WHEEL, 4, 0, 0);
int index2 = SDL_JoystickAttachVirtual(SDL_JoystickType::SDL_JOYSTICK_TYPE_WHEEL, 4, 0, 0);
```
but this function always returns 0 index (index1 == index2 == 0).

Then I try to use:
```
int index = SDL_JoystickAttachVirtual(SDL_JoystickType::SDL_JOYSTICK_TYPE_WHEEL, 4, 0, 0);
auto joystick = SDL_JoystickOpen(index);
auto res = SDL_JoystickSetVirtualAxis(joystick, 0, 10); // set 0 axis to 10
SDL_JoystickUpdate();
```
In this case the res is equal to 0 (success), but:
```
auto axisState = SDL_JoystickGetAxis(joystick, 0); // get 0 axis state
```
axisState == 0!  (instead of 10)
What the problem?

**Comment by slouken** [comment]
If I run your first program, I get index 0 and then index 1.

The second test program is running into the protection against jitter. The initial axis motion needs to be around 500 or more to register. I'll change this so it's not done for virtual joysticks, but just so you know, that's what's happening.

**Comment by GentleHedgehog** [comment]
> If I run your first program, I get index 0 and then index 1.
> 
> The second test program is running into the protection against jitter. The initial axis motion needs to be around 500 or more to register. I'll change this so it's not done for virtual joysticks, but just so you know, that's what's happening.

Thank you, axis value 500 works!) But the index is always 0.. May be it is a bug in sdl version 2.18

**Comment by slouken** [comment]
Yes, please check the index values in SDL 2.24 and report a separate bug if you're still seeing the issue there.
