### ISSUE TITLE
change window shape with SDL_SetWindowShape

### ISSUE THREAD

**Issue by lpalozzi** [libsdl-org/SDL#6428]
Hi,

Trying to *change* the window shape after previously being set with SDL_SetWindowShape, but it seems to do a union with previous shapes.

Following X11_SetWindowShape and SDL_CalculateShapeBitmap, the bitmap shaper->driverdata is not zeroed, and previous bitmap is OR'd with the new shape. X11_XShapeCombineMask is then called with ShapeSet operation.

I guess the Shape Extension is not fully supported?

Thanks.

**Comment by lpalozzi** [comment]
In SDL_CalculateShapeBitmap I zero the bitmap to fix it in my case. I'm not sure if this is a general solution for all use cases.

 ```
   if(SDL_MUSTLOCK(shape))
        SDL_LockSurface(shape);

    SDL_memset(bitmap, 0, shape->h * bytes_per_scanline);

    for(y = 0;y<shape->h;y++) {
```

**Comment by slouken** [comment]
This change looks good, thanks!
