### ISSUE TITLE
Xbox controllers with BLE firmware (5.x+) rumble crash

### ISSUE THREAD

**Issue by kakra** [libsdl-org/SDL#6435]
https://github.com/libsdl-org/SDL/blob/413500ab69d9ac288a73946073d4414376ca17d2/src/joystick/hidapi/SDL_hidapi_rumble.c#L90

In the xpadneo project, we found that newer BLE firmwares on original Xbox controllers need to raise this delay from 10ms to 50ms otherwise it may crash or delay the rumble loop inside the firmware.

I'm not sure if this is the code path used by the rumble thread on Xbox controllers in Linux, maybe it needs adjustments somewhere else in the code.

Suggested-by: https://github.com/ValveSoftware/steam-for-linux/issues/8107#issuecomment-1287778570
See-also: https://github.com/atar-axis/xpadneo/commit/74ea7c1488f9ccebf3ed6d9aea1319cacb08c625

**Comment by slouken** [comment]
This has the side effect of delaying all reports for all controller types. I think the right thing to do is configure the report update rate for each controller type, possibly even by report type.

Thanks for the report, I'll investigate this for 2.26.

**Comment by kakra** [comment]
Yeah I was thinking about implementing something similar in the kernel ff-memless driver, so drivers using ff-memless can use an individual rumble update interval. Currently it's doesn't have anything like that, just an envelope update interval per effect which can result in combined envelope rumble update intervals below the supported intervals in the firmware.

I think it'd be good to have this at least per model, defaulting to 10ms if it wasn't set otherwise. Then, individual models can set other values. Xbox controller firmware <5 supports 10ms, firmware 5+ supports 50ms as the minimum interval - at least for Bluetooth. But I think the xone author found similar behavior for USB connections. Hint: There's a pitfall with older firmwares reporting themselves as firmware 9 via Bluetooth when paired with a Linux host, which is actually some 3.x or 4.x firmware. And xpadneo actually pretends to be firmware 11 to bypass wrong SDL mappings because SDL doesn't look at HID descriptors.

I'm not sure what you mean by "report type"... There's probably just one rumble report but at least for Xbox Elite 2 controllers, there are some more reports that could be sent to the device, e.g. RGB updates for the Guide button. Not sure if those have the same restrictions, I haven't implemented support for this in xpadneo yet.
