### ISSUE TITLE
Applications look blurry/"soft" on wayland with fractional scaling

### ISSUE THREAD

**Issue by git-bruh** [libsdl-org/SDL#6438]
sway - `6e023257e8e9a6673fc3ff69048cdaf8baa70044`
wlroots - `fa7d2cb8d60ed48c44c707106c03682056ddfaca`
nvidia - `520.56.06`
egl-wayland - `1.1.11`
sdl2 - `2.24.1`

GTK programs look the same in terms of sharpness at both 1.00 and 1.25 scale, but SDL seems to be blurry at any scale that isn't 1.00

Qemu with scale of 1.00 (`-device virtio-vga-gl -display sdl,gl=on`)

![100](https://user-images.githubusercontent.com/67585967/197484388-7b31f7c2-eb53-4bd3-b65f-190a7178a8ea.png)
![100_display](https://user-images.githubusercontent.com/67585967/197484417-afd1d1c5-5ea1-46ce-82c5-fa8d9b2df459.png)

Qemu with scale of 1.25

![125](https://user-images.githubusercontent.com/67585967/197484508-5f6612d2-89a9-4250-b572-a30c812400ac.png)
![125_display](https://user-images.githubusercontent.com/67585967/197484538-fde750aa-8982-4ac2-9d83-3861f6411a31.png)

[lite-xl](https://github.com/lite-xl/lite-xl) editor with scale of 1.00

![100](https://user-images.githubusercontent.com/67585967/197484751-8495efd5-a9a6-4285-9976-75e26812ec53.png)

lite-xl with scale of 1.25

![125](https://user-images.githubusercontent.com/67585967/197484799-739ffdd0-4d10-42ac-a3a6-e8fec88d521e.png)

Uncompressed images since the difference might not be very noticeable

[images.tar.gz](https://github.com/libsdl-org/SDL/files/9850163/images.tar.gz)

**Comment by sulix** [comment]
I don't think the Wayland protocol has standardised support for fractional scaling yet, so it's expected that this doesn't work.

You may have some luck with fullscreen modes, as we use the viewporter extension to implement this for mode emulation, if the window is created with ``SDL_WINDOW_ALLOW_HIGHDPI``. But for windowed mode, I think this is still a work-in-progress for Wayland generally.

**Comment by flibitijibibo** [comment]
Probably the most relevant task is #5906

**Comment by Kontrabant** [comment]
SDL actually does give you a properly sized backbuffer that is as close to 1:1 mapping as possible for fractionally scaled desktops.  The blurriness happens because Qemu doesn't set the DPI-aware flag when creating the window.

https://github.com/qemu/qemu/blob/70e975203f366f2f30daaeb714bb852562b7b72f/ui/sdl2.c#L74

**Comment by git-bruh** [comment]
Thanks for pointing that out @Kontrabant, with that flag Qemu's display is sharp but it's "boxed" and there's an offset between mouse clicks and where it actually clicks. I guess qemu needs some more work to adapt to this flag:

![2022-10-26T13:43:55,127549525+05:30](https://user-images.githubusercontent.com/67585967/197972125-9a97c586-f995-420b-bf5a-f638c5c10994.png)


lite-xl works fine (it already had the HIGHDPI flag enabled but there was a build option to toggle the SDL renderer that I forgot about)

**Comment by dos1** [comment]
Nothing to be done here. Applications that don't handle HiDPI are going to be blurry on non-1.0 scales and SDL can't fix it. Report it to the apps you're seeing blurriness with.
