### ISSUE TITLE
The problem of SDL_GL_SetSwapInterval(int)

### ISSUE THREAD

**Issue by Wudr-1995** [libsdl-org/SDL#6439]
The program was compiled to run in the computer with several RTX 3090s. 
**The function SDL_GL_SetSwapInterval(int) always returns -1 with different inputs (0, 1 or -1).**
I didn't find any solution of this issue.
If any one has any idea about this, please inform me.

**Comment by icculus** [comment]
Also, it might give a generic error, but can you tell us was SDL_GetError() reports right after this returns -1?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
