### ISSUE TITLE
SDL doesn't respond to window size changes with VirtualGL

### ISSUE THREAD

**Issue by smoogipoo** [libsdl-org/SDL#6447]
When running programs with VirtualGL (`vglrun`), SDL doesn't seem to respond to window size changes and leaves the window's framebuffer in a broken state.

To test this, I've taken the [glxgears implementation](https://github.com/Lyude/mesa-utils/blob/master/srcs/glx/glxgears.c) which uses raw X11 window events and works correctly with VGL, and re-implemented it under SDL2. That implementation can be found here: https://gist.github.com/smoogipoo/cde4fa3ca870726f07b384bcc3555f21

Here's the results:

<table>
<th>impl</th><th>without VGL</th><th>with VGL</th>
<tr>
<td>
X11
</td>
<td>

https://user-images.githubusercontent.com/1329837/197932707-4315ac2c-76d5-4232-beb1-2e91273efbc3.mp4

</td>
<td>

https://user-images.githubusercontent.com/1329837/197932721-5350cddb-e23d-48a9-8481-b0bbc2a2fd68.mp4

</td>
</tr>
<tr>
<td>
SDL2
</td>
<td>

https://user-images.githubusercontent.com/1329837/197932746-04033880-a47c-4a1e-9fda-a534c9b0108e.mp4

</td>
<td>

https://user-images.githubusercontent.com/1329837/197932758-9b9b3a6e-39a1-48b1-a021-fc423815211a.mp4

</td>
</tr>
</table>

**Comment by icculus** [comment]
(Unlikely this will make 2.26.0, but we'll see how the week goes.)

**Comment by icculus** [comment]
I don't think we're going to have time to look at this in the near future, so I'm taking it out of any milestone, but we will accept a patch to resolve this problem!

**Comment by smoogipoo** [comment]
That's fine, this isn't a really important issue for me anyway :)
