### ISSUE TITLE
kAudioObjectPropertyElementMaster is depreciated (MacOS)

### ISSUE THREAD

**Issue by essial** [libsdl-org/SDL#6449]
There are at least 12 places in audio/coreaudio that uses the following for MacOS:
kAudioObjectPropertyElementMaster

This value is depreciated and is a synonym for:
kAudioObjectPropertyElementMain

It should be enough to replace one for the other and eliminate at least 1/3 of the build warnings for SDL2 on MacOS.

**Comment by icculus** [comment]
Gonna try to sneak this into 2.26.0, but we might run out of time.
