### ISSUE TITLE
Write more robust documentation for Emscripten target

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6453]
> Added a note, but this makes me want to write more comprehensive documentation for the platform, which I will do sometime after 2.26.0 ships, I hope.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/6385#issuecomment-1295417201_

**Comment by CaptainKraft** [comment]
Is there any progress on this? I'm just starting a search now for documentation on SDL + Emscripten

**Comment by icculus** [comment]
Not yet, but I can scratch together something basic tonight, I think.

**Comment by icculus** [comment]
This is in revision control now! If you get stuck please let us know!
