### ISSUE TITLE
Wayland reports loss of focus on mouse button release when in relative mouse mode

### ISSUE THREAD

**Issue by GoGoOtaku** [libsdl-org/SDL#6460]
If mouse mode set to relative mouse mode (in my case to look around in an FPS game) and the mouse gets moved between mouse down and mouse up the window sometimes looses focus for just a fraction of a second. It is however long enough for both `SDL_GetMouseFocus` to report a `nullptr` (polling at 60FPS) and `SDL_WINDOWEVENT_LEAVE` and `SDL_WINDOWEVENT_ENTER` to fire. In the game this causes the menu to open (which is wanted behavior on actual focus loss).

This happens only with the Wayland video driver. Using x11 (through XWayland, as I am still using Wayland under the hood) or Wine does not cause this behavior and the code has been working for a while under Windows.

Having skimmed through the code and recent changes this might be a regression from [this commit](https://github.com/libsdl-org/SDL/commit/f600364b8a575e03f140ab18eeabaeffb8f0b392)?
I haven't had the time to properly investigate further and frankly I don't know enough about Wayland itself to make a proper call on how to capture the mouse. This might be something to look into tho.

System Info:
SDL: 2.24.0
OS: Linux (5.19.8-gentoo-x86_64)
Window Manager: Sway

PS: I don't have a short code sample but I can link to the [game](https://github.com/ArnoAnsems/CatacombGL).
Note that in the current code the `SDL_GetMouseFocus` gets polled instead of using the window events. I have tested the code using window events instead and the same problem occurs. Due to this not having a noticeable performance impact it is not uploaded into this version. The code for the basic window is under [`src/System/CatacombGL.cpp`](https://github.com/ArnoAnsems/CatacombGL/blob/master/src/System/CatacombGL.cpp)
I do not exclude the possibility that it's a mistake on the part of my game code neither can I fully exclude my window manager but after a while of testing and looking into the code of all three I am pretty sure it is in SDL.

**Comment by flibitijibibo** [comment]
@icculus, any ideas?

**Comment by GoGoOtaku** [comment]
Thank you for the quick response and fix :+1:
