### ISSUE TITLE
Hardware mouse seems to be not properly initialized on iOS

### ISSUE THREAD

**Issue by deveee** [libsdl-org/SDL#6466]
It may be hard to catch but it seems that sometimes mouse is not properly initialized. I mean, mouse clicks work fine, but on mouse move SDL constantly receives from system one incorrect position that doesn't change. Note that it's system that already sends incorrect values, not SDL. What helps is to minimize window and show it again. Or just close application and reopen it again, and have a hope that it will work properly next time.

I tried it on iPad Pro with iOS 15.6.1. UIApplicationSupportsIndirectInputEvents is set and relative mouse mode works fine.

**Comment by slouken** [comment]
Have you been able to track down what's causing this? I haven't seen the issue here.

**Comment by deveee** [comment]
Seems that it's caused by a window that is used for extracting assets before actual SDL window is created.

When I use window.hidden = YES for that window before SDL initialization, then mouse seems to work fine every time. Or maybe it's just a case.

I'm not sure if you want somehow workaround it in SDL or just assume it's not SDL bug.

**Comment by deveee** [comment]
SDL has something similar in destroy window, it may be related
https://github.com/libsdl-org/SDL/blob/main/src/video/uikit/SDL_uikitwindow.m#L366

**Comment by deveee** [comment]
Yes and as far as I tested it seems to work.
