### ISSUE TITLE
IME Composition window and `SDL_TEXTEDITING`

### ISSUE THREAD

**Issue by vkedwardli** [libsdl-org/SDL#6469]
With @zreedy's https://github.com/libsdl-org/SDL/pull/4707 implementation, I can display the native IME Candidate window, and set it's location with `SDL_SetTextInputRect`

<img width="312" alt="image" src="https://user-images.githubusercontent.com/602245/199105784-a09deffc-4e50-4bde-a98e-1dd53aa0499a.png">

But how can I also display the native IME Composition window?
<img width="277" alt="image" src="https://user-images.githubusercontent.com/602245/199105702-5c410fe6-5328-4576-8d1f-2b3de4de00a2.png">

I noticed that I can get the composition char from the `SDL_TEXTEDITING` event, am I responsible to draw the composition and is it the only way?

Thank you

**Comment by slouken** [comment]
Yes, you are responsible for drawing the composition text.

**Comment by slouken** [comment]
Actually, it turns out there is a way to have Windows draw this for you. I'm working on this now.

**Comment by slouken** [comment]
This is fixed in https://github.com/libsdl-org/SDL/commit/4c7db129df3f6d56a809826a6fa76375dca422f6, and is the default behavior.
