### ISSUE TITLE
Can't build in Cmake+clang

### ISSUE THREAD

**Issue by Cn-mjt44** [libsdl-org/SDL#6470]
I try to update sdl 2.0.15 to 2.24.1, after that It can't build with Clang anymore.
How to fix that?
This project is using Cmake and Clang.
![image](https://user-images.githubusercontent.com/50526629/199176170-1b364784-fd37-4951-be5d-c8f366d6679e.png)

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/pull/6475 addresses this
