### ISSUE TITLE
Win10 x64 mingw64 add -m32 compile error

### ISSUE THREAD

**Issue by 505799690** [libsdl-org/SDL#6480]
Win10 Cmake Mingw64 uses Add_Subdirectory (VENDORD/SDL Exclude_from_all) , add -m32 compile error

[build] [ 29%] Linking C shared library SDL2d.dll
[build] D:/PROGRA~1/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: i386:x86-64 architecture of input file `CMakeFiles\SDL2.dir/objects.a(version.rc.obj)' is incompatible with i386 output
[build] collect2.exe: error: ld returned 1 exit status

**Comment by 505799690** [comment]
64bit normal

**Comment by madebr** [comment]
Where did you get your multilib MinGW toolchain?
https://www.mingw-w64.org/downloads/ only lists toolchains that build either i686 or x86_64.
(multilib means one gcc executable is able to build both 32- and 64-bit executables)

How did you configure your cmake project?
Ideally, it should be done using:
```
cmake .. -DCMAKE_C_COMPILER="path/to/gcc.exe" -DCMAKE_CXX_COMPILER="path/to/g++.exe" -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM="path/to/mingw32-make.exe" -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"
```

**Comment by 505799690** [comment]
> Where did you get your multilib MinGW toolchain? https://www.mingw-w64.org/downloads/ only lists toolchains that build either i686 or x86_64. (multilib means one gcc executable is able to build both 32- and 64-bit executables)
> 
> How did you configure your cmake project? Ideally, it should be done using:
> 
> ```
> cmake .. -DCMAKE_C_COMPILER="path/to/gcc.exe" -DCMAKE_CXX_COMPILER="path/to/g++.exe" -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM="path/to/mingw32-make.exe" -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"
> ```

MinGW download [https://sourceforge.net/projects/mingw-w64/](https://gitee.com/link?target=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmingw-w64%2F)
x86_64-win32-sjlj
Is it a question of windres.exe?version.rc.obj

**Comment by 505799690** [comment]
Solved, 32 -bit CMAKE, 32 -bit compiler, 64 -bit CMAKE cannot compile

**Comment by madebr** [comment]
The [toolchains at mingw-w64](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/) are not multilib.
You can only build 32-bit Windows binaries with the i686-* toolchains, and 64-bit WIndows binaries with the x86-64-* toolchains.

The bitness of cmake should not matter.
