### ISSUE TITLE
build broken on OpenBSD (and likely other non-linux *nix systems)

### ISSUE THREAD

**Issue by stspdotname** [libsdl-org/SDL#6484]
Since this commit the main branch of SDL no longer compiles on OpenBSD:

  https://github.com/libsdl-org/SDL/commit/71fb91f7e43c5f046a037bf5ca59214d93fe2d51

.../src/core/linux/SDL_evdev_capabilities.h:28:10: fatal error: 'linux/input.h' file not found

There will still need to be a guard of some kind around the inclusion of linux/input.h, as long as the file src/core/linux/SDL_evdev_capabilities.c remains on the list of core *nix files in configure.ac.

**Comment by cgutman** [comment]
Should OpenBSD even be building evdev stuff?

**Comment by stspdotname** [comment]
I don't know.

The file is being built on any *nix because it is listed here: https://github.com/libsdl-org/SDL/blob/main/configure.ac#L4003

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/9f8b68a2785563031473011379878bb63ed5d3a3
