### ISSUE TITLE
Request's SDL2.dll but doesnt work with it.

### ISSUE THREAD

**Issue by BrotherNova** [libsdl-org/SDL#6487]
I followed a Youtube tutorial and the guy in the vid didn't have this issue and I don't know what to do.
![error sdl2](https://user-images.githubusercontent.com/117553676/200151494-3461e082-6ce1-4f79-a0c1-3f99919172a2.png)

**Comment by slouken** [comment]
Did you put SDL2.dll next to snake.exe?
https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-2.24.2-win32-x64.zip
https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-2.24.2-win32-x86.zip
