### ISSUE TITLE
Direct3D11 broken ARGB8888 textures

### ISSUE THREAD

**Issue by Panjaksli** [libsdl-org/SDL#6488]
Hello, when I use lock texture method for writing to texture of ARGB8888 or BGRA32 under DX9, it works as expected.
However when switching to DX11 renderer,  displayed texture looks like this.
![image](https://user-images.githubusercontent.com/82727531/200181152-2cf75237-8518-4da8-9ed2-dbbbed87644e.png)

**Comment by slouken** [comment]
It looks like you're not respecting the pitch of the locked texture. You generally can't do a memcpy of the whole thing, you need to copy row by row and advance each row by the pitch value.

**Comment by Panjaksli** [comment]
> It looks like you're not respecting the pitch of the locked texture. You generally can't do a memcpy of the whole thing, you need to copy row by row and advance each row by the pitch value.

Hmm, I'm writing to the pointer with array indexing in for loop, using the same pitch and everything. As I said, it works that way under DX9 normally.

**Comment by slouken** [comment]
Can you provide a minimal example, or at least your function to do the copy?

**Comment by Panjaksli** [comment]
```
#define SDL_MAIN_HANDLED
#include <SDL.h>
#define WIDTH 800
#define HEIGHT 600
#define uchar unsigned char
//red vertical stripes
void draw_bgr(uchar* bgr, int y, int x)
{
	bgr[0] = 0;
	bgr[1] = 0;
	bgr[2] = x % 255;
	bgr[3] = 255;
}
int main()
{
	int width = WIDTH, height = HEIGHT;
	SDL_Init(SDL_INIT_EVERYTHING);
#if 0
	/*this works*/
	SDL_SetHint(SDL_HINT_RENDER_DRIVER, "direct3d9");
	SDL_PixelFormatEnum Format = SDL_PIXELFORMAT_ARGB8888;
#else
	/*this doesn't*/
	SDL_SetHint(SDL_HINT_RENDER_DRIVER, "direct3d11");
	SDL_PixelFormatEnum Format = SDL_PIXELFORMAT_ARGB8888;
#endif
	SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "2");
	SDL_Window* window = SDL_CreateWindow("EG", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, width, height, SDL_WINDOW_SHOWN);
	SDL_SetWindowMinimumSize(window, 200, 200);
	SDL_Texture* frame;
	SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
	
	frame = SDL_CreateTexture(renderer, Format, SDL_TEXTUREACCESS_STREAMING, width, height);
	SDL_Event event;
	bool running = 1;
	while (running) {
		SDL_RenderClear(renderer);
		while (SDL_PollEvent(&event))
		{
			if (event.type == SDL_QUIT)
				running = false;
		}
		uchar* pixels;
		int pitch = 4 * width;
		SDL_LockTexture(frame, 0, (void**)&pixels, &pitch);

		for (int y = 0; y < height; y++)
			for (int x = 0; x < width; x++)
				draw_bgr(pixels+4*(y*width+x), y, x);

		SDL_UnlockTexture(frame);
		SDL_RenderCopy(renderer, frame, NULL, NULL);
		SDL_RenderPresent(renderer);
	}
	SDL_DestroyRenderer(renderer);
	SDL_DestroyWindow(window);
	SDL_Quit();
}
```

**Comment by slouken** [comment]
Yes, try replacing this:
`draw_bgr(pixels+4*(y*width+x), y, x);`
with this:
`draw_bgr(pixels+(y*pitch+x*4), y, x);`

**Comment by Panjaksli** [comment]
> 

AHA ! Thanks, for some reason I thought pitch was const and same with classic array layout. Sorry for wasting time.
