### ISSUE TITLE
SDL_RenderSetVSync exists, but SDL_RenderGetVSync not

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#6495]
There is a function `SDL_RenderSetVSync` to enable or disable vertical synchronization, but there is no function to read the current state of VSync usage. I suggest you to implement `SDL_RenderGetVSync` function, which will be used for this purpose and returns the current state as bool/int.

**Comment by slouken** [comment]
Good idea, let's add it for SDL 3.0

**Comment by 1bsyl** [comment]
done!
