### ISSUE TITLE
Not getting a high DPI window despite SDL_WINDOW_ALLOW_HIGHDPI

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#6497]
I'm for some reason not getting a High DPI window with GNOME 3 Wayland session and 125% UI scale (set in GNOME's "Display" settings in gnome-control-center/"Settings"). Even when I'm using `SDL_VIDEODRIVER=wayland` and `SDL_WINDOW_ALLOW_HIGHDPI` I'm not.

Steps to reproduce:

1. Make new file `sdl2dpibug.c`:

```
#include <assert.h>
#include <SDL2/SDL.h>
#include <stdio.h>


int main(int argc, const char **argv) {
    int r = SDL_Init(SDL_INIT_EVERYTHING);
    assert(r == 0);

    SDL_Window *window = SDL_CreateWindow("sdl dpi bug", 0, 0, 200, 200,
        SDL_WINDOW_RESIZABLE|SDL_WINDOW_OPENGL|
        SDL_WINDOW_ALLOW_HIGHDPI);
    assert(window != NULL);
    SDL_Renderer *renderer = SDL_CreateRenderer(
        window, -1, SDL_RENDERER_SOFTWARE);
    assert(renderer != NULL);

    int renderw, renderh;
    int windoww, windowh;
    int squaremotion_x = 0;
    int squaremotion_y = 0;
    int squareclick_x = 0;
    int squareclick_y = 0;
    double dpi_factor = 1;
    int updatedpi = 1;
    int notquit = 1;

    while (notquit) {
        if (updatedpi) {
            int result = SDL_GetRendererOutputSize(
                renderer, &renderw, &renderh
            );
            if (result == 0) {
                updatedpi = 0;
                SDL_GetWindowSize(window, &windoww, &windowh);
                dpi_factor = ((double)renderw)/((double)windoww);
                printf("renderw/windoww: %d, %d\n", renderw, windoww);
                printf("factor: %f\n", dpi_factor);
            }
        }

        SDL_Event e = {0};
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                notquit = 0;
                break;
            } else if (e.type == SDL_WINDOWEVENT) {
                if (e.window.event == SDL_WINDOWEVENT_CLOSE) {
                    notquit = 0;
                    break;
                } else if (e.window.event ==
                        SDL_WINDOWEVENT_SIZE_CHANGED) {
                    updatedpi = 1;
                }
            } else if (e.type == SDL_MOUSEMOTION) {
                squaremotion_x = e.motion.x * dpi_factor;
                squaremotion_y = e.motion.y * dpi_factor;
            } else if (e.type == SDL_MOUSEBUTTONUP) {
                squareclick_x = e.button.x * dpi_factor;
                squareclick_y = e.button.y * dpi_factor;
            }
        }
        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
        SDL_Rect r = {0};
        r.w = renderw;
        r.h = renderh;
        SDL_RenderFillRect(renderer, &r);
        SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
        r.x = squaremotion_x - 10 * dpi_factor;
        r.y = squaremotion_y - 10 * dpi_factor;
        r.w = 20 * dpi_factor;
        r.h = 20 * dpi_factor;
        SDL_RenderFillRect(renderer, &r);
        SDL_SetRenderDrawColor(renderer, 0, 0, 255, 255);
        r.x = squareclick_x - 10 * dpi_factor;
        r.y = squareclick_y - 10 * dpi_factor;
        r.w = 20 * dpi_factor;
        r.h = 20 * dpi_factor;
        SDL_RenderFillRect(renderer, &r);
        SDL_RenderPresent(renderer);
    }
    return 0;
}
```

2. Compile with: `gcc -g -o ./sdl2dpibug sdl2dpibug.c -lSDL2`

3. Run: `./sdl2dpibug` and observe terminal output

Expected behavior: terminal outputs something like `factor: 1.25...`

Actual behavior: terminal outputs `factor: 1.000000`
    
**Tested with SDL2 version:** SDL2-2.24.0-1.fc36

**Tested on OS:** Fedora Linux 36 x64 with GNOME 3 Wayland session

**Comment by flibitijibibo** [comment]
This currently matches the spec, it's actually the compositor giving us that number! #5906 will fix this for future Mutter releases.

**Comment by ell1e** [comment]
@flibitijibibo is there maybe a bigger problem then where some SDL2 apps may end up unintentionally using fractional scale anyway?

The thing is, another app of mine gets `1.263157894736842`. And since a recent SDL2 update it's quite broken:https://bugzilla.redhat.com/show_bug.cgi?id=2137027 (The app code was unchanged and motion events are unaffected, so this seems to be an SDL2 regression.)

I wanted to file a ticket for that and hence have been trying to reproduce it, but I can't even reliably get a fractional scale. In the complex app I get one, in my minimal example above I don't. Why would that be?

**Comment by Kontrabant** [comment]
Wayland is creating a high-DPI window here, the problem is that the SDL software renderer is not DPI-aware. It uses the window size instead of the drawable backbuffer size when creating it's canvas and that's what `SDL_GetRendererOutputSize()` returns.

If you set your example to `SDL_RENDERER_ACCELERATED` to use the GL backend or use a function like `SDL_GL_GetDrawableSize()/SDL_GetWindowSizeInPixels()` to query the backbuffer size, it returns a 250x250 backbuffer for the 200x200 window.

**Comment by ell1e** [comment]
Ah, I see, thanks so much for finding that out! While that sounds like a limitation that might be worth fixing, I'll close the ticket for now since it's not a bug like I thought.
