### ISSUE TITLE
Is it mandatory for different SDL2 apps to need different values?

### ISSUE THREAD

**Issue by superfury** [libsdl-org/SDL#6499]
So I've made a sort of framework (actually a layer of common functionality shared with all my apps using SDL/SDL2) based on SDL/SDL2 (compatible with both). Then I followed the basic steps for creating the Android project (originally this was on Ant, but eventually linked most files using symbolic links to the Android Studio folders, exactly the reversed way it's handled on the SDL repository (the app/src/main (java, jni res and AndroidManifest.xml) folders and files in the Android Studio of my apps are linked to the Ant folder files instead of the other way around to provide compatiblity with both build methods (I started out on Ant, then added Android Studio support later when it became mandatory)).

Now I notice that according to the SDL2 documentation ( https://github.com/libsdl-org/SDL/blob/main/docs/README-android.md ), when giving each application it's own name (which is clearly seperated between projects), but also requires to extend the SDL2 activity class for each project.

Now, the SDL2Activity class is the same for each project using the framework. Can I just create the same activity java class file and name for all the projects (say commonSDL2Activity) without the apps colliding with each other when ran at the same time on Android?

**Comment by icculus** [comment]
(Should this be closed, as answered?)

**Comment by superfury** [comment]
So if I understand correctly, that file (starting with package ...; etc.) is required to be different for each project using SDL (because of that package row being different)?

**Comment by 1bsyl** [comment]
@superfury 
Yes, that's what I meant. And yes, same also for the AndroidManifest.xml.
In fact: AndroidManifest defines what is going to be your package name / where to find the activity. The .java is exactly your java implementation.
And the package name, is also what you tell to google play, which requires it to "be globally unique in Google Play".

Let's wait for superfury to close the issue

**Comment by superfury** [comment]
OK. So it can't be duplicated accross projects. Nice to know.
Although that means that whenever SDL2 has changed stuff in AndroidManifest.xml, I'll need to manually change said files in all projects to reflect what SDL2's release version has in it's AndroidManifest.xml file (excluding custom things of course that depend on the app of course). Too bad that you can't just #include such a thing into the xml file, removing the duplicated work across when SDL2 newer versions requires new stuff to work properly.

**Comment by superfury** [comment]
Closed.

**Comment by 1bsyl** [comment]
@superfury I may also be wrong :) because I set up this a while ago.
try to upload a app to google play with tweaking the java package name and see if it passes
