### ISSUE TITLE
windows get incorrect flags when use SDL_CreateWindowFrom on win32 platform.

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#6500]
I use qt and SDL_CreateWindowFrom to create window from an existing window handle,  found that window gets SDL_WINDOW_BORDERLESS flags when win32 windows has WS_POPUP style.  Window has SDL_WINDOW_BORDERLESS  will return 0 when process WM_NCCALCSIZE msg instead of calling original WNDProc. which will lead to mouse motion event report wrong mouse positions.

**Comment by slouken** [comment]
Do you have a minimal repro case that we can use to debug this?

**Comment by sandsc** [comment]
Sorry for the late reply, found that this issue has been fixed on sdl3 latest commit.

**Comment by sandsc** [comment]
Sorry for the late reply, found that this issue has been fixed on sdl3 latest commit.
