### ISSUE TITLE
Question: How much effort is needed to get the Mac OS X 10.4 and PPC supported?

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#6506]
Why I asking this? I want to perform certain debug of my stuff using PowerPC processor with a big endinan byte order. However, on my hardware (PPC G4, Radeon 9200), Debian 8 has issues to run the accelerated graphics (OpenGL applications draw very very slow, around 1 FPS, but works) because "Radeon 9200 is too old for 'XXX' system" (at the same time, on my another old computer, it has the same Radeon 9200, but discrete, and runs Windows XP, the same game works flawless). I did attempt to run OpenBSD, but it sucks even more... And, there is only way to have full support of graphics, is Mac OS X Tiger 10.4. Anyway, I had upgraded my environment using Tigerbrew (fork of Homebrew to backport it into 10.4).

Environment I got:
- CMake 3.6
- Ninja 1.16
- GCC 7.3
- etc.

However, I understand that several system APIs lacks certain features, and I should tune out these codes. Also, Objective-C code fails to build if code files contains the `@autoreleasepool` keyword, but builds fine if I remove this keyword.

**Comment by Wohlstand** [comment]
EDIT: Anyway: https://stackoverflow.com/questions/14677049/what-is-autoreleasepool
> If you remove the autorelease pool, your objects will start leaking

**Comment by sezero** [comment]
I don't think it would be possible to make current or recent SDL2 to work under ppc macs. There was an effort to use SDL-2.0.3 under ppc macs named [pather_sdl2]() ([my fork](https://github.com/sezero/panther_sdl2)) -- your mileage may vary..

**Comment by vkedwardli** [comment]
`@autoreleasepool{ /* your code */ }` is the shorthand syntax of
```objc
NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];

/* your code */

[pool drain];
```

**Comment by Wohlstand** [comment]
> `@autoreleasepool{ /* your code */ }` is the shorthand syntax of
> ```objc
> NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
> 
> /* your code */
> 
> [pool drain];
> ```

Thanks for the hint, I'll try some.

**Comment by Wohlstand** [comment]
> I don't think it would be possible to make current or recent SDL2 to work under ppc macs. There was an effort to use SDL-2.0.3 under ppc macs named [pather_sdl2](https://github.com/blackberryhurricane/panther_sdl2) ([my fork](https://github.com/sezero/panther_sdl2)) -- your mileage may vary..

Ye, I saw that build, however, it's too old (I need at least 2.0.8)

**Comment by 1bsyl** [comment]
@Wohlstand you can use qemu to try latest SDL for big endian

**Comment by Wohlstand** [comment]
> @Wohlstand you can use qemu to try latest SDL for big endian

Already, it works extremely slow on my end due to my processor, and recently I got a used Mac Mini G4 for a cheap price, so, I started to experiment on it.

**Comment by 1bsyl** [comment]
@Wohlstand yes this is slow indeed. .. but if it's only for debugging some little endian issue, I would reduce this to some minimal test cases ... but you know better your app and your issues

**Comment by Wohlstand** [comment]
> @Wohlstand yes this is slow indeed. .. but if it's only for debugging some little endian issue, I would reduce this to some minimal test cases ... but you know better your app and your issues

I want to debug the gameplay (that's why I need the GPU to be working) and verify that the script engine works just fine. That's an unusual script engine: in the past, it was a hack tool intended to be DLL-Injected into the original game (made for Windows and it was closed source until 2nd of February, 2020), and by its scripts, it allows one to write random bytes of any available data field. I wrote the memory emulator (mapper) which makes scripts think they work with the original game binary and X86 memory (Mainly, to support backward compatibility to these hacky scripts and make old levels work on other platforms). This already works on ARM and PPC64LE, but, both architectures are a little endian. And I looked for a big-endian-based machine to debug the stuff. In addition, I also got the Nintendo Wii where I can produce the homebrew game (but, my custom SDL2 port isn't finished yet, it supports audio, partially joysticks, threads, mutexes, and timers, but no graphics yet).

**Comment by icculus** [comment]
Yeah, there's just a lot of problems on trying to get this working...the autorelease keyword, ARC support in general, the lack of tools or SDKs, and just newer APIs that we're coming to rely on.

We will take small patches to improve compatibility, but if they are intrusive at all, we won't at this point, and honestly...most would be pretty intrusive.

**Comment by Wohlstand** [comment]
Okay, I just taking a look at SDL2 2.0.2's code to compare modules which fail to build (for example, recently I managed to tweak the CoreAudio module). For my needs, I'll take the simplified backport of the stuff and put it on my separate branch (I'll submit it to the Tigerbrew set if I get successful to tweak it). Ye, at mainstream SDL2, let's keep the stuff support as it supports. Such legacy platforms generally have a narrow range of uses: just for fun, sports interest, or research.

**Comment by Wohlstand** [comment]
Anyway, I would be very happy if I just get a Linux distro to support the GPU properly. At my end, it didn't work right and lagged as heck (at Mac OS Tiger, the graphics work just quickly, that's a confirmation that Radeon 9200 isn't a mess, and it has abilities to produce a good-quality render).

**Comment by Wohlstand** [comment]
P.S. As a workaround, I could allow using X11 API here and disable the Cocoa.

**Comment by Wohlstand** [comment]
Okay, with few tweaks, I got modern SDL2 work as X11 application!

![20221112_175856.jpg](https://user-images.githubusercontent.com/6751442/201480403-58503c61-0abe-47fb-8f86-ea9514f8c76b.jpg)

![20221112_175937.jpg](https://user-images.githubusercontent.com/6751442/201480407-20a5ce6d-90cc-46ae-a17b-a8738df7805b.jpg)

However, there are things I met:
- if call glXMakeContext() with "None" context, it causes a dead lock on XLockWindow(). Avoiding to call these methods "fixes" the issue, BUT, I am not sure is this correct solution, or I should do something different?
- XRandr header is incompatible, so, I disabled this module
- XScreenSaver also incompatible, it misses one call, so, I disabled it
- I found an answer on a question left at "sdlchecks.cmake" at line 449: this is disabled, because there are all library name macros at SDL_x11dyn.c are null, and therefore it won't load anything at all. To make this case work on macOS, need to define these macros with respective library names.

**Comment by Wohlstand** [comment]
Just for your info: There are changes I made over the mainstream SDL2 to get it to work on the Mac OS X Tiger as an X11 application:
https://github.com/libsdl-org/SDL/compare/main...Wohlstand:SDL:mac-tiger

- I copied the CoreAudio module from SDL 2.0.2 and tweaked it to bring it into the updated environment. I made the "coretiger" module to keep the mainstream "coreaudio" untouched.
- I made a few tweaks to enable the X11 module on macOS
- I copied file, filesystem, locale, and misc modules and made a few tweaks to get them buildable with GCC-7
- I made one fix at the SDL_unixtimer.c to fix the build (No idea why it wasn't static, but it caused an error during the build process when it's a non-static thing)
- I made a few tweaks at SDL_x11opengl.c to fix the startup on X11 (making libGL.1.dylib adequately recognised, "fixing" the deadlock on an attempt to call the glXMakeCurrent() with the "None" context).
- Made CMake-side tweaks to detect Mac OS X 10.4 and tweak modules. I disabled Joystick, HIDAPI, and Haptic for now. Maybe it's possible to make some via libusb (it can be installed via Tigerbrew as the `brew install libusb`)?

**Comment by Wohlstand** [comment]
And... I got my game work on my Power Mac using the newest state of SDL2 with my own tweaks:
![Picture 9](https://user-images.githubusercontent.com/6751442/201503956-d1ad9e36-cc3d-405c-8b66-efeb86a7dc08.png)

However, there is a limitation of OpenGL here, it doesn't support the framebuffer object extension, and therefore it can't render into the texture (I used it to draw my in-game scene and smoothly scale it depending on the physical resolution of the screen).
