### ISSUE TITLE
Latest update broke a lot of wayland games

### ISSUE THREAD

**Issue by Korothi** [libsdl-org/SDL#6511]
Example: OpenHV unable to launch in wayland mode or Unity games.
For openHV solution was to put SDL2.so from lib64 in appimage.

**Comment by Kontrabant** [comment]
`SDL init failed: wayland not available`

OpenHV bundles an old version of SDL without Wayland support in the appimage.  It works fine with the Wayland backend if you override it with `SDL_DYNAMIC_API` pointed to an up-to-date system library with Wayland support.

https://github.com/OpenRA/OpenRA/issues/20014

Not an SDL bug.

**Comment by flibitijibibo** [comment]
Yeah, sounds like a conflict between global environment variables and statically bundled SDL binaries - not much we can do about this except recommend the use of `SDL_VIDEODRIVER=wayland,x11` which does admittedly not work for the much older SDL2 releases.

**Comment by Mailaender** [comment]
Is this https://github.com/pchote/SDL2-binaries/pull/2 enough to enable wayland support?
