### ISSUE TITLE
wl_pointer interface error when using SDL in Snap

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#6516]
It looks like 057086e389a78c600c0862ea331aa9b834ffbb43 (or 76308483fa2d057ed18bcb302c84bba650ab532f) introduced a bug where SDL can negotiate a `wl_pointer` interface version that the runtime `libwayland-client` version may not understand.

After updating SDL, we hit a situation in https://github.com/maxiberta/moonlight-snap/issues/18 where a Core22-based Snap running on Ubuntu 22.10 is negotiating `wl_pointer` v8 with the newer version of Mutter on the host, however the Core22 Wayland libraries (from Ubuntu 22.04) don't understand `wl_pointer` v8. The result is that scrolling the mouse wheel triggers a `interface 'wl_pointer' has no event 9` message and crashes the Snap. I imagine a similar issue could happen with Flatpaks or AppImages too.

I'm not sure how you're supposed to handle this kind of client/server protocol mismatch, so tagging @Kontrabant for assistance.

**Comment by Kontrabant** [comment]
Yep. this sounds like the compositor advertising wl_seat (and subsequently wl_pointer) v8, SDL reporting that it supports v8 (it uses whatever version is advertised by the compositor up to 8) and the bundled libwayland being too old to support it.

There doesn't seem to be a way to detect the libwayland version at runtime, so what we can do is clamp the wl_seat max version to 5 unless the version of libwayland the headers come from is 1.21.0 or higher.  It's not the perfect solution as it is still possible to mix a version of SDL built against newer headers with older libraries, but as long as you are building all of the bundled libraries against each other, it should be fine.
