### ISSUE TITLE
PSP issues

### ISSUE THREAD

**Issue by Seng-Jik** [libsdl-org/SDL#6528]
1. Screen is not centered when window width is less than 480, framebuffer will be shown on the left-top corner on the screen.
2. When I render a texture with alpha channel and set blend state to `SDL_BLENDMODE_BLEND`, it just normalize all alpha to 0 or 255.

**Comment by sharkwouter** [comment]
Thanks for reporting.

About 1, is this addressed in ports to other systems? I'm not 100% sure if this is a bug or not, but changing it would probably make sense. 

2 surprises me. I use this code in one of my projects to set the blend mode, which does work:
```c++
SDL_SetRenderDrawBlendMode(this->renderer, SDL_BLENDMODE_BLEND);
```
Can you test if that is the case for you too? What code do you use to set the blend mode?

**Comment by Seng-Jik** [comment]
> Thanks for reporting.
> 
> About 1, is this addressed in ports to other systems? I'm not 100% sure if this is a bug or not, but changing it would probably make sense.
> 
> 2 surprises me. I use this code in one of my projects to set the blend mode, which does work:
> 
> ```c++
> SDL_SetRenderDrawBlendMode(this->renderer, SDL_BLENDMODE_BLEND);
> ```
> 
> Can you test if that is the case for you too? What code do you use to set the blend mode?


I mean when I set logic screen size less than 480, it happens.

![image](https://user-images.githubusercontent.com/11296891/202171625-1a7a72f9-2ec2-4c7e-a6fa-4a9cdb6d588a.png)

left: PPSSPP (and real PSP has same behaviour)
right: Windows 11

After init window and before render first frame, I has called this in `main()` function:
![image](https://user-images.githubusercontent.com/11296891/202172213-1d3cd978-15b1-427c-a68d-22e03fed8dc1.png)

imagesize_w = 363
imagesize_h = 272

**Comment by Seng-Jik** [comment]
About 2:

on PPSSPP and PSP GO:
![image](https://user-images.githubusercontent.com/11296891/202173118-2a97f5b8-c6e3-4f4d-bffc-32bfd1a0468d.png)

on Windows 11:
![image](https://user-images.githubusercontent.com/11296891/202173300-3d5d1281-4337-4f3c-a06f-15c2a88f3dce.png)

 This effect is defined by a single channel image `void *mask`:
![image](https://user-images.githubusercontent.com/11296891/202173685-2d7bb576-322a-4af4-ac03-fb77df17c021.png)

![image](https://user-images.githubusercontent.com/11296891/202174533-87d4f5ad-a997-45b6-98a8-a79852e90b6a.png)

**Comment by sharkwouter** [comment]
Ah, I see. I think the problem here is not the blending, but updating the texture. The streaming texture test has also never really worked for the PSP. I've tried to figure this out, but I've not found a solution for it yet. That's this code: https://github.com/libsdl-org/SDL/blob/main/test/teststreaming.c

**Comment by sharkwouter** [comment]
@Seng-Jik glad you found a solution. How did you end up solving it?
