### ISSUE TITLE
Emscripten CMake tests fail and are disabled on CI

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#6529]
Running the SDL tests on CI fail.
This is probably because the tests don't expect to be run inside node and not in a browser environment.

Summarized, the errors are:
- ERROR: Couldn't create thread: Threads are not supported on this platform
- ERROR: Couldn't initialize SDL: No audio context available.
-
    ````
    ReferenceError: screen is not defined
    at _emscripten_get_screen_size (/home/runner/work/SDL/SDL/build/test/testlocale.js:1:114863)
    ````
-
     ```
    ReferenceError: navigator is not defined
    at battery (/home/runner/work/SDL/SDL/build/test/testpower.js:1:113007)
    at _emscripten_get_battery_status (/home/runner/work/SDL/SDL/build/test/testpower.js:1:113137)
    at sd (<anonymous>:wasm-function[812]:0x5ecf8)
    ```

Complete test log can be found at https://gist.github.com/madebr/91972a7458bc9317e3f3364d3caaf9ee

**Comment by icculus** [comment]
Yeah, this doesn't, and won't ever, work in node. It 100% needs a browser environment.

Can we just disable running the tests on Emscripten builds?

**Comment by slouken** [comment]
Yes, @madebr has already done that, I believe.

**Comment by madebr** [comment]
I did disable running *all* tests on ci.
Is it okay to blacklist these "demanding" tests and just run the others?

Using the WebDriver standard, running all tests might be possible.

**Comment by icculus** [comment]
I don't think there's much value in testing this under node at all, and tests will break as we make changes to SDL and suddenly need a browser component elsewhere, but if you want to do the work, that's fine with me.

**Comment by madebr** [comment]
Thanks, so I suppose using a webdriver is the way to go.
