### ISSUE TITLE
PS2_JoystickUpdate:  some invalid condition

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#6533]
Seems there is some invalid condition here:

https://github.com/libsdl-org/SDL/blob/main/src/joystick/ps2/SDL_sysjoystick.c#L278

`
     if (state != PAD_STATE_DISCONN || state != PAD_STATE_EXECCMD || state != PAD_STATE_ERROR) {
`

written by @fjtrujy  ?

**Comment by fjtrujy** [comment]
Now that I’m again taking a look at the code, probably these `||` need to be `&&` right?

**Comment by 1bsyl** [comment]
probably, but you double-check :) I automatically find it using 'spatch / coccinelle' tool ! (I'm not using the PS2)

**Comment by 1bsyl** [comment]
Sounds to be the right fix! so closing.
