### ISSUE TITLE
SDL2+Lunarg MoltenVK crash.

### ISSUE THREAD

**Issue by fhoenig** [libsdl-org/SDL#6535]
Hope its okay to post this as a link. Really not sure if this issue fits here or there.

https://github.com/KhronosGroup/MoltenVK/issues/1774

**Comment by fhoenig** [comment]
Okay never mind. I had passed the NSWindow instead of the layer accidentally. 
However `SDL_SysWMinfo` probably should expose a pointer to contentView.layer.

**Comment by icculus** [comment]
I added a note to look at changing SDL_SysWMinfo, so that idea won't be forgotten.
