### ISSUE TITLE
AIX: use PAUDIO_WaitDevice

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#6537]
Probably at typo:
```
    impl->PlayDevice = PAUDIO_PlayDevice;
    impl->PlayDevice = PAUDIO_WaitDevice;
```
only renamed there for compilation
https://github.com/libsdl-org/SDL/commit/380e0693b1869fe31bb96eba37ca2b9d087003ad

**Comment by sezero** [comment]
This should probably go into release-2.24.x branch, too

**Comment by 1bsyl** [comment]
yes done !
