### ISSUE TITLE
[Android] SensorManager solicited as part of handleNativeState() before getting user consent

### ISSUE THREAD

**Issue by FlorianB-playdigious** [libsdl-org/SDL#6538]
A partner for which I develop an app using SDL pointed out that some methods considered as "sensitive" from a user privacy standpoint were called from app start without requesting user consent (and before the user can accept the user agreement as part of the app flow). 

The callstack ultimately points towards the use of SensorManager as part of SDLActivity.java. It is used in the static method handleNativeState(), which is called whenever the window focus changes, or the native thread pauses or resumes (meaning the activity is suspended or restored) and whenever the surface changes. So, quite often in the app lifecycle, including its startup.
It is also used in handlePause() and handleResume(), which doesn't change much.

Reading the code, the only use I can see of the accelerometer is in onSensorChanged() listener callback. It seems that the accelerometer is used to detect the actual device orientation. It seems to me this code is closer to a hack rather than intended behaviour. Does not mean the code is wrong, but it might have outlived its use. I have been asked to remove all usage of SensorManager before the user has approved the user agreement. It is actually easier to remove usage entirely rather than making it conditional to a user event, but in order to do so, I must be sure removing it will not cause bigger issues within the app.

I am currently using SDL based on commit 2970710b5dbdcf2f2fa674c29ada6e458e2c4149. Could SensorManager usage be safely removed or would it break SDL android support ? (i.e. is the usage of accelerometer legacy code or an actual feature, still needed today).

With the strengthening of user privacy controls nowadays, it might become a widespread review blocker for mobile apps in the future. Handling it more gracefully than removing it entirely would of course be in the best interest of everyone, while preserving the behaviour (my knowledge of SDL is far too small to consider doing it myself, sadly, hence the questions here).

**Comment by 1bsyl** [comment]
before the C SDL app starts, we enable sensors here: 
https://github.com/libsdl-org/SDL/blob/main/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L711
https://github.com/libsdl-org/SDL/blob/main/android-project/app/src/main/java/org/libsdl/app/SDLSurface.java#L301

If you only play with touchscreen. you can comment out the sensor manager, at those 3 places:
https://github.com/libsdl-org/SDL/blob/main/android-project/app/src/main/java/org/libsdl/app/SDLSurface.java#L34
https://github.com/libsdl-org/SDL/blob/main/android-project/app/src/main/java/org/libsdl/app/SDLSurface.java#L55
https://github.com/libsdl-org/SDL/blob/main/android-project/app/src/main/java/org/libsdl/app/SDLSurface.java#L301

but maybe some complex joystick requires it ... not sure ..

**Comment by FlorianB-playdigious** [comment]
I ended up isolating the code, based on a flavor. not perfect, but seems to work fine for this time.
