### ISSUE TITLE
macOS - 2.26.0 RC1 - VSync with multiple windows halves the frame rate of each window.

### ISSUE THREAD

**Issue by directmusic** [libsdl-org/SDL#6541]
Hey all,

This CVDisplayLink VSync patch works great with one window. I am seeing 120hz on my ProMotion MacBook Pro. However when I call SDL_RenderPresent() or SDL_GL_SwapWindow() on multiple windows in one loop the frame rate divides down for each subsequent window. Here is some simple example code.

```
void update_current_fps() {
    static float frame_counter = 0.0f;
    static float last_time = 0.0f;
    static int current_fps = 0;
    float current_time = SDL_GetTicks64() * 0.001f;
    ++frame_counter;
    if (current_time - last_time > 1.0f) {
        last_time = current_time;
        current_fps = (int)frame_counter;
        printf("Current FPS: %i\n", current_fps);
        frame_counter = 0;
    }
}

int main() {
    SDL_Window* win_1 = NULL;
    SDL_Window* win_2 = NULL;
    SDL_Renderer* renderer_1 = NULL;
    SDL_Renderer* renderer_2 = NULL;
    SDL_bool done = SDL_FALSE;
    SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl");
    SDL_Init(SDL_INIT_VIDEO);

    win_1 = SDL_CreateWindow("window 1", 100, 100, 400, 400, 0);
    renderer_1 = SDL_CreateRenderer(win_1, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

    win_2 = SDL_CreateWindow("window 2", 500, 100, 400, 400, 0);
    renderer_2 = SDL_CreateRenderer(win_2, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

    while (!done) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            switch (event.type) {
            case SDL_QUIT:
                done = SDL_TRUE;
                break;
            }
        }
        update_current_fps();

        SDL_RenderClear(renderer_1);
        SDL_RenderPresent(renderer_1);
        SDL_RenderClear(renderer_2);
        SDL_RenderPresent(renderer_2);
    }

    SDL_DestroyRenderer(renderer_1);
    SDL_DestroyWindow(win_1);
    SDL_DestroyRenderer(renderer_2);
    SDL_DestroyWindow(win_2);

    SDL_Quit();
}
```

I am definitely coming at this from a point of ignorance so my apologies if I am simply handling multiple windows incorrectly. Handling multiple windows in one draw loop works as expected on Windows and Linux.

**Comment by slouken** [comment]
This is pretty much what you'd expect to see when the present call waits for the next vblank interval. The first one waits for one vblank, the next one waits for the next, so the number of refreshes is divided by the number of times you're waiting. Unfortunately I don't know of a better way of doing this. Maybe there's something useful in online documentation about CVDisplayLink?

**Comment by slouken** [comment]
@icculus, I don't know if there's anything useful here, but here's an interesting commit from the wine folks:
https://www.winehq.org/pipermail/wine-patches/2015-November/144277.html

**Comment by icculus** [comment]
They have a more scalable solution: they use one displaylink per display, which will help with pathological cases like having 30 OpenGL windows open...so you don't end up with 30 high priority threads.

That being said, you are correct, the problem is that blocking on swapbuffers means you can't have two windows doing this or the framerate will halve.

Does SDL_GL_SetSwapInterval only affect the current context? If so, set one's swap interval to -1 and the other's to zero. The macOS compositor already prevents tearing, so you're just using this to trying and keep your framerate around 60 anyhow. Present the 0 interval window and then the -1 interval.

**Comment by directmusic** [comment]
@icculus This works beautifully here. Thank you.
