### ISSUE TITLE
Rendering sporadically silently fails on macOS

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#6542]
I am experiencing an issue, where rendering sporadically fails on macOS. All involved functions do not return an error. The problem is described in detail here: `https://discourse.libsdl.org/t/inexplainable-race-condition-in-sdl-renderer/39454`

Please note that this also happens if running everything in a single thread. So it is NOT a multi-threading issue.

I'm on a Mac mini M1 running macOS Ventura but the problem also occured on an older machine running an older version of macOS.

This issue might be related to #5588.

**Comment by slouken** [comment]
I don't know if this is the same problem, but I've seen rendering consistently fail on systems that have been up for a long time, and a reboot fixes the issue.

**Comment by andreasgrabher** [comment]
The issue is not related to uptime. It also occurs right after booting.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by andreasgrabher** [comment]
This problem does still exist (macOS Sonoma v14.1 and SDL2 v2.28.5).

**Comment by slouken** [comment]
Okay, I'm reopening this, please go ahead and add any additional information as you find it.
