### ISSUE TITLE
Incorrect Button and stick mappings for joystick in UWP

### ISSUE THREAD

**Issue by tunip3** [libsdl-org/SDL#6549]
bug: sticks and buttons are mapped incorrectly in a joystick with sdl winrt. Most notable issue is that axis x and y are swapped.
Operating System: Windows 10 and Xbox (unsure what firmware version)

**Comment by slouken** [comment]
Which joystick are you testing with?

**Comment by slouken** [comment]
I just tested with an Xbox One controller on Windows 11 and it worked fine here.

**Comment by tunip3** [comment]
> I just tested with an Xbox One controller on Windows 11 and it worked fine here.

I am testing with an xbox one s controller on windows 10 over bluetooth
I am testing with this example project.

When using the example in a desktop app the sticks function correctly. The arrow points up when the left stick is pushed up, down when its pushed down, left when its pushed left, right when its pushed right.

In a uwp project using SDL winrt. When the left stick is pushed up the arrow faces right, when pushed left it faces up, when pushed down it faces left and when pushed right it faces up.

I can upload the desktop and uwp visual studio projects if that will help you.

I am also using `SDL-release-2.24.2`

[19_gamepads_and_joysticks.zip](https://github.com/libsdl-org/SDL/files/10046785/19_gamepads_and_joysticks.zip)

The example is from this tutorial https://lazyfoo.net/tutorials/SDL/19_gamepads_and_joysticks/index.php

**Comment by slouken** [comment]
You shouldn't assume anything about events coming in through the joystick API. The axes may not be mapped the way you expect, buttons may be in entirely different orders, etc.

If you want a consistent API for controllers, you should use the game controller API. I was using testgamecontroller.c from the test directory and that works the way you'd expect on UWP.

**Comment by sabin1981** [comment]
This isn't "completed", you didn't help at all and instead just shut down the error. Can you please take another look rather than handwaving it away?

**Comment by tunip3** [comment]
> This isn't "completed", you didn't help at all and instead just shut down the error report. Can you please take another look rather than handwaving it away?

Whilst it is annoying that the same controller on UWP and desktop produce different Joystick mappings. This issue was initially created to see if there was a way to get them to be the same instead of just switching to the controller api as a way to improve SDL for UWP.

If you are not meant to assume standardized mappings for joysticks I can see why this is not an issue that needs fixing.

Thank you anyway, Slouken and much love for you work on SDL
