### ISSUE TITLE
compilation error when the video subsystem is cropped on the Windows

### ISSUE THREAD

**Issue by zxhxw** [libsdl-org/SDL#6562]
In some scenarios on the Windows platform, I only need the event subsystem, so I tried to trim the other subsystems in the CMake build framework using the following compilation options, but I found that the compilation error was reported.
```
-DSDL_VIDEO=OFF
```

```
SDL\SDL_dynapi.obj : error LNK2019: Unresolvable external symbols SDL_RegisterApp_REAL，This symbol is referenced in the initialize_jumptable function
SDL\SDL_dynapi.obj : error LNK2019: Unresolvable external symbols SDL_UnregisterApp_REAL，This symbol is referenced in the initialize_jumptable function
SDL\SDL_dynapi.obj : error LNK2019: Unresolvable external symbols SDL_Direct3D9GetAdapterIndex_REAL，This symbol is referenced in the initialize_jumptable function
SDL\SDL_dynapi.obj : error LNK2019: Unresolvable external symbols SDL_DXGIGetOutputInfo_REAL，This symbol is referenced in the initialize_jumptable function
SDL\SDL_dynapi.obj : error LNK2019: Unresolvable external symbols SDL_SetWindowsMessageHook_REAL，This symbol is referenced in the initialize_jumptable function
bin_x64\SDL2d.dll : fatal error LNK1120: 5 external commands that cannot be parsed
```

After querying related interfaces, I find that these functions are implemented in the `src\video\windows\SDL_windowsevents.c` file. However, these files have been tailored and will not participate in compilation. As a result, an error is reported in the link.

**Comment by madebr** [comment]
I can also reproduce this in current main and release-2.26.x with MinGW.
I'm getting a bonus missing symbol:
```
undefined reference to `SDL_HelperWindow'
```

**Comment by sezero** [comment]
About missing `SDL_HelperWindow`: `SDL_dinputjoystick.c` and `SDL_dinputhaptic.c`
rely on it. Job for @slouken, I guess.

About missing public functions: Is the following OK? (It adds to ifdef hell, but whatever.)
```diff
diff --git a/src/core/windows/SDL_windows.c b/src/core/windows/SDL_windows.c
index 4ec9dbb..12bcda9 100644
--- a/src/core/windows/SDL_windows.c
+++ b/src/core/windows/SDL_windows.c
@@ -343,4 +343,44 @@ WIN_RectToRECT(const SDL_Rect *sdlrect, RECT *winrect)
 
 #endif /* defined(__WIN32__) || defined(__WINRT__) || defined(__GDK__) */
 
+#if !defined(SDL_VIDEO_DRIVER_WINDOWS)
+#if defined(__WIN32__) || defined(__GDK__)
+int
+SDL_RegisterApp(const char *name, Uint32 style, void *hInst)
+{
+    (void) name;
+    (void) style;
+    (void) hInst;
+    return (0);
+}
+
+void
+SDL_UnregisterApp(void)
+{
+}
+
+void SDL_SetWindowsMessageHook(SDL_WindowsMessageHook callback, void *userdata)
+{
+}
+#endif
+
+#if defined(__WIN32__) || defined(__WINGDK__)
+int
+SDL_Direct3D9GetAdapterIndex(int displayIndex)
+{
+    (void) displayIndex;
+    return (0); /* D3DADAPTER_DEFAULT */
+}
+
+SDL_bool
+SDL_DXGIGetOutputInfo(int displayIndex, int *adapterIndex, int *outputIndex)
+{
+    (void) displayIndex;
+    if (adapterIndex) *adapterIndex = -1;
+    if (outputIndex) *outputIndex = -1;
+    return SDL_FALSE;
+}
+#endif
+#endif /* !defined(SDL_VIDEO_DRIVER_WINDOWS) */
+
 /* vi: set ts=4 sw=4 expandtab: */
```

**Comment by slouken** [comment]
I'd rather put those functions in the normal file they're defined, but in an `#else` block.

**Comment by sezero** [comment]
> I'd rather put those functions in the normal file they're defined, but in an `#else` block.

That requires build system changes to include `src/video/windows/*.c` regardless of video subsystem enablement (and if done so, then those sources will need proper guarding if they don't have it already.)

**Comment by zxhxw** [comment]
> I'd rather put those functions in the normal file they're defined, but in an `#else` block.

that will be good for me

**Comment by sezero** [comment]
@slouken: What is your decision?

**Comment by slouken** [comment]
I went with your approach, thanks!
