### ISSUE TITLE
libdrm minimum requirement too minimum(?)

### ISSUE THREAD

**Issue by jengelh** [libsdl-org/SDL#6565]
Commit 010d5fba9324173f74ec6630acb971c26fe34fe1 changed in configure.ac

```
-        PKG_CHECK_MODULES([LIBDRM], [libdrm >= 2.4.82], libdrm_avail=yes, libdrm_avail=no)
+        PKG_CHECK_MODULES([LIBDRM], [libdrm >= 1.4.82], libdrm_avail=yes, libdrm_avail=no)
```

However, I see no 1.4.82 tag in the libdrm git repo; if anything, it seems to have gone straight from 1.0.5 to 2.0 in 2005, and that "1.4.82" may be a typo accidentally introduced in SDL2.

**Comment by slouken** [comment]
I think that should be 2.4.74. We use cmake for libdrm detection in SDL3, and I don't think this is causing a problem in SDL2, so I'll go ahead and close this.

Thanks!
