### ISSUE TITLE
Create sdl2-compat

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6567]
Create sdl2-compat, a binary compatibility library that will run SDL2 applications on the SDL3 runtime, similar to what sdl12-compat has done for ancient SDL 1.2 games.

**Comment by flibitijibibo** [comment]
Obnoxious idea: Could we possibly generate the _entire_ library right now, with it just being a 1:1 dispatcher, and then incrementally implement compat functions as we break the ABI? Might give us slightly less to do over time, provided the initial generation of the library isn't too much work.

**Comment by slouken** [comment]
Yep, that's the plan.

**Comment by icculus** [comment]
I think it's worth noting that this plan relies on something we're already very good at: fighting against accidental ABI changes. We're already extremely well-trained to sniff these out, and I think this discipline is going to help a lot to make sure things slot directly into sdl2-compat when there are breaking changes in SDL3.

**Comment by icculus** [comment]
So we talked about this before, but I don't recall what the resolution was: do we want sdl2-compat to be in-tree, or should I do this in a separate project, like sdl12-compat is? I'm sort of inclined to say separate was the right way to go, although it will not feel like it at the start when every commit is a breaking change.

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/issues/6327#issuecomment-1276459707 suggests out-of-tree, which I think is reasonable.
I suppose all sdl2 tests will be copied as well?

**Comment by slouken** [comment]
Yes, a separate project with the SDL2 tests like we did with sdl12-compat seems like the right way to go.

**Comment by sezero** [comment]
What will happen to SDL2's dynapi? Is sdl2-compat supposed to support it and export an `SDL_DYNAPI_entry`?

**Comment by icculus** [comment]
It is supposed to, I just haven't implemented it yet.

**Comment by icculus** [comment]
This is under way, so I'm going to close this; sdl2-compat has its own bug tracker, of course.

**Comment by serfcity** [comment]
Is it possible to run SDL 1.2 application on SDL3 using sdl12-compat and sdl2-compat both?

**Comment by slouken** [comment]
Yes.
