### ISSUE TITLE
Separate the wiki

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6568]
Separate the wiki so we have documentation for both SDL2 and SDL3

**Comment by icculus** [comment]
Okay, we're up and running; this works like it always does, except now changes to the SDL branch headers go to an SDL2 subdirectory on the wiki. Main goes to the usual place.

Both branch's pages have warnings about version differences.

I might tweak this more, but it's usable enough now to unblock everything.

**Comment by icculus** [comment]
Actually, reopening, I need to sort through the non-bridged pages still (tutorials, enums/structs that aren't bridged, etc).

But still consider this unblocked!

**Comment by icculus** [comment]
WinRT stuff removed from the main wiki in https://github.com/libsdl-org/sdlwiki/commit/1e26a8f907b8ec405b8b578a9233203541421952  ... just realized I need to update the first-available-in-version management script though!

**Comment by icculus** [comment]
I'm assuming we want everything on the wiki to say "available since SDL 3.0.0" even if it exists unchanged from SDL2...?  Partially I'm concerned about things that are going to have the same name but different parameters; SDL_CreateThread comes to mind immediately.

The SDL2 subdir will still have the SDL2 initial version values, as usual.

**Comment by slouken** [comment]
> I'm assuming we want everything on the wiki to say "available since SDL 3.0.0" even if it exists unchanged from SDL2...? Partially I'm concerned about things that are going to have the same name but different parameters; SDL_CreateThread comes to mind immediately.

Yup, that makes sense to me.

**Comment by slouken** [comment]
Can we have the message about SDL2 link to the SDL2 Wiki?
Maybe it makes sense to have an SDL2 directory and an SDL3 directory and the front page redirects to SDL2 for now?

**Comment by icculus** [comment]
Yeah, I was thinking about that, that's a good idea.

**Comment by icculus** [comment]
Okay, this now has SDL2 and SDL3 subdirs, and if you go to any page that isn't in a subdirectory, as a hack inserted in our copy of ghwikipp, it'll redirect you to the SDL2 page for now.

like this:  https://wiki.libsdl.org/SDL_CreateWindow bumps to https://wiki.libsdl.org/SDL2/SDL_CreateWindow

Eventually we'll flip that to redirect to SDL3.

**Comment by slouken** [comment]
Great!

**Comment by icculus** [comment]
SDL2 pages that aren't autogenerated are back in place.

**Comment by berarma** [comment]
Maybe you're already aware but just in case, when browsing by category, there are a lot of functions missing. It's worse in some categories than others. See for example the input categories joystick, gamecontroller,...

**Comment by icculus** [comment]
I think @berarma's issue got resolved in early December. Please let me know if it didn't!

I'd still like the version message at the top of pages link to the actual wiki locations, if it's not a giant hassle; after that, I think this issue can be closed.
