### ISSUE TITLE
Review hints

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6573]
Review our hints:
* Are there hints that are platform specific that make more sense as general hints?
* Are there hints that can be removed?
* Are there hints that would be better moved to new API functionality?
* For any changes that we make, what is our plan for sdl2-compat support?

@libsdl-org/a-team

**Comment by Susko3** [comment]
https://github.com/libsdl-org/SDL/blob/4ee4e49e4904d7472360188343744652167a150d/include/SDL_hints.h#L597-L606

`SDL_HINT_IME_SUPPORT_EXTENDED_TEXT` should not be a hint, instead this functionality should be controlled by
```c
SDL_EventState(SDL_TextEditingExtEvent, SDL_ENABLE/SDL_DISABLE);
```

Especially as the hint doc is also wrong, multiple `SDL_TextInputEvent` are [sent](https://github.com/libsdl-org/SDL/blob/d1858eb124293ace5783a5e1a6788df7c57c02a8/src/events/SDL_keyboard.c#L1033-L1047) regardless of `SDL_HINT_IME_SUPPORT_EXTENDED_TEXT` state.

**Comment by slouken** [comment]
Agreed, feel free to submit a PR for this.

**Comment by Kontrabant** [comment]
https://github.com/libsdl-org/SDL/blob/fa3814ddf1512ff756f11f31d3d59e2f8e75218d/include/SDL_hints.h#L1644-L1653

This seems like it would be better off as a per-window flag, as with this hint it's either all or nothing.  Setting this for all windows globally can have unintended side-effects as well, such as disabling unredirection for fullscreen windows.

**Comment by slouken** [comment]
Agreed, we should review this when we replace the shaped window API.

**Comment by slouken** [comment]
> Agreed, we should review this when we replace the shaped window API.

This hint is gone, replaced with a check for SDL_WINDOW_TRANSPARENT.
