### ISSUE TITLE
Public header include convention

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6575]
For years people have been trying to include SDL headers like this:
```c
#include <SDL2/SDL.h>
```
We've recommended including SDL headers like this:
```c
#include "SDL.h"
```
macOS frameworks now require headers to be included using the first method, and that's causing issues with people trying to write cross-platform SDL code.

With SDL3, I'm inclined to move the headers to an SDL3 subdirectory and use the convention:
```c
#include <SDL3/SDL.h>
```

Thoughts?

@libsdl-org/a-team

**Comment by madebr** [comment]
I think this will require us to move all headers from `include/*.h` to `include/SDL3/*.h`.
The Visual Studio projects, the Xcode projects, Android.mk and android gradle require this when people use a vendored SDL as a subproject.
These build systems don't move the headers.
