### ISSUE TITLE
Remove usages of SDL_VERSIONNUM

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#6578]
This macro is not available anymore in SDL3:
https://github.com/libsdl-org/SDL/blob/0bfeed061b10ea7dd37c88d9bae1824bad760f3a/include/SDL_version.h#L86-L102

It is e.g. used in this source to compare against a `SDL_version` struct:
https://github.com/libsdl-org/SDL/blob/0bfeed061b10ea7dd37c88d9bae1824bad760f3a/src/video/wayland/SDL_waylandwindow.c#L1159

Perhaps replace it with a slightly different named macro?
e.g.
```c
#define SDL_VERSIONINT(X, Y, Z)                       \
    ((X) << 24 | (Y) << 8 | (Z) << 0)
```
32768 stable minor releases ought to be sufficient?

Opinions?

**Comment by smcv** [comment]
For the use of this in `SDL_SysWMinfo`, for SDL 2 it's too late: we have to use `SDL_VERSIONNUM` whether we want to deprecate it or not, because that's the ABI that SDL 2 users expect.

For SDL 3, I think it might be better if `SDL_SysWMinfo` (and any similar struct) is handled according to facts about `SDL_SysWMinfo` itself, rather than facts about the SDL version number.

One way to do that would be to do the same trick the Linux kernel often uses:

```
typedef struct
{
  /* since v3.0 */
  int a;
  char *b;
  union
  {
    struct
    {
      /* since v3.2 */
      Display *display;
    } x11;
    struct
    {
      /* since v3.0 */
      surface *s;
    } wayland;
  }
  etc.
} SDL_SysWMinfo;

void
SDL_GetSysWMInfo(void *info, size_t size)
{
    SDL_SysWMinfo real_info = {};

    memset(info, '\0', size);

    ... fill real_info with all the information for the appropriate backend, which it can do unconditionally ...

    memcpy (info, real_info, size);
}

...

void
application_code(void)
{
    SDL_SysWMinfo info;

  SDL_GetSysWMInfo(info, sizeof(info));
}
```

Or we could have a version number for the struct itself, separate from the SDL version:

```
#define SDL_SYSWMINFO_VERSION_CURRENT 2

typedef struct
{
  /* since v0 */
  int a;
  char *b;
  union
  {
    struct
    {
      /* since v1 */
      Display *display;
    } x11;
    struct
    {
      /* since v1 */
      wl_connection *conn;
      /* since v2 */
      wl_surface *surface;
    } wayland;
  }
  etc.
} SDL_SysWMinfo;

static void
X11_FillSysWMInfo(SDL_SysWMinfo *info, int info_version)
{
    if (info_version >= 1)
        info->x11.display = ...;
}

static void
Wayland_FillSysWMInfo(SDL_SysWMinfo *info, int info_version)
{
    if (info_version >= 1)
        info->wayland.conn = ...;

    if (info_version >= 2)
        info->wayland.surface = ...;
}

void
SDL_GetSysWMInfo(SDL_SysWMinfo *info, int info_version)
{
    info->a = ...;
    info->b = ...;
    backend->FillSysWMInfo(info, info_version);
}

...

void
application_code(void)
{
    SDL_SysWMinfo info;

  SDL_GetSysWMInfo(info, SDL_SYSWMINFO_VERSION_CURRENT);
}
```

**Comment by slouken** [comment]
I like @madebr's suggestion for the macro, and @smcv's suggestion to version `SDL_SysWMinfo` directly.

**Comment by smcv** [comment]
Having the first member of `SDL_SysWMinfo` in 3.0 be its size or version number (depending which approach we use) would probably also be a good thing to have.

**Comment by madebr** [comment]
I suppose it is okay to remove all usages of `if (version > SDL_VERSIONNUM(2, x, y))` because they are currently all true.
