### ISSUE TITLE
Separate versioning for SDL_syswm?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6584]
From @smcv's comment at https://github.com/libsdl-org/SDL/issues/6578#issuecomment-1323755222:

We could have a version number for the struct itself, separate from the SDL version:

```c
#define SDL_SYSWMINFO_VERSION_CURRENT 2

typedef struct
{
  /* since v0 */
  int a;
  char *b;
  union
  {
    struct
    {
      /* since v1 */
      Display *display;
    } x11;
    struct
    {
      /* since v1 */
      wl_connection *conn;
      /* since v2 */
      wl_surface *surface;
    } wayland;
  }
  etc.
} SDL_SysWMinfo;

static void
X11_FillSysWMInfo(SDL_SysWMinfo *info, int info_version)
{
    if (info_version >= 1)
        info->x11.display = ...;
}

static void
Wayland_FillSysWMInfo(SDL_SysWMinfo *info, int info_version)
{
    if (info_version >= 1)
        info->wayland.conn = ...;

    if (info_version >= 2)
        info->wayland.surface = ...;
}

void
SDL_GetSysWMInfo(SDL_SysWMinfo *info, int info_version)
{
    info->a = ...;
    info->b = ...;
    backend->FillSysWMInfo(info, info_version);
}

...

void
application_code(void)
{
    SDL_SysWMinfo info;

  SDL_GetSysWMInfo(info, SDL_SYSWMINFO_VERSION_CURRENT);
}
```

Having the first member of SDL_SysWMinfo in 3.0 be its size or version number (depending which approach we use) would probably also be a good thing to have.

**Comment by slouken** [comment]
I like the idea of passing in the version as a parameter, and having the version be in the structure, but is there value in having the version be different from the SDL version?

I would think it's much easier for people to wrap their head around versioning of the SDL library rather than have each structure versioned independently.

**Comment by smcv** [comment]
What I was thinking is that the version of each struct is going to change much less frequently than the version of SDL. If you use the compile-time SDL version as the thing the caller passes in, then that's quite likely to break forwards compatibility (ability to build a game against SDL 3.4.1 and have it run successfully against 3.2.3 if you're lucky enough), which you've said in the past is something that's important to you?

The Linux kernel convention that I mentioned on #6578 (using the `sizeof` the struct as the "version") is an easy way to get a "version" for each struct without having to actually say it explicitly.

**Comment by smcv** [comment]
The other technique I wanted to mention on #6578, but forgot by the time I had described the two options I did, is that instead of being a struct whose layout is directly library-user-visible, it could be an opaque object:

```
SDL_SysWMInfo *SDL_GetSysWMInfo(void);
void SDL_SysWMInfo_Free(SDL_SysWMInfo *self);
void *SDL_SysWMInfo_GetX11Display(SDL_SysWMInfo *self);
const char *SDL_SysWMInfo_GetWhateverName(SDL_SysWMInfo *self);
etc.
```

which would sidestep this whole versioning thing completely.

**Comment by madebr** [comment]
If we want the installed headers to work independent of `SDL_config.h` (see [this proposal](https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1232908677)),
we need to make the `SDL_SysWMInfo` struct a black box, as [smcv suggested above](https://github.com/libsdl-org/SDL/issues/6584#issuecomment-1323995029).

**Comment by slouken** [comment]
Implemented in https://github.com/libsdl-org/SDL/commit/b0840eb32e67861cfc803dc7eecae39008b4f783
