### ISSUE TITLE
Typo SDL2 2.26.0 Android.mk

### ISSUE THREAD

**Issue by 312937** [libsdl-org/SDL#6585]
I believe there is a coincidental (minor) typo in `Android.mk` file of the SDL2 2.26.0 source root at line 15.
- The newly appended `include` seems to be superfluous (actually misleading the make process):
  - ` LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)/include`
- It should be:
  - ` LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)`

**Comment by madebr** [comment]
Fixed in 47c37a8e9 (SDL3) and a8dd7a10f (SDL2)

**Comment by slouken** [comment]
I cherry-picked this to the SDL2 branch as well in 156bf7e6aab2535e06e6653e82251b98f32d5cfa
