### ISSUE TITLE
Code style: #if vs #ifdef

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6588]
We should standardize on the use of `#if` vs `#ifdef` in our code.

My understanding is that `#if X` will evaluate true if X is defined and evaluates non-zero and evaluate false if X is not defined or evaluates to 0, and that if X is undefined it will silently evaluate as 0. However I seem to remember that some compilers will complain that X is not defined if it is tested by the preprocessor like this and is not defined. Does anyone know if that's correct?

I think for most of the feature related tests we want `#if X`, e.g.
```
#ifndef SDL_HAVE_BLIT_AUTO
#define SDL_HAVE_BLIT_AUTO              !SDL_LEAN_AND_MEAN
#endif

#if SDL_HAVE_BLIT_AUTO
...
#endif

#define __APPLE_PLATFORM__ (__MACOSX__ || __IOS__ || __TVOS__)
#if __APPLE_PLATFORM__ 
...
#endif
```

Thoughts?

@libsdl-org/a-team

**Comment by slouken** [comment]
There's some more discussion here:
https://stackoverflow.com/questions/135069/ifdef-vs-if-which-is-better-safer-as-a-method-for-enabling-disabling-compila

**Comment by sezero** [comment]
With `#if XXX` where `XXX` is not defined, you can get `-Wundef` warnings.
Mainstream clang made that an error for apple platform macros, (see #4475,
but that behavior doesn't seem to be adopted by apple's clang versions.)

**Comment by slouken** [comment]
We could guarantee safety with:
```c
#if defined(FOO) && FOO
...
#endif
```
but that seems unnecessarily verbose.

**Comment by slouken** [comment]
I just answered my own question.

I did this:
```c
#define SDL_ENABLE_SYSWM_X11
#if SDL_ENABLE_SYSWM_X11
...
#endif
```
and got the compiler error "#if with no expression"

I think it's probably best to leave things as they are, using `#ifdef` for most cases and `#if` for specific cases where we know we define something to 1 or 0.
