### ISSUE TITLE
All of the documentation is gone!!!! 

### ISSUE THREAD

**Issue by neet93** [libsdl-org/SDL#6590]
All of the documentation is gone!!!! https://wiki.libsdl.org/SDL2/APIByCategory

**Comment by sor** [comment]
Just noticed this as well...
For the future SDL3 docs this should not necessarily need to be touched/changed. :thinking:

**Comment by mgerhardy** [comment]
Maybe related: https://github.com/libsdl-org/SDL/issues/6568

**Comment by icculus** [comment]
Whoops, there's a script that generates this that is pointing to the wrong place.

**Comment by icculus** [comment]
Oh, this isn't the autogenerated thing: https://wiki.libsdl.org/SDL2/CategoryAPI

I copied that page back from SDL3. There are others I need to fix up still, but we'll deal with that in #6568.
