### ISSUE TITLE
Code style: function declarations

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6592]
We don't have consistent placement of the return values of functions, sometimes it's on the previous line:
```c
int
foo(void)
{
}
```
and sometimes it's on the same line:
```c
int foo(void)
{
}
```

Originally having the return value on the previous line was to highlight exported functions and make it easy to quickly see the name of the function, but it doesn't seem to be that helpful, and I propose that all functions have the return value on the same line for consistency.

Thoughts?

@libsdl-org/a-team

**Comment by smcv** [comment]
When the `{}` and function body are present, it's a definition, not a declaration:

```
/* this is a declaration */
int do_something (void *argument);

/* this is a definition */
int
do_something (void *argument)
{
    printf ("hello\n");
}
```

Some projects have a convention of *always* putting a linebreak after the return type of a definition, but *never* putting a linebreak after the return type of a declaration (as in my example above). If you do that consistently, then you can jump to the definition, ignoring the declarations, by searching for `^do_something\b`.

If SDL isn't intending to follow that convention, then it's purely an aesthetic choice and might as well be the same for declarations and definitions.

**Comment by flibitijibibo** [comment]
In terms of maintenance, contributions, and _keeping_ things consistent: I've definitely forgotten the line break on more than one occasion, and have done so as recently as this past week https://github.com/libsdl-org/SDL/commit/f3cc99fb9342337c75ecf16250f80f54f4a4c8b5

Inversely, I've never _added_ the new line by accident for other projects :P

**Comment by icculus** [comment]
I'm definitely changing this, this has always driven me nuts.  :)

**Comment by slouken** [comment]
I'm using clang-format to catch a bunch of these. It looks like it doesn't catch the static function definitions, but it's a good step forward.
