### ISSUE TITLE
Code style: pointer * placement

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6593]
Older SDL code has a space between the * and related variable, e.g. `void * value`, and newer code has it next to the variable, e.g. `void *value`

I propose that we standardize on having the * next to the variable.

Thoughts?

@libsdl-org/a-team

**Comment by madebr** [comment]
I 2nd your proposal.
The *new style* has a nicer syntax (imho) for declaring multiple pointers in one line.
```c
int * a, * b;
```
vs
```c
int *a, *b;
```
