### ISSUE TITLE
Code style: third party code

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6594]
We have some third party code in SDL, for example the libm code from Sun Microsystems. I propose that we exclude these from all code style changes to make it easier to accept upstream patches, contribute upstream patches, and make it clear that it's third-party code.

Here is the third party code in SDL:
```
include/SDL_egl.h
include/SDL_hidapi.h
include/SDL_opengl.h
include/SDL_opengl_glext.h
include/SDL_opengles2_gl2.h
include/SDL_opengles2_gl2ext.h
include/SDL_opengles2_gl2platform.h
include/SDL_opengles2_khrplatform.h
src/events/imKStoUCS.*
src/hidapi/* (except for src/hidapi/SDL_hidapi.c)
src/joystick/controller_type.c
src/joystick/controller_type.h
src/joystick/hidapi/steam/controller_constants.h
src/joystick/hidapi/steam/controller_structs.h
src/libm/*
src/stdlib/SDL_malloc.c
src/stdlib/SDL_qsort.c
src/stdlib/SDL_strtokr.c
src/video/arm/*
src/video/khronos/*
src/video/x11/edid-parse.c
src/video/yuv2rgb/*
```

Thoughts?

@libsdl-org/a-team

**Comment by madebr** [comment]
This should also be coordinated with clang-tidy (https://github.com/libsdl-org/SDL/pull/6448).
The CMake script might need to be restructured a bit for that.

Is there an inventory of third-party code somewhere?

- `src/libm`: Sun Microsystems libm code
- `src/video/arm`: Nokia pixman code

**Comment by FtZPetruska** [comment]
> This should also be coordinated with clang-tidy (#6448). The CMake script might need to be restructured a bit for that.
> 
> Is there an inventory of third-party code somewhere?
> 
>     * `src/libm`: Sun Microsystems libm code
> 
>     * `src/video/arm`: Nokia pixman code

In CMake, you can turn off clang-tidy for such 3rd party code by making an object library:
```cmake
add_library(libm OBJECT src/libm/...)
set_target_properties(
    libm
    PROPERTIES
         C_CLANG_TIDY ""
         CXX_CLANG_TIDY ""
         OBJC_CLANG_TIDY ""
)

target_sources(SDL2 $<TARGET_OBJECTS:libm>) # Pre-3.12
target_link_libraries(SDL2 PRIVATE libm) # Since 3.12
```

**Comment by slouken** [comment]
I updated the original description with a list of the third party code I found in SDL. All of those should be excluded from code style changes.
