### ISSUE TITLE
Window data 'name' parameter usage is unclear

### ISSUE THREAD

**Issue by genpfault** [libsdl-org/SDL#6600]
The [`SDL_SetWindowData()`/`SDL_GetWindowData()` header docs](https://github.com/libsdl-org/SDL/blob/release-2.26.0/include/SDL_video.h#L892-L922) don't mention that `name` needs to be non-NULL and non-empty, as [enforced by the implementation](https://github.com/libsdl-org/SDL/blob/release-2.26.0/src/video/SDL_video.c#L2106-L2110).

Would also be nice to mention the lookup complexity; given the string key I expected something like a hashmap but [the current implementation](https://github.com/libsdl-org/SDL/blob/release-2.26.0/src/video/SDL_video.c#L2159-L2163) looks to be a `SDL_strcmp()`-powered scan through a linked list.

**Comment by slouken** [comment]
Feel free to submit a PR with documentation that makes sense to you.

**Comment by slouken** [comment]
This API has been removed in SDL3, replaced with window properties.
