### ISSUE TITLE
Feature request: A way to do delays with better precision than 1 millisecond

### ISSUE THREAD

**Issue by nightmareci** [libsdl-org/SDL#6602]
Since many modern platforms support sleeping threads with a delay precision better than 1 millisecond, it'd be nice if an option to delay at higher precision were provided. The requested delay duration should probably be nanosecond precision, per POSIX nanosleep. Delays down to 100 nanosecond interval precision can be done on Windows with [waitable timers](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-setwaitabletimer).

**Comment by slouken** [comment]
For SDL3 there is a new `SDL_DelayNS()` API that allows higher precision delays, implemented in https://github.com/libsdl-org/SDL/commit/8121bbd083b5a568709305270b554f2add3ba4a1.
