### ISSUE TITLE
SDL 2.26.0 does not work on the Nokia N-Gage

### ISSUE THREAD

**Issue by mupfdev** [libsdl-org/SDL#6610]
Hello,
I hate to be so non-specific, but SDL 2.26.0 does not work on the Nokia N-Gage.
An executable linked against the latest version simply does not start. No error message or crash whatsoever.

I opened this issue to document my findings on this matter.

**Comment by mupfdev** [comment]
@FtZPetruska advised me to use git-bisect, which quickly put me on the right track. I messed up myself.

**Comment by madebr** [comment]
Fixed in  #6612.

Thank you :)
