### ISSUE TITLE
Should the iOS demos be removed?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6623]
> Should the iOS demos be removed (https://github.com/libsdl-org/SDL/tree/main/Xcode-iOS/Demos)? Cross-platform SDL test programs already exist and I think the iOS demos have historically been less maintained than most other parts of SDL.
>
> (I'm not sure if this was brought up already but I couldn't find it in a short search at least.)

_Originally posted by @slime73 in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1325699809_

**Comment by slouken** [comment]
They're actually pretty interesting demos, and one of them shows how to use the accelerometer, which isn't demoed anywhere else. I think we can leave them for now.

I'll leave it open so we can think about this later.

**Comment by slime73** [comment]
Fair enough. The accelerometer demo will have to change or be removed if/when accelerometer joysticks are removed, maybe some of the demos could be updated to be more cross-platform test apps around that time?

**Comment by slouken** [comment]
Sure.

**Comment by slime73** [comment]
I suppose https://github.com/libsdl-org/SDL/commit/1d80082e8e08ed66294371818f03f32aa5072dcd resolves this.
