### ISSUE TITLE
Metal Contentview.layer in syswm

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6629]
> Mentioned in #6535, for future consideration:
>
> > However SDL_SysWMinfo probably should expose a pointer to contentView.layer.

__Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1318063657__

**Comment by slime73** [comment]
Does `SDL_Metal_GetLayer` return what they needed? I actually don't know if it returns the same layer as the backing view's layer on macOS, but I think it is what `VkMetalSurfaceCreateInfoEXT` expects at least.

**Comment by slouken** [comment]
I think so. Also I'd like to move a bunch of the SysWM stuff into window properties in the future so it can be easily extended.
