### ISSUE TITLE
Make SDL_*DRIVER match

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6630]
> It drives me nuts that we have `SDL_VIDEODRIVER` and `SDL_AUDIODRIVER` and `SDL_RENDER_DRIVER` (extra underscore). Let's make these all match in SDL3.

__Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1317324597__

**Comment by 1bsyl** [comment]
done!
