### ISSUE TITLE
We should grep the sources for "2.1"

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6633]
> We should grep the sources for "2.1" (for comments like "we should change this in 2.1"). Also, a grep for FIXME probably makes some sense, too, although I'm not sure I would commit to fixing all the FIXMEs, 3.0 or otherwise.  :)

__Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1311782712__

**Comment by Starbuck5** [comment]
I did a search through and had a stab at organizing them together in a coherent way--
I used "commit-absolute" links so they don't break what they are pointing at as code moves.

**Thread**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/include/SDL_thread.h#L194-L196
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/thread/SDL_thread.c#L398

**Haptic**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/include/SDL_haptic.h#L120-L128
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/haptic/darwin/SDL_syshaptic.c#L439
+2 other instances of the same thing in that line, + repeated instances of this comment in https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/haptic/linux/SDL_syshaptic.c, https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/haptic/windows/SDL_dinputhaptic.c, and https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/test/testhaptic.c

**Dynapi**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/dynapi/SDL_dynapi.c#L33-L41

**Hint**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/include/SDL_hints.h#L2239-L2245

**Pixels**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/include/SDL_pixels.h#L89-L91

**Surface**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/include/SDL_surface.h#L165
Applies to `SDL_CreateRGBSurfaceWithFormat` and `SDL_CreateRGBSurfaceWithFormatFrom`

**Audiocvt**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/audio/SDL_audiocvt.c#L467-L469
Comment occurs twice, once in `SDL_BuildAudioResampleCVT`, once above `SDL_ResampleCVT`.

**Render**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/render/SDL_render.c#L2695-L2696

**Video**
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/video/SDL_video.c#L3666
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/video/uikit/SDL_uikitvideo.m#L183-L184
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/src/video/windows/SDL_windowswindow.c#L86-L94

**Comment by icculus** [comment]
Thanks, this was super-helpful!

I've split these out into new issues where appropriate, so this one can be closed.

**Comment by meyraud705** [comment]
There are also 2 "next time we rev the ABI" comments, I am not sure if there already are issues for these:
https://github.com/libsdl-org/SDL/blob/0a48abc860b436387c94e90c13fd0db25772e356/include/SDL3/SDL_audio.h#L224
https://github.com/libsdl-org/SDL/blob/80a9397459cdbb15b7b0e403aec002ff68db5be9/include/SDL3/SDL_hints.h#L2539
