### ISSUE TITLE
Replace the name "iphone"

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6637]
> Some [APIs](https://github.com/libsdl-org/SDL/blob/main/include/SDL_system.h), defines, and public headers have "iphone" in their name, because iOS used to be called iPhoneOS. They could be renamed for SDL3.

_Originally posted by @slime73 in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1126716968_

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/cc1f9eb983a056bd4fd19dc4b8699c8b5d1cce77
