### ISSUE TITLE
Rethink logging subsystem

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6640]
> On a call this morning, the thought came up that some of our auxillary subsystems (logging, asserts, hints, etc) might be more complex than they need to be. No specific action items at the moment, but in SDL3 it might be worth thinking through how to trim these down to just what they need.
>
> The end result might be "they are fine as-is," and nothing changes, but it's important to remember that anything _can_ change for SDL3.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1210779445_

**Comment by icculus** [comment]
I want to vote for "fine as-is" for logging, asserts, and hints (beyond reviewing the existing hints, which we have a separate issue for, the subsystem itself is probably fine at the API level).

**Comment by slouken** [comment]
I reviewed the logging system, and I think you're right. I was thinking about removing the category from SDL_LogError(), etc, but if you're going to go to the trouble of using different log levels, you're probably going to want to separate them by category too.
