### ISSUE TITLE
Change `HAVE_*_H` in the public headers to `SDL_HAVE_*_H`

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6641]
> If there's still things like `HAVE_STDLIB_H` in the public headers, it should be renamed to `SDL_HAVE_STDLIB_H` or similar to avoid clashes with headers from other libs.
Otherwise people using two libs that use that kind of naming at the same time get compiler warnings about redefining those #defines - I think I have seen that with SDL2 and libjpeg in the past

_Originally posted by @DanielGibson in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1230392672_

**Comment by sezero** [comment]
Ughh.. And, if #6643 is done, there'll be no need for this.

**Comment by slouken** [comment]
Yep, this is taken care of in https://github.com/libsdl-org/SDL/pull/6649

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/63f307fe1fa662dbf2ffb2d2194d2d8b3191257d

**Comment by madebr** [comment]
I think moving `SDL_revision.h` and `SDL_revision.h.cmake` to `include/build_config` as well makes sense.

Additionally, if we add `include/build_config` to the include path of all build systems,
I think we can avoid needing to copy the include folder to the build folder.
