### ISSUE TITLE
CreateWindowFrom vs opaque pointers

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6642]
> Less a new feature and more fixing an existing one: We should change CreateWindowFrom to use something similar to SysWMInfo rather than an opaque pointer. Using a versioned struct will let us avoid doing things like [reading a pointer from an environment variable](https://github.com/libsdl-org/SDL/blob/main/src/video/windows/SDL_windowswindow.c#L611), which I'm still surprised we've gotten away with for so long. (Not as bad as .NET asking developers to set a _function pointer_ as an environment variable, but pretty darn close...)

_Originally posted by @flibitijibibo in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1229480067_

**Comment by slouken** [comment]
SDL_syswm.h just went away... hmmm. :)

**Comment by slouken** [comment]
SDL_CreateWindowFrom() has been replaced with SDL_CreateWindowWithProperties(), which allows more flexibility in how we create windows in the future.
