### ISSUE TITLE
Make public headers need no configuration at all

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6643]
> It would actually be nice if the installed headers just work without any SDL_config.h, honestly.
>
> Generally any app can build against SDL's headers just using the minimal config file, but we install the machine-specific SDL_config.h, even though this is only crucial for building SDL itself in modern times.
>
> For SDL3, let's have one set of static headers that are installed for public use.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1232908677_
      

(I don't know if this is possible, but we're getting away with this at the 1.2 API level in sdl12-compat, which replaced all configuration-specific details with preprocessor checks.)

**Comment by icculus** [comment]
A couple of good comments from @sezero to consider before we close this issue permanently:

https://github.com/libsdl-org/SDL/commit/63f307fe1fa662dbf2ffb2d2194d2d8b3191257d

**Comment by slouken** [comment]
Fixed, thanks!
