### ISSUE TITLE
The VC SDL2 SDK contains `SDL2test.lib`, the MinGW SDL2 SDK contains `libSDL2_test.a`.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6645]
> The VC SDL2 SDK contains `SDL2test.lib`, the MinGW SDL2 SDK contains `libSDL2_test.a`.
>
> Both should use the same name, with or without underscore.

_Originally posted by @madebr in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1137700193_

**Comment by slouken** [comment]
This was on my list as well, as I was going through things.

I think we want to have an underscore after SDL3 for all SDL related libs, e.g. SDL3_main, SDL3_test, SDL3_image, etc.

Thoughts @libsdl-org/a-team?

**Comment by icculus** [comment]
Underscore is fine with me.

**Comment by madebr** [comment]
Since c2432f8d0d569e5d90a2e22ce3207cd183293b33, main and test libraries are built with underscore.
