### ISSUE TITLE
Disabled subsystems remain with just dummy implementations

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6647]
> Another idea for SDL3:
> * Remove all the complexity around removing API entry points. You can disable subsystems, but the API entry points will remain, with dummy implementations.

_Originally posted by @slouken in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1014974840_

**Comment by slouken** [comment]
I don't think we remove entry points any more, is there anything missing at this point?

**Comment by slouken** [comment]
I double checked and this is completely implemented now.
