### ISSUE TITLE
Remove `depth` field from SDL_CreateRGBSurfaceWithFormat and SDL_CreateRGBSurfaceWithFormatFrom 

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6655]
https://github.com/libsdl-org/SDL/blob/bc5677db95f32294a1e2c20f1b4146df02309ac7/include/SDL_surface.h#L165

Why do these have a depth field? Remove it for SDL3.

**Comment by 1bsyl** [comment]
I think this can be closed
