### ISSUE TITLE
How to provide SDL3 to satellite libraries and SDL2-compate

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#6667]
These external projects will need to be able to link against a SDL3 sdk.
Because SDL3 is in its infancy, our usual approach of using the system package manager won't work.

The easiest, but most wasteful solution, is to always rebuild SDL3.

Alternatively, we somehow cache SDL3 builds and re-use these.
This can probably be combined with https://github.com/libsdl-org/SDL/issues/6624.

In both cases, this requires installation of system requirements.
Creating a `libsdl-org/setup-sdl` GitHub action would be nice.

**Comment by 1bsyl** [comment]
At first, to avoid handling various branches in the libraries, maybe we can have some specific defines ...

```
#if SDL2 
...
#elif SDL3
...
#endif
```

**Comment by icculus** [comment]
(sdl2-compat just clones SDL's repo, because it only needs the SDL3 headers, and not a build of SDL3, to compile, and we want the absolute latest in revision control for SDL3 at this point, so this works out.)

**Comment by madebr** [comment]
I created an [experimental setup-sdl action](https://github.com/madebr/setup-sdl), with an example usage at [this SDL_image pr](https://github.com/libsdl-org/SDL_image/pull/368).
Before it eventually moves to the [libsdl-org](https://github.com/libsdl-org) organization, I'd like feedback on the general design, and what inputs to add/keep/remove.

**Comment by madebr** [comment]
Closing for https://github.com/libsdl-org/SDL/issues/7219
