### ISSUE TITLE
Issue with include SDL2/SDL.h

### ISSUE THREAD

**Issue by Stefcool8** [libsdl-org/SDL#6669]
On Linux Mint 20.3, in Visual Studio Code, I spotted an error when including SDL to my c++ code (which was installed using apt-get):

After writing **#include <SDL2/SDL.h>** I get the error:
_cannot open source file "begin_code.h" (dependency of "SDL2/SDL.h")_

After tracking down the issue, I found, in /usr/include/x86_64-linux-gnu/SDL2/SDL_platform.h header file at line 179 and 194, that the problem was with the _#include "begin_code.h"_ and _#include "close_code.h"_ . After changing the lines to _#include "SDL2/begin_code.h"_ and _#include "SDL2/close_code.h"_, the issue seems to be solved. Guess the reason is that the file SDL_platform.h (from x86_64-linux-gnu) is a link to SDL_platform.h (from SDL2), and it interferes with the relative path from the include line.

**Comment by slouken** [comment]
This is related to https://github.com/libsdl-org/SDL/issues/6575

**Comment by madebr** [comment]
I don't understand why, after doing `#include <SDL2/SDL.h>`,
you only receive an error about `begin_code.h` and `close_code.h`.

The include chain is:
```
#include <SDL2/SDL.h>
|-> #include "SDL_atomic.h"
    |-> #include "SDL_platform.h"
        |-> #include "begin_code.h"
```

Why would `#include "SDL_atomic.h"` (inside `SDL.h`) work, but `#include "begin_code.h"` don't?
All includes use double quotes, so should include the files in the same folder.

**Comment by Stefcool8** [comment]
> I don't understand why, after doing `#include <SDL2/SDL.h>`, you only receive an error about `begin_code.h` and `close_code.h`.
> 
> The include chain is:
> 
> ```
> #include <SDL2/SDL.h>
> |-> #include "SDL_atomic.h"
>     |-> #include "SDL_platform.h"
>         |-> #include "begin_code.h"
> ```
> 
> Why would `#include "SDL_atomic.h"` (inside `SDL.h`) work, but `#include "begin_code.h"` don't? All includes use double quotes, so should include the files in the same folder.

Well, the way I tracked down the error was by entering each header and reading it's include issue, which was, like you described, refering to another header along the chain (actually, the chain was longer in my case).
The chain that led to the root of the problem is this:
> ```
> #include <SDL2/SDL.h>
> |-> #include "SDL_main.h"
>     |-> #include "SDL_stdinc.h"
>         |-> #include "SDL_config.h"
>             |-> #include <SDL2/_real_SDL_config.h> (located in one of the compiler's default include directories, in my case x86_64-linux-gnu/SDL2)
>                 |-> #include "SDL_platform.h" (this is a link in the compiler's SLD2 directory, to the header in include/SDL2 directory)
> ```

So, in `SDL_platform.h` the issue was, as described earlier, with `#include "begin_code.h"` and `#include "close_code.h"`. After changing it to `#include "SDL2/begin_code.h"` and `#include "SDL2/close_code.h"`, the issue was solved.
Now, my guess is that the link-to-file **SDL_platform.h** (which is located in the compiler's SDL2 directory) doesn't get along with relative paths. I'm a total beginner, so I can't give better arguments... What's certain is that the issue was solved after the described changes in the file.

**Comment by slouken** [comment]
I'm glad you figured it out. This is fixed for SDL3 in https://github.com/libsdl-org/SDL/commit/0a48abc860b436387c94e90c13fd0db25772e356.

**Comment by michahn01** [comment]
> On Linux Mint 20.3, in Visual Studio Code, I spotted an error when including SDL to my c++ code (which was installed using apt-get):
> 
> After writing **#include <SDL2/SDL.h>** I get the error: _cannot open source file "begin_code.h" (dependency of "SDL2/SDL.h")_
> 
> After tracking down the issue, I found, in /usr/include/x86_64-linux-gnu/SDL2/SDL_platform.h header file at line 179 and 194, that the problem was with the _#include "begin_code.h"_ and _#include "close_code.h"_ . After changing the lines to _#include "SDL2/begin_code.h"_ and _#include "SDL2/close_code.h"_, the issue seems to be solved. Guess the reason is that the file SDL_platform.h (from x86_64-linux-gnu) is a link to SDL_platform.h (from SDL2), and it interferes with the relative path from the include line.

I just want to say that you are a savior, thank you so much for this post.
