### ISSUE TITLE
please check DMG file in release 2.26.0

### ISSUE THREAD

**Issue by efa** [libsdl-org/SDL#6673]
check the DMG file is not damaged:
https://github.com/libsdl-org/SDL/releases/download/release-2.26.0/SDL2-2.26.0.dmg

**Comment by slouken** [comment]
It works fine here... ?

**Comment by efa** [comment]
the file has this signature:
SHA256             : 0x3BA2FB0A2E83060BF17E29381C230FED160503B00ECCB747210EDA149B321067
Size: 2083765 bytes
?

**Comment by slouken** [comment]
Okay?

**Comment by efa** [comment]
the hash is the same for you?

**Comment by slouken** [comment]
I don't have sha256 handy, but the size is correct and the MD5 checksum is:
`MD5 (/Users/valve/Downloads/SDL2-2.26.0.dmg) = 5ff2938339254326dd7d0578c9e81707`

**Comment by efa** [comment]
solved, was my 7zip that was old and can't unzip the file. Ver 22.01 can unpack the file without error, while 16.02 won't.

Sorry for the noise

**Comment by slouken** [comment]
I'm glad you figured it out.
