### ISSUE TITLE
Code style: sized types

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6677]
From [discourse](https://discourse.libsdl.org/t/sdl-3-0/40374/9):
It would be nice to see the public API replace the SintN, UintN, and SDL_bool types with their equivalent <stdint.h> and <stdbool.h> types.

Along similar lines, I would really like to see every integer field or parameter changed to an explicitly-sized type (presumably int32_t/uint32_t by default.

The former is mainly about reducing the cognitive load of (visually) parsing the API, but the latter would be particularly helpful for binding to languages where all types are explicitly sized (like C#) and languages where the size of the basic integer type varies by platform (like Go).

--
@libsdl-org/a-team, thoughts?

**Comment by sezero** [comment]
_Can_ we use stdint.h types? Yes, we can. _Should_ we? _I_ really don't see the point, but that's me.

**Comment by flibitijibibo** [comment]
I'd like this personally, but more importantly I'd like to use this as an excuse to fix the types that aren't consistent (especially `long`), as that also makes bindings generation very difficult.

**Comment by sezero** [comment]
> (especially `long`)

As far as I can see, `long` use in public apis are `MD5UINT4` in SDL_test_md5.h (which _is wrong_), and `SDL_threadID` in SDL_thread.h (which isn't really wrong.)

Other `long` uses in src tree are usually dictated by backends, are they not?

**Comment by slouken** [comment]
In general we've decided to minimize sweeping code changes that won't translate to SDL2. This will minimize the work involved in merging fixes between them.

**Comment by slouken** [comment]
Feel free to open a separate issue for any pain points when adding language bindings.
