### ISSUE TITLE
(Oracle Solaris 11.4) libsdl3 (main) does not build on Solaris even though it does on OpenIndiana

### ISSUE THREAD

**Issue by time-killer-games** [libsdl-org/SDL#6679]
I was expecting libsdl3 not being available to the package manager yet, considering how new it is, but the only version they have of sdl is sdl 1.2 with the LGPL license and highly outdated feature set.

I've tried building it from source code and was unsuccessful. It works in OpenIndiana but that is based on an older version of Solaris back when it was temporarily open source and it appears the two projects have parted ways enough they are no longer compatible with the same build instructions for libSDL2+. 

I can't further test this because:

1) I may be doing something wrong but my virtual machine stopped working now i have a broken grub menu "no filesystem found" error and can't fix it even after deleting, redownloading the vm and reinstalling the latest version of virtual box it seems my computer is still holding on to corrupted files preventing my vm to work like it used to and i have no idea how to start with a fresh vm again. Normally with other OS's i can just delete the VM and make a new one, not the case with Solaris. Really odd.

2) I don't have access to any other device to test it on as a host machine, because I am away from home for the foreseeable future (don't ask).

....

Also note: OpenIndiana by contrast does have libsdl2 available from the pkg package manager.

**Comment by slime73** [comment]
Individual library / software owners rarely have direct control over what's in the package manager of a particular Linux distro. You'll probably have better luck contacting the package manager maintainers.

**Comment by time-killer-games** [comment]
I guess i could also change the title of this issue since there's another problem, libsdl3 (main) does not build on Solaris even though it does on OpenIndiana

**Comment by time-killer-games** [comment]
We'll need someone else to verify this with testing as i mentioned I can't go back and provide the steps i tried which aren't working because vm is busted and not fixable without going on a huge rabbit trail.

**Comment by time-killer-games** [comment]
@icculus I'll see what I can do as soon as i fix my virtual machine. It's no longer showing the grub menu error, but now it is having kernel panic every time I run it in VirtualBox, with a fresh install of the vm file and virutalbox... and I don't have any compatible devices at the moment, but we'll see.

**Comment by time-killer-games** [comment]
Once I have access to Solaris again I'll see if i can fix a few things myself to work in that direction. 

For starters I did this: https://github.com/libsdl-org/SDL/pull/6681

Likely not one of the issues. But it's something...

**Comment by time-killer-games** [comment]
@icculus i verified sdl2 works on solaris.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
