### ISSUE TITLE
cmake: Debug builds have a 'd' appended to the library name

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6703]
Doing a `sudo ninja install` of SDL3 built with `-DCMAKE_BUILD_TYPE=Debug` ...

```
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/libSDL3d.so.0.0.0
```

Do we _need_ to mark debug builds with a separate name? It makes it harder to install a system-wide copy to debug things.

If this is common practice, I guess we'll live with it, but if we did this, can we undo it in CMakeLists.txt?

(CC @madebr)

**Comment by icculus** [comment]
I can't think of a time when someone would want both side-by-side, honestly...having an option to supply a postfix is good, but I'm inclined to say it should default to "".

@slouken, do you have an opinion on this one?

**Comment by madebr** [comment]
Honestly, I would just remove the variable and let people use `CMAKE_DEBUG_POSTFIX`, which is standard over all CMake projects.

**Comment by madebr** [comment]
I think the `d` suffix was introduced for MSVC, where the debug runtimes (MTd/MDd) complicate things even further.
But you're the main developers here, so your comfort counts :)

**Comment by slouken** [comment]
I agree with @icculus. What does CMAKE_DEBUG_POSTFIX default to? If it defaults to "", then let's just remove the variable.

**Comment by madebr** [comment]
By default is is not set, so the empty string.

**Comment by slouken** [comment]
Boom, let's do that.

**Comment by madebr** [comment]
See #6705
