### ISSUE TITLE
SDL3 build time increases...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6704]
Laptop with 4 physical CPU cores:

The configure script, SDL2, debug build: `CFLAGS="-O0 -ggdb3" ../configure`

`time make -j8` reports
```
real	0m35.094s
```

CMake, SDL2, debug build: `CFLAGS="-O0 -ggdb3" cmake -G Ninja ..`

`time ninja` reports
```
real	0m29.715s
```

**CMake, SDL3, debug build: `CFLAGS="-O0 -ggdb3" cmake -G Ninja ..`**

`time ninja` reports
```
real	0m52.708s
```

What did we do that almost doubled the build time?

**Comment by slouken** [comment]
We included all SDL headers instead of just the ones needed in each source file, in https://github.com/libsdl-org/SDL/commit/0a48abc860b436387c94e90c13fd0db25772e356.

I did partially to simplify the header migration and partially because the set of headers included wasn't included in order or always the minimal set. Is there a header analysis tool that can automate getting the minimum compilable set of headers?

Precompiled header support for SDL_internal.h would be fantastic, and greatly reduce build time everywhere. :)

**Comment by oleg-derevenetz** [comment]
@slouken

> Is there a header analysis tool that can automate getting the minimum compilable set of headers?

We use [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) in our [project](https://github.com/ihhub/fheroes2). It works pretty well with in-project headers and "good enough" with system headers, but it is targeted for C++, not C. It should work with C too, I believe, but I never tried to use it in pure C projects.

**Comment by madebr** [comment]
I tried [`target_precompile_headers`](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html) at https://github.com/madebr/SDL/tree/precompiled-headers,
but am not seeing a reduction in build time.

**Comment by 1bsyl** [comment]
@slouken I've tried to revert partially your patch on src/ and test/ + modify the header to keep the one before.
not sure if this is faster because I already have a recent machine ...
[patch_include.txt](https://github.com/libsdl-org/SDL/files/10117001/patch_include.txt)

**Comment by slouken** [comment]
FWIW, SDL2 build times:
real	1m48.792s
SDL3 build times:
real	3m11.533s
SDL3 build times with precompiled header:
real	2m12.512s

So including the minimal set of headers really does give the best compile times.

**Comment by madebr** [comment]
I revert my last statement: ccache was enabled.
Build time goes from 5m25s to 1m18s with precompiled headers
SDL2 build time is 2m44.

**Comment by slouken** [comment]
> I revert my last statement: ccache was enabled. Build time goes from 5m25s to 1m18s with precompiled headers SDL2 build time is 2m44.

Wow, your change is great, can you please merge it?

On my system, build times dropped to:
real	1m6.407s

**Comment by madebr** [comment]
Will do. But for CMake 3.16+ only.

**Comment by madebr** [comment]
Also keep in mind that this forces `SDL_internal.h` to be included, even when you don't add it as an `#include "../SDL_internal.h"`.

This is why it is explicitly disabled for `src/dynapi/SDL_dynapi.c`.
It renamed the `SDL_xxx` symbols to `SDL_xxx_REAL`, causing duplicate symbol link errors.

**Comment by slouken** [comment]
That's fine. I've actually add it to all the headers and source files manually anyway. That's the intent of that file in SDL builds.

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/pull/6708 so CI can have a say.

**Comment by icculus** [comment]
Um, I went from 52 seconds to 19.

Holy moly, I think we can call this resolved.   :)

**Comment by slime73** [comment]
Is there anything that needs to be done for the visual studio and xcode projects?

**Comment by madebr** [comment]
[target_precompile_headers](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html) mentions MSVC.
I don't know about xcode though.

**Comment by icculus** [comment]
I'll do a comparison real fast, sit tight.

**Comment by slime73** [comment]
> [target_precompile_headers](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html) mentions MSVC. I don't know about xcode though.

I was mostly thinking of the existing project files (https://github.com/libsdl-org/SDL/issues/6571#issuecomment-1325657754) - but either way I don't think build times are as important for them as the cmake project, I'm just wondering if they take significantly longer now and whether there are any easy changes to get them closer to cmake's times.

**Comment by icculus** [comment]
This M1 Mac Mini, using xcodebuild with the CMake project, with the commit before precompiled headers:

```
real	0m9.768s
```

The commit that enabled precompiled headers:

```
real	0m6.497s
```

Shaving off a 1/3rd of the time isn't that impressive when we went from 9 to 6 seconds, but obviously older Intel machines are likely to benefit more here.

So I think the answer is, yes, let's absolutely find the checkbox to enable this in the standalone Xcode project, too.

**Comment by slouken** [comment]
I'm working on this now.

**Comment by icculus** [comment]
@slouken: For xcode, you set this:

![image](https://user-images.githubusercontent.com/673562/204681779-c0415048-cfcf-45e5-b4d6-46def00d03a1.png)

"whatever.h" needs to be something it can find, I don't know how to specify a relative path or if there's a `$(PROJECT_DIR)` variable or something.

It can't point right to SDL_internal.h, because SDL_dynapi.c can't use precompiled headers. CMake generates a stub file and does this:

```c
/* generated by CMake */

#ifndef CMAKE_SKIP_PRECOMPILE_HEADERS
#include "/Users/icculus/projects/SDL/src/SDL_internal.h"
#endif // CMAKE_SKIP_PRECOMPILE_HEADERS
```

And then defines `CMAKE_SKIP_PRECOMPILE_HEADERS` on the compiler command line for just SDL_dynapi.c

I don't know what Visual Studio needs.

**Comment by slouken** [comment]
New Xcode is even easier. You just enable modules and Xcode automatically converts all #include statements into precompiled header directives. I flipped that on and compile times went from 12 seconds to 7 seconds - even faster than CMake's 8 seconds with precompiled headers enabled. :)
