### ISSUE TITLE
Rename *.pc in SDL satellite libraries

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6713]
The convention for package config files is lower case and use `-` instead of `_` in the filenames. When we switch the satellite libraries over to SDL3, we should rename them to match convention.

**Comment by madebr** [comment]
We now have:
- [`sdl3.pc`](https://github.com/libsdl-org/SDL/blob/main/cmake/sdl3.pc.in)
- [`sdl3-mixer.pc`](https://github.com/libsdl-org/SDL_mixer/blob/main/cmake/sdl3-mixer.pc.in)
- [`sdl3-ttf.pc`](https://github.com/libsdl-org/SDL_ttf/blob/main/cmake/sdl3-ttf.pc.in)
- [`sdl3-image.pc`](https://github.com/libsdl-org/SDL_image/blob/main/cmake/sdl3-image.pc.in)
- [`sdl3-rtf.pc`](https://github.com/libsdl-org/SDL_rtf/blob/main/cmake/sdl3-rtf.pc.in)
- [`sdl3-net.pc`](https://github.com/libsdl-org/SDL_net/blob/main/cmake/sdl3-net.pc.in)

**Comment by slouken** [comment]
Thanks!

**Comment by jengelh** [comment]
I guess we need `Provides: sdl2_compat` as well now; can't rule out that someone is depending on `PKG_CHECK_MODULES([sdl2_compat], [sdl2_compat])` already.
