### ISSUE TITLE
SDL2: windows: alt+mnemonics not working

### ISSUE THREAD

**Issue by rudolfwalter** [libsdl-org/SDL#6726]
I'm porting an old level editor from MFC+DirectDraw to MFC+SDL, and I noticed that when the focus is on the panel that I use as my SDL window, I can't open menus with their corresponding alt+letter (eg, alt+f doesn't open the File menu).

I traced the problem to b11b3493b9b6e8eac967befc1ec4c80287cea678, which was done in response to #1590. However, I need the exact opposite behavior. I checked to be sure, and commenting out the three lines added by that commit does fix my issue.

That said, both use cases seem valid to me, so I was wondering if SDL could accommodate this. Perhaps with a new hint?

**Comment by slouken** [comment]
Sure, feel free to create a PR with a new hint.
