### ISSUE TITLE
FreeBSD: Corrupt input in some locales

### ISSUE THREAD

**Issue by Carmina16** [libsdl-org/SDL#6728]
For some locales in FreeBSD (cannot see the correlation), X11 input of non-ASCII text is corrupt: UTF-8 key strings are converted to UTF-8 again as if they were Latin-1, with some trailing garbage in the end some times. The culprit seems to be this function:

https://github.com/libsdl-org/SDL/blob/ab916e8a61e8db6638c54a8d8155325bca277f29/src/video/x11/SDL_x11events.c#L741-L755

What is going on there?

**Comment by Carmina16** [comment]
Note the classic miscalculation of a string length at line 745 :P

**Comment by slouken** [comment]
Fixed, thanks!
