### ISSUE TITLE
SDL2 Keyboard Issue

### ISSUE THREAD

**Issue by Lenny003** [libsdl-org/SDL#6733]
Don't know how to describe properly at this point, my third time trying to report a bug, first post on PCSX2's github https://github.com/PCSX2/pcsx2/issues/7514#issue-1470634534 , and on arch linux's bug tracker https://bugs.archlinux.org/task/76716 , essentially with version 2.26.0 I have an issue where it will disconnect and reconnect my keyboard, but version 2.24.2 wont.

**Comment by Lenny003** [comment]
Still happening with 2.26.1

**Comment by slouken** [comment]
What if you do this before running your program from the terminal window?
`export SDL_JOYSTICK_HIDAPI=0`

**Comment by Lenny003** [comment]
Seems like it fixes the issue but why does it happen in the current version compared to 2.24.2?

**Comment by slouken** [comment]
We started probing devices to see if they were game controllers, and apparently this causes problems for some Razer devices. This is fixed for the next release, thanks!

**Comment by sezero** [comment]
Fix eligible for `release-2.26.x` branch?

**Comment by slouken** [comment]
> Fix eligible for `release-2.26.x` branch?

Yep

**Comment by sezero** [comment]
OK, cherry-picked as 690e2f21f25801e7f56aab1e29bb4d2a151b7995
