### ISSUE TITLE
Add event timestamps for Wayland

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6738]
We now have the ability to pass on event timestamps from the OS, added in https://github.com/libsdl-org/SDL/commit/0a3262e819edc695a764702e8127bbd1b09944ef.

Let's hook this up for Wayland!

**Comment by Kontrabant** [comment]
Sounds like a good time to wire up the [high-res timestamp protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/input-timestamps/input-timestamps-unstable-v1.xml) as well.
