### ISSUE TITLE
gendynapi.pl uninitialized value warning

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#6740]
```
Use of uninitialized value $7 in split at ./gendynapi.pl line 86, <HEADER> line 71.
NEW: extern DECLSPEC Uint64 SDLCALL SDL_GetTicksNS(void);
Use of uninitialized value $7 in split at ./gendynapi.pl line 86, <HEADER> line 125.
NEW: extern DECLSPEC void SDLCALL SDL_DelayNS(Uint64 ns);
```

Possibly because of this, when I tried to recreate the late addition of NS time
procedures' entries it output `SDL_DYNAPI_PROC(void,SDL_DelayNS,(void),(),)`
instead of `SDL_DYNAPI_PROC(void,SDL_DelayNS,(Uint64 a),(a),)`

I'm running with perl-5.10.1. @icculus ?

**Comment by sezero** [comment]
Commit 0f9482ebc is to blame. Doing the following fixes things for me.
Don't know whether that is the right thing to do here at all, though..
```diff
diff --git a/src/dynapi/gendynapi.pl b/src/dynapi/gendynapi.pl
index f9cba30..99f7095 100755
--- a/src/dynapi/gendynapi.pl
+++ b/src/dynapi/gendynapi.pl
@@ -81,10 +81,10 @@ while (my $d = readdir(HEADERS)) {
 
             next if $existing{$fn};   # already slotted into the jump table.
 
-            $sdl_dynapi_sym_contents =~ s/# extra symbols go here/$fn;\n    # extra symbols go here/;
-
             my @params = split(',', $7);
 
+            $sdl_dynapi_sym_contents =~ s/# extra symbols go here/$fn;\n    # extra symbols go here/;
+
             #print("rc == '$rc', fn == '$fn', params == '$params'\n");
 
             my $retstr = ($rc eq 'void') ? '' : 'return';
```

**Comment by madebr** [comment]
I think you're right. The `$7` refers to matching groups of the last regex.
You can't execute a new regex before it.

**Comment by madebr** [comment]
Perhaps move this regex to the bottom of the `if` branch, where macros are appended to `SDL_dynapi_procs.h` and `SDL_dynapi_overrides.h`.

**Comment by sezero** [comment]
I'm no perl guru at all, so I'l defer to the judgement of whoever is.

**Comment by slouken** [comment]
@icculus is your man, and probably needs to make magic happen when we bump to a new version here.

**Comment by madebr** [comment]
I added that `$sdl_dynapi_sym_contents` regex, so the problem is 100% there.

**Comment by icculus** [comment]
Ugh, is this for the symbol versioning thing? Did we actually _need_ that?

(The fix here is correct, but I'll look to see if there was a more-reasonable place to put this.)

**Comment by sezero** [comment]
Hope this gets fixed before some new addition: Note the wrong output by the script.

**Comment by madebr** [comment]
> Ugh, is this for the symbol versioning thing? Did we actually _need_ that?

We don't, but see https://github.com/libsdl-org/SDL/issues/2786#issuecomment-1333927823 for why it's useful for users.

**Comment by 1bsyl** [comment]
I wonder whether we should move to python for this script

**Comment by icculus** [comment]
> We don't, but see https://github.com/libsdl-org/SDL/issues/2786#issuecomment-1333927823 for why it's useful for users.

I still don't see any actual value in this, fwiw.

**Comment by sezero** [comment]
Can I push the following to address the immediate issue until you solve the other things?
```diff
diff --git a/src/dynapi/gendynapi.pl b/src/dynapi/gendynapi.pl
index f9cba30..e5300db 100755
--- a/src/dynapi/gendynapi.pl
+++ b/src/dynapi/gendynapi.pl
@@ -81,8 +81,6 @@ while (my $d = readdir(HEADERS)) {
 
             next if $existing{$fn};   # already slotted into the jump table.
 
-            $sdl_dynapi_sym_contents =~ s/# extra symbols go here/$fn;\n    # extra symbols go here/;
-
             my @params = split(',', $7);
 
             #print("rc == '$rc', fn == '$fn', params == '$params'\n");
@@ -140,6 +138,8 @@ while (my $d = readdir(HEADERS)) {
             print("NEW: $decl\n");
             print SDL_DYNAPI_PROCS_H "SDL_DYNAPI_PROC($rc,$fn,$paramstr,$argstr,$retstr)\n";
             print SDL_DYNAPI_OVERRIDES_H "#define $fn ${fn}_REAL\n";
+
+            $sdl_dynapi_sym_contents =~ s/# extra symbols go here/$fn;\n    # extra symbols go here/;
         } else {
             print("Failed to parse decl [$decl]!\n");
         }
```

**Comment by slouken** [comment]
yes, go for it

**Comment by sezero** [comment]
> yes, go for it

Pushed https://github.com/libsdl-org/SDL/commit/ed6d4016165a5f890bb1e4946e95e8126c519339

**Comment by 1bsyl** [comment]
Trying a re-write in python here https://github.com/libsdl-org/SDL/issues/6783 ...
