### ISSUE TITLE
Audio input not working on Mac mini M1 using Studio Display Microphone

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#6751]
I have a problem with Audio Input on my Mac mini M1 with Studio Display (macOS v13.0.1, SDL2 v2.26.0). The device opens without indicating an error and callback function is being called. But I only get silence (all streaming data is 0).

This is my code for initializing the device:

```c
void Audio_Input_Init(void) {    
    SDL_AudioSpec request;    /* We fill in the desired SDL audio options here */
    SDL_AudioSpec granted;
    
    /* Init the SDL's audio subsystem: */
    if (SDL_WasInit(SDL_INIT_AUDIO) == 0) {
        if (SDL_InitSubSystem(SDL_INIT_AUDIO) < 0) {
            Log_Printf(LOG_WARN, "[Audio] Could not init audio input: %s\n", SDL_GetError());
            Statusbar_AddMessage("Error: Can't open SDL audio subsystem.", 5000);
            bSoundInputWorking = false;
            return;
        }
    }
    
    /* Set up SDL audio: */
    request.freq     = SOUND_IN_FREQUENCY; /* 8kHz */
    request.format   = AUDIO_S16MSB;	   /* 16-Bit signed, big endian */
    request.channels = 1;			       /* mono */
    request.callback = Audio_Input_CallBack;
    request.userdata = NULL;
    request.samples  = SOUND_BUFFER_SAMPLES; /* buffer size in samples */
    
    if (Audio_Input_Device == 0) {
		char* device;
		SDL_GetDefaultAudioInfo(&device, &granted, 1);
		printf("%s\n", device);
        Audio_Input_Device = SDL_OpenAudioDevice(device, 1, &request, &granted, 0); /* Open audio device */
    }
    if (Audio_Input_Device == 0) {
        Log_Printf(LOG_WARN, "[Audio] Could not open audio input device: %s\n", SDL_GetError());
        Statusbar_AddMessage("Error: Can't open audio input device. Recording silence.", 5000);
        bSoundInputWorking = false;
        return;
    }
    
    bSoundInputWorking  = true;
    bSoundInputWorking &= check_audio(request.freq,     granted.freq,     "freq");
    bSoundInputWorking &= check_audio(request.format,   granted.format,   "format");
    bSoundInputWorking &= check_audio(request.channels, granted.channels, "channels");
    bSoundInputWorking &= check_audio(request.samples,  granted.samples,  "samples");
	
	if (!bSoundInputWorking) {
        SDL_CloseAudioDevice(Audio_Input_Device);
        Audio_Input_Device = 0;
        Statusbar_AddMessage("Error: Can't open audio input device. Recording silence.", 5000);
	}
}
```

For device name I get "Studio Display Microphone" which would be correct. There are no other input devices. Sound input did work on my old Intel iMac.

**Comment by icculus** [comment]
This is super-patronizing of me to ask, which I apologize for, but: the microphone definitely works with other applications, right? There isn't a mute button pressed on it or something?

Just want to get the obvious details out of the way before we dig deeper.

**Comment by andreasgrabher** [comment]
No problem. I know these things happen, but I did test and successfully recorded some sound using QuickTime Player. I will ask in the NeXT forums if someone can try using the latest code to record something on another platform. But it definitely worked previously and it seems everything is normal so far (callback is being called, and data len is normal, but stream contains all 0).

**Comment by andreasgrabher** [comment]
It seems to be a permission problem. This probably needs to be fixed outside of SDL. For details see here: http://www.nextcomputers.org/forums/index.php?topic=2642.1425

Quote:
„Works for me on macOS 12.6.1 (M1) with Previous rev 1244, NeXTstep 3.3, [Sound.app](http://sound.app/).

When starting the recording in [Sound.app](http://sound.app/), a requester is shown asking for access to the microphone. libSDL is installed via MacPorts.

Tested a bit more. The requester asked for microphone permission for [Terminal.app](http://terminal.app/), since I started the Previous binary directly (./src/Previous.app/Contents/MacOS/previous) to see the log in the terminal.

The requester isn't shown when starting Previous using open (open ./src/Previous.app) or using Finder and no audio level is shown when recording in [Sound.app](http://sound.app/).

I couldn't find a way to add [Previous.app](http://previous.app/) to the Security & Privacy -> Privacy -> Microphone access permissions in System Preferences, but it seems this is at least part of the problem. I never tried recording audio from Previous before, so I can't really say if this was different in earlier versions...

It seems that starting in macOS 10.14 an additional entry in Info.plist is required to show the Microphone requester. Adding a [key NSMicrophoneUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsmicrophoneusagedescription) works for me:

CodeSelect
        <key>NSMicrophoneUsageDescription</key>
        <string>In order to record audio, Previous requires access to your microphone.</string>

You can use "tccutil reset Microphone com.sourceforge.previous" to reset Previous' access permissions to the Microphone for testing.„

**Comment by slouken** [comment]
Great, I'm glad you figured that out.
