### ISSUE TITLE
Combine SDL_WINDOWEVENT_RESIZED and SDL_WINDOWEVENT_SIZE_CHANGED?

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#6757]
One of the FIXME comments in SDL's code suggests combining the two events. Personally the split has been confusing to me, so I like the idea:

https://github.com/libsdl-org/SDL/blob/8cafde5ecc402f62a3fa1efe9c94b4f12ae6f4f4/src/events/SDL_windowevents.c#L197-L198

**Comment by slouken** [comment]
This has been clarified with `SDL_EVENT_WINDOW_RESIZED` and `SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED`
