### ISSUE TITLE
The "SDL_JOYBATTERYUPDATED" event is not sent when a joystick is connected, but only after the first activity

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#6761]
When the joystick is connected to the PC, the `SDL_JOYBATTERYUPDATED` event is not sent, so the battery/power status is initially unknown to the application. This state is maintained until the first use of any manipulator (button, hat, axis, stick) — only then SDL sends the `SDL_JOYBATTERYUPDATED` event together with the event for the manipulator used.

I suggest that this event should always be automatically sent as soon as the joystick is connected to the computer, so that the application can know the battery/power status from the first moment. Now all that's left is to ask the joystick for this data using the `SDL_JoystickCurrentPowerLevel` function as soon as the joystick is opened using the `SDL_JoystickOpen` function.

Problem detected on 64-bit Windows 10, using the **SDL 2.26.1** release and the **8bitdo SN30 Pro** gamepad.

**Comment by furious-programming** [comment]
> You can't ask the joystick for data, you have to wait until it sends it.

Hmm… that sucks… :(

> I'm not sure what mode the controller is in, but you can debug the joystick code and see what's happening?

My **8bitdo SN30 Pro** controller has no battery and no bluetooth support, so the only supported mode is just wired. And when I connect the controller to the PC and press something, the `SDL_JOYBATTERYUPDATED` event is generated, and the power level in the `event.jbattery.level` is `4`, which is the `SDL_JOYSTICK_POWER_WIRED` constant (correct value for my controller).

**Comment by furious-programming** [comment]
In the default mode. Which one is the default?

**Comment by AntTheAlchemist** [comment]
@furious-programming if you hold down A, B, X or Y when the controller first powers-up, you can select which mode it emulates: XBox, PS4, D-input, or SN30 Pro. Some of these modes will require a button to be pressed first so SDL can automatically detect which interface to use, and only then it will receive power information. Try powering-up the controller in the different modes to see the difference.

@slouken while I am here, there is a big problem with the mapping in SN30 Pro mode. The right stick up/down comes through as left/right and up/down is ignored. SDL spits out a "Joystick only has 4 axis" if you try SDL_GameControllerGetAxis with SDL_CONTROLLER_AXIS_RIGHTY, even though RIGHTY is the 4th axis? Raw axis 2 is X and 3 is Y as you'd expect. GUID is 0300d640c82d00000160000000000000. SDL reports the joystick type as unknown, but with 4 axis. The sensors and vibration are  not detected and no battery info is ever reported.

**Comment by AntTheAlchemist** [comment]
The Nintendo Switch Pro mode works great though, btw. But interestingly two battery events come through when it's opened in this mode. First event is "wired" and the second is "medium", which might seem odd, but I have the bluetooth version of this controller and I think it makes sense, it's wired and battery is charged to medium.

**Comment by furious-programming** [comment]
> @furious-programming if you hold down A, B, X or Y when the controller first powers-up, you can select which mode it emulates: XBox, PS4, D-input, or SN30 Pro. Some of these modes will require a button to be pressed first so SDL can automatically detect which interface to use, and only then it will receive power information. Try powering-up the controller in the different modes to see the difference.

Wait, I have a USB-only version, so it is constantly wired and there is no wireless mode. There is only one additional feature in it — turbo mode. I tried what you desribed and nothing happened. Apparently my controller does not support anything which is supported by the wireless model.

Secondly, I have my controller constantly connected to the laptop (again: via USB), from the start of the Windows to its shut down. I unplug it only when I need to test my game code to check how it behave. But normally, the controller is constantly connected when writing code for my game, sometimes i take a break and play some game using it, then i go back to writing. The behavior of the controller is always the same, no matter if I played it before testing my code or not. So 100% it's not because the controller is waiting for input to determine the handling mode.

The problem, however, is that the documentation for the controller does not address the subject of operating modes at all. So it is not known whether the wired version of the SN30 Pro does not actually support these modes, does not give the possibility to change them and is not implemented in the firmware, or maybe it is implemented in the firmware, but not made available to the user. So, I don't know if the firmware of the controller, when connected to a Windows PC, immediately and always chooses and uses DirectInput, or if it waits for anything to be pressed before selecting DirectInput anyway.

**Comment by AntTheAlchemist** [comment]
@furious-programming I was doing this test with mine wired, not over bluetooth. So the wired version only doesn't let you change the mode? The mode is selected depending on what it is plugged in to? So to answer @slouken's question, you will be in xinput mode. In this mode SDL is waiting for an event from the controller so it can decide which interface to use internally - it will not matter that the controller was used before SDL is started up. Only then will it pick up the battery level. This is part of the design behind SDL's clever compatibility with everything. I think the only way around this would be disable direct inpute and / or HIDAPI, forcing SDL to choose an interface from the start, but you'll lose compatibility and features this way.

**Comment by furious-programming** [comment]
> @furious-programming I was doing this test with mine wired, not over bluetooth. So the wired only version doesn't let you change the mode?

I can't change the mode myself, so I have to use the one that this controller supports under Windows. From what I can see, the wired version only supports X-Input under Windows:

![image](https://user-images.githubusercontent.com/8170730/205904074-7dd34048-9588-47e1-8cd3-1f2ee8644432.png)

And this is all that the manual of this controller describes.

> The mode is selected depending on what it is plugged in to?

That's what it says in the manual.

**Comment by slouken** [comment]
I'm going to reopen this and see if we can be a little smarter in SDL.

**Comment by slouken** [comment]
So after investigation, it's totally expected that that battery status can be unknown in some circumstances, and the application should be able to handle this state.

**Comment by furious-programming** [comment]
Yes, it may happen that the actual state of the battery cannot be determined, so it will be unknown for the SDL. I meant more that if the controller is wired and does not support wireless operation, then the power status should be known always and from the moment the controller is connected to USB port.

The `unknown` state needs to be handled anyway, but that's a different case. If my original problem cannot be solved in any way, then so be it — I will properly secure the code and adapt it to SDL behavior. Thanks again for your feedback.
