### ISSUE TITLE
Multiple steam controllers with same name

### ISSUE THREAD

**Issue by german77** [libsdl-org/SDL#6764]
After updating to 2.26.1 all controllers say "Steam Virtual Gamepad 0" but have different GUID. Making it impossible to identify which controller they are selecting for the end user.

before update 2.0.18
`03000000de280000ff11000001000000 is the old GUID for ALL steam controllers - with different ports for controllers.`

after update 2.26.1
```
030079f6de280000ff11000001000000 is the GUID for steam controller (1) port 0
0300b836de280000ff11000001000000 is the GUID for steam controller (2) port 0
0300f837de280000ff11000001000000 is the GUID for steam controller (3) port 0
030039f7de280000ff11000001000000 is the GUID for steam controller (4) port 0
```

**Comment by slouken** [comment]
I'm not sure what software you're using? SDL doesn't have any concept of "port"
