### ISSUE TITLE
Hat is not returning to "centered" state on some(only my?) gamepads

### ISSUE THREAD

**Issue by LittleCrabby** [libsdl-org/SDL#6767]
- Version: 2.0.14 and newer
- OS: Windows

I have Mocute 054 gamepad which is recognized as Xbox One S Controller. It has weird behavior in SDL2: d-pad buttons keep "pressed" state even after being released but gets "released" state after pressing another button. After debugging I realized that the problem appeared with big changes in version 2.0.14. The problem is in RAWINPUT_HandleStatePacket(). The `hat_states[]` array contains 9 values, but when I release a button on my gamepad, I receive state 9, so it fails on array size check. Link to the video for better understanding: 
https://user-images.githubusercontent.com/24526536/205724966-23c07991-4a8f-43cd-a216-10d5abe61327.mp4

In my system I was able to fix this, defining default state hat as `SDL_HAT_CENTERED`, so it always being centered if unknown state was received. I am very unsure, but anyway here is the affected code with my "fix":
```c
for (i = 0; i < nhats; ++i) {
        HIDP_DATA *item = GetData(ctx->hat_indices[i], ctx->data, data_length);
        if (item) {
            /* Set default state here */
            Uint8 hat = SDL_HAT_CENTERED;
            const Uint8 hat_states[] = {
                SDL_HAT_CENTERED,
                SDL_HAT_UP,
                SDL_HAT_UP | SDL_HAT_RIGHT,
                SDL_HAT_RIGHT,
                SDL_HAT_DOWN | SDL_HAT_RIGHT,
                SDL_HAT_DOWN,
                SDL_HAT_DOWN | SDL_HAT_LEFT,
                SDL_HAT_LEFT,
                SDL_HAT_UP | SDL_HAT_LEFT,
            };
            ULONG state = item->RawValue;

            if (state < SDL_arraysize(hat_states)) {
#ifdef SDL_JOYSTICK_RAWINPUT_MATCHING
                match_state = (match_state & ~HAT_MASK) | hat_map[state];
#endif
                /* Reassign default state */
                hat = hat_states[state];
            }

            /* Call with default or reassigned state */
            SDL_PrivateJoystickHat(joystick, i, hat);
        }
    }
```

**Comment by slouken** [comment]
Your fix looks good, thanks!
