### ISSUE TITLE
SDL3 some keys not updating timestamp with SDL_SetWindowKeyboardGrab

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#6771]
Just in case this has been overlooked. Since the nanosecond changes, I've noticed certain keys aren't updating the timestamp. 

Affected keys are: tab, ctrl, alt, win

**Comment by slouken** [comment]
I assume this is on Windows? Have you looked at the messages to see why that would be?

**Comment by AntTheAlchemist** [comment]
Yes, Windows. I just discovered this is only happening with SDL_SetWindowKeyboardGrab, and it's a new bug. I saw a recent commit that changed the behaviour or Windows keyboard shortcuts. It's possibly to do with that? SDL 2.25.0 works fine.

**Comment by slouken** [comment]
It looks like the keys handled with `WIN_KeyboardHookProc()`

**Comment by slouken** [comment]
I think this is the fix, can you verify?
