### ISSUE TITLE
SDL_GetEventState

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6773]
This is in SDL_events.h ...

```c
#define SDL_GetEventState(type) SDL_EventState(type, SDL_QUERY)
```

This is pretty harmless, but do we want to replace this with a real function or rethink anything about SDL_EventState for SDL3?

(The answer can be "this is fine" and close the issue, I'm just posting things as I notice them.)

**Comment by flibitijibibo** [comment]
As long as it can be represented as a macro for #6337 I don't think these are too big a deal - in the early SDL2# days I did occasionally hit a function that turned out to be a macro, but it's not life-or-death to fix.
