### ISSUE TITLE
Remove event filters?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6774]
We have two ways to let people get callbacks about events as they are heading into the SDL event queue: SDL_AddEventWatch and SDL_SetEventFilter. Event filters should be removed:

- You can only have one filter with the current API (unless building a chain of filters, which is messy), which means an app and a library that both want one are going to stomp on each other. Event watchers don't have this problem.
- Internal pieces of SDL (the render API, for example) rely on events not being filtered out to make it work correctly (if you filter out resize events, the scene can render with the wrong viewport or mouse scaling, etc).

**Comment by slouken** [comment]
Yeah, I believe the event filter allows the application to modify handling for Windows messages as well. I don't mind if we change things, but we need to have that functionality available somehow.

**Comment by icculus** [comment]
Eh, let's abandon this, not every idea is good.  :)

Closing, but feel free to reopen if anyone has a good idea that makes an API improvement.

**Comment by slime73** [comment]
> One possible caveat is that the timings for the two APIs are not the same, as far as I know - FNA actually depends on filters _specifically_ to implement `OnPaint` accuracy

I was looking at the code the other day and it seemed like the event filters are executed at the same time as event watchers (so event watchers should already work the same as filters for the purposes of timing). Is that not the case in practice?

https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_events.c#L1164
