### ISSUE TITLE
About disabling of SDL_X11_SHARED on Apple Platforms

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#6778]
Hello!

At some moment I found at the `cmake/sdlchecks.cmake` the next code:
```cmake
      # !!! FIXME: why is this disabled for Apple?
      if(APPLE)
        set(SDL_X11_SHARED OFF)
      endif()
```

And, during my experiments on [Mac OS X Tiger](https://github.com/libsdl-org/SDL/compare/SDL2...Wohlstand:SDL:mac-tiger) when I started to use X11, I found an answer to that SDL_X11_SHARED question: it just doesn't work, basically, there are no valid library paths specified, and they are always NULL, and therefore, never gets loaded. So, to allow the shared mode we need to specify library paths for the Apple platform. I think we can give the comment with a proper answer to this block.

**Comment by madebr** [comment]
`FindLibraryAndSONAME` is not looking for the X11 libraries in any special paths.

Can you try applying the following patch:
```patch
diff --git a/cmake/sdlchecks.cmake b/cmake/sdlchecks.cmake
index 6e860415a..982089bdd 100644
--- a/cmake/sdlchecks.cmake
+++ b/cmake/sdlchecks.cmake
@@ -280,6 +280,7 @@
 macro(CheckX11)
   cmake_push_check_state()
   if(SDL_X11)
+    find_package(X11)
     foreach(_LIB X11 Xext Xcursor Xi Xfixes Xrandr Xrender Xss)
         FindLibraryAndSONAME("${_LIB}")
     endforeach()
```
configure CMake (with `SDL_X11` enabled) and then provide me with the output of the following command:
```
cat CMakeCache.txt | grep "X.*_LIB"
```

The output will contain the result of finding the X11 libraries using the current SDL logic and CMake's [`FindX11`](https://cmake.org/cmake/help/v3.0/module/FindX11.html) logic.
If the latter works, we can probably piggyback ride it.

**Comment by Wohlstand** [comment]
I'll take a look today a bit later, thanks for the hint.

**Comment by Wohlstand** [comment]
And the next output part:
```
-- Looking for XOpenDisplay in /usr/X11R6/lib/libX11.dylib;/usr/X11R6/lib/libXext.dylib
-- Looking for XOpenDisplay in /usr/X11R6/lib/libX11.dylib;/usr/X11R6/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/X11R6/lib/libX11.dylib
-- dynamic libX11 -> libX11.6.dylib
-- dynamic libXext -> libXext.6.dylib
-- dynamic libXcursor -> libXcursor.1.dylib
-- dynamic libXi -> libXi.6.dylib
-- dynamic libXrandr -> libXrandr.2.dylib
-- dynamic libXrender -> libXrender.1.dylib
-- dynamic libXss -> libXss.1.dylib
```

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by Wohlstand** [comment]
I think, I forgot about this one, but seems doesn't matter. This issue was a kind of discussion about suspicious thing on Apple.

**Comment by Wohlstand** [comment]
I guess, to completely "fix" this issue it's enough to change the comment I mentioned into something like:
```cmake
# Note: Disabled on Apple because the dynamic mode backend for X11 doesn't work properly on Apple during several issues.
```

**Comment by Wohlstand** [comment]
To completely solve this, the patch is needed to change the comment in CMakeLists file.

**Comment by slouken** [comment]
Can you create a PR for this, just so the comment is in the right place?

**Comment by Wohlstand** [comment]
Ye, I'll try that very soon.

**Comment by slouken** [comment]
Merged, thanks!

**Comment by Wohlstand** [comment]
By the way, the `abandoned` tag here is not suitable, and this can be changed into "closed as completed". Because all the topic was about the reason why that question was been added.
