### ISSUE TITLE
Question: why glXMakeCurrent() with a None context leads a dead lock on some platforms?

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#6779]
During my experiments on Mac OS X Tiger, I accidentally found that that attempt to [make the `None` context current](https://github.com/libsdl-org/SDL/compare/SDL2...Wohlstand:SDL:mac-tiger#diff-08989bbcfbd808cb82f415675a25d06a80e3568231667eb49361ce2cbadd4642R475), leads to a deadlock. So, I disabled that block on my side. However, I want to get an understanding of why it happens. Is that a bug of certain X11 implementations? At my end, there is a very old X11R6 based on XFree86. The same code works fine everywhere, it gets a deadlock exclusively on the Mac OS X Tiger's X11.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by Wohlstand** [comment]
This issue is a question that I gave, but seems, nobody replied to it.

**Comment by slouken** [comment]
Yeah, I don't think anyone here knows. :)

**Comment by Wohlstand** [comment]
Anyway, I may guess it's a bug of the XFree86 of that era, and the thing I did on my end is a workaround over it.
