### ISSUE TITLE
[SDL 2.26.0] Not receiving SDLK_5 or SDL_SCANCODE_5

### ISSUE THREAD

**Issue by rom1v** [libsdl-org/SDL#6787]
When I press number keys above the letters keys (not the numpad), I receive a `SDL_KeyboardEvent` with a keycode (`event->keysym.sym`) and a scancode (`event->keysym.scancode`). However, I get unexpected values when I press <kbd>5</kbd>:
 - <kbd>1</kbd>: keycode=`SDLK_1`, scancode=`SDL_SCANCODE_1`
 - <kbd>2</kbd>: keycode=`SDLK_2`, scancode=`SDL_SCANCODE_2`
 - <kbd>3</kbd>: keycode=`SDLK_3`, scancode=`SDL_SCANCODE_3`
 - <kbd>4</kbd>: keycode=`SDLK_4`, scancode=`SDL_SCANCODE_4`
 - <kbd>5</kbd>: keycode=`SDLK_LEFTPAREN`, scancode=`SDL_SCANCODE_SK_LEFTPAREN`
 - <kbd>6</kbd>: keycode=`SDLK_6`, scancode=`SDL_SCANCODE_6`
 - <kbd>7</kbd>: keycode=`SDLK_7`, scancode=`SDL_SCANCODE_7`
 - <kbd>8</kbd>: keycode=`SDLK_8`, scancode=`SDL_SCANCODE_8`
 - <kbd>9</kbd>: keycode=`SDLK_9`, scancode=`SDL_SCANCODE_9`
 - <kbd>0</kbd>: keycode=`SDLK_0`, scancode=`SDL_SCANCODE_0`

On Linux/Debian sid with XFCE/X11.

I don't know if it happens with earlier versions, but I would probably have noticed if it was the case.

**Comment by meyraud705** [comment]
git bisect gives 99f2a5039 as the first bad commit.

This commit is really broken:
1 2 3 -> No event
4 -> work
5 -> (
6 -> work
7 8 9 0 -> No event

Commit 2c1923859 fixes every key except 5.

**Comment by mcourteaux** [comment]
Just wanted to point out that this bug is still in the latest version on Ubuntu. I was on 2.0.20 on my machine (Ubuntu 22.04.3 LTS). I don't know how the distribution cycle for SDL goes, but probably quite some software is affected by this.

Let me be clear that I don't have an issue myself, as I just pulled and installed from source again.
