### ISSUE TITLE
android project reports an error on first open.

### ISSUE THREAD

**Issue by BruceWayen66** [libsdl-org/SDL#6792]
[CXX1405] error when building with ndkBuild using C:\Users\lee\Projects\SDL\android-project\app\jni\Android.mk: Build command failed.
Error while executing process C:\Users\lee\AppData\Local\Android\Sdk\ndk\21.4.7075529\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\lee\Projects\SDL\android-project\app\jni\Android.mk NDK_APPLICATION_MK=C:\Users\lee\Projects\SDL\android-project\app\jni\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 NDK_OUT=C:\Users\lee\Projects\SDL\android-project\app\build\intermediates\cxx\Debug\3q4g6la6/obj NDK_LIBS_OUT=C:\Users\lee\Projects\SDL\android-project\app\build\intermediates\cxx\Debug\3q4g6la6/lib APP_PLATFORM=android-16 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

C:/Users/lee/AppData/Local/Android/Sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:651: Android NDK: Module main depends on undefined modules: SDL3    
C:/Users/lee/AppData/Local/Android/Sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.

**Comment by BruceWayen66** [comment]
How should I fix it?

**Comment by madebr** [comment]
Can you please post a reproducer?
We test building SDL with `Android.mk` using the following driver scripts: [`androidbuildlibs.sh`](https://github.com/libsdl-org/SDL/blob/main/build-scripts/androidbuildlibs.sh) and [`androidbuild.sh`](https://github.com/libsdl-org/SDL/blob/main/build-scripts/androidbuild.sh).

**Comment by AntTheAlchemist** [comment]
I'm getting the same error when converting a project from SDL2 to SDL3. I thought I might have broken something somewhere. But it might be something wrong with the new build? Has anyone got SDL3 working on Android yet?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
