### ISSUE TITLE
OpenGLES removed?

### ISSUE THREAD

**Issue by rtrussell** [libsdl-org/SDL#6793]
I've seen some recent references to **OpenGLES** being removed.  I still use OpenGLES, it's essential to my application because I rely on the functionality of **glLogicOp()** which is supported in Open GLES but not in OpenGLES 2.  So removing OpenGLES would be catastrophic for me; can somebody confirm that this is just in **SDL3** rather than SDL2?

**Comment by slime73** [comment]
Yes, the OpenGL ES 1 renderer backend was removed from SDL3 and not SDL2.

OpenGL ES 1 context creation support was *not* removed, though. Just the SDL_Render backend.
