### ISSUE TITLE
[UWP/XBOX] assert() firing when removing earphones from controller

### ISSUE THREAD

**Issue by ITotalJustice** [libsdl-org/SDL#6795]
this is the assert that is triggered <https://github.com/libsdl-org/SDL/blob/f17058b562c8a1090c0c996b42982721ace90903/src/audio/wasapi/SDL_wasapi_winrt.cpp#L192>

to reproduce this, init sdl with audio (you dont have to open an audio device). plugin and remove earphones from the xbox controller and the assert fires. the earphones can already be plugged in or plugged in at runtime, the assert will happen only when removed.

i don't quite understand the assert as to why it needs to be a capture device. Building in release mode (asserts disabled) seems to work fine

**Comment by icculus** [comment]
It looks like these asserts are backwards (see the one in the function below, too).

**Comment by icculus** [comment]
This is resolved now in SDL3 and SDL2. Thanks!

**Comment by ITotalJustice** [comment]
Thank you!
