### ISSUE TITLE
User report very long controller init times after uprev to 2.26.1

### ISSUE THREAD

**Issue by Novum** [libsdl-org/SDL#6799]
https://github.com/Novum/vkQuake/issues/594
This didn't happen before on SDL 2.0.22 (with some backports)

Getting those in the log:
```
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Connection timed out
ioctl (GFEATURE): Connection timed out
ioctl (GFEATURE): Connection timed out
ioctl (GFEATURE): Connection timed out
ioctl (GFEATURE): Connection timed out
ioctl (GFEATURE): Connection timed out
```

User is running a custom kernel and Arch though so this might just be a some problem in other parts of the system. Still wanted to point it out because it seems it was fine in older SDL versions.

**Comment by slouken** [comment]
What is the output of lsusb?
We might be running into a problem where SDL is probing Logitech devices for PS3/PS4 controller interfaces.

**Comment by putridpete** [comment]
Hi, user in question here. Output of `lsusb`:

```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID b58e:9e84 Blue Microphones Yeti Stereo Microphone
Bus 003 Device 002: ID 1532:0226 Razer USA, Ltd Huntsman Elite
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 090c:1000 Silicon Motion, Inc. - Taiwan (formerly Feiya Technology Corp.) Flash Drive
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 007: ID 2433:b200 ASETEK [NZXT Kraken X60]
Bus 001 Device 005: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 010: ID 045e:0b12 Microsoft Corp. Xbox Wireless Controller (model 1914)
Bus 001 Device 008: ID 1532:0099 Razer USA, Ltd Razer Basilisk V3
Bus 001 Device 002: ID 1532:0529 Razer USA, Ltd Razer USB Sound Card
Bus 001 Device 006: ID 26ce:01a2 ASRock LED Controller
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by slouken** [comment]
Ah, I'm betting it's one of the Razer devices.

Let's see if we can isolate which device is causing the issue. Can you try launching with this environment variables set?
```sh
env SDL_HIDAPI_IGNORE_DEVICES=0x1532/0x0000 /home/<YourName>/Applications/AppimageName.AppImage
```
Then, if that works, try each device individually?
```sh
env SDL_HIDAPI_IGNORE_DEVICES=0x1532/0x0226 /home/<YourName>/Applications/AppimageName.AppImage
env SDL_HIDAPI_IGNORE_DEVICES=0x1532/0x0099 /home/<YourName>/Applications/AppimageName.AppImage
env SDL_HIDAPI_IGNORE_DEVICES=0x1532/0x0529 /home/<YourName>/Applications/AppimageName.AppImage
```

And just for kicks, let's try this one too?
```sh
env SDL_HIDAPI_IGNORE_DEVICES=0x26ce/0x01a2 /home/<YourName>/Applications/AppimageName.AppImage
```

**Comment by putridpete** [comment]
OK, so the result was

0x0000 > No issue
0x0226 > No issue
0x0099 > ioctl (GFEATURE): Connection timed out
0x0529 > ioctl (GFEATURE): Connection timed out
0x01a2 > ioctl (GFEATURE): Connection timed out

As for the last item, ASRock LED Controller, I use a udev rule to blacklist the device, as it was interfering with input for my controllers:

/etc/udev/rules.d/01-asrock-LED-controller.rules
```
# Disable Asrock LED controller
 SUBSYSTEM=="usb", ATTRS{idVendor}=="26ce", ATTRS{idProduct}=="01a2", ATTR{authorized}="0"
```
Not sure if that has anything to do with this, but just figured I should disclose this.

**Comment by Novum** [comment]
Judging from that it is the mouse (Ltd Huntsman Elite)

**Comment by slouken** [comment]
Thanks! This should be fixed by 817454cfe.

**Comment by Novum** [comment]
Well that certainly is _a_ fix haha. Thanks @slouken

**Comment by slouken** [comment]
You're welcome! :)
We needed similar fixes for the other Huntsman keyboards.
