### ISSUE TITLE
SDL2: Wayland: On-screen keyboard pops up on its own

### ISSUE THREAD

**Issue by dos1** [libsdl-org/SDL#6807]
Running pretty much any SDL application with Wayland backend causes it to unconditionally request on-screen keyboard to show up via text-input protocol:

```
[1040824.581]  -> zwp_text_input_v3@22.enable()
[1040824.693]  -> zwp_text_input_v3@22.commit()
[1040824.714]  -> zwp_text_input_v3@22.enable()
[1040824.733]  -> zwp_text_input_v3@22.commit()
[1040824.751]  -> zwp_text_input_v3@22.set_content_type(0, 0)
[1040824.771]  -> zwp_text_input_v3@22.commit()
```

This event sequence is sent on window creation and also every time the window gains focus. Since on creation time the window lacks keyboard focus, some compositors such as phoc ignore the request, so OSK doesn't pop up instantly on window creation - but it's sufficient to move the focus away and back for it to show up.

This is easily reproducible with pretty much every test app that creates a window. In phosh, it's enough to unfold the home screen and fold it back to trigger this, as that causes SDL window to lose and regain focus.

This started to happen in 2.0.18, and both 2.24.2 and latest `SDL2` branch (c7097418711b57e786eeb464bbe366c056b19801) still exhibit this behavior.

**Comment by dos1** [comment]
Looks like it's caused by fc998b8ec963101466ee9827423ee29b270d93a2. That check is flawed BTW - devices that lack physical keyboard will often still have keyboard interface available - OSKs like virtboard that use virtual-keyboard protocol show up as a regular keyboard on a seat, and things like volume or home buttons do as well.

**Comment by flibitijibibo** [comment]
Haven't looked into this but a PinePhone is expected to show up at my door this week, so I can at least test/verify changes that anyone makes (and I can now actually make sure it _stays_ stable, once it is fixed).

**Comment by dos1** [comment]
Just for the record (I haven't had time for a dive into SDL yet): with this kind of stuff there's nothing that requires a phone hardware in order to test - phoc, phosh, Squeekboard etc. all run well on a PC, both directly on DRM and nested.

**Comment by slouken** [comment]
I'm going to move this out of this milestone. I don't have a Linux install new enough to build and install squeekboard and nobody else has had a chance to look more closely at this.

**Comment by slouken** [comment]
Text input is no longer enabled by default in SDL3.
