### ISSUE TITLE
wasm/wasi support?

### ISSUE THREAD

**Issue by dobkeratops** [libsdl-org/SDL#6810]
I use SDL2 via *emscripten* in the web 

the rust language has a lot of native bindings to the web platform without emscripten in the way (which adds alot of posix emulation in javascript)

Would it be possible to write an implementation of the SDL2 (and forthcoming SDl3) APIs in the web , to run without the emscripten compiler (hence use with languages like rust that are setup with wasm targets directly)

I have a mixed aproach based on C-FFI , as such whilst I use Rust, i'm also a fan of the SDL2 library , and C-FFI, and the further language experimentation (JAI, Zig, Carbon, cppfront) . My rust project is built SDL2 and GL ,using C-FFI wrappers - this gave me confidence that I was wokring at the same level as C/C++ , and let me move code snippets back and forth with my C++ projects.

some people insist that "emscripten is a hack". and it has certainly fallen out of favour in the rust community - there is a bug in their build preventing the use of threads, that will likely never be fixed. But a lean SDL2 implementation would surely enable a lot of code to run in the web

**Comment by icculus** [comment]
We'll certainly accept patches to improve this, but I think there's a _lot_ of code in SDL that assumes it's being compiled with, and depends on, Emscripten.

**Comment by icculus** [comment]
Actually, just grepping for "EMSCRIPTEN" real fast here...you'd probably have to write (or adapt) most of the backend code (video, audio, joystick, etc), which is non-trivial, but the core of SDL itself seems to not have a lot of Emscripten-specific code in it. There's an EM_ASM macro in the assertion code to call `window.prompt` that could be `#ifdef`d out, but I think that's the worst of it in the high-level code.

So if anyone is feeling eager, feel free to work on this and see how far you get!

**Comment by dobkeratops** [comment]
in my case i would not need the whole of SDL2 . I have considered implementing a subset. but then I figured "hang on surely everyone else that uses sdl2 with c or c++ will have similar requirements". is there a way to do this whilst through the SDL2 community such that this work would not be wasted as a solo effort. an incomplete 'port' might sound bad but it could display a helpful error message to inform of its limitations. The functionality I'm after is definitely possible without emcsripten because many rust projects written against different (rust-native) APIs run in the web.. but I would prefer to stick with a cross-langauge, cross platform API like SDL2.  Unusally for a rust enthusiast I do actually respect what C-FFI has done for the world. I *only* considered rust because it could work direct with C-FFI interfaces. but right now i'm in this awkward place between communities.

**Comment by dobkeratops** [comment]
> We'll certainly accept patches to improve this, but I think there's a _lot_ of code in SDL that assumes it's being compiled with, and depends on, Emscripten.

also i'm not even sure of the boundaries here - so is the SDl2 main project itself adapted for emscripten - I had assumed the emscripten/binarian project would have re-implemented it themselves but evidently not

I could certainly find out the subset I've used. I wasn't using any of the SDL2 *renderer* for example, just window +GL context setup, keyboard, mouse. I do use sound aswell. Joypad is optional - my project switched to keyboard+mouse controls.

my code already has a kind of layer .. which i'd prefer to cut out. "wrappers over wrappers over wrappers.."

**Comment by dobkeratops** [comment]
> The goal would be to either write a new thing that uses whatever Rust prefers for rendering video on the web, 

to clarify:
[1] my project stars out Native, written using 2 C-FFI libraries: SDL2 (window,input), and OpenGL (rendering in the context it gets from SDL2). plus some file IO. 

[2]In turn the *current* web port relies on emscripten to provide those. So how it renders looks exactly like a C/C++ project.
File IO is replaced with "emscripten_wget" but I can replace those aswell, thats not as hard to change as the graphics: I could also make a *native* project that sources its data from asset servers on a network (on my todo list actually)

> assume you still use Emscripten to compile it, as C code that just needs to become a wasm library (or perhaps, an LLVM bitcode library, more accurately?), but the goal is to get it to a state where you link that library to something written in Rust that Just Works without having to link to any Emscripten support libraries.

emscripten to compile it, uyes.

So currently Rust provides 2 ways to compile to the web:
"wasm32-unknown-emscripten" - which has broken threading, and comes with emscripten bloat, that I put up with to get the SDl2/OpenGL APIs
"wasm32-unknown-unknown" - where there is no SDL2 support, and OpenGL works through a Rust wrapper that I dont use. (My graphcis code is written against C-FFI , it is recognizable to a C/C++ programmer)

I'm assuming Wasm itself should allows linking modules compiled in different languages, as it is a JIT system,.

So this support that i'm after could be done in C,C++ rather than Rust, in collaboration with the broader C/C++ community.

I've heard continual claims that "emscripten is what stops people doing serious games in the web, it's a hack". and Rust (unknown-unknown) solves these problems - but there's no reason why that that should *permanently* be the case, and there is huge legacy in C++ , unlike most Rust people I do not demand that the world throws this way, far from it.

I straddle the worlds - Rust is a great langauge but it's taken me years to get used to it, and I need to be able to go back.



>> We're absolutely buried in work now that SDL3 has started, so I can't get into this myself, but if you are feeling bold and want to take a run at it, I'm always available for questions and help!

Thanks taking the time to read my posts and reply .
maybe I can confirm which parts of SDL2 I use.  and I'll get more of an idea of how much effort this would be.

I've heard of other people doing their own WASI stuff to run C++ in the web without emscripten. Maybe  I just need to find these people and connect.. and get some kind of collobarative effort going.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
