### ISSUE TITLE
The mstsc remotely causes the computer that is using the sdl to play the video to crash

### ISSUE THREAD

**Issue by Mangomm** [libsdl-org/SDL#6819]
The mstsc remotely causes the computer that is using the sdl to play the video to crash
1. Configuration
My SDL version is SDL-release-2.26.x(SDL.dll is 2.2.6.1.0).
Computer 1 configuration: graphics card Intel(R)UHDGraphics630, system for win10, CPU Intel(R)CORE(TM)i7-8700 CPU@3.20GHz3.19GHz, memory 32G). The resolution is 3840x1080 and consists of two monitors, which should be noted because it is a widescreen monitor.
Computer 2 configuration: and computer 1 resolution is not the same. The Computer 2 has a resolution of 1920x1080.

2. Outline the development scenario
Hi, I have some problems while developing multi-screen player using sdl. The program has been tested extensively and the problems are related to sdl.
My development scenario is: initially play a certain number of video channels, after 30 seconds, turn off the 30 channels of video, and then restart. And then we keep going.

3. Specific recurrence process
When the problem reappears, the following procedure ensures that the computer crashes:
1) First, I used a multi-screen player developed by sdl to play 32 channels of video on PC 1, and it played normally.
2) However, when I use the computer 2 through the mstsc remote computer 1, the first time I may see the video picture is still, remote again, or minimize the player first and then click the player, then the video will move, make sure the video picture is moving.
3) At this time, use computer 1 to eject the remote mstsc offline (just log in computer 1 again), wait for a while, when the video is closed, computer 1 will crash.

When I looked at the log, sdl destroyed the resources when closing the video, which I found in SDL_DestroyRenderer(_renderer); There was an error and the computer crashed.

4. Problem analysis
My own guess is that the cause of this problem might be:
1) First, the video will play normally on PC 1. When PC 2 is remote, the _renderer size will be changed, for example to 1920x1080;
2) When computer 1 re-logged in, the size of _renderer changed back to 3840x1080. As a result, when shutting down the video, the size of the video was actually only 1920x1080, but the video was destroyed according to 3840x1080, so computer 1 crashed.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
