### ISSUE TITLE
About homebrew Nintendo Switch support (via DevkitPro) backporting

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#6822]
Hello!

Some months ago I copied the branch made by other people to make SDL2 work on Nintendo Switch using the DevkitPro SDK:

https://github.com/Wohlstand/SDL/tree/switch-sdl2-2.0.14-dev

(In addition to that, I made a small bunch of my own fixes to resolve a touchscreen doesn't work, and switched the sound to work with Audio Out instead of Audio Render for better stability of the sound output)

So, as the title says, it's based on SDL 2.0.14 and wasn't updated yet. However, I think, I could backport it over the latest SDL2 (and possibly, over WIP SDL3), however, I have the next questions:
- How I could avoid the possible collision with the official Nintendo SDK support? Should I rename certain modules placed at the tree of that branch to prevent the possible collision, or it's already fine as-is to work?
- Will you accept the pull requests that add homebrew Nintendo Switch support?

**Comment by Wohlstand** [comment]
@icculus, @slouken, what do you think?

**Comment by icculus** [comment]
I will say that SDL's official Switch port was done by me, under my own NDA with Nintendo, and I would rather not upset them by putting a homebrew version for their current generation console in the main repo.

I can't control what anyone does in a fork, though.

**Comment by Wohlstand** [comment]
Then, I think, the homebrew Switch support could be a separately maintained plugin then (in the scope of #6781 this idea). So, if I understood reasonably, the homebrew Switch support could be added officially here once Nintendo will use their future console generation and this will turn into EOL as was happening with Wii/WiiU/3DS. Am I right?

**Comment by crudelios** [comment]
I would love to see updated unofficial Nintendo Switch support.

The game I'm contributing to supports Nintendo Switch and the devkitpro port is starting to show its age.

And though I'm not an SDL developer, I can say the unofficial PSVita port was added to the SDL repo last year, so that tells you that it's possible that eventually in the future the unofficial switch port is added too.

**Comment by Wohlstand** [comment]
I think, I'll try to backport Switch support from that SDL 2.0.14 to the latest SDL2. That shouldn't be a problem. I'll make a shot in some days on the week.

**Comment by Wohlstand** [comment]
This issue is suitable to be a discussion rather than a task to do. Maybe you'll give it a "question" label? Anyway, all had been answered to me by @icculus .
