### ISSUE TITLE
RFE: gstreamer as output back-end

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#6832]
Hi.

gstreamer can be used as an output
back-end for video and audio. This
will allow any SDL app to capture
its output to the video file.
Have you considered implementing
something like that?

**Comment by slouken** [comment]
No, but you're welcome to add one and submit a PR.

**Comment by stsp** [comment]
In that case it wouldn't be much
different for me than to code it directly
into my app - same amount of work or
even fewer.
Since I want to save my time and get
multiple features coded in parallel (rather
than me alone coding each sequentially),
I can instead donate via patreon for such
activity. :)
Please let me know (here or by e-mail)
if that can help. Though I'd prefer to donate
for #6831 instead.
