### ISSUE TITLE
SDL3 Request: separate SDL_Init*/SDL_Quit*

### ISSUE THREAD

**Issue by dustdfg** [libsdl-org/SDL#6840]
Hello!

I don't know if it is possible to create something like SDL_init.h that doesn't include all headers but only SDL_Init*/SDL_Quit*.
I think it will be good to have separate header for it

**Comment by icculus** [comment]
What's the reason to have just init/quit in its own header? Is it causing problems to include SDL.h?

**Comment by dustdfg** [comment]
> What's the reason to have just init/quit in its own header? Is it causing problems to include SDL.h?

Not to include all unnecessary headers ...? I am not sure but it seems so

**Comment by icculus** [comment]
Oh, and the idea is that if one only wants video functions they can include SDL_video.h, etc, but the Init calls are in SDL.h which includes everything, right?

That's not a bad point, we should probably look at this.

**Comment by dustdfg** [comment]
> Oh, and the idea is that if one only wants video functions they can include SDL_video.h, etc, but the Init calls are in SDL.h which includes everything, right?
> 

Yes, I meant exactly it

**Comment by dustdfg** [comment]
@icculus I think that it also will be good for SDL2.28 because it doesn't break compatibility
