### ISSUE TITLE
make[1]: *** [Makefile:563: build/SDL_RLEaccel.lo] Error 1 when building for aarch32

### ISSUE THREAD

**Issue by Ntemis** [libsdl-org/SDL#6843]
batocera@2494eaf3df45:/cha/build/sdl2-2.24.2$ /cha/host/bin/arm-buildroot-linux-gnueabihf-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -g0 -D_FORTIFY_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DUSING_GENERATED_CONFIG_H -Iinclude -I/cha/build/sdl2-2.24.2/include -idirafter /cha/build/sdl2-2.24.2/src/video/khronos -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=24 -DSDL_BUILD_MICRO_VERSION=2 -Wall -fno-strict-aliasing -fvisibility=hidden -Wdeclaration-after-statement -Werror=declaration-after-statement -I/cha/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/pipewire-0.3 -I/cha/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/spa-0.2 -D_REENTRANT -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 -I/cha/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libdrm -Igen -D_REENTRANT -DHAVE_LINUX_VERSION_H -c /cha/build/sdl2-2.24.2/src/video/SDL_RLEaccel.c -o build/SDL_RLEaccel.o
{standard input}: Assembler messages:
{standard input}:8521: Error: co-processor offset out of range
batocera@2494eaf3df45:/cha/build/sdl2-2.24.2$

**Comment by nadenislamarre** [comment]
fixes if we disable rle/sdl lean and mean

```
/* A few defines to reduce SDL2 footprint.
   Only effective when library is statically linked.
   You have to manually edit this file. */
#ifndef SDL_LEAN_AND_MEAN
define SDL_LEAN_AND_MEAN               1
#endif
```

but i don't know the impacts

**Comment by nadenislamarre** [comment]
same error with version 26.1

**Comment by 1bsyl** [comment]
sounds like a compiler issue ? 
try to comment out function implement in SDL_RLEaccel.c to find the culprit

**Comment by 1bsyl** [comment]
instead of fully using SDL_LEAN_AND_MEAN, you simply 
#define SDL_HAVE_RLE 0

and there will be no RLE support

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
