### ISSUE TITLE
Hover and focus effects of Wayland titlebar are broken for lazy redraw apps

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#6847]
Hover and focus effects of Wayland titlebar are broken for lazy redraw apps. It seems like the titlebar just expects that whenever it changes visible items, surely the app will refresh and redraw in the next milliseconds no matter what. This seems conceptually wrong since while SDL2's event poll mechanism isn't ideal for lazy redraw, I don't think anything in the documentation declares that lazy redraw is disallowed. Therefore, the titlebar simply cannot assume the app will redraw it unconditionally in an always timely manner without any notification to do so.

**Problem seen on SDL2 version:** SDL2-2.26.0-1.fc36

**Seen on Linux distribution:** Fedora 36

**Seen on desktop:** GNOME 3 Wayland

**Comment by flibitijibibo** [comment]
Might be similar to #6461 - I thought libdecor updated separately from our surface but it seems not!.

**Comment by slouken** [comment]
@Kontrabant, is there anything we can do here?

**Comment by Kontrabant** [comment]
libdecor subsurfaces are synchronous, so the application ultimately has to redraw when asked.  The current version of the Wayland backend sends expose all cases where it should, but ultimately the application has to redraw when asked, and if it doesn't, that's out of our hands.

**Comment by ell1e** [comment]
What does the "when asked" mean here? I'm not aware of libdecor asking me to redraw somehow. My own UI stuff of course has a way to query that, but it's not like libdecor is sending me events that indicate it wants to redraw (or is it?).

**Comment by Kontrabant** [comment]
The `.commit` callback in `libdecor_frame_interface` is called when the client needs to redraw.

>The window decoration asked to have the main surface to be committed. This is required when the decoration is implemented using synchronous subsurfaces.

**Comment by slouken** [comment]
Do we have that wired up to the SDL expose event?

**Comment by Kontrabant** [comment]
Yep.

**Comment by ell1e** [comment]
Ah, so an SDL2 app needs to redraw when it gets the expose event and I'm probably not doing that then? Oops, that might be possible, seems like this is my own bug in that case :sob: hah. Sorry!

**Comment by Guldoman** [comment]
> The current version of the Wayland backend sends expose events in all cases where it should

@Kontrabant is that supposed to happen on focus lost too? Or should we just redraw on `SDL_WINDOWEVENT_FOCUS_LOST`?
