### ISSUE TITLE
Blurry high DPI output on Windows with DPI awareness set

### ISSUE THREAD

**Issue by GranMinigun** [libsdl-org/SDL#6853]
Originally reported here: https://github.com/dosbox-staging/dosbox-staging/issues/2135

On an up-to-date Windows 10 system with RTX 3060 card, with both Windows DPI awareness/scaling hints set, it seems there's still scaling performed by the OS when DPI scaling is enabled in system settings. I'm not able to reproduce that in Win11 VM, so decided to ask here if maybe you can.

Attaching code snippet and archive with compiled program (or grab the latest CI build of DOSBox Staging, it does the same thing). On the screenshot, the same program was launched, at 125% scaling set in system. On the right I forced scaling to be performed by system, to demonstrate the reproduction scenario. The program was compiled in MSYS2 environment, with Clang, debug symbols included, SDL 2.26.1 statically linked: [dpitest.zip](https://github.com/libsdl-org/SDL/files/10268321/dpitest.zip)

![dpitest](https://user-images.githubusercontent.com/11149380/208666935-c6172057-c3d2-486a-85f2-e68c647d36c0.png)

```c
#include <SDL2/SDL.h>

int main(int argc, char* argv[])
{
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_AWARENESS, "permonitorv2");
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_SCALING, "1");
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window* window;
    SDL_Renderer* renderer;
    SDL_SetHint(SDL_HINT_RENDER_VSYNC, "1");
    SDL_CreateWindowAndRenderer(128, 128, SDL_WINDOW_ALLOW_HIGHDPI, &window, &renderer);

    SDL_bool exit = SDL_FALSE;
    SDL_Event event;
    while (!exit)
    {
        while (SDL_PollEvent(&event))
            switch (event.type)
            {
                case SDL_QUIT:
                    exit = SDL_TRUE;
                    break;
            }

        SDL_SetRenderDrawColor(renderer, 0xfc, 0xfc, 0xfc, 0xff);
        SDL_RenderClear(renderer);

        SDL_Rect rect = {};
        SDL_GetWindowSizeInPixels(window, &rect.x, &rect.y);
        rect.w = rect.x * 0.5;
        rect.h = rect.y * 0.5;
        rect.x *= 0.25;
        rect.y *= 0.25;

        SDL_SetRenderDrawColor(renderer, 0x00, 0x00, 0x00, 0xff);
        SDL_RenderDrawRect(renderer, &rect);
        SDL_RenderPresent(renderer);
    }

    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
```

**Comment by Kontrabant** [comment]
Are you using the software renderer by any chance?  The software renderer is not DPI aware, so things will be scaled up on output and thus blurry.

**Comment by GranMinigun** [comment]
No, it was checked against different renderer drivers and OpenGL context, same result.

**Comment by ericwa** [comment]
I'm not repro'ing this with the attached `a.exe` on Windows 11 - I get a crisp single-pixel-thick box with the OS scaling set to 125% or 150%.
![Screenshot 2022-12-24 144725](https://user-images.githubusercontent.com/239161/209451813-6b87643b-cea9-443f-bb38-a118344f1094.png)
- Not a VM. Windows 11 22H2
- NVIDIA 1070 Ti, driver 527.56

**Comment by GranMinigun** [comment]
False alarm. It was either a wrong build of DOSBox Staging or another "resolved by reboot" kind of issue.
