### ISSUE TITLE
Add an event for double clicks

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#686]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2012-10-21 10:28:07 +0000, Sik wrote:

> I suggest adding an event for when the user performs a double click. Should be self-explanatory. Whenever possible, the double click event should respect the system settings for the maximum delay and distances allowed (e.g. by using the OS's own events), while elsewhere it may have to be faked.
> 
> For when it's faked, do you think a maximum delay of 500ms and a maximum distance of 1% of the screen resolution (take the shortest dimension) are good enough?
> 
> PS: should this be "enhancement" or "API change"?

On 2014-01-30 22:59:17 +0000, Philipp Wiesemann wrote:

> A "clicks" field was added for mouse button events here:
> https://hg.libsdl.org/SDL/rev/658b461d81be
> 
> I guess this will be part of SDL 2.0.2 (although not listed in WhatsNew.txt yet).

On 2014-03-01 18:36:35 +0000, Sam Lantinga wrote:

> Yup, I'll add it to the WhatsNew.txt file today.

**Comment by dbechrd** [comment]
Is this actually implemented? It was closed, but with no PR. How do I use it?

**Comment by icculus** [comment]
Yeah, this predates the project being on GitHub. This issue was migrated from a closed bug report on our old Bugzilla, and that hg.libsdl.org link above will take you to the equivalent commit on GitHub!
