### ISSUE TITLE
When a floating SDL2 wayland window with cairo decoration touches the top of the screen, it's impossible to resize it vertically from the top

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#6860]
When a floating SDL2 wayland window with cairo decoration touches the top of the screen, it's impossible to resize it vertically from the top. Let me demonstrate, this might sound confusing:

[sdl2cairowaylandborderbug.webm](https://user-images.githubusercontent.com/64124388/208941915-0eaa71ab-c17f-4843-816c-50a426ae9cf7.webm)

As you can see, "normal" windows like Firefox here in the background will have the resize cursor change to diagonal and allow resizing on a vertical axis as well when the top of the window touches the top of the screen. Not so the SDL2 window, as you can see it will only ever allow horizontal resizing which means the window is basically way more stuck/sticky to the top of the screen with no obvious way to resize it downward. It just feels weird.

**Affected SDL2 version:** SDL2-2.26.0-1.fc37 (and libdecor-0.1.1-1.fc37)

**Linux distribution that was tested on:** Fedora 37

**Desktop environment:** GNOME 3 Wayland

**Comment by Kontrabant** [comment]
SDL can only control move/resize zones within the window itself via the hittest API.  Any behavior involving the decorations is dictated by libdecor and there's nothing SDL can do about it.

**Comment by ell1e** [comment]
I forwarded the issue to here now: https://gitlab.freedesktop.org/libdecor/libdecor/-/issues/62 Hopefully that's the correct place.
