### ISSUE TITLE
Including SDL to a new project - CMake

### ISSUE THREAD

**Issue by dilson-pieve** [libsdl-org/SDL#6861]
I followed the steps presented here [SDL - Cmake](https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md).
It shows this error message when I try to **build** my project with the command `cmake --build .`:

```sh
MSVCRTD.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl in
voke_main(void)" (?invoke_main@@YAHXZ) [D:\cpp\DemoSDL\DemoSDL\build\mygame.vcxproj]
D:\cpp\DemoSDL\DemoSDL\build\Debug\mygame.exe : fatal error LNK1120: 1 unresolved externals [D:\cpp\DemoSDL\DemoSDL\bui
ld\mygame.vcxproj]
```

- `CMakeLists.txt` file is exactly the one showed in the link above.

 ```c
 // mygame.c file
 #include <stdio.h>

int main()
{
	printf("Hello, Wold\n");
	return 0;
}
```

The project directory has the `CMakeLists.txt`, `mygame.c` file and just in case I added the `SDL3.dll`.

From the project directory, I tried to build it using the following commands:
```sh
mkdir build
cd build
cmake ..
cmake --build . 
```
SDL was successfully installed using the command` cmake --install .`. 

My system:
Windows 11 Home
Visual Studio 2022 17.3.6

**Comment by madebr** [comment]
In SDL3, you need to add `#include <SDL3/SDL_main.h>` to the source file containing your `main` function (below `#include <SDL3/SDL.h>`).
This header will create a platform appropriate entry function, calling your application's `main` function.

**Comment by dilson-pieve** [comment]
It works after
.Added `#include <SDL3/SDL_main.h>`
.Added SDL3.dll inside the project directory.

Thank you very much!
