### ISSUE TITLE
Add event categories

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6869]
> We probably want the event category stuff as a part of this PR. I think adding the category to the event structure is a good idea.

_Originally posted by @slouken in https://github.com/libsdl-org/SDL/issues/6863#issuecomment-1362484255_

Basically the idea is either we add a `category` enum to all events:

```c
enum SDL_Event_Category {
    SDL_EVENTCATEGORY_WINDOW,
    SDL_EVENTCATEGORY_DISPLAY,
    SDL_EVENTCATEGORY_JOYSTICK
    SDL_EVENTCATEGORY_MOUSE,  // maybe _INPUT? idk.
    // etc
    SDL_EVENTCATEGORY_USER
};
```

...or we provide an API that returns this:

```c
SDL_EventCategory SDL_GetEventCategory(SDL_EventType t);
```

I'm leaning towards the second option at the moment:

- We don't have to touch every place we generate events to add it.
- Events don't get larger.
- You only pay for it (with a function call) if you need it.
- We don't have to worry about apps using SDL_PushEvent forgetting to set the category field, or setting it incorrectly.

**Comment by slouken** [comment]
I like the second option as well. We can remove the *_FIRST and *_LAST  constants I added with this change as well.

**Comment by icculus** [comment]
I'll take a run at this later today.

**Comment by icculus** [comment]
Ugh, I dunno, having started on this, I'm wondering if there's a lot of value in supplying this...apps that care could provide this function as a single switch statement themselves, and if they decide the categories should be "mouse" and "keyboard" and "window" and "display" but we thought it should be "input" and "video" then they'd have to write their own anyhow.

**Comment by nfries88** [comment]
> Ugh, I dunno, having started on this, I'm wondering if there's a lot of value in supplying this...apps that care could provide this function as a single switch statement themselves

biggest value would be to constrain the events you see in the queue, ie SDL_PeepEventsByCategory would be slightly better than the current in-range SDL_PeepEvents. Could be some value in SDL_PollEventByCategory too, for example to preserve unused events in a custom modal loop without having to use SDL_PeepEvents
