### ISSUE TITLE
Centering a window with the "SDL_WINDOWPOS_CENTERED" flag works a bit wrong on Windows

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#6875]
If we use the `SDL_WINDOWPOS_CENTERED` flag when creating a window, then when the window appears on the screen, it looks centered (tested on Windows 10):

![image](https://user-images.githubusercontent.com/8170730/209362841-7e52cf23-ea3b-44b1-b40b-42e96164c36f.png)

The problem is that the window is centered only horizontally and not vertically — the distance from the top edge of the screen is exactly `30px` smaller than from the bottom. I suspect that SDL's window centering code does not take into account the size of the window border, because the title bar is just `30px` high.

It is also a pity that there is no flag to center the window in the working area of ​​the screen, i.e. also taking into account the position and size of the taskbar. It would be nice if the SDL user could take advantage of something like this instead of implementing it themselves.

**Comment by furious-programming** [comment]
This problem may be a bit more complex and not related to the SDL code at all. I noticed a similar window centering issue with the Lazarus IDE — I reported it and one of the developers responded with:

> **Don Siders**:
> It's not obvious from the screenshot whether the task bar is "auto hidden".
> 
> This is a problem for Windows (8.1 at least), because SPI_GETWORKAREA does not exclude the task bar area if it is not visible when called. Not sure what Win 10 and 11 do...

- ["IDE Options" and "Options for Project" windows are centered on the screen without taking into account the taskbar area](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40042#notes)
- [IDE main window: maximization doesnt respect Win10 vertical taskbar](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/36140)

**Comment by ericoporto** [comment]
It looks like `SDL_WINDOWPOS_CENTERED` centers the client area in the screen, so if you have a window where it's external size (including titlebar and borders) is exactly the working area (the screen desktop without the taskbar), the window won't fit in the exact space.

**Comment by ivan-mogilko** [comment]
> It looks like `SDL_WINDOWPOS_CENTERED` centers the client area in the screen, so if you have a window where it's external size (including titlebar and borders) is exactly the working area (the screen desktop without the taskbar), the window won't fit in the exact space. (It will appear with top half of the titlebar cutoff on top, with some open area below, more noticeable when taskbar is positioned at either left or right)

Yes, apparently it uses `SDL_GetDisplayBounds` and not `SDL_GetDisplayUsableBounds` when centering:
https://github.com/libsdl-org/SDL/blob/d5b5e524af010d51437470255d5ac848996eeabd/src/video/SDL_video.c#L2343

Also, I may be understanding something wrong, but I've been experimenting with `SDL_SetWindowPosition` lately, and it *seems* like it aligns the client rect to the given position, rather than the "external" top-left corner of the border.

**Comment by slouken** [comment]
We just changed window centering to center the client area in the usable display bounds. If you want a different centering algorithm you're welcome to specify the window position when creating the window.
