### ISSUE TITLE
Discussion: rename SDL event types?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6877]
Half related to #6869 #6772 . but shouldn't then event be named more like `SDL_EVENT_* `:
`SDL_EVENT_WINDOW_CLOSE` for instance, instead of `SDL_WINDOWEVENT_CLOSE`.

_Originally posted by @1bsyl in https://github.com/libsdl-org/SDL/issues/6871#issuecomment-1364127152_

**Comment by AntTheAlchemist** [comment]
Why not `SDL_WINDOW_CLOSE`?

_CLOSE is a bad example, but makes more sense for the other events, eg `SDL_WINDOW_HIDDEN`.

**Comment by 1bsyl** [comment]
could be "CLOSED"
but for instance SDL_WINDOW_SHOWN is already a Window Flags. and it SDL_WINDOWEVENT_SHOWN is an event.

**Comment by icculus** [comment]
> SDL_WINDOW_SHOWN is already a Window Flags.

As is SDL_WINDOW_HIDDEN (although I'm about to open a bug about both of these existing).

I do worry that we're making these too verbose, but having everything prefixed with SDL_EVENT_* wouldn't be the worst thing.

**Comment by 1bsyl** [comment]
> I do worry that we're making these too verbose, but having everything prefixed with SDL_EVENT_* wouldn't be the worst thing.

not sure to get the sense of the sentence :) ? are you in favor of SDL_EVENT_* or not ?


- adding SDL_EVENT_ is verbose, but it helps to discriminate ...
- maybe, only for the window Event. (eg changing SDL_WINDOWEVENT to  SDL_EVENT_WINDOW)
  without touching SDL_QUIT, SDL_KEYDOWN, etc.
- SDLE_  ? ( like the SDLK_ we have for keys )

**Comment by stianhoiland** [comment]
My 2c: Yes, it should be named SDL_EVENT_*.

**Comment by nfries88** [comment]
>   without touching SDL_QUIT, SDL_KEYDOWN, etc.
> * SDLE_  ? ( like the SDLK_ we have for keys )

SDLE_ makes me think error codes, maybe SDLEV_

**Comment by AntTheAlchemist** [comment]
I notice "DEVICE" was removed from the gamepad added/removed events, so shouldn't we also do this:

Rename SDL_JOYDEVICEADDED to SDL_JOYSTICKADDED or SDL_JOYADDED
Rename SDL_JOYDEVICEREMOVED to SDL_JOYSTICKREMOVED or SDL_JOYREMOVED
