### ISSUE TITLE
SDL API renaming: SDL_pixels.h 

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6886]
Here are proposed name changes for functions in SDL_pixels.h, per discussion in https://github.com/libsdl-org/SDL/issues/6569
```
SDL_AllocFormat => SDL_CreatePixelFormat
SDL_AllocPalette => SDL_CreatePalette
SDL_FreeFormat => SDL_DestroyPixelFormat
SDL_FreePalette => SDL_DestroyPalette
SDL_GetPixelFormatName
SDL_GetRGB
SDL_GetRGBA
SDL_MapRGB
SDL_MapRGBA
SDL_MasksToPixelFormatEnum => SDL_GetPixelFormatEnumForMasks
SDL_PixelFormatEnumToMasks => SDL_GetMasksForPixelFormatEnum
SDL_SetPaletteColors
SDL_SetPixelFormatPalette
```
Original proposal, changing SDL_PixelFormat to SDL_SurfaceFormat, but which ended up not making sense in some contexts:
```
Structure:
SDL_PixelFormat => SDL_SurfaceFormat

Functions:
SDL_AllocFormat => SDL_CreateSurfaceFormat
SDL_AllocPalette => SDL_CreatePalette
SDL_FreeFormat => SDL_DestroySurfaceFormat
SDL_FreePalette => SDL_DestroyPalette
SDL_GetPixelFormatName
SDL_GetRGB
SDL_GetRGBA
SDL_MapRGB
SDL_MapRGBA
SDL_MasksToPixelFormatEnum => SDL_GetPixelFormatForMasks
SDL_PixelFormatEnumToMasks => SDL_GetMasksForPixelFormat
SDL_SetPaletteColors
SDL_SetPixelFormatPalette => SDL_SetSurfaceFormatPalette
```
@libsdl-org/a-team for discussion

**Comment by icculus** [comment]
> SDL_PixelFormat => SDL_SurfaceFormat

I'm not against this, but are these never meaningful outside of surfaces? And if so, should we just merge this into SDL_Surface?

**Comment by icculus** [comment]
(Rest looks good in any case.)

**Comment by slouken** [comment]
> > SDL_PixelFormat => SDL_SurfaceFormat
> 
> I'm not against this, but are these never meaningful outside of surfaces? And if so, should we just merge this into SDL_Surface?

Format structures are shared between surfaces, so we can't just merge them in, and they're also used as targets for blit mapping.

However, it would totally make sense to move the new structure and related functions to SDL_surface.h.

**Comment by slouken** [comment]
Renaming the pixel format structure looked weird, so I'm leaving that alone. Updating the function list above to match.
