### ISSUE TITLE
SDL API renaming: SDL_rect.h

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6887]
Here are proposed name changes for functions in SDL_rect.h, per discussion in https://github.com/libsdl-org/SDL/issues/6569
```
SDL_EncloseFPoints => SDL_GetRectEnclosingPointsF
SDL_EnclosePoints => SDL_GetRectEnclosingPoints
SDL_FRectEmpty => SDL_IsRectEmptyF
SDL_FRectEqualsEpsilon => SDL_AreRectsEqualF
SDL_FRectEqualsEpsilon => SDL_AreRectsEqualWithinEpsilon
SDL_HasIntersection => SDL_HasRectIntersection
SDL_HasIntersectionF => SDL_HasRectIntersectionF
SDL_IntersectFRect => SDL_GetRectIntersectionF
SDL_IntersectFRectAndLine => SDL_GetRectAndLineIntersectionF
SDL_IntersectRect => SDL_GetRectIntersection
SDL_IntersectRectAndLine => SDL_GetRectAndLineIntersection
SDL_PointInFRect => SDL_IsPointInRectF
SDL_PointInRect => SDL_IsPointInRect
SDL_RectEmpty => SDL_IsRectEmpty
SDL_RectEquals => SDL_AreRectsEqual
SDL_UnionFRect => SDL_GetRectUnionF
SDL_UnionRect => SDL_GetRectUnion
```
@libsdl-org/a-team for discussion

**Comment by icculus** [comment]
SDL_HasRectIntersection -> SDL_DoRectsIntersect  ...?   I don't feel strongly about it, just throwing it out there.

**Comment by slouken** [comment]
> SDL_HasRectIntersection -> SDL_DoRectsIntersect ...? I don't feel strongly about it, just throwing it out there.

I considered that, but I thought the symmetry with SDL_Has* vs SDL_Get* was nice.

**Comment by slouken** [comment]
@libsdl-org/a-team, of all of the renaming proposals this one feels the most clunky. Thoughts?

**Comment by 1bsyl** [comment]
but that should be `SDL_GetRectsIntersection` ?
