### ISSUE TITLE
Will SDL3 move away from OpenGL?

### ISSUE THREAD

**Issue by konsuko** [libsdl-org/SDL#6890]
Sorry if this is a naive question but I could not find any information about this.

I am considering using SDL2 for a new, super small 2D engine that I'd like to be able to export to as many platforms as possible.
I am working on macOS and want to ship to e.g. iOS, so what's bothering me is that Apple deprecated OpenGL a few years ago.
They will "pull the plug" one day and basically make my renderer unusable if I were to use SDL2 with OpenGL, correct?

Will SDL3 aim to address this issue with OpenGL in any way?
I know that everyone loves to hate on Apple platforms (me too), but especially iPhone will likely stay relevant for game development and it looks like OpenGL is just doomed.

Thanks for your time! :)

**Comment by chalonverse** [comment]
Maybe you already know this, but SDL2 has a Metal renderer and it has been the default on IOS/Mac for some time. So if you stick to the SDL_Renderer 2D API you are set.

On the other hand, if you mean you intend to write your own custom OpenGL code for the 2D engine then yes, you may potentially run into the deprecation issue.

As for future plans for SDL 3 and rendering, you may want to read this: https://github.com/libsdl-org/SDL_shader_tools/blob/main/docs/README-SDL_gpu.md

**Comment by konsuko** [comment]
@chalonverse Thanks for your reply! I did not know that SDL2 has a Metal renderer.

That document about the upcoming SDL3 renderer/APIs is very interesting, thanks for posting it.
