### ISSUE TITLE
SDL_oldnames.h defining __IPHONEOS__

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6892]
Just hit this in sdl2-compat:

```c
#ifdef __IPHONEOS__
Something_that_only_compiles_on_iOS();
#endif
```

The problem is `__IPHONEOS__` is now defined in SDL_oldnames.h unconditionally (even if `__IOS__` is undefined itself).

Obviously I'm going to update sdl2-compat to use the new symbol, but can we wrap the define in `#ifdef __IOS__` in SDL_oldnames.h?

**Comment by slouken** [comment]
Yup!
