### ISSUE TITLE
[BUG] SDL_WaitEvent isn't safe when event param is NULL

### ISSUE THREAD

**Issue by akk0rd87** [libsdl-org/SDL#6893]
Take a look at SDL_WaitEvent func in src/events/SDL_events.c at both branches release-2.26.x and main.

https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_events.c#L945
https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_events.c#L1057
https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_events.c#L1115

numevents param always passed as 1 without checking if event is not NULL.

I get an app freeze on Android and iOS when SDL_WaitEvent(NULL) call and 4 minutes period without any events.
But there is no problem when I pass nonNULL pointer.

**Comment by icculus** [comment]
I'm actually surprised that SDL_WaitEvent(NULL) isn't outright illegal, but since it isn't, yes, this appears to be a bug.

**Comment by akk0rd87** [comment]
I tried to make some fix locally but looks like that's not enough to solve this issue.

![Screenshot_2022-12-29 011747](https://user-images.githubusercontent.com/19515341/209873141-4ac7a137-61c8-4035-8e21-7764ec86f585.png)

**Comment by slouken** [comment]
It's intentional that numevents is 1 but the event can be NULL. I just pushed a related fix in 00b87f1ded0a4fdb6a0bab611171f37eeb0b2ebb, can you verify with the latest code?

**Comment by slouken** [comment]
We haven't heard back on this issue, and I believe that it's fixed in the current code, shipping in 2.28.0. Please feel free to reopen it if that isn't the case.
