### ISSUE TITLE
SDL3: Consider removing SDL_Window* from SDL_Vulkan_GetInstanceExtensions

### ISSUE THREAD

**Issue by Novum** [libsdl-org/SDL#6895]
This isn't used in any of the backends and makes no sense to me. I had to fight this recently. Why does the app have to create a window before initializing Vulkan?

**Comment by hkva** [comment]
FWIW, it's legal to pass a NULL window to SDL_Vulkan_GetInstanceExtensions as of a794126d569ec689b56e4f59c859752257ff71bb (SDL 2.0.9 ?)

**Comment by Novum** [comment]
Even so, fhis doesn't make sense from an API perspective and in my opinon should be removed.

**Comment by slime73** [comment]
Even with that commit, the `SDL_Vulkan_GetInstanceExtensions` backend implementations require `SDL_Vulkan_LoadLibrary` to be called before `GetInstanceExtensions`. When a window is created with the vulkan flag this happens automatically, but if a window isn't created yet it's up to the user to do it themselves which is a little confusing (especially if the window parameter is removed entirely.)

**Comment by slouken** [comment]
The window parameter has been removed, thanks!
