### ISSUE TITLE
SDL_RenderSetClipRect BUG

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#6896]
if rect w  or h  <0   
SDL_RenderSetClipRect  invalid
Render  opengl  opengles  direct3d11
SDL 2.26.1

```c
#include "SDL.h"

int main(int argc, char** argv)
{
    SDL_Init(SDL_INIT_VIDEO);

    SDL_SetHint(SDL_HINT_RENDER_BATCHING, "1");

    SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl");
    SDL_Window* window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 800, 600, 0);

    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);


    SDL_Rect rect = { 0,0,100,-100 }; //if <0
    SDL_Rect rect2 = { 200,200,50,50 };
    int quit = 1;
    while (quit) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {


            switch (e.type)
            {

            case SDL_QUIT:
            {
                quit = 0;
            }
            break;

            }

        }


        SDL_SetRenderDrawColor(renderer, 0x70, 0x70, 0x70, 255);
        SDL_RenderClear(renderer);

        SDL_RenderSetClipRect(renderer, &rect);
        SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
        SDL_RenderFillRect(renderer, &rect2);
        SDL_RenderSetClipRect(renderer,NULL);
        SDL_RenderPresent(renderer);
        SDL_Delay(1);
    }
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
```

**Comment by slouken** [comment]
A negative width or height is always an invalid rectangle, and can't be used for clipping. What is the bug here?

**Comment by baidwwy** [comment]
> 

but direct3d9 and direct3d12 
if<0  then =0

**Comment by baidwwy** [comment]
direct3d9 and opengl present different results

**Comment by slouken** [comment]
Ah good point. 

This is fixed, thanks!

**Comment by baidwwy** [comment]
I think>=0 is more appropriate 😁

**Comment by slouken** [comment]
What does setting a clip rect of width or height 0 do on the various backends?

**Comment by baidwwy** [comment]
> What does setting a clip rect of width or height 0 do on the various backends?

My English is poor, and I can't describe it in English, just to make it unable to display any content

Just suggestions

**Comment by Pentarctagon** [comment]
I'm not at all familiar with the code, but I can at least confirm that it being `rect->w > 0 && rect->h > 0` instead of `rect->w >= 0 && rect->h >= 0` causes a variety of issues for Wesnoth (https://github.com/wesnoth/wesnoth/issues/7864).

Using x11 driver and OpenGL renderer.

**Comment by lukegrahamSydney** [comment]
The "fix" has broken my GUI code. As commented by the guy above me, it should be >= 0 not > 0
A w/h value of 0 should be valid and should totally disable the drawing and is required when coding GUI. It was working perfectly in previous versions.

**Comment by smcv** [comment]
@Pentarctagon, @lukegrahamSydney, are #8228 and #8229 the change you are asking for? Please try whichever one is appropriate for the branch of SDL your games are using (I know Wesnoth is SDL 2, I don't know what  @lukegrahamSydney is developing) and confirm whether it fixes the issue. Or if that change is not what you wanted, please propose a different PR.

**Comment by Pentarctagon** [comment]
Yep, that's the change that fixed Wesnoth's issues when I tested previously.
