### ISSUE TITLE
SDL 2.26 does not work with old style mapping strings

### ISSUE THREAD

**Issue by ilmola** [libsdl-org/SDL#6898]
It seems that SDL 2.26 added a CRC to the gamepad GUID. This broke the support for mapping strings where the GUID is missing the CRC at least when used with SDL_GameControllerAddMappingsFromRW.

Tested with "2dc8:3010 8BitDo 8BitDo Pro 2".

**SDL 2.24.2:**
Using `03000000c82d00001030000011010000,8BitDo Pro 2 Wired Controller,a:b1,b:b0,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b4,y:b3,platform:Linux,`.
SDL_GameControllerAddMappingsFromRW returns 0.
The controller is correctly mapped.

Using `030095acc82d00001030000011010000,8BitDo Pro 2 Wired Controller,a:b1,b:b0,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b4,y:b3,platform:Linux,`.
SDL_GameControllerAddMappingsFromRW returns 1.
The controller is NOT correctly mapped! (As expected since 2.24 does not support CRC in the GUID.)

**SDL 2.26.1:**
Using `03000000c82d00001030000011010000,8BitDo Pro 2 Wired Controller,a:b1,b:b0,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b4,y:b3,platform:Linux,`.
SDL_GameControllerAddMappingsFromRW returns 1.
The controller is NOT correctly mapped! (This is a regression since it worked in 2.24.)

Using `030095acc82d00001030000011010000,8BitDo Pro 2 Wired Controller,a:b1,b:b0,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b4,y:b3,platform:Linux,`.
SDL_GameControllerAddMappingsFromRW returns 0.
The controller is correctly mapped.

**Comment by slouken** [comment]
I just tested this, and the mapping was picked up correctly in both cases here.

When SDL_GameControllerAddMappingsFromRW() returns 1, it means the mapping already exists and may not be overwritten. SDL doesn't have a mapping for that particular VID/PID (my 8BitDo Pro 2 is PID 0x6006), but maybe you have something else that's adding that mapping before that call? Maybe you can debug into that call to see what's happening?

**Comment by ilmola** [comment]
The something else that's adding the mapping is `SDL_PrivateGenerateAutomaticControllerMapping`. 
Adding `return NULL;` as the first line of this function fixes this bug.
With this change in both cases (`03000000c82d00001030000011010000` and `030095acc82d00001030000011010000`) `SDL_GameControllerAddMappingsFromRW` returns 1 and the controller is correctly mapped .

**Comment by slouken** [comment]
That's interesting, because it adds the mapping with priority SDL_CONTROLLER_MAPPING_PRIORITY_DEFAULT, which should be overridden by your call.

**Comment by ilmola** [comment]
It seems that this bug only appears if `SDL_GameControllerAddMappingsFromRW` is called after `SDL_Init(SDL_INIT_GAMECONTROLLER)`. If I call `SDL_GameControllerAddMappingsFromRW` before `SDL_Init` it works correctly in both cases.

**Comment by slouken** [comment]
Okay, I'm investigating, thanks.

**Comment by ilmola** [comment]
Note: I used https://github.com/py-sdl/py-sdl2 to write the test script. So it could in principle a py-sdl2 bug.

**Comment by slouken** [comment]
Yep, it was an SDL bug. Thanks!

**Comment by sezero** [comment]
Cherry-pick to release-2.26.x ?

**Comment by slouken** [comment]
Yes please

**Comment by sezero** [comment]
> Yes please

https://github.com/libsdl-org/SDL/commit/278c78e34c5fc949560a620e6157120b4b32f1dc

**Comment by slouken** [comment]
Thanks!
