### ISSUE TITLE
Full screen with 2560 x 1440 does not cover rightmost column of pixels

### ISSUE THREAD

**Issue by ArchRobison** [libsdl-org/SDL#6900]
This is for Windows 10. When I ask sdl.CreateWindow for full screen, the rightmost column of pixels remains in their original desktop state, i.e. are not included in the window. 

I'm using the Go bindings from https://github.com/veandco/go-sdl2 . Given the nature of the bug, it seems unlikely that layer is causing the problem. Here's the call for initializing the window:
```
			window, err = sdl.CreateWindow("", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED,
				0, 0, sdl.WINDOW_SHOWN|sdl.WINDOW_FULLSCREEN_DESKTOP)
````
I see the problem only for 2560 x 1440 resolution. Other resolutions (I tried 1920 x 1080, 2048 x 1152, 1920 x 1440) work fine.

[Here](https://github.com/ArchRobison/Gophetica/blob/5f3c121930fe5f9386da6f4e009df8d7ed984be8/nimble/host_sdl2.go#L129) is the source file with the call. Any suggestions on fixes or work-arounds?

**Comment by slouken** [comment]
When your desktop is at 2560x1440, do you have desktop scaling enabled? If so, what scaling percentage are you using?

**Comment by ArchRobison** [comment]
Yes, desktop scaling is on. I had forgotten about setting it years ago. Here are results of various scales:

- 100% okay
- 125% okay
- 150% 1 rightmost column of pixels problem
- 175% 2 rightmost column of pixels problem
- 200% okay
- 225% 1 rightmost column of pixels problem

**Comment by ericwa** [comment]
I can reproduce this on the following configuration:

- a single-monitor setup, 2560x1440 pixel monitor, 150% scaling.
- Windows 11
- `release-2.26.1` tag
- `testwm2` demo program launched with: `--info all --fullscreen-desktop`  -> the desktop is visible on a single column of pixels on the right edge of the screen

One workaround is adding `SDL_SetHint(SDL_HINT_WINDOWS_DPI_SCALING, "1");` to the top of `testwm2.c` - this makes SDL DPI aware and makes Windows API's work in pixels, so we can accurately read the monitor size and fit the fullscreen_desktop window to match the monitor exactly.

---

Without setting SDL_HINT_WINDOWS_DPI_SCALING / being DPI aware, Windows tells us (SDL) that the monitor is 1707x960:

```
INFO: Bounds: 1707x960 at 0,0
INFO: Usable bounds: 1707x912 at 0,0
INFO: DPI: 96.000000x96.000000
INFO:   Current mode: 1707x960@165Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
```

and it looks like we get the "correct" size window:

```
INFO: SDL EVENT: Window 1 moved to 0,0
INFO: Window 1 moved to 0,0 (display XB271HU)
INFO: SDL EVENT: Window 1 changed size to 1707x960
INFO: SDL EVENT: Window 1 resized to 1707x960
INFO: Window 1 resized to 1707x960
```

but of course, it still has the crack on the right edge. I'm not sure if we can do anything else on SDL's end to work around this, becuase it looks like we are correctly requesting a monitor-filling window (given the scaled coordinate system Windows is giving us?)

**Comment by slouken** [comment]
SDL 3.0 is fully DPI aware, and you can make your application DPI aware in SDL 2.0 to completely fill the display, using the application manifest.

**Comment by ggggg111** [comment]
@slouken Sorry for re-opening this issue. I would like to ask if it is possible to ignore the windows scaling from SDL. My resolution is 2560x1440 but then, when executing my application, the resolution is 1707x960. How can I make SDL keep the original resolution? Also, this only happens when I'm I compile in Release mode - in Debug mode is fine. Thank you.

**Comment by slouken** [comment]
SDL 3.0 is fully DPI aware, and you can make your application DPI aware in SDL 2.0 to completely fill the display, using the application manifest.

**Comment by ggggg111** [comment]
Thanks for your response. I'm not sure how to use the application manifest, where can I find more info about this?

I've found a workaround:

```c++
SDL_SetHint(SDL_HINT_WINDOWS_DPI_SCALING, "0");
SDL_SetHint(SDL_HINT_WINDOWS_DPI_AWARENESS, "permonitorv2");

if(SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER) < 0)
{
	CONSOLE_LOG("SDL can't be initialized. SDL_Init error: %s", SDL_GetError());
}

int image_format_flags = IMG_INIT_JPG | IMG_INIT_PNG;

if((IMG_Init(image_format_flags) & image_format_flags) != image_format_flags)
{
	CONSOLE_LOG("SDL_image can't be initialized. IMG_Init error: %s", IMG_GetError());
}

SDL_DisplayMode display_mode;
if(SDL_GetDesktopDisplayMode(0, &display_mode) != 0)
{
	CONSOLE_LOG("Can't get desktop display mode. SDL_GetDesktopDisplayMode error: %s", SDL_GetError());
}

CONSOLE_LOG("Window resolution: %dx%d", display_mode.w, display_mode.h);

SDL_WindowFlags window_flags = (SDL_WindowFlags)(SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI);

this->window = SDL_CreateWindow(this->name.c_str(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, display_mode.w, display_mode.h, window_flags);
```

However, the application now is always in fullscreen without setting the fullscreen flag(s) when creating the window.
