### ISSUE TITLE
Remove vi specific comments in the code

### ISSUE THREAD

**Issue by ihhub** [libsdl-org/SDL#6903]
Somehow almost every file in the code contains this line
```c
/* vi: set ts=4 sw=4 expandtab: */
```
I understand the meaning of this line but it should not be present in the code and it belongs only to a specific editor which is very rarely used nowadays. This is a developer responsibility to adjust any editor per their needs, not to put into the code.

**Comment by icculus** [comment]
I'm not a vi user, but this feels like heresy to remove this after almost a quarter of a century.  :)

**Comment by ihhub** [comment]
This is just a suggestion. The collaborators of this repository can decide to keep it this way and close this issue. I just pointed out odd lines in the code with a fresh look.

**Comment by slouken** [comment]
I'm a vi user. :)

**Comment by 1bsyl** [comment]
also one :)

**Comment by madebr** [comment]
We have an [.editorconfig](https://github.com/libsdl-org/SDL/blob/main/.editorconfig), that can configure IDEs.
See [this plug-in for vim](https://github.com/editorconfig/editorconfig-vim).

**Comment by slouken** [comment]
Excellent. I just tried out the editorconfig vim plugin and it works well. I'll go ahead and remove the vim comments in SDL3.
