### ISSUE TITLE
SDL_CreateThreadWithStackSize don't pass stack size on win32 static

### ISSUE THREAD

**Issue by yaz0r** [libsdl-org/SDL#6904]
https://github.com/libsdl-org/SDL/blob/31976323474e6399fb9b62c15bd6b0b7bb49fbae/include/SDL3/SDL_thread.h#L138

should have been 
#define SDL_CreateThreadWithStackSize(fn, name, stacksize, data) SDL_CreateThreadWithStackSize(fn, name, stacksize, data, (pfnSDL_CurrentBeginThread)_beginthreadex, (pfnSDL_CurrentEndThread)_endthreadex)

As it is, calling SDL_CreateThreadWithStackSize without dynamic api won't compile due to the missmatch of arguments

**Comment by slouken** [comment]
Fixed, thanks!
