### ISSUE TITLE
Remove subsystem-specific init/quit functions?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6906]
Are SDL_AudioInit, SDL_AudioQuit, etc, redundant? Should they be removed for SDL3?

They are there, afaik, to let someone initialize a specific subsystem, but we already let people do this with hints, and honestly over large periods of time this is asking for trouble, when they request a subsystem that has since become obsolete.

**Comment by slouken** [comment]
They're not redundant, but maybe they don't need to be public.

**Comment by 1bsyl** [comment]
maybe SDL_INIT_AUDIO etc. should be SDL_SUBSYTEM_AUDIO etc. ..

**Comment by slouken** [comment]
> maybe SDL_INIT_AUDIO etc. should be SDL_SUBSYTEM_AUDIO etc. ..

I think the more common use case will be passing them to SDL_Init(), so I think we can leave them as-is.

**Comment by icculus** [comment]
Also, SDL_Init is just a wrapper over SDL_InitSubsystem...nostalgia, muscle memory and a million tutorials want me to keep SDL_Init, fwiw, but one of them should go.

**Comment by slouken** [comment]
> Also, SDL_Init is just a wrapper over SDL_InitSubsystem...nostalgia, muscle memory and a million tutorials want me to keep SDL_Init, fwiw, but one of them should go.

I disagree, we should keep SDL_Init() and SDL_Quit(), IMHO.

**Comment by 1bsyl** [comment]
maybe SDL_InitSubSystem is too *complex*. And SDL_Init could handles the flags + resolve dependencies. And SDL_InitSubSystem would only be initialize 1 sub system or fails. (in fact, it just replace SDL_AudioInit etc.

**Comment by slouken** [comment]
No, let's leave it as-is for now.
