### ISSUE TITLE
Add branch restriction rules

### ISSUE THREAD

**Issue by ihhub** [libsdl-org/SDL#6909]
I noticed that this repository does not have any branch specific rules which means that anyone with correct access can commit into the `main` branch. This is very dangerous as all commits which directly go into master/main branch **without** passing GitHub Actions checks, can essentially break the build leading to subsequent "hot" fix commits. The correct approach is to allow commits which can be done only as a merge commit from pull requests.

However, this is just an observation point. Please feel free to ignore it and close this issue if it is irrelevant.

**Comment by icculus** [comment]
We're not doing this, sorry. The builds break from time to time, but doing everything through PRs would be a giant hassle.
