### ISSUE TITLE
Implement polygon rendering

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#692]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Proposed patch (0001-extended-sdl-renderer-for-polygon-rendering.diff, text/plain, 2012-11-08 05:21:44 +0000, 22047 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=985)

**Reported in version:** 2.0.0
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2012-11-01 04:10:40 +0000, Martin Gerhardy wrote:

> Having the ability to render polygons in the SDL render interface would be really nice. Something like:
> 
>   int SDL_RenderDrawPolygons(SDL_Renderer * renderer, const float* vertices, const int count);

On 2012-11-08 05:21:44 +0000, Martin Gerhardy wrote:

> Created attachment 985
> Proposed patch

On 2012-11-08 05:22:30 +0000, Martin Gerhardy wrote:

> would something like that be acceptable?

On 2012-11-08 07:46:34 +0000, Sam Lantinga wrote:

> That seems pretty good.
> 
> Have you thought about what would be required for the software implementation?

On 2012-11-08 07:48:02 +0000, Martin Gerhardy wrote:

> hehe - not yet ;) i will do some research. just wanted to ensure that any work on this side isn't for the trash because it won't get accepted upstream.

On 2014-05-10 03:14:41 +0000, Adam M. wrote:

> Shouldn't you be passing an array of points or something, rather than an array of floats? And why floats when other renderer functions use ints? There should be consistency here.

On 2014-06-22 17:19:38 +0000, Sam Lantinga wrote:

> Assigning to Gabriel, since it overlaps work that he's doing.

On 2019-06-04 13:30:28 +0000, Ellie wrote:

> This looks really nice, and it could be an absolute game changer for TEXTURED polygons.
> 
> Imagine something like Diablo 2's fake 3d mode, or simple oldschool-style games that don't need shaders! Currently this can only be done using OpenGL, and of course using that would be faster too with VBO and other functionality being available, but it would be so cool if for really basic but universal 3d effects one could also use SDL2 for simplicity. It's just such an easier way to get started!
> 
> I just wanted to say that if this ever gets picked up and if textured triangles were to be added that support SDL2's texture color mod when rendering, I'd definitely be using it

**Comment by icculus** [comment]
Closing this because we're likely merging @1bsyl's work in #4195 for 2.0.18.
