### ISSUE TITLE
Titlebar is sized differently depending on the compiler I use on Windows (g++ v.s. clang++)

### ISSUE THREAD

**Issue by addiment** [libsdl-org/SDL#6940]
The code used in each is the same. The window width/height is 512x256.
g++ is running under MSYS2 (the MinGW64 subsystem) and clang++ is running natively on Windows using Visual Studio 2022 as a backend (community edition v17.4.3)
For g++, I compiled with this:
```
g++ main.cpp -lmingw32 -mconsole -lSDL2main -lSDL2
```
For clang++, I compiled with this:
```
clang++ '-ISDL2-2.26.1/include' '-LSDL2-2.26.1/lib/x64' -lSDL2main -lSDL2 -o clangMain.exe -Xlinker /subsystem:console main.cpp -lkernel32 -lgdi32 -luser32 -lole32 -lshell32
```

In terms of code, the only flag I applied to the windows is `SDL_WINDOW_SHOWN`. Other than that, their initiation is as standard as it gets. This seems like a problem with g++ (or more specifically, the MinGW libraries) but I'm not sure. It's also easier to describe with images, so:

The window compiling with clang++:
![clangppwindow](https://user-images.githubusercontent.com/63932310/209970301-30647642-951c-4f31-b578-09786d3c5ddd.png)
The window compiling with g++:
![gppwindow](https://user-images.githubusercontent.com/63932310/209970318-2a75b679-a4de-4fbe-8430-7ecf4912f0fc.png)
Side-to-side comparison of the two:
![windowcomparison](https://user-images.githubusercontent.com/63932310/209970324-c581a5d0-7bd9-4e1a-8eed-2ff49aecd71c.png)

Through Win32's [`GetWindowInfo`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowinfo), I retrieved the styles of the two different windows. Oddly, they were the same:
```
Styles: 382337024
Ext. Styles: 536873232
```

Any ideas?

**Comment by ericwa** [comment]
I'm pretty sure it's something highdpi related..

If your sample program is not setting any hints (`SDL_HINT_WINDOWS_DPI_AWARENESS` or `SDL_HINT_WINDOWS_DPI_SCALING`), both programs would normally be DPI unaware (OS-scaled).

If you right click the .exe's and go to "Properties -> Compatibility -> Change high DPI settings" are any of the settings modified?

![image](https://user-images.githubusercontent.com/239161/209991834-2cc7ed99-63f1-43fd-b6de-91e052ead12a.png)

**Comment by addiment** [comment]
Nope. I tried changing them after checking, and that didn't help either.
