### ISSUE TITLE
Static linking on Windows still requires DLL

### ISSUE THREAD

**Issue by Calhai** [libsdl-org/SDL#6943]
Hey, I'm attempting to static link SDL with a C project but every time I attempt to run it, it complains about the SDL2.dll not being next to the exe. I thought I don't need the dll if I'm static linking? 

I'm using Visual Studio 2022, I have included the header files and also added the SDL2main.lib and SDL2.lib files as linker dependencies. I am using the SDL2-devel-2.26.1-VC release on GitHub.

**Comment by slouken** [comment]
That's not a static build, that's a DLL import library.

I highly recommend linking with SDL dynamically, as that will allow your users to drop in newer SDL with bug fixes in the future long after you've moved on to other projects.
