### ISSUE TITLE
Do we still need SDL_LockJoysticks() in the public API?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6956]
In SDL3, SDL_GetJoysticks() returns a copy of the list to the app, which means they don't need to protect against the list changing while they iterate it.

We probably need to maintain a mutex internally, but does it make sense to make this lock public, especially if it's going to touch not just the list but the delivery of events?

It's trivial for an app to provide its own lock if they deal with the array returned by SDL_GetJoysticks() from multiple threads, but I assume most things won't be touching it from multiple threads in the first place.

**Comment by slouken** [comment]
I removed it, but then I remembered that people might want to lock around getting the list of joysticks and then querying attributes about them. I don't feel strongly either way, but it seems like it's still useful.

**Comment by icculus** [comment]
My thinking is that if they query an instance that has vanished (or is bogus), we should return an error and they should ignore that device. It's probably not useful to provide correct information for a device that is no longer available.

**Comment by slouken** [comment]
Fair enough. I’ll remove it from the public API.

**Comment by slouken** [comment]
Yes, we still need the functions to lock joystick mappings.
