### ISSUE TITLE
Bump event type value for structs that change

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6957]
Right now sdl2-compat just uses the SDL3 event queue, with the assumption that SDL2 apps will see some event types they don't recognize and ignore them, as they would for events that weren't available in their current SDL build, or user-defined types they don't know about, etc.

This lets most things Just Work, and sdl2-compat catches a few events in an event watcher and generates SDL2-compatible stuff from it (window events generate a new SDL_WINDOWEVENT event, SDL2 apps ignore the SDL3 one and see the SDL2-compatible event instead).

We need to do this for events that had their structs change, too.

Let's bump the mouse events to a different value, so SDL3 can have its float fields, and leave a note that the SDL2 event type is reserved.

It's possible this whole system will collapse if SDL_Event itself changes size, but for now it simplifies the sdl2-compat code dramatically.

**Comment by slouken** [comment]
FYI, SDL_Event already changed size, but not in a way that can't be worked around in sdl2-compat.

**Comment by slouken** [comment]
@sezero, is this still helpful or are we in a good state in sdl2-compat?

**Comment by sezero** [comment]
sdl2-compat should be in a good state, but I haven't (or can not) tested every possible event

**Comment by slouken** [comment]
This seems like it's working well!
