### ISSUE TITLE
[Feature Request] Fix the windows out of focus white title bar

### ISSUE THREAD

**Issue by aymen157** [libsdl-org/SDL#6958]
On Windows, when out of focus, the window title bar turns white, which could be extremely frustrating / hurts the eyes (especially in dark environment or at night etc..
Whereas all of the other apps don't (such as Terminal/TextEditors/webbrowsers/etc...)

![disc](https://user-images.githubusercontent.com/53356009/210131402-922c4071-f7fd-42fa-8135-bdce0fd32847.png)
![disc2](https://user-images.githubusercontent.com/53356009/210131421-a5b74335-97f4-400a-8beb-78a26551939d.png)

**Comment by slouken** [comment]
I'm moving this to SDL 3.0, where we plan on adding dark mode support.

**Comment by icculus** [comment]
Apparently this just needs this, sometime after we create the HWND:

```c
BOOL value = TRUE;
DwmSetWindowAttribute(hWnd, DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value));
```

It just says "my UI is dark mode aware, so make the title bar match"...I think it'll do the right thing in light mode, this just gives it permission to respect dark mode.

This only works on Windows 11 (the function exists in Vista and will just report an error for this attribute), and we'd have to #define the attribute value for older SDKs.
