### ISSUE TITLE
[Feature Request] RWop saves filename field

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL#6970]
I was wondering if there was any appetite for adding a file name (+ extension) field to the File RWop.

I think it could be useful to get a RWop struct (from wherever) and be able to get a file name or extension out of it.

**Anecdote 1**
Inside of pygame, we implemented a system to do this, because the RWops get created deep in one place (with lots of Python string decoding mumbo jumbo), and then used in a fully different place, which needs the file extension (for music type or image type, for example).

I implemented this system by using one of the hidden data pointers and mallocing some room for the extension, but I couldn't figure out a way to give a "standard RWop" -- a file RWop -- a custom deletion function to clean up that memory. So we now have a different strategy to get around storing the memory in the RWop directly.

**Anecdote 2**
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicTitle
> Please note that if the music was loaded from an SDL_RWops instead of a filename, the filename returned will be an empty string ("").

Having this field could allow SDL_mixer to get rid of this caveat in their API

**Comment by slouken** [comment]
Sure, that seems like a good idea.

**Comment by icculus** [comment]
So we would do a NULL filename if it doesn't make sense (rwops from a memory buffer)? If someone implements an HTTP rwops, would this be NULL ("this is not a file") or would it be the URL ("this is where the data came from")?

Who is responsible for freeing the string? The `close` implementation, presumably, so the implementation using a string literal knows not to free it at all.

Maybe we just add an extra void pointer to the struct that adds can use to attach arbitrary data that the implementation leaves alone?

**Comment by icculus** [comment]
Tossing this into 3.2 because if we do this, it's going to be an ABI change.

**Comment by Starbuck5** [comment]
> Maybe we just add an extra void pointer to the struct that adds can use to attach arbitrary data that the implementation leaves alone?

How were you thinking of accessing the data from the RWop?

Maybe this could manifest as a dedicated `char *` in the RWop struct, called `name`. The file implementation would set it to the filename, the custom HTTP implementation could set it to the URL. The implementation is responsible for populating it (or leaving it NULL), and for freeing it (if dynamically allocated)

**Comment by icculus** [comment]
> Also is 3.2 planned to be the first release of SDL3? I was surprised to see that milestone and "3.x" rather than a "3.0" milestone.

This has caused a little confusion, but yes: 3.2.0 will be the first official release (strictly speaking, the thing where we are breaking everything right now is 3.0.0, so there's no question it's not SDL2, and it will not be formally released but if someone built from git we don't risk confusion between "very old development build" and "first SDL3 release"

The 3.2 milestone is for things that must be in place for a first release (everything that breaks API/ABI), 3.x is everything we want to tackle at some point in SDL3.

**Comment by icculus** [comment]
> Maybe this could manifest as a dedicated char * in the RWop struct, called name.

My concern is that if this field means whatever a given implementation feels like it should mean, it's not useful to the app at all.

Which is why it might be better to have a field that the _app_ controls and the implementation never uses, so pygame can put what it needs there and we don't have to formalize this further.

(My previous comment unhelpfully autocorrected "app" to "add" in case that made my point unclear.)

**Comment by Starbuck5** [comment]
Sorry for the late reply icculus.

> Which is why it might be better to have a field that the app controls and the implementation never uses, so pygame can put what it needs there and we don't have to formalize this further.

Pygame could already put the data into one of the `hidden.unknown.data` pointers, the issue was I couldn't find a good way to add a custom `close` function to a `SDL_RWFromFile`-created RWop. Without a custom close function (somehow on top of the existing close function), the data can't be freed when `SDL_RWClose` is called.

**Comment by icculus** [comment]
I think this is solved by 4368f70ff9447f5960e1afa7a2bb878414c50bc, which lets you assign arbitrary key/value pairs to various objects, including SDL_RWops. The values can be any pointer, and there's a destructor callback thing for freeing it later.

**Comment by slouken** [comment]
For example:
```
void SDLCALL SDL_FreePropertyValue(void *userdata, void *value)
{
    SDL_free(value);
}

SDL_SetProperty(SDL_GetRWPoperties(rwops), "file", SDL_strdup(file), SDL_FreePropertyValue, NULL);
```

**Comment by Starbuck5** [comment]
Very cool!

I look forward to using that in the future.
