### ISSUE TITLE
missing SDL_audio.h include in SDL_events.h ?

### ISSUE THREAD

**Issue by mpalomas** [libsdl-org/SDL#6971]
https://github.com/libsdl-org/SDL/blob/7f23d71b6afe92555fd535e875b05ef37f0aa6d3/include/SDL3/SDL_events.h#L489

Hello, I can see `SDL_AudioDeviceID` is used in `SDL_events.h`, and it is only declared (typedef'ed) in `SDL_audio.h`, which is not included by `SDL_events.h`. 

This result in a compilation error at least on my toy project based on main (I am aware the main branch is currently undergoing heavy changes). Had to typedef it in my code right before `#include <SDL_events.h>`.

**Comment by slouken** [comment]
Fixed, thanks!
