### ISSUE TITLE
X11_SafetyNetErrHandler called contineously, stuck, 100% cpu usage

### ISSUE THREAD

**Issue by anvilvapre** [libsdl-org/SDL#6981]
issue occured once in the past. please consider it to improve the stability of libsdl.

originally reported here: https://github.com/OpenRA/OpenRA/issues/19027

relevant information:
- Not reproducable 
- 99.3% cpu time spent in SDL2.SDL.SDL_GL_DeleteContext
- Using gdb to see the thread is stuck in X11_SafetyNetErrHandler, symbols available
- Browsing the source code (version not checked) http://www-personal.umich.edu/~bazald/l/api/_s_d_l__x11video_8c_source.html
- Relevant source line: https://github.com/libsdl-org/SDL/blob/b5a92406ebd6398e334c88303c2e6c83d3a3f806/src/video/x11/SDL_x11video.c#L136
- Noticing that safety_net_triggered == SDL_TRUE
- Breakpoint shows X11_SafetyNetErrHandler is called continesouly, not recursively
- Noticing that orig_x11_errhandler == X11_SafetyNetErrHandler which results in the callback loop

gdb, display original error handler, which points the same function.
(gdb) x orig_x11_errhandler 0x7fc96d8ea220 <X11_SafetyNetErrHandler>:       0x415641f789495741

possible solution/fix/work around:
- SDL should check to see if orig_x11_errhandler does not equal the current function `X11_SafetyNetErrHandler`
- SDL should check if destroy was called from the same thread as init - if relevant/required

platform:
- Ubuntu 20 LTS. (in the past, with the default latest libSDL of that distribution)

**Comment by sezero** [comment]
I don't know whether this is still reproducible: @icculus and/or @slouken should look..

**Comment by anvilvapre** [comment]
it never happend again. i tried reporting it with SDL, not sure if i did.

**Comment by anvilvapre** [comment]
thought this was the original issue in openra project. sorry.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
