### ISSUE TITLE
macOS: mousedown events lost at screen edges in SDL_WINDOW_FULLSCREEN_DESKTOP

### ISSUE THREAD

**Issue by treellama** [libsdl-org/SDL#6994]
Steps to reproduce:

Modify testmouse.c to add the `SDL_WINDOW_FULLSCREEN_DESKTOP` flag to SDL_CreateWindow. Run testmouse, and draw lines from any of the screen edges inwards.

Expected behavior (2.0.22): red lines are drawn each time
Observed behavior (2.24 and up): red lines are rarely drawn

Reverting 56c1481 and 08d17f4 fixes the issue.

Use case:

Aleph One uses raw mouse for mouselook, but during level transitions it releases the mouse to the user. When it regrabs, it cannot recenter the pointer, and if the pointer happens to be at a screen edge (which can happen often as the player was mouselooking before the level transition) then the game gets into a state where primary mouse clicks are not recognized.

**Comment by icculus** [comment]
Ok, so this is a difficult one. MacOS is stealing the mouse clicks at the edge of the screen because fullscreen desktop windows are now resizable and can be tiled with other windows in the fullscreen space.

This was a feature (or misfeature!) of newer macOS releases, and it's desirable to let windows cooperate with this feature...but maybe we need a hint to turn this off.

Alternately: have you considered using SDL_SetRelativeMouseMode instead of warping the mouse cursor, so it doesn't need to be recentered and doesn't ever reach the edge of the screen?

**Comment by treellama** [comment]
We are using relative mouse and raw input while in mouselook. So the pointer is never warped: it will just stay there at the edge, and we don't get any clicks until the user pauses (disabling mouselook), moves the pointer, and resumes.

One proposed workaround was: upon entering mouselook mode, disable raw input, disable relative mouse, recenter the pointer, re-enable raw input and relative mouse. That might work, but it's only necessary for macOS with newer versions of SDL. Windows and Linux have no trouble processing clicks at the edge of the screen, and it's great when you don't have to worry about platform specifics.

**Comment by icculus** [comment]
Okay, I believe this is fixed. Here was my patch to SDL/test/testmouse.c, for comparison:

```diff
diff --git a/test/testmouse.c b/test/testmouse.c
index d1c4edc06..ecfb3e7de 100644
--- a/test/testmouse.c
+++ b/test/testmouse.c
@@ -204,6 +204,13 @@ void loop(void *arg)
         case SDL_KEYDOWN:
         case SDL_KEYUP:
             switch (event.key.keysym.sym) {
+            case SDLK_SPACE:
+                if (event.key.state == SDL_PRESSED) {
+                    //SDL_WarpMouseInWindow(window, SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2);
+                    SDL_SetRelativeMouseMode(SDL_GetRelativeMouseMode() ? 0 : 1);
+                }
+                break;
+
             case SDLK_LSHIFT:
                 isRect = (event.key.state == SDL_PRESSED);
                 if (active) {
@@ -265,7 +272,7 @@ int main(int argc, char *argv[])
     /* Create a window to display joystick axis position */
     window = SDL_CreateWindow("Mouse Test", SDL_WINDOWPOS_CENTERED,
                               SDL_WINDOWPOS_CENTERED, SCREEN_WIDTH,
-                              SCREEN_HEIGHT, 0);
+                              SCREEN_HEIGHT, SDL_WINDOW_FULLSCREEN_DESKTOP);
     if (window == NULL) {
         SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Couldn't create window: %s\n", SDL_GetError());
         return SDL_FALSE;
```

Draw lines with the mouse, get to the edge of the screen, and press the space bar to toggle relative mouse mode. In 2.26, this behaves badly. With 2afb49ba9a2edc361a3b35d8e30be977a5bcc0c4, it handles it correctly.

Note that on an unpatched SDL, the commented-out SDL_WarpMouseInWindow call also fixes the problem, I've just added code to the Cocoa backend to warp the mouse before enabling relative mode, for roughly the same effect.

If the user is pressing the mouse on the edge of the screen when relative mode is enabled, I can't help you: macOS eats that press and the mouse may misbehave until the user releases the press. But for the common case of turning on relative mode without knowing where the cursor is, I think this is fixed.

**Comment by icculus** [comment]
Cherry-picked to SDL3 in 125e7420ecd2b0d1847aef804f53e614fbc68253.
