### ISSUE TITLE
no available video device

### ISSUE THREAD

**Issue by RyuhoW** [libsdl-org/SDL#6995]
>requirement
wsl2
SDL2
OS:Ubuntu22.04.1 LTS on windows11
Shell:zsh 5.8.1
gcc-12(or clang-15)

>installed
libsdl2-dev
x11-apps(I can see xeyes)

>compile command
	gcc-12  -D LUA_USE_POSIX ./lib/lua/src/*.c ./src/*.c -lm  -lSDL2  -o main  && ./main

#include "../lib/lua/src/lauxlib.h"
#include "../lib/lua/src/lua.h"
#include "../lib/lua/src/lualib.h"
#include <SDL2/SDL.h>
#include <stdio.h>

#define FALSE 0
#define TRUE 1
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

int is_running = FALSE;

SDL_Window *window = NULL;
SDL_Renderer *renderer = NULL;

int initialize_window(void) {
  if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
    fprintf(stderr, "Error initialize_window SDL.%s\n", SDL_GetError());
    return FALSE;
  }
  window =
      SDL_CreateWindow(NULL, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                       WINDOW_WIDTH, WINDOW_HEIGHT, SDL_WINDOW_BORDERLESS);
  if (!window) {
    fprintf(stderr, "Error creating SDL window.%s\n",SDL_GetError());
    return FALSE;
  }
  renderer = SDL_CreateRenderer(window, -1, 0);
  if (!renderer) {
    fprintf(stderr, "Error creating SDL renderer.%s\n",SDL_GetError());
    return FALSE;
  }
  return TRUE;
}

void process_input(void) {
  SDL_Event event;
  SDL_PollEvent(&event);
  switch (event.type) {
  case SDL_QUIT: {
    is_running = FALSE;
    break;
  }
  case SDL_KEYMAPCHANGED: {
    if (event.key.keysym.sym == SDLK_ESCAPE)
      is_running = FALSE;
    break;
  }
  }
}

void update(void) {}

void render(void) {}

void destory_window(void) {
  SDL_DestroyRenderer(renderer);
  SDL_DestroyWindow(window);
  SDL_Quit();
}

int main(int argc, char *argv[]) {
  is_running = initialize_window();
  while (is_running) {
    process_input();
    update();
    render();
  }
  destory_window();
  return 0;
}

>Result
Error initialize_window SDL.No available video device

>Tried
DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0(:0.0  and  :1)
LIBGL_ALWAYS_INDIRECT=1
SDL_VIDEODRIVER=wayland(and x11)
I did try that  installed and started vcxsry,I cann`t it

**Comment by icculus** [comment]
My guess is that we're looking for Xlib in some standard Unix locations and WSL puts those files somewhere else, which causes our X11 code to declare X11 isn't available.

**Comment by RyuhoW** [comment]
Can i need link?
I  tried  adding gcc option -lx11, I can`t.
-L  /usr/X11R6/lib 
-L  /usr/include/SDL2
-L  /usr/include/X11 
I've tried adding too.

**Comment by madebr** [comment]
WSL2 is using a standard Ubuntu distro, so the locations should be standard.

Perhaps you are missing the gl libs. Does glxgears work?

**Comment by RyuhoW** [comment]
Yes, I can using glxgears.
❯ glxgears -info
GL_RENDERER   = D3D12 (NVIDIA GeForce RTX 3050 Ti Laptop GPU)
GL_VERSION    = 3.3 (Compatibility Profile) Mesa 22.0.5
GL_VENDOR     = Microsoft Corporation

**Comment by RyuhoW** [comment]
>apt purge  libsdl2-dev

>cd ~
git clone https://github.com/libsdl-org/SDL.git -b SDL2
cd SDL
mkdir build
cd build
../configure
make
sudo make install

>gcc-12  -D LUA_USE_POSIX ./lib/lua/src/*.c ./src/*.c -lm -lSDL2 -DSDL_X11_SHARED=OFF -o main  && ./main

It was  a success.
create winodw does work.
Thank you so mauch.

**Comment by madebr** [comment]
The `-DSDL_X11_SHARED` was meant for the cmake config script, not as a preprocessor definition.

By doing `sudo make install`, you're ignoring Ubuntu's libsdl2 package.

I just ran `objdump -p /usr/lib/x86_64-linux-gnu/libSDL2.so | grep NEEDED` inside a Ubuntu docker which returned:
```
  NEEDED               libasound.so.2
  NEEDED               libm.so.6
  NEEDED               libpulse.so.0
  NEEDED               libX11.so.6
  NEEDED               libXext.so.6
  NEEDED               libXcursor.so.1
  NEEDED               libXinerama.so.1
  NEEDED               libXi.so.6
  NEEDED               libXfixes.so.3
  NEEDED               libXrandr.so.2
  NEEDED               libXss.so.1
  NEEDED               libXxf86vm.so.1
  NEEDED               libdrm.so.2
  NEEDED               libgbm.so.1
  NEEDED               libwayland-egl.so.1
  NEEDED               libwayland-client.so.0
  NEEDED               libwayland-cursor.so.0
  NEEDED               libxkbcommon.so.0
  NEEDED               libdecor-0.so.0
  NEEDED               libc.so.6
```

Which means [sdl2 on Ubuntu is built with `--enable-x11-shared=off`](https://github.com/libsdl-org/SDL/blob/a0991727545967d9e4b54a16f12ae641991a1e76/configure.ac#L1904-L1905).
So I think the issue is not failure to find the X11 libraries.
