### ISSUE TITLE
please allow to set SDL_HINT_AUDIO_RESAMPLING_MODE to "linear"

### ISSUE THREAD

**Issue by fabiangreffrath** [libsdl-org/SDL#6998]
The libsamplerate library provides 5 different converter types, but only 3 of them (i.e. the SRC_SINC_* converters) can be set through SDL's API. In my projects I need fastest-possible on-the-fly conversion of audio samples and libsamplerate's SRC_LINEAR converter fits this purpose quite well. Please make it possible to select this (and possibly even SRC_ZERO_ORDER_HOLD) through SDL's API.

Thanks!

https://github.com/libsdl-org/SDL/blob/bb34441474486f64f69c97bddd54f39adaea73ce/src/audio/SDL_audio.c#L123-L133

**Comment by icculus** [comment]
Note to self: let's cherry pick this to main before closing this issue.

(I'll do this when I get back to a computer shortly.)

**Comment by slouken** [comment]
FYI, in general I've been doing work on main and cherry picking to SDL2, so it's obvious where the main work is being done.

**Comment by icculus** [comment]
Yeah, I wasn't paying attention to the target branch here, that was my bad.
