### ISSUE TITLE
Update copyright for 2023

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7002]
It's that time of the year again, to run the copyright script across every repository.   :)

**Comment by madebr** [comment]
[This godot commit](https://github.com/godotengine/godot/commit/d95794ec8a7c362b06a9cf080e2554ef77adb667) is saying that it is not required for the copyright notice to contain the current year.

**Comment by icculus** [comment]
I'm not a lawyer, but I also don't have reason to believe they have consulted one on the matter, either.

**Comment by slouken** [comment]
We can keep updating the current year. It's a nice milestone. :)

Done!
