### ISSUE TITLE
Question: SDL_RenderGeometry's blending support

### ISSUE THREAD

**Issue by Jack-Ji** [libsdl-org/SDL#7004]
Happy new year everyone!
A quick question, does SDL_RenderGeometry respect blending options set by SDL_SetRenderDrawBlendMode? (assuming I'm not using texture)

**Comment by 1bsyl** [comment]
happy new year !
It supports blend modes even if you use the software renderer!
https://github.com/libsdl-org/SDL/blob/main/src/render/software/SDL_triangle.c#L839
