### ISSUE TITLE
`SDL_HasGCKeyboard()` not available and not documented (iPadOS)

### ISSUE THREAD

**Issue by MoNTE48** [libsdl-org/SDL#7005]
I was looking for a way to check if the keyboard is plugged in right now, and I can't seem to use the `SDL_HasGCKeyboard` function.

https://github.com/libsdl-org/SDL/blob/7f23d71b6afe92555fd535e875b05ef37f0aa6d3/src/video/uikit/SDL_uikitevents.m#L225-L228

**Comment by flibitijibibo** [comment]
I believe that's an internal function only. Could maybe be added as a 3.0 feature, Wayland is interested in this too #6807

**Comment by MoNTE48** [comment]
@slouken any chance?

**Comment by slouken** [comment]
SDL_HasKeyboard() has been added to SDL3.
