### ISSUE TITLE
cmake: math functions are not found

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#7011]
```
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for atan
-- Looking for atan - not found
-- Looking for atan2
-- Looking for atan2 - not found
-- Looking for atanf
-- Looking for atanf - not found
-- Looking for atan2f
-- Looking for atan2f - not found
-- Looking for ceil
-- Looking for ceil - not found
-- Looking for ceilf
-- Looking for ceilf - not found
-- Looking for copysign
-- Looking for copysign - found
-- Looking for copysignf
-- Looking for copysignf - found
-- Looking for cos
-- Looking for cos - not found
-- Looking for cosf
-- Looking for cosf - not found
-- Looking for exp
-- Looking for exp - not found
-- Looking for expf
-- Looking for expf - not found
-- Looking for fabs
-- Looking for fabs - not found
-- Looking for fabsf
-- Looking for fabsf - not found
-- Looking for floor
-- Looking for floor - not found
-- Looking for floorf
-- Looking for floorf - not found
-- Looking for fmod
-- Looking for fmod - not found
-- Looking for fmodf
-- Looking for fmodf - not found
-- Looking for log
-- Looking for log - not found
-- Looking for logf
-- Looking for logf - not found
-- Looking for log10
-- Looking for log10 - not found
-- Looking for log10f
-- Looking for log10f - not found
-- Looking for lround
-- Looking for lround - not found
-- Looking for lroundf
-- Looking for lroundf - not found
-- Looking for pow
-- Looking for pow - not found
-- Looking for powf
-- Looking for powf - not found
-- Looking for round
-- Looking for round - not found
-- Looking for roundf
-- Looking for roundf - not found
-- Looking for scalbn
-- Looking for scalbn - found
-- Looking for scalbnf
-- Looking for scalbnf - found
-- Looking for sin
-- Looking for sin - not found
-- Looking for sinf
-- Looking for sinf - not found
-- Looking for sqrt
-- Looking for sqrt - not found
-- Looking for sqrtf
-- Looking for sqrtf - not found
-- Looking for tan
-- Looking for tan - not found
-- Looking for tanf
-- Looking for tanf - not found
-- Looking for acos
-- Looking for acos - not found
-- Looking for acosf
-- Looking for acosf - not found
-- Looking for asin
-- Looking for asin - not found
-- Looking for asinf
-- Looking for asinf - not found
-- Looking for trunc
-- Looking for trunc - not found
-- Looking for truncf
-- Looking for truncf - not found
```

Looks like `-lm` isn't used. From CMakeError.log:
```
CMakeFiles/cmTC_f577f.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x4): undefined reference to `atan'
```

The SDL2 branch doesn't seem to have the issue.

CC: @madebr

**Comment by sezero** [comment]
Another interesting note from github CI (ubuntu) logs:
```
-- Looking for pow in m
-- Looking for pow in m - not found
```

**Comment by sezero** [comment]
> Another interesting note from github CI (ubuntu) logs:
> 
> ```
> -- Looking for pow in m
> -- Looking for pow in m - not found
> ```

... And it seems to happen in SDL2 version too (github CI / ubuntu).

**Comment by sezero** [comment]
The striking difference between SDL2 and SDL3 versions is this, i.e. `-lm`
isn't used in `CMAKE_REQUIRED_LIBRARIES`:
```diff
     check_library_exists(m pow "" HAVE_LIBM)
     if(HAVE_LIBM)
-      set(CMAKE_REQUIRED_LIBRARIES m)
+      cmake_push_check_state()
       foreach(_FN
               atan atan2 atanf atan2f ceil ceilf copysign copysignf cos cosf
```

**Comment by sezero** [comment]
Another thing of note (actually off-topic): Math functions need _not_ be strictly searched in libm: they may very well be in libc, too.

**Comment by sezero** [comment]
The LIBM detection failure is due to `-Werror` being added to CFLAGS too early:
`/opt/cmake3.9/share/cmake-3.9/Modules/CheckFunctionExists.c:7: error: conflicting types for built-in function ‘pow’`
I suggest moving `-Werror` addition down below, after all other checks are done,
like the following: (for all SDL3, SDL2, and release-2.26.x branches)
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 49f1bfb..aff7783 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -466,23 +466,6 @@ set_option(SDL_INSTALL_TESTS   "Install test-cases" OFF)
 
 set(HAVE_STATIC_PIC "${SDL_STATIC_PIC}")
 
-if(SDL_WERROR)
-  if(MSVC)
-    check_c_compiler_flag(/WX HAVE_WX)
-    if(HAVE_WX)
-      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /WX")
-      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /WX")
-    endif()
-  elseif(USE_GCC OR USE_CLANG)
-    check_c_compiler_flag(-Werror HAVE_WERROR)
-    if(HAVE_WERROR)
-      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror")
-      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
-      set(CMAKE_OBJC_FLAGS "${CMAKE_OBJC_FLAGS} -Werror")
-    endif()
-  endif()
-endif()
-
 if(SDL_HIDAPI)
   if(HIDAPI_ONLY_LIBUSB)
     set(SDL_HIDAPI_LIBUSB ON CACHE BOOL "" FORCE)
@@ -2835,6 +2818,23 @@ if(NOT HAVE_SDL_TIMERS)
   list(APPEND SOURCE_FILES ${TIMER_SOURCES})
 endif()
 
+if(SDL_WERROR)
+  if(MSVC)
+    check_c_compiler_flag(/WX HAVE_WX)
+    if(HAVE_WX)
+      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /WX")
+      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /WX")
+    endif()
+  elseif(USE_GCC OR USE_CLANG)
+    check_c_compiler_flag(-Werror HAVE_WERROR)
+    if(HAVE_WERROR)
+      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror")
+      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
+      set(CMAKE_OBJC_FLAGS "${CMAKE_OBJC_FLAGS} -Werror")
+    endif()
+  endif()
+endif()
+
 # Append the -MMD -MT flags
 # if(DEPENDENCY_TRACKING)
 #   if(COMPILER_IS_GNUCC)
```

As for math function detection failures in SDL3 _without_ `-Werror`, I suggest the following:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 49f1bfb..84d0820 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1057,6 +1057,7 @@ if(SDL_LIBC)
     check_library_exists(m pow "" HAVE_LIBM)
     if(HAVE_LIBM)
       cmake_push_check_state()
+      list(APPEND CMAKE_REQUIRED_LIBRARIES m)
       foreach(_FN
               atan atan2 atanf atan2f ceil ceilf copysign copysignf cos cosf
               exp expf fabs fabsf floor floorf fmod fmodf log logf log10 log10f
```

@madebr: Are these good?

**Comment by sezero** [comment]
> Another thing of note (actually off-topic): Math functions need _not_ be strictly searched in libm: they may very well be in libc, too.

As for this, I suggest the following, for all branches: Good?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 84d0820..59d530f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1057,18 +1057,20 @@ if(SDL_LIBC)
     check_library_exists(m pow "" HAVE_LIBM)
     if(HAVE_LIBM)
       cmake_push_check_state()
       list(APPEND CMAKE_REQUIRED_LIBRARIES m)
-      foreach(_FN
+    endif()
+    foreach(_FN
               atan atan2 atanf atan2f ceil ceilf copysign copysignf cos cosf
               exp expf fabs fabsf floor floorf fmod fmodf log logf log10 log10f
               lround lroundf pow powf round roundf scalbn scalbnf sin sinf sqrt
               sqrtf tan tanf acos acosf asin asinf trunc truncf)
         string(TOUPPER ${_FN} _UPPER)
         set(LIBC_HASVAR "LIBC_HAS_${_UPPER}")
         check_symbol_exists("${_FN}" "math.h" ${LIBC_HASVAR})
         set(HAVE_${_UPPER} ${${LIBC_HASVAR}})
-      endforeach()
+    endforeach()
+    if(HAVE_LIBM)
       cmake_pop_check_state()
       if(NOT VITA)
         list(APPEND EXTRA_LIBS m)
       endif()
```

**Comment by madebr** [comment]
That looks fine.
The use of `CMAKE_<LANG>_FLAGS` should be phased out.

**Comment by sezero** [comment]
> That looks fine.

OK, will push shortly.

> The use of `CMAKE_<LANG>_FLAGS` should be phased out.

I don't know what to do about it?

**Comment by madebr** [comment]
Getting rid of it, requires some refactoring.

Something slightly different, what is the reason you're unable to upgrade to a cmake > 3.9?

**Comment by sezero** [comment]
OK, relevant patches applied to main, SDL2, and release-2.26.x branches.

> The use of `CMAKE_<LANG>_FLAGS` should be phased out.

Leaving that part to you

**Comment by sezero** [comment]
> Getting rid of it, requires some refactoring.
> 
> Something slightly different, what is the reason you're unable to upgrade to a cmake > 3.9?

My current everyday-machine is running on old CentOS-6.10.
Had tried building some newer cmake myself, failed - can not
remember precisely what the error was, possibly some library
missing or some library too old for cmake - so I gave up.

**Comment by madebr** [comment]
@sezero 
Assuming your machine is x86_64, does the following work?
```sh
wget --quiet -P /tmp "https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3-linux-x86_64.tar.gz"
tar xf /tmp/cmake-3.24.3-linux-x86_64.tar.gz -C /tmp
/tmp/cmake-3.24.3-linux-x86_64/bin/cmake --version
```

**Comment by sezero** [comment]
>  Assuming your machine is x86_64,

i686, unfortunately.

**Comment by madebr** [comment]
Assuming you have a modern enough toolchain, does the following build a working cmake?
```
git clone git@gitlab.kitware.com:cmake/cmake.git /tmp/cmake -b v3.25.1 --depth 1
mkdir -p /tmp/cmake/cmake-build
mkdir -p /tmp/cmake/cmake-prefix
cd /tmp/cmake/cmake-build
cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/cmake/cmake-prefix -GNinja
ninja
ninja install
```
Remove `-GNinja` and replace `ninja`  with `make` if you don't have `ninja-build` available.

```
/tmp/cmake/cmake-prefix/bin/cmake --version
```

**Comment by sezero** [comment]
I vaguely remember doing something similar in my past failed attempt. I can
re-attempt later. I'll setup a new machine with a new distro soon, though.

**Comment by sezero** [comment]
>  The use of `CMAKE_<LANG>_FLAGS` should be phased out.

> Getting rid of it, requires some refactoring.

How about moving `-Werror` from compiler's CFLAGS to SDL's own `EXTRA_FLAGS`
like we do for all other warning flags? That'd work for all gcc & compatibles, but don't
know whether MSVC builds through cmake use EXTRA_FLAGS.

**Comment by madebr** [comment]
I'm currently working to get rid of as much variables as possible, and use targets instead.
So no more `EXTRA_FLAGS`, `SDL_LIBS`, ...

**Comment by sezero** [comment]
OK then, not touching.

**Comment by sezero** [comment]
> Assuming you have a modern enough toolchain, does the following build a working cmake?

OK, I managed to build cmake-3.18.6. Using it with SDL_mixer seems to be a pain as compared to autotools.
```
-- Using system libxmp
CMake Error at /home/ozzie/opt/cmake3.18/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find libxmp (missing: libxmp_LIBRARY libxmp_INCLUDE_PATH)
Call Stack (most recent call first):
  /home/ozzie/opt/cmake3.18/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findlibxmp.cmake:17 (find_package_handle_standard_args)
  CMakeLists.txt:665 (find_package)
```
libxmp is installed under `/home/sezero/z1` and setting `PKG_CONFIG_PATH` has no effect,
neither does `LIBXMP_DIR` or `libxmp_DIR` -- sigh....

**Comment by madebr** [comment]
`PKG_CONFIG_PATH` is a hint for the `pkg-config` util, which the current Findlibxmp.cmake does not use.
By default, CMake looks in `CMAKE_PREFIX_PATH` folders, when looking for dependencies.
Configure the cmake project with `-DCMAKE_PREFIX_PATH=/home/sezero/z1`.

**Comment by sezero** [comment]
> `PKG_CONFIG_PATH` is a hint for the `pkg-config` util, which the current Findlibxmp.cmake does not use. By default, CMake looks in `CMAKE_PREFIX_PATH` folders, when looking for dependencies. Configure the cmake project with `-DCMAKE_PREFIX_PATH=/home/sezero/z1`.

Can it handle multiple paths, if yes with colon or semicolon as delimiter?

**Comment by madebr** [comment]
Yes, it expects a cmake list, thus using a semicolon as delimiter.

**Comment by sezero** [comment]
Thanks.

**Comment by sezero** [comment]
Well, it certainly doesn't work with a semicolon (`;`), colon (`:`) works.

**Comment by madebr** [comment]
Well, that certainly contradicts [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html)'s documentation.

**Comment by madebr** [comment]
I always use `CMAKE_PREFIX_PATH`, but looks like that variable is intended to be set by projects.
Users are supposed to set [`CMAKE_FIND_ROOT_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH.html).

**Comment by sezero** [comment]
Well, I did `CMAKE_PREFIX_PATH=/path/1:/path/2 cmake ....` and it worked.
Maybe in a cmake script, it expects semicolons?

Can try `CMAKE_FIND_ROOT_PATH` later.

**Comment by sezero** [comment]
Just tried `CMAKE_FIND_ROOT_PATH="/path/1;/path/2" cmake ...`
with semicolon or colon as delimiter, and with or without the
quotes: no success. `CMAKE_PREFIX_PATH` is good enough for me
for now.

**Comment by madebr** [comment]
You need to surround multiple arguments with double quotes, otherwise bash will interpret everything after the semicolon as a new command.

**Comment by madebr** [comment]
I see what you're doing. You're using `CMAKE_PREFIX_PATH` as an environment variable, which newer CMake releases support. [Then it's indeed using semicolons.](https://cmake.org/cmake/help/latest/envvar/CMAKE_PREFIX_PATH.html)

I assumed you were passing `CMAKE_PREFIX_PATH` as an argument:
`cmake .. -DCMAKE_PREFIX_PATH="/path/1;/path/2"`

**Comment by sezero** [comment]
Huh.. That's good additional information, thanks!
