### ISSUE TITLE
Spinlock implementation is incorrect on some platforms

### ISSUE THREAD

**Issue by elahav** [libsdl-org/SDL#7021]
Hello,

The implementation of user-mode spin locks in `SDL_spinlock.c` results in priority inversion on systems that use priority-based scheduling. Even on an SMP system with N processors, if N threads at priority X are waiting for spin locks held by N threads at a lower priority Y then no forward progress will ever occur. Spin locks can only be implemented by disabling preemption, which normal user-mode threads cannot do.

For the QNX implementation (see pull request 7018) I'd like to use native mutexes, which solve the priority problem, and are actually more efficient than the SDL implementation using GCC atomics and `SDL_Delay()`. The only caveat is that a mutex is 8 bytes in size, while the SDL spin lock type is 4 bytes.

Would it be acceptable to change the type to a 64-bit one, either for all platforms, for 64-bit platforms only, or conditionally for specific platforms?

Thanks,
--Elad

**Comment by slouken** [comment]
Yes, that’s fine.
