### ISSUE TITLE
Since SDL 2.0.18 and up, joystick stop working when SDL loses focus

### ISSUE THREAD

**Issue by leniad** [libsdl-org/SDL#7028]
When the app starts joystick work fine, but when the app loses focus, and take it back, the joystick stop working, but keyboard, mouse, window, etc events still work fine.
I tested SDL 2 versions and something happens between 2.0.16 (this work fine) and 2.0.18 and up, those don't work
I used 'SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS' but still fails.

**Comment by leniad** [comment]
More info!
Fails when I use 'SDL_CreateWindowFrom', if I use 'SDL_CreateWindow' works fine.
Tested on Windows OS 32 & 64 bits

**Comment by slouken** [comment]
I know what’s going on here. If you set that hint before you call SDL_Init, it should solve your issue.

**Comment by leniad** [comment]
Yes! It works!
I read the docs and see '_This hint may be set at any time_' and set it after SDL_Init, I changed before SDL_Init and works fine.
Thank you!

**Comment by madebr** [comment]
I suppose the doc should be updated then?
https://github.com/libsdl-org/SDL/blob/fde78d12f247a776b52b007479e5274d4bd4e3fe/include/SDL3/SDL_hints.h#L602-L613

**Comment by slouken** [comment]
The hint actually works when changed at runtime, I just tested it. I'm not sure what happened in the original report.
