### ISSUE TITLE
Building SDL using mingw and cmake require "vulkan.h"

### ISSUE THREAD

**Issue by ToxicDuckXx** [libsdl-org/SDL#7030]
I am currently using windows, cmake, mingw32 and and trying to build SDL 2.26.2. 
After building the source code with cmake, and running "cmake --build ." I get an error saying- 
./khronos/vulkan/vulkan.h: No such file or directory.

**Comment by madebr** [comment]
When running `cmake --build . --verbose`, does the build command contain `-idirafter "xxx/src/video/khronos" `?
What file is failing to build?
What is the command?

https://github.com/libsdl-org/SDL/blob/d09d0aaab69f1543886dfcf185ff24822eb1284e/CMakeLists.txt#L320

**Comment by ToxicDuckXx** [comment]
The problem was on my end, for some reason the video folder did not contain a khronos dir. I fixed it by re-downloading the source code
