### ISSUE TITLE
Simplification Joystick / Gamepad

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7032]
SDL3, when I plug Logitech device, I get both :  SDL_JOYDEVICEADDED and SDL_GAMEPADADDED.
Event, If I don't open the Joystick (only the gamepad), I still get SDL_JOYHATMOTION events and SDL_JOYBUTTONDOWN.

I wonder whether Gamepad/Joystick code could be more factorized, and/or merged  ?

**Comment by slouken** [comment]
The gamepad is a superset of joystick, so you receive both events. It has always been this way, and you can just not handle joystick events if you don't want them. The instance ID of the joystick is included in the event so you can distinguish between events from open gamepads and open joysticks if you're handling both.

If there's a good reason to change this, I'm open to it, but nobody has reported an issue with this yet.

**Comment by 1bsyl** [comment]
Just thinking of simplification:

the device we could always be opened as a Gamepad when possible. (SDL_IsGamepad() can still tell if this is a gamepad)
(would merge/keep one among SDL_OpenGamepad / SDL_OpenJoystick).
also keep one: SDL_JoyButtonEvent/SDL_GamepadButtonEvent
also keep one: SDL_JoyAxisEvent/SDL_GamepadAxisEvent

not sure if this makes sense

**Comment by slouken** [comment]
No thanks. We're likely to add a similar Wheel API in SDL 3.x, which will need the same split as gamepad and joystick, where you're always able to open one of them as a joystick.
