### ISSUE TITLE
Android backwards compatibility (SDL2.26.x before API30) for BS key reporting

### ISSUE THREAD

**Issue by 312937** [libsdl-org/SDL#7039]
Version/System/Subsystem:
  - SDL2 **2.26.x (2.26.[0|1|2])**
  - Android API < **30**

Problem description:
  - Soft keyboard (Android, `SDL_StartTextInput()`, `DummyEdit` class);
  - Backspace (BS) key will not be reported if nothing (no other key) has been entered before backspace;
  - Hint: `DummyEdit` class is context free (_has no memory_);
  - Initially detected on an API 28 device, reproduced on emulators afterwards.

Resolution status:
  - After a temporary remedy (_revert_ below) had been applied the difficulty could not be reproduced any more (devices, emulators). Though, only elementary debugging was performed. Thus, some caution might be necessary.

Proposed _Remedy_:
1. Source file: `SDLActivity.java`;
2. Function: `public boolean deleteSurroundingText(int beforeLength, int afterLength)`;
3. Change: reverted lines of code from 2.24.x (apperently removed during 2.26.x cleanup);
4. Additonal: added test condition for API30.

>     public boolean deleteSurroundingText(int beforeLength, int afterLength) {
>
>        // ... 20230107: revert back to 2.24.2 (and before) for APIs until 29 (APIs 30 and above work)
>
>        if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.Q) {
>            // Workaround to capture backspace key. Ref: http://stackoverflow.com/questions>/14560344/android-backspace-in-webview-baseinputconnection
>            // and https://bugzilla.libsdl.org/show_bug.cgi?id=2265
>            if (beforeLength > 0 && afterLength == 0) {
>                // backspace(s)
>                while (beforeLength-- > 0) {
>                    nativeGenerateScancodeForUnichar('\b');
>                }
>                return true;
>            }
>        }
>
>        if (!super.deleteSurroundingText(beforeLength, afterLength)) {
>            return false;
>        }
>        updateText();
>        return true;
>     }

**Comment by slouken** [comment]
Thanks for the fix! Please let us know if you found any issues with this change.
