### ISSUE TITLE
DaemonBite-Arcade-Encoder not recognized as controller

### ISSUE THREAD

**Issue by RaymondGrumney** [libsdl-org/SDL#7043]
The [DaemonBite-Arcade-Encoder](https://github.com/MickGyver/DaemonBite-Arcade-Encoder) running on an arduino pro micro isn't recognized by SDL.

Found through setting up controllers in [EmulationStation Desktop Edition](https://es-de.org/).

Workaround was to create a config manually:

```
03002c10412300003680000000000000,Arduino Leonardo,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,-leftx:-a0,+leftx:+a0,-lefty:-a1,+lefty:+a1,lefttrigger:b6,righttrigger:b7,platform:Windows,
```

Above worked great. The first input is lost every time but then it works fine from then on. Don't know if that's an SDL issue or ES-DE though.

**Comment by slouken** [comment]
It looks like this is working for you?
