### ISSUE TITLE
Android Rotation silent behavior change 

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#7076]
https://github.com/libsdl-org/SDL/commit/d52ba78b2968373888fc3e3664967f8fc2e688ce

After this commit, window has to be marked as resizable for the Android app, which is Fullscreen, to be adjusted when the screen is rotated and the device has the rotation unlocked.

It sounds weird having a Fullscreen window be marked resizeable. Is this correct? Is there any consequences on having all my Fullscreen and Borderless Fullscreen for all platforms marked as Resizable?

I would like that, when no orientation hint is passed, that the screen can be rotated (if unlocked) or a new value for `SDL_HINT_ORIENTATIONS` (say OsSensor), even if the window is not marked as resizable - resizable means that it has a handle that the user can resize the window, no?

**Comment by slime73** [comment]
It sounds like the new Android behaviour matches existing iOS behaviour, for what it's worth. IMO keeping them consistent is good.

I also think it makes sense because the resizable flag is meant to control whether the user can resize the window dimensions, which is what happens if the window rotates (and therefore changes dimensions) when the user rotates the device.

> Is there any consequences on having all my Fullscreen and Borderless Fullscreen for all platforms marked as Resizable?

I don't believe so.

**Comment by slime73** [comment]
> My worry is adding the resizable makes the Fullscreen completely unlocked, ignoring the hint

Looking at the code in the commit, I don't think it ignores the hint when resizable is set - it allows the hint to affect more situations.

> The orientation hints should take precedence over being resizable for flipping.

I think this is actually the case in iOS (https://github.com/libsdl-org/SDL/blob/main/src/video/uikit/SDL_uikitwindow.m#L395). So maybe the Android code could be changed a bit again to use that sort of precedence system, or maybe the iOS code should be changed so the resizable window flag is respected more when the hint is used, I'm not sure. Either way I don't think the current Android code restricts the possibilities of what you can do, unless I'm missing something.

> in löve do you know if both Fullscreen modes are resizable there or only in mobile ports?

I'm not sure I understand the question, but love generally has the same behaviour as SDL: the resizable flag sets whether the user has any possibility of resizing the window, but fullscreen also means the window covers the entire screen, so "resizing" in that situation can only mean rotation and only some platforms / systems have the concept of rotating a window (usually mobile devices).

**Comment by ericoporto** [comment]
> I'm not sure I understand the question,

sorry, I asked specifically about the implementation in löve because it's a very battletested codebase. I will just use resizable for mobile platforms in fullscreen for the time being.

> Looking at the code in the commit, I don't think it ignores the hint when resizable is set - it allows the hint to affect more situations.

yes, you are correct, thanks!

> I don't think the current Android code restricts the possibilities of what you can do, unless I'm missing something.

I was just trying to get more information on the intent here, and I haven't been able to test iOS in a device yet, so not super familiar there too. Thanks for the info.

---

OK, I got all information I need, not sure about closing this, so I will let it be for a bit, but if someone feels like closing it's alright.

**Comment by slime73** [comment]
I believe love doesn't use the SDL hint at all right now, it just lets people either set the resizable flag or use the Android/iOS app build configuration to restrict orientations (each of those platforms has their own way of specifying that for built apps).

That said, I don't think there's any particular reason why the hint isn't used. I actually thought I did implement it at one point but maybe it was only when I was first developing the iOS port of love and it never made it into the main repository or something.

**Comment by 1bsyl** [comment]
the commit is 3 yo ! I think the idea of using resizable, was to distinguished from fixed orientation.
(and it has a bug, because `portrait` is also contain in `portraitupsidedown` and also left/right were inversed, but this was fixed recently: https://github.com/libsdl-org/SDL/commit/c4982955b2640a2421288bd09000330a356ff5ec and https://github.com/libsdl-org/SDL/commit/4408e9f957ff75f4282659a9a6b228e8632ae941).
Feel free to submit a pr to improve ...
As @slime73 said, the best is to have the same behavior across platform !

**Comment by ericoporto** [comment]
@1bsyl I agree with having the same behavior across platform, and I think it's ok. 

> the commit is 3 yo

It's been some long years. I will close this to avoid confusion.
