### ISSUE TITLE
Please try to keep the git history sensible

### ISSUE THREAD

**Issue by Akaricchi** [libsdl-org/SDL#7082]
![2023-01-14T11:00:27,689292168+01:00](https://user-images.githubusercontent.com/609016/212466583-54a3d3bc-1268-4c2e-847f-4d88afbc8d6d.png)

As someone who uses SDL a lot and wants to keep up with the latest developments, this is impossible to follow and physically hurts.

What tool are you even using that generates these strange commits and why? Maybe I can suggest a better alternative if you give me some idea of what your workflow is like.

**Comment by madebr** [comment]
[Can we enforce linear history on OSS repos?](https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-linear-history)

**Comment by uyjulian** [comment]
You can use `--no-merges` argument on `git log` to remove merge commits in listing

**Comment by bradallred** [comment]
> You can use `--no-merges` argument on `git log` to remove merge commits in listing

True, but AFIK, there is no way to filter from the WebUI.

**Comment by icculus** [comment]
I think there's probably a value in being able to merge a long-running topic branch without there suddenly being 100 new commits in main from a rebase merge, and without losing all the development history to a squash merge, so I'd say let's not turn on the "forbid all merges to this branch" option.

I don't know what happened in that screenshot, but let's avoid doing that in the future, too.  :)

I'm going to close this issue for now, as I don't think there's more to be done here at this time.

**Comment by slouken** [comment]
My apologies. I'm not sure what in my workflow caused this, but I added a preview step so I don't accidentally push these commits again.
