### ISSUE TITLE
Codeblocks : "Error creating process (error 193) " with SDL2 in DBG

### ISSUE THREAD

**Issue by LudoDeve** [libsdl-org/SDL#7084]
I want to debug a code with codeblocks. It is not possible if I include the SDL2 lib.

The building of the bin/debug/*.exe is ok...but when I run it there is the following message:

Starting debugger: .../bin/Debug/dsl2_test4.exe
done
Setting breakpoints
Debugger name and version: GNU gdb (GDB) 8.1
Error creating process ...\bin\Debug\dsl2_test4.exe, (error 193).
Debugger finished with status 0

============>  It only appears when I add #include <SDL.h> !!!!!!!

Has someone an idea to solve my problem because I would like to debug complex code using SDL2...

example of code:

#include <exception>
#include <string>
#include <iostream>
#include <stdlib.h>
#include <SDL.h>   

int main(int argc, char* argv[])
{
 int a;
 int b = 5;
 a = b+6;
 return 0;
}
I want to run a debug *.exe with "#include <SDL.h>"

I use "codeblocks-20.03mingw-setup" that includes GDB debugger from MinGW-W64 project (version 8.1.0, 32/64 bit,SEH) and SDL2-devel-2.24.0-mingw

SDL2.dll is in the same directoty as the executable. And the .exe runs in debug mode without "#include <SDL.h>"

**Comment by madebr** [comment]
This looks like very similar to this issue: https://github.com/libsdl-org/SDL/issues/6139#issuecomment-1267716841
SDL releases 2.24.1 (or newer) are built with `-gdwarf-4`.

**Comment by LudoDeve** [comment]
it seems different from #6139. But looking at other forums, the problem is solved : I add "#undef main" after "#include <SDL.h>"

thank you for your help.

**Comment by LudoDeve** [comment]
issue closed
