### ISSUE TITLE
3DS: sdl2-config setup incorrectly

### ISSUE THREAD

**Issue by Anh302kay** [libsdl-org/SDL#7088]
I might have compiled the 3DS port incorrectly, but running `'sdl2-config --libs'` will result in it linking with `-lSDL2 -lSDL2 -lm` and not with `-lSDL2main -lSDL2 -lm`.

![image](https://user-images.githubusercontent.com/77185387/212522091-c542ccf0-7745-417d-8d1f-54a81db69826.png)

- I compiled the version in the SDL2 branch following the guide in docs/README-n3ds.md.
- OS: Windows 10 21H2

**Comment by madebr** [comment]
Apparently, we don't support this because running the compiler manually is not supported for n3ds:
https://github.com/libsdl-org/SDL/blob/b47b6e02fd7f427bbd65726c226759d8a1b18b63/.github/workflows/n3ds.yml#L41-L42

@FtZPetruska

**Comment by FtZPetruska** [comment]
> Apparently, we don't support this because running the compiler manually is not supported for n3ds:
> 
> https://github.com/libsdl-org/SDL/blob/b47b6e02fd7f427bbd65726c226759d8a1b18b63/.github/workflows/n3ds.yml#L41-L42
> 
> @FtZPetruska

You're correct, that we're not expecting users to manually invoke the compiler as there are many extra steps to achieve a working binary.

On the other hand, since `SDL2main` is a necessity on 3DS, I do think it's relevant to add it to the pc file and sdl2-config. Is adding `list(INSERT SDL_LIBS 0 "-lSDL2main")` in the 3DS block the correct thing to do?

**Comment by madebr** [comment]
I'm working on this. I think I found a way to completely test n3ds on ci.

**Comment by madebr** [comment]
See #7089

**Comment by FtZPetruska** [comment]
Works great on my end, thank you for your help!

**Comment by madebr** [comment]
No problemo :)
This is also fixed for SDL3 in https://github.com/libsdl-org/SDL/commit/0a1479d58c4f617ffcb84a6977f57d8ddc703662
