### ISSUE TITLE
Type of SDL ID 

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7095]
we have various type of ID

```
SDL_audio.h:typedef Uint32 SDL_AudioDeviceID;
SDL_joystick.h:typedef Uint32 SDL_JoystickID;
SDL_mouse.h:typedef Uint32 SDL_MouseID;
SDL_sensor.h:typedef Uint32 SDL_SensorID;
SDL_thread.h:typedef unsigned int SDL_TLSID;
SDL_thread.h:typedef unsigned long SDL_threadID;
SDL_timer.h:typedef int SDL_TimerID;
SDL_touch.h:typedef Sint64 SDL_FingerID;
SDL_touch.h:typedef Sint64 SDL_TouchID;
SDL_video.h:typedef Uint32 SDL_DisplayID;
SDL_video.h:typedef Uint32 SDL_WindowID;
```

Should we make them more uniform ? with the same invalid id one (currently sometime it's 0, sometime it's -1)? 

I think (not tested) compilers don't warn if you use at some place a SDL_AudioDeviceID instead of a SDL_JoystickID, in a function.
If we fake using a `typedef struct *` (or other thing)  (but keeping ID), maybe that could break at compile time, when there is an API misuse  ?

**Comment by slouken** [comment]
SDL_TimerID, and SDL_TLSID have been switched to use Uint32. SDL_ThreadID has been changed to Uint64.

**Comment by slouken** [comment]
SDL_TouchID and SDL_FingerID have been switched to Uint64, with 0 being an invalid ID.

At this point all of the IDs are either Uint32 or Uint64 and 0 is the invalid value. We could turn them into structure pointers to provide type safety, but that would involve awkward casts at the API surface level to turn them back into numerical IDs, and I don't think we want to do that.

I'll go ahead and close this now, feel free to reopen if I missed something!

**Comment by slouken** [comment]
> not sure, but maybe everything could be Uint32 ...
> eg, SDL_TouchID, SDL_FingerID, SDL_ThreadID ...

No, the underlying representation of those IDs don’t necessarily fit in 32-bits.
