### ISSUE TITLE
Gboard (default keyboard on Android) does not capitalize the first word in a sentence

### ISSUE THREAD

**Issue by antorix** [libsdl-org/SDL#7101]
I apologize if I'm duplicating a known issue, but I suspect this has something to do with SDL. In Kivy applications (Kivy 2.1.0, Android 12) the Gboard keyboard can't capitalize the first word in a sentence after a period, as it normally does in all other apps. Even with this option explicitly enabled, it doesn't work in Kivy.

**Comment by antorix** [comment]
I don't know, Gboard just works by default. Maybe because I'm not typing in Japanese.

**Comment by slouken** [comment]
Capitalizing the first word in the sentence is now the default behavior for SDL3.

Thanks!
