### ISSUE TITLE
Set the default priority level of SDL_LOG_CATEGORY_ERROR to SDL_LOG_PRIORITY_ERROR

### ISSUE THREAD

**Issue by iloveclang** [libsdl-org/SDL#7105]
When trying to print an error with SDL_LogError, it does nothing because there is a mismatch between the default priority level of of SDL_LOG_CATEGORY_ERROR (which is 6 (CRITICAL) for some reason) and SDL_LOG_PRIORITY_ERROR (which is 5).

**Comment by slouken** [comment]
Done!
