### ISSUE TITLE
What’s the point of passing pitch = 0 to surface creation functions?

### ISSUE THREAD

**Issue by JWStaiert** [libsdl-org/SDL#7110]
The various surface creation functions allow the caller to pass in a pitch of zero, and then assigns pitch to the surface struct as is. What’s the reason for this? It breaks caller code that depends on pitch being at least the minimum value for the format. Is there some SDL function where having a zero pitch is necessary?

**Comment by slouken** [comment]
Which function has this behavior?

**Comment by JWStaiert** [comment]
In SDL 3, SDL_CreateSurfaceFrom does and in SDL 2 it’s equivalents do so. If this is not a bug I’d like to know the use case for it.

**Comment by JWStaiert** [comment]
In SDL 2: SDL_CreateRGBSurfaceFrom and SDL_CreateRGBSurfaceWithFormatFrom

**Comment by slouken** [comment]
The function assumes that the application knows what it's doing and will fill in the pitch later.
