### ISSUE TITLE
SDL_CreateRenderer() declaration and definition are not the same.

### ISSUE THREAD

**Issue by iloveclang** [libsdl-org/SDL#7112]
In `SDL_render.h`, on line 191 there is:

`extern DECLSPEC SDL_Renderer * SDLCALL SDL_CreateRenderer(SDL_Window * window, int index, Uint32 flags);`

In `SDL_render.c`, on line 938 there is:

`SDL_Renderer * SDL_CreateRenderer(SDL_Window *window, const char *name, Uint32 flags)`

The difference is in the second argument. One is an int, and the other is a string.
In the header file, people are advised to use -1, and in the other one, NULL is used in one place.

I don't know if this is intentional, and sorry if it is, but it looks suspicious.

**Comment by slime73** [comment]
I think you're looking at a header for SDL2 and the source code for SDL3.

Here's the current header for SDL3 https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_render.h

A number of APIs have changed between SDL2 and SDL3, including SDL_CreateRenderer.
