### ISSUE TITLE
Atari VCS modern controller has some buttons mapped incorrectly when using it in BT mode (Linux)

### ISSUE THREAD

**Issue by WizzardSK** [libsdl-org/SDL#7116]
Using EmulationStation DE I found out that my Atari VCS controller does not work as expected in BT mode.
Right Trigger button and right analog stick has some incorrect mappings. It works good in wired mode.

So I used antimicro tool to find the GUID of my controller and it works correctly using this line:
(I added it to my  ~/.emulationstation/es_controller_mappings.cfg)

`05000000503200000210000000000000128804098,Atari Game Controller,platform:Linux,a:b0,b:b1,x:b3,y:b2,back:b6,start:b7,guide:b8,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,`

With this line it works like expected, all buttons are mapped correctly.

**Comment by slouken** [comment]
Added, thanks!
