### ISSUE TITLE
Konami Amusement Controllers Cause Hang on Enumeration

### ISSUE THREAD

**Issue by PARTYMANX** [libsdl-org/SDL#7118]
When plugging in a Konami Amusement controller (for example, a [Beatmania IIDX Entry Model controller](https://www.konamistyle.jp/products/detail.php?product_id=110744)), SDL will hang.  Specifically, I've run into the issue on Windows machines with Intel CPUs/chipsets (the controllers generally fail to function at all on my AMD machine).  

Running through a debugger, I can see that the hang happens in HIDAPI in HidD_GetSerialNumberString (and the other string queries) in hid_enumerate (in sdl 2.0.16).  From what I know about these controllers, they do not respond to these queries at all.  

I can write a fix myself, but I'm not sure exactly what it should look like.  Should these devices be added to the blacklist or should it skip by vendor ID ([like Valve is here](https://github.com/libsdl-org/SDL/blob/main/src/hidapi/windows/hid.c#L533)) since it seems to affect all of their controllers for now?  I would like these to still function as joysticks for a potential project (it would also be nice for EZ2ON Reboot: R).  Does skipping those queries prevent that?

**Comment by slouken** [comment]
Is it all string queries that cause problems? If you skip those, are they usable as normal joysticks/gamepads?

**Comment by PARTYMANX** [comment]
Yes, all string queries in that function (past the blacklist check) cause issues.  I did just do a build with one of the controllers added to the blacklist and it does preserve joystick functionality in the joystick tester, so that answers my question there.  So the question remains whether to add the vendor ID or each controller (I know the info for all of them except for the Sound Voltex Premium Controller)

**Comment by PARTYMANX** [comment]
Oh, I am also missing data for the Beatmania IIDX Pro Controller (this one is interesting as it has configurable lights but I don't own one to figure out how that works).  From my count this would (currently) affect 8 devices with a possiblity of an arcade-style DDR pad coming that will almost definitely be prohibitively expensive to acquire.  It's probably safest to skip all devices with the vendor ID if that's alright.

**Comment by PARTYMANX** [comment]
Alright, went ahead and made a PR after some more messing with it.

**Comment by slouken** [comment]
Yup, it looks good, thanks!
