### ISSUE TITLE
Joystick/Gamepad isn't working on PS Vita

### ISSUE THREAD

**Issue by ghost** [libsdl-org/SDL#7128]
Reproducible examples:

```
SDL_OpenJoystick(1) returns "Joystick 1 not found".
SDL_OpenGamepad(1) returns "Couldn't find mapping for device (1)".
```

Using 0 won't work either (and goes against SDL_JoystickID minimum value of 1 anyway).

I noticed that VITA_JoystickInit is calling SDL_PrivateJoystickAdded with 0, that is against the SDL_JoystickID minimum value too. VITA_JoystickGetDeviceInstanceID will return an invalid ID when called from SDL_GetDriverAndJoystickIndex, since its iteration on the secondary loop begins on 0.

If I correct this by making SDL_PrivateJoystickAdded be called with 1, VITA_JoystickGetDeviceInstanceID return the received value plus one and removing the minus on the calling of SDL_GetJoystickInstanceID on VITA_JoystickUpdate, the controls work again. But isn't a useful fix, since e.g. SDL_GetJoystickFromInstanceID will return null on receiving an 1, and only return the valid pointer on receiving 0. The data on SDL_joysticks seems to be being initialized wrongly somewhere.

Since there's no way to attach a debugger currently, I couldn't progress further. Hopefully someone more versed on the API can make something out of this report and understand what is going on (┬┬﹏┬┬).

**Comment by slouken** [comment]
Thanks for the report. I have some rearchitecture planned that will take care of this, but it's a ways out on the TODO list.
