### ISSUE TITLE
cannot open source file "SDL2/SDL_main.h" (dependency of "SDL.h")

### ISSUE THREAD

**Issue by FeistierMage-Gabe** [libsdl-org/SDL#7129]
So my code compiles and even runs yet this error still appears and I have no idea how to get rid of it. It's keeping my intellisense from working. I'm on a Mac using vscode. I moved the SDL framework into /Library/Framework/ area and changed my json file to include the whole path to the header folder, pls help.

**Comment by madebr** [comment]
I'm no Apple person myself, but the SDL2.framework need the following compiler arguments:
```
-F/Library/Framework -I/Librar/Frameworks/SDL2.framework/Headers
```
The first argument (`-F`) is needed for `#include <SDL2/...>`, the second (`-I`) to get `#include "SDL.h"` working.

**Comment by FeistierMage-Gabe** [comment]
Ah yes thank you my intellisense works now using

-F/Library/Frameworks

and

-I/Library/Frameworks/SDL2.framework/Headers

in the compiler arguements, thank you!
