### ISSUE TITLE
Should the flags passed to SDL_Init be an enum of their own?

### ISSUE THREAD

**Issue by Lokathor** [libsdl-org/SDL#7133]
Many flags are defined as an enum such as:

```c
typedef enum
{
    SDL_MESSAGEBOX_ERROR                 = 0x00000010,   /**< error dialog */
    SDL_MESSAGEBOX_WARNING               = 0x00000020,   /**< warning dialog */
    SDL_MESSAGEBOX_INFORMATION           = 0x00000040,   /**< informational dialog */
    SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT = 0x00000080,   /**< buttons placed left to right */
    SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT = 0x00000100    /**< buttons placed right to left */
} SDL_MessageBoxFlags;
```

But the flags for `SDL_Init` are still just created with `#define`.

Should they perhaps be grouped into a new `SDL_InitFlags` enum? I should be able to do the PR if this seems like a good idea.

**Comment by slouken** [comment]
This seems like a good idea to me.  @icculus?

**Comment by icculus** [comment]
This is fine with me. Groups them together, makes them real things instead of preprocessor macros.
