### ISSUE TITLE
Team Fortress 2 crash with version 2.26.2

### ISSUE THREAD

**Issue by wantija** [libsdl-org/SDL#7138]
Deleting the binary that comes with TF2 ($PATHTOGAME/bin/libSDL2-2.0.so.0) so it uses the one provided by your system causes the game to randomly crash, usually near the beginning of a match. Using Arch Linux.

**Comment by icculus** [comment]
I'll try to reproduce this here today.

**Comment by hkva** [comment]
This might be related to https://github.com/ValveSoftware/Source-1-Games/issues/4686

**Comment by icculus** [comment]
I wasn't able to trivially reproduce this issue. I guess the question is: is https://github.com/ValveSoftware/Source-1-Games/issues/4686 triggering it, or _just_ deleting the included SDL?

**Comment by wantija** [comment]
Well looks like Arch has updated lib32-libx11 to 1.8.4 and the issue is gone, I guess this is safe to close.
