### ISSUE TITLE
Header search path in Visual Studio project

### ISSUE THREAD

**Issue by jessechounard** [libsdl-org/SDL#7139]
If I understand correctly, what I'm writing about here seems to be the same thing as issue #1967, which was completed, but it looks like the Visual Studio project was recreated during an upgrade and the change was lost.

Here's the gist: I'd like to be able to include the SDL project in my solution, and set it as a dependency of my game, and then it'll be automatically rebuilt when necessary. I could do this with a local copy of SDL that I tweak myself, but it would be much better to use a git submodule that I can keep it up to date.

The problem is that the search path is set to search relative to the `SolutionDir` not the `ProjectDir` so it's searching relative to my solution file, which isn't correct.

The fix is to change `SDL/VisualC/SDL/SDL.vcxproj` to use `$(ProjectDir)/../../src;$(IncludePath)` for "Include Directories" (for all configurations and platforms.) It's not necessary to change any of the output directories, as it's actually ideal that it outputs to the same location as my output files.

If this change is okay, and you'd like me to open a PR, just let me know, I'd be happy to. Thanks!

**Comment by slouken** [comment]
Yeah, go ahead and open a PR for this. Thanks!
