### ISSUE TITLE
[cmake] [SDL3] unsupported configurations for visibility attributes should be detected

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#7146]
From a MinGW build run:
```
/home/sezero/SDL3/src/events/SDL_clipboardevents.c: In function 'SDL_SendClipboardUpdate':
/home/sezero/SDL3/src/events/SDL_clipboardevents.c:41:1: warning: visibility attribute not supported in this configuration; ignored
/home/sezero/SDL3/src/events/SDL_displayevents.c: In function 'SDL_SendDisplayEvent':
/home/sezero/SDL3/src/events/SDL_displayevents.c:57:1: warning: visibility attribute not supported in this configuration; ignored
/home/sezero/SDL3/src/events/SDL_dropevents.c: In function 'SDL_SendDropFile':
/home/sezero/SDL3/src/events/SDL_dropevents.c:77:1: warning: visibility attribute not supported in this configuration; ignored

[... multitude of others ...]
```

Seems to happen after https://github.com/libsdl-org/SDL/commit/fb80608ffffa09bd2004733212f18b8b7c92a05b

Unsupported configurations for visibility attributes should be detected before enabling.
For several other references, see:
https://github.com/libsndfile/libsamplerate/blob/master/src/CMakeLists.txt#L21-L29
https://github.com/libsndfile/libsamplerate/pull/160
http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commitdiff;h=c3549ab805260a7679bc6459612904a3cf3b8ab1
https://lists.gnu.org/archive/html/bug-gnulib/2021-05/msg00117.html

CC: @madebr

**Comment by madebr** [comment]
Does removing the following lines make the warning disappear?
```cmake
    C_VISIBILITY_PRESET "hidden"
    CXX_VISIBILITY_PRESET "hidden"
    OBJC_VISIBILITY_PRESET "hidden"
```

I thought CMake auto-detected the availability of the `-fvisibility=` argument.

**Comment by sezero** [comment]
> Does removing the following lines make the warning disappear?

Yes, because, the compiler visibility switches aren't used then.

If you really want to use tat cmake feature, a lazy solution might be using it
orly for non-windows.

**Comment by madebr** [comment]
Fixed by https://github.com/libsdl-org/SDL/commit/4ec3a5ac27a808ad91eb680cd96a4506b29c4b97

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL/commit/3bf86c0eca0607f160decaacf2905c26df584fcb as a follow-up patch.

BTW, the satellite libraries seem to need similar changes in both SDL2
and SDL3 branches.

**Comment by madebr** [comment]
Use of `__attribute__ ((visibility("default")))` is not controlled by CMake, but driven b the GNU version:
https://github.com/libsdl-org/SDL/blob/597031135337056dc804d805e1a93eaab7bb8d87/include/SDL3/SDL_begin_code.h#L61-L65
The only thing in CMake's hand is the `-fvisibility=hidden` argument.

**Comment by sezero** [comment]
The code already relied on GCC:
```
      #if !defined(__GNUC__) || __GNUC__ < 4
      #error SDL only uses visibility attributes in GCC 4 or newer
      #endif
```
For other visibility implementations, we should add e.g. `-xldscope=hidden`
of SunPro and the like if they are still really relevant. Don't know of a
better solution here?

**Comment by madebr** [comment]
If you have access to this compiler, you can check the current compiler through [`CMAKE_<LANG>_COMPILER_ID`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html).
```cmake
if(CMAKE_C_COMPILER_ID MATCHES "SunPro")
  check_c_compiler_flag("-xldscope=hidden" COMPILER_SUPPORTS_HIDDEN)

  # add this when cmake does  properties are not supported
  if(COMPILER_SUPPORTS_HIDDEN)
    target_compile_options(sdl-build-options PRIVATE "-xldscope=hidden")
  endif()
endif()
```

**Comment by sezero** [comment]
> If you have access to this compiler, 

Nope, I don't, unfortunately.

What precisely is the issue we have, actually?

**Comment by madebr** [comment]
Looking at your initial patch, I don't think the cmake script was doing anything wrong.
The logic to use `__attribute__((visibility("default")))` is all done using macro `ifdef`'ery.
I would revert all of them.

I would count on CMake to know how to configure visibility on "exotic" compilers and assume it knows about `-xldscope=hidden`.

**Comment by sezero** [comment]
> Looking at your initial patch, I don't think the cmake script was doing anything wrong.

I didn't say that it was

> The logic to use `__attribute__((visibility("default")))` is all done using macro `ifdef`'ery. I would revert all of them.

That addition detects whether gcc acttually supports the attribute: Newer gcc doesn'
warn in certain cases, the added code catches that.

**Comment by madebr** [comment]
> I didn't say that it was

Nope, it's me who assumed wrong.

> That addition detects whether gcc acttually supports the attribute: Newer gcc doesn' warn in certain cases, the added code catches that.

What gcc version were you using? Perhaps [the test you mentioned](https://github.com/libsdl-org/SDL/issues/7146#issuecomment-1404575889) is wrong?

**Comment by sezero** [comment]
> > That addition detects whether gcc acttually supports the attribute:
> > Newer gcc doesn' warn in certain cases, the added code catches that.
> 
> What gcc version were you using? Perhaps [the test you mentioned](https://github.com/libsdl-org/SDL/issues/7146#issuecomment-1404575889) is wrong?

gcc-4.5.4 for mingw: rejects `-fvisibility=xxx`

gcc-7.5.0 for mingw: doesn't reject it unless it really encounters some
procedure to apply the attribute, not just its declaration but also its
body. That is where the added code comes into play.

**Comment by madebr** [comment]
We're talking about this code, right?
https://github.com/libsdl-org/SDL/blob/b23d20cd4defc61872af25e2292a7d3692b8c084/include/SDL3/SDL_begin_code.h#L53-L67

`__attribute__ ((visibility("default")))` should never be used for mingw.
Isn't `__WIN32__` defined?

**Comment by sezero** [comment]
> `__attribute__ ((visibility("default")))` should never be used for mingw.

But 'hidden' would be used because of `-fvisibility=hidden` switch
