### ISSUE TITLE
Remove diagonal DPI parameter of SDL_GetDisplayPhysicalDPI()

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7147]
Should the diagonal DPI "ddpi" parameter of SDL_GetDisplayPhysicalDPI() be removed? 

```
 * \param ddpi a pointer filled in with the diagonal DPI of the display; may
 *             be NULL
 * \param hdpi a pointer filled in with the horizontal DPI of the display; may
 *             be NULL
 * \param vdpi a pointer filled in with the vertical DPI of the display; may
 *             be NULL
 * \returns 0 on success or a negative error code on failure; call
 *          SDL_GetError() for more information.
 *
 * \since This function is available since SDL 3.0.0.
 *
 * \sa SDL_GetNumVideoDisplays
 */
extern DECLSPEC int SDLCALL SDL_GetDisplayPhysicalDPI(int displayIndex, float * ddpi, float * hdpi, float * vdpi);
```

**Comment by ericwa** [comment]
+1 for removal. In SDL2/currently, the meaning of `ddpi` is inconsistent - in `WIN_GetDisplayDPI` it just returns the same thing as `hdpi` and `vdpi`, in other places (wherever `SDL_ComputeDiagonalDPI` is called), ddpi returns `sqrt(hdpi*hdpi + vdpi*vdpi)`. That inconsistency makes it dangerous to use imo.

**Comment by Kontrabant** [comment]
There also exist displays that provide bad EDID data where this info isn't correct, so that's another scenario where this can't be relied upon.

Another +1

**Comment by icculus** [comment]
Agreed

**Comment by slouken** [comment]
Let's remove this from SDL 3.0. We can add it back if we find important use cases, and if we do, we can add it back with a single DPI value instead of 3.

The sdl2-compat version would be (in pseudo-code):
```c
int DPI = android ? 160 : 96;
float scale = getdesktopmode()->display_scale;
return (int)SDL3_lroundf(DPI * scale);
```

**Comment by AntTheAlchemist** [comment]
The DPI useful to me. I use it to scale some fonts and UI elements, so that big fonts / elements aren't in-you-face on big screens and fonts aren't too small to read on smaller screens. I'd miss it, so vote to put a single value DPI back in at some point.

**Comment by slouken** [comment]
I think what you want to use is the desktop display scale, in the new SDL_DisplayMode structure.

**Comment by slime73** [comment]
Using display scale / DPI scale instead of physical DPI is good for accessibility too, since users of a particular device can often choose a global OS scale that fits their needs (for eyesight etc.)

**Comment by slouken** [comment]
> I'll try the desktop scale, but this is mainly for Android. On a small phone, I would automatically choose the big UI option, on a large tablet it would scale the UI down. On Windows it would depend what the user has chosen, which might work in some situations. DPI would give a consistent result. Just want to put my vote in for putting DPI back in.

Yes, please try the desktop scale and see how that works for you. It will be different than using the DPI, but it should still provide good results. Please let us know how it works!

**Comment by 1bsyl** [comment]
I was also using the SDL_GetDisplayPhysicalDPI to display element at arbitrary fixed sized on android.
eg: I want a button of 1 cm, on a touch screen because otherwise it's not usable.

On android, I want to access densityDpi, which is in SDL_DiplayMode.display_scale. So this is ok.

except the division it currently an integer division.
See this PR to fix android by cast to float (otherwise, for instance, when you re-multiply by 160, you get 320 instead of 440)
https://github.com/libsdl-org/SDL/pull/7164/files

**Comment by slime73** [comment]
For what it's worth the iOS backend for this has a hard-coded list of physical DPIs for each model of iPhone. That list hasn't been updated in several years, so the API isn't very accurate on iOS these days.

I don't imagine that hard-coded list will be regularly updated in the future either, so relying on GetDisplayPhysicalAPI on all platforms seems a little dangerous / misleading. Personally I'm in favour of removing it.

**Comment by slouken** [comment]
I went ahead and removed the API for now. We can reopen this PR if we decide we want to bring it back.

**Comment by AntTheAlchemist** [comment]
I'm ok with this. I looked at the desktop scale in `SDL_DisplayMode` reported from various different devices and it makes a lot of sense regarding UI scale. Amazon Fire TV is set to 2.0 scale for instance. All the devices seemed to have a sensible scale set.

**Comment by slouken** [comment]
Great. :)
