### ISSUE TITLE
SDL_PollEvents performance issues on MacOS

### ISSUE THREAD

**Issue by Grieverheart** [libsdl-org/SDL#7151]
I was trying out some examples from Dear Imgui using SDL and found that performance was worse than expected on MacOS. After investigating further, I found that the issue is only present in the SDL backend and not e.g. the GLFW one. For reference, here is the issue I opened at Dear Imgui [https://github.com/ocornut/imgui/issues/6113](https://github.com/ocornut/imgui/issues/6113) . I think the main issue is coming from `SDL_PollEvent`. I removed handling of events in the code and only run poll events and timed the while block. Here are some typical timings in milliseconds:
```
0.663672
0.672658
0.966297
0.901251
0.955485
0.739116
0.839618
0.852102
0.684907
0.825224
1.002466
3.012460
0.141898
0.432765
2.062570
0.566215
0.860042
0.291974
0.545771
1.263200
0.773571
0.773499
1.048631
6.769198
0.249501
2.735734
0.431145
1.426689
2.423991
0.623085
2.550020
0.091564
1.507378
0.615969
0.178367
2.395290
10.93059
0.416646
1.277229
0.890001
0.451946
1.305677
1.868883
0.090235
1.230001
1.297767
0.120430
1.334700
1.824015
0.419720
1.136415
```

Some info:

OS: MacOS 11.7.1 (also tried with later MacOS on different Macbook)
SDL version: 2.24.0

**Comment by Grieverheart** [comment]
![graph](https://user-images.githubusercontent.com/1652929/214648881-0805718a-7ffa-498b-8255-33932e42a68a.svg)
Here is a flamegraph if it helps.

**Comment by slime73** [comment]
> I found that the issue is only present in the SDL backend and not e.g. the GLFW one.

I'm kinda curious what a flamegraph when using GLFW looks like when compared to SDL's, if it's not too much trouble. Also what does your SDL event-polling loop code look like?

**Comment by icculus** [comment]
The flame graph looks like we waited for the OS to run the run loop...that entire tower is stuff running behind the scenes in cocoa.

This...doesn't appear to be an SDL thing at first glance.

**Comment by Grieverheart** [comment]
> The flame graph looks like we waited for the OS to run the run loop...that entire tower is stuff running behind the scenes in cocoa.
> 
> This...doesn't appear to be an SDL thing at first glance.

Indeed, that's what I also deduces, but compare to GLFW's flamegraph:
![graph](https://user-images.githubusercontent.com/1652929/214872206-3725da1f-773d-40e1-b3df-3b78bbdb5691.svg)

**Comment by sridenour** [comment]
Running ImGui's SDL_metal and GLFW_metal samples, measuring time taken to poll events, GLFW is 2x to 3x faster. Sometimes polling events in SDL took over a millisecond, even *without* passing any events to ImGui!

SDL_metal results:
```
Frames: 3714
Total event polling time: 2.368252
Avg poll time: 0.637655 (ms)
```

GLFW_metal results:
```
Frames: 3762
Total event polling time: 0.727516
Avg poll time: 0.193385 (ms)
```

It might be worth looking into any differences between GLFW's macOS event code and SDL's macOS event code.

**Comment by icculus** [comment]
This likely affects SDL3 as well, but I'm putting it into the 2.28.0 milestone as something we should figure out before that ships.

**Comment by sridenour** [comment]
@icculus IDK if you saw my edit, but it looks like there's a good chance it's something weird with ImGui's SDL2 backend. A simple test app that doesn't use ImGui only takes 0.16 ms per frame to poll events.

**Comment by Grieverheart** [comment]
I had a look and the culprit seems to be `SDL_SetCursor`, which is called every frame. Now GLFW is simply calling `[(NSCursor*) window->cursor->ns.object set];`, while in SDL I'm a bit lost; If I understand correctly, the following code is called then every frame:
```C++
        if (cursor != mouse->def_cursor) {
            SDL_Cursor *found;
            for (found = mouse->cursors; found; found = found->next) {
                if (found == cursor) {
                    break;
                }
            }
            if (found == NULL) {
                SDL_SetError("Cursor not associated with the current mouse");
                return;
            }
        }
```
Which looks through a linked list of cursors (`mouse->cursors`) to check if the cursor is present. Could this be the bottleneck? Is the check really required?

**Comment by Grieverheart** [comment]
I think I missed the call to the following function:
```objc
static int Cocoa_ShowCursor(SDL_Cursor *cursor)
{   
    @autoreleasepool {
        SDL_VideoDevice *device = SDL_GetVideoDevice();
        SDL_Window *window = (device ? device->windows : NULL);
        for (; window != NULL; window = window->next) {
            SDL_WindowData *driverdata = window->driverdata;
            if (driverdata) {
                [driverdata.nswindow performSelectorOnMainThread:@selector(invalidateCursorRectsForView:)
                                                      withObject:[driverdata.nswindow contentView]
                                                   waitUntilDone:NO];
            }
        }
        return 0;
    }
}
```
which is called then every frame.

**Comment by sridenour** [comment]
@Grieverheart Calling `SDL_SetCursor()` definitely seems to be the culprit. Changing my test app to call `SDL_SetCursor()` every frame makes the average event poll time jump from 0.16ms per frame to 0.67ms!

What's weird is that my test app isn't setting the cursor inside the event polling loop (and neither is Dear ImGui), yet the event polling is where the performance hit takes place.

**Comment by slime73** [comment]
SDL_SetCursor's macOS implementation has some code to run this function https://developer.apple.com/documentation/appkit/nswindow/1419601-invalidatecursorrectsforview in the event loop after SetCursor has been called. I looked through the history of that area of the code but it was made that way some time before the repository's history got broken, so I don't know why exactly.

As a user I wouldn't really expect calling SetCursor with the same parameters every frame to cost a lot, but I suppose I also wouldn't expect SDL to check every API to make sure redundant work isn't being done if the same parameters are used (that's more of a user responsibility IMO in most cases.)

So I guess the main question right now is what purpose does that invalidateCursorRects call inside SetCursor have?

**Comment by sridenour** [comment]
Given that SDL doesn't support having different cursors in different areas of the screen (which is what all this cursor rect stuff is about, so a Mac app can manually specify different cursors to use on different areas of its window, like for a drawing app) it would probably be better to do away with the cursor rects entirely (after all, SDL is setting the cursor rect to the entire window anyway) and just call the cursor's `-set` method.

Changing `Cocoa_ShowCursor()` to the code below fixes the performance problem, but IDK if it has any knock-on effects related to not invalidating the useless cursor rects
```objc
static int
Cocoa_ShowCursor(SDL_Cursor * cursor)
{ @autoreleasepool
{
    SDL_VideoDevice *device = SDL_GetVideoDevice();
    SDL_Window *window = (device ? device->windows : NULL);
    for (; window != NULL; window = window->next) {
        SDL_WindowData *driverdata = (__bridge SDL_WindowData *)window->driverdata;
        if (driverdata) {
            SDL_Mouse *mouse = SDL_GetMouse();

            if (mouse->cursor_shown && mouse->cur_cursor && !mouse->relative_mode) {
                [(__bridge NSCursor*)mouse->cur_cursor->driverdata set];
            } else {
                [[NSCursor invisibleCursor] set];
            }
        }
    }
    return 0;
}}
```

**Comment by sridenour** [comment]
Ok, so one consequence of just calling `[mouseCursor set]` is that it sets it for the whole screen; the mouse cursor doesn't change back to normal when it leaves the window. It *does* change back when the application exits.

IMHO not really a big deal, but I'm sure there's somebody out there for whom this will be the end of the world. Maybe something to save for SDL3, with a hint that will make it use a cursor rect for the whole window like it currently does. Nobody seems to be complaining that GLFW sets the cursor for the entire screen instead of using cursor rects.

I wonder if it's possible for the Dear ImGui SDL backend to cache what the set cursor is, to avoid calling `SDL_SetCursor()` unless the cursor actually changes.

**Comment by Grieverheart** [comment]
@sridenour Would that be as simple as checking if `cursor != cur_cursor` in `SDL_SetCursor`?

**Comment by sridenour** [comment]
Looking further into it, GLFW doesn't set the cursor for the whole screen. Even though it calls `[mouseCursor set]` the cursor still goes back to normal when it leaves the application's window.

There's probably a "mouse exited window" Cocoa event that GLFW is listening to and changing the cursor back to normal; SDL could probably do the same.

**Comment by sridenour** [comment]
GLFW implements the `mouseExited:` and `mouseEntered:` Cocoa view delegate functions and sets the mouse cursor back to the normal system cursor when the mouse exits and back to the user-supplied one (or hides it) when it re-enters the window. SDL could probably do the same. SDL would have to save the user-supplied mouse cursor and visibility state somewhere accessible by the window handling code and then add `mouseExited:` / `mouseEntered:` delegate functions that changed/hid the cursor as appropriate.

**Comment by slouken** [comment]
> GLFW implements the `mouseExited:` and `mouseEntered:` Cocoa view delegate functions (which SDL doesn't seem to), and sets the mouse cursor back to the normal system cursor when the mouse exits, and back to the user-supplied one (or hides it) when it re-enters the window.
> 
> SDL could probably do the same. SDL would have to save the user-supplied mouse cursor and visibility state somewhere accessible by the window handling code and then add `mouseExited:` / `mouseEntered:` delegate functions that changed/hid the cursor as appropriate.
> 
> Would also have to deal with the application trying to change the cursor while it was outside the window.

Yes, this seems like the right approach. Does anyone want to take a stab at a (tested) PR?

**Comment by sridenour** [comment]
If I were to give it a shot this weekend, should I base the PR off of SDL 2 or 3?

**Comment by sridenour** [comment]
@slouken If I were to take a shot at it this weekend, should I base the PR off SDL 2 or 3?

**Comment by icculus** [comment]
Wait, so we can't just make sure the cursor isn't the current one in SDL_SetCursor and return early?

**Comment by sridenour** [comment]
You could, but that'd still leave the unnecessarily large performance hit when the cursor really does change. The best way IMHO would be to do both: return early if it's the same, and ditch the cursor rectangle stuff when it does change.

**Comment by sridenour** [comment]
Maybe for SDL 2.28 just check and return early, to minimize code changes, and then for SDL 3 get rid of the cursor rectangles.

**Comment by slouken** [comment]
That sounds good, thanks!

**Comment by slime73** [comment]
> one consequence of just calling [mouseCursor set] is that it sets it for the whole screen

> GLFW implements the `mouseExited:` and `mouseEntered:` Cocoa view delegate functions

It sounds like there could be more edge cases to deal with when using this approach. For example if the cursor isn't inside any SDL window when SDL_SetCursor is called, we'd need extra code to avoid calling `[cursor set]` in that situation if I'm not misunderstanding how it works.

**Comment by icculus** [comment]
Okay, the SDL2 fix is in, let's do the more aggressive change for SDL3.

**Comment by sridenour** [comment]
Actually, the SDL3 change wound up being really simple. It could even be backported to SDL2.

Instead of having to mess around with adding `mouseEntered:` and `mouseExited:` and keeping track of whether or not the mouse was hidden, had gone outside the window, etc., in `Cocoa_ShowCursor()` (which gets called by `SDL_SetCursor()`) we just check to see if the mouse has a focused window.

If the mouse is inside a focused SDL window, we set the desired cursor using `[NSCursor set]`. If it's outside an SDL window, or if the window loses focus, we change the cursor back to the system arrow.

And since `Cocoa_ShowCursor()` gets called whenever the cursor crosses a window boundary, changing back and forth between the system cursor and the app cursor is easy and doesn't require tracking a bunch of extra state.

**Comment by slime73** [comment]
> And since Cocoa_ShowCursor() gets called whenever the cursor crosses a window boundary, changing back and forth between the system cursor and the app cursor is easy and doesn't require tracking a bunch of extra state.

Does this happen in the same frame and at the same frequency as before? I can imagine macOS might be more accurate with this inside its own delegate functions than SDL could be without using those.

**Comment by sridenour** [comment]
Just eyeballing it, it happens so quickly that I can't tell if it's the same frame or not. I assume it is, since it's happening as soon as SDL realizes the mouse has crossed the window border.

One thing I noticed when looking into how GLFW does it (which uses `mouseEntered:` and `mouseExited:`) is that it's possible for the cursor to get "stuck" as the app's cursor if you move the mouse outside the window really quickly. Like the `mouseExited:` delegate function doesn't get called if the mouse leaves too quickly or something, so GLFW never changes it back to the system arrow.

With the way it's handled in my PR, I cannot get the cursor to stick no matter how fast I move my mouse. It always switches back to the system arrow once it goes outside the window.

**Comment by slouken** [comment]
Nice!
