### ISSUE TITLE
No Input detected from L2 and R2 buttons, affects multiple 8BitDo Game Pads and probably also some PSX controller wired adapters

### ISSUE THREAD

**Issue by it9exm** [libsdl-org/SDL#7155]
The issue is extensively described in the following URLs.

https://github.com/ValveSoftware/steam-for-linux/issues/8772
https://github.com/ValveSoftware/steam-for-linux/issues/8293
https://codeberg.org/fabiscafe/game-devices-udev/issues/2

I tried to map the buttons L2 and R2 of my 8BitDo P30 Modkit in Duckstation, but the input from such buttons is not detected. Tested with Debian Sid on different machines.

Many months ago the same happened with a PSX to USB adapter, tried with Duckstation too, but on Windows 11

Also tried to follow the the instructions in the following comment without success.

https://codeberg.org/fabiscafe/game-devices-udev/issues/2#issuecomment-634142

**Comment by slouken** [comment]
Can you provide specific repro steps for your issue?

What version of SDL are you testing with?
What controller are you using, and what mode are you enabling when you connect it?
What is the dmesg output when your controller is connected?
What is the output of SDL's testcontroller test program (testgamepad with SDL 3.0)?

**Comment by slouken** [comment]
I tested with the 8BitDo Pro 2 Bluetooth gamepad using SDL 3.0, holding down the B button while connecting it via USB.
The kernel reported USB device idVendor=045e, idProduct=028e, bcdDevice=1.14, and connected it as a Microsoft X-Box 360 pad.
testgamepad showed all inputs working correctly, and the R2 and L2 triggers gave analog inputs and rumbled when pressed (a feature of testgamepad)

**Comment by slouken** [comment]
We haven't heard back on this issue, so I'm removing this from the current milestone, which is shipping soon.

**Comment by slouken** [comment]
No response from author in almost 6 months. We've made lots of improvements to the gamepad support since this was reported, so I'll close this for now. Please feel free to reopen it if you are able to reproduce with the latest SDL code.

**Comment by Hordeking** [comment]
It could be that the L2 and R2 buttons are being detected as axes and not buttons. When I run jstest-gtk, these buttons activate axes 2 & 5, rather than buttons.
