### ISSUE TITLE
RE: spurious SDL_MOUSEMOTION events with SDL_HINT_MOUSE_RELATIVE_MODE_WARP 1 since Windows 10 Fall Creators update

### ISSUE THREAD

**Issue by x0rnn** [libsdl-org/SDL#7159]
Since https://github.com/libsdl-org/SDL/issues/2695 is wrongfully closed, I'm opening a new issue referencing it. This is still an issue/bug.

**Comment by AntTheAlchemist** [comment]
@x0rnn I've given this a try on my system (Win 10 Pro, 22H2, Build 19045.2546, Windows Feature Experience Pack 120.2212.4190.0). I'm not seeing the spurious events here. This is the first time I've tried this hint and I was expecting the mouse to be constantly snapped to the centre of the screen, but that's not happening. It gets snapped back when focus changes, which isn't what I expected.

Have you played around with `SDL_HINT_MOUSE_RELATIVE_WARP_MOTION` and `SDL_HINT_MOUSE_RELATIVE_SCALING` to see what effect that has on the bug?

I'm using the latest SDL3 source.

**Comment by x0rnn** [comment]
Sorry, should have mentioned this is with SDL2. Is the workaround by Daniel Gibson not in the codebase anymore?

**Comment by slouken** [comment]
Are you still seeing this with the latest SDL release? If so, can you provide a small example that shows the issue, or tell us how to reproduce it with the SDL test programs?

**Comment by AntTheAlchemist** [comment]
FYI: No change my end. I don't know how this hint is supposed to behave, but it only warps the mouse once, upon activating relative mode, then behaves no different except the inputs aren't as smooth as raw input.

**Comment by slouken** [comment]
Can you provide a test program, or steps with the SDL test programs and the testing steps? The warping hint isn't actually meant to be used on Windows, since as you noted the behavior isn't as good as raw input, but we should at least make it work.

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.
