### ISSUE TITLE
Could you add a way to disable the call to ShowScreenKeyboard() from SDL_StartTextInput()?

### ISSUE THREAD

**Issue by leonstyhre** [libsdl-org/SDL#7160]
My application EmulationStation Desktop Edition (ES-DE) has run into a problem on the Steam Deck where the on-screen keyboard is automatically displayed any time SDL_StartTextInput() is called.

As ES-DE has a built-in virtual keyboard this is very annoying because the SteamOS keyboard will be displayed on top of it. Since I build and bundle SDL with my AppImage I can work around this issue by essentially patching out the call to ShowScreenKeyboard() from SDL_StartTextInput() in SDL_video.c. But this is of course not a proper long term solution.

There is also an option in ES-DE to disable the built-in virtual keyboard and if a user chooses to do this it would be really nice to be able to use the SteamOS on-screen keyboard instead.

Would it as such be possible to add a mechanism to SDL to explicitly enable and disable the on-screen keyboard using some function call or similar? Then I could call this function based on whether the user has decided to use the built-in virtual keyboard or not.

Many thanks in advance!

**Comment by rsubtil** [comment]
Seems like this is detected through a `SteamDeck` flag, so you may be able to manually manipulate it to disable this behavior:
https://github.com/libsdl-org/SDL/blob/7c4ec1867b682d58077be5b5f5299f5165014ee9/src/video/x11/SDL_x11video.c#L208
Also you can trigger the Steam's keyboard through a URL as well (`steam://open/keyboard`):
https://github.com/libsdl-org/SDL/blob/c5c94a6be6bfaccec9c41f6326bd4be6b2db8aea/src/video/x11/SDL_x11keyboard.c#L444-L453
*(mind you I've never used SDL nor have tested this on a Steam Deck; I was searching on how to show the Deck's keyboard and stumbled upon this. Hope it helps you :+1:)*

**Comment by ericoporto** [comment]
Probably related to #3383

**Comment by leonstyhre** [comment]
@rsubtil Thanks for the proposal, but unfortunately this is not limited to the Steam Deck but to any device which brings up a virtual keyboard. It could be other handheld devices running Linux or Windows for instance.

**Comment by leonstyhre** [comment]
@slouken Thanks a lot for adding this!

**Comment by slouken** [comment]
You're welcome!
