### ISSUE TITLE
Spacemouse mapped to Virtual Joystick misdetected as XBox 360 Controller

### ISSUE THREAD

**Issue by kermitfrog** [libsdl-org/SDL#7165]
In Steam / X4: Foundations, my Virtual Joystick (a remapped Spacemouse) is misdetected as XBox 360 Controller, which seems to be an issue in SDL.

Instead of copying the whole text, here is the link to the [issue in SteamInput](https://github.com/ValveSoftware/steam-for-linux/issues/9124).

My most important question for now:
What exactly are the criteria to determine whether a device is a joystick or controller?

**Comment by slouken** [comment]
You should be able to remap your mouse in the Steam controller settings now. Please let me know if you have any issues with that!

**Comment by kermitfrog** [comment]
> You should be able to remap your mouse in the Steam controller settings now. [..]

I'm glad something happens :) - but... based on that sentence I'm not sure you understand the problem, which is that I **can** remap my mouse in the Steam controller settings. This works **because steam thinks it's a XBOX 360 Controller**, which causes the game to not get the negative values of 2 axes.

Or do you mean that there is now a way to fix this in the steam beta?
And: do I need to compile the newest version of SDL and replace the steam libSDL2.so with that?

As of now, nothing has changed.


I had a quick look at the latest commit messages to see if something could be related to this. There are too many to read, but one seems kind of related: 
> Revert "Added Linux mappings for the Logitech G29 in PS3 and PS4 modes"

With the additional description:
> We don't want the G29 to show up as a gamepad, Steam will create a virtual Xbox controller for it, which breaks racing games.

In that spirit, another description of my problem is: Steam will create a virtual Xbox controller for my Virtual 6-Axis Joystick, which breaks Space-Flight games.

**Comment by kermitfrog** [comment]
Back to my earlier question:
> What exactly are the criteria to determine whether a device is a joystick or controller?

If the detection is based on the devices capabilities and I knew which, I could probably tweak those of the Virtual device to make clear that it's not a gamepad.

**Comment by slouken** [comment]
Ah, I understand now.
If you edit Steam\config\config.vdf, and set "controller_blacklist" to "1234/5678," where 1234 is the VID and 5678 is the PID of your controller, Steam will ignore it.

**Comment by kermitfrog** [comment]
Ah, thanks - that does what I want :)

Does that mean that determining the type of device is done exclusively via database lookup of VID and PID?
If so, maybe we (as in developers that use uinput to create virtual input devices <-> SDL devs) could agree to reserve certain ranges PIDs of VID 0000 for specific virtual device types? e.g. 0000/f000 - 0000/f0ff for joysticks, 0000/f000 - 0000/f0ff for controllers, etc.
That should prevent such problems in the future.

**Comment by slouken** [comment]
No, but the blacklist is done by VID/PID. If the kernel standardized ranges for virtual devices, we would certainly respect those.
