### ISSUE TITLE
Remove SDL_GL_GetDrawableSize, SDL_Metal_GetDrawableSize, and SDL_Vulkan_GetDrawableSize?

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#7172]
Since the addition of SDL_GetWindowSizeInPixels, those other functions have felt pretty redundant to me. It's a bit confusing to have two sets of APIs which effectively do the same thing.

There was a bit of discussion about eventual removal in the PR for adding GetWindowSizeInPixels: https://github.com/libsdl-org/SDL/pull/6112 - I think the conclusion there was that the older functions are mostly redundant except maybe on macOS/iOS where the GetDrawableSize APIs have some code to detect an externally created Metal view with a specific hard-coded tag that was attached to the window, and return the size of its backing layer if it exists.

But that's not an officially documented part of SDL_Metal/Vulkan_GetDrawableSize (you'd have to look at SDL's source code to know it's looking for that in the first place, and to know what the expected tag ID is), and if a user has an externally created view set to that tag they probably also have the ability to query its size directly instead of going through SDL. So personally I don't see much value in keeping the DrawableSize APIs just for that.

Related: #3980

**Comment by slouken** [comment]
Fair enough, go ahead and submit a PR for this.

Thanks!
