### ISSUE TITLE
Deployment license-related question

### ISSUE THREAD

**Issue by corwinn** [libsdl-org/SDL#7177]
Hi,
I have to patch **src/main/windows/version.rc** (comment out lines 2 and 4) in order to cross-compile (for "Windows" x86_64) **SDL2-2.26.2** - using the **configure** build script, because a tool of my toolchain (**llvm-rc**) fails to process the file.
In this case:
1. Am I allowed to publish my program statically-linked with **SDL2**, or I should deploy **SDL2** as a ".dll", and link dynamically?
2. Am I required to state that my program is using "Altered source" version "plainly marked as such" of **SDL2** and not the original - as per your license?

Also, could you answer questions 1 and 2 - but in the case where I do manage to cross-compile w/o patching your code.

Just linking with [SDL2-devel-2.26.2-mingw.tar.gz](https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-devel-2.26.2-mingw.tar.gz) probably won't work, as my cross-compiler != yours.

Regards,
Corwin.

**Comment by icculus** [comment]
> Am I allowed to publish my program statically-linked with SDL2, or I should deploy SDL2 as a ".dll", and link dynamically?

You can link it statically, modified or not.

> Am I required to state that my program is using "Altered source" version "plainly marked as such" of SDL2 and not the original - as per your license?

I think generally we wouldn't consider changes to an .rc file as significant, but I'll stick a "this file is public domain" comment at the top of that file, which should resolve the issue here.

@libsdl-org/a-team, do we _need_ these first two lines in the .rc file? I think I've run into this with llvm-rc too, before.

Also, this file appears to be gone in SDL3, was that intentional?

**Comment by icculus** [comment]
Forgot to mention this issue in the commit log, but 7ac43cfb6be0559f54a2f4c1b26fe536c10de544 adds a note about version.rc being public domain.

This issue can be closed once we get some feedback on those first two lines.

**Comment by sezero** [comment]
I _think_ `#include "winresrc.h"` is necessary. Don't know what the build
error is, but if it is about failing to include winresrc.h, does changing
it to `#include <winresrc.h>` help in any way?

**Comment by sezero** [comment]
> Also, this file appears to be gone in SDL3, was that intentional?

it is now `src/core/windows/version.rc`

**Comment by corwinn** [comment]
> `#include <winresrc.h>`

 - same error:
`SDL2-2.26.2/src/main/windows/version.rc:2:10: fatal error: 'winresrc.h' file not found`

Invoking **x86_64-w64-mingw32-windres** with the addition of `--include-dir $CMAKE_SYSROOT/include ` to its command line, resolves the issue.

**Comment by sezero** [comment]
Never used it myself, but it's _probable_ that llvm-rc isn't using the standart
include paths of its library, unlike windres. Don't know a solution if that is the
case.

Does llvm project now about this?

**Comment by corwinn** [comment]
> Does llvm project know about this?

No.
I just found out the cause. "x86_64-w64-mingw32-windres" is invoking "clang" and it should be invoking "x86_64-w64-mingw32-clang". Manually invoking "x86_64-w64-mingw32-clang" with the command line built by "x86_64-w64-mingw32-windres" transforms the .rc without an issue. I'll have to cross-compile "windres" too it seems; or file a bug report if I find a bug at **https://github.com/llvm/llvm-project/blob/main/llvm/tools/llvm-rc/llvm-rc.cpp**
Not your issue it seems.
.
Thank you.
