### ISSUE TITLE
Segfault on window close in Wayland with second monitor

### ISSUE THREAD

**Issue by TwistedBlizzard** [libsdl-org/SDL#7192]
After commit 22c69bccdf18d6c5c0990de9bc89e5e76d3a7c50, `if (display->driverdata->xdg_output)` on line 1012 of `SDL_waylandvideo.c` produces a segfault when `SDLQuit()` is called if I have an external monitor plugged in.

**System Info:**
OS: ArchLinux
Desktop Manager: Gnome
GPU: Nvidia RTX 2060 (Notebook)

**Comment by slouken** [comment]
Thanks for the report, this should be fixed now.
