### ISSUE TITLE
Wayland: not possible to set the window position

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7197]
With wayland backend: it's not possible to set the window position
- at window creation (SDL_CreateWindow())
- using SDL_SetWindowPosition()

**Comment by Kontrabant** [comment]
Wayland has no mechanism for applications to specify their window position. They can request a display on which to be made fullscreen, but that's it.

**Comment by 1bsyl** [comment]
yes i didn't find obvious information.

on the other hand:
- you can move/drag a window with the mouse 
- you can also move/place a window with specific short cut.
- seems unbelievable this doesn't exist

**Comment by Kontrabant** [comment]
> yes i didn't find obvious information.
> 
> on the other hand:
> 
> * you can move/drag a window with the mouse
> * you can also move/place a window with specific short cut.
> * seems unbelievable this doesn't exist

Yes, you can request that the compositor start an interactive move event or have it move windows around, but an application can't specifically ask it to put a window at a specific location. It does make sense in the larger scheme of things, as desktops aren't necessarily stacks of windows that can be arbitrarily placed anywhere (e.g. tiling window managers).

This functionality would have to come via an extension, and there's not much interest in it as the general philosophy behind Wayland's design is that applications are limited to managing the contents within their own window borders and shouldn't have any control beyond them, which is also why querying or warping the global mouse pointer position isn't allowed either.

**Comment by 1bsyl** [comment]
thanks for info ...
also found this link ... https://mir-server.io/docs/window-positions-under-wayland

**Comment by madebr** [comment]
I just ran into this. Should `SDL_SetWindowPosition` return a negative value in the case where a window is not a pop-up and thus cannot be placed?

**Comment by slouken** [comment]
Yes, probably.

**Comment by avafinger** [comment]
i have a case where i need to position the window at x,y on the screen.
This is possible with a hack on Weston and some changes on sdl2.
It was tested on rockchip platform (rk3588) with the hack provided here:
https://github.com/JeffyCN/rockchip_mirrors/commit/7fe4cc10ae131a4c212740cc836d372317427395#commitcomment-115317778

**On the SDL2 side (basically):**

```
--- /apps/arm/rk3588/ubuntu_22.04/rockchip/sdl2/libsdl2-2.0.20+dfsg/src/video/wayland/SDL_waylandwindow.c
+++ /tmp/libsdl2-2.0.20+dfsg/src/video/wayland/SDL_waylandwindow.c
@@ -541,8 +541,8 @@
     for (i = 0; i < numdisplays; i += 1) {
         if (SDL_GetDisplay(i)->driverdata == driverdata) {
             SDL_SendWindowEvent(window, SDL_WINDOWEVENT_MOVED,
-                                SDL_WINDOWPOS_CENTERED_DISPLAY(i),
-                                SDL_WINDOWPOS_CENTERED_DISPLAY(i));
+                                window->x /* SDL_WINDOWPOS_CENTERED_DISPLAY(i)*/,
+                                window->y /*SDL_WINDOWPOS_CENTERED_DISPLAY(i)*/);
             break;
         }
     }
@@ -748,6 +748,11 @@
         data->shell_surface.xdg.roleobj.toplevel = xdg_surface_get_toplevel(data->shell_surface.xdg.surface);
         xdg_toplevel_set_app_id(data->shell_surface.xdg.roleobj.toplevel, c->classname);
         xdg_toplevel_add_listener(data->shell_surface.xdg.roleobj.toplevel, &toplevel_listener_xdg, data);
+
+        if (data->shell_surface.xdg.surface) {
+            xdg_surface_set_window_geometry (data->shell_surface.xdg.surface,
+                                            window->x, window->y, 0, 0);
+        }
     }
 
     /* Restore state that was set prior to this call */
@@ -1246,7 +1251,6 @@
     if (window->y == SDL_WINDOWPOS_UNDEFINED) {
         window->y = 0;
     }
-
     data->waylandData = c;
     data->sdlwindow = window;
 
@@ -1332,6 +1336,10 @@
     /* We may need to create an idle inhibitor for this new window */
     Wayland_SuspendScreenSaver(_this);
 
+    if (c->shell.xdg && data->shell_surface.xdg.surface) {
+       xdg_surface_set_window_geometry(data->shell_surface.xdg.surface, window->x, window->y, window->w, window->h);
+    }
+
     return 0;
 }
 
@@ -1370,7 +1378,7 @@
      * but at least lets us not be terminated by the compositor.
      * Can be removed once SDL's resize logic becomes compliant. */
     if (viddata->shell.xdg && data->shell_surface.xdg.surface) {
-       xdg_surface_set_window_geometry(data->shell_surface.xdg.surface, 0, 0, window->w, window->h);
+       xdg_surface_set_window_geometry(data->shell_surface.xdg.surface, window->x, window->y, 0, 0);
     }
 }
 
@@ -1432,7 +1440,7 @@
 
     /* Update the geometry which may have been set by a hack in Wayland_HandleResize */
     if (data->shell.xdg && wind->shell_surface.xdg.surface) {
-       xdg_surface_set_window_geometry(wind->shell_surface.xdg.surface, window->x, window->y, window->w, window->h);
+       xdg_surface_set_window_geometry(wind->shell_surface.xdg.surface, window->x, window->y, 0, 0);
     }
 }
 
@@ -1450,11 +1458,15 @@
             libdecor_frame_set_title(wind->shell_surface.libdecor.frame, window->title);
         } else
 #endif
+        
         if (viddata->shell.xdg) {
             if (wind->shell_surface.xdg.roleobj.toplevel == NULL) {
                 return; /* Can't do anything yet, wait for ShowWindow */
             }
             xdg_toplevel_set_title(wind->shell_surface.xdg.roleobj.toplevel, window->title);
+            if (wind->shell_surface.xdg.surface) {
+                xdg_surface_set_window_geometry(wind->shell_surface.xdg.surface, window->x, window->y, 0, 0);
+            }
         }
     }
 

```

**Important:**
Tested without decorations and resizing (which is my use case).

**On the application side, you disable libdecor**

Now i face a new challenge, i have a dual-screen setup and need to display content on the second screen.
Is there a way to do it with SDL2 (Weston/Wayland) ?

**Comment by woxels** [comment]
I would suppose this means custom window decoration within SDL2 is now impossible on Wayland? Unless it's a non-movable window that you can only maximize and minimize.

**Comment by Kontrabant** [comment]
You can use the hit test API to interactively move a window with custom decorations.

Currently, trying to center the window isn't going to work. Keep an eye on https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/247 that may allow windows to suggest their initial position. If it ends up finalized, SDL will support it.

**Comment by woxels** [comment]
> You can use the hit test API to interactively move a window with custom decorations.
> 
> Currently, trying to center the window isn't going to work. Keep an eye on https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/247 that may allow windows to suggest their initial position. If it ends up finalized, SDL will support it.

You are a hero, thank you.
`SDL_SetWindowHitTest() + SDL_PointInRect()`
I honestly thought for a moment I was doomed, this means a lot to me Kontrabant.

**Comment by Fumador-debug** [comment]
I had trouble getting window positions right on Wayland until I discovered silicon-signals. Their solution fixed my issue quickly and without hassle. I'm not trying to push their product, but I thought sharing this might help someone else out there.
Curious, how did they achieve this?
link: <https://www.linkedin.com/company/silicon-signals-pvt-ltd/>
Anyone?
