### ISSUE TITLE
x11: set window position on a 2nd screen.

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7198]
It's possible to set the window on a first or on a second screen
with SDL_CreateWindow():
```
SDL_WINDOWPOS_CENTERED | displayid_1
SDL_WINDOWPOS_CENTERED | displayid_2
```

but this doesn't work and product a glitch when this is used with SDL_SetWindowPosition():
the window is moved to the 2nd display, and immediately gets back to the first

**Comment by Kontrabant** [comment]
Does this still happen with #7204 applied?  I didn’t try x11, but some other window positioning oddities were fixed by it, so maybe this is too?

**Comment by 1bsyl** [comment]
yes, this still happens with latest head version

**Comment by 1bsyl** [comment]
actually, not a bug but wrong testcase
