### ISSUE TITLE
Access Violation when calling SDL_CreateWindow() with SDL_WINDOW_OPENGL flag

### ISSUE THREAD

**Issue by JJCUBER** [libsdl-org/SDL#7201]
I am using SDL2 (I noticed this on version `release-2.0.22`, then I upgraded to version `release-2.26.2` and it still occurs).
My environment is Microsoft Visual Studio Community 2019 Version 16.11.23 on Windows 10.

After calling `SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER)`, then calling `SDL_CreateWindow()` with the flag `SDL_WINDOW_OPENGL` (this issue only occurs when I include this flag), my program gets an Access Violation.  It also reports `Critical error detected c0000374`, `Unhandled exception`, and `A heap has been corrupted`.  After pressing continue via the debugger, the program proceeds to hang indefinitely, repeatedly logging `Access violation writing` and never getting past the line of code:
```cpp
    wglGetExtensionsStringARB = (const char *(WINAPI *) (HDC))
        _this->gl_data->wglGetProcAddress("wglGetExtensionsStringARB");
```

The place where the code breaks when this occurs is in the file `SDL_windowsopengl.c` in the function `WIN_GL_InitExtensions()` on the line `SetPixelFormat(hdc, ChoosePixelFormat(hdc, &pfd), &pfd);`.  This seems to be caused by reading `hdc`, which was assigned shortly prior via `hdc = GetDC(hwnd);`.

When compiling without the flag `/fsanitize=address`, the program runs/behaves "normally."

I normally have these SDL_GL attributes set between the call to `SDL_INIT()` and `SDL_CreateWindow()`, though the same issue occurs with all of these removed:
```cpp
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, 0);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);

    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
```
There is no other code before or between the init and create window calls (other than handling of `SDL_Init()` when it returns something other than 0).

Edit:
I have also tried calling `SDL_GL_LoadLibrary()` myself, both with `nullptr`/`NULL` and with the direct path to the opengl dll on my system.  The same issue above still occurs (the program gets an Access Violation).

**Comment by icculus** [comment]
> When compiling without the flag /fsanitize=address, the program runs/behaves "normally."

This seems like maybe AddressSanitizer is upset about the OpenGL implementation? This doesn't seem like an SDL bug.
