### ISSUE TITLE
-lmingw32 flag gives the error ld.lld: error: duplicate symbol: main

### ISSUE THREAD

**Issue by dortamiguel** [libsdl-org/SDL#7209]
My platform is Windows 11 x64 and when I use this flags from the `./sdl2-config --static-libs` command

```
-Llib/windows/SDL2 -lmingw32 -lSDL2main -lSDL2 -mwindows -Wl,--dynamicbase -Wl,--nxcompat -Wl,--high-entropy-va -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid
```

But when I include them I get the following error

```
ld.lld: error: duplicate symbol: main
>>> defined at build/development/src/main.o
>>> defined at C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexewin.c:26
>>>            libmingw32.a(lib64_libmingw32_a-crtexewin.o)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Seems like for some reason -lmingw32 includes a main entrypoint? How I can avoid this issue?

This is the full command I use for linking
```
clang++ -std=c++20 -O2 -fuse-ld=lld -Llib/windows/SDL2 -lmingw32 -lSDL2main -lSDL2 -mwindows -Wl,--dynamicbase -Wl,--nxcompat -Wl,--high-entropy-va -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -lcomctl32 -lpsapi -Wl,-Bdynamic build/development/src/main.o -o build/development/prototype.exe
```

My main in `main.o` looks like this
```c++
int main(int, char **) {
  // code here
  return 0;
}
```

**Comment by madebr** [comment]
The use of `SDL2main` presumes you do `#include "SDL.h"` in the file you're declaring the main function.

```c
#include "SDL.h"
int main(int argc, char *argv[]) {
  // code here
  return 0;
}
```

On certain platforms, SDL2 renames the `main` entry point to `SDL_main` and creates a platform appropriate entry point that calls your `main` function.
This happens with a macro in `SDL_main.h`, included through `SDL.h`.

For Windows GUI applications, SDL2main provides a `WinMain` function calling your `SDL_main`.

Usually, errors against this usage pattern result in different error messages.
[https://wiki.libsdl.org/SDL2/FAQWindows#i_get_undefined_reference_to_sdl_main_...](https://wiki.libsdl.org/SDL2/FAQWindows#i_get_undefined_reference_to_sdl_main_...)
So I'm not 100% confident this solves your issue. Please let us know!

**Comment by dortamiguel** [comment]
Thank you! Including `#include <SDL2/SDL.h>` in main worked
