### ISSUE TITLE
Test of 'src/SDL_cpuinfo.c'

### ISSUE THREAD

**Issue by gvanem** [libsdl-org/SDL#7212]
While compiling the test-code for `src/cpuinfo/SDL_cpuinfo.c` (with `-DTEST_MAIN`), I get this error from clang-cl:
```c
../src/cpuinfo/SDL_cpuinfo.c(1101,5): error: conflicting types for 'SDL_main'
int main()
    ^
../include\SDL3/SDL_main.h(144,17): note: expanded from macro 'main'
#define main    SDL_main
                ^
../include\SDL3/SDL_main.h(156,29): note: previous declaration is here
extern SDLMAIN_DECLSPEC int SDL_main(int argc, char *argv[]);
                            ^
1 error generated.
```

An easy fix for me was simply:
```diff
--- a/src/cpuinfo/SDL_cpuinfo.c 2023-01-31 15:06:34
+++ b/src/cpuinfo/SDL_cpuinfo.c 2023-02-01 09:49:24
@@ -1098,7 +1098,8 @@

 #include <stdio.h>

-int main()
+#undef main
+int main (void)
 {
     printf("CPU count: %d\n", SDL_GetCPUCount());
```

**Comment by madebr** [comment]
I see 2 in-tree test programs: [`src/cpuinfo/SDL_cpuinfo.c`](https://github.com/libsdl-org/SDL/blob/d58693928db28c2e3519a4891c694319941de76b/src/cpuinfo/SDL_cpuinfo.c#L1101) and [`src/stdlib/SDL_getenv.c`](https://github.com/libsdl-org/SDL/blob/d58693928db28c2e3519a4891c694319941de76b/src/stdlib/SDL_getenv.c#L235).
I think it makes sense to move these to the test folder and make them part of the test (build) suite.

**Comment by madebr** [comment]
The cpuinfo functions are already tested by the [test automation](https://github.com/libsdl-org/SDL/blob/d58693928db28c2e3519a4891c694319941de76b/test/testautomation_platform.c#L127).
[Same goes for getenv.](https://github.com/libsdl-org/SDL/blob/d58693928db28c2e3519a4891c694319941de76b/test/testautomation_stdlib.c#L214)

My vote goes for removing these currently commented-out main functions.

**Comment by slouken** [comment]
Yep, go for it.

**Comment by madebr** [comment]
Done in 4af93990a and 048df6260
There are still 4 main functions in `src/hidapi`, but I left these alone.

**Comment by slouken** [comment]
> Done in [4af9399](https://github.com/libsdl-org/SDL/commit/4af93990a90dc0b5d293a01b1a2869734db75981) and [048df62](https://github.com/libsdl-org/SDL/commit/048df6260c1c78863234945e556e9247c55ac31a) There are still 3 main functions in `src/hidapi`, but I left these alone.

Thanks, yes, we shouldn't change the upstream code unless necessary.

**Comment by 1bsyl** [comment]
function are tested by test automation, but maybe we could add some independant "./testcpuinfo"

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/commit/5888b008b1af17f6a0ea5f3c0c793e44dfd9c767 adds `testcpuinfo.c`.
I dropped a call to `SDL_GetCPUName` and `SDL_GetCPUType` because they use internal functions. `SDL_GetCPUName` is removed completely.

**Comment by slouken** [comment]
This is already covered in testplatform.c

**Comment by madebr** [comment]
Reverted in https://github.com/libsdl-org/SDL/commit/78be9eaf3835e4671882950e35bbb654fb74c826
