### ISSUE TITLE
Can't include SDL2 on windows using cmake

### ISSUE THREAD

**Issue by gorogoro2** [libsdl-org/SDL#7213]
Hello there,

I'm trying to include SDL2 to my project using cmake. For that I downloaded the following version: [SDL2-devel-2.26.2-mingw.zip](https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-devel-2.26.2-mingw.zip)

And added to a folder on my project called _dependencies_. I have include the _dependencies/SDL2-2.26.2/cmake_ on `CMAKE_MODULE_PATH`.

When I do: `find_package(SDL2 REQUIRED SDL2)` it goes to  _dependencies/SDL2-2.26.2/cmake/sdl2-config.cmake_ which is correct.
Then _dependencies/SDL2-2.26.2/x86_64-w64-mingw32/lib/cmake/SDL2/sdl2-config.cmake_ is called which is also correct  on my system.

However on this file on line 106 where we can see:
```cmake
  set(_sdl2_implib "${SDL2_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}SDL2${CMAKE_SHARED_LIBRARY_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}")
```
The variable `_sdl2_implib` is with the following value: _dependencies/SDL2-2.26.2/x86_64-w64-mingw32/lib/SDL2.dll.lib_. And this is wrong since this file _SDL2.dll.lib_ does not exist, what I can see is _libSDL2.dll.a_ file.

I also don't see _SDL2main.dll_ and _.lib_ on this package.

Am I doing anything wrong?

Thank you

**Comment by madebr** [comment]
The SDL2 mingw development package assumes you're using a mingw toolchain. (These use .a suffixes for import libraries)
We provide a development package for VC too: [SDL2-devel-2.26.2-VX.zip](https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-devel-2.26.2-VC.zip).

Let's replace all occurrences of `${CMAKE_STATIC_LIBRARY_SUFFIX}` with `.a` in [sdl2-config.cmake.in](https://github.com/libsdl-org/SDL/blob/SDL2/sdl2-config.cmake.in).

**Comment by gorogoro2** [comment]
oh! Thank you for the quick answer.

I can use [SDL2-devel-2.26.2-VC.zip](https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-devel-2.26.2-VC.zip). But I want it to be used also on an unix system. How can I achieve this?

**Comment by madebr** [comment]
I've tested usage of the VC devel package with a modern mingw unix toolchain, but apparently not the use of the mingw devel package with VC.
I think it's fine to use the shared SDL2 libraries across mingw/VC, but usage of the static SDL2 library across mingw/VC will cause issues because of potential c library mismatches.


I've just pushed a commit that hardcodes the `lib` prefix and `.a` suffix for static libraries: https://github.com/libsdl-org/SDL/commit/8800d404428a9d499fde880236856ac739fe44c0
It should be applied on the `sdl2-config.cmake` file in both `(x86_64|i686)-w64-mingw32/lib/cmake/SDL2` subdirectories.

**Comment by gorogoro2** [comment]
Thank you. That changed worked for windows.
Now I'm trying to build using linux WSL, but it is asking for libSDL2.so as `_sdl2_shared` here:
```cmake
set(_sdl2_shared "${SDL2_LIBDIR}/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2${CMAKE_SHARED_LIBRARY_SUFFIX}")
```
However it does not exist. So I guess I can't use this for linux right? 
As far as I know there isn't any release with .so already created. Am I right?
