### ISSUE TITLE
SDL3: pointers as bool

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#7214]
Recently we made a change to switch pointer evaluation from `if (pointer)` to `if (pointer != NULL)`, and having poked around the code a lot, I find this increases the time for me to parse the conditional and determine correctness.

I propose that we switch pointer validation back to boolean form: `if (pointer)` and `if (!pointer)`

Related, I'm having the same issue with flag evaluation, e.g. `if (pointer != NULL && (pointer->flags & BIG_FLAG) != 0)` vs `if (pointer && (pointer->flags & BIG_FLAG))`, but I think there's a compiler warning reason for that, is that right?

@libsdl-org/a-team, thoughts?

**Comment by sezero** [comment]
> Recently we made a change to switch pointer evaluation from `if (pointer)` to `if (pointer != NULL)`, and having poked around the code a lot, I find this increases the time for me to parse the conditional and determine correctness.

IMO, it was one of the unnecessary changes that went in

> I propose that we switch pointer validation back to boolean form: `if (pointer)` and `if (!pointer)`

I have no problem with that

> Related, I'm having the same issue with flag evaluation, e.g. `if (pointer != NULL && (pointer->flags & BIG_FLAG) != 0)` vs `if (pointer && (pointer->flags & BIG_FLAG))`, but I think there's a compiler warning reason for that, is that right?

What warning really?

**Comment by slouken** [comment]
I take it back, I tried the second form using clang -Wall -pedantic and --std=c89 through c2x and it was fine. Any objections to switching the code back to the easier to read form?

**Comment by sezero** [comment]
>  Any objections to switching the code back to the easier to read form?

Not from me

**Comment by 1bsyl** [comment]
I think `if (pointer != NULL)` is more readable because of the contrast of the "space" just before the "!" rather than "(!" which are quite similar characters.  It also tells that the variable is actually pointer and not int / bool; that's my opinion.

**Comment by icculus** [comment]
I flip-flop back and forth in preference, but generally I find "!pointer" to read like human language ("if not this thing, then do this"). It's definitely more compact, and sometimes that's worth a lot in itself.

But I would argue that there are places where either form could be clearer than the other, depending on what you are trying to do in a piece of code, so we maybe shouldn't have a serious coding standard for it.

**Comment by slouken** [comment]
How about testing flags?

**Comment by icculus** [comment]
Oh, I hate the `if ((x & FLAG) != 0)` form unconditionally.  🤣

**Comment by slouken** [comment]
@1bsyl, I took a quick look at a coccinelle script for these, but this doesn't work, it seems to evaluate the expression and compare it to 0, rather than matching the literal "== 0" and "!= 0". Any ideas?
```
@@ expression x, y; @@
(
  !(x & y)
|
- (x & y) != 0
+ (x & y)
)
}
@@ expression x, y; @@
- (x & y) == 0
+ !(x & y)
```

**Comment by 1bsyl** [comment]
it somehow evaluate the patch. (you cannot for instance applied a broken c replacement)
maybe this did the tric: 
```
  (x & c)
- != 0
```
it match (x & c), and removed the  "!= 0"

there are also return value that should be avoid I think,
here so PR testing this: https://github.com/libsdl-org/SDL/pull/7220

**Comment by slouken** [comment]
@1bsyl, can you flip pointer comparisons back to the form `if (pointer)` and `if (!pointer)`?

**Comment by slouken** [comment]
Please apply this change (separately) in both SDL2 and SDL3, so we can continue to cherry-pick changes back and forth.

**Comment by slouken** [comment]
Yep!
