### ISSUE TITLE
Inconsistent Sizes SDL_GetWindowSizeInPixels vs SDL_Metal_GetDrawableSize

### ISSUE THREAD

**Issue by fhoenig** [libsdl-org/SDL#7215]
Setup:

I have a Macbook Pro with HDPI screen connected to an external monitor which is *not* HDPI.
The lowDPI external monitor is the primary display (with status bar etc).
When I launch my SDL2 application the application windows gets created on this external monitor (of course).
I create the window with ALLOW_HDPI and a size of `1280x720`.

Following inconsistent behavior exists on `SDL2-2.26.2`:

When Macbook lid is open:

```
 SDL_Metal_GetDrawableSize(s_window, &fbWidth, &fbHeight); 
// fbWidth = 2560
// fbHeight = 1440

SDL_GetWindowSizeInPixels(s_window, &fbWidth, &fbHeight);
// fbWidth = 1280
// fbHeight = 720

SDL_GetWindowSize(s_window, &windowWidth, &windowHeight);
// windowWidth = 1280
// windowHeight = 720

Vulkan surface caps also return 2560x1440 at this point.
vkQueuePresent errors with SUBOPTIMAL each frame but things are visible.

When I resize the window manually, all functions return 1280x720.
```

When Macbook lid is closed:

```
SDL_Metal_GetDrawableSize(s_window, &fbWidth, &fbHeight); 
// fbWidth = 1280
// fbHeight = 720

SDL_GetWindowSizeInPixels(s_window, &fbWidth, &fbHeight);
// fbWidth = 1280
// fbHeight = 720

SDL_GetWindowSize(s_window, &windowWidth, &windowHeight);
// windowWidth = 1280
// windowHeight = 720
```

I create my metal layer like this (not using any SDL built in Vulkan functions):

```
SDL_MetalView v = SDL_Metal_CreateView(window);
void* l = SDL_Metal_GetLayer(v);

VkMetalSurfaceCreateInfoEXT ci {};
ci.sType = VK_STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT;
ci.pLayer = l;
VkResult res = vkCreateMetalSurfaceEXT(m_instance, &ci, nullptr, &surface);
    
```

I suspect the initial layer create of the SDL window does not respect that the window isn't created on a HDPI display, only once it is resized for the first time.

Any clues?

**Comment by slouken** [comment]
High DPI support is being reworked for SDL 3.0. If it's easy, could you try using the latest main code?
https://github.com/libsdl-org/SDL.git

The migration guide is here, to help you figure out what changed:
https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md

**Comment by fhoenig** [comment]
Is the main branch reasonably stable? Looks like a lot of work to rename all kinds of things.

**Comment by slime73** [comment]
If I'm understanding right: the problem is SDL_Metal_GetDrawableSize is returning the wrong size (effectively what it would be on your secondary highdpi display, not what it is on the primary low-dpi display where the window was created)?

SDL3 removed SDL_Metal_GetDrawableSize and its implementation, so I think the same issue won't exist there just because of that.

I haven't tested/verified but I think I might see the problem in SDL2's code: the pixel size of the Metal view / layer is computed when it's created, but before it's attached to the SDL window's main content view. So I guess it doesn't know it should be inside the low-dpi monitor by that point?

**Comment by slime73** [comment]
@fhoenig do you think you could test this SDL2 change? https://github.com/slime73/SDL/tree/sdl2-metal-drawablesize if it works for you I'll make a pull request so it gets into mainline SDL.

I don't have a setup that's easily able to test that situation right now, but if my hunch above was correct then that change should fix it.

**Comment by fhoenig** [comment]
Hi @slime73 -

Thank you for taking the time to look into it!
Let me see if I get the time later today or tomorrow. Sounds like you found it though. Fingers crossed.

**Comment by fhoenig** [comment]
Yes that fixed it.

**Comment by slime73** [comment]
Great, thanks for testing!

**Comment by fhoenig** [comment]
Appreciate you :-)
