### ISSUE TITLE
SDL3  SDL_RenderWindowToLogical mouse coordinates never reach right-most or bottom-most pixel of window with desktop scaling

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#7221]
SDL3 latest source, Win 10, desktop scale of 1.5. Mouse coordinates come through as scaled window points, and right-most and bottom-most mouse coordinates do not convert properly with SDL_RenderWindowToLogical. 1079 would come out as 1078.75 for example, which happens even when window size matches logical size pixel-for-pixel.

**Comment by slouken** [comment]
There's a massive change that just went in that should take care of this. Note that the coordinate function name changed, you can use the `rename_symbols.py --all-symbols` script to automate this on your source code.

Please let me know how this goes for you!

**Comment by AntTheAlchemist** [comment]
@slouken I manually rename as-i-go, so I can scrutinise the changes :-) 

Okay, recent massive change takes a bit of getting used to. My first attempts resulted in horrible blurring due to the rendered scene being scaled to screen coordinates, rather than the coordinates scaled. Then I found `SDL_LOGICAL_PRESENTATION_STRETCH` which seems to be exactly what I've wanted for a long time. Overscan works now too. 

It's a little hard to understand what's going on behind the scenes at first, regarding coordinates scaled, or is the final render being scaled.

Testing on Nexus 7, I noticed the pixel width of the renderer was +1 larger than the screen resolution, then the tablet's battery died. I'll do more tests on the mouse coordinates after my body and tablet are recharged :-)

**Comment by slouken** [comment]
Can you clarify a bit what you expected vs what you saw?

One of the things I'm trying to do is improve the documentation around this, in addition to the functionality, so if you have suggestions for improvement, please let me know!

**Comment by AntTheAlchemist** [comment]
@slouken I’ve been experimenting with `SDL_SetRenderLogicalPresentation`. I understand a lot of thought and work has been put into this and it seems sound in principle, but I see it causing a lot of problems for devs. Please bear with me while I present my case as best I can 😄 

Every `SDL_RendererLogicalPresentation` mode I tried on Windows 10 with desktop scaling resulted in a jagged (SDL_SCALEMODE_NEAREST) or blurred (SDL_SCALEMODE_BEST) output. DPI-awareness embedded in the .exe is ignored. So the only way to get a pixel-perfect render was to use SDL_LOGICAL_PRESENTATION_DISABLED and `SDL_SetRenderScale` (after a `SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED` event) to manually scale coordinates myself. I am guessing `SDL_RendererLogicalPresentation` renders to a target texture smaller than the pixel-size of the window and up-scaling? Why doesn’t it up-scale the render coordinates to the pixel-size of the window? That way there will be no blurring or jagged rendering?

The other issue is that I expected mouse coordinates to be scaled to match rendering coordinates. I am also still having a problem with the right-most and bottom-most mouse coordinate never being hit when being scaled up because they’re rounded-down. For instance: a 1920 x 1080 screen resolution with a desktop scaling of 1.25 will give a bottom-right mouse coordinate of 1535 x 863. This converts to 1918.75 x 1078.75. So you never get a pixel mouse coordinate of 1919 x 1079 as expected, even with SDL_LOGICAL_PRESENTATION_DISABLED, because mouse coordinates are still subject to desktop scaling. This wasn’t the case when we were able to DPI-aware the application.

Hopefully that makes sense. Either I am misunderstanding / misusing this feature, or there's a problem.

**Comment by slime73** [comment]
> For instance: a 1920 x 1080 screen resolution with a desktop scaling of 1.25 will give a bottom-right mouse coordinate of 1535 x 863.

Does it give an integral value, or a fractional value there? Mouse coordinates are floats now so if the backend supports it, the value could be fractional. If it is an integral value, maybe something is rounding it in the Windows backend before it pushes the event.

**Comment by AntTheAlchemist** [comment]
@slime73 to clarify, the bottom-right mouse coordinates are floats: 1535.00 x 863.00, which is accurate. You can never convert from a bottom-right screen coordinate to the bottom-right pixel when scaling is in effect. 863.00 x 1.25 = 1078.75. This is why we need mouse coordinates to be pixels like before, not scaled window points.

**Comment by slime73** [comment]
At a DPI scale of 1.25 I'd expect the bottom right mouse coordinate to be `(1535.2, 863.2)` - since that's `(1919 / 1.25, 1079 / 1.25)`, so it does seem like there's rounding happening in the Windows backend before being pushed to a higher level. If that rounding is removed then you'd be able to convert to accurate pixel coordinates like you're expecting.

**Comment by AntTheAlchemist** [comment]
Yes, there's definitely something rounding down the right and bottom most screen coordinate. If that's removed, that'll fix that problem. 

There's still the problem of the new scaling logic forcing apps to be blurry or jagged by obscuring away the native resolution of the monitor.

**Comment by slouken** [comment]
> @slouken I’ve been experimenting with `SDL_SetRenderLogicalPresentation`. I understand a lot of thought and work has been put into this and it seems sound in principle, but I see it causing a lot of problems for devs. Please bear with me while I present my case as best I can 😄
> 
> Every `SDL_RendererLogicalPresentation` mode I tried on Windows 10 with desktop scaling resulted in a jagged (SDL_SCALEMODE_NEAREST) or blurred (SDL_SCALEMODE_BEST) output. DPI-awareness embedded in the .exe is ignored. So the only way to get a pixel-perfect render was to use SDL_LOGICAL_PRESENTATION_DISABLED and `SDL_SetRenderScale` (after a `SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED` event) to manually scale coordinates myself. I am guessing `SDL_RendererLogicalPresentation` renders to a target texture smaller than the pixel-size of the window and up-scaling? Why doesn’t it up-scale the render coordinates to the pixel-size of the window? That way there will be no blurring or jagged rendering?

Previously the logical size implementation used scale and viewport the way you described, but that had a number of problems:
* It prevented the application from using scale and viewport
* Overscan was only possible if the underlying renderer supported viewport coordinates outside the output bounds
* When the window was resized the view contents and viewport were reset

The implementation was changed so that applications could naively create content at a specific scale and it would be rendered smoothly moving across multiple density displays. This corresponds to the "high DPI unaware" state on Windows. Applications which want pixel perfect rendering should disable this, entering "high DPI aware" state by handling the scaling and output as appropriate.

The new implementation also makes it possible to easily switch presentation mode without having to change the size of the content, automatically redisplaying as needed based on the new mode.

An approach which would get the benefits of both would be to set the logical size equal to the display output and then set the scale as desired for rendering.

> The other issue is that I expected mouse coordinates to be scaled to match rendering coordinates. I am also still having a problem with the right-most and bottom-most mouse coordinate never being hit when being scaled up because they’re rounded-down. For instance: a 1920 x 1080 screen resolution with a desktop scaling of 1.25 will give a bottom-right mouse coordinate of 1535 x 863. This converts to 1918.75 x 1078.75. So you never get a pixel mouse coordinate of 1919 x 1079 as expected, even with SDL_LOGICAL_PRESENTATION_DISABLED, because mouse coordinates are still subject to desktop scaling. This wasn’t the case when we were able to DPI-aware the application.

I'll double check this. The mouse coordinates should be float, so converting from pixels to window coordinates and back should work.

**Comment by AntTheAlchemist** [comment]
@slouken the pros of this feature are very nice and useful and work well. The con is that apps will be blurred or jagged as a result, taking us back to the horrible way Windows scales old apps. If it's really unavoidable then this needs to be stressed in the documentation somehow, so devs are aware and can opt to using the benefits of both as you suggested. It's a difficult subject to get to grips with, especially if you're used to SDL2. My experience is very narrow, so I would be interested to see how the wider community get on with this feature.

Can mouse coordinate events come through as pixels if SDL_LOGICAL_PRESENTATION_DISABLED is used? Or can they be scaled to the logical size by default, so they match the rendering points? I see devs getting frustrated that mouse coordinates aren't what they expect.

**Comment by slouken** [comment]
The mouse coordinate bug is fixed in b9773be3b.

Logical presentation is literally "the horrible way Windows scales old apps", so your analysis is correct.

What we could do for SDL 3.0 is not set logical size by default, and just say "here's how it works, pick the approach you want in your application".

**Comment by AntTheAlchemist** [comment]
@slouken that fixes it, thank-you. Please don't hate me, but I did notice this fix creates 1 artefact mouse event as the mouse leaves the window, with coordinates outside of the window, which technically should be considered global mouse events but come through without global capture on. Only happens when the mouse leaves bottom or right side of the window. I don't know if this would cause problems, is considered a bug, or a caveat, but I thought it was worth mentioning, before closing this issue.

As for the rest of the logical scaling; as it stands, it works well and all the functionality is there to get access to pixel-perfect rendering with the benefits of letterboxing, et all - it's just a little tricky to set up and the default behaviour may not be what devs expect. I'd be interested to see what others devs make of a pre-release.

**Comment by slouken** [comment]
What is the exact coordinate of the mouse event outside the window?

**Comment by AntTheAlchemist** [comment]
Actually, the rogue mouse event is the edge coordinate rounded down, it comes after the correct right-most / bottom-most coordinate. So as I move the mouse right off the window I get 1226.400024 x 391.200012, then 1227.199951 x 391.200012 (which should be the last event), then 1227.000000 x 391.200012 at the same time as the SDL_WINDOW_MOUSE_LEAVE event

**Comment by AntTheAlchemist** [comment]
So the last event clamps the coordinate back to the old value before the fix.

**Comment by slouken** [comment]
Fixed!

**Comment by AntTheAlchemist** [comment]
These are the mouse events I'm getting when sliding a mouse off the right side of a window of width 1228. If I slide the mouse off slowly, the last event is 1227.199951, which converts to 1534 pixels nicely, otherwise I get 1533.75 pixels.
```
0:02:39.357 WINDOW_MOUSE_LEAVE
0:02:39.357 Mouse_Motion #0 1227.000000 x 236.000000 relative +1.400024 x +0.000000
0:02:39.310 Mouse_Motion #0 1225.599976 x 236.000000 relative +51.199951 x +0.000000
0:02:39.295 Mouse_Motion #0 1174.400024 x 236.000000 relative +14.400024 x +0.800003
```

**Comment by AntTheAlchemist** [comment]
Oh Android, I am (current SDL3 source) getting SDL_WINDOW_MOUSE_LEAVE events when hitting the bottom and right of the screen in a full-screen app. Probably related to this bug.

**Comment by slouken** [comment]
This no longer happens in the new high DPI model.
