### ISSUE TITLE
Setting a Parent or Owner Window (whether OS-native or SDL Window)

### ISSUE THREAD

**Issue by time-killer-games** [libsdl-org/SDL#7231]
Something similar to what I'm doing here, making my dialog have an owner and then place the dialog in the center of the parent window's size/position, and if parent is zero or nullptr than ignore the parent/owner paremeter.

https://github.com/time-killer-games/libfiledialogs/blob/6a169748b115ae26295ad5bbfa4b5d2ec7f788e9/filedialogs/filedialogs.cpp#L248-L333

Note my code only covers Win32 WinAPI, macOS AppKit, and X11 Xlib platforms. Wayland and anything else which may exist out there still needs fresh code written. Ignore the pointer to integer casting my code does, that is unique to my use case.

**Comment by slouken** [comment]
Does SDL_SetWindowModalFor() do what you need?

**Comment by time-killer-games** [comment]
> Does SDL_SetWindowModalFor() do what you need?

Yes, actually! Thank you for bringing that one to my attention.

**Comment by slouken** [comment]
You’re welcome!
