### ISSUE TITLE
SDL_GetDisplayForWindow() returns the wrong display when an exclusive fullscreen window is moved

### ISSUE THREAD

**Issue by Kontrabant** [libsdl-org/SDL#7254]
For exclusive fullscreen windows, `SDL_GetDisplayForWindow()` defaults to directly grabbing the display ID from the fullscreen mode:

https://github.com/libsdl-org/SDL/blob/375bde8a4fc6a5ca413dea13c3e47de1bae974a8/src/video/SDL_video.c#L1255-L1261

The issue is that, when the OS moves an exclusive fullscreen window to another display via shortcut keys, returning the display ID in the existing fullscreen mode means that `SDL_GetDisplayForWindow()` is returning where the window was, rather than where it is after the move. Subsequently, `SDL_CheckWindowDisplayChanged()` doesn't see that the window has moved, so the display changed event is never sent, the display changed handler function is never called, and the fullscreen parameters are never updated. The window can now be on a new display, but SDL still thinks and reports that it is on the previous display.

There are two ways to solve this:
- Change `SDL_GetDisplayForWindow()` to first try to retrieve the fullscreen window position via the window coordinates, and only fall back to grabbing the display from the fullscreen mode if this fails.
- Implement the `GetDisplayForWindow` backend driver function for all desktops that handle multiple displays and return the true position of the window in these cases (Mac has it, Win32, Wayland, and X11 would need it).

The former would obviously be easier, but I'm not sure if there are cases where that behavior can fail or isn't desirable. Thoughts?

**Comment by slouken** [comment]
We could try the first approach and then implement a backend `GetDisplayForWindow` for cases where this isn't correct. I didn't do that by default because I'm not sure how display positions change when fullscreen modes are applied on the various platforms.

**Comment by slouken** [comment]
BTW, the fullscreen mode should probably be changed when the display is changed, so the mode has the correct data. On some platforms the mode has platform-specific data used to change or restore the mode, so having that refer to the correct platform data is important.
