### ISSUE TITLE
Empty window on Win7 with classic desktop theme

### ISSUE THREAD

**Issue by jwt27** [libsdl-org/SDL#7258]
I first reported this for [Furnace](https://github.com/tildearrow/furnace/issues/851).  Thought I'd report it here too.

When using the (default) D3D9 renderer with the Classic desktop theme (no Aero/DWM) on Windows 7, nothing is ever drawn to the window.  More specifically, `IDirect3DDevice9_Present(...)` always returns `D3DERR_DEVICELOST`.

Don't know if this is something that can be fixed in the D3D9 renderer.  A possible solution is to prefer the D3D11 renderer, when that is available.  But maybe there is already some reason why currently D3D9 is at the top of the list.

**Comment by slouken** [comment]
D3D9 had the best compatibility for a long time. With SDL3, we've made D3D11 the default renderer.

**Comment by Squall-Leonhart** [comment]
> D3D9 had the best compatibility for a long time. With SDL3, we've made D3D12 the default renderer.

how is this relevant to an issue on an OS that doesn't implement D3D12

**Comment by slouken** [comment]
Sorry, I meant D3D11.
