### ISSUE TITLE
X11: small glitch when creating a window.

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7259]
On linux / X11 (maybe other, but not on Wayland)
Calling `./testsprite`
It seems that a first black window is opened first. Then immediately after, the correct window is opened. It makes a small visual glitch.

**Comment by slouken** [comment]
This is caused by the window first opening without the OpenGL flag, and then it being recreated with that flag by the renderer.

**Comment by slouken** [comment]
I fixed this with SDL_CreateWindowAndRenderer(), but this will happen if you create a visible window without the OpenGL flag and then create a renderer later that uses OpenGL. If you're not using SDL_CreateWindowAndRenderer(), you should create your window hidden, then create your renderer, and then show it.
