### ISSUE TITLE
macOS 10.15 Apple clang 12.0.0 build failed

### ISSUE THREAD

**Issue by knell** [libsdl-org/SDL#7264]
Xcode 12.4
% g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix

src/thread/pthread/SDL_systhread.c:151:52: error: too many arguments to function call, expected 1, have 2
            if (pthread_setname_np(pthread_self(), name) == ERANGE) {
                ~~~~~~~~~~~~~~~~~~      

pthread_setname_np() accepts only one argument 'name' on this platform

**Comment by slime73** [comment]
That file has an Apple-specific path via the preprocessor to make sure `pthread_setname_np` is only called with a single argument, but it seems your build setup doesn't think it's compiling for macOS (or maybe it thinks the system doesn't have `dlopen`, which is always available on macOS).

So I guess it's a local build setup issue?

**Comment by knell** [comment]
Well, tbh, I have no idea, it's just clean xcode with no anything installed, build ran using cmake. I have just downloaded last 2.26.3 version and tried to build, previous version was building with no issues.

**Comment by sridenour** [comment]
Have you tried using the Xcode project that SDL ships with?

**Comment by slouken** [comment]
I think this is an issue with the older toolchain. I don't have access to that here, but I'll leave this bug open in case someone else comes along and has a patch to fix this. @Wohlstand?

**Comment by Wohlstand** [comment]
I have several vidtual machines with the stuff, I could make a shot.

**Comment by slouken** [comment]
No response, I'll go ahead and close this for now. Please let us know if it's still an issue.

**Comment by Wohlstand** [comment]
Huh, I just forgot about this one... I'll try to test some on my VMs very soon.

**Comment by Wohlstand** [comment]
Okay, for a test purposes, I installed the same Xcode version to the Catalina VM, and the same CLang version:
```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
SDL2 branch has been built successfully via CMake and make. Now testing other ways and SDL3...

**Comment by Wohlstand** [comment]
SDL3 is also built successfully with CMake build. Now let me try Xcode builds...

**Comment by Wohlstand** [comment]
Via Xcode latest SDL2 branch builds fine:
![изображение](https://github.com/user-attachments/assets/14894add-4b17-47e3-baff-2169c7f45f51)

However, SDL3 won't open with THIS Xcode 12.4:
![изображение](https://github.com/user-attachments/assets/59159ea0-3168-410d-8770-d04690cf4350)

Then, sounds like the problem is completely local.

Anyway, I found that it used the SDK for 11.1 rather than for 10.15:
![изображение](https://github.com/user-attachments/assets/f8db560b-d1de-4149-b9d9-30c5b1d02633)


And then, I tried to build SDL3 with:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/ -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 ..
```

And then it fails at other places:
```
[ 38%] Building C object CMakeFiles/SDL3-shared.dir/src/SDL_properties.c.o
/Users/vitaly/Repos/SDL3/src/gpu/metal/SDL_gpu_metal.m:89:5: error: 'MTLPixelFormatB5G6R5Unorm' is unavailable: not available on macOS
    MTLPixelFormatB5G6R5Unorm,  // B5G6R5_UNORM
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:43:5: note: 'MTLPixelFormatB5G6R5Unorm' has been explicitly marked unavailable here
    MTLPixelFormatB5G6R5Unorm API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(macos, macCatalyst) = 40,
    ^
/Users/vitaly/Repos/SDL3/src/gpu/metal/SDL_gpu_metal.m:90:5: error: 'MTLPixelFormatBGR5A1Unorm' is unavailable: not available on macOS
    MTLPixelFormatBGR5A1Unorm,  // B5G5R5A1_UNORM
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:46:5: note: 'MTLPixelFormatBGR5A1Unorm' has been explicitly marked unavailable here
    MTLPixelFormatBGR5A1Unorm API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(macos, macCatalyst) = 43,
    ^
/Users/vitaly/Repos/SDL3/src/gpu/metal/SDL_gpu_metal.m:91:5: error: 'MTLPixelFormatABGR4Unorm' is unavailable: not available on macOS
    MTLPixelFormatABGR4Unorm,   // B4G4R4A4_UNORM
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:45:5: note: 'MTLPixelFormatABGR4Unorm' has been explicitly marked unavailable here
    MTLPixelFormatABGR4Unorm  API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(macos, macCatalyst) = 42,
    ^
/Users/vitaly/Repos/SDL3/src/gpu/metal/SDL_gpu_metal.m:3862:39: error: no known instance method for selector 'supportsBCTextureCompression'
                    [renderer->device supportsBCTextureCompression] &&
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 38%] Building C object CMakeFiles/SDL3-shared.dir/src/SDL_utils.c.o
/Users/vitaly/Repos/SDL3/src/gpu/metal/SDL_gpu_metal.m:4086:51: error: use of undeclared identifier 'kCGColorSpaceITUR_2100_PQ'; did you mean 'kCGColorSpaceITUR_2020_PQ'?
            SwapchainCompositionToColorSpace[3] = kCGColorSpaceITUR_2100_PQ;
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                  kCGColorSpaceITUR_2020_PQ
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGColorSpace.h:134:29: note: 'kCGColorSpaceITUR_2020_PQ' declared here
CG_EXTERN const CFStringRef kCGColorSpaceITUR_2020_PQ
                            ^
5 errors generated.
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/gpu/metal/SDL_gpu_metal.m.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/vitaly/Repos/SDL3/src/dialog/cocoa/SDL_cocoadialog.m:25:9: fatal error: 'UniformTypeIdentifiers/UTType.h' file not found
#import <UniformTypeIdentifiers/UTType.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by slouken** [comment]
From the SDL3 README-macos.md:
`Please note that building SDL requires at least Xcode 12.2 and the 11.0 SDK.`

You should be able to tweak the Xcode version in the project to open it and build with the older Xcode. I don't know what version should be put there though.

**Comment by Wohlstand** [comment]
I just changed the `objectVersion` to the 54 in a VSCode, and it opens.

**Comment by Wohlstand** [comment]
And now it fails on "3 duplicated symbols"
![изображение](https://github.com/user-attachments/assets/b96d9f8a-19d4-4f72-a29d-f46162cdc40c)

**Comment by slouken** [comment]
I've updated the project so it should build on Xcode 12.

**Comment by Wohlstand** [comment]
Ye, it opens and builds, but the build at final just fails for the in-code problem.

**Comment by slouken** [comment]
What's an "in-code" problem?

**Comment by Wohlstand** [comment]
> What's an "in-code" problem?

In my screenshot, you can see that it attempts to link both cocoa and dummy dialogue related modules, and the thing fails to link because of function names collision.

**Comment by slouken** [comment]
Did you update? I fixed that.

**Comment by Wohlstand** [comment]
Let me try that... Not yet, and I powered off my VM for now, going to boot it again...

**Comment by Wohlstand** [comment]
Okay, now it builds just fine!
![изображение](https://github.com/user-attachments/assets/0748855e-0b42-40e7-9b91-ffe5ab7a56fa)

**Comment by slouken** [comment]
Yay! Thanks!

**Comment by Wohlstand** [comment]
I am glad to verify that! Have a good time!
