### ISSUE TITLE
Problems with CMake when using SDL2_image, SDL2_ttf, SDL2_mixer and SDL_net with SDL2

### ISSUE THREAD

**Issue by ingvart** [libsdl-org/SDL#7267]
Hello

Using CMake, I am trying to setup a development environment using SDL2 with SDL2_image, SDL2_ttf, SDL2_mixer and SDL2_net.

I have a simple main.cxx file in a directory and the following subdirectories in the same folder:
    SDL2
    SDL2_image
    SDL2_ttf
    SDL2_audio
    SDL2_net

My CMakeLists.txt in the "main.cxx"-folder with these subfolders looks like this:

```
cmake_minimum_required(VERSION 3.14)

project(main)
add_executable(main main.cxx)

#Not sure if these do any good, but I found them somewhere. Don't seem to make a difference:
set(SDL2_DIR "SDL2")
set(SDL2_PATH "SDL2")

target_include_directories(${PROJECT_NAME} PUBLIC ${PROJECT_SOURCE_DIR}/SDL2_image)
target_include_directories(${PROJECT_NAME} PUBLIC ${PROJECT_SOURCE_DIR}/SDL2_ttf)
target_include_directories(${PROJECT_NAME} PUBLIC ${PROJECT_SOURCE_DIR}/SDL2_mixer/include)
target_include_directories(${PROJECT_NAME} PUBLIC ${PROJECT_SOURCE_DIR}/SDL2_net)

add_subdirectory(SDL2)
add_subdirectory(SDL2_image)
add_subdirectory(SDL2_ttf)
add_subdirectory(SDL2_mixer)
add_subdirectory(SDL2_net)

target_link_libraries(ATISControl 
    SDL2
    SDL2main
    SDL2_image
    SDL2_ttf
    SDL2_audio
    SDL2_net
)
```

Trying to build this gives me this issue:

```
[build] Starting build
[build] Build finished with exit code -1
[cmake] -- Could NOT find Python (missing: Python_EXECUTABLE Interpreter) 
[cmake] -- Configuring done
[cmake] CMake Error: install(EXPORT "SDL2ImageExports" ...) includes target "SDL2_image" which requires target "SDL2" that is not in any export set.
[cmake] CMake Error: install(EXPORT "SDL2_ttfTargets" ...) includes target "SDL2_ttf" which requires target "SDL2" that is not in any export set.
[cmake] CMake Error: install(EXPORT "SDL2MixerTargets" ...) includes target "SDL2_mixer" which requires target "SDL2" that is not in any export set.
[cmake] -- Generating done
[cmake] CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I've tried to serach for help with this problem, but it is not easy to find anything useful.

I'm using mingw on Windows (w. Visual Studio Code).

Mingw info:
```
This is the winlibs 64-bit standalone build of:
- GCC 12.2.0
- GDB 12.1
- MinGW-w64 10.0.0 (linked with ucrt)
- GNU Binutils 2.40
- GNU Make 4.4
- PExports 0.47
- dos2unix 7.4.3
- Yasm 1.3.0
- NASM 2.16.01
- JWasm 2.12pre
- ccache version 4.7.4
- CMake 3.25.1
- ninja 1.11.1
- doxygen 1.9.6
```

I appreciate slightly elaborated replies as I am learning CMake. Thank you!

**Comment by madebr** [comment]
This error happen**ed** when you configure**d** a project with vendored SDL2 + satellite libraries with `-DSDL2TTF_INSTALL=ON -DSDL2MIXER_INSTALL=ON -DSDL2IMAGE_INSTALL=ON -DSDL2NET_INSTALL=ON` but without `-DSDL2_DISABLE_INSTALL=ON`.
CMake compained the SDL2_xxx library refers to a SDL2 library, but that library was not being installed.

You can fix it by reconfiguring with `-DSDL2TTF_INSTALL=OFF -DSDL2MIXER_INSTALL=OFF -DSDL2IMAGE_INSTALL=OFF -DSDL2NET_INSTALL=OFF` or `-DSDL2_DISABLE_INSTALL=OFF`.

I patched the current masters of all SDL satellite libraries to force disable installation when SDL is built in the same cmake run and SDL installation is disabled.

SDL2: https://github.com/libsdl-org/SDL_mixer/commit/6abf246af948ece4d7ee7471ab304a566ded7e1e https://github.com/libsdl-org/SDL_image/commit/44354bc1a5b472e1755761fb1405d768a69bbb74 https://github.com/libsdl-org/SDL_ttf/commit/c643f520c22d3e6442cc7cda4026c9cd1e6e52ec https://github.com/libsdl-org/SDL_net/commit/d98c71106d6fa5245741ef340f1c89c790a5cbf4
SDL3: https://github.com/libsdl-org/SDL_mixer/commit/55c0899c9c064f31b998d1f0993fc2d124d83aeb https://github.com/libsdl-org/SDL_image/commit/3705bb808267b8de1b9fec83d9f8380ec25a3ceb https://github.com/libsdl-org/SDL_ttf/commit/ac67507a5f2cf381f736446f18a3d4b16b1ebf3d

**Comment by ingvart** [comment]
Thank you.

Not being too good at CMake yet, but I did the following, based on your reply:

In SDL CMakeLists.txt I changed the following
```

if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  set(SDL2_SUBPROJECT OFF)
else()
  set(SDL2_SUBPROJECT OFF)   # <=  Changed this to OFF
endif()

```

I got this to work. I'll probably try a new release of the library later on. Thank you very much!

**Comment by msscaroso** [comment]
Many thanks @ingvart @madebr

**Comment by msscaroso** [comment]
If anyone is looking into this in the future,
this is how it worked for me:

```cmake
cmake_minimum_required(VERSION 3.24)
project(studying_sdl2)

set(CMAKE_C_STANDARD 17)
set(SDL2_DIR third_party/SDL)

add_executable(studying_sdl2 src/main.c)

set(SDL2_IMAGE_INSTALL OFF)
set(SDL2_DISABLE_INSTALL OFF)

add_subdirectory(third_party/SDL)
add_subdirectory(third_party/SDL_image)

target_link_libraries(studying_sdl2 SDL2 SDL2_image)

```

(SDL2 and SDL2_Image are submodules on ./third_party/SDL and ./third_party/SDL_Image)
