### ISSUE TITLE
cmake: broken final report of EXTRA INCDIRS

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#7273]
Substitutions like `$<LOWER_CASE:$<CONFIG>>` and alsa stuff & all don't seem to be performed:
```
--  EXTRA INCDIRS: -I/home/sezero/SDL3/b/include-config-$<LOWER_CASE:$<CONFIG>> -I/home/sezero/SDL3/b/include -I/home/sezero/SDL3/include -I$<TARGET_PROPERTY:ALSA::ALSA,INTERFACE_INCLUDE_DIRECTORIES> -I/usr/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/ibus-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
```

**Comment by madebr** [comment]
I argue this is no issue: this output is printed to stderr and is an extra service for the builder for easier debug, not something that should be interpreted as the final compile options.

CMake creates build scripts (=build.ninja/Makefile/SDL3.vcxproj) in 2 phases: CMake script evaluation and build system generation phase.
For single-config build systems (=Ninja/make files) the configuration is well defined, but for multi-config build systems, such as Visual Studio/Ninja Multi-Config, config can be multiple values.

This behavior is also present in SDL_image and SDL_mixer for getting the library names of the built-in decoders: CMake prints generator expressions to stderr, but passes the correct values to the compiler.
