### ISSUE TITLE
Offscreen backend for platforms other than Linux?

### ISSUE THREAD

**Issue by quyykk** [libsdl-org/SDL#7290]
For Linux there is an `offscreen` video backend that uses EGL to render to an offscreen texture. Unless using something like ANGLE, this is not available on say Windows.

Would it be possible to add such an offscreen backend for Windows (and maybe MacOS) as well? Using OpenGL.

This is 100% out of my expertise, so it's possible that this isn't possible in the first place. From a bit of Googling it would seem like there is no general solution available and I would have to render to a texture myself instead of the backbuffer, but idk.

So is something like this possible? Thanks!

**Comment by nfries88** [comment]
I haven't done this since the D3D9 days, but you don't need actually need a window to create a D3D12 context or vkDevice so don't see why this shouldn't be achievable fairly portably.

**Comment by slime73** [comment]
I believe you do need a window when creating an OpenGL context on some platforms.

But SDL allows you to create a hidden window and an OpenGL context for it.

Render target textures (textures attached to Framebuffer Objects in OpenGL's terminology) are the idiomatic way to render to an offscreen texture across platforms as a general solution. Is that sufficient for your needs?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
