### ISSUE TITLE
Memory 'leak' on SDL_Quit

### ISSUE THREAD

**Issue by opadin** [libsdl-org/SDL#7302]
Hi folks,

I am not shure, if we can really speak of mem-leak on the exit of the program. Wenn the app is closed, the OS will grab the used memory in either way. On the other hand, imho SDL_Quit SHOULD free all used mem, so I can re-init it, if I would do so.

I would not open this issue, if I have the opportunity to fix it myself (e.g. until now I called SDL_TLSCleanup() myself after SDL_Quit() ... which is fixed in the latest version ... thumbs-up!). But there is a new 'leak' with the windows mouse system scale (I am working only on Windows, so can only say about things on windows. Used version 2.26.1): the (re)allocated array of scale values is never freed.

**SDL-release-2.26.1\src\events\SDL_mouse.c**
```c
int
SDL_SetMouseSystemScale(int num_values, const float *values)
{
    SDL_Mouse *mouse = SDL_GetMouse();
...
    
    v = (float *)SDL_realloc(mouse->system_scale_values, num_values * sizeof(*values));
    if (!v) {
```

Greets,
Opadin.

**Comment by 1bsyl** [comment]
Thanks ! 
This is fixed in 
main: https://github.com/libsdl-org/SDL/commit/93ed3148baf8bc9c5f016a2de7ece2e842cc29d3
SDL2: https://github.com/libsdl-org/SDL/commit/45e5f0f10bd44022cb3df3808eaa14ebb1eb2e4e
