### ISSUE TITLE
Merge version 2 in 3

### ISSUE THREAD

**Issue by kevin2kevin2** [libsdl-org/SDL#7309]
Fixes and minor improvements had been made in version 2. But after release of new versions of version 2, it seems that no merge was done in version 3. In consequence, the fixes and minor improvements done in version 2 are not in version 3.

It seems to me that a merge to version 3 should be done after a version 2 release. But, of course, we should not wait the next one, as the last version 2 released had not been merged (or I sadly missed it).

**Comment by slime73** [comment]
Generally when a fix is made it's committed to main (SDL3) first, and then backported to the SDL2 branch soon after, unless the fix is actually SDL2-specific.

If there are commits where that didn't happen, it might be useful for someone to gather a list of them I guess?

**Comment by kevin2kevin2** [comment]
Sorry. I wrongly assumed that the "standard" way would be used and I opened this issue due to the fact that I did not see its use. But there is also the fact that I made 3 merge requests for version 2.26 (https://github.com/libsdl-org/SDL/pull/7289, https://github.com/libsdl-org/SDL/pull/7307 and https://github.com/libsdl-org/SDL/pull/7308), should I first redo them for `main` branch and then backport them if it has been accepted for `main` branch?

**Comment by sezero** [comment]
>   I made 3 merge requests for version 2.26 (#7289, #7307 and #7308), should I first redo them for `main` branch and then backport them if it has been accepted for `main` branch?

Yes please. If the patches are accepted and are found worthy of backporting to SDL2, that will be done so later.

Closing this ticket.
