### ISSUE TITLE
lld-link: warning: found main and WinMain; defaulting to /subsystem:console

### ISSUE THREAD

**Issue by dortamiguel** [libsdl-org/SDL#7315]
Hi, I'm on Windows 11 and using clang 15.07 with target x86_64-pc-windows-msvc.

When I link my program I get the following warnings
```
lld-link: warning: found main and WinMain; defaulting to /subsystem:console
lld-link: warning: found both wmain and main; using latter
```

These are my link flags
```
ccache clang++ -std=c++20 -O2 -fuse-ld=lld -Llib/windows/SDL2 -lSDL2 -lSDL2main -lshell32 -luser32 -lgdi32
```

The problem I have is that when I open the executable after SDL_CreateWindow gets called, instead of opening a window it opens a terminal.

Is this related to how I set my main?

It looks like this now
```
int main(int, char **) {
```

**Comment by madebr** [comment]
Do you do `#include "SDL.h"` in the file where you're implementing the `main` function?
Your question looks very similar to [this FAQ item](https://wiki.libsdl.org/SDL2/FAQWindows#i_get_undefined_reference_to_sdl_main_...).

**Comment by slouken** [comment]
You probably need to add `-mwindows` to your link options.

**Comment by dortamiguel** [comment]
In the ende this is what it worked for me `-Llib/windows/SDL2 -w -Wl -lSDL2main -lSDL2 -Xlinker /subsystem:windows` also `#include <SDL2/SDL.h>` had to be in the main of the program too
