### ISSUE TITLE
SDL_CreateWindow flags will hit limit soon 

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7321]
SDL_CreateWindow flags will hit limit soon ..
https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_video.h#L110
maybe we should use 64 bits here for flags ?

**Comment by Kontrabant** [comment]
The C standard states that enum values are of type int, unless the value of the integer constant expression given by `=` is not representable by an int, in which case a suitably sized type will be used. This only changes in C23, which mirrors c++11 and allows the underlying type to be explicitly defined.

So yes, tacking on ULL for 64 bit enum constants _should_ be OK, as long as all the compilers follow the standard.

**Comment by slime73** [comment]
`SDL_CreateWindow` and `SDL_GetWindowFlags` both use a 32 bit (unsigned) integer for flags, so those APIs would have to change if > 32 bit flag values are added.

**Comment by sezero** [comment]
> `SDL_CreateWindow` and `SDL_GetWindowFlags` both use a 32 bit (unsigned)
> integer for flags, so those APIs would have to change if > 32 bit flag
> values are added.

BTW, three of the slots in the 32 bit range, i.e. 0x00200000, 0x00400000
and 0x00800000, still aren't used, as far as I can see.

**Comment by slime73** [comment]
For reference, SDL 2.0.0 had 13 window flags when it was released. SDL 2.26.3 has 23 (so 10 flags were added across SDL2's patch history.)

**Comment by LiquidityC** [comment]
Then we should probably push it for 3.0 so there is room to grow during its patch history. I can convert my test change to a PR.

**Comment by slime73** [comment]
Since work towards a pull request is running into issues on various platforms...

If the 3 reserved flag bits are removed and sdl2-compat does its own remapping instead (I think that's possible, right?), that leaves 10 extra flag bits for SDL3 to use in the future if I'm counting right (or 9 if #7319 is added). Maybe that's enough?

**Comment by 1bsyl** [comment]
clearly, i didn't see the gap between, otherwise I wouldn't have opened the issue ... (sorry)
```
SDL_WINDOW_KEYBOARD_GRABBED     = 0x00100000,   /**< window has grabbed keyboard input */
SDL_WINDOW_VULKAN               = 0x10000000,   /**< window usable for Vulkan surface */
```

**Comment by Lokathor** [comment]
If we're adjusting the flags, can we also document if the OpenGL, Vulkan, and/or Metal flags can be combined when creating a window?
