### ISSUE TITLE
Request: Expose a function for Vulkan surface destruction

### ISSUE THREAD

**Issue by Lokathor** [libsdl-org/SDL#7322]
At the moment, `SDL_Vulkan_CreateSurface` exists to allow for surface creation, but there's no matching function for surface destruction.

Technically a person can call `vkDestroySurfaceKHR` on their own, but to do that the programmer must know that the `VkAllocationCallbacks` used during surface creation was `NULL`. This is currently the case, but isn't guaranteed to be the case.

It's probably easiest if SDL just offers a matching destruction function for each creation function.

**Comment by slouken** [comment]
Sure, feel free to create a PR for this.

**Comment by icculus** [comment]
Let's put this in 3.2, so it's there from the beginning of SDL3. I'm going to assign myself so I don't forget to do this, but I'll absolutely accept a PR if anyone else does this before I get to it!

**Comment by slouken** [comment]
Implemented by @Lephar, thanks!
