### ISSUE TITLE
Recommended CMake find_package call fails when there is only a static library

### ISSUE THREAD

**Issue by Daft-Freak** [libsdl-org/SDL#7326]
First problem I hit while trying to use SDL3 with Emscripten. I'm assuming this is supposed to work since the CMake config has a fallback to create an alias of the static target.

```
CMake Error at .../CMakeLists.txt:49 (find_package):
  Found package configuration file:

    .../lib/cmake/SDL3/SDL3Config.cmake

  but it set SDL3_FOUND to FALSE so package "SDL3" is considered to be NOT
  FOUND.
```

I _think_ this is because the fallback is after the `check_required_components` and it doesn't set `SDL3_SDL3_FOUND`.

**Comment by madebr** [comment]
What is your `find_package` command?
The SDL3 component = shared SDL3
The SDL3-static component = static SDL3

**Comment by Daft-Freak** [comment]
`find_package(SDL3 REQUIRED CONFIG REQUIRED COMPONENTS SDL3)` copied from the migration doc. I thought that because of https://github.com/libsdl-org/SDL/blob/03e69fbc0ca5cf8ca4c982240e4f1d0ac0d48f24/cmake/SDL3Config.cmake.in#L68-L77
SDL3 would also be static if there is no shared SDL3. (... and emscripten builds never have a shared lib)

**Comment by madebr** [comment]
I've created https://github.com/libsdl-org/SDL/pull/7332 that introduces the `SDL3-shared` component for a shared SDL library.
The `SDL3` component now means "shared or static SDL3 library".
