### ISSUE TITLE
Backbone One controller not recognized

### ISSUE THREAD

**Issue by 616dustin** [libsdl-org/SDL#7329]
Trying to use devilutionX (which uses SDL2 v2.0.2) with the Backbone One mfi controller and the application recognizes that a button on the controller is pressed but does not perform the corresponding action, like the button press is not sent correctly. I've submitted bugs to DevilutionX and SDL_GameControllerDB and both told me to report the issue here.

**Comment by jdactal** [comment]
I’m having the same issue with the Backbone One controller

**Comment by slouken** [comment]
This is fixed in the latest SDL release.
