### ISSUE TITLE
(Feature/Merge Request) X11/Wayland API emulation as a SDL2 app

### ISSUE THREAD

**Issue by hardBSDk** [libsdl-org/SDL#7338]
Add a X11/Wayland compatibility layer inside SDL2 for systems that don't support these display servers, the X11/Wayland API will run as a SDL2 app.

[This project](https://github.com/Abestanis/SDL2X11Emulation) have a decent X11 emulation inside SDL2.

(Wayland would be nice to have too).

**Comment by icculus** [comment]
I don't think we're going to build this into SDL itself.
