### ISSUE TITLE
Should SDL_DYNAMIC_API be renamed to SDL3_DYNAMIC_API?

### ISSUE THREAD

**Issue by chayleaf** [libsdl-org/SDL#7347]
I wouldn't be surprised if some users have set a global `SDL_DYNAMIC_API` env var on their systems, as it gives proper Wayland and Pipewire support for old binary builds of proprietary games using SDL. I wanted to set it too, but decided against it because of SDL3. If SDL3 uses the same env var name, those users would have to remove that env var from their system config.

SDL1 didn't have such a feature, so to my knowledge this is the first time this issue is being discussed.

Is this use case something SDL devs want to consider, or is this not a concern (i.e. this env var is meant to be per-app, and systemwide usage is not supported)?

**Comment by Etaash-mathamsetty** [comment]
+1
I also think it should get renamed because we don't want SDL2 apps to try calling on SDL3 or the other way around.

**Comment by chayleaf** [comment]
Apparently it already got renamed! https://github.com/libsdl-org/SDL/blob/9f21bed7293d5cb8cf992052417faced56238e1a/src/dynapi/SDL_dynapi.c#L27

The docs just use the old variable name.

**Comment by slouken** [comment]
I updated the documentation, thanks!
