### ISSUE TITLE
SDL_CreateThread segfaults when statically linking UCRT

### ISSUE THREAD

**Issue by neonmoe** [libsdl-org/SDL#7350]
While trying to figure out a segfault I was having in another program, I was setting up a minimal program that uses SDL_CreateThread. After a while of trying to find out why I was getting "missing _beginthreadex" errors, I [noticed](https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_thread.h#L96-L103) that it seems to depend on a CRT. I originally wasn't linking against any CRT, as I was under the impression that SDL would work without any, but it seems like this particular feature just really needs the CRT.

Now, dynamically linking in UCRT (ucrt[d].lib, according to [this](https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170)) made the SDL_CreateThread work great. Unfortunately, using the statically linked variant, libucrt[d].lib, seems to cause a segfault. I'd prefer the statically linked one, since based on my understanding, that would make the executable compatible with older versions of Windows which don't have the UCRT.

Here's two Visual Studio 2022 projects (note: only the Debug profiles are set up) that are identical except for the static one linking in libucrtd.lib (and changing /nodefaultlib to /nodefaultlib:library) and using /MTd, and the dynamic one linking in ucrtd.lib and using /MDd. The dynamically linked one works great, prints out "Hello, World!" when ran, while the statically linked one segfaults on SDL_CreateThread (particularly the part where it calls _beginthreadex). The SDL lib/dll files are from the 2.26.3 release.
[CreateThreadExample With Static CRT.zip](https://github.com/libsdl-org/SDL/files/10776243/CreateThreadExample.With.Static.CRT.zip)
[CreateThreadExample With Dynamic CRT.zip](https://github.com/libsdl-org/SDL/files/10776244/CreateThreadExample.With.Dynamic.CRT.zip)

The statically linked version not working seems very odd to me, and I'm almost sure that I'm just overlooking something here. However, since I could reproduce this with a very minimal VS project, and I'm getting an identical segfault in a Rust program that also happens to be statically linking the CRT, I think there might be an actual issue here.

**Comment by madebr** [comment]
In both projects you're passing `/ENTRY:WinMain` to the linker.
By calling WinMain directly, you're bypassing the static runtime startup code.
See [its documentation](https://learn.microsoft.com/en-us/cpp/build/reference/entry-entry-point-symbol). By default, a Windows window application using the CRT starts `WinMainCRTStartup`. `WinMainCRTStartup` will then call your `WinMain` function.

You should remove this argument and add `libucrtd.lib`, `libvcruntimed.lib` and `libcmtd.lib` to the list of additional link dependencies.
Or, just don't pass`/nodefaultlib` and MSVC will automatically link the static debug runtime libraries mentioned above.

**Comment by neonmoe** [comment]
Ah, of course! :facepalm: Thank you very much for the explanation.
