### ISSUE TITLE
SDL2/begin_code.h use of _... #defines elicits reserved identifier (cert-dcl37-c,cert-dcl51-cpp) warnings

### ISSUE THREAD

**Issue by nbriggs** [libsdl-org/SDL#7352]
SDL version 2.26.3

clang-tidy complains that:

```
/usr/local/include/SDL2/begin_code.h:34:9: warning: declaration uses identifier '_begin_code_h', which is reserved in the global namespace [cert-dcl37-c,cert-dcl51-cpp]
#define _begin_code_h
        ^~~~~~~~~~~~~
        begin_code_h
/usr/local/include/SDL2/begin_code.h:174:9: warning: declaration uses identifier '_HAS_FALLTHROUGH', which is a reserved identifier [cert-dcl37-c,cert-dcl51-cpp]
#define _HAS_FALLTHROUGH __has_attribute(__fallthrough__)
        ^~~~~~~~~~~~~~~~
        HAS_FALLTHROUGH
```

Note that apart from `SDL2/begin_code.h` all the other headers use a symbol starting SDL_ as a guard.  A change in `begin_code.h` would need the corresponding change in `close_code.h`.

There doesn't seem to be any reason not to use `SDL_HAS_FALLTHROUGH` instead of `_HAS_FALLTHROUGH`, either.

Meanwhile, I've turned off the cert-dcl37-c and cert-dcl51-cpp warnings.

**Comment by icculus** [comment]
This was already fixed in the main branch, so my commit only deals with SDL2.
