### ISSUE TITLE
What happen to SDL_RENDERER_TARGETTEXTURE?

### ISSUE THREAD

**Issue by jarroddavis68** [libsdl-org/SDL#7353]
I update my repo fork and tried to compile some code and SDL_RENDERER_TARGETTEXTURE seem to not be there any longer?

**Comment by slime73** [comment]
The main branch of the repository is for the in-development SDL3 now (there's a separate SDL2 branch) - I believe SDL_Render in SDL3 now requires render target support on a system in order to work, so the flag would be redundant.

**Comment by jarroddavis68** [comment]
@slime73 Ahh, gotcha. Thanks!
