### ISSUE TITLE
Should SDL_WINDOWPOS_CENTERED default to SDL_WINDOWPOS_CENTERED_DISPLAY(0)?

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#7354]
In the current `SDL_CreateWindow` logic, SDL_WINDOWPOS_CENTERED causes a call to SDL_GetDisplayIndex(0), which will error. Can we change the logic to do a `displayID = SDL_GetPrimaryDisplay();` if SDL_WINDOWPOS_CENTERED is used, rather than go through SDL_WINDOWPOS_CENTERED_DISPLAY(0), which sets an error.

**Comment by slouken** [comment]
Good point. Fixed, thanks!
