### ISSUE TITLE
Mac: Sided key modifier behavior broken

### ISSUE THREAD

**Issue by tmcdaniel-aspyr** [libsdl-org/SDL#7355]
Please see my comment on the commit that introduced the issue:
https://github.com/libsdl-org/SDL/commit/7e1088167a7cf47ca920667743e84cacb82af481#commitcomment-101380356

**Comment by sezero** [comment]
CC: @deveee , @slouken

**Comment by sezero** [comment]
Copying the op's original report here:  @slouken , @deveee : Is this correct?

---

This change leads to some undesired behavior between left and right modifiers.
As an example, using the `test/checkkeys.c` program:
hold left shift key, hold right shift key, release left shift key, release right shift key
Results in the following output:
```
Initial state: modifiers: (none)
Key pressed :  scancode 225 = Left Shift, keycode 0x400000E1 = Left Shift  modifiers: LSHIFT          <-- hold left shift
Key pressed :  scancode 225 = Left Shift, keycode 0x400000E1 = Left Shift  modifiers: LSHIFT (repeat) <-- (phantom repeat)
Key pressed :  scancode 229 = Right Shift, keycode 0x400000E5 = Right Shift  modifiers: LSHIFT RSHIFT <-- hold right shift
Key released:  scancode 225 = Left Shift, keycode 0x400000E1 = Left Shift  modifiers: LSHIFT RSHIFT   <-- release left shift (phantom LSHIFT modifier)
Key pressed :  scancode 225 = Left Shift, keycode 0x400000E1 = Left Shift  modifiers: LSHIFT RSHIFT   <-- (phantom LSHIFT press)
Key released:  scancode 229 = Right Shift, keycode 0x400000E5 = Right Shift  modifiers: LSHIFT        <-- release right shift (phantom LSHIFT modifier)

```
In `HandleModifiers`, adding a `return` after the code is found is enough to fix this behavior:
```c
    for (int i = 0; i < 12; i++)
    {
        if (code == codes[i])
        {
            if (modifierFlags & modifiers[i])
                SDL_SendKeyboardKey(SDL_PRESSED, code);
            else
                SDL_SendKeyboardKey(SDL_RELEASED, code);
            return;
        }
    }
```
It's not clear to me what the purpose is for duplicating the left side scancodes in the `codes` array, and why the "unsided" masks like `NX_SHIFTMASK` are included in the `modifiers` array.

---

**Comment by deveee** [comment]
I should have a time in next 2-3 days to look at this.

IIRC shift is duplicated in codes for older systems because there is NX_DEVICERSHIFTKEYMASK and NX_SHIFTMASK. Maybe return early if found is enough.

**Comment by tmcdaniel-aspyr** [comment]
One more point, in `Cocoa_HandleKeyEvent`, `scancode` is checked to be within bounds of `darwin_scancode_table`, but then `scancode` is passed into `HandleModifiers` where it is used unchecked as `darwin_scancode_table[scancode]`.
```
    if (scancode < SDL_arraysize(darwin_scancode_table)) {
        code = darwin_scancode_table[scancode];
    } else {
        /* Hmm, does this ever happen?  If so, need to extend the keymap... */
        code = SDL_SCANCODE_UNKNOWN;
    }
```
To avoid this, change `HandleModifiers` signature to take `code` param instead of `scancode`.

**Comment by sezero** [comment]
PING?

**Comment by kcgen** [comment]
the DOSBox Staging project is consider having to add a lookup state table to work around this new sticky-key bug (oh no, the horror!! :laughing:).

Of course, I definitely don't want our own code littered with hacks to work-around temporary bugs in external dependencies.  So this is more just a question, to check if this bug will (or can) be triaged.

If it's can be triaged ("Yeah, we see it and it's in the queue") -> that will be a big help.

But if it's too tangled up "We need this buggy behavior to correctly support older systems, so just triaging this is going to be nuanced, etc.. ) -> Then that helps too, and we can commit to a work-around for the time being.

Much thanks for catching and working on it - egardless of where the solution lies!

**Comment by deveee** [comment]
I will send a patch today

**Comment by deveee** [comment]
Please check if it fixes the issue for you:
https://github.com/deveee/SDL/commit/d0e2a0f33353cc10a8e637ad8d071c70cf6c55a4

If so, I will make a pull request.

It would be great if someone can test with devices that don't recognize left/right modifiers and don't send NX_DEVICE*MASK and just only NX_*MASK. I think it should work but I don't have a possibility to test.

**Comment by kcgen** [comment]
Thanks @deveee - @XMHat, can you try this out?

**Comment by kcgen** [comment]
@deveee, I also am unable to test it.

Unfortunately @XMHat, who opened the work around [in this PR](https://github.com/dosbox-staging/dosbox-staging/pull/2316), has blown away their account and GitHub reports it as a ghost :ghost: :face_exhaling:.

@XMHat - if you're out there and build SDL w/ commit https://github.com/deveee/SDL/commit/45a58b7882a253db29b1b1393bc2a1fe030d5955, any feedback would be appreciated!

**Comment by deveee** [comment]
I looked at some old documentation and I think it should work for old keyboards too.
https://boredzo.org/blog/archives/2007-05-22/virtual-key-codes

The command/shift/control/etc. key codes had the same values as currently SDL_SCANCODE_LCTRL/SDL_SCANCODE_LSHIFT/etc. in scancodes_darwin.h. So it should just send left modifier event.

And they also say
"On modern keyboards, there are different codes for right Command (54), right Option (61), Right Control (62), and right Shift (60)"
So in the past there was just single control/shift/etc. key code, no matter if you pressed left or right physical key.

And the ```if (either_pressed != (target_pressed || other_pressed))``` will detect if we should use old modifier mask, so again it should work.

**Comment by slouken** [comment]
Go ahead and create a PR for this, thanks!
