### ISSUE TITLE
Switching to fullscreen gets wrong values from X11_XGetWindowAttributes

### ISSUE THREAD

**Issue by neon12345** [libsdl-org/SDL#7357]
I have a simple app with a fullscreen toggle working fine on a real system but behaving wrong in qemu vm. The app prints the mouse movement events from SDL.

The system is Ubuntu with xwayland and X11 handling used internally by SDL. (SDL was updated to the latest release and xwayland is also a recent version)

The window size in fullscreen and the mouse events are wrong when running the app in qemu. It seems X11_XGetWindowAttributes is called when the app is not yet in final fullscreen mode.

The app has a window size of  200x100, but after switching to fullscreen 320x200 is reported instead of 1920x1080. I can see with gdb that  the size of 1920x1080 is reported at some point but later 320x200 is set as the final state.

**Comment by neon12345** [comment]
According to xwininfo the window is indeed 320x200 but at the same time the rendering fits the full screen.

**Comment by slouken** [comment]
We are improving the order of operations for fullscreen transitions in SDL 3, but qemu is known to have some timing issues with resolution changes. If this is affecting you outside of the emulator, please let us know, otherwise please check again when we have an SDL 3.0 release candidate.
