### ISSUE TITLE
Android Open GL demo does not work

### ISSUE THREAD

**Issue by rodrigovaras** [libsdl-org/SDL#7363]
Tried to build and run the Android demo sample and I get:
I did some research and I notice somebody open a similar bug that was closed.
It seems the situation has not changed since I get this (problems with bluetooth permissions):

Java.Lang.RuntimeException: 'Unable to start activity ComponentInfo{com.companyname.AndroidDemo/crc640cc520f458eee55e.MainActivity}: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@a7e74ba0: AdapterService getBondedDevices'

**Comment by AntTheAlchemist** [comment]
Where is this demo?
Which version of SDL are you trying out?

I'm not seeing any issues like this with my Android SDL projects, but I do divert from the supplied android-project a bit. Can you try this line in your manifest:

```
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" android:required="false" android:minSdkVersion="31"/>
```

**Comment by rodrigovaras** [comment]
I realize this issue should have been opened on the Silk.NET repo where they use the SDL activity. Apologize will close it and open it there
