### ISSUE TITLE
[Feature Request] Make crossplatform tooltips possible for SDL3?

### ISSUE THREAD

**Issue by BreyerW** [libsdl-org/SDL#7364]
I once checked source code for SDL2 and it turned out that crossplatform tooltips could be achieved by adding `ShowWindow` overload with optional bool takeFocus parameter (tenative name) and for Windows this bool would provide different flag for internal ShowWindow that instructs window to not take focus, for X11 it would skip `SetWindowActive` method call for others platforms idk (i tried only cocoa but i dont know well cocoa rest platforms i skipped).

Alternative would be to make `SDL_SetWindowInputFocus` actually crossplatform but the disadvatage is that it wastes unnecessarily cycles on switching focus back and forth between tooltip and original window.

Personally im most concerned with Windows support so if tooltips were provided only here with sdl3 that would be ok but not ideal.

**Comment by icculus** [comment]
This should work in SDL2 and SDL3:

```c
SDL_CreateWindow("Hello SDL", x, y, width, height, SDL_WINDOW_TOOLTIP);
```

(This _should_ do it, but this isn't heavily tested.)

**Comment by slime73** [comment]
It looks like `SDL_WINDOW_TOOLTIP` is only implemented for the X11 and Wayland backends right now.

**Comment by icculus** [comment]
Oh. Well, we should definitely fix that, then.   :)

**Comment by Kontrabant** [comment]
> It looks like `SDL_WINDOW_TOOLTIP` is only implemented for the X11 and Wayland backends right now. Same with `SDL_WINDOW_POPUP_MENU` (X11 and Wayland) and `SDL_WINDOW_UTILITY` (only X11).

It seems to only work on Wayland with xdg-toplevel windows, not libdecor.  Will take care of that.

**Comment by Kontrabant** [comment]
Setting some rules to normalize behavior would be good as well. Currently, if you try to make a tooltip/popup menu with X11, it uses the position to place it at those absolute coordinates on the desktop, while on Wayland, the position is ignored and the window appears where the cursor is. In the case of tooltips, on Wayland they move with the cursor, while they are static on X11.

Maybe something in between, where tooltip and popup menu x,y coordinates are always relative to the parent window, and if the application wants the window to follow the cursor, it can respond to cursor events and change the position itself.

**Comment by flibitijibibo** [comment]
One detail that might act as a test case: This was a feature that I believe came from Unreal Engine, and I definitely used the editor aa my test case for the first Wayland draft. Definitely worth testing changes against UE5!

**Comment by DeafMan1983** [comment]
I suggest about SDL_WINDOW_UTILITY but all platforms it reminds in gdk ( Gtk4,Gdk ) like all platform usable features. Like Qt6, Gtk4 or WxWidget3x also X11, xcb, Wl, directfb and more 

I will help everyone.
