### ISSUE TITLE
SDL3 should accept optional length for some functions accepting only zero-terminated strings.

### ISSUE THREAD

**Issue by eloj** [libsdl-org/SDL#7371]
I find that APIs that only accept zero-terminated strings are often cumbersome to work with, since it's quite common for the source data for such APIs to be some part of a buffer that is not already zt.

The standouts to me are `SDL_SetClipboardText` and `SDL_SetPrimarySelectionText`, but there may be others.

My preference would be that such calls also accept a `len` as int, denoting the number of octets to pass to the underlying API, possibly with the documented option to pass ~-1~ a negative value to denote that this can be calculated internally using `strlen()`.

For the internal clipboard that just turns the existing `SDL_strdup()` paths into `SDL_strndup()`s, while making client code simpler.

I looked at the X11 implementation, and the underlying API already accepts a length, that is unconditionally calculated using `strlen` today.

```c
static int SetSelectionText(_THIS, const char *text, Atom selection_type) {
...
    X11_XChangeProperty(display, DefaultRootWindow(display),
                        X11_GetSDLCutBufferClipboardType(display, SDL_X11_CLIPBOARD_MIME_TYPE_STRING, selection_type),
                        X11_GetSDLCutBufferClipboardInternalFormat(display, SDL_X11_CLIPBOARD_MIME_TYPE_STRING), 8, PropModeReplace,
                        (const unsigned char *)text, SDL_strlen(text));
```

I'm ~willing~ happy to work on an initial patch if this an acceptable change.

PS.
Bonus [motivation](https://youtu.be/3xNM4jDOx3c?t=1629).

**Comment by icculus** [comment]
I wouldn't want this for most functions, but this _does_ make sense for the clipboard.  @slouken, do you agree?

**Comment by eloj** [comment]
I'm proceeding with an implementation on the assumption that it's totally the Right Thing, andhas a fair chance of getting accepted.

I ran into an issue where `gendynapi.py` doesn't update the existing function with the new prototype (by design I assume). I'm moving forward by hand-editing it for now since I don't know what the procedure for this is.

**Comment by slime73** [comment]
If it's just a couple APIs (like clipboards), would it be more idiomatic for the length parameter to be a `const size_t *` (or similar) so people could pass in `NULL` instead of a sentinel value when they want the implementation to treat the string as zero-terminated?

**Comment by icculus** [comment]
> I'm proceeding with an implementation on the assumption that it's totally the Right Thing

We're still discussing here, but it wouldn't hurt to get started, I think.

Gendynapi assumes existing functions never change, but we're still changing interfaces for SDL3, so hand-editing the function is the right thing to do.

**Comment by eloj** [comment]
To be clear; with 'an implementation' I mean for the two clipboard functions mentioned only. I have it working on X11 for now.

> If it's just a couple APIs (like clipboards), would it be more idiomatic for the length parameter to be a `const size_t *` (or similar) so people could pass in `NULL` instead of a sentinel value when they want the implementation to treat the string as zero-terminated?

It's nicer in that it's `size_t`, it's worse in that it's a pointer. I don't have strong feelings either way. The 'negative value' convention is just something I'm used to.

Only the public SDL_Set*Text() functions deal with that aspect anyway, so it's an easy change whatever is decided.

Likewise the coccinelle script is trivial in both cases.

**Comment by slouken** [comment]
This is not going to work on Windows.

From https://learn.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats:
```
CF_TEXT: Text format. Each line ends with a carriage return/linefeed (CR-LF) combination. A null character signals the end of the data. Use this format for ANSI text.
CF_UNICODETEXT: Unicode text format. Each line ends with a carriage return/linefeed (CR-LF) combination. A null character signals the end of the data.
```

What is the use case for text with embedded null characters?

**Comment by slouken** [comment]
There's a difference between a text with embedded nulls and using a length for a partial string buffer. I think we need to be clear we support the latter and not the former.

**Comment by eloj** [comment]
That's fine. Don't panic, I'm not done. I plan to clamp it to the first zt, it's just not in yet.

**Comment by slouken** [comment]
In that case, maybe it's clearer to simply wrap the call to the SDL function with a function that extracts the length and zero terminates it? It's an additional allocation and annoying to purists, but the contract of the API is very clear. I'm going under the assumption that copying is very rare and this isn't a performance issue?

**Comment by eloj** [comment]
I think there's a path to a better implementation than that, and would say that the clarity of the API contract is primarily a documentation issue, not an QoI issue.

In the specific case of not accepting buffers with embedded nuls, I can check for that. I'd like to think it would be enough to document against it, but I'm not against enforcing terminating at the first nul.

Is this a code path where performance is absolutely critical? No. I'd still not want to introduce new essentially unbounded `strdup`s if I could avoid it, and for many backends I can. X11, wayland so far. Windows if I invest a bit of time. Android seems like maybe not from a glance.

I don't mind investing time in getting it right. I can be less communicative till PR time, if mental bandwidth is an issue.

If there's really no chance of acceptance for a min-strdup's approach... I'd find that disappointing, but tell me if so and I'll stop here.

**Comment by 1bsyl** [comment]
+1 to leave all strings by default 0-terminated

but if this make really sense for 1 or 2 API, let's update them.

**Comment by slouken** [comment]
I reviewed all the functions that take `const char *` parameters, and I think the only ones where a partial string makes sense are the clipboard functions.

After thinking about it, I'd like to keep the clipboard functions the way they are, for consistency with the rest of the API. A memcpy into a temporary buffer occasionally is not a big deal for today's computers. :)

Here is the full list, for anyone who's curious:
```
SDL_clipboard.h:extern DECLSPEC int SDLCALL SDL_SetClipboardText(const char *text);
SDL_clipboard.h:extern DECLSPEC int SDLCALL SDL_SetPrimarySelectionText(const char *text);
SDL_egl.h:typedef __eglMustCastToProperFunctionPointerType (EGLAPIENTRYP PFNEGLGETPROCADDRESSPROC) (const char *procname);
SDL_egl.h:EGLAPI __eglMustCastToProperFunctionPointerType EGLAPIENTRY eglGetProcAddress (const char *procname);
SDL_egl.h:typedef void (EGLAPIENTRY  *EGLDEBUGPROCKHR)(EGLenum error,const char *command,EGLint messageType,EGLLabelKHR threadLabel,EGLLabelKH
R objectLabel,const char* message);
SDL_error.h:extern DECLSPEC int SDLCALL SDL_SetError(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
SDL_filesystem.h:extern DECLSPEC char *SDLCALL SDL_GetPrefPath(const char *org, const char *app);
SDL_gamepad.h:extern DECLSPEC int SDLCALL SDL_AddGamepadMapping(const char *mappingString);
SDL_gamepad.h:extern DECLSPEC SDL_GamepadAxis SDLCALL SDL_GetGamepadAxisFromString(const char *str);
SDL_gamepad.h:extern DECLSPEC SDL_GamepadButton SDLCALL SDL_GetGamepadButtonFromString(const char *str);
SDL_guid.h:extern DECLSPEC SDL_GUID SDLCALL SDL_GUIDFromString(const char *pchGUID);
SDL_hidapi.h:extern DECLSPEC SDL_hid_device * SDLCALL SDL_hid_open_path(const char *path, int bExclusive /* = false */);
SDL_hints.h:extern DECLSPEC SDL_bool SDLCALL SDL_SetHintWithPriority(const char *name,
SDL_hints.h:extern DECLSPEC SDL_bool SDLCALL SDL_SetHint(const char *name,
SDL_hints.h:extern DECLSPEC SDL_bool SDLCALL SDL_ResetHint(const char *name);
SDL_hints.h:extern DECLSPEC const char * SDLCALL SDL_GetHint(const char *name);
SDL_hints.h:extern DECLSPEC SDL_bool SDLCALL SDL_GetHintBoolean(const char *name, SDL_bool default_value);
SDL_hints.h:typedef void (SDLCALL *SDL_HintCallback)(void *userdata, const char *name, const char *oldValue, const char *newValue);
SDL_hints.h:extern DECLSPEC int SDLCALL SDL_AddHintCallback(const char *name,
SDL_hints.h:extern DECLSPEC void SDLCALL SDL_DelHintCallback(const char *name,
SDL_joystick.h:extern DECLSPEC SDL_JoystickGUID SDLCALL SDL_GetJoystickGUIDFromString(const char *pchGUID);
SDL_keyboard.h:extern DECLSPEC SDL_Scancode SDLCALL SDL_GetScancodeFromName(const char *name);
SDL_keyboard.h:extern DECLSPEC SDL_Keycode SDLCALL SDL_GetKeyFromName(const char *name);
SDL_loadso.h:extern DECLSPEC void *SDLCALL SDL_LoadObject(const char *sofile);
SDL_loadso.h:extern DECLSPEC SDL_FunctionPointer SDLCALL SDL_LoadFunction(void *handle, const char *name);
SDL_log.h:extern DECLSPEC void SDLCALL SDL_Log(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
SDL_log.h:extern DECLSPEC void SDLCALL SDL_LogVerbose(int category, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_log.h:extern DECLSPEC void SDLCALL SDL_LogDebug(int category, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_log.h:extern DECLSPEC void SDLCALL SDL_LogInfo(int category, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_log.h:extern DECLSPEC void SDLCALL SDL_LogWarn(int category, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_log.h:extern DECLSPEC void SDLCALL SDL_LogError(int category, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_log.h:extern DECLSPEC void SDLCALL SDL_LogCritical(int category, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_log.h:typedef void (SDLCALL *SDL_LogOutputFunction)(void *userdata, int category, SDL_LogPriority priority, const char *message);
SDL_main.h:extern DECLSPEC int SDLCALL SDL_RegisterApp(const char *name, Uint32 style, void *hInst);
SDL_messagebox.h:extern DECLSPEC int SDLCALL SDL_ShowSimpleMessageBox(Uint32 flags, const char *title, const char *message, SDL_Window *window);
SDL_misc.h:extern DECLSPEC int SDLCALL SDL_OpenURL(const char *url);
SDL_render.h:extern DECLSPEC SDL_Renderer *SDLCALL SDL_CreateRenderer(SDL_Window *window, const char *name, Uint32 flags);
SDL_rwops.h:extern DECLSPEC SDL_RWops *SDLCALL SDL_RWFromFile(const char *file,
SDL_rwops.h:extern DECLSPEC void *SDLCALL SDL_LoadFile(const char *file, size_t *datasize);
SDL_shape.h:extern DECLSPEC SDL_Window * SDLCALL SDL_CreateShapedWindow(const char *title,unsigned int x,unsigned int y,unsigned int w,unsigned int h,Uint32 flags);
SDL_stdinc.h:extern DECLSPEC char *SDLCALL SDL_getenv(const char *name);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_setenv(const char *name, const char *value, int overwrite);
SDL_stdinc.h:extern DECLSPEC size_t SDLCALL SDL_strlen(const char *str);
SDL_stdinc.h:extern DECLSPEC size_t SDLCALL SDL_strlcpy(SDL_OUT_Z_CAP(maxlen) char *dst, const char *src, size_t maxlen);
SDL_stdinc.h:extern DECLSPEC size_t SDLCALL SDL_utf8strlcpy(SDL_OUT_Z_CAP(dst_bytes) char *dst, const char *src, size_t dst_bytes);
SDL_stdinc.h:extern DECLSPEC size_t SDLCALL SDL_strlcat(SDL_INOUT_Z_CAP(maxlen) char *dst, const char *src, size_t maxlen);
SDL_stdinc.h:extern DECLSPEC SDL_MALLOC char *SDLCALL SDL_strdup(const char *str);
SDL_stdinc.h:extern DECLSPEC char *SDLCALL SDL_strchr(const char *str, int c);
SDL_stdinc.h:extern DECLSPEC char *SDLCALL SDL_strrchr(const char *str, int c);
SDL_stdinc.h:extern DECLSPEC char *SDLCALL SDL_strstr(const char *haystack, const char *needle);
SDL_stdinc.h:extern DECLSPEC char *SDLCALL SDL_strcasestr(const char *haystack, const char *needle);
SDL_stdinc.h:extern DECLSPEC char *SDLCALL SDL_strtokr(char *s1, const char *s2, char **saveptr);
SDL_stdinc.h:extern DECLSPEC size_t SDLCALL SDL_utf8strlen(const char *str);
SDL_stdinc.h:extern DECLSPEC size_t SDLCALL SDL_utf8strnlen(const char *str, size_t bytes);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_atoi(const char *str);
SDL_stdinc.h:extern DECLSPEC double SDLCALL SDL_atof(const char *str);
SDL_stdinc.h:extern DECLSPEC long SDLCALL SDL_strtol(const char *str, char **endp, int base);
SDL_stdinc.h:extern DECLSPEC unsigned long SDLCALL SDL_strtoul(const char *str, char **endp, int base);
SDL_stdinc.h:extern DECLSPEC Sint64 SDLCALL SDL_strtoll(const char *str, char **endp, int base);
SDL_stdinc.h:extern DECLSPEC Uint64 SDLCALL SDL_strtoull(const char *str, char **endp, int base);
SDL_stdinc.h:extern DECLSPEC double SDLCALL SDL_strtod(const char *str, char **endp);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_strcmp(const char *str1, const char *str2);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_strncmp(const char *str1, const char *str2, size_t maxlen);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_strcasecmp(const char *str1, const char *str2);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_strncasecmp(const char *str1, const char *str2, size_t len);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_sscanf(const char *text, SDL_SCANF_FORMAT_STRING const char *fmt, ...) SDL_SCANF_VARARG_FUNC(2);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_vsscanf(const char *text, const char *fmt, va_list ap);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_snprintf(SDL_OUT_Z_CAP(maxlen) char *text, size_t maxlen, SDL_PRINTF_FORMAT_STRING const char *fmt, ... ) SDL_PRINTF_VARARG_FUNC(3);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_vsnprintf(SDL_OUT_Z_CAP(maxlen) char *text, size_t maxlen, const char *fmt, va_list ap);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_asprintf(char **strp, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_stdinc.h:extern DECLSPEC int SDLCALL SDL_vasprintf(char **strp, const char *fmt, va_list ap);
SDL_stdinc.h:extern DECLSPEC SDL_iconv_t SDLCALL SDL_iconv_open(const char *tocode,
SDL_stdinc.h:extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf,
SDL_stdinc.h:extern DECLSPEC char *SDLCALL SDL_iconv_string(const char *tocode,
SDL_stdinc.h:size_t strlcpy(char* dst, const char* src, size_t size);
SDL_stdinc.h:size_t strlcat(char* dst, const char* src, size_t size);
SDL_system.h:extern DECLSPEC SDL_bool SDLCALL SDL_AndroidRequestPermission(const char *permission);
SDL_system.h:extern DECLSPEC int SDLCALL SDL_AndroidShowToast(const char* message, int duration, int gravity, int xoffset, int yoffset);
SDL_test_assert.h:void SDLTest_Assert(int assertCondition, SDL_PRINTF_FORMAT_STRING const char *assertDescription, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_test_assert.h:int SDLTest_AssertCheck(int assertCondition, SDL_PRINTF_FORMAT_STRING const char *assertDescription, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_test_assert.h:void SDLTest_AssertPass(SDL_PRINTF_FORMAT_STRING const char *assertDescription, ...) SDL_PRINTF_VARARG_FUNC(1);
SDL_test_common.h:void SDLTest_CommonLogUsage(SDLTest_CommonState *state, const char *argv0, const char **options);
SDL_test_font.h:int SDLTest_DrawString(SDL_Renderer *renderer, float x, float y, const char *s);
SDL_test_font.h:void SDLTest_TextWindowAddText(SDLTest_TextWindow *textwin, SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(2);
SDL_test_font.h:void SDLTest_TextWindowAddTextWithLength(SDLTest_TextWindow *textwin, const char *text, size_t len);
SDL_test_harness.h:int SDLTest_RunSuites(SDLTest_TestSuiteReference *testSuites[], const char *userRunSeed, Uint64 userExecKey, const char *filter, int testIterations);
SDL_test_log.h:void SDLTest_Log(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
SDL_test_log.h:void SDLTest_LogError(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
SDL_thread.h:SDL_CreateThread(SDL_ThreadFunction fn, const char *name, void *data,
SDL_thread.h:SDL_CreateThread(SDL_ThreadFunction fn, const char *name, void *data);
SDL_thread.h:SDL_CreateThreadWithStackSize(SDL_ThreadFunction fn, const char *name, const size_t stacksize, void *data);
SDL_video.h:extern DECLSPEC SDL_Window *SDLCALL SDL_CreateWindow(const char *title, int x, int y, int w, int h, Uint32 flags);
SDL_video.h:extern DECLSPEC int SDLCALL SDL_SetWindowTitle(SDL_Window *window, const char *title);
SDL_video.h:extern DECLSPEC void *SDLCALL SDL_SetWindowData(SDL_Window *window, const char *name, void *userdata);
SDL_video.h:extern DECLSPEC void *SDLCALL SDL_GetWindowData(SDL_Window *window, const char *name);
SDL_video.h:extern DECLSPEC int SDLCALL SDL_GL_LoadLibrary(const char *path);
SDL_video.h:extern DECLSPEC SDL_FunctionPointer SDLCALL SDL_GL_GetProcAddress(const char *proc);
SDL_video.h:extern DECLSPEC SDL_FunctionPointer SDLCALL SDL_EGL_GetProcAddress(const char *proc);
SDL_video.h:extern DECLSPEC SDL_bool SDLCALL SDL_GL_ExtensionSupported(const char *extension);
SDL_vulkan.h:extern DECLSPEC int SDLCALL SDL_Vulkan_LoadLibrary(const char *path);
```

**Comment by eloj** [comment]
So does that mean that you wouldn't consider adding a new function either, like a `SDL_SetClipboardTextBuffer()`?

**Comment by slouken** [comment]
A new function would be fine, although is it really worth adding a new function to the API to avoid copying to a temporary buffer?

**Comment by Desour** [comment]
In X11 and wayland, copying could be completely (that is, as long as nobody requests the selection) avoided by exposing the underlying API to the SDL user, who would then have to maintain a buffer themselves. This would be more suitable to the use-case of huge selections (like someone doing ctrl+a in a huge file opened by text editor). It would then also allow doing more advanced things like copying non-text data, i.e. a part of an image. Otherwise if someone has performance issues, I'd suggest to simply not set the primary selection text if the selection is too big.

--------

>Bonus [motivation](https://youtu.be/3xNM4jDOx3c?t=1629).

I've noticed a worse issue there: `get*Text()` returns `""` on failure. However, this does not necessarily indicate an error. Users (like the one in this example) easily get this wrong. I'm not sure if this is just a documentation issue or if it would make sense to return `NULL` on error.

**Comment by slouken** [comment]
> In X11 and wayland, copying could be completely (that is, as long as nobody requests the selection) avoided by exposing the underlying API to the SDL user, who would then have to maintain a buffer themselves. This would be more suitable to the use-case of huge selections (like someone doing ctrl+a in a huge file opened by text editor). It would then also allow doing more advanced things like copying non-text data, i.e. a part of an image. Otherwise if someone has performance issues, I'd suggest to simply not set the primary selection text if the selection is too big.

This seems like a good direction to go for SDL3.

> I've noticed a worse issue there: `get*Text()` returns `""` on failure. However, this does not necessarily indicate an error. Users (like the one in this example) easily get this wrong. I'm not sure if this is just a documentation issue or if it would make sense to return `NULL` on error. (Sorry if this is offtopic.)

Yep, returning NULL on error seems like a good idea.

After discussion let's go ahead and close this bug, but feel free to open PRs for either of the above ideas.

Thanks!
