### ISSUE TITLE
Documentation is gone!

### ISSUE THREAD

**Issue by neet93** [libsdl-org/SDL#7372]
https://wiki.libsdl.org/SDL2/CategoryAPI Used to be the most complete list of functions and types for SDL and now there are only a few listed there. What happened to all the functions documented there??

**Comment by neet93** [comment]
For instance if I want to find a function like `SDL_ShowSimpleMessageBox` I have to search it on a search engine to find a link like [this](https://wiki.libsdl.org/SDL2/SDL_ShowSimpleMessageBox) When before it would just be listed and I could just Ctr+F it!

**Comment by icculus** [comment]
This broke at some point, I'll fix it.

**Comment by neet93** [comment]
Thank you!

**Comment by icculus** [comment]
This was just fixed by the last few commits to ghwikipp. The category pages should be populated again now.

**Comment by neet93** [comment]
Thank very much!
