### ISSUE TITLE
PSVita fails to run SDL_CreateWindow with SDL_WINDOW_OPENGL flag

### ISSUE THREAD

**Issue by XITRIX** [libsdl-org/SDL#7376]
Trying to port my UI library which uses [SDL_gpu](https://github.com/grimfang4/sdl-gpu) to my PSVita. This lib requires to init window with `SDL_WINDOW_OPENGL` flag, but SDL fails to init a window with that flag.

Error says: 
"OpenGL support is either not configured in SDL or not available in current SDL video driver (VITA) or platform"

Am I doing something wrong or it is correct behavior and SDL really not support Vita with SDL_WINDOW_OPENGL flag?

**Comment by slouken** [comment]
@isage, any ideas here?

**Comment by isage** [comment]
Vita port by default (and default is installed with vitasdk) built without opengl support
