### ISSUE TITLE
Remove the audio callback!

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7379]
> We ***REMOVE*** the callback API. If someone needs it, we provide a single-header library to feed an audiostream from a thread. This lets us remove the device locking APIs, too (audiostreams will still be threadsafe for queuing and dequeuing data). Behind the scenes, we'll probably still have a thread to feed the audio device when appropriate, but we can probably have a single thread that serves all the open devices.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/6632#issuecomment-1441894386_

**Comment by 1bsyl** [comment]
some quick start of attempt here:  https://github.com/libsdl-org/SDL/pull/7457/files ...
