### ISSUE TITLE
SDL_WaitEvent(NULL) followed by SDL_PollEvent(&ev) broken

### ISSUE THREAD

**Issue by olvaffe** [libsdl-org/SDL#7392]
I have an UI app that does

```
static void wait_and_process_events()
{
  // idle wait for events
  SDL_WaitEvent(NULL);

  SDL_Event ev;
  while (SDL_PollEvent(&ev)) { process(&ev); }
}
```

`SDL_PollEvent` almost always return 0 every other time.

Looking at `SDL_WaitEventTimeout`, it appears that the `SDL_WaitEvent(NULL)` call adds a `SDL_POLLSENTINEL` event without removing it.  And the `SDL_PollEvent` call returns 0 upon seeing it.  It polls the real events when called the second time.

**Comment by slouken** [comment]
This is fixed in 00b87f1ded0a4fdb6a0bab611171f37eeb0b2ebb, thanks!
