### ISSUE TITLE
move C++ wrappers to begin_code.h/end_code.h?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7393]
Dumb question...we have this in most headers...

```c
#include <SDL3/SDL_begin_code.h>
/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

// [...]

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif
#include <SDL3/SDL_close_code.h>
```
...is there any reason we can't shuffle the `__cplusplus` stuff into SDL_begin_code.h and SDL_close_code.h?

**Comment by madebr** [comment]
I was thinking the same recently. It's not like SDL is going to provide C++ symbols anytime soon?

**Comment by madebr** [comment]
All SDL satellite libraries use it.
Do external libraries use this?

**Comment by slouken** [comment]
The idea was to wrap function definitions and avoid wrapping anything else. Specifically we don't want an extern "C" around other header includes.

**Comment by icculus** [comment]
Alright, we'll just close this then.
