### ISSUE TITLE
Wayland: warnings on exit with libwayland >= 1.22

### ISSUE THREAD

**Issue by jbeich** [libsdl-org/SDL#7397]
Regressed by [wayland!282](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/282). CC @afrantzis

Tested together with [wayland!297](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/297) + [mesa!21646](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21646) + [mesa!21647](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21647) in order to reduce noise.
```
$ SDL_VIDEODRIVER=wayland testdrawchessboard
<press ESC to quit>
warning: queue 0x82bc7fea0 destroyed while proxies still attached:
  wl_callback@33 still attached
  wl_surface@31 still attached

$ git describe --tags
release-2.26.3-7-gcbc2b014b
```

**Comment by jbeich** [comment]
Forgot to mention, I've tested together with [wayland!297](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/297) + [mesa!21646](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21646) [mesa!21647](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21647) in order to reduce noise.

**Comment by Kontrabant** [comment]
Note that there are other warnings of this variety regarding wl_registry and zwp_linux_dmabuf_v1, however they occur when calling into function pointers for external libraries and drivers. The new libwayland warnings are shaking out bugs in many libraries at all levels, so this likely isn't anything that can be fixed on SDL's side.

**Comment by bernhardkaindl** [comment]
> Note that there are other warnings of this variety regarding wl_registry and zwp_linux_dmabuf_v1, however they occur when calling into function pointers for external libraries and drivers. The new libwayland warnings are shaking out bugs in many libraries at all levels, so this likely isn't anything that can be fixed on SDL's side (we don't even use zwp_linux_dmabuf_v1 directly).

Yep, while unrelated just for the sake of reference, on Mali-G52 with the closed-source libMali.so from https://dl.khadas.com/repos/vim4/pool/main/l/linux-gpu-mali-wayland/linux-gpu-mali-wayland_1.4-r44p0-202311_arm64.deb on the Khadas VIM4 board.

With it, `eglInitialize()` triggers a warning on zwp_linux_dmabuf_v1() still attached on the queue destroy. The `mali_buffer_sharing` of the closed-source libMali.so is there as well:
```py
ltrace es2gears_wayland 2>x
grep -B4 'still attached' x
eglGetDisplay(0x55951c96e0, 1, 4, 1)                                = 0x55951cffd0
eglInitialize(0x55951cffd0, 0x5583680068, 0x558368006c, 1
warning: queue 0x55951e6bf0 destroyed while proxies still attached:
  wl_callback@9 still attached
  zwp_linux_dmabuf_v1@8 still attached
  mali_buffer_sharing@7 still attached
  wl_callback@6 still attached
)
```
Same from the `eglInitialize()` from the eglConfigTest.c attached in this post:
https://e2e.ti.com/support/processors-group/processors/f/processors-forum/679641/linux-sgxfrmcpylink-eglchooseconfig-success-but-return-0-config :
```py
drmOpen(0x55745c2c98, 0, 0x200003098, 0x55745c18f0)                  = 0xffffffff
eglGetDisplay(0, 0xffffffff, 0, 0)                                   = 0x55b2445150
eglGetError(1, 1, 0, 1)                                              = EGL_SUCCESS
eglInitialize(0x55b2445150, 0x7fc6c1064c, 0x7fc6c10650, 0x7fab2625b0
warning: queue 0x55b245fb00 destroyed while proxies still attached:
  wl_callback@6 still attached
  zwp_linux_dmabuf_v1@5 still attached
  mali_buffer_sharing@4 still attached
  wl_callback@3 still attached
)                                    = 1
eglGetError(1, 1, 0, 1)                                              = EGL_SUCCESS
```
The open-source Mali panfrost driver might solve that some time in the future, but it crashed the system in my case.
