### ISSUE TITLE
Windows + SDL3 + SDL_Init(SDL_INIT_GAMEPAD) = Joystick 4294967295 no found

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#7398]
`SDL_Init` doesn't return an error, but `SDL_GetError` is set. I *know* I'm not supposed to look at `SDL_GetError` when a function doesn't return an error code - please don't lecture me on this 👍🏼 99.99% of the time, an error isn't set when an error isn't returned, so when it is, it usually indicates a problem internally.

If I set `SDL_INIT_SENSOR`, this error doesn't get set, which makes me wonder if `SDL_HINT_ACCELEROMETER_AS_JOYSTICK` is doing something naughty since the joystick index changed to a list of IDs? I couldn't find where the source code was to look into it deeper. I think it's worth checking. Although, `SDL_SetHint(SDL_HINT_ACCELEROMETER_AS_JOYSTICK, "0")` doesn't make the error go away, so it could be something else? I feel it's worth investigating please, since this error didn't get set before SDL3.

**Comment by slouken** [comment]
Any chance you can debug into SDL and see what's happening?

**Comment by AntTheAlchemist** [comment]
@slouken yes, leave it with me. Just a bit daunting stepping into SDL_Init, but I'll see what I can find 😬

**Comment by slouken** [comment]
You can set a breakpoint in SDL_SetError_REAL if that's easier.

**Comment by AntTheAlchemist** [comment]
@slouken good tip - that makes it easy, thank you. I found a problem:

`SDL_GetJoystickIDForPlayerIndex` returns a -1 as a `SDL_JoystickID`. Should be 0 now we're not using indexes, right?

**Comment by slouken** [comment]
Yes it should. Fixed in c9aec268f, thanks!
