### ISSUE TITLE
cmake cannot find libGL.so in /usr/lib/x86_64-linux-gnu/mesa/libGL.so

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#740]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2013-01-13 13:33:31 +0000,  wrote:

> I am on Ubuntu x86_64 and have 2 versions of libGL installed (i386 and x64). Cmake cannot find libGL to link with SDL. I did a 
> ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so /usr/lib/libGL.so
> to get it to build.
> 
> Sorry I cannot submit a patch I don't have much experience with cmake.

On 2016-07-18 20:27:00 +0000, Philipp Wiesemann wrote:

> Does this still not work with SDL 2.0.4?

**Comment by icculus** [comment]
I'm assuming this is fixed since 2013, or someone will (re)open a bug.
