### ISSUE TITLE
SDL_CONTROLLERDEVICEREMOVED reports incorrect value for sdlEvent.cdevice.which

### ISSUE THREAD

**Issue by jkaplan55** [libsdl-org/SDL#7401]
`sdlEvent.cdevice.which`  seems to report the wrong device index to SDL_CONTROLLERDEVICEREMOVED.

The device index reported seems to increment each time a device is removed, regardless of the actual index of the device that is removed.

If I do something like this:
 ```
 while (SDL_PollEvent(&sdlEvent)) {
            switch (sdlEvent.type) {

            case SDL_CONTROLLERDEVICEADDED:
                     cout << "SDL_CONTROLLERDEVICEADDED sdlEvent.cdevice.which is : " << sdlEvent.cdevice.which << endl;

            case SDL_CONTROLLERDEVICEREMOVED:
                      cout << "SDL_CONTROLLERDEVICEREMOVED sdlEvent.cdevice.which is : " << sdlEvent.cdevice.which << endl;
```

And then plug and unplug the same device, I get the output below in my console.

![image](https://user-images.githubusercontent.com/93295860/222863600-e494d21f-c0f2-4501-8f29-5eafda9a5734.png)

**Comment by slouken** [comment]
The removed event passes the controller ID, not the index. This confusion is fixed in SDL 3.0 where both events pass the controller ID.

**Comment by jkaplan55** [comment]
Thanks for the quick reply!  I found mention of that [here](https://5pmcasual.com/post/sdl2-game-controllers/) but I guess I didn't fully understand.  Your commend helps.

What is the Status of SDL 3.0?  Should I be using that instead?  Thanks again for an excellent library!

**Comment by slouken** [comment]
SDL 3.0 is still in development, but if you don't mind living on the edge, it's fully functional, just grab the main code from github.
