### ISSUE TITLE
SDL_GetWindowSize returns the same as SDL_Vulkan_GetDrawableSize in linux when using SDL_WINDOW_ALLOW_HIGHDPI

### ISSUE THREAD

**Issue by dortamiguel** [libsdl-org/SDL#7402]
In mac I can pass the flag `SDL_WINDOW_ALLOW_HIGHDPI` when creating the window, and then when calling SDL_GetWindowSize I will get the pixels of the window but scaled to UI dpi, and when I call `SDL_Vulkan_GetDrawableSize` I get the real number of pixels used in the screen,

But in linux it seems like both `SDL_GetWindowSize` and `SDL_Vulkan_GetDrawableSize` just return the same. 
I'm now using the KDE linux desktop that comes with the steam deck and there I set the UI scaling to 200%

![image](https://user-images.githubusercontent.com/3449006/222869818-7bae4cc4-026f-4e0b-a950-d8c01f2c7261.png)

Is this option meant to be detected by SDL2? If not how can SDL be aware of the UI scaling when using a high res monitor?

**Comment by slime73** [comment]
Is the X11 backend being used in your situation? I don't think it has any DPI scale / high-dpi awareness, whereas the Wayland backend does.

**Comment by Kontrabant** [comment]
I think that 'global scale' on KDE is just their term for the font scale factor, which doesn't have anything to do with actual desktop scaling, it's just sets a value that applications and toolkits can optionally read to determine how much to scale things like text, icons and widgets.

**Comment by dortamiguel** [comment]
> Is the X11 backend being used in your situation? I don't think it has any DPI scale / high-dpi awareness, whereas the Wayland backend does.

ah! that might be, I need to compile SDL2 with wayland support first

**Comment by everdrone** [comment]
I'm getting the same behavior on windows, building from source the `2.26.5` release

**Comment by slouken** [comment]
Yes, Windows high DPI support is not enabled by default in SDL 2.0

**Comment by everdrone** [comment]
For posterity: to enable high dpi on windows just add this line to your CMakeFile.txt

```
set_target_properties(your_sdl_executable PROPERTIES
    VS_DPI_AWARE "PerMonitor"
)
```
