### ISSUE TITLE
SDL_GameControllerAddMappingsFromFile: Failed loading udev_device_get_action

### ISSUE THREAD

**Issue by audetto** [libsdl-org/SDL#7406]

**Comment by slouken** [comment]
Did SDL_GameControllerAddMappingsFromFile() return an error? The SDL API should always set a relevant error message if the function returns an error, but if the function does not, you should ignore SDL_GetError(). There may be some internal errors that are recoverable that still set the error message.

**Comment by audetto** [comment]
Hi,

I thought I did not complete the creation of the issue.
It happened exactly what you said, I misunderstood the correct return value and called GetError anyway.
