### ISSUE TITLE
SDL2: Destroying a secondary OpenGL context in another thread turns the window black permanently on macOS

### ISSUE THREAD

**Issue by Fulgen301** [libsdl-org/SDL#7410]
Creating a secondary OpenGL context and destroying it in another thread turns the window black permanently. This bug only happens on macOS, it works fine on Linux (X11), haven't tested Windows.

See https://gist.github.com/Fulgen301/232dcac99c7c7f2fd4a9e5c0d7df7ce2 for a reproducible example. Expected behavior is that the window turns red for a frame and then blue; however, with the secondary context being destroyed in another thread, the window turns red and then black.

**Comment by slouken** [comment]
This is fixed in f5c0760c6, thanks!

**Comment by 1bsyl** [comment]
could this be the same as https://github.com/libsdl-org/SDL/issues/7320 ?
