### ISSUE TITLE
`SDL_CreateRenderer` argument `flags` under-documented

### ISSUE THREAD

**Issue by rohlem** [libsdl-org/SDL#7412]
The `SDL_CreateRenderer` function takes a `Uint32` argument `flags` (both in SDL2 and current `main` branch / SDL3).
The documentation states that this should be "0, or one or more `SDL_RendererFlags` OR'd together".
`SDL_RendererFlags` are used to convey information about a particular renderer in other places, but I guess the meanings of "this is x" and "I want x" aren't too far apart.

When looking through the code however, I've found that `SDL_RENDERER_PRESENTVSYNC` is the only bit ever actually queried from the argument (both in SDL2 and SDL3 - but possible I missed something).
This is the behavior I would have expected for the other bits:
- `SDL_RENDERER_SOFTWARE`: provide the fallback software renderer, error if we can't (unsure if there is a use case for this)
- `SDL_RENDERER_ACCELERATED`: provide a hardware accelerated renderer, error if we can't (unsure if there is a use case for this)
- `SDL_RENDERER_TARGETTEXTURE`: provide a renderer that can render to a texture, error if we can't (seems like it would be useful)

Also note that in some places (like [test/testautomation_render.c](https://github.com/libsdl-org/SDL/blob/c9aec268fa7f892e183219683160599a4a2b86db/test/testautomation_render.c#L59)), SDL's own code passes ignored flag values (in this case -ACCELERATED),
so it seems like I'm not the only one surprised by this.
If the current behavior is by design, say if backends "are allowed but not required to respect flags, only none of them do", I think it should be documented better.

Also, `SDL_RENDERER_TARGETTEXTURE` seems to have been removed from SDL3 (I guess all renderers now support it?), but
[the comment on SDL_SetRenderTarget in SDL_render.h](https://github.com/libsdl-org/SDL/blob/c9aec268fa7f892e183219683160599a4a2b86db/include/SDL3/SDL_render.h#L801) still mentions it. It's also still on [the SDL3 wiki page](https://wiki.libsdl.org/SDL3/SDL_RendererFlags) for some reason.

**Comment by slouken** [comment]
The flags are requirements. e.g. if you pass `SDL_RENDERER_ACCELERATED`, you're guaranteed not to get a software renderer, and if you pass `SDL_RENDERER_SOFTWARE` you're guaranteed to get a software renderer.
