### ISSUE TITLE
GameControllAddMapping from String Variable?

### ISSUE THREAD

**Issue by jkaplan55** [libsdl-org/SDL#7417]
Hi!  Not an issue, per se, but a question from an inexperienced developer seeking advice.  Thanks for any assistance!

I LOVE that [SDL_GameControllerAddMappingsFromFile()](https://wiki.libsdl.org/SDL2/SDL_GameControllerAddMappingsFromFile
) exists.
I LOVE EVEN MORE that [gabomdq/SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) exists.

My problem is that my SDL implementation is a small part of a larger project that is an extension of an even larger project that I do not own.  Given the distribution model involved, I have very low confidence that I will be able package a text file with my build targets and trust that it will land safely in an appropriate path on the end-users machine where my code can find it.

I want to leverage GameControllerDB, but I do not want to be dependent on an external file that has to travel around with me.  My first impulse is to create a std::string variable in my code and dump the contexts of gamecontrollerdb.txt into that.  Then I can just read that string in my source code to get all the controller mappings.

This sent me on an investigation of the SDL_RWops struct.  This is probably due to my newbishness, but it was not immediately clear how I could read a string into an instance of SDL_RWops.  It looks like once get that far I can just call SDL_GameControllerAddMappingsFromRW() and be good to go.  But how can I populate the RW from a string in my code rather than a file?

Any input on this would greatly accelerate by development here.   Thanks for your consideration.

**Comment by slouken** [comment]
Questions and advice are best gotten from the SDL discourse:
https://discourse.libsdl.org/c/sdl-development/6

To answer your question, you would create an RWops from a string like this:
```c
rw = SDL_RWFromConstMem(str.c_str(), str.size());
```

**Comment by jkaplan55** [comment]
Thanks a ton!

**Comment by jkaplan55** [comment]
Well, that didn't work.  The compiler complains that the string is too big.  I'll take my question over to the discussion forum to inquire about other solutions.  Thanks again.

**Comment by slouken** [comment]
You're welcome!

**Comment by jkaplan55** [comment]
for the sake of completeness i _think_ I got this sorted out [here](https://discourse.libsdl.org/t/add-mappings-from-gamecontrollerdb-without-carting-around-another-txt-file/42991).


I'm quite impressed with the responsiveness of this community.  I'm glad I dipped my toe in these waters. :D
