### ISSUE TITLE
Wayland: Incorrect SDL_GL_GetDrawableSize() after creating highdpi, fullscreen window

### ISSUE THREAD

**Issue by aufau** [libsdl-org/SDL#7418]
Hi,

My OS is Fedora 36 with Gnome (Wayland) desktop
I was testing on SDL 2.26.3 (that comes with Fedora) and SDL 2.26.4 (compiled from source)

I tried to add highdpi support to my opengl application but it was drawing only to quarter of the screen (with 200% scaling) in SDL_WINDOW_FULLSCREEN mode with wayland videodriver.
I've been able to pin down the problem and reproduce it on testgl2.c on SDL 2.26.4 with following instructions:

Set non-trivial desktop scaling and run testgl2 with following arguments:
```
testgl2 --video wayland --opengl-window --allow-highdpi --fullscreen --geometry 1280x800
```
where --geometry is native for your display (my display is 2560x1600 with 200% scaling).
If you step through main rendering loop in testgl2.c with a debugger, or add a delay between iterations, you will notice that on the first frame image is drawn only to a part of the screen. It gets fixed on second and later frames.

Turns out SDL_GL_GetDrawableSize() returns 1280x800 after creating window and opengl context. It only changes to correct value after calling SDL_GL_SwapWindow() **and** polling window events, which will eventually yield window resize event. After that SDL_GL_GetDrawableSize() returns 2560x1600 correctly. This can serve a workaround. Curiously it didn't happen on the same system, SDL 2.0.17 so must have been introduced somewhere in between.

It may not be a big problem or go unnoticed for applications that call SDL_GL_GetDrawableSize() every frame like testgl2 or support window resize events, but my application (id tech 3 game) cannot change drawable size without reloading so it called SDL_GL_GetDrawableSize() only once - after creating opengl context. Finding this workaround was quite hard. I believe it's a bug or at least should be documented if it is impossible to fix it.

In attachment I send full testgl2 logs with my system details. [testgl2.txt](https://github.com/libsdl-org/SDL/files/10914965/testgl2.txt)

PS I didn't examine SDL3 changes in the main branch, but it seems the bug is not present there? I need to pass --geometry 2560x1600 though so I guess testgl or api changed.

**Comment by Kontrabant** [comment]
The common testing code calls `SDL_SetWindowDisplayMode()` while passing a fullscreen mode that has a width and height of 0, and the Wayland backend uses the desktop dimensions as a fail-safe in this case. This can be fixed just by ensuring that the mode dimensions are some sane value, like the window dimensions. Will write up a patch shortly.

>It may not be a big problem or go unnoticed for applications that call SDL_GL_GetDrawableSize() every frame like testgl2 or support window resize events, but my application (id tech 3 game) cannot change drawable size without reloading so it called SDL_GL_GetDrawableSize() only once - after creating opengl context. Finding this workaround was quite hard. I believe it's a bug or at least should be documented if it is impossible to fix it.

If you are using high-DPI, you need to handle drawable size changes or your application will very easily break in mixed-DPI setups. If you eventually migrate to SDL3, this is non-optional.

**Comment by aufau** [comment]
Actually I tested a little more yesterday and when I pass windows width/height to SDL_SetWindowDisplayMode() it's the same, only I don't get window resize event anymore and my workaround doesn't work - testgl2 keeps drawing to the portion of the screen.
You can try it with testgl2 by setting width/height of fullscreen_mode variable in SDL_test_common.c if you can reproduce it on your system.

I knew about the issue with changing displays, but honestly it's quite hard for me to change because the game client supports all kind of mods that were released during last 20 years and they expect to have fixed rendering width/height. It's possible by adding translation layer but to be honest, I don't think it's worth the effort for me.
It would be easier if I could fix drawable size and have window size change as you move it to another display, but I guess this is not how these display managers work?

**Comment by Kontrabant** [comment]
Using --fullscreen with the test program uses exclusive fullscreen, which should always be 1:1 output and never change. If it does, that's an SDL bug. If you pass in 1280x800, it should stay 1280x800 until fullscreen is exited and the window is resized.

I can't replicate the quarter-screen issue here.  Since you are on Gnome, I wonder if what you are seeing is related to this bug: https://github.com/libsdl-org/SDL/issues/6056

It was fixed in Mutter, but I don't know if it was ever backported to Fedora 36.

**Comment by aufau** [comment]
Just to make sure we are on the same page here. This is what I'm doing - you can see git diff and window/draw size being 1280x800. commandline was `testgl2 --vsync --video wayland --opengl-window --allow-highdpi --geometry 1280x800 --fullscreen --info all`
![obraz](https://user-images.githubusercontent.com/4474909/223837485-3686446a-bcd0-4ba7-978a-aa812e2e1c00.png)

**Comment by Kontrabant** [comment]
> Maybe I should ignore SDL_GetDesktopDisplayMode() and get highest resolution from all available modes - 2560x1600. But then why isn't --geometry 1280x800 mode switching to 1280x800?

It does switch to 1280x800, then switches right back to the desktop mode because of the bad fullscreen mode values the window is set to. Can you try https://github.com/Kontrabant/SDL/tree/SDL2_wayland_fullscreen_size and see if it fixes the issue for you?

With this and your parameters, I get a 1280x800 fullscreen window that covers the screen with no size changes, even right after the first buffer swap.

**Comment by Kontrabant** [comment]
Ah, I can replicate this now. It has to do with Gnome behaving differently depending on whether or not fractional scaling is enabled.

**Comment by aufau** [comment]
I tested sdl2 branch and now I don't get quarter-screen issue, hurray!

However `SDL_GetCurrentDisplayMode()` still returns 1280x800 (before creating window or anything) even though my desktop runs at 2560x1600:
```
INFO: Video driver: wayland
INFO: Number of displays: 1
INFO: Display 0: Built-in display
INFO: Bounds: 1280x800 at 0,0
INFO: Usable bounds: 1280x800 at 0,0
INFO: DPI: 112.110344x112.888885
INFO:   Current mode: 1280x800@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
INFO:       Red Mask   = 0x00ff0000
INFO:       Green Mask = 0x0000ff00
INFO:       Blue Mask  = 0x000000ff
INFO:   Fullscreen video modes:
INFO:     Mode 0: 2560x1600@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
INFO:         Red Mask   = 0x00ff0000
INFO:         Green Mask = 0x0000ff00
INFO:         Blue Mask  = 0x000000ff
```
Is it how it's supposed to work? I need to select "max" resolution from all available modes manually? I'm quite certain using SDL_GetCurrentDisplayMode() on cocoa with fullscreen and highdpi flag makes it render at max resolution.

**Comment by Kontrabant** [comment]
2560x1600 is the physical resolution of your display, and with 2x scaling, the logical resolution is half that at 1280x800. Getting the current display returns the desktop mode, which is the logical resolution.

If you want the highest exclusive fullscreen mode, you need to enumerate the modes and select one manually. If you just want a desktop sized window with the max resolution, using `SDL_WINDOW_FULLSCREEN_DESKTOP` will do what you want.

**Comment by aufau** [comment]
I understand the explanation, but I just double checked and fyi on cocoa videodriver `SDL_GetDesktopDisplayMode()` returns 1280x800 but using SDL_WINDOW_FULLSCREEN results in windows size 1280x800 and drawable size of 2560x1600. I don't know which is right, I guess enumerating all display modes and selecting the highest will work on both (although it's not a perfect solution, I'd rather just use the same display mode and drawing size as desktop - there are cases where user runs desktop at lower resolution than maximum).

SDL_WINDOW_FULLSCREEN_DESKTOP - even if it's the same as SDL_WINDOW_FULLSCREEN on wayland, it isn't on windows or x11 and most games have separate setting for "fullscreen" and "fullscreen borderless" for a reason. I have it as option, but not replacement.

GJ on fixing the original bug!
