### ISSUE TITLE
Please expand on "Fixed using older game controller mappings on Linux"

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#7421]
It's not clear to me what bug is being fixed by 727c7d4e2f44 and its backports. @slouken, please could you expand on this? Presumably it's something relatively important since it got backported to 2.26.4.

I'll need this information for the Debian packaging, because Debian 12 is currently in freeze, so if we want to get 2.26.4 into Debian 12 I will need to be able to ask the release team and justify a freeze exception.

**Comment by slouken** [comment]
As the mappings are loaded, the new mapping is checked to see if it updates an existing mapping. Previously we did loose matching and new mappings with the same VID/PID would overwrite existing mappings with a different hardware version. The practical impact of this is that people with older drivers or older controller firmware versions would get the new mapping, which would be incorrect if the actual reported axes and buttons changed.

This was reported as Xbox controllers not having the correct mapping on some Linux versions, but with a modern kernel and fixed driver set, it's likely that this wouldn't affect Debian 12.

**Comment by smcv** [comment]
Thanks, much appreciated! I'll start the process of getting these versions into the Steam Runtime (which *does* potentially want to run on ye olde kernels), and think about whether an unblock would be desirable in Debian 12.

> with a modern kernel

FWIW the oldest kernel that will be officially supported in Debian 12 is the one from Debian 11, which is 5.10.x.
