### ISSUE TITLE
SDL3 still using -1 `SDL_JoystickID` in some places, should be `0`

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#7426]
`SDL_FindFreePlayerIndex` sets `SDL_joystick_players[]` to -1.

As does `SDL_SetJoystickIDForPlayerIndex` line 268:

```
        SDL_joystick_players[existing_player_index] = -1;
```

And `SDL_PrivateJoystickRemoved` line 1485:

```
        SDL_joystick_players[player_index] = -1;
```

That's all I could find by doing a search for -1

**Comment by slouken** [comment]
Fixed, thanks!
