### ISSUE TITLE
Wayland: Fullscreen does not respect display orientation on KDE. 

### ISSUE THREAD

**Issue by Quackdoc** [libsdl-org/SDL#7439]
`SDL_setwindowfullscreen()` does not respect compositor orientation on KDE. This applies to both auto rotation, as well as still rotation. 

on sway it seems to respect it fine, gnome is untested.

**Comment by Kontrabant** [comment]
Is it certain that SDL is the issue if it works on Weston and Sway, and only KDE is problematic? SDL reports the display orientation received from the compositor to the application, as well as adjusts the display coordinates for rotated displays. Beyond that, I'm not sure what else it is supposed to do to 'respect the compositor orientation'?

Note that I also found this related to KWin: https://invent.kde.org/plasma/kwin/-/merge_requests/2081
Seems that versions prior to 5.27 weren't using the panel orientation property.

**Comment by Quackdoc** [comment]
Ok, done some more testing, I certainly think it's a kwin issue. Tested vkmark and gamescope both exhibited the same issue, mpv did not which was the only graphical app I had been using that wasn't SDL. Reported the issue upstream.

https://bugs.kde.org/show_bug.cgi?id=467138

**Comment by Quackdoc** [comment]
https://invent.kde.org/plasma/kwin/-/merge_requests/4002

fixed upstream
