### ISSUE TITLE
SDL3 + Android: No `SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED` event at start-up without `SDL_WINDOW_FULLSCREEN`

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#7441]
I think this happened since the recent change to `SDL_CreateWindow` logic. Very easy to recreate on any Android device using the default android-project. The following code clears the screen to blue, and draws a green box to the size provided by SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED. You'll see a green box at the top-left, until an event is received, which happens when the app focus changes, or the soft buttons hidden, or orientation change, but NOT at start-up, unless using `SDL_WINDOW_FULLSCREEN`. IMPORTANT: If you test this app holding a phone in portrait, it will create a size changed event when it forces the app to landscape (which seems to be the default behaviour). Hold the device in landscape when starting the app. 
```
#include <SDL3/SDL_main.h>
#include <SDL3/SDL.h>
int main(int argc, char** argv) {
	SDL_Init(SDL_INIT_VIDEO);
	SDL_Window* w = SDL_CreateWindow("", 640, 480, SDL_WINDOW_MAXIMIZED);
	SDL_Renderer* r = SDL_CreateRenderer(w, 0, SDL_RENDERER_PRESENTVSYNC);
	int window_w = 50;
	int window_h = 50;
    while (SDL_TRUE) {
		SDL_PumpEvents();
		SDL_Event event;
		while (SDL_PeepEvents(&event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST) == 1) {
			switch (event.type) {
				case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
					window_w = event.window.data1;
					window_h = event.window.data2;
					break;
				case SDL_EVENT_QUIT:
                    SDL_Quit();
					return 0;
			}
		}
		SDL_SetRenderDrawColor(r, 0, 0, 255, SDL_ALPHA_OPAQUE);
		SDL_RenderClear(r);
		SDL_FRect box = { 0,0,window_w,window_h };
		SDL_SetRenderDrawColor(r, 0, 255, 0, SDL_ALPHA_OPAQUE);
		SDL_RenderFillRect(r, &box);
		SDL_RenderPresent(r);
	}
}
```

**Comment by slouken** [comment]
Fixed, thanks!
