### ISSUE TITLE
[Feature request] File dialogs

### ISSUE THREAD

**Issue by RT2Code** [libsdl-org/SDL#7445]
It would be very convenient to have file dialogs integrated into the SDL. Here's an example of what the interface could be :

```
typedef struct
{
    const char* description;
    const char* extension;
} SDL_FileDialogFilter;

SDL_ShowOpenFileDialog(const char *title, const char *file_name, const SDL_FileDialogFilter *filters, int filter_count, const char *default_location, SDL_Window *parent_window);
SDL_ShowOpenMultipleFilesDialog(const char *title, const char *file_name, const SDL_FileDialogFilter *filters, int filter_count, const char *default_location, SDL_Window *parent_window);
SDL_ShowSaveFileDialog(const char *title, const char *file_name, const SDL_FileDialogFilter *filters, int filter_count, const char *default_location, SDL_Window *parent_window);
SDL_ShowOpenFolderDialog(const char *title, const char *folder_name, const char *default_location, SDL_Window *parent_window);
```

I could help with the Windows implementation.

**Comment by flibitijibibo** [comment]
Prior art:

https://github.com/mlabbe/nativefiledialog

https://github.com/flibitijibibo/nativefiledialog-CS

It was kind of a pain to make GTK optional but my quick and dirty plugin system was enough, at the cost of having multiple sofiles. (This currently ships in Terraria)

**Comment by takase1121** [comment]
I think it's worth to mention that if XDG portal is running on a system it can be used to create file dialogs without ever touching the toolkit.

**Comment by slouken** [comment]
I agree this would be useful. Please feel free to create a PR for this.

**Comment by ericoporto** [comment]
Just on the topic of prior art and Linux: https://github.com/encharm/UELinuxNativeDialogs 

It has this interesting note:

> The shared libraries can be dlopened and UNativeDialogs.h should be used to utilize them.
