### ISSUE TITLE
SDL_RENDERER_ACCELERATED stray and missing pixels with SDL_Rect drawing

### ISSUE THREAD

**Issue by 12oclocker** [libsdl-org/SDL#7447]
Stray pixels and missing pixels when using SDL_RENDERER_ACCELERATED and drawing SDL_Rect with SDL_Renderer.
Problem does NOT appear using SDL_RENDERER_SOFTWARE
Example attached using SDL_RenderDrawRect.
Appear to be off by 1px off on start and finish of line drawing.
More than one user has found this bug. details below.
https://discourse.libsdl.org/t/stray-pixels-in-sdl2-program/26837

details of system this bug was found on...
libsdl2-2.0-0 (SDL version 2.0.14)
Intel(R) Core i5-4210U CPU
Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
Debian GNU/Linux 11 (bullseye)

**Comment by 12oclocker** [comment]
![example](https://user-images.githubusercontent.com/73079144/224509576-78b7b049-1ed5-4d97-a1e7-b69db4151350.jpg)

**Comment by slime73** [comment]
Which patch version of SDL2 are you using exactly? (I assume it's not actually 2.0.0 because that's a decade old.)

**Comment by 12oclocker** [comment]
SDL version 2.0.14

attached is example app to exhibit bug
`
//
// Compile command
// g++ -O2 -DLINUX -D_GNU_SOURCE -DDEBUG=1 -Wall -I /usr/include/SDL2 main.cpp -lSDL2 -o main
//

#include <stdio.h>
#include <iostream>
#include <SDL2/SDL.h>

#define C_RED     255,   0,   0, 255
#define C_GRAYBG  100, 100, 100, 255

#define width 150
#define height 150

int main(int argc, char* argv[]) {
	if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS) < 0) {
		std::cout << "Error SDL2 Initialization : " << SDL_GetError();
		return 1;
	}

	SDL_Window* window = SDL_CreateWindow("First program", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, width, height, SDL_WINDOW_OPENGL);
	if (window == NULL) {
		std::cout << "Error window creation";
		return 3;
	}

	//bug only occurs when SDL_RENDERER_ACCELERATED
	SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED); //SDL_RENDERER_ACCELERATED SDL_RENDERER_SOFTWARE
	if (renderer == NULL) {
		std::cout << "Error renderer creation";
		return 4;
	}

    SDL_Texture* texture = SDL_CreateTexture(renderer,SDL_PIXELFORMAT_YUY2,SDL_TEXTUREACCESS_STREAMING,width,height);
    if(!texture)
    { printf("ERROR SDL_CreateTexture: %s\n",SDL_GetError()); return 5;}

    //allow alpha channel enable
    SDL_SetRenderDrawBlendMode(renderer,SDL_BLENDMODE_BLEND);
    SDL_SetTextureBlendMode(texture,SDL_BLENDMODE_BLEND);

    //Select the color for drawing. It is set to gray here.
    SDL_SetRenderDrawColor(renderer,C_GRAYBG);

    //Clear the entire screen to our selected color. (also prep's the backbuffer per SDL docs, use this even if overwritting all pixels)
    SDL_RenderClear(renderer);    

	SDL_Rect rc = { 10,10, 50, 50 };
	SDL_SetRenderDrawColor(renderer,C_RED);
	SDL_RenderDrawRect(renderer,&rc);        //drawing bug occurs when SDL_RENDERER_ACCELERATED

    //Up until now everything was drawn behind the scenes.
    //This will show the new, gray contents of the window.
    SDL_RenderPresent(renderer);			

	while (true) {
		SDL_Event e;
		if (SDL_PollEvent(&e)) {
			if (e.type == SDL_QUIT) {
				break;
			}
		}	

		//do stuff
	}

	SDL_DestroyTexture(texture);
	SDL_DestroyRenderer(renderer);
	SDL_DestroyWindow(window);
	SDL_Quit();

	return 0;
}
`

**Comment by slouken** [comment]
Yes, this is a known bug fixed in more recent releases. Please try SDL 2.26 or newer.

**Comment by 12oclocker** [comment]
thanks
