### ISSUE TITLE
SDL2 2.26.4 Breaks Controller Support for Some Applications

### ISSUE THREAD

**Issue by sonic2kk** [libsdl-org/SDL#7448]
### System Information
- Kernel: 6.2.2-zen2-1-zen
- OS: Arch Linux (KDE Plasma 5.27.2 Wayland Session)

SDL 2.26.4 breaks controller support for some applications, the ones I could reproduce with were the Steam Client and [Gamepad Tester](https://gamepad-tester.com/). I tested with a Switch Pro Controller using `joycond`.

With SDL 2.26.3 and below, when a Switch Pro Controller is paired as a virtual gamepad, the Steam Client and Gamepad Tester see the controller no problem.

With SDL 2.26.4, when a Switch Pro Controller is paired either regularly or as a virtual device, neither the Steam Client nor Gamepad Tester can see the controller.

Currently I am working around the issue by downgrading my SDL version. I tried downgrading the kernel to ensure it wasn't a breakage caused by a different kernel version. The solution which worked for me was downgrading the SDL version to 2.26.3.

I initially thought this was an issue with Steam for Linux and I reported it as such (ValveSoftware/steam-for-linux#9254) but as this also affects Gamepad Tester (and perhaps other scenarios that don't impact me or that I'm not aware of), it was suggested that I report the issue here.

**Comment by slouken** [comment]
Is it https://github.com/libsdl-org/SDL/commit/cbc2b014b64dd9c1d63e873cff0ada76751fd24d that broke it for you?

**Comment by sonic2kk** [comment]
I am not sure, but that commit does look like it may have affected controller mappings. I saw the changelog mentioned some changes to controller mapping stuff on Linux so if they're related, it could be.

I use SDL from the Arch repos and a few packages I have rely on the SDL2 package, so I don't think I can simply follow the build instructions as I cannot remove the existing SDL from my system.

I'm not sure how to test if that commit is the issue but I'd be happy to test however I can :-)

**Comment by TellowKrinkle** [comment]
If you can downgrade the arch package, can you also modify it to specify that commit?

Otherwise, you can always build SDL and then manually replace the `.so` file installed by the package manager with your newly built one.

**Comment by sonic2kk** [comment]
I don't think modifying the commit is possible at least with an official package. It seems like there's an [`sdl2-git`](https://aur.archlinux.org/packages/sdl2-git) package on the AUR which would probably allow specifying a specific commit by modifying the PKGBUILD file. I would assume that would do basically the same thing as building and replacing the `.so` file, though this is absolutely out of my depth as I've never done something like this :-)

I will try it out when I have a moment though, hopefully sometime this week. Do you know if it should take a particularly long time to build? I'm fairly sure the `sdl2` package from the official Arch repos is just a pre-compiled binary so it shouldn't be compiled on install. Of course build times vary depending on system specs and such but a _rough_ idea is all I'm looking for :sweat_smile:

**Comment by TellowKrinkle** [comment]
Yeah, ideally you test both fa9f7c70c5bf75ee841c97cae87cfae74f018a9c and cbc2b014b64dd9c1d63e873cff0ada76751fd24d, verifying that it's both broken on cbc2b014b64dd9c1d63e873cff0ada76751fd24d and working on fa9f7c70c5bf75ee841c97cae87cfae74f018a9c

On my computer (i9-9980HK), SDL takes about a minute to build (30s `configure`, 20s `make -j16`).  Configure is single threaded, so even if you don't have 8 cores, it'll probably still take around a minute.

**Comment by sonic2kk** [comment]
Thanks, SDL builds very fast on my system as well (didn't time it, but fast enough that it was not a problem at all to build two packages from each commit).

Unfortunately things seemed to have changed. Now SDL-2.26.3, https://github.com/libsdl-org/SDL/commit/fa9f7c70c5bf75ee841c97cae87cfae74f018a9c, https://github.com/libsdl-org/SDL/commit/cbc2b014b64dd9c1d63e873cff0ada76751fd24d and SDL-2.26.4 all seem to work for gamepad-tester. This wasn't the case earlier this morning when I did a quick test, then I had a bunch of system updates to run, and now testing again Gamepad Tester works but only if I connect my controller *after* loading the site.

And also now, Steam doesn't recognise my controller *at all*, even with SDL-2.26.3, and this worked earlier this morning as I was using it to test, so Steam Input does not work.

Perhaps now that Gamepad Tester is working as expected, this is an issue related to Steam, and the issue I raised downstream (https://github.com/ValveSoftware/steam-for-linux/issues/9254) should be re-opened?

I don't have any other applications to test as far as I'm aware. Gamepad Tester and Steam were the only two that I knew of which rely on the Switch Pro Controller to be connected as a virtual device. Every other application I use (Dolphin, Ryujinx, SuperTuxKart were tested) need the controller to be connected normally and they have recognised my controller just fine on all 4 versions I tried. Previously Gamepad Tester and Steam worked with SDL-2.26.3 but not with 2.26.4, but now Gamepad Tester works with both SDL versions, and now Steam works with neither.

**Comment by sonic2kk** [comment]
Okay, I did some further investigation and here's what I found.

- SDL 2.26.3 will work if I unpair and re-pair my Switch Pro Controller - That is, I remove it from the remembered Bluetooth devices and then repair it.
- SDL 2 from commit https://github.com/libsdl-org/SDL/commit/fa9f7c70c5bf75ee841c97cae87cfae74f018a9c will work following the same steps (unpairing and re-pairing).
- SDL 2 from commit https://github.com/libsdl-org/SDL/commit/cbc2b014b64dd9c1d63e873cff0ada76751fd24d does **not** work at all, even after unpairing and re-pairing.
- SDL 2.26.4 does not work either.

So the culprit appears to be SDL 2+Steam. This does not affect any other applications both when using the Pro Controller paired regularly and as a virtual device. This issue only affects the Steam Client, at least out of the small handful of applications which I have tested:
- SuperTuxKart
- Ryujinx
- Yuzu
- Dolphin

I am also able to reproduce the issue on my laptop running Arch with essentially the same software setup as my PC (`joycond` driver installed, Arch Linux + KDE Plasma Wayland, Zen kernel, etc).

**Comment by slouken** [comment]
Have you tried the latest SDL in the SDL2 branch? If that's working for you, then Steam should work in the client beta next week.

**Comment by Balderick** [comment]
SDL2 Gamepad Mapper is a handy tool to help see if  the issue is steam sdl or otherwise, especially handy when steam is detecting controller but is applying bad controller layout and/or game configs.  imo steam shipping with sdl3 and sdl2 dll's breaks much of sdl2 in steam and Valve have hardcoded stuff that breaks any controller support in Steam for some gaming devices i.e. T500 RS steering wheel.
I used sdl2 gamepad mapper to prove nothing wrong with sdl to map wheel buttons and set as ps2 type controller - like i used to be able to do in steam define layout ui so i can use wheel buttons to navigate steamui but then just disable steam input for game to get wheel working in games that natively support it.   This used to add huge immersion to VR session for racing games but apparently linux cant do that so T500 got blacklisted to benefit linux users only..   Thanks for that slouken [/sarcasm]

https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/releases

At least it is not web based like gamepadtester - it really a html5 app, not sure how to check what build of sdl it uses.

**Comment by sonic2kk** [comment]
The issue seems to lie with some udev rules. After troubleshooting for a while I found that running the following command and restarting Steam fixes the issue:

```
sudo udevadm control --reload-rules && sudo udevadm trigger
```

The issue appears to be neither to do with SDL nor Steam. Apologies for the confusion here. Closing.
