### ISSUE TITLE
SDL audio callback not called frequently enough

### ISSUE THREAD

**Issue by rom1v** [libsdl-org/SDL#7450]
In an application, I set the audio callback buffer size to 5ms (240 samples, for an audio stream with 2 channels `SDL_AUDIO_F32` at 48000Hz). It works well for almost everyone.

But one user reported an audio playback issue, and with the provided logs, it appears that the SDL audio callback is called twice too infrequently (it is called every 10ms to request 5ms of samples): https://github.com/Genymobile/scrcpy/issues/3793
Doubling the `SDL_AudioSpec.samples` value from 240 to 480 fixes the problem.

Is it an SDL issue?

**Comment by slouken** [comment]
While lower values often work, we recommend setting samples to 1024 to cover systems that can't handle lower latencies.

Can you provide more information on the affected system? Sound card, OS, etc.?

**Comment by slouken** [comment]
Unfortunately, it's not. I use 512 or 1024 for all my applications to be safe.

**Comment by rom1v** [comment]
OK, thank you. I will expose an option to let users configure it then.

**Comment by icculus** [comment]
If things go as planned, I'm getting rid of this in SDL3, fwiw.

**Comment by rom1v** [comment]
Getting rid of what? The audio output buffer? How would it work?

**Comment by icculus** [comment]
You queue data into an SDL_AudioStream (or several SDL_AudioStreams), we figure out how to mix everything and feed it to the hardware. No callback, no "samples" setting because we'll handle that internally.

That's the gameplan at least.

**Comment by rom1v** [comment]
OK, but if an `SDL_AudioStream` is involved (for mixing/converting), will latency be increased? (my use case is to mirror an audio stream with the minimal possible latency, once I give the samples to SDL I want them played as soon as possible).

**Comment by slouken** [comment]
You should use a larger mixing buffer size in SDL2, 1024 is a good value. @icculus's changes for SDL 3.0 are in as well, so you can try that out if you want.
