### ISSUE TITLE
Regression for DualShock 4 controllers on macOS

### ISSUE THREAD

**Issue by leonstyhre** [libsdl-org/SDL#7451]
Hi!

There seems to have been a regression introduced at some point that breaks support for DualShock 4 controllers on macOS when using the GameController API.
I don't know exactly when it occurred, only that it works fine in 2.0.18 but is no longer working in 2.26.3 which I currently use for my application (ES-DE).

What happens is that SDL seems to mix up the wired and wireless GUID:s for this device.

For my controller these are the GUIDs:
050000004c050000cc090000ff870001 (wireless)
03008fe54c050000cc09000000016800 (wired)

In 2.0.18 both are correctly identified and both connection modes work.

In 2.26.3 however the wired GUID is always used, even if the controller is in wireless mode which means no input events are registered. Wired mode works correctly though.

Only the DualShock 4 is affected as far as I know, DualSense controllers seem to work fine.
The situation with these two controllers have been confirmed by other people as well so it's not isolated to my specific controllers or my computer.

Thanks in advance!

**Comment by leonstyhre** [comment]
@slouken Any chance of having this fixed in 2.28.0 as currently this makes DualShock 4 controllers unusable on macOS? Thanks :)

**Comment by slouken** [comment]
Does https://github.com/libsdl-org/SDL/commit/57ae9f466db41e32c67c5a9a03c28f7803ac02c9 fix your issue?

**Comment by slouken** [comment]
The GUIDs are not an issue, the ...6800 GUID just means it's being handled by the HIDAPI driver, which is what I would expect.

**Comment by leonstyhre** [comment]
Thanks for the explanation, I can confirm that this patch fixes the issue! (I've only tested it on macOS though.)

**Comment by slouken** [comment]
Great, thanks!
