### ISSUE TITLE
Mouse wheel value is always 0

### ISSUE THREAD

**Issue by genericptr** [libsdl-org/SDL#7454]
On my MacBook the Y value from SDL_MouseWheelEvent  in only one direction always returns 0. It's strange because all the other values are correct so it's just this one direction.

Here's my system. Any ideas?  I would blame my Pascal headers struct definition but this used to work before so I'm curious what changed.

SDL version: 2.24.1

<img width="240" alt="Screenshot 2023-03-13 at 8 37 47 AM" src="https://user-images.githubusercontent.com/10937186/224589547-8f8234ba-9060-4ae0-9c59-f94535f369c1.png">

**Comment by genericptr** [comment]
Just wanted to mention this is the negative Y axis which is always 0, that is it returns positive values for Y but not negative so it only scrolls in one direction.

**Comment by slouken** [comment]
If you set this environment variable `export SDL_EVENT_LOGGING=1` and then run your application from the Terminal, you should get detailed logging of events. Can you add the output of the mouse wheel events?

Also, are you using the built-in trackpad or an external mouse?

**Comment by genericptr** [comment]
Sorry I'm mistaken, SDL_EVENT_LOGGING reveals the the data is correct but I was misusing the event struct and getting bad values.

**Comment by slouken** [comment]
I'm glad you figured it out. :)
