### ISSUE TITLE
Add ObjectiveC to `project` decl in CMakeLists

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [libsdl-org/SDL#7456]
As-is I'm getting `error: Objective-C was disabled in PCH file but is currently enabled`, but changing the project call to read `project(SDL3 LANGUAGES C CXX VERSION "3.0.0")` resolves it - as CMake doesn't seem to tell Clang to emit an ObjC pch otherwise. I'm working off of trunk as of the time of writing.

If this is something on my end I apologise, though in that case I'm unsure of what's wrong here.

```
$ clang -v
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by Th3T3chn0G1t** [comment]
I found I also need to add `enable_language(OBJC)`

**Comment by madebr** [comment]
Are you building SDL as a subproject?
We're only enabling `OBJC` when SDL is built as the top project.

https://github.com/libsdl-org/SDL/blob/d5b5e524af010d51437470255d5ac848996eeabd/cmake/macros.cmake#L114-L130

We can perhaps unconditionally enable `OBJC` and emit a warning when it was not enabled before.
This, plus adding a FAQ item might solve this.

**Comment by Th3T3chn0G1t** [comment]
Ah that would be it - yeah it's a subproject

**Comment by Th3T3chn0G1t** [comment]
Same situation for both - and no I don't enable ObjC in my top level project

**Comment by madebr** [comment]
So you're not getting a `CMAKE_OBJC_COMPILE_OBJECT` error/warning?
Does the generator matter? Can you repeat the experiment with the `Xcode` and `Ninja` generator?

**Comment by Th3T3chn0G1t** [comment]
@madebr I did a full clean and rebuild with all three:

With an unmodified CMakeLists.txt:
**make**: Produces the original `Objective-C was disabled in PCH file but is currently enabled`.
**ninja**: ...
**xcode**: Objective-C seems to be completely broken - get errors such as:
```
error: expected identifier or '('
@class NSInvocation, NSMethodSignature, NSCoder, NSString, NSEnumerator;
^
```
(Full log at https://pastebin.com/phQ0bTA3)

With ObjectiveC unconditionally enabled:
**make**: No change
**ninja**: No change
**xcode**: No change

**Comment by madebr** [comment]
Thanks for doing these tests. It's very appreciated! SDL's CMake behavior on Apple is partially unknown to me.

I tried to reproduce these issues on ci at [`madebr/SDL@803d4a7c`](https://github.com/madebr/SDL/tree/803d4a7cb41e6b0f55e1784c588bd81c23cf7eca). It builds SDL as main and subproject, optionally enables OBJC in the main project, and does this for Ninja and Xcode generator.

I found only one error:

- building SDL as a subproject with the Ninja generator without `enable_language(OBJC)~ fails with the following error when compiling `.m` sources:
    ```
    error: C17 was enabled in PCH file but is currently disabled
    ```

I think I fixed this + not passing `-x objective-c` to `.m` sources in https://github.com/libsdl-org/SDL/pull/7471.
Can you please try running these tests using this pr?

**Comment by Th3T3chn0G1t** [comment]
@madebr Yeap! That did indeed fix the issue.

**Comment by madebr** [comment]
Thanks for the help!
