### ISSUE TITLE
Re-evaluate default GL backbuffer red/green/blue/alpha bit sizes

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#7462]
Right now, the default backbuffer color format when creating an OpenGL context (`SDL_GL_RED_SIZE`, `SDL_GL_GREEN_SIZE`, `SDL_GL_BLUE_SIZE`, and `SDL_GL_ALPHA_SIZE`) is 3/3/2/0. Most graphics drivers don't actually support an 8 bit per pixel backbuffer and will choose something it does support, like 8/8/8/x or 5/6/5/0 or similar. It's sort of inconsistent and unreliable cross-platform.

In my opinion 8/8/8/8 would be a more solid and expected default compared to 3/3/2/0 and even 5/6/5/0 (most desktop drivers don't really support the latter either). I don't know of any GL/GLES-capable phones that don't support 8/8/8/8, but app developers could still choose 5/6/5/0 for specific use cases they have.

Defaulting to 8/8/8/8 would also allow `SDL_WINDOW_TRANSPARENT` to work without fiddling with bit sizes, when using OpenGL.

Or maybe other people have different opinions, but I wanted to throw it out there since 3/3/2/0 as a default has always seemed super weird to me and has caused issues in the past (for example the Android readme recommends avoiding it).

**Comment by slouken** [comment]
I think for SDL3 we can default to 8/8/8/x where x is 0 for regular windows and 8 for transparent windows.

**Comment by 1bsyl** [comment]
this parts should be updated https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L3789

but glconfig is in SDL_VideoDevice struct, whereas it should be within SDL_Window struct

https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_sysvideo.h#L371

**Comment by slouken** [comment]
Yes, the GL attributes need to be set before creating a window, so they're global for the application.

**Comment by 1bsyl** [comment]
yes, so difficult to have "default to 8/8/8/x where x is 0 for regular windows and 8 for transparent windows.", 
if the window isn't created.
a const 8888 or 8880 would be easier.

Or: 
starts with 8880
And if this hasn't been explicitly set with SDL_GL_SetAttribute , and we have transparency, overload to 8888 ?

**Comment by slouken** [comment]
> Or: starts with 8880 And if this hasn't been explicitly set with SDL_GL_SetAttribute , and we have transparency, overload to 8888 ?

Yeah, that sounds reasonable.

**Comment by slime73** [comment]
What benefit does 8880 give over 8888? GPUs don't like non power of two pixel sizes very much so I'd have thought the driver would just use 8888 internally in that situation.

**Comment by slouken** [comment]
They're both 32-bit formats, but the alpha channel can be used in whole-window compositing for transparent windows if enabled.

**Comment by slime73** [comment]
If 888x (32 bit) is requested, I believe many drivers will give back 8888 but maybe some won't. This could be confusing to developers if for example they have screenshot code which uses glReadPixels to copy the backbuffer and save it to a PNG, and the saved PNG is opaque on the developer's computer but transparent on other users'.

I just don't really understand what the purpose of trying to request 8880 is, if it's going to be 32 bit anyway and it's overall less consistent to have the split between requesting 8880 depending on non-GL configuration, versus getting back 8888 on different drivers.

**Comment by 1bsyl** [comment]
changing to 8888 also in SDL_test_common.c
 https://github.com/libsdl-org/SDL/pull/7482

**Comment by 1bsyl** [comment]
marked as fixed 
updated sdl2-compat: https://github.com/libsdl-org/sdl2-compat/commit/a445d8b63aea6313431d1191b790b905bb663c84

**Comment by 1bsyl** [comment]
for the record, this seems to cause some trouble using SDL+QT5: https://github.com/libsdl-org/SDL/issues/7511

**Comment by Desoroxxx** [comment]
The documentation still says `3/3/2/0` is it outdated?

**Comment by slouken** [comment]
> The documentation still says `3/3/2/0` is it outdated?

Yes, where does it say that?

**Comment by Desoroxxx** [comment]
> > The documentation still says `3/3/2/0` is it outdated?
> 
> Yes, where does it say that?

![Image](https://github.com/user-attachments/assets/392b23f3-770c-430f-aaf9-bab3f557c7f7)

![Image](https://github.com/user-attachments/assets/020907cd-8548-4e7f-885a-8d0b6c1630e7)

**Comment by slouken** [comment]
Fixed, thanks!
