### ISSUE TITLE
error - clangd reported clang error: In included file: definition of builtin function '__rdtsc'

### ISSUE THREAD

**Issue by kglundgren** [libsdl-org/SDL#7465]
clang gives me this error when including SDL.h. It seems to originate from SDL_cpuinfo.h -> intrin.h.
I'm using mingw64 from MSYS2 on Windows 10.

How would I go about fixing this? I've been unable to disable the error via compiler flags and source pragmas.

**Comment by madebr** [comment]
Can you provide a little reproducer?
We're testing [all 5 msys2 flavors](https://github.com/libsdl-org/SDL/blob/57ae9f466db41e32c67c5a9a03c28f7803ac02c9/.github/workflows/main.yml#L18-L22) on ci, so perhaps you're doing something special.

Maybe useful, what versions of SDL2 and clang are you using?

**Comment by kglundgren** [comment]
I forgot the most important part, **this error is coming from clangd**, the language server, not clang itself. I will correct the title of the post after posting this. I'm using gcc to compile with cmake. 

I'll try my best to make it reproducible, please let me know if there is any other information you may need. 

## MSYS2 and Windows w/ neovim and clangd setup
1. Install the latest version MSYS2 on Windows. Enter commands 2 & 3 in the MSYS2 MINGW64 terminal.
2. pacman -Syu
3. pacman -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-SDL2
4. You should now have the following versions installed: gcc version 12.2.0 (Rev10, Built by MSYS2 project), cmake version 3.25.3, sdl2 version 2.26.4.
5. **Leave MSYS2,** and do the next part in Windows directly (eg. pwsh in the Windows Terminal).
6. Install neovim >= v0.8.
7. Install clangd v15.0.6 and pass it this command on startup: --query-driver=C:\msys64\mingw64\bin\gcc.exe.

That's the setup part done... I know it's a lot, but I was able to reproduce it on 2 computers, my personal laptop and on my work PC. I'm thinking that the problem is that clangd can't find the correct headers or something like that.

## Project setup

1. In the project folder, create CMakeLists.txt like this: 

```cmake
cmake_minimum_required(VERSION 3.25.0)
project(sdl-test)
add_executable(sdl-test src/sdl-test.c)
target_include_directories(sdl-test SYSTEM PRIVATE C:\\msys64\\mingw64\\include)
target_link_libraries(sdl-test mingw32 SDL2main SDL2)
```

2. Create a folder `src` with the file `sdl-test.c` with these contents:

```c
#include <SDL2/SDL.h>

int main(int argc, char **argv)
{
}
```

4. Create a folder `build`.
5. In the MSYS2 MINGW64 terminal, run this cmake command in the build folder: `cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++`
6. Move `compile_commands.json` to the root of the project. 
7. Start `nvim src/sdl-test.c` and observe the clangd reported clang error: `In included file: definition of builtin function '__rdtsc'`.

**Comment by kglundgren** [comment]
@madebr Turns out that this had nothing to do with SDL, after all. I posted in the clangd repo about how I managed to solve this issue here: clangd/clangd#1541, but I will repost the text here as well, in case someone else needs to know how to fix it.

> I wasn't able to get any of the config files working when specifying a --query-driver, neither %localappdata%\clangd\config.yaml or the local project root .clangd were respected.
> 
> However, I actually managed to solve this! I installed mingw-w64-x86_64-clang and mingw-w64-x86_64-clang-tools-extra from MSYS2, and then pointed Neovim to use that clangd.exe (from C:\msys64\mingw64\bin\clangd.exe) instead of the clangd I had installed from Mason. (I'm talking about the Windows Neovim instance here, Neovim doesn't seem to work properly when used in the MSYS2 MINGW64 shell.) This solved all of my issues -- no weird include or definition errors -- and I didn't even have to use any clangd config files at all anymore (the config files started working when I used the clangd from MSYS2). It seems like that clangd version that I installed from Mason wanted to use the MSVC stuff, paths and includes and such.

**Comment by madebr** [comment]
Great to hear you figured it out and got back to us!

**Comment by mlauronen** [comment]
[https://github.com/clangd/clangd/issues/1541#issuecomment-1793677824](https://github.com/clangd/clangd/issues/1541#issuecomment-1793677824)
