### ISSUE TITLE
Question about Stadia Bluetooth controller mappings

### ISSUE THREAD

**Issue by murrant** [libsdl-org/SDL#7472]
Looks like it was added here #7193

But I checked a couple of my Stadia controllers and get different GUID.  Will these still work or do we need a mapping for every single controller?

0500e045d11800000094000000010000635337888 StadiaNSR2-cfe1
0500e3ead11800000094000000010000635337888 StadiaFXLW-5bc3

**Comment by slouken** [comment]
These will work, the name (and name CRC) can be different.

**Comment by murrant** [comment]
I built SDL from git and can confirm, sorry should have done that first :flushed:
