### ISSUE TITLE
`SDL_BLENDMODE_MUL` can be simplified to keep destination alpha constant

### ISSUE THREAD

**Issue by rohlem** [libsdl-org/SDL#7473]
After reading the definition of [`SDL_BLENDMODE_MUL`](https://github.com/libsdl-org/SDL/blob/981e0d367c9c5320970bfd39a8ba8747a7c2e393/include/SDL_blendmode.h#L53), the alpha formula seems redundant to me:
`dstA = (srcA * dstA) + (dstA * (1-srcA))` can be rewritten as `dstA * (srcA + (1 - srcA)) = dstA * 1 = dstA`.

If my understanding is correct, the alpha component could really just be replaced by constant `dstA` (like in blendmodes `ADD` and `MOD`). Or maybe I'm misunderstanding something, and/or the documentation is wrong.

This blending mode was introduced in commit 981e0d3. From a quick glance at it the relevant implementation sections (as introduced in the commit) to change would be:
- [`include/SDL_blendmode.h`](https://github.com/libsdl-org/SDL/blob/981e0d367c9c5320970bfd39a8ba8747a7c2e393/include/SDL_blendmode.h#L55): simplify the formula in the doc comment
- [`src/render/SDL_render.c`](https://github.com/libsdl-org/SDL/blob/a17ad65f2b99785554ef60fd75135b5859b86ddd/src/render/SDL_render.c#L88): replace last three factors, like in the other blend modes, with `SDL_BLENDFACTOR_ZERO`, `SDL_BLENDFACTOR_ONE`, `SDL_BLENDOPERATION_ADD`
- [`src/render/psp/SDL_render_psp.c`](https://github.com/libsdl-org/SDL/blob/981e0d367c9c5320970bfd39a8ba8747a7c2e393/src/render/psp/SDL_render_psp.c#L684): adapt the implementation? I've found [the called function](https://pspdev.github.io/pspsdk/group__GU.html#ga8cb7979517331dd069d3bf7d032c62b6) via internet search, but haven't been able to figure out where/how the alpha formula is specified here (if at all?)
- [`src/render/software/SDL_draw.h`](https://github.com/libsdl-org/SDL/blob/981e0d367c9c5320970bfd39a8ba8747a7c2e393/src/render/software/SDL_draw.h#L90): remove the line modifying alpha
- [`src/video/SDL_blit_slow.c`](https://github.com/libsdl-org/SDL/blob/981e0d367c9c5320970bfd39a8ba8747a7c2e393/src/video/SDL_blit_slow.c#L160): remove the lines modifying alpha
- [`src/video/directfb/SDL_DirectFB_render.c`](https://github.com/libsdl-org/SDL/blob/981e0d367c9c5320970bfd39a8ba8747a7c2e393/src/video/directfb/SDL_DirectFB_render.c#L205): maybe adapt the implementation, though I currently don't understand it enough
- [`src/video/sdlgenblit.pl`](https://github.com/libsdl-org/SDL/blob/981e0d367c9c5320970bfd39a8ba8747a7c2e393/src/video/sdlgenblit.pl#L332): remove this line... I think. (Seems to be the one added in the commit.) Then regenerate `src/video/SDL_blit_auto.c`.

**Comment by slouken** [comment]
I think you're right. Do you want to make a pull request for this change?

**Comment by 1bsyl** [comment]
funny bug ...
also, triangle should be updated in the same way as SDL_blit_slow.c: 
https://github.com/libsdl-org/SDL/blob/main/src/render/software/SDL_triangle.c#L871

**Comment by rohlem** [comment]
I don't have the repository pulled at the moment, also I'm not 100% sure of my changes, and what other places could need adapting. (Also I don't have Pearl handy to generate `SDL_blit_auto.c` .)
So if someone more familiar could do it, that would probably be faster. Otherwise I can probably get around to it this weekend - if there's no other updates linked here I'll open a PR then.

**Comment by 1bsyl** [comment]
I can probably submit a PR later

**Comment by 1bsyl** [comment]
I didn´t change the gl renderer, because maybe the current implementation is faster, and this should be tested

with constant = 1 - srcA 
dst = src * dst + dst * constant. 
this may be faster than doing each channel independently ?

only the sw part is changed, see the PR. I spitted that in different commit too.

**Comment by slime73** [comment]
> I didn´t change the gl renderer, because maybe the current implementation is faster

Desktop GPUs use fixed-function blending hardware which shouldn't have any performance difference between different configurations. Some mobile GPUs do blending via shaders, which might be slightly faster with the simplified version (although it probably won't be a noticeable performance difference even then).

**Comment by 1bsyl** [comment]
ok, so I've updated the SDL_BLENDMODE_MUL_FULL
directfb disappeared...
didn't changed psp...

**Comment by 1bsyl** [comment]
Marked as fixed with PR https://github.com/libsdl-org/SDL/pull/7475 and https://github.com/libsdl-org/SDL/pull/7477 for SDL2
In addition to the simplification of SDL_BLENDMODE_MUL, the alpha value was sometime wrong.

(with blit auto and draw.h, when blitting from non-alpha format to alpha format, dstA would be set to 0xff (instead of keeping dstA).
eg: SDL_blit_auto.c // SDL_Blit_BGR888_ARGB8888_Blend )

**Comment by rohlem** [comment]
Cool, thanks for the quick fix!

**Comment by 1bsyl** [comment]
@rohlem you're welcome! thanks for the spotting this issue + all detailed commits and sources !

**Comment by iryont** [comment]
I was the one to write this code. It's quite funny how I didn't notice this and instead I overcomplicated alpha formula. I think I simply copied formulas from some OpenGL specs and I didn't even pay much attention to it.

Anyway, thanks for noticing and simplifying this implementation :)
