### ISSUE TITLE
When using HIDAPI on macOS, controllers get duplicate MFi versions

### ISSUE THREAD

**Issue by hikari-no-yume** [libsdl-org/SDL#7479]
OS: macOS 12.6.3 Monterey
SDL version: 2.26.4
Controller: Nintendo Switch Joy-Cons L & R, connected over Bluetooth

[My app](https://github.com/hikari-no-yume/touchHLE) sees two different copies of this “controller”:

```
New controller connected: Nintendo Switch Joy-Con (L/R).
New controller connected: MFi Gamepad.
```

This is annoying for my particular use-case since I don't have a way to select a controller right now, instead I sum the inputs across all connected controllers. But I guess I'll have to add one considering the unfortunate behaviour that will have here (2× analogue stick sensitivity).

If I set the hint `SDL_JOYSTICK_HIDAPI_JOY_CONS` to `0`, then I no longer have the dupe, but then I wouldn't get accelerometer sensing, which is a real shame. It'd also be a pretty macOS-specific hack.

**Comment by hikari-no-yume** [comment]
Additionally, it's surprising that the name is just “MFi Gamepad”, considering SDL2 has SDL2 has specific code for detecting Joy-Cons, including paired ones, via MFi. But that's no big deal.

**Comment by hikari-no-yume** [comment]
Hmm, it seems like SDL has deduplication code:

https://github.com/libsdl-org/SDL/blob/a9650d440a862b86dc5722a402b06bf2bbbec527/src/hidapi/mac/hid.c#L558-L567

But it works the wrong way around (skips the HID device rather than the MFi device) and is disabled?

**Comment by hikari-no-yume** [comment]
> Additionally, it's surprising that the name is just “MFi Gamepad”, considering SDL2 has SDL2 has specific code for detecting Joy-Cons, including paired ones, via MFi. But that's no big deal.

Aha, I think this is specific to when macOS's built-in Joy-Con combining happens. If there's just a single Joy-Con, it shows up with some name along the lines of “Joy-Con (L)”, which is slightly different from the SDL HIDAPI controller's name (one or the other doesn't have the “Nintendo Switch” suffix).

**Comment by hikari-no-yume** [comment]
@slouken Would you like me to make a separate issue for the naming thing?

**Comment by slouken** [comment]
No, I can look at these together. I think the resolution will be that the HIDAPI version will be preferred, I'm just not sure why the existing detection code doesn't work.

**Comment by hikari-no-yume** [comment]
> I think the resolution will be that the HIDAPI version will be preferred, I'm just not sure why the existing detection code doesn't work.

For my app I would like HIDAPI to be preferred, because it gives me accelerometer access, whereas the “MFi” way doesn't. At least, this is the case for Joy-Cons.
