### ISSUE TITLE
Should Gamecube controllers work with the pre-built SDL on Windows?

### ISSUE THREAD

**Issue by Lokathor** [libsdl-org/SDL#7481]
On my windows machine I've set up my gamecube controller to work with the Dolphin emulator using the Zadig driver ([as described in their docs](https://dolphin-emu.org/docs/guides/how-use-official-gc-controller-adapter-wii-u/#Using_Zadig)). However, the gamecube controller isn't detected by the pre-built version of SDL provided on the releases page.

So my questions are basically:
* Should the pre-built SDL for windows detect a GameCube controller by default? Do I have to do a custom build of the library using some other flag?
* If the controller should work using the pre-built SDL, does using the Zadig driver make things not work? Since it's the suggested driver method to make Dolphin work with the controller I would hope that SDL is also compatible, but perhaps not?

**Comment by flibitijibibo** [comment]
The Zadig part is okay, but SDL currently requires self-building with libusb support enabled:

https://github.com/libsdl-org/SDL/blob/main/src/hidapi/SDL_hidapi.c#L691

By default it's not enabled because libusb takes over the whole endpoint (so you couldn't have Dolphin running at the same time as something else, for example). Hoping to fix that with this: #6014

**Comment by Lokathor** [comment]
@slouken I don't believe this is resolved. At least, it's not resolved according to the comments in #6014 , which is the last issue/pr to reference this issue.

**Comment by slouken** [comment]
It's resolved in that I think your questions are answered:

> Should the pre-built SDL for windows detect a GameCube controller by default? Do I have to do a custom build of the library using some other flag?

No, it should not, you need to build SDL with libusb, as @flibitijibibo mentioned.

**Comment by Lokathor** [comment]
Ah, fair enough. If I *wanted* them to be supported in the pre-built windows distribution should I open a fresh issue for that?

**Comment by slouken** [comment]
Yes, but we intentionally don't build with it. We don't want to pull it in as a general dependency.
