### ISSUE TITLE
SDL_RenderSetVSync() with simulated vsync fails to update SDL_RENDERER_PRESENTVSYNC

### ISSUE THREAD

**Issue by ivan-mogilko** [libsdl-org/SDL#7491]
With the simulated vertical sync, the RendererInfo's flags have correct SDL_RENDERER_PRESENTVSYNC state if the vsync was requested at Renderer's creation. However, if you call SDL_RenderSetVSync() anytime later, the vsync state changes, but SDL_RENDERER_PRESENTVSYNC flag is not updated (neither set nor removed). This makes it impossible to detect the current state using RendererInfo.

Tested with 2.27, commit 23bce27b26aa078a902ed73878b21d2fe94cc6e5.

EDIT: There seem to be an additional problem.

Logging the return value of a renderer->SetVSync displays it is "5" on my system (which also complies to a failure as it's not "0"?). The code in SDL_RenderSetVSync, however, tests strictly for value < 0:
https://github.com/libsdl-org/SDL/blob/446e0943da8c543ba0dbade1a8822d805ca8d347/src/render/SDL_render.c#L4512-L4517

For a comparison, SDL tests the render info flags when creating a renderer:
https://github.com/libsdl-org/SDL/blob/446e0943da8c543ba0dbade1a8822d805ca8d347/src/render/SDL_render.c#L1018-L1025

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by ericoporto** [comment]
@slouken , in case a 2.26.5 is planned, it would be nice to have this fix backported there too.

**Comment by slouken** [comment]
Yep, I just merged this fix, thanks.
