### ISSUE TITLE
Creating a window with SDL_WINDOW_MINIMIZED does not minimize the window

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#7492]
The SDL window is not minimized at start-up when using `SDL_WINDOW_MINIMIZED` in the initial window flags.

Steps to reproduce:
- build `testdraw`
- run with `testdraw 4 --vsync --minimize`.
  (with `SDL_VIDEO_DRIVER=wayland` or `SDL_VIDEO_DRIVER=x11`)

`--vsync` and `4` were added to lower the cpu load

Expected behavior:
Window is minimized

Actual behavior:
Window is shown

System:
Fedora Linux 36

**Comment by slouken** [comment]
I think this is caused by the renderer recreating the window and losing the minimized state.

**Comment by slouken** [comment]
Are you still seeing this? I just tested with the latest main code and the window was created in a minimized state on both X11 and Wayland.

**Comment by Kontrabant** [comment]
This used to be inconsistent across platforms as it relied on the backend driver checking the flags and taking the appropriate actions when showing the window, but now windows are created in the 'normal' state and set to minimzied/maximized/fullscreen later in the process, so this is fixed and consistent across platforms.

**Comment by slouken** [comment]
Thanks!
