### ISSUE TITLE
SDL_GetFullscreenDisplayModes retuns empty list

### ISSUE THREAD

**Issue by 1vanK** [libsdl-org/SDL#7493]
After this <https://github.com/libsdl-org/SDL/commit/6b137579eaa4ff47c936e72ced73939bc69daa62#diff-c7876243863d7fbb4c1fbd0f1ed1fbd3c0fa003da7acc0ecc9d295ed4f4351beL707-L720> return empty list when `SDL_VIDEO_DRIVER_X11_XRANDR` is not defined. In old version the list contained current resolution

**Comment by slouken** [comment]
If `SDL_VIDEO_DRIVER_X11_XRANDR` is not defined, I believe setting a fullscreen resolution will fail, and in that case there are no valid true fullscreen resolutions available. If that's not the case, then setting the current resolution would be appropriate. Can you double check and submit a PR once you've tested it?

**Comment by 1vanK** [comment]
`SDL_VIDEO_DRIVER_X11_XRANDR` is not defined when `libxrandr-dev` is not installed. Perhaps the new version of the function is the correct behavior, since the developer just forgot to install all the necessary libraries.
