### ISSUE TITLE
Improve window move/resize performance on X11

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#7494]
Some window managers will silently block application move requests, for example when trying to move windows over the task bar, etc.

Currently there is code in SDL_x11window.c that waits for the move/resize to complete and will time out after 100ms. This causes a hitch in applications trying to animate motion, e.g. sliding a window onto the screen, etc.

There are a couple of approaches to deal with this.

One approach is to change the contract of the SDL API, allowing the application to request move/resize changes and then handling events to indicate that they were honored by the window manager. This is more likely to be future proof as there are more and more cases where the OS windowing system may adjust window position and sizing based on other constraints.

Another approach is to simply add a hint that allows us to skip the wait for move/resize changes. We'd need to carefully test to make sure the asynchronous nature of this doesn't cause other problems, e.g. position bouncing back and forth as the application request and subsequent events fight each other setting the current position of the window.

For what it's worth, changes on windows marked override redirect won't be adjusted by the window manager, and it's likely safe to assume that those changes will go through immediately.

**Comment by flibitijibibo** [comment]
This might be something that can be combined with #6646, since lots of the issues also come from chains of SDL_SetWindow calls.

**Comment by slouken** [comment]
@Kontrabant, is this fixed by https://github.com/libsdl-org/SDL/pull/8472?

**Comment by Kontrabant** [comment]
It should be, as move and resize operations don't block anymore unless the application explicity wants to block until the window manager completes the pending operation (or times out).
