### ISSUE TITLE
The "event.jbattery.which" field contains wrong joystick instance ID

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#7497]
I am using the official SDL library version 2.26.4 ([this release](https://github.com/libsdl-org/SDL/releases/tag/release-2.26.4)) and Windows 10.

I don't have any joystick connected to the computer, I turn on the game, it starts correctly, the window shows up. If I now connect the controller, my log system will add the following two lines to the console:

```
00  00:00:07.958  INFO     Gamepad "0" connected.
00  00:00:08.110  INFO     Gamepad "0" initialized successfully: "Xbox 360 Controller" (0x2249BAF5D80AB67F), buttons: 11, hats: 1, axes: 6, sticks: 2.
```
The joystick identifier `0` is the contents of the `event.jdevice.which` field from the `SDL_JOYDEVICEADDED` event structure. Now when I press any button, SDL generates the `SDL_JOYBATTERYUPDATED` event and a line is added to the console about it:

```
00  00:03:09.570  INFO     Gamepad "0" changed power level to "wired".
```
The joystick identifier `0` is the contents of the `event.jbattery.which` field from the `SDL_JOYBATTERYUPDATED` event structure. Now I disconnect the controller and get an event about it which is logged:

```
00  00:05:08.605  INFO     Gamepad "0" named "Xbox 360 Controller" (0x2249BAF5D80AB67F) disconnected.
```
The joystick ID comes from the `event.jdevice.which` field of the `SDL_JOYDEVICEREMOVED` event structure.
____

So I'm doing a quick test to see if joystick attaching and detaching works properly and if the joystick events contain correct data. The sequence of actions is as follows:

1. connect joystick to PC — handling `SDL_JOYDEVICEADDED`,
2. press any button — handling `SDL_JOYBATTERYUPDATED`,
3. disconnect joystick from PC — handling `SDL_JOYDEVICEREMOVED`,
4. back to 1. and repeat the sequence.

Repeating this sequence several times produces strange logs in the console:

```
00  00:00:07.958  INFO     Gamepad "0" connected.
00  00:00:08.110  INFO     Gamepad "0" initialized successfully: "Xbox 360 Controller" (0x2249BAF5D80AB67F), buttons: 11, hats: 1, axes: 6, sticks: 2.
00  00:03:09.570  INFO     Gamepad "0" changed power level to "wired".
00  00:05:08.605  INFO     Gamepad "0" named "Xbox 360 Controller" (0x2249BAF5D80AB67F) disconnected.

00  00:11:41.502  INFO     Gamepad "0" connected.
00  00:11:41.531  INFO     Gamepad "0" initialized successfully: "Xbox 360 Controller" (0x2249BAF5D80AB67F), buttons: 11, hats: 1, axes: 6, sticks: 2.
00  00:11:44.862  INFO     Gamepad "1" changed power level to "wired".
00  00:11:47.262  INFO     Gamepad "0" named "Xbox 360 Controller" (0x2249BAF5D80AB67F) disconnected.

00  00:11:51.187  INFO     Gamepad "0" connected.
00  00:11:51.193  INFO     Gamepad "0" initialized successfully: "Xbox 360 Controller" (0x2249BAF5D80AB67F), buttons: 11, hats: 1, axes: 6, sticks: 2.
00  00:12:04.463  INFO     Gamepad "0" named "Xbox 360 Controller" (0x2249BAF5D80AB67F) disconnected.

00  00:12:09.756  INFO     Gamepad "0" connected.
00  00:12:09.759  INFO     Gamepad "0" initialized successfully: "Xbox 360 Controller" (0x2249BAF5D80AB67F), buttons: 11, hats: 1, axes: 6, sticks: 2.
00  00:12:11.446  INFO     Gamepad "3" changed power level to "wired".
00  00:12:15.266  INFO     Gamepad "0" named "Xbox 360 Controller" (0x2249BAF5D80AB67F) disconnected.

00  00:12:18.046  INFO     Gamepad "0" connected.
00  00:12:18.050  INFO     Gamepad "0" initialized successfully: "Xbox 360 Controller" (0x2249BAF5D80AB67F), buttons: 11, hats: 1, axes: 6, sticks: 2.
00  00:12:26.333  INFO     Gamepad "0" named "Xbox 360 Controller" (0x2249BAF5D80AB67F) disconnected.

00  00:12:29.863  INFO     Gamepad "0" connected.
00  00:12:29.866  INFO     Gamepad "0" initialized successfully: "Xbox 360 Controller" (0x2249BAF5D80AB67F), buttons: 11, hats: 1, axes: 6, sticks: 2.
00  00:12:31.646  INFO     Gamepad "5" changed power level to "wired".
00  00:12:34.696  INFO     Gamepad "0" named "Xbox 360 Controller" (0x2249BAF5D80AB67F) disconnected.
```
As you can see, the events `SDL_JOYDEVICEADDED` and `SDL_JOYDEVICEREMOVED` always contain an ID of `0`, no matter how many times I connect and disconnect the joystick.

However, as the joystick is connected and disconnected, the ID provided in the `SDL_JOYBATTERYUPDATED` event is incremented and only the first time it is `0`. Secondly, this event is not always generated — when I connect a joystick and press anything, sometimes SDL generates this event and other times it doesn't (even if I press the buttons more than once, it doesn't appear anyway).

Are you sure `event.jbattery.which` is providing the correct joystick instance ID?

**Comment by meyraud705** [comment]
In SDL2, joysticks have an index  and an instance ID. `SDL_JOYDEVICEADDED` gives you the index and all other joystick events give you the instance ID.

The value of `which` is correct for `SDL_JOYBATTERYUPDATED` but is wrong for `SDL_JOYDEVICEREMOVED`. They should be the same.

> Secondly, this event is not always generated

If the initial state of the battery is unknown, no event is sent.

**Comment by furious-programming** [comment]
So it looks like the `SDL_JOYDEVICEREMOVED` event provides wrong data — device index instead of joystick instance ID. Houston, we have a problem!

> *If the initial state of the battery is unknown, no event is sent.*

Yes, and in the case of my controller, the initial battery status is always unknown. The state of the battery is determined only when using a joystick for the first time (e.g. after pressing a button, D-Pad, etc.). This is expected behavior, but not the problem.

The problem is that when I freshly connect the controller to the PC and press something, SDL sometimes generates the `SDL_JOYBATTERYUPDATED` event and other times it doesn't (see the logs I've pasted).

- 1st connection, button press — event is generated,
- 2rd connection, button press — **event is not generated**,
- 3th connection, button press — event is generated,
- 4th connection, button press — **event is not generated**,
- 5th connection, button press — event is generated,
- 6th connection, button press — **event is not generated** ...

and such a pattern cuntinues — each even joystick connection has no `SDL_JOUBATTERYUPDATED` event generated, after pressing something right after connection. I don't know if this is an SDL problem, but the problem clearly exists and is reproducible.

**Comment by meyraud705** [comment]
I did some test and the `SDL_JOYDEVICEREMOVED` works fine for me.

For the battery event:
 - Xbox 360 controller: got event every other hotplug, if another controller is connected I always get an event
 - XBox One controller: often got event if already plugged in, no event at hotplug

**Comment by furious-programming** [comment]
My controller is **8bitdo SN30 Pro** (wired version).

**Comment by slouken** [comment]
Can you show us your code handling `SDL_JOYDEVICEREMOVED`? I looked through the code and I don't see anywhere it's possible for the removed event to have an ID of 0.

**Comment by furious-programming** [comment]
Here is the function from the gamepad manager, which handles gamepad-related events:

```pascal
procedure Game_GamepadsUpdate(AEvent: PSDL_Event);
var
  Gamepad:      PGame_Gamepad;
  GamepadIndex: TGame_SInt32;
begin
  case AEvent^.Type_ of

    // The gamepad was connected to the computer.
    SDL_JOYDEVICEADDED:
    begin
      GamepadIndex := AEvent^.JDevice.Which;
      Game_LogInfo(['Gamepad "', GamepadIndex, '" connected.']);

      // Try to create gamepad object and only add it to the list if it has been properly created.
      Gamepad := Game_GamepadCreate(GamepadIndex);

      // If the joystick fails to open, do not add anything to the list, otherwise append the devices list.
      if Gamepad <> nil then
        Game_ListPtrAppend(Gamepads, Gamepad);
    end;

    // Gamepad has been disconnected from the computer.
    SDL_JOYDEVICEREMOVED:
      // Find the object of the disconnected gamepad and remove it from the list.
      for GamepadIndex := 0 to Game_ListPtrGetSize(Gamepads) - 1 do
      begin
        Gamepad := Game_ListPtrGetData(Gamepads, GamepadIndex);

        // The event provides the joystick instance ID, so compare them.
        if AEvent^.JDevice.Which = Game_GamepadGetInstanceID(Gamepad) then
        begin
          // Log data about the disconnected gamepad.
          Game_LogInfo(['Gamepad "', GamepadIndex, '" named "', Game_GamepadGetName(Gamepad), '" (', TGame_Pointer(Game_GamepadGetChecksum(Gamepad)), ') disconnected.']);

          // Release the gamepad object and delete it from the device list.
          Game_ListPtrDelete(Gamepads, GamepadIndex, @Game_GamepadDestroy);
          exit;
        end;
      end;

    // Battery status has changed or the way the device is powered.
    SDL_JOYBATTERYUPDATED:
      // Find a gamepad that has changed power status and update it.
      for GamepadIndex := 0 to Game_ListPtrGetSize(Gamepads) - 1 do
      begin
        Gamepad := Game_ListPtrGetData(Gamepads, GamepadIndex);

        // The event provides the joystick instance ID in a dedicated structure ("JBattery" instead of "JDevice").
        if AEvent^.JBattery.Which = Game_GamepadGetInstanceID(Gamepad) then
        begin
          // Pass the event to the update function and exit.
          Game_GamepadUpdate(Gamepad, AEvent);
          exit;
        end;
      end;

    {...}
end;
```
- `SDL_JOYDEVICEADDED` — uses joystick index to create gamepad object,
- `SDL_JOYDEVICEREMOVED` — uses joystick instance ID to find and remove gamepad object from the list.
- `SDL_JOYBATTERYUPDATED` — uses joystick instance ID to find and update gamepad object.

Here is the `Game_GamepadUpdate` function, which updates specified gamepad object:

```pascal
procedure Game_GamepadUpdate(AGamepad: PGame_Gamepad; AEvent: PSDL_Event);
var
  Manipulator: PGame_State;
begin
  case AEvent^.Type_ of
    // Battery status has changed or the way the controller is powered.
    SDL_JOYBATTERYUPDATED:
    begin
      Game_StateAccumulate(AGamepad^.Power, @AEvent^.JBattery.Level);
      Game_LogInfo(['Gamepad "', AEvent^.JBattery.Which, '" changed power level to "', Game_GamepadPowerToString(AEvent^.JBattery.Level), '".']);
    end;

    {...}
end;
```
Data from both of these functions are visible in the logs (from calls to the `Game_LogInfo` function).

**Comment by slouken** [comment]
Okay, this makes sense.

When you're logging `SDL_JOYDEVICEADDED`, you log the event `which` member, which in SDL 2.0 is the index and SDL 3.0 is the instance ID.
When you're logging `SDL_JOYDEVICEREMOVED`, you log `GamepadIndex`, which will also be 0 for the first connected gamepad.
When you're logging `SDL_JOYBATTERYUPDATED`, you log the event `which` member, which will be the joystick instance ID.

So the logging is explained, and I think the only remaining issue is why sometimes you get a battery event, and sometimes you don't. This depends on the driver, which we can tell from the GUID of the controller. Can you post what the joystick GUID is for your Xbox 360 and Xbox One controllers?

**Comment by slouken** [comment]
The issue that was first reported is fixed, so I'm going to go ahead and close this. If you're concerned about the battery status update, feel free to open a separate one for that.
