### ISSUE TITLE
DualShock 4 cannot be used outside AntimicroX if it is connected via USB

### ISSUE THREAD

**Issue by maxigaz** [libsdl-org/SDL#7503]
While my DualShock 4 is connected via USB, AntimicroX grabs the controller so other applications and games can't use it.

For example, the following works only if the game controller is connected via Bluetooth or AntimicroX is not running in the background:

- Controlling the system's mouse cursor with the controller's touchpad
- Querying the controller's battery level with cat `/sys/class/power_supply/ps-controller-battery-*/capacity`
- Navigating the menu in RetroArch

I've tested both the [AppImage](https://github.com/AntiMicroX/antimicrox/releases/download/3.3.3/AntiMicroX-x86_64.AppImage) version of AntimicroX and the one installed from the [AUR](https://aur.archlinux.org/packages/antimicrox),  with the default settings and no custom mappings. The former bundles SDL 2.24.2 while the latter uses what is installed system-wise, i.e. SDL 2.26.4. I can reproduce the issue only with the AUR package.

I have reported the issue on the AntimicroX bug tracker [here](https://github.com/AntiMicroX/antimicrox/issues/746), and the project maintainer believes that the issue lies at the root of SDL.

## System Information

- OS: Arch Linux
- Kernel version: 6.2.6
- Gamepad driver: hid-playstation
- SDL 2.26.4
- AntimicroX 3.3.3

**Comment by slouken** [comment]
It sounds like the one installed from AUR is built with libusb support, which takes exclusive access to the device, and is disabled by default. If you remove that and build SDL from source, do you have the same problem?

**Comment by maxigaz** [comment]
I'm not sure I fully understand. Could you be more specific on what I should remove exactly?

I'm looking at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=antimicrox) of AntimicroX at the moment. Do you mean removing one of the lines with the cmake flags?

In the meantime, I have managed to compile SDL from source. (I cloned `https://github.com/libsdl-org/SDL.git`.)

**Comment by zturtleman** [comment]
The ArchLinux sdl2 [PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/sdl2/trunk/PKGBUILD#L26) uses cmake `-D SDL_HIDAPI_LIBUSB=ON`. This could be removed to allow multiple programs to access the PS4 controller. An [ArchLinux issue](https://bugs.archlinux.org/task/75827) shows the reason for enabling libusb was to support the USB GameCube controller adapter. This conflict of interest is tracked in #6005 for whatever it's worth.

**Comment by maxigaz** [comment]
Thank you for the detailed explanation! I have just tried building sdl2 with the modified PKGBUILD, and I can confirm that removing the line with `-D SDL_HIDAPI_LIBUSB=ON` on it fixes the issue with the PS4 controller and AntimicroX.

Does omitting this flag break other controllers beside the Gamecube Controller? If it does, then I guess it is reasonable to keep it as it is, considering that fewer people might have the exact same issue as mine.

**Comment by slouken** [comment]
I'm going to go ahead and work on https://github.com/libsdl-org/SDL/issues/6005 soon, thanks for the confirmation!

**Comment by maxigaz** [comment]
I've just discovered a disadvantage to omitting `-D SDL_HIDAPI_LIBUSB=ON` from the PKGBUILD of sdl2: AntimicroX can't detect the accelerometer and the gyro of my DualShock 4. Here is a screenshot of its main window:

![antimicrox-sdl2-libusb-off-2023-04-03_12-04-33](https://user-images.githubusercontent.com/10419911/229479110-c5f1b940-2b94-4865-a715-8eadcac53007.png)

However, if I use the original sdl2 package (i.e. the one that is compiled with the flag  `-D SDL_HIDAPI_LIBUSB=ON`), the main window now shows mapping options for the accelerometer and gyro:

![antimicrox-sdl2-libusb-on-2023-04-03_12-02-37](https://user-images.githubusercontent.com/10419911/229479784-dcb520ff-294d-4868-acb1-c1a6d711dc4d.png)

I don't have any games that natively support motion sensors to test, but I assume disabling libusb may cause issues with them, too.
