### ISSUE TITLE
Why is SDL_CreateWindowInternal() decided to not be visible to a client side?

### ISSUE THREAD

**Issue by P3RK4N** [libsdl-org/SDL#7506]
As the title says. ImGui's SDL3 backend is not compatible with this anymore. It would be great if client could keep more fine grained control over window creation

**Comment by slouken** [comment]
SDL_CreateWindowInternal() was never public. The recommended way to create windows with a position is to create the window hidden, set the window position, then show the window. Feel free to post more details if there's a use case that is no longer possible.

**Comment by P3RK4N** [comment]
My bad, I just discovered that SDL_SetWindowPosition exists.
