### ISSUE TITLE
High-resolution Rumble API

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#7509]
This could be folded into #4464, but still worth writing down.

We currently support rumble as well as "effects" (mostly DualSense effects), but despite supporting numerous devices with high-resolution haptic support (Steam controllers and Switch controllers are the big ones) we don't really have a good API to send high-resolution haptic data. This would probably need a feature query similar to LED support; as for actually _sending_ HD rumble data I guess it just depends on what kind of data the devices like to receive from hidapi...?

Ref https://github.com/TerryCavanagh/VVVVVV/pull/954

**Comment by slouken** [comment]
Yeah, I think the problem here is there isn't a uniform way to represent the haptic data. I'm open to suggestions, but I'll go ahead and close this for now.

**Comment by isXander** [comment]
Are HD haptics not just audio streams? Couldn't it be as simple as exposing an AudioStream from a gamepad that the user can then stream into? This AudioStream would be configured by the driver to be in the correct format for the specific gamepad. E.g. DualSense stereo -> channels 3 & 4.

Relates to #9197
