### ISSUE TITLE
[Intel C++] error : undefined symbol: __declspec(dllimport) ldexp

### ISSUE THREAD

**Issue by icls1337** [libsdl-org/SDL#7510]
I used cmake to generate SLN, adding the compile command /Qmsse3 /Qfreestanding.
Version:2.26.4
Output:
3>lld-link: : error : undefined symbol: __declspec(dllimport) ldexp
3>>>> referenced by SDL2.dir\Release\SDL.obj:(ldexpf)
3>>>> referenced by SDL2.dir\Release\SDL_assert.obj
3>>>> referenced by SDL2.dir\Release\SDL_dataqueue.obj

**Comment by madebr** [comment]
While working on getting SDL building with the Intel compilers, I have not encountered this issue. See #7250 for my fixes for SDL2.
I tested with [this 2023.0.0 toolchain](https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#dpcpp-cpp).

I did all my tests with the Ninja generator (`-GNinja`).

Can you try again with a fresh build tree, and provide more information about what exact toolchain + arguments you've used.

**Comment by madebr** [comment]
This has now been merged.
Please comment here or create a new issue if you run into broken things.
Thanks!
