### ISSUE TITLE
"Could not make GL context current: BadMatch (invalid parameter attributes)"

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#7511]
SDL3 main branch report **"BadMatch (invalid parameter attributes)" in Linux x11**, commit **"4dededd34"** is ok, It seems caused by "SDL_WINDOW_TRANSPARENT" feature.

Basically I create an invisible window, just to initialize an opengl context, then I create my actual render windows (compatiable with window which created context), then I use `SDL_GL_MakeCurrent` to switch render window between multiple windows.

**Comment by 1bsyl** [comment]
so this is the transparent commit: https://github.com/libsdl-org/SDL/commit/2cafa525981b1ec2fe25ced632221d639ec11f96

A quick look on x11 diff, it seems all is checked with "if (transparent) {" so if you don't use SDL_WINDOW_TRANSPARENT .. it shouldn't change the behavior.

is it x11 with GLX, or x11 with EGL ? 

maybe you can submit a testcase

**Comment by sandsc** [comment]
It's x11 with GLX, here is the test case, I am using SDL with Qt 5.15.2, here is the testcase, another issue in this case is SDL don't report any event when integrated with qt in X11 system.
```
 while (SDL_PollEvent(&event))
    {
        // NO events report on linux!!
         SDL_LogInfo(SDL_LOG_CATEGORY_VIDEO, "Receive SDL event %d", event.type);
        if (event.type == SDL_EVENT_QUIT)
        {
            break;
        }
    }
```
[QtWidgetsTest.zip](https://github.com/libsdl-org/SDL/files/11027952/QtWidgetsTest.zip)

**Comment by 1bsyl** [comment]
I've tried and I see : a white window with border, + an "open" button. and log 
```
INFO: Receive SDL event 514
INFO: Receive SDL event 519
INFO: Receive SDL event 517
INFO: Receive SDL event 516
INFO: Receive SDL event 525
INFO: Receive SDL event 528
INFO: Receive SDL event 770
INFO: Receive SDL event 526
INFO: Receive SDL event 770
INFO: Receive SDL event 770
INFO: Receive SDL event 770
INFO: Receive SDL event 770
INFO: Receive SDL event 770
```
same with head, transparent and before .
what should be seen ?

**Comment by madebr** [comment]
I always see this error when using the x11 video driver (`SDL_VIDEO_DRIVER=x11`):
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x4
  Serial number of failed request:  181
  Current serial number in output stream:  206
```

**Comment by sandsc** [comment]
> 
On my machine, it continue reporting **DEBUG: Could not make GL context current: GLXBadContextTag** in this code:
` SDL_GL_MakeCurrent(m_window, m_context.context);`
Another issue is that it can't receive any mouse input events in Linux x11, e.g SDL_EVENT_MOUSE_MOTION, it's all ok on Windows.

**Comment by 1bsyl** [comment]
@sandsc I don't know what should be expected with SDL+Qt
maybe you need the Qt listener for mouse events 


about the first GL issue. can you double check the good & bad commit just to make sure.
then, fetch the bad commit (eg SDL_TRANSPARENT_WINDOW), and comment out the new stuff.
to see where that fails.
there are lots of file modified, but most are not relevant (test, other platform), in the end, that's really not much code to touch.

**Comment by 1bsyl** [comment]
@madebr why do you have to set SDL_VIDEO_DRIVER=x11  before ? 
( is this x11 over wayland, maybe ? )

**Comment by madebr** [comment]
> @madebr why do you have to set SDL_VIDEO_DRIVER=x11 before ? ( is this x11 over wayland, maybe ? )

With the wayland video driver, the qt window showed without issues.
I've read qt5 is very x11-centric, and has poor wayland support. So I assumed the error lies in the interaction between qt and SDL.
qt6 has a much improved wayland backend. But that's all I know.

**Comment by 1bsyl** [comment]
I tried, and get the same result with wayland.

@madebr how to you test wayland or x11 ? 
```
SDL_VIDEO_DRIVER=x11 ./a.out
SDL_VIDEO_DRIVER=wayland ./a.out
```
like this on the same session ?

**Comment by sandsc** [comment]
I' using git bisect 75da730a8 4dededd34, finally found the bad commit:
**
5da9e99da076dae56a4fbee31c774932d9928296 is the first bad commit
commit 5da9e99da076dae56a4fbee31c774932d9928296
Author: Sylvain <sylvain.becker@gmail.com>
Date:   Thu Mar 16 20:30:56 2023 +0100

    Fixed bug #7462 - 8888 as default GL backbuffer red/green/blue/alpha bit sizes

 src/test/SDL_test_common.c | 8 ++++----
 src/video/SDL_video.c      | 8 ++++----
 2 files changed, 8 insertions(+), 8 deletions(-)
**

**Comment by 1bsyl** [comment]
@sandsc ok so that's different.
you can try to set them 
SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 3);
SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 3);
SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 2);
SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 0);

after SDL_Init, and before SDL_CreateWindow

**Comment by sandsc** [comment]
> 

That solved my problem, thank you very much!  Why these default values affect creation of window or context. After all, these values are set before the context or window is created.

**Comment by slime73** [comment]
Can you find some info about your GPU and supported pixel formats on it? I'm not too familiar with Linux / X11 but I wonder if the `glxinfo` tool will have anything relevant.

**Comment by sandsc** [comment]
8880 is ok, I think `SDL_GL_ALPHA_SIZE` default value is 8 causes the problem. My graphic card is Nvidia Quadro P2200, OpenGL version 4.6.0 NVIDIA 525.89.02.
some glxinfo:

```
visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x021 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  8 16 16 16 16  0 0 None
0x022 24 dc  0  24  0 r  y .   8  8  8  0 .  s  4 24  8 16 16 16 16  0 0 None
0x024 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4 24  8 16 16 16 16  0 0 None
0x025 24 tc  0  24  0 r  . .   8  8  8  0 .  s  4 24  8 16 16 16 16  0 0 None
0x026 24 tc  0  32  0 r  . .   8  8  8  8 .  s  4 24  8 16 16 16 16  0 0 None
0x027 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  0 16 16 16 16  0 0 None
0x028 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4 24  0 16 16 16 16  0 0 None
0x029 24 tc  0  24  0 r  . .   8  8  8  0 .  s  4 24  0 16 16 16 16  0 0 None
0x02a 24 tc  0  32  0 r  . .   8  8  8  8 .  s  4 24  0 16 16 16 16  0 0 None
0x02b 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4  0  0 16 16 16 16  0 0 None
0x02c 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4  0  0 16 16 16 16  0 0 None
0x02d 24 tc  0  24  0 r  . .   8  8  8  0 .  s  4  0  0 16 16 16 16  0 0 None
0x02e 24 tc  0  32  0 r  . .   8  8  8  8 .  s  4  0  0 16 16 16 16  0 0 None
0x02f 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  0 16 16 16 16  2 1 None
0x030 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4 24  0 16 16 16 16  2 1 None
0x031 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  0 16 16 16 16  4 1 None
0x032 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4 24  0 16 16 16 16  4 1 None
0x033 24 tc  0  24  0 r  . .   8  8  8  0 .  s  4 24  0 16 16 16 16  2 1 None
0x034 24 tc  0  32  0 r  . .   8  8  8  8 .  s  4 24  0 16 16 16 16  2 1 None
0x035 24 tc  0  24  0 r  . .   8  8  8  0 .  s  4 24  0 16 16 16 16  4 1 None
0x036 24 tc  0  32  0 r  . .   8  8  8  8 .  s  4 24  0 16 16 16 16  4 1 None
0x037 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  8 16 16 16 16  2 1 None
0x038 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4 24  8 16 16 16 16  2 1 None
0x039 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  8 16 16 16 16  4 1 None
0x03a 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4 24  8 16 16 16 16  4 1 None
0x03b 24 tc  0  24  0 r  . .   8  8  8  0 .  s  4 24  8 16 16 16 16  2 1 None
0x03c 24 tc  0  32  0 r  . .   8  8  8  8 .  s  4 24  8 16 16 16 16  2 1 None
0x03d 24 tc  0  24  0 r  . .   8  8  8  0 .  s  4 24  8 16 16 16 16  4 1 None
0x03e 24 tc  0  32  0 r  . .   8  8  8  8 .  s  4 24  8 16 16 16 16  4 1 None
0x03f 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  0 16 16 16 16  8 1 None
0x040 24 tc  0  32  0 r  y .   8  8  8  8 .  s  4 24  0 16 16 16 16  8 1 None
```

**Comment by slime73** [comment]
Interesting that there are a bunch of 8/8/8/8 pixel formats but they don't work for you - I wonder if something else is causing a conflict or is missing that'd make it work.

We could go with the original suggestion before of defaulting to 8/8/8/0 when window transparency isn't used (https://github.com/libsdl-org/SDL/issues/7462#issuecomment-1472226343) even with its downsides, but I suspect there might be something else to fix instead, and not investigating that might leave window transparency broken on some systems.

**Comment by 1bsyl** [comment]
maybe it conflicst with SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);  ?

**Comment by 1bsyl** [comment]
or others:
```
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
QtWidgetsTest.cpp:    flags |= SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG;
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, flags);
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 1);
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 0);
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 4);
QtWidgetsTest.cpp:    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 5);
```

**Comment by sandsc** [comment]
Hi, guys, any suggestions for this issue, In this case, can I only use the Qt framework's event system instead of getting events from SDL?
>Another issue is that it can't receive any mouse input events in Linux x11, e.g SDL_EVENT_MOUSE_MOTION. it's all ok on win32 platform. I'm sorry that I'm not very familiar with x11lib development. When I debug into sdl source code, found that following function in SDL/src/video/x11/SDL_x11events.c:
static SDL_bool X11_PollEvent(Display *display, XEvent *event)
{
    if (!X11_XCheckIfEvent(display, event, isAnyEvent, NULL)) {
        return SDL_FALSE;
    }
    return SDL_TRUE;
}
X11_XCheckIfEvent always return false, could it be that Qt's event loop processes and removes all XEvents from the event queue, making it impossible for SDL to fetch XEvent here, If this is the case, how to handle SDL_Events in Qt?

**Comment by 1bsyl** [comment]
https://tronche.com/gui/x/xlib/event-handling/manipulating-event-queue/XCheckIfEvent.html
this means it find no events, maybe because Qt has already processed them

**Comment by sandsc** [comment]
> ok, I give a try, and you need to create the window with a valid size.
> then the window is created (not sure why, but outside),

It's only can has events over the dummy window, which in my case, it's hidden dummy window used to create context, I still can't gets events on window created from Qt widget by using `SDL_CreateWindowFrom`, however events can be received on Win32 platform. This inconsistent API behavior on different platforms may need to be documented.

**Comment by 1bsyl** [comment]
yes, inconsistency is bad :/
I have never use the SDL_CreateWindowFrom so I don't know what should really be expected..

reading this:
https://stackoverflow.com/questions/36311439/handle-x11-events-with-qt5 
do you have the possibility to re-run with Qt4 and see if the behavior is different ?

there is this thead https://www.qtcentre.org/threads/23459-Getting-system-wide-X11-events-problems
that suggest to move "XSelectInput" (eg SDL_CreateWindow()) after the show() method, but that doesn't seem to work..

**Comment by slime73** [comment]
> maybe it conflicst with SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24); ?

The depth buffer associated with the backbuffer generally isn't dependent on the backbuffer's color pixel format, so it'd be very surprising if that's what's causing the issue.

It'll probably be pretty hard to narrow it down without someone debugging or figuring out working vs non-working GL setup combinations on the affected machine.
