### ISSUE TITLE
Remaining intrinsics work:

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#7512]
Left over stuff after https://github.com/libsdl-org/SDL/pull/7490 :

- [ ] Cmake SIMD feature tests use `-mXXX` switches, the build itself doesn't:
  https://github.com/libsdl-org/SDL/pull/7490#issuecomment-1477428226
  Not a real show-stopper, but the cmake detection can be a lie: clang-cl
  is a good example.
- [x] RDTSC option can probably go away and be made into a macro:
  https://github.com/libsdl-org/SDL/pull/7490#pullrequestreview-1350050161
  - Done with https://github.com/libsdl-org/SDL/pull/7516
- [x] Intel compiler hanling: It seems to support target attributes, but
  I don't know since which version:
  https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/attributes.html
  - Done with https://github.com/libsdl-org/SDL/pull/7516
- [ ] Handling ARM / NEON intrinsics similarly:
  Don't know how to handle.
- [ ] Handling PowerPC ALTIVEC similarly:
  Don't know how to handle.
- [ ] Handling LSX and LASX intrinsics similarly:
  Don't know how to handle (I don't even know where to find those two
  `lsxintrin.h` and `lasxintrin.h` headers.)

**Comment by sezero** [comment]
@madebr: About `rdtsc`: 

As of gcc-4.5.x, `__rdtsc()` is available from `x86intrin.h` (which
includes `ia32intrin.h`), and `_rdtsc()` has always been defined as
`__rdtsc`. See:
https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/config/i386/ia32intrin.h;hb=HEAD#l313

As of clang-3.5: same behavior as gcc.
Clang as of 4.0, however, made `__rdtsc()` simply a builtin function,
ia32intrin.h (included by x86intrin.h as usual) still defines `_rdtsc`
as `__rdtsc` as it used to.

I.e.: Neither of gcc or clang actually need immintrin.h for rdtsc but
only `x86intrin.h`, as of above-mentioned versions which go much older
than what we expect in current SDL_intrin.h.

**Comment by icculus** [comment]
> Handling ARM / NEON intrinsics similarly:
> Don't know how to handle.
> Handling PowerPC ALTIVEC similarly:
> Don't know how to handle.

Does this just need something like `SDL_TARGETING("altivec")` or is it more complicated than that?

**Comment by sezero** [comment]
> > Handling ARM / NEON intrinsics similarly:
> > Don't know how to handle.
> > Handling PowerPC ALTIVEC similarly:
> > Don't know how to handle.
> 
> Does this just need something like `SDL_TARGETING("altivec")` or is it more complicated than that?

Don't really know whether the target attributes work for those targets, hence the "don't know how to handle" notes

**Comment by slouken** [comment]
We are scoping work for the SDL 3.2.0 release, so please let us know if this is a showstopper for you.

**Comment by madebr** [comment]
I think this is done.
Ok to close @sezero?

**Comment by sezero** [comment]
> I think this is done. Ok to close @sezero?

Yup. We can change things as we go if needed, later.
