### ISSUE TITLE
[iOS] MessageBox not show up when using SDL_iPhoneSetAnimationCallback

### ISSUE THREAD

**Issue by 0x4d696e68** [libsdl-org/SDL#7513]
It blocks the thread, but messageboxs are not showing

**Comment by slouken** [comment]
Do you have a simple repro case?

**Comment by slouken** [comment]
I haven't heard any response, and don't have any way to repro this, so I'm going to go ahead and close it. Please feel free to reopen this if you still have this problem and have a repro case.
