### ISSUE TITLE
SDL3 SDL_QueryTexture is not directly compatible with SDL_FRect

### ISSUE THREAD

**Issue by panreyes** [libsdl-org/SDL#7519]
Because of recent changes related to SDL3's to improve support for HDPI displays, SDL_QueryTexture now requires a different type of structure (SDL_Rect) than SDL_RenderTextureRotated (SDL_FRect).

I can solve it like this:
```
SDL_FRect dstRect;
SDL_Rect dstRectTex;
[...]
SDL_QueryTexture(texture, NULL, NULL, &dstRectTex.w, &dstRectTex.h);
dstRect.x = (float)dstRectTex.x;
dstRect.y = (float)dstRectTex.y;
SDL_RenderTextureRotated(renderer, piece->texture, NULL, &dstRect, 0., NULL, flip);
```
But it might be a good idea having SDL_QueryTexture and SDL_FQueryTexture to make it easier for the users.

It might probably related to SDL3 still being in its early stages, but I mention it just in case :)

**Comment by slouken** [comment]
A similar argument can be made for the viewport functions.

**Comment by slouken** [comment]
I'll take a quick look at this and see how changing the API would affect things.
