### ISSUE TITLE
SDL_hidapi_steam: build failure on c2x

### ISSUE THREAD

**Issue by FtZPetruska** [libsdl-org/SDL#7522]
Trying to build SDL3 using LLVM 15/16 and `-std=c2x` fails with the following error:

```
[141/381] Building C object CMakeFiles/SDL3-shared.dir/src/joystick/hidapi/SDL_hidapi_steam.c.o
FAILED: CMakeFiles/SDL3-shared.dir/src/joystick/hidapi/SDL_hidapi_steam.c.o 
/opt/homebrew/opt/llvm/bin/clang -DSDL3_shared_EXPORTS -DSDL_BUILD_MAJOR_VERSION=3 -DSDL_BUILD_MICRO_VERSION=0 -DSDL_BUILD_MINOR_VERSION=0 -DUSING_GENERATED_CONFIG_H -I/SDL/build/include-config-release -I/SDL/src -I/SDL/build/include -I/SDL/include -I/SDL/include/SDL3 -std=c2x -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -fvisibility=hidden -Wno-error=deprecated-declarations -D_THREAD_SAFE -fobjc-arc -idirafter /SDL/src/video/khronos -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wdocumentation -Wdocumentation-unknown-command -fcomment-block-commands=threadsafety -Wshadow -fcolor-diagnostics -Winvalid-pch -Xarch_arm64 -include/SDL/build/CMakeFiles/SDL3-shared.dir/cmake_pch_arm64.h -MD -MT CMakeFiles/SDL3-shared.dir/src/joystick/hidapi/SDL_hidapi_steam.c.o -MF CMakeFiles/SDL3-shared.dir/src/joystick/hidapi/SDL_hidapi_steam.c.o.d -o CMakeFiles/SDL3-shared.dir/src/joystick/hidapi/SDL_hidapi_steam.c.o -c /SDL/src/joystick/hidapi/SDL_hidapi_steam.c
/SDL/src/joystick/hidapi/SDL_hidapi_steam.c:36:5: error: expected identifier
    false,
    ^
/SDL/src/joystick/hidapi/SDL_hidapi_steam.c:37:5: error: expected identifier
    true
    ^
/SDL/src/joystick/hidapi/SDL_hidapi_steam.c:38:2: error: expected ';' after enum
} bool;
 ^
 ;
/SDL/src/joystick/hidapi/SDL_hidapi_steam.c:34:1: warning: typedef requires a name [-Wmissing-declarations]
typedef enum
^~~~~~~
/SDL/src/joystick/hidapi/SDL_hidapi_steam.c:38:3: warning: declaration does not declare anything [-Wmissing-declarations]
} bool;
  ^~~~
```

It seems to be related to the enum in `src/joystick/hidapi/SDL_hidapi_steam.c`:

```c
typedef enum {
  false,
  true
} bool;
```

C23 make `true` and `false` keywords, which is implemented in LLVM Clang since version 15.
Unfortunately, I do not see any feature check that we could use for falling back to the enum. I will see about using `check_c_source_compiles` to test for that.

---

This affects:
- main branch @ 586004e52a7bb81ab970e58804620dec4e3b1d70
- SDL2 branch @ b57a6a1adf15f9a6e4a48e1980aa723d47fa2fe3
- release-2.26.x branch @ 24098b75b10ec827d517715d0fb963b0bcce7c3c

**Comment by madebr** [comment]
Can a comparison with `__STDC_VERSION__` be used?

**Comment by FtZPetruska** [comment]
> Can a comparison with `__STDC_VERSION__` be used?

It does seem like it, LLVM 15 and 16 have that feature while LLVM 14 does not, but they all set `__STDC_VERSION__` to the same value (`202000`).

It seems that testing the feature in CMake can be done as such:
```cmake
check_c_source_compiles("
int main() {
  bool foo = false || true;
}" HAS_C23_BOOL_KEYWORDS)
```
The check fails on `-std=c17` and below even when the feature is supported, and succeeds on `-std=c2x` only when the feature is available.

Would you like me to open a PR with a patch?

**Comment by FtZPetruska** [comment]
> I'm hesitant to let CMake handle this, because the Android, xcode and VC scripts will then start failing in the future.

I hear your concern, I had not thought about that.

> Can't we just use SDL types, and do e.g. the following?
> 
> ```c
> #define bool SDL_bool
> #define false SDL_FALSE
> #define true SDL_TRUE
> ```

Replacing the enum with this seems to work perfectly!

> Btw, that source file is already full of SDL'isms.
> Is there a reason SDL data types are not used?

I am honestly not sure, this enum seems to be there since the file creation. I wonder if part of that file is some code copied from elsewhere, because the only portion of code that uses bool/true/false:
- redefines macros like `clamp` when there is `SDL_clamp`
- uses stdint.h's `(u)intX_t` types when there is SDL_stdinc.h's `S/UintX` types
- seems to be delimited by two large `/******/` comments on lines 30 and 940, with `SDL_bool` being used after that point
