### ISSUE TITLE
`testautomation --filter surface_testBlitBlendNone` segfaults

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#7523]
Since 69de6964e58d287919048e9ac0da41c206fd80bd, the `surface_testBlitBlendNone` test fails with a segmentation fault.
The error is somewhere in [`SDL_BlitSurface`](https://github.com/libsdl-org/SDL/blob/586004e52a7bb81ab970e58804620dec4e3b1d70/test/testautomation_surface.c#L184).
Building SDL with `-DSDL_MMX=OFF`, makes the test work again.
Building SDL with `-DSDL_MMX=ON -DCMAKE_C_FLAGS="-mmmx -msse -msse2 -msse3 -mavx -mavx2` does NOT fix the crash.

**Comment by madebr** [comment]
Fixed in 749f3ebd1

**Comment by sezero** [comment]
Does SDL2 branch need that patch too? (Haven't tested myself.)

**Comment by sezero** [comment]
> Does SDL2 branch need that patch too? (Haven't tested myself.)

Ah no, it was my screw-up in #7490
