### ISSUE TITLE
Add 8bitDo Ultimate Bluetooth Controller

### ISSUE THREAD

**Issue by Manukineko** [libsdl-org/SDL#7524]
While there is already the Ultimate **Wireless** Controller in SDL_gamepad_db, the 8BitDo Ultimate **Bluetooth** Controller has a slight difference : it follows a "nintendo layout" as it is also compatible with the Nintendo Switch (A = East, B = South, Y = West and X = North) when the Wireless version follow the "Xbox layout".
 
![ultimate-bluetooth-controller](https://user-images.githubusercontent.com/43104858/227396277-346748f7-1d7f-4527-bd6c-cd720f3229bc.png)
*8bitDo Ultimate Bluetooth Controller*

![ultimate-wireless-2 4g-controller](https://user-images.githubusercontent.com/43104858/227396279-6e36a83c-35f9-4e11-8441-5c156d0e79d8.png)
*8BitDo Ultimate Wireless Controller*

Is there something that can be done about that ?

**Comment by CzarnaMamba** [comment]
It works for me.
