### ISSUE TITLE
Should `__IOS__` be prefixed as a platform definition to prevent ambiguity with STL iostreams?

### ISSUE THREAD

**Issue by addiment** [libsdl-org/SDL#7525]
This is a very opinionated idea/nitpick, but I was reading the migration guide and wondered if the platform macro could be confusing. I mean, it's more accurate, but I thought maybe something like `__PLATFORM_IOS__` would be less ambiguous. My main concern is with C++'s STL iostreams using "ios" frequently. Again, this is just an idea.

**Comment by 1bsyl** [comment]
I think that would be a good change to have specific macros to have a uniform convention, centralized ...
( most of time they are tested with def/undef, but sometime they are tested directly..)

**Comment by madebr** [comment]
My vote would be to namespace everything in `SDL_` namespace.
[See this earlier suggestion.](https://github.com/libsdl-org/SDL/issues/7228#issuecomment-1419461456)
How about introducing e.g. `SDL_PLATFORM_<xxx>` macro's in some global header, and always use these in-source? And also do this for subsystems such as gdk etc.

**Comment by slouken** [comment]
> My vote would be to namespace everything in `SDL_` namespace. [See this earlier suggestion.](https://github.com/libsdl-org/SDL/issues/7228#issuecomment-1419461456) How about introducing e.g. `SDL_PLATFORM_<xxx>` macro's in some global header, and always use these in-source? And also do this for subsystems such as gdk etc.

I like this suggestion. The subsystems wouldn't be in public SDL headers, but we could rename the existing platform defines for SDL3.

**Comment by addiment** [comment]
I didn't even think of the namespacing of it- I like that idea.

**Comment by madebr** [comment]
I'm [prototyping this in my fork](https://github.com/madebr/SDL/tree/use-SDL_OS_xxx-macros). It's still wip.
As a first step, I'm modifying `SDL_platform_defines.h` to define `SDL_OS_xxx` and `SDL_PLATFORM_xxx` macro's.

Currently, other include headers depend on these platform macro's:
- `SDL_LinuxSetThreadPriority` and `SDL_LinuxSetThreadPriorityAndPolicy` depend on `SDL_OS_LINUX`,
- `SDL_syswm.h` needs to know what wm's are available on a certain platform,
- `SDL_main.h` needs to know whether `main` needs to be wrapped
- & others, because I have not finished yet

I'm not 100% confident these macro's can be removed from the public headers.

**Comment by slouken** [comment]
The platform macros should be public, the feature macros should be private. What's the difference between OS and PLATFORM macros?

**Comment by madebr** [comment]
> The platform macros should be public, the feature macros should be private. What's the difference between OS and PLATFORM macros?


I was thinking like this:
- `SDL_OS_xxx` stands for an operating system from a specific software creator for a specific (type of) device (haiku, qnx, windows desktop
- `SDL_PLATFORM_xxx` stands for a family of operating systems. e.g. apple, unix, windows (`SDL_PLATFORM_APPLE`, `SDL_PLATFORM_UNIX`, `SDL_PLATFORM_WINDOWS`)

For Windows, you would then have a `SDL_PLATFORM_WINDOWS` for all windows things, but also `SDL_OS_WINDOWS` for the desktop os, `SDL_OS_XBOXONE`, `SDL_OS_WINRT`, `SDL_OS_WINGDK`, ...

With the above convention,`__GDK__` would then turn into `SDL_PLATFORM_GDK`.
https://github.com/libsdl-org/SDL/blob/1f095b9ce65e2b689d12d4c8abb81081eb5e2bb1/include/SDL3/SDL_platform_defines.h#L189-L192

For Apple, you'd then have `SDL_PLATFORM_APPLE` for everything Apple,
and have `SDL_OS_xxx` for every os Apple releases: tvos, ios, macos.

For hardware ports, such as psp and vita, I would only use `SDL_PLATFORM_` prefixes:
`SDL_PLATFORM_PS2`, `SDL_PLATFORM_NGAGE`, `SDL_PLATFORM_VITA`, ...


I'm open to suggestions on alternative naming conventions.
It would be great to avoid opinionated naming convention.

**Comment by madebr** [comment]
Talking about `__MACOS__`, is tvOS also macOS? Or should the `#if TARGET_OS_IPHONE` become `#elif TARGET_OS_IPHONE`?
https://github.com/libsdl-org/SDL/blob/1f095b9ce65e2b689d12d4c8abb81081eb5e2bb1/include/SDL3/SDL_platform_defines.h#L98-L107

**Comment by slouken** [comment]
I'd prefer to match the existing platform definitions, just adding SDL_PLATFORM_ to them. That way existing code can be easily transformed. Once we do that we can potentially create groupings if that really makes sense.

**Comment by slouken** [comment]
> can the convention be to define everything, 0 by default, and 1 when available. So that we don't need "idef" or "defined()" and just "if". the convention seem to have things defined or not, but here for instance, it tests the value: https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L192

No, because these defines are user-facing, and there's lots of application code that does `#ifdef PLATFORM ...`

**Comment by slouken** [comment]
@madebr, how is this coming?

**Comment by slouken** [comment]
Ping?
