### ISSUE TITLE
swrender is broken with wayland

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#7532]
Hello.

This problem is reproducible mostly with
fedora, which applies the following patch:
[SDL2-2.0.22-prefer-wayland.patch.gz](https://github.com/libsdl-org/SDL/files/11068516/SDL2-2.0.22-prefer-wayland.patch.gz)

This patch looks harmless, it only gives
the wayland more priority than to X11.
But after that you'll get broken swrenderer.
To reproduce (after applying the patch above):
```
diff --git a/test/testyuv.c b/test/testyuv.c
index e7373a8b1..d337b73f5 100644
--- a/test/testyuv.c
+++ b/test/testyuv.c
@@ -361,7 +361,8 @@ int main(int argc, char **argv)
         return 4;
     }

-    renderer = SDL_CreateRenderer(window, -1, 0);
+    SDL_SetHint(SDL_HINT_FRAMEBUFFER_ACCELERATION, "0");
+    renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_SOFTWARE);
     if (renderer == NULL) {
         SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Couldn't create renderer: %
s\n", SDL_GetError());
         return 4;
```

Now you'll get this:
```
$ ./testyuv
INFO: 100 iterations in 90 ms, 0.90ms each
ERROR: Couldn't create renderer: Couldn't find matching render driver
```

**Comment by icculus** [comment]
Wayland doesn't have a framebuffer interface afaik. The software renderer should work, but it needs to use OpenGL to get the software rendered pixels to the screen.

Which is to say that the SDL_HINT_FRAMEBUFFER_ACCELERATION line is what's causing this to fail.

I don't think we can do anything about this.

**Comment by stsp** [comment]
Where can I read about limitations of
that approach? My renderer is threaded,
which was a no-go for openGL.
So if a stop disabling fb accel, then
will I be able to create textures from
non-main thread?

**Comment by stsp** [comment]
Also this doesn't fail:
```
      SDL_SetHint(SDL_HINT_RENDER_DRIVER, "software");
      SDL_SetHint(SDL_HINT_FRAMEBUFFER_ACCELERATION, "0");
      int err = SDL_CreateWindowAndRenderer(0, 0, 0, &window, &renderer);
```

What could be the difference?

**Comment by stsp** [comment]
Oh, and probably important is the fact
that Xwayland works fine with sw renderer
and X11 sdl back-end.
If Xwayland works, then certainly there
is some possible implementation?

**Comment by stsp** [comment]
> Which is to say that the SDL_HINT_FRAMEBUFFER_ACCELERATION line is what's causing this to fail.

So here's the real bug then.
I tried this:
```
     renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_SOFTWARE);
     if (renderer == NULL) {
         SDL_SetHint(SDL_HINT_FRAMEBUFFER_ACCELERATION, "1");
         renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_SOFTWARE);
    }
    if (renderer == NULL) {
         SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Couldn't create renderer: %
s\n", SDL_GetError());
         return 4;
    }
```
... and that doesn't work.
It seems, one need to set that hint to "1"
before the FIRST call to SDL_CreateRenderer().
Fall-back doesn't work.
Could you take a look at why that happens?

And on a side-note, when is to expect the
thread-safe API for hw rendering (on top of
vulkan I guess), is it a subject for SDL3, or
missed again?

**Comment by Kontrabant** [comment]
> SDL_HINT_RENDER_DRIVER

The hint is being ignored because 0 is a valid renderer index (corresponding to GL or GLES). The renderer index needs to be a negative value for the renderer hint to be used.

> Oh, and probably important is the fact that Xwayland works fine with sw renderer and X11 sdl back-end. If Xwayland works, then certainly there is some possible implementation?

Framebuffer support could probably be implemented via SHM buffers, but the question is whether it's necessary and worth the effort. Using the software renderer still renders everything via software, it just uses GL/GLES during presentation to send the final software rendered surface to the GPU and draw it to the screen.

Is your application actually broken when using the software renderer with a hardware accelerated framebuffer?

**Comment by stsp** [comment]
> needs to be a negative value for the renderer hint to be used.

What API grants that when using
SDL_CreateWindowAndRenderer()?

> presentation to send the final software rendered surface to the GPU and draw it to the screen.

Does this mean RenderPresent() should be done
from the main thread, or its unrelated to RenderPresent()?

> Is your application actually broken when using the software renderer with a hardware accelerated framebuffer?

I am not actually sure, I think @stefand tested
that scenario.
But if you say its a thread-safe case, then I'll
just use that and will bug-report whatever problem
pops up.

**Comment by stsp** [comment]
The problem is that radeon open=source
driver is very permissive about threading.
Not so much for proprietary nvidia drivers.
So I can't test that on my own.
I'll just take your word on that. :)

**Comment by icculus** [comment]
> And on a side-note, when is to expect the
thread-safe API for hw rendering (on top of
vulkan I guess), is it a subject for SDL3, or
missed again?

The new GPU API will be thread safe, and there will be a 2D backend that uses it, which will solve this for systems with reasonably modern hardware.

**Comment by stsp** [comment]
That's a great news!
Please let me know when there is an
overview to read.
