### ISSUE TITLE
SDL3 gpu-api: consider supporting compute shaders

### ISSUE THREAD

**Issue by aardappel** [libsdl-org/SDL#7537]
I am aware that `SDL_gpu.h` explicitly says they are currently not supported, but wanted to open an issue for discussion, as I feel they are by far the most important feature that is missing.

It is pretty common nowadays for even a pure graphics pipeline to do all its intermediate passes using compute, it is actually cleaner/simpler than the equivalent pixel shader in terms of API (in OpenGL at least), it is of course more powerful (arbitrary reads/writes), and it can also be faster in some cases (we had some computationally heavy shaders passes speed up by as much as 20% when moving from pixel to compute, code unchanged apart from texture access functions).

To some extent, the absolute simplest possible modern graphics API is just a graph of buffers and compute shaders. Some people would go as far as to even remove buffers ;) https://github.com/PetorSFZ/sfz_tech/tree/master/Lib-GpuLib @PetorSFZ though I wouldn't suggest that for SDL :)

The gpu api on the one hand wants to target only modern command-queue APIs, yet it doesn't support compute, in some way that makes the existing code bases that would be a good fit to port to it the empty set: modern graphics pipelines likely use compute somewhere, old-fashioned pipelines would need a lot of work to convert to command-queues. (Sorry, bit of a strawman argument, but an another way to look at it).

I know you value simplicity highly, what exactly about compute shaders would make either the API or the shading language more complicated?

**Comment by icculus** [comment]
@slouken and I have been discussing this recently; we're likely going to add compute before the API is finalized, but there's a lot of related shader work to do before I can add it.

I'll leave this issue open until then.
