### ISSUE TITLE
Wiki-page (SDL2) needs update of the links to the Libraries

### ISSUE THREAD

**Issue by klartext** [libsdl-org/SDL#7540]
I was looking for SDL2-TTF Wiki, found the general SDL2 Wiki here:
https://wiki.libsdl.org/SDL2/FrontPage

Then I looked for the libraries:
  https://wiki.libsdl.org/SDL2/Libraries

The link for SDL2-TTF-wiki is this here: https://wiki.libsdl.org/SDL_ttf

The link did not work, so I opened an issue: https://github.com/libsdl-org/SDL_ttf/issues/270

The answer was: SDL2-TTF has a wiki-page, but the correct link is this one:
https://wiki.libsdl.org/SDL2_ttf/FrontPage

I assume that the changes will be affecting all links to the libraries.

Would be nice to have the correctlinks for the SDL2-Helper-Libs available from the SDL2-Wiki-page.

**Comment by icculus** [comment]
Oh, shoot, I think I promised to fix this so links to `SDL_ttf` would redirect to `SDL2_ttf` (and at some uncertain future date, maybe switch over to `SDL3_ttf`). Either I forgot to fix this or it didn't work, I can't remember.

I'll try to look at this on Monday, sorry for the confusion!

**Comment by slouken** [comment]
@icculus, is this fixed already?

**Comment by icculus** [comment]
Yeah, I fixed this a while ago. All the unversioned pages (SDL_ttf) go to SDL2 equivalents (SDL2_ttf), and at some point we'll flip this to go to SDL3.
