### ISSUE TITLE
SDL_SetRenderLogicalPresentation() / with render_testLogicalSize() fails 

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7544]
usage of SDL_SetRenderLogicalPresentation() fails within render_testLogicalSize()
`./test/testautomation --renderer software --filter render_testLogicalSize` is ok

but
`./test/testautomation --renderer software --filter render_testLogicalSize` fully fails randomly / most of the time.
eg, the 3 image comparaison

What's read with RenderReadPixels is sometime correct, sometime garbage.

**Comment by slouken** [comment]
I think this is fixed now...
