### ISSUE TITLE
No configure script in SDL3?

### ISSUE THREAD

**Issue by kglundgren** [libsdl-org/SDL#7562]
I cloned the main branch using `git clone https://github.com/libsdl-org/SDL.git` and then `mkdir build`, `cd build`, and finally `../configure`.

Then I get this error: `bash: ../configure: No such file or directory`

**Comment by icculus** [comment]
The autoconf script has been removed in SDL3. Use CMake instead.

```bash
mkdir cmake-build
cd cmake-build
cmake ..
make
sudo make install
```
