### ISSUE TITLE
evt.key.keysym.sym in Linux with russian keyboard layout

### ISSUE THREAD

**Issue by 1vanK** [libsdl-org/SDL#7565]
On Windows `sym` is always in the range of `SDL_Keycode` enum. When I press `W` for example `sym` is `SDLK_w` even if the `ru` keyboard layout is enabled.

On Linux with `ru` keyboard layout `sym` is different and out of range `SDL_Keycode`.

Is there a way to get identical behavior on these two platforms?

![](https://user-images.githubusercontent.com/13021826/229269578-a21b967a-b644-4830-a401-f55470e6be56.png)

**Comment by slouken** [comment]
The Windows behavior was a bug and is now fixed.
