### ISSUE TITLE
[Android] Kotlin support for android project

### ISSUE THREAD

**Issue by vladimirlisovskij** [libsdl-org/SDL#7566]
Hi there!

Currently, kotlin is the preferred language to develop applications for android. Therefore, switching to kotlin will make the project more attractive for new contributions and possibly make it easier to support in the future.

Kotlin will run on the JVM, so the java code can be called from the kotlin code and vice versa if necessary.

I propose to change the current android project (or a new one created from it) as follows:
- Migration from java to kotlin for android project source code files
- Migration from groovy to kotlin for gradle files for the android project
- Add instructions for using kotlin to the documentation

I can start doing it if you approve.

**Comment by madebr** [comment]
The beauty of having java sources is you only need the Android platform tools (`android.jar`) and the android build tools (`aapt2`, `apksigner`, `d8`, `apksigner`, `zipalign).
With kotlin, you'd need to download additional packages from maven.

**Comment by vladimirlisovskij** [comment]
@madebr 
Thanks for the reply!
I think all we need additionally is the kotlin compiler. We can get it from the official repository or by using the gradle plugin

**Comment by wddl** [comment]
I also need kotlin's support very much, how can I do it

**Comment by wddl** [comment]
> Hi there!
> 
> Currently, kotlin is the preferred language to develop applications for android. Therefore, switching to kotlin will make the project more attractive for new contributions and possibly make it easier to support in the future.
> 
> Kotlin will run on the JVM, so the java code can be called from the kotlin code and vice versa if necessary.
> 
> I propose to change the current android project (or a new one created from it) as follows:
> 
> * Migration from java to kotlin for android project source code files
> * Migration from groovy to kotlin for gradle files for the android project
> * Add instructions for using kotlin to the documentation
> 
> I can start doing it if you approve.
Whether you have implemented this feature?thanks

**Comment by madebr** [comment]
Why do you think to need the android glue in kotlin?
Kotlin and java can call each other without issue.

https://kotlinlang.org/docs/java-interop.html
https://kotlinlang.org/docs/java-to-kotlin-interop.html

**Comment by wddl** [comment]
> Why do you think you need the android glue in kotlin? Kotlin and java can call each other without issue.
> 
> https://kotlinlang.org/docs/java-interop.html https://kotlinlang.org/docs/java-to-kotlin-interop.html


thanks to relpy.
I need to use jetpack compose  ui component. so I need a kotlin activity.

**Comment by wddl** [comment]
> You don't need to modify the SDL java classes: simply subclass them and override `getLibraries`.
> 
> So this java code ...
> 
> ```java
> package com.example;
> 
> import org.libsdl.app.SDLActivity;
> 
> public class MyActivity extends SDLActivity {
>     protected String[] getLibraries() {
>         return new String[] { "example", "SDL2" };
>     }
> }
> ```
> 
> ... becomes the following in kotlin:
> 
> ```kotlin
> package com.example;
> 
> import org.libsdl.app.SDLActivity
> 
> class MyActivity : SDLActivity() {
>     override fun getLibraries(): Array<String> {
>         return arrayOf("example", "SDL2")
>     }
> }
> ```

![image](https://github.com/libsdl-org/SDL/assets/26518625/7d7e4db4-4b6a-4c2a-94c8-21d6c0f32a55)
![image](https://github.com/libsdl-org/SDL/assets/26518625/04318b1f-411b-4a93-9355-76a462e2ce14)

Thanks！
I successfully called setContent function in the above way in order to use jetpack compose ui, but the program run with a black screen. I found that it is possible to package SurfaceView to AndroidView, but the work is complicated. Is there a better way to use jetpack compose ui in sdl?

**Comment by wddl** [comment]
> You don't need to modify the SDL java classes: simply subclass them and override `getLibraries`.
> 
> So this java code ...
> 
> ```java
> package com.example;
> 
> import org.libsdl.app.SDLActivity;
> 
> public class MyActivity extends SDLActivity {
>     protected String[] getLibraries() {
>         return new String[] { "example", "SDL2" };
>     }
> }
> ```
> 
> ... becomes the following in kotlin:
> 
> ```kotlin
> package com.example;
> 
> import org.libsdl.app.SDLActivity
> 
> class MyActivity : SDLActivity() {
>     override fun getLibraries(): Array<String> {
>         return arrayOf("example", "SDL2")
>     }
> }
> ```

![image](https://github.com/libsdl-org/SDL/assets/26518625/59063cb6-ad53-440f-b300-2b6a54fbdbab)
![image](https://github.com/libsdl-org/SDL/assets/26518625/5a5ebee2-44b3-4326-baa9-373a9f4e26ca)

I successfully called setContent in the above way to use the jetpack compose ui, but SurfaceView overrides the previous ui. I found that it is possible to package SurfaceView to AndroidView, but the work is complicated. Is there any way to use jetpack compose ui in sdl?

**Comment by wddl** [comment]
> You don't need to modify the SDL java classes: simply subclass them and override `getLibraries`.
> 
> So this java code ...
> 
> ```java
> package com.example;
> 
> import org.libsdl.app.SDLActivity;
> 
> public class MyActivity extends SDLActivity {
>     protected String[] getLibraries() {
>         return new String[] { "example", "SDL2" };
>     }
> }
> ```
> 
> ... becomes the following in kotlin:
> 
> ```kotlin
> package com.example;
> 
> import org.libsdl.app.SDLActivity
> 
> class MyActivity : SDLActivity() {
>     override fun getLibraries(): Array<String> {
>         return arrayOf("example", "SDL2")
>     }
> }
> ```

![image](https://github.com/libsdl-org/SDL/assets/26518625/e91132fa-949e-47d8-9700-8181831a2903)
![image](https://github.com/libsdl-org/SDL/assets/26518625/46edcde1-333d-4dd5-9bee-fc693ef36a01)

I successfully called setContent in the above way to use the jetpack compose ui, but SurfaceView conflicts with the compose ui and can only display one of them. I found that it is possible to package SurfaceView to AndroidView, but the work is complicated. Is there any way to use jetpack compose ui in sdl?

**Comment by madebr** [comment]
@1bsyl
You know a lot about the SDL on Android architecture.

**Comment by 1bsyl** [comment]
I've never used Jetpack compose ui ... so I don't really know.

but SDL uses a SurfaceView internally to render things.
If i remember correctly it's should possible to use 2 surfaceview 
(https://github.com/google/grafika multiple surface view example,
https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/MultiSurfaceActivity.java ).

So 1 for SDL, and the other for compose ui.
and you can use the z order so jetpack compose ui is display on top ... 
(or change SDL so that it's display under)

not really sure if that would work ...

**Comment by wddl** [comment]
> I've never used Jetpack compose ui ... so I don't really know.
> 
> but SDL uses a SurfaceView internally to render things. If i remember correctly it's should possible to use 2 surfaceview (https://github.com/google/grafika multiple surface view example, https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/MultiSurfaceActivity.java ).
> 
> So 1 for SDL, and the other for compose ui. and you can use the z order so jetpack compose ui is display on top ... (or change SDL so that it's display under)
> 
> not really sure if that would work ...

thanks to relpy！
I'm not sure if jet compose ui uses surfaceview, which does not expose a specific method. However, I successful integrate jet compose ui with sdl by modifying a little of sdl class code. But it is not certain that this change will hide some problems? I expect the official sdk to support the jet compose ui library. my method is as follows:
![image](https://github.com/libsdl-org/SDL/assets/26518625/dab8ad46-e5ee-4cef-83fe-711d8472500d)
![image](https://github.com/libsdl-org/SDL/assets/26518625/3ccac259-5271-4c86-9b69-7727c572b572)
![image](https://github.com/libsdl-org/SDL/assets/26518625/d1af0367-e0a1-4388-bb9a-b6987a079b7b)

**Comment by 1bsyl** [comment]
At first, this doesn't look scary:
- instead of adding the SurfaceView directly in the view/layout from the sdl activity, you defer this to jetpack compose constructor. 
- and you replaced Activity by ComponentActivity.
this is neat.

Do this render both SDL (from c side) and compose ui ?

maybe you still need the onsystemuivisibility listener (overload the one from ComponentActivity ) ? or you will miss some functionality (but this may no be a big deal)

**Comment by wddl** [comment]
> At first, this doesn't look scary:
> 
> * instead of adding the SurfaceView directly in the view/layout from the sdl activity, you defer this to jetpack compose constructor.
> * and you replaced Activity by ComponentActivity.
>   this is neat.
> 
> Do this render both SDL (from c side) and compose ui ?
> 
> maybe you still need the onsystemuivisibility listener (overload the one from ComponentActivity ) ? or you will miss some functionality (but this may no be a big deal)

![Screenshot_20230927_183513_org libsdl app](https://github.com/libsdl-org/SDL/assets/26518625/0c946d4c-8013-4d4e-92e1-b263a2f2bec9)
render both SDL (from c side) and compose ui is ok。other features have not yet been tested。

**Comment by slouken** [comment]
It sounds like this is working? I'll go ahead and close this for now. Please feel free to open other issues if you're running into specific problems.
