### ISSUE TITLE
There seems to be no way of actually modifying the window's size on Android.

### ISSUE THREAD

**Issue by themistocles-0** [libsdl-org/SDL#7568]
Using the basic android-project that comes packaged with SDL2 version 2.26.4, I've written the below `Activity.java` as the launcher for my application:
```
package org.libsdl.app;

public class Activity extends SDLActivity
{
	protected String[] getLibraries()
	{
		return new String[]
		{
			"SDL2",
			/* "SDL2_image",
			"SDL2_mixer",
			"SDL2_net",
			"SDL2_ttf", */
			"activity"
		};
	}
}
```
Below is my `activity.cpp` that contains the c++ source code for the basic application:
```
#include <GLES2/gl2.h>
#include <SDL2/SDL.h>
#include <utility>

int main(int argc, char** argv)
{
	if(SDL_Init(SDL_INIT_VIDEO|SDL_INIT_EVENTS) == 0)
	{
		uint32_t displayWidth { 0 };
		uint32_t displayHeight { 0 };
		
		SDL_DisplayMode displayMode;
		// SDL_GetCurrentDisplayMode(0, &displayMode);
		SDL_GetDisplayMode(0, 0, &displayMode);
		displayWidth = static_cast<uint32_t>(displayMode.w);
		displayHeight = static_cast<uint32_t>(displayMode.h);
		
        std::pair<uint32_t, uint32_t> displaySize {
			std::make_pair(displayWidth, displayHeight)
		};
		
		SDL_Window* window {
			SDL_CreateWindow("Activity", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, displaySize.first, displaySize.second, SDL_WINDOW_FULLSCREEN_DESKTOP|SDL_WINDOW_OPENGL|SDL_WINDOW_ALLOW_HIGHDPI)
		};
		
		SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);
		
		SDL_GLContext context {
			SDL_GL_CreateContext(window)
		};
		
		glClearDepthf(1.0f);
		glEnable(GL_DEPTH_TEST);
		glDepthFunc(GL_LEQUAL);
		glEnable(GL_CULL_FACE);
		glViewport(0, 0, displaySize.first, displaySize.second);
		
		bool b = true;
		
		while(b)
		{
			SDL_Event event;
			
			while(SDL_PollEvent(&event))
			{
				switch(event.type)
				{
					case SDL_QUIT:
						b = false;
					case SDL_KEYDOWN:
						if(event.key.keysym.sym == SDLK_ESCAPE)
						{
							b = false;
						}
						break;
					default:
						break;
				}
			}
			
			SDL_GL_MakeCurrent(window, context);
			
			glClearColor(0.0f, 1.0f, 0.0f, 1.0f);
			glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);
			
			SDL_GL_SwapWindow(window);
		}
		
		SDL_GL_DeleteContext(context);
		SDL_DestroyWindow(window);
		
		SDL_Quit();
	}
	else
	{
	}
	
	return 0;
}
```
My expectation was that the entire screen would be green, however, the image below was the result:
![Screenshot_20230402-171530](https://user-images.githubusercontent.com/74494183/229359721-b525467f-3b71-4557-a0cb-79408c7b6294.png)
No matter what line of code I've changed above, the black regions are retained. I've altered:

1.  `glViewport(0, 0, displaySize.first, displaySize.second)` to `glViewport(0, 0, 100, 100)`

2. `SDL_CreateWindow("Activity", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, displaySize.first, displaySize.second, SDL_WINDOW_FULLSCREEN_DESKTOP|SDL_WINDOW_OPENGL|SDL_WINDOW_ALLOW_HIGHDPI)` to `SDL_CreateWindow("Activity", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 100, 100, SDL_WINDOW_FULLSCREEN_DESKTOP|SDL_WINDOW_OPENGL|SDL_WINDOW_ALLOW_HIGHDPI)`

3. Used `SDL_WINDOW_FULLSCREEN` rather than `SDL_WINDOW_FULLSCREEN_DESKTOP`

I've tried more possible solutions than I could list here, none worked. I've also had the same problem with SDL versions 2.0.22 and 2.24.2. I'm using an Android 10 device.

**Comment by madebr** [comment]
Does adding `SDL_WINDOW_RESIZABLE` to the window creation flags change anything?

**Comment by themistocles-0** [comment]
It's started behaving as it should, with the entire screen green except a small black bar at the top, however, I can't seem to only have a small window at the center of the screen.

**Comment by themistocles-0** [comment]
> Does adding `SDL_WINDOW_RESIZABLE` to the window creation flags change anything?
It does not. I've specified minimum API as 29 and target API as 33, the entire screen is green, don't know if that changed anything.

**Comment by slouken** [comment]
That's correct, you get the whole screen on Android, and you're responsible for drawing just into the part you care about.
