### ISSUE TITLE
Issue with Compiz .9 on with drawable failing.

### ISSUE THREAD

**Issue by shadoww1028** [libsdl-org/SDL#7582]
I have been having an issue with Compiz .9 (Arch and Linux Mint), Where if you debug enough windows, aka it takes awhile, eventually you will get a blank window.  I don't think this will occur with full screen windows but only windowed windows.  If I disable Compiz and just let XFCE's WM handle things everything works fine.  I get the following in the output from compiz:

compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (decor) - Warn: No default decoration found, placement will not be correct
failed to create drawable
compiz (core) - Warn: glXCreatePixmap failed

I'm really only reporting this because SDL gives no indication that there was an error.  All of SDLs error handling mechanisms don't indicate any kind of error and the application seems to run just fine in a blank window.   The window has a transparent interior with only the window decoration.  The debugging can be restarted and normally it will work once again.  I'm Running an AMD GPU and the kernel doesn't seem to matter.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
