### ISSUE TITLE
14.3 Project builds but will not archive

### ISSUE THREAD

**Issue by timothystulman** [libsdl-org/SDL#7584]
When I build the Mac app in Xcode, everything works as it always has. But when I try to archive the app for distribution, I get this error: 

ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by timothystulman** [comment]
Sorry wrong thread.

**Comment by slouken** [comment]
FYI, this happens because Xcode 14.3 doesn't support the minimum deployment target of macOS 10.9. The minimum supported deployment target is macOS 10.13.

**Comment by timothystulman** [comment]
@slouken TYSM! Spent an entire day trying to figure this out, and likely would have spent a few more had you not chimed in. So glad I posted this here in error.

**Comment by slouken** [comment]
You're welcome!
