### ISSUE TITLE
Is there any support on BT2020 in windows platform？

### ISSUE THREAD

**Issue by futan-yj** [libsdl-org/SDL#7588]
![image](https://user-images.githubusercontent.com/106951140/230628108-eb9292ab-4c74-452f-b786-70441d666abe.png)
From the header, seems still not support the mode.

**Comment by futan-yj** [comment]
> Not currently, but you're welcome to add it and submit a pull request.

Thanks, I tried to add CONVERSATION_BT2020 and corresponding shader, but found it can't support 10bit data processing in the logic...

**Comment by slouken** [comment]
@futan-yj, did you get any farther? This is something I'd like to get for SDL 3.0

**Comment by slouken** [comment]
This is currently supported in SDL3.
