### ISSUE TITLE
testsprite only shows a black screen on Android

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#7589]
I found these messages in the log, but I'm not sure they are relevant.
```
04-08 00:30:04.938 15260 15260 V SDL     : surfaceChanged()
04-08 00:30:04.939 15260 15260 V SDL     : Window size: 1920x1023
04-08 00:30:04.939 15260 15260 V SDL     : Device size: 1920x1080
04-08 00:30:04.941 15260 15260 E libEGL  : eglMakeCurrentImpl:1049 error 3002 (EGL_BAD_ACCESS)
04-08 00:30:04.941 15260 15260 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
04-08 00:30:04.941 15260 15260 E libEGL  : eglMakeCurrentImpl:1049 error 3002 (EGL_BAD_ACCESS)
```
Switching the renderer to `software` by passing `--renderer software` makes the app work, though very slow.

**Comment by 1bsyl** [comment]
using software render, it's normal to be slow.
not sure why there is a black screen, but logs seems the egl starts to initialize, where's  runMain() log ? 
I would need the full adb log to see what's wrong.

(maybe more info / logs: `--info renderer`)

**Comment by madebr** [comment]
Here's a log of logcat with `--info render`.
[log.txt](https://github.com/libsdl-org/SDL/files/11183429/log.txt)

I launched `SDLTestActivity` through `SDLEntryTestActivity`.
This activity is added in #7581 to modify the arguments. Its log entries are prefixed with `SDLEntry`.

**Comment by 1bsyl** [comment]
strange ...
I tried just replacing my code, with testsprite.c and other code dependencies, and that works directly
I'd say this has something to do with SDLEntryTestActivity, but in the other hand you say this runs with the software renderer.

surfaceChanged seems to be called twice .. not sure why (this may be ok).
this could be, the context get lost, and now the render use a bad one.

```
04-08 15:58:08.247 21031 21031 V SDL     : onConfigurationChanged()
04-08 15:58:08.249  2395  2517 E OpenGLRenderer: Unable to match the desired swap behavior.
04-08 15:58:08.249 21031 21049 E OpenGLRenderer: Unable to match the desired swap behavior.
04-08 15:58:08.251 21031 21031 V SDL     : surfaceChanged()
```
using two activity, interact inbetween ...

**Comment by madebr** [comment]
With #7581, you can launch the `SDLActivity` immediately, or go though `SDLEntryActivity` through a shortcut (by keeping pressing on the launcher icon).
`testsprite` keeps showing a black screen however I launch it.

**Comment by 1bsyl** [comment]
Just want to add: that I tried, and it worked :/
btw, when I go to backgroud/foreground, it became very slow. not sure what happens ...
but there no synchronisation inside the app, so this is strange...

**Comment by 1bsyl** [comment]
when exiting:
`libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 23687 (RenderThread), pid 23667 (SDLActivity)`

exiting, after bg/fg: 
```
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x79f11bf2d0)
libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 23471 (Binder:23361_5), pid 23361 (SDLActivity)
```

**Comment by 1bsyl** [comment]
ok. it actually not working. I was testing spritemininal ! I look later.

**Comment by 1bsyl** [comment]
1/  testprite.c has some problem when it sets the logicalpresentation,
that makes the black screen:

  if (SDL_SetRenderLogicalPresentation(state->renderers[i], state->logical_w, state->logical_h, state->logical_presentation, state->logical_scale_mode) < 0) {
                     SDL_Log("Couldn't set logical presentation: %s\n", SDL_GetError());
                     return SDL_FALSE;
                 }

2/ testspritemininal and lots of testapp ends the main with an exit(0). (inside the "static int quit()" function).
which is bad for Android, because main() doesn't run in the main thread.
(eg. the issue sigsev at the ends)


3/ background / foreground. when going to foreground, it then behaves as if presentvsync was set.

**Comment by 1bsyl** [comment]
this should fix the 3/: swap interval on android:
https://github.com/libsdl-org/SDL/pull/7602

**Comment by 1bsyl** [comment]
2/ exits are checked here:
https://github.com/libsdl-org/SDL/pull/7603

**Comment by 1bsyl** [comment]
it seems SDL_SetRenderLogicalPresentation is failing because it is used to early (for Android). app should be on screen.

**Comment by slouken** [comment]
Is this still active?

**Comment by madebr** [comment]
Nope, testsprite is a good citizen now.
Thanks @1bsyl !
