### ISSUE TITLE
Android app public shared files?

### ISSUE THREAD

**Issue by superfury** [libsdl-org/SDL#7592]
I'm currently simply using SDL2 with my app to port it to Android.

Now I use either SDL_AndroidGetExternalStoragePath if SDL_AndroidGetExternalStorageState says it's r/w.
Otherwise, it defaults to SDL_AndroidGetInternalStoragePath instead (or it gives NULL).

Finally, if the resulting path ends with "/Android/data/appfolder", it will strip that off and look for /rootappfolder/redirect.txt at that location or (if that's not found) a redirect.txt file inside the folder returned by those SDL functions.

The content of the redirect.txt file is a simple path (optionally with line ending, which is stripped off) to replace the application files path with instead. But that's only done if it can create (and deleted after that) a writable.txt file in said folder (to check if the location is valid for use).

Would that be a good way to get it's file paths when running on Android w/ SDL2? Or does SDL2 have a better way for this?

**Comment by slouken** [comment]
This is a good question for the SDL discussion group:
https://discourse.libsdl.org/c/sdl-development/6

**Comment by superfury** [comment]
Well, the basic issue is that all SDL2 seems to support is those 2 locations, but my app needs somewhere else to store it's files on Android.

In this case, the user can override the app's path using a redirect.txt in a folder on the root of internal storage, defaulting to what SDL2 supplies, but SDL2 doesn't support such paths directly.
And with the latest Android versions, there's the issue that the internal/external paths returned by SDL2 (those 3 functions) are all inaccessable using their own file managers (blocked by Android) and other apps (as it's more secure). So even after installing the app, the user can't access it's required files (for assets provided by the user him/herself) without hooking up to a PC to access said folder by default.

Android does have some file picker with providing access rights for folders, but those are unsupported by SDL2 as well.

Luckily, such app-specific folders on /storage/emulated/0 are still allowed, but it might not be future-proof wrt Android's security?
