### ISSUE TITLE
SDL_NumJoysticks reports wrong number of controllers in macos on controller reconnect

### ISSUE THREAD

**Issue by dortamiguel** [libsdl-org/SDL#7593]
When using mac I see the following behaviour when calling `SDL_NumJoysticks()`

If I connect a controller to SDL for the first time `SDL_NumJoysticks()` will report that 1 there is 1 controller available.

Then if I disconnect the controller `SDL_NumJoysticks()` will report 0 available

But now if the same controller is connected again `SDL_NumJoysticks()` will say there is now 2 controllers available when there is only one connected.

If I try disconnecting and connecting again `SDL_NumJoysticks()` will keep saying that there is 2 controllers available, so it seems like it stops increasing there.

Something else I noticed is that after reconnecting many times the same controller `event.cdevice.which` will increase by 2 each time, this means that if I reconnect the same controller the value of `event.cdevice.which` will be 4, and a third time 6.

Restarting the game will reset `SDL_NumJoysticks()` back to 0 again.

I tested it on Windows and in there this issue won't appear.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.
