### ISSUE TITLE
[Linux] [Feature Request] Add support for 8bitDo Arcade Stick

### ISSUE THREAD

**Issue by cmalvi** [libsdl-org/SDL#7615]
The stick works as Xbox360 gamepad now using xpad, but P1 and P2 buttons aren't recognized, made those buttons unusable

**Comment by icculus** [comment]
The stick is working on Linux for me in Xbox mode, without xpad, including the Left-Stick/Dpad/Right-Stick toggle switch. I used a wired connection, ymmv with Bluetooth or the 2.4Ghz dongle thing.

P1 and P2 are _macro_ buttons on this controller; they are not reported to the app by the hardware. Instead, you record combos of other inputs that are played back when you press those buttons. SDL and/or xpad can't use them in any other way.
