### ISSUE TITLE
Support for additional clipboard content

### ISSUE THREAD

**Issue by LiquidityC** [libsdl-org/SDL#7625]
Currently the SDL functions that read from clipboard are all text-oriented. Are there any plans or is there any value in looking into fetching other buffers from clipboard?

Personally I'm mostly thinking about image content. Cutting and pasting images and screenshots etc is quite common these days and it could be useful to facilitate in SDL.

**Comment by slouken** [comment]
Yep, I'm surprised there isn't already a bug for this, but this would be great to add in the SDL 3.0 milestone. Feel free to submit a PR that adds image support on your favorite platform. :)

**Comment by Guldoman** [comment]
I wonder if it would be possible to have a generic way to manage multiple mime types.

So, when the application wants to set the clipboard, it sends to SDL the list of mime types it supports and a callback function to be called when the data is requested. This callback would receive the requested mime type and would return the actual data.

To get the clipboard data, the application should be able to specify the mime type it wants.
Moreover there should be a mechanism to let the application know about the available mime types, so an event or a function that returns the list of available mime types would be ideal.

We might also need something like this for drag and drop, but I guess that's something for another issue.

The use case for Lite XL would be quite simple and would mostly be about setting our own custom mime type to check if the clipboard content is "ours", so we can manage it in a special way.

**Comment by Guldoman** [comment]
> You think this is risky because the data can be large and therefore it would be better to move this into the application layer?
> 
> The benefit of SDL holding the data is that the developer doesn't need to concern themselves with keeping the data around until another app requests it. Which I think feels most useful.

Yeah, but it also means that the application must produce all the possible data in advance instead of on-demand, which could mean having to keep around big buffers that won't even be used.

For example copying something in `inkscape` results in the following mime types:
```
image/png
image/x-wmf
image/webp
image/tiff
image/sif
text/x-povray-script
image/x-postscript
application/pdf
image/png
text/x-povray-script
text/xml+xaml
application/tar
text/x-tex
application/x-zip
image/jpeg
text/html
image/hpgl
application/x-xcf
text/xml+fxg
image/x-emf
image/x-e-postscript
image/dxf
image/dxf
application/x-zip
image/svg+xml
image/svg+xml-compressed
image/x-inkscape-svg-compressed
image/svg+xml
image/png
text/plain
image/x-inkscape-svg
STRING
TARGETS
TIMESTAMP
```
Something like this would be quite onerous to precalculate.

**Comment by LiquidityC** [comment]
Ah. No. That's a lot. I see what you're getting at. A callback that provides the data is a lot *smaller* then although slightly more of a hassle to implement. So we can either go with:

```c
// Single
SDL_SetClipboardBuffer(void (*callback)(Uint8 *buf, const size_t len, char *mime), char *mime);

// ...or multi
SDL_SetClipboardBuffer(void (*callback)(Uint8 *buf, const size_t len, char *mime), char **mimes);

// .. or both?
```

As for retrieving data. Introducing a new event is unavoidable as I see it and it will have to include the mime type. We'll most likely start getting two events for text clipboard though. The existing event and the new data event. I don't really see this as a problem.
In regards to maintaining a list of available mime-types retrievable through eg. `SDL_ClipboardHasMimeType(char *mime)` we can see if it's viable. I've only looked at wayland so far. And in line with @icculus comment I prefer being careful so I don't build a bunch of stuff that doesn't fit with other platforms. Even though I assume they will be similar.

I'll start with the above approach (Get, Set and an Event) and see if I can get that running on Wayland in a usable way then we can expand from there.

**Comment by icculus** [comment]
> Yeah, but it also means that the application must produce all the possible data in advance instead of on-demand

This is a good example of what I meant by testing the API by implementing it across several platforms: the above quote is _exactly_ how the Windows clipboard works: you can supply the same data in multiple formats simultaneously, but you have to supply them all upfront and the system makes a copy of everything. There isn't the X11/Wayland concept of an app owning the clipboard so it can generate the data on request.

(Practically speaking, this is technically true on X11 now too, as there is usually a background process in modern times that immediately requests any published data, holds a copy and immediately becomes the clipboard owner to serve it to others, so the clipboard lives on even if the app hangs/terminates.)

**Comment by takase1121** [comment]
> exactly how the Windows clipboard works: you can supply the same data in multiple formats simultaneously, but you have to supply them all upfront and the system makes a copy of everything

This is somewhat misleading - Yes, you do supply them upfront in most cases with the Cliboard API, but with the OLE Clipboard API, it's possible to defer "rendering" (whatever MS calls it) until it is requested. However, due to what Windows people usually expect from the clipboard (namely the program exiting shouldn't make all clipboard data dissapear), you can call `OleFlushKeyboard`, which will write everything to memory.

> All formats are offered on the clipboard using delayed rendering (the clipboard contains only a pointer to the data object unless a call to [OleFlushClipboard](https://learn.microsoft.com/en-us/windows/desktop/api/ole2/nf-ole2-oleflushclipboard) renders the data onto the clipboard). The formats necessary for OLE 1 compatibility are synthesized from the OLE 2 formats that are present and are also put on the clipboard.

https://learn.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-olesetclipboard

**Comment by LiquidityC** [comment]
I've been thinking some more. Prepare for somewhat coherent conclusions followed by a question.

The amount of code required from developers in the pre-made approach and the on-demand approach is the same.
In general I think the on-demand approach feels nicer and more "optimized", but this is pure opinion probably biased by my actual work and a long linux history.

However. SDL is (I'm going to assume) primarily used in game development. In my experience CPU cycles and control of them is the real gold when making games. Memory, not so much. Here I think the on demand approach is a poor design since an external app can request and cause "unplanned" CPU load from the SDL app. In a performance aware context I think it's preferable to consciously generate the content in advance. Granted this can be done despite how we solve it in SDL but I'm sort of leaning towards SDL taking that decision out of the developers hands and being biased instead.

From a user perspective I think the approach `SetClipboardData(Uint8 *data, size_t len, char *mime_type)` is a lot more user friendly and requires less underlying understanding then the callback approach. I also think this one will match better with the different APIs.

My question is: Who decides how we should build this? Can I just get cracking and make a decision? I'd rather not dedicate the hours and then get bounced in review.

**Comment by Guldoman** [comment]
Regarding the on-demand model in Windows, this seems to describe the situation and might be useful: https://learn.microsoft.com/en-us/windows/win32/dataxchg/clipboard-operations#delayed-rendering

**Comment by LiquidityC** [comment]
I've more or less completed a working implementation for Wayland. I'm going to un-draft the PR once I get all the builds to get green but if anyone wants to give some feedback I don't mind hearing it. I also left a bunch of comments explaining my thoughts.

**Comment by LiquidityC** [comment]
I started looking into the X11 driver. It seems to be piggybacking the clipboard data in an X11 property and doesn't introduce any data containers in `SDL_VideoData` like Wayland does (`SDL_WaylandInput`).

Is it ok to extend this so that X11 can carry some data through `SDL_VideoData`. Eg. `SDL_X11ClipboardData`?
This is my initial thought on how to solve this for X11. If anyone with more X11 experience wants to chime in I'm open to suggestions.

**Comment by slouken** [comment]
This is implemented for SDL3!
