### ISSUE TITLE
Needed functions to generate formatted null-terminated strings

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#7626]
I'm working in Free Pascal which handles strings in three different ways:

1. `PChar` — null-terminated string, any length, compatible with C.
2. `ShortString` — a managed string with a maximum length of 255 characters.
3. `String` — managed string of any length, automatic support for UTF-8, refcount, codepages, silent convertion, concatenation, blah blah blah.

SDL is written in C, so it's ideal for me to only use the first way, which is `PChar`. The Free Pascal standard library has a small set of functions for manipulating these types of strings — allocation, deallocating, copying, concatenation, searching, etc. The problem is that it does not have a function that would allow you to format a string, as does, for example, `sprintf`-like and simillar functions, which are given a format string and parameters to convert and insert into the string.
___

Can SDL expose these types of functions from the C library externally so that they can be used on the application side?

I mean a function like `sprintf` that you can give a format string and arguments to. Actually, two would be useful: one that fills the already allocated string buffer (equivalent to `sprintf`) and the other that itself allocates a large enough buffer for the output, fills it and returns a pointer to it (something like [`asprintf`](https://man7.org/linux/man-pages/man3/asprintf.3.html)).

Perhaps it would be a good idea to create and expose a full set of functions for manipulating null-terminated strings, but for now we're mainly talking about string formatting.

**Comment by slouken** [comment]
You mean something like `SDL_snprintf()` and `SDL_asprintf()`? They exist:
https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_stdinc.h#L578
