### ISSUE TITLE
Read/write thread locks

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7635]
It would be nice if SDL3 offered read/write locks instead of just the traditional mutex.

These work _mostly_ like a mutex, but you specify if you are locking for _read-only_ access verses locking for _write_ access. The difference is that if every thread acquiring the lock just wants to read, they are all permitted access in parallel, but if something asks for write access, it must wait until all locks (read or write) are relinquished, and then it is granted exclusive access--like a standard mutex--until it releases the lock.

A real-world example I'm running into right now is the global list of audio devices SDL maintains: this list only changes when a device is connected or unplugged, so in real life this list might change somewhere between rarely and never during a run of the program, but every function that specifies a device instance ID needs to lock a mutex before searching this list for the appropriate instance, in case it is changing at that exact moment in another thread.

This isn't life-and-death in this example, but things like this can be potential wins if we had a better set of verbs for locking.

On Unix and macOS, this is implemented via pthread_rwlock_t.

Win32 has SRWLOCK as of Windows Vista.

Other platforms might have other things, but it's always safe (though less efficient) to fall back to a standard mutex on platforms without specific support for this (and/or maybe we can build our own implementation out of existing locking primitives?).

**Comment by DeafMan1983** [comment]
You mean `SDL_LockRW(RWops *rw)` and `SDL_UnlockRW(RWops *rw)` it looks much better. Do you like my suggestion?

**Comment by icculus** [comment]
> You mean SDL_LockRW(RWops *rw) and SDL_UnlockRW(RWops *rw)

It's not for RWops.

**Comment by icculus** [comment]
This was added in https://github.com/libsdl-org/SDL/commit/e474047ff8bf076c86699cc9bf33e9320f2eb05a
