### ISSUE TITLE
Restore macOS minimum deployment target to 10.7

### ISSUE THREAD

**Issue by Garirry** [libsdl-org/SDL#7636]
The deployment target for Mac has been 10.7 for a significant amount of time, yet has been raised to 10.9 last year, and now to 10.11. I do not have in-depth knowledge regarding the development of SDL, but reading the issues list it appears that most of the problems that resulted in the version increase are minor and could be resolved with reasonable ease.

I realise that support for versions this old is often looked down upon and seen as unnecessary in the modern day. However, here are some further points as to why I ask to take another look at this matter:

- A significant amount of Macs cannot upgrade past 10.7. For the kind of software built on SDL, they are usually more than adequate in terms of performance. While installing newer versions unofficially is possible, lack of GPU acceleration makes this impractical in most scenarios.
- There are no substantial technical advancements or feature improvements relevant for the platform for versions afterwards. By comparison, the upgrade from 10.6 to 10.7 abolished 32-bit support and created the new full screen mode, both of which are relevant to SDL. There is nothing significant (at least anything that's mandatory) the library takes advantage of in newer versions.
- SDL still supports Windows XP, despite it being significantly older and the amount of hurdles needed to make it run properly. I understand that the life cycle of Windows is generally considerably longer than macOS, but nonetheless, 10.7 is modern enough to make it sustainable without significant drawbacks.
- SDL2 is reaching its end of life. I have no issues with SDL3 requiring cutting-edge hardware and software, as it is a new platform with new long-term aspirations. But as effort on SDL2 is significantly reduced, it appears irresponsible to kill compatibility for a legacy platform that has preserved it for so long. At the same time, the lack of significant new features seems to suggest that any hurdles introduced to keep it working are unlikely to cause problems.
- There is nothing preventing developers from supporting older versions, and ultimately it should be their decision whether it's too much of a pain to support, not the SDL team's. I understand Apple likes to make life for developers difficult, but that's not an excuse. Considering how critical SDL is of a library and how often it's used, it's difficult to justify a significant handicap in terms of compatibility. I myself have built a SDL test project that is fully compliant with Apple's latest requirements, is dual binary, and supports 10.7, with relative ease.

I just think it is disappointing to have this completely unnecessary regression. For me, as someone who believes in preserving maximum compatibility with older devices, it means I'm forced to use an older version of SDL, having to renounce minor bugfixes and improvements, creating a situation that will ultimately end up inconveniencing one group of users or the others no matter what. Even if it is not the top priority to address this right away, I strongly urge the developers to at the very least consider resolving this issue at some point in the future.

**Comment by icculus** [comment]
The bumps to 10.9 and, later, to 10.11 are simply that the latest version of Xcode forced this as a minimum, but there are no code changes to SDL that prevent building for 10.7, afaik.

Either tweaking that version lower in the Xcode projects, or generating an Xcode project with CMake, or using CMake to build _without_ Xcode, will let mainline SDL build for 10.7.

**Comment by icculus** [comment]
(And, obviously, build with an older version of Xcode after tweaking the project files.)

I think there's nothing else to do here; if there's a cleaner solution, or we need a patch to restore compat with older macOS releases, please let us know and I'll reopen this issue.

**Comment by Wohlstand** [comment]
What about the CMake build? Is this limitation affects only Xcode projects only, or this is a limitation added on the compiler side?

**Comment by Wohlstand** [comment]
By myself, I do use CMake build only. So, I do have a question, does this limitation happens on IDE and native project files only? Or it happens on complier level? I.e. if I try to run the Clang directly with pointing a minimal macOS version, will the build fail?

**Comment by Garirry** [comment]
I did a lot of testing and research and I found out that ultimately, the only problem comes down to Xcode 14.3. It is missing critical libraries required for building for targets older than 10.11. However, it is possible to restore those files and I can confirm both the latest SDL2 master and my project build just fine with 10.7 as the target. See here for more info: https://github.com/kamyarelyasi/Libarclite-Files

But regardless, even without this hack, there is nothing that prevents developers from using the frameworks that have been successfully built for 10.7 in a project with a higher target development. Meaning that even if their original Xcode install fails to build for targets older than 10.11, there is no issue with building a 10.11 project with a framework that has a lower target. The reverse is technically true also, you can build a project with a lower target than the framework's; Xcode will just give a warning and the final product will crash when attempting to run on a lower version (as opposed to when an app has a target higher than the OS, it will not run in the first place). What I'm basically trying to say is that there is no benefit for the developer to have the framework be built for anything higher than the actual supported version.

My recommendations are as follows:

- Publish the framework in the .dmg built for a target of 10.7. It will eliminate the requirement for developers to have to clone the repo and build their own version for no real reason.
- Keeping the 10.11 target by default in the Xcode project is probably okay since most people won't want to mess around with settings or weird hacks, but I'd suggest to update the docs to indicate that 10.7 can be built (it still says 10.9), and also to inform anyone who wants to build SDL themselves that they can lower the version if the circumstances are right.

**Comment by slouken** [comment]
We use an unmodified Xcode for the official releases, and don't plan to try to introduce hacks to target earlier versions of macOS than are officially supported by Apple. That said, you're welcome to publish your own set of Frameworks that target earlier versions, and we will continue to accept patches providing source compatibility down to 10.7.
