### ISSUE TITLE
Composition cursor cannot be moved after accepting an IME candidate

### ISSUE THREAD

**Issue by Robyt3** [libsdl-org/SDL#7639]
After you select an IME candidate, the composition cursor cannot be moved at all initially. If you select a candidate by using the up/down arrows, then the composition cursor will be positioned correctly at the end of the composition text. If you use the space key to cycle through the candidates, the cursor will always be incorrectly at position 0 instead, whereas it should also be at the end in this case. In both cases, using the left/right arrows does not update the composition cursor anymore in this state. But the cursor still seems to update correctly internally. If you use backspace, this correctly removes the last character from the composition in both cases, so the cursor is actually at the last position also in the case that that space key was used to select a candidate. The cursor seems to move correctly internally, so you can also use the left arrow key to move it all the way to the beginning and then use the delete key to remove the first character from the composition. Using backspace or delete to remove a character from the composition also makes the composition cursor update correctly again when the left/right arrow keys are used.

Using Windows 10 64 bit (e.g. in Firefox or in the default Editor) and the Japanese IME, you can for example type "sekai" as "世界", move the cursor one position to the left (between the two kanji), then type "a" as "あ" so the current composition text becomes "世あ界".

This bug happens with all SDL versions that I tested (2.0.8, 2.0.16, 2.0.20, 2.0.22 and 2.26.5) so it doesn't appear to be a regression like #7616.

This also applies to any kind of candidate being accepted, not only to candidates containing kanji. For example typing "sumaho" and accepting the candidate "スマホ" (only katakana) or typing "kore" and pressing space to accept the initial composition "これ" (only hiragana) also prevents the composition cursor from being updated.

**Comment by slouken** [comment]
By default, we'll show the native IME UI, which allows you to move the cursor this way.

If you hide the native IME UI, as far as I can tell Windows does not provide subclause cursor information (the cursor is reported as being at the beginning of the clause)

Since it will work now by default, I'll go ahead and close this.
