### ISSUE TITLE
Rename Cond and Sem functions?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7642]
Most things in SDL3 got renamed to be SDL_VerbNoun, but the semaphore and condition variables did not:

- SDL_SemWait
- SDL_SemTryWait
- SDL_SemPost
- SDL_SetValue
- SDL_CondSignal
- SDL_CondBroadcast
- SDL_CondWait
- SDL_CondWaitTimeout

These should probably be SDL_WaitSem, SDL_BroadcastCond, etc.

(and maybe "Sem" should be "Semaphore" and "Cond" should be "Condition", idk.)

**Comment by slouken** [comment]
Yep, agreed.
