### ISSUE TITLE
I made SDL3 in C# with ClangSharp ( but not all complete )

### ISSUE THREAD

**Issue by DeafMan1983** [libsdl-org/SDL#7643]
Hello everyone,

I have developed SDL3 in C# ( @flibitijibibo for SDL2-CS )
But ClangSharp can't convert complete from `SDL_stdinc`.h into cs content file

I replace `SDL_(mabsf etc ... )` with `System.Math(F)`

And ClangSharp doesn't know `byte *` from `const char *` just to `sbyte *`

I have made own sbyte * and string conversion functions like so close by @flibitijibibo's UTF8Heap, UTF8ToString and ManagedFromString etc....
See [DeafMan198.Conversion](https://github.com/DeafMan1983/DeafMan1983.Conversion)

And I have made [SDL3](https://github.com/DeafMan1983/DeafMan1983.Interop.SDL3) ( DeafMan1983.Interop.SDL3 ) *Work in Process...

And I have added own `Program.cs`
How do I display filled Rectangle in SDL_Surface?
```
namespace SDL3_Test;

using System;

using DeafMan1983.Interop.SDL3;
using static DeafMan1983.Interop.SDL3.SDL3;

unsafe class Program
{
    private SDL_Window *window;
    private SDL_Surface *surface;

    public void Run()
    {
        if (SDL_Init(SDL_INIT_VIDEO))
        {
            Console.WriteLine("Error: Initializing SDL3!");
        }

        window = SDL_CreateWindow(null, 100, 100, 200, 200, 0);
        if (window == null)
        {
            Console.WriteLine("Error: Creating SDL_Window");
        }

        surface = SDL_GetWindowSurface(window);

        bool isRunning = true;

        SDL_Event evt = new();

        while (isRunning)
        {
            while (SDL_PollEvent(&evt))
            {
                if (evt.type == SDL_EVENT_QUIT)
                {
                    isRunning = false;
                }

                if (evt.type == SDL_EVENT_KEY_DOWN)
                {
                    if (evt.key.keysym.sym == SDL_KeyCode.SDLK_ESCAPE)
                    {
                        isRunning = false;
                    }
                }
            }

            SDL_Rect rect = new()
            {
                x = 20, y = 20,
                w = 160, h = 160
            };

            SDL_FillSurfaceRect(surface, &rect, SDL_MapRGB(surface->format, 255, 255 / 3, 0));
            SDL_UpdateWindowSurface(window);
        }

        SDL_DestroyWindow(window);
        SDL_Quit();
    }


    static void Main()
    {
        new Program().Run();
    }
}
```
Screenshot:
![image](https://user-images.githubusercontent.com/57066679/233953094-71b89191-aa38-42c2-97c8-721509575cd0.png)

PS I replace `int` with `bool` example `SDL_PollEvent()` or `SDL_UpdateWindowSurface()` Why? I would like to replace int to bool? Because sometimes conflict of getting started like C++/c <-> C# if you write in C# and you don't need to worry if you write an example:
```
if (SDL_Init(SDL_INIT_VIDEO))
{
    Console.WriteLine("Error!");
}
```
in C# syntax seems as `bool` and C/C++ syntax seems as `int` or `bool`

And I am still working in process.

I hope you like my C# porting from SDL3 I will release for SDL_image, SDL_ttf and other for 3.x.x version.

**Comment by madebr** [comment]
> And I have added own `Program.cs` How do I display filled Rectangle in SDL_Surface?
> 
> ```
> namespace SDL3_Test;
> 
> using System;
> 
> using DeafMan1983.Interop.SDL3;
> using static DeafMan1983.Interop.SDL3.SDL3;
> 
> unsafe class Program
> {
>     private SDL_Window *window;
>     private SDL_Surface *surface;
> 
>     public void Run()
>     {
>         if (SDL_Init(SDL_INIT_VIDEO))
>         {
>             Console.WriteLine("Error: Initializing SDL3!");
>         }
> 
>         window = SDL_CreateWindow(null, 100, 100, 200, 200, 0);
>         if (window == null)
>         {
>             Console.WriteLine("Error: Creating SDL_Window");
>         }
> 
>         surface = SDL_GetWindowSurface(window);
> 
>         bool isRunning = true;
> 
>         SDL_Event evt = new();
> 
>         while (isRunning)
>         {
>             while (SDL_PollEvent(&evt))
>             {
>                 if (evt.type == SDL_EVENT_QUIT)
>                 {
>                     isRunning = false;
>                 }
> 
>                 if (evt.type == SDL_EVENT_KEY_DOWN)
>                 {
>                     if (evt.key.keysym.sym == SDL_KeyCode.SDLK_ESCAPE)
>                     {
>                         isRunning = false;
>                     }
>                 }
> 
>                 SDL_Rect rect = new()
>                 {
>                     x = 10, y = 10,
>                     w = 180, h = 180
>                 };
> 
>                 SDL_FillSurfaceRect(surface, &rect, SDL_MapRGB(surface->format, 255, 255 / 3, 0));
>                 SDL_UpdateWindowSurface(window);
> 
>             }
>         }
> 
>         SDL_DestroyWindow(window);
>         SDL_Quit();
>     }
> 
> 
>     static void Main()
>     {
>         new Program().Run();
>     }
> }
> ```
> 
> Screenshot: ![image](https://user-images.githubusercontent.com/57066679/233870558-4fc93b1b-2270-4cff-9a34-f5d0cd40f1ea.png)
> 
> PS I replace `int` with `bool` example `SDL_PollEvent()` or `SDL_UpdateWindowSurface()` Why? I would like to replace int to bool? Because sometimes conflict of getting started like C++/c <-> C# if you write in C# and you don't need to worry if you write an example:
> 
> ```
> if (SDL_Init(SDL_INIT_VIDEO))
> {
>     Console.WriteLine("Error!");
> }
> ```
> 
> in C# syntax seems as `bool` and C/C++ syntax seems as `int` or `bool`
> 
> And I am still working in process.
> 
> I hope you like my C# porting from SDL3 I will release for SDL_image, SDL_ttf and other for 3.x.x version.

**Comment by DeafMan1983** [comment]
@slouken Do you like I add wrapper for SDL3 / SDL3image - I will work other extensions like msic and ttf in SDL3 into C# .

I hope you accept my workstation.

I made own simple getting started for SDL3 in C# dotnet net7.0x

```
namespace Tutorial;

using System;

using static DeafMan1983.ConvFunctions;

using DeafMan1983.Interop.SDL3;
using static DeafMan1983.Interop.SDL3.SDL3;

unsafe class SDL3Program
{
    static void Main(string[] args)
    {
        if (SDL_Init(SDL_INIT_VIDEO))
        {
            Console.WriteLine("Error!");
            Environment.Exit(1);
        }

        SDL_Window *window = SDL_CreateWindow(StringFromHeap("Hello Window"), 800, 600, SDL_WINDOW_RESIZABLE);
        if (window == null)
        {
            Console.WriteLine("Error: SDL3 Window creation failed.");
            Environment.Exit(1);
        }

        SDL_Renderer *renderer = SDL_CreateRenderer(window, null, SDL_RENDERER_ACCELERATED);
        if (renderer == null)
        {
            Console.WriteLine("Error: SDL3 Renderer creation failed.");
            Environment.Exit(1);
        }

        bool isRunning = true;
        SDL_Event evt = new();
        while (isRunning)
        {
            while (SDL_PollEvent(&evt))
            {
                if (evt.type == SDL_EVENT_QUIT)
                {
                    isRunning = false;
                }

                if (evt.type == SDL_EVENT_KEY_DOWN)
                {
                    if (evt.key.keysym.sym == SDL_KeyCode.SDLK_ESCAPE)
                    {
                        isRunning = false;
                    }
                }

                if (evt.window.type == SDL_EVENT_WINDOW_RESIZED)
                {
                    SDL_SetWindowSize(window, evt.window.data1, evt.window.data2);
                }
            }

            SDL_SetRenderDrawColor(renderer, 255, 255 / 3, 0, 255);

            SDL_RenderClear(renderer);
            SDL_RenderPresent(renderer);
        }

        SDL_DestroyRenderer(renderer);
        SDL_DestroyWindow(window);
        SDL_Quit();
    }
}
```
And I am stressing because I was sick since 2 weeks but I need take rest if I have time to write on my SDL3 for C# and I hope many developers for C# work with SDL3.

Enjoy and happy developing....
