### ISSUE TITLE
Could not create/update textures when window is minimized on Windows

### ISSUE THREAD

**Issue by rom1v** [libsdl-org/SDL#7651]
This is more a question about how a client app should behave rather than a bug report.

On Windows (and only on Windows), if the window is minimized, creating a texture (`SDL_CreateTexture()`) results in the following error:

```
CreateTexture(D3DPOOL_DEFAULT): INVALIDCALL
```

Updating a texture (`SDL_UpdateYUVTexture()`) results in:

```
LockRect(): INVALIDCALL
```

Is it expected? Should I disable all texture creation/update when a window in minimized? Should I disable it only on Windows (for example, I can imagine that some window managers may still update some thumb view when a window is minimized)?

**Comment by slouken** [comment]
It doesn't surprise me that Direct3D may not have access to graphics hardware when the application is minimized, but I think the intent is for you to be able to create textures and so forth. Maybe it should cache the textures and recreate them once the D3D context is valid again?

FWIW, SDL 3.0 defaults to the D3D11 backend, which as far as I know doesn't have this problem.

**Comment by rom1v** [comment]
Thank you for your answer.

> I think the intent is for you to be able to create textures and so forth

Yes.

> Maybe it should cache the textures and recreate them once the D3D context is valid again?

Meanwhile, I accept failures in texture creation (I do not consider this fatal anymore) and cache the input image until I can create the texture: [commit](https://github.com/Genymobile/scrcpy/commit/6e9a7afdb1576b3d58a169300442c717a91e6d87)
