### ISSUE TITLE
[SDL3] Window titlebar and border colors are inconsistent

### ISSUE THREAD

**Issue by LiquidityC** [libsdl-org/SDL#7653]
Hi,
I have two laptops that I develop on and I'm getting some different behavior in regards to the actual window and it's decorations.
Both my laptops are running gnome3 on Wayland (Ubuntu and Arch Linux).
One one of them the window borders and titlebar are black which doesn't align with my otherwindows. Close and minimize buttons work as expected.
On the other I get no windowborders and no titlebar. Just the SDL content with nothing else.

Is this "under construction" artifacts, an intentional change or should I be taking screenshots and posting logs?

**Comment by Guldoman** [comment]
Is `libdecor` installed on both machines? If I remember correctly, it must be available both at compile-time and run-time to be enabled.

**Comment by LiquidityC** [comment]
That might be it. I'll try to confirm. As for the window not looking like my other windows. Any concern?

![image](https://user-images.githubusercontent.com/164039/234503549-64388cf5-28ae-4003-9af0-b59388ac5a0c.png)

The lower titlebar in this image is my SDL window. The other looks like the rest of my desktop windows.

**Comment by Guldoman** [comment]
> As for the window not looking like my other windows. Any concern?

I don't think we can do much. It's all on `libdecor`.
They have a GTK-style plugin, but afaik distros need to ship it.

**Comment by LiquidityC** [comment]
Noted. Thanks for the info.
