### ISSUE TITLE
Support for fetching user's preferred folders

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#7654]
Many operating systems provide each user with default folders for certain files, such as pictures, videos, music, downloads and the desktop. Since each platform has their own way to name those folders (some even localize the folder name, making it a hassle to implement reliably), it would be interesting to have SDL provide cross-platform support for fetching those folders, similarly to `SDL_GetBaseDir` and `SDL_GetPrefDir`. It would help both game and non-game applications place certain types of files in the relevant folders, such as screenshots in the pictures folder, application updates in the download folder, or saved documents in the documents folder.

If the idea sounds good, I'm willing to take the responsibility to implement this feature.

**Comment by slouken** [comment]
Yes, this seems like a good idea for SDL 3.

Maybe something like SDL_GetPath(enum), where SDL_GetBaseDir() and SDL_GetPrefDir() are special cases of this?

**Comment by DeafMan1983** [comment]
Yeah great idea, Can it work with SDL_RWops? Like it saves and loads preferred file if you resize and close before saving preferred file then you re open sdl3 window with loaded preferred file. Is it for Serialization/Deserialization?

**Comment by Semphriss** [comment]
> Maybe something like SDL_GetPath(enum), where SDL_GetBaseDir() and SDL_GetPrefDir() are special cases of this?

Will do! Thought of using an enum indeed. I didn't think of wiring SDL_GetBaseDir/GetPrefDir on that since they have their own mechanism (most OSes provide builtin functions for users' home folders, but I believe those functions are a bit more advanced), but I can give it a try.

I'm making quite a few design decisions in the process which will eventually need feedback, but I think it'll be easier to discuss them when we'll have the code. I'm taking care to document everything!

**Comment by Semphriss** [comment]
@DeafMan1983 

> Can it work with SDL_RWops?

As currently planned, the functions would just return the paths as a C string, similarly to SDL_GetBaseDir(). Any I/O operation would be done with something else, possibly SDL_RWops or any other.

**Comment by smcv** [comment]
Prior art in other widely-portable open source libraries:

Qt has this under the name "standard paths", https://doc.qt.io/qt-6/qstandardpaths.html which is approximately what's proposed here.

GLib has something similar as "user special directories", https://docs.gtk.org/glib/enum.UserDirectory.html, https://docs.gtk.org/glib/func.get_user_special_dir.html - although GLib's accessors for "important" directories like configuration, data and cache are separate functions in their own right, such as https://docs.gtk.org/glib/func.get_user_config_dir.html, instead of being special members of the enum.

**Comment by slime73** [comment]
This is an API that could be used in Apple backends (macOS / iOS / tvOS): https://developer.apple.com/documentation/foundation/nssearchpathdirectory

And for Windows: https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath

**Comment by Semphriss** [comment]
@slime73 I opened the pull request for this: #7665

For Windows, I found both `SHGetFolderPathA` (deprecated but still available, WinXP+) and `SHGetKnownFolderPath` (modern, Vista+). Do you know if there is a way to detect whether or not the latter is available with a macro? Wine does not support the newer option, so I used the older one for maximum compatibility.

As for macOS, I couldn't implement a port, because I unfortunately do not own a macOS computer; if you have some time and are interested, could you help me with that?
