### ISSUE TITLE
[SDL3] SDL_SetRenderViewport, SDL_Rect is treat as xy,x2y2, coordinates.

### ISSUE THREAD

**Issue by Umwelt32** [libsdl-org/SDL#7655]
[SDL3] Not Clear useage of SDL_Rect parameter in SDL_SetRenderViewport.
SDL_Rect currently is treat as x,y,x2,y2 coordinates, but in SDL_Rect description following fields are:
x,y,w,h. 
Now i have to pass e.g x=100,y=100,w=132,h=132. To render 32x32px rectangle at 100,100 coords.
Last two parameters of SDL_Rect are w,h so i expect that x=100,y=100,w=32,h=32 parameters will render 32x32px rectangle at 100,100 coords.

**Comment by slouken** [comment]
This doesn't seem right. What render backend are you using?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
