### ISSUE TITLE
NULL mutexes are treated as success

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7656]
Most (all?) backends for SDL_mutex support will treat a NULL mutex as a no-op and report success:

```c
// gcc -Wall -O0 -ggdb3 -o testnull testnull.c `pkg-config sdl3 --cflags --libs`
#include "SDL.h"

int main(void)
{
    SDL_Log("%d\n", SDL_LockMutex(NULL));
    return 0;
}
```

will print...

```
INFO: 0
```

Is this good? Should we report an error here, instead, for SDL3?

**Comment by slouken** [comment]
This is intentional. In the case where mutexes aren't allocated yet or have been cleaned up, we don't want spurious errors if other code uses the locks. This is important for the event mutexes and a couple others I can't remember off the top of my head.
