### ISSUE TITLE
DUALSHOCK®4 (PS4) Wireless Controller no longer works in macOS

### ISSUE THREAD

**Issue by vkedwardli** [libsdl-org/SDL#7661]
Since the commit https://github.com/libsdl-org/SDL/commit/2ccdd0667, players report that they cannot use the gamepad anymore.

OS: macOS 10.13.6 (Intel)
Gamepad: DUALSHOCK®4 
Connection method: Bluetooth

Tested using Flycast,  https://github.com/libsdl-org/SDL/commit/653e433c0 is the last commit that works

**Comment by slouken** [comment]
Have you tested the latest SDL2 source? There have been fixes to this since that commit.

**Comment by vkedwardli** [comment]
Just ask him to test, verified it is fixed by v2.26.5
Thanks
