### ISSUE TITLE
Does SDL take donations?

### ISSUE THREAD

**Issue by computermouth** [libsdl-org/SDL#7664]
I don't see anything on the main site, didn't happen to see the github sponsors thing or whatever set up. Tempted to subscribe to @icculus patreon, but I know SDL is certainly more than just Ryan.

I love SDL so much, really looking forward to 3.0 <3

**Comment by slouken** [comment]
SDL doesn't take donations, but I'm sure @icculus would appreciate subscribing to his patreon.

I'm glad you like it! :)

Cheers,
