### ISSUE TITLE
Use ClipCursor(x,y,x+1,y+1) instead of warping

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#7675]
Recording a "desired position" and warping cursor to that position every frame is a janky hack that results in the cursor jittering in place when the user moves the mouse and before the game reaches the next frame update, so it needs to be "faked" with a stationary software sprite while hiding the native cursor. 

Why not just use the cursor clipping function that OSes provides natively? Instead of the game resetting the cursor position, just ask the OS to not move it. 

I think the whole janky warping architecture was motives out of the pre winXP days before providing raw device data is commonplace, but now with all the major OS having raw delta streams there is no reason to keep basing the whole organization around warping.

**Comment by slouken** [comment]
Yes, we recommend not doing that and using SDL_SetRelativeMouseMode(), which uses clipcursor by default.
