### ISSUE TITLE
[DirectFb] Shaped window segmentation fault on create

### ISSUE THREAD

**Issue by LocOlli** [libsdl-org/SDL#7676]
I'm working on a project use SDL2 on directFB. I meet the segmentation fault when try to create a shaped window. I found the problem was here, when you try to use a memory without allocate it first.
I can fix them by apply this patch
`@@ -104,6 +112,7 @@ DirectFB_SetWindowShape(SDL_WindowShaper *shaper,SDL_Surface *shape,SDL_WindowSh
 
         SDL_DFB_CHECKERR(devdata->dfb->CreateSurface(devdata->dfb, &dsc, &data->surface));
         SDL_DFB_CALLOC(bitmap, shape->w *shape->h, 1);
         /* Assume that shaper->alphacutoff already has a value, because SDL_SetWindowShape() should have given it one. */
         SDL_CalculateShapeBitmap(shaper->mode, shape, bitmap, 1);
`
Please review it and fix on the next release

**Comment by madebr** [comment]
`bitmap` is indeed never assigned a value.
Feel free to open a pr.
```patch
--- a/src/video/directfb/SDL_DirectFB_shape.c
+++ b/src/video/directfb/SDL_DirectFB_shape.c
@@ -104,6 +104,8 @@ DirectFB_SetWindowShape(SDL_WindowShaper *shaper,SDL_Surface *shape,SDL_WindowSh
 
         SDL_DFB_CHECKERR(devdata->dfb->CreateSurface(devdata->dfb, &dsc, &data->surface));
 
+        SDL_DFB_CALLOC(bitmap, shape->w * shape->h, 1);
+
         /* Assume that shaper->alphacutoff already has a value, because SDL_SetWindowShape() should have given it one. */
         SDL_CalculateShapeBitmap(shaper->mode, shape, bitmap, 1);
 
```

**Comment by LocOlli** [comment]
I has created a pull request, please help me review, hope to see it on the next release.
