### ISSUE TITLE
Android Devolopement Info

### ISSUE THREAD

**Issue by cool-dev-guy** [libsdl-org/SDL#7679]
# Using CPP/SDL for android Games
Hi i was thinking instead of running SDL with C++ through Java and using JNI ,cant C++ directly compiled to Android Machine Code?Like Unity Game Engine uses Mono to convert C# to Native Machine Code?
- Will there be a performance rise?(since its not passing through JVM or ART layer?)

**Comment by slouken** [comment]
We looked at that a few years ago and there's a lot of functionality that's only available through the Java layer. We've designed SDL so you can entirely write your game in C++, and SDL handles all of the Java interactions for you.

**Comment by cool-dev-guy** [comment]
Thanks but will there be a `mono` like software for C++ in the future?

**Comment by slouken** [comment]
That's not something in scope for SDL development, but who knows what other people might be working on?

**Comment by cool-dev-guy** [comment]
Thanks @slouken for yor reply
