### ISSUE TITLE
No SDL_KEYDOWN/UP events when sending input with virtual key codes on Windows

### ISSUE THREAD

**Issue by takase1121** [libsdl-org/SDL#7687]
On Windows, when a key code is sent with [keybd_event] or [SendInput], no events will be received on SDL2.
However, if the same code is modified to use keyboard scan codes instead of key codes, the events will be received.

[keybd_event]: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-keybd_event
[SendInput]: https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-sendinput

**Comment by slouken** [comment]
This is fixed in SDL3.
