### ISSUE TITLE
Constant cpu usage on mac coreaudiod process after closing audio device

### ISSUE THREAD

**Issue by serakeri** [libsdl-org/SDL#7689]
**Environment**
macOS M1, arm64 python 3.10.11 (when using pygame) 

- **bug observed on tests with SDL2 versions**
2.24.2
2.26.4
2.26.5

- **bug not observed on versions of SDL2 versions**
2.0.18
2.0.22

note: I initially noticed this issue while using pygame (https://github.com/pygame/pygame/issues/3840) so some of those versions are from tests with pygame. **When testing SDL from source with the test program posted here I used versions 2.26.5 (confirm bugged) and 2.0.22 (confirm bug free)** which had the same expected results as pygame using those versions of SDL.

**Current Behavior:**

Opening then closing an audio device on mac uses a constant 10-15% cpu on the process **coreaudiod**.

note: I was able to reproduce this to less of an effect on an x86 mac (3-5% cpu usage) but it seems like the same issue.

**Expected Behavior:**

Opening then closing an audio device on mac has a negligible effect on the cpu usage of **coreaudiod**

**Steps to reproduce:**

1. Open activity monitor and make sure the process "coreaudiod" is idle (0% cpu usage). Do not run other media apps so the cpu usage of "coreaudiod" can be isolated to SDL2. If it's not at 0% cpu usage then quit other media apps until it is at 0%.
2. Run a program that opens an audio device, closes the audio device, then sleeps forever.
3. Open activity monitor and observe "coreaudiod" cpu usage at 10-15% (or 3-5% on x86) until the test program is closed.

**Test Code**
```c++
#include <iostream>
#include <SDL/SDL.h>
#include <unistd.h>

int main() {
    if (SDL_Init(SDL_INIT_AUDIO) < 0) {
        std::cerr << "Failed to initialize SDL: " << SDL_GetError() << std::endl;
        return 1;
    }

    SDL_AudioSpec desired_spec, obtained_spec;
    SDL_zero(desired_spec);
    desired_spec.freq = 44100;
    desired_spec.format = AUDIO_S16;
    desired_spec.channels = 2;
    desired_spec.samples = 1024;

    SDL_AudioDeviceID audio_device_id = SDL_OpenAudioDevice(NULL, 0, &desired_spec, &obtained_spec, 0);
    if (audio_device_id == 0) {
        std::cerr << "Failed to open audio device: " << SDL_GetError() << std::endl;
        SDL_Quit();
        return 1;
    }

    std::cout << "Opened audio device:" << std::endl;
    std::cout << "    Frequency: " << obtained_spec.freq << std::endl;
    std::cout << "    Channels: " << (int)obtained_spec.channels << std::endl;
    std::cout << "    Samples: " << (int)obtained_spec.samples << std::endl;

    SDL_CloseAudioDevice(audio_device_id);
    SDL_Quit();

    for (;;) {
        sleep(5);
    }

    return 0;
}
```

**Additional Info**

You can reproduce the bug with the test code on non bugged versions of SDL by commenting out SDL_CloseAudioDevice which leads me to believe this is an issue with the audio device never being closed.

I have not looked too far into this the SDL2 side of things but https://github.com/libsdl-org/SDL/commit/e7ab581d796aa83f7d028ea4249fdc66600df173 might be related.

The call to AudioQueueDispose parameter was changed from True to False to prevent a hang up.
>If you pass true, the audio queue is disposed of immediately (that is, synchronously). If you pass false, disposal does not take place until all enqueued buffers are processed (that is, asynchronously).
> from https://developer.apple.com/documentation/audiotoolbox/1502229-audioqueuedispose

But I have not worked on SDL2 before so any thoughts or insight is appreciated!

**Comment by icculus** [comment]
These two threads (I assume, from CoreAudio) are still alive, even after SDL_Quit()...

```
  thread #8: tid = 0x74bc3, 0x00000001a8133710 libsystem_kernel.dylib`__psynch_cvwait + 8, name = 'AQConverterThread'
  thread #9: tid = 0x74bc6, 0x00000001a812ff14 libsystem_kernel.dylib`mach_msg2_trap + 8, name = 'com.apple.audio.IOThread.client'
```

Our internal thread is definitely gone, fwiw.

These threads are spun by [the AudioQueueStart call in prepare_audioqueue](https://github.com/libsdl-org/SDL/blob/de9372867484a1290d4d81ec5b697a290a5c7d1e/src/audio/coreaudio/SDL_coreaudio.m#L927), as one might guess.

And yes, these threads go away (and coreaudiod drops to 0% CPU) if we call AudioQueueDispose with a 1 instead of a 0 for the second parameter, so you're definitely on target here.

Let me read up on those commits and see what the full motivations were.

**Comment by serakeri** [comment]
Thank you for the replies and patch!
