### ISSUE TITLE
Last fix to remove Logitech Extreme 3D Pro Joystick from Linux may have broken its detection on Windows

### ISSUE THREAD

**Issue by rsperanza** [libsdl-org/SDL#7698]
To fix a previous defect that was reported that Logitech Extreme 3D Pro was only defined under Linux, 

 Logitech Extreme 3D joystick is listed as gamepad in linux section of SDL_gamecontrollerdb.h #3858 
 
the fix removed the entry completely, instead of moving it under the proper section of the header file so it could be detected on Windows.  I believe this has caused the joystick to not be detected by Steam on Windows any more.

Please fix this properly this time.  Thanks.

**Comment by slouken** [comment]
Steam intentionally does not detect the Logitech Extreme 3D joystick. It only detects gamepad style devices.

**Comment by igitur** [comment]
> Steam intentionally does not detect the Logitech Extreme 3D joystick. It only detects gamepad style devices.

hi @slouken , do you perhaps know why this is the case?

**Comment by slouken** [comment]
> > Steam intentionally does not detect the Logitech Extreme 3D joystick. It only detects gamepad style devices.
> 
> hi [@slouken](https://github.com/slouken) , do you perhaps know why this is the case?

Yes, because if it treats it as a gamepad, it will show up as a gamepad to games running under Steam, which breaks games that have support for these specific devices.
