### ISSUE TITLE
Window does not show up as expected on Wayland

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#7699]
I'm not sure if this is intended behavior, but I thought I should report it anyways.

### Summary

When I attempt to create a simple window with basic code (as shown in the snippet below), on Wayland and with SDL3, no window shows up. If I add some basic rendering, a window does show up, but it is not responsive (I can't move it around) and does not properly show the border decoration.

This does not happen if I use Xorg OR if I use SDL2 instead, which makes me believe that although a simple stub as below rarely occurs in production, such a behavior is probably unintended.

### Details

When I execute the code below on Ubuntu 22.04 with Wayland:
```c
#include "SDL3/SDL.h"

int main()
{
  SDL_Init(0);
  SDL_Window* w = SDL_CreateWindow("", 640, 480, 0);

  SDL_Delay(2000);

  SDL_DestroyWindow(w);
  SDL_Quit();
  return 0;
}
```

... a window is created and registered by the OS dock, but no window actually shows on-screen. After the specified 2 seconds, the app quits, without ever showing any window:

![image](https://github.com/libsdl-org/SDL/assets/66701383/f69f3d24-9139-43ed-a5a1-f86326ed15c6)
<sup>The dock properly registers a window. Right-clicking the icon and clicking "All Windows" reveals a slot for a single window, which is empty and appears to have a size of 0x0.</sup>

If I add basic SDL_Renderer, and the code becomes like this:
```c
#include "SDL3/SDL.h"

int main()
{
  SDL_Init(0);
  SDL_Window* w = SDL_CreateWindow("", 640, 480, 0);
  SDL_Renderer* r = SDL_CreateRenderer(w, NULL, 0);

  SDL_SetRenderDrawColor(r, 0, 0, 0, 255);
  SDL_RenderClear(r);
  SDL_RenderPresent(r);

  SDL_Delay(2000);

  SDL_DestroyRenderer(r);
  SDL_DestroyWindow(w);
  SDL_Quit();
  return 0;
}
```

... then a window does show up, but with several problems:
- The window is unresponsive, I cannot move it around my screen.
- The window decorations are not shown properly, and instead of looking like this:

![Screenshot from 2023-05-11 22-52-12](https://github.com/libsdl-org/SDL/assets/66701383/f4a3387f-b1e2-4159-bccc-407f9232a568)
<sup>Expected appearance of the window. This is the appearance if I use Xorg, or SDL2, or both.</sup>

... the window looks like this:

![Screenshot from 2023-05-11 22-37-56](https://github.com/libsdl-org/SDL/assets/66701383/e141b627-2104-4020-bac8-22974ee1227c)
<sup>Actual appearance of the windows on Wayland with SDL3. Unlike with the properly shown window, taking a screenshot of the window directly does not include the decorations; I had to take a screenshot of my full desktop and crop it down to show the window with decorations.</sup>

I've observed that this issue happens only with:
- Wayland: On the same OS with Xorg, with the first code snippet, the windows shows up, properly shows the window decorations, and can be moved around without problem.
- SDL3: If I try compiling the same code (first snippet) on Wayland against SDL2 instead, the window shows up, is responsive and shows the proper decoration.

**Comment by icculus** [comment]
Wayland needs an event loop and rendering or it won't function. This isn't something we can fix in SDL, and has come up before.

In practice, it only affect little test programs like this, but a better solution would be welcome.

Maybe we just need to document this in README-wayland?

**Comment by icculus** [comment]
Also, the SDL2 examples were almost certainly using the X11 backend with XWayland. The window decorations look weird in sdl3 because libdecor is using a default client-side decoration thing instead of GTK+, and we _really_ need that to change, because this is stating to look like an SDL issue by now.

**Comment by Kontrabant** [comment]
Added a README-wayland file in the documentation that lists common issues, including the above. If any others come up, they can be added.

Hopefully this will help head-off reports of non-bugs in the future.

**Comment by StarmanAkremis** [comment]
> Also, the SDL2 examples were almost certainly using the X11 backend with XWayland. The window decorations look weird in sdl3 because libdecor is using a default client-side decoration thing instead of GTK+, and we _really_ need that to change, because this is starting to look like an SDL issue by now.

any updates on this? I am quite a fan of the gnome theme and I'm sure the users of the other DEs are fans of their themes too.
