### ISSUE TITLE
[xbox (PowerA)]: "guide" and "share" buttons not accessible via SDL

### ISSUE THREAD

**Issue by foxsouns** [libsdl-org/SDL#7713]
Controller: "PowerA", 3rd-party wired Xbox Series X|S controller
Detected as: "Generic X-Box Pad"
Model Name: `lot20103d0401`
[Product site](https://www.powera.com/p/xbox/xbox-series-xs/controllers/wired/enhanced-wired-controller-for-xbox/)

This controller works mostly fine, excepting the fact that the "Guide" and "Share" buttons do not register at all. Running `evtest` on this device reveals that the two buttons simply do not send anything. 

All other buttons appear to work as intended, including the AGB (back-side buttons).

**Comment by slouken** [comment]
If evtest doesn't show any button presses, then the kernel driver isn't reading those buttons and SDL can't provide the data. If evtest is showing button events for those, then it's probably a mapping issue, and you can use the SDL controllermap program to generate a mapping and attach it to this issue.
