### ISSUE TITLE
Wav files with blockalign==0 unnecessarily fail to load.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7714]
This code in the .wav loader...

https://github.com/libsdl-org/SDL/blob/b5cd0749b2d04fbab07be46a5167eac3083b04fb/src/audio/SDL_wave.c#L1711-L1713

...prevents divisions by zero and other disasters, I assume, but there are otherwise-valid .wav files that set this to zero. Like this one from tuxmath: [buzzwav.zip](https://github.com/libsdl-org/SDL/files/11500785/buzzwav.zip)

Can we change this from returning an error to forcing the alignment to 1? It fixes the tuxmath wav file, but I don't know the full ramifications here.

**Comment by slouken** [comment]
Sure, seems fine to me.
