### ISSUE TITLE
Idea / Feature Request: Disconnect, power off, turn off gamepad functions

### ISSUE THREAD

**Issue by Dev-draco** [libsdl-org/SDL#7720]
Would it be possible to add simple support for sending a signal to power off a controller if applicable?

I apologize if this seems out of place, but I'm told that it isn't possible with SDL, or at least I'm not totally familiar with how. If possible, could this be explained on how to achieve this if it is already possible?

**Comment by icculus** [comment]
I'm not sure what controllers would be able to turn off programmatically. Surely not many of them...?

**Comment by slouken** [comment]
Most Bluetooth controllers turn off when disconnected, but that requires a bunch of Bluetooth infrastructure.

Feel free to submit a PR for this, but I'll go ahead and close this for now.
