### ISSUE TITLE
Vulkan function to check for queue family present support

### ISSUE THREAD

**Issue by poconn** [libsdl-org/SDL#7725]
It would be nice to have a wrapper for the platform-dependent `vkGetPhysicalDevice*PresentationSupportKHR()` functions to check whether a given queue family supports presenting to a Vulkan surface. Of course it's possible to create a surface and then use `vkGetPhysicalDeviceSurfaceSupportKHR()`, but in some cases it's more convenient to check before creating the surface. Does it seem worth adding something like the following?
```c
SDL_bool SDL_Vulkan_GetPresentationSupport(VkPhysicalDevice physical_device, uint32_t queue_family_index);
```
If so, happy to try and post a PR for it.

**Comment by slouken** [comment]
It seems reasonable to me. Go ahead and post a PR?

**Comment by poconn** [comment]
Sounds good, thanks! I've been a bit busy but haven't forgotten about this, will hopefully get to it in the next week or so.

**Comment by icculus** [comment]
Duplicate of #8000
