### ISSUE TITLE
hidapi: commits from mainstream for mac and windows

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#7727]
@slouken: These might - or might not - be of interest for backporting into SDL?
Just FYI...

Windows: https://github.com/libusb/hidapi/pull/464
https://github.com/libusb/hidapi/commit/bd6be4d83b36d0dcd5401fb335384586b066a2eb

Mac: https://github.com/libusb/hidapi/issues/531
https://github.com/libusb/hidapi/pull/534
https://github.com/libusb/hidapi/commit/80a206aee5c71d584e8c918e8649cecec02b2ccd
https://github.com/libusb/hidapi/commit/b516e970480a8d05b1c392d106ca110a9d06d668

**Comment by slouken** [comment]
I wonder if it's time to rebase SDL's hidapi on the latest upstream code?

**Comment by sezero** [comment]
For SDL3 only, I guess

**Comment by slouken** [comment]
Yep, if we're going to update the API now's a good time. I know we've added some good fixes as well, and it would be nice to be able to upstream them.

**Comment by slouken** [comment]
So that was a fair bit of work, but I we're now rebased on upstream and I think we have all the important changes for SDL. I merged the PR for additional testing and I'll go ahead and start some PRs so we can get them upstreamed as desired by the maintainers.
