### ISSUE TITLE
Vendoring SDL2 With CMake Breaks QtCreator

### ISSUE THREAD

**Issue by TheBrokenRail** [libsdl-org/SDL#7737]
(I apologize if this is the wrong place to report this, I wasn't sure if this was caused by QtCreator being weird or SDL's CMake script being strange.)

[Vendoring SDL2 with CMake](https://github.com/libsdl-org/SDL/blob/SDL2/docs/README-cmake.md) and Git submodules is a really convenient way to build with the latest SDL2, and for the most part[^1], it works perfectly.

The only issue is with QtCreator, which seems unable to locate SDL2's header files. (This is odd since as I understand it, QtCreator integrates with [CMake's API](https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html) and thus should be able to detect the correct include directory search path.)

![Screenshot from 2023-05-25 01-46-27](https://github.com/libsdl-org/SDL/assets/17478432/4d0dbf23-9e67-4fc3-9f47-08f219fe5d73)

I'd assume this to be an issue with QtCreator, except this only occurs with SDL2. Every other library I've used (vendored or otherwise) works fine.

For now, I've been able to workaround this using this bit of CMake:

```cmake
target_include_directories(SDL2::SDL2 INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/SDL/include")
```

Thank you for any assistance!

[^1]: It forces you to use `#include <SDL.h>` rather than `#include <SDL2/SDL.h>`, that should probably be documented somewhere.

**Comment by madebr** [comment]
Closing this issue.
If you still have issues with using SDL2 in Qt Creator, please provide a reproducer.
