### ISSUE TITLE
Implicit Declaration in SDL_stdinc.h

### ISSUE THREAD

**Issue by phutnick** [libsdl-org/SDL#7740]
Hello,

I am trying to compile fizmo-sdl2 0.8.5 from the current GitHub source. I am using SDL2 version 2.26.5 from Homebrew on an Intel Mac.

% make
[ . . . ]
In file included from sound_sdl2.c:47:
In file included from /usr/local/include/SDL2/SDL.h:32:
In file included from /usr/local/include/SDL2/SDL_main.h:25:
/usr/local/include/SDL2/SDL_stdinc.h:532:5: error: call to undeclared function 'memset_pattern4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    memset_pattern4(dst, &val, dwords * 4);
    ^
1 error generated.
make[2]: *** [sound_sdl2.o] Error 1
make[1]: *** [libsndifsdl2.a] Error 2
make: *** [libsndifsdl2] Error 2
% 

Can you please make this C99 clean? Thanks!

**Comment by slouken** [comment]
This is fixed for the next release. You can get a preview from here:
https://github.com/libsdl-org/SDL/tree/SDL2
