### ISSUE TITLE
Mouse button "stuck" (release + press ignored once) after alt-tabbing off and back onto window (when SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH=0)

### ISSUE THREAD

**Issue by rohlem** [libsdl-org/SDL#7747]
Observed with current `SDL2` branch (commit c68976360d241fb82eda909e610a69b93c90d5d1) on Windows 11.

To reproduce:
1. create an SDL window `w1`, give it focus / have it be in front, and position the mouse over its display area
2. press and hold a mouse button: generates `SDL_MOUSEBUTTONDOWN`
3. alt-tab switch to any other window (can be another program, or even another SDL window of the same program): generates `SDL_WINDOWEVENT_FOCUS_LOST`
4. alt-tab switch back to `w1`: generates `SDL_WINDOWEVENT_FOCUS_GAINED` -> `SDL_WINDOWEVENT_EXPOSED`
5. release held mouse button: **generates no event** (imo a bug)
6. re-press and hold the same mouse button: **generates no event** (imo a bug)
7. release held mouse button: generates `SDL_MOUSEBUTTONUP`

Note: Using `SDL_SetWindowsMessageHook` I am observing `WM_LBUTTONDOWN` and `WM_LBUTTONUP` messages at steps 5 and 6, so the cause is surely SDL-internal.
If the mouse button is released after step 3, at step 4 before the `SDL_WINDOWEVENT_EXPOSED` event a `SDL_MOUSEBUTTONUP` event is generated.

Since the mouse button always seems to get "stuck" in this scenario, and SDL probably can't track the actual "mouse release" event timing after focus loss,
IMO the most sensible alternative behavior would be to always generate `SDL_MOUSEBUTTONUP` and reset the state for all held mouse buttons immediately on window focus loss,
then query the mouse state on focus gain and send `SDL_MOUSEBUTTONDOWN` for the buttons being held down at that point.

**Comment by rohlem** [comment]
Probably the same issue described in #4022 - although that describes a range of scenarios, and seems harder for me to follow.
Here I have a simple scenario that looks like incorrect behavior, and reliably reproduces every time.
Enabling SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH fixes my issue, however from my understanding of the hint it shouldn't:

> A hint that specifies if mouse click events are sent when clicking to focus an SDL window.

In this case, I am not "clicking to focus" because the window is already focused at steps 5 and 6, yet SDL still swallows the events.

**Comment by MadByteDE** [comment]
I might have reproduced this on Fedora Linux 39 (X11) using a lua game framework called LÖVE which appears to utilize SDL2.

**Comment by slouken** [comment]
Thanks for the repro steps, this is fixed!
