### ISSUE TITLE
[Windows] The xbox controllers do not respond if the computer has been remote controlled by the 'mstsc.exe'.

### ISSUE THREAD

**Issue by yanyu-xww** [libsdl-org/SDL#7759]
As the title, if the computer has been controlled by the 'mstsc.exe', my Xbox controllers do not return any events except 'SDL_EVENT_JOYSTICK_ADDED' and 'SDL_EVENT_JOYSTICK_REMOVED'. 
I can only restart the computer to solve this problem.

**Comment by yanyu-xww** [comment]
Sorry,  it seems to be some time difference between us. It doesn't work

**Comment by yanyu-xww** [comment]
After I replied to your message, I found that it now has some returns, but it has a big delay.

**Comment by yanyu-xww** [comment]
If I close the connection, xbox controllers also do not have any response except ‘LT’ and 'RT'.

**Comment by slouken** [comment]
I am able to reproduce this, thanks!

**Comment by yanyu-xww** [comment]
Thanks, the first issue has been solved. But the second problem remains. And now it do not have any response including ‘LT’ and 'RT'. You can reproduce it by "Disconnect all Xbox controllers -> Activate the Remote Desktop -> Close the Remote Desktop -> Connect an Xbox controller - Reproduce".

**Comment by slouken** [comment]
I can reproduce this as well. It's crazy, the WM_INPUT messages just stop being delivered if Remote Desktop has connected.

**Comment by yanyu-xww** [comment]
No, it seems introduced for a long time. I have tested Win10 19H2 and Win11 22H2. They can all reproduce this. And I cannot reproduce it with any other types of controllers. May an XBox controller bug? I will ask them for help.

**Comment by yanyu-xww** [comment]
I consulted the technical support of Microsoft and they initially judged it is a bug.

**Comment by yanyu-xww** [comment]
They can finally reproduce the problem and are looking for more information.
You can see the progress here: https://forums.xboxlive.com/questions/152665/windows-the-xbox-controllers-do-not-respond-if-the.html

**Comment by Squall-Leonhart** [comment]
Also https://github.com/microsoft/GDK/issues/28

**Comment by slouken** [comment]
Was there any resolution on Microsoft's side?

**Comment by Squall-Leonhart** [comment]
I have heard there is some back and forth dialog in the Xbox Dev Forum report, but am not privy to it.

**Comment by slouken** [comment]
I'm going to close this here, and hopefully Microsoft will have a fix coming.

**Comment by Squall-Leonhart** [comment]
Microsoft wants the WGI Redist from https://www.nuget.org/packages/Microsoft.GameInput/2.0.26100.5334 tested.

**Comment by Squall-Leonhart** [comment]
Just affirming this is not fixed, despite microsofts insistence lol.
