### ISSUE TITLE
CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS doesn't work properly with SDL

### ISSUE THREAD

**Issue by radiokilcat** [libsdl-org/SDL#7763]
Hi! 
I've been encountering an issue when trying to build a DLL project that uses SDL3 as a shared lib, included as a git submodule. 

I tried to set  `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)` in my root cmake, to export all my dll functions and classes, but in this case i got bunch of linker errors, finally i figured out that SDL can't find MSVC runitme libs. 

If i don't use this flag and just `__declspec(dllexport)` all my functions and classes, it seems ok. 
Is it SDL3 problem, or using this cmake option is not recommended?

**Comment by madebr** [comment]
I'll look into this.
Perhaps we need to explicitly disable this property.

**Comment by madebr** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/ffcd1c0c26b63c2824050651dfe2e3c67a3de0e9 (SDL3) and https://github.com/libsdl-org/SDL/commit/8908d16285a0ee374b81553aabc61e0d0dc75bd7 (SDL2)
Also added it to 2.28.2
