### ISSUE TITLE
SDL2 Window larger than desktop in Win10 when UI scale > 100%

### ISSUE THREAD

**Issue by dacobi** [libsdl-org/SDL#7767]
I have a problem with a program where the window will start larger than the desktop in Win10 when Windows UI scale is larger than 100%

I won't post a screenshot since the entire screen is just the background color of my program.

The problem can be "fixed" with a manifest file telling Windows not to scale the program, but I would like to find a solution where the program can still be scaled by Windows?

I've tried adding SDL_WINDOW_ALLOW_HIGHDPI to the SDL window flags along side the manifest, but it doesn't have any effect.

The only thing I've found to work is to set the Window size very small.

Is there another/better solution?

I guess what I'm looking for is a way to choose if Windows will scale the program.
Right now it will never scale when the manifest file is linked in and always scale without it.

**Comment by slouken** [comment]
We've done a lot of work in SDL 3 to address high DPI situations and the conclusion we came to is that, for this and many other reasons, the best way to handle this is for the application do its own scaling as needed. There were several APIs that were added to make this easier:
https://github.com/libsdl-org/SDL/blob/main/docs/README-highdpi.md
