### ISSUE TITLE
Bazel build support

### ISSUE THREAD

**Issue by sircmpr** [libsdl-org/SDL#7769]
Hi there, user of SDL for a long time, just wanted to pop in and ask if it would make sense to have native [Bazel](https://bazel.build/) build system support inside SDL2?

I do most of my hobby development using SDL (unfortunatley nothing on GitHub :( ), and I would like to have native support for Bazel.

If so, give me a shout, I will do the contributions for it.

**Comment by slouken** [comment]
We just removed autotools support for SDL 3.0 and in general are trying to reduce the number of build systems we have to maintain, so I don't think we'd add it to the main repository.

That said, you're welcome to submit a PR and we'll park it here so other people can find and use it, if you want.

**Comment by wpieterse-me** [comment]
I understand, not everybody will use it.

Bazel supports importing external repositories, either via Git or tarball. Maybe I can create a GitHub repository referencing SDL, exporting it via Bazel for users who wish to use it like that?

**Comment by slouken** [comment]
Sure!
