### ISSUE TITLE
[macOS] Improve SDL_WINDOW_FULLSCREEN by removing the blanking window

### ISSUE THREAD

**Issue by RustyMoyher** [libsdl-org/SDL#7776]
SDL_WINDOW_FULLSCREEN_DESKTOP is a _great_ solution for some games, but it doesn’t fit everything. You can’t set the monitor refresh rate and resolution. Some games prefer the refresh rate to match the logic update. This seems more needed now too, since many mac laptops now ship with "ProMotion” 120Hz displays.

SDL_WINDOW_FULLSCREEN on mac has a few drawbacks:
- Cannot use CMD + Tab to switch applications
- Can’t see any OS-level overlays like the application switcher
- Can’t switch away to a crash or a breakpoint when a debugger is attached

This can be fixed by removing the “blanking window”.

1. In SDL_cocoamodes.m modes remove the blanking window from `Cocoa_SetDisplayMode()`:

```
int Cocoa_SetDisplayMode(SDL_VideoDevice *_this, SDL_VideoDisplay *display, SDL_DisplayMode *mode)
{
    SDL_DisplayData *displaydata = (SDL_DisplayData *)display->driverdata;
    SDL_DisplayModeData *data = (SDL_DisplayModeData *)mode->driverdata;
    CGDisplayFadeReservationToken fade_token = kCGDisplayFadeReservationInvalidToken;
    CGError result = kCGErrorSuccess;

    /* Fade to black to hide resolution-switching flicker */
    if (CGAcquireDisplayFadeReservation(5, &fade_token) == kCGErrorSuccess) {
        CGDisplayFade(fade_token, 0.3, kCGDisplayBlendNormal, kCGDisplayBlendSolidColor, 0.0, 0.0, 0.0, TRUE);
    }

    if (data == display->desktop_mode.driverdata) {
        /* Restoring desktop mode */
        SetDisplayModeForDisplay(displaydata->display, data);
    } else {
        /* Do the physical switch */
        result = SetDisplayModeForDisplay(displaydata->display, data);
    }

    /* Fade in again (asynchronously) */
    if (fade_token != kCGDisplayFadeReservationInvalidToken) {
        CGDisplayFade(fade_token, 0.5, kCGDisplayBlendSolidColor, kCGDisplayBlendNormal, 0.0, 0.0, 0.0, FALSE);
        CGReleaseDisplayFadeReservation(fade_token);
    }

    if (result != kCGErrorSuccess) {
        CG_SetError("CGDisplaySwitchToMode()", result);
        return -1;
    }
    return 0;
}
```

2. In SDL_cocoawindow.m change `[data.nswindow setLevel:CGShieldingWindowLevel()]` to `[data.nswindow setLevel:NSMainMenuWindowLevel + 1]`. Do this in two places: `Cocoa_SetWindowFullscreen()` and `Cocoa_SetWindowMouseGrab()`. This is what GLFW uses for its fullscreen mode.

3. In the application, set SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS to “0”. By default the hint is set to “auto”. Perhaps this part isn’t necessary, but it feels much better to me when switching windows.

One issue: I found a rendering bug when using CMD + Tab with the SDL 2D Renderer. A flickering empty line is sometimes visible in the OS-level task switcher. OpenGL doesn’t have this issue.

![sdl_2d_renderer_task_switcher_bug](https://github.com/libsdl-org/SDL/assets/775602/9ade27f7-08a5-48dd-b3d4-2791bb35b331)

I’m not familiar with the 2D Renderer. Maybe this was always happening behind the blanking window? Maybe this is fixable? I saw the flickering in SDL 2.26.5 with these changes.

Perhaps there should be an SDL Hint to enable/disable the blanking window?

**Comment by slouken** [comment]
What happens if you CMD+Tab after setting the display resolution to 640x480 in this new model?

**Comment by slouken** [comment]
I think in general the minimizing on focus loss has the best behavior on macOS.

The flickering you're seeing is metal rendering directly to the screen, interleaved with the desktop also rendering to the screen. There's no compositing happening in this case because you've requested fullscreen mode rendering. I believe OpenGL is always composited (at a performance cost) so that doesn't have the same issue. On my system I see flicker across the bottom task bar, as well as over notifications.

I went ahead and merged your change, as I think it's an improvement over the current behavior on macOS. Thanks!
