### ISSUE TITLE
Are the Famicom NSO controllers supported?

### ISSUE THREAD

**Issue by Bitwolfies** [libsdl-org/SDL#7787]
Support for the NES variant was added a long time ago, but it's unclear if the Famicom variant is supported. One of the two controllers in the pack has a microphone which is a fairly large difference. Just wondering if its supported since I have a set on the way and once arrived can contribute any info needed to get them in if they're not already. Thanks!

**Comment by slouken** [comment]
If they don't work out of the box, I can help you get them set up.

**Comment by slouken** [comment]
Usually controller microphones show up as audio devices to the OS.

**Comment by slouken** [comment]
Can you apply this patch to SDL, and then build and run the testgamepad test program? If you're having trouble with that, go ahead and send me e-mail at slouken@libsdl.org and we can schedule a Zoom call to walk through the process.

```diff
diff --git a/src/joystick/hidapi/SDL_hidapi_switch.c b/src/joystick/hidapi/SDL_hidapi_switch.c
index 438c9c62c..9a184f492 100644
--- a/src/joystick/hidapi/SDL_hidapi_switch.c
+++ b/src/joystick/hidapi/SDL_hidapi_switch.c
@@ -591,6 +591,7 @@ static SDL_bool BReadDeviceInfo(SDL_DriverSwitch_Context *ctx)
         if (WriteSubcommand(ctx, k_eSwitchSubcommandIDs_RequestDeviceInfo, NULL, 0, &reply)) {
             // Byte 2: Controller ID (1=LJC, 2=RJC, 3=Pro)
             ctx->m_eControllerType = CalculateControllerType(ctx, (ESwitchDeviceInfoControllerType)reply->deviceInfo.ucDeviceType);
+SDL_Log("CONTROLLER TYPE: %d\n", ctx->m_eControllerType);

             // Bytes 4-9: MAC address (big-endian)
             SDL_memcpy(ctx->m_rgucMACAddress, reply->deviceInfo.rgucMACAddress, sizeof(ctx->m_rgucMACAddress));

```

**Comment by slouken** [comment]
It's in the test directory. It's easier to build with Visual Studio or if you're using CMake you can pass `-DSDL_TESTS=ON` to build the tests as well.

**Comment by slouken** [comment]
If you're not running in Visual Studio you may need to get [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview) to see the debug output, but just run testgamepad, then connect the left controller, disconnect it, then connect the right controller, and copy the debug output here.

Thanks!

**Comment by slouken** [comment]
Oh, if you're on Linux it's easier, just `cd $(dirname $(find . -name testgamepad)) && ./testgamepad`

**Comment by slouken** [comment]
Can you update code and see if they're recognized properly?
This change should have what you need: https://github.com/libsdl-org/SDL/commit/baa9c57581490bd9cdefabb213e7cb6d0c30b296

**Comment by slouken** [comment]
> (Side note, could you also tell me the uninstall command for this build of sdl? Thanks!)

If you haven't done `make install`, it isn't installed, you can just delete the SDL directory. If you have done `make install`, then `make uninstall` should take care of uninstalling it.

**Comment by slouken** [comment]
Thanks! I hope you feel better soon!
