### ISSUE TITLE
Mobapad M073 (NS Pro Variant) no more works properly since SDL 2.26

### ISSUE THREAD

**Issue by eUnisk** [libsdl-org/SDL#7788]
I'm a Yuzu user. Their latest release from EA channel starts to use SDL 2.26.5 instead of 2.0.18. I just found that my controller (Mobapad M073, an NS Pro Variant) no more works properly after that. 

By "not working properly" I mean in Yuzu it can no more detect gyro, and AB and XY buttons are switched, like when I press A, showing B. Somehow I feel the controller is treated like an Xbox controller. 

To make sure the issue is only related to SDL.dll I have made some simple tests. 

- From the folder of the new Yuzu (EA 3645) that the controller is not working, replace SDL.dll with the old version 2.0.18. And the controller works again.
- From the folder of the older Yuzu (EA 3638) that the controller is working, replace SDL.dll with the new version 2.26.5 and the controller is no more working. 
- I tested a few SDL releases and can confirm my controller lost SDL support since 2.26.0

I do hope my controller can work again with the latest SDL. Please let me know how can I assist.

**Comment by eUnisk** [comment]
> Can you run testgamecontroller and attach the debug output? I'd like to see what SDL thinks the controller is.

Could you explain more about how to do it? I can see a testgamepad.c from the test folder. Is that the one I should use? I don't really know how to run it. I use windows 11.

**Comment by slouken** [comment]
You can install the Microsoft Visual Studio C++ development environment and open VisualC\SDL.sln and build and run testgamepad directly from there.

If you aren't familiar with development on Windows, send me e-mail at slouken@libsdl.org and we can schedule a Zoom call to walk you through the process.

I've also ordered the controller, so I should be able to test this soon too.

**Comment by eUnisk** [comment]
> 

Thanks! I'll google it and give it a try.

**Comment by eUnisk** [comment]
> You can install the Microsoft Visual Studio C++ development environment and open VisualC\SDL.sln and build and run testgamepad directly from there.
> 
> If you aren't familiar with development on Windows, send me e-mail at [slouken@libsdl.org](mailto:slouken@libsdl.org) and we can schedule a Zoom call to walk you through the process.
> 
> I've also ordered the controller, so I should be able to test this soon too.

I installed VS Studio 2022 community edition. Cloned https://github.com/libsdl-org/SDL.git and run debug on tests\testgamepad. A controller showed up and pressed some buttons, looks fine, keys are not switched. But there's no way to tell if the gyro is working.

And here is the info I copied from the Output window (showing output from: debug).

See if this is the info you need. But it seems to use sdl3.dll instead of sdl2.

[debug.txt](https://github.com/libsdl-org/SDL/files/11684650/debug.txt)

**Comment by slouken** [comment]
That's interesting. It does show that it's acting like a Nintendo Switch Pro controller, but the HIDAPI driver (which supports gyro) isn't picking it up. Can you add `#define DEBUG_HIDAPI` to the top of SDL_joystickhidapi.c and resend the debug output?

**Comment by eUnisk** [comment]
> SDL_joystickhidapi.c

I couldn't find SDL_joystickhidapi.c, could you let me know where should I locate the file? There's SDL_joystick.c and there's SDL_hidapi.c.

**Comment by eUnisk** [comment]
> #define DEBUG_HIDAPI

Not sure if I did it right or not, see attached. 

![SDL_hidapijoystick c](https://github.com/libsdl-org/SDL/assets/109562613/87e6de79-990c-4188-b746-8f268d37f643)


[debug 09 jun.txt](https://github.com/libsdl-org/SDL/files/11697662/debug.09.jun.txt)

**Comment by slouken** [comment]
That looks right, but I’m not seeing the output I expect. Can you send me email and we can coordinate a time for a Zoom debugging session?

**Comment by slouken** [comment]
I just received this controller and plugged it into Windows, and it shows up as an Xbox 360 controller, complete with the home button bringing up the Microsoft Game Bar.

I double checked on a Linux system, and sure enough, it's enumerating over USB as an Xbox 360 controller:
```
[   64.416581] usb 1-1.2: new full-speed USB device number 5 using berlin-ehci
[   64.508569] usb 1-1.2: New USB device found, idVendor=045e, idProduct=028e
[   64.508582] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   64.508590] usb 1-1.2: Product: Controller
[   64.508596] usb 1-1.2: Manufacturer: ZhiXu
[   64.523499] input: Generic X-Box pad as /devices/soc.0/f7ee0000.usb/usb1/1-1/1-1.2/1-1.2:1.0/input/input3
```

The manual online seems to confirm this:
https://www.tgbus.com/news/156229
Note it showing up as an Xbox 360 controller in the Steam Big Picture screenshot.

The controller does have A to the east and B to the south, like Nintendo controllers. Is there a trick to having this show up as a Nintendo Switch Pro controller?

**Comment by eUnisk** [comment]
> I just received this controller and plugged it into Windows, and it shows up as an Xbox 360 controller, complete with the home button bringing up the Microsoft Game Bar.
> 
> I double checked on a Linux system, and sure enough, it's enumerating over USB as an Xbox 360 controller:
> 
> ```
> [   64.416581] usb 1-1.2: new full-speed USB device number 5 using berlin-ehci
> [   64.508569] usb 1-1.2: New USB device found, idVendor=045e, idProduct=028e
> [   64.508582] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
> [   64.508590] usb 1-1.2: Product: Controller
> [   64.508596] usb 1-1.2: Manufacturer: ZhiXu
> [   64.523499] input: Generic X-Box pad as /devices/soc.0/f7ee0000.usb/usb1/1-1/1-1.2/1-1.2:1.0/input/input3
> ```
> 
> The manual online seems to confirm this: https://www.tgbus.com/news/156229 Note it showing up as an Xbox 360 controller in the Steam Big Picture screenshot.
> 
> The controller does have A to the east and B to the south, like Nintendo controllers. Is there a trick to having this show up as a Nintendo Switch Pro controller?

Hi mate,

The controller comes with a USB dongle, when connect using the dongle or wired plugged via USB it is in Xbox mode. 

When connected via normal Bluetooth (not through the dongle comes with it) it will be in NS pro controller mode, showing as a pro controller. 

To pair it, just add new device in Bluetooth settings and then press and hold the "wifi" icon button of the controller until the home button blinks in blue.

**Comment by slouken** [comment]
Ah, that was the info I needed. I'm able to reproduce this, and am investigating. Thanks!

**Comment by slouken** [comment]
Fixed! :)

**Comment by eUnisk** [comment]
> Fixed! :)

Thank you so much! So I just wait for a new release?

**Comment by slouken** [comment]
Yep! We're working on the SDL 2.28.0 release and it should be available soon.

**Comment by eUnisk** [comment]
Great work! Appreciate it.
