### ISSUE TITLE
Renderer is made for no reason (Linux)

### ISSUE THREAD

**Issue by yolowex** [libsdl-org/SDL#7793]
this is an issue redirection, originated from [pygame-ce](https://github.com/pygame-community/pygame-ce/issues/2190).
every detail about my OS and my sdl version is available at the link I provided, but I can put some extra details here if you need them.

```c
#include <stdio.h>

#define SDL_MAIN_HANDLED

#include "SDL.h"

// my compile command
// gcc test.c -ISDL2 -lsdl2 -L.

#define SDL_ERROR                            \
    printf("SDL error: %s", SDL_GetError()); \
    exit(1);

int main()
{
    SDL_Init(SDL_INIT_EVERYTHING);

    SDL_Window *win = SDL_CreateWindow("test", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 500, 500, 0);
    if (!win)
    {
        SDL_ERROR
    }

    SDL_Surface *screen = SDL_GetWindowSurface(win);
    if (!screen)
    {
        SDL_ERROR
    }

    SDL_Renderer *renderer = SDL_GetRenderer(win);
    printf("renderer = %p\n", renderer);

    SDL_Quit();

    printf("Finished.\n");
}
```

When I run it, I get this:
```
└─$ ./main
renderer = 0x5648f705f330
Finished.
```
this is a bad thing right?

could it be that some program in my OS has created an sdl renderer, so it's always occupied?.

**Comment by yolowex** [comment]
> SDL_GetWindowSurface() is calling SDL_CreateWindowFramebuffer() with create a SDL_Renderer underneath...
> 
> you can call SDL_SetHint(SDL_HINT_FRAMEBUFFER_ACCELERATION, "false"); to disable the renderer creation, but not sure if you app will still runs correctly ...

I did that and now it returns 
```
└─$ ./main
renderer = (nil)
Finished.
```

But why is this happening only on my machine? other people don't have this problem.

**Comment by 1bsyl** [comment]
not sure exactly, sometime the renderer is created underneath if you want to use a  framebuffer interface.
I'd say, it depends on the platform you're using: linux, win, mac, rpy, etc.

see the code that creates it or not:
https://github.com/1bsyl/SDL/blob/main/src/video/SDL_video.c#L2970

**Comment by yolowex** [comment]
> @yolowex : please check the PR above

I don't know how to compile SDL to see if it works, but I can try

**Comment by 1bsyl** [comment]
the patch is for latest SDL3 btw

**Comment by yolowex** [comment]
> the patch is for latest SDL3 btw

just curious, when will SDL3 be out?

**Comment by 1bsyl** [comment]
I don't know !

**Comment by slouken** [comment]
I went ahead and provided information for the pygame folks so they can fix this on their end.
