### ISSUE TITLE
SDL properties

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#7799]
We have some cases where it would be handy to have arbitrary properties associated with objects... windows, surfaces, even hints as a global property set. This might also be useful for the new 3D API.

@libsdl-org/a-team, what do you guys think about making this an official API?

e.g.
```
SDL_Properties *SDL_CreateProperties()
int SDL_LockProperties(SDL_Properties *props);
void SDL_UnlockProperties(SDL_Properties *props);
int SDL_SetProperty(const char *name, const char *name, void *value, void (*cleanup)(void *context, void *value), void *context);
void *SDL_GetProperty(SDL_properties *prop, const char *name);
void SDL_DestroyProperties(SDL_Properties *props);
```

**Comment by icculus** [comment]
First instinct is that this feels _extremely_ heavyweight in general.

But on the other hand, once this makes sense for _one_ type of object, you might as well offer it on _every_ object, as it's just an extra NULL pointer on things that aren't using it. I had been thinking that it would be nice if most SDL objects accepted a generic pointer the app can use to hang whatever on, the way we already offer via SDL_SetWindowData(), and this is probably a safer equivalent that unrelated pieces of code can share.

Maybe what we actually need is SDL_Dictionary (or SDL_HashTable or whatever), so you can do key/value lookups as a general piece of functionality, and then various things, like SDL_Window and such, can optionally have one associated with it internally.

(And then, internally, the entire SDL_Hint system becomes a single SDL_Dictionary, but that might be taking it too far.)

**Comment by slouken** [comment]
That's essentially what I was proposing, and SDL_Dictionary seems like a good name for it. We should definitely have a locking function so accessing it can be done atomically.

**Comment by icculus** [comment]
> That's essentially what I was proposing

I just had to talk myself through it.  :)

**Comment by icculus** [comment]
Is there any reason not to just lock it internally during SDL_SetProperty, instead of having a public locking API? If there's a thing that needs to atomically set several keys at once, we can offer a second, more-complex function that accepts an array of items.

This is also an extremely good candidate for an SDL_RWLock, so it only has to block threads when something wants to change the dictionary, not look up an existing value.

**Comment by flibitijibibo** [comment]
Another +1 from me, as this could be useful for connecting arbitrary online accounts to controllers when appropriate (mostly consoles, but could be useful for a multi-user Steam instance too), as well as linking objects from one subsystem to another, without having to export new lookup functions (for example, controllers may have an SDL_StorageContainer or SDL_AudioDevice object linked to it).

**Comment by icculus** [comment]
> without having to export new lookup functions

Oh god, now I'm wondering how much we can cut down the public API by just exposing properties through this mechanism.  :)

**Comment by slouken** [comment]
> Is there any reason not to just lock it internally during SDL_SetProperty, instead of having a public locking API? If there's a thing that needs to atomically set several keys at once, we can offer a second, more-complex function that accepts an array of items.
> 
> This is also an extremely good candidate for an SDL_RWLock, so it only has to block threads when something wants to change the dictionary, not look up an existing value.

We definitely should lock internally when setting and getting a property, but I think people will potentially want to lock it for more complex operations or series of operations, especially when passing objects as values. The locking function could take a read/write flag so we can use rwlocks. :)

**Comment by slouken** [comment]
> Oh god, now I'm wondering how much we can cut down the public API by just exposing properties through this mechanism. :)

Right?? :D

**Comment by slouken** [comment]
My initial use case for this was the window surface, but it could also be used for the renderer associated with a window, and all sorts of user data associated with SDL objects. :)

**Comment by 1bsyl** [comment]
+1 sounds a useful feature.
but I think this should be used carefully for SDL internals.  Otherwise we could start to want to replace all struct members by an entry in a dictionary.

**Comment by Kontrabant** [comment]
+1 as well.
Being able to tie arbitrary data to window objects has come in handy in several cases, so there are undoubtedly uses for this functionality beyond that.

**Comment by slouken** [comment]
@icculus, I'm running into a use case for this again, what do you think about adding properties to arbitrary objects in SDL?

**Comment by icculus** [comment]
I'm totally on board, I was waiting for you to implement it.  :) 

Let me know if I should start it though!

**Comment by slouken** [comment]
lol, okay. I'll look at doing it soon.

**Comment by slouken** [comment]
@icculus, I remember now, this was waiting on your hashtable implementation. Can you bring that over as an isolated change for SDL3?

**Comment by icculus** [comment]
Oh, yeah, I'll slide that over shortly.

**Comment by icculus** [comment]
Okay, include SDL_hashtable.h, and make a hashtable that maps strings to pointers:

```c
// this is called when something is removed from the hashtable, to free it.
static void NukeProperty(const void *key, const void *value, void *data)
{
    SDL_free((void* )key);  // free the string, which is a simple SDL_strdup().
    // we don't free the `value` because we don't own it; it's a generic pointer the app owns.
}

// hashing a string and matching it are so common, those implementations are built in.
// the first arg is userdata, but we don't need it here.
// the second arg is the bucket size of the hash. 16 might be too high for something that will only have a couple properties.
// the last arg is whether inserting something that already exists in the hash stacks a new copy or refuses to add a duplicate (so, false, here).
SDL_HashTable *myhash = SDL_CreateHashTable(NULL, 16, SDL_HashString, SDL_KeyMatchString, NukeProperty, SDL_FALSE);
```

...then you add things to the hash like this:

```c
if (!SDL_InsertIntoHashTable(myhash, SDL_strdup("Some Property Name"), generic_pointer)) {
    // insert failed; either out of memory or the key already exists
}
```

...find things like this:

```c
void *generic_pointer = NULL;
if (!SDL_FindInHashTable(myhash, "Some Property Name", &generic_pointer)) {
    // item was not found in the hash
} else {
    // item was found in the hash and stored in `generic_pointer`
}
```

...when done:

```c
SDL_DestroyHashTable(myhash);
```


...if you need to iterate over all keys in the hash:

```c
void *iter = NULL;
void *key = NULL;
while (SDL_IterateHashTableKeys(myhash, &key, &iter)) {
     const char *keystr = (const char *) key;  // we know this is a string because we made this hashtable, but you don't have to store strings!
     void *value = NULL;
     SDL_FindInHashTable(myhash, key, &value);
     SDL_Log("key='%s', value=%p", key, value);
}
```

**Comment by icculus** [comment]
(And feel free to change the hashtable API however you like, I don't feel precious about it.)

**Comment by slouken** [comment]
It's tempting to add a set of functions to modify properties and then add a way to query the properties object for a given SDL object, but you run into problems where someone might destroy the object while the properties are being modified. The alternative is to create a set of Get/Set property functions for every object that supports them.

That might be okay, but does anyone have other thoughts?

**Comment by slouken** [comment]
Ah, we can make the properties be an ID, and we can manage them internally as needed.

**Comment by slouken** [comment]
@icculus, that ended up being pretty clean with the new hashtable functionality. Check it out! :)

**Comment by sam20908** [comment]
If I understand correctly, this essentially means an optional hash table for every object?

**Comment by icculus** [comment]
> If I understand correctly, this essentially means an optional hash table for every object?

Probably not every object, but many of the major ones, so apps can hang arbitrary data off various SDL things.

Right now we store space for a single generic pointer on SDL_Window for an app, via SDL_SetWindowData(). Now they'll be able to assign key/value pairs to this and other important objects.

Presumably for objects not using properties, this is just a single extra pointer set to NULL.

**Comment by sam20908** [comment]
> Oh god, now I'm wondering how much we can reduce the public APIs by exposing properties through this mechanism. :)

I still don't really understand the benefit of this. Does this mean we have to memorize the property names for the hash table to set a property (not to mention, that the hash table is a big overhead)? Sorry if I am not seeing the big picture.

**Comment by icculus** [comment]
> Does this mean we have to memorize the property names for the hash table to set a property (not to mention, that the hash table is a big overhead)?

I think this is for setting your own key/value pairs on various objects, if you want to, not to control core SDL functionality.

**Comment by 1vanK** [comment]
Passing SDL_PropertiesID to SDL_DestroyProperties() as reference allows set the variable to zero.

It would be useful to have predefined constants for strings "title", "x", "y", etc. This will reduce the chance of typos.
