### ISSUE TITLE
Clipboard testautomation failing

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7800]
Clipboard testautomation is currently failing: an assert that abort the whole tests. Not really worried about the clipboard, but this prevent checking all other in 1 shot. 2.7 and 2.8 are failing (linux / x11).

Pinging @LiquidityC because of last clipboard modification https://github.com/libsdl-org/SDL/pull/7652
( but not sure if this is related at all ) 
could you give a try and maybe you've a quick fix for it ?

**Comment by LiquidityC** [comment]
I will take a peek tonight or tomorrow.

**Comment by LiquidityC** [comment]
Checked the tests for wayland and x11. Both had problems cause by me. Sorry. Missed the "testautomation" part when I submitted these PRs.

**Comment by 1bsyl** [comment]
no problem ! thanks a lot for fixing !
