### ISSUE TITLE
`SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE` doesn't respect DPI scaling on windows

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#7802]
## Steps to reproduce

0. Have a display where DPI scaling != 100% (higher scaling makes it easier to see the difference)
1. Set `SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE` to `true`, via envvar or hint
2. Run `testwm` (SDL built-in test)
3. Move the mouse up and down at a constant rate, over an area where you can see (eg. look at the highlighted display mode)
4. Toggle between relative and non-relative mouse mode (<kbd>Ctrl</kbd>+<kbd>R</kbd>)

## Expected behaviour

The cursor should move (roughly) the same distance in both modes.

## Actual behaviour

The mouse will move slower in relative mode (2x slower on a display with 200% scaling).

https://github.com/libsdl-org/SDL/assets/16479013/6cf9bad8-d621-4a7e-96c2-1cfd6d9d8af4

## Platform
- Windows 11 22H2
- SDL3 current `main`, at commit 125e7420ecd2b0d1847aef804f53e614fbc68253

## Remarks

I'm not really sure how mouse DPI scaling should behave when not using `SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE`. Also I have not tested this in 3D applications, only on the 2D example given. Not sure what feels better / is more correct.
Also I think it's weird that the display's `pixel_density` always shows `1` on windows (this display is most certainly using 200% scaling, as evident by taskbar and titlebar size).

**Comment by Susko3** [comment]
[`SDL_HINT_MOUSE_RELATIVE_SCALING`](https://wiki.libsdl.org/SDL2/SDL_HINT_MOUSE_RELATIVE_SCALING) used to exist, but it seems to be removed with SDL3.

**Comment by slouken** [comment]
Pixel density and content scale are different, FYI. Pixel density comes into play when the window coordinates and pixels are not 1:1, e.g. macOS. Content scale comes into play when the pixel density is 1.0, but the user has requested content scaling on the display, e.g. 200%.

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by Susko3** [comment]
> Pixel density and content scale are different, FYI. Pixel density comes into play when the window coordinates and pixels are not 1:1, e.g. macOS. Content scale comes into play when the pixel density is 1.0, but the user has requested content scaling on the display, e.g. 200%.

Is the content scale of the display exposed in SDL?

**Comment by slouken** [comment]
Yes, see https://github.com/libsdl-org/SDL/blob/main/docs/README-highdpi.md for more details.
