### ISSUE TITLE
Disabling the CPUinfo system utterly breaks the audio subsystem

### ISSUE THREAD

**Issue by zeltermann** [libsdl-org/SDL#7809]
See https://github.com/yuzu-emu/yuzu/pull/10739.

https://github.com/libsdl-org/SDL/blob/4e0f94ea7d58d4a1aac624421d73110232df3efd/src/audio/SDL_audiotypecvt.c#L939C1-L978

**Comment by icculus** [comment]
Didn't we _just_ fix this? Something about it could land in a scenario where it didn't hit the scalar fallback.

I'll check.

**Comment by zeltermann** [comment]
> Didn't we just fix this?

Yes, https://github.com/libsdl-org/SDL/pull/7464, but it hasn't landed in a release yet.

> Also, can we make it so things like the cpuinfo subsystem can't be disabled?

Yes, please, that will probably fix a lot of bugs. The code I saw in SDL's audio system is already self-contradicting enough as-is, with some parts using `SDL_HasX` and some parts using compiler flags.
