### ISSUE TITLE
Using Mono For SDL2 On Android

### ISSUE THREAD

**Issue by cool-dev-guy** [libsdl-org/SDL#7820]
Since Game engines like Unity uses mono to run on android and the high performance got as a result of it,Is it possible to use SDL without using Java,(ie. using C# and mono with C++ using cpp.so files?)
```C#            ----------> CIL ---> Native machine code(using Mono)
C# + C++(.so) ----------> CIL ---> Native machine code(using mono)
        |____________________________________|
  (c++ compiled)                    (c++ executed with C#)

Instead of:
Java + C++(.so) ------------------------>JVM/ART
                  |_________________________|
        (ndk compiles to .so)    (JNI calls the cpp functions)
```
- **`This concept may be entirely wrong,But still if it works...Does that mean there will be a performance increase or any other perks?`**

**Comment by TheComputerGuy96** [comment]
Or even better:
Why not drop all the Java code (so SDL applications don't have to deal with classes.dex again)?

rawdrawandroid has examples on how to do that: https://github.com/cnlohr/rawdrawandroid

**Comment by cool-dev-guy** [comment]
Does currently rawdrawandroid support SDL

**Comment by slouken** [comment]
No, there's a bunch of Java code that would need lots of work to be reimplemented in C++, and then couldn't be extended by other people using Java or Kotlin.
