### ISSUE TITLE
Support for system tray icon?

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#7822]
Would it be useful to support system tray icons within SDL?

----------

<details>
<summary>Screenshots for Windows, macOS and Ubuntu</summary>

Windows:
<img src="https://github.com/libsdl-org/SDL/assets/66701383/78d8e64e-7c28-4d24-acd7-43b5a2ecd553" alt="Windows system tray" width="300"/>

macOS:
<img src="https://github.com/libsdl-org/SDL/assets/66701383/8f62d4b2-fa1b-479f-a58f-6222d535c63a" alt="macOS system tray" width="300"/>

Ubuntu:
<img src="https://github.com/libsdl-org/SDL/assets/66701383/fc7ba218-24df-486a-9957-f8d242457238" alt="Ubuntu system tray" width="300"/>
</details>

Some potentially useful repositories:
- https://github.com/Soundux/traypp
- https://github.com/zserge/tray

**Comment by icculus** [comment]
I want to say no here, because this probably either gets watered down to an array of strings that represent possible menu items, or it starts really getting into the specifics of various OSes in ways we don't want to expose in the API.

**Comment by smcv** [comment]
The API for "system tray" icons on Linux is [a bit of a disaster area](https://blog.tingping.se/2019/09/07/how-to-design-a-modern-status-icon.html), even if we assume that a "system tray" is even desirable, which not everyone agrees;  so supporting anything non-trivial in a portable way is going to be a struggle.

(Link is from 2019, there has been [more](https://pagure.io/fedora-workstation/issue/264) [recent](https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84) [work](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/54) but nothing very conclusive)

**Comment by slouken** [comment]
Yeah, I think this is outside the scope of SDL for now.

**Comment by Semphriss** [comment]
Generally speaking, what sorts of idea should I consider worth suggesting to add in SDL?

I have a few changes I'm making for my personal projects and I'd like to contribute them back, but I don't want to flood the issue tracker with my ideas. How should I decide what to share and what not to share?

**Comment by slouken** [comment]
Feel free to share and we'll let you know if we think it's appropriate. Even if we don't include it in mainline, having it here will let other people find your changes and use them.

**Comment by Semphriss** [comment]
For future reference, I managed to implement system trays on Windows, macOS, and Unix.

The source is available at https://github.com/Semphriss/SDL/tree/tray

![Windows screenshot](https://github.com/user-attachments/assets/c966c20b-34b4-45e1-a59f-a1a19411e2d4)
![macOS screenshot](https://github.com/user-attachments/assets/3138d220-d96c-4ce4-8728-ea5fc9e5f931)
![Unix screenshot](https://github.com/user-attachments/assets/b7ba5d35-cdfd-41b1-a0bc-c1fccfc18461)

It supports:
- Custom tray icon (I used `test/trashcan.bmp` as an example)
- Tooltip on the tray icon
- Menus including:
  - Items
  - Disabled items
  - Checkboxes
  - Separators
  - Submenus
  - Custom callbacks on any item

I still have a few rough edges to iron out, but it generally works well at the moment. If anybody would need help to use it, please let me know!

**Comment by slouken** [comment]
This actually looks pretty good! I'm going to go ahead and reopen this.

**Comment by Semphriss** [comment]
Should I open it as a pull request?

**Comment by slouken** [comment]
> Should I open it as a pull request?

Sure!

**Comment by slouken** [comment]
One thing I expected to see was a show/hide or some way of letting the system know you're done creating the menus. It looks like right now you can keep adding entries over time and they dynamically show up, and if you need to remove one, you have to destroy the tray and start over.

**Comment by icculus** [comment]
> This actually looks pretty good! I'm going to go ahead and reopen this.

Nothing changes minds faster than working code.  :)
