### ISSUE TITLE
Proactive C runtime checks

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7825]
Occasionally calls into the C runtime, instead of their SDL equivalents, slip in via pull request or just muscle memory.

Like #7824, correcting one of these.

Maybe we should put a header in, included from SDL_internal.h, that does the same thing we did for SDL3 symbols:

```c
#define strcpy Please_use_SDL_strcpy_instead
```

**Comment by slouken** [comment]
That seems like a great idea.

**Comment by 1bsyl** [comment]
trying some PR https://github.com/libsdl-org/SDL/pull/7864 
let see if this compile ...

some file, still needs the symbols somehow, or use it indirectly from macros

**Comment by 1bsyl** [comment]
closing, because this was fixed in https://github.com/libsdl-org/SDL/commit/70ccf3458701d8563f4b213b1713eafcc052e34e
