### ISSUE TITLE
evdev: Distinguish between full keyboards and devices that merely have some keys

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#7827]
In both udev and [steam-runtime-tools](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/steam-runtime-tools/input-device.h), the equivalent of `SDL_UDEV_DEVICE_KEYBOARD` is split into two:

* `KEYBOARD` is a reasonably full alphanumeric keyboard that you could use to type commands or your password;
* `HAS_KEYS` is anything that can produce keyboard events, including USB numeric keypads, Bluetooth headset volume buttons, ACPI power buttons and even a few game controllers

At the moment `SDL_UDEV_DEVICE_KEYBOARD` is basically udev's `HAS_KEYS`.

If we want to change this in SDL 3, I would suggest renaming `SDL_UDEV_DEVICE_KEYBOARD` to `SDL_UDEV_DEVICE_HAS_KEYS` and introducing a new `SDL_UDEV_DEVICE_FULL_KEYBOARD`, so that anyone porting SDL 2 code is forced to decide which one they meant.

The logic in steam-runtime-tools, and I think also udev, is that a keyboard is assumed to be a full alphanumeric keyboard if it has at least Escape, 0-9 and Q-D, so the end of `SDL_EVDEV_GuessDeviceClass` would change to something like this:

```
    keyboard_mask = 0xFFFFFFFE;
    if ((bitmask_key[0] & keyboard_mask) != 0) {
        devclass |= SDL_UDEV_DEVICE_HAS_KEYS;
    }

    if ((bitmask_key[0] & keyboard_mask) == keyboard_mask) {
        devclass |= SDL_UDEV_DEVICE_FULL_KEYBOARD;
    }
```

**Comment by smcv** [comment]
(As discussed briefly on #7826)

**Comment by slouken** [comment]
Looking more closely I think that SDL's current behavior is intended. I think we wanted to support things like headsets with additional multimedia keys and so forth. Right now, if you plug in a controller that generates keys as well as gamepad input, we'll send the keys as keyboard input to the application. I don't think there's any reason to prevent that.

**Comment by slouken** [comment]
Also, the SDL udev support is entirely internal, there's no SDL 2 application code that would be affected by any change we make here.

**Comment by smcv** [comment]
That's fine, that would be `HAS_KEYS` in udev-speak. The thing that makes `KEYBOARD` more useful is for ruling out keyboards from slightly shaky heuristics, like this pseudocode:

```
if (!(flags & KEYBOARD) && weak_indication_of_being_a_gamepad) {
    do gamepad things;
}
```
