### ISSUE TITLE
Logitech Chillstream has wrong bindings

### ISSUE THREAD

**Issue by Managor** [libsdl-org/SDL#7829]
Demonstrative video: https://www.youtube.com/watch?v=WHbdRLHc_kQ
AntiMicroX config: [Chillstream.gamecontroller.amgp.txt](https://github.com/libsdl-org/SDL/files/11763305/Chillstream.gamecontroller.amgp.txt)
Device ID: 046d:cad1
In the video I have configured AntiMicroX to show what I physically press where as SDL2 Gamepad Tool is what the game sees. The physical buttons don't align with what the game gets as input. I'm hoping the included AntiMicroX config allows you to resolve this. I will be happy to provide any extra information you require.

**Comment by slouken** [comment]
What version of SDL are you testing this with? 

Support for this controller was added in https://github.com/libsdl-org/SDL/commit/71546059828af1b40b0585ab494cccf982bb3069, which is in the SDL 2.28.0 release.

**Comment by Managor** [comment]
Latest that Arch provides. Currently on version 2.28.0-1.

**Comment by slouken** [comment]
Ahhh, that makes sense. The PS3 controller support built into SDL isn't enabled on Linux. I'll take a look at that.

**Comment by slouken** [comment]
Added a Linux mapping, thanks!

**Comment by slouken** [comment]
This is in for the next Steam beta client update as well.

**Comment by Managor** [comment]
Alright. Confirming that the controller is working as intended now.

**Comment by slouken** [comment]
Great!
