### ISSUE TITLE
GameSir G4 pro is detected but no input

### ISSUE THREAD

**Issue by meirl1** [libsdl-org/SDL#7830]
Thank you for your great work!
As a Yuzu user I have a GameSir G4 pro, it used to work decently until version 2.0.22.
With version 2.24 the controller is detected but no input, it also causes Yuzu be less responsive.
Since 2.26 the controller is still detected with no input but without the responsiveness issues.

Some other issues I had with this controller are: 
1. Gyro wouldn't stop moving (slightly).
2. When I close Yuzu, the controller becomes unresponsive, and I had to press the reset button on the back of the controller.

Thank you
[debug_log.txt](https://github.com/libsdl-org/SDL/files/11767432/debug_log.txt)

**Comment by slouken** [comment]
This is fixed for the 2.28 release, thanks!

The controller documentation says that it supports gyro and accelerometer, but I'm not seeing any sensor data in the raw reports coming from the controller, and reading the IMU calibration fails. Maybe it's a flaw in my controller? Does the gyro work for you?

**Comment by meirl1** [comment]
Thank you
The gyro does work for me, it would drift a bit but it worked.
🙂

**Comment by slouken** [comment]
Can you grab the latest code from GitHub and see if it works for you? I’m wondering if maybe I just got a defective controller?

**Comment by meirl1** [comment]
It works! but without gyro or accelerometer.

**Comment by slouken** [comment]
Which release did it work with? I tried 2.0.22, 2.0.20, and 2.0.18, and they didn't work.

**Comment by meirl1** [comment]
Just checked again to make sure, gyro works for me with 2.0.22.
I check it with yuzu by replacing the sdl2.dll with the required release.
Maybe your controller is faulty.

**Comment by slouken** [comment]
Since I'm getting different results, could we set up a Zoom call to do remote debugging? Please send e-mail to me at slouken@libsdl.org to coordinate.
