### ISSUE TITLE
Bug: SDL_SetRelativeMouseMode() does not restore cursor position correctly

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#7840]
https://github.com/libsdl-org/SDL/assets/77922942/8d228139-6b8d-462b-9330-9ee159ec1a0f

Using Love2D 11.4 on Windows, tested both the default distribution as well as with `SDL.dll` replaced to latest release.

```lua
crosshairX, crosshairY = 0 , 0
posX, posY = 0 , 0
panning = false
function love.mousepressed( x, y, button, istouch, presses )
    if button==3 then 
       crosshairX , crosshairY = x , y
       panning = true
       love.mouse.setRelativeMode(true)
    end
end
function love.mousereleased( x, y, button, istouch, presses )
    if button==3 then 
       love.mouse.setRelativeMode(false)
       panning = false
       crosshairX , crosshairY = 0 , 0
    end
end
function love.mousemoved( x, y, dx, dy, istouch )
    if panning then 
       posX = posX + dx
       posY = posY + dy
    end
end
function love.draw()
    local w,h = love.graphics.getDimensions()
    local x,y = w/2 - posX , h/2 - posY
    love.graphics.rectangle('line',x-50,y-50,100,100)
    love.graphics.line(x,0,x,h)
    love.graphics.line(0,y,w,y)
    if panning then
       love.graphics.line(crosshairX,0,crosshairX,h)
       love.graphics.line(0,crosshairY,w,crosshairY)
    end
end
```

**Comment by Susko3** [comment]
Hmm, not sure if toggling relative mouse mode should remember/set the mouse position. I think it's best if you manually set and restore the mouse position before enabling and after disabling relative mouse mode.

**Comment by slouken** [comment]
You're moving your mouse position based on relative motion, you're not querying what SDL thinks is the mouse position. The SDL mouse position should remain in the upper right corner in your video. You can confirm that by looking at the x and y coordinates in the mousemoved handler.

**Comment by Susko3** [comment]
I understand what you're trying to do. Unfortunately for you, SDL doesn't work this way out of the box so you'll need to have a bit of special handling. Change your program to the equivalent of this C code:

```c
static SDL_Window * window;
static int saved_x, saved_y;

void setMyRelativeMouseMode(SDL_bool enable)
{
    if (enable) {
        SDL_GetMouseState(&saved_x, &saved_y);
        SDL_SetRelativeMouseMode(true);
    } else {
        // also try flipping the order of these calls.
        SDL_SetRelativeMouseMode(false);
        SDL_WarpMouseInWindow(window, saved_x, saved_y);
    }
}
```

**Comment by slouken** [comment]
I'm glad you have a solution that works for you. The SDL design came from systems where there is no absolute mouse position (it processed raw hardware deltas) and games that draw their own mouse cursor, but want the precision and unlimited motion of relative mode.

**Comment by slouken** [comment]
However, with SDL3, we have an opportunity to change that behavior. Let me mull that over for a bit.

**Comment by Susko3** [comment]
Not sure how valid your test is, as it's running in [quirks mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode). If I add `<!DOCTYPE html>` to return to no-quirks mode, it behaves differently.

The mouse and the coordinates seem to be working the same in both modes, so that kinda proves your point.

**Comment by slouken** [comment]
Just thinking this through a little bit...
* Relative mode is implemented on some platforms by warping the cursor, when low level raw input isn't available, so we can't show the cursor in this case
* Over Remote Desktop you don't get relative motion, and the OS coalesces incoming input and warping so it's really easy to accidentally move the mouse off of the window. Putting it at the center gives you the most room to get large mouse deltas.
* SDL has code internally to replicate the OS mouse acceleration curves, so for applications that do want normal mouse motion while also getting relative deltas (e.g. scrolling the map at the edge of the window), it is much easier for an application to draw a cursor at a fixed location than to try to replicate the mouse acceleration algorithm.
* SDL would have to draw the cursor in a fixed location if we wanted to not move the mouse when mouse warping is needed, and there isn't a single way for applications to get graphics on the screen. We would have to implement a drawing hook for all the different methods of getting graphics on the screen in SDL (Vulkan, OpenGL, OpenGLES, D3D9, D3D11, D3D12, etc.)

For an application to get the behavior you're asking for using the existing system is fairly easy:
* Save the mouse position before entering relative mode
* Draw the cursor at that location while in relative mode
* Process mouse motion accepting relative deltas for panning and ignoring the absolute position
* Restore the mouse position
* Leave relative mode

I think the only thing that's tricky here is getting the same cursor that the OS uses, and at least on Windows you can write code to do that. An easier approach is to have a special panning cursor that you draw when you're in this mode.

**Comment by slouken** [comment]
Well, SDL is processing relative motion and moving the cursor during relative mode (for the aforementioned scrolling map game), but we can certainly add a hint to freeze the mouse position while in relative mode.

**Comment by slouken** [comment]
> No, that's not what I meant. I meant restore it to the right spot when you _exit_ relative mode. This wouldn't affect any of the four points you raised, there really isn't any reason not to make this the exclusive behavior.

We currently move the mouse to SDL's internal mouse position when leaving relative mode, so freezing the mouse position has the effect you're asking for (I think?)

**Comment by slouken** [comment]
Let's say you have a real-time strategy game, and you're showing the cursor all the time (usually a custom cursor, based on the game state), and you're in the main map view where you can move the mouse to the edge of the screen to scroll the map. What you want to do is show the mouse at the edge of the screen, and not immediately start scrolling, but respond to additional movement beyond the edge of the screen for scrolling the map. A small movement will move the map a little bit, a large movement would move it a lot.

**Comment by slouken** [comment]
I've seen in in several games, but I don't remember which off the top of my head.
