### ISSUE TITLE
SDL_CreateTextureFromSurface does not appear to correctly respect SDL_PIXELFORMAT_INDEX1LSB

### ISSUE THREAD

**Issue by alestane** [libsdl-org/SDL#7844]
Test case at [github.com/alestane/sdl_surface_test_nff/](https://github.com/alestane/sdl_surface_test_nff/). Provided with a packed black-white bitmap, SDL_CreateTextureFromSurface treats the contents as being in MSB order even if SDL_PIXELFORMAT_INDEX1LSB is specified

Uncomment lines 41-44 of demo.cpp to manually reverse each byte before drawing.

SDL_ConvertSurface also appears to be affected.

**Comment by slouken** [comment]
Thanks for the great test case! This is fixed for SDL 2.28.
