### ISSUE TITLE
2.26.5 not working for some game pad switch pro model

### ISSUE THREAD

**Issue by lovelygfj** [libsdl-org/SDL#7845]
SDL2.dll v2.26.5 not working for some game pad (like Betop) switch pro model, no response when touch.
V2.0.18.0 works well.

**Comment by madebr** [comment]
Can you try last week's prerelease?
https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.27.1

**Comment by lovelygfj** [comment]
yes I tried, it's not working in yuzu https://github.com/yuzu-emu/yuzu

**Comment by slouken** [comment]
Are you able to debug the initialization process in HIDAPI_DriverSwitch_InitDevice() and HIDAPI_DriverSwitch_OpenJoystick() to see what's going on?

If not, can you send me e-mail at slouken@libsdl.org so we can use Zoom to do interactive troubleshooting with Visual Studio?

**Comment by slouken** [comment]
This is fixed for 2.28.1, in f168f9c81326ad374aade49d1dc46f245b20d07a and https://github.com/libsdl-org/SDL/commit/3694dabe7c16bb8e76f6f4820a1987ce16c4a3c9.
