### ISSUE TITLE
SDL3 + Android + PS5 Controller + Bluetooth = Rumble appears as a haptic device

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#7847]
One of my users of my Game Controller Tester app reported that their PS5 controller via Bluetooth doesn't support rumble. I heard mentioned here that this is to be expected, because Bluetooth on Android doesn't expose any rumble functionality. However, they noticed that a haptic device was listed by my app called "DualSense Wireless Controller". This haptic device was able to vibrate their PS5 controller. I'm not sure if this is a bug or a misaligned feature? Can this info be used to somehow support rumble over bluetooth?

Here's the info (spat out by my app) about his controller:

Gamepad Name PS5 Controller
Type PS5
Touchpads 0
Sensors none
Mapping 00ea5e4c050000e60c0000ffff3f00,PS5 Controller,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,platform:Android
Joystick Name DualSense Wireless Controller
Buttons 17
Hats 0
Axes 8
Product Version 65535
Product ID 3302
Vendor ID 1356

**Comment by slouken** [comment]
That's interesting, what version of Android are they running?

**Comment by AntTheAlchemist** [comment]
They report they're using Android 12 on a Motorola Moto G Stylus 5G (2022) device.

I'm also using the hint `SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE, "1"` in my app, if it matters.

**Comment by slouken** [comment]
Interesting. I can confirm that there is a haptic device that rumbles DualSense controllers on Android.

It's a fair amount of work to glue those together, but it's the right way going forward. I'll add this to my TODO list.

Thanks!

**Comment by AntTheAlchemist** [comment]
Good luck! It would be great to get that working.

Is there still plans to scrap the haptic api in SDL3?

**Comment by slouken** [comment]
Yes, so far.

**Comment by MrSteel22** [comment]
Hi, i am not sure if there is any progress already on this. and the information is useful but i think ps5 controller on android phone can supports rumble over Bluetooth connection. Try to use skyline emulator and  controller settings while setting up the keys it detects rumble also.

**Comment by slouken** [comment]
The haptic API is staying for SDL 3.0, but it'll only be for handheld devices and wheels and throttles and so forth. Gamepads showing up as haptic devices will be considered a bug.

**Comment by slouken** [comment]
Fixed, thanks!
