### ISSUE TITLE
Backspace on Colemak keyboard layout doesn't work on Windows

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#7853]
On the [Colemak](https://en.wikipedia.org/wiki/Colemak) keyboard layout, the usual Caps Lock key is mapped to Backspace. This remapping [works on linux/wayland](https://github.com/ppy/osu-framework/issues/1463#issuecomment-1596885079), but doesn't [on windows](https://github.com/ppy/osu-framework/issues/1463#issuecomment-1597647472) (the keycode reports as `SDLK_CAPSLOCK` even though it should be `SDLK_BACKSPACE`).

The root cause of this is probably the following code, disallowing caps lock remapping:

https://github.com/libsdl-org/SDL/blob/70e43c150ec377d5aad2ca238752b1140abc03f0/src/video/windows/SDL_windowskeyboard.c#L132-L136

**Comment by slouken** [comment]
Fixed, thanks!
