### ISSUE TITLE
Inconsistent mouse warp behaviour between platforms

### ISSUE THREAD

**Issue by GranMinigun** [libsdl-org/SDL#7855]
DOSBox Staging calls `SDL_WarpMouseInWindow()` when releasing mouse cursor to center it in the window (whether that's a good idea is a separate topic). It was noticed that using DPI-scaled coordinates works as expected on macOS, but on Windows with HiDPI enabled the cursor lands closer to the upper-left corner instead, suggesting that real pixels are used there as coordinates.

Here's an [example code](https://github.com/libsdl-org/SDL/files/11818715/mwarp.tar.gz). Left click will try to center the cursor based on DPI-scaled coordinates, and right click - on real pixels. This was tested on up-to-date Windows 10 machine (SDL 2.28 RC 1) and macOS 11 (SDL 2.26.5), confirming the above behaviour. Also tested in X11 (no concept of DPI scaling, so the cursor always lands dead-center), native Wayland, and XWayland (both do not allow the cursor to budge), with SDL 2.26.5.

I'm personally not worried about Wayland's behaviour, but it would be nice to at least document the difference between Windows and macOS.

**Comment by slouken** [comment]
Can you reproduce this with an SDL test program? I modified testsprite2.c with the following patch:
```diff
diff --git a/test/testsprite2.c b/test/testsprite2.c
index 89037fd09..b8f86b232 100644
--- a/test/testsprite2.c
+++ b/test/testsprite2.c
@@ -400,6 +400,11 @@ void loop()

     /* Check for events */
     while (SDL_PollEvent(&event)) {
+        if (event.type == SDL_KEYDOWN && event.key.keysym.sym == SDLK_b) {
+            int w, h;
+            SDL_GetWindowSize(state->windows[0], &w, &h);
+            SDL_WarpMouseInWindow(state->windows[0], w / 2, h / 2);
+        }
         SDLTest_CommonEvent(state, &event, &done);
     }
     for (i = 0; i < state->num_windows; ++i) {

```
When I press the B key, it warps the mouse to the center of the window.

If I disable DPI awareness, the window is scaled up by the desktop scale as expected, and warping the mouse moves it to the center of the (larger) window.
If I enable DPI awareness, the window is not scaled, all coordinates are in pixels, and warping the mouse moves it to the center of the (smaller) window.

**Comment by slouken** [comment]
Thanks, this is fixed!
