### ISSUE TITLE
Multi-click count does not differentiate between mouse buttons

### ISSUE THREAD

**Issue by abdes** [libsdl-org/SDL#7866]
Clicking the same mouse button multiple times produces the correct number of clicks per pressed or released event.

Clicking left and right mouse buttons simultaneously produces mouse events for each button press/release with clicks count having the total number of clicks. Not sure this is the intended behavior and if it is, it's kinda useless as a button handler cannot make sense out of it.

Clicking middle mouse button multiple times produce the correct clicks count.

Clicking middle button and left or right button simultaneously, then releasing both quickly enough produces:
```
Mouse button event button = 1 state = DOWN clicks = 1
Mouse button event button = 2 state = DOWN clicks = 1
Mouse button event button = 2 state = UP clicks = 1
Mouse button event button = 1 state = UP clicks = 2
```

Clicking middle button and left or right button simultaneously, holding for a while, then releasing both produces:
```
Mouse button event button = 1 state = DOWN clicks = 1
Mouse button event button = 2 state = DOWN clicks = 1
Mouse button event button = 2 state = UP clicks = 0
Mouse button event button = 1 state = UP clicks = 2
```

Not sure what the above behavior means...

If this is an intended behavior, docs do not mention it.

If this is not, then it renders click counting totally useless, either remove it from the API or it should be fixed/documented (for example that it only works when a single button is clicked).

**Comment by slouken** [comment]
What version of SDL are you using? There's a function GetMouseClickState() that gives unique click count for each mouse button. If you're able to reproduce this with the latest version of SDL, can you debug into that and find out what's going wrong?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
