### ISSUE TITLE
switch_hidapi: Controller player leds are always off

### ISSUE THREAD

**Issue by german77** [libsdl-org/SDL#7868]
Yuzu recently updated to SDL 2.28.0. The controllers work correctly after changing a few flags on https://github.com/yuzu-emu/yuzu/pull/10901. But the leds are always off regardless of the controller number. 

I took the liberty to try to debug this issue.  This line doesn't seem to return the correct value. Setting a hard coded value from 0-3 will turn the correct player led value. https://github.com/libsdl-org/SDL/blob/release-2.28.x/src/joystick/hidapi/SDL_hidapi_switch.c#L1417

I'm not really sure how to fix this issue myself.

**Comment by german77** [comment]
The value returned from SDL_JoystickGetPlayerIndex() is always -1. Controller names seem to have the correct index

**Comment by german77** [comment]
On a closer inspection all hidapi drivers have this function stubbed. I suppose this isn't intended.
https://github.com/libsdl-org/SDL/blob/c27f3ead7c37bcbef608f385baa9fce7232efc6d/src/joystick/hidapi/SDL_hidapi_switch.c#L1306-L1309

**Comment by slouken** [comment]
Good catch, this is fixed now, thanks!
