### ISSUE TITLE
Cemu sld NSw wired controller not working 

### ISSUE THREAD

**Issue by Sumo2016** [libsdl-org/SDL#7870]
It senses my controller and when I move the joysticks it detects them as they move but in game they don't

**Comment by slouken** [comment]
Please report this to the Cemu developers. Once they've identified the issue, feel free to report it here with more information on what SDL is doing wrong.

Please make sure Cemu is using the latest version of SDL (2.28.0) as there have been significant controller bug fixes in that release.

**Comment by Sumo2016** [comment]
Hi yes I fixed it although I am new to cemu and I don't know how to install the latest SDL version for cemu?
