### ISSUE TITLE
AltGr not working properly

### ISSUE THREAD

**Issue by bztsrc** [libsdl-org/SDL#7873]
This effects Windows 11 and latest Ubuntu LTS (23.04), other platforms may be affected too.

Keyboard input isn't working properly with Hungarian layout, namely the combinations with the AltGr key. No text input event arrives, and if I check KEYDOWN / KEYUP events individually, then I see when I press AltGr I get SDL_SCANCODE_LCTRL + SDL_SCANCODE_RALT combination, always, even though I haven't pressed the Ctrl key, just the AltGr key.

I assume the reason for text input failing is because for example AltGr+, should produce a text input event with ";", but it's trying to translate Ctrl+AltGr+, instead, which isn't ";".

To reproduce, initialize events, open a window, and print the scancode for key events. Might be related to this ancient issue https://forums.libsdl.org/viewtopic.php?t=8590

Cheers,
bzt

**Comment by Susko3** [comment]
`AltGr` → `Ctrl` + `Alt` is how windows works. I tried the `checkkeys` test on the current `main` branch, and it seems to work as expected:

```cs
INFO: Key pressed :  scancode 224 = Left Ctrl, keycode 0x400000E0 = Left Ctrl  modifiers: LCTRL RALT
INFO: Key pressed :  scancode 230 = Right Alt, keycode 0x400000E6 = Right Alt  modifiers: LCTRL RALT
INFO: Key pressed :  scancode 54 = ,, keycode 0x0000002C = ,  modifiers: LCTRL RALT
INFO: INPUT Text (\x3b): ";"
INFO: Key released:  scancode 54 = ,, keycode 0x0000002C = ,  modifiers: (none)
INFO: Key released:  scancode 224 = Left Ctrl, keycode 0x400000E0 = Left Ctrl  modifiers: (none)
INFO: Key released:  scancode 230 = Right Alt, keycode 0x400000E6 = Right Alt  modifiers: (none)
```

**Comment by bztsrc** [comment]
Hi,

Thank you for your answer!

> AltGr → Ctrl + Alt is how windows works.

But the issue appears on Ubuntu too.

> on the current main branch

Forgot to mention, this is with the SDL2 version that Ubuntu ships.

Anyway, thanks for the tip, I've statically linked with the latest git versions (both `sdl2` and `main` branches), and it did solve the problem. So it seems this has already been fixed on SDL side, just the latest version isn't shipping yet by the OS, therefore I'm closing this issue.

Thanks,
bzt
