### ISSUE TITLE
Mingw memory error with cmake and ninja

### ISSUE THREAD

**Issue by kaissouDev** [libsdl-org/SDL#7882]
Hello, I tried to add sdl3 in my project with cmake and when I compile on github action with mingw I get this error:

`FAILED : 3rdparty/SDL/CMakeFiles/SDL3-static.dir/src/SDL_assert.c.obj
C:\ProgramData\chocolatey\bin\gcc.exe -DSDL_BUILD_MAJOR_VERSION=3 -DSDL_BUILD_MICRO_VERSION=0 -DSDL_BUILD_MINOR_VERSION=0 -DSDL_STATIC_LIB -DUSING_GENERATED_CONFIG_H -ID:/a/Eat-the-Mushroom/Eat-the-Mushroom/build/3rdparty/SDL/include-config-release -ID :/a/Sdl3-test/Sdl3-test/3rdparty/SDL/src -ID:/a/Eat-the-Mushroom/Eat-the-Mushroom/build/3rdparty/SDL/include -ID:/a/Sdl3-test/Sdl3-test/3rdparty/SDL/include -ID :/a/Sdl3-test/Sdl3-test/3rdparty/SDL/include/SDL3 -O3 -DNDEBUG -idirafter D:/a/Sdl3-test/Sdl3-test/3rdparty/SDL/src/video/khronos -Wall -Wundef -fno-strict-aliasing -Wshadow -Wno-unused-local-typedefs -gdwarf-4 -fdiagnostics-color=always -Winvalid-pch -include D :/a/Eat-the-Mushroom/Eat-the-Mushroom/build/3rdparty/SDL/CMakeFiles/SDL3-static.dir/cmake_pch.h -MD -MT 3rdparty/SDL/CMakeFiles/SDL3-static.dir/src/SDL_assert.c.obj -MF 3rdparty\SDL\CMakeFiles\SDL3-static.dir\src\SDL_assert.c.obj.d -o 3rdparty/SDL/CMakeFiles/SDL3-static.dir/src/SDL_assert.c.obj -c D:/a/Sdl3-test/Sdl3-test/3rdparty/SDL/src/SDL_assert.c
erreur interne dans mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:192 : MapViewOfFileEx : 
  Attempt to access invalid address`

**Comment by slouken** [comment]
This is a bug in the mingw toolchain. Please make sure you have the latest version of the tools, and verify that it works locally.

**Comment by madebr** [comment]
You can disable precompiled headers with [`-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON`](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_PRECOMPILE_HEADERS.html).
