### ISSUE TITLE
On glibc / 32-bit, define _TIME_BITS to 64 during compilation if possible

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#7886]
On platforms where time_t is a signed 32-bit integer, most notably i386 Linux, various functions stop working when dealing with a timestamp beyond January 2038.

glibc has an opt-in mechanism that redefines time_t to be 64-bit, and correspondingly increases the size of all system data
structures that contain a time_t, such as struct timeval and struct stat. This is necessary to allow timestamps beyond January 2038 to be represented; as well as things that obviously deal with timestamps, this affects functions like stat(), which will fail with EOVERFLOW if asked to inspect a file whose correct timestamp does not fit in time_t. This in turn can cause unexpected problems for "filesystem APIs" of the form "if /run/foo exists, then ..." when accessed by 32-bit code, if the check for existence is done with stat() rather than access().

Using 64-bit timestamps in glibc is an opt-in and not the default, because if done carelessly it can change libraries' ABIs. However, SDL *mostly* doesn't use system headers or types in its own headers. If it doesn't have any mentions of the following types in its ABI (from [the glibc wiki](https://sourceware.org/glibc/wiki/Y2038ProofnessDesign), with the ones I think are most likely to be used by SDL in bold):

* **time_t**
* struct lastlog
* struct msqid_ds
* struct semid_ds
* struct timeb
* **struct timespec**
* **struct timeval**
* struct utimbuf
* struct itimerspec
* **struct stat**
* struct clnt_ops
* struct elf_prstatus
* struct itimerval
* struct ntptimeval
* **struct rusage**
* struct timex
* struct utmp
* struct utmpx

then it should be possible to make SDL's build system always compile it with `-D_TIME_BITS=64`, similar to the way it has had `-D_FILE_OFFSET_BITS=64` since #5724.

Similar to #5724, this needs to be something that is done internally to compile SDL itself, but not exposed to user code, because SDL users might have dependencies on non-SDL libraries that do mention `time_t` in their ABIs (notably libX11 and GLib), which would make it unsafe to force this.

I've been trying to use `abi-dumper` and `abi-compliance-checker` to verify that SDL's outward-facing ABI is unchanged by using `-D_TIME_BITS=64`, but so far I haven't been able to get that to work.

Equivalent change in dbus (where I *did* manage to get `abi-compliance-checker` to tell me that the ABI hadn't broken): https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/416

**Comment by slouken** [comment]
Speaking of X11, if we make this change, are we no longer compatible with the standard X11 library, which we load dynamically?

**Comment by smcv** [comment]
Limitations:

This will only help if SDL is compiled against glibc 2.34 or later. With older glibc, it will be harmless but useless. This is going to be a problem for the Steam Runtime in 15 years' time, but let's cross that bridge when we're closer to coming to it - in 10 years' time, glibc 2.34 should be sufficiently ubiquitous that it would be OK to include it in even the legacy `LD_LIBRARY_PATH`-based branch of the Steam Runtime.

This is only for glibc. Other libc implementations like musl and Android's bionic will have to find their own solution, either making a backwards-incompatible change to define time_t as 64-bit always (musl did this) or sending their own libc-specific PR similar to #5724.

This won't (and can't) help old game binaries that use 32-bit time internally, or when calling into their non-SDL dependencies. I'm hoping that by 2038, it'll be feasible to just run all 32-bit games in a virtual machine or something, with a fake clock that tells them it's 2032 forever; by then, hopefully either GPU passthrough to virtual machines will work, or CPUs will be fast enough that running all 32-bit games under software rendering is viable.

**Comment by smcv** [comment]
> Speaking of X11, if we make this change, are we no longer compatible with the standard X11 library, which we load dynamically?

If I understand correctly, we're OK as long as we don't call any functions with one of the affected types in their signature.

From a quick grep through my `/usr/include/X11`, as long as we steer clear of `TimerEventRec` in `XtAppStruct` and anything in `Xtrans`, we're probably OK?

**Comment by slouken** [comment]
I think this is probably a safe change to make in SDL3. @madebr, do you want to add it to our build config?
