### ISSUE TITLE
More Faster sdl3 rendering

### ISSUE THREAD

**Issue by kaissouDev** [libsdl-org/SDL#7888]
Hello! In my program, when I clear the background color, the program takes 1 to 2 seconds to clear the background. Is there a way to do this directly, without disturbing you of course? : 

```c
#include <SDL3/SDL.h>
#include <stdio.h>
#include <fmt/core.h>

int main(int argc, char* argv[]) {

    SDL_Window *window;                    // Declare a pointer

    SDL_Init(SDL_INIT_VIDEO);              // Initialize SDL2
    SDL_Renderer* renderer;
    SDL_Event event;
    int isRunning = 1;

    // Create an application window with the following settings:
    window = SDL_CreateWindow(
        "Eat-The-Mushroom (5.X dev)",                  // window title
        800,                               // width, in pixels
        600,                               // height, in pixels
        SDL_WINDOW_OPENGL                 // flags - see below
    );


    renderer = SDL_CreateRenderer(window, NULL, 0);

    while (isRunning) {
        // Gestion des événements
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_EVENT_QUIT) {
                isRunning = 0;
            }
        }
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 0, 0, 161, 255);
        SDL_RenderPresent(renderer);
    }
    // Close and destroy the window
    SDL_DestroyWindow(window);

    // Clean up
    SDL_Quit();
    return 0;
}
```

**Comment by madebr** [comment]
>     * `SDL_CreateRenderer(window, NULL, 0)` should be `SDL_CreateRenderer(window, -1, 0)`...[the second argument is not a pointer](https://wiki.libsdl.org/SDL2/SDL_CreateRenderer), so this is going to become a request whatever renderer is first...which might be something that isn't working well on your machine.

This is SDL3 code so the `NULL` is correct here.

**Comment by icculus** [comment]
> This is SDL3 code so the NULL is correct here.

Oh, sorry, I totally missed that this is SDL3.

The other advice still stands, though!

**Comment by kaissouDev** [comment]
Ok thank you very much for your help! I'm going to try this as soon as I have time.

**Comment by kaissouDev** [comment]
Hello, I followed the steps you told me but I still have the same problem ...

**Comment by icculus** [comment]
The next steps would be to see which SDL renderer you're using, and if there's a problem with your computer's video drivers.

**Comment by kaissouDev** [comment]
However, it works very well with other libraries such as raylib and sfml, and my gpu is compatible with vulkan and opengl.

But I've created a project that works with sdl and cmake, and if you'd be so kind as to check it out, it's here: https://github.com/kaissouDev/Eat-the-mushroom in the sdl3-refractor branch.

**Comment by kaissouDev** [comment]
Hello Again, I've finally fixed the problem here's the final code: 

`#include <SDL3/SDL.h>
#include <stdio.h>

int main(int argc, char* argv[]) {

    SDL_Window *window;                    // Declare a pointer

    SDL_Init(SDL_INIT_VIDEO);              // Initialize SDL2
    SDL_Renderer* renderer;
    SDL_Event event;
    int isRunning = 1;

    // Create an application window with the following settings:
    window = SDL_CreateWindow(
        "Eat-The-Mushroom (5.X dev)",                  // window title
        800,                               // width, in pixels
        600,                               // height, in pixels
        0                 // flags - see below
    );


    renderer = SDL_CreateRenderer(window, NULL, 1);

    SDL_SetRenderDrawColor(renderer, 0, 0, 161, 255);
    SDL_RenderClear(renderer);

    while (isRunning) {
        // Gestion des événements
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_EVENT_QUIT) {
                isRunning = 0;
            }
        }
        SDL_RenderPresent(renderer);
    }
    // Close and destroy the window
    SDL_DestroyWindow(window);

    // Clean up
    SDL_Quit();
    return 0;
}`

thanks again for trying to help me :)

**Comment by icculus** [comment]
(This still sounds like you have an SDL3 that accidentally only built with the software renderer. If you get further along and still have problems, let's revisit that.)

**Comment by kaissouDev** [comment]
But why is it that when I replace 0 by 1 the problem is solved? In SDL_CreateRenderer(window, NULL, 1);

**Comment by kaissouDev** [comment]
Then I fix the problem by replacing SDL_CreateRenderer(window, NULL, 0); with SDL_CreateRenderer(window, directx, 0);?

**Comment by icculus** [comment]
> But why is it that when I replace 0 by 1 the problem is solved? In SDL_CreateRenderer(window, NULL, 1);

You moved the SDL_RenderClear() call out of the loop; the main loop isn't drawing _anything_ at the moment in the code you posted.

**Comment by kaissouDev** [comment]
unfortunately it still doesn't work but I think I've found the problem, I just replaced NULL with "direct3d11" and it worked normally, so I think it's directx12 that has a problem with me.

**Comment by slouken** [comment]
Can you add `SDL_SetHint(SDL_HINT_RENDER_DIRECT3D11_DEBUG, "1");` to the beginning of your program and re-run it with the default renderer?

**Comment by kaissouDev** [comment]
yes, but it doesn't seem to correct the problem ...
![image](https://github.com/libsdl-org/SDL/assets/93447388/09e6154a-5e68-4089-a827-14661665e603)
```
SDL_RendererInfo rendererInfo;
SDL_GetRendererInfo(renderer, &rendererInfo);
SDL_Log("Renderer: %s", rendererInfo.name);
```

**Comment by kaissouDev** [comment]
> Can you add `SDL_SetHint(SDL_HINT_RENDER_DIRECT3D11_DEBUG, "1");` to the beginning of your program and re-run it with the default renderer?

yes, but it doesn't seem to correct the problem ...
![image](https://github.com/libsdl-org/SDL/assets/93447388/09e6154a-5e68-4089-a827-14661665e603)
```
SDL_RendererInfo rendererInfo;
SDL_GetRendererInfo(renderer, &rendererInfo);
SDL_Log("Renderer: %s", rendererInfo.name);
```

**Comment by slouken** [comment]
No, it won't correct the problem, but there might be some diagnostic output that will help us figure out what's happening.

**Comment by kaissouDev** [comment]
but I've tried it and directx11 seems to run better than directx12

**Comment by slouken** [comment]
Yes, it seems to for you, we're just trying to get more information so games that use the default renderer on your system will work better. Can you run it once with that hint set with directx12 and post the output?

**Comment by kaissouDev** [comment]
in the output I have no message more ..
![image](https://github.com/libsdl-org/SDL/assets/93447388/62a87e17-a4cb-43e7-a98e-8fab6beaa441)

**Comment by slouken** [comment]
Okay, good to know, thank you!

**Comment by kaissouDev** [comment]
so are you going to find a way of fixing it?

**Comment by slouken** [comment]
We've never seen this and you don't have any information on why it's happening there, so how could we?

**Comment by kaissouDev** [comment]
I'm not... but at least I know that the problem is directx12

**Comment by slouken** [comment]
Changing 0 to 1 makes sure that the software renderer is used instead of DirectX12

**Comment by slouken** [comment]
What happens if you apply this patch to SDL?
```diff
diff --git a/src/render/SDL_render.c b/src/render/SDL_render.c
index 82fe65099..a54555ff8 100644
--- a/src/render/SDL_render.c
+++ b/src/render/SDL_render.c
@@ -89,12 +89,12 @@ this should probably be removed at some point in the future.  --ryan. */

 #ifndef SDL_RENDER_DISABLED
 static const SDL_RenderDriver *render_drivers[] = {
-#ifdef SDL_VIDEO_RENDER_D3D12
-    &D3D12_RenderDriver,
-#endif
 #ifdef SDL_VIDEO_RENDER_D3D11
     &D3D11_RenderDriver,
 #endif
+#ifdef SDL_VIDEO_RENDER_D3D12
+    &D3D12_RenderDriver,
+#endif
 #ifdef SDL_VIDEO_RENDER_D3D
     &D3D_RenderDriver,
 #endif

```

**Comment by kaissouDev** [comment]
Hello @slouken, if I apply this patch, the program will use Direct3D11 as the default rendering engine.
![image](https://github.com/libsdl-org/SDL/assets/93447388/bd3eb10c-04d8-4413-97f9-45149e1aa416)

**Comment by slouken** [comment]
Right, does it fix the issue for you?

**Comment by kaissouDev** [comment]
Yes, it solves the problem!

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
