### ISSUE TITLE
Version 2.28.0 prevents Switch Pro Controller from working and showing up

### ISSUE THREAD

**Issue by Berny23** [libsdl-org/SDL#7893]
I'm using the 3rd party MOBAPAD CHITU HD controller that is recognized by Windows as a Switch Pro Controller.

While using the latest version of both SDL and Yuzu, the controller does not show up in any list, and this somehow causes the full window to extremely stutter and lag. But as soon as I replace the DLL file with version 2.26.5.0, everything is working again, so it's definitely related to SDL, not Yuzu.

**Comment by slouken** [comment]
Can you try with the latest SDL code, we've added some fixes for Nintendo Switch Pro controllers:
https://github.com/libsdl-org/SDL/archive/refs/heads/release-2.28.x.zip

**Comment by Berny23** [comment]
I built the latest DLL, now it works with Yuzu and my Pro Controller. Thanks!
