### ISSUE TITLE
SDL_ShowMessageBox (Wayland): Zenity --icon-name is deprecated

### ISSUE THREAD

**Issue by takase1121** [libsdl-org/SDL#7895]
On my system (Fedora 38 with Zenity 3.92.0), `--icon-name` is deprecated in favor of `--icon`. This is completely broken until 3.99.0 where the option is added back with a deprecation notice.

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by slouken** [comment]
@takase1121 mentions:
git blaming indicates that `--icon-name` was removed in 3.90.0, 3.91.0, 3.92.0 and added back in `3.99.0`. Perhaps it'll be a good idea to check for Zenity's exit code and retry with `--icon-name`?

[The relevant commit that removed the option](https://github.com/GNOME/zenity/commit/c686bdb1b45e95acf010efd9ca0c75527fbb4dea)

EDIT:

A quick look at repology suggests that a lot of Distros are shipping problematic versions:
https://repology.org/project/zenity/versions

[![Packaging status](https://repology.org/badge/vertical-allrepos/zenity.svg)](https://repology.org/project/zenity/versions)
