### ISSUE TITLE
I'm very concerned about the footgun introduced in SDL 3 for resolution-dependent adulturation of relative mouse motion

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#7898]
Rawinput was meant to be a guarantee for not just devs but also assurance to fps players that their mouse input has a raw correspondence to their in-game rotation.

The addition of the flag to artificially add resolution dependent scaling is already dangerous enough of a footgun for coding-by-committee devs to misguidedly enable it in order to "make my game dpi-aware", despite it being meant to be a visible-cursor oriented feature.

On top of that, the current plan of making it _enabled by default_ is a complete regression for the entire purpose of what raw input is for. Now, players can never be sure if the game they're playing, despite being marked "raw input enabled!", is actually indicating the sensitivity as indicated or if it's compounded by their operating system configurations. 

This is only adding _more_ arbitrarily confounding parameters that players now need to keep track of in maintaining their configurations, totaling four layers of arbitrary multipliers between their mouse hardware resolution setting, operating system acceleration setting (because games may or may not use relativemode, players needs to situationally remember whether or not this is active), in-game rotation sensitivity setting, and now display-resolution-dependent game engine scaling (because devs can and will trigger this footgun, players will now also need to situationally remember whether or not this is active)

I watched the GDC 2023 presentation, in it was an allusion that SDL3 was "tested with counterstrike players". However, it seems to me that this was not developed in consultation with _any_ FPS players who are also technically-minded, who would instantly spot this footgun.

The non-technical players would not mention to you this particular aspect of player ergonomics, but this is something that they would instantly spot once the developer _does_ end up triggering this footgun in their game. If not corrected, there will be a pandemic of poorly-configured FPS camera sensitivity options once SDL3 releases.

I would propose these options to avert the oncoming disaster, with varying levels compromise:

## (best) Remove display-dependent scaling from RelativeMode altogether
Instead add a separate API for developers to specifically query for the SDL-calculated density- and acceleration- dependent factor. This way for cursor-based games the developer still have the option to get continuity between the behavior of the hardware cursor and the relative delta when the cursor is clipped, while newbie developers by default wont inadvertently make their FPS sensitivity twice-scaled because they wanted to "make their app DPI-aware".

## (first compromise) Make RelativeMode _not_ density-dependent by default
And make the activation flag require extra conscious choice (e.g. changing the flag from a boolean to a string flag explicitly indicating "fps-based" vs "rts-based" mode)

## (second compromise) Add an escape hatch that _guarantees_ you are subscribing to the platform-dependent raw device deltas, and name it as such.
For platforms which do not provide it, simply make the best-effort to report the least adulterated deltas by temporarily set the operating-system cursor speed setting to unscaled and unaccelerated

**Comment by slouken** [comment]
Raw input is not scaled by default, I'm not sure where you got that idea. The game can enable either linear scaling or desktop acceleration scaling, but it's an option and can be overridden by the user using environment variables.

**Comment by slouken** [comment]
Yes, that's outdated.

Here is more current information:
https://github.com/libsdl-org/SDL/blob/main/docs/README-highdpi.md
https://github.com/libsdl-org/SDL/blob/5b9fdc9dd12564b54612ef7bd45d4b119cb18f03/include/SDL3/SDL_hints.h#L1204
https://github.com/libsdl-org/SDL/blob/5b9fdc9dd12564b54612ef7bd45d4b119cb18f03/include/SDL3/SDL_hints.h#L1215

**Comment by slouken** [comment]
Yup.

**Comment by slouken** [comment]
You're welcome!

**Comment by icculus** [comment]
Either. The developer can set things they need with SDL_SetHint, and users can also set them through environment variables.

Some are meant to be platform-specific quirks that developers might care about, others are meant to be tweaks an end user might care greatly about but apps would never handle directly.

**Comment by slime73** [comment]
SDL hint #define names are separate from the string their define is set to. The usual convention is to have a `SDL_HINT_` prefix for the #define and a `SDL_` prefix for the string.

For example `SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE`'s value is `"SDL_MOUSE_RELATIVE_SPEED_SCALE"`, so you'd use the latter when setting an environment variable.

https://github.com/libsdl-org/SDL/blob/769bf2ebcca8f0cbcde4ec50008942f4eda57f4a/include/SDL_hints.h#L1176-L1179

**Comment by slime73** [comment]
You can use LuaJIT's FFI to load the SDL2 dll with `ffi.load`, declare the SDL_SetHint function with `ffi.cdef`, and then call it using the loaded SDL2 object. But maybe that's a little off-topic for this issue tracker. :)

**Comment by slime73** [comment]
Environment variables have higher priority than `SDL_SetHint`, but I think you can use `SDL_SetHintWithPriority` with `SDL_HINT_OVERRIDE` priority to replace an envvar's value with one of your own, in your app - although I've never tried it myself.

**Comment by slime73** [comment]
Non-integer mouse coordinates are a new feature in SDL3.

**Comment by icculus** [comment]
It's nice we kept all this information together, but if we could take this conversation out of the bug tracker now, I'd appreciate it.

Thanks!
