### ISSUE TITLE
SDL_RWops cannot append to a file >= 4 GiB on Windows

### ISSUE THREAD

**Issue by TheSpydog** [libsdl-org/SDL#7900]
If an RWops->write operation attempts to append to a file on Windows, the operation will fail once the file reaches 4GiB in size.

This appears to be due to a quirk of `SetFilePointer`. In the [windows_file_write](https://github.com/libsdl-org/SDL/blob/main/src/file/SDL_rwops.c#L257) function, the `lpDistanceToMoveHigh` param is set to NULL. Per [the docs](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfilepointer):
> If lpDistanceToMoveHigh is NULL and the new file position does not fit in a 32-bit value, the function fails and returns INVALID_SET_FILE_POINTER.

It seems like there are two potential solutions:
1. Pass in a pointer to the top 32 bits of the offset and deal with the resulting error checking (see the Remarks on the doc page).
2. Use SetFilePointerEx instead. [windows_file_seek](https://github.com/libsdl-org/SDL/blob/main/src/file/SDL_rwops.c#L179) already uses SetFilePointerEx, so maybe this would be the best approach?

**Comment by icculus** [comment]
Okay, this is in for SDL2, SDL3, and 2.28.1.
