### ISSUE TITLE
SDL_PIXELFORMAT_BGR888 is 32 bpp

### ISSUE THREAD

**Issue by tom-seddon** [libsdl-org/SDL#7903]
I'm using SDL 2.0.20 but it looks like this applies to current SDL2 head.

I was consulting the doc page here: https://wiki.libsdl.org/SDL2/SDL_PixelFormatEnum

`SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGR888)` is 4, as the headers define it as equivalent to XBGR8888: https://github.com/libsdl-org/SDL/blob/769bf2ebcca8f0cbcde4ec50008942f4eda57f4a/include/SDL_pixels.h#L253

But the existence of formats such as BGRX8888 (from the name, clearly 4 bytes per pixel) suggests, in the absence of any notes to the contrary, that BGR888 will be 3 bytes per pixel.

If it's going to be an alias for something else, feels like it should be an alias for BGR24.

(Looks like the same would apply to `SDL_PIXELFORMAT_RGB888`.)

Thanks,

--Tom

**Comment by slouken** [comment]
Sure, we can remove that confusion for SDL 3.0.

**Comment by Starbuck5** [comment]
Good idea! This pixel format confused me as well, it seems like a good housekeeping change for SDL3.
