### ISSUE TITLE
Async windowing

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7907]
In reference to this...

https://github.com/libsdl-org/SDL/issues/7070#issuecomment-1616186729

...the way-too-long lag can be shortened, but can we consider saying that SDL3 is intended to be asynchronous, and the proper way to deal with things is:

- Create your window at the size you want,
- position it where you want, if you care
- assume it's at those points...
- ...until you get an event telling you it's elsewhere, which might happen at any time anyhow.
- if you _have to_ query the window dimensions, you shouldn't do it once and consider it gospel; do it every frame if you care.

For most apps, nothing changes, the only real ask here is "don't call GetWindowSize right after SetWindowSize; you already know what you asked for." which is probably where _every_ one of these bug reports came from.

A lot of tap dancing can evaporate from the X11 code, and we don't have to care if some window resize animation that takes time gets added to a later version of Windows or whatever.

It feels like we struggled against this in SDL2 and it's an ongoing, losing battle, and the right solution for everyone is to simply stop struggling.

Opinions?

**Comment by slouken** [comment]
I see why this is attractive, but I think this will break a lot of things subtly.
Out of curiosity, what are you thinking for sdl2-compat?

**Comment by icculus** [comment]
> I see why this is attractive, but I think this will break a lot of things subtly.

The biggest risk is likely things that built entire GUI toolkits on top of SDL. I suspect most games just create a window and move on. However, SDL2 has been implicitly async for most of its life, so maybe most things already deal with this?

Most platforms have always been synchronous under the hood--Windows, Cocoa, etc--and would remain as such. It's just X11 (and Wayland?) that are like this, so most things aren't going to change, and the rest can be managed with a few platform-independent Best Practices in the app.

>  Out of curiosity, what are you thinking for sdl2-compat?

SDL2 hasn't attempted to force synchronicity at all until pretty late in life, and not 100% successfully, so most things probably don't actually require it to function, so I would probably leave it as a quirk flag.

If the quirk flag is set, we'd force SDL_SetWindowSize() to wait X milliseconds or until SDL_GetWindowSize reports a change, etc, same as the X11 code does now.

**Comment by slouken** [comment]
Hmm, worth a shot

**Comment by Kontrabant** [comment]
A change like this would probably address #6646 too, as applications could change all the window state they want, and it could then be applied at some arbitrary time. A lot of heavyweight round-trips in the Wayland backend could be removed if window operations were considered to be async, as we currently need to sync after most window operations as SDL applications expect the changes to be immediate.

I can see the potential issues though, especially if window changes are immediate on some platforms, but not others.

> Out of curiosity, what are you thinking for sdl2-compat?

There could be some kind of `SDL_SyncWindow()` function that blocks until all pending changes are fully committed.  It would work for SDL3 applications that still want their changes committed now, no matter how long it takes, and for sdl2-compat, where it would basically have to be used after every window state call, since that's what SDL2 apps expect.

**Comment by icculus** [comment]
> There could also be some kind of SDL_SyncWindow() 

The problem is that, with X11, it's not just "wait until this happens," it's also "the window manager said no and chose something else, or not to do anything at all, and there's no indication of this," so a SyncWindow function would put us right back where we started.

**Comment by slouken** [comment]
I think that means that we define all windowing operations as asynchronous, and only set window state in response to events from the windowing system. We'd have to carefully review all the code that sets state and expects to be able to read it back. I'm thinking fullscreen state transitions are the most risky here.

It definitely sounds worth trying, and would improve performance of things like window animation operations.

**Comment by slouken** [comment]
If we wanted to make the behavior the same across platforms, we could implement a queue of windowing operations and all those functions would submit to the queue, and we could have a SDL_FlushWindowOperations() function that could be called to guarantee that they've been sent off to the server. This would be implicitly called by SDL_PumpEvents().

One upside to this is that we could make all the windowing functions callable from any thread, and only SDL_FlushWindowOperations() would need to be called on the main thread.

**Comment by slouken** [comment]
This would definitely improve things for applications that want a set of atomic state changes (e.g. change position and size at the same time)

**Comment by icculus** [comment]
> One upside to this is that we could make all the windowing functions callable from any thread

Oh my god. I wasn't thinking this advanced, but...that would be kinda awesome if it works out.

**Comment by Kontrabant** [comment]
Just to note, I'm currently working on this (https://github.com/Kontrabant/SDL/tree/async_window_ops2).  This touches quite a bit and is still very WIP, so a draft pull is still a bit off, but it seems promising so far. Tests are passing and a lot of blocking code was able to be ripped out.
