### ISSUE TITLE
Blit function signatures are inconsistent

### ISSUE THREAD

**Issue by tom-seddon** [libsdl-org/SDL#7911]
I noticed this in SDL 2.0.21, but looks like it's still the case in head (4aee17b039981f2bb79892f3d3e3e17bd6b66530 at the time of writing).

`SDL_BlitSurfaceScaled` and `BDL_SoftStretchLinear` don't have the same function signature.

**Comment by slouken** [comment]
That's correct. I'm updating the documentation to explain why.

Thanks!
