### ISSUE TITLE
Header refers to `SDL_BlitScaled`

### ISSUE THREAD

**Issue by tom-seddon** [libsdl-org/SDL#7912]
https://github.com/libsdl-org/SDL/blob/4aee17b039981f2bb79892f3d3e3e17bd6b66530/include/SDL3/SDL_surface.h#L817

Looks like this function is now actually called `SDL_BlitSurfaceScaled`.

Thanks,

--Tom

**Comment by slouken** [comment]
Fixed, thanks!
