### ISSUE TITLE
UpdateWindowSurface() causes error "Window surface is invalid, please call SDL_GetWindowSurface() to get a new surface"

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [libsdl-org/SDL#7917]
I wanted to write a quick program in SDL2, since I don't have too much familiarity to SDL3.
I already had a few applications written in SDL2 so I thought this would be a problem. My other applications that I wrote were done using Windows but this time I'm writing this using Linux.

Here is a quick code snippet:

```
int main(int argc, char** argv){
    sW = SDL_CreateWindow("Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, SDL_WINDOW_SHOWN | SDL_WINDOW_OPENGL);
    SDL_UpdateWindowSurface(sW);
    // this returns the error in the title.
    printf("%s\n", SDL_GetError());

    // ... Other code for SDL renderer and stuff
}
```

It asks me to call SDL_GetWindowSurface() but doing so caused the entire background to not be painted!?
I haven't had this problem before and when I try using SDL_image no image appears.

Yes, I've already checked to make sure my paths and stuff are correct. Using IMG_GetError() returns the exact same result later on. Unfortunately since I've migrated to Linux I can't really test this out on Windows at the moment.

If needed I can provide more code.
Any help would be appreciated!

**Comment by slouken** [comment]
This is a good question for the SDL discussion group:
https://discourse.libsdl.org/c/sdl-development/6

**Comment by icculus** [comment]
(The short of it, though, is you probably _should not_ call SDL_UpdateWindowSurface, but rather create an SDL_Renderer and let it deal with getting pixels to the screen. The 1.2-to-2.0 migration guide explains this in detail here, just ignore the SDL 1.2-specific bits: https://wiki.libsdl.org/SDL2/MigrationGuide#setting_up_a_game_with_the_new_video_api )
