### ISSUE TITLE
SDL2 macOS relative mouse mode regression 

### ISSUE THREAD

**Issue by alexey-lysiuk** [libsdl-org/SDL#7918]
Since https://github.com/libsdl-org/SDL/commit/2afb49ba9a2edc361a3b35d8e30be977a5bcc0c4 (SDL 2.28.0+), switching to other process, moving the pointer, and switching back may cause incorrect coordinates received in `SDL_MOUSEMOTION` events.

It can be reproduced with `testrelative`, red square may jump unexpectedly on attempt to move the pointer after window gains focus as if coordinates change by `CGWarpMouseCursorPosition()` is applied to the first mouse movement event.
The problem becomes more obvious if the given test is modified to process these events when window is in foreground only.

There is no difference between using mouse or trackpad, the issue seems to reproduce more reliably with the latter. OS version is 13.4.1.

**Comment by icculus** [comment]
Sigh, okay.

**Comment by icculus** [comment]
Okay, the latest in SDL2 (and 2.28.x) fixes this without breaking testrelative in general or #6994, which is what the regression in question was addressing.
