### ISSUE TITLE
Mac OS X: Completely remove Carbon dependency.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#792]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Mac OS X (All), x86

# Comments on the original bug report:

On 2013-03-15 01:51:36 +0000, Ryan C. Gordon wrote:

> The configure script on Mac OS X has this...
> 
>        EXTRA_CFLAGS="$EXTRA_CFLAGS -DTARGET_API_MAC_CARBON"
> 
> ...do we still need that (and/or is it causing us compatibility problems)?
> 
> --ryan.

On 2015-02-19 05:22:22 +0000, Ryan C. Gordon wrote:

> 
> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry if you got a lot of email from this. This is to help me sort through some bugs in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4, though!

On 2015-02-19 21:22:46 +0000, Ryan C. Gordon wrote:

> 
> Ok, it builds fine without that #define, apparently, but we still actually link against Carbon in any case.
> 
> Here's where we still use it:
> 
>   "_KBGetLayoutType", referenced from:
>       _Cocoa_HandleKeyEvent in SDL_cocoakeyboard.o
>   "_LMGetKbdType", referenced from:
>       _UpdateKeymap in SDL_cocoakeyboard.o
>       _Cocoa_HandleKeyEvent in SDL_cocoakeyboard.o
>   "_TISCopyCurrentKeyboardLayoutInputSource", referenced from:
>       _UpdateKeymap in SDL_cocoakeyboard.o
>   "_TISGetInputSourceProperty", referenced from:
>       _UpdateKeymap in SDL_cocoakeyboard.o
>   "_kTISPropertyUnicodeKeyLayoutData", referenced from:
>       _UpdateKeymap in SDL_cocoakeyboard.o
> 
> ...and here's where we still #include <Carbon/Carbon.h> ...
> 
>     src/video/cocoa/SDL_cocoakeyboard.m
>     src/video/cocoa/SDL_cocoamodes.m
> 
> ...so I'm leaving this alone for now, and removing the triage-2.0.4 tag, and renaming this bug "completely remove Carbon dependency."
> 
> --ryan.

On 2015-09-21 22:42:23 +0000, Dominik Reichardt wrote:

> Add to this https://bugzilla.libsdl.org/show_bug.cgi?id=3127 which fixes a deprecated Carbon component dependency.

**Comment by icculus** [comment]
Let's see what state this is in for 2.0.20.

**Comment by icculus** [comment]
We spoke to Apple engineers and they say at this time, the remaining APIs are _not_ deprecated and have no replacements, and that linking to the Carbon framework for these cases is not considered bad form.

As such, I'm declaring this bug closed. If a time comes where these last APIs _are_ deprecated, we'll open a new bug.
