### ISSUE TITLE
Brightness of Guide button LED on Xbox Wireless Controller can't be adjusted while connected via Bluetooth on Windows

### ISSUE THREAD

**Issue by Yuuyatails** [libsdl-org/SDL#7920]
It comes to my attention that the brightness of the guide button LED on the Xbox Wireless Controller (specifically, model 1708 and model 1914) cannot be adjusted with the `SDL_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED` command while the controller was connected via Bluetooth on Windows.

It is possible to add the ability to adjust the brightness while connected via Bluetooth?

**Comment by slouken** [comment]
No, it's not possible to adjust the brightness over Bluetooth.
