### ISSUE TITLE
SDL_Vulkan_GetInstanceExtensions pass pointer without copying

### ISSUE THREAD

**Issue by CodesOtakuYT** [libsdl-org/SDL#7926]
SDL_Vulkan_GetInstanceExtensions currently expect the user to allocate memory so it can copy the array of extensions to it, while it can just pass a pointer to the internal array and leave the freedom to the user to either use the pointer directly with vulkan in the case of not needing other extensions, or allocating his own memory and copying it himself.

Currently the signature is this:
```
SDL_bool SDL_Vulkan_GetInstanceExtensions(SDL_Window *window,
                                          unsigned int *pCount,
                                          const char **pNames);
```

I suggest turning it into this, similar to other APIs like GLFW:
`const char ** SDL_Vulkan_GetInstanceExtensions(SDL_Window *window, unsigned int *pCount);`

Returning an SDL_bool in the previous version was necessary, now we can just return a pointer to the internal extensions array, or NULL in the rare case where it's not possible.

**Comment by slouken** [comment]
This has been implemented!
