### ISSUE TITLE
Use XCB instead of Xlib extensions for vulkan when possible.

### ISSUE THREAD

**Issue by CodesOtakuYT** [libsdl-org/SDL#7927]
![image](https://github.com/libsdl-org/SDL/assets/88196711/15f1229e-bcc6-4cd1-8d7f-b2a6a9ebfa9a)
Seems like Xlib is prioritized over XCB extensions for vulkan, it should probably be flipped.

**Comment by slouken** [comment]
As discussed in https://github.com/libsdl-org/SDL/pull/7928, we don't use xcb for windowing, so we shouldn't default to it for Vulkan.
