### ISSUE TITLE
Direct Input Haptic Issues with Thrustmaster T150 Steering Wheel

### ISSUE THREAD

**Issue by c3pp0** [libsdl-org/SDL#7941]
Hi,

first of all, great library!!!

I ended up here because I wanted to use a 
Thrustmaster T150 Steering Wheel (Firmware 35,  Driver 2.11.38.0) with _FFBArcadePlugin_ in Windows 10.

After some debugging, I found that `IDirectInputDevice8_CreateEffect` in _SDL_dinputhaptic.c_ always returned `E_INVALIDARG.`
This seems to happen because `effect->hweffect->effect.cAxes` gets set to an apparently wrong value of _3_ instead of _2_.
Since `SDL_SYS_ToDIEFFECT` sets `dest->cAxes` from `haptic->naxes` if `src->constant.direction.type` is different from `SDL_HAPTIC_STEERING_AXIS` (which it is for _testrumble_ and _FFBArcadePlugin_) and `haptic->naxes` gets set by `IDirectInputDevice8_EnumObjects`, I don't know how to fix this in a decent way :(

My quick and dirty solution is to set `dest->cAxes` to _2_ instead of `haptic->naxes` in `SDL_SYS_ToDIEFFECT`.

It works perfectly in my specific case and I'd really be glad to contribute, but I have no idea how to do this properly.
I thought maybe somebody here does :)

Keep up the good work 💪

**Comment by meyraud705** [comment]
`SDL_HAPTIC_STEERING_AXIS` was added to solve this issue. You should file a bug at *FFBArcadePlugin* telling them to change `SDL_HAPTIC_CARTESIAN` to `SDL_HAPTIC_STEERING_AXIS`.
