### ISSUE TITLE
Build instructions for gamepadmap and SDL test utils

### ISSUE THREAD

**Issue by danboid** [libsdl-org/SDL#7955]
My joypad isn't working with a couple of SDL2 apps under Linux.

After a bit of research and finger pointing, I learn about gamecontrollerdb.txt and I ended up here:

https://github.com/gabomdq/SDL_GameControllerDB

Which says "gamepadmap.c utility provided with SDL2 is the official tool to create these mappings" but it doesn't explain how to build it, nor does the README within the test dir and the test tools don't get built by default.

**Comment by slouken** [comment]
Maybe create a PR on that project with more instructions?

**Comment by artcfox** [comment]
For SDL2, the utility is called controllermap, and it can be found in the test directory.

```
sudo apt install libsdl2-dev
git clone https://github.com/libsdl-org/SDL
cd SDL
git checkout SDL2
cd test
./configure
make
```
Plug in your controller
```
./controllermap
```
Follow the instructions printed to the console.

**Comment by danboid** [comment]
> For SDL2, the utility is called controllermap, and it can be found in the test directory.
> 
> ```
> sudo apt install libsdl2-dev
> git clone https://github.com/libsdl-org/SDL
> cd SDL
> git checkout SDL2
> cd test
> ./configure
> make
> ```
> 
> Plug in your controller
> 
> ```
> ./controllermap
> ```
> 
> Follow the instructions printed to the console.

Thanks Artcfox!

I cam confirm these instructions work.
