### ISSUE TITLE
commit 1ee9a437f947d0f63c27989db765a821f4c817ab vs SDL_TEXTINPUT

### ISSUE THREAD

**Issue by lumpymilk** [libsdl-org/SDL#7958]
On branch release-2.28.x,

After commit 1ee9a437f947d0f63c27989db765a821f4c817ab (May 20th) on iOS for iPhone, I no longer receive SDL_TEXTINPUT events when a hardware keyboard is attached to the iPhone simulator. See changes made to "src/video/uikit/SDL_uikitview.m.

If I revert back to 69644346acda4dc8455fda2b9d26ca19844b93dd for src/video/uikit/SDL_uikitview.m, then SDL_TEXTINPUT messages are sent as normal, if I add 1ee9a437f947d0f63c27989db765a821f4c817ab, I get not SDL_TEXTINPUT events from SDL_PollEvent(&event).

**Comment by lumpymilk** [comment]
it looks like the one I really needed here was:
[super pressesBegan:presses withEvent:event]; 

As long as that is in src/video/uikit/SDL_uikitview.m, then I receive the SDL_TEXTINPUT events.

- (void)pressesBegan:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event
{
      if (!SDL_HasGCKeyboard()) {
          for (UIPress *press in presses) {
              SDL_Scancode scancode = [self scancodeFromPress:press];
              SDL_SendKeyboardKey(SDL_PRESSED, scancode);
          }
      }
      [super pressesBegan:presses withEvent:event];
}

**Comment by kiddkaffeine** [comment]
My understanding from discussions with other Apple devs is that you shouldn't pass these events up if you handle them but it's entirely possible that some other code depends on the default handling; we also don't usually use the simulator much.

I may try to dig into this but it might be at least several days before I can.

That said, this is probably not the optimal solution, but if this is urgent and since it only affects the simulator, one possible fix would be to re-add the call back in pressesBegan but wrap the super call in a
#if TARGET_OS_SIMULATOR
or similar.

**Comment by lumpymilk** [comment]
thanks @kiddkaffeine

I have additional information and I'm not sure how you'll want to handle it. You might want to close this case.

I tested with the current 2.28.x code and a physical iPhone + physical keyboard over bluetooth. All SDL_KEYDOWN and SDL_KEYUP are sent to the app through SDL_PollEvent, but SDL_TEXTINPUT is never found in SDL_PollEvent().
I went back to 2.26.x code and again with physical iPhone + physical keyboard over bluetooth. Same results.
If I do the same with the simulator and connect hardware keyboard, that works fine (SDL_TEXTINPUT is sent).

At this point, I don't think any real existing functionality was affected by 1ee9a437f947d0f63c27989db765a821f4c817ab. Probably the best thing for me to do is find another way to handle text input on the iPhone when a keyboard is in use. I might resort to using SDL_KEYDOWN/SDL_KEYUP events. This could actually work for my use-case.

I would like the SDL_TEXTINPUT to work with hardware keyboards and iPhone but realistically it probably isn't that common of a use-case.

**Comment by kiddkaffeine** [comment]
I am unfortunately not an expert here so I will direct this to @slouken

**Comment by deveee** [comment]
Not sure if related https://github.com/libsdl-org/SDL/issues/7979

**Comment by slouken** [comment]
Text input is intended to work when hardware keyboards are connected, and this is fixed. Thanks for the good investigation!
