### ISSUE TITLE
SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!

### ISSUE THREAD

**Issue by HexDecimal** [libsdl-org/SDL#7959]
There's an error message since SDL 2.0.10 that's causing some confusion:

https://github.com/libsdl-org/SDL/blob/550c84b4dfc4f9f98d190e8c0e8714655f23b6a8/src/render/direct3d/SDL_render_d3d.c#L1138-L1141

Users are encountering this error from updating SDL and enabling logs but there's not much anyone can do about it other than to suppress the logs and move on.

https://github.com/Genymobile/scrcpy/issues/1441
https://github.com/libtcod/python-tcod/issues/131

I don't have any real suggestions.  It'd be nice to figure out what exactly triggers this error.  If there's nothing that can be done then maybe reduce the error level of this message.

**Comment by icculus** [comment]
I guess the question is: does it recover? If performance drops for a frame and then it's fine, we should just remove the error logging.

**Comment by HexDecimal** [comment]
This always seems to happen on the first frame so I don't know if SDL ever uses the vertex buffer.  I haven't noticed any major slowdown but don't have much to compare to.  Performance seems fine compared to before SDL 2.0.10.

**Comment by icculus** [comment]
Putting this in 2.28.2 in case it's either easy to fix or we just remove the log messages.

**Comment by slouken** [comment]
What version of SDL are you testing with? I recently fixed a bug causing this message.

**Comment by HexDecimal** [comment]
The issue exists on `2.26.5`, and seems fixed in `2.28.1`.

It looks like I can just update everything to the latest release.
