### ISSUE TITLE
[SDL 2.28.1] PS4 controller itself gets frozen on macOS via Bluetooth

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#7960]
This issue was been reported to my game here: https://github.com/Wohlstand/TheXTech/issues/549

Attempt to use an Unofficial PS4 controller (model `CUH-ZCT2E`) via Bluetooth, causes it (controller itself) being frozen, and needs to use a clip to push a reset button on it. This problem appears at recent versions of SDL2. With the SDL2 version 2.23.1 it works just fine.

With SDL 2.28.1 and SDL 2.28.0 the problem is here.

The log of my application that reported about connecting / disconnecting of the controller:
```
Debug: Opening joystick id 0...
Debug:   successfully opened!
Debug:   Name: PS4 Controller
Debug:   GUID: 03008fe54c050000c405000000016800
Debug:   Number of Axes: 6
Debug:   Number of Buttons: 16
Debug:   Number of Balls: 0
Debug:   claims to be a game controller...
Debug:     successfully opened game controller!
Debug:   does not support haptic.
Debug:   received ID 6. adding to poll list!

Debug: joystick with ID 6 removed.
```

**Comment by slouken** [comment]
I don’t have an unofficial controller. Is it possible for the user to git bisect the commit that is causing problems?

**Comment by Wohlstand** [comment]
Sounds tricky, like I will need to build multiple test programs of different versions (starting from stable releases first) and let user to test each of them to find which gets being faulty. And then, check PS4 related commits between these stable releases to find one that is actually a source of the failure...

**Comment by slouken** [comment]
I'm guessing it's either the k_ePS4FeatureReportIdSerialNumber or k_ePS4FeatureReportIdCapabilities requests. Neither of which should actually be sent to a Sony controller over Bluetooth.

**Comment by slouken** [comment]
Try the latest code and see if that works? If it doesn't, can you hack your local copy of SDL so it doesn't send k_ePS4FeatureReportIdSerialNumber and see if that fixes it? You shouldn't ship that change, but if that works it will tell us which of the two reports is the problem.

**Comment by Wohlstand** [comment]
I'll make a build and will send it to the user, and if okay or not, I'll let you know.

**Comment by Wohlstand** [comment]
I cherry-picked the commit, and built the game. User confirmed that controller now works just fine. Thank you for the help!
