### ISSUE TITLE
How do you handle touch events in sdl2 i.e moving sprite on the lane via finger touch event( asimple car game where all drawings are from scratch)

### ISSUE THREAD

**Issue by Emmy-infinity** [libsdl-org/SDL#7963]
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL_image.h>
#include <cstdlib>
#include <ctime>

int main(int argc, char **argv)
{
    bool quit = false;
    SDL_Event event;

    SDL_Init(SDL_INIT_VIDEO);
    SDL_Init(SDL_INIT_AUDIO);
    /*SDL_AudioSpec * SDL_LoadWAV(const char *file, SDL_AudioSpec *spec, int**audio_buf, int*audio_len);
    SDL_LoadWAV_RW("/storage/emulated/0/Download/ETH128_07April23_HolyCommunion.mp3",&wav_spec,&wav_buffer,wav_length);*/

    SDL_Window *window = SDL_CreateWindow("SDL2 Displaying Image", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, 1);
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);

    SDL_Renderer *renderer2 = SDL_CreateRenderer(window, -1, 0);
    SDL_Surface *image = IMG_Load("/storage/emulated/0/Pictures/Photoshop Express/PSX_20220629_211837.jpg");
    SDL_Surface *image2 = IMG_Load("/storage/emulated/0/Pictures/Photoshop Express/PSX_20220629_132819.jpg");
    SDL_Surface *image3 = IMG_Load("/storage/emulated/0/Pictures/Photoshop Express/PSX_20230409_182557.jpg");

    SDL_Texture *texture = SDL_CreateTextureFromSurface(renderer, image);
    SDL_Texture *texture2 = SDL_CreateTextureFromSurface(renderer, image2);
    SDL_Texture *texture3 = SDL_CreateTextureFromSurface(renderer, image3);
    SDL_RenderClear(renderer);

    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);

    //SDL_WM_SetIcon(image,NULL);

    SDL_Rect dstrect = {50, -500, 122, 275};
    SDL_Rect image2i = {30, 90, 122, 275};
    SDL_Rect emmy = {50, 50, 122, 275};
    SDL_Rect Nelly = {340, 900, 122, 275};
    SDL_Rect atoo = {6, 70, 80, 1200};

    //int r = rand() % 10 + 0.1;

    while (!quit)

    {
        int x = (((SDL_GetTicks()) % 6));
        x++;
        dstrect.y += rand() % 7 + 1;
        image2i.y += rand() % 10 + 1;
        if (image2i.y > 1200)
        {
            image2i.y = -200;
            image2i.x += rand() % 6 + 30;
            if (image2i.x > 550)
            {
                image2i.x = 100;
            }
        }

        if (dstrect.y > 1200)
        {
            dstrect.y = -200;
            dstrect.y += rand() % 7;
            dstrect.x += 200;
            if (dstrect.x > 550)
            {
                dstrect.x = 100;
            }
        }
        //  if (dstrect.x -image2i.x<10)
        //  {

        //}

        SDL_PollEvent(&event);

        switch (event.type)
        {
        case SDL_FINGERMOTION:

            if (Nelly.x>360)
            {
                
                if(Nelly.x>10){
                    Nelly.x=50;}
            }
            if (Nelly.x <= 350)
            {
                Nelly.x -= 5;
            }

            break;
        case SDL_QUIT:

            quit = true;
            break;
        }
        /* if (Nelly.x - dstrect.x < 10 or Nelly.x - image2i.x < 10 and Nelly.y - dstrect.y < 10 or Nelly.y - image2i.y < 20)
        {
            quit = true;
        }
*/
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 80, 80, 80, 200);

        //SDL_RenderDrawRect(renderer2, &emmy);
        SDL_RenderClear(renderer);

        SDL_Rect multi_rect[6];

        multi_rect[0].w = 150;
        multi_rect[0].h = 1280;
        multi_rect[0].x = 550 + 50;
        multi_rect[0].y = 0;
        multi_rect[0].w = 10;
        multi_rect[1].w = 10;
        multi_rect[1].h = 1280;
        multi_rect[1].x = 100;
        multi_rect[1].y = 0;
        multi_rect[2].w = 10;
        multi_rect[2].h = 1280;
        multi_rect[2].x = 350;
        multi_rect[2].y = 0;
        multi_rect[4].h = 1280;
        multi_rect[4].x = 50;
        multi_rect[4].y = 0;
        multi_rect[4].w = 10;
        multi_rect[5].h = 1280;
        multi_rect[5].x = 350;
        multi_rect[5].y = 0;
        multi_rect[5].w = 1;

        
        SDL_RenderClear(renderer);
          SDL_RenderClear(renderer2);

        SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
        SDL_SetRenderDrawColor(renderer2, 255, 255, 255, 255);

        SDL_RenderFillRects(renderer, multi_rect, 6);
        SDL_RenderDrawLine(renderer2, 230, 0, 230, 1280);
        SDL_Log("4578");
        SDL_Color White = {25, 55, 255};
        TTF_Font *Sans = TTF_OpenFont("Sans.ttf", 24);

        SDL_Surface *surfaceMessage =
            TTF_RenderText_Solid(Sans, "put your text here", White);
        SDL_Texture *Message = SDL_CreateTextureFromSurface(renderer2, surfaceMessage);
        SDL_Rect Message_rect = {360, 700, 400, 400};

        DrawRoad(renderer2, &atoo);
        SDL_RenderCopyEx(renderer, texture2, NULL, &image2i, 0, 0, SDL_FLIP_NONE);
        SDL_RenderCopyEx(renderer, texture3, NULL, &Nelly, 0, 0, SDL_FLIP_NONE);

        SDL_RenderCopyEx(renderer, texture, NULL, &dstrect, 0, 0, SDL_FLIP_NONE);
        SDL_RenderCopyEx(renderer, Message, NULL, &Message_rect, 0, 0, SDL_FLIP_NONE);
        //SDL_RenderCopy(renderer, texture, NULL, NULL);

        SDL_RenderPresent(renderer);
        SDL_RenderPresent(renderer2);
    }

    SDL_DestroyTexture(texture);
    SDL_FreeSurface(image);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);

    SDL_Quit();

    return 1;
}

**Comment by icculus** [comment]
Hi, as we told you 3 weeks ago in #7851, this is the bug tracker and not for general questions.

If you have questions about game development and/or SDL, or want to talk about what you're working on, head over to our forums at https://discourse.libsdl.org/

Thanks!
