### ISSUE TITLE
Text (prediction?) is visible when typing in password on iPadOS/iOS

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#7965]
This is a user report from an app using SDL2, see Issue 2 in https://github.com/ppy/osu/issues/24041.

I'm not sure if this is actually text prediction, as no predictions actually appear, but the inputted text is visible above the keyboard:

https://user-images.githubusercontent.com/46646694/248590981-929a7ea9-9b12-473b-b8a3-c3d82a322e16.mp4

SDL2 version: 1ee9a437f947d0f63c27989db765a821f4c817ab

**Comment by slouken** [comment]
We don't really have a password mode for text input. Maybe we should add that?

**Comment by slouken** [comment]
You can now use SDL_StartTextInputWithProperties() and set the property `SDL_PROP_TEXTINPUT_TYPE_NUMBER` to `SDL_TEXTINPUT_TYPE_TEXT_PASSWORD_HIDDEN` to get password text input.
