### ISSUE TITLE
wiki problems?

### ISSUE THREAD

**Issue by ndearns** [libsdl-org/SDL#7966]
First tutorial entry in the Wiki is linking to a site that's 15 years out of date.  Hundreds of people complaining in the comments.

https://wiki.libsdl.org/SDL2/Tutorials

This site is a problem : http://www.sdltutorials.com/

**Comment by icculus** [comment]
I removed the link to sdltutorials in https://github.com/libsdl-org/sdlwiki/commit/c5a8cb92d3bded01adbeae8f5e2db3e3a225a4a3.
