### ISSUE TITLE
[Feature Request]: Motion control support for ROG Ally

### ISSUE THREAD

**Issue by NightlyFox** [libsdl-org/SDL#7972]
The ROG ally has a gyro/accelerometer built in. Would be nice to be able to use it in CEMU emulator but it needs to be added to SDL first.

**Comment by slouken** [comment]
This is already in for SDL 3.0.

**Comment by grill2010** [comment]
@slouken is this feature also avaible in SDL2?

**Comment by slouken** [comment]
No, this is an SDL3-only feature.

**Comment by streamingdv** [comment]
@slouken I saw that the gyro support for the steamdeck was back ported to SDL2 any specific reason why this is not considered for the Ally gyro? I'm just asking, if there was the decision to not do  back port this feature it's fine.

**Comment by slouken** [comment]
The Ally gyro relies on other functionality that isn't available in SDL2.
