### ISSUE TITLE
Make JoystickPath stable under Linux

### ISSUE THREAD

**Issue by z-s-e** [libsdl-org/SDL#7973]
From my understanding, the best way to refer to a Joystick (across runs or even reboots) is to use a combination of the device GUID plus a representation of the port it is connected to, which seems to be the point of JoystickPath. However, under Linux at least `SDL_JoystickPathForIndex` returns paths such as `/dev/input/event20` which are not stable at all; I get that path no matter which usb port I use. I would rather expect a `/sys` path (see e.g. [here](https://unix.stackexchange.com/q/405991) for reference).

**Comment by slouken** [comment]
The path that's returned is the path that is opened by SDL. You can write system specific code to scan devices and associate the event node and the system path, but that is outside the scope of SDL.
