### ISSUE TITLE
transparent testgl/testsprite in Wayland with Nvidia drivers...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7978]
I should preface this by saying I had no idea Nvidia's binary drivers worked with Wayland, so this might just be a bug on their end.

Is anyone else seeing transparency with testgl or testsprite on Wayland?

[Screencast from 07-12-2023 11:01:35 PM.webm](https://github.com/libsdl-org/SDL/assets/673562/ee2152cd-c47c-4636-9dc9-f5f7e8ad175a)

Xwayland is fine...

[Screencast from 07-12-2023 11:12:56 PM.webm](https://github.com/libsdl-org/SDL/assets/673562/52c48933-03c6-4812-9be2-abe708edc5e0)

testsprite is translucent...and...pink...?

[Screencast from 07-12-2023 11:13:51 PM.webm](https://github.com/libsdl-org/SDL/assets/673562/24893922-8f41-4866-881d-bd15467d6cfb)

...is this us, or the drivers?

**Comment by Kontrabant** [comment]
What desktop and driver versions are these?  This doesn't happen on Fedora 38 with the latest Nvidia drivers, and I've been using the proprietary Nvidia drivers with Wayland since early last year and never saw anything like this.

**Comment by sulix** [comment]
IIRC, this was added in the 530 series, and needs a sufficiently new libnvidia-egl-wayland:
https://github.com/NVIDIA/egl-wayland/pull/71

**Comment by Kontrabant** [comment]
I think EGL_EXT_present_opaque was in even earlier than that (520 I think?), and it doesn't explain why testsprite is translucent pink when the background is cleared to gray.

**Comment by icculus** [comment]
OpenGL renderer string: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.125.06
Ubuntu 22.04.2 LTS

It's probably the drivers. I'm getting random flickering in other apps, etc, too.

**Comment by Kontrabant** [comment]
I've used those drivers on the current version of Fedora at the time (37 I believe) without issue, aside from some occasional XWayland app flicker, which was a known bug.

It looks like Ubuntu 22.04 ships egl-wayland 1.1.9 from 2021, which is quite out of date as a significant amount of fixes and improvements happened during the last two years.  That could be the issue, as newer drivers won't necessarily help if the rest of the software stack is too old to support all of the more recently supported features.

**Comment by icculus** [comment]
I'm going to assume this is me and not SDL, then, and close this issue. Thanks everyone!
