### ISSUE TITLE
Cannot compile and link SDL with cmake if the absolute path has spaces.

### ISSUE THREAD

**Issue by Tykveg** [libsdl-org/SDL#7980]
For example, my game has path: `path/with spaces/game/`
And the `game` directory look like this:
```
game
    SDL            // SDL repo clone
    hdr            // hpp files
    src            // cpp files
    CMakeLists.txt // my cmake script
```
My `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.0)
set(PROJECT_NAME testl)
project(${PROJECT_NAME} CXX)

add_subdirectory(SDL EXCLUDE_FROM_ALL)

file(GLOB hdrs "${CMAKE_CURRENT_SOURCE_DIR}/hdr/*.h*")
file(GLOB srcs "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")

include_directories(${CMAKE_CURRENT_SOURCE_DIR}/hdr)

add_executable(${PROJECT_NAME} ${srcs} ${hdrs})

target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3)

set_target_properties(${PROJECT_NAME} PROPERTIES LINKER_LANGUAGE CXX)
```
When building everything (SDL and my game) at the end of building SDL I get this:
```
[build] [ 96%] Building C object SDL/CMakeFiles/SDL3-shared.dir/src/sensor/dummy/SDL_dummysensor.c.o
[build] [ 97%] Linking C shared library libSDL3.so
[build] /usr/bin/ld: cannot open linker script file path/with: No such file or directory
[build] collect2: error: ld returned 1 exit status
[build] gmake[2]: *** [SDL/CMakeFiles/SDL3-shared.dir/build.make:4428: SDL/libSDL3.so.0.0.0] Error 1
[build] gmake[1]: *** [CMakeFiles/Makefile2:128: SDL/CMakeFiles/SDL3-shared.dir/all] Error 2
[build] gmake: *** [Makefile:91: all] Error 2
[proc] The command: /usr/bin/cmake --build "path/with spaces/game/build" --config Release --target all -j 6 -- exited with code: 2
[driver] Build completed: 00:00:32.158
[build] Build finished with exit code 2
```
The path was suppose to be `path/with spaces/game/SDL/src/dynapi/SDL_dynapi.sym` because file `path/with spaces/game/build/SDL/CMakeFiles/SDL3-shared.dir/link.txt` has `-Wl,--version-script=path/with spaces/game/SDL/src/dynapi/SDL_dynapi.sym` without quotation marks at the end.
I believe it's because of [those lines of code](https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L274).
```cmake
check_linker_flag(C "-Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/src/dynapi/SDL_dynapi.sym" HAVE_WL_VERSION_SCRIPT)
if(HAVE_WL_VERSION_SCRIPT)
  target_link_libraries(sdl-shared-build-options INTERFACE "-Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/src/dynapi/SDL_dynapi.sym")
else()
  if((LINUX AND LIBC_IS_GLIBC) OR ANDROID)
    message(FATAL_ERROR "Linker does not support '-Wl,--version-script=xxx.sym'. This is required on the current host platform (${SDL_CMAKE_PLATFORM}).")
  endif()
endif()
```
My solution is to change this line:
```cmake
target_link_libraries(sdl-shared-build-options INTERFACE "-Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/src/dynapi/SDL_dynapi.sym")
```
to this:
```cmake
target_link_libraries(sdl-shared-build-options INTERFACE "-Wl,--version-script=\"${CMAKE_CURRENT_SOURCE_DIR}/src/dynapi/SDL_dynapi.sym\"")
```
So I just add quotation marks around path. After this change, everything builds, compiles and links normally.
And adding quotation marks manually in `path/with spaces/game/build/SDL/CMakeFiles/SDL3-shared.dir/link.txt` and building again also works (after the linker error).

And for whatever weird reason, doing the same with this line:
```cmake
check_linker_flag(C "-Wl,--version-script=\"${CMAKE_CURRENT_SOURCE_DIR}/src/dynapi/SDL_dynapi.sym\"" HAVE_WL_VERSION_SCRIPT)
```
breaks everything so the error message `Linker does not support '-Wl,--version-script=xxx.sym'. This is required on the current host platform (${SDL_CMAKE_PLATFORM}).` will show all the time (because I use Linux).

I don't know if my fix breaks something but it worked for me.

**Comment by madebr** [comment]
Never mind, the issue is with `target_link_options` <-> `target_link_libraries`.

**Comment by madebr** [comment]
Can you try https://github.com/libsdl-org/SDL/pull/7923?

**Comment by Tykveg** [comment]
Sorry, I was out.

> Can you please build the script above, and post your results?

Got same results.

> Can you try https://github.com/libsdl-org/SDL/pull/7923?

Yeah, with those fixes everything builds, compiles and links normally.
