### ISSUE TITLE
Memory leak while setting Desktop display mode (Windows)

### ISSUE THREAD

**Issue by RPP-dev** [libsdl-org/SDL#7982]
In Windows 10, _WIN_AddDisplays()_ seems to be called twice.

Additonally, in _WIN_GetDisplayMode()_ there is a memory allocation:

`data = (SDL_DisplayModeData *)SDL_malloc(sizeof(*data));`

The second _WIN_AddDisplays()_ call cause to override the first allocation causing the leak (220 bytes per each monitor you have and each time you call to init and quit the video system).

I dont know why this function is called twice (it could be on purpose or another bug that should be fixed) so, I have a patch that only avoid this memory leak modifying the _SDL_SetDesktopDisplayMode()_ function.

_WIN_AddDisplay()_ addressed a similar memory leak calling to _SDL_ResetFullscreenDisplayModes()_ but nothing is done with the desktop mode.

It could not be the cleanest way of removing the memory leak but it was I am using on my project.

I have a patch here: https://github.com/libsdl-org/SDL/compare/main...RPP-dev:SDL:main

Before creating the pull request I would like to know your opinion on this fix.

Thanks
Regards

**Comment by slouken** [comment]
I'd like to find out why SDL_SetDesktopDisplayMode() is getting called twice. How many monitors do you have connected? Can you print out the value of info->szDevice before it gets called?

**Comment by RPP-dev** [comment]
Hi, although it is some months late... I have 2 monitors connected.
I can see the fix has been implemented so thank you very much!

No more memory leaks because of this :)
