### ISSUE TITLE
Please commit gamepad UI images in an editable form

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#7983]
In recent versions of SDL3, the various bitmaps used in the UI for gamepad testing/mapping are committed to git as C header files containing hex-encoded bytes, rather than as binary .bmp files. Presumably this means that whenever they are edited, maintainers are either converting them back to binary, editing them, converting the edited version to hex and committing that; or editing some external version that is not in SDL.git, converting it to hex and committing it.

From the point of view of giving all users the same ability to contribute features and bug fixes, it would be better if the editable bitmap files were committed to this repo, like they are in SDL2.

Ideally, I'd prefer it if the git repo contained .bmp files, and there was an automated step at build time (done by the CMake build system) to "compile" them into C header files that don't get committed. I can contribute a Perl or Python script to do this, if that would be helpful. That would make `SDL_TESTS` require Perl or Python (like generating man pages already requires Perl).

If that optional build-dependency would be a problem for one of the supported platforms (presumably this means Windows!), then the next best thing would be to have the .bmp files and the script that generates the C headers committed to git, but *also* commit the pre-generated C headers for extra convenience for systems where running Perl is difficult (and OS distros that feel strongly about generating everything from source code, like Debian, can delete and re-generate those C headers).

**Comment by madebr** [comment]
[CMake has a way to read binary data](https://cmake.org/cmake/help/v3.16/command/file.html#read), so it should be possible to hook it up there.

**Comment by slouken** [comment]
I'll check in the BMP files, but we need to have the headers checked in as well, for the Visual Studio and Xcode projects.

**Comment by ericoporto** [comment]
Added in https://github.com/libsdl-org/SDL/commit/689555a4007a14eae75ab997783cc59b7dda6548

**Comment by madebr** [comment]
Since #7992, the headers are automatically re-generated by CMake, using a python script

**Comment by smcv** [comment]
Thanks, the experimental Debian packaging for SDL3 is now deleting the generated headers and using the Python script to regenerate them from the bitmaps (which gives me a much smaller diff to review for each update).
