### ISSUE TITLE
[ Question ] SDL3 license

### ISSUE THREAD

**Issue by avafinger** [libsdl-org/SDL#7988]
Can someone clarify what is the SDL3 license? I could only find SDL2 is zlib license.
Straight to the point, i have been asked to release the code for a small application that has Apache 2.0 code and is linked to SDL2, which is license incompatible. Apache License 2.0 is compatible with GPLv3 but by mixing the code the resulting software must be released under GPLv3.

**Comment by okuoku** [comment]
> that has Apache 2.0 code and is linked to SDL2, which is license incompatible

These licenses are compatible; unlike GPL2/3, both Apache2.0 and zlib do not require to follow their own terms for linked materials. I'd guess you might saw "GPL2 is incompatible with Apache2.0 and GPL3 is compatible" elsewhere but it doesn't mean Apache2.0 software cannot mix materials that has been licensed under another license(s).

Real world example is Android emulator of Android SDK. It's licensed under Apache2.0 and linked against PNG reference library which is licensed under zlib license https://android.googlesource.com/platform/prebuilts/android-emulator/+/7c9394a2f934c4f2108225ab8f2cd46c04577642/linux-x86_64/NOTICE.txt

**Comment by icculus** [comment]
SDL3 will be zlib-licensed, same as SDL2.

You can link it with Apache-licensed code, and it does not require you to release the source code to your program.

**Comment by avafinger** [comment]
A portion of the code is under Apache 2.0, which makes use of FFmpeg (LGPL 2.1) and originally was released under an Apache 2.0 license. The new derivative work is linked against SDL2 (zlib license). 
If i want to release the code, what license should it be, or a dual license, or it is not possible?

**Comment by okuoku** [comment]
> So, the derivative work "uses" the library (ffmpeg and sdl2 / sdl3)

Yes, as long as FFmpeg is dynamically linked.

In case you had linked FFmpeg statically, you must provide a way to re-link your app. For example, Bun uses statically-linked WebKit that is LGPL2.1,  uWebSocket which is Apache2.0, and zlib which is zlib licensed; Bun itself is MIT licensed https://bun.sh/docs/project/licensing . Bun document provides how to re-link it.

> and the license must be Apache 2.0.

No. You can choose any license(, except GPL2 which is not compatible with existing Apache 2.0 portions.) 

Anyway, SDL is zlib licensed and doesn't force choosing any license for users.

**Comment by avafinger** [comment]
Ok, I get it now, thanks!
