### ISSUE TITLE
xinmo dual arcade usb contoller board requires manual mapping in emulation station desktop edition

### ISSUE THREAD

**Issue by sandfm2** [libsdl-org/SDL#7991]
Hi, Emulation Station DE Leon asked me to request sdl be updated to include my Xin-Mo dual arcade controller board (allows 2 sets of arcade sticks and buttons to be connected and functional in windows computer via usb).   the arcade sticks and buttons (player  1 and player 2) work okay in windows, but arent fully/properly mapped  (most buttons not usable) in ES-DE.  

i found the below SDL mapping on the internet, which provided a good mapping for ES-DE.  once added to ES-DE es_controller_mappings.cfg file, both (xinmo board connected) player 1 and player 2 buttons worked well.  Also, mappings could also be further adjusted/overriden (if preferred) via the ES-DE  user interface (which results in updates to es_input.xml), where this was not possible without the es_controller_mapping.cfg update.   

es_controller_mappings.cfg (renamed to .txt) attached 
[es_controller_mappings.txt](https://github.com/libsdl-org/SDL/files/12063789/es_controller_mappings.txt)

**Comment by slouken** [comment]
Thanks for the contribution, but this is one of those boards that's used in different configurations without any application visible changes. This mapping will work for your board, but will break for other people, so we won't include it in the official SDL release.

Cheer,
