### ISSUE TITLE
SDL_strndup doesn't match POSIX strndup behaviour

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#7993]
In POSIX, it's OK to use `strndup()` on unterminated strings: for example

```
char abxy[] = { 'a', 'b', 'x', 'y' };

ab = strndup(abxy, 2);
assert(strcmp(ab, "ab") == 0);
```

It looks as though SDL's new `SDL_strndup` will read beyond the end of the array while evaluating `SDL_strlen`.

I think it would be safer and less surprising for `SDL_strndup` to have the same semantics as POSIX `strndup`. I see two ways to do this:

1. implement `SDL_strnlen()` with the semantics of POSIX `strnlen()` and make `SDL_strndup()` use it to get `len`;
2. implement it inline in `SDL_strndup()`

`strnlen` is basically this:

```
size_t len = 0;

while (len < max_len && string[len] != '\0') {
    len++;
}

return len;
```

**Comment by slouken** [comment]
Adding strnlen sounds like a good idea.
