### ISSUE TITLE
SDL_SetWindowSize() no longer generates SDL_WINDOWEVENT_RESIZED

### ISSUE THREAD

**Issue by BeagleJoe** [libsdl-org/SDL#8001]
This is required for some OpenGL apps to resize the viewport.

**Comment by slouken** [comment]
SDL_WINDOWEVENT_RESIZED means the user resized the window. SDL_WINDOWEVENT_SIZE_CHANGED means the size of the window changed and the OpenGL viewport needs to be recalculated.

This is an easy mistake, and one that's bitten me as well. SDL 3.0 has made this more clear, with SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED being the one that you should watch for to resize the viewport.
