### ISSUE TITLE
SDL3's testlocale on msys2  is slower then SDL2's testlocale

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8002]
Quick comparison:
- current SDL3: https://github.com/libsdl-org/SDL/actions/runs/5589750584/jobs/10218500715#step:11:691 (6.77s)
- current SDL2: https://github.com/libsdl-org/SDL/actions/runs/5582047079/jobs/10200904814#step:11:85 (0.02s)

In https://github.com/libsdl-org/SDL/pull/7923, I'm somehow making it worse because it sometimes times out (10s limit).
For some reason, clang32 is the slowest and is the one that started me to notice this issue.
ucrt64 does not have this regression, so we are probably tickling the mingw runtime wrong.

Occasionally, testfilesystem also times out. But not so frequent.

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/commit/e620925728b48b39f5d40e9b1d6e2e36fd2bc97f (with follow-up https://github.com/libsdl-org/SDL/commit/b1a0bc3fb0ad2198500cbddc2e8c73d8ec39de31) seems to have fixed it.
Alas, it's not a root cause.

**Comment by madebr** [comment]
I ssh'ed into a GitHub workflow using this github action: https://github.com/luchihoratiu/debug-via-ssh
But I can't reproduce timeouts when manually running `ctest` again and again.

**Comment by madebr** [comment]
Looks like I was wrong, and SDL2 is also suffering from this:
https://github.com/libsdl-org/SDL/actions/runs/5631444463/job/15258396467#step:11:146
```
test 7
      Start  7: testfilesystem

7: Test command: D:\a\SDL\SDL\build\test\testfilesystem.exe
7: Working Directory: D:/a/SDL/SDL/build/test
7: Environment variables: 
7:  SDL_AUDIODRIVER=dummy
7:  SDL_VIDEODRIVER=dummy
7: Test timeout computed to be: 10
 7/15 Test  #7: testfilesystem ...................***Timeout  10.30 sec
```

**Comment by madebr** [comment]
As a band-aid, we can re-run failed tests until they pass:
```
  --repeat until-pass:<n>      = Allow each test to run up to <n> times in
                                 order to pass
```

**Comment by slouken** [comment]
Let's not do that, CI already takes a long time, I don't want to extend it. I'd rather tests fail quickly and we have impetus to figure out what's going on.

**Comment by madebr** [comment]
Duplicate of #8214
