### ISSUE TITLE
How to properly add additional SDL libraries (SDL_ttf, SDL_mixer and others) in my project?

### ISSUE THREAD

**Issue by akimky** [libsdl-org/SDL#8003]
I apologize if my question turned out to be too stupid or there is no place for these questions, but I was sent to Google on StackOverflow, lowering the rating of the question.

I want to write a game on SDL 2 for ios. I have no problems connecting the main library. However, something is not clear to me when adding additional libraries, for example SDL_ttf. When connecting the main library, we simply drag the ready-made SDL.xcodeproj is included in our project and the build will work for various devices, including a simulator. However, SDL_ttf needs to be builded separately. And if it turns out that if I want to test my game first on the ipad, then on the iphone 6s, and then on the iphone 12, then I will have to build SDL_ttf 3 times for each of the devices. And if I want to release my app in the AppStore? Do I have to build them for all the devices? And when the new iPhone comes out, do I need to release a new one for it from the side for this phone? It sounds like some kind of nonsense, so I'm asking here.

I know that there is a possibility to build “all ios devices”, but then I will not be able to run the project for the simulator. And the problem will remain, but only for simulators. That is, if I want to test my game first on an iphone simulator and then on an ipad simulator, then I will have to build SDL_ttf for each of their simulator.

How to properly add additional SDL libraries (SDL_ttf, SDL_mixer and others) in my project?

**Comment by slouken** [comment]
Are you still stuck on this?

**Comment by Akimpaus** [comment]
Actually, yes. If someone would explain to me how to do it correctly, I would be very grateful. In YouTube and the Internet, in general, there are no tutorials on how to do this.

**Comment by slouken** [comment]
You should be able to add SDL and each subproject to your workspace and then add each library to your list of embedded frameworks. Then you can build your application for whatever target you want, and the dependencies should be built for that same target.

If that doesn't work with SDL2, could you try with SDL3 and see if that works better? We've made a bunch of improvements to the Xcode build process in SDL3.
