### ISSUE TITLE
SDL2.28.0 Exception during IOS exit

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#8005]
The screen turns black
I also tested 2.22, 2.0.16

**Comment by slouken** [comment]
Do you have a stack trace? Typically iOS applications are not supposed to exit, they're supposed to follow the application life cycle:
https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle?language=objc

SDL has events to help you manage this:
https://github.com/libsdl-org/SDL/blob/53882a2ed29f381bce110d95358ebbbff89aa6bd/include/SDL3/SDL_events.h#L71

**Comment by baidwwy** [comment]
Sorry, I don't know how to stack  trace yet

I added exit(0); to fix

**Comment by MoNTE48** [comment]
@baidwwy, this behaviour is forbidden by Apple's guideline and can be the reason why an app is rejected in the App Store, keep this in mind.
