### ISSUE TITLE
SDL_Init(SDL_INIT_EVERYTHING) tries to initialise disabled subsystems

### ISSUE THREAD

**Issue by sjnewbury** [libsdl-org/SDL#8008]
In Gentoo, libsdl2 has various subsystems enabled or disabled according to USEflags.  This means it's possible to have, for example, the "haptic" subsystem disabled at build time.

When SDL_Init(SDL_INIT_EVERYTHING) is called, the "haptic" subsystem is part of the included set, but fails to initialise because the code is not present.  SDL_Init() fails at this point.  If the return value isn't tested, and the application continues regardless, basic functionality appears to be working, only subsystems initialised after "haptic" are not started, such as "audio".

Is this the intended behaviour? Shouldn't SDL_INIT_EVERYTHING only initialise enabled subsystems?

**Comment by slouken** [comment]
Yep, that makes sense. Feel free to create a PR to remove disabled subsystems.

We've been toying with the idea of removing disabled subsystems in SDL 3, as it's always been a source of confusion and bugs, so if you have an important use case for that, please let us know!

**Comment by sjnewbury** [comment]
I don't mind creating a PR for it.  I'll take a look.

I just encountered such a "bug" in a project I'm contributing to, and improved the code so it's not an issue, but it seemed plenty of code out there does it, and as you say it causes confusion and bugs.  Although I suppose it also encourages people to only initialise what they actually need, if EVERYTHING doesn't actually work!

**Comment by sjnewbury** [comment]
A possible proposal:

- Create an SDL_ENABLE_MASK at configure time with the enabled subsystem flags, store it in SDL_config.h
- SDL_Init() filters the passed flags with SDL_ENABLE_MASK

Only downside is passing a disabled subsystem to SDL_Init() would then silently do nothing, so it would probably be necessary to only apply the filter when SDL_INIT_EVERYTHING is passed explicitly.

It shouldn't matter if SDL_INIT_EVERYTHING starts without error and a disabled subsystem is later used since it will just trigger a subsystem is uninitialised error and so just fails a little later.

Am I missing anything?

**Comment by slouken** [comment]
SDL_INIT_EVERYTHING has been removed in SDL 3.0, applications should only pass flags for the subsystems they care about, and if those subsystems are disabled, it's reasonable for the function to report failure.
