### ISSUE TITLE
Wrong version in VERSION INFO part of exe - https://libsdl.org/release/SDL-1.2.15-win32-x64.zip

### ISSUE THREAD

**Issue by necros2k7** [libsdl-org/SDL#8010]
1.2.14.0 not 1.2.15, not a super bug but still

**Comment by madebr** [comment]
Thanks for letting us know, but it is very unlikely we will ever spin a a revised SDL release.
Instead, we advise you to use [sdl12-compat](https://github.com/libsdl-org/sdl12-compat) instead. This library provides a sdl1.2 compatibility layer, using SDL2.

**Comment by necros2k7** [comment]
@madebr , sdl12-compat - can it be called "latest" release of 1.2 branch?

**Comment by madebr** [comment]
It's the only sdl 1.2 incarnationthat is somewhat supported.
But only for old projects, not for new ones.
