### ISSUE TITLE
SDL_GetDefaultAudioInfo() broken: it shouldn't be able to cause SDL_GetError() "That operation is not supported" if SDL2 audio playback picks another than card 0 if not overridden

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#8012]
On my machine, `SDL_GetDefaultAudioInfo()` for an output device errors with `SDL_GetError()` afterward returning `"That operation is not supported"`. But when I actually open an audio device via `SDL_OpenAudioDevice()` without specifying the sound card, SDL2 **doesn't just pick** the output device with index 0 named by `SDL_GetAudioDeviceName(0, 0)`. That makes no sense to me:

This feels like potentially a bigger conceptual error. It looks from the outside like SDL2 uses another mechanism than it gives me for obtaining the default card since clearly it still picks one somehow that isn't card 0, while it can't return that to me. For more advanced audio engines, this seems like a bigger problem since they would want to have high control over sound card choice while not being cut off from picking or knowing the proper default. But that's kind of what any SDL app would run into on my machine right now, my code ends up broken because it's "too nosy" about first examining the default, not getting any, and ending up going to the wrong speakers.

**Seen with SDL2 version:** SDL2-2.26.3-1.fc37

**Seen on OS:** Linux as provided by Fedora 37

**Seen with audio system:** pulseaudio is picked when actual playback starts, not sure if SDL_GetDefaultAudioInfo is confused and tries to go for pipewire or something else ill-advised and that is maybe part of the problem

**Comment by ell1e** [comment]
Okay, if I had to guess due to generally having trouble with broken pipewire on this system, after some more prodding I assume that audio playback tries pipewire, fails to use it, then tries pulseaudio and succeeds (and plays on what the pulseaudio server considers the default audio device). It seems like SDL_GetDefaultAudioInfo on the other hand tries pipewire, also fails to use it, but then just returns the error instead of following the same fallback path that playback does. But that's just a wild guess on my behalf.

**Comment by icculus** [comment]
SDL either uses a backend totally or not at all; if PipeWire fails to initialize, it won't use any piece of it thereafter, so we can't get into a position where it uses GetDefaultAudioInfo from the wrong backend.

(Also, SDL2 tries PulseAudio before PipeWire, so it would never even try to initialize PipeWire if Pulse worked out.)

**Comment by icculus** [comment]
Actually, the question is _what_ backend did you end up with? SDL will set that error message if the backend doesn't have GetDefaultAudioInfo implemented, but PulseAudio and PipeWire both do. Is it possible you ended up in the "dsp" (Open Sound System) backend or something?

Could you add this to your program right before the GetDefaultAudioInfo call and see what it reports?

```c
SDL_Log("Current audio backend: %s", SDL_GetCurrentAudioDriver());
```

**Comment by ell1e** [comment]
These calls were right after each other, so if that didn't have them use the same backend that sounds like a bug in itself. Sadly, after a reboot the phenomenon went away for now, but maybe it would be possible to investigate if SDL_GetDefaultAudioInfo and SDL_OpenAudioDevice always use the same backends since it seems like that's not reliably the case. (And I'm not talking of situations where it's a timing issue where the true backend availability changes just in between, but where nothing changed.)

**Comment by ell1e** [comment]
I'm wondering now if Fedora in their pipewire obsession implemented something where the dsp or some other completely unrelated backend was emulated by Pipewire. It wouldn't surprise me, maybe that would explain what I saw. Nevertheless, once it repeats (I'm expecting that to happen sooner or later) I'll collect more info.

**Comment by icculus** [comment]
Yeah, a lot of these things tend to emulate each other (notably: PipeWire will _definitely_ emulate PulseAudio, so SDL thinks it's talking to Pulse but it's eventually going through a broken PipeWire install).

They often offer an ALSA emulation too, which is likely what you landed in and would produce this error in SDL.

Anyhow, if it pops up again, we can dig deeper, but you're probably right that it cleared out with the reboot.

**Comment by ell1e** [comment]
If this would show with ALSA emulation I'm just going to assume that is what happened and that it's not an SDL2 bug after all. Man, I'm really annoyed with Pipewire sometimes. Anyways, apologies for the invalid issue filed.
