### ISSUE TITLE
Win10: Gamepad Power Level broken in latest SDL3?

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#8015]
I've just noticed power level has stopped working in the latest source, it always reports unknown. If I disable RawInput, it will always report empty.

Tested on XBox One S controller and a Chinese PS4, both do the same. I'm certain this used to work, so I guess the recent changes to this area broke something?

**Comment by slouken** [comment]
The XInput calls themselves are saying the battery is disconnected. Can you try older SDL versions to find one that works?

**Comment by AntTheAlchemist** [comment]
I'll look into it now 👍🏼

**Comment by slouken** [comment]
For the PS4 controller, we only read the battery status for official controllers. If you disable that check in SDL_hidapi_ps4.c, does it work for you?

**Comment by AntTheAlchemist** [comment]
My Chinese PS4 controller (PS-P01-WirelessController) is being detected as an `official_controller`, and the battery is always reported as empty (it's at 80% according to Win10), even with RAWINPUT enabled.

```
Gamepad Name PS4 Controller
Type PS4
Touchpads 1 Maximum Fingers 2
Sensors gyroscope 250 Hz accelerometer 250 Hz
Mapping 05008fe54c050000c405000000006800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,touchpad:b15,crc:e58f,platform:Windows,
Features LED rumble
Serial 20-20-12-15-04-4d
Product ID 1476
Vendor ID 1356
```

**Comment by slouken** [comment]
It sounds like the controller isn't providing the battery data in the report. You can check the report handling in SDL_hidapi_ps4.c

**Comment by AntTheAlchemist** [comment]
Doesn't seem to be in enhanced mode despite the hint that enables it.

`k_ePS4FeatureReportIdCapabilities` returns -1, and because the `vendor_id` claims it's Sony, a bunch of `ctx` get set to true. Sensors, LED, vibration and touchpad don't work via Bluetooth, so I guess the battery doesn't for the same reason...  

Going back a few weeks and the Xbox controller still doesn't report a battery. Might it be an issue with Windows?

**Comment by AntTheAlchemist** [comment]
I've just tried my 8BitDo SN30pro, which reports the battery ok. Although when wired, it doesn't report wired, still reports battery level.

So, it's just the Xbox controller not reporting the battery. I did recently upgrade the firmware, which might be why:

```
Power Unknown
Gamepad Name Xbox One S Controller
Type Xbox One
Mapping 030082795e040000200b000017057200,*,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,crc:7982,platform:Windows,
Features rumble rumble-triggers
Serial null
Product Version 1303
Product ID 2848
Vendor ID 1118
```

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
