### ISSUE TITLE
Mistake in the wiki page of "SDL_Rect"?

### ISSUE THREAD

**Issue by rempas** [libsdl-org/SDL#8017]
**Info**
So, in the wiki page about [SDL_Rect](https://wiki.libsdl.org/SDL2/SDL_Rect), there is an example about how to use it with "SDL_BlitSurface". Based on the wiki page about [SDL_BlitSurface](https://wiki.libsdl.org/SDL2/SDL_BlitSurface), the code example doesn't appear to be correct! Specifically, in the [remarks](https://wiki.libsdl.org/SDL2/SDL_BlitSurface#remarks) section, it states that:

> The width and height in srcrect determine the size of the copied rectangle

Based on that, I do understand that "srcrect" will determine the size (width and height) and from where (X and Y) on the surface about to BE COPIED (aka "foreground") it will begin counting for the pixels to be copied. Then, it says:

> Only the position is used in the dstrect (the width and height are ignored)

Based on that, I do understand that "dstrect" controls where the surface is to be copied in the surface that is to be copied TO (aka "background"). As someone who have never worked with graphics and pixels before, this make **TOTAL SENSE** to me and this is how I expect it to work.

**Problem**
In the page of "SDL_Rect", the example, messes up the second part. Instead of not setting (meaning, set to `0`) the "X" and "Y" fields of "dstrect" as they are gonna be ignored as stated in the wiki page of "SDL_BlitSurface", the example does not set the "X" and "Y" fields of "srcrect". And not only that, it also sets the fields of "dstrect" to the value of `32` even tho they are gonna have no effect and I was expecting it to set the to `0`.

For me, I happened to watch a tutorial series on YouTube that used "SDL_BlitSurface" without introducing "SDL_Rect" so, I first looked in the wiki page about "SDL_BlitSurface" to figure out how it works and then learned about "SDL_Rect" and looked at the its page, after I have read the "Remarks" section. So, even before copying the example in the "SDL_Rect" page, it seems weird to me.

But after playing with it, I confirmed that it is indeed wrong. Even further, I tried to change the "X" and "Y" fields of "dstrect" and it indeed seems to not have any effects. While changing the "X" and "Y" fields of "srcrect" indeed changes the position of the "foreground".
 
**NOTE:**
As I was writing this, I checked the example and tried to think a little bit more and, it may seem that maybe the example means to just set the position of the surface to "foreground" to `0` instead of meaning that this is the "ignored" and "unset" position object.

But even then, this still doesn't explain why the "X" and "Y" of "dstrect" have been set. This is confusion and in that case, I would request the modification of the wiki page example about "SDL_Rect" because in that case, it is confusing, especially for a beginner. Thank you for your time!

**Comment by madebr** [comment]
This is indeed a pitfall: the size of `dstrect` is not taken into account.
Would the following be acceptable for SDL3?
```patch
--- a/src/video/SDL_surface.c
+++ b/src/video/SDL_surface.c
@@ -713,6 +713,14 @@ int SDL_BlitSurface(SDL_Surface *src, const SDL_Rect *srcrect,
         h = src->h;
     }
 
+    /* clip to the destination rectangle */
+    if (w > dstrect->w) {
+        w = dstrect->w;
+    }
+    if (h > dstrect->h) {
+        h = dstrect->h;
+    }
+
     /* clip the destination rectangle against the clip rectangle */
     {
         SDL_Rect *clip = &dst->clip_rect;
```
sdl2-compat will have to override `dstrect->w` and `dstrect->h`.

**Comment by madebr** [comment]
You'e probably right.
The wiki data lives at https://github.com/libsdl-org/sdlwiki.
So perhaps, you might create a pr there while it's still fresh in your head.

**Comment by rempas** [comment]
> You're probably right. The wiki data lives at https://github.com/libsdl-org/sdlwiki. So perhaps, you might create a pr there while it's still fresh in your head.

Oh, is this how it works? Shouldn't someone confirm that first? I mean, I may be wrong....

**Comment by slouken** [comment]
Y

**Comment by slouken** [comment]
> This is indeed a pitfall: the size of `dstrect` is not taken into account. Would the following be acceptable for SDL3?
> 
> ```diff
> --- a/src/video/SDL_surface.c
> +++ b/src/video/SDL_surface.c
> @@ -713,6 +713,14 @@ int SDL_BlitSurface(SDL_Surface *src, const SDL_Rect *srcrect,
>          h = src->h;
>      }
>  
> +    /* clip to the destination rectangle */
> +    if (w > dstrect->w) {
> +        w = dstrect->w;
> +    }
> +    if (h > dstrect->h) {
> +        h = dstrect->h;
> +    }
> +
>      /* clip the destination rectangle against the clip rectangle */
>      {
>          SDL_Rect *clip = &dst->clip_rect;
> ```
> 
> sdl2-compat will have to override `dstrect->w` and `dstrect->h`.

The destination width and height are ignored by design. I clarified the documentation in https://github.com/libsdl-org/SDL/commit/2e7d2b94ebf614b9711c76ce9bafe9e814b54ee4
