### ISSUE TITLE
SDL_ALSA_SHARED (Wanted: ON): OFF

### ISSUE THREAD

**Issue by davesworking** [libsdl-org/SDL#8018]
Hi,

builds are working on Windows, Mac and Linux x86. Linux ARM64 says:

-- Looking for snd_pcm_recover in asound
-- Looking for snd_pcm_recover in asound - not found

Logs are showing some fatal errors. Is there some package missing? I have installed libpulse-dev libasound2-dev.

Thanks!

[CMakeError.log](https://github.com/libsdl-org/SDL/files/12131122/CMakeError.log)
[CMakeOutput.log](https://github.com/libsdl-org/SDL/files/12131123/CMakeOutput.log)

**Comment by madebr** [comment]
When you are cross building, you need to configure with [a cmake toolchain](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html).

This is the test that fails:
```
Determining if the function snd_pcm_recover exists in the asound failed with the following output:
Change Dir: /Linux-ARM64/aarch64-glibc2.31-gcc10.2/build_cmake/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_8c29a/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_8c29a.dir/build.make CMakeFiles/cmTC_8c29a.dir/build
gmake[1]: Entering directory '/Linux-ARM64/aarch64-glibc2.31-gcc10.2/build_cmake/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8c29a.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -std=c99 -g -I/Linux-ARM64/aarch64-glibc2.31-gcc10.2/alsa2/usr/include -idirafter "/Linux-ARM64/aarch64-glibc2.31-gcc10.2/libsdl/src/video/khronos" -DCHECK_FUNCTION_EXISTS=snd_pcm_recover  -D_GNU_SOURCE=1 -o CMakeFiles/cmTC_8c29a.dir/CheckFunctionExists.c.o -c /Developer/teamcity/work/e7a9578bd49a8fa6/re_custom_tool/cmake-3.24.3/share/cmake-3.24/Modules/CheckFunctionExists.c
Linking C executable cmTC_8c29a
/Developer/teamcity/work/e7a9578bd49a8fa6/re_custom_tool/cmake-3.24.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8c29a.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -std=c99 -g -I/Linux-ARM64/aarch64-glibc2.31-gcc10.2/alsa2/usr/include -idirafter "/Linux-ARM64/aarch64-glibc2.31-gcc10.2/libsdl/src/video/khronos" -DCHECK_FUNCTION_EXISTS=snd_pcm_recover  -D_GNU_SOURCE=1 -Wl,-rpath=\\$ORIGIN  -Wl,--enable-new-dtags -L/Linux-ARM64/aarch64-glibc2.31-gcc10.2/alsa2/usr/lib  -rdynamic CMakeFiles/cmTC_8c29a.dir/CheckFunctionExists.c.o -o cmTC_8c29a  -lasound 
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_8c29a.dir/build.make:99: cmTC_8c29a] Error 1
gmake[1]: Leaving directory '/Linux-ARM64/aarch64-glibc2.31-gcc10.2/build_cmake/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_8c29a/fast] Error 2
```

If I modified the commands correctly, these commands fail:
```
/usr/bin/cc -fPIC -std=c99 -g -I/Linux-ARM64/aarch64-glibc2.31-gcc10.2/alsa2/usr/include -idirafter "/Linux-ARM64/aarch64-glibc2.31-gcc10.2/libsdl/src/video/khronos" -DCHECK_FUNCTION_EXISTS=snd_pcm_recover  -D_GNU_SOURCE=1 -o /tmp/CheckFunctionExists.c.o -c /Developer/teamcity/work/e7a9578bd49a8fa6/re_custom_tool/cmake-3.24.3/share/cmake-3.24/Modules/CheckFunctionExists.c
/usr/bin/cc -fPIC -std=c99 -g -I/Linux-ARM64/aarch64-glibc2.31-gcc10.2/alsa2/usr/include -idirafter "/Linux-ARM64/aarch64-glibc2.31-gcc10.2/libsdl/src/video/khronos" -Wl,-rpath=\$ORIGIN  -Wl,--enable-new-dtags -L/Linux-ARM64/aarch64-glibc2.31-gcc10.2/alsa2/usr/lib  -rdynamic /tmp/CheckFunctionExists.c.o -o /tmp/snd_test  -lasound 
```
So you need to create a cmake toolchain file, and/or add arguments to cmake such that the commands above succeed.

**Comment by sezero** [comment]
This seems to be with SDL2 2.26.x and older. After https://github.com/libsdl-org/SDL/pull/6741, the check for `snd_pcm_recover` is removed which is not actually nice: In all SDL3, SDL2 and release-2.28.x branches, we should either put it back or add `>=1.0.11` checks to alsa-lib search (since we aren't using pkg-config for alsa, I don't know how to do that.)

**Comment by madebr** [comment]
The error is `cannot find -lasound`, not `cannot find "snd_pcm_recover" symbol`.
So I'm not sure the checks are at fault here.

**Comment by sezero** [comment]
(My comment was off-topic, yes.)

**Comment by davesworking** [comment]
Sorry, could you just clarify _"If I modified the commands correctly, these commands fail:"_ ?

(It's late on a Friday and "correctly" and "fail" together are not making sense to me)

Thanks!

**Comment by madebr** [comment]
> Sorry, could you just clarify _"If I modified the commands correctly, these commands fail:"_ ?

It seems like the linker cannot find `libasound.so`, so you need to pass configure the library search path (`-L`) correctly.
The exact path depends on what distribution you use.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
