### ISSUE TITLE
Could we use X11 back-end for older macOS, for which Cocoa one is broken?

### ISSUE THREAD

**Issue by barracuda156** [libsdl-org/SDL#8021]
X11 back-end builds perfectly fine on macOS PowerPC with no patching to it.

macOS-specific files, _excluding Cocoa Video and Joystick,_ require absolutely minimal fixes: https://github.com/macports/macports-ports/blob/780e00f02d9bd8a098f9e4b6712937cf49bc0b62/devel/libsdl2/files/0001-Fixes-for-PowerPC.patch
These should be mergeable (obviously, not like in the linked patch, but conditionally, so that clangisms are not used where they are not supported).

(Cocoa Video is broken, fixing it is non-trivial and would not be accepted to merge even if fixed, since it gonna require massive rewriting of the existing code. Therefore, X11.)

Now, there are three issues which I would like to get advice on:

1. Is X11 back-end generally believed to work on macOS? If yes, can we make it the default for < 10.7 and then allow builds for those OS?
2. Is there a generic Unix implementation for Joystick module, to use on the older macOS? The present code does not build due to an unfixed bug in GCC, which causes ICE. See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105522
Since that code was introduced in a huge re-write of Joystick module, I did not see an easy way to fix it by a minor revert.
Besides that, it is likely its macOS-specific implementation is broken beyond repair for < 10.7 and should be disabled anyway.
3. The same GCC bug affects Hidapi. I could revert a breaking commit to make it build: https://github.com/macports/macports-ports/blob/780e00f02d9bd8a098f9e4b6712937cf49bc0b62/devel/libsdl2/files/0002-hidapi-revert-a-commit-that-triggers-ICE-with-GCC.patch
Otherwise, Hidapi can be disabled to avoid this issue.

Since many games and emulators require Joystick to be enabled, this issue is pretty relevant (provided X11 itself works). Otherwise SDL2 won’t be too useful for end-users on older macOS.

**Comment by slouken** [comment]
We don't have a PowerPC Mac in the core SDL developers, and Apple likes to break compatibility regularly, so there isn't any practical method of maintaining support in the main SDL code.

However, there are some people who have forked SDL and it's certainly reasonable to have a semi-official port for older macOS. You may want to coordinate with @Wohlstand, who's doing similar work.

**Comment by barracuda156** [comment]
@slouken Thank you for replying. macOS PowerPC won’t change anymore, and with X11 back-end we do not need any significant patching. I also do not imply that some ongoing testing will be done on your end, of course.
If we could make a one-time fix, that would be awesome.
I think that anything outside of Cocoa will work normally, as it usually does.

Joystick is an open question though, for which I currently do not have a solution.

@Wohlstand Maybe you can advise something here? Will be very much appreciated.

**Comment by Wohlstand** [comment]
Hello!

I actually trying to make the SDL2 to work on Mac OS X Tiger, and I actually have the game to run on X11 (I made an attempt to make the Cocoa parts work, and I made them work, except video. Joystick just doesn't work).

What I did:
- I took some parts of SDL2 and I made a "platform" named "tiger" (among source code I mean) to don't touch and break anything for modern macOS.

All the stuff is here: https://github.com/Wohlstand/SDL/tree/mac-tiger

> Joystick is an open question though, for which I currently do not have a solution.

I did an attempt to make it work, but unfortunately it doesn't builds. Probably I'll need to take some parts of the old SDL2 code and make the "tiger" submodule for it if it works. There is a chance that HIDAPI thing would work to bring up joysticks are unknown to the Mac OS X itself.

To build it, it's required to use the Tiger Brew thing (the port of Homebrew for older Mac OS X) https://github.com/mistydemeo/tigerbrew

Here is full difference of the current state with a latest SDL2: https://github.com/libsdl-org/SDL/compare/SDL2...Wohlstand:SDL:mac-tiger

One note about this Mac: Here is an OpenGL 1.3, and it does NOT has the framebuffer, that means you will be unable to render into texture (if you have anything related, it will not work). Here is a full spec of OpenGL at me (an output of glxinfo from XTerm): [macminig4-opengl.txt](https://github.com/libsdl-org/SDL/files/12136988/macminig4-opengl.txt)


![Picture 61](https://github.com/libsdl-org/SDL/assets/6751442/680f2703-87c5-49d6-bb49-16d13562e03f)

**Comment by icculus** [comment]
Fwiw, the X11 backend _did_ work on macOS at some point (including accelerated OpenGL), but I cannot vouch for it in recent years.

I have a PowerPC Mac in the closet, but even if I were to set it up: if it's not on GitHub Actions, it's going to break again and stay broken, no matter what changes we make in this bug report.

**Comment by Wohlstand** [comment]
P.S. At the other side, I trying to make a cross-compiler toolchain that will build the thing that will work on PowerPC. That's because development on my Mac Mini is hard: primarily, it builds very slow. And also, I want to make a kind of CI that will be able to compile the stuff quickly.

**Comment by icculus** [comment]
(Also: can we make X11 the default for < 10.7? Absolutely not, because then we'll be fielding bug reports from people that built SDL but don't have an X server running. This sort of thing makes sense in a separate fork that is PowerPC-specific, like what @Wohlstand is/was working on.)

**Comment by Wohlstand** [comment]
At my game, I made a workaround to automatically run the X server if it wasn't launched yet (something like a Bash script that I included into the bundle of my game).

Also, the support is implemented via the CMake only, no autotools and no Xcode builds got been touched.

**Comment by Wohlstand** [comment]
Anyway, I guess, once I make the Cocoa subsystem work on my fork, I'll get a shot to make a pull-request to bring the Tiger Mac support here. As I already said, I implemented the legacy Mac as a different set of sources rathar than patching of existing codes, just to keep the modern Mac supported properly, and legacy Mac have a separated implementation.

**Comment by icculus** [comment]
(Honestly, if it's a separate thing for SDL2 that's just adding new "backends" that are Tiger-compatible versions of the existing code, I'm not against that getting merged, because SDL2 is about to go into limited maintenance mode. @slouken might reasonably disagree here, though, and I would not be willing to do this for SDL3 in any case.)

**Comment by Wohlstand** [comment]
(what about SDL3, I suggested making a kind of custom platform plugins concept to allow people to add and maintain the new platform support without pushing everything to the main SDL2 side, and there is a related issue made #6781)

**Comment by barracuda156** [comment]
@Wohlstand Very interesting, thank you! I will look into your branch.
The latest SDL we have built in Macports for PowerPC with Cocoa Video was 2.0.9, though it required replacing joystick with earlier source (I believe, 2.0.2) and substantial patching otherwise for Cocoa Video. Discussion thread is here: https://trac.macports.org/ticket/64655

I tried to port patches to 2.0.22 (which Macports has for 10.6 Intel) to make it work on 10.6 PowerPC, but Cocoa Video part turned hopeless and I gave up on it. With X11 backend it required minimal patches, with which 2.28.1 also builds fine, so I did that instead.

We are yet to determine usability though, since a larger chunk of ports which use SDL2 are broken for 10.6 for unrelated reasons or require dependencies which are broken, and 10.6 is the best we got for PowerPC.

P. S. If you make a PR to support Darwin PowerPC, please also make sure to add Leopard and Snow Leopard into that, as long as build arch is ppc/ppc64. It would be disappointing to have 10.4 fixed while leaving 10.5–10.6 broken.

**Comment by barracuda156** [comment]
> P.S. At the other side, I trying to make a cross-compiler toolchain that will build the thing that will work on PowerPC. That's because development on my Mac Mini G4 that I have, is hard: primarily, it builds very slow. And also, I want to make a kind of CI that will be able to compile the stuff quickly.

@Wohlstand If I can be helpful for PowerPC testing, please ping me anytime. I have pretty fast G5 machines, latest CMake, GCC 12.3.0 and everything else needed. I normally use 10.6 ppc (10A190), but I have a functional set-up for 10.5 and 10.4.

**Comment by slouken** [comment]
If you can get a cross-compiler working, that might work around the gcc ICE issue as well, and let more of the code work on PowerPC.

I'm not opposed to including this as a separate backend in SDL 2. Once it works it's not like we'll be making massive changes to either macOS or SDL.

**Comment by Wohlstand** [comment]
> I'm not opposed to including this as a separate backend in SDL 2. Once it works it's not like we'll be making massive changes to either macOS or SDL.

That's what I doing: avoiding any changes to mainstream macOS support of SDL: these modules will just being unused in legacy Mac OS X modules. Right now I named them as "cocoatiger" or just "tiger". Maybe I'll rename them as "cocoalegacy" or "applelegacy" or something like?

**Comment by barracuda156** [comment]
@Wohlstand Since we got identical problem on 10.4–10.6 (at least on PowerPC, where clangs are broken), that would make sense, I believe.

**Comment by Wohlstand** [comment]
About the cross toolchain: At the first attempt, I used the gcc 7.3 (the same as Tigerbrew has), and once I got ot built successfully, but something went wrong, or I doing wrong to make the CMake platform: any project fails to find any generic C headers during configure tests, etc. But as I updated my main OS, I need to rebuild the toolchain again, and also try to fix other mess.

**Comment by Wohlstand** [comment]
> Since we got identical problem on 10.4–10.6 (at least on PowerPC, where clangs are broken), that would make sense, I believe.

Old Macs has GCC only, no Clang at all. Also, there are all binaries were GCC compatible, and if get a shot to make a Clang toolchain, need to make sure it produces GCC-comaptible objects.

**Comment by Wohlstand** [comment]
P.S. I do have a pile of mess at my place, and I should systematize the stuff to make the toolchain being easily built. at any machine.

**Comment by barracuda156** [comment]
> Old Macs has GCC only, no Clang at all. Also, there are all binaries were GCC compatible, and if get a shot to make a Clang toolchain, need to make sure it produces GCC-comaptible objects.

@Wohlstand On Intel you can use modern Clangs. Just not on PowerPC.

**Comment by barracuda156** [comment]
> Fwiw, the X11 backend _did_ work on macOS at some point (including accelerated OpenGL), but I cannot vouch for it in recent years.

@icculus Strangely, while makefiles build has no issues with X11 on macOS, with CMake I am struggling to make it enabled, and still unsuccessfully.

**Comment by Wohlstand** [comment]
On my end there is the CMake build, and I use Ninja build instead of Makefiles. Both ways should work.

**Comment by barracuda156** [comment]
@Wohlstand I meant without CMake at old, building old way, everything works fine with X11. With CMake, I get all X11 forced to be off. I will check what setting you have to make it work.

On a side note, here are tests. Not sure yet why atomics fails:
```
--->  Testing libsdl2
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_libsdl2/libsdl2/work/build" && /usr/bin/make test 
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_libsdl2/libsdl2/work/build
      Start  1: testatomic
 1/15 Test  #1: testatomic .......................***Timeout  10.03 sec
      Start  2: testerror
 2/15 Test  #2: testerror ........................   Passed    5.14 sec
      Start  3: testthread
 3/15 Test  #3: testthread .......................   Passed   10.11 sec
      Start  4: testlocale
 4/15 Test  #4: testlocale .......................   Passed    0.11 sec
      Start  5: testplatform
 5/15 Test  #5: testplatform .....................   Passed    0.11 sec
      Start  6: testpower
 6/15 Test  #6: testpower ........................   Passed    0.13 sec
      Start  7: testfilesystem
 7/15 Test  #7: testfilesystem ...................   Passed    0.12 sec
      Start  8: testtimer
 8/15 Test  #8: testtimer ........................   Passed   27.19 sec
      Start  9: testver
 9/15 Test  #9: testver ..........................   Passed    0.13 sec
      Start 10: testqsort
10/15 Test #10: testqsort ........................   Passed    0.16 sec
      Start 11: testaudioinfo
11/15 Test #11: testaudioinfo ....................   Passed    0.10 sec
      Start 12: testsurround
12/15 Test #12: testsurround .....................   Passed    0.28 sec
      Start 13: testkeys
13/15 Test #13: testkeys .........................   Passed    0.11 sec
      Start 14: testbounds
14/15 Test #14: testbounds .......................   Passed    0.10 sec
      Start 15: testdisplayinfo
15/15 Test #15: testdisplayinfo ..................   Passed    0.10 sec

93% tests passed, 1 tests failed out of 15

Total Test time (real) =  53.93 sec

The following tests FAILED:
	  1 - testatomic (Timeout)
Errors while running CTest
```

**Comment by Wohlstand** [comment]
> With CMake, I get all X11 forced to be off

Because official build does. I made a mods on my side, so, CMake enables X11 on CMake.

**Comment by Wohlstand** [comment]
What about unit tests... lemme try out them on my side...

**Comment by barracuda156** [comment]
UPD. Ah, I think I have found where CMake build sabotages X11 :)

**Comment by barracuda156** [comment]
Yes, now it configures correctly:
```
-- SDL2 was configured with the following options:
-- 
-- Platform: Darwin-10.0.0d2
-- 64-bit:   FALSE
-- Compiler: /opt/local/bin/gcc-mp-12
-- Revision: SDL-release-2.28.1-0-g4761467b2
-- 
-- Subsystems:
--   Atomic:	ON
--   Audio:	ON
--   Video:	ON
--   Render:	ON
--   Events:	ON
--   Joystick:	OFF
--   Haptic:	OFF
--   Hidapi:	ON
--   Power:	ON
--   Threads:	ON
--   Timers:	ON
--   File:	ON
--   Loadso:	ON
--   CPUinfo:	ON
--   Filesystem:	ON
--   Sensor:	ON
--   Locale:	ON
--   Misc:	ON
-- 
-- Options:
--   SDL2_DISABLE_INSTALL        (Wanted: OFF): OFF
--   SDL2_DISABLE_SDL2MAIN       (Wanted: OFF): OFF
--   SDL2_DISABLE_UNINSTALL      (Wanted: OFF): OFF
--   SDL_3DNOW                   (Wanted: OFF): OFF
--   SDL_ALSA                    (Wanted: OFF): OFF
--   SDL_ALSA_SHARED             (Wanted: OFF): OFF
--   SDL_ALTIVEC                 (Wanted: ON): ON
--   SDL_ARMNEON                 (Wanted: OFF): OFF
--   SDL_ARMSIMD                 (Wanted: OFF): OFF
--   SDL_ARTS                    (Wanted: OFF): OFF
--   SDL_ARTS_SHARED             (Wanted: OFF): OFF
--   SDL_ASAN                    (Wanted: OFF): OFF
--   SDL_ASSEMBLY                (Wanted: ON): ON
--   SDL_ASSERTIONS              (Wanted: auto): auto
--   SDL_BACKGROUNDING_SIGNAL    (Wanted: OFF): OFF
--   SDL_CCACHE                  (Wanted: ON): OFF
--   SDL_CLOCK_GETTIME           (Wanted: OFF): OFF
--   SDL_COCOA                   (Wanted: OFF): OFF
--   SDL_DBUS                    (Wanted: OFF): OFF
--   SDL_DIRECTFB                (Wanted: OFF): OFF
--   SDL_DIRECTFB_SHARED         (Wanted: OFF): OFF
--   SDL_DIRECTX                 (Wanted: OFF): OFF
--   SDL_DISKAUDIO               (Wanted: ON): ON
--   SDL_DUMMYAUDIO              (Wanted: ON): ON
--   SDL_DUMMYVIDEO              (Wanted: ON): ON
--   SDL_ESD                     (Wanted: OFF): OFF
--   SDL_ESD_SHARED              (Wanted: OFF): OFF
--   SDL_FOREGROUNDING_SIGNAL    (Wanted: OFF): OFF
--   SDL_FUSIONSOUND             (Wanted: OFF): OFF
--   SDL_FUSIONSOUND_SHARED      (Wanted: OFF): OFF
--   SDL_GCC_ATOMICS             (Wanted: ON): ON
--   SDL_HIDAPI                  (Wanted: ON): ON
--   SDL_HIDAPI_JOYSTICK         (Wanted: ON): OFF
--   SDL_HIDAPI_LIBUSB           (Wanted: OFF): OFF
--   SDL_IBUS                    (Wanted: OFF): OFF
--   SDL_INSTALL_TESTS           (Wanted: OFF): OFF
--   SDL_JACK                    (Wanted: OFF): OFF
--   SDL_JACK_SHARED             (Wanted: OFF): OFF
--   SDL_KMSDRM                  (Wanted: OFF): OFF
--   SDL_KMSDRM_SHARED           (Wanted: OFF): OFF
--   SDL_LASX                    (Wanted: OFF): OFF
--   SDL_LIBC                    (Wanted: ON): ON
--   SDL_LIBSAMPLERATE           (Wanted: OFF): OFF
--   SDL_LIBSAMPLERATE_SHARED    (Wanted: OFF): OFF
--   SDL_LIBUDEV                 (Wanted: ON): OFF
--   SDL_LSX                     (Wanted: OFF): OFF
--   SDL_METAL                   (Wanted: ON): OFF
--   SDL_MMX                     (Wanted: OFF): OFF
--   SDL_NAS                     (Wanted: OFF): OFF
--   SDL_NAS_SHARED              (Wanted: OFF): OFF
--   SDL_OFFSCREEN               (Wanted: ON): ON
--   SDL_OPENGL                  (Wanted: ON): ON
--   SDL_OPENGLES                (Wanted: ON): ON
--   SDL_OSS                     (Wanted: OFF): OFF
--   SDL_PIPEWIRE                (Wanted: OFF): OFF
--   SDL_PIPEWIRE_SHARED         (Wanted: OFF): OFF
--   SDL_PTHREADS                (Wanted: ON): ON
--   SDL_PTHREADS_SEM            (Wanted: ON): ON
--   SDL_PULSEAUDIO              (Wanted: OFF): OFF
--   SDL_PULSEAUDIO_SHARED       (Wanted: OFF): OFF
--   SDL_RENDER_D3D              (Wanted: OFF): OFF
--   SDL_RENDER_METAL            (Wanted: ON): OFF
--   SDL_RPATH                   (Wanted: OFF): OFF
--   SDL_RPI                     (Wanted: OFF): OFF
--   SDL_SNDIO                   (Wanted: OFF): OFF
--   SDL_SNDIO_SHARED            (Wanted: OFF): OFF
--   SDL_SSE                     (Wanted: OFF): OFF
--   SDL_SSE2                    (Wanted: OFF): OFF
--   SDL_SSE3                    (Wanted: OFF): OFF
--   SDL_SSEMATH                 (Wanted: OFF): OFF
--   SDL_STATIC_PIC              (Wanted: OFF): OFF
--   SDL_SYSTEM_ICONV            (Wanted: ON): OFF
--   SDL_TESTS                   (Wanted: ON): ON
--   SDL_VENDOR_INFO             (Wanted: ): OFF
--   SDL_VIRTUAL_JOYSTICK        (Wanted: ON): OFF
--   SDL_VIVANTE                 (Wanted: OFF): OFF
--   SDL_VULKAN                  (Wanted: ON): OFF
--   SDL_WASAPI                  (Wanted: OFF): OFF
--   SDL_WAYLAND                 (Wanted: OFF): OFF
--   SDL_WAYLAND_LIBDECOR        (Wanted: OFF): OFF
--   SDL_WAYLAND_LIBDECOR_SHARED (Wanted: OFF): OFF
--   SDL_WAYLAND_QT_TOUCH        (Wanted: OFF): OFF
--   SDL_WAYLAND_SHARED          (Wanted: OFF): OFF
--   SDL_X11                     (Wanted: ON): ON
--   SDL_X11_SHARED              (Wanted: OFF): OFF
--   SDL_X11_XCURSOR             (Wanted: ON): ON
--   SDL_X11_XDBE                (Wanted: ON): ON
--   SDL_X11_XFIXES              (Wanted: ON): ON
--   SDL_X11_XINPUT              (Wanted: ON): ON
--   SDL_X11_XRANDR              (Wanted: ON): ON
--   SDL_X11_XSCRNSAVER          (Wanted: ON): ON
--   SDL_X11_XSHAPE              (Wanted: ON): ON
--   SDL_XINPUT                  (Wanted: OFF): OFF
```

**Comment by barracuda156** [comment]
@Wohlstand How do I enable them though? -DSDL_TESTS gets me only these 15 tests.

**Comment by Wohlstand** [comment]
If you trying to make your own things, keep a note that there are some small tweaks at OpenGL side needs, otherwise, the thing will stuck. I left a note at my branch for that.

**Comment by barracuda156** [comment]
@Wohlstand Well, I can’t just build from your (or my own, or anyone’s) personal branch, that won’t be accepted in Macports then. But I can certainly pick your fixes.

**Comment by Wohlstand** [comment]
About tests, I made some check, and Atomic fails because of assert inside:

[testatomic-output.txt](https://github.com/libsdl-org/SDL/files/12137511/testatomic-output.txt)

![Picture 112](https://github.com/libsdl-org/SDL/assets/6751442/50488c7c-7b71-4586-b469-519888765421)
![Picture 113](https://github.com/libsdl-org/SDL/assets/6751442/d5b78d44-3785-48c5-ba20-f017f27d3da7)

**Comment by Wohlstand** [comment]
Looks like, the "bad" should contain a garbage, but it contains an actual clear data.

**Comment by slouken** [comment]
That's a flawed test. It will always fail on a single-core system. @madebr, is that what we're running into in CI?

**Comment by Wohlstand** [comment]
When I rebuilt the same test using Autotools, it, looks, like works... :thinking:  (when running directly), but stucks at the FIFO test :thinking:

**Comment by Wohlstand** [comment]
> It will always fail on a single-core system.

Good to know. Sounds like, it's need to make a condition when it runs on a single-core CPU or multi-core to adjust checks.

**Comment by madebr** [comment]
> That's a flawed test. It will always fail on a single-core system. @madebr, is that what we're running into in CI?

We're running all tests with `SDL_TESTS_QUICK=1`, so the long test in `testatomic` is skipped.
There is an issue with `testfilesystem` on msys2, which should take only ~0.02s (instead of >10s and hitting the time limit).

**Comment by barracuda156** [comment]
@Wohlstand I got X11 via SDL2 to load, however rendering is broken. Notice, this uses Mesa `libGL`, and fails to load unless I set `LIBGL_ALLOW_SOFTWARE=true` in the environment. Apparently, that does not work correctly.

![ocp](https://github.com/libsdl-org/SDL/assets/92015510/2d510a77-9ea3-4f63-aa6b-049fd508b7de)

I will try falling back to an archaic macOS X11 and isolating Mesa headers and libs so they are not found by configure.

P. S. For the record, 10.6 does not seem to require patching context in `SDL_x11opengl.c`. It builds with and without it, and identical rendering problem is there, so apparently changing glxMakeCurrent is redundant.

**Comment by Wohlstand** [comment]
> glxMakeCurrent

It just leads a dead freeze on 10.4 at me, that why I made this tweak. Probably is need to make a programmical check to call this at newer macOS.

**Comment by barracuda156** [comment]
> > glxMakeCurrent
> 
> It just leads a dead freeze on 10.4 at me, that why I made this tweak. Probably is need to make a programmical check to call this at newer macOS.

@Wohlstand Maybe it is needed with old macOS `libGL`? For now, consider it indecisive. I will update on that for 10.6.

Have you tried by the way using Mesa libraries for OpenGL with your branch?

**Comment by Wohlstand** [comment]
> Maybe it is needed with old macOS libGL?

Very possibly, I even left a question about t his https://github.com/libsdl-org/SDL/issues/6779 that remains unresponded.

> Have you tried by the way using Mesa libraries for OpenGL with your branch?

Didn't yet, but I could try out something, could you give me some hints on how to do that? Which libraries I need to pull and install?

**Comment by Wohlstand** [comment]
@slouken, thanks for the assert removing, however, there is still a problem remained: the `FIFO test` just stucks forever:

```
$ ./testatomic 
INFO: 
spin lock---------------------------------------

INFO: AtomicLock                   lock=1
INFO: AtomicUnlock                 lock=0
INFO: 
atomic -----------------------------------------

INFO: AtomicSet(10)        tfret=TRUE val=10
INFO: AtomicAdd(10)        tfret=TRUE val=20
INFO: AtomicIncRef()       tfret=TRUE val=1
INFO: AtomicIncRef()       tfret=TRUE val=2
INFO: AtomicDecRef()       tfret=TRUE val=1
INFO: AtomicDecRef()       tfret=TRUE val=0
INFO: AtomicCAS()          tfret=TRUE val=10
INFO: AtomicCAS()          tfret=TRUE val=20
INFO: 
epic test---------------------------------------

INFO: Size asserted to be >= 32-bit
INFO: Check static initializer
INFO: Test negative values
INFO: Verify maximum value
INFO: Test compare and exchange
INFO: Test Add
INFO: Test Add (Negative values)
INFO: Reset before count down test
INFO: Counting down from 2147483647, Expect 47 remaining
INFO: Thread subtracting 100 10737418 times
INFO: Thread subtracting 100 10737418 times
INFO: Finished in 2.172000 sec
INFO: Atomic 47 Non-Atomic 47
INFO: 
FIFO test---------------------------------------

INFO: Mode: LockFree
INFO: Starting 4 readers
INFO: Starting 4 writers

```

**Comment by barracuda156** [comment]
@Wohlstand @slouken Re atomics, if something assumes 1-byte size for bool or spinlock, that would break things for Darwin ppc. Both are 4 bytes. (A quick look seemed to suggest SDL does not set those to 1 byte, but I easily could miss something.)

We could also try disabling GCC atomics and falling back to Apple’s own from in `libkern`.

**Comment by barracuda156** [comment]
> > Have you tried by the way using Mesa libraries for OpenGL with your branch?
> 
> Didn't yet, but I could try out something, could you give me some hints on how to do that? Which libraries I need to pull and install? Also, keep in a mind, my machine has ATI Radeon 9200.

@Wohlstand Install the Mesa port: https://ports.macports.org/port/mesa/details (according to statistics it builds for 10.4). Or the same with any other package manager (tigerbrew? fink?).
Then set DEFAULT_OPENGL to `${macports_prefix}/lib/libGL.1.dylib` in `SDL_x11opengl.c`.
Perhaps that is it? I also did not disable OpenGLES – not sure yet if that is okay or not, need to try building without it.

**Comment by barracuda156** [comment]
UPD. It appears that it is indeed either Mesa is broken or something went wrong with it. Building SDL2 and setting DEFAULT_OPENGL to the one in `/usr/X11/lib` seems to fix the problem, at least for the port I tested:
![ocp_sdl2](https://github.com/libsdl-org/SDL/assets/92015510/c26fe0b4-885d-4478-92f3-8ac55cf23c46)
(Does not mean as such mean that an archaic `libGL` is preferable, but FWIW.)

**Comment by icculus** [comment]
> We could also try disabling GCC atomics and falling back to Apple’s own from in libkern

I believe we had code to do this in an earlier SDL2 release that was likely removed as redundant, once we had reliable gcc built-ins.

**Comment by icculus** [comment]
Actually, they're still there:

https://github.com/libsdl-org/SDL/blob/37e567994dfa5cf6215b1767295e3399c83a3136/src/atomic/SDL_atomic.c#L134

**Comment by barracuda156** [comment]
@icculus Generally speaking, GCC atomics should work, but who knows, at least it is worth trying a fallback. (If it happens to be a target-specific bug in GCC, it has to be reported to upstream.)

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.

**Comment by Wohlstand** [comment]
Speaking about X11 on old Mac OS X and in general, I could backport my patches from my TigerMac branch to bring these fixes to mainstream. Actually, the way I did is hacky, and is not looks like a production. Actually, I want to finish my old Cocoa support implementation (using old SDL2's code as reference, compared to modern Cocoa code). On my end I started some work on making the old Cocoa support in a form of separated from modern Cocoa module (to let modern Cocoa go with progress and old Cocoa preserve compatibility independently), but I didn't completed yet the work, as just hard to work on weak Mac Mini G4 computer and "inconvenient" Xcode 2 for Mac OS X Tiger (blame Qt Creator that has powerful refactoring functionliaty that can perform smart search by usages, etc). I started another work to attempt implement the cross compiler that might allow compilation from Linux to PPC Mac, but it just failed to build for various reasons, and somebody suggested me to try that on Mac (and of course, use custom compiled legacy linker that has PPC support, and specific version as the best one in stability, as newer versions became broken in this case). I do have Mac Mini M2 that I already use for various debug stuff, but for general use, Linux Mint feels more convenient for me.

**Comment by barracuda156** [comment]
@Wohlstand Re cross-compiler, we can ask @Jazzzny to comment, since, I believe, he has it working on macOS arm64 (compiling to ppc and ppc64).
Re toolchain, it is likely possible to get much newer `as` and `ld64` via `darwin-xtools`. On 10.5 and 10.6 ppc that is trivial and implemented already, but I did not try on 10.4. Also notice, gcc14 now builds and works on Tiger, reproducibly so.

**Comment by barracuda156** [comment]
@Jazzzny It is possible for a compiler executable to use paths pointing to an external machine over ssh?

**Comment by Jazzzny** [comment]
Not sure about SSH, but I've had good luck by using the "Sharing" features and connecting to the hosted SMB/AFP server and accessing the files that way.

**Comment by barracuda156** [comment]
@Wohlstand Do you have a tree for your current version of SDL2 with Cocoa? I could try building that.

**Comment by Wohlstand** [comment]
Here is everything I made to allow old Mac being supported, but, Cocoa is used here partially, not yet video (for video I use X11 as a temporary solution): https://github.com/Wohlstand/SDL/tree/mac-tiger

**Comment by barracuda156** [comment]
I guess I have SDL3 working on 10.6 PowerPC.
It was kinda expected, but nothing to test it with. Now that `lite-xl` switched from SDL2 to SDL3, here we go:

![Image](https://github.com/user-attachments/assets/abf3fbcf-6cee-4bd4-9a54-2d02e86d737b)

**Comment by Wohlstand** [comment]
Cool, and the question: @barracuda156, what the hardware is? I have Mac Mini G5 and it's very weak

**Comment by barracuda156** [comment]
> Cool, and the question: @barracuda156, what the hardware is? I have Mac Mini G5 and it's very weak

All development work and compilation is done on the G5 Quad. It is still good (in a sense I do not feel it is outdated in terms of raw performance) – the only weak point for normal usage is GPUs. It still can play 4K vids, but not all and not at 60FPS.

If you want an enjoyable machine in terms of performance, you may also get PowerMac G5 2.3DC (late 2005 model). While it takes longer to build gcc than Quad, it is still a very capable machine which can be used normally for most tasks. Max the RAM, install SSD, and they run nicely.

I have a few PowerBooks, but I can say for sure that pretty much nothing would have been done, if not for G5 PowerMacs. I can’t stand compiling cmake for hours and gcc for days LOL.
Anything G4 will feel slow. Sadly, since PowerBooks have beautiful hardware otherwise.
