### ISSUE TITLE
GitHub Action for Emscripten needs update

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8022]
This GitHub Actions warning on the Emscripten builds:

```
The following actions uses node12 which is deprecated and will be forced to run on node16: mymindstorm/setup-emsdk@v10. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

Probably just needs to be bumped to v11, but I haven't looked at setup-emsdk to see if that's appropriate.

Putting this in 3.2.0 milestone, but this should go into SDL2, too.

**Comment by madebr** [comment]
Fixed in 3823219b2813bea49ca996b0774c830c6bbd2606 (SDL3), 322dbdde4e90cd3322ade8efef059fc2216db47d (SDL2) and e6f044ddd (2.28.x)
