### ISSUE TITLE
RISC OS: need C99 compiler

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8023]
Getting errors for RISC OS builds in #7704 ...

```
../src/audio/SDL_audio.c:172:5: error: 'for' loop initial declarations are only allowed in C99 mode
../src/audio/SDL_audio.c:172:5: note: use option -std=c99 or -std=gnu99 to compile your code
```

Since we're doing the C99 stuff like `for (int i = 0; ...)`, we need to flip on this compiler option there. None of the other GCC/Clang builds have needed this, so it's RISC OS-specific thing.

(Paging @madebr and @smcv, in case either of you are the right person to poke at this. Thanks!)

**Comment by madebr** [comment]
This probably depends on the gcc/clang version.

What about modifying [these lines](https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L380-L390) into the following?
Let's make use of CMake 3.16+ features while we can.
```cmake
if(SDL_SHARED)
  add_library(SDL3-shared SHARED)
  add_library(SDL3::SDL3-shared ALIAS SDL3-shared)
  SDL_AddCommonCompilerFlags(SDL3-shared)
  target_compile_features(SDL3-shared PRIVATE c_std_99)
endif()

if(SDL_STATIC)
  add_library(SDL3-static STATIC)
  add_library(SDL3::SDL3-static ALIAS SDL3-static)
  SDL_AddCommonCompilerFlags(SDL3-static)
  target_compile_features(SDL3-static PRIVATE c_std_99)
endif()
```

**Comment by sezero** [comment]
> This probably depends on the gcc/clang version.
> 
> What about modifying [these lines](https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L380-L390) into the following? Let's make use of CMake 3.16+ features while we can.
> 
> ```cmake
> if(SDL_SHARED)
>   add_library(SDL3-shared SHARED)
>   add_library(SDL3::SDL3-shared ALIAS SDL3-shared)
>   SDL_AddCommonCompilerFlags(SDL3-shared)
>   target_compile_features(SDL3-shared PRIVATE c_std_99)
> endif()
> 
> if(SDL_STATIC)
>   add_library(SDL3-static STATIC)
>   add_library(SDL3::SDL3-static ALIAS SDL3-static)
>   SDL_AddCommonCompilerFlags(SDL3-static)
>   target_compile_features(SDL3-static PRIVATE c_std_99)
> endif()
> ```

That would be good: Older gcc versions don't default to c99 (gnu99) or higher.

**Comment by icculus** [comment]
Yeah, do it.
