### ISSUE TITLE
Support for visionOS / Vision Pro

### ISSUE THREAD

**Issue by Ravbug** [libsdl-org/SDL#8025]
It would be cool if SDL supported the new Apple headset (at least in Windowed mode) when it releases to the public. The simulator is already publicly available via the Xcode 15 betas. 

I've done some preliminary work in an attempt to get SDL building for visionOS. It seems like the iOS UIKit backend can be adapted for visionOS with some modifications:
- `UIScreen` does not exist on visionOS
- CMake file needs to be aware of `CMAKE_SYSTEM_NAME=visionOS` (support was recently merged into CMake: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8581)
- `TARGET_OS_XR` to conditionally compile for visionOS

**Comment by slouken** [comment]
Feel free to create a PR. If the changes in uikit are extensive, go ahead and consider separating entire files or branching the entire directory for visionOS

**Comment by icculus** [comment]
Do we _not_ have to use SwiftUI for this? Or are we talking about just a simple migration path for 2D iOS apps? (Either or both of these would be great, fwiw!)

**Comment by Ravbug** [comment]
I have been focusing on the path for 2D apps. As far as I am aware, SwiftUI is not required.

**Comment by Ravbug** [comment]
Could someone please review my PR? Thanks
