### ISSUE TITLE
SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 not working

### ISSUE THREAD

**Issue by taep96** [libsdl-org/SDL#8028]
I tried preventing osu!Lazer from minimizing when I switch to another workspace (GNOME on Arch Linux).

I tried:
1. Running the game with `SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 game_executable`
2. Removing [this line](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/SDL2Window.cs#L233).
3. Setting the value of [this line](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/SDL2Window.cs#L233) to 0 (worked)

I opened an [issue](https://github.com/ppy/osu/discussions/24332) on the game's repo and was told this is an issue with SDL not reading the env vars

**Comment by slouken** [comment]
The environment variable doesn't have the word "HINT" in it: `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0`
