### ISSUE TITLE
error compiling on macos 12.6.8 - with MacOSX13.1.sdk

### ISSUE THREAD

**Issue by TrevorCash** [libsdl-org/SDL#8033]
Hello All, I am using cmake to compile release 2.28.1 , I am getting an error when it references the headers in the MacOSX 13.1 sdk:

```
[ 34%] Building C object _deps/sdl2-build/CMakeFiles/SDL2.dir/src/file/cocoa/SDL_rwopsbundlesupport.m.o
In file included from /Users/trevorcash/Repos/motion/build/_deps/sdl2-src/src/file/cocoa/SDL_rwopsbundlesupport.m:24:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:371:81: error: 
      function does not return string type
- (nullable instancetype)initWithUTF8String:(const char *)nullTerminatedCString NS_FORMAT_ARGUMENT(1);
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^                  ~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:103:48: note: 
      expanded from macro 'NS_FORMAT_ARGUMENT'
        #define NS_FORMAT_ARGUMENT(A) __attribute__ ((format_arg(A)))
                                                      ^          ~

...
..
```

Thanks in advance for any ideas.

**Comment by slouken** [comment]
Interesting. This looks like a bug in the SDK headers to me. I don't think there's anything we can fix here, other than not including that header.

**Comment by icculus** [comment]
There's a bug in NSString.h?! But wouldn't that break every Cocoa app ever written?

I'm going to try this on a Mac soon. Even if it _is_ an SDK bug, I'd feel better about verifying it.

**Comment by icculus** [comment]
This is definitely not happening here, fwiw. Tried it with the 13.1 SDK.

If you could rerun this build command as `make VERBOSE=1` instead of `make`, and post more lines of output, it's possible that it would give us some further clues as to what went wrong.

If nothing is obviously, you could try adding this to the very top of src/file/cocoa/SDL_rwopsbundlesupport.m, as a workaround, but even if this works, it's masking what might be a more serious problem:

```c
#define NS_FORMAT_ARGUMENT(A)
```

**Comment by TrevorCash** [comment]
> This is definitely not happening here, fwiw. Tried it with the 13.1 SDK.
> 
> If you could rerun this build command as `make VERBOSE=1` instead of `make`, and post more lines of output, it's possible that it would give us some further clues as to what went wrong.
> 
> If nothing is obviously, you could try adding this to the very top of src/file/cocoa/SDL_rwopsbundlesupport.m, as a workaround, but even if this works, it's masking what might be a more serious problem:
> 
> ```c
> #define NS_FORMAT_ARGUMENT(A)
> ```

This must have been something with my particular setup.
