### ISSUE TITLE
Support ShapedWindow with alpha value from surface shape

### ISSUE THREAD

**Issue by LocOlli** [libsdl-org/SDL#8044]
I'm currently working on a project that uses SDL2 (2.26.2) on DirectFB. I decided to use ShapeWindow to show popup notifications but I met a problem with the window corner alias.  I modified some source to fix this problem, by changing the pixel's alpha value, it works like a charm. The question is, any problem if I modify it directly to ShapeModeColorKey ?
My source as below:

`int
DirectFB_SetWindowShape(SDL_WindowShaper *shaper,SDL_Surface *shape,SDL_WindowShapeMode *shape_mode) {

    if(shaper == NULL || shape == NULL || shaper->driverdata == NULL)
        return -1;

    if(shape->format->Amask == 0 && SDL_SHAPEMODEALPHA(shape_mode->mode))
        return -2;

    if(shape->w != shaper->window->w || shape->h != shaper->window->h)
        return -3;

    {
        SDL_VideoDisplay *display = SDL_GetDisplayForWindow(shaper->window);
        SDL_DFB_DEVICEDATA(display->device);
        Uint32 *pixels;
        Sint32 pitch;
        Uint32 h,w;
        Uint32 *surface_pixels = (uint32_t*)shape->pixels;
        Uint32 surface_alpha = 0xff000000;
        uint8_t  *src, *bitmap;
        DFBSurfaceDescription dsc;

        SDL_ShapeData *data = shaper->driverdata;

        SDL_DFB_RELEASE(data->surface);

        dsc.flags = DSDESC_WIDTH | DSDESC_HEIGHT | DSDESC_PIXELFORMAT | DSDESC_CAPS;
        dsc.width = shape->w;
        dsc.height = shape->h;
        dsc.caps = DSCAPS_PREMULTIPLIED;
        dsc.pixelformat = DSPF_ARGB;

        SDL_DFB_CHECKERR(devdata->dfb->CreateSurface(devdata->dfb, &dsc, &data->surface));

        SDL_DFB_CALLOC(bitmap, shape->w *shape->h, 1);
        /* Assume that shaper->alphacutoff already has a value, because SDL_SetWindowShape() should have given it one. */
        SDL_CalculateShapeBitmap(shaper->mode, shape, bitmap, 1);

        src = bitmap;

        SDL_DFB_CHECK(data->surface->Lock(data->surface, DSLF_WRITE | DSLF_READ, (void **) &pixels, &pitch));

        h = shaper->window->h;
        while (h--) {
            for (w = 0; w < shaper->window->w; w++) {
                if (*src)
                {
                    surface_alpha = (surface_pixels[h * (shaper->window->w) + w] & 0xff000000);
                    pixels[w] = surface_alpha + 0xffffff;
                }
                else
                    pixels[w] = 0;
                src++;
            }
            pixels += (pitch >> 2);
        }
        SDL_DFB_CHECK(data->surface->Unlock(data->surface));
        SDL_DFB_FREE(bitmap);

        /* FIXME: Need to call this here - Big ?? */
        DirectFB_WM_RedrawLayout(SDL_GetDisplayForWindow(shaper->window)->device, shaper->window);
    }

    return 0;
error:
    return -1;
}`

**Comment by slouken** [comment]
No, that seems fine to me.
