### ISSUE TITLE
Incorrect gamepad button mappings

### ISSUE THREAD

**Issue by Reu12310** [libsdl-org/SDL#8045]
Since version 2.28 some buttons are incorrectly mapped on most games (using proton on Linux), as follows (Xbox Symbols):

A, B, Triggers, Sticks and d-pad are correctly mapped.

Y -> X
X -> None
LB -> Y
RB -> None
Select -> LB
Start -> RB

Downgrading to version 2.26 solves the problem and works normally.

Games tested:
Dark Souls Remastered
Dark Souls II Scholar of the first Sin
Batman: Arkham Knight
Tunic
Psychonauts
God of War (2018)
Spider-Man: Miles Morales

Batman: Arkham City works correctly for some reason despite Knight not working. This is the only game i have found to be unaffected.

OS: Arch Linux
Gamepad: 8BitDo Pro 2 (x-input mode)
Wine: Lutris-GE-Proton

**Comment by slouken** [comment]
Can you check to see if this is an issue with the latest SDL code here?
https://github.com/libsdl-org/SDL/tree/release-2.28.x

I believe this was fixed in https://github.com/libsdl-org/SDL/commit/0dbeec449fe1f89c0b14bc7a15deecf1557631d0

**Comment by Reu12310** [comment]
Installing the sdl2-git package from AUR fixes the problem. Thank you.
