### ISSUE TITLE
SDL3 Linux: SDL_CreateWindowWithPosition() and SDL_SetWindowPosition() position the window differently.

### ISSUE THREAD

**Issue by directmusic** [libsdl-org/SDL#8047]
On Linux (Ubuntu 22.04.2 + Gnome 42.5) under both Wayland and X11 creating a window with `SDL_CreateWindowWithPosition()` produces different results than `SDL_SetWindowPosition()`.

`SDL_CreateWindowWithPosition()` positions the window to the top left corner of the titlebar.
`SDL_SetWindowPosition()`positions the window to the top left corner of the window content.

When creating the window with SDL_WINDOW_BORDERLESS the position is accurate.

As a result `SDL_GetWindowPosition()` returns x:100 y:174 when creating a bordered window with x:100 y:100

I am on the latest (at the time of posting) commit: https://github.com/libsdl-org/SDL/commit/d086d9874d21780e18e2e44b2545b2e74a5a49fa

Here is a small C++ example that moves the window after 100 frames:

```c
#include <SDL.h>
#include <iostream>

int main(int argc, char **argv) {
  SDL_Window *window = SDL_CreateWindowWithPosition(
      "Window", 100, 100, 300, 300, 0); // Try with SDL_WINDOW_BORDERLESS
  SDL_Renderer *renderer =
      SDL_CreateRenderer(window, nullptr, SDL_RENDERER_PRESENTVSYNC);
  SDL_Event e;

  int frame_counter = 0;

  bool quit = false;
  while (quit == false) {
    while (SDL_PollEvent(&e)) {
      if (e.type == SDL_EVENT_QUIT) {
        quit = true;
      }
    }

    if (frame_counter == 100) {
      // This will set the position shortly after beginning rendering.
      SDL_SetWindowPosition(window, 100, 100);
    }

    int window_x, window_y;
    SDL_GetWindowPosition(window, &window_x, &window_y);
    std::cout << "Frame:" << frame_counter << '\n';
    std::cout << "x: " << window_x << ", y:" << window_y << '\n';

    frame_counter++;

    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    SDL_RenderClear(renderer);
    SDL_RenderPresent(renderer);
  }
  SDL_DestroyRenderer(renderer);
  SDL_DestroyWindow(window);
  return 0;
}
```

**Comment by slouken** [comment]
@icculus, can you take a quick look? I'm not seeing any significant difference between how we initially place the window and when we move it into position.

**Comment by icculus** [comment]
One calls X11_UpdateWindowPosition, which tries to reposition vs the border dimensions, and also calls X11_WaitAndSendWindowEvents, and the other just calls XCreateWindow.

If I force it to use window->x and window->y instead of calculating it vs the border dimensions, _and_ I comment out X11_WaitAndSendWindowEvents, the remaining call to XMoveWindow under X11_SetWindowPosition does not make the window jump any more.

Which narrows down the problem, but that's still a bit of surface area to examine.

**Comment by slouken** [comment]
FWIW, the intent is for the x/y position of the window to be the position of the client area.

**Comment by icculus** [comment]
Updated program to build for latest SDL3 and without C++:

```c
#include <SDL3/SDL.h>

int main(int argc, char **argv)
{
    SDL_PropertiesID props = SDL_CreateProperties();

    SDL_SetStringProperty(props, SDL_PROP_WINDOW_CREATE_TITLE_STRING, "Window");
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, 300);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, 300);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_X_NUMBER, 100);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_Y_NUMBER, 100);
    //SDL_SetBooleanProperty(props, SDL_PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN, true);

    SDL_Window *window = SDL_CreateWindowWithProperties(props);
    SDL_Renderer *renderer = SDL_CreateRenderer(window, NULL);

    SDL_DestroyProperties(props);

    int frame_counter = 0;

    bool quit = false;
    while (quit == false) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
        if (e.type == SDL_EVENT_QUIT) {
            quit = true;
        }
    }

    if (frame_counter == 100) {
        // This will set the position shortly after beginning rendering.
        SDL_SetWindowPosition(window, 100, 100);
    }

    static int prev_window_x = -1, prev_window_y = -1;
    int window_x, window_y;
    SDL_GetWindowPosition(window, &window_x, &window_y);

    if ((window_x != prev_window_x) || (window_y != prev_window_y)) {
        SDL_Log("frame: %d   x: %d  y: %d", frame_counter, window_x, window_y);
        prev_window_x = window_x;
        prev_window_y = window_y;
    }

    frame_counter++;

    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    SDL_RenderClear(renderer);
    SDL_RenderPresent(renderer);
  }

  SDL_DestroyRenderer(renderer);
  SDL_DestroyWindow(window);
  return 0;
}

```

As of the latest in revision control, this creates a client window at 100,100 right off the start. The client position is always at 100,100, bordered or not, and the titlebar rises to somewhere above that position. Tested on X11.

![image](https://github.com/user-attachments/assets/cfed5a72-5b86-4f1e-9004-031ffa0c8775)

![image](https://github.com/user-attachments/assets/c03c646a-4fd6-4c63-b6b4-68217ba17419)

...so I think we fixed this at some point?
