### ISSUE TITLE
Document how to build tests?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8049]
I've seen a bunch of people asking how to build the test programs in main. Is there somewhere we can be documenting that better?

**Comment by madebr** [comment]
How about the following to `docs/README-cmake.md`?

## SDL-specific CMake options

SDL can be customized through (platform-specific) CMake options.
The following table shows generic options that are available for most platforms.
At the end of SDL CMake configuration, a table shows all CMake options along with its detected value.

| CMake option                  | Accepted values | Description                                                                                         |
|-------------------------------|-----------------|-----------------------------------------------------------------------------------------------------|
| `-DSDL_SHARED=`               | `ON`/`OFF`      | Build SDL shared library (not all platforms support this) (`libSDL3.so`/`libSDL3.dylib`/`SDL3.dll`) |
| `-DSDL_STATIC=`               | `ON`/`OFF`      | Build SDL static library (`libSDL3.a`/`SDL3-static.lib`)                                            |
| `-DSDL_TEST=`                 | `ON`/`OFF`      | Build SDL test library (`libSDL3_test.a`/`SDL3_test.lib`)                                           |
| `-DSDL_TESTS=`                | `ON`/`OFF`      | Build SDL tests (**requires `-DSDL_TEST=ON`**)                                                      |
| `-DSDL_DISABLE_INSTALL=`      | `ON`/`OFF`      | Don't create a SDL install target                                                                   |
| `-DSDL_DISABLE_INSTALL_DOCS=` | `ON`/`OFF`      | Don't build the SDL documentation                                                                   |

**Comment by slouken** [comment]
That seems helpful, but I think we want this at the top, maybe after building SDL?
e.g.

## Building SDL
...

## Building SDL tests

You can build the SDL test programs by adding `-DSDL_TESTS=ON` to the first cmake command above:
```sh
cmake -S ~/sdl -B ~/build -DSDL_TESTS=ON
```
and then building normally. In this example, the test programs will be built and can be run from ~/build/tests/

**Comment by madebr** [comment]
I think this got addressed in https://github.com/libsdl-org/SDL/commit/41a96c813336a933c21bdf7352d7f26115bfe3f8 and https://github.com/libsdl-org/SDL/commit/e24b3e2fa40412aca6690472bcdb1a90a5b9475c

**Comment by slouken** [comment]
Thanks!
