### ISSUE TITLE
Rename SDL_GetPath to SDL_GetUserFolder, and possibly add SDL_GetAppFolder

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#8051]
It has been a while since I implemented SDL_GetPath as #7665, and [this discussion](https://github.com/libsdl-org/SDL/pull/7665#discussion_r1185091222) has made me think that the name of the function is too vague, and does not reflect well its purpose.

On my local copy, I renamed the function **SDL_GetUserFolder**, which reflects better the intention I had for the function when I first implemented it: to fetch the standard locations for certain user-controlled folders.

In the linked discussion, it has been proposed to move SDL_GetBasePath and SDL_GetPrefPath under that function. I initially advised against, both because it breaks the function's semantic purpose (it was originally meant to return user-controlled folders, rather than app-controlled folders) and because those functions need special arguments.

If there is still interest in grouping those functions, I can make a similar function for application-specific folders, probably called **SDL_GetAppFolder**. It would accept as arguments any information necessary to generate an application-specific path for the requested purpose, and would otherwise work the same way as SDL_GetUserFolder.

Do any of those two suggestions (renaming SDL_GetPath to SDL_GetUserFolder, adding SDL_GetAppFolder) sound interesting?

**Comment by slouken** [comment]
I think renaming SDL_GetPath() would be fine. I agree it's confusing that appdata isn't in that list, but maybe documentation pointing at SDL_GetPrefPath() would take care of that?

**Comment by Semphriss** [comment]
I can do that, I'll open a PR in a few moments.
