### ISSUE TITLE
Will support SDL3 YUV420P10 and Matrix BT.2020

### ISSUE THREAD

**Issue by gispos** [libsdl-org/SDL#8053]
UHD and HDR are almost standard for video playback, will it be possible to use this with SDL3 (YUV420P10 and BT.2020) ?
Thanks in advance.

**Comment by slouken** [comment]
Yep, I'm planning on working on this.

**Comment by gispos** [comment]
Nice to read that.
Thank you!

**Comment by slouken** [comment]
Added! This currently works on the Direct3D11 renderer.

**Comment by waterblower** [comment]
Is it supported on Mac? @slouken

**Comment by slouken** [comment]
> Is it supported on Mac? [@slouken](https://github.com/slouken)

Yes.
