### ISSUE TITLE
"No available displays" when no monitor is connected

### ISSUE THREAD

**Issue by jenda122** [libsdl-org/SDL#8054]
Hi,
I'm using SDL on a computer without a monitor attached (via VNC). However, SDL init fails with "No available displays" (it works when the local monitor is turned on). Setting the SDL_VIDEO_X11_XRANDR=0 environment variable fixes (works around) the problem.

I think maybe the X11_InitModes_XRandR function should not return an error [here](https://github.com/libsdl-org/SDL/blob/f2ae00c1ad5194586bacbd7b374422bd1d47c81a/src/video/x11/SDL_x11modes.c#L726) and the caller should retry with X11_InitModes_StdXlib, which is probably what happens with SDL_VIDEO_X11_XRANDR? I have not tested this approach yet, though.

The platform is x86-64 with Debian 12 (the issue appeared after upgrading from Debian 11).

**Comment by slouken** [comment]
Fixed, thanks!
