### ISSUE TITLE
Export functions from static lib

### ISSUE THREAD

**Issue by 1vanK** [libsdl-org/SDL#8057]
It is necessary to add the ability to export functions not only from dll, but also from the static version of the library.

Situation: SDL is statically linked to a game engine, but the game engine itself is compiled as dll. Applications that use the game engine must be able to call sdl functions.

Good way for this:
https://github.com/dviglo2d/dviglo2d/blob/main/libs/third_party/glad/include/glad/gl.h#L120-L144

This allows to manipulate defines in sdl/engine/app configs

**Comment by madebr** [comment]
This would just be a matter of adding
```cmake
option(SDL_STATIC_EXPORT_SYMBOLS "Export SDL symbols from static library" OFF)
if(SDL_STATIC_EXPORT_SYMBOLS)
  target_compile_definitions(SDL3-static PRIVATE DLL_EXPORT)
endif()
```
(it's [used here](https://github.com/libsdl-org/SDL/blob/36b5f3e35c00f1b392618f657d1cc32d8327527f/include/SDL3/SDL_begin_code.h#L55-L69) in the headers)

I think you need to link with `-Wl,--whole-archive libSDL3.a -Wl,--no-whole-archive` (`/wholearchive:SDL3-static.lib`) to make sure all SDL symbols are included, but I'm not 100% sure.

I doubt doing this is a good idea as users lose the advantages of using shared libraries.
The only disadvantage of a shared SDL3 library is the extra file (of which your game engine with exe + dll ships multiple of anyways).

**Comment by 1vanK** [comment]
dllimport must be provided in SDL header files

**Comment by madebr** [comment]
What build error are you trying to fix?
Not using dllimport allows us to link to a shared/static SDL library without recompile.

**Comment by sezero** [comment]
The described use case is a bad abuse and must not be allowed by us. If the user of that game engine dll has such a necessity, they should customize their builds but be on their own. (That's how I see it, I'm not the owner of this library.)

**Comment by 1vanK** [comment]
What do you mean by "bad abuse"?

**Comment by 1vanK** [comment]
> Not using dllimport allows us to link to a shared/static SDL library without recompile.

What are we even talking about?

**Comment by 1vanK** [comment]
> What build error are you trying to fix?

If app uses SDL from dll and engine used from SDL from dll there will be two different instances of SDL.

**Comment by madebr** [comment]
> If app uses SDL from dll and engine (compiled as dll) uses SDL from dll there will be two different instances of SDL.

When `app.exe` and `engine.dll` both use `SDL3.dll`, there will be only one SDL3 instance in memory, that's the beauty of dll's.

**Comment by madebr** [comment]
> What do you mean by "bad abuse"?

`SDL_*` symbols are either hidden inside an executable by linking to a static library, or they are provided by `SDLx.DLL`.
All other configurations are considered "unwanted".

**Comment by sezero** [comment]
Your scenario should only be achieved by exporting forwarder procedures from your dll and calling those forwarders from your exe accordingly instead of SDL functions themselves.

**Comment by 1vanK** [comment]
> When `app.exe` and `engine.dll` both use `SDL3.dll`, there will be only one SDL3 instance in memory, that's the beauty of dll's.

Try init SDL in engine.dll and the play audio in app.exe

**Comment by madebr** [comment]
> > When `app.exe` and `engine.dll` both use `SDL3.dll`, there will be only one SDL3 instance in memory, that's the beauty of dll's.
> 
> Try init SDL in engine.dll and then play audio in app.exe

As long as `SDL_Init` (through `Engine::Init`) is called before `SDL_QueueAudio` (through `Engine::Audio::Play`), that's fine.
Your engine design should accommodate this.

**Comment by 1vanK** [comment]
I have nothing more to add about this

**Comment by 1vanK** [comment]
In fact, this problem doesn't bother me personally anymore, because I no longer compile my engine as a Dll.
The entire engine, along with SDL and other libraries, is statically linked to the application. My engine is tiny enough for this.
The reason for dll support deletion was that with the static version of the engine a sound was played (wia SDL_Mixer), but in the dynamic version it was not played.

Removing dll support: https://github.com/dviglo2d/dviglo2d/commit/bf44cd25f6bd7db78a308c76ed50a8fc20956f08

Next commit - adding SDL_Mixer: https://github.com/dviglo2d/dviglo2d/commit/dbcc969c0bfcf2e193073e13940e803f328f53b8

In any case, if you don’t care and I don’t care, then let it remain as it is.
