### ISSUE TITLE
Proposal: Generate Xcode build files instead of including them in git

### ISSUE THREAD

**Issue by creichen** [libsdl-org/SDL#8064]
As a non-OS X contributor, I find CI breakages caused by the (recent?) inclusion of Xcode build files in the SDL git to be concerning, since such build failures aren't actionable for individual contributors.  By comparison, MSVC build files are somewhat maintainable for humans, but my current understanding of Xcode files is that they represent project modules (files etc.) as hashes and can switch the order of entries when saving (as if naively serialising a hash table).  If my understanding is correct, this  makes them a poor match for working with git.
Here's a [post by Xcode users discussing the challenges and a custom solution that they built](https://medium.com/lightricks-tech-blog/kintsugi-automatically-solving-git-conflicts-in-xcode-project-files-6b9f955cef5c), to give context from people who know more about this than I.

Thus, developers with OS X access (like the excellent @sezero) have to help us out.

My understanding is that cmake [can generate Xcode build files, at least on OS X](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#why-do-generated-xcode-projects-have-a-cmake-postbuild-rules-phase).  This step could perhaps even be run on a suitable git hook, on OS X.  I would thus like to propose removing the Xcode files from SDL git and instead generating them for OS X users (as transparently as possible).

Since I have no Xcode experience I have no idea if this is actually practical, but *if* it is feasible without impacting contributors who use Xcode, it would be a benefit for contributors who don't use Xcode.
[**edit**: "OS X contributors" -> "contributors who use Xcode]

**Comment by slime73** [comment]
My 2c as someone who uses SDL on macOS and iOS:

* The Xcode project has been in SDL's repository for a very, very long time.
* CMake doesn't always have good support for modern platform toolchain features (or new platforms) and in particular is known for poor iOS support.
* CMake isn't able to generate an Xcode project that can be used on someone else's machine, as far as I'm aware.

Personally I'd really prefer the non-generated Xcode project to stick around.

**Comment by madebr** [comment]
Perhaps, portable xcode project files can be auto-generated (from cmake) using tools such as [XcodeGen](https://github.com/yonaskolb/XcodeGen)?

Then, the cmake scripts become the only source of truth.
The xcode projects can be checked for "correctness" on ci, and also auto-regenerated if necessary.

(Then again, I don't use Apple. So I might be speaking gibberish)

**Comment by creichen** [comment]
@slime73, my reading is that even if `cmake -G Xcode` were to work right now, you wouldn't consider it sufficiently reliable for production use, i.e., you'd expect it to create nontrivial extra effort for iOS maintainers and Xcode users in general, down the road?

Given that Xcode users have to always use these files (to my understanding) while non-Xcode users only need to deal with Xcode CI breakage when dependencies change, that would be a strong argument against my proposal.

**Comment by slouken** [comment]
Yep, the Xcode projects have some downsides, but they are valuable for Apple development and usually (when I'm not overhauling them) stable.
