### ISSUE TITLE
No support gamepad G-Shark GS-GP702

### ISSUE THREAD

**Issue by 64ghost** [libsdl-org/SDL#8068]
In **SDL2-2.26.4** support 03000000790000000600000000000000 G-Shark GS-GP702
In **SDL2-2.26.5 and newer** support is delete

**Comment by 64ghost** [comment]
My controller data as in file SDL_gamepad_db.h

"03000000790000000600000000000000,G-Shark GS-GP702,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b0,"

**Comment by 64ghost** [comment]
03004f8e790000000600000000000000,G-Shark GS-GP702,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,crc:8e4f,

![1](https://github.com/libsdl-org/SDL/assets/77530734/b9ef3f6f-671c-47d8-a5b0-40b25f092d14)

**Comment by slouken** [comment]
Added, thanks!
