### ISSUE TITLE
No support for Magic-X + Xbox x-input controller

### ISSUE THREAD

**Issue by CorpseSlayer** [libsdl-org/SDL#8073]
I have try some how to test SDL with magix -X + plus a xbox series S controller
and fpPS4 now that is using SDL for controller detection but SDL wont detect
or do anything  while using May Flash Magic-X

**Comment by slouken** [comment]
I have a Magic-X and it's plugged into my PC and it shows up as an Xbox 360 controller to SDL. I connected an Xbox Series S controller both wired and over Bluetooth to the Magic-X and it works fine here.

What version of SDL are you using, and what is your Magic-X connected to?

**Comment by CorpseSlayer** [comment]
Not worry there was and update that fix this issue for me..
SDL was recognizing inputs in some games but not in others
this is the reason the Xbox S controller was not working when
using it with Bluetooth.

**Comment by slouken** [comment]
What was updated that fixed it for you?

**Comment by CorpseSlayer** [comment]
> What was updated that fixed it for you?
I believe someone in FPps4 did a fix,
[SDL2.zip](https://github.com/libsdl-org/SDL/files/12446893/SDL2.zip)

you can try it and see if it works this is the same one i am using right now
with Magic-X

> What was updated that fixed it for you?
