### ISSUE TITLE
Port PR/7607 to SDL3 (Unaligned stacks on i686-w64-mingw32, may lead to crashes)

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#8075]
See https://github.com/libsdl-org/SDL/pull/7607 (https://github.com/libsdl-org/SDL/commit/8231278817faabdff4a232770f798684bd2e12df)

It needs porting to SDL3,  at least because SDL_main is different.  (CC: @skeeto)

**Comment by sezero** [comment]
BTW, @madebr: https://github.com/libsdl-org/SDL/pull/7017 (https://github.com/libsdl-org/SDL/commit/87af5cfc9fca61eacf2297474d0215a3821194a3) seems to have removed `-mpreferred-stack-boundary=2`
in SDL3: I'm curious as to why? (BTW it was supposed to be for windows-only but
the cmake'ry used to apply it everywhere...)

**Comment by sezero** [comment]
I created an initial patch at https://github.com/sezero/SDL/commit/f82e57209c7ea9f78b438607619f2036650b4cd2 which does _not_ touch SDL_main stuff but applies the attribute to `SDL_RunApp` instead. Comments?

CC: @skeeto as author of original patch, @DanielGibson as author of SDL3 main stuff.

**Comment by madebr** [comment]
> BTW, @madebr: #7017 ([87af5cf](https://github.com/libsdl-org/SDL/commit/87af5cfc9fca61eacf2297474d0215a3821194a3)) seems to have removed `-mpreferred-stack-boundary=2` in SDL3: I'm curious as to why? (BTW it was supposed to be for windows-only for #477 but the cmake'ry used to apply it nowhere...)

CMake was checking for `-mpreferred-stack-boundary=2`, and storing the result in `HAVE_GCC_PREFERRED_STACK_BOUNDARY`.
But nobody was using that variable: it was not added to the compile options.
