### ISSUE TITLE
sys/sysctl.h file not found when compiling for Android

### ISSUE THREAD

**Issue by JES101** [libsdl-org/SDL#8078]
I've been trying to get a very simple C++ program to compile for Android. All of the code is in one file called "main.cpp." I've seen a few different error messages as I've adjusted versions for JDK, Gradle, and Android Studio. I tried to follow the instructions from the /docs/README-android.md file. I was trying to do things without Android Studio, but I have been using it to try to help with debugging.

Android Studio version: 2022.3.1
openjdk version: 17.0.8
Android SDK platform package version: Android 13.0 ("Tiramisu")
SDL2 version: 2.28.1

I'm developing on a Macbook with Intel chip and everything builds and runs fine locally with a `clang++ -Wall -g -lSDL2 -lSDL2_ttf main.cpp -o main`. When I run the androidbuild.sh program, it generates a project for me. But when I navigate to the directory for the project and run `./gradlew installDebug, it fails. The error message indicates a problem with SDL.c, so I don't think removing SDL2_ttf would be beneficial. I've attached a reference to the error ([debug.log](https://github.com/libsdl-org/SDL/files/12264054/debug.log))

If I try to build the project in Android Studio, I get a different error message.
`> Task :app:buildNdkBuildDebug[x86] FAILED
C/C++: /Users/jared/qt/deps/SDL2-2.28.1/build/com.test2/app/jni/SDL/src/cpuinfo/SDL_cpuinfo.c:49:10: fatal error: 'sys/sysctl.h' file not found
C/C++: #include <sys/sysctl.h>
C/C++:          ^~~~~~~~~~~~~~
C/C++: 1 error generated.
C/C++: make: *** [/Users/jared/Library/Android/sdk/ndk/23.1.7779620/build/core/build-binary.mk:476: /Users/jared/qt/deps/SDL2-2.28.1/build/com.test2/app/build/intermediates/cxx/Debug/50293c39/obj/local/x86/objs-debug/SDL2/src/cpuinfo/SDL_cpuinfo.o] Error 1`

This makes me think that the HAVE_SYSCTLBYNAME macro might somehow be getting set incorrectly, since it looks like that import will only occur if that macro value is set. Maybe?

I also get the `error: invalid input constraint 'a' in asm  __asm__ ("hreset $0" :: "a"(__eax));` from Android Studio, which I think might be related since it is also tied to settings on macro variables.

I tried to run the same thing from an exported zip of the SDL3 repository earlier today, but I got an error that some .c files were missing, so I couldn't get anything running locally. So while SDL3 is stabilizing, I've been trying to build with SDL2. It's likely that I'm doing something wrong, especially since I don't see other sysctl.h bug reports and the other issues related to 'invalid conversion between vector type' issues seem to have been resolved prior to the 2.28.1 version of SDL. That said, this looks to me like a bug.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
