### ISSUE TITLE
SDL_SetSurfaceColorMod on indexed surfaces

### ISSUE THREAD

**Issue by BumfuzzledGames** [libsdl-org/SDL#8079]
Calling `SDL_SetSurfaceColorMod` on an indexed surface returns 0, but breaks blitting when blitting to RGB surfaces. As far as I can tell, this sets an invalid combination of flags and `SDL_CalculateBlit1` will return NULL.

Calling `SDL_SetSurfaceColorMod` on an indexed surface should return an error or have no effect on blitting.

**Comment by slouken** [comment]
That seems reasonable to me, I'll go ahead and make that change.

**Comment by slouken** [comment]
Actually, it seems reasonable that this would be supported. I'll add it to the 3.0 milestone and we can look at it then.
