### ISSUE TITLE
size_t vs Sint64

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8084]
We changed the SDL RW interfaces to use Sint64 for sizes so we could support large files and still return error codes. However, I'm continually having to cast between that and size_t for things like string operations, memory allocations, etc. This continues out into application code where all calls to and from the RW API have to have sizes cast.

I'd really like to switch the RW API back to use size_t so it's more in line with other APIs that it replaces, but I don't have a solution for returning rich error codes.

@libsdl-org/a-team, thoughts?

**Comment by sezero** [comment]
Current Sint64 is fine with me: casting should be a minor inconvenience.

One thing to consider with current situation however is 32 bit platforms,
i.e. we should make sure that an Sint64 result is never ever greater than
SIZE_MAX, where it matters.

**Comment by slouken** [comment]
Using SDL shouldn't have minor inconveniences, that's sort of the point. :)

We have a context structure that we can easily put status flags into if we want to signal error conditions.

I'll try out a prototype of that and see what impact that has on things like SDL_image and SDL_mixer, that use the API heavily.

**Comment by slouken** [comment]
Oops... fundamental problem here, size_t is often 32-bit on 32-bit platforms, but we support 64-bit files.

**Comment by icculus** [comment]
Although, to be fair, you can't read more than your address space can hold in a single operation.  :)

We talked about this before in #6729, fwiw, if any of that discussion should be revisited.

**Comment by slouken** [comment]
Yeah, I've done more work with rwops and the constant casting has been a pain. I'll play with this a bit.

**Comment by slouken** [comment]
I'm closing this and reopening the other issue for further discussion.

**Comment by slouken** [comment]
Implemented!

**Comment by icculus** [comment]
Just ran into this...we ended up back where we started: we can't differentiate between EOF and error on calls to SDL_RWread(). Do we want to change this API further?

**Comment by slouken** [comment]
There’s a flag on the rwops object now.
