### ISSUE TITLE
testsurround times out during build-time testing if SDL_TESTS_QUICK is not set

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#8088]
`testsurround` sleeps for `CHANNEL_TEST_TIME_SEC` (5 sec) per channel (typically 2).

The default timeout for non-interactive tests is 10 seconds.

This seems like a bad interaction whenever you have a better-than-mono audio output device :-)

Is the intention that `SDL_TESTS_QUICK` will be set whenever the tests are run non-interactively? If it is, then the CMake/CTest glue should make that be the default, and `test/template.test.in` should perhaps also be running:

```
Exec=env SDL_TESTS_QUICK=1 @installedtestsdir@/@exe@ @noninteractive_arguments@`
```

Or, if the intention is that this test will take 10+ seconds (depending on audio backend), then it needs a longer timeout.

**Comment by icculus** [comment]
It's meant to test playback to each channel of a device...if someone has a 7.1 setup, it's okay if it runs for 40 seconds. :)

If it has to be excluded from things that run as "quick," I'm fine with that. This one is meant to be more diagnostic than an ongoing unit test that has to run every time.

**Comment by smcv** [comment]
My high-level goal here is that a packager or user doing the most obvious possible `cmake .. && make && make test && make install` sequence should get tests that have some reasonable amount of automated coverage, and reliably pass.

One option is to make the CTest glue automatically export `SDL_TESTS_QUICK=1` (and maybe `SDL_AUDIO_DRIVER=dummy`, `SDL_VIDEO_DRIVER=dummy`?) when we run automated tests. Users can still run the test executable manually, without those environment variables, if they want a longer, more thorough manual test (which might require for example listening to each speaker and checking that the right noises come out). At the moment the Github CI does this and as a workaround I've done the same in my in-progress Debian packaging; but if the default test timeout is going to be set too short for non-quick tests to complete successfully, then requiring users/packagers to "just know" that they are expected to do this seems like an unnecessary hoop to jump through.

Another option is to give it a long enough `SDL_NONINTERACTIVE_TIMEOUT` for any reasonable number of speaker channels.

A third option, if this is meant to be a manual test and doesn't provide meaningful automated coverage, would be to drop its `SDL_NONINTERACTIVE` flag so that `make test` won't run it automatically at all.

I see there are some other tests that respond to `SDL_TESTS_QUICK=1`. Are we expecting that packagers (and other users who want a non-interactive smoke test to check that changes in SDL or a dependency haven't made it regress) should be running these tests with or without `SDL_TESTS_QUICK=1`? I think the right solution to choose is influenced by the answer to this question.

**Comment by smcv** [comment]
> My high-level goal here is that a packager or user doing the most obvious possible `cmake .. && make && make test && make install` sequence should get tests that have some reasonable amount of automated coverage, and reliably pass.

Similarly, I want `ginsttest-runner SDL3/` (which runs each command named in `/usr/share/installed-tests/SDL3/*.test`) to give us non-interactive tests that have some reasonable amount of automated coverage, and reliably pass. We use this in Debian to check that changes in SDL's dependencies won't make SDL regress - every time one of our dependencies is updated, the SDL tests are re-run, and if the tests fail then that's a bug in either the updated dependency or SDL.

I realise the amount of non-interactive coverage we can usefully have for SDL is limited, because so much of what SDL does is fundamentally an interactive thing, but some test coverage is better than no test coverage.

**Comment by icculus** [comment]
I'm not against an option that says "run for no more than X seconds" and the test will just distribute that time between each channel, with a little wiggle room for overhead.

**Comment by slouken** [comment]
That particular test should only be run interactively. It has no value as an automated test.
