### ISSUE TITLE
SDL_GetGlobalMouseState does not update the input mouse position after doing a SDL_SetWindowGrab()

### ISSUE THREAD

**Issue by tylerfan** [libsdl-org/SDL#8090]
if the window is not full screen, and the initial cursor is somewhere outside the window, the cursor will move to the closest edge of the window based on x11 doc here https://tronche.com/gui/x/xlib/input/XGrabPointer.html

However, directly query the cursor position using SDL_GetGlobalMouseState right after the SDL_SetWindowGrab without new motion events, the reported cursor location is still the old location while the cursor actually has been moved inside the window already.  the global_mouse_changed is false reading the code basically means SDL_SetWindowGrab won't update the input position . This is a subtle behavior, but i wonder whether this is a wrong behavior.

**Comment by slouken** [comment]
We just need to set videodata->global_mouse_changed when grabbing input.
