### ISSUE TITLE
Wiki is broken

### ISSUE THREAD

**Issue by rainerdeyke** [libsdl-org/SDL#8093]
The wiki is broken.  I noticed the problem on https://wiki.libsdl.org/SDL2/CategoryVideo, but I expect that other pages are also affected.  Here is a screenshot of what it looks like to me:

![wiki_error](https://github.com/libsdl-org/SDL/assets/10830454/3ed5fdd8-e321-4fbb-8cfb-0de024089c37)

Note that the items listed under Functions are types, not functions.

**Comment by icculus** [comment]
We're tracking this stuff over here: https://github.com/libsdl-org/sdlwiki/issues/344
