### ISSUE TITLE
Only fire audio stream callbacks if data is actually needed?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8095]
> We change the SDL3 audio stream callback to only fire when something reads from a stream _and the stream needs more data to fulfill the request_. Right now it always fires, in case the app wants the status update, since the app isn't required to fulfill a request of any size here, in any case, but that might be silly.

_Originally posted by @icculus in https://github.com/libsdl-org/sdl2-compat/issues/94#issuecomment-1670448845_

(This might not be worth changing, but I'm opening a bug so I don't forget to consider this further.)

**Comment by icculus** [comment]
So the specific problem was that WASAPI, with its tiny buffers, could get into a situation where you always get requests for 0 bytes because you're _never_ making forward progress, but that was a bug and was fixed.

With that fixed, I'm inclined to leave this as-is ("some one is requesting more audio and we can fulfill the request without you providing additional data, but you may want to run some upkeep code in your callback anyhow").

If there's no disagreement, I'll close this bug in a day or two.

**Comment by slouken** [comment]
I think that might be confusing. If someone has regular upkeep they're likely to be running that on a timer or other parallel mechanism. I think it's more clear to get "we need more audio" when the system actually needs more audio.

**Comment by icculus** [comment]
Your wish is my command.  :)
