### ISSUE TITLE
Feature request (if possible): expose system-level gamepad deadzone

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#8099]
I know this might get thrown-out, but if there's a chance, could we have something like a `SDL_GetGamepadGetFlat()` & `SDL_GetGamepadSetFlat()`, if possible? I know it's possible to set the system-level dead zone for an xbox controller in Windows. Can this be done from SDL? And I've noticed in Android there is a `InputDevice.MotionRange.getFlat()`. 

How does the Steam Client handle deadzones? Does it set them on a system level, or a Steam level?

In my Android Game Controller Tester app, I get a lot of criticism that users can't set the controller's dead-zone on their gamepad (not just for the app / game, but for all games). 

My knowledge of this area is very limited, so apologies if it's not a good suggestion / request.

**Comment by slouken** [comment]
I'm not seeing any way to adjust this globally on Android. All of the answers I've found involve changing settings in individual applications.

**Comment by slouken** [comment]
The Steam client sends through the exact axis values by default so games can do their own sensitivity settings. There is a way to override this, but it's off by default because often games will have their own dead zone and adding another one just reduces usable axis range.
