### ISSUE TITLE
[uwp] testmessage segfaults after clicking OK in all message boxes

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8105]
After clicking on OK in all message boxes, a segfault occurs.

At this location:
https://github.com/libsdl-org/SDL/blob/8e99a4f4f5789335fb170e0cd8c953c4e4335b0f/src/core/winrt/SDL_winrtapp_direct3d.cpp#L399

The following is printed to stdout:
```
Exception thrown: read access violation.
**this** was nullptr.
```

Using `SDL_Log` debugging, I found `CoreWindow::GetForCurrentThread()` returns `null`.

Call stack:
```
 	SDL3.dll!Windows::UI::Core::ICoreWindow::Dispatcher::get()	C++
>	SDL3.dll!SDL_WinRTApp::PumpEvents() Line 399	C++
 	SDL3.dll!WINRT_PumpEvents(SDL_VideoDevice * _this) Line 54	C++
 	SDL3.dll!WINRT_ShowMessageBox(const SDL_MessageBoxData * messageboxdata, int * buttonid) Line 96	C++
 	SDL3.dll!SDL_ShowMessageBox(const SDL_MessageBoxData * messageboxdata, int * buttonid) Line 4937	C
 	testmessage.exe!button_messagebox(void * eventNumber) Line 61	C
 	SDL3.dll!SDL_RunThread(SDL_Thread * thread) Line 290	C
 	SDL3.dll!RunThread(void * data) Line 50	C
 	SDL3.dll!RunThreadViaCreateThread(void * data) Line 64	C
 	[External Code]	
```

Tested with UWP cmake support proposed in https://github.com/libsdl-org/SDL/pull/7633.

**Comment by icculus** [comment]
UWP support was removed from SDL3, so this is a WONTFIX now.
