### ISSUE TITLE
Display does not get recognized desite being connected

### ISSUE THREAD

**Issue by m00tY** [libsdl-org/SDL#8110]
As I began toying with the SDL2 Library (version 2.28) on my new debian system, I ran into am issue where despite the creation of a window, the window itself would never actually display. The reason that I am making this issue is due to the fact that there was CPU utilization being taken up by the "invisible window program" which I only noticed after opening task manager. I also ran the following benchmark which showed that I somehow had zero displays connected, even though the function that checks for the number of displays can only return positive integers above 1 or negative values as error codes.
```C
#include "SDL2/SDL_video.h"
#include <stdio.h>
#include <SDL2/SDL.h>
#include <stdbool.h>

int main(void)
{
	if (SDL_InitSubSystem(SDL_INIT_EVERYTHING) < 0)
		SDL_Log("SDL fails to initialize! %s\n", SDL_GetError());

	int num_drivers = SDL_GetNumVideoDrivers();
	printf("Number of drivers: %d\n", num_drivers);
	for (int i = 0; i < num_drivers; i++)
		printf("VIDEO Driver name: %s\n", SDL_GetVideoDriver(i));

	int num_displays = SDL_GetNumVideoDisplays();
	printf("Number of displays: %d\n", num_displays);
  printf("DISPLAY NAME: ", SDL_GetDisplayName);
	

	SDL_Window *window = SDL_CreateWindow("SDL Tutorial", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, SDL_WINDOW_SHOWN|SDL_WINDOW_ALWAYS_ON_TOP|SDL_WINDOW_FULLSCREEN);

	int w, h;
	SDL_GetWindowSize(window, &w, &h);
	printf("Window dimensions: %dx%d\n", w, h);

	bool quit = false;
	SDL_Event e;
	while (!quit) {
		while (SDL_PollEvent(&e)) {
			if (e.type == SDL_QUIT) {
				quit = true;
			}
		}
	}

	SDL_DestroyWindow(window);

	return 0;
}
```
RESULT OF BENCHMARK TEST:
```console
INFO: SDL fails to initialize! dsp: No such audio device
Number of drivers: 3
VIDEO Driver name: offscreen
VIDEO Driver name: dummy
VIDEO Driver name: evdev
Number of displays: 0
DISPLAY NAME: Window dimensions: 640x480
```
Although I am fairly new the SDL2 library, this seems like an unexpected behavior worth reporting.

Thanks!

**Comment by Kontrabant** [comment]
It looks like your SDL library was built without the X11 or Wayland backends. Check the `docs/README-linux.md` file and make sure you have the required dependencies installed.

**Comment by m00tY** [comment]
> 

This worked perfectly, thank you for the suggestion.
