### ISSUE TITLE
SDL_GetGPUString(): glGetString()-like function but with multiple backends

### ISSUE THREAD

**Issue by time-killer-games** [libsdl-org/SDL#8117]
So my thoughts on this are this would mimic glGetString(), but allow for multiple backends, getting the PCI ID hex integer, as well as a more descriptive form of what is returned by glGetString() like what you can get from parsing pci.ids. You can grab the most up to date version of the pci.ids file from this download link: https://pci-ids.ucw.cz/pci.ids 

```
SDL_GetGPUString(SDL_GPU_VENDOR, nullptr);     // Intel (glGetString(), etc)
SDL_GetGPUString(SDL_GPU_VENDOR_EX, &pciID);   // Specific Name (from pci.ids file)
SDL_GetGPUString(SDL_GPU_RENDERER, nullptr);   // Intel(R) UHD Graphics (glGetString(), etc)
SDL_GetGPUString(SDL_GPU_RENDERER_EX, &pciID); // Specific Name (from pci.ids file)
```
The second argument of SDL_GetGPUString() would be filling the argument with the value of the PCI ID associated with the more descriptive string which holds a more exact company name or renderer. See the pci.ids file for examples of these. These functions would return a string, and would use whatever graphics renderer context currently utilized to get the necessary information. On Windows you can use dxgi without having to resort to creating any graphics context. Same is true for mac but you would need to parse the output of shell scripts with CLI apps like ioreg or the system profiler. On open source platforms like Linux, *BSD's and Illumos you would need a solution a bit more tricky which relies on the current graphics context in use. Also see this for help: https://github.com/time-killer-games/ween

But that's not a big deal because SDL won't be useful without a rendering context, as it is used most for games. I have code for this if you would like to me to help provide pointers on how to implement this, though I am too busy to make a pull request this involved. macOS might have a solution which doesn't require shell scripts, but I have yet to find that.

**Comment by YJN1024** [comment]
Give me some tokens from the ETH chain. 0x87F555Eba5B7Ab9Ea53867BabC23921F85DBa567

**Comment by slouken** [comment]
We're thinking about adding these as properties for the SDL 3.0 renderers

**Comment by slouken** [comment]
The problem with doing things like this, even as properties, is that games start to rely on it and there are drivers or platforms where the information is not available or is formatted differently, etc. I think we'll hold off on this for now.
