### ISSUE TITLE
Controller mappings are parsed incorrectly if name contains a comma

### ISSUE THREAD

**Issue by rsn8887** [libsdl-org/SDL#8128]
Some controllers have a comma in their official name, such as
"HORI CO.,LTD. HORI Fighting Commander OCTA" (see the issue here  https://github.com/batocera-linux/batocera.linux/issues/8568)

SDL will get confused when parsing game controller mappings where the controller name contains a comma. For example the code here is problematic because it looks for an explicit comma:

https://github.com/libsdl-org/SDL/blob/0b9d8e679a26ee98bb055efd244c703b7dda8727/src/joystick/SDL_gamecontroller.c#L1175

Other explicit reliances on comma can be found by searching SDL_gamecontroller.c for occurrences of ','.

I am not sure how to fix this in a general way. The bottom line is that SDL should allow controller names with a comma in their name string, since such controllers exist.

**Comment by slouken** [comment]
We do, they're stripped out when creating mapping strings using the SDL gamepad tools.
