### ISSUE TITLE
Joystick plugout give assert message on last version 2.28.2 (Assertion failure at SDL_AssertJoysticksLocked)

### ISSUE THREAD

**Issue by abin2017** [libsdl-org/SDL#8146]
hello brothers, here is the detail:

test enviroment, 

- linux platform, 
- video driver 'kmsdrm', 
- SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_TIMER | SDL_INIT_JOYSTICK), 
- defined SDL_USE_LIBUDEV, SDL_INPUT_LINUXEV
- SDL 2.28.2 and 2.26.5 

plugout joystick give assert. debug by gdb in SDL_PumpEventsInternal process event, 
```
    /* Get events from the video subsystem */
    if (_this) {
        _this->PumpEvents(_this);
    }

#if !SDL_JOYSTICK_DISABLED
    /* Check for joystick state change */
    if (SDL_update_joysticks) {
        SDL_JoystickUpdate();
    }
#endif
```

it will process joystick hotplug event in KMSDRM_PumpEvents, it will call enter SDL_PrivateJoystickAdded not take lock
```
KMSDRM_PumpEvents->SDL_EVDEV_Poll->SDL_UDEV_Poll
```

**Comment by slouken** [comment]
Thanks for the excellent details. This is fixed for the next release.
