### ISSUE TITLE
Expose separate SDL_RunApp setup/teardown functions (calling SDL_RunApp in non-C languages)

### ISSUE THREAD

**Issue by LunarLambda** [libsdl-org/SDL#8149]
When using SDL from languages other than C/C++, it may still be desirable to call SDL_RunApp rather than re-implementing it. However, due to its signature requiring a C-ABI-compliant main() function, this prevents languages such as Rust from being able to return other types from main (as well as needing additional C-ABI wrapping code)

Exposing the setup and teardown as their own functions, such as `SDL_InitApp` and `SDL_QuitApp` would be beneficial, since it allows the "call main()" portion of the code to be tailored to the language.

Currently, in Rust, we'd need to do something akin to this:

```rust
// macro that transforms main to call the SDL initialization and teardown code
//
// main() can also return void, or Option<...> or a status code...
#[sdl::main]
fn main() -> Result<...> {
    <code>
}
```
which gets transformed into something like this: (pseudocode, unclear if this would even compile)
```rust
// New, generated main() wrapper
fn main() -> Result<...> {
    static mut RETURN: Option<Result<...>> = None;

    extern "C" fn sdl_main(_argc: c_int, _argv: *const c_void) -> int {
        // Our original main is buried all the way in here!
        RETURN = Some({ <code> });
        return 0;
    }

    SDL_RunApp(0, ptr::null(), sdl_main, ptr::null_mut());

    return RETURN.unwrap();
}
```

This has a lot of issues, such as needing hidden globals, being a lot of code for a single setup function, and also not being unwind safe (if main() throws an exception ("panics"), it will unwind into SDL_RunApp and probably hard-crash the program)

Instead, ideally, we'd want to have something like this instead: (pseudocode)

```rust
fn main() -> Result<...> {
    SDL_InitApp(ptr::null_mut());
    let result = { <code> };
    SDL_QuitApp();
    return result;
}
```

The downside is that this *does* require storing additional global state on SDL's side (storing pointers/handles to resources that need freeing in `SDL_QuitApp()`) but that feels like a lot less of a burden of implementation, since `SDL_RunApp` can then similarly be turned into
```c
int SDL_RunApp(int argc, char **argv, SDL_main_func mainFunction, void * reserved)
{
    SDL_InitApp(reserved);
    int ret = mainFunction(argc, argv);
    SDL_QuitApp();
    return ret;
}
```
for all platforms.

**Comment by slouken** [comment]
@DanielGibson, thoughts?

**Comment by DanielGibson** [comment]
Sorry, I missed this, I was on vacation.

I'll have to think about the problem

**Comment by DanielGibson** [comment]
That probably wouldn't work on iOS, at least in the way it's implemented now, because the main-callback is stored as a global variable that is called from elsewhere: https://github.com/libsdl-org/SDL/blob/main/src/video/uikit/SDL_uikitappdelegate.m#L400-L420

**Comment by slouken** [comment]
Does 9c664b00623926a0973a8f19cecc55bc7c757d5b do what you need here?

**Comment by LunarLambda** [comment]
I'm not sure. Would have to think about it. The issue remains that Rust can't easily make use of SDL_main.h, and the callback nature of SDL_RunApp is very difficult to bridge to Rust's idiomatic main function signature. One issue is that Rust expects to be allowed to unwind out of main(), which is not possible if Rust main() is redirected through SDL_RunApp.

I'll look at the PR in more depth later. Thank you for the consideration and work on this so far.

**Comment by icculus** [comment]
I'm inclined to not make changes to this; for one thing, `argc` and `argv` are decided on most platforms by what would be the init code (these are almost always 0 and NULL coming into SDL_RunApp on Windows, for example), and would have to be passed _back_ to the caller to call SDL_main (and then passed into the quit function to free them), so it's not a simplification at all.

Are we _sure_ Rust couldn't handle the existing interfaces in a reasonable (if perhaps not perfectly ideal) way?

**Comment by icculus** [comment]
Okay, I'm passing on this one. But if Rust absolutely can't work at all without this, please do make some noise here and we'll revisit.

**Comment by LunarLambda** [comment]
I'll revisit this once 3.2.0 releases and see what comes up on the Rust side. Probably not worth it to bikeshed the current machinery for now.

**Comment by slouken** [comment]
Just remember, once 3.2.0 releases, the ABI is locked. We can extend it, but we can't change existing interfaces, so if there's something that fundamentally needs to change, now's the time to do it.

**Comment by madebr** [comment]
@LunarLambda

Can you please prepare a minimum rust cargo project with minimal (unsafe :) ) SDL bindings?
We can then maybe get feedback in the wider rust community, and iterate on it.

**Comment by LunarLambda** [comment]
Another thing that would help would be a list of platforms that Rust supports (WinRT isn't currently one of them) that definitely want/need the SDL_main stuff. I think iOS might, and emscripten. Maybe someone could help me figure out the exact list, I get easily lost in the SDL_main stuff

**Comment by LunarLambda** [comment]
I guess a better question would be: does SDL *need* argc/argv for anything other than passing it to main()?

Rust's runtime already provides access to argv through its own means, so assuming SDL doesn't do anything with it except pass it through, we could just get away with always passing 0/NULL to SDL_RunApp

**Comment by icculus** [comment]
> I guess a better question would be: does SDL need argc/argv for anything other than passing it to main()?

Only for passing it to SDL_main, afaik. External things that alter SDL's behavior are all environment variables.

Note that RunApp on some exotic platforms--usually homebrew game console stuff--might do a few other init things in SDL_RunApp before calling SDL_main(), but I would worry about those as individual tasks if and only if someone tries to get Rust code running on a Sony PSP or whatever in the future.

**Comment by icculus** [comment]
For example, here's SDL_RunApp for most platforms:

https://github.com/libsdl-org/SDL/blob/ab53ff77bbe15507150a9bf072dd4201915bcbdb/src/main/SDL_runapp.c#L27-L41

**Comment by LunarLambda** [comment]
In that case I think I can probably make Rust use SDL_RunApp as is while keeping everything working as Rust users would expect.

I will experiment over the weekend and report back

**Comment by LunarLambda** [comment]
Okay so I've been looking over it and. Theoretically it's possible to call `SDL_RunApp` without restricting Rust's `main()` function with respect to its return types and exception handling.

However the whole thing is quite messy right now.

Basically, the end user would write something like
```rs
#[sdl3::main]
fn main() -> SomeReturnType {
    /* user code */
}
```

And this would get transformed into something like

```rs
fn main() -> SomeReturnType {
    fn user_main() -> SomeReturnType {
        /* user code */
    }

    use std::mem::MaybeUninit;
    use std::sync::atomic::{AtomicPtr, Ordering};
    type R = std::thread::Result<SomeReturnType>;

    // Storage space for the return value of user_main(), or an exception produced by it
    let mut return_slot = MaybeUninit::<R>::uninit();

    // We will store the pointer to return_slot in this, such that sdl_main_shim below can write the return value to it.
    static RETURN_PTR: AtomicPtr<R> = AtomicPtr::new(std::ptr::null_mut());
    RETURN_PTR.store(return_slot.as_mut_ptr(), Ordering::SeqCst);

    // C-ABI shim that calls user_main and smuggles the return value out of it
    unsafe extern "C" fn sdl_main_shim(_argc: c_int, _argv: *mut *mut c_char) -> c_int {
        let ptr = RETURN_PTR.load(Ordering::SeqCst);
        let result = std::panic::catch_unwind(user_main);
        unsafe { ptr.write(result); }
        return 0;
    }

    // Call SDL_RunApp
    unsafe {
        // SDL doesn't care what we pass as `argc/argv` in any way.
        sdl3_sys::SDL_RunApp(0, std::ptr::null_mut(), Some(sdl_main_shim), std::ptr::null_mut());
    }

    // SAFETY: This was initialised by sdl_main_shim by means of RETURN_PTR.
    let result = unsafe { return_slot.assume_init() };

    match result {
        Ok(r) => r, /* return result of user_main */
        Err(e) => std::panic::resume_unwind(e) /* propagate exception, if it had one */
    }
}
```

This is probably as short as I can make it, and the use of the `static AtomicPtr` is quite bothersome, as it might not be supported on all platforms that SDL might support, and it's really just an ugly redundant hack.

Ideally, I would be able to pass the pointer to `return_slot` to `sdl_main_shim` directly as an argument through `SDL_RunApp`. I thought about abusing the `argv` argument for this, but that doesn't work, since e.g. on Windows, `SDL_RunApp` ignores `argv` and passes its own version instead.

Really, Rust doesn't care about `SDL_RunApp` at all. It only cares about any initialisation and deinitialisation steps `SDL` might want to perform. Having `SDL_RunApp` call `main` and therefore sit permanently in our call stack is quite bothersome as you can see.

But this is still a *reasonable* solution to me, I just wish it didn't have to involve any unnecessary global variables at this point.

**Comment by LunarLambda** [comment]
Bumping this to ask for some feedback on the above? I hope this can clarify the issue I was trying to solve in the original issue post.

**Comment by maia-s** [comment]
FWIW, I'm working on the "official" raw SDL 3 bindings for Rust over at https://github.com/maia-s/sdl3-sys-rs ("official" in the sense that this is the original sdl3-sys rust crate, which I took over maintainership of earlier this year (and rewrote to generate platform independent bindings regardless of generator platform), raw in the sense that it's just the bindings for other crates to build higher level abstractions on top of). @LunarLambda we should probably talk so we don't duplicate efforts?

**Comment by LunarLambda** [comment]
Right, my plan is to build high level bindings. However back when I started this effort the sdl3-sys crate was, as far as I can remember, either unmaintained and/or the author had no interest in contributions or letting someone else have the crate name, so I started making my own. 

If someone else is doing high quality raw bindings that would take a lot of annoying platform work off my shoulders :)

**Comment by maia-s** [comment]
That's my goal 😊. If you have any comments or issues, please do let me know over there

**Comment by icculus** [comment]
So a general goal is for SDL to be usable by not just something that will compile to native code, but also from a scripting language binding where main() is not negotiable, because it's already been called long before an SDL shared library was even loaded.

I guess I would say here that what Rust should be doing is _not_ using SDL_RunApp at all.

It should just call SDL_SetMainReady(), which is basically used to signal to SDL: "I didn't use the RunApp stuff but I know what I'm doing," and be done with it. SetMainReady literally just sets a flag so SDL_Init knows that the app wasn't built horribly wrong somehow.

And maybe this approach needs to have some special-case code on a Nokia N-Gage or a PlayStation 2 or whatever, but I think the simplest way to avoid all that code and having SDL_RunApp wedged in the callstack forever is just to not ever call it from the Rust bindings.

**Comment by icculus** [comment]
(with that said, if the best way forward is in fact to not do anything here, can we close this issue?)

**Comment by LunarLambda** [comment]
yeah, I suppose so. I don't think many people using Rust are targeting either of those platforms, and I don't think Rust supports WinRT targets either.

The list of targets I care about having work properly is Desktop OSs (Win, Mac, Linux, other Unixes), maybe mobile (Android/iOS), consoles that would support both modern SDL and Rust (which right now is only the Nintendo Switch I believe), and web targets (wasm/emscripten)

I think only 2 or 3 of these are likely to require anything special, and maybe it would be simpler to just have Rust-native startup code for those targets that does the same things as SDL would.

**Comment by maia-s** [comment]
My current plan for `sdl3-sys` is to provide one or more proc-macros (function attributes) for setting up the main callbacks interface with Rust using `SDL_EnterAppMainCallbacks`, which if I understand correctly requires also going through `SDL_RunApp` first on some platforms? (@icculus is that correct?)  Given that, providing a proc-macro for basic passing through `SDL_RunApp` as well is no extra work. (The expansions of the macros could be different on platforms that don't use a traditional main, but they'd still require a different build process for that to work.)

These would both be optional, of course. I want to make this functionality available to Rust programs since SDL provides it, but it's up to the user what they want to make use of, and since `sdl3-sys` is only low-level bindings it's not the place to put more advanced abstractions. I wasn't planning on supporting arbitrary returns from main, for example, I don't think that's used very often.

(Technically, these wouldn't actually be part of `sdl3-sys`. Proc-macros have to be separate from other crates anyway, so unless they would depend on specific `sdl3-sys` configuration, they can be wholly separate optional crates you only bring in if you want them)

As an aside, panics raised in Rust no longer pass through to extern "C" functions if they're not caught, but automatically abort the process, so no UB can occur there.

**Comment by LunarLambda** [comment]
We can discuss that on the sdl3-sys crate repository in future. For your reference, here's what I did to call SDL_RunApp while propagating panics across the FFI boundary and retain Rust's default return-from-main behaviour: https://github.com/libsdl-org/SDL/issues/8149#issuecomment-2294824915
