### ISSUE TITLE
crash when turning off and back on external monitor

### ISSUE THREAD

**Issue by gucio321** [libsdl-org/SDL#8152]
When I build an SDL app (e.g. [PPSSPP](https://github.com/hrydgard/ppsspp) or example_sdl2_opengl3 from [imgui](https://github.com/ocornut/imgui)) it crashes when I turn off and back on my external monitor

- ref: https://github.com/hrydgard/ppsspp/issues/17910
- ref: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6941

OS: Fedora 38
SDL version: 2.26.3-1.fc38

**Comment by slouken** [comment]
There were some fixes for this in 2.28, can you try with the latest SDL release?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.
