### ISSUE TITLE
Should GDK enable dynapi?

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#8154]
Per https://github.com/libsdl-org/SDL/commit/c0cd8c8142b70c70da4dddc32244da6593cb6bb0#commitcomment-125530365:

> Actually now that I think about it, I'm not 100% sure we should even have dynapi enabled for GDK titles, since the packages are usually sandboxed and encrypted anyhow... if we want to add it to the table anyway go ahead and push that change; otherwise we should probably just disable dynapi in the GDK project files.

**Comment by slouken** [comment]
We can disable it like we do for iOS and other embedded-ish platforms.

**Comment by flibitijibibo** [comment]
I think that's the way to go for now; I'm not 100% sure if it's possible to make it work on Windows (might need mod support enabled, lol) but Xbox definitely doesn't need it.
