### ISSUE TITLE
SDL_AudioStream on Ubuntu

### ISSUE THREAD

**Issue by Michael-LightGameFramework** [libsdl-org/SDL#8155]
Device OS : Ubuntu 22.04.3 LTS
CPU: Intel® Core™ i7-8565U CPU @ 1.80GHz × 8
Audio Card: Audio device: Intel Corporation Cannon Point-LP High Definition Audio Controller (rev 30) (prog-if 80)
	Subsystem: Lenovo Cannon Point-LP High Definition Audio Controller
	Flags: bus master, fast devsel, latency 32, IRQ 147
	Memory at 93318000 (64-bit, non-prefetchable) [size=16K]
	Memory at 93000000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_cnl

### The Problem
I'm having issues with the new SDL3 audio stream API.
Specifically binding a stream to an output device, whether it's using SDL_BindAudioStream() or SDL_CreateAndBindAudioStream() I end up getting a pop-up that says the following

Popup Title: "Assertion Failed"
> Assertion failure at GetAudioStreamDataInternal (/home/MyHome/srcfiles/SDL-main/src/audio/SDL_audiocvt.c:1109), triggered 1 time:
  'bytes_read == input_bytes'

I tried to break down to some simple code that still reproduces the error for me:

```
#include <SDL3/SDL.h>
int main()
{
        SDL_Init(SDL_INIT_EVERYTHING);

        SDL_Window * win = SDL_CreateWindow("Timer", 300, 300, SDL_WINDOW_ALWAYS_ON_TOP);
        SDL_Renderer * screen = SDL_CreateRenderer(win, 0, SDL_RENDERER_PRESENTVSYNC);

        SDL_AudioSpec spec;
        spec.freq = 11025;
        spec.format = SDL_AUDIO_F32;
        spec.channels = 1;

        SDL_AudioDeviceID speaker = SDL_OpenAudioDevice(SDL_AUDIO_DEVICE_DEFAULT_OUTPUT, &spec);
        // error occurs on call of the following function
        SDL_AudioStream * stream = SDL_CreateAndBindAudioStream(speaker, &spec);

        SDL_Delay(4000);

        SDL_DestroyAudioStream(stream);
        SDL_CloseAudioDevice(speaker);
        SDL_DestroyWindow(win);
        SDL_Quit();
}
```

I've tried rebuilding the SDL3 libs, updating and restarting the computer, etc. 
The worst part is that initially this error only popped up half the time (now every time), so I don't know if this might be a reproducible error.
I will try downloading and fresh installing again, but I'm curious if anyone else on Ubuntu or Linux in general might also be getting similar errors.

## The Solution:
I commented out the assertion on line 1109 of src/audio/SDL_audiocvt.c, and then a following Popup meant I wrapped line 1125 and 1126 of the same file in an if statement instead of an assert. 
I do not know enough about the audiocvt library to know if this solution is contraindicated.
I'm currently trying to track down a better solution.

**Comment by Michael-LightGameFramework** [comment]
Sorry, Just trying to think things out, I think I'm on the right track:
The audio device says it is playing from the moment that it is created. 
If I pause the device before binding the audio, the popup doesn't seem to happen until after I play again and the stream runs out of data. 

What is the default behavior when a stream is empty, but the audio device is still playing?

**Comment by icculus** [comment]
In SDL3, the audio device is unpaused at start, because it doesn't actually make noise until you add an audio stream with some data in it.

This code all changed dramatically _today_ as a pull request came in; are you working from the absolute latest in git? If not, please update and see if this is still broken. If you're already on the latest, I'll take a look.

**Comment by Michael-LightGameFramework** [comment]
After reading your post I downloaded/built/installed just now, and the problem is persisting.
Thank you for the response.
I'll keep poking around the source code for a while, but I'm having trouble finding relevant code.

I'm assuming that the default behavior when a stream runs empty is to just supply the audio device with 0's, but I'm having trouble finding where that behavior might be defined.

**Comment by icculus** [comment]
There is still an optional callback, but an empty stream just supplies silence. It's legal to have a bound stream with no audio.

**Comment by icculus** [comment]
Back at a machine now; your test case reproduces here. I'll dig in.

**Comment by Michael-LightGameFramework** [comment]
Awesome, thank you.

**Comment by icculus** [comment]
@0x1F9F1 I think this is your pull request causing this one.

The audio playback code is asking for a block of data when there's none available:

```c
SDL_GetAudioStreamData(stream, buf, 24064);
```

Which calls this:

```c
const int max_available = SDL_GetAudioStreamAvailable(stream);
```

It checks the dataqueue's currently available data (zero bytes) and eventually calls this:

```c
count = GetResamplerAvailableOutputFrames(count, stream->resample_rate, stream->resample_offset);
```

...which (incorrectly?) returns 1 from this...

```c
const Sint64 output_frames = ((((Sint64)input_frames << 32) - resample_offset - 1) / resample_rate) + 1;
return (size_t) SDL_max(output_frames, 0);
```

...which much later in GetAudioStreamDataInternal causes this assert to fail, because bytes_read is zero but input_bytes is 4 (a single sample frame in this case).

```c
    if (input_frames > 0) {
        int bytes_read = (int) SDL_ReadFromDataQueue(stream->queue, input_buffer, input_bytes);
        SDL_assert(bytes_read == input_bytes);
    }
```

Bisecting blames this commit, specifically: 96e47f16576bdd794c349b808fe771275d3d6b5c

Can you take a look at this?

**Comment by 0x1F9F1** [comment]
Thanks for the clear repro and bisection. Should be fixed in #8160

**Comment by icculus** [comment]
Thank you!

@Michael-LightGameFramework, the latest in git should resolve this problem for you.

**Comment by Michael-LightGameFramework** [comment]
That was so cool to see that all. You guys are great!

**Comment by Michael-LightGameFramework** [comment]
That was so cool to see that all. You guys are great!

**Comment by Michael-LightGameFramework** [comment]
Sad to see SDL_CreateAndBindAudioStream() go away, maybe it will be back before the stable release. 
I think it was both convenient and a method to ease the way for new users of the stream API.
Oh well. Still excited to see the changes as they roll in.

**Comment by icculus** [comment]
> Sad to see SDL_CreateAndBindAudioStream() go away, maybe it will be back before the stable release.

The thinking is that we needed a dirt-simple interface for those that wanted _no_ complexity (that's the new SDL_OpenAudioDeviceStream) and the fancier API for those that want more power, and SDL_CreateAndBindAudioStream became this sort of unnecessary middle ground between the two.

It's easy to reproduce in the app, so it was only a useful convenience function when trying to simplify their init code. Here's a robust replacement:

```c
static SDL_AudioStream *CreateAndBindStream(SDL_AudioDeviceID mydevice, const SDL_AudioSpec *spec)
{
    SDL_AudioStream *stream = SDL_CreateAudioStream(spec, spec);  // 2nd param can be NULL when #8181 merges.
    if (SDL_BindAudioStream(mydevice, stream) == -1) {  // it's okay if stream is NULL here.
        SDL_DestroyAudioStream(stream);   // it's okay if stream is NULL here.
        return NULL;
    }
    return stream;
}
```

**Comment by Michael-LightGameFramework** [comment]
I did not notice the (addition of)/(replacement with) SDL_OpenAudioDeviceStream() function, this makes sense now. 
There's so many fun things happening for SDL3! 
Thanks again.
