### ISSUE TITLE
Issue with Inverted Cursor Color using SDL_CreateCursor on Windows

### ISSUE THREAD

**Issue by iGwkang** [libsdl-org/SDL#8157]
**Issue Description:**

**Summary:**
I encountered an issue related to cursor color inversion on Windows while using the SDL library. Specifically, when utilizing `SDL_CreateCursor` to create a cursor with type I data (monochrome), the cursor appears as a black "I" without any color inversion. However, the problem doesn't occur when using the Windows system API `CreateCursor`, as the cursor's color inversion works as expected.

**Steps to Reproduce:**
1. Use the SDL library in a Windows application.
2. Attempt to create a cursor with type I data using the `SDL_CreateCursor` function.
3. Observe that the resulting cursor displays as a black "I" without color inversion.

**Expected Behavior:**
When using `SDL_CreateCursor` to create a cursor with type I data, the cursor's color should be inverted, just like it happens when using the `CreateCursor` function from the Windows system API.

**Actual Behavior:**
The cursor created with `SDL_CreateCursor` and type I data remains a black "I" without any color inversion.

**Additional Information:**
- This issue is specific to the SDL library on Windows.
- Using the Windows system API `CreateCursor` does not exhibit this problem, and cursor color inversion works correctly.
- I have tested this on multiple Windows systems to ensure the issue is not isolated to a single environment.

**Environment:**
- Windows operating system (multiple versions tested)
- SDL library (version 2.x)

**Note:**
This issue is preventing me from achieving the desired cursor color inversion effect using SDL. As a workaround, I'm currently using the Windows system API, but I believe this issue should be addressed within the SDL library to ensure consistent behavior across platforms.

**Comment by slouken** [comment]
Great find, do you have a fix ready?

**Comment by iGwkang** [comment]
Thank you for your prompt response. I greatly appreciate your attention to the issue. While I haven't conducted extensive testing yet, I've come up with a potential workaround that seems to address the problem of the cursor "I" remaining black on Windows systems. Here's the code snippet I've used:

```c
int x = 0;
Uint8 *data_ = (Uint8 *) data;
Uint8 *mask_ = (Uint8 *) mask;
for (int i = 0; i < h; ++i)
{
    const uint8_t *data_line = data_ + (w / 8) * i;
    const uint8_t *mask_line = mask_ + (w / 8) * i;
    for (int j = 0; j < w / 8; ++j)
    {
        uint8_t b = data_line[j];
        uint8_t m = mask_line[j];
        data_[x] = ~m;
        mask_[x] = b ^ m;
        ++x;
    }
}

SDL_Mouse * mouse = SDL_GetMouse();

cursor = calloc(1, sizeof(*cursor));
cursor->driverdata = CreateCursor(GetModuleHandle(NULL), hot_x, hot_y, w, h, data_, mask_);
cursor->next = mouse->cursors;

mouse->cursors = cursor;
```

Please note that I haven't thoroughly tested this solution yet, but it does seem to at least address the issue of the cursor "I" consistently appearing as black. I believe this workaround could be worth exploring further to ensure that the cursor color inversion works correctly on Windows systems when using `SDL_CreateCursor`.

**Comment by slouken** [comment]
@DJm00n, I noticed this too, when using testcursor. It's not a regression in your changes, but are you able to look at this?

**Comment by DJm00n** [comment]
AFAIK inverted pixels in cursors are only supported for monochrome cursors in Windows (screen pixel is inverted [when XOR and AND mask pixels are set](https://devblogs.microsoft.com/oldnewthing/20101018-00/?p=12513) in such cursor).

Two of [standard Windows cursors](https://learn.microsoft.com/en-us/windows/win32/menurc/about-cursors) have such inverted pixels - `IDC_IBEAM` (`SDL_SYSTEM_CURSOR_IBEAM`) and `IDC_CROSS` (`SDL_SYSTEM_CURSOR_CROSSHAIR`) and you can load them with `SDL_CreateSystemCursor`.

`SDL_CreateCursor` can only create cursors from 32bit RGBA surfaces by design. We can extend `SDL_CreateCursor` with support of providing XOR and AND mask in theory... but it will work this way only on Windows.

AFAIK even [Windows Forms](https://github.com/dotnet/winforms) and [Qt](https://github.com/qt/qtbase) doesn't have support for creating custom monochrome cursors with inverted pixels at runtime.

@iGwkang I can recommend using your platform-specific workaround for now.

**Comment by slouken** [comment]
SDL_CreateColorCursor() is the one that takes a surface as RGBA pixels. SDL_CreateCursor() supports a bitmap and mask style cursor creation, and documents the values to create an inverted cursor. We should either add plumbing for monochrome cursors or change the documentation such that it's no longer supported.

**Comment by DJm00n** [comment]
@slouken oops. I missed it. I'll take a look then for fixing `SDL_CreateCursor`.

**Comment by iGwkang** [comment]
> AFAIK even [Windows Forms](https://github.com/dotnet/winforms) and [Qt](https://github.com/qt/qtbase) doesn't have support for creating custom monochrome cursors with inverted pixels at runtime.

@DJm00n There may be something wrong with what you said. Qt supports it. The above code is extracted from the source code of Qt.
Qt provides `QCursor(const QBitmap &bitmap, const QBitmap &mask, int hotX = -1, int hotY = -1)` to create a mouse

**Comment by DJm00n** [comment]
Can you please test my change https://github.com/libsdl-org/SDL/pull/8688 ?
