### ISSUE TITLE
SDL3 drawing on texture instead of screen

### ISSUE THREAD

**Issue by avafinger** [libsdl-org/SDL#8163]
Currently, i have my image data copied to the texture and the subsequent drawing is done on the screen, i would like to draw rectangles in the texture instead of the screen, i want the final image that is rendered on the screen to be pushed to a remote server.
I want to avoid any additional memcpy.

I know my texture must be created with [SDL_TEXTUREACCESS_TARGET] but if i copy the image to the texture i get a core dump.

the code:
https://github.com/avafinger/ff-rknn/blob/main/ff-rknn.c#L261

What is the correct way to do it? Is it possible?

PS: Actually I want my imageData to have the drawing objects (rectangles), i am not sure if imageData will be the same as the texture data.

**Comment by avafinger** [comment]
Another question, if my "imageData" is a dma buffer, isn't there a way to pass the fd instead of copying the content?
Apart from dma buffer, i am thinking of this:

SDL_LockTexture(texture, 0, (void **)&texture_data, &texture_pitch);
memcpy(texture_data, (void *)imageData, frameSize_texture);
SDL_UnlockTexture(texture);
.
.
Draw objects on texture
.
.
Render it on screen
.
//
// copy the texture data back to my imageData
//
SDL_LockTexture(texture, 0, (void **)&texture_data, &texture_pitch);
memcpy((void *)imageData, texture_data, frameSize_texture);
SDL_UnlockTexture(texture);

Then i can push my "imageData" to where i want...

But then there is this memcpy penalty....

**Comment by slouken** [comment]
This is a good question for the SDL discussion group:
https://discourse.libsdl.org/c/sdl-development/6
