### ISSUE TITLE
undefined behavior in audio_resampleLoss test

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8164]
I see a failure in the `audio_resampleLoss`.

https://github.com/libsdl-org/SDL/blob/3b1d1e4e31ba17eba2271f34a6c1db4ba1a883c0/test/testautomation_audio.c#L802-L807

The 3rd test spec fails for:
https://github.com/libsdl-org/SDL/blob/3b1d1e4e31ba17eba2271f34a6c1db4ba1a883c0/test/testautomation_audio.c#L926

There is undefined behavior (or failure to reset some state) into play because when only testing the 3rd spec, it succeeds.

```
ERROR: 08/27/23 00:09:05: Assert 'Conversion signal-to-noise ratio 65.823531 dB should be no less than 79.000000 dB.': Failed
ERROR: 08/27/23 00:09:05: Assert 'Maximum conversion error 0.608279 should be no more than 0.012000.': Failed
```

It reproduces on ci: https://github.com/libsdl-org/SDL/actions/runs/5987203046/job/16241153819#step:11:12460

**Comment by 0x1F9F1** [comment]
Yup, I broke it in f6a4080ff56cd2ccdaa3e5bbf16dc172ae838e95. Could you double-check this fixes it https://github.com/0x1F9F1/SDL/commit/dac492f4303483102f81fbc8c74770ea37b71d86?

It works "fine" on my machine, but I'm able to repro it if I fill the fill the allocations with random data. Perhaps some of the tests would benefit from a version of malloc which does this?

**Comment by madebr** [comment]
Yes, that fixes the error on my system too.

SDL has SDL_SetMemoryFunctions, that can override the allocation functions.
It's used by SDL_test for tracking leaks (enabled by `--trackmem`).
So perhaps an additional `--randommem` could be useful?

**Comment by slouken** [comment]
Yeah, that seems like a good idea.

**Comment by icculus** [comment]
I think we're good to go on this issue, so I'm closing it. Please let me know if there's something still pending, though!
