### ISSUE TITLE
left stick giving right stick input without movement with SDL2.dll, doing fine with Windows.Gaming.Input API (WinGamingInput.dll) cemu uses. also problem is gone when i start cemu first and open controller input and then yuzu if i start yuzu only problem persists

### ISSUE THREAD

**Issue by AAAthisisTRIPLEA** [libsdl-org/SDL#8168]
controller is a 3rd party switch pro bluetooth controller branded "daugee games JV800" (https://www.amazon.com/dp/B09QLZFXNY)

in cemu with win gaming input it works flawless. need to circle joycons one time after connecting controller and its calibrated. when not starting cemu and opening controller input, in yuzu (and other games) its never good, when moving the left stick there is inout of the right stick aswell (mostly moving camera)
there is NO physical movement of the right stick however

[temp. workaround]
if someone else has this problem try opening cemu controller input and move sticks clockwise, problem is gone afterwards in yuzu until controller disconnects from bluetooth or computer is restarted. this only fixes the problem temporary

**Comment by slouken** [comment]
Can you reproduce this with SDL testcontroller?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.

**Comment by bluenote73** [comment]
That's an end user who has to wait for your new version to drop and then be incorporated into the software he uses to re-report. Which depending on the software may be quite a long time.  I also reported this, and your attitude here tells me not to bother reporting anything to you ever again, just migrate off your software and encourage anything I'm using to do so as well.
This is a terrible practice and a waste of *everyone's* time including your own.

**Comment by icculus** [comment]
I get it, but the problem with this type of bug is that it happens in someone else's software with specific controller hardware we don't have.

Often we can only hope that the bug is being reported by a programmer that can give us more insight by using a debugger on their machine. It's usually reasonable odds that those types will wander through here.

But without that, we all end up stuck. Often times these are hardware or driver problems, too. But we don't know and don't have any way to explore it from here.

**Comment by bluenote73** [comment]
There's no indication from the other dupes that were closed that this is limited to only one specific piece of hardware.

**Comment by slouken** [comment]
Unfortunately, no SDL developer has been able to reproduce the problem, and nobody else who has reported it has debugged it to provide more information about what's happening.

@bluenote73, I can walk you through the process if you're willing to debug the issue. Let me know and I'll be happy to reopen this bug.

**Comment by bluenote73** [comment]
If you have some sort of reference client for me to use that logs or something, happy to help. If you mean install a development environment and go from there, then probably not

**Comment by slouken** [comment]
The testcontroller test program in the main SDL repo is a good test. However, if you're able to reproduce it, we'll need to debug what's happening, which will involve installing Visual Studio and spending time over Zoom. I'm willing to do that if you are, and you can send me e-mail at slouken@libsdl.org to coordinate.
