### ISSUE TITLE
tests seem to ignore SDL_VIDEODRIVER

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#8169]
`./testdraw` runs in wayland.
`SDL_VIDEODRIVER=x11 ./testdraw` also runs in wayland.
This is the latest sdl git.

**Comment by madebr** [comment]
SDL3 uses `SDL_VIDEO_DRIVER`.

**Comment by stsp** [comment]
Thank you, that works.
Why such an incompatible changes...
