### ISSUE TITLE
SDL_SetWindowIcon ignored under wayland

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#8170]
`./testdraw --icon icon.bmp` doesn't
set any icon, because it seems the
needed call-back is not implemented
in a wayland back-end.
`SDL_VIDEODRIVER=x11 ./testdraw --icon icon.bmp`
does the same because SDL_VIDEODRIVER=x11
is somehow ignored.

**Comment by stsp** [comment]
`SDL_VIDEO_DRIVER=x11 ./testdraw --icon icon.bmp`
works as expected.

**Comment by Kontrabant** [comment]
Wayland doesn’t allow for setting the app icon programmatically. If you want an icon to appear, the application must be accompanied by an associated .desktop file that points to an icon image file. Even then, if and how it is displayed is up to the compositor. 

Will add this caveat to the README-Wayland.md file.

**Comment by stsp** [comment]
Maybe its just not implemented yet
in wayland? A temporary problem?

**Comment by Kontrabant** [comment]
> Maybe its just not implemented yet in wayland? A temporary problem?

As far as I know, there are no upstream plans to implement support for programmatically setting application icons under Wayland.

**Comment by stsp** [comment]
At least you need to return failure from
that function in this case.

**Comment by Kontrabant** [comment]
It does currently return an unsupported error:

https://github.com/libsdl-org/SDL/blob/8387fae698745969ce366c4de9bcc1b4a364a7dd/src/video/SDL_video.c#L2356-L2358

**Comment by stsp** [comment]
Wow, I thought its void...
Thanks.

**Comment by stsp** [comment]
> If you want an icon to appear, the application must be accompanied by an associated
> .desktop file that points to an icon image file.

I tried that and it doesn't work.
The desktop file is already there,
but it only shows an icon when
you browse the apps in a gnome-shell.
But when the app is running, the
icon doesn't appear.
A quick googling reveals you need
to set "app_id" for a running up to
match it with a desktop file.
SDL obviously doesn't seem to do
that, and I can't find a precise
description on how exactly is to
do that.

**Comment by stsp** [comment]
I figured this can be done with
setting the SDL_VIDEO_X11_WMCLASS
env var (which works even for wayland),
but its far from being convenient.
I think this should be done through
some SDL API.
