### ISSUE TITLE
x11: SDL_SetWindowIcon produces garbled image

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#8171]
Using the non-standard icon size,
SDL_SetWindowIcon() produces bad
results:
![Снимок экрана от 2023-08-28 11-56-22](https://github.com/libsdl-org/SDL/assets/3295627/1fcc0040-19e2-47da-88d6-27ab1015d92e)

You can see the garbage under the icon image.

Icon is also attached:
[a.bmp.gz](https://github.com/libsdl-org/SDL/files/12451219/a.bmp.gz)

How to reproduce:
`SDL_VIDEO_DRIVER=x11 ./testdraw --icon a.bmp`

**Comment by madebr** [comment]
I also reproduce this, I tried using a non-square icon with glfw3 and it reproduces too over there.
Looks like both of us are using GNOME 3/4.
So I wonder whether this is an issue with GNOME (mutter) or the protocol expecting a square icon.
Does this also happen with different compositors?

Standalone reproducer:
```c
#include <SDL3/SDL.h>

int main(int argc, char *argv[]) {
    SDL_Window *window;
    SDL_Renderer *renderer;
    SDL_Surface *surface;
    SDL_Init(SDL_INIT_VIDEO);

#define WIDTH 64
#define HEIGHT 40 /* non-square icon */

    SDL_CreateWindowAndRenderer(640, 480, 0, &window, &renderer);
    surface = SDL_CreateSurface(WIDTH, HEIGHT, SDL_PIXELFORMAT_RGBA32);
    SDL_FillSurfaceRect(surface, NULL, SDL_MapRGB(surface->format, 255, 0, 0));
    SDL_SetWindowIcon(window, surface);
    SDL_DestroySurface(surface);

    while (1) {
        int quit = 0;
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_EVENT_QUIT) {
                quit = 1;
                break;
            }
        }
        if (quit) {
            break;
        }
        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
    }
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
}
```

**Comment by stsp** [comment]
> So I wonder whether this is an issue with GNOME (mutter) or the protocol
> expecting a square icon.

You seem to be right.
I used this reproducer:
```
# Firstly import Tkinter Module
from tkinter import *
from tkinter.ttk import *
import tkinter as tk
# Then create a program Tkinter window
program = Tk()
# Photoimage class is created
# And Image should be in the same folder where there is script saved
p1 = PhotoImage(file = './a.gif')
# Icon set for program window
program.iconphoto(False, p1)
# Button creation
b = Button(program, text = 'Press Me!')
b.pack(side = TOP)
program.title('iconphoto() method')
mainloop()
```

Run it with python3, previously
converting a.bmp to a.gif.
And it shows the problem too.
So where to report this then?

**Comment by stsp** [comment]
Thank you. :)
