### ISSUE TITLE
Possible CSD vs SSD when using SDL_VIDEODRIVER=wayland

### ISSUE THREAD

**Issue by infapi00** [libsdl-org/SDL#8173]
Recently a bug was fixed on Wayfire, where SDL were not working when using SDL_VIDEODRIVER=wayland

Quoting the explanation of the bug:

> The problem was that SDL says a hard 'I need SSD' but Wayfire does not take that into account and forces CSD.

And quoting the reason to create this issue:

> With the fix, SDL apps will work correctly, however, it may be worth reporting this to the SDL devs as well. SDL appears to have a code path for this which seemingly does not work .. Of course, I'm not sure how to trigger that path without having a bug in the compositor.

For full details, this is the issue created:

https://github.com/WayfireWM/wayfire/issues/1870

and this is the Wayfire fix (already merged):

https://github.com/WayfireWM/wayfire/pull/1871

**Comment by ammen99** [comment]
A bit of additional info: Wayfire used to force CSD even if the app has selected SSD via xdg-decoration (a bug which is now fixed). In SDL, the following function is called :https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandwindow.c#L833. It destroys the first xdg_toplevel, but does not create a new one.

**Comment by Kontrabant** [comment]
Managed to reproduce this. Switching from SSD to CSD at window creation time was causing the backend to recurse into the internal show/hide functions during the initial roundtrip, which caused some internal window state to get out of sync. SDL did have a bad code path in this case.

Working on it now.
