### ISSUE TITLE
SDL3 [iOS] [Android] finger touch screen coordinates only updated on dragging

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/SDL#8176]
Testing with `testwm` on SDL3 and `testwm2` on SDL2 in the iOS simulator.

On SDL2 when you touch on the screen (or rather in the simulator) you get updated screen  coordinates for
`SDL_GetMouseState` and `SDL_GetGlobalMouseState`.

On SDL3 the coordinates do not change on touch (and in our app Exult the touch event will happen on the old coordinates).
`SDL_GetMouseState` and `SDL_GetGlobalMouseState` do only change when you drag the finger across the screen (or rather the cursor across the simulator).

That puzzled me for quite a while on our SDL3 migration efforts before I thought to test with SDL tests.

Our Android port seems to have the same problem (only the app becomes unresponsive after a touch event).

**Comment by slouken** [comment]
Which test did you try, and what steps did you take to see the problem?

**Comment by slouken** [comment]
Fixed, thanks!
