### ISSUE TITLE
GitHub Action for Emscripten: don't use Release settings

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8180]
Unlike other targets, Emscripten does a _ton_ of optimization work at link time instead of compile time:

https://emscripten.org/docs/optimizing/Optimizing-Code.html#how-emscripten-optimizes

Which, in SDL's case, means each additional test app we build dramatically increases build time vs a Debug build, which is effectively running optimizers over the entirety of SDL's codebase for each little app.

It might be worth it to bump the Emscripten workflow file from Release to Debug, which is trivial to do (and on my laptop makes the builds more than 3x faster, fwiw).

Emscripten's docs note that you can also _link_ with `-O0`, even if you compiled with `-O3` to refuse the link-time optimizations, but I haven't tried forcing the link flags.

**Comment by madebr** [comment]
I see a 4x time decrease on my system, when going from `-O3` (release) to `<nothing>` (debug).
Adding an extra `-O0` does not make it go faster.

Let's make this change as the emscripten ci job is relatively heavy on ci.

**Comment by madebr** [comment]
This is applied in https://github.com/libsdl-org/SDL/commit/f002f7d12e0a29547e675245143a1af5edc5c7ff

[Build times go from ~16m to ~6m.](https://github.com/libsdl-org/SDL/actions/workflows/emscripten.yml)
