### ISSUE TITLE
libdecor needs its GTK+ backend merged to main

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8185]
This is really a libdecor issue and not an SDL issue, but as far as I'm concerned it's a showstopper for SDL3 on Wayland to be most likely to look like this:

![image](https://github.com/libsdl-org/SDL/assets/673562/8ae23741-c70d-435f-936f-1ba81e0546b9)

So let's keep this issue open to figure out a solution: either default to XWayland, or get some enthusiasm going in libdecor to merge the GTK+ backend.

On environments that support server-side-decorations, like KDE, libdecor uses them, so it really is the GTK+ backend we need most urgently to cover almost everything else.

**Comment by icculus** [comment]
(Also if this has already been resolved in libdecor since last I checked, I'd love to just close this issue immediately.)

**Comment by Kontrabant** [comment]
Libdecor merged it some time ago, so yes, it’s just a matter of it percolating downstream. 

The current master is needed to pass through occlusion events as well.

**Comment by icculus** [comment]
@Conan-Kudo I don't know if this is your department, but can you ask around in Fedora to see if this is solid?

**Comment by Conan-Kudo** [comment]
The [libdecor project moved to the FreeDesktop GitLab some time ago](https://gitlab.freedesktop.org/libdecor/libdecor). The current code there has a gtk backend merged. At this point, @jadahl just needs to tag a release and ship it to Fedora.

**Comment by woxels** [comment]
Hey we have an issue at the moment where not only do we not get Window Decorations on Wayland using SDL2 but also WarpMouse is non-functional.

What is the deal with wayland? I don't think even GLFW will work on both Wayland and Gnome currently.

I am not an expert so if anyone could explain the situation somewhat or point me in the right direction to learn more I would appreciate that.

**Comment by flibitijibibo** [comment]
0.2.0 was tagged a few hours ago: https://gitlab.freedesktop.org/libdecor/libdecor/-/releases/0.2.0

**Comment by icculus** [comment]
Tweeted so package maintainers can notice the new version: https://twitter.com/icculus/status/1706327752729559425

**Comment by Kontrabant** [comment]
The new version was tagged as 0.2.0 instead of 0.1.2, so the build scripts and #ifdef checks have been updated to check for this version for new functionality.
