### ISSUE TITLE
SDL3 Linux multi-monitor window flicker/jumps between monitors with fullscreen-desktop and borderless window set

### ISSUE THREAD

**Issue by danginsburg** [libsdl-org/SDL#8186]
After shipping the latest Dota 2 update, users on Linux started encountering an issue with multi-monitor systems where the window constantly flickers back and forth between monitors: https://github.com/ValveSoftware/Dota-2/issues/2435

I was able to reproduce this with one of the SDL3 test apps.  I built SDL3 from fd7cd91dc9c6c5c3882b69793642b7915184535b and am running it on Ubuntu 24.0.2 with NVIDIA GTX 1070 535.104.05 with two monitors both set to the same resolution (1920x1080).  If I run `./testviewport  --noframe --fullscreen-desktop` then the window will flicker and the mouse jumps between the left and right monitor, pretty much the same behavior as I'm seeing in Dota.  If I drop `--noframe` then the bug goes away.  I also found that in Dota 2 if I remove the SDL_WINDOW_BORDERLESS SDL window creation flags that I am similarly able to workaround it in Dota 2.

**Comment by danginsburg** [comment]
I've bisected it to this commit a6d8cdf18605645b3201cee32443afb0d20a1eb4

**Comment by danginsburg** [comment]
A possible fix is to remove the call to `SetWindowBordered` in `X11_CreateWindow` when `SDL_WINDOW_BORDERLESS` is specified.  I've confirmed this fixes the issue, but I can't say I understand why.

**Comment by slouken** [comment]
Can you create a PR for that? I don't have a multi-monitor Linux setup at the moment, so I can't test it.

**Comment by mdumitrean** [comment]
I'm still experiencing this in DOTA w/ Ubuntu 22.04.  How do we resolve this?
