### ISSUE TITLE
iOS: fullscreen window continuously changes orientation

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#8201]
If I edit testspriteminimal.c (or testrendercopyex, etc) to create a fullscreen window, on iOS it continuously changes orientation of the window between landscape and fullscreen. I discovered this while testing #8200 in the iOS Simulator.

I haven't debugged enough to understand what's happening.

**Comment by slouken** [comment]
I just tested this here, and it's working fine with the latest code. Are you still able to reproduce this?

**Comment by slouken** [comment]
Actually, I'm seeing this with SDL3 code now, digging in...
