### ISSUE TITLE
[Feature] Wii U GamePad on Linux

### ISSUE THREAD

**Issue by Sebio1980** [libsdl-org/SDL#8202]
Hello,
Are there plans to support the Wii-u gamepad in the near future?
[Wii_U_GamePad](https://en.wikipedia.org/wiki/Wii_U_GamePad)

![image](https://github.com/libsdl-org/SDL/assets/53249046/c3c910d8-d704-42a3-8849-b5841212d42a)

Thank a lot

**Comment by slouken** [comment]
I don't have a Wii U GamePad, but you're welcome to submit a PR to add support for yours.

**Comment by icculus** [comment]
So this thing doesn't talk over HID at all, afaik, it uses WiFi to talk to the console and a non-standard protocol.

Supporting it would be a lot of work, I suspect.

**Comment by icculus** [comment]
(I would guess it would be easier and better to have a daemon that talks to the device and exposes some sort of standard /dev/input interface that SDL can talk to without modifications.)

**Comment by Sebio1980** [comment]
i found this documentation [libdrc](https://docs.google.com/presentation/d/126fk9mO5jROMfuw-2ASDv7-YH_A0LZO0Phxedh9deiE/preview?pli=1#slide=id.p)
and the soft for windows and macos [UsendMii](https://wiiubrew.org/wiki/UsendMii)
and this article [How To Use Nintendo's Wii U Gamepad With Your Computer](https://www.slashgear.com/1131478/upcoming-nintendo-switch-exclusives-we-cant-wait-to-play-in-2023/)

**Comment by icculus** [comment]
Yeah, I think we won't be able to do this cleanly in SDL itself for several reasons. But we'll take a reasonable pull request to add support.
