### ISSUE TITLE
Set `SDL_bool` to be a `bool` in C++

### ISSUE THREAD

**Issue by Agamenon-sama** [libsdl-org/SDL#8203]
I am sorry if this is noobie suggestion but I noticed that functions that take an `SDL_bool` can't take C++ `bool`s unless it's casted like `(SDL_bool) myBool`.  Wouldn't it be more convenient to typedef `SDL_bool` to `bool` for C++ ?

It's seems `SDL_bool` is defined in `SDL_stdinc.h` as such:

```c++
#ifdef __CC_ARM
/* ARM's compiler throws warnings if we use an enum: like "SDL_bool x = a < b;" */
#define SDL_FALSE 0
#define SDL_TRUE 1
typedef int SDL_bool;
#else
typedef enum
{
    SDL_FALSE = 0,
    SDL_TRUE = 1
} SDL_bool;
#endif
```

It could maybe be changed to

```c++
#ifdef __cplusplus
#define SDL_FALSE false
#define SDL_TRUE true
typedef bool SDL_bool;
#elif defined(__CC_ARM)
/* ARM's compiler throws warnings if we use an enum: like "SDL_bool x = a < b;" */
#define SDL_FALSE 0
#define SDL_TRUE 1
typedef int SDL_bool;
#else
typedef enum
{
    SDL_FALSE = 0,
    SDL_TRUE = 1
} SDL_bool;
#endif
```

**Comment by slouken** [comment]
This is fixed in https://github.com/libsdl-org/SDL/commit/a76d8e39aa3c7e136eba58290880a7cbbc4f5faf, thanks!
