### ISSUE TITLE
Pandora Box 7 (RX Gamepad) not in gamecontrollerdb.txt

### ISSUE THREAD

**Issue by Oberworld** [libsdl-org/SDL#8217]
First of all, sorry for my poor english. 
I have a pandora box 7, when I connect it to windows, some programs doesn't detect it.
That programs uses the gamecontrollerdb.txt, but my device it's not in that DB, so it doesn't work. I have downloaded the SDL2 Gamepad tool and created a custom profile that works:

030000000d0f0000ad00000000000000,RX Gamepad,platform:Windows,a:b0,b:b4,x:b2,y:b1,back:b11,start:b9,leftshoulder:b3,rightshoulder:b6,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,

Maybe this can be useful for some other people and can be added to future updates of gamecontrollerdb.txt.

Thank you for your great work.
Regards.

**Comment by slouken** [comment]
Thanks, can you provide a link to the product so I can see what it looks like?

**Comment by Oberworld** [comment]
Sorry for the delay, here is a picture:

![pandora box 7](https://github.com/libsdl-org/SDL/assets/5934369/9cfe4ebd-6046-4f99-88d6-ec25c35f9cd9)


Regards.

**Comment by slouken** [comment]
Added, thanks!
