### ISSUE TITLE
kmsdrm no longer autodetected

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#8218]
Trying to run an sdl app under kms
console, I am getting a blinking cursor.
But using `SDL_VIDEODRIVER=kmsdrm`
makes the initialization to pass.
I didn't have to do that in the past.
I think wayland is tried to be used instead,
because with `SDL_VIDEODRIVER=wayland`
I am getting the same effect.

wayland is running on that machine but
not on that kms console. Maybe that
somehow tricks the detection logic.

**Comment by stsp** [comment]
2.28.2+dfsg-1 under ubuntu.

**Comment by stsp** [comment]
So the fix here is going to be to
just check the `WAYLAND_DISPLAY`
variable in `Wayland_CreateDevice()`.

**Comment by stsp** [comment]
So this?
```
index bd9b7d404..6d2828ca5 100644
--- a/src/video/wayland/SDL_waylandvideo.c
+++ b/src/video/wayland/SDL_waylandvideo.c
@@ -128,7 +128,7 @@ static SDL_VideoDevice *Wayland_CreateDevice(void)
     SDL_VideoData *data;
     struct wl_display *display;
 
-    if (!SDL_WAYLAND_LoadSymbols()) {
+    if (!SDL_WAYLAND_LoadSymbols() || !getenv("WAYLAND_DISPLAY")) {
         return NULL;
     }
 
```

**Comment by sezero** [comment]
@Kontrabant ?

**Comment by Kontrabant** [comment]
The tricky part is, the spec doesn't require that `WAYLAND_DISPLAY` be set, as it's really only needed if a non-default socket is being used. Most environments do set it regardless, but it's not guaranteed and there are cases where this can fail.

**Comment by stsp** [comment]
What about `$XDG_SESSION_TYPE`?

**Comment by stsp** [comment]
Thank you.
Please back-port to sdl2/release branches,
if possible.
