### ISSUE TITLE
Removed gamepad things in README-migration still listed as renamed

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8220]
Several gamepad binding things in README-migration.md are still listed as being renamed, but they have since been removed.

A possibly incomplete list:

```
* SDL_GameControllerBindType => SDL_GamepadBindingType
...
* SDL_GameControllerButtonBind => SDL_GamepadBinding
...
* SDL_GameControllerGetBindForAxis() => SDL_GetGamepadBindForAxis()
* SDL_GameControllerGetBindForButton() => SDL_GetGamepadBindForButton()

```

Also, [someone is asking on the forums](https://discourse.libsdl.org/t/sdl-3-0/40374/57) what to do if you were using these removed functions; there is this text in README-migration.md ...

```
The gamepad binding structure has been removed in favor of exchanging bindings in text format.
```

...but it might be helpful to explain how to use the new thing in a little more detail, either in the doc or in reply to the forum post.

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/859dc14addcce248ff6085c7f842ebb3a2001eff
