### ISSUE TITLE
SDL_FORCE_STATIC_VCRT

### ISSUE THREAD

**Issue by jarroddavis68** [libsdl-org/SDL#8221]
Setting this to ON, still seems to default to /MD for me. Any ideas?

**Comment by madebr** [comment]
Fixed by https://github.com/libsdl-org/SDL/commit/22d81fb3e97cc5ee01ef1375fdf9d437e16f17c3
I also backported it.

I tested this with:
```cmd
cmake -S .. -DSDL_FORCE_STATIC_VCRT=ON
cmake --open .
```
and checked whether `-MT` or `-MTd` was present in the compile command line of the property page of SDL3-shared.
