### ISSUE TITLE
Windows: Exclusive fullscreen and high DPI causes window to flicker

### ISSUE THREAD

**Issue by danginsburg** [libsdl-org/SDL#8222]
I have SDL built to a2e17852d9d8e3b80fca64dc2ce42da41a21e707 and am seeing a problem in exclusive fullscreen.  The repro steps are:

1. Under Windows Display Settings, set "Change the size of text, apps, and other items" to a value of 125% or greater.
2. Run `testviewport.exe --fullscreen`
3. Note the window flickering in and out of exclusive fullscreen mode

We're hitting this problem on Source 2 as well.

**Comment by danginsburg** [comment]
Note that setting `SDL_SetHint( SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "0" );` in testviewport.c works around this particular issue, but I am also doing that in Source 2 and there if my DPI is 200% or greater I get the same behavior as if minimize-on-focus-loss is not set (as soon as it goes exclusive fullscreen, it minimizes and switches out of it - but it only happens at DPI > 200%!).

**Comment by slouken** [comment]
Does it happen with testsprite as well?
Is this specific to multi-monitor or single-monitor setup?

**Comment by danginsburg** [comment]
> Does it happen with testsprite as well?

Yes.

> Is this specific to multi-monitor or single-monitor setup?

Happens either way.  I repro'd it on a setup with 2560x1440 and 1920x1080 monitor setting the first display to 125%.  I also repro'd it with just one monitor 1920x1080 setting to 125%.

**Comment by slouken** [comment]
I'm not able to reproduce this here on Windows 11. If I run testsprite --fullscreen I get a 640x480 borderless window in the upper left corner of the screen. If I run testwm and select the specific fullscreen mode I want and then press Ctrl+Enter, I get an exclusive fullscreen mode with no flickering.

Are you able to add logging to find out what's going on?

**Comment by danginsburg** [comment]
Closing this in favor of #8237 which better describes the problem.
