### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by MapleGlazedCrow** [libsdl-org/SDL#8223]
Hi, I either need help installing SDL2 for visual studio or I need a different zip, because the one I downloaded only contains "SDL2.dll" and a txt, but the tutos I'm seeing all have multiple folders, like "include" or "x64" or stuff like that. I can't find anything, be it doc, tutorial, or ticket that says what to do with the ".dll". _**Help**_.

_edit_: Should I just use the nuget?

**Comment by icculus** [comment]
Get the download with "devel" in the name, not the "win32" one at the top:

https://github.com/libsdl-org/SDL/releases/tag/release-2.28.3


In this case you probably specifically want:

https://github.com/libsdl-org/SDL/releases/download/release-2.28.3/SDL2-devel-2.28.3-VC.zip

**Comment by MapleGlazedCrow** [comment]
Oh wow, thanks. It indeed does have everything else.
