### ISSUE TITLE
UEFI as platform

### ISSUE THREAD

**Issue by Torinde** [libsdl-org/SDL#8232]
Provide SDL for UEFI, https://github.com/Openwide-Ingenierie/uefi-musl

One use-case is to provide bare metal DOS. FreeDOS [doesn't have UEFI](http://wiki.freedos.org/wiki/index.php/Releases/1.3#Support_for_UEFI.3F) support, while many computers now ship without UEFI Compatibility Support Module.

Discussion about potential solutions: https://github.com/dosemu2/dosemu2/discussions/1800#discussioncomment-6960239

If SDL provides support for UEFI, then [DOSBox-X](https://github.com/joncampbell123/dosbox-x) can run there.

**Comment by icculus** [comment]
I don't think this is something we'd take on, but if this can coexist in the source tree as just another platform, we'd likely accept a pull request if someone else took on the work.
