### ISSUE TITLE
[SDL2] using SDL_SetHint with SDL_AUDIODRIVER doesn't look changing the audio driver selection

### ISSUE THREAD

**Issue by Raffaello** [libsdl-org/SDL#8233]
SDL version 2.0.11
OS: Windows 11

----

using `SDLSetHint` and setting the `SDL_AUDIODRIVER` with, for e.g. `SDL_GetAudioDriver(1)` it will still use the default `0` one, basically it is ignored and it looks there is no way to change the audio driver.

Is there any simpler way/workaround to select the audio driver to use instead of setting an ENV variable that looks like also ignored?

Would it be possible to have a simpler API to select Audio driver in SDL3?

**Comment by icculus** [comment]
SDL_AUDIODRIVER wants a name, not a number. "directsound" or "wasapi", etc.

**Comment by Raffaello** [comment]
> SDL_AUDIODRIVER wants a name, not a number. "directsound" or "wasapi", etc.

yes, So if using directly the result from `SDL_GetAudioDriver(1)` considering  `NumAudioDrivers >=2`, should work, but in my specific case is alwasys `wasapi` (index 0) and `directsound` (index 1) is not selected

----

even a more straightforward small example:

```
SDL_SetHint("SDL_AUDIODRIVER", "directsound");
m_device_id = SDL_OpenAudioDevice(nullptr, 0, &desired, &obtained, 0);
const char* sdlDriverName = SDL_GetCurrentAudioDriver();
cout << std::format("Using SDL Audio Driver '{}'", sdlDriverName);
```

results in the output: `wasapi`:
```
Using SDL Audio Driver 'wasapi'
```

**Comment by madebr** [comment]
Have you set the hint before `SDL_Init`?

**Comment by Raffaello** [comment]
> SDL_SetHint("SDL_AUDIODRIVER", "directsound");

that's it! :)
it was because i called `SDL_SetHint` after `SDL_init`.
It is working if using `SDL_SetHint` 

Thanks.

May i suggest to add a  note on the Remarks section in the documentation of `SDL_SetHint` please?

**Comment by slouken** [comment]
I'll open a separate task to go through the hints and improve documentation. Thanks!
