### ISSUE TITLE
Pulseaudio not working in SDL3

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8235]
I'm trying pulseaudio with the new SDL audio system and I'm not getting any audio playing. It appears to be hung up in the pulseaudio main loop wait function.

I'm testing on Ubuntu 22.04, and the ALSA driver works fine.

**Comment by slouken** [comment]
SDL2 works fine, FWIW.

**Comment by slouken** [comment]
I tried it again today and I'm not seeing any issue. I'll keep an eye out for this again and send you all the thread states if I see it again.

**Comment by icculus** [comment]
We still have a pending bug about race conditions, perhaps you got bit by it? I'll try to focus on that shortly.
