### ISSUE TITLE
Fails to compile for emscripten with memory64

### ISSUE THREAD

**Issue by jspanchu** [libsdl-org/SDL#8241]
When I use `-sMEMORY64=1` flag, SDL2 fails to compile with error:
```
/emsdk/emscripten/main/cache/ports/sdl2/SDL-release-2.24.2/src/SDL_assert.c:263:25: error: cast to 'char *' from smaller integer type 'int' [-Werror,-Wint-to-pointer-cast]
  263 |             char *buf = (char *) EM_ASM_INT({
      |                         ^~~~~~~~~~~~~~~~~~~~~
  264 |                 var str =
      |                 ~~~~~~~~~
  265 |                     UTF8ToString($0) + '\n\n' +
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  266 |                     'Abort/Retry/Ignore/AlwaysIgnore? [ariA] :';
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  267 |                 var reply = window.prompt(str, "i");
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  268 |                 if (reply === null) {
      |                 ~~~~~~~~~~~~~~~~~~~~~
  269 |                     reply = "i";
      |                     ~~~~~~~~~~~~
  270 |                 }
      |                 ~
  271 |                 return allocate(intArrayFromString(reply), 'i8', ALLOC_NORMAL);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  272 |             }, message);
      |             ~~~~~~~~~~~
1 error generated.
```

I suspect it should use `EM_ASM_PTR` instead. There are other files that need to proxy pointers back to main thread.

**Comment by sbc100** [comment]
I'm looking at a fix for this on the emscripten side, then I will send a patch here.

**Comment by jspanchu** [comment]
The fix is in https://github.com/jspanchu/SDL/commit/1c87595214239dd65bfe9c27f53029192dd02866. 

Before making a PR, wanted to check if I should bump the emsdk version in the workflow - https://github.com/libsdl-org/SDL/blob/main/.github/workflows/emscripten.yml#L16?

The issue now is that `MAIN_THREAD_EM_ASM_PTR` was commited after `3.1.46` was tagged, I guess my only option is to wait for 3.1.47?

**Comment by sbc100** [comment]
Yes for `MAIN_THREAD_EM_ASM_PTR` we will need to wait for 3.1.47

**Comment by icculus** [comment]
Ok, @jspanchu's patch is in revision control: 953b55dd6da1dd9fb937f3c67a18c5cab2988599

My patches to make it work with existing emsdk releases: 5008521538ffe7931ecd0d11c4a5e75a05f54b5b


SDL2 branch: 330d420afc226257a63ba8607ead606699900525 and 60070d0b3d3c55d608af58d6a74f9fa540dfb3b0
release-2.28.x branch: 536f625bdec2752d1785b9230bbc867295277a74 and b93a8a86abcc772f4200ca610d76eb6283afd14c

**Comment by sbc100** [comment]
Great!
