### ISSUE TITLE
Enhancement: Retrieve Correct SDL_GameControllerGetType with Steam Input

### ISSUE THREAD

**Issue by echeese** [libsdl-org/SDL#8242]
Issue:
When I run my SDL application through Steam with Steam Input enabled, all controllers are identified with VID: 28de and PID: 11ff. Consequently, the SDL_GameControllerGetType function returns SDL_CONTROLLER_TYPE_UNKNOWN. This behavior hinders the ability to accurately determine which controller glyphs should be displayed in-game.

Desired Outcome:
I'm looking for a way to retrieve the correct controller type, even when Steam Input is enabled. This would provide a more seamless experience for new and existing SDL games, allowing them to work out of the box without the need for additional configurations.

Suggestion:
While Steam offers an API for detecting controller types, I'm hoping for a solution from SDL that doesn't require any application code changes, and without direct integration with Steam, as I feel like this should work even for non-Steam games. Ideally, an internal workaround or method that can recognize and correctly classify controllers when Steam Input is active would be perfect.

**Comment by flibitijibibo** [comment]
Related: #6068

**Comment by slouken** [comment]
What platform is this on?

**Comment by echeese** [comment]
I've only been developing non Windows, but it's likely to be  an issue on every Steam platform.

**Comment by slouken** [comment]
I don't know of any way to pass any metadata from Steam through the uinput device, but suggestions and pull requests are welcome!

**Comment by slouken** [comment]
This is implemented in SDL 2.30 and the latest version of Steam.
