### ISSUE TITLE
SDL_main: Remove SDL2 compatibility macros?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8245]
Since we're breaking ABI, do we want to dump these?

```c
#ifdef __WINRT__

/* for compatibility with SDL2's function of this name */
#define SDL_WinRTRunApp(MAIN_FUNC, RESERVED)  SDL_RunApp(0, NULL, MAIN_FUNC, RESERVED)

#endif /* __WINRT__ */

#ifdef __IOS__

/* for compatibility with SDL2's function of this name */
#define SDL_UIKitRunApp(ARGC, ARGV, MAIN_FUNC)  SDL_RunApp(ARGC, ARGV, MAIN_FUNC, NULL)

#endif /* __IOS__ */

#ifdef __GDK__

/* for compatibility with SDL2's function of this name */
#define SDL_GDKRunApp(MAIN_FUNC, RESERVED)  SDL_RunApp(0, NULL, MAIN_FUNC, RESERVED)
```

Also, is there a compiler that can't tolerate indented preprocessor commands? SDL_main.h necessarily has a lot of them, but it would be nice if it were more readable...

```c
#ifndef SDL_MAIN_HANDLED
#ifdef __WIN32__
#define SDL_MAIN_AVAILABLE

#elif defined(__WINRT__)
#define SDL_MAIN_NEEDED

#elif defined(__GDK__)
```

vs

```c
#ifndef SDL_MAIN_HANDLED
    #ifdef __WIN32__
        #define SDL_MAIN_AVAILABLE

    #elif defined(__WINRT__)
        #define SDL_MAIN_NEEDED

    #elif defined(__GDK__)
```

**Comment by icculus** [comment]
(CC @DanielGibson)

**Comment by DanielGibson** [comment]
I've never heard anything about indented preprocessor commands not being allowed, should be fine I guess - only possible drawback is that the lines might become pretty long, especially if you also indent the regular C code behind several levels of `#if`

I have no strong feelings about the compatibility macros, feel free to remove them :)
