### ISSUE TITLE
SDL_JoystickCurrentPowerLevel is always -1 on Nintendo Switch Pro Controller

### ISSUE THREAD

**Issue by z0rti** [libsdl-org/SDL#8252]
Using:
```SDL_JoystickPowerLevel joypow=SDL_JoystickCurrentPowerLevel(joy);```
(at start, but also in the event loop) to get the power level of my 'Nintendo Switch Pro Controller' (EasySMX clone)
but it is always -1 (SDL_JOYSTICK_POWER_UNKNOWN)
event.jbattery.level is 1 though, but not sure what that means
Tested with SDL 2.29.0 (SDL_JoystickCurrentPowerLevel) and 3.0.0 (SDL_GetJoystickPowerLevel)
upower works:
```
$ upower -i $(upower -e | grep nintendo)
[...]
    battery-level:       high
    percentage:          70% (should be ignored)
[...]
```

**Comment by slouken** [comment]
What does testcontroller from the SDL test programs show?

**Comment by slouken** [comment]
try:
```
cd SDL; mkdir build; cd build; cmake .. -DSDL_TESTS=ON
```

**Comment by z0rti** [comment]
there it is :-)
all keys working, accelerometer+gyro too, no mention of battery
```
$ ./testcontroller
INFO: Opened gamepad Nintendo Switch Pro Controller, /dev/input/event6
INFO: Rumble supported
INFO: Enabling accelerometer at 0.00 Hz
INFO: Enabling gyro at 0.00 Hz
```

**Comment by slouken** [comment]
It'll show a battery icon in the upper right, if there's any battery information available.

**Comment by slouken** [comment]
Can you grab the latest SDL code? I added some more logging information that would be helpful.

**Comment by slouken** [comment]
Ah, okay, what's happening is that it's using the Linux joystick driver, which doesn't have any battery query support.

**Comment by slouken** [comment]
If you enable the HIDAPI driver, it'll be able to read the battery directly from the controller, but you may need to add a udev rule to enable read/write permission to the device.

**Comment by z0rti** [comment]
I'm on ubuntu focal, so i did ```apt install libhidapi-hidraw0```
Then i put SDL/src/hidapi/udev/69-hid.rules into /etc/udev/rules.d/
changed the line to ```KERNEL=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="2009", TAG+="uaccess"```
then ```sudo udevadm control --reload-rules && sudo udevadm trigger```
and ```systemctl restart bluetoothd```
connected the controller, started testcontroller, still no battery.
But i'm not sure if it uses hidraw now (probably not)
syslog:
```
Nov  8 23:08:24 focal bluetoothd[77422]: Can't get HIDP connection info                                                                                         
Nov  8 23:08:26 focal kernel: [5209835.404316] input: Pro Controller as /devices/pci0000:00/0000:00:1d.0/usb6/6-2/6-2:1.0/bluetooth/hci0/hci0:71/0005:057E:2006.
2BDB/input/input12645

```
What needs to be in the syslog? And Mapping line?

**Comment by slouken** [comment]
The mapping will have 68 near the end of the GUID if it's using HIDAPI.

**Comment by z0rti** [comment]
Got it!
The udev rule must be 
```KERNEL=="hidraw*", KERNELS=="*057E:2006*", TAG+="uaccess"```
or it would not give the correct permissions to /dev/hidraw
it didn't work with the example line (not even 2006)
```ATTRS{idVendor}=="057e", ATTRS{idProduct}=="2009"```
probably because it's connected via bluetooth?

```
$ ./testcontroller
INFO: Opened gamepad Nintendo Switch Pro Controller, /dev/hidraw4
INFO: Rumble supported
INFO: Enabling accelerometer at 200.00 Hz
INFO: Enabling gyro at 200.00 Hz
INFO: Mapping: 050056fb7e0500000920000000006803,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,misc1:b15,crc:fb56,platform:Linux,
```
It outputs /dev/hidraw4 instead of /dev/input/event6 now and shows different Hz too.
It shows the battery now in the GUI but SDL_GetJoystickPowerLevel is still -1
```
         SDL_JoystickID instance_id = joysticks[stick];                                                                                                         
         const char *name = SDL_GetJoystickInstanceName(instance_id);                                                                                           
         const char *path = SDL_GetJoystickInstancePath(instance_id);                                                                                           
                                                                                                                                                                
         SDL_Log("Joystick %" SDL_PRIu32 ": %s%s%s VID 0x%.4x, PID 0x%.4x\n",                                                                                   
                 instance_id, name ? name : "Unknown", path ? ", " : "", path ? path : ""                                                                       
                 , SDL_GetJoystickInstanceVendor(instance_id)                                                                                                   
                 , SDL_GetJoystickInstanceProduct(instance_id));

         SDL_Joystick *joy = SDL_OpenJoystick(instance_id);                                                                                                     
         SDL_JoystickPowerLevel joypow=SDL_GetJoystickPowerLevel(joy);                                                                                          
         SDL_Log("Joystick[%d] Power[%d]", instance_id, joypow);                                                                                                
 
```
```
INFO: Joystick 1: Nintendo Switch Pro Controller, /dev/hidraw4 VID 0x057e, PID 0x2009
INFO: Joystick[1] Power[-1]

```
(the PID seems not to be correct, maybe because it's a clone?)

**Comment by slouken** [comment]
Can you see if 09d1e9def fixes your issue?

**Comment by slouken** [comment]
This will only work in SDL3, FYI.

**Comment by z0rti** [comment]
Nope, am i doing it wrong?
```
INFO: compiled    with SDL version 3.0.0
INFO:  linking against SDL version 3.0.0
INFO: Joystick 1: Nintendo Switch Pro Controller, /dev/hidraw4 VID 0x057e, PID 0x2009
INFO: Joystick[1] Power[-1]
INFO:  Gamepad[1] Power[-1]
```
[joypower_sdl3.c.gz](https://github.com/libsdl-org/SDL/files/13326432/joypower_sdl3.c.gz)

**Comment by slouken** [comment]
Just as a sanity check, you have it plugged in wired, right?

**Comment by slouken** [comment]
And you're running the very latest SDL code? (https://github.com/libsdl-org/SDL/commit/843873626c88c8cc4a9d23e01beb6512f5978dee as of this writing)

**Comment by z0rti** [comment]
No, not wired, Bluetooth, sorry i should have mentioned, (is there a function to show if BT or WIRED?)
Yes pulled the latest SDL code.

It seems to work in an event loop though:
```
INFO: compiled    with SDL version 3.0.0
INFO:  linking against SDL version 3.0.0
INFO: Joystick 3: Nintendo Switch Pro Controller, /dev/hidraw4 VID 0x057e, PID 0x2009
INFO: Joystick[3] Power[-1]
INFO:  Gamepad[3] Power[-1]
INFO: SDL_EVENT_JOYSTICK_BATTERY_UPDATED: event.jbattery.level[2]
INFO: SDL_EVENT_KEY_DOWN: event.jbattery.level[1]
INFO:  Gamepad[3] Power[2]
INFO: Quit!
INFO:  Gamepad[3] Power[2]
```
'2' seems to be the correct value
event.jbattery.level is only 2 if SDL_EVENT_JOYSTICK_BATTERY_UPDATED not with SDLK_b
[joypower_sdl3-v2.c.gz](https://github.com/libsdl-org/SDL/files/13326476/joypower_sdl3-v2.c.gz)

**Comment by slouken** [comment]
Ohhhhh, yes, when your first open the controller we don’t know what the battery status is yet. It’ll be updated when we get an input report from the controller. Your application should be able to handle an unknown status.
