### ISSUE TITLE
Could we get a new SDL2 release/tag?

### ISSUE THREAD

**Issue by sbc100** [libsdl-org/SDL#8253]
I'm looking to upgrade the emscripten port to include 042243471.

It looks like that last release was 2.28.0 back in ffa78e6bead23e2ba3adf8ec2367ff2218d4343c, and there are have been 148 changes on the SDL2 branch since then.

**Comment by slime73** [comment]
There have been 3 patches for 2.28.x released since 2.28.0, the most recent one was the beginning of this month: https://github.com/libsdl-org/SDL/releases

**Comment by sbc100** [comment]
Ah.. I see. Do you know why my change from back in July that exists on the SDL2 branch doesn't seems to be included in the `release-2.28.3` tag.   Shouldn't all the `release-2.X` tags exist on the `SDL2` branch, or am I misunderstanding the branch structure?

**Comment by sbc100** [comment]
Do I need to cherry-pick my change from the `SDL2` branch to the `release-2.28.x` branch?  Or perhaps I should be asking for a 2.29 release to include all the latest SDL2 changes?

**Comment by slouken** [comment]
No, we only merge low risk or high importance changes for patch releases. Since I hadn't heard whether this was risky or not, I left it in the SDL2 branch. I'll cherry-pick it over for the next patch release, which is typically at the start of each month.

**Comment by slouken** [comment]
This is done in 7d80e2088

**Comment by sbc100** [comment]
Thanks!

**Comment by slouken** [comment]
You're welcome! :)
