### ISSUE TITLE
Make it Simple to start a new SDL project

### ISSUE THREAD

**Issue by aganm** [libsdl-org/SDL#8254]
You know how when you start using SDL in a new project, you make a repo and then you start configuring everything to make this work? This configuration step can be very complicated and so far from Simple.

To make it simple to start a new project in SDL, I propose that this sample project be added into the SDL repo so that people can copy paste it to bootstrap their new git repos:

https://github.com/Ravbug/sdl3-sample

This sample has CI setup, CMake setup, Gradle setup, all the good stuff! Such that you can copy the sample folder into your own repo and get started right away, easily, and simply.

The SDL repo already has a android-project folder. It could be replaced by the sample project linked above because this sample project also contains configuration for android, and everything else as well.

**Comment by icculus** [comment]
I threw together a simple thing here:

https://github.com/icculus/SDL_helloworld

If this is useful, we can transfer it to the libsdl-org organization. Also, feedback is welcome. This is only Mac/Linux/Windows right now, but I want to keep it _small_.

**Comment by madebr** [comment]
2 remarks for the cmake:
- link to `SDL3::SDL3` instead of the explicit `SDL3::SDL3-shared`: the latter target is not available for e.g. emscripten. By default `SDL3::SDL3` aliases to `SDL3::SDL3-shared`.
- do `set_property(TARGET sdl-helloworld PROPERTY WIN32_EXECUTABLE TRUE)` unconditionally. CMake ignores unknown properties, or properties that don't apply to the current target. Also, `WINDOWS` does not exist (it's a SDL'ism): use `WIN32` instead.

**Comment by icculus** [comment]
Fixed, thanks!

**Comment by madebr** [comment]
Another little thing: `SDL3::Headers` is not needed. It is implicitly added when linking to `SDL3::SDL3`.
(I created the `SDL3::Headers` target for sdl2-compat such that we no longer have to fiddle with CMake variables)

**Comment by aganm** [comment]
Oh, I misunderstood the android-project folder. It's required to build SDL on android isn't it?


> If this is useful, we can transfer it to the libsdl-org organization. Also, feedback is welcome. This is only Mac/Linux/Windows right now, but I want to keep it _small_.

I do think this would be useful! I don't know if this is a lot to ask for but my personnel wish would be:

- To put [SDL_helloworld](https://github.com/icculus/SDL_helloworld) in libsdl-org as 'SDL_helloworld_basic' for a minimalist example of how to start an SDL project for windows/linux/mac.

- And to put [sdl3-sample](https://github.com/icculus/SDL_helloworld) in libsdl-org as 'SDL_helloworld_advanced' for an example of how to start an SDL project for platforms beyond windows/linux/mac, such as iOS and Android.

**Comment by icculus** [comment]
> Another little thing: SDL3::Headers is not needed. 

Fixed now!
