### ISSUE TITLE
Is there a way to stop events from being queued?

### ISSUE THREAD

**Issue by faizol** [libsdl-org/SDL#8255]
platform: Linux
SDL version : SDL2 & SDL3

I am experimenting with callback using boost.signals with SDL3 and trying to use own queue management for that. I found SDL_StopEventLoop() function in SDL_events.c but that seems to not being exported to the library. I tried to change all the files in dynapi folder to generate the function as exported symbol in the shared or static library but that didn't seem to work. Is there a way to stop the generated events from being queued selectively or for all of them?

**Comment by icculus** [comment]
I don't know what you're trying to do specifically, but SDL_SetEventFilter can be used to forbid events from reaching SDL's event queue at all.

**Comment by faizol** [comment]
> I don't know what you're trying to do specifically, but SDL_SetEventFilter can be used to forbid events from reaching SDL's event queue at all.

Thank you. I just found some examples using SDL_SetEventFilter to return 0 and prevent the filtered event from reaching event queue.
