### ISSUE TITLE
Bluetooth Nintendo Switch Pro Controller does not trigger SDL_JOYDEVICEADDED on reconnect

### ISSUE THREAD

**Issue by minkezhang** [libsdl-org/SDL#8260]
See https://retropie.org.uk/forum/post/290734 for full context.

I am trying to conect to a RaspberryPi Zero 2W board with the Bluetooth functionality of a Nintendo Switch Pro Controller. The connection works upon repeated connect / disconnect cycles, as confirmed by `jstest /dev/input/js0`.

However, it appears there is some issue with SDL events not firing upon subsequent reconnects.

```python
import sdl2
import ctypes

v = sdl2.version.SDL_version()
sdl2.SDL_GetVersion(ctypes.byref(v))
assert "%s.%s.%s" % (v.major, v.minor, v.patch) == "2.28.3" 

sdl2.SDL_Init(sdl2.SDL_INIT_JOYSTICK)
event = sdl2.SDL_Event()

def _list_js():
    for j in range(sdl2.SDL_NumJoysticks()):
        js = sdl2.SDL_JoystickOpen(j)
        print(sdl2.SDL_JoystickName(js))

while True:
    if sdl2.SDL_PollEvent(ctypes.byref(event)) != 0:
        if event.type == sdl2.SDL_JOYDEVICEADDED:
            print("SDL_JOYDEVICEADDED")
            _list_js()
        elif event.type == sdl2.SDL_JOYDEVICEREMOVED:
            print("SDL_JOYDEVICEREMOVED")
            _list_js()
```

Trying to run this script nets the following output

```bash
SDL_JOYDEVICEADDED
b'Nintendo Switch Pro Controller'  # after boot
 
# Power off controller and wait for 10s
 
SDL_JOYDEVICEREMOVED  # controller removed
 
# Power back on and paired, no SDL_JOYDEVICEADDED event generated
```

If I rerun this script (i.e. call `SDL_Init` again), I get

```bash
SDL_JOYDEVICEADDED
b'Nintendo Switch Pro Controller'
```

If I'm interpreting this correctly, this seems to indicate there is some dropped `SDL_JOYDEVICEADDED` signal.

**Comment by slouken** [comment]
Yes, your analysis seems correct and the code usage seems right. Can you run testcontroller from the SDL test programs and see if it has the same behavior?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.
