### ISSUE TITLE
SDL2.0.22 crashed on macos10.13

### ISSUE THREAD

**Issue by MrYin23** [libsdl-org/SDL#8264]
SDL version: SDL 2.0.22
OS: MacOS High Sierra

I crashed on Mac OS 10.13 using self built  SDL2.0.22（There is no problem using SDL2.0.12）, and the crash stack is as follows:

Termination Reason:    DYLD, [0x4] Symbol missing
Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/.../office6/libSDL2-2.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Thread 0 Crashed::Dispatch queue: com.apple.main-thread
0   dyld                          	0x000000011384924a __abort_with_payload + 10
1   dyld                          	0x0000000113848bbc abort_with_payload_wrapper_internal + 89
2   dyld                          	0x0000000113848be9 abort_with_payload + 9
3   dyld                          	0x000000011381c482 dyld::halt(char const*) + 354
4   dyld                          	0x000000011381c5a9 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 170
5   libdyld.dylib                 	0x00007fff6e470292 dyld_stub_binder + 282
6   ???                           	0x00000001733bb000 0 + 6228258816
7   libSDL2-2.0.dylib             	0x000000017336581c COREAUDIO_DetectDevices + 28
8   libSDL2-2.0.dylib             	0x0000000173278db5 SDL_AudioInit_REAL + 885
9   libSDL2-2.0.dylib             	0x0000000173275edc SDL_InitSubSystem_REAL + 220

**Comment by icculus** [comment]
So this happens when building with a newer Xcode and running on an older macOS.

This should just need the deployment target changed to fix this. Did you build this with the Xcode project, or the configure script? Something else?

**Comment by MrYin23** [comment]
> So this happens when building with a newer Xcode and running on an older macOS.
> 
> This should just need the deployment target changed to fix this. Did you build this with the Xcode project, or the configure script? Something else?



> So this happens when building with a newer Xcode and running on an older macOS.
> 
> This should just need the deployment target changed to fix this. Did you build this with the Xcode project, or the configure script? Something else?

It should be compiled using the xcode command line. How can I change the deployment target? modify MACOSX_DEPLOYMENT_TARGET in project?

**Comment by icculus** [comment]
I don't know off the top of my head, but I think so...but also, I'm surprised we don't have this set to something pretty conservative already.

**Comment by icculus** [comment]
The Xcode project has the right values; I have to find a 10.13 machine to verify, but I'm inclined to just close this.

**Comment by slouken** [comment]
I believe this is fixed in the latest SDL release. Please feel free to reopen if you're still seeing this issue.
