### ISSUE TITLE
AudioStreams should work in terms of sample frames, not bytes

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8265]
Just putting this up here for a sanity check before I make this change, but several pieces of SDL_AudioStream's public API operate in _bytes_, but should probably speak in _sample frames_ instead.

Talking in bytes is a holdover from SDL1 audio callback (where you might have only had time to memcpy a premixed buffer in a predetermined format before a hardware interrupt expired), but there are several places where we immediately convert that number to a count of sample frames internally, or have to deal with the possibility that the app erroneously gave us half a sample frame, etc.

Affected APIs are:

SDL_PutAudioStreamData
SDL_GetAudioStreamData
SDL_GetAudioStreamAvailable
SDL_AudioStreamCallback
SDL_AudioPostmixCallback

Oddballs:
SDL_MixAudioFormat  (it only cares about _samples_ and not frames)
SDL_LoadWAV, SDL_LoadWAV_RW, and SDL_ConvertAudioSamples (callers probably care more about buffer size than sample frame count (but I might be wrong)).

CC @slouken @0x1F9F1 ...any objection to me making this change?

**Comment by slouken** [comment]
I think it's reasonable for the audio stream functions to work in terms of frames. Applications can probably work with either one, and may need to convert internally between them, so whatever makes sense from an aesthetic and functional point of view is fine.

**Comment by 0x1F9F1** [comment]
Personally I'd stick with bytes, since I think most applications just treat audio as blobs of data.
At least when the calculations are done internally, we know they are being done with a valid spec.

**Comment by slouken** [comment]
So I was thinking about this a little more, and conceptually working with frames makes sense, but:
* If you're writing your own mixer, you know the size of your frames and can easily convert to bytes
* If you're opening a stream and throwing chunks of data from files at it, you don't want to have to query the spec and do the math every time you add data.
* The existing API calls all used bytes and changing that to samples without a function signature change would lead to surprising bugs.

So, as much as I'd like to switch to samples, I think bytes is probably the right call. @libsdl-org/a-team thoughts?

**Comment by icculus** [comment]
Okay, I switched SDL_GetAudioStreamQueued over to bytes, let's close this issue as WONTFIX, too.
