### ISSUE TITLE
Audio device format changed event

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8267]
We need a new event when the audio device format changes.

Cases I can think of:
* User changes speaker configuration in system settings
* User changes the default audio device

I'm not sure how this would work given the plethora of logical devices, but applications need some way of knowing things have changed so they can update their mixing or UI as needed.

**Comment by icculus** [comment]
I have this in progress, PR coming soon!

**Comment by icculus** [comment]
Okay, PR posted!
