### ISSUE TITLE
SDL_exit?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8276]
So one part of the standard library you need, unless you always can cleanly return from main(), is exit(), but SDL doesn't include this in SDL_stdinc.h.

We have a thing in SDL.c for this:

```c
/* This is not declared in any header, although it is shared between some
    parts of SDL, because we don't want anything calling it without an
    extremely good reason. */
extern SDL_NORETURN void SDL_ExitProcess(int exitcode);
```

We should make this part of the public API. Otherwise you end up having to include stdlib.h for this one function.

We should note that it does not respect atexit() handlers, because we don't control the C runtime the app is using. 

Also noting that I don't know why the comment demands you avoid it without an "extremely good reason," and that it might be worth figuring out what the concern was.

**Comment by okuoku** [comment]
What will it do on Emscripten(that is, platforms without exit() feature)? (A)bort (R)eload the program or (I)nfinite event waiting?

**Comment by slouken** [comment]
You shouldn't call this on iOS or Android. Not calling atexit() handlers means that some graphics driver cleanup won't happen. I'm also not sure what will happen with global destructors, which are important in large games, etc. etc.

We should not expose this... or even call it, really. :)

**Comment by icculus** [comment]
> What will it do on Emscripten(that is, platforms without exit() feature)? (A)bort (R)eload the program or (I)nfinite event waiting? 

Emscripten has an exit() function, and it eventually just makes the page go idle.

**Comment by icculus** [comment]
> You shouldn't call this on iOS or Android

Nor on a console, or a webpage, where we expect there to be a different mechanism for quitting an app, and those can take the "quit to desktop" option off their main menus.  :)

> Not calling atexit() handlers means that some graphics driver cleanup won't happen.

This is a Linux issue, but the C runtime is ubiquitous there, which is why graphic drivers expect it to work...so we probably use exit() internally on that platform.

> We should not expose this... or even call it, really. :)

But there are times when one needs to eject from a process without returning from main(). Our test apps do this, SDL_assert does this. Most programs take for granted they can terminate the process at any time, and they need the C runtime for this one function.

**Comment by smcv** [comment]
Would it make sense for this to exist on exactly those platforms where it would make sense to call it (Windows, Linux, macOS) but cause a compile/link error on the platforms where you shouldn't call it anyway (games consoles, iOS, Android); possibly combined with an easy way to detect at compile-time whether it's something that makes sense on the current platform?

**Comment by icculus** [comment]
> Would it make sense for this to exist on exactly those platforms where it would make sense to call it (Windows, desktop Linux, macOS) but cause a compile/link error on the platforms where you shouldn't call it anyway (games consoles, iOS, Android); possibly combined with an easy way to detect at compile-time whether it's something that makes sense on the current platform?

I'd probably rather this exist as a fallback on platforms that literally have nothing:

```c
void SDL_exit(int exitcode)
{
    #if ABSOLUTELY_NOT_SUPPORTED
    while (SDL_TRUE) { SDL_Delay(999999999); }  // this never returns, but just sleeps forever.
    #endif
}
```

But even on platforms that don't _want_ you to terminate your own process, they almost always _allow_ you to. You shouldn't call exit() on an iOS app because Apple would rather apps operate as if they run forever (and will quietly terminate them in the background and later revive them without the user noticing), but exit() works and will just dump the user back to the home screen.

The only place where this is absolutely forbidden, afaik, is consoles: you will definitely fail cert if you call (the equivalent of) exit() in a PlayStation game, but the function still exists and works, and is useful in debug builds when you hit an assertion, or perhaps in some performance test developers run locally that is meant to fly through a map, report the FPS, and terminate.

Anyhow, I'm going to leave this issue open for now, but if we end up closing it as WONTFIX, that's how it goes. But I really think we should offer this API in SDL3.

**Comment by icculus** [comment]
I'm closing this as WONTFIX; there's a few too many corner cases that aren't worth imposing on the app.
