### ISSUE TITLE
SDL2 on MacBook M2

### ISSUE THREAD

**Issue by robfaber** [libsdl-org/SDL#8277]
I'm not able to run my SDL2 applications anymore on my MacBook M2 (Ventura 13.5.2) with arm arch.

Compiling, linking the application works perfectly fine as always but when I run;
```
dyld[7130]: Symbol not found: _SDL_CreateRenderer
  Referenced from: <F60490C0-EABA-38AE-B46D-F334205E6A95> /Users/rob/Developer/SDL_helloworld/build/sdl-helloworld
  Expected in:     <no uuid> unknown
[1]    7130 abort      /Users/rob/Developer/SDL_helloworld/build/sdl-helloworld
```
The output above is produced by a fork of https://github.com/libsdl-org/SDL_helloworld
Which can be found here; https://github.com/robfaber/SDL_helloworld/tree/sdl2

The only change I made was I downgraded the example to SDL2.
But I'm getting the above result on all my SDL2 applications.

Using SDL2-2.28.3.dmg but also tried other versions with same error

Please advice, breaking my head over this one for days now....

**Comment by icculus** [comment]
Can you run `otool -L /Users/rob/Developer/SDL_helloworld/build/sdl-helloworld` and make sure it's actually linked against SDL2?

**Comment by robfaber** [comment]
❯ otool -L build/sdl-helloworld
build/sdl-helloworld:
	@rpath/SDL2.framework/Versions/A/SDL2 (compatibility version 2801.0.0, current version 2801.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)

**Comment by icculus** [comment]
Mmm...maybe it's an Intel-only version of SDL2...? So it definitely found the file but then rejected it for not being ARM?

I'm not really sure what went wrong here. @slime73, you ever see anything like this?

**Comment by slouken** [comment]
> Mmm...maybe it's an Intel-only version of SDL2...? So it definitely found the file but then rejected it for not being ARM?

That seems very likely.

**Comment by robfaber** [comment]
I can try to link it against a locally build version of the framework. Would that help?

**Comment by robfaber** [comment]
Yes that worked! So I have followed the instruction and have built SDL and ran `cmake --install . ` after that. Removed SDL.framework from my ~/Library/Frameworks folder. Rebuild the SDL_helloworld and bingo!

What does this prove? That we need a separate distribution for ARM on OSX?

**Comment by Nrezinorn** [comment]
I have this problem on an INTEL macbook pro too

Copied the 2.28.4 DMG framework to /Library/Frameworks.

`g++ -g -fpermissive -DDEBUG -F/Library/Frameworks   -c -o src/foo.o src/foo.cpp
g++ -o demo src/foo.o -g -fpermissive -DDEBUG -F/Library/Frameworks -framework SDL2 -framework cocoa
nrezinorn@Jims-MacBook-Pro samples % ./demo
dyld[47879]: Symbol not found: _SDL_CreateWindow
  Referenced from: <59CD2E4B-5645-3FB6-BE4B-FB8B165A0413> /Users/nrezinorn/git/samples/demo
  Expected in:     <no uuid> unknown
zsh: abort      ./demo
nrezinorn@Jims-MacBook-Pro samples % otool -L demo
demo:
	@rpath/SDL2.framework/Versions/A/SDL2 (compatibility version 2801.0.0, current version 2801.4.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 24.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.151.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)`

**Comment by slouken** [comment]
You need to build a universal framework. The Xcode project provides that, and you can also download it from the SDL release page:
https://github.com/libsdl-org/SDL/releases/download/release-2.28.4/SDL2-2.28.4.dmg

**Comment by AasmundN** [comment]
I was finally able to make it work using this setup

```cmakecmake_minimum_required(VERSION 3.5.0)
project(sdl-test)

include(CTest)
enable_testing()

add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(
  ${PROJECT_NAME} PRIVATE
  /Library/Frameworks/SDL2.framework/Versions/A/SDL2
)

target_include_directories(
  ${PROJECT_NAME} PRIVATE
  /Library/Frameworks/SDL2.framework/Versions/A/Headers
)

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
```
Should this be necessary?

**Comment by madebr** [comment]
I recently pushed a fix for the framework CMake config.
https://github.com/libsdl-org/SDL/commit/10c292b0550d98bf891416162b50e91c14928ef3
It fixed a similar problem for somebody on discord.

**Comment by AasmundN** [comment]
So when a new version is released I should be able to include the library like it says in the dmg readme?

Use in CMake projects:
SDL2.framework can be used in CMake projects using the following pattern:
```
find_package(SDL2 REQUIRED COMPONENTS SDL2)
add_executable(my_game ${MY_SOURCES})
target_link_libraries(my_game PRIVATE SDL2::SDL2)
```
Thanks for the reply 🙌

**Comment by madebr** [comment]
Yes, the person on discord rebuilt the DMG using the xcode project, and was able to use it.
But please also try this so we know before the next release.

There should be a SDL(2).dmg target in the xcode project.

**Comment by AasmundN** [comment]
Great! I am quite new to using cpp and cmake, so I am not quite sure how I would go about testing that. I'll try to figure out how. In the meanwhile, maybe we could reopen this issue?

**Comment by madebr** [comment]
I don't know the cli commands, but you need to open the xcode project at `Xcode/SDL/SDL.xcodeproj` and build the "Standard DMG" target (or something similar).

**Comment by slouken** [comment]
This issue is fixed in the repo, right? We usually close issues when they’re fixed, not when the release happens.

**Comment by madebr** [comment]
Oops sorry. 

Reading this issue again, I think my commit will fix the problem.
I think the error is caused due to wrong rpaths.
https://github.com/libsdl-org/SDL/issues/8277#issuecomment-1753086948 correctly built and linked, but could not find SDL2 at runtime.

Anyway, @AasmundN I'd like to know whether it works for you.

**Comment by AasmundN** [comment]
Okay I am pretty lost here, never used xcode before. I'm on the SDL2 branch, and selected the standard DMG target like you said, but the build is failing. It is complaining about some function declarations.

<img width="1440" alt="Screenshot 2023-12-20 at 00 41 39" src="https://github.com/libsdl-org/SDL/assets/48122613/b9bb7154-7226-41d6-9422-c4a430ed9483">

**Comment by madebr** [comment]
The central warning is non-critical, and can simply be fixed by adding the following above `#if SDL_HAVE_BLIT_AUTO`. (But this is not required)
```c
static SDL_bool SDL_UseALitivecPrefetch(void);
```

The error on the left is more troubling. Can you show the complete error message?
It warns about missing symbols, yet none are listed.

**Comment by AasmundN** [comment]
One thing I notice is that it says something about building for version 10.11. I'm on an M1 mac on Ventura 13.5.2. Also it is saying something about x86_64. And of course the undefined symbols.

<img width="1440" alt="Screenshot 2023-12-20 at 11 43 41" src="https://github.com/libsdl-org/SDL/assets/48122613/bc4da2d9-b4c4-463f-92d0-934b4811dd80">

**Comment by madebr** [comment]
Ignore the warning. The compatibility version is set this low to support older macos.
About the linker error, @slouken is the xcode project up-to-date?

@AasmundN Fetch the latest SDL2 branch and try multiple commits. As a non Apple user, I can't help you here.

**Comment by AasmundN** [comment]
Think I got it. I had to go to product > archive. Then it opened a new panel where I could select distribute content and the export the build. I placed the new SDL2.framework folder in my Framework directory, and it seems to be all working 🙌 
I built the project from your commit, https://github.com/libsdl-org/SDL/commit/10c292b0550d98bf891416162b50e91c14928ef3
