### ISSUE TITLE
Direct3D Fullscreen Gamma Change (+ OpenGL & Vulkan)

### ISSUE THREAD

**Issue by pogrammerX** [libsdl-org/SDL#8280]
I'm using Direct3D right now, when i create my Window with SDL2 everything renders fine, but when i enter fullscreen the gamma is increased, i experienced this issue awell with OpenGL and Vulkan.

Any help is appreciated

**Comment by slouken** [comment]
@danginsburg, any ideas here?

**Comment by danginsburg** [comment]
> @danginsburg, any ideas here?

I'm not familiar with this issue, I'd likely need a repro.  The obvious thing to suggest is to see if calling `SDL_SetWindowGammaRamp` makes any difference (maybe the default gamma being used in the fullscreen mode is incorrect?), but that's just a guess.

**Comment by slouken** [comment]
This isn't anything SDL controls and sounds like a driver issue. Have you installed the latest drivers for your hardware and made sure that you have default settings in the video card driver control panel?

**Comment by pogrammerX** [comment]
Latest drivers are installed. Calling Set_WindowGammaRamp also didn’t help.

Sam Lantinga ***@***.***> schrieb am Do. 23. Mai 2024 um
19:17:

**Comment by slouken** [comment]
What video card do you have, what monitor do you have, and what version of graphics drivers do you have?

**Comment by slouken** [comment]
No response, I'll go ahead and close this for now. Please let us know if it's still an issue.
