### ISSUE TITLE
Potential NULL pointer dereference in LINUX_JoystickGetDeviceGUID

### ISSUE THREAD

**Issue by tntnkn** [libsdl-org/SDL#8282]
In [this piece](https://github.com/libsdl-org/SDL/blob/399bc709b7485bab57880f8261f826f29dc0d7b2/src/joystick/linux/SDL_sysjoystick.c#L1013) the `GetJoystickByDevIndex` may return a `NULL` pointer ( [see here](https://github.com/libsdl-org/SDL/blob/4c3e84897fdf483394cf48c05df6d544afbe83ec/src/joystick/linux/SDL_sysjoystick.c#L980) ) which is then gets dereferenced straight ahead.

**Comment by slouken** [comment]
It's true that this is a potential issue, but the device index is verified before calling these functions and a lock is held that prevents it from changing unexpectedly.
