### ISSUE TITLE
Potential UB in __ieee754_exp

### ISSUE THREAD

**Issue by tntnkn** [libsdl-org/SDL#8283]
In [this piece](https://github.com/libsdl-org/SDL/blob/6a381567b0412603054e3ecd77916085edffe94a/src/libm/e_exp.c#L159) `k` is shifted left, but in may be negative according to the `if` condition above. This is UB in C.

**Comment by slouken** [comment]
This should probably be reported upstream:
https://elixir.bootlin.com/uclibc-ng/latest/source/libm/e_exp.c#L149

**Comment by slouken** [comment]
We'll go ahead and pull a fix from upstream when this is taken care of there.
