### ISSUE TITLE
Potential UB in __ieee754_rem_pio2

### ISSUE THREAD

**Issue by tntnkn** [libsdl-org/SDL#8284]
In [this piece](https://github.com/libsdl-org/SDL/blob/6a381567b0412603054e3ecd77916085edffe94a/src/libm/e_rem_pio2.c#L151) `e0` is being shifted left, but the minimal possible value it may assume according to checks and operations above is `-3`. Shifting negative value to the left is UB in C. Most likely, [here](https://github.com/libsdl-org/SDL/blob/6a381567b0412603054e3ecd77916085edffe94a/src/libm/e_rem_pio2.c#L150C1-L150C1) `1043` should be subtracted instead of `1046`.

**Comment by slouken** [comment]
This should probably be reported upstream:
https://elixir.bootlin.com/uclibc-ng/latest/source/libm/e_rem_pio2.c#L150

**Comment by slouken** [comment]
We'll go ahead and pull a fix from upstream when this is taken care of there.
