### ISSUE TITLE
SDL_GetCursor may return uninitialized cursor

### ISSUE THREAD

**Issue by tntnkn** [libsdl-org/SDL#8285]
In [this piece](https://github.com/libsdl-org/SDL/blob/4c3e84897fdf483394cf48c05df6d544afbe83ec/src/events/SDL_mouse.c#L1376) the check for `NULL` does not make sense, because what is returned by `SDL_GetMouse` is the address of a global static variable. It cannot be `NULL` but the variable may be pretty much uninitialized (with correct values) when `SDL_GetCursor` is called.

**Comment by slouken** [comment]
The mouse is a static variable so should be initialized to zero. The check for NULL is silly, but harmless, and good practice once we support multiple mice.
