### ISSUE TITLE
Possible wrong branching in SDL_SW_FillTriangle

### ISSUE THREAD

**Issue by tntnkn** [libsdl-org/SDL#8286]
In [this piece](https://github.com/libsdl-org/SDL/blob/bac7eeaaae00b929808ed8efe1a76e45a4e2c54b/src/render/software/SDL_triangle.c#L341) branches have identical code. If the commented code is no more valid, then probably the branching should be deleted.

**Comment by slouken** [comment]
The branching should probably be deleted. I'll leave this open as a reminder to verify this.
