### ISSUE TITLE
Possible UB SDL_iconv_string

### ISSUE THREAD

**Issue by tntnkn** [libsdl-org/SDL#8287]
In [this piece](https://github.com/libsdl-org/SDL/blob/bac7eeaaae00b929808ed8efe1a76e45a4e2c54b/src/stdlib/SDL_iconv.c#L789) `NULL` may be passed, as signified by the checks following after. The accepting function is a wrapper around unix `iconv_open`. In clib implementations known to me no checks for `NULL`s would be done in this function. See [BSD](https://github.com/freebsd/freebsd-src/blob/366ef17bb6ce008f79a283ff5dc5e87ab13dbdb3/sys/libkern/iconv.c#L248), [Musl](https://github.com/kraj/musl/blob/2e6edc1b699851fcbe9f7ab0fbd724624adde88a/src/locale/iconv.c#L145) and [GNU](https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/iconv/iconv_open.c#L32). The checks for `NULL` shall be placed before the first call.

**Comment by slouken** [comment]
Fixed, thanks!
