### ISSUE TITLE
Impossible check in SDL_LoadFile_RW

### ISSUE THREAD

**Issue by tntnkn** [libsdl-org/SDL#8288]
In [this piece](https://github.com/libsdl-org/SDL/blob/4c3e84897fdf483394cf48c05df6d544afbe83ec/src/file/SDL_rwops.c#L644C10-L644C10), if `size` would try to be more then `SIZE_MAX`, wouldn't it be UB?

**Comment by slouken** [comment]
What is UB?
The API takes 64-bit values, but size_t can be 32-bit on some systems.

**Comment by tntnkn** [comment]
Sure. What I am saying is that when `size` would try to be more than `SIZE_MAX`, it would overflow regardless of word size. And while `size` is signed, overflow will cause undefined behavior. 

Well, the main question is rather how `int64_t` max value can possibly be more then `size_t` max value?

PS: here is [the definition of Sint64](https://github.com/libsdl-org/SDL/blob/1375d2049d9fd17cb0d9a47a0e256a42c3188f76/include/SDL3/SDL_stdinc.h#L178), the type of the `size` variable, and [here is the one for](https://github.com/libsdl-org/SDL/blob/1375d2049d9fd17cb0d9a47a0e256a42c3188f76/include/SDL3/SDL_stdinc.h#L64) for SDL_SIZE_MAX.

**Comment by slouken** [comment]
On 32-bit systems, size_t is 32 bits, which is less than 64 bits. :)
