### ISSUE TITLE
Render the picture using the device pixel resolution

### ISSUE THREAD

**Issue by w4ngzhen** [libsdl-org/SDL#8293]
SDL is a great library, but I’ve had some issues lately.
Recently I was using SDL to create an image software on my Mac. The logical resolution of my Mac machine is 1280X800 (also called “Point”). Then, I prepared a PNG image with a resolution of 2560X1600(in fact, that is my screenshot). Now I want to render this image to a full-screen window created by SDL. However, in fact, the picture is rendered very blurry, here I guess because although the texture with a resolution of 2560X1600, but, the logical resolution of the resolution to be processed by the render is 1280X800, which is reduced and therefore blurred. But my use of SDL_RenderSetLogicalSize didn’t work either. What I want is that when I render PNG images, I can directly use the device’s 2560X1600 resolution pixels, not because of the logical resolution at High DPI. Can this be done?

**Comment by slouken** [comment]
This is a bug reporting tool, but this is a great question for the SDL discussion group:
https://discourse.libsdl.org/c/sdl-development/6
