### ISSUE TITLE
ActiveX not available error from SDL_Init(SDL_INIT_VIDEO)

### ISSUE THREAD

**Issue by cpicanco** [libsdl-org/SDL#8296]
Hi everyone,

I am getting an "ActiveX not available" error from SDL_Init(SDL_INIT_VIDEO) on an old Windows 7 machine. Can you shed some light on this?

Best regards,
R

**Comment by icculus** [comment]
That's a string that SDL_GetError returned? If so, and if you can, it would be helpful if you could set a breakpoint on SDL_SetError and see where that is getting set.

Also, if there's something unusual about your windows install, let us know. Maybe there's literally a system component that's missing or damaged...?

**Comment by cpicanco** [comment]
Yes, it is a message returned by SDL_GetError. I am working on Free Pascal code using SDL2 bindings. There is an unusual fact, code is running on an old Windows 7, the display pc part of an Eye Link system.

All I get right now is the error message, because the source C files are not setup for debugging in my dev env. I am not sure where should I place them ir order to Lazarus give me the specific line of the error, but I can work on that soon.

**Comment by sezero** [comment]
Why do you call SDL_GetError? Is some SDL call actually returning error and you want to see the reason? If not, then it's perfectly normal to get some random error message from SDL_GetError (see its documentation in SDL_error.h)

**Comment by cpicanco** [comment]
I am calling to test if the video was initialized:

```pascal
  if SDL_Init(TSDL_Init(SDL_INIT_VIDEO)) < 0 then begin
    Print(SDL_GetError);
    Exit;
  end;
```

So, I am doing something wrong here?

**Comment by sezero** [comment]
`SDL_GetError` is called only if `SDL_Init(SDL_INIT_VIDEO)` fails, so you aren't doing it wrong.
(I asked because people do that mistake once in a while.)

**Comment by cpicanco** [comment]
Thanks @sezero , my bad not including the code. Well, I am really not sure where I should place the source/header SDL files in order to allow Lazarus to jump into the C code. I am searching for this right now.

**Comment by cpicanco** [comment]
Hi everyone, just want to give you an update on this.

I am getting this weird "activex not available" error when calling:

```
if SDL_InitSubSystem(SDL_INIT_VIDEO) < 0 then begin
  raise Exception.Create(SDL_GetError);
end;
```

or 

```
if SDL_Init(SDL_INIT_VIDEO) < 0 then begin
  raise Exception.Create(SDL_GetError);
end;
```
The strange thing is that this error was **NOT** happening on my Windows 11 machine. I found this error running on a Windows 7 machine. And now it is happening on my Windows 11 machine too. What the hell is happening??

**Comment by cpicanco** [comment]
For reasons I cannot examplain, the bug is gone. I deleted the `SDL_VIDEODRIVER` system variable that was `directx` and now everything is working just fine (https://wiki.libsdl.org/SDL2/FAQUsingSDL).

The weird thing is that now I can't reproduce the bug. Please, help me making some sense of this. I don't want to think I am getting crazy or allucinating. 🤣 😆

**Comment by cpicanco** [comment]
So, for the old Windows 7, setting "windows" in `SDL_VIDEODRIVER` fixed the problem.
