### ISSUE TITLE
Audio device already open

### ISSUE THREAD

**Issue by MrJokerBoy** [libsdl-org/SDL#8297]
Hello, can I open multiple audio devices by calling SDL_OpenAudioDevice? , the second call prompts the following error message: “Audio device already open”

**Comment by icculus** [comment]
In SDL2, it depends on the platform and the hardware. Some let you do it, some do not.

In SDL3, you can open the audio device as many times as you want (because SDL3 opens the actual hardware only once and manages the details to make it look to the app like it opened it multiple times).

**Comment by MrJokerBoy** [comment]
Hello, I am currently using SDL2.28.3 version.

**Comment by MrJokerBoy** [comment]
I would like to ask if there is any relevant introductory document on upgrading from 2.0 to 3.0 or how to download 3.0 directly.

**Comment by slouken** [comment]
You can get SDL3 directly from GitHub:
https://github.com/libsdl-org/SDL

Migration information is available here:
https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_audioh
