### ISSUE TITLE
Use `RAWMOUSE.ulExtraInformation` instead of `GetMessageExtraInfo()` to filter touch events in WM_INPUT

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#8298]
`GetMessageExtraInfo()` is not actually tied to the actual message being processed but rather a global state for the current thread. It is overwritten on successive message fetches from the queue, and can be mutated at any time via `SetMessageExtraInfo` so it is not an authoritative ground-truth for what the original OS-supplied ExtraInfo was.

On the other hand, the `.ulExtraInformation` member of each rawinput report is associated to that report alone.

The advantage of using the ground-truth field associated to individual rawinput reports may not be immediately apparent if you process each WM_INPUT message synchronously, however it's not just a matter of dependency cleanliness but also that it allows you to use `GetRawInputBuffer` to retrieve all pending rawinput reports upon notification, without losing track of whether the input is generated by touch or device.

**Comment by slouken** [comment]
That sounds good, do you have a PR ready?
