### ISSUE TITLE
Software renderer draws long lines incorrectly

### ISSUE THREAD

**Issue by genpfault** [libsdl-org/SDL#8301]
The software renderer draws long lines incorrectly, either with the wrong slope (`SDL_RENDERLINEMETHOD_LINES`):

![image](https://github.com/libsdl-org/SDL/assets/721338/37ce0812-b76a-483b-a8ca-d578cf0264b7)

...or in extra places (`SDL_RENDERLINEMETHOD_GEOMETRY`):

![image](https://github.com/libsdl-org/SDL/assets/721338/f1bfcf56-91ee-484e-bcd1-f45acb76a54e)

Compare to the expected output (with `x` set to `1 << 10`, using `SDL_HINT_RENDER_LINE_METHOD`):

![image](https://github.com/libsdl-org/SDL/assets/721338/b83a8f85-59cc-43d6-8a83-ab2dc3fc511e)

Demo:

```c++
#include <SDL.h>

int main( int, char** )
{
    //SDL_SetHint( SDL_HINT_RENDER_LINE_METHOD, "2" ); // SDL_RENDERLINEMETHOD_LINES
    SDL_SetHint( SDL_HINT_RENDER_LINE_METHOD, "3" ); // SDL_RENDERLINEMETHOD_GEOMETRY

    SDL_Init( SDL_INIT_EVERYTHING );
    auto win = SDL_CreateWindow( "SDL", 100, 100, 300, 300, SDL_WINDOW_SHOWN );
    auto ren = SDL_CreateRenderer( win, -1, SDL_RENDERER_SOFTWARE );

    bool running = true;
    while( running )
    {
        SDL_Event ev;
        while( SDL_PollEvent( &ev ) )
        {
            if( SDL_QUIT == ev.type || SDL_KEYUP == ev.type )
            {
                running = false;
                break;
            }
        }

        SDL_SetRenderDrawColor( ren, 0, 0, 0, SDL_ALPHA_OPAQUE );
        SDL_RenderClear( ren );

        int x = ( 1 << 24 );
        SDL_SetRenderDrawColor( ren, 255, 255, 255, SDL_ALPHA_OPAQUE );
        SDL_RenderDrawLine( ren, -x, -x, x, x );

        SDL_RenderPresent( ren );
    }

    SDL_DestroyRenderer( ren );
    SDL_DestroyWindow( win );
    SDL_Quit();

    return 0;
}
```

I'm seeing this on [`release-2.28.3`](https://github.com/libsdl-org/SDL/tree/release-2.28.3).

**Comment by hkva** [comment]
This seems to be caused by an integer overflow in SDL_IntersectRectAndLine/SDL_GetRectAndLineIntersection during screen clipping.

**Comment by icculus** [comment]
The latest in revision control fixes the LINES and POINTS case. I still need to look into the GEOMETRY case.

**Comment by icculus** [comment]
The GEOMETRY case seems to be dying at this point:

https://github.com/libsdl-org/SDL/blob/d81d98685887a90b8284a57130da6a3712b63202/src/render/software/SDL_triangle.c#L248-L256

SDL_IntersectRect seems to fail with negative numbers, large or not, so when dstrect is `{x = -16777216, y = -16777216, w = 1, h = 1}`, this ends up with a rect of `{x = 0, y = 0, w = -16777215, h = -16777215}`.

Simple test program that demonstrates the problem.
```c
#include "SDL.h"

int main( int, char** )
{
    SDL_Rect dstrect = { -10, 10, 1, 1 };
    SDL_Rect rect = { 0, 0, 300, 300 };
    SDL_IntersectRect(&dstrect, &rect, &dstrect);
    printf("{x = %d, y = %d, w = %d, h = %d}\n", dstrect.x, dstrect.y, dstrect.w, dstrect.h);
    return 0;
}
```

This prints `{x = 0, y = 10, w = -9, h = 1}`, which is not right at all.

**Comment by 1bsyl** [comment]
btw, if now, you use `1<<25`,
it will display nothing, even for the opengl renderer, because
the coordinates are internally float, and so all get rounded to the same thing.

**Comment by slouken** [comment]
This is confirmed fixed by @1bsyl's changes, thanks!
