### ISSUE TITLE
Delete Mercurial repositories

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8310]
So a Mercurial client will still successfully pull from hg.libsdl.org, but there hasn't been a commit there since 2021, of course.

It's way past time to shut these down.

Should I push a commit that deletes everything except a README that says we moved, or should I just turn off Mercurial access outright on the server?

**Comment by slouken** [comment]
Go ahead and just turn it off.

**Comment by icculus** [comment]
Ok, done. If someone tries to point a Mercurial client at it:

```
icculus@lucha:~/SDL-hg$ hg pull
pulling from https://hg.libsdl.org/SDL
real URL is https://github.com/libsdl-org/SDL
real URL is https://github.com/libsdl-org/SDL
abort: HTTP Error 400: Bad Request

icculus@lucha:~/SDL-hg$ cd
icculus@lucha:~$ hg clone https://hg.libsdl.org/SDL
real URL is https://github.com/libsdl-org/SDL
real URL is https://github.com/libsdl-org/SDL
abort: HTTP Error 400: Bad Request
```

So it'll literally tell them it moved to GitHub before failing, which is nice. Web browsers still redirect to the best URL for the request, so something like https://hg.libsdl.org/SDL/rev/00a1aa5a1fc0 will still kick to https://github.com/libsdl-org/SDL/commit/48ac92af548607e91fc6744872ad490717d277b5, etc
