### ISSUE TITLE
Compile fails on MinGW 7.3.0 with HIDAPI enabled

### ISSUE THREAD

**Issue by LooSik** [libsdl-org/SDL#8324]
I am hitting a weird linker error when trying to build SDL on ubuntu/bionic with hidapi enabled since version 2.0.18 
( 2.0.16 is compiling without issues ).

```
./configure --host=i686-w64-mingw32
make
```

SDL 2.82.3 error:
```
In file included from /usr/share/mingw-w64/include/oledlg.h:25:0,
                 from /usr/share/mingw-w64/include/setupapi.h:27,
                 from ../src/hidapi/windows/hid.c:69,
                 from ../src/hidapi/SDL_hidapi.c:590:
/usr/share/mingw-w64/include/commdlg.h:621:5: error: unknown type name 'LPUNKNOWN'
     LPUNKNOWN lpCallback;
     ^~~~~~~~~
/usr/share/mingw-w64/include/commdlg.h:645:5: error: unknown type name 'LPUNKNOWN'
     LPUNKNOWN lpCallback;
     ^~~~~~~~~
Makefile:374: recipe for target 'build/SDL_hidapi.lo' failed
make: *** [build/SDL_hidapi.lo] Error 1
```

`--disable-hidapi` allows the build to succeed

I am on ubuntu bionic with mingw version 7.3.0
```
apt-get -yq install g++-mingw-w64-i686 g++-mingw-w64-x86-64
Reading package lists...
Building dependency tree...
Reading state information...
g++-mingw-w64-i686 is already the newest version (7.3.0-11ubuntu1+20.2build1).
g++-mingw-w64-x86-64 is already the newest version (7.3.0-11ubuntu1+20.2build1).
```

ubuntu focal has mingw 9.3.0 provided in repository and seems to be compiling it all right, but would really like the build to pass on lower mingw version.

**Comment by LooSik** [comment]
As a side note, I did manage to build it temporarily adding
`#include <unknwn.h>` to `hidapi/windows/hid.c`

Then make seems to have no issues linking
```
  LTLINK build/libSDL2main.la
  LTLINK build/libSDL2_test.la
i686-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
i686-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
  LTLINK build/libSDL2.la
i686-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
```

**Comment by sezero** [comment]
Seems like an issue with mingw-w64-headers: What version of it is in use?

**Comment by madebr** [comment]
I reproduced it with a `ubuntu:bionic` docker container.
```
$ apt-cache show mingw-w64-common
Package: mingw-w64-common
Architecture: all
Version: 5.0.3-1
...
```

**Comment by sezero** [comment]
Issue with mingw-w64 headers, yes v5.0.3 has it, fixer later by this:
https://github.com/mingw-w64/mingw-w64/commit/d713e2226a3ff134d1367e5638f0242640f5a049

IMO, we shouldn't do anything here.

**Comment by sezero** [comment]
And, just built release-2.28.x branch using mingw gcc-7.5 against mingw-w64 headers and libs from their v5.x branch: no issues.

**Comment by LooSik** [comment]
Thank you for investigating this, I guess the solid workaround is to use the newer fixed headers or just applying the mentioned commit that changes `#include <oledlg.h>` to `#include <devpropdef.h>` in the `setupapi.h` this indeed makes the SDL compile.

**Comment by sezero** [comment]
OK then, closing this.

**Comment by sezero** [comment]
FWIW, mingw-w64 just tagged a v5.05 release, so you can poke ubuntu / debian guys to update their stuff.
