### ISSUE TITLE
[winxp] SDL_GetWindowPixelFormat returns SDL_PIXELFORMAT_UNKNOWN

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8328]
Running SDL3's testautomation.exe in a Windows xo vm fails for the `video_getWindowPixelFormat` test:
```
INFO:  10/01/23 10:37:05: ----- Test Case 22.12: 'video_getWindowPixelFormat' started
INFO:  10/01/23 10:37:05: Test Description: 'Checks SDL_GetWindowPixelFormat'
INFO:  10/01/23 10:37:05: Test Iteration 1: execKey 10053643308509124472
INFO:  10/01/23 10:37:05: Assert 'Call to SDL_CreateWindow('Title',578,434,48)': Passed
INFO:  10/01/23 10:37:05: Assert 'Validate that returned window struct is not NULL': Passed
INFO:  10/01/23 10:37:05: Assert 'Call to SDL_GetWindowPixelFormat()': Passed
INFO:  10/01/23 10:37:05: Assert 'Verify that returned format is valid; expected: != 0, got: 0': Failed
INFO:  10/01/23 10:37:05: Assert 'Call to SDL_DestroyWindow()': Passed
INFO:  10/01/23 10:37:05: Assert 'Call to SDL_ClearError()': Passed
INFO:  10/01/23 10:37:05: Assert 'Call to SDL_GetWindowPixelFormat(window=NULL)': Passed
INFO:  10/01/23 10:37:05: Assert 'SDL_GetError()': Passed
INFO:  10/01/23 10:37:05: Assert 'Verify error message is not NULL': Passed
INFO:  10/01/23 10:37:05: Assert 'SDL_GetError(): expected message 'Invalid window', was message: 'Invalid window'': Passed
INFO:  10/01/23 10:37:05: Assert 'Call to SDL_ClearError()': Passed
INFO:  10/01/23 10:37:05: Fuzzer invocations: 2
INFO:  10/01/23 10:37:05: Assert Summary: Total=11 Passed=10 Failed=1
INFO:  10/01/23 10:37:05: Total Test runtime: 0.3 sec
```

`SDL_GetWindowPixelFormat()` returns `SDL_PIXELFORMAT_UNKNOWN`.
Screenshot of `testwm.exe`, also showing the unknown pixel format:
![image](https://github.com/libsdl-org/SDL/assets/4138939/d4627371-ab00-4c37-9325-800c8ec2118c)

**Comment by slouken** [comment]
Are you able to debug and see what the format actually is?

**Comment by madebr** [comment]
Running ` SDL_ClearError()` before, and SDL_GetError()` after `SDL_GetPixelFormatName()` gives an empty message.

This is a fresh Windows XP installation running on top of qemu.
I have no compatible debugger installed on this vm.

**Comment by slouken** [comment]
Can you print out the masks for the display format?

**Comment by madebr** [comment]
Adding prints in `WIN_UpdateDisplayMode` [here](https://github.com/libsdl-org/SDL/blob/09d1e9defb49e53acefed0d2fd22b3a28584cd8f/src/video/windows/SDL_windowsmodes.c#L81), I think I see normal bpp values (`data->DeviceMode.dmBitsPerPel`): a combination of palette pixel formats and "normal" formats.

Also in [`WIN_UpdateDisplayMode`](https://github.com/libsdl-org/SDL/blob/09d1e9defb49e53acefed0d2fd22b3a28584cd8f/src/video/windows/SDL_windowsmodes.c#L58-L77), I see `bmi->bmiHeader.biCompression == 0` and `bmi->bmiHeader.biBitCount == 24`.

When I apply this patch:
```diff
--- a/src/video/windows/SDL_windowsmodes.c
+++ b/src/video/windows/SDL_windowsmodes.c
@@ -70,6 +70,8 @@ static void WIN_UpdateDisplayMode(SDL_VideoDevice *_this, LPCWSTR deviceName, DW
                 mode->format = SDL_PIXELFORMAT_RGB555;
                 break;
             }
+        } else if (bmi->bmiHeader.biBitCount == 24) {
+            mode->format = SDL_PIXELFORMAT_RGB24;
         } else if (bmi->bmiHeader.biBitCount == 8) {
             mode->format = SDL_PIXELFORMAT_INDEX8;
         } else if (bmi->bmiHeader.biBitCount == 4) {
```

`testwm.exe` shows this:
![Screenshot from 2023-11-11 03-20-55](https://github.com/libsdl-org/SDL/assets/4138939/64d172d0-4669-4a13-83d0-3c1af30f2131)

**Comment by slouken** [comment]
Sweet, ship it! :)

**Comment by madebr** [comment]
Is it guaranteed to be `RGB24`, and not `BGR24`?
[The BITMAPINFOHEADER documentation](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader) does not tell where to find the bitmask of the RGB components.

That said, what do you think about the following patch? (`BI_RGB` == 0)
```patch
--- a/src/video/windows/SDL_windowsmodes.c
+++ b/src/video/windows/SDL_windowsmodes.c
@@ -70,10 +70,14 @@ static void WIN_UpdateDisplayMode(SDL_VideoDevice *_this, LPCWSTR deviceName, DW
                 mode->format = SDL_PIXELFORMAT_RGB555;
                 break;
             }
-        } else if (bmi->bmiHeader.biBitCount == 8) {
-            mode->format = SDL_PIXELFORMAT_INDEX8;
-        } else if (bmi->bmiHeader.biBitCount == 4) {
-            mode->format = SDL_PIXELFORMAT_INDEX4LSB;
+        } else if (bmi->bmiHeader.biCompression == BI_RGB) {
+            if (bmi->bmiHeader.biBitCount == 24) {
+                mode->format = SDL_PIXELFORMAT_RGB24;
+            } else if (bmi->bmiHeader.biBitCount == 8) {
+                mode->format = SDL_PIXELFORMAT_INDEX8;
+            } else if (bmi->bmiHeader.biBitCount == 4) {
+                mode->format = SDL_PIXELFORMAT_INDEX4LSB;
+            }
         }
     } else if (mode->format == SDL_PIXELFORMAT_UNKNOWN) {
         /* FIXME: Can we tell what this will be? */
```

**Comment by slouken** [comment]
I think RGB24 is right, that's bytes in memory order, which would be reversed if they were packed into a little endian value. This patch looks good to me.

**Comment by madebr** [comment]
I will commit it.
I've got a question about detecting the pixel formats when color masks are available (`bmiHeader.biCompression == BI_BITFIELDS`).
The current code does [not check the pixel size](https://github.com/libsdl-org/SDL/blob/09d1e9defb49e53acefed0d2fd22b3a28584cd8f/src/video/windows/SDL_windowsmodes.c#L58-L72).
This is fine when the red component is the MSB, but when it is LSB, can't it also be RGB24?
Or am I missing something?

```patch
--- a/src/video/windows/SDL_windowsmodes.c
+++ b/src/video/windows/SDL_windowsmodes.c
@@ -61,7 +61,11 @@ static void WIN_UpdateDisplayMode(SDL_VideoDevice *_this, LPCWSTR deviceName, DW
                 mode->format = SDL_PIXELFORMAT_XRGB8888;
                 break;
             case 0x000000FF:
-                mode->format = SDL_PIXELFORMAT_XBGR8888;
+                if (bmi->bmiHeader.biBitCount == 24) {
+                    mode->format = SDL_PIXELFORMAT_BGR24;
+                } else {
+                    mode->format = SDL_PIXELFORMAT_XBGR8888;
+                }
                 break;
             case 0xF800:
                 mode->format = SDL_PIXELFORMAT_RGB565;
```
