### ISSUE TITLE
v2.28.4 assets have wrong file name

### ISSUE THREAD

**Issue by MichaIng** [libsdl-org/SDL#8332]
Many thanks for the new release. However, some of the v2.28.4 assets accidentally have "2.26.4" in their filename: https://github.com/libsdl-org/SDL/releases/tag/release-2.28.4

**Comment by slouken** [comment]
Whoops, fixed, thanks!

**Comment by slouken** [comment]
... and can't count.

**Comment by slouken** [comment]
Fixed, thanks!
