### ISSUE TITLE
testautomation mouse_getMouseFocus fails when run interactively in GNOME/Wayland

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#8333]
```
$ ./testautomation --filter mouse_getMouseFocus
...
ERROR: 02/10/23 19:57:22: Assert 'Check returned window value is not NULL': Failed
ERROR: 02/10/23 19:57:22: Assert 'Check returned window value is test window': Failed
```

Is this just a limitation of the Wayland backend?

**Comment by Kontrabant** [comment]
Ah, it tries to warp the mouse pointer to a point within the window and check that the window has focus, which won't work under Wayland as it explicitly disallows warping the pointer. We'll have to disable the warp test under Wayland as it will never be reliable.

**Comment by smcv** [comment]
Thanks, I thought it would probably be something along those lines.
