### ISSUE TITLE
SDL 2.28.3+ breaks rendering in Mesen2

### ISSUE THREAD

**Issue by TakuikaNinja** [libsdl-org/SDL#8340]
Yes, an SDL2 update broke Mesen2 again.
This time, the renderer fails to show up at all when loading a game, leaving a black screen in the window as if nothing was loaded.
(I'm not even bothering to upload a screenshot because it's so self-explanatory)
This has gotten to the point where the developer has had to add a software rendering option just so Linux users don't get screwed over every time something like this happens.
OS: EndeavourOS (Arch-based)

**Comment by icculus** [comment]
Weird, almost nothing has changed in the 2.28.x releases.

There's one thing about setting a zero-sized cliprect in 2.28.4, but that's the only obvious culprit I see.

**Comment by sezero** [comment]
> Weird, almost nothing has changed in the 2.28.x releases.
> 
> There's one thing about setting a zero-sized cliprect in 2.28.4, but that's the only obvious culprit I see.

You mean https://github.com/libsdl-org/SDL/commit/d710e0be2743a5241766cd8368e5b66dbe190a93? That's not even in 2.28.3, only in 2.28.4.

**Comment by slouken** [comment]
@TakuikaNinja, can you confirm whether 2.28.4 fixes the issue?

**Comment by TakuikaNinja** [comment]
2.28.4 does not fix the issue.

**Comment by slouken** [comment]
I wonder if this is a Wayland issue? Does it happen on macOS as well? Does Mesen do any rendering while games are loading?

**Comment by TakuikaNinja** [comment]
I am using X11 on XFCE4.

**Comment by slouken** [comment]
Are you able to use git bisect to find out where it broke? I don't have access to that environment.

**Comment by TakuikaNinja** [comment]
>Does Mesen do any rendering while games are loading?
It has an interface to let the user select a recent game. That interface seems to display fine but I'm not sure if that explicitly uses SDL2.

**Comment by TakuikaNinja** [comment]
> Are you able to use git bisect to find out where it broke? I don't have access to that environment.

I was just going to check that. Hold on.

**Comment by TakuikaNinja** [comment]
Um, downgrading to 2.28.2 did not fix the issue. It must be something else which is breaking things.
Sorry.

**Comment by TakuikaNinja** [comment]
This appears to be an issue with mesa 23.2.1. Closing.

**Comment by slouken** [comment]
I'm glad you were able to track it down.
