### ISSUE TITLE
SDL3 Unable to play audio

### ISSUE THREAD

**Issue by 0x4d696e68** [libsdl-org/SDL#8342]
in SDL_SetAudioPostmixCallback()

```c
        if (callback && !device->postmix_buffer) {
            device->postmix_buffer = (float *)SDL_aligned_alloc(SDL_SIMDGetAlignment(), device->work_buffer_size);
            if (device->mix_buffer == NULL) {
                retval = SDL_OutOfMemory();
            }
        }
```

it shouldn't be like this ?

```c
            device->postmix_buffer = (float *)SDL_aligned_alloc(SDL_SIMDGetAlignment(), device->work_buffer_size);
            if (device->postmix_buffer == NULL) {
                retval = SDL_OutOfMemory();
            }
```

**Comment by icculus** [comment]
No, because we don't want to allocate a buffer we won't use if setting a NULL callback, and we don't want to allocate the buffer a second time if we've already allocated it.

(And we don't free it if there's a NULL callback in case we're going to reenable the callback later; it'll free when closing the device.)

**Comment by slouken** [comment]
I think they were referring to checking postmix_buffer for a NULL return value from SDL_aligned_alloc(). If you're intentionally not doing that, maybe add a comment that says NULL is okay? Right now it looks like you've written a bug. :)

**Comment by 0x4d696e68** [comment]
i mean this

`
if (callback && !device->postmix_buffer) {
            device->postmix_buffer = (float *)SDL_aligned_alloc(SDL_SIMDGetAlignment(), device->work_buffer_size);
            if (device->postmix_buffer == NULL) {
                retval = SDL_OutOfMemory();
            }
        }
`
because device->mix_buffer is NULL at that point so SDL_SetAudioPostmixCallback() allways return -1

**Comment by icculus** [comment]
Oh, yeah, that _is_ a bug.  :)

**Comment by icculus** [comment]
Fixed, thanks for catching that!
