### ISSUE TITLE
docs/README-android.md wrong about custom class name

### ISSUE THREAD

**Issue by pommicket** [libsdl-org/SDL#8345]
it says to put the .java file at `src/com/gamemaker/game/MyGame.java` although as we can see in `androidbuild.sh`, the file should actually be at `app/src/main/java/com/gamemaker/game/MyGame.java` (doing it as the readme suggests gives a "class not found" exception on startup)

also might be worth mentioning that `app/build.gradle` should be changed too in addition to AndroidManifest.xml?

**Comment by madebr** [comment]
I applied your suggestions in 38dd6bcd3

Since you created this issue, we also have a `build-scripts/create-android-project.py` script that can create a SDL3 Android project for you from scratch.
