### ISSUE TITLE
How to render the avframe which from av_hwframe_map in ffmpeg?

### ISSUE THREAD

**Issue by huangjinshe** [libsdl-org/SDL#8353]
When use ffmpeg + SDL play video, if the video size larger as 4K, `av_hwframe_transfer`_data would take too much times. ffmpeg provide us the alternative way: `av_hwframe_map`, we don't need to copy the data from GPU to CPU, and directly accessing. But current main problem is how to show it then?  Is there any good example we could know that?

**Comment by huangjinshe** [comment]
For directly render the data from GPU without copying to CPU (Hardware acceleration), I think this should put in the SDL v3.0 major todo list.

**Comment by slouken** [comment]
I agree. I'll add an example of this to SDL, as this is becoming a more common use case.

**Comment by slouken** [comment]
I've added an example for SDL3 of how to do cross-platform hardware decoding with ffmpeg.

Enjoy!
