### ISSUE TITLE
first mouse click in window after window creation not registered

### ISSUE THREAD

**Issue by u-an-i** [libsdl-org/SDL#8358]
Window created with `SDL_CreateWindow("name", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, WIDTH, HEIGHT, SDL_WINDOW_RESIZABLE)`.  
  
Polled events checked for `SDL_MOUSEBUTTONDOWN`.  
  
Many attempts at workarounding did not succeed, eg. neither `SDL_WINDOW_MOUSE_FOCUS` nor `SDL_RaiseWindow`.  
  
`printf` to attached console does let the first mouse click register.  
  
Current solution:  
```C
int x, y;
SDL_GetWindowPosition(window, &x, &y);
SDL_WarpMouseGlobal(x + centerX, y + centerY);
INPUT fakeFirstClick[2];
fakeFirstClick[0].type = INPUT_MOUSE;
fakeFirstClick[0].mi.dx = 0;
fakeFirstClick[0].mi.dy = 0;
fakeFirstClick[0].mi.mouseData = 0;
fakeFirstClick[0].mi.dwFlags = MOUSEEVENTF_LEFTDOWN;
fakeFirstClick[0].mi.time = 0;
fakeFirstClick[0].mi.dwExtraInfo = (ULONG_PTR)NULL;
fakeFirstClick[1].type = INPUT_MOUSE;
fakeFirstClick[1].mi.dx = 0;
fakeFirstClick[1].mi.dy = 0;
fakeFirstClick[1].mi.mouseData = 0;
fakeFirstClick[1].mi.dwFlags = MOUSEEVENTF_LEFTUP;
fakeFirstClick[1].mi.time = 0;
fakeFirstClick[1].mi.dwExtraInfo = (ULONG_PTR)NULL;
SendInput(2, fakeFirstClick, sizeof(INPUT));
```
  
Details at https://discourse.libsdl.org/t/first-mouse-click-in-window-after-window-creation-not-registered/46441

**Comment by Michael-LightGameFramework** [comment]
I would like to note that `SDL_SetHint("SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH", "1"); ` is not working either.
( I was trying to help over on the discourse-linked page.)

**Comment by u-an-i** [comment]
Please note:  
  
`SDL_SetHint("SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH", "1")` did not succeed either.  
  
But this Michael-LightGameFramework reported in https://github.com/libsdl-org/SDL/issues/8360 .  
  
I am on Windows 11 in VS2022 using Intel C++ Compiler 2023.

**Comment by u-an-i** [comment]
As I learned, `SDL_SetHint(SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH, "1");` is the correct way to set the hint and this works.  
  
I'll close this report but make the info about such behavior available near the documentation for related functions.

**Comment by slouken** [comment]
Can you suggest documentation updates? It's helpful to get suggestions from fresh eyes on the project.

Thanks!

**Comment by u-an-i** [comment]
I created https://github.com/libsdl-org/sdlwiki/pull/437 and https://github.com/libsdl-org/sdlwiki/pull/436
