### ISSUE TITLE
EMUELEC glXGetProcAddressARB SEG FAULT SDL 2.28.4

### ISSUE THREAD

**Issue by Kelvfimer** [libsdl-org/SDL#8363]
Hello

I'm member of the EMUELEC testing community and we are upgrading the system.

I notice when upgrading from SDL2 2.24.2 to SDL 2.28.4 using BOX64 in any commit (I tested even in the latest one available this morning [c904a9af1ca653443988ee698dec4670d4b32f88](https://github.com/ptitSeb/box64/commit/c904a9af1ca653443988ee698dec4670d4b32f88) it crashes for example with Shovel knight  game crashes . If I keep SDL2 2.24.2 it works.

Call Stack

7412|PltResolver "glXGetProcAddressARB" => return 0x84E
7412|0x1028d5bcf: Calling my_glXGetProcAddressARB (ShovelKnight)(0x1028F713E, 0x102B07606, 0x102B07609, ...) => return 
7412|0xe107e8: Calling glClearColor (/usr/lib/libGL.so.1)(0x0, 0x0, 0x780, ...) => return 0x0
NativeBT: ShovelKnight() [0x348af964]
NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7fb03ad670]
NativeBT: /usr/lib/libc.so.6(+0x7ac44) [0x7fb025ac44]
NativeBT: /usr/lib/libc.so.6(gsignal+0x14) [0x7fb02187f4]
NativeBT: /usr/lib/libSDL2-2.0.so.0(+0xd43e8) [0x7fafb843e8]
NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7fb03ad670]
NativeBT: ShovelKnight() [0x348b8738]
NativeBT: ShovelKnight() [0x34f5141c]
NativeBT: ShovelKnight(my_glXGetProcAddressARB+0x34) [0x34f4d4dc]
NativeBT: ShovelKnight() [0x34e11960]
NativeBT: ShovelKnight() [0x3488460c]
NativeBT: [0x7fa8818278]
7412|SIGSEGV @0x7fb025ac44 (???(/usr/lib/libc.so.6+0x7fb025ac44))

Attached log file 

[emuelec.log](https://github.com/libsdl-org/SDL/files/12835776/emuelec.log)

Besides there are other programas crashing due to the same issue for example executing monosquashfs mono https://github.com/PortsMaster/PortMaster-Hosting/releases/download/large-files/mono-6.12.0.122-aarch64.squashfs 

 I'm getting same callstack as with BOX64

    0x5589e6e9d8 - mono :
    0x5589e6ece4 - mono :
    0x5589e26b18 - mono :
    0x5589defa08 - mono :
    0x7fb05c9670 - linux-vdso.so.1 : kernel_rt_sigreturn
    0x7fb00bac44 - /usr/lib/libc.so.6 :
    0x7fb00787f4 - /usr/lib/libc.so.6 : gsignal
    0x7fa5fd43e8 - /usr/lib/libSDL2-2.0.so.0 :
    0x7fb05c9670 - linux-vdso.so.1 : kernel_rt_sigreturn
    0x7f95dcdd4c - Unknown
    SIGSEGV 

The same behaviour is for monosquash If I use SDL 2.24.2 everything works fine.
    

The platform used is odroid n2+ . BOX64 has been built using Ubuntu 22.04 WSL2 gcc 12.1, cmake 3.27.5 Emuelec Toolchain for amlogic-ng

Issue seemed to start after SDL 2.24.2 I tested with 2.26 and it crashes too and onwards.

Pls Can you help us? I can provide an image to debug.

thx
KR

**Comment by icculus** [comment]
This would probably be faster for you to use "git bisect" on your side than it would be for us to try to get a working BOX64 setup here.

Is this something you're comfortable trying?

**Comment by Kelvfimer** [comment]
I'm ok I will go for the latest working commit and the failing one. I will test on the second executable as it seems the box64 has another potential bug needed to be fixed.

thx @icculus

**Comment by Kelvfimer** [comment]
Hello @icculus 

The first failing commit is https://github.com/libsdl-org/SDL/commit/96a2a6b94515c5a0c920d5ffd64bf83acb74d7a8

the last working commit is https://github.com/libsdl-org/SDL/commit/fd4bb4154b034727b0504921eab78b4c07f39db7

both are in the SDL2.28.X Branch. 

I tested in the mono application. Both fails in the same way BOX64 and mono. 

There is other point that I notice, that could be related. Starting SDL2 2.26 Box64 was failing with the following error (but mono works)

[emuelecsdljoy.log](https://github.com/libsdl-org/SDL/files/12837024/emuelecsdljoy.log)

It was displaying that error until the failing commit. On the hand mono was working with no issues. I'm bringing this as I see failing commit is related to keymaps and there were and existing error with BOX64.

Starting https://github.com/libsdl-org/SDL/commit/fd4bb4154b034727b0504921eab78b4c07f39db7 BOX64 and mono had the glXGetProcAddressARB SEG FAULT issue


I wait for your feedback

thx!!

**Comment by Kelvfimer** [comment]
I implemented a patch to revert the changes of the commit and it fixes the issue on my end in all applications. So it's clear that the issue comes from there. 

I wait for you @icculus

**Comment by slouken** [comment]
That's interesting, that commit is related to keyboard work and shouldn't affect graphics at all. Can you share the patch that makes it work for you?

**Comment by Kelvfimer** [comment]
@slouken 

Basically I removed the failing commit. Yes I was surprised that the commit was about keyboard. It ends in a seg fault, no idea why

[sdlkbdtmnt.patch](https://github.com/libsdl-org/SDL/files/12848441/sdlkbdtmnt.patch)

thx for your help. BTW there is a carry on issue about pad CRC from SDL2.26 that I also reported that who knows if it's related https://github.com/libsdl-org/SDL/issues/8372

**Comment by Kelvfimer** [comment]
Hello @slouken 

Waiting for any feedback. On the other hand I would like to let you know that the issue of CRC was not related to SDL.

thx

**Comment by slouken** [comment]
I don't think we have any ideas here. We're just waiting for the results of your debugging to see why the keyboard change would cause a glX crash. I would suspect memory corruption somewhere. Have you tried running under valgrind?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.
