### ISSUE TITLE
[SDL2] SDL_VideoInit does not increment the video reference count

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8364]
Running `SDL_WasInit(SDL_INIT_VIDEO)` right after a successful `SDL_VideoInit(NULL)` returns 0 (instead of 0x20).
The tests use `SDL_VideoInit` through `SDLTest_CommonInit` and also show this behavior, but they work nonetheless.

Reproducer:
```c
#include "SDL.h"

int main (int argc, char *argv[]) {
 if (SDL_VideoInit(NULL) < 0) {
  SDL_Log("SDL_VideoInit(NULL) failed (%s)", SDL_GetError());
  return 1;
 }
 SDL_assert(SDL_WasInit(SDL_INIT_VIDEO));
 SDL_Quit();
 return 0;
}
```
I expect this app to not assert.

**Comment by slouken** [comment]
This is documented, and we've deprecated calling SDL_VideoInit() and SDL_AudioInit() directly for exactly this reason.

**Comment by madebr** [comment]
Ah yes, it's in the documentation of `SDL_QuitSubSystem`.
Thanks!
