### ISSUE TITLE
Audio channel map support

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8367]
The SDL API should finally be updated to allow flexible channel maps instead of using the hard-coded default Windows mapping.

@libsdl-org/a-team, thoughts?

**Comment by icculus** [comment]
Do we want to make this a function of SDL_AudioStreams? So it defaults to the Windows mapping, but the app can change their end to what they want, and the audio thread can change theirs to match the hardware.

(And add an extra arg to SDL_GetAudioDeviceFormat to get the current channel map, so things that want to generate audio in the right format can avoid conversions.)

**Comment by slouken** [comment]
Yes, I think so.

**Comment by icculus** [comment]
I'm putting this in the 3.0 ABI milestone, but this might be a lot of work to implement well, so we might have to decide if we can do this with some API additions later instead.
