### ISSUE TITLE
Creating of OpenGL shared context in different thread doesn't work...

### ISSUE THREAD

**Issue by Honya2000** [libsdl-org/SDL#8368]
Hello,

I'm creating SDL window and main GL context.
Next step i would like to create additional GL context in separate thread shared with the main context.
And i didn't find the way how to do this in SDL API.

So in new thread i'm calling:
                SDL_GL_SetAttribute(SDL_GL_SHARE_WITH_CURRENT_CONTEXT, 1);
                m_SDLSharedContext = SDL_CreateContext(m_SDLWindow);
                SDL_GL_MakeCurrent(m_SDLWindow, m_SDLSharedContext);

The above code doesn't work because here:
    if (_this->gl_config.share_with_current_context) {
        share_context = (HGLRC)SDL_GL_GetCurrentContext();
    } else {
        share_context = 0;
    }

SDL_GL_GetCurrentContext - gets current context from TLS storage. Which returns zero in new thread!
And I didn't find any other methods to provide main context to share with new context.

So any ways to create shared context in separate thread with SDL2?

**Comment by playmer** [comment]
I believe you need to create all of your contexts in the same thread (which admittedly doesn't appear to be documented in SDL), my code for this looks like the following:

```cpp
SDL_GL_SetAttribute(SDL_GL_SHARE_WITH_CURRENT_CONTEXT, 1);
mContext = SDL_GL_CreateContext(mWindow);
mUploadContext = SDL_GL_CreateContext(mWindow);
SDL_GL_MakeCurrent(mWindow, mContext);
```

**Comment by Honya2000** [comment]
I provided the example above. Yes i'm creating all my contexts in the same thread. And make shared context current in worker thread.
My problem not in context creation but in WebGL function accessing in worker thread.
For some reason i cannot use any functions on WebGL context in the worker!

**Comment by Honya2000** [comment]
Hmm,
In 2 weeks - no any help :(

I know WebGL supports offline GL canvas, so i should be able to access WebGL context from the worker, but how to achive this from native C++ code?

Once again i'm activating shared context in the worker and immediately try to create WebGL shader:
                int res = SDL_GL_MakeCurrent(m_SDLWindow, m_SDLShadersContext);
                if (res != 0)
                {
                    Error{} << "Failed to activate Shaders Service in worker thread!";
                }
                g_shaderId = glCreateShader(GL_VERTEX_SHADER);

glCreateShader implementation looks like this:

/** @suppress {duplicate } */ var _glCreateShader = shaderType => {
 var id = GL.getNewId(GLEM.shaders);
 GL.shaders[id] = GLctx.createShader(shaderType);
 return id;
};

And here GLctx is undefined! Why?

**Comment by icculus** [comment]
Yeah, current context is a per-thread thing, both in SDL and OpenGL itself, afaik.

It's just one of those messy OpenGL things. :/

**Comment by jrynkiew** [comment]
Below is some pseudocode that I use. It's not perfect, but it works. Could be optimized for sure. 
Define a number of threads and corresponding mutexes you want your application to support in a Global namespace

```
extern SDL_GLContext glThreadContexts[NUM_GL_THREADS];
extern std::mutex glThreadMutexes[NUM_GL_THREADS];
```

initialize the contexts on the main thread

```
for (int i = 0; i < Global::NUM_GL_THREADS; ++i) {
    Global::glThreadContexts[i] = SDL_GL_CreateContext(Global::mainWindow);
}
```

Then inside of the thread try to lock on one of the mutexes. If successful, make the context current on that thread

```
for (int i = 0; i < Global::NUM_GL_THREADS; ++i) {
    if (Global::glThreadMutexes[i].try_lock()) {
        if (SDL_GL_MakeCurrent(Global::mainWindow, Global::glThreadContexts[ctxIndex]) != 0) {
           Global::glThreadMutexes[i].unlock();
           return -1;
        }
    }
}
```

`SDL_GL_SetAttribute(SDL_GL_SHARE_WITH_CURRENT_CONTEXT, 1); ` only needs to be called once on the main thread before the main context is created. It signals that the main context is going to be shared with other contexts
