### ISSUE TITLE
SDL2 use wayland as video driver problem

### ISSUE THREAD

**Issue by GeorgeWang12356** [libsdl-org/SDL#8370]
always reporting error wayland scanner cannot be found, but wayland scanner already exists， which is a strange issue

![image](https://github.com/libsdl-org/SDL/assets/13636697/ba023dc3-d888-4dbe-be72-026b6f413967)

**Comment by madebr** [comment]
autotools gets the path of wayland-scanner here:
https://github.com/libsdl-org/SDL/blob/25b00813679997715f0b7d22eae416d284411456/configure.ac#L1697

You need to find out what `wayland-scanner.pc` file is actually used, and then look at its contents (please post it).
Then, check that the `wayland_scanner` variable it returns is a path that can be executed by SDL2's autotools (x86_64 cannot run aarch64 executables + the path actually exists)

**Comment by icculus** [comment]
Also, "no such file or directory" can also unhelpfully mean "this binary is linked to a shared library I can't find," in case that's worth exploring, too.

**Comment by madebr** [comment]
Can you bring this to the attention of the buildroot maintainers?
