### ISSUE TITLE
[SDL2] 2.0.22 can not receive SDL_FINGERxxx event when touch the screen

### ISSUE THREAD

**Issue by Jim-Carrey** [libsdl-org/SDL#8382]
OS : ubuntu 20.04
did the **evtest** on system , both hardware touchscreen and device driver supported multi-touch 
normally we could receive both Mouse and Finger event when we touch the screen like this :
> Mouse Down | Up | Motion event
Mouse Down | Up | Motion event
Finger Down: (0.429266, 0.185301)
Mouse Down | Up | Motion event
Finger Up: (0.429266, 0.185301)
Mouse Down | Up | Motion event
Mouse Down | Up | Motion event
Finger Down: (0.515623, 0.262095)
Mouse Down | Up | Motion event
Finger Up: (0.515623, 0.262095)

it's work ok in version   **SDL2  2.0.20**

but in   **SDL2  2.0.22**

 (same system environment and same test program except SDL version), only could receive Mouse event when touch screen like this :

> Mouse Down | Up | Motion event
Mouse Down | Up | Motion event
Mouse Down | Up | Motion event
Mouse Down | Up | Motion event
Mouse Down | Up | Motion event

**This problem exists in versions 2.0.22 and higher(tested 2.26.0 also got problem)**

test program as follows:
```
#include <stdio.h>
#include <stdlib.h>
#include <SDL2/SDL.h>

int main(int argc, char* argv[]) {
    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS);

    SDL_Window* window = SDL_CreateWindow("Multi-Touch Test", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 800, 600, SDL_WINDOW_SHOWN);
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, 0);

    SDL_Event event;
    int quit = 0;

    while (!quit) {
        while (SDL_PollEvent(&event)) {
            switch (event.type) {
                case SDL_QUIT:
                    quit = 1;
                    break;
                case SDL_MOUSEMOTION:
                case SDL_MOUSEBUTTONDOWN:
                case SDL_MOUSEBUTTONUP:
                    printf("Mouse Down | Up | Motion event\n");
                    break;
                case SDL_FINGERDOWN:
                    printf("Finger Down: (%f, %f)\n", event.tfinger.x, event.tfinger.y);
                    break;
                case SDL_FINGERUP:
                    printf("Finger Up: (%f, %f)\n", event.tfinger.x, event.tfinger.y);
                    break;
                case SDL_FINGERMOTION:
                    printf("Finger Motion: (%f, %f)\n", event.tfinger.x, event.tfinger.y);
                    break;
                default:
                    break;
            }
        }

        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
    }

    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}

```

**Comment by slouken** [comment]
What was the issue?
