### ISSUE TITLE
RGB555 routines in SDL_blit_A.c don't account for destination alpha channels.

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#8401]
Routines like `BlitARGBto555PixelAlpha` are currently used for both RGB555 and ARGB1555 destinations, but the functions don't preserve the alpha channel for the destination surface, causing it to be zeroed out and leading to visual issues if the alpha channel is used later.

This was originally observed in SDL 1.2 when running on the Nintendo DS, but looking at the code suggests that SDL2 and SDL3 have the exact same issue.

**Comment by slouken** [comment]
Fixed, thanks!
