### ISSUE TITLE
Assertion failure at SDL_CaptureAudioThreadIterate

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8402]
- Run testaudio
- Right-drag the default capture device to create a logical device.
- Right drag the headphones icon to create an audio stream of sample.wav
- Drop audio stream on logical device to append more audio data to the end of it.

```
Assertion failure at SDL_CaptureAudioThreadIterate (/home/icculus/projects/SDL/src/audio/SDL_audio.c:1061), triggered 1 time:
  'stream->src_spec.channels == device->spec.channels'
```

**Comment by addiment** [comment]
Would like to re-open this, I just built SDL3 from source and am experiencing this issue both in my own code and in the test code. Currently on Debian 12. Running the `testaudiocapture` program and changing the audio input device will cause this same error message to show up whenever the window is clicked (i.e. to resume the input stream). Perhaps I am using the API incorrectly, but given that the test program also crashes, I don't believe this to be the case.

```
Assertion failure at SDL_CaptureAudioThreadIterate (/home/addiment/Projects/SDL/src/audio/SDL_audio.c:1257), triggered 4 times:
  'stream->src_spec.channels == device->spec.channels'
```

If "ignore" is pressed, execution resumes, but audio cannot be recorded or played back, and the "triggered X times" increments.

**Comment by icculus** [comment]
This should be resolved now, sorry for the delay on this!
