### ISSUE TITLE
Relative pathnames prefer executable location over current working directory

### ISSUE THREAD

**Issue by markjreed** [libsdl-org/SDL#8403]
In this setup:

1. application launched from command line
2. attempts to read file via relative pathname (e.g. bare filename)
3. a file exists at that path relative to both the current working directory and the directory containing the executable

Then any access to the filename through SDL (e.g. `SDL_RWFromFile(filename)`) will find the one located relative to the executable, not the current working directory.  Which is exactly backwards from a POSIX perspective; the local file should take precedence, and the executable directory only searched as a fallback. 

This should ideally be corrected, but if this is the desired behavior, it needs to be documented clearly.

I created a simple `cat` emulator that uses `SDL_RWFromFile`/`SDL_RWread` to display the contents of a file, to demonstrate the problem:

    $ cat hello.txt                                              # standard cat
    I'm the hello.txt in the current directory.
    $ cat bin/hello.txt                                          # with other pathname
    I'm the hello.txt in the bin directory.
    $ bin/sdlcat hello.txt                                       # using SDL routines
    I'm the hello.txt in the bin directory.

**Comment by madebr** [comment]
I cannot reproduce:
```
echo "root">txt; echo "subdir">test/txt; test/sdlcat txt
INFO: read : root
```

source:
```c
#ifdef USE_SDL2
#include "SDL.h"
#else
#include <SDL3/SDL.h>
#endif

int main(int argc, char *argv[]) {
    if (!argv[1]) {
        SDL_Log("Missing argument");
        return 1;
    }
    SDL_RWops *rwops = SDL_RWFromFile(argv[1], "rb");
    if (!rwops) {
        SDL_Log("Could not open %s (%s)", argv[1], SDL_GetError());
    }
    {
        char buffer[2048];
        size_t count;
#ifdef USE_SDL2
        while ((count = SDL_RWread(rwops, buffer, 1, sizeof(buffer))) != 0) {
#else
        while ((count = SDL_RWread(rwops, buffer, sizeof(buffer))) != 0) {
#endif
            SDL_Log("read : %.*s", (int)count, buffer);
        }
    }
    SDL_RWclose(rwops);
    return 0;
}
```

**Comment by markjreed** [comment]
macOS with SDL2.  When I compile your code with USE_SDL2, the output is "subdir".

**Comment by icculus** [comment]
I think we do something weird on macOS because double-clicking an app bundle in the Finder will launch it with a current working directory of "/" and we were attempting to combat that specific problem.

**Comment by markjreed** [comment]
I looked at the code, and it simply try the filename as provided unless it's an absolute path. It would seem to be a pretty simple fix to always (modulo POSIX) try just a regular fopen first, and only fall back to the other location options if that fails.

**Comment by slouken** [comment]
Our plan for SDL 3.0 is to remove the changing of working directory entirely. Your application should never rely on the working directory on any platform, and should use well known directories with APIs in SDL_filesystem.h

**Comment by icculus** [comment]
I looked at this more closely: the cwd stuff has been gone for macOS since SDL 2.0.0 (when we removed the mac-specific SDLMain.m startup code), but the thing about absolute paths is wrong, too, since that's in an Android-specific block of code.

This is the actual code that macOS runs:

https://github.com/libsdl-org/SDL/blob/release-2.30.5/src/file/cocoa/SDL_rwopsbundlesupport.m#L28-L63

This is where all the directory choice stuff is happening.

I think it wouldn't be wrong to remove this for SDL3 (for macOS, probably not iOS), but removing this in SDL2 will probably break things. But we could probably offer a hint to say "don't do this bundle stuff, just use fopen() directly on the string" and be done with it.

**Comment by icculus** [comment]
Haiku still changes the cwd on startup, and that could be worth fixing, separately.

**Comment by icculus** [comment]
Okay, SDL3 now has the Apple-specific behavior removed (it uses the specified path unadjusted), and SDL2 now has a hint to turn off the behavior:

```c
SDL_SetHint(SDL_HINT_APPLE_RWFROMFILE_USE_RESOURCES, "0");
```

sdl2-compat updated to support the new hint and the usual SDL2 behavior, too.
