### ISSUE TITLE
Problem w/ iPad Air 5th gen, iOS 17 screen touch and Mouse coordinates 

### ISSUE THREAD

**Issue by w1ebr** [libsdl-org/SDL#8407]
Running the sample demo IMGUI standalone program with the menus (rendering via SDL2) screen touch location and mouse location are reported as approx. half of the actual physical location of the touch or mouse pointer (when sharing the keyboard and mouse on the MacBook wirelessly with the iPad). Is there a flag to fix this? The window was created with option SDL_WINDOW_ALLOW_HIGHDPI.

**Comment by slouken** [comment]
The window coordinates are half the size of the render target. You just need to scale convert them when you translate them into your view.

SDL3 provides a function to easily do this: [SDL_ConvertEventToRenderCoordinates](https://github.com/libsdl-org/SDL/blob/bf269571fc484afe5155f2f5e5f269dd328ce6f6/include/SDL3/SDL_render.h#L937)
