### ISSUE TITLE
SDL3 Wiki `SDL_CreateAudioStream()` describes return value as `-1` or `0` instead of a pointer to the `SDL_AudioStream`

### ISSUE THREAD

**Issue by Szahu** [libsdl-org/SDL#8409]
Hi, I have been reading the SDL3 Wiki here https://wiki.libsdl.org/SDL3/SDL_CreateAudioStream, and it seems that under the **Return Value** it says "*Returns 0 on success, or -1 on error.*,"  whereas the return type of the function is `SDL_AudioStream*`. 
It's a minor thing but I thought I'd let you know, cheers!

**Comment by icculus** [comment]
Fixed in 142366c837b506dda9563e34d31c229017de77af, thanks!
