### ISSUE TITLE
SDL_WINDOW_UTILITY flag is not working

### ISSUE THREAD

**Issue by Ivan-753** [libsdl-org/SDL#8410]
Linux 5.15
SDL3 (current main branch, no release version)

The SDL_WINDOW_UTILITY flag for SDL_CreateWindow() does nothing.

SDL_WINDOW_SKIP_TASKBAR works well on the same system with a SDL2 (2.28.1).

**Comment by Kontrabant** [comment]
Can you try #8483 and see if it fixes your problem?

**Comment by Ivan-753** [comment]
> Can you try #8483 and see if it fixes your problem?

Thank you very much!
It solved my issue)

I tried this commit ( https://github.com/libsdl-org/SDL/tree/1533fd8f1e5f04ba37e71848aefc63f9c93d2d29 ) and it says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.", so there is no changes for main branch yet.
Hope they will merge your pull request soon.
