### ISSUE TITLE
[Question] __driDriverGetExtensions_d3d12 on a Linux system

### ISSUE THREAD

**Issue by Pentarctagon** [libsdl-org/SDL#8411]
Hi,

For Battle for Wesnoth, I was doing some profiling, and in the results from gperftools it's showing a significant amount of time spent in `__driDriverGetExtensions_d3d12` even though I'm on a Linux system (Mint 21.2, SDL 2.0.20). I was pretty confused to see something related d3d12 show up in the profiling results, so I was just wondering if this is normal and expected? Or is the profiler potentially just giving wrong results?

One of the profiling results as an example:
https://user-images.githubusercontent.com/3030250/276737124-f4d9770a-bd56-412e-bd61-637ad6be619f.gif

**Comment by icculus** [comment]
I think this is probably just the profiler giving wrong results (likely...a whole bunch of OpenGL internals ended up getting reported as an arbitrary symbol, maybe?).

**Comment by Pentarctagon** [comment]
Alright, thanks!
