### ISSUE TITLE
SDL_AddGamepadMappingsFromFile

### ISSUE THREAD

**Issue by SystemBuilding** [libsdl-org/SDL#8412]
I'm on an Ubuntu Linux system (x86_64), SDL3.

When I used `SDL_AddGamepadMappingsFromFile("resources/gamecontrollerdb.txt");`  I was immediately getting assertion errors like this: 

> WARN: 
> 
> Assertion failure at SDL_AssertJoysticksLocked (/home/michael/src/SDL/src/joystick/SDL_joystick.c:190), triggered 1 time:
>   'SDL_JoysticksLocked()'

Ignoring the error just caused it to fire again. I added a call to `SDL_LockJoysticks();` just above `SDL_AddGamepadMappings(etc);` which made the errors go away

(I just now did a pull-rebuild-install on my SDL3 libs to confirm it's occurring on the newest version.)

**Comment by SystemBuilding** [comment]
I edited my copy of gamecontrollerdb.txt to only include Linux platform text, which got the file size down to 159K in size. This did not noticeably speed up the load time.

**Comment by slouken** [comment]
Fixed, thanks!
