### ISSUE TITLE
Documentation: Clarify how to get borderless fullscreen

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#8413]
The migration guide states the following:

> `SDL_WINDOW_FULLSCREEN_DESKTOP` has been removed, and you can call `SDL_GetWindowFullscreenMode()` to see whether an exclusive fullscreen mode will be used or the fullscreen desktop mode will be used when the window is fullscreen.

But `SDL_GetWindowFullscreenMode()`'s documentation doesn't make it clear that the "desktop mode" is the non-exclusive borderless fullscreen mode (if that is indeed what it is, since I might be understanding it wrong). I would suggest clarifying the instructions in the migration guide and also note it down in the header comment / documentation.

**Comment by slouken** [comment]
The documentation has been clarified, thanks!
