### ISSUE TITLE
Vulkan SDK packaging for .pdb files, debug libraries

### ISSUE THREAD

**Issue by lunarpapillo** [libsdl-org/SDL#8415]
The **Windows Vulkan SDK** would like to start packaging `.pdb` files and `Debug` binaries for the **SDL2** libraries, at user request.  I have a few questions.  I'm using the latest **SDL2** release `release-2.28.4`.

- I notice that `.pdb` files are not part of the `install` target.  Is there a reason for this?  (I did find the `.pdb` files in the build directory.)
- The `install` target includes `bin\SDL2.dll` and `lib\SDL2.lib`, `lib\SDL2-static.lib`, `lib\SDL2main.lib`, and `lib\SDL2_test.lib`.  The build directory creates `SDL2.pdb`, `SDL2-static.pdb`, `SDL2main.pdb`, and `SDL2_test.pdb`.  Is the built `SDL2.pdb` supposed to be associated with `SDL2.dll` or with `SDL2.lib`?  Why aren't two different `.pdb` files created?
- I notice that the `Debug` build does not set `CMAKE_DEBUG_POSTFIX=d`, so the debug libraries end up with the same names as their release counterparts.  Is this intentional?  Does **SDL** intend to ship debug libraries in different directories than `bin\` and `lib\`?

**Comment by madebr** [comment]
Coincidentally, [just a week ago](https://github.com/libsdl-org/SDL/commit/1ae33f675118f32b6faab7645f140bab26d432d5), we enabled installation of pdb's on SDL3, but only for the shared library. Perhaps we should also install ones for the static libraries.

>  I notice that `.pdb` files are not part of the `install` target.  Is there a reason for this?  (I did find the `.pdb` files in the build directory.)

No reason, SDL2 MSVC releases are not created using the CMake script, so we never felt the need.
et's add this.

>  The `install` target includes `bin\SDL2.dll` and `lib\SDL2.lib`, `lib\SDL2-static.lib`, `lib\SDL2main.lib`, and `lib\SDL2_test.lib`.  The build directory creates `SDL2.pdb`, `SDL2-static.pdb`, `SDL2main.pdb`, and `SDL2_test.pdb`.  Is the built `SDL2.pdb` supposed to be associated with `SDL2.dll` or with `SDL2.lib`?  Why aren't two different `.pdb` files created?

`SDL2.lib` is the [import library](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-creation#using-an-import-library) of `SDL2.dll`. It does not contain any executable SDL code, just references to SDL symbols.
By linking to `SDL2.lib`, your program will load the SDL symbols from `SDL2.dll`. `SDL2.pdb` is associated with `SDL2.dll`.
You can regenerate the `SDL2.lib` import library and still have a compatible `SDL2.pdb` for the original `SDL2.dll`, but you cannot use a different `SDL2.dll`.

> I notice that the `Debug` build does not set `CMAKE_DEBUG_POSTFIX=d`, so the debug libraries end up with the same names as their release counterparts.  Is this intentional? 

What do you mean? `CMAKE_DEBUG_POSTFIX=d` should add the `d` to all libraries + executables, and also pdb's.
I'm not on Windows rn, but it would look like a cmake quirk to me if the pdb of a debug library does not have the `d` suffix.
By default, release mode does not create pdb files, so there is no clash there.

FYI, we abandoned `d` suffix'es for debug libraries in SDL3. These suffixes were CMake-only.
The Visual Studio project never added these.

> Does **SDL** intend to ship debug libraries in different directories than `bin\` and `lib\`?

In the patch above, I simply installed the pdb in the same directory as the dll (`/bin`), so the debugger can find it.
But I'm not sure what to do with static libraries.
What do you think about putting the pdb's in the same directory as their corresponding library?
So:
- `/bin/SDL3.dll` and `/bin/SDL3.pdb`
- `/lib/SDL3-static.lib` and `/lib/SDL3-static.pdb`
- `/lib/SDL3_test.lib` and `/lib/SDL3_test.pdb`

**Comment by lunarpapillo** [comment]
> Coincidentally, [just a week ago](https://github.com/libsdl-org/SDL/commit/1ae33f675118f32b6faab7645f140bab26d432d5), we enabled installation of pdb's on SDL3, but only for the shared library. Perhaps we should also install ones for the static libraries.

Convenient!  I'm not sure whether the `.pdb` files are important for static libraries - I know some static libraries already contain debug information - but they seem to be built, so it seems like shipping them can't do harm, right?
 
> No reason, SDL2 MSVC releases are not created using the CMake script, so we never felt the need. et's add this.

Woot!  Thanks.
 
> `SDL2.lib` is the [import library](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-creation#using-an-import-library) of `SDL2.dll`. It does not contain any executable SDL code, just references to SDL symbols. By linking to `SDL2.lib`, your program will load the SDL symbols from `SDL2.dll`. `SDL2.pdb` is associated with `SDL2.dll`. You can regenerate the `SDL2.lib` import library and still have a compatible `SDL2.pdb` for the original `SDL2.dll`, but you cannot use a different `SDL2.dll`.

Ah, gotcha, sorry, I'd thought `SDL2.lib` was the static equivalent of `SDL2.dll`.  But that's probably `SDL2-static.lib`, yes?

> > I notice that the `Debug` build does not set `CMAKE_DEBUG_POSTFIX=d`, so the debug libraries end up with the same names as their release counterparts.  Is this intentional?
> 
> What do you mean? `CMAKE_DEBUG_POSTFIX=d` should add the `d` to all libraries + executables, and also pdb's. 

Sorry, I meant that the fact that the flag wasn't set up in the repository's own CMake files suggested that munging the debuggable library names by externally modifying the flag wasn't the intended means of distribution for this repository.

If y'all have your own convention for shipping debuggable libraries (in different directories from the release binaries, maybe?) I'd rather follow that than apply a different convention (though there is some pressure from the shader libraries all following the `d` convention).

> FYI, we abandoned `d` suffix'es for debug libraries in SDL3. These suffixes were CMake-only. The Visual Studio project never added these.

So debug libraries get installed into different directories, then?

Should we consider switching to SDL3 for the Vulkan SDK instead of SDL 2?

> In the patch above, I simply installed the pdb in the same directory as the dll (`/bin`), so the debugger can find it. But I'm not sure what to do with static libraries. What do you think about putting the pdb's in the same directory as their corresponding library? So:
> 
>     * `/bin/SDL3.dll` and `/bin/SDL3.pdb`
> 
>     * `/lib/SDL3-static.lib` and `/lib/SDL3-static.pdb`
> 
>     * `/lib/SDL3_test.lib` and `/lib/SDL3_test.pdb`

That seems reasonable.

Thanks for your time and attention!

**Comment by madebr** [comment]
> Convenient! I'm not sure whether the `.pdb` files are important for static libraries - I know some static libraries already contain debug information - but they seem to be built, so it seems like shipping them can't do harm, right?

I don't have much experience with pdb's in general so I can't help much. But distributing them does not harm, it only consumes disk space.

> Sorry, I meant that the fact that the flag wasn't set up in the repository's own CMake files suggested that munging the debuggable library names by externally modifying the flag wasn't the intended means of distribution for this repository.

Looks like we  set the `DEBUG_POSTFIX` property for every target (so we don't use `CMAKE_DEBUG_POSTFIX`)
https://github.com/libsdl-org/SDL/blob/44d87210870b60237e762ac6117f9d7c2e62c6a2/CMakeLists.txt#L3438

> So debug libraries get installed into different directories, then?

I think so.
You will probably want to reconfigure SDL slightly different for release and debug:
```
cmake -S /sdl -B /sdl_build_release -GNinja -DCMAKE_BUILD_TYPE=Release -DSDL_CMAKE_DEBUG_POSTFIX= -DCMAKE_INSTALL_PREFIX=/sdl_install
cmake --build /sdl_build_release
cmake --install /sdl_build_release
cmake -S /sdl -B /sdl_build_debug -GNinja -DCMAKE_BUILD_TYPE=Debug -DSDL_CMAKE_DEBUG_POSTFIX= -DCMAKE_INSTALL_PREFIX=/sdl_install -DCMAKE_INSTALL_LIBDIR=lib/debug -DCMAKE_INSTALL_BINDIR=bin/debug -DSDL_INSTALL_CMAKEDIR=cmake
cmake --build /sdl_build_debug
cmake --install /sdl_build_debug
```
Untested, but this should create a prefix like this:
```
/sdl_install 
├── bin
│   ├── debug
│   │   ├── SDL2.dll
│   │   └── SDL2.pdb
│   ├── SDL2.dll
│   └── SDL2.pdb
├── cmake
│   ├── SDL3Config.cmake
│   ├── SDL3sharedTargets.cmake
│   ├── SDL3sharedTargets-debug.cmake
│   ├── SDL3sharedTargets-release.cmake
│   ├── SDL3staticTargets.cmake
│   ├── SDL3staticTargets-debug.cmake
│   └── SDL3staticTargets-release.cmake
├── include
│   └── SDL2
│       └── SDL.h
└── lib
    ├── debug
    │   ├── SDL2.lib
    │   ├── SDL2-static.lib
    │   └── SDL2-static.pdb
    ├── SDL2.lib
    ├── SDL2-static.lib
    └── SDL2-static.pdb
```
Having the cmake scripts for release and debug in one directory, makes it easier to use by cmake.

> Should we consider switching to SDL3 for the Vulkan SDK instead of SDL 2?

SDL3 is still in development, so not yet please.

**Comment by madebr** [comment]
Looks like CMake does not support [`$<TARGET_PDB_FILE>`](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_PDB_FILE) for static library targets.

https://gitlab.kitware.com/cmake/cmake/-/issues/16932

**Comment by slouken** [comment]
PDBs are not necessary for static libraries. They already contain the symbols needed.
PDBs are typically not shipped with the application, but held by the developer to diagnose crash dumps in shipping products. In the case of Vulkan, it may make sense to include the PDBs, but including the source is probably even more useful.

**Comment by madebr** [comment]
Do the object files in static libraries contain sufficient information to connect some offset in a symbol to a file location?

@lunarpapillo 
I pushed https://github.com/libsdl-org/SDL/commit/90255914a848a6ad4dc62dfb95b9a73a49b03ee6 which will install pdb's for SDL2.
I'm hesitant to queue it for the next 2.28.x release as it changes install behavior.

**Comment by slouken** [comment]
> Do the object files in static libraries contain sufficient information to connect some offset in a symbol to a file location?

Yes, static libraries typically have symbols which can be stripped out of the final executable.

**Comment by madebr** [comment]
Thanks slouken.

@lunarpapillo
Do you still have unanswered questions?
If not, can we close this issue?

**Comment by madebr** [comment]
> > Looks like CMake does not support [$<TARGET_PDB_FILE>](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_PDB_FILE) for static library targets.
> 
> Hmmm, but yet a normal `RelWithDebInfo` build does seem to produce `SDL2-static.pdb`, `SDL2main.pdb`, and `SDL2_test.pdb`.... ?

Looks like you're right.
When using ninja, a pdb of the static library is created in a  `CMakeFiles\SDL3-static.dir` subdirectory.
After moving this `SDL3-static.pdb` to a different directory, manually compiling and linking SDL3's testspriteminimal against `SDL3-static.lib` emits a lot of warnings:
```
cl /nologo /c path/to/test/testspriteminimal.c  /I path/to/include
link /nologo testspriteminimal.obj path/to/SDL3-static.lib /subsystem:windows /out:testspriteminimal.exe /debug kernel32.lib user32.lib gdi32.lib winmm.lib imm32.lib ole32.lib oleaut32.lib version.lib uuid.lib advapi32.lib setupapi.lib shell32.lib dinput8.lib
```
emits:
```
SDL3-static.lib(SDL_dynapi.c.obj) : warning LNK4099: PDB 'SDL3-static.pdb' was not found with 'SDL3-static.lib(SDL_dynapi.c.obj)' or at 'C:\Users\maarten\source\repos\SDL\cmake-build-debug\prefix\lib\SDL3-static.pdb'; linking object as if no debug info
SDL3-static.lib(SDL_log.c.obj) : warning LNK4099: PDB 'SDL3-static.pdb' was not found with 'SDL3-static.lib(SDL_log.c.obj)' or at 'C:\Users\maarten\source\repos\SDL\cmake-build-debug\prefix\lib\SDL3-static.pdb'; linking object as if no debug info
...
```

Building SDL3-static with [`/Z7`](https://learn.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format) made the link errors go away.
Unless we [add custom code the install script](https://cmake.org/cmake/help/latest/command/install.html#code) that can be buggy, I think it's best to wait until CMake adds a [`$<TARGET_COMPILE_PDB_FILE` genex](https://gitlab.kitware.com/cmake/cmake/-/issues/25244).

> Thank you! I understand your hesitation. Perhaps we could either have a CMake flag (e.g. `-DSDL_INSTALL_FOR_VULKAN_SDK=ON` or `-DSDL_INSTALL_FOR=VulkanSDK`) or a separate install target (e.g. `vulkan-sdk-install` instead of `install`)? Either of those would maintain backward-compatible behavior while still leaving y'all in control of what is installed and where in the Vulkan SDK.

I think it would be easier for you to manually copy over the pdb's in a post-install step.

> One final question, to make sure I understand correctly. It's your intention to have debuggable SDL libraries shipped in different `debug` directories in the Vulkan SDK, without the `d` postfix, yes? (I ask for explicit confirmation because I know I'm going to be questioned about it. ;-)

Yes, no more `d` suffix for debug libraries. These suffixes were a cmake-ism not applied by autotools. It was there for the Visual Studio generator that can build Release and Debug binaries with the same project in one location.
Because SDL would not be the only "victim" of these collisons, people should configure cmake with [`CMAKE_<CONFIG>_POSTFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIG_POSTFIX.html) themselves.
In https://github.com/libsdl-org/SDL/issues/8415#issuecomment-1774097617, by putting the debug variants in a debug subdirectory, no collision happens.

For `SDL3.dll`, SDL does its best to not use Microsoft's C runtime. So there's no `/MD` vs `/MT` vs `/MDd` vs `/MTd` conflict there. For the static library, the MS C library is needed for [a few compiler intrinsics](https://github.com/libsdl-org/SDL/blob/main/src/stdlib/SDL_mslibc.c).

**Comment by slouken** [comment]
It sounds like this is resolved, @lunarpapillo, do you have any other questions?

**Comment by lunarpapillo** [comment]
> I think it would be easier for you to manually copy over the pdb's in a post-install step.

I've no problem with that, if y'all are comfortable with not having repository-level control over what is installed for your repository and where.  It sounds like you are.

> Yes, no more d suffix for debug libraries.

> Because SDL would not be the only "victim" of these collisons, people should configure cmake with [`CMAKE_<CONFIG>_POSTFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIG_POSTFIX.html) themselves.

I'm not quite sure how to put these observations together... is your preference:
- **A** to ship a `bin\debug\` directory for debuggable SDL libraries and `.pdb`s (recognizing that most of the other **Vulkan SDK** debuggable libraries have a `d` postfix)
- **B** to configure `CMAKE_DEBUG_POSTFIX=d` ourselves and ship debuggable SDL libraries and `.pdb`s in `bin\`, like the other **Vulkan SDK** libraries

I'm happy to implement either.  I don't think it's a serious issue either way for users (as no users who are using **SDL** out of the **Vulkan SDK** can be using debug libraries currently, and the location of the debug binaries is a one-time project configuration step).

As y'all will have to support any users with issues, if you have a strong preference one way or the other, we'll do that.  I'm divided on whether you might see more issues because the **SDL** libraries don't have debuggable binaries that look like other SDK debuggable binaries, or because someone calls in with a problem in `SDL2d.dll` and your support people don't know exactly what that library is supposed to be...

**Comment by madebr** [comment]
> I've no problem with that, if y'all are comfortable with not having repository-level control over what is installed for your repository and where. It sounds like you are.

I'll look at this for SDL3. (perhaps it can be backported)

> > Yes, no more d suffix for debug libraries.
> 
> > Because SDL would not be the only "victim" of these collisons, people should configure cmake with [`CMAKE_<CONFIG>_POSTFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIG_POSTFIX.html) themselves.
> 
> I'm not quite sure how to put these observations together... is your preference:
> 
> * **A** to ship a `bin\debug\` directory for debuggable SDL libraries and `.pdb`s (recognizing that most of the other **Vulkan SDK** debuggable libraries have a `d` postfix)
> 
> * **B** to configure `CMAKE_DEBUG_POSTFIX=d` ourselves and ship debuggable SDL libraries and `.pdb`s in `bin\`, like the other **Vulkan SDK** libraries

For the SDL2 dll, it is preferable to don't add a `d` suffix so people can switch a release SDL2.dll with a debug SDL2.dll without rename (they are compatible after all).
We have not made anything "official" about `d` suffixes for debug builds, and it is nowhere documented. So I'd go with option **A**.
SDL3's cmake script removed the `d` suffix, so you're forward compatible.

> I'm happy to implement either. I don't think it's a serious issue either way for users (as no users who are using **SDL** out of the **Vulkan SDK** can be using debug libraries currently, and the location of the debug binaries is a one-time project configuration step).

Indeed, when you create it using similar commands of https://github.com/libsdl-org/SDL/issues/8415#issuecomment-1774097617, then `SDL3Config.cmake` will automatically switch between Debug and Release.

> As y'all will have to support any users with issues, if you have a strong preference one way or the other, we'll do that. I'm divided on whether you might see more issues because the **SDL** libraries don't have debuggable binaries that look like other SDK debuggable binaries, or because someone calls in with a problem in `SDL2d.dll` and your support people don't know exactly what that library is supposed to be...

I think having a pdb available for the dll is the important thing for a (good) stacktrace. A pdb of a release pdb would be less precise, but sufficient.
I haven't seen a lot of SDL bug reports with a stack trace thanks to a pdb (SDL does not crash :p).

**Comment by madebr** [comment]
I just pushed commits for SDL2 and SDL3 that installs pdbs for static libraries as well.
