### ISSUE TITLE
Clarification on SDL_WaitEventTimeout - does it block?

### ISSUE THREAD

**Issue by hummy123** [libsdl-org/SDL#8416]
Hi there. I appreciate all of the impressive work and effort that's been going into SDL. 

Just a question about the function I referred to ([docs link here](https://wiki.libsdl.org/SDL3/SDL_WaitEventTimeout)). 

If I understand correctly, this function waits for the specified amount of time and then, when the timeout is over, SDL will call the event loop again with all of the events that have gathered during the timeout period all at once. 

This is in contrast to GLFW's [glfwWaitEventsTimeout](https://www.glfw.org/docs/3.3/group__window.html#ga605a178db92f1a7f1a925563ef3ea2cf) function which does not block but `puts the thread to sleep until at least one event has been received, or until the specified number of seconds have elapsed. It then processes any received events`.

Is my understanding correct? I personally prefer how the GLFW function works (it's a big advantage in my opinion), but everything else is making SDL look more attractive to me. 

I recall reading (not sure if it still the case) SDL_WaitEventTimeout uses the blocking SDL_Delay under the hood (not sure if it is still the case).

Would appreciate any clarification about this particular function (and, if it does work as I described, I would be happy to see it implemented closer to how GLFW's function is although that's a big ask).

**Comment by slime73** [comment]
SDL_WaitEventTimeout behaves similarly to glfwWaitEventsTimeout: it returns quickly if there's a new event before the timeout. If there have been no events by the time the timeout is reached then it returns a failure status.

**Comment by hummy123** [comment]
Oh, I understand. Then there's nothing else that makes me think I would regret choosing SDL. Thanks for the help!
