### ISSUE TITLE
Logitech F310 broke on macOS after 2.24.2

### ISSUE THREAD

**Issue by alicedb2** [libsdl-org/SDL#8424]
I'm using `test/testgamecontroller` compiled on MacOS Ventura 13.6.

Every buttons (except `guide`) on the F310 are working correctly with 2.0.22 and 2.24.2, but in the next tagged release 2.25.1 (2.26.0 RC1) the `back`, `start` and `rightstick` press do not register at all and what should be a `leftstick` press registers as `guide` instead. This bug is still present as of 2.28.4.

**Comment by Squall-Leonhart** [comment]
As more info, the existing profile was based on the prior driver supporting X mode, the current instance of MacOS only works in D mode.

**Comment by slouken** [comment]
I just tried the F310 and it's working properly here, except the guide button doesn't work. I'm pretty sure 2.25.1 turned on MFI support, as Apple added support for the Logitech controllers recently.

I'm not sure how X mode worked for you, since macOS blocks access to Xbox controllers, which is what the F310 looks like in X mode.

Are you able to debug SDL and figure out what's going on?

**Comment by Squall-Leonhart** [comment]
> I'm not sure how X mode worked for you, since macOS blocks access to Xbox controllers, which is what the F310 looks like in X mode.

the F310 was previously supported in X mode using [360Controller](https://github.com/360Controller/360Controller/) on Monterey.

Ventura+ has issues even in D mode that required following this informational, https://gist.github.com/jackblk/8138827afd986f30cf9d26647e8448e1

**Comment by alicedb2** [comment]
> Ventura+ has issues even in D mode that required following this informational, https://gist.github.com/jackblk/8138827afd986f30cf9d26647e8448e1

I had to do that after buying the controller otherwise it just wouldn't work at all. If you touch that little switch at the back by mistake you have to do it again.

Here's something weird I found just yesterday. When I fire-up `testgamecontroller` the situation is as I explained, back/start/rightstick button don't work and the leftstick button registers as guide. If I plug and unplug the controller while `testcontroller` is still running then I get
```
INFO: Game controller device 0 removed.
INFO: Game controller device 1 added.
INFO: Opened game controller Logitech Dual Action
INFO: Controller 1 axis leftx changed to -2442
INFO: Controller 1 axis leftx changed to -643
INFO: Controller 1 axis lefty changed to 3726
INFO: Controller 1 axis lefty changed to 1413
INFO: Controller 1 axis rightx changed to -2185
INFO: Controller 1 axis rightx changed to -900
INFO: Controller 1 axis righty changed to 3212
INFO: Controller 1 axis righty changed to 1413
INFO: Controller 1 axis leftx changed to 128
INFO: Controller 1 axis lefty changed to -129
INFO: Controller 1 axis rightx changed to 128
INFO: Controller 1 axis righty changed to -129
INFO: Game controller device 2 added.
INFO: Opened game controller Logitech Dual Action
```
and the problem disappear and all buttons start working normally (except guide). Then if I unplug/plug again it will do one of two things: (1) if I get a clean
```
[unplug]
INFO: Game controller device N removed.
[plug]
INFO: Game controller device N+1 added.
INFO: Opened game controller Logitech Dual Action
```
then the controller is back to being buggy. But if instead I get (2) a bunch of leftx/rightx glitches at unplugging, then I will get a bunch of leftx/rightx glitches at plugging and the controller will work again with logs that look like this
```
INFO: Game controller device N removed.
INFO: Controller N-1 axis leftx changed to -2956
INFO: Controller N-1 axis lefty changed to 2955
       [bunch more glitches on controller N-1]
INFO: Game controller device N-1 removed.
INFO: Game controller device N+1 added.
INFO: Opened game controller Logitech Dual Action
       [bunch more glitches on controller N+1]
INFO: Game controller device N+2 added.
INFO: Opened game controller Logitech Dual Action
```
Notice the N/N-1/N+1/N+2 pattern. Whether it chooses to unplug/glitch/plug/glitch and work or unplug/plug and be buggy appears to be random.

**Comment by alicedb2** [comment]
Ok, here's a summary of what I found. Glitches always appear as a bunch of stray leftx/lefty/rightx/righty.

- For release 2.24.2, no controller is added when firing up `testgamecontroller`. Eventually after unplugging/plugging a bunch of times the controller gets recognize, you get a glitch, and then all buttons start working normally. Sometimes no controller is detected when plugging back and of course nothing works again.
- For releases 2.25.1, 2.26.1, the intermittent unplug/plug/glitch trick described in my previous comment works.
- For releases 2.26.2 and 2.26.3, first time you fire up `testgamecontroller` all buttons work normally except that `start` registers as `guide`. If you get a glitch during both unplug/plug then the buttons all work correctly except that every once in a while for a single press `start` will register as `guide` and then will go back to register as `start`. If you don't get a glitch during plugging then you're back to `start` registering as `guide and all other buttons working normally.
- With 2.26.4 you're back to the unplug/plug/glitch trick described before working.
- For all remaining releases (2.26.5, 2.27.1, 2.28.0, 2.28.1, 2.28.2, 2.28.3, 2.28.4, 2.28.5) there are no more glitches when you unplug/unplug and the controller gets correctly removed and added back, but you're stuck with back/start/rightstick click not registering and leftstick click registering as guide.

Make it make sense

**Comment by slouken** [comment]
Thanks for the great info. I have an issue open with Apple on this now.

**Comment by alicedb2** [comment]
Just to make things concrete, here's a typical pattern in the logs, in this case using release 2.26.4, the last one before the glitch trick stopped working completely.

- **Plug**
- Controller 0 added, buttons don't work normally
- **Unplug**
- Controller 0 is removed
- **Plug**
- Controller 1 is added
- Buttons don't work normally
- **Unplug**
- Controller 1 is removed
- **Plug**
- Controller 2 is added and throws glitches
- Controller 3 is added
- Buttons work normally
- **Unplug**
- Controller 2 throws glitches and is removed
- Controller 3 is removed
- **Plug**
- Controller 4 is added
- buttons don't work normally
- **Unplug**
- Controller 4 is removed
- **Plug**
- Controller 5 is added
- Buttons don't work normally
- **Unplug**
- Controller 5 is removed
- **Plug**
- Controller 6 is added and throws glitches
- Controller 7 is added
- Buttons work normally
- **Unplug**
- Controller 7 is removed
- Controller 6 throws glitches and is removed

and so on and so forth with variations of the above in random order.

**Comment by slouken** [comment]
@alicedb2, can you increase MAX_ATTEMPTS in src/joystick/apple/SDL_mfijoystick.m and see how many attempts you need for this to work?

**Comment by slouken** [comment]
I've also added hints to let you control which joystick driver you're using, so you can identify which one is broken, in https://github.com/libsdl-org/SDL/commit/708f18d49ef6975769865d247e2ce4da6ce8da76.
e.g.
```
mkdir -p SDL/build
cd SDL/build
cmake -DCMAKE_BUILD_TYPE=Debug -DSDL_TESTS=ON ..
make -j10 && SDL_JOYSTICK_MFI=1 SDL_JOYSTICK_IOKIT=0 ./test/testcontroller
```
(and flip the variables to switch IOKit on)

**Comment by alicedb2** [comment]
The testcontroller program of the current main branch was much more verbose and I could see that leftstick/rightstick/back/start where actually registering as b6/b7/b8/b9 and that they were either incorrectly mapped as guide:b6 or not mapped at all

```
INFO: Opened gamepad Logitech Dual Action
INFO: Mapping: 0500040eac05000001000000ef076d01,*,
a:b0,b:b1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,
guide:b6,    <----- incorrect
leftshoulder:b4,lefttrigger:a2,leftx:a0,lefty:a1,
rightshoulder:b5,righttrigger:a5,rightx:a3,righty:a4,
x:b2,y:b3,platform:macOS
....b7/b8/b9 missing....
```

So I removed `guide:b6` and added `leftstick:b6,rightstick:b7,back:b8,start:b9` and passed the string explicitly through `SDL_GAMECONTROLLERCONFIG` and everything works as it should!

Looking at src/joystick/SDL_gamepad_db.h, there's an explicit "Logitech F310 Gamepad (DInput)" in the `__MACOS__` block at line 390, but my game controller is recognized as a "Logitech Dual Action". The F310 mapping string, while it correctly specifies `back:b8,start:b9`, maps `leftstick:b10,rightstick:b11` instead of to b8/b9.

With all that said, there's no `0500040eac05000001000000ef076d01` anywhere in SDL_gamepad_db.h, so I don't know how SDL decides it's a "Logitech Dual Action". I added

"0500040eac05000001000000ef076d01,Logitech F310 Gamepad (DInput),a:b0,b:b1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,righttrigger:a5,rightx:a3,righty:a4,x:b2,y:b3,leftstick:b6,rightstick:b7,back:b8,start:b9,"

on top of line 390, recompiled, and everything works.

**Comment by alicedb2** [comment]
I just tried Cemu/Ryujinx by launching them with the `SDL_GAMECONTROLLERCONFIG` environment variable set as above and everything works!

**Comment by slouken** [comment]
Great! I'm working on automatic mapping so you won't have to do that. It's still work in progress, but should work for the Logitech F310 now:
https://github.com/libsdl-org/SDL/pull/8557

**Comment by slouken** [comment]
@alicedb2, can you try the latest SDL3 code? It should work much better now. :)

**Comment by alicedb2** [comment]
All buttons work right away! Only (non)issue is that the back button registers as guide, i.e. the mapping string includes guide:b2 instead of back:b2, but then again "back" is just a label on the faceplate.

**Comment by slouken** [comment]
Yeah, because that controller doesn't send input for the real home (guide) button, Apple decided to map the back button to home instead.

Thanks!
