### ISSUE TITLE
Android SDL_RWFromFile() fails to set an error if it fails

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#8427]
If `SDL_RWFromFile()` returns NULL, no error is set. The specific condition is to try and open a file that doesn't exist. I stepped through the code and the offending code is here:

https://github.com/libsdl-org/SDL/blob/4ac38d13ddce8d247041f92fc45f4ac00c106674/src/file/SDL_rwops.c#L502

`Android_JNI_FileOpen()` doesn't set an error. Should be a `SDL_SetError("Can't open %s", file);` before the `return NULL` ?

**Comment by slouken** [comment]
Fixed, thanks!
