### ISSUE TITLE
Possible undefined behaviour in hid.c

### ISSUE THREAD

**Issue by themightyoarfish** [libsdl-org/SDL#8428]
https://github.com/libsdl-org/SDL/blob/b45a0d901625cb1ab66b64bc57a9df0ca51ca7b2/src/hidapi/mac/hid.c#L1233C2-L1233C2

In `hid_report_callback()` and a few other places, we find the idiom

```
return_data(dev, NULL, 0);
```

Which then turns into 

```
memcpy(NULL, rpt_data, 0)
```

This I believe is undefined behaviour according to the C99 standard:

> Where an argument declared as size_t n specifies the length of the array for a
function, n can have the value zero on a call to that function. Unless explicitly stated
otherwise in the description of a particular function in this subclause, pointer arguments
on such a call **shall still have valid values**, as described in 7.1.4. On such a call, a
function that locates a character finds no occurrence, a function that compares two
character sequences returns zero, and a function that copies characters copies zero
characters.

Is this a problem here?

**Comment by themightyoarfish** [comment]
we have seen some segfaults on macos. We are not sure if this is related, but would this be enough for a fix?

```
diff --git a/src/hidapi/mac/hid.c b/src/hidapi/mac/hid.c
index 20c664501..5e6c9d461 100644
--- a/src/hidapi/mac/hid.c
+++ b/src/hidapi/mac/hid.c
@@ -1230,7 +1230,10 @@ static int return_data(hid_device *dev, unsigned char *data, size_t length)
 	   return buffer (data), and delete the liked list item. */
 	struct input_report *rpt = dev->input_reports;
 	size_t len = (length < rpt->len)? length: rpt->len;
-	memcpy(data, rpt->data, len);
+	if (data)
+	{
+		memcpy(data, rpt->data, len);
+	}
 	dev->input_reports = rpt->next;
 	free(rpt->data);
 	free(rpt);

**Comment by sezero** [comment]
Is the patch submitted to mainstream?

**Comment by icculus** [comment]
> Is the patch submitted to mainstream?

I haven't done so. Is it https://github.com/libusb/hidapi ?

**Comment by sezero** [comment]
> > Is the patch submitted to mainstream?
> 
> I haven't done so. Is it https://github.com/libusb/hidapi ?

Yes

**Comment by icculus** [comment]
Submitted: https://github.com/libusb/hidapi/pull/637

I can see from this discussion there is an unrelated bug (should we reopen this?), but that patch is still right regardless, because they have cases in that same source code that definitely will trigger a memcpy to NULL otherwise.
