### ISSUE TITLE
A way to cancel threads

### ISSUE THREAD

**Issue by mr-sihc** [libsdl-org/SDL#8434]
I saw that this was already possible in SDL1.2
And it was removed because some OS's don't like it,
have those OS's improved enough?

I really need something to exit a thread (from itself)

I'll explain my problem

I have a function to end my program, lets say there was an error, and i need to exit.
So i call the function from the thread that encountered the error,
and then i need to destroy the thread that called the function

If i don't, the thread exits the function, and continues like nothing happened,
until it ether survives until the main loop and sees it should die (and return from its main)
or it crashes after doing some things where it should have already exited at that point

and I cant just make it return from that function that sees the code to return, return, return...
until its at its main.

this would be extremely tedious
(every function that could lead to a function that can error exit,
would have to have a return code and check for it and then return...)

If the OS's still can't do that, is there at least an alternative for my problem?

**Comment by bradallred** [comment]
> And it was removed because some OS's don't like it, have those OS's improved enough?

It's not a question of improvement. Canceling threads is fraught with peril :) Even on some systems that allow it, it doesn't result in things getting properly torn down (eg macOS with C++). The only way to guarantee consistent cross platform behavior is to not do it.

If you don't require cross platform support (and accept the consequences), just use whatever cancelation mechanism exists on your platform (eg `pthread_exit`).

Alternatively, if you do require cross platform support, use C++ and throw an exception to unwind all the way back to the "main" function where you return to exit the thread.

**Comment by icculus** [comment]
> use C++ and throw an exception to unwind all the way back to the "main" function where you return to exit the thread

Or setjmp/longjmp from C, if you can't just call pthread_exit().

They all have the same problem: any resources allocated by the thread earlier in the stack are going to leak. But at least you can control when you stop.

An API that forcibly kills another thread risks the thread dying while it holds a lock, which is going to have disastrous results.
