### ISSUE TITLE
Rename SDL_MUTEX_MAXWAIT?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8436]
```c
/**
 *  This is the timeout value which corresponds to never time out.
 */
#define SDL_MUTEX_MAXWAIT   -1
```

We should rename this something like SDL_MUTEX_FOREVER or SDL_MUTEX_NOTIMEOUT so it doesn't sound like one can outwait the thing if some timer maximum rolls over (which a positive Sint32 will do in ~24 days).

(Or just remove it and say "pass a -1 to wait forever"? to these functions?)

**Comment by slouken** [comment]
It's not just used by mutexes, so I'm fine with either renaming it or removing it.
