### ISSUE TITLE
Vulkan backend?

### ISSUE THREAD

**Issue by rygo6** [libsdl-org/SDL#8438]
Are there any plans to implement a vulkan backend for the sdl renderer? Or is anyone working on it already?  If not, is there a reason why? Or just no one has got around to it?

**Comment by icculus** [comment]
The goal is to get the GPU API into SDL3, which will have a Vulkan backend, and then use the new GPU API as a backend for the renderer.

**Comment by rygo6** [comment]
That sounds like a good plan. Is there any beta version of the GPU API available? Or any specs on it published yet?

**Comment by mr-sihc** [comment]
look on icculus's account, he has an SDL2 branch with the api
https://github.com/icculus/SDL/tree/gpu-api

**Comment by icculus** [comment]
...and a FAQ for this work: 

https://github.com/libsdl-org/SDL_shader_tools/blob/main/docs/README-SDL_gpu.md

The GPU API pull request is sitting in #7067 until it merges.

I'm closing this bug, but you can watch that PR for updates!
