### ISSUE TITLE
Unable to compile on MacOS with OpenGL ES

### ISSUE THREAD

**Issue by CaptainKraft** [libsdl-org/SDL#8439]
I'm on an M1 Macbook Pro with MacOS Ventura 13.4.1

When attempting to build while using OpenGL ES, I get the following error:
`fatal error: 'GLES2/gl2platform.h' file not found`

In the `SDL_opengles2.h` file, it attempts to include the above header file when on MacOS, but it seems my machine does not have that header file.

The same code builds and runs on Windows and Linux without issue.

If I remove any OpenGL ES-specific code from my C files or shaders, everything builds and runs fine.

**Comment by slouken** [comment]
That’s correct, macOS does not support OpenGL ES.
