### ISSUE TITLE
SDL2, Crash on signal SIGABRT

### ISSUE THREAD

**Issue by michael1413** [libsdl-org/SDL#8441]
My program crash with a SEGV if the program receive a SIGABRT signal.

Sample source:

SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS) ;
while(1) sleep(1);

killall -s SIGABRT sample
->Segmentation fault

Hardware: Raspberry PI CM3&4 with fkms

Version: sdl2-2.28.4

**Comment by slouken** [comment]
Can you run it under the debugger and see what's happening?

**Comment by michael1413** [comment]
Sorry I can't reproduce the error with a simple program.
My program has multiple threads and only crashes when executing SDL_Init and receiving a SIGABRT.

It looks that the error is in SDL_evdev_kbd.c 
If I set my signal handler for SIGABRT after SDL_Init, my program does not crash on SIGABRT.


Thread 1 "bluebox" received signal SIGABRT, Aborted.
Thread 1 "bluebox" received signal SIGABRT, Aborted.
Thread 1 "bluebox" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) where
#0  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by slouken** [comment]
It's probably something in kbd_cleanup_signal_action(), can you add debug print statements and narrow down where it's crashing?

**Comment by michael1413** [comment]
The segv is not in the kbd_cleanup_signal_action function.
The crash occurs after the line "SDL_EVDEV_kbd_reraise_signal(signum);"

**Comment by slouken** [comment]
Ah, so it's something else in your program that is crashing in response to SIGABRT. Maybe some other library is setting a SIGABRT handler that's causing an issue? I'll go ahead and close this for now, feel free to reopen if you find that it's something in SDL.
