### ISSUE TITLE
SDL_AddEventWatch returns void

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8442]
SDL_AddEventWatch calls SDL_realloc, and if it's out of memory, it simply doesn't add the watcher, but the function returns void so the app has no idea.

We should change this for SDL3.

**Comment by slouken** [comment]
Fixed in f439ccfc1.

**Comment by icculus** [comment]
Ozkan already fixed up sdl2-compat, but we need to make a note that this changed in the migration doc.
