### ISSUE TITLE
SDL2 screensaver causes display to never turn off at lock screen (GNOME on Xorg)

### ISSUE THREAD

**Issue by lxylxy123456** [libsdl-org/SDL#8443]
I am using GNOME 43 on Xorg. Normally, when I lock the screen, the display will be turned off. Only when I move the mouse / press the keyboard, the display will turn back on.

However, when I am running a SDL2 application and lock the screen, the display turns off at first. However, after less than 1 minute, the display turns on by itself. The display stays on even after waiting for a few minutes.

Way to reproduce (demo video: <https://youtu.be/Tfs2amLXogI>):
1. Get a GNOME environment. For example I am using Debian 12 Live.
2. Make sure to switch to "GNOME on Xorg", the default is likely Wayland.
3. Open an SDL2 application. For example I am using <https://gitlab.com/aminosbh/basic-c-sdl-game>. Can also reproduce this problem using PPSSPP.
4. Lock the screen using Super+L. See that the display is turned off.
5. Wait for a few minutes, notice that the display is turned on, even without any user input. The display stays on forever.

Expected behavior:
* The display should be off when there is no user input.

Workaround:
* Use `SDL_VIDEO_ALLOW_SCREENSAVER=1` to prevent SDL2 from disabling screensaver.

Software versions:
* SDL 2.26.5
* GNOME Shell 43.6

**Comment by icculus** [comment]
This is likely not an SDL bug.

It's reasonable for a user to lock the desktop while an app is requesting the screensaver not turn on, but the screen coming out of standby in this scenario is controlled by Gnome (I assume), not SDL.
