### ISSUE TITLE
Build fails on macOS when using gcc (but succeeds with clang)

### ISSUE THREAD

**Issue by miguno** [libsdl-org/SDL#8448]
Originally reported at https://github.com/microsoft/vcpkg/issues/34778

When building SDL (via vcpkg) with gcc, the build fails with:

```
gcc-13: error: unrecognized command-line option '-fobjc-arc'; did you mean '-fobjc-gc'?
```

The relevant line in `CMakeLists.txt` is:
https://github.com/libsdl-org/SDL/blob/875e45e70b4086ca8cdff405231fc616f06cda7e/CMakeLists.txt#L2976C44-L2976C44

```cmake
if(APPLE)
  sdl_compile_options(PRIVATE "-fobjc-arc")
endif()
```

Apparently, the current SDL build setup does not differentiate between different compilers on macOS. Not sure whether this is intentional or not. I don't recall having come across a note in the documentation about this, though.

The build works when using clang (v17.0.3 in my case, installed via homebrew).

**Environment**
- macOS 14.0 Sonoma (Silicon)
- gcc-13 (Homebrew GCC 13.2.0) 13.2.0
- SDL: latest available version

**Comment by miguno** [comment]
That makes sense. AFAIK, GCC indeed does not support ARC.

Feel free to close, unless you prefer to have a more descriptive error message in case someone does attempt to build SDL with GCC.

**Comment by madebr** [comment]
The flag is now checked in SDL3 (https://github.com/libsdl-org/SDL/commit/f18120c83cc623224a694677837ea4d78cd5b94f) and SDL2 (https://github.com/libsdl-org/SDL/commit/20630b2e6c02e40b5da12cccb7e74ef2b8fdfc08)

**Comment by sezero** [comment]
> The flag is now checked in SDL3 ([f18120c](https://github.com/libsdl-org/SDL/commit/f18120c83cc623224a694677837ea4d78cd5b94f)) and SDL2 ([20630b2](https://github.com/libsdl-org/SDL/commit/20630b2e6c02e40b5da12cccb7e74ef2b8fdfc08))

```
 -- Performing Test COMPILER_SUPPORTS_-fobjc-arc
-- Performing Test COMPILER_SUPPORTS_-fobjc-arc - Failed
CMake Error at CMakeLists.txt:3342 (message):
  Compiler does not support -fobjc-arc: this is requires on Apple platforms
```

**Comment by madebr** [comment]
Yeah, i made a typo in the SDL2 branch.
