### ISSUE TITLE
SDL3 Tearing BGRA image on D3D11 & D3D12

### ISSUE THREAD

**Issue by nomi-san** [libsdl-org/SDL#8451]
To reproduce this issue:

1. Use D3D11 or D3D12 renderer driver
2. Render a BGRA image with any BGR pixel formats:
   - `SDL_PIXELFORMAT_XRGB8888`
   - `SDL_PIXELFORMAT_BGRX8888`
   - `SDL_PIXELFORMAT_BGRA32`
3. Resize the texture that the width is not divisible by 64, e.g `1271`, `1285`

No problem with other renderers (D3D9/OpenGL/Software), and RGB pixel formats (but wrong color), and the texture width is divisible by 64. I used the latest build (2 days ago) from https://github.com/mmozeiko/build-sdl3.

Weird example with **1285px width (not divisible by 64)** & SDL_PIXELFORMAT_**BRGA32**.

![image](https://github.com/libsdl-org/SDL/assets/38210249/f4fb68dd-a173-4afd-aa18-0b48a8bebb6a)

Normal example with **1280px width (divisible by 64)** & SDL_PIXELFORMAT_**BRGA32**.

![image](https://github.com/libsdl-org/SDL/assets/38210249/5d25be73-ed5a-4fe8-bedc-e441edf8bf6e)

Normal example with **1285px width (not divisible by 64)** & SDL_PIXELFORMAT_**RGBA32**.

![image](https://github.com/libsdl-org/SDL/assets/38210249/eea95d08-4f1e-4c84-b6dd-10ca12b6a151)

**Comment by nomi-san** [comment]
@slouken

Hi, here's my simple test [bgra_frame_test.zip](https://github.com/libsdl-org/SDL/files/13246074/bgra_frame_test.zip) with 10 image frames (1280 to 1344 px width).

Some key bindings:
- Press N to change next frame.
- Press F to change pixel format (BGR <-> RGB)
- Press V to set vsync on/off

The image source is actually BGRA frames from example.com via CEF offscreen rendering.

![image](https://github.com/libsdl-org/SDL/assets/38210249/d2183f5f-29c8-4804-aa56-fbe1ad77eeb3)

![image](https://github.com/libsdl-org/SDL/assets/38210249/7823c2e9-ab75-46cc-9c56-ac8d34f63711)

**Comment by ccawley2011** [comment]
> Hi, here's my simple test [bgra_frame_test.zip](https://github.com/libsdl-org/SDL/files/13246074/bgra_frame_test.zip) (vs2022 project) with 10 image frames (1280 to 1344 px width).

The test program ignores the pitch value returned by `SDL_LockTexture`, so that'll probably explain what's going wrong. Direct3D 11 likely requires 64 byte alignment for the start of each row, so you'll need to account for that when writing for textures. R/B swapped textures are currently emulated by SDL, and will have different alignment requirements.

This code should work (but isn't tested):
```
        SDL_LockTexture(tex, nullptr, &pixels, &pitch);
        for (int y = 0; y < width; y++) {
            fread_s(pixels, width * 4, 1, width * 4, fp);
            pixels = (Uint8 *)pixels + pitch;
        }
        SDL_UnlockTexture(tex);
```

**Comment by nomi-san** [comment]
Thank you, I just realized that when updating resource data in pure D3D11.

```diff
D3D11_MAPPED_SUBRESOURCE m = { 0 };
context->Map(resource_, 0, D3D11_MAP_WRITE_DISCARD, 0, &m);
-memcpy(m.pData, image, width * height * 4);
+for (int y = 0; y < height; y++)
+  { ... }
context->Unmap(resource_, 0);
```
