### ISSUE TITLE
Excessive Noise in Recorded Audio with SDL2

### ISSUE THREAD

**Issue by mystorp** [libsdl-org/SDL#8453]
Hi,

I am attempting to record audio using SDL2, however, the resulting audio contains a significant amount of noise. The noise is consistent and overpowers the desired audio. I have tried adjusting various settings, but the issue persists. Could you please provide insight into what might be causing this and how I can resolve it?

Thank you.

![QQ截图20231101114623](https://github.com/libsdl-org/SDL/assets/1627624/b37b7887-7d99-42ff-b9c9-a98f116803de)

This is my code:
```c
#include <stdio.h>
#include <SDL.h>

#define MAX_SOUND_BYTES 768000

static int bytesWritten = 0;

struct AudioFormatName
{
  SDL_AudioFormat format;
  char *name;
};

static struct AudioFormatName sdl_audio_formats[] = {
  { AUDIO_S16, "s16le" },
  { AUDIO_F32, "f32le" }
};

char *getAudioFormatName(SDL_AudioFormat format);
void printAudioSpec(SDL_AudioSpec *spec, char *placeholder);

void onAudioData (void *userdata, Uint8 * stream, int len) {
  FILE *pcmf = (FILE *)userdata;
  fwrite(stream, len, 1, pcmf);
  bytesWritten += len;
}


int main (int argc, char **argvv) {
  int code;
  SDL_AudioSpec desired, hardware;
  SDL_AudioDeviceID id;
  FILE *pcmfile;
  const char *audioDevName;
  pcmfile = fopen("./out.pcm", "w");
  if (pcmfile == NULL) {
    SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Failed to create pcm file!\n");
    return 1;
  }
  code = SDL_InitSubSystem(SDL_INIT_AUDIO);
  if (code != 0) {
    SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Failed to init audio!\n");
    return 1;
  }
  SDL_zero(desired);
  SDL_zero(hardware);
  desired.channels = 1;
  desired.format = AUDIO_S16SYS;
  desired.freq = 48000;
  desired.samples = 4096;
  desired.callback = onAudioData;
  desired.userdata = pcmfile;

  audioDevName = SDL_GetAudioDeviceName(0, SDL_TRUE);
  SDL_Log("device: %s\n", audioDevName);
  id = SDL_OpenAudioDevice(audioDevName, SDL_TRUE, &desired, &hardware, SDL_AUDIO_ALLOW_ANY_CHANGE);
  printAudioSpec(&desired, "desired");
  printAudioSpec(&hardware, "hardware");
  if (id <= 0) {
    SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Failed to open audio.\n");
  }
  SDL_PauseAudioDevice(id, 0);
  while (bytesWritten < MAX_SOUND_BYTES) {
    SDL_Delay(20);
  }
  SDL_PauseAudioDevice(id, SDL_TRUE);
  fflush(pcmfile);
  fclose(pcmfile);
  SDL_CloseAudioDevice(id);
  SDL_QuitSubSystem(SDL_INIT_AUDIO);
  return 0;
}

char *getAudioFormatName (SDL_AudioFormat format) {
  for (int i = 0, len = sizeof(sdl_audio_formats) / sizeof(struct AudioFormatName); i < len; ++i) {
    if (sdl_audio_formats[i].format == format) {
      return sdl_audio_formats[i].name;
    }
  }
  return "unknow";
}

void printAudioSpec(SDL_AudioSpec *spec, char *placeholder) {
  SDL_Log("%s audio spec: channels=%d, format=%s, freq=%d, samples=%d, size=%d, silence=%d\n",
    placeholder,
    spec->channels,
    getAudioFormatName(spec->format),
    spec->freq,
    spec->samples,
    spec->size,
    spec->silence);
}
```
and logs:
```log
INFO: device: 阵列麦克风 (AMD Audio Device)
INFO: desired audio spec: channels=1, format=s16le, freq=48000, samples=4096, size=0, silence=0
INFO: hardware audio spec: channels=2, format=f32le, freq=48000, samples=480, size=3840, silence=0
```

**Comment by mystorp** [comment]
I am currently using SDL2-2.28.4 for audio recording.

**Comment by icculus** [comment]
Can you try recording directly through Audacity, just to make sure this is an SDL bug and not a hardware or platform issue?

Also, can you add this to the program after the SDL_InitSubSystem call?

```c
SDL_Log("Current audio driver: %s", SDL_GetCurrentAudioDriver());
```

**Comment by mystorp** [comment]
Thank you very much for your suggestions. @icculus 

> Can you try recording directly through Audacity, just to make sure this is an SDL bug and not a hardware or platform issue?

I tried recording audio using Audacity. In Audacity, the waveform and playback of the recorded sound appear normal, without any noticeable noise.

> Also, can you add this to the program after the SDL_InitSubSystem call?

I checked the audio driver and found that the default driver being used is wasapi. 

On my machine, the available drivers include: wasapi, directsound, winmm, disk, and dummy. 

I tried using the SDL_AudioInit(driver_name) interface and passed directsound, but the problem persists. 

I also tried using disk driver, and attempted to export a music file as sdlaudio-in.raw using ffmpeg, yet the noise issue remains unresolved.

Could you please advise if there are any other troubleshooting methods or possible solutions?

**Comment by slouken** [comment]
We greatly improved things in SDL 3.0. Please let us know if you're still seeing the issue there.
