### ISSUE TITLE
How to use SDL_MixAudioFormat in SDL3?

### ISSUE THREAD

**Issue by huangjinshe** [libsdl-org/SDL#8465]
Looks like the [SDL_MixAudioFormat](https://wiki.libsdl.org/SDL3/SDL_MixAudioFormat ) document still not update.
it still using `Uint8 *` type for stream, but SDL3 already using `SDL_AudioStream*` for stream in callback.

**Comment by huangjinshe** [comment]
We usally use this for change audio volume before in SDL2.

**Comment by icculus** [comment]
SDL_MixAudioFormat still operates on an array of audio data; when using the callbacks in SDL3, where you might have previously done something like this:

```c
static void SDLCALL MyAudioCallback(void *userdata, Uint8 * stream, int len)
{
     // I have audio data in a global, MyAudioBuffer, that I want to adjust and copy into stream...
     // you have to initialize `stream` to silence first, because we're mixing into it!
     SDL_memset(stream, 0, len);
     SDL_MixAudioFormat(stream, MyAudioBuffer, MyAudioBufferFormat, len, MyVolume);
}
```

...now you have to put that data into an SDL_AudioStream instead of copying to an array:

```c
static void SDLCALL MyAudioCallback(void *userdata, SDL_AudioStream * stream, int len)
{
     // I have audio data in a global, MyAudioBuffer, that I want to adjust and copy into stream...
    Uint8 *buffer = (Uint8 *) SDL_calloc(1, len);  // SDL_calloc zeroes out the buffer after allocating.
    if (buffer) {
        SDL_MixAudioFormat(buffer, MyAudioBuffer, MyAudioBufferFormat, len, MyVolume);
        // okay, _now_ we're ready to put the mixed data into the stream!
        SDL_PutAudioStreamData(stream, buffer, len);
        SDL_free(buffer);
    }
}
```

This doesn't necessarily _have to_ use SDL_calloc, but it needs a buffer somewhere it can mix to before putting it in the stream.

**Comment by ell1e** [comment]
Hm sads, I wish there was a way to avoid more buffer copies.
