### ISSUE TITLE
Emscripten SDL UpdateWindowFramebuffer performance

### ISSUE THREAD

**Issue by hedwigz** [libsdl-org/SDL#8467]
https://github.com/libsdl-org/SDL/blob/c4bf05fd9d0126cbdf4db09f11bc5737b38f5f76/src/video/emscripten/SDL_emscriptenframebuffer.c#L57

when doing performance analysis of my application I see much CPU usage in this function.  
It looks like there's a loop that's setting the alpha channel of the canvas image
```js
while (i < j) {
    data8[i] = 0xff;
    i = i + 4 | 0;
    data8[i] = 0xff;
    i = i + 4 | 0;
    data8[i] = 0xff;
    i = i + 4 | 0;
    data8[i] = 0xff;
    i = i + 4 | 0;
    data8[i] = 0xff;
    i = i + 4 | 0;
    data8[i] = 0xff;
    i = i + 4 | 0;
    data8[i] = 0xff;
    i = i + 4 | 0;
    data8[i] = 0xff;
    i = i + 4 | 0;
  }
```
I am wondering if there's a way to avoid this?  
Also, possibly, can we even avoid copying the surface pixels to an image? and create image directly from the buffer? that'll provide major improvement in performance if possible.  
There's also a nice example where getting bitmap from webassembly is not copied in the following [article](https://compile.fi/canvas-filled-three-ways-js-webassembly-and-webgl/)

**Comment by icculus** [comment]
We're happy to take patches to speed this up, but generally you want to be using the rendering API, which will let you upload buffers of pixels to a texture and draw them with WebGL (the fastest method mentioned in that article).

**Comment by icculus** [comment]
I'm going to close this as WONTFIX for now, because the render API is the recommended path for pushing pixels to the screen, and will 100% solve the problem mentioned here, but if someone comes along later and wants to make the effort to optimize this codepath in a reasonable way, we'll accept a patch (open a PR or leave a comment here!).

**Comment by hedwigz** [comment]
Makes sense @icculus 
thanks
