### ISSUE TITLE
Windows default compile settings with CMake gives linker warning

### ISSUE THREAD

**Issue by null77** [libsdl-org/SDL#8473]
Warning when building shared SDL with my version of MSVC/CL on Windows:

```
1>LINK : warning LNK4044: unrecognized option '/Wl,--version-script=C:/src/TestCpp/third_party/SDL/src/dynapi/SDL_dynapi.sym'; ignored
```

CMake file for reference

```
cmake_minimum_required(VERSION 3.19.0 FATAL_ERROR)

project(TestCpp VERSION 1.0 LANGUAGES CXX)

add_subdirectory(third_party/SDL)

add_executable(TestCpp Test.cpp)
target_link_libraries(TestCpp PRIVATE SDL3::SDL3-shared)
```

Looking at the macro `check_linker_supports_version_file`:

https://github.com/libsdl-org/SDL/blob/91f045639160dece14ece8d404816d8e9b8a61e9/cmake/macros.cmake#L89

One solution is to change to:

```
  check_c_source_compiles("int func(void) {return 0;} int main(int argc,char*argv[]){(void)argc;(void)argv;return func();}" LINKER_SUPPORTS_VERSION_SCRIPT FAIL_REGEX "(unsupported|syntax error|unrecognized option)")
```

This makes the linker warning go away. I can upload a pull request if that's an acceptable fix.

**Comment by madebr** [comment]
That change looks perfectly reasonable, and a pr will get accepted immediately :)
