### ISSUE TITLE
Add `SDL_InitUserEvent`

### ISSUE THREAD

**Issue by ankith26** [libsdl-org/SDL#8479]
Related to discussion in the PR #6524 and its linked issue.

As per [slouken's comment on that thread](https://github.com/libsdl-org/SDL/pull/6524#issuecomment-1793450430), opening a new issue to further discuss this. Associating free functions with userevents has an application. Users who call `SDL_FlushEvents` have no way of handling freeing of their user events properly. This forces us to either not call this, or end up doing a custom implementation specific to our userevent, in order to not leak it. As someone who contributes to a library that wraps SDL, we have to export an equivalent of `SDL_FlushEvents`, and we also make heavy use of userevents with data pointers.

So I propose adding a new function that is to be called on every userevent before it is pushed, that takes care of initialisations properly. For example, consider the below SDL2 code
```c
SDL_Event my_event;
my_event.type = SDL_USEREVENT;
my_event.code = 1234;
my_event.data1 = foo;
my_event.data2 = bar;
```
and what it could look like with this function in place
```c
SDL_Event my_event;
SDL_InitUserEvent(&my_event, SDL_USEREVENT, 1234, foo, bar, the_custom_free_function);
```

For extra safety, maybe this new function could also set a special magic field in the userevent struct, signalling to SDL API recieving this event that it has been properly initialised. In case this magic does not match, the other SDL API could either decide to error, or ignore/not-call the free callback.

**Comment by slouken** [comment]
That's a good idea, but anyone who knows to use this function would also know to initialize the free function manually.

After thinking about it, I think it's a good idea to add the cleanup function for SDL3, I'll go ahead and do that.

**Comment by slouken** [comment]
Actually, with my last change we lost the cleanup function, but maybe we could take advantage of the event memory cleanup somehow?

**Comment by slouken** [comment]
Do you need generic cleanup or is using SDL_AllocateEventMemory() sufficient for your needs?

**Comment by ankith26** [comment]
For my application, I would need the ability to set up a custom cleanup mechanism. Because the struct I'm passing contains things that need to be freed/cleaned-up on free of the struct

**Comment by slouken** [comment]
So really the only case that you need handled is when events are flushed, correct? It sounds like for your case you can create a custom flush function that you expose that does cleanup, and in all other cases you're handling the event yourself and can clean it up appropriately, right?

**Comment by ankith26** [comment]
> and in all other cases you're handling the event yourself and can clean it up appropriately, right?

yes, that is the case

> It sounds like for your case you can create a custom flush function

Yes that is definitely doable (as I mentioned before) and not much work either. But that still means there is a potential leak in a public SDL API function and my proposal is one way to address it, and I personally don't see a better fix. Alternatively, if this is not being fixed, it should be documented at the very least (lmk if you favour this, I can open a docs PR) so that people who have this usage (not super common, I agree) know to avoid the function altogether.

**Comment by slouken** [comment]
Yes, let's do a docs fix for now. Later we can add a flush callback function if it becomes an important use case.
