### ISSUE TITLE
Rudder Pedals Not Detected in v2.28.5

### ISSUE THREAD

**Issue by rickechler** [libsdl-org/SDL#8484]
SDL2 2.26 auto detects the Saitek Pro Flight Combat Rudder Pedals, v 2.28.5 does not.

2.26 example code output
![image](https://github.com/libsdl-org/SDL/assets/13603029/3758c246-5460-47d1-9657-d469b881adcb)

2.28.5 example code output
![image](https://github.com/libsdl-org/SDL/assets/13603029/bb8ed5c4-23f7-4b4c-be32-fc067a7ad285)

Thanks!

**Comment by CyborgYL** [comment]
Same problem here with sim racing pedals. Simagic P2000 detected in 2.26.5 but not detected in 2.28 and above.
