### ISSUE TITLE
Can't get all keys on Linux

### ISSUE THREAD

**Issue by EdouardBERGE** [libsdl-org/SDL#8486]
Hi, some keys are hidden by Linux (no event for F11 but OS is doing some desktop-fullscreen)
I installed a new LUbuntu 23.10 and the French handler is buffering  circumflex key (to easily type any upper case circumflex)
Then SDL is blind with this key
If i use "xev" to show X11 events, i see the keydown/keyup on the key BUT state is always zero whereas other keys have state to 1 when the key is released (or up)

I saw some people on Windows using their own driver to catch all keys, is there any solution for Linux/X11 ?

Regards

**Comment by Kontrabant** [comment]
You could open the `dev/hidraw` device and get the raw keyboard data directly, but this requires admin privileges for obvious reasons.

**Comment by EdouardBERGE** [comment]
thanks,  will try to manage raw events
