### ISSUE TITLE
D3D12: Expose method to get internal ID3D12CommandQueue

### ISSUE THREAD

**Issue by null77** [libsdl-org/SDL#8491]
Some projects that use D3D12 would like to use the same one SDL uses internally, instead of calling CreateCommandQueue themselves.

Namely, I'm working on an integration with SDL and NVRHI, and NVRHI can use a provided command queue instead of creating a second one. I'd like to add an API to SDL's D3D12 interface to query the command queue so I can take advantage of this.

My proposed method would be `SDL_RenderGetD3D12CommandQueue(SDL_Renderer *)`, similar to `SDL_RenderGetD3D12Device`. Any thoughts or objections to this proposal?

Note: D3D12 might the same command queue if we call create with the same parameters? In any case, calling SDL would be a nicer way to do it - less code and easier to understand what is really happening.

**Comment by null77** [comment]
Thanks for the quick feature!

**Comment by slouken** [comment]
You're welcome! :)
