### ISSUE TITLE
Hint to report out-of-bounds touch coordinates

### ISSUE THREAD

**Issue by NyakoFox** [libsdl-org/SDL#8494]
While working on touch controls for VVVVVV, I noticed that finger positions get clamped to the viewport. This is unwanted for us as 4:3 (VVVVVV's aspect ratio) is pretty small for touch controls, and we'd like to use all of the out-of-bounds space as well. A hint to unclamp the finger positions would be nice, as I could see other games/programs wanting this functionality as well.

**Comment by slouken** [comment]
Yes, this seems like a good idea. Feel free to create a PR for it, if you have time.

**Comment by NyakoFox** [comment]
Actually, was this clamping removed in dcd17f547324a143d66d79e3b586577a7da558ed? I can't find code responsible for the clamping after this commit.
