### ISSUE TITLE
Haptics API in SDL3?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8498]
The haptics API is deprecated for gamepads, but is still the only way to do vibration on steering wheels, flight sticks, and phones.

Do we want to keep this API for SDL3? Do we want to exclude gamepads? Do we want to implement haptics for gamepads on top of the gamepad rumble API?

@libsdl-org/a-team, @flibitijibibo, @cgutman, thoughts?

**Comment by flibitijibibo** [comment]
Having access to it does seem important, though I haven't dug into the output portion of ActionSet enough to know if there's anything that can be trimmed down. Gamepads probably don't need it, but we could always just use the metadata system to hook things back together if the need arises.

**Comment by slouken** [comment]
We have decided to keep the API for SDL3.
