### ISSUE TITLE
`SDL_SetWindowFullscreen(window, SDL_TRUE)` stopped working on linux in SDL3

### ISSUE THREAD

**Issue by dortamiguel** [libsdl-org/SDL#8501]
Hello, I just tried on linux the latest SDL3 source and I noticed that when I call `SDL_SetWindowFullscreen(window, SDL_TRUE)` to go fullscreen the application gets stuck.

I tried on macos and windows and it works fine there, also just in case I tried SDL2 on linux and in there `SDL_SetWindowFullscreen` works fine.

I tried to debug where the issue happens, and I think is somewhere inside `SDL_UpdateFullscreenMode`

My linux distro is the archlinux that comes with the steam deck `uname -r` `6.1.52-valve3-1-neptune-61`

**Comment by slouken** [comment]
Can you reproduce this with the testsprite test program? You can toggle fullscreen with Alt-Enter. I'm able to do that here on Ubuntu 22.04

**Comment by dortamiguel** [comment]
I just tried the SDL3 windows build on linux with proton experimental and in there the fullscreen works fine

**Comment by slouken** [comment]
Can you try this again with the latest code? We've reworked how fullscreen modes are set and may have fixed this.

**Comment by dortamiguel** [comment]
Ah nice, I will try this weekend

**Comment by dortamiguel** [comment]
I just tried and now it works again, thank you!
