### ISSUE TITLE
Installing SDL3 on Windows, Release folder not being created

### ISSUE THREAD

**Issue by koogelpotato** [libsdl-org/SDL#8503]
# Issue
Hello, I followed the instruction for installing the SDL3 with Mingw-64, built succesfully, but it doesnt install due to the Release folder not being created, when I execute `cmake --build build` I get the following error:

```
E:\SDL>cmake --install build
-- Install configuration: "Release"
-- Installing: C:/Program Files (x86)/SDL3/lib/pkgconfig/sdl3.pc
CMake Error at build/cmake_install.cmake:55 (file):
  file INSTALL cannot find "E:/SDL/build/Release/SDL3.dll": No error.
```
Mingw is installed but it picks Visual Studio 17 2022
```
-- SDL3 was configured with the following options:
--
-- Platform: Windows
-- 64-bit:   TRUE
-- Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
```
# Ways to reproduce
1.  Install choco, with it install git, cmake, mingw
2. Clone repository
3. run `cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=build-scripts/cmake-toolchain-mingw64-x86_64.cmake`
4. run `cmake --build build`
5. run `cmake --install build`

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/blob/main/build-scripts/cmake-toolchain-mingw64-x86_64.cmake does not set the cmake generator.
It looks like the `Visual Studio` generator does not install correctly for non-msvc toolchains. (maybe worth to ask this upstream)
Pass `-GNinja` or `-G "Unix Makefiles"` during configuration to use ninja/make.
