### ISSUE TITLE
CI: re-enable intel compiler runs?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#8511]
Intel Compiler workflows had been failing because of [expired keys](https://github.com/oneapi-src/oneapi-ci/issues/77)
and @madebr had disabled them.

deal.ii project applied a [workaround](https://github.com/dealii/dealii/pull/16073) apparently based on instructions [at
intel site](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-2/apt.html#GUID-A127A14F-A303-40FC-A0A9-FF69E446AEE6): Are we interested?

**Comment by madebr** [comment]
Yes, thanks for the heads-up!
These steps make ci succeed again: https://github.com/madebr/SDL/actions/runs/6814749981/job/18532327253

I pushed 61c39ce8489ae52933825a8c8b06553eedc3d0e9 (SDL3) and f0d65436f (SDL2)
