### ISSUE TITLE
Quit event is not delivered when pressing ALT+F4

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8517]
Open a test application, e.g. `test/testviewport` and immediately press <kbd>ALT</kbd>+<kbd>F4</kbd>.
The application should quit.
Instead, the loop remains running (`testviewport` keeps printing to the terminal)
The window disappears though.

I see this behavior on Windows and Linux (wayland).

I bisected this problem to commit 9c664b00623926a0973a8f19cecc55bc7c757d5b (@icculus).

**Comment by slouken** [comment]
For some reason Windows is only providing one key message per message pump iteration. I can reproduce this with SDL2 as well, and easily see the issue with this patch:
```diff
diff --git a/src/video/windows/SDL_windowsevents.c b/src/video/windows/SDL_windowsevents.c
index 9fa10954a..307c3c721 100644
--- a/src/video/windows/SDL_windowsevents.c
+++ b/src/video/windows/SDL_windowsevents.c
@@ -48,6 +48,7 @@
 #endif /* HAVE_TPCSHRD_H */

 /* #define WMMSG_DEBUG */
+#define WMMSG_DEBUG
 #ifdef WMMSG_DEBUG
 #include <stdio.h>
 #include "wmmsg.h"
@@ -1923,6 +1924,7 @@ void WIN_PumpEvents(_THIS)
 #endif

     if (g_WindowsEnableMessageLoop) {
+        SDL_Log("Pumping windows messages\n");
         while (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE)) {
             if (g_WindowsMessageHook) {
                 g_WindowsMessageHook(g_WindowsMessageHookData, msg.hwnd, msg.message, msg.wParam, msg.lParam);
@@ -1957,6 +1959,7 @@ void WIN_PumpEvents(_THIS)
                 }
             }
         }
+        SDL_Log("Pumping complete\n");
     }

 #if !defined(__XBOXONE__) && !defined(__XBOXSERIES__)

```

**Comment by madebr** [comment]
I don't see this anymore on SDL3.

Running testviewport and immediately pressing `ALT+F4` closes the window, and also exits the app.
I'm closing this issue.
Please re-open if you think my test is incorrect.
