### ISSUE TITLE
SDL_WaitEventTimeout result of 0 is ambiguous

### ISSUE THREAD

**Issue by jagprog5** [libsdl-org/SDL#8522]
Per SDL2 doc:

>Returns:
1 on success or 0 if there was an error while waiting for events; call SDL_GetError() for more information. This also returns 0 if the timeout elapsed without an event arriving.

Is there any way of disambiguating if a return of 0 is for error or timeout? There are cases where it's important to know the difference. Thanks.

**Comment by slouken** [comment]
The only errors possible are out of memory or other system errors. We changed the return value in SDL3 to SDL_bool to indicate that you don't need to worry about errors when calling that function and can assume a timeout if it returns SDL_FALSE.
