### ISSUE TITLE
Expose method to query ID3D12Resource from SDL Texture Properties

### ISSUE THREAD

**Issue by null77** [libsdl-org/SDL#8529]
Currently the method to retrieve the ID3D12Resource is to

 1. call `SDL_GetTextureDXGIResource` to get the `IDXGIResource *`
 2. Call `QueryInterface` to get a handle to the `ID3D12Resource` interface from DXGI.

It would be nice if we could instead query the `ID3D12Resource *` directly from the API, using `SDL_GetTextureProperties` and `SDL_GetProperty`. SDL could set the resource property trivially like it sets the D3D12 Device and Command Queue properties:

https://github.com/libsdl-org/SDL/commit/6c91b28e71e46d509431178fb52a7715385d54af#diff-4a86d53a7065d716212934fa4d6cc0d2960749a4fb91cac46909e151994ae86aR326

Would this be a desirable change? I can author something if acceptable.

**Comment by slouken** [comment]
Try this?

**Comment by null77** [comment]
Awesome! Works like a charm, thank you.

**Comment by slouken** [comment]
You’re welcome!
