### ISSUE TITLE
How to disable subsystems in CMake?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8534]
How do you disable subsystems in the new CMake build system?

I tried to disable MFI joystick support using the following, and it didn't work:
`cmake .. -DSDL_JOYSTICK_MFI=OFF -DCMAKE_BUILD_TYPE=Debug`

**Comment by madebr** [comment]
Current cmake only allows you to enable/disable [the main SDL subsystems](https://github.com/libsdl-org/SDL/blob/f66f61de01e1269cd25999a584885ec563f174e8/CMakeLists.txt#L237-L256) and [some extra options](https://github.com/libsdl-org/SDL/blob/f66f61de01e1269cd25999a584885ec563f174e8/CMakeLists.txt#L278-L357).

I even didn't know [mfi being an Apple thing](https://github.com/libsdl-org/SDL/tree/main/src/joystick/apple) until now.
I think you can disable it by configuring with `-DSDL_JOYSTICK=OFF -DSDL_HAPTIC=OFF`.

If you want more fine-grained control/options somewhere, please ask.

**Comment by slouken** [comment]
We basically want to be able to disable any of the driver related SDL_* defines in SDL_build_config.h.cmake. In this case I was trying to build without MFI support because there's an Apple bug I wanted to workaround for testing. I was able to manually clear it, but I was under the impression that any of the SDL defines could be overridden on the cmake command line.

**Comment by iryont** [comment]
```
-DSDL_JOYSTICK_ENABLED_BY_DEFAULT=OFF -DSDL_HAPTIC_ENABLED_BY_DEFAULT=OFF
```

It does work perfectly fine on MacOS. I had some issues with ARM64 build so I had to disable those.
