### ISSUE TITLE
hidapi: netbsd uhid native backend in mainstream

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#8535]
https://github.com/libusb/hidapi/commit/c19ae126d8856b55af34d64ee11641920475961c (netbsd-only, was originally discussed at https://github.com/libusb/hidapi/pull/612)

@slouken: Are we interested?

**Comment by slouken** [comment]
NetBSD isn't a primary platform for SDL, @madebr, what do you think?

**Comment by madebr** [comment]
ci wise, it's not hard to add netbsd.
cmake wise, if it can treat freebsd and netbsd similarly it should not be too hard.
c wise, that's up to you :)

**Comment by slouken** [comment]
Sure, there's no reason not to.

**Comment by madebr** [comment]
@sezero 

Do you know how to install packages on netbsd?
I followed [these instructions](http://www.netbsd.org/docs/pkgsrc/using.html#using-pkg), but get errors.
https://github.com/madebr/SDL/actions/runs/6836739399/job/18591993484#step:3:140

It runs
```
export PATH="/usr/pkg/sbin:/usr/pkg/bin:$PATH";export PKG_PATH="https://cdn.netbsd.org/pub/pkgsrc/packages/$(uname)/$(uname -m)/$(uname -r)/All/";echo $PKG_PATH;sudo pkg_add -v pkg
```
with on stdout:
```
https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/9.3/All/
pkg_add: no pkg found for 'pkg', sorry.
pkg_add: 1 package addition failed
```

**Comment by sezero** [comment]
> Do you know how to install packages on netbsd?

Nope, sorry

**Comment by sezero** [comment]
Created initial PR as https://github.com/libsdl-org/SDL/pull/8536 -- feel free to push to my branch.
