### ISSUE TITLE
ci: add NetBSD to the test matrix

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8537]
It would be useful to add NetBSD to the ci matrix.

[cross-platform-actions/action](https://github.com/cross-platform-actions/action) supports NetBSD, so this workflow can be re-used.

**Comment by madebr** [comment]
I tried following the install instructions at http://www.netbsd.org/docs/pkgsrc/using.html#using-pkg and https://pkgsrc.org/, but failed.

So if somebody with NetBSD experience is reading this.. ;)

**Comment by sezero** [comment]
@madebr: This works as far as command correctness is concerned: [cpactions.yml.gz](https://github.com/libsdl-org/SDL/files/13348237/cpactions.yml.gz)

It is based on yours with corrections taken from this workflow:
https://github.com/gansm/finalcut/blob/main/.github/workflows/netbsd.yml

It fails because these packages are not available:
```
libXext is not available in the repository
libXinerama is not available in the repository
libXi is not available in the repository
libXfixes is not available in the repository
libXrandr is not available in the repository
mesa-libs is not available in the repository
libglvnd is not available in the repository
evdev-proto is not available in the repository
jackit is not available in the repository
pipewire is not available in the repository
sndio is not available in the repository
zh-fcitx is not available in the repository
libudev-devd is not available in the repository
```
See: https://github.com/sezero/SDL/actions/runs/6862862541/job/18661448650

Maybe we should conditionalize the pkgs to install.

**Comment by sezero** [comment]
BTW, looking at `+CONTENTS` in https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/9.3/All/SDL2-2.28.3.tgz I see
```
@blddep wayland-1.21.0nb2
@pkgdep wayland>=1.21.0
@blddep wayland-protocols-1.32
@pkgdep wayland-protocols>=1.26nb1
@blddep libxkbcommon-1.5.0nb2
@pkgdep libxkbcommon>=1.5.0nb2
@blddep libsamplerate-0.2.2nb4
@pkgdep libsamplerate>=0.2.2nb4
@blddep digest-20220214
@blddep x11-links-1.35
```
That should give us an idea of what pkgs are needed installing...

**Comment by sezero** [comment]
I ended up with this: [cpactions.yml.gz](https://github.com/libsdl-org/SDL/files/13420764/cpactions.yml.gz)
Unfortunately, it fails with a pkg install error, I think:
```
[...]
installing jbigkit-2.1nb1...
pkg_install warnings: 3, errors: 3
pkg_install error log can be found in /var/db/pkgin/pkg_install-err.log
[...]
```

**Comment by madebr** [comment]
I also tried again last weekend and also ran into package issues.
[NetBSD 9.3 is missing dependencies](https://github.com/madebr/SDL/actions/runs/6910085517/job/18802604924) and [10.0 is not finished yet](https://github.com/madebr/SDL/actions/runs/6910170962/job/18802852484) (and not available through cpo).
I don't understand why gcc13 is missing, since [it is present](https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/9.3/All/).

[This makefile](https://github.com/NetBSD/pkgsrc/blob/trunk/devel/SDL2/options.mk) was useful while working on this.

**Comment by madebr** [comment]
Wait, 9.3 is complaining about libstdc++ which is provided by gcc13-libs. Maybe...

**Comment by madebr** [comment]
I got it started building, and opened https://github.com/libsdl-org/SDL/pull/8588 

The libstdc++ issue is caused by broken amd64 pacages: https://mail-index.netbsd.org/pkgsrc-bugs/2023/11/21/msg072291.html
