### ISSUE TITLE
Why have `SDL_LockTexture` ?

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL#8540]
Hello, this is something I've been wondering about recently-

My understanding is that SDL_LockTexture/SDL_UnlockTexture is a fast way to update the texture when the texture created with SDL_TEXTUREACCESS_STREAMING. This is fast in comparison to SDL_UpdateTexture, the generic method.

My question is why does there need to be a special method in the first place? Couldn't SDL_UpdateTexture call whatever internal code makes SDL_LockTexture fast if it determines the Texture is a streaming texture?

```
int SDL_LockTexture(SDL_Texture * texture,
                    const SDL_Rect * rect,
                    void **pixels, int *pitch);
int SDL_UpdateTexture(SDL_Texture * texture,
                      const SDL_Rect * rect,
                      const void *pixels, int pitch);
Seems like SDL_UpdateTexture could wrap SDL_LockTexture, based on their signatures
```

Thanks for your consideration.

**Comment by slouken** [comment]
SDL_LockTexture() implies that you'll do it frequently, so staging resources are prepared and left allocated for you to update every frame, where SDL_UpdateTexture() will free any staging resources after the update.

There are more complexities with YUV textures, but that's the basic reason there are different code paths.

**Comment by slime73** [comment]
> staging resources are prepared and left allocated for you to update every frame

`SDL_TEXTUREACCESS_STREAMING` sort of covers that already, right? Or maybe waiting to re-evaluate this stuff until SDL_gpu is ready and being used by SDL_Render makes sense.

**Comment by Starbuck5** [comment]
> `SDL_TEXTUREACCESS_STREAMING` sort of covers that already, right?

This is what I was thinking.

> Or maybe waiting to re-evaluate this stuff until SDL_gpu is ready and being used by SDL_Render makes sense.

Interesting, I knew there was discussion of getting icculus's SDL_gpu as a unified backend, but I was thinking that was more long term: in the life of SDL3 rather than the first release.

**Comment by Clownacy** [comment]
`SDL_LockTexture` is good for avoiding a memory copy: it _gives_ you a buffer to occupy while `SDL_UpdateTexture` _takes_ a buffer to read from. If your texture data is not readily-available as a buffer, then you would need to create one just to pass it to `SDL_UpdateTexture`. `SDL_LockTexture` avoids this.

For instance, I use `SDL_LockTexture` for my Mega Drive emulator, which does not maintain a framebuffer - instead, the emulator emits only a single row of indexed pixels at a time. This data cannot be directly passed to `SDL_UpdateTexture` as it needs to be converted to not be indexed. If I'm going to output converted pixels to an intermediary buffer, then I might as well use `SDL_LockTexture` to avoid maintaining an extra buffer in my code.

In theory, `SDL_LockTexture` would allow for zero-copy texture updating (as appears to be the case for [the PS2 backend](https://github.com/libsdl-org/SDL/blob/c790572674b225de34fe53c0a0188dca8a05c722/src/render/ps2/SDL_render_ps2.c#L132)), while `SDL_UpdateTexture` will always require at least one copy (as also shown by [the PS2 backend](https://github.com/libsdl-org/SDL/blob/c790572674b225de34fe53c0a0188dca8a05c722/src/render/ps2/SDL_render_ps2.c#L166)).

**Comment by sdegutis** [comment]
Am I understanding this right, that LockTexture is basically the same as UpdateTexture except one less malloc? Is that the only performance gain?

**Comment by icculus** [comment]
On the software renderer, you can write directly to the final destination with LockTexture, whereas UpdateTexture will need to make a copy from your buffer to ours.

On the other renderers, it's probably the same (the GLES2 renderer, for example, literally just calls UpdateTexture for its UnlockTexture implementation)...but if you ever _need_ a software renderer, this is the thing that would benefit most from texture locking.

But in real life, with actual GPUs, it doesn't really matter a whole lot.

**Comment by icculus** [comment]
(I can also imagine scenarios where a unified memory architecture system can get the same benefit as the software renderer does, but I don't know if we actually work like that in any of our renderers.)

**Comment by sdegutis** [comment]
Cool then I'll keep a uint8_t* in memory and call UpdateTexture with that with the default renderer, which on windows apparently is directx 12.
