### ISSUE TITLE
Support for 16 and 32 bit floating point pixel formats

### ISSUE THREAD

**Issue by jdolan** [libsdl-org/SDL#8543]
Many modern games support HDR in some form or another. Often times, this requires uploading pre-calculated static lighting data (lightmaps, etc) to the GPU. These are best represented with half or single precision floating point textures, which all accelerated backends support these days, too.

However, to my knowledge, it's not possible to represent these kinds of images with SDL_Surface, which I believe is limited to the existing 4-byte SDL_PixelFormats. And so SDL3 users wanting to use HDR in their games will have to implement a separate codepath for floating point textures, which really stinks if you've found SDL_Surface quite handy and have based all of your image management around it *cough*

Is there a widely known workaround of, say, using surface-per-channel `SDL_PIXELTYPE_ARRAYF32` or do you think this is something that would be genuinely useful and not horribly difficult to add for SDL3?

**Comment by slouken** [comment]
We've added some floating point formats in SDL3, but haven't wired them up in the renderers. We plan to add that but the SDL3 list is quite long, so feel free to pitch in and propose a PR that meets your needs!

**Comment by jdolan** [comment]
Thanks. This is not even a question about renderers, honestly. Tho, of course it would make sense to support them there, too. I'm working with these floating point textures "offline" in my BSP compiler; baking HDR lightmaps for Quake :) 

I've ended up just kind of "overloading" `SDL_Surface` and assigning its pixel data to a packed RGB floating point array, like this:

```
/**
 * @brief Create an `SDL_Surface` with the given luxel data.
 */
SDL_Surface *CreateLuxelSurface(int32_t w, int32_t h, size_t luxel_size, void *luxels) {

	SDL_Surface *surface = SDL_malloc(sizeof(SDL_Surface));

	surface->flags = SDL_DONTFREE;
	surface->w = w;
	surface->h = h;
	surface->userdata = (void *) luxel_size;
	surface->pixels = luxels;

	return surface;
}
```

Where, for `RGB32F`, `luxel_size` would be `sizeof(float[3])`. This "works" just fine, and allows me to stick with `SDL_Surface` for all of my image routines. The only downside is that the SDL blitting functions won't know what to do with these surfaces because there's no `SDL_PixelFormat` that represents them -- so I had to write my own barebones blit to pack these into an atlas image:

```
/**
 * @brief Blits the `src` to the given `rect` in `dest`.
 */
int32_t BlitLuxelSurface(const SDL_Surface *src, SDL_Surface *dest, const SDL_Rect *rect) {

	assert(src);
	assert(src->pixels);
	
	assert(dest);
	assert(dest->pixels);

	assert(src->userdata == dest->userdata);

	assert(rect);

	assert(src->w == rect->w);
	assert(src->h == rect->h);

	const size_t luxel_size = (size_t) src->userdata;

	const byte *in = src->pixels;
	byte *out = dest->pixels;

	out += rect->y * dest->w * luxel_size + rect->x * luxel_size;

	for (int32_t x = 0; x < src->w; x++) {
		for (int32_t y = 0; y < src->h; y++) {

			const byte *in_luxel = in + y * src->w * luxel_size + x * luxel_size;
			byte *out_luxel = out + y * dest->w * luxel_size + x * luxel_size;

			memcpy(out_luxel, in_luxel, luxel_size);
		}
	}

	return 0;
}
```

It's very basic, with no support for scaling or changing pixel formats, but it does the job for this use case. Here's a packed lightmap atlas created from `RGB32F` with the code above, but saved to `RGB8` for web viewing:


![pits_lm_diffuse0](https://github.com/libsdl-org/SDL/assets/643118/e5592329-3ae1-4a43-b362-0228c6824b47)

So, maybe this helps refine my feature request, which I guess is really: Can SDL_Surface support > 32bpp pixel formats?

**Comment by slouken** [comment]
In theory, if someone adds support for them. :)

**Comment by slouken** [comment]
We've just added a bunch of large pixel size formats to SDL3.

Cheers!
