### ISSUE TITLE
PSP: Parameter 'sem' is invalid

### ISSUE THREAD

**Issue by AJenbo** [libsdl-org/SDL#8554]
When rendering textures I get the following spammed all over my log:
```
DEBUG: Parameter 'sem' is invalid
```

It looks like I'm not the only one either: https://github.com/libsdl-org/SDL/issues/5075#issuecomment-1041305869

It appears to be related to code in this file:
https://github.com/libsdl-org/SDL/blob/2c1fbe1967457c6b95323a5ea4136849c66bc307/src/thread/psp/SDL_syssem.c#L118

**Comment by ccawley2011** [comment]
I suspect the culprit is the `event_sem` semaphore in `src/video/psp/SDL_pspevents.c` - it's supposed to be created in `PSP_EventInit`, but that doesn't seem to be called anywhere.

**Comment by icculus** [comment]
My guess is the PSP code started as a copy of the "raspberry" or "kmsdrm" backend, which defined an `*_EventInit` function in their headers that didn't actually exist, so when they actually filled them in for PSP, there was nothing in the copied code that actually called it. (See 87875a49b4cfc277aba6d2c4c32769a29767e561)

**Comment by icculus** [comment]
Okay, this is fixed up in SDL2 and SDL3, but someone with a means to test should verify this and reopen if I made it worse.  :)

**Comment by AJenbo** [comment]
Thanks for the quick fix, I'll test as soon as I get the chance
