### ISSUE TITLE
[SDL2] [Windows] : Small memory leak

### ISSUE THREAD

**Issue by ndbn** [libsdl-org/SDL#8555]
[This](https://github.com/libsdl-org/SDL/blob/SDL2/src/video/windows/SDL_windowsmodes.c#L173) memory need to be freed somewhere, just 220 bytes, if it matter, but not a big problem

**Comment by slouken** [comment]
This should be fixed in 0ec1209eab437ebf49506f1649199f0aec9c54cb, can you confirm?

**Comment by ndbn** [comment]
Confirmed, No leaks now in my small project. Thanks!

**Comment by slouken** [comment]
You're welcome!
