### ISSUE TITLE
macOS: IOHIDDeviceGetReport is blocking when initialising a controller

### ISSUE THREAD

**Issue by vkedwardli** [libsdl-org/SDL#8558]
When a controller is connected to macOS, the init device stage would call `ReadFeatureReport` -> `hid_get_feature_report` -> IOKit's `IOHIDDeviceGetReport`, and the application would freeze until it is returned.

https://developer.apple.com/documentation/iokit/1588659-iohiddevicegetreport :
> This method behaves synchronously and will block until the report has been received from the device. This is only intended for feature reports because of sporadic devicesupport for polling input reports. Please defer to using IOHIDDeviceRegisterInputReportCallback for obtaining input reports.

**Comment by vkedwardli** [comment]
Relevant issue: https://github.com/libretro/RetroArch/issues/3660

**Comment by slouken** [comment]
I believe this is synchronous on most OSes. Is there an alternate approach that would work better?

**Comment by slouken** [comment]
What controller are you using and what is the USB VID/PID of it?

**Comment by vkedwardli** [comment]
8bitdo Zero 2 (Firmware V1.06), connected using Bluetooth 
```
  Connected:
  DUALSHOCK 4 Wireless Controller:
  Address:	E4:17:D8:23:E7:7F
  Vendor ID:	0x054C
  Product ID:	0x05C4
  Firmware Version:	1.0.0
  Minor Type:	Gamepad
  Services:	0x800020 < HID ACL >
```

**Comment by slouken** [comment]
I tested the 8bitdo Zero 2 a few days ago and it didn't hang during initialization. Maybe it's a different firmware version? What symptoms are you seeing?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.
