### ISSUE TITLE
Text input regression for Steam Deck users

### ISSUE THREAD

**Issue by JavidPack** [libsdl-org/SDL#8561]
We recently updated SDL (from v2.24.0 to v2.28.2) and received reports that Steam Deck users could no longer type text using USB keyboards. (Many Steam Deck users will dock their Steam Deck to access a larger monitor, mouse, and keyboard when at home) Eventually we narrowed down the issue to some code in SDL that seems to assume that just because the Steam Deck supports an on screen keyboard, it shouldn't initialize with `SDL_StartTextInput();` invoked. 

https://github.com/libsdl-org/SDL/blob/cc7c0a2dabe016e454e83f607465558188ed7548/src/video/SDL_video.c#L542-L551

This commit is 8 years old, but a recent commit, https://github.com/libsdl-org/SDL/commit/c4b9f621649d4e2ddb05e7f396e43e2d9e0402cc, adds logic to detect a Steam Deck and will now return true for the `SDL_HasScreenKeyboardSupport` check, resulting in `SDL_StartTextInput();` not being called.

We managed to work around the issue with the `SDL_HINT_ENABLE_SCREEN_KEYBOARD` hint added in https://github.com/libsdl-org/SDL/commit/a6a222095e85e179209b9badb611c3dbdb16ccc6 and calling `SDL_StartTextInput` directly. This combo prevents the screen keyboard from showing when `SDL_StartTextInput` is called. (https://github.com/tModLoader/tModLoader/pull/3931/files)

---

The fix is easy enough to implement on our end, but I still feel like this new behavior is a regression, and could be affecting other programs using SDL. 

I don't agree with the notion that `If we don't use a screen keyboard, turn on text input by default`. I am not familiar with all the inner workings or reasons for the behavior, but it seems like the logic is a bit too limiting. Having support for on screen keyboard shouldn't preclude normal keyboard input from working as expected. I imagine if there is a reason for this logic, there might need to be more granularity in the on screen keyboard support. Maybe separating devices that are only able to use on screen keyboards from devices that additionally support on screen keyboards.

**Comment by flibitijibibo** [comment]
I think this is the same as #6807

**Comment by slouken** [comment]
There is a little more complexity here, as starting text input also means turning on IME processing, so things like a Chinese IME would start interpreting WASD key presses as Chinese character composition.

Out of curiosity, if you just enable text input events, does it work the way you want?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and moving this to the next milestone.

**Comment by JavidPack** [comment]
> There is a little more complexity here, as starting text input also means turning on IME processing, so things like a Chinese IME would start interpreting WASD key presses as Chinese character composition.
> 
> Out of curiosity, if you just enable text input events, does it work the way you want?

I believe it does work the way we want, as doing that restores the old logic that the game currently expects. I haven't tested IME much on the Steam Deck, but I'll mention anything here if the workaround I made causes any issues for our users. Our fix has been live for our users but I haven't seen any reports, but that could just be because steam deck + IME would be pretty rare.

**Comment by bertogg** [comment]
Hi, this problem has been reported with a bunch of different games (I verified it myself with Portal 2 and GZDoom), I can work it around by setting `SteamDeck=0` in the environment when I launch the game.

**Comment by slouken** [comment]
I added a general fix for this in 4ff3b2827, thanks! Please let me know if this has any undesirable side effects.

**Comment by irov** [comment]
@slouken This commit implements automatic keyboard display when the application is restored from the task manager on Android. Because setup event state SDL_TEXTINPUT to SDL_ENABLE.

SDL_IsTextInputActive always return TRUE

and 

void Android_PumpEvents_Blocking(_THIS)
...
            /* Make sure SW Keyboard is restored when an app becomes foreground */
            if (SDL_IsTextInputActive() &&
                SDL_GetHintBoolean(SDL_HINT_ENABLE_SCREEN_KEYBOARD, SDL_TRUE)) {
                Android_ShowScreenKeyboard(_this, Android_Window); /* Only showTextInput */
            }
            
Show keyboard after restoring.

Thanks
