### ISSUE TITLE
The mouse-down event is not generated in a certain situation

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#8562]
I've encountered some strange, incorrect behavior of the SDL event system. If I have automatic mouse capture enabled in SDL, thanks to the `SDL_HINT_MOUSE_AUTO_CAPTURE` hint, everything works very well. However, if I turn off this hint, strange things happen. It can be reproduced this way:

- place the cursor over the client area of the window,
- press and hold the left mouse button,
- while holding, move the cursor outside the window,
- release the button when the cursor is outside the window,
- move the cursor back over the client area of the window,
- press the left mouse button — **the `SDL_MOUSEBUTTONDOWN` event will NOT be generated,**
- release the button — **the `SDL_MOUSEBUTTONUP` event will be generated,**
- press it again — then the event will be generated (and all subsequent ones too).

I thought my code was to blame, but I put a breakpoint in the event handling code and in fact the first mouse down event (after the cursor returns from outside the window) is not emitted. I am using **SDL 2.28.5** library under Windows 10, 64-bit.

I checked this behavior in a test application and confirmed that it was an SDL issue. I recorded everything in the test application. I don't know if you will understand what I mean, if not, see the description in the points above.

![mouse-down event bug](https://github.com/libsdl-org/SDL/assets/8170730/b94fcc3f-b591-48e8-bc8c-4ed1cbf404d8)

Source code of this test program is here:

```pascal
program mctest;

{$mode objfpc}{$H+}

uses
  SDL2;
var
  Window:  PSDL_Window;
  Event:   TSDL_Event;
  Running: Boolean = True;
begin
  if SDL_Init(SDL_INIT_EVERYTHING) <> 0 then exit;

  Window := SDL_CreateWindow('mouse capture test', SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 600, 450, 0);

  if Window <> nil then
  begin
    SDL_SetHint(SDL_HINT_MOUSE_AUTO_CAPTURE, '0');

    while Running do
    begin
      while SDL_PollEvent(@Event) = 1 do
      case Event.type_ of
        SDL_MOUSEBUTTONDOWN: WriteLn('button pressed');
        SDL_MOUSEBUTTONUP:   WriteLn('button released');
        SDL_QUITEV:          Running := False;
      end;

      SDL_Delay(10);
    end;

    SDL_DestroyWindow(Window);
  end;

  SDL_Quit();
end.
```
Compiled application for testing — [mouse-down bug.zip](https://github.com/libsdl-org/SDL/files/13370421/mouse-down.bug.zip)

**Comment by slouken** [comment]
This is not a bug, by default the first click activates the window. You can set the hint `SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH` to change this behavior.

**Comment by furious-programming** [comment]
> This is not a bug, by default the first click activates the window.

Yes, the first click activates the window but, the problem is that in this case, **the window does not lose focus** — it is still active (look at the window caption bar) and receives input from the keyboard. If the window lost focus, the caption bar would change its appearance and the keyboard input would not be processed by this window. Setting the hint `SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH` does not change anything here. This problem affects all mouse buttons, not just the left one.

I prepared a second demo, adding keystroke logging code to confirm that the window is still active and capturing keyboard input:

```pascal
program mctest;

{$mode objfpc}{$H+}

uses
  SDL2;
var
  Window:  PSDL_Window;
  Event:   TSDL_Event;
  Running: Boolean = True;
begin
  if SDL_Init(SDL_INIT_EVERYTHING) <> 0 then exit;

  Window := SDL_CreateWindow('mouse capture test', SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 600, 450, 0);

  if Window <> nil then
  begin
    SDL_SetHint(SDL_HINT_MOUSE_AUTO_CAPTURE,       '0');
    SDL_SetHint(SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH, '1'); // "0" or "1", the same behaviour.

    while Running do
    begin
      while SDL_PollEvent(@Event) = 1 do
      case Event.type_ of
        SDL_MOUSEBUTTONDOWN: WriteLn('"', Event.Button.Button, '" button pressed');
        SDL_MOUSEBUTTONUP:   WriteLn('"', Event.Button.Button, '" button released');
        SDL_KEYDOWN:         WriteLn('"', Event.Key.KeySym.Scancode, '" key pressed');
        SDL_KEYUP:           WriteLn('"', Event.Key.KeySym.Scancode, '" key released');
        SDL_QUITEV:          Running := False;
      end;

      SDL_Delay(10);
    end;

    SDL_DestroyWindow(Window);
  end;

  SDL_Quit();
end.
```
The effect is the same:

![mouse-down event bug](https://github.com/libsdl-org/SDL/assets/8170730/bb9167c0-977d-4595-9fdf-2a63a295beb2)

There is clearly a problem with this, but I'm not sure why it works this way — whether the problem is with SDL or with the Windows shell. If the window lost focus, I wouldn't blame it, but currently it looks like a bug and works completely unintuitively.

Compiled demo — [mouse-down bug.zip](https://github.com/libsdl-org/SDL/files/13377650/mouse-down.bug.zip)

**Comment by slouken** [comment]
You only get mouse release events outside your window if you have the mouse captured. This is the way Windows works.

Thanks for the detailed example!

**Comment by furious-programming** [comment]
So this is not a problem, just the default behavior of Windows. It's best to just make sure that the `SDL_HINT_MOUSE_AUTO_CAPTURE` hint is enabled and then there will be no problem with capturing. Thank you for the answer!

**Comment by slouken** [comment]
You're welcome!
