### ISSUE TITLE
Windows: Candidate list for [MonoGame] immediately disappears/flickers in fullscreen windows

### ISSUE THREAD

**Issue by shshshdy** [libsdl-org/SDL#8563]
[test-win-x64.zip](https://github.com/libsdl-org/SDL/files/13371953/win-x64.zip)

The candidate list is displayed normally in window mode, and in the attached example, it flashes when F2 is in full screen mode.

**Comment by slouken** [comment]
The OS UI for IMEs does not work in fullscreen mode. SDL3 has added SDL_EVENT_TEXT_EDITING_CANDIDATES so you can draw your own candidate list in fullscreen mode.
