### ISSUE TITLE
No way to distinguish between EOF and error condition after RWops operations.

### ISSUE THREAD

**Issue by dtromb** [libsdl-org/SDL#8564]
It seems like it is currently impossible to tell when an RWops operation encounters an error condition, because the functions return the same error code on EOF and error.

For example, from the documentation:

> read is a function pointer that reads from the stream. It reads up to num objects each of size bytes into the buffer pointer to by ptr. Returns the number of objects read, which may be less than requested. Returns 0 on error or EOF.

Since there is no way to tell if or not EOF or end of stream has occurred for an abstract RWops (for which this notion makes sense), we are left guessing.

One might think to do some elaborate workaround like record the error state before every call to a RWops function, check if it changed, and assume it was an EOF condition if it has not, restoring it after.   Besides being a terrible hack, this does not work.  It relies on all of the implementations always setting the error condition when they return zero on error, and a quick code survey shows that this is definitely not the case:

    // SDL_rwops.c:214
    if (context == NULL || context->hidden.windowsio.h == INVALID_HANDLE_VALUE || !total_need) {
        return 0;
    }

The RWops abstraction is a good idea (to the point of necessary), and I'd like to use it throughout my project.  But this limitation makes that - and any fully abstract use of RWops - impossible, I think.   

What is needed is one of the following:

1) a way to query an arbitrary RWops for EOF or end-of-stream condition.   This could be done with a new RWops field "is_eof":  `int (*is_eof)(SDL_RWops*)`, returning zero if the end-of-file condition has not been encountered, or nonzero otherwise (including the case that the stream implementation does not EOF)

2) establishment of a constant RWOPS_EOF which is returned instead of zero on end-of-file or end-of-stream. 

In either case, this would unfortunately mean touching all of the extant RWops implementations.   Happy to do a PR / test cases, this is a blocker on my current project and absent some workaround I'm missing I'll have to otherwise do it anyway, in a private fork...

**Comment by icculus** [comment]
I kinda agree...I really wish we hadn't removed the ability to return -1 on error here, both from an interface and implementation standpoint.

Can we revisit this?

**Comment by slouken** [comment]
We have this:
https://github.com/libsdl-org/SDL/blob/f61c0f3dc1a8c63c83129a1c3176e00bdbecff87/include/SDL3/SDL_rwops.h#L53

**Comment by dtromb** [comment]
@slouken  Are you saying that this issue has been fixed in SDL3, and all of the RWops implementations now return SDL_RWOPS_STATUS_EOF  on EOF condition?     If so, could you link the issue where this was implemented?   I searched but couldn't find it.     (I'm using SDL2 currently, there is no such constant...)

**Comment by slouken** [comment]
Yes, this is fixed for SDL3, sorry for not clarifying.

**Comment by dtromb** [comment]
Will the docs be updated to reflect, perhaps?

**Comment by slouken** [comment]
In SDL3, you can just check the status field of the SDL_RWops object. Yes, we should really update the docs ;) I'll reopen this to capture that work.
