### ISSUE TITLE
Touchpad (a.k.a.) trackpad support, and touchscreen 

### ISSUE THREAD

**Issue by c-smile** [libsdl-org/SDL#8567]
As far as I understand Touchpad is currently supported only on MacOS. 

Windows does not provide meaningful API for touchpad except of following options:

### 1. Raw input using WM_INPUT. 

That's quite unreliable.  In my [Sciter](https://sciter.com) I've made an attempt to use it but 

1. Quite a mess. You'll get touch/finger coordinates and should do gesture recognition on your side. Doable but could off the platform style.
2. Works only for so called precision touchpads, synaptics touchpad drivers is one big mystery shrouded in darkness.

### 2. Use of DirectManipulation COM API

That's more practical (read "reliable") and I've ended up using it in Sciter. But you will get only high level gesture events this way.

That rises the following problem:

In order to support Touchpad and also Touchscreen SDL should have high-level  EVENT_GESTUREs instead of raw touch events.

### Practical solution

All major UI platforms ( Windows, MacOS/iOS, Linux, Android ) have touch event recognizers already.

Common denominator between platforms and touch devices are following gesture events:

* TOUCH_START - user have touched the device somehow;
* TOUCH_PRESS - touch start (usually single finger), close to MOUSE_DOWN by nature.
* TOUCH_PAN - scroll by touch;
* TOUCH_SWIPE - fast move/scroll;
* TOUCH_PINCH - either zoom or rotate gesture;
* TOUCH_END - user's hands are off the device;

In principle I can add support of gestures to SDL3 if that makes sense and is somehow on the track/plans. Please, let me know.

**Comment by icculus** [comment]
We're tracking this in #7706
