### ISSUE TITLE
Luna controller guide button sends keyboard homepage button in bluetooth mode?

### ISSUE THREAD

**Issue by Bitwolfies** [libsdl-org/SDL#8578]
Using Linux here, when the controller is wired the guide button is enabled and the mic button does nothing, this is because it uses the xpad driver, which makes sense.

However in Bluetooth mode, the mic button does work, but guide does not, with Steam even opting to use the mic button as its guide. 

Using Duckstation, we can see that when guide is pressed in BT mode, it sends a keyboard home press?
![Screenshot_20231117_192520](https://github.com/libsdl-org/SDL/assets/65789901/1fe9d5b7-bff7-41a8-996a-1e39e5299911)

Unsure if this is intended or not. Controller is on the latest app firmware.

**Comment by slouken** [comment]
SDL has no control over whether a controller sends input as a keypress.
