### ISSUE TITLE
[SDL 3.x]SDL_HideCursor() and SDL_SetRelativeMouseMode() show a "Black square Cursor" in vulkan application

### ISSUE THREAD

**Issue by ySion** [libsdl-org/SDL#8583]
I tried to call SDL_SetRelativeMouseMode to limit cursor at center and hide it, then cursor become a black square.
then I try SDL_HideCursor() to test it, it causes the same result.

### SDL_SetRelativeMouseMode :
![anim](https://github.com/libsdl-org/SDL/assets/39912009/9759afd5-bc93-4ef3-812b-c932437a7b1a)

### SDL_HideCursor:
![anime2](https://github.com/libsdl-org/SDL/assets/39912009/7ad5dd8e-7bd8-47f5-bf2b-f9e5e9aaaded)

### Relative code:
```c++
SDL_Window* window = SDL_CreateWindow("Hello", width, height, SDL_WINDOW_VULKAN);
SDL_ShowWindow(window);

bool relta_mouse_mode = false;
SDL_SetCursor(SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_HAND));

auto logic_func = [&](const SDL_Event& sevent) { // call every frame
	if (sevent.type == SDL_EVENT_MOUSE_BUTTON_DOWN) {
		if (sevent.button.button == SDL_BUTTON_MIDDLE) {
			SDL_HideCursor();
			//SDL_SetRelativeMouseMode(SDL_TRUE);
			relta_mouse_mode = true;
		}
	}else if (sevent.type == SDL_EVENT_MOUSE_BUTTON_UP) {
		if (sevent.button.button == SDL_BUTTON_MIDDLE) {
			//SDL_SetRelativeMouseMode(SDL_FALSE);
			SDL_ShowCursor();
			relta_mouse_mode = false;
		}
	} else if (sevent.type == SDL_EVENT_MOUSE_MOTION) {
		if (relta_mouse_mode) {
                      /* do something */
		}
	}
}
```
### Environment 
- System: Windows 11
- GPU: AMD 6800xt
- CPU: AMD 3950x
- Version: 3.x
- Vulkan version: 1.3

**Comment by slouken** [comment]
This is fixed in the latest commits, thanks!
