### ISSUE TITLE
Windows Precision Touchpad wrongly reports clicks when primary mouse buttons are swapped and relative mode is enabled

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#8597]
Originally reported in https://github.com/ppy/osu/issues/25527.

This issue uses the following terminology:
- primary action - the traditional left click, action is select/open, maps to `SDL_BUTTON_LEFT` (`1`)
- secondary action - the traditional right click context action, maps to `SDL_BUTTON_RIGHT` (`3`)
- left/right button/click - the button that is physically on the left/right

**When:**

1. The primary mouse button is set to `Right`
   - Control panel: `main.cpl` → `Switch primary and secondary buttons`
   - Windows 10: `Settings` → `Devices` → `Mouse` → `Select your primary button`
   - Windows 11: `Settings` → `Bluetooth & devices` → `Mouse` → `Primary mouse button`
2. Relative mouse mode is enabled
3. The touchpad is
   - tapped with one finger
   - tapped with two fingers
   - clicked in the centre / regular area (if the touchpad supports clicking-in the surface)
   - clicked in the bottom / virtual button area (this area is separated into the left and right virtual button)

Then the click or tap will result in the wrong action (primary action instead of the secondary, and vice-versa).

For example:
- tapping or clicking the touchpad will result in the secondary action, even when a user would always expect the action to be the primary
- taping with two fingers will result in the primary action
- clicking the left virtual button will result in the primary action

---

I have tested this on latest `main` and on `SDL2` using `testwm` by observing the printed `SDL_BUTTON` values. Note that when it behaves as expected (left is primary, relative mode is disabled, or regular mouse buttons are clicked), `SDL_BUTTON`s of `SDL_GetMouseState` and `SDL_GetGlobalMouseState` will match. With buggy behaviour, the two will not match (eg. the regular will show `SDL_BUTTON(1)` while the global shows `SDL_BUTTON(3)`).

I have not tested physical touchpad buttons, but a friend will help me out with this soonish. (Don't confuse [track point](https://en.wikipedia.org/wiki/Pointing_stick) buttons commonly found on ThinkPads with touchpad buttons.)

**Comment by Susko3** [comment]
I've had a friend test out, they have physical buttons specifically for the touchpad on their laptop. Here are the results:
- taps match the testing above (same as the OP)
- physical buttons behave the same as virtual buttons
  - left button is (unwantedly) the primary action
  - right button is secondary action

**Comment by slouken** [comment]
I think this will work to detect touchpad input. Please let me know if this doesn't work!

**Comment by Susko3** [comment]
Tested to work correctly on a touchpad. [MSDN](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawinputheader#remarks) also mention the `hDevice == NULL` check:
>`hDevice` can be zero if an input is received from a precision touchpad.

I presume `hDevice` is null iff the events are synthesised (not coming from a real "raw input" device). I can confirm that `hDevice` is null when using a touchscreen (no regressions here).

But I'm wondering if this fix negatively affects remote desktop, because those events can also be considered synthesised. I know swapping mouse buttons is already really weird as the resulting button is a function of the swap mouse button setting in the client PC, the client Remote Desktop app, and the server PC.

![image](https://github.com/libsdl-org/SDL/assets/16479013/a46eee56-d087-4cd5-83b4-67a4a60af623)
