### ISSUE TITLE
build for androd      couldn't find "libhidapi.so"

### ISSUE THREAD

**Issue by springtom** [libsdl-org/SDL#8598]
SDL error
      An error occurred while trying to start the application.Please try again and /or reinstall
      Error:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.libsdl.app-2/base.apk"],nativeLibraryDirectories=[/data/app/org/libsdl.app-2/lib/arm64,/system/lib64,/vendor/lib64,/system/vendor/lib64,/product/lib64]]] count`t find "libhidapi.so"

**Comment by madebr** [comment]
Can you update SDL2 to a recent version? Hidapi is embedded into the SDL2 shared library nowadays.

If not, make sure `libhidapi.so` is built as part of SDL2 and pacaged in the apk.

**Comment by icculus** [comment]
Yeah, this is either upgrade to the latest SDL2, or make sure you didn't forget to package libhidapi on older versions.
