### ISSUE TITLE
issues 16000HZ to 48000HZ

### ISSUE THREAD

**Issue by birdhello** [libsdl-org/SDL#8606]
android-19
SDL: 2.26.1、2.26.5、2.28.5 ; function: SDL_ConvertAudio
SDL: 3.0.0; function: SDL_ConvertAudioSamples

src format:
sample rate: 16000HZ
channel count: 1
format: S16LE
dest format:
sample rate: 48000HZ
channel count: 2
format: F32LE

装换后的声音存在噪音转换后的声音存在噪音
[33.mp3.zip](https://github.com/libsdl-org/SDL/files/13445909/33.mp3.zip)

**Comment by slouken** [comment]
What was the issue?

**Comment by birdhello** [comment]
> 问题出在哪里？

The problem arises in pcm conversion

**Comment by jfmu** [comment]
Is he maybe using the SDL_ConvertAudioSamples function to convert audio in blocks? @birdhello Sample code would be very great to see what you are doing.

SDL_ConvertAudioSamples is not supposed to be used in a streaming fashion. If you are doing it like that, use SDL_AudioStream.

**Comment by icculus** [comment]
My other guess is that maybe @birdhello is send MP3 data into SDL_ConvertAudio, but that function only deals with converting PCM data between two audio formats, and does not decode MP3s.

I'm going to close this for now, but if new information comes that helps reveal a bug in SDL, we can definitely reopen this issue!
