### ISSUE TITLE
SDL under Windows_ Joystick Rumble interface, parameter duration_ MS does not take effect, calling the interface handle to fix the vibration for a period of time

### ISSUE THREAD

**Issue by kc991229** [libsdl-org/SDL#8607]
SDL under Windows_ Joystick Rumble interface, parameter duration_ MS does not take effect, calling the interface handle to fix the vibration for a period of time
At the same time, after the first vibration, calling the interface again will not cause any vibration
Do you have a partner who can help with the answer

**Comment by slouken** [comment]
Are you calling SDL_PollEvent() or SDL_JoystickUpdate()?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.
