### ISSUE TITLE
Mouse clicks not reported because mouse is misdetected as a pen

### ISSUE THREAD

**Issue by tilman3** [libsdl-org/SDL#8611]
With SDL 42a8139fd662c I am only seeing mouse events SDL_EVENT_MOUSE_BUTTON_DOWN, SDL_EVENT_MOUSE_BUTTON_UP when the *first* mouse button (left mouse button) is pressed/released. Clicking the other buttons does not generate SDL_EVENT_MOUSE_* events, but SDL_EVENT_PEN_DOWN/_UP instead.

I believe the root issue is that the mouse is mistaken for a pen.

I'm seeing this behavior on a Linux system running X11 with xinput 1.6.4.

**Comment by sylware** [comment]
I seems that may be why my input (mouse+keyboard) is completely broken in dota2/cs2 (my keyboard is emitting tons of weird controls and stuff too). Have to test it but I am already fixing alsa dmix multi-channel support in SDL3 and got grabbed by IRL stuff and other software issues. Will be back soon.
