### ISSUE TITLE
iconv fails to be detected when compiling with clang >=15

### ISSUE THREAD

**Issue by CasualPokePlayer** [libsdl-org/SDL#8614]
https://github.com/libsdl-org/SDL/blob/42a8139fd662cefd32f851af95cc44f546c5834a/CMakeLists.txt#L1107-L1108
iconv_open returns a pointer, and main returns int. While gcc and < clang 15 will just emit a warning over this, clang >= 15 by default will error over such an implicit conversion, resulting in iconv failing to be detected.

**Comment by sezero** [comment]
Fixed in SDL2 branch as of https://github.com/libsdl-org/SDL/commit/bbcf40e811785400df741023c4437762dc9ea4b0, and in main (SDL3) branch as of https://github.com/libsdl-org/SDL/commit/d486de634917b80c53362d0f62a9d1f762c8f4fb. Thanks,
