### ISSUE TITLE
CI: macOS runners have been failing frequently because of a brew failure

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#8615]
.. which is truly annoying.

See, e.g., https://github.com/libsdl-org/SDL/actions/runs/6992014582/job/19023703000
which succeeded after the 5th re-try:
```
Pouring python@3.11--3.11.6_1.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
```

Googling results in https://github.com/actions/setup-python/issues/577
.. which is most recent and relevant. See, e.g., the latest commits
referenced in there.

Also see:
https://discuss.circleci.com/t/homebrew-error-the-brew-link-step-did-not-complete-successfully-trying-to-install-ffmpeg/39727
.. where the given advice is running `brew update` before `brew install`

Also see:
https://support.circleci.com/hc/en-us/articles/360043542933--Error-The-brew-link-step-did-not-complete-successfully-When-Installing-Python
... where the given advice is runing `brew unlink python@2` before installs

CC: @madebr

**Comment by madebr** [comment]
I tried [this](https://github.com/madebr/SDL/commit/5ff4f2ea99244a90ac9e353712396520a1c9f1ae) but it did not solve the python issue.
It's  python 3.11 that is causing issues.

Then I tried disabling dependent checks https://github.com/madebr/SDL/commit/20d0758baf5ffa8975c75b99b73a1bff158e57f0
which succeeds..
https://docs.brew.sh/Manpage#install-options-formulacask-

**Comment by madebr** [comment]
I pushed c4ca64deaf556ad298cdd4f226ba838dec7ffb0b to main.
I'm not 100% confident this fixes the current brew error.

**Comment by sezero** [comment]
Here is a surprise: https://github.com/libsdl-org/SDL/actions/runs/6993539025/job/19026336102

**Comment by madebr** [comment]
Let's hope these errors are the exception.
If not, I suppose we can retry a few times.

**Comment by sezero** [comment]
> Let's hope these errors are the exception. 

Looks like it: the 2nd re-run of netbsd workflow succeeded

**Comment by sezero** [comment]
It seems to be going good so far.

Closing for now. We'll reopen if it hits back.
