### ISSUE TITLE
GameCube Controller Adapter appears to invert Y axis inputs

### ISSUE THREAD

**Issue by CasualPokePlayer** [libsdl-org/SDL#8617]
The SDL2 SDL_GameController API normally has the Y axis produce negative values on going Up and positive values on going Down. Indeed, an Xbox One Controller used under this API seems to produce -/+ for U/D. However, the GameCube Controller Adapter (used in Wii U mode) appears to not follow this, resulting in an inverted Y axis compared to other controllers under the SDL_GameController API. This is consistent in both the Left and Right sticks.

I haven't checked the SDL3 SDL_Gamepad API to see if the same issue occurs there, although it probably does.

**Comment by slouken** [comment]
Which specific GameCube Controller Adapter? I tested 3 different ones (2 Evoretro adapters and the official Nintendo adapter) and they all worked correctly here.

**Comment by CasualPokePlayer** [comment]
Reportedly it's some Mayflash adapter although looking at it closely appears to indicate it is some kind of knock off. It does however report itself using USB_VENDOR_NINTENDO/USB_PRODUCT_NINTENDO_GAMECUBE_ADAPTER within its "Wii U/NS" mode.

FWIW, it seems to be working correctly under Dolphin (which has its own implementation of dealing with the official GC Adapter / Wii U/Switch mode Mayflash adapters).

**Comment by CasualPokePlayer** [comment]
Looking at the code
https://github.com/libsdl-org/SDL/blob/bbcf40e811785400df741023c4437762dc9ea4b0/src/joystick/hidapi/SDL_hidapi_gamecube.c#L362-L377
Are any corrections supposed to be happening at this stage? The GC controller has Right/Up orientation natively (like the behavior I'm seeing), rather than Right/Down orientation that SDL_GameController expects.

**Comment by CasualPokePlayer** [comment]
> Are any corrections supposed to be happening at this stage? The GC controller has Right/Up orientation natively (like the behavior I'm seeing), rather than Right/Down orientation that SDL_GameController expects.

Ah, nevermind, it would appear it is supposed to be corrected by the internal game controller db mapping, which would invert the y axises (so matching what is expected from SDL game controllers)
https://github.com/libsdl-org/SDL/blob/bbcf40e811785400df741023c4437762dc9ea4b0/src/joystick/SDL_gamecontrollerdb.h#L702

However, if I try to query the mapping (with SDL_GameControllerMappingForDeviceIndex), I don't get the entry in the db, rather I get this one: https://github.com/libsdl-org/SDL/blob/bbcf40e811785400df741023c4437762dc9ea4b0/src/joystick/SDL_gamecontroller.c#L575

**Comment by slouken** [comment]
You're right, the built in mapping was just wrong, and that was hidden by the fact that there was a Linux-specific override mapping that corrected it.

I believe this is fixed now, can you double check with the latest code?

**Comment by CasualPokePlayer** [comment]
Yes, it seems to be fixed.

**Comment by slouken** [comment]
Great, thanks!
