### ISSUE TITLE
SDL doesn't see valid parameters for the "PS5 DualSense Wireless Controller"

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#8619]
I'm testing a new PS5 controller and from what I've researched, several parameters of this controller are not visible to SDL. For testing, I use the stable version of SDL, from the latest official release — version 2.28.5.0

I listed all the parameters of this controller using SDL functions:

```
          name: DualSense Wireless Controller
          type: Game Controller
           LED: no
        rumble: no
trigger rumble: no
          axes: 6
         balls: 0
          hats: 0
       buttons: 17
   instance id: 0
          guid: 030057564c050000e60c000000006800
       VID/PID: 0x054c/0x0ce6
```
These parameters seem to be incorrect:

```
           LED: no    // should be yes
        rumble: no    // should be yes
trigger rumble: no    // should be yes
          hats: 0     // should be 1
       buttons: 17    // should be 14
```
This is what the controller looks like in the **Game Controllers** tool in Windows 10:

![image](https://github.com/libsdl-org/SDL/assets/8170730/4fa72bd7-4457-4154-be2f-517efe0f7271)

**Comment by slouken** [comment]
By default SDL will not enable advanced reports, to preserve compatibility with DirectInput games. If you want to enable them (and break DirectInput games) you can do that by adding this code before `SDL_Init()`:
```c
SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE, "1");
SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE, "1");
```

**Comment by furious-programming** [comment]
Enabling those hints does not change anything. The gamepad is still seen without the hat and with 17 buttons.

**Comment by slouken** [comment]
Can you debug it and see what's going on?

**Comment by slouken** [comment]
That is actually the correct number of buttons, but with those hints set you should see LED support enabled.

**Comment by furious-programming** [comment]
> Can you debug it and see what's going on?

Unfortunately not. Firstly, I use Free Pascal and I have neither C tools nor knowledge, and secondly, I borrowed the DualShock controller and unfortunately I have already returned it. If the opportunity arises, I will borrow it and test it.

> That is actually the correct number of buttons, but with those hints set you should see LED support enabled.

If I set the hints you provided, the only change is that `SDL_JoystickHasLED` returns `true` (correct) and `SDL_JoystickHasRumble` returns `true` (also correct). I don't know whether this controller supports rumble triggers or not, but after enabling these HIDAPI hints, the `SDL_JoystickHasRumbleTriggers` function still returns `false`. I'm pointing it out to be clear.

The biggest problem is that the `SDL_JoystickHasHat` function always returns `false` and the `SDL_JoystickNumHats` function always returns `0`, regardless of whether I enable the hints you provided or not. This gamepad has one POV hat, so SDL should see it.

Also, in theory, this controller has `14` buttons (that's how the system tool sees it), so I don't know what to think about the fact that SDL sees `17` buttons.
___

It would be best if someone with this gamepad — [PS5 DualSense™ Wireless Controller](https://direct.playstation.com/en-us/buy-accessories/dualsense-wireless-controller) — checked whether the above-mentioned functions return different values than mine. Especially someone who would be able to debug SDL code.

**Comment by slouken** [comment]
Ah, okay, this sounds correct. You're seeing LED and rumble false when the PS5 rumble hint is off and they're true when the hint is on. SDL treats the hat as 4 D-Pad directional buttons, so all is well.

**Comment by furious-programming** [comment]
So the hat should not be available for this controller?

**Comment by slouken** [comment]
That's correct.

**Comment by furious-programming** [comment]
I understand and I don't understand at the same time.

Why should a controller with a POV hat be seen as a controller without a POV hat? The current behavior of SDL with this gamepad causes a huge problem, because `SDL_JoyHatEvent` events will not be generated at all when pressing the D-Pad.

Forgive me for bothering you, but this is illogical to me and makes it very difficult for me to work on my engine code.

**Comment by slouken** [comment]
The D-Pad is represented on various systems as both a hat and a set of directional buttons. To simplify the gamepad API, SDL has opted to treat it as buttons.

**Comment by furious-programming** [comment]
Yes, maybe it simplifies the gamepad API, but now it is impossible to handle D-Pad with a joystick API.

**Comment by slouken** [comment]
Mmmm, good point.

**Comment by slouken** [comment]
Can you enter a new issue for that, and I'll look at changing that for SDL3?

**Comment by furious-programming** [comment]
Done. I hope that this problem doesn't affect many types of controllers and that those two APIs (joystick and gamepad) can be easily reconciled.
