### ISSUE TITLE
SDL_RenderSetScale enlarging results in blurred font

### ISSUE THREAD

**Issue by huabanlu** [libsdl-org/SDL#8625]
I developed the game at 480 × 270 resolution. Then use `SDL_RenderSetScale` to enlarge the image to fit various screens. Because the footage is pixel-style, it looks acceptable when enlarged. But when the font is enlarged, it becomes blurry. I used `SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "0");`

**Comment by icculus** [comment]
Did you mean to close this issue, @huabanlu?

**Comment by slouken** [comment]
@huabanlu, you're using SDL3 in this case, correct?

**Comment by slouken** [comment]
Great!
