### ISSUE TITLE
Video capture change wishlist

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8626]
I said I wanted to do some revisions to the video capture code once it was in main and didn't need to keep updating the Pull Request to keep up, and here I am.

This is my list, but I'd like to hear from @1bsyl and @slouken before I start on any of them. A lot of this is informed by the audio subsystem rework, so it's reasonable to say "this is different because cameras are different" and we'll move on.

Here goes.

***EDIT: checklist moved to #8633 where the work is happening.***

**Comment by slouken** [comment]
Yes to all of these. :)

**Comment by Starbuck5** [comment]
On Windows support:
I have prior art to share (I might've linked this a long time ago on the videocapture PR too)-- pygame-ce has a Windows webcam implementation written by me. https://github.com/pygame-community/pygame-ce/blob/main/src_c/camera_windows.c

It uses Microsoft Media Foundation, in C, which is unusual, all the examples are in C++ last I checked. It needed some tricks to work in C.

I would be interested in contributing a windows backend to SDL videocapture, but I'd need some help to get it fully mergeable, I haven't contributed anything large to SDL before.

**Comment by Starbuck5** [comment]
> Should this be named "Camera" instead of "VideoCapture"? I kind of regret using the word "capture" in the audio subsystem but feel like we're probably just stuck with it now. (I know not everything is a camera that generates video frames, but still.)

In pygame and pygame-ce, it's called camera, but we frequently get people think it refers to "game cameras" e.g. the system that determines what part of the world to render.

*Not advocating for either, just bringing that up.

**Comment by ericoporto** [comment]
Like Game Controller usually means something different, enough to have SDL Game Controller renamed for Gamepad, I think VideoCapture is better than Camera - it may not be much an issue now but as soon the 3D part of SDL is done people will talk about cameras in that and it will get confusing.

**Comment by icculus** [comment]
We have merged #8633, so this can close.
