### ISSUE TITLE
Backport GamePad "type:" parser to 2.0

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL#8629]
In fussing with Steam Input one more time, it occurred to me that Steam could pass the real controller type to applications via the mapping rather than my earlier attempt to get it via the device (#6068). Turns out this got implemented in 3.0, so it'd be great to backport this since it shouldn't affect compatibility in either direction. Looking at the current virtual mappings I don't think Steam is passing this, but it'd be great if it did!

**Comment by flibitijibibo** [comment]
Slapped together #8631, definitely needs testing first!

**Comment by slouken** [comment]
This idea is interesting, but wouldn't work with multiple controllers of different types. Even if we had a way to solve that, users can move controllers between slots without causing the game to reopen the device, so this potentially needs to handle dynamic controller type changes.

**Comment by slouken** [comment]
That said, this might be useful in general, so I'm happy to merge for 2.30 once you've tested to your satisfaction.

**Comment by flibitijibibo** [comment]
I wonder if it'd be possible to send an event noting an update to the config hint, so that when the virtual slot layout changes it can run the update routine like it does for other database updates. That'd probably be 3.0 territory though - I'd just be happy to have the single-player use case handled, since it enables us to tick the box for PlayStation support on Steam without having to forcibly disable Steam Input.

Will test this within the next couple days!

**Comment by flibitijibibo** [comment]
Fixed by #8631, at least on the SDL side - if this gets added to Steam I can test ASAP.
