### ISSUE TITLE
Building tests in parallel breaks CI

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8635]
It looks like building the tests in parallel will frequently causes file copy to fail because multiple files are being copied at the same time, e.g. https://github.com/libsdl-org/SDL/actions/runs/7019723795/job/19097813233#step:6:225

Should we have a single file copy target, or build tests single-threaded, or is there another solution for this?

**Comment by madebr** [comment]
SDL3: fea6e7afb1c13326f463aef47ecd26396d1e3a2f
SDL2: 01346723455a37c1cd14bba28ebeffe268002bcd

**Comment by slouken** [comment]
Thanks!
