### ISSUE TITLE
docs with DOS endlines

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8640]
This might be silly, but can we convert all the .md files in the docs directory from DOS endlines to Unix?

Anything that can read Markdown format on Windows can surely handle the endline difference (right...?), but I end up having to convert the files to Unix endlines, make an edit, and convert them back before diffing/committing.

**Comment by sezero** [comment]
Yes

**Comment by slouken** [comment]
Yes!

**Comment by 1vanK** [comment]
Add `.gitattributes` with content

```
* text=auto
```

to avoid this problems in future.

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

**Comment by icculus** [comment]
I assumed the docs were intentionally kept in Windows format in case someone tried to open them with Notepad.exe, but I could be wrong.
