### ISSUE TITLE
SDL_malloc, etc, should call SDL_OutOfMemory()

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8642]
All over the code we have:

```c
void *ptr = SDL_malloc(blah);
if (!ptr) {
    SDL_OutOfMemory();
    return NULL;
}
```

Shouldn't we just have SDL_malloc/realloc/calloc/etc call SDL_OutOfMemory, so we don't have to clutter up the codebase, and we don't risk forgetting to set the error state?

**Comment by slouken** [comment]
At one point those functions were `#define` as malloc and friends, so we couldn't guarantee we could run any code to handle failures. I don't think that's still the case, so maybe we can change that?

**Comment by icculus** [comment]
Ah, yeah, this is probably a holdover from 1.2.

They're always real functions now; even if they call app-supplied function pointers or dlmalloc internally, we can check the results for NULLs in a single spot now.

**Comment by icculus** [comment]
@libsdl-org/a-team Just a heads up for new rules of SDL_OutOfMemory in SDL3 (tl;dr: you probably don't have to call it directly anymore). Please read the commit message on 447b508a77b8601d23ca48cf189fe4436ab33572 for details!

SDL2 still works as it always has; this is SDL3 only.

**Comment by 1bsyl** [comment]
Maybe, we can remove the 
`#define SDL_OutOfMemory()   SDL_Error(SDL_ENOMEM)` for the public header 
so we're sure we don't use it anymore !?

**Comment by icculus** [comment]
I think it's fine to keep it. This was just about reducing mistakes by managing it ourselves on every allocation, but it's legit to use it.

(Also, I like the idea that there's a non-string way to report out of memory conditions, since currently SDL_SetError allocates memory, and we might want to change this to set a flag that makes SDL_GetError return a static "Out of memory!" string, instead.)

**Comment by slouken** [comment]
> (Also, I like the idea that there's a non-string way to report out of memory conditions, since currently SDL_SetError allocates memory, and we might want to change this to set a flag that makes SDL_GetError return a static "Out of memory!" string, instead.)

Ooh, I like that. Originally we used a static buffer to avoid memory issues, but since we changed that it’s important not to allocate memory in out of memory scenarios.

**Comment by sezero** [comment]
src/video/SDL_video_capture* and src/video/android/SDL_android_video_capture.c still call SDL_OutOfMemory

**Comment by sezero** [comment]
For sdl2-compat I pushed https://github.com/libsdl-org/sdl2-compat/commit/ab347e79a5d6fd71e846db77b5a6e30cec0f6083

**Comment by icculus** [comment]
> src/video/SDL_video_capture* and src/video/android/SDL_android_video_capture.c still call SDL_OutOfMemory

These files have been renamed and dramatically changed in another branch for #8633, so I was avoiding the pain of merging.  :)
