### ISSUE TITLE
SDL_SetError vs Out Of Memory conditions

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8648]
> Also, I like the idea that there's a non-string way to report out of memory conditions, since currently SDL_SetError allocates memory, and we might want to change this to set a flag that makes SDL_GetError return a static "Out of memory!" string, instead.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/8642#issuecomment-1833838653_

**Comment by slouken** [comment]
Implemented in 66e532fa61f7915a4f356c24789b5b79b8c9dfad
