### ISSUE TITLE
SDL_HINT_ENABLE_SCREEN_KEYBOARD not working on Android

### ISSUE THREAD

**Issue by leonstyhre** [libsdl-org/SDL#8652]
Hi!

It seems as if setting SDL_HINT_ENABLE_SCREEN_KEYBOARD to false on Android has no effect, i.e. the on-screen keyboard is still displayed.

I have tried both this in AndroidManifest.xml:
`<meta-data android:name="SDL_ENV.SDL_ENABLE_SCREEN_KEYBOARD" android:value="0" />`

As well as this in the C++ code:
`SDL_SetHint(SDL_HINT_ENABLE_SCREEN_KEYBOARD, "0");`

The only way I've found to disable the keyboard is to comment out the following line in SDLActivity.java:
`imm.showSoftInput(mTextEdit, 0);`

This is with SDL 2.28.5
SDL_HINT_ENABLE_SCREEN_KEYBOARD works fine on other operating systems, the issue is specific to Android.

Thanks!

**Comment by slouken** [comment]
This should be fixed now, can you please try out the latest SDL code?

**Comment by leonstyhre** [comment]
I tried building at this commit and also at df438a3170fcef32166e5b5e48ffeb6692b5913c but both give me a lot of linker errors like the following:

`ld: error: undefined symbol: ACaptureSessionOutput_create`
`ld: error: undefined symbol: AImageReader_acquireNextImage`

**Comment by leonstyhre** [comment]
I just tested this with the release-2.30.x branch and it works correctly as far as I can tell!

**Comment by slouken** [comment]
Great, thanks!
