### ISSUE TITLE
SDL_RendererReadPixels in combination with SDL_RenderSetLogicalSize looks to not working as expected

### ISSUE THREAD

**Issue by Raffaello** [libsdl-org/SDL#8654]
if using in combination with `SDL_RenderSetLogicalSize` let say with a value of (320,200), and using a screen resolution that is not an exact multiple of the logical size, like e.g. (800x600).
What is read from the screen is not aligned, it is like it is reading from a bigger screen, in fact, is behaving like having a 800x500 window. 
Basically the resource is 100px up of the rendered position.
e.g:
```
................
.....XXX...
................
```
after renderer read pixels those `XXX` and present the surface, those vlaues are in different position, up like:
```
.....XXX.....
..................
................
```

If there is no `SDL_RenderSetLogicalSize`, apart not rescaling the textures, the issue is not present.
So i think it is something related to `SDL_RendererReadPixels` that has an optimizaition, or not taking in consideration some fractional values as a resolution of (800x600) in logical size of (320,200) is like a 800/320=2.5 factor and that is ok for the width, but it will use the width again for the height ->2.5*200 = 500, instead of a factor of 600/200 = 3.

For the result, i think, it is like is considered a square region to read pixels, not sure why. I am not sure is the `SDL_RendererReadPixels` pixel alone. but just guessing

But it shouldn't as it should read 

The renderer driver used is DirectX9 (`-1`),

**Comment by slouken** [comment]
So this isn't technically a bug. What's happening here is that the read is going to read back the drawable area, which is offset into the window, exactly the way you've described above.

It might be surprising that it doesn't read back the pixels scaled to the logical size, but that's a side effect of how it's implemented for SDL2.

Here is a simple example demonstrating the situation. Note that the area that is being read back is `x = 0, y = 50, w = 800, h = 500`
```c
#include "SDL.h"

int main(int argc, char *argv[])
{
    SDL_Window *window;
    SDL_Renderer *renderer;
    void *pixels = NULL;
    int pitch = 0;
    int quit = 0;

    window = SDL_CreateWindow("Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 600, 0);
    renderer = SDL_CreateRenderer(window, -1, 0);
    SDL_RenderSetLogicalSize(renderer, 320, 200);
    while (!quit) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_QUIT) {
                quit = 1;
            }
        }

        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 0);
        SDL_RenderClear(renderer);

        SDL_SetRenderDrawColor(renderer, 0xff, 0xff, 0xff, 0xff);
        SDL_RenderFillRect(renderer, NULL);

        SDL_RenderReadPixels(renderer, NULL, SDL_PIXELFORMAT_RGBA32, pixels, pitch);

        SDL_RenderPresent(renderer);
        SDL_Delay(100);
    }
    return 0;
}
```
