### ISSUE TITLE
DPI and scaling

### ISSUE THREAD

**Issue by r-tmp** [libsdl-org/SDL#8661]
Not sure what I'm doing wrong here, I have 3 4K screens with scaling of 100% and 250%.
I create a window:
```C++
auto sdlWindow = SDL_CreateWindow("TEST", 800, 600, SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE
| SDL_WINDOW_HIGH_PIXEL_DENSITY);
```

I'm creates a really small window, I can get the scale and scale it up:
```C++
auto scale = SDL_GetWindowDisplayScale(sdlWindow);

SDL_SetWindowSize(sdlWindow, 800 * scale, 600 * scale);
```
Which seems about right, however creating the window then resizing it briefly shows the small window before it's resized which doesn't look great.

I thought of getting the display scale first then before creating the window, but I'm not sure how to get the display that the window is going to be created on.

Primary screen is built in and is at 100% scale, it's disabled, and the window is created on screen 2.

I'm using SDL3 (main branch).
On Windows 11 23H2 (22631.2792)

A bit more detail...
My monitors setup is as follows:
1. 3840x2160 @ 100% (Laptop screen - "disconnected").
2. 3840x2160 @ 250% (Monitor - Primary - this is where the window is created).
3. 3840x2160 @ 250% (Monitor).
![image](https://github.com/libsdl-org/SDL/assets/112827473/85aff279-22e9-44c9-8260-63b8b73cd9c3)

When I create a 800x600 window, this is what is created (you can see relative to my screen size):
![Screenshot 2023-12-05 204522](https://github.com/libsdl-org/SDL/assets/112827473/559098c4-cb86-4616-826b-0dca78623cea)

After calling resize (basically 800x600 * 2.5) and recentering the window (notice the two white lines - probably need to clear the window):

![Screenshot 2023-12-05 205040](https://github.com/libsdl-org/SDL/assets/112827473/0a72d66a-d990-46b7-918e-1de976208bd8)

I've created a 800x600 in WPF, for size comparison:
![Screenshot 2023-12-05 205535](https://github.com/libsdl-org/SDL/assets/112827473/ca54bcfa-12b5-4a02-adab-d37729787136)

**Comment by Kontrabant** [comment]
What os/window manager is this on?

**Comment by r-tmp** [comment]
Sorry, forgot to mention, this is on Windows 11.

**Comment by r-tmp** [comment]
Added further details and screenshots for clarity.

**Comment by slouken** [comment]
You can create the window hidden using the flag `SDL_WINDOW_HIDDEN` if you want to resize it after creating it, and then show it with `SDL_ShowWindow()`.
