### ISSUE TITLE
SDL 2.28.X No Longer Detects LTEK Dance Pads

### ISSUE THREAD

**Issue by dreamsyntax** [libsdl-org/SDL#8662]
Starting in PCSX2 1.7.4694 (https://github.com/PCSX2/pcsx2/pull/9181), LTEK Dance Pads are no longer detected by SDL. This applies all the way up latest which at time of writing is 2.28.5.

I was also able to confirm the Dolphin Emulator, which currently uses 2.26.5, can properly detect the gamepad. In the test branch PR for using SDL 2.29.0, the controller is also no longer detected by SDL (https://github.com/dolphin-emu/dolphin/pull/12144).

The LTEK series of controllers is currently the main recommended hard pad still on the market Q4 2023 in Dance Game communities. Many enjoy the use of these pads, directly relying on SDL for easy integration.

Windows GUID: (pending)
Linux GUID: (pending)

**Comment by slouken** [comment]
Can you try with the latest SDL2 code? We reverted the change that caused this in cc20d0147eb87f5726f073f25b6700e031d78d33.

**Comment by dreamsyntax** [comment]
> Can you try with the latest SDL2 code? We reverted the change that caused this in [cc20d01](https://github.com/libsdl-org/SDL/commit/cc20d0147eb87f5726f073f25b6700e031d78d33).

I was able to confirm this fixes the issue and the LTEK Dance are properly detected when building this commit and supplying the resulting dll to PCSX2.

**Comment by slouken** [comment]
Great, thanks!

2.30.0 is the next SDL release, and we're wrapping things up for a release next month.
