### ISSUE TITLE
ES-DE - Fails to detect controllers if Thrustmaster T.16000M is connected

### ISSUE THREAD

**Issue by mvrk69** [libsdl-org/SDL#8664]
Hi,

Emulation Station Desktop Edition on Fedora 37 fails to detect my 8bitdo pro 2 controller when Thrustmaster T.16000M + TWCS THROTTLE is connected.

Emulation Station gives this error on startup:
Dec 03 12:43:36 Error:	Couldn't add controller with device index 0
device index 0 was the Thrustmaster T.16000M.

As soon as i disconnect the thrustmaster joystick and throttle, the 8bitdo pro 2 controller is detected and works fine.

According to ES-DE developers (https://gitlab.com/es-de/emulationstation-de/-/issues/1574#note_1666873754) this is a SDL issue.

**Comment by slouken** [comment]
This is a bug in ES-DE. I'll follow up on the original bug report.
