### ISSUE TITLE
SDL2 `SDL_Vulkan_GetInstanceExtensions` does not work properly with NULL window

### ISSUE THREAD

**Issue by rongcuid** [libsdl-org/SDL#8668]
On SDL 2.26.3, 2.28.5, and presumably all prior versions), `SDL_Vulkan_GetInstanceExtensions(NULL, ...)` works only if a window has previously been created.

Minimal example:

```c
#include <SDL2/SDL.h>
#include <SDL2/SDL_vulkan.h>

void main() {
    unsigned int extensionCount;
    //SDL_CreateWindow("Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
    //                 1280, 720, SDL_WINDOW_VULKAN | SDL_WINDOW_HIDDEN);
    if (!SDL_Vulkan_GetInstanceExtensions(NULL, &extensionCount, NULL)) {
        SDL_LogCritical(SDL_LOG_CATEGORY_APPLICATION,
                "Failed to get number of instance extensions");
    }
    printf("%d\n", extensionCount);
}
```

This causes a segmentation fault. However, uncommenting the create window line will work.

**Comment by icculus** [comment]
This happens because you didn't call `SDL_Init(SDL_INIT_VIDEO)` ... SDL_CreateWindow implicitly calls SDL_Init on your behalf if necessary.

(This will still fail with the error "Vulkan is not loaded" if you _do_ call SDL_Init--SDL_CreateWindow also implicitly calls SDL_Vulkan_LoadLibrary--but it won't crash.)

**Comment by rongcuid** [comment]
Sorry, please reopen this. It was an error I made when making this minimal example. The following code exemplifies the original bug with the initialization added:

```c
#include <SDL2/SDL.h>
#include <SDL2/SDL_vulkan.h>

void main() {
    unsigned int extensionCount;
    SDL_Init(SDL_INIT_VIDEO);
    SDL_CreateWindow("Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                     1280, 720, SDL_WINDOW_VULKAN | SDL_WINDOW_HIDDEN);
    if (!SDL_Vulkan_GetInstanceExtensions(NULL, &extensionCount, NULL)) {
        SDL_LogCritical(SDL_LOG_CATEGORY_APPLICATION,
                "Failed to get number of instance extensions");
    }
    printf("%d\n", extensionCount);
}
```

Without creating window:

```
-> ./a.out
CRITICAL: Failed to get number of instance extensions
32765
```

With creating window:
```
-> ./a.out
2
```
