### ISSUE TITLE
Should SDL_SetYUVConversionMode be global state?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8669]
```c
extern DECLSPEC void SDLCALL SDL_SetYUVConversionMode(SDL_YUV_CONVERSION_MODE mode);
```

This sets the conversion mode for the whole library; should this be per-SDL_Surface in SDL3?

**Comment by slouken** [comment]
We probably need the whole colorspace/transfer function, etc., and even more data for HDR.
