### ISSUE TITLE
Handle X11 crashes in child process?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8671]
This might be a _terrible_ idea, so let's talk first and patch later.

Right now, in #8624, we have a problem where an X11 error fires and the error handler tries to reset the desktop mode and everything explodes.

Notably, the test app I listed there shows that if you change the display mode and forcibly kill the app, the system doesn't know to reset the mode, which is why that error handler is there.

So...

What if, during SDL's X11 init, we fork() and detach a child process that waits for the parent to terminate for any reason (crash, normal exit, etc), and then sets the display mode back if necessary, before _exit()ing...? Would that work?

**Comment by slouken** [comment]
I'm voting this as a terrible idea. Among other things, it can hold file descriptors open if they aren't opened with O_CLOEXEC, which can cause surprising things. Also if we're not careful, atexit handlers could be called in a different process, which means more surprising behavior.

I'd rather just have an X11 error flag that there was a resolution error or whatever, and have the video subsystem quit do the right thing. If we need to, we could follow the example of the KDSDRM driver which sets signal handlers to take care of the most critical cleanup.

**Comment by icculus** [comment]
Yeah, that gets complicated fast.

Really, we need a way to signal the window manager (or something) to keep an eye on the temporary resolution change, and change it back when the process vanishes, but this protocol doesn't exist at all.
