### ISSUE TITLE
Steam Deck controller order

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8672]
On Steam Deck, Steam presents the controllers as virtual controllers named:
* Microsoft X-Box 360 pad 0
* Microsoft X-Box 360 pad 1
... etc.

These devices might be out of order, e.g. /dev/input/event17, /dev/input/event8, etc, but the name reflects how Steam sees the controller order, and how they're shown in the Steam UI to move controllers around.

SDL should sort these controllers by name rather than by evdev node number so games see them in the same order Steam thinks about them.

**Comment by ThisByzantineConduit** [comment]
This is an issue I'm having, where I set my controller order and everything works fine but then later (maybe after a reboot or controller disconnect and reconnect) the ordering in "Reorder Controllers" doesn't match the SDL device index (i.e. Steam Deck says Pro Controller is #1 and built in Deck controls are #2, but emulators still call the Pro Controller SDL-01 and the built in SDL-0.

I see this change was committed but I'm still having this issue. Has it been pushed out yet or will be soon? Thanks so much!

**Comment by slouken** [comment]
Those emulators probably haven't been updated a new version of SDL. The 2.30.0 release should be out this week.

**Comment by ThisByzantineConduit** [comment]
> Those emulators probably haven't been updated with a new version of SDL. The 2.30.0 release should be out this week.

OK, thanks so much! I notice most emulators on Deck use SDL2; will this apply to those as well?
