### ISSUE TITLE
`testdrawchessboard` regressed with batching changes

### ISSUE THREAD

**Issue by Guldoman** [libsdl-org/SDL#8676]
Since 6ba90f77752ab0350f28fb228c5dde550244904e `testdrawchessboard` isn't drawing properly on Wayland/X11.
I haven't tested other backends.

**Comment by icculus** [comment]
So this is happening because we never do anything to flush the renderer: this never calls SDL_RenderPresent (which _would_ flush it), because it's intending to handle the present with a call to SDL_UpdateWindowSurface itself; this worked before because it explicitly requested a software renderer, which would turn off batching.

This is such a weird corner case...should we say you need to call SDL_FlushRenderer() explicitly here, or should we have SDL_UpdateWindowSurface realize it has a software renderer attached to it and implicitly flush?

I'm thinking the latter is the better option but also possibly a giant pain in the butt.

**Comment by icculus** [comment]
(If you need this fixed right now, though: just call `SDL_FlushRenderer(renderer);` right before the `SDL_UpdateWindowSurface(window);` call.)

**Comment by madebr** [comment]
Related to windows surfaces and the renderer api, I find this comment of `SDL_GetWindowSurface` a bit misleading.
https://github.com/libsdl-org/SDL/blob/f3d8a2def5e2214290bbbc075a6381fa9b753acf/include/SDL3/SDL_video.h#L1583-L1583

**Comment by icculus** [comment]
Yeah, SDL_UpdateWindowSurface is a weird beast...it's used by the software renderer and exists in the public API in case you have a system that does _nothing_ but software rendering and you don't want to use the rendering API.

But also, it will almost certainly use the rendering API behind the scenes to upload your pixels to a texture.

It's an often-misunderstood API that I was genuinely surprised to find testdrawchessboard using today.

I do think that documentation should change from "don't use this with the render API" to "don't use this unless you know what you're doing, this is almost certainly not how you are meant to draw to the screen."

**Comment by Guldoman** [comment]
> (If you need this fixed right now, though: just call `SDL_FlushRenderer(renderer);` right before the `SDL_UpdateWindowSurface(window);` call.)

No worries, I was just testing something unrelated and noticed that the test wasn't working.

**Comment by icculus** [comment]
Thinking more on this, I think the right thing is to say you have to flush the renderer first if you do this and not try to coerce SDL_UpdateWindowSurface to flush any associated renderer. If you don't want to do this, you should be using SDL_RenderPresent() instead.

I guess we could use a property on the surface and flush during UpdateWindowSurface if the property indicates a renderer attached to it. I guess we could just do that in SDL3. I dunno. @slouken, what do you think?

**Comment by slouken** [comment]
I feel like if you're using a software renderer you should call Present() before updating the window surface. This is consistent with other render drivers. Alternatively, we could just say that all software renderer operations are synchronous and present is a no-op, which is what I would naively assume if I were using it.

**Comment by icculus** [comment]
> Alternatively, we could just say that all software renderer operations are synchronous and present is a no-op

Right now that's true, but I can envision a world where we can optimize if we have a whole command queue to run at a time: render front-to-back and reject things we know will be covered completely, etc.

The other concern here is also that testdrawchessboard doesn't create a renderer for a window, it uses SDL_CreateSoftwareRenderer with a surface that happens to be a window surface. Maybe we should change this test to just use SDL_CreateRenderer directly, even if it forces a software renderer.

**Comment by slouken** [comment]
That was intentional, because it’s a valid code path that isn’t exercised anywhere else. I just fixed it to call present, which it really should have been doing all along.
