### ISSUE TITLE
Move Xbox GDK rendering code to public repo

### ISSUE THREAD

**Issue by chalonverse** [libsdl-org/SDL#8681]
Currently, to build for Xbox GDK you need to copy over SDL_render_d3d12_xbox.h/cpp and the two Xbox d3d12 shader blob sources files from the GDK forums (under NDA).

However, I heard back from Microsoft that the code in SDL_render_d3d12_xbox.h/cpp is referencing APIs that is now public in their samples, so they don't have an issue with that code also being in the public SDL repo.

They do have an issue with the shader blobs, however, because the shader blob format is under NDA, and further may be brittle because they are subject to change between Xbox GDK releases.. Their suggestion was that we can do something like they do in DirectXTK12, which is have a script which builds the bitcode using the installed GDK (eg. https://github.com/microsoft/DirectXTK12/blob/main/Src/Shaders/CompileShaders.cmd).

As far as I know, this isn't something that's typically done in SDL, but conceivably I could add a pre-build step in the VisualC-GDK project files. The idea would be that if you're building for Xbox, it would generate the SDL_shaders_d3d12_xbox*.cpp files for you via a script that utilized the installed GDK shader compiler. Then it would just compile the source as it is. That way we can still have everything we need in the SDL repo without running afoul of the NDA?

I made this as an issue for discussion -- am open to ideas on what would be the best way to approach this. I think it would be a nice win and simplify things to have the Xbox stuff all just be in the public repo without needing to maintain a separate NDA'd set of files.

Feel free to assign this issue to me.

**Comment by slouken** [comment]
This sounds good to me. Thanks!

**Comment by flibitijibibo** [comment]
We were thinking of doing the same thing, I think we can invoke something similar to ``dxc.exe -Fh` in a prebuild step to get what we want.
