### ISSUE TITLE
Regressions with "asynchronous windowing" on X11

### ISSUE THREAD

**Issue by meyraud705** [libsdl-org/SDL#8689]
I noticed 2 regressions with commit related to asynchronous windowing:

- Window move down and right when taking or losing focus. Movement match size of the border and titlebar. git bisect give 4fd778119b85626d06e74dbc38c56881a0cd1508 as first bad commit.
- Resize event is not sent after calling `SDL_SetWindowFullscreen()`. First bad commit is 835c733f4d2199b4b9f195f0d1c4b9286726e071 .

I am using SDL3 through SDL2-compat on X11 and KDE.

**Comment by slouken** [comment]
I'm running into this as well, using GNOME on Ubuntu.
