### ISSUE TITLE
Two issues related to asynchronous windowing on win32

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#8692]
after commit [`4fd778`](https://github.com/libsdl-org/SDL/commit/4fd778119b85626d06e74dbc38c56881a0cd1508) ,  ITwo problems were encountered， 
1. create window with external window handle has border.
2. `SDL_Init` with flag `SDL_INIT_VIDEO`  gets slow.

these issues was not present in the previous commit.

I use sdl3 with qt5 on windows10. The image below shows a render window that I created from the Qt widget, which now has an outer border and title bar.
![image](https://github.com/libsdl-org/SDL/assets/1673854/ea53a437-df73-4512-82fc-74b5e62eda60)

**Comment by Kontrabant** [comment]
Can you try the main branch with the fix just pushed and see if it fixes your problem? The external window size and position weren't being set correctly on win32 and the native window test works now.

As for SDL_Init being slow, I'm not sure what would cause that. The only thing that commit changed in the video init code was checking a hint, and that shouldn't be a heavy operation.

**Comment by sandsc** [comment]
update main branch today,  problem still exists.
![image](https://github.com/libsdl-org/SDL/assets/1673854/d21af18a-42ce-4d3e-8e27-f40ec3f4296b)

**Comment by Kontrabant** [comment]
I managed to replicate your issue and pushed another fix. Hopefully that takes care of it.

I still don't know what would be slowing down init in your case. I did some rudimentary profiling of `SDL_VideoInit()` before and after that commit, and there is no difference on my machine.

**Comment by sandsc** [comment]
:thumbsup: The latest commit doesn't have border problem anymore, thank you very much, as for the slow issue, I'll test it again  :smile: .

**Comment by Kontrabant** [comment]
Great, let's close this as completed then. If you can find something more specific that's causing a performance problem, we can revisit that separately.
