### ISSUE TITLE
Download SDL3?

### ISSUE THREAD

**Issue by LedLoaf** [libsdl-org/SDL#8693]
Hello,

I'm a little confused how to download SDL3. Everything I see, including the branches is SDL2. I recall reading something along the lines of "We are combining SDL3 into the master SDL2 branch now" or it might have been soon.

Any who, just trying to get the proper version. Also, for the additional components like image, mixer, ttf I noticed they have an SDL3 folder. So I just pasted in the previous header (SDL_image/mixer/ttf.h) and I'm assuming that will work?

Thanks and have a great week. Welcome to delete this after if it's explained clearly somewhere.

**Comment by playmer** [comment]
SDL3 isn't released formally yet, there's no versions, so there's nothing to really download. They're indeed working on it in the main branch, with SDL2 as a servicing branch, as it is still getting comparatively minor updates and fixes.

If you want to use SDL3 you currently need to compile it yourself, or alternatively look for tip of branch runs of the relevant Github Actions and download the artifacts from those:

[MSVC Run](https://github.com/libsdl-org/SDL/actions/runs/7213526017)
[Mac/Linux Run](https://github.com/libsdl-org/SDL/actions/runs/7213526034)

**Comment by LedLoaf** [comment]
Yeah, I know it's not officially out. But I couldn't find the public files that were out to experiment with. I could have sworn there was an SDL3 branch to download from awhile back. Maybe I'm making that up. 

Thanks for the links!

**Comment by playmer** [comment]
Gotcha, just to clarify if my previous comment was unclear, SDL3 development is happening in the `main` branch. So no need to go looking elsewhere. Just be aware that things may change and are more likely to have bugs.

**Comment by LedLoaf** [comment]
Thanks for the clarity. Much appreciated! Happy Holidays!
