### ISSUE TITLE
SDL2.28.5 compilation issue on AIX 5.3L PowerPC

### ISSUE THREAD

**Issue by kinthall** [libsdl-org/SDL#8695]
Hello, I am compiling SDL2 on AIX 5.3L on POWER3-II/PowerPC 630, it is a 64 bit processor and I am using the 32 bit ABI. 

The toolchain is GCC 4.8.4 with the AIX linker, archiver, and assembler. I am using CMake to configure this, and it does compile mostly working code. The issue comes in with two things. 

It generates invalid opcodes for the CPU Info package and for the `X11_InitMode` function, it ends up giving a coredump and it is having an issue at

```
0xD2DCEEE8 X11_InitMode+0x5d0 7c0150ce Invalid Opcode.
```

I'm willing to help troubleshoot this, however I have little idea on where to even start, I have it compiling with X11, I have tried linking against the system ones and ones I built, it comes down to a bug within SDL. It appears to be an Altivec `lvx` instruction?

I can get more information, I'm away from the box right this second though.

**Comment by madebr** [comment]
CMake only detects whether the compiler supports altivec, not whether the cpu can execute it.
Configure CMake with `-DSDL_ALTIVEC=OFF` to disable it.

**Comment by kinthall** [comment]
I am mostly certain I have done that, however with how many re-compilations I've had to do I'm not certain it's still on honestly. I'll try that and recompile, I have been using `ccmake` as well, so I'll just run a `-DSDL_ALTIVEC=OFF` flag with `cmake`. I'll report back if it's still erroring with a new coredump and stuff. If it still is the Altivec instruction I'll manually pass  `-mno-altivec` to gcc/g++.

**Comment by kinthall** [comment]
So I have it compiling fine without altivec it seems, however, it is trying to link against shared libraries SVR4 style, not AIX style, even removing the extra linker flags it still is trying to link against SVR4 style soname, not AIX archives along with trying to use OpenGL ES when the system has OpenGL 1.3 installed. I will recompile with ES disabled, however, I'm running into the SVR4 style links wanted issue.

Any input would be appreciated. 

```
./testgl2 --log all                  DEBUG: Failed loading libX11.a:         0509-022 Cannot load module /usr/local/lib/libX11.a.
        0509-103   The module has an invalid magic number.
DEBUG: Failed loading libGLESv2.so.2:   0509-022 Cannot load module .
        0509-026 System error: A file or directory in the path name does not exist.
```

**Comment by sezero** [comment]
What happens if you configure and build using autotools (configure) instead of cmake?

**Comment by kinthall** [comment]
I was trying with autotools and was running into weird issues without GNU Coreutils sort so I went with CMake instead. 

I think I have the issue currently resolved by `ar -x -X32 <archive>` and then renaming the XCOFF contents to the library, putting it in there as .so. 

It's something with the dynamic searching at runtime I think, looking for binaries rather than archived ones.

I'll update after I get some weirdness sorted out.

**Comment by madebr** [comment]
You can see the compile and link commands by running `cmake --build /path/to/build --verbose`.
Perhaps you can verify the commands, and manually fix them? Copy pasting in the terminal should work.

**Comment by kinthall** [comment]
I'm still working on this so don't close it quite yet, it's going to probably take a short while though. 

Currently getting 

```
[using memory image in core]
reading symbolic information ...

Illegal instruction (illegal opcode) in . at 0x0 ($t1)
warning: Unable to access address 0x0 from core
```

But I'm looking into linking still.

**Comment by slouken** [comment]
We haven't heard back in over 6 months, so I'm going to go ahead and close this. Please let us know if you'd like it reopened!
