### ISSUE TITLE
SDL_Quit does not free/unlock all resources on raspi5

### ISSUE THREAD

**Issue by zoff99** [libsdl-org/SDL#8699]
system: raspi5 32bit OS, bookworm
SDL version: 2.26.5
i have a sample program that just paints the screen blue with SDL.
the program it self works fine.
when i run another program which uses the same SDL functions, the screen will go blue the first time.
then SDL_Quit() is called. and now if i init SDL again the screen will just turn black. no blue color, no textures. nothing works after that.
when i check with lsof i can see that after the SDL_Quit() there are still some open filehandles to dri stuff:

when SDL is active lsof shows these:

```
t_main  30056   pi  mem       CHR            226,128              517 /dev/dri/renderD128
t_main  30056   pi  mem       CHR              226,1              680 /dev/dri/card1
t_main  30056   pi   19u      CHR              226,1       0t0    680 /dev/dri/card1
t_main  30056   pi   20u      CHR              226,1       0t0    680 /dev/dri/card1
t_main  30056   pi   21u      CHR            226,128       0t0    517 /dev/dri/renderD128
t_main  30056   pi   22u      CHR              226,1       0t0    680 /dev/dri/card1
```

after SDL_Quit() lsof shows these:

```
t_main  30056   pi  mem       CHR 226,128              517 /dev/dri/renderD128
t_main  30056   pi   22u      CHR   226,1       0t0    680 /dev/dri/card1
```

**Comment by slouken** [comment]
Did you figure this out?

**Comment by zoff99** [comment]
yes silly me. SDL_Quit() needs to be run on the same thread as all other commands.
i am not sure why? even if i do locking. but ok, annoying but i can do that.
