### ISSUE TITLE
Playstation 5 Controller is rumble weak on Mac

### ISSUE THREAD

**Issue by RustyMoyher** [libsdl-org/SDL#8706]
PlayStation DualSense rumble is about half the strength it should be in macOS 14 and macOS 13. I'm using SDL 2.28.5 here.

However in macOS 12, the rumble strength is correct. The PS5 rumble in Windows 10 is very similar (or perhaps exactly the same) as macOS 12. I also tested a PlayStation DualShock (PS4) controller. This PS4 controller rumble is correct and the same between macOS 12, 13 and 14. So this issue only seems to affect PS5 controllers.

I'm seeing the same results on multiple macs: m1 mac mini, m2 mac studio and m2 MacBook pro.

My results - PS5 w/ SDL 2.28.5
- macOS 14.1.1: HALF strength
- macOS 13.6.1: HALF strength
- macOS 12.7: Full strength
- Windows 10: Full strength

**Comment by slouken** [comment]
This is an issue with Apple's GCController implementation for PS5 controllers. Sony has two versions of the rumble in their firmware. The version that originally shipped is weak, and then they introduced a stronger version in a firmware update. SDL uses the second version when talking to the PS5 controller directly, but Apple hasn't updated their driver yet, it seems.

You can use SDL's driver by setting the environment variable SDL_JOYSTICK_MFI=0, if you're using the latest unreleased SDL code, but you'll lose support for Xbox controllers.

**Comment by RustyMoyher** [comment]
Oh wow! Apple must have switched to the other rumble (function?) in macOS 13. Is there already a bug open with Apple?

**Comment by RustyMoyher** [comment]
Just updated and tested this in macOS 14.2 and the issue is fixed! Also tested on macOS 13.6.2 where it is not. Closing as fixed.
