### ISSUE TITLE
Based on DL_CreateWindowWithProperties API interface implementation into an existing window

### ISSUE THREAD

**Issue by laijihuan** [libsdl-org/SDL#8711]
At present, from the source code, it seems that SDL3 does not have the WIN_CreateWindowFrom implementation mode in SDL2, is it not yet implemented? If you have the similar function, could you tell me how to correctly call SDL_CreateWindowWithProperties interface implementation before SDL2 SDL_CreateWindowFrom interface functions. Thank you!

**Comment by laijihuan** [comment]
Thank you very much for implementing the window embedding mode I want according to your suggestion. However, there is a problem here, that is, the title bar will exist in the embedded sdl window. At present, I circumvent the title bar and border of this window by setting the fullscreen parameter. Tried setting borderless to true and it doesn't seem to make any difference. Are there any parameters here that I haven't noticed that implement the sdl window without the title bar and border? Thank you!
`SDL_PropertiesID props = SDL_CreateProperties();
SDL_SetProperty(props, "win32.hwnd", const_cast<void*>(pHwnd));
// SDL_SetBooleanProperty(props, "high-pixel-density", true);
// SDL_SetBooleanProperty(props, "focusable", true);
// SDL_SetBooleanProperty(props, "borderless", true);
SDL_SetBooleanProperty(props, "fullscreen", true);
m_pWin = SDL_CreateWindowWithProperties(props);`
![微信图片_20231219144912](https://github.com/libsdl-org/SDL/assets/29115363/a5c8d6c2-6639-4bdf-8565-6a91c059f655)
![微信图片_20231219145030](https://github.com/libsdl-org/SDL/assets/29115363/69786166-1472-43aa-aef2-f6ffe5f3ec44)

**Comment by slouken** [comment]
Can you post a link to a complete example for testing?

**Comment by slouken** [comment]
Also, please try the latest SDL code, as we put a fix in for a related issue yesterday.

**Comment by laijihuan** [comment]
Just pulled the latest code to try, that embedded in other Windows, SDL still exist window title bar problem solved, thank you very much!

**Comment by slouken** [comment]
Great, thanks!
