### ISSUE TITLE
Unresolved external symbol 

### ISSUE THREAD

**Issue by BeeKeepGaming** [libsdl-org/SDL#8720]
_imp_glewInit reference in funtion main
_imp_glewExperimental reference in function main

I'm trying to learn OpenGl with SDL but I can't get passed these issues

**Comment by slouken** [comment]
These are glew symbols, not SDL. You probably need to link with the glew library?

**Comment by BeeKeepGaming** [comment]
Sorry it mentions the SDL_main

**Comment by madebr** [comment]
https://wiki.libsdl.org/SDL2/FAQWindows#i_get_undefined_reference_to_sdl_main_...
