### ISSUE TITLE
GUIDs are no longer unique for Steam Virtual Gamepad

### ISSUE THREAD

**Issue by FrogTheFrog** [libsdl-org/SDL#8724]
Hello o/

After the https://github.com/libsdl-org/SDL/commit/4d5949dcf64f2633b1b435fb0c22a3b0b44d855f commit, we have a hardcoded string for `Steam Virtual Gamepad`. Before we would have the following pattern:

```
Microsoft X-Box 360 pad 0
Microsoft X-Box 360 pad 1
Microsoft X-Box 360 pad 2
...
```

However, since now the name is the same - we calculate the same GUIDs:
```
# INFO: Joystick: Steam Virtual Gamepad, bustype = 3, vendor = 0x28de, product = 0x11ff, version = 1
# [2023-12-20 23:06:02.833417] [0x00007f7af5d2e740] [info]    Watching gamepad GUID: 0300f617de2800000512000000036800, name: Steam Deck
# [2023-12-20 23:06:02.833585] [0x00007f7af5d2e740] [info]    Watching gamepad GUID: 03006983de280000ff11000001000000, name: Steam Virtual Gamepad
# [2023-12-20 23:09:08.019814] [0x00007f7af5d2e740] [info]    Watching gamepad GUID: 050057564c050000e60c000000006800, name: DualSense Wireless Controller
# INFO: Joystick: Steam Virtual Gamepad, bustype = 3, vendor = 0x28de, product = 0x11ff, version = 1
# [2023-12-20 23:09:09.174667] [0x00007f7af5d2e740] [info]    Watching gamepad GUID: 03006983de280000ff11000001000000, name: Steam Virtual Gamepad
```

I have a very niche case where I want to blacklist some of the virtual gamepads and I have used the deterministic GUIDs to do so (provided via the ENV to Moonlight app).

I was wondering if we could have this uniqueness back? Maybe by modifying the GUID here?
https://github.com/libsdl-org/SDL/blob/56f111dffc2828d67fd8e0402b0fe1193c48ce26/src/joystick/linux/SDL_sysjoystick.c#L464

**Comment by slouken** [comment]
The GUID hasn't changed, it should be the same.

**Comment by slouken** [comment]
That code was intended to use the same vendor and product names that are input to `SDL_CreateJoystickName()`, not the output of that function. I'll fix this for the next release, thanks!

**Comment by slouken** [comment]
FYI, in the next release you'll be able to get more information about Steam Virtual Gamepads, check out https://github.com/libsdl-org/SDL/commit/c981a597dc7c69e7532796b3a206071807479d35.

**Comment by FrogTheFrog** [comment]
> FYI, in the next release you'll be able to get more information about Steam Virtual Gamepads, check out [c981a59](https://github.com/libsdl-org/SDL/commit/c981a597dc7c69e7532796b3a206071807479d35).

Yup, I saw it already while looking through the commits. Looks very nice!

I assume you would then need 2 "input" handlers? 1 for SteamInput and one for the controllers that don't have the handle (like right now) 🤔

**Comment by FrogTheFrog** [comment]
Actually don't bother replying, you're probably busy and I will just read release notes afterwards 👍
