### ISSUE TITLE
Xcode SDLTest programs crash on startup on iOS

### ISSUE THREAD

**Issue by TheSpydog** [libsdl-org/SDL#8737]
Running any of the Xcode SDLTest programs on my iPhone results in an immediate crash with the following error output:
> dyld[2875]: Library not loaded: @rpath/SDL2.framework/SDL2
  Referenced from: <8BA1BA82-C495-3D24-9E6E-48E856EC427E> /private/var/containers/Bundle/Application/5633A41C-9423-427C-AE99-ABA2056FFD65/testgamecontroller.app/testgamecontroller
  Reason: tried: '/private/var/containers/Bundle/Application/5633A41C-9423-427C-AE99-ABA2056FFD65/testgamecontroller.app/Frameworks/SDL2.framework/SDL2' (no such file), '/private/var/containers/Bundle/Application/5633A41C-9423-427C-AE99-ABA2056FFD65/testgamecontroller.app/Frameworks/SDL2.framework/SDL2' (no such file)
  
This only happens on the SDL2 branch; the main branch works correctly. I think the issue is that the SDL2 test programs do not include `SDL2.framework` in their `General > Frameworks, Libraries, and Embedded Content` section, but I'm not familiar enough with Xcode to say for sure.

Tested with Xcode 15.1, iOS 17.1.2.

**Comment by slouken** [comment]
Yep, that was the problem, thanks!
