### ISSUE TITLE
SDL_main.h provides wrong language linkage for main function

### ISSUE THREAD

**Issue by yuanbraing** [libsdl-org/SDL#8738]
As known to all, SDL provides it's own main function to take over application's lifecycle.And as many c header do,SDL_main.h have extern "C" blocks in cpp surrounded all it's c functions,including main.
 But use c language linkage for main function is illegal in cpp(see also [cpp reference](https://en.cppreference.com/w/cpp/language/main_function)).So it's better to move main function out of extern "C".

**Comment by yuanbraing** [comment]
I think that no one found out this due to no compiler checks that(In fact many compiler even can't check wrong main args).But if you has his own reason of doing this,you can show me here.

**Comment by yuanbraing** [comment]
And just for asking,why doesn't "wmain" function's third argument have a double pointed type?

**Comment by yuanbraing** [comment]
And just for asking,why doesn't "wmain" function's third argument have a double pointer type?

**Comment by icculus** [comment]
I believe this is fixed in SDL3 with all the reworking that happened for SDL_main there.

But I think your assertion is still correct for the SDL2 branch. Is that what you're looking at?

**Comment by yuanbraing** [comment]
In fact,SDL2 don't have this problem,because the "main" part is compiled in pure c(That only need to assume that compiler ensures c++ object destruction by atexit()).
But all part of SDL3 main in SDL3/SDL_main_impl.h is in extern "C",that's where the problem happen.

**Comment by yuanbraing** [comment]
```c
--- SDL_main_impl.h     2023-12-24 19:06:03.974028410 +0800
+++ SDL_main_impl_fixed.h       2023-12-24 19:11:44.162028281 +0800
@@ -95,12 +95,18 @@
     return SDL_RunApp(0, NULL, SDL_main, NULL);
 }
 #else /* ANSI */
+#ifdef __cplusplus
+} /* extern "C" */
+#endif
 int main(int argc, char *argv[])
 {
     (void)argc;
     (void)argv;
     return SDL_RunApp(0, NULL, SDL_main, NULL);
 }
+#ifdef __cplusplus
+extern "C" {
+#endif
 #endif /* UNICODE */

 #endif /* _MSC_VER && ! __GDK__ */
@@ -198,19 +204,11 @@

 #include <SDL3/SDL_begin_code.h>

-#ifdef __cplusplus
-extern "C" {
-#endif
-
 int main(int argc, char *argv[])
 {
     return SDL_RunApp(argc, argv, SDL_main, NULL);
 }

-#ifdef __cplusplus
-} /* extern "C" */
-#endif
-
 #include <SDL3/SDL_close_code.h>

 /* end of impls for standard-conforming platforms */
```

**Comment by slouken** [comment]
What compiler and operating system is this causing problems with?

**Comment by yuanbraing** [comment]
You can say no or all.
It happens in all platform,but no platform really have problems on it.But because of contraction between this and standard,it may cause real problem in the future.That's why I start this issue.

**Comment by slouken** [comment]
Fixed, thanks!
