### ISSUE TITLE
Unable to handle POV hat for "PS5 DualSense" controller using SDL's joystick API

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#8754]
This is continuation af the #8619 issue.

SDL doesn't see the POV hat for the PS5 DualSense controller by default, and it also sees too many buttons. After enabling the use of advanced reports using the hints below ([as suggested](https://github.com/libsdl-org/SDL/issues/8619#issuecomment-1868580962)):

```c
SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE, "1");
SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE, "1");
```
LED and rumble are visible as available, but POV hat is still not visible and the number of buttons is still too large:

- [SDL_JoystickNumHats](https://wiki.libsdl.org/SDL2/SDL_JoystickNumHats) returns `0` (should be `1`),
- [SDL_JoystickNumButtons](https://wiki.libsdl.org/SDL2/SDL_JoystickNumButtons) returns `17` (should be `14`).

Apparently SDL maps the POV hat as four direction buttons, as @slouken [researched](https://github.com/libsdl-org/SDL/issues/8619#issuecomment-1869710419):

> Ah, okay, this sounds correct. You're seeing LED and rumble false when the PS5 rumble hint is off and they're true when the hint is on. SDL treats the hat as 4 D-Pad directional buttons, so all is well.

If a given joystick/gamepad has a POV hat, SDL must use it as an actual POV hat, rather than a set of buttons. Otherwise it will be impossible to handle the POV hat using the pure SDL joystick API — [SDL_JoystickNumHats](https://wiki.libsdl.org/SDL2/SDL_JoystickNumHats) will allways return `0` and the SDL will never generate [SDL_JoyHatEvent](https://wiki.libsdl.org/SDL2/SDL_JoyHatEvent) events. It will also not be possible to create custom input mapper on top of the SDL joystick API (which is what happens in my case).

**Comment by slime73** [comment]
> Otherwise it will be impossible to handle the POV hat using the pure SDL joystick API

You just need to know which button numbers correspond to the dpad directions, right? That seems similar to knowing which button numbers correspond to specific face buttons (X, O, etc) – in both cases the driver doesn't necessarily tell you what's what. i.e. making the dpad more easily identifiable doesn't solve the root issue you'd have.

In order to support everything in a game you either need an internal mapping for the driver/OS combo (using the joystick GUID), or you can use the gamepad API (which does that for you), or you can make the user bind things themselves.

**Comment by furious-programming** [comment]
> In order to support everything in a game you either need an internal mapping for the driver/OS combo (using the joystick GUID), or you can use the gamepad API (which does that for you), or you can make the user bind things themselves.

I chose the third option, i.e. I created my own input mapper that uses the joystick API and  the user can independently assign gameplay actions to the triggers of his or her choice. However, for the main menu, it is possible to use any joystick, without any mapping. You can use the POV hat and both sticks to navigate the menu. And here there is a problem, because **SDL claims that the PS5 DualSense does not have a POV hat** (which is wrong), so pressing it does not allow you to navigate the menu.

The problem is not the joystick support in my (game) engine, but the fact that SDL uses the POV hat as four buttons completely unnecessarily. As mentioned in the previous issue, this was done to simplify the gamepad API ([source](https://github.com/libsdl-org/SDL/issues/8619#issuecomment-1869752051)):

> The D-Pad is represented on various systems as both a hat and a set of directional buttons. To simplify the gamepad API, SDL has opted to treat it as buttons.

And this breaks compatibility with the joystick API, which means that the POV hat of this controller cannot be handled normally.
