### ISSUE TITLE
SDL_bool causes signed/unsigned mismatch errors with boolean expressions

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8761]
Using /W4 warning level on Visual Studio 2022:
src\render\SDL_render.c(1101,76): warning C4389: '==': signed/unsigned mismatch
src\render\SDL_render.c(1322,76): warning C4389: '==': signed/unsigned mismatch
src\render\opengles2\SDL_render_gles2.c(952,63): warning C4389: '!=': signed/unsigned mismatch
src\render\opengl\SDL_render_gl.c(1114,78): warning C4389: '!=': signed/unsigned mismatch
src\video\SDL_video.c(317,25): error C2220: the following warning is treated as an error
src\video\SDL_video.c(317,25): warning C4389: '==': signed/unsigned mismatch

**Comment by Kontrabant** [comment]
Looking into this a bit more, making `SDL_bool` signed is probably the only real way to fix this as the C spec states:

>The == (equal to) and != (not equal to) operators are analogous to the relational operators except for their lower precedence. Each of the operators yields 1 if the specified relation is true and 0 if it is false. **The result has type int**. For any pair of operands, exactly one of the relations is true.

The offending code that caused the build to fail with the unsigned -> signed change was fixed, so changing `SDL_bool` to be signed is safe now. There are tradeoffs either way, but, ultimately, it's probably better to stick with the spec on this.

**Comment by slouken** [comment]
That makes sense and is probably why the Windows BOOL is an int as well. Thanks for looking into this.

**Comment by slouken** [comment]
@smcv, any thoughts before we make SDL_bool an int?

**Comment by Kontrabant** [comment]
> That makes sense and is probably why the Windows BOOL is an int as well. Thanks for looking into this.

That's actually the exact reason for it :)
https://devblogs.microsoft.com/oldnewthing/20110328-00/?p=11113

**Comment by icculus** [comment]
To save @smcv the typing, the reason we went with unsigned was because if someone does:

```c
struct x {
    SDL_bool y:1;
};
```

...then the two values `x::y` holds are not SDL_TRUE (1) and SDL_FALSE (0), but -1 and 0.

But speaking for myself, I still think that if you do this, you only have yourself to blame, and if you genuinely needed a bitfield, you should have used `int` here.

**Comment by slouken** [comment]
Well, 25 years later, we arrived at the same conclusion. Alright, I'll go ahead and change that. 😄

**Comment by smcv** [comment]
> if you genuinely needed a bitfield, you should have used `int` here

Presumably that should read "you should have used `unsigned` here" (or equivalently, `unsigned int`), as in `struct { unsigned a : 1; unsigned b : 1; }`.

**Comment by icculus** [comment]
> Presumably that should read "you should have used unsigned here" 

See, I tried to save you some typing and blew it in the last sentence anyhow.  :P
