### ISSUE TITLE
Update copyrights for 2024.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8765]
Happy new year.  :)

**Comment by slouken** [comment]
Done!

**Comment by sezero** [comment]
P.S.: SDL_rtf did not get the update

**Comment by sezero** [comment]
P.S. / 2: neither did sdl12-compat and sdl2-compat.

**Comment by slouken** [comment]
Done!

**Comment by sezero** [comment]
P.S./3: @icculus: SDL3_net main source file doesn't have a license header

**Comment by icculus** [comment]
> P.S./3: @icculus: SDL3_net main source file doesn't have a license header

Fixed in https://github.com/libsdl-org/SDL_net/commit/00404cfa71c7f391d26d67aa7d4d853a8355df7e
