### ISSUE TITLE
Wayland window decorations

### ISSUE THREAD

**Issue by qaxl** [libsdl-org/SDL#8767]
Hey! I've been having a problem lately with SDL3 (the master branch, latest commit as of writing `44c2f34`). The problem is basically that on Wayland with GNOME the SDL window decorations look vastly different compared to other GTK and native apps. Creating window like normal leads to the incorrect decorations, however I have found a workaround which seems to fix the issue.

# The workaround 

Initialize GTK3 by myself before initializing SDL: 
```c
/* in the initialization code */
gtk_init_check(NULL, NULL);
SDL_Init(SDL_INIT_EVERYTHING);
```
I have no idea why this workaround works, but it seemingly fixes the issue and I get the wanted decorations on the Window.

# Without using the workaround

I get the following errors on stderr and the window decorations look wrong.
```sh
libdecor-gtk-WARNING: Failed to initialize GTK
Failed to load plugin 'libdecor-gtk.so': failed to init
```

# Screenshots 

Unwanted:
![incorrect decorations](https://media.discordapp.net/attachments/1100066076026474566/1191009059172794429/image.png?ex=65a3e09f&is=65916b9f&hm=325db3366d607c52eb7787eeb775725e1c27ae98b89779fc1a60a3312f0b9c63&=&format=webp&quality=lossless&width=1102&height=40)

Wanted:
![correct decorations](https://cdn.discordapp.com/attachments/1100066076026474566/1191009059453800488/image.png?ex=65a3e09f&is=65916b9f&hm=d1d77922e500319f7a98ca946d2a6ecefdbfe61f67d40687c5f62a9f6ae54c6e&)

# Environment

OS: Arch Linux
DE: GNOME 45

I can provide more information as needed.

**Comment by Kontrabant** [comment]
This should be reported upstream to libdecor, as it's not something SDL can fix.

**Comment by qaxl** [comment]
Alright. Thank you.

**Comment by madebr** [comment]
This is a duplicate of https://github.com/libsdl-org/SDL/issues/8185
Latest libdecor should fix this.

**Comment by Kontrabant** [comment]
Looks like the OP has the latest libdecor, it's just failing to initialize the GTK plugin unless they manually initialize GTK before loading libdecor for some reason. Either way, SDL doesn't touch GTK or the libdecor internals, so there's nothing that can be done to fix this on our end.

**Comment by diant0** [comment]
already commented on issue upstream, but all search engines point here, so here's a possible solution.

most likely, this has to do with mismatched 'GDK_BACKEND' environment variable. i think it happens when you launch your executable though something that uses xwayland.

try `GDK_BACKEND=wayland ./your-executable-here`
