### ISSUE TITLE
[feature] Wayland: add option to disable scaling completely with scaling/fractional_scale

### ISSUE THREAD

**Issue by manio** [libsdl-org/SDL#8768]
Hi
The Wayland fractional scaling code made mainly by @Kontrabant is working good, ie:
- when I have disabled scaling for my 4K display (scale=1) the SDL game is rendering at full 4K resolution, so all is fine
- when I set the scale to 2 (my normal setting) then I have the game "upscaled" - it is also fine because it honors the scale provided by the compositor.

But is would be great to have some way to disable scaling completely. Let's say I want to keep scale set to 2 (eg. for the web browser, other native wayland apps, etc.) but in the same time I'd like to start the SDL game without scaling.
I was thinking about some env variable before start, like `export SDL_DISABLE_SCALING=1` or something similar.
I think it would be useful for some specific cases...

---
_One day later:_
After some playing with this, I've figured out the code needed to achieve the above.
This is the quick and dirty (hardcoded scale value) minimal changes:
```diff
diff --git a/src/video/wayland/SDL_waylandevents.c b/src/video/wayland/SDL_waylandevents.c
index 65adff64c..9862d75ca 100644
--- a/src/video/wayland/SDL_waylandevents.c
+++ b/src/video/wayland/SDL_waylandevents.c
@@ -399,7 +399,7 @@ static void pointer_handle_motion(void *data, struct wl_pointer *pointer,
         const float sy_f = (float)wl_fixed_to_double(sy_w);
         const int sx = (int)SDL_floorf(sx_f * window->pointer_scale_x);
         const int sy = (int)SDL_floorf(sy_f * window->pointer_scale_y);
-        SDL_SendMouseMotion(window->sdlwindow, 0, 0, sx, sy);
+        SDL_SendMouseMotion(window->sdlwindow, 0, 0, sx*2, sy*2);
     }
 }
 
diff --git a/src/video/wayland/SDL_waylandwindow.c b/src/video/wayland/SDL_waylandwindow.c
index ff323083e..be94650ad 100644
--- a/src/video/wayland/SDL_waylandwindow.c
+++ b/src/video/wayland/SDL_waylandwindow.c
@@ -273,7 +273,7 @@ static void ConfigureWindowGeometry(SDL_Window *window)
 
                 if (!FullscreenModeEmulation(window)) {
                     /* Round to the next integer in case of a fractional value. */
-                    wl_surface_set_buffer_scale(data->surface, (int32_t)SDL_ceilf(data->scale_factor));
+                    wl_surface_set_buffer_scale(data->surface, 2);
                 } else {
                     wl_surface_set_buffer_scale(data->surface, 1);
                 }
@@ -564,6 +564,8 @@ static void handle_configure_xdg_toplevel(void *data,
 {
     SDL_WindowData *wind = (SDL_WindowData *)data;
     SDL_Window *window = wind->sdlwindow;
+    width*=2;
+    height*=2;
 
     enum xdg_toplevel_state *state;
     SDL_bool fullscreen = SDL_FALSE;
```
Instead of using the hardcoded value I was also trying to get the value from `data->scale_factor` but this is only working when the window has the `SDL_WINDOW_ALLOW_HIGHDPI` flag set, and even then, there was problems because the same value is used in multiple other places, so it cannot be used directly.

Steps to reproduce:
1. Install some compositor like [Sway](https://swaywm.org/) or [Hyprland](https://hyprland.org/)
2. Set scaling factor for some display eg. to `2`
3. Start some SDL application. I was testing it on [freeserf](https://github.com/freeserf/freeserf) but it shouldn't matter.

I would be grateful if @Kontrabant or anyone can take a look at this and share thoughts.

**Comment by Kontrabant** [comment]
I'm not exactly sure what you are trying to do here? This isn't disabling scaling, it's doubling the logical size of the window, which is going to result in a window that is 2x larger than requested, with a backbuffer that needs to be 2x larger than that to do 1:1 pixel mapping (so a 1280x720 window ends up becoming 2560x1440 with a backbuffer of 5120x2880), and converts pointer coordinates from logical points/screen units to pixels before delivery (so the aforementioned 2560x1440 window will get pointer coordinates well outside of its bounds).

You can't disable or avoid scaling with Wayland outside of setting the desktop scale factor to 1, as scaling will have to be done somewhere, either by the application using a backbuffer size that results in 1:1 pixel mapping (`SDL_WINDOW_ALLOW_HIGHDPI`), or by the compositor scaling things itself (usually blurry).

**Comment by manio** [comment]
@Kontrabant 
As _a picture is worth a thousand words_ so I'll try to explain this like that:
(I had to push it on my server as github complaints about image sizes...)
3 screenshots with the above patch applied (sdl-freerdp for remote RDP session and freeserf game):

freerdp logon screen: http://skyboo.net/temp/sdl/2024-01-03-184120_grim.png
freerdp webbrowser: http://skyboo.net/temp/sdl/2024-01-03-184147_grim.png
freeserf game: http://skyboo.net/temp/sdl/2024-01-03-184419_grim.png

And vanilla SDL lib without any patch (with the same output settings):
freerdp logon screen: http://skyboo.net/temp/sdl/2024-01-03-184924_grim.png
freerdp webbrowser: http://skyboo.net/temp/sdl/2024-01-03-185009_grim.png
freeserf game: http://skyboo.net/temp/sdl/2024-01-03-184602_grim.png

Unfortunately all above pictures are not a real 4K because of grim tool wrongly applied scaling when doing a screenshot. Just look at this full screen and look at details/font quality (also the waybar at the top).
As you can see on vanilla SDL the windows just have half of possible resolution and it is upscaling this.

That's why a [wl_surface_set_buffer_scale](https://wayland-client-d.dpldocs.info/wayland.client.protocol.wl_surface_set_buffer_scale.html) is doing its job:
_The purpose of this request is to allow clients to supply higher resolution buffer data for use on high resolution outputs. It is intended that you pick the same buffer scale as the scale of the output that the surface is displayed on. This means the compositor can avoid scaling when rendering the surface on that output._

I know that setting scale=1 will just work fine but this way I have a plenty of other problems like too small fonts everywhere (like waybar), cursor "acceleration" which is wrong, and eg. web browser with too small UI which has to be adjusted. With setting scale=2 for output all the above problems are non existent, the only problem is with wayland apps that are unaware of this (like the SDL here) when we want to force eg real 4K resolution content from the desired application.

**Comment by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [comment]
Hi, I wanted to chime in because I have literally the same issue right now.
I am using KDE Plasma 5.27 with a 4k display and I am trying to use freerdp but everything on the connected machine is blurry as long as the global display scaling in kwin is active. Unfortunately, I also can't  deactivate the scaling because then everything becomes unusable tiny on the host machine. 

I would really appreciate an option that allows me to disable scaling for SDL applications.  🙏

**Comment by manio** [comment]
@e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd 
Just curious: What is your scale value for this 4K display? I am wondering if it is integer or fractional scaling.

**Comment by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [comment]
I am using 150% fractional scaling. It's what KDE sets by default on my machine.

**Comment by Noted-Jrelvas** [comment]
+1. This is basically a requirement for non-dpi aware legacy games, where scaling on the Wayland compositor will simply result in the game's resolution being proportionally reduced:

![imagem](https://github.com/libsdl-org/SDL/assets/55360900/1bbe1bf9-3e15-4d7d-a819-e0fb4f1273e2)

The current behavior of running these SDL2 games via XWayland is to simply "ignore" scaling and continue exposing to the game  the monitor's actual resolution. I believe that the same behavior should be achievable when SDL's backend is Wayland. A lot of these games are already doing internal scaling of their UI based on resolution, anyways. 

This is the only problem stopping me from running Source 1 games on Wayland.

**Comment by Kontrabant** [comment]
Currently in progress. It works, although it has some ugly side effects with high-DPI/mixed-DPI setups since it's basically forcing scaling to do 1:1 mapping by resizing the window, which does against how Wayland desktops are designed to work. I can understand the use for this in legacy applications, but it is definitely something that will remain gated behind a hint.

Bumping the milestone to 3.2.0, as this is too involved and experimental for SDL2.

**Comment by Noted-Jrelvas** [comment]
Those are some good news. Just for clarification, end-users are capable of providing this hint themselves, right? (For instance, via an env var). Developers of legacy programs might not provide an updated version which sets this hint.

**Comment by X-m7** [comment]
Given that this feature is currently targeting the future SDL3 release rather than SDL2, programs would need to be ported over to SDL3 first before it can make use of this, no? In that case then an environment variable or whatever wouldn't be useful unless there are plans to have an equivalent of sdl12-compat for SDL2 -> SDL3.

**Comment by Noted-Jrelvas** [comment]
As far as I'm aware, such a compatibility layer is planned. I might be
wrong though.

**Comment by slouken** [comment]
Yes, there is already sdl2-compat in progress:
https://github.com/libsdl-org/sdl2-compat

**Comment by Kontrabant** [comment]
This is now in SDL3 and works quite well aside from the quirks that naturally arise when forcing this type of scaling when Wayland wasn't designed for it.

Backporting this to SDL2 would not be a trivial cherry-pick, and would basically have to be completely re-implemented as the SDL3 Wayland backend has been significantly streamlined vs SDL2, so that's going to be left as "patches welcome" if someone really wants to do it vs using sdl2-compat.
