### ISSUE TITLE
Adaptive Sync Detection

### ISSUE THREAD

**Issue by AI221** [libsdl-org/SDL#8772]
Adaptive Sync detection is relevant to some game engine's internal workings
Suggested API:
SDL_DisplayMode struct: Add "bool adaptive_sync_enabled"

I understand that detecting this may be difficult however hopefully this is something that can be coordinated with AMD and Nvidia. 
Perhaps using a struct with "UNKNOWN" and true/false  would be a better interface since I'm not sure if most drivers currently support this query. However, it would be a boon if SDL could add this feature to take the hairiness out of the querying -- something SDL is strong at. SDL could then have backends per GPU driver.

Furthermore, it would be nice if we got events when the display mode changes -- since users may adjust the adaptive sync (or framerate!) of their monitors while running a game.

Thank you for developing this open-source library, and I hope you can trust the value in this feature!

**Comment by slouken** [comment]
That seems like a good idea. Feel free to submit a PR that would be helpful to you.

**Comment by AI221** [comment]
Thanks for the quick reply! 

I'm not very familiar with operating system / GPU-driver-talking stuff. Guess that's your fault ;)

Are you looking for a PR with the interface changes I mentioned? Like, perhaps just STUB with "UNKNOWN"? 

Thanks

**Comment by Qwinci** [comment]
Using a debug variable in SDL doesn't seem a good idea, as the kernel may be compiled without debugfs support. And it looks like that doesn't reflect the enable status of VRR, my guess is that it just shows its supported by the screen connected to that particular connector.

**Comment by AI221** [comment]
Hmmm, true. (it still works well for a stub implementation). 
As far as  /sys/kernel/debug/dri/0/DP-1/vrr_range goes, it DOES work for me in reporting enabled -- since it reports
two zeros if not enabled. And using it made me realize the interface needed to have fps min/max, so that was a good thing.

I'm of the opinion that a file-based interface works best here, since we're just querying hardware info. So, something on /proc/ would be ideal. If we can't get libdrm working (and I will investigate that after making a stub implementation) then perhaps a new /proc/ interface that is always available would be the next best thing. 
     If that's the case, then  I would probably want to leave the debugFS implementation in as a fallback if it's available. It's not too much source code anyway, and kernel changes can take a while to propagate.

One thing to note -- Do you happen to have an Nvidia card? I don't have access to one at the moment. I'm running on AMD, and from Linux source code AMD and Intel both have vrr debugFS query implementations. If you're on NVIDIA, does  `/sys/kernel/debug/dri/0/DP-1/vrr_range` work for you?
    It may simply be necessary to use NVAPI on Nvidia on all platforms. 
    However, on Linux, it appears that it's likely _only_ possible to use DRM to query AMD/Intel anyway.

**Comment by Qwinci** [comment]
> Hmmm, true. (it still works well for a stub implementation). As far as /sys/kernel/debug/dri/0/DP-1/vrr_range goes, it DOES work for me in reporting enabled -- since it reports two zeros if not enabled. And using it made me realize the interface needed to have fps min/max, so that was a good thing.
> 
> ~I'm of the opinion that a file-based interface works best here, since we're just querying hardware info. So, something on /proc/ would be ideal. If we can't get libdrm working (and I will investigate that after making a stub implementation) then perhaps a new /proc/ interface that is always available would be the next best thing. If that's the case, then I would probably want to leave the debugFS implementation in as a fallback if it's available. It's not too much source code anyway, and kernel changes can take a while to propagate.~
> 
> One thing to note -- Do you happen to have an Nvidia card? I don't have access to one at the moment. I'm running on AMD, and from Linux source code AMD and Intel both have vrr debugFS query implementations. You're saying `/sys/kernel/debug/dri/0/DP-1/vrr_range` doesn't work for you? It may simply be necessary to use NVAPI on Nvidia on all platforms. However, on Linux, it appears that it's likely _only_ possible to use DRM to query AMD/Intel anyway.
> 
> Edit: If you do `drm_info > /tmp/aa`, toggle VRR, and do `drm_info > /tmp/aa`, what is your `diff /tmp/aa /tmp/bb`? Mine looks like this: https://gist.github.com/AI221/4e7029e635075d2008f3102e514e57ea
> 
> Edit2: It looks like while "vrr_enabled" is plumbed through drm props, min/max vfreq is not. So I'll make a PR for that. It's not complicated. Then, as I understand, the drm props system means that libdrm will immediately have that information available.
> 
> Edit3: I seem to have forgotten that DebugFS requires super user. Probably not relevant to include, but again, works nicely for testing.

Are you talking about disabling freesync on the monitor settings? I were talking about enabling variable refresh on software, eg. with the "VariableRefresh" xorg option (not sure what is it on wayland). Regarding the /sys/kernel/debug I do have it (on amd), but only because I have CONFIG_DEBUGFS enabled if I were to not have selected that kernel config option then I wouldn't have /sys/kernel/debug either.

**Comment by AI221** [comment]
> > Hmmm, true. (it still works well for a stub implementation). As far as /sys/kernel/debug/dri/0/DP-1/vrr_range goes, it DOES work for me in reporting enabled -- since it reports two zeros if not enabled. And using it made me realize the interface needed to have fps min/max, so that was a good thing.
> > ~I'm of the opinion that a file-based interface works best here, since we're just querying hardware info. So, something on /proc/ would be ideal. If we can't get libdrm working (and I will investigate that after making a stub implementation) then perhaps a new /proc/ interface that is always available would be the next best thing. If that's the case, then I would probably want to leave the debugFS implementation in as a fallback if it's available. It's not too much source code anyway, and kernel changes can take a while to propagate.~
> > One thing to note -- Do you happen to have an Nvidia card? I don't have access to one at the moment. I'm running on AMD, and from Linux source code AMD and Intel both have vrr debugFS query implementations. You're saying `/sys/kernel/debug/dri/0/DP-1/vrr_range` doesn't work for you? It may simply be necessary to use NVAPI on Nvidia on all platforms. However, on Linux, it appears that it's likely _only_ possible to use DRM to query AMD/Intel anyway.
> > Edit: If you do `drm_info > /tmp/aa`, toggle VRR, and do `drm_info > /tmp/aa`, what is your `diff /tmp/aa /tmp/bb`? Mine looks like this: https://gist.github.com/AI221/4e7029e635075d2008f3102e514e57ea
> > Edit2: It looks like while "vrr_enabled" is plumbed through drm props, min/max vfreq is not. So I'll make a PR for that. It's not complicated. Then, as I understand, the drm props system means that libdrm will immediately have that information available.
> > Edit3: I seem to have forgotten that DebugFS requires super user. Probably not relevant to include, but again, works nicely for testing.
> 
> Are you talking about disabling freesync on the monitor settings? I were talking about enabling variable refresh on software, eg. with the "VariableRefresh" xorg option (not sure what is it on wayland). Regarding the /sys/kernel/debug I do have it (on amd), but only because I have CONFIG_DEBUGFS enabled if I were to not have selected that kernel config option then I wouldn't have /sys/kernel/debug either.

The debugfs variable is based on DRM. From a friend's computer, I can see that the Nvidia driver under Linux does not use DRM (by default), and thus this debugfs variable does not appear on these setups.


The debugfs variable is tied to connector properties in linux DRM, specifically `monitor_range->min_vfreq`. 

I'm trying to investigate on the Linux kernel side of things how exactly this should be exposed in _all kernels_, with or without debugfs enabled. Basically, it's a matter of trying to expose this monitor range variable to non-root applications. 


At any rate, a separate implementation for Nvidia will be needed. NVapi actually exposes vrr min/max, so this would work for Nvidia on _both_ Linux and Windows. That would leave only Intel & AMD on Windows out of the implementation, though they probably have their own APIs. 

Can SDL3 include NVapi without licensing issues?

**Comment by Qwinci** [comment]
so we don't want to get the software enable status of vrr? because freesync can be enabled on the monitor but disabled on software (like it is usually by default, unless you add `Option "VariableRefresh" "true"` to your xorg config.

**Comment by AI221** [comment]
> so we don't want to get the software enable status of vrr? because freesync can be enabled on the monitor but disabled on software (like it is usually by default, unless you add `Option "VariableRefresh" "true"` to your xorg config.

We want to get whether _VRR is currently enabled on the computing device_.

In other words, _is VRR active right now_. We don't care about why or why not; __is our swapchain VRR?__

Hopefully this answers your question!

**Comment by Zamundaaa** [comment]
Please don't try to use libdrm for anything outside of actually driving a display. A given display might not have a related drm connector, you might not know the related drm connector or match it wrongly, and on future versions of KWin it will always tell you adaptive sync is active (because it is, on a connector level), even when the refresh rate is entirely stable.

I don't know about Xorg, but on Wayland you can get this information properly through the presentation time protocol - the [refresh](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/presentation-time/presentation-time.xml#L250) value will be zero while adaptive sync is active.

**Comment by AI221** [comment]
> Please don't try to use libdrm for anything outside of actually driving a display. A given display might not have a related drm connector, you might not know the related drm connector or match it wrongly, and on future versions of KWin it will always tell you adaptive sync is active (because it is, on a connector level), even when the refresh rate is entirely stable.
> 
> I don't know about Xorg, but on Wayland you can get this information properly through the presentation time protocol - the [refresh](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/presentation-time/presentation-time.xml#L250) value will be zero while adaptive sync is active.

That sounds good. I will do that instead. 
I did talk about Nvidia drivers not having a DRM driver. 

Anyway, yes I agree it's definitely better to go through Wayland. Thanks for pointing out a method to do so!

At any rate, this helps to unify the current Windows implementation I have in mind.

**Comment by slouken** [comment]
@Kontrabant, does it make sense to add an optional property on the SDL display for this?

**Comment by Kontrabant** [comment]
On Wayland, a presentation time feedback request needs to be submitted per-surface for each frame. It's not of much use if SDL isn't internally handling presentation, and of less use in a per-display sense as there is no way to query any of this before making a window and sending frames. Plus VRR could arbitrarily be enabled/disabled at any time, for any reason, by the desktop compositor, so that display property may not be accurate unless constantly polled.

I would imagine this is case across platforms, as just because a display has VRR enabled, it's may not actually be used, which makes a display property for it unreliable.

**Comment by AI221** [comment]
What we really need is a way to query the _OS_ if VRR is being used by the
entire swapchain or not. Basically, is the monitor being presented with VRR
or not?

And then a way for SDL to query this per display. A game could then
periodically (say, once every 100 frames) poll this and adjust accordingly.

However, I've been unable to find suitable methods for all OSes. The
closest I can find on Windows, for example, is to query if "tearing" is
enabled (which gets enabled with VRR I believe).

**Comment by slouken** [comment]
Since it sounds like this isn't currently possible, I'm going to go ahead and close this. Please let us know if you find out more information!
