### ISSUE TITLE
SDL3 icon doesnt show up

### ISSUE THREAD

**Issue by ghost** [libsdl-org/SDL#8774]
SDL3 icon shows the default wayland icon not the one set by SDL_SetWindowIcon(m_window, m_icon);

**Comment by Nour1248** [comment]
![Screenshot_20240103_014920](https://github.com/libsdl-org/SDL/assets/121687016/c8c855ac-210b-4452-acab-c4758d9578d1)

**Comment by Nour1248** [comment]
the icon does show up on x11 though

**Comment by Kontrabant** [comment]
Wayland doesn’t support setting the icon programmatically. You need to use a .desktop file that points to the icon image.

**Comment by Kontrabant** [comment]
There is a proposed protocol for this, but it is unknown if/when it will be adopted. 

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269

**Comment by madebr** [comment]
@Kontrabant 
xdg-toplevel-icon has been merged, and is part of the recently released Wayland Protocols 1.37

**Comment by Kontrabant** [comment]
Wayland support has been merged.
