### ISSUE TITLE
Mouse clicks not registering in fullscreen desktop on macOS

### ISSUE THREAD

**Issue by danginsburg** [libsdl-org/SDL#8778]
Starting with commit e66896406d6cf44d1770e6e11d5275c7c635dfa1 @Kontrabant I am no longer seeing mouse button down/up events in desktop friendly fullscreen on macOS.  I noticed this while testing Dota 2 with latest SDL3, but also can reproduce it in a test app.

Setup:
* Macbook Air M1, 2020 macOS 13.2.1
* Display set to "Default"

Repro:
* Build SDL3 from e66896406d6cf44d1770e6e11d5275c7c635dfa1 or newer
* Run ./testhittesting --fullscreen-desktop
* Note that the following messages don't appear in the console output:

2024-01-03 15:29:41.560 testhittesting[15837:8048725] INFO: button down!
2024-01-03 15:29:41.612 testhittesting[15837:8048725] INFO: button up!

If you build from an earlier commit, those messages will appear.

@slouken

**Comment by Kontrabant** [comment]
Strange, fullscreen space windows don't get any mouse button events if the `NSWindowStyleMaskTitled` flag isn't set, even though the window becomes key, it has mouse focus, and motion events arrive.

A fix is on the way.
