### ISSUE TITLE
Renaming file SDL_mslibc_x64.asm to .masm ?

### ISSUE THREAD

**Issue by J-Vernay** [libsdl-org/SDL#8781]
Hello,

Commit https://github.com/libsdl-org/SDL/commit/6127ac08714f423b523c0bf6c2210a782b2f571a has added a Microsoft Assembly source file `SDL_mslibc_x64.asm`.

Could it be possible to rename the file to `SDL_mslibc_x64.masm` ?
This extension helps tools identify this file as specific to MASM, instead of other assemblers.

In particular, this helps when using Meson build system importing the CMake project.
Meson assumes that `.asm' file stands for NASM or YASM, not MASM.

(this is also an issue with Meson which does not respect CMake's SOURCE PROPERTY LANGUAGE,
but changing the extension may help other tools too, and is not costly)

Would it be possible?

Thank you for your time!

**Comment by madebr** [comment]
I renamed it in 5cbdeab7997809c517683efbcc0d563f19c9d326
