### ISSUE TITLE
"SDL_SetWindowFullscreen" function should be more useful

### ISSUE THREAD

**Issue by furious-programming** [libsdl-org/SDL#8784]
If we talk about the fullscreen and exclusive fullscreen modes, the API user should not mess with the video modes, but simply tell SDL to display the window on a specific display and in a specific mode. Current display modes should be used at most to read the parameters of these modes in order to be able to list them clearly (e.g. build an in-game menu showing available resolutions and refresh rates).

While working on SDL3, it would be worth taking up this topic and thinking once again how video modes should be used. As far as I'm concerned, only one function would be enough to turn on and off full screen mode (fake and exclusive). The parameters should include a window handle, display index, video mode index and a flag specifying whether it should be fake fullscreen, exclusive fullscreen or fullscreen off. This function could be the current `SDL_SetWindowFullscreen` function.

```c
int SDL_SetWindowFullscreen(SDL_Window *window, int displayIndex, int modeIndex, Uint32 flags);
```
The `displayIndex` and `modeIndex` parameters can be provided by the user and point to one of the supported displays and video modes. To show a window on the primary display, `-1` can be specified. To use the default video mode (e.g. native resolution), `-1` can be passed.

If there is a need to display a window in desktop fullscreen, the `modeIndex` parameter should be ignored and the window should be displayed on the display indicated by `displayIndex`. When disabling fullscreen mode, parameters with display and mode indexes should be ignored. The current set of flags could stay, although it would be good to use a better named set of constants, e.g. the following:

* `SDL_WINDOW_FULLSCREEN_DISABLED` — disable fullscreen mode (the same as currently `0`),
* `SDL_WINDOW_FULLSCREEN_DESKTOP` — the same as now, i.e. activate fake fullscreen,
* `SDL_WINDOW_FULLSCREEN_EXCLUSIVE` — display window in a specified exclusive video mode.

Nothing else is needed, the above proposal would not require the SDL user to write a lot of code to handle fullscreen, and supporting different displays and video modes would be trivial. Currently, not only is it not known how to handled displays and resolutions exactly, but existing functions are bugged and do not work properly.

**Comment by slouken** [comment]
The existing functions are fairly straightforward. There is a single function to set a window fullscreen or not, and the default is to use the common fullscreen desktop behavior. If you want to set a specific fullscreen mode, you just set it once with `SDL_SetWindowDisplayMode()` and then you can toggle back and forth between fullscreen and windowed with `SDL_SetWindowFullscreen()` and change the mode any time with `SDL_SetWindowDisplayMode()`. You do have to enumerate the display modes in order to use that, but you'd have to anyway with your proposal that takes an index.

If the documentation isn't clear, please let us know, and we can clarify that. If you're running into bugs, please enter them as individual issues for tracking purposes.

Thanks!

**Comment by furious-programming** [comment]
If so, it's ok. In that case, the only thing I would ask is to add short examples in the documentation of the [`SDL_SetWindowDisplayMode()`](https://wiki.libsdl.org/SDL2/SDL_SetWindowDisplayMode) and [`SDL_SetWindowFullscreen()`](https://wiki.libsdl.org/SDL2/SDL_SetWindowFullscreen) functions, so that we know exactly how to use these functions correctly (for primary and other displays). Thank you in advance.

**Comment by furious-programming** [comment]
@slouken: I see that the problem with `SDL_SetWindowDisplayMode` is already reported (#8544), so I will add a post there and write what goes wrong when using this function.
