### ISSUE TITLE
SDL_ConvertAudio duplicate frames

### ISSUE THREAD

**Issue by automaciej** [libsdl-org/SDL#8786]
The original post was at https://discourse.libsdl.org/t/change-of-behavior-in-audiocvt-sdl-convertaudio-from-2-0-5-to-2-0-6/24682 and I can still reproduce the issue.

SDL_ConvertAudio gets asked to convert some audio from 1 to 2 channels, and instead of going:

> sample0 sample0 sample1 sample1 sample2 sample2 (…)

it goes:

> sample0 sample0 sample1 sample1 **sample1 sample1** sample2 sample2 (…)

I tested it with 256 frames and this behavior first occurs at array index 130.

The [original post](https://discourse.libsdl.org/t/change-of-behavior-in-audiocvt-sdl-convertaudio-from-2-0-5-to-2-0-6/24682) contains a small C program reproducing the issue.

**Comment by icculus** [comment]
Turns out this wasn't the mono-to-stereo converter, it was a lack of precision in the U8->float converters causing it to land on the wrong number sometimes, looking like it duplicated a channel more than once.

SDL3 fixed this, so I backported the relevant code.
