### ISSUE TITLE
Are triggers reported as [0, 32K) or as [-32K, 32K)?

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#8793]
The documentation in `SDL_gamepad.h` says:

```
 *  Trigger axis values range from 0 to SDL_JOYSTICK_AXIS_MAX.
```

(which is the range [0, 32K), where `[` is inclusive but `)` is not)

But Xbox 360 HIDAPI converts the Uint8 [0, 255] trigger value from the HID API into the range [-32K, 32K), and Switch HIDAPI converts the 1-bit flag for whether ZL/ZR are pressed into either -32K or +(32K-1).

Which is correct? Does the trigger range from 0 to 32K as documented (in which case the HIDAPI drivers should follow that, and other drivers like evdev might also need updating), or does the trigger range from -32K to +32K like the other axes (in which case the documentation should say so)?

**Comment by smcv** [comment]
It might also be helpful to document the sense (direction), which I think is: trigger fully released is either 0 or SDL_JOYSTICK_AXIS_MIN (large and negative), trigger fully pulled is SDL_JOYSTICK_AXIS_MAX (large and positive).

**Comment by slouken** [comment]
Both are correct. Joysticks use the full 16-bit signed range, and gamepads map them into 0 at rest and 32k fully pressed. This is for historical reasons where some gamepads actually did use the full axis range on some platforms.

**Comment by smcv** [comment]
Huh, OK: so SDL_GameControllerGetAxis() and SDL_JoystickGetAxis() will generally return different values for the same device and the same trigger axis? I think that could benefit from some cross-references to make it clearer.

**Comment by slouken** [comment]
Agreed.
