### ISSUE TITLE
SDL_GamepadButtonLabel constants for BACK, START, MISC1?

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#8794]
SDL_GamepadButtonLabel currently covers the ABXY diamond, but nothing else.

The BACK and START buttons also have assorted labels on different gamepads (Select/Start on PS3, Share/Start on PS4, View/Menu on X360, -/+ on Switch), which can be derived from the SDL_GamepadType. Would it be helpful for SDL to include those labels in SDL_GamepadButtonLabel?

**Comment by smcv** [comment]
Similarly MISC1 is variously Share, Capture or Microphone depending who you ask.

This is particularly unfortunate because Back on PS4 is *also* officially labelled Share, but the user expectation (at least on PC) is usually that it does the same thing as Back, Select or View, often some sort of secondary pause menu like an in-game map.

**Comment by slouken** [comment]
I thought about doing that, but since applications would have to have their own art for various controller types, I didn't try to enumerate the entire set of labels. We could, for completeness sake though.

**Comment by smcv** [comment]
I have an untested version of this which I can turn into a PR if you'd like, but I wanted to check whether this is even something you want before polishing it!

**Comment by smcv** [comment]
I wasn't going to bother with the labelling of the shoulder buttons (LB/L1/L, RB/R2/R) or the guide/logo button, just the ones that often have text labels printed/embossed on the controller face. Does that seem a reasonable place to draw the line?

**Comment by slouken** [comment]
If we're going to try for completeness, we should use the full set of names that controller manufacturers have for all the buttons on their controllers. We probably need an extension to the mapping system to allow unknown controllers to specify the labels for their buttons. We probably also need a text representation of these so that games using future versions of SDL can provide something useful for new controllers that don't exist today.

I'm not opposed to this, but that's why I left it at the face buttons. :)

**Comment by smcv** [comment]
Yeah, that's fair. Is this a correct summary of your current position, then?

Games that just want to label the face buttons correctly can use `SDL_GetGamepadButtonLabel()` to cope with the labelling of the most commonly used and therefore most confusing buttons, and use some sort of gamepad-neutral labelling like "left shoulder", "back", "start", "right trigger" for the rest.

Games that care about 100% correct labelling of buttons beyond ABXY (for example labelling Back as Select and left shoulder as L1 on a PS3 pad) should use `SDL_GetGamepadType()`, and have built-in knowledge of how these buttons are labelled by PS3/PS4/PS5, X360/Xbone/Xeries, Switch, etc. gamepads.

**Comment by smcv** [comment]
(Or of course use a higher-level framework like Steam Input that handles that sort of thing for them)

**Comment by slouken** [comment]
> Yeah, that's fair. Is this a correct summary of your current position, then?
> 
> Games that just want to label the face buttons correctly can use `SDL_GetGamepadButtonLabel()` to cope with the labelling of the most commonly used and therefore most confusing buttons, and use some sort of gamepad-neutral labelling like "left shoulder", "back", "start", "right trigger" for the rest.
> 
> Games that care about 100% correct labelling of buttons beyond ABXY (for example labelling Back as Select and left shoulder as L1 on a PS3 pad) should use `SDL_GetGamepadType()`, and have built-in knowledge of how these buttons are labelled by PS3/PS4/PS5, X360/Xbone/Xeries, Switch, etc. gamepads.

That's my current position, yes. I'm open to changing that, and the API can be extended, if I get feedback from game developers that it would be helpful to have that in the core library.

**Comment by smcv** [comment]
OK, let's say this is wontfix unless an actual game developer requests otherwise.
