### ISSUE TITLE
[2.x] video_getSetWindowGrab test failure in testautomation with dummy drivers

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#8796]
## Steps to reproduce

```
$ git describe --tags
release-2.28.0-362-g5e12e4b81
$ podman run --rm -it -w $(pwd) -v $(pwd):$(pwd):rw -v $(pwd)/.git:$(pwd)/.git:ro debian:sid-slim
# sed -i -e 's/Types: deb/& deb-src/' /etc/apt/sources.list.d/debian.sources
# apt update
# apt upgrade
# apt build-dep libsdl2
# ./configure
# make
# cd test
# ./configure \
  --x-includes=/usr/include \
  --x-libraries=/usr/lib/x86_64-linux-gnu \
  SDL_CFLAGS=-I$(pwd)/../include \
  SDL_LIBS="-L$(pwd)/../build/.libs -lSDL2" \
  ac_cv_lib_SDL2_ttf_TTF_Init=no
# make
# export SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy LD_LIBRARY_PATH=$(pwd)/../build/.libs
# make check
```

(the steps above are similar to how Debian currently builds SDL2)

Still in the same container as above, run

```
# ./testautomation
# ./testautomation --filter Video
# ./testautomation --filter video_getSetWindowGrab
```

I'm doing this to get a baseline for whether sdl2-compat can be expected to pass `testautomation`, which would allow `testautomation` to be used as a QA gate to accept/reject new versions. Unlike the "real SDL2" Autotools build system, sdl2-compat's CMake build system treats `testautomation` as a non-interactive test that can be expected to succeed.

When doing the equivalent in SDL3, `testautomation` *does* pass (which is great).

## Expected result

All tests should ideally pass, both `make check` and `testautomation`.

## Actual result

`make check` passes, but `testautomation` does not:

```
ERROR: 01/08/24 16:13:40: Run Summary: Total=305 Passed=289 Failed=8 Skipped=8
ERROR: 01/08/24 16:13:40: >>> Run /w seed 'SPG1ACIYUPHXALSY': Failed
INFO:  01/08/24 16:13:40: Harness input to repro failures:
INFO:  01/08/24 16:13:40:  --seed SPG1ACIYUPHXALSY --filter audio_initQuitAudio
INFO:  01/08/24 16:13:40:  --seed SPG1ACIYUPHXALSY --filter audio_initOpenCloseQuitAudio
INFO:  01/08/24 16:13:40:  --seed SPG1ACIYUPHXALSY --filter audio_pauseUnpauseAudio
INFO:  01/08/24 16:13:40:  --seed SPG1ACIYUPHXALSY --filter video_getSetWindowGrab
INFO:  01/08/24 16:13:40: Exit code: 1
```

For the purposes of this particular issue report, I'm only looking at `video_getSetWindowGrab`; I'll open a separate issue for the others.

If I re-run with either `--filter Video` or `--filter video_getSetWindowGrab`, the test passes. So there must be some sort of state "leaking" into this test-case from another?

**Comment by smcv** [comment]
> If I re-run with either --filter Video or --filter video_getSetWindowGrab, the test passes. So there must be some sort of state "leaking" into this test-case from another?

I wonder whether this is failing *because* #8797 failed?

**Comment by slouken** [comment]
I would be surprised if audio tests interfered with video tests, but I'll take a look.

**Comment by smcv** [comment]
If I switch the three failing tests from #8797 to `TEST_DISABLED`, this test still fails. So I think the problem must be some sort of state "leaking" into it from some other test-suite, but the three audio tests failing in #8797 are not the problem.
