### ISSUE TITLE
X11: Minimum window size setting lost when window is recreated due to creation of renderer

### ISSUE THREAD

**Issue by kspangsege** [libsdl-org/SDL#8805]
In the latest release of SDL, i.e., 2.28.5, and when using the X11-based back-end, the effect of setting the minimum window size (`SDL_SetWindowMinimumSize()`) is lost if a renderer is created (`SDL_CreateRenderer()`), and the minimum window size is set before the creation of the renderer.

It seems to me that the problem is caused by the recreation of the underlying X11 window, which presumably happens because OpenGL is used as renderer back-end, and it requires a different visual than the one picked initially.

This also suggests that the problem will fail to reproduce if the initially chosen visual happens to be compatible with an OpenGL-based renderer back-end.

A workaround for applications seems to be to move the setting of the minimum window size to after the creation of the renderer, or, if the renderer is created late / on demand, the setting of the minimum window size can be repeated after the creation of the renderer.

At the very least, if an actual fix is deemed unnecessary, I think the documentation should be improved to hint about this problem.

**Comment by slouken** [comment]
Fixed, thanks!
