### ISSUE TITLE
run SDL with UBSan ASan

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#8808]
I would be nice to have an option (or just some doc) to setup SDL library, and programs like testautomation with ASan UBSan

**Comment by madebr** [comment]
What I do is configure and build with e.g. `-DCMAKE_C_FLAGS="-fsanitize=address"`.
The CMake script has a `SDL_ASAN` option, but that one enables a lot.
https://github.com/libsdl-org/SDL/blob/ccae9c1ef6b70f4d91eaf4e95f48ee806b8081bd/CMakeLists.txt#L2941-L2959

**Comment by 1bsyl** [comment]
With the cmake flags, not sure why, I have a bunch of unresolved asan symbol.

With SDL_ASAN=ON, It compiles (but I am pretty sure that it doesn't actually uses the asan stuff, because of no output)

**Comment by madebr** [comment]
For my distro (=Fedora), I have to install `libasan`, `liblsan`, `libubsan` and `libtsan` using the package manager.
You can verify the build/link flags by building with `cmake -build . --verbose`.
When I run with asan, the tests emit a lot of warnings due to leaks.

**Comment by 1bsyl** [comment]
I have the pacakge, and the verbose just show more the links error.

but now it works now! 
I changed various variables in the cmakecache file.
maybe, the more relevant switch from llvm to gcc ...

thanks anyway !

**Comment by 1bsyl** [comment]
btw, it re-happens,  but seems the fix is to give the library in command line:

```
cmake -DCMAKE_C_FLAGS="-fsanitize=address"  -DCMAKE_CXX_STANDARD_LIBRARIES="-lasan" .
cmake -DCMAKE_C_FLAGS="-fsanitize=undefined"  -DCMAKE_CXX_STANDARD_LIBRARIES="-lubsan" .

```

**Comment by madebr** [comment]
`CMAKE_C_FLAGS` is used when compiling C sources, and for linking targets with C link languages (=targets that ONLY contain `.c.o` objects).
When you add at least 1 c++ source, the linking will bill be done with `CXX` link languages, so then it will use `CMAKE_CXX_FLAGS`.

So for c++ projects, you need to configure with `-DCMAKE_C_FLAGS=-fsanitize=address -DCMAKE_CXX_FLAGS=-fsanitize=address`.
`CMAKE_CXX_STANDARD_LIBRARIES` should not be necessary.
[Its documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_STANDARD_LIBRARIES.html) says it should be set by platform information modules (e.g. in [`CMake/Modules/Platform/Windows-MSVC.cmake`](https://github.com/Kitware/CMake/blob/87200ec97fb5945a942eec210fbc2d2d4194ed5c/Modules/Platform/Windows-MSVC.cmake#L207C7-L207C39))

**Comment by 1bsyl** [comment]
ok, make sense, indeed that works!

for the record:
`cmake -DCMAKE_C_FLAGS="-fsanitize=address -fsanitize=undefined" -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=undefined"  .`
