### ISSUE TITLE
Wayland video driver does not show a window

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8809]
No window is shown when using the wayland video driver.
When running the testsprite test, the fps is printed to stderr but no window is shown.

Last good commit was 95066ce2a0b37f0c703b9b63dfe6e8e407d10221

It got broken in the commit range:
392796e49c40bff0ad08ac899ffcd2834ad87aca: skipped (build failure)
4417250d0dd02f25302c61e87aebf8d9d45e55be: skipped (build failure)
f7dd0f9491ab52833801dce8b5ebc4694e8e7c39: no wayland window

@Kontrabant 

system: Fedora 38, libwayland-client 1.22.0, libdecor 0.2.1

**Comment by Kontrabant** [comment]
Whoops, a rather important line was lost while rebasing. Fix incoming.
