### ISSUE TITLE
Error C2732 linkage specification contradicts earlier specification for 'wWinMain'

### ISSUE THREAD

**Issue by ilyachastikov** [libsdl-org/SDL#8814]
In latest version of main branch I've got compilation error: Error C2732 linkage specification contradicts earlier specification for 'wWinMain' in Visual C++. I've investigated this problem and found out what reason of this is deleting 
`#ifdef __cplusplus
extern "C" {
#endif`
before 
`typedef struct HINSTANCE__ * HINSTANCE;`
and corresponding closing conditional compilation of __cplusplus in SDL_main_impl.h.
I think this code should be returned.

**Comment by slouken** [comment]
Looking at my headers for Visual Studio 2019 I'm not seeing where wWinMain() has C linkage. Where is that specified in your configuration?

**Comment by DanielGibson** [comment]
this is weird, I don't think I've ever seen extern "C" around `WinMain()` in C++ code (is it different for `wWinMain()`?)

**Comment by DanielGibson** [comment]
OTOH, maybe it's specified that way in some windows header that we're not including in SDL_main_impl.h
