### ISSUE TITLE
A way to access logical_dst_rect?

### ISSUE THREAD

**Issue by Ethanscharlie** [libsdl-org/SDL#8815]
I'm working with ImGui and am facing an issue when using logical rendering and an aspect ratio change. I believe I could fix my issue my offsetting the panel position with the logical_dst_rect position, but currently it doesn't look like there is any way to access it without the definition of the SDL_Renderer

**Comment by slouken** [comment]
Can you explain more? Conceptually the logical rect is the viewport that you can draw into and it shouldn't matter where it is.

**Comment by Ethanscharlie** [comment]
Sorry it took me so long to respond, I need to know where it is to correctly draw an imgui panel, for logical rendering I have to turn it off before I render the imgui frame, because of that I need to know where to put the frame, and that involves the offset that the logical rect is from 0, 0 because of how it is pushed to the middle with letterboxing, currently I am using a modified version of the UpdateLogicalPresentation method to get the rect, but this should just be a sdl feature

**Comment by slouken** [comment]
That makes sense, thanks.

**Comment by Ethanscharlie** [comment]
If I were to add this would I belong in SDL_render.h?

**Comment by Ethanscharlie** [comment]
I made a pull request
