### ISSUE TITLE
UpdateWindowFramebuffer

### ISSUE THREAD

**Issue by Poleg44** [libsdl-org/SDL#8825]
I use SDL2 lib at my Python Pygame app.
The program runs on Raspberry and has a Full HD resolution. For good performance, it is necessary to update not the entire screen, but the required part.
Pygame uses the pygame.display.update(pygame.Rect()) command, when the required update rectangle.
I noticed that SDL does not work correctly on Raspberry, but it works correctly on Windows.
I have created a Python test program that updates only 1 pixel with coordinates 50, 50. For clarity, this pixel is green on a black background.
For completeness, I present this text program and screenshots for Raspberry and Windows:

import pygame
pygame.init()

surface = pygame.display.set_mode((400,300), pygame.NOFRAME)
pygame.draw.rect(surface, (0, 255, 0), (0, 0, 400, 300))

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    pygame.display.update(pygame.Rect((50, 50, 1, 1)))
![Screenshot_766](https://github.com/libsdl-org/SDL/assets/152655126/024edb02-8452-4790-86bb-f04653395903)
![Screenshot_767](https://github.com/libsdl-org/SDL/assets/152655126/46407c99-bd72-40b3-8447-ce199819380f)

You can be see that the program is executed correctly in the Windows version (green pixel on a black background).
But at Raspberry line has been updated. That is, the x position and height are accepted correctly, but the y position and width are not.

As far as I know, the SDK uses different functions for different platforms. This means that the implementation of the Update Window Frame buffer for Raspberry has an error.

At Raspi: SDL 2.26.5, at Windows: SDL 2.28.5

**Comment by Poleg44** [comment]
i try research:
SDL lib use SDL_UpdateWindowSurfaceRects(SDL_Window *windows, const SDL_Rect *rests, int numrects) function
file SDL2-2.28.5/src/video/SDL_video.c, line 2716
next function: _this->UpdateWindowFramebuffer(_this, window, rects, numrects)

i think,
for Raspberry this will X11_UpdateWindowFramebuffer(_THIS, SDL_Window *window, const SDL_Rect *rects, int numrects)
file SDL2-2.28.5/src/video/x11/SDL_x11framebuffer.c, line 145
for Windows this will WIN_UpdateWindowFramebuffer(_THIS, SDL_Window *window, const SDL_Rect *rects, int numrects)
file SDL2-2.28.5/src/video/windows/SDL_windowsframebuffer.c, line 101

These functions are very different

**Comment by Poleg44** [comment]
I found a discussion of a similar issue for the Windows platform in 2020:
[https://discourse.libsdl.org/t/question-about-implementation-of-sdl-updatewindowsurfacerects/27561](url)
It was successfully solved 4 years ago.

**Comment by icculus** [comment]
Is the raspberry Pi version using x11, or kmsdrm (is there a whole desktop or is the app taking the whole screen without a window manager)?

**Comment by Poleg44** [comment]
I tested both options (X11 and terminal). Tried Pi4 and Pi5. The result is the same everywhere.
Only for Pi5 I had to install a patch according to
[https://github.com/libsdl-org/SDL/issues/8579](url)

**Comment by Srandista** [comment]
Just curious, what OS are you using on those Pi's?

**Comment by Poleg44** [comment]
Yes, Raspi provides inexpensive and effective solutions )

**Comment by Srandista** [comment]
No, I mean, is it the Raspberry Pi OS you're using on the Pi? If yes, is it the one based on Debian 11 or Debian 12?

**Comment by Poleg44** [comment]
Debian 12 (bookworm)

**Comment by Srandista** [comment]
Have you tried it on Debian 11 (Bullseye)? I have similar sounding issue with other SDL2 based games, which I mentioned here: #8792 
I have no programing experience, so I can't help with troubleshooting issue, but it's good to see, that (at least it seems) I'm not the only one experiencing this problem.

**Comment by smcv** [comment]
Back in 2020, @slouken said this on #3663:
> The rects argument is just supposed to be an optimization. Conceptually the entire back buffer is reflected to the front buffer.

That would imply that this is not necessarily considered to be a bug: if I'm understanding correctly, the specification for `SDL_UpdateWindowSurfaceRects()` is that it will copy *at least* the specified rectangle(s) to the window surface, but it is allowed to copy more than that if it's easier or more efficient to implement that way on a particular platform.

In the Discourse thread you linked, @icculus also gave this advice:
> I would also encourage you not to use this function, but rather wrap your 2D rendering in the SDL render API, which will move the work to the GPU and get you free scaling, etc. This is often worthwhile (and faster!) even if you’re just uploading a block of pixels you rendered yourself on the CPU every frame.

**Comment by icculus** [comment]
Yeah, I think we should close this. Notably: The X11 backend _does_ respect dirty rectangles, but on almost any modern system, we _do not use the X11-specific code_.

It'll almost certainly use OpenGL to get bits to the screen (this is in SDL_UpdateWindowTexture, which replaces the implementation's UpdateWindowFramebuffer function pointer), and we have no control over subregions of the screen here, since we have to present the whole backbuffer in all cases.

**Comment by icculus** [comment]
(I've updated the documentation to reflect the reality, though.)
