### ISSUE TITLE
SDL_GetGlobalMouseState returns wrong mouse position when using x11vnc

### ISSUE THREAD

**Issue by chrismile** [libsdl-org/SDL#8827]
Hi,

When using x11vnc to stream the content of the screen on Ubuntu 22.04, SDL_GetGlobalMouseState will not return the actual current mouse position, but the position where the last mouse click occurred.

I have reported this bug first on ImGui, which has an SDL2 backend: https://github.com/ocornut/imgui/issues/7217

I confirmed that the current code of `X11_GetGlobalMouseState` is almost the same as SDL 2.0.20 (the version shipped by Ubuntu 22.04; it only has an ifdef check for XInput2 instead of a runtime check): https://github.com/libsdl-org/SDL/blob/5b3ee51c6ca94f803a4ca77ce0dce08ee0426f80/src/video/x11/SDL_x11mouse.c#L419

I can't say for certain if XInput2 is enabled in the version of SDL2 shipped with Ubuntu, but if it is, then I believe this behavior could be explained this way:
- The position is only updated if global_mouse_changed is true.
- It is set to true in SDL_x11xinput2.c if, e.g., XI_RawMotion or XI_RawButtonRelease events are encountered by XInput2.
- The XI_RawMotion event is not triggered by x11vnc, but XI_Motion. global_mouse_changed is not set to true by this event.

This is also supported by this source: https://stackoverflow.com/questions/62448181/how-do-i-monitor-mouse-movement-events-in-all-windows-not-just-one-on-x11
> Set mask to receive XI_RawMotion events. Because it's raw, XWarpPointer() events are not included, you can use XI_Motion instead.

If x11vnc uses XWarpPointer (which is highly likely, as the mouse position is transferred via the network), XI_RawMotion will never trigger, and as SDL doesn't set the variable to true for XI_Motion events, it will think the mouse position never changed. Only when a XI_RawButton* event arrives, it will finally update the mouse position.

The solution should be for SDL to also set global_mouse_changed to true when encountering XI_Motion events. This should be a bug in SDL2 and not in x11vnc, as it should be perfectly legal for x11vnc to call XWarpPointer, which triggers a XI_Motion event, which in turn is not handled correctly by SDL.

**Comment by icculus** [comment]
Hmm, this is working for me here.

I added this to testsprite2.c:

```diff
diff --git a/test/testsprite2.c b/test/testsprite2.c
index 71b565678..15ab3f4d2 100644
--- a/test/testsprite2.c
+++ b/test/testsprite2.c
@@ -411,6 +411,11 @@ void loop()
 
     /* Check for events */
     while (SDL_PollEvent(&event)) {
+if (event.type == SDL_KEYDOWN) {
+    int x = 0, y = 0;
+    SDL_GetGlobalMouseState(&x, &y);
+    SDL_Log("Global position: (%d, %d)", x, y);
+}
         SDLTest_CommonEvent(state, &event, &done);
     }
 
```

I launched x11vnc on a Linux virtual machine, connected to that machine with a VNC client, and then ran the modified testsprite2 on the machine running x11vnc. Occasionally I press a keyboard key (not space, that pops up a message box) while moving the mouse around _on the VNC client, not the system that x11vnc is serving to the client_, and it appears to be showing global positions for that remote desktop correctly without clicking the mouse.

Am I doing this wrong and/or misunderstanding the problem?

**Comment by chrismile** [comment]
First of all, thanks for testing it! I cloned the SDL code from release-2.28.5 and added your changes to testsprite2.c. For me, SDL_GetGlobalMouseState behaves incorrectly for the SDL2 test (i.e., the same as in ImGui). That means: When I press any key, the mouse position is returned where the last mouse click happened, and not the correct one.

I am unsure what the source of the missing replicability is. I will try to set up a virtual machine with Ubuntu 22.04 and test it there with a fresh system. I use the following arguments for x11vnc, which could potentially be the source of the different results: `-xkb -noxdamage -repeat -forever -clip xinerama0 -rfbport 5900 -display :0 `.

**Comment by icculus** [comment]
Just tried 2.0.20 just to make sure, and _that's_ working, too, so something else is up here. If imgui didn't make a change to workaround the issue, maybe it's an x11vnc thing? Or the VNC client? (I'm using Remmina here.)

**Comment by chrismile** [comment]
I'm also using Remmina, so maybe it is the x11vnc arguments I use. Which x11vnc arguments did you use for testing? Then I will try that on my system.

**Comment by icculus** [comment]
I just ran `./x11vnc`, but I also tried it with your arguments a moment ago (`-xkb -noxdamage -repeat -forever -clip xinerama0 -rfbport 5900 -display :0`) to the same effect: still worked.

**Comment by chrismile** [comment]
Did you use the x11vnc from the Ubuntu repos or the most current version?

**Comment by icculus** [comment]
I installed it with `apt-get`

```
$ x11vnc -version
x11vnc: 0.9.16 lastmod: 2019-01-05
```

I just realized the virtual machine is a Debian 12 installation and not Ubuntu, though, but I can't imagine it matters _that_ much. (right?!)

**Comment by chrismile** [comment]
I'll install both a fresh version of Ubuntu 22.04 and Debian 12 in a VM and keep you updated on whether it makes a difference.

**Comment by icculus** [comment]
I was on VMware Workstation. I'll try to roll a real Ubuntu install on a real machine later.

**Comment by chrismile** [comment]
I was able to get the SDL tests to run now with VirtualBox. Indeed, on a freshly installed system, I cannot replicate the issue. I will continue investigating what the source could be.

**Comment by chrismile** [comment]
So I tried to set up the VirtualBox Ubuntu 22.04 system in exactly the same way my physical PC is set up: Same DE (XFCE), same login manager (LightDM), same x11vnc startup service, ...
However, only on my physical system `SDL_GetGlobalMouseState` works incorrectly over x11vnc. The only differences I can see is that (a) I do not use VirtualBox on my physical system, and (b) I use the proprietary NVIDIA driver.

I asked a colleague at work if they could also test it, and they get the same faulty behavior of `SDL_GetGlobalMouseState` over x11vnc (using Gnome as the DE in their case, but also with an NVIDIA GPU).

**Comment by chrismile** [comment]
Additional info: Whatever the reason may be why `SDL_GetGlobalMouseState` makes problems on my physical system only - when I add `videodata->global_mouse_changed = SDL_TRUE;` to `case XI_Motion` in `SDL_x11xinput2.c`, the problem is fixed.

**Comment by chrismile** [comment]
@icculus I finally found out why it was not possible to recreate the issue on a VM. According to the file `x11vnc.1` from the x11vnc repo, XWarpPointer is only used if more than one monitor is connected. This is true for both my PC and the PC my colleague used for reproducing this issue on their system, but VMWare Workstation/VirtualBox do not use multiple monitors by default. When I add a second virtual monitor to my Ubuntu 22.04 VM, `SDL_GetGlobalMouseState` stops working. As explained in the last comment, it should be sufficient to add `videodata->global_mouse_changed = SDL_TRUE;` to `case XI_Motion` in `SDL_x11xinput2.c` to fix this issue.

**Comment by chrismile** [comment]
Btw., it should theoretically also possible to add the option `-xwarppointer` to x11vnc to be able to replicate this issue with only one monitor connected.

In the end, I'd say this is not necessarily even a x11vnc related issue, but a general issue that SDL does not set `videodata->global_mouse_changed` to true when `XWarpPointer` is used by some application.

**Comment by icculus** [comment]
Okay, the fix is in revision control, for both SDL2 and SDL3!

I'm impressed with all the research you did not just to solve this, but figure out _why_ it was happening with x11vnc. Nice work.  :)
