### ISSUE TITLE
Clipboard data gets cleared on exit

### ISSUE THREAD

**Issue by jqcorreia** [libsdl-org/SDL#8830]
Hello and first of all thank you for this amazing work.
I'm writing a omnibar-ish application using SDL2 and need to put text into the clipboard and it to be available after the application closes.

After some search on why any method I used in order to achieve this, I ended with no ideas and a clear clipboard.
Then I stumbled on [this](https://github.com/libsdl-org/SDL/blob/483155bbf94b661b9054d1dba75b23ec9ed5626a/src/video/SDL_video.c#L3718), (thanks @slouken for the helpful commit message) 

Is there a reason to wipe the clipboard on SDL_Quit that I'm not understanding? If so is possible for this behaviour to be configurable? I'm more than happy to try and provide a PR for this if needed.

Thanks in advance.

**Comment by slouken** [comment]
Yeah, there's really no reason to do this.

Fixed, thanks!
