### ISSUE TITLE
[SDL2] hidapi_switch: `m_bUseButtonLabels` conflicts with controller configurations

### ISSUE THREAD

**Issue by SuperSamus** [libsdl-org/SDL#8837]
This is a little hard to explain, so I'll use examples.

Let's say you are using a controller configuration like [this one](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt).
In that configuration, the Switch Pro Controller is only mapped by positions (there is no mapping by labels).

If you are using `SDL_JOYSTICK_HIDAPI_SWITCH=0`, then it rightfully doesn't matter what value `SDL_GAMECONTROLLER_USE_BUTTON_LABELS` is set to: the configuration says that \<South\>=A, and this is respected.

But if you are using `SDL_JOYSTICK_HIDAPI_SWITCH=1`:
- With `SDL_GAMECONTROLLER_USE_BUTTON_LABELS=1`, the mapping is positional. While it doesn't respect the hint name, it is respecting the configuration (just like above).
- With `SDL_GAMECONTROLLER_USE_BUTTON_LABELS=0`, the mapping is by labels. Meaning that it doesn't respect the hint name, nor the configuration. It makes no sense.

This is the output I get with `sdl2-jstest -g`, using the configuration I linked, when holding the South button on my Switch Pro Controller.
![image](https://github.com/libsdl-org/SDL/assets/40663462/7418ee8e-fe1c-428a-87bc-4a155abef999)
You can see that top-right it makes no sense.

**Comment by slouken** [comment]
You're not intended to create a positional mapping for HIDAPI controllers, instead you use the hint to control whether the built-in mapping is positional or by label.

This is changed in SDL3 so the buttons are always positional.

**Comment by SuperSamus** [comment]
> You're not intended to create a positional mapping for HIDAPI controllers

Many programs (e.g. [PCSX2](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Input/SDLInputSource.cpp#L229)) add a configuration file themselves.
Also, maybe someone's goal for adding the configuration isn't to modify the Switch Pro Controller, but to add support for other controllers, and the Switch Pro Controller is part of the file.

So, what I'm saying is, the issue can easily be reproduced accidentally.

> instead you use the hint to control whether the built-in mapping is positional or by label

I've been setting the hint to 0 (position) for a while, tried PCSX2 for the first time, which automatically sets the configuration file, reproduced this (top-right corner of the image), and wrote this issue after understanding what's happening.

(Also, the issue *is* about that hint.)

> This is changed in SDL3

I know, I did specify SDL2 in the title.
