### ISSUE TITLE
SDL_SetWindowDisplayMode does not change refresh rate for some renderers

### ISSUE THREAD

**Issue by thrust26** [libsdl-org/SDL#8838]
I found that OpenGL ignores the refresh rate setting while Direct3D works fine. However in both cases the function returns no error.

**Comment by slouken** [comment]
@icculus, is this an actual bug, or just a driver quirk?

**Comment by icculus** [comment]
My suspicion is driver quirk, but I'll take a look at what we're doing here.

**Comment by thrust26** [comment]
It would already help if the function returned an error.

**Comment by icculus** [comment]
Yeah, it looks like we're doing things as correctly as possible; there doesn't appear to be a way to tell WGL to use a specific display refresh rate, so you get whatever we've set the display to via Win32 calls...and if the driver ignores it, there's not much we can do.

(If this is totally incorrect, let's reopen this, but I don't see a way to do anything differently.)

**Comment by thrust26** [comment]
Maybe you should add a comment to the documentation here. That you cannot trust the return value.
