### ISSUE TITLE
dedicated `WM_INPUT` thread using `GetMessage()` 

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#8841]
On Windows, each thread that creates a window gets its own message queue.

If you spawn a thread that creates a window with the parent handle set to `HWND_MESSAGE`, and subscribe to rawinput messages with target set to that window, then the thread will only ever receive `WM_INPUT` messages.

This means that you can use the blocking `GetMessage()` syscall (instead of polling with `PeekMessage()`) for that dedicated thread, it will have the theoretically lowest latency between the OS placing a rawinput message into its queue and the thread reacting to it, as well as having the advantage of it being idle most of the time until an input is available.

The thread should do very light processing that just fetches the rawinput packet and forwards it to the SDL event queue. Maybe also doing a extremely low-latency timestamp capture like this:

```
While true:
    msg = GetMessage(); // blocks until a message arrives
    timestamp = QueryPerformanceCounter(); // capture timestamp at exact instant a msg arrives
    if msg.flag==0xFF then ForwardResult(timestamp, GetRawinputData(msg));
    elif ShouldQuit(msg) then break;
```

**Comment by slouken** [comment]
This was implemented in https://github.com/libsdl-org/SDL/commit/31851a50d2e30efa1a3c74ae83592d6a29ffc5b7.

**Comment by slouken** [comment]
Have you tried it? It’s actually more efficient with high data rate mice. It also blocks until there are events, so it combines the best of both worlds.
