### ISSUE TITLE
gamescope in GNOME Wayland with a Vulkan client is broken without SDL_VIDEODRIVER=x11

### ISSUE THREAD

**Issue by DeedleFake** [libsdl-org/SDL#8845]
Coming from https://github.com/ValveSoftware/gamescope/issues/1051. Essentially, gamescope has a ton of issues in a specific situation that all disappear when `SDL_VIDEODRIVER=x11` is set, implying that this is not a gamescope-specific bug.

If gamescope runs as a Wayland client in GNOME 45 on an AMD card and has a Vulkan client running inside of it, it causes all sorts of bizarre problems, such as an inability to start fullscreen with the `-f` flag, and often just utterly refusing to start after the first run until the entire computer is rebooted, instead spamming the console with vague error messages and requiring a SIGKILL to stop. Setting `SDL_VIDEODRIVER=x11` before running it, however, fixes every single one of those problems, which makes me think that this is an SDL bug, not a gamescope bug.

This happens in both the latest gamescope release and the latest gamescope `master`. My local SDL2 version is 2.28.5.

**Comment by slouken** [comment]
I'm going to bounce this back to gamescope for further investigation. Forcing gamescope to run under X11 doesn't necessarily mean that it is doing the right thing under Wayland. @Joshua-Ashton might have more insight.

**Comment by Joshua-Ashton** [comment]
You must have a global definition of SDL_VIDEODRIVER somewhere, you must unset it.
