### ISSUE TITLE
Remove the ability to disable timers

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8850]
This is a core subsystems and many other things in SDL are broken if they are removed.

**Comment by icculus** [comment]
YES PLEASE

**Comment by slouken** [comment]
It turns out we already did that for threads (with the exception of Emscripten), so this just covers timers.

**Comment by icculus** [comment]
PR looks good to me.

Are there other things that should probably always exist but can be turned off? cpuinfo/loadso/atomic or whatever?

**Comment by slouken** [comment]
Most are okay, atomics and events should probably always be enabled. I'm looking at those now.
