### ISSUE TITLE
dynamically adjustable mouse scaling factor (e.g. able to map to an analog axis)

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#8856]
would like an option/flag/api that makes the mouse delta scalable by a user-mappable input axis, e.g. hold right trigger for highest scaling factor, completely release right trigger for a factor of zero (e.g. mouse disabled), ideally with a user-definable transfer function.

**Comment by slouken** [comment]
You should be able to dynamically change the mouse speed scale hints to achieve this.

**Comment by slouken** [comment]
Sure, these hints affect the mouse speed scale in various circumstances:
https://github.com/libsdl-org/SDL/blob/0d7df16812c75c4a587d7d2673e3d1a5f2c2879b/include/SDL3/SDL_hints.h#L1340-L1343
https://github.com/libsdl-org/SDL/blob/0d7df16812c75c4a587d7d2673e3d1a5f2c2879b/include/SDL3/SDL_hints.h#L1372-L1375
