### ISSUE TITLE
Suggestion: Function for vertically flipping SDL_Surface

### ISSUE THREAD

**Issue by broughtong** [libsdl-org/SDL#8857]
When using SDL with OpenGL, most people immediately have to flip their images in the vertical axis due to the different assumptions about which direction the positive Y axis goes.

Current Options to do this are:

1. Use an SDL renderer. Not really efficient to set one up just for this purpose if we're already using OpenGL rendering directly.

2. Manual pixel manipulation. Loop through the surface->pixels (row by row) and swap them around. In C++ we can  just memcpy the row to a temporary buffer, swap in the new one, and write the buffer to the old position. But when using SDL as a library from other languages, trying to directly play with C++ pointers and types and allocate memory dynamically is _really_ a PITA.

3. Flip images on disk. Makes working on them difficult as they're now inverted.

4. Flip them in the GPU shaders. Which means complicating any UV code with constantly prefixing "1.0-" and needless extra calculations each frame.

I therefore suggest to add a function to vertically flip the SDL_Surface structures without requiring manual manipulation or setting up renders, along the lines of `int SDL_FlipSurfaceVertically(SDL_Surface *src)`

**Comment by Starbuck5** [comment]
This has been brought up in https://github.com/libsdl-org/SDL/issues/5697

**Comment by slouken** [comment]
Done!
