### ISSUE TITLE
Support X11 incremental clipboard transfers

### ISSUE THREAD

**Issue by raiguard** [libsdl-org/SDL#8871]
In our game, copy/pasting very large strings is relatively common, as users can share "blueprint strings" that can grow to be several megabytes large. I attempted to change our codebase to rely on SDL's clipboard functions in lieu of our custom implementations, but that made users unable to [paste large blueprint strings](https://forums.factorio.com/105915) on X11.

Some investigation has revealed the existence of the [INCR mechanism](https://tronche.com/gui/x/icccm/sec-2.html#s-2.5) in X11 to transfer large selections in the clipboard. Our custom X11 clipboard code implements this, but it appears that the SDL X11 clipboard does not, meaning that if this mechanism is used, pasting into the SDL application will not work. I would love it if this could be supported so I can fully rely on the SDL clipboard functions in the future!

Attached below is the problematic string.

[huge-blueprint.txt](https://github.com/libsdl-org/SDL/files/13980251/huge-blueprint.txt)

**Comment by raiguard** [comment]
Apologies, immediately after posting I noticed that this is implemented in SDL3. Is there a chance this could be backported?

**Comment by slouken** [comment]
We're working on showstoppers for 2.30 and focused on moving towards SDL 3.0 release. Feel free to submit a PR that implements this though!

**Comment by icculus** [comment]
@raiguard When you get a chance to test that PR, let me know; you have the best possible test case for it, so if it covers your needs, I'll merge it.

**Comment by raiguard** [comment]
I made a small app to test this and it appears to work great! Unfortunately I cannot test it with the actual game since we are still on SDL2, but it should theoretically work just the same.

**Comment by icculus** [comment]
Would this be difficult to cherry pick to SDL2? I assume the surrounding code is pretty different.

**Comment by slouken** [comment]
> Would this be difficult to cherry pick to SDL2? I assume the surrounding code is pretty different.

Yep, it is.
