### ISSUE TITLE
Finalizing SDL 3.0 API changes

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8872]
This issue is intended to capture the remaining work on finalizing the SDL 3.0 API.

Here's a list of the open API issues that are blocking a 3.0 release:
- [ ] https://github.com/libsdl-org/SDL/issues/6644
- [x] https://github.com/libsdl-org/SDL/issues/9056
- [ ] https://github.com/libsdl-org/SDL/issues/9439
- [x] https://github.com/libsdl-org/SDL/issues/9542
- [x] https://github.com/libsdl-org/SDL/issues/9626
- [x] https://github.com/libsdl-org/SDL/issues/9493
- [x] https://github.com/libsdl-org/SDL/issues/9484
- [x] https://github.com/libsdl-org/SDL/issues/9482

Not blocking, but would be nice:
- [ ] https://github.com/libsdl-org/SDL/pull/7067

@libsdl-org/a-team, is there anything else I'm missing?

**Comment by Starbuck5** [comment]
icculus's videocapture/camera PR does API changes: https://github.com/libsdl-org/SDL/pull/8633

**Comment by slouken** [comment]
Added!

**Comment by slime73** [comment]
Decide whether the accelerometer-as-joystick feature should be removed now that there's a real sensor API? (#3012 / #7879)

**Comment by sezero** [comment]
GPU api: https://github.com/libsdl-org/SDL/pull/7067 ?

**Comment by slouken** [comment]
Added!

**Comment by icculus** [comment]
After I finish the camera API (which keeps getting stalled for other tasks, but is close to done), I can go hard on the filesystem stuff...and then I _have_ to go hard on the GPU API. I _really_ want this in 3.2.0 if it's at all possible, but I understand we're getting down to the wire here.

**Comment by slouken** [comment]
I've created a new milestone for issues that need to be complete for the ABI freeze:
https://github.com/libsdl-org/SDL/milestone/16
