### ISSUE TITLE
Distorted audio in 2.29.1

### ISSUE THREAD

**Issue by vladkosi** [libsdl-org/SDL#8886]
Release canditate version 2.29.1 produces distorted audio in ScummVM 2.8.0, Windows 10 64-bit, 44.1 kHz output sample rate. Tested with multiple games.

[2.29.1.zip](https://github.com/libsdl-org/SDL/files/13997455/2.29.1.zip)
[2.28.5.zip](https://github.com/libsdl-org/SDL/files/13997457/2.28.5.zip)

![1](https://github.com/libsdl-org/SDL/assets/6567423/69202bc8-4df7-4906-9ec0-0a8e1a7b8aec)

**Comment by slouken** [comment]
@icculus, is this related to the audio converter backport?

**Comment by Starbuck5** [comment]
Running through the pygame-ce test suite I also hear distorted audio.

**Comment by icculus** [comment]
> @icculus, is this related to the audio converter backport?

It's possible. I'll take a look.

**Comment by slouken** [comment]
I can confirm audio is badly distorted and checking out the commit before 1e2f3118117a3cd6d483ea090db8d15a50f3bfdc fixes it.

**Comment by icculus** [comment]
Test with the latest in revision control, I bet @pionere just fixed it.

**Comment by slouken** [comment]
I can confirm that fixes it. Thanks @pionere!
