### ISSUE TITLE
SDL_ShowMessageBox isn't honoring SDL_VIDEODRIVER env setting

### ISSUE THREAD

**Issue by shmerl** [libsdl-org/SDL#8892]
I was testing recent SDL version of Freerdp 3 and while running it in KDE Wayland session and using `SDL_VIDEODRIVER='wayland'`, it opened an X11 variant of a dialog (using `SDL_ShowMessageBox`).

So it looks like setting `SDL_VIDEODRIVER='wayland'` isn't enough? Does it need anything else to work without X11 on Wayland?

* SDL: 2.8.2
* FreeRDP: 3.2.1-dev0 (bc23b205b)

See https://github.com/FreeRDP/FreeRDP/issues/9787

**Comment by icculus** [comment]
Currently, without a video backend initialized, SDL tries all available message box implementations until one works.

I agree this should probably respect `SDL_VIDEODRIVER` (`SDL_VIDEO_DRIVER` in SDL3), though.

Right now the code does like this:

```c
#ifdef SDL_VIDEO_DRIVER_X11
    if (retval == -1 &&
        X11_ShowMessageBox(messageboxdata, buttonid) == 0) {
        retval = 0;
    }
#endif
#ifdef SDL_VIDEO_DRIVER_HAIKU
    if (retval == -1 &&
        HAIKU_ShowMessageBox(messageboxdata, buttonid) == 0) {
        retval = 0;
    }
#endif
```

We could probably just make that:

```c
#ifdef SDL_VIDEO_DRIVER_X11
    if (retval == -1 && (!viddrv || (SDL_strcmp(viddrv, "x11") == 0) &&
        X11_ShowMessageBox(messageboxdata, buttonid) == 0) {
        retval = 0;
    }
#endif
```

@slouken, should I change this?

**Comment by slouken** [comment]
> Currently, without a video backend initialized, SDL tries all available message box implementations until one works.
> 
> I agree this should probably respect `SDL_VIDEODRIVER` (`SDL_VIDEO_DRIVER` in SDL3), though.
> 
> @slouken, should I change this?

Yes, I think this is a good change for both SDL 2 and 3.

**Comment by icculus** [comment]
Okay, this is in SDL2 and release-2.30.x, too.

**Comment by sezero** [comment]
Pushed 9e352e61db6836e85e24e9f2497dee5a62d8e212 to SDL2 (and cherry-picked to 2.30.x) as a follow-up fix.

video/pandora is still not touched, but as far as I can see it is very much out of date.

**Comment by sezero** [comment]
BTW: struct SDL_VideoDevice->ShowMessageBox() is never set, as far as I can see..
