### ISSUE TITLE
how to use transformation matrix to change image during rendering

### ISSUE THREAD

**Issue by LWshu0** [libsdl-org/SDL#8893]
I need to render an image using the transformation matrix, just like the opengl rendering pipeline. But I can't achieve it using SDL_RenderCopyEx.
for example:

![coin_gold_dollar](https://github.com/libsdl-org/SDL/assets/113842364/65736aa6-fdd8-40ae-bfb4-9ab5c4b19771)

to

![coin2](https://github.com/libsdl-org/SDL/assets/113842364/91ffa4ef-01b8-4a87-9819-2ac6ce174d74)

**Comment by slime73** [comment]
You could use SDL_RenderGeometry and apply your transformation to the vertex positions before giving them to SDL. I don't think SDL_Render provides a full transformation matrix otherwise (including skew/shear, which it looks like that example is using).
