### ISSUE TITLE
SDL_BlitSurface segfault

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL#8897]
I've been chewing on the SDL 2.29.1 pre-release for a few days now trying to figure out some failures and segfaults in the pygame-ce test suite.

I found that one of our image saving routines was segfaulting, and I tracked it down to SDL_BlitSurface and this commit https://github.com/libsdl-org/SDL/commit/bb969ac74710604d13c189899d37c285e90ccaf8

Here is a minimum reproducible example (this segfaults for me):
```c
SDL_Surface* surface = SDL_CreateRGBSurfaceWithFormat(0, 1, 1, 32, SDL_PIXELFORMAT_ARGB8888);
SDL_Surface* linebuf = SDL_CreateRGBSurfaceWithFormat(0, 1, 1, 32, SDL_PIXELFORMAT_ARGB8888);
SDL_Rect srcrect = {0, 0, 1, 1};
SDL_BlitSurface(surface, &srcrect, linebuf, NULL);
```

This code lacks a dest rect, and SDL_UpperBlit now sends that NULL through into SDL_LowerBlit, where it didn't previously.

**Comment by 1bsyl** [comment]
I see, this should be
        return SDL_LowerBlit(src, &r_src, dst, &r_dst);
I'll fix that

**Comment by 1bsyl** [comment]
done.
for SDL3, that was actually ok https://github.com/libsdl-org/SDL/commit/3639743d8909406557663af0854dc7bd97956b24
issue, was when doing the merge probably.

**Comment by 1bsyl** [comment]
@Starbuck5 please give a try

**Comment by oddbookworm** [comment]
@1bsyl I'm not @Starbuck5, but I just tried with the SDL 2.29.2 prerelease, and it seems to be working correctly now. The tests that were segfaulting before no longer do so with that prerelease. I've got a draft pull request up that's running through the entire test suite on all of our platforms, so when those all finish I can update this comment with any findings

**Comment by Starbuck5** [comment]
Thanks for the quick action @1bsyl, I've tested it and confirmed it works.

Thanks @oddbookworm for checking up on this too :)
