### ISSUE TITLE
testatomic clang-cl CI runs occasionally segfault

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#8905]
See e.g. the latest occurance of it:
https://github.com/sezero/SDL/actions/runs/7618767021/job/20750571996
```
 94% tests passed, 1 tests failed out of 17

Total Test time (real) =  20.22 sec

The following tests FAILED:
	  2 - testatomic (SEGFAULT)
```

This seems to happen in SDL2 branch. Haven't noticed in SDL3 (but I may
have very well missed it.)

**Comment by slouken** [comment]
Duplicate of https://github.com/libsdl-org/SDL/issues/8576

**Comment by sezero** [comment]
Ah, missed that ticket. Closing this one.
