### ISSUE TITLE
WinRT vs VectoredExceptionHandler

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8906]
This is coming up in the WinRT builds for SDL3...

```
D:\a\SDL\SDL\src\thread\windows\SDL_systhread.c(157,34): warning C4013: 'AddVectoredExceptionHandler' undefined; assuming extern returning int [D:\a\SDL\SDL\build\SDL\SDL3-static.vcxproj]
D:\a\SDL\SDL\src\thread\windows\SDL_systhread.c(157,32): warning C4047: '=': 'PVOID' differs in levels of indirection from 'int' [D:\a\SDL\SDL\build\SDL\SDL3-static.vcxproj]
D:\a\SDL\SDL\src\thread\windows\SDL_systhread.c(169,13): warning C4013: 'RemoveVectoredExceptionHandler' undefined; assuming extern returning int [D:\a\SDL\SDL\build\SDL\SDL3-static.vcxproj]
```

The thing still links, but I don't know if it will fail when you try to run it (or if this is supported and we just need an include somewhere).

Related: We really need a better way to know if compiler warnings are coming up on GitHub Actions; we currently only know about them when sifting through build logs, as far as I know.

**Comment by madebr** [comment]
Usually, warnings are treated as errors.
I think it's only WinRT and macos where warnings are let through.

**Comment by slouken** [comment]
Interestingly this builds with no warnings using Visual Studio 2019.

> I think it's only WinRT and macos where warnings are let through.

Android also, and we should probably change that, as it comes up with good warnings.

**Comment by icculus** [comment]
Then it's probably just an old SDK issue on GitHub Actions, and the function is actually supported.

**Comment by slouken** [comment]
Okay, I'll go ahead and close this for now.
