### ISSUE TITLE
macOS first keyboard input freezes app for 1 to 2 seconds

### ISSUE THREAD

**Issue by RGPaul** [libsdl-org/SDL#8928]
I tried SDL2 stable and current main branch.
On first key hit the app freezes for 1 till 2 seconds (not measured) and in the console I can see that some libraries are loading.
After that all seems fine.

Is it possible to preload the required libraries? Maybe I can add some compile flags?

**Comment by slouken** [comment]
What libraries are loading? Does this only happen in the debugger?

**Comment by RGPaul** [comment]
I will add Logs tomorrow and check release build.

**Comment by icculus** [comment]
I'm wondering if this is the same thing as #8839. Is this loading libraries from a non-SSD disk? I didn't see any lag on an M1 Mac Mini, but it's got a massively fast disk, and maybe that makes all the difference. I'm just guessing here.

**Comment by icculus** [comment]
(At any rate, if it's specifically stalling to load shared libraries, we can maybe take steps to force them to load sooner, but I'd need to know which ones are involved.)

**Comment by RGPaul** [comment]
I'm on a Macbook with M1 Max - I don't think it's an issue with a slow disk.

This are the lines before the game is running
`Loaded '/System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/TextInputUI.framework/Versions/A/TextInputUI'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/TextInputUIMacHelper.framework/Versions/A/TextInputUIMacHelper'. Symbols loaded.`

After klicking a keyboard key this is loading:
`Loaded '/System/Library/PrivateFrameworks/SystemAdministration.framework/Versions/A/SystemAdministration'. Symbols loaded.
Loaded '/System/Library/Frameworks/DirectoryService.framework/Versions/A/DirectoryService'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages'. Symbols loaded.
Loaded '/System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/LoginUIKit.framework/Versions/A/Frameworks/LoginUICore.framework/Versions/A/LoginUICore'. Symbols loaded.
Loaded '/usr/lib/libodfde.dylib'. Symbols loaded.
Loaded '/usr/lib/libcurl.4.dylib'. Symbols loaded.
Loaded '/usr/lib/libcrypto.46.dylib'. Symbols loaded.
Loaded '/usr/lib/libssl.48.dylib'. Symbols loaded.
Loaded '/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent'. Symbols loaded.
Loaded '/usr/lib/libsasl2.2.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SidecarUI.framework/Versions/A/SidecarUI'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/VoiceShortcutClient.framework/Versions/A/VoiceShortcutClient'. Symbols loaded.
Loaded '/System/Library/Frameworks/Intents.framework/Versions/A/Intents'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/CoreDuet.framework/Versions/A/CoreDuet'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/CoreDuetContext.framework/Versions/A/CoreDuetContext'. Symbols loaded.
Loaded '/System/Library/Frameworks/CoreSpotlight.framework/Versions/A/CoreSpotlight'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/IntentsFoundation.framework/Versions/A/IntentsFoundation'. Symbols loaded.
Loaded '/System/Library/Frameworks/AppIntents.framework/Versions/A/AppIntents'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/IntentsCore.framework/Versions/A/IntentsCore'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomePubSub.framework/Versions/A/BiomePubSub'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/LinkMetadata.framework/Versions/A/LinkMetadata'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftAccelerate.dylib'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftFileProvider.dylib'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftIntents.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/ApplePushService.framework/Versions/A/ApplePushService'. Symbols loaded.
Loaded '/System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/CoreDuetDaemonProtocol.framework/Versions/A/CoreDuetDaemonProtocol'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/ProactiveSupport.framework/Versions/A/ProactiveSupport'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Rapport.framework/Versions/A/Rapport'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeStorage.framework/Versions/A/BiomeStorage'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeFoundation.framework/Versions/A/BiomeFoundation'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/InternationalTextSearch.framework/Versions/A/InternationalTextSearch'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/CommonUtilities.framework/Versions/A/CommonUtilities'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom'. Symbols loaded.
Loaded '/usr/lib/libParallelCompression.dylib'. Symbols loaded.
Loaded '/usr/lib/libAppleArchive.dylib'. Symbols loaded.
Loaded '/System/Library/Frameworks/SharedWithYouCore.framework/Versions/A/SharedWithYouCore'. Symbols loaded.
Loaded '/usr/lib/libBASupport.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/AppleAccount.framework/Versions/A/AppleAccount'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/C2.framework/Versions/A/C2'. Symbols loaded.
Loaded '/System/Library/Frameworks/PushKit.framework/Versions/A/PushKit'. Symbols loaded.
Loaded '/System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/FeatureFlags.framework/Versions/A/FeatureFlags'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftAVFoundation.dylib'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftCoreMIDI.dylib'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftCoreMedia.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/IDS.framework/Versions/A/IDS'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/AppleIDSSOAuthentication.framework/Versions/A/AppleIDSSOAuthentication'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/IMFoundation.framework/Versions/A/IMFoundation'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Marco.framework/Versions/A/Marco'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/IDSFoundation.framework/Versions/A/IDSFoundation'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/FTServices.framework/Versions/A/FTServices'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Engram.framework/Versions/A/Engram'. Symbols loaded.
Loaded '/usr/lib/libtidy.A.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/FTAWD.framework/Versions/A/FTAWD'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/RTCReporting.framework/Versions/A/RTCReporting'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/CryptoKitCBridging.framework/Versions/A/CryptoKitCBridging'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftCryptoTokenKit.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/AssistantServices.framework/Versions/A/AssistantServices'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/DoNotDisturb.framework/Versions/A/DoNotDisturb'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeStreams.framework/Versions/A/BiomeStreams'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Koa.framework/Versions/A/Koa'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeSync.framework/Versions/A/BiomeSync'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeFlexibleStorage.framework/Versions/A/BiomeFlexibleStorage'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeDSL.framework/Versions/A/BiomeDSL'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeSequence.framework/Versions/A/BiomeSequence'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/InternalSwiftProtobuf.framework/Versions/A/InternalSwiftProtobuf'. Symbols loaded.
Loaded '/usr/lib/libskit.dylib'. Symbols loaded.
Loaded '/usr/lib/libmorphun.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/MorphunAssets.framework/Versions/A/MorphunAssets'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Trial.framework/Versions/A/Trial'. Symbols loaded.
Loaded '/usr/lib/libmarisa.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/EmbeddedAcousticRecognition.framework/Versions/A/EmbeddedAcousticRecognition'. Symbols loaded.
Loaded '/System/Library/Frameworks/CoreML.framework/Versions/A/CoreML'. Symbols loaded.
Loaded '/System/Library/Frameworks/NaturalLanguage.framework/Versions/A/NaturalLanguage'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/EmojiFoundation.framework/Versions/A/EmojiFoundation'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SDAPI.framework/Versions/A/SDAPI'. Symbols loaded.
Loaded '/System/Library/Frameworks/MLCompute.framework/Versions/A/MLCompute'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/MLAssetIO.framework/Versions/A/MLAssetIO'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Montreal.framework/Versions/A/Montreal'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/DifferentialPrivacy.framework/Versions/A/DifferentialPrivacy'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BiomeLibrary.framework/Versions/A/BiomeLibrary'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/UnifiedAssetFramework.framework/Versions/A/UnifiedAssetFramework'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SiriAnalytics.framework/Versions/A/SiriAnalytics'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SiriInstrumentation.framework/Versions/A/SiriInstrumentation'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/TrialProto.framework/Versions/A/TrialProto'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/FeedbackLogger.framework/Versions/A/FeedbackLogger'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/AtomicsInternal.framework/Versions/A/AtomicsInternal'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/AppleFlatBuffers.framework/Versions/A/AppleFlatBuffers'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/ProactiveEventTracker.framework/Versions/A/ProactiveEventTracker'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SAObjects.framework/Versions/A/SAObjects'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SiriTTSService.framework/Versions/A/SiriTTSService'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SiriCrossDeviceArbitrationFeedback.framework/Versions/A/SiriCrossDeviceArbitrationFeedback'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SiriCrossDeviceArbitration.framework/Versions/A/SiriCrossDeviceArbitration'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/MediaServices.framework/Versions/A/MediaServices'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/PersistentConnection.framework/Versions/A/PersistentConnection'. Symbols loaded.
Loaded '/usr/lib/libtailspin.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Osprey.framework/Versions/A/Osprey'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SiriTTS.framework/Versions/A/SiriTTS'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/GraphicsServices.framework/Versions/A/GraphicsServices'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SiriPowerInstrumentation.framework/Versions/A/SiriPowerInstrumentation'. Symbols loaded.
Loaded '/usr/lib/swift/libswiftNaturalLanguage.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/TailspinSymbolication.framework/Versions/A/TailspinSymbolication'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/Darwinup.framework/Versions/A/Darwinup'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SignpostSupport.framework/Versions/A/SignpostSupport'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/FeatureFlagsSupport.framework/Versions/A/FeatureFlagsSupport'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/ktrace.framework/Versions/A/ktrace'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SampleAnalysis.framework/Versions/A/SampleAnalysis'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/kperfdata.framework/Versions/A/kperfdata'. Symbols loaded.
Loaded '/usr/lib/libdscsym.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/BulkSymbolication.framework/Versions/A/BulkSymbolication'. Symbols loaded.
Loaded '/usr/lib/libedit.3.dylib'. Symbols loaded.`

After loading is done the game continues to work.

**Comment by RGPaul** [comment]
And I just tried with release build. It is not happening with release build. All is smooth with release. :)

**Comment by icculus** [comment]
That's kinda horrifying that so much is loading on the first keyboard press, but if a release build is fixing it, I guess we'll call this okay for now...?

**Comment by RGPaul** [comment]
Yeah it's not important if it's just in debug mode. Thanks :)
