### ISSUE TITLE
Accelerometer and Gryo values are swapped?

### ISSUE THREAD

**Issue by Socke81** [libsdl-org/SDL#8931]
Hi,
when I run the testgamecontroller.c and lay my PS5 gamepad flat on the table I get these values. 

```
INFO: Controller 0 sensor gyro: 0.01, -0.00, -0.00 (1335577948)
INFO: Controller 0 sensor accelerometer: 0.24, 9.53, 1.55 (1335577948)
```

When I turn the gamepad around with the buttons facing down, I get these values:

```
INFO: Controller 0 sensor gyro: 0.01, -0.00, -0.00 (1419985054)
INFO: Controller 0 sensor accelerometer: 0.21, -9.61, 2.39 (1419985054)
```

Isn't that wrong? Isn't the gyro sensor responsible for the position instead of the accelerometer?

Version 2.29.0.0

**Comment by slouken** [comment]
No, the accelerometer is what measures gravity. The gyro measures rotation but only while in motion.
