### ISSUE TITLE
SDL3, xboxgip prevents detection of xbox controller types

### ISSUE THREAD

**Issue by isXander** [libsdl-org/SDL#8972]
I own an Xbox Elite Controller Series 2. When testing it out with `testcontroller.c` test, the PID shows as `0x02ff`, which referencing the code, matches the Xbox GIP driver controller.

This then prevents the back paddles from being detected, as well as the LED light.

My question is:
- Can SDL bypass xboxgip so users don't run into the issue
- Failing that, how can I prevent xboxgip from abstracting my controller

**Comment by slouken** [comment]
> * Can SDL bypass xboxgip so users don't run into the issue

No, this can only be done with a custom driver.

> * Failing that, how can I prevent xboxgip from abstracting my controller

You can't, it's built into the Windows controller driver stack.

**Comment by isXander** [comment]
So there is no planned way to support the extra Xbox inputs like back paddles and share button on Windows?

**Comment by slouken** [comment]
There is no way to do it. They are not exposed in any public API that I'm aware of.

**Comment by Squall-Leonhart** [comment]
These controls are available by WGI i thought?

**Comment by isXander** [comment]
> These controls are available by WGI i thought?

Doesn't look like it

https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/input/gameinput/enums/gameinputgamepadbuttons#syntax

**Comment by Squall-Leonhart** [comment]
Thats the public info, theres privage info only available to XDK members.

**Comment by slouken** [comment]
> These controls are available by WGI i thought?

Not as far as I know. Please let me know if I'm wrong though!
