### ISSUE TITLE
SDL3, POPUP windows. mouse captured by wrong window. 

### ISSUE THREAD

**Issue by c-smile** [libsdl-org/SDL#8974]
When popup window is shown without setting keyboard focus on it, [SDL_UpdateMouseCapture](https://github.com/libsdl-org/SDL/blob/7c089f4e570b7849c7af3d406ee2b4e39aa23435/src/events/SDL_mouse.c#L1166) sets capture to wrong window - not to the popup window as it should.

This leads to mouse handling problems on popups. For example SDL_EVENT_MOUSE_BUTTON_UP is not delivered to the popup.

I suspect that this line 
```
capture_window = SDL_GetKeyboardFocus();
```
shall be replaced by 
```
capture_window = mouse->focus;
```
`keyboard focus` window is not always the one that contains the mouse.

Think about popup window of combobox (dropdown select), or a menu. Such popups do not have input (keyboard) focus.

**Comment by slouken** [comment]
You're right, this is fixed, thanks!
