### ISSUE TITLE
SDL3, No HID devices found in the system, Windows

### ISSUE THREAD

**Issue by isXander** [libsdl-org/SDL#8975]
When enabling only the HIDAPI, controllers are not detected because HIDAPI does not find any connected devices.
Tried with both an Xbox Elite Series 2 Controller (BLE) and a Dualshock 4 Controller (to get around any dumb windows stuff) and both are not detected.

**Comment by slouken** [comment]
Are you able to debug and see what's happening? I'm not seeing that here. The Xbox controller doesn't show up (as expected, because Windows uses the USB GIP driver for this), but the DualShock 4 controller shows up just fine.

**Comment by slouken** [comment]
No response, I'll go ahead and close this.
