### ISSUE TITLE
SDL3, `SDL_GetJoystickGUIDString` segfaults on Steam Deck

### ISSUE THREAD

**Issue by isXander** [libsdl-org/SDL#8978]
Testers of my mod have found that this function causes a segfault on the Steam Deck.

I am running SDL through Java using JNA, https://github.com/isXander/libsdl4j/tree/SDL3.
The value of `SDL_GetJoystickInstanceGUID` is `00000001-0000-11ff-0000-28def6790003`, when printed directly through JNA.

**Comment by slouken** [comment]
That sounds like a JNI interop problem. That function fills in memory that needs to be allocated and managed by the caller.

**Comment by isXander** [comment]
> That sounds like a JNI interop problem. That function fills in memory that needs to be allocated and managed by the caller.

I allocate 33 bytes of memory just like the function says to.
I also tried just giving it 256 bytes and still the error occurred.

**Comment by isXander** [comment]
Note this works compeletely fine for my Xbox controller, it is only on SteamDeck that this is an issue.

**Comment by slouken** [comment]
Can you catch this in the debugger and see what's happening?

**Comment by madebr** [comment]
Where do the `-` come from?
SDL's `SDL_GetJoystickInstanceGUID` (`SDL_GUIDToString`) [does not emit dashes](https://github.com/libsdl-org/SDL/blob/ab571633d1207dcf63624b8e00f366fd44cfc8b1/src/SDL_guid.c#L23-L46).

**Comment by isXander** [comment]
> Where do the `-` come from? SDL's `SDL_GetJoystickInstanceGUID` (`SDL_GUIDToString`) [does not emit dashes](https://github.com/libsdl-org/SDL/blob/ab571633d1207dcf63624b8e00f366fd44cfc8b1/src/SDL_guid.c#L23-L46).

I used Java to convert it into a UUID using the least significant bits and most significant bits (since SDL is not working)

**Comment by isXander** [comment]
> Can you catch this in the debugger and see what's happening?

Unfortunately I wouldn't have a clue how to do this :/

Working with C is very new to me so I can try and emulate the call on my machine but no promises
