### ISSUE TITLE
Environment variable for choosing renderer backend

### ISSUE THREAD

**Issue by sim1cent** [libsdl-org/SDL#8985]
Hello.
It would be neat to have an env var to specify a desired SDL renderer backend for testing purposes, rather than giving an hint to SDL baked in the binary.
It may already exist but as far as i can tell i couldn't find any.

**Comment by sim1cent** [comment]
I would do a pull request myself, as a matter of fact i tried but i think my patch wouldn't be valuable since im not familiar with SDL coding standards

**Comment by slouken** [comment]
All of the hints can be set as environment variables:
https://github.com/libsdl-org/SDL/blob/a29f37c14abc2ae418e770353657e872a70d90b8/include/SDL_hints.h#L1644
e.g. `SDL_RENDER_DRIVER=opengl`
