### ISSUE TITLE
testcontroller segfaults on exit

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8986]
On my Windows machine, running testcontroller segfaults when closing the app.
```
 	[External Code]	
 	d3d11_3SDKLayers.dll!ReportCorruption(unsigned int,enum D3D11_MESSAGE_ID,char const *,...)	Unknown
 	d3d11_3SDKLayers.dll!CLayeredObject<class NDebug::CBlendState>::CContainedObject::Release(void)	Unknown
>	SDL3.dll!D3D11_ReleaseAll(SDL_Renderer * renderer) Line 306	C
 	SDL3.dll!D3D11_DestroyRenderer(SDL_Renderer * renderer) Line 346	C
 	SDL3.dll!SDL_DestroyRenderer_REAL(SDL_Renderer * renderer) Line 4356	C
 	SDL3.dll!SDL_DestroyRenderer(SDL_Renderer * a) Line 172	C
 	testcontroller.exe!SDL_main(int argc, char * * argv) Line 2131	C
 	SDL3.dll!SDL_RunApp_REAL(int _argc, char * * _argv, int(*)(int, char * *) mainFunction, void * reserved) Line 453	C
 	SDL3.dll!SDL_RunApp_DEFAULT(int a, char * * b, int(*)(int, char * *) c, void * d) Line 586	C
 	SDL3.dll!SDL_RunApp(int a, char * * b, int(*)(int, char * *) c, void * d) Line 586	C
 	testcontroller.exe!main(int argc, char * * argv) Line 97	C
 	[External Code]	
```
This location:
https://github.com/libsdl-org/SDL/blob/ab571633d1207dcf63624b8e00f366fd44cfc8b1/src/render/direct3d11/SDL_render_d3d11.c#L306

I bisected the first bad commit back to 9591b2cfb4454f7aab7a3b93337a816abb2c84ee.

@slouken

**Comment by slouken** [comment]
Are you getting any debug output? I accidentally turned that on, and it might be causing the issue, but more likely would have good diagnostic output.

**Comment by madebr** [comment]
No, the output widget of Visual Studio was only printing things about loading the debug symbols + the strings printed by testcontroller.
Nothing extra.

7271a2040b6bfec261bf1160422d7cc2f9e7c2cc fixes the crash. Thanks!

**Comment by slouken** [comment]
That was actually a legitimate issue, fixed in https://github.com/libsdl-org/SDL/commit/2ad4646a2488a435ac54b3b342d03b92302b3058.

Thanks!
