### ISSUE TITLE
Question: Can you add at least one unit test checker with all SIMD disabled?

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#8994]
Hello!

Recently, [I fixed one of bugs](https://github.com/libsdl-org/SDL/pull/8982) that was found on platforms where SIMD is unavailable completely (also, the 3DS platform is totally lacks any suitable SIMD, and 3DS users also noted about crashes during the audio playback). And so, me and my friends discussed to figure, why these bugs gets introduced sometimes. And so, we got a think that you don't test SIMD-disabled builds. What if add some CI tests to verify the same stuff but with SIMD disabled? Just, because you do have many variants of similar functions, including SIMD-powered and universal, it's need to test all of these variants I think.

**Comment by madebr** [comment]
I think it would be useful for SDL, at initialization, to allow disabling extensions using e.g. hints.
Such that you can run e.g. `SDL_CPU_SSE2=0 ./testautomation`, or something general.
Having the possibility to enable and/or disable certain extensions could be useful for performance comparisons.

**Comment by slouken** [comment]
@madebr, can we add running some specific tests that would exercise the SIMD code paths to CI, with the environment variable you added?

**Comment by madebr** [comment]
This has been added in 89b135e570e3d8ab81e48d73971088b0e68e4e9a

ci runs `testautomation` and `testautomation-no-simd`.
The latter sets the environment variable `SDL_CPU_FEATURE_MASK=-all`
