### ISSUE TITLE
X11 window don't keep fullscreen state after being minimized

### ISSUE THREAD

**Issue by meyraud705** [libsdl-org/SDL#9003]
On X11, an exclusive fullscreen window becomes windowed if you minimize it.

You can reproduce with `testwm`:
 - Ctrl-Enter toggle fullscreen
 - Ctrl-Z to minimize

Fullscreen desktop mode (Alt-enter in `testwm`) works correctly.
This affect alt-tab because window is minimized during switching.

You can call `SDL_SetWindowFullscreen(window, SDL_TRUE);` on `SDL_EVENT_WINDOW_RESTORED` as a workaround.

First bad commit is 4fd778119b85626d06e74dbc38c56881a0cd1508.

**Comment by slouken** [comment]
Can you provide more information about your environment? I'm not able to reproduce this on Ubuntu 22.04 running GNOME.

**Comment by meyraud705** [comment]
I am using KDE  on openSUSE Tumbleweed:
 - KDE plasma 5.27.10
 - KDE Frameworks 5.115.0
 - X.org 21.1.11
 - Mesa 23.3.6

**Comment by slouken** [comment]
Is this SDL2 or SDL3?

**Comment by meyraud705** [comment]
SDL3

**Comment by Kontrabant** [comment]
I can reproduce this with the window int both fullscreen and maximized.  KDE is sending unmap/map events when the window is minimized and restored causing hidden and shown events, which causes the window flags to be reset in the OnWindowShown event handler.

I think we need to save the fullscreen and maximized flags as the window pending_flags when the window manager unmaps a window, so they will be restored if restoring the window causes a shown event to be dispatched.
