### ISSUE TITLE
Crash in SDL 2.30 with wayland backend when rotating mobile device

### ISSUE THREAD

**Issue by mlehtima** [libsdl-org/SDL#9010]
At least in 2.30 the commit https://github.com/libsdl-org/SDL/commit/0ec1209eab437ebf49506f1649199f0aec9c54cb introduced a regression in linux when using wayland backend on devices with support for rotating the display (Sailfish OS, using a slightly patched SDL to bring back wl_shell support). In wayland the driverdata is the wl_output and releasing it is not a good idea at least if rotating device is supported. Valgrind output is here
[sdl_2.30_valgrind.txt](https://github.com/libsdl-org/SDL/files/14185573/sdl_2.30_valgrind.txt)

**Comment by Kontrabant** [comment]
Backported and fixed.
