### ISSUE TITLE
Wayland:  SDL2.28.5 crashes itermitantly due to nullptr in wayland keyboard handling.

### ISSUE THREAD

**Issue by kuroneko** [libsdl-org/SDL#9022]
This is not a consistently reproducable bug unfortunately, but I've managed to analyse the cause sufficiently.

On some of our embedded wayland targets, it is possible for the keyboard modifier handler to be called before a keymap is established via the keymap handler.

As there's no keymap was received, then the xkb state is NULL, and that's fed, unguarded, into xkb functions (which then SEGVs).

SDL needs to correctly guard the use of the xkb functions in these handlers to not run before the xkb.state is allocated.

In 2.28.5, the offending call is in `src/video/wayland/SDL_waylandevents.c:1259` (`keyboard_handle_modifiers`) - there may be others.

It's probably also important to note that these systems are operating with no keyboard, so there may never be a valid keymap!  SDL needs to survive this particular oddity!

**Comment by slouken** [comment]
@Kontrabant, is this still active in 2.x?

**Comment by Kontrabant** [comment]
The fix was already cherry-picked, so it should be fine now.
