### ISSUE TITLE
Issues Creating a transparent click through window.

### ISSUE THREAD

**Issue by MrCoInSanity** [libsdl-org/SDL#9024]
Hello, I'm looking to make an overlay in SDL3.

I started by making the transparent window like this:

```

bool CreateTransparentWindow()
{
	if (SDL_Init(SDL_INIT_VIDEO) < 0) {
		return false;
	}
	
	window = SDL_CreateWindow("About", 1920, 1080, SDL_WINDOW_TRANSPARENT | SDL_WINDOW_BORDERLESS | SDL_WINDOW_ALWAYS_ON_TOP);
	renderer = SDL_CreateRenderer(window, NULL, SDL_RENDERER_ACCELERATED);
	if (window == NULL) {
		blog(LOG_ERROR, "Creation Failed for: %s", SDL_GetError());
		return false;
	}

	font = TTF_OpenFont("C:\\Users\\Joel\\Desktop\\Roboto-Regular.ttf", 18);
	if (!font) {
		blog(LOG_ERROR, "Font loading failed: %s", TTF_GetError());
		return false;
	}
	SDL_SetRenderDrawColor(renderer, 0, 0, 0, 0);
	SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

	return true;
}
```

The above code makes a black window appear, but whats strange is when I remove the renderer aspect and just leave the window creation, it creates a transparent window correctly.

I should also note that this my is update loop (for testing)

```
while (1) {

		SDL_RenderClear(renderer);
		SDL_SetRenderDrawColor(renderer, 0, 0, 0, 0);
		SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

		// Present the renderer
		SDL_RenderPresent(renderer);
		SDL_PumpEvents(); // Process pending events
		}
```

I'd also be greatful if you told me how to allow click through on the window if possible directly using SDL3 library.

**Comment by slouken** [comment]
The issue is that D3D12 doesn't work with transparent windows and that's the default renderer. Try the latest code, it should fall back to D3D11 for transparent windows.

Clickthrough may work if you use the hittest functionality of SDL, but I haven't tried that myself. Let us know if you get that working?

**Comment by MrCoInSanity** [comment]
Even trying the latest build, I still run into this issue.

**Comment by frauber84** [comment]
> Thank you! that solved the issue!

Did you get the ClickThrough to work properly?
