### ISSUE TITLE
Steam Generic Controller not working with sdl2 2.30.0

### ISSUE THREAD

**Issue by 5hayanB** [libsdl-org/SDL#9025]
Just updated my arch btw, and found out that non-steam games are not receiving controller inputs. The controller itself is being recognized and inputs work in big picture mode as well, but as soon as the game launches, no inputs are received and have to use the keyboard. I then downgraded `sdl2 2.30.0` to `sdl2 2.28.5` and now the controller works flawlessly. What might be the bug?

**Comment by slouken** [comment]
I'm not sure. Can you provide full repro steps, e.g. what game you're using, what controller you're using, etc.?

**Comment by 5hayanB** [comment]
Steps to reproduce:

- Update to SDL2 2.30.0
- Open Steam and go to Library
- Make sure to have your controller connected. I use a Google Stadia controller.
- Make sure the controller is responsive. Go to controller layout and test your controller.
- Launch a controller supported game. Any game which supports a controller will do.
- No input is received in the game.

One thing to note is that Steam, in Big Picture Mode, shows the keyboard and mouse indicator on the game banners, even though they support controller inputs and navigation is done through controllers in Big Picture Mode.

What else can I provide?

**Comment by slouken** [comment]
Can you provide a specific game that's having the issue?

**Comment by slouken** [comment]
I tried Assault Android Cactus and replaced SDL2 in the x86_64 directory with a symlink to a locally built SDL 2.30.0 and it works fine here... ?

I tested with Steam Input for generic controllers both enabled and disabled and it worked fine both ways.

**Comment by 5hayanB** [comment]
> Can you provide a specific game that's having the issue?

- Attack on Titan
- Attack on Titan 2
- Dragon Ball FighterZ
- Dragon Ball Z Kakarot

I will try locally building SDL 2.30.0 and try again.
