### ISSUE TITLE
Allowing Click Through On SDL3 Window

### ISSUE THREAD

**Issue by MrCoInSanity** [libsdl-org/SDL#9028]
Hey, I would firstly like to thank you for making such a nice library. I'm trying to achieve click through and you recommended using SDL_EVENT_WINDOW_HIT_TEST. I really don't know how I would use that to achieve what I want. But, I did in-fact get it working in SDL2. But I cannot get it working in SDL3.

In SDL2, I was simply doing the following

```
HWND hwnd = GetActiveWindow();
SetWindowLong(hwnd, GWL_EXSTYLE, GetWindowLong(hwnd, GWL_EXSTYLE) | WS_EX_LAYERED | WS_EX_NOACTIVATE);
```

In SDL3, this does not effect the window from what I can see, I would be greatful if you gave me some more suggestions or even in-site to using SDL_EVENT_WINDOW_HIT_TEST or other recommendations.

Thanks in advance!

**Comment by MrCoInSanity** [comment]
Managed to get it working, the problem was I was getting the current window **AFTER** creating both the renderer and window, if you simply move the above code before making the renderer, it works.

**Comment by MrCoInSanity** [comment]
Managed to get it working, the problem was I was getting the current window **AFTER** creating both the renderer and window, if you simply move the above code before making the renderer, it works.

**Comment by slouken** [comment]
FYI, I added the function SDL_SetWindowShape() that takes care of this for you, and works on Windows, macOS and X11.
