### ISSUE TITLE
Shaped windows, revisited

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9032]
So transparent windows works great for graphics, but we still have the problem of making the window transparent to mouse clicks.

On macOS, this is easy, and already works.
On Windows, you can return HTTRANSPARENT from the hit test callback, and I have a prototype patch that implements that.
On X11 you still need to use the XShape extension which takes a bitmap or set of regions
On Wayland, you can't do this at all (is that right @Kontrabant?)

@libsdl-org/a-team, suggestions?

**Comment by icculus** [comment]
Hmmm, I hadn't thought about that.  :/ 

How badly do we still want this, vs just having alpha-blendable windows?

**Comment by slouken** [comment]
It's actually looking pretty good! This works way better than SDL2's attempt. :)
