### ISSUE TITLE
Rename `SDL_HasWindowSurface` => `SDL_WindowHasSurface`

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#9034]
This is the only SDL3 function that starts with `SDL_Has` and does not operate on global state.
So I propose to rename it to `SDL_WindowHasSurface`.

https://github.com/libsdl-org/SDL/blob/1143bdc35130e68c90c9b1a3a2069399b7f6143a/include/SDL3/SDL_video.h#L1687-L1698

What do you think? Or is this naming intentional.

(My apologies for this bike shed)

**Comment by slouken** [comment]
Nope, this name change sounds good. You can use rename_api.py to help with that.
