### ISSUE TITLE
E1696: couldn't open source file "GLES/gl.h", "GLES/glext.h"

### ISSUE THREAD

**Issue by 0Q1BE** [libsdl-org/SDL#9040]
### Introduce
I wanted to start making games with SDL (and this was first time I downloaded custom library)
But I couldn't find any guide because of irrelevance or guider's speech sounding like "alidebodeowode"
So I used to go through all the options and... At first I used to build the library, BUT every time I rebuild it says SDL.dll is broken and unlaunchable. Then I barely found new (6 months ago) guide with understandable speech and did everything as said in the video
**and then I've met this problem.**

### The problem
I've copied include and library files into my visual studio project file and included every single header file to make this fricking SDL work but when I launched my file visual studio said like "bro, I can't open this sh...(uh i mean very nice project) because there's a `E1696` issue."
The problem is in `SDL_opengles.h` which includes `<GLES/gl.h>` and `<GLES/glext.h>` (I don't have GLES in my directory), but if i don't include `SDL_opengles.h`, visual studio can't define `SDL_Quit();`, `SDL_CreateWindow();` etc.

**I don't know where to search help so I post this issue. Please help me.**

**Comment by icculus** [comment]
> and included every single header file

Just include SDL.h

(And maybe SDL_main.h)

Look at the files in the "test" directory for examples of working SDL programs.

**Comment by 0Q1BE** [comment]
> Just include `SDL.h`
If I include only `SDL.h` (and `SDL_main.h`) there will be a LNK2019 issue. Nice!
> Look at the files in the "test" directory for examples of working SDL programs.
I've tried to build and it said "nah i won't work"

**Comment by icculus** [comment]
You probably need to add the .lib files to your build. The `#include` lines tell the C compiler how to use SDL, but you still need to link your program to SDL, too.

https://stackoverflow.com/questions/19886397/how-can-i-solve-the-error-lnk2019-unresolved-external-symbol-function

I'd encourage you to ask these questions on [our forums](https://discourse.libsdl.org/), as we use the issue tracker for bug reports.
