### ISSUE TITLE
SDL3: Recent changes to SDL_render_d3d.c don't respect `SDL_LEAN_AND_MEAN`

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9054]
Latest source doesn't compile with `SDL_LEAN_AND_MEAN` preprocessor define.
```
SDL\src\render\direct3d\SDL_render_d3d.c(1002,36): error C2039: 'shaders': is not a member of 'D3D_RenderData'
SDL\src\render\direct3d\SDL_render_d3d.c(1002,36): error C2198: 'function through pointer': too few arguments for call
```

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by fdwr** [comment]
Thanks Sam.

\<ignorable\>I'm updating an old 2005 app (when SDL.dll was 232KB!) to SDL2 and noticed it grew 10x to 2MBs. So this SDL_LEAN_AND_MEAN and [SDL_internal.h](https://github.com/libsdl-org/SDL/blob/main/src/SDL_internal.h#L135-L195) look promising for me to do silly things like fit it on a 3.25 floppy again :b 💾☑️.\</ignorable\>

**Comment by AntTheAlchemist** [comment]
@fdwr I'd also like to push-back against the growing KB size of SDL because it is starting to grow in size exponentially now. It was being able to pack a lot of power into a tiny size 😊 , and size makes a big difference when deploying an app to Android. 

There are other pre-compiler defines: SDL_AUDIO_DISABLED, SDL_JOYSTICK_DISABLED, SDL_HAPTIC_DISABLED,  SDL_SENSOR_DISABLED, SDL_CAMERA_DISABLED, SDL_CPUINFO_DISABLED, SDL_POWER_DISABLED, but they don't make much difference.

How about WIN32_LEAN_AND_MEAN?

The internals containing unused code is also an issue when it comes to virus scanners. SDL related binaries often trigger false positives due to the vast number of features packed in, and interestingly enough, sending emails is often one of the triggers identified with VirusTotal. 

Should we open an issue to see if there's something we can do about any of this?

**Comment by slouken** [comment]
These are the top two objects, which really surprises me since there's not a lot of code in them:
```
-rwxrwxr-x+ 1 saml Domain Users   790312 Mar  6 08:41 SDL_rawinputjoystick.obj
-rwxrwxr-x+ 1 saml Domain Users   782128 Mar  6 08:41 SDL_windows_gaming_input.obj
```

**Comment by slouken** [comment]
But yes, opening a new issue to discuss size reduction is a good idea.
