### ISSUE TITLE
macOS - regression in exclusive fullscreen, SDL_GetWindowSize returning (0,0)

### ISSUE THREAD

**Issue by danginsburg** [libsdl-org/SDL#9061]
I have been looking into a problem users have been facing with the latest Dota 2 update on macOS https://github.com/ValveSoftware/Dota-2/issues/2655 and have bisected it to commit 4fd778119b85626d06e74dbc38c56881a0cd1508 @Kontrabant.  The problem that's occuring is the following:

1. When the game enters Exclusive Fullscreen it gets an `SDL_EVENT_WINDOW_RESTORED` event.
2. The game then calls `SDL_GetWindowSize` and this returns a size of (0, 0)
3. The game stops rendering because the code early-outs based on having a (0, 0) window size.

I have reproduced this on Macbook Air M1, 2020 on macOS Sonoma 14.3.  This behavior does not occur on the previous commit ace385a134b3675164fa1e3229e28855e0922d1b and is still happening at tip-of-tree.

**Comment by slouken** [comment]
Are you able to repro with an SDL test program, or modify one to show the issue?

**Comment by danginsburg** [comment]
The following local hack works around the issue for me: 

```
diff --git a/src/video/cocoa/SDL_cocoawindow.m b/src/video/cocoa/SDL_cocoawindow.m
index df1e39221..7a1cfc3e0 100644
--- a/src/video/cocoa/SDL_cocoawindow.m
+++ b/src/video/cocoa/SDL_cocoawindow.m
@@ -1142,7 +1142,14 @@ static SDL_bool Cocoa_IsZoomed(SDL_Window *window)
         /* Force a resize event when the backing scale factor changes. */
         _data.window->w = 0;
         _data.window->h = 0;
+        
+        SDL_bool b_prevInModeTransition = b_inModeTransition;
+        if (b_inModeTransition)
+        {
+            b_inModeTransition = SDL_FALSE;
+        }
         [self windowDidResize:aNotification];
+        b_inModeTransition = b_prevInModeTransition;
     }
 }
```

What seems to be happening is that `Cocoa_SetDisplayMode` set the global variable `b_inModeTransition` to TRUE, then the backing scale code above runs in `windowDidChangeBackingProperties`, then the `windowDidResize` call in it doesn't actually do the resize because of that global being set.  So my hack workaround saves and restores that global variable...but, yuck...there must be a better way to fix this.

**Comment by Kontrabant** [comment]
Hmm, I'm wondering if we actually still need the window width/height = 0 hack at all anymore?  It was needed in SDL2 to hack around the deduplication code in the window event dispatch handler, but in SDL3, even if a resize event is dispatched with dimensions that match the current logical window size, the higher level window event code will still check if the window pixel size has changed and send the appropriate event.

**Comment by Kontrabant** [comment]
Yep, tested it out, and I think we can just get rid of that dedup-short-circuit hack altogether, as dragging a window between two displays with different scale factors still sends the appropriate pixel size and display scale changed events. Will have it ready shortly.
