### ISSUE TITLE
SDL3 Possible fault in `#if defined` logic in SDL_memcpy.c & SDL_memset.c after disabling c runtimes. Low-priority

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9064]
SDL_build_config_windows.h has a `#define HAVE_LIBC` which can be removed to enable SDLs C functions. But it causes unresolved external symbol _memset, _memove, _memcpy. Happened since 5e70ee2

**Comment by Dv-Senna** [comment]
The changes introduced in yesterday commit break SDL for me.
I compile SDL using gcc (mingw) on a Windows 11 machine. The memcpy, memmove and memset functions just become infinite recursion loop with the default CMake configuration.
