### ISSUE TITLE
Using SDL_SetWindowFullscreen() causes havoc

### ISSUE THREAD

**Issue by CorruptVoidSoul** [libsdl-org/SDL#9065]
I have a 640x480 for my app and depending on the platform weird things happen.

On the Xfce desktop environment installed on Termux (android) it resizes the desktop to 640x480 and I have to change it back manually.

On Windows, it resizes background windows.

Anyone knows any workaround to avoid this ?

Also small precision it can't be used to extend the desktop, I tried. The weirdest thing is that the function never fails whatsoever.

**Comment by slouken** [comment]
You should probably use fullscreen desktop mode, which will not change the resolution. If you do that you'll need to set a logical size if you're using the SDL render API.

**Comment by CorruptVoidSoul** [comment]
I did the logical size strategy, now it works properly so thanks, and I'll see if the resizing tabs bug on Windows is still there tomorrow because I can't use a computer now.

**Comment by CorruptVoidSoul** [comment]
Tested it on Windows as well, everything works correctly.
Noice 👌
