### ISSUE TITLE
SDL3 excessive internal calls to `SDL_SetError("Couldn't find property named %s", name);`

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9067]
Since the introduction of properties, a successful call to `SDL_CreateWindow` now calls `SDL_SetError` a total of 24 times (on Windows).  `SDL_CreateRenderer` calls it 4 times, and `SDL_SetError` is called every time `SDL_CreateTexture` is used. There may be more, but they're the ones I've observed.

This seems excessive overhead; is there a better way of doing this? Do the get property methods really need to set an error if they default?

I know `SDL_GetError` shouldn't be used for error-checking, but that's actually the only way to error-check the get property methods.

**Comment by slouken** [comment]
Good point, those functions don't need to set an error.
