### ISSUE TITLE
Launching game on wayland mode causes window to be misplaced 

### ISSUE THREAD

**Issue by coronavirus6045** [libsdl-org/SDL#9069]
Games using sdl, when ran in wayland, gets placed at the wrong position
Is it a problem with wayland, or kde or sdl?
![image](https://github.com/libsdl-org/SDL/assets/140826405/3944edc7-cc9a-4d24-82ae-264341015bd8)

**Comment by Kontrabant** [comment]
Wayland window positioning is 100% done by the compositor (there is no API for setting/getting the window position at all). Neither SDL nor client applications have any control over it.
