### ISSUE TITLE
SDL_GameControllerGetAppleSFSymbolsNameForButton() now returns empty string, not NULL

### ISSUE THREAD

**Issue by willco007** [libsdl-org/SDL#9071]
On macOS Sonoma, after upgrading to SDL2 2.3, from 2.0.18, the API `SDL_GameControllerGetAppleSFSymbolsNameForButton()` now returns an empty string if the name is not found. The docs say it will return `NULL` and it used to return `NULL` in 2.0.18.  This appears to be a regression at some point after 2.0.18.

**Comment by sezero** [comment]
I guess the same thing is needed for `SDL_GameControllerGetAppleSFSymbolsNameForAxis`
