### ISSUE TITLE
Installing SDL on Mac OS 

### ISSUE THREAD

**Issue by nicholas-galea** [libsdl-org/SDL#9073]
I have a 2020 M1 Macbook Air running macOS Sonoma Version 14.2.1. I have been trying to install SDL for my University project and I am struggling with finding the SDL2/SDL2.h file.

main.cpp:1:10: fatal error: 'SDL2/SDL.h' file not found

I have also tried each package that are attached with the releases to exhaust all options.

My last solution is that maybe it is my OS has not yet had a SDL for it (surely not). Could someone kindly guide me to which SDL release could I install.

Thanks in advance :)

**Comment by madebr** [comment]
I think you need [Homebrew "The Missing Package Manager for macOS (or Linux)"](https://brew.sh).
It has a [sdl2 package](https://formulae.brew.sh/formula/sdl2#default).

**Comment by nicholas-galea** [comment]
I used brew to install it.

Precisely this command in the terminal:
brew install sdl2 

The installation seems to be fine (partially). I believe that the issue is that the folder for the headers that the compilation is requiring is not being installed and i have no idea why.

Thanks for your help :)

**Comment by madebr** [comment]
The issue with brew is that it does not install libraries and headers in the search path of your toolchain.
You need to pass extra flags (`-I` or `-L`) to add these.

Let's consider a minimal SDL2 c source `test.c`:
```c
#include "SDL.h"
int main(int argc, char *argv[]) {
  SDL_Init(0);
  SDL_Quit();
  return 0;
}
```
Which of the following commands work?
- `cc $(pkg-config --libs --cflags sdl2) test.c`
- `cc $(sdl2-config --libs) $(sdl2-config --cflags) test.c`
