### ISSUE TITLE
[sdl3,cmake] `SDL3_INCLUDE_DIRS` does not only contain `/usr/include`

### ISSUE THREAD

**Issue by akallabeth** [libsdl-org/SDL#9084]
when using `SDL3` the include paths are just the `/usr/include` whereas with `SDL2` the paths are `/usr/include/SDL2`
so all `#include <SDL.h>` need to be replaced with `#include <SDL3/SDL.h>`

same is true for `SDL-ttf` and `SDL-image`

is this intentional or by mistake?

**Comment by slouken** [comment]
This is intentional. With SDL3, you should prefix the include with SDL3, e.g. `#include <SDL3_image/SDL_image.h>`. This allows includes to work with macOS frameworks with no changes.
