### ISSUE TITLE
SDL3 & Windows: Duplicate Xbox One S controller on USB

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9091]
Might be caused by the recent GameInput code. Doesn't happen via Bluetooth, only by plugging in an Xbox One S controller via USB. I get two game controllers added: 

One called "Xbox One Game Controller" with GUID 03004d6e5e040000ea02000000007701
Another called "Xbox One Controller" with GUID 0300938d5e040000ff02000000007200

Hopefully an obvious fix.

**Comment by AntTheAlchemist** [comment]
Only happens when hot-plugging. Doesn't happen if already wired when application stars.

**Comment by slouken** [comment]
I'll try to repro. One of those is from raw input and one is from WGI.

**Comment by slouken** [comment]
Fixed, thanks!
