### ISSUE TITLE
SDL3 direct3d12 blank screen on "Intel(R) HD Graphics"

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9093]
SDL3 was working on my old test notebook until recently. `SDL_RenderClear` works, setting the correct draw colour, but all other drawing operations case a "[direct3d12] Unable to create required pipeline state" error and draw nothing. direct3d11 and other renderers work no problem. direct3d12 is chosen by default on this notebook when passing null as a driver name.

**Comment by AntTheAlchemist** [comment]
"D3D12_CreatePipelineState, lD3D12Device:CreateGraphicsPipelineState: Unspecified error"

`#if 1` didn't seem to make a difference.

I'm digging a bit deeper, unfortunately remote debugger won't install on offending machine 😢 . 

Even though no drawing methods worked, I noticed `SDL_CreateTextureFromSurface` produces the following error: "[pd3d12] Cannot allocate more than 16384 textures!", probably because SDL_INIT_VIDEO has already silently failed?

**Comment by AntTheAlchemist** [comment]
@slouken I got remote debugging working. `SDL_RenderPresent` is silently failing. It fails in `D3D12_CreatePipelineState`. `D3D_CALL` returns `E_FAIL`. 

What else should I be looking out for? `SDL_SetRenderDrawBlendMode` doesn't make a difference. SDL3 used to work on this laptop / tablet thing until recently. I remember that one of the renderers had an odd blending glitch on this device.

**Comment by slouken** [comment]
If you set `#if 1`, does the initial pipeline state creation also fail?

**Comment by AntTheAlchemist** [comment]
> If you set `#if 1`, does the initial pipeline state creation also fail?

Yes, it fails on the first one and does the `goto done`.

**Comment by AntTheAlchemist** [comment]
I removed `goto done` and every iteration of `D3D12_CreatePipelineState` failed. I get the feeling the renderer hasn't been created properly at this point. Something about this hardware the new HDR code doesn't like? (clutching at straws here)

**Comment by slouken** [comment]
The HDR code doesn't do anything new, just queries the characteristics of the display. Are you able to git bisect to find out where it broke?

**Comment by AntTheAlchemist** [comment]
I believe it's f1c3d3b

So, direct3D12 has apparently never worked on this device, at least not since Jan 2023, but it wasn't being chosen first by default. 

If I go back in history and continue to bisect, it's possible that i'll never find a version where direct3D12 - I don't think I've tried it before the `render_drivers` order changed.

What should we do? Might this be happening on all Intel HD devices? (I have a Dell Optiplex in the attic I can try). 

Can we get `SDL_CreateRenderer` to fail, instead of choosing a renderer that doesn't work?

**Comment by slouken** [comment]
Yes, we shouldn't use the renderer if it can't create pipeline state. Fixed, thanks!

**Comment by slouken** [comment]
Can you retest with the latest SDL3 code? We've made the renderer creation fail if D3D12 can't create pipeline state.
