### ISSUE TITLE
SDL_MouseWheelEvent mouseX and mouseY are not translated to logical window dimensions

### ISSUE THREAD

**Issue by yuv422** [libsdl-org/SDL#9097]
The values for `mouseX` and `mouseY` in `SDL_MouseWheelEvent` are relative to the render output size not the logical window size. In the other events like `SDL_MouseMotionEvent` the `x` and `y` coordinates have been converted to the logical window size.

This feels like a bug, the mouse wheel position should also be translated to the logical window size.

I tested this in `2.28.5`
Windows 10
with `direct3d11` renderer

**Comment by slouken** [comment]
Fixed, thanks!
