### ISSUE TITLE
2.30: Cannot draw to X11 root window.

### ISSUE THREAD

**Issue by IoIxD** [libsdl-org/SDL#9100]
I am trying to make an xscreensaver-compatible screensaver using SDL. This requires being able to draw to the X11 root window.

I have the following code for creating an SDL Window that should draw to it:

    Display *x11_d;
    int x11_s;
    Window x11_w;
    SDL_Window *window;
    x11_d = XOpenDisplay(getenv("DISPLAY"));
    if (!x11_d)
    {
        fprintf(stderr, "couldn't open display\n");
        return;
    }

    x11_s = DefaultScreen(x11_d);
    x11_w = DefaultRootWindow(x11_d);
    if (None == x11_w)
    {
        fprintf(stderr, "Failed to create window");
        XCloseDisplay(x11_d);
        return;
    }
    XMapWindow(x11_d, x11_w);
    Atom wm_delete_window = XInternAtom(x11_d, "WM_DELETE_WINDOW", False);
    XSetWMProtocols(x11_d, x11_w, &wm_delete_window, 1);

    if (SDL_Init(SDL_INIT_VIDEO) < 0)
        panic("[x] Couldn't initialize SDL: %d\n", SDL_GetError());
    atexit(SDL_Quit);

    window = SDL_CreateWindowFrom((void *)x11_w);

As well as `XFlush(x11_d);` being executed on loop.

Nothing I do is able to make SDL actually draw to the provided root window. I'm able to make it draw to a user created window, but not the root one.

**Comment by slouken** [comment]
I'm pretty sure the issue here is that the root window isn't compatible with an OpenGL context, which SDL uses by default.

Are you able to draw using a software renderer? (e.g. passing the `SDL_RENDERER_SOFTWARE` flag to SDL_CreateRenderer())

**Comment by IoIxD** [comment]
Nevermind, turns out I was looking at an outdated tutorial anyways. This is not even how you do an xscreensaver module anymore.
