### ISSUE TITLE
SDL_SetRenderLogicalPresentation doesn't scale mouse inputs to the target resolution

### ISSUE THREAD

**Issue by Plackett** [libsdl-org/SDL#9101]
In SDL2 there was a function called SDL_RenderSetLogicalSize which has been renamed SDL_SetRenderLogicalPresentation, a command that allowed me to scale all of my mouse events to the upscaled size of my game when it is played on larger screens. However, it seems that this functionality has been removed in SDL3, which is okay since I can just scale it manually by getting the current screen size but I'd like to see that functionality returned in future versions in order to make migration easier for other users.

### here's some sample code
Upon running this code you will be presented with a basic application that tracks your mouse position, the thing I have a problem with is that the logical size is supposed to be 160x90 but your mouse position in this example will not be scaled down to that and instead just goes up to the whole window size of 640x360, as shown by the console.

```
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <stdio.h>

int main(int argc, char** argv)
{
    // init video
    if (SDL_Init(SDL_INIT_VIDEO) != 0) {
        SDL_Log("Unable to initialize SDL: %s", SDL_GetError());
        return 1;
    }
    // making the window
    SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles2");
    SDL_Window* window = SDL_CreateWindow(
        "Mouse Test", 640, 360, SDL_WINDOW_MOUSE_FOCUS);
    // Check that the window was successfully created
    if (window == NULL) {
        // In the case that the window could not be made...
        printf("Could not create window: %s\n", SDL_GetError());
        return 1;
    }
    // making the renderer
    SDL_Renderer* r = SDL_CreateRenderer(window, NULL, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    // main render loop
    bool running = true;
    while (running)
    {
        // SET LOGICAL SIZE <---
        SDL_SetRenderLogicalPresentation(r, 160, 90, SDL_LOGICAL_PRESENTATION_LETTERBOX, SDL_SCALEMODE_NEAREST);
        // allow the user to quit the application
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_EVENT_MOUSE_MOTION)
            {
                printf("\nMouse movement at X: %d Y: %d", (int)event.button.x, (int)event.button.y);
            }
            else if (event.type == SDL_EVENT_QUIT)
            {
                running = false;
            }
        }
    }
    SDL_DestroyWindow(window);
    SDL_DestroyRenderer(r);
    return 0;
}

**Comment by slime73** [comment]
The [migration guide](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_renderh) says that you should call `SDL_ConvertEventToRenderCoordinates` if you want that behaviour.

**Comment by Plackett** [comment]
> The [migration guide](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_renderh) says that you should call `SDL_ConvertEventToRenderCoordinates` if you want that behaviour.

Thats true yeah my bad, should've read it more closely.
