### ISSUE TITLE
Should `SDL_GetGamepadStringForButton` return brand-dependant button names? e.g. "Cross", "Circle" for PS controllers

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9104]
... or will this upset the mapping strings? It's a real shame we're stick with a,b,x,y which contradicts the new n,e,s,w. At least if `SDL_GetGamepadStringForButton` returned the correct string, it would make a little more sense.

**Comment by slouken** [comment]
Yeah, we tried that and it broke mappings.
