### ISSUE TITLE
Wayland scaling error on display toggle off

### ISSUE THREAD

**Issue by u16rogue** [libsdl-org/SDL#9107]
*For some context I am coming from https://github.com/Genymobile/scrcpy/issues/4686 and was told to report it here instead.*

Whenever I lock my computer and turn off its display the `scrcpy` application (which uses SDL I presume) closes with a
```
wl_surface@32: error 0: Specified scale value (0) is not positive
```

Is there any way this error could be ignored or make SDL go dormant when there's no active display?

I'm using sway (1.8.1) on wayland.

**Comment by Kontrabant** [comment]
Sway 1.8.1 doesn't support the fractional scale protocol, so SDL pulls the scale from the display info, but SDL should account for there being no displays and preserve the old, valid, scale value.

Could you replicate this with `WAYLAND_DEBUG=1` set? That will show us exactly what is going on.

**Comment by u16rogue** [comment]
[scrcpy.log](https://github.com/libsdl-org/SDL/files/14368483/scrcpy.log)
Thanks! It does take a bit of time for it to close/error out so a quick display off didn't trigger it.

**Comment by Kontrabant** [comment]
One other question: what version of SDL is being used here?  The log shows me where this is happening, but I absolutely cannot replicate this in the current code, even artificially, as the only condition that could cause this is explicitly guarded against.

**Comment by u16rogue** [comment]
```
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.28.5 / 2.30.0
 - libavcodec: 60.31.102 / 60.31.102
 - libavformat: 60.16.100 / 60.16.100
 - libavutil: 58.29.100 / 58.29.100
 - libavdevice: 60.3.100 / 60.3.100
 - libusb: - / 1.0.27
```
Apologies, I should've provided these much earlier.

**Comment by Kontrabant** [comment]
Thanks for the additional info.

I see what is happening now: the spec apparently does not guarantee that a leave event is sent when a wl_output object is destroyed, and at some point, the compositor destroys and immediately recreates an output without a corresponding leave event, which means that any references to the output data held by a window will point to invalid memory since the pointer to the output was never removed from the window's output list, and the scale value is read as 0 because it's dereferencing garbage. We're going to have to ensure that all references to a removed output are removed from any window lists manually when an output is destroyed since the leave is implicit here.

This needs to be handled in both SDL3 and SDL2.

**Comment by Kontrabant** [comment]
Hmm, my previous hypothesis proved incorrect upon further review. In the meantime, I created a fix that should work, but I still don't particularly like not knowing exactly why this is happening. On the other hand, the code path where this occurs is basically already a legacy path, as any more recent version of the major desktop environments already has support for protocols that report the preferred scale directly vs having to derive it from what outputs the surface is on.

@u16rogue, could you test this branch and see if it fixes your issue? https://github.com/Kontrabant/SDL/tree/wayland_scale_zero_fix

**Comment by u16rogue** [comment]
I might be doing this incorrectly but the shared object binary should be `libSDL2-2.0.so.0.3100.0`? I've got the branch compiled locally but cant use `LD_PRELOAD` to force `scrcpy` to use the built SDL.

```
[I] <>@<> /home/<>/Packages/SDL/build (wayland_scale_zero_fix)
[$] export LD_PRELOAD=~/Packages/SDL/build/libSDL2-2.0.so.0.3100.0
[I] <>@<> /home/<>/Packages/SDL/build (wayland_scale_zero_fix)
[$] scrcpy --version
ERROR: ld.so: object '~/Packages/SDL/build/libSDL2-2.0.so.0.3100.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Comment by Kontrabant** [comment]
You can also try `SDL_DYNAMIC_API=~/Packages/SDL/build/libSDL2-2.0.so.0.3100.0`, and SDL will internally direct function calls to the newer version.

**Comment by Kontrabant** [comment]
Ok, stared at the logs and code a bit more last night and finally figured out exactly what was going on. My original guess was actually correct, but I was mislead by looking at the wrong event IDs in the log. The window surface does indeed enter an output, which is then removed with no corresponding leave event when the suspend/resume cycle occurs, so we need to make sure that no windows hold a reference to a removed output.

A proper fix is tested and ready to go.

**Comment by u16rogue** [comment]
Thanks! I wasn't able to do the tests yesterday as I was out. Ran the test today and left my display off for 10 minutes and `scrcpy` no longer closes. I'll relay this to the original issue. Thanks a lot!
