### ISSUE TITLE
SDL 3 Migration - Audio API

### ISSUE THREAD

**Issue by Ravbug** [libsdl-org/SDL#9109]
I am updating code that used the SDL2 audio callback to SDL3. I noticed that `SDL_AudioSpec.samples` does not appear to have an analogue in SDL3. This is a problem for my code because I am using audio spatialization middleware which can only output a fixed buffer size after it is initialized. With SDL2, this was not a problem because I could just set `SDL_AudioSpec.samples` and the middlware's buffersize to be the same value, and each time the callback was invoked, it was asking for that number of samples.

However, in SDL3, the callback asks for a different number of samples every time it is called, which means that migration is not as simple as what the migration guide shows: https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_audioh

Is it possible to configure SDL3 to invoke the audio callback such that it always asks for the same number of samples every time it is called?

**Comment by icculus** [comment]
> Is it possible to configure SDL3 to invoke the audio callback such that it always asks for the same number of samples every time it is called?

No, but the callback also does not care how much data you _actually_ put to the audiostream on each call. If you give it less than requested, it will fill the rest of the playback time with silence (which could make sense at the end of playback), and if you give it more, it'll just have extra already available when it goes to consume more data.

Which is to say: you can just feed the thing a fixed amount every time it runs, regardless of what it asks for.

The only gotcha is that you need to make sure you give it _at least_ what it asks for so you don't get skips in the audio. After opening the audio device, you can call [SDL_GetAudioDeviceFormat](https://wiki.libsdl.org/SDL3/SDL_GetAudioDeviceFormat) to find out how much data it intends to consume at a time, and then set up the middleware to output that much audio per iteration.

**Comment by Ravbug** [comment]
This works, thianks!
