### ISSUE TITLE
Typo in SDL_filesystem.h docs

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9115]
"Finds the most suitable user folder for `@p` purpose" ... the `@p` is a typo, right?

https://github.com/libsdl-org/SDL/blob/5b3ee51c6ca94f803a4ca77ce0dce08ee0426f80/include/SDL3/SDL_filesystem.h#L209

EDIT: sorry for the notification, @p!

**Comment by slouken** [comment]
I think it used to have a `p` parameter.

**Comment by Semphriss** [comment]
I originally named the single argument for that function "purpose" instead of "folder", and I used a `@p` for Doxygen formatting. If it's not needed to refer to parameters in the Doxygen comments, it can be removed.

**Comment by Semphriss** [comment]
It's been open for a few days, would you like me to fix it and open a PR?

**Comment by slouken** [comment]
Sure, thanks!
