### ISSUE TITLE
Build SDL release artifacts in GitHub Actions CI

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#9126]
I am picking this out of #4758 because I think it's really important, as it would enable tracing what is actually built in the VC package shipped in the releases. I had issues in the past with the binary Windows releases two times now

- https://github.com/libsdl-org/SDL/issues/9099#issuecomment-1961982338
- https://github.com/libsdl-org/SDL/issues/6996#issuecomment-1371720196

Unfortunately there's a different issue currently that is about dropping binaries (#8065), we currently use the [VC package in a Windows Docker image](https://github.com/adventuregamestudio/ags/blob/c13eca1adaec6e05f65beca5e53d5ba2b95f5e16/ci/windows/Dockerfile#L67-L80) which gives me an environment I can build our project using Visual Studio and can still run for debugging in my machine (with Windows Docker). If it's decided that the binaries are to actually be dropped we will rework to build things from source.

So it would be nice to be able to have the binaries built in GitHub Actions here so we could have logs so we know which SDL project options are used and also know the same binary is either working or giving errors for other developers too.

**Comment by slouken** [comment]
This is implemented in https://github.com/libsdl-org/SDL/pull/8076
