### ISSUE TITLE
Review the hints API

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#9129]
- Remove deprecated function(s): [`SDL_ClearHints`](https://github.com/libsdl-org/SDL/blob/38d24778ed528db361a991b5e449ec907b35711b/include/SDL3/SDL_hints.h#L2664-L2678) https://github.com/libsdl-org/SDL/commit/64ea6cefafb006799dedca0f11e937158ce60045
- Review the other api functions.

**Comment by slouken** [comment]
I reviewed the API and everything else looks good. Thanks for catching this!
