### ISSUE TITLE
SDL3 macOS build no longer a universal library

### ISSUE THREAD

**Issue by isXander** [libsdl-org/SDL#9134]
Since SDL3, the macOS build now only supports x86_64, not ARM.

These are my current build steps
```bash
brew install ant cmake
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release
cp SDL/build/libSDL3.dylib target.dylib
```
Here is the error Java JNA outputs 
```
is an incompatible architecture (have 'x86_64', need 'arm64'))
```

This is built on a GitHub macOS runner, so it may be an x86 host. For the exact build steps, see here https://github.com/isXander/libsdl4j/blob/SDL3/.github/workflows/build-natives.yml#L96

**Comment by madebr** [comment]
Can you try configuring with the following command?
```sh
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
```

**Comment by slouken** [comment]
Maybe we need to add this to the documentation? Or maybe default to that on macOS builds? I certainly could use that being the default.

**Comment by madebr** [comment]
Not sure about this, documentation of [`CMAKE_OSX_ARCHITECTURES`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) says the variable is user-set.

Can you try the following, and check whether it behaves as expected?
```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -98,6 +98,10 @@ list(APPEND CMAKE_REQUIRED_LINK_OPTIONS ${SDL_CHECK_REQUIRED_LINK_OPTIONS})
 # Get the platform
 SDL_DetectCMakePlatform()
 
+if(NOT SDL3_SUBPROJECT AND (DARWIN OR MACOSX) AND NOT DEFINED CMAKE_OSX_ARCHITECTURES)
+  set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")
+endif()
+
 # Don't mistake macOS for unix
 if(UNIX AND NOT ANDROID AND NOT APPLE AND NOT RISCOS)
   set(UNIX_SYS ON)
```
I *think* this will build both archs for the desktop platform, and don't do anything for the other platforms.
I don't know how it behaves with Apple simulators.

I'm not a fan for doing this.
Alternatively, you can modify your dev environment, to use an alternative default cmake toolchain.
Add the following to your `.bashrc` (or the Apple equivalent):
```sh
cat >/Users/slouken/default-cmake-toolchain.cmake <<EOF
set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")
EOF
export CMAKE_TOOLCHAIN_FILE="/Users/slouken/default-cmake-toolchain.cmake"
```

fyi, using similar environment files, I configure cross compilers in clion

**Comment by slouken** [comment]
Okay, well let’s at least document this, as well as document how to fix the rpath issue.

**Comment by slouken** [comment]
Why would the build default to x86_64? That hasn’t been my experience.

**Comment by madebr** [comment]
Just a guess, perhaps the cmake binary is x86_64?

**Comment by madebr** [comment]
> Okay, well let’s at least document this, as well as document how to fix the rpath issue.

What rpath issue?

**Comment by slouken** [comment]
> > Okay, well let’s at least document this, as well as document how to fix the rpath issue.
> 
> What rpath issue?

https://github.com/libsdl-org/SDL/issues/9017

I ran into this recently myself and had to use otool to remove the rpath entry in order to run my application linked with SDL3.

**Comment by isXander** [comment]
Adding the compiler flag did fix the issue, thank you. Should I leave this issue open or leave it tracking in the PR?

**Comment by slouken** [comment]
Tracking in the PR is fine. Thanks for the update!

**Comment by xesf** [comment]
Just setting the architecture was not enough for me to make it work on x86. I had to to link with 
`-L$(BIN) -Wl,-rpath,${BIN} -lSDL3` to work with dynamic linking

Without this, I was always getting "cland ld: symbol(s) not found for architecture x86_64"

**Comment by Aeonitis** [comment]
I imagine SDL3 is now on its way to brew.sh?

**Comment by madebr** [comment]
> I imagine SDL3 is now on its way to brew.sh?
> 
> https://www.phoronix.com/news/SDL3-Official-Release

Don't assume. Ask [here](https://github.com/orgs/Homebrew/discussions), and/or create a pr [here](https://github.com/Homebrew/homebrew-core)
