### ISSUE TITLE
Direct2D12 no longer works with ImGui's SDL3+SDL_Renderer correctly

### ISSUE THREAD

**Issue by JoeyLiang-0** [libsdl-org/SDL#9135]
Since the commit of: https://github.com/libsdl-org/SDL/commit/54c2ba6afd776d0d0c8f2bc438ad34d49a9cd87c
ImGui's example of SDL3+SDL_Renderer3 doesn't work correctly, https://github.com/ocornut/imgui/tree/master/examples/example_sdl3_sdlrenderer3
Omar thought the cause should be on SDL side. The details of the issue: 
https://github.com/ocornut/imgui/issues/7343
The screenshots of correct version vs. wrong one:
![image](https://github.com/libsdl-org/SDL/assets/68010055/2df9c14c-adb5-4463-8454-9fd62cdd8f88)

**Comment by slouken** [comment]
Can you find out what renderer is being used and what texture format is being used? Is this an HDR use case?

**Comment by JoeyLiang-0** [comment]
Don't think HDR is used in the example project.
When stepping into the rendering callstacks, it showed D3D12 renderer is used, texture format is 0x16762004.
```
>	example_sdl3_sdlrenderer3.exe!SDL_RenderGeometryRaw_REAL(SDL_Renderer * renderer, SDL_Texture * texture, ...
 	example_sdl3_sdlrenderer3.exe!SDL_RenderGeometryRaw(SDL_Renderer * a, SDL_Texture * b, ...
 	example_sdl3_sdlrenderer3.exe!ImGui_ImplSDLRenderer3_RenderDrawData(...
 	example_sdl3_sdlrenderer3.exe!main(...

renderer->info
{name=0x00007ff7a5f18940 "direct3d12" flags=0x00000006 num_texture_formats=0x00000009 ...}
    name: 0x00007ff7a5f18940 "direct3d12"
    flags: 0x00000006
    num_texture_formats: 0x00000009
    texture_formats: 0x0000017ce27b60e8 {0x16362004, 0x16161804, 0x16572004, 0x1a204008, 0x32315659, 0x56555949, 0x3231564e, ...}
    max_texture_width: 0x00004000
    max_texture_height: 0x00004000

texture->format
0x16762004
```

Note: with the same version, example_win32_directx12 works fine (the left half of the attached screenshot)

**Comment by slouken** [comment]
Hmm, it's working for me here. Are you using the latest imgui and SDL code?
<img width="642" alt="image" src="https://github.com/libsdl-org/SDL/assets/2100061/876f836e-2ea7-4bd4-88f5-38be37154f84">

**Comment by joey-cyt** [comment]
Thanks, I will try to find other machine(s) to test, to see if there is other cause(s) invovled.

**Comment by oscar7070** [comment]
Not working currently for me too on OpenGL & Vulkan
OpenGL(Broken ):
![Screenshot_318](https://github.com/libsdl-org/SDL/assets/56559647/b78d8fe6-472b-4f8a-abd0-5d600bdc677e)

DirectX(Works with no problems):
![Screenshot_319](https://github.com/libsdl-org/SDL/assets/56559647/16cd59ec-45bc-4b14-b5f8-4ee835d97b59)

And Vulkan(Broken and crashing)
![Screenshot_320](https://github.com/libsdl-org/SDL/assets/56559647/6f19a5eb-f1db-47d8-b4cd-a05231d3fcdd)

**Comment by joey-cyt** [comment]
Today, sync-ed to the latest SDL source code, and kept ImGui code the same, the ImGui's example_sdl3_sdlrenderer3 renders content correctly again! Thanks for the great work!

**Comment by slouken** [comment]
Great!
