### ISSUE TITLE
SDL3 Request: Date and Time API

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#9138]
It might be useful to provide an API for getting current date and time in a cross-platform manner. Some uses of this are:

1. Showing the date/time when a save game was made.
2. Printing the time of error in a log file.
3. Creating a unique, sortable name for screenshot files.
4. Showing the time when a multiplayer match started/ended.

Following is an (potentially incomplete) list of desirable APIs:

1. `SDL_TimeCurrent()`: A function to get current time (`SDL_Time`) in terms of seconds passed since some epoch, along with nanoseconds passed since last discrete second.
2. `SDL_TimePassed(new, old)`: A function to subtract two `SDL_Time`s that returns `SDL_Time_Passed`.
3. `SDL_TimeFormat()`: An equivalent to [`strftime`](https://man7.org/linux/man-pages/man3/strftime.3.html) to get the `SDL_Time` and `SDL_Time_Passed` in a human-readable string format.
4. _(optional)_ A function to revert the formatting in the above (i.e., string→`SDL_Time` or `SDL_Time_Passed`).

**Comment by AntTheAlchemist** [comment]
Would also be useful for designing idle games.

**Comment by slouken** [comment]
Adding to the 3.x milestone for consideration. @icculus, what are your thoughts?

**Comment by Kontrabant** [comment]
Taking a swing at this.  Currently have RTC handling for all of the supported platforms except for PS2 (which looks like a huge pain), conversion to human readable UTC and local date/time for ease of use, and strftime is in progress. Still WIP and not ready for review yet, but underway.

Since the forthcoming filesystem code uses seconds since the Unix epoch, it's trivial to use the human readable `SDL_DateTime` conversion functions with filetimes as well.

https://github.com/Kontrabant/SDL/tree/sdl_rtc_functions

**Comment by madebr** [comment]
How does it handle time zones and DST?

**Comment by Kontrabant** [comment]
It leaves that up to the OS.  Timestamps are in UTC, and every platform (except for the 3DS) has functions to convert system timestamps to either UTC or the local date/time according to the system timezone (e.g. gmtime/localtime).

The 3DS clock is the exception, as it seems to basically be a digital watch, with no concept of time zones or DST, so there's nothing we can really do about it.

**Comment by Kontrabant** [comment]
Still in progress; getting time string formatting reasonably consistent across platforms was not an easy task, as strftime is one of those "standard" functions that has all kinds of quirks and non-standard extensions across platforms, so SDL wound up with its own implementation that only calls into the underlying strftime when locale-specific formatting is required, and can work without any underlying C standard library, albeit sans locale support. Wound up with some #ifdef hell in there, but that's not out of the ordinary for formatting functions that need to be cross platform if you look at some of the c standard libraries.

Feature wise it's fairly complete now, but still needs code and documentation cleanup, and formal automated tests.  Current working branch is at https://github.com/Kontrabant/SDL/tree/sdl_rtc_functions_dst
