### ISSUE TITLE
`JoyDeviceEvent`'s `SDL_EVENT_JOYSTICK_ADDED` `which` field does not refer to a `SDL_JoystickID`

### ISSUE THREAD

**Issue by isXander** [libsdl-org/SDL#9141]
On the added event, the `which` field refers to the device index, even though it is wrapped in an `SDL_JoystickID`. This leaves the field ambiguous and leads to bugs.

**Comment by isXander** [comment]
Even when calling `SDL_GetGamepadInstanceID` after the controller is opened would for example output `1`, but when consuming the remove event I get `0x8BCBD361` from `which`

**Comment by slouken** [comment]
For SDL 2.0 this was intentional design. For SDL 3.0 we've rethought that, and it's an instanceID everywhere.

**Comment by isXander** [comment]
> For SDL 2.0 this was intentional design. For SDL 3.0 we've rethought that, and it's an instanceID everywhere.

Could you let me know what I'm doing wrong here? Instance id appears to still be index on added

**Comment by isXander** [comment]
From debugging my application, this is what it currently looks like: 
```java
SDL_JoystickID[] joysticks = SDL_GetJoysticks();
for (SDL_JoystickID jid : joysticks) {
	LOGGER.info("Controller discovered: {}", jid.intValue()); // Controller discovered: 1
}
```
```java
SDL_Event event = new SDL_Event();
while (SDL_PollEvent(event)) {
	switch (event.type) {
		case SDL_EVENT_JOYSTICK_REMOVED -> {
			SDL_JoystickID jid = event.jdevice.which;
			LOGGER.info("Controller removed: {}", jid.intValue()); // Controller removed: -1818745232
		}
	}
}
```
This very clearly shows the problem here

**Comment by isXander** [comment]
https://github.com/libsdl-org/SDL/blob/main/src/joystick/SDL_joystick.c#L697

I assume this is the problem

**Comment by slouken** [comment]
The ID I'm seeing is 3, which is correct. What operating system and controller are you using?

**Comment by isXander** [comment]
Windows 11 with a Dualsense Controller. No additional software

**Comment by slouken** [comment]
Yeah, the ID is still 3 here when using a DualSense controller, both over USB and Bluetooth. I'm not sure what's happening here, other than maybe the memory layout doesn't match between C and whatever language you're using?

**Comment by isXander** [comment]
It was indeed a misaligned struct, sorry for bothering you with this.
