### ISSUE TITLE
UWP SDL3: SDL_GetWindowSizeInPixels returns points not pixels

### ISSUE THREAD

**Issue by Ravbug** [libsdl-org/SDL#9146]
I am testing on a 4K monitor (3840x2160 pixels), with the window maximized. With Win32, when I call `SDL_GetWindowSizeInPixels`, I get 3840x2066, which is expected because of the window titlebar. However, on UWP, when I call `SDL_GetWindowSizeInPixels`, I get 2560x1368, which appears to be screen points rather than pixels and matches the value returned by `SDL_GetWindowSize`.

**Comment by icculus** [comment]
UWP support was removed from SDL3, so I'm closing this one.
