### ISSUE TITLE
testffmpeg link failure in absence of EGL libs

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#9155]
```
CMakeFiles/testffmpeg.dir/testffmpeg.c.o: In function `CreateWindowAndRenderer.isra.2':
testffmpeg.c:(.text+0x2e4): undefined reference to `eglGetCurrentDisplay'
testffmpeg.c:(.text+0x2f1): undefined reference to `eglQueryString'
testffmpeg.c:(.text+0x395): undefined reference to `eglGetProcAddress'
CMakeFiles/testffmpeg.dir/testffmpeg.c.o: In function `GetTextureForDRMFrame.constprop.8':
testffmpeg.c:(.text+0x3dc): undefined reference to `eglGetCurrentDisplay'
testffmpeg.c:(.text+0x5f9): undefined reference to `eglCreateImage'
testffmpeg.c:(.text+0x61d): undefined reference to `glBindTexture'
collect2: error: ld returned 1 exit status
```

testffmpeg.c relies on `HAVE_EGL` which in turn relies on `HAVE_OPENGLES_V2`
which is supposedly checked in top-level cmake/sdlchecks.cmake::CheckOpenGLES
That check tests build success by including GLES2 headers but it checks the
local headers from src/video/khronos which is pretty much pointless. It does
not check linkage to EGL library which testffmpeg actually needs.

CC: @madebr, @slouken

**Comment by madebr** [comment]
SDL loads EGL dynamically, whereas the tests links.
Does this work?
```diff
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -232,12 +232,10 @@ if(FFmpeg_FOUND AND LIBAVUTIL_AVFRAME_HAS_CH_LAYOUT)
     if(APPLE)
         target_link_options(testffmpeg PRIVATE "-Wl,-framework,CoreVideo")
     endif()
-    if(HAVE_OPENGLES_V2)
+    if(TARGET OpenGL::EGL)
         message(DEBUG "Enabling EGL support in testffmpeg")
+        target_link_libraries(testffmpeg PRIVATE OpenGL::EGL)
         target_compile_definitions(testffmpeg PRIVATE HAVE_EGL)
-        if(TARGET OpenGL::EGL)
-            target_link_libraries(testffmpeg PRIVATE OpenGL::EGL)
-        endif()
     endif()
     target_link_libraries(testffmpeg PRIVATE ${FFMPEG_LIBRARIES})
 else()
```

**Comment by sezero** [comment]
>  Does this work?

Yes, with and without EGL libs present.

**Comment by madebr** [comment]
> > Does this work?
> 
> Yes, with and without EGL libs present.

So I understand:
- when they are present, testffmpeg correctly links to EGL and works?
- when not present, EGL is correctly disabled?

If so, I'll push a commit.

**Comment by sezero** [comment]
>     * when they are present, testffmpeg correctly links to EGL and works?
>     * when not present, EGL is correctly disabled?

Yes.

**Comment by madebr** [comment]
Thanks!
I pushed it as 0a961915d
