### ISSUE TITLE
SDL3 Request: qsort_r

### ISSUE THREAD

**Issue by bobbens** [libsdl-org/SDL#9159]
`SDL_qsort` is great, but can not handle the case that the comparison function needs extra data and the call is threaded so you can't use globals. Different operating systems have proposed different variants such as `qsort_r` (BSD / Linux), and `qsort_s` (Windows), but they aren't API compatible, and furthermore, I believe the BSD / Linux variants of `qsort_r` are not even compatible with each other. Adding something like `SDL_qsort_r` which would wrap around such functions would be great to have and solve the issue.

There is a public domain implementation of a portable `qsort_r` at https://github.com/noporpoise/sort_r that could be used as a reference to implement it in SDL.

**Comment by icculus** [comment]
I think this is a good idea, but we should take a quick look at our existing qsort implementation first and see if it's trivial to retrofit the userdata argument into it, so we don't have to juggle two implementations.

**Comment by slouken** [comment]
> I think this is a good idea, but we should take a quick look at our existing qsort implementation first and see if it's trivial to retrofit the userdata argument into it, so we don't have to juggle two implementations.

Agreed.

**Comment by icculus** [comment]
Also, surprised to find out SDL_qsort's callback isn't marked SDLCALL. Let's fix that while we're in here, too.

**Comment by icculus** [comment]
Also surprised to discover that macOS/iOS/BSD has a qsort_r that takes the same arguments in a different order than glibc/ISO's version. (and Visual Studio has a qsort_s that matches glibc, except the callback takes parameters in a different order). @bobbens said as such at the start, to be clear.

Thinking we should just always our built-in version of qsort in SDL3, extended to be qsort_r, and dump the external C runtime versions. They're probably all using the same algorithm anyhow.

**Comment by icculus** [comment]
Okay, I took a run at this. Merge if you think it's a good idea!
