### ISSUE TITLE
SDL3 request: SDL_ShowCursor and SDL_SetCursor should probably have a window parameter (consistency nitpick)

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#9160]
I suggest that SDL_ShowCursor should have a window parameter, such that when an app runs windowed and created multiple windows, there is granular control over which window will hide the cursor when the cursor hovers over it, and which ones won't. Same for SDL_SetCursor.

Maybe it's just me, but I'm currently implementing a higher level API on top of this and since showing or hiding the mouse cursor usually depends on what's under it and mouse events to figure out what is under a cursor depend on the window already, it doesn't seem to make too much sense to have this setting not also per window.

**Comment by slouken** [comment]
The general use case is a single window, so in the interest of keeping the API simple for the simple use case, we've left a window parameter out. If you're handling multiple windows it's easy enough to keep track of which windows need the cursor shown and update the state when you get mouse enter/leave events.

With SDL3 you can even use window properties to track this state so you don't need a separate way to track it.

**Comment by ell1e** [comment]
Yes that's what I'm currently doing, tracking it manually. I just struck me as oddly inconsistent, so I think a change here would still work better in terms of API consistency.

However, I agree that it's not strictly speaking needed just to make it "work" for the user.
