### ISSUE TITLE
Make `SDL_TouchDevicesAvailable` return actual number of touch devices, instead of a bool

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9164]
I have a case where I just want to know the number of touch devices:

```
int count;
SDL_free(SDL_GetTouchDevices(&count));
```

Can we just make `SDL_TouchDevicesAvailable` return the actual number of devices?

**Comment by AntTheAlchemist** [comment]
... And also open this function up to public

**Comment by slouken** [comment]
It's not as relevant for touch devices, but there's potentially a race condition between getting the device list and getting the device count, so we opted to have a single function that returns both, atomically. We don't want to add a separate function that returns the count so people don't make the mistake of trying to get one and then the other.

The way you're doing it is correct, even if a little more cumbersome.
