### ISSUE TITLE
Feature Request: Control/Set Player LED without Overwriting Player Index

### ISSUE THREAD

**Issue by dreamsyntax** [libsdl-org/SDL#9165]
Currently, SDL 2.30.0 only exposes the player LED through this function:
```C++
/**
 * Set the player index of an opened game controller.
 *
 * \param gamecontroller the game controller object to adjust.
 * \param player_index Player index to assign to this controller, or -1 to
 *                     clear the player index and turn off player LEDs.
 *
 * \since This function is available since SDL 2.0.12.
 */
extern DECLSPEC void SDLCALL SDL_GameControllerSetPlayerIndex(SDL_GameController *gamecontroller, int player_index);
```

However, some programs make use of the player_index. As such they cannot both have a player LED set to off (-1) and have a unique player index per controller.

This is most easily demonstrated on a Dual Sense controller (photos in below link)
Below is one such example in PCSX2, where we are unable to set the player LED off still utilizing the player index.
https://github.com/PCSX2/pcsx2/pull/10864#issuecomment-1966169776

**Request**
Currently we can only disable the player LED by clearing the player_index to -1 per https://github.com/libsdl-org/SDL/issues/5904
Expose the ability to disable/enable the player LED for controllers, not to be confused with the existing HasLED/SetLED, which affects the primary LED not the player LED, without clearing the assigned player_index.

Thank you for your consideration.

**Comment by slouken** [comment]
There is a hint to control the player LED:
https://github.com/libsdl-org/SDL/blob/9eaf7d8cc87755c094cb4e04e84eb5bfa5f8f544/include/SDL_hints.h#L895-L902
