### ISSUE TITLE
SDL3 Vulkan update doesn't respect SDL_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9173]
error C2039: 'samplerYcbcrConversion': is not a member of 'VULKAN_TextureData'
warning C4047: 'function': 'VkSamplerYcbcrConversionKHR' differs in levels of indirection from 'VULKAN_Image *'
warning C4024: 'VULKAN_AllocateImage': different types for formal and actual parameter 8
error C2198: 'VULKAN_AllocateImage': too few arguments for call
error C2039: 'descriptorSetLayoutYcbcr': is not a member of 'VULKAN_TextureData'
error C2039: 'descriptorSetLayoutYcbcr': is not a member of 'VULKAN_TextureData'
error C2039: 'pipelineLayoutYcbcr': is not a member of 'VULKAN_TextureData'
error C2039: 'pipelineLayoutYcbcr': is not a member of 'VULKAN_TextureData'

**Comment by slouken** [comment]
Fixed, thanks!
