### ISSUE TITLE
No longer able to use process substitution to supply input to apps

### ISSUE THREAD

**Issue by markjreed** [libsdl-org/SDL#9174]
[This change](https://github.com/sezero/SDL/commit/c9c7d58a5b138a034a0b68613e3ce0e7c8172bf2) removed the ability to use any sort of special file with SDL apps.  On POSIX systems (Linux, macOS) I used to be able to pass command output via process substitution (e.g. `--input-file <(command here)`) and can no longer do that. Since I was using that mechanism to supply code to an emulator, this change broke my automated tests.

**Comment by slouken** [comment]
Oh, yeah, we should just check to see if the output is a directory. Writing to things like named pipes is totally fine.

**Comment by sezero** [comment]
That change was to fix https://github.com/libsdl-org/SDL/issues/8935, as was noted in the commit message.

Does something like to following help / is the correct change for this? (The helper name procedure needs changing to something more suitable too, I guess? To what?)

```diff
diff --git a/src/file/SDL_rwops.c b/src/file/SDL_rwops.c
index 439f20a..cb0579e 100644
--- a/src/file/SDL_rwops.c
+++ b/src/file/SDL_rwops.c
@@ -528,14 +528,15 @@ static int SDLCALL mem_close(SDL_RWops *context)
 static SDL_bool SDL_IsRegularFile(FILE *f)
 {
     #ifdef __WINRT__
     struct __stat64 st;
-    if (_fstat64(_fileno(f), &st) < 0 || (st.st_mode & _S_IFMT) != _S_IFREG) {
+    if (_fstat64(_fileno(f), &st) < 0 ||
+        ((st.st_mode & _S_IFMT) != _S_IFREG && (st.st_mode & _S_IFMT) != _S_IFIFO) {
         return SDL_FALSE;
     }
     #else
     struct stat st;
-    if (fstat(fileno(f), &st) < 0 || !S_ISREG(st.st_mode)) {
+    if (fstat(fileno(f), &st) < 0 || !(S_ISREG(st.st_mode) || S_ISFIFO(st.st_mode))) {
         return SDL_FALSE;
     }
     #endif
     return SDL_TRUE;
```

**Comment by sezero** [comment]
> Does something like to following help / is the correct change for this?
>
> (The helper name procedure needs changing to something more suitable too, I guess? To what?)
> 
> ```diff
> diff --git a/src/file/SDL_rwops.c b/src/file/SDL_rwops.c
> index 439f20a..cb0579e 100644
> --- a/src/file/SDL_rwops.c
> +++ b/src/file/SDL_rwops.c
> @@ -528,14 +528,15 @@ static int SDLCALL mem_close(SDL_RWops *context)
>  static SDL_bool SDL_IsRegularFile(FILE *f)
>  {
>      #ifdef __WINRT__
>      struct __stat64 st;
> -    if (_fstat64(_fileno(f), &st) < 0 || (st.st_mode & _S_IFMT) != _S_IFREG) {
> +    if (_fstat64(_fileno(f), &st) < 0 ||
> +        !((st.st_mode & _S_IFMT) == _S_IFREG || (st.st_mode & _S_IFMT) == _S_IFIFO)) {
>          return SDL_FALSE;
>      }
>      #else
>      struct stat st;
> -    if (fstat(fileno(f), &st) < 0 || !S_ISREG(st.st_mode)) {
> +    if (fstat(fileno(f), &st) < 0 || !(S_ISREG(st.st_mode) || S_ISFIFO(st.st_mode))) {
>          return SDL_FALSE;
>      }
>      #endif
>      return SDL_TRUE;
> ```

Can someone review this? Has the issue reporter tested this?

**Comment by slouken** [comment]
This change looks fine to me if it works for @markjreed. The function could be renamed IsReadableFile()?

**Comment by sezero** [comment]
> This change looks fine to me if it works for @markjreed.

OK, waiting.

Here are the new patches:

SDL2 version: [sdl2.patch.txt](https://github.com/libsdl-org/SDL/files/14470999/sdl2.patch.txt) (applies to release-2.30.x too)

SDL3 version: [sdl3.patch.txt](https://github.com/libsdl-org/SDL/files/14471000/sdl3.patch.txt)

> The function could be renamed IsReadableFile()?

Went with `IsRegularFileOrPipe` ..

**Comment by sezero** [comment]
> > This change looks fine to me if it works for @markjreed.
> 
> OK, waiting.
> 
> Here are the new patches:
> 
> SDL2 version: [sdl2.patch.txt](https://github.com/libsdl-org/SDL/files/14510701/sdl2.patch.txt) (applies to release-2.30.x too)
> 
> SDL3 version: [sdl3.patch.txt](https://github.com/libsdl-org/SDL/files/14510706/sdl3.patch.txt)
> 
> > The function could be renamed IsReadableFile()?
> 
> Went with `IsRegularFileOrPipe` ..

@slouken: The issue reporter @markjreed seems to have lost interest..
Do you want these patches in? (I don't have a way of run-testing them
with named pipes myself.) If you do, do you want it in release-2.30.x
too? (issue was reported against 2.30.0 .)

**Comment by slouken** [comment]
Yep, go ahead and apply and cherry pick to 2.30.x. Thanks!

**Comment by sezero** [comment]
Patches are in.

@markjreed: If you still have issues, please re-open this and give details.

**Comment by markjreed** [comment]
Sorry for the radio silence. Looks good to me. Thanks!

**Comment by sezero** [comment]
Thanks for the feedback.
