### ISSUE TITLE
SDL_GetRenderTarget returning different value than the one set in SDL_SetRenderTarget

### ISSUE THREAD

**Issue by mystborn** [libsdl-org/SDL#9176]
I'm working on a camera system, and throughout my draw calls I check if the renderer is currently using the camera texture. The value returned by SDL_GetRenderTarget does not return the pointer passed into SDL_SetRenderTarget.

I am on Windows 10, using the x64 debug version of SDL.

```c
SDL_RendererInfo info;
SDL_GetRendererInfo(renderer, &info);
SDL_SetRenderTarget(renderer, camera->render_target);
printf("%p == %p\n", camera->render_target, SDL_GetRenderTarget(renderer));
printf("%s\n", info.name);

// Output on my system: 
000001ECE78C59C0 == 000001ECE78C5900
direct3d12
```

Maybe a d3d12 bug?

EDIT:

Digging into the source, it looks like SDL_GetRenderTarget returns the native texture, which feels like unintended behaviour.

**Comment by slouken** [comment]
Can you create a more complete minimal example? I suspect it has to do with creating a render target in a texture format that isn't supported, which hasn't really been tested much.

**Comment by slouken** [comment]
Typically unless you need to lock the texture and access the pixels in a specific format, you'll want to use the first format in the list provided by SDL_GetRendererInfo(). For many renderers this is SDL_PIXELFORMAT_ARGB8888.
