### ISSUE TITLE
SDL_RenderGeometry no longer working on D3D12

### ISSUE THREAD

**Issue by mystborn** [libsdl-org/SDL#9178]
When I was investigating https://github.com/libsdl-org/SDL/issues/9176 (which is still an issue) I tried pulling the most recent master branch and now my draw commands no longer work. If you try and draw the most simple triangle, it just draws a line to the top left corner, and more advance routines output all sorts of weird stuff. I'm not sure where the regression happened, but I do know that the version I was previously using used SDL_Color in SDL_Vertex, and the new version uses SDL_FColor. Not sure if it's related, but if I were a betting man...

The renderer is direct3d12 and my graphics card is an RTX 3070

EDIT: For funsies I've tried switching the rendering engine to opengl, and it still fails to draw anything correctly.

Bigger Edit:

I'm a goddamn moron and didn't update the DLL, so was getting the weirdest functionality in the world when trying to call SDL_RenderGeometry. After updating the DLL, this issue is fixed. The linked issue still exists though.

**Comment by slouken** [comment]
lol, I'm glad you figured it out.
