### ISSUE TITLE
Mouse click on Android makes SDL crash

### ISSUE THREAD

**Issue by remjey** [libsdl-org/SDL#9185]
I found that when the `SDL_HINT_MOUSE_TOUCH_EVENTS` is enabled, which it is by default, using a mouse on an Android debug build of my app makes it crash. I narrowed it down to this call:

https://github.com/libsdl-org/SDL/blob/e524e545f2bca599b00610b7e8f5a59a23bd4d95/src/events/SDL_mouse.c#L757

It generates a virtual event, with `fingerId` always equal to `0`. This function in turns calls `SDL_AddFinger()` with the same value for `fingerId`:

https://github.com/libsdl-org/SDL/blob/e524e545f2bca599b00610b7e8f5a59a23bd4d95/src/events/SDL_touch.c#L322

And this last function has an assertion that fails if `fingerId` is `0`:

https://github.com/libsdl-org/SDL/blob/e524e545f2bca599b00610b7e8f5a59a23bd4d95/src/events/SDL_touch.c#L201

I tried setting `fingerId` to `1` in `src/events/SDL_mouse.c` and it seemed to solve the problem. I also set it to `1` in a call to `SendTouchMotion()` here:

https://github.com/libsdl-org/SDL/blob/e524e545f2bca599b00610b7e8f5a59a23bd4d95/src/events/SDL_mouse.c#L574

If that solution looks good I can make a pull request.

**Comment by slouken** [comment]
Fixed, thanks!
