### ISSUE TITLE
how to make it work in flutter ffi?

### ISSUE THREAD

**Issue by hirara-svg** [libsdl-org/SDL#9195]
I use Flutter's ffi to link to the compiled libSDL2.so, but always throw an error when calling SDL_init.
What is the reason for this? Is it true that Android SDL can only be called using Java's JNI?

W/SDL     (14205): Request to get environment variables before JNI is ready
I/flutter (14205): Application didn't initialize properly, did you include SDL_main.h in the file containing your main() function?

**Comment by icculus** [comment]
The Android version of SDL expects to be in charge of the Activity, so it does some setup at app startup time...it does this in Java and then calls into the C `main` function for the app to take control.

**Comment by hirara-svg** [comment]
> The Android version of SDL expects to be in charge of the Activity, so it does some setup at app startup time...it does this in Java and then calls into the C `main` function for the app to take control.

Thank you for your guidance. I initialized JNI in the activity, and now it won't prompt this error. I can initialize SDL_INIT.VIDEO, but once I initialize SDL_INIT.JOYSTICK, an error will appear. The problem seems to be in PLATFORM_hid_init?



backtrace:
      #00 pc ~~~/lib/x86_64/libSDL2.so (PLATFORM_hid_init+57)
      #01 pc ~~~/lib/x86_64/libSDL2.so (SDL_hid_init+27)
      #03 ~~~/lib/x86_64/libSDL2.so (SDL_JoystickInit+237)
      #04 ~~~/lib/x86_64/libSDL2.so (SDL_InitSubSystem+328)

**Comment by hirara-svg** [comment]
> The Android version of SDL expects to be in charge of the Activity, so it does some setup at app startup time...it does this in Java and then calls into the C `main` function for the app to take control.

Thank you for your guidance. I initialized JNI in the activity, and now it won't prompt this error. I can initialize SDL_INIT_VIDEO, but once I initialize SDL_INIT_JOYSTICK, an error will appear. The problem seems to be in PLATFORM_hid_init?

backtrace:
#00 pc ~~~/lib/x86_64/libSDL2.so (PLATFORM_hid_init+57)
https://github.com/libsdl-org/SDL/issues/1 pc ~~~/lib/x86_64/libSDL2.so (SDL_hid_init+27)
https://github.com/libsdl-org/SDL/issues/3 ~~~/lib/x86_64/libSDL2.so (SDL_JoystickInit+237)
https://github.com/libsdl-org/SDL/issues/4 ~~~/lib/x86_64/libSDL2.so (SDL_InitSubSystem+328)

**Comment by slouken** [comment]
In order to use SDL, your activity must derive from SDLActivity, which does a bunch of Android specific Java setup.
