### ISSUE TITLE
make gendynapi.py sort functions 

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#9196]
make we could make gendynapi.py sort API functions. 
so that we have less "merge conflicts" between two pr that would triy to had a new functions at the bottom of the dynapi files.

**Comment by madebr** [comment]
Once SDL3's api becomes fixed, we cannot change the order of the macro's in [src/dynapi/SDL_dynapi_procs.h](https://github.com/libsdl-org/SDL/blob/main/src/dynapi/SDL_dynapi_procs.h).
When using the dynapi, the order of the functions **must** be identical between SDL3 binaries that have a different version.
The order of the jump table is [simply memcpy'd](https://github.com/libsdl-org/SDL/blob/1e790b20c9b44986d405fdbaaeba5ebbf319b386/src/dynapi/SDL_dynapi.c#L389).

**Comment by slouken** [comment]
I will do a manual sort before we freeze the ABI, and once that happens all added functions must be at the end. We can leave it as-is for now.
