### ISSUE TITLE
Wayland: SDL_RaiseWindow() does not raise the window on KDE

### ISSUE THREAD

**Issue by weirddan455** [libsdl-org/SDL#9199]
System is Arch Linux using KDE Plasma 5.27.10.  When `SDL_RaiseWindow()` is called, the window does not get moved above any other window and it does not take keyboard input focus.  All that happens is the icon in the title bar turns orange.

Both trip of tree main and release 2.30 have the same behavior.

Repro case:

```c
#include <SDL3/SDL.h>
#include <unistd.h>
#include <stdio.h>

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *window = SDL_CreateWindow("Test", 200, 300, SDL_WINDOW_RESIZABLE);
    SDL_Renderer *renderer = SDL_CreateRenderer(window, NULL, 0);
    while (1) {
        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
        SDL_Event event;
        SDL_WaitEvent(&event);
        if (event.type == SDL_EVENT_QUIT) {
            return 0;
        }
        if (event.type == SDL_EVENT_KEY_DOWN) {
            sleep(2);
            puts("Raising Window");
            SDL_RaiseWindow(window);
        }
    }
    return 0;
}
```

This comment explains the situation.  I'm assuming it's up to the compositor what ends up happening but maybe there is something different SDL can do to convince it to raise the window.  Have not researched that far into it.

https://github.com/libsdl-org/SDL/blob/fb87f8f15c11477f294b6486f967ea167dcc20d6/src/video/wayland/SDL_waylandwindow.c#L1848-L1868

**Comment by Kontrabant** [comment]
All that can be done is the request as is done now. Window managers generally don’t allow apps to raise themselves to prevent focus stealing.
