### ISSUE TITLE
SDL_RenderPresent capped to 30 FPS when window in focus

### ISSUE THREAD

**Issue by mystborn** [libsdl-org/SDL#9216]
For some reason when the window is focused, SDL_RenderPresent acts similar to if VSync was enabled and always ensures that the frame takes ~33ms to complete. If I click off the window, it starts to render uncapped again.

Renderer: direct3d12
Renderer Flags: 2
VSync: 0

**Comment by AntTheAlchemist** [comment]
I'm not able to repro here with the same settings. I did notice is direct3d12 is a lot slower (800 fps) in my app compared to direct3d11 (1300 fps). 

Which version of SDL are you using? Which operating system? Video card? Can you rule out Nvidia settings overriding vsync behaviour?

**Comment by mystborn** [comment]
I'm building from source, here is the last commit I built from: 5643fd683f2e65daf533c7287d21a2f2324b4cdd

I am on Windows 10 version 22H2, build 19045.4123
Video card is Nvidia GeForce RTX 3070
I have double checked that VSync is off in the NVidia control panel.

Apparently this does only happen on one of my monitors, an LG ULTRAGEAR

**Comment by AntTheAlchemist** [comment]
I'm also Win 10 22H2, with GTX 1650. 

Is that SDL2 source or SDL3? Does direct3d11 give the same result?  Strange it only happens with a specific monitor 🤔

**Comment by slime73** [comment]
> Apparently this does only happen on one of my monitors, an LG ULTRAGEAR

Do you have freesync/gsync (variable-rate refresh) enabled for that monitor?

**Comment by slouken** [comment]
No response, I'll go ahead and close this for now. Please let us know if it's still an issue.
