### ISSUE TITLE
the libgl.dylib dosen't work work on macos montery 

### ISSUE THREAD

**Issue by JonnycatMeow** [libsdl-org/SDL#9222]
there is no libgl.dylib on my macos Monterey. I think they dropped support for it for Monterey and higher ups. but there is libgl.dylib on big sur and lower so Is there any alternative for libgl.dylib. I tried to use #version 150 but it says not supported even tho the core function is supported.

**Comment by icculus** [comment]
I think "libgl", by that specific name, is only in the optional X server package...? macOS provides OpenGL through OpenGL.framework, and has not removed it afaik.

(In modern times, their GL implementation appears to be built on top of Metal, presumably so it can keep working without a lot of maintenance on Apple's part in the future.)

**Comment by JonnycatMeow** [comment]
> I think "libgl", by that specific name, is only in the optional X server package...? macOS provides OpenGL through OpenGL.framework, and has not removed it afaik.
> 
> (In modern times, their GL implementation appears to be built on top of Metal, presumably so it can keep working without a lot of maintenance on Apple's part in the future.)

No the libgl.dylib is used on the system folder for macos but its in bigsur and below. I have used bing ai to find out. but I have thought about using mesa opengl but mesa opengl uses x11 so does mesa count as x11.

**Comment by sezero** [comment]
Here are the link libraries for OpenGL.framework,

for Monterey:
https://github.com/alexey-lysiuk/macos-sdk/blob/main/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL.tbd
for Sonoma:

https://github.com/alexey-lysiuk/macos-sdk/blob/main/MacOSX14.4.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL.tbd

Nothing is removed, it is always at 
`/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib`

I don't see any issues related to SDL here. @icculus?

**Comment by icculus** [comment]
I don't either.

If you need to load OpenGL symbols on macOS, either use them directly and link your program with `-framework OpenGL` or let SDL find them for you at runtime.

**Comment by JonnycatMeow** [comment]
but i don't see the dylib 
![Screen Shot 2024-03-07 at 5 02 25 PM](https://github.com/libsdl-org/SDL/assets/107599365/9decfd37-3270-4b86-afae-9254ec34551a)

**Comment by JonnycatMeow** [comment]
![Screen Shot 2024-03-07 at 5 02 42 PM](https://github.com/libsdl-org/SDL/assets/107599365/0b8dc7ba-c8dd-4081-83b0-5b68611bb643)

**Comment by alexey-lysiuk** [comment]
https://stackoverflow.com/questions/73376007/where-are-the-shared-libs-in-macos
