### ISSUE TITLE
Improvements to and fixes of wikiheaders.pl and sdlwiki SDL API documentation generation.

### ISSUE THREAD

**Issue by blaisemccourtney** [libsdl-org/SDL#9236]
There are some improvements that could be made to the automated generation of the sdlwiki SDL API documentation, some of which I am listing below to enable developers keep track of them. I considered fixing some of them myself, but the script responsible https://github.com/libsdl-org/SDL/blob/main/build-scripts/wikiheaders.pl for the generation would probably have to be refactored before I would venture a try at working with it. 1700+ lines of Perl with heavy regex usage and long code blocks is a bit daunting if you are not familiar with Perl.

- **By-name listing pages missing items in their list:** Not all types are included in the 'CategoryAPI' "API reference [by Name]" web pages. As an example, for the SDL 2 by-name listing page at https://wiki.libsdl.org/SDL2/CategoryAPI, the type `SDL_Surface` with the page https://wiki.libsdl.org/SDL2/SDL_Surface is not present in that by-name listing page.
  - [ ] SDL2
  - [x] SDL3
- **Missing links:** Several types in pages do not have links to types present in the type signature. An example is https://wiki.libsdl.org/SDL2/SDL_RenderGetWindow, where both types in the type signature have pages, but no links to them. Example for SDL3: https://wiki.libsdl.org/SDL3/SDL_GetRenderWindow .
  - [x] SDL2
  - [x] SDL3
- **Missing pages:** Some types do not have a page for them yet. An example is a type in the page https://wiki.libsdl.org/SDL2/SDL_CondSignal, which describes the type `SDL_cond` , but `SDL_cond` does not appear to have a page for it. Example for SDL3: https://wiki.libsdl.org/SDL3/SDL_SignalCondition and https://wiki.libsdl.org/SDL3/SDL_Condition .
  - [ ] SDL2
  - [x] SDL3
- **Misleading disclaimer:** Some types have _"THIS PAGE IS A WORK IN PROGRESS ... Please make edits to this page to improve it!"_, even when they do actually have a bit of documentation in them. An example being https://wiki.libsdl.org/SDL2/SDL_Renderer, which contains the documentation from https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_render.h#L138-L141 and also lists a number of relevant types. Example for SDL3: https://wiki.libsdl.org/SDL3/SDL_HapticSetGain . The category for these pages might be `CategoryDraft`.
  - [x] SDL2
  - [x] SDL3
- **Inconsistent formatting:** Some pages have inconsistent formatting relative to other pages, like https://wiki.libsdl.org/SDL2/SDL_Window.
  - [ ] SDL2
  - [x] SDL3
- **Pages with wiki warnings:** The page https://wiki.libsdl.org/SDL2/SDL_GetNumInputDevices has a warning about _"#!wiki warning The SDL_input.h header is incomplete and has been temporarily removed from the wiki. Please disregard this and related pages until this notice has been removed."_. Example for SDL3: https://wiki.libsdl.org/SDL3/CategoryInput . The most straightforward way to fix this may be to search in the Wiki GitHub repository on the search string "incomplete and has been temporarily", and handle each case manually: https://github.com/search?q=repo%3Alibsdl-org%2Fsdlwiki+incomplete+has+been+temporarily&type=code . Only 5 results as of this writing.
  - [x] SDL2
  - [x] SDL3
- [x] **Old pages from SDL2 that no longer exist in SDL3, for instance due to renaming:** One example is https://wiki.libsdl.org/SDL2/SDL_CondSignal in SDL2 which also has a page (as per 2024-04-09) in the SDL3 Wiki https://wiki.libsdl.org/SDL3/SDL_CondSignal , but the function was [renamed](https://github.com/libsdl-org/SDL/blob/c8a066019b686351afc614a44a2111111c42d697/include/SDL3/SDL_oldnames.h#L372) in SDL3 https://wiki.libsdl.org/SDL3/SDL_SignalCondition . This could presumably be fixed by manual removal, however, a lot of renaming was done: https://github.com/libsdl-org/SDL/blob/c8a066019b686351afc614a44a2111111c42d697/include/SDL3/SDL_oldnames.h .

The above issues may be relevant for both SDL 2 at https://wiki.libsdl.org/SDL2/FrontPage and SDL 3 at https://wiki.libsdl.org/SDL3/FrontPage.

Related:
- https://github.com/libsdl-org/SDL/pull/7528 , for category pages. There are two types of category pages, one by-name, one by-category.

**Comment by icculus** [comment]
For what it's worth, that thing was going to be daunting in any other language than Perl, too.

That being said, this was a _really_ good example of "I can fix this with regex" that got _wildly_ out of control.

If there's ever time, I would probably rewrite this as such:

- drop MediaWiki support.
- use a proper markdown parser to build an abstract syntax tree
- split the tree by sections for comparison between wiki/headers
- walk that syntax tree to output other formats, like manpages, clearly and cleanly.
- Probably drop Perl, since it scares everyone but me.  :)

**Comment by blaisemccourtney** [comment]
In theory, an alternative solution might be to switch back to Doxygen or some other general documentation generation tool. Though I would guess that you have good reasons for switching away from Doxygen and not picking a similar tool in the first place.

**Comment by icculus** [comment]
The documentation is bridged bidirectionally between the wiki and the headers, so Doxygen probably isn't a solution here.

**Comment by blaisemccourtney** [comment]
Bidirectional bridging is an interesting functionality to have. That editing a wiki page automatically somehowupdates the corresponding header in the source code is not a common feature to have in projects, in my experience. I would imagine that it makes it easier to get contributors to update the source code documentation. I do not know what the trade-offs are like in this case. Is bidirectional bridging and editing wiki->updates source code headers something that you have been very happy about, or have been needed?

**Comment by slouken** [comment]
Yes, we've been very happy that people can contribute via GitHub and automatically update the headers for public release.

**Comment by slouken** [comment]
I know that wikiheaders.pl is daunting, and I would suggest that you create a separate python script that autogenerates the category pages (and other documentation, potentially) and we can bring that into the process as well.

Thanks!

**Comment by blaisemccourtney** [comment]
> Yes, we've been very happy that people can contribute via GitHub and automatically update the headers for public release.

Well, people can always contribute via Github and to the headers for public release without a bidirectional bridge, it is just a bit easier with a bidirectional bridge.

> Actually, it looks like category generation is already partially implemented in https://github.com/libsdl-org/SDL/pull/7528. @icculus, can you take a look? It would be great to get this in for the 3.0 prerelease.

Is that PR for by-name listing, by-category listing, or both? I cannot really tell from the code.

**Comment by blaisemccourtney** [comment]
I believe that these are the version histories of syncing for the SDL 2 and SDL 3 pages of by-name listing, respectively:

- SDL 2 by-name listing: https://github.com/libsdl-org/sdlwiki/commits/main/SDL2/CategoryAPI.mediawiki
- SDL 3 by-name listing: https://github.com/libsdl-org/sdlwiki/commits/main/SDL3/CategoryAPI.mediawiki

Like the live pages, both of those ".mediawiki" files are missing `SDL_Surface` even though the wiki page for `SDL_Surface` exists for both SDL 2 and SDL 3.

The SDL 2 by-name listing was last updated 3 months ago.

The SDL 3 by-name listing was last updated more than a year ago, and its latest commit description contains something about cronjobs, though that commit touches many other files than just for CategoryAPI ("CategoryAPI" is the name for the by-name listing files).

**Comment by blaisemccourtney** [comment]
@slouken I think I understand what is happening now (after I learned a minuscule amount of Perl to prod and prick at things), and basically, the reason why `SDL_Surface` is not included in the by-name category is that the mediawiki/markdown page for `SDL_Surface` is never generated automatically.

No matter which system for the category pages are used, the category pages appear to rely on there being accurate information in the mediawiki/markdown pages in the `footer`. When going from the source to the wiki, the process might be as follows: For functions, this footer and other information is parsed from the header files (!!, C++ is not generally easy to parse!), and then categorized somehow. The information is also drawn from existing wiki pages. This is then written to the wiki pages. However, for types that are not functions, nothing is parsed. It was never implemented. So the information for non-function types, like `SDL_Surface`, nothing is gotten from the header files, and instead everything is just taken from the existing mediawiki file for `SDL_Surface`, and then written back again. This fits with the mediawiki file for `SDL_Surface` not having had any changes for 2 years: https://github.com/libsdl-org/sdlwiki/blob/main/SDL2/SDL_Surface.mediawiki . Since the categories in that file does not include `CategoryAPI`, the `SDL_Surface` wiki page is never included in the by-name listing.

This also means that, since non-function types are never parsed from the headers, the information in the headers and in the wiki can get arbitrarily out of sync. I have only investigated the direction from header-source to wiki. I do not know what the state of the script is for the other direction.

It would be solved if more non-function types are parsed (and documentation for the other direction is written?) . But the script is already long enough, and C++ is not at all among the easier languages to parse, even if you use proper parser techniques instead of regex (ab)use. I cannot in good conscience suggest anyone to add more parsing of C++ code using Perl regexes, especially to a Perl script that is already 1700+ lines long.

Some of the wiki pages will stay out of sync with the header code unless manually updated, namely the wiki pages for the non-function types, if my understanding of the scripts is correct.

I would personally have off-loaded the burden of parsing C++ for the sake of retrieving documentation, and the other documentation generation tasks, to Doxygen or Sphinx or some other documentation generator. Or maybe at least search for a Perl library or a library in a different language for parsing C++ comments.

I have not investigated the other direction, namely from wiki pages to header documentation.

**Comment by icculus** [comment]
Parsing C (let alone C++!) was never a goal; it looks for lines with a very specific format to identify function signatures, and would likely do the same for other things like structs, no matter what changes we make.

**Comment by blaisemccourtney** [comment]
My bad, I completely forgot that the project is purely C. And C should, despite `#include`, be much easier to parse than C++. Getting specific data structures out of the format is arguably still a kind of parsing, though, even if it is limited and does not parse all structures, only looking for some structures like type signatures and documentation comments. Using regexes for this purpose can be on the fragile side, but you have already mentioned that previously.

**Comment by blaisemccourtney** [comment]
@icculus I have searched on the net for Perl and Python libraries to parse C header files (or C programs in general), including documentation, but what I found either had not been maintained for years, or did not include comments. I then looked at Doxygen, and saw that it can generate XML output.

I have also looked at the parsing/extraction code in 'wikiheaders.pl', and it is fragile. I also looked at the formatting in the header files.

For functions, it can for instance look like this:

```c
/**
 * Get the name of the current camera driver.
 *
 * The returned string points to internal static memory and thus never becomes
 * invalid, even if you quit the camera subsystem and initialize a new driver
 * (although such a case would return a different static string from another
 * call to this function, of course). As such, you should not modify or free
 * the returned string.
 *
 * \returns the name of the current camera driver or NULL if no driver has
 *          been initialized.
 *
 * \threadsafety It is safe to call this function from any thread.
 *
 * \since This function is available since SDL 3.0.0.
 */
extern DECLSPEC const char *SDLCALL SDL_GetCurrentCameraDriver(void);
```
Which for the non-comment code is _relatively_ straightforward, and for the comment block

**Comment by blaisemccourtney** [comment]
The main problem I see with my proposal above is that user edits to non-function types to the wiki would be ignored or overwritten. I do not know what the best solution to that would be.

**Comment by icculus** [comment]
I'm curious to see if this works out, but you should be aware this sounds like a lot of work and there's no guarantee this is going to be accepted, since there are a lot of unknowns about this right now.

**Comment by blaisemccourtney** [comment]
@icculus You might be right about that. Do you have any specific unknowns in mind or that you know of, or is it more that this is uncharted territory and unanticipated issues may crop up? I am also uncertain myself about how a PR might pan out.

Do you have any other thoughts on this proposal? What about the issue in https://github.com/libsdl-org/SDL/issues/9236#issuecomment-1999539878 ?

**Comment by blaisemccourtney** [comment]
This article warns against using the SDL wiki, in _"Mistake 4: Using the SDL wiki for API documentation"_ : https://nullprogram.com/blog/2023/01/08/ .

**Comment by slouken** [comment]
This predates the wiki bridge for SDL3, and while there’s still lots of room for improvement, the wiki should be much better now.

**Comment by slouken** [comment]
The authors main point is that the headers are the authoritative documentation, which is completely true.

**Comment by blaisemccourtney** [comment]
@slouken Most or all of the sub-issues that I have listed in this issue also currently hold for the SDL3 wiki. And if wiki pages are never generated for non-function types, including for the SDL3 wiki, only generated for function types, then it would take a lot of continued work and effort, with a lot of room for errors, to maintain and keep both the SDL2 and SDL3 wikis up to date. Will the SDL3 wiki really ever get to a good state if wiki pages are not generated for non-function types?

And I can understand that the headers being authoritative is fine, but what I am used to for documentation in other libraries is that the API documentation is always up to date relative to the source documentation by being generated from the source header files or corresponding source files themselves, for instance by using tools like Doxygen. I understand that it is more difficult to create quality API documentation for languages like C or C++, and that some dislike Doxygen, and I could adapt if told clearly that the SDL2/SDL3 wiki pages are not in a good state. But for newcomers, they are currently presented indirectly as the main way of viewing API documentation, there is a clear box on the website with the header "Documentation", with a link to the SDL wiki. And the main wiki page for both SDL2 and SDL3 says *"This wiki is your portal to documentation and other resources for SDL 2.0."* (it actually currently says *"SDL 2.0"* also for the SDL3 wiki, it has not yet been updated: https://wiki.libsdl.org/SDL3/FrontPage ).

It is perhaps not surprising that the SDL2 and SDL3 wikis are not in a good state if the main developers of SDL do not use them, eating your own dog food and all that. And I am not asking you to begin using the SDL wikis. But it might be better for newcomers to present the wikis differently, like instead of presenting them as *"this wiki is your portal to documentation"*, then present the wikis as a "best effort", and instead clearly mention and link to the header source files.

**Comment by slouken** [comment]
All of your points are valid, I was just clarifying the author's position. I appreciate your digging into this. I think in the long run, we want the wiki documentation to be good quality and a good introduction to the API.

**Comment by blaisemccourtney** [comment]
@slouken That is reasonable. I am curious if you have any plans or ideas currently on how to get the wiki documentation into a good state, whether it is for SDL2 or SDL3. Without automatic generation of API documentation for the non-function types, my guess is that it will be tough getting the wiki to a good state overall, even in the long run. My proposal in a comment a few comments up would introduce automatic generation of API documentation for non-function types (there is already automatic generation of API documentation for function types currently) if successful, but it would also not have the bidirectional updates of the source (header to wiki & wiki to header), and having users edit a wiki page for a non-function type and then have those changes be thrown away silently during automatic generation is not optimal. I have some ideas on how to deal with that.

One idea would be that each wiki page for a non-function type is "split" into two sections in each page, one from automatic generation, and one manual and limited to the wiki (maybe put into the lower part of the page), and then users can edit the lower part and the upper part comes from automatic generation; this idea would not have bidirectional updating. You could call this idea "two-section wiki API pages".

Another idea would be more limited, just disable editing of non-function type wiki pages, to prevent users from wasting their time and effort, but having some wiki pages (specifically the API wiki pages for non-function types) not being editable would be less nice.

Both of those ideas suffer from the issue that it is inconsistent with the bidirectional updating of the function type wiki pages, which my proposal would not touch.

For both of those ideas, I think you could generate a link to the header file, and maybe even starting line number, where the header documentation is - but I think you could do that already now, honestly. Maybe a PR expanding the wikiheaders.pl script to also track the source header path (and maybe line numbers), and then generate a link in the corresponding wiki pages to the header source file (maybe with line number) in Github. But I am digressing from the topic at hand.

The bidirectional update functionality is neat, but it is probably complicated to implement for non-function types.

**Comment by icculus** [comment]
The wiki bridge now includes `#define`s, structs, unions, and enums, so we can have a much better reach with documentation now. Going through the contents of the wiki by hand is probably the next (extremely tedious) step, since there's a lot of cleaning that needs to be done.

The next tedious step after that is going through all the headers and making sure everything reasonable is documented.

**Comment by icculus** [comment]
The "Missing Links" bullet point is resolved now, for SDL2 and SDL3 (although SDL2 is likely to have a lot of missing pages when you click through).

Now function params and return values are listed on the page outside of the preformatted C code syntax section, generating wikilinks to `SDL_*` type names.

I'm pretty pleased with how this turned out, and doing this extremely basic parsing of the function signatures lets wikiheaders.pl validate \param and \returns lines, which brought up some errors to clean up.

**Comment by icculus** [comment]
The Work In Progress disclaimer was manually cleaned out of SDL2 and SDL3 a while ago, too.

Missing pages is almost complete for SDL3, and being tracked in a different bug.

I do not expect we will go back and write a lot of new documentation for SDL2, even for things that could be pasted from SDL3 (but I will merge PRs from others that want to do this work). We _are_ making sure wikiheaders continues to work with SDL2, so while the SDL2 pages are mostly pretty, consistent, functional and automated now, it's going to come down to a lot of documentation just simply not existing until someone writes the SDL2 version of it.

**Comment by icculus** [comment]
Okay, I think we're totally settled out for SDL3 now, and SDL2's janitorial work is done, but we're likely _not_ going to spend time improving SDL2's docs at this point (but will readily accept PRs that do), so I'm closing this. Thanks!
