### ISSUE TITLE
Different SDL.h header file on releases Windows and MacOS .framework?

### ISSUE THREAD

**Issue by DJLink** [libsdl-org/SDL#9237]
I'm probably missing something here and/or this is a dumb question.

I was updating an older project to newest SDL2 version. 2.30.1, on Windows and Mac, and I noticed that

https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL.h

![image](https://github.com/libsdl-org/SDL/assets/423769/c709aef5-5f73-4bb2-83ac-910f5a7c90bb)

Seems to be different from the header included in the Releases .dmg file for MacOS.

https://github.com/libsdl-org/SDL/releases/download/release-2.30.1/SDL2-2.30.1.dmg

Here the files have SDL2/ before each file, on Windows it doesn't?
![image](https://github.com/libsdl-org/SDL/assets/423769/d3bfd188-7682-461c-bd05-e24d8b7aa94c)

Any reason for this difference? Right now this new one breaks my includes in MacOS (but not Windows), I thought it could be related to now having SDL2 and 3, but then noticed that they files are different, so became confused.

**Comment by slouken** [comment]
Yes, because Apple frameworks require that you use the framework name in the include declaration. SDL3 has moved to requiring this for all platforms, for consistency. If you're not using it as a framework, you can build from source, which will create a dylib and the header layout you're expecting.
