### ISSUE TITLE
SDL_RenderPolygon's limit to the range 0 to 1 texture coordinates seems impractical and I don't get why it exists

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#9238]
I discovered by seeing geometry disappear under some conditions and then after checking the wiki page that SDL_RenderPolygon limits texture coordinates to 0-to-1 range. That seems like a problematic thing to do:

It doesn't seem beneficial even for software rendering, since the expectation of any rasterizer would be to modulo it to 0-to-1 anyway. If it's for performance and to avoid that modulo, you could have the render function check if it's in 0-to-1 range at the start of the draw call and branch into a software rasterizer version that can assume it's 0-to-1, and you'll basically have no performance loss for people that stick with your old limit. It also doesn't seem beneficial logistically, since texture coordinates outside 0-to-1 don't commonly constitute an error but valid use cases, so in most code bases it won't be a useful sanity check to make the users aware of.

And this limit blocks valid use cases, for example many models simply use a texture more repeatedly, so coordinates outside of 0-to-1 are fairly common. And splitting that up into sub polygons to work around that is not only not trivial (since the level of math required is similar to just hand-rolling your own rasterizer at which point why even bother to use SDL2?), but also simply tedious to implement even if you know how. Also, all 3d accelerate APIs don't really care about this limit so it has no obvious benefits on SDL2's side either.

Summed up, I suggest this limitation be removed! If someone ever gets around to it, of course.

Edit: I'm realizing now that maybe I interpreted the wiki page wrong :sweat_smile: I'll check real quick if this limit actually applies and it's not something else going on. Will close if I read it correctly, sorry! Will update in a few minutes with results...

**Comment by slime73** [comment]
#5369 

If the limit is lifted, then SDL will need to expose at least clamp and repeat wrap modes (like in the above PR) instead of always using a repeat wrap mode, otherwise people will run into unexpected behaviour – for example geometry that uses 0-1 texture coordinates can end up sampling texture pixels past the edges of the texture depending on what the vertex positions are, which results in visual artifacts with the repeat wrap mode.

**Comment by ell1e** [comment]
Okay, sadly I was able to confirm this in my opinion possibly destructive limit exists:

```
#include <SDL2/SDL.h>
#include <stdio.h>

int main(int argc, const char **argv) {
    SDL_Window *window = NULL;
    if (SDL_Init(SDL_INIT_VIDEO) < 0) return 1;
    const int w = 400;
    const int h = 500;
    window = SDL_CreateWindow("Test",
        SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
        w, h, SDL_WINDOW_SHOWN);
    if (window == NULL) return 1;
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);
    if (!renderer) return 1;

    SDL_Surface *srf = SDL_LoadBMP("test.bmp");
    SDL_Texture *tex = SDL_CreateTextureFromSurface(renderer, srf);

    while (1) {
        SDL_Event e;
        while (SDL_PollEvent(&e) != 0) {
            if (e.type == SDL_QUIT) {
                return 0;
            }
        }

        SDL_Vertex vertex_1 = {
            {0, 0},
            {255, 255, 255, 255},
            {-1, -1},
        };
        SDL_Vertex vertex_2 = {
            {w, 0},
            {255, 255, 255, 255},
            {3, -1},
        };
        SDL_Vertex vertex_3 = {
            {w, h},
            {255, 255, 255, 255},
            {3, 3},
        };
        SDL_Vertex vertices[] = {
            vertex_1,
            vertex_2,
            vertex_3
        };

        SDL_RenderGeometry(renderer, tex, vertices, 3, NULL, 0);

        SDL_Surface *srf = SDL_GetWindowSurface(window);
        SDL_RenderPresent(renderer);
    }
    return 0;
}
```
Expected result: Polygon shows up. I would even expect it to show up with seemingly nonsensical texture coordinates, e.g. all of them set to the same value resulting in a solid color. It should show up no matter what the coordinates are, with no exceptions other than maybe `NaN` or infinity.

Actual result: Nothing is visible, unless you edit the texture coordinates to be in the 0-to-1 range.

**Comment by ell1e** [comment]
Interesting point and I understand the concern over clamp modes. However, you could default to something like clamp to given coordinates if input coordinates were in range 0 to 1 to start with, otherwise sample past repeating points. I know this results in artifacts in some cases, but I think this is still highly preferable to the geometry just *not showing up at all*. I can't think of any use case where that is the preferred outcome.

**Comment by slime73** [comment]
> Actual result: Nothing is visible, unless you edit the texture coordinates to be in the 0-to-1 range.

`SDL_RenderGeometry` is returning an error result in your code, I think. So it's not silently failing at least.

> you could default to something like clamp to given coordinates if input coordinates were in range 0 to 1 to start with (which I assume is how it behaves now for that range), otherwise sample past repeating points and texture edges.

I think the approach in the above PR (having an explicit API that defaults to clamp) would feel more consistent to users, although personally I'd remove the error/UV range check in all cases if that's added.

**Comment by ell1e** [comment]
There is for sure nothing wrong with an explicit API, but if you wanted to backport the fix to SDL2 I just wanted to suggest how to do that without breaking API compatibility.

**Comment by slime73** [comment]
It's a new feature rather than a bug to be fixed, so I don't think any change would go into SDL2 and there wouldn't be a need for adding a compatibility mode.

sdl2-compat would just need to re-add the previous range check.

**Comment by ell1e** [comment]
It seems more like a bug to me, but fair enough. Reason being it renders the old API broken for some important use cases, e.g. rendering just arbitrary 3d models loaded up. While affine mapping and no z buffer also gets in the way of that in some way I suppose, it's not in a way where the model can't even show up in the first place.

**Comment by ell1e** [comment]
Did I spot correctly that `SDL_RenderPolygon` was entirely removed from SDL3? I guess that would be one way to solve it, albeit slightly radical.

**Comment by slime73** [comment]
There was never a SDL_RenderPolygon, the name is SDL_RenderGeometry.

**Comment by ell1e** [comment]
Oops my bad, I clearly got the names mixed up!

**Comment by slouken** [comment]
This limited has been lifted for SDL 3.0, thanks!
