### ISSUE TITLE
Permission dialog which ruins controller input is displayed on Android when plugging in a USB controller

### ISSUE THREAD

**Issue by leonstyhre** [libsdl-org/SDL#9241]
Hi

I have found a strange SDL problem on Android, when plugging in a USB controller there is a popup displayed where the user is expected to give permissions to access the controller. However accepting this will lead to emulators launched from my app (ES-DE) having no access to the controller. So it seems like SDL is taking exclusive ownership of the controller. However if the user presses "CANCEL" in this dialog then everything will work correctly and emulators will have access to the controller as well.

I don't understand the purpose of the dialog in the first place since it's not needed for controller input to work in my app. What I've done to work around this is commenting out the call to connectHIDDeviceUSB() in HIDDeviceManager.java:

```
    private void handleUsbDeviceAttached(UsbDevice usbDevice) {
        // connectHIDDeviceUSB(usbDevice);
    }
```

This gets rid of the dialog altogether and everything is working fine. I've put this into production and it's been tested by a lot of people and seems to work perfectly. I could find no other way to disable the dialog except this, changing things in AndroidManifest.xml did not have any effect.

I absolutely have no idea why the above code change worked, I just figured out that this was causing the issue through a lot of trial and error.

Thanks!

**Comment by slouken** [comment]
Exclusive access to the device allows control of rumble and LEDs on the DualSense controller, for example. We could turn that into a hint however, if your application doesn't need or want that level of control.

**Comment by leonstyhre** [comment]
Thanks for the info, yes that sounds like a good idea. And ES-DE does not need this functionality so setting a hint would be better than commenting out the method altogether.

But maybe something worth considering would be to always release the exclusive access on onPause() or onStop() and recapture it on onResume() ? Otherwise any SDL app using a controller in exclusive mode would prevent any other app or game from accessing it which would normally not be what you want. Although I don't know if this proposal is even technically doable.

**Comment by AntTheAlchemist** [comment]
Or better still, if possible, add a couple of SDL methods to capture and release. That way it can be handled in-app?

**Comment by leonstyhre** [comment]
Yes that's even better, you could then just call them on onPause() and onResume(). Again assuming it works like that, because it would not be very nice to have the popup getting displayed every time your app is resumed for example.

**Comment by slouken** [comment]
The hint is easy to implement, though it would have to be set before SDL_Init().

Dynamically releasing and reacquiring the device is more difficult and might involve triggering hotplug disconnect/reconnect for the controller, and might impact other applications that don't support hotplug anyway. If you think that's worthwhile, feel free to submit a PR that implements that on pause/stop so we can try it out.

**Comment by AntTheAlchemist** [comment]
> Dynamically releasing and reacquiring the device is more difficult

That's what I suspected; let's not go there. Let's just stick to the hint before `SDL_Init`.

**Comment by AntTheAlchemist** [comment]
Couple of quick questions: does this exclusive mode affect platforms other than Android? And to confirm; the exclusive mode is released on `SDL_Quit` ?

**Comment by leonstyhre** [comment]
For me the hint is enough, I don't need exclusive access to the device. And it's fine to set it before SDL_Init() as well. Thanks!

**Comment by slouken** [comment]
If you add this before your SDL_Init(), does that fix it?
```c
SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI, "0");
```

**Comment by leonstyhre** [comment]
Yes that fixes it, the popup is no longer displayed! But isn't this hint disabling a lot more than only exclusive access to the controller?

**Comment by slouken** [comment]
Well yes, it disables everything that comes with exclusive access to the controller. :)
But if you don't need that, then this is the hint for you.

**Comment by leonstyhre** [comment]
Aha, so it will not disable support for certain controllers or anything like that?

In this case I guess you can close the issue as there is already a solution in place, sorry I had no idea this hint would have this effect :)

**Comment by slouken** [comment]
No worries. I went ahead and disabled it by default on Android, on the principle of least surprise. :)

Thanks!

**Comment by slouken** [comment]
FYI, it does disable support for controllers that SDL knows how to handle but Android doesn't, but such is the price of convenience.

**Comment by leonstyhre** [comment]
Do you mean that the hint does that, or does commenting out the call to connectHIDDeviceUSB() as I did also limit controller support as well? Or in other words, would setting this hint to 0 give the exact same result as commenting out that line?

**Comment by slouken** [comment]
Yep, they would have the same result.

**Comment by leonstyhre** [comment]
Ok, thanks for clarifying!
