### ISSUE TITLE
cmake file can't be used without a C++ compiler

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#9244]
the CMakeLists.txt does a lot of testing of C++ compiler, and fails if it can't find one, even though SDL2 is (thank god) written in C.
it should be changed to detect if a C++ compiler is available, and only then do the optional testing. or even better, remove anything C++ related.

**Comment by sezero** [comment]
>  or even better, remove anything C++ related.

Not possible, but a C++ compiler is needed for a few targets only
(haiku and winrt, as far as I remember, maybe one or two more?..)
Maybe we can limit C++ compiler detection to those targets only??

CC: @madebr

**Comment by madebr** [comment]
Fixed in b5eb704fa
Android, Haiku and UWP need a c++ compiler.
Xbox One and Xbox Series also need it, but those platforms don't have CMake support (yet).

**Comment by rofl0r** [comment]
wow, that was quick. thanks!

**Comment by rofl0r** [comment]
oh, i actually need this for the SDL2 branch. any chance to apply the diff tehre too ?

**Comment by madebr** [comment]
SDL2's cmake script is not too different: 318493695
