### ISSUE TITLE
PSP joystick polling happens not frequently enough

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#9245]
on PSP, you often have to press a button for about a second so SDL notices the change. if you hit it shortly, it is often not noticed at all and no event fired.

i've tried upping the polling rate in the thread created by psp/joystick.c and also the one of PSP_pumpevents without avail. can't figure out where SDL_JoystickUpdate() is being called from, which seems to be the only place calling driver->update().

the thread created by psp/SDL_sysjoystick.c seems superfluous, the vita code doesn't use it either. the tiny code snippet in the callback function would be better suited inside the main updatejoystick function.

**Comment by rofl0r** [comment]
ok, the thread was already removed in 2b41f497db5f5f98ee4f355c9cadfea3b169f969 , but still with current HEAD of SDL2 branch the problem persists

**Comment by rofl0r** [comment]
maybe @sharkwouter has an idea where SDL_UpdateJoystick()  is supposed to be called from ?

**Comment by rofl0r** [comment]
> ok, the thread was already removed in https://github.com/libsdl-org/SDL/commit/2b41f497db5f5f98ee4f355c9cadfea3b169f969 , but still with current HEAD of SDL2 branch the problem persists


hmm, that commit fixed the issue too on real hardware, now it's only PPSSPP that doesnt detect short keypresses.

**Comment by sharkwouter** [comment]
Okay, thanks for updating. I would personally use the gamepad API. It's easier to use and works more consistently. I don't know if that fixes the issue in PPSSPP, though.

Here is an example of how input is processed in OceanPop: https://github.com/sharkwouter/oceanpop/blob/master/src/EventManager.cpp

**Comment by rofl0r** [comment]
i've been testing the sceCtrlReadLatch function and it seems to work best in that it mimics "keyrepeats" that SDL only provides for keyboard events. i was able to circumvent that issue though by creating a timer that fires its own events every 25 ms after a button was pressed and not yet released. it's nicer to be able to use pure SDL code for everything, so also the "desktop version" of the app behaves identical. thanks for your link, reading it now.

**Comment by sharkwouter** [comment]
If something doesn't work like on desktop on real hardware then that's a bug. I've never used that function, though.
