### ISSUE TITLE
SDL_LEAN_AND_MEAN CI build?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9249]
It's pretty easy to break builds that define SDL_LEAN_AND_MEAN. Can we add one to CI just to verify that we haven't broken that? Platform and toolchain doesn't matter, it should be whatever GitHub can spin up and build the fastest.

**Comment by ericoporto** [comment]
> Platform and toolchain doesn't matter

It does, there is no build issues in Ubuntu currently but you can trigger them with Android, so building on top of Android existing ci for it as done by @madebr is the way to go, as it will give you better coverage. :)

**Comment by madebr** [comment]
Ubuntu/Linux fails also.
There is currently a difference between configuring CMake with `-DSDL_LEAN_AND_MEAN=1` (this does nothing) and configuring with `-DCMAKE_C_FLAGS="-DSDL_LEAN_AND_MEAN=1"`.
