### ISSUE TITLE
 [Windows:MSVC] building error with static SDL bug reappeared

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#9255]
#5156 [[Windows:MSVC] building error with static SDL](https://github.com/libsdl-org/SDL/issues/5156) bug has reappeared after pull on latest commit.

> Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2268	'memmove' is a compiler predefined library helper. Library helpers are not supported with /GL; compile object file '..\build\win-x64-release\src\build\sdl\sdl3-static.dir\release\sdl_memmove.obj' without /GL.

**Comment by sandsc** [comment]
error can be fixed by turn INTERPROCEDURAL_OPTIMIZATION off
`set_target_properties(SDL3-static PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF)`

**Comment by madebr** [comment]
To conclude this, combining `SDL_LIBC=OFF` with ltcg is not supported.
