### ISSUE TITLE
Gamepad is mapped incorrectly

### ISSUE THREAD

**Issue by kotenok2000** [libsdl-org/SDL#9265]
When sdl maps Defender Omega gamepad with driver[Driver for Challenge Mini LE, Cobra R4, Omega, Glyder (VID_0079&PID_0006, Win XP / VISTA / 7 / 8 /10) (310.3 Кб)](https://defender.ru/data/files/20141105/841e1588.zip) from https://defender.ru/catalog/gamepads-16/omega-usb-12-buttons-2-sticks it is detected  as Sanwa Supply JY-P76USV and maps SDL-0/A to button 1, SDL-0/B to button 2, SDL-0/X to button 3, and SDL-0/Y to button 4
instead of correct way of mapping Y to 1, B to 2, A to 3, and X to 4
![image](https://github.com/libsdl-org/SDL/assets/8822292/db69628e-cd6c-4bb4-a8cf-504761d312d8)
![image](https://github.com/libsdl-org/SDL/assets/8822292/54a59004-fa02-462b-a7d9-433289e47060)
![image](https://github.com/libsdl-org/SDL/assets/8822292/55d4bf06-ff2c-4ba7-b515-c86e66ad58d3)

![image](https://github.com/libsdl-org/SDL/assets/8822292/3d8cdbe3-ace0-4819-864b-6b8880a4fcf1)

**Comment by AntTheAlchemist** [comment]
The same thing happens with the G-Shark. Did this happen due to ccd309c ?

**Comment by slouken** [comment]
I've fixed it so the Sanwa mapping isn't used for other controllers. You can use the SDL testcontroller program to generate a new mapping for this controller.

**Comment by kotenok2000** [comment]
it also inverts right stick horizontally and vertically.


I have made a new mapping

'03000000790000000600000000000000,G-Shark GS-GP702,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2~,righty:a3~,lefttrigger:b6,righttrigger:b7,'

**Comment by kotenok2000** [comment]
03000000790000000600000000000000,G-Shark GS-GP702,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2~,righty:a3~,lefttrigger:b6,righttrigger:b7,

**Comment by slouken** [comment]
This mapping doesn't have a CRC. Can you please use testcontroller from the SDL repo to create it?

**Comment by kotenok2000** [comment]
Where is it?

**Comment by slouken** [comment]
Do you need a pre-built Windows binary?

**Comment by kotenok2000** [comment]
Yes.

**Comment by slouken** [comment]
Try this:
http://www.libsdl.org/tmp/testcontroller.zip

Once you set up the mapping you can use the button to copy it to the clipboard and paste it here.

**Comment by kotenok2000** [comment]
03007ac7790000000600000000000000,Defender Joystick Cobra R4,crc:c77a,platform:Windows,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2~,righty:a3~,start:b9,x:b3,y:b0,

First time i used gamepad-tool from https://generalarcade.com/gamepadtool/

**Comment by slouken** [comment]
This is added for the next release, thanks!
