### ISSUE TITLE
The rawinput joystick driver APIs latency seems to be tied to the main message poll rate (windows 2.30.0)

### ISSUE THREAD

**Issue by not-magic** [libsdl-org/SDL#9270]
Here is a sample app that highlights what is going on:

```
#include <SDL2/SDL.h>

struct ThreadData {
	SDL_GameController *game_controller = nullptr;
};

int InputThread(void *data) {
	auto& thread_data = *reinterpret_cast<ThreadData*>(data);

	auto last_time = SDL_GetPerformanceCounter();

	Uint16 last_result = 0;

	const auto ticks_per_msec = SDL_GetPerformanceFrequency()/1000;

	while (true) {

		SDL_GameControllerUpdate();

		if (SDL_GameControllerGetButton(thread_data.game_controller, SDL_CONTROLLER_BUTTON_A)) {
			auto current_time = SDL_GetPerformanceCounter();

			const Uint16 current_result = SDL_GameControllerGetAxis(thread_data.game_controller, SDL_CONTROLLER_AXIS_LEFTX) ^
					SDL_GameControllerGetAxis(thread_data.game_controller, SDL_CONTROLLER_AXIS_LEFTY);

			if (current_result != last_result) {
				printf("GP Rate %lld ms\n", (current_time - last_time)/ticks_per_msec);
				last_result = current_result;
				last_time = current_time;
			}
		}

		if (auto *joystick = SDL_GameControllerGetJoystick(thread_data.game_controller)) {

			auto button_index = SDL_GameControllerGetBindForButton(thread_data.game_controller, SDL_CONTROLLER_BUTTON_X);
			auto left_x_axis = SDL_GameControllerGetBindForAxis(thread_data.game_controller, SDL_CONTROLLER_AXIS_LEFTX);
			auto left_y_axis = SDL_GameControllerGetBindForAxis(thread_data.game_controller, SDL_CONTROLLER_AXIS_LEFTY);

			if (SDL_JoystickGetButton(joystick, button_index.value.button)) {

				auto current_time = SDL_GetPerformanceCounter();

				const Uint16 current_result = SDL_JoystickGetAxis(joystick, left_x_axis.value.axis) ^
						SDL_JoystickGetAxis(joystick, left_y_axis.value.axis);

				if (current_result != last_result) {
					printf("JS Rate %lld ms\n", (current_time - last_time)/ticks_per_msec);
					last_result = current_result;
					last_time = current_time;
				}

			}
		}		

		if (SDL_GameControllerGetButton(thread_data.game_controller, SDL_CONTROLLER_BUTTON_START)) {
			printf("Goodbye\n");
			SDL_Event quit_event{};
			quit_event.type = SDL_QUIT;
			SDL_PushEvent(&quit_event);
			return 0;
		}

		SDL_Delay(4);
	}

	return 0;
}

int SDLMAIN_DECLSPEC SDL_main(int argc, char* argv[]) {

	if (SDL_Init(SDL_INIT_EVENTS|SDL_INIT_GAMECONTROLLER|SDL_INIT_VIDEO) != 0) {
		printf("SDL Init failed :%s\n", SDL_GetError());
		return -1;
	}

	ThreadData thread_data;
	thread_data.game_controller = SDL_GameControllerOpen(0);

	if (!thread_data.game_controller) {
		printf("Unable to open SDL controller\n");
		return -1;
	}

	printf("Usage:\n\tHold X and wiggle the left stick to test joystick API sample rate.\n\tHold A and wiggle the left stick to test the game controller sample rate.\n\tPress Start to exit\n");

	auto *input_thread = SDL_CreateThread(&InputThread, "Input", &thread_data);

	SDL_GameControllerEventState(SDL_IGNORE);
	SDL_JoystickEventState(SDL_IGNORE);

	SDL_Event event{};

	bool is_running = true;

	while (is_running) {

		while (SDL_PollEvent(&event)) {

			if (event.type == SDL_QUIT) {
				is_running = false;
			}
		}

		SDL_Delay(100);
	}

	SDL_WaitThread(input_thread, nullptr);

	SDL_Quit();
	return 0;
}
```

If you run it and hold X or A and wiggle the left stick it can only ever poll input once ever 100ms, the rate of the main SDL_PollEvent. Furthermore input doesn't update at all unless you pass SDL_INIT_VIDEO to the init flags.

Doing some debugging it looks like it may be a result of having the raw input driver being preferred, which is updated via wndproc.

This seems counter to what I would assume here, where `SDL_GameControllerUpdate` would update the controller state.

**Comment by not-magic** [comment]
I should mention this is with an XB1 controller plugged in via USB

**Comment by not-magic** [comment]
Ok I just found `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");` and this indeed works around it. It also fixes the need for SDL_INIT_VIDEO.

**Comment by AntTheAlchemist** [comment]
Have a look at `SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");`

**Comment by petrutoader** [comment]
Can confirm we also have this bug. `SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");` does not fix it for us. Only `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");` does indeed fix it.

Currently testing reports from our users that SDL2@2.28.5 did not face this issue.

**Comment by petrutoader** [comment]
We rolled back to 2.24.0 and everything works fine. Works on the latest version with `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");` but I'm hesitant to push a hotfix with that hint. No luck in setting any other hints.

**Comment by CasualPokePlayer** [comment]
The main issue here is that you inited SDL_INIT_GAMECONTROLLER on the main thread. This means the RAWINPUT window is created on the main thread (see SDL_CreateDeviceNotification in SDL_windowsjoystick.c), which then would normally only be updatable on the main thread (windows message queues are more or less thread local).

SDL_HINT_JOYSTICK_THREAD should normally prevent this issue, as it would delegate the window creation to a separate thread. Not sure why it reportedly doesn't work (did you make sure to set the hint before calling SDL_Init?).

An alternative way to fix this is to do the first call of SDL_INIT_GAMECONTROLLER on your input thread, which would then create the window on that thread. However, this would then require you to implement a standard windows message pump loop since you wouldn't want to call SDL event functions within that thread.

**Comment by not-magic** [comment]
Using SDL_HINT_JOYSTICK_THREAD does work for my use case. I'm going to close it because I [petrutoader](https://github.com/petrutoader) must have a different issue.
