### ISSUE TITLE
Window Creation and Resizing in Tiling Window Managers (e.g., sway)

### ISSUE THREAD

**Issue by KairuiLiu** [libsdl-org/SDL#9271]
I'm encountering issues when using SDL with tiling window managers, specifically sway. I've identified a few key issues and have a question regarding window management behavior in these environments. Here are the details:

1. **Resizing in sway may fail**
   When creating a window with dimensions 0x0 and then resizing it, it seems to cause problems in a sway environment. Specifically, the following assertion failure occurs:

   ```
   sway: render/pass.c:33: wlr_render_pass_add_texture: Assertion `box->x >= 0 && box->y >= 0 && box->x + box->width <= options->texture->width && box->y + box->height <= options->texture->height' failed.
   ```

   This issue is similar to what has been discussed in the context of the scrcpy project (https://github.com/Genymobile/scrcpy/issues/4760#issuecomment-1999550347).

2. **Inability to Obtain Real Dimensions in Tiling Window Managers:**
   In tiling window managers, attempts to resize the window seem to be ineffective, and obtaining the real dimensions of the window appears impossible. We tried to resize in a tiling window manager and then obtain the window size. We found that even if the window size has not changed, we could only get the values we had previously set (https://github.com/Genymobile/scrcpy/issues/4760#issuecomment-1999925658).

3. **Detecting the Presence of a Tiling Window Manager:**
   Is there a recommended approach or mechanism within SDL for detecting whether the application is running under a tiling window manager? This information could be crucial for dynamically adjusting application behavior to accommodate the specifics of tiling window manager environments.

**Comment by Kontrabant** [comment]
1. Sounds like this bug in wlroots https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3766
2. In Wayland, changing the window size programmatically only initially changes the reported size.  A frame with the new dimensions actually has to be committed before the window will be visibly resized.
3. Wayland has no way of doing this, and there is no way to do this via SDL. Checking the `XDG_CURRENT_DESKTOP` envvar against a list of tiling window managers is the only thing you could do.

**Comment by KairuiLiu** [comment]
Thanks :smile:
