### ISSUE TITLE
CMake build from source depends on .git

### ISSUE THREAD

**Issue by Eric-Arz** [libsdl-org/SDL#9274]
I am trying to integrate the SDL3 source code as a vendored library into my CMake project like i used to do with SDL2.

It seems like something changed and building SDL3 with CMake now for some reason relies on the .git folder to be present (which you dont get when you download the source from github)

```
[cmake] CMake Error: File C:/xxx/sdl/.git/packed-refs does not exist.
[cmake] CMake Error at build/lib/sdl/CMakeFiles/git-data/grabRef.cmake:29 (configure_file):
```

When cloning the repo with git clone (.git now present) the build succeeds, but then the vendored SDL3 source code obviously gets ignored by the outer git repository because of it now being a git repository itself.

I am using Windows 11

**Comment by icculus** [comment]
CC @madebr

**Comment by madebr** [comment]
How do you configure the CMake project?
Can you post a short reproducer + post more error context?
On Linux, the following succeeds:
```
cd /tmp
rm -rf main.zip SDL-main SDL-build
wget https://github.com/libsdl-org/SDL/archive/refs/heads/main.zip
unzip main.zip
cmake -S SDL-main -B SDL-build -GNinja --fresh
cmake --build SDL-build
```

The `.git` directory is accessed [here](https://github.com/libsdl-org/SDL/blob/2f13f66c71d11115381ea6bbdece4bcdec252584/CMakeLists.txt#L2915-L2921) to build a `SDL_REVISION` string.

But thinking about it, perhaps we should only access `.git` when `SDL-root/.git` exists.
This would also make it possible to [eliminate the configurability of `SDL_REVISION`](https://github.com/libsdl-org/SDL/pull/8030).

**Comment by Eric-Arz** [comment]
```
cmake_minimum_required(VERSION 3.24)

project(engine C)

# C standard
set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)

set(SOURCES
    src/main.c
)

set(LIBRARY_OUTPUT_PATH "${CMAKE_BINARY_DIR}")
set(EXECUTABLE_OUTPUT_PATH "${CMAKE_BINARY_DIR}")

add_subdirectory(${CMAKE_SOURCE_DIR}/lib/sdl EXCLUDE_FROM_ALL)

add_executable(${PROJECT_NAME} ${SOURCES})

target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3)
```

**Comment by Eric-Arz** [comment]
i tried it again today and now it works as ist should, maybe i just downloaded a bad commit?

**Comment by madebr** [comment]
Nothing related to revision hashes has been changed.
So I don't know what happened here.

If you can reproduce it, please re-run configure with `--trace` (and/or `--trace-expand`)  and share the logs here.
Also try configuring in a clean build folder (or pass `--fresh` to cmake at configure time).
