### ISSUE TITLE
Error when building Android app.

### ISSUE THREAD

**Issue by cheyao** [libsdl-org/SDL#9275]
I'm trying to build a android app (The test file `test/testgles.c`) using sdl, and I'm currently following the guide in `docs/README-android.md`. But I've encountered this problem:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Task with path 'externalNativeBuildDebug' not found in project ':app'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

Does anyone know how to fix this? Googling yields nothing.

I'm on macos 11.

**Comment by madebr** [comment]
I succesfully created a new Android project with the command below, which I could open with Android Studio.
```
ANDROID_HOME=~/AndroidANDROID_NDK_HOME=~/Android/Sdk/ndk/26.0.10792818  build-scripts/androidbuild.sh org.libsdl.testgles test/testgles.c
```

I had to modify `build/org.libsdl.testgles/app/jni/src/Android.mk` slightly:
```diff
-LOCAL_SHARED_LIBRARIES := SDL3
+LOCAL_SHARED_LIBRARIES := SDL3_test SDL3
```

**Comment by cheyao** [comment]
Thanks! I successfully compiled the test app!
