### ISSUE TITLE
 [Request] Add SDL3 Package to Vcpkg

### ISSUE THREAD

**Issue by mohitsainiknl** [libsdl-org/SDL#9277]
The SDL3 package is currently unavailable in Vcpkg. As my project utilizes Vcpkg for dependency management, we have encountered challenges when attempting to migrate to SDL. Despite its widespread use and importance in our development workflow, SDL3 is conspicuously absent from the Vcpkg repository.

**Comment by madebr** [comment]
SDL3 has not been released yet, so there's nothing for them to package.
As soon as a release happened, you/somebody can create a sdl3 package at the vcpkg repo.
[The sdl2 package](https://github.com/microsoft/vcpkg/tree/master/ports/sdl2) can act as a starter.

**Comment by madebr** [comment]
vcpk has an issue already for tracking sdl3 [here](https://github.com/microsoft/vcpkg/issues/37162)
