### ISSUE TITLE
Add new SDL_WindowFlags for fullscreen windowed

### ISSUE THREAD

**Issue by R0cketboy** [libsdl-org/SDL#9280]
Sorry if im not supposed to propose changes like this, im new to GIT.

So, im proposing that instead of having to do this to create a fullscreen windowed window:
window = SDL_CreateWindow(...SDL_WINDOW_RESIZABLE);
SDL_MaximizeWindow(window);

We could have a SDL_WindowFlags that does the same thing like this: SDL_WINDOW_FULLSCREEN_WINDOWED

**Comment by Kontrabant** [comment]
You can already create a window with the SDL_WINDOW_MAXIMIZED flag, and it will immediately become maximized.

**Comment by R0cketboy** [comment]
> You can already create a window with the SDL_WINDOW_MAXIMIZED flag, and it will immediately become maximized.

My bad, maximized lost itself in translation hahaha
