### ISSUE TITLE
See also, in SDL3 headers?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9282]
We’re inconsistent in what other functions are referenced in the \sa block in the headers.

For SDL3 we should probably standardize what we link to.

Here are some options:
* Nothing - we could entirely rely on browsing the header or the content pages on the wiki for related content.
* Closely related functions only - variants of the current function, functions that are likely to be used together as part of user flow, etc.
* All functions in the same group, e.g. all joystick functions link to all other joystick functions.

SDL has leaned towards the second option but there’s a lot of gray area in choosing closely related functions, so I wanted to get people’s thoughts? @libsdl-org/a-team?

**Comment by icculus** [comment]
The second option. "Here's a SHORT list of other things that are interesting to what you are reading right now." An Open function should reference a Close function, etc, but it's hard to
pin down exact rules for this.

In theory, in the headers you already have a list of all functions in the same group (it's the same header file!), and in the wiki there should be a category link.
