### ISSUE TITLE
test project "testautomation" doesn't build with build-type "MinSizeRel"

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9284]
All other build-types(Debug, RelWithDebInfo, Release) compile and link this and all other test projects without errors.

System Specs:
Kernel: Linux 6.7.9-zen1-1-zen
OS: Arch Linux x86_64
DE: Plasma 6.0.2
WM: kwin
Wayland
Compiler: gcc 13.2.1

Command used to build:
```
cmake --fresh -S SDL_repo/ -B SDL_build/ -D CMAKE_BUILD_TYPE=MinSizeRel -D SDL_TESTS=YES
cmake --build SDL_build/
```

Error message:
```
[ 66%] Building C object test/CMakeFiles/testautomation.dir/testautomation.c.o
[ 66%] Building C object test/CMakeFiles/testautomation.dir/testautomation_audio.c.o
[ 66%] Building C object test/CMakeFiles/testautomation.dir/testautomation_clipboard.c.o
[ 67%] Building C object test/CMakeFiles/testautomation.dir/testautomation_events.c.o
[ 67%] Building C object test/CMakeFiles/testautomation.dir/testautomation_guid.c.o
[ 67%] Building C object test/CMakeFiles/testautomation.dir/testautomation_hints.c.o
[ 67%] Building C object test/CMakeFiles/testautomation.dir/testautomation_images.c.o
[ 67%] Building C object test/CMakeFiles/testautomation.dir/testautomation_intrinsics.c.o
[ 67%] Building C object test/CMakeFiles/testautomation.dir/testautomation_iostream.c.o
[ 68%] Building C object test/CMakeFiles/testautomation.dir/testautomation_joystick.c.o
[ 68%] Building C object test/CMakeFiles/testautomation.dir/testautomation_keyboard.c.o
[ 68%] Building C object test/CMakeFiles/testautomation.dir/testautomation_log.c.o
[ 68%] Building C object test/CMakeFiles/testautomation.dir/testautomation_main.c.o
[ 68%] Building C object test/CMakeFiles/testautomation.dir/testautomation_math.c.o
[ 69%] Building C object test/CMakeFiles/testautomation.dir/testautomation_mouse.c.o
[ 69%] Building C object test/CMakeFiles/testautomation.dir/testautomation_pen.c.o
[ 69%] Building C object test/CMakeFiles/testautomation.dir/testautomation_pixels.c.o
[ 69%] Building C object test/CMakeFiles/testautomation.dir/testautomation_platform.c.o
[ 69%] Building C object test/CMakeFiles/testautomation.dir/testautomation_properties.c.o
[ 69%] Building C object test/CMakeFiles/testautomation.dir/testautomation_rect.c.o
[ 70%] Building C object test/CMakeFiles/testautomation.dir/testautomation_render.c.o
[ 70%] Building C object test/CMakeFiles/testautomation.dir/testautomation_sdltest.c.o
[ 70%] Building C object test/CMakeFiles/testautomation.dir/testautomation_stdlib.c.o
[ 70%] Building C object test/CMakeFiles/testautomation.dir/testautomation_subsystems.c.o
[ 70%] Building C object test/CMakeFiles/testautomation.dir/testautomation_surface.c.o
[ 71%] Building C object test/CMakeFiles/testautomation.dir/testautomation_timer.c.o
[ 71%] Building C object test/CMakeFiles/testautomation.dir/testautomation_video.c.o
[ 71%] Linking C executable testautomation
/usr/bin/ld: CMakeFiles/testautomation.dir/testautomation_math.c.o: undefined reference to symbol '__fpclassify@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/testautomation.dir/build.make:516: test/testautomation] Error 1
make[1]: *** [CMakeFiles/Makefile2:637: test/CMakeFiles/testautomation.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

Seems like the test project testautomation doesn't link to the C-math library for the build-type MinSizeRel.

**Comment by madebr** [comment]
We currently don't link `testautomation` to any at all.
Replacing
https://github.com/libsdl-org/SDL/blob/1bab87399fde8b6f0f98ccf641c8473b3d929a5d/test/testautomation_math.c#L28
with 
```c
#define IS_INFINITY(V) isinf(V)
```
fixes the link error for me (on Linux).

**Comment by Sackzement** [comment]
Yes, this fixes it.

On my system the default build, with just setting the build-type and with test, links `SDL` and `testautomation` to `libm`.
I'm curious why the build-type `MinSizeRel` didn't link `testautomation` to `libm`.

Here are the dependencies of both targets(without version numbers and addresses):
SDL:
```
ldd my_build_dir/Release/libSDL3.so
	linux-vdso.so
	libm.so
	libc.so
	/usr/lib64/ld-linux-x86-64.so
```
testautomation:
```
ldd build_dir/Release/test/testautomation
	linux-vdso.so
	libSDL3.so
	libunwind.so
	libc.so
	libm.so
	/lib64/ld-linux-x86-64.so
	liblzma.so
```

**Comment by Sackzement** [comment]
@madebr thanks for the fast fix :)

**Comment by Sackzement** [comment]
Quick follow-up:

Before the fix, when building `SDL` with test-projects and the build-type `MinSizeRel`, on my system the test project `testautomation` in fact did link to `libm` but somehow couldn't find the function `fpclassify`.

My system defaults to building  `SDL` with 'libc' and 'libm' as dependencies, which would be the same as:
```cmake -DCMAKE_BUILD_TYPE=<build-type> -DSDL_LIBC=YES <SDL_repo>```
and the `SDL` dependencies were:
```
linux-vdso.so
libm.so
libc.so
ld-linux-x86-64.so
```
Now I'm building with ```cmake -DCMAKE_BUILD_TYPE=<build-type> -DSDL_LIBC=NO <SDL_repo>```
and the dependencies are:
```
linux-vdso.so
libc.so
ld-linux-x86-64.so
```
So no more math library. Yay!

I did some comparisons, building `SDL` with `-DSDL_LIBC=YES` and with `-DSDL_LIBC=NO`:
|build-type|build-time/file-size|`-DSDL_LIBC=YES`|`-DSDL_LIBC=NO`|
|---|---|---|---|
|`Debug`|build-time|35.573 seconds|24.990 seconds|
|`Debug`|file-size|9,762,824 bytes|9,281,096 bytes|
|`RelWithDebInfo`|build-time|1:01.17 minutes|50.223 seconds|
|`RelWithDebInfo`|file-size|11,572,432 bytes|10,816,416 bytes|
|`Release`|build-time|1:03.62 minutes|52.222 seconds|
|`Release`|file-size|3,155,232 bytes|2,843,528 bytes|
|`MinSizeRel`|build-time|50.932 seconds|39.594 seconds|
|`MinSizeRel`|file-size|2,195,536 bytes|1,986,760 bytes|

When building with `-DSDL_LIBC=NO` the file-size is a bit smaller and the build-time is much faster(~10 seconds).
Really nice to see.
