### ISSUE TITLE
Add SDL_GlobDirectory()

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9287]
Maybe we leave the callback API but also add:
```c
char **SDL_GlobDirectory(const char *path, const char *pattern);
```

`path` is a directory, `pattern` allows '*' and '?' wildcards within that directory (NULL means "don't filter, return everything"). Returns an array that you free with a single SDL_free: all the string pointers point into memory allocated in the same block as the array itself.

Internally, this uses the callback, where it filters out things that don't match the pattern.

Makes implementations easy, gives an easy public API with an added feature of pattern matching, and leaves the original for apps that prefer to drink straight from the firehose.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/pull/9276#discussion_r1527532299_

**Comment by icculus** [comment]
I'm taking a run at this one tonight or tomorrow.

**Comment by slouken** [comment]
I'm adding SDL_IOFromDynamicMem(), which might be helpful for assembling a list of variable length strings to pass back as a single freeable buffer. :)

**Comment by slouken** [comment]
I'm heading out to dinner, but feel free to merge and use it if CI passes.

**Comment by 0x1F9F1** [comment]
FWIW I found this article really useful when I had to implement a glob function a while ago https://www.codeproject.com/Articles/5163931/Fast-String-Matching-with-Wildcards-Globs-and-Giti

**Comment by AntTheAlchemist** [comment]
Forgive me if this already exists, or is planned, but is there also an easy way to check if a path/file exists? Would we use `SDL_GlobDirectory` for this? Or can it be added to `SDL_GetPathInfo` in the form of a new `SDL_PathInfo` entry `SDL_PATHTYPE_NOTEXISTS`, or something. Or a standalone `SDL_GetPathExists` ?

**Comment by slouken** [comment]
> Forgive me if this already exists, or is planned, but is there also an easy way to check if a path/file exists? Would we use `SDL_GlobDirectory` for this? Or can it be added to `SDL_GetPathInfo` in the form of a new `SDL_PathInfo` entry `SDL_PATHTYPE_NOTEXISTS`, or something. Or a standalone `SDL_GetPathExists` ?

That's a trap for race conditions. If you want to know if it exists so you can open it, you should open it and handle the open failing. If you want to know if it exists, you probably also need to know whether it is a file or directory, and you can use SDL_GetPathInfo() to find that out, and handle failures there.

**Comment by AntTheAlchemist** [comment]
> use SDL_GetPathInfo() to find that out, and handle failures there.

Understood. The documentation is not clear on what `SDL_GetPathInfo()` does if the file doesn't exist though. Does it error? What would SDL_PathInfo look like?

**Comment by slouken** [comment]
Good point. I'll clarify that.

FYI, an easy way to check for existence would be `if (SDL_GetPathInfo(path, NULL) == 0) { ... }`

**Comment by AntTheAlchemist** [comment]
Ah, that's nice! Can you also clarify that `SDL_PathInfo *info` can be null.  Is there any universal way to know if `fill` can be null? Or can they all be null?

**Comment by slouken** [comment]
> Ah, that's nice! Can you also clarify that `SDL_PathInfo *info` can be null. Is there any universal way to know if `fill` pointer can be null? Or can they all be null?

I did clarify that. In general any `fill` pointer can be NULL if you don't care about the result.
