### ISSUE TITLE
Use of uninitialised variable in DBus_OpenDialog()

### ISSUE THREAD

**Issue by meyraud705** [libsdl-org/SDL#9300]
In function `DBus_OpenDialog()`, if `dbus->connection_send_with_reply_and_block()` return NULL, then `signal_id` is not initialised and is passed to `SDL_strlen()` and `SDL_snprintf()`.

https://github.com/libsdl-org/SDL/blob/fc26d5d3285d4a5f501c7416a61181e3402d4a50/src/dialog/unix/SDL_portaldialog.c#L345-L361

**Comment by slouken** [comment]
Fixed, thanks!
