### ISSUE TITLE
SDL 3.0 prerelease

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9301]
We're just about done with the ABI changes, so now's a good time to cut a 3.0 prerelease.

@libsdl-org/a-team, is there anything that should absolutely be fixed before we start getting feedback on 3.0 changes?

Here's a list of things that we need before the prerelease:
- [x] https://github.com/libsdl-org/SDL/issues/9309

**Comment by flibitijibibo** [comment]
I threw a FIXME in SDL_storage.h, would definitely consider that necessary for calling SDL filesystem support ready to freeze.

More broadly, how are we feeling about SDL_gpu? The FNA team is still hacking away on our end, and while it may not be _strictly_ required we'd still like to try and make sure that 3.0's GPU integration doesn't end up as an afterthought.

I'm still working on ActionSet but that's not going to be coupled in the same way that GPU might be, so I'm willing to let that go after the freeze.

**Comment by slouken** [comment]
> I threw a FIXME in SDL_storage.h, would definitely consider that necessary for calling SDL filesystem support ready to freeze.

Yep, this is not 3.0 feature complete or even ABI frozen yet, just an "almost done, let's get feedback" preview. I'll make that clear in the announcement.

> More broadly, how are we feeling about SDL_gpu? The FNA team is still hacking away on our end, and while it may not be _strictly_ required we'd still like to try and make sure that 3.0's GPU integration doesn't end up as an afterthought.

I'll let @icculus speak in more detail, but we don't want to delay SDL 3.0 release for the GPU API, so we're not considering that a blocker.

**Comment by madebr** [comment]
Not SDL, but I'd think SDL_test deserves a review before freezing it.

**Comment by slouken** [comment]
> Not SDL, but I'd think SDL_test deserves a review before freezing it.

SDL_test is never frozen, but is there something specific you'd like us to look at?

**Comment by sezero** [comment]
> and make sure that 3.0's GPU integration doesn't end up as an afterthought.

Seconded

**Comment by madebr** [comment]
> > Not SDL, but I'd think SDL_test deserves a review before freezing it.
> 
> SDL_test is never frozen, but is there something specific you'd like us to look at?

I meant its API should be stable: SDL_image uses SDL_test.
I think only the automation part should be thought about: https://github.com/libsdl-org/SDL/issues/9303

**Comment by slouken** [comment]
> I meant its API should be stable: SDL_image uses SDL_test. I think only the automation part should be thought about: #9303

#9303 sounds like a good idea, do you want to tackle that?

**Comment by icculus** [comment]
> I'll let @icculus speak in more detail, but we don't want to delay SDL 3.0 release for the GPU API, so we're not considering that a blocker.

It needs non-trivial effort to finish, and I would like people to start migrating from SDL2 generally to SDL3 generally in the meantime.

Which is to say, I do _not_ want to shove the existing GPU API into 3.2.0 and be stuck with design mistakes for the next decade.

It can land in an early 3.x update, the same way other APIs (and entire subsystems!) were added to SDL2 after 2.0.0 shipped.

I expect this will be a FAQ for the initial SDL3 release, and the tl;dr is "we want to get it right and we didn't want to hold up the rest of SDL3 in the meantime."

FNA crew: all that being said, let's get a meeting of some sort together soon and figure out the details, please!

**Comment by 1bsyl** [comment]
Just catching up with recent changes, besides looking like "iostream.h", just want to signal SDL_**IOS**tream also looks like an Apple subliminal message. Though, I don't see better naming.

Eventually, if both are streams, could it make sense to have the SDL_AudioStream, and SDL_IOStream somehow factorized.

**Comment by cgutman** [comment]
I filed #9339 to consider removing the legacy grab API for SDL3. Not sure if we need to do that before the prerelease though.

**Comment by slouken** [comment]
> I filed #9339 to consider removing the legacy grab API for SDL3. Not sure if we need to do that before the prerelease though.

Not needed before prerelease, but seems like a good idea.

**Comment by slouken** [comment]
This release is live!
https://github.com/libsdl-org/SDL/releases/tag/prerelease-3.1.0
