### ISSUE TITLE
Should SDL start with text input enabled?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9309]
I've gone back and forth on this.

Users expect their keyboards to input text into applications, but starting with text input enabled means that IMEs can potentially be showing and users get unexpected behavior like https://github.com/libsdl-org/SDL/issues/9268

We have the opportunity with SDL 3.0 to document and change the default behavior so applications have to explicitly say when they want text input.

Do people think this is a good idea? @libsdl-org/a-team?

**Comment by slouken** [comment]
@cgutman, thoughts?

**Comment by cgutman** [comment]
I lean toward disabled by default. 
- It avoids surprises like #9268 on platforms where the IME decides to jump in an inopportune times
- When using `SDL_SetTextInputRect()`, the docs advise to set the text input rectangle _before_ calling `SDL_StartTextInput()`, so having it enabled by default without a defined text input rectangle seems odd.
- It allows for a nice clean state machine for input in applications - you call ``SDL_SetTextInputRect()`` and `SDL_StartTextInput()` when you want the user to type something, the on-screen keyboard pops up, you receive the text input events, then you `SDL_StopTextInput()` when you're finished.
- It's apparently so unintuitive even [our own text input tutorial](https://wiki.libsdl.org/SDL2/Tutorials-TextInput) calls `SDL_StartTextInput()` as the first thing it does.

**Comment by flibitijibibo** [comment]
I'm also on Team Disabled By Default - had I not just assumed that StartTextInput was always required it would have given us a lot of long-term portability problems on mobile and console; better to make the behavior consistent so games don't have to port from SDL to SDL when moving away from PC.

**Comment by slouken** [comment]
Okay, here's my proposal for SDL 3.0:
* Text input events are always enabled and are not related to IME input state or on-screen keyboard
* We add SDL_HasKeyboard() and SDL_HasMouse() (this could be a precursor to multi-mouse/keyboard, but for now will be used for the next steps)
* SDL_StartTextInput() will take a window and a rect as a parameter to enable input for a particular window. By default this will show the on-screen keyboard if that's available and there are no keyboards attached. `SDL_HINT_ENABLE_SCREEN_KEYBOARD` can be set to "1", "0", or "auto", to force or use the default behavior here.
* SDL_StopTextInput() will take a window as a parameter and will undo screen keyboard changes, respecting the hint as above.
* SDL_VideoInit() will no longer start text input
* sdl2-compat will start text input using the same logic and hint setting that SDL2 currently does.

Thoughts? @icculus sanity check?

**Comment by slouken** [comment]
Assuming people like this proposal, I'm adding it for the SDL 3.0 prerelease, as it's a pretty dramatic behavior change. Feel free to pick it up if you'd like to work on this.

**Comment by slime73** [comment]
> * Text input events are always enabled and are not related to IME input state or on-screen keyboard

If I'm understanding that approach correctly, is it able to solve #9268 ? I haven't looked too closely at the specifics but it seems like the macOS text input event code is incidentally making some IME UI show up, so the way that text input events are generated on macOS would need to change (if possible) in order to make them independent from IME UI, right?
