### ISSUE TITLE
SDL_SetYUVConversionMode() has no effect with OpenGL

### ISSUE THREAD

**Issue by rom1v** [libsdl-org/SDL#9311]
`SDL_SetYUVConversionMode(SDL_YUV_CONVERSION_JPEG);` works correctly for many render drivers, but not for OpenGL.

If I set:

```c
SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles2");
SDL_SetHint(SDL_HINT_RENDER_DRIVER, "software");
```

the rendered colors are as expected.

But without hint, or with:

```c
SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl");
```

the result is the same as if `SDL_SetYUVConversionMode(SDL_YUV_CONVERSION_JPEG);` was not called.

Context: https://github.com/Genymobile/scrcpy/issues/4756#issuecomment-2007195006

**Comment by slouken** [comment]
This function has been removed in SDL 3.0, and all renderers respect the new texture colorspace properties.
