### ISSUE TITLE
Cocoa mouse wheel events different from what the SDL_MouseWheelEvent documentation says

### ISSUE THREAD

**Issue by cblc** [libsdl-org/SDL#9318]
Reading https://wiki.libsdl.org/SDL2/SDL_MouseWheelEvent it says that you can figure out if a mouse wheel event came from a real mouse, or from a touch input device by checking whether `which` is `SDL_TOUCH_MOUSEID` or not.

I found that its definition is `#define SDL_TOUCH_MOUSEID ((Uint32)-1)` at https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_touch.h (with the comment `/* Used as the device ID for mouse events simulated with touch input */` )

But I see that https://github.com/libsdl-org/SDL/blob/SDL2/src/video/uikit/SDL_uikitevents.m seems to make `mouseID` equal to `mice_connected`, which, if I'm reading it correctly, is obtained as the number of mice connected to the Mac. It looks like this is different from what the documentation says, because `SDL_SendMouseWheel()` is being called with the number of mice connected, which has nothing to do with the definition of `SDL_TOUCH_MOUSEID`.

A different -but very relevant- point is that if the meaning of `SDL_TOUCH_MOUSEID` is "the device ID for mouse events simulated with touch input", you cannot get that information from the number of mice connected (i.e. the Magic Mouse is actually "touch input" in terms of "wheel" events). In fact, AFAIK, there's no clear Apple API for telling you if a scroll event came from a wheel or from a touch device. The workarounds I use for this in my code is to check for `hasPreciseScrollingDeltas` in the received `NSEvent`, which works fine for me because wheels in common mice don't have precise scrolling, and, when some device has precise scrolling, it's likely to behave very much as a touch device (the ball in the Mighty Mouse has precise scrolling, but, honestly, I'd say that ball is more like "touch input" than a real mouse wheel).

In Carbon there is a way for checking if a scroll event came from a wheel or from a touch device: Just use `GetEventKind()` and then check if it's `kEventMouseWheelMoved` (a real mouse wheel) or `kEventMouseScroll` (a touch device).

There are other "hacky" approaches for telling if it came from a wheel or not, like checking the Phase in a multitouch gesture, but, IMHO, I consider that less convenient (and less rock-solid in terms of possibility of being broken in the future) than just checking for `hasPreciseScrollingDeltas`, or even using the Carbon approach.

**Comment by icculus** [comment]
`src/video/uikit` is the iOS code, not the macOS code. You want `src/video/cocoa` for that.

We've got some discussion going about what to do with SDL_TOUCH_MOUSEID, though, since the Mac touchpad is as much a touch device as it is a trackpad, but this is confusing users and developers. That's over in #3303, so we'll discuss futher there.
