### ISSUE TITLE
New High DPI functions do not report high DPI screen properly

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#9322]
I have an Ubuntu 22.04 desktop with two 1920x1080 monitors, and a Pixel 3a phone running Ubuntu Touch with a screen that will report its resolution to be 1080x1920, but is one quarter of the physical size in each dimension compared to my desktop monitors.

When I use SDL2, the `SDL_GetDisplayDPI` function signals for, respectively, my two desktop monitors and my phone screen:
```
# ddpi hdpi vdpi
# Desktop
101.599998 101.599998 101.599998
101.599998 101.599998 101.599998

# Phone
399.881653 397.565216 400.467163
```

However, when I use the corresponding SDL3 functions recommended in [this document](https://github.com/libsdl-org/SDL/blob/main/docs/README-highdpi.md) ([fixed commit](https://github.com/libsdl-org/SDL/blob/70b0d33106e98176bf44de5d301855d49587fa50/docs/README-highdpi.md)), specifically `SDL_GetDisplayContentScale` and `SDL_GetWindowPixelDensity`, both functions on either device report the same scaling:
```
# SDL_GetDisplayContentScale
# Desktop
1.000000

# Phone
1.000000

# SDL_GetWindowPixelDensity
# Desktop
1.000000

# Phone
1.000000
```

The documentation does not seem to refer to any other function to get the "raw" DPI of a screen/window. There is a `SDL_WINDOW_HIGH_PIXEL_DENSITY` flag mentioned (or `SDL_WINDOW_ALLOW_HIGHDPI` for SDL2); I tried enabling it and disabling it, but it doesn't seem to change anything.

Is this a misunderstanding on my end, or a bug in SDL?

**Comment by slime73** [comment]
Are you using x11 or Wayland? I don't think SDL supports app dpi scale awareness for the former, but maybe that's changed recently.

**Comment by Semphriss** [comment]
I believe Ubuntu Touch now runs with Wayland, but I'd have to confirm. It used Mir before, though, I don't think it ever used X11.

**Comment by Semphriss** [comment]
I made SDL print its video driver, and it reports Wayland on my phone device.

Interestingly, it reports X11 on my desktop when I use Clickable (Ubuntu Touch's standard development tool), despite my desktop using Wayland. It does report Wayland when I compile and run it manually though. But I don't think that's related to the issue, since it uniformly reported a scale of 1 followed by as many zeroes as one could ever want.

**Comment by Kontrabant** [comment]
SDL3 ignores physical dimensions and DPI in favor of the reported desktop scale (i.e. manually setting your desktop scale to 150%, 200%, etc…). If you have your desktop scale factor set to 100%, SDL is always going to report 1.0.

**Comment by Semphriss** [comment]
Is there a way to get the old-style DPI?

**Comment by slime73** [comment]
The old physical DPI couldn't be consistent in a manner that's accurate / representative across devices and platforms I think.

If you just want it to scale differently on your phone, I suppose you could hard-code something into your app? It doesn't seem any worse to do that than using the old API imo.

**Comment by Semphriss** [comment]
I'm hesitant to hardcode stuff according to my device since Ubuntu Touch ships on a variety of phones, with different screens, and I'd like apps to work conveniently on all devices.

In addition, I'm creating an SDL template to allow developers to create and port SDL apps to Ubuntu Touch, and the template is likely to become part of Clickable; I would like to take the opportunity to show the good practices to new developers.

Is there more info on how the SDL functions are generally expected to obtain the scaling they report? If they take some pixel density into account (as opposed to just the user's preferences), would it be good if I opened a PR with some code specific to Ubuntu Touch, assuming I can get something working?

**Comment by Kontrabant** [comment]
The display scale seen when enumerating displays is calculated from the logical and reported resolutions, and the actual scale that the window should use is handled in one of two ways:

1. If the compositor is more recent, it directly reports the scale that a window should use via either the fractional scaling protocol or the core protocol, and this scale factor is simply forwarded to the client application.
2. The old way where a list is kept of displays that the window is currently on, and the highest scale factor of all the displays that the window is currently on is forwarded to the client.

**Comment by Semphriss** [comment]
Is there a way to obtain the low-level DPI info reported by Wayland, similar to what is done in SDL2? I'm thinking something to obtain the raw driverdata handle, and from there I could obtain the reported DPI. It would help me a lot, since the scaling in Ubuntu Touch isn't reported as the regular "desktop scaling" user preference concept that's managed in the settings.
