### ISSUE TITLE
SDL3 Android crash getVibrator() == null

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9331]
I get the following crash report on Google Play Console on the rare occasion.  Why would this be null? Do we need to add a null check here?

No pending exception expected: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Vibrator android.view.InputDevice.getVibrator()' on a null object reference

**Comment by 1bsyl** [comment]
yes, maybe, I´ll do a PR

**Comment by 1bsyl** [comment]
PR https://github.com/libsdl-org/SDL/pull/9334
the code, just after, is actually testing the (vib != null)
