### ISSUE TITLE
Issue regarding audio dropouts on PipeWire systems when native PipeWire support is not specified at compile time

### ISSUE THREAD

**Issue by KSSBrawl** [libsdl-org/SDL#9335]
I originally filed an issue regarding this [here](https://github.com/TerryCavanagh/VVVVVV/issues/1159) and was suggested to file it here as well. Whether this is an issue with SDL or PipeWire itself I am unsure of as PipeWire ostensibly is able to capture and emulate PulseAudio API calls. Additionally, although I originally tested the issue using SDL2 2.28.5, it still persists in SDL2 2.30.1.

**Comment by icculus** [comment]
The latest SDL will default to PipeWire, so you won't use their PulseAudio emulation by default anymore.
