### ISSUE TITLE
[SDL2] Buffering of SDL_MOUSEMOTION events after some time on Linux

### ISSUE THREAD

**Issue by FrogTheFrog** [libsdl-org/SDL#9336]
### Background

I am using the [Moonlight](https://github.com/moonlight-stream/moonlight-qt) application for streaming.
When it receives events from SDL, it processes all of them and aggregates the data from SDL_MOUSEMOTION events
before sending them out to the host.

However, after some 30 to 60 minutes, the mouse movement becomes jittery/jumpy instantly (there does not seem to be a gradual increase in jitteriness).

### The issue

I have investigated the problem and found out that suddenly a lot of SDL_MOUSEMOTION events are being send out at the same time:

```
std::chrono::steady_clock::now(),SDL_TIMESTAMP,SDL_XREL, SDL_YREL, SDL_X, SDL_Y
6021324282773,2767746,-1,0,1667,529
6021326505831,2767748,-1,0,1666,529
6021327612034,2767749,-1,0,1665,529
6021329792241,2767751,-1,0,1664,529
6021382150844,2767804,-1,0,1663,529
6021382180205,2767804,-1,0,1662,529
6021382184845,2767804,-1,0,1661,529
6021382189145,2767804,-1,0,1660,529
```

If you look at the second column, you can see that after value `2767751` there is a big gap and then we have a lot of events with the same timestamp.

I have counted the events with the same timestamp and this is how it looks when there is no problem:
![image](https://github.com/libsdl-org/SDL/assets/22381748/29fa372a-2540-482e-95f8-8a1b95909307)

vs. when they are buffered:
![image](https://github.com/libsdl-org/SDL/assets/22381748/286b0b17-9148-42b0-aa3f-55249d3aba04)

Since Moonlight aggregates all of the received events, there is now quite a jitter in the mouse movement.

### Inconsistent behavior

I have noticed that the issue occurs when using an AppImage and flatpak build with `--filesystem=host` enabled. However, if you do not enable `--filesystem=host` permission this issue does not occur.

### Further steps

The problem is that it  occurs only after some time so it is a nightmare to debug.
I have tried to trace the issue using `callgrind`, however the application becomes unusable on SteamDeck.

I am rather lost in the SDL2 code and thought it would be just faster to ask for an advice on where to maybe add some logs or enable some secret parameters to get to core of the issue.

**Comment by slouken** [comment]
@cgutman, any insight? I can't think of anything that SDL would be doing that could affect this, nor why `--filesystem=host` would affect events.

**Comment by cgutman** [comment]
Neither can I, but I'll try to profile it and see what's going on during those pauses in event delivery. It's definitely strange that the delivery of mouse events doesn't completely stop during most of those pauses, so it doesn't look like the event loop is blocked during those periods.

@FrogTheFrog IIRC, you mentioned that you saw the effects persist even beyond the lifetime of a single connection and needed a restart of Moonlight to get it back to normal. Is that correct?

**Comment by FrogTheFrog** [comment]
@cgutman Nope. I meant that it persists for the lifetime of the connection - once you terminate the connection, the mouse is fine again for a while.

My Moonlight app always terminates after connection is lost so I may have confused us both.

**Comment by FrogTheFrog** [comment]
I'm sad to announce that I can no longer reproduce this issue...
Time heals wounds and apparently this bug too.
