### ISSUE TITLE
Automated video_getSetWindowState test is failing

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9338]
On my Windows system, `testautomation --filter video_getSetWindowState` is failing. This used to pass, are we doing something wrong in the event handling?

The output is:
```
INFO:  03/23/24 09:12:35: Assert 'Call to SDL_GetWindowPosition()': [0;32mPassed[0m
'testautomation.exe' (Win32): Unloaded 'C:\Windows\System32\dwmapi.dll'
ERROR: 03/23/24 09:12:35: Assert 'Verify returned X coordinate; expected: 1695, got: 0': [0;31mFailed[0m
ERROR: 03/23/24 09:12:35: Assert 'Verify returned Y coordinate; expected: 791, got: 0': [0;31mFailed[0m
INFO:  03/23/24 09:12:35: Assert 'Call to SDL_GetWindowSize()': [0;32mPassed[0m
ERROR: 03/23/24 09:12:35: Assert 'Verify returned width; expected: 450, got: 3840': [0;31mFailed[0m
ERROR: 03/23/24 09:12:35: Assert 'Verify returned height; expected: 578, got: 2160': [0;31mFailed[0m
```

**Comment by Kontrabant** [comment]
Hmm, I can't replicate this on the current main branch on Win 10. Everything passes for me, whether I run just the individual test or the whole suite.

**Comment by slouken** [comment]
Okay, I’ll dig in here, thanks!

**Comment by slouken** [comment]
Hmm, so what's happening is that the window is maximized, then transitioned to fullscreen, then out of fullscreen, then restored. WM_WINDOWPOSCHANGING is called with the full desktop size in the restore call. What behavior are you seeing there?

**Comment by Kontrabant** [comment]
When I break in the WM_WINDOWPOSCHANGING message during the restore call and cast lParam to WINDOWPOS, I see the correct, original windowed size and position (Win 10 22H2, all the latest updates).

This sounds like a bugged behavior change in Windows.

**Comment by slouken** [comment]
Ugh, okay, thanks. I'll leave this open for now, but I'm not sure what the fix would be.

**Comment by Kontrabant** [comment]
Is this still failing on your system? I finally set up a Win11 test environment, and will all available updates applied, this test passes for me.

**Comment by slouken** [comment]
I grabbed the latest updates and all tests pass for me now.
