### ISSUE TITLE
V-Sync toggle for framebuffer API?

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#9347]
Is it possible to specify the V-Sync setting for the framebuffer API, similarly to how the render API has the `SDL_RENDERER_PRESENTVSYNC` flag?

**Comment by slouken** [comment]
Currently the framebuffer backends that use the SDL renderer use `SDL_HINT_RENDER_VSYNC` as a hint for this. We could document that this hint also affects the framebuffer API and you could key off of that.

Alternatively we could add flags and an explicit API for this in SDL 3.0. I'm feeling lazy, so I'm leaning towards just keeping the hint, but if you think this should be exposed as a first class citizen in the API, feel free to create a PR for review.

**Comment by icculus** [comment]
Tossing this into the 3.0 ABI category in case we want changes, but I say the hint is good enough for now.
