### ISSUE TITLE
Text input is now always on in Windows

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9353]
I'm always getting `SDL_EVENT_TEXT_INPUT` events now, and can't disable them. `SDL_StopTextInput()` has no effect. `SDL_TextInputActive()` returns false until `SDL_StartTextInput()` is called, but otherwise no apparent effect, and still returns true after `SDL_StopTextInput()`. Probably something simple overlooked in a recent commit.

**Comment by slouken** [comment]
Yep, fix, thanks!

**Comment by AntTheAlchemist** [comment]
Stopping and starting input used to call `SDL_SetEventEnabled()` to enable and disable these events, but now these events are always on, is this intentional?

**Comment by slouken** [comment]
Yes, so that your own application can send text events when it wants. I have a fix coming...

**Comment by slouken** [comment]
This should be fixed, thanks!
