### ISSUE TITLE
3.1.0 pre release build failure on alpinelinux

### ISSUE THREAD

**Issue by bl4ckb0ne** [libsdl-org/SDL#9357]
I started packaging the 3.1.0 pre release on alpine linux [1] and the build is failing on all arch with the same error

```
In file included from /usr/include/fortify/string.h:26,
                 from /home/simon/aports/testing/sdl3/src/SDL3-3.1.0/include/SDL3/SDL_stdinc.h:38,
                 from /home/simon/aports/testing/sdl3/src/SDL3-3.1.0/include/SDL3/SDL.h:32,
                 from /home/simon/aports/testing/sdl3/src/SDL3-3.1.0/test/testevdev.c:14:
/usr/include/fortify/stdlib.h:42:1: error: 'realpath' undeclared here (not in a function)
   42 | _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
      | ^~~~~~~~~~~
In file included from /home/simon/aports/testing/sdl3/src/SDL3-3.1.0/test/../src/SDL_internal.h:90,
                 from /home/simon/aports/testing/sdl3/src/SDL3-3.1.0/test/testevdev.c:26:
/usr/include/fortify/stdlib.h: In function 'realpath':
/usr/include/fortify/stdlib.h:45:2: error: #error PATH_MAX unset. A fortified realpath will not work.
   45 | #error PATH_MAX unset. A fortified realpath will not work.
      |  ^~~~~
```

[1]: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/62841

**Comment by slouken** [comment]
Where is PATH_MAX defined on your system? Shouldn't the system headers include their own necessary dependencies?

**Comment by sezero** [comment]
Alpine linux uses musl libc, not glibc, that _might_ be the reason for failures. Maybe define `_BSD_SOURCE` at top of testevdev.c if not already defined?

**Comment by madebr** [comment]
> @madebr, I think the autotools path defined _GNU_SOURCE when building SDL. Are we no longer doing that?

The only reference to `_GNU_SOURCE` I can find in SDL2 are these:
https://github.com/libsdl-org/SDL/blob/cbc9bd9804c6be58cc2fc95c716342ba49f55419/configure.ac#L3207
https://github.com/libsdl-org/SDL/blob/cbc9bd9804c6be58cc2fc95c716342ba49f55419/configure.ac#L3219
https://github.com/libsdl-org/SDL/blob/cbc9bd9804c6be58cc2fc95c716342ba49f55419/src/SDL_internal.h#L24-L27
https://github.com/libsdl-org/SDL/blob/cbc9bd9804c6be58cc2fc95c716342ba49f55419/src/hidapi/linux/hid.c#L27-L29

So perhaps we need to apply sezero's suggestion? 
I'd use `_POSIX_SOURCE` instead. [spec link](https://pubs.opengroup.org/onlinepubs/9699919799/functions/realpath.html)

**Comment by slouken** [comment]
Hmm, testevdev.c includes SDL_internal.h by default, which defines _GNU_SOURCE. Is that not happening in the CMake test build?

**Comment by sezero** [comment]
The thing is, as far as I know, musl libc doesn't respond to _GNU_SOURCE

**Comment by sezero** [comment]
> The thing is, as far as I know, musl libc doesn't respond to _GNU_SOURCE

Well, I was very wrong:
https://git.musl-libc.org/cgit/musl/tree/include/stdlib.h#n113

**Comment by bl4ckb0ne** [comment]
@madebr I commented out the `SDL_internal.h` include line and it built fine.

**Comment by madebr** [comment]
> @madebr I commented out the `SDL_internal.h` include line and it built fine.

Doing so, you disabled the complete evdev test.
https://github.com/libsdl-org/SDL/blob/58f2e102a93810944af7ba41452235f4a46c3f95/test/testevdev.c#L35
Your issue has something to do with the fortification.
What are the compile flags?

**Comment by bl4ckb0ne** [comment]
> Doing so, you disabled the complete evdev test.

Ha, makes sense it builds then.

Here's the line above the error

```
/usr/bin/cc -DHAVE_SIGNAL_H -I/tmp/SDL/src -I/tmp/SDL/build/include-config-minsizerel -I/tmp/SDL/build/include -I/tmp/SDL/include -I/tmp/SDL/include/SDL3 -Os -DNDEBUG -std=c90 -Wall -Wundef -fno-strict-aliasing -Wshadow -Wno-unused-local-typedefs -Wimplicit-fallthrough -fdiagnostics-color=always -idirafter/tmp/SDL/src/video/khronos -MD -MT test/CMakeFiles/testevdev.dir/testevdev.c.o -MF test/CMakeFiles/testevdev.dir/testevdev.c.o.d -o test/CMakeFiles/testevdev.dir/testevdev.c.o -c /tmp/SDL/test/testevdev.c
```

**Comment by madebr** [comment]
I'd like to see what happens in a docker container, but I get these errors when installing cmake:
```
# apk add cmake
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/edge/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/edge/community: temporary error (try again later)
ERROR: unable to select packages:
  cmake (no such package):
    required by: world[cmake]
```
I start the container with `docker run --rm -ti -v $PWD:/src:z alpine:edge`

**Comment by bl4ckb0ne** [comment]
Maybe a networking issue? I got it to work fine on my end with podman. Although I had an issue with cmake at first `Error relocating /usr/bin/cmake: SSL_get0_group_name: symbol not found`, running `apk upgrade` in the container worked.

I used this to generate the build folder, it's what's used in the APKBUILD

```
cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_JOB_POOLS=thr=3 -DCMAKE_JOB_POOL_LINK=thr -DBUILD_SHARED_LIBS=True -DSDL_TESTS=ON -DSDL_ALSA=ON -DSDL_JACK=ON -DSDL_CLOCK_GETTIME=ON -DSDL_RPATH=OFF -DSDL_X11=ON -DSDL_WAYLAND=ON -DSDL_STATIC=ON -DSDL_SHARED=ON
```

**Comment by madebr** [comment]
#9362 fixes this issue

This is a minimum reproducer of the error you were seeing:
```c
#include <limits.h>
#define _GNU_SOURCE
#include <stdlib.h>
```

**Comment by bl4ckb0ne** [comment]
Test failure but it builds fine, thank your for taking care of the issue @madebr

**Comment by madebr** [comment]
Glad we found the issue.

The failure is probably because SDL is built without evdev capability check.
I also saw this when building in the alpine docker.
