### ISSUE TITLE
Make hashtable a public API

### ISSUE THREAD

**Issue by nightmareci** [libsdl-org/SDL#9358]
There's lots of uses for hashtables in gamedev. Making the currently internal API public would be great, for games written in C.

One common use for hashtables is config files, like INI. So if SDL had hashtables public, it'd be pretty easy to make your own config file parser, the hardest part is already done.

Having the API public would also be nice for addon libraries, which would be C code. Could even make a pretty simple INI parser addon.

**Comment by slouken** [comment]
I vote for not making the hashtable part of the public API. You're welcome to include SDL_hashtable.h and SDL_hashtable.c in your project, under the ZLib license.

**Comment by icculus** [comment]
That's fine with me.

**Comment by robindegen** [comment]
sad; I found something about this and it would actually really help for things like asset load caches etc. I was disappointed to find it wasn't public api

**Comment by icculus** [comment]
This is about to get more complicated when we move to the templated hash table (#12848). It wouldn't really fit with most of SDL's API anymore, since it would cease to be specific entry points in a shared library, but rather code generated in one's app.*

I'm honestly surprised we haven't needed a hashtable implementation in any of the satellite libraries, though...maybe Properties turned out to be enough?

----
*this isn't completely unheard of: SDL_assert and SDL_main do, too, but those are small, special-case magic.

**Comment by nightmareci** [comment]
> I'm honestly surprised we haven't needed a hashtable implementation in any of the satellite libraries, though...maybe Properties turned out to be enough?

I've actually been using Properties for a virtual filesystem implementation, over a custom "DAT" uncompressed archive format. It does seem plenty good enough if you only need string keys, the string keys in my virtual filesystem being relative file paths.

I suppose we could consider making the hashtable public if satellite libraries suddenly need non-string-keyed hashtables. Or add new dynamic library APIs like current Properties, supporting key types other than strings.

Technically, keys don't even have to be valid UTF-8 strings, per the current ABI: All they have to be are zero-byte-terminated arrays of nonzero bytes, so you could "cheat" and convert any kind of data to that format, the data possibly not being valid UTF-8 text. Or convert to base64, of course.

**Comment by robindegen** [comment]
i didn't even consider using properties for this. That does make sense. I'll try that thanks

**Comment by slouken** [comment]
SDL_ttf uses hashtables
