### ISSUE TITLE
SDL3 - window created fullscreen inherits size from screen

### ISSUE THREAD

**Issue by slembcke** [libsdl-org/SDL#9359]
In SDL2 if I create a window with small dimensions + the fullscreen flag. It will open a fullscreen window at the screen's native resolution. Exiting from fullscreen turns it into a window with the smaller dimensions specified at creation. This is more or less expected, though open to debate.

In SDL3.1.0, when exiting from fullscreen it turns into a window with the screen's dimensions. This is a bit awkward as the window is too big to fit on the screen and the edges get pushed off. However, if you start in windowed mode, then enter/exit fullscreen it does remember the previous window dimensions.

So far have tested this on Fedora in both X11 and Wayland. I haven't tried Mac or Windows yet.

**Comment by Kontrabant** [comment]
I found and fixed the bug related to this in Wayland, but I can't replicate this in X11. Do you have a simple repro case?

**Comment by slembcke** [comment]
Hmm. To be more clear, I tested with _XWayland_ would that matter? I'll pull from main and test again, but it will be a few days before I have the time.

**Comment by Kontrabant** [comment]
Has this been resolved for you?

**Comment by slembcke** [comment]
Oh shoot, I completely forgot about this... Too much going on this spring. I can look into it tomorrow though.

**Comment by slouken** [comment]
No response, I'll go ahead and close this for now. Please let us know if it's still an issue.
