### ISSUE TITLE
SDL3 - segfault when reinitializing SDL

### ISSUE THREAD

**Issue by slembcke** [libsdl-org/SDL#9360]
In order to switch between Vk and GL in my game, I fully reinitialize SDL. This worked in SDL2, and IIRC it avoided some issues.

This doesn't work in SDL3 however. I get a segfault in `SDL_VideoInit()` the second time around. (Fedora tested with both X11 and Wayland) In the past @icculus said ["this is allowed behavior, afaik."](https://github.com/libsdl-org/SDL/issues/6048#issuecomment-1214283653) Is that still true? If this is considered undefined behavior now in v3 I can try rewriting it to just recreate the window instead.

**Comment by icculus** [comment]
This sounds like an SDL bug from here.

**Comment by icculus** [comment]
If you can say where it crashes, or have a tiny reproduction case we can run, please post it, though!

**Comment by slembcke** [comment]
Hmm. Tried to make a minimal example, but that works just fine. I won't have time this weekend to look into it more, but I should have time in a few days.

**Comment by slouken** [comment]
It looks like you haven't had time to get back to this, let us know if you're still seeing the issue?
