### ISSUE TITLE
[Regression] Software renderer not working at all on MacOS (tested on both M1 and Intel)

### ISSUE THREAD

**Issue by olekolek1000** [libsdl-org/SDL#9367]
How to reproduce:
Start ./testcamera or ./testdrawchessboard. 

Video:

https://github.com/libsdl-org/SDL/assets/29149078/a8470181-169d-4699-8a6d-b31c895407f3

Macbook 2015, Intel, MacOS 12.7.2.

On M1 CPU it just shows a black screen (reported by my colleagues)

~~Probably continuation of the https://github.com/libsdl-org/SDL/issues/9221~~ Nevermind
SDL_FlushRenderer doesn't seem to change anything.

Tested by many different methods:
via `SDL_CreateSoftwareRenderer`: not working
via `SDL_CreateRenderer` with `SDL_RENDER_DRIVER software` hint: not working
via `SDL_GetWindowSurface & Blit & SDL_UpdateWindowSurface`: not working

**Comment by olekolek1000** [comment]
It seems that the surface texture is wrongly displayed to the screen somehow.

**Comment by olekolek1000** [comment]
`SDL_RENDER_DRIVER=software ./testgeometry` shows up a black screen.

**Comment by olekolek1000** [comment]
Bisected!
commit ba074acad43fe3253fcdb9b7a696152fb01c5e42
Author: Sam Lantinga <slouken@libsdl.org>
Date:   Tue Feb 6 05:31:43 2024 -0800

    Implemented scRGB colorspace and HDR support on macOS

@slouken

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by olekolek1000** [comment]
Can confirm, works perfectly!
