### ISSUE TITLE
[SDL3] Request - Adding macros for accept and cancel buttons

### ISSUE THREAD

**Issue by panreyes** [libsdl-org/SDL#9369]
It might be a good idea to have macros for accept and cancel buttons depending on the platform.

I know this accept/cancel thing gets complicated soon, but for most cases it would be nice if it was solved by SDL3, making our games even more platform agnostic (♥!)

It could be easily be solved by adding those two lines to each `SDL_build_config_*.h`. For example, for Nintendo Switch:
```
#define SDL_GAMEPAD_BUTTON_ACCEPT SDL_GAMEPAD_BUTTON_EAST
#define SDL_GAMEPAD_BUTTON_CANCEL SDL_GAMEPAD_BUTTON_SOUTH
```

And maybe adding in `SDL_Gamepad.h` these fallback lines (Xbox sorted, which are the most common) just in case:
```
#ifndef SDL_GAMEPAD_BUTTON_ACCEPT
#define SDL_GAMEPAD_BUTTON_ACCEPT SDL_GAMEPAD_BUTTON_SOUTH
#endif
#ifndef SDL_GAMEPAD_BUTTON_CANCEL
#define SDL_GAMEPAD_BUTTON_CANCEL SDL_GAMEPAD_BUTTON_EAST
#endif
```

I know it could also be solved with SDL_ActionSet, but I think it might be nice to have both solutions, as SDL_ActionSet might be a bit overkill for just this.

**Comment by slouken** [comment]
We thought about this extensively, and it turns out that which button the user wants as accept/cancel depends on the platform, region, and muscle memory. Games should make this an option so users can use either one.
