### ISSUE TITLE
SDL3.1 Keyboard event only when mouse is on SDL window

### ISSUE THREAD

**Issue by sechshelme** [libsdl-org/SDL#9374]
Keyboard event is only triggered when the mouse cursor is over the SDL window.
I still have a lib that I compiled yesterday and it still worked perfectly.
So the bug must have been recent.

Linux Mint 64bit Cinnamon

**Comment by slouken** [comment]
Can you try the latest code in git? I've been messing around with XInput2 and may have introduce a bug (and then possibly fixed it?)

**Comment by sechshelme** [comment]
Version 3.1.0 from here works.
https://github.com/libsdl-org/SDL/releases/tag/prerelease-3.1.0

But the current one from here still doesn't work.
https://github.com/libsdl-org/SDL

**Comment by sechshelme** [comment]
I have built the latest SDL3.DLL for Windows 10 64bit.
And everything seems to be working properly there.
So I only notice the problem with Linux.

**Comment by slouken** [comment]
Yep, I can reproduce this here, thanks!

**Comment by sechshelme** [comment]
I just tried it, now it seems to be working again.
Thanks.

**Comment by slouken** [comment]
Great, thanks for the report! :)
