### ISSUE TITLE
[Q] user-configurable SDL_Event -> action mapping ?

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#9376]
i'm looking for a generic way for a user to configure the behaviour of SDL based apps using some textual representation, rather than hardcoding in a huge switch statement every possible action. of course, providing the action itself is then the task of the app.

a possible configuration for a quit action may look like:

action_quit = keydown_q,joybuttondown_button8,keydown_ctrl_x

does SDL provide some means that come close to this - for example getting a textual representation of an event (other than raw numbers), or does some recommendable 3rd-party solution exist (preferably in C and non-bloated) ?
or if you have any other idea, just throw it my way.

**Comment by slouken** [comment]
No, this isn't something SDL provides. You might be interested in https://github.com/libsdl-org/SDL/pull/7558 however.
