### ISSUE TITLE
SDL3 feedback: state for the SDL_main callback interface

### ISSUE THREAD

**Issue by maia-s** [libsdl-org/SDL#9377]
The SDL_main callback interface currently doesn't provide a way to pass program state, so the program has to store some of this state in static/global variables. This is cumbersome to do in e.g. the Rust programming language (in particular in the upcoming 2024 edition, which will remove static mutable variables from the language)

I'd like to propose changing the callback functions to support passing state. Instead of the current:
```
typedef int (SDLCALL *SDL_AppInit_func)(int argc, char *argv[]);
typedef int (SDLCALL *SDL_AppIterate_func)(void);
typedef int (SDLCALL *SDL_AppEvent_func)(const SDL_Event *event);
typedef void (SDLCALL *SDL_AppQuit_func)(void);
```
These could be changed to for example:
```
typedef int (SDLCALL *SDL_AppInit_func)(void** state, int argc, char *argv[]);
typedef int (SDLCALL *SDL_AppIterate_func)(void* state);
typedef int (SDLCALL *SDL_AppEvent_func)(void* state, const SDL_Event *event);
typedef void (SDLCALL *SDL_AppQuit_func)(void* state);
```
`SDL_AppInit` would set `*state` to the desired program-specific state, if any, and SDL would pass this value to the other functions. `state` would default to NULL for programs that don't write to `*state` in `SDL_AppInit`.

**Comment by slouken** [comment]
This seems like a good idea to me. @icculus, thoughts?

**Comment by icculus** [comment]
I don't mind adding this, but...does Rust not have global variables? It's not like there are multiple instances of the main loop.

**Comment by slouken** [comment]
Related:
https://github.com/libsdl-org/SDL/issues/8149

I'm also pretty sure this exact thing was proposed before, although I can't find it now.

**Comment by icculus** [comment]
I'll add this tonight and read over the other bug report.

**Comment by icculus** [comment]
> does Rust not have global variables?

Just reread the original comment, and wow, they are in fact removing globals. That's bold.  :)

**Comment by maia-s** [comment]
> Just reread the original comment, and wow, they are in fact removing globals. That's bold. :)

Kind of. Rust will still have read-only globals, and you can still get writable globals after this change by using a wrapper that enables what Rust calls interior mutability, which have interfaces that lets you write through a read-only reference with certain restrictions (the exact restrictions depends on the wrapper you use). So for clarity, I don't think this change would be required for Rust code to be able to use this feature, but with it we won't have to jump through as many hoops.

**Comment by icculus** [comment]
This should be good to go, as of 38e3c6a4aa338d062ca2eba80728bfdf319f7104; let me know if this needs anything else!
