### ISSUE TITLE
SDL_RenderSetIntegerScale both renamed and removed

### ISSUE THREAD

**Issue by Pentarctagon** [libsdl-org/SDL#9384]
In the migration guide at https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md, it states that `SDL_RenderSetIntegerScale` had been renamed to `SDL_SetRenderIntegerScale`, but also that `SDL_RenderSetIntegerScale` has been removed. The latter appears to be correct, as neither seem to exist in 3.1.

**Comment by slouken** [comment]
Fixed, thanks!
