### ISSUE TITLE
SDL_DisplayMode has no member display_scale

### ISSUE THREAD

**Issue by Pentarctagon** [libsdl-org/SDL#9386]
The migration guide at https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md states that `SDL_GetDisplayDPI` was removed and that it can instead be roughly calculated by multiplying the `display_scale` value on the `SDL_DisplayMode` returned by `SDL_GetDesktopDisplayMode`. However `SDL_DisplayMode` has no such member in 3.1.

**Comment by slouken** [comment]
Fixed, thanks!
