### ISSUE TITLE
SDL_InitSubSystem(SDL_INIT_AUDIO) = -1

### ISSUE THREAD

**Issue by MrJokerBoy** [libsdl-org/SDL#9388]
Hello, when using SDL on the Android platform, int ret = SDL_InitSubSystem(SDL_INIT_AUDIO); = - 1, initialization error

**Comment by icculus** [comment]
Is this with SDL2 or SDL3? Does SDL_GetError() report anything specific, or is it actually returning "initialization error" as its error string?

**Comment by MrJokerBoy** [comment]
The SDL2 version used is 2.28.5, and the error message is Application didn't initialize properly, did you include SDL_main.h in the file containing your main() function?

**Comment by MrJokerBoy** [comment]
> 这是SDL2还是SDL3？ SDL_GetError() 是否报告任何特定内容，或者它实际上返回“初始化错误”作为其错误字符串？

SDL2 is introduced by bringing compiled so and header files into your own project.

**Comment by MrJokerBoy** [comment]
> Is this with SDL2 or SDL3? Does SDL_GetError() report anything specific, or is it actually returning "initialization error" as its error string?

SDL2 is introduced by bringing compiled so and header files into your own project.

**Comment by icculus** [comment]
SDL on Android needs some other pieces to work correctly, like the Java code.

It's more complicated to set up than other platforms, but you only have to do it once.

https://wiki.libsdl.org/SDL2/README/android

**Comment by icculus** [comment]
(Closing this because it doesn't appear to be an SDL bug, but please let me know if I should reopen!)
