### ISSUE TITLE
User object leaking！

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#9391]
The number of user handles continues to grow, reaching a maximum of 10,000 in a while，Below is a screenshot in ProcessExplorer I have uploaded a qt5 test project.
<img width="948" alt="Snipaste_2024-03-28_22-33-43" src="https://github.com/libsdl-org/SDL/assets/1673854/93497c5d-9f81-4497-8e0e-a687816d6251">

[QtWidgetsTest.zip](https://github.com/libsdl-org/SDL/files/14791277/QtWidgetsTest.zip)

**Comment by icculus** [comment]
Is there some indication of _what_ is leaking? Perhaps there is some source code we can run that reproduces this?

(Also: are we sure that it's SDL leaking and not Qt, in this screenshot's example?)

**Comment by slouken** [comment]
This should be fixed in https://github.com/libsdl-org/SDL/commit/af5728b94d21ee23e3e6ab15e12430a15d33fbf0, can you verify?

**Comment by sandsc** [comment]
> This should be fixed in [af5728b](https://github.com/libsdl-org/SDL/commit/af5728b94d21ee23e3e6ab15e12430a15d33fbf0), can you verify?

Yep, this commit fixed the issue,  thanks you for the nice work!

**Comment by slouken** [comment]
You're welcome, thanks for the report!
