### ISSUE TITLE
enum <-> int size equality check in SDL_stdinc.h

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#9392]
At present, we skip checking enum <-> int size equality when targeting
Android, VITA and N3DS in SDL_stdinc.h.

For Android, it was disabled with https://github.com/libsdl-org/SDL/commit/6b8d32ccdecae205a55776501b6514aa1fe7c6f4
For VITA, it was disabled with https://github.com/libsdl-org/SDL/commit/ca5e5d615435cf0d57f87288f4d6199a31b50b3f
For N3DS, it was disabled with https://github.com/libsdl-org/SDL/commit/655275378d22acbef4685d8992a5c7b370bab4fa

I just quickly checked today against a _very_ old Android NDK (r10e, to
be precise (it was available)), and the assertion did actually pass. Do
not know the others, i.e. VITA and N3DS.

I'm raising this issue, because if there still is that size inequality,
it presents an abi incompatibility in sdl2-compat, because we share the
SDL_bool type with SDL3 in there when (_if_) targeting those platforms..

@slouken, @icculus?

CC: @1bsyl for Android (also @bieh for the original Android commit)
CC: @isage for VITA
CC: @FtZPetruska for N3DS

**Comment by slouken** [comment]
We can probably remove the Android check in a PR and see if one of the platforms fails. For VITA and N3DS I can confirm that those asserts fail, but there is probably a compiler option that will let it pass.

I'm assuming that anyone using sdl2-compat on VITA and N3DS will be rebuilding from source and we can remove those platform checks in both SDL2 and SDL3, so we can guarantee ABI compatibility.

**Comment by icculus** [comment]
...can sdl2-compat even work on VITA and N3DS?

**Comment by slouken** [comment]
Good point, can they build SDL as a dynamic library?

**Comment by sezero** [comment]
no idea..

**Comment by isage** [comment]
> Good point, can they build SDL as a dynamic library?

no (technically, yes, dynamic libraries are supported, but it's a whole another hell to do so)

**Comment by isage** [comment]
> but there is probably a compiler option that will let it pass

Well, `-fno-short-enums` will let that assert pass, but will break other things.
What's the initial reason for such assert? You can force specific enums to specific size if that's required

**Comment by FtZPetruska** [comment]
> Good point, can they build SDL as a dynamic library?

To my knowledge, the Homebrew toolchain for the N3DS does not allow building shared libraries.

> but there is probably a compiler option that will let it pass.

We got `-fno-short-enums` too, but if you turn that on you get warnings due to mismatched enum sizes:
```
% arm-none-eabi-gcc -fno-short-enums a.c
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/13.2.0/../../../../arm-none-eabi/bin/ld: warning: /var/folders/pm/wyy2q8sn3qj235t35_w1pgbm0000gn/T//ccGs1dHu.o uses 32-bit enums yet the output is to use variable-size enums; use of enum values across objects may fail
```

**Comment by slouken** [comment]
Let's go ahead and leave this alone for now. It sounds like sdl2-compat isn't going to be a thing on these platforms.

**Comment by sezero** [comment]
OK.

I will attempt at a PR removing Android from that list later.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/sdl2-compat/commit/fab4f808b141199ac900445f5dadb5c9aef39792 to sdl2-compat as a precaution.

**Comment by 1bsyl** [comment]
I don't really get the implications of these ...
 but sometimes, we put an enum entry like "last_thing = 0xffffffff" to make sure the enum is a 32bits". 
I believe for android, we don´t need a strong ABI compatibility: whatever the enum size, it should compile and run fine ...
