### ISSUE TITLE
SDL3 - MOUSE_UP doesn't arrive in relative mouse mode

### ISSUE THREAD

**Issue by amlinux** [libsdl-org/SDL#9395]
When SDL_SetRelativeMouseMode is enabled, SDL_EVENT_MOUSE_BUTTON_UP doesn't come. Platform: Windows. It was broken in commit https://github.com/libsdl-org/SDL/commit/361b7190df20b8b22e0d4e9ba4a4d7525aa794be. @slouken

**Comment by slouken** [comment]
Can you try the latest code?

**Comment by nomi-san** [comment]
@slouken, tried commit 4659a84bd1aebeeeac94793afb046a4059e8366d build and the issue is still here.

**Comment by slouken** [comment]
I'm not seeing the problem here. Does it happen with the SDL test programs? Can you provide more exact steps?

**Comment by nomi-san** [comment]
The problem is that you keep pressing mouse then enter relative mode, next mouse up does not arrive.
Tested on another build at 10 March (before 361b7190df20b8b22e0d4e9ba4a4d7525aa794be and 3.1.0 pre-release), mouse up arrives normally.

```cpp
    // handle events
    case SDL_EVENT_MOUSE_BUTTON_UP: {
        printf("SDL_EVENT_MOUSE_BUTTON_UP\n");
        break;
    }
    case SDL_EVENT_KEY_DOWN: {
        bool relative = !SDL_GetRelativeMouseMode();
        SDL_SetRelativeMouseMode(relative);

        if (relative)
            SDL_HideCursor();
        else
            SDL_ShowCursor();

        printf("Relative mouse: %d\n", relative);
        break;
    }
```

**Comment by slouken** [comment]
Fixed, thanks!
