### ISSUE TITLE
No available video device - Any way to use the library on headless ubuntu server?

### ISSUE THREAD

**Issue by slunak** [libsdl-org/SDL#9410]
Hello folks.

Is there any way to use the library on a Ubuntu Server without a display?

```
if err := sdl.Init(sdl.INIT_VIDEO); err != nil {
    println(err.Error())
    return
}
```

Gives the following error: `No available video device`, which is expected.

The reason I would like to use the library on headless ubuntu is to only generate graphics with SDL and later simply copy it to LED matrix display, pixel by pixel.

**Comment by icculus** [comment]
Set the environment variable SDL_VIDEODRIVER=dummy

(It's SDL_VIDEO_DRIVER in SDL3.)

**Comment by slunak** [comment]
Does it apply to SDL2? I'm afraid Go binding currently supports only version 2.

**Comment by icculus** [comment]
Yes. One less underscore in the variable name.

**Comment by slunak** [comment]
Sorry, I missed to see the difference between the two vars in your first reply; it was either late last night or perhaps because I was looking at it from my mobile phone :) in any case, thank you very much. Feel free to close this issue.
