### ISSUE TITLE
macOS: Opening a file select dialog crashes on macOS 11.0+

### ISSUE THREAD

**Issue by sridenour** [libsdl-org/SDL#9414]
When running macOS 11 or later, opening an SDL file selection dialog causes an Objective-C exception to be thrown.

This is because, when running on macOS 11 and later, SDL calls an NSOpen/NSSavePanel function that expects an array of `UTType` objects as the file type filters. However, SDL gives it an array of `NSString` objects (which is what the function that gets called on earlier macOS versions needs).

I've got a fix for this, and will link to the pull request once it's been created.

**Comment by slouken** [comment]
Merged, thanks!
