### ISSUE TITLE
Implement advanced joycon features

### ISSUE THREAD

**Issue by german77** [libsdl-org/SDL#9419]
I would like to implement extra functionality for joycons. Like IR camera, NFC or the external ring controller support. Is there any interest for that?

The ring can be quite easy to implement as it can be just another axis on the gamepad. But SDL lack the interface for IR and NFC so we need to define some rules and methods to make it as compatible as possible for other devices to be able to share the same interfaces which I would like to define in this issue.

IR camera has multiple features like: video, object detection, hand detection. With properties like resolution, window of interest, exposure time, etc.

NFC has support for multiple tags mostly following ISO14443A and Mifare protocols. So you can detect/read/write on the tags.

**Comment by slouken** [comment]
This is outside the scope of the SDL API. It sounds like this would be a nice standalone library for Joy-Con support.
