### ISSUE TITLE
WINWING Orion Throttle Base II + F15EX HANDLE - Not all buttons available 

### ISSUE THREAD

**Issue by mvrk69** [libsdl-org/SDL#9426]
Hi,

I'm trying to use the WINWING Orion Throttle Base II + F15EX HANDLE on linux, but it seems SDL can't detect all buttons.

When i use sdl-jstest it only shows 79 buttons, but the device has in total 110 buttons.

**Comment by slouken** [comment]
What is the output of `sudo evemu-describe` on the two devices?

**Comment by mvrk69** [comment]
evemu-describe | tr -d '#'
Available devices:
/dev/input/event0:	Power Button
/dev/input/event1:	Power Button
/dev/input/event2:	Linux 3.18.0 with ast_vhub SMCI HID KM
/dev/input/event3:	Linux 3.18.0 with ast_vhub SMCI HID KM
/dev/input/event4:	USB 2.0 Camera: USB 2.0 Camera
/dev/input/event5:	Winwing WINWING Orion Throttle Base II + F15EX HANDLE L + F15EX HANDLE R
/dev/input/event6:	Logitech USB Receiver
/dev/input/event7:	Logitech USB Receiver Keyboard
/dev/input/event8:	Winwing WINWING Orion Joystick Base 2 + JGRIP-F16
/dev/input/event9:	PC Speaker
/dev/input/event10:	Plantronics Poly BT700
/dev/input/event11:	HDA NVidia HDMI/DP,pcm=3
/dev/input/event12:	HDA NVidia HDMI/DP,pcm=7
/dev/input/event13:	HDA NVidia HDMI/DP,pcm=8
/dev/input/event14:	HDA NVidia HDMI/DP,pcm=9
Select the device event number [0-14]: 5
 EVEMU 1.3
 Kernel: 6.7.10-200.fc39.x86_64
 DMI: dmi:bvnAmericanMegatrendsInc.:bvr2.7:bd10/25/2023:br5.22:svnSupermicro:pnSuperServer:pvr0123456789:rvnSupermicro:rnH12SSL-i:rvr1.01:cvnSupermicro:ct17:cvr0123456789:skuTobefilledbyO.E.M.:
 Input device name: "Winwing WINWING Orion Throttle Base II + F15EX HANDLE L + F15EX HANDLE R"
 Input device ID: bus 0x03 vendor 0x4098 product 0xbd64 version 0x111
 Supported events:
   Event type 0 (EV_SYN)
     Event code 0 (SYN_REPORT)
     Event code 1 (SYN_CONFIG)
     Event code 2 (SYN_MT_REPORT)
     Event code 3 (SYN_DROPPED)
     Event code 4 ((null))
     Event code 5 ((null))
     Event code 6 ((null))
     Event code 7 ((null))
     Event code 8 ((null))
     Event code 9 ((null))
     Event code 10 ((null))
     Event code 11 ((null))
     Event code 12 ((null))
     Event code 13 ((null))
     Event code 14 ((null))
     Event code 15 (SYN_MAX)
   Event type 1 (EV_KEY)
     Event code 288 (BTN_TRIGGER)
     Event code 289 (BTN_THUMB)
     Event code 290 (BTN_THUMB2)
     Event code 291 (BTN_TOP)
     Event code 292 (BTN_TOP2)
     Event code 293 (BTN_PINKIE)
     Event code 294 (BTN_BASE)
     Event code 295 (BTN_BASE2)
     Event code 296 (BTN_BASE3)
     Event code 297 (BTN_BASE4)
     Event code 298 (BTN_BASE5)
     Event code 299 (BTN_BASE6)
     Event code 300 ((null))
     Event code 301 ((null))
     Event code 302 ((null))
     Event code 303 (BTN_DEAD)
     Event code 704 (BTN_TRIGGER_HAPPY1)
     Event code 705 (BTN_TRIGGER_HAPPY2)
     Event code 706 (BTN_TRIGGER_HAPPY3)
     Event code 707 (BTN_TRIGGER_HAPPY4)
     Event code 708 (BTN_TRIGGER_HAPPY5)
     Event code 709 (BTN_TRIGGER_HAPPY6)
     Event code 710 (BTN_TRIGGER_HAPPY7)
     Event code 711 (BTN_TRIGGER_HAPPY8)
     Event code 712 (BTN_TRIGGER_HAPPY9)
     Event code 713 (BTN_TRIGGER_HAPPY10)
     Event code 714 (BTN_TRIGGER_HAPPY11)
     Event code 715 (BTN_TRIGGER_HAPPY12)
     Event code 716 (BTN_TRIGGER_HAPPY13)
     Event code 717 (BTN_TRIGGER_HAPPY14)
     Event code 718 (BTN_TRIGGER_HAPPY15)
     Event code 719 (BTN_TRIGGER_HAPPY16)
     Event code 720 (BTN_TRIGGER_HAPPY17)
     Event code 721 (BTN_TRIGGER_HAPPY18)
     Event code 722 (BTN_TRIGGER_HAPPY19)
     Event code 723 (BTN_TRIGGER_HAPPY20)
     Event code 724 (BTN_TRIGGER_HAPPY21)
     Event code 725 (BTN_TRIGGER_HAPPY22)
     Event code 726 (BTN_TRIGGER_HAPPY23)
     Event code 727 (BTN_TRIGGER_HAPPY24)
     Event code 728 (BTN_TRIGGER_HAPPY25)
     Event code 729 (BTN_TRIGGER_HAPPY26)
     Event code 730 (BTN_TRIGGER_HAPPY27)
     Event code 731 (BTN_TRIGGER_HAPPY28)
     Event code 732 (BTN_TRIGGER_HAPPY29)
     Event code 733 (BTN_TRIGGER_HAPPY30)
     Event code 734 (BTN_TRIGGER_HAPPY31)
     Event code 735 (BTN_TRIGGER_HAPPY32)
     Event code 736 (BTN_TRIGGER_HAPPY33)
     Event code 737 (BTN_TRIGGER_HAPPY34)
     Event code 738 (BTN_TRIGGER_HAPPY35)
     Event code 739 (BTN_TRIGGER_HAPPY36)
     Event code 740 (BTN_TRIGGER_HAPPY37)
     Event code 741 (BTN_TRIGGER_HAPPY38)
     Event code 742 (BTN_TRIGGER_HAPPY39)
     Event code 743 (BTN_TRIGGER_HAPPY40)
     Event code 744 ((null))
     Event code 745 ((null))
     Event code 746 ((null))
     Event code 747 ((null))
     Event code 748 ((null))
     Event code 749 ((null))
     Event code 750 ((null))
     Event code 751 ((null))
     Event code 752 ((null))
     Event code 753 ((null))
     Event code 754 ((null))
     Event code 755 ((null))
     Event code 756 ((null))
     Event code 757 ((null))
     Event code 758 ((null))
     Event code 759 ((null))
     Event code 760 ((null))
     Event code 761 ((null))
     Event code 762 ((null))
     Event code 763 ((null))
     Event code 764 ((null))
     Event code 765 ((null))
     Event code 766 ((null))
     Event code 767 (KEY_MAX)
   Event type 3 (EV_ABS)
     Event code 0 (ABS_X)
       Value     2062
       Min          0
       Max       4095
       Fuzz        15
       Flat       255
       Resolution   0
     Event code 1 (ABS_Y)
       Value     2048
       Min          0
       Max       4095
       Fuzz        15
       Flat       255
       Resolution   0
     Event code 2 (ABS_Z)
       Value     2048
       Min          0
       Max       4095
       Fuzz        15
       Flat       255
       Resolution   0
     Event code 3 (ABS_RX)
       Value    53256
       Min          0
       Max      65535
       Fuzz       255
       Flat      4095
       Resolution   0
     Event code 4 (ABS_RY)
       Value    53350
       Min          0
       Max      65535
       Fuzz       255
       Flat      4095
       Resolution   0
     Event code 5 (ABS_RZ)
       Value    32952
       Min          0
       Max      65535
       Fuzz       255
       Flat      4095
       Resolution   0
     Event code 6 (ABS_THROTTLE)
       Value    32768
       Min          0
       Max      65535
       Fuzz       255
       Flat      4095
       Resolution   0
     Event code 7 (ABS_RUDDER)
       Value    32617
       Min          0
       Max      65535
       Fuzz       255
       Flat      4095
       Resolution   0
   Event type 4 (EV_MSC)
     Event code 4 (MSC_SCAN)
   Event type 20 (EV_REP)
     Event code 0 (REP_DELAY)
     Event code 1 (REP_PERIOD)
 Properties:
N: Winwing WINWING Orion Throttle Base II + F15EX HANDLE L + F15EX HANDLE R
I: 0003 4098 bd64 0111
P: 00 00 00 00 00 00 00 00
B: 00 0b 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 ff ff 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 ff ff ff ff ff ff ff ff
B: 02 00 00 00 00 00 00 00 00
B: 03 ff 00 00 00 00 00 00 00
B: 04 10 00 00 00 00 00 00 00
B: 05 00 00 00 00 00 00 00 00
B: 11 00 00 00 00 00 00 00 00
B: 12 00 00 00 00 00 00 00 00
B: 14 03 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
A: 00 0 4095 15 255 0
A: 01 0 4095 15 255 0
A: 02 0 4095 15 255 0
A: 03 0 65535 255 4095 0
A: 04 0 65535 255 4095 0
A: 05 0 65535 255 4095 0
A: 06 0 65535 255 4095 0
A: 07 0 65535 255 4095 0

**Comment by slouken** [comment]
It looks like the Linux kernel only sees 79 buttons. You'll need to talk to the kernel folks to see how to get all the buttons detected.

**Comment by igorinov** [comment]
@mvrk69 I have solved this problem with the grip handles that have 80 or fewer button codes.
https://github.com/igorinov/linux-winwing/
