### ISSUE TITLE
SDL_SetWindowModalFor isn't wired up for several platforms...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9427]
It looks like it's implemented for X11 and Wayland, but there are several other desktop platforms that could benefit from it:

- [ ] Cocoa
- [ ] Windows
- [ ] Haiku

We should take a run at this for 3.2.0 if possible.

**Comment by Semphriss** [comment]
I'll give this a try.

Posting this here now in case anybody else works on the task.

**Comment by Kontrabant** [comment]
The easiest way to handle this would be to add a window creation property like `SDL_PROP_WINDOW_CREATE_MODAL_BOOLEAN` and use the existing `SDL_PROP_WINDOW_CREATE_PARENT_POINTER` property to set the parent.

`SDL_SetWindowModalFor` was added specifically for the Linux version of the Unreal Engine editor, and as far as I can tell, it's still the only thing that actually uses it. My personal opinion of how to proceed would be to require passing the parent window at creation time for modal windows in SDL3 and remove the function from the public SDL3 API headers. For sdl2-compat, there are two possible solutions: keep the function internally in SDL3 and specially load it for sdl2-compat, or, completely remove it in SDL3, and sdl2-compat can just recreate the window with the modal parent when it is called. Unreal just calls `SDL_CreateWindow` followed by [setting the modal parent before the window is actually shown](https://github.com/EpicGames/UnrealEngine/blob/ee70eb2ee5a57dfd9be139a9ce20ab9cc1ef2487/Engine/Source/Runtime/ApplicationCore/Private/Linux/LinuxWindow.cpp#L352), so this should work correctly.

**Comment by Semphriss** [comment]
Before I proceed, I'd just like to confirm if it's okay to replace the function with a function like SDL_CreateWindowModal (or any other option, like add a parameter to SDL_CreateWindow, etc).

**Comment by slouken** [comment]
@Kontrabant’s approach sounds best to me.
