### ISSUE TITLE
[SDL3 migration] Migration for `SDL_SysWMinfo.info.uikit.framebuffer`

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#9430]
I have a simple question for SDL2 to SDL3 migration: How to migrate `SDL_GetWindowWMInfo()` + `SDL_SysWMinfo.info.uikit.framebuffer` usage to SDL3?

The [migration guide for `SDL_syswm.h`](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_syswmh) describes how to migrate `SDL_SysWMinfo` usages to window properties, but only does so for desktop platforms.

**Comment by slouken** [comment]
Excellent question. It looks like that was missed. I'll add this to the 3.2 milestone so we remember to implement this before release.

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by michaeleggers** [comment]
Sorry to jump in here into this closed issue but the migration guide states that the header has been removed and then it... uses the header? `SDL_SysWMInfo` is not available anymore to me. What do I miss here? 

EDIT: Whooops. I didn't scroll down far enough. Sorry! 💃
