### ISSUE TITLE
Suggestion for SDL3: Per window cursor visibility and style

### ISSUE THREAD

**Issue by circl-lastname** [libsdl-org/SDL#9431]
SDL3 currently can set cursor visibility (`SDL_HideCursor`) and style (`SDL_SetCursor`) globally, presumably for every window in the application. In a case where any application wishes to display a different cursor per window, it must detect the user's movement to said window and manually change the global cursor. I believe it may make more sense to accept a window argument, and make cursor properties based on the window.

**Comment by slouken** [comment]
I've been mulling this over, and I think it probably makes sense to leave this up to the application to handle in response to mouse focus events. For cursor changes, the cursor often changes depending on the content that is under the mouse. For cursor visibility, this is automatically handled for you if you have relative mode enabled, and is easy to implement yourself in response to focus events.

I think the ease of implementing this yourself means we can avoid the API complexity added to the common single window case by adding a window parameter to the mouse functions.

@icculus, thoughts?
