### ISSUE TITLE
Possible improvements for SDL_dialog

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#9432]
I've been reviewing my implementation of SDL_dialog, and I've had a few things come up to mind:
- Currently, the filters support the catch-all pattern `*` at any place in a list, e. g. `png;jpg;jpeg;*`. I see no meaningful utility in adding specific extensions if `*` is already present. Should I change the behavior to only allow the filter to be either a list of extension _or_ just the single catch-all pattern?
- Speaking of the filters, there's a lot of memory manipulation done around them, and I already expect the security vulnerabilities arising from that. Would it be worth adding a general function that validates the filter patterns and outright blocks the function call if a pattern list is malformed? It would probably not prevent all problems, but at least some of them. I'm mostly thinging of apps like game engines that may allow users to control the contents of the patterns.
- On non-Apple Unix platforms, the dialog can either use the XDG Portals implementation, or the Zenity implementation. Both have noticeable differences in their appearance and their behavior, and one might prefer, for example due to local problems, to force usage of one over the other. Would it be worth adding a hint to force-choose one method in particular, similarly to the hint that controls the video driver used?

Additionally, is there a recommended way to report security problems privately?

**Comment by slouken** [comment]
> * Currently, the filters support the catch-all pattern `*` at any place in a list, e. g. `png;jpg;jpeg;*`. I see no meaningful utility in adding specific extensions if `*` is already present. Should I change the behavior to only allow the filter to be either a list of extension _or_ just the single catch-all pattern?

Sure, that seems reasonable.

> * Speaking of the filters, there's a lot of memory manipulation done around them, and I already expect the security vulnerabilities arising from that. Would it be worth adding a general function that validates the filter patterns and outright blocks the function call if a pattern list is malformed?

This also seems reasonable.

> * On non-Apple Unix platforms, the dialog can either use the XDG Portals implementation, or the Zenity implementation. Both have noticeable differences in their appearance and their behavior, and one might prefer, for example due to local problems, to force usage of one over the other. Would it be worth adding a hint to force-choose one method in particular, similarly to the hint that controls the video driver used?

Yes, a hint for this is a good idea.

> Additionally, is there a recommended way to report security problems privately?

This is generally done via e-mail to slouken@libsdl.org.
