### ISSUE TITLE
Is it possible to activate the keyboard hint on iOS?

### ISSUE THREAD

**Issue by barisyild** [libsdl-org/SDL#9439]
The keyboard looks like the one below, is there any way to activate the hint?

![image](https://github.com/libsdl-org/SDL/assets/25794892/dec71082-a8b7-463c-beb9-009b1bb1921e)

**Comment by slouken** [comment]
This is a good question for the SDL discussion group:
http://discourse.libsdl.org/

The quick answer is that you should use SDL_StartTextInput()

**Comment by barisyild** [comment]
This is not what I'm talking about, when I use "SDL_StartTextInput" I don't get keyboard suggestions like in the image.

![image](https://github.com/libsdl-org/SDL/assets/25794892/01be4401-df8e-47c0-991f-2893af01ccee)

So the keyboard gives no hint in SDL.

**Comment by slouken** [comment]
We probably need to add some flags to SDL_StartTextInput() to define the style of input we want.

**Comment by ericoporto** [comment]
> We probably need to add some flags to SDL_StartTextInput() to define the style of input we want.

If this is possible to do it would be great because the Android keyboard used to be "Password" mode, which has no hint, and later was changed for "multiline" which has hint, in SDL2 (I think 2.24 version) and this change changes everything on how one would handle the received input.

**Comment by kambala-decapitator** [comment]
you could find the text field object at runtime and modify its configuration to your needs, something like this:
```objc
// root VC has class SDL_uikitviewcontroller
for (UIView* v in UIApplication.sharedApplication.keyWindow.rootViewController.view) {
  if (![v isKindOfClass:[UITextField class]])
    continue;
  UITextField* sdlTextField = (UITextField*)v;
  // now adjust properties of sdlTextField
  break;
}
```

**Comment by slouken** [comment]
Showing suggestions is now the default behavior in SDL3, and you can customize this with SDL_StartTextInputWithProperties()
