### ISSUE TITLE
SDL_error.h inclusion rule

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9444]
I was wondering when exactly the header `SDL_error.h` is included in other SDL headers.
Going through all headers I noticed that sometimes `SDL_error.h` is not included, but there are comments about calling `SDL_GetError()`.

Here are three lists about `SDL_error.h` inclusion.

SDL headers, which don't include `SDL_error.h` themself, but have a comment about calling `SDL_GetError()`:
```
SDL_camera.h
SDL_clipboard.h
SDL_dialog.h
SDL_filesystem.h
SDL_hidapi.h
SDL_hints.h
SDL_init.h
SDL_main.h
SDL_messagebox.h
SDL_misc.h
SDL_pixels.h
SDL_power.h
SDL_properties.h
SDL_render.h
SDL_stdinc.h (but SDL_error.h includes SDL_stdinc.h)
SDL_storage.h
SDL_surface.h
SDL_system.h
SDL_version.h
SDL_video.h
SDL_vulkan.h
```

SDL headers, which don't include `SDL_error.h` themself and don't include other headers, which include `SDL_error.h`, but have a comment about calling `SDL_GetError()`:
```
SDL_clipboard.h
SDL_filesystem.h
SDL_hidapi.h
SDL_hints.h
SDL_init.h
SDL_misc.h
SDL_pixels.h
SDL_power.h
SDL_properties.h
SDL_version.h
SDL_stdinc.h (but SDL_error.h includes SDL_stdinc.h)
SDL_storage.h
```
  
SDL headers, which include `SDL_error.h` but don't have a comment about calling `SDL_GetError()`:
```
SDL_locale.h
SDL_quit.h
```

What exactly is the rule for `SDL_error.h` inclusion?

**Comment by slouken** [comment]
I haven't really thought it through, but it seems like any function that can return an error ought to include SDL_error.h, unless it's a header that's included by SDL_error.h itself.

We generally suggest doing `#include <SDL3/SDL.h>` so it hasn't really come up, but if you want to create a PR to standardize this, feel free!

**Comment by Sackzement** [comment]
> We generally suggest doing #include <SDL3/SDL.h> so it hasn't really come up, but if you want to create a PR to
> standardize this, feel free!

I find it more expressive, if I only include the headers, which will actually be used.
And it should make the compiler's life easier, if there isn't so much included in all translation units.
