### ISSUE TITLE
The camera subsystem does not detect the cameras those hot plugged/unplugged

### ISSUE THREAD

**Issue by joey-cyt** [libsdl-org/SDL#9455]
(Tested on Windows 11)
With current main branch, periodically call the following code:

>         SDL_CameraDeviceID* pDeviceList = SDL_GetCameraDevices(&nDevices);
>         for (int i = 0; i < nDevices; ++i)
>         {
>             char* pName = SDL_GetCameraDeviceName(pDeviceList[i]);
>             printf("Found video: %s\n", pName);
>             ...

The reported cameras are always those plugged in before the program started. While the program running, unplugging or plugging a new camera does not make the reported list any different.
The similar test code to report microphone (audio capture device) works as expected - the reporting changes upon hot plugging/unplugging.

**Comment by icculus** [comment]
Camera hotplug for Windows isn't hooked up yet. I'll take a look at this soon.

**Comment by joey-cyt** [comment]
Thank your very much, icculus!

**Comment by icculus** [comment]
This work is being tracked over in #9108 now, so I'll close this issue as a duplicate.
