### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by kdschlosser** [libsdl-org/SDL#9456]
Why is there only a 2 year old version of SDL2 available for use in the package index for Ubuntu 22.04??... There is a newer release available for Ubuntu 24.04 but that version of Ubuntu isn't even in beta test yet. Are newer versions of SDL2 not compatible with Ubuntu 22.04??

I help out with the development of LVGL and this really puts a kink in using LVGL on a desktop. Especially on Windows using WSL because Ubuntu 24.04 is only available as a test version for WSL. Having to compile SDL2 when using a CI is also an extra step that is going to take some time to do when the CI resources are already pretty tight. It would be so much nicer if there is a binary for Ubuntu 22.04 that is a newer version than 2.20.0. Specifically need 2.24.0 or above.

**Comment by slime73** [comment]
You'd have to ask Ubuntu's package maintainers I think. Typically software developers aren't the ones deciding whether a package in a linux distro for their software should be updated.

**Comment by kdschlosser** [comment]
No the folks over at Ubuntu are not responsible for maintaining the packages in the index. It is the responsibility of whoever added the package to the index. I would have thought that to be the developers of SDL.

**Comment by kdschlosser** [comment]
It appears like one of these folks is responsible for maintaining it.

* Sam Hocevar
* Manuel A. Fernandez Montecelo
* Felix Geyer
* Simon McVittie

**Comment by madebr** [comment]
I think the policy of Ubuntu is to pick a SDL2 version for a Ubuntu release, and keep it stable during its life cycle.
Bumping SDL2 to a new major release means rebuilding or retesting all consumers, which is only done when doing a new distro release.

https://packages.ubuntu.com/search?keywords=libsdl2

Besides, 22.04 is a LTS release. LTS stands for Long Term Support, not for Long Term updateS.

If you have a problem with the old version on GitHub Actions, there is [setup-sdl](https://github.com/libsdl-org/setup-sdl).
