### ISSUE TITLE
Report mouse wheel scroll state through a function 

### ISSUE THREAD

**Issue by duerdak** [libsdl-org/SDL#9459]
SDL allows you to poll mouse and keyboard state with SDL_GetMouseState() and SDL_GetKeyboardState(). But mouse scroll wheel state is only reported through events. Can a similiar function as the above ones be added for scroll wheel state - something like SDL_GetScrollWheelState() where you pass in two variables for the amount scrolled?

**Comment by slime73** [comment]
Scroll wheels don't have a state, at a hardware level - they're just immediate actions.

**Comment by duerdak** [comment]
> Scroll wheels don't have a state, at a hardware level - they're just immediate actions.

I see what you mean after checking the [docs ](https://wiki.libsdl.org/SDL2/SDL_MouseWheelEvent) some more. It's not actually a state, more so the event reports an amount that has been scrolled. I'll go ahead and close this issue.
