### ISSUE TITLE
Cannot build SDL3 for iOS or tvOS using CMake

### ISSUE THREAD

**Issue by Ravbug** [libsdl-org/SDL#9462]
If I use the following command:
```sh
cmake -G "Xcode" -DCMAKE_SYSTEM_NAME=tvOS ..
```
SDL's CMake config reports the correct platform:
```
-- SDL3 was configured with the following options:
-- 
-- Platform: tvOS
-- 64-bit:   TRUE
```

However, I get the following compile error:
```cpp
/Users/admin/Downloads/sdl3-sample/SDL/src/dialog/cocoa/SDL_cocoadialog.m:24:9: fatal error: 'Cocoa/Cocoa.h' file not found
#import <Cocoa/Cocoa.h>
 ^~~~~~~~~~~~~~~
1 error generated.
```
It appears that SDL_cocoadialog.m is erroneously being included on iOS and tvOS. If I compile for macOS, this error does not occur.

**Comment by madebr** [comment]
Building SDL23 using CMake for Apple products is only tested for macos on ci. ios/tvos are only built using the xcode project, and visionos currently skipped.
So it shouldn't really be a big surprise if those targets fail to build.
My lack of an Apple system is also not helping the cause :)

Anyhow, can you please [open the xcode project](https://github.com/libsdl-org/SDL/blob/main/Xcode/SDL/SDL.xcodeproj/project.pbxproj) and see how the it is handled there? CMake should just copycat its behavior.

**Comment by Ravbug** [comment]
The Xcode project appears to work for both iOS and tvOS. It appears that `SDL_cocoadialog.m` is skipped in those cases.

**Comment by Semphriss** [comment]
Looks like something that's my fault. If the dialog files are the only thing that fail, it's very very very very likely that I just failed to configure something properly. I'll give it a look when I can.

**Comment by slime73** [comment]
The platform includes (`<Cocoa/Cocoa.h>` and `<UniformTypeIdentifiers/UTType.h>`) in cocoadialog.m are missing the `SDL_PLATFORM_TVOS` and `SDL_PLATFORM_IOS` define checks that the contents of `show_file_dialog` have.

That being said, building the file for tvOS/iOS in the first place might not be wanted.

**Comment by Semphriss** [comment]
Indeed, I think just switching the CMake platform check from `APPLE` to `MACOS` should be enough. THe PR appears to do that already, so it should be good.
