### ISSUE TITLE
With SDL 3.1.1, In pixels colors, Rmask, Gmask, Bmask, Rshift, Gshift and Bshift don't match to real positions coponents of color pixel

### ISSUE THREAD

**Issue by ArnaudNRoses** [libsdl-org/SDL#9466]
With SDL 3.1.1, In pixels colors, Rmask, Gmask, Bmask, Rshift, Gshift and Bshift don't match to real positions coponents of color pixel

I Try many formats and it don't work if we use masks and shift.

I tested formats in 32 bits or 24 bits with or without alpha and 8 bits per coponents colors in differents order.

I don't understand why....

**Comment by slouken** [comment]
Can you provide a simple repro case for this?

**Comment by ArnaudNRoses** [comment]
> Can you provide a simple repro case for this?

How can I do this ?
I cannot give you my "project" by email the site d'ont want this....I tryed....
I d'ont how as well...

**Comment by slouken** [comment]
Can you just copy and paste the code you're using to check the mask and shift values?

**Comment by ArnaudNRoses** [comment]
I hope It's well...
[test sdl.zip](https://github.com/user-attachments/files/15517992/test.sdl.zip)

**Comment by slouken** [comment]
Thanks for the test case.

You set _FormatImages to SDL_PIXELFORMAT_RGBA32, which means that _DecalageOctetsR = 0, _DecalageOctetsG = 1, _DecalageOctetsB = 2, _DecalageOctetsA = 3. The indices are in the same order of the pixel format "R G B A".

If you had set _FormatImages to SDL_PIXELFORMAT_BGRA32, then you would get the colors you expect.

What's a little confusing is that those names are in byte array order, but they map to other names which are packed 32-bit values, and those names correspond to the packing order in high bits to low bits. So for example, on little endian systems like a PC, SDL_PIXELFORMAT_RGBA32 will be SDL_PIXELFORMAT_ABGR8888, and on big endian systems, like the old PowerPC macs, SDL_PIXELFORMAT_RGBA32 will be SDL_PIXELFORMAT_ARGB8888. The byte order doesn't change, but the ordering within a 32-bit word does.

**Comment by slouken** [comment]
Since you are indexing the color components as bytes, you want to use SDL_PIXELFORMAT_RGBA32 or SDL_PIXELFORMAT_BGRA32 for your image format, depending on what component order you want to use.

**Comment by ArnaudNRoses** [comment]
SEE README FILE !!!!!!

I said It's don't work....
I know what I meaan...

**Comment by ArnaudNRoses** [comment]
I explain It in readme file....

**Comment by ArnaudNRoses** [comment]
or the function SDL for converting  format surface dosen't wortk.....

**Comment by ArnaudNRoses** [comment]
I know It's the wrongs parameters for offsets but It's works ,When I set the " regular formula " It's don't works ( see readme file I explain it ....)

**Comment by ArnaudNRoses** [comment]
PS SDL 3 the better version of SDL I love it ! Can I contribuate ? ( for setting docs in the wiki.... or something else.... like that )

"regular formula " is in comment in the code...

**Comment by slouken** [comment]
This is the formula you want, but it only works for 32-bit formats:
```c
			_DecalageOctetsR = ( Format->Rshift / _BitsPerComponentPixel );
			_DecalageOctetsG = ( Format->Gshift / _BitsPerComponentPixel );
			_DecalageOctetsB = ( Format->Bshift / _BitsPerComponentPixel );
			_DecalageOctetsA = ( Format->Ashift / _BitsPerComponentPixel );
```

**Comment by ArnaudNRoses** [comment]
It's to me to take care of the endianess of the machine in SDL or The Rshift value(s) is not what I'm waiting for, an offset like in opengl (or on the others...), or I' don't understand at all ????

**Comment by slouken** [comment]
If you use pixels as arrays of bytes, the format shift and loss aren't useful. Instead you can just look at the name of the format, e.g. RGBA32, and hard code the offsets. For RGBA32 for example, the offsets are in the name of the format - R = 0, G = 1, B = 2, A = 3.

If you use pixels as native words, then you would use a pointer of the appropriately sized type and use the shift and mask to place the channels inside that pixel. This is necessary for 16-bit formats, for example.

Here is code demonstrating how that's done:
[X](https://github.com/libsdl-org/SDL/blob/fd2b9c060291af8ba3388f18b3b0000e81e41643/src/video/SDL_pixels.c#L1269)

If you have further questions, please ask on the forums:
https://discourse.libsdl.org/c/sdl-development/6

**Comment by ArnaudNRoses** [comment]
Thanks for your answer !
so shift, loss and masks are made for using / reading with "32bits struct" directly pixels in memery because the systems videos acess them in 32 bits value for speed, alignement ect..... ain't that and only that ?

if I convert all image of my classes in the pixel format of my screen, it's speed up my app no ?

I consider in my classes only pixels formats with 8 bits per component pixels ( who uses less than 256 colors today ?????? ),
so 3 or 4 bytes by pixels, and I would like a " universal formula " for readings / writings pixels for grey the image or red the image but 

1 :  the only difference between my formula and your formula is the byte order, so shifts and masks is not affetecd by th byte order .... ain't normal ??????

_BytesPerPixel = Format->bytes_per_pixel;

_BitsPerComponentPixel = Format->bits_per_pixel / Format->bytes_per_pixel;

//your formula :

_DecalageOctetsR = (Format->Rshift / _BitsPerComponentPixel);
_DecalageOctetsG = (Format->Gshift / _BitsPerComponentPixel);
_DecalageOctetsB = (Format->Bshift / _BitsPerComponentPixel);
_DecalageOctetsA = (Format->Ashift / _BitsPerComponentPixel);

// my formula :
//_DecalageOctetsR = (_BytesPerPixel - 1) - (Format->Rshift / _BitsPerComponentPixel);
//_DecalageOctetsG = (_BytesPerPixel - 1) - (Format->Gshift / _BitsPerComponentPixel);
//_DecalageOctetsB = (_BytesPerPixel - 1) - (Format->Bshift / _BitsPerComponentPixel);
//_DecalageOctetsA = (_BytesPerPixel - 1) - (Format->Ashift / _BitsPerComponentPixel);

![Sans titre2](https://github.com/libsdl-org/SDL/assets/92106896/d3d6ce26-9397-43a4-bba3-cf1d9354d4f3)

after this It's my formula that would works ( no ???? )
But It's don't .... I don't understand at all... why It's to me of take care of the byte order for having positions pixels .....

2 : Your formula works / don't works in this cases 

 //  _FormatImages = SDL_PIXELFORMAT_ABGR8888;//work
//  _FormatImages = SDL_PIXELFORMAT_BGRA8888;//work
//  _FormatImages = SDL_PIXELFORMAT_ARGB8888;//work
//  _FormatImages = SDL_PIXELFORMAT_RGBA8888;//work
//  _FormatImages = SDL_PIXELFORMAT_XBGR8888;//don't work
//  _FormatImages = SDL_PIXELFORMAT_BGRX8888;//don't work
//  _FormatImages = SDL_PIXELFORMAT_XRGB8888;//don't work
//  _FormatImages = SDL_PIXELFORMAT_RGBX8888;//don't work
//  _FormatImages = SDL_PIXELFORMAT_RGBA32;//work
//  _FormatImages = SDL_PIXELFORMAT_ARGB32;//work
//  _FormatImages = SDL_PIXELFORMAT_BGRA32;//work
//  _FormatImages = SDL_PIXELFORMAT_ABGR32;//work
//  _FormatImages = SDL_PIXELFORMAT_RGBX32;//don't work
//  _FormatImages = SDL_PIXELFORMAT_XRGB32;//don't work
//  _FormatImages = SDL_PIXELFORMAT_BGRX32;//don't work
//  _FormatImages = SDL_PIXELFORMAT_XBGR32;//don't work
//  _FormatImages = SDL_PIXELFORMAT_BGR24;//don't work
//  _FormatImages = SDL_PIXELFORMAT_RGB24;//don't work

so ain't it a problem ?????

**Comment by ArnaudNRoses** [comment]
I hope You understand what I mean.....

**Comment by ArnaudNRoses** [comment]
Thanks  for your help !!!!

I find my errors....
