### ISSUE TITLE
Remove SDL_WinRTGetFSPath

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9470]
```c
typedef enum
{
    /** The installed app's root directory.
        Files here are likely to be read-only. */
    SDL_WINRT_PATH_INSTALLED_LOCATION,

    /** The app's local data store.  Files may be written here */
    SDL_WINRT_PATH_LOCAL_FOLDER,

    /** The app's roaming data store.  Unsupported on Windows Phone.
        Files written here may be copied to other machines via a network
        connection.
    */
    SDL_WINRT_PATH_ROAMING_FOLDER,

    /** The app's temporary data store.  Unsupported on Windows Phone.
        Files written here may be deleted at any time. */
    SDL_WINRT_PATH_TEMP_FOLDER
} SDL_WinRT_Path;

extern DECLSPEC const wchar_t * SDLCALL SDL_WinRTGetFSPathUNICODE(SDL_WinRT_Path pathType);
```

I think this predates SDL_GetBasePath, SDL_GetPrefPath, and SDL_GetUserFolder. We should see if this function can be folded into there, if the functionality isn't already duplicated, and remove this.

Even if we keep it, this function has "UNICODE" and "UTF8" versions, and the "Unicode" one should go away in any case.

**Comment by slouken** [comment]
Do we already expose easy functions for converting between wchar and utf-8?

**Comment by icculus** [comment]
> Do we already expose easy functions for converting between wchar and utf-8?

We have WIN_StringToUTF8 and WIN_UTF8ToString macros internally that are prettier versions of calls to SDL_iconv_string.

**Comment by icculus** [comment]
Okay, so SDL_WinRTGetFSPath returns locations that SDL_GetUserFolder doesn't (and are sort of WinRT specific), so I've removed the separate Unicode/UTF-8 versions from the API and left it at that.

This is updated for sdl2-compat in https://github.com/libsdl-org/sdl2-compat/commit/e17992cf2226bc6110317e0460b16dabc7734ce5
