### ISSUE TITLE
SDL3 audio playback progress?

### ISSUE THREAD

**Issue by MrJokerBoy** [libsdl-org/SDL#9472]
Hello, how can I get the audio playback progress using SDL 3.1.1?

**Comment by icculus** [comment]
You can use an SDL_AudioStreamCallback to be notified when data is consumed by the audio device (and maybe add more data to the stream during the callback; this technique is about the same as the SDL2 audio interface), or you can call SDL_GetAudioStreamQueued to see how much data is still pending in a stream; as this number goes down, it means the device has consumed more of it.

**Comment by MrJokerBoy** [comment]
Okay, thank you for the ideas.
