### ISSUE TITLE
Reduce SDL_Event padding?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9477]
Currently we pad all SDL_Events to 128 bytes; this is a holdover from when there were events with static buffers for text input, filenames, etc.

The largest structs in the event union (on this 64-bit Linux machine) are SDL_PenButtonEvent, SDL_PenMotionEvent, and SDL_PenTipEvent, at 64 bytes each.

Do we want to drop the padding to a smaller amount for SDL3?

**Comment by cgutman** [comment]
Personally, I would leave the padding alone. I don't think the benefits outweigh the costs to future extensibility of SDL3.

`SDL_Event` is one of the few structs we can modify without breaking the ABI for existing code. The padding we choose for SDL3 is going to have to last until the next major version of SDL when we can break the ABI again. If we can't fit whatever new event or fields we want to add in the existing padding, we're screwed and the feature will be stuck waiting for SDL4.

**Comment by icculus** [comment]
True, a little extra wouldn't hurt, but we have a system in place now to manage memory for thing that need buffers, like drag-and-drop events, so we're unlikely to need _double_ the largest event, as something with that much data would likely allocate a buffer for it.

**Comment by slouken** [comment]
We could reduce the padding to 80, but I'm not sure that buys us much, practically speaking.

**Comment by icculus** [comment]
Eh, let's leave it be, then.
