### ISSUE TITLE
FIXME in SDL_haptic.h

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9480]
```c
/* FIXME: For SDL 2.1, adjust all the magnitude variables to be Uint16 (0xFFFF).
 *
 * At the moment the magnitude variables are mixed between signed/unsigned, and
 * it is also not made clear that ALL of those variables expect a max of 0x7FFF.
 *
 * Some platforms may have higher precision than that (Linux FF, Windows XInput)
 * so we should fix the inconsistency in favor of higher possible precision,
 * adjusting for platforms that use different scales.
 * -flibit
 */
```

Did we ever change this?

CC @flibitijibibo

**Comment by flibitijibibo** [comment]
I don't think we ever made it consistent, no... I think we also still need to expand the haptic type enum size so that square fits again, but I haven't thought about SDL_haptic for a long while 😅

**Comment by slouken** [comment]
Square was re-added, but magnitude hasn’t been changed. If we still want to do this, it should be added to our 3.0 ABI checklist.

**Comment by icculus** [comment]
I'm wondering if we should bother changing the magnitude; it's not hurting anyone, we don't really have the hardware to make sure we didn't break it on various platforms.

**Comment by slouken** [comment]
Yeah, let's leave this as-is for now.
