### ISSUE TITLE
Remove SDL_KMOD_RESERVED?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9481]
In SDL_Keymod:

```c
    SDL_KMOD_RESERVED = SDL_KMOD_SCROLL /* This is for source-level compatibility with SDL 2.0.0. */
```

Based on the comment, this should probably be removed in SDL3, as source-level SDL2 compat isn't really a thing here.

**Comment by icculus** [comment]
@slouken, we can dump this one, right?

**Comment by slouken** [comment]
Yup.
