### ISSUE TITLE
Add the missing types/macros equivalent to C99 stdint.h and inttypes.h

### ISSUE THREAD

**Issue by nightmareci** [libsdl-org/SDL#9482]
SDL already provides much of what C99 stdint.h provides, like the fixed with integer types (`Uint32`, etc.) and inttypes.h's printf macros (`SDL_PRI*`). But there's utility in filling out the rest of what stdint.h and inttypes.h provide:
* `intptr_t`, `uintptr_t`, and `uintmax_t`. There's situations of using `void*` to contain `intptr_t`, like callbacks taking a userdata pointer. Storing an integer in userdata when that's all you need can simplify things a bit, not having to pass a data structure pointer (possibly malloc'd) just for a single integer:
```c
int x = 5;

/* Set userdata to an integer, to be read by the callback code later. */
userdata = (void*)(intptr_t)x;

/* Get the integer in the callback code. */
int x = (int)(intptr_t)userdata;
```
I've run code using the `(void*)(intptr_t)`/`(int)(inptr_t)` pattern on a variety of architectures, and it seems to work as expected (32-bit x86 and ARM, 64-bit x86 and ARM). Though if you intend to target 32-bit platforms, `intptr_t` won't be 64-bit, so you have to stay 32-bit or under in that case (probably best to use fixed width types there).

Also, it can be handy to store a 64-bit integer into an atomic pointer, though that requires checking if your platform is 64-bit, falling back to another solution on 32-bit platforms. If you don't need atomic add/subtract, that's a usable solution.
* The `*_C` macros. They're useful for constructing constants that will always work, regardless of the data model of target platforms. Though you can get by without them, for constants 32-bit or smaller, by just using ordinary `int`/`unsigned int` constants. The C standard says `int` constants are at a minimum 16-bit, but in practice they're 32-bit or larger on all(?) platforms targetable by SDL.
* The fast/least types can come in handy sometimes, when it's acceptable to use a larger type temporarily, to ensure math operates in the best register size of a CPU architecture, casting to the not-fast type required at the end of the math.
* The `SCN*` equivalent macros are missing, and some of the `PRI*` macros (like ones for pointers).

**Comment by slouken** [comment]
We should review this for the SDL 3.0 milestone. Aside from the PRI* macros, I'm inclined not to add them since the application is likely already in an environment that provides intptr_t, etc.

@libsdl-org/a-team, thoughts?

**Comment by madebr** [comment]
I would not know how to define `size_t`, `uintptr_t`, `intptr_t`, ... without some kind of (cmake) configuration.
These, and the fast/least macros depend on the target architectures, which is a job for the platform toolchains.
Aren't the `SCN*` macros equal to the `PRI*` macros?

**Comment by sezero** [comment]
> I would not know how to define `size_t`, `uintptr_t`, `intptr_t`, ... without some kind of (cmake) configuration.

We shouldn't, not ever

> These, and the fast/least macros depend on the target architectures, which is a job for the platform toolchains.

Yes. We already are including stdint.h

> Aren't the `SCN*` macros equal to the `PRI*` macros?

Not necessarily. E.g., %d and %i aren't exactly the same for scanf, if I recall correctly..

Re: `(void*)(intptr_t)x` and `(int)(intptr_t)pointer` :

Maybe (just maybe) add SDL_INT2PTR and SDL_PTR2INT macros?
(possibly not really necassary...)

**Comment by slouken** [comment]
Since we include stdint.h, I'm going to go ahead and close this as not planned. SDL isn't actually intending to be a complete C environment. We discussed removing the sized SDL types in favor of the stdint types, but we decided against it to make it easy to port patches between SDL2 and SDL3.
