### ISSUE TITLE
SDL_VIRTUAL_JOYSTICK_DESC_VERSION

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9489]
```c
/**
 * The structure that defines an extended virtual joystick description
 *
 * The caller must zero the structure and then initialize the version with `SDL_VIRTUAL_JOYSTICK_DESC_VERSION` before passing it to SDL_AttachVirtualJoystickEx()
 *  All other elements of this structure are optional and can be left 0.
 * ...
 */
```

Should we change this to work like SDL_IOStream and SDL_Storage? You create an object from a standard interface, and if we need to change it, we'll add a new function and struct?

**Comment by slouken** [comment]
Yep, for the same reasons we did it there.

**Comment by icculus** [comment]
This is done, and sdl2-compat is updated in https://github.com/libsdl-org/sdl2-compat/commit/2fe62be59e449a6f25455097c394dc4111a79115
