### ISSUE TITLE
"This hint should be set before enumerating controllers."

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9490]
Several hints say, in their documentation: "This hint should be set before enumerating controllers."

Is this still true in SDL3? In SDL2, enumeration was often a "throw away the existing stuff and do a new query", but now that we return lists instead of counts, is this still where this happens, or has this moved to init?

**Comment by icculus** [comment]
Pinging @slouken, since this question probably got lost in the notifications flood this week.

**Comment by slouken** [comment]
These hints are dynamic, but will potentially cause orphaned joysticks if they change while a controller is opened. That was the verbiage to reflect when it's safe to do that. I'm open to changing it to "before initializing joysticks and gamepads" if that's more clear.
