### ISSUE TITLE
Bug in SDL 3.1.0: SDL_CreateRenderer doesn't respect "vsync off" on direct3d11 renderer..

### ISSUE THREAD

**Issue by oscarbg** [libsdl-org/SDL#9492]
Hi,
I modified testnative.c on Windows changing:
>SDL_CreateRenderer(window, NULL, 0);

with:
```
    if (use_vsync)
        flags |= SDL_RENDERER_PRESENTVSYNC;
char* drivers[4] = {"direct3d11","direct3d12","opengl","vulkan" };
    int drvnum = 3;
    renderer = SDL_CreateRenderer(window, drivers[drvnum], flags);
```
to test vsync off/on support on 4 APIs..
it works OK except with direct3d11, i.e with:
>renderer = SDL_CreateRenderer(window, "direct3d11", 0);

I get vsync on eqaully as:
>renderer = SDL_CreateRenderer(window, "direct3d11", SDL_RENDERER_PRESENTVSYNC);

**Comment by slouken** [comment]
SDL_CreateRenderer() no longer takes flags, you can set your desired vsync behavior after creating the renderer. I tested this with the direct3d11 renderer and I do not get vsync behavior, so I think this is fixed. Please reopen this if you're still seeing the issue with the latest SDL3 code.
