### ISSUE TITLE
Windows SDL_INIT_GAMEPAD setting errors on success.

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9495]
In SDL_hidapijostick.c, `devs = SDL_hid_enumerate(0, 0);` repeatedly sets an error: "No HID devices found in the system." during `SDL_INIT_GAMEPAD` despite success. I understand `SDL_GetError()` shouldn't be used for error-checking, but nearly 100% of methods are `SDL_GetError()` silent when they succeed, so when an error gets set, it almost always indicates something's broken internally. 

The above is a recent thing. `SDL_INIT_GAMEPAD` was silent on success up until a change few weeks ago. It's currently the only place an error gets set when nothing goes wrong (at least on Windows), so I think I'm just checking if this is intentional so we can possibly keep this trend of `SDL_GetError()` being silent on success (there was mention of perhaps having this is a reliable feature).

Should `hid_enumerate()` be calling `register_global_error` when `vendor_id == 0 && product_id == 0` ?

I apologise in advance if this isn't an issue, but I like the idea of keeping `SDL_GetError()` quiet on non-errors.

**Comment by slouken** [comment]
No, you should never take an error being set as a failure condition. There are many places internally where there are errors set but are recoverable.
