### ISSUE TITLE
Can't receive any events if create SDL_Window from AvaloniaUI NativeControlHost on x11.

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#9503]
Create a sdl window by Avalonia NativeControlHost's platform handle shows black window on x11, it seems underlying window can't gets resized, when I resize underlying window manually, it shows, however it detached from Avalonia window, can't embedded in main window. It works no problem on windows platform, I don't know if this is a SDL bug, or an Avalonia bug?
[Avalonia x11 bug](https://github.com/AvaloniaUI/Avalonia/issues/15284#issue-2233095610)

**Comment by madebr** [comment]
Can you please provide a (small) reproducer?
That way triage will go a lot faster.

**Comment by sandsc** [comment]
using code 
`  SDL_SetNumberProperty(sdlPid, SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER,
                                  reinterpret_cast<Sint64>(handle));` 
instead of
`  SDL_Setroperty(sdlPid, SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER,
                                  handle);` 
now NativeControlHost's  can embedded in Avalonia window,  I guess that x11 window handle should be passed as number value, or a toplevel window created,  but a new issue has arisen, I can't receive any input events if it is a embedded child window.  
I will provide a small app to reproduce the bugs later, thanks for any helps.

**Comment by sandsc** [comment]
Here is screenshot on **Linux x11**, only `SDL_EVENT_WINDOW_SHOWN` and `SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED` events received when app started. but all input and window events can be received on **Windows** platform.
>
![2024-04-10](https://github.com/libsdl-org/SDL/assets/1673854/d3884b8f-2f21-4c64-adaa-975efc4fdc4b)

**Comment by sandsc** [comment]
In [SDL_x11window](https://github.com/libsdl-org/SDL/blob/f121553082cc4a68784c10b8ad896d34e9412449/src/video/x11/SDL_x11window.c#L459) When creating window for external window, add some code for set event mask for external window, then events can be received, I'm not very familiar with x11 programming and don't know if this's the right way to fix.
```
 if (w) {
        window->flags |= SDL_WINDOW_EXTERNAL;
        if (SetupWindowData(_this, window, w) < 0) {
            return -1;
        }
        unsigned int keyboard_events = KeyPressMask | KeyReleaseMask;
        unsigned int pointer_events = ButtonPressMask | ButtonReleaseMask | PointerMotionMask | ButtonMotionMask;
        X11_Xinput2SelectMouseAndKeyboard(_this, window);

        SDL_WindowData *wd = window->driverdata;
        /* If XInput2 can handle pointer and keyboard events, we don't track them here */
        if (wd->xinput2_keyboard_enabled) {
            keyboard_events = 0;
        }
        if (wd->xinput2_mouse_enabled) {
            pointer_events = 0;
        }
        Display *display = _this->driverdata->display;
        X11_XSelectInput(display, w,
                         (FocusChangeMask | EnterWindowMask | LeaveWindowMask | StructureNotifyMask |
                          keyboard_events | pointer_events));
        return 0;
    }
```

**Comment by slouken** [comment]
Fixed, thanks!
