### ISSUE TITLE
[SDL3] SDL_CreateTexture() doesn't always store a texture's ACTUAL pixel format

### ISSUE THREAD

**Issue by sridenour** [libsdl-org/SDL#9504]
Recently discovered that `SDL_CreateTexture()` doesn't fail on unsupported texture formats like the docs say it does, but it instead chooses an alternate format.

### ISSUE: ###
Mismatches with the docs aside, `SDL_CreateTexture()` stores the requested pixel format in the texture struct BEFORE checking if the renderer supports it, *and then never changes it if an alternate format gets used instead*. So an application can't even use `SDL_QueryTexture()` to see what it got!

Shouldn't `SDL_CreateTexture()` fail if the pixel format is unsupported? At the very least, it should store the *actual* pixel format so the application can pixel data in the right format!

**Comment by sridenour** [comment]
I came across this when playing around with the camera API.

With my camera, `testcamera.c` shows junk on the screen. My camera's native pixel format is UYVY, which the Metal renderer doesn't support (at least not on my GPU). But instead of failing, `SDL_CreateTexture()` silently chooses a different format, and so `testcamera.c` uploads pixel data from the camera API in UVYV format, which doesn't match the pixel format SDL chose, ergo junk on the screen.

The bug (`SDL_CreateTexture()` not storing the alternate format it chose) makes it worse, because adding a call to `SDL_QueryTexture()` doesn't reveal the actual underlying pixel format, so no format conversion can be done.

**Comment by slouken** [comment]
I'm going to reopen this. What should have happened it that it would pick a different underlying texture format and then converted when you uploaded texture data. I'll see what testyuv shows in this case.

**Comment by slouken** [comment]
I double checked and `testyuv --uyvy` will create a texture in UYVY format, which, since it's not supported on Metal, will create an ARGB native texture for actual rendering. When pixels are uploaded to the UYVY texture, they are converted to ARGB and the texture renders normally.

**Comment by slouken** [comment]
Since you went ahead and closed this bug, I'll assume you figured out your issue. Please feel free to reopen this if I've misunderstood the problem or you don't have a solution.
