### ISSUE TITLE
`Wayland_GetWindowSizeInPixels` not always filling the `w` and `h` parameters

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#9530]
The source code for that function is:

```c
void Wayland_GetWindowSizeInPixels(SDL_VideoDevice *_this, SDL_Window *window, int *w, int *h)
{
    SDL_WindowData *data;
    if (window->driverdata) {
        data = window->driverdata;
        *w = data->current.drawable_width;
        *h = data->current.drawable_height;
    }
}
```

If `window->driverdata` is null, both arguments are left unset silently; no error is reported. Is that normal behavior?

I often leave the variables unset before passing them to similar functions, which means that they would be left uninitialized after the function call.

**Comment by Kontrabant** [comment]
Actually, the window driverdata should never be null here, so the check is probably unnecessary.  The window data is allocated at the same time as the higher level window object and is not released until the window is destroyed.

**Comment by slouken** [comment]
You can open a PR that changes this to an SDL_assert() and removes the check.
