### ISSUE TITLE
[SDL2] VK_ERROR_OUT_OF_DATE_KHR not happens on window resize on Wayland

### ISSUE THREAD

**Issue by DragonSWDev** [libsdl-org/SDL#9531]
When window is resized vkAcquireNextImageKHR result is VK_ERROR_OUT_OF_DATE_KHR. At least this is how it works on most platforms. On Wayland that is not a thing. Changing window size is not making vkAcquireNextImageKHR return VK_ERROR_OUT_OF_DATE_KHR. That means application that is working fine under X11 and reacts properly to changing window size, on Wayland it is unable to do so. I have NVIDIA GPU, I also tried it on lavapipe and the result is same.

**Comment by Kontrabant** [comment]
Wayland buffer surfaces aren't tied to the window size in the way it is on other windowing environments, so the window changing size doesn't necessarily mean that the backbuffer needs to be resized. Particularly when using viewports, the buffers can be scaled and often differ from the window size, such as when using a high-DPI desktop, scaling fullscreen output, only displaying a portion of the buffer, etc...

You need to watch the window and backbuffer sizes reported by SDL and react to that.

**Comment by DragonSWDev** [comment]
@Kontrabant Thank you for explanation.
