### ISSUE TITLE
Xbox controllers not properly working via SDL3 gamepad api

### ISSUE THREAD

**Issue by TylerGlaiel** [libsdl-org/SDL#9533]
on windows 10

Ps4 controller I tested with works fine.

The xbox controllers I've tested (xbox elite 2 1 via bluetooth and usb, and an xbox one controller via usb) only emit events when the left or right trigger is pressed, and do not emit events for any other buttons or axis. Neither SDL_EVENT_GAMEPAD_BUTTON_DOWN nor SDL_EVENT_JOYSTICK_BUTTON_DOWN are triggering

(using version prerelease 3.1.1)

**Comment by TylerGlaiel** [comment]
from attempting to debug this, the xbox controllers are using the RAWINPUT driver, and the ps4 controller is using the HIDAPI driver

**Comment by TylerGlaiel** [comment]
If I remove SDL_RAWINPUT_JoystickDriver from the driver list in SDL_joystick_drivers[] (SDL_joystick.c) the controller works again, so there's definitely something up there

**Comment by slouken** [comment]
Are you able to reproduce this with testcontroller in the SDL project?

**Comment by TylerGlaiel** [comment]
it works on testcontroller, let me check to see what I'm doing differently in my project...

**Comment by TylerGlaiel** [comment]
ok, the thing I was doing different was I was calling "SDL_INIT_GAMEPAD | SDL_INIT_JOYSTICK" later (after initializing video, events, timer, audio, opening the window), if I init gamepad and joystick at the same time as the rest the controller works.


From testing this in my project the behavior changes if I init the gamepad and joystick subsystems *after* opening a window (but before creating an opengl context). I can see if I can reproduce this in testcontroller

**Comment by TylerGlaiel** [comment]
The issue still exists with the steam API disabled, though only if I wait until after my loading screen to init the subsystems

**Comment by TylerGlaiel** [comment]
ok I narrowed it down to actually me initializing SDL_GAMEPAD and SDL_JOYSTICK on a different thread than my main thread... can chalk this up to user error I guess (though I don't think I had issues doing this in SDL2?)

**Comment by slouken** [comment]
Does setting `SDL_HINT_JOYSTICK_THREAD` help you?

**Comment by TylerGlaiel** [comment]
yes actually that does fix the issue

**Comment by slouken** [comment]
Great. Where in the headers or documentation would you expect to find that tip?

**Comment by TylerGlaiel** [comment]
I would expect the documentation for SDL_Init to specify that it must be called from the main thread (or use the hint if it isn't)?

**Comment by slouken** [comment]
Okay, added, thanks!
