### ISSUE TITLE
SDL_Vulkan_CreateSurface include

### ISSUE THREAD

**Issue by pc-john** [libsdl-org/SDL#9536]
The page https://wiki.libsdl.org/SDL3/SDL_Vulkan_CreateSurface claims that "apps should only #include <SDL3/SDL.h>!" for SDL_Vulkan_CreateSurface(). But I cannot compile the code without #include <SDL3/SDL_vulkan.h>. Is it bug in SDL headers or in the doc?

I use SDL3 preview downloaded few days ago from SDL pages, Windows 10 and MSVC 2022.

**Comment by icculus** [comment]
All the functions get that message automatically, let me think about how to solve that.

**Comment by DJLink** [comment]
> All the functions get that message automatically, let me think about how to solve that.

![image](https://github.com/libsdl-org/SDL/assets/423769/6b890d41-313e-41bf-9711-8d70ab3f9577)

Dumb suggestion maybe, but what if the header files of files that are not in SDL.h had a 

"Not included in SDL.h, needs manual include" on the header info and then some code/script that when detects it ignores that chunk of the message? This way documentation would be correct, and someone looking at the header file directly would also know about it.

**Comment by slouken** [comment]
@icculus, just out of curiosity, why are we recommending that people don't include the individual headers?

**Comment by icculus** [comment]
Isn't that the policy? With the exception of SDL_main and a few others, do they even work as individual includes?

And if they do work, do we want to encourage it?

**Comment by slouken** [comment]
Yes, they do work. It’s simpler to just include SDL.h, and we should use that for examples, but there’s no reason to have a giant warning on every wiki page.

**Comment by icculus** [comment]
Okay, let's just dump that warning, it solves the problem.  :)

**Comment by slouken** [comment]
Can you change it to <SDL3/SDL_vulkan.h>?

**Comment by icculus** [comment]
> Can you change it to <SDL3/SDL_vulkan.h>?

Done.

**Comment by pc-john** [comment]
SDL3 wiki seems ok. Somehow, it does not mention <SDL3/SDL3.h> that might be used for most functions, but I understand that this might not be straightforward to append.

It is also not clear if I should include only <SDL3/SDL_vulkan.h> for SDL_bool SDL_Vulkan_CreateSurface(....) or even <SDL3/SDL_stdinc.h> for using SDL_TRUE for return value checking. Using my bran, something tells me that I do not need it, but it might not be obvious for beginners. But I understand, that this is even more difficult to "automatically" append into doc, so you might prefer to not solve it.

SDL2 wiki seems strange to me after the fix. For SDL_GetError() it tells <code>Defined in SDL_error.h</code>. How shall I include it in portable way? By <SDL2/SDL_error.h>, "SDL2/SDL_error.h", <SDL_error.h>, or "SDL_error.h"? I remember, there was some rule. Maybe, appending <code>"</code> around SDL_error.h would be solution (?).
