### ISSUE TITLE
SDL_GetPrefPath() without creating directories

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9538]
Right now the function `SDL_GetPrefPath(org, app)` always creates the directories org/app, if they don't exist.
It would be useful to have a way to just check, if there are existing files, without creating the directories.
It would minimize the clutter from apps, which run for the first time on a system and don't choose to save files yet, but still want to check, if there are any.

Maybe `SDL_GetPrefPath()` could be replaced with an enum constant in `SDL_Folder` called `SDL_FOLDER_PREF`.
And if an app wants to save something, it can create the directories with the new `SDL_CreateDirectory()` function, if there aren't any.

Example on a UNIX system:
```
SDL_GetUserFolder(SDL_FOLDER_PREF) ==> "/home/a_username/.local/share/"
```

**Comment by Sackzement** [comment]
You are absolutely right. My proposal to replace `SDL_GetPrefPath(org, app)` with an enum constant in `SDL_Folder` wasn't good.
The main point I wanted to make was, that it could be useful to have a way to get the pref-path without directly creating it if non-existent.
Maybe some function like this:
```
char * SDL_GetPrefPathButDontCreate(const char *org, const char *app);
```
This is also just an example.
Some way to just check if there are preferences files.
If nothing ever gets written to the path returned by `SDL_GetPrefPath(org, app)`, there will still be the directories `org/app` and no files inside.

**Comment by icculus** [comment]
I think we're going to pass on this one.
