### ISSUE TITLE
SDL_SetEventEnabled (Segmentation fault)

### ISSUE THREAD

**Issue by sechshelme** [libsdl-org/SDL#9544]
If you enter something other than 0 or 1 as the 2nd parameter for SDL_SetEventEnabled, a “segmentation fault” will be triggered.
Of course, if you use SDL_TRUE and SDL_FALSE nicely, this won't happen. But with an IntBool, all values that an integer can represent are actually possible. Eg. also -1.

I added the following line to "SDL_events.c" and it seems to work with this.

```c
void SDL_SetEventEnabled(Uint32 type, SDL_bool enabled)
{
    SDL_bool current_state;
    Uint8 hi = ((type >> 8) & 0xff);
    Uint8 lo = (type & 0xff);

    if (enabled) { enabled = SDL_TRUE; } // New Line
```

**Comment by icculus** [comment]
```c
#ifdef _MSC_VER /* Visual Studio analyzer can't tell that SDL_disabled_events[hi] isn't NULL if enabled is true */
#pragma warning(push)
#pragma warning(disable : 6011)
#endif
            SDL_disabled_events[hi]->bits[lo / 32] &= ~(1 << (lo & 31));
#ifdef _MSC_VER
#pragma warning(pop)
#endif
```

It always kills me when we're this incorrectly insistent that the static analyzer was wrong, lol.

**Comment by icculus** [comment]
This is fixed in SDL3 now. SDL2 did not have this bug.

**Comment by sechshelme** [comment]
Thanks
