### ISSUE TITLE
Ubuntu build missing semicolon on main branch

### ISSUE THREAD

**Issue by mir-arturs-tamanis** [libsdl-org/SDL#9547]
Simple change like below fixed it:
`
diff --git a/src/video/wayland/SDL_waylandwindow.c b/src/video/wayland/SDL_waylandwindow.c
index 5af5add45..d31cfd340 100644
--- a/src/video/wayland/SDL_waylandwindow.c
+++ b/src/video/wayland/SDL_waylandwindow.c
@@ -2472,7 +2472,7 @@ void Wayland_GetWindowSizeInPixels(SDL_VideoDevice *_this, SDL_Window *window, i
 {
     SDL_WindowData *data;

-    SDL_assert(window->driverdata)
+    SDL_assert(window->driverdata);

     data = window->driverdata;
     *w = data->current.drawable_width;
`

**Comment by slouken** [comment]
Yep, fixed, thanks.
