### ISSUE TITLE
string function names: "L" used instead of default "N"

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9554]
This may be a bit too nit-picky, but I found three SDL string functions, which use the letter "L"(lowercase) for length/maxlength, instead of the default "N" in the C language.
```
     SDL          C
SDL_wcsncmp     wcsncmp   N N
SDL_strnlen     strnlen_s N N
SDL_strncmp     strncmp   N N
SDL_strndup     strndup   N N

SDL_wcsncasecmp           N -
SDL_strnstr               N -
SDL_utf8strnlen           N -
SDL_wcsnstr               N -

SDL_strlcat     strncat   L N
SDL_strlcpy     strncpy   L N

SDL_utf8strlcpy           L -

```

**Comment by slouken** [comment]
These are actually modeled after the functions without the SDL prefix, and have different behavior than the 'n' functions.

**Comment by sezero** [comment]
strlcpy and strlcat are not STDC. Here is their OpenBSD man page: https://man.openbsd.org/strlcpy.3

**Comment by Sackzement** [comment]
Ah, I didn't know that. Thanks for the info. I'm sorry for posting this.

**Comment by icculus** [comment]
> I'm sorry for posting this.

Keep going through the headers like this. This wasn't a mistake, this is double-checking the fine details of an API we're about to lock down. This is important work and you don't have to apologize.

**Comment by slouken** [comment]
^this^
