### ISSUE TITLE
Android build warnings

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9556]
@0x1F9F1:
./src/audio/SDL_audioresample.c:450:7: warning: no previous extern declaration for non-static variable 'ResamplerFilter' [-Wmissing-variable-declarations]
Cubic ResamplerFilter[RESAMPLER_SAMPLES_PER_ZERO_CROSSING][RESAMPLER_SAMPLES_PER_FRAME];
      ^
./src/audio/SDL_audioresample.c:450:1: note: declare 'static' if the variable is not intended to be used outside of this translation unit
Cubic ResamplerFilter[RESAMPLER_SAMPLES_PER_ZERO_CROSSING][RESAMPLER_SAMPLES_PER_FRAME];
^

**Comment by slouken** [comment]
That should be static, right?

**Comment by 0x1F9F1** [comment]
Ah yup, that can be made static

**Comment by slouken** [comment]
Done, thanks!
