### ISSUE TITLE
Wiki not syncing SDL_WindowFlags macros

### ISSUE THREAD

**Issue by e-l-i-j-a-h** [libsdl-org/SDL#9557]
A few days ago, support for auto-generating wiki pages for public-facing typedefs was introduced with libsdl-org/sdlwiki@ed200683589ddd95089a0d4017580e9fa97969d2.

However, this had the side effect of deleting the manually-authored table of `SDL_WindowFlags` macros under the [SDL_WindowFlags](https://wiki.libsdl.org/SDL3/SDL_WindowFlags) page. Currently, there are no pages in the wiki documenting the full list of window flags.

Filed as per Sam's request.

**Comment by icculus** [comment]
Ah, I meant to bring this up, thank you.

In SDL2, this was an enum:

https://github.com/libsdl-org/SDL/blob/effc16954f25a09fd6b1d3753a1bea28ae2349bf/include/SDL_video.h#L102-L131

In SDL3, it's a Uint32 and all the enum values are now `#define`s:

https://github.com/libsdl-org/SDL/blob/bdd47f7770542c1fe6af9edcc4e8109511453c42/include/SDL3/SDL_video.h#L133-L157

Is there a reason for this change? We use enums for other bitflag values elsewhere, and it would let all these values be covered in one header comment and displayed on one wikipage. The actual typedef can still be a Uint32, which we expect to fill in with values from an enum OR'd together.

The alternative, for documentation purposes, is going to be to add documentation to each define, and a pile of `\sa` tags on the Uint32 typedef that will go out of date as we add new flags in later versions.

**Comment by slouken** [comment]
Yes, using a define instead of an enum makes the 31st bit available, which is important for window flags (given that bit is already used and we want as many spare as we can get)

**Comment by slouken** [comment]
We should probably be consistent in how we represent bit flags in the API. There's no real reason to make them an enumeration, in fact that makes it confusing since we don't also have bitwise operators for them and the enum is never actually used as the type for the parameter.

Maybe we can use an enum with a naming convention that's more clear, like SDL_WindowFlagMaskValues? SDL_XxxMaskValues for anywhere else we do that too? Then the mask type is Uint32?

**Comment by slouken** [comment]
Also, some compilers take a dim view of ORing enumerated values, and I'm not sure what the promotion rules are when promoting an enum (as an int) to an unsigned int mask...

**Comment by icculus** [comment]
Okay, leave it alone, I'll figure out a way to make this reasonable to express on the wiki bridge.

**Comment by slouken** [comment]
FYI, I also just switched SDL_KeyCode to defines, to reduce confusion.

**Comment by icculus** [comment]
SDL_messagebox.h also has a few bitflag enums, in case you want to clean those out. I haven't looked through the whole API for these, there may be others.

**Comment by slouken** [comment]
I don't mind making some new construct to indicate that these are a set of related bitflags. An enum is a tempting way of doing it, if it didn't have all the language baggage around that. Maybe we can use comments to indicate a grouping of bitflags?

**Comment by slouken** [comment]
Does this turn into immediate constant values for all compilers? @sezero?
```c
const SDL_WindowFlag /* Uint32 */ SDL_WINDOW_NOT_FOCUSABLE = 0x80000000U;
```
static const? extern const?

**Comment by sezero** [comment]
> Does this turn into immediate constant values for all compilers? @sezero?
> 
> ```c
> const SDL_WindowFlag /* Uint32 */ SDL_WINDOW_NOT_FOCUSABLE = 0x80000000U;
> ```

As it is above, I don't think so, hat's asking for trouble.

As it is above, you'll be relying on `-fcommon` which recent gcc _not_ default to

> static const?

you'll be getting lots of unused warnings

> extern const?

Worst:
```
$ gcc -Wall -c 1.c
In file included from 1.c:1:
1.h:1: warning: ‘SDL_WINDOW_NOT_FOCUSABLE’ initialized and declared ‘extern’
```

**Comment by icculus** [comment]
Yeah, the solution here is to add some magic to the wiki bridge that lets us add a comment that groups things.

(Also, if we're using all 32 bits in the window flags and we haven't even released 3.2 yet, we need to make that thing 64-bit. Surely something new is going to come up in the next 10 years!)

**Comment by slouken** [comment]
We're not using all 32-bits yet, we have 9 bits left, but we are using the highest bit.

**Comment by icculus** [comment]
Okay, wikiheaders now will treat defines directly below a _typedef_ that _isn't_ a struct/union/enum as part of the definition.

Like this:

https://wiki.libsdl.org/SDL3/SDL_WindowFlags

This seemed like the easiest way to handle this.

So if you see any of these in the headers that need to be paired, just make sure all the `#define` lines are right below the typedef (not even a comment or a blank line between them!), and it'll include all lines that start with `#define` after typedef until it hits a line that doesn't.

**Comment by slouken** [comment]
Can you allow blank lines (but not comments)?

**Comment by slouken** [comment]
Yes, actually that’s super helpful, thanks!

I’ll work on making these consistent today.

**Comment by icculus** [comment]
> Can you allow blank lines (but not comments)?

Done!

This has spaces to separate the defines and each datatype, as an example:

https://wiki.libsdl.org/SDL3/SDL_AudioFormat

(but those can be packed back together, this was just for demonstration purposes.)

**Comment by Susko3** [comment]
Endian-specific audio format are missing from that documentation. Not sure if you want the code to handle this, or if this is something to manually add.

https://github.com/libsdl-org/SDL/blob/e0b45fed06cb7b4b22df91ceb137c3587c0a8403/include/SDL3/SDL_audio.h#L221-L229

**Comment by icculus** [comment]
Yeah, that's a known issue over here still.

**Comment by icculus** [comment]
Actually, the fix there is easy; I thought this would suck in more incorrect bits of the headers, but it only needed one tweak.

https://wiki.libsdl.org/SDL3/SDL_AudioFormat covers that piece now.
