### ISSUE TITLE
[SDL3.1.1] Single-threaded Emscripten build fails to find default audio device.

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#9558]
Building SDL3 for Emscripten without `-DSDL_PTHREADS=ON` results in audio tests failing with `"No default audio device available"`.

Debugging this a bit it seems to be caused by `CreatePhysicalAudioDevice()` failing because `SDL_CreateCondition()` fails due to `SDL_Semaphore` being unimplemented.

As a temp fix I tried replacing `SDL_Condition` with a `#ifndef SDL_THREADS_DISABLED` dummy implementation and it made the audio tests work fine again.

**Comment by icculus** [comment]
Unlike SDL_CreateMutex(), we don't have SDL_CreateCondition() report success when built with SDL_THREADS_DISABLED. SDL_RWlock also reports success, but SDL_Semaphore doesn't, fwiw.

I'm going to change SDL_CreateCondition so everything succeeds in single-threaded builds.
