### ISSUE TITLE
[SDL3, X11] Window size 0x0 with xvfb-run

### ISSUE THREAD

**Issue by texus** [libsdl-org/SDL#9573]
Since ad813a65e791d295351e70b2d1c36b06f3853999 (https://github.com/libsdl-org/SDL/pull/9535), I'm having issues with running a program on a virtual X server with the following command:
`xvfb-run --server-args="-screen 0, 1280x720x24" -a ./executable`

The width and height returned by `SDL_GetWindowSize` are both 0 (and the function returns 0 as well).

This is reproducible on both a Github Action runner with Ubuntu 20.04 and on a desktop with Manjaro Linux (Cinnamon DE).

**Comment by Kontrabant** [comment]
Ah, the headless display doesn't provide an initial configure event, so it can't be presumed that one will always be sent when mapping the window. Should be a simple fix.
