### ISSUE TITLE
Pipewire version check should use the core version

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9582]
Good point. Yes, we've been checking the client library version, but we should use the core version for this check instead, as that's what we really care about here.

_Originally posted by @Kontrabant in https://github.com/libsdl-org/SDL/issues/9543#issuecomment-2062849998_

**Comment by slouken** [comment]
@Kontrabant, is that something we can change soon? I'd like to get this in before merging recent changes to Source 2.

**Comment by Kontrabant** [comment]
Already done in https://github.com/libsdl-org/SDL/commit/a923db9d0a65e79ed79078f6fccd984d13528045

**Comment by slouken** [comment]
Ah, thanks!
