### ISSUE TITLE
Mouse events trigger "X server refused mouse capture" in X11

### ISSUE THREAD

**Issue by 64ArthurAraujo** [libsdl-org/SDL#9593]
I am developing a project using [osu!framework](https://github.com/ppy/osu-framework), and recently they started moving towards SDL3. While updating my project to the version that uses SDL3 i found that any mouse events such as left and right clicking and the middle button click were showing "SDL error log [debug]: X server refused mouse capture" in the logs. After discussing this with a developer of the framework @Susko3 he pointed out that the issue could be at `SDL_PumpEvents`; setting the env variable `SDL_MOUSE_AUTO_CAPTURE=0` seems to mute those errors. 
(sorry if i am too vague but i don't work with SDL directly)

### System Information
OS: Fedora Linux 39 (using NVIDIA proprietary drivers)
`X -version` output:
```
X.Org X Server 1.20.14
X Protocol Version 11, Revision 0
Build Operating System:  6.8.0-0.rc7.55.fc40.1.x86_64 
Current Operating System: Linux fedora 6.8.5-201.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 11 18:25:26 UTC 2024 x86_64
Kernel command line: BOOT_IMAGE=(hd0,gpt2)/vmlinuz-6.8.5-201.fc39.x86_64 root=UUID=d2f75f24-a558-4ae7-99ff-bcd9522b7257 ro rootflags=subvol=root rd.driver.blacklist=nouveau modprobe.blacklist=nouveau rhgb quiet rd.driver.blacklist=nouveau modprobe.blacklist=nouveau
Build Date: 10 April 2024  12:00:00AM
Build ID: xorg-x11-server 1.20.14-35.fc39 
Current version of pixman: 0.42.2
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

https://github.com/libsdl-org/SDL/assets/90941580/9f6cc227-042e-42ac-ad2f-1dd29e3a91e4

**Comment by Susko3** [comment]
Note that the log entries mean that something is calling `SDL_SetError("X server refused mouse capture")` i.e. [this error is getting hit repeatedly](https://github.com/libsdl-org/SDL/blob/c623bd2fdcca29c513f5b68e7bd89368929ee564/src/video/x11/SDL_x11mouse.c#L400).

**Comment by Kontrabant** [comment]
The error being returned is `AlreadyGrabbed`, which is due to XInput2 capturing the pointer when it's being used for mouse input handling.
