### ISSUE TITLE
SDL 3.1.1 : SDL_FlipSurface() and SDL_ConvertSurfaceFormat() don't works...

### ISSUE THREAD

**Issue by ArnaudNRoses** [libsdl-org/SDL#9602]
SDL_FlipSurface() do nothing.
SDL_ConvertSurfaceFormat() don't works well :
it's convert a format without alpha to a format that take alpha or inverse but not replace RGB colors in any ways....

RGBA masks and shifts of the color format not take the effect if we use SDL_ConvertSurfaceFormat(), just the alpha is set or not, pixels are always in same place like the first initialisation of the surface by SDL_LoadBMP().

SDL 3.1.1 compiled by myself with VS 2022 latest version under win 10 Latest version.

**Comment by slouken** [comment]
Can you provide a minimal test program that shows the problem?

Thanks!
