### ISSUE TITLE
Convert SDL_CaseFoldUnicode() results to UTF-8

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9607]
I saw this warning: `SDL_filesystem.c(157,39): warning C4244: '=': conversion from 'Uint32' to 'char', possible loss of data` and it looks like we should be converting from UTF-32 to UTF-8 in CaseFoldUtf8String(). Is that right?

**Comment by icculus** [comment]
Whoops, yes, that was dumb. I'll fix it.

**Comment by icculus** [comment]
Fixed (and actually tested) now.
