### ISSUE TITLE
SDL3 Windows rwops files getting locked?

### ISSUE THREAD

**Issue by superfury** [libsdl-org/SDL#9609]
I've ported over my own app to SDL3, based on the older SDL2 code.
It seems to run fine as long as nothing gets written using rb+ file i/o mode.
This is using SDL_IOFromFile to open a file and SDL_CloseIO to close the file that was opened.

But when I use SDL3, somehow, when opening files with rb, closing it and then opening the file with rb+ causes SDL to fail (stepping through the code it seems to get an error indicating that the file is locked (confirmed by trying to open the file in other software) from what I can tell?). My app has already closed the file at an earlier point in time (by calling SDL_CloseIO on the file's SDL_IOStream pointer).

Is anything known what might cause this to happen?

**Comment by slouken** [comment]
It sounds like SDL_CloseIO isn't actually closing the file. Can you step in and see what it's doing wrong?

**Comment by superfury** [comment]
> It sounds like SDL_CloseIO isn't actually closing the file. Can you step in and see what it's doing wrong?

So far looked at opening an existing existing file with "rb" mode. That one seems to close correctly.
Now to wait for the "rb+" call (read and overwrite for data editing and appending in this case, to add and overwrite data in the file)...

**Comment by slouken** [comment]
I'm glad you figured it out!

**Comment by slouken** [comment]
FYI, in general memory allocations need to be super fast and semaphores aren't the right tool for locking them. Unless you're doing some custom pooled allocations it's better to use existing allocator implementations that have been well tested. I'm not familiar with what you're trying to do, so it might be fine, but just a heads up.
