### ISSUE TITLE
SDL_GetCameraDevices not listing internal Macbook camera

### ISSUE THREAD

**Issue by olekolek1000** [libsdl-org/SDL#9610]
From what I have noticed, only "OBS Virtual camera" is reported by `SDL_GetCameraDevices`, internal "FaceTime HD Camera" is missing from the list, needs investigation.

MacOS 14.4.1, aarch64, main branch

**Comment by hkva** [comment]
This should be fixed as of 4d392bfc67eb1f682797102aaae0fffddf6b3f0b
