### ISSUE TITLE
Clipboard history Win+V mechanism on Windows doesn't work (w/ fix)

### ISSUE THREAD

**Issue by ocornut** [libsdl-org/SDL#9613]
When pressing Win+V, Windows shows a popup allowing users to select an item among clipboard history, and submitting this item to paste into the application.
A brief research on a win32-api based test-bed suggest that this works by temporarily swapping the clipboard contents, and emitting the equivalent of a Ctrl+V keypress as a series of WM_KEYDOWN/WM_KEYUP events.

**For some reason, this Windows feature doesn't seem to work in SDL apps.**
I haven't gotten this to work with neither SDL2 or recent SDL3 builds.
If I compile and run checkkeys from SDL 2.30.2, I can get e.g. a regular Ctrl+V to be printed in the log, but using Win+V doesn't emit the Ctrl+V.

I added debug printing in the WM_KEYDOWN and WM_KEYUP handlers:
```cpp
    case WM_KEYDOWN:
    case WM_SYSKEYDOWN:
    {
        SDL_Scancode code = WindowsScanCodeToSDLScanCode(lParam, wParam);
        const Uint8 *keyboardState = SDL_GetKeyboardState(NULL);

        SDL_Log("WM_*KEYDOWN %08X %08X -> code %08X\n", lParam, wParam, code);
[..]
```

When I press Ctrl+V (works)
```cpp

INFO: WM_*KEYDOWN 001D0001 00000011 -> code 000000E0
INFO: Key pressed :  scancode 224 = Left Ctrl, keycode 0x400000E0 = Left Ctrl  modifiers: LCTRL NUM
INFO: WM_*KEYDOWN 002F0001 00000056 -> code 00000019
INFO: Key pressed :  scancode 25 = V, keycode 0x00000076 = V  modifiers: LCTRL NUM
INFO: WM_*KEYUP C02F0001 00000056 -> code 00000019
INFO: Key released:  scancode 25 = V, keycode 0x00000076 = V  modifiers: LCTRL NUM
INFO: WM_*KEYUP C01D0001 00000011 -> code 000000E0
INFO: Key released:  scancode 224 = Left Ctrl, keycode 0x400000E0 = Left Ctrl  modifiers: NUM
```

When I press Win+V (doesn't work):
```cpp
INFO: WM_*KEYDOWN 015B0001 0000005B -> code 000000E3
INFO: Key pressed :  scancode 227 = Left Windows, keycode 0x400000E3 = Left Windows  modifiers: LGUI NUM
INFO: Key released:  scancode 227 = Left Windows, keycode 0x400000E3 = Left Windows  modifiers: NUM
INFO: WM_*KEYUP C15B0001 0000005B -> code 000000E3
^^^ those are the real Win+V presses

(here I interact with the Windows popup to select a clipboard entry)
INFO: WM_*KEYDOWN 00000001 00000011 -> code 00000000
INFO: WM_*KEYDOWN 00000001 00000056 -> code 00000000
INFO: WM_*KEYUP C0000001 00000056 -> code 00000000
INFO: WM_*KEYUP C0000001 00000011 -> code 00000000
^^^ those are the "virtual" Ctrl+V emitted by Windows
```

So in the first instance of the direct CTRL+V press
```cpp
INFO: WM_*KEYDOWN lParam=001D0001 wParam=00000011 -> code 000000E0
INFO: WM_*KEYDOWN lParam=002F0001 wParam=00000056 -> code 00000019
```
Gets interpreted correctly.
Whereas in the second instance, the indirect CTRL+V pressed emitted by Win+V:
```cpp
INFO: WM_*KEYDOWN lParam=00000001 wParam=00000011 -> code 00000000
INFO: WM_*KEYDOWN lParam=00000001 wParam=00000056 -> code 00000000
```
Doesn't get interpreted correctly.

The only difference between in lParam.
The affected bits 16-23 are the scancode as stored in lParam:
https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-keydown

And basically SDL doesn't accept any keys unless the scancode is set.
The bottom of `WindowsScanCodeToSDLScanCode()` has this:

```cpp
    /* The on-screen keyboard can generate VK_LEFT and VK_RIGHT events without a scancode
     * value set, however we cannot simply map these in VKeytoScancode() or we will be
     * incorrectly handling the arrow keys on the number pad when NumLock is disabled
     * (which also generate VK_LEFT, VK_RIGHT, etc in that scenario). Instead, we'll only
     * map them if none of the above special number pad mappings applied. */
    if (code == SDL_SCANCODE_UNKNOWN) {
        code = VKeytoScancodeFallback(wParam);
    }
```
Which I believe could be extended to fix this thing.
If I complement `VKeytoScancodeFallback()` with 
```cpp
    case VK_CONTROL:
        return SDL_SCANCODE_LCTRL;
    case VK_V:
        return SDL_SCANCODE_V;
```

Then Win+V starts working.

(For reference, original issue posted on dear imgui repository: https://github.com/ocornut/imgui/issues/7522)

**Comment by ocornut** [comment]
Thanks for merging.
It may be good to amend the "The on-screen keyboard can generate ..." comment to explicitly refer to this Win+V feature.

(I didn't make a PR as I was expecting you may want to dig further into what other odd/custom events Windows may emit. I suppose we'll probably find some over time!)

**Comment by slouken** [comment]
SDL3 should generally handle this case now, and we can update SDL2 as we find other cases like this.
