### ISSUE TITLE
[SDL 3.1.1] remove SDL_RENDERER_ACCELERATED ?

### ISSUE THREAD

**Issue by sechshelme** [libsdl-org/SDL#9614]
Why was the SDL_RENDERER_ACCELERATED flag removed from SDL_RendererFlags?
But if I still use it, the rendering runs about 30x faster.
You can check this with the following demo.

Tested with Linux 64bit

```c
#include <SDL3/SDL.h>

#define  SDL_RENDERER_ACCELERATED 0x00000002 // for test

int main(int argc, char *argv[])
{
  SDL_bool quit = SDL_FALSE;
  SDL_Window *window = SDL_CreateWindow("Triangle Example", 800, 600, 0);

//  SDL_Renderer *renderer = SDL_CreateRenderer(window, NULL, SDL_RENDERER_PRESENTVSYNC);
  SDL_Renderer *renderer = SDL_CreateRenderer(window, NULL, SDL_RENDERER_ACCELERATED);

  SDL_Vertex vert[3]= {{400, 150, 1.0, 0.0, 0.0, 1.0}, {200, 450, 0.0, 0.0, 1.0, 1.0}, {600 ,450, 0.0, 1.0, 0.0, 1.0}};

  while (!quit) {
    SDL_Event ev;
    int64_t startTick = SDL_GetTicksNS();
    while (SDL_PollEvent(&ev) != 0) {
      switch(ev.type) {
        case SDL_EVENT_QUIT:
        quit = SDL_TRUE;
        break;
      }
    }
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    SDL_RenderClear(renderer);

    SDL_RenderGeometry(renderer, NULL, vert, 3, NULL, 0);

    SDL_RenderPresent(renderer);
    //int tickEnd = SDL_GetTicks();
    SDL_Log("Tick: %i", (SDL_GetTicksNS() - startTick) / 10000);

  }

  SDL_DestroyRenderer(renderer);
  SDL_DestroyWindow(window);
  SDL_Quit();
  return 0;
}

```

**Comment by slouken** [comment]
It's not accelerated that's causing the speedup, it's removing SDL_RENDERER_PRESENTVSYNC, which allows the renderer to run as fast as it can, instead of synchronized to your monitor's refresh rate.

**Comment by sechshelme** [comment]
Thanks, that's an explanation.
What I don't understand is why SDL_RendererFlags() only has one parameter, even though other values are also permitted. There was even software rendering in a pre-release version of SDL3.
Why was all of this removed?

**Comment by slouken** [comment]
Because it was confusing and unnecessary. Software rendering is still available, you just specify "software" as the name of the renderer.

**Comment by lumPalette** [comment]
since `SDL_RendererFlags` only consist in one flag now (`SDL_RENDERER_PRESENT_VSYNC`), maybe it would be better to just remove the `flags` parameter in `SDL_CreateRenderer()` (or removing `SDL_RendererFlags` completely), so if you need vsync, you would have to use `SDL_CreateRendererWithProperties()` instead?

**Comment by slouken** [comment]
> since `SDL_RendererFlags` only consist in one flag now (`SDL_RENDERER_PRESENT_VSYNC`), maybe it would be better to just remove the `flags` parameter in `SDL_CreateRenderer()` (or removing `SDL_RendererFlags` completely), so if you need vsync, you would have to use `SDL_CreateRendererWithProperties()` instead?

Yep, I agree. This is done in https://github.com/libsdl-org/SDL/commit/17520c2e6eeac14839ecc510472353bf84a9c985.
