### ISSUE TITLE
Linux, -std=c17, test/testlock.c, error: call to undeclared function 'kill'

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9617]
When compiling SDL with tests on Linux and the `-std=c17` flag (actually any STDC flag instead of GNUC) I get following error/warning:
```
Clang:
path/to/SDL-repo/test/testlock.c:105:5: error: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  105 |     kill(0, SIGINT);
      |     ^
```
```
GCC:
path/to/SDL-repo/test/testlock.c: In function ‘hit_timeout’:
path/to/SDL-repo/test/testlock.c:105:5: warning: implicit declaration of function ‘kill’ [-Wimplicit-function-declaration]
  105 |     kill(0, SIGINT);
      |     ^~~~
```

My first idea was just to replace the call to `kill(0, SIGINT);` with `raise(SIGINT);`, but the two functions aren't exactly equivalent.
The `kill` function with the parameter 0 sends a signal to the whole process group, but the `raise` function just sends the signal to the calling process.

My second idea was to define following macro before `signal.h` is included:
```
#define _POSIX_C_SOURCE 1
```
This would let `signal.h` declare the function itself.

**Comment by icculus** [comment]
`raise` is probably okay here, we're only trying to signal the current process, not a group.
