### ISSUE TITLE
Replace SDL_GetNumXDrivers/SDL_GetXDriver interfaces?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9618]
This one is questionable, since it's just returning const static data, but: everything else now returns an array of items instead of making you call SDL_GetWhatever() for SDL_GetNumWhatevers() iterations; should we also do this for things like SDL_GetAudioDriver(), SDL_GetVideoDriver(), etc?

**Comment by slouken** [comment]
The reason we moved to a SDL_GetWhatevers() model was to handle lists that dynamically update. I think we can if you want consistency here, but it's not necessary.

**Comment by icculus** [comment]
Yeah, let's pass on this, then.
