### ISSUE TITLE
Microsoft Xbox One Elite not working anymore?

### ISSUE THREAD

**Issue by eliasHeyndrickx** [libsdl-org/SDL#9622]
Hello

I am working on a game using FNA (an alternative implementation of XNA). For various reasons FNA uses SDL2. Controller support was working on my game a while ago but seems to have stopped suddenly. FNA has not updated anything regarding controller logic on their end, neither have I.  When I inquired the creator of the library he advised me to update SDL2 to a newer version and that it worked for him after that.

I attempted that but it did not fix the issue. I have tried to update the "gamecontrollerdb.txt" with the GUID of my controller as follows: 030000005e040000ff02000000007801,Microsoft Xbox One Elite,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,

I could not find that GUID, what is more strange is that only "Microsoft Xbox One Elite 2" seem to be present in this file. Am I missing something here? I don't really use SDL(2) all that much so it's hard for me to pinpoint what is causing the issue here.

Finally in the code it picks up nothing, no button presses at all. A button is never pressed, it worked in older versions of SDL2 so I have no idea what's going on here.

**Comment by flibitijibibo** [comment]
To isolate the problem we can run SDL's tests for controller support: Grab this zip file...

https://github.com/libsdl-org/SDL/archive/refs/heads/SDL2.zip

... and open `SDL2/VisualC/SDL.sln`. There will be a bunch of projects in the solution but the only ones we care about are testjoystick, testgamecontroller, and controllermap in that order:

- testjoystick will ensure we're getting something from the raw input device
- testgamecontroller will ensure that SDL recognizes the device and knows how to map it to the Xbox-like layout
- If the first test passes and the second test fails, controllermap will generate a binding for us to add to the mapping database

Give these tests a try and let us know what the results are!

**Comment by eliasHeyndrickx** [comment]
I suspect the issue was on my part since the problem has been resolved. Thanks to @flibitijibibo for helping me figuring out the problem.
