### ISSUE TITLE
Text input doesn't work in iOS simulator

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#9624]
- Originally reported in https://github.com/ppy/osu/issues/27984
- Related: https://github.com/libsdl-org/SDL/issues/6465

`SDL_EVENT_KEY_DOWN` and `SDL_EVENT_KEY_UP` events are sent just fine, but no `SDL_EVENT_TEXT_INPUT` events are sent.
Attached are application logs with `SDL_HINT_EVENT_LOGGING` enabled. Typing starts at the first `SDL_EVENT_KEY_DOWN`.

[log3.txt](https://github.com/libsdl-org/SDL/files/15120224/log3.txt)

I don't have iOS simulator setup, so please ping the OP if you need additional info.

**Comment by slouken** [comment]
Is SDL_StartTextInput() being called?

**Comment by Susko3** [comment]
> Is SDL_StartTextInput() being called?

It must be. It's working fine for all other platforms. I've not personally tested iOS on a real device, but others have and there are no reports of text input not working.

Please check if you're able to reproduce the issue.

**Comment by slouken** [comment]
What are the repro steps, assuming I've never used osu? :)

**Comment by Susko3** [comment]
I was hoping you (or someone on the team) might be able to confirm whether or not text input works in the SDL tests on iOS simulator.

The latest release of osu! for iOS can be downloaded from https://github.com/ppy/osu/releases/download/2024.412.1/osu.iOS.ipa. It still uses SDL2, so it might not be of much use. (The original issue is about SDL3.)

Once opened, you can dismiss the first run setup overlay, you can then tap on the osu! cookie and go to settings, where you can find a search text box, tapping on it activates it and calls `SDL_StartTextInput()`.

You can verify that keyboard events work by pressing `Ctrl-O`, which should toggle settings.

**Comment by drkoll** [comment]
Following up on this issue as I am experiencing the same behavior described in the original post by @Susko3 on an iPad Pro 4th Gen with the latest version (2024.625.2) of Osu and a Logitech Combo Touch keyboard.

#### Symptoms
- **Keyboard Commands:** `Ctrl-O` and other related keyboard commands work fine.
- **Text Input:** Text input does not work in text fields (e.g., username/password boxes, settings search bar, chat, etc).

#### Temporary Workaround
1. **Disconnect Keyboard:**
   - Disconnect the physical keyboard from the Smart Connector port of the iPad.
   - The onscreen keyboard will appear.
2. **Use Onscreen Keyboard:**
   - Use the onscreen keyboard to input any text into any text field (tested with username/password boxes and settings search bar).
3. **Reconnect Keyboard:**
   - Reconnect the physical keyboard to the Smart Connector port.
   - The hardware keyboard will then function properly for text input.

#### Additional Information
- **Duration of Workaround:** The workaround works for as long as the application remains running, including in the background.
- **Reversion:** Quitting the application completely reverts the behavior back to the original issue.
- I have ensured that the settings mentioned in https://github.com/libsdl-org/SDL/issues/6465#issuecomment-1306318213 are not enabled

#### Steps to Reproduce
1. Connect a Logitech Combo Touch keyboard to an iPad Pro.
2. Open Osu.ipa
3. Attempt to type in any text field.
4. Follow the temporary workaround steps if needed.

I do not have any log files but I can attempt to get some if they would be helpful. All I know so far is the stuff I mention above. I can also attempt to side-load different versions of Osu to see if the behavior is present in those. I am new to this particular game (which I believe the SDL project is not directly connected to,) and all of this is quite new to me. Thanks in advance for any light you can shine on this issue!

**Comment by drkoll** [comment]
I have recorded a video demonstrating the behavior in case it is helpful to you @slouken 
https://github.com/libsdl-org/SDL/assets/128939759/f677f364-5b81-4fad-b1c7-6e1aaad2a103
