### ISSUE TITLE
CreateWindowAndRenderer() take title as a parameter?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9626]
Should SDL_CreateWindowAndRenderer() take a title as a parameter? I think that's something that everyone sets on their window and makes sense to add here.

@libsdl-org/a-team, thoughts?

**Comment by icculus** [comment]
Yes.

**Comment by sechshelme** [comment]
I just came across this issues https://github.com/libsdl-org/SDL/issues/9626
I think this is related to this?

But it is still a stumbling block if the wiki does not correspond to the current version of SDL3.

**Comment by madebr** [comment]
> But it is still a stumbling block if the wiki does not correspond to the current version of SDL3.

https://wiki.libsdl.org/SDL3/SDL_CreateWindowAndRenderer looks correct to me  (Great job @icculus!)

The example is bad, but ci is failing so can/should be fixed soon:
https://github.com/libsdl-org/sdlwiki/actions/runs/8850025086/job/24303310350#step:18:127

**Comment by icculus** [comment]
> The example is bad, but ci is failing so can/should be fixed soon:

Fixed in https://github.com/libsdl-org/sdlwiki/commit/343e8a8f5cd2f352dd491819ce620edbc6234231

**Comment by icculus** [comment]
and also https://github.com/libsdl-org/sdlwiki/commit/7509189f58c44a189f6fe775a1509157cbee4995 ...the CI building all the example code is kinda freakin' awesome, @madebr.  :)

**Comment by slouken** [comment]
> the CI building all the example code is kinda freakin' awesome, @madebr. :)

Yes, definitely!
