### ISSUE TITLE
Tried SDL2 (stable release) on Mac crashes right away?

### ISSUE THREAD

**Issue by John-Lluch** [libsdl-org/SDL#9633]
Tried SDL2 (stable release?) on Mac.

After compiling, my code crashes right away even before reaching the main function 

This is the code:

```
#include <SDL.h>
#include <stdio.h>

//Screen dimension constants
const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 480;

int main( int argc, char* args[] )
{
	//The window we'll be rendering to
	SDL_Window* window = NULL;
	
	//The surface contained by the window
	SDL_Surface* screenSurface = NULL;

	//Initialize SDL
	if( SDL_Init( SDL_INIT_VIDEO ) < 0 )
	{
		printf( "SDL could not initialize! SDL_Error: %s\n", SDL_GetError() );
	}
	else
	{
		//Create window
		window = SDL_CreateWindow( "SDL Tutorial", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, SCREEN_WIDTH, SCREEN_HEIGHT, SDL_WINDOW_SHOWN );
		if( window == NULL )
		{
			printf( "Window could not be created! SDL_Error: %s\n", SDL_GetError() );
		}
		else
		{
			//Get window surface
			screenSurface = SDL_GetWindowSurface( window );

			//Fill the surface white
			SDL_FillRect( screenSurface, NULL, SDL_MapRGB( screenSurface->format, 0xFF, 0xFF, 0xFF ) );
			
			//Update the surface
			SDL_UpdateWindowSurface( window );
            
            //Hack to get window to stay up
            SDL_Event e; bool quit = false; while( quit == false ){ while( SDL_PollEvent( &e ) ){ if( e.type == SDL_QUIT ) quit = true; } }
		}
	}

	//Destroy window
	SDL_DestroyWindow( window );

	//Quit SDL subsystems
	SDL_Quit();

	return 0;
}

```

I installed SDL by copying the SDL2.framework to the /Library/Frameworks directory and by specifying the header and framework paths on Xcode build settings.

Any idea about what can be wrong?

**Comment by madebr** [comment]
If it's crashing before main, maybe that points to a search path issue?

**Comment by John-Lluch** [comment]
> Do you have a stack trace where it's crashing?

Yes, see screenshots.

<img width="1368" alt="Screenshot 2024-04-26 at 18 50 11" src="https://github.com/libsdl-org/SDL/assets/1282248/27e57ebf-aa4a-45dd-8853-dacadc2dcced">
<img width="1368" alt="Screenshot 2024-04-26 at 18 51 12" src="https://github.com/libsdl-org/SDL/assets/1282248/2004b2cf-fd99-47e2-8614-82b6e13adae6">

It appears to crash inside a function with the following signature:

` dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)`

**Comment by madebr** [comment]
Google search gave me these related threads:
- https://forums.developer.apple.com/forums/thread/102571
- https://stackoverflow.com/questions/42027601/dyld-abort-with-payload-without-an-error-message

Perhaps you can try some suggestions, and report back what worked (and what not)?

**Comment by John-Lluch** [comment]
> Google search gave me these related threads:
> 
> * https://forums.developer.apple.com/forums/thread/102571
> * https://stackoverflow.com/questions/42027601/dyld-abort-with-payload-without-an-error-message
> 
> Perhaps you can try some suggestions, and report back what worked (and what didn't?

Thank you very much. Adding the SDL2 framework  inside the "Embedded Binaries" section appears to have solved the issue !!

**Comment by John-Lluch** [comment]
On iOS apps it's very common to have static libraries embedded in the app, but I understand that this should be optional for a desktop app.  

Indeed, the SDL2 framework gets embedded in the app bundle, which makes the app much bigger, so I understand what you say.

But I do not know what else should I try. The app compiles and links fine without the embedded framework, so this means the compiler and linker actually finds it in the specified path.  It just crashes upon execution, but why?

**Comment by slime73** [comment]
Mac .apps are generally expected to be self-contained aside from OS libraries (which SDL is not), so if adding SDL to the Embedded Binaries section is copying the .framework into yourapp.app/Contents/Frameworks/ then that's probably what you want.

**Comment by John-Lluch** [comment]
> Mac .apps are generally expected to be self-contained aside from OS libraries (which SDL is not), so if adding SDL to the Embedded Binaries section is copying the .framework into yourapp.app/Contents/Frameworks/ then that's probably what you want.

Yes, that's exactly what happens. The framework is found inside the app bundle in the location you pointed out
