### ISSUE TITLE
SDL_hints.h: Two macro-name and string-literal inconsistencies

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9643]
Found two macro-name and string-literal inconsistencies and wanted to point them out.
https://github.com/libsdl-org/SDL/blob/8d0ad44edd81b39cc6d27e9a2a66afcce25eebe7/include/SDL3/SDL_hints.h#L2337
https://github.com/libsdl-org/SDL/blob/8d0ad44edd81b39cc6d27e9a2a66afcce25eebe7/include/SDL3/SDL_hints.h#L2901

**Comment by slouken** [comment]
Fixed, thanks!
