### ISSUE TITLE
Removing macro SDL_DROPEVENT_DATA_SIZE

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9645]
This is similar to issue #9644.

In 70c149c88f05e469f07b7e5fff58b7e16e4d1bea the member `char short_data[SDL_DROPEVENT_DATA_SIZE]` was removed from `SDL_DropEvent`.

Can the macro `SDL_DROPEVENT_DATA_SIZE` be removed?
https://github.com/libsdl-org/SDL/blob/8d0ad44edd81b39cc6d27e9a2a66afcce25eebe7/include/SDL3/SDL_events.h#L667
I can't find any other entry of `SDL_DROPEVENT_DATA_SIZE` anywhere in the source code.

**Comment by Sackzement** [comment]
resolved in #9681

**Comment by icculus** [comment]
oops, overlap from me, sorry!

**Comment by Sackzement** [comment]
All good :) <3
