### ISSUE TITLE
Window width/height is off by one when odd?

### ISSUE THREAD

**Issue by jeannekamikaze** [libsdl-org/SDL#9653]
SDL: 2.30.2
Ubuntu 23.10, Gnome desktop, 3840x2160, 200% scale

The code below creates a resizable window and clears it to black in a loop. When either the window's width or height are odd, a 1-pixel white horizontal/vertical line appears as shown in the screenshot (pink arrows are hand-drawn) as if the width/height reported by SDL were off by one when they are odd. The initial window width and height in the example below are odd so that you can reproduce this issue. If you resize the window to make either of them even, the 1-pixel line disappears. Make it odd again, and it re-appears.

Is this an issue with the library or the sample?

Thanks for the help.

![sdl](https://github.com/libsdl-org/SDL/assets/1595451/33f000ff-7926-43ea-bba7-e083a80113f0)

**Video**

The sample program below on top of a black background. Notice the 1-pixel vertical/horizontal lines that flicker at the edges as the window is resized.

![Peek 2024-04-30 17-00](https://github.com/libsdl-org/SDL/assets/1595451/ff6b3c7d-2fd9-410a-b0b3-ecd400a09a9f)

**Display settings:**

![ubuntu-display](https://github.com/libsdl-org/SDL/assets/1595451/22497846-86fc-4880-87d2-af7108fbb2ca)

**Sample:**

```c++
#include <SDL.h>

#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>

static bool Render(SDL_Window* window) {
  assert(window);

  SDL_Surface* window_surface = SDL_GetWindowSurface(window);
  if (!window_surface) {
    return false;
  }

  // Render.
  memset(window_surface->pixels, 0, window_surface->pitch * window_surface->h);

  if (SDL_UpdateWindowSurface(window) != 0) {
    return false;
  }

  return true;
}

static bool Resize(SDL_Window* window) {
  assert(window);

  // This returns the same values as the implementation below.
  // int width, height;
  // SDL_GetWindowSize(state->window, &width, &height);

  const SDL_Surface* window_surface = SDL_GetWindowSurface(window);
  if (!window_surface) {
    return false;
  }
  const int width  = window_surface->w;
  const int height = window_surface->h;

  printf("Resize: %dx%d\n", width, height);

  return true;
}

int main(
    __attribute__((unused)) int          argc,
    __attribute__((unused)) const char** argv) {
  bool success = true;

  SDL_Window* window = 0;

  if (SDL_Init(SDL_INIT_VIDEO) != 0) {
    success = false;
    goto cleanup;
  }

  if ((window = SDL_CreateWindow(
           "Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 901, 601,
           SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE)) == NULL) {
    success = false;
    goto cleanup;
  }

  for (;;) {
    // Draw if needed.
    if (!Render(window)) {
      success = false;
      break;
    }

    // Handle events.
    SDL_Event event = {0};
    if (SDL_WaitEvent(&event) == 0) {
      success = false;
      break;
    } else if (event.type == SDL_QUIT) {
      break;
    } else {
      if (event.type == SDL_WINDOWEVENT) {
        if ((event.window.event == SDL_WINDOWEVENT_SIZE_CHANGED) ||
            (event.window.event == SDL_WINDOWEVENT_RESIZED) ||
            (event.window.event == SDL_WINDOWEVENT_MOVED)) {
          if (!Resize(window)) {
            success = false;
            break;
          }
        }
      }
    }
  }

cleanup:
  if (!success) {
    fprintf(stderr, "%s\n", SDL_GetError());
  }

  if (window) {
    SDL_DestroyWindow(window);
    window = 0;
  }

  SDL_Quit();

  return success ? 0 : 1;
}
```

**Comment by Kontrabant** [comment]
I installed Ubuntu 23.04 on a VM and this issue replicates when running via the X11 driver at 200% scaling either in an X or Wayland session with fractional scaling off. The X11 window is also half the size of the Wayland window, so I'm guessing that either GNOME or XWayland is doing some of its own scaling to make X apps appear sharper, which is causing the problem.  With fractional scaling enabled, there is no issue.

I'm tentatively saying this is not our bug, as the SDL X11 code doesn't handle scaling at all, so whatever is doing this is further down the stack.

**Comment by jeannekamikaze** [comment]
Thank you for checking. I come from GLFW and hadn't noticed something like this before. Would it be any value to write an "equivalent" GLFW sample, or are SDL/GLFW two completely different beasts?

**Comment by Kontrabant** [comment]
Made this quick sample in GLFW
```
#include <GLFW/glfw3.h>

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv)
{
    int xpos, ypos, height;
    const char* description;
    GLFWwindow* window;

    if (!glfwInit())
    {
        glfwGetError(&description);
        printf("Error: %s\n", description);
        exit(EXIT_FAILURE);
    }

    glfwWindowHint(GLFW_DECORATED, GLFW_TRUE);

    window = glfwCreateWindow(901, 601, "Example", NULL, NULL);
    if (!window)
    {
        glfwGetError(&description);
        printf("Error: %s\n", description);
        glfwTerminate();
        exit(EXIT_FAILURE);
    }

    glfwSetInputMode(window, GLFW_STICKY_KEYS, GLFW_TRUE);

    glfwMakeContextCurrent(window);
    glClearColor(0.0f, 0.0f, 0.0f, 1.f);

    for (;;)
    {

        glfwMakeContextCurrent(window);
        glClear(GL_COLOR_BUFFER_BIT);
        glfwSwapBuffers(window);

        if (glfwWindowShouldClose(window) ||
            glfwGetKey(window, GLFW_KEY_ESCAPE))
        {
            glfwTerminate();
            exit(EXIT_SUCCESS);
        }

        glfwWaitEvents();
    }
}
```

The white line is still there, so this is definitely something else scaling the window and rounding off the size, since odd sizes aren't divisible evenly by 2.

**Comment by Kontrabant** [comment]
Closing as notourbug. Ubuntu sometimes pulls in non-upstreamed patches for their GNOME fork, so this should be reported to them.
