### ISSUE TITLE
Device not found error on SDL_Init()

### ISSUE THREAD

**Issue by captain1947** [libsdl-org/SDL#9660]
If I run this simple piece of code
```cpp
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

int main(int, char**) {
	if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS | SDL_INIT_CAMERA) < 0) {
		SDL_Log("Error: %s", SDL_GetError());
	}

	SDL_Window *window = SDL_CreateWindow("Test", 800, 600, 0);
	SDL_Renderer *renderer = SDL_CreateRenderer(window, NULL, 0);

	SDL_Log("Error: %s", SDL_GetError());

	bool rng = true;
	SDL_Event event;

	while (rng) {
		if (SDL_PollEvent(&event)) {
			if (event.type == SDL_EVENT_QUIT)
				rng = false;
		}

		SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
		SDL_RenderClear(renderer);
		SDL_RenderPresent(renderer);
	}

	SDL_DestroyRenderer(renderer);
	SDL_DestroyWindow(window);

	return 0;
}

```
I get the output
`INFO: Error: Device not found`
The same happens if I put SDL_INIT_AUDIO in place of SDL_INIT_CAMERA. Though the camera api and the audio api both work as expected. I am on windows and a camera is present in the system.

**Comment by icculus** [comment]
Just to check: is it the `SDL_INIT_VIDEO` causing it?

**Comment by slouken** [comment]
You should only check the error if an API function returned an error code.

**Comment by captain1947** [comment]
@icculus no it's `SDL_INIT_CAMERA` and/or `SDL_INIT_AUDIO`.
@slouken Oh, makes sense. Actually, I was trying to debug a different issue and was kinda lost. So, thought about putting a SDL_GetError() to see if it catches anything.

**Comment by xlievo** [comment]
> Just to check: is it the causing it?`SDL_INIT_VIDEO`

YSE! 
SDL_Init(SDL_INIT_AUDIO);
SDL_GetError();
Device not found
