### ISSUE TITLE
testdropfile: Wayland display connection closed after repeatedly dropping file

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#9667]
After repeatedly dropping a file on testdropfile, the following error appears and the application closes:
```
Wayland display connection closed by server
```
I cannot reproduce with the x11 video driver.

How to reproduce:
1. Start GNOME Files/Nautilus (=file explorer)
2. Run `testdropfile` (from terminal, or from an ide), with the wayland video driver
3. Repeatedly drop a file from the file explorer on the `testdropfile` window

Sometimes immediately, but always after less then 10 drops, the error above appears and the app is closed.

System:
Fedora 39 x86_64
libwayland-client 1.22.0

**Comment by Kontrabant** [comment]
This is a long-standing issue with the connection buffer filling up, which causes the server to close the connection. It can happen with any types of events if the application doesn't pump events frequently enough, but it seems particularly problematic with high-refresh mice and drag-and-drop.

It has _finally_ [been fixed upstream](https://gitlab.freedesktop.org/wayland/wayland/-/commit/d074d52902633d8700ce06b484508db0f8fba02b), and now it just has to be deployed.
