### ISSUE TITLE
Feature Request: Debugging Symbols for Windows

### ISSUE THREAD

**Issue by grochoge** [libsdl-org/SDL#9677]
Please include debug symbols (.pdb files) for Windows as part of a release.

I see #8415 added them to cmake install, but they don't appear to be captured in any of the release archived in GitHub.

I see SDL3 has them in the artifacts captured by Github Actions, but I don't see any artifacts for SDL2. These also expire relatively shortly.

**Comment by slouken** [comment]
The SDL2 releases are built using a gcc cross-compiler and PDBs are not available. You’re always welcome to build it yourself if you want symbols.

**Comment by madebr** [comment]
I think he is talking about the MSVC releases.
For SDL3, SDL3.dll is rebuilt between MSVC and MinGW. So 2 SDL3.dll binaries are released.

**Comment by slouken** [comment]
Yes, the MSVC releases are built with gcc

**Comment by madebr** [comment]
And SDL2_test by MSVC?
So to reproduce this for SDL3, I'd need to make the MSVC release depend on mingw, and just throw away the SDL3 dll built by the MSVC project?

**Comment by slouken** [comment]
That’s not a goal for SDL3, it’s just a side effect of my custom release process. I think the SDL3 build process is an improvement, thanks!

**Comment by madebr** [comment]
Then releasing pdb's is possible for SDL3.
The binaries are built with the MSVC project in Release mode.
So I don't think pdb's are generated at the moment.

**Comment by madebr** [comment]
Adding pdb's to the SDL3 VC devel packages would increase its size from 2608 kB to 8232 kB.

**Comment by sezero** [comment]
> Adding pdb's to the SDL3 VC devel packages would increase its size from 2608 kB to 8232 kB.

Dude, look at the size of mingw devel package :)
