### ISSUE TITLE
Dump SDL_vulkanInstance and SDL_vulkanSurface?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9678]
`SDL_vulkanInstance` and `SDL_vulkanSurface` were left in SDL_vulkan.h for compatibility with "Tizen," which I don't know much about except it had some sort of SDL2 port that added Vulkan functionality before we did.

Does anyone know if they're still a going concern in general? And if they are, they'll still need to port their apps to the new API to use SDL3, so can we remove these typedefs?

**Comment by slouken** [comment]
Yes, we can re-add them if they’re important.
