### ISSUE TITLE
[KMSDRM] is there any way to have SDL set display mode in portrait mode? 

### ISSUE THREAD

**Issue by Raffaello** [libsdl-org/SDL#9682]
When using a `KMSDRM` is not possible to have a portrait window using SDL as the hardware mode are in a landscape format with a `panel_orientation`. It looks like SDL doesn't take into account any possible display orientation. 

Using also the `SDL_SetDisplayMode` won't work.

Basically as a simple test would be enough to have a whatever resolution, let say 1920x1080, and create in a portrait mode the full-screen window (1080x1920).

The SDL window is always in a landscape mode.

**Comment by Raffaello** [comment]
for e.g. wayland/weston using KMSDRM are taking advantages of `panel_orientation` parameter:
ref: https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/315

SDL when creating a window if it is using wayland al is ok as it is delegated to window manager, but in case of single window application mode, without window manager there is no really a way to tell SDL (when using KMSDRM) to create in portrait mode the window.

i think it should query kmsdrs to retrieve that parameter `panel_orientation` to adjust accordingly setting up to respect the kmsdrm video driver. 
or having an env variable `SDL_KMSDRM_WINDOW_ORIENTATION=portrait`  to override evenually any settings.

or something like that.

**Comment by slouken** [comment]
@Kontrabant, is this reasonable?

**Comment by Kontrabant** [comment]
Sure, just have to check the "panel orientation" property when enumerating kmsdrm displays and pass the info to the SDL display info as is done in the other video backends.

**Comment by Kontrabant** [comment]
@Raffaello would you be able to try the pull and see if it works for your needs?

**Comment by Raffaello** [comment]
@Kontrabant yes, i think so. I will try tomorrow.

**Comment by Raffaello** [comment]
@Kontrabant unfortunately i can't test it, as i am still using SDL2 version 2.30, that PR is for SDL3. 

I tried manually to apply the patch as it is just 1 single file changed, but it looks like  SDL3 has further improvement that makes that PR incompatible with SDL2.30 

```
SDL_VideoDisplay' has no member named 'current orientation'
SDL_VideoDisplay' has no member named 'natural_orientation'
``` 

i might will upgrade to SDL3 when it will be out. 

Thanks for now

**Comment by Kontrabant** [comment]
I backported it to SDL2 here: https://github.com/Kontrabant/SDL/tree/SDL2_kmsdrm_orientation

**Comment by Raffaello** [comment]
i'll have a look tomorrow. thanks.

**Comment by Raffaello** [comment]
i have a segmentation error at the `SDL_Init` video point.

I have no problem when using `Wayland` video driver

this is `strace` when using `KMSDRM`.
```
openat(AT_FDCWD, "/dev/dri/card1", O_RDWR|O_CLOEXEC) = 3
ioctl(3, DRM_IOCTL_MODE_GETRESOURCES, 0x7ffdfb0595d0) = 0
ioctl(3, DRM_IOCTL_MODE_GETRESOURCES, 0x7ffdfb0595d0) = 0
ioctl(3, DRM_IOCTL_MODE_GETCONNECTOR, 0x7ffdfb059580) = 0
ioctl(3, DRM_IOCTL_MODE_GETCONNECTOR, 0x7ffdfb059580) = 0
ioctl(3, DRM_IOCTL_MODE_GETCONNECTOR, 0x7ffdfb059580) = 0
ioctl(3, DRM_IOCTL_MODE_GETCONNECTOR, 0x7ffdfb059580) = 0
ioctl(3, DRM_IOCTL_MODE_GETENCODER, 0x7ffdfb059530) = 0
ioctl(3, DRM_IOCTL_MODE_GETENCODER, 0x7ffdfb059530) = 0
ioctl(3, DRM_IOCTL_MODE_GETENCODER, 0x7ffdfb059530) = 0
ioctl(3, DRM_IOCTL_MODE_GETENCODER, 0x7ffdfb059530) = 0
ioctl(3, DRM_IOCTL_MODE_GETENCODER, 0x7ffdfb059530) = 0
ioctl(3, DRM_IOCTL_MODE_GETCRTC, 0x7ffdfb0594e0) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb059470) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb059470) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059420) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059420) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059490) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059490) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb0594b0) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb0594b0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb059470) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb059470) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059420) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059420) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_OBJ_GETPROPERTIES, 0x7ffdfb0594a0) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059490) = 0
ioctl(3, DRM_IOCTL_MODE_GETPROPERTY, 0x7ffdfb059490) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x2} ---
```

**Comment by Kontrabant** [comment]
Pushed some changes that should (hopefully) fix this.

**Comment by Raffaello** [comment]
now is working and running fine, but no changes in the window orientation/rotation. 
It is still in the "normal view". 

KMSDRM has also this other prop: `rotate` that might affect it?
reF: https://patchwork.kernel.org/project/dri-devel/patch/2afd45902d7e1e849d0aa7a0c4268c424cabe778.1554988934.git-series.maxime.ripard@bootlin.com/

**Comment by Kontrabant** [comment]
Correct, unlike higher-level windowing systems, the panel orientation property of KMSDRM is just metadata; it doesn't actually change any coordinate systems, which is why I now think this is better exposed as a KMSDRM-specific display property instead of setting the display orientation directly, as things like cursor coordinates are also unaffected by it.

With KMSDRM being low-level, applications are generally expected to handle coordinate transformations themselves. I believe that people have investigated using the hardware plane rotation property in the past and concluded that it is a bad general fit for SDL, due to requiring hardware support, rotated planes requiring special tiling, and so on.

**Comment by bigfatbrowncat** [comment]
Ok, we have to rotate our image according to the metadata. That makes sense. What about the mouse cursor? How could its posittion be recalculated and its image rotated?

**Comment by Raffaello** [comment]
@Kontrabant could it work if setting the property in the KMSDRM with: `KMSDRM_drmModeObjectSetProperty` using the `DRM_MODE_OBJECT_PLANE` after query the panel orientation  ( if the hardware monitor support it)?
