### ISSUE TITLE
The Sensor API may send duplicate events with the same timestamp, confusing downstream consumers

### ISSUE THREAD

**Issue by antheas** [libsdl-org/SDL#9688]
Under certain circumstances, the sensor polling drivers may send an update without having new sensor data, which will contain a duplicate sensor timestamp. If the sensor timestamp is assumed to be unique by library users, this can cause a division by zero, which destabilizes their Gyro implementation.

Steam, at least, has this problem. It uses the sensor timestamp for both gyroscope and touchpad events. Any duplicate timestamp will cause a large camera jitter in game that makes it unusable (Under the Gyro to Mouse mode, or if the touchpad has enabled acceleration).

## Dualsense Driver
The hidapi Dualsense driver will always send sensor events, even if the timestamp is the same (and perhaps overflow itself).
https://github.com/libsdl-org/SDL/blob/7856c8fb8fec5114af54299a8cafa81db507a0b6/src/joystick/hidapi/SDL_hidapi_ps5.c#L1312-L1359

This is not a problem with real dualsense controllers, as they always send unique timestamps (?), but may be a problem with third party controllers. It is certainly a problem with controller emulators such as those based on [ViGEm](https://vigembusdriver.com) on Windows (e.g., [Handheld Companion](https://github.com/Valkirie/HandheldCompanion), potentially Sunshine), or in the linux side on a project I'm involved in, [Handheld Daemon](https://github.com/hhd-dev/).

The problem here arises from the fact that it's common for game controllers to have 200-500hz polling rates, whereas the onboard IMU of devices is around 100hz (e.g., Legion Go is 500hz, its controller gyros are 125hz, Bosch windows driver is 100hz).
On Linux we can go higher, up to 1600hz.

A potential solution to this is syncing the controller output to the gyro. This is done by Handheld Daemon and works perfectly well. However, this is not an ideal solution, as it lowers the polling rate of the controllers (e.g., Legion Go becomes 125hz).

## Linux Evdev Driver
Currently, I am working on a reference evdev implementation for IMU in userspace in [Handheld Daemon](https://github.com/hhd-dev/). It works quite well, both in Steam and in emulators. 

However, when playing Spiderman Remastered (by emulating a JoyCon pair for gyro, paddles) once every 1-2 minutes I get a large gyro jitter while gaming in Steam. Here, the solution is out of my hands, as the duplicate timestamp is produced by SDL (I suspect).

In the following code, if SDL does not poll the sensor fast enough, it will receive a `SYN_DROPPED` event.
https://github.com/libsdl-org/SDL/blob/7856c8fb8fec5114af54299a8cafa81db507a0b6/src/joystick/linux/SDL_sysjoystick.c#L2126-L2143

When that happens, the function `PollAllSensors` is called, which emits an event without updating the `sensor_tick` variable. This always results in a duplicate timestamp.
https://github.com/libsdl-org/SDL/blob/7856c8fb8fec5114af54299a8cafa81db507a0b6/src/joystick/linux/SDL_sysjoystick.c#L1924-L1957

I made sure that as far as Handheld Daemon is concerned, it will only send a `syn` event after a timestamp has been sent. However, it is out of my hands whether SDL will receive a `SYN_DROPPED` event.

Perhaps `sensor_tick` should not be assumed to be unique. Then, this would be a problem for clients to deal with (e.g., Steam), and the function comment should be updated to reflect that. See below: 
https://wiki.libsdl.org/SDL3/SDL_GamepadSensorEvent

If sensor_tick should be assumed to be unique, then SDL would have to be updated to ensure it always sends a unique sensor timestamp. For that there could be two potential solutions:
  1) **Skip Sending Events with 0 Delta**: For Dualsense, this could be done by checking the delta and if it is 0, skipping updating the sensors. For evdev, if a `SYN_DROPPED` happens, `PollAllSensors` could be modified to not send an event in favor of waiting for the next event. 
     - This would have the minor issue of lowering the polling rate slightly, and breaking non-compliant controllers that do not have a hw timestamp.
  2) **Send Synthetic Delta**: If a `SYN_DROPPED` happens, or the Dualsense controller sends a duplicate timestamp, a synthetic delta based on `SDL_GetTicksNS` could be used. 
     - This would maintain the polling rate of the controllers, and restore functionality with devices that do not meet spec (e.g., controller emulators without a hw timestamp). However, it would interfere with motion vectoring (e.g., touchpad acceleration), if the downstream consumer expects that.
     - In fact, when testing using a synthetic timestamp version in earlier versions of Handheld Daemon, I noticed that gyro to camera would experience slight stutters, so perhaps this is not a good solution. I attributed that to inconsistent wake-up times, but it could have been something else.
     - The current version always uses the sensor hardware timestamp, and behavior is excellent, other than the evdev occasional stutter (which is part of and blocks the release of the next version).

Would love to hear your thoughts. If in the end, this is a docs issue and a problem on Steam's side, I'd also appreciate help with forwarding the issue. 

Sidenote: as part of Handheld Daemon, I have implemented Linux support for all Windows handhelds in the market right now (see [here](https://github.com/hhd-dev/hhd#supported-devices)) including RGB and touchpads in Steam Input and I would be interested in defining a spec for handheld controllers, so we can get away from hacks such as emulating Dualsense or Joycon controllers, which have Glyph issues and non-matching capabilities.

Perhaps starting by making the appropriate extensions to the evdev API, which can be the foundation to a hid API and kernel driver that is implemented in firmware by device manufacturers. Current devices are a hodgepodge of different vendor specific windows devices, so a tool like Handheld Daemon w/ root access is needed to fuse them together in a cohesive manner. This should not be the case with future devices, and the sooner we start the better.

**Comment by slouken** [comment]
If I'm reading this right, we should only send a sensor update if we got an MSC_TIMESTAMP event in the previous event cycle, or we never get a timestamp event. Is the solution that simple?

 ```diff
diff --git a/src/joystick/linux/SDL_sysjoystick.c b/src/joystick/linux/SDL_sysjoystick.c
index ed7cf8f2a..5f21f51fc 100644
--- a/src/joystick/linux/SDL_sysjoystick.c
+++ b/src/joystick/linux/SDL_sysjoystick.c
@@ -2050,8 +2050,10 @@ static void HandleInputEvents(SDL_Joystick *joystick)
                     case SYN_REPORT:
                         if (joystick->hwdata->recovering_from_dropped_sensor) {
                             joystick->hwdata->recovering_from_dropped_sensor = false;
-                            PollAllSensors(SDL_GetTicksNS(), joystick); // try to sync up to current state now
-                        } else {
+                            break;
+                        }
+                        if (!joystick->hwdata->last_sensor_tick ||
+                            joystick->hwdata->sensor_tick != joystick->hwdata->last_sensor_tick) {
                             Uint64 timestamp = SDL_EVDEV_GetEventTimestamp(event);
                             SDL_SendJoystickSensor(timestamp, joystick, SDL_SENSOR_GYRO,
                                                    SDL_US_TO_NS(joystick->hwdata->sensor_tick),
@@ -2059,6 +2061,7 @@ static void HandleInputEvents(SDL_Joystick *joystick)
                             SDL_SendJoystickSensor(timestamp, joystick, SDL_SENSOR_ACCEL,
                                                    SDL_US_TO_NS(joystick->hwdata->sensor_tick),
                                                    joystick->hwdata->accel_data, 3);
+                            joystick->hwdata->last_sensor_tick = joystick->hwdata->sensor_tick;
                         }
                         break;
                     default:
diff --git a/src/joystick/linux/SDL_sysjoystick_c.h b/src/joystick/linux/SDL_sysjoystick_c.h
index 517854d6d..e5e87095f 100644
--- a/src/joystick/linux/SDL_sysjoystick_c.h
+++ b/src/joystick/linux/SDL_sysjoystick_c.h
@@ -88,6 +88,7 @@ struct joystick_hwdata
      * LINUX_JoystickUpdateupdate(), store them for the next one */
     float gyro_data[3];
     float accel_data[3];
+    Uint64 last_sensor_tick;
     Uint64 sensor_tick;
     Sint32 last_tick;


```

**Comment by antheas** [comment]
Hi Sam,
The current status of this issue is that I suspect Steam went with the N2 fix. So right now, provided a dualsense controller clamps to the gyro rate, we have no issues. Likewise, evdev has a separate gyro `SYN` and has no issues. On the rare situation that lead to an invalid timestamp, a synthetic delta is used instead.

This has been the case the past 2 months I think.

However, if we unclamp the controller rate on the dualsense handler (e.g., controller is 500hz, gyro is 125hz), steam uses fake deltas, which breaks gyro vectoring on the new Steam Input backend. This results in "mushier" gyro.

For example, if there is a controller that is 400hz and a gyro that is 100hz, we get the chain `GYRO -> JUST_CONTROLLER ->  JUST_CONTROLLER -> GYRO`. We would expect the receiver to say ok, i have 2 gyro events with 4ms inbetween and do proper vectoring. However, Steam would see the first 3 events have the same timestamp, and use synthetic deltas for them which results at having peak at the end.

Your patch would solve both parts I think. But it might have unintended regressions (e.g., when is `joystick->hwdata->last_sensor_tick` 0?) so it might need some extra thought.

By the way, currently we emulate a Horipad Steam controller through evdev for gyro as it has correct glyphs and does not need to clamp. Vibration works as well because of evdev. Dualsense is a niche feature now. So from my end this issue is solved. We still have the capability issue. Handhelds do not have capacitive sticks and most of them do not have 4 buttons. Also, roll needs to be reversed, 3D to 2D conversion is set to Yaw by default and gyro is set to enable on capacitive touch, both of which are broken for handhelds, etc. So lmk if you want to re-open that discussion.

**Comment by slouken** [comment]
Okay, I'll mark this as closed for now. Feel free to reopen it if that patch is useful or there's something more we need to do here with sensor reports.
