### ISSUE TITLE
SDL3 and CMake: Need equivalent to SDL2_LIBDIR

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#9697]
For building my application bundle on macOS via CMake I used this command to copy SDL2.framework to my application bundle:

`COMMAND cp -R ${SDL2_LIBDIR} ${BUNDLE_CONTENTS}/Frameworks/`

Unfortunately this no longer works with SDL3 because there is no SDL3_LIBDIR and I was not able to find an equivalent to it. Therefore I request to add this to SDL3.

**Comment by madebr** [comment]
Use [CMake generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html) instead: `$<TARGET_FILE_DIR:SDL3::SDL3-shared>`.

**Comment by andreasgrabher** [comment]
Thank you! This seems to work if with this line:

`COMMAND cp -R $<TARGET_FILE_DIR:SDL3::SDL3-shared>/SDL3.framework ${BUNDLE_CONTENTS}/Frameworks/`

Is there an expression that directly points to the framework itself? It seems there is _sdl3_framework_path in the scripts. This might be what I am looking for but unfortunately it gets unset at the end of the script.

**Comment by madebr** [comment]
Does `TARGET_FILE` work?

**Comment by andreasgrabher** [comment]
Yes, this one works:

`COMMAND cp -R $<TARGET_FILE:SDL3::SDL3-shared> ${BUNDLE_CONTENTS}/Frameworks/`

Thank you very much! Maybe there could be some documentation about the existence and the contents of these expressions?

**Comment by madebr** [comment]
Looks like it.
I'll add a section to the CMake and migration documentation.
