### ISSUE TITLE
Perspective correct texture mapping for SDL_RenderGeometry() in SDL3

### ISSUE THREAD

**Issue by duerdak** [libsdl-org/SDL#9701]
My understanding is that SDL_RenderGeometry() in SDL2 only does affine texture mapping. Now that SDL3 will have a new gpu API is it possible to change SDL_RenderGeometry() to do perspective correct texture mapping?
SDL_RenderGeometry() probably shouldn't be used for any serious 3D but if this is implemented it would be an easy way for people to get started with making a spinning cube for example or a very simple 3d game and at least much simpler than using OpenGL, Vulkan etc. Since i don't know of any plans for there to be a 3D API akin to the 2D one I'd consider this almost a simplified version of the future gpu api.

**Comment by slouken** [comment]
We don't plan to add perspective correct texture mapping to the render API. I recommend using a 3D API for that.
