### ISSUE TITLE
NULL dialog filter SDL_ShowOpenFileDialog crashes on Windows

### ISSUE THREAD

**Issue by JoelLinn** [libsdl-org/SDL#9702]
1. When setting the `filters` parameter to `NULL`, SDL crashes in the dialog thread inside of the `convert_filters` function. Related to #9665 
2. When setting an empty filters list, memory is read out of bounds and a gibberish filter is set in the dialog.             `SDL_DialogFileFilter filters[1] = { {nullptr, nullptr} };`

**Comment by Semphriss** [comment]
I could find the cause for both and wrote the fix, but I currently don't have a Windows machine around me to test it. I'll do that later today and open a PR after testing.
