### ISSUE TITLE
Please add SPEEDLINK STRIKE Gamepad support

### ISSUE THREAD

**Issue by ProjectXsent** [libsdl-org/SDL#9705]
I'm using a T-Wolf Controller with SPEEDLINK STRIKE Gamepad driver installed on Windows.

Here's my mapping string.
`03001158790000000600000000000000,SPEEDLINK STRIKE Gamepad,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b6,righttrigger:b7,platform:Windows,`

My controller was previously detected as "G-Shark GS-GP702" in SDL2 v2.30.0 x86 but was replaced and detected as "Sanwa Supply JY-P76USV" in the later versions with a different mapping in which I cannot use in DMC3SE Inputs Thing mod. It was also detected as Sanwa in SDL2 Gamepad Mapper.

**Comment by slouken** [comment]
Added, thanks!

**Comment by ProjectXsent** [comment]
Hello again. 

I think the `crc:5811` part must be removed since it doesn't work anymore for SDL3 and when using SDL2 Compat.

I guess you can change the whole preset into
`"0300457e790000000600000000000000,DragonRise Inc. Generic USB Joystick,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a3,righty:a4,start:b9,x:b3,y:b0,",`

I tried building myself and now it works.
