### ISSUE TITLE
Can't init SDL wayland not available

### ISSUE THREAD

**Issue by shmerl** [libsdl-org/SDL#9707]
After recent updates in Debian testing, SDL stopped working in Wayland mode for a few (but not all) scenarios. In particular, for scummvm and dosbox-staging when setting `SDL_VIDEODRIVER='wayland'`
Example for dosbox-staging error:

```
Stack trace:
3             0x4d54de _start + 46
2       0x7fe721443c45 __libc_start_main + 133
1       0x7fe721443b8a /lib/x86_64-linux-gnu/libc.so.6(+0x27b8a) [0x7fe721443b8a]
0             0x77bb91 sdl_main(int, char**) + 7649
2024-05-06 19:02:28.290 | ABORT: SDL: Can't init SDL wayland not available
```

Scummvm error:

```
Could not initialize SDL: wayland not available!
```

* DE: KDE Plasma 5.27.10, Wayland session.
* SDL2: 2.30.2

I was able to use SDL in Wayland mode in other cases for example with freerdp SDL client.

Any idea what can be causing it and how can this be troubleshooted?

**Comment by shmerl** [comment]
Oh, my fault, I realized this is not caused by SDL, but by attaching mangohud to it. False alarm.

**Comment by slouken** [comment]
Okay, thanks for letting us know.

**Comment by shmerl** [comment]
For the reference, if anyone needs. I had an outdated mangohud build and hooking that with LD_PRELOD was breaking something for OpenGL. Making it up to date fixed it.
