### ISSUE TITLE
Feedback on page SDL3/SDL_SetRenderViewport

### ISSUE THREAD

**Issue by renebarto** [libsdl-org/SDL#9725]
SDL_SetRenderViewport does not seem to do anything when x, y != 0,0. The calls do not render anything in that case.

**Comment by icculus** [comment]
This was a comment on the wiki from some time ago; can someone verify if this is working now?

**Comment by madebr** [comment]
testviewport seems to work fine (for me).
It tests `SDL_SetRenderViewport` and `SDL_SetRenderClipRect`.
