### ISSUE TITLE
Window position changes when re-sizing window

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#9730]
I am experiencing the following issue:

My application has a status bar at the bottom of the window. There is an option to show or hide that bar. The window's size is modifies accordingly. If I do this with SDL3 my window moves to towards the bottom instead of staying in place. This did not happen with SDL2.

This is the simplified code:
```
int w = 0;
int height = 1000;
int width  = 1000;
SDL_Window* sdlWindow  = SDL_CreateWindow("Test", width, height, SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY);
height -= 100;
SDL_GetWindowSize(sdlWindow, &w, NULL);
SDL_SetWindowSize(sdlWindow, w, (height*w)/with);

```

**Comment by slouken** [comment]
What platform are you running on?

**Comment by andreasgrabher** [comment]
I am running on macOS Sonoma v14.4.1 on a Mac mini M1.
