### ISSUE TITLE
Please clarify which thread the main callbacks run on

### ISSUE THREAD

**Issue by Kaktus514** [libsdl-org/SDL#9731]
The docs describing the [main callbacks](https://wiki.libsdl.org/SDL3/README/main-functions#how-to-use-main-callbacks-in-sdl3) only mention threads in this one sentence about `SDL_AppEvent`:

> This will be called whenever an SDL event arrives, on the thread that runs SDL_AppIterate.

which makes me wonder which thread that is and what about the other callbacks? 

If it wasn't for this sentence I would be tempted to assume all callbacks will always be called on the main thread. If some of the callbacks can run on other threads that is something I would really want to know about so that I can use proper thread synchronization and knows which SDL functions that are safe to call.

**Comment by slouken** [comment]
It was actually supposed to comfort you to know that you don't have to worry about multi-threaded issues. I just removed it, since it's documented more clearly in the header and in general you don't have to think about it.
