### ISSUE TITLE
Does SDL_SetWindowMinimumSize work before creating a renderer?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9736]
So this PR to the wiki:

https://github.com/libsdl-org/sdlwiki/pull/142

says:

> Calling this function _before_ creating a renderer will have no effect.

This was in reference to SDL2; can someone verify?

(and maybe was this on Wayland, which has some different rules about GUI app lifecycle)

**Comment by slouken** [comment]
This was a bug where the minimum and maximum size would be lost when recreating the window as OpenGL. It's been fixed in SDL3.
