### ISSUE TITLE
Incorrect mouse position on first SDL_WarpMouseInWindow() call in fullscreen

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#974]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [A short SDL program that demonstrates the bug (main.cpp, text/x-c++src, 2013-07-18 23:30:08 +0000, 1015 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1241)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2013-07-18 23:30:08 +0000,  wrote:

> Created attachment 1241
> A short SDL program that demonstrates the bug
> 
> Upon calling SDL_WarpMouseInWindow(window, WINDOW_SIZE_X / 2, WINDOW_SIZE_Y / 2) (immediately after creating the window) in a fullscreen SDL window, the cursor is not placed in the center, but slightly to the lower right. If the mouse is not moved (by the user) before exiting the program, the cursor will be moved (by SDL) to the center of the screen on exit. If SDL_Delay(x) is called before SDL_WarpMouseInWindow (where x > ~10), this fixes the bug.

On 2013-07-24 17:16:17 +0000,  wrote:

> I just found out that this doesn't happen if I wait until a SDL_WINDOWEVENT_FOCUS_GAINED event to warp the mouse.

On 2013-10-07 21:17:33 +0000, (disabled) Jørgen Tjernø wrote:

> Bonsairobo, can you try reproducing with the latest HG version of SDL2? (I.e. one including this change: http://hg.libsdl.org/SDL/rev/b8d4be87970a)
> 
> Hopefully that fixes your issue.

On 2013-10-07 21:47:49 +0000,  wrote:

> (In reply to Jørgen Tjernø from comment # 2)
> > Bonsairobo, can you try reproducing with the latest HG version of SDL2?
> > (I.e. one including this change: http://hg.libsdl.org/SDL/rev/b8d4be87970a)
> > 
> > Hopefully that fixes your issue.
> 
> I didn't notice a change. The bug persists for me. Used "hg clone http://hg.libsdl.org/SDL".

On 2013-10-08 00:23:46 +0000, (disabled) Jørgen Tjernø wrote:

> This seems to be due to the SDL_WarpMouseInWindow being called, and afterwards then we get an EnterNotify from the X server, telling us that the cursor is somewhere else. This is possibly related to how we fullscreen? This is not code I'm familiar with, so assigning back to Sam.

On 2014-01-28 11:02:48 +0000, Jon Lund Steffensen wrote:

> I'm stuck with porting to SDL2 on this same issue. It seems that the mouse position is incorrect after SDL_WarpMouseInWindow() both in (desktop) fullscreen mode and windowed mode whenever scaling is applied. If the logical screen is the same size as the window everything works as expected. SDL version 2.0.1.

**Comment by icculus** [comment]
Likely fixed since 2014...? We'll verify and fix/close for 2.0.18.

**Comment by icculus** [comment]
Tested this against the release-2.0.3 tag and bug is definitely there, and then tested against the main branch and it definitely isn't, so we're good to go here.
