### ISSUE TITLE
SDL_SetWindowPosition() does not work on Linux/X11

### ISSUE THREAD

**Issue by c-smile** [libsdl-org/SDL#9740]
SDL3

If window position is set at creation time by `SDL_SetNumberProperty(SDL_PROP_WINDOW_CREATE_X_NUMBER, 10)` then 
`SDL_SetWindowPosition()` does not work on Linux/X11. At all.

Note that is with X11 backend where window positioning is supposed to work.

**Comment by Kontrabant** [comment]
What desktop are you using? I'm not seeing this on GNOME or KDE.

**Comment by c-smile** [comment]
@Kontrabant : Linux Mint 21.3, GNOME/X11, high-dpi monitor if that matters.

I was trying to debug the issue here but I am lost in too many locations of window coordinates: window.x/y window.floating.x/y, window.expected.x/y and couple of more.

**Comment by Kontrabant** [comment]
Would you have a small reproduction sample that shows the issue? I've set up Mint 21.3 in a VM and I still can't replicate this. Running testsprite and changing the window position programmatically with shift+arrow keys works on both GNOME and the Cinnamon desktop, and I've also tried a sample program that creates the window in the hidden state, changes the position, then shows it, and it correctly appears at the last requested coordinates.
