### ISSUE TITLE
[SDL 2.28, latest mixer, ttf and image] Resize the window cause the texture to SWITCH to each other, NOT RAISE ERROR

### ISSUE THREAD

**Issue by thep1ckaxe91** [libsdl-org/SDL#9748]
https://github.com/thep1ckaxe91/Tetris-with-SDL2.git

I make an engine out of SDL (SDL 2.28 and other is latest) to simulate the feel of working with Pygame
But as the game goes on and I have many assets, it starts to get weird when I resize the game window

The images that have the same size switch to each other, for example, the start button switches to credit or quit when click
(You can achieve this by going into my game and deleting the images.load() in the handle event part in main.cpp, then just let the game load to the main menu and try to resize it)

It may be hard to believe, but you must try it out.

I wonder if it is related to the frame buffer change when we resize, but in any case, it just makes no sense to me.

I'm a new developer, so I haven't dove deep into low-level stuff. So it'd be helpful if anyone has the same problem or can figure it out.

**Comment by madebr** [comment]
Is your repo private? I cannot access it.

The problem you're seeing looks like a logic bug in your game.
I suggest to save (commit) everything, and remove logic from your game until the problem disappears.

**Comment by thep1ckaxe91** [comment]
> Is your repo private? I cannot access it.
> 
> The problem you're seeing looks like a logic bug in your game. I suggest to save (commit) everything, and remove logic from your game until the problem disappears.

Thanks for having a look and sorry for the inconvenience, I public it and you should be able to see it now.
As for your solution, I tried previously but only to the point I found out that the pointer to the texture doesn't change, the texture I called to draw and the texture I want to is indeed the same.

**Comment by thep1ckaxe91** [comment]
Turn out, Direct3D was the problem, i found a post after make a small test example I got some kind of error: D3DPOOL_DEFAULT...
Direct3D will for some reason, lose or somehow the data of the texture is broke when window lost focus, therefore, all we need to do is set the renderer driver hint by SetHintPriority to "opengl"
I'm using window, which default it will pick Direct3D as driver

**Comment by thep1ckaxe91** [comment]
close
