### ISSUE TITLE
What's SDL_LoadObject behavior on iOS, using SDL 2.23

### ISSUE THREAD

**Issue by Longtianmu** [libsdl-org/SDL#9749]
What's the actually behavior of SDL_LoadObject?
Since I do link static library to Xcode project, it still cannot load the library.

**Comment by madebr** [comment]
`SDL_LoadObject` is an abstraction arounc [`dlopen(3)`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dlopen.3.html).

`SDL_LoadObject` has nothing to do with linking against a shared or static SDL:
- with `SDL_LoadObject` you can dlopen any other shared library and call symbols from it (using `SDL_LoadFunction`)
- linking against a static SDL library, means your application does not need a SDL framework or SDL dylib.

**Comment by madebr** [comment]
The logic goes like:
```c
#include <SDL3/SDL.h>
int main(int argc, char *argv[]) {
  void *libc = SDL_LoadObject("libc.so.6");
  void (*libc_printf)(const char *fmt, ...) = (void*)SDL_LoadFunction(libc, "printf");
  libc_printf("Hello %s! SDL%d rules!\n", "world", 3);
  SDL_UnloadObject(libc);
  return 0;
}
```

**Comment by icculus** [comment]
Which is to say if you just want to use SDL itself, you don't have to use SDL_LoadObject at all. It's for loading other libraries that you didn't link directly to...which you rarely have to do on iOS.

**Comment by icculus** [comment]
Anyhow, if you have questions about using SDL, asking on [our forums](https://discourse.libsdl.org/) or [our Discord server](https://discord.gg/BwpFGBWsv8) helps us keep the bug tracker manageable.

Thanks!
