### ISSUE TITLE
Rename header SDL_misc.h to SDL_url.h

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9750]
Probably not worth it.

The header `SDL_misc.h` sounds vague but at same time more important than just the one function that is in it.

**Comment by slouken** [comment]
Agreed.

**Comment by icculus** [comment]
I always assumed other things would collect in there. I'm surprised they never did.

**Comment by slouken** [comment]
I'm fine with renaming this, if you want. We can always re-add SDL_misc.h if we have more miscellaneous things to add.
