### ISSUE TITLE
SDL3  SDL_GetStoragePathInfo not return 0

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#9755]
in windows ,if success It return 1
https://github.com/libsdl-org/SDL/blob/323bab9305db74a5049e7b1a689483f3fb6402d5/include/SDL3/SDL_storage.h#L347
https://github.com/libsdl-org/SDL/blob/323bab9305db74a5049e7b1a689483f3fb6402d5/src/filesystem/windows/SDL_sysfsops.c#L172

**Comment by slouken** [comment]
Fixed, thanks!
