### ISSUE TITLE
SDL_TextEditingEvent.edit.start will go wrong

### ISSUE THREAD

**Issue by signin0** [libsdl-org/SDL#9761]
Keep pressing the left arrow and the error is 3
```c
#include <SDL2/SDL.h>

int main(int argc, char *argv[]) {
    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER);
    SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1");
    SDL_CreateWindow("demo", 800, 80, 340, 740,SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE | SDL_RENDERER_PRESENTVSYNC);
    SDL_Event e;
    while (1) {
        if (SDL_PollEvent(&e)) {
            switch (e.type) {
                case SDL_QUIT:
                    return 0;
                case SDL_TEXTEDITING:
                    SDL_Log("%d|%d|%s\n", e.edit.start, e.edit.length, e.edit.text);
            }
        }
    }
}
```
![image](https://github.com/libsdl-org/SDL/assets/159759746/0ee236bc-fa47-461e-94f5-6324b05c4747)
It means a's|, but it's actually |a's

**Comment by slouken** [comment]
@zreedy, this is caused by this code in SDL_windowskeyboard.c:
https://github.com/libsdl-org/SDL/blob/f79d0adfc9300173669db646d68a567ed7196508/src/video/windows/SDL_windowskeyboard.c#L841-L873

I'm commenting it out for now, since this is clearly wrong here, but is there a better way to fix this?

**Comment by slouken** [comment]
@zreedy, I found the case you were trying to solve, and I handle both this and the case of the selected candidate in https://github.com/libsdl-org/SDL/commit/80e64ef9217a73e26764ca71f3b076ef0602590e. I only move the cursor to the end of the selected text if the candidate window is closed, which happens when a candidate is selected.

**Comment by zreedy** [comment]
@slouken My apologies for missing your original ping regarding this. These changes look good to me. I will keep an eye out for the next SDL2 release as these might break some of our Application-level workarounds for these bugs. If I find anything that's framework-level I'll follow up.

**Comment by slouken** [comment]
These changes are only in SDL3, so you should be fine for the next SDL2 release.

**Comment by slouken** [comment]
However, if you could grab the latest SDL3 code sometime soon and run testime through your test cases, I'd appreciate it!
