### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9764]
Here is a list of some magic numbers in the headers.

```c
SDL_GamepadSensorEvent.data[3]
SDL_SensorEvent.data[6]
SDL_Event.padding[128]
SDL_GUID.data[16]
SDL_HapticDirection.dir[3]
SDL_HapticCondition.right_sat[3]
SDL_HapticCondition.left_sat[3]
SDL_HapticCondition.right_coeff[3]
SDL_HapticCondition.left_coeff[3]
SDL_HapticCondition.deadband[3]
SDL_HapticCondition.center[3]
```

I was trying to replace some of these with a more descriptive macro constant or struct type.
But some of these are obvious enough and some can't be replaced by a struct because their used parameters and meaning vary.

Any thoughts?

**Comment by slouken** [comment]
I think we can leave them.
