### ISSUE TITLE
Fails to compile with WIN32_LEAN_AND_MEAN because OPENFILENAMEW is not defined

### ISSUE THREAD

**Issue by ror3d** [libsdl-org/SDL#9766]
I am adding SDL as a cmake sub-project of my main project.

In the main project, I have defined WIN32_LEAN_AND_MEAN.

Because of that, `src\dialog\windows\SDL_windowsdialog.c` fails to compile, as de header that defines `OPENFILENAMEW` is no longer included.

Adding `#include <commdlg.h>` after the include for windows.h fixes that.

**Comment by slouken** [comment]
Fixed, thanks!
