### ISSUE TITLE
Rename SDL_loadso.h?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9785]
Sacred cow from SDL1 here, but do we want to rename SDL_loadso.h to something more clear, like SDL_sharedobject.h or SDL_dynload.h or something?

**Comment by slouken** [comment]
Sure

**Comment by icculus** [comment]
I started doing this yesterday and didn't find a name I liked better than "loadso" anyhow. It gets a stay of execution for SDL3.
