### ISSUE TITLE
A few keycode/scancode renaming suggestions

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/SDL#9808]
`SDLK_a-SDLK_z` -> `SDLK_A-SDLK_Z` (uppercase)

`SDL_SCANCODE_NUMLOCKCLEAR` -> `SDL_SCANCODE_KP_NUMLOCK` (adding _KP, removing CLEAR)

`SDL_SCANCODE_AGAIN` -> `SDL_SCANCODE_REDO`

RIGHT/LEFT vs L/R:
```
SDL_SCANCODE_LCTRL
SDL_SCANCODE_LSHIFT
SDL_SCANCODE_LALT
SDL_SCANCODE_LGUI
SDL_SCANCODE_RCTRL
SDL_SCANCODE_RSHIFT
SDL_SCANCODE_RALT
SDL_SCANCODE_RGUI
SDL_SCANCODE_LEFTBRACKET   -> SDL_SCANCODE_LBRACKET
SDL_SCANCODE_RIGHTBRACKET  -> SDL_SCANCODE_RBRACKET
SDL_SCANCODE_KP_LEFTPAREN  -> SDL_SCANCODE_KP_LPAREN
SDL_SCANCODE_KP_RIGHTPAREN -> SDL_SCANCODE_KP_RPAREN
SDL_SCANCODE_KP_LEFTBRACE  -> SDL_SCANCODE_KP_LBRACE
SDL_SCANCODE_KP_RIGHTBRACE -> SDL_SCANCODE_KP_RBRACE
```

RETURN vs ENTER:
```
SDL_SCANCODE_KP_ENTER
SDL_SCANCODE_RETURN   -> SDL_SCANCODE_ENTER
```

PERIOD vs DOT:
```
SDL_SCANCODE_PERIOD    -> SDL_SCANCODE_DOT
SDL_SCANCODE_KP_PERIOD -> SDL_SCANCODE_KP_DOT
```

`SDL_SCANCODE_DISPLAYSWITCH` -> `SDL_SCANCODE_SWITCHVIDEOMODE`

A bit of clarification needed:
```
SDL_SCANCODE_APPLICATION
SDL_SCANCODE_APP1
SDL_SCANCODE_APP2
```

Shorten some names:
`SDL_SCANCODE_ESCAPE` -> `SDL_SCANCODE_ESC`
`SDL_SCANCODE_PRINTSCREEN` -> `SDL_SCANCODE_PRINT`
`SDL_SCANCODE_CALCULATOR` -> `SDL_SCANCODE_CALC`
`SDL_SCANCODE_MEDIASELECT` -> `SDL_SCANCODE_MEDIA`

**Comment by slouken** [comment]
We've considered this and there doesn't seem to be a lot of value in changing these. Thanks for the suggestion!
