### ISSUE TITLE
Some bitflags still need a typedef.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9812]
Right now SDL_Surface::flags is a Uint32. It should get the same typedef update (and wikiheaders magic) that other bitflags did.

**Comment by icculus** [comment]
Just grepping for `flags` here...

- SDL_GetPenCapabilities() needs this too.
- SDL_test_common.h has a `Uint32 flags` that is...probably?...meant to be SDL_InitFlags.
- SDL_test_common.h also has a `Uint32 verbose` that handles the VERBOSE_* defines above it.

**Comment by TerensTare** [comment]
Slightly off-topic but can I ask what is the reasoning behind having a typedef + macro values instead of simply an enum? I am trying to write a parser to help with #9771 and enums-over-macros would help a lot with parsing these bitflags under a common type.

**Comment by slouken** [comment]
Conceptually an enum is simply a set of valid values, and C++ enforces this. To be correct, all of the valid flag combinations would need to be added to the enumeration, which is unwieldy and in some cases not possible. The SDL headers have formalized a typedef followed by defines so language bindings and other parsers can rely on that.

**Comment by TerensTare** [comment]
I see the reasoning, that's unfortunate for C ... Would love to learn more about how this method is handled by language bindings though!

**Comment by icculus** [comment]
So if the parser is SDL-specific: by policy, these typedefs _always_ have the `#defines` directly after them, since we have a perl script that parses the headers to add these to wiki pages, like this one:

https://wiki.libsdl.org/SDL3/SDL_WindowFlags

If that makes it easier to parse for SDL specifically.

More explanation: https://wiki.libsdl.org/SDL3/README/documentation-rules#defines-right-below-typedefs-and-functions-bind
