### ISSUE TITLE
Occasional macOS CI failures

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9815]
macOS CI will fail occasionally with:
```
CPack Error: Error executing: /usr/bin/hdiutil create -ov -srcfolder "/Users/runner/work/SDL/SDL/build/dist/_CPack_Packages/Darwin/DragNDrop/SDL3-3.1.2-macOS-arm64-x64" -volname "SDL3 3.1.2" -fs "HFS+" -format UDZO "/Users/runner/work/SDL/SDL/build/dist/_CPack_Packages/Darwin/DragNDrop/temp.dmg"
CPack Error: Error generating temporary disk image.
hdiutil: create failed - Resource busy
```
Are we somehow running multiple builds out of the same directory?

**Comment by madebr** [comment]
This is an issue with CMake itself: https://gitlab.kitware.com/cmake/cmake/-/issues/19517
What we can do perhaps is ignore an error during package creation.

**Comment by slouken** [comment]
In our case we're creating a disk image and it looks like the disk image creation actually fails.

**Comment by madebr** [comment]
Looks like I pasted the wrong report: https://gitlab.kitware.com/cmake/cmake/-/issues/25671
(I reported our failure there already)

**Comment by slouken** [comment]
Can we retry the command if it fails with "Resource busy"?
