### ISSUE TITLE
arm optimized memset4 and memcpy4

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#982]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [checking GNUCC for __builtin function (1-check_for_some___builtin___functions.patch, text/plain, 2013-07-25 16:55:20 +0000, 1218 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1255)
* [arm optimized SDL_memset4 (2-ARM_optimized_SDL_memset4.patch, text/plain, 2013-07-25 16:55:52 +0000, 3001 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1256)
* [arm optimized SDL_memcpy4 (3-ARM_optimized_SDL_memcpy4.patch, text/plain, 2013-07-25 16:56:16 +0000, 2549 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1257)
* [original non-inlined memset4 version (sdl-framebuffer.patch, text/plain, 2013-07-25 16:57:19 +0000, 4078 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1258)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Other, ARM

# Comments on the original bug report:

On 2013-07-25 16:53:43 +0000, Vittorio Giovara wrote:

> Long time ago some code was posted here to improve the default implementation fo SDL_memset4 for arm (http://sdl.5483.n7.nabble.com/ARM-optimised-memset-td29728.html).
> I originally ported that code for the ancient GAS present in Xcode and then lost track of it when converting it to inline assembly.
> 
> When I found that code a few days ago and tried inlining it again but failed, So I looked if there were alternatives and found this nice code http://lists.uclibc.org/pipermail/uclibc/2003-September/027817.html that works well with SDL. I have a patch ready (attached) - there is no explicit license attached so I think the original author should be contacted about this use (and maybe improve it?).
> 
> Just as backup, I've included the original patch that still needs to be inlined if anyone would prefer that...
> 
> Then I noticed that also memcpy4 could be optimized, and added it even thought SDL doesn't use it internally -- maybe I placed the assembly in the wrong place, if so tell me and I'll move it.
> 
> 
> What also puzzled me a bit is that for SDL_memcpy there is a check for using __builtin_memcpy... so what is really preventing us for applying the same check for the other functions? I've added a third patch that adds this check for other functions too...
> 
> Besides alignment, what is preventing using the __builtin equivalent functions for memset?

On 2013-07-25 16:55:20 +0000, Vittorio Giovara wrote:

> Created attachment 1255
> checking GNUCC for __builtin function

On 2013-07-25 16:55:52 +0000, Vittorio Giovara wrote:

> Created attachment 1256
> arm optimized SDL_memset4

On 2013-07-25 16:56:16 +0000, Vittorio Giovara wrote:

> Created attachment 1257
> arm optimized SDL_memcpy4

On 2013-07-25 16:57:19 +0000, Vittorio Giovara wrote:

> Created attachment 1258
> original non-inlined memset4 version

On 2013-07-27 04:16:01 +0000, Sam Lantinga wrote:

> Thanks for the patches.  A few comments:
> 
> * Do you know what version of gcc provides each of those builtins?  I believe gcc 2.95 doesn't, for example, which is I think still used for the Haiku build.
> * I didn't check your assembly, but your SDL_memset4() is a 32-bit set, not an 8-bit set, correct?
> * SDL_memcpy4() has been removed, since it isn't faster than modern memcpy functions.

**Comment by kodabb** [comment]
hi, i'm the original reporter, i believe we can close the bug, in the last 8 years things have improved so much that these patches are probably not necessary

**Comment by sezero** [comment]
> hi, i'm the original reporter, i believe we can close the bug, in the last 8 years things have improved so much that these patches are probably not necessary

OK then, closing.
