### ISSUE TITLE
[SDL2 Vita] Wrong touch IDs gets assigned to touch devices

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#9830]
Hello!

I do see that at the SDL2 touch device IDs gets assigned incorrectly: one of IDs had been assigned as 0 that results an invalid behaviour: the SDL_GetTouchDevice() claims the 0 is an invalid device, but [in a case of Vita's](https://github.com/libsdl-org/SDL/blob/SDL2/src/video/vita/SDL_vitatouch.c#L73-L74) code it's a fully valid device.

Anyway, on SDL3 side I see these device ID codes are valid.

**Comment by slouken** [comment]
Please feel free to submit a PR to fix this, thanks!

**Comment by Wohlstand** [comment]
I'll do, but right now I'm out of home, first off I should test out this on my end. I'll be back when I get my home.

**Comment by Wohlstand** [comment]
Hello!
Sorry for the VERY long delay, I was:
- busy
- ill
- overloaded
- etc.
Now, I going to perform this. Actually very small tweak, just few digits, so long time of wait...

**Comment by Wohlstand** [comment]
@slouken, is possible that change I did will come into the next bugfix update? Or you already going to releae the 2.32.0 very soon? I asking because of milestone where this task is. It's solved right now.
Now going to close it, and then try to resolve the new renderer bug (#10538) that ruined my test of this.

**Comment by slouken** [comment]
Yes, I've merged it to release-2.30.x so it'll be in the next 2.30 release.
