### ISSUE TITLE
Touch inputs can get stuck in pressed state

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#9833]
- Originally reported in https://github.com/ppy/osu/issues/28211
- Related: https://github.com/libsdl-org/SDL/issues/9591

When pressing multiple fingers at the same time, some fingers can get stuck in a pressed state. I have reproduced this on Windows and Android. It's easy to reproduce the issue by just repeatedly pressing and releasing three or more fingers. I've not quite figured out _how_ to press the fingers to cause issues.

To demonstrate the issue I have written a simple program that shows each active SDL_FingerID as a unique colour. The program just observes SDL finger events and draws a rect at the last touch position. When a `SDL_EVENT_FINGER_UP` is received, its rect is no longer drawn.

https://github.com/libsdl-org/SDL/assets/16479013/71a18034-bdee-4dd9-aa07-939e3baa0d07

**Comment by AntTheAlchemist** [comment]
I'm seeing the same. Something also happens with just 2 fingers. I'm seeing finger up events are coming through for the 2nd finger just before the finger down event, then a 2nd finger down event is coming through for the 1st finger.

Is this something that happened recently with the latest SDL3 source? Something's really broken the touch devices with a recent update - I'm also seeing a crash with touch device cleanup on quit.

**Comment by Susko3** [comment]
I don't think this is recent. I have a feeling that the conversion from touch indexes to SDL_TouchID was improper and caused those issues.

It's very concerning that you get a crash. I also got some crashes but I didn't investigate what they were from.

**Comment by AntTheAlchemist** [comment]
The crash #9810 happens on cleanup, and I only know because it's come up on Google Play Console, and made my crashes go beyond bad behaviour. This, and the out of sync touch events also happened at around the same time, 2 months ago. It's something that was committed around 2 months ago that caused both these, I think.
