### ISSUE TITLE
SDL_GetKeyFromScancode does not consider the keyboard layout

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#9835]
According to https://wiki.libsdl.org/SDL3/SDL_GetKeyFromScancode, it should return the key based on the current keyboard layout.

However, when running a simple program calling that function with `SDL_SCANCODE_Q`, the function returns `SDLK_q` even when I'm using an AZERTY keyboard. I would expect it to return `SDLK_a` on AZERTY.

Here's the program I used to test it:

```c
#include <SDL3/SDL.h>

int main()
{
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Window *w = SDL_CreateWindow("SDL", 640, 480, 0);
  SDL_Renderer *r = SDL_CreateRenderer(w, NULL);

  int quit = 0;

  SDL_Log("Press %s", SDL_GetKeyName(SDL_GetKeyFromScancode(SDL_SCANCODE_Q)));

  while (!quit)
  {
    SDL_Delay(10);

    SDL_Event e;
    while (SDL_PollEvent(&e))
    {
      if (e.type == SDL_EVENT_QUIT)
      {
        quit = 1;
        break;
      } else if (e.type == SDL_EVENT_KEY_DOWN && e.key.keysym.scancode == SDL_SCANCODE_Q) {
        SDL_Log("Pressed %c", e.key.keysym.sym);
        quit = 1;
      }
    }

    SDL_RenderPresent(r);
  }

  SDL_DestroyRenderer(r);
  SDL_DestroyWindow(w);
  SDL_Quit();
  return 0;
}
```

With QWERTY, this behaves as expected:
```
INFO: Press Q
INFO: Pressed q
```
I pressed the Q key.

With AZERTY:
```
INFO: Press Q
INFO: Pressed a
```
I pressed the A key (in AZERTY labeling, so on top left). If I press the AZERTY 'Q' key, nothing happens, as expected.

I would expect the first line to read `INFO: Press A` instead. The second line, which prints the expected scancode, leads me to believe the issue is indeed with SDL_GetKeyFromScancode.

Just in case: I did make sure to have the keyboard set to AZERTY before launching the program :)

**Comment by AntTheAlchemist** [comment]
`.sym` isn't the scancode, so they will differ because the system remaps the keys?

```
    SDL_Scancode scancode;      /**< SDL physical key code - see SDL_Scancode for details */
    SDL_Keycode sym;            /**< SDL virtual key code - see SDL_Keycode for details */
```

**Comment by Semphriss** [comment]
> `.sym` isn't the scancode, so they will differ because the system remaps the keys?
> 
> ```
>     SDL_Scancode scancode;      /**< SDL physical key code - see SDL_Scancode for details */
>     SDL_Keycode sym;            /**< SDL virtual key code - see SDL_Keycode for details */
> ```

That's the thing, both of them are printing keycodes rather than scancodes, so I expect both of them to give results corresponding to the current keyboard layout. The keysym is correct, it's the SDL_GetKeyFromScancode that returns an unexpected result.

> What happens if you print SDL_GetKeyName(SDL_GetKeyFromScancode(SDL_SCANCODE_Q)) when you receive the event? Does it still print Q or has it corrected itself?

I tried copy-pasting the first SDL_Log within the event handler, and it seems to have corrected itself indeed when reaching that point.

I also pasted it in the main loop, and I noticed that it remains wrong for a few loops (the exact number of loops varies), then it automatically corrects itself after a while. It behaves as if the keyboard layout was detected asynchronously.

I'm on Ubuntu 22.04, if that helps.

**Comment by Kontrabant** [comment]
The keymap is configured with locale data after running the message pump to process OS events that set the layout, so your first call is looking up the key in the default ANSI table.

Once you pump the events and the keyboard locale event is processed to set the keymap, it works as expected.

**Comment by Semphriss** [comment]
I did try adding `SDL_PumpEvents();` (and afterwards, `SDL_Delay(10);` before PumpEvents) before the first call to SDL_Log, but the same behavior happens; it takes several main loop iterations, each of which pass through the inner event loop, which polls events to exhaustion each time. I tried again, and it took 7 full rendering loops before the keyboard layout was properly detected.

<details>
<summary>My updated code, with results</summary>

```c
#include <SDL3/SDL.h>

int main()
{
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Window *w = SDL_CreateWindow("SDL", 640, 480, 0);
  SDL_Renderer *r = SDL_CreateRenderer(w, NULL);

  int quit = 0;

  // Make sure all events are pumped, and give it 10ms to collect events
  SDL_Delay(10);
  SDL_PumpEvents();
  SDL_Log("BEGIN: Scancode Q == Keycode %s", SDL_GetKeyName(SDL_GetKeyFromScancode(SDL_SCANCODE_Q)));

  while (!quit)
  {
    SDL_Delay(1);

    SDL_Event e;
    while (SDL_PollEvent(&e))
    {
      if (e.type == SDL_EVENT_QUIT)
      {
        quit = 1;
        break;
      } else if (e.type == SDL_EVENT_KEY_DOWN && e.key.keysym.scancode == SDL_SCANCODE_Q) {
        SDL_Log("EVENT: Scancode Q == Keycode %s", SDL_GetKeyName(SDL_GetKeyFromScancode(SDL_SCANCODE_Q)));
        SDL_Log("Pressed that scancode, event contains sym (keycode): %c", e.key.keysym.sym);
        quit = 1;
      }
    }

    SDL_Log("LOOP: Scancode Q == Keycode %s", SDL_GetKeyName(SDL_GetKeyFromScancode(SDL_SCANCODE_Q)));
    SDL_RenderPresent(r);
  }

  SDL_DestroyRenderer(r);
  SDL_DestroyWindow(w);
  SDL_Quit();
  return 0;
}
```

Result:
```
$ ./a.out 
INFO: BEGIN: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode Q
INFO: LOOP: Scancode Q == Keycode A
INFO: LOOP: Scancode Q == Keycode A
INFO: LOOP: Scancode Q == Keycode A
INFO: LOOP: Scancode Q == Keycode A
INFO: LOOP: Scancode Q == Keycode A
INFO: LOOP: Scancode Q == Keycode A
INFO: LOOP: Scancode Q == Keycode A
INFO: LOOP: Scancode Q == Keycode A
...
```
</details>

**Comment by Sackzement** [comment]
Found a workaround:
Just set the `magic_number` to how many times the keycode was NOT correctly converted:
```c
#include <SDL3/SDL.h>

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *w = SDL_CreateWindow("SDL", 640, 480, 0);
    SDL_Renderer *r = SDL_CreateRenderer(w, NULL);

    int magic_number = 2; // <==================================================
    for (; magic_number > 0; --magic_number) {
        SDL_RenderPresent(r);
    }

    int quit = 0;
    while (!quit) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_EVENT_QUIT) {
                quit = 1;
            } else if (e.type == SDL_EVENT_KEYMAP_CHANGED) {
                SDL_Log("SDL_EVENT_KEYMAP_CHANGED");
            }
        }
        SDL_Log("Finished event polling");

        SDL_Keycode keycode = SDL_GetKeyFromScancode(SDL_SCANCODE_Q);
        const char *keyname = SDL_GetKeyName(keycode);
        SDL_Log("LOOP: Scancode: Q, Keycode: %c, KeyName: %s", keycode, keyname);
        SDL_RenderPresent(r);

        if (keycode == SDLK_a) {
            quit = 1;
        }
    }

    SDL_DestroyRenderer(r);
    SDL_DestroyWindow(w);
    SDL_Quit();
    return 0;
}
```
No idea why... but it works xD

**Comment by Semphriss** [comment]
I did think about doing something like this initially :)

The problem is that the number of loops varies between each execution. I tried again a few times and it took 7, 3, 7, 3, 3 and 4 loops before fixing itself. I also note that it varies by the duration of SDL_Delay if I set it to 0, 1 or 10, so I think it's not a specific function being called or not that's the issue, but rather some asynchronous task that takes around 3-7ms to complete before actually initializing the keyboard layout.

On qn unrelqted note; it.s qnnoying to szitch betzeen keyboqrds qll the ti,e:

**Comment by Sackzement** [comment]
> On qn unrelqted note; it.s qnnoying to szitch betzeen keyboqrds qll the ti,e:

xD

Somehow, on my system(Wayland), a delay didn't matter at all. Even with a delay of 1000ms before and inside the loop, it always detected a keymap change after exactly two loops.
Only when I rearranged the function calls, it made a difference. After some reordering I noticed that the only function, that actually mattered, was the `SDL_RenderPresent()` function. It had to be called twice before the event polling loop detected the keymap change.
Just calling it twice before entering the main loop solved the issue.

Seems like it varies, when and why exactly a keymap change is detected.

**Comment by Kontrabant** [comment]
>I also note that it varies by the duration of SDL_Delay if I set it to 0, 1 or 10, so I think it's not a specific function being called or not that's the issue, but rather some asynchronous task that takes around 3-7ms to complete before actually initializing the keyboard layout.

Correct, SDL can't update the keymap until the OS sends the event notifying of the layout change, and SDL has no control over when that happens.

This can even change depending on which window has focus, as many desktops support setting the keyboard layout per-window, so the only thing to do is wait for the keymap event to appear before doing anything that requires it.

Closing as this isn't an SDL bug, and there's nothing that SDL can do to make the OS send the underlying keymap event faster.

**Comment by slouken** [comment]
SDL_GetKeyFromScancode() returns information based on the key map provided by the system, and the event SDL_EVENT_KEYMAP_CHANGED is sent when this changes. It can change for many reasons, and if your application needs up to date information, you should handle that event and re-query anything you need. You are not intended to cache the information for exactly this reason.

**Comment by Semphriss** [comment]
Would it be reasonable to wait for the initial keyboard layout setup from within SDL_Init? I did not intuitively guess that the keyboard layout could take a substantial delay before being detected, and I'm using the keyboard early enough in the process that it hasn't been yet loaded when it needs that information. Since SDL_Init already takes a few milliseconds to complete with just SDL_INIT_VIDEO, the impact of waiting a bit longer shouldn't be too important.

If it's not possible/reasonable/desirable, would it be good to update the documentation to say that the keymap-sensitive functions should not be used before the first SDL_EVENT_KEYMAP_CHANGED event is received?

**Comment by Kontrabant** [comment]
- Waiting in SDL_Init() won't work, because the layout might not be reported until a window is created.
- The keyboard might not have a layout at all, as is the case with some virtual keyboards, so you might be waiting forever.

**Comment by Semphriss** [comment]
> * Waiting in SDL_Init() won't work, because the layout might not be reported until a window is created.
> * The keyboard might not have a layout at all, as is the case with some virtual keyboards, so you might be waiting forever for an event that never arrives.

How can I determine when it is safe to call SDL_GetKeyFromScancode and related functions? Can I use it if my app does not have a window?

**Comment by slouken** [comment]
Call them anytime, just be aware that you can't cache the return values. You need to look up keys when you're using them if you don't handle the keymap event.

**Comment by Kontrabant** [comment]
> Can I use it if my app does not have a window?

Keyboard input without a window isn't something you can rely on in general, as some platforms only deliver key events to (focused) windows.

**Comment by Semphriss** [comment]
> Call them anytime, just be aware that you can't cache the return values.

My use case requires displaying a message at the beginning of the program in the form of "Press [key] to lorem ipsum", and I can't retroactively change the contents of the message after it is sent. I'm not caching the values, but I've consumed them "too fast", and I'm not sure how to work around this without opening new problems.

It's probably a narrow enough use case that it may not be worth fixing, but lacking a fix, would it be possible to add an informative line on the relevant wiki pages?
