### ISSUE TITLE
`SDL_ConvertEventToRenderCoordinates` doesn't convert pen event coordinates

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#9839]
The event types are simply not handled in the function. I've not checked if there are any other positional events that are also not converted.

https://github.com/libsdl-org/SDL/blob/2cf32b0e0a55e3ca3cc52cd01901a06dca722d9b/src/render/SDL_render.c#L2700-L2791

**Comment by slouken** [comment]
No, that's just an oversight with the new pen events. Feel free to submit a PR to fix this.

**Comment by Susko3** [comment]
I won't be submitting a PR because I don't know how pen events are supposed to work. I also don't have a tablet and a linux dev environment to test on.

**Comment by icculus** [comment]
This was fixed in 5136b306524f6710ab9cb1e4b51b9db41716ee7b.
