### ISSUE TITLE
SDL_CreateThreadWithStackSpace should probably be a generic SDL_Properties thing.

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9844]
We have SDL_CreateThread and SDL_CreateThreadWithStackSpace, but that second one should probably just be SDL_CreateThreadWithProperties, of which stack space is only one property.

Other properties (which can be added later in 3.x, once the generic interface is available in 3.2.0) could be things like thread affinity, detaching the thread at startup, thread priority at startup, etc.

**Comment by slouken** [comment]
I like it!

**Comment by icculus** [comment]
This is done, merged with #9843.
