### ISSUE TITLE
SDL3: Do we need two duplicate ways to get Renderer name?

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9845]
`max_texture_width` & `max_texture_height` has just been removed from `SDL_RendererInfo` because we have `SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER`.

But `SDL_RendererInfo::name` remains even though there is `SDL_PROP_RENDERER_NAME_STRING`.

Do we need to consistently clean duplicated info like this? It could cause confusion having multiple sources for the same information, but no uniformity for where to access it.

**Comment by slouken** [comment]
Yes, the info needs the name and there's no harm in having the property too.
