### ISSUE TITLE
Remove the `SDL_RendererInfo` struct and use the properties API instead

### ISSUE THREAD

**Issue by lumPalette** [libsdl-org/SDL#9851]
Since `SDL_GetRendererProperties()` exists now, it would be nice to have just one API to query renderer information.

I suggest removing the `SDL_RendererInfo` struct and the `SDL_GetRendererInfo()` function and instead add `SDL_PROP_RENDERER_TEXTURE_FORMAT_COUNT_NUMBER` and `SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER` as properties that can be queried using `SDL_GetRendererProperties()`.

**Comment by slouken** [comment]
Thanks for the suggestion! I'm also going to add SDL_GetRendererName()

**Comment by AntTheAlchemist** [comment]
I tried to suggest this yesterday #9845, but got shot down - I probably didn't word it very well. 

Not just rendering info, but other areas need to have a uniform API. There's currently no rhyme behind helper functions like `SDL_GetRendererInfo()` & proposed `SDL_GetRendererName()` or using properties. It's a bit of a random mix and awkward to know which method to use and why some info is in properties and other info from direct functions.

**Comment by lumPalette** [comment]
i'm glad my suggestion was useful! :)

**Comment by icculus** [comment]
> I probably didn't word it very well.

Or maybe you did, and you just had to wait for the idea to soak fully into our brains for an extra day.  :)
