### ISSUE TITLE
Cannot build SDL3.dll on Visual Studio with SDL_LIBC=OFF

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#9858]
Since #9843, when configuring SDL with `-DSDL_LIBC=OFF`, linking `SDL3.dll` fails due to missing `_beginthreadex` and `_endthreadex` symbols.

Full error log:
```
SDL_timer.c.obj : error LNK2019: unresolved external symbol _beginthreadex referenced in function SDL_InitTimers
SDL_hidapi_rumble.c.obj : error LNK2001: unresolved external symbol _beginthreadex
SDL_windowsdialog.c.obj : error LNK2001: unresolved external symbol _beginthreadex
SDL_audio.c.obj : error LNK2001: unresolved external symbol _beginthreadex
SDL_camera.c.obj : error LNK2001: unresolved external symbol _beginthreadex
SDL_hidapi.c.obj : error LNK2001: unresolved external symbol _beginthreadex
SDL_thread.c.obj : error LNK2001: unresolved external symbol _beginthreadex
SDL_timer.c.obj : error LNK2001: unresolved external symbol _endthreadex
SDL_hidapi_rumble.c.obj : error LNK2001: unresolved external symbol _endthreadex
SDL_windowsdialog.c.obj : error LNK2001: unresolved external symbol _endthreadex
SDL_audio.c.obj : error LNK2001: unresolved external symbol _endthreadex
SDL_camera.c.obj : error LNK2001: unresolved external symbol _endthreadex
SDL_hidapi.c.obj : error LNK2001: unresolved external symbol _endthreadex
SDL_thread.c.obj : error LNK2001: unresolved external symbol _endthreadex
SDL3.dll : fatal error LNK1120: 2 unresolved externals
```

**Comment by icculus** [comment]
So this is literally the calls to SDL_CreateThread inside of SDL.

I'm thinking the cleanest thing here is to add something in SDL_internal.h that, if `!defined(HAVE_LIBC)` will define SDL_BeginThreadFunction to NULL somewhere before including SDL.h.

That way it'll do the right thing for LIBC and non-LIBC builds of SDL, and it's all handled in one place.

**Comment by icculus** [comment]
>  ```
> /__w/SDL/SDL/test/../src/SDL_internal.h:270:48: error: missing terminating ' character [-Werror]
>  270 | // gets included, so SDL_CreateThread calls won't try to reference the
> ```

...the Vita compiler doesn't like `//` comments...?

**Comment by icculus** [comment]
okay, what the heck

**Comment by icculus** [comment]
I believe this is resolved now. Let me know if it isn't!

**Comment by madebr** [comment]
It is resolved! Thank you!
