### ISSUE TITLE
SDL_ShowOpenFileDialog paths containing file:// (URI)

### ISSUE THREAD

**Issue by JoelLinn** [libsdl-org/SDL#9863]
`SDL_ShowOpenFileDialog` on Linux will output file paths that start with `file://` in URI format. I understand this is sometimes expected (i.e. Androids `content://`) but it gives further issues when the paths will be forwarded to other code, for example C++ `std::filesystem::path` or other third-party libraries that expect file paths.

This should either be clarified in the docs or changed. At minimum there should be a way to retrieve the "native" path that other libraries can work with.

**Comment by slouken** [comment]
We should strip file:// from returned paths. @Semphriss, do you want to take this one?

**Comment by JoelLinn** [comment]
Thanks, your efforts are very much appreciated ❤️
