### ISSUE TITLE
Three minor typos.

### ISSUE THREAD

**Issue by Nakhr11n** [libsdl-org/SDL#9874]
Pull request #9727 (Commit: 93a0db5) has three minor typos on lines `118, 174 and 228` of `include/SDL3/SDL_dialog.h`.

>  \* requires and event-handling loop. Apps that do not use SDL to handle events
----------^^^

_and_ should be _an_

**Comment by slouken** [comment]
This is fixed in daf500939551c93968bea7f794800ea16870c74f, thanks!
