### ISSUE TITLE
Dialog API: Support MIME types?

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#9881]
I've been reading the [JS File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API) for Emscripten support, and I noticed it uses MIME types. The potential fallbacks using `<input type-"file" />` also work with MIME. I believe the same may apply for some other platforms. Would it be worth checking to add a place for them in file filters?

**Comment by icculus** [comment]
I don't have an opinion on this at the moment, but I'm tossing this into 3.0 ABI milestone so we don't forget to look at this.

**Comment by slouken** [comment]
Since this isn't generally supported across platforms, let's not do this for now. We can add it later if we decide it's important.
