### ISSUE TITLE
Cannot drop file on testdropfile, when running in the browser

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#9882]
When running testdropfile in Firefox/Chromium, no SDL drop events are generated.

Since 78e25d4994c4baa5213729506af3c718cc00d60a, testdropfile runs in the browser.

**Comment by slouken** [comment]
We are scoping work for the SDL 3.2.0 release, so please let us know if this is a showstopper for you.

**Comment by madebr** [comment]
I've created [a WIP patch here](https://github.com/madebr/SDL/tree/emscripten-drag-n-drop) that tracks the mouse pointer when dropping a file or text in `testdropfile`.

But the browsers are complaining about "memory access out of bounds" [here](https://github.com/libsdl-org/SDL/blob/2e70944c448c327e25501a9034aa5db461f596d0/src/events/SDL_dropevents.c#L39).
I noticed the event handlers are registered twice, with the second time an invalid `SDL_WindowData` is passed.

**Comment by madebr** [comment]
I got it working, but I have an API problem/question.
Dropping strings (=text/plain) works without issue.
Dropping files behaves slightly different then desktop.

On desktop, using the filename you can simply use `fopen` to read the file.
On the web, this is not possible. The file should be read while processing the event, and the file data passed through an event.

In my WIP branch, the file content memory is passed as an extra pointer and leaked (should be fixed).

What API do you prefer? Do you have alternatives?
- Write the file contents to the Emscripten FS. An advantage of this is that normal libc functions will work. A disadvantage is that dropped files are never freed.
- Add a `SDL_IOStream *stream;` member to the `SDL_DropEvent` event. To take ownership of the stream object, users should set a property (e.g. `SDL_SetBooleanProperty(SDL_GetIOProperties(event.props.stream), SDL_PROP_IOSTREAM_EVENT_FREE, false);`). If this is not done, the object is freed on the next invocation of `SDL_PollEvent`.

The `SDL_IOStream` approach looks nice to me. Tough, it could benefit from an asynchronous API

**Comment by icculus** [comment]
> Write the file contents to the Emscripten FS. An advantage of this is that normal libc functions will work. A disadvantage is that dropped files are never freed.

I'd be inclined to say write it to /.sdl-dragdrop.bin or whatever, and then delete the file after a few animation frames; if they didn't handle it by then, it was an app bug and/or they didn't intend to handle it.

The downside is a massive file will cause allocation problems, chewing up memory through MEMFS, but this might be true in any case...?

**Comment by madebr** [comment]
I did that, but I don't know where to free the files.
The current implementation stores all files in `/tmp/dragrop/<ID>/<filename>` with an incrementing counter, and filename the name of the dropped files.

I created https://github.com/libsdl-org/SDL/pull/11526 so you have code to try and comment on.
