### ISSUE TITLE
Add macros for SDL main callback return codes

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#9883]
When using SDL main callbacks, most functions need to return *magic* return codes: -1, 0, or 1.

Would it be useful to define macros for these? As a form of self-documentation.

e.g.

```c
#define SDL_MAIN_CALLBACK_EXIT_FAILURE   (-1)
#define SDL_MAIN_CALLBACK_EXIT_SUCCESS   ( 1)
#define SDL_MAIN_CALLBACK_CONTINUE       ( 0)
```

**Comment by icculus** [comment]
I think it's wordy, but I'm not against it existing, in the same way that _technically_ one can return EXIT_SUCCESS from `main` but everyone returns 0.

**Comment by icculus** [comment]
Okay, I added these. It's not my thing, but I _can_ see the value in them existing.

I didn't update any of the test programs to use them. I don't mind if you do that, though!
