### ISSUE TITLE
MacOS Xcode CPP #include "SDL2/SDL2.h" File Not Found

### ISSUE THREAD

**Issue by Liam-Hughes-Ruddell** [libsdl-org/SDL#9884]
Hi I am trying to use SDL2 in my CPP project in Xcode but it says this:
/Users/USER/Desktop/XCodeProjects/tests/cmdCPPtest1/test/test/main.cpp:9:10 'SDL2/SDL2.h' file not found

I am new to CPP and I am trying it out and want to try SDL2 but I get an error

Here is where I am importing SDL2 but get the error
`#include "SDL2/SDL2.h"`

I even imported the SDL Framework but still gives me an error

**Comment by yannb2159** [comment]
@Liam-Hughes-Ruddell It's SDL/SDL2.h and not SDL2/SDL2.h ! :)

Hope it helps.
