### ISSUE TITLE
Documentation warnings

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9890]
In file SDL_thread.h: function SDL_CreateThreadRuntime() has 0 '\param' but expected 5
  In file SDL_thread.h: function SDL_CreateThreadRuntime() missing '\param fn'
  In file SDL_thread.h: function SDL_CreateThreadRuntime() missing '\param name'
  In file SDL_thread.h: function SDL_CreateThreadRuntime() missing '\param data'
  In file SDL_thread.h: function SDL_CreateThreadRuntime() missing '\param pfnBeginThread'
  In file SDL_thread.h: function SDL_CreateThreadRuntime() missing '\param pfnEndThread'
  In file SDL_thread.h: function SDL_CreateThreadWithPropertiesRuntime() has 0 '\param' but expected 3
  In file SDL_thread.h: function SDL_CreateThreadWithPropertiesRuntime() missing '\param props'
  In file SDL_thread.h: function SDL_CreateThreadWithPropertiesRuntime() missing '\param pfnBeginThread'
  In file SDL_thread.h: function SDL_CreateThreadWithPropertiesRuntime() missing '\param pfnEndThread'
  In file SDL_thread.h: function SDL_CreateThreadRuntime() has 0 '\returns' but expected 1
  In file SDL_thread.h: function SDL_CreateThreadWithPropertiesRuntime() has 0 '\returns' but expected 1
  In file SDL_thread.h: function SDL_CreateThreadRuntime() has 0 '\since' but expected 1
  In file SDL_thread.h: function SDL_CreateThreadWithPropertiesRuntime() has 0 '\since' but expected

**Comment by slouken** [comment]
Also, running gendynapi will generate entries for CreateThread and CreateThreadWithProperties. It probably needs to be updated to handle the wiki ifdefs in the headers.

**Comment by icculus** [comment]
Ugh, I'll do that now.
