### ISSUE TITLE
interval_numerator/denominator of SDL_CameraSpec is opposite for Windows/MediaFoundation implementation

### ISSUE THREAD

**Issue by joey-cyt** [libsdl-org/SDL#9896]
In our test, the behavior of interval_numerator/denominator of SDL_CameraSpec match to the comment in code on Mac:
```
    int interval_numerator;     /**< Frame rate numerator ((dom / num) == fps, (num / dom) == duration) */
    int interval_denominator;   /**< Frame rate demoninator ((dom / num) == fps, (num / dom) == duration) */
```

However, the meanings of the two variables are swapped for Windows/MediaFoundation implementation. The code in SDL src/camera/mediafoundation/SDL_camera_mediafoundation.c, L573:
```
ret = IMFMediaType_SetUINT64(mediatype, &SDL_MF_MT_FRAME_RATE, (((UINT64)spec->interval_numerator) << 32) | ((UINT64)spec->interval_denominator));
```

From MSDN, https://learn.microsoft.com/en-us/windows/win32/medfound/mf-mt-frame-rate-attribute
> The frame rate is expressed as a ratio. The upper 32 bits of the attribute value contain the numerator and the lower 32 bits contain the denominator. For example, if the frame rate is 30 frames per second (fps), the ratio is 30/1. If the frame rate is 29.97 fps, the ratio is 30,000/1001.

**Comment by joey-cyt** [comment]
GatherCameraSpecs() has the same issue:
```
ret = IMFMediaType_GetUINT64(mediatype, &SDL_MF_MT_FRAME_RATE, &val);
interval_numerator = (UINT32)(val >> 32);
interval_denominator = (UINT32)val;
```

**Comment by icculus** [comment]
> The upper 32 bits of the attribute value contain the numerator

So `(numerator << 32)` would put the numerator in the upper 32 bits for SetUINT64 and `(numerator >> 32)` would extract the top 32 bits after GetUINT64.

So this appears to be correct, unless I'm misunderstanding the problem...?

**Comment by joey-cyt** [comment]
The numerator/denominator in SDL_CameraSpec are for frame interval/duration; In MediaFoundation they are for frame rate (FPS).
Thus, SDL_CameraSpec::interval_numerator should be MediaFoundation's denominator, and SDL_CameraSpec::interval_denominator should be MediaFoundation's numerator.
To achieve correct frame rate on both MacOS and Windows, our code has to be written like this:
        mSpec = 
        {
            .format = SDL_PIXELFORMAT_YUY2,
            .width = 1280,
            .height = 1024,
            // to-do: check on Linux
#ifdef __APPLE__
            .interval_numerator = 1,
            .interval_denominator = 60
#else
            .interval_numerator = 60,
            .interval_denominator = 1
#endif
        };

**Comment by slouken** [comment]
This has been a source of confusion for me as well. Should we change the SDL API to be frame rate rather than interval?

**Comment by joey-cyt** [comment]
I'd prefer to use frame rate rather than interval, frame rate is more widely used.

**Comment by icculus** [comment]
Either is fine with me as long as it's consistent. I think the Video4Linux code is interval instead of framerate, so the entire thing was probably inherited from there, but we can do whatever we like.

**Comment by slouken** [comment]
Let's use framerate, since that's a more commonly used concept in games and SDL.
