### ISSUE TITLE
The wait cursors aren't animated on Wayland

### ISSUE THREAD

**Issue by zturtleman** [libsdl-org/SDL#9897]
Using SDL 3 on GNOME/Wayland, the cursors for wait and small wait are not animated. Run `./testcustomcursor` and click to cycle to the two wait cursors. They are animated when using XWayland (`SDL_VIDEO_DRIVER=x11 ./testcustomcursor`).

I don't know of software using these cursors with SDL. I'm just noting a Wayland difference compared to X11.

**Comment by Kontrabant** [comment]
Animated system cursors have never been supported in the non-cursor-shape protocol path. Shouldn't be too much work to implement though.
