### ISSUE TITLE
Dialog xdg portals broken

### ISSUE THREAD

**Issue by JoelLinn** [libsdl-org/SDL#9899]
Unfortunately after this commit, xdg portal file dialogs are completely broken for me
https://github.com/libsdl-org/SDL/commit/3acca27e9576200f6c26bbbc55662179f04a2115#diff-e5622cd97ddd4c631ff84ec042ba52d0237876475495354a2f867ac1aef3d882R244

It looks like there was a mistake in the `strncmp`
```diff
- if (SDL_strncmp(uri, "file://", SDL_strlen("file://"))) {
+ if (SDL_strncmp(uri, "file://", SDL_strlen("file://")) == 0) {
```

**Comment by slouken** [comment]
Fixed, thanks!
