### ISSUE TITLE
[Android] Hardcoding Gamepad hats to buttons [b11; b14] makes no sense

### ISSUE THREAD

**Issue by darksylinc** [libsdl-org/SDL#9916]
**Note:** Affects SDL2 and SDL3.

**Note 2:** I opened a sister ticket to this issue in https://github.com/mdqinc/SDL_GameControllerDB/issues/760

> [!IMPORTANT] 
> The following is a copy paste from its [sister ticket](https://github.com/mdqinc/SDL_GameControllerDB/issues/760) to provide context.

Hi!

I'm adapting SDL2's gamepad code to our own code so that we can use SDL_GameControllerDB directly (i.e. for various technical reasons we're not using SDL2).

We bought a XBox controller and noticed the DPad wasn't working. After some debugging, I nailed it to wrong mapping. I thought "Ok, perhaps my implementation is wrong and I missed something".

So then I proceed to compare with vanilla SDL2 (2.30.0) demo. And lo and behold, the gamepad's dpad button wasn't working on SDL2 either.

The entry in question is this one:

```
050000005e040000130b0000ffff3f00,Xbox Series Controller,a:b0,b:b1,back:b15,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,platform:Android,
```

On Android, SDL2 [hardcodes all hats](https://github.com/libsdl-org/SDL/blob/3ee20388c574096bff412041745a5fd8086d6afc/src/joystick/android/SDL_sysjoystick.c#L284-L296) (dpad) to emit buttons b11, b12, b13, b14. I don't know SDL2's rationale behind this decision, but it is what it is.

It seems like originally SDL2 would actually map hats correctly, but [this was changed](https://github.com/libsdl-org/SDL/commit/9e651b691562516128dfa27120767c542b084e64) in March 2018.

Thus any Android entry of the type "hX.Y" (i.e. like h0.4) is simply wrong for any modern SDL2 build.

> [!IMPORTANT] 
> Copy paste for context ends here. For more info go read the [sister ticket](https://github.com/mdqinc/SDL_GameControllerDB/issues/760).

I'm opening a ticket in both places because one of them must be wrong:

1. Either SDL2/3 is wrong.
2. Or the database is wrong.

However what looks suspicious is that [the change in 2018](https://github.com/libsdl-org/SDL/commit/9e651b691562516128dfa27120767c542b084e64) does not mention this change at all. All it says is:

> Try to dynamically create a default Android game controller mapping based on the buttons and axes on the controller.
> Include the controller USB VID/PID in the GUID where possible, as we do on other platforms.

If I take a guess, it appears the original commit tried to fix something broken on Android, and attempted to bypass mapping and issue raw `SDL_CONTROLLER_BUTTON_DPAD_*` events. **But that is not what is happening**.

The buttons do get remapped. Thus in order to work properly, button 11 must be mapped to button 11 (and button 14 must be mapped to button 14).

**This will work fine as long as there is no actual button 11 that needs to mapped to something else.** Therefore this looks like an SDL2/3 bug rather than a db bug.

Now the question is how to handle the fix. Because fixing this bug will break more recent DB entries (but this is very easily fixable!).

Although judging from the amount of Android entires using broken hat mappings; it looks like half of them haven't been tested in a long time.

An alternate solution would be to actually issue raw `SDL_CONTROLLER_BUTTON_DPAD_*` events, and bypass the database remapping entirely.

**Comment by AntTheAlchemist** [comment]
The D-pad / hat currently works for me on Android / Windows on different controllers and versions of Android, so is the issue with your adaption's assumption of how the DB should work?

**Comment by slouken** [comment]
Any Android mapping that uses a hat won't work, and the official mappings don't include any:
https://github.com/libsdl-org/SDL/blob/7b14fcb4d9224f79629853d86affd46f9014b43b/src/joystick/SDL_gamepad_db.h#L786-L837

The reason SDL's button mapping works is that it looks at the keycode of the controller button and maps that into a standard button space, and button 11 will be remapped into 20 + 11:
https://github.com/libsdl-org/SDL/blob/7b14fcb4d9224f79629853d86affd46f9014b43b/src/joystick/android/SDL_sysjoystick.c#L63-L67

**Comment by slouken** [comment]
FYI, the reason the hat is treated as buttons is because some gamepads represent the dpad as a hat and some as buttons, and this lets SDL handle both the same way, as well as include the D-pad capabilities in the controller GUID.
