### ISSUE TITLE
Trouble with X11_SetWindowMouseGrab()

### ISSUE THREAD

**Issue by Kharzette** [libsdl-org/SDL#9917]
I updated my SDL submodule today and started getting a freeze when calling SDL_SetRelativeMouseMode() on x11/vulkan.  I use this for mouselook while right mouse is held.  Since it is an input thing I debugged it via prints like a savage.

That's when I noticed the stall was 5 seconds, and if the full stall duration is reached, relative mode behaved normally again.

I eventually tracked it down to the loop in X11_SetWindowMouseGrab() line 1844.  For me the X11_XGrabPointer() call always returns AlreadyGrabbed when in this stall.  I stuck a print in X11_CaptureMouse() to see if that might have been grabbing the mouse, but the print never hits.

I noticed there's 2 ungrabs on program start, then one more once I get rendering going, but I don't see any grabs from within SDL happening that would cause X11 to think the pointer is already grabbed.

Once broken_pointer_grab is set everything seems to normally work.  I don't see any odd behaviour.  I could just set that to true manually and work around this, but curious if this is a bug or I'm doing something wrong elsewhere?

I'm using arch with LXQt and Openbox as my window manager.

I wish I knew X11 enough to write a program to test X11_XGrabPointer() in the simplest possible way (to see if it is a bug in LXQt or something) but I've never used X11 directly.

Any ideas?

**Comment by Kontrabant** [comment]
What desktop are you running, and is this real X11 or XWayland? XGrabPointer is a system call, so if it is failing, there's probably something going on at a deeper level.

**Comment by Kharzette** [comment]
Desktop?  I think that would be LXQt.

**Comment by Kharzette** [comment]
Ok I decided to test it with raw X11.  It's not so bad!  I stole a little hello world program and put in a hold-down-mouse event to grab and ungrab.

https://github.com/Kharzette/X11Test/blob/main/X11Test.c

This works as expected, grabbing when a button is held and ungrabbing upon release.

I'll try a super simple SDL version of the same thing and see how it goes.

**Comment by Kharzette** [comment]
The simple SDL test works fine too!

https://github.com/Kharzette/X11Test/blob/main/SDLTest.c

I'll have to dig in my other libraries.  Faudio/dxvk-native etc etc.

**Comment by Kharzette** [comment]
dxvk-native is the culprit!  👮🏻‍♀️
