### ISSUE TITLE
Unexpected `SDL_BLENDMODE` differences in `SDL_CreateTextureFromSurface()` and `SDL_CreateTexture()`

### ISSUE THREAD

**Issue by Green-Sky** [libsdl-org/SDL#9941]
When creating a surface using `SDL_CreateSurfaceFrom()` with `SDL_PIXELFORMAT_RGBA32`, blend mode is set to `SDL_BLENDMODE_BLEND`. `SDL_CreateTextureFromSurface()` then goes in and copies the blend mode from the surface to the texture. Due to limitations on setting properties (static/streaming) I went with `SDL_CreateTexture()`, which obv does not copy the blend mode.

This whole behavoir difference is a bit unintuitive, and I propose to **make the behavoir the same for surfaces and textures**.

edit: just found out its actually worse, the blend mode is always set to BLEND if the source surface has alpha, and copied otherwise:
https://github.com/libsdl-org/SDL/blob/fd2b9c060291af8ba3388f18b3b0000e81e41643/src/render/SDL_render.c#L1619-L1625

**Comment by 1bsyl** [comment]
there was this PR related: https://github.com/libsdl-org/SDL/pull/4690

**Comment by slouken** [comment]
Fixed, thanks!
