### ISSUE TITLE
Suggestion: Improve preprocessor logic for SDL_AUDIO_DISABLED, SDL_CAMERA_DISABLED, etc

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9947]
Can we extend the reach of SDL_AUDIO_DISABLED, SDL_CAMERA_DISABLED, etc? Can we extend their influence to the various build_config files? This will make it much easier to exclude unused code from final binaries when building with Visual Studio's project, or by adding -D macros to Android projects. 

For example, wrapping the driver macros up like this (in SDL_build_config_windows.h):

```
/* Enable the camera driver */
#ifndef SDL_CAMERA_DISABLED
#define SDL_CAMERA_DRIVER_MEDIAFOUNDATION 1
#define SDL_CAMERA_DRIVER_DUMMY 1
#endif
```

I've tried it out on a few areas and it works well.

**Comment by slouken** [comment]
Sure, feel free to create a PR

**Comment by AntTheAlchemist** [comment]
> Sure, feel free to create a PR

I'll give it a bash. Couple of questions first though, as I don't understand how the drivers and dummy driver thing works: Is everything expected to have a dummy driver for it to work? Even when disabled? Does what I proposed make sense; to filter out the driver #defines? Would that be enough (that alone seems to make a fair bit of difference), or could the #ifndefs go deeper? Do you think it's worth the work, or too complex?

**Comment by slouken** [comment]
Honestly, most of the platform specific code is tiny enough that this won't make much savings. The dummy implementation is almost always what will need to be used when the subsystem is disabled. We've been moving away from making code disabled, as it inevitably results in bug reports who don't realize the system SDL maintainer did something silly (like Arch disabling SDL threads at one point)

However, if it makes you happy, go for it! :)

**Comment by AntTheAlchemist** [comment]
This should make a lot of Android devs, end-users, and Google Play happy :). APK size is important. With this patch (and SDL_LEAN_AND_MEAN) you can shave up to half a MB from each libSDL3.so file.
