### ISSUE TITLE
Please increment version after a release

### ISSUE THREAD

**Issue by akallabeth** [libsdl-org/SDL#9952]
current latest prerelease tag `prerelease-3.1.2` and `main` share the same version `3.1.2`
since there have been breaking changes inbetween there is currently no way to have something compile for `prerelease-3.1.2` and `main`

please increment the release version after a release so that it is possible to distinguish a release from current development versions.

**Comment by slouken** [comment]
The prerelease is not an actual release, just a preview. You should not be relying on SDL3 version numbers yet, as you noted the API/ABI is not frozen yet. If you are working on a project in progress, you should target the latest main SDL code.
