### ISSUE TITLE
DuelSence(PS5) controller becomes unresponsive to other apps when SDL library accessed.

### ISSUE THREAD

**Issue by harley-codes** [libsdl-org/SDL#9954]
I have witnessed this with three different applications. DuckStation, PCSXE2, and Ryujinx. 

After running either software, other applications will stop seeing button presses on the controller. 
This includes the controller view from the windows control panel.

**Comment by AntTheAlchemist** [comment]
Is this on Windows? Are you using the following hint?

`SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE, "1");`

Enabling extended input will break DirectInput for applications that don't use SDL.

**Comment by harley-codes** [comment]
This is for Windows 11. I removed the last paragraph related to versioning. I got that part mixed up with a separate issue I am facing (slow DB load times).

So I am not actually coding anything with SDL, just trying to mediate issues I have seen with other applications using SDL2.

I narrowed the issue down last night. It happens when the applications enabled additional features in the PS5 controller. Reading up, it is something about the Bluetooth connection changing, and things like xinput no longer being able to recognise the inputs until the controller is rebooted. 

So - annoying as it is, does not sound like it is an SDL issue,

**Comment by AntTheAlchemist** [comment]
When an application enables extended inputs so it can use features like rumble, it switches the game controller's mode, which can only be switched back by rebooting the controller. This disables Xinput/DirectInput. So games (or Windows control panel) that only support that mode will stop working. It's a feature :)
