### ISSUE TITLE
SDL2 issues with Wayland fractional scaling

### ISSUE THREAD

**Issue by robotman2412** [libsdl-org/SDL#9958]
I'm using SDL2.30.3 with a little application to test a GUI library I'm making (https://github.com/robotman2412/pax-sdl-testing).
However, I am seemingly unable to make it work with HIGH-DPI / scaling when I use Wayland's 150% fractional scaling. It works fine with 200%, but that makes my desktop look tiny.

Is this a limitation of Wayland, SDL2, or am I doing something wrong?

**Comment by Kontrabant** [comment]
Your code is calling `SDL_GetWindowSurface()` after creating a renderer on the window, but the surface retrieval function states:
>You may not combine this with 3D or the rendering API on this window.

It doesn't seem like you are using the renderer for anything but getting the backbuffer size, in which case you should eliminate the creation of the renderer and replace the calls to `SDL_GetRendererOutputSize` with  `SDL_GetWindowSizeInPixels`. If I modify your code to not create the renderer and use the latter function to query the buffer size, everything seems to work correctly.

**Comment by robotman2412** [comment]
I've changed my code accordingly, but I still get blurry results with fractional scaling.

**Comment by Kontrabant** [comment]
Just to check, you are running with the Wayland video driver (`SDL_VIDEODRIVER=wayland`), correct?  XWayland will give blurry results when scaled. I ask because your test app was initially segfaulting for me under Wayland due to a null surface being returned until the renderer was removed, but still ran under XWayland.

**Comment by robotman2412** [comment]
No, I apparently wasn't. This has fixed the fractional scaling (is there a way to do this in C? Or do I just add it to `~/.bashrc`?) but there is a new problem: The window decorations have removed themselves.

**Comment by Kontrabant** [comment]
GNOME based desktops need libdecor installed for SDL to show decorations on Wayland. Your distro's package manager should have it available.

**Comment by Kontrabant** [comment]
To set the hint in C, you can use `SDL_SetHint(SDL_HINT_VIDEODRIVER, "wayland")`.

**Comment by robotman2412** [comment]
Strange. I'm running Ubuntu 20.04 and have `libdecor-0-0` already installed. I'll try restarting my computer tomorrow, see if that does anything.

**Comment by Kontrabant** [comment]
Are you using SDL from your distro repos, or did you build it yourself? In the latter case, you need the libdecor-dev package (maybe called libdecor-0-dev on Ubuntu) installed when building SDL, or libdecor support will be disabled.

**Comment by robotman2412** [comment]
That'll do it. Recompiled SDL after installing `libdecor-0-dev` and the window decorations don't exactly match my OS' theme but at least they're there.

**Comment by robotman2412** [comment]
Do you happen to know how to make libdecor use the OS' theme?

**Comment by Kontrabant** [comment]
You need a new enough version built with the GTK backend. The GTK backend was only enabled fairly recently, so the packages in your older LTS distro might be too old. The alternative is to build it yourself.

It's hosted on the freedesktop gitlab, which is down for the next couple of days for maintenance and upgrades though.

**Comment by robotman2412** [comment]
I noticed it was down. Looks like I'm building even more packages from source. One of these days, I will find the time to switch my laptop, too, to Arch so I don't have years old packages all the time...

**Comment by estrac** [comment]
In case it helps someone, I had issues with fractional scaling on Wayland, and when I ran `SDL_SetHint(SDL_HINT_VIDEODRIVER, "wayland")`, SDL2 could not set up the OpenGL context with Glew. I was able to get my app running with fractional scaling (crisp fonts) on Wayland by linking to Glew built from source with EGL enabled (make SYSTEM=linux-egl).

**Comment by griffi-gh** [comment]
i have the opposite issue... the app's a blurry mess with the Wayland videodriver but looks fine under Xwayland

**Comment by Reonu** [comment]
> i have the opposite issue... the app's a blurry mess with the Wayland videodriver but looks fine under Xwayland

Have you found a solution to this? We're having the same issue: Our SDL2 game looks fine with xWayland, but with native Wayland it's blurry when using fractional DPI scaling and the window size is wrong.
