### ISSUE TITLE
SDL2: Xbox controller with wrong mappings?!

### ISSUE THREAD

**Issue by lassade** [libsdl-org/SDL#9975]
Hi I have a wireless Xbox Controller with that have the following mapping assigned by default

0300938d5e040000ff02000000007200,*,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,crc:8d93,platform:Windows

The problem is that some buttons are worng:
- leftshoulder triggers back
- rightshoulder triggers guide
- leftstrick triggers rightstrick
- rightstrick triggers leftshoulder
- start triggers leftstrick
- back triggers start

I tried to use `SDL_GameControllerAddMapping` with a custom mapping with the buttons swapped but it didn't change anything.

Edit

Using the SDL2 Gamepad Tool I got the following mapping string: 030000005e040000ff02000000007801,Xbox Wireless Controller,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,

It doesn't work even if I change the guid to match. not sure what's happening

Edit2

using `SDL_GameControllerGetBindForButton(gamepad, SDL_CONTROLLER_BUTTON_LEFTSHOULDER)` results in `SDL_CONTROLLER_BUTTON_BACK` but if I use a PS4 controller it will give the left shoulder

**Comment by AntTheAlchemist** [comment]
Hi @lassade ,

That mapping looks right. The mapping string you generated with the Gamepad Tool looks the same as the default one, which is why it didn't change anything.

When you pressed the left shoulder in the Gamepad Tool, it produced the correct scancode and mapped it as expected. Something seems to be changing the behaviour of your app? I suspect that if you used your controller in any other SDL app, it would be mapped ok?

**Comment by lassade** [comment]
It work as expected, I also played Hades from Supergiant Games without any problems with it.

I have a very cursed workaround that uses `SDL_GameControllerGetBindForButton` that I use undo (or do) the binding like so:
```
// I think this is a valid c code, I'm acctually using zig :P
// reset binds
for(int i = 0; i < SDL_CONTROLLER_BUTTON_MAX) {
    binds[i] = i;
}
// de-map binds
for(int i = 0; i < SDL_CONTROLLER_BUTTON_MAX) {
    bind = SDL_GameControllerGetBindForButton(i);
    if (bind.bindType) binds[bind.value.button] = i;
}
```

**Comment by slouken** [comment]
Oh, yeah, `SDL_GameControllerGetBindForButton(gamepad, SDL_CONTROLLER_BUTTON_LEFTSHOULDER)` will give you a button index, not another gamepad button. You generally shouldn't be using the functions to look up bindings, they won't provide you with anything useful unless you're building a gamepad binding application.

Take a look at https://github.com/libsdl-org/SDL/blob/main/test/testcontroller.c for a complete example of using the SDL gamepad API.

**Comment by slouken** [comment]
If you need more help, try asking on the SDL forums:
https://discourse.libsdl.org/c/sdl-development/6
