### ISSUE TITLE
SDL_JOYSTICK_DISABLED breaks Android build with a linker error

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#9978]
I'm working on #9947 and discovered this and don't know how to fix it. The other `SDL_*_DISABLED` defines seem to be working, but not this one.  I get the following link error:

```
ld: error: undefined symbol: SDL_DUMMY_JoystickDriver
>>> referenced by SDL_joystick.c
```

**Comment by madebr** [comment]
I see `SDL_DUMMY_JoystickDriver` here:
https://github.com/libsdl-org/SDL/blob/26fc7a80601046a4c1e91ffc407fccd694cdefa4/src/joystick/SDL_joystick.c#L106-L108

**Comment by sezero** [comment]
If this is with Android.mk, it does seem to be missing src/joystick/dummy/*.c

**Comment by slouken** [comment]
Fixed!
