### ISSUE TITLE
Crash with SDL_EVENT_GAMEPAD_REMOVED [[repro inside]]

### ISSUE THREAD

**Issue by bjadamson** [libsdl-org/SDL#9996]
```C++
#include <external/sdl_full.hpp>
#include <cassert>
#include <cstdlib>
#include <cstdio>

void
add(SDL_JoystickID const id)
{
  assert(::SDL_IsGamepad(id));  // # NOTE: This does not assert!
  printf("Joystick %d added\n", id);

  assert(::SDL_OpenGamepad(id)); // # NOTE: I added this after the first comment from @AntTheAlchemist  below
}

void
remove(SDL_JoystickID const id) 
{
  printf("Joystick %d removed\n", id);
  assert(SDL_TRUE == ::SDL_IsGamepad(id)); // # CRASH #1

  SDL_Gamepad* data = ::SDL_GetGamepadFromInstanceID(id);
  assert(data); // # CRASH #2

  assert(SDL_TRUE == ::SDL_GamepadConnected(data));
  ::SDL_CloseGamepad(data);
}

void
poll_events(bool& quit)
{
  for (SDL_Event event; ::SDL_PollEvent(&event);)
  {
    switch (event.type)
    {
      case SDL_EVENT_QUIT:
        quit = true;
        break;

      case SDL_EVENT_GAMEPAD_ADDED:
        add(event.gdevice.which);
        break;

      case SDL_EVENT_GAMEPAD_REMOVED:
        remove(event.gdevice.which);
        break;
    }
  }
}

int
main(int, char**)
{
  ::SDL_Init(SDL_INIT_TIMER | SDL_INIT_EVENTS | SDL_INIT_GAMEPAD | SDL_INIT_VIDEO);
  ::SDL_ClearError();

  bool quit = false;
  while (!quit)
  {
    poll_events(quit);
  }
  return EXIT_SUCCESS;
}
```

Hi, this program crashes on windows after plugging in / removing a controller. It also crashes when removing a controller, if the program is started with a controller already plugged in.

Is this expected? As I understand it the GAMEPAD_REMOVED event is supposed to give my application a chance to respond to the event before the system removes the gamepad, but on windows using both an xbox360 or xbox one controller the above program crashes on the two lines marked above when my gamepad is removed.

Please let me know if I'm missing something. I boiled this down to the simplest program I can think of, but let me know if more information is needed.

edit: I verified the SDL_JoystickID is the same in both events.

**Comment by bjadamson** [comment]
How can I modify this to not  complain about signed/unsigned mismatch?

template <typename A, typename... Args>
bool constexpr
any_equal_first([[maybe_unused]] A&& head, Args&&...tail) noexcept
{
  return (... || (head == tail));
}

**Comment by AntTheAlchemist** [comment]
I'm using `SDL_GetGamepadFromInstanceID` on `SDL_EVENT_GAMEPAD_REMOVED` without a crash using the latest SDL3 source. Which version of SDL are you using?

I've found none of the Gamepad functions return anything useful during the `SDL_EVENT_GAMEPAD_REMOVED` event. `SDL_IsGamepad` even returns false (because it decides based on if the Gamepad has mapping, which will be false because the GUID is zeroed out at this point), which is very misleading - maybe this should be considered a bug at least. `SDL_GetGamepadInstanceName` will return null. `SDL_GetGamepadFromInstanceID` DOES work though, and returns a valid pointer. 

Just to clarify: when you say crash, do you mean assertion fail?

If you've not done a `SDL_OpenGamepad`, then that might be why you're getting null from `SDL_GetGamepadFromInstanceID`?

So, yes, you're not opening a Gamepad. "Get the SDL_Gamepad associated with a joystick instance ID, if it has been opened." is what `SDL_GetGamepadFromInstanceID` says.

**Comment by bjadamson** [comment]
> If you've not done a SDL_OpenGamepad, then that might be why you're getting null from SDL_GetGamepadFromInstanceID?

Sorry, that was a mistake when I reduced the program from my actual program to the example code above. I am indeed calling SDL_OpenGamepad(id) in the add() function. I've updated the original example program to include this now.

> Just to clarify: when you say crash, do you mean assertion fail?

Yes.

**Comment by bjadamson** [comment]
I took a [video](https://www.youtube.com/watch?v=b3gRUaXSYJk&list=PL1mxi1CLAl9GlujOB8yxsnL5tF4usvn3X&index=7) running the program  -- I don't know if it provides more information than the code does, but it's here if it will help.

**Comment by AntTheAlchemist** [comment]
Yes, I'm on Windows 10. 

`SDL_IsGamepad` on an open Gamepad does return false, after `SDL_EVENT_GAMEPAD_REMOVED`, which I think is kind of a bug, or misleading at worst. A Gamepad loses mapping when it's removed, so it becomes invalid for anything useful. 

Moving passed "CRASH #1", can you now double-check if `SDL_GetGamepadFromInstanceID` is returning null or not?

**Comment by bjadamson** [comment]
> Moving passed "CRASH https://github.com/libsdl-org/SDL/issues/1", can you now double-check if SDL_GetGamepadFromInstanceID is returning null or not?

Tested, and it does not return null, BUT SDL_GamepadConnected is returning false.
![image](https://github.com/libsdl-org/SDL/assets/1087837/49cc2715-4fea-4c2f-b765-fffc57336938)


That's happening because it's being set to FALSE in SDL_PrivateJoystickRemoved

![image](https://github.com/libsdl-org/SDL/assets/1087837/ab4c60d3-6ecf-4378-a77f-bcee4405627b)


This happens directly from the windows event removing the controller:
![image](https://github.com/libsdl-org/SDL/assets/1087837/1c36b51a-4300-411c-9596-a6e47994d4f2)

**Comment by AntTheAlchemist** [comment]
I would expect `SDL_GamepadConnected` to return false if it's been unplugged?

**Comment by bjadamson** [comment]
> SDL_IsGamepad on an open Gamepad does return false, after SDL_EVENT_GAMEPAD_REMOVED, which I think is kind of a bug, or misleading at worst. A Gamepad loses mapping when it's removed, so it becomes invalid for anything useful.

I just wanted to respond to this, I feel like it's invalid in the sense that the way I understand it works is that I'm supposed to receive the event before the system does anything to my controller.

**Comment by AntTheAlchemist** [comment]
It's okay, you're raising valid questions here. I don't believe there is any way to "catch" a Gamepad before it's been physically disconnected. It will always be too late to do anything with a Gamepad after it's removed.

**Comment by bjadamson** [comment]
> It's okay, you're raising valid questions here. I don't believe there is any way to "catch" a Gamepad before it's been physically disconnected. It will always be too late to do anything with a Gamepad after it's removed.

Okay, that's just a misunderstanding on my part. Thanks!

**Comment by AntTheAlchemist** [comment]
> Okay, that's just a misunderstanding on my part. Thanks!

I'm glad we were able to figure it out.  Do you think there is a way to clarify this for other users in the documents somewhere?

**Comment by bjadamson** [comment]
> > Okay, that's just a misunderstanding on my part. Thanks!
> 
> I'm glad we were able to figure it out. Do you think there is a way to clarify this for other users in the documents somewhere?

Yeah, I do think just adding some documentation to the event itself stating that once the event has been received by the application it has already been "disconnected." Specifically calling on SDL_GamepadConnected() on the id is either expected to return false, or undefined behavior (idk, maybe another controller gets plugged at the exact right time).

**Comment by AntTheAlchemist** [comment]
@slouken The only issue here is a misunderstanding of what's possible after a `SDL_EVENT_GAMEPAD_REMOVED`, and that `SDL_IsGamepad` always returns false after a removed Gamepad. Is this considered a bug? Shall we keep this issue open?

**Comment by AntTheAlchemist** [comment]
> Specifically calling on SDL_GamepadConnected() on the id is either expected to return false, or undefined behavior (idk, maybe another controller gets plugged at the exact right time).

I believe the instance ID remains valid until you close the Gamepad. And I believe if the gamepad was never opened, though, then the ID will be invalid after you return from handling the removed event.

**Comment by bjadamson** [comment]
> > Specifically calling on SDL_GamepadConnected() on the id is either expected to return false, or undefined behavior (idk, maybe another controller gets plugged at the exact right time).
> 
> I believe the instance ID remains valid until you close the Gamepad. And I believe if the gamepad was never opened, though, then the ID will be invalid after you return from handling the removed event.

That's super clear. Thanks.

I would like to add, it does seem very unclear that I cannot query if a joystick ID was a gamepad in the `SDL_EVENT_GAMEPAD_REMOVED` event -- I mean it's right there in the name of the event, it's a gamepad event!

**Comment by slouken** [comment]
I have a fix for SDL_IsGamepad() so it will return true even after the controller was disconnected.

With this change, if you also make the following change to your code, it will work as expected:
```c
assert(SDL_FALSE == ::SDL_GamepadConnected(data));
```

**Comment by bjadamson** [comment]
Wow you work quick! Thanks. 👍

**Comment by slouken** [comment]
You're welcome! :)
