### ISSUE TITLE
Unnecessary CMake re-configures triggered by git history changes

### ISSUE THREAD

**Issue by Ravbug** [libsdl-org/SDL#9998]
It appears that SDL is creating CMake dependencies on data inside my git history:
```
1>------ Build started: Project: ZERO_CHECK, Configuration: debug x64 ------
1>1>Checking Build System
1>CMake is re-running because C:/Users/Ravbug/source/repos/RavEngine-Samples/build/win/RavEngine/deps/SDL/CMakeFiles/generate.stamp is out-of-date.
1>  the file 'C:/Users/Ravbug/source/repos/RavEngine-Samples/.git/modules/RavEngine/refs/heads/master'
1>  is newer than 'C:/Users/Ravbug/source/repos/RavEngine-Samples/build/win/RavEngine/deps/SDL/CMakeFiles/generate.stamp.depend'
```
This triggers unnecessary re-configures whenever something inside git changes. What is creating these dependencies? Is it possible to disable this?

**Comment by slouken** [comment]
I’ve noticed this too. @madebr, do you know what’s going on?

**Comment by madebr** [comment]
This is expected.

SDL built from git embeds the git hash through `SDL_revision.h.cmake`, which needs to be regenerated on each git change.

You can override this by configuring with `-DSDL_REVISION=blabla`.

**Comment by slouken** [comment]
Ah, thanks!
